### ISSUE TITLE
Molten Redstone Alloy attainable in an LV fluid extractor via nuggets

### ISSUE THREAD

**Issue by enki1337** [GTNewHorizons/GT-New-Horizons-Modpack#10009]
### Your GTNH Discord Username

pleinair#2040

### Your Pack Version

2.1.2.2QF2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

You probably shouldn't be allowed to do this

### The Reality

You can do this

### Your Proposal

Change nugget recipe to require MV

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Duplicate of #9092
