### ISSUE TITLE
Allow changing machine input mode without access to the front

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#10004]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.1.2.0

### Your Proposal

With the new defaults of GT machines often being at odds with automation, it should be easy to correct the machine's mode to the value it had in previous pack versions, i.e. Input filter on, multi-stack input off.

Currently this can only be achieved by shift-right clicking the front of the machine with a screwdriver.

This face is not always accessible, and particularly for efficiently packed setups *can't* be made accessible without having to break nearby plumbing. The front is the most useless side, and generally tends to face away to make the functional sides accessible to the player.
Placing a row of machines for instance will now take minutes instead of a seconds. You have to place the first machine, wait for it to "form", before you can shift-right click it and then place the next machine in the row against it that would have prevented the necessary modifications. 

**Therefore, I want the shift-right clicking functionality to work on any side**. Of course assuming the side in question has no other functionality for shift-clicks, like having a cover or being the output side.

### Your Goal

This is for builder quality of life, and reducing unnecessary wait times *placing* blocks.

Placing a mere 8 electrolysers took 2 minutes on Delta due to the current limitation. That would have been less than 10 seconds with the proposed improvement.

### Your Vision

Bad UX should go away.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
I believe you can also use the screwdriver on the output side, so with a wrench and a screwdriver you can do what you wish for without making any changes.
