### ISSUE TITLE
Assembler recipe for JABBA's Better Barrel does not use oredict correctly

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#10005]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Based on what I'm seeing in the recipes, I should be able to use any stacks of wood planks as long as they have the plankWood oredict entry

### The Reality

Some planks are missing, notably Thaumcraft's Greatwood planks (possibly Silverwood planks too).

### Your Proposal

Fix the recipes so that only one recipe is needed that calls the plankWood oredict correctly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
Other missing planks:
- Barnarda C Wood (Galaxy Space)
- Warpwood (Tainted Magic)
- Towerwood, Twilight Oak, Canopy, Mangrove, Darkwood, Timewood, Transwood, Minewood, Sortingwood (The Twilight Forest)
- Wood (GregTech)
- Nether Wood (Pam's Harvest the Nether)
- Ender Wood (Thaumic Bases)
- Rowan, Alder, Hawthorn (Witchery)

**Comment by TwoTailedFox** [comment]
Any update on this one being looked into?

**Comment by BritishCynic** [comment]
Issue persists in 2.2.7
