### ISSUE TITLE
Obsidian Stick is uncraftable

### ISSUE THREAD

**Issue by NexusNull** [GTNewHorizons/GT-New-Horizons-Modpack#10011]
### Your GTNH Discord Username

NexusNull#6364

### Your Pack Version

2.1.2.3qf

### Your Server

private Server

### Type of Server

Vanilla Forge

### Your Expectation

Crafting a Obsidian stick returns the correct item.

### The Reality

Crafting the Obsidian Stick (# 9993/1) isn't possible. The recipe exists, however when trying to craft it the result is always an Obsidian Rod (# 6954/23804).

### Your Proposal

Remove the recipes that result obsidian sticks and add one from the lathe or extruder instead. This was also proposed in this issue  #5236 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NexusNull** [comment]
Apparently you can craft the the stick in a normal crafting table.

**Comment by chochem** [comment]
ah I see, you also want it closed because its in error. sorry about that

**Comment by NexusNull** [comment]
yeah no worries, thanks for your work.

**Comment by NexusNull** [comment]
Although, the thing is when you craft the obsidian sticks in the tc crafting table it turns into the wrong type. I dunno if that's worth fixing.

**Comment by ChaoticTabris** [comment]
Having the same issue. People on Discord say it's something that people ask from time to time. I think the problem is that different people will get different recipes initializing first. For me using a vanilla Crafting Table didn't fix it, neither using a Crafting Terminal. The workaround I found was to use a Worktable from Forestry, they have a built in fix for recipe conflicts (You can choose the output you want)

**Comment by chochem** [comment]
looks like a recipe conflict yea
