### ISSUE TITLE
Visual glitch with buckets and water tank from Railcraft

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#10014]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Get one or few stacks of buckets, fill all buckets from rail tank, open the inventory. Game will only show buckets which are on the tools panel and will hide others up until you'll come to a chest or worktable and click on it, only after it you'll see other buckets

https://user-images.githubusercontent.com/29717217/159571350-19c94a6b-af2a-4af8-8672-63ade8c977fb.mp4

### The Reality

null

### Your Proposal

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Minepolz320** [comment]
This is really annoys me someone missed the inventory update method
