### ISSUE TITLE
Precise assembler dont eat circuits

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#10026]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Expected assembler in normal mode to work properly

### The Reality

![image](https://user-images.githubusercontent.com/39595617/159905439-a4f697ec-bd87-4009-83cd-1df73447c539.png)
this is what is left in bus after making mv field generator
![image](https://user-images.githubusercontent.com/39595617/159905555-690affe5-c5a1-4165-bf45-33361bc6a135.png)
ZPM circuits from iv gen wasnt consumed too

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
will be fixed by https://github.com/GTNewHorizons/bartworks/pull/110
