### ISSUE TITLE
Charcoal Pile Igniter not correctly showing "Incomplete Structure" error

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#10027]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The Charcoal Pile Igniter is supposed to check all appropriate blocks for whether or not it is a valid structure

### The Reality

The Charcoal Pile Igniter appears to only be checking the dimensions are valid rather than the constituent blocks. Replacing dirt with sand, for example, fails to trigger the "Incomplete Structure" error message.

### Your Proposal

Have the logic of the block changed to check both dimensions and blocks themselves for validity to ensure accurate error reporting.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Speiger never released the source. Will probably need a mixin.
