### ISSUE TITLE
Iron Duping in Disassembler

### ISSUE THREAD

**Issue by MeiTianyou** [GTNewHorizons/GT-New-Horizons-Modpack#10020]
### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Disassembling a railcraft 'low pressure boiler tank' should return 6 iron casings, since that's the assembler recipe.

### The Reality

Disassembly returns 6 iron casings and two screws, which is the crafting table recipe.

### Your Proposal

Change which recipe the disassembler reverses.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by cubic-chariot** [comment]
Macerating the tank down also gives 29 tiny iron dusts, which is enough to get 6 iron casings with two tiny dusts leftover. The same thing happens with the High Pressure Boiler Tank, allowing steel duplication.

**Comment by miozune** [comment]
Disassembler is fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1035
