### ISSUE TITLE
Assembly line recipe persistant hash for GT++ molecular transformer

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#10024]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Make the controller block for the molecular assembler for GT++ in the assembly line using the datastick.

### The Reality

Controller block is made, but gregtech.log spams
`Assline recipe persistent hash has not been set! Recipe: 1xgt.blockmachines@31072`

which is

`META 31072 moleculartransformer.controller.tier.single`

### Your Proposal

This is similar to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9606 however the datastick is not made in the TT research station.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eranicus** [comment]
I can confirm, same story with elemental dublicator blocks with data stick receipts (probably all of new 3qf gt++ blocks) spam log non-stop with errors. I simply removed every Gt++ data stick from my data bank to stop the spam.
