### ISSUE TITLE
Item filter cover not filtering item pipe output

### ISSUE THREAD

**Issue by ivanpu** [GTNewHorizons/GT-New-Horizons-Modpack#10038]
### Your Pack Version

2.1.2.0 (I've verified that it still happens in 2.1.2.3QF)

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

All machines/covers are of LV-tier.
1. My setup (covers: 1st robot arm on washer exports [output 1] into forge hammer, 2nd arm on washer exports [output 2] into pipes, 3rd arm on a pipe near washer imports [output 3] into the a pipe, "item filter (export)" on a pipe before the chest):
![2022-03-26_00 41 56](https://user-images.githubusercontent.com/2607888/160205900-8d0a9f06-a812-4b69-936e-e5fcbda0d2af.png)
2. Item filter configuration (export, blacklist stone dust):
![2022-03-26_00 42 17](https://user-images.githubusercontent.com/2607888/160205965-84ed998d-ed44-44fc-bc6a-bc9e299699cc.png)
3. I'm expecting that stone dust will be put into the connected barrel.

### The Reality

Stone dust is dumped into the chest, despite the filter.

### Your Proposal

Make item filter to block exporting of the blacklisted item.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
The item filter unfortunately does not filter output (due to a technical difficulty). It really should have been named filtered converyor cover instead. Since it's never supposed to do this, marking this as a suggestion now.

**Comment by ivanpu** [comment]
Ok, fair enough.
Fortunately I've just unlocked the Project Red quest line.
