### ISSUE TITLE
Change opencomputers RITEG upgrade to use 1 complexity rather than 3

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#10039]
### Your GTNH Discord Username

KiloJoel#3044

### Your Pack Version

2.1.2.3QF

### Your Proposal

The absolute basic setup for a microcontroller which moves items and can interact with redstone requires 3 complexity.
Tier 2 Microcontrollers have a max complexity of 5.
The RITEG upgrade adds 3 complexity.
This means that for most use cases, the riteg upgrade can only be used for tier 3 microcontrollers, which require UV circuits.
![image](https://user-images.githubusercontent.com/17787093/160213491-9a0b63f4-e788-4e07-ae56-6d2b868700de.png)

I propose it should have 1 complexity to make it compatible with tier 2 microcontrollers with 1 additional card.

### Your Goal

Since the RITEG upgrade is expensive to make in itself, and is essentially a QoL upgrade, I don't think this additional gating is necessary.

### Your Vision

Make the RITEG upgrade useable outside of lategame.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by KiloJoel** [comment]
For those who don't know, the RITEG upgrade provides a small amount of power, removing the need to connect a microcontroller to a power cable.

**Comment by Glease** [comment]
Yes we should definitely do that. Just noticed this myself as well. Complexity 3 makes the whole thing too expensive, and sometimes just impossible.
