### ISSUE TITLE
acquiring alumnium quest info inaccurate

### ISSUE THREAD

**Issue by piantgenis** [GTNewHorizons/GT-New-Horizons-Modpack#10037]
### Your GTNH Discord Username

piant genis#0358

### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

accurate information about the updated aluminium line

### The Reality

![image](https://user-images.githubusercontent.com/102388079/160196521-953c8e20-9ae0-4517-b146-fe5732f46433.png)
quest #1866 is inaccurate about updated aluminium tree. it says you can electrolyze sapphire dusts for aluminium but you cant

### Your Proposal

update the quest to contain accurate info

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by joshaup1999** [comment]
Should change electrolyse to ebf. Since it’s an ebf process now
