### ISSUE TITLE
Crop Manager doesn't check if the items are fertalizer or weed-ex

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#10035]
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.2.3qf

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Make Crop Manager for my crop needs

### The Reality

The Crop Manager doesn't actually check if it's fertalizer or weed-ex, it just checks the slot where the items are at, and if there is any, consume item and apply effect

### Your Proposal

Is a rocket a fertilizer? Perhaps some plutonium 241?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Just tried in dev env you cannot actually put non fert/weedex in those slots. Doubt how you did that..

**Comment by ScriptedPiky** [comment]
You have to shift click what you want inside of it, heh whoops forgot to mention that
