### ISSUE TITLE
Cells destroyed by EnderIO Tanks

### ISSUE THREAD

**Issue by VermillionX** [GTNewHorizons/GT-New-Horizons-Modpack#1003]
Water cells when used in EnderIO tanks are consumed instead of yielding an empty cell, unlike any other fluid cell where you get an empty cell back.
This also happens when attempting to fill railcraft tanks with water cells as well.

**Comment by Ugachaga** [comment]
Perhaps intended, like 
```
    # Enables emptying vanilla water bottles without breaking the bottle. In combination with a water source block this allows duping of water without cost.
    B:enableWaterFromBottles=true
```

**Comment by VermillionX** [comment]
They default to IC2 ones, so those. I don't think GT actually has a water cell.

**Comment by meonester** [comment]
@Dream-Master Water cells, IC2Coolant cells, distilled water cells, compressed air cells. Same thing happens while used on Extra Utils drums.

**Comment by Dream-Master** [comment]
I guess there is nothing i can do. @Technus any idea?
