### ISSUE TITLE
Crash to menu loading singeplayer world

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#10046]
### Your GTNH Discord Username

KiloJoel#3044

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I went from singleplayer to a server, then back to singleplayer. Game crashed 2 seconds into loading singeplayer world and did every time after. Relaunching pack seems to have sorted it for now.

### Crash Report

[Stacktrace.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8357711/Stacktrace.txt)

Full log here if needed
[fml-client-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8357716/fml-client-3.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
This is known as the "ancient GC cannot register world" bug. Surprisingly it doesn't yet have a tracking issue...
