### ISSUE TITLE
Server crashes on launch, gregtech initialization fails

### ISSUE THREAD

**Issue by jkstenzel95** [GTNewHorizons/GT-New-Horizons-Modpack#10042]
### Your GTNH Discord Username

Sylarsun#1114

### Your Pack Version

2.1.2.0

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Actions

// Below is in bash, ignore incorrect // comment syntax
// Super summarized version of what this repo is accomplishing: https://github.com/jkstenzel95/jks.gameservers/tree/main/shared/scripts
// Running Dockerized in Amazon Kubernetes on Amazon AMI ami-093d9796e55a5b860 (Amazon Linux 2, based on Red Hat Enterprise Linux), on a c6i.8xlarge instance

// Every other Minecraft modpack (pixelmon and greedycraft) work as expected.

yum install nano jq unzip vim wget tar python3 glibc.i686 libstdc++.i686 ncurses-libs.i686 sudo -y
echo "fs.file-max=100000" >> /etc/sysctl.conf
echo -e "* soft nofile 1000000\n* hard nofile 1000000" >> /etc/security/limits.conf

sudo yum update -y
sudo yum install java-1.8.0-openjdk -y
sudo tee /etc/profile.d/jdk.sh <<EOF
export JAVA_HOME=/opt/jdk-17
export PATH=\$PATH:\$JAVA_HOME/bin
EOF

// Download and unzip GTNewHorizonsServer-1.7.10-2.1.2.0.zip

java -Xmx6G -Xms2G -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar --port 25569 nogui

// Fix eula

java -Xmx6G -Xms2G -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar --port 25569 nogui

// Cannot reproduce on my Ubuntu subsystem for Linux! Server runs fine there. Same java version.

### Crash Report

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8354697/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
You have too few CPU cores that it errs out. I'm not exactly sure why this still happens in 2.1.2.0. It should have been fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/802. Anyway, try at least upgrade to 2.1.2.1. 2.1.2.0 is not that stable after all/

**Comment by jkstenzel95** [comment]
The issue occurs in 2.1.2.3 as well. I've attached a log again. This is odd and might be worth digging into I think, the c6i.8xlarge isn't a weak machine, and RAM here was allocated in a way that provides some RAM overhead beyond the recommended arguments (no specifications on vCPU limits). AWS hosting of a GT New Horizons server is also a fairly common use scenario I imagine. Could that one change/issue you mentioned be revisited in light of this, should that seem to be the issue?
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8360048/fml-server-latest.log)

**Comment by Glease** [comment]
This is weird. Can you try compile and run this very short java class with openjdk 8 or something? What's its output on your problematic VM?
```java
public class Main {
	public static void main(String[] args) {
		System.out.println(Runtime.getRuntime().availableProcessors());
		System.out.println(Math.min(8, Math.max(1, Runtime.getRuntime().availableProcessors() * 2 / 3)));
	}
}
```

```bash
$ javac -version
$ java -version
# make sure they both show 1.8.0_XXX
$ javac Main.java
$ java Main
```

**Comment by bombcar** [comment]
`export JAVA_HOME=/opt/jdk-17`

This is very suspect.

**Comment by bombcar** [comment]
I wonder what happens if Java8 is run with a Java 17 home?

**Comment by jkstenzel95** [comment]
@Glease @bombcar Apologies, I actually misread my own code there. That export line only happens if I specify a modpack uses JDK 17, while this uses JDK 8. Here are links to my [JDK installation code](https://github.com/jkstenzel95/jks.gameservers/blob/main/shared/scripts/init/Minecraft/install-jdk.sh) and the [code for starting the server](https://github.com/jkstenzel95/jks.gameservers/blob/main/shared/scripts/runtime/Minecraft/start-map.sh) (config this all uses is [here](https://github.com/jkstenzel95/jks.gameservers/blob/main/shared/data/minecraft_mappings.json)). I've fixed the above code summary to reflect this.

As requested, code output is as follows (after creating Main.java as requested):

bash-4.2# javac -version
bash: javac: command not found
bash-4.2# java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
bash-4.2# javac Main.java
bash: javac: command not found
bash-4.2# java Main
Error: Could not find or load main class Main
bash-4.2# java Main.java
Error: Could not find or load main class Main.java

Interestingly, javac is not detected. Wondering if there's some weirdness about java-1.8.0-openjdk and javac.

Also, $JAVA_HOME is unset:

bash-4.2# echo $JAVA_HOME
<blank line>

I wonder why the jdk installation seems half-baked. Seems I'm following instructions [here](https://access.redhat.com/documentation/en-us/openjdk/8/html-single/installing_and_using_openjdk_8_for_rhel/index)

**Comment by jkstenzel95** [comment]
Interesting - The host VM reaches this line eventually:
[FML]: Unloading dimension 1
...which I assume means it made it past the problem. Tried separately on two different instances of the same type, one with java-1.8.0-openjdk installed, one with java-1.8.0-openjdk-devel
