### ISSUE TITLE
Add Assembler recipes for StorageDrawers upgrades

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#10045]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Proposal

To add assembler recipes for the upgrades

### Your Goal

To make StorageDrawers a more attractive mod to produce upgrades for

### Your Vision

To bring a little more parity to StorageDrawers compared to JABBA.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TwoTailedFox** [comment]
Could this be looked into further? I feel this would make Drawers worth crafting a lot more.

**Comment by TwoTailedFox** [comment]
The following recipes should be added for this:

3 x Upgrade Template + 5 x [plateIron] + 1 x [stickIron] = Storage Upgrade (II)
3 x Upgrade Template + 1 x [plateSteel] + 4 x [plateGold] + 1 x [stickGold] = Storage Upgrade (III)
3 x Upgrade Template + 1 x [plateAkuminium] + 4 x [plateObsidian] + 1 x [stickObsidian] = Storage Upgrade (IV)
3 x Upgrade Template + 1 x [plateStainlessSteel] + 4 x [plateDiamond] + 1 x [stickDiamond] = Storage Upgrade (V)
3 x Upgrade Template + 1 x [plateTitanium] + 4 x [plateEmerald] + 1 x [stickEmerald] = Storage Upgrade (VI)
1 x Upgrade Template + 2 x Redstone Torch + 4 x Red Alloy Wire + 2 x [plateRedstone] = Status Upgrade (I)
1 x Upgrade Template + 2 x Comparator + 4 x Red Alloy Wire + 2 x [plateRedstone] = Status Upgrade (II)
1 x Upgrade Template + 2 x [plateDenseObsidian] + 4 x [stickWood] + 2 x Red Alloy Wire = Void Upgrade
1 x Upgrade Template + 4 x [plateRedstone] + 3 x [stickWood] + 1 x Red Alloy Wire = Redstone Upgrade
1 x Upgrade Template + 3 x [plateRedstone] + 4 x [stickWood] + 1 x Red Alloy Wire = Redstone Max Upgrade (needs circuit)
1 x Upgrade Template + 3 x [plateRedstone] + 4 x [stickWood] + 1 x Red Alloy Wire = Redstone Min Upgrade (needs circuit)
1 x Upgrade Template + 2 x [plateSteel] + 1 x [stickGold] + 1 x [boltGold] + 1 x [plateGold] = Drawer Key
1 x [drawerBasic] + 2 x [plateStainlessSteel] + 1 x [circuitGood] + 1 x Comparator + 1 x [plateDiamond] + 2 x [plateObsidian] = Drawer Controller
1 x [drawerBasic] + 2 x [plateStainlessSteel] + 1 x [circuitGood] + 1 x Comparator + 1 x [plateEnderEye] + 2 x [plateObsidian] = Controller Slave
3 x [Oak Trim,Sprice Trim,Birch Trim,Jungle Trim,Acacia Trim,Dark Oak Trim] + 4 x [fenceWood] + 1 x [stickWood] = Framing Table

The Framing Table recipe might benefit from the Trim blocks being included in Oredict (perhaps with something like drawerTrim)

**Comment by BritishCynic** [comment]
Any update on this one?

**Comment by Ethryan** [comment]
You could always create a pull request at gtnhcore and add the recipes.
