### ISSUE TITLE
The process: H2O+S+O2 =H2SO4 in large chemical reactor can run without S in input bus.

### ISSUE THREAD

**Issue by WTWTWTWTWTWT** [GTNewHorizons/GT-New-Horizons-Modpack#10044]
### Your GTNH Discord Username

WTWTWTWTWTWT

### Your Pack Version

2.1.2.3

### Your Server

SP

### Your Expectation

It's a important bug which can affect my game,it's really need to be solved.

### The Reality

The process: H2O+S+O2 =H2SO4 in large chemical reactor can run without S in input bus.

### Your Proposal

Fix this bug in as soon as possible.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/967
