### ISSUE TITLE
Massive log spam from SGCraft

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#10047]
### Your GTNH Discord Username

KiloJoel#3044

### Your Pack Version

2.1.2.3QF

### Your Server

private server/SP

### Type of Server

Vanilla Forge

### Your Expectation

N/A

### The Reality

Server log file is always full of thousands of lines like this:
[14:40:47] [Server thread/TRACE] [SGCraft/]: SGCraft.onChunkLoad: 7,-2

About 800 of them follow 1 line like this:
[14:40:46] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Creative test world

This happens about once a minute, that's about 48,000 lines per hour. So I would consider this a pretty serious issue.

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8357747/fml-client-latest.log)

### Your Proposal

Remove the writes to log

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/SGCraft/pull/10
