### ISSUE TITLE
Supercritical Steam incorrect EU Value

### ISSUE THREAD

**Issue by Dacer1** [GTNewHorizons/GT-New-Horizons-Modpack#10040]
### Your GTNH Discord Username

DacerFanAccount#4757

### Your Pack Version

2.1.2.3qf

### Your Server

Private Server, SP

### Type of Server

Single Player

### Your Expectation

Supercritical Steam, produced by the Extreme Heat Exchanger Multiblock added by Good Generators, is supposed to have a 1:100 mB to EU ratio inside their respective turbine, the SC Turbine Multiblock.

### The Reality

During testing in creative Single Player,  while supplying a constant overabundance of IC2 Hot Coolant to the Extreme Heat Exchanger, the Multiblock Information when scanning it (with the portable scanner) suggests that the Steam Output is equal to 160,000 EU/t while outputting 32k mB of Supercritical Steam per Second (equal to 1600mB per tick).
Using a Turbine thats slightly below 32k mB/s optimal flow, (30k mB/s and 130% efficiency, Large Haderoth) you receive only 1,8k EU/t  which is most likely not the intended value. 

### Your Proposal

Up the EU/mB of Supercritical Steam to 100EU per mB as given by the Item Description of the SC Steam Turbine (ID: 2062:32016)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
has been fixed by https://github.com/GTNewHorizons/GoodGenerator/commit/a3d3cfd0b42dec4226a9fe951192f10f72b0d164
