### ISSUE TITLE
Tinkers Aluminium nugget EBFable in MV 

### ISSUE THREAD

**Issue by karikamiya** [GTNewHorizons/GT-New-Horizons-Modpack#10041]
### Your GTNH Discord Username

Mike#6628

### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Force players to use alumina and cryolite to make Al during MV.

### The Reality

Using a LV compressor or a smeltery, Al dust can be changed to tinkers construct Al nugget-thing and this can be EBF'd in a 120EU/t EBF with CuNi coils vs Al dust that needs 480EU/t and Kanthal coils.

### Your Proposal

Change the EBF requirements of the tinkers Al nugget to the same as Al dust.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by joshaup1999** [comment]
You don’t need kanthal coils for alu regardless. Kanthal coils is better yes but not needed for alu. Don’t think raw aluminium should be changed

**Comment by karikamiya** [comment]
Al dust needs 2054K, CuNi does 1801. Al dust does need kanthal

**Comment by Alrightsc** [comment]
The aluminum line got reworked a while ago; you're specifically meant to use alumina + cryolite or carbon (which requires kanthal) recipes which are more efficient than smelting up raw aluminum via TiC smeltery/compressor recipes. Major electrolysis recipes like clay dust already give alumina so you can't reliably get aluminum unless you hunt for aluminum gravel a lot or farm.

**Comment by Glease** [comment]
This is intentional to keep pure aluminium dusts you get from alum gravel smeltable in MV. The compressor step should be tedious enough that discourage prolonged use of this route.
