### ISSUE TITLE
I think we need to add the laser version of the debug generator

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#10057]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.1.2.3qf

### Your Proposal

I think we need to debug the laser version of the generator, because the laser bug is fixed in the next version, we can use a larger laser tank, but we don't have a generator that can supply current

### Your Goal

In the next version, the bug above the MAX voltage has been fixed, and the larger cabin can be used for testing. But we don't have a creative test generator that can provide high current, I believe we will need these things for testing large machines in the future

### Your Vision

If this generator is added, it will be easier to control the current for testing large machines later.
### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ethryan** [comment]
Please write in english so it's easier to understand.

Or use Google Translate.

**Comment by foxwhite25** [comment]
They need a debug generator for the tectech laser.

**Comment by SafariXiu** [comment]
> ### Your GTNH Discord Username
> 鄂木斯克间谍#9569
> 
> ### Your Pack Version
> 2.1.2.3qf
> 
> ### Your Proposal
> I think we need to debug the laser version of the generator, because the laser bug is fixed in the next version, we can use a larger laser tank, but we don't have a generator that can supply current
> 
> ### Your Goal
> In the next version, the bug above the MAX voltage has been fixed, and the larger cabin can be used for testing. But we don't have a creative test generator that can provide high current, I believe we will need these things for testing large machines in the future
> 
> ### Your Vision
> If this generator is added, it will be easier to control the current for testing large machines later.
> 
> ### Final Checklist
> * [x]  I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying _I like this feature please reconsider adding it_ will prompt us to investigate and reopen it once we confirm your report.
> * [x]  I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
> * [x]  I understand this change request may not attract enough attention and thus not be implemented.
> * [x]  I understand this change request may be rejected due to other community members thinking it's inappropriate.
> * [x]  I believe this feature would make the pack better.
