### ISSUE TITLE
Server has stopped responding in AE2 path finding

### ISSUE THREAD

**Issue by simbiant** [GTNewHorizons/GT-New-Horizons-Modpack#10058]
### Your GTNH Discord Username

SimbiAnT29#7106

### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Type of Server

Don't know

### Your Expectation

I start server with my world transfered from 2.1.1.0. The first minute or two it runs good. Then just stop responding.

### The Reality

[2022-03-27-2.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8362327/2022-03-27-2.log)

### Your Proposal

Don't know.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Is that all? We have other ultramine servers running 2.1.2.3qf just fine after replacing the stock magicbees with this one: http://jenkins.usrv.eu:8080/job/MagicBees/lastSuccessfulBuild/artifact/build/libs/magicbees-1.7.10-2.5.8-GTNH-11-gb12577b.jar

**Comment by simbiant** [comment]
I attached the log file, I give me 5 minutes, I'll try you magicbees file. I was trying with 2.5.7 because of crash

**Comment by simbiant** [comment]
I didn't help the same error: The server has stopped responding

**Comment by Glease** [comment]
2.5.7 should work either way. It probably won't make a difference. Did you check if you have accidentally included some client only mods? I can see it trying to access a bunch of client only classes somehow.
---
I did see your log. The log stops at a very abnormal point. At that point pretty much non of the mod code has ever been run. I'd say try switch to another version of ultramine, ask ultramine developers for help, or see there is something wrong with your system. After all, as I said above, we have other ultramine servers runnng gtnh 2.1.2.3qf just fine. The likelihood of an incompatibility is low.

**Comment by simbiant** [comment]
[2022-03-27-2.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8362270/2022-03-27-2.log)
Oh, I'm sorry. Looks like I sent wrong log file

**Comment by Glease** [comment]
Huh now it starts to make some sense. Does it hang on non ultramine servers? Otherwise it sounds like a bug in ae2 pathing somehow.

**Comment by simbiant** [comment]
I tried to update my forge server, and it has the same error, looks like it’s not just ultraMine

**Comment by repo-alt** [comment]
Yes, if it is indeed an AE2 bug, the world download would help a lot

**Comment by simbiant** [comment]
Do I need to leave just DIM1 dimension in map?

**Comment by repo-alt** [comment]
Whatever dimension the bugging AE2 network is in

**Comment by simbiant** [comment]
https://drive.google.com/file/d/1776_hyQlsIs0JyTlvFPzI6vG-x-skUcv/view?usp=sharing

**Comment by repo-alt** [comment]
Ok, as a workaround may take latest AE2 version from Jenkins http://jenkins.usrv.eu:8080/job/Applied-Energistics/  and in config\AppliedEnergistics2\AppliedEnergistics2.cfg set `B:EnableP2pBackboneTransfer=false` in `debug` section (also may set `B:EnableQuantumBridgeBackboneTransfer=false` just in case)

**Comment by simbiant** [comment]
It works. Thanks.

**Comment by Glease** [comment]
It's most likely an issue with machine slot index shifting. It's a one time bug whenever we add new slots to machines. There *are* known ways to solve this, but this is not known to the one who was adding slots. It should not happen any more in future versions...

**Comment by repo-alt** [comment]
Idk why this issue is still open. There are probably bugs in backbone cable pathfinding, but not something reproducible. Reopen with new data.
