### ISSUE TITLE
Tree grow simulator Unable to output

### ISSUE THREAD

**Issue by blackicecurry** [GTNewHorizons/GT-New-Horizons-Modpack#10054]
### Your Pack Version

2.1.2.3qf

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

The Tree Grow Simulator can output logs.

### The Reality

The Tree Grow Simulator unable to output any logs, Even if the structure is correct, there is power supply, and there are saplings and electric saws on the input bus / controller. The machine can even run but cannot output logs.
![image](https://user-images.githubusercontent.com/49740327/160301042-478efda3-02ad-4870-beac-6b520b4c8549.png)
![image](https://user-images.githubusercontent.com/49740327/160301098-594798f3-fd08-48d1-8682-2915d58f7f22.png)

### Your Proposal

Fix it so that it can produce logs normally.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
is this still an issue? we had multiple fixes and it seems to fully work now. I am gonna say fixed in dev for now.
