### ISSUE TITLE
Neutron Activator not working on Multiplayer (Thermos)

### ISSUE THREAD

**Issue by minecraft7771** [GTNewHorizons/GT-New-Horizons-Modpack#10059]
### Your GTNH Discord Username

minecraft7771#0427

### Your Pack Version

2.1.2.3QF

### Your Server

MyFTB

### Type of Server

Thermos

### Your Expectation

I setup multiple neutron activators for the naquadah line, connected the neutron accelerator to power and toggled both the accelerator and controller on and expected the NKE to rise.

### The Reality

The NKE stayed at 0eV. Using the scanner on both the accelerator and controller states, that the accelerator has enough energy and continues to consume energy. Using the scanner on the controller yields the following:
When the accelerator is disabled the scanner string of the controller says it has 0eV and an input of -72keV, which is as expected.
![image](https://user-images.githubusercontent.com/13762078/160430822-7111772b-fa99-4288-af82-c158ec4449a9.png)
However if the accelerator is enabled the scanner string of the controller no longer shows any information about the KNE.
![image](https://user-images.githubusercontent.com/13762078/160431011-d69ab3d5-7717-4d6c-bfdd-9bb0fe4b2f97.png)

Also if I would leave my world while the accelerator is running and come back, the controller turns into a missing texture block with the name ".name".
![image](https://user-images.githubusercontent.com/13762078/160431172-8e6193f4-a928-478b-8941-1c79a5cf6d28.png)
This state lasts until I disable the accelerator, after that the controller goes back to normal instantly.

### Your Proposal

This behavior does not happen in singleplayer, only on the server, for every player asked (each in their own dimension). We suspect this might be an issue with thermos but this would be the first known case to us that thermos stopped a machine from working alltogether, so maybe a weird interaction between the mod and thermos? No other machine was reported to have such a problem before.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Doesn't official run on thermos as well. How could neutron activator work fine there? Or has nobody ever built one on official so far?

**Comment by Sphyix** [comment]
> Doesn't official run on thermos as well. How could neutron activator work fine there? Or has nobody ever built one on official so far?

I built them on officials, but on version 2.1.2.0, and they work fine

**Comment by Runakai1** [comment]
> > Doesn't official run on thermos as well. How could neutron activator work fine there? Or has nobody ever built one on official so far?
> 
> I built them on officials, but on version 2.1.2.0, and they work fine

They don't work on MYFTB since 2.1.2.0

**Comment by FoKuCNiK** [comment]
I play on version 2.1.2.3qf alone and nothing works either, and here is the server core

**Comment by AVVasiliev** [comment]
I'm not alone, I'm playing on version 2.1.2.3qf - and the neutron activator does not work - kinetic energy does not accumulate (although electricity is consumed)

**Comment by GlodBlock** [comment]
in 2.1.1.4 there is fix for it, but not sure it works

**Comment by GlodBlock** [comment]
confirm fixed now https://github.com/GTNewHorizons/GoodGenerator/commit/13b8e4850cf940a773df4cd8f7415886bebb4f0c
