### ISSUE TITLE
StackOverflowError during client loads the world

### ISSUE THREAD

**Issue by kozachok3000** [GTNewHorizons/GT-New-Horizons-Modpack#10060]
### Your GTNH Discord Username

Kozachok#0327

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I've been loading my world

### Crash Report

I'v got a floating error during loading my world. I can backup it, but sooner or later this crash repeats. There are a couple of differend crash reports, but i think that the sourse of the problem is one. "Logisticspipes" was with another save.
[crash-2022-03-28_00.13.47-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8364697/crash-2022-03-28_00.13.47-client.txt)
[crash-2022-03-28_19.03.30-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8364698/crash-2022-03-28_19.03.30-client.txt)
[crash-2022-03-28_19.09.53-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8364699/crash-2022-03-28_19.09.53-client.txt)
 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
did you tried to load the map on 2.1.2.3qf?

**Comment by Glease** [comment]
Looks like we need to copy over ****ING_LOCK over from GT_Block_Ores to GT_Block_Machines.

Marking this as a reminder so we know why there is this lock.

**Comment by kozachok3000** [comment]
This crash is caused by 3000 glass from ztones. IDK how it works, but removing glass roof removed this unstable crashes and speeded up world loading. Version still 2.1.2.1.

**Comment by wohaopa** [comment]
I ran into the same bug. https://paste.ubuntu.com/p/fYP6MK5c4m/ 
This is a server, only one player had such an error, the other players did not have the problem.  I used a 2.1.2.3QF. I think this place is responsible: 
```
at net.minecraft.world.World.func_147453_f(World.java:3876)
at net.minecraft.world.World.func_147455_a(World.java:2603)
at net.minecraft.world.chunk.Chunk.func_150806_e(Chunk.java:851)
at net.minecraft.world.World.func_147438_o(World.java:2540)
```
And how did you solve it?

**Comment by BritishCynic** [comment]
@Glease Did anything get fixed regarding this?

**Comment by BritishCynic** [comment]
Closing as this is an old crash report; if this crash still occurs on 2.3.0+, please comment to reopen.
