### ISSUE TITLE
StructureLib Multiblock ghost particles immediately disappear on MP if you have "All Particles" settings on

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#10067]
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.2.3qf

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Right click a multiblock with Multiblock Structure Hologram Projector

### The Reality

The particles immediately disappear

### Your Proposal

This only happens on MP, Vanilla Forge (so far, probably might affect other servers) IF you have the "All Particles" settings on. If you have either Decreased or Minimal Particles, the issue is not present.

Why and how this occurs is beyond me

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Cannot reproduce with any of the 3 level.

**Comment by Chaoschaot232** [comment]
Never encountered this problem too, even not with OptiFine installed or not.

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
