### ISSUE TITLE
T.F.F.T. Voiding stored fluids and various other bugs

### ISSUE THREAD

**Issue by Dacer1** [GTNewHorizons/GT-New-Horizons-Modpack#10061]
### Your GTNH Discord Username

DacerFanAccount#4757

### Your Pack Version

2.1.2.3qf

### Your Server

private Server

### Type of Server

Vanilla Forge

### Your Expectation

Used a T.F.F.T. as a Fluid Storage
Imported all, previously in super tanks, stored fluids. Added a Multi I/O Hatch at the bottom to fill the various fluids in.
The Multi I/O Hatch does not output into ender fluid conduits.
Because of that i placed 25 output hatches (LV) adjacent to the center pillar, replacing the reinforced glass structure within that Multiblock. Then i locked every single available fluid to one fluid hatch (each) on the outside and then removed the circuit such that the Tank will refill all hatches on its own, because the T.F.F.T. doesnt output anything to hatches locked with a "null circuit" present (a circuit with a number of an ID thats not been filled in the T.F.F.T. yet), i changed the circuit to a number of a present fluid. this lead to the hatch filling up but also voiding all fluid contents of that respective ID.

### The Reality

Observation 1: The Multi I/O Hatch does not output into ender fluid conduits (perhaps a bug, but i dont know if that may be intended behaviour).

Observation 2: The T.F.F.T. does not output to locked hatches unless a fluid has been present inside that hatch after locking it
(replicate by filling a T.F.F.T. with for example water, then lock the T.F.F.T. from outputting anything by placing a circuit with a different ID from all other fluids, place a hatch, lock it to water, remove circuit, the T.F.F.T. will not refill the hatch until you place a water cell inside of the hatch first)

Observation 3: Placing a circuit with a fluid's ID (for example 22 for Iron-III-Chloride) inside the Controller and then taking a Cell out of the respective output hatch leads to the T.F.F.T. overwriting the previously stored fluid ID with NULL, essentially voiding the Fluid

### Your Proposal

-make tfft I/O hatch output to ender conduits pls
-make tfft less evil such that other people wont suffer the tragic fate of it voiding 2 million mB of fluorine while setting up
-make tfft output to locked hatches properly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by madmacf** [comment]
Yeah. Super annoying. Makes the TFFT useless.

**Comment by s9hysky** [comment]
Yes my TFFT is broken too
