### ISSUE TITLE
Logistics Pipes recipies place it at or beyond the point where you can run for AE

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [GTNewHorizons/GT-New-Horizons-Modpack#10062]
### Your GTNH Discord Username

A_D#7588

### Your Pack Version

2.1.2.0

### Original Request

Clarification on LP recipe difficulty and intended teir

### Responding developer

@Steelux8

### Context

https://discord.com/channels/181078474394566657/234936569360809996/958102560407957525

Most of this chat took place on kharax82's discord

https://discord.com/channels/329103600364027906/836979474306170900/958087099045802006 <-- start of that chat

### Developer's Promise

Look at | rebalance of the recipes

I asked specifically about intended tier being around MV (for me early MV, but somewhere there)

### Final Checklist

- [X] The developer in question has instructed me to create such an issue.
- [X] I believe the developer is not causally joking around.
- [X] I understand this reminder might take a long time to implement no matter what the developer has promised. (e.g. unforeseeable life difficulty, computer breakdowns, forgetting, laziness, etc)
- [X] I understand other people (developers or not) might not like this feature and would oppose its integration.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
LP definitely needs to be re-tiered to land in MV. As of right now, there's barely any room between having a full LP setup and replacing it with AE2. I have been working on other stuff, but I'll try to make sure this happens before the next stable release.

**Comment by Steelux8** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/10288 

LP has successfully been re-tiered to MV, except for some high-tier upgrades of important blocks that need more progression to achieve.
