### ISSUE TITLE
Disable Hydrogen as a directly burnable turbine fuel

### ISSUE THREAD

**Issue by Glease** [GTNewHorizons/GT-New-Horizons-Modpack#10066]
### Your GTNH Discord Username

glee8e#7174

### Your Pack Version

2.1.2.1

### Your Proposal

Disable Hydrogen as a directly burnable turbine fuel.

At least make it only burnable in stuff like LV gas turbine and not others, so the New Powerful Hydrogen Production Method® won't become a scaleable perpetual motion machine.

### Your Goal

Burnable Hydrogen makes a hard bottom line (to not create a positive power loop) for any hydrogen producing recipes on energy costs. If the upstream material is nothing but a power sink, the material cost would also be affected. Since we are utilizing hydrogen in more and more mid & late contructs, the need for cheap and mass scale hydrogen producing method is needed. However, due to the aforementioned bottom line this is just impossible.

### Your Vision

Pave path for cheaper hydrogen production method.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
No i am against it. Hydrogen is a very clean way to produce power even in RL. We can change the fuel values or change the pasth how hydrogen is made but please not disable it.
