### ISSUE TITLE
Wrong questbook text for more advanced circuit board

### ISSUE THREAD

**Issue by YanFett** [GTNewHorizons/GT-New-Horizons-Modpack#10064]
### Your GTNH Discord Username

reverse71

### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Your Expectation

More advanced circuit boards are made with energetic alloy foil and aluminium foil. The Questbook should reflect this.

### The Reality

The Questbook says it is made with copper and annealed copper foil.

### Your Proposal

Change it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment]
![image](https://user-images.githubusercontent.com/39595617/163549447-3b5a0e37-8e3a-4c4e-9586-541df7503095.png)
someone probably fixed it
did u do /bq_admin default load(if you updated pack)

**Comment by miozune** [comment]
Already fixed by #9086. (included in 2.1.2.3qf)
