### ISSUE TITLE
Small changes for the rewards of "Armor 2.5" quest

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#10072]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Proposal

All the reward books are 2 level, except Aqua Affinity - this book is lvl 1, i think all the books should be of level 2

### Your Goal

null

### Your Vision

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by King65868** [comment]
There is not

**Comment by MadRatSRP** [comment]
My bad then
