### ISSUE TITLE
Buff stargate, make officials lag-free again

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#10071]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.1.2.0

### Your Proposal

Stargate difficulty should be lowered. With the current difficulty and corresponding implementation it is expected to cost 2 months at a whopping 70% CPU load on the officials, or roughly 3 weeks of 24/7 100% CPU load. This is already reducing the quality of life for all other players on the officials, and can't be reduced further due to already being CPU-bound.

[NoLife]Pandoro: then, 200 void miners III are 2 months
[NoLife]Pandoro: but 400 it's just 1 month for the mats
[Elite]POPlol333: bruh
[Elite]POPlol333: what are you doing?
[NoLife]Pandoro: stargate after nerf
[Elite]POPlol333: to prove to colen it's still possible?
[NoLife]Pandoro: should be around 600k infinity ingots
[NoLife]Pandoro: no, to prove colen how dumb it is
[NoLife]Pandoro: cause there's no way i can do it with 25ms limit for my base
[NoLife]Pandoro: boubs is not opposed to the nerf

### Your Goal

GTNH should be about being smart, not about having to spam a server to the point of maximum load and still having to wait months if you do that.

### Your Vision

Stargate should be difficult, but not unreasonably taxing.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Connor-Colenso** [comment]
Except the stargate is supposed to be a meme item so, no.

**Comment by Connor-Colenso** [comment]
This issue has been debated like 3 times previously and it was decided that the stargate will not be buffed so I really struggle to see why this ticket shouldn't be closed right now? I don't think "not being able to make the stargate on a public server with 10 others" is a valid reason to buff it.

**Comment by combusterf** [comment]
<img width="506" alt="image" src="https://user-images.githubusercontent.com/8459776/160829411-154ca763-65e8-4b2a-a555-7f4aad57ec2c.png">

**Comment by Connor-Colenso** [comment]
As discussed on github this ticket is now closed and not to be opened again. If you wish to open a constructive ticket on an issue that has not been previously discussed then feel free to do so but spamming this and abusing your perms is not going to get you any progress.
