### ISSUE TITLE
Flotation Cell Regulator can process single stack of milled ore

### ISSUE THREAD

**Issue by pulsemageadvocate** [GTNewHorizons/GT-New-Horizons-Modpack#10076]
### Your GTNH Discord Username

pulsemageadvocate

### Your Pack Version

2.1.2.3qf with some jenkins jar

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Flotation Cell Regulator needs 256 milled ore (and 32 Sodium/Potassium Ethyl Xanthate Dust) to work.

### The Reality

It can work with only 64 milled ore (and Xanthate), and produce full 1000L Froth.

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
Looks like a bug similar to what happened to 72 plutonium in LCR for radon and buttons for keyboard in assembler. #8166 references both solutions, maybe this can be of use?
