### ISSUE TITLE
Change SB machines to use OVERLAY_PIPE texture

### ISSUE THREAD

**Issue by Jimbno** [GTNewHorizons/GT-New-Horizons-Modpack#10083]
### Your GTNH Discord Username

Jimbno

### Your Pack Version

2.1.2.3QF

### Your Proposal

Have single block machines use OVERLAY_PIPE instead of OVERLAY_PIPE_OUT which is used for output hatches.

### Your Goal

giving single block machines their own overlay for the back would open up new possibilities for texture packs

### Your Vision

it would improve texture packs

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
OVERLAY_PIPE is used for steam vents in steam machines. You sure this is a good idea?

**Comment by Jimbno** [comment]
the idea would be for steam machines to use overlay_pipe_out and any single block machines above steam tier to use overlay_pipe
