### ISSUE TITLE
find out why logistic pipes is wrongly flagged as a malware

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10085]
for those who wonder if it's a real malware. No! Looks like a new malware definition has been detecting logistic pipes somehow. We are investigating.

**Comment by simplesmiler** [comment]
VirusTotal complains about two files in particular:
- logisticspipes/proxy/enderio/EnderIOProxy.class: https://www.virustotal.com/gui/file/3313d4d8b793e15f0cd08b49fe5d38113e99eac1ca660cf139ede4d1e1d637bf
- logisticspipes/utils/item/ItemIdentifier$ArrayDamagedItentifierHolder.class: https://www.virustotal.com/gui/file/f72ec43269619bfbd65877a8c6b2acdcfca4823c3dd10d5f9e41596b6ce8b351

**Comment by Glease** [comment]
> EnderIOProxy
I guess they are mad because it embedded classbytes as base64... indeed very suspicious

> ArrayDamagedItentifierHolder
The antivirus thing is broken.
