### ISSUE TITLE
Cannot craft Dangote Distillus (GT++)

### ISSUE THREAD

**Issue by miozune** [GTNewHorizons/GT-New-Horizons-Modpack#10091]
### Your GTNH Discord Username

miozune#9742

### Your Pack Version

2.1.2.3qf + several manual updates

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to craft Dangote Distillus

### The Reality

The recipe requires unobtainable fake circuits (and it's not just visual bug but also actually uncraftable)
![2022-04-04_17 38 44](https://user-images.githubusercontent.com/40035906/161507215-f846a619-f0b6-4752-a199-57817caa305d.png)

### Your Proposal

Implement oredicted input for Chemical Plant or add recipes for all the circuit variants.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
What’s uncraftable?
Put circuit in GT++ circuit programmer.

**Comment by miozune** [comment]
The recipe requires "Any IV Circuit" added by coremod, which is used only for oredict fix and unobtainable.
