### ISSUE TITLE
Infinite Fluid Drilling Rig - Recipe not craftable

### ISSUE THREAD

**Issue by minecraft7771** [GTNewHorizons/GT-New-Horizons-Modpack#10096]
### Your GTNH Discord Username

minecraft7771#0427

### Your Pack Version

2.1.2.3QF

### Your Server

MyFTB

### Type of Server

Thermos

### Your Expectation

We tried to craft the infinite fluid drilling rig according to the recipe in NEI with UHV mainframes.

### The Reality

The Recipe does not accept the UHV mainframes. It is notable that the "Any UHV Circuit" placeholder is in the recipe, but it does not cycle through the other UHV mainframes, like it does for other assembly line recipes. Testing it out by cheating the "Any UHV Circuit" shows that the recipe does start with it, but not with the UHV mainframe.

### Your Proposal

I think the recipe just needs to enable substitution for UHV circuits.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
already fixed by https://github.com/GTNewHorizons/TecTech/commit/be2da1f5f44af821e338cf48621a57c84568aaef
