### ISSUE TITLE
Significant slowdown AE2 terminals

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/GT-New-Horizons-Modpack#10093]
### Your GTNH Discord Username

Usernm#4396

### Your Pack Version

2.1.2.3 qf

### Your Server

SP

### Your Expectation

I have specific AE2 setup. 1 Controller block. Dense cable from it connects to 16 drawer controllers. Each controller connect 120 x4 storage drawers (480 items on each drawer controller) And about 7k item types in all system. Each drawer have one creative vendor upgrade and void upgrade. ME system see 2G items (signed int items in fact) each type.

Everything works fine when i play on 2.1.2.1.

### The Reality

After update on 2.1.2.3 qf ME terminals freeze for about 5 seconds EVERY time i open it. Totally unplayable. I partially remove connection to drawer blocks and it helps a little. When connected about 1.5k items freeze for about 2 seconds every time. 

### Your Proposal

Find what broke in AE2 in last commits and fix it. Because everything works fine before. 

I can upload my save somewhere, but it's about 1.2GB now.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
Do you access externally the drawers in addition of accessing them with AE?

On a side note you shouldn't use drawer controllers with storage buses, that's laggy and it's the very reason why the cells are dirt cheap now.

**Comment by Usernm0** [comment]
I put items in drawers by hands. Not in drawer controller. I use ME terminals to get items from drawer controllers and void existing items using void upgrades on each drawer.

I can't use cells, because i use creative vending upgrades to have unlimited items.

**Comment by mitchej123** [comment]
1) you're using things in an unsupported configuration (drawer controller and creative upgrades)
2) don't they have creative ae2 cells?
3) run visualvm or warmroast and provide a profile showing the lag

**Comment by boubou19** [comment]
I can confirm that AE2 has a creative cell, you just need to format it with the items you want and you'll automagically have 2B of it in the cell. Also accessing the drawers externally could invalidate the cache so i wouldn't be surprised it lags.

As Mitch pointed out, you use something in an unsupported configuration so unless you provide a jvm sampling through warmroast or visualvm, we won't try to replicate the bug.

**Comment by Skiftcha** [comment]
> you use something in an unsupported configuration

what changed between 2.1.2.1 and 2.1.2.3 qf so this became unsupported?
you already greatly reduced number of drawers supported by drawer controller to reduce lags and then increased lags of each drawer?

@Usernm0 а лагают именно креативные дроверы или если в отдельном мире собрать дроверы без апгрейдов они так же лагают? конечно сетапить такое с разными итемами будет неприятно) мб просто повынимать креативные апгрейды из текущих дроверов и посмотреть?

**Comment by Usernm0** [comment]
About cache. Most of the time i just open ME terminal, take few items and close it. I shouldn't change cache at all. 

I can't download warmroast beacuse this link is dead:
[](http://builds.enginehub.org/job/warmroast/last-successful/)
And i can't find alternative links.

Try to understand how work with visualvm to get profile
