### ISSUE TITLE
Assembly line does not form with 16 input buses

### ISSUE THREAD

**Issue by GDCloudstrike** [GTNewHorizons/GT-New-Horizons-Modpack#10100]
### Your GTNH Discord Username

GDCloud#2907

### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Tried to build an assline with 16 input buses and 1 output bus (a total of 17 slices)

### The Reality

Assline didnt form

### Your Proposal

Make the assline work with 16 input buses because some recipes need it (mainly dyson swarm) and NEI suggests that it should be working
![image](https://user-images.githubusercontent.com/93287602/161758834-b07f3815-f5fc-4321-b572-1f2b46ab753e.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
So far ik ass line not need to be 17 blocks long. Controlblock can set on top.

**Comment by GDCloudstrike** [comment]
Can you elaborate? I dont quite understand what you mean

**Comment by GTNHAfx237v7** [comment]
Output bus on top of slice 16, no need for 17 slices.

**Comment by GDCloudstrike** [comment]
> Output bus on top of slice 16, no need for 17 slices.

Ah okay, got it now, thanks.
The thing that confused me is that the hologram projector doesn't say that you can place an output bus there.
![2022-04-05_17 54 06](https://user-images.githubusercontent.com/93287602/161795294-af818672-1e0f-44ae-a9c2-d7ea33ff7311.png)

**Comment by Dream-Master** [comment]
Yea need to be updated

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1155
