### ISSUE TITLE
Zirconium ingot is nearly impractical to get as it has no EBF from pure dust to ingot recipe

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#10109]
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.2.3qf

### Your Proposal

The Zirconium dust is automatically converted to BartWorks dusts. However, this dust version does not have a EBF recipe and thus there are extremely few ways to get certain GT++ recipes via pure Zirconium

### Your Goal

Add EBF recipe to pure BW Zirconium

### Your Vision

Where to add it?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Elisis** [comment]
Zirconium dust isn't really intended to be EBFed as you're now supposed to go through zirconium tetrachloride. Couldn't hurt to have the dust to ingot anyway however

**Comment by LewisSaber** [comment]
Ingot is needed to make fine wire that is needed for GT++ forge hammer

**Comment by ScriptedPiky** [comment]
Yeah, that recipe I can go and do. Although, it's technically the only way to realistically get pure GT++ Zirconium (why this is doesn't already have one perplexes me)
