### ISSUE TITLE
Long Distance Item Pipe (LDIP) not working with input Bus Input

### ISSUE THREAD

**Issue by JustBenji** [GTNewHorizons/GT-New-Horizons-Modpack#10107]
### Your GTNH Discord Username

Benji#0586

### Your Pack Version

2.1.2.3qf

### Your Server

Private Multiplayer

### Your Expectation

The Long Distance Item Pipeline (LDIP) to work with input bus for input in machines.

Testscenario;
Creative, over 4 chunks

Test A: End input Chest , End output Chest
Test B: End input chest , end output Input Bus

Test A works, item goes into chest, Test B fail.

### The Reality

Transfer to chests work, transfer to input bus does not

### Your Proposal

To make it work for input bus since it is an "Inventory".

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
For a temporary solution, point the input bus in the opposite direction of the LDIP, e.g. this
![ldip](https://user-images.githubusercontent.com/4586901/162517098-b967dd0d-b200-4e0d-92e5-d44813e7f4c9.png)
