### ISSUE TITLE
Tremendeous amount of Entites and TileEntities loaded on Moon over time.

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/GT-New-Horizons-Modpack#10105]
### Your GTNH Discord Username

Gates_ice#4537

### Your Pack Version

2.1.2.3qf

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Should investigate the reason for this that causes huge lag to the server.

### The Reality

We have a multiblock ore miner set up on moon, as long as a passive chunk loader, we only have one. The multiblock ore miner is the one w/ lowest level.

I observed around one day passed, the entity and TileEntities on the moon are increased overtime. Here is the file that shows the server TPS (other dimensions are ignored as they are not active, all numbers are 0):

```
Overworld [0]: 20.00 TPS / 17.22 ms. Loaded chunks: 696. Loaded entities: 575. Loaded TE: 10539.
Moon [28]: 20.00 TPS / 21.23 ms. Loaded chunks: 0. Loaded entities: 44998. Loaded TE: 832463.
Overall: 20.00 TPS / 39.28 ms. Loaded chunks: 696. Loaded entities: 45573. Loaded TE: 843002. Loaded dims: 49.
```

### Your Proposal

N/a

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
What happens if you visit that place? do they disappear?

**Comment by Gateswong** [comment]
> What happens if you visit that place? do they disappear?

I tried to use a creative character to visit Moon. I got timeout error right after reach moon. Then in the following period of time I completely cannot log in to server, time out everytime.

After around half hour, everything goes to normal.

Actually I found in the screenshot in post, the chunk loaded on moon is ZERO, which means the chunkloader and miner are already finished the job and stopped working.

I wonder my visit to moon with the creative character triggered something to load the Moon area which cause the loaded E/TE back to normal (but it still takes around 30 mins). Here is the TPS log file right now:

![image](https://user-images.githubusercontent.com/2586057/161917948-04b5d9c8-72ba-4003-b3ce-44c0a25b01ad.png)

You can still see 0 chunks loaded on moon and there are many E/TE loading. The image shows there are 4000 TEs loaded but I'm sure that it was around 100 right after the huge lag gone.

P.S: The log file is the <minecraft_server_path>/logs/admintools/tps/tps.log

**Comment by Gateswong** [comment]
Update:

The problem still exists, with `/cofh tps` command, I found that sometimes it returns me 1 chunk is loaded on moon:

![image](https://user-images.githubusercontent.com/2586057/162075646-931a850f-a3d9-4f0d-b005-5112cb403f97.png)

I'm still don't know which chunk is loaded yet.

**Comment by Gateswong** [comment]
Update:

After I removed the Thaumcraft magic mirror (linked) on Moon, this problem don't happen anymore.

While I was investigating the problem on the Moon, my overworld area w/ the other mirror is unloaded, the same thing happened on my overworld. So I'm guessing put a linked magic mirror in an unloaded chunk might help reproduce this problem.

More investigations might needed to figure out which part of code causes this.

**Comment by Glease** [comment]
Try remove cofhcore and see if it helps. If anything complains about missing classes add cofhlib

**Comment by Glease** [comment]
Might be related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6964. I vaguely recall we were also seeing ghost tiles caused by magic mirrors.

**Comment by fluffle** [comment]
Or #6976 maybe? At any rate I have found that switching in the latest hodgepodge (and reverting to BoP from curseforge) fixed some pretty substantial memory leaks I was seeing that sound similar.
