### ISSUE TITLE
Infinite [HV] energy

### ISSUE THREAD

**Issue by arbitrarystar** [GTNewHorizons/GT-New-Horizons-Modpack#10103]
### Your GTNH Discord Username

dxzfvzs#1259

### Your Pack Version

2.1.2.3.qf

### Your Server

Private server

### Your Expectation

I have set up blast furnace to be powered by two HV hatches. 

Powered by a battery buffer consisting of 4 batteries, cable going from the buffer into both energy hatches. A HV combustion generator connected to this cable (just in case). The battery buffer has been at the end of the larger wire network, but the power source of that one was another HV battery buffer which was charged by a singular kinetic wind generator working at half power at that time. 

Expected electricity to be drained from both of those battery buffers. 

### The Reality

It did not drain the energy from either of them, nor from the combustion generator, and the blast furnace kept going, virtually consuming no electricity whatsover.

The rest of the wire network - between the two battery buffers, did not work. No electricity was flowing within those wires -- when I clicked on them with a tricoder, it showed 0A flowing. Only place where amperage did flow was between the last battery buffer and the HV energy hatches. When I added another battery into the last buffer, it began charging.

Possibly not directly related -- when I have reconnected to the server, the first battery buffer (powered by wind) was a broken block with `.name` as a name, and right-clicking on it caused my client to die on me.
 
![image](https://user-images.githubusercontent.com/56274079/161875539-52496128-a1de-4b27-a5b1-1d28d84a5b41.png)
![image](https://user-images.githubusercontent.com/56274079/161875570-ad1e3d7e-3be6-4c18-88f9-5858ec9ebb34.png)

I have replicated this issue in singleplayer, with way easier wire setup and no combustion generator. Apparently, the first battery does not even have to be powered at all, and yet it generates electricity somehow.

The final setup was just a battery buffer, some gold 3A cables, another buffer, and a thicc aluminium 8A cable into the HV energy hatches.

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hikari1nVoid** [comment]
Not enough information provided.
Try provide more data on real-time power usage?since such a bug (if really exist ,not just some creepy buffer) is a bugMajor.

**Comment by chochem** [comment]
Just did some testing:

I wasn't able to replicate @arbitrarystar's issues but I am not sure if I really had the same setup, the description wasn't very clear.

But I was able to replicate @dipo33's problem with the exact same setup (in SP, 2.1.2.3qf). The key point that makes it act that way is the 1A gold cable. This cable really should burn up as it can only support 3A but 4A flow through However for some reason it doesn't and instead it bugs out as described. If one uses a 4A+ cable this behavior does not happen.

**Comment by chochem** [comment]
so here is a more minimal setup of the bug. no ebf or energy hatches involved:

high voltage battery buffer with 4 full HV lithium batteries -> 1x gold cable ->high voltage battery buffer with 4 empty HV lithium batteries


![2022-04-30_14 32 32](https://user-images.githubusercontent.com/40274384/166107723-895a30dd-0d58-4c50-8f59-4166edf3f34f.png)

Indeed the bug occurs, the outputting batteries get stuck on this value and stop draining:

![2022-04-30_14 32 34](https://user-images.githubusercontent.com/40274384/166107780-0643ac48-8866-490b-ba8d-7075702cd91f.png)

but the receiving batteries continue filling:
![2022-04-30_14 32 37](https://user-images.githubusercontent.com/40274384/166107826-cd38112d-b2dd-46d0-a09f-ba8ce2696575.png)

scanning the cable shows 380A/3A (the value continues to rise):
![2022-04-30_14 32 49](https://user-images.githubusercontent.com/40274384/166107850-24da623c-bcb1-43e3-8080-bdab6bc8e080.png)
