### ISSUE TITLE
Severe graphical glitches

### ISSUE THREAD

**Issue by Tymekin** [GTNewHorizons/GT-New-Horizons-Modpack#10106]
### Your GTNH Discord Username

Tymekin#9457

### Your Pack Version

2.1.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to start the adventure, I tried using couple of launchers, but in all of them the journey stops pretty fast.

The game renders Quest Book correctly (if Optifine isn't installed)
![2022-04-06_15 53 12](https://user-images.githubusercontent.com/103122082/161994128-79a6cfbb-fa67-4a1a-a180-ba62b4130263.png)
![2022-04-06_15 53 14](https://user-images.githubusercontent.com/103122082/161994140-f50670eb-dc7d-45d9-9a88-bcaee2f32bcc.png)

### The Reality

The game seems to have problem with rendering, including but not limited to:

- Making whole screen as just one single color while holding an item/block in hand, depending on what are we looking (for example, if we look into the sky, it shows light blue)

- Not rendering mobs
![2022-04-06_15 56 37](https://user-images.githubusercontent.com/103122082/161993322-ddee33b7-0202-473f-8348-6fe130a4d494.png)

- Rendering dropped blocks as black boxes and not rendering dropped items
![2022-04-06_15 56 12](https://user-images.githubusercontent.com/103122082/161993790-72609822-bdc8-4b3c-8c99-7ac7d9c27577.png)

- Some chunks don't render textures, instead use full color
![2022-04-06_15 34 17](https://user-images.githubusercontent.com/103122082/161994465-88a85969-0cbb-4ac0-9505-85480b1da99e.png)
![2022-04-06_15 32 53](https://user-images.githubusercontent.com/103122082/161994427-abed8dec-bc60-484e-8205-a465adb1d28f.png)

Also, after adding Optifine to the game, the bugs change to:

- Holding item/block in inventory makes most of the GUI black
![2022-04-06_15 52 32](https://user-images.githubusercontent.com/103122082/161994812-de6c39a5-0cda-4a6c-9775-35d4c7694e24.png)

- Also, Quest Book starts to be glitched
![2022-04-06_15 33 37](https://user-images.githubusercontent.com/103122082/161994969-f7b9df3d-87c0-450c-8ce8-79e486a7aedb.png)
![2022-04-06_15 33 54](https://user-images.githubusercontent.com/103122082/161994973-1a38ba20-6665-4494-9b59-6c78e3ef831d.png)
![2022-04-06_15 33 26](https://user-images.githubusercontent.com/103122082/161994976-910b6752-c6a6-4308-bdee-b2fc08005423.png)

All other glitches are still in the game with Optifine (apart from the full color screen of course).
There are some error messages on the chat after joining a world:
![2022-04-06_15 32 40](https://user-images.githubusercontent.com/103122082/161995290-987ce35a-8e9e-47f6-972e-d9371259d561.png)
 

### Your Proposal

Could it be that it's problem with my graphics card (Intel HD Graphics 620)? My game never got broken this way, it's an pretty unusual sight.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
what's your operating system? and what's your java brand and version? What's the graphic card used by the game?

**Comment by Tymekin** [comment]
> what's your operating system? and what's your java brand and version? What's the graphic card used by the game?

Windows 10 Home Edition, Java 8 Update 311, Intel HD Graphics 620

**Comment by boubou19** [comment]
Do you have another graphic card on your computer to see if it's related to the graphic card?

**Comment by Tymekin** [comment]
No, sadly.

**Comment by UniZero15** [comment]
I think it is related to your video card as Intel integrated cards were not great for gamin especially for Minecraft. 

There was a crash log error called Pixel Format not Accelerated, or similar to that anyway, which was caused by Intel video cards.
