### ISSUE TITLE
The "Beginning of the End Game" quest has a place holder item

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#10118]
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.2.3qf

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

I tried to complete the questline for Wetware

### The Reality

The quest ID 2006 requested an item that no longer exists in TecTech

### Your Proposal

Remove the item `tectech:item.em.constructable/0` from quest requirement, which seems to be the Blue Print before it got moved into StructureLib

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
I cannot find, probably fixed in dev

**Comment by Dream-Master** [comment]
@ScriptedPiky show us the Page and the Quest.

**Comment by LewisSaber** [comment]
![image](https://user-images.githubusercontent.com/39595617/162569632-509c2156-937e-4b7e-95ea-8c8bfb82112f.png)
guest for me
im using 2.3gf + some jenkins mods

**Comment by ScriptedPiky** [comment]
Oh neat, thank you then!
Seems like me and my friend didn't have the proper quest
