### ISSUE TITLE
Think Neutron reflector can't be crafted by using  Neutron reflector I made

### ISSUE THREAD

**Issue by kuso2020** [GTNewHorizons/GT-New-Horizons-Modpack#10114]
### Your GTNH Discord Username

KUSO2020#1784

### Your Pack Version

2.1.2.3qf

### Your Server

private sever

### Type of Server

Vanilla Forge

### Your Expectation

I want to craft a Think Neutron reflector by using Neutron reflector I make in the assembler but it cant work. (I using the processing Array with 8 IV assembler)

![QQ图片20220408202648](https://user-images.githubusercontent.com/101241062/162435789-1f77c3a7-c8ed-4e47-83d7-348f60baffa5.png)

### The Reality

The assembler is not working and I find only the chest one can be use to make it.
![QQ图片20220408202706](https://user-images.githubusercontent.com/101241062/162435758-e63627b1-0532-4d84-bfb8-434508a9d810.png)

### Your Proposal

I hope the recipe will be fixed

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment]
Already fixed
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/294

**Comment by kuso2020** [comment]
@LewisSaber  in the new version?

**Comment by LewisSaber** [comment]
yes
