### ISSUE TITLE
T8 Rocket is potentially impossible to create

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#10117]
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.2.3qf

### Your Proposal

In order to create a Heavy Duty Plate T8, you need 2 UHV hatches for UEV input to create said plates. But in order to get UHV, you need Awakened Draconium Coils, which needs the tedious Draconic Evolution questline that also requires you to visit T8 planets and harvest planet stone over there for some reason. The quest in question that requires T8 stones is the "The technician part 2" quest.

I also just realized that maybe it's possible to craft the T8 rocket parts with 8 UV energy hatches? Or at least so that I think. Not sure if the Assembly Line will even function properly this way.

### Your Goal

UHV SC instead should use Electrum Fluxed Coils. The DE questline shouldn't require the player to need to go to T8 planets to collect some stones, instead, it should just be a T7 planet gating. Maybe the questline could be reworked slightly.

### Your Vision

This would make getting to UHV and also certain progression requirements a little more bearable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by jjbraun** [comment]
you need to factor in the +100 heat per energy level above mv. with that electrum fluxed already works, right?

**Comment by chochem** [comment]
you need to factor in the +100 heat per energy level above mv. with that electrum fluxed already works, right?

**Comment by ScriptedPiky** [comment]
I have tried and it's not working. 
![2022-04-08_14 53 23](https://user-images.githubusercontent.com/41557212/162537168-9f5f1b2c-bc01-4b77-bb66-8b2f484a9405.png)
![2022-04-08_14 53 27](https://user-images.githubusercontent.com/41557212/162537173-4e8f97b7-70a1-4a91-ab4a-67cb1bb854ba.png)
![2022-04-08_14 53 30](https://user-images.githubusercontent.com/41557212/162537176-97aec3e7-172f-4a09-a50b-8d2bd9cc9ced.png)

**Comment by ScriptedPiky** [comment]
Ah wait, this was an output bus, sorry!

**Comment by ScriptedPiky** [comment]
Seems like it does work. However, the exception applies to a Volcanus, which doesn't accept the increased heat buff it seems. Although, that's a GT++ issue. I mistaken that this was impossible, sorry!

Not sure if a Mega EBF works, but I presume it does

**Comment by chochem** [comment]
MEBF and Volcanus dont get the bonus heat (which might be intended? not sure why though). The EBF quest actually mentions this. :)

**Comment by ScriptedPiky** [comment]
Ah yeah, that quest seemed so old that I forgot about it! Heh, ah well
