### ISSUE TITLE
behavior and description does not match

### ISSUE THREAD

**Issue by BlueIceJAY** [GTNewHorizons/GT-New-Horizons-Modpack#10112]
### Your GTNH Discord Username

Neutron#6126

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Block breaker (ProjectRed Expansion) will break the block and put it into the container on the back.I want use it to instead ME Annihilation Plane (Applied Energistics 2) ,because this is the only pulse-excited block breaker in all GTNH.This can greatly reduce the probability of errors occurring in Assline automation.
![Assline 002](https://user-images.githubusercontent.com/63415263/162379170-d1a8ecd8-87cc-44a8-98ad-18708f5913a8.png)

![Assline 001](https://user-images.githubusercontent.com/63415263/162379066-e481601a-85a0-4ff0-b43b-7b2322909e4f.png)

### The Reality

Block breaker (ProjectRed Expansion) will break the block and put it into the container on the back.It works for most blocks,but not for Compressed Chest (Avaritiaddons) .When it mines the Compressed Chest, it cannot enter the container behind it correctly, but instead becomes a entity item.So I had to add the item collector or use a ugly reflow device to increase my tps for no reason.
![001](https://user-images.githubusercontent.com/63415263/162379321-70d6eac9-ee13-4a21-9028-3b0317d32d7d.png)
![002](https://user-images.githubusercontent.com/63415263/162379383-b040b7e5-2088-4a66-b216-221ef245de5f.png)
![003](https://user-images.githubusercontent.com/63415263/162379462-f15dba0e-edab-42f1-b960-80d565575b47.png)
![004](https://user-images.githubusercontent.com/63415263/162379543-fa40ceb5-2df0-452e-a05a-f03df45d5e74.png)

### Your Proposal

I hope it mines the Compressed Chest and puts into the back container correctly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueIceJAY** [comment]
I am not a native English speaker.So sorry my word may not be so easy to understand.

**Comment by boubou19** [comment]
this seems like an overengineered assline automation. Here is one of the easiest ones: https://youtu.be/W1eIV-AbBlA

Now for your issue itself, it seems like the block breaker doesn't accept to break a block with a TileEntity.

**Comment by BlueIceJAY** [comment]
> [](https://youtu.be/W1eIV-AbBlA)
> 
> Now for your issue itself, it seems like the block breaker doesn't accept to break a block with a TileEntity.

I also tested other chests that can keep items,like Draconic Chest,but this chest can be broken and sent to the back container.it's so weird,I don't know why :(
![图片](https://user-images.githubusercontent.com/63415263/162416264-cc8fd25d-0bad-4a14-b341-c999f1f2e51f.png)
![图片](https://user-images.githubusercontent.com/63415263/162416295-dbceb087-41f8-4171-8d42-22d2cb9f974d.png)

**Comment by BlueIceJAY** [comment]
Thanks for you suggest and your recommended videos!but emmmmmm...actually my design is based on packager and unpackager,I use ae2 put the items in compressed chest in order,then send the chest to the assembly line array,finally feed each assembly line through an unpackager.I mainly like this design with relatively low silent stutter, better parallelism, and convenient pseudo-synthesis.
![图片](https://user-images.githubusercontent.com/63415263/162417338-4f4a9fd1-bc99-4130-8cb5-aa9365aa9adf.png)
![图片](https://user-images.githubusercontent.com/63415263/162418008-c8f30d44-b0c0-4af6-9217-8499f5715c6c.png)
![图片](https://user-images.githubusercontent.com/63415263/162419597-cd27f5c3-4b64-43b8-bbdc-9791798bc7aa.png)

**Comment by GlodBlock** [comment]
avaritiaddon's creator always has some *creative* design in his code.
