### ISSUE TITLE
Stop ccl_modular from dumping classes in the .minecraft on every game start

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#10116]
### Your GTNH Discord Username

Alexdoru#9395

### Your Pack Version

GTNH 2.1.2.3QF3

### Your Proposal

those classes are beeing dumped on every game start could you just disabled it 
![image](https://user-images.githubusercontent.com/57050655/162495762-68e689a7-cee8-4942-9451-687192a8e93e.png)

### Your Goal

I want my .minecraft to look clean

### Your Vision

make it stop

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by MuXiu1997** [comment]
@Alexdoru 
Here is a configuration file that may be helpful to you
The path to it should be `***/.minecraft/config/CodeChickenLib.cfg`

```cfg
#CodeChickenLib configuration file.

dump_asm=false

```

**Comment by Dream-Master** [comment]
why they need to be dumped in the first place ?

**Comment by MuXiu1997** [comment]
> why they need to be dumped in the first place ?

For debug? Actually, I'm not so sure.
@Glease

**Comment by Glease** [comment]
for debugging. turning it on when something goes wrong is usually just too late.
