### ISSUE TITLE
Chemical Bath GUI does not have a fluid output slot or auto-output button

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10121]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expect the chemical bath to have a slot for output fluids and a visual button for auto-fluid--output as there are recipes that have fluid outputs. Specifically I have tried the Advanced Chemical Bath (MV) and the cooling recipe for Kanthal which has IC2 hot coolant as a fluid byproduct.

![image](https://user-images.githubusercontent.com/40274384/162567839-bd7e48b7-82a8-4cbc-93d6-4eeefd23f110.png)

### The Reality

The functionality is all there but the GUI does not reflect that:
![image](https://user-images.githubusercontent.com/40274384/162567898-a6eaa355-c008-4923-bb43-8bcc83effeac.png)

you can actually hover over the empty spaces: 
![image](https://user-images.githubusercontent.com/40274384/162567926-4992a986-9901-4925-8802-764b6abfa813.png)

### Your Proposal

update the chemical bath GUI to have a visual fluid output slot and auto-fluid-output button.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@chochem i guess you using a texture pack. GT Texture is fine

**Comment by chochem** [comment]
oh you are right, forgot about them changing GUIs too. Yeah without resourcepacks it is all good. Sorry about that. :)

**Comment by Dream-Master** [comment]
@chochem you can easyly added a new slot via Photoshop or another graphic programm. Even in your Texture Pack files
