### ISSUE TITLE
Fixing Lava and Water Sigils used in Infusion recipes

### ISSUE THREAD

**Issue by NikitaGamer64** [GTNewHorizons/GT-New-Horizons-Modpack#10135]
### Your GTNH Discord Username

Никита#8621

### Your Pack Version

2.1.1.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to put a Lava/Water Sigil (Blood Magic) on Thaumcraft’s Arcane Pedestal by hand, with right-click or at least shift-right-click.

### The Reality

For some reason, instead of putting the sigils, the lava/water source block was put on the pedestal, so, instead of just being used as an infusion ingredient, the sigil has simply been activated.
With shift-right-click, nothing even happened.

### Your Proposal

Can you fix it so I can put these sigils on a pedestal with right-click and putting liquids at the top with shift-right-click?

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment]
use hopper or other things that move items

**Comment by NikitaGamer64** [comment]
> use hopper or other things that move items

There’s the thing: I made this issue so there should be possible to do stuff without hoppers or conduits, just by hand.
