### ISSUE TITLE
Thaumic Horizons Self-Infusions disappear on dimension change

### ISSUE THREAD

**Issue by Voxxynn** [GTNewHorizons/GT-New-Horizons-Modpack#10138]
### Your Pack Version

2.1.2.0

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

For self infusions to remain after changing dimensions

### The Reality

All self infusions disappear, specifically upon returning to overworld. It seems likely the specific trigger is getting a different potion effect while in another dimension: however, Ive not been able to reproduce the issue perfectly consistently. After they break, the potion effect buffs (diamond skin, etc) will remain active in GUI, but toggle able buffs (spider climb and invisibility) will no longer function. Also, warp tumor will no longer deduct warp.

### Your Proposal

Some changes were made to self infusions to prevent warp tumor from double triggering, it seems possible that this has caused breakages: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8907

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
It's related to the weird health bar, xp bar dimension change reset glitch, exiting your world to the main menu and coming back corrects it
