### ISSUE TITLE
Shepherd's Pie Converts to Cottage Pie

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#10132]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

2.1.2.3qf

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Crafted Shepherd's Pie and it showed it would craft to a Shepherd's Pie.

### The Reality

Crafted Shepherd's Pie and when it moved into my inventory it converted into Cottage Pie (similar to how the flour converts).

### Your Proposal

Fix it so Shepherd's Pie doesn't auto convert into another food item.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
It doesn't convert, two recipes are the same. I will fix it tomorrow probably

**Comment by Pxx500** [comment]
![image](https://user-images.githubusercontent.com/81298696/236342363-36936426-1d88-415e-80d3-0248a4479dc9.png)
Doesn't convert
