### ISSUE TITLE
Strange dupe bug with Smeltery

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#10146]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

![bug smeltery #1](https://user-images.githubusercontent.com/29717217/163227034-39b68d66-515b-40a2-8f7a-906d9d6dfb1d.png)
![bug smeltery #2](https://user-images.githubusercontent.com/29717217/163227039-6759c40e-b62d-419a-b014-de118254b2ea.png)
![bug smeltery #3](https://user-images.githubusercontent.com/29717217/163227040-d1e4cfd7-e6cb-47c9-a782-c9f00afdeb48.png)

Before closing the game i melted few things in smeltery and with the help of nugget cast and ingot cast got metals from it, before leaving the world smeltery was empty and on the casting table there was an nugget cast.
After i came back strange things happened, i right clicked on cast and instead of getting nugget cast back i got ingot cast instead. And the strangest thing happened with the smeltery - somehow all the metals i melted and turned into metals and ingots were in smeltery again and at the same time i had all the metals and ingots i got before leaving the game in my inventory o_0 Screenshots above.

### The Reality

null

### Your Proposal

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
looks like a missing markDirty somewhere
