### ISSUE TITLE
Thermal Boiler does not output Steam with lava

### ISSUE THREAD

**Issue by Exelion42** [GTNewHorizons/GT-New-Horizons-Modpack#10143]
### Your GTNH Discord Username

Exelion#8813

### Your Pack Version

2.1.2.1-3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Pumped lava into a GT++ thermal boiler (with lava filter), expected to get steam, lava byproducts and phahoe (like the NEI recipe, the questbook description and the block description suggest)

### The Reality

Only got the byproducts, no Steam (not using up water), no phahoe.

### Your Proposal

I don´t konw if this is a bug or intentional. 
If if is the first, fix/change the behavior of the thermal boiler. 
If it is the latter, change the description of the machine and the corresponding quest.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by pd2s** [comment]
2.2.0.0, same problem with normal lava.  No pahoehoe, no steam, no water consuming, lava filters do not break, getting only byproducts

**Comment by ImpTs** [comment]
I'm also having this issue with pahoehoe and distilled water. I am running on 2.1.2.4-29-pre from 08-18

**Comment by Ajes1337** [comment]
I am also having this problem, cannot generate pahoehoe with lava in thermal boiler, I am on version 2.2.0.0 (NEI states that you can)

**Comment by Ajes1337** [comment]
getting server-side nullpointer exception when turning on the thermal boiler 
![image](https://user-images.githubusercontent.com/11885892/205347951-c39b5058-81e3-40ad-9630-0103ac6efbf9.png)

**Comment by mitchej123** [comment]
Can you upload that section of the log itself? or check gregtech log?  Need to see where the NPE is coming from

**Comment by Ajes1337** [comment]
@mitchej123 yup

[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10143202/GregTech.log)

![image](https://user-images.githubusercontent.com/11885892/205353301-92773ad8-1158-49f2-9b66-216a4b745677.png)

![image](https://user-images.githubusercontent.com/11885892/205353440-f3c56daa-f9b3-4d11-9b84-5ba46e5a5f8f.png)

**Comment by PhoenixtheII** [comment]
No pahoehoe lava from a lava drilled on Ross128b on v2.2.3 here either.

**Comment by Ajes1337** [comment]
I quickly tried the changes out in the newest 2.2.8 version of the thermal boiler (it ofc explodes now if you activate it without supplying it water) - so after I supplied it water, it generates steam... to my the steam is just a by-product, I really want the pahoehoe that NEI shows it can generate. but so far I have had no luck in getting pahoehoe out of the machine 🤷‍♂️ 

btw the machine also eats up alot of the lava-filters now for generating the byproducts, maybe way too much compared to how little tungstate you get out of the process..

If the machine cannot generate the pahoehoe, I would rather use the old buggy version that did not consume lava-filters for generating tungstate :b (maybe I should just make another machine to make the pahoehoe lol)
