### ISSUE TITLE
Strange crash with after seeing missing textures

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#10145]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Loaded into the world, gregtech's pipes and machines had ".name" in waila and missing textures, right clicked on machine after that world crashed

### Crash Report

[crash-2022-04-13_19.21.21-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8483084/crash-2022-04-13_19.21.21-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
The crash is a separate issue, but tiles going to .name with facade covers on them is a known issue (See https://github.com/GTNewHorizons/GT5-Unofficial/pull/974). Not sure if this is what happening to you.

**Comment by MadRatSRP** [comment]
> The crash is a separate issue, but tiles going to .name with facade covers on them is a known issue (See [GTNewHorizons/GT5-Unofficial#974](https://github.com/GTNewHorizons/GT5-Unofficial/pull/974)). Not sure if this is what happening to you.

I don't have any covers neither on machines nor on cables :D

**Comment by Glease** [comment]
Then I have no idea. The crash report is an extremely generic one. Maybe look at GregTech.log and fml-client-latest.log?

**Comment by MadRatSRP** [comment]
[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8487103/GregTech.log)
[fml-client-2.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8487104/fml-client-2.log)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8487105/fml-client-latest.log)

Here are the files, a bit more information - sometimes when you teleport to JM's viewpoint you're getting stucked in 2 blocks height space and in rare case minecraft doesnt load the world properly after tping, so i had to exit to menu and then load to world, and after loading to world this bug happened

**Comment by Glease** [comment]
Try restore from a backup maybe... honestly no idea what's happening. maybe others would have better ideas.

**Comment by MadRatSRP** [comment]
> Try restore from a backup maybe... honestly no idea what's happening. maybe others would have better ideas.
Restoring from backup before crash helped, but when i tried to open backup saved right when this crash happened winrar showed unexpected end of archive error

**Comment by boubou19** [comment]
looks like a corruption to me. Not much we can do in that case

**Comment by Glease** [comment]
They are not connected to texture loading. They will using missing texture texture for a short period at chunk load because meta tile id has not been sent to the client side, even if it's in single player mode. Minecraft single player is really just a server and client stuffed into one process.

Since it appears to be a corruption, there isn't much we can do here. Closing for now.
