### ISSUE TITLE
ME calculating the number of bytes

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#10157]
### Your GTNH Discord Username

Кетцаль#0802

### Your Pack Version

2.1.2.1

### Your Server

Server Zvezdolet

### Type of Server

Other MCPC+ fork

### Your Expectation

request 2 macerators = 78k bytes (zpm circuits are already in the ME)
removed zpm circuits  recipe -> 2 macerators  = 60k

If you request item and some resources already in me, ME still counts bytes and on their craft.
The more ME can craft, the more expensive in bytes the craft will be

### The Reality

.

### Your Proposal

ME does not add bytes of resources that will not be crafted

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
That's an old AE2 bug, and it is kind of not trivial to fix. It requires some major crafting CPU calculator refactoring.
