### ISSUE TITLE
Lithium Fluoride dust (ID7785) cannot be extracted to liquid (ID6934:972) (for LFTR)

### ISSUE THREAD

**Issue by Exelion42** [GTNewHorizons/GT-New-Horizons-Modpack#10154]
### Your GTNH Discord Username

Exelion#8813

### Your Pack Version

2.1.2.4-5

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Having a possibility to convert lithium fluoride dust item (ID7785; GT++) into liquid lithium fluoride (ID6934:972; GregTech)

### The Reality

There is no way, at leats no direct one (via fluid extractor).

### Your Proposal

Make a recepie for that conversion. Or tell me that this is intentional ;)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment]
A recipe for this isn’t auto generated because you can’t fluid extract dusts. Neither mod is aware the other mods thing exists, so someone would have to manually add such. If they’re used for totally different uses, conversion probably shouldn’t be allowed.

**Comment by Exelion42** [comment]
So that´s what I asked myself, if it is planed that way or not.

**Comment by Exelion42** [comment]
I have done some more "research", by scrolling back and forth in NEI. And as far as I can tell is there no way to produce liqud lithium fluoride. This is a problem, as you need it for the production of fuel for the LFTR. So I guess a recepie for the conversion from dust (or something else) to liquid needs to be manually added.
