### ISSUE TITLE
fix Optifine changing chunkloading mode to multicore when you change your gui scale

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10159]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Proposal

prevent OF from changing its chunkloading mode when you change the gui scale

### Your Goal

avoid stupid crashes that shouldn't even happen

### Your Vision

This bug is ancient in optifine, and i think this would help tons of people asking in #help why the fuck their game keep crashing after they have changed their gui scale. I know it has already been reported before (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7334) but i think it's worth the effort to mixin/asm optifine to stop this.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Eranicus** [comment]
Hmm interesting... I play with multi core chunk loading for more than a year without a single crash related to it or any visual problems.

**Comment by Glease** [comment]
Multicore chunk loading has 0 effect if you play on servers.

**Comment by Eranicus** [comment]
I play single player only, and the only thing I cant do with multi core is chisel blocks and its because i have AMD card, with Nvidia you can make chisel work with multi core option.

**Comment by boubou19** [comment]
> Multicore chunk loading has 0 effect if you play on servers.

tell that to my game: if it's not on default chunkloading , i end up with "already tesselating" crashes and i play on delta
