### ISSUE TITLE
hodgepodge's bop fixes crash game

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/GT-New-Horizons-Modpack#10150]
### Your GTNH Discord Username

mini_ben#0027

### Your Pack Version

2.1.2.3qf with newest hodgepodge

### Your Server

SP

### Your Actions

update hodgepodge to the newest one in jenkins

### Crash Report

[crash-2022-04-14_00.21.40-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8486274/crash-2022-04-14_00.21.40-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@bjin2000 please stop using new mods in existing versions. You need to backdate your bop version to lastest curse version.
Do me a favor and wait for a 2.1.2.4 dev. Thanks
