### ISSUE TITLE
OC charger cant be crafted

### ISSUE THREAD

**Issue by joinusordie** [GTNewHorizons/GT-New-Horizons-Modpack#10155]
### Your GTNH Discord Username

join us or die#2061

### Your Pack Version

2.1.2.1

### Your Server

Zvezdolet

### Type of Server

Ultramine

### Your Expectation

Trying to crаft 1 Charger.
![image](https://user-images.githubusercontent.com/61594234/163549732-4d50c70d-b80c-430b-bf08-30c050f3a75e.png)

### The Reality

Charger is not craftable.
![image](https://user-images.githubusercontent.com/61594234/163549770-4828530a-0a77-4276-8c01-6e2c251748a3.png)

### Your Proposal

Maybe it's a problem with the Charge Pad(MFE).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment]
i made one yesterday/ im on 2,3gf, i used gt++ assembler

**Comment by LewisSaber** [comment]
@joinusordie did u use right fluid?

**Comment by joinusordie** [comment]
@LewisSaber polyethylene

**Comment by KamenriderZO** [comment]
Can't craft either in latest version 2.1.2.4-18
Why can't we change this recipe? Charger pad(MFE) is not stackable at all.
Why not change it to a single GT battery (MV or HV or EV all be fine) 
As a crazy fan with robots we can only get chargers through Cheating???
![ESIDPJ22P%EXRBJFG5B6S1R](https://user-images.githubusercontent.com/77818313/178228018-1c3c9b9a-ad33-458c-9325-860b8421a726.png)

**Comment by Zereff06** [comment]
and keyboard is not crafted in PA

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
