### ISSUE TITLE
Allow Fine Soldering Alloy IN IC2 Tool Box

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#10172]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

2.1.2.3qf

### Your Proposal

Allow storage of Fine Soldering Alloy Wire inside the IC2 Tool Box. If worried about "free backpack space too easy, etc" then only allow Fine Soldering Alloy Wire and not anything else.

### Your Goal

 Easy of use for repairing multiblocks.

### Your Vision

Make the tool box every man's (or woman's) handy box of handiness.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Already fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1002
