### ISSUE TITLE
Give Mega MBs Scaled-Up Controller Faces

### ISSUE THREAD

**Issue by Aurastorm** [GTNewHorizons/GT-New-Horizons-Modpack#10175]
### Your GTNH Discord Username

Aura#0696

### Your Pack Version

2.1.2.0

### Your Proposal

Make certain mega multiblocks feature scaled-up controller faces (see attached image I photoedited some time ago). 
![mega_vf_smol](https://user-images.githubusercontent.com/6663834/164010540-7db9a706-e2c8-47c9-85ec-fecd08c6f117.png)
This would feasibly only apply to mega MBs with homogenous front faces, such as the MDT and MVF, and notably not the MEBF. 

### Your Goal

Mega MBs look a bit silly imo.
They look a bit like this:
![img-1421492-1-tumblr_m9lhpmFTuq1resz14o1_1280](https://user-images.githubusercontent.com/6663834/164011390-96ca9208-9639-4ad7-9a12-b49a9d321d9b.jpg)

### Your Vision

Simply put, I think that first image I put here looks better than what the current MVF looks like.

Plus, I think that walking through a hallway of mega MBs in a lategame base and seeing giant activity indicators on each one (with or without MEBFs) would be pretty darn nice looking.

Besides, if turbines can have those kinds of scaled up front faces, why not other multis? 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
While I'd like to see something like this to happen, we don't currently have the required technical infrasturcture for this. mitch's multi tile entity is a step in the right direction, but it alone is probably not enough to suppport this.

**Comment by Aurastorm** [comment]
@Glease Would some of the turbine code potentially be able to be ported into Mitch's MB code?

**Comment by GTNH-Colen** [comment]
Honestly I'd rather just see a "better" structure for these multis as they are kinda bland at present.
