### ISSUE TITLE
Large Processing Factory does not accept multiple Energy Hatches to perform higher voltage recipe

### ISSUE THREAD

**Issue by miozune** [GTNewHorizons/GT-New-Horizons-Modpack#10180]
### Your GTNH Discord Username

miozune#9742

### Your Pack Version

2.1.2.2qf2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Try to perform recipe `Glowing Coral -> Sunnarium Dust (7680 EU/t)` by Large Processing Factory with 2 EV Energy Hatches attached.

### The Reality

The machine doesn't start. I then replaced 2 EV Energy Hatches with 1 IV Energy Hatch, and it worked, so it's not an issue with configuration.

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Rubix2048** [comment]
I had thought this was intentional, as it seems to occur with all GT++ machines, but idk

**Comment by miozune** [comment]
No? I can make Chrome-Iron Plate (LuV tier) with my multi Forming Press with 2 IV Energy Hatches attached.

**Comment by Rubix2048** [comment]
Oh really? Huh... Come to think of it, I may have just assumed that to be a property of all GT++ machines. Maybe try the alloy blast smelter? I swear I thought I tested this, but I could well be mistaken. The LPF does certainly have this issue, I was doing sodium tungstate solution in the autoclave mode and it did not start either, I can corroborate there.

**Comment by boubou19** [comment]
i confirm the LPF on 2.1.2.0
