### ISSUE TITLE
recipe of precise auto Assembler MT-3662 needs Ad

### ISSUE THREAD

**Issue by tkjoker1996** [GTNewHorizons/GT-New-Horizons-Modpack#10194]
### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Your Expectation

I want to craft neutron activator to get Nq with its by-products Ad, but the recipe of the machine to craft neutron activator need Ad gears.

### The Reality

recipe of precise auto Assembler MT-3662 needs Ad, which is available at least in T5.

### Your Proposal

change the recipe of precise auto Assembler MT-3662.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GoodGenerator/pull/20
