### ISSUE TITLE
GT++ Power Station not forming after update to 2.1.2.0

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#10197]
### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

PSS should form was prior to the update. Control block gave me error 64 prior to update

### The Reality

I've completed torn down the structure, unloaded and reloaded the chunk. It contains a control block, LuV power cells, 4 LuV buffered dynamos, 2 energy hatches. 1 LuV energy dynamos. Structure blocks changes color like it's forming but stays non-functional.  I tried rolling back to prior GT plus plus GTNH version but mixin crashes. Use of control cores is turned off.

### Your Proposal

I have no idea what I am missing 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eason134HK** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10199
you don't need the maintenance hatch

**Comment by redmage17** [comment]
> #10199 you don't need the maintenance hatch in 2.1.2.0

Yep not part of the structure still refuses to fully form

**Comment by GTNH-Colen** [comment]
This is a pretty serious bug tbh given a lot of peoples bases still rely on the PSS for power.

**Comment by LewisSaber** [comment]
mine on 2.1.2.3gf works fine

**Comment by Glease** [comment]
Tagging as fixedindev for now, unless proven otherwise.

**Comment by Sphyix** [comment]
> Tagging as fixedindev for now, unless proven otherwise.

There was an issue with the structure check with dynamos, not sure if it was fixed in dev.
Basically all the dynamos/hatches on the roof of the machine, in the pattern below, stop the PSS from forming
![chrome_zcPr5Os89Z](https://user-images.githubusercontent.com/17811922/165053456-ec9edccb-b812-420f-897a-99819c590409.png)


Ingame:
![javaw_DAhCcenYsb](https://user-images.githubusercontent.com/17811922/165052805-a62dd739-a54b-4354-93fb-e87f6cd15bd1.png)

**Comment by Glease** [comment]
I honestly don't see how it's not forming. The hatch texture changes. Maybe there were a broken checkHatch implementation that rejected your hatches, but this does not happen in dev
![image](https://user-images.githubusercontent.com/4586901/165069009-9084023b-57bc-4fb1-9ef2-347f3e5dcde5.png)

**Comment by Sphyix** [comment]
My tests are on 2.1.2.0 (on delta)
It's probably fixed on dev

**Comment by redmage17** [comment]
My hatches are in about the same location. This may be the case - is their a stable version of dev that is recommended? QF is giving me a expecting stack map frame error

**Comment by redmage17** [comment]
Fixed in Dev

**Comment by redmage17** [comment]
Well no now it forms yet says it needs more power

**Comment by redmage17** [comment]
Nvm refilling
