### ISSUE TITLE
Neutron sensor from neutron activator (Naquadah line) is crashing the game

### ISSUE THREAD

**Issue by Eranicus** [GTNewHorizons/GT-New-Horizons-Modpack#10206]
### Your GTNH Discord Username

Eranicus#5476

### Your Pack Version

2.1.2.4 (kevlar line)

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

For neutron sensor to work properly.

### The Reality

Every time you click on neutron sensor, game crashes

crash log from clean 2.1.2.4 pre-dev

https://pastebin.com/gtJY1tBr

(I have same situation with my main game on v, 3qf + some main mods updated from jenkins)

### Your Proposal

Please fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
https://github.com/GTNewHorizons/GoodGenerator/commit/611e7e1d3ed76fc8839c2206d6ad296c83df44ac#diff-c1dddebf7c2b0c88876fbe822fb69f0632fa30744c3e0b6fd5e8f0d93b528b8dR43

@GlodBlock You have a duplicate discriminator here. MessageOpenNeutronSensorGUI is now being handled as a MessageResetTileTexture when received.
