### ISSUE TITLE
Add option to put Liquid Blueslime in Fluid Solidifier

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10202]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Proposal

To allow a recipe in the Fluid Solidier to turn 1000L of Liquid Blueslime into 1 Block of Congealed Blue Slime

### Your Goal

To further allow for Slime islands to be harvested for resources

### Your Vision

This would further increase the resource value of slime islands

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TwoTailedFox** [comment]
Any update on the feasibility of this one?

**Comment by LazyFleshWasTaken** [comment]
Seems like a good idea to me. Can you consider this again. Also the blue slimedirt centrifuging that seems to not be in newer versions.
