### ISSUE TITLE
Sorting mode not working on input bus

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#10217]
### Your GTNH Discord Username

Alexdoru#9395

### Your Pack Version

dev 2.1.1.3

### Your Server

solo

### Your Expectation

I expect the following stacks to merge on their own and or the machine to recognize the craft and start crafting

![image](https://user-images.githubusercontent.com/57050655/165206173-67f9da3c-5a6f-414d-9730-7955513627bd.png)

### The Reality

The items stay like this in the input bus and the machine never crafts

### Your Proposal

please fix it makes my machines throttle and the crafts never ends

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
It appears the last slot was intentionally excluded from sorting... probably a copy pasting error from buffer sorting code.
