### ISSUE TITLE
Platline processing

### ISSUE THREAD

**Issue by Team1Warlord** [GTNewHorizons/GT-New-Horizons-Modpack#10219]
### Your GTNH Discord Username

KOT_BHE_3AKOHA#7758

### Your Pack Version

2.1.2.1

### Your Proposal

Platinum concentrate re-crystallization recepie (HV tier recepie) in LCR on screenshot should be fixed
![image](https://user-images.githubusercontent.com/55826128/165336355-8b726bfc-3168-422a-8129-986287739b69.png)
[](url)

### Your Goal

LV LCR recepie processing faster than HV recepie on any tier, so this recepie is a bit broken in my opinion. Just a bit math to proove:
HV tier: 33.75 sec vs 70 sec
EV tier: 8.4375 sec vs 17.5 sec
IV tier:  2.11 sec vs 4.375 sec
etc.
HV tier recepie is a bit better than LV tier recepie bcs of making normal dusts instead of tiny dusts, but it still does not justify the difference in time of processing (more than twice).

### Your Vision

In my opinion HV tier recepie should work a bit slower than LV tier recepie, for example 35-40 sec for a recepie, bcs u dont have to make normal dust from tiny dusts.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNHAfx237v7** [comment]
Isn’t the LV recipe a candidate for removal anyway?

**Comment by Alexdoru** [comment]
yes it's slower at low tiers, but the long processing time allows to reach more overclocks at higher tier. The recipes costs the sames amount of energy so i don't see any problem

**Comment by Team1Warlord** [comment]
it is still slow on high tiers and its more profitable to use LV recepie instead of higher tier recepie. Suggestion about making it 480 eu/t and 35 sec is the best solution of the problem in my opinion

**Comment by Alexdoru** [comment]
> it is still slow on high tiers and its more profitable to use LV recepie instead of higher tier recepie. Suggestion about making it 480 eu/t and 35 sec is the best solution of the problem in my opinion

please no that would make it loose one possible overclock at high tier

**Comment by Rubix2048** [comment]
That's a point, I guess? If people use one hatch of some voltage it can't OC the last time. Eh, leave it then.

**Comment by Sphyix** [comment]
> > it is still slow on high tiers and its more profitable to use LV recepie instead of higher tier recepie. Suggestion about making it 480 eu/t and 35 sec is the best solution of the problem in my opinion
> 
> please no that would make it loose one possible overclock at high tier

What do you mean? Less time for the recipe means you reach 1 tick processing 1 tier earlier. You can't go faster than 1 tick, so it doesn't matter at what tier you reach it.
Both recipes should be equal in time/output so change is needed here
