### ISSUE TITLE
Dolly Placing JABBA Barrel on Hopper Crashes Server/World Ticking Block Exception

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#10213]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

Kevlar Test Pack

### Your Server

Private Server

### Your Actions

Placed barrel on top of a hopper and server/world crashed. Ticking block exception. This worked prior to Kevlar Test Pack.

### Crash Report

I lost this file during a restore of the server...

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
Could you try set `fixHopperVoidingItems` to false in hodgepodge.cfg?

**Comment by shawnbyday** [comment]
> Could you try set `fixHopperVoidingItems` to false in hodgepodge.cfg?

Thanks :) This fixed the crash! It's also worth noting that it also fixed a weird issue I was having with my bee hopper automation setup...so maybe something to keep in mind. Before I changed this a hopper would pull the bee and the drone out of the input slot on the apiaries so the bees would never breed.

**Comment by TenchiRyokoMuyo** [comment]
Commenting for knowledge - Same issue, placed barrel onto hopper. Caused instant 'server closed' message. Applied fix with success. Server started up again with no problem and barrel/hopper functioned as expected afterwards.

**Comment by YannickMG** [comment]
Is this still an issue?

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
