### ISSUE TITLE
Insert Into Chest/Crafting Station Seems Backwards

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#10210]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

Kevlar Test Pack

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Output from GT Universal Macerator into vanilla double chest  to go in top row first.

### The Reality

Goes in 4th row first. Tinkers Construct Crafting Station also starts at bottom right first...seems different than it used to be.

![image](https://user-images.githubusercontent.com/33701188/165178074-cac5e451-c74b-4e1f-aedd-0b105e1c5657.png)

### Your Proposal

Fix?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
It depends on which of the two chests you are outputting to. Not a bug afaik.

**Comment by shawnbyday** [comment]
@Glease but if it fills up the bottom half of the chest and never fills up the top half of the chest? The machine just buffers but only the bottom half of the chest is full. That seem like a bug?

**Comment by Glease** [comment]
You should have mentioned it doesn't fill the other chest...

**Comment by shawnbyday** [comment]
> You should have mentioned it doesn't fill the other chest...

My brain is broken most of the time, sorry. Would this have anything to do with my other open issue about machines outputting into barrels?
