### ISSUE TITLE
Clay Electrolysis Reverted to Silicon and Aluminium Dust?

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#10216]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

Kevlar Test Pack

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Expecting Silicon Dioxide and Alumina Dust from electrolyzing clay.

### The Reality

![image](https://user-images.githubusercontent.com/33701188/165193218-c44c8fd3-7408-4835-b4df-ea2751c8210c.png)

### Your Proposal

Not sure if this is an expected change or not. From my understanding this looks like our old recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
i revert it to orginal recipe because the chemical formular was wrong . Convince me to change this back :)

**Comment by shawnbyday** [comment]
I think it is fine as the old recipe, especially with the new silicon processing line. Was just surprised to see it. I think with new silicon line this actually feels better.

**Comment by Alastors** [comment]
> i revert it to orginal recipe because the chemical formular was wrong . Convince me to change this back :)

bruh, why add in the new line if you're just going to do this, nix the new alu line if this is the case, redundancy is redundant

**Comment by Alastors** [comment]
> i revert it to orginal recipe because the chemical formular was wrong . Convince me to change this back :)

it's the same bs as this: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9909 if you leave it in dream, this is clearly making clay overpowered compared to the other options to make aluminia dust, so why the hell would anyone use anything other than clay dust???

**Comment by chochem** [comment]
hmm. if dream wants this to be alu dust, one option for could be to remove the tinker-raw-alu-EBF route so that alu dust cant be immediately processed trivially in early MV. Then clay dust-> alu dust only becomes strong with kanthal coils and you still use alumina before.


See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10041 if you dont know what the tinker-raw-alu-EBF for reference.
