### ISSUE TITLE
Batty Species from Magic Bees has a String specialty, but is unable to produce it.

### ISSUE THREAD

**Issue by smudgerox** [GTNewHorizons/GT-New-Horizons-Modpack#10225]
### Your GTNH Discord Username

Smudge#1285

### Your Pack Version

2.1.2.3QF

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

The Batty species should be able to produce string, or the specialty should be removed. I assumed the display was bugged, but it turns out that the production chance is 0.00001%.  The minimum chance for any product should be 1%.
![image](https://user-images.githubusercontent.com/2375161/165617884-f1d252a3-4b81-4430-90c8-6baf56999727.png)
![image](https://user-images.githubusercontent.com/2375161/165617977-64809561-e774-483f-aab2-706e8c3ead3c.png)

### The Reality

The bee does not produce any string with maximum production boost.

![image](https://user-images.githubusercontent.com/2375161/165619451-13e00e73-013d-4556-ab6f-7ca8fe019e3a.png)

### Your Proposal

I propose either removing the chance from the species entirely so it's not potentially misleading, or changing it so that the bee can actually produce string, as it would be an excellent source for Powderbarrels. Spidery bees can produce string, however Batty is a much longer breeding chain, so I think it's fine to have it produce it as well.
[Line 80 in this class](https://github.com/GTNewHorizons/MagicBees/blob/master/src/main/java/magicbees/bees/BeeProductHelper.java)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ScriptedPiky** [comment]
Gave it a good ol' fix. Though not sure if I should lower the string chance from 20% to something like 10% for balance concerns, heh
