### ISSUE TITLE
Input Hatches Accepting more than their usual Capacity, and duping Fluid (Distilled Water)

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#10224]
### Your GTNH Discord Username

TrainerSnow#5086

### Your Pack Version

Latest from #announcements [ 23.04.2022}

### Your Server

Private dedicated

### Your Expectation

Tried to setup LHE, inserted distilled Water via gregtech pump
Expected it to fill up the input hatch.

### The Reality

While, only WHILE, the LHE is running, Dt. Water is still being inserted into the Input Hatch, over the Max Capacity. 
Distilled Water from the input container is not being used up (Duplicated)

![grafik](https://user-images.githubusercontent.com/81151019/165608129-fdf33555-e53e-4c3e-800d-83bd3cc74ecc.png)

https://user-images.githubusercontent.com/81151019/165609201-b671ada3-d31f-4bec-a513-d03700f22387.mp4

![grafik](https://user-images.githubusercontent.com/81151019/165609759-93808f05-deeb-429b-be6c-af3f7f9eba03.png)

IDK if its the input hatch, distilled water or the LHE is that broken

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@GlodBlock is this maybe related with the 4x input hatch you added recently ?

**Comment by Glease** [comment]
Might be a LHE problem.
