### ISSUE TITLE
Make the GTUnofficial cryolite (the stuff you can mine from TF) eletrolyzable

### ISSUE THREAD

**Issue by TomatoSoup1** [GTNewHorizons/GT-New-Horizons-Modpack#10222]
### Your GTNH Discord Username

MajorTom#2873

### Your Pack Version

2.1.2.0

### Your Proposal

Make the GTUnofficial cryolite (the stuff you can mine from TF) eletrolyzable, just like the GT++ cryolite is. Simplest would be to Oredict it so that they are treated the same, where you can electrolyze both and use both to cook aluminum in MV.

### Your Goal

Getting fluorine is a pain in the butt, and I have two options as of this version: electrolyze stonedust, which takes forever and requires a lot of power/infra, or do crops, which I don't like. Cryolite has plenty of fluorine, and the GT++ cryolite which is molecularily identical is electrolyzable, but not obtainable for some reason, which is inconsistent. Also, its completely useless after MV, and this gives it a new purpose.

### Your Vision

Having an extra option to obtain fluorine in HV for PTFE and other things would be nice. This pack is unusually good at providing multiple solutions to a single problem, and I think this aligns well with that. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/252
