### ISSUE TITLE
Monocrystalline Silicon Boule Uncraftable (Teflon Test Pack)

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#10220]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

Teflon Test Pack

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

32x Silicon Dust + 1x Small Pile of Gallium Arsenide Dust = 1x Monocrystalline Silicon Boule

### The Reality

16x Silicon Electronic Grade (Mono SI) Dust + Small Gallium Arsenide Crystal = 1x Monocrystalline Silicon Boule
AND
32x Silicon Solar Grade (Poly SI) Dust + Small Gallium Arsenide Crystal = 1x Monocrystalline Silicon Boule

Cannot craft:
* Silicon Electronic Grade (Mono SI) Dust <-- used in 16x recipe (is this only intended to come from cutting the boules?)
* Small Gallium Arsenide Crystal

![image](https://user-images.githubusercontent.com/33701188/165368700-753a2528-8a43-4529-9d90-d4812e3e0eaa.png)

### Your Proposal

* Add recipe to process 16x Silicon Electronic Grade (Mono SI) Dust (unless it is only intended to come from cutting the boules).
* Add recipe to craft Small Gallium Arsenide Crystal OR change back to using Small Pile of Gallium Arsenide.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
SIeg will be removed so only the SIsg recipe will stay

**Comment by Dream-Master** [comment]
small gallium crystal can be made in the forge hammer so far ik

**Comment by shawnbyday** [comment]
> small gallium crystal can be made in the forge hammer so far ik

How do you make the Gallium Crystal in general? Maybe my NEI is just bugged? Neither have a recipe that I can see.

**Comment by Dream-Master** [comment]
Let me join the game and i can check the recipe

**Comment by Dream-Master** [comment]
wired. Must be some data loss on my side. A few commits not added. Will add a recipe

**Comment by shawnbyday** [comment]
Okies, if you have a patch build let me know on Discord or here and I'll load it up so I can keep exploring that line.

**Comment by Dream-Master** [comment]
https://www.dropbox.com/s/3eje62ippkek8bk/GTNH-Kevlar-and-SI-Test.zip?dl=0

**Comment by Dream-Master** [comment]
just forget the dev core mod version

**Comment by shawnbyday** [comment]
Thanks! Loading up now.
