### ISSUE TITLE
Right click on (connected?) AE2 P2P gives you X, Z, Z coords in your chat.

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/GT-New-Horizons-Modpack#10231]
### Your GTNH Discord Username

Gates_ice#4537

### Your Pack Version

2.1.2.3qf

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

![image](https://user-images.githubusercontent.com/2586057/165828958-c235a55c-060c-42bb-b2d8-061f8f4289e4.png)

### Your Proposal

A coordinate should be X, Y, Z (sometimes X, Z, Y for convenient), not X, Z, Z

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
click with a wrench

**Comment by Gateswong** [comment]
> And whats wrong with this behavior?

A coordinate should be X, Y, Z (sometimes X, Z, Y for convenient), not X, Z, Z

**Comment by repo-alt** [comment]
Weird, looks like some other mod is adding empty hand handling, because wrench works fine. BetterP2P maybe?

**Comment by GlodBlock** [comment]
i don't remember betterp2p has such function.

**Comment by MuXiu1997** [comment]
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/master/src/main/java/appeng/parts/p2p/PartP2PGT5Power.java#L71-L74
