### ISSUE TITLE
Piston plates can only be crafted out of oak plank items

### ISSUE THREAD

**Issue by DirtyFaced** [GTNewHorizons/GT-New-Horizons-Modpack#10235]
### Your GTNH Discord Username

DirtyFaced#6746

### Your Pack Version

2.1.2.3qf

### Your Proposal

It should be possible to craft piston plates out of more types of wood plank, not just oak.

### Your Goal

There are many other recipes where you can use any kind of wood. I feel like this one should be one of them.

### Your Vision

Everyone will be happy.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
@DirtyFaced cany you try with dev 18 version ?
