### ISSUE TITLE
Thaumcraft and multiblocks, saving schematic

### ISSUE THREAD

**Issue by Runakai1** [GTNewHorizons/GT-New-Horizons-Modpack#10238]
### Your GTNH Discord Username

Runakai ~ Docsyᵇᵒᵗ#7676

### Your Pack Version

2.1.2.3QF3

### Your Proposal

I will keep this short. 
It would be cool to have a thaumcraft item that can function as a schematic holder. That can hold whole multiblock structures so you can replace multiblocks and place them on demand. This idea came up because I hate setting up multi block miner. 

### Your Goal

It would just be a neat QOL feature as well as giving thaumcraft a bit more cool features. 

### Your Vision

This would just simply bring QOL updates and features and just make people less frustrated lol

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
That’s why we have schematica in the pack, or am I missing a point here?
