### ISSUE TITLE
(Re) Add Angel Wings from ExU Mod

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#10249]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

2.1.2.3qf

### Your Proposal

Wings from Extra Utilities should also be available like other items which provide creativ flight even if these wings do not require any substitude or energy.

### Your Goal

Beside the Draconic Amour, Flügel Tiara or any other items I don't see any valid reason that these items are unobtainable/disabled.
It shouldn't be so hard to to add them so that they are suiting the pack.

Also some players may prefere these wings instead of suites or other armor while for example currently working on a hugh building?

But generally they shouldn't be thrown away :)

### Your Vision

I have thought over this and was finally be able, with some help, to hopefully make suiteable recipes.
A PR will be sended out where you can free discus about the recipes, it's flavor text and how they got implemented.

I'll provide Screens from the Recipes too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Chaoschaot232** [comment]
Research ist placed in Artifice tab and gated behind Infusion. First one is only filled with flavor text and so it is free:
![image](https://user-images.githubusercontent.com/1703441/166158851-8556ea57-b183-4934-87ae-19e19afd24c3.png)

The main recipe ... it was earlier ... well ... more a kind of a meme than what it is now
![image](https://user-images.githubusercontent.com/1703441/166158912-cf0ef8e7-85e1-4fbe-a38c-7fe3d3edaaf3.png)

You want some stylisch Wings? Here you go:
![image](https://user-images.githubusercontent.com/1703441/166159209-0a40de24-3367-4100-8d78-28373f106a52.png)
![image](https://user-images.githubusercontent.com/1703441/166159216-9b2ad8f5-0367-4b07-94f9-dbcb7757521a.png)

**Comment by Dream-Master** [comment]
added
