### ISSUE TITLE
Wireless Charger MK 1 doesn't charge items until world is reloaded, also stops charging after it's chunk is unloaded and reloaded.

### ISSUE THREAD

**Issue by austin1346** [GTNewHorizons/GT-New-Horizons-Modpack#10245]
### Your GTNH Discord Username

Austin#3823

### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Wireless charger (Added by alkalus ID: 1754:890, assuming the rest of them have the same issue) is expected to wirelessly charge items in inventory or being worn (in this case, IC2 electric jetpack).

### The Reality

Wireless charger does NOT charge items in inventory or in armor slots. 

Reloading the world fixes it, but once the chunk it's in is unloaded and reloaded, it's broken again.

### Your Proposal

A world anchor placed nearby will keep it in a working state after the world is reloaded, but it should be fixed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
The gt++ wireless charger has been in this state for a long time: https://github.com/alkcorp/GTplusplus/issues/694

But I guess its good to have a ticket over here now.

**Comment by austin1346** [comment]
Correction, reloading the world does not fix it in SP, you need to restart your entire game. As for a dedicated server, I'm not sure.

**Comment by TwoTailedFox** [comment]
This is still occurring on 2.2.3 with the MKIII charger I'm using.
