### ISSUE TITLE
add a line in the debug menu to show the graphic card

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10241]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Proposal

add a line in the debug menu to show the graphic card

### Your Goal

this can help troubleshoot commutable graphic issues directly from in game

### Your Vision

this will not improve the pack directly,  but will improve troubleshooting for players.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
seconded.

isn't this already normally in the F3 screen in vanilla MC?

It looks like the HydroEnergy mod is messing with things at the moment (2.1.2.3qf) for whatever reason:

![image](https://user-images.githubusercontent.com/40274384/166102046-63bb18d4-20d7-4b4a-9d28-547481fcfe12.png)

**Comment by boubou19** [comment]
it's not in 1.7 vanilla

**Comment by chochem** [comment]
ah my bad, Anyway it would be nice. You can tell the GPU with task manager of course but its not quite as simple as pressing F3.

**Comment by Glease** [comment]
Install optifine and you get it for free.

---

If you hate optifine with a passion, you don't need a mixin either way. There are forge events for this. It's called `net.minecraftforge.client.event.RenderGameOverlayEvent.Text`

**Comment by boubou19** [comment]
it's not in D6 version of optifine, unless i'm blind?
![2022-04-30_21 58 23](https://user-images.githubusercontent.com/12850933/166120829-19ef2fd8-c5be-4545-8125-c8a7062d8553.png)

**Comment by Glease** [comment]
Yeah, I'm being too stupid here. It's not optifine but a different minecraft version.
