### ISSUE TITLE
Game crashed when IC2 generator output eu that exceeds gt wire capacity

### ISSUE THREAD

**Issue by ordpus** [GTNewHorizons/GT-New-Horizons-Modpack#10256]
### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Type of Server

Thermos

### Your Actions

I have a Th fuel IC2 nuclear reactor that outputs 4160EU/t with 4x aluminum wire, everything works fine.
I updated my IC2 reactor from Th to U which outputs 20800EU/t. The moment I turn on the reactor, the game crashes.
Then, I change my wire to 12x, everything works fine.

### Crash Report

[crash-2022-05-01_23.36.13-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8600856/crash-2022-05-01_23.36.13-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by GlodBlock** [comment]
will be fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1041
