### ISSUE TITLE
World Type button unclickable

### ISSUE THREAD

**Issue by Lordmoose213** [GTNewHorizons/GT-New-Horizons-Modpack#10255]
### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Your Expectation

Tried to click the world type button in the create new world>more world option screen so i could change to it Biomes O' Plenty from realistic alpha (Like the first time world creation popup says to do).

https://user-images.githubusercontent.com/79426096/166176083-4b9775f8-bab1-482a-bc57-0a609058b470.mp4

### The Reality

Made the minecraft button click sound, but did absolutely nothing. This happened on both the curseforge and Technic versions of the pack, both of which i reloaded/reinstalled cleanly multiple times.

### Your Proposal

Allow the changing of world type.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
It's intended behavior. If you don't like it, remove DefaultWorldGenerator mod
