### ISSUE TITLE
uhv version of crop gene extractor exists but is uncraftable

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10253]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

With another player we managed to get a primordial crop 1/1/1. We wanted to scan it, so to do that we checked the tooltip, saying the machine must be (tier+2)/2 rounded down so because the crop is tier 16, that makes the machine required to be tier 9, aka UHV. So i wanted to make it, and i expected it to have a recipe.

### The Reality

it has no recipe.

### Your Proposal

add a recipe please, players able to reach UHV or UEV should be allowed to scan and duplicate the primordial pearl crop.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
this is the recipe for the UV version, so we can just shift all the components from 1 tier above: 
![image](https://user-images.githubusercontent.com/12850933/166165305-1c304e9a-c8ca-4e16-af12-ff402c9d936c.png)

**Comment by Pxx500** [comment]
Questbook says something about that have you read it?

**Comment by boubou19** [comment]
nope as i know how to use the machine for every single other crop. Can you post the quest id and a picture of the text?

**Comment by boubou19** [comment]
![javaw_2022-05-02_00-27-42](https://user-images.githubusercontent.com/12850933/166167077-776b8760-488f-42b6-8307-e07b226a1950.jpg)

yeah so basically once again the QB just hides the issue under the blanket.

This is exactly why we need the recipe for it. It had been registered in the game but the recipe wasn't addded (on purpose or not, idk). But how can this be OP? you can duplicate your pearls already by smashing them then infuse them again. Tedium is bad.
