### ISSUE TITLE
Add VoidDimSkyChanger to the pack

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#10264]
### Your GTNH Discord Username

AdamR#0072

### Your Pack Version

2.1.2.0

### Mod Name

voiddimskychanger

### The Mod to Add

to begin with I wanted to switch the sad void dim sky with the one from barnada c, after discussing a bit with @glowredman  he come up with a mod that actually allow you to switch the sky as you want, he's already updating the mod and fixing bug that he and I encounter.
Here a beautiful screenshot 
![image](https://user-images.githubusercontent.com/76914762/166525368-1adecbd2-bff0-444f-b8a3-19796eac6b10.png)
The last version allow you to fully configure your sky with a cfg file, should work as long as you don't want a gs-like sky (mine is kinda different, using a premade build for it). You can just ping him for further details
 

### Your Reason

void dim black sky legitimaly make people want to commit suicide

### Preliminary Investigation

it's a rendering mod lol so no need to tweek any recipe

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by boubou19** [comment]
Mod is client side only, availiable here: https://github.com/glowredman/VoidDimSkyChanger

**Comment by glowredman** [comment]
> should work as long as you don't want a gs-like sky

This limitation is only for GTNH 2.1.2.0 and older, as those versions do not yet contain the [`SkyProviderBase`](https://github.com/GTNewHorizons/Galaxy-Space-GTNH/blob/master/src/main/java/galaxyspace/core/render/sky/SkyProviderBase.java) class. *This is not an issue in any dev pack*. (For those who want it right now, use version 1.1)
