### ISSUE TITLE
Combustion Gen infinite power

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#10276]
### Your GTNH Discord Username

Szajkop

### Your Pack Version

2123qf

### Your Server

priv srv

### Your Expectation

Today some weirdness happened in the game: After the generator run out of creosote, i put a cell of diesel into it and it started producing electricity but not consuming the fuel. Then I removed the fuel to pipe back the creosote and it still not consuming the fluid.

After breaking and replacing, it started to function normally again.
I could not reproduce it to make it infinite again.

### The Reality

Demo:

https://user-images.githubusercontent.com/7230430/166905369-74f120a3-9c4e-4fb5-9000-63625386f252.mp4

### Your Proposal

fix/check

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
