### ISSUE TITLE
Update GTNH Version # on Loading Screens

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#10271]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

2.1.2.4-dev-pre-test

### Original Request

N/A

### Responding developer

N/A

### Context

Don't forget to update the GTNH version number on all of the loading screen overlays prior to release.

### Developer's Promise

Someone promised me a cookie or something? :)

### Final Checklist

- [X] The developer in question has instructed me to create such an issue.
- [X] I believe the developer is not causally joking around.
- [X] I understand this reminder might take a long time to implement no matter what the developer has promised. (e.g. unforeseeable life difficulty, computer breakdowns, forgetting, laziness, etc)
- [X] I understand other people (developers or not) might not like this feature and would oppose its integration.
- [X] I believe this feature would make the pack better.

**Comment by BritishCynic** [comment]
This relates to the 2.2.0.0 stable build, which is now released.
