### ISSUE TITLE
Change the tooltip/question for electric prospector's scanner

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/GT-New-Horizons-Modpack#10274]
### Your GTNH Discord Username

mini_ben#0027

### Your Pack Version

2.1.2.4

### Your Proposal

1. Higher tier advanced seismic prospector should be able to detect underground fluids in larger areas.
2. The electric prospector's scanner should be able to detect several fluid fields, not the fluid in one chunk.

### Your Goal

There are too few ways to add underground fluids to the map.

### Your Vision

Maybe I'm missing some methods, but I only found three ways to detect the underground fluids.
1. Portable scanner
    1) Mv-tier
    2) Detect underground fluid in one chunk by right click on a block(any)
    3) Can't add to the map
    4) No change is needed
2. Advanced seismic prospector
    1) Lv-Ev tier
    2) Detect 3x3 oil fields
    3) Can be added to the map
    4) Change
        a) use more explosive items on higher tier
        b) detect more fields on higher tier
3. Electric prospector's scanner
    1) Luv-tier
    2) Detect underground fluid in one chunk by right click on a bedrock
    3) Can't add to the map
    4) Change
        a) detect several fluid fields, not the fluid in one chunk
        b) add to the map
        c) detect underground fluid by right click on a block(same as the portable scanner)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
Try right click the air with electric prospector without sneaking. I believe this is what you need.

**Comment by bjin2000** [comment]
Thank you for your help. I can shift+right-click the air to switch the mode to underground fluids, then right-click the air to detect the underground fluids.
However, neither the tooltip nor the question mentions that I can switch modes by shift+right-click the air.

![2022-05-05_11 15 04](https://user-images.githubusercontent.com/48137054/166955872-ebb3f9b8-1daf-40f0-bd6b-1e22bcaa1f2d.png)
![2022-05-05_11 15 16](https://user-images.githubusercontent.com/48137054/166955887-bbc1d143-0034-42d5-b98f-659e10791153.png)
