### ISSUE TITLE
Visual Prospecting can't add ores to the map around spawn

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/GT-New-Horizons-Modpack#10273]
### Your GTNH Discord Username

mini_ben#0027

### Your Pack Version

2.1.2.4

### Your Server

SP

### Your Expectation

Visual Prospecting work for all places

### The Reality

![2022-05-04_22 56 09](https://user-images.githubusercontent.com/48137054/166858885-79acb1ba-249e-4b81-b667-71013d8791ab.png)
![2022-05-04_22 56 20](https://user-images.githubusercontent.com/48137054/166858895-86522133-b79e-46fc-9983-cc9ce1e1a5fa.png)

### Your Proposal

properly work on spawn

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bjin2000** [comment]
Underground fluids work fine on the spawn point.

**Comment by MLellmann** [comment]
Workaround/fix is available: Go into the config folder - open "visualprospecting.cfg" file and change the line

    B:recacheVeins=false

to true. After a restart, veins around start will work. Though note, if your world is older and you have explored quite a bit, it might require more than the typical 6-8GB to run this step. The option will disable itself after it has run once on any world.

**Comment by bjin2000** [comment]
Thank you for your help.
