### ISSUE TITLE
Extreme Heat Exchanger (Good Generators) - not expected fluid output

### ISSUE THREAD

**Issue by AVVasiliev** [GTNewHorizons/GT-New-Horizons-Modpack#10278]
### Your GTNH Discord Username

Savitar#7841

### Your Pack Version

2.1.2.3qf

### Your Server

singlplayer

### Your Expectation

Problems with extreme heat exchanger (goog generators). I see recipes in NEI (examples), and expect both fluids - for hot coolant: 3.2M superheated steam, and 32k supercritical steam. 
![image](https://user-images.githubusercontent.com/20434719/166942236-94a3748f-2a7f-4e71-aa57-69976e78beb1.png)
![image](https://user-images.githubusercontent.com/20434719/166942309-2954f4c8-d0b0-4d96-9d2c-5a723cf7b15e.png)

### The Reality

I get only one fluid - the second from recipe. Supercritical steam for hot coolant, superheated steam from lava. Only one fluid.

### Your Proposal

Add additional description for Add a description if it's an expected mechanic (looks like a bug now) or make steam out of the recipe - both liquids

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Steelux8** [comment]
@GlodBlock

**Comment by GlodBlock** [comment]
well it is intended, this nei display show that the max output of steam when input under the threshout or above that.

**Comment by AVVasiliev** [comment]
when input under the threshold steam amount will be other - smaller, example: for hot coolant with threshold under 8k - I can get only half from NEI amount - 1,6M from 3.2M
Max amount 3.2M can't be never produced

**Comment by Steelux8** [comment]
So you're saying that the displayed amount of the first fluid can't be reached because, when you add the maximum amount of input allowed, the output changes to the second fluid? That makes sense, but should be clarified somewhere.

**Comment by AVVasiliev** [comment]
Yes exactly. But the numbers are misleading in this case. We will always get a maximum of half of the first type of liquid - then the second liquid will be dispensed
