### ISSUE TITLE
Add ability to search for stocked items in interface terminal

### ISSUE THREAD

**Issue by Divran** [GTNewHorizons/GT-New-Horizons-Modpack#10279]
### Your GTNH Discord Username

Divran

### Your Pack Version

2.1.2.3qf with jenkins v242 of AE

### Your Proposal

The new interface terminal is 10/10, but could be 11/10 if we could also search for stocked items.

### Your Goal

Would make things easier to find

### Your Vision

Would make things easier to find

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
why do you need to look at stored items when you insert patterns in your network?

**Comment by Divran** [comment]
In many cases it's easier to keep an item stocked in a machine at all times, instead of using encoded recipes. And if you're playing with friends someone else may have set it up and you have no idea where they've already automated a thing, and it doesn't show up when searching for encoded patterns because it doesn't use patterns, it uses stocked items to automate it. Or even if you're playing by yourself and you just forgot where it was among the other 30 chemical reactors.

Arguably export buses could use the same feature.

So far we've had to spend half an hour basically right clicking every single interface in the entire base like three separate times looking for something (or at least the ones that we remember keep some stock, which is about half). One time something was using like a hundred water cells a second which is stupid since that should just use an infinite water source at location, and after a ton of searching I found out it was the other guy who had set a mixer to use a water cell instead of water fluid.

Obviously if you think it's too much work to be worth it then don't do it, but I think it would be very helpful.

**Comment by Divran** [comment]
Another situation has arisen just now. We're crafting one chlorine cell per tick but using up every single one instantly and none of us has any clue where it's being used up so we can't change it into a bigger cell, like stainless steel fluid cells, so that it can keep up, unless we go on another 30 minute click spree
