### ISSUE TITLE
Increase height of crafting status UI

### ISSUE THREAD

**Issue by Divran** [GTNewHorizons/GT-New-Horizons-Modpack#10286]
### Your GTNH Discord Username

Divran

### Your Pack Version

2.1.2.3qf with jenkins v242 of AE

### Your Proposal

Increase height of crafting status UI to be about as tall as your screen, just like the other AE UI components. See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10232#issuecomment-1119356508 for discussion context

### Your Goal

Less scrolling with tall UI

### Your Vision

Less scrolling with tall UI

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
And Crafting Confirmation GUI too

**Comment by Divran** [comment]
yeet

**Comment by Divran** [comment]
oops forgot to bump it
