### ISSUE TITLE
Potin fluid pipes are less efficient than Lead fluid pipes

### ISSUE THREAD

**Issue by alfooscxx** [GTNewHorizons/GT-New-Horizons-Modpack#10280]
### Your GTNH Discord Username

alcxx#4313

### Your Pack Version

2.1.2.3qf

### Your Proposal

Potin fluid pipes should be upgraded
![image](https://user-images.githubusercontent.com/51835571/166967564-79dab9f9-941d-42a9-808a-867d92681dd3.png)
![image](https://user-images.githubusercontent.com/51835571/166967765-50a7ff66-dcf2-45c4-9004-318000171296.png)

### Your Goal

Potin pipes are useless despite there is a quest for them and they are recommended

### Your Vision

Crafting complicated potin alloy on early tier will make sense

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
This https://github.com/GTNewHorizons/GTplusplus/pull/128

**Comment by Dream-Master** [comment]
sure i nerf lead pipe as well
