### ISSUE TITLE
let us see the contents of lootbags in survival

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#10289]
### Your GTNH Discord Username

maniifestantes

### Your Pack Version

2.1.1.3qf

### Your Proposal

What the title says, allow us to see the content of lootbags in survival. Having to go on creative and having to shift right click on the lootbag to look at its content is pretty annoying, also, a lot of people don't know you can check its content on creative.

### Your Goal

That way we can check if it's worth enchanting them now or upgrading them for the next tier. 

### Your Vision

yes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by cubic-chariot** [comment]
Being able to see the contents of Pam's gardens would also be nice. Maybe a NEI tab?

**Comment by miozune** [comment]
Harvestcraft Garden NEI is already implemented
