### ISSUE TITLE
Quicksilver Block Recipe Change

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#10284]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

2.1.2.4-dev-pre-test

### Your Proposal

Change Quicksilver Block recipe to require compressor instead of crafting table.

### Your Goal

Align Quicksilver Block with rest of "blocks".

### Your Vision

Align Quicksilver Block with rest of "blocks".

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
Quicksilver block doesn't make sense. It's a liquid at room temperature. You sure it isn't bind together using magic - lore wise?

**Comment by shawnbyday** [comment]
I don't really know much of anything honestly. Quicksilver balls are a thing...how do you carry those if they're liquid?
