### ISSUE TITLE
Bug with keyboard key in NEI

### ISSUE THREAD

**Issue by MadRatSRP** [GTNewHorizons/GT-New-Horizons-Modpack#10297]
### Your GTNH Discord Username

MadRat96#9831

### Your Pack Version

2.1.2.1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Sometimes when using NEI's search keyboard key "Y" stops to work completely, no matter how many times i'm trying to press it it doesnt print a letter. This happens for like from 30 seconds to around 2 minutes i think, never happens with other keys, also i checked Notepad when this bug happened - Y key works as usual, prints into Notepad, so its not because of my keyboard.
p.s. also one more thing to add - i checked my settings and this key doesnt have any conflict in controls and in Nei's settings it represents "Search the world" option
![image](https://user-images.githubusercontent.com/29717217/167291895-81cc16d9-bfd2-4213-99a9-ff8cdaff2ba5.png)

### The Reality

null

### Your Proposal

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
just rebind it in the NEI options?

**Comment by MadRatSRP** [comment]
> just rebind it in the NEI options?

I can rebind it, but why doesnt it allow to press this key in search bar sometimes?

**Comment by chochem** [comment]
That should just depend on whether your cursor is over an item or not.

**Comment by boubou19** [comment]
also, this is because you didn't properly click on the search bar. For exemple, if i press T or Y while in AE terminal, while i'm in auto focus mode, i need to explicitely click on the search bar or those keys will not be processed as input keys, they will br processed as triggers to corresponding actions in NEI

**Comment by MadRatSRP** [comment]
> also, this is because you didn't properly click on the search bar. For exemple, if i press T or Y while in AE terminal, while i'm in auto focus mode, i need to explicitely click on the search bar or those keys will not be processed as input keys, they will br processed as triggers to corresponding actions in NEI

If I remember correctly, this also happened when i pressed previously F key for focusing NEI's search and tried to press Y after that

**Comment by TwoTailedFox** [comment]
Similar issue; NEI and AE2 won't process the T key unless specifically moused over. Seriously annoying as hell.

**Comment by Eranicus** [comment]
Got same problem with T key and as far as I remember its a very old problem

**Comment by Runakai1** [comment]
A simple solution would be just setting the search item function to a key you'd not use normally

**Comment by slprime** [comment]
Maybe need add keys combinations like `ctrl+<key>` or `shift+<key>`
