### ISSUE TITLE
Coin/Kill Repeatable Quests Don't Reset

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#10294]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

2.1.2.4-dev-pre-test

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Be able to complete coin/kill quests when they reset.

### The Reality

They show as repeatable but in order to repeat them I have to logout and back in again.

### Your Proposal

Figure out what change broke these and fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NoX-programer** [comment]
In version 2.1.2.3qf it was not appear. Modpack v.2.2.3: this bug is still actual!
