### ISSUE TITLE
Witchery Quest Brew Of Flowing Spirit is Kinda Broken

### ISSUE THREAD

**Issue by EmrahKhan** [GTNewHorizons/GT-New-Horizons-Modpack#10295]
### Your GTNH Discord Username

Emrah

### Your Pack Version

2.1.2.3qf

### Your Server

None

### Your Expectation

Spirit World Quest Chain uses a coin transfer system to get required witchery blocks such as oven, altar etc. 

Up to the "Fanciful Thread" Quest everything is fine. This quest wants 4 String, 4 Odour of Purity and 16 Wispy Cotton to craft 4 Fanciful Thread (Which is required for the final quest Brew of Flowing Spirit) but Fanciful Thread recipe is different now. It requires gold thread which needs fine gold wire. And u cant get that in Spirit World. 

U can actually get fine gold wire if u coin transfer for Gold Ores in the coins tab but i dont think this is the intended way.

### The Reality

Brew Of Flowing Spirit Quest can not be completed as intended. 

### Your Proposal

Allow to transer some fine gold wires from overworld as it is needed to craft Fanciful Thread.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
i better give it as quest reward somehow

**Comment by Dundun3Billion** [comment]
Wrong part for quest was fixed. Golden thread is still unobtainable in the Spirit World. Quest needs to be added as "trade quest" (similar to distillery, oven, and cauldron quests) to allow you to claim golden thread or even fanciful thread in the spirit world.
