### ISSUE TITLE
[RFC] Borosilicate Glass rebalance

### ISSUE THREAD

**Issue by miozune** [GTNewHorizons/GT-New-Horizons-Modpack#10306]
### Your GTNH Discord Username

miozune#9742

### Your Pack Version

2.1.2.2qf2

### Your Proposal

Current recipes for Borosilicate Glasses:
- EV = Borosilicate Glass (HV) + 36 ingot equivalent of molten Nickel
- IV = EV + 9 Tungsten
- LuV = IV + 9 Chrome
- ZPM = LuV + 27 Iridium
- UV = ZPM + 9 Osmium
- UHV = UV + 16 Uranium 235
- UEV = UHV + 32 Europium

I suggest using main tier material and making them non-recursive, i.e.
- EV = HV + 8 Titanium
- IV = HV + 8 Tungstensteel
- LuV = HV + 8 Rhodium-Plated Palladium
- ZPM = HV + 8 Iridium
- UV = HV + 8 Osmium
- UHV = HV + 8 Neutronium
- UEV = HV + 8 ~~Bedrockium~~ Cosmic Neutronium

### Your Goal

context: https://discordapp.com/channels/181078474394566657/603348502637969419/968106506190995498

Recursive is evil, we all know. Why do we need stupid amount of Nickel for advanced UV glass?
Material tiering is also wierd. Chrome is not main material anymore, Uranium 235 is trivial at UHV (I guess).

EV-UV Glass recipes have not been changed since Bart originally added them, so it's time to change.

### Your Vision

Less tedious.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Eranicus** [comment]
good idea recursuve is very bad... but i would make HV + 32 or even better 64 ingots per glass, 8 is a joke considering recursive is removed.

**Comment by GTNHAfx237v7** [comment]
The LSC and the MBF are main users of this type of glass, with an MBF needing 1,004 glass blocks and an LSC a varying amount of glass blocks. 64 seems excessive imho; 64,256 neutronium for an MBF is painful. Between 8 and 32 is my suggestion, depending on how plentiful the metal types are for a typical playstyle.

**Comment by Connor-Colenso** [comment]
I agree but imo bedrockium is easier than neutronium, perhaps cosmic neutronium? Also we will need to retexture the glass itself but that shouldn't be too hard given it's just a 1 pixel border.

**Comment by miozune** [comment]
I chose 8 because most of the metal casings are made of 8. Glass that is made of more metal than casing doesn't make sense to me.

If Bedrockium is easy, UEV Hull recipe should be changed. It's also ancient recipe. But yes, since we're going to make glasses non-recursive, recipe can be harder, to prevent tier skipping.

**Comment by KamenriderZO** [comment]
> I chose 8 because most of the metal casings are made of 8. Glass that is made of more metal than casing doesn't make sense to me.
> 
> If Bedrockium is easy, UEV Hull recipe should be changed. It's also ancient recipe. But yes, since we're going to make glasses non-recursive, recipe can be harder, to prevent tier skipping.

Hello miozune san,this is a good idea. but the recipe only with HV glass and tier metal is too simple.
maybe you can also add some metal part that were not consumed very usually.
maybe Oriharukon,Desh...
