### ISSUE TITLE
Quest: Basic Cracking (ID: 2993)

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#10301]
### Your GTNH Discord Username

Szajkop

### Your Pack Version

2123qf

### Your Proposal

To complete the quest I need to get steam cells. However, gregtech steam cell is not accepted in the quest. Only ic2 steam cell.
Picking up steam from a fluid tank or a fluid heater gives gt steam, the quest should accept both.
![image](https://user-images.githubusercontent.com/7230430/167311100-f43aed5e-0b23-4f55-ab87-38cde6334640.png)
![image](https://user-images.githubusercontent.com/7230430/167311104-dfcff60e-fc4f-4fdf-8dcd-3c2d26ca4324.png)
![image](https://user-images.githubusercontent.com/7230430/167311152-320b677f-8f63-4a6d-9bc1-961b960f8215.png)

### Your Goal

 the quest should accept both cells or preferably the gt one.

### Your Vision

quality of life improvement

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Fixed by #10019
