### ISSUE TITLE
Bug Tinkers Construct with emerald and mining levels

### ISSUE THREAD

**Issue by AsGeNoCiide** [GTNewHorizons/GT-New-Horizons-Modpack#10313]
### Your GTNH Discord Username

As GeNoCiide | WGG#2304

### Your Pack Version

2.1.2.3

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

emerald is supposed to add 50% more durabilty, and increase mining to level 2 
![image](https://user-images.githubusercontent.com/105320040/167720169-596ca56c-8364-4d99-8b42-3e389eed663f.png)

The durability part is working correctly.

Problem comes from mining levels and single use

### The Reality

i did some testing, depending in what order you apply the emerald, effects changes completely.
emerald = add emerald to pickaxe.
bottle of enchanting= xp pickaxe to boosted mining level.

![image](https://user-images.githubusercontent.com/105320040/167720009-0b6df200-57dd-4601-89e9-ed7d6b450648.png)

As you can see you can exceed the level 4 which stand for redstone and you can mine obsdian with a bronze pickaxe. Even if  the mining level is increase to level 2. and not 5.
You can also apply the emerald twice ???!!!

Same bug with diamond 
![image](https://user-images.githubusercontent.com/105320040/167721349-384846b4-9857-4866-ad49-cc51f01ef09e.png)
but in this case it's still level 5 and not 6.
You can't also double apply the diamond to make it improve.

### Your Proposal

Fix the mining level bug. Send me message on discord if there is any point that are left unclear.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
this book need a complete rewrite
