### ISSUE TITLE
Toolbox and soldering alloy

### ISSUE THREAD

**Issue by Runakai1** [GTNewHorizons/GT-New-Horizons-Modpack#10317]
### Your GTNH Discord Username

Runakai ~ Docsyᵇᵒᵗ#7676

### Your Pack Version

2.1.2.3QF3

### Your Proposal

Would be cool to have a soldering alloy block that can be partially used every time instead of using fine tin wire or sth every time, like a buffer-item. 

Also would be very QoL if we could use soldering alloy within the toolbox and keep it in it 

### Your Goal

QoL

### Your Vision

QoL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Soldering into toolbox is implemented in https://github.com/GTNewHorizons/GT5-Unofficial/pull/1002
As for "partially used", currently ingot, stick, and fine wire are consumed one item per time in the same way, so we might want to look into this.

**Comment by Runakai1** [comment]
Was added. Can't find PR. But it's in the game now:)
