### ISSUE TITLE
Early Everglades portal in dev version

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10318]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4 pre-dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

There should be only one recipe for the everglades containment frames (portal to gt++ everglades dimension) and unless I missed something it is supposed to be tiered in ZPM.

### The Reality

There is an additional early recipe which can be crafted in EV:

![image](https://user-images.githubusercontent.com/40274384/167903789-2809205a-9e13-498f-8e90-7d79305c4607.png)

(the one based on LuV power is the old/correct one that is tiered to ZPM based on materials involved)

### Your Proposal

remove the EV recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
regarding:needs to tested

only one recipe in .4 3 dev-pre-test namely the LuV-power one. So looking good.

**Comment by Alastors** [comment]
it's also in 2.1.0.3QF, what's in the everglades anyway

**Comment by King65868** [comment]
All the GT++ ores
