### ISSUE TITLE
Add extra info to Electrical Stimulator quest (#2093)

### ISSUE THREAD

**Issue by S-Czernik** [GTNewHorizons/GT-New-Horizons-Modpack#10319]
### Your GTNH Discord Username

CyanPlatypus#8441

### Your Pack Version

2.1.2.1

### Your Proposal

Change the bonuses to multipliers instead of percentages. Also mention that the effects are multiplicative.

 
Iron ET - Production x1.5 (Max x5)
Diamantine ET - Production: x2.5 (Max x10)
Apatine ET - Pollination: x1.5 (Max x5)
Obsidian ET - Lifespan: x0.8 (Min x0.2)
Lapis ET - Lifespan: x1.5 (Max x5)
Blazing ET - Simulates the Nether
Golden ET - Mutation rate: x1.5 (Max x5)
Tin ET - Territory: x0.4 (Min x0.1) Prod: x0.9 (Min x0.5)
Bronze ET - Territory: x1.5 (Max x5)

### Your Goal

Better info about the circuits, since neither wiki nor discord has that information now.

### Your Vision

The change helps people who want to know the specific numbers / bonuses the Stimulator grants.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
this was apparently done at some point.
