### ISSUE TITLE
Tree Growth Simulator Issues

### ISSUE THREAD

**Issue by Josh5minus1** [GTNewHorizons/GT-New-Horizons-Modpack#10310]
### Your GTNH Discord Username

A1#8299

### Your Pack Version

2.1.2.4  dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I tried using the tree growth simulator, filling it with saplings. This time Barnarda C saplings was used in order to get Barnarda C logs, and expected to consume the saplings from the input bus.

### The Reality

The saplings do not get consumed, resulting to infinite output of logs. Also when using Barnarda C saplings, the tree growth simulator outputs oak logs instead of the Barnarda C logs. Other saplings seems to output the right type of logs as expected. I checked in NEI as it says the multiblock accepts Barnarda C saplings and outputs Barnarda C logs.

### Your Proposal

Make it so the saplings in the input bus gets consumed, and make it so that the multiblock recognizes the Barnarda C saplings in order to produce Barnarda C logs as what NEI says.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
saplings are not supposed to be consumed, they are just there to select the type of tree.

**Comment by chochem** [comment]
And just tested in .4 dev: barnarda C sapling work fine for me. 
![image](https://user-images.githubusercontent.com/40274384/167632811-f5c00181-2ae4-4f86-aab5-01c8fb16418f.png)

**Comment by chochem** [comment]
Ah I found the problem with the barnarda C saplings. The one in NEI (that I tested) is the 3122:1, that one works. But that is probably not the one one gets normally. Tried a 3122 and got oak logs too.
