### ISSUE TITLE
[NEW MOD]Share your waypoint and share where you are

### ISSUE THREAD

**Issue by MuXiu1997** [GTNewHorizons/GT-New-Horizons-Modpack#10312]
### Your GTNH Discord Username

MuXiu1997#3167

### Your Pack Version

2.1.2.3qf

### Mod Name

Share Where I am

### The Mod to Add

1. You can share your `Waypoint` in your `Waypoint Manager` or use the command `/sharewhereiam` to share your current location:

   ![unknown](https://user-images.githubusercontent.com/49554020/167680560-e8c600b6-6239-4fbd-a72c-cc15c7a0949f.png)
   ![unknown](https://user-images.githubusercontent.com/49554020/167680782-239841be-3630-4e2d-bba9-1f00f02c7c64.png)

2. Other players can just save this `Waypoint`(click `[SAVE]`):

   ![unknown](https://user-images.githubusercontent.com/49554020/167681032-37292289-9e0b-404d-9f67-80b8a73289ee.png)
   ![unknown](https://user-images.githubusercontent.com/49554020/167681151-f99ef9a5-1bad-445b-b594-e10d12bdc222.png)

3. Or save after editing (click `[EDIT]`):

   ![unknown](https://user-images.githubusercontent.com/49554020/167681299-62f854ef-36c3-454d-8cca-17a0657124cc.png)
   ![unknown](https://user-images.githubusercontent.com/49554020/167681323-db580dbe-b755-426a-b3fa-5787b1cea064.png)

4. Or temporarily make the `Waypoint` a beacon without saving it (click `[Enable/Disable]`):

   ![unknown](https://user-images.githubusercontent.com/49554020/167682067-e6f74af3-f3d7-4784-aa5c-5fed6044409a.png)
   ![unknown](https://user-images.githubusercontent.com/49554020/167682098-7847b924-08b0-4f8e-97cf-b2800e5b7471.png)

 

### Your Reason

When I played this pack with my friends, sharing location information was a pain in the ass

### Preliminary Investigation

/

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [X] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by glowredman** [comment]
I guess this is client-side only?

**Comment by MuXiu1997** [comment]
> I guess this is client-side only?


Need server to post message to other players?

**Comment by glowredman** [comment]
> > I guess this is client-side only?
> 
> Need server to post message to other players?

VoxelMap does it without being server-side too ¯\\\_(ツ)\_/¯

**Comment by MuXiu1997** [comment]
> VoxelMap does it without being server-side too ¯\_(ツ)_/¯

There is a way to do it, but I chose the easier way because I am a rookie ¯\_(ツ)_/¯

**Comment by Dream-Master** [comment]
@MuXiu1997 where is the link to the mod ?

**Comment by Ethryan** [comment]
[Here](https://github.com/MuXiu1997/Share-Where-I-am) i think
