### ISSUE TITLE
maybe a problem with "Industrial strength hydrogen chloride cell" recipe

### ISSUE THREAD

**Issue by NoX-programer** [GTNewHorizons/GT-New-Horizons-Modpack#10316]
### Your GTNH Discord Username

NoXъ # 0667

### Your Pack Version

2.1.2.3qf

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

Trying to craft "Industrial strength hydrogen chloride cell". But the lens in the recipe is **not marked** as "does not get consumed in the process" and consuming during craft.

### The Reality

![recipe-of-the-cell](https://cdn.discordapp.com/attachments/234936569360809996/973945488443310080/unknown.png)
Is that intended, recipe is really that expensive or recipe need to be fixed?

### Your Proposal

Fix the recipe if necessary.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/178
