### ISSUE TITLE
NEI search always darken full universal cells

### ISSUE THREAD

**Issue by NoX-programer** [GTNewHorizons/GT-New-Horizons-Modpack#10328]
### Your GTNH Discord Username

NoXъ # 0667

### Your Pack Version

2.1.2.3qf

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

Double-clicking NEI search bar to search for liquid cells.

### The Reality

But even with empty search bar the **full** Universal Cells (w/1000 mb) are darken already: ![2022-05-13_11 19 57](https://user-images.githubusercontent.com/4730256/168211057-5d18dbb8-a6e5-4a5c-a495-0c1cea7fc073.png)
Then, whatever I type to search bar, they are not going bright. That is prevent to search for liquids in Universal Cells using NEI. For example, this happens with liquids: molten.thorium, poison, hell_blood, endergoo, wet.concrete.

### Your Proposal

Fix NEI.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by slprime** [comment]
I think it's the same

duplicate: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7819
fix here: https://github.com/GTNewHorizons/NotEnoughItems/pull/240

**Comment by NoX-programer** [comment]
Looks like related/same/duplicate. But now with info about universal cells. Let the staff to decide - close it or not.
