### ISSUE TITLE
An attempt at a comprehensive list of redundant recipes.

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#10320]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.3QF

### Your Proposal

No proposal, just a collection of redundant recipes

### Your Goal

to avoid redundancy and remove unneeded recipes

### Your Vision

there is a clear idea to how this would improve the pack, I will be attempting to point out every possibly redundant recipe I can find that either needs to be changed to give it purpose or needs to be cut, I'll be doing this in spurts throughout the day, so I'm just going to post them all in the comments instead of through here.

I request that anyone who reads this doesn't add a new part to this list, and rather dm me the info so that I can collect the recipes cohesively, I will give you credit, I promise.

### Final Checklist
- [X] I understand this change request may be rejected due to other community members think it's too awesome.
- [X] I believe this feature would make the pack better, why would I do this otherwise.
- [x] I understand that Alastor is a god at thaumcraft

**Comment by Alastors** [comment]
1. Magic Essence BS and Inert Pearl Fragements
    
<img width="792" alt="Screen Shot 2022-05-11 at 3 43 08 PM" src="https://user-images.githubusercontent.com/78517796/167944534-a4db0ab4-0b37-41c4-a987-139813cbb4c2.png">
<img width="796" alt="Screen Shot 2022-05-11 at 3 43 18 PM" src="https://user-images.githubusercontent.com/78517796/167944547-62102ef1-f237-40be-9214-0c4992739c86.png">
<img width="830" alt="Screen Shot 2022-05-11 at 3 43 33 PM" src="https://user-images.githubusercontent.com/78517796/167944551-d71db628-43d3-45cb-a1aa-3c5f18f47824.png">
<img width="643" alt="Screen Shot 2022-05-11 at 3 43 37 PM" src="https://user-images.githubusercontent.com/78517796/167944555-9acfe922-050e-47bb-9386-1b5c9492414d.png">
<img width="716" alt="Screen Shot 2022-05-11 at 3 43 46 PM" src="https://user-images.githubusercontent.com/78517796/167944556-a79f590e-3cae-4599-b840-3d25483440ef.png">
<img width="814" alt="Screen Shot 2022-05-11 at 3 43 53 PM" src="https://user-images.githubusercontent.com/78517796/167944558-83c3b365-fee7-4537-b78f-3eb436ad3e03.png">

**Comment by Alastors** [comment]
2. The Alumina line now that clay dust produces straight aluminium dust:
     1. 
<img width="496" alt="Screen Shot 2022-05-11 at 3 56 51 PM" src="https://user-images.githubusercontent.com/78517796/167946244-11338137-4142-4f20-b190-c8f12771cbec.png">
<img width="507" alt="Screen Shot 2022-05-11 at 3 56 56 PM" src="https://user-images.githubusercontent.com/78517796/167946195-d221d2b9-0193-46f1-9791-d672112ef97d.png">

**Comment by boubou19** [comment]
i'm using the forge hammer recipe in 2.1.2.0 because there is a bug in NEI that doesn't show the usage of inert pearl fragments, but when you look at the recipe of the primordial pearl, you see that you can make it from the inert pearl fragment. That way it's a duping recipe for those who can't bear the farming of the outterlands or the crops growth duration.

**Comment by Alastors** [comment]
> i'm using the forge hammer recipe in 2.1.2.0 because there is a bug in NEI that doesn't show the usage of inert pearl fragments, but when you look at the recipe of the primordial pearl, you see that you can make it from the inert pearl fragment. That way it's a duping recipe for those who can't bear the farming of the outterlands or the crops growth duration.

weird, I can't see it for some reason

**Comment by Alastors** [comment]
> i'm using the forge hammer recipe in 2.1.2.0 because there is a bug in NEI that doesn't show the usage of inert pearl fragments, but when you look at the recipe of the primordial pearl, you see that you can make it from the inert pearl fragment. That way it's a duping recipe for those who can't bear the farming of the outterlands or the crops growth duration.

could you please post the recipe though, if you could?

**Comment by mfruendt** [comment]
> > i'm using the forge hammer recipe in 2.1.2.0 because there is a bug in NEI that doesn't show the usage of inert pearl fragments, but when you look at the recipe of the primordial pearl, you see that you can make it from the inert pearl fragment. That way it's a duping recipe for those who can't bear the farming of the outterlands or the crops growth duration.
> 
> could you please post the recipe though, if you could?

![image](https://user-images.githubusercontent.com/82537644/168077019-f63dae6a-1fd8-4ca0-9e46-0b36d242798d.png)
Just click usage on the inert pearl fragment.

**Comment by Alastors** [comment]
> > > i'm using the forge hammer recipe in 2.1.2.0 because there is a bug in NEI that doesn't show the usage of inert pearl fragments, but when you look at the recipe of the primordial pearl, you see that you can make it from the inert pearl fragment. That way it's a duping recipe for those who can't bear the farming of the outterlands or the crops growth duration.
> > 
> > 
> > could you please post the recipe though, if you could?
> 
> ![image](https://user-images.githubusercontent.com/82537644/168077019-f63dae6a-1fd8-4ca0-9e46-0b36d242798d.png) Just click usage on the inert pearl fragment.

it legit doesn't work for me for some reason
