### ISSUE TITLE
High Energy Flow Circuit only using wetware assembly

### ISSUE THREAD

**Issue by joshuan123** [GTNewHorizons/GT-New-Horizons-Modpack#10327]
### Your GTNH Discord Username

Joshuan123#6232

### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

High Energy Flow Circuit accepts and ZPM circuit like in previous versions. WIll admit I'm not sure if this was intended or not but couldn't find anything on discord so making ticket anyways

### The Reality

High Energy Flow Circuit recipe only accepts wetwareprocessor assemblies

### Your Proposal

Reenable all ZPM circuits working for the recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment]
I have this same issue, but Default on discord said he is on .3qf and can use any ZPM circuit.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/300
