### ISSUE TITLE
Remove queued thaumcraft effects 

### ISSUE THREAD

**Issue by Runakai1** [GTNewHorizons/GT-New-Horizons-Modpack#10329]
### Your GTNH Discord Username

Runakai ~ Docsyᵇᵒᵗ#7676

### Your Pack Version

2.1.2.3QF3

### Your Proposal

Add a command/item to remove the queued thaumcraft recipes. 
When I'm in single player and I cheat in all thaumcraft researches, warp goes up insanely high as expected. However, pure tear and removing warp via command (temp and perm) doesn't remove the queued effects so I have to sit on my world 3 hours in order to properly test my things.  

### Your Goal

Because it is needed

### Your Vision

Because its annoying if you can't test something in TC immediately

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
Before this is implemented you could just use `/tc warp <player> set 0`, `/tc warp <player> set 0 perm` and `/tc warp <player> set 0 temp` to reset warp without triggering warp events to get by this.

**Comment by Runakai1** [comment]
> Before this is implemented you could just use `/tc warp <player> set 0`, `/tc warp <player> set 0 perm` and `/tc warp <player> set 0 temp` to reset warp without triggering warp events to get by this.

That's the point, that doesn't work. It removes the warp, not the effects

**Comment by Glease** [comment]
Well if you don't use pure tear you don't get warp effects, unless you are unlucky enough to get a warp event fire that fast.

**Comment by Runakai1** [comment]
> Well if you don't use pure tear you don't get warp effects, unless you are unlucky enough to get a warp event fire that fast.

Every time I complete all researches via command at once, I get warp effects immediately

**Comment by Alastors** [comment]
same actually

**Comment by Alastors** [comment]
same actually
