### ISSUE TITLE
GTNH bibliocraft related crash

### ISSUE THREAD

**Issue by Maaaarah** [GTNewHorizons/GT-New-Horizons-Modpack#10333]
### Your GTNH Discord Username

Marah#1337

### Your Pack Version

2.1.1.0

### Your Server

Private server with a friend

### Type of Server

Vanilla Forge

### Your Actions

I interacted with a bibliocraft canvas block as soon as i tried to shift click it to place a new painting, it hard crashed me to the launcher with the message in the image: 

![crash weird](https://user-images.githubusercontent.com/105515531/168343772-2bb4b760-1b8b-41a2-938f-e3b584576a84.png)

### Crash Report

java.lang.ArrayIndexOutOfBoundsException: 1
Exit Code: -1
![crash weird](https://user-images.githubusercontent.com/105515531/168343943-43f30aaa-4a50-4507-bca9-dedd203559b7.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by YannickMG** [comment]
I couldn't reproduce this on the latest devpack. Please provide a full stack trace and/or full reproduction steps if this still happens.
