### ISSUE TITLE
Buff the thaumium reinforced jar, it's extremely inferior to the reservoir

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#10332]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.3QF

### Your Proposal

1. <details><summary>remove the primal charm, remove the frame, make it not infusion, make it 4 thaumium plates,  *blocks* of glass to make it more expensive in that terms to balance it out, obviously on an arcane crafting table</summary>
      1. <img width="952" alt="Screen Shot 2022-05-13 at 12 53 20 PM" src="https://user-images.githubusercontent.com/78517796/168340303-fe63f0a0-5642-4e3d-972a-8300d423b998.png">
      

2. <details><summary>likewise, switch this dense obsidian plate for the normal obsidian plate from the original void jar recipe, and make it possible to turn a normal void jar into the thaumium reinforced void jar using the suggested recipe from above</summary>
     1. <img width="652" alt="Screen Shot 2022-05-13 at 12 54 49 PM" src="https://user-images.githubusercontent.com/78517796/168340498-75baaa09-f7ad-45e8-9d14-0c82a4fb6075.png">
      

### Your Goal

4. <details><summary>my point is, this jar is highly inferior to the reservoir, and you can make the reservoir as early as literal stone age (if you can do infusion in stone age, which it seems like it is highly likely through extreme suffering) and they have the same exact essentia storage but the reservoir can store more than just 1 type of essentia, so it just makes sense to buff the jar so that it's just a shittier reservoir in terms of cost.</summary>
    1.  <img width="671" alt="Screen Shot 2022-05-13 at 12 57 29 PM" src="https://user-images.githubusercontent.com/78517796/168340844-a2138df0-847b-4ba6-acb1-268705c2aea9.png">
    
 

### Your Vision

It just buffs something that clearly needs it, otherwise this is extremely redundant to even exist.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by DianeXD** [comment]
As far as I know, you need to use thaumic energistics to get the gas essentia

**Comment by Alastors** [comment]
> As far as I know, you need to use thaumic energistics to get the gas essentia

No, no you do not
