### ISSUE TITLE
Metadata shift again

### ISSUE THREAD

**Issue by pulsemageadvocate** [GTNewHorizons/GT-New-Horizons-Modpack#10334]
### Your GTNH Discord Username

pulsemageadvocate

### Your Pack Version

2.1.2.4-pre-dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Related to #9876 
Update from 2.1.2.3qf with #9876 fix to 2.1.2.4-pre-dev.
Reproduceable from 2.1.2.1 to 2.1.2.4-pre-dev.
All items are same.

### The Reality

Wrap of Neuro Processing Units become Wrap of Optical SMD Diodes.
Metadata shifts.

2.1.2.3qf with fix
![20220514_2123qf](https://user-images.githubusercontent.com/59131259/168346201-663f0173-2485-4b19-8fb6-f08f5b808f7c.jpg)

2.1.2.4-pre-dev
![20220514_2124pre](https://user-images.githubusercontent.com/59131259/168346373-5372e52d-aac1-4245-9cbf-5c7c0ad7b8d0.jpg)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
I'm relabelling this as bugMajor as it keeps happening between updates and breaks a shit ton of automation as a ton of wraps get randomly shuffled. I've no clue why adding a new wrap would cause this shift.

**Comment by miozune** [comment]
Wrapped normal SMDs and Coils are missing. Not sure why though

**Comment by GlodBlock** [comment]
may related to this https://github.com/GTNewHorizons/GT5-Unofficial/pull/1040. but this pr has not been merged, how it appeared in 2114 pack

**Comment by miozune** [comment]
Dream merged that commit into dev branch.
In that commit, normal SMDs now have oredictionary, and they confuse this part https://github.com/GTNewHorizons/bartworks/blob/master/src/main/java/com/github/bartimaeusnek/bartworks/system/material/CircuitGeneration/CircuitPartLoader.java#L84-L86
So we might as well stop those on-the-fly generation and instead manually add them
