### ISSUE TITLE
Zoomed in when holding item and broken textures

### ISSUE THREAD

**Issue by SD678** [GTNewHorizons/GT-New-Horizons-Modpack#10346]
### Your GTNH Discord Username

Silent Demon678#9170

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

loading into a new world, changed from technic launcher to mcc, then back to technic, restarted my system. 

any held item causes the screen to zoom in to a single pixel. 

### The Reality

![2022-05-15_13 03 20](https://user-images.githubusercontent.com/78656707/168485000-cf2082e5-5316-485a-91c9-416fa975b9a9.png)
![2022-05-15_13 03 18](https://user-images.githubusercontent.com/78656707/168485004-5b8548af-5f0c-4896-a692-9cfe7b7d26d8.png)

issue still persists. Have reinstalled multiple times 

### Your Proposal

the pack was working fine the day before, same version, same system, no visual bugs, i load it up today and it does that.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Try reboot and/or remove optifine. This seems unrelated to the pack itself.

**Comment by SD678** [comment]
unfortunately i do not have optifine installed to do that, i downloaded the pack on technic yesterday and had no issues when playing
