### ISSUE TITLE
Change recipe of me output bus

### ISSUE THREAD

**Issue by Runakai1** [GTNewHorizons/GT-New-Horizons-Modpack#10342]
### Your GTNH Discord Username

Runakai ~ Docsyᵇᵒᵗ#7676

### Your Pack Version

2.1.2.3QF3

### Your Proposal

Change the Recipe. Quest says, it has significantly less tps impact for servers. Why exactly is this recipe more expensive than input bus + interface only?
![image](https://user-images.githubusercontent.com/48415331/168445270-e076783d-9506-4715-b3fe-5e9f9d965faa.png)

Change the HV Hull to LV and remove the 4 acceleration cards.
Who designed this? Doesn't make sense to make something with the same effect and speed and same channel consumption more expensive. Saving tps shouldnt depend on material cost.

Also, does this have an internal buffer? People report voiding interfaces when AE starts loading and materials get pushed into the interface in the meanwhile. This was fixed iirc but I'd like to know if the me output bus also has this fix implemented 

### Your Goal

TPS saving shouldn't cost more.

### Your Vision

Server owners be like: yay

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by mudspaw** [comment]
I'd just yeet the cards tbh

**Comment by Runakai1** [comment]
> I'd just yeet the cards tbh

Or that lol, would be fine as well
