### ISSUE TITLE
Quest Clay Electrolizing step 2

### ISSUE THREAD

**Issue by skushnarev** [GTNewHorizons/GT-New-Horizons-Modpack#10341]
### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Complete the Clay Electrolysis quest

### The Reality

The Clay electrolysis quest requires showing aluminum dust and silicon dust, and clay dust electrolysis gives alumina dust and silicon dioxide dust.

Perhaps the recipe for electrolysis has changed, but the quest remains old.

### Your Proposal

Update the dust for presentation

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
You are on an older version the quest has already changed since then and so has the clay recipe. The entire aluminum quests are still in need for an overhaul, but not this.

**Comment by skushnarev** [comment]
When creating a new world, the quests are correct. How to update the old world? The bq_user refresh command did not help.

**Comment by chochem** [comment]
bq_admin default load
