### ISSUE TITLE
Tinkers Traveller's belt crashes the client

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#10358]
### Your GTNH Discord Username

szajkop

### Your Pack Version

2123qf

### Your Server

priv srv

### Your Actions

Trying to use the belt on a server and the game crashes immediately.
It also happens when the hotbar is empty.

Strange, that when i played on other server there was no issues with the belt.

### Crash Report

[crash-2022-05-15_18.41.35-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8719741/crash-2022-05-15_18.41.35-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Szajkop** [comment]
update: when i crafted a new one it started working properly again. 
When i was testing it i used the give command to spawn the belt. That way it always comes out as broken.

/mt hand on the crafted one (top) and spawned one (bottom)
![image](https://user-images.githubusercontent.com/7230430/169262559-3b2726a4-5570-4270-9c23-46cb5c79cc94.png)

**Comment by chochem** [comment]
Since crafted ones work everything is fine.
