### ISSUE TITLE
Dyson Swarm craft

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#10355]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

last version 2.1.2.4

### Your Server

null

### Your Expectation

Dyson Swarm recipe in ASS Line has 16 elements (maximum 15 input buses and 16 elements) no more comments required

### The Reality

null

### Your Proposal

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GDCloudstrike** [comment]
You can put an input bus and an output bus in the same slice.

[https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10100]
(for reference)

**Comment by FoKuCNiK** [comment]
crooked crutch is not for perfectionists, but oh well

**Comment by GTNHAfx237v7** [comment]
You can do this, however it has 16 input items and 4 input fluids so you need effectively a 20 slot pattern for automation. Guess that is related, or would y’all think it’s worth a separate ticket?

**Comment by GDCloudstrike** [comment]
> You can do this, however it has 16 input items and 4 input fluids so you need effectively a 20 slot pattern for automation. Guess that is related, or would y’all think it’s worth a separate ticket?

I don't think addressing this is important, automation isn't really necessary because the dyson swarm is a one and done type of machine.

**Comment by boubou19** [comment]
> You can do this, however it has 16 input items and 4 input fluids so you need effectively a 20 slot pattern for automation. Guess that is related, or would y’all think it’s worth a separate ticket?

OC can address this anyways: ME interfaces can be interacted with to encode patterns.
