### ISSUE TITLE
Silicon Line: The HV process is complex but useless and should be removed/changed.

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10356]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4 4-dev-pre-test

### Your Proposal

Remove the HV silicon line and dichlorosilane/trichlorosilane/silane/hexachlorosilane. Or otherwise overhaul this process to something actually meaningful.

### Your Goal

The new silicon line additions provide two different paths to get from Raw Silicon Dust to Silicon Solar Grade (Poly Si) Dust.

The first unlocks in LV and involves three very simple recipes with a sodium and chlorine loop. The end result is that 1 raw silicon dust becomes 1 Solar Grade Dust.

The second path unlocks in HV and is a lot more involved. It needs 8 recipes, requires a good amount of hydrogen, produces small amounts of chlorine, and includes 4 fluids/gasses who's only use is in this chain (dichlorosilane/trichlorosilane/silane/hexachlorosilane). And what is the end result of all that effort? 1 raw silicon dust becomes 1.01 Solar Grade Dust.

here are my quick calculations (let me know if you think they are wrong):

![image](https://user-images.githubusercontent.com/40274384/169111352-019a968a-2b7d-44bb-bf3f-f022b3fd9727.png)

![image](https://user-images.githubusercontent.com/40274384/169111486-e621b8c4-56cb-4700-bbf1-0f5449c01a6a.png)

That means this more complex HV line is 100% useless at all stages of the game. In fact, the LV line is so nice, simple and scalable that even a buff to the HV would likely not change that.

Hence it is best to just remove.

By the way: I would love to know what the idea was behind these recipes. Maybe something can be done to achieve them?

### Your Vision

less bloat/useless and confusing stuff.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I think I just figured at least _why_ the HV recipe is in such a bad place. It probably used to be a good bit better than the LV one, but then https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10228 buffed the LV variant without adjusting the HV one.

**Comment by Pxx500** [comment]
How about reversing LV silione rubber change that made it Cl neutral, if it's going to waste chlorine then the HV variant would automatically better.  Then buffing HV variant would make things balanced

**Comment by Pxx500** [comment]
It would make sense that the "worse" process has losses while "complex" one has less/none

**Comment by chochem** [comment]
@shawnbyday any thoughts?

**Comment by Pxx500** [comment]
I just don't like when things have efficiency over 100%. I assume HV line is 100% efficient and I would like for it to stay that way but I never checked it, so if it isn't 100%eff I agree that it should be buffet to 100% but I'd rather nerf LV then make HV over 100% efficient.

**Comment by chochem** [comment]
I posted the numbers above. and HV is like 101% silicon efficiency while gaining tiny amounts of chlorine and loosing hydrogen. I think it had small losses on all three of those as well as sodium without the salt change.

If we are buffing HV than we should at least be careful that the buff does not increase chlorine as it is already positive. I dont mind to have above 100% efficiency on raw silicon->solar grade. But this process probably shouldn't replace regular chlorine production.

**Comment by GTNH-Afx237v7** [comment]
Here are my two cents:
1. The LV process seems ok for early game and the fact that it is lossless is a nice addition for when mining is manually and resources may be sparse. 
2. The LV process is bad for late-/endgame as looping around chlorine/sodium and salt just to turn A into B only and unnecessarily consumes tps. If a closed loop process is meant to stay we need to increase the numbers significantly to reduce amount of cycles and save tps.
3. The HV process seems more attractive, however the outputs that just exist to be recycled again fall under the same category as #2. Turning 1 raw into 1.01 poly is not attractive, I suggest to turn 1 into 1 with a %chance for a second (10-20%). Additionally with a recipe that consumes and produces more per cycle to save on tps.

**Comment by chochem** [comment]
dev18 update: the numbers are slightly different now due to the chem standardization. Everything is now lossless and silicon is 1:1 in either process.

Even worse, I cannot see any way to fix this. Things like 'chlorine loss' or 'bonus output' are forbidden now.

**Comment by GlodBlock** [comment]
lossful recipe is still acceptable in minimal(like the silicon dioxide electrolysis), but bonus output is forbidden even this material can't be electrolyszed, because you don't know how people can decomposit it with a bunch of reactions(e.g. the industrial hydrofluoric acid, you can't turn it back to hydrofluoric acid directly but can use IHF -> NaF -> Na2SO4 + HF route to decomposit it, which caused the fluorine dupe)

**Comment by boubou19** [comment]
i'd like to see a buff of the HV path as well.

**Comment by Dream-Master** [comment]
will check it soon

**Comment by Lithorn** [comment]
I want to make a suggestion. The LCR version of Trichlorosilane has a 10/30 input ratio for a 9/20 output with some byproducts. I don't care about the byproducts, could we add another circuit version that is a straight 10/30 input (Bulk craft) for a 10/22 Output? No Byproducts
