### ISSUE TITLE
Binding p2ps with advanced memory card breaks the p2p and dupes p2ps when there is a security terminal in the network

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10367]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-zeta

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I would love to connect (and potentially rename) an existing p2p connection from the output side with the new advanced memory card.

### The Reality

I have one p2p on a controller, one p2p elsewhere in my storage room and I try to link the with the advanced memory card from the side of the storage room. Using either bind input or bind output mode to connect them gives the p2p in the storage room I am interacting with a channel while the one on my controller drops in world and some dupes a few additional p2ps.

(As a logical sideeffect this creates a direct connection between my 2 me controllers (main network and p2p-transport network) causing both to shut down.)

Edit: See updates below. it doesnt work with security terminal apparently.

betterp2p version: 1.0.7-3-g00855f0
AE2 version: 1.7.10-rv3-beta-83-GTNH-1-g0b181e0

### Your Proposal

Fix the advanced memory card.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
upon further trying, this might be a bit more complicated. will test a bit more and post an update.

**Comment by chochem** [comment]
yeah I was wrong, this wasnt about renaming but about the advanced memory card. I adjusted title and text. Still need to do some more testing as I have actually used the advanced memory card successfully before. Not sure if it is a version difference or specific extra conditions

**Comment by chochem** [comment]
ok so I can narrow it down a bit: The advanced memory only seems to bug out when one of the p2ps is directly on an me controller, and it is always that side that pops off and potential dupes no matter which way one binds.

**Comment by GlodBlock** [comment]
can't reproduce this bug. do you mean such setup?
![image](https://user-images.githubusercontent.com/60341015/169628353-dc12c9c9-20dd-4921-95ba-12f9021f839e.png)
the advanced memery card can link them without duping.
what ae2 version are you using?

**Comment by chochem** [comment]
I trying to reproduce it on a minimal setup myself already to post that but it all works for the small minimal setup and not for my actual system. here is the small one I had in mind
![image](https://user-images.githubusercontent.com/40274384/169628454-f9083ba8-3a64-473e-80c9-c955271f60db.png)

The idea being that if I try to bind those two the one on the left pops off (drops as an item) + potentially a few duped copies. However in this small setup everything works fine!

Does the advanced memory card struggle with bigger systems and plenty of channels? (I mean my system isn't super big but still)

AE2 version: 1.7.10-rv3-beta-83-GTNH-1-g0b181e0

I can try to make a picture of my actual system were the bug occurs.

**Comment by GlodBlock** [comment]
can you prodive the fml-client-latest.log

**Comment by chochem** [comment]
ok, so here is pictures of my actual setup. Ignore all the background. Just the two p2p at the front:

![image](https://user-images.githubusercontent.com/40274384/169628677-a7a7cc4e-d73f-48c2-a79f-fe3bac1d8f7a.png)

I could link them just fine with the normal card but if I used the advanced one this happens:

![image](https://user-images.githubusercontent.com/40274384/169628653-2b326cd4-8054-46ee-bad7-a0155dc9601c.png)

the three p2ps in my inventory are the one that came off + 2 duped ones, and of course the system shut down because it is now illegally connecting.

oh even easier, I can literally do this: 
![image](https://user-images.githubusercontent.com/40274384/169628791-fd1ca7d8-9a7a-4ef2-aa08-8e3ef46fa812.png)

and it bugs out with advanced card. will check log.

**Comment by chochem** [comment]
[02:03:34] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova 2.1.2 v1
[02:03:34] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova 2.1.2 v1
[02:06:10] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova 2.1.2 v1
[02:09:50] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova
[02:10:35] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova
[02:10:48] [Client thread/DEBUG] [betterp2p/]: Bind 20 as input
[02:10:55] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova
[02:11:22] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova
[02:13:30] [AromaBackup/INFO] [AromaBackup/AromaBackup]: Suspending Server Thread.
[02:13:31] [AromaBackup/INFO] [AromaBackup/AromaBackup]: Continuing Server Thread.
[02:14:21] [Client thread/DEBUG] [betterp2p/]: Bind 0 as input
[02:14:31] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova
[02:15:16] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova
[02:15:35] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova
[02:15:47] [Client thread/DEBUG] [betterp2p/]: Bind 1 as input
[02:15:49] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova

**Comment by GlodBlock** [comment]
![image](https://user-images.githubusercontent.com/60341015/169656687-8fe19749-3a35-4aa8-9b99-2501460e3d67.png)
i still can't reproduce it. is it ok to download your save so i can test it?
also i sus this bug may rooted in ae since better p2p doesn't have update recently other than the search bar.
@repo-alt is there any update in ae2 p2p recently?

**Comment by chochem** [comment]
I mean the advanced memory card is very much new and largely untested. I asked around a bit on discord and at least two people tell me that they dont use it because they get straight up kicked from server/crash when trying to bind certain things (dont have any details or version for that).

I should probably add that my betterp2p version is: 1.0.7-3-g00855f0

Anyway, I figured it out! took me some time (basically reducing my network bit by bit to narrow stuff down)

The key thing is a security terminal. The advanced memory card bugs out and dupes items whenever there is a security terminal in the network. Reproducible test setup:

![image](https://user-images.githubusercontent.com/40274384/169658785-7d46ba4d-e927-4849-ad0a-6a9764521310.png)

tested with no biometric card/blank biometric card/biometric card for me. I only have a security terminal to use wireless stuff :(

**Comment by chochem** [comment]
actually I was inserting the biometric card wrong. Inserting a blank card with all permissions fixes things. :)

**Comment by GlodBlock** [comment]
even without permission it shouldn't remove the p2p or dupe it, still need a fix

**Comment by GTNHAfx237v7** [comment]
Ah yes security terminal strikes again !

**Comment by repo-alt** [comment]
@GlodBlock the only somewhat recent change related to p2p was their abilty to pass 128 channels (now disabled in config), but this change is on the level of grid nodes, don't see how that may affect such functions as renaming.

**Comment by chochem** [comment]
@repo-alt this is not about renaming. the first version of the ticket said so but that was wrong, it took me a while to figure this bug out. Its about using the advanced memory card to bind P2Ps while there is a security terminal. In terms of mods it is likely more about betterp2p than ae2 itself.

**Comment by repo-alt** [comment]
AE2 security is so broken, I hope someone will have time to rip it out leaving only the part providing the wireless terminal binding
