### ISSUE TITLE
Dangote Distillation Tower and MEGA Distillation Tower don't work with recipes requiring circuits

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#10360]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

last version 2.1.2.4

### Your Server

null

### Your Expectation

The regular distillation tower works great with the newly introduced recipes using circuits. However, Dangote Distillation Tower (GT++) and MEGA Distillation Tower (Bartworks) do not work at all with circuits.

I give an example of a recipe that does not work. (absolutely everything does not work using circuits, I checked
![Screenshot](https://user-images.githubusercontent.com/61422500/169271886-45775161-7b4d-48a5-8979-572af9d3b311.PNG)
)

### The Reality

need to fix

### Your Proposal

need to fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
yes it use a new recipe map. To make it useable we need to add thies recipe map to gt++ or/and to Bartworks

**Comment by FoKuCNiK** [comment]
well I hope to add a recipe map this is not a request to me, but to the GTNH coders

**Comment by FoKuCNiK** [comment]
GT5:
  
    @Override
    public GT_Recipe.GT_Recipe_Map getRecipeMap() {
        return GT_Recipe.GT_Recipe_Map.sDistillationRecipes;
    }
    
GT++:

	public GT_Recipe.GT_Recipe_Map getRecipeMap() {
		return mMode == 0 ? GT_Recipe.GT_Recipe_Map.sDistillationRecipes : GT_Recipe.GT_Recipe_Map.sDistilleryRecipes;
	}

BARTWORKS:

    @Override
    public GT_Recipe.GT_Recipe_Map getRecipeMap() {
        return GT_Recipe.GT_Recipe_Map.sDistillationRecipes;
    }

**Comment by FoKuCNiK** [comment]
recipe map they use the same kind, the problem is probably in the "checkrecipe"

**Comment by Steelux8** [comment]
The bigger DTs were never meant to work with circuits, since the DT was never expected to use circuits at all. They'll have to be configured to use the new circuits, since this is apparently here to stay.

**Comment by FoKuCNiK** [comment]
so you mean that the distillation tower from Gregtech should work with circuits and you don't need to repair the same ones from GT++ and BARTWORKS?

> The bigger DTs were never meant to work with circuits, since the DT was never expected to use circuits at all. They'll have to be configured to use the new circuits, since this is apparently here to stay.
