### ISSUE TITLE
Disable supertank screwdriver interaction on faces with cover

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10364]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-zeta

### Your Proposal

If there is a cover like a pipe on a super or quantum tank, then a screwdriver should not effect the tank settings but only the pump settings.

At the moment it changes both at the time:
![image](https://user-images.githubusercontent.com/40274384/169593040-34e7e80c-f9f5-4edb-a0f3-cfd73178e188.png)

### Your Goal

so that the screwdriver doesn't change two independent settings at the same time.

### Your Vision

To integrate the new overflow voiding feature properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1318
