### ISSUE TITLE
Elemental Dublicator Multiblock is broken

### ISSUE THREAD

**Issue by Eranicus** [GTNewHorizons/GT-New-Horizons-Modpack#10370]
### Your GTNH Discord Username

Eranicus#5476

### Your Pack Version

2.1.2.4

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

For Elemental Dublicator to work properly like it used to, in pack version 2.2

### The Reality

Problem is the following, imagine you got 10 diffrent data orbs, you start game and data orbs 1,4,7 are working (all other just spam log with errors), you restart game and now data orbs 2,5,10 are working but all other are not... looks like something to do with recipe registering during loading ?...

Errors in the screen below, spam every 4-5 sec with the same message.

https://cdn.discordapp.com/attachments/181078474394566657/949812363522080808/111.png

On pack version 2QF it was working without any problems for me.

### Your Proposal

Please fix the multiblock... or if it is not fixable it should be removed/made uncraftable because it's a bad idea to have such an expensive to craft multi broken.

But the worst part is that there are no alternatives to this multi since replicators cant be used in PA's..

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/222
