### ISSUE TITLE
Crash on creating game

### ISSUE THREAD

**Issue by vippeople22** [GTNewHorizons/GT-New-Horizons-Modpack#10372]
### Your GTNH Discord Username

aglow#2576

### Your Pack Version

2.1.2.4-zeta

### Your Server

SP and multiplayer

### Type of Server

Single Player

### Your Actions

I try loading a new game or joining the zeta test server.
When I try loading a new game I [crash](https://paste.ee/p/7Ld9X)
It happen every time, 
For joining any server I get an issue of mod compatibility
![image](https://user-images.githubusercontent.com/46292914/169673682-3ce16bf9-aacf-4a25-bc10-7ac1f04a8ddf.png)
this is new install I get from announcements and just updated old version from multimc

### Crash Report

https://paste.ee/p/7Ld9X

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
_Assuming_ that this is the key error here:
> [17:37:17] [Client thread/ERROR] [FML]: The fluid registry is corrupted. A fluid gregtech.api.objects.GT_Fluid hexafluorosilicic acid is not properly registered. The mod that registered this is broken

Then you need to update gtnhlanth to a newer version from discord or jenkins. Or wait for Dream to make a new build.

I don't know anything about the server though.
