### ISSUE TITLE
Replace Uncertainty Resolver with Uncertainty Resolver X

### ISSUE THREAD

**Issue by minecraft7771** [GTNewHorizons/GT-New-Horizons-Modpack#10374]
### Your GTNH Discord Username

minecraft7771#0427

### Your Pack Version

2.1.2.3QF

### Your Proposal

I think that the normal Uncertainty Resolver should be disabled and the Uncertainty Resolver X should take its recipe. Both work the same but the Uncertainty Resolver has blue squares that blink in different intervals, while the Uncertainty Resolver X has its squares in different shapes of blue. 

### Your Goal

I do understand how the puzzle works but have a hard time to map the squares correctly because of the blinking.

### Your Vision

It would increase the accessability of solving the Uncertainty of the Quantum Computer without removing the mechanic entirely. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Colen** [comment]
Isn't the resolver X basically just the debug solver?

**Comment by minecraft7771** [comment]
Idk how it first got into the mod but it has a recipe that is much later in the game. However it requires you to move the  tiles around to solve the Uncertainty. It's just that the tiles are different static colors instead of blinking.
