### ISSUE TITLE
[RFC] Void Miner Balancing

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#10378]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.4dev

### Your Proposal

As briefly mentioned on Discord I'd like to open up a discussion about void miner balancing.

The approach is to look at the production rate, energy consumption and gas boosting.

Currently, a T2 void miner makes double the amount of ores/s as a T1 miner, while using four times the energy. This is inline with the GT 4/2 overclock of cutting processing time in half while requiring four times the amount of Eu/t.
A T3 void miner falls out of line, as energy requirement is quadrupled while output is increased by a factor of 1.5 instead of 2.

Therefore, one may wonder why actually invest in a T3 void miner instead of building a second T2 miner, as you receive double the output.

Regardless of tier, all void miners will receive an output boost when using Neon (x2), Krypton (x4), Xenon (x16) and Oganesson (x64).

This results in the following table:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mandelm/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mandelm/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

VM Tier | Eu/t | Ores/s | Ores/s Neon | Ores/s Krypton | Ores/s Xenon | Ores/s Oganesson
-- | -- | -- | -- | -- | -- | --
LuV | 32768 | 2 | 4 | 8 | 32 | 128
ZPM | 131072 | 4 | 8 | 16 | 64 | 256
UV | 524288 | 6 | 12 | 24 | 96 | 384

</body>

</html>

I propose to:

1. not buff void miners in general
2. make T3 void miner more attractive instead of placing more T2's

This could be achieved by 

1. adjust base production rate without gas boost
2. adjust gas boost
3. tiering of available gasses

Not scope of this RFC is
1. void miner recipes
2. Replicating process of gasses

My suggestion is the following:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mandelm/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mandelm/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

VM Tier | Eu/t | Ores/s | Ores/s Neon | Ores/s Krypton | Ores/s Xenon | Ores/s Oganesson
-- | -- | -- | -- | -- | -- | --
LuV | 32768 | 2 | 4 | 8 | 16 | 32
ZPM | 131072 | 4 | 16 | 32 | 64 | 128
UV | 524288 | 8 | 48 | 96 | 192 | 384

</body>

</html>

achieved by the following new gas multipliers:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/mandelm/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/mandelm/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Gas | Ne | Kr | Xe | Og
-- | -- | -- | -- | --
LuV | 2 | 4 | 8 | 16
ZPM | 4 | 8 | 16 | 32
UV | 6 | 12 | 24 | 48

</body>

</html>

Further I want to open discussion about available gasses, as a further incentive to progress in tier.
Therefore I suggest to disallow Xenon and Oganesson for the T1 miner and disallow Oganesson for the T2 miner.

### Your Goal

Bring balance to something currently considered unbalanced

### Your Vision

Less machine spam, more attraction towards progress.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
I agree with what @Steelux8 said. For example neon is basically irrelevant as you can straight up go to krypton or xenon. And since oganesson needs a T3 fusion reactor you can't make it when you first get your hands on the T1 VM so imo nothing is lost if that gas is cut from T1 and T2.
