### ISSUE TITLE
Recipe inconsistency

### ISSUE THREAD

**Issue by Qactis** [GTNewHorizons/GT-New-Horizons-Modpack#10384]
### Your GTNH Discord Username

Qactis

### Your Pack Version

2.1.2.3qf

### Your Proposal

LV Muffler recipe for crafting table includes a bronze fluid pipe, but for the assembler version it includes a large bronze fluid pipe.

### Your Goal

Both should be the same size pipe

### Your Vision

Consistent recipes make the pack more fun for everyone

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
duplicate and already fixed in dev. :) https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9878
