### ISSUE TITLE
Give the Elemental Duplicator a crop replicate mode

### ISSUE THREAD

**Issue by stlchase40** [GTNewHorizons/GT-New-Horizons-Modpack#10381]
### Your GTNH Discord Username

stlchase40#7583

### Your Pack Version

2.1.2.2

### Your Proposal

My proposal is to add the functionality of the Crop Replicator to the Elemental Duplicator. It could be done with a screwdriver to change the mode just like the other multis with multiple modes.

### Your Goal

By the time you HAVE the ability to make the elemental duplicator, resources are relatively infinite and makes crops kind of useless unless you spend massive amounts of hours breeding them to scale up to the amount you require at ZPM+ tier. I dont think it would break any balance and the ability to mass produce seeds quickly would give more incentive to make the multi and also continue to make crops "worth it". The UU-Matter requirement is already high for seed replication, which would make creating thousands of them a lengthy task.

### Your Vision

I think it would improve the pack by finally granting what was the biggest challenge for anyone who was doing ic2 crops, to finally have the ability to get them in a more efficient and streamlined way. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Colen** [comment]
Isn't this basically just buffing seed replication? Why not just buff it on the intended machines instead?
