### ISSUE TITLE
Silicon Line: Needed adjustment for current silicon dust

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#10385]
### Your GTNH Discord Username

Lord Peverell#3125

### Your Pack Version

2.1.2.4 dev

### Your Proposal

From the current discussion going around on discord, this new silicon line basically changes everyones silicon dust/ingots into raw silicon that then needs to be reprocessed through the line... I dont believe this is even a smart decision. Why not adjust the silicon dust people already have into the end part of the new line?

### Your Goal

Adjust the final product dust to reflect silicon dust from 2.3 and prior

### Your Vision

Make it so people who are mid-late game aren't punished for no reason and having to reprocess millions of dust before they can be used again

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I am very strongly against that. You still need the raw silicon for many parts of the game, so taking that all away is terrible. It's not like you only use silicon for boules.

**Comment by chochem** [comment]
maybe actually check out .4 before asking for changes. ;)

> Is solar grade use ONLY for boules?

yes. though I think dream has talked about also using it for solars I think.

**Comment by Dream-Master** [comment]
i need to recheck all recipes and decide where raw silicon is usefulland which recipes use the new SiSg
