### ISSUE TITLE
MineColonies for GTNH?

### ISSUE THREAD

**Issue by fiftycthulhu** [GTNewHorizons/GT-New-Horizons-Modpack#10393]
### Your GTNH Discord Username

Mycroft Holmes#1618

### Your Pack Version

2.1.2.3

### Mod Name

MineColonies

### The Mod to Add

Allows for RTS-like basebuilding, allowing you to automate resource gathering and some production through Villagers.

### Your Reason

This would allow for some automation of component and equipment production for those of us (like me) too dumb to make automation chains.

### Preliminary Investigation

I have not added this mod to the pack, as it needs to be custom modified to provide pack-specific materials and components

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Pxx500** [comment]
No
