### ISSUE TITLE
[RFC] Assembly line soldering alloy changes

### ISSUE THREAD

**Issue by greesyB** [GTNewHorizons/GT-New-Horizons-Modpack#10397]
### Your GTNH Discord Username

Greesy#2016

### Your Pack Version

2.1.2.3qf

### Your Proposal

This RFC is regarding the [new soldering alloy change](https://github.com/GTNewHorizons/GTplusplus/pull/193) which replaces basic soldering alloy in all assembly line recipes with an ABS alloy made of indium and a few other materials.

First off, I think that the idea of changing out basic soldering alloy in assline recipes is conceptually good. That said, mindlessly swapping one for another is, as mudspaw aptly described in discord, negative content. It is forcing players to revisit something they had thought they completed for zero reward.

### Your Goal

I think the old soldering alloy recipes should continue to exist (at least for one major version) alongside the new soldering alloy recipes so that updating players do not immediately have to replace dozens, or in the case of UV+ players, literally hundreds of assembly line patterns for zero reward.

Instead, the new recipes should have some benefit to them. The most obvious benefit that wouldn't be immediately overpowered is recipe processing time. Hell, you could even double the processing time of the old soldering alloy recipes and make the new recipes use the unchanged old time. While I'd argue that's still negative content, it would be better than it is now.

Additionally, [this comment](https://github.com/GTNewHorizons/bartworks/pull/129#pullrequestreview-987221948) references wanting to add yet another alloy for endgame. Again, I think this is fine conceptually, but if it is going to happen it should happen _now_ along with the other alloy and take the same thoughts as above into consideration.

### Your Vision

Flesh out soldering alloy changes and provide alternatives and incentive to use the new instead of breaking existing automation just for the sake of adding something "more complex".

Despite all the memes of this pack being nothing but pain, people enjoy playing it because players are generally rewarded for their efforts. Updates that break players' existing automations without providing ANY reward for fixing them removes that enjoyment and causes, as mudspaw put it again, forced burnout.

Would like to hear other's thoughts.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Eranicus** [comment]
I'm at UHV at the moment and I'm totally fine for end game to become more hard.
Currently I have 24 asslines full of recipes, I dont mind changing all of them but preferably only ones... because if additional comment regarding adding another (end game) soldering later is true, I really dont want to chenge recipes second time after it is implemented...  

My solution is the following, leave current soldering as it is and decide if another end game soldering will be introduced or not.

**Comment by Steelux8** [comment]
I have tried to have both the old solder and the new one at the same time. The Assembly Line does not allow this, and every player would be forced to re-do their scanning twice. If this ends up being done, which I'd really like, it will be with some changes in the assline itself or the data sticks, which I unfortunately don't know how to do.

**Comment by Connor-Colenso** [comment]
Isn't it just delaying the inevitable by extending it one version though? A better solution to tackle these issues would probably be some tool to automatically replace certain items in many recipes at once, perhaps even an entire network. Maybe @repo-alt would be kind enough to look into if this is possible (assuming the idea can be fleshed out more). No one likes replacing patterns but delaying a change for a major version is a long time (potentially 6m-1y).

**Comment by greesyB** [comment]
> Isn't it just delaying the inevitable by extending it one version though?

If both old and new soldering recipes could be in place at once with different processing times for each then it would give players a meaningful reason to switch other than "all my automation broke". It would let them do it at their own pace. Sounds like assembly line recipes can't work like that without changes to the machine itself though, oh well.

> A better solution to tackle these issues would probably be some tool to automatically replace certain items in many recipes at once, perhaps even an entire network.

I would love to see something like that implemented, and would embrace these changes if it could happen.

> I would agree on both of these changes happening at once

One of the reasons I was not pleased with the soldering alloy change as-is is because it is only challenging at all right when you get the assline, and even then is really just an indium check. Past LuV and especially beyond the new alloy is barely more of a challenge than the old. An endgame alloy would help (UHV+?)

**Comment by Connor-Colenso** [comment]
> You can easily edit a lot of patterns with OC( you have to connect adapter to each interface tho)

Not sure I'd consider it easy if you have to connect an OC adapter to every interface but yes you can in theory do it with OC. Would be nice to have a tool to update the entire network though.
