### ISSUE TITLE
Raw Silicon production from Silicon Dioxide should be lossless like Raw Silicon to Solar Grade Silicon

### ISSUE THREAD

**Issue by Nilau1998** [GTNewHorizons/GT-New-Horizons-Modpack#10399]
### Your GTNH Discord Username

Noila#7604

### Your Pack Version

2.1.2.4-zeta.4

### Your Proposal

Currently the silicon lines in MV tier are running lossless, at least the line for silicon to silicon solar grade does. However the line for SiO2 to raw silicon doesn't which makes it quiet the hassle as it runs at a magnesium loss.
The following screenshot visualizes both lines. The red thick arrow on the Silicon Dioxide to Raw Silicon line indicates where the magnesium loss happens. The 1x, 4x etc. within the red boxes are just recipe multipliers to equalize input and outputs between machines.
![](https://i.imgur.com/tROMObj.png)

### Your Goal

Make it so that the electrolyzer recipe for 2MgO outputs 2Mg + 2O instead of Mg + O for proper chemistry and for the sake of making it lossless.

### Your Vision

We won't have to go and prospect for magnesium in MV tier because the universe decided to void 1 Oxygen and 1 Magnesium somewhere. :)
Well and it makes the processes lossless like they are supposed to be.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by tommmmmmmmm** [comment]
i agree, i was going to make a new issue for this exact reason....

**Comment by WSpadaro** [comment]
I agree as well, currently in Lv and the loss in magnesium makes this path very difficult and sorta forces to use 320 redstone -> boule.

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/179517673-fae2c934-ce95-4d42-8ba9-abb6e73b5cba.png)
![image](https://user-images.githubusercontent.com/40274384/179517714-6cf74801-0ef7-4ceb-81c1-b93918dbc573.png)
