### ISSUE TITLE
Cooking table temporarily removes your armor's effects

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#10396]
### Your GTNH Discord Username

maniifestantes

### Your Pack Version

2.1.2.4

### Your Server

zeta

### Type of Server

Thermos

### Your Expectation

when you open the cooking table gui from cooking for blockheads, your armor becomes invisible, and their bonus are removed until you click on one armor slot, or get hit and the armor loses durability (they don't come back if your armor is unbreakable)

### The Reality

https://user-images.githubusercontent.com/57275066/170732222-c8ab7075-82ae-45be-93c2-eaa8b1acdecf.mp4

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
From testing it only occurs on the cooking table but not any of the cooking books.

The armor can be retrieved by clicking on the armor slots
![CookingBug](https://user-images.githubusercontent.com/47131096/182654317-8b9e4b6e-437e-4dec-be56-bf1392728b16.gif)
