### ISSUE TITLE
Make Nether Stars Accessible Without Combat

### ISSUE THREAD

**Issue by henrydukepickle** [GTNewHorizons/GT-New-Horizons-Modpack#10398]
### Your GTNH Discord Username

henryduke#0140

### Your Pack Version

2.1.2.4z

### Your Proposal

Nether Stars should have some way to obtain them that can be done reasonably in peaceful. I'm not saying it should be easy, but some tech-based recipe. The vanilla way should still be present

### Your Goal

Many players do not like the mob balance in the pack. Many players, like myself, bypass mobs by playing on peaceful. While this does make things harder at some points, which is a reasonable trade-off, the nether stars needed for the NASA workbench in HV are the only point in mainline tech progression, as far as I know, where peaceful makes it near impossible to progress.

### Your Vision

It would help peaceful players enjoy the pack.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by henrydukepickle** [comment]
I should also mention that the recipe can be quite expensive. The stars can be duped without combat, so only 1 is needed.

**Comment by TwoTailedFox** [comment]
You can make Nether Stars without combat using ThaumCraft.

**Comment by henrydukepickle** [comment]
How?

**Comment by TwoTailedFox** [comment]
Balance Shards, made in a Crucible with shards of each aspect. You grind up Balance Shards to make Salis Mundis (sic), which can be made into Nether Stars

**Comment by henrydukepickle** [comment]
That's the dupe method I mentioned. You need 1 nether star to begin the process.

**Comment by ScriptedPiky** [comment]
In the Twilight Forest and specifically the Lich towers, you can obtain tiny piles of nether star dust from the various chests, allowing you to do the salis into nether star method. You can also technically obtain nether star ore via one of the early Blood Magic meteors. Granted it does require a significant amount of investment into getting that in the first place but hey, it's one way of doing it if you're brave.

**Comment by boubou19** [comment]
the pack was never intended to be played in peaceful mode. Because you got rid of the hostile mobs, you might as well spawn one nether star too.
