### ISSUE TITLE
Glue and Graphene feedback and suggestions for 2.1.2.4

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10391]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-zeta

### Your Proposal

Overview: the current .4-zeta (.4 4-dev) version contains advanced glue (advanced glue) and super glue (Ethyl Cyanoacrylate). Their main usage currently is graphene but the super glue can also be used for duct tape, high tier battieries and tier 2 thermal cloth. However all of these have alternative recipes.

General thoughts:
- I really like the new glues. :)
- The advanced glue is relatively easy to make for a player familiar with chem lines (it uses just LCR and mixer) and synergizes well with an epoxid setup (acetone, acetic acid). As such I think it should be seen as an EV+ material even if it can be done earlier.
- The super glue is much harder. A long chemical line that requires many chemplants steps. While in principal doable in late IV, it should be considered an LuV+ material due to the complexity and to not overload IV even more.
- At the moment any player focussed on speed or ease will probably just ignore the glues as simpler alternatives exist. That would be a shame. Therefore some of those alternative recipes should be removed.

Specific suggestions:
- Done. **remove the refined glue graphene recipes for the Nq/Eu/Am wafers.** It can stay for phosphor wafers to get players started.
- ~~remove the carbon->graphene MT recipe or tier it much higher (I am thinking maybe UHV)~~ (edit: after some testing I think this might be fine as is, as the multi MT is rather slow and inefficient.)
- add advanced glue duct tape and maintenance hatch recipes. they just looks like they were forgotten.
- remove super glue from the T2 thermal cloth, it should not be used in IV in my opinion.
- but maybe use advanced glue for T1 and/or T2 thermal cloth (without a plastic alternative) 
- ideally find more uses for advanced glue (in EV+) and super glue (in LuV+)
- more of a _minor point:_ maybe adjust the amount of refined glue/advanced glue/super glue used in recipes. Ideally the values should be either a multiple of 144L or correspond to one of the other volumetric flask assembler settings (250L, 500L). The current non-standard values of 75L/100L/125L/200L/375L are strange.

I would be very interested to hear what other people think. :)

more edits:
- ~~add LCR recipes for new chem reactor recipes (sodium cyanide dust, cooper (II) Sulfate Dust, potentially others)~~ moved to dedicated ticket: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11428
- Done. **re-add advanced glue recipe. Somehow this got lost between .4 4-dev and .4 5-dev.** 
- Done. change special ceramics from refined glue to advanced glue
- add oxygen mask recipe using refined glue

### Your Goal

The goal is to integrate the new higher tier glues into the pack better.

### Your Vision

The vision is to integrate the new higher tier glues into the pack better.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I will continue to add edits. The latest is that advanced glue lost its recipe. :(

**Comment by fluffle** [comment]
Advanced glue can't be used to make the maintenance hatch, only refined glue and cyanoacrylate. But for a reasonable amount of the pack advanced glue is going to be the one you have lying around. Any chance of an additional recipe here?

**Comment by chochem** [comment]
if there are still problems they should now get individual tickets
