### ISSUE TITLE
NEI feature to select the current machine catalyst from the list on the left

### ISSUE THREAD

**Issue by Nilau1998** [GTNewHorizons/GT-New-Horizons-Modpack#10395]
### Your GTNH Discord Username

Noila#7604

### Your Pack Version

dev 2.1.2.4

### Your Proposal

The new NEI gives us the ability to look at GT recipes and see how long it takes to process, how much EU and so on. When we open the avaliable recipes in a machine it shows us those recipes for the current tier the machine is in. E.g. checking the processing recipes in a LV Macerator gives us the recipes avaliable in LV and their values adjusted to it (OC..).
However if we check for example the usage of some random crushed ore via NEI search and go to the Macerator tab it will only show us the recipe adjusted to ULV, or rather the default without OC of a process.

My feature request is that we get the chance to make use of the list that is shown on the left when looking at the usage of something. I'm talking about this list over here:
![](https://i.imgur.com/s01WITJ.png)
It would be a nice QoL feature to be able to press a button when hovering over a machine and getting NEI to adjust the recipe to the tier of the machine selected. A middle mouse click would work for example.
So if we look up the usage of crushed copper ore via the NEI search bar and then head over to the Macerator we have the default values showing everything for ULV, would be a processing time of 20s in this case. Now we head over to the list of machines, hit middle mouse on the MV Macerator and NEI shows the same recipe but adjusted to MV OC, so 10s processing time etc.

### Your Goal

It's a nice QoL feature that would make planning within the game a tiny bit easier, especially with the OC values changing over tiers.

### Your Vision

The catalyst (I believe that's how machines are treated in NEI) selection would be another awesome QoL feature for the pack to make it even better and more fun to play. It gets rid of me and maybe others having to use spreadsheets to do OC calculations).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by slprime** [comment]
Like point 10 in https://github.com/GTNewHorizons/NotEnoughItems/pull/240?

**Comment by Nilau1998** [comment]
> Like point 10 in [GTNewHorizons/NotEnoughItems#240](https://github.com/GTNewHorizons/NotEnoughItems/pull/240)?

Ah snap never saw that issue, I'll close this one. Thank you.
