### ISSUE TITLE
Many recipes with circuits broken in .4 5-dev

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10404]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4 5-dev-pre-test

### Your Server

SP

### Your Expectation

Fluid regulators should be craftable. (edit: also many other items, see comments)

### The Reality

They are not. The recipe shows in NEI but it doesn't work. I tested LV, MV, HV, EV, and IV.

### Your Proposal

fix it. I am fairly sure things worked fine in 4-dev. So this has to be something added or changed just now.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
some more testing:

I can make an LV fluid regulator, but **only** if I use electronic circuits as the LV circuits. microprocessors/ILC/basic magneto do not work.

**Comment by chochem** [comment]
This is affecting other recipes as well.

Specifically the 16k me storage component. I have not even found a combination of circuits that work. And again this was fine in 4-dev.

But if its those two then there might be many more. It looks like a pretty major bug in that case.

**Comment by chochem** [comment]
ok I am just trying random 'similar looking' recipes: 

- The Simple PCB from Steve Carts is also only craftable with the electronic circuit and no other LV one.
- The same is true for the gregtech schematic.

I guess I dont really need to continue trying. its gonna be a lot.

**Comment by chochem** [comment]
probably related to https://github.com/GTNewHorizons/GT5-Unofficial/pull/1064

**Comment by KamenriderZO** [comment]
Same by making OC microchips , every MV circuit doesn't work now.except you cheat and get some "Any MV Circuit" from mod GT New Horizon and set it in the machine.then the recipe can consume the MV circuit(original circuits)

**Comment by miozune** [comment]
Closing as problematic commit was reverted. For those who want a fix, here's the latest dev build (make sure to fetch "origin/dev" branch!) http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/2686/
