### ISSUE TITLE
Advanced memory card crashes game

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10406]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4 5-dev-pre-test

### Your Server

SP

### Type of Server

Single Player

### Your Actions

clicked the advanced memory card on a p2p to open the GUI (and select it).

I am using mod versions: betterp2p-1.7.10-1.0.7-4-gb9b399c and appliedenergistics2-1.7.10-rv3-beta-83-GTNH-4-g32a0592

### Crash Report

[crash-2022-05-28_17.00.08-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8791435/crash-2022-05-28_17.00.08-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
@GlodBlock

**Comment by GlodBlock** [comment]
it is the MeTextField update in ae2 causing the crash, i can't fix it now since the ae2 doesn't give a tag for me to setup the latest dev environment. you can downgrade ae2 as temporary solution. i will fix it asap when ae2 build the tag.

**Comment by chochem** [comment]
ok. :) 
which ae2 version should I use?

**Comment by GlodBlock** [comment]
[pack.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8791470/pack.zip)
here

**Comment by Dream-Master** [comment]
@GlodBlock is this guy already pushed ?

**Comment by GlodBlock** [comment]
push what?

**Comment by Dream-Master** [comment]
@GlodBlock you add a zip file with a fix i guess. Want to know if this is on github?

**Comment by chochem** [comment]
that zip is just the downgraded AE2 version. Nothing new.

**Comment by Dream-Master** [comment]
yea ik now.
