### ISSUE TITLE
Error with uncomeatable mod "Avaritia" when try join Zeta server

### ISSUE THREAD

**Issue by RimanKis** [GTNewHorizons/GT-New-Horizons-Modpack#10405]
### Your GTNH Discord Username

RimanKis#4938

### Your Pack Version

2.1.2.4-4

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

I download current version of test build (2.1.2.4-4). Run client and join the server.

### The Reality

![image](https://user-images.githubusercontent.com/106441898/170832084-aa0d6a3f-a0f4-4694-aa9c-ef79ad80bdb5.png)
I download current version of test build (2.1.2.4-4). Run client and try to join server (Test server Zeta). This error occurred.

### Your Proposal

Fix it :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
https://discord.com/channels/181078474394566657/234936569360809996/978103414405861416

**Comment by miozune** [comment]
Can we close this?

**Comment by Dream-Master** [comment]
yes we on pre 18
