### ISSUE TITLE
A QoL Change to Assline Patterning

### ISSUE THREAD

**Issue by stlchase40** [GTNewHorizons/GT-New-Horizons-Modpack#10417]
### Your GTNH Discord Username

stlchase40#7583

### Your Pack Version

2.1.2.2

### Your Proposal

If a recipe contains one of more fluids in its recipe, then move all the items over to the right by one for each fluid in the recipe in the pattern terminal. It would allow for a QoL change which would allow the user a better ability to make use of the shift-click the recipe into the correct place feature.

### Your Goal

With the new soldering alloy++ alloys being added, I was trying to figure out how to minimalize the pain of re-patterning my assline patterns. It would be extremely helpful to have the shift_click pattern into place feature would offset the item ingredients by number of fluids in its recipe. this would allow easier patterning  for the assline as it's best practice to filter the fluids first in the pattern.

### Your Vision

It would add a major QoL feature to one of the most annoying things you have to do. It's not a major implementation but feels like it would make life a million times easier to pattern your assembly line.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I dont know about changing patterns but this would in particular be great for new patterns. A nice and simple trick.

**Comment by minecraft7771** [comment]
Fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/8
