### ISSUE TITLE
Bricked Blast Furnace runs without fuel

### ISSUE THREAD

**Issue by Rubix2048** [GTNewHorizons/GT-New-Horizons-Modpack#10414]
### Your GTNH Discord Username

Khona Betwanhe#7122

### Your Pack Version

2.1.2.4-5 dev pre test (from Announcements)

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Crafting 5 steel ingots and 1 ash with 5 iron ingots and one block of coal coke in bricked blast furnace

### The Reality

One iron ingot is immediately consumed without fuel, crafting into 1 steel ingot and 8 tiny ash.
Additionally, there do not seem to be any recipes that consume blocks of coal/coke/charcoal anymore.
![image](https://user-images.githubusercontent.com/12417837/170887778-f6614968-de62-4e98-81d0-07e41efa29ff.png)

### Your Proposal

Re-add coal/coke/charcoal block recipes and remove fuel-free recipes for all crafts (it appears to apply to any BBF recipe, not just iron->steel)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
should be fixed . Need to test next dev version.

**Comment by chochem** [comment]
fixed in dev14.
