### ISSUE TITLE
XL Gas Turbine doesn't run while pollution is disabled

### ISSUE THREAD

**Issue by xSkewer** [GTNewHorizons/GT-New-Horizons-Modpack#10411]
### Your GTNH Discord Username

xSkewer#4113

### Your Pack Version

2.1.2.3qf (occurs on 2.1.2.4-5 too)

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I tried to run an XL Gas Turbine while pollution was disabled and expected it to run fine.

### The Reality

The first time it runs, it hits ~3.7% efficiency then immediately turns off. Any attempt to turn it on again results in it immediately turning off again.

### Your Proposal

From a bit of testing, the problem seems to come from the polluteEnvironment method in GregtechMetaTileEntity_LargerTurbineBase.java in GT++. Adding another condition to the if statement to check if pollution is enabled fixes it, but I'm not a good coder so there's probably a better solution.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/200
