### ISSUE TITLE
Add recipes for all gardens

### ISSUE THREAD

**Issue by MrJakobLaich** [GTNewHorizons/GT-New-Horizons-Modpack#10424]
### Your GTNH Discord Username

MrJakobLaich#6170

### Your Pack Version

2.1.2.3

### Your Proposal

Add recipes for all pams gardens to be craftable into each other

I have spend way too long IRL running (and by the end flying in creative) to find ground and desert gardens.
I have still not found any tbh and I've searched a lot.

Water gardens are craftable.
Make every garden craftable from the other gardens.
"but there are lootbags for gardens"
yeah but not everyone likes that, I personally don't like lootgames / lootbags / quest reward progression because it feels like cheating
"I made an HV electrolyzer in steam because I got all the items from minesweeper" <- is what I personally consider tier skipping cheating
And if we already have the water gardens craftable we might just add recipes for the other ones too
it will not change anything for anyone except make it better for the few poor souls that have to cheat them in currently 

### Your Goal

Makes more sense than to just have only water ones craftable 

### Your Vision

Be able to actually get the gardens without magical lootgame cheating 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
#9665 might work better than garden RNG, but no one is working on it

**Comment by Dream-Master** [comment]
No i plan to remove the recipes, I thought Water gardens not spawn in RWG but this is not true
