### ISSUE TITLE
Jabba & Tinkers interaction - Dupe & crash

### ISSUE THREAD

**Issue by Officialy** [GTNewHorizons/GT-New-Horizons-Modpack#10425]
### Your GTNH Discord Username

Officialy#2961

### Your Pack Version

2.1.2.3

### Your Server

Private Server - No modifications 

### Type of Server

Vanilla Forge

### Your Actions

Upon placing a tinkers construct crafting table next to a jabba barrel, you can take items out of it as normal. However, if you lock the barrel, then proceed to take the original items out using either the barrel itself or the crafting table, you'll reach 0. However, you can still pick up this item, interact with it (infinite uses if it's a loot reward). Upon throwing this item onto the ground, it crashes the server. (Potentially may be an interaction with fire, as I threw it into fire)

Note: Not repeatable in single player as far as I've tested, though I didn't test it with fire.

### Crash Report

I'll upload this soon, gotta wait for the server admin to give me the crash log. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ToastedEggplant** [comment]
Crash report: https://pastebin.com/WM0MtDjy

**Comment by eigenraven** [comment]
Fixed
