### ISSUE TITLE
Mod rejections [FMLMod:LogisticsPipes{0.9.5.4-GTNH}]

### ISSUE THREAD

**Issue by Militant-Panda** [GTNewHorizons/GT-New-Horizons-Modpack#10432]
### Your Pack Version

2.1.2.3

### Your Server

Private server

### Type of Server

Open To LAN

### Your Actions

Trying to join players on the same network with the same version of GT New Horizon, but the error message "Mod rejections [FMLMod: LogisticsPipes{0.9.5.4-GTNH}] " shows up. A friend of mine tried hosting a server(same version and all) and when I try to join I get the same error message. I went looking through the mod folder and saw that particular mod is missing. Trying to find the correct version of this mod was hard, so I just went to someone with the same mod pack and acquired it from them, BUT whenever I try to download it and move it to the mod folder, I think my anti-virus software is removing it. The only anti-virus software I have is Windows defender on an up-to-date Windows 10 machine. Any ideas on how to stop my evil anti-virus software from deleting this mod every time I try to move it?

Things I have tried already:
updates on security
restart PC
reinstall GT New horizons
make the mod folder for GT New horizons an exception in my firewall

Any ideas on what to do next/corrections to my diagnosis?

### Crash Report

Connection Lost:
Mod rejections [FMLMod:LogisticsPipes{0.9.5.4-GTNH}]

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
this is why i made 2 announcements on the discord server...
