### ISSUE TITLE
TC Crafting Station has odd UI behaviour

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10430]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The middle mouse wheel controls the scrolling functionality for the contents of a chest if a chest is placed next to it. The middle scroll wheen should only operate the scrolling functionality, and should not interfere otherwise with the UI.

### The Reality

If the mouse hovers over an occupied grid square and the mouse wheel is moved, it automatically moves the contents of that cell to the crafting grid. This makes it incredibly frustrating to use the scroll functionality.

### Your Proposal

Ensure that the mouse wheel does not cause unintended items to enter the crafting grid.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by eigenraven** [comment]
Fixed by <https://github.com/GTNewHorizons/TinkersConstruct/pull/49>, I couldn't find this issue when making the PR
