### ISSUE TITLE
Noble gas fluid cell in centrifuge dupes cells. 

### ISSUE THREAD

**Issue by Arvannies** [GTNewHorizons/GT-New-Horizons-Modpack#10436]
### Your GTNH Discord Username

Arvannies

### Your Pack Version

2.1.2.4-5

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Expected the noble gas fluid cell recipe to require empty cells to process. 

### The Reality

Used one noble gas cell only and returned 21 CO2, 9 He, 3 CH4, and 1 deuterium. Duping 33 cells. 

### Your Proposal

Add empty cells to recipe. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1062/commits/b03176da0952577c16758c2018131db7bc9eab5d
