### ISSUE TITLE
Solar goggles does not provide the amount of energy per tick the research description says

### ISSUE THREAD

**Issue by SpwnX** [GTNewHorizons/GT-New-Horizons-Modpack#10442]
### Your GTNH Discord Username

SpwnX#5613

### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Don't know

### Your Expectation

Expect about 128 EU/t of armor charging from solar goggles of revealing, the same of a hybrid solar helmet.

### The Reality

Power production is not equal to the hybrid solar helmet, it is probably something around 10 EU/t during day and 1 EU/t during night.
Observed by getting a solar goggles of revealing from NEI and comparing visually the charging rate of an empty piece of armor with both helmets.

### Your Proposal

Fix it in the code.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment]
Fixed in dev
