### ISSUE TITLE
Server build not working

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#10447]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

last version 2.1.2.4

### Your Server

MP

### Your Expectation

I explain the situation:

The server worked on version 2.1.2.3qf for about 2 months, and once, during a scheduled server reboot, it did not start. (literally 7 days ago) (gives an error which you can see in the attached log)

I tried to delete World, it's not about him, that is, the mods themselves that worked for about 2 months stopped working.

I did not make any changes to the configs and mods, I took everything as a pack in the #Annonuncents section.

I tried to install version 2.1.2.4 and 2.1.2.5 the same log and the server does not start with an error that I will attach below.

I can run only assembly 2.1.2.2 on the server and it will work without crash, don't you think it's strange?

Еhe core of the Thermos server (it doesn't matter since the build has always worked on it, no need to blame everything on this, this is not the source of the problem)

In general, I don’t know how to solve this problem, I attach a crash log and am ready to answer any questions for those who want to help me

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8847007/latest.log)

### The Reality

help

### Your Proposal

help

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FoKuCNiK** [comment]
checked the same thing on the ULTAMINE core, the same crash gives

**Comment by FoKuCNiK** [comment]
2.1.2.2 work perfectly TESTED 08.06.2022
2.1.2.3qf Server Pact not work TESTED 08.06.2022

**Comment by Ydrec** [comment]
`[22:01:31] [Server thread/ERROR]: There was a problem reading the entry META-INF/versions/11/pro/gravit/utils/Downloader$ProgressTrackingBodyHandler$ProgressTrackingBodySubscriber.class in the jar /home/Mega/ServerWrapper.jar - probably a corrupt zip`

You may want try redownloading a stock 2.1.2.3qf serverpack and testing if it would laucnh without you altering it aside from enabling Thermos

**Comment by FoKuCNiK** [comment]
> `[22:01:31] [Server thread/ERROR]: There was a problem reading the entry META-INF/versions/11/pro/gravit/utils/Downloader$ProgressTrackingBodyHandler$ProgressTrackingBodySubscriber.class in the jar /home/Mega/ServerWrapper.jar - probably a corrupt zip`
> 
> You may want try redownloading a stock 2.1.2.3qf serverpack and testing if it would laucnh without you altering it aside from enabling Thermos

i installed CLEAN version 2.1.2.3qf

**Comment by GlodBlock** [comment]
try to remove `GregTech.lang` if there is any

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
