### ISSUE TITLE
Robot Arm (IV tier) not craftable in Precision Assembler (Good generator mod)

### ISSUE THREAD

**Issue by Eranicus** [GTNewHorizons/GT-New-Horizons-Modpack#10443]
### Your GTNH Discord Username

Eranicus#5476

### Your Pack Version

2.1.2.4-5-dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

For it to craft.

### The Reality

Robot Arm (IV tier) not craftable in Precision Assembler, tryed with every possible IV circuit type without any luck, not sure whats wrong since LV/MV/HV/EV are perfectly craftable.

inserted recipe into gt++ assembler and it worked fine.

(got latest good gen from jenkins) 

### Your Proposal

Fix please.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
check the machine casing you are using in precious assembler, it limits the highest voltage it can accept. also notice that you need 4 ev hatches to run the iv recipe.

**Comment by Eranicus** [comment]
MK-3 casings and normal UV energy hatch

**Comment by GlodBlock** [comment]
no i mean the casing at the button, are they iv machine casing or higher tier?

**Comment by Eranicus** [comment]
At the bottom i have UHV machine casings. ( I use this awesome assembler for several months already )

funny did a test with IV components (motor/pump/piston/conveyor) are craftable but (robot arm/sensor/emitter) are not ...

in gt++ assembler arm/sensor/emitter are working fine.

**Comment by chochem** [comment]
Might just be the circuit ore dict problem again. check the other ticket/try the latest gregtech from Jenkins/ the 4-dev one. 5-dev build has lots of these recipe problems.

**Comment by Eranicus** [comment]
> Might just be the circuit ore dict problem again. check the other ticket/try the latest gregtech from Jenkins/ the 4-dev one. 5-dev build has lots of these recipe problems.

I will test with latest gregtech  now , but looks like its not oredict, because they are all perfectly craftable in gt++ assembler.

**Comment by miozune** [comment]
GT++ is doing something special iirc, how about GT single assembler?

**Comment by Eranicus** [comment]
> GT++ is doing something special iirc, how about GT single assembler?

just updated gregtech from the link you posted before for origin/dev and it looks like it is fixed now for precision assembler at least all the recipes I tested before are working now...

**Comment by GlodBlock** [comment]
gt++ writes its own recipe checker. now it seems fixed at gt side, is it ok to close this issue?

**Comment by Eranicus** [comment]
yes will close now, thank you
