### ISSUE TITLE
Clay Dupe

### ISSUE THREAD

**Issue by xSkewer** [GTNewHorizons/GT-New-Horizons-Modpack#10446]
### Your GTNH Discord Username

xSkewer#4113

### Your Pack Version

2.1.2.4 dev5 (updated GT++ and GT5)

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Expected clay blocks to not be able to generate infinite clay.

### The Reality

![image](https://user-images.githubusercontent.com/43712386/172220885-d2fb6e68-ad13-49eb-921b-d9646bc54bec.png)
![image](https://user-images.githubusercontent.com/43712386/172220917-301f0319-252a-4a75-a0ca-6e31f55e2f89.png)
![image](https://user-images.githubusercontent.com/43712386/172220942-cf1cb4d0-6723-434b-89ac-a5cee77ad249.png)
![image](https://user-images.githubusercontent.com/43712386/172221792-217bfb0b-c063-4e13-9441-e15025a894f4.png)
![image](https://user-images.githubusercontent.com/43712386/172222090-9b2e4d82-a0d8-4dc9-94a1-9b517179a521.png)

Net result is 4.5 clay blocks from 1

### Your Proposal

Change the cutting machine recipe to give 4 plates instead of 9 and make the mixer recipe require 1 clay dust.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
2 plates, since clay macerate into 2 dusts.

**Comment by Tralomine** [comment]
this is not very balanced

**Comment by chochem** [comment]
this is actually worse. there are other ways to loop this too. e.g. with clay pipes. No wonder nobody has been willing to tackle this.

**Comment by chochem** [comment]
after some discussion on github (https://discord.com/channels/181078474394566657/401118216228831252/1008734077244948510), including input from dream, the ratios should be:
1 clay block = 4 clay ball (just basic stuff)
1 clay ball = 2 small clay dust (but can be 1 small dust in early game maceration)
1 clay dust = 1 clay plate (like stone!)

The main reason being that the early game like BBFs is balanced around 1 clay ball = 2 small clay dust and that this is the main ratio used in GT5u.

that means:
- the cutting recipe should go.
- plates should be obtained by compression. that is already the case but it should be from normal dust too, not just 4x small dust.
- a small pipe is always equivalent to a plate, so pipe extruder recipes need adjusting
