### ISSUE TITLE
Gregtech Log Spam "rewrite Assline recipes" 

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#10459]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.4.dev-5

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The lines 
```
In rewriteAsslineRecipes Pt. 2!
In rewriteAsslineRecipes!
```

are spammed to gregtech.log.

### The Reality

Maybe some debug feature that needs to be turned off?

### Your Proposal

Turn off before release of stable version

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNHAfx237v7** [comment]
Will be closed by https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/25
