### ISSUE TITLE
Change LSC quest capacitor casings required

### ISSUE THREAD

**Issue by realthecaffiend** [GTNewHorizons/GT-New-Horizons-Modpack#10458]
### Your GTNH Discord Username

thecaffiend#2253 

### Your Pack Version

2.1.2.3qf  (Some config changes, no recipe changes)

### Your Proposal

LSC quest in multiblock goals, "The Third Time's the Charm"/2732, requires 46 lapotronic super capacitor casings. Other multiblock quests require the actual minimum amounts of items for the multiblock (17, in this case). 17 is only useful if trying to build the very minimal LSC, but with many people in the discord seeming to use multiple in and outs, 46 is likely too high. Maybe require the 17 and mention you will likely want (not need) more, or something more like 20? 

The quest also requires 4 empty lapotronic capacitors (A great hint that up to just under half can be empties) but, requires lapotronic energy orbs to unlock the quest, and demands only lapotron capacitor (EV), not IV, It would be good to make it accept both, or possibly change the requirements since there is never an orb used in the basic construction. 

Also, the quest and tooltip should be updated as it forms just fine at 32 borosilicate glass (I have no idea where 41 comes from)

### Your Goal

The quest should more closely reflect reality, instead of people making a bunch of blocks that are destined to be thrown out. 

### Your Vision

The quest book is an amazing work and I'd like to see that continued consistently 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
also the quest description is outdated at five points:

1) doesnt hold less power than PSS
2) first list point 6, PSS can do laser hatches too, so not a difference
3) second list point 2  'stores less power' again no longer a thing/downside
4) second list point 5 same.
5) EV size is no longer 90M to 1.35B but 540M to 8.1B now
