### ISSUE TITLE
Make the creative mana tablet craftable

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#10456]
### Your GTNH Discord Username

Maniifestantes

### Your Pack Version

2.1.4.4 zeta

### Your Proposal

The infinite mana tablet is currently uncraftable 

### Your Goal

using the tools like terra shatterer is pretty mana intensive

### Your Vision

So an infinite source of mana is pretty much needed (considering the infinite pool already exists)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by combusterf** [comment]
https://github.com/GTNewHorizons/Botanic-horizons/pull/11
