### ISSUE TITLE
Silicon boules circuit numbers aer weird

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#10468]
### Your GTNH Discord Username

repolainen#0483

### Your Pack Version

Update 2.1.2.4-zeta

### Your Proposal

Silicon boules EBF recipes use circuits numbers 2,3,4,5,6 - that makes no sense.  You cannot even (simply) automate putting the circuits in the input bus depending on the recipe, because they mosly use 3 igredients.
To remove conflicts it would be quite enough to use circuit #2 for the first boule (2 ingredients) and circuit #3 for the rest.

### Your Goal

-

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
i merged it and take it in the si branch later
