### ISSUE TITLE
change lightning rods' recipes and output to correct

### ISSUE THREAD

**Issue by InTheBackOf** [GTNewHorizons/GT-New-Horizons-Modpack#10462]
### Your Pack Version

2.1.2.3qf

### Your Proposal

Tier 1 Lighting Rod can make 13A IV arrange power in trunder weather. But it's almost free for change weather to trunder like Weather Obelisk from Ender IO. And the higher tier Lighting Rods are useless because too expencive and output less extra EU. (T1 can make 13A IV arrange but T2 only can make 19A IV ,T3 can make 23A IV but needs Ultimate Battery)

### Your Goal

Nerf low Tier Lightning Rod and buff high Tier Lightning Rod.
For T1 lightning rod , it has 13,500,000 eu's capacity(= 4A IV arrange) and need Euporium to craft it.
For T2 lightning rod , it has 50,000,000 eu's capacity(= 19A IV) and need any UV-Tier circuit and Assline to craft it.
For T3 lightning rod , it has 150,000,000 eu's capacity(= 61A IV) and need any UHV-Tier circuit and ZPM-Tier Lapotron to craft it.

### Your Vision

Make some good generator ideas instead of free eu generator

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Hikari1nVoid** [comment]
Balance should depend on output cuz A lightning always have the same power.
Lightning Rod I :256A@128V
Lightning Rod II:256A@512V
And did anyone really craft Lightning Rod III??It should be cheaper then we can talk about its output.

**Comment by Ethryan** [comment]
Perhaps turning it to a multiblock and making it **constantly** use Crushed Ice fluid in a input hatch as coolant for the insane amout of power that will travel through the tower, And then outputing some kind of steam while sending out the power, that way you vae to build some kind of infrastructure to keep it working.

**Comment by Hikari1nVoid** [comment]
Another path is to change the recipe for EIO weather obliesk as it is the key to generate the infinite thunderstorm weather.
Also there's a bug on weather changing feature and it sounds like a forge related.So I wonder if it is possible to build a GT MLB to change weather,Tiered UV.(Also remove recipe for EIO weather obliesk.)
