### ISSUE TITLE
The Lack of Potassium alternatives

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/GT-New-Horizons-Modpack#10473]
### Your GTNH Discord Username

popyy xabe#4042

### Your Pack Version

whichever eta is running

### Your Proposal

Bananas cannot be used to produce potassium, when we clearly should be able to farm bananas to produce a potassium farm

### Your Goal

Bananas are a source of potassium, realistically speaking, if we want a realistic pack experience we'll need to add bananas->potassium processing

### Your Vision

Adding more realistic  sources of potassium will help out the pack's realism

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Waisse** [comment]
https://chemistrytalk.org/potassium-metal-banana-extraction/

**Comment by PoptartOverlord-Xabedo** [comment]
adding to that I suggest we should differentiate between the types of bananas, where forestry  yellow banana gives an ample amount of potassium, while red bananas are literally just yellow bananas with red dye!

also pam's harvestcraft bananas should produce nothing but sugar, because thats what pam's eats

**Comment by Dream-Master** [comment]
@PoptartOverlord-Xabedo if we add this we use the way @Waisse describe in the link :)

**Comment by Dream-Master** [comment]
so a long chain of chemical processes get potassium i guess

**Comment by Waisse** [comment]
Banana fuel.

**Comment by Dream-Master** [comment]
And at the end throw the potassium back to water and have a massive Explosion.
