### ISSUE TITLE
Rebalance recipes for YOTT Fluid Tank

### ISSUE THREAD

**Issue by Milesman34** [GTNewHorizons/GT-New-Horizons-Modpack#10476]
### Your GTNH Discord Username

milesman34#2076

### Your Pack Version

2.1.2.4.5-dev-pre-test

### Your Proposal

Change the recipes for YOTT Fluid Cell Blocks to be far less gated and expensive. Why should they need hundreds of Quantum Tanks and other insanely expensive components to craft? Additionally, the T6 Fluid Storage Core should have a recipe that isn't 64 of the T5 Fluid Storage Core, and all the recipes that just use 64 of the previous tier should be removed. I don't understand how this recipe made it to any sort of beta release.

### Your Goal

I can't see how the YOTT Tank is supposed to be remotely viable at the higher tiers given the same cost. The higher tier YOTT Fluid Cell blocks have terrible recipes. For instance, the T6 Fluid Cell needs 10 T6 Fluid Storage Cores. These cannot be crafted directly, unlike the other tiers, so each one needs 64 T5 Fluid Storage Cores. Each of these require 32 Quantum Tank IV's. This results in T6 Fluid Cell blocks needing _**20480**_ Quantum Tank IV's _**each**_. This is not a reasonable recipe for a *fluid tank*. Why should the player spend millions of resources on a fluid tank?

### Your Vision

It would make the YOTT Tank actually viable for endgame, even though storing quadrillions of L of fluids is overkill, at least the cost of such wouldn't be incredibly stupid. If you want to make the max size T6 multiblock (which I think would be 135 Fluid Cells), the cost is comparable to Stargate in terms of neutronium (40 million+ for the 135 fluid cells, 65 million+ for a Stargate).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by greesyB** [comment]
I like the idea of YOTT Tank being expensive, but agree it's overdone right now. Would be nice if all current recipes were tiered down and a couple more tiers got recipes since cells exist up to T10 but currently T6 is the highest craftable.

**Comment by Milesman34** [comment]
> I like the idea of YOTT Tank being expensive, but agree it's overdone right now. Would be nice if all current recipes were tiered down and a couple more tiers got recipes since cells exist up to T10 but currently T6 is the highest craftable.

Ideally the new recipes wouldn't be so nested. It is better to use a few more expensive components (say, the GT pumps) instead of hundreds of less expensive components (lower tier quantum tanks). Could also include the Fluid Storage Components or something?

**Comment by Eranicus** [comment]
I just checked T5 and T6 fluid cells,  I dont like T6 because its recursive from T5 cores.

As for T5 fluid cell, its 10 cores (32 quantum IV each) = 320 q. IV in total. Sounds good considering the quantity it can hold. The question is why do you need such a big storage ? but if you need it , the crafting for T5 is perfectly fine in my opinion.

**Comment by greesyB** [comment]
I think it's less about the need for such big storage and more about wanting a native fluid storage option that can compete with super chests of bedrockium drums in terms of being practically infinite.

**Comment by Connor-Colenso** [comment]
> I think it's less about the need for such big storage and more about wanting a native fluid storage option that can compete with super chests of bedrockium drums in terms of being practically infinite.

Yea and it's not even just cost, yotta tanks are quite bulky. I can store virtually infinite fluid in a few blocks with bedrockium drums + super chests, I cannot do the same with a yotta tank even if the costs were reasonable.

What a lot of endgame players really want is just a compact tank that can store a maximum of long max rather than int max.
