### ISSUE TITLE
Add tool to copy paste AE part config

### ISSUE THREAD

**Issue by ordpus** [GTNewHorizons/GT-New-Horizons-Modpack#10479]
### Your Pack Version

2.1.2.3qf

### Your Proposal

We should have a tool that allows us to copy-paste config between ae parts, for example, export and import buses. This tool should also have a copy pattern mode for ME interface, and can be switched between override/append mode.

### Your Goal

Because it is annoying if I want to move ae parts to a different place as i need to re-select the items in the filter, and re-insert the patterns.

### Your Vision

It will make the update of ae logistics network more convenient 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
Memory card exists
