### ISSUE TITLE
Salt dupe in 2.1.2.4-5

### ISSUE THREAD

**Issue by S4mpsa** [GTNewHorizons/GT-New-Horizons-Modpack#10477]
### Your GTNH Discord Username

Sampsa#2464

### Your Pack Version

2.1.2.4-5

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

Creating 1000L of salt water requires a single salt dust, but distilling 1000L of salt water gives back two salt dusts.

Either it should require two salt to make 1000L of salt dust, or 1000L of salt water to distill into one dust.

![image](https://user-images.githubusercontent.com/69092953/173214598-0c00d9c1-52d0-4c01-bfc6-05b0e9d69fe5.png)

### The Reality

Two salt is gained from using a single salt dust, producing infinite salt.

### Your Proposal

Change the saltwater distillery recipe to use 1000L instead of 500L.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
probably caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/983/commits/dc097373463a1f751bcd9765f0845b6a78a28278

**Comment by Dream-Master** [comment]
i exclude this pr in the next release

**Comment by Dream-Master** [comment]
seems to be fixed. I exlude the chemical rebalance pr

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/174157868-fd5c1dea-de50-4b89-a400-1a0e0350cee7.png)
