### ISSUE TITLE
Kinetic Rotors Reset Durability On Relog

### ISSUE THREAD

**Issue by xSkewer** [GTNewHorizons/GT-New-Horizons-Modpack#10471]
### Your GTNH Discord Username

xSkewer#4113

### Your Pack Version

2.1.2.4-dev5 w/ updated GT5 and GT++

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expected a non-iridium kinetic rotor to stay damaged when I relog.

### The Reality

The rotor returns to 100% durability every time I relog. As far as I can tell, this isn't just visual and the rotor will last forever if I keep relogging.

### Your Proposal

Fix the bug and maybe increase the durability of non-iridium rotors to compensate. I'm not sure how long they last without the bug but it seems like vibrant alloy rotors will last about 24h before breaking from some quick testing.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by s9hysky** [comment]
In 2124-pre18 it will also return to 100% durability
