### ISSUE TITLE
Fix tier progression on GT++ single-block advanced boilers

### ISSUE THREAD

**Issue by Shadowsoftime99** [GTNewHorizons/GT-New-Horizons-Modpack#10483]
### Your GTNH Discord Username

Shadows#4865

### Your Pack Version

2.1.2.1

### Your Proposal

At the moment, the MV and HV ones of these use the tier above's metal, and ~40 ingots of it per boiler too.

Example of the HV chassis component, using Titanium: 
![image](https://user-images.githubusercontent.com/16748195/173417963-3a21a9e4-96b5-46e5-b532-5d90c55805f2.png)

I feel this should be dropped down to use the current tier's metal instead (Alu for MV, Stainless for HV), keeping them in line with the LV one and making them remotely craftable at a reasonable time.

### Your Goal

Really, just consistency.

These things aren't good, and honestly they still wouldn't be even after this. Their output scales at only 2x (LV -> MV) or 1.5x (MV -> HV) as you go up in tiers. And that's not even including the turbines' efficiency drops as you rise in tiers which are similar but steeper than combustion gens and other similar single-block sources.They'd still fall off hard even without needing tier-above, and that's fine. You're clearly not meant to be using this stuff, but at least if they used the proper tier metals they'd fit in more correctly with their named tiers and be maybe worth crafting for some people.

### Your Vision

I'm just a big proponent of the consistency, and maybe this would make single-block steam not fall off a scaling cliff as hard as it does. At the very least maybe it'd be worth crafting MV+ boilers instead of just spamming out more LV ones? Especially because unlike a generator, this doesn't output "LV tier steam". Steam is steam, so there's literally no reason to upgrade past the LV ones right now and it's in fact just a downgrade.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
The problem is there is still no mv pipe. Steel is mid steam age, stailess is late mv and titanium is beginning ev. @Shadowsoftime99 what is your suggestions?

**Comment by Shadowsoftime99** [comment]
hm, I see now that all the pipes match the plates for the "40 of" material. It's weird because we don't have aluminium pipes to match. Maybe Dark steel? I think that's around MV level, and it would let all three require "X Steel" as their material.

Yeah Steel is accessible during steam, but it's LV's "tier metal" so I think it fits fine. Same with Stainless for HV.
