### ISSUE TITLE
Bibliocraft painitng canvas does not have recipe

### ISSUE THREAD

**Issue by Ydrec** [GTNewHorizons/GT-New-Horizons-Modpack#10482]
### Your GTNH Discord Username

@ydrec#7877

### Your Pack Version

2.1.2.1

### Your Server

SP

### Your Expectation

Bibliocraft painitng canvas is used to make paintings (pre made images applied to it with painting press) as well as to make openblocks canvas block. 

### The Reality

But itself painting canvas does not have any recipe. As well checked scripts currently in gtnh repository, and didn't find any mention of its recipe (as well as whole bibliocraft scripts file missing for some reason)

### Your Proposal

Add a recipe to it, like this basic one

`
// --- PaintingCanvas
recipes.remove(<BiblioCraft:item.PaintingCanvas>);

// --- PaintingCanvas
recipes.addShaped(<BiblioCraft:item.PaintingCanvas>, [
[<ore:platePaper>, <ore:platePaper>, <ore:platePaper>],
[<ore:platePaper>, <ore:platePaper>, <ore:platePaper>],
[<ore:platePaper>, <ore:platePaper>, <ore:platePaper>]]);`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
have you checked in latest dev? I moved all the bibliocraft recipes in code long time ago, but i remember doing some mistake first time i did it.

**Comment by Ydrec** [comment]
Yep, exists, assumed it was minor thing noone noticed when making recipes, my mistake
