### ISSUE TITLE
Forestry Swarmer replacing IC2 crops

### ISSUE THREAD

**Issue by arbitrarystar** [GTNewHorizons/GT-New-Horizons-Modpack#10486]
### Your GTNH Discord Username

dxzfvzs#1259

### Your Pack Version

2.1.2.3.qf

### Your Server

Private server

### Your Expectation

When using a swarmer block in an alveary; expecting SwarmHives to spawn in reasonable distance on viable blocks around the alveary.

### The Reality

The Swarm Hive spawned exactly 66 blocks away and in place of a full grown IC2 crop. 

### Your Proposal

Adding a check that would not allow the hive to be spawned instead of ic2 crop and possibly other plants / structures. Relevant code might be in [here](https://github.com/GTNewHorizons/ForestryMC/blob/06baad945a4354387128325f8cb03cabfc2bd406/src/main/java/forestry/apiculture/worldgen/HiveGen.java#L27)

Also suggesting to lower the spawn distance, at least a little.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DianeXD** [comment]
Idk, it's by design, not sure if it needs to be fixed
