### ISSUE TITLE
Tree Growth Simulator stays off permanently once Output Hatch is full

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10489]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Your Expectation

The Tree Growth Simulator will correctly realise when the Output Hatch is full, and it should correctly start processing once enough room is in the Output Bus for additional items.

### The Reality

The Tree Growth Simulator will correctly realise when the Output Hatch is full; however, it will fail to re-engage once there is sufficient room for new output, meaning that the multiblock has to be constantly stop-started.

### Your Proposal

Rather than fully shut down, have the multiblock scan the Output Bus, and if there is enough space for new items, proceed to a new operation.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
That is almost the opposite as to how it works for me lol. Mine just always voids excess independent of setting or anything.

cf. https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10451

**Comment by miozune** [comment]
Should be fixed by one of those patches
