### ISSUE TITLE
Add fluid sodium formate SB chem reactors

### ISSUE THREAD

**Issue by realthecaffiend** [GTNewHorizons/GT-New-Horizons-Modpack#10487]
### Your GTNH Discord Username

thecaffiend#2253 

### Your Pack Version

2.1.2.3qf  (Some config changes, no recipe changes)

### Your Proposal

I'm doing the platline setup and working on formic acid; This is a fairly sensible recipe, with two fluids in and a fluid/item out, you can chose to use the LCR or a single block: Obviously, either one needs cells and thus handling of them or go LCR.

Sodium formate, for some reason, cannot be produced in an SB chem reactor in fluid form, and the input CO cannot be in anything other than cell form. This is a very standard fluid + item chem reactor recipe which generally would have options for direct fluids in/out of a SB reactor, and the lack of that feels like a simple oversight. 

### Your Goal

Greater consistency in chem reactor recipes (And not dedicating an entire LCR to a very trivial recipe to avoid cells)

### Your Vision

Removing cell handling from the ~~entire pack~~ unreasonable recipes 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
it is possible to add fluid recipes to single block chem reactor if you have only 2 fluids and an item/dust.
