### ISSUE TITLE
Unable to fall on Jupiter space station

### ISSUE THREAD

**Issue by mudspaw** [GTNewHorizons/GT-New-Horizons-Modpack#10499]
### Your GTNH Discord Username

mudspaw#9583

### Your Pack Version

2.1.2.4-dev-5

### Your Server

Private Server

### Your Expectation

Attempted to fall to the ground of my station after constructing my Jupiter space station to place a Planetary Gas Siphon.

### The Reality

There is no gravity on the station for some reason. Jetpacks don't help. Any height you gain is permanent, and I had to enter creative mode just to land on the station.

### Your Proposal

Add low gravity to space stations.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
Did you try "SpaceSuit Gravity Boots"?

**Comment by mudspaw** [comment]
I did not, but I also didn't know those were a thing. If the newer stations required these boots, I think the quest should say so or mention it but personally I would still disagree that they should be required. The overworld space station has a small amount of gravity, which is what I was expecting.

**Comment by glowredman** [comment]
I'm going to rework the gravity stuff a bit anyways, since GS is using "looks like straight up copied code but of an old version"
