### ISSUE TITLE
stackoverflow error due to cooking for blockhead

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10493]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.4-zeta

### Your Server

Zeta

### Type of Server

Thermos

### Your Actions

.

### Crash Report

[crash-2022-06-15_17.31.37-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8910893/crash-2022-06-15_17.31.37-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
Should switch to an iterative algorithm instead of recursive, and then add a limit to how far it'll look.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
