### ISSUE TITLE
Flourine Field generation might be too high

### ISSUE THREAD

**Issue by ChrisLua** [GTNewHorizons/GT-New-Horizons-Modpack#10495]
### Your GTNH Discord Username

ChrisLua

### Your Pack Version

2.1.2.3qf

### Your Server

private dedicated server with friends

### Your Expectation

The quest says there should be Fluorine Fields on Pluto ranging von 4-800

### The Reality

I am finding a lot fields above 3000. Some ranging close to 4000.

### Your Proposal

chochom told me that it might be a bug. so i'm reporting :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
cfg :
        fluorine {
            # Chance generating (weighted chance!, there will be a fluid in chunk always!)
            I:Chance=80

            # Decrease per operation (actual fluid gained works like (Litre)VeinData/5000)
            I:DecreasePerOperationAmount=5

            # Max amount generation (per operation, sets the VeinData) 80000 MAX
            I:MaxAmount=800

            # Min amount generation (per operation, sets the VeinData) 0 MIN
            I:MinAmount=4

            # Fluid registry name
            S:Registry=fluorine
        }

**Comment by greesyB** [comment]
> cfg :
> 
> ```
>         fluorine {
>             # Chance generating (weighted chance!, there will be a fluid in chunk always!)
>             I:Chance=80
> 
>             # Decrease per operation (actual fluid gained works like (Litre)VeinData/5000)
>             I:DecreasePerOperationAmount=5
> 
>             # Max amount generation (per operation, sets the VeinData) 80000 MAX
>             I:MaxAmount=800
> 
>             # Min amount generation (per operation, sets the VeinData) 0 MIN
>             I:MinAmount=4
> 
>             # Fluid registry name
>             S:Registry=fluorine
>         }
> ```

There must be a bug then. These chunks were generated on .2.3qf with the same config:
![image](https://user-images.githubusercontent.com/73182109/174158879-60882903-76b0-4b1c-bd8e-63bff7acc477.png)

**Comment by Dream-Master** [comment]
if the amount is wrong maybe other fluids are wrong as well

**Comment by ChromicRedBrick** [comment]
After some investigation I found that if the min amount of underground fluid is set to larger than 0, the max amount generated in the game will be several times the set max amount value.

There are 3 underground fluids with min amount set to >0: Fluorine in Pluto (4-800), Liquid Air in Pluto (4-300) and Liquid Air in Callisto (2-200).

All of them have a much higher generation amount than config in the game.

Callisto:
![Callisto-LiquidAir](https://user-images.githubusercontent.com/85604068/192462526-65372286-4c6f-43a1-86bd-863bee8c929a.png)

Pluto:
![Pluto](https://user-images.githubusercontent.com/85604068/192462536-721bd34a-0cec-4447-a10d-11eafe0a5d5c.png)

**Comment by ChromicRedBrick** [comment]
There's an issue about this weird generation
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6387

**Comment by chochem** [comment]
oh wow thanks for finding that issue. I completely forgot about all of that (and was not a dev back then). That really shouldn't have been closed.

So the problem is the incredibly stupid maths in https://github.com/GTNewHorizons/GT5-Unofficial/blob/697925c533c870f5f5b18d4b59287d9557d2de27/src/main/java/gregtech/api/objects/GT_UO_Fluid.java#L54
