### ISSUE TITLE
Incorrect crafting result of structure block of vaccum freezer.

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/GT-New-Horizons-Modpack#10494]
### Your Pack Version

2123QF

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Normally get a vaccum freezer block with aluminum frame and 6 aluminum panels.

### The Reality

Vaccum freezer block was crafted as result at first but instantly turned into 2 Reinforced Aluminum Blocks of GT++
I found a dupe crafting recipe for vaccum freezer block and reinforced aluminum block, which has same exactly materials to craft but produced different results.
https://user-images.githubusercontent.com/57739338/173891150-d786bbd7-bb1e-4d94-aa12-69f26a864479.mp4

### Your Proposal

As the video showed, this bug made me impossible to build a vaccum freezer.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/205
