### ISSUE TITLE
The quest explaining the way of obtaining Xenoxene Xenoxsis is unnecessarily gated

### ISSUE THREAD

**Issue by alexandre-tardif** [GTNewHorizons/GT-New-Horizons-Modpack#10500]
### Your GTNH Discord Username

AlexandreTardif#5582

### Your Pack Version

2.1.2.3qf

### Your Proposal

The way of obtaining Xenoxene Xenoxsis used to make Xenoxene, which is now used in optical SMDs, is hidden. It is currently explained in the Radox Polymer quest, which is gated behind a relatively useless quest to make general purpose bacteria. I suggest moving that explanation to a quest for optical SMDs which could be before the quest for Nano/Pico/Quantum circuits in Endgame goals or in UHV since they can be used for Bio Circuits

### Your Goal

It would make the way to obtain Xenoxene clearer

### Your Vision

Optical SMDs wouldn't look uncraftable since right now it looks uncraftable from NEI

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
yeah we talked about this a bit on discord:

I think 2 UHV quests would be good. Probably located behind 'Industrial Scale Seaweed Production'.

The first for Xenoxene (basically the current radox quest except for the radox) which then leads to a new oSMD quest. The xenoxene quest should either have the general purpose bacteria as requirement or reference it at least as there are more explanations there.

The radox quest in the endgame goals can then be reduced a good bit and use the xenoxene quest and welcome to hell as requirements.
