### ISSUE TITLE
Air filter small turbine durability

### ISSUE THREAD

**Issue by XxYeetusMinecraftxX** [GTNewHorizons/GT-New-Horizons-Modpack#10508]
### Your GTNH Discord Username

Xx_YeetusMinecraft_xX#7455

### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

I believe that the air filter multiblock's small turbine durability should be decreasing over time.

### The Reality

It's been running for quite some time now and the stainless steel turbine is still at full durability

### Your Proposal

If not intended, make the small turbine's in the electric air filter multiblock durability decrease over time

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
I also wonder if this is intentional.

**Comment by boubou19** [comment]
yeah known bug since i never was able to identify why the durability wasn't going down
