### ISSUE TITLE
Ztones Aurora crafting

### ISSUE THREAD

**Issue by XxYeetusMinecraftxX** [GTNewHorizons/GT-New-Horizons-Modpack#10506]
### Your GTNH Discord Username

Xx_YeetusMinecraft_xX#7455

### Your Pack Version

2.1.2.3qf

### Your Proposal

Make Ztones Aurora craftable using non-vanilla dyes

### Your Goal

It's annoying and doesn't make sense

### Your Vision

It would just make more sense

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by QuantumBlink1337** [comment]
This bug still exists in version 2.5.1 of the pack

**Comment by Ethryan** [comment]
It was literally merged yesterday, [#796](https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/796).
Give it enough time for a dev version to be released.

**Comment by QuantumBlink1337** [comment]
> It was literally merged yesterday, [#796](https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/796).
> Give it enough time for a dev version to be released.

This isn't the same bug though. I fixed the assembler Ztones but not necessarily the recipe. I can fix that as well and I tried to reopen the issue to reference it in a PR.
