### ISSUE TITLE
Reactor Processing Unit and Cold Trap Bugged Inventory Slots (GT++)

### ISSUE THREAD

**Issue by Josh5minus1** [GTNewHorizons/GT-New-Horizons-Modpack#10505]
### Your GTNH Discord Username

A1#8299

### Your Pack Version

2.1.2.4-5 dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Since both of these machines are useful for the LFTR line, the recipes are able to use most of the slots of these machines. So I expected all the slots to be working.

### The Reality

There are only 1 input and 1 output slots for both of these machines, despite GUI showing that there are 2 input slots and 9 output slots, resulting for both RPU and CT unusable. I also tried putting other items required for recipe via automation, also no luck.

### Your Proposal

Make all slots in RPU and CT usable as the recipes require most of the slots as expected.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Steelux8** [comment]
I've already told Alkalus about this, but she has so far been too busy to help out with bugfixing. I'll try to get it fixed myself.
