### ISSUE TITLE
Change Wood Tar DT Recipe Voltage

### ISSUE THREAD

**Issue by henrydukepickle** [GTNewHorizons/GT-New-Horizons-Modpack#10519]
### Your GTNH Discord Username

henryduke#0140

### Your Pack Version

2.1.2.4-5

### Your Proposal

The DT recipe for wood tar should be reduced to 240 eu/t.

### Your Goal

Obviously, this voltage is derived from the singleblock recipe. While that works fine for the singleblock, because singleblock distilleries only ever accept 1 amp, it causes issues when extrapolated to the multiblock. For instance, if you want to power the recipe with one MV hatch, you would need 2 MV generators. However, since the amount is *exactly* the amount required, no loss can be incurred. Thus, you need a single superconductor, just because the voltage value on this recipe is poorly thought out.

### Your Vision

Wood Tar DT setups (for benzene) would function like other setups.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [x] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
first of all, for context: the recipe currently takes 256eu/t

Are you saying you are able to run the recipe with a single MV hatch? I thought that shouldn't be possible, as it should only be able to do recipes up to 128eu/t. That would mean you actually stumbled upon a bug. I never had such a bug happen for me, my DTs work fine. Can you give instructions to reproduce it?


Sounds like quite an annoying bug because it means you cant just power it off one HV hatch+gen as it would probably try to OC. Or does that work fine again?

**Comment by chochem** [comment]
nope, I have tried (one MV hatch, 2 gens, 1 SC cable), cant reproduce it.

**Comment by chochem** [comment]
> Huh. I must've misunderstood how hatches work. I thought that they could handle 2A each, as evidenced by the fact that 2 MV hatches on an EBF can run 480 eu/t recipes (480 > 128 * 2), is it to do with the fact that things change when only 1 hatch is present?

oh, so you didnt experience it, this was just theory? And yes, 1 hatch is different.

> I mean, if that's the case, I would just ask to change it to 120 eu/t or 480 eu/t - those work better with hatches. I imagine the recipe was just procedurally created, because most DT recipes seem to be 4x the voltage of the singleblock.

there are many recipes that dont need a full amp, that is normal.

I guess this can be close then?

**Comment by henrydukepickle** [comment]
Well, it might be normal but it is annoying. That's interesting about hatches though, thanks for the info. Yes, this can be closed.
