### ISSUE TITLE
Small mistake in gallium arsenide quest (LV, 836)

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10517]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4 5-dev-pre-test

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

-

### The Reality

Quests says:

![image](https://user-images.githubusercontent.com/40274384/174670874-f82ea5ad-82a9-47ef-8549-c25b38c8d673.png)

But in reality MV is not needed, just an EBF. This makes a difference as arsenic is needed just then, in late LV.

### Your Proposal

replace 'but that requires MV Voltage' by 'but that requires an EBF'.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
in addition of that, you must have an EBF anyways as the quest still mentions the mixer but the recipes changed:
![image](https://user-images.githubusercontent.com/12850933/177044240-b004b326-719d-45eb-a892-e9996d6969c7.png)
then you have to pulverize it:
![image](https://user-images.githubusercontent.com/12850933/177044262-ea4b25ee-25cc-4391-9df6-222292ef6285.png)

**Comment by chochem** [comment]
@boubou19 well there is an open ticket about the mixer recipe which should maybe be resolved one way or the other first #10350

Overall none of the new silicon changes are in the questbook at the moment, see #10347

The quests are a bit on hold until dream finishes the work on silicon stuff (also aluminum is similar). There is also plenty of open tickets that probably need to be resolved before somebody writes the quests: #10356, #10577, #10399, #10331, #10350
