### ISSUE TITLE
Adjust Hydrogen Gas Siphons on Jupiter to not generate ridiculous power

### ISSUE THREAD

**Issue by xSkewer** [GTNewHorizons/GT-New-Horizons-Modpack#10525]
### Your GTNH Discord Username

xSkewer#4113

### Your Pack Version

2.1.2.4-5 w/ updated GT++ and GT5u

### Your Proposal

Hydrogen gas siphons on Jupiter should be adjusted to produce less hydrogen or use more power. Or nerf the fuel value of hydrogen/remove it as fuel entirely.

### Your Goal

Right now, Jupiter siphons make 15000L/s of hydrogen for 1024eu/t.
Hydrogen is burnable for 20eu/L.
At 100% fuel efficiency, a Jupiter siphon will make 15000eu/t worth of hydrogen while only eating 1024eu/t meaning a net positive of almost 14000eu/t.

When factoring in the efficiency bonuses of large gas turbines as well as how cheap, easy, and low maintenance hydrogen gas siphons are compared to other power sources, gas siphons on Jupiter are one of the most overpowered power sources in the game.

For example, with large trinium rotors in an XL Gas Turbine (before the nerf to 16x),
![image](https://user-images.githubusercontent.com/43712386/174941594-b815b7f4-4f7f-4c0b-ae1c-0c6bb7a2651a.png)
you would only need ~25 Jupiter gas siphons to maintain this. This requires no fuel input, no maintenance besides machine maintenance and adding in rotors, and has no risk of explosion.

### Your Vision

This would prevent every other non-fusion power source at LuV+ from becoming irrelevant.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by xSkewer** [comment]
Here is a setup (done in creative) using only 8 gas siphons producing more than enough hydrogen to keep a large ori XLGT running with 100% uptime for nearly 1A ZPM. You can even cut out a siphon and still have enough hydrogen.
![2022-06-22_00 38 44](https://user-images.githubusercontent.com/43712386/174945101-ac95eb02-9b2a-492a-975e-09d42eb8c1ea.png)

**Comment by realthecaffiend** [comment]
I'd prefer to see the siphons produce less/cost more (I mean you are hovering over a planet sucking up and somehow refining a gas....), nerfing hydrogen fuel value as a result of one machine feels a little odd
