### ISSUE TITLE
Wireless crafting terminal issue with crafting status and infinity booster card

### ISSUE THREAD

**Issue by GTNHAfx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#10523]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.4dev5

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Look up the status of an ongoing craft via wireless crafting terminal that has an infinity booster card. Expected to be able to see the status anywhere, even in different dimensions.

### The Reality

Looking up the crafting status via wireless crafting terminal just exits the GUI.
Turns out when you are within range of the wireless access point, it works just fine.
Therefore I assume that the functionality of viewing the crafting status UI via wireless crafting terminal ignores the presence of the infinity booster card.

### Your Proposal

One should be able to see the crafting status from anywhere once you have the infinity booster card.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
I have this too, clicking the crafting status just closes theverything 
![image](https://user-images.githubusercontent.com/57050655/176503605-512ccee7-75a7-4bc9-b15b-7e861952bacd.png)
