### ISSUE TITLE
Botania makes some mobs "shed" items this can be turned off in the config

### ISSUE THREAD

**Issue by BeepBeep20** [GTNewHorizons/GT-New-Horizons-Modpack#10536]
### Your GTNH Discord Username

BeepBeep2020

### Your Pack Version

2.1.2.3QF

### Your Proposal

Botania by default makes certain mobs "shed" items, in a similar way as a vanilla chicken lays an egg.  

Slimes slowly shed slime balls, Blaze = blaze powder, Skeletons = bones, Chickens = feathers, Villagers = emeralds, Squid = ink sacs, Ghast = ghast tears. Spider = string

### Your Goal

a) When Skeletons/spiders spawn in caves sometimes zombies will pick up the item they shed shed (string/bone).  As it's now holding an item that zombie won't despawn or count towards the mob cap. In a world played for a long time that could lead to a lot of zombies collecting in caves potentially causing lag.

b) It's a nuisance to walk around & constantly pick up feathers & ink sacs while exploring.

c) Some of the items are intended to be somewhat risky/difficult to get early game, mainly blaze powder/ghast tears.

### Your Vision

Most importantly reducing the amount of zombies collecting in caves, who've picked up a "shedded" item so they won't despawn or count towards the mob cap.

There are config options to turn each one of these off & I think all shedding should be turned off.

It would be a quick change to make: the Botania config file is very long but all the items can be found by searching for 'minecraft:'. In the default config all the shedded items are from vanilla MC mobs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
> this seems to be a fair change. However a small precision: since a while now, in the hodgepodge config, you can chose if yes or no the mobs holding an item can pickup items on the ground, preventing them from being not despawnable. it's the `preventPickupLoot` under the `tweak` section.

I like boubou's solution better, tbh I like the mob shedding mechanic, it's good for getting certain items
