### ISSUE TITLE
Parralel serch in NEI not work with gt ore map 

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/GT-New-Horizons-Modpack#10537]
### Your GTNH Discord Username

@dahgul#1726

### Your Pack Version

2.1.2.0

### Your Server

Eta

### Your Expectation

trying to search multiple orese onse 

### The Reality

https://cdn.discordapp.com/attachments/289850721988509696/989914179949441084/unknown.png
https://cdn.discordapp.com/attachments/434377208740708374/989910113932410940/unknown.png

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
can you try on latest pack please?
