### ISSUE TITLE
Make the condenser later game but keep the functionality

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#10549]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.3QF

### Your Proposal

With the condenser being fixed, it will not only be more expensive than cells, less useable than cells, and on top of that, won't be useable with AE.

As such, I propose that instead we push the recipe to UHV or such, as proposed by a few other peeps, since thaumcraft itself does not have any creative essentia generation (besides that one jar, but this one is better, and you can't make the jar) currently craftable in game.

### Your Goal

To keep the condenser relevant, because it is unparalleled in it's ability to save processing power, and by god we should keep it in because of it.

Thaumcraft doesn't have many good lategame essentia generation methods, you could even argue it doesn't have any at all, given that one might even have to resort to horrifically large planar vortex farms, as such I think it's worthy to leave the condenser in game with it's current functionality, but with the stipulation that its recipe is raised to a higher tier.

### Your Vision

Instead of making the condenser useless, we have the chance to consider it balanced for the sheer capability to save people's tps, and if that's not a worthy cause, I don't know what is.

The recipe should be UHV and gated with:

8 infinity large plates, 8 any UIV circuit, 2 shadowmetal caps, 2 shard(s) of creation, and a extremely primordial pearl center and 512 nebresium, 512 Terminius, 256 Praecantatio, 128 custom1, 128 custom2, 128 custom3, 128 custom4, 128 custom5, and 64 strontio

which would equate to: 24 primoridal pearls (extremely primordial pearl), 8 more primordial pearls, 3 nether cubes, 6 exquisite tanzinite, 96 shadowmetal, 57 void metal, 24 warped shards, 6 void metal caps, 24 infinity ingots, and 24 UIV circuits

and not to mention the ungodly amount of essentia correlated to this recipe, I think this would be more than balanced enough to keep functionality

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Runakai1** [comment]
I strongly agree with this. There should be either a good essentia generation or the functionality of the condenser should be maintained and uplifted to a higher tier. It's unreasonable to fix a mechanic when the outcome of said fix would be to incredibly lag the server. And it's not just a little bit of lag. To keep up with essentia you'd have to world accelerate a lot of tiles as well as have dozens of planar vortexes. 
We even consider mana in botania to be a problem due to no efficient calculation methods as well as no efficient way to generate mana in quantities that are needed. We should follow that spirit with thaumcraft and think about a fix of the condenser being more problematic than fixing anything.

**Comment by Alrightsc** [comment]
I am also for moving it towards late-game, somewhere in Creative/Avaritia range, or making it store infinite essentia (although the uncraftable creative essentia cell is probably better for this purpose).

**Comment by Aurastorm** [comment]
I also would suggest using the creative essentia cell as it's easier to implement into a base, etc.
Thaumcraft as a whole absolutely needs lategame essentia generation, however, as I think it's in the same camp as RF devices (with how the chaotic capacitor is craftable).

**Comment by Alastors** [comment]
I personally think we should continue to use the condenser myself, but that might just be me, no reason to give AE cells more power, plus the condenser looks better anyhow, but idk man

**Comment by Runakai1** [comment]
> I personally think we should continue to use the condenser myself, but that might just be me, no reason to give AE cells more power, plus the condenser looks better anyhow, but idk man

Exactly. We are already primary focusing on AE. Can't harm to have thaumcraft be the first and only option.

**Comment by Alastors** [comment]
> > I personally think we should continue to use the condenser myself, but that might just be me, no reason to give AE cells more power, plus the condenser looks better anyhow, but idk man
> 
> Exactly. We are already primary focusing on AE. Can't harm to have thaumcraft be the first and only option.

yeah my thoughts exactly, why solve thaumcraft problems with purely ae solutions, it's already half of the solution now.

**Comment by xSkewer** [comment]
The current proposed recipe from Alastor is:
8 infinity large plates, 8 any UIV circuit, 2 shadowmetal caps, 2 shard(s) of creation, and an akashic center and 512 nebresium, 512 Terminius, 256 Praecantatio, 128 custom1, 128 custom2, 128 custom3, 128 custom4, 128 custom5, and 64 strontio for all 3 condenser blocks. This is farther than UHV but this is to prevent people from abusing it with the LEG and getting easy power.

Here is my half-assed attempt at adding it ingame (will fix it if approved):
![image](https://user-images.githubusercontent.com/43712386/176071558-bfa45a62-cd7d-4946-9e45-9210580b2f5a.png)

If people want, the creative essentia cell can have a similarly expensive recipe.

**Comment by EnderProyects** [comment]
I think that the Element of Darkness and the Aura Core should be added to the recipe ( they are in the original one, and the Element of Darkness is also used to maximize the essentia storage then)

**Comment by repo-alt** [comment]
Maybe only maxed out condenser should act as infinite source? This will make use of elements of darkness and funny black hole mechanics

**Comment by boubou19** [comment]
oh yeah please do

**Comment by EnderProyects** [comment]
If that, the recipe for the element of darkness should be changed
