### ISSUE TITLE
make holoinventory display darken items like in NEI highlight mode

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10546]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0-pre4

### Your Proposal

Darken the items just like NEI does in highlight mode:
![image](https://user-images.githubusercontent.com/12850933/175767799-52021080-abec-490a-9ed5-c7b6b32292a5.png)

Might justify the creation of advanced hologlass items if it is too OP

### Your Goal

i'm fed up with opening the chests to use NEI highlight mode despite having a tool to see the content of the chests without opening them.

### Your Vision

This will remove a lot of tedium bound to item research pre AE.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
You mean, for Holoinventory to highlight the item filtered by the NEI search bar?

**Comment by boubou19** [comment]
either filter them by removing them from display or by turning them dark when they aren't matching what is specified in NEI
