### ISSUE TITLE
Thaumic iconographers packet too big 

### ISSUE THREAD

**Issue by XxYeetusMinecraftxX** [GTNewHorizons/GT-New-Horizons-Modpack#10542]
### Your GTNH Discord Username

Xx_YeetusMinecraft_xX#7455

### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Actions

I made a photo and wanted to successfully develop it in arcane crafting table

But this happened instead:
![image](https://user-images.githubusercontent.com/60048782/175699733-71041dd9-2da8-444d-8b51-e24b2f2bbc08.png)

No one could join anymore

NOTE: Apparently this only happens if you make a photo of a player

### Crash Report

Apparently the server is technically still running but no one can join anymore

Not sure if backup loading is needed (it most likely is) or just a restart. Not sure because the only guy that has the SSH keys is currently not able to access his PC

Decided to put it in the crash category as it definitely can be a very big problem and it's pretty much on the level of a crash if no one can join

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
