### ISSUE TITLE
Change portal reward in quest 'Final choice: personal dimension'. (IV, 217)

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10550]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4 5-dev-pre-test

### Your Proposal

utility worlds was replaced by a new mod, personal space. The portal reward needs to be updated accordingly.

### Your Goal

-

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Closed by #10553
