### ISSUE TITLE
Precise assembler broken in 2.1.2.4-14-pre

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10552]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-14-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

should work. And yes it has power, is in normal, is on. this is already confirmed by other people as well.

### The Reality

It doesnt work. Random items get eaten but nothing crafted. gregtech.log has many iterations of this:

![image](https://user-images.githubusercontent.com/40274384/175827485-680d9204-5b28-4905-a302-9494652dc36a.png)

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by xSkewer** [comment]
Likely caused by https://github.com/GTNewHorizons/bartworks/commit/320813cd561f0ba94c65f17f1840d64ba99d3042#diff-62a4469fb6db3dc39246b1ac2f122f1bfb07a16685203dac3450396fb8720877

**Comment by chochem** [comment]
we have been trying to get this to work but without success. might be the adhoc compilation? a release would clear that up at least. But please re-open for now.

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/175845519-c1c5401d-1336-41c7-8683-7fb1b10d9b4c.png)

this is the crash I get while starting the game.

**Comment by xSkewer** [comment]
Should mention that chochem is using a jar compiled by me. I get the same crash.

**Comment by Connor-Colenso** [comment]
Yea just tried it myself and same issue, gonna re-open.

**Comment by chochem** [comment]
same crash with the bartworks-1.7.10-0.5.43-32-g105cc8b.jar from jenkins

**Comment by kuba6000** [comment]
Plese use http://jenkins.usrv.eu:8080/job/Bartworks/498/
