### ISSUE TITLE
Personal Space issues

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10555]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.4-dev-pre14

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

.

### The Reality

- [x] the `/pspace where <player>` could say `<player> is in dim <dim>` instead of `<dim>` in the chat
- [x] pressing the done button in the gui of the portal always tells in the chat `Personal dimension successfully updated!` even if the portal is locked and no change applied to star/sky colors
- [x] the `/pspace allow-worldgen-change <dim>` doesn't say anything in the chat, it could say something like `Sucessfully unlocked portal edition of dimension <dim>`
- [x] Biome name button is always greyed out, dunno what is its purpose. Maybe turn it into something displaying the list of availiables biomes, because it's impossible for the user to guess what biomes are allowed.
- [x] Make a way to know for the user the list of availiable blocks to use in the custom world generator, as it's also impossible for the user to guess the blocks if the server owner changed the config.
- [x]  what's is the difference between red color and yellow color? both are not saved when clicking on the done button.
- [x] In case of invalid input, the done button still acts as if it was successful, but it's not actually saving. Maybe add a red string in the gui saying it cannot save due to incorrect input
- [x] gui is too zoomed in gui scale auto, so you can't even validate stuff as you need to press the done button
- [x] Add a weather unlock toggle
- [x] Look into void sky compatibility

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eranicus** [comment]
(clean 2.4-14v pre dev) something is wrong with generation, just created new portal with tree/foliage off, but got tree's from natura / thaumcraft  and some flowers from projectred exploration
![](https://cdn.discordapp.com/attachments/401118216228831252/990759859995697203/2022-06-27_02.23.02.png)
.

**Comment by eigenraven** [comment]
A lot of these are now resolved in <https://github.com/GTNewHorizons/PersonalSpace/releases/tag/1.0.5-GTNH>

 - Generation: sadly natura&probably thaumcraft register their trees etc. as generic WorldGenerators which makes them near-impossible to disable without hacking into forge, for natura I can add an API to configure a dimension list for them at least because it's open source
 - Color differences: red = invalid syntax, yellow = valid, but denied by the configs; I'll add tooltips at some point
 - VoidDimSkyChanger: it looks relatively easy to integrate, I'll add it as an option later

**Comment by Eranicus** [comment]
> A lot of these are now resolved in https://github.com/GTNewHorizons/PersonalSpace/releases/tag/1.0.6-GTNH
> 
> * Generation: sadly natura&probably thaumcraft register their trees etc. as generic WorldGenerators which makes them near-impossible to disable without hacking into forge, for natura I can add an API to configure a dimension list for them at least because it's open source
> * Color differences: red = invalid syntax, yellow = valid, but denied by the configs; I'll add tooltips at some point
> * VoidDimSkyChanger: it looks relatively easy to integrate, I'll add it as an option later

Good news, will be waiting for SkyChanger, Thank you
