### ISSUE TITLE
Stop OC from saving items in computers in the state file

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10551]
Basically, OC stores items in its state file, not in the TE on the map, so if you restore the map without restoring the state files, bye bye your components, especially the HDD bound to the corresponding folder in the map.

Please make it store them in TEs, like any other mod would do.

**Comment by repo-alt** [comment]
The components are saved in NBT, looks like the problem on zeta was caused by incorrect handling of the missing file system

**Comment by boubou19** [comment]
fixed with https://github.com/GTNewHorizons/OpenComputers/pull/63
