### ISSUE TITLE
Nei Config and Bookmark Panel symbols vanish when in inventory or terminal

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10562]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-14-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

When looking at a recipe they look like this at the bottom left of the screen:

![image](https://user-images.githubusercontent.com/40274384/175973314-00941d88-13ef-441c-8762-e52b52e98ce2.png)

### The Reality

When in your inventory or at a AE terminal the symbols suddenly vanish: 
![image](https://user-images.githubusercontent.com/40274384/175973509-a5ccbb28-c269-4439-89d1-73f0d46d32f3.png)

functionality still seems to be fine.

Edit: Even worse, the NEI options look like this: 
![image](https://user-images.githubusercontent.com/40274384/175973897-0de84011-823f-4aa3-a184-1b7a07af3d02.png)

### Your Proposal

make the symbols not vanish.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
buttons tend to reappear when looking at a recipe: 
![image](https://user-images.githubusercontent.com/12850933/176475234-58c92d5a-866e-4628-9aaa-843742007b4f.png)

**Comment by boubou19** [comment]
i qualify this bug as major because config menu is nearly 100% unusable in this state
