### ISSUE TITLE
Adding Weather toggle to Personal Space

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#10560]
### Your GTNH Discord Username

Lord Peverell#3125

### Your Pack Version

2.1.2.4-14-pre

### Your Proposal

Added a setting you can enable to allow weather events in the dim

### Your Goal

Allow the choice of allowing weather events to occur for those that want to use Aqua solars in their base dim. This will allow those who want it not to suffer the 5% transfer from another dim that has the aqua solars and thunderstorm weather enabled

### Your Vision

Allow weather to occur in Personal Dims if the person chooses it 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by eigenraven** [comment]
Implemented in <https://github.com/GTNewHorizons/PersonalSpace/releases/tag/1.0.6-GTNH>
