### ISSUE TITLE
Adding MineMenu

### ISSUE THREAD

**Issue by silverphoenix300** [GTNewHorizons/GT-New-Horizons-Modpack#10564]
### Your GTNH Discord Username

silverphoenix300#0237

### Your Pack Version

2.1.2.3qf

### Mod Name

MineMenu

### The Mod to Add

Adds a radial menu of configurable actions shown while a key is held.
Actions consist of:

- executing a command (/home /warp etc.)
- using an item in a specified slot
- using actions usualy executed by keypress (everything in Options->Controls)
- opening a submenu

### Your Reason

Quality of life and ability to better work around key conflicts

### Preliminary Investigation

- No crash on startup.
- shown in options->Controls as key.open_menu
- Should be mentioned in Quest E_TOO_MANY_KEYS # 2145
- Using an item in a specified slot did not seem to work and coud cause some issues with mods expecting the item to be in the players hand if working(functionality should propably be removed before adding).

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by boubou19** [comment]
source link?

**Comment by silverphoenix300** [comment]
https://github.com/GirafiStudios/MineMenu/tree/1.7.10,also sould propably be added to the template

**Comment by boubou19** [comment]
good point

**Comment by Gateswong** [comment]
Alternatively you can also look into https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1275039-macro-keybind-mod
