### ISSUE TITLE
The new Integrate Ore Factory doesn't seem to work properly

### ISSUE THREAD

**Issue by alexandre-tardif** [GTNewHorizons/GT-New-Horizons-Modpack#10569]
### Your GTNH Discord Username

AlexandreTardif#5582

### Your Pack Version

2.1.2.4-14dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expected the multi to start after it forms and has the required inputs (Lubricant / Distilled water / Ores)

### The Reality

I can get the multi to work on my single player test world but for some reason it doesn't want to start on my main save on a private server. I build it the exact same way and provided the exact same inputs and it still doesn't start

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Josh5minus1** [comment]
I have similar issue, however the difference is that the multi does not process gregtech ores. Only vanilla ores are able to be processed, and regardless of processing mode, it only does maceration part.
