### ISSUE TITLE
Can't clear fluid filter in ender io conduit with left click

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#10567]
### Your GTNH Discord Username

GlodBlock

### Your Pack Version

2.1.2.4

### Your Server

.

### Your Expectation

![image](https://user-images.githubusercontent.com/60341015/176152606-f2c8e4aa-c478-48b7-a005-6487eda79ed3.png)
be able to clear the filter by clicking the icon

### The Reality

can't clear

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
the output hatch lock fluid can be cleared with both right/left click, which also support the ghost item from nei. maybe you can check the holding item, and clear the filter when it isn't a valid fluid container

**Comment by eigenraven** [comment]
I had issues with double events being generated, first a ghost click from nei with the nei item, and then immediately afterwards a regular (non-ghost) click with no item which cleared the ghost filter set before. I'll have a look how the hatches deal with this
