### ISSUE TITLE
Larger ME Storage Cells 

### ISSUE THREAD

**Issue by ChrisLua** [GTNewHorizons/GT-New-Horizons-Modpack#10568]
### Your GTNH Discord Username

ChrisLua

### Your Pack Version

2.1.2.3qf

### Your Proposal

Add larger Storage cells such as 64M, 128M, etc.
Currently the Limit for one cell is 120Million Items of one type. 
i Just placed my Void Miners  3 Days ago. my storage is bursting of "mass" ware like Redstone dust, iron etc.
It would be nice, if we would have an option for larger Storage cells, to not have to spam the max size ones.
(also ME Performance if, there are more then one source/drain of ressources)

### Your Goal

more storage

### Your Vision

Reach stargate!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
I also propose to add an endgame 2^64 single item storage cell

**Comment by joshaup1999** [comment]
Would be nice, different alternative to use infinity chests. Hell could adjust the infinity chest recipe accordingly if these get implemented

**Comment by Sphyix** [comment]
inf chests as drives when :^)

**Comment by Runakai1** [comment]
Infinity chests are supposed to be used and those tiers. If you can fill a 16348k cell fast, you can also make some more infinity chests

**Comment by chochem** [comment]
include infinity in the recipe then. sounds fair.

**Comment by alexandre-tardif** [comment]
I think it's still a pretty good idea. There's a time between filling cells fast and infinity chest that is currently pretty annoying

**Comment by Runakai1** [comment]
> include infinity in the recipe then. sounds fair.

I already made another 65536k Cell, however I got recommended to not do it since infinity chests act as a larger me storage alternative

**Comment by alexandre-tardif** [comment]
Currently the highest tier cell is equivalent to only a quantum tank 1. Adding more isn't a bad idea. Infinity chest will always be better because of the amount of different items it can hold

**Comment by GTNHAfx237v7** [comment]
I’d also welcome higher storage disks to get rid of my 100+ chests with storage busses…

**Comment by boubou19** [comment]
super chests and quantum chests got special support to AE2 so they are interpreted as AE2 cells, making them functionally equivalent. Only thing left that must be done is similar support for the infinity chests, and maybe 2^64 single item storage cells as Repo mentionned.

**Comment by alexandre-tardif** [comment]
While quantum chest do get treated as cell there's the problem that extracting items from them is quite a pain. You kind of have to do that for a lot of the stuff you would store in them when switching over to infinity chests.

**Comment by boubou19** [comment]
What if we could use quantum chests/infi chests directly as cell? i mean physically putting them in the ME drives? the quantum chests keep their content when breaking them, so that would just be a simple matter of spamming ME IO ports.

**Comment by leagris** [comment]
Or more broadly, directly as ME Chests (means directly connects to the ME network via ME cable and occupy One Channel. But at the other end of the spectrum, we need to question why people have incentive to store so much items and fluids and if it is really necessary to provide a sense of progression and enjoyment with the pack.

**Comment by repo-alt** [comment]
What is the point of putting chests in the drives, it does not solve extraction problem, only saves some channels. Bt probably it can be done semi-easily, just need to implement some interfaces on GT side.
As for connecting them directly to the network, that changes practically nothing at all (saves you a storage bus)

**Comment by Eranicus** [comment]
If it is not very hard to implement large ME drives, please do so, there is absolutely zero reason not to do it, especially considering the amount of resources needed at endgame after all latest additions. 

In my opinion ME drives are just better compared to hundreds of chests and storage buses.... 

p.s. currently at the start of UHV and I have zero super/quantum chests, I store everything on a partitioned 16384k drives.

**Comment by Runakai1** [comment]
> If it is not very hard to implement large ME drives, please do so, there is absolutely zero reason not to do it, especially considering the amount of resources needed at endgame after all latest additions.
> 
> In my opinion ME drives are just better compared to hundreds of chests and storage buses....
> 
> p.s. currently at the start of UHV and I have zero super/quantum chests, I store everything on a partitioned 16384k drives.

I will make a PR and see if it gets accepted. If not, 🤷‍♂️ 
Not a big deal. I'd also like the infinity chest to be of more use but I also got the infrastructure for adding new cells so I can just do that as well. Even if it might not get accepted, it's still something that can be "re activated" for the future if needed.

**Comment by leagris** [comment]
The issue with things like ME Chests or chests connected with Storage Buses is their inventory can be altered from other sources than the ME. So the ME need to constantly update the inventory each time items moves in or out without using the ME Network. It makes these inventories which exist in both in-world and within the ME network, very CPU costly to operate.

**Comment by Eranicus** [comment]
> > If it is not very hard to implement large ME drives, please do so, there is absolutely zero reason not to do it, especially considering the amount of resources needed at endgame after all latest additions.
> > In my opinion ME drives are just better compared to hundreds of chests and storage buses....
> > p.s. currently at the start of UHV and I have zero super/quantum chests, I store everything on a partitioned 16384k drives.
> 
> I will make a PR and see if it gets accepted. If not, 🤷‍♂️ Not a big deal. I'd also like the infinity chest to be of more use but I also got the infrastructure for adding new cells so I can just do that as well. Even if it might not get accepted, it's still something that can be "re activated" for the future if needed.

Thanks, hope it will be accepted ...

**Comment by boubou19** [comment]
> The issue with things like ME Chests or chests connected with Storage Buses is their inventory can be altered from other sources than the ME. So the ME need to constantly update the inventory each time items moves in or out without using the ME Network. It makes these inventories which exist in both in-world and within the ME network, very CPU costly to operate.

Repo made the super/quantum chests locked from in world interactions if it's connected to an AE2 network, but not for the infi chest. Since both infi chest and super/quantum chests keep their content when pickaxed/wrenched, i thought we may as well add them directly as cells.

Honestly, other cells than 1 type cells are purely useless as you will never use the full potential of the cell, as the ratio bytes used / item will be higher than lower cells.

**Comment by chochem** [comment]
large cells are now available in 2.1.2.4 20-pre
