### ISSUE TITLE
Indalloy 140 is not used in all assembling line recipes. 

### ISSUE THREAD

**Issue by alexandre-tardif** [GTNewHorizons/GT-New-Horizons-Modpack#10565]
### Your GTNH Discord Username

AlexandreTardif#5582

### Your Pack Version

2.1.2.4-dev-pre14

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Was converting my assembling line recipe to the new soldering alloy. Expected all recipes to use the new alloy.

### The Reality

Quite a bit of the recipes still use the old soldering alloy. For example UHV+ components, VM2-3, Really / Ultimate battery, etc...

### Your Proposal

Change every assembling line recipe to use the new soldering alloy

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
- [ ] TecTech
- [ ] Bartworks
- [ ] GalaxySpace

@Steelux8
