### ISSUE TITLE
EIO item filter in item conduit behaves oppositely in terms of extract and insert

### ISSUE THREAD

**Issue by SSWZDDTI** [GTNewHorizons/GT-New-Horizons-Modpack#10570]
### Your Pack Version

2124-14-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Place item filter in extract side will filter extracted item, place item filter in insert side will filter imported item.

### The Reality

Place item filter in extract side filter imported item, place item filter in insert side filter extracted item. In order to filer imported item need to put item filter in extract side
![Screenshot 2022-06-28 210719](https://user-images.githubusercontent.com/44363450/176186234-59680469-0954-4569-8213-18ff67854228.png)

### Your Proposal

Fix the issue

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by eigenraven** [comment]
Whoops, I was sure this was going to happen with one of the conduit slots. For context, the enderio code uses "import" for extracting and "export" for inserting, which made moving around the gui components confusing. This will be an easy swap of slot positions in the gui.
