### ISSUE TITLE
Add a TPS card to open computers

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10573]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.4-dev14

### Your Proposal

I suggest to add a TPS card, that basically acts the same way as `/cofh tps` but with some extras.
- [ ] `component.tps_card.getTickTimeInDim` would be the equivalent of `/cofh tps <dim>`, which would return a float representing the ms taken by the dimension
- [ ] `component.tps_card.getOverallTickTime` would be the equivalent of `/cofh tps o`, which would return a float representing the overall tick time of the server
- [ ] `component.tps_card.getAllDims` which would return a table with index corresponding to the dimension and value at the index being the dimension name
- [ ] `component.tps_card.getNameForDim` which would return the name corresponding to the dimension passed as parameter (only int). Should crash on non existing dim number or non int values.
- [ ] `component.tps_card.convertTickTimeIntoTps` which would take a number as parameter (in ms), and returns the actual TPS corresponding to it. (`ticktime < 50 ? 20 : 20*50/ticktime` in java)
- [ ] `component.tps_card.getOverallTileEntitiesLoaded` would return the overall amount of TE loaded in memory. (see `/cofh tps a`)
- [ ] `component.tps_card.getOverallChunksLoaded` would return the overall amount of chunks loaded in memory. (see `/cofh tps a`)
- [ ] `component.tps_card.getOverallEntitiesLoaded` would return the overall amount of entities loaded in memory. (see `/cofh tps a`)
- [ ] `component.tps_card.getOverallDimsLoaded` would return the number of dims loaded. (see `/cofh tps a`)
- [ ] `component.tps_card.getEntitiesListForDim` would take an int representing the dim id and would return a table where the index is the name of the entity class, and the value the amount of entities in that dim. It should crash on non int values or invalid dims.
- [ ] `component.tps_card.getTileEntitiesListForDim` would take an int representing the dim id and would return a table where the index is the name of the TE class, and the value the amount of TE in that dim. It should crash on non int values or invalid dims.
- [ ] `component.tps_card.getChunksLoadedForDim` would take an int representing the dim id and would return a value corresponding to the amount of chunks loaded in that dimension. It should crash on non int values or invalid dims.
- [ ] `component.tps_card.getCoordinatesForEntityClassInDim` (optional) **Should be availiable only for operators**. It would take a string corresponding to the targetted entity class name, and an int corresponding to the dim number. It would return a table with all the coordinates of the entities matching the class name. It should return an empty table if there is no matching entity in the dimension. It should crash on invalid dim value.
- [ ] **That card should be a T1 card**, as i don't see the need to gate this, it's meant to be a legit way for players to diagnose a bit their map/server, so it should be availiable asap.
- [ ] **It should have a cheap recipe**, as it is meant to be public information, so it should have the easiest access possible.
- [ ] Behind the scene, that component **should cache the values returned for a configurable amount of ticks in the config**. We do want to avoid the server being spammed.

### Your Goal

Make such data availiable in game, without having to resort to commands/plugins.

Right now, it's done on the officials by the combination of a custom mod to extract data from the game and a lua program to process the data.
For the curious, see https://github.com/boubou19/boubs-admin-tools and http://boubou-19.fr:8080/oc/admin/tps_reader.lua . I don't really intend to support stuff, as it was quickly designed to provide a basic tps measuring tool displayed at spawn of each official server. So it would be cool to have a "legit" way of doing that 😄 

### Your Vision

This would finally provide a base framework for server admins to do tps related displays on their server. This could also enables basic self monitoring for players, so they can see their lag footprint at anytime without the need of an operator.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
TPS card is in, but it needs a recipe
