### ISSUE TITLE
XL gas turbine seems to ignore mufflers

### ISSUE THREAD

**Issue by realthecaffiend** [GTNewHorizons/GT-New-Horizons-Modpack#10572]
### Your GTNH Discord Username

thecaffiend#2253 

### Your Pack Version

2.1.2.3qf  (Some config changes, no recipe changes)

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

The XLGT would use the installed mufflers to reduce pollution output

### The Reality

Experimenting with mufflers in single player, I found that my test XLGT (Large ori turbines and benzene) would accept advanced EV mufflers, work without filters, report an odd value for reduction (34%, which is neither the regular or advanced muffler reduction according to the tooltips), but that it also just continued to produce an amount of pollution that I have to assume is still exactly 5k/second (Constantly scanning a block, almost every update was exactly, to the single digits, 10k pollution increase, except the occasional addition of 10k and then the dissipation mechanic). I went to file that as an issue and tested with regular EV hatches to make sure that they worked; Surprisingly, every update was once again, exactly 10k except the occasional tick down. EV hatches should result in 3100/second which can not add up to 10k, so it seems to be ignoring the mufflers. 

Then to test, I installed UHV mufflers which should reduce to 0, and had the same result of exactly 10k pollution additions every time the value updated: As referenced below, nothing else anywhere nearby was producing any pollution whatsoever, this was a new teleported to area in a test world. 

Between all of these tests I used a multiblock air scrubber to get back down to near-zero, under 10k where they start ignoring the chunk, disabled it, and waited for the cycle to complete, just to make sure there was no shenanigins with scrubbing or spreading to other chunks at over 400k. Nothing else nearby polluted, as confirmed by scanning blocks repeatedly when the XLGT was off and reporting the same value over and over again.

### Your Proposal

Fix the XLGT to respect the installed mufflers, and also, reduce the pollution output of it: While it is meant to represent a lot of gas turbines, 12 or 16 or 18 depending how you look at it/what version you are on, 16 turbines at 300 each would still only be 4800, let alone the fact that they would often tend to end up in different chunks. Right now I had to install a multiblock scrubber near it in order to ever consider seeing a plant again (Such as the trees that feed the turbine). 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by realthecaffiend** [comment]
As requested, the controller with advanced EV mufflers (Bonus, seen in the background) reporting 34%: 
![image](https://user-images.githubusercontent.com/8347355/176252624-780fca3c-4ecb-4ec1-a710-44ba47335d4b.png)

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GTplusplus/pull/227, https://github.com/GTNewHorizons/GTplusplus/pull/228
