### ISSUE TITLE
Unable to equip a LINKED wireless golem backpack to my golems

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#10584]
### Your GTNH Discord Username

Shibva_

### Your Pack Version

2.1.2.3

### Your Server

NA

### Your Expectation

I was going to make somthing funny in creative and networked l inked golems was going to be part of it so I did a small setup and linked the pcack and right clicked it

### The Reality

Id did not work at all

### Your Proposal

It might have something todo with this
https://github.com/Nividica/ThaumicEnergistics/issues/328

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment]
Also tested in .3qf and confirmed you cannot place wireless backpack on a golem

**Comment by SteamDoge9000** [comment]
https://github.com/Nividica/ThaumicEnergistics/issues/328

this report seems to adress the issue possibly being a conflict


https://github.com/Nividica/ThaumicEnergistics/issues/328
