### ISSUE TITLE
Update quest description or fix radio hatch decay times to match quest

### ISSUE THREAD

**Issue by greesyB** [GTNewHorizons/GT-New-Horizons-Modpack#10585]
### Your GTNH Discord Username

Greesy#2016

### Your Pack Version

2.1.2.3qf

### Your Server

Private

### Your Expectation

The questbook lists acceptable rod types, sievert values, and decay times for radio hatches for bacterial vats:
![image](https://user-images.githubusercontent.com/73182109/176506753-68c5322d-33b5-4c7b-8636-4d2c4c75a0b7.png)

While the sievert values are correct, the decay times for bismuth through plutonium are incorrect.

### The Reality

Bismuth expected decay: 198 seconds
Actual decay (spamming scan as one finishes decaying and another is consumed): ~190 seconds
![image](https://user-images.githubusercontent.com/73182109/176507872-1bf4e59c-a8d9-466a-8ff9-29e8202111e9.png)

Uranium expected decay: 80 seconds
Actual decay: ~60 seconds
![image](https://user-images.githubusercontent.com/73182109/176508849-8bb564dd-0907-41aa-8bd8-09ae749d16f2.png)

Plutonium expected decay: 66 seconds
Actual decay: ~42 seconds
![image](https://user-images.githubusercontent.com/73182109/176509109-781cf340-7067-4501-b452-3ba4b8f7f50a.png)

Bartworks appears to use [this function](https://github.com/GTNewHorizons/bartworks/blob/648cce31e82760df877ff48177003a0e789a8396/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/tiered/GT_MetaTileEntity_RadioHatch.java#L78) to calculate decay time.
![image](https://user-images.githubusercontent.com/73182109/176508980-fbd1ca99-2c4d-40d8-9c06-d2d59f82cb7d.png)

For sieverts less than or equal to 100 (materials below naq) it should use the first formula which would match the questbook values. Instead it seems to use the second formula for all sievert values which seems impossible by just looking at the code.

Example
Plutonium has sievert of 94. Using the first formula:
`(8000 * tanh(-94/20) + 8000) * 1000 = 1324 ticks to decay (66.2 seconds, questbook value)`
Using the second:
`(8000 * tanh(-94/65) + 8000) = 841 ticks to decay (42.05 seconds, observed value)`

Naq and enriched naq have proper decay times:
![image](https://user-images.githubusercontent.com/73182109/176510150-83d505ae-eea4-4148-8f18-5bbcb654e730.png)
![image](https://user-images.githubusercontent.com/73182109/176510249-f2df45ce-f940-403a-9414-f471e74693cc.png)

~Naquadria doesn't seem to be an actually valid material as their rods cannot be placed in a radio hatch.~ Apparently fixed in newer BW versions.

All of the above is unaffected by radio hatch tier and sievert shuttering.

### Your Proposal

Either these decay times should be accepted as intended and the questbook updated, or fix the decay rate since it seems that they were originally meant to match the current quest.

For what it's worth, the current values in the questbook appear to have come from testing when the vat was originally added, thanks to chochom for this link - https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6115

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Bart switched the normal tanh to a hacked tanh to improve speed in  [#GTNewHorizons/bartworks@#a811bd4](https://github.com/GTNewHorizons/bartworks/commit/a811bd46d45ba07207ef818702b4b6198d7641b8)

The tanh-code now is the following
```
public static float tanh(float x) {
        float x2 = x * x;
        float a = x * (135135.0f + x2 * (17325.0f + x2 * (378.0f + x2)));
        float b = 135135.0f + x2 * (62370.0f + x2 * (3150.0f + x2 * 28.0f));
        return clamp(a / b, -1, 1);
    }
```
Doing the original calculation for plutonium `(8000 * tanh(-94/20) + 8000) * 1000`
this yields:
a = -3 351 454.4135063
b = 3 351 805.844212
and thus the tanh returns -0.9998951518309728. While a true tanh(-94/20) would yield -0.99983456555. So we are slightly off starting at the 5th digit. Though with this small difference the whole formular calculates to 838 ticks which is as measursed. So we'd either need to make the tanh function from bartworks more accurate or we need to change the multiplicators/offsets in the formular a bit to compensate. Or of course just change the questbook to fit the values.

**Comment by chochem** [comment]
oh wow. nice find. its the fifth digit but you then look at (1+that value)x8.0E6 and that drastically blows up the error.

I guess I could use that formula to calculate the new values and put them in the questbook. Though ideally somebody tests in game as well.
