### ISSUE TITLE
Centrifugating Ashes does not match NEI recipe

### ISSUE THREAD

**Issue by thomas-lehericy** [GTNewHorizons/GT-New-Horizons-Modpack#10581]
### Your GTNH Discord Username

Castor#0577

### Your Pack Version

2.1.2.0

### Your Server

Official GTNH Server 2 EU

### Type of Server

Don't know

### Your Expectation

Centrifugating Ashes yields, according to NEI, in full dust per ash:
- 0.5 quicklime
- 0.16 potash
- 0.15 magnesia
- 1/180 phosphorous pentoxide
- 1/18 soda ash
- 1/36 banded iron, approx. 0.2777

### The Reality

After centrifugating close to 120 stacks of ashes, the observed drop chance are as approximately (+/- 10% relative error) as follows, in full dust per ash:
- 0.5 quicklime
- 0.16 potash
- 0.0175 magnesia
- 1/9 phosphorous pentoxide
- 1/18 soda ash
- 0.097 banded iron
Note the very different values for: magnesia, phosphorous pentoxide, banded iron.

### Your Proposal

Possible explanation: the NEI recipe describes what happens when centrifugating ashes one by one. However, the ashes are centrifugated 36 by 36. The numbers may not match in this latter recipe?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
NEI in .4 dev14 says: 
- quicklime 0.32
- potash 0.15
- magnesia 0.0125
- phosphorous pentoxide 0.055 (1:18)
- soda ash 0.027777 (1:36)
- banded iron 0.1111 (1:9)

thats completely different than what you wrote. Dont know if thats caused by a version difference or your maths skills though. :P

**Comment by chochem** [comment]
did some testing by putting in some separate storage. I got the following ratios after some unknown amount of recipes:

- quicklime 56336 (56336/0.32=176050)
- potash 26685 (26685/0.15=177900)
- magnesia 2268 (2268/0.0125 = 181440)
- pp 9932 (9932*18=178776
- soda ash 4860 (4860*36=174960)
- banded iron 19656 (19656*9=176904)

as you can see in the brackets the agreement with the NEI rates is perfect.

The ticket can be closed or at least get a 'cannot reproduce' tag.
