### ISSUE TITLE
Button not working in crafting status GUI

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#10583]
### Your GTNH Discord Username

Alexdoru#9395

### Your Pack Version

2.1.2.4-14pre

### Your Server

SP

### Your Expectation

When I click the CPU button at the bottom I expect it to cycle through the currently working crafting CPUs

![image](https://user-images.githubusercontent.com/57050655/176506086-06088bc6-4ec0-40ae-bcc3-60b275697f45.png)

### The Reality

it doesn't

### Your Proposal

please fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by eigenraven** [comment]
Fixed in https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/167
