### ISSUE TITLE
Thousands of duplicate TileEntityNuclearReactorElectric / TileEntityReactorChamberElectric tile entities being created.

### ISSUE THREAD

**Issue by fluffle** [GTNewHorizons/GT-New-Horizons-Modpack#10595]
### Your Pack Version

2.1.2.3qf (+some changes, see below)

### Your Server

personal private server

### Type of Server

Vanilla Forge

### Your Expectation

Each of my 2 nuclear reactors has one `TileEntityNuclearReactorElectric` and six `TileEntityReactorChamberElectric` objects in my Java heap dump.

### The Reality

I'm running 2.1.2.3qf with some additional mods (sorry not sorry).

 - hodgepodge 1.7.3 from Jenkins to fix #6976
 - BoP 2.1.0.2308 from curseforge (for compat with new hodgepodge
 - appliedenergistics2-1.7.10-rv3-beta-86-GTNH-1-g8e6b826.jar (it's got some nice new features in)
 - FTBLib + FTBUtilities for server backups + chunkloading

As noted in the last updates to #6964, I have seen some odd error messages with reactor tile entities not being part of the correct energy net, or being duplicates. After updating to hodgepodge 1.7.3 to fix the leaking tile entities from #6976 I was still seeing strange and relatively frequent tick drops while connected and playing. I dumped another heap to see why, but with only 1.6G of live objects (and 10G allocated heap) it couldn't be GC thrashing. 

I noticed that one of the largest heap dominators was `mcp.mobius.mobiuscore.monitors.MonitoredTileList`. Notably, all of the reactor tile entities that I was seeing were retained by this and nothing else, though I only checked a handful of the ~27k objects. A quick poke through github issues for this turned up #9147 which made me suspect that the reason for my dropped ticks is the O(n^2) iteration through the ~30k tile entities that mobiuscore does on a regular basis.

But this doesn't tell me why these entities are duped in the first place, and that's why I'm filing this bug.

What I'm going to do next:

- Remove Opis from the server mod list
- Add fastcraft to the server mod list
- Play a bit and grab another heap

If anyone has any interesting ideas for debugging this please LMK!

### Your Proposal

I would think that duplicate tile entities would be quite concerning, and I would like my nuclear reactors not to be duplicated!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by fluffle** [comment]
Update: I removed Opis and added fastcraft server side. I can confirm that reactor tile entities are being duped still.

Here are some entertaining screenshots of what happened when I tore down one of my reactors after the server had been up ~2h: https://imgur.com/a/9i7wm9l

As you can see it's duping all the contents of the TE as well; I certainly didn't make that many rods or reactor components. And those three compressed chests are probably only half of the total, the rest despawned before I got it all into chests. I don't think this is particularly chunkloading related, since I was in my base for ~all of the two hours or so prior to the disassembly. 

The only departure was to take a quick trip to the nether to (probably, modulo spawn chunks?) unload the chunks the reactor was in and grab a heap dump, shortly before I decided to disassemble the reactor. I took another heap dump ~3 minutes later once I returned from the nether. Comparing these heaps with a couple of OQL queries shed some more light on things:

```OQL
SELECT OBJECTS o FROM "ic2\.core\.block\.reactor\.tileentity\.TileEntityNuclearReactorElectric" o
  -> 49 reactor entries in heap where reactor chunks are unloaded
  -> 50 reactor entries in heap where reactor chunks are loaded

SELECT toString(o.field_145851_c)+","+toString(o.field_145848_d)+","+toString(o.field_145849_e) FROM "ic2\.core\.block\.reactor\.tileentity\.TileEntityNuclearReactorElectric" o
  -> all 49 tile entities are at -88,59,-89 where reactor chunks are unloaded
  -> 1/50 is at -72,59,73 where reactor chunks are loaded
```

So it seems like only one of my two reactors is being duplicated? After disassembling the reactor that was bugged and leaving the server alone with 0 players and everything unloaded for 24h, I can still see 49 reactor tile entities in the heap, so they have very definitely leaked.

The reactor isn't doing all that much, either, so maybe someone else can reproduce this?

I have the standard 1920EU/t thorium design from the wiki, with its output going via 1 aluminium cable directly into a 4-slot EV battery buffer with 4 lapotron crystals. This feeds directly into an AE energy acceptor, which is connected to my AE network via a cable with a toggle bus on it. The ev battery buffer has a energy level cover on the bottom, and the redstone signal from this feeds through a relatively standard RS latch setup with 2 dense crystals, a not gate and a buffer. There's nothing else connected to this.

I went over my server logs a little more carefully and noticed these lines occurred before other instances of EnergyNet complaints:

    [18:39:25] [Server thread/WARN] [IC2.EnergyNet]: EnergyNet.removeTileEntity: appeng.tile.networking.TileController@53a7050c (appeng.tile.networking.TileController@53a7050c) doesn't match the registered te appeng.tile.networking.TileController@283f724b, skipping
    [18:39:25] [Server thread/WARN] [IC2.EnergyNet]: EnergyNet.removeTileEntity: appeng.tile.networking.TileEnergyAcceptor@18613bff (appeng.tile.networking.TileEnergyAcceptor@18613bff) doesn't match the registered te appeng.tile.networking.TileEnergyAcceptor@7f8646af, skipping 

So this made me go and see whether TileController and TileEnergyAcceptor were being duplicated too... And they were :-(

The 2h heap with chunks *unloaded* shows 4 copies of most of my controller TEs and my 2 energy acceptors. The 2h heap with chunks *loaded* actually shows fewer copies -- one duped controller and one duped energy acceptor. Much more concerning is that the heap from the next day shows 3923 controller TEs and 306 energy acceptor TEs (302 copies of 1, 4 of the other). So while the server is idle something is still duplicating (or not cleaning up).

I took ~50 of the TileEnergyAcceptors and asked MAT what was holding references to them. A couple of loaded classes hold references to them. Here's a screenshot because it's easier than trying to use words: https://imgur.com/a/TTYsS5Q

I am not going to have any time to debug this further for ~6-7 weeks, because summer. But given the above the next thing I'm going to try is removing holoinventory, since I don't use it anyway.

**Comment by fluffle** [comment]
Hi all,

I can confirm that even with @eigenraven's patched holoinventory I still get duplicated reactor TEs. At this point their only non-weak path to a GC root is via the minecraft server's field_147482_g ArrayList, which is presumably a list of all loaded TEs?

The duplication only happens on the reactor that's connected to my AE2 network The other reactor I have (which is only connected to an EBF and a vacuum freezer) does not suffer duplicated tile entities in the same fashion. It doesn't appear to be necessarily to do with loading/unloading chunks -- I had just north of 1500 reactor TEs live on my heap after ~4h of playing entirely within my base, from a fresh server start. 

Is it possible to patch in a command somewhere that can simply scan the list of loaded TEs and print out the number of reactors found, to make debugging this easier? I could then attempt to recreate a minimal reproduction case, which might help figure out where the bug is.

Lastly, I can also confirm that while strange this isn't the root cause of my odd tick-skipping. I moved my world from spinning rust to SSD on the server and the skips went away :-)

**Comment by boubou19** [comment]
are your reactors not crossing chunks? might be some ghost loaded TEs. I have seen this impossible to trackdown issue on the officials for some random other TEs. Usually the players just rebuild their infra and it goes away.

**Comment by fluffle** [comment]
The reactor was within a single chunk, along with the battery buffer, energy acceptor, all AE controller TEs and the RS latch to control the reactor. I'm now powering my AE system with a gas turbine running on Nitrobenzene, thus far this seem to be working fine w.r.t. duplicated TEs.
