### ISSUE TITLE
Ammonium Nitrate solution is missing an LCR recipe

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#10591]
### Your GTNH Discord Username

repolainen#0483

### Your Pack Version

2.1.2.4-14-pre

### Your Proposal

Add a recipe

### Your Goal

.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/16
