### ISSUE TITLE
Bringing the Future to the past with Village Names

### ISSUE THREAD

**Issue by Shibva** [GTNewHorizons/GT-New-Horizons-Modpack#10605]
### Your GTNH Discord Username

Shibva_

### Your Pack Version

2.1.2.3

### Mod Name

Village Names

### The Mod to Add

Overhauls the Villagers by bringing some of the changes they underwent in 1.14 to older versions (and apparently is updating still in 1.7.10)

the mod includes
-structure generation from post 1.14 villages
-Texture Overhaul that the villagers received (can be configured and even has modded support)

### Your Reason

Villages in this version are... well stupid. I've been in the newer versions and looking back at them in this pack after returning for a time it shows how far they have come. The pack is focused on the progression through the technology that some of the smaller things get left unnoticed. The pack is in a version that is 8 years old now and some people miss some of the features that were added over the years (while others are not)

Adding village names would bring some of that future version feel into the pack and could give a more comforting feel of the newer versions in a pack that is in a old version.

its also was found by one user who agrees with this idea that its under the LGPU 3.0 

### Preliminary Investigation

other than the villager changes, future version trades can be added (and disabled in the provided config below), and the generation of an igloo and underwater monument (also disabled in provided config; that also removes the items associated with them {monument} from the registry as well)

the nitwit profession (left ON in the config below because yes)

the blocks associated with the world of color update (concrete and its powder forms with colors, glazed terracotta; left ON in the config below; provides no conflicts with existing recipes and does not bypass any progression as the items themselves provide no prediction that is used)

a few special trades regarding documenting villages (left on due to these being minor things that just make survival a tad bit easier; usually enchantments and potions, nothing big and requires some work todo)

it seems that this mod works without causing any real issues on its own; though if its considered blot it could just be a addon for the pack

the config below is one that's adjusted for GTNH, if its considered an addon it may be best to have this config in the pack regardless 

[VillageNames4.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9030960/VillageNames4.zip)
H

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by YannickMG** [comment]
Looks published and updated for 1.7.10: https://www.curseforge.com/minecraft/mc-mods/village-names
GNU LGPL: https://www.curseforge.com/project/259230/license

Looks like a great mod, sounds great in theory.

**Comment by SteamDoge9000** [comment]
only issue is that I had to disable their village gen, only because it doesn't seem to be showing up; id did say something about possibly having to disable other village generation or something, but if its considered it can be fixed

the skins are working and it may be client? idk tbh

glad to hear some positive response for a change

**Comment by YannickMG** [comment]
Don't get your hopes up too much, I just like shiny new things.

**Comment by SteamDoge9000** [comment]
by the looks of it and the config i created (and the creation of a few trades that are added that don't break the progression but can serve as nice lil quest for the villagers) it seems like it can be added out of box

**Comment by RehabCZ** [comment]
I'd love to see Village Names in GTNH. It really improves the Village experience and i believe that GTNH devs can really push that experience much further

**Comment by leagris** [comment]
Seems reasonable to me as this mod is purely cosmetic while improving the gameplay.

**Comment by SteamDoge9000** [comment]
keep in mind that ti seems to work just by plugging it in, it does seem that the custom village generation cannot take place as the others seem to be preventing it; if it is accepted, we will have to see what the devs decide with it
