### ISSUE TITLE
Controling [mod update]

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#10604]
### Your GTNH Discord Username

Shibva_

### Your Pack Version

2.1.2.3

### Mod Name

Controlling

### The Mod to Add

... tbh its the one thats in the pack, but it updated (surprisingly since this is a mod that's in future versions)

this update adds in the overlay that is default in the newer versions of minecraft

basically a backport touchup by implementing the overlay standerd

### Your Reason

makes key managment a lot easier

### Preliminary Investigation

no issues, works and behaves and keybinds remain unaffected

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by SteamDoge9000** [comment]
Before yall get on me for filling this out wrong; IN DEFENCE, there's no template that really exists for suggesting mod updates

**Comment by miozune** [comment]
Already updated in dev https://github.com/GTNewHorizons/DreamAssemblerXXL/pull/46
