### ISSUE TITLE
Retier the integrated ore factory

### ISSUE THREAD

**Issue by Miisi** [GTNewHorizons/GT-New-Horizons-Modpack#10606]
### Your GTNH Discord Username

Misi#3673

### Your Pack Version

2.1.2.4-14-pre with updated bw+gt

### Your Proposal

change the components in this recipe to UHV tier, optionally change the UV circuits for an UEV circuit
![image](https://user-images.githubusercontent.com/46682682/176955025-12e1e752-09ae-439b-a42c-94bea4fb248e.png)
maybe change the scanning requirement to an UV/UHV washing machine in a research station so that it fits

### Your Goal

discord convo that we had yesterday for reference https://discord.com/channels/181078474394566657/181078474394566657/992160295378239518

at ~7.5s @ 1A ZPM, the multi is able to crush->wash->crush->centrifuge 1024 ores, which is a bit too much for how simple it is to craft. more than that, I think players should "have to" set up PA/GT++ ore processing infrastructure to handle void miner output before having access to the multiblock, because as it is right now, you can craft the multiblock before void miners

I don't think the processing speeds should be changed, a retier by changing the components would be fine as to not make it too weak for UHV+

### Your Vision

I think this would help improve the pack by having players build dedicated void miner ore processing before being able to craft this multiblock (?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Sphyix** [comment]
Players won't move to this multiblock after setting up gt++
This multiblock as it is, is slower and/or requires amounts of power far superior than what gt++ needs.
The good thing about this multiblock is how easy it is to setup, but I wouldn't move to this if gt++ is already setup, as this multiblock is inferior.

**Comment by alexandre-tardif** [comment]
The time were adjusted based on your feedback. Speed is roughly the same now. Macerate -> Macerate -> Centrifuge is base 15s instead of 90s now

**Comment by Sphyix** [comment]
Then this suggestion makes sense, I didn't follow what happened on the original PR, sorry
