### ISSUE TITLE
Reimplements control cores with much cheaper recipes

### ISSUE THREAD

**Issue by alexandre-tardif** [GTNewHorizons/GT-New-Horizons-Modpack#10609]
### Your GTNH Discord Username

AlexandreTardif#5582

### Your Pack Version

2.1.2.4-14-pre

### Your Proposal

I think that now that GT++ machines are required for late game it's time to balance them a bit. What I think would be a good way to balance them somewhat would be to re-enable control cores but massively change the recipe. What I propose is that the cost is somewhat in line with a single block of the tier. What I was thinking of would be 2 circuits of the tier and 2 motors. It'd still be cheaper than making a single block and would eliminate tier skipping.

Discord conversation for reference https://discord.com/channels/181078474394566657/224191655375273985/992797124188176434

### Your Goal

Currently I think GT++ machines are quite strong compared to the alternatives. I think this change would make them cost a bit more while not nerfing their efficiency. If possible I'd like it if a UEV control core could be added and that would unlock all recipes UEV+. It would also be great if power cores only affected multi that replace single blocks.

### Your Vision

I think this would make GT++ a bit more in line with other options cost wise, they'll still be stronger because of their speed and power efficiency but I feel this would help the overall balance of the pack

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
an interesting suggestion. I would just add that this change is probably a bit bigger in scope/questions than the ticket suggest as one would likely need to:
- disable the functionality for a few selected multis (pss obviously would be one example if it would restrict that).
- decrease casing count by one for many multis.

Furthermore, if this is implemented we can consider: TT energy hatch and laser support for many multis, removing energy hatch limit on stuff like the ABS.

It would obviously mess up almost every IV+ base severely. But I guess that is obvious. So if done it should be done properly and thought out.
