### ISSUE TITLE
New problems with windows defender and logistics pipes

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10602]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-14-pre

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

-

### The Reality

![image](https://user-images.githubusercontent.com/40274384/176886979-39fdb88b-9b2e-4441-99a0-20857993507b.png)

This is on .4 14dev which uses logisticspipes-1.7.10-0.9.4.5.6-GTNH. So this is a new problem or a new versions of it, not just the old.

It happened directly after a windows update today.

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
that sucks.

**Comment by Connor-Colenso** [comment]
This is pretty serious if it keeps re-occuring as it looks really bad to people trying to play the pack for the first time.

**Comment by xSkewer** [comment]
It's happening with the "fixed" version in announcements for .3qf as well now.

**Comment by SteamDoge9000** [comment]
oh for fucks sake, I was told about this; its a curseforge bug and is a false positive because it was encoded or whatever its called incorrectly 

seriously a fix was posted but the one on curse needs to be hotfixed and I think its a pain for them todo it; CONSIDERING curse does not support custom instances

**Comment by chochem** [comment]
> oh for fucks sake, I was told about this; its a curseforge bug and is a false positive because it was encoded or whatever its called incorrectly
> 
> seriously a fix was posted but the one on curse needs to be hotfixed and I think its a pain for them todo it; CONSIDERING curse does not support custom instances

I am not following what you are saying. I am not using curse obviously. And this is several dev versions past the old hotfix.

**Comment by SteamDoge9000** [comment]
no it is, ist in the last curseforge release

**Comment by boubou19** [comment]
@SteamDoge9000 you are refering to the old issue we had on the dev version posted on curseforge, but this is another issue. This one is happening on latest dev, for different reasons, but with the same result. It is also not a bug, just the antiviruses hating smart code as it is oftenly suspicious.

**Comment by Chaoschaot232** [comment]
Any new information about this problem?
Sended it in to Microsoft but it was rejected for full scann because there are to many files within the JAR itself so it checked only a few thounds from arround 2k files which it finds sus but couldn't find itself anything bad so I wonder how we can get rid of this stupied false-positive which only applies to LP sadly :/

**Comment by RichardCritten** [comment]
Created an exclusion for the virus scanner and extracted the contents of logisticspipes-1.7.10-0.9.4.5.4-GTNH.jar (it's just a zip file) into its individual files.

Removed the virus scanner exclusion and manually scanned:
  Category: Trojan  file: C:\NB\logisticspipes-1.7.10-0.9.4.5.4-GTNH\logisticspipes\proxy\enderio\EnderIOProxy.class

Removed the above .class file and rescanned passed ok.

Hope this helps.

**Comment by chochem** [comment]
@RichardCritten I have no idea if that helps, just wanted to say thats the wrong version.

**Comment by RichardCritten** [comment]
Download today from [GTNewHorizonsClient-1.7.10-2.1.2.3qf.zip](http://downloads.gtnewhorizons.com/ClientPacks/GTNewHorizonsClient-1.7.10-2.1.2.3qf.zip)

**Comment by chochem** [comment]
just read the ticket. this is about a dev version (namely dev14, but also applies to dev17 and dev18 I think) and log pipe 0.9.4.5.6

**Comment by Connor-Colenso** [comment]
It's non-ideal but purging the mod wouldn't be the end of the world. I'd rather lose LP than have GTNH show as a trojan forever given this seems a particularly tricky issue to resolve.

**Comment by chochem** [comment]
The new https://github.com/GTNewHorizons/LogisticsPipes/releases/tag/0.9.4.5.7-GTNH hasnt had any problems for 4 weeks now, so I am gonna call this is fixed. Lets hope it doesnt come back again.

**Comment by Shibva** [comment]
I hope so too *knocks on wood*
