### ISSUE TITLE
Game crashes occasionally when a quest from better questing is clicked 

### ISSUE THREAD

**Issue by richj04** [GTNewHorizons/GT-New-Horizons-Modpack#10617]
### Your GTNH Discord Username

rich2#0105

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Clicked on a quest that I haven't completed yet. Expected to show the questing page with information, but the game crashed. 

### Crash Report

[crash-2022-07-03_15.06.11-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9035513/crash-2022-07-03_15.06.11-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by YannickMG** [comment]
Would you happen to know which specific quest it was?

**Comment by richj04** [comment]
One of them I crashed on was while clicking on the solar panel quest in MV, but it happens on others too.

**Comment by YannickMG** [comment]
I believe this was fixed as part of https://github.com/GTNewHorizons/BetterQuesting/pull/54.

Please try updating BetterQuesting to [3.0.353-GTNH](https://github.com/GTNewHorizons/BetterQuesting/releases/tag/3.0.353-GTNH) or [later](https://github.com/GTNewHorizons/BetterQuesting/releases/).

**Comment by richj04** [comment]
I tried updating to better questing 3.0.353. This time I crashed attempting to click on a super tank quest from MV (which I haven't completed yet)
[crash-2022-07-03_15.47.14-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9035540/crash-2022-07-03_15.47.14-client.txt)

**Comment by YannickMG** [comment]
[BetterQuesting-1.7.10-3.0.359-GTNH-1-g41c69fc.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9035550/BetterQuesting-1.7.10-3.0.359-GTNH-1-g41c69fc.zip)

Thanks for checking, could you check with this version? I think it should no longer crash, but I'm unsure if it'll be showing the right things. I'm also playing on 2.1.2.0 and haven't had any issues, so I'm not sure what's causing this, or whether there might be issues with your quest database so that reloading it might be beneficial.

**Comment by richj04** [comment]
The problem is fixed, thanks!!

**Comment by YannickMG** [comment]
You're welcome! Just to make sure, your `Super Tank I` quest looks like this (apart from the completion status) ?
<img width="394" alt="image" src="https://user-images.githubusercontent.com/5321549/177058868-672608e2-ffd3-47ec-8e62-1b2fec891fc9.png">

**Comment by richj04** [comment]
Yeah, it looks exactly like that, the problem was just clicking on the quest in the quest lines.
