### ISSUE TITLE
Expanding on less hostile user interfaces

### ISSUE THREAD

**Issue by Connor-Colenso** [GTNewHorizons/GT-New-Horizons-Modpack#10612]
### Your GTNH Discord Username

Colen

### Your Pack Version

zeta latest

### Your Proposal

Add tabs inside GUIs for the following features, this expands on a prior request:
 - Toggle auto-voiding on super/quantum tanks. (Plus GT++ tanks? If this is already implemented there)
 - Toggle auto-voiding on super/quantum chests.
 - Toggle auto-input for super/quantum tanks (hammer click).
 - Toggle input filters based on recipe map for single blocks.
 - Toggle single stack mode for single blocks (Limits each item to only taking 1 stack max).
 - Toggle input filters based on recipe map for input busses/hatches.
 - Toggle auto-sorting for input busses.
 - Toggle allowed input from output side on single blocks.

Additionally: Tooltip on button should tell the user which tool toggles it. Please suggest any I have missed in comments.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Connor-Colenso** [comment]
As per discussion in discord, these are the suggested icons at present. Please feel free to suggest new/better ones.

Toggle auto-voiding on super/quantum tanks. (Plus GT++ tanks? If this is already implemented there)
 - Fluid trash can from ExU.
Toggle auto-voiding on super/quantum chests.
 - Trash can from ExU.
Toggle auto-input for super/quantum tanks (hammer click).
 - Vanilla hopper?
Toggle input filters based on recipe map for single blocks.
 - GT Item filter?
Toggle single stack mode for single blocks (Limits each item to only taking 1 stack max).
 - 64 as text?
Toggle input filters based on recipe map for input busses/hatches.
 - GT Item filter?
Toggle auto-sorting for input busses.
 - Up + down arrow icon?
Toggle allowed input from output side on single blocks.
 - ??

**Comment by minecraft7771** [comment]
Maybe this can be expanded to multiblocks.

- Void excess on GT++
- Seperate Inputs on PA/GT++
- Finally bringing the on/off switch to every multi
- Possible much more

**Comment by YannickMG** [comment]
@Dream-Master Any idea what remains to be done in the original task? A bunch of it was implemented in [2165](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2165).

There's also a lot of suggestions in the comments but no clarity on whether they're desirable. Should new issues be opened instead?

**Comment by Dream-Master** [comment]
@YannickMG lets chat later. To much to write here.
