### ISSUE TITLE
Give Multis Better Error Messages

### ISSUE THREAD

**Issue by realthecaffiend** [GTNewHorizons/GT-New-Horizons-Modpack#10610]
### Your GTNH Discord Username

thecaffiend#2253 

### Your Pack Version

2.1.2.3qf  (Some config changes, no recipe changes)

### Your Proposal

Spending time in the help channel on the discord, one of the most frequent, and difficult to troubleshoot, issues that comes up is: Why isn't this multiblock forming?

Each block has logic to form, and each will be different, and documentation (Especially cross-version) can vary wildly. 

I'd love to see *any* solution to this: A scanner on the multiblock including a line about which check failed? Using the schematic or a new schematic somehow shows which check failed? The multiblock gui showing which check failed? Something, anything, to find out: Oh this multiblock doesn't accept those hatches, or you whiffed the (undocumented) minimum number of casings, or there is no mufflers at -4, -6, 7 or whatever. 

### Your Goal

This is an incredibly frequent question, not just from new players; I've been playing gregtech since it was mostly a lightning rod addon to IC2 and I still swear at my monitor for some multis. 

### Your Vision

Making multiblock formation so much less annoying, especially for rapidly-changing lategame systems. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Savallator** [comment]
This would indeed be very nice, but incredible hard to implement.
It would need to be implemented for every multi seperately, and the structure check code is a real mess most of the time...
In the past i sometimes had a hard time to see the intended structure even when reading the code, and i do know java quite well...
But maybe it could be demonstrated for some multis and then over time patched into the old ones...

**Comment by leagris** [comment]
This type of issue is solved by providing a common API for the structure check where the structure check itself can report the cause of the fail. This can be achieved by having a structure object with not only with a check method but can report the state of the structure in a human readable form.

Doing this incrementally, means older legacy structures will not be able to report the human readable. This can be handled in a wrapper/decorator class to report the already known generic message. Then progressively, structure checks can be upgraded to the new API and have themselves mean to report the structure state in a meaningful description.

One can even imagine the structure object can also report the exact location of what it is expecting, so it can be rendered as an overlay client-side.
