### ISSUE TITLE
Ae2 pattern refill

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#10614]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.4-14-pre

### Your Proposal

Add button to me pattern terminal that will refill empty pattern if you have enough in your systrem OR
make it refill automaticly after new pattern is made

### Your Goal

I think it will be cool, can order 1k patterns and forget about constant refill

### Your Vision

Hello world

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
Actually, why not

**Comment by LewisSaber** [comment]
bot, dont
