### ISSUE TITLE
Botmium

### ISSUE THREAD

**Issue by Phineasor** [GTNewHorizons/GT-New-Horizons-Modpack#10629]
### Your GTNH Discord Username

Phineasor#5220

### Your Pack Version

Latest dev, with most GT related mods from jenkins

### Your Server

Private server

### Your Expectation

be able to make botmium

### The Reality

Botmium uses the wrong form of Ruthenium, it should use the BW version cause the GTPP version gets turned into the BW version when you hold it.

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by xSkewer** [comment]
Something similar happens with Monomethylhydrazine cells which messes up the t5-6 chem plant rocket fuel.
