### ISSUE TITLE
DTPF Recipes non-matching heat requirements with coils heat capacity

### ISSUE THREAD

**Issue by Josh5minus1** [GTNewHorizons/GT-New-Horizons-Modpack#10624]
### Your GTNH Discord Username

A1#8299

### Your Pack Version

2.1.2.4-14 dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

DTPF recipes have different heat requirements, so I decided to put eternal coils in order to do all recipes.

### The Reality

Some recipes can't be created, due to heat requirements higher than the coil heat capacity. The latest zeta has some heat bonus like in EBF. However as updating to latest build to further test the DTPF, the heat bonus was removed, causing the multi to not meet the heat requirements of some recipes. For example, some recipes require heat of 13,600K, however the eternal coil casing has only heat capacity of 13,501 K, causing the recipe to be undoable. Same thing with other coils, they seems to be 99K less than the heat required of recipes.

### Your Proposal

Make the DTPF recipes match the heat capacity of the coils, in order for recipes to be doable. It sucks that eternal coils can't do recipes using 13,600K, due to the coil having capacity of 13,501K, etc. I know that the feature was not final, but this may be a slight oversight.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/330
