### ISSUE TITLE
Railcraft tanks only fills/drains 8000L of fluid cells

### ISSUE THREAD

**Issue by cubic-chariot** [GTNewHorizons/GT-New-Horizons-Modpack#10628]
### Your GTNH Discord Username

cubic-chariot#3803

### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

To be able to fill/empty a fluid cell completely when I manually insert it in the Railcraft tanks GUI.

### The Reality

If I add an empty Large Aluminium Fluid Cell from GregTech (capacity: 32000L) to the top slot of a Railcraft steel tank, for example, the fluid cell will only be partially filled, up to 8000L. If I add a full cell, only 8000L are drained from the cell. This happens with other higher capacity fluid cells, and higher capacity Railcraft tanks as well.

### Your Proposal

Make the cells be completely filled/emptied (assuming there is enough space and fluid of course).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
yes known issue not sure if there will be a fix soon.

**Comment by BritishCynic** [comment]
This is fixed, I have been able to fill and empty large cells of 8000, 32000 and 64000 mB using Railcraft Tanks in 2.2.8. This issue should thus be closed.
