### ISSUE TITLE
Integrated Ore Factory broken again

### ISSUE THREAD

**Issue by GDCloudstrike** [GTNewHorizons/GT-New-Horizons-Modpack#10627]
### Your GTNH Discord Username

GDCloud#2907

### Your Pack Version

2.1.2.4-dev-pre14

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

The integrated ore factory should process my ores like it did before updating gt5u, bartworks and tectech to the latest jenkins versions.

### The Reality

It doesn't turn on anymore. The setup didn't change a single bit.

### Your Proposal

Make it work again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
which patched gt5u do you use? also check the distilled water and lubricant input.

**Comment by GDCloudstrike** [comment]
After updating to todays jenkins build of gt5u the multi started working again, so I consider this issue fixed.
