### ISSUE TITLE
Re-enable the DHD for the stargate

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#10623]
### Your GTNH Discord Username

Lord Peverell#3125

### Your Pack Version

2.1.2.1

### Your Proposal

Re-enable the DHD, no reason for it to not have a recipe and also be hidden in NEI

### Your Goal

Add back the DHD so it can be used to dial the Stargate

### Your Vision

I want to have the authentic feeling of using the Stargate eventually

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Connor-Colenso** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/10625/commits unhides it from NEI at least, recipe will definitely need more work. Open to suggestions.
