### ISSUE TITLE
Spacetime material with Tinker Construct

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#10633]
### Your GTNH Discord Username

AdamR#0072

### Your Pack Version

2.1.2.4-14-pre (zeta current)

### Your Proposal

![image](https://user-images.githubusercontent.com/76914762/177395004-549289be-903e-4f7d-8849-52864eb4692b.png)
Colen told me to make a ticket about this, "briefly" buff this beautiful material tinker construct's stats

### Your Goal

it's supposed to be even beyond infinity like a huge way further considering all the infra it seem to ask for

### Your Vision

would make more sense

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Connor-Colenso** [comment]
<img width="322" alt="Screenshot 2022-07-07 at 14 16 21" src="https://user-images.githubusercontent.com/52056774/177782789-b2d339b2-68ca-488b-aa9c-28be31fade2b.png">
