### ISSUE TITLE
bq_admin reset all <player> isn't persistent through reboot

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10639]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.4-pre14

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

/bq_admin reset all <player> isn't persistent through reboots.

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
i legit deleted `<map folder>/betterquesting/questprogress/<uuid>.json` and ran `/bq_admin reset all <player>`. It's really annoying to not be able to delete quests on a test server, and it would be a mess if a player with a quest reset would get back all his progress (and possibly rewards) after a reboot, leading to possible staff scams.

**Comment by boubou19** [comment]
it is not fixed on 2.2.0.0

**Comment by Aiidoneus** [comment]
Hello,
I am having this issue on my community server. Has anyone been able to get this to work properly? I can test builds in anyone needs. I have some players upset about this

**Comment by minecraft7771** [comment]
Which version do you play on @Aiidoneus?

**Comment by boubou19** [comment]
known bug and it is fixed in dev. Basically we use a new format for the quest progress so when the game starts, it triggers each time the conversion code to the new format, but since we don't delete the old file, each time it reimports the data.

**Comment by Aiidoneus** [comment]
I don't suppose there is a temp way to work around this? Yes, I was on 2.2.0.0. Do I just need to wait for a modpack update? Trying to solve this from a server admin standpoint if that makes sense.

**Comment by eigenraven** [comment]
not easily unless you want to potentially wipe everyone's old quest progress (the solution is to delete the old all-player json file in the world/betterquesting folder, but the new files only contain data since the update and not all data)

**Comment by FloatDoubling** [comment]
There is also related issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12335
