### ISSUE TITLE
recipe to apply fortune on ic2 crops lootbags is overpriced

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10637]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.4-dev14

### Your Proposal

![image](https://user-images.githubusercontent.com/12850933/177408624-5bfe309f-1c8d-425b-82e0-2cf1176de466.png)
![image](https://user-images.githubusercontent.com/12850933/177408639-7b549c71-8588-4be2-9491-c20da21dfc3f.png)

The price of the scanner is way bigger than most of the stuff proposed in the lootbag:
![image](https://user-images.githubusercontent.com/12850933/177408767-410c2ddc-33f2-44fe-b41a-5e555ec6c52d.png)

i suggest to swap the scanner with something like a crop for exemple. The current recipe is a complete scam.

### Your Goal

Avoid being scammed by the game.

### Your Vision

Reduce scam.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ethryan** [comment]
Maybe just use a flower?

Since you don’t seem to get any high tier materials out of that lootbag. Only thing is the 8v solar but I guess that is a rare reward.

**Comment by Chaoschaot232** [comment]
I would suggest to use then any ULV-Tier or LV-Tier ciruit or a Resistor maybe?
A flower sounds to cheap in my eye's

**Comment by POPlol333** [comment]
using circuit for this wouldn't make any sense either though, as a random proposition I propose a plant lens, would both make sense and not be either too cheap or too expensive

**Comment by LewisSaber** [comment]
What about farm block
