### ISSUE TITLE
Missing recipie for "Ring of the Aesir"

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#10634]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

2.1.2.4-14-pre

### Your Server

private mp server

### Type of Server

Vanilla Forge

### Your Expectation

That the RIng of Aesir sould be craftable.

### The Reality

The Ring of the Aesir is not craftable and it seems that Combuster has missed it out to port the recipie in (https://canary.discord.com/channels/181078474394566657/739165604233216042/993966569652756531)

### Your Proposal

Adding the correct recipie or a well balanced recipe so that this item can be crafted.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by EnderProyects** [comment]
The recipe is just joining the other 3 rings in a crafting table

**Comment by Chaoschaot232** [comment]
Normaly it is but referencing NEI it isn't craftable.
