### ISSUE TITLE
New Circuit Lines

### ISSUE THREAD

**Issue by Connor-Colenso** [GTNewHorizons/GT-New-Horizons-Modpack#10636]
### Your GTNH Discord Username

Colen

### Your Pack Version

Zeta Latest

### Your Proposal

Please make recommendations for future circuit lines and mechanics surrounding them in this ticket for devs to utilise for ideas. I.e. new machines for them, fabrication processes, new cleanroom variants etc.

Circuit lines requiring recommendations:

Optical
Exotic
Cosmic
Transcendent

These names/textures can change, any suggestions are welcome.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by henrydukepickle** [comment]
Perhaps the circuits require such precision that they have to be crafted in empty space, so dyson swarm or something similar to get them into space and build them would be required?

**Comment by Alastors** [comment]
We could add a magic based circuit line, it's an idea I've had for awhile, but it would be nice to give the magic mods something else that would give people more of a reason to use them.

I know that's not exactly what you're aiming for, but I thought I'd at least mention it

**Comment by TwoTailedFox** [comment]
Optical Circuits: where light is faster than light inside the circuits, making operation faster. Should use an FTL warp bubble creator in the circuit recipe.

**Comment by henrydukepickle** [comment]
You could also integrate something alike to the W-brain from orionsarm for the later circuits

**Comment by EnderProyects** [comment]
About alastor, we have many magical resources with which to create multiblocks, would one be good that had to support everything at once, essence, vis, blood, mana, and a witchery altar? so you need a whole magical complex to create them.

**Comment by chochem** [comment]
basics:
- use some material exclusive to the DD
- use a material exclusive to the plasma forge

more interesting:
- make an LHC like particle collider (relatively thin but spanning many many chunks,) to make fundamental particles (replacing the COMET in that. not that much chance dependency but heavy need for coolants). then assemble a 'fundamental circuit' from them.

**Comment by Alastors** [comment]
> About alastor, we have many magical resources with which to create multiblocks, would one be good that had to support everything at once, essence, vis, blood, mana, and a witchery altar? so you need a whole magical complex to create them.

also sort of, you don't necessarily need an entire magic complex, everything I listed has decent methods to obtain, it's why I specifically said we shouldn't use essentia, but they would take some dedicated magic infrastructure to fund, and honestly the mana from botania would likely be the easiest of the 3 to fuel within that specific part.

**Comment by leagris** [comment]
Why another circuit line?
The post mention new names and new textures. But it does not tells why there need to be yet another circuit line or why previous circuit lines are not enough.

**Comment by greesyB** [comment]
TecTech has a lot of interesting sounding things in NEI that are not documented, some with recipes (e.g. matter quantizer) some without (e.g. matter collider, wormhole, matter assembler). I have no clue if these are implemented or how they work if they are, but might have some interesting concepts for new lines.

**Comment by chochem** [comment]
> Why another circuit line? The post mention new names and new textures. But it does not tells why there need to be yet another circuit line or why previous circuit lines are not enough.

because we are already using circuits above the bio-mainframe in recipes. nano/pico/quantum are really just placeholders without much to them

**Comment by shitstainlord** [comment]
> At the end of the day, thaum and other magic mods exist to provide an alternative route with proper QoL upgrades, and I believe that my suggestion fuels this concept at it's very core!

No, TC does not exist to provide alternative route, it has a separate progression that does not affect GT progression and it will stay that way. We are talking about higher tier circuits, which start at one step UV circuits and there's no need to make magic required for it

**Comment by Alastors** [comment]
> > At the end of the day, thaum and other magic mods exist to provide an alternative route with proper QoL upgrades, and I believe that my suggestion fuels this concept at it's very core!
> 
> No, TC does not exist to provide alternative route, it has a separate progression that does not affect GT progression and it will stay that way. We are talking about higher tier circuits, which start at one step UV circuits and there's no need to make magic required for it

That's literally what an alternative route is shitstain

**Comment by Alastors** [comment]
> > At the end of the day, thaum and other magic mods exist to provide an alternative route with proper QoL upgrades, and I believe that my suggestion fuels this concept at it's very core!
> 
> No, TC does not exist to provide alternative route, it has a separate progression that does not affect GT progression and it will stay that way. We are talking about higher tier circuits, which start at one step UV circuits and there's no need to make magic required for it

also it literally does, it does this for a metric fuck ton of things, hell thaum power even exists, magic progression has the potential to directly affect GT progression ***THROUGH ALTERNATIVE ROUTES***

**Comment by shitstainlord** [comment]
I know you are a TC zealot but just stop please

**Comment by 98VMS** [comment]
Admittedly I've never actually made anything beyond an IV circuit yet, but I can think of a few ideas for cleanroom upgrades or new multiblocks that could be involved in making the highest tier circuits:

- Faraday cage, in order to prevent outside interference from damaging the sensitive circuit components. Perhaps have it work very similarly to the cleanroom. In fact, perhaps even make it have to go inside the cleanroom -- this would force you to have a pretty big cleanroom in order to fit another multi inside of it.
- Some sort of machine to nullify static electricity inside the cleanroom, or maybe just some sort of special suit or rubber gloves or something.
- A vacuum chamber, similar to someone else's idea from above about making circuits in space, but I think this just makes more sense. As an upgrade of a cleanroom you could have some room that's a complete vacuum (requiring constant power input to keep pumping out the air that gets in from any leaks), and maybe you'd need Galacticraft oxygen gear inside of it? No idea if that's even possible, but if not, perhaps a 'glovebox' machine or multi that you don't go inside of could replace this.
- Microscopes and stuff. Honestly aside from the precision laser engraver, I don't really get the vibe that making circuits involves any sort of nanoscale engineering when it probably does and should. Maybe instead of just putting different colored lenses into the precision laser engraver, some sort of machine should be used to create blueprints/schematics/patterns that you put into the laser engraver.

**Comment by EnderProyects** [comment]
Well, I have tell this points to Alastors in private but I will post theme here:

-The essence could be used as a working gas inside a clean room so as not to damage the circuits or something similar.
-The wand focus and the mana lens can be lenses for laser engravers and somehow use the mana or vis as a laser (with a multiblock or similar).
-The various fluids of thaumcraft and the blood of blood magic can serve as welders.
And for the witchery apart of using some materials the spinning wheel could be used to create some magical wire ( with some speed upgrades) ( or add some multiblocks for witchery)

**Comment by shitstainlord** [comment]
Can we please mark magic suggestions as off-topic? kthx

**Comment by EnderProyects** [comment]
> Can we please mark magic suggestions as off-topic? kthx

Why is not off-topic, but could magic haters stop shiting about others ideas? Thanks uwu

**Comment by Chaoschaot232** [comment]
It would be glad if both sides are not going to poke each other.
If you have ideas or anything else which are helping the OP with his suggestion then anything is welcome.
But please be fair and discuss any idea with a constructive argument, thanks :)

**Comment by Jonodonozym** [comment]
I think I saw someone on the discord suggest a tier where circuits require a Matryoshka Brain to be made; sort of like a dyson sphere / swarm except the energy is used entirely for computation. You could launch the components using the existing dyson swarm multi, and add a new "Matryoshka Brain Uplink Terminal" multi which lets you assemble uplink processors for the circuit tier so long as you have >x Brain modules orbiting the sun.

**Comment by Glease** [comment]
Let's don't get into stellaris scale this fast.

---
Magic circuits will probably mainly be used for magic constructs. When it's used for tech stuff it will probably be tiered down by one or more (e.g. T1 magic as ULV circuit), depending on how expensive/complex/hard we made it.

However, I'd like to leave this to the other day, probably in its own RFC. Colen here need more advanced circuits for the very end game he envisions. The need of these are real as to solve the end game basic material spam issue we currently have. Magic restructure can wait until someone on the team pick it up.

**Comment by GTNHAfx237v7** [comment]
Please no more recursion….

**Comment by Alastors** [comment]
> Let's don't get into stellaris scale this fast.
> 
> Magic circuits will probably mainly be used for magic constructs. When it's used for tech stuff it will probably be tiered down by one or more (e.g. T1 magic as ULV circuit), depending on how expensive/complex/hard we made it.
> 
> However, I'd like to leave this to the other day, probably in its own RFC. Colen here need more advanced circuits for the very end game he envisions. The need of these are real as to solve the end game basic material spam issue we currently have. Magic restructure can wait until someone on the team pick it up.

I'm honestly fine with that, given that it leaves room for more new magic multis in general, we could have the same effect if you try to use normal circuits on magic multis and we could explain it with some bs like "Oh they are sort of incompatible so you need to use more advanced circuitry for the same effect if you're trying to merge tech and magic"

And likewise, yeah it likely will be a bit until that can all get started.

> Can we please mark magic suggestions as off-topic? kthx

I will mention though, colen told me to put the magic circuit line ideas here, and I later reconfirmed that's what he meant, which it was, so kindly fuck off shitstain.

**Comment by Logos-Askrson** [comment]
I'd suggest, if you're looking for ways to make new tiers of circuits satisfying rather than just being another item with a new image and the tier incremented, looking into ways to change how the circuits are used. I've a few examples:

Suppose starting in LuV, you got access to a line of plasma circuits, quite expensive compared to normal circuitry with a heavy emphasis on high-power magnets, which can be used to craft an alternative line of machines using them which require plasma as an input to run but take much less energy, potentially allowing 2-3 tiers of additional overclocking. Later in the tier, or perhaps starting in the next tier up, plasma machines replace conventional ones, making full use of plasma as a computational medium. Later still, you might start getting photon plasma circuits, requiring a more advanced plasma that's high-energy enough that photon-photon interactions become computationally useful.

Or perhaps you could make singularity chips, hypothetical single-use computers created by encoding information and instructions into matter that is collapsed into a black hole, such that the answer to your computation can be read in the hawking radiation given off as it decays. In-game, these would be consumables taken in by the machine with each operation, possibly making use of the existing singularity items as components.

Hopefully this helps spark some ideas.

**Comment by Alastors** [comment]
I like your moxie, but I don't like the cut of your idea. I genuinely believe it should be a new magic multi, or multis.

It shouldn't be gated late game, it should be available when thaum and other magic mods are.

It shouldn't be thaum-specific like this is.

It shouldn't use mob sourced materials such as zombie brains which are specifically only generated from zombie types, materials should be accessible without entities.

All magic mods should have options (except witchery) for producing materials for the circuits.

It shouldn't use Iron (III) chloride.

The animation powder is an interesting proposal.

We already have a research minigame from Thaum, don't use the GT research.

Don't use Draconic Evolution for any of it, while you can make your argument about it being a magic mod, in the context of GTNH magic, it is not.

The concept of it using some machines from GT is a good proposal, but it shouldn't be the bulk of magic circuit creation, magic circuit line should feel like it's something never done before, new, not just another kevlar line clone.

And this is probably shocking, but I genuinely don't like the idea of infusion being part of the magic line if avoidable, at most I think it should be part of the upgrade cluster line I suggested above, but until someone makes a method to automate infusion within it's own multi, I don't think it should be part of a GT specific line.

**Comment by Alastors** [comment]
> Combining circuit and magic into a thing is creating an Frankenstein oxymoron.
> 
> Magic usually refer to mind blowing technology so advanced it cannot be understood.
> 
> An electronic circuit designs something with very known underlying technology.
> 
> So having a magic circuit is non-sense. Maybe you want a Magic Circus?
> 
> * Nobody is asking for it.
> * Nobody needs it.
> * Its naming does not make sense.
> * And it is a solution waiting for a problem to solve.

This is a waste of breath, magic in this context is referring to the *magic* mods of GTNH, not specifically the concept in human language.

**Comment by mitchej123** [comment]
I'd love to have a "magic line" of circuits as an alternative to the strict tech lines.  I think they'd both work nicely side by side and give some more choice.

**Comment by mitchej123** [comment]
> Look at this magical botania/thaumcraft/whatever rune that's running my macerator!  Awesome

**Comment by Alastors** [comment]
> magic should really be considered off-topic here Progression of magic is separated from GT, it's possible to get to endgame without touching magic, so I don't see why late endgame it should become required.

1st off, the magic circuit line shouldn't be considered off topic here, this is a ticket about new circuit lines

2nd off, Colen specifically wanted the magic circuit line here, I asked him if I should put it on another ticket or whatever, so no it shouldn't be considered off topic

3rd off, I agree, it shouldn't be required, read through my proposal for the magic circuit line, and you'll see that all throughout it I say it should be specifically optional, magic circuits shouldn't be the endgame circuits. They should be an optional route.

Get out of here with the "magic shouldn't be here" nonsense, that point has been thrown out the window for awhile now.

**Comment by mitchej123** [comment]
> magic should really be considered off-topic here Progression of magic is separated from GT, it's possible to get to endgame without touching magic, so I don't see why late endgame it should become required.

I disagree that it's off topic, it's explicitly on topic per my reading of the initial prompt: `Please make recommendations for future circuit lines and mechanics surrounding them in this ticket for devs to utilise for ideas. `

Now I do agree it shouldn't be required to get to endgame, but I see little reason not to offer a magic alternative.

**Comment by chochem** [comment]
> > magic should really be considered off-topic here Progression of magic is separated from GT, it's possible to get to endgame without touching magic, so I don't see why late endgame it should become required.
> 
> I disagree that it's off topic, it's explicitly on topic per my reading of the initial prompt: `Please make recommendations for future circuit lines and mechanics surrounding them in this ticket for devs to utilise for ideas. `
> 
> Now I do agree it shouldn't be required to get to endgame, but I see little reason not to offer a magic alternative.

before it got derailed this thread was supposed to be about the new endgame circuits after wetware and bio. These are currently named optical, exotic, cosmic, transcendent (see initial prompt). It was not about alternative circuits.

**Comment by mitchej123** [comment]
> before it got derailed this thread was supposed to be about the new endgame circuits after wetware and bio. These are currently named optical, exotic, cosmic, transcendent (see initial prompt). It was not about alternative circuits.

![image](https://user-images.githubusercontent.com/1894689/178368028-3cfc38cb-d960-4124-bf7d-7821004cc707.png)

Please show me where, in the OP, it says end game only?

**Comment by shitstainlord** [comment]
Well, I did try to warn you guys before it devolved into magic circuit discussion lol

**Comment by Alastors** [comment]
> Well, I did try to warn you guys before it devolved into magic circuit discussion lol

fuck off shitstain, your commentary isn't necessary

**Comment by combusterf** [comment]
> before it got derailed this thread was supposed to be about the new endgame circuits after wetware and bio. These are currently named optical, exotic, cosmic, transcendent (see initial prompt). It was not about alternative circuits.

It is *not* a derail, and apparently I have to repeat my earlier post to explain why: I like the idea that a post-infinity endgame exists where all mods come together in a grand finale. That would thus includes the magic mods, and circuits could well be the vehicle. Magic-enhanced circuits are also lore-wise an effective way to surpass the limitations of our earthly reality.

Of course the suggestion could also be repurposed into a parallel circuit line, but then that scheme as-is would be way too expensive.

**Comment by Alastors** [comment]
> > before it got derailed this thread was supposed to be about the new endgame circuits after wetware and bio. These are currently named optical, exotic, cosmic, transcendent (see initial prompt). It was not about alternative circuits.
> 
> It is _not_ a derail, and apparently I have to repeat my earlier post to explain why: I like the idea that a post-infinity endgame exists where all mods come together in a grand finale. That would thus includes the magic mods, and circuits could well be the vehicle. Magic-enhanced circuits are also lore-wise an effective way to surpass the limitations of our earthly reality.
> 
> Of course the suggestion could also be repurposed into a parallel circuit line, but then that scheme as-is would be way too expensive.

I will mention, as I've noted before, the entire consensus between most of the devs interested, even non-devs like me, is that magic mods should stay the hell out of main progression. 

Yours is a good idea, but it's just not going to happen, the player base would absolutely lose their shit if magic was required all of a sudden end game, and as such, it's just not realistic in scope and there's no way it'll get through.

They really should just be a magic-based alternative, not late game, but available as soon as you can start magic in general.
Slightly OP for magic machines, and tier-1 for everything else, vice versa with normal gt circuits on magic machines.

**Comment by chochem** [comment]
so here is another idea for Colen for a mechanic that could be explored for future circuit production (or other new technology):

what if 'Computation' from the Quantum Computer actually had more uses than just the research station. How about a circuit (part) recipe that needs a constant supply of computation for the recipe. This could be seen as 'configuring'/'programming' the circuit, or maybe its an abstract scifi purely *information based* circuit.

To implement that you would ofc either need a new multi, or at least a hatch for AL/CAL/precass to do it there.

**Comment by combusterf** [comment]
That reminds me of the mechanisms of the https://hitchhikers.fandom.com/wiki/Infinite_Improbability_Drive which is known for being able to calculate things into existence.

**Comment by Alastors** [comment]
> so here is another idea for Colen for a mechanic that could be explored for future circuit production (or other new technology):
> 
> what if 'Computation' from the Quantum Computer actually had more uses than just the research station. How about a circuit (part) recipe that needs a constant supply of computation for the recipe. This could be seen as 'configuring'/'programming' the circuit, or maybe its an abstract scifi purely _information based_ circuit.
> 
> To implement that you would ofc either need a new multi, or at least a hatch for AL/CAL/precass to do it there.

so basically a crypto-miner to make circuits :kekw:

**Comment by Lapinwarrior** [comment]
Idea: Matrix. Currently the "Best" circuit is Bioware: putting neurons in a circuit, but neurons are cell-sized, but what if they were smaller? Transistors in a computer are 14nm while neurons are 0,004 mm at their smallest (That is ~286 times bigger!), That is where matrix comes into play, imagine a neuron-like component made of a Extremely-High-Speed conductor which is Ridiculously small. It could be made in batches of thousands, then layered to make some kind of Matrix-Ware circuit, it would also be fitting with the "Matrix" term, a neuronal matrix perhaps? Also it would maybe be in the "exotic" tier?

I am not an expert in any of the subjects you talk about, but i have one hell of a imagination!
