### ISSUE TITLE
Several multiblock textures broken in 17-pre

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10648]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-17-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

-

### The Reality

LCR, MCR, TFFT, Research Completer, Void miners, infinite drilling rig, ...
all look like this in NEI:
![image](https://user-images.githubusercontent.com/40274384/177626865-a9700007-9d58-45fc-993e-658b1b4ecd94.png)

and like this in-world:

![image](https://user-images.githubusercontent.com/40274384/177626914-a249a9b0-6ffe-4528-a217-d954e7a937f9.png)

happens with or without texturepack.

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
apparently caused by this PR: https://github.com/GTNewHorizons/GT5-Unofficial/pull/1106
steelux and dream seem to know about it.

**Comment by boubou19** [comment]
specifically https://github.com/GTNewHorizons/GT5-Unofficial/pull/1106/files#diff-98c7a286610eb2ec96721c23bedfb5d039db1b6fe0d4430b37fd3d5f76abf639R25
