### ISSUE TITLE
magnesium dupe

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#10646]
### Your GTNH Discord Username

tom#6482

### Your Pack Version

GTNH-1.7.10-2.1.2.4-17-pre.zip

### Your Server

sp

### Your Expectation

no easy dupes of metals

### The Reality

![image](https://user-images.githubusercontent.com/8298646/177600407-abcd3b58-9dcc-4f0b-9f35-cbf0bacada45.png)
![image](https://user-images.githubusercontent.com/8298646/177600438-e054c0c3-be80-4745-99c0-974b7748cb7a.png)
![image](https://user-images.githubusercontent.com/8298646/177600459-1d07c7ea-e7f4-47a0-9f29-1e8a2134bd26.png)

### Your Proposal

remove magnesite smelt or remove the recipe for making it (must be carefull that it musn't be required in any chain)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
yeah the smelting would need to be 1->1/5 to make sense after the chem standardization. I guess at best it can make a nugget but its not great.

**Comment by Dream-Master** [comment]
@GlodBlock

**Comment by GlodBlock** [comment]
magnesite smelt will be removed as temportory solution, considering you can electrolyze it to get magnesium back

**Comment by GlodBlock** [comment]
fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/1062
