### ISSUE TITLE
iTNT and TNT quests ask for differing Toluene amounts, but same amount of Gelled Toluene

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10647]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Because both quests call for 256 Gelled Toluene, both quests should initially list 26 Toluene Cells

### The Reality

The TNT quest correctly lists 26 Toluene Cells, but the iTNT quest incorrectly lists 18 Toluene Cells

### Your Proposal

Alter the iTNT quest to properly ask for 26 Toluene Cells in the first part of the quest

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
This is obsolete because of optional tasks. You don't need to hold Toluene to complete the quest in 2.1.2.4-dev.
