### ISSUE TITLE
Insane Blood Magic LP production

### ISSUE THREAD

**Issue by GTNHAfx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#10656]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.4dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Posted today in #tips-and-tricks:

Category: Blood Magic - Generating Blood
Tier: Tier 6 altar, ZPM+

Tip: Get 4 pieces of primordial armour (as the instant health stacks to make it level 5 instant health). Get a glass dagger, 121 self sacrifice runes, 7 speed runes, some orb runes, some superior capacity. An eldritch Orb.

Make a ritual of the feathered knife and put a 16x(maximum it can receive) WA on it. LuV WA on the altar. Encase yourself and use a dynamism table on a timer of 9 secs to hit you. Use glass dagger with an autoclicker(50 miliseconds between clicks seems to be perfect for no death). 

Generate around 2M LP a minute.

### The Reality

Sounds seriously broken. Also looks to me like a heavy impact on tps.

### Your Proposal

Adjust?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
Honestly I would rather players did this than spam witches/other random mobs under their ritual that lag 24/7, not that either situation is ideal.

**Comment by chochem** [comment]
guess I should actually try to do this myself
