### ISSUE TITLE
GT Pipes and Cable blocks get corrupted after attaching AE2 Cable Facades

### ISSUE THREAD

**Issue by Evuflow** [GTNewHorizons/GT-New-Horizons-Modpack#10652]
### Your GTNH Discord Username

Evuflow#9718

### Your Pack Version

2.1.2.3qf

### Your Server

Single

### Type of Server

Single Player

### Your Expectation

Expectation should be that each GT Pipe and Wire should keep their Cable facades when reloading the game.

### The Reality

When placed there is no issue, however when reloading the game after closing it, all the Pipe and Wire blocks with AE2 Facades have been replaced with a block called .name and no skin.

I think some NBT data still exists because walia still knowns which tool to use to disconnect the block.

This is very annoying if you have pumps/conveyors also attached to the same block as they become unrecoverable.

![image](https://user-images.githubusercontent.com/93747198/177769514-520d8984-0eb2-4a58-a2f6-a03efadcb92c.png)

### Your Proposal

Fix what is causing the corruption.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
fixed in dev already
