### ISSUE TITLE
Add Extractor recipes for Hardened Clay -> Clay balls

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10669]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.4-18-pre

### Your Proposal

Add Extractor recipes for Hardened Clay (and al coloured clay variants) to get 4 Clay Balls per Block (same as the normal, wet clay blocks)

### Your Goal

To enable additional uses for Hardened Clay

### Your Vision

To ensure that additional clay is not needlessly difficult to come by.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by YannickMG** [comment]
Why would squeezing hard clay through metal make wet clay?

**Comment by chochem** [comment]
just crush it for the dust and then mix it with water. This is already in the game. It's just one step more than your suggestion.
