### ISSUE TITLE
errors in chat on startup in dev17

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10663]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-17-pre

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

.

### The Reality

![image](https://user-images.githubusercontent.com/40274384/177993447-8b3019bd-7d73-45b0-ab17-ddb1f0b188e9.png)

that basalt error started in dev14. the other one is already happening longer.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
both are still around on dev25

**Comment by Dream-Master** [comment]
need to check mt script
