### ISSUE TITLE
The Quantum computer quest and the parametrizer quest need fixing and improving

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10672]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-18-pre

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

The quest should be accurate, informative, and helpful. The QC is complicated :P.

### The Reality

These quests leave out a few key things and have some inaccuracies.

### Your Proposal

Change the text to the text below. Let me know if you have comments to improve it further!

**Summary of the main changes**: explanation for bottom row of Parametrizer, non-integer values for Parametrizer, improved id explanation, fixed maxheat description for QC, how to make the QC bigger and that you can chain them, removed the remark that Parametrizer is useless, made it clear that the setup here is just an example and that better setups might exist. pointed to wiki for stats.

**Quest 2683 'Configure TecTech Multiblocks':**

The Parametrizer allows you to configure TecTech multis by adjusting the numbers. There are 3 different versions. Let us focus on the basic one.

If there are lit up sections in the Parameters part of the multi interface (see the TecTech Multiblocks quest), you can configure the multi, otherwise the block does nothing.

We'll be using the Quantum Computer as our example, since that's what you probably want it for.

First we need to understand the parameter naming, like ID:0:1:I. The first number represents the parameter block. For the QC only block 0 is used. Each such block can have up to 4 used parameters, 2 inputs and 2 outputs. The letter at the end specifies if its an input or output with I or O and the number in the middle distinguishes the 2 parameters of this kind in the block. It is either 0 or 1.

Inputs are something that is either set by the Parametrizer, or is the default. Outputs give information that the machine sends to you, that indicates things. (like heat or computation power)

In the Parametrizer's interface, the outputs are marked by a down arrow, while the inputs are indicated by an up arrow. Around that you can find 16 buttons. The outer 8 just change things by a larger quantity, as does shift clicking. So let us focus on the inner 8.

In the first row we can change the parameter block to look at or change. For the QC only 0 is relevant, so change it to that.

The next to rows now allow us to change either the first or the second input parameter in this block by -1/+1 per button press. You can see in the QC controller GUI that the first input parameter is the overclock ratio, while the second is the overvoltage ratio.

The bottom row is where the binary nature of the Parametrizer really shows. It lets you multiply the parameters by 2 or divide them by 2. However: it changes both of them together! So if you want different values you will have to change things in the second and third row. Despite what the TecTech wiki claims, being able to divide by 2 also allows you to set non-integer values for your OC and OV ratio!

**Quest 2007 'Quantum Computer':** 

One of the most incredibly complicated machines, this will serve as the main structure for your Computation generation for the Research Station.

First, you'll need a few things: the Quantum Computer itself, the Uncertainty Resolver, some good circuits and the Computer Racks to hold them, and at least a UV energy hatch (maybe start with a UV 4A energy hatch). The QC will consume 1A of UV, and each rack will use one more. So another important factor is to ONLY turn on the Quantum Computer once you have the desired recipe for the Research Station ready to avoid excess energy loss. Remember to turn the QC on BEFORE the RS. In order for you to build this absolute monster, you'll need to place down the Quantum Computer at least 1 block above the surface/ground and use the Multiblock Structure Hologram Projector to see where to place everything. The blocks with no dots next to the vents indicate that that space must be empty. Later you'll want to build a bigger QC. Use a stack of multiple Hologram Projectors to see how that is build. If at some point even a maximum size QC with 24 racks is no longer sufficient, you can also chain multiple QCs. For now, let us focus on a basic setup.

Uncertainty Resolver:
A mini-game that might take you a bit to understand. Your goal is to balance the lights around the focal points. Sometimes, the Schrödinger Status will require some puzzle solving again after a period of time. This is random and incredibly frustrating, especially during operations being done between the Research Station and Quantum Computer(s), so it is important to constantly check the Uncertainty Resolver before you start operations on your Computer. If the puzzle looks too hard or you can't complete it, just remove it and the controller and re-place them to get a different puzzle.

Computer Racks:
The main component within the multiblock to generate Computation. In order to achieve this, you will need to input some circuits and ic2 heat vents; Advanced Heat Vents work best. It is critical that you use Heat Vents to prevent the heat from reaching a catastrophic point. Computer Racks will always melt or explode about 9000 heat (also written as 90%, 10000 being 100%) but most circuits have much lower thresholds. For our example here we will use Ultimate Crystalcomputers. With these, any heat above 54% should be avoided for safety reasons! The maximum heat will be different for different circuits, even if they are of the same tier. You can see the heat for individual Racks by scanning them. You cannot remove or input components until the heat is gone. You can see the overall heat value in the controller's interface. And most importantly: DO NOT WRENCH THE COMPUTER RACKS IF THEY HAVE HEAT IN THEM. Otherwise, you're going to get an explosion.

Computation:
Computation is generated every second and is based on the tier of your circuit. There are, however, differences in between how much computation is generated, even with the same exact tier. For instance, you could use a Master Quantum Computer (Quantum Circuit Series / LuV) or a Wetwareprocessor (Wetware Circuit Series / LuV) which will give you more Computation even though they are of the same tier. If you wish to find out exactly how much Computation a circuit gives; place down a Computer Rack, put a circuit inside and scan it. You can also see the total computation in the controller.

It will include the following information.
Base computation:
After overclocking: same as above unless you specially overclock it
Heat Accumulated: based on circuits and heat vents, keep a watchful eye on this part as it's extremely important

You can find an overview of circuits with their maximum heat and Computation values on the GTNH wiki.

Using the Parametrizer you can overclock and overvolt the QC, but we won't do so for our example setup here.

Sending Computation to the Research Station:
Use the Optical Master Connector in one of the variable spaces on the QC, and the Optical Slave Connector on the RS. Use Optical Fiber Cable to connect them, and make sure to paint all three.

Example Setup:
Now that you've understood the concepts and safety of handling of the QC, what are the more optimal setups for your Quantum Computer? For now, I'll suggest 2 racks with 3 Ultimate Crystalcomputers each, and of course 1 Advanced Heat Vent each. This gives you 156 C/s and will get you started with some recipes in the Research Station. This is a rather minimal setup though, you should probably think about more optimized (or just larger) setups later!

Now that you understand the QC, it's time to build it! You'll need to gather quite a lot of resources.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Maybe when explaining that for chips of the same tier but different quality the max heat increases just like the computation.

**Comment by chochem** [comment]
> Maybe when explaining that for chips of the same tier but different quality the max heat increases just like the computation.

done. I also added a line that the stats can be found on the gtnh wiki.
