### ISSUE TITLE
Quest "Minecart" bugged

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10671]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The quest should track when a Minecart is transferred from an Assembler to the player's inventory.

### The Reality

The quest only tracks if a Minecart is made in a crafting table.

### Your Proposal

Alter the quest so that the Assembler option is available to complete the quest.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
its a crafting task in the early game (stone/steam age). Dreammaster wants those to stay and so they are staying.
