### ISSUE TITLE
Eliminate the 50:50 possibility in LootGame's Minesweeper

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#10678]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

2.1.2.4-14-pre

### Your Proposal

Minesweeper is a nice game but I never encountered so many time a 50:50 chance which is pre-defined which should never be happen. Instead they should accept all given solutions as they are solvable in at last two ways.

Example:

![image](https://user-images.githubusercontent.com/1703441/178133120-dd40ca29-0e93-49fd-85d8-70120fad3339.png)
![image](https://user-images.githubusercontent.com/1703441/178133127-1f08f901-5149-4fbc-a864-c8782e61d0cc.png)

You can clearly see that the game can definitly ignore what field I choose to be a mine or not a mine but nope it is in a hidden state definitly pre-defined and this sucks -.-

### Your Goal

Remove every 50:50 possibility or add a check against them and accept every given valid solution.

### Your Vision

Make every Minesweeper field solvable and not ending up in a 50:50 pain where you are hitting most time the mine.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
@Chaoschaot232 if you not solve the issue with your own pr please let the triage tag enabled.

**Comment by Buggy123** [comment]
I agree, this is quite a annoying issue. I was going to make a report for it myself. A skill-based challenge shouldn't have a arbitrary element of RNG, especially with limited lives.

By my understanding, the general solution for preventing this is implementing a solver which tries to solve the board and generates a new one if it encounters this situation. There's more info over on [Stackoverflow](https://stackoverflow.com/questions/8304982/generate-a-minesweeper-board-which-doesnt-need-guessing).

**Comment by leumasme** [comment]
Note that if this is implemented without further changes, Lootgames Minesweeper will likely be immensely easier to win than Sequence; should probably consider how to rebalance the two (and in which direction; Minesweeper harder or Sequence easier?).
Sequence easier: Shorter Stage 4 / Less rerandomization
Minesweeper harder: Time limit? Increasing mine density can only increase the difficulty by so much without getting ambiguous (50/50s).
