### ISSUE TITLE
Crash when using Voxelmap and scanning veins with Prospector's Scanner

### ISSUE THREAD

**Issue by qazxcdertgb1** [GTNewHorizons/GT-New-Horizons-Modpack#10670]
### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Your Actions

When using Prospector's Scanner to add vein waypoints to Voxelmap, the the game may crash. Test with IV level.
mods:Voxelmap-1.7.0b-liteloader, visualprospecting-1.0.28, no other minimap

### Crash Report

[crash-2022-07-09_12.30.16-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9076007/crash-2022-07-09_12.30.16-client.txt)
[crash-2022-07-09_14.24.40-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9076011/crash-2022-07-09_14.24.40-client.txt)
[crash-2022-07-09_14.42.46-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9076009/crash-2022-07-09_14.42.46-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
