### ISSUE TITLE
Poly SI block and nickel aluminide block all entangled and mixed up

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10683]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-18-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

silicon and silicon. nickel aluminide is nickel aluminide.

### The Reality

its all weird

- my europium (EU) boule recipe in NEI suddenly needs nickel aluminide blocks
- nickel aluminde blocks have the color of poly SI solar grade silicon
- poly SI solar grade silicon blocks have the color of nickel aluminde
- the ids are also swapped

pics:
silicon:
![image](https://user-images.githubusercontent.com/40274384/178165069-8e7c7372-c4eb-42c9-989b-024abb19b2e1.png)
![image](https://user-images.githubusercontent.com/40274384/178165087-a33e7ddc-f2df-4ed4-b42f-46d862f4f799.png)
![image](https://user-images.githubusercontent.com/40274384/178165092-4fc624c2-cb78-4fa9-83ad-779296eba0b4.png)

nickel aluminide:
![image](https://user-images.githubusercontent.com/40274384/178165102-c1e0a801-4712-405f-8f33-798d69d6e2ad.png)
![image](https://user-images.githubusercontent.com/40274384/178165109-7b71a9cf-e86d-492e-bb84-4ca1a2458766.png)
![image](https://user-images.githubusercontent.com/40274384/178165112-51a74af7-33fd-4b82-98d9-7abfb757542f.png)

### Your Proposal

fix it,

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
bonus picture that should explain the problem pretty well:

![image](https://user-images.githubusercontent.com/40274384/178165487-f46230de-60a5-46aa-8b1c-eefc75aa9f14.png)

Colen and Manii also found the same problem in their instances.

**Comment by xSkewer** [comment]
Happened to me as well, but on dev-14. Had to repattern my naq boules because of it.

**Comment by chochem** [comment]
talking with some other people this very like shifted between dev5 and dev14
