### ISSUE TITLE
The village generation is weird

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/GT-New-Horizons-Modpack#10689]
### Your GTNH Discord Username

mini_ben#0027

### Your Pack Version

2.1.2.4-18

### Your Server

SP

### Your Expectation

full generation

### The Reality

seed: 1484143766554798585
![2022-07-12_06 17 48](https://user-images.githubusercontent.com/48137054/178470447-14762c13-77fb-4f8e-96cd-36faebc60323.png)
seed: 5436816742697180545
![2022-07-12_05 41 33](https://user-images.githubusercontent.com/48137054/178470759-38b7dddd-1d64-4e0e-ae9d-515ec0456d0a.png)

### Your Proposal

identify and fix it if possible

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bjin2000** [comment]
Update: The village generation works well in 2.1.2.3qf.

**Comment by bjin2000** [comment]
Update2: The BugTorch > 1.1.2 breaks the village generation. The version of BugTorch in 2.1.2.4-18 is 1.1.6.2.
Issue: The entire village is covered by the path, some of which have replaced roofs.

**Comment by Dream-Master** [comment]
@jss2a98aj any idea how to fix that ?

**Comment by jss2a98aj** [comment]
Turning "fixVillagePathsHavePlantsOnTop" in the BugTorch mixin config should stop that if it is something in village path generation breaking.

**Comment by bjin2000** [comment]
@jss2a98aj Setting "fixVillagePathsHavePlantsOnTop" to false solved the problem. Also, I found "fixVillageWellDesertMaterial" didn't work.
![2022-07-15_14 52 29](https://user-images.githubusercontent.com/48137054/179336564-d273ed83-aae6-4788-8a4b-b27a78837ef7.png)
Is it better to wait for a fix or to temporarily set "fixVillagePathsHavePlantsOnTop" to false by making a pull request? The certificate for "maven.mcmoddev.com" has expired, so I can't build and run this mod.
