### ISSUE TITLE
Coke Oven Brick incorrect status

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#10685]
### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

Coke Oven Brick to display correct status

### The Reality

After coke oven brick runs out of wood, it's visual display still keeps animating as if it is still processing wood. This makes it difficult to track if everything works as expected. You have to manually check every coke oven brick.

### Your Proposal

Fix display to stop showing processing if wood runs out.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@nikitinalexx please check with 2.1.2.3qf or 2.1.2.4-dev version

**Comment by Gateswong** [comment]
> @nikitinalexx please check with 2.1.2.3qf or 2.1.2.4-dev version

Both versions you mentioned have the same problem.

**Comment by boubou19** [comment]
i have the exact inverse situation: my coke oven doesn't light up despite having fuel running in it
![2022-07-30_11 51 40](https://user-images.githubusercontent.com/12850933/181905094-765bfea1-6814-4958-b05f-8165bf0d66db.png)
![2022-07-30_11 51 43](https://user-images.githubusercontent.com/12850933/181905095-67575eb0-6a3d-4fe5-8aae-6392dba15a3b.png)
