### ISSUE TITLE
Add compatability to the ME interface to accept the ore dict filter

### ISSUE THREAD

**Issue by stlchase40** [GTNewHorizons/GT-New-Horizons-Modpack#10684]
### Your GTNH Discord Username

stlchase40#7583

### Your Pack Version

2.1.2.2

### Your Proposal

I think it would be an improvement to add compatibility to the ME interface to accept the ore dict filter card. It would work by filling its inventory with items from the system that fit the matching filter.

### Your Goal

Interfaces can export like infinitely fast this way if the player uses a conveyor on the input bus. Export busses are slower and dont export full stacks like interfaces do.

### Your Vision

It would make instant I/O of the ME system easier, and help with ore-processing.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNHAfx237v7** [comment]
Sounds like another reason for an ME input bus -  no need to transfer between AE and a multiblock via conveyors or similar.

**Comment by joshaup1999** [comment]
Would need a GUI to fiilter things or add cards
