### ISSUE TITLE
Another loop to turn water to hydrogen and oxygen very cheaply

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10691]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-18-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

there no such chemical loops used as hydrogen production, so I dont think this is intended.

### The Reality

Sodium Burn: 1Na + 1000 H2O -> 3 NaOH + 1000 H, 400EU
Make carbonmonoxide: 1000L O + 1 C -> 1000L CO, 280EU 
Make Sodium Formate:  1000 CO + 3 NaOH -> 1000L  HCOONa, 450EU
Make Formic Acid: 1000L HCOONa + 500L H2SO4 ->3.5 Na2SO4 + 1000L CH2O2, 225EU
Electrolyze Formic Acid: 1000L CH2O2 ->1C + 2000L O + 2000L H, 6480EU
Sodium Sulfate reprocessing: 1000L H + 3.5 Na2SO4 - > 1 Na + 500L H2SO4, 450EU

total: 1000 H2O -> 2000L H + 1000L O for 8285EU (electrolysis needs 60000EU)

### Your Proposal

The easiest place to nerf might be the 'Electrolyze Formic Acid' step. So I would just propose doing that.

------------
However I should point out that some chemist (I think) on discord say its the sodium sulfate reprocessing that should be nerfed instead as that is not a thing that actually works apparently. If the nerf goes via that keep in mind that the above only uses half a recipe so 120 kEU or so would need to be added there and also keep in mind that there is a second route to reprocess the Sodium sulfate by electrolyzing the it and making sulfuric acid from sulfur, water and oxygen. that second route would also need a nerf then.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
what is the recipe suggestion for "Make Formic Acid" @chochem

**Comment by chochem** [comment]
my suggestion would be to just add 60kEU to 'Electrolyze Formic Acid'. That is the easiest route balance wise.
But I am not a chemist.

**Comment by Alastors** [comment]
I'd like to mention, I mentioned something similar to to the sodium sulfate processing mentioned here in my ticket about adding a new recipe for sodium bisulfate:

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9909

**Comment by chochem** [comment]
so after I got some explanation on discord, I think the last comment is about the following:

Sodium Burn: 1Na + 1000 H2O -> 3 NaOH + 1000 H, 400EU
Make carbonmonoxide: 1000L O + 1 C -> 1000L CO, 280EU
Make Sodium Formate: 1000 CO + 3 NaOH -> 1000L HCOONa, 450EU
Make Formic Acid: 1000L HCOONa + 500L H2SO4 ->3.5 Na2SO4 + 1000L CH2O2, 225EU
Sodium Sulfate Electrolysis: 3.5 Na2SO4 -> Na + 0.5 S + 2000L O, 1035EU
make Sulfuric Acid: 500L H2O + 1500L O + 0.5S -> 500 H2SO4 (7200EU directly or 4330EU with 3 steps)

Total: 1500L H2O + 1C+ 500L O -> 1000H + 1000L CH2O2 (9590 EU/6720EU)

So even if you throw away the Formic Acid (if its nerfed), you still produce Hydrogen cheaply. This one is not quite as broken as the other since it needs C and O or CO input, but still pretty weird.
