### ISSUE TITLE
Crafting Quests not registering with Tinkers Crafting Station

### ISSUE THREAD

**Issue by nickjfrench** [GTNewHorizons/GT-New-Horizons-Modpack#10695]
### Your GTNH Discord Username

ForsakenBacon#9090

### Your Pack Version

2.1.2.0-RC1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Using the Tinkers Crafting Station completes crafting quest tasks.

### The Reality

Tinkers Crafting Station does not complete crafting quest tasks. Meaning I have to recraft it in a vanilla crafting table.

The quest I discovered this on was the Tier 0 > You Shall Proceed > 5 Bronze Plates.

### Your Proposal

Register Tinkers Crafting Station as an accepted type for crafting quest tasks. 

I also feel Crafting Quests are a bit redundant. If you already have the required items, I shouldn't be required to recraft them to complete a quest.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
Wow, it's almost like crafting quests should be removed and everyone has been saying so for multiple years...

**Comment by Dream-Master** [comment]
and i say for the stone aga and steam age it is fine. Maybe we can add tinkers table to crafting task

**Comment by eigenraven** [comment]
I guess the tinker's table doesn't call the game statistics update function, should be an easy fix. There is no "registration" of which crafting guis work afaik.

**Comment by Dream-Master** [comment]
if that can added and maybe the forestry table as well would be nice. In lv you dont have crafting quests anyway

**Comment by Connor-Colenso** [comment]
> and i say for the stone aga and steam age it is fine. Maybe we can add tinkers table to crafting task

I just cannot comprehend why, they are just totally unnecessary and everyone except you seems to hate them. They aren't hard, they aren't engaging, it's just wasting the users time because they didn't use a vanilla crafting table. That isn't what GTNH should strive for.

And like you say they are totally obsolete beyond stone age so why are we so desperately clinging onto the label? It makes no sense.

**Comment by Dream-Master** [comment]
@eigenraven said its not a big deal so we can go this way.

**Comment by Connor-Colenso** [comment]
> @eigenraven said its not a big deal so we can go this way.

If it gets done, which is a big if given this has been an issue for 3+ years with a trivially easy solution readily available to us.

**Comment by eigenraven** [comment]
I just tested this and both forestry worktables and tinkers crafting stations (full and slab) trigger the bq crafting tasks already in latest dev, even with GT tools

**Comment by joshaup1999** [comment]
I’ve never had issues with crafting task detection in a crafting station, never used the vanilla table once I was able to make the TiC one, I restarted on 2.1.2.1 and wasn’t an issue for me

**Comment by MortiferDec** [comment]
I have noticed before that when crafting if the item is not in your inventory, the crafting quests aren't completed. If you stick it directly back into the crafting table, or in an adjacent chest, the crafting task will not complete.
