### ISSUE TITLE
Silicon Dioxide Electrolysis wrong

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10699]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-18-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

3 SiO2 -> 1 Si + 2000L O

### The Reality

![image](https://user-images.githubusercontent.com/40274384/178808391-60dbf816-96cb-4e52-8f77-1440a920c2d7.png)

### Your Proposal

Make it 3 SiO2 -> 1 Si + 2000L O

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
another "Dream wants nerf" time...

**Comment by chochem** [comment]
are you saying this is intended?

from my understanding, if recipes are supposed to be nerfed after our 'chem standardization', one should
1) remove recipe/replace the recipe by something very different
2) increase EU/time or minimum tier.
3) introduce a hard to process sludge/trash item. (does not really work here)

I searched a bit and it looks like IRL the main process seems to be SiO2+2C=Si+2CO (in some kind of a furnace), or in our notation 3 SiO2+2C -> Si+ 2000L CO. (that is how our notation works right?)

So if there is supposed to be a nerf here, maybe lets go with 1 and just remove the electrolysis and just keep the focus on the EBF recipe with this?

**Comment by GlodBlock** [comment]
silicon dioxide electrolysis recipe was removed when dream worked on silicon change, then people complained it a lot so dream added this 'nerfed' electrolysis recipe(5 silicon dioxide -> 2 siliocn and 3000 oxygen). but this recipe will turn oxygen into silicon through silicon dioxide loop, so i changed it into 5 silicon dioxide -> 1 siliocn and 3000 oxygen.
however dream removed this electrolysis recipe again later (before the chem standardization pr merged) so i added it back accidentally. i asked dream should i removed it and dream said it is ok to keep it.
