### ISSUE TITLE
change DTPF recipe, endgame recipe cost too much material and time

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#10690]
### Your GTNH Discord Username

456k

### Your Pack Version

2.1.2.4pre7

### Your Proposal

DTPF recipe have a very long time to do it, and endgame recipe changed to use DTPF materials a lot. now some endgame recipe like star gate take much more time than human life to make it in uev. 
here is materials cost for one star gate
![CUYDTPF recipe have a very long time to do it, and endgame recipe changed to use DTPF materials a lot. now some endgame recipe like star gate take much more time than human life to make it in uev. 
here is materials cost for one star gate
12%S5F1{7_WPB5ZLFD](https://user-images.githubusercontent.com/49830847/178140879-aae9a469-35c1-4a33-9eba-5f9e888aa310.png)
we can find we used 9123ML Residue to make it. every 1000 L Residue cost 9837.5s in UEV. so we need 501712.5s to make it in total

### Your Goal

reduce the time

### Your Vision

people can arrive endgame in a acceptable time

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pnc6lx** [comment]
> Not really sure what the complaint is here, is it that the DTPF is too expensive, the recipes are too time consuming or that the stargate is too expensive?
> 
> Latest does have a 100s recipe for 576L of spacetime iirc, this is not in any latest release yet and may abate some of your concerns. Please contact me on discord if you want to discuss it in more detail as I'm more likely to respond promptly there.

spacetime dont cost too much time( in fact it cant be crafted now: you cant reach MAX) mixer and laser cost too much time for end game cost.

**Comment by ScriptedPiky** [comment]
I'm guessing that the resource demand is also pretty obscene, seeing 198k UEV circuits & 184k space time ingots being required is bonkers. That amount of resource gain required jumped at an obscene rocket point prior to the Stargate recipe changes as well

**Comment by Connor-Colenso** [comment]
> I'm guessing that the resource demand is also pretty obscene, seeing 198k UEV circuits & 184k space time ingots being required is bonkers. That amount of resource gain required jumped at an obscene rocket point prior to the Stargate recipe changes as well

Sure but that is for the stargate, not the DTPF itself. The stargate is an extreme anomaly and meant to be obscene.

**Comment by Pnc6lx** [comment]
> > I'm guessing that the resource demand is also pretty obscene, seeing 198k UEV circuits & 184k space time ingots being required is bonkers. That amount of resource gain required jumped at an obscene rocket point prior to the Stargate recipe changes as well
> 
> Sure but that is for the stargate, not the DTPF itself. The stargate is an extreme anomaly and meant to be obscene.

NAN also have a crazy resource need, and it is used to unlock endgame quest page

**Comment by GlodBlock** [comment]
stargate is the sign of beating gtnh. if it can't be made in human life that means our pack's balance has reached a new peak

**Comment by Connor-Colenso** [comment]
> NAN also have a crazy resource need, and it is used to unlock endgame quest page

Yea we have discussed that in discord and the endgame page needs re-arranging at some point.
