### ISSUE TITLE
Loop to Turn CO2 to C and O way cheaper

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#10692]
### Your GTNH Discord Username

tim lam

### Your Pack Version

2.1.2.4-dev-18

### Your Server

SP

### Your Expectation

CO2 reduction is expensive

### The Reality

MgCO3 route takes 7480eu compared to CO2 electrolysis for 36000eu
80% energy discount

### Your Proposal

Change the recipe a bit?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
cardon dioxide doesn't have an easy and infinity source like water. i think it is fine to keep this cheap loop
