### ISSUE TITLE
Add Blaze Rods to Coins, Coins, Coins Tab

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#10705]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Proposal

Add a convenience option for Blaze Rods to the "Coins, Coins, Coins" Tab of the Quest Book.

### Your Goal

Since Ender Eyes and Ender Pearls (arguably rarer treasure) are present, adding Blaze Rods would fit with an overall goal of adding convenience for players. 

### Your Vision

Add a route (for a cost, of course) for players that wants access to Blaze Rods but don't particularly want to step foot in the Nether right now.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
Set up a blaze farm, like a normal person, would be my suggestion. Or just do crops. Or bees. There might be other ways too.

**Comment by TwoTailedFox** [comment]
By that logic, we shouldn't have Ender Pearls in that tab either.

**Comment by boubou19** [comment]
i'd even add that on one hand, by that logic, coins coins coins shouldn't even exist, but on the other hand, when should quest dev stop adding stuff in coins coins coins? because if ender pearls are in it, and some other mob loots too, should we also add everything mob loot based to the tab? @Dream-Master i think a clear limit has to be drawn here.

**Comment by Dream-Master** [comment]
it depends. If we tier it its ok. Now i am in mid hv and can farm blazes and not need the quest but in mid mv it could be usefull even if your armor is weak.

**Comment by BritishCynic** [comment]
Closing as request implemented.

**Comment by Dream-Master** [comment]
@BritishCynic its not merge yet so let it open
