### ISSUE TITLE
Side support API to OC 

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#10707]
### Your GTNH Discord Username

Кетцаль#0802

### Your Pack Version

2.1.2.1

### Your Proposal

The possibility for the robot to change the output of GT/IC2 machines and the face. Also the ability to connect the wires

You can add a robot update that allows the robot to interact with all sides of the GT block and use different GT tools on different sides

### Your Goal

Right now, robots can't assemble structures properly without the ability to change the orientation of mechanisms. I propose to fix it.

### Your Vision

It will be possible to program the robot to build repetitive structures, for example: plasma turbines or miners and customize them

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
I suspect that current implementation of `robot.use` is capable of all of that

**Comment by repo-alt** [comment]
Ok, looks like there is a bug in `robot.use` or in GT `onPlayerInteract` event handling
