### ISSUE TITLE
Grandmaster magic energy absorber doesn't pull enchantments off books

### ISSUE THREAD

**Issue by FlandreS** [GTNewHorizons/GT-New-Horizons-Modpack#10718]
### Your GTNH Discord Username

Flandre#6326

### Your Pack Version

2.1.2.3qf

### Your Server

Earthquake

### Type of Server

Crucible

### Your Expectation

Inserting a book into the "in" slot of a grandmaster energy absorber, it adds the expected amount of energy to the machine's energy buffer, **then moves an unenchanted book to the "out" slot.**

### The Reality

Inserting a book into the "in" slot of a grandmaster energy absorber, it adds the expected amount of energy to the machine's energy buffer, **and moved the same enchanted book to the "out" slot** which can be cycled straight back in for infinite energy akin to a dragon egg.

Not the most useful thing on the planet, as the absorbers tend to get powered by other infinite sources like CV or dragon eggs, but cycling the same book in/out bypasses the high up-front cost of those things. At least in our current arrangement of crucible + 2.1.2.3QF a single enchanted book can act as 1A EV

### Your Proposal

Strip book enchantments when the machine absorbs them for energy, outputting a plain book.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed in dev
