### ISSUE TITLE
Crash When Clicking On LootGames MineSweeper Block

### ISSUE THREAD

**Issue by Atomic203** [GTNewHorizons/GT-New-Horizons-Modpack#10714]
### Your GTNH Discord Username

Atomic#5169

### Your Pack Version

2.1.2.4-dev18

### Your Server

SP

### Your Actions

Whenever i click on the minesweeper loot games block it works but the 2nd time i do it my game crashes 

### Crash Report

https://paste.ee/p/L28rj

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
