### ISSUE TITLE
Large Molecular Assembler Performance Issues

### ISSUE THREAD

**Issue by Jonodonozym** [GTNewHorizons/GT-New-Horizons-Modpack#10719]
### Your GTNH Discord Username

Jono#7396

### Your Pack Version

2.1.2.4-13-pre

### Your Server

SP

### Your Expectation

The Large Molecular Assembler should produce a reasonable amount of lag

### The Reality

Lag scales with every pattern added:

No patterns:
![2022-07-16_07 31 41](https://user-images.githubusercontent.com/18454922/179298781-1f370ba1-28d6-4e5e-ab3d-4605d72ebb7e.png)

16 patterns:
![2022-07-16_07 31 48](https://user-images.githubusercontent.com/18454922/179298783-eedf206d-bcc0-4c46-af4f-840d6c6e1c8c.png)

Diamond chest of patterns:
![2022-07-16_07 31 39](https://user-images.githubusercontent.com/18454922/179298774-e3721180-dcef-466d-9c38-7b82eee86840.png)

Also using IV energy hatch if that matters

### Your Proposal

Refactor the pattern checking code to run less frequently

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
Yea multiple people have reported this being exceptionally laggy, to the point where it's virtually useless. Even when not running it can easily take 0.5ms.

**Comment by MuXiu1997** [comment]
On the one hand, I've been busy lately and on the other hand, I'm really a rookie and it would be great if someone could give me advice or help me fix it
