### ISSUE TITLE
Add Assembler recipe for H.S. Booster Track / Change Quest for it.

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#10716]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Proposal

When you click on the item, it brings up Assembler recipes for "normal" tracks, rather than an Assembler recipe for the correct track.

Additionally, both the "The Transcontinental Railroad - High Speed" and "Boost Your Speed v2" quests ask for H.S. Booster Tracks and H.S. Transition Tracks; I propose that the first quest only ask for 64 x H.S. Track, and the second quest ask for 24 x H.S. Booster Track and 32 x H.S. Transition Track (the combined tally from both what both quests ask for).

### Your Goal

Add an Assembler recipe for the H.S. Booster Track and make modifications to the quests.

### Your Vision

Ensure it, like other tracks, have correct Assembler recipes and ensure the quest flow is a little saner.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TwoTailedFox** [comment]
Any update on this one?

**Comment by TwoTailedFox** [comment]
OK, 2.2.0.0-RC2 has an Assembler recipe showing for the H.S. Booster Track, but it only shows in NEI when you check Assembler recipes for H.S. Track. This should be changed so that H.S. Booster Track correctly shows its Assembler recipe in NEI.
