### ISSUE TITLE
Forestry Cans void when filling GT tanks

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10724]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

When filling a tank, the game should dispense empty cans when the fluid is passed to to the tank's internal storage

### The Reality

The tank consumes the entire cell and does not pass an empty can to the bottom output slot.

### Your Proposal

Ensure that the tank correctly checks for kind of cell is passing fluid to it and gives the player an empty version of it. This issue might also affect wax capsules.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leagris** [comment]
Forestry capsules are **explicitly single-use** as they are made from renewable wax.

**Comment by miozune** [comment]
Technically duplicate of #10185
