### ISSUE TITLE
Multiblock Oil Driller repeatedly retracting/deploying pipes, while continuing to pump

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT-New-Horizons-Modpack#10731]
### Your GTNH Discord Username

mitchej123

### Your Pack Version

2.1.2.4-18-pre

### Your Server

localhost

### Type of Server

Vanilla Forge

### Your Expectation

My existing multi block oil driller rig would continue to drill oil in a chunk that is not depleated

### The Reality

The pump was at Y 67.  It would continuously retract, and re-deploy the pipes.  However since it was 67 (> 64) above bedrock, it voided the extra pipes, and when redeploying was 3 short of hitting bedrock and would stop pumping.  Filling the controller up with mining pipes would cause it to continue to cycle, pumping while doing so.  

I broke the controller and replaced it.  It re-deployed the pipes and did not continue the cycle.

### Your Proposal

Track down what caused the bug, and fix it.  I didn't see any obvious changes in the past 4 months; but I haven't actively been playing so I can't say when this bug was introduced. 

Chochom noticed the same issue; however his pumps were within 64 of bedrock so the cycling was not noticed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNHAfx237v7** [comment]
Can confirm it breaks my OW oil drill too, as well as off-planet fluid drills (Deuterium, Helium-3 etc)

**Comment by repo-alt** [comment]
works fine on Zeta too...

**Comment by GTNHAfx237v7** [comment]
I don't see anything that jumps to my attention in fml-client-latest.log or gregtech.log, other than a one-time warning of my OW oil drill being a potential lag source. Want me to upload them nonetheless?

**Comment by repo-alt** [comment]
Do you also use the latest version?

**Comment by GTNHAfx237v7** [comment]
Yes, 2.1.2.4 dev18.
Breaking and replacing the controllers fixed it for me, too.

Logs attached.

[GregTech - Kopie.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9150153/GregTech.-.Kopie.log)

[fml-client-latest - Kopie.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9150140/fml-client-latest.-.Kopie.log)

**Comment by repo-alt** [comment]
> Primary storage file broken in C:\Test\MultiMC\instances\GTNH 2.1.2.4dev18\.minecraft\saves\New World Backup_borked\gregtech\UO.0.0.dat

**Comment by boubou19** [comment]
well aside from a backup, not much can be done except break and replace the pump to regen this file.

**Comment by boubou19** [comment]
also, i think we should make it regen the file,assuming the pump has to redo all the work from the begining.

**Comment by Glease** [comment]
Can you send me this broken file somehow? I'm cursious how it's broken.

**Comment by GTNHAfx237v7** [comment]
[UO.0.0.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9156517/UO.0.0.zip)

**Comment by Glease** [comment]
OK now I'm certain it's some catastrophic event like power outage or disk failure - the file is full of zeros. No wonder it'd break. There is nothing I can do with this.

**Comment by mitchej123** [comment]
His file is corrupt, I haven't been home to check but I'm not sure if mine was.  I wouldn't say this issue is closed...

**Comment by mitchej123** [comment]
I've been away on a business trip. l experienced the issue myself and found others with the same behavior.  Was planning on checking my logs and providing any follow up findings when I get back

**Comment by chochem** [comment]
@Glease As the ticket mentioned I also found the same behavior after mitch talked about it on discord. I have had no power outages or disk problems as far as I am aware.

Fixed it by breaking and replacing controller. I guess that means my files are regenerated and there is nothing I can check? Well unless it happens again ofc. (I havent checked on them since).

**Comment by repo-alt** [comment]
You can still look up the old Gregtech.log is it is saved, if there was the same error as above

**Comment by GTNHAfx237v7** [comment]
I am also not aware of disk issues or power outages during gameplay. My file has been broken since 18.05.2022, at least this is the oldest save I still have.

**Comment by Florexiz** [comment]
Can confirm, this happens every restart on zeta with my helium 3 pump
I have to go there and manually re insert extracted pipes

**Comment by mitchej123** [comment]
I'm back, forgot to check into this -- will dig more today and see if it's still happening and look for some logs on it.

**Comment by PolkageistHS** [comment]
I've ran into this with our infinite drills on other planets, here's what I've noticed: 

- The pipes that are retracted will go into an output bus if one is available, which can be pointed at the input bus to recycle the pipes so nothing gets lost
- The drill will deploy its pipes (if it's more than 65 blocks above bedrock it'll use more than 1 stack), pump for 10-15 seconds, then shut off for about a second before resuming.  As soon as it turns off and back on is when it switches from deploying to retracting the pipes (and eating them if there's not an output bus to put the extras in).  The shut-off is not related to power or fluid levels (I removed all covers from the controller so it wouldn't turn back on if it lost power).  
- I've only noticed this on drills that were placed prior to updating to 2.1.2.4-25pre.  Ones I've placed afterwards don't seem to have the issue that I can tell.

**Comment by Glease** [comment]
Next time you got this please run `/gt toggle debugDriller` and see what you get on server console.

**Comment by PolkageistHS** [comment]
It set debugDriller = true, but nothing else has happened in the server console.  I let the driller lose all its pipes and shut off, then fed it more so it would turn back on, then put the output bus on it so it wouldn't run out of pipes.  Would it be in a different log file?

**Comment by Glease** [comment]
Ah yes it's outputting to GregTech.log not server console. Sorry my bad.

**Comment by PolkageistHS** [comment]
[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9389939/GregTech.log)

Ran it for about 15 seconds and the file size went from 300kb to 11mb.  We have at least a dozen pumps running so I'm not sure how helpful it's going to be, but here's the log.
