### ISSUE TITLE
Sodium Potassium Missing Multiblock Mixer Recipe

### ISSUE THREAD

**Issue by Dyonovan** [GTNewHorizons/GT-New-Horizons-Modpack#10739]
### Your GTNH Discord Username

Dyonovan

### Your Pack Version

2.1.2.4-18-Pre

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

There should be a Multiblock Mixer recipe for Sodium Potassium 

### The Reality

There isnt one

### Your Proposal

Add Recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DirtyFaced** [comment]
same for bio-balls

**Comment by BritishCynic** [comment]
This issue is now obsolete as Sodium Potassium is now made via the Distillery, and thus should be closed.
