### ISSUE TITLE
Server crash durring launch

### ISSUE THREAD

**Issue by natec22** [GTNewHorizons/GT-New-Horizons-Modpack#10736]
### Your GTNH Discord Username

Natec22#2006

### Your Pack Version

2.1.2.3qf

### Your Server

Private server, nodecraft host

### Type of Server

Nodecraft

### Your Actions

On launching server server polls Dropbox for baubles, this returns a 404 error. So far as I can tell, this crashes the server.
Dropbox link returned 404 on all systems attempted, crash now replicated on friends server.

### Crash Report
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9128151/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by natec22** [comment]
Workaround found, install baubles to the 1.7.10 folder on the server from the client.

**Comment by boubou19** [comment]
server side should have baubles shipped already. This is weird

**Comment by natec22** [comment]
My server is throwing quite a few mods are throwing requirement errors, in sequence. I already fixed several of them after that one.

**Comment by boubou19** [comment]
at that point you should check if the server archive is correct and not corrupted because you are the only one having this issue.

**Comment by natec22** [comment]
so far at least: open modular turrets, a library (don't remember which one), Ztones, and forge relocation.

**Comment by natec22** [comment]
I will take a look at that

**Comment by natec22** [comment]
that was the issue, fixed both on my server and my friends server.
