### ISSUE TITLE
Items are swallowed and disappear after returning to AE

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#10733]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.1.2.4 pre-18

### Your Server

SP

### Type of Server

Open To LAN

### Your Expectation

In the game, AE displays items in the terminal or automation panel after receiving input from the outside, and then outputs the next step of automation

### The Reality

My AE doesn't work correctly in the game, it sometimes does not display items when it receives items returned by automation, causing my automation to get stuck frequently.

### Your Proposal

AE has swallowed my countless automation products, which makes me very uncomfortable. Every time I need to open the creative mode to get the missing parts, I hope I can find the cause of this problem as soon as possible, because this is my problem in 2.1.2.3qf or earlier never encountered in the version

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SafariXiu** [comment]
Sometimes this problem also seems to occur when transmitting across latitudes

**Comment by chochem** [comment]
Any steps to to reproduce this? seems to work just fine for anybody I have talked to. not sure why you checked that last box.
