### ISSUE TITLE
Allow PAs to accept Laser Source Hatches

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#10746]
### Your GTNH Discord Username

maniifestantes

### Your Pack Version

2.1.2.4-18-pre

### Your Proposal

When i read about the power pass function form Tec Tech, the first thing that came to mind were those long lines of PAs, so i tried to see if you could make them power each other. But sadly you can't put a Laser Source in one

### Your Goal

My idea would be that you could feed the first one, say 4096A, and then you'd put a power pass on a laser source, which would power the next pa, and so on, so forth

### Your Vision

![2022-07-17_20 17 16](https://user-images.githubusercontent.com/57275066/179428774-01c4c6b0-a0da-4edb-ac12-c66ee0d27d88.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by alexandre-tardif** [comment]
If the power pass cover could be fixed and allowed on PA it could be a pretty good way to allow this. From what I understand, the cover is supposed to allow this functionality on multis that don't have it yet
