### ISSUE TITLE
Backport fix for PR: Transportation Crafting Extension Cards

### ISSUE THREAD

**Issue by OrderedSet86** [GTNewHorizons/GT-New-Horizons-Modpack#10741]
### Your GTNH Discord Username

Order#0001

### Your Pack Version

2.1.2.4-5

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Crafting extension cards from Project Red: Transportation don't work at all. They are supposed to allow for output to be on a different block than input (for example, EBFs). Instead PRT eternally waits for the output to be on the input block:
![2022-07-17_13 10 58](https://user-images.githubusercontent.com/88752681/179423154-c17c3601-4d34-4802-a2cb-33d75bdc4a6d.png)
This is a simple setup - going from the left: request pipe, broadcaster on chest with 64 steel ingots, crafting card for steel ingot -> steel plate in bending machine, and crafting extension card (the bending machine outputs into the rightmost chest). But PRT waits forever for return on the bending machine instead of properly on the rightmost chest.

**Apparently this is a known issue and was fixed in PR 1.12: https://github.com/MrTJP/ProjectRed/issues/1416**

The fix appears to only be two lines long.

### The Reality

See above.

### Your Proposal

Backport the fix so crafting extension cards work properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by OrderedSet86** [comment]
Hi @Shiroi -

I looked into it, and it appears to work if the input item is in the top left of the crafting chip, like so:
![image](https://user-images.githubusercontent.com/88752681/207474727-a1a8038e-d6e4-437d-aa71-95599afde2ca.png)

But if you move the input to the bottom left, it breaks and sends the input to the extension chip instead:
![image](https://user-images.githubusercontent.com/88752681/207474776-681e0a7b-ab24-449e-99bf-f8a5cbd867e2.png)

No idea what the cause is...

**Comment by Zrashin** [comment]
Hi, I cannot reproduce this issue and can use the extension perfectly fine in testing.
Testing with a Blast Furnace setup for Aluminium:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11055259/8bbee3d9-fb2d-47a6-9969-f4acc1aa956e)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11055259/c40a3595-aef7-4efb-a6a1-11d10761502f)

^^^
This Interface pipe is connected to the output bus while the one with the extension is connected to the input bus.

As long as the extension is attached to the same slot as the item you are sending it should work, which I assume is intended behavior so you can use multiple extensions to send inputs to multiple places as long as you get the output in the interface pipe the crafting chip is in.

It would be nice to have a recipe for this item, as far as I can see it does work and very operational. Probably would be same as the other chips just with red dye I'm assuming?

**Comment by Zrashin** [comment]
Just so I have all my x's crossed, I checked against the setup had in the original post:

Crafting chip extension page:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11055259/08214545-58ac-45bc-a1a1-981e1ee4e86d)

Crafting Chip Matrix page:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11055259/1ab3fb16-bc06-4989-b92b-89e8efd0964f)

Physical Setup:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11055259/9e834a27-751e-453e-9585-67715979a3db)
Includes a broadcast on the left interface, the extension in middle, and crafting chip on right.

Tested by requesting steel plates:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11055259/a2056449-e38a-48a2-aa56-9ac8c22875ab)

Plates end up spitting out after to prove functionality, it works.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11055259/22c761d7-eca8-45c1-b96c-42d33ede2e79)
