### ISSUE TITLE
conflicting (duplicated?) recipes in EBF for the raw aluminum

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10745]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.4-dev18

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

There are 2 recipes for the raw aluminum:
![image](https://user-images.githubusercontent.com/12850933/179427696-3b12b52e-9641-4c60-83d8-c006d04249c2.png)
![image](https://user-images.githubusercontent.com/12850933/179427688-4b8d2cb0-fd6d-45a2-80f8-66c2c6e50ae7.png)

The heating value of the cupronickel coil is 1801 °K so i don't see the point of those. Also rn on zeta it's the 65.75s that is used, but i saw the 80 one being used before so looks like it's not even deterministic.

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by King65868** [comment]
#10470 is the same

**Comment by boubou19** [comment]
eh it's spelled aluminum that's why i didn't find it
