### ISSUE TITLE
raw silicon dust to raw silicon ingot went missing

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10748]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.4-dev18

### Your Proposal

this is the only usage for the raw silicon dust in the EBF
![image](https://user-images.githubusercontent.com/12850933/179432353-1889c716-e5b0-4de4-a338-be243a70ccd2.png)

It would be cool if we could get ithe dust -> ingot recipe back because it was in the pack at one point

### Your Goal

.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
Specifically it is supposed to be an EBF recipe with kanthal coils (says dream on discord). In particular it is supposed to be more expensive and (due to kanthal) is supposed to unlock later than the SiO2 smelting.
