### ISSUE TITLE
Electrical Stimulator does not simulate Nether

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/GT-New-Horizons-Modpack#10752]
### Your GTNH Discord Username

MrWye

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

Alveary Electrical Stimulator is supposed to simulate nether with circuit board and blazing electron tube embedded into it
https://prnt.sc/2zlDim06_qE0
### The Reality

Nether is not simulated

### Your Proposal

needs a fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
the quest was incorrect. fixed in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/10880
