### ISSUE TITLE
small ores dont give roasted crushed/impure ores

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10759]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-18-pre with updated gt5u/coremod

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Banded iron ore now gives roasted iron dusts when processed. I would expect that to be consistent with the small ore as well. (same with Garnierite and maybe others)

### The Reality

The small ores still given impure banded iron ore and crushed banded iron ore, not the roasted variant.

Basically the changes here https://github.com/GTNewHorizons/GT5-Unofficial/commit/cc8eeca01789f30e84083bffd388f4abb9658fa5 did not cover small ores.

### Your Proposal

include small ores in the changes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
@GlodBlock just let me know if I am wrong and this is intended behavior.

**Comment by Elisis** [comment]
:concern: yet another commit few knew about/asked for
