### ISSUE TITLE
The use of oxygen in the production of styrene-butadiene rubber is a lower material utilization rate than air

### ISSUE THREAD

**Issue by MarchMoon-Hubert** [GTNewHorizons/GT-New-Horizons-Modpack#10765]
### Your Pack Version

2.1.2.3qf

### Your Proposal

The use of oxygen in the production of styrene-butadiene rubber is a lower material utilization rate than air.
![J2I4TRZYQD2{M`AH_ (}U6Y](https://user-images.githubusercontent.com/55826199/179672362-ce89e2b9-e94a-4307-90e5-16f6d495fae0.png)
![PWWCKH2%FCQ0YQXK0A(U2DO](https://user-images.githubusercontent.com/55826199/179672379-317bc8b2-83a0-4af3-9caa-e76083725af7.png)

I think this is wrong, because in other polyaddition reactions, oxygen has a significantly higher raw material utilization than air. 
![IVN)$P9T%$K9V0KC 771P83](https://user-images.githubusercontent.com/55826199/179672465-e3227a3e-60b7-453a-a151-32cd6fba4aec.png)
![6O}6(}A_R1VUCYQ_4Q)C{$I](https://user-images.githubusercontent.com/55826199/179672479-57b4e930-79b1-487e-8206-32080d483ffd.png)

And in the reaction of styrene-butadiene rubber using titanium tetrachloride, the appearance of oxygen is better than that of air. 
I have reason to think that in the production of SBR powder, using oxygen will get less SBR powder than using air is wrong. 
A machine translation from a Chinese player.

### Your Goal

wrong recipe

### Your Vision

Raw material utilization of oxygen and air in the production of interchangeable styrene-butadiene rubber

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/183459629-00e0becd-7a81-4c4a-949e-f9d34f2e7eb6.png)
was fixed at some point.
