### ISSUE TITLE
MTBE reaction mixture gives too much output

### ISSUE THREAD

**Issue by Anonim1998** [GTNewHorizons/GT-New-Horizons-Modpack#10761]
### Your GTNH Discord Username

Anonim98

### Your Pack Version

2.1.2.4-18-pre

### Your Server

SP

### Your Expectation

Distillate 2xMTBE mixture into 900 methanol and butene.

### The Reality

From 1000 methanol and 1000 butene I can make 2000 MTBE mixture, and then distillate it to 2x900 methanol and butene(+ anti-knock agent)? Infinite source of methanol and butene?

### Your Proposal

Change either craft price (1000xmethanol+1000xbutene=1000xMBTE mixture) of distillate output (1000xMBTE mixture = 450methanol+450MBTE mixture+...)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Ah this'd explain why my HOG factory was using way less butene than calculated...
