### ISSUE TITLE
Engrave Crystal Chip EBF recipe missing

### ISSUE THREAD

**Issue by Josh5minus1** [GTNewHorizons/GT-New-Horizons-Modpack#10767]
### Your GTNH Discord Username

A1#8299

### Your Pack Version

2.1.2.4-18 dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to craft engraved crystal chip with EBF, I remember them requiring 1 raw crystal chip, 1 emerald/olivine plate, and helium gas

### The Reality

The EBF recipes are missing, making the engraved crystal chip uncraftable, which is important for making crystal processor circuits

### Your Proposal

Re add the missing recipes back

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you mean this? 
![image](https://user-images.githubusercontent.com/40274384/179741226-4fe2387a-4e7c-4ff8-adaf-6d11f32481d9.png)
that works fine for me in dev18 + some updated mods :/

**Comment by Josh5minus1** [comment]
Hmmm.. probably because of some mods i manually updated, i use latest gregtech and gtnh core mod from master branch in jenkins

**Comment by chochem** [comment]
why did you close it then. or is it fixed in dev?
