### ISSUE TITLE
Botania Addon

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#10762]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.1.2.4-18-pre

### Mod Name

Advanced Botany

### The Mod to Add

- Mana Distribution: Adds some containers that can store mana in large amounts without having to use tons of pools all over an area to make a single recipe, a next tier of spreaders and sparks to transfer mana more quickly, and a mana display of the entire mana network.
![image](https://user-images.githubusercontent.com/45178400/179634664-0738e359-4951-442f-a512-f2568e1ca7fb.png)
![image](https://user-images.githubusercontent.com/45178400/179634725-a796d0c2-7818-40ff-83a1-decc6664f102.png)

- Mana charger: a device that charges mana items "into" itself without having to drop the items on the ground and causing some lag for entities
![image](https://user-images.githubusercontent.com/45178400/179634738-94370867-0809-457c-bd0e-b006e591c34d.png)

- Advanced aglomeration plate: a device that can handle items inside ( and in stack sice) so you dont need to drop them in the floor, so they dont create lag, also used to make some recipes of the addon
![image](https://user-images.githubusercontent.com/45178400/179635777-749e1a73-e569-46b6-ae52-7156f4c9f85d.png)
![image](https://user-images.githubusercontent.com/45178400/179636073-7667f221-6b49-4944-a431-31b39af3af0c.png)

### Your Reason

Apart from being able to handle mana more efficiently and items, it adds integrity with thaumcraft in the botania patterns, adding some more advanced ones, apart from adding some more items like relics, advanced armor, a flower that generates vis, some flowers of mana generation, and some decorative blocks.
![image](https://user-images.githubusercontent.com/45178400/179636556-a8d4b013-3c71-4160-aee7-cd4d468afb17.png)

### Preliminary Investigation

The pack works nice, is only an addon so there are no incompats, there are some recipes that should be more costly to make them but for all is fine.
https://www.curseforge.com/minecraft/mc-mods/advanced-botany

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Dream-Master** [comment]
Not sure if is possible but why don’t make mana a fluid store in gt devices as well ?
And wasn’t Alfheim not suggested first as adding mod?
First Botania need to be more integrated into gtnh

**Comment by AlastorsGame** [comment]
> Not sure if is possible but why don’t make mana a fluid store in gt devices as well ?
> And wasn’t Alfheim not suggested first as adding mod?
> First Botania need to be more integrated into gtnh

I strongly believe that this mod would help with the integration into GTNH, given that it adds greater automation and major improvements to botania that would not only help reduce lag, but just in general be a key asset to botania integration.

likewise, we can technically already store mana within AE within the limited scope that botanic energistics offers, and I personally believe botania integration will be highly stunted until botanic energistics is finished

**Comment by EnderProyects** [comment]
Hi, so the next dev version is on the way, could this be checked if some magic lover dev have some free time? XD

**Comment by Dream-Master** [comment]
> Hi, so the next dev version is on the way, could this be checked if some magic lover dev have some free time? XD

<https://github.com/GTNewHorizons/Advanced-Botany> i add this repository. A buildscript need to be added if we add this mod somehow

**Comment by EnderProyects** [comment]
Advanced botany recipes that need to be tweaked:
- Add plates and variants of Advanced Botany (AB) Mithirll to greg-tech (Colen)
- Forge of Nidavellir:  Infusion recipe, void metal in the middle, 4 agglo plates, 4 blooks of manasteel, 4 item circuit tier2, 2 runes of air, 2 runes of earth ( and essece)
- Thaumin Crafty Crate:  1 Screwdriver at the bottom
- Mana Charger: Infusion recipe, mana pylon at the midle, 2 manatide bellows, 4 livingrock slabs, 4 runes of mana, 2 runes of air, 4 mana tablets, 4 mana diamonds
- Terrahoe: Infusion recipe, hoe of growth at the midle, 4 livinwood Twigg, 4 terrasteel plates, 2 earth crystal cluster, 2 runes of eath, 1 flawless olvine and 1 sapphire ( replace this item with the how of growth to Bound Sickle BM recipe)
- Nebula armour set: change all the terrasteel armour ingredients with elementium ones
- Material destroyer: infusion recipe, Natural core at the middle, 1 Terra Shaterer SS, 1 terra truncator, 1 terra hoe, 1 terra blade, 4 AB Mithrill blocks, 4 livinwood
- Mana flower: add 2 primordial pearls, add 4 AB Mithrill plates
- Blade of space: infusion recipe, Blade of the sea at the midle, 4 AB Mithrill plates, 2 nebula fragments, 2 rod of nebula, 1 rod of bifrost, 1 magic hand mirror
- Blade of the sea: infusion recipe, Starcaller at the middle. 2 AB Mithrill plates, 4 pieces of nebula, 2 runes of water, 2 runes of air, 1 dreamwood twig, 1 rod of seas
- Mithrill ingot: massive nerf, use a block of terrasteelk instead of a nugget, and a gaia spirir ingot instead of a gaia spirit
- Nebula fragment: massive nerf, use a block of Mithrill instead of a nugget, rod of the bifrost instead of pixie dust
- Rod of nebula: change 1 dreamwood twigg with a staff of travelling

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Advanced-Botany/releases/tag/1.4.3

**Comment by EnderProyects** [comment]
P.s I'm also working on three new blocks (just missing the textures) that work as mana pools, and the two catalysts but have inventory, so crafting can be done using hoppers or any type of pipe.

**Comment by Minepolz320** [comment]
Nerf IT!

**Comment by Alastors** [comment]
> Nerf IT! ;)

_shut_

**Comment by Alastors** [comment]
> https://github.com/GTNewHorizons/Advanced-Botany/releases/tag/1.4.3

already wrote the lore for the mana fountain, finishing the rest right now because holy christ the lang file makes me cringe

**Comment by combusterf** [comment]
> I strongly believe that this mod would help with the integration into GTNH, given that it adds greater automation and major improvements to botania that would not only help reduce lag, but just in general be a key asset to botania integration.

This is probably a case of mistaken identity, there's an AE2+Botania mod that does this with the obvious hard dependency on applied energistics. See:

> P.s I'm also working on three new blocks (just missing the textures) that work as mana pools and the two catalysts, but have inventory, so crafting can be done using hoppers or any type of pipe.

So basically the stuff that's been argued as the main reason for inclusion is actually not implemented yet. That kind of begs the question if those should be implemented *outside* of Advanced Botany before they become a package deal.

**Comment by Alastors** [comment]
> > I strongly believe that this mod would help with the integration into GTNH, given that it adds greater automation and major improvements to botania that would not only help reduce lag, but just in general be a key asset to botania integration.
> 
> This is probably a case of mistaken identity, there's an AE2+Botania mod that does this with the obvious hard dependency on applied energistics. See:
> 

combuster, my love, Botanic Energistics is highly unfinished, I would know, I've worked on it's code. It doesn't even have models, I was the one who proposed that mod a long time back

> > P.s I'm also working on three new blocks (just missing the textures) that work as mana pools and the two catalysts, but have inventory, so crafting can be done using hoppers or any type of pipe.
> 
> So basically the stuff that's been argued as the main reason for inclusion is actually not implemented yet. That kind of begs the question if those should be implemented _outside_ of Advanced Botany before they become a package deal.

I don't disagree

**Comment by EnderProyects** [comment]
Actually I was the one that suggested Botanic Energistics xd

**Comment by Alastors** [comment]
I also have to point out, some of my opinions regarding this mod have changed since September of last year, regardless of whether I believe it should be in the pack or not

**Comment by Alastors** [comment]
> Actually I was the one that suggested Botanic Energistics xd

Inaccurate

**Comment by combusterf** [comment]
Aside from the discussion that started while I was looking into this, my observations:
- The Lexica Botania integration is very much a stub. There's no in-game documentation what this stuff does, and googling "Advanced Botany" doesn't do anything useful either.
- Adds mostly higher-tier mana transfers, and a bunch of endgame items. Please argue how this stuff is useful and competitive with other stuff in the pack
- Tiering seems awkward, everything is rated at IV: once you got Gaia tech you have everything - except for that one item that uses a flawless mysterious crystal that looks more like an odd recipe accident.
- Please tell me you can progress without repeating the gaia boss for hours to get those resources.
- Recipes are otherwise expert-mode :+1: Still some work needed with GT material types for the plates and corresponding recipe tweaks, but that can only efficiently done after adding it to the pack.
- Mithrill gives a naming conflict with the infused platinum stuff already in the pack - probably best to add an adjective to that, e.g. "Charged Mithril" and maybe even use the base mithril as a crafting ingredient for the advanced stuff.

**Comment by Alastors** [comment]
> 

Yeah I've mentioned the mithrill thing to Ender multiple times, rewriting the entire lang file right now and reverting to mithril

**Comment by Alastors** [comment]
mithrill is a clear typo

**Comment by Alastors** [comment]
I will note combuster, we've already hashed out the mithril discussion, he was told to use one of GT's many pre-existing mithrils

**Comment by EnderProyects** [comment]
1 There are lexica pages for all the stuff of the mod so idk of what are you talking, and also you will not winf nothing in goggle since the mod is dead
2 The most valuable things are the forge, the mana charger, the thaumim crafty table, and some qol features, you can ask if you want me to name all of them and what can each of them make
3 The tiering seems ok for me, but if you see a recipe that seems not okay you can say it
4 I want to add a block that can make gaia recipes so you dont need to kill it, but idk how it can affect to progression, so is a work in progress
5 and 6 Since there where arguments about mithrill I will not say anything about that

**Comment by SweptWasTaken** [comment]
> Tiering seems awkward, everything is rated at IV: once you got Gaia tech you have everything - except for that one item that uses a flawless mysterious crystal that looks more like an odd recipe accident.

I mean, tiering for Botania in GTNH is still a little awkward. Botania isn't *really* integrated into any recipes outside of itself within GTNH's progression, so it's not like we have any basis for what kind of setups would be made in GTNH to make use of a lot of this stuff. Otherwise it's just a bunch more "Automation Magic" bloat that nobody really uses. I mean be honest, does anyone really use stuff like Thaumcraft Golems or the Assembly Halo?

Don't get me wrong, automating Botania stuff is actually really fun and fulfilling, but is this needed right now?

**Comment by EnderProyects** [comment]
> > Tiering seems awkward, everything is rated at IV: once you got Gaia tech you have everything - except for that one item that uses a flawless mysterious crystal that looks more like an odd recipe accident.
> 
> I mean, tiering for Botania in GTNH is still a little awkward. Botania isn't _really_ integrated into any recipes outside of itself within GTNH's progression, so it's not like we have any basis for what kind of setups would be made in GTNH to make use of a lot of this stuff. Otherwise it's just a bunch more "Automation Magic" bloat that nobody really uses. I mean be honest, does anyone really use stuff like Thaumcraft Golems or the Assembly Halo?
> 
> Don't get me wrong, automating Botania stuff is actually really fun and fulfilling, but is this needed right now?

You dont need to use this mod but helps a lot since it means no more dropping of items, and no more lag, also it add advanced versions of spreaders and sparks , so it makes botania easy to handle

**Comment by combusterf** [comment]
Fun fact: I tried that, and it didn't work. NEI lexicon integration also only showed the item subtitle. In fact while I was testing the Alphirine it ate 50% of my items without giving anything back with no discernible pattern - and of course with no lexicon entry to explain why.

**Comment by EnderProyects** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/b483c0e7-2274-4c06-9f6c-b76c7e56f137)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/7aa24230-5bb6-4f02-b693-5026d5e30d01)
The bar is the chance percentage

**Comment by EnderProyects** [comment]
also I have dropped the lexicon and it works for me, tested a minute ago

**Comment by EnderProyects** [comment]
The NEI lexicon integration also works for me, so or you are doing something wrong or you dont like the mod and you're trying to pretend it doesn't work

**Comment by EnderProyects** [comment]
Solved, you now dont need gaia to progress with the ancient alphirine
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/2e2b8527-9d8e-4549-9a75-935f57a73b2d)

**Comment by EnderProyects** [comment]
@combusterf  If you want I can make alternate recipes for the ones that makes the ancient alphirine, more costly but with the 100% chance percentage

**Comment by EnderProyects** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/521065c1-0d44-4e4d-a460-170df7fb3de4)
Something like this, but I will not modify the first 3 ones

**Comment by Star-Tube** [comment]
I'm a tad new around here but I was wondering whether it wouldn't be better to make some sort of plan for how botania tiering should be in relation to the rest of the pack first? Setting up gates for botania tiers tied to main line quest tiers would probably make it easier to assess these recipes and their balance. Anyway that's my two cents as a noob down in HV.

**Comment by EnderProyects** [comment]
All this mod is tiered the same way as botania, but with components of thauncraft, twilight forest, botania and gtnh

**Comment by Alastors** [comment]
> I'm a tad new around here but I was wondering whether it wouldn't be better to make some sort of plan for how botania tiering should be in relation to the rest of the pack first? Setting up gates for botania tiers tied to main line quest tiers would probably make it easier to assess these recipes and their balance. Anyway that's my two cents as a noob down in HV.

It's sort of hard to tier a mod that has little direct application to the rest of the pack, especially given how many recipes we removed ourselves, but you aren't wrong we do need a more cohesive plan for the future, but I will also point out the magic sector of the pack, particularly Botania need more devs who want to apply their love to it

**Comment by combusterf** [comment]
@Star-Tube That's been documented here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9314

**Comment by PrezesE** [comment]
Do it! The more the merrier

**Comment by EnderProyects** [comment]
@combusterf I have lowered the tiers, so now you dont need gaia to get mithril if you dont want ( its more costly though), for nebula the same since it uses mithril in the recipe, the only recipes that now needs 100% gaia are the ones that uses mana nether stars and the nebula armour, also added qol recipes as well for the chance ones
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/e176d7de-1f54-4fd8-8eea-0426cb64649a)

**Comment by Chaoschaot232** [comment]
So we have this and like Dream a bunch of comments stated earlier also the Alfheim Mod, which is also an addition to Botania?
Sounds interesting.


> [...] but I will also point out the magic sector of the pack, particularly Botania need more devs who want to apply their love to it

I like everything around Magic Mods, incl. Botania (which I see as a mix between Tech X Magic). I would also like to have/see the latest Tainted Magic in the Pack but currently this seems to be on hold to?
What kind of help here is needed?
