### ISSUE TITLE
Charcoal to Coal Coke in Adv Coke Oven

### ISSUE THREAD

**Issue by Teykn** [GTNewHorizons/GT-New-Horizons-Modpack#10770]
### Your GTNH Discord Username

Teykn#4647

### Your Pack Version

2.1.2.1

### Your Server

Private Server

### Type of Server

Don't know

### Your Expectation

The Advanced Coke Oven not allowing charcoal to be cooked into coal coke

### The Reality

Charcoal seems to be able to convert into coal coke in the adv coke oven, despite no NEI recipe showing this. The only NEI recipe shown is for coal converting to coal coke, but not charcoal.

### Your Proposal

Remove ability for charcoal to be converted to coal coke

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
Why this issue is closed?

**Comment by cubic-chariot** [comment]
For the record, this is still an issue in 2.2.3; it slightly messes up automation because charcoal can be put both in the input slot and in the fuel slot.

**Comment by chochem** [comment]
@cubic-chariot there is an open ticket here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9093
