### ISSUE TITLE
Disassembling thermal cloths yields thermal chestplate

### ISSUE THREAD

**Issue by deraXyna** [GTNewHorizons/GT-New-Horizons-Modpack#10777]
### Your GTNH Discord Username

deraXyna#1601

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expected getting the crafting materials back from the thermal cloth.

### The Reality

Disassembling yields the chestplate for that tier.
Sometimes i get the materials that are used to craft the cloth.
Works for T1 and T2 cloth.
![image](https://user-images.githubusercontent.com/32879367/180054560-1e53a926-c3a8-4428-95cd-04a9c772f29f.png)

### Your Proposal

Either disable the cloth in the disassembler or remove the armor from possible results

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1044
