### ISSUE TITLE
aluminum hydroxide recipe in small chem reactor eats cells

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#10774]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.1.2.4 20 pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Cells should be returned

### The Reality

![image](https://user-images.githubusercontent.com/49487505/179997988-ff281432-3353-4ca2-baed-2cde5eaa0d9a.png)

3 cells are eaten on craft

### Your Proposal

make recipe not eat cells

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
switch the cell into a fluid and voilà ez fix

**Comment by GlodBlock** [comment]
no, the fluid input slot is already occupied by carbon dioxide

**Comment by chochem** [comment]
I have talked with miozune and glod and this fix did not really work because the recipe is specifically for MV but now it needs and LCR, so HV. We didnt come up with a good solution yet. recommendations very much welcome.

**Comment by tommy307507** [comment]
I am playing through the latest 20pre with the chem rebalancing rn, and this is my experience on the latest changes. 
I am not sure if this is relevant, but with the fact that most electrolyzer recipes returning raw silicon dust and aluminum dust instead of the aluminum oxide or silicon oxide, getting alu in mv is actually a hassle, as you cannot smelt aluminum dust until nichrome, which is locked either by coolant or the vac (massive alu dump) 

The goto electrolyzer recipe I found is still clay electrolyzing, and for processing minerals, this is the only way to get (massive amounts of) alumina. And with the chem rebalancing, you do need quite a massive amount of alumina. 
Compared to the previous version (2123qf), aluminum and silicon are nerfed by a lot and I was surprised by how little alu came from a lot of clay....
well, this would be a good incentive for the player to setup a bit of a processing for getting alumina this way
So it's important that this works in mv, my suggestion would be adding another step in between for singleblocks.
