### ISSUE TITLE
Playing with MultiMC

### ISSUE THREAD

**Issue by sleepycakepop** [GTNewHorizons/GT-New-Horizons-Modpack#10776]
### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Actions

The game isn´t even starting. It´s crashing immediately, but Vanilla is working absolute fine.

### Crash Report

[Log.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9152430/Log.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
you need to use java8 not java17.

**Comment by sleepycakepop** [comment]
> you need to use java8 not java17.

Ahh ok thank you.
