### ISSUE TITLE
"Glider Wings" quest should use optional tasks.

### ISSUE THREAD

**Issue by KydZombie** [GTNewHorizons/GT-New-Horizons-Modpack#10778]
### Your GTNH Discord Username

KydZombie#6090

### Your Pack Version

2.1.2.3

### Your Proposal

The "Glider Wings" quest in "Getting Around Without Dying" should use optional tasks for the 1st and 2nd tasks.

### Your Goal

Other parts of the quest book have started using optional tasks leading up to the final end product.

### Your Vision

Reflect the changes made in other areas of the quest book, and then you don't accidentally make a glider and then have to re-craft 2 unneeded glider wings.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/180067499-1196fcf4-2cf1-43d5-8145-38388a05e8ed.png)

fixed in dev already
