### ISSUE TITLE
Add Iron,Steel,Diamond etc Slightly larger Chests

### ISSUE THREAD

**Issue by Atomic203** [GTNewHorizons/GT-New-Horizons-Modpack#10785]
### Your GTNH Discord Username

Atomic#5169

### Your Pack Version

2.1.2.4-dev18

### Your Proposal

i would like the chests from the iron chests mod to get a Slightly Larger Version of them i hope u understand what i am trying to say

### Your Goal

Well if those chests are added they will just look nice/clean

### Your Vision

ppl wont have to look at those lame normal iron chests

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by NoriSilverrage** [comment]
I was just thinking about this yesterday. I use slightly larger chests a lot with AE2 as temp buffers because they seamlessly fit with the surrounding full blocks. But sometimes I need something bigger, like a iron, gold etc chest.
