### ISSUE TITLE
Industrial Greenhouse can't plant Nether warts,sugar cane, carrots ,potatos and such crops

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#10786]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.2.4-18

### Your Proposal

Why such a super machine can't even plant mincraft vanilla crops???

### Your Goal

Since this is a great machine for farming so it should be compatable with at least all the minecraft vanilla crops.
Not only pams and wheat like seed crops

### Your Vision

Its a balance of the cost of the machine
expensive(IV accelerators,EIO farm as materials) but limited functions

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Josh5minus1** [comment]
There's like workaround for that, for example: carrot seeds, potato seeds, etc. which works with the multi
