### ISSUE TITLE
Kinetic generators are too cheap

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#10784]
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

qf

### Your Proposal

Kinetic generators are too cheap.

Yes, kinetic needs a turbine, but quite fast you come to an indestructible turbine.
Water kinetics requires a certain biome, but witchery can make you a needed one pretty fast.
Those are just little inconveniences. Setting up them is pretty easy. Nothing really to connect, just put some water, kinetic, cable, and you are done.

Very same function with solar panels, solars are slightly more convenient.

But now let's compare the number of resources to make a Water kinetic.
It is just 4 EV circuits. 2 for kinetic, and 2 for kinetic water generator.
Other than that just some steel, stainless steel and HV components. These resources are almost free at this stage and are required in very little amount.

Let's look at solar panel.
It requires 4 EV superconductors. 4 IV circuits. Uranium, sunnarium, tons of other staff.
And because it works only during the day, we may double those resources to get the same outcome as kinetics.

Final comparison is
4 ev circuits with some almost free other HV staff.
vs
8 iv circuits + 4 ev superconductors + expensive ev staff.

The final price is about 5x bigger for the same outcome.
And that is just for convenience?

Compare to huge steam/combustion turbines, nuclear power.
Kinetics are too cheap and too convenient. Even the wind one. Wind one is still too cheap even if sometimes u lose that extra energy.

I am already playing the third or fourth time and kinetics are always too good to avoid them, and other options compared to kinetics are too bad to use them.

Kinetics need to be at least 2x times more expensive.

### Your Goal

Kinetics are too OP, or solars are too expensive. Increase the price of kinetics.

### Your Vision

It will make free kinetics challenging.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by nikitinalexx** [comment]
To be honest I don't like kinetics because they are too straightforward. Just have enough resources, and recursively update them and they will get you up to ZPM.

**Comment by Steelux8** [comment]
Kinetics are much weaker if you do not use the tools GT++ added for them. One of the things added by it were the turbines that never get destroyed. I want to look at this and rebalance this type of powergen, but I currently have my hands full with other IV power generation setups.

**Comment by nikitinalexx** [comment]
Could you please put it into your far away to do list, so eventually it would be done sometime

**Comment by Steelux8** [comment]
Since it's GT++, I feel obligated to do it. However, I really have no idea how the setup works, or how it's coded, so it will take a while. I will at least have to make a new multiblock for HOG processing and then evaluate the Rocketdyne and the LFTR before I look at kinetics.

**Comment by Hikari1nVoid** [comment]
I won't call it too cheap unless it can provides a constant 512Eu/t output(2048 for EV 8192 for IV,etc).It still use space as a resource. You have to constantly chunkloading your generator fields and That's the limit for Wind kinetic energy(I'm assuming nobody is using water kinetic since there's even no ocean biome in this pack)
For GTPP rotor they do sucks.We may set another standard for the rotors just like GT turbines .

**Comment by greesyB** [comment]
> I won't call it too cheap unless it can provides a constant 512Eu/t output(2048 for EV 8192 for IV,etc).

Kinetic generators provide constant 1.2A of tier power for water, and up to 3A of tier for wind (variable).

> It still use space as a resource. You have to constantly chunkloading your generator fields and That's the limit for Wind kinetic energy(I'm assuming nobody is using water kinetic since there's even no ocean biome in this pack)

Water kinetics are absolutely viable with river biomes and the various methods of changing biomes. I used them and several others have as well.

> For GTPP rotor they do sucks.We may set another standard for the rotors just like GT turbines .

The good rotor (iridium) is gt++.

Kinetics could stand to be a little more expensive imo, though we shouldn't go overboard. Kinetics come in a tier that has a lot of power diversity, and nerfing them too much would simply make people not use them.
