### ISSUE TITLE
Solar panel abnormal loading server

### ISSUE THREAD

**Issue by simbiant** [GTNewHorizons/GT-New-Horizons-Modpack#10787]
### Your GTNH Discord Username

SimbiAnT29#7106

### Your Pack Version

2.1.2.3qf

### Your Server

private server ultra mine

### Your Expectation

I faced low tps on my server and started checking what could load server with spark, people in discord noticed abnormal loading of ic2 energy in profiler, so I created a ticket
![image](https://user-images.githubusercontent.com/24406976/180220910-5336a019-817f-43a2-aaa7-70a0e3a9857d.png)
https://spark.lucko.me/V5V6SxiWWS

Main energy producing are solar panels.
![image](https://user-images.githubusercontent.com/24406976/180221508-530c7a2a-081b-4f98-94d6-e7d7ddef43ff.png)

### The Reality

-

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by simbiant** [comment]
Due to quantity of panels, maybe its normal
P.S. there were 400 solar panels in total

**Comment by repo-alt** [comment]
62ms is still bad, even for 400, it may be regared as a stress test revealing a problem

**Comment by boubou19** [comment]
as usual, it's IC² energy code causing the issue: the GT part of it takes only 3%. Altho, 0.105ms per solar is too high, we never saw that on the officials, (and i'm a solar enjoyer). So either you hit a edgecase, or your server run onto something weaker than the officials. Nevertheless, it's still an issue we need to solve, either by implementing direct GT5U Enet support in Super Solar Panels, but that would only benefits for Super Solar Panels, or we hack IC² once again to make their shitty ENet code efficient.
