### ISSUE TITLE
Parametrizer X broken

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10791]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-18-pre

### Your Server

SP

### Your Expectation

One should be able to set a parameter as a double by using the pointer to select a bit and then change that bit.

### The Reality

In reality the pointer only reaches half the bits. While it does go from 0 to 63 decimal (gui is in hex), the values x and x+32 point to the same bit. Thus it is only possible to change half the bits of the double. In particular, the exponent bits are unreachable making this hatch completely broken.

### Your Proposal

Probably a simple fixable bug somewhere, maybe a float/double type mismatch or similar. I cant fully understand the code though.

However, there is also the option to just disable the hatch and remove the recipe, Even functional the hatch is worse then the normal one

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
https://github.com/GTNewHorizons/TecTech/pull/58
