### ISSUE TITLE
Travel Anchor Config Doesn't work

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#10795]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.4-14-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I wanted to build buildings far away from each other in personal space void dimension, so i can save some fps, 
expected to use anchors to travel between builings,

### The Reality

I cant reach anchor when its futher then 128 blocks(config is set to default 512)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
what's the server render distance (or your render distance if you play on singleplayer)?

**Comment by LewisSaber** [comment]
it was 7 when i first trie but increasing it to 10+ didnt help

**Comment by boubou19** [comment]
512 blocks is 32 chunks. Try setting the config to 160 blocks (10 chunks) then retry with a render distance of 12. It should work. If it doesn't then it's indeed a bug.

**Comment by LewisSaber** [comment]
![image](https://user-images.githubusercontent.com/39595617/180421814-c4c3b775-99dd-48dd-bbe7-3f078fb86d42.png)
![image](https://user-images.githubusercontent.com/39595617/180421848-022af9a8-55ba-4186-ab9c-7bc377a92f17.png)
tried to change to a lot of diffrent rendering distances but none of them worked(im holding staff of traveling in hand, placing anchor at same distance didnt help too)

**Comment by vlaetansky** [comment]
@boubou19 Can you please assign me on this?
