### ISSUE TITLE
Required in NEI bee tree 

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#10790]
### Your GTNH Discord Username

Кетцаль#0802

### Your Pack Version

2.1.2.1

### Your Server

Server Zvezdolet

### Your Expectation

I can't see what is required in the bottom recipe.  
And the top requires the wrong place to hold

![image](https://user-images.githubusercontent.com/17906427/180307435-67a83347-3bc3-4524-b202-c1edb548e8fa.png)

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
BeeBetterAtBees is All Rights Reserved so we can do nothing about this
