### ISSUE TITLE
[RFC] Change TecTech Energy Infuser to not be a meme

### ISSUE THREAD

**Issue by minecraft7771** [GTNewHorizons/GT-New-Horizons-Modpack#10809]
### Your GTNH Discord Username

minecraft7771#0427

### Your Pack Version

2.1.2.3QF

### Your Proposal

Currently the Energy Infuser (which probably almost no one knows about) can recharge items in the slot of the controller GUI. While doing so it has a loss of 3.125%. The machine is crafted at UV or higher using various UV components, which is pretty ridiculous when you consider that its just a huge battery charger.
My proposal would be to make the charge lossless and to also make it repair things, kinda lika an electric version of the thaumic restorer. It could use up for example UU-Matter to repair the durability. Of course this would also need a blacklist of items that can't be repaired.

### Your Goal

Right now the Energy Infuser is neither good nor well known. With the ability to repair stuff it might get more known among the magic haters and of course it would also be somewhat worth its price.

### Your Vision

The Energy Infuser would be less of a joke and somewhat viable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
that sounds nice. I think we have 2 magical but no tech based solutions to repairing items yet. This is a lot higher tier so should be completely fine in terms of balancing as long as it cant do turbines I guess.

Even better if you implement it yourself which you seem to be considering, its nice to have someone working a bit on tectech fixing/improving/documenting things. :)
