### ISSUE TITLE
Multiblock Casing From NEI

### ISSUE THREAD

**Issue by henrydukepickle** [GTNewHorizons/GT-New-Horizons-Modpack#10801]
### Your GTNH Discord Username

henryduke#0140

### Your Pack Version

2.1.2.4-18

### Your Proposal

when viewing the recipe for a multiblock's controller from NEI, there should be an option to easily view the recipe for all of the casings used in said multiblock (I feel I should note here that I have no idea if this suggestion would be easy or difficult to implement, so if there is no easy way to implement it, don't bother).

### Your Goal

Especially for bigger/more complicated multis (assline, DTPF, molecular transformer, etc) it can be a pain to manually search the name for each of the casings required- especially when some of them have very long and specific names.

### Your Vision

It would generally make building and researching a multiblock a more fluid task.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Added in https://github.com/GTNewHorizons/BlockRenderer6343
