### ISSUE TITLE
Witchery Mod Vampire's skill the world replicates the Compressed Solar Panel

### ISSUE THREAD

**Issue by wohaopa** [GTNewHorizons/GT-New-Horizons-Modpack#10806]
### Your Pack Version

2.1.2.3qf

### Your Proposal

In Witchery Mod, vampires have a skill called The World. It can duplicate some blocks placed on the ground. The Electro-Magic Tools Mod for Compressed Solar Panel is also included.

### Your Goal

I think it seriously affects the balance of the generator, it makes all the other generators look like a joke.

First become a vampire and gain the The World skill.
As shown in figure to place.（The foot block is the same height as the block to be copied. The block to be copied needs to be kept at a distance from the player. ）
![2022-07-23_22 49 11](https://user-images.githubusercontent.com/30284813/180611328-cf03e941-f6f7-4ed9-8e23-147f6572a842.png)

Hold the Witches Hand to the sky and hold the right mouse button. Release the mouse when you hear the third tone.
![2022-07-23_22 49 27](https://user-images.githubusercontent.com/30284813/180611545-9995e706-f5c7-40d9-8149-1c44defc3eca.png)
Get three!
![2022-07-23_22 49 41](https://user-images.githubusercontent.com/30284813/180611555-704063fd-0351-4365-9e7f-826a91cb56e2.png)

### Your Vision

Make it impossible to replicate Compressed Solar panels. Do not disable this skill. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Shibva** [comment]
that skill sounds like a progression break in general

**Comment by wohaopa** [comment]
I tried to solve the problem. I found the problem code `com.emoniph.witchery.infusion.infusions.InfusionOverworld.ShockwaveTask.drawPixel()`. It's [here ](https://github.com/GTNewHorizons/Witchery/blob/4b7a98b60de7901e3503247016aa90c90099d0ce/src/main/java/com/emoniph/witchery/infusion/infusions/InfusionOverworld.java#L360)on Github. I don't have the ability to modify it with mixins.

**Comment by wohaopa** [comment]
And it's called a shockwave. It can copy many things, such as dragon eggs.
