### ISSUE TITLE
Add additional machine recipes for Natura fruits

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#10817]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.4-dev28

### Your Proposal

Add Compressor recipes for the following Natura crops:

8x Stingberry -> 1x Plantball
8x Skyberry -> 1x Plantball
8x Duskberry -> 1x Plantball
8x Blightberry -> 1x Plantball
8x Raspberry -> 1x Plantball
8x Blueberry -> 1x Plantball
8x Blackberry -> 1x Plantball

Add Compressor recipes for the following Minecraft vanilla items:

8x Melon (slice) -> 1x Plantball
1x Melon (block) -> 1x Plantball
8x Cactus -> 1x Plantball
8x Lily Pad -> 1x Plantball

### Your Goal

To ensure these fruits have comparable uses to their Pam's Harvestcraft equivalents.

### Your Vision

To unify these fruits' functionality with their Pam's Harvestcraft equivalents.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
already seem to exist in dev:
![image](https://user-images.githubusercontent.com/40274384/180646434-7cf8e05c-d524-46eb-8c74-b72bf00bec7f.png)
![image](https://user-images.githubusercontent.com/40274384/180646427-6d652470-6a77-47cb-a5b6-8fd64579048a.png)
![image](https://user-images.githubusercontent.com/40274384/180646457-bc3adc46-ce56-4ba8-b6ca-59747f0f1e3a.png)

**Comment by TwoTailedFox** [comment]
In Dev-28, the Nature Stingberry, Skyberry, Duskberry, Raspberry, Blueberry and Blackberry don't have Compressor recipes to make Plantballs. In addition, also noticed that a few plant-based vanilla items also don't have Compressor recipes.

**Comment by chochem** [comment]
can you update the list in the post?

**Comment by TwoTailedFox** [comment]
Done

**Comment by ShyZShark** [comment]
From the sounds of this, Vanilla Melon Slices and Melon Blocks, should be converted to a Plantball...
In 2.8.4, this isn't working, if it was previously.
