### ISSUE TITLE
OC pattern returns wrong output

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#10810]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.4-18-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Expected
components.me_interface.getInterfacePatter(1).outputs to return table of outputs of first pattern

### The Reality

I get nil if amount of outputs > 32

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vlaetansky** [comment]
@repo-alt can you assign me on this?
