### ISSUE TITLE
Crop Manager operation mode, buffer size

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#10819]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

2123qf

### Your Proposal

A few thoughts about the crop manager:
- Imo the energy buffer size is too large (LuV takes like 6bil EU)
- when the output storage is full, it stops watering/fertilizing
- u can place trash items in the weed-ex slot
- also, It would be nice if there would be an option to disable harvesting on the crop manager. This way it would be possible to use a larger farmland as a breeder farm.

### Your Goal

.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by trollolal** [comment]
Follow-up suggestion, you regulate operation size for crop manager
and you can have a void mode to let it void excess item

**Comment by boubou19** [comment]
i'd also add a mode to harvest crops asap (useful for oreberry crops for exemple)
