### ISSUE TITLE
Remote IO disconnect AE Channels or maybe reset configs by chance every start of the game

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#10814]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.2.4-18

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Use RIO interface to bind a me controller and insert the AE transmition upgrade to transport AE channels longsistance(not cross dimension)

### The Reality

It works good when you are playing
But after every launch of the game, it happens to disconnect the AE dense smart wires

Not only I but many players suffered this issue
(As an uploader,I have some fansof mine reported this too)

### Your Proposal

Please check this mod if this mod is still aloud to be used in GTNH
I doubt this RIO not lost its settings because if you reconnect the wire it also works.
But just dieconnecting the cables

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
It is not forbidden but is not supported either. I myself regard it as an expoit. Maybe some other dev will disagree and fix it.

**Comment by KamenriderZO** [comment]
> It is not forbidden but is not supported either. I myself regard it as an expoit. Maybe some other dev will disagree and fix it.

My dear Master Repo, I have chased your contribution to this modpack a lot.
I know you have added beekeeper upgrade to OC
and Backbone smart cable for AE
and also asked me a question about OC
I'm your fan and respect you a lot.
Could you or introduce someone help us this favor?
Because RIO is really interesting when someone has good imagination and can do cool things.
