### ISSUE TITLE
[Suggestion] Add Program Circuit for Rock Breaker

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#10812]
### Your GTNH Discord Username

tim lam

### Your Pack Version

GTNH-1.7.10-2.1.2.4-18-pre

### Your Proposal

Add Program Circuit for Rock Breaker to select create which block so it wont clog the machine when it is run out of input

### Your Goal

GoL

### Your Vision

QoL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TwoTailedFox** [comment]
The lack of this feature is highly annoying. I just want it to output Obsidian, and not push out Cobblestone when it runs out of Redstone.
