### ISSUE TITLE
Furnace not smelting when a bit far or reconnecting

### ISSUE THREAD

**Issue by Panbati** [GTNewHorizons/GT-New-Horizons-Modpack#10818]
### Your GTNH Discord Username

mclovin#0261

### Your Pack Version

1.17.10

### Your Server

SP

### Type of Server

Vanilla Forge

### Your Expectation

Trying to automate crushed ores going to a macerator and being fed into a furnace.
The furnace should then cook it and drop it into a hopper which leads into a chest. 
The furnace also has a hopper connected to it which feeds it fuel

### The Reality

Once in a while, when I reconnect or go a few blocks away (@ 30), the furnace just stops smelting completely even though the ore and fuel are there. The picture will show Ground Cassiterite Sand with Charcoal. 
![image](https://user-images.githubusercontent.com/26098924/180651023-23ccded5-17ec-4145-b397-7a1b903ec2a7.png)

This is the setup 
![image](https://user-images.githubusercontent.com/26098924/180651035-e6f357a3-33ab-4e20-a75f-25508fcfe3b6.png)

### Your Proposal

Furnace shouldn't stop smelting unless I leave the chunk (as intended in vanilla I guess?)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNHAfx237v7** [comment]
Pack version is not the MC Version, current stable release is 2.1.2.0 iirc.
30 blocks is definitely outside of the chunk that the furnace is in, as a chunk is 16x16. What is your render distance? Sounds like the furnace is just outside of the chunks that are loaded.

**Comment by Panbati** [comment]
Ah sorry, I'm playing on 2.1.2.3, The view distance on the server properties in 7 and on my own launcher its 12.

**Comment by leagris** [comment]
The vanilla furnace might not tick smelt when too far away as its attached TileEntity which is what is ticking to computes the smelting process is frozen until you come back in range to load chunk. So on your server is 7 blocks away. Although, the furnace might still look lit because it uses a different Block to render it as lit furnace. So might still appear lit even if the TileEntity is frozen  awaiting proximity activation.
