### ISSUE TITLE
Long Distance Pipeline Suggestions

### ISSUE THREAD

**Issue by Teykn** [GTNewHorizons/GT-New-Horizons-Modpack#10815]
### Your GTNH Discord Username

Teykn#4647

### Your Pack Version

2.1.2.1

### Your Proposal

Either the questbook should list that Vertically placed Long Distance Pipeline Pipes count as half of a block of distance, or vertically placed long distance pipeline pipes should count as a full block of distance.

### Your Goal

To prevent players from being confused as to why items are not being transferred when it is assumed that enough pipeline pipes are used.

### Your Vision

It would prevent a lot less confusion to players who want to use Long Distance Pipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by trollolal** [comment]
Originally it set the restriction as many people spam LDPE to transfer item in a short distance due to its cheap recipe
It set the vertical count as half as people just build up to an intermediate point and then transfer down to the desired location

**Comment by Teykn** [comment]
Isn't there a taxicab distance that prevents building up that high and then building all the way down? I was told that you cannot zig-zag to artificially increase the LDP distance
