### ISSUE TITLE
Clean up DD VM list a bit

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10827]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-18-pre (+some updates)

### Your Proposal

Some ore have been added lately all of which get added automatically to VMs in the DD. Many of those are probably unintended and should be removed. Either they shouldn't generate ores or they should be changed with the weight/blacklist config we now have here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/GTNewHorizons/dreamcraft.cfg

Of course maybe Colen wants to go further and remove some older ones for balancing reasons ;)

The recent additions I am looking at are: SiliconSG (*), CalciumDisilicide, Calciumhydride, AluminiumFluoride, roastedIron, roastedNickel

(*) While those were probably all unintended, it has been requested heavily by some late game players that SiliconSG should stay and I think that makes sense. :)

This is ontop of the old list assembled here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7916

So a full cleanup would really be needed. But that also changes relative weights for the remaining ones. I guess I mostly pointing out unintended new additions in the 2.1.2.4 dev versions here.

I have been trying to look into the code and I am not sure but its probably the |8 and addOreItems() in the GT materials file that add the Ores and crushed/etc variants. For roasted iron/nickel that needs to stay I guess for the crushed form so the blacklist might be the easier option there.

### Your Goal

Void miners should not make weird stuff.

### Your Vision

Void miner would be smoother.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Connor-Colenso** [comment]
I agree the VM list needs a cleanup the issue is no one could agree on what should be removed. I.e. fusion materials etc. Really the DD is a very bad bandaid for endgame resource gen.
