### ISSUE TITLE
Add iron catalyst to ammonia receipe

### ISSUE THREAD

**Issue by YanFett** [GTNewHorizons/GT-New-Horizons-Modpack#10824]
### Your GTNH Discord Username

reverse71

### Your Pack Version

18dev

### Your Proposal

The production of ammonia is based on the Haber-Bosch route.
The mechanism is long known to require an iron surface as a catalyst besides high pressure and temperature.
Like in the receipe for 2-Ethyl-1-Hexanol you could add a persistent iron plate to the receipe, to make it a little more realistic.

### Your Goal

More realistic chemistry!

### Your Vision

More realistic chemistry!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by trollolal** [comment]
To add more complexity, I think it can replace the recipe that require tiny pile of iron dust or 9x with full iron dust with some energy discount. So it can force some people to do the fermented biomass route.

**Comment by chochem** [comment]
The best way to support a catalyst would be to replace it by a chemplant recipe. The LCR plate 'catalysts' are a bit silly.

 An iron based 'red metal catalyst' already exists. So that would be perfect.
