### ISSUE TITLE
launch crash

### ISSUE THREAD

**Issue by valerka-php** [GTNewHorizons/GT-New-Horizons-Modpack#10826]
### Your Pack Version

2.1.2.3-1.7.10

### Your Server

-

### Your Actions

just try to launch
![config](https://user-images.githubusercontent.com/81385130/180824534-f0364921-8244-41d8-ac03-dea48c84dcee.png)

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9182939/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
ftb launcher is not *fully* supported. best try MultiMC or technic.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev with a supported launcher, please leave a comment to re-open with a full log report of the crash.
