### ISSUE TITLE
Bug with disassembling lv machines

### ISSUE THREAD

**Issue by Atomic203** [GTNewHorizons/GT-New-Horizons-Modpack#10829]
### Your GTNH Discord Username

Atomic#5169

### Your Pack Version

2.1.2.4-dev18

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

i tried dissembling lv machines and i expected to get a electronic circuit from them as i crafted them with a electronic circuit

### The Reality

after disassembling the lv machines i got a microprocessor instead of a electronic circuit 

### Your Proposal

Make some sort of a system where like u craft a lv machine for example with a electronic circuit if u put it in the disassembler u get electronic circuits but if u make the lv machine with like microprocessors when u disassemble that machine u get microprocessors and i am not sure if this thing happens with higher tier stuff too like for example there are multiple ev circuits u craft a ev machine with like a quantum processor (ev circuit) and when u disassemble that ev machine u get like a completely different circuit this is the thing i am not sure if it happens or not but this new disassembler thing would be great if it is added

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
While the Microprocessor is indeed a "higher tier" one, as in you make it later, it makes sense that you get that back. For every disassembler recipe you (alteast should) get back one that can't be upgraded any further so players can't take advantages. The Microprocessor does this, you can't upgrade it any more.

> Make some sort of a system where like u craft a lv machine for example with a electronic circuit if u put it in the disassembler u get electronic circuits but if u make the lv machine with like microprocessors when u disassemble that machine u get microprocessors

This was the state of the system a while ago from what I heard. I don't know the details why it was changed but I'd imagine that non stackable machines, which would be a result, are a nightmare. Especially if you want to use them in a PA.

**Comment by Atomic203** [comment]
> While the Microprocessor is indeed a "higher tier" one, as in you make it later, it makes sense that you get that back. For every disassembler recipe you (alteast should) get back one that can't be upgraded any further so players can't take advantages. The Microprocessor does this, you can't upgrade it any more.
> 
> > Make some sort of a system where like u craft a lv machine for example with a electronic circuit if u put it in the disassembler u get electronic circuits but if u make the lv machine with like microprocessors when u disassemble that machine u get microprocessors
> 
> This was the state of the system a while ago from what I heard. I don't know the details why it was changed but I'd imagine that non stackable machines, which would be a result, are a nightmare. Especially if you want to use them in a PA.

what do u mean by u cant "upgrade" the microprcoessor if u mean like upgrading a circuit from a tier to a higher tier the microprcoessor can be indeed upgraded to a mv circuit
![image](https://user-images.githubusercontent.com/97828365/180944216-96ad95de-8ca9-4e38-af6f-693276da9c7a.png)

**Comment by minecraft7771** [comment]
> what do u mean by u cant "upgrade" the microprcoessor if u mean like upgrading a circuit from a tier to a higher tier the microprcoessor can be indeed upgraded to a mv circuit

Its true that you can build the "Good Electronic Circuit" with it. Though that can be build with any LV-tier circuit. While the "Good Integrated Circuit" needs specific LV-tier circuits, and this MV one can be upgraded further to HV. I guess you could return the "Electronic Circuit" instead of the Microprocessor but what really would it change? The uses are exactly the same, both can't be upgraded any more than once plus if you do give the Microprocessor its less annoying for later tiers since then you already use Microprocessors everywhere.

**Comment by Atomic203** [comment]
> > what do u mean by u cant "upgrade" the microprcoessor if u mean like upgrading a circuit from a tier to a higher tier the microprcoessor can be indeed upgraded to a mv circuit
> 
> Its true that you can build the "Good Electronic Circuit" with it. Though that can be build with any LV-tier circuit. While the "Good Integrated Circuit" needs specific LV-tier circuits, and this MV one can be upgraded further to HV. I guess you could return the "Electronic Circuit" instead of the Microprocessor but what really would it change? The uses are exactly the same, both can't be upgraded any more than once plus if you do give the Microprocessor its less annoying for later tiers since then you already use Microprocessors everywhere.

well returning the electronic circuit would make a little more sense and wont be a little strange to ppl its just weird like u use a electronic circuit to make a machine u disassemble it u get microprocessors its just a little weird so thats why i think this change should improve ppls experience a little teeny tiny bit

**Comment by miozune** [comment]
Any of LV circuits being able to be used to make Good Electronic Circuit is not intended.
`GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Board_Phenolic_Good.get(1L), GT_ModHandler.getModItem("IC2", "itemPartCircuit", 2L, 0), ItemList.Circuit_Parts_Diode.get(2L), GT_OreDictUnificator.get(OrePrefixes.wireGt01, Materials.Copper, 2)}, tMat.getMolten(144L * tMultiplier / 2L), ItemList.Circuit_Good.get(1L), 300, 30);`
We started working on backporting RecipeBuilder, hopefully we also work on RecipeInput, so that we have proper oredict handling.

**Comment by chochem** [comment]
no longer relevant
