### ISSUE TITLE
Add a quest in lv questline for lv disassembler

### ISSUE THREAD

**Issue by Atomic203** [GTNewHorizons/GT-New-Horizons-Modpack#10823]
### Your GTNH Discord Username

Atomic#5169

### Your Pack Version

2.1.2.4-dev18

### Your Proposal

Add a quest in lv questline for lv disassembler

### Your Goal

lv disassembler should be a quest as it is a somewhat important machine

### Your Vision

by adding a quest for lv disassembler in the lv questline ppl would know that exists the lv disassembler is a important machine and i really think it should be added as a quest

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
disassembling machine is cool and all to get back few materials from your old machines. But when your machines will blow up, you'll be happy to have the old set of machines so you can recover quicker than recovering from scratch. Also the disassembler is subject to allow dupes for some weird recipes. Imo it shouldn't be encouraged to use. You'll need way more than what you recover from the disassembler anyways.

**Comment by Atomic203** [comment]
> disassembling machine is cool and all to get back few materials from your old machines. But when your machines will blow up, you'll be happy to have the old set of machines so you can recover quicker than recovering from scratch. Also the disassembler is subject to allow dupes for some weird recipes. Imo it shouldn't be encouraged to use. You'll need way more than what you recover from the disassembler anyways.

tho dont ppl just load backups when a explosion happens and ppl would want to recycle some of there lv machines when they reach mv and make mv machines and ik u can make a mv disassembler there is a quest for the mv disassembler but u need like 73 aluminium to make the mv disassembler and after the aluminium nerf i think the lv disassembler should be added as a quest cuz whos got 73 aluminium in early mv

**Comment by chochem** [comment]
we could move the MV quest to LV (and require the LV one ofc). That would not be any _additional_ encouragement but the info would be there from the start.

**Comment by boubou19** [comment]
>tho dont ppl just load backups when a explosion happens

just because people don't play the game how it's intended to be doesn't grant them the right to get unfair advantages.

**Comment by Atomic203** [comment]
> 

i dont see how loading a backup is a unfair advantage

**Comment by boubou19** [comment]
loading a backup for another reason than to avoid a bug/corruption is just nullifying the downsides of dangerous setups or the consequencies of a mistake. Therefore, in comparison to players on a server who can't restore and effectively suffer the downsides or consequencies, players restoring backups are just cheating. They play how they want, but their play style shouldn't be taken into account when balancing stuff, as they are already bypassing the current balance of the things, and we have no guarantee that players wouldn't bypass/cheat again.

**Comment by Atomic203** [comment]
> loading a backup for another reason than to avoid a bug/corruption is just nullifying the downsides of dangerous setups or the consequencies of a mistake. Therefore, in comparison to players on a server who can't restore and effectively suffer the downsides or consequencies, players restoring backups are just cheating. They play how they want, but their play style shouldn't be taken into account when balancing stuff, as they are already bypassing the current balance of the things, and we have no guarantee that players wouldn't bypass/cheat again.

well either way maybe ur correct there but whats gonna heppen the quest gonna be added or no?

**Comment by boubou19** [comment]
As @chochem said, the quest already exists, but is MV, so maybe move it in LV so people are aware of that option sooner.

**Comment by Atomic203** [comment]
> As @chochem said, the quest already exists, but is MV, so maybe move it in LV so people are aware of that option sooner.

alright so i guess thats a yes so we done here? should i close the ticket? (also sorry i am kinda new to github tickets i dont know how things happen)

**Comment by chochem** [comment]
no just leave it. will be closed once its done.

**Comment by Atomic203** [comment]
> 

ok
