### ISSUE TITLE
Something incorrectly overwrites formaldehyde (and other rocket fuel chemicals) blocking the normal crafting process

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10847]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-18-pre (+some updates)

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

To have a functioning rocket fuel crafting process.

### The Reality

Something incorrectly replaces formaldehyde, hydrogen peroxide (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10208), and possibly other gt++ chemicals with their variant from lanthanides (old botdustry stuff).

Specifically for formaldehyde the cells look like the gt++ variant and have that tooltip, but when putting them into a tank or hatch they turn into the (for this) useless bartworks variant.

In the case of formaldehyde that replacement makes it impossible to continue to craft the green rocket fuel (H8N4C204). One has to go back and turn it back into the proper formaldehyde variant and then take care to never use cells.

### Your Proposal

Stop chemicals in the rocket fuel chain from being overwritten.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I guess its not bartworks actually, changed those parts of the ticket. :)

**Comment by chochem** [comment]
ok I found an 'explanation' in the logs as to what is causing this:

![image](https://user-images.githubusercontent.com/40274384/181642685-7bc22ff9-afdd-42ec-a939-24e5b3403ad4.png)
![image](https://user-images.githubusercontent.com/40274384/181642724-6b4dedf1-c586-4dbe-9757-7f5ebcfa1dc0.png)

Though I dont know where the code for that is.

I can only come up with 2 good solutions:
Either
1) they are treated as 2 completely separate fluids. Or
2) one is removed in favor of the other.

**Comment by Elisis** [comment]
BW often replaces other materials in recipe outputs in favour of its own, so this isn't surprising. Moving these fluids to Coremod/GT5U would likely be preferable but I can see whether I can alter the recipe to have the GT++ fluids as output
