### ISSUE TITLE
Railcraft higher tier tanks should have better throughput

### ISSUE THREAD

**Issue by AlbertoPirillo** [GTNewHorizons/GT-New-Horizons-Modpack#10849]
### Your GTNH Discord Username

AlbyNexus#4160

### Your Pack Version

2.1.2.0

### Your Proposal

Railcraft higher tier tanks (e.g. Aluminium, Stainless, Titanium, ...) valves should be able to accept and output a much higher amount of fluid (according to their tier) w.r.t. the regular iron and steel tank valves

### Your Goal

Higher tier tanks have larger capacities but their valves are limited to 20KL/s just like regular iron and steel tanks.
I think that this limits a lot the applications for these tanks. 

### Your Vision

Those tanks would become actually useful: for instance, right now running a steam turbine with a Manyullyn Large Turbine requires 4 valves.  Or a 100% efficiency LHE requires 15 valves to input the fluid into the tank without wasting any.
This is clearly impractical. But with the proposed changes it will become feasible.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
this is slightly different but works as a fix right? https://github.com/GTNewHorizons/Railcraft/pull/26

**Comment by AlbertoPirillo** [comment]
I didn't get it, was a bug limiting the throughput? It is higher now?

**Comment by chochem** [comment]
you can now use a pump of any tier. apparently that wasn't a mechanical restriction but just a bug.

**Comment by AlbertoPirillo** [comment]
Interesting. Thanks for your efforts.
I'm closing this since it works as a fix.
