### ISSUE TITLE
Ardite nuggets are weird

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#10842]
### Your GTNH Discord Username

repolainen#0483

### Your Pack Version

GTNH-1.7.10-2.1.2.4-18-pre

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

You can dupe Ardite nuggets with Thaumcraft and platinum, but you get TiC nuggets that don't unify to GT and also - can't be smelted in the TiC smeltery. Essentially the only use they have is turning then into GT rounds 
![image](https://user-images.githubusercontent.com/23512002/181307107-92a8cf37-a88b-43ac-8ef5-88851accc132.png)

### The Reality

I don't think all of that is intended.
Related issues: 
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10392
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7251
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9384
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/701
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/268

### Your Proposal

 There should be either: 
- Unification to GT turned on for these nuggets, like it is done for Void metal & Thaumium
- or the crucible recipe removed
- or smelery smelting turned on

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by shekurika** [comment]
exact same issue with manyllum nuggets and cobalt nuggets

**Comment by Dream-Master** [comment]
yes some tico stuff was added manual because we not enable gt compat for it. (because you get alu gravel very eraly and can skip tiers)

**Comment by Dream-Master** [comment]
Maybe we can change the alu gravel to something else early game stuff that can be used in a melting form. So we can eable tico compat. And we should remove all the other gravel in code since iron gravel cant be disabled even if config is set generate "Iron Gravel" to false.
