### ISSUE TITLE
Arance assembler infusion recipe invalid

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#10845]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

2123qf

### Your Server

priv srv

### Your Expectation

I tried to craft the arcane assembler with this recipe:
![image](https://user-images.githubusercontent.com/7230430/181381459-04a58b89-e2af-4078-9f63-9ffbb06bbe02.png)

### The Reality

The crafted wand is not accepted, only the cheated in from NEI.
![image](https://user-images.githubusercontent.com/7230430/181381632-25fa0741-2281-4aae-92a7-43bf7e7b78d7.png)
bottom one is the cheated in what is accepted

### Your Proposal

fix it pls

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DianeXD** [comment]
You need to fill the wand iirc

**Comment by repo-alt** [comment]
Works fine with a filled wand, and I think it is on purpose.
