### ISSUE TITLE
GT-Botania items spelling consistency

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#10841]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.1.2.4-18

### Your Server

Zeta

### Your Expectation

Be able to find GT materials based on their existing name

### The Reality

Terrasteel is called Terra Steel (with space) in GT
Manasteel is called Mana Steel

Searching for the common Botania name will therefore not yield these as a result in NEI

### Your Proposal

Rename the GT materials

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
sure will do

**Comment by miozune** [comment]
Fixed in dev
