### ISSUE TITLE
Server crashes when loading mobs

### ISSUE THREAD

**Issue by DianeXD** [GTNewHorizons/GT-New-Horizons-Modpack#10851]
### Your GTNH Discord Username

DianeXD#2249

### Your Pack Version

2.1.2.4-18-pre

### Your Server

Private server

### Type of Server

Thermos

### Your Actions

Enter the game and load to some mobs

The first crash may not be related to the others idk

### Crash Report

https://pastebin.com/PfEAAEz5

https://pastebin.com/D6LS5VzQ
https://pastebin.com/BzLT92r5

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
how can you be on 2.1.2.4-20-pre? it's not even released yet

**Comment by DianeXD** [comment]
> how can you be on 2.1.2.4-20-pre? it's not even released yet

Should be the latest version

**Comment by chochem** [comment]
latest dev is 18-pre. But from the logs it looks like you manually updated beyond that.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
