### ISSUE TITLE
OC's AR Glasses and Hologlasses should be able to occupy Visor slot and amulet slot 

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#10858]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.1.2.4 20 pre

### Your Proposal

I want to wear either glasses with some amulet from some other mod, 
Also it'll be more consistent behaviours 

### Your Goal

QOL of the pack

### Your Vision

QOL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11786
