### ISSUE TITLE
AE2 fluid craft voids items and breaks AE network

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#10864]
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

dev18

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

If AE network doesn't have enough energy stored, for example it doesn't have an Energy Cell buffer.

When you try to craft with AE2 fluid, because it uses the drops, that's a huge amount of drops, for example 16 buckets is treated as 16k items. To transfer 16k items it requires tons of energy. If AE network doesn't have enough energy, two things will happen.

1)It will void all the fluid that it didn't have enough energy for.
2)It will start returning all the liquid it had enough energy for, to the AE2 network. And it will return all drops not as liquid, but as items.
This will take Item Storage Cells, and not Liquid Storage Cells. Even though the ME network will display it all together as Drops in the ME interface, these drops will occupy different cells, both item and liquid cells, and in fact for the recipes, and for everything else the system now will have 2 types, one in form of liquid, and one in form of items. And these items will take tons of space. It should never be treated as items.
More than that, for autocrafting, the "item drops" will never be treated as "liquid drops" and autocrafting will say that you don't have enough items.

Also another bug is that if you try to order an autocraft that contains liquid, but from "not liquid me terminal", it will use the Crafting Bytes as if those "liquid drops" were items, and the amount of bytes required will be thousands more than really needed.

### The Reality

AE2 network got into inconsistent state.

### Your Proposal

Whenever autocrafting returns the liquid to the system for any reason, it should be returned as "liquid drops" and not "item drops", and it should occupy the "ae2fc fluid cells", not "item cells".

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
the huge energy consumption problem is fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/07b03d1ef12e38308e30323c89d2c5db85c6c32a. but item drops problem is bit tricky to deal with. as a workaround you should make sure the fluid discretizer in you network never go offline so these drops won't flood into your item cells

**Comment by nikitinalexx** [comment]
Thank you for a workaround. Is it possible to fix this bug also in future? Because the pull request you linked addresses only half of the issue.
Ofcrouse most people build the reliable energy supply, but every now and then somewhen can have the network accidentally go offline and then the drops might pollute the network.

**Comment by GlodBlock** [comment]
ok
