### ISSUE TITLE
Botania Creative mana pool rebalance

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#10865]
### Your GTNH Discord Username

Hikari1nVoid#9527

### Your Pack Version

2.1.2.3

### Your Proposal

In 2.1.2.3 the creative mana pool only takes 7 infinity plate which is way too cheap comparing to other end-game creative items(i.e.creative wands from thaumcraft).These items should be crafted in extreme crafting tables or use 7 infinity blocks.

### Your Goal

Creative mana pool from Botania is overpowered comparing to its cost.

### Your Vision

We should rebalance these items to make them "require similiar amount of resources and time to craft".

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/Botanic-horizons/pull/11
