### ISSUE TITLE
[Quest] Advanced Heat Exchanger require wrong heat exchanger

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#10866]
### Your GTNH Discord Username

tim lam

### Your Pack Version

GTNH-1.7.10-2.1.2.4-18-pre

### Your Server

SP

### Your Expectation

![image](https://user-images.githubusercontent.com/105285781/181898817-284ea570-6753-4a9b-83e9-38a86970d66a.png)

### The Reality

![image](https://user-images.githubusercontent.com/105285781/181898879-e50701e0-0db7-451c-b5ca-26b9b909ef72.png)

### Your Proposal

Change the quest requirement to Heat Exchanger instead of Component Heat Exchanger

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
i change the ic2 recipes in the last version so maybe the quest need an update

**Comment by chochem** [comment]
is fixed already
