### ISSUE TITLE
Infernal Blastoff effect causes massive lagspike in mob grinder with iron spikes

### ISSUE THREAD

**Issue by Flanisch** [GTNewHorizons/GT-New-Horizons-Modpack#10863]
### Your GTNH Discord Username

Albi#2020

### Your Pack Version

2.1.2.4-18

### Your Server

Private Server (i7 7700k, CentOS 8, openjdk8)

### Type of Server

Vanilla Forge

### Your Expectation

A mob grinder kills Carminite Ghastlings by blowing them into eu2 iron spikes. I expect this to maybe cost a low amount of server performance at most.

### The Reality

Once in a while (on average every 30mins but very inconsistent) an infernal Ghastling causes a chain of recursive functions upon being hurt which cause over 30 seconds of server lag. Everytime the lag happens, the blastoff-function can be found in the stack trace.

This times out every player on the server.

The mobgrinder has been running fine for a couple of months on 2.1.2.0. Since the update to 2.1.2.4-18 I started seeing regular time outs.

Disabling `MM_Blastoff enabled` in `InfernalMobs.cfg` stops the Blastoff-function from being called, but follow up functions are still being called. I also don't know why functions from malisiscore are being called either, since there are no malisisDoors in the vicinity of the grinder.

Here is the warmroast trace as well:
![warmroast trace](https://user-images.githubusercontent.com/12825442/181845840-2a752415-a7af-49cb-a4cb-fb6332fa9d0a.png)

### Your Proposal

Since neither InfernalMobs nor Extra Utilities got changed from 2.1.2.0 to 2.1.2.4-18, it would be interesting to see what the actual cause of the lag is.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4654

**Comment by Flanisch** [comment]
A little update to the issue. 

I tried disabling infernalmobs completely. And while the timeouts became less frequent, they still happened. Even with a vanilla zombie. It turns out, that neither Extra Utilities nor InfernalMobs cause the lag by themselves. There seems to be an incompatibility with malisiscore specifically.

If I remove malisiscore and by that extent malisisdoors the lag doesn't occur anymore. In all of the profiler stack traces `net.malisis.core.util.chunkcollision.ChunkCollision.getRayTraceResult()` and `net.malisis.core.util.chunkblock.ChunkBlockHandler.getAffectedChunks()` are called and seem to cause an enormous lagspike by themselves.

**Comment by Flanisch** [comment]
Related to this [MalisisCore Issue](https://github.com/Ordinastie/MalisisCore/issues/80)
