### ISSUE TITLE
Outdated Quest

### ISSUE THREAD

**Issue by Atomic203** [GTNewHorizons/GT-New-Horizons-Modpack#10876]
### Your GTNH Discord Username

Atomic#5169

### Your Pack Version

2.1.2.4-dev18

### Your Proposal

i would like the Monocrytaline silicon boules quest in the mv questline to get updated
![image](https://user-images.githubusercontent.com/97828365/182008791-4cbd4f41-5521-43f7-a6e4-50fb85cdd58f.png)
![image](https://user-images.githubusercontent.com/97828365/182008802-66c3def1-5110-441d-95ba-e0c7fe646412.png)
![image](https://user-images.githubusercontent.com/97828365/182008806-4407b9dd-b26b-450f-8ffa-69fe6cf28a3a.png)
![image](https://user-images.githubusercontent.com/97828365/182008822-29a8047d-ace3-48ba-b61e-f728b66373b9.png)
![image](https://user-images.githubusercontent.com/97828365/182008834-f7a4a191-1fe2-46e1-8f9f-b9186400e58e.png)

### Your Goal

my goal is to get the quest updatex

### Your Vision

To get the quest updated?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
already done
