### ISSUE TITLE
IC2 crop sticks can't be placed randomly in overworld

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10879]
Ok so i make yet another ticket about this randomly occuring bug as it's happening on zeta. What we currently know:
- it happens randomly
- it is reboot persistant
- it disappears usually after a day or two
- looks like we can place a crop after some delay, but only one.
- looks like it only gets reported from players on the official servers.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3841
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5070
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3350

**Comment by repo-alt** [comment]
So, probably either Thermos itself or some plugins

**Comment by boubou19** [comment]
dynamism tablet can't place it either

**Comment by boubou19** [comment]
i booted zeta with no plugin, and it still happens

**Comment by Dream-Master** [comment]
@eigenraven Thermos problem :P

**Comment by boubou19** [comment]
i attempted to load plain forge, got a random unrelated crash, was lazy to figure out what was happening, went back on the usual setup with thermos and all the plugins, issue disappeared. wtf

**Comment by ashido96** [comment]
This bug is also occurring on the gtnh server in the "modded minecraft club" servers. So it is not official server only.

**Comment by boubou19** [comment]
@ashido96 do you know what server brand do they use? like plain forge?thermos?crucible?ultramine?

**Comment by Miisi** [comment]
I had this happen in singleplayer about two months ago after moving crops to the Last Millenium and changing biomes with Witchery, not entirely sure if that's relevant at all

only way I found to place the crop sticks was with AE2 formation plane. had the issue happen for a few days and then never again, updating the pack to a dev version may have fixed it but I don't remember

**Comment by boubou19** [comment]
thx god, it has been finally reproduced in SP. Do you have any 3rd party mods aside from NH modpack?

**Comment by Miisi** [comment]
had FTB Utilities and its library

**Comment by ashido96** [comment]
Has anyone found a way to stop this bug once is starts occurring?

**Comment by Duckhemp** [comment]
> @ashido96 do you know what server brand do they use? like plain forge?thermos?crucible?ultramine?

We use thermos. Currently have 1614-58 on our server.

**Comment by NickBjurstrom** [comment]
Occurs on Earthquake GTNH, I believe we're using Thermos.

**Comment by BeepBeep20** [comment]
It still happens on Earthquake in 2.2.0.0 (maybe not for everyone, but at least 2 players including me)

I doubt this will help track down the bug but a Botania floating Rannuncarpus can place them on tilled fertilised dirt when I can't

**Comment by TheRealRobin** [comment]
Well, it also happened to me now.
Version: 2.3.0, Server: Epsilon

It tried a few things (like restarting the game, rebooting etc, did not work.) It seems this issue thread is the correct one.
Is there any known way to reliably place crop sticks again after this bug occurs? I would like to plant some oreberries :)

I will try waiting a bit and maybe if it works again, I will update you here. Sorry if this comment is not that helpful with new info.
