### ISSUE TITLE
Buff lower-tier CAL speeds

### ISSUE THREAD

**Issue by realthecaffiend** [GTNewHorizons/GT-New-Horizons-Modpack#10887]
### Your GTNH Discord Username

thecaffiend#2253 

### Your Pack Version

2.1.2.3qf  (Some config changes, no recipe changes)

### Your Proposal

Make the CAL recipes for lower-grade circuits faster: I happen to be looking at micros but I could see others being relevant

### Your Goal

A dedicated multiblock should be way, way more then a 25% speedup (And nearly-identical resources) versus slapping some circuit assemblers in a PA

### Your Vision

Getting to the CAL should be a carrot *as well* as a stick. Honestly we assumed it was, an entire, new, expensive multiblock, surely it's much much faster right? Well..... Oops. A PA full of EV circuit assemblers would be "cheaper" (in resources that someone in ZPM cares about) to build, and about 25% slower (Assuming the CAL has the 4/4 OC I heard about in the discord (Hi chochom!)). 

People are forced to go CAL's for the crystal line, that's fine and new and neat! But there could be a carrot here as well, in faster production of lower-grade circuitry that if you really need now, you likely need in bulk (Hello, solar). 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by stlchase40** [comment]
The CAL has a perfect overclock in addition to creating circuits at a massively cheaper cost. Overclock your CAL once and this shouldnt seem as much of a problem anymore.

**Comment by greesyB** [comment]
I think this is worth looking into. For reference, making 2 Micros in a normal circuit assembler takes just 2.5 seconds at EV. This means they one-tick with UHV circuit assemblers (3 ticks at UV). In a PA this means 128 circuits per tick.
Meanwhile a CAL takes 30 seconds for 32 microprocessors at EV. Even with perfect OCs this doesn't one-tick until UHV, where it will still only make 32 circuits per tick compared to the 128 of a PA.
![image](https://user-images.githubusercontent.com/73182109/193098286-5e02bdd1-c3aa-4297-8f51-1aceed209079.png)
![image](https://user-images.githubusercontent.com/73182109/193098372-913a456e-c87a-494d-8d59-b5ca1587e3e5.png)

Admittedly the PA will take ~50x the power of a CAL per circuit when both are UHV, but I do not think that alone is reason enough to use them when the PA can be so much faster.

CALs are a decently interesting multi, and I don't think PAs should be able to compete with them as well as they do for lower tier circuits. One way to improve CALs here could be to add additional recipes for lower tier circuits that use higher-tier soldering alloys for both speed boosts and possibly yield.
