### ISSUE TITLE
Natura is not compatible with my Modpack

### ISSUE THREAD

**Issue by OMGICE** [GTNewHorizons/GT-New-Horizons-Modpack#10888]
### Your Pack Version

This is not GT new horizons modpack

### Your Server

Single Player

### Your Actions

Unable to start the game normally

### Crash Report

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 2022-08-01 07:56:53 CST
Description: Initializing game

cpw.mods.fml.common.LoaderException: java.lang.VerifyError: Expecting a stackmap frame at branch target 39
Exception Details:
  Location:
    mods/natura/blocks/crops/Glowshroom.func_149674_a(Lnet/minecraft/world/World;IIILjava/util/Random;)V @18: if_acmpeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2a2b 1c1d 1504 1905 b800 383a 0c19 0cb2
    0x0000010: 003e a500 1519 0cb2 0041 a601 2e19 0510
    0x0000020: 19b6 0047 9a01 2407 3606 0836 071c 1506
    0x0000030: 6436 0815 081c 1506 60a3 004a 1504 1506
    0x0000040: 6436 0915 0915 0415 0660 a300 331d 0464
    0x0000050: 360a 150a 1d04 60a3 0020 2b15 0815 0a15
    0x0000060: 09b6 004d 2aa6 000c 8407 ff15 079d 0004
    0x0000070: b184 0a01 a7ff de84 0901 a7ff c984 0801
    0x0000080: a7ff b31c 1905 06b6 0047 6004 6436 081d
    0x0000090: 1905 05b6 0047 6019 0505 b600 4764 360a
    0x00000a0: 1504 1905 06b6 0047 6004 6436 0903 360b
    0x00000b0: 150b 07a2 0058 2b15 0815 0a15 09b6 0051
    0x00000c0: 9900 1b2a 2b15 0815 0a15 09b6 0055 9900
    0x00000d0: 0d15 083d 150a 3e15 0936 041c 1905 06b6
    0x00000e0: 0047 6004 6436 081d 1905 05b6 0047 6019
    0x00000f0: 0505 b600 4764 360a 1504 1905 06b6 0047
    0x0000100: 6004 6436 0984 0b01 a7ff a82b 1508 150a
    0x0000110: 1509 b600 5199 002a 2a2b 1508 150a 1509
    0x0000120: b600 5599 001c 2b1c 1d15 04b6 0059 360b
    0x0000130: 2b15 0815 0a15 092a 150b 06b6 005d 572a
    0x0000140: 2b1c 1d15 04b8 0061 b1                 
  Stackmap Table:
    append_frame(@51,Integer,Integer,Integer)
    append_frame(@67,Integer)
    append_frame(@82,Integer)
    same_frame(@113)
    same_frame(@119)
    chop_frame(@125,1)
    chop_frame(@131,1)
    append_frame(@176,Integer,Integer,Integer)
    same_frame(@219)
    chop_frame(@267,1)
    full_frame(@328,{Object[#2],Object[#73],Integer,Integer,Integer,Object[#67]},{})

    at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandlerMixin.java:243)
    at net.minecraft.client.Minecraft.func_71384_a(MinecraftMixin.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(MinecraftMixin.java:3592)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.VerifyError: Expecting a stackmap frame at branch target 39
Exception Details:
  Location:
    mods/natura/blocks/crops/Glowshroom.func_149674_a(Lnet/minecraft/world/World;IIILjava/util/Random;)V @18: if_acmpeq
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: 2a2b 1c1d 1504 1905 b800 383a 0c19 0cb2
    0x0000010: 003e a500 1519 0cb2 0041 a601 2e19 0510
    0x0000020: 19b6 0047 9a01 2407 3606 0836 071c 1506
    0x0000030: 6436 0815 081c 1506 60a3 004a 1504 1506
    0x0000040: 6436 0915 0915 0415 0660 a300 331d 0464
    0x0000050: 360a 150a 1d04 60a3 0020 2b15 0815 0a15
    0x0000060: 09b6 004d 2aa6 000c 8407 ff15 079d 0004
    0x0000070: b184 0a01 a7ff de84 0901 a7ff c984 0801
    0x0000080: a7ff b31c 1905 06b6 0047 6004 6436 081d
    0x0000090: 1905 05b6 0047 6019 0505 b600 4764 360a
    0x00000a0: 1504 1905 06b6 0047 6004 6436 0903 360b
    0x00000b0: 150b 07a2 0058 2b15 0815 0a15 09b6 0051
    0x00000c0: 9900 1b2a 2b15 0815 0a15 09b6 0055 9900
    0x00000d0: 0d15 083d 150a 3e15 0936 041c 1905 06b6
    0x00000e0: 0047 6004 6436 081d 1905 05b6 0047 6019
    0x00000f0: 0505 b600 4764 360a 1504 1905 06b6 0047
    0x0000100: 6004 6436 0984 0b01 a7ff a82b 1508 150a
    0x0000110: 1509 b600 5199 002a 2a2b 1508 150a 1509
    0x0000120: b600 5599 001c 2b1c 1d15 04b6 0059 360b
    0x0000130: 2b15 0815 0a15 092a 150b 06b6 005d 572a
    0x0000140: 2b1c 1d15 04b8 0061 b1                 
  Stackmap Table:
    append_frame(@51,Integer,Integer,Integer)
    append_frame(@67,Integer)
    append_frame(@82,Integer)
    same_frame(@113)
    same_frame(@119)
    chop_frame(@125,1)
    chop_frame(@131,1)
    append_frame(@176,Integer,Integer,Integer)
    same_frame(@219)
    chop_frame(@267,1)
    full_frame(@328,{Object[#2],Object[#73],Integer,Integer,Integer,Object[#67]},{})

    at mods.natura.common.NContent.preInit(NContent.java:246)
    at mods.natura.Natura.preInit(Natura.java:90)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
    ... 10 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 11 (amd64) version 10.0
    Java Version: 1.8.0_341, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 87096072 bytes (83 MB) / 1524629504 bytes (1454 MB) up to 14388559872 bytes (13722 MB)
    JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx13721m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 96 mods loaded, 96 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCH    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCH    FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCH    Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
    UCH    CodeChickenCore{1.1.5} [CodeChicken Core] (minecraft.jar) 
    UCH    InputFix{1.7.10-v5} [InputFix] (minecraft.jar) 
    UCH    NotEnoughItems{2.2.19-GTNH} [NotEnoughItems] (NotEnoughItems-1.7.10-2.2.19-GTNH.jar) 
    UCH    se{0.4.1} [Super Enchants] (minecraft.jar) 
    UCH    <CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
    UCH    FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
    UCH    WorldEngine{1.1710.0} [WorldEngine] (1.7.10-ASJCore-1.2.0.0.jar) 
    UCH    asjpatcher{1.0} [asjpatcher] (1.7.10-ASJCore-1.2.0.0.jar) 
    UCH    flammpfeil.slashblade{mc1.7.10-r88} [SlashBlade] (SlashBlade-mc1.7.10-r88.jar) 
    UCH    flammpfeil.nihil{mc1.7.x-r8} [Nihil] ([1.7.X]-拔刀剑附属似蛭-Nihil-r8.jar) 
    UCH    levels{r3.0.1} [Levels] ([Secretmine.net]-《1.7.10》等级系统MOD.jar) 
    UCH    Yamazakura{1.0.0} [Yamazakura] ([山樱]SlashBlade-Yamazakura-mc1.7-r4.jar) 
    UCH    heart{2.0.0} [Heart Health] ([心殇汉化]Hearts Damage-2.0.0.jar) 
    UCH    KeepingInventory{1.6} [Keeping Inventory] ([死亡不掉落MOD]KeepingInventory[1.7.10].jar) 
    UCH    Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
    UCH    Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCH    harvestcraft{1.7.10j} [Pam's HarvestCraft] ([潘马斯丰收工艺]Pam's+HarvestCraft+1.7.10Lb.jar) 
    UCH    InfernalMobs{1.6.6} [Infernal Mobs] ([精英怪]InfernalMobs-1.7.10.jar) 
    UCH    adventurebackpack{1.0.5-GTNH} [Adventure Backpack] (adventurebackpack-1.7.10-1.0.5-GTNH.jar) 
    UCH    falsepatternlib{0.9.4} [FalsePatternLib] (falsepatternlib-mc1.7.10-0.9.4.jar) 
    UCH    animfix{2.0.0-hotfix1} [AnimFix] (animfix-mc1.7.10-2.0.0-hotfix1.jar) 
    UCH    AppleCore{3.1.1} [AppleCore] (AppleCore-1.7.10-3.1.1.jar) 
    UCH    BambooMod{Minecraft@MC_VERSION@ var@VERSION@} [BambooMod] (Bamboo-2.6.8.5.jar) 
    UCH    bamboolightplus{1.0.0} [BambooLight Plus] (bamboolight plus 1.0.0 MC1.7.10.jar) 
    UCH    BetterAchievements{0.1.0} [Better Achievements] (BetterAchievements-1.7.10-0.1.0.jar) 
    UCH    bettercrashes{1.1.4-GTNH} [BetterCrashes] (bettercrashes-1.7.10-1.1.4-GTNH.jar) 
    UCH    flammpfeil.slashblade.blademaster{mc1.7.2-r1} [BladeMaster] (BladeMaster-mc1.7.2-r1.2.jar) 
    UCH    bloodblade{1.0.0} [bloodblade] (BloodBlade1.3.9Final.jar) 
    UCH    Botania{r1.8-249} [Botania] (Botania r1.8-249.jar) 
    UCH    campfirebackport{1.7.10-1.9.2} [Campfire Backport] (campfirebackport-1.7.10-1.9.2.jar) 
    UCH    ChestTransporter{2.0.6} [Chest Transporter] (ChestTransporter-1.7.10-2.0.6.jar) 
    UCH    CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
    UCH    cookingforblockheads{1.2.9-GTNH} [Cooking For Blockheads] (CookingForBlockheads-1.7.10-1.2.9-GTNH.jar) 
    UCH    cmm{1.0 by Dot_Silver} [Craftable Music Discs Mod - MCV 1.7.10] (Craftable Music Discs Mod 1.7.10.jar) 
    UCH    flammpfeil.darkraven{mc1.7.2-r2} [DarkRaven] (DarkRaven-mc1.7.2-r2.jar) 
    UCH    eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
    UCH    eide{1.0a} [Enchantment ID Extender] (EnchantmentIDExtender-1.0a.jar) 
    UCH    endercore{0.2.9} [EnderCore] (endercore-1.7.10-0.2.9.jar) 
    UCH    endercrop{1.7.10-1.1} [Ender Crop] (endercrop-1.7.10-1.2.jar) 
    UCH    Waila{1.5.21} [Waila] (Waila-1.7.10-1.5.21.jar) 
    UCH    EnderIO{2.3.1.41} [Ender IO] (EnderIO-1.7.10-2.3.1.41.jar) 
    UCH    endlessids{1.3.0} [EndlessIDs] (endlessids-mc1.7.10-1.3.0.jar) 
    UCH    HardcoreEnderExpansion{1.9.3-GTNH} [Hardcore Ender Expansion] (HardcoreEnderExpansion-1.7.10-1.9.3-GTNH.jar) 
    UCH    TwilightForest{2.3.8.15} [The Twilight Forest] (TwilightForest-1.7.10-2.3.8.15.jar) 
    UCH    etfuturum{2.4.0} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.4.0.jar) 
    UCH    fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
    UCH    flammpfeil.fluorescentbar{mc1.7.2-r3} [fluorescentbar] (FluorescentBar-mc1.7.2-r3.jar) 
    UCH    foxex{1.1.2} [FoxBlade Extra] (FoxExtra狐月刀改 v1.1.2(MC1710).jar) 
    UCH    ganysend{1.11.3} [Gany's End] (Ganys+End-1.11.3.jar) 
    UCH    ganysnether{1.8.3} [Gany's Nether] (Ganys+Nether-1.8.3.jar) 
    UCH    GodFox{1.0.0} [GodFox] (GodFox1.1.5Final.jar) 
    UCH    immersivesnow{1.0b} [Immersive Snow] (immersive-snow-1.7.10-1.0b.jar) 
    UCH    IC2{2.2.828-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.828-experimental.jar) 
    UCH    inventorytweaks{1.5.15} [Inventory Tweaks] (inventorytweaks-1.7.10-1.5.15.jar) 
    UCH    IronChest{6.0.71} [Iron Chests] (IronChest-1.7.10-6.0.71.jar) 
    UCH    flammpfeil.slashblade.kirisaya{r1} [SlashBlade-Kirisaya] (Kirisaya-r1.jar) 
    UCH    Mantle{0.3.5} [Mantle] (Mantle-1.7.10-0.3.5.jar) 
    UCH    MaterialsPlus{1.0.0} [MaterialsPlus] (MaterialsPlus+1.0+(1.7.10).jar) 
    UCH    Wa{1.7.10.16} [Wa] (mcmap.cc-[和风MOD][1.7.10].jar) 
    UCH    AencEx{0.0.1} [AencEx] (mcmap.cc-[更多的附魔MOD][1.7.10].jar) 
    UCH    me{1.3.2.1} [More Enchantments] (mcmap.cc-[更多的附魔MOD][1.7.10].jar) 
    UCH    modernsplash{@VERSION@} [ModernSplash] (modernsplash-1.7.10-2c17c9a.jar) 
    UCH    flammpfeil.slashblade.murasamablade{mc1.7.2-r3.2} [murasamablade] (MurasamaBlade-mc1.7.2-r3.2.jar) 
    UCH    MysteriumLib{1.0} [§5Mysterium§aLib ] (MysteriumLib-1.0.jar) 
    UCE    Natura{2.5.3} [Natura] (Natura-1.7.10-2.5.3.jar) 
    UCH    neodymium{0.1.5} [Neodymium] (neodymium-1.7.10-0.1.5.jar) 
    UCH    netherlicious{3.2.3} [§6Netherlicious] (netherlicious-3.2.3.jar) 
    UCH    netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.7.10-1.1.1.jar) 
    UCH    recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-1.7.10-0.3.2.jar) 
    UCH    notenoughpets{2.3.3} [§eNot Enough Pets] (NotEnoughPets-1.7.10-2.3.3.jar) 
    UCH    harvestthenether{1.7.10} [Pam's Harvest the Nether] (Pam's+Harvest+the+Nether+1.7.10a.jar) 
    UCH    skinport{1.7.10-v10d} [SkinPort] (SkinPort-1.7.10-v10d.jar) 
    UCH    flammpfeil.slashblade.anvilenchant{mc1.7.10-r1} [Slashblade-AnvilEnchant] (Slashblade-AnvilEnchant-mc1.7.10-r1.jar) 
    UCH    flammpfeil.slashblade.kamuy{mc1.7.10-r6} [Kamuy] (SlashBlade-Kamuy-mc1.7.10-r6.jar) 
    UCH    flammpfeil.slashblade.laemmle{mc1.7.10-r1} [Slashblade-Laemmle] (Slashblade-Laemmle-mc1.7.10-r1.jar) 
    UCH    flammpfeil.slashblade.zephyr{1.7.2 r1.2} [SlashBladeZephyr] (SlashBlade_Zephyr-mc1.7.2-r1.2.2.jar) 
    UCH    flammpfeil.slashbladewa{mc1.7.2-r1} [SlashBladeWa] (SlashBladeWa-mc1.7.2-r1.jar) 
    UCH    soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
    UCH    SpecialMobs{3.3.12} [Special Mobs] (SpecialMobs-1.7.10-3.3.12.jar) 
    UCH    spongemixins{1.5.0} [SpongeMixins Loader] (SpongeMixins-1.5.0.jar) 
    UCH    ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
    UCH    TofuCraft{2.1.6-MC1.7.10} [豆腐Craft (TofuCraft)] (TofuCraft-2.1.6-MC1.7.10.jar) 
    UCH    mrblade{2.12} [Technology Revolution Blade Extra] (TRblade技术革新 v2.1.2[MC1.7.10].jar) 
    UCH    VeinMiner{0.36.0_1.7.10-28a7f13} [Vein Miner] (VeinMiner-1.7.10-0.36.0.496+28a7f13.jar) 
    UCH    VeinMinerModSupport{0.36.0_1.7.10-28a7f13} [Mod Support] (VeinMiner-1.7.10-0.36.0.496+28a7f13.jar) 
    UCH    VillageNames{4.3.12} [§6Village Names] (VillageNames-1.7.10-4.3.12.jar) 
    UCH    WailaHarvestability{1.1.10-GTNH} [Waila Harvestability] (WailaHarvestability-1.7.10-1.1.10-GTNH.jar) 
    UCH    flammpfeil.slashblade.wanderer{mc1.7.2-r1} [SlashBladeWanderer] (Wanderer-mc1.7.2-r1.jar) 
    UCH    wawla{1.1.3-GTNH} [What Are We Looking At] (Wawla-1.7.10-1.1.3-GTNH.jar) 
    UCH    waystones{1.0.0} [Waystones] (Waystones_Jawsawn_Fork-mc1.7.10-1.0.0.jar) 
    UCH    weaponmod{v1.17.0} [Balkon's WeaponMod] (weaponmod-v1.17.0.jar) 
    UCH    flammpfeil.frostwolf{mc1.7.2-r1} [FrostWolf] (冰狼之刃-FrostWolf-mc1.7.2-r1.1.jar) 
    UCH    ironfurnaces{1.2} [Iron Furnaces] (更多熔炉.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.72' Renderer: 'NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
    CoFHCore: -[1.7.10]3.1.4-329
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    ThermalFoundation: -[1.7.10]1.2.6-118
    EnderIO: Found the following problem(s) with your installation:
                  * Optifine is installed. This is NOT supported.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
    Suspected Mods: Natura (Natura)
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.72, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs: [Modernity-format1-v3.7.0.zip]
    Current Language: 简体中文 (中国)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Anisotropic Filtering: Off (1)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by OMGICE** [comment]
Natura don't have issue form,so I can only posting here. :)

**Comment by joshaup1999** [comment]
So uhh, you arent playing GTNH yet you post a crash report here? Unsure what you want anyone to do since i dont see how this is the devs issues? I dont even think NH uses a custom natura 

Go post this on the ftb crash reddit or something instead

**Comment by OMGICE** [comment]
> 所以呃，你没有玩GTNH，但你在这里发布了一个崩溃报告？不确定您希望任何人做什么，因为我不明白这是开发人员的问题吗？我甚至不认为NH使用定制的自然
> 
> 去把这个发布在ftb崩溃reddit或其他东西上

You are right
