### ISSUE TITLE
[Mod/Concpet] UniversalChat; a means for Cross-language communication in game

### ISSUE THREAD

**Issue by Shibva** [GTNewHorizons/GT-New-Horizons-Modpack#10886]
### Your GTNH Discord Username

Shibva_

### Your Pack Version

2.1.2.3 

### Mod Name

UniversalChat [newer version mod; quilt/farbic]

### The Mod to Add

A chat modification mod that adds in a translator for languages

concept/mod in action
https://oh.why-am-i-he.re/5AJkJJiDr.gif

Source code, Wrintten in fabric sadly; Is under the AFL (Achidemic Free Lisence) 3.0
https://github.com/mineblock11/UniversalChat

### Your Reason

Because the GTNH community is made up of different members and afaik the official servers only communicate in English (and that by reasoning other official GTNH servers for parties that cant communicate in the English Language don't exist due to cost for such independent servers to exist)

The goal of this is to allow for such groups to be able to have a form of in-game communication with those that cant speak English nor be able to understand the English language; serving as a way for such players to be able to play on these servers in terms of being able to communicate with other server members in-game

### Preliminary Investigation

The Mod itself is capable of activly translating text and showing that translation in some means.

the mod itsel fwtih the pack cannot be tested due to it only existing in newer versions and the fact that its a Fabric/quilt API built mod.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Connor-Colenso** [comment]
Mod is not 1.7.10 nor forge. Keep it up and I will personally ban you from the github organisation.

**Comment by boubou19** [comment]
> Because the GTNH community is made up of different members and afaik the official servers only communicate in English (and that by reasoning other official GTNH servers for parties that cant communicate in the English Language don't exist due to cost for such independent servers to exist)

you try to solve something that was never an issue on the officials: /msg exist and is extensively used. Sometimes, players speak in their own language for short periods and that's ok. The official language had been chosen to english because it's the default language around the world. As long as no one feels excluded, the language used in the chat doesn't matter.

Also, cluttering the pack for the officials have already been done too much.

**Comment by Shibva** [comment]
ok, sorry. I was suggested by this when I bought it up in off topic; though idk if I was being bated or something on this.

Again, my apologies

**Comment by boubou19** [comment]
also, even if it was actually needed, one would still need to backport it, and we are all busy/in vacation right now.

**Comment by Shibva** [comment]
@Connor-Colenso apologies; I was redirected by this by Boubou and if the report is meant for mods only in 1.7.10 then may I suggest adding a checkbox to the Mod Report format
