### ISSUE TITLE
Give AE2 Wireless Connectors the ability to be named via the Quartz Cutting Knife

### ISSUE THREAD

**Issue by stlchase40** [GTNewHorizons/GT-New-Horizons-Modpack#10892]
### Your GTNH Discord Username

stlchase40#7583

### Your Pack Version

2.1.2.2

### Your Proposal

Just give the wireless connectors the ability to be named via the cutting knife from AE2. 

### Your Goal

It would allow for better navigation and organization of the AE2 network, would be a small QoL feature. "Endgame" AE2 uses a bunch of wireless connectors and this could help the player remember which ones link up to which connectors.

### Your Vision

It would remove a lot of burden on the player to remember which connector goes to which one, and removes the annoying need to press f3 to go to the coordinates the connector currently displays.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
let it stay in backlog some more

**Comment by LewisSaber** [comment]
This one is nice

**Comment by Dream-Master** [comment]
Wasnt this added? or i am wrong?

**Comment by serenibyss** [comment]
Implemented in https://github.com/GTNewHorizons/ae2stuff/pull/16
