### ISSUE TITLE
allow waila to show progress of the drying rack

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#10894]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.4-dev18

### Your Proposal

allow waila to show the progress of the recipe in the drying rack

### Your Goal

.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
It already does?
![2022-08-02_02 13 40](https://user-images.githubusercontent.com/40035906/182205474-eff8d692-c8e4-4481-a368-e14469639714.png)

**Comment by boubou19** [comment]
not in dev 18 apparently
