### ISSUE TITLE
AE2 fluid crafting. Spare fluid goes into Item Drive.

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#10907]
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

dev18

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

1)
After making some fluid crafting, my ME network shows that I have 14 types of fluid drops.
But in reality I have only 13 ae2 fluid drives.
1 of the fluid went into ME item drive.
After removing all ae2 fluid drives the fluid still remained in the network. After removing the drops I noticed that one of the drives changed. This means that fluid was inside the Item Drive.

2)
If you remove all ae2 fluid drives from the network, the network would still show that all the liquid you just removed,  is still inside the network.

### The Reality

1) Spare fluid should not go into item drives.
2) If you remove ae2 fluid drives, the ME network interface should not display the drops anymore, because they left the network with the fluid drives.

### Your Proposal

Fix 2 bugs.

First is very critical, second is not.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by nikitinalexx** [comment]
@GlodBlock

**Comment by GlodBlock** [comment]
can you show your ae storage setup? i can't reproduce the 1 and 2

**Comment by GlodBlock** [comment]
do you use a subnet to store fluid and items

**Comment by nikitinalexx** [comment]
It is very simple and straightforward. A single Network block and just cables from it. No p2p, no subnets.
Maybe you are testing in your fixed dev version? I am using just dev18.

![pic1](https://user-images.githubusercontent.com/4941736/182869418-9d27a13d-cfd4-4fe0-83cb-9a4af6360627.png)
![pic2](https://user-images.githubusercontent.com/4941736/182869428-408b9599-eb73-4686-95a4-e43931d57c04.png)

**Comment by GlodBlock** [comment]
try this http://jenkins.usrv.eu:8080/job/AE2FluidCraft-Rework/

**Comment by nikitinalexx** [comment]
It didn't help, I took away half the cells.
Only 9 cells left in the ME drive.
But there is 19 fluids displayed in ME network.
10 cells are in my inventory.

**Comment by nikitinalexx** [comment]
![pic1](https://user-images.githubusercontent.com/4941736/182987243-9162f588-f431-4e1a-8d8c-485d3f70cfbd.png)

**Comment by GlodBlock** [comment]
sorry i can't make the drops that already in item cell go back to fluid cells. but they can be used as crafting drops in crafting jobs. so you can output these item drops with a large fluid pattern as fluid and put them back.

but later these drops should not go into the item cells

**Comment by nikitinalexx** [comment]
No, I have checked. This fluid is real fluid. It is not "item" fluid. I can remove all "item cells" and still the fluid will be there.
Anyway I don't even have enough space to hold those 565k oxygen or other.

**Comment by GlodBlock** [comment]
oh you mean it is the visual drops bug after taking fluid cells away? it is haven't been solved yet.
