### ISSUE TITLE
General performance are worse in 2.1.2.4-25-pre version?

### ISSUE THREAD

**Issue by kexes** [GTNewHorizons/GT-New-Horizons-Modpack#10908]
### Your GTNH Discord Username

KeXeS

### Your Pack Version

2.1.2.4-25-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Same performance like before

### The Reality

My average CPU temp raised by like 10 celsius with the newest build, also my CPU fan are constantly working in higher rpm, and the general smoothness of the game is just gone for me, i mean turning the character with the mouse feels really choppy now like its some kind of frame lags, compared to the previous GTNH-1.7.10-2.1.2.4-18-pre version. Im using the same settings, same save, im only in the LV age, i dont have anything fancy, just some basic machines, two tanks (one for steam one for creosote) and some chests. I dont have any problems like this with the previous version.

### Your Proposal

I dont know what is causing this, im using 4 extra mods on top of the modpack:

- SmoothFont-1.7.10-1.15.3.jar (for better unicode font readability)
- FTBLib-1.7.10-1.0.18.3.jar
- FTBUtilities-1.7.10-1.0.18.3.jar (for chunkloading)
- JustEnoughCalculation-1.7.10-3.8.4.jar (for recipe material calculations)

Im used all these mods before the update too, they does not caused any problems before like i have now.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
Please provide some profiling with one of the available tools (warm roast, visualvm, etc) with actionable evidence of a regression.

**Comment by repo-alt** [comment]
I saw big FPS drop at Zeta after the update, TPS is ok

**Comment by kexes** [comment]
Sure, i did a CPU monitoring with AIDA64. I did with both versions, first is 2.1.2.4-25pre, second is 2.1.2.4-18pre. Both picture have 2 red rectangles, indicates the initial world loading and started idling right after the world loaded. You can clearly see that the CPU utilization spikes on the first picture (2.1.2.4-25pre) are much bigger compared to the second (2.1.2.4-18pre) one.

![2124-25pre1](https://user-images.githubusercontent.com/59803900/182631020-45e4ba00-e2cc-4482-b38f-b73effa63588.jpg)

![2124-18pre1](https://user-images.githubusercontent.com/59803900/182631081-f75a8b0e-d9f7-4402-a6f5-b227ffdc37ae.jpg)

**Comment by mitchej123** [comment]
That isn't actionable. We need a profile showing the hot spots so we can determine what is driving the CPU usage.  Check on the discord about how to use the various profiling tools available (vusiualvm is my go-to but there are others available)

**Comment by kexes** [comment]
Those programs needs JDK to be installed. Im using only regular Java x64. Maybe someone who using JDK will do it, because i never used those programs, i dont even know them. I don't want to be rude, but I don't want to bother with this, sorry.

**Comment by boubou19** [comment]
it's ok, we observed the slowdowns as well. Now to fix them...

**Comment by kexes** [comment]
That is glad to hear :) Hope you can fix it, keep up the good work!

**Comment by isxwzya** [comment]
I've noticed this performance problem in my SP game as well, but what I've observed is something unusual about the GPU video memory.  In 2.1.2.3qf it was 0.7G, but in pre25 it was stepped up to around 3.2G.(same setting and same save)

**Comment by boubou19** [comment]
it's caused by heavy animated textures for items. We do have some lead to reduce this issue, but in the mean time you can disable mip map/disable animated textures in fastcraft.ini / remove the GT animated textures recently added from the jar (which is just a renamed zip file)

**Comment by kexes** [comment]
Looks like the choppyness is fixed now in the 2.1.2.4.-28-pre version, but the CPU spikes still present and last for like 10 minutes after i load the world. It happening even if i press ESC to pause the game. This was also not present in 2.1.2.4.-18-pre version.
