### ISSUE TITLE
P2P and AE2FC Fluids mixing

### ISSUE THREAD

**Issue by Tyrantgtnh** [GTNewHorizons/GT-New-Horizons-Modpack#10906]
### Your GTNH Discord Username

ｔｙｒａｎｔ#5957

### Your Pack Version

2.1.2.4-14

### Your Server

SP

### Your Expectation

Use both ae2fc, and p2p for seperate applications on the same network

### The Reality

If i have a fluid stored or accessible by my ae2fc, it may look for a p2p on an empty input hatch and output one of the stored fluids, some of the fluids this has decided to output are molten naq, oxygen, and lubricant among others. This has even happened on p2p channels where there's only 1 input and 1 output so there is no way it should have a different fluid.

### Your Proposal

Not have fluids mix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
do you have screenshot of the setup you are using? my english isn't good enough to understand what you actually mean

**Comment by Tyrantgtnh** [comment]
This shows an aqua regia setup, 1 mixer making it, 1 supertank to store it, and 1 input hatch for the lcr. There is no where in this system where it should get lubricant 
![2022-08-03_07 42 22](https://user-images.githubusercontent.com/101432450/182599692-a7136dd4-766f-4ed6-b549-200dbf5d0f13.png)
![2022-08-03_07 42 18](https://user-images.githubusercontent.com/101432450/182599696-97acff15-36c4-40fc-86e1-09d1ffbe2b9b.png)
![2022-08-03_07 42 06](https://user-images.githubusercontent.com/101432450/182599697-9e8ffcb6-cef4-477b-af0f-e1cea70de9f1.png)
![2022-08-03_07 42 34](https://user-images.githubusercontent.com/101432450/182599699-3b28461b-7508-4744-b189-2e181dfc48a4.png)

**Comment by GlodBlock** [comment]
why close the issue? is it fixed?

**Comment by Runakai1** [comment]
> 

He used a fluid storage bus and it mixed up in the network

**Comment by GlodBlock** [comment]
bruh
