### ISSUE TITLE
Ender IO teleportation

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#10913]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.2.4-25-pre

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

Use travel anchor, the ender or other short range teleportation from ender io

### The Reality

Kicked from server with fatal error

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Do you have any logs?

**Comment by Florexiz** [comment]
Can't reproduce in sp. so maybe @boubou19 can give some related logs from zeta
