### ISSUE TITLE
Crash seemingly caused by gtneioreplugin

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10910]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-25-pre

### Your Server

SP

### Type of Server

Single Player

### Your Actions

start up a my world in a fresh 25-pre install.

### Crash Report

First I get this:
![image](https://user-images.githubusercontent.com/40274384/182671427-456fe8de-16c4-4afe-8c87-f6ff3d0c4d89.png)

then shortly thereafter the game crashes with various errors
[crash-2022-08-03_13.41.56-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9253749/crash-2022-08-03_13.41.56-client.txt)

[crash-2022-08-03_17.49.11-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9253756/crash-2022-08-03_17.49.11-server.txt)

[crash-2022-08-03_17.49.23-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9253755/crash-2022-08-03_17.49.23-client.txt)
 

I dont the the relation to the crash reports, but I have been able to narrow the problem down to a single mod: gtneioreplugin-1.7.10-1.0.15

Reverting to gtneioreplugin-1.7.10-1.0.12 fixes everything. :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@miozune any idea ?

**Comment by chochem** [comment]
I thought an extra mod I had was indirectly to blame but I removed everything now and I still have the same problem. The key part being the maxium id range being exceeded (while loading my save):
![image](https://user-images.githubusercontent.com/40274384/182965087-65420762-ad96-4cc5-897e-c5892e3c0bea.png)
which causes this popup
![image](https://user-images.githubusercontent.com/40274384/182965373-b19c7d93-5e99-4275-ad22-204a6756ab48.png)

and if one continues that leads to a crash that blames some unrelated mod a short time later.

**Comment by miozune** [comment]
I guess it's because ids are already mapped for save file. You can try [NotEnoughIDs](https://www.curseforge.com/minecraft/mc-mods/notenoughids) but it's not supported by us

**Comment by chochem** [comment]
yeah I think fml blocks ids even after removing a mod. :(
I am trying to nbtedit myself out of this right now.

I guess the closer we come to using all ids the easier this can happen to people. But this ticket can be closed
