### ISSUE TITLE
lathe gives small piles of dust

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#10927]
### Your GTNH Discord Username

ImpossibleVT#3997

### Your Pack Version

2.1.2.4-dev25

### Your Proposal

make lathe give 2 rods instead of 1 rod and 2 small piles of dust

### Your Goal

yeeting small piles

### Your Vision

small piles bad

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TwoTailedFox** [comment]
The Extruder gives two rods.

**Comment by Impos913** [comment]
> The Extruder gives two rods.

You missed the point.

**Comment by GlodBlock** [comment]
nobody will use lathe for rods massively

**Comment by chochem** [comment]
no I dont think that missed the point. the extruder is supposed to be an upgrade that you only get one tier later.

_However_ why not let it make 1 rod and 50% chance for a full dust.

**Comment by TwoTailedFox** [comment]
The whole point of the lathe giving two small dusts is to give you an incentive to upgrade to the Extruder.

**Comment by alexandre-tardif** [comment]
It is still used for some rods even later because some stuff can't be extruded like quartz.

**Comment by miozune** [comment]
Except Quartz and Certus Quartz. I think these 2 should still be addressed, like Charged Certus Quartz.

**Comment by Impos913** [comment]
This is about yeeting the small piles not difficulty.

**Comment by chochem** [comment]
If its just about yeeting small piles then a chance based solution does that. Same as everywhere else.

**Comment by Impos913** [comment]
Making lenses from plates also give a small pile.

**Comment by TwoTailedFox** [comment]
The better solution would be a 50% chance to get back a full dust.

**Comment by TwoTailedFox** [comment]
In fact, the lens recipes could apply the same principle as well.

**Comment by DianeXD** [comment]
I think small pile is acceptable in this recipe, this is not the same thing as ore treatment

**Comment by Connor-Colenso** [comment]
I don't think removing tiny dusts needs to be taken to the extreme, this recipe is very early game and as such a non-issue lag wise. Tiny piles were rightfully yeeted from ores because it was a pointless laggy drop that had to be processed twice but here it serves a purpose, to incentivise upgrading to an extruder.

**Comment by mitchej123** [comment]
Yeet them completely

**Comment by boubou19** [comment]
what about 2 ingots = 2 rods + a full dust?

**Comment by bedrill64** [comment]
> what about 2 ingots = 2 rods + a full dust?

This would give the same result cost-wise for rods, but in the case of lenses won't work, as lenses are way more expensive to make with exquisite(or flawless, not sure atm) gem recipes.

**Comment by boubou19** [comment]
just make it take 2 exquisite to give the dust or you buff it so the exquisite gives two lenses

**Comment by bedrill64** [comment]
The thing is getting 2 exquisites is pita at a low level, and u do not need 2 lenses of the same type, also u do not need dust back in most cases, so I'd just make it 1 gem -> 1 lens + 50% dust, as dust doesn't matter in case of gems.

**Comment by YannickMG** [comment]
One thing to consider when adding random chance to a material transformation recipe is that a very appealing part of gregtech's processing is that it is generally lossless, if you do it right. Made too many rods? That's fine, you can pulverize them and use the dust you got from the lathe to get back all of the ingots you started with. Just requires time and energy to undo small mistakes.

If this changes to random chance, I can see people being very annoyed at their precious materials being lost to this process.

**Comment by cubic-chariot** [comment]
On 2.1.2.3qf, most LV lens recipes consume one exquisite gem and produce 1 lens and 2 full dusts. The only exception is the glass and diamond lenses recipe; one plate yields 1lens and 1 small dust, and one exquisite gem yields 3 lenses and 1 full dust. At MV all recipes take one plate and yield 1 lens and 1 small dust.

I'm at HV and I made only a handful of lenses so far, compared to the thousands of rods lathed from ingots. Maybe this changes with higher tiers, but it seems that simply applying boubou's `2 ingots -> 2 rods + 1 full dust` idea and leaving the lenses unchanged would work.

Alternatively, as PLEs have the ghost circuit slot, they could be used to choose between `1 ingot -> 1 rod + 2 small dust` and `2 ingots -> 2 rods + 1 full dust`, and same for lenses.

**Comment by stlchase40** [comment]
This completely screws the earlygame gating of efficient material production. If this were to go through it'd probably have to be done by giving a single rod and no dusts, but even then, that removes the purpose to make a lathe earlygame. The lathe produces rods to the same ratio as an extruder, it just makes one and returns remaining materials.

**Comment by stlchase40** [comment]
> no I dont think that missed the point. the extruder is supposed to be an upgrade that you only get one tier later.
> 
> 
> 
> _However_ why not let it make 1 rod and 50% chance for a full dust.

That would result in the creation of a rod from nothing
