### ISSUE TITLE
Allow GT++ dehydrator in PA

### ISSUE THREAD

**Issue by GTNHAfx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#10921]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.4dev18

### Your Proposal

Please allow the use of GT++ dehydrator singleblocks in the Processing Array.

### Your Goal

Parallel processing of items, especially rare earth dust.

### Your Vision

iirc there were some GT++ singleblocks added to be used in PA recently, I predominantly remember the simple washer.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
there is a multi in zpm by the way if that is not clear, the Utupu-Tanuri. :)

**Comment by minecraft7771** [comment]
Due to how the PA works its not really possible. It would register each dehydrator as a much lower tier than it is (HV as LV for example)
