### ISSUE TITLE
AE2 doesn't send some recipe materials (ME Dual Interface)

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#10936]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.2.4-25

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Make 16 ZPM Energy hatch

### The Reality

The AE system doesn't send items to Assline
it works with some recipes (ZPM Pump Motor..)
But when I make Fusion computer controller MK2
and ZPM energy hatch it sends nothing out
Just holding crafting status in AE CPU

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I just ordered a zpm energy hatch and it all works fine. Hence:

how does your setup actually look like you gave zero info on that? double check all the parts! how can one reproduce this? did you actually ask other people and they confirmed this?
