### ISSUE TITLE
Door recipes seem to require vanilla (oak) trapdoors and there's no way to convert other types to vanilla.

### ISSUE THREAD

**Issue by UristMcStoutHorn** [GTNewHorizons/GT-New-Horizons-Modpack#10941]
### Your GTNH Discord Username

Urist McStout-Horn#7573

### Your Pack Version

2.1.2.4-25-pre-MMC

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Attempted to craft a door (just plain vanilla door).  Using jungle wood/slabs yielded a jungle trapdoor.  Attempted to use the jungle trapdoor in the recipe (along with spruce planks for the planks) and it wouldn't craft.  One would think that just the plain door recipe should accept mix/matched components.

### The Reality

Plain door recipe requires plain trapdoor and oak planks instead of accepting mixed components.

### Your Proposal

Allow the recipe for a plain door to take oredict input for trapdoors/planks or have a way to convert trapdoors into plain.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
Multiple mods add other doors including a jungle door, so you cant just allow any material. The vanilla door is just seen as the oak door.
Oak is not exactly hard to obtain so I think this can safely stay as is.
