### ISSUE TITLE
Industrial Apiary with WA is nice but not adequate to gendustry one

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#10943]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.1.2.4.-18

### Your Server

local and myFTB

### Type of Server

Single Player

### Your Expectation

first:  integrated WA is nice!

missing functions - to be an adequate alternative to gendust industrial apiary

### The Reality

- were to put frames?
- no biome and/or climate upgrades 
- princess to queen process needs to put queen back 
- UV Tier is very high for it, because alternative Alveary take performance if they are build in masses

Question: usable in PA?

Suggestion: 
Frames shall be essential for producing (like in real), that it is equivalent for other natural production (fertilizer at farms, ..)

### Your Proposal

please add:
- Slot for frames
- Biome and climate upgrades are missing (maybe using existing Gendust - upgrades?)
- Switch, were the princess to queen process which brought the queen automaticly into first slot back. 
   Than it can be decided: mass production or breeding
- UV Tier is very high for it, better LUV or lesser.

Question: usable in PA?

Suggestion: 
Frames shall be essential for producing (like in real), that it is equivalent for other natural production (fertilizer at farms, ..)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
- What frames? Old industrial apiary doesn't use any frames, It was crafted with frames.
- All gendustry upgrades are valid in new IApiary
- Princess to queen process is changed on purpose, now it needs automation upgrade
- Wasn't the recipe always LuV ? Either way now it will be crafted in HV

**Comment by Ngar1** [comment]
ok:
1) you are right, IA don't have frames.
2) now I know it, thx. Would it possible to put a infotext (at the blue "I" or by fly over the Slots for upgrades?
3) exactly - if automation upgrade is working it is perfect
open:
4) Power is signed as UV and a supply with lower voltage (I tried with 8196EU) is not possible, even if only 37EU/t is configured.
    Crafting is LuV

**Comment by kuba6000** [comment]
2  Ye I can put info somewhere that gendustry upgrades are supported.

4 The machine will not start until 1/4 of its EU capacity, already fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1197
also fixed battery slot (batteries were not de/charging)

**Comment by Ngar1** [comment]
Thank you very much!

**Comment by Ngar1** [comment]
closed

**Comment by Runakai1** [comment]
To further add information: the automation upgrade will be craftable in LV following with other upgrade recipe changes I will perform. 
Also, an apiary multiblock for UV is planned to get away from industrial apiary in that tier.

**Comment by chochem** [comment]
> Princess to queen process is changed on purpose, now it needs automation upgrade

@kuba6000 why though? Thats just a big QoL step backwards compared to the old IApiary and _not_ what the automation upgrade is for with the old.

**Comment by chochem** [comment]
I think this is important enough to reopen this. To add some more explanation: the automation upgrade is there to toggle between breeding and production. For breeding you do not want drones reinserted automatically, for production you do. But you **always** want the queen to be reinserted automatically in either scenario and that is indeed how it worked before.
