### ISSUE TITLE
Ender Fluid Link Cover with better overview

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#10947]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.1.2.4.-18

### Your Proposal

Ender Fluid Link Cover is a very nice alternative to ender tank!

But with many fluids the coding by numbers is not easy to handle

### Your Goal

good example with better GUI is the dimensional transeiver

![grafik](https://user-images.githubusercontent.com/7759876/183248290-6a15be2e-7885-4371-8afb-b742253f566d.png)

### Your Vision

GUI with names instead or as alternative to numbers 
GUI with overview of existing channels

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
Should already be included by https://github.com/GTNewHorizons/TecTech/pull/61
