### ISSUE TITLE
Lifespan upgrades bugged or working incorrectly with GT IApiary

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10952]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-25-pre + gt from jenkins

### Your Server

SP

### Your Expectation

The lifespan upgrade should drastically reduce the time it needs for a queen to die and generate the rest next generation. (without increases combs produced per time)

### The Reality

It does not affect the time at all. In fact the time seems to be fixed based on the acceleration upgrade. Instead the lifespan upgrade seems to result in a small productivity boost.

### Your Proposal

I am not sure how the internal code works now or before, so this is just one option, alternatives might be easier:

Make the life span upgrade reduce the 'recipe time'. ideally by 90-95% or so with the maximum of 4 upgrades. (maybe each one cuts the time in half?).

At the same time the comb production for that 'recipe' should also be cut by _at least_ the same amount. This is intended for breeding not production. The same should be done for any effect if they are calculated per recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
Progress time is capped at minimum 5 secounds, after that it increases outputs

**Comment by chochem** [comment]
ah well that is my bad then for only testing with the 256x upgrade.

yeah, just checked, works with slower upgrades. Each one cuts it down by one third as intended (dont know why I said half).

5 sec minimum is slower than before, but I think thats all fine then.
