### ISSUE TITLE
Crash after break anythings with a hammer

### ISSUE THREAD

**Issue by WhiteNightAWA** [GTNewHorizons/GT-New-Horizons-Modpack#10951]
### Your GTNH Discord Username

White_Night_awa#1729

### Your Pack Version

2.1.2.4-25-pre

### Your Server

Zeta

### Your Actions

Mine a Redstone Ore with a Hammer. 
Every time I did this it will crash.

(edit: not only redstone ore, the game will crash after I break any block with hammer)

(video here: https://youtu.be/AxIHIDrqaIs)

### Crash Report

https://paste.ubuntu.com/p/Fn9cYtym7W/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1182
