### ISSUE TITLE
Jar Label duplication glitch with Witching Gadgets' Aspect Library

### ISSUE THREAD

**Issue by cubic-chariot** [GTNewHorizons/GT-New-Horizons-Modpack#10950]
### Your GTNH Discord Username

cubic-chariot#3803

### Your Pack Version

2.1.2.4-25-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I placed down an Aspect Library, put a single jar label inside, and chose an aspect. I then broke the library without taking the labelled label from the GUI. I expected to get the single unlabelled label that I put there in the first place.

### The Reality

I got both an unlabelled label and a labelled label.

### Your Proposal

Make the library drop only the unlabelled labels when broken.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AlastorsGame** [comment]
This is a known glitch
