### ISSUE TITLE
Zeron-100 Reactor Shielding recipe is not using Zeron-100 plates 

### ISSUE THREAD

**Issue by Exelion42** [GTNewHorizons/GT-New-Horizons-Modpack#10961]
### Your GTNH Discord Username

Exelion#8813

### Your Pack Version

2.1.2.4-25

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Having to use Zeron-100 to craft the corosponding reactor shielding block (like in previous versions)

### The Reality

Recipe is now using Hastelloy C-276 plates.

### Your Proposal

Either change the recipe to Zeron 100 plates or rename the block to something else not refering to Zeron.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Steelux8** [comment]
Zeron-100 is an LuV material, whereas the LFTR and the fuel production multiblock are meant to be IV. I'll see what I'll do about the name.

**Comment by Anarack** [comment]
If it is meant to be IV, you should change the minimum muffler tier on the reactor fuel processing plant as well, It requires a LuV muffler.
