### ISSUE TITLE
When I start up no matter were I look it is just 1 solid color and changes when ever I look around

### ISSUE THREAD

**Issue by Keskeer** [GTNewHorizons/GT-New-Horizons-Modpack#10965]
### Your GTNH Discord Username

keskeer#3763

### Your Pack Version

Curse Forge

### Your Server

SP

### Your Expectation

I expected when I clicked play for my game to run as normal 

### The Reality

But when I spawn in and I look around its just 1 solid color and when I look around the color changes to what imp looking at i've look online and I could find nothing but to roll back my intel drivers and that's what I did and nothing fixed it 

### Your Proposal

To find a way to fix it or to get help on how to fix it 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
are you using an intel graphics card?

**Comment by boubou19** [comment]
intel graphics are borked since monthes now. Either you have another graphic card and you make the game use it, or you keep rolling back your intel drivers. In both cases, it's not our fault so i'm closing this
