### ISSUE TITLE
I cant joi  in the servers

### ISSUE THREAD

**Issue by lobiita24** [GTNewHorizons/GT-New-Horizons-Modpack#10962]
### Your GTNH Discord Username

marylobi25

### Your Pack Version

2.1.2.0

### Your Server

Craftersland

### Your Actions

I try to join in the server but my pc frezze and when change put the time is finish, i check and join and left in 1sec but i cant jpin never for play i only have 4 gb ram

### Crash Report

i not have

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
If you have a computer with 4GB ram total, it's impossible to play. This modpack requires at least 6GB of RAM in total so you can allocate at least 4GB of RAM to the game. And even in this case, your game will periodically freeze. Sadly, aside from improving your computer, nothing can be done.
