### ISSUE TITLE
Some bees do not have a NEI Bee Breeding page

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#10966]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-25-pre +gt from jenkins

### Your Server

SP

### Your Expectation

every bee should have a NEI breeding page

### The Reality

some do not. For example vindictive and vengeful. I can see them indirectly by looking at avenging: 
![image](https://user-images.githubusercontent.com/40274384/183314071-13b08dd7-af7a-4883-93f7-cc617e9c1331.png)

but selected either directly does not lead to a bee breeding page. They only have a broken botania page instead (there should not be a botania page obviously).
![image](https://user-images.githubusercontent.com/40274384/183314126-44be0f85-4613-4b0a-b6c1-07e276496230.png)

For this behavior specifically I only found vindictive and vengeful.
But merry, tipsy, thorium, inf catalyst, neutronium, and probably more also have the breeding page missing but no botania thing. (edit: potentially some are mutratron only, then dont change anything ofc)

### Your Proposal

add the breeding page where its missing.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by King65868** [comment]
At least some of them are mutatron only, but yea would be good if vindictive and vengeful was fixed

**Comment by chochem** [comment]
oh I see but yeah not the early ones

**Comment by Runakai1** [comment]
Fixed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/10989#issuecomment-1211003895

**Comment by Runakai1** [comment]
> At least some of them are mutatron only, but yea would be good if vindictive and vengeful was fixed

All bees can be bred normally, even if only mutatron shows up.
