### ISSUE TITLE
 The required block for bee mutation does not show the localized name for many gt and ic2 blocks

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#10973]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.2.4-25

### Your Proposal

When you search how to mutate a Naquadah bee
the info said "Requires gt.metalblock4.12.name as foundation "
not only Naquadah bee be also more like Plutonium
We don;t know what's that block

### Your Goal

Make it more understandable

### Your Vision

of course

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
This only seems to affect gregtech blocks, and is not limited to bee breeding. See for example the description of the VM2:

![image](https://user-images.githubusercontent.com/40274384/184360640-1678a79f-2dfa-4095-a8de-e446a1c55488.png)

**Comment by miozune** [comment]
Miner description was fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1215 and https://github.com/GTNewHorizons/bartworks/pull/178

**Comment by KamenriderZO** [comment]
By the way not only GT
look at the mutation to "Steel bee" , 
the ic2.blockmetalAdvIron shows that ic2 block also miss name.

**Comment by chochem** [comment]
uh. I guess stumbling onto both of these on the same day made me connect dots that were not related.

you are right, ic2 blocks are broken too. And I just updated my gt and that fixed half the miner tooltips. I guess updating bartworks would be the other half. I guess I am changing the title kinda back sry for that distraction.
