### ISSUE TITLE
Diatomite Dust has incorrect chemical formula

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10977]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.4-dev25

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The correct chemical formula should be (SiO₂)₈Fe₂O₃(Al₂O₃).

### The Reality

The formula shown is (SiO₂)₈Fe₂O₃Al₂O₃. To keep with the format we have already, this should be updated to ensure that the Oxygen in the formula is not shown twice in the same sequence of elements without a divider.

### Your Proposal

Update the tooltip.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
no, that is not correct. diatomite is 80-90% silicia. The fomula you claim is current is also not the one I see in game.
![image](https://user-images.githubusercontent.com/40274384/185804977-51b6f2d3-c932-47e2-925f-bdcd254aa5c5.png)

**Comment by TwoTailedFox** [comment]
It does not follow the Hill system of chemical notation because you have declared Oxygen twice, and the elements (since there are no Carbon or Hydrogen atoms present) are also listed incorrectly. If you're not grouping molecular compounds together, then it should actually be written like this:

Al₂Fe₂O₅(SiO₂)₈

**Comment by chochem** [comment]
I dont care one bit about the order its written, I just dont want you guys to randomly change the composition by mistake.

**Comment by TwoTailedFox** [comment]
(SiO₂)₈Fe₂O₃(Al₂O₃) does not change the composition, just ensure that the Alumina molecule is represented separately.

**Comment by chochem** [comment]
now that you added the 8, yes.
