### ISSUE TITLE
Allow PAs to output as fluids

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#10986]
### Your GTNH Discord Username

Lord Peverell#3125

### Your Pack Version

2.1.2.4-25-pre

### Your Proposal

Allow PAs to output as fluids and not need cells

### Your Goal

Allow PAs to no longer need cells for recipes

### Your Vision

PAs output fluids please

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by POPlol333** [comment]
the problem is that, they aren't allowed or not, PA recipe take the singleblock recipe map, which are mostly made out cells when it comes to fluids

**Comment by joshaup1999** [comment]
Would be nice if it was changed though for the PAs, would be a big help on tick time as well i believe

**Comment by POPlol333** [comment]
It would indeed, but on others hand if they didn't had to handle cells PA would become wild OP

**Comment by BlueWeabo** [comment]
GT++ multiblocks don't use cells for their crafting. They can use pure fluids. PAs are worse in most situations when compared to GT++ multiblocks. It wouldn't be too OP for them to not take cells

**Comment by joshaup1999** [comment]
I'd like to point towards ++...

**Comment by POPlol333** [comment]
I'm personally not against it, but there's a lot of PA haters that will probably bitch about it. Yeah on that point GT++ are kinda op, but actually if you look closely PA are way better if you don't care about energy and you'll to craft like 64 singleblocks machine of a tier high enough to make the recipe fast

**Comment by joshaup1999** [comment]
Its called equality! No reason why PAs need to have cell interactions whilst ++ doesnt

**Comment by boubou19** [comment]
PAs are a dirty hack to let you do extreme parallel or recycle your old single blocks in exchange of some power. As a result, it uses all the recipes of the single block. One would need to make the PA code worse just to fix that. As pointed out in this ticket, ++multis are far superior in nearly all the cases. Not using them is asking for pain.
