### ISSUE TITLE
Copper cable dupe

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#10988]
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

dev18

### Your Server

SP

### Your Expectation

You need a machine disassembler.

Put Mv transformer -> get IC2 transformer + 2 copper cables.
Put IC2 transformer -> get Mv transformer + 2 2x copper cables.

one cycle and you get 2 1x copper cables and 2 2x copper cables.

### The Reality

The transformer disassembling cycle should not exist.

### Your Proposal

Change the recipe so that disassembler doesn't give IC2 transformer.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by POPlol333** [comment]
dissasemblers strikes again, we need a label for this
