### ISSUE TITLE
Large generator array causes HOG to produce infinite 40k EU/t

### ISSUE THREAD

**Issue by Josh5minus1** [GTNewHorizons/GT-New-Horizons-Modpack#10983]
### Your GTNH Discord Username

A1#8299

### Your Pack Version

2.1.2.4-25 dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to run Large Generator Array with 16 basic combustion generators, with HOG as fuel in input bus, i expect it to get consumed and only produce 16x32 = 512 EU/t

### The Reality

The HOG is not consumed, and produces 40k EU/t, which is surprising, as what it says when using scanner on the LGA.

### Your Proposal

Make the HOG get consumed and correct the power output calculation of LGA, as it can be used for infinite power at more than 1A LuV.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by querns** [comment]
Is the Large Generator Array even intended to be used? I thought it wasn't implemented or not properly implemented.

**Comment by Josh5minus1** [comment]
well there is currently a recipe for the multi, previous versions of the pack doesn't have recipe

**Comment by Steelux8** [comment]
I'll look at it to see what's going on.

**Comment by alexandre-tardif** [comment]
For a little more context I looked into it and disabled it for now. The multi is not finished
