### ISSUE TITLE
Unable to load any saves - can create new worlds fine

### ISSUE THREAD

**Issue by survivorchris** [GTNewHorizons/GT-New-Horizons-Modpack#10985]
### Your GTNH Discord Username

Kelsier__#3205

### Your Pack Version

2.1.2.3

### Your Server

SP

### Your Actions

Trying to load old save following updating Java from x32 to x64. Creating new worlds works fine however trying to load old saves and backups keeps producing the following error and crash:

java.io.EOFException
Crash exit: -1

Also getting the below item removal notice.

![image](https://user-images.githubusercontent.com/110969107/183860445-ecb8fb1f-046f-4f05-b282-056b3a293f4e.png)

### Crash Report

https://paste.ee/p/Y1iTP

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
your antivirus deleted logistic pipes because it was detected as a false positive, also your extra utilities jar is disabled somehow. The log you provide doesn't contain any crashlog.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
