### ISSUE TITLE
Reopen of #10980 

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#10981]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Proposal

I'm not talking about the cover
I mean item filters
![image](https://user-images.githubusercontent.com/59776356/183721888-d6f97abb-d245-4733-bc55-fefb4e0b3d8a.png)

### Your Goal

The staff misunderstood me
and closed the discussion 
i am reopening it here 

### Your Vision

Reduce repetitive work

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Eason134HK** [comment]
#10980

**Comment by chochem** [comment]
dont spam tickets pls, just write there
