### ISSUE TITLE
Add a item that can copy GT filter setting

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#10980]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Proposal

Add a item that can copy GT filter setting

### Your Goal

when setting something at a large amount using GT filter 
I always wondering it will be nice if we have a gadget like conduit probe that can copy settings to 1 filter to another 
![image](https://user-images.githubusercontent.com/59776356/183708060-498fc21e-1fdb-439b-b9c5-36475414e7e7.png)

### Your Vision

Reduce repetitive work I think nobody doesn't like the change

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by DianeXD** [comment]
Please check the new version, there is a "cover copy/paste tool".

**Comment by DianeXD** [comment]
![ezgif-6-17c9fc875b](https://user-images.githubusercontent.com/64360468/183714381-ef75d252-65ff-4520-b669-6a65e940f28f.gif)

**Comment by Eason134HK** [comment]
> ![ezgif-6-17c9fc875b](https://user-images.githubusercontent.com/64360468/183714381-ef75d252-65ff-4520-b669-6a65e940f28f.gif) [ ![ezgif-6-17c9fc875b](https://user-images.githubusercontent.com/64360468/183714381-ef75d252-65ff-4520-b669-6a65e940f28f.gif) ](https://user-images.githubusercontent.com/64360468/183714381-ef75d252-65ff-4520-b669-6a65e940f28f.gif) [ ](https://user-images.githubusercontent.com/64360468/183714381-ef75d252-65ff-4520-b669-6a65e940f28f.gif)

![image](https://user-images.githubusercontent.com/59776356/183720228-2b53613a-c9b2-4fe5-834e-0013e9f5f9b5.png)
![image](https://user-images.githubusercontent.com/59776356/183720399-a75b5c76-3dd9-4275-b076-44bdcdfb09c4.png)

I am talking about these filter not the filter cover
