### ISSUE TITLE
Squid is not squid but actually octopus

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#10996]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

I recently learned how to tell the difference between octopus, neritic squid, oval squid , squid, and cuttlefish
So I'm trying to identify if Minecraft squid are real squid. The outcome is mind blowing

### The Reality

Squid should have 10 arms but the "Squid" i found only have 8 
![image](https://user-images.githubusercontent.com/59776356/184139191-29076327-1653-4956-a684-b8aed7eb9265.png)

"Squid" are not squid they are most likely be octopus

### Your Proposal

Change their names to octopus
or give them two more arms

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Nolij** [comment]
I believe this is an upstream issue.

**Comment by leagris** [comment]
See: https://bugs.mojang.com/browse/MC-89883?jql=project%20%3D%20MC%20AND%20text%20~%20%22squid%22
