### ISSUE TITLE
Weird behavior or Crash with ReplayMod 2.5.2

### ISSUE THREAD

**Issue by Blade8895** [GTNewHorizons/GT-New-Horizons-Modpack#10994]
### Your GTNH Discord Username

Blade8895#6067

### Your Pack Version

2.1.2.4-25-pre

### Your Server

Private Server & SP 

### Your Actions

Starting with ReplayMod in the neweset pack versions let me load into the Game and Record without any Problems. (to view the replays i must mostly reload my game but thats ok!)

But i got a weird looking hand texture. its completly offset and not showing any tools in hand what can be annoying.
![2022-08-11_08 52 13](https://user-images.githubusercontent.com/76847661/184089766-c27b6591-19de-4958-81f9-723052d4e867.png)
![2022-08-10_22 12 35](https://user-images.githubusercontent.com/76847661/184089799-7122b8cb-181c-4221-84a6-e320441a12c9.png)

- [ X ] Tried without Optifine
- [ X ] Tried with different versions of ReplayMod for the 1.7.10 MC Version

In older Versions of the Pack (i tested only 2.1.1.0) it wont load because of Mixin Errors.

They have the Sourcecode more or less opensource on GitHub with a very weird versioning system.
https://github.com/ReplayMod/ReplayMod

i hope you guys can help me to get this Running. 
It will help all of us to create more epic Videos of the ModPack :D
i hope you guys can help me to get this Running. 
It will help all of us to create more epic Videos of the ModPack :D

### Crash Report

Log from Technic Launcher from the 2.1.1 Mixin Error

https://pastebin.com/b6sfTBNy

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
Why don't you record externally instead of adding a mod we don't support?

**Comment by POPlol333** [comment]
The mod is most likely not  supported, there already hundreds of mods so it would have been more strange if it actually worked lol

**Comment by Blade8895** [comment]
"Why don't you record externally instead of adding a mod we don't support?"

Thats very easy. 
Because not everyone had a powerfull pc to do this :D 
and with Replaymod you can Render Footage from an external Camera view. and you dont need to setup a Spectating Camera then run do your stuff and move it every second you need an another angle.
Basicly you can "Record" and then just Render the Angle and the Time you want out of it. 
It is a very awesome tool to render Cinematic Scenes out of it.

And its just the Hand Texture by now... that must be in someway fixable :P

**Comment by POPlol333** [comment]
You're right on the fact that ReplayMod is really useful for all YTB and videos stuff, but unfortunately it's not because it affect only the hand that this is "easy fixable" sometimes bugs are caused by strange archwizardry doing

**Comment by Blade8895** [comment]
"sometimes bugs are caused by strange archwizardry doing"

you are absolut right about that.

Thats why i am hoping some of the Gurus here knows what he can do about it.
By now i talked to the ReplayMod Devs. They sad all of the GTNH Mods are combatible... but they dont believe that many of the Mods are extended or backportet from the GTNH Devs itself.
They sad nobody will do something just for Minecraft :D

so Challange Accepted?^^

**Comment by wohaopa** [comment]
I also want to use replaymod in GTNH, [this](https://github.com/wohaopa/ReplayModFixMod) is a fix I made, it just works on 2.2.8
