### ISSUE TITLE
Gallium Arsenide Crystal should be yielding 2 dusts, not 1.

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10993]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.4-dev25

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Because 1 Gallium Dust and 1 Arsenic Dust have gone to create 1 Gallium Arsenide Crystal, the crystal when macerated should yield 2 Gallium Arsenide Dusts.

### The Reality

1 Gallium Arsenide Crystal, when macerated currently yields 1 Gallium Arsenide Dust. This is inconsistent with the way the mod handles alloys in that mass should be preserved so that materials are not lost unfairly.

### Your Proposal

Adjust the macerator recipe to yield 2 dusts OR change the EBF recipe to yield 2 crystals.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
now I see why you labeled this a bug, not suggestion. This breaks chem standardization rules.
