### ISSUE TITLE
Bronze Work Bench doesnt count as crafting for quests

### ISSUE THREAD

**Issue by runcreeper** [GTNewHorizons/GT-New-Horizons-Modpack#10990]
### Your GTNH Discord Username

Doomed_One#5926

### Your Pack Version
2.1.2.4-25-pre 

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Crafting a LV resistor in the workbench for the quest to be counted .

### The Reality

Crafts the resistor but quest book does not acknowledge the crafting.

### Your Proposal

Update quest book mod to include bronze workbench for crafting quests.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
Bronze workbench? Which mod ads it ?

**Comment by runcreeper** [comment]
Sorry for delay its the Bronze Workbench by GT++ Alkalus 2084:31081

**Comment by Connor-Colenso** [comment]
Ahh yes another fine example of how amazing crafting quests are.

**Comment by Dream-Master** [comment]
> Ahh yes another fine example of how amazing crafting quests are.

no a new example every mod use different crafting methodes i guess.
