### ISSUE TITLE
FastCraft Crash

### ISSUE THREAD

**Issue by runcreeper** [GTNewHorizons/GT-New-Horizons-Modpack#10991]
### Your GTNH Discord Username

Doomed_One#5926

### Your Pack Version

2.1.2.4-25-pre 

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Was Walking from stone age base to steam age base when it crashed.

### Crash Report

https://paste.ubuntu.com/p/4zZrKT2qyT/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
can you post that somewhere else? that is a restricted page.

**Comment by runcreeper** [comment]
https://pastebin.com/WUfjyami

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
