### ISSUE TITLE
AE2FC fluid crafting does not finish craft if fluid stored on subnet

### ISSUE THREAD

**Issue by CharlieTuna8** [GTNewHorizons/GT-New-Horizons-Modpack#11001]
### Your GTNH Discord Username

Charlie Tuna#7949

### Your Pack Version

2.1.2.4-18

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

I request 144 MB soldering alloy, it crafts, fluid in storage on subnet, craft completes.

### The Reality

I request 144 MB soldering alloy, it crafts, fluid in storage on subnet, craft does not complete and will forever stay waiting on 144 MB soldering alloy.

(I tested putting the storage on main and it finished the craft like it should)

### Your Proposal

Finish craft.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
fluid subnet storage is fine, but you need to put all fluid i/o port in main network.
further investigation is under work
