### ISSUE TITLE
Allow parallel output of stacks of the ME Output bus

### ISSUE THREAD

**Issue by GTNHAfx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#11004]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.4dev 18

### Your Proposal

Allow the ME output bus to empty it’s content in parallel, not in serial.

Example: I rearranged ore processing to be pure AE (interfaces into input busses and ME output busses as buffer). One PA with simple washers handles crushed coal and crushed lapis. Another PA with sifters handles purified coal and purified lapis (each with separate storage bus).
Only the input busses with purified lapis will be filled as this is the first stack in the ME output bus. If it dumped its contents in parallel, both sifter PAs could work.

### Your Goal

Not have to wait for an ME output bus to empty its contents one after the other.

### Your Vision

Faster processing I guess?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
Do you mean GT's ME output bus or AE2's ME export bus? If it's latter, have you tried ME export bus's round robin mode?

**Comment by GTNHAfx237v7** [comment]
GT‘s ME Output Bus.

**Comment by repo-alt** [comment]
In general case this will slow down emptying ME Output bus a lot (if e.g. it will split it's contents to 64-sized stacks and store them in the network one by one). Also, if the first storage bus cannot accept all the lapis, it will go ito another storage bus, and even exporting stack by stack won't change much

**Comment by GTNHAfx237v7** [comment]
I was led to believe that the content of the ME output bus would be dumped just like when AE handles item output via a storage bus. Say a storage bus facing an empty chest has to handle 3 stacks of cobble and 3 stacks of iron, womit dump all 6 stacks simultaneously? Visually I would say yes, but code wise I do not know.

**Comment by repo-alt** [comment]
> Say a storage bus facing an empty chest has to handle 3 stacks of cobble and 3 stacks of iron, wouldn't it dump all 6 stacks simultaneously? 

It would first dump one stack of 192, then another stack of 192. Either I don't really understand what do you want, or you don't really understand the consequences of implementing what do you want.

**Comment by GTNH-Afx237v7** [comment]
I guess the consequences will be much slower item handling, surely something no one wants. I’ll have to think of a different way to handle my processing. Thx anyway for the explanation.

**Comment by repo-alt** [comment]
I hope the next variant of ME input bus should help when/if I'll have time to implement it (or maybe someone else if I'll be out of time before vacation)

**Comment by GTNHAfx237v7** [comment]
The one that was recently merged already sounds like a decent solution; Grab what ever item is stored in AE (interface and conveyor into input bus was what I was using before).
