### ISSUE TITLE
Make dissolution tank and digester structure more QOL friendly

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#11008]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.1.2.4 20 pre

### Your Proposal

Make the blocks outside the structure not cause a incomplete, there's no reason that blocks outside a tank can cause it to not be a valid tank, this makes automation harder and ugly air gaps around it 

### Your Goal

QOL

### Your Vision

QOL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TrainerSnow** [comment]
Submitted PR for this, https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/28
