### ISSUE TITLE
GTNH AppleCore breaks HungerOverhaul

### ISSUE THREAD

**Issue by DrParadox7** [GTNewHorizons/GT-New-Horizons-Modpack#11000]
### Your GTNH Discord Username

TechnoParadox#6840

### Your Pack Version

GTNewHorizonsServer-1.7.10-2.1.2.4-25-pre

### Your Server

SP

### Your Expectation

Having this config from Hunger Overhaul to work:
```
    # Minimum hunger level before healing starts [vanilla: 18] [range: 0 ~ 2147483647, default: 7]
    I:minHungerToHeal=8
```
https://github.com/GTNewHorizons/HungerOverhaul/blob/0504469e11b92925933fd27e84548cc540e2f682/src/main/java/iguanaman/hungeroverhaul/food/FoodEventHandler.java#L87

### The Reality

It does not.

Healing still requires 18 hunger
![HungerIssues](https://user-images.githubusercontent.com/47131096/184230403-b5b071a8-aa9a-46b9-905a-f325cba5b861.gif)
.

### Your Proposal

Fix AppleCore 3.2.0 breaking HungerOverhaul, working as it did on version 3.1.1
3.1.3 and above are all broken _(couldn't test 3.1.2)_.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DrParadox7** [comment]
Damage on Starve is also broken, and is not reliably firing at every instance of starvation damage.

**Comment by DrParadox7** [comment]
Well Fed Buff is also broken and will provide regeneration unless player is at 18 shanks:

![No regen](https://user-images.githubusercontent.com/47131096/184336865-15427da7-332c-4389-9c49-fab204912be6.gif)

**Comment by tyrael93** [comment]
Can confirm that going back to version 3.1.1 fixes the issues presented.
It also breaks the New Horizons fork of Natura at startup though.

**Comment by DrParadox7** [comment]
Upon investigating it looks to be issue #9158 except it goes beyond breaking hunger on peaceful and very likely more than what has been reported here.

**Comment by wlhlm** [comment]
I think found the underlying issue. Should be fixed soon. @DrParadox7 thanks for the effort you put into this bug report, it helped a lot with tracking down the underlying problem.
