### ISSUE TITLE
ME Level Emitter not working properly

### ISSUE THREAD

**Issue by homullily** [GTNewHorizons/GT-New-Horizons-Modpack#11006]
### Your GTNH Discord Username

homuhomu#9810

### Your Pack Version

2.1.2.4-25-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

ME标准发信器反应迟缓，如果快速从ae网络中存入或取出物品，ME标准发信器会无法正确的发出或停止红石信号。
Machine translation：
ME Level Emitter respond slowly, If store or take item quickly in ae network. Which could not send or stop Redstone signals correctly.

### The Reality

当ae网络中的物品数量大于或小于设置数量时，ME标准发信器应该会迅速发出或停止红石信号。
Machine translation：
When the item number greater or less than the number already set, ME Level Emitter should send or stop Redstone signals immediately.

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
There is a setting "levelEmitterDelay" in AE2 config. Be aware that delay is there for a reason, constantly updating network cache is expensive.
