### ISSUE TITLE
Item pipes are not activated by signals from redstone pipes of other color channels

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#11003]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.1.2.4 pre-20

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

![QQ图片20220812203303](https://user-images.githubusercontent.com/98251218/184354799-3b073bf6-8b55-436a-ab3e-4f7167655549.png)
I use redstone pipes to control item pipes for input
![QQ图片20220812203315](https://user-images.githubusercontent.com/98251218/184354918-2390a710-e5dc-4c2e-883b-abad0a2d46c2.png)
![QQ图片20220812203319](https://user-images.githubusercontent.com/98251218/184354935-d41b2567-8b4d-457b-9d24-1e6f88ea2aa1.png)
But it didn't input after receiving the redstone signal as expected
![QQ图片20220812203323](https://user-images.githubusercontent.com/98251218/184355060-57156e62-a68d-4439-9a5a-0c9bd6962a58.png)
But the redstone light on the same redstone signal channel is on

### The Reality

Redstone conduits, except for the red channel, cannot control item conduits for input

### Your Proposal

This is a bug that needs to be fixed, the automation in my house has been forced to shut down because of this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by n0099** [comment]
Same here

**Comment by Viktor-KN** [comment]
Item conduits don't have redstone channel color button for some reason... But fluid one has. Can we get it back?
