### ISSUE TITLE
GTPP multies should support separate input bus toggle (like the PA)

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#11012]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.1.2.4 20 pre

### Your Proposal

make GT++ multies and GT Multies have similar behavior instead of having to learn them separately. Same goes for the void excess and input filter behaviors that we have now.

### Your Goal

QOL

### Your Vision

QOL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
> GTPP multies should support separate input bus

They do, by default. Thats where the idea came from to add it to the PA.

They also have optional voiding mode. On that they just have *more* functionality than other multis.

**Comment by tommy307507** [comment]
> > GTPP multies should support separate input bus
> 
> They do, by default. Thats where the idea came from to add it to the PA.
> 
> They also have optional voiding mode. On that they just have _more_ functionality than other multis.

I tried on the gtpp mixer to set to this mode (screwdriver the controller block) however it doesn't have the ability to toggle this separate input bus. they do this by default and mandatory , I want the ability to toggle with a tool instead of being forced to use this

**Comment by chochem** [comment]
oh, so you want it off? thats like the opposite of what the ticket says

**Comment by tommy307507** [comment]
sorry I should have specified the toggle ability ;p
