### ISSUE TITLE
Rock Salt Electrolysis and Glass Dust centrifuging recipes have vanished. And many more!

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#11017]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-25-pre+mod updates(!), see below

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expect Rock Salt to electrolyze for some chlorine and glass dust to centrifuge into silicon dioxide like they have both done for ages.

### The Reality

The recipes are gone. Runa and I only noticed these two, maybe a lot more stuff is missing. There also seems to be no commit or ticket that is named 'nerf rock salt' or similar.

my versions beyond dev25:
GTNewHorizonsCoreMod-1.7.10-1.9.39-11-gdc3e377 (local build)
gregtech-1.7.10-5.09.40.89
and more, can provide mod version where deemed relevant.

### Your Proposal

Find out whats going on and/or readd them.

Runa already made a PR to readd one of them https://github.com/GTNewHorizons/GT5-Unofficial/pull/1252
but it might be suitable to first find out whats happening.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
was able to load up an older version to get a picture of the now missing recipes: 
![image](https://user-images.githubusercontent.com/40274384/184516179-b19c39a7-c0c9-4945-aad2-fb4d36e80cf9.png)
![image](https://user-images.githubusercontent.com/40274384/184516194-71725048-5f76-49dc-88a8-6f914457ddd2.png)

**Comment by chochem** [comment]
That pictured flint dust recipe there is also gone now. And I looked at the numbers. Just to estimate the worst case scenario I also looked at the number of recipes in the electrolyzer and centrifuge to see how bad it might be. and we now have around 200 electrolyzer recipes and 100 centrifuge recipes less than 3 weeks ago.

**Comment by chochem** [comment]
also apatite, monazite, garnet dusts, methane, to name a few more that people have spotted

**Comment by chochem** [comment]
also cobaltite, phosphate, borax, barite, saltpeter, bauxite, galena, almandine, spessartine, chromite, tantalite, grossular, pyrope, andradite, uvarovite all cant be electrolyzed anymore (thanks gdc)

I am gonna upgrade this to major

**Comment by Connor-Colenso** [comment]
Seems to be caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1223. I reverted this commit and now the recipes have returned.
