### ISSUE TITLE
Cerium rich mixture doesnt have recipes in nei

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#11011]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.1.2.4 20 pre

### Your Proposal

In nei it only has packager and crafting table (small / tiny piles ), there's no ore proc recipes for making it , in quest book it says its from ores, maybe have a tip  for where to get it?
![image](https://user-images.githubusercontent.com/49487505/184467414-5b9be1ed-3828-4a9a-ad6b-4d3a3c5cac8a.png)

### Your Goal

QOL

### Your Vision

QOL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by tommy307507** [comment]
ACTUALLY, this is what happened 
![image](https://user-images.githubusercontent.com/49487505/184467454-af216bb0-d32f-4554-9061-bd0bf0105994.png)
it was 
![image](https://user-images.githubusercontent.com/49487505/184467467-fcc7c2db-e4b0-405b-b890-c98c0d9ba496.png)
in dev-4 and dev-5 , this is more so of a bug I think...

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/22
