### ISSUE TITLE
Soul brazier crash the game when entering personal dimension

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#11014]
### Your GTNH Discord Username

tim lam

### Your Pack Version

2.1.1.4-dev15

### Your Server

SP

### Your Actions

When the second time i enter personal space, it crash

### Crash Report

[crash-2022-08-13_22.24.47-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9331588/crash-2022-08-13_22.24.47-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by cubic-chariot** [comment]
I'm also getting a similar crash. My soul brazier is in the Overworld. This happens intermittently, when I'm loading the world. I'm on 2.1.2.3qf, except that I updated Thaumic Exploration to 1.7.10-1.1.88 from [this link](http://jenkins.usrv.eu:8080/job/ThaumicExploration/lastSuccessfulBuild/artifact/build/libs/Thaumic-Exploration-1.7.10-1.1.88-GTNH-1-gc7dd5b5.jar) (to avoid  #10725), and I downgraded Galacticraft and Galaxyspace to the versions shipped with 2.1.2.0 (to avoid #10377)

Crash report: [crash-2022-08-13_23.21.15-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9332691/crash-2022-08-13_23.21.15-server.txt)
