### ISSUE TITLE
Add Nickelback Leaf recipe to roasted nickel

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#11013]
### Your GTNH Discord Username

tim lam

### Your Pack Version

2.1.1.4-dev15

### Your Server

SP

### Your Expectation

![image](https://user-images.githubusercontent.com/105285781/184494238-226ed023-ffc7-4179-9c67-ffcb14068e46.png)
garnierite should give garnierite instead of roasted nickel
garnierite dust missing blast furnace recipe

### The Reality

![image](https://user-images.githubusercontent.com/105285781/184494231-df3f9fb6-d175-47bd-abd2-72d2ed408b27.png)
it is weird ore dict

### Your Proposal

Fix roasted ore to have quad recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Laiff** [comment]
This issue still actual

**Comment by Impos913** [comment]
Still no quadrupling recipe with crop leaves for roasted nickel and roasted iron in 2.4.0
