### ISSUE TITLE
Crash when opening Fluid Canning Machine recipe tab in NEI for some fluids

### ISSUE THREAD

**Issue by DotJason** [GTNewHorizons/GT-New-Horizons-Modpack#11010]
### Your GTNH Discord Username

DotJason#2491

### Your Pack Version

2.1.2.4-25-pre

### Your Server

SP

### Type of Server

Single Player

### Your Actions

1. Searched NEI for recipes of (left-click) Molten MAR-Ce-M200 Steel (as a fluid, not in a cell)
2. Clicked on the Fluid Canning Machine tab
3. Immediate crash upon clicking

After restarting, did the exact same thing with Molten MAR-M200 Steel and got the same result.
Unfortunately, after the second restart neither sequence of actions (or with any other fluid) seems to produce a crash.

### Crash Report

[crash-2022-08-12_22.44.55-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9329832/crash-2022-08-12_22.44.55-client.txt)

[crash-2022-08-12_22.48.40-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9329834/crash-2022-08-12_22.48.40-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
I tried to reproduce this and ran into a (different!) error within seconds too.

Steps to reproduce:

Step 1. rightclick any fluid canner

(yeah that was the full list of steps)

result: error message in chat
![image](https://user-images.githubusercontent.com/40274384/184444065-fc197a0f-ece0-4bab-85e2-0988d98bbbd1.png)
and the log says
[fml-client-latest - Copy.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9329871/fml-client-latest.-.Copy.log)

clearly something is wrong with fluid canner recipes. :/

However I have no problem looking at the fluid canner recipe for molten mar or marce. So maybe these are 2 unrelated problems.

**Comment by YannickMG** [comment]
So I couldn't reproduce the crash with the reported fluid, but it appears that some commit has completely broken basic machine tiered recipe lookup.

**Comment by YannickMG** [comment]
> I tried to reproduce this and ran into a (different!) error within seconds too.
> 
> Steps to reproduce:
> 
> Step 1. rightclick any fluid canner
> 
> (yeah that was the full list of steps)
> 
> result: error message in chat ![image](https://user-images.githubusercontent.com/40274384/184444065-fc197a0f-ece0-4bab-85e2-0988d98bbbd1.png) and the log says [fml-client-latest - Copy.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9329871/fml-client-latest.-.Copy.log)
> 
> clearly something is wrong with fluid canner recipes. :/
> 
> However I have no problem looking at the fluid canner recipe for molten mar or marce. So maybe these are 2 unrelated problems.

Adressed this in GTNewHorizons/GT5-Unofficial#1244.

For the originally reported issue, it looks like it might be tough to reproduce.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
