### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by TimberDimber** [GTNewHorizons/GT-New-Horizons-Modpack#11022]
### Your GTNH Discord Username

TimberDimber

### Your Pack Version

2.1.2.4-25-pre

### Your Server

SP

### Type of Server

Single Player

### Your Actions

After a random period of time, the screen becomes beige (GUI disappears) after which the client freezes for a few seconds and an error message occurs related to the MCFrames and ForgeRelocation mods
![image](https://user-images.githubusercontent.com/22298720/184550707-3e47a312-815a-4327-a146-0bc4b466c1de.png)
![image](https://user-images.githubusercontent.com/22298720/184550719-92d0d2aa-4181-4bb0-89c1-2ab2fcb61b41.png)

The crash has already occurred 3 times after an approximately equal period of time (around 1 hour)

### Crash Report

[crash-2022-08-14_20.54.54-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9333862/crash-2022-08-14_20.54.54-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
