### ISSUE TITLE
Extreme Extermination chamber have strange overclock

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#11020]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.1.2.4-25-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

So basically nei page says this
![image](https://user-images.githubusercontent.com/39595617/184542434-6dcf98a2-7c2a-4970-8185-21002efb455e.png)
8.25 seconds = 165 ticks
because mob is always infernal, energy usage should be 16k eu/t(2000 base * 8)
i am supplying uv to so i should get 165/4 = 41 tick
while i am getting 74 ticks and 1,024,000 eu/t used

### The Reality

-

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
2000 * 8 = 16000
16k * 4 * 4 * 4 = 1024k <----- 3 overclocks
165 / 2 / 2 / 2 ~= 20 ticks
So the recipe should be done in 20 ticks, **but** since its Infernal mob, it has **more health**
Thats why its longer than expected.

**Comment by LewisSaber** [comment]
welp, makes sence, ty
