### ISSUE TITLE
Multi Smelter incorrectly processes recipes with more than 1 output item

### ISSUE THREAD

**Issue by DotJason** [GTNewHorizons/GT-New-Horizons-Modpack#11028]
### Your GTNH Discord Username

DotJason#2491

### Your Pack Version

2.1.2.4-25-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Processing any smelting recipe that outputs more than 1 item at a time, i. e. Crushed Gold Ore -> 10 Gold Nuggets, or Sphalerite Ore (raw block ore, Nether variant) -> 2 Zinc Ingots, in the Multi Smelter.

### The Reality

The Multi Smelter only outputs 1 item per 1 input item, i. e. 32 Crushed Gold Ore -> 32 Gold Nuggets (with an MV Output Bus, so there should be enough space for the intended output), and 32 Sphalerite Ore (raw block ore, Nether variant) -> 32 Zinc Ingots, also processing 1 item at a time yields the same result (1 Crushed Gold Ore -> 1 Gold Nugget).

A normal furnace works fine with those recipes though.

### Your Proposal

Make the Multi Smelter properly output for recipes with more than 1 output item at a time.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment]
Works fine in .3qf, probable casualty of https://github.com/GTNewHorizons/GT5-Unofficial/pull/1108
