### ISSUE TITLE
Machines disappearing in lagspike

### ISSUE THREAD

**Issue by JustBenji** [GTNewHorizons/GT-New-Horizons-Modpack#11027]
### Your GTNH Discord Username

Benji#0586

### Your Pack Version

2.1.2.0

### Your Server

ETA

### Type of Server

Don't know

### Your Expectation

Picking the machine up with a wrench.

### The Reality

The machine (HV Mixer) lagged out when picking up, there came a pink/black blocked box (The type of box when a block is not loaded correctly) then I used wrench again, item didnt drop but is disappeared.

Time of event 21:38 at ETA official server
X: 3781
Y: 65
Z: -2601

### Your Proposal

Fix the bug, get back my HV Mixer :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
I have definitely seen this behaviour on the officials before. Seems kinda bizarre, doesn't happen with non-GT stuff.

**Comment by JustBenji** [comment]
> 

It happened before with a LV wiremill, but a mate told me and i thought he was just making a mistake or something. Now it happened to me.

**Comment by POPlol333** [comment]
don't know if it's actually the same bug, but two days ago a QC2 dissapeared in the same condition for me on delta

**Comment by ppozniak** [comment]
Just happened to me.
Used wrench to remove the machine, it turned into a pink/black block with `.name` and then disappeared.
The machine was not dropped.

* GTNH version: `2.2.8`
* Block: **GT Crop Manger (LV)**
* Single player
* MultiMC
