### ISSUE TITLE
GT++, GG, bartworks NEI pages crash

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#11039]
### Your GTNH Discord Username

Lord_Anarack#2705

### Your Pack Version

Dev 27

### Your Server

SP

### Your Actions

Tried to search for the usage of Beryllium Fluoride from the liquid in a machine or the cell in nei, game instantly crashes.

### Crash Report

https://pastebin.com/qPpEW9wm

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Anarack** [comment]
LFTR nei page is also a instant crash.
https://pastebin.com/m4CtYU5x

**Comment by chochem** [comment]
@miozune I think you did some stuff there

**Comment by chochem** [comment]
also happens when looking at a neutron activator

[crash-2022-08-17_00.37.25-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9355271/crash-2022-08-17_00.37.25-client.txt)

**Comment by pilchard436** [comment]
I also crashed when looking at any recipes related to the neutron activator
[crash-2022-08-16_16.55.58-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9355340/crash-2022-08-16_16.55.58-client.txt)

**Comment by chochem** [comment]
add bartworks to the list, well the NEI handler is in gregtech.

[crash-2022-08-17_01.25.35-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9355420/crash-2022-08-17_01.25.35-client.txt)

**Comment by chochem** [comment]
I think that means its probably caused by these changes: https://github.com/GTNewHorizons/GT5-Unofficial/commit/43c014a8db9ad4d44c19190718835a7596dc0a2d#diff-4db87b23352cd956ad1d2464dfce2e50c23565bfd39cbf4c537f54e1a403d25dL124

dont know whats going on there though, or how to fix it.

**Comment by Glease** [comment]
Recompile all GT addons against the latest GT will fix this.

**Comment by chochem** [comment]
this is not a local compilation. this is the dev release

**Comment by Glease** [comment]
Yes? And the fix would be Recompile all GT addons against the latest GT. What's wrong with that?

**Comment by Dream-Master** [comment]
ok i try that

**Comment by Dream-Master** [comment]
fixed
![image](https://user-images.githubusercontent.com/2970688/185083167-529f5d75-e3b8-44e9-abbb-e0dd639d0af4.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/185083497-c7305114-e176-4821-9515-fa05e1652c0b.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/185083684-798d7c55-59d7-4de0-a72b-6c2a1fa9fc6e.png)
