### ISSUE TITLE
Server crashes after player right click on the bed sleep.

### ISSUE THREAD

**Issue by quickgk** [GTNewHorizons/GT-New-Horizons-Modpack#11034]
### Your GTNH Discord Username

kirinquick#7619

### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Actions

The server crashes after a player right clicks on a bed to sleep when other players are already asleep.

### Crash Report

[crash-2022-08-16_18.02.44-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9350167/crash-2022-08-16_18.02.44-server.txt)
[crash-2022-08-16_18.06.24-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9350169/crash-2022-08-16_18.06.24-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by quickgk** [comment]
### Possible requirements to reproduce this crash:
- Player log out of the server directly after falling asleep
- When the player quits, the number of players who are sleeping has not reached the number of people who can skip the night.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
