### ISSUE TITLE
Beryllium Fluoride can not be produced for the LFTR

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#11031]
### Your GTNH Discord Username

Lord_Anarack#2705

### Your Pack Version

Dev 25

### Your Server

SP

### Your Expectation

I expected to be able to produce Beryllium Fluoride in the dehydrator

### The Reality

Instead the recipe that creates a dust of Ammonia Tetrafluorberyllate is ran, this dust is useless and causes the LFTR fuel chain to break. 

### Your Proposal

Add a non conflicting circuit to the useless recipe or remove it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Exelion42** [comment]
I also ran into this problem. The dehydrator keeps using the default recepie (the one without a circuit) and produces berillium hydroxide dust, no matter how you configure it. I also guess the next step in the chain will have the same problem, bescause there is also a dust recepie with no circuit to deconflict.
