### ISSUE TITLE
Digester do not work properly.

### ISSUE THREAD

**Issue by SSWZDDTI** [GTNewHorizons/GT-New-Horizons-Modpack#11032]
### Your Pack Version

2124-25-pre

### Your Server

SP

### Your Expectation

Digester get crushed monazite and nitric acid, work for a few second then output muddy monazite rare earth solution.

### The Reality

The Digester works for 2 seconds then acts like power insufficient while there is enough power in energy hatch, also it won't trigger safe mode of machine controller cover means it won't shutdown automatically even if safe mode is on.

### Your Proposal

Fix the issue

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
did you forget the muffler?

**Comment by isadora-6th** [comment]
Happened to me yesterday. I guess new message for "not outputting pollution" should be in game.
