### ISSUE TITLE
Some AE text with new colors unreadable

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#11038]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-27-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

-

### The Reality

Specifically that is in the AE crafting GUI.

![image](https://user-images.githubusercontent.com/40274384/184986815-f6d92206-fd8b-43b7-980a-9fe62c990b84.png)

I guess my contrast or eyes are terrible.

This is without any texturepack.

### Your Proposal

change it back.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
If I'm not mistaken this is some kind of ME crafting's GUI, not NEI.

**Comment by chochem** [comment]
oh sorry. why did I write that.

**Comment by chochem** [comment]
this also happens in the questbook but not usually, maybe just a few items:
![image](https://user-images.githubusercontent.com/40274384/186006899-bb2a5cdf-bfa0-4c11-8ff8-555a1f1b669c.png)

**Comment by Connor-Colenso** [comment]
I thought this got fixed already?

**Comment by chochem** [comment]
maybe I havent updated the right mod? where would that be?
