### ISSUE TITLE
T2 fusion Titanium Plasma( Fluorine+ Aluminium) not working properly

### ISSUE THREAD

**Issue by alex7500** [GTNewHorizons/GT-New-Horizons-Modpack#11030]
### Your GTNH Discord Username

alex75049#6423

### Your Pack Version

2.1.2.0-1.7.10

### Your Server

tested SP + ProsperCraft

### Your Expectation

Tryed to fuse Titanium Plasma in T2 fusion reactor. Both tests (PC server + SP) were made in a garden dimension. Fusion starts and power is being deducted properly.
(ISSUE) While the Titanium plasma (Fluorine+ aluminium) is active, power in fusion controller only decreases (the controller doesn't get extra power) During the fusion, power is STILL being drained from powersource (like normal) but amount drained is not added to internal buffer of the T2 fusion. After internal buffer colapses and recype stops, recrahing of the T2 internal buffer resumes correctly. ( for charging porposes, disconecting the power supply or conecting it during fusion doesn't modofy power draining speed). Considered isualated issue ( Molten tungsten that fuses under the same conditions works properly)

### The Reality

Despite power pasing through the wire during titanium plasma fusion, no power is being added to the internal fusion buffer. It is impossible to stop the recype from colapsing after the buffer emptyes, and impossible to fill the buffer during titanium plasma fusion

### Your Proposal

check that power being drained during titanium plasma fusion to be added properly to the internal T2 fusion buffer

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1181
