### ISSUE TITLE
LogisticsPipes changedetection cause stackoverflow

### ISSUE THREAD

**Issue by albus12138** [GTNewHorizons/GT-New-Horizons-Modpack#11041]
### Your GTNH Discord Username

r4phael#8493

### Your Pack Version

2.1.2.3qf

### Your Server

private server & SP

### Type of Server

Don't know

### Your Actions

Convert node with many kind of aspects (made by bee) to energized node, crash after covertation start a few seconds.

8.17 Edit: Node manipulator maybe don't have this problem. (not sure, just can't reproduce crash yet)

8.18 Edit: The node didn't crash after moved by "Node in a Jar". 

### Crash Report

https://pastebin.com/MY2xVJ5n

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by nhwhirlwind** [comment]
Same crash happened here. I'm using a Node Stabilizer, the node is moved by "Advanced Node Jarring", also tried move using Teleposer from blood magic, similar crash.

I'm on version 2.1.2.4-28-pre

Crash Report:
https://pastebin.com/8ULEwm23

**Comment by GodlyIdea** [comment]
Bug also occurs in version 2.2.3.

**Comment by BritishCynic** [comment]
Closing as this is an old crash report; if this crash still occurs on 2.3.0+, please comment to reopen.
