### ISSUE TITLE
Crashing on world load

### ISSUE THREAD

**Issue by draaac** [GTNewHorizons/GT-New-Horizons-Modpack#11044]
### Your GTNH Discord Username

Drac#3479

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Loaded world, in addition I have tried to load backups and have had the same crash for the most recent 2 backups. I had loaded these backups in the past and had no issue with them, so I assume something has gone wrong with the files.

### Crash Report

[crash-2022-08-14_11.21.16-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9357706/crash-2022-08-14_11.21.16-client.txt)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9357707/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by robbertapir** [comment]
I had the same issue and upgrading to 2.1.2.3qf fixed it.

**Comment by chochem** [comment]
Same as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8892. Gonna close this, We can reopen one of the two if it happens on a newer version
