### ISSUE TITLE
Incorrect NEI values for Railcraft Fluid Tanks

### ISSUE THREAD

**Issue by CuencaGuy** [GTNewHorizons/GT-New-Horizons-Modpack#11040]
### Your GTNH Discord Username

Duke Duke

### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Titanium Railcraft tanks should provide 128 buckets per block according to NEI.

### The Reality

Titanium Railcraft tanks are actually providing 256 buckets per block. According to others in Discord, the value is wrong for every material beyond aluminium.

### Your Proposal

The stated NEI values provide plenty of storage for their cost. The code should be changed so that the Railcraft tank blocks provide the storage as they are listed in NEI.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by cubic-chariot** [comment]
I personally would prefer if the tooltip was updated to match the value in the code. [The values in the code](https://github.com/GTNewHorizons/Railcraft/blob/master/src/main/java/mods/railcraft/common/modules/ModuleAdvancedTanks.java) keep doubling with each tier (until iridium), mirroring the progression of super tanks.
