### ISSUE TITLE
Progression up until iron can be easily skipped

### ISSUE THREAD

**Issue by Blazing-Blast** [GTNewHorizons/GT-New-Horizons-Modpack#11054]
### Your GTNH Discord Username

Blazing Blast#9996

### Your Pack Version

2.1.2.3 in launcher, but 2.1.2.2 in loading screen

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I tried to mine iron gravel ore by dropping it on a torch, this shouldn't work because it skips a bunch of progression.
![image](https://user-images.githubusercontent.com/69185984/185219331-8f810d45-41fb-4d4e-a27c-68f8699fb7be.png)

### The Reality

The ore dropped  and gave me iron way before I was supposed to.
![image](https://user-images.githubusercontent.com/69185984/185219460-4229aabe-cccf-48fa-b179-4d814c7fb5f3.png)

### Your Proposal

have gravel ores not break when they land on non-full blocks and instead have it fall into place on top of said block

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
What are you really skipping here? iron isn't really gated by anything, some iron types are mining level 1. I guess if you have a smeltery as well you dont need a flint pick?

All sounds fine to me.
