### ISSUE TITLE
Crash when toggling fullscreen on a fresh installation

### ISSUE THREAD

**Issue by villevilli** [GTNewHorizons/GT-New-Horizons-Modpack#11050]
### Your GTNH Discord Username

villsukka#6680

### Your Pack Version

2.1.2.4-28-pre

### Your Server

Main Menu

### Your Actions

After loading into the modpack on a fresh installation and trying to toggle on full screen the game crashes and produces a crash report. After this however the main menu music still keeps on playing and log spam is still generated.

Modpack is installed in polymc.

### Crash Report

[crash-2022-08-17_19.23.41-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9364603/crash-2022-08-17_19.23.41-client.txt)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9364624/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Connor-Colenso** [comment]
Can anyone reproduce this? Seems serious if so.

**Comment by eigenraven** [comment]
The first error is `org.lwjgl.LWJGLException: Failed to set display mode (-2).`, -2 is DISP_ERROR_BADMODE on Windows so lwjgl tried to set an invalid resolution/refresh rate. Switching modes after loading works fine for me, so I think I'll blame a broken options.txt or video drivers here.

**Comment by villevilli** [comment]
> The first error is `org.lwjgl.LWJGLException: Failed to set display mode (-2).`, -2 is DISP_ERROR_BADMODE on Windows so lwjgl tried to set an invalid resolution/refresh rate. Switching modes after loading works fine for me, so I think I'll blame a broken options.txt or video drivers here.

The issue was not fixed by a driver update. However switching to another port on my gpu seems to have fixed the issue. Hopefully its just a random issue and not a permanent hardware problem.
