### ISSUE TITLE
The Multi Smelter outputs based on stack size, not actual input size

### ISSUE THREAD

**Issue by DotJason** [GTNewHorizons/GT-New-Horizons-Modpack#11053]
### Your GTNH Discord Username

DotJason#2491

### Your Pack Version

2.1.2.4-28-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

It seems like the issue only appears when the size of the stack that's being taken from is greater than the number of items that are smelted at once (i. e. if a stack of 64 or 33 items is inserted but only 32 are smelted at once).

### The Reality

The output appears to be based on the initial stack size and not on the actual amount that's being processed, for example, with Nichrome Coils:
64 Iron Dust -> 32 is being smelted -> the output is 64 Iron Ingots (should be 32).
33 Iron Dust -> 32 is being smelted -> the output is 33 Iron Ingots (should also be 32).

### Your Proposal

Make the Multi Smelter output the proper amount of items.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment]
Oops 🙃
I'll fix this after work and clean up the smelter logic since as Glease said it is a bit weird now.
