### ISSUE TITLE
sodium fluoride liquid can not be produced

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#11055]
### Your GTNH Discord Username

Lord_Anarack#2705

### Your Pack Version

dev 28

### Your Server

SP

### Your Expectation

I expected to be able to make sodium fluoride liquid in a HV fluid heater per NEI. breaking part of the LFTR fuel chain.

### The Reality

The recipe does not run.

### Your Proposal

Fix the broken recipe or move it to the fluid extractor?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AlbertoPirillo** [comment]
Same behaviour here...
How is this not fixed after almost a month? It completely breaks the LFTR

**Comment by AlbertoPirillo** [comment]
The issue appears to be fixed in 2.2.0.0-RC2. 
This can be closed.
