### ISSUE TITLE
Nuclear Control Panel - average values no longer showing

### ISSUE THREAD

**Issue by GTNHAfx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#11056]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.4dev28

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Nuclear control panel should show avg EU in / avg EU out, as it did before

### The Reality

After update from dev 18 to dev 28, the avg values no longer show.
Other operational data is working fine.

![image](https://user-images.githubusercontent.com/99402656/185370574-bedbf584-00cb-423e-9498-920d5bbbab30.png)

### Your Proposal

Please fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by S4mpsa** [comment]
Likely related to the wireless EU functionality of the LSC, unless the average data is properly shown on the GT scanner, as that is where the panel pulls the data from.

**Comment by GTNHAfx237v7** [comment]
No, the avg values are also not shown when using the GT scanner. Both values are indicated as 0.

**Comment by repo-alt** [comment]
So the bug is in LSC

**Comment by GTNHAfx237v7** [comment]
Still not fixed, just tested with 2.2.0.0 stable :(
