### ISSUE TITLE
Improve Rock Breaker NEI Obsidian Entry

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#11063]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.4-dev29

### Your Proposal

Rock Breaker now needs a circuit set to 1 to make Obsidian. As there is only one inventory slot, the built-in circuit must be toggled. The NEI GUI only has the standard machine GUI with the yellow "G". I propose that the NEI GUI itself should show a 1 Circuit in the place of that "G" to properly instruct the player on the correct toggle setting.

### Your Goal

To ensure that NEI is accurate when players new to these changes check NEI for how to make Obsidian

### Your Vision

To ensure that NEI is kept accurate.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by tommmmmmmmm** [comment]
i'd even mark this as a bug, i lost 10 minuts trying to find out why my rock breaker wasn't making obsidian anymore, was going to make a ticked about it and found this
