### ISSUE TITLE
Fluid storage bus GUI issues

### ISSUE THREAD

**Issue by GTNHAfx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#11067]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.1.2.4dev28

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Configure the GUI of a fluid storage bus similar to that of an AE storage bus (shift-click with actual item in inventory or drag-click ghost item from NEI)

### The Reality

Shift-click with actual item (e.g. flask) works fine.

Drag-click from NEI bookmark does not work - it looks like the ghost item just disappears after clicking

Left-click with actual item (e.g. flask) on a slot will set it correctly, however you cannot put the item back into your inventory (neither left nor right click). Also you cannot drop the item by clicking it outside of the GUI. You need to press ESC to leave the GUI which drops the item on the ground.

### Your Proposal

Fix please ;)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
seems like a nei update breaks this

**Comment by GlodBlock** [comment]
well this pr breaks the fluid storage bus clicking https://github.com/GTNewHorizons/NotEnoughItems/pull/271 it is so big ...
