### ISSUE TITLE
Refactor integated circuit slot handling in a generic manner, allowing to be easily used in buses/controllers

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#11065]
### Your GTNH Discord Username

repolainen#0483

### Your Pack Version

GTNH-1.7.10-2.1.2.4-18-pre

### Your Proposal

I copypasted some integrated circuit slot functionality in https://github.com/GTNewHorizons/GT5-Unofficial/pull/1271, but it should be refactored to reduce code duplication, allowing to reuse GUI callbacks, etc.

### Your Goal

simplicity

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
In case you missed that, there is a `Create a Reminder` type of issue that have less useless fields.

**Comment by repo-alt** [comment]
Does it? I used before and I think it also required to fill some redundand stuff, maybe I remember wrong though.
