### ISSUE TITLE
DNA Dye cannot be made in MB Mixer

### ISSUE THREAD

**Issue by albertopirillo** [GTNewHorizons/GT-New-Horizons-Modpack#11066]
### Your GTNH Discord Username

AlbyNexus#4160

### Your Pack Version

2.1.2.3qf

### Your Server

Private 

### Type of Server

Vanilla Forge

### Your Expectation

~Molten Blaze should be able to enter in an Input Hatch of the Industrial Mixing Machine, since some recipes like DNA Dye requires it.~ DNA Dye can be made in both the SB and the MB Mixer.

### The Reality

~Molten Blaze does not enter in the Input Hatch, and I've tried different setups.~
DNA Dye can only be made in the SB Mixer.

### Your Proposal

Add the recipe to the MB Mixer.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AlbertoPirillo** [comment]
I've just realized that, according to NEI, DNA Dye can be made only in the SB Mixer.
Thus, Molten Blaze is not entering as no recipe that uses it exists.

**Comment by Dream-Master** [comment]
we can add this to gt++ maybe. Not sure if the MB map not take SM recipes

**Comment by miozune** [comment]
We need to move MT recipes into code to fix this issue. I'd like to work on the migration but it will introduce new bugs in high possibility so have not worked on it yet.
