### ISSUE TITLE
Quest requires BW Sodium Nitrate which cannot be made

### ISSUE THREAD

**Issue by AlbertoPirillo** [GTNewHorizons/GT-New-Horizons-Modpack#11068]
### Your GTNH Discord Username

AlbyNexus#4160

### Your Pack Version

2.1.2.3qf

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

The quest "Sodium Nitrate" of the IV tab requires to retrieve Sodium Nitrate Dust. 
The expectation is that both BW and GT++ Sodium Nitrate Dust will be accepted.

### The Reality

Only BW Sodium Nitrate Dust is accepted, which cannot be produced in any way, as all recipes give out GT++ Sodium Nitrate Dust.

![image](https://user-images.githubusercontent.com/79864956/185619967-0c0b7deb-63a5-4044-bc66-68203961fca4.png)

### Your Proposal

Fix the quest

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/10133
