### ISSUE TITLE
Puzzle game kicks from the server

### ISSUE THREAD

**Issue by Salio24** [GTNewHorizons/GT-New-Horizons-Modpack#11061]
### Your GTNH Discord Username

Salio♿#5442

### Your Pack Version

2.1.2.4 29-pre

### Your Server

Zeta

### Type of Server

Don't know

### Your Actions

![image](https://user-images.githubusercontent.com/62927095/185471671-adecf91f-2950-4070-8ca7-a6cb6d219a82.png)
Right clicking on puzzle minesweeper grid block causes an internal server error, and kicking from server.

### Crash Report

Internal server error

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@Salio24 logs please 
@TimeConqueror any idea why this happen ?

**Comment by Salio24** [comment]
> @Salio24 logs please @TimeConqueror any idea why this happen ?

I don't have any logs, it just kicks me from the server. No clue why this happened.

**Comment by vlaetansky** [comment]
I did encounter this error, it happens when you switch to a different level, will look into it.

**Comment by Dream-Master** [comment]
> > @Salio24 logs please @TimeConqueror any idea why this happen ?
> 
> I don't have any logs, it just kicks me from the server. No clue why this happened.

you have a fml log

**Comment by vlaetansky** [comment]
There will be no logs on client side most likely since it is a NPE on server side.
