### ISSUE TITLE
Rename "Bentonite" (the ore block) to "Bentonite Ore"

### ISSUE THREAD

**Issue by DotJason** [GTNewHorizons/GT-New-Horizons-Modpack#11071]
### Your GTNH Discord Username

DotJason#2491

### Your Pack Version

2.1.2.4-29-pre

### Your Proposal

Rename "Bentonite" (the ore block) to "Bentonite Ore".

### Your Goal

Bentonite is (at least to my knowledge) the only ore block that does not follow the general naming scheme and does not contain "Ore" in its name.

### Your Vision

It's cool and good when naming is consistent

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
its not the only on without 'ore', no. For example Kaolinite, Pitchblende, Talc, all the 'sands', the infused stones, etc.

This looks very deliberate. It just defaults to 'ore' outside of a certain list.
