### ISSUE TITLE
Level Emitters are not working correctly

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#11075]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Here is a specific example:

![image](https://user-images.githubusercontent.com/40274384/185714095-833c2bf1-a2cf-4ccf-8b1c-7fa254989ac6.png)
![image](https://user-images.githubusercontent.com/40274384/185714157-0c72ff90-4d30-439d-a761-e56ef6c29727.png)
![image](https://user-images.githubusercontent.com/40274384/185714141-335b6413-aa76-46f1-a790-bce3296903f8.png)

This worked fine in the past and I expect the light to be off. Instead:

### The Reality

![image](https://user-images.githubusercontent.com/40274384/185714235-c188a4e9-558b-431c-afc6-1dab9a618729.png)

and this is not just visual, it is in fact on.

I have double check channels and power, both are fine and have plenty to spare. this is on my main net, same as the storage.

But it is somewhat inconsistent. It only happens for some of my level emitters, not all. And they seems to turn on on game start but if I redo it or interact with them they turn off.
Multiple other people on discord reported problems too.

I am not sure how long this has been going on, I don't use a lot of level emitters.

### Your Proposal

Make sure level emitters work correctly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by cpreh** [comment]
I'm experiencing the same problem, both in 2.1.2.4_18pre and 2.1.2.4_29pre. Level emitters consistently break after a server restart, though not all of them. They only fix themselves once I update the item count they are referring to manually.
