### ISSUE TITLE
Recipe conflict for LiCl + potash electrolysis

### ISSUE THREAD

**Issue by MisterTGithub** [GTNewHorizons/GT-New-Horizons-Modpack#11085]
### Your GTNH Discord Username

MisterT#8428

### Your Pack Version

2.1.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to electrolyze 16 LiCl, 10 potash dust, and 2 buckets of hotspring water into lithium dusts and ashes in MV electrolyzer connected to annealed copper 2x cable and 2 MV steam turbines

### The Reality

3 potash was consumed to make 2 potassium and 1000 L of oxygen. Swapping the 2x annealed copper cable into a 1x annealed copper cable caused the recipe to work properly. 

### Your Proposal

When connected to cables capable of over 1 amp, make electrolyzer use the right recipe instead of just taking the potash. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
probably wasnt the cable but the order you put the items in
