### ISSUE TITLE
Sky Stone Chests can't be moved with dollys

### ISSUE THREAD

**Issue by TheBlizWiz** [GTNewHorizons/GT-New-Horizons-Modpack#11086]
### Your GTNH Discord Username

TheBlizWiz#6524

### Your Pack Version

2.1.2.0-RC1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Move Sky Stone Chests like normal chests using dollys

### The Reality

Dolly does nothing and opens the chest instead

### Your Proposal

Allow dollys to pick up and move Sky Stone Chests

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
need to be implemented here https://github.com/GTNewHorizons/Jabba/blob/master/src/main/java/mcp/mobius/betterbarrels/common/items/dolly/ItemBarrelMover.java#L54
and here https://github.com/GTNewHorizons/Jabba/blob/master/src/main/java/mcp/mobius/betterbarrels/common/items/dolly/ItemBarrelMover.java#L227

**Comment by Dream-Master** [comment]
Example for Forestry Work tabel :https://github.com/GTNewHorizons/Jabba/commit/1f9909fa847edae8b27aecde40bd910835ef345a
