### ISSUE TITLE
Crash on looking recipes

### ISSUE THREAD

**Issue by rasenk1** [GTNewHorizons/GT-New-Horizons-Modpack#11089]
### Your GTNH Discord Username

rasenk#5133

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Trying to look into Crude oil recipes (button U) from pump inventory.

### Crash Report

https://paste.ubuntu.com/p/zYbVKdGftj/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
that link is not accessible.

**Comment by chochem** [comment]
there is no crude oil afaik but pressing use on any of the oils works fine for me.

**Comment by miozune** [comment]
@chochem You can sign in to see log

**Comment by chochem** [comment]
well its good if you can.

**Comment by miozune** [comment]
Your modpack version seems to be 2.1.2.4-27-pre, rather than 2.1.2.4-29-pre. Please reinstall the pack from Discord announcement.
