### ISSUE TITLE
Early wand recipes not showing in NEI (e.g. gold banded wooden wand)

### ISSUE THREAD

**Issue by knapaJ** [GTNewHorizons/GT-New-Horizons-Modpack#11094]
### Your GTNH Discord Username

niecze#3238

### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Type of Server

Don't know

### Your Expectation

Upon researching wand wand core (greatwood wand core) and wand caps (Iron wand caps, copper wand caps and Golden wand caps) Recipes for wands with those components should be visible in NEI (e.g. Gold banded wooden wand, Iron banded greatwood wand).

### The Reality

I researched
- greatwood wand core
- gold wand caps
- copper wand caps
- (no others are available for research -> "missing research")

Now i wanted to craft the Gold banded wooden wand (as per the quest in the quest book), but:
- it's not in NEI
- Could not find the recipe even by pressing right click (aka searching for usage of):
  - gold caps
  - impregnated stick
  - naga scale
  - aluminium screw

Finally i went into SP to fing out what is wrong, gave myself the _cheat sheet_ thaumonomicon and suddenly i can see the recipes for all wands simply by searching for the usages of a wand cap. _(And i got MASSIVE amounts of warp)_

So it seems that the recipes are there, BUT are hidden until some kind of trigger in the researches is hit, which seems is much further, than needed.

And just to clarify, after i found out, what the recipe is (and beat myself for not figuring it out sooner) i went back to the MP, still not seeing the recipe in NEI, but when i tried to craft the wand, it worked.

### Your Proposal

Change the triggers for revealing of thaumcraft wand recipes in NEI. (or idk how NEI works :(  )

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by knapaJ** [comment]
Just to add, we were able to reproduce the bug on the server.

Given how tedious the reproduction in SP is, I was the only one tho try it in SP from our group.

**Comment by miozune** [comment]
Fixed in dev by several commits on TCNEIAdditions
