### ISSUE TITLE
Crash when ExtremeExterminationChamber is removed.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#11099]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.2.4-29Pre

### Your Server

SP

### Type of Server

Single Player

### Your Actions

1. Place ExtremeExterminationChamber Controller
2. Remove this
3. Crash

### Crash Report

[crash-2022-08-22_20.56.20-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9394090/crash-2022-08-22_20.56.20-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by kuba6000** [comment]
Fixed in https://github.com/GTNewHorizons/KubaTech/pull/7
https://github.com/GTNewHorizons/KubaTech/releases/tag/0.2.2
