### ISSUE TITLE
The Ender MKIV cannot be upgraded with Travel

### ISSUE THREAD

**Issue by AlbertoPirillo** [GTNewHorizons/GT-New-Horizons-Modpack#11091]
### Your GTNH Discord Username

AlbyNexus#4160

### Your Pack Version

2.1.2.3qf

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

"The Ender MKIV" + "Ender Crystal" in Anvil should add "Travel" to the sword.
Note: everything works if "The Ender" or "The Ender MKII" are used instead of "The Ender MKIV"

### The Reality

Nothing happens, as shown below
![image](https://user-images.githubusercontent.com/79864956/185804824-c412df22-3002-46e0-b399-b27d8ac238f4.png)

### Your Proposal

Add the possibility of upgrading.
Also, where is The Ender MKIII? 🤔 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Quarri6343** [comment]
Works fine in 2.1.2.4-29-pre
![キャプチャ1590](https://user-images.githubusercontent.com/39122497/186574915-24d6c534-6d14-493e-8bc1-1f4cb0b5966d.PNG)

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/EnderIO/pull/66
