### ISSUE TITLE
Industrial Cutter, Arc Furnace, ABS (maybe more?) do not form anymore

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#11104]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.1.2.4-29-pre + some manual updates

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

It was working fine for a long time.

### The Reality

EDIT: also arc furnace and ABS!

The structure deformed. Breaking and replace the controller does not help.

It looks to me like it does not allow for an input hatch anymore. Ofc an input hatch is very much needed to use it.

![image](https://user-images.githubusercontent.com/40274384/185949835-7e8c16d2-e386-4586-9cfe-c23b016d2936.png)

### Your Proposal

allow input hatch again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
likely caused by https://github.com/GTNewHorizons/GTplusplus/commit/50ab243835c1686d0f9c15dc1b33d6c33393c3cf

**Comment by chochem** [comment]
arc furnace and ABS too. will need to check whats missing there.
maybe others too?

**Comment by chochem** [comment]
These are fixed by https://github.com/GTNewHorizons/GTplusplus/pull/294,
though there might be more.

**Comment by DianeXD** [comment]
Maybe check the Adv DT? I noticed someone said it doesn't work now.

**Comment by Glease** [comment]
@DianeXD adv dt should be "fixed" in that same pr as far as structure code goes. Not sure if it's functioning correctly though...

**Comment by chochem** [comment]
@DianeXD have you checked after this https://github.com/GTNewHorizons/GTplusplus/pull/294 or before?

**Comment by chochem** [comment]
I guess the question just got answered: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11116
