### ISSUE TITLE
Two Molten Dragonblood recipe

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#11101]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.2.4-29pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Recipe 'Molten Dragonblood' confirmed by NEI.

### The Reality

Two similar recipes existed
![2022-08-22_19 58 27](https://user-images.githubusercontent.com/40425798/185922993-04a1a063-a016-48d4-ba01-fa263518a695.png)
![2022-08-22_19 58 30](https://user-images.githubusercontent.com/40425798/185922996-5c949cf8-bdaf-4832-8ee0-3a0a0dd7efc4.png)
.

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
looks correct.

**Comment by DianeXD** [comment]
I guess one is infinity egg and the other is dragon egg

**Comment by POPlol333** [comment]
Absolutely, if you look closely the texture are different @yukieiji (+you can hover them with your mouse lol)

**Comment by yukieiji** [comment]
Oops, I was looking at it wrong.
