### ISSUE TITLE
Can't see Molten Transcendent Metal Capsule

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#11100]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.2.4-29Pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Recipe 'Molten Transcendent Metal' confirmed by NEI.

### The Reality

I couldn't see 'Molten Transcendent Metal Capsule' displayed in tab 'Fluid Canning Machine'.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Transcendent Metal is fixed presumably by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1347, but SpaceTime is still invisible
