### ISSUE TITLE
The climate upgrade from Gendustry effects to much to industrial apiary

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#11105]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.2.4-29

### Your Proposal

I tried to produce Salt comb from Salt bees.
I know this bee needs Warm temperature,and normal humidty.And my biome is simple Plain
which is normal,normal
so i add a temperature upgrade to rise up the temperature.
But just one upgrade make apiary from normal to hot!
just jump through the "warm" level.
There is no other ways to fix the temperature need except changing biomes

### Your Goal

Please add more Biome simulation upgrades,which suitable for all the Tem,Hum combinations
To make the bees can work in different apiaries
and that will not effect the whole column of block (y=0~>256 are all the same biome) 

### Your Vision

May there is a way for the beekeepers to live happily in GTNH world
and as an optional main rescourses gain methode

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Runakai1** [comment]
You can simply use jungle simulation and it will work. If not, breed your bees with proper attributes

**Comment by DianeXD** [comment]
It's about producing specialty

**Comment by chochem** [comment]
jungle+1 dryer does work though.

**Comment by KamenriderZO** [comment]
> jungle emulation +1 dryer does work though.
> 
> ![image](https://user-images.githubusercontent.com/40274384/186227821-7ae678d5-d04d-44e0-8822-fe99bf4bb968.png)

And it may be too strict to combine the upgrades each other with just 4 upgrade slots
For example your settings.
The automation upgrade and ignoble won't die upgrade can no more inserted because of limited slots
and even production upgrade and acceleration upgrade has been crafted together...

**Comment by Runakai1** [comment]
Closing this as there are workarounds and it doesn't need fixing. We have more than enough ways to deal with this
