### ISSUE TITLE
Superconductor tier colour

### ISSUE THREAD

**Issue by CharlieTuna8** [GTNewHorizons/GT-New-Horizons-Modpack#11112]
### Your GTNH Discord Username

Charlie Tuna#7949

### Your Pack Version

2.1.2.4-29-pre

### Your Proposal

Give superconductors the same colour as their tier.
Currently in tooltips MV is lightblue,  HV is a dark yellow ish or something, etc.
I'd also recommend to sync the tooltip colours to the coloured dots on energy hatches etc.

### Your Goal

Easier to determine what voltage something is because each tier has its own definitive colour.
Also visually nice :)

### Your Vision

Easier to determine what voltage something is because each tier has its own definitive colour.
Also visually nice :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by POPlol333** [comment]
Actually to change this we would just have to change the RGB code the sc base and the sc material itself, will discuss a bit with others about that

**Comment by Connor-Colenso** [comment]
I would like this and have thought about it before but it's not as easy as it looks to implement.
