### ISSUE TITLE
Add Circuit Scroll and Item Count Scroll to Fluid Pattern Terminals

### ISSUE THREAD

**Issue by BlueWeabo** [GTNewHorizons/GT-New-Horizons-Modpack#11118]
### Your GTNH Discord Username

BlueWeabo#7517

### Your Pack Version

2.1.2.4-28-pre

### Your Proposal

Add the functionality from the normal AE2 pattern terminals like circuit scrolling(changes the type of circuit, ZPM magneto to ZPM Quantum) and count increase/decrease with scroll wheel.

### Your Goal

Make the AE2FC terminals have some of the same functionality.

### Your Vision

It would add to QoL.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by PolkageistHS** [comment]
Also the crafting preview screen in the ae2fc terminals doesn't allow you to bookmark an item or look it up in NEI.  The regular terminals do though. 

This screen.  
![image](https://user-images.githubusercontent.com/9247381/186253136-f7a080b5-14cc-4d4c-bf01-16ddfcdf4a68.png)
