### ISSUE TITLE
Nerf power generation of lighting rod 

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#11115]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.1.2.4 20 pre

### Your Proposal

ONE Lighting rod paired with a battery ( LAPO / PSS ) can basically skip all power gen until ZPM or later, (you can just double up on the rods to make enough power tbh) , only caveat is constant rain (EIO / Forestry, EIO method has nearly 0 cost ,just not very automatable (OC-able) ) 
The setup of this trick is to pull as much amps from the rods as fast as possible. 2 (ev) power distributors, upvolted into 16A iv each with 2 iv 16A energy hatches into the battery will pull max amount of amps pre Luv (which is all the point to this), then it's just normal gameplay.
This allows you to skip every power gen if you stack enough of it, as it's only cost is the setup . 
This dwarves vac nukes (actually tested it, way better), as it's literally cheaper than spamming vac nukes or any mb power gen option 

### Your Goal

Tbh I think the entire EV - Luv (fusion) power gen options need to be looked at, the reason everyone use lighting rod is just because of the ease and low scaling cost
mb power gen have such a high scaling cost , that only the argument of "efficiency" will never make people wanting to scale up for mb power gen, esp because of the exponentially increasing voltage tiers, you'll never use a sb gen for more than 1 tiers (e.g. lv to hv), as mb gens at this tier or lower are basically either glorified 100 efficiency sbs or only 3-4x sbs, you'll never use it for more than 1-2 tiers as well... machines with very expensive setup cost and scaling off just because of how voltage tiers are designed is not very good game design, as it only rewards player that are willing to set it up with tedium
Sure you might get a power boost for 1 - 2 tiers, but with most ppl in the chinese community turning away from most other power gen options into this, I think current power gen options really doesnt give player much incentive to use apart from "I have to because it's the only option", there's neither fun or challenging to setup as well, unlike the later naqline or any complex processing line, only thing you do is spam and scale and pray.

### Your Vision

Make EV-Luv powergen actually diverse and fun. because most ppl that know this will choose this immediately.... any other options are viewed as 'not worth the trouble' or 'weak' compared to this
And this isn't just 'solved' by nerfing this , it's been this way for a looooooooooong time, sure there's LCE, ECE, LGS, etc etc, but it's still in the mindset of the spam and scale method, and doing so requires a boat load of resources and setup. Lighting rod is just so happens to be as strong (someone counted roughtly 13A iv?)  , but way cheaper to setup.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
better discuss in the existing ticket: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10462
