### ISSUE TITLE
Dangote Distillation Tower voids fluid

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11116]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.1.2.4-29-pre, with some manual updates (GT++ version 1.7.76)

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Put wood tar in input hatch and programmed circuit 1 in controller block, activate the machine, hope it to work properly.

### The Reality

The machine doesn't work unless I enable void excess. 

When it works, it voids fluid in the input hatch and outputs nothing. (both DTower and Distillery mode tested)

https://user-images.githubusercontent.com/85604068/186218792-379051ea-3cea-49c9-8973-ac3762dd423c.mp4

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
@Glease can you have a look at this? this sounds very much like its caused by the structure changes. like it does recognize the output hatches properly?

**Comment by ChromicRedBrick** [comment]
@Glease Now the machines runs, but void excess seems broken.
