### ISSUE TITLE
Presence of energized node causes unbearable flashing/screen aberrations

### ISSUE THREAD

**Issue by lor1113** [GTNewHorizons/GT-New-Horizons-Modpack#11121]
### Your GTNH Discord Username

Neuro#8416

### Your Pack Version

2.1.2.3qf

### Your Server

A personal server of mine, but this bug also occurs in SP

### Type of Server

Don't know

### Your Expectation

I expected to energize a node as normal and use the resulting centivis

### The Reality

Being within render distance of the node causes constant, unbearable screen flashes and tears. This sometimes takes a minute or two to start but once it starts it never stops. No obvious "starting condition" has been identified other than being within render distance of the node. Being outside of render distance of the node prevents this from occuring.

Video of said screen flashes:
https://user-images.githubusercontent.com/15572735/186266755-c8fc4757-8d87-499d-8ed5-9aec2a6ccf8b.mp4

Note that this video was taken on SP but I get it on my personal server as well. Additionally, I have tested on a friends laptop and he does not get it on SP or on my server, so it is unlikely to be server issue.

### Your Proposal

I propose that, uhhh, this gets fixed so it does not happen?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lor1113** [comment]
I have asked multiple times on the discord about this and have recieved many suggestions, but none of them have worked.

I have already:
Updated Nvidia drivers
Updated AMD drivers
Run GTNH on my GPU (3060 laptop)
Run GTNH on my CPU + iGPU only (Ryzen 7 5800H)
Tried different java runtimes
Tried a variety of different java settings (by default I was using both the runtimes and settings from (https://gtnh.miraheze.org/wiki/Low_End_PCs)
Tried almost every possible combination of ingame graphics/video settings

I did not tick the "ask other people" because as far as I can tell, nobody else seems to have this problem. I asked multiple times on the discord and nobody responded saying they had a similar problem. This (https://www.reddit.com/r/feedthebeast/comments/oyjx0n/thaumcraft_4_screen_tearingflashing/) is the closest I can find to someone else having a similar problem, although the nature of the flashing is markedly different.

**Comment by Szajkop** [comment]
Im having the same issue.
https://discord.com/channels/181078474394566657/234936569360809996/1001768211399852087

If that matters im using optifine

**Comment by AlastorsGame** [comment]
Oh my guy this is easy, go into your tc4tweaks config folder and turn node rendering to 0.5

**Comment by AlastorsGame** [comment]
This is completely because nodes weren’t meant to be larger than very small for the most part, also it’s basically unfixable other than the tc4tweak thing I mentioned

**Comment by Szajkop** [comment]
> Oh my guy this is easy, go into your tc4tweaks config folder and turn node rendering to 0.5

Thanks for the suggestion. What other effects this change brings? Can it be set to that value by default in next updates?

**Comment by Alastors** [comment]
> > Oh my guy this is easy, go into your tc4tweaks config folder and turn node rendering to 0.5
> 
> 
> 
> Thanks for the suggestion. What other effects this change brings? Can it be set to that value by default in next updates?

It's a client specific thing, and most people who dont mess with giga nodes probably wouldn't like the change cause of hungry nodes

**Comment by Ethryan** [comment]
Hmm… Maybe some kind of size limit for nodes could be implemented. That should solve this better i think.

**Comment by Alastors** [comment]
> Hmm… Maybe some kind of size limit for nodes could be implemented. That should solve this better i think.

There already is, it's a soft cap, the only people this issue effects is people who make massive nodes, and as mentioned, there already is a fix for them, changing the rendering to 0.5.

There isn't a reason to nerf nodes like that given that people tend to just make 'em that large as a trophy of some sort or for insane TE crafting

**Comment by Godelboard** [comment]
On 2.2.0.0 and was experiencing this issue. Was on OpenJ9 and swapped to JRE8 and that made the issue go away. So I think it should be that.

Original idea to try this fix was found here: #4872

**Comment by Alastors** [comment]
My guy, this is a forever issue, you have to go into your config and change it

**Comment by Godelboard** [comment]
I did some additional testing and I'm 100% sure this is OpenJ9 related. Having _any sized_ energized node with OpenJ9 causes this issue.

Here is me in OpenJ9 with 5 cv terra node (25 base terra) and limitOversizedNodeRender set to 0.5. This node is smaller than any reasonable user would use for the most part, so the fact it occurs at such a small size is concerning.
![image](https://user-images.githubusercontent.com/6662420/196008451-766898e5-de74-442c-a856-ac1f96b4f96a.png)

Here's a 1095 cv terra node (1000000 base terra) and limitOversizedNodeRender at its default value of 1. Still same flickering (more visible when moving around). But clearly not occurring based on the node size, since it occurs at both sizes
![image](https://user-images.githubusercontent.com/6662420/196008635-b19c1b8c-c274-4f3e-b38a-01f6ab57b38f.png)

Anyways I don't know if there's a fix for the rendering in OpenJ9 that should/needs to be applied but users should be advised this is a potential side effect of using _alternate_ JVMs.

**Comment by Alastors** [comment]
This has been fixed for ages, closing

**Comment by Alastors** [comment]
Well fixed to the extent we can anyway, closing
