### ISSUE TITLE
AE2FC

### ISSUE THREAD

**Issue by NoriSilverrage** [GTNewHorizons/GT-New-Horizons-Modpack#11120]
### Your GTNH Discord Username

Nori Silverrage#7354

### Your Pack Version

2.1.2.4-29-pre

### Your Proposal

The new fluid cells should allow you to partition them to a specific fluid.

### Your Goal

It would be nice to be able to set each storage cell to a specific fluid so that if one runs out, it won't get overfilled by another.

### Your Vision

Better fluid storage mechanics.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GlodBlock** [comment]
use fluid container to set partition in cell workbench
![image](https://user-images.githubusercontent.com/60341015/186347283-523a272a-ed61-4c10-ad54-40a2d90c4d17.png)

**Comment by Connor-Colenso** [comment]
@GlodBlock if this is already possible please close this.
