### ISSUE TITLE
Sodium Potassium cannot be put into an IC2 Fluid cell 

### ISSUE THREAD

**Issue by Indyjunk** [GTNewHorizons/GT-New-Horizons-Modpack#11124]
### Your GTNH Discord Username

Indyjunk#1254

### Your Pack Version

2.1.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Sodium potassium is loaded into a fluid cell when clicking on the fluid in the mixer.

### The Reality

Nothing happens when you want to load it into a fluid cell.

### Your Proposal

Make it so that you can put Sodium potassium into a fluid cell so it can be easily moved. You can put it in a bucket.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
guess it is defined in the core mod and not in gt. Maybe we need to switch that

**Comment by TwoTailedFox** [comment]
You can use a Universal cell for this

**Comment by hallucinogender** [comment]
> You can use a Universal cell for this

That is a workaround, not a solution.

**Comment by TwoTailedFox** [comment]
By that definition, it is a workaround for a great many fluid cells not defined in GT5/GT++.
