### ISSUE TITLE
NEI labels MK1 fusion recipes as MK2

### ISSUE THREAD

**Issue by CharlieTuna8** [GTNewHorizons/GT-New-Horizons-Modpack#11136]
### Your GTNH Discord Username

Charlie Tuna#7949

### Your Pack Version

2.1.2.4-29-pre

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Fusion recipe with starting EU <160.000.000 be labeled as MK 1.

### The Reality

![image](https://user-images.githubusercontent.com/38141544/186943492-b67d0bae-793a-4c76-9c4d-8a46f688c78b.png)

(There are no MK 1 recipes, only 2, 3 and 4.)

### Your Proposal

Fiks

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1288
