### ISSUE TITLE
Lv conveyor belt outputs silicone rubber pulp when put in macerator

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#11134]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.1.2.3 QF

### Your Server

private server

### Type of Server

Thermos

### Your Expectation

mecerate Lv conveyor belt will not output silicone rubber pulp.

### The Reality

Lv conveyor belt outputs silicone rubber pulp when put in macerato
![QQ截图20220825214319](https://user-images.githubusercontent.com/49871378/186824364-39df842f-b4ed-44a0-a82d-4f51d0e10c3d.png)
r
![QQ截图20220825214341](https://user-images.githubusercontent.com/49871378/186824366-e77dce1c-d5f8-476e-a622-7ba6000b8c65.png)

### Your Proposal

let mecerator recipe always output the lowest quality rubber when mecerating tech components like Lv conveyor belt.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Didn't we fix this before https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5896 Are you really using 2123?

**Comment by Glease** [comment]
Indeed still a thing. The fix in https://github.com/GTNewHorizons/GT5-Unofficial/commit/8327be885e70cebeaa757443009a7cac9905e8a6 probably didn't take effect somehow.
