### ISSUE TITLE
Fluid processing pattern terminal merge same items enabled = crash

### ISSUE THREAD

**Issue by CharlieTuna8** [GTNewHorizons/GT-New-Horizons-Modpack#11138]
### Your GTNH Discord Username

Charlie Tuna#7949

### Your Pack Version

2.1.2.4-29-pre

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Actions

Press ? to put recipe in terminal.
![image](https://user-images.githubusercontent.com/38141544/186989937-2c67795a-4121-4576-b6e3-718c86f4ef42.png)

### Crash Report

![image](https://user-images.githubusercontent.com/38141544/186989986-9bbf4c0d-8895-4ef1-8e01-9f7dd88b5662.png)
If merge the same items is enabled, this always happens:
![image](https://user-images.githubusercontent.com/38141544/186990020-2d27c382-87eb-4a14-a805-d3d17929cc81.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by GlodBlock** [comment]
fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/89ca4b83134e005a2e85071c2f49b1768624913b
