### ISSUE TITLE
Primitive Blast Furnace Recipie Oversight with Iron Blocks

### ISSUE THREAD

**Issue by TheBlizWiz** [GTNewHorizons/GT-New-Horizons-Modpack#11148]
### Your GTNH Discord Username

TheBlizWiz#6524

### Your Pack Version

2.1.2.0-RC1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

5 Iron Ingots + 1 Block of Coal Coke --> 5 Steel Ingots and 1 Pile of Ash
10 Iron Ingots + 2 Block of Coal Coke --> 10 Steel Ingots and 2 Piles of Ash

1 Block of Iron + 18 Coal Coke Pieces --> 1 Block of Steel and 18 small piles of ash (Side note, would be a lot better to make 2 big piles of ash)

1 Block of Iron + 2 Blocks of Coal Coke --> 1 Block of Steel and 18 small ash

### The Reality

1 Block of Iron + 2 Blocks of Coal Coke / Charcoal / Regular Coal ---> Nothing, it's not a recipie

### Your Proposal

Add 1 Block of Iron + 2 Blocks of Coal Coke / Charcoal / Regular Coal ---> 1 Block of Steel and 2 Big piles of ash

It might also be worth considering 1 Block of Iron + fuel --> 10 steel ingots since that would make it equivalent to the original recipe. You'd get rewarded by compressing it first by only doing one smelting operation. If the above is used, you would cook faster but it would not be as efficient.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Quarri6343** [comment]
2 Blocks of Coal Coke worth 20 Cokes in fuel value
9 irons + 20 cokes -> 9 steels should not be allowed in my opinion.

Also, this will cause game balance issue since PBF cannot be automated.
In its current state you can only process 60 iron ingots at a time without manual interaction.
(5 Iron Ingots + 1 Block of Coal Coke)
However, with the Iron Block recipe, you can process 9*32 = 288 iron ingots at a time
This will make afking op

**Comment by TheBlizWiz** [comment]
You can already process 125 ingots at a time though. You have 2 input slots for ingots.

**Comment by Quarri6343** [comment]
oh I have totally forgot that
thanks
so you can process 9*64=576 ingots at a time with the new recipe

**Comment by TheBlizWiz** [comment]
I still think that's a non-issue since 1 Block of Steel would need 2 coal blocks, so if you were to throw in 2 stacks of Iron Blocks, you would have to refill the BBF with fuel 4 times. If you threw in 2 stacks of coal blocks, you could smelt an entire stack of iron blocks. It's either check back on the BBF more often or get less benefit out of it. 

If that still seems to OP for AFKing, (which I think is a dumb argument since the point of a convenience like this is to turn it on and then go do other tasks while you wait) you could always just add a 1.5x time penalty or something.
