### ISSUE TITLE
Being able to monitor IC Redstone chips

### ISSUE THREAD

**Issue by NikitaGamer64** [GTNewHorizons/GT-New-Horizons-Modpack#11144]
### Your GTNH Discord Username

Никита#8621

### Your Pack Version

2.1.2.4-29-pre

### Your Proposal

After you make a IC chip, right-clicking on it will give you nothing. I would like to be able to look on the IC chip like I would open an IC workbench or blueprint inventory, and watch the redstone signals that activate and inactivate on it in real time.
P.S. I don’t know if the current issue was already posted or solved before, so I posted it anyway.
![image](https://user-images.githubusercontent.com/36325411/187034857-45834188-e4ea-4cb8-a6c7-874ad32eb7d6.png)

### Your Goal

I once watched a man who has a Minecraft YouTube playlist. He claimed that he couldn’t monitor the behavior of his IC chip in his redstone scheme. Because of that, correcting some issues or looking for the problems was too hard and time-wasting for him. Even if that was a different modpack, the same thing is in GT:NH.

### Your Vision

Being able to right-click the chip itself that participates in the redstone route and look at its scheme to watch an important part that would interest the creator would definitely help in fixing some issues that would occur if something went or was done wrong. The information about the IC chip scheme would also be useful in OpenComputers, for anyone that wanted computerize it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by NikitaGamer64** [comment]
I am surprised no one noticed my issue.

**Comment by repo-alt** [comment]
wdym no one noticed. You basically asked if someone wants to implement some really nontrivial and rather niche thing. Nobody volunteered (surprize).

**Comment by NikitaGamer64** [comment]
> wdym no one noticed. You basically asked if somebody wants to implement some really nontrivial and rather niche thing. Nobody volunteered (surprize).

But this is rather important, at least because you wouldn’t have to take the blueprint back on the table to watch it. It would be much more simple with just a single right-click on the circuit.
