### ISSUE TITLE
Void excess doesn't work on Dangote

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11141]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.1.2.4-29-pre, with some manual updates (GT++ version 1.7.80-pre)

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Enable void excess to make Dangote ignore the output hatch and continue running.

### The Reality

When the output hatch is full, Dangote will stop even if void excess is enabled.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11116#issuecomment-1229082888

Video here: https://youtu.be/lHbpYgUm7X8

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
In addition, Dangote's tooltip seems not correct. In DTower Mode its parrellel is 4 x Tier both in T1&T2.
![image](https://user-images.githubusercontent.com/85604068/187026467-69c39b07-9877-431e-9e79-9a4b866c9477.png)

**Comment by Glease** [comment]
T2 is probably never used in real game.. The upgrade chip never had a recipe until very recent times. I'm honestly not sure what to do with it. I'll restore it to what tooltip says, state all hidden effects and leave the actual balancing decision to much later.

**Comment by ChromicRedBrick** [comment]
@Glease In Distillery Mode, T2 can give 2x parrellel compared with T1, that is, in T1 its parrellel is 4 x Tier, and in T2 it is 8 x Tier. But this does not apply in DTower mode.

**Comment by Glease** [comment]
Yes, as tooltip states the it has different parallel based on operation mode. DT mode has 4 parallel regardless of InputTier in T1 and 12 in T2. Distillery has Tier * 4 * InputTier. It also has a 15% energy discount in distillery mode which is not mentioned in tooltip.

**Comment by ChromicRedBrick** [comment]
Maybe remove the recipe of upgrade chip and give Dangote 4 \* Tier parallel in DTower Mode and 8 \* Tier in Distillery Mode is a better option. That recipe does not make any sense.

**Comment by Glease** [comment]
I'd like to also mute the freaking thing. Why would anyone add a 5 sec sound to something whose work cycle is usually less than 1 sec is beyond me.
