### ISSUE TITLE
allow waila to display what covers a GT tile has independantly from the side looked at

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#11142]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.4-dev29

### Your Proposal

Allow waila to display what covers a GT tile has independantly from the side looked at.

### Your Goal

This is not very practical
![2022-08-27_12 42 12](https://user-images.githubusercontent.com/12850933/187026757-9f6c03a7-e40b-4b6c-9019-b213b19d90cb.png)
![2022-08-27_12 45 54](https://user-images.githubusercontent.com/12850933/187026772-2e2a7dd9-dcf3-4d69-bf6b-e092f9f6e624.png)

How do i know what cover i have if something is placed in front of the side having the cover other than digging my walls to access another side and open the gui?

### Your Vision

Add some QoL to the pack, which is good.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by hallucinogender** [comment]
This seems to be a wise suggestion. A sensible implementation in the information display would probably be something like this (most information omitted for brevity):

Cover (EAST): Conveyor Module (LV)
Cover (SOUTH): Pump Module (LV)
etc.

Something like the above could replace the current cover display, omitting any sides that lack covers.
