### ISSUE TITLE
Some crushed ores retrieved by Miner lacking item name

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#11153]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.4-dev29

### Your Server

SP

### Your Expectation

When using a Miner, all crushed ores should have the correct name i.e. "Crushed Gold Ore", "Crushed Bismuth Ore", etc.

### The Reality

A small minority of crushed ores (so far, only seen it happen to Gold and Bismuth crushed ores) retrieved by the miner show "crushed" as the item's name, the same name as the item filters show when you select a filter. These unnamed crushed ores are not being recognised by the item filters, and because they take up a space in the pipe, end up causing blockages until manually extracted. 

### Your Proposal

Ensure that all crushed ores extracted by the Miner have correct names to prevent this issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TwoTailedFox** [comment]
![crushed](https://user-images.githubusercontent.com/13187606/190425621-acd0de18-5a0f-43ac-aa0e-9f5fff3ea426.png)

Seeing this in Overworld, Twilight Forest and The Nether.
