### ISSUE TITLE
Nitrogen Dioxide chemical recipe unbalanced

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11158]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I think it is not intended.

### The Reality

9000L O + 9000L NO == 18000L NO2

9000L NO == 9000L N + 9000L O

18000L NO2 == 18000L N + 36000L O

![image](https://user-images.githubusercontent.com/85604068/187181177-dbf8e82c-56f8-444a-8dff-171f2ff5057e.png)

**Because of this unbalanced recipe, one can produce nitric acid from sugar, steps are as follows:**

1. 24 Sugar + 6000L HNO3 == 3000L H2C2O4 + 6000L NO (Vanadium Pentoxide does not get consumed)
![image](https://user-images.githubusercontent.com/85604068/187185123-1c7577c1-9c9e-44e7-a8c9-1278181e1317.png)

2. 9000L O + 9000L NO == 18000L NO2
![image](https://user-images.githubusercontent.com/85604068/187185666-5dee3b5f-e53a-426b-93d7-01502ff050ab.png)

3. 1000L O + 2000L NO2 + 1000L H2O == 2000L HNO3
![image](https://user-images.githubusercontent.com/85604068/187185820-f40dfc2e-d6d3-49ef-b861-3051ecc90d22.png)

4. 1000L H2C2O4 == 2 C + 4000L O + 2000L H
![image](https://user-images.githubusercontent.com/85604068/187186052-b120c90c-b6f8-4e1e-8680-d563de71ad8e.png)

Overall formula : **24 Sugar + 6000L H2O == 6000L HNO3 + 6 C + 6000L H**

With an industrial greenhouse, It is way more faster than get HNO3 from NH3 in LCR in IV Tier.

### Your Proposal

Balance the recipes, make 9000L NO + 9000L O == 9000L NO2.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
Is this caused by the recent changes to general chemical balance or was it in game for a long time? I don't remember this recipe
![image](https://user-images.githubusercontent.com/81298696/187190037-56f8d3ea-9dd5-4656-898b-933fd76d82b4.png)
I thought it didn't increase in volume after combining

**Comment by ChromicRedBrick** [comment]
The recipe with programmed circuit 1 is balanced, but circuit 9 does not.
![image](https://user-images.githubusercontent.com/85604068/187190720-52868441-e2e9-46f0-b966-91dd8f48b96f.png)

**Comment by Pxx500** [comment]
Probably an error when the multiplied recipe was created
