### ISSUE TITLE
Allow locking super tank with NEI ghost items

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11167]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.1.2.4-29-pre

### Your Proposal

Super tanks can be locked with NEI ghost items.

### Your Goal

QoL

### Your Vision

QoL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Quarri6343** [comment]
Ghost item Locking is a good idea
but I don't like the first idea
Imagine you placed a distillation tower and want to lock tanks to chemical products
If you can lock the tank with auto inputted fluid, you no longer have to open GUI and set fluid for 12 times

**Comment by ChromicRedBrick** [comment]
I agree with you after rethinking it.
