### ISSUE TITLE
One of two lazurite electrolysis recipes is missing a circuit

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#11164]
### Your GTNH Discord Username

querns#3785

### Your Pack Version

2.1.2.4-29pre

### Your Server

n/a

### Type of Server

Single Player

### Your Expectation

I am attempting to use the lazurite electrolysis recipe to recover alumina from lazurite dust. There are two recipes for electrolysis:

![image](https://user-images.githubusercontent.com/33518699/187315272-6c056da4-7dbc-4cac-b3ef-fcc03f2b8422.png)

One uses a circuit, one does not. I expect that if I use circuit 1, I get the alumina yield.

### The Reality

Instead, I get the no-circuit recipe. I suspect this is dependent on the recipe map simply encountering the aluminium dust recipe first and would not be consistent between players or even between games.

![image](https://user-images.githubusercontent.com/33518699/187315382-7d011e07-3f5d-440e-9a2c-6118d43e0f28.png)

### Your Proposal

Make the no-circuit recipe for lazurite use circuit 2 instead of no circuit.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
oh need to check . Guess i need to disable the auto generated one.

**Comment by querns** [comment]
Does this mean that it should NEVER give pure aluminium dust? If so, these need to be fixed so they only have an alumina recipe:

Sodalite
Lazurite (for completion's sake)
Zeolite

These dusts have no circuit variant, but also yield pure aluminium dust:
Red Granite
Ruby (both real and fake)
Kyanite
Spodumeme
Jade
Kaolinite
Potassium Feldspar
Pyrope
Spessartine
Grossular
Almandine
Emerald
Bauxite

These dusts have an identical 1-circuit and no circuit recipe (yielding pure aluminium dust):
Cryolite

**Comment by Dream-Master** [comment]
with circuits are custom recipes without auto generated. Sure i can add two recipes but we need to add circuit 1 or 2 to make alu/si or alumina /sio2 as an example. Are you want this ?

**Comment by querns** [comment]
I'm not entirely sure what the pack direction is on aluminium. Should the player have the option to electrolyze ores and get pure aluminium dust, or should they always get alumina and be forced to process it?

If it's okay for the player to choose which they want, adding circuit 1 and 2 recipes is the way to go. If the player should only ever get alumina, the pure aluminium recipes should be removed.

**Comment by Dream-Master** [comment]
alumina is much cheaper and only possible early game. pure alu works later as well

**Comment by jakubceremanski** [comment]
I'm playing version 2.2.0.0 and in early MV tier the possibility to get alumina out of lazurite would be very helpful at this stage.

**Comment by Lithorn** [comment]
Can confirm this problem in 2.2.0.0. Just reached MV and the first thing I tried to do was get more alumina but kept getting aluminum dusts from Lazerite no matter what circuit is set.

**Comment by Sovereignty89** [comment]
![Zeolite](https://user-images.githubusercontent.com/6663736/204326164-2071cdaa-9451-45da-8bff-5ebdc005c0b9.png)

This recipe Zeolite to Alumina using circuit 1 doesn't work in version 2.2.3.0. It outputs 9 pure Aluminium. 
It also doesn't give Silicon Dioxide but Raw Silicon.

![Zeolite2](https://user-images.githubusercontent.com/6663736/204327223-d4e0073d-e27a-48e8-857f-62b11b72c993.png)

**Comment by BritishCynic** [comment]
This issue has been fixed.
