### ISSUE TITLE
LPF void protection broken

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#11162]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expected to void protection stop machine when result cannot be placed in putput busses/hatches

### The Reality

LPF(Large Processing Factory) in fluid extractor mode(havent tested other modes/machines) when void protection is enabled, stop melting fluids even when same fluid is in output hatch
like:
hv output hatch has 64 000L capacity
LPF did 1 tungstensteel extracting recipe and made ~2 000L
hatch has a place to fit 2 000L more
LPF refuses to start 

this bug makes LPF stop after each recipe an stay in resting for +-5 seconds

### Your Proposal

Fix 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
This should be fixed by https://github.com/GTNewHorizons/GTplusplus/pull/317
