### ISSUE TITLE
Allow reconfiguring programmed circuit while having screwdriver in IC2 tool box

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11165]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.1.2.4-29-pre

### Your Proposal

Allowing reconfiguring programmed circuit while having screwdriver in IC2 tool box in my inventory, so that I don't need to take out the screwdriver in the toolbox beforehand. 

It would be a QoL change.

### Your Goal

QoL

### Your Vision

QoL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miaowwwwww** [comment]
that‘s pretty convenient
