### ISSUE TITLE
The Ultimate GTNH inventory interface

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#11166]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Proposal

![unknown](https://user-images.githubusercontent.com/59776356/187385921-9c8d48d2-452f-42b2-8bff-87af8fabefbb.png)

It's a preliminary idea
but the idea is here
I believe the devs can make a more reasonable layout

### Your Goal

![image](https://user-images.githubusercontent.com/59776356/187384783-e39f70d8-87c7-4b9f-a110-b47e84f0184b.png)

### Your Vision

better quality of life
always have insufficient inventory slot when you build
especially if you working on your multi block the inventory fill with a bunch of different bus and hatch and casing and cables and Tool and AE item
the inventory expansion can unlock with magic or tech way 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ngar1** [comment]
May be to double the inventory of Advanture-Backpacks (extended versoin of it like Forestry  Backpacks) would help a lot.

**Comment by vovaksenov** [comment]
I am with boubou on this one. It seems like a cool idea at first, but not everyone is a fan of 2x2mm inventory slots. I would rather look into the possibility to expand already existing solutions, such as adding an upgrade to the TiCo belt for more toolbars (maybe have 3/4 instead of 2), increasing the sizes of backpacks (adding extra lines to adventure and extra columns to normal, etc) and so on.
I think the belt upgrade can efficiently address your specific concern, as you can dedicate one of the toolbars for your multiblock buses.

**Comment by Cata-bre** [comment]
> I would rather look into the possibility to expand already existing solutions, such as adding an upgraded version of the TiCo belt for more toolbars (maybe have 3/4 instead of 2), increasing the sizes of backpacks (adding extra lines to adventure and extra columns to normal, etc) and so on.

I too would like to see larger Adventure Backpacks. I use TiCo belt frequently when building and using GT tools; buffing that would help. I think it may be worth fixing the dupe bugs with the TiCo backpack. It is easy to access from the normal inventory screen (you simply click the tab).

A bit of a segue, but IO can think of some nice QoL changes for Adventure Backpack:

- Make it so the player can drink potions out of the tanks with the hose. I haven't tested to see if the hose allows the player to drink milk out of the tanks.
- Buff the tank size. Perhaps a higher tier Adventure Backpack with increased inventory also has increased tank sizes?
- Add a Quantum Adventure Backpack with one tank and one battery. The battery would add to the player's total EU storage.

**Comment by Eason134HK** [comment]
> I hope this is a joke.

I was a joke at the beginning until saw this

![image](https://user-images.githubusercontent.com/59776356/187745583-cb9fa4d6-5273-4b36-b97f-8704fe823d66.png)

it seems people agree the inventory is too small and want some expansion for it 
that's why I posted this idea here

**Comment by Dream-Master** [comment]
Ok the idea is nice but i guess its hard to realize because change core component break many shit

**Comment by Quarri6343** [comment]
Ok I made a mod prototype that solves this in a realistic way
The concept of the mod is that you can override your inventory screen to something else
If the development continues, You will be able to press E key to open your backpack, Tool Forge, wireless crafting terminal... 
 directly and switch between them without closing window.
Of course, If you like the traditional style, you can just press back button and your vanilla inventory will be back
The benefit of using it is that you don't have to worry about your gui scale or breaking mods compat while having theoretically infinite amounts of slots
This mod does not add any item or block or tileentity. Every transaction is completed sorely by player.

https://user-images.githubusercontent.com/39122497/190214799-67291690-3e55-4d10-a3ee-c083aeeb5803.mp4

idk if anyone want it so comments are welcome

**Comment by Alastors** [comment]
> Ok I made a mod prototype that solves this in a realistic way The concept of the mod is that you can override your inventory screen to something else If the development continues, You will be able to press E key to open your backpack, Tool Forge, wireless crafting terminal... directly and switch between them without closing window. Of course, If you like the traditional style, you can just press back button and your vanilla inventory will be back The benefit of using it is that you don't have to worry about your gui scale or breaking mods compat while having theoretically infinite amounts of slots This mod does not add any item or block or tileentity. Every transaction is completed sorely by player.
> 
>  8mb.video-6Gi-mitZaI1f.mp4 
> idk if anyone want it so comments are welcome

yeah that's pretty cool, ngl

**Comment by Alastors** [comment]
> ### Your GTNH Discord Username
> Eason1134HK#5098
> 
> ### Your Pack Version
> 2.1.2.0
> 
> ### Your Proposal
> ![unknown](https://user-images.githubusercontent.com/59776356/187385921-9c8d48d2-452f-42b2-8bff-87af8fabefbb.png)
> 
> It's a preliminary idea but the idea is here I believe the devs can make a more reasonable layout
> 
> ### Your Goal
> ![image](https://user-images.githubusercontent.com/59776356/187384783-e39f70d8-87c7-4b9f-a110-b47e84f0184b.png)
> 
> ### Your Vision
> better quality of life always have insufficient inventory slot when you build especially if you working on your multi block the inventory fill with a bunch of different bus and hatch and casing and cables and Tool and AE item the inventory expansion can unlock with magic or tech way
> 
> ### Final Checklist
> * [x]  I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying _I like this change please reconsider adding it_ will prompt us to investigate and reopen it once we confirm your report.
> * [x]  I understand this change request may not attract enough attention and thus not be implemented.
> * [x]  I understand this change request may be rejected due to other community members think it's inappropriate.
> * [x]  I believe this feature would make the pack better.

that is single handedly the ugliest inventory i've ever seen

**Comment by Ethryan** [comment]
Modded Factorio have a nicer inventory.
