### ISSUE TITLE
Energy Acceptors are laggy when supplied with EU

### ISSUE THREAD

**Issue by S4mpsa** [GTNewHorizons/GT-New-Horizons-Modpack#11161]
### Your GTNH Discord Username

Sampsa#2464

### Your Pack Version

2.1.2.4-28

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

Connecting energy acceptors to GT EU seems to force the network to recalculate the energy demand constantly. This is not the case without energy acceptors (Neutronium Energy Cell etc.)

![image](https://user-images.githubusercontent.com/69092953/187280326-f09e644e-9d60-4388-8c02-52f7774daa32.png)

### The Reality

In large networks, the constant recalculation of usage uses up a lot of tick time.

### Your Proposal

Make it less laggy to use EU for feeding AE networks.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11795
