### ISSUE TITLE
OC Buffer Changes config

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#11171]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.2.4-29-pre

### Your Proposal

Change Default value of OpenComputers config "bufferChanges": true -> false

### Your Goal

Im tired of changing it every time i update pack

### Your Vision

This change doesn't affect people who just use programs, and this setting is vital if you want to edit your code outside of game

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by asiekierka** [comment]
`bufferChanges` is an optimization made to avoid unnecessary I/O loads on the server side. However, its usefulness has been disputed even in the OC community - I would encourage doing benchmarks (on a variety of operating systems) to figure it out, it might be possible to cut it from mainline...

**Comment by boubou19** [comment]
almost 2 years had passed since i turned this off on the officials, and i never seen OC lag in warmroast so it is safe to do this change i think.
