### ISSUE TITLE
QoL change to Gigantic volumetric flask recipe

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11178]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

2124-25

### Your Proposal

The gigantic volumetric flask uses 8,000L of molten borosilicate glass which is hard to automate.
![image](https://user-images.githubusercontent.com/7230430/187545773-e6d2d17c-32b4-4faf-9e99-20e0851a7fb1.png)
_note: there is a texturepack error on my side, this makes the 64 glass barely visible_

### Your Goal

It would be better if the required fluid is dividable by 144. For example, set the input fluid value to: 8064mb (56*144mb)

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
why is there glowstone block in the recipe ?
