### ISSUE TITLE
Large Steel Boiler not working after update

### ISSUE THREAD

**Issue by itsArk55** [GTNewHorizons/GT-New-Horizons-Modpack#11176]
### Your GTNH Discord Username

Ark#0740

### Your Pack Version

GT-New-Horizons-2.1.2.4-29-pre

### Your Server

Private server

### Type of Server

Don't know

### Your Expectation

Try to turn on Large Steam Boiler as noticed it off
Expect it to work as normal
Open GUI, says Incomplete structure

Was working fine before updating modpack from pre25 to pre29

### The Reality

Not working whatever I change
Still says Incomplete Structure

### Your Proposal

Please fix as it is not good for it to not work :/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
@Glease probably another problem from the autoplace integration

**Comment by chochem** [comment]
ah sorry, looks like this one is fixed already https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11114.
