### ISSUE TITLE
Nautra Sulfur not accepted (at the least) by alloy smelter.

### ISSUE THREAD

**Issue by TCWilliamson** [GTNewHorizons/GT-New-Horizons-Modpack#11177]
### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to make rubber using Sulfur gathered from sulfur clouds in alloy smelter

### The Reality

Sulfur crafter from sulfur clouds is not compatable -> have to craft it to GT tiny piles of sulfur, then back to a different modpack's sulfu

### Your Proposal

either ensure sulfur crafter from sulfur cloud is an accepted one, or ensure all machines accept the Natura Sulfur

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BritishCynic** [comment]
This is likely because the Sulfur dust has a second ordict tag, dustSuphur, while the Raw Rubber Dust recipe calls the dustSulfur tag, which the Natura Sulfur Dust isn't registered properly on.
