### ISSUE TITLE
AE2FC 4096K ME Fluid Storage Cell has infinite fluid storage

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11187]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

ME 1024K Fluid Storage Cell can store up to almost 2^31 mB fluid;
ME 4096K Fluid Storage Cell's storage should be four times as much as the 1024K one.

### The Reality

It has unlimited fluid storage.

It seems that when the amount of fluid exceeds 2^31, its byte usage will become a negative number, so its storage is never used up.

In addition, take the cell out of ME drive will clear its storage beyond 2^31, and if the cell is taken out when its byte usage is a negative number, it will be unusable.

Video here: https://youtu.be/g_z_9tMYwrA

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Runakai1** [comment]
A useful bug soon to be fixed :(
