### ISSUE TITLE
Possible erroneous omission of coke and coke blocks from large bronze and steel boilers.

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#11189]
### Your GTNH Discord Username

hallucinogender#1408

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Coal coke and coal coke blocks should be able to be used as fuel for the first two large GT boilers, because regular coal and coal blocks can be used as fuel for these. I checked every page of large boiler fuel in NEI, expecting to see coal coke and coal coke blocks.

### The Reality

Coal coke and coal coke blocks do not appear on any page of large boiler fuel recipes in NEI.

I attempted to test in a creative world whether they work _anyway_ in the large boiler, but it would not form due to a bug that has already been previously reported for this version.

### Your Proposal

If regular coal and coal blocks can be burned in the large bronze and steel boilers, which they can, then coal coke and coal coke blocks should be able to be burned in these boilers as well because these are a more processed version of the same fuel source. If they can be burned in the large boilers and the error is just with the NEI recipe list, then that list should be fixed to include coke and coke blocks.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
@Steelux8 I vaguely recall you did something with boilers. You might be interested in this.
