### ISSUE TITLE
Type filter card for AE 

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#11185]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Proposal

**Add type filter card of AE or add type filter feature to the oredictionary filter card**

![image](https://user-images.githubusercontent.com/59776356/187686105-1be0411e-4881-408a-bf03-fc6c86c802da.png)
![image](https://user-images.githubusercontent.com/59776356/187686122-86180137-ba34-401c-bb02-6f7846340f0b.png)

the oredictionary filter card is ok but still not good enough it need a type filter to make it but it can't use as a type filter 
I think it is really necessary for a type filter on export bus and storage bus 
it is so useful of no matter classified different stuff or setting up ore processing line or filtering tiny dust into packager or other needs too

### Your Goal

with the current oredictionary filter card you can only filter same variety of ore and items that have same oredictionary
this is requiring a lot of Channel and filter setting if you want to do type filtering 

### Your Vision

type filer is amazing 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by greesyB** [comment]
Why can you not do type filtering with an oredict card? E.g. `crushed* & !crushedPurified*` to get normal crushed ore? Also you can filter for multiple types at once with an oredict card. They already have more functionality than type filters unless I am missing something.

**Comment by Eason134HK** [comment]
> Why can you not do type filtering with an oredict card? E.g. `crushed* & !crushedPurified*` to get normal crushed ore? Also you can filter for multiple types at once with an oredict card. They already have more functionality than type filters unless I am missing something.
