### ISSUE TITLE
Make the extreme industrial greenhouse scream when it has goldfish crops

### ISSUE THREAD

**Issue by PolkageistHS** [GTNewHorizons/GT-New-Horizons-Modpack#11194]
### Your GTNH Discord Username

Pao

### Your Pack Version

28-pre

### Your Proposal

Currently the EIG is silent when processing goldfish crops. It should scream at a rate comparable to the number of goldfish seed bags times 32.  It could even be adjusted with an optional muffler on the EIG that mutes the screams based on the muffler pollution reduction percentage. And of course it would only be enabled if the config file allows screaming fish. 

### Your Goal

Keep the goldfish screaming like they are meant to. 

### Your Vision

Goldfish screaming. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
Please don't.
