### ISSUE TITLE
Electrolyzing Carbon Monoxide cell gives additional empty cell

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11192]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

electrolyzing CO cell in an single block electrolyzer gives one carbon dust and a oxygen cell.

### The Reality

![QQ图片20220902195043](https://user-images.githubusercontent.com/85604068/188135944-cf930514-218c-4668-bd5c-c63c439952a7.png)

**However, in 2.1.2.3QF, the recipe goes well:**
![JIVSFHL{KO6 YP24MW 7`D6](https://user-images.githubusercontent.com/85604068/188140353-cc18702a-0697-4848-97c9-dc21e4750861.png)

Seems another problem caused by the recent chemical balance...

**Also, it seems #4753 still not get fixed.**

### Your Proposal

Fix(or delete) the recipe, and add two electrolysis recipes for CO in single block electrolyzer:

1. 1000L CO (Fluid) == 1 C + 1000L O (Fluid) *with Circuit 1*
2. 1000L CO (Fluid) + 1 empty cell == 1 C + 1 Oxygen Cell *with Circuit 11*

**This makes the electrolysis recipe of CO be consistent with CO2:**
![Snipaste_2022-09-02_20-09-27](https://user-images.githubusercontent.com/85604068/188139954-7e9f110d-4645-49c5-b6a1-197f84ffb67a.png)
![Snipaste_2022-09-02_20-09-39](https://user-images.githubusercontent.com/85604068/188139960-a506e710-ac40-4c27-9c4c-bdef3466a212.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
This is but a glitch. The cell is a 0 sized stack that got stuck there somehow.

**Comment by ChromicRedBrick** [comment]
This is what I get from electrolyzing 8 CO cells.

It seems that when there is no empty cell in the output slot, one will be produced.

This empty cell cannot be output with auto-output or conveyor, I can only take it out manually.

Yes, it is 0 "empty cell". Hold in hand and right click, it disappears, but it can turn to 1 real empty cell when I use it to do something, like craft it into an IC2 universal cell.

![20220902233349](https://user-images.githubusercontent.com/85604068/188184869-2afc941d-af45-43e2-b538-4db394f661ba.png)
