### ISSUE TITLE
Changing Priority on ME Dual Interface Crashes the game

### ISSUE THREAD

**Issue by tybarkle** [GTNewHorizons/GT-New-Horizons-Modpack#11191]
### Your GTNH Discord Username

Shadowpaw#0001

### Your Pack Version

2.1.2.4-29-pre

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Actions

Place ME Dual Interface
Click the priority button in the top right of the interface

Game crashes

This persists across client and server restarts

### Crash Report

[crash-2022-09-01_21.20.13-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9474854/crash-2022-09-01_21.20.13-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by GlodBlock** [comment]
fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/a0e6277a3bd183adcca39bd876bd767d38b58205
please use the latest build in jenkins: http://jenkins.usrv.eu:8080/job/AE2FluidCraft-Rework/
