### ISSUE TITLE
Significantly improve bacteria chances

### ISSUE THREAD

**Issue by realthecaffiend** [GTNewHorizons/GT-New-Horizons-Modpack#11219]
### Your GTNH Discord Username

thecaffiend#2253 

### Your Pack Version

2.1.2.3qf  (Some config changes, no recipe changes)

### Your Proposal

Increase the bacteria output chances to 100%

### Your Goal

Bacteria would be annoying at 75%; At these rates, it's an insult to the player. I'm working on the bioware line, and this is just awful gameplay. Long cycle recipes in the cursed biolab that have incredibly tiny chances to actually succeed. Please seriously increase these: 7.5 is bad, 2.5 is just asinine. There is no real way to increase this, there is no solution to engineer, it's just a boring time gate combined with the fact you don't even know how long the time gate will be. 

### Your Vision

Not trying to have a worse experience than opening EA lootbags 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
Yeah i just ran the numbers, for a 2.5% chance of success, you have a mean of 40 tries, with a standard deviation of 39.5 ... This is retarded.
