### ISSUE TITLE
Drilling rig IV and III got shifted

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#11214]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.1.2.4-29-pre + jenkins

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

my oil is gone

### The Reality

Someone added new Oil rig II (stainless one) 
Old Tungstensteel OIl Rig IV(formerlty III) got shifted to Titanium One in world(and titanium to stainless), not just in recipes but in world, so now i have
![image](https://user-images.githubusercontent.com/39595617/188313296-149d71ca-4525-4657-9129-1ad92a24aceb.png)

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
That's part of the rig retiering. It's a necessary breaking change, as you can't retier them without changing their structure check.
