### ISSUE TITLE
Chunks never unload while a game session is active

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#11212]
### Your GTNH Discord Username

hallucinogender#1408

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Chunks that are not being actively loaded by either a nearby player or by some means of artificial chunkloading should be unloaded according to the standard behaviour of the game.

It is worth noting that I have Optifine installed for shaders, though I have not seen anyone else using Optifine report a similar problem.

### The Reality

Chunks that are loaded by any means remain loaded indefinitely. The only way I have found to reduce the number of loaded chunks (as listed in the information in the top left of the UI) is by closing the game and reopening it.

I asked about the problem in the Discord server and FTB Utilities was suggested as a possible cause. I removed FTB Utilities (having installed it solely for the purpose of chunkloading without needing world anchors, as is suggested in a few places for the pack). The issue remains without FTB Utilities, so I can only conclude it is a problem with something else.

### Your Proposal

Determine the cause, and fix the chunkloading issues. I unfortunately can't help much with finding the source of the issue as I have no idea what could possibly be causing this now that FTB Utilities is ruled out as a possibility; it _might_ be Optifine, but if I am the only person using Optifine who has encountered this issue then a connection seems unlikely.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FlandreS** [comment]
Does it seem that _all_ chunks are loaded? On my server, I'm noticing that most of my base remains loaded 24/7, even though I'm only using personal anchors.

Only the area of my base though, the server plugin Plan shows the number of loaded chunks to still increase significantly upon my return implying that, if it's to be believed, only the base itself is being force loaded while the rest of the overworld seems unaffected.

It's been suggested before that it's a Thermos problem, though if we're having the same experiences maybe it's not the case.

**Comment by boubou19** [comment]
Thermos doesn't cause more ghostloading than any other server brand.

What is happening tho is that you managed to make a weird interaction between multiple mods, so they all keep loading the chunks. It's hard to track down, and in the worse case, it's even ghostloading.

**Comment by KevTheGame-Dev** [comment]
I've experienced this myself. Chunks Loaded counter continually increments, never goes down. Chunks don't unload until I close the game and reopen.
![image](https://user-images.githubusercontent.com/31352416/212387080-2a98436d-06ed-48a0-8a01-e3c1c48ae684.png)

Im also using Optifine. Related settings:
- Chunk updates: 1
- Lazy Chunk Loading: on
- Preloaded chunks: off
- dynamic updates: off
- Render distance: 20
