### ISSUE TITLE
Liquid Helium temperature seems incorrect

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11220]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Temperature of liquid helium should be lower than helium gas.

### The Reality

Liquid helium is 300K while helium gas is 295K.
![image](https://user-images.githubusercontent.com/85604068/188460410-d149a99c-09c1-47d6-ac62-525a9521242d.png)
![image](https://user-images.githubusercontent.com/85604068/188460442-7f17f1d7-6f41-41bb-b006-b1672050269e.png)

### Your Proposal

In reality, liquid helium should be 4K at standard pressure.

https://en.wikipedia.org/wiki/Liquid_helium

Whatever the temperature of liquid helium is in GTNH, it should be much lower than that of helium gas.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
in code it is defined with Meltig point 1 and boiling point 4 (it is set to 1K and 4K) not sure why it is displayed wrong
@minecraft7771 any idea ?

**Comment by minecraft7771** [comment]
> in code it is defined with Meltig point 1 and boiling point 4 (it is set to 1K and 4K) not sure why it is displayed wrong @minecraft7771 any idea ?

I looked into it. NEI actually displays the values that are given in `GT_Loader_Item_Block_And_Fluid.java` Not sure if we should just change the values there or interconnect them with those defined in `Materials.java`. Apart from that we'd need to go through probably all gases, since many have their temp set as 295K.
