### ISSUE TITLE
Chest and Super buffers sorting mode 

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#11237]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.1.2.0

### Your Server

Eta

### Type of Server

Thermos

### Your Expectation

Trying to use chest and superbuffer with enabled sort mod

### The Reality

I got a bonk from staff
With sort mode it creates a lot of lags(x3 for chest buffer, x12 for super buffer)
Chest buffer **WITH** sort mode
![image](https://user-images.githubusercontent.com/70205464/188935695-a5ebe00f-3aee-41d8-bbeb-1d6c4aa366c9.png)

Chest buffer **WITHOUT** sort mode
![image](https://user-images.githubusercontent.com/70205464/188935813-89acbbb0-c0d2-4f39-bcad-b5b573dfdd43.png)

### Your Proposal

Sort mode be server-friendly and nice to use it

Note: we cant to not use sort mode for buffers with different items, because one item will take up all available slots like this:
![image](https://user-images.githubusercontent.com/70205464/188936651-1da71661-4176-4d44-bcac-983e51d04340.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Zereff06** [comment]
sort mode on :
![image](https://user-images.githubusercontent.com/17906427/188969336-b7063be9-8b9b-4d63-8abf-1de12b46eaef.png)

sort mode off 
![image](https://user-images.githubusercontent.com/17906427/188968720-78671787-3075-4643-ba5e-d406bce2fee7.png)

**Comment by dahgul333** [comment]
![изображение](https://user-images.githubusercontent.com/35747549/188977272-99e6b2d1-88fd-45a2-82dc-4fedbb9556e0.png)
![изображение](https://user-images.githubusercontent.com/35747549/188977389-26c689b6-dff3-43e3-9b31-4154acf8cca1.png)

**Comment by Glease** [comment]
Sort mode are expected to lag. It used to lag more. There aren't a lot we can do with it. Leaving this open for now in case some genius show up and optimized it.

**Comment by Glease** [comment]
Actually, there is an optimization for this already. It's merged after 2123qf so not in your revision (thought you were using latest dev). Still, let's leave this open until next stable comes out.

**Comment by dahgul333** [comment]
> Actually, there is an optimization for this already. It's merged after 2123qf so not in your revision (thought you were using latest dev). Still, let's leave this open until next stable comes out.

![image](https://user-images.githubusercontent.com/35747549/200889967-3e30269d-4452-4db3-ab4f-d9b270b4d143.png)
2.2.0.0
Walking with hollo glasses, I noticed that in sorting mode it sorts literally every cycle of work (1 per tick on IV).As a simple solution, I see sorting once every 20 cycles(although 1 sorting sesion every 3-12 hours would be enough for me at the base)

**Comment by dahgul333** [comment]
> > Actually, there is an optimization for this already. It's merged after 2123qf so not in your revision (thought you were using latest dev). Still, let's leave this open until next stable comes out.
> 
> ![image](https://user-images.githubusercontent.com/35747549/200889967-3e30269d-4452-4db3-ab4f-d9b270b4d143.png) 2.2.0.0 Walking with hollo glasses, I noticed that in sorting mode it sorts literally every cycle of work (1 per tick on IV).As a simple solution, I see sorting once every 20 cycles(or more)(although 1 sorting sesion every 3-12 hours would be enough for me at the base)

Or/And do 3 sorting modes often(1m)/medium(15m)/rare (1h)   mean 1 sroting per x -time

**Comment by greesyB** [comment]
I have nothing against new slower sorting modes to combat lag, but the current sort speed should remain default as infrequent sorting would be next to useless in many meaningful throughput systems

**Comment by dahgul333** [comment]
> I have nothing against new slower sorting modes to combat lag, but the current sort speed should remain default as infrequent sorting would be next to useless in many meaningful throughput systems

give an example, because now the only use is to turn it on, - put the server up to 5tps and turn it off forever,or turn it on manually sometimes for a short while to eliminate the blockage

**Comment by greesyB** [comment]
> give an example, because now the only use is to turn it on, - put the server up to 5tps and turn it off forever,or turn it on manually sometimes for a short while to eliminate the blockage

How is a 200k ns block putting your server to 5tps exactly? An example is literally any usage of a buffer in front of an input bus with decent throughput

**Comment by dahgul333** [comment]
@GTNH-Colen 

> > give an example, because now the only use is to turn it on, - put the server up to 5tps and turn it off forever,or turn it on manually sometimes for a short while to eliminate the blockage
> 
> How is a 200k ns block putting your server to 5tps exactly? An example is literally any usage of a buffer in front of an input bus with decent throughput

@GTNH-Colen explain to the dude the fate of someone who will do this on official servers please :3

**Comment by greesyB** [comment]
And why should the experience on official servers impact the experience of the average player?

Any way you try to justify this, as a user if I turn on sorting mode and the inventory does not get sorted for a full minute I would think the implementation is utter garbage.

Again, a slow mode is fine as a new option, but it should not replace what I and most would consider expected behavior.

**Comment by RaitGamerGR** [comment]
Sort every 1-3 sec decrease lag 20+times without breaking setups

**Comment by RaitGamerGR** [comment]
@greesyB what do you think about it? On my test full superbuffer emptyng withou sortmode about 10 seconds

**Comment by greesyB** [comment]
Imo it should try to sort whenever the inventory is changed. I gave the code a quick glance and it seems that it already does this (sort on inventory update), but it also sorts each tick for 50 ticks after successfully moving an item?
[L317 ](https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java#L317)and [L364](https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Buffer.java#L364)
I don't know the reasoning behind this, but it seems incredibly wasteful if I am understanding it correctly.

**Comment by dvdmandt** [comment]
What about using a binary tree (red-black?) keyed by item ID or whatever is currently used for sorting, with a template ItemStack, count and a flag for each node..? Whenever items are added to the buffer, sort them into the tree, and if the count >= the output stack size, set the flag and add the node to a list (stack?) of to be output items. Each tick, check if said list has any items and if so, output the expected item count and subtract it from the count in the node. If count reaches 0, remove node, otherwise just clear the flag. Perhaps some additional math to simulate stack count and limitation, but that should be doable.

If I'm right, insertions would be O(log(n)), outputs would basically be O(1) and serialization would only need item list/count, which could probably be backwards compatible with current implementation.

Thoughts?
