### ISSUE TITLE
OPIS crash on profiler opening

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#11239]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Actions

install opis from jenkins
enter world
wait till it loads
run /opis

I had same problem on older versions 

### Crash Report

[crash-2022-09-07_22.06.26-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9509062/crash-2022-09-07_22.06.26-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment]
got the same crash when typing /opis in a singleplayer world

[crash-2022-09-10_17.01.53-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9540676/crash-2022-09-10_17.01.53-server.txt)

**Comment by BritishCynic** [comment]
@LewisSaber Is this still a problem since 2.3.0?
