### ISSUE TITLE
Multi Smelter consumes much more EU/t than expected for every coil level below Trinium

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11234]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Hope an LuV multi smelter to work properly.

### The Reality

It consumes 262144EU/t (at max parallel) when I only install one LuV energy hatch on it. It is supposed to consume less than 32768EU/t.

Also I find out that all coils from cupronickel to naquadah alloy have this problem.

Video here: https://youtu.be/yICdm63T0DE

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
do you know the version of gregtech you are running?

**Comment by ChromicRedBrick** [comment]
> do you know the version of gregtech you are running?

5.09.41.29.
