### ISSUE TITLE
some gt++ ore in world make scanner cant open gui

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#11232]
### Your GTNH Discord Username

456k#6874

### Your Pack Version

2.1.2.4pre29

### Your Server

sp

### Your Expectation

open scanner gui in gt++ world

### The Reality

it cant open, if there is Fluorite ore in world. there are some ore also make this case

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
i thought detrave scanners weren't compatible at all with gt++ ores?
