### ISSUE TITLE
Weird behavior with saw and chainsaw

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#11240]
### Your GTNH Discord Username

Alexdoru#9395

### Your Pack Version

dev

### Your Server

solo

### Your Expectation

breaking an ice block with a saw/chainsaw should drop the block of ice and not spawn a water source

we should be able to break flowers and double tall grass

### The Reality

breaking an ice block with a saw/chainsaw drops the block of ice and spawns a water source

we can't break flowers and double tall grass

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by 52871299hzy** [comment]
Ice blocks still spawn water when harvested by saw in 2.8.1. It seems that the fix in Hodgepodge was removed but never got re-implemented in GT5U.
