### ISSUE TITLE
[RC1] Crash on Startup

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#11249]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.2.0.0-RC1

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Attempted to boot up MultiMC package, and it crashes.

### Crash Report

https://pastebin.com/Zg1vbv6k

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by GlodBlock** [comment]
forgelin :desolate::FUUUCKGINGFUCK:

**Comment by Ethryan** [comment]
Ran into this too

**Comment by Dream-Master** [comment]
redown load the Pack or exchange Forgelin 1.9.5 with 1.9.2 <https://www.dropbox.com/s/ds0e1iiv05j3emk/Forgelin-1.9.2-GTNH-1.7.10-Edition.jar?dl=0>
