### ISSUE TITLE
Scanner cannot show ore name properly in ross128ba

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11241]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

scan ores in ross128ba.

### The Reality

The scanner cannot show ore names properly.
![Ross128ba_Scanner](https://user-images.githubusercontent.com/85604068/189033822-e1d07b45-fac3-4aa0-8df8-cd00a42dfc1f.png)

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@minecraft7771 can you fix that as well. Seen you fixed gt++ ores
