### ISSUE TITLE
Stocking Input Bus in subnetworks

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#11243]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Expected to ME Stocking Input Bus to see items throu storage bus + interface connection

### The Reality

It dont see while terminal sees

### Your Proposal

Fix
EDIT: After Some investigation i found out that problem is just visual, bus works properly but its inside is not changed when item change quantity

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Please post your exact setups. It's hard to guess what you are doing with a 15 word sentence.

**Comment by LewisSaber** [comment]
After some investigation i found out that problem is that i placed item in stocking bus before i connected its network to the one that have items

**Comment by boubou19** [comment]
it shouldn't matter, as the network should update itself

**Comment by LewisSaber** [comment]
> it shouldn't matter, as the network should update itself

After even more testing it looks like bug is visual

**Comment by ADDION21** [comment]
been having this issue for a few weeks, but i cant seem to recreate it in other worlds or subnets, is there any known triggers that could cause this to happen? unlike op my issue isnt visual and the items dont seem to stock if theyre on my main net, sorry for necro

**Comment by 28Smiles** [comment]
This also happens to me for a few weeks @ADDION21 
With reloading chunks i got it to work once again but afterwards this didnt work either, i think there is some problem here (Version 2.8.4), i got it to work again, i think its some issue with the hatch/subnet forgetting who ownes it. Using a blank biometric card it works
