### ISSUE TITLE
Unable to complete the "Electrolyzing borax" quest 

### ISSUE THREAD

**Issue by Snowleopold** [GTNewHorizons/GT-New-Horizons-Modpack#11256]
### Your GTNH Discord Username

nuttertools#9992

### Your Pack Version

2.1.2.4

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I tried clicking the "Detect/Submit" button to complete the quest but it didn't work.
![borax](https://user-images.githubusercontent.com/113206098/189419698-ebe4f201-2a69-4997-ba0b-50178a33d730.png)

### The Reality

![borax](https://user-images.githubusercontent.com/113206098/189419813-92dc9312-b820-4c2b-b091-55ed73c4239a.png)
I have crafted the volumetric flask using fluid solidifier but the quest won't complete.

### Your Proposal

Seems that the volumetric flask I crafted always has NBT tags so my volumetric flask cannot be detected. It makes the quest impossible to complete without enabling cheats. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Shadowsoftime99** [comment]
Did you end up trying to run it through a Name Remover to strip the NBT, or does it keep NBT because that's how the capacity is stored?

The Name Remover might let you complete the quest but of course it'd be better if we could just let the quest ignore NBT somehow...

**Comment by Snowleopold** [comment]
> Did you end up trying to run it through a Name Remover to strip the NBT, or does it keep NBT because that's how the capacity is stored?
> 
> The Name Remover might let you complete the quest but of course it'd be better if we could just let the quest ignore NBT somehow...

I tried putting it in name remover, it didn't work
