### ISSUE TITLE
Z-Logic controller has lost it's recipe

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#11250]
### Your GTNH Discord Username

Ethryan

### Your Pack Version

2.2.0.0-Pre1

### Your Server

Private server

### Type of Server

Thermos

### Your Expectation

![image](https://user-images.githubusercontent.com/3237986/189360613-3beb6221-8ea8-4790-b41b-ec84f5dff30d.png)

### The Reality

Not craftable

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
fixed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/1f963ccaf35b32df2e6b5c2cd51c24e9e0b1b910
