### ISSUE TITLE
AE2 Printed Silicon taking Solar Grade silicon plate instead of raw

### ISSUE THREAD

**Issue by Alrightsc** [GTNewHorizons/GT-New-Horizons-Modpack#11252]
### Your GTNH Discord Username

Alright#2304

### Your Pack Version

2.2.0.0 RC-1

### Your Server

SP

### Your Expectation

Craft AE2 printed silicon with raw silicon plate and press in forming press, get printed silicon.

### The Reality

The printed silicon now takes solar grade silicon plate instead of raw.

### Your Proposal

Fix/change it back. It used raw silicon plates without issues in 29-pre, so don't know what happened here. The old AE2 inscribers still take in regular silicon to craft them for some reason.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
It's a bug to still use regular silicon. I thought dream fixed that a while ago.

**Comment by Glease** [comment]
@Dream-Master Did you forget to commit the `.minecraft/config/AppliedEnergistics2/recipes/user/materials/circuits.recipe` to github?
