### ISSUE TITLE
crash after updating server to GT_New_Horizons_2.2.0.0-RC-1_SERVER

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11257]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

2.2.0.0-RC-1

### Your Server

priv srv

### Your Actions

After updating the server from 2124-dev its no longer starts up.

### Crash Report

[crash-2022-09-09_20.42.25-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9537994/crash-2022-09-09_20.42.25-server.txt)
[crash-2022-09-09_20.47.15-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9537995/crash-2022-09-09_20.47.15-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
Please remove craft presence manually for now. It will be removed for later releases.

**Comment by Szajkop** [comment]
I removed craftpresence-1.7.10-1.8.3-GTNH.jar
it still crashes:
[crash-2022-09-09_23.11.00-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9538893/crash-2022-09-09_23.11.00-server.txt)

**Comment by Dream-Master** [comment]
> I removed craftpresence-1.7.10-1.8.3-GTNH.jar it still crashes: [crash-2022-09-09_23.11.00-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9538893/crash-2022-09-09_23.11.00-server.txt)

remove this mods as well

* craftpresence
* bettercrashes
* DefaultWorldGenerator
* MouseTweaks
* defaultserverlist

**Comment by Szajkop** [comment]
Thanks, i managed to start it by disabling
- craftpresence
- DefaultWorldGenerator
- MouseTweaks
