### ISSUE TITLE
Some recipes display out of screen range in NEI

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11255]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

NEI display recipes properly.

### The Reality

1. d-o-b comb
![d-o-b](https://user-images.githubusercontent.com/85604068/189410679-26d5960f-7e3e-4b3b-a636-2b52ebb73dce.png)

2. Floral/Blossom/Botanic bee
![Floral](https://user-images.githubusercontent.com/85604068/189411287-d4939d3b-57a6-4e58-875c-fdc785f46db9.png)

![Blossom](https://user-images.githubusercontent.com/85604068/189411282-e6ff1375-6d9a-426c-b6f7-f37b33fe878b.png)

![Botanic](https://user-images.githubusercontent.com/85604068/189411285-2412c4b9-e365-45b5-b38d-047ecb4622df.png)

I'm using smooth font but I have asked other people who do not add addtional mods, they also have the problem.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
It seems that d-o-b comb centrifuge recipe is incorrect. It can only produce the first six products in a single block centrifuge machine.

**Comment by ChromicRedBrick** [comment]
Tested with an industrial centrifuge, it really can produce such items.
![centrifuge](https://user-images.githubusercontent.com/85604068/189413809-a8a8f8ec-d6a2-4c5a-8363-413d6fc7192f.png)

**Comment by Runakai1** [comment]
> It seems that d-o-b comb centrifuge recipe is incorrect. It can only produce the first six products in a single block centrifuge machine.

Recipe is added via script. It used to only display the 6 items but was always able to produce more.
