### ISSUE TITLE
Waila feature update

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#11268]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.1.2.0

### Your Proposal

After machine works with time <1 sec waila shows time in ticks 

### Your Goal

0 secs dont give needed information of working time, its 1 tick or 19?
![2022-09-10_10 22 01](https://user-images.githubusercontent.com/70205464/189473848-03172d16-802d-4f6e-9233-bc7017d01756.png)
its 8 ticks!

### Your Vision

With this feature waila be nicer for high tiers and fast recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
use a scanner

**Comment by RaitGamerGR** [comment]
> use a scanner

Ok, time to remove time showing, because we have scanner

**Comment by boubou19** [comment]
It is limited like that to avoid packet spam iirc. As Chochem said, if you want to know something faster than a sec, use the tricorder.

**Comment by vlaetansky** [comment]
We can show total tick time required for a recipe and it won't lead to a packet spam.
