### ISSUE TITLE
java.lang.IllegalArgumentException: Could not get provider type for dimension 83, does not exist

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#11271]
### Your GTNH Discord Username

Alexdoru#9395

### Your Pack Version

GTNH 2.2.0.0 RC1

### Your Server

solo

### Your Actions

I updated the pack to latest version and I was doing nothing special when the crash happened

### Crash Report

[crash-2022-09-10_00.48.48-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9540626/crash-2022-09-10_00.48.48-server.txt)
[crash-2022-09-10_16.32.13-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9540627/crash-2022-09-10_16.32.13-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
