### ISSUE TITLE
Add fuzzy card and oredictionary filter card support for ME void storage

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11270]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-1

### Your Proposal

Add fuzzy card and oredictionary filter card support for ME void storage.

### Your Goal

We need it to void items like enchanting books and equipments.

### Your Vision

QoL.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AlbertoPirillo** [comment]
Yep, that would be appreciated. 
It's the first use I thought of for void storage. If it doesn't support at least fuzzy card, void storage is basically useless

**Comment by SafariXiu** [comment]
We really need it. AE in my family has been too slow for garbage disposal, so the warehouse is too slow
![QQ截图20221014221341](https://user-images.githubusercontent.com/98251218/195868938-8bd5e585-78cb-45f3-accf-fa0b4a92f786.jpg)
