### ISSUE TITLE
Add Ghost Circuit entry to Tips and Tricks quest tab

### ISSUE THREAD

**Issue by dragagon** [GTNewHorizons/GT-New-Horizons-Modpack#11279]
### Your GTNH Discord Username

Dragagon#5025

### Your Pack Version

2.2.0.0 RC 1

### Your Proposal

Add a check box entry into the Tips and Tricks tab specifically for the Ghost Circuit in the lower right. Having it in the Circuit Programming quest makes it easy to miss.

### Your Goal

Make it easier to find info about the Ghost Circuit since the Wiremill now requires it and its easy to miss.

### Your Vision

The quest text for the Ghost Circuit is easy to miss for returning players or players upgrading now that its added to the wiremill.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I dont think its easy to miss, but we can copy the quest over. Not a new quest though.
