### ISSUE TITLE
Large Molecular Assembler does not return reusable items

### ISSUE THREAD

**Issue by Blockmaster139** [GTNewHorizons/GT-New-Horizons-Modpack#11285]
### Your Pack Version

2.1.2.4-29-pre with MX-Random updated to 0.1.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Request to autocraft items that use GT tools or water buckets, etc. in the recipe with the crafting pattern inside an active Large Molecular Assembler. Tested with GT++ Wash Plant Casing, LV Machine Casing and Fresh Water crafting recipes. Expect to complete the craft, receive items, tools and empty water bucket to be returned.

### The Reality

Some of the requested items are given, but reusable items are not returned. Craft will return only as many items as you have tools, eg. requesting 8 LV Machine Casings while having 1 Wrench in your AE System will only give 1 LV Machine Casing. The crafting CPU does not complete the craft and will state that it is currently crafting the tool/bucket which will not get completed, and the tool/bucket will not be returned when the craft is cancelled.

### Your Proposal

Functionality should be the same as a regular Molecular Assembler: Tools should be returned with some durability used, empty buckets should be returned, multiple crafts should be able to reuse the same GT tools, and the craft should be completed in the crafting CPU.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
I also encountered this problem. It's annoying, making large molecular assembler useless since many recipes require GT tools.

**Comment by Oueio** [comment]
Still issue in 2.2.0.0. Can devs fix it please?

**Comment by AlbertoPirillo** [comment]
Afaik the LMA has another, much bigger issue: the lag it creates increases exponentially with the number of provided patterns.
Thus, I don't think that this will be taken care of until someone fixes its main issue.
