### ISSUE TITLE
My horny boink doesn't KB

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#11284]
### Your GTNH Discord Username

AdamR#0072

### Your Pack Version

2.1.2.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

![image](https://user-images.githubusercontent.com/76914762/189530657-fa7a052d-7343-402f-a991-285272cd2d36.png)
expected boubs to fly

### The Reality

he didn't >:(

### Your Proposal

fix it :(
(my bet is that too much kb cancel kb or something idk)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by POPlol333** [comment]
small precision, but he didn't fly, I mean there was literally 0 kb (tested on non op person too)

**Comment by boubou19** [comment]
that's all you get for trying to yeet people out of your sight.

**Comment by POPlol333** [comment]
said the world breaker spammer guy

**Comment by Connor-Colenso** [comment]
This may be an issue in minecraft itself, if you try enchant a stick with say knockback 50 it just won't do knockback for some reason.
