### ISSUE TITLE
NEI: excessive animations

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11294]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

latest dev

### Your Proposal

Animations are cool but getting out of hand when opening GUIs regularly
https://user-images.githubusercontent.com/7230430/189756710-9b55c2f0-0f20-48d9-a3cc-3106c9704f48.mp4

### Your Goal

reduce animations

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
yeah wtf is that? is there a config for it?

**Comment by mbryantms** [comment]
Looks like NEI has 20 columns with one interface and adjusts to 21 columns with the other. It then appears to be an animation as everything adjusts down the line. So to me doesn't look like intended animation but rather just different numbers of columns adjusting between the different screens.

**Comment by Szajkop** [comment]
In RC3 the animations got reduced to minimum
