### ISSUE TITLE
Crash when clicking on Open Modular Turrets configuration button

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11297]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

latest dev

### Your Server

priv srv

### Your Actions

I tried to open the turret's configuration GUI to add trusted players to the turret and it crashed the game

### Crash Report

[crash-2022-09-12_23.59.03-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9552258/crash-2022-09-12_23.59.03-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
