### ISSUE TITLE
Downloading latest pack version without having it previously installed only downloads 40 mods

### ISSUE THREAD

**Issue by sharpskull2** [GTNewHorizons/GT-New-Horizons-Modpack#11292]
### Your Pack Version

2.1.2.3-1.7.10

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to download the pack with the latest version I expect to get all the mods necessary for the pack

### The Reality

Only 40 mods are downloaded I have to go back and download some previous version, which I don't know, to get all the necessary mods for the pack then work my way up through the versions

### Your Proposal

Please make it so that downloading the latest version of the pack downloads all the mods instead of just overriding what is currently there.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
You are using the curseforge/twitch release while you were previously using the mmc release. It will download all needed mods on first modpack run.
