### ISSUE TITLE
World generation changed somewhere between 

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#11291]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.2.0.0-RC1

### Your Server

SP

### Your Expectation

Somewhere between dev 2.1.2.4-4 and 2.2.0.0-RC1 the worldgen changed, leading to ugly hard cuts in the world. That really sucks, and if i can not resolve it, i will likely give up this run because i don't want to invest thousands of hours into a broken world.
In my Opinion, special care should be taken that this almost never happens, or only when unavoidable, and sicne it was not announced, i guess it is by accident. Other people in Discord had the same problems.

### The Reality

![2022-09-12_12 37 15](https://user-images.githubusercontent.com/10967188/189634071-c84d53ad-2ac2-495e-956c-3296200b1466.png)
![2022-09-12_12 37 33](https://user-images.githubusercontent.com/10967188/189634086-f27f5b0c-45cc-47cd-9732-42d9de2ac205.png)

### Your Proposal

Find what changed it and revert it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
we not change anything in world gen from 2.1.2.4 to 2.2.0.0 so far ik.

**Comment by mitchej123** [comment]
Verify your configs locally didn't shift or other user error.  I had a similar issue and turns out mucked up the config.  I used world edit to delete the effected chunks and they regenerated properly

**Comment by Savallator** [comment]
i did not change any config options. Afaik, the seed and level type should be in the world save, so that should have stayed the same anyways. Also, people on Discord had the same issue...

**Comment by Savallator** [comment]
The issue can be reproduced easily:
1. Create a world in an older version (i used 2.1.2.4-4 dev).
2. Load that into the new RC.
3. Get ugly borders

**Comment by mitchej123** [comment]
Worth running a diff on the relevant configs between the two, or any potential unintentional mod changes.

**Comment by mitchej123** [comment]
As dream noted, nothing was intentionally changed.  Any help tracking down which change(s) broke this would be helpful.

**Comment by Dream-Master** [comment]
let me test it in my world to be sure we not have an oversight here.

**Comment by Dream-Master** [comment]
@Savallator cant reproduce.
My world is older than 2.1.2.4 but i am on RC2 as well and i have no issues generating new chuncks. Must be on your end.

**Comment by ChromicRedBrick** [comment]
I just started a new save in 2.2.0.0 and got weird world generation.
![1](https://user-images.githubusercontent.com/85604068/192736221-4866f268-2a65-4c97-b360-6656bc228701.png)
![2](https://user-images.githubusercontent.com/85604068/192736234-34e1efb2-9ecc-4f36-bbd5-b901f2b7a8ec.png)
![3](https://user-images.githubusercontent.com/85604068/192736237-3febab71-2af7-47ba-aac0-ec7bc8461444.png)
![mountains](https://user-images.githubusercontent.com/85604068/192736242-35605c3a-b750-4dd8-9790-2216b317729b.png)
![ugly mountain](https://user-images.githubusercontent.com/85604068/192736248-a69ffe38-ea84-463b-81f3-2aab4dbbd675.png)

**Comment by kaspertfg** [comment]
I found this as well and it appeared to be caused by the newest version of RWG 1.3.2.1.  Perfect test is to load this seed -2880359926994560111 in the 2.2.0.0 and compare with loading it in  2.1.2.3qf.

**Comment by chochem** [comment]
It seems that RWG is the likely cause. All pack version up to dev29 used RWG-alpha-1.3.2.jar. The RCs then switched to 1.3.2.1 for some reason.

That explain why stuff is only broken now, even though the changes between those version were done back in February.

On the surface it looks like only license stuff. But in fact some biome apis were changed too

![image](https://user-images.githubusercontent.com/40274384/192739144-926604c9-79da-4771-80e4-ce99b30acc17.png)
![image](https://user-images.githubusercontent.com/40274384/192739222-3d1f4945-b04b-4e76-a7a2-15086f0a3f95.png)

**Comment by eigenraven** [comment]
The biome apis were removed and moved to use gradle dependencies instead of copy-pasted code so it shouldn't have an impact

**Comment by ChromicRedBrick** [comment]
I replaced rwg-1.7.10-alpha-1.3.2.1.jar with rwg-alpha-1.3.2.jar, using the same seed (832856121806790657) to generate the world.

Spawning area in 1.3.2.1:
![1 3 2 1](https://user-images.githubusercontent.com/85604068/192741672-58928ef0-4c86-4ed7-b8c1-4949f3242afa.png)
![Spawning1 3 2 1](https://user-images.githubusercontent.com/85604068/192741680-30440cb6-53a3-4700-827c-25c9da4780de.png)

Spawning area in 1.3.2:
![1 3 2](https://user-images.githubusercontent.com/85604068/192741776-ed893603-0b45-48ca-a21e-83165e4948e3.png)
![Spawning1 3 2](https://user-images.githubusercontent.com/85604068/192741785-24104083-80f8-497e-b0b7-e99f23c4b7c0.png)

**Comment by chochem** [comment]
apparently some more stuff was changed in between those version. Actual changelog should be this:

![image](https://user-images.githubusercontent.com/40274384/192742363-50a59631-6ccf-43db-b4fc-3a3068031543.png)

**Comment by eigenraven** [comment]
Can you test the jar from <http://jenkins.usrv.eu:8080/job/Realistic-World-Gen/4/>?

**Comment by ChromicRedBrick** [comment]
> Can you test the jar from http://jenkins.usrv.eu:8080/job/Realistic-World-Gen/4/?

Tested this jar with the same seed 832856121806790657.
![1 3 2 1_1](https://user-images.githubusercontent.com/85604068/192749534-ba3ef252-2987-460b-872c-62a731f8dcda.png)
![Spawning1 3 2 1_1](https://user-images.githubusercontent.com/85604068/192749542-8df15a69-47fa-48a6-9968-86644db3d5c9.png)

**Comment by Askara** [comment]
> Can you test the jar from http://jenkins.usrv.eu:8080/job/Realistic-World-Gen/4/?

[crash-2022-09-28_11.52.05-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9663891/crash-2022-09-28_11.52.05-server.txt)

**Comment by Abalieno** [comment]
I think it's fine. :add troll emote:

![2022-09-28_12 43 35](https://user-images.githubusercontent.com/4656436/192760032-3231feaf-4070-47dc-8ce4-ff86e474e8d5.png)

**Comment by eigenraven** [comment]
> [crash-2022-09-28_11.52.05-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9663891/crash-2022-09-28_11.52.05-server.txt)
> 
> Crash while ingame explore-generation. Terrain generation is different from 1.32.0

This crash should now be fixed, the generation will be slightly different due to a couple of added biomes and bugfixes, but it's now mostly the same as before. Jar for testing: <http://jenkins.usrv.eu:8080/job/Realistic-World-Gen/7/> PR to review: <https://github.com/GTNewHorizons/Realistic-World-Gen/pull/3>

**Comment by dvdmandt** [comment]
I've started working on making this a config option to allow users to upgrade worlds created in 2.2.0.0 to update to newer versions without chunk border ugliness: https://github.com/GTNewHorizons/Realistic-World-Gen/pull/4
