### ISSUE TITLE
Requesting missing items in wireless crafting terminal crashes the client

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11295]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

latest dev

### Your Server

priv srv

### Your Actions

When i try to make a recipe in the wireless crafting terminal and some mats are not on storage i press CTRL+? in NEI to order the craft of missing items.

### Crash Report

When i CTRL+Click it crashes while trying to load the recipe/order the missing items.
[crash-2022-09-12_22.59.02-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9551807/crash-2022-09-12_22.59.02-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment]
already fixed by https://github.com/GTNewHorizons/NotEnoughEnergistics/pull/17

you can download this update of the mod to solve the crash https://github.com/GTNewHorizons/NotEnoughEnergistics/releases/download/1.3.18/NotEnoughEnergistics-1.7.10-1.3.18.jar

**Comment by Szajkop** [comment]
> already fixed by [GTNewHorizons/NotEnoughEnergistics#17](https://github.com/GTNewHorizons/NotEnoughEnergistics/pull/17)
> 
> you can download this update of the mod to solve the crash https://github.com/GTNewHorizons/NotEnoughEnergistics/releases/download/1.3.18/NotEnoughEnergistics-1.7.10-1.3.18.jar

I was using NotEnoughEnergistics-1.7.10-1.3.18-4-g7cd7052.jar

**Comment by Szajkop** [comment]
Updating to:
- WirelessCraftingTerminal-1.7.10-1.8.8.7-1-gea10257.jar
- NotEnoughEnergistics-1.7.10-1.3.18-9-gf06c687.jar

fixed the problems
