### ISSUE TITLE
Chem Rework Balance Issues List

### ISSUE THREAD

**Issue by Elisis** [GTNewHorizons/GT-New-Horizons-Modpack#11299]
### Your Pack Version

Many

### Your Proposal

For discussing and noting any balance issues that arise from the chemistry rework.

### Your Goal

- [ ] The ratios of Chemical Reactor dust recipes (Uraninite, etc.) are now the same as electrolysis
- [ ] Rutile processing is now Chlorine-neutral
- [ ] Platline is now Calcium-neutral
- [ ] Alumina yield from clay unfair
- [ ] Alumina + Cryolite EBF recipe not worth anymore

**Comment by GlodBlock** [comment]
1) remove the simple electrolyis recipe, but it will break someone's base.
2) make rutile line loss 1b chlorine per titanium
3) calcium neutral in platline is fine imo, platline itself is already complex enough and it costs other material heavily.
4) add clay + sodium hydroxide mixer recipe like other alu-related ore, so clay can output the same alu like before.
5) make cryolite ebf recipe costs 1 cryolite dust.

these are my proposal
