### ISSUE TITLE
Ender Fluid Cover log spam

### ISSUE THREAD

**Issue by Eranicus** [GTNewHorizons/GT-New-Horizons-Modpack#11298]
### Your GTNH Discord Username

Eranicus#5476

### Your Pack Version

RC-1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

.

### The Reality

After ender fluid link covers were changed from color to numbers they started to spam log with the following errors:

[02:24:06] [Server thread/INFO] [STDOUT]: [com.github.technus.tectech.mechanics.enderStorage.EnderWorldSavedData:func_76187_b:68]: ENDER_LIQUID_TAG_LINK SAVE FAILED
[02:24:06] [Server thread/INFO] [STDOUT]: [com.github.technus.tectech.mechanics.enderStorage.EnderWorldSavedData:func_76187_b:69]: java.io.NotSerializableException: net.minecraft.nbt.NBTTagCompound

They work but keep spamming the error.

### Your Proposal

please fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Could you provide more info how you use it or even the save? I can't reproduce this in test environment

**Comment by Eranicus** [comment]
> Could you provide more info how you use it or even the save? I can't reproduce this in test environment

well here is more info,  my play world is dev-18 (tectech version before cover update)

I just did some more testing, I updated copy of my world (dev-18) to RC-4 and removed every possible cover and log spam disappeared.

I think I might know what the problem is. Right now after cover update if you have full tank and you put cover , it will start working immediately by pumping fluid into  (empty channel) and this will start error spam 

Previously the cover would start working only after you press button (import or export)

**Comment by Eranicus** [comment]
> Could you provide more info how you use it or even the save? I can't reproduce this in test environment

ok I did a few more testing, Im not sure why you cant reproduce it. I just did a clean install of RC-4, created new world , created 8 filled tanks and 8 empty tanks , placed 8+8 covers with channels 1-8  and here it is .... :  
![DiscordDiscord Server Invite Splash Image Size](https://user-images.githubusercontent.com/92493145/192177379-1f8cfe8e-d18d-40bf-aa03-f843592df268.png)

**Comment by boubou19** [comment]
we get those as well on delta, i guess that's because they are older covers than cannot auto convert or something.

**Comment by cinch** [comment]
mine were freshly crafted

**Comment by minecraft7771** [comment]
> we get those as well on delta, i guess that's because they are older covers that cannot auto convert or something.

The covers fail to save the fluid data, no matter if they are old or new, this was caused by https://github.com/GTNewHorizons/TecTech/pull/62. But the only solution that I would be capable of coming up with would break all covers (deleting their saved channels). Idk if someone more experienced than me can do this without breaking
