### ISSUE TITLE
"Wooden Bolts" quest requirement for iron bolts should be optional to allow for other bolt materials

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#11301]
### Your GTNH Discord Username

hallucinogender#1408

### Your Pack Version

2.1.2.4-29-pre

### Your Proposal

Steam age quest "Wooden Bolts" (quest ID 1156) says in the description "For now, you can put either iron, alumite, or steel on the tip of your bolts using the Smeltery." However, the third quest objective requires that players tip their bolts with iron, and will not register bolts made with other options. This objective is required to complete the quest. It should be made optional so that players can use alumite or steel if desired, while still being able to complete the quest.

### Your Goal

The quest suggests that players use either iron, alumite, or steel. It should be completable no matter which material players use to create their crossbow bolts, and should not specifically require the bolts to be made of iron.

### Your Vision

The ability to make bolts using any of the suggested materials while still completing the quest would mean that players who want to make crossbow bolts out of steel or alumite would still be able to do so without having to waste time creating undesired iron bolts as well.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by hallucinogender** [comment]
> the final one needs iron too right? so just making step 3 optional doesnt change anything.

I don't think it does. This was a few days ago but I think the final one completed with my finished steel bolts. I think the issue is that, while _completed_ Tinker's Construct tools are part-agnostic for quests that ask for them (so, for example, you can complete the quest for a hammer with one made with iron, wood, and obsidian even though the quest depicts one made solely of steel), incomplete bolts do not have this property.

**Comment by chochem** [comment]
I dont know if thats correct but I will make them optional. it doesnt hurt anyway.
