### ISSUE TITLE
Add bending machine recipes for metal rings

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#11306]
### Your GTNH Discord Username

hallucinogender#1408

### Your Pack Version

2.1.2.4-29-pre

### Your Proposal

Metal rods should be able to be turned into metal rings in a bending machine, in a 1:1 ratio.

### Your Goal

It'll allow for a reduction of manual crafting of components prior to MV.

### Your Vision

Rings being manually crafted exclusively prior to MV has always seemed strange, so it'd make sense for them to be able to be machine-crafted. This change as described would not make significant changes to game balance, but it _would_ allow for a bit more automation early on of a component that is otherwise fairly inconvenient. Additionally, it makes sense that a machine called a "bending machine" would be able to bend a rod round into a ring shape.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
@hallucinogender make it out of a rod make sense ?
