### ISSUE TITLE
Can't create and start server on my own box

### ISSUE THREAD

**Issue by sharpskull2** [GTNewHorizons/GT-New-Horizons-Modpack#11304]
### Your Pack Version

2.1.2.3-1.7.10

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Actions

Uploaded the pack to my server box and removed clientside folders cause those shouldn't be needed for a server

### Crash Report

`Server thread/ERROR16:08:18
Skipping event FMLServerStoppedEvent and marking errored mod tectech since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod bartworks since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod EMT since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod bartworkscrossmodtgregworkscontainer since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod GoodGenerator since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod gtnhlanth since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod TGregworks since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod bartworkscrossmod since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod botanichorizons since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod findit since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod galacticgreg since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod GalaxySpace since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod Australia since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod ToxicEverglades since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod detravscannermod since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod gtneioreplugin since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod gtnhtcwands since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod hydroenergy since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod kekztech since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod ModMixins since required dependency gregtech has errored
Skipping event FMLServerStoppedEvent and marking errored mod openglasses since required dependency OpenComputers has errored
Skipping event FMLServerStoppedEvent and marking errored mod opensecurity since required dependency OpenComputers has errored
Skipping event FMLServerStoppedEvent and marking errored mod WitchingGadgets since required dependency gregtech has errored
Server thread/INFO16:08:18
The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED. Errors may have been discarded.
The state engine was in incorrect state ERRORED and forced into state AVAILABLE. Errors may have been discarded.`

[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9560470/GregTech.log)
[latest (9).log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9560472/latest.9.log)
[crash-2022-09-13_16.08.18-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9560473/crash-2022-09-13_16.08.18-server.txt)

error that shows in the server console, as well as crash report, latest log, and gregtech log

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by sharpskull2** [comment]
I found the server pack under the downloads link for your website. It would be nice to have it on curse as well for ease of access

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
