### ISSUE TITLE
Super Glue Line Sodium Hydroxide Inconsistant

### ISSUE THREAD

**Issue by SSWZDDTI** [GTNewHorizons/GT-New-Horizons-Modpack#11307]
### Your Pack Version

2.2.0.0-RC2

### Your Server

SP

### Your Expectation

Recycling sodium in super glue line won't give extra sodium.

### The Reality

Instead of a perfect loop, recycling salt by either directly electrolyzing salt or mix into salt water then electrolyze it will give extra sodium hydroxide.

### Your Proposal

Decrease salt returned or increase sodium cyanide required in the line.
![Capture](https://user-images.githubusercontent.com/44363450/190094064-e032efc5-6aae-4b9e-a066-989b1ef95b31.PNG)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Steelux8** [comment]
How exactly do you get more Sodium than you put in? I'm counting 6x2 Na from Sodium Carbonate and 3x1 Na from Sodium Cyanide as input (15 total input), and 6x1 from Salt as output (6 total output).
