### ISSUE TITLE
Exiting nei dont trigger ae terminal upate

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#11302]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.2.0.0-RC-2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Expected to leave nei and see real content of terminal

### The Reality

When you open nei recipe in any ae terminal gui(crafting status gui too) and then close, numbers in terminal wont be upated, in crafting status gui you will see recipe that was already completed 

Step to reproduce
- Order some recipe
- open any recipe in NEI
- wait a bit
- close
you will see that amount of item didnt change
when you reopen terminal it will update

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Szajkop** [comment]
Similar bug happened with me before. Mostly appears at random occasions.
For example when i order an item to craft (with the middle click) and the item is finished its not added to the already existing stock until i close and reopen the terminal.
Sometimes when i pick items out its not registering that there is 1 stack less and still displaying the original stock.

**Comment by eigenraven** [comment]
This is an issue with any gui, while the NEI gui is the main open gui minecraft will ignore update packets from the serverside container because the classes don't match up (there can only be one Gui open at a time in the Minecraft class). There's probably a fix possible via mixins/asm into vanilla packet handling code
