### ISSUE TITLE
Teleporting between personal dimenstion and OW doesn't sync your EXP

### ISSUE THREAD

**Issue by dipo33** [GTNewHorizons/GT-New-Horizons-Modpack#11313]
### Your GTNH Discord Username

Dipo#3713

### Your Pack Version

2.1.2.4-29-pre with some updated mods

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Teleport from OW to personal dimension and see the same amount of EXP i had before teleporting.

(Actually it's not only between OW and Personal Dimension, I've checked and the same issue appears when teleporting to Twilight Forest, but doesn't happen when teleporting to Nether)

### The Reality

After teleporting, it shows i don't have any EXP. 

It has to be some sync issue, since rejoining the server fixes the issue.

### Your Proposal

Properly sync it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
Yeah also happens to the health bar, relatively known bug

**Comment by eigenraven** [comment]
For reference: <https://github.com/MinecraftForge/MinecraftForge/pull/4830/files>, <https://bugs.mojang.com/browse/MC-88179>

**Comment by eigenraven** [comment]
Actually hodgepodge should already be fixing this, and PS portals use code almost identical to nether portals to transfer players between dimensions (ServerConfigurationManager's transfer method taking a Teleporter object), it'll need more testing to figure out why it's not working
