### ISSUE TITLE
Sulfur Dioxide can be crafted without materials

### ISSUE THREAD

**Issue by xiacari** [GTNewHorizons/GT-New-Horizons-Modpack#11316]
### Your Pack Version

2.1.2.3

### Your Server

SP

### Your Expectation

Sulfur Dioxide is crafted and some materials used in process

### The Reality

The amount of oxygen and sulfur is constantly increasing while sulfur dioxide is being created

### Your Proposal

1 MV Mixer (sulfur dust + 2L of oxygen -> 3L of sulfur dioxide)
1 MV Electrolyzer (1L of sulfur dioxide -> sulfur dust + 2L of oxygen)
This 2 Machines working together can produce oxygen, sulfur dust and sulfur dioxide infinitely for 2 Amps of MV

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
No longer valid in RC2
![img](https://user-images.githubusercontent.com/4586901/190308375-dc13da77-75b4-44dd-8d9d-22fca9085f95.png)
