### ISSUE TITLE
Compact fusion flickering and causing increased lag

### ISSUE THREAD

**Issue by GDCloudstrike** [GTNewHorizons/GT-New-Horizons-Modpack#11315]
### Your GTNH Discord Username

GDCloud#2907

### Your Pack Version

2.2.0.0-RC-2

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Expect compact fusions' lights to stay on and be relatively performant as seen in previous versions.

### The Reality

After updating from dev 28-ish to RC2, all my compact fusion reactors started flickering and causing 20x more lag compared to before updating. They have enough power and inputs, so that isnt the cause. 
The energy hatches light up for a short time every time a recipe starts/finishes (one of the two, I don't know which exactly).

Fusion Flickering:
![javaw_NC7YXSxEEl](https://user-images.githubusercontent.com/93287602/190265150-85446ddb-b9d3-44b9-a656-d8d77c0d5dab.gif)

After trying to track down when this change happened, I found that compacts became laggy and started flickering sometime between dev28 and dev29 

Scan in dev28:
![dev28](https://user-images.githubusercontent.com/93287602/190265422-d6a69914-7d5a-4e1b-b697-177f58257adb.PNG)

Scan in dev29:
![dev29](https://user-images.githubusercontent.com/93287602/190265427-6b8cfca1-f521-45ee-b38f-804664a46017.PNG)

Scan in RC1:
![RC1](https://user-images.githubusercontent.com/93287602/190265429-80fe1cc1-aa83-4442-bca1-daf5a16c88bc.PNG)

Scan in RC2:
![RC2](https://user-images.githubusercontent.com/93287602/190265433-fa1d9f27-d178-45a5-b386-134ce93aca94.PNG)

### Your Proposal

Fix the flickering and the increased lag.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
the only change in compact fusion between dev28 and dev29 is this commit https://github.com/GTNewHorizons/GoodGenerator/pull/71
@minecraft7771 any idea?

**Comment by Glease** [comment]
Probably caused by recurring call to checkStructure. This will overwrite the texture into the inactive version.

**Comment by Eranicus** [comment]
I can confirm, compacts are broken... screen is from idle compact , working one will double the lag numbers

![2022-09-16_02 00 06](https://user-images.githubusercontent.com/92493145/190523165-5aeffef7-740d-4092-a7f2-e64e3016cbe1.png)

Im not yet sure, but after I updated to RC-2 i got +0.5-0.7 ms from unknown source, might be compacts...

**Comment by GDCloudstrike** [comment]
I ran Spark on my server and the structure check does seem to be at fault here
![image](https://user-images.githubusercontent.com/93287602/191046775-647fad60-cd3b-4f05-baf1-5b5a315eb892.png)

Here's the full report
https://spark.lucko.me/eDXn6bSYzx

**Comment by minecraft7771** [comment]
I now had some time to look into it. The TT specific cyclic call doesn't reset the updateTimer, hence why it waits one update cyclc and then never stops updating. When reseting it however it would still cause a slight lag spike every 50s as the structure check is performed. Not sure if there is any way to prevent this other than just going back to the old way of never checking the structure after it has formed.

**Comment by Eranicus** [comment]
definitely going the old way because 500-700k ns per 1 working fusion is just crazy...  previously 1 working fusion was 50-60k ns for me and right now idle one is 250k ns...

**Comment by eigenraven** [comment]
Can you see if <http://jenkins.usrv.eu:8080/job/GoodGenerator/393/> helps with the lag?

**Comment by GDCloudstrike** [comment]
Its a lot better with that jar
![image](https://user-images.githubusercontent.com/93287602/191307430-b4e60966-d41e-4a38-afc5-03b365b3be4a.png)

It spikes to this from time to time, but that is still miles better compared to before.
![image](https://user-images.githubusercontent.com/93287602/191307540-67f7a15f-efdb-488f-b84d-e3be1c662e95.png)

**Comment by Eranicus** [comment]
I can confirm my working compacts are back to 50-60k ns while working (idle is also fine)

But to be honest if its possible to reverse back structure check like it was before,  please do so because spikes are bad and imagine these spikes from 10+ compacts
