### ISSUE TITLE
Increase single quantum computer output cap by adding liquid cooling

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#11317]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2200 RC-1

### Your Proposal

In the current version, the computational requirements are higher and higher, such as Dyson Swarm. I think we need to improve the computational power of quantum computers.

### Your Goal

In the real world, most supercomputers are immersed in coolant or other liquids that are not air-cooled. I think we can add liquid cooling to quantum computers to get more power with less heat sink. For example, you can put in coolant to cool the quantum computer, or you can put out thermal coolant, or super coolant, or even some other cooler liquid.

### Your Vision

At present, quantum computers are too single and their computational power is too low. Even the largest quantum computer can only output 1000 computational power. However, machines such as Dyson Swarm have a huge demand for quantum computers, which requires hundreds or thousands of quantum computers to achieve a relatively ideal power generation. Adding liquid cooling would allow the creation of APUs to be used in later stages to achieve higher computational power in a relatively convenient way and also make quantum computers more realistic

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
not stale. I think @minecraft7771 will work on it sooner or later
