### ISSUE TITLE
Windmill can double ore output and give extra slot output when processing nether/end ores

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11312]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Windmill cannot give additional outputs.

### The Reality

When process ores from nether/end (when not from normal stone), it works like an HV macerator and gives extra output, which is weird.

Video: https://youtu.be/u3i2FYAgLmY

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
In addtion, when processing common stone ores, it takes 6000s (base time), but with variant ores, it only takes 4000s (base time).

Also GTpp ores can be doubled too.

**Comment by ChromicRedBrick** [comment]
This is what I get from one stack of ruby ore (nether).

![output](https://user-images.githubusercontent.com/85604068/190220954-4d25b492-bbce-4e69-a45a-d7897ab50ae4.png)

Oh no, it just use a two-slot macerator recipe.

**Comment by Dream-Master** [comment]
This is intended. If we reduce it to a normal lv macerator we can disable the windmil. No one will use it anymore.

**Comment by Dream-Master** [comment]
@ChromicRedBrick @iouter

**Comment by ChromicRedBrick** [comment]
> This is intended (not sure about process time differences). If we reduce it to a normal lv macerator we can disable the windmil. No one will use it anymore.

What questbook says (Quest 1832):

> The Windmill is a grinder that uses the force of wind to macerate Items and Blocks. It is pretty slow and won't macerate ores well. **You will only get one crushed Ore from it.** However it does give you a bonus when you try to macerate other things. That bonus depends on the item inserted, for example Netherrack has a chance to give two instead of one dust and Wheat will always give one and a quarter flour.

**Comment by Shadowsoftime99** [comment]
Sounds like if anything the QB should be updated to describe what the windmill does better.

That being said, it's weird if it does OW ores 1x and Nether ores 4x. It should be either 1x/2x or 2x/4x, right?

**Comment by ChromicRedBrick** [comment]
Closing as it was fixed by the windmill rework. https://github.com/GTNewHorizons/bartworks/pull/205
