### ISSUE TITLE
Questbook Update following Keybinds

### ISSUE THREAD

**Issue by Tat0Dev** [GTNewHorizons/GT-New-Horizons-Modpack#11321]
### Your GTNH Discord Username

TheTato#7414

### Your Pack Version

2.1.2.3

### Your Proposal

QuestBook article regarding keybinds to deconflict has verbage slightly different from what's in the controls menu, making what should be deconflicted slightly confusing. For example, backpacks and adventure backpacks, Open Inventory vs Open Backpack vs B-Inventory and G-Open backpack (in the questbook).

### Your Goal

Make brand new players such as my self not feel stupid when deconflicting keybinds.

### Your Vision

Ease the earlygame stress of overwhelment felt by new players.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
can you be more specific as to the problems?

**Comment by Tat0Dev** [comment]
I can’t cite specific examples right now as I’m afk, but the problems exist
where the quest book talks about keybinds to deconflict or change, but some
keybinds the questbook refers to (such as the examples given in the ticket)
are different in the actual keybind settings of the game, making a new
player slightly confused as to what the QB is talking about.
