### ISSUE TITLE
AE2 Fluid Crafting patterns cannot be unencoded in crafting grid

### ISSUE THREAD

**Issue by greesyB** [GTNewHorizons/GT-New-Horizons-Modpack#11324]
### Your GTNH Discord Username

Greesy#2016

### Your Pack Version

2.2.0.0-RC-2

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

Unencode unneeded AE2FC patterns back into normal patterns by placing them in a crafting grid

### The Reality

They cannot be unencoded in a crafting grid (they can be with shift rclick in hand):
![image](https://user-images.githubusercontent.com/73182109/190535488-f70573af-aba1-4cc2-adc7-fc0c66cac9de.png)

Normal patterns can be:
![image](https://user-images.githubusercontent.com/73182109/190535515-72642829-1f1b-425c-87ec-6a469a2a4516.png)

### Your Proposal

Allow unencoding AE2FC patterns

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
you can hold shift and right click in air with pattern in hand in clear it.
the crafting clear recipe will be added later
