### ISSUE TITLE
Wire Factory Multiple with multiple input bus

### ISSUE THREAD

**Issue by TimberDimber** [GTNewHorizons/GT-New-Horizons-Modpack#11329]
### Your GTNH Discord Username

TimberDimber#7872

### Your Pack Version

2.2.0.0-RC-1 and 2.2.0.0-RC-2 

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Wire Factory does not accept different circuits in different input busses
Here are two different recipes, with circuit one - should make 2 wires, with circuit three - 8 fine wire
![image](https://user-images.githubusercontent.com/22298720/190827832-7e3d2b06-0b77-4551-97cf-29e997cab21f.png)
![image](https://user-images.githubusercontent.com/22298720/190827847-b4c116cc-a797-4e44-a80b-d73af4ef345f.png)
But both of them use circuit one from first input bus
![image](https://user-images.githubusercontent.com/22298720/190828031-bdb43332-1279-44c3-993b-a04ce98713c2.png)

### The Reality

Different circuits in different input busses should produce different results.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
Since I have experienced this bug too, I will add the even when using the "ignore different input buses" setting thing, this still happens
