### ISSUE TITLE
GraviSuit won't craft unless Quantum Armor fully charged

### ISSUE THREAD

**Issue by cinch** [GTNewHorizons/GT-New-Horizons-Modpack#11325]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.1.2.0

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

craft gravisuit

### The Reality

it wouldn't craft. 

for the final craft of the gravichestplate: it requires "Durability 26/27", which is fine, except: some wireless chargers don't fully charge it (for me it was 25/27).
it worked with a wireless charger mk V, but not with the previous one (think it was Mk I). 
related: now with the gravi suit it only charges to 25/27

### Your Proposal

change the recipe to allow less than full charged or fix the wireless charger to fully charge

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by cinch** [comment]
or make it so you can charge it in a regular machine like a battery, seems to only work with wireless/charge packs

**Comment by chochem** [comment]
you can charge it in a regular machine. Just needs the right tier.

**Comment by chochem** [comment]
ok tested just now. you can charge it in any EV machine and you will get to the full 26/27 as required. it also says you need it fully charged in NEI.
