### ISSUE TITLE
LTFR Fuel cannot be made in Survival

### ISSUE THREAD

**Issue by AlbertoPirillo** [GTNewHorizons/GT-New-Horizons-Modpack#11327]
### Your GTNH Discord Username

AlbyNexus#4160

### Your Pack Version

2.1.2.4-28-pre

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

The only way to make LTFR Fuel for the first time, when you cannot recycle anything depleted from the reactor (since the reactor didn't run yet) requires to make Beryllium Fluoride. The only way to get this fluid is to run Ammonium Tetraflouroberyllate in a Dehydrator, with the following recipe:
![image](https://user-images.githubusercontent.com/79864956/190664915-32a43775-4d2f-4f68-8549-9b24e0270931.png)

### The Reality

There is another dehydrator recipe, which overrides the previous one and makes Beryllium Fluoride unobtainable.
![image](https://user-images.githubusercontent.com/79864956/190665019-fccf8b68-447d-4b33-8a25-cf9c339d884f.png)
 

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AlbertoPirillo** [comment]
Let me say that we need more control over issue labels: this is a major bug as it breaks the LTFR completely.

**Comment by GTNHAfx237v7** [comment]
Duplicate of #11031

**Comment by AlbertoPirillo** [comment]
> Duplicate of #11031
Damn how could I miss it 

However, I will keep this open since it gives a better idea of what the broken recipe causes, i.e. it breaks a good portion of a quest tab. 

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11031 was opened a month ago and received no attention whatsoever from the devs

**Comment by AlbertoPirillo** [comment]
Closing as it was fixed with https://github.com/GTNewHorizons/gtplusplus/pull/345
