### ISSUE TITLE
High Density Plutonium Fuel Rod cannot produce real depleted rod when used up in reactor

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11330]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

1 high density plutonium fuel rod give 1 depleted fuel rod which can be correctly stacked and centrifuged when used up in nuclear reactor.

### The Reality

Seems it turns into a "0 stacked" depleted fuel rod. It cannot be stacked or centrifuged, and when I break the nuclear reactor block, no depleted fuel rod drops.

Video: https://youtu.be/xLsrGbBulaI

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
Duplicate of #11328

**Comment by BlueIceJAY** [comment]
I also encountered this bug,actually this is a very serious problem,Not only did it dampen the enthusiasm of nuclear power enthusiasts,but also 0 stacked item means you can copy unlimited items at 0 cost.
![@RT@`J`M_Q(B9C_G@X%P31X](https://user-images.githubusercontent.com/63415263/196606683-5695038a-63fc-4fcf-b085-3f7479076485.png)
