### ISSUE TITLE
New multiblock for make bases nicer 

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#11346]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.1.2.0

### Your Proposal

Add a new multi to do chemicals shortcuts on high tier.

### Your Goal

On middle tiers base we need to do a lot of normal and ore chemistry lines. All this lines needs tons of machines and transformers, kilmeters of wires and fluix cables. And need to dont forgot about control of this lines! All this creates lags and cant be optimized as well.
I think we need a new machine for do chemical recipes at 1 time. This machine will accept only lasers and be available on ZPM or UV tier. Recipes need to be variable like normal chemical reactor, epoxy for example epoxy, using oil processing (propene), (with mercury or without) or biomass processing (glycerol).
![image](https://user-images.githubusercontent.com/70205464/190924570-d6779f3f-12e2-42a0-af0e-cda04058f6a1.png)

![image](https://user-images.githubusercontent.com/70205464/190924587-76db0023-7ea8-4823-bc4e-8f1e5a6a1847.png)

![image](https://user-images.githubusercontent.com/70205464/190924593-f406b43a-d2bb-4016-8b4f-db72be4ab81b.png)

### Your Vision

This machine do all base nicer and less laggy.

If you need more information, ping me in Discond please.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TwoTailedFox** [comment]
![not-sure-if-serious](https://user-images.githubusercontent.com/13187606/190925936-3ff6ec33-c781-4aa8-8fc9-2d476dfe59ac.jpg)

**Comment by boubou19** [comment]
Yeah i'm not sure i get the reason why we should add a new machine for that. If you want to batch process recipes, uses the mega chemical reactor, it does already what you want. Also i'll add that most of the lag induced by chemlines are because the player usually uses inefficient ways to feed the machine.
