### ISSUE TITLE
Grid to rotate mechanism disappears at a certain angle

### ISSUE THREAD

**Issue by danbka33** [GTNewHorizons/GT-New-Horizons-Modpack#11343]
### Your GTNH Discord Username

Nuclear#4783

### Your Pack Version

2.2.0.0-RC-3

### Your Server

private

### Type of Server

Single Player

### Your Expectation

Grid is visible in any position

### The Reality

Grid is disappears at a certain angle

https://www.youtube.com/watch?v=6Z1gNsijS1Y

### Your Proposal

Fix this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
it can also sometimes lead to devastation because despite clicking on the correct side of the grid visually, the game process the information differently, so imagine having this issue on a transformer... It's very annoying.
