### ISSUE TITLE
Chisel blocks missing tooltip

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11341]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Display tooltip.

### The Reality

Some blocks' tooltip is broken:

beacon (light blue), dirt (13-15), imperialistic block (0-4), rebellious block (0-4)

![Blocks](https://user-images.githubusercontent.com/85604068/190915411-b227e6fd-13f3-441a-a33d-e75f9e436ec9.png)

like this:

![tooltip](https://user-images.githubusercontent.com/85604068/190915412-6ded24a9-658d-4921-99c0-83f63ec8516c.png)

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Yamnasm** [comment]
I'm on the Nightly build 730 and these tooltip descriptions are still missing.
Example:
![image](https://github.com/user-attachments/assets/6d0383dc-a343-4bf6-a0bb-4dd6e88b0571)
