### ISSUE TITLE
game crash when rocket is placed on rocket launcher

### ISSUE THREAD

**Issue by Sslimmm** [GTNewHorizons/GT-New-Horizons-Modpack#11358]
### Your GTNH Discord Username

Sslim#6478

### Your Pack Version

 2.2.0.0-RC-3

### Your Server

SP

### Your Actions

Placed rocket t6 (or any rocket) on rocket launcher. world crash instantly and go back to menu with the message : A fatal error has occured, this connection is terminated. Trying to reconnect to the world/restart game instantly crash as soon as the world is loaded.

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9601068/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Sslimmm** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11351

**Comment by Alexdoru** [comment]
sorry about that, it's my fault, by thanks fully it had been fixed you can download the fixed jar here https://github.com/GTNewHorizons/HoloInventory/releases
