### ISSUE TITLE
Update basic rock breaker quest

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/GT-New-Horizons-Modpack#11357]
### Your Pack Version

2200rc1

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Put a Redstone dust in stonebreaker,and it should  give me a obsidian.

### The Reality

It just give me stones even if I put redstone into ingredient slot.if I put Redstone in battery slot, the Redstone will be consumed but it will still give me a stone.

### Your Proposal

fix stonebreaker

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TwoTailedFox** [comment]
Obsidian is Circuit 1. Neither of you have set the Circuit in the bottom-right to 1.

**Comment by ChromicRedBrick** [comment]
Sorry I didn't notice that. Now it produces obsidian.

![1](https://user-images.githubusercontent.com/85604068/191051346-a3b2c5f4-9690-46b8-9462-ea07978deee4.png)


However, NEI and questbook do not mention this. Maybe need a fix.
 
![2](https://user-images.githubusercontent.com/85604068/191051476-b8b207f5-647a-4c33-bf05-16cc9bd346ed.png)
![NEI](https://user-images.githubusercontent.com/85604068/191051487-9bafb274-8bb5-4bff-8e80-f878a4a8b478.png)

**Comment by TwoTailedFox** [comment]
A request has already been made in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11063 for this to be changed to reflect the recent change.
