### ISSUE TITLE
AE can't handle supertank in void overflow mode correctly

### ISSUE THREAD

**Issue by albus12138** [GTNewHorizons/GT-New-Horizons-Modpack#11352]
### Your GTNH Discord Username

r4phael#8493

### Your Pack Version

2.2.0.0-RC2

### Your Server

private server

### Type of Server

Don't know

### Your Expectation

1. Connect supertank to ae system by fuild storage bus.
2. ME fuild input bus (ec2 & ae2fc) should drain fuilds when supertank is full and enable void overflow mode.

### The Reality

1. Connect supertank to ae system by fuild storage bus.
2. ME fuild input bus (ec2 & ae2fc) don't drain fuilds when supertank is full and enable void overflow mode.

### Your Proposal

AE should recognize supertank in void overflow mode correctly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alrightsc** [comment]
I have the same problem with AE2 dual interfaces not inserting the fluids from output to the main tank via fluid storage bus. I started using overflow covers again just so that AE2 can dump into them as normal.
