### ISSUE TITLE
WTF??? Why so dim?

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#11354]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

2.2.0.0-RC-3

### Your Server

SP, MP

### Your Expectation

why are all holograms so dim after updating from 2.1.2.4-25 to 2.2.0.0-RC-3? Yesterday I built 1 multiblock, my eyes hurt terribly to squint, either tell me how to turn it off, or turn it off yourself, it's impossible

### The Reality

fix it

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
![1](https://user-images.githubusercontent.com/61422500/190969912-a499c654-f1ba-4141-b99d-bbb487c95918.PNG)
![2](https://user-images.githubusercontent.com/61422500/190969915-f0b16299-37a5-4a79-906f-fe691ca3b514.PNG)

**Comment by Glease** [comment]
Set it to a lower value in structurelib config. Either edit the structurelib config in text editor or find structurelib's in game gui.

**Comment by FoKuCNiK** [comment]
client {

    hologram {
        # An attempt will be made to prune old holograms when a new hologram is about to be projected [range: 1 ~ 100, default: 1]
        I:maxCoexisting=1

        # An attempt will be made to remove an existing hologram if it collides with a new hologram. [default: true]
        B:removeColliding=true
    }

}

**Comment by FoKuCNiK** [comment]
I don't see anything in the config that could solve this problem.

**Comment by FoKuCNiK** [comment]
Need change HitTransparency = 1 ingame config structure lib

**Comment by Glease** [comment]
You must be editing the config file from a wrong version. It should look like this
```
client {

    hologram {
        # Ticks before a hologram disappears. [range: 1 ~ 20000, default: 400]
        I:hintLifespan=400

        # Alpha value of hologram particles. Higher the value, the more "ghostly" the hologram will appear to be. [range: 1 ~ 255, default: 192]
        I:hintTransparency=192

        # An attempt will be made to prune old holograms when a new hologram is about to be projected [range: 1 ~ 100, default: 1]
        I:maxCoexisting=1

        # An attempt will be made to remove an existing hologram if it collides with a new hologram. [default: true]
        B:removeColliding=true
    }

}
```
