### ISSUE TITLE
Cannot craft hypogen coil because need UMV solidifier

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11356]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Make hypogen coil.

### The Reality

1. Hypogen ingot needs UMV solidifier. That means at least I need an LPF with 2 UIV energy hatches.

![Hypogen](https://user-images.githubusercontent.com/85604068/191026402-312e896d-e67c-4d2a-84d1-6633ba9cea25.png)

2. Need UIV superconductor to craft UIV energy hatch.

![UIV Energy Hatch](https://user-images.githubusercontent.com/85604068/191026825-a4a68c8e-f790-48a2-916b-696a8ff875e7.png)

3. UIV superconductor base dust needs transcendent metal dust to craft.

![UIV Superconductor](https://user-images.githubusercontent.com/85604068/191027003-f3841b0d-a6d9-4c39-896d-50f70bf22336.png)

4. Transcendent metal dust needs raw tesseract.

![Transcendent](https://user-images.githubusercontent.com/85604068/191029162-9f6e8454-c306-404e-b7da-d2bc37ab13d5.png)

5. Raw tesseract needs at least a hypogen coil DTPF to make.

![Raw Tesseract](https://user-images.githubusercontent.com/85604068/191027324-52ffae0f-b675-480b-a47f-2a97ef2acb64.png)

That means I need hypogen coil to make hypogen coil.

### Your Proposal

Make hypogen solidifier recipe UIV or UEV.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
> You can use an LPF with 8 UEV energy hatches

LPF has an EU discount of 20%, solidifying hypogen needs 125,829,120 EU/t, that means at least 100,663,296 EU/t in LPF.

However, UEV energy hatch only have 67,109,376 EU capacity, not enough for this recipe.

**Comment by GDCloudstrike** [comment]
I literally tested this 5 min ago and it works
