### ISSUE TITLE
AE2FC creates random fluid packets and stalls crafts

### ISSUE THREAD

**Issue by greesyB** [GTNewHorizons/GT-New-Horizons-Modpack#11359]
### Your GTNH Discord Username

Greesy#2016

### Your Pack Version

2.2.0.0-RC-2

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

AE2FC patterns should send fluid droplets/packets as necessary when crafting

### The Reality

Using the assembly line [automation on the wiki]( https://gtnh.miraheze.org/wiki/AE2FC#/media/File:AE2FCAsslineproper.png), crafts constantly stall as scheduled after random fluid packets are created in the craft status screen. In this image, it has a single packet of 144 indalloy, instead of just having 144 indalloy, and same for 250 lubricant:
![image](https://user-images.githubusercontent.com/73182109/191090724-a3c19172-7914-46d7-88b9-f2d635886613.png)
Cancelling crafts at this stage causes the fluid packets to appear in AE as items. Restarting the craft will work as normal for a while.

This happens quite frequently, for almost any craft of more than a few items. Some discussion on discord as this is also seen by GDCloud and BlueWeabo:
https://discord.com/channels/181078474394566657/181078474394566657/1021486477428916316

### Your Proposal

Fix the fluid packets as items appearing mid-craft, as the prevent ingredients being available to the craft and cause it to stall.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
do these packets always show up when cancelling recipes or just sometimes

**Comment by GlodBlock** [comment]
also can you check whether you write fluid packets in pattern accidently, since the packets shouldn't appeared in crafting screen in normal condition. a correct pattern should display drops as input:
![image](https://user-images.githubusercontent.com/60341015/191271395-b82207bc-e9cc-44e3-9946-7c58d10f264c.png)
instead of 
![image](https://user-images.githubusercontent.com/60341015/191271762-00e01be0-cda0-4448-9750-6bfd70a0e983.png)

you can search it in pattern interminal

**Comment by greesyB** [comment]
Once the packets show in the crafting status screen they will appear in AE after the craft is cancelled as far as I can tell.
My patterns say drops, and were encoded directly with the `?` button in NEI and fluids first option enabled:
![image](https://user-images.githubusercontent.com/73182109/191278760-224977ba-e951-45f4-8b07-6c09a43a865d.png)

I captured a few more screenshots. In the first image the craft is progressing normally with full amounts of lube/indalloy, then much later the last motor hangs in scheduled as 1 packet of each lube/indalloy was created so it is now missing the drops required for the craft.
![image](https://user-images.githubusercontent.com/73182109/191278355-a72e4a96-7ad7-496d-bda8-6510a4dff9ff.png)

![image](https://user-images.githubusercontent.com/73182109/191278503-fcc33a6e-3e84-486c-8035-ef99e998250e.png)

In another craft attempt it created 1 packet of each almost immediately, then later created a second, so this time 2 motors are stalled as scheduled. It's worth noting that the drops were missing for the second before the packets showed up in the status screen, and the packets only appeared after closing and reopening the status screen.
![image](https://user-images.githubusercontent.com/73182109/191279590-d82f4e4b-a51a-4224-bc5d-8b3e67b581d4.png)
![image](https://user-images.githubusercontent.com/73182109/191280450-e8600387-c345-4149-8fa0-3cc4d0aab962.png)

These screenshots were taken out of 3 different attempts to craft 100 motors. The first time one stalled, the second time all completed normally, the third time two stalled. It is somewhat random, but consistent enough to prevent crafting at large scales.

**Comment by greesyB** [comment]
Some packets still appear even after the fix, though it does seem less than before. This is from crafting 8.2k wetwares:
![image](https://user-images.githubusercontent.com/73182109/191515836-30647a84-d321-4de8-aef8-d5dd142dffbe.png)
