### ISSUE TITLE
GT Fluid temperature seems broken

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11355]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Fluids should have correct temperature.

### The Reality

Many GT fluids temperatures are 300K,

For example:
![spacetime](https://user-images.githubusercontent.com/85604068/191006401-f1adec9e-acd1-4ef7-82c0-233a4a2e83a8.png)
![oxygen plasma](https://user-images.githubusercontent.com/85604068/191006397-064684c4-0058-4389-b8e7-ff2bc3f26a27.png) 
![Molten Cu](https://user-images.githubusercontent.com/85604068/191006395-ba7a5d6f-746a-45d0-a31a-f26bb54ef973.png)
![liquid air](https://user-images.githubusercontent.com/85604068/191006388-a7f4508d-58fd-451b-83d0-23587c8a7b29.png)

This is weird.

### Your Proposal

Fix it.

Related issue: #11220 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
And this bug is not visual. I put tin plasma into plastic fluid pipe (heat limit 350K), it did not melt.
![Tin plasma](https://user-images.githubusercontent.com/85604068/191007923-891bfb71-3ff4-4b00-972b-1685fd985870.png)

**Comment by ChromicRedBrick** [comment]
I did clean install of 2.1.2.4-29pre and 2.2.0.0-RC1.

In 29pre, GT fluids have correct temperature:

![29pre](https://user-images.githubusercontent.com/85604068/191356375-398b3517-2a59-4a07-8e8e-3d81ac47c9df.png)
![29pre2](https://user-images.githubusercontent.com/85604068/191356386-83ff0a49-d48d-4593-97cb-4330d4a120a5.png)

But in RC1 most GT Fluids become 300K:

![2200RC1-1](https://user-images.githubusercontent.com/85604068/191356397-bace2fd3-a092-4507-97c5-c5cdf3f213e0.png)
![2200RC1-2](https://user-images.githubusercontent.com/85604068/191356401-02e1a830-72ac-48ff-8c0c-a6513b6b6557.png)

Something must be broken between the two versions.

**Comment by chochem** [comment]
there was a full overhaul of the gtfluid API by @leagris between those updates. Sounds like a likely cause.

**Comment by ChromicRedBrick** [comment]
Update GregTech to 5.09.41.48 fix GT fluid temperature.

However, liquid helium is still 300K. (related issue: #11220 ) It is added by GalaxySpace via Bartworks. This need a fix too.
![Liquid Helium](https://user-images.githubusercontent.com/85604068/191474887-f871ee36-f89c-4000-bffc-e9a2591f8543.png)

**Comment by ChromicRedBrick** [comment]
Closing as it was fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/1396
