### ISSUE TITLE
Crash related to dim ID #32

### ISSUE THREAD

**Issue by idkimanerd** [GTNewHorizons/GT-New-Horizons-Modpack#11365]
### Your GTNH Discord Username

Some Nerd With A Keyboard#4823

### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Created world with cheats and ran /gamemode 2

### Crash Report

[crash-2022-09-19_17.03.13-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9603143/crash-2022-09-19_17.03.13-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
luckily thats fixed, see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10377
