### ISSUE TITLE
make monster repellators prevent bat spawns

### ISSUE THREAD

**Issue by guineawheek** [GTNewHorizons/GT-New-Horizons-Modpack#11361]
### Your GTNH Discord Username

guineawheek#9117

### Your Pack Version

pre29

### Your Proposal

title

### Your Goal

bats are annoying and i don't want to light up areas to get rid of them

### Your Vision

it'd be nice to have dark areas without hostiles _and_ bats so you can have your platline In The Dark

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
Not really doable given that bats aren't considered hostile mobs, but we do need a bat solution anyway

**Comment by guineawheek** [comment]
Also blocking all passive mob spawns (e.g. sheep/cows/chickens from grass) may be desirable behavior anyway (mobs are lag). Although at that point it's now a mob repellator, rather than a monster repellator.

(plus, the code already has special handling to deal with slime spawns because vanilla jank)
