### ISSUE TITLE
Game won't start.

### ISSUE THREAD

**Issue by Cogitorius** [GTNewHorizons/GT-New-Horizons-Modpack#11367]
### Your Pack Version

GT_New_Horizons_2.2.0.0-RC-3_(MMC)

### Your Server

SP

### Your Actions

After updating game from version: "GTNewHorizonsClient-1.7.10-2.1.2.3qf-MMC" to: "GT_New_Horizons_2.2.0.0-RC-3_(MMC)", game not start,

### Crash Report

MMC crash log: https://paste.ee/p/RWmo3

When the client starts it deletes the file: "CodeChickenLib-1.7.10-1.1.5.5.jar" from "mods" folder, and throws an error that this file is not in the folder. After copying that file to the "mods" folder situation repeats itself.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
