### ISSUE TITLE
XL Gas Turbine use incorrect calculation for some turbines

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11378]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Use huge ichorium turbines on XL gas turbine, input refinery gas (160 EU/L).

Huge ichorium turbine has 245% efficiency, overflow efficiency tier 3 and 470,400 EU/t output from optimal gas flow.

![Ichorium turbine](https://user-images.githubusercontent.com/85604068/191330283-c5378863-f14d-4a0b-85b8-9a03a148674d.png)

XL gas turbine is equal to 16x gas turbine, so optimal gas flow for refinery gas should be 19,200 L/t, with 7,526,400 EU/t output.

### The Reality

The optimal gas flow I scan is 640L/t, with 250880 EU/t output.

![refinerygas1](https://user-images.githubusercontent.com/85604068/191329949-1f6cb06d-5b51-404f-baf7-0f33e8fd9872.png)

Ichorium's output changed from 2.1.2.4-18pre to 2.1.2.4-29pre (I can't remember the exact version), so I tried huge extremely unstable naquadah turbine, its output did not change in these versions. Its output is 168,750 EU/t with 245% efficiency. In XL gas turbine the output was 2,700,000 EU/t with optimal gas flow, the value is correct.. 

It seems that XL gas turbine is still using old output calculation.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueWeabo** [comment]
This is all on normal mode correct?

**Comment by chochem** [comment]
XLs dont have fuel overflow or was that changed? how can it 'not work'?

**Comment by ChromicRedBrick** [comment]
> XLs dont have fuel overflow or was that changed? how can it 'not work'?

I thought it has overflow like LGT, because tooltip say it "runs as fast as 16 LGT"

**Comment by chochem** [comment]
last I heard it does not and was not planned either

**Comment by ChromicRedBrick** [comment]
> This is all on normal mode correct?

Yes on normal mode.

**Comment by ChromicRedBrick** [comment]
> last I heard it does not and was not planned either

OK I'll change the title then

**Comment by BlueWeabo** [comment]
I cannot find the difference between the two turbine's calculations. I think they practically do the same calculation. Its just that recently there are 2 Gas Turbines, a normal one which is only up to IV and an Advanced Version, which is for IV+, but It may have been scrapped. The turbines still exists tho.

**Comment by BlueWeabo** [comment]
Alright I have found the problem as to why the XLs use a different calculation. will be fixed shortly
