### ISSUE TITLE
Error with holoInventory

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11370]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

RC3

### Your Server

priv srv

### Your Actions

I jumped in my T7 rocket and the server disconnected me.
Rejoining kicks me instantly

### Crash Report

[holoerror_server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9606790/holoerror_server.txt)
[holoerror_client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9606791/holoerror_client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment]
This was fixed yesterday, get the updated mod here : https://github.com/GTNewHorizons/HoloInventory/releases/tag/2.1.17-GTNH

**Comment by Ethryan** [comment]
Duplicate of #11351
