### ISSUE TITLE
Energium dust is not craftable

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11379]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

RC3

### Your Server

priv srv

### Your Expectation

make energium like before with:
![image](https://user-images.githubusercontent.com/7230430/191381083-80876166-71b7-4a36-9a74-6d8a075c364b.png)

### The Reality

![image](https://user-images.githubusercontent.com/7230430/191381112-d0e7a7dd-f97d-41ee-8a66-ca85fcf123d6.png)
![image](https://user-images.githubusercontent.com/7230430/191381138-81362048-a8f9-48c9-80bb-69c1291ff193.png)
the ruby is different and the recipe is not working

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
that is fools ruby. use the proper one and it should work.
