### ISSUE TITLE
Cannot craft turbine housing

### ISSUE THREAD

**Issue by XiaoPangxie732** [GTNewHorizons/GT-New-Horizons-Modpack#11381]
### Your GTNH Discord Username

XiaoPangxie732#3938

### Your Pack Version

2.2.0.0-rc3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Craft a turbine housing

### The Reality

![image](https://user-images.githubusercontent.com/47449269/191411290-31f0fc26-0af1-4aca-8cbc-1d0b96cef412.png)
To craft a turbine housing, you need Research on Turbine Automation, which requires an ingot that cannot be crafted

Also, turbine housing does not work for sc turbines. because `SupercriticalFluidTurbine extends goodgenerator.blocks.tileEntity.base.GT_MetaTileEntity_LargeTurbineBase`, which is a copy of `gregtech.common.tileentities.machines.multi.GT_MetaTileEntity_LargeTurbine`. but turbine housing only works for turbines that extends `gregtech.common.tileentities.machines.multi.GT_MetaTileEntity_LargeTurbine`

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by XiaoPangxie732** [comment]
After some investigation, I found that this had been fixed in https://github.com/GTNewHorizons/GTplusplus/pull/307
But this fix got reverted a few days later https://github.com/GTNewHorizons/GTplusplus/commit/0d94566641d8333655f199da8068e44f90335e5b

**Comment by Dream-Master** [comment]
@Steelux8 and idea ?
