### ISSUE TITLE
ME Stocking bus and ME output bus channel issue

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11389]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

RC3

### Your Server

priv srv

### Your Expectation

The ME Stocking bus and ME output bus should use a channel to work.

### The Reality

They are working just fine without free channel
![Screenshot_10](https://user-images.githubusercontent.com/7230430/191625053-84b20659-1282-4779-81f4-f0937c4d9b21.png)
![Screenshot_9](https://user-images.githubusercontent.com/7230430/191625057-016cee9f-4f2c-41d9-b6f0-bb2acd5eecfc.png)

### Your Proposal

disable the bus when its offline

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
Seems to be working fine, reopen if still reproducible in the last release.
