### ISSUE TITLE
XL Plasma Turbines consume plasma every tick

### ISSUE THREAD

**Issue by pulsemageadvocate** [GTNewHorizons/GT-New-Horizons-Modpack#11384]
### Your GTNH Discord Username

pulsemageadvocate

### Your Pack Version

2.2.0.0-RC-3, GT-PlusPlus-1.7.10-1.7.100-2-gb4ce97b.jar

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

XL Plasma Turbines consume plasma every second.

### The Reality

XL Plasma Turbines consume plasma every tick.

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
I updated GTPlusPlus to 1.7.101 and had this problem too. 

It seems that XL plasma turbine treat plasma overflow EU/s as EU/t, and consumes 20 times the fuel while generating the same EU/t as before. Something went wrong in https://github.com/GTNewHorizons/GTplusplus/pull/357.

**Comment by BlueWeabo** [comment]
Are you sure that its coming from my PR and not somewhere else? As the XLs were consuming plasma every tick before my PR, (As I had to test other bugs too)

**Comment by ChromicRedBrick** [comment]
> Are you sure that its coming from my PR and not somewhere else? As the XLs were consuming plasma every tick before my PR, (As I had to test other bugs too)

I replaced GT-PlusPlus-1.7.10-1.7.101.jar with GT-PlusPlus-1.7.10-1.7.100.jar, and tested. In 1.7.100, XL plasma turbine consumes fuel every second, not tick (However the scanner shows optimal flow in L/t, but this is another visual bug, imo).

**Comment by BlueWeabo** [comment]
okay I found out why. apparently only the plasma turbine consumes plasma every second instead of everytick. Gonna fix it rn
