### ISSUE TITLE
Fastcraft crash

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11383]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

RC3

### Your Server

priv srv

### Your Actions

This crash happened to me randomly when i was running around the base.
I dont know how to reproduce, it only happened once.

### Crash Report

[crash-2022-09-21_14.29.41-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9616981/crash-2022-09-21_14.29.41-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
