### ISSUE TITLE
Crash after updating version

### ISSUE THREAD

**Issue by Gigaca1** [GTNewHorizons/GT-New-Horizons-Modpack#11380]
### Your GTNH Discord Username

Gigacal#3539

### Your Pack Version

2.2.0.0 RC3

### Your Server

SP

### Your Actions

I copied my world over from 2.1.2.0 to 2.2.0.0 RC3

### Crash Report

https://paste.ubuntu.com/p/XHHSMD3Hj7/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by eigenraven** [comment]
Can you provide the full logs? The crash report doesn't point to anything specific

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
