### ISSUE TITLE
Stackable Reactor Vents

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#11398]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.2.0.0-RC3

### Your Proposal

To have Reactor Vents of the same durability able to stack in the player's inventory while ensuring that they remain unstacked in reactors.

### Your Goal

To remove having to use filing cabinets to force Reactor Vents to stack

### Your Vision

To ensure that player inventory is used more efficiently.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Szajkop** [comment]
Reactor platings also could use the same stacking rule
