### ISSUE TITLE
Wallsharing XL plasma turbines

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11390]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

RC3

### Your Proposal

In my testing i managed to build 2 XL plasma turbines together with a 3 deep wallshare. Its working fine and both generating power.

![xl wallshare](https://user-images.githubusercontent.com/7230430/191625360-0cbe2c02-b38d-458c-93a2-8be508195cb0.png)

### Your Goal

Check that this is legal or not and adjust the code/balance it accordingly.

### Your Vision

In my opinion this looks cool but it uses less turbine items and much less building materials to reach double output.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
I'd say this is a bug since the rotor assembly already have logic to connect to a controller, but it ignores if it already has one when adding to the controller list.
