### ISSUE TITLE
Forbidden magic overwrote the corrupting enchantment id with the default value

### ISSUE THREAD

**Issue by albertopirillo** [GTNewHorizons/GT-New-Horizons-Modpack#11402]
### Your GTNH Discord Username

AlbyNexus#4160

### Your Pack Version

2.2.0.0-RC-3

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Actions

Start the server

### Crash Report

Fun fact: I updated the pack yesterday and everything worked fine. (Of course, I had to manually fix the hodgepodge problem).
From this morning, the server keeps crashing.

[Crash report](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9632769/crash-2022-09-23_09.59.06-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by eigenraven** [comment]
Corrupting should be enchantment id 125, can you check if your forbidden magic config matches the config file from the pack? See <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/ForbiddenMagic.cfg#L28>

**Comment by AlbertoPirillo** [comment]
It does not: in my file the Corrupting enchantment has id 71.
Which is weird since I did not edit it.

**Comment by AlbertoPirillo** [comment]
I edit the id back to 125. 
Server is working now, thanks.

**Comment by AlbertoPirillo** [comment]
As I said, server is working, but I cannot join it with the client.
I've created another ticket: #11403
Labeled it as "crash" since it is impossible to play.

**Comment by albertopirillo** [comment]
Closing as it was probably induced by file corruption on my side.
