### ISSUE TITLE
Molten Steel from TiC melting Can't be used in Fluid Solidifier

### ISSUE THREAD

**Issue by YasenGaming24** [GTNewHorizons/GT-New-Horizons-Modpack#11407]
### Your GTNH Discord Username

LazyFlesh#4533

### Your Pack Version

2.2.0.0 RC 3

### Your Proposal

I propose either changing it so TiC fluid can be used in the solidifier, or purring a warning on at least the LV one that stuff from the smeltery can't be used in it.

### Your Goal

I made a solidifier thinking it could use the Tic fluid, wasting time and resources.

### Your Vision

It could help people not waste resources thinking it would work, like me. Not much else.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
this is in gt tiering so we are not gonna unify those fluids. But a warning somewhere in a quest makes a lot of sense if there really is none.
