### ISSUE TITLE
Infinity booster bug

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#11411]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

Bug from all versions 

### Your Server

Eta

### Type of Server

Thermos

### Your Expectation

Trying to use Wireless Crafting Terminal.

### The Reality

After scrolling Infinity Booster Card randomly moving into cursor slot or drops into world. After that you cant open terminal to return it into slot or it fall into lava or void.

### Your Proposal

Add button to lock card slot.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by eigenraven** [comment]
This has already been fixed with <https://github.com/GTNewHorizons/WirelessCraftingTerminal/pull/21> and <https://github.com/GTNewHorizons/WirelessCraftingTerminal/pull/23>
