### ISSUE TITLE
Some Assembler recipes can use any trophies though asking for one specific trophy

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11412]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Use trophies to craft leather in an assembler.

### The Reality

Though the recipe asks for a cow trophy, literally any trophy works in this recipe.

Same with other recipes using a trophy.

Video: https://youtu.be/Yx_y-H-gdAg

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
the recipe seems to be defined correctly. Now in RA2 but the behaviour is the same.

can GT not handle NBT tags in machine recipes? So either GT recipes/recipe checks need a fix here, or if that is not possible we need to replace these recipes by something very different.
