### ISSUE TITLE
Improvements for batterybuffer info in Waila

### ISSUE THREAD

**Issue by MireskaleFay** [GTNewHorizons/GT-New-Horizons-Modpack#11419]
### Your GTNH Discord Username

Mireska_le_Fay#6221

### Your Pack Version

2.1.2.3qf

### Your Proposal

Add an existing (at least in GT IMPACT) feature to show full (with batteries and intertnal buffer) charge of a battery buffer, income and outcome ATM in Waila

### Your Goal

Kinda smart and usefull, imho (much smarter and less buggy than NC inf panel)

### Your Vision

Nice and smart small improvement, e.g.
![image](https://user-images.githubusercontent.com/113138431/192121844-16573018-04a0-489c-8c4d-a4e91400db76.png)

Sry for the Russian interface.
The info is following:
Used capacity
Total capacity
Income (EU/t)
Outcome (EU/t)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by greesyB** [comment]
There may be some other worthwhile improvements in Impact's fork of WAILAPlugins to check as well https://github.com/GT-IMPACT/WAILAPlugins
