### ISSUE TITLE
Some gregified recipes for tools and armors are broken now

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11413]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Some recipes should be gregified.

### The Reality

Some recipes now use vanilla version. All of them are fine in 29pre, but broken in RC3.

For Example:
(I ran two instances on my PC, the left is 2.2.0.0-RC-3, the right is 2.1.2.4-29pre)
![golden-sword](https://user-images.githubusercontent.com/85604068/192109195-53456efe-f2da-416d-a69c-1376927d32eb.png)

Vanilla Minecraft tools (except pickaxe) cannot be arc furnaced in RC3:
![tools](https://user-images.githubusercontent.com/85604068/192109261-d4876562-ad0a-4440-837f-745573a87de3.png)

Items with wrong recipes are all tools and armors. As far as I could tell, affected materials are iron, gold, thaumium, fiery, ironwood, steeleaf, dark steel, steel (armors from RailCraft), knightmetal.

All of their arc furnace recipes are broken as well, and diamond tool and armors arc furnace recipes are broken too.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
Twilight Forest armors and tools recipes still not fixed now. :(

(including fiery, ironwood, steeleaf, knightmetal, as far as I know)

The left is 2.2.0.0, the right is 2.1.2.4-29-pre.
![ironwood](https://user-images.githubusercontent.com/85604068/192969046-81c01a66-6616-4e51-bcee-ae2954f33ebd.png)

**Comment by Dream-Master** [comment]
@Glease any idea why other mods not supported anymore ?
