### ISSUE TITLE
Muffler Hatch (MV) recipe difference

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/GT-New-Horizons-Modpack#11410]
### Your GTNH Discord Username

DragScorpion

### Your Pack Version

2.1.2.3QF

### Your Server

SP

### Your Expectation

Shaped Crafting:
MV Machine Hull; Electric Motor (MV)
Steel Fluid Pipe; Steel Rotor

Assembler:
MV Machine Hull; Large Steel Fluid Pipe; Steel Rotos; Electric Motor (MV);Programmed Circuit 3

![javaw_1yzAflnN4m](https://user-images.githubusercontent.com/9047664/192095658-c4d7f24c-a41b-43c5-89cd-6531673e5760.png)
![javaw_CQ0A8pDJwE](https://user-images.githubusercontent.com/9047664/192095667-ce9ec148-fbbf-4d64-9aa6-3b275bf70fdd.png)

### The Reality

---

### Your Proposal

Changed the Large Steel Fluid Pipe (Assembler) to Steel Fluid Pipe (shaped)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/986
