### ISSUE TITLE
Perfromance Issue on Server Side

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/GT-New-Horizons-Modpack#11425]
### Your Pack Version

2200RC2

### Your Proposal

Add some mixins to prevent unnecessary loading of chunk when ai of entities runs.
When playing I found the tps of server is so low that I can saw bunches of messages like:
```
[10:55:17] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4262ms behind, skipping 85 tick(s)
[10:55:31] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3046ms behind, skipping 60 tick(s)
[10:55:50] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3755ms behind, skipping 75 tick(s)
[10:56:05] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4381ms behind, skipping 87 tick(s)
[10:56:20] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2366ms behind, skipping 47 tick(s)
[10:56:37] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2722ms behind, skipping 54 tick(s)
[10:56:57] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 4045ms behind, skipping 80 tick(s)
[10:57:13] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3006ms behind, skipping 60 tick(s)
[10:57:29] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3582ms behind, skipping 71 tick(s)
[10:57:49] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 6498ms behind, skipping 129 tick(s)
[10:58:04] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3453ms behind, skipping 69 tick(s)
[10:58:19] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3014ms behind, skipping 60 tick(s)
```
on the console.
As it says, there was a 'cant keep up' printed every 15-30 seconds. And top -Hp showed that server thread kept using almost 100% of cpu, and File IO Thread kept using nearly 30%-40%, when there was only one or no player in the server. 
So I used a tool called arthas to get flame graph of a running server. As the screenshot showed, the entity ai costed a lot of cpu(more than 33% of cpu time on server thread).
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/57739338/192171707-18cc7e8c-678a-4ade-9b7c-c9298a849bd3.png">

After reading the source code of minecraft, I found 2 boolean variables controlled the loading of chunk.
```
public Chunk provideChunk(int p_73154_1_, int p_73154_2_) {
        Chunk chunk = (Chunk)this.id2ChunkMap.getValueByKey(ChunkCoordIntPair.chunkXZ2Int(p_73154_1_, p_73154_2_));
        return chunk == null ? (!this.worldObj.findingSpawnPoint && !this.chunkLoadOverride ? this.dummyChunk : this.loadChunk(p_73154_1_, p_73154_2_)) : chunk;
    }
```
It says if no such chunk corresponding to the given chunkcoord, and findingSpawnPoint is true or chunkLoadOverride is true, a chunk will be loaded from disk. 
Through grep command I find variable findingSpawnPoint is default false, and it is changed to true when called 'createSpawnPosition' in WorldServer.java and set back to false when returned. And initial value of chunkLoadOverride is true, and it's only referred in provideChunk.

The func_72865_a before constructor of ChunkCache is called getPathEntityToEntity, it calculates the path between 2 entities, after build a cache of chunks. In constuctor of ChunkCache, the chunks between (ChunkX1, ChunkZ1) and (ChunkX2, ChunkZ2) are get from getChunkFromChunkCoords, and getChunkFromChunkCoords just calls provideChunk of ChunkProviderServer. Because default value chunkLoadOverride is true, it will just try to load chunks from disk, if the cache missed.

So I tried to remove reference of chunkLoadOverride from provideChunk through such mixin:
```
package dev.youtiao.mixins;

import net.minecraft.util.LongHashMap;
import net.minecraft.world.ChunkCoordIntPair;
import net.minecraft.world.WorldServer;
import net.minecraft.world.chunk.Chunk;
import net.minecraft.world.gen.ChunkProviderServer;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Overwrite;
import org.spongepowered.asm.mixin.Shadow;

/**
 * @author koiNoCirculation
 */
@Mixin(ChunkProviderServer.class)
public abstract class MixinChunkProviderServer {
    @Shadow
    private LongHashMap id2ChunkMap;

    @Shadow
    private WorldServer worldObj;

    @Shadow
    private Chunk dummyChunk;

    @Shadow
    abstract Chunk loadChunk(int p_73154_1_, int p_73154_2_);

    @Overwrite
    public Chunk provideChunk(int p_73154_1_, int p_73154_2_) {
        Chunk chunk = (Chunk)this.id2ChunkMap.getValueByKey(ChunkCoordIntPair.chunkXZ2Int(p_73154_1_, p_73154_2_));
        return chunk == null ? (!this.worldObj.findingSpawnPoint ? this.dummyChunk : this.loadChunk(p_73154_1_, p_73154_2_)) : chunk;
    }

}
```
And it just worked, the server is no longer laggy, now I am testing if there are another side effects.
Flame graph after the mixin,it shows the chunkload part just disappear:
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/57739338/192173437-39a9f5d2-3bbf-4038-ae9b-85639cb216f2.png">

### Your Goal

To prevent drop of tps on servers.

### Your Vision

You will not be defeated by Creeper King on Mars due to lags :).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by koiNoCirculation** [comment]
And the EventHandlerEntity of Thaumic Horizons is also a lag source, it kept calling getStackTrace(), looks like it's preventing recursive calls, but I found no recursive call of "applyNewAI". So I think this call of getStackTrace() should be removed, because it costs a lot when loading chunks. As the following screenshot shows, getStackTrace() costs more than half of time of stage 2 when loading chunks.
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/57739338/192174225-14e13aa6-eff8-4ed0-a96f-228a055e98c3.png">

```
public void applyInfusions(EntityLivingBase entity) {
        StackTraceElement[] above = Thread.currentThread().getStackTrace();
        EntityInfusionProperties infusionProperties = (EntityInfusionProperties)entity.getExtendedProperties("CreatureInfusion");
        int[] infusions;
        int i;
        if (entity instanceof EntityPlayer) {
            infusions = infusionProperties.getPlayerInfusions();
            for(i = 0; i < infusions.length; ++i) {
                if (infusions[i] != 0 && infusions[i] == 8 && !entity.field_70170_p.field_72995_K) {
                    this.warpTumor((EntityPlayer)entity, ThaumicHorizons.warpedTumorValue - infusionProperties.tumorWarpPermanent - infusionProperties.tumorWarp - infusionProperties.tumorWarpTemp);
                }
            }

            this.applyPlayerPotionInfusions((EntityPlayer)entity, infusions, infusionProperties.toggleInvisible);
            if (!entity.field_70170_p.field_72995_K) {
                PacketHandler.INSTANCE.sendToAll(new PacketPlayerInfusionSync(entity.func_70005_c_(), infusions, infusionProperties.toggleClimb, infusionProperties.toggleInvisible));
            }
        } else {
            StackTraceElement[] var8 = above;
            i = above.length;

            for(int var6 = 0; var6 < i; ++var6) {
                StackTraceElement el = var8[var6];
                if (el.getMethodName().equals("applyNewAI")) {
                    return;
                }
            }

            infusions = infusionProperties.getInfusions();

            for(i = 0; i < 12; ++i) {
                if (infusions[i] != 0) {
                    PotionEffect effect;
                    if (infusions[i] == 1) {
                        effect = new PotionEffect(Potion.field_76430_j.field_76415_H, 2147483647, 0, true);
                        effect.setCurativeItems(new ArrayList());
                        entity.func_70690_d(effect);
                    } else if (infusions[i] == 3) {
                        effect = new PotionEffect(Potion.field_76428_l.field_76415_H, 2147483647, 0, true);
                        effect.setCurativeItems(new ArrayList());
                        entity.func_70690_d(effect);
                    } else if (infusions[i] == 4) {
                        effect = new PotionEffect(Potion.field_76429_m.field_76415_H, 2147483647, 0, true);
                        effect.setCurativeItems(new ArrayList());
                        entity.func_70690_d(effect);
                        ThaumicHorizons.instance.renderEventHandler.thingsThatSparkle.add(entity);
                    } else if (infusions[i] == 8 && !entity.getEntityData().func_74764_b("runicCharge")) {
                        entity.getEntityData().func_74768_a("runicCharge", 6);
                    } else if (infusions[i] == 7) {
                        this.applyNewAI((EntityLiving)entity);
                    }
                }
            }
        }
    }
```

**Comment by koiNoCirculation** [comment]
Before mixin:
Can't keep up reported, Server Thread costs 60% of cpu, sometimes nearly 90%, and File IO Thread costs more than 30% of cpu when no one's in the server.
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/57739338/192174374-82221b62-d621-4633-aedb-a15e838cdef1.png">
After applying the mixin, cpu cost of Server Thread is only below 20%, not 0% because some chunks are permanently loaded by FTBU.
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/57739338/192174828-6f0e2794-c398-42c0-b033-d71ca934bf7a.png">

**Comment by mitchej123** [comment]
Nice. Thanks for the investigation.  A few questions:
  
Are you running a dedicated server? (Assuming yes)
Fastcraft?
Thermos?
Other non forge environment?

**Comment by koiNoCirculation** [comment]
@mitchej123 vanilla forge server.

**Comment by mitchej123** [comment]
I think fastcraft (🤮 and thermos) patch some of these.  That being said, we should offer some patches for vanilla forge servers and this should help with that.

**Comment by koiNoCirculation** [comment]
@mitchej123 I am just using official GTNH pack :(, so I don't think it contains Fastcraft or some other patch mods.

**Comment by mitchej123** [comment]
Fastcraft is included in the client.  It's a mixed bag for the server. But i use it locally and would recommend it.

These patches won't make the stable but maybe the one after

**Comment by koiNoCirculation** [comment]
@mitchej123 In addition I think replacing EventHandlerEntity of thaumic horizons will also work, because you know, getStackTrace costs a lot :(. I think it's foolish to detect recursive call with stack traces.
