### ISSUE TITLE
LCR and PA lose locked recipe data when reentering the game

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11420]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Lock recipe for LCR.

### The Reality

When reentering the game, it lost locked recipe data and started to do another recipe and locked that one.

Video: https://youtu.be/Bj-Hw2jd38s

Also tested on PA, it lost locked recipe data too.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
It seems like the machines only save that they have a recipe locked, but not which :kekw:

**Comment by Glease** [comment]
Actually there isn't a lot of ways around this, unless we can somehow give each recipe a persistent identifier.
