### ISSUE TITLE
RC4 AE2 network cannot form

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11429]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

RC4

### Your Server

priv srv

### Your Expectation

Use AE2 just like before

### The Reality

After upgrading to RC4 the main ae2 network cannot initialize properly. 
It looks like the network is constantly trying to recalculate itself because sometimes for a few seconds all the connection is established but then everything falls apart, ME p2ps cannot connect to the main controller.
I cant see any error output or anyting related in the log files.
![image](https://user-images.githubusercontent.com/7230430/192281765-c12f9670-93b4-4ef9-8831-b4ac4b67b96d.png)

when the network is "broken":
![image](https://user-images.githubusercontent.com/7230430/192282399-afbc20a9-aba8-4f51-9ec3-0232ce4258fa.png)

then it finds itself for a few seconds:
![image](https://user-images.githubusercontent.com/7230430/192282648-1d3fbff4-fc83-46dd-864c-10b843211155.png)

and it goes back to the broken state after a few seconds. It seems like the ME p2p carrying network breaks too, network tool shows no devices when probing at the broken state

My smaller subnets are running fine/i didnt notice any issue

### Your Proposal

fix/check

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
Are you using long distance Wireless connectors from AE2 stuff ?

**Comment by Szajkop** [comment]
> Are you using any long distance Wireless connectors from AE2 stuff ?

Only 1 at the cleanroom

**Comment by Hikari1nVoid** [comment]
Used to have the same problem before and pretty sure it's not an RC4-exclusive bug.Definitely need some logs.

**Comment by Szajkop** [comment]
i cannot replicate this issue when loading the world in SP. Only the server is not happy with something

**Comment by Szajkop** [comment]
done some more testing:
I tried
- removing all backbone cables
- disconnecting network parts
- downgrading ae2 back to rc3 version
nothing fixed the server issue.

other note: when i teleported to OW from garden the whole server become unresponsive, i couldnt even run opis. tick times were around 800ms. This behavior seems reproduceable, every time i go to OW it slows to this almost dead phase and when i go back to garden it returns to normal tick times. Maybe is there something i can dump out for debugging?

**Comment by boubou19** [comment]
can you upload the map somewhere? having a solid reproductible setup would help us greatly to understand what's going on

**Comment by eigenraven** [comment]
> when i teleported to OW from garden the whole server become unresponsive, i couldnt even run opis. tick times were around 800ms. This behavior seems reproduceable, every time i go to OW it slows to this almost dead phase and when i go back to garden it returns to normal tick times
Are you sure 100% of your base is chunkloaded? it's possible something is loading and unloading chunks every tick. If you could capture a profiler trace (visualvm might be the easiest to obtain from the server while it's lagging) of the lag spike that would be useful

**Comment by Szajkop** [comment]
I cannot use visualVM. the server is running on a dedicated linux machine without display and my notebook is not capable of running both the server and the client at the same time.

for the world download, ill pack up the whole server and upload it in a few minutes

**Comment by mitchej123** [comment]
As a heads up, you can run visualvm on your laptop, and connect to the instance on the server, via a SSH tunnel

**Comment by Szajkop** [comment]
managed to hook up visualvm to find out that the chunk loading/unloading cripples the server. i managed to fuk up the chunkloading configuration while migrating from RC3 and this caused the issue. after every dim was correctly chunk loaded this issue gone.
