### ISSUE TITLE
Issues encountered trying to start a 2.2.0.0-RC4 server

### ISSUE THREAD

**Issue by cheide** [GTNewHorizons/GT-New-Horizons-Modpack#11424]
### Your GTNH Discord Username

HalibutBarn#9882

### Your Pack Version

2.2.0.0-RC4

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Actions

After downloading and extracting the server package for 2.2.0.0-RC4, the following problems were encountered trying to start the server on a Linux system:

1. Missing files.
The server package does not contain the 'forge-1.7.10-10.13.4.1614-1.7.10-universal.jar', 'minecraft_server.1.7.10.jar', and 'startserver.*' files.
Workaround: These files were copied from an earlier 2.1.2.3qf install.

2. Launch error about missing classes.
With the server .jar files in place, attempting to launch the server produces the error:

> We appear to be missing one or more essential library files.
> You will need to add them to your server before FML and Forge will run successfully.java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
>         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>         at java.lang.Class.forName0(Native Method)
>         at java.lang.Class.forName(Class.java:348)
>         at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:25)
>         at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12)

Workaround: The 'libraries' directory was copied from an earlier 2.1.2.3qf install.

3. Fatal error about missing 'journeymap' jar file.
After launching the server, it produces the error:

> [12:26:28] [main/ERROR] [Hodgepodge/]: CRITICAL ERROR: Could not find required jar journeymap.  If this mod is not required please remove it from the 'requiredMods' section of the config.

and stops running.
Workaround: Changed the S:requiredMods entry in config/hodgepodge.cfg from 'journeymap' to 'journeymapserver'. This entry doesn't appear in the file until the server has been launched at least once to get the above error.

With these workarounds, the server then launches successfully.

### Crash Report

See messages above

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
basically, i don't know what license rules the jars, so they aren't included in the server pack.

@Dream-Master i thought you changed the server config for RC4 to make them boot? or was it only zeta?

also @Alexdoru looks like your sided mixin failed

**Comment by Dream-Master** [comment]
@boubou19 you must pack the jar inside the server  jar.
the hodgepodge config is different then the client one. We use a different version of Journeymaps on server and client.
The start server files we can add i guess (sh and bat files)

**Comment by boubou19** [comment]
files required to boot the server out of the box will be availiable for any server version generated after this PR: https://github.com/GTNewHorizons/DreamAssemblerXXL/pull/74

**Comment by mitchej123** [comment]
Hodgepodge should mark journeymap as not required in target mods.  That will fix it for now

**Comment by cheide** [comment]
All issues are resolved with the final GT_New_Horizons_2.2.0.0_SERVER.zip package. Thanks!
