### ISSUE TITLE
Some super glue ingredients has no LCR

### ISSUE THREAD

**Issue by tankobuman** [GTNewHorizons/GT-New-Horizons-Modpack#11428]
### Your GTNH Discord Username

tnkB#4563

### Your Pack Version

2.2.0.0-RC-4

### Your Server

SP

### Your Expectation

Super glue line can be made without single block chemical reactor

### The Reality

"Copper(Ⅱ) sulfate dust" and "Sodium cyanide dust" have no LCR recipe
![2022-09-26_19 56 20](https://user-images.githubusercontent.com/90376144/192263690-4aa6cd8f-f916-4904-a299-55ef32ce7074.png)
![2022-09-26_20 01 44](https://user-images.githubusercontent.com/90376144/192263705-5c644f1a-8ed6-40fc-b94e-1473d5aa2997.png)

### Your Proposal

Please add these LCR recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by POPlol333** [comment]
I though it was fixed?

**Comment by POPlol333** [comment]
because when I learned about that and asked if it was gonna be fixed someone (don't remember) told me that he'll do it

**Comment by tankobuman** [comment]
still no recipe on stable
