### ISSUE TITLE
Infusion Enchanting can break ench level limit

### ISSUE THREAD

**Issue by s9hysky** [GTNewHorizons/GT-New-Horizons-Modpack#11438]
### Your GTNH Discord Username

s9hy_sky#5884

### Your Pack Version

2.1.2.4

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Infusion Enchanting for items.It shouldn't break the ench level limit.

### The Reality

Prepare two items of the same kind(like two swords),one of them has reached the upper limit of enchanting,and the other can still enchant.
For example,prepare a looting III iron sword and a iron sword without enchantment,put the no ench sword on center pedestal,and put a hopper point to center pedestal,put the looting III sword in the hopper.
Start Infusion Enchanting for looting,and remove sword from center pedestal,looting III sword will take its place.Wait until the infusion is completed,looting III will increase to IV.Repeating the process can make the enchanting level very high

### Your Proposal

Fix it.Make it can't to break through the limit.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
Completed, closing
