### ISSUE TITLE
Overchanting Table can increase enchanting level infinitely on any item

### ISSUE THREAD

**Issue by s9hysky** [GTNewHorizons/GT-New-Horizons-Modpack#11437]
### Your GTNH Discord Username

s9hy_sky#5884

### Your Pack Version

2.1.2.4

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Overchanting Table can increase enchanting level to the maximum level+1

### The Reality

If you overchant a spike(from exu),put it in world and break it,it can be overchant again.Like #2387
Use Disenchanter(from DE) you can get a ultra high level enchanted book from it.
Use Mana Enchanter(from BOT),now can put the ultra high level ench on any item.
You can also leave spikes,just overchant any worthless item->disenchant->mana enchant another worthless item->overchant...
to get a high ench level.
This will lead to some resource get too easy.Like put a high looting level weapon in EEC,you can get 100x drop even more.

### Your Proposal

Change Overchanting Table code,no longer give items "overchants"nbt but check the limit of enchanting level.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
Completed, closing
