### ISSUE TITLE
Salt Recipe not working

### ISSUE THREAD

**Issue by IsOobt** [GTNewHorizons/GT-New-Horizons-Modpack#11436]
### Your GTNH Discord Username

oobt#8431

### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Your Expectation

Tried crafting salt with mortar and salt ore. I am not using rock salt and the salt ore was above the mortar like in the recipe.

### The Reality

The recipe does not output salt; the output slot remains empty. Yes, I am putting the salt ore directly above the mortar like the recipe states, but it is not working. I know I am also not accidentally using rock salt ore. I used NEI to autofill the recipe multiple times, but it is just not working.

### Your Proposal

I want to know if Im doing something wrong, or if the recipe just needs to be fixed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/193480566-a2f30708-0bc4-4f4e-8c6f-05b003636645.png)
works just fine on 2.2.

If it really doesnt work for you, then you should update. But I am pretty sure it also worked in 3qf.
