### ISSUE TITLE
Lag source (betterquesting?)

### ISSUE THREAD

**Issue by realthecaffiend** [GTNewHorizons/GT-New-Horizons-Modpack#11432]
### Your GTNH Discord Username

thecaffiend#2253 

### Your Pack Version

2.1.2.3qf  (Some config changes, no recipe changes)

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Betterquesting would not eat 12 seconds in a single tick due to checking something about my nano goggles

### The Reality

![image](https://user-images.githubusercontent.com/8347355/192387220-3d360f6d-8a1c-4221-be02-130467257d20.png)

(Full profile at https://spark.lucko.me/mYwzglutmq , made with --only-ticks-over 10000, so it should be ignoring ticks under 10 seconds (Yes, ten seconds))

We have a recurrent lagspike that seems to get worse and worse until the server is rebooted, so I went looking with a profiler today. I found the above information; it looks to me like BQ is for some reason firing something that is consuming giant tick time, every time my nano goggles discharge? I get that it has to scan inventory but

a) Why interact with equipped items at all
b) Am I misreading this, or is BQ firing every time anything charges or discharges?
c) How in the world is an oredict match consuming 12 seconds?
d) is it my imagination that the reboot helps somehow? Or is there some memory problem? 

### Your Proposal

Don't consume incredible amounts of tick time trying to match my hat to a quest item every time it uses 1 EU

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Should be fixed by https://github.com/GTNewHorizons/StandardQuestingPack/pull/18. Can you update the mod to see if it's actually mitigated? http://jenkins.usrv.eu:8080/job/StandartExpansion/70/

**Comment by realthecaffiend** [comment]
Hey thanks, I replaced the file with StandardExpansion-1.7.10-3.0.197-GTNH-1-g4a5871a.jar here today, I'll update this presumably tomorrow: If the ugly lagspikes happen, they tend to take about a day to become apparent. I'll run a profile with --only-over again if they do show up

This seems like mitigation and a good general change, though I also admit questions how in the world that process consumed 12 seconds regardless

**Comment by eigenraven** [comment]
@realthecaffiend ideally update both betterquesting and standardquestingpack to their newest releases from github, both had optimizations done to solve this issue

**Comment by realthecaffiend** [comment]
http://jenkins.usrv.eu:8080/job/BetterQuesting/ and BetterQuesting-1.7.10-3.0.367-GTNH-4-g021aab4.jar I assume? I can do that, it's just I'd rather do it all in one shot, updating players packs for the server is kind of tedious due to custom configs and the fact we are already using a few custom mods to avoid bugs: Would that be all?

**Comment by eigenraven** [comment]
Jenkins builds (from origin/master) work too, I was talking about github releases (which is the builds the pack is assembled from): <https://github.com/GTNewHorizons/StandardQuestingPack/releases/tag/3.0.197-GTNH>, <https://github.com/GTNewHorizons/BetterQuesting/releases/tag/3.0.368-GTNH>

**Comment by realthecaffiend** [comment]
Update, I completed a quest today (naq reactor V, if it matters) grabbing some from my AE network, and the entire server crashed (https://termbin.com/6vid crash report0 with an NPE from BQ. 

Is this from updating just the standardquestingpack mod? I'll update BQ if I absolutely must but I realized that this rolls in the view mode change that I have nothing but negative opinions about :/

**Comment by eigenraven** [comment]
yes, it's because you only updated one. the view mode change was done to the quests json, not the bq mod

**Comment by realthecaffiend** [comment]
The server also now crashes when I rejoin if, say, the auto-reboot happened before I got around to replacing BQ 😅  

Now rebooting with:
StandardExpansion-1.7.10-3.0.197-GTNH.jar
BetterQuesting-1.7.10-3.0.368-GTNH.jar
From github

**Comment by realthecaffiend** [comment]
Thanks for the bugfixes folks: I've ran several profiles since then trying to run down any lag sources, and taken down some setups etc but this one hasn't occurred at all.

Now my players and I do crash to desktop on trying to click something in the questbook for a recipe, but we've chalked that up to updating these two mods and not other dependencies and it's pretty trivial to avoid (don't do it)

As I understand the fix, this avoids loading up the armor (among other items) to compare to the questbook pending rewards, would this solve it if you had the relevant armor still pending as a reward? Just wondering how it managed to eat this much time in the check regardless and if it will not be more rare, but still a problem?

**Comment by eigenraven** [comment]
There were a few fixes:
 - Delaying NBT check until after the other checks (id, metadata) were done, as NBT comparison is much slower than just checking item IDs
 - Rewrite the detection code to do much less memory allocations, reducing GC pressure
 - Delay scanning the inventory until the end of the game tick, so that it can only run once per tick and not every time an item sends the inventory updated event (which can be very frequent per tick, like with ic2 armor due to its bad implementation most likely)
