### ISSUE TITLE
Distillation tower GUI texture has not been updated with config slot

### ISSUE THREAD

**Issue by dvdmandt** [GTNewHorizons/GT-New-Horizons-Modpack#11430]
### Your GTNH Discord Username

DvDmanDT#3943

### Your Pack Version

2.2.0.0-RC4

### Your Server

My own

### Type of Server

Vanilla Forge

### Your Expectation

Show in the GUI that there's a slot to place a config circuit in. 

### The Reality

![image](https://user-images.githubusercontent.com/11985732/192291924-f0a07641-d53e-4040-97a6-bd6678f7afaa.png)

Right now they can be placed in the top right corner, over the structure check thing, but there's no visible slot there.

### Your Proposal

Update the texture so that it's visible that a config circuit can go in there.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
Same with Pyrolyse Oven.
![Pyrolyse Oven GUI](https://user-images.githubusercontent.com/85604068/192295006-fea5229a-f022-46fc-9881-9c5bd785cd26.png)
