### ISSUE TITLE
Cooking For Blockheads kitchen cannot find/use items in storage drawers

### ISSUE THREAD

**Issue by Superfrogman98** [GTNewHorizons/GT-New-Horizons-Modpack#11444]
### Your GTNH Discord Username

Superfrogman98#8329

### Your Pack Version

2.2.0.0-Stable

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

After updating was trying to craft food using the Cooking for Blockheads kitchen with items stored in connected Storage Drawers 

### The Reality

Kitchen doesn't use or find items inside of drawers for recipes after updating. It does still seem to treat the drawers as a connector similar to flooring and can use foods in cabinets/fridges with drawers being the connecting block to the Cooking Table

### Your Proposal

Restore the ability of the kitchen to use food stored in connected storage drawers

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/StorageDrawers/pull/18
