### ISSUE TITLE
GT Item Pipes push into output

### ISSUE THREAD

**Issue by Exelion42** [GTNewHorizons/GT-New-Horizons-Modpack#11442]
### Your GTNH Discord Username

Exelion#8813

### Your Pack Version

2.2.0.0 RC4

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

GT item pipes should behave like the always did, but...

### The Reality

A while ago (actually some versions ago) I noticed a new strange behavior on GT item pipes. Once an item is present in a machine, item pipes connecet to this machine transporting the same item, can push it into it (regardless of the settings an the machine). They can even push it into the output slot (!) or an output bus. This can mess up many setups, especially with several machies of the same type producing the same item on one pipe, because the machines filling each others output slots.
It seems to happen on all types of GT item pipes (brass, electrum...) and it seems to be caused by the pipes, beacause when I use other transport systems (like ender IO) this dosen´t hapen.

### Your Proposal

Investigate what the pipes are doing, and fix it to how they behaved before.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2207
