### ISSUE TITLE
Recent fix breaks Industrial Mixer's ability of separate input buses

### ISSUE THREAD

**Issue by joegnis** [GTNewHorizons/GT-New-Horizons-Modpack#11446]
### Your GTNH Discord Username

joegnis#6497

### Your Pack Version

2.2.0.0

### Your Server

private server

### Type of Server

Open To LAN

### Your Expectation

- Add 2 Iron Dust to one input bus with circuit 1
- Add 1 Nickel Dust to another
- Mixer should not run
i.e., GT++ Mixer should support separate input buses

### The Reality

Mixer runs the recipe to generate 3 Invar Dust, i.e., it treats all input buses as one

### Your Proposal

GT++ mixer should support separate input buses like other multis. I believe it is due to this PR on mixer: https://github.com/GTNewHorizons/GTplusplus/pull/375. It should be reimplemented to avoid breaking existing feature. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by fluffle** [comment]
Ah yes it seems to be, looking at the code fixed by GTNewHorizons/GTplusplus#379 it wasn't checking fluid inputs at all :-(

**Comment by minecraft7771** [comment]
> Ah yes it seems to be, looking at the code fixed by [GTNewHorizons/GTplusplus#379](https://github.com/GTNewHorizons/GTplusplus/pull/379) it wasn't checking fluid inputs at all :-(

It did check every input. It just didn't look at item inputs seperatly.

**Comment by miozune** [comment]
@fluffle 's issue seems to be https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11448. Try with larger capacity of hatches or fewer inputs.

**Comment by miozune** [comment]
Yeah another ticket with detailed information would be good.

**Comment by fluffle** [comment]
No neeeed *cough* ... during some of my debugging I had disabled the mixer and not re-enabled it. Sorry for the noise :-(
