### ISSUE TITLE
Mytown plugin is missing, all towns disappeared

### ISSUE THREAD

**Issue by ZuOverture** [GTNewHorizons/GT-New-Horizons-Modpack#11447]
### Your GTNH Discord Username

AnCorp

### Your Pack Version

2.2.0.0

### Your Server

Epsilon

### Your Expectation

On 2.1.2.0 /mytown existed and provided permissions, mob and blast protection.

### The Reality

On 2.2.0.0 there's no /mytown and no relevant permissions/protection.

### Your Proposal

Major bug, please restore towns or at least make them work asap.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by POPlol333** [comment]
Known issue, unfortunately boubou has an higher priority first which is getting delta to breath again, he'll probably come back to you when he'll be done with it

**Comment by ZuOverture** [comment]
Ok. Hope there'll be no griefing/stealing meanwhile to add to his current problems.

**Comment by ZuOverture** [comment]
Towns were fixed yesterday, everything seems restored to previous state.
There was one complaint from Zachary09 about not being able to lift the claim from individual chunks, but cannot confirm that, as both claiming and unclaiming worked for me. Anyways, he can create his own issue if need be.

Resolved.

**Comment by Ngar1** [comment]
At _zeta_ towny is not active or working
