### ISSUE TITLE
Questbook View Mode No Longer Shows Most Chapters

### ISSUE THREAD

**Issue by OrderedSet86** [GTNewHorizons/GT-New-Horizons-Modpack#11443]
### Your GTNH Discord Username

Order#0001

### Your Pack Version

2.2.0.0

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

View Mode should allow you to view almost all quests ahead of time, except for certain narrow chapter exceptions (eg Legendary Questline) that can be argued over.

### The Reality

In current version, View Mode only allows you to see locked quests on the chapters you've unlocked. You cannot view any chapters you have not unlocked.
![image](https://user-images.githubusercontent.com/88752681/192678749-1633e0c3-9111-444c-be68-f40b81cbf0da.png)

### Your Proposal

You should be able to view almost all chapters like "/bq_admin edit". 
(While this command is a workaround, it requires OP permissions, which many multiplayer users don't have.)
![image](https://user-images.githubusercontent.com/88752681/192678820-9bc8c7e9-9ae0-46cf-a78e-9b10d29e6fb1.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by OrderedSet86** [comment]
According to Colen, this is an intentional change to make the start less informationally dense / confusing for new players. In this case, I recommend adding a toggle to view all chapters. Currently there is no way to regain this functionality from previous devs without using /bq_admin edit.

**Comment by Connor-Colenso** [comment]
Yea I agree, I do think the existing paradigm should be default set to minimal mode to prevent information overload, especially with new players. However the view mode needs to re-enable other tabs as well. This will require code changes.

**Comment by realthecaffiend** [comment]
Yeah default to avoid information overload?
Solid change!
No way to see what you're planning for in the future? Big oof. View mode exists for a reason, having to constantly admin edit is annoying
