### ISSUE TITLE
Industrial diamond recipe need attention

### ISSUE THREAD

**Issue by Glease** [GTNewHorizons/GT-New-Horizons-Modpack#11445]
### Your GTNH Discord Username

glee8e

### Your Pack Version

2.2.0.0-RC3

### Your Proposal

Revert it back to IC2 shape, or use assembler in place of crafting recipes in IC2 shape if you like.

### Your Goal

Because it makes no sense now.

There is a first chain...
1. 8 coal dust + 9 flint (in the form of 1 full flint dust) => 1 coal ball, in assembler.
2. 1 coal ball => 1 compressed coal ball, in compressor.
3. 8 compressed coal ball + 1 coal block => 1 coal chunk, in assembler

There is a second chain...
1. 8 coal dust + 1 flint => 1 compressed coal ball, in assembler.
2. 8 compressed coal ball + 1 coal block => 1 coal chunk, in assembler

Both chain are available at the same time, but the second chain require 88% less flint and one less step.

### Your Vision

no recipe loophole idk

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Zap0** [comment]
This does not seem up-to-date anymore. In 2.2.8 I can't find a recipe using Flint Dust in the Assembler (a mixer recipe with 8 Coal Dust and 1 Flint Dust exists instead). Also 1 full Flint Dust is made with 2 Flint, not 9 Flint in the Macerator now. So the alternative chain now only uses 2x the Flint, not 9x.
