### ISSUE TITLE
MouseTweaks no longer working in Wireless Crafting Terminal GUI

### ISSUE THREAD

**Issue by glowredman** [GTNewHorizons/GT-New-Horizons-Modpack#11441]
### Your GTNH Discord Username

glowredman#1337

### Your Pack Version

None (private pack), WCT version: 1.8.8.10-1-g07fd1ee

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Pressing LM+Shift and "sliding" over multiple items to move them to an inventory should work in the Wireless Crafting Terminal like in any other inventory.

### The Reality

It works in the ME Crafting Terminal but no longer in the WCT.

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by eigenraven** [comment]
This was done on purpose because MT was badly broken in the WCT, scrolling and dragging in some areas of the gui manipulated the wrong slots. Keeping this open, because turning off MT in there is more of a hotfix than a real solution of the problem
