### ISSUE TITLE
GT++ machines always need enough fluid space for max parallels

### ISSUE THREAD

**Issue by minecraft7771** [GTNewHorizons/GT-New-Horizons-Modpack#11448]
### Your GTNH Discord Username

minecraft7771#0427

### Your Pack Version

2.2.0.0

### Your Server

Any

### Your Expectation

GT++ multis should only make as much fluid as the output space and inputs allow.

### The Reality

Opening this issue so it doesn't get lost:
`private int canBufferOutputs(FluidStack[] aFluidOutputs, int aParallelRecipes)` in `GregtechMeta_MultiBlockBase` only checks if it has enough space for the maximum amount of parallels that the machine tier allows, if not it fails. The check for items however calculates how many parallels are possible to output and then returns that number. Fluid should behave the same.

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by joegnis** [comment]
Can confirm that centrifuge has this issue too:
To make recipe: 53k Liquid Air => 40k Nitrogen and other 3, Needs at least IV input hatches (256,000L) to work

**Comment by minecraft7771** [comment]
Not the gt++ nerf we wanted but the one we deserved :kekw:

**Comment by alphaNOVAircraft** [comment]
Output bus i disagree, multis always were voiding when the output was full. You can work around that. Input sure.

**Comment by Dr-Nye** [comment]
happening for me as well, HV Endstone Dust Centrifuge would require and EV hatch to operate

**Comment by shadowpho** [comment]
This is awful,  EV centrifuge doing air needs UV hatches to work currently.   Makes industrial centrifuge... not very useful.

**Comment by minecraft7771** [comment]
> This is awful, EV centrifuge doing air needs UV hatches to work currently. Makes industrial centrifuge... not very useful.

I mean you could still disable void protection (and possibly add your own void protection with covers if you care)

**Comment by chochem** [comment]
@minecraft7771 if you know what its caused by, do you know how to fix it? Its pretty annoying tbh. Its hard enough to debug broken multis in discord without bugs coming in on top to add another layer. And this one comes up a lot.

**Comment by minecraft7771** [comment]
The thing that broke it was https://github.com/GTNewHorizons/GTplusplus/pull/317 iirc. It was a proper fix to the void protection respecting locked hatches. I'm not sure how it is really fixable in a way that isn't very compute intensitive but @BlueWeabo wants to try and implement it into his new parallel calacultor so we have a clean solution across all mods.

**Comment by skizzerz** [comment]
@minecraft7771 I have a (currently untested) fix in my fork at https://github.com/skizzerz/GTplusplus/commit/ecd88498bae06cea302938f1a9cccbb01939d4ee along with another change to GT++ related to how overclocks were sequenced with parallels to be less punishing for wire/transformer loss. Could be useful perhaps, and should still be performant.

**Comment by minecraft7771** [comment]
> @minecraft7771 I have a (currently untested) fix in my fork at [skizzerz/GTplusplus@ecd8849](https://github.com/skizzerz/GTplusplus/commit/ecd88498bae06cea302938f1a9cccbb01939d4ee) along with another change to GT++ related to how overclocks were sequenced with parallels to be less punishing for wire/transformer loss. Could be useful perhaps, and should still be performant.

Thanks you very much 🙏 We will integrate this into the new parallel calculator so it can be used across all GT mods.
