### ISSUE TITLE
Project red IC gate went missing after update

### ISSUE THREAD

**Issue by christianvdstap** [GTNewHorizons/GT-New-Horizons-Modpack#11453]
### Your GTNH Discord Username

Lalaru

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Your Expectation

Critical automation does not go missing after server upgrade.

### The Reality

The IC gate disappeared after the update, meaning the entire base ran out of power.

### Your Proposal

Not making the block disappear (if this is a one off I guess that is fine, it was easy enough to replace)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by christianvdstap** [comment]
Can't reproduce consistently since I can not update ETA repeatedly

**Comment by BritishCynic** [comment]
Hard to investigate if there is no reliable way to reproduce this. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
