### ISSUE TITLE
Reduce void miner craft time

### ISSUE THREAD

**Issue by realthecaffiend** [GTNewHorizons/GT-New-Horizons-Modpack#11454]
### Your GTNH Discord Username

thecaffiend#2253 

### Your Pack Version

2.1.2.3qf  (Some config changes, no recipe changes)

### Your Proposal

Reduce the void miner, III especially, craft time in the asssline. 

VMI: 1/2, 2700 seconds: By the time you want/need more than one, there is a legit expectation that you are well past LuV anyhow, 2700 is too long but this is a "stretch" new technology.
VMII: 1/4, also 2700: This looks the same but due to being a voltage step up will in every case be one less OC, and thus slower. 
VMIII: 1/8, 1350 seconds. There are simply less voltages available past UV to climb the OC chains, and the whole original idea of VM's (As I understand it?) was to reduce TPS problems from spam. Making these too long just means I'll probably mostly make VMII's in order to not tie up assslines. 

### Your Goal

Removing useless time gates with no gameplay resolution available

### Your Vision

Time gates *that incentivize you to improve something* are, at times, fine. Neutronium I actually don't mind because you can goto better gasses, more blast furnace capacity, MEBF/s, climb voltages, etc. 

Void miners are just silly. The cost of them is in the expensive chain to produce them, the time is nothing more than an irritant (There is other solid convo on github about suggestions for balance of them in general, I'm not touching that here). Considering as it produces ores forever, I'd argue there is zero balance change to make the craft time more reasonable.

We have UIV assslines and the void miner III recipe is *still* 45 minutes. It's nothing but waiting for a machine, it's not some new form of engagement, it's just trying to convince me to only make VMII instead purely due to the time involved. This isn't like neutronium, there isn't much higher voltages available to push the assslines to, and it's a single multiblock controller, not something you want to make in massive parallel (I say, waiting for a craft of five to finish). The time required is not adding anything to gameplay, it's just taking it away

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by POPlol333** [comment]
I'm not really up for it, recipe time are somehow part of the recipe, if you want decent time overclock, which mean more energy consumption that you have to keep up, and well considering overall how VM are badly fucked it still fair for them to be a pain to craft in every way overall

**Comment by boubou19** [comment]
It's one of the few time gates i actually support in the pack: VMs are totally unbalanced right now, so you at least need to wait some time before abusing it.

**Comment by POPlol333** [comment]
I've been told that there was a misunderstanding, I'm not for timegate at all, I'm only talking in this exclusive case, where I think energy consumption is fair to be part of the price considering vm utility

**Comment by realthecaffiend** [comment]
The base recipe is too high to really overclock. We have UXV assslines now, we can't go higher, and still it would tie up a line for like 12 minutes. I would be fine if we could climb to making it in a kind of reasonable time (like, 2-4 minutes, not 12) but it's not available so it's just a boring wait. 

I'm not suggesting some sort of a buff here, energy by the time you're making multiple VMIII is sort of a joke anyhow, just spam more naq or solar or plasma. The cost of the machine is fine (tbh could even be more), the time is just boring when there is no way to really reduce it.

The vm produces ores for weeks/months/years so the waiting to abuse it doesn't do anything but annoy players: It's the worst type of time gate, one where there is no way around it (Except instead spamming II's which is what I'm doing in the other monitor, increasing server load)

**Comment by POPlol333** [comment]
So, you're complaining, for 12 minutes?

**Comment by realthecaffiend** [comment]
Yes. Because it's not 12 minutes, it's 12Xnumber produced which is distinctly more than one. And it serves no purpose other than being a boring wait. There isn't some sort of new engaging mechanic or something, it's just ignore it for a while and sorry I guess you can't craft anything else in those lines

**Comment by boubou19** [comment]
12 mins to have something OP is not a big deal. Just do assline parallelism and you are fixed. VM recipe time will be reworked when there will be an overhaul of the multi. I know it's far from ideal, but it needs to stay like that otherwise it's equivalent to get yourself creative amount of ores.

note: you should update your game, 2.1.2.3qf3 is quite ancient now, even if it was fixed in dev, you'd have to update

**Comment by realthecaffiend** [comment]
I'm only filing this for the future; We are approaching gate and there are *way* too many breaking changes for us to consider updates. Uninterested in spending weeks or months rebuilding setups we didn't even notice were broken. 

The VM timer doesn't change how it works; For pure TPS reasons I'd like to see (only the III) have overclock so there was some incentive to use it with big volts and not just spam more. I feel like any VM re-work (Which they could use, assuming that the balance based around their existence changed) will just mean that the craft time isn't changed because "it's always been like that". 

I think player incentive is important; Right now, the incentive is for me to make (another) 64 void miners on vega because it will be faster to craft than making a mess of III's. Less TPS consuming (Though, from my profiles, the VM is very tps friendly) solutions not being penalized seems better: It's not like there is a functional difference between 3 II's and two III's, except cost (Eh, you have void miners) and craft time.

**Comment by POPlol333** [comment]
Sup I Forget to mention the other day, but there a new multi in dev the Space Elevator which contain a new mining module which will be the successor of VM, kind of VM MK2. So you might want to update some day to try it out
