### ISSUE TITLE
Ender Fluid Link Cover reset itself after the update

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#11459]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

delta

### Your Server

delta

### Your Expectation

Expected Ender Fluid Link Cover to keep old channels setup

### The Reality

All Ender Fluid Link Covers lost their channel

### Your Proposal

Probably too late on officials, but is this normal? And why did it happen?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
they were rewritten. I fear that might be unavoidable but I am just gonna point to @alexandre-tardif

**Comment by Connor-Colenso** [comment]
Yea pretty sure this was intentional because it is no longer bound to just colours and allows any string.
