### ISSUE TITLE
Chemical plant (nitro benzene) stopped working after the update

### ISSUE THREAD

**Issue by christianvdstap** [GTNewHorizons/GT-New-Horizons-Modpack#11452]
### Your GTNH Discord Username

Lalaru

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Your Expectation

Before the update chemical plant was working, after the update it was not.

- output hatches are configured and have space
- input hatches have enough and correct input fluids
- structure did not change (and is shown as complete)
- energy buffer below the energy hatch has 2 full batteries
- correct circuit is inserted in an input bus

### The Reality

The chem plant does not run the recipe any more

### Your Proposal

Make it work?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Which pipe casing tier do you use? And how many of which tier output hatches?

**Comment by christianvdstap** [comment]
pipe casings are titanium, 2 LV output hatches (fluid locked, both empty and it fits the 3000 diluted sulfuric acid and 5000 nitrobenzene)

**Comment by christianvdstap** [comment]
> The problem is that now the machine wants enough room to fit the max parallels (so 6 * 5000L) even when it doesn't have enough input. It's not related to the chemplant but all gt++ machines. Already documented the issue here #11448 and will close this as duplicate.

Thanks, I have just found the issue, this is a change then?

**Comment by minecraft7771** [comment]
Yes the old handler for calculating output space was replaced and this is an oversight.
