### ISSUE TITLE
GT++ algae farm casings are too expensive

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#11450]
### Your GTNH Discord Username

querns#3785

### Your Pack Version

2.2.0.0

### Your Proposal

The GT++ Algae Farm multiblock currently uses Sterile Farm Casings for its structure. These casings are also used by the Tree Growing Simulator. When the TGS was nerfed, the cost of the casings went up significantly.

![image](https://user-images.githubusercontent.com/33518699/192786714-10ab0ece-36a2-422b-a433-4cd88f2ab351.png)

However, the Algae Farm is tiered to LV.

![image](https://user-images.githubusercontent.com/33518699/192786803-ddad7abe-e80b-4794-bb6c-68f29464261b.png)

### Your Goal

I think that the Algae Farm should have casings appropriate to its tier.

### Your Vision

Create a second type of casing, "Farm Casing" or "Basic Farm Casing." Give them the pre-TGS-nerf recipe, and adjust the Algae Farm to use the cheaper casings. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
this was probably a mistake when changing the TGS because they overlap in casing, right?

**Comment by Steelux8** [comment]
I will fix this now, I wasn't aware of it beforehand.
