### ISSUE TITLE
Conveyor pulling from a drawer always pulls a single stack

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#11457]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

delta

### Your Server

delta

### Your Expectation

Example: UV conveyor placed on an input bus directly connected to a drawer, set to import, is going to move 1 stack/tick instead of 8 stacks/tick

### The Reality

+

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
it is likely caused by the fact that the drawer exposes only a stack at a time

**Comment by Glease** [comment]
there are compat for these type of storage to move multiple stacks. probably a regression.
