### ISSUE TITLE
ME output bus do not work with Wire fucktory(gt++)

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/GT-New-Horizons-Modpack#11460]
### Your GTNH Discord Username

@dahgul#1726

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Your Expectation

https://cdn.discordapp.com/attachments/603348502637969419/1024764284980449351/unknown.png
https://cdn.discordapp.com/attachments/603348502637969419/1024764285617975366/unknown.png
*it was enebled

### The Reality

continued to work after the resignation to normal bus

### Your Proposal

Fix :/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
did you allow for voiding?

**Comment by dahgul333** [comment]
With voiding it start work but ... voiding all

**Comment by dahgul333** [comment]
![image](https://user-images.githubusercontent.com/35747549/192875589-7d05f5db-211c-48e3-a6f5-328fd8021594.png)

**Comment by chochem** [comment]
1) how certain are you that it isnt in your system?
2) scan the bus itself to see if things are still in there. (in case its not connected properly)

**Comment by dahgul333** [comment]
![image](https://user-images.githubusercontent.com/35747549/192878273-34a55c15-e8cd-4981-8f02-1a2a3eef05df.png)
with a normal interface on his channel everything works

**Comment by GDCloudstrike** [comment]
I think you might have mistakenly placed an me input but instead of an me output bus there

**Comment by dahgul333** [comment]
I have already set up a working network for tests many times, and I can’t say for sure whether the bass was there initially. Now everything seems to work
