### ISSUE TITLE
Loading screen apears as just a "No texture found" image

### ISSUE THREAD

**Issue by Ben-Bingham** [GTNewHorizons/GT-New-Horizons-Modpack#11467]
### Your GTNH Discord Username

honda go brrrrrr#4491

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

While the game is loading i expect to see cool bases in the backround.

### The Reality

![image](https://user-images.githubusercontent.com/94578530/192914848-33b669be-be82-4235-87e6-f792f747975f.png)

My image may not work but all i saw was the default no texture found image ie: Pink and black squares in a chekerboard pattern. However the splash text did render over the image but no other text did, like the little bar at the bottom that shows what version your on was not there.

### Your Proposal

Fix the missing texture unless its intentional

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
try a clean install. also, do replace the `resources` folder. They aren't just a bunch of texturepacks.
