### ISSUE TITLE
some tree-like structure generates with IC2 solar panels for leaves

### ISSUE THREAD

**Issue by potato4444** [GTNewHorizons/GT-New-Horizons-Modpack#11466]
### Your GTNH Discord Username

potato44#4929

### Your Pack Version

2.2.0.0, but with RWG replaced by the old version (1.3.2)

### Your Server

localhost

### Type of Server

Vanilla Forge

### Your Expectation

Trees to have regular leaves, or to not exist at all.

### The Reality

2 trees (well, I think they are trees) generated with IC2 Solar panels and untextured blocks where the leaves normally are. 
![2022-09-29_08 41 40](https://user-images.githubusercontent.com/32945005/192904967-115edcc5-4a60-4379-8d91-6ba458abd131.png)
![2022-09-29_08 41 54](https://user-images.githubusercontent.com/32945005/192904988-e89f081d-e39c-4097-8874-bf827d3628cc.png)

I've also found a message from May on the discord which seems to be a reference to someone else experiencing the same bug at some point: https://discord.com/channels/181078474394566657/181078474394566657/977681933322563594

### Your Proposal

To either generate the trees with the intended blaocks, or to not generate them at all.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
chunk corruption. nothing we can do here.
