### ISSUE TITLE
Integrated Ore Factory recipe is wrong

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#11462]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

delta

### Your Server

delta

### Your Expectation

Expected diamond and tungsten grinding head to be the same

### The Reality

Number of tungsten grinding head is 4
![javaw_JNVdf7Qtoc](https://user-images.githubusercontent.com/17811922/192879656-fb3ca264-fc08-412c-924e-ec13878dcb92.png)
Number of diamond grinding head is 64
![javaw_X0VFh5eaIb](https://user-images.githubusercontent.com/17811922/192879909-1f330b2c-3937-460e-bcaf-738a415849d5.png)

### Your Proposal

Make both 4 or both 64

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
i would say remove diamond grinder. Its a high end recipe use tungestensteel grinder.

**Comment by Sphyix** [comment]
They are already both used like they are the same in all recipes, hv to uev
So in the case one gets removed, rest of the recipes should match and a tier should be decided for the switch

**Comment by GTNHAfx237v7** [comment]
Tbh just ditch the diamond recipe, use 64x tungstensteel grinding heads and call it a day.
Singleblocks use both variants but this is a lategame multi so not comparable.
