### ISSUE TITLE
PersonalSpace prevents Minecraft from starting.

### ISSUE THREAD

**Issue by m4n02** [GTNewHorizons/GT-New-Horizons-Modpack#11469]
### Your Pack Version

2.2.0.0

### Your Server

SP

### Your Actions

Installed the newest version of GT New Horizons, got rid of some dupped mods, then started game.

### Crash Report

[crash-2022-09-29_01.03.52-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9670859/crash-2022-09-29_01.03.52-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by eigenraven** [comment]
As the error message says, you have to remove utilityworlds because PS replaces it. You should do a clean install and not merge mods folders from two different versions, some mods were removed from the pack.
