### ISSUE TITLE
Error while trying to check in what vein an ore is found

### ISSUE THREAD

**Issue by Pawxcio** [GTNewHorizons/GT-New-Horizons-Modpack#11461]
### Your GTNH Discord Username

Pawlo#4258

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Open To LAN

### Your Expectation

![2022-09-28_21 34 55](https://user-images.githubusercontent.com/87355768/192872818-84cf1fff-3c72-4d32-aa6c-0207cc13442c.png)

I tried to check crafting of various ores by clicking "r" in NEI. The goal was to find in which vein would I find them

### The Reality

![image](https://user-images.githubusercontent.com/87355768/192872882-b77320b1-a92b-4b83-bc6e-b78954f679bb.png)
I got a "There was error during loading recipe. Please check log for details" in the chat. No crafting displayed :(

### Your Proposal

By clicking "r" on an ore in NEI, the vein description appears(as in previous version)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Pawxcio where is the log ?

**Comment by johnso48** [comment]
I have the same issue and can post the log

[https://pastebin.com/WyN0m390](url)

**Comment by Glease** [comment]
Fixed by https://github.com/GTNewHorizons/BloodMagic/pull/33
