### ISSUE TITLE
Electrolyzer recipes got changed and now require empty cells next to the cells to electrolyze

### ISSUE THREAD

**Issue by christianvdstap** [GTNewHorizons/GT-New-Horizons-Modpack#11473]
### Your GTNH Discord Username

Lalaru

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Your Expectation

Old recipes where the fluids where offered in cells and then produced empty cells or let electrolyzer just accept the fluid inputs with empty cells in the input. Automation is now broken (ex: methane and 1,2-Dimethylbenzen)

### The Reality

Recipes got changed and were not added to the breaking changes list messing up the automation.

### Your Proposal

At least add these types of recipes changes to the breaking changes list, as this will kill automation based upon it forcing basically a rebuild just for the update where the yields did not change.

Preferably, let electrolyzers accepts fluids directly in the fluid input (Like HCL already does for instance) (this would actually be a feature request in that case)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
the wiki isnt official maintained by the devs. Feel free to add stuff yourself anyway. :)

**Comment by BritishCynic** [comment]
I am closing issue as it does not relate to anything that can be fixed in code.
