### ISSUE TITLE
Breaking EIO Conduit with DE Staff of Power causes disconnections/crashes

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#11474]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

delta

### Your Server

delta

### Your Actions

Breaking old setups containing EIO Fluid Stelllar condiut and/or Item Conduit causes crashes/disconnections with "Internal Server Error"
Breaking what's in the screenshot causes a crash
![hFovCnqBHv](https://user-images.githubusercontent.com/17811922/192986891-b2157438-3bd5-4ff0-bc29-a3881773eb8a.png)

Not all setups cause the same disconnect/crash, it happens randomly.
Looks like doesn't matter what's close to it, removing everything and breaking just the EIO conduit causes the same crash

@boubou19 around 10:27 AM 29/09 I disconnected twice, if logs needs to be recovered for the ticket

### Crash Report

[crash-2022-09-29_10.20.55-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9672871/crash-2022-09-29_10.20.55-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by POPlol333** [comment]
stable feature

**Comment by POPlol333** [comment]
Jokes apart, according to him it *ONLY* happen at an exact coordinate, the block next to it doesn't trigger this and placing a new cable to test with a fresh conduit still trigger it

**Comment by Sphyix** [comment]
How to reproduce (at least in my base)
Place a stellar ender fluid conduit at coordinate x 45
Then break it with a DE Staff of Power and server disconnects you.
If conduit is placed at x 46 or at x 44, nothing happens

**Comment by dvdmandt** [comment]
Looks like the problem is the GT hatch it's attached to at first glance. For some reason EIO thinks the connected hatch is a conduit.
