### ISSUE TITLE
Wrong Plasma values after update to 2.2.0.0

### ISSUE THREAD

**Issue by DefNotLeethe** [GTNewHorizons/GT-New-Horizons-Modpack#11477]
### Your GTNH Discord Username

Leethe#6564

### Your Pack Version

2.2.0.0

### Your Server

SP

### Your Expectation

Prior Note: This issue resolved itself after removing and reinstalling the GNTH instance. This ticket was submitted due to a dev request.

After the update, Plasma values stay constant (since no intentional nerf was planned) 

### The Reality

At least the fusable Plasma types had the wrong fuel values displayed and in terms of actual output. E.g. Helium sitting at exactly 1/20th the previous value (picture) while tin was at 1/6.
![unknown](https://user-images.githubusercontent.com/114660139/193035679-13a672e9-0c1e-4f2b-97c8-2201c47195de.PNG)

### Your Proposal

Investigate what caused this error? Idk

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I requested you make a ticket, but you didnt tell me it resolved itself lol. You told me you got the problem on a brand new clean instance. Must have been some weird misunderstanding. I guess we dont need a ticket then.

**Comment by DefNotLeethe** [comment]
That's why i was confused you wanted me to submit a ticket here as i solved it by reinstalling lol. Anyway, works for me.
