### ISSUE TITLE
MCR accepts energy hatches only behind

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#11476]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

delta

### Your Server

delta

### Your Expectation

Expected to be able to place them anywhere, like under or on top

### The Reality

Energy hatches on the MCR are limited only behind the machine, this can be an issue and sometimes annoying 

### Your Proposal

Make it accept energy hatches on every chemically inert machine casing, like the rest of the multis and mega multis

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Im sure this is done on purpose to make it a bit more interesting to set up

**Comment by Sphyix** [comment]
Probably, but we probably have a different concept of interesting aswell, it can be interesting and annoying at the same time, depends on situations

**Comment by Sphyix** [comment]
Still an issue if no one changed anything
