### ISSUE TITLE
Dimensionally transcendent catalysts recipes require more than one fluid input slots in single block mixer

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11471]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Expect to use 1 cell and 1 fluid in recipe

### The Reality

![recipe1](https://user-images.githubusercontent.com/85604068/192943047-92ca27c0-3cbf-48e7-a331-b5fe8c9002d4.png)
![recipe2](https://user-images.githubusercontent.com/85604068/192943050-8929f834-1b82-4a78-8356-d9810ddc7691.png)
![recipe3](https://user-images.githubusercontent.com/85604068/192943054-a5b2c129-b6f8-4d6c-a2e6-13b96c2d7dca.png)
![recipe4](https://user-images.githubusercontent.com/85604068/192943060-0ebf9bfe-ac59-44fa-a8cc-d57acac36613.png)

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@ChromicRedBrick is this a gt recipe or from another mod?

**Comment by ChromicRedBrick** [comment]
It is a GT recipe.
Multiblock mixer recipe is like this:
![multimixer](https://user-images.githubusercontent.com/85604068/192952892-dd203c92-2b77-4fd2-be17-0b4bfb0ede4d.png)

**Comment by ChromicRedBrick** [comment]
All of these recipes require 4 types of 1000L plasma, but one cell of plasma is 144L, maybe this is the cause.

**Comment by Dream-Master** [comment]
gt have no multi mixer its a gt++ recipe i guess. Why it is still displayed/used in single block mixer ?

**Comment by minecraft7771** [comment]
The recipe is indeed added in GT5U. Guess it's like chromic said and the input amount matches no cell which is why it generates incorrectly. Or the recipe was added with the GT++ mixer in mind.

**Comment by Glease** [comment]
per colen this is intentional. he said no one use sb at that tier and both PA and GT++ can do this recipe.

personally i feels this is just a makeshift solution and must be changed

**Comment by Connor-Colenso** [comment]
The recipe was added with the GT++ mixer in mind, you were never supposed to do this in a single block. As Chromic noted, this is not as simple as just adding a few cells instead. If someone wants to fix plasma not having 1000L in each cell instead of sometimes being 144 then this can be adjusted.

However until then it just looks a bit odd visually.

**Comment by miozune** [comment]
Maybe add them only to MB recipemap so that they won't show up in SB recipemap

**Comment by BlueWeabo** [comment]
That will remove the recipe from being done in the PA. making it only possible to use the GT++ mixer
