### ISSUE TITLE
output buses (me) permanently stuck in offline(booting) mode when connected to a ME conduit

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#11478]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.2.0.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

have the output bus (me) works as usual

### The Reality

![2022-09-29_15 30 03](https://user-images.githubusercontent.com/12850933/193044860-9495044d-2b8d-4133-9be3-b401e6e61168.png)

it works well with AE2 cables tho

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
can't reproduce that in dev env, perhaps it was fixed, what GT version is there in 2.2.0.0?

**Comment by boubou19** [comment]
according to the manifest on the DAXXL repo, it's the version 5.09.41.61

**Comment by boubou19** [comment]
zeta is still in 2.2.0.0 because we didn't updated it yet (i guess business). We can update it if it's mandatory for testing purposes tho

**Comment by repo-alt** [comment]
Well, Zeta is a testing server, supposedly
