### ISSUE TITLE
Energy Infuser needs better documentation

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#11480]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Type of Server

Thermos

### Your Expectation

Trying to charge items in Energy Infuser

### The Reality

Nothing happens
![image](https://user-images.githubusercontent.com/70205464/193084936-75bfca24-ec05-41e5-b5df-348da23f9642.png)

### Your Proposal

Energy infuser can charge items

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Indeed the controller GUI slot is no longer charged, only input bus slots.

**Comment by RaitGamerGR** [comment]
Ok, it works with input bus. So, can you add it into wiki and tooltip of infuser?

**Comment by chochem** [comment]
has a quest now. :)
