### ISSUE TITLE
slicing Nanoprocessor results in imprint for ic2.itemPartCircuitAdv.name

### ISSUE THREAD

**Issue by shekurika** [GTNewHorizons/GT-New-Horizons-Modpack#11488]
### Your GTNH Discord Username

shekurika#8884

### Your Pack Version

2.2.0.0

### Your Server

MyFTB server

### Type of Server

Don't know

### Your Expectation

When slicing a Nanoprocessor (HV-Tier), I will get an imprint for it.

### The Reality

I get an imprint for ic2.itemPartCircuitAdv.name which does not work in the CAL..
![image](https://user-images.githubusercontent.com/25935015/193300982-63acf77f-83d1-4f86-a438-9042d11b1c27.png)
![image](https://user-images.githubusercontent.com/25935015/193301014-7ced66e6-c22c-412b-9ce2-13eedef3b743.png)
![image](https://user-images.githubusercontent.com/25935015/193301135-d94ce647-f172-41bb-b1a3-4617a21bde16.png)

### Your Proposal

Fix this I guess.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
Thats an old problem. See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6512. Didn't know the problem was still around, I have never been able to reproduce this.

Apparently using a single block machine instead of the multi is a workaround.

**Comment by chochem** [comment]
Just to be clear: the quest should tell you about this in big red letters. Should be pretty hard to miss.

I think we should still leave this open. A fix would better and some devs wanted to look at circuit oredicting anyway.

**Comment by minecraft7771** [comment]
I confirmed this behavior using the ZPM single block slicing machine

**Comment by chochem** [comment]
so the workaround does not actually work?

**Comment by minecraft7771** [comment]
Not for me and shekurika also used the single block I think

**Comment by GTNHAfx237v7** [comment]
I always used a slicing machine of the same tier as the circuit in a PA.

**Comment by chochem** [comment]
@GTNHAfx237v7 and that worked or was bugged?

Myself, I just always used the multi and never had this happen. As I said, I was never able to reproduce it.

**Comment by shekurika** [comment]
Sorry for the late reply. I did use the Cutting Machine from GT++ in Slicing Mode.

**Comment by zgggz** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/64369015/afd4218b-db7b-4cba-b361-1a8f9b549a65)
With single block the same problem. 2.4.0
