### ISSUE TITLE
Add Ding Mod

### ISSUE THREAD

**Issue by DarkMagicSource** [GTNewHorizons/GT-New-Horizons-Modpack#11483]
### Your GTNH Discord Username

squishy wizard#6206

### Your Pack Version

2.1.2.3QF

### Mod Name

[Ding](https://www.curseforge.com/minecraft/mc-mods/ding)

### The Mod to Add

It goes Ding when the pack has finished loading :)

### Your Reason

Mostly just a handy QoL tweak to know when the pack is finished loading if you switch to another window while waiting.

### Preliminary Investigation

Added it to the pack via PolyMC, no crashes or extra lib mods needed. Goes Ding when expected

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Glease** [comment]
Nice mod to have, though we already have the awesome main menu music, so you can't miss it anyway.

**Comment by chochem** [comment]
yea the main menu music is pretty clear about this :)

**Comment by Leatryx** [comment]
I installing Ding every time i play modded Minecraft. Definitely nice to have it in GT:NH

**Comment by eigenraven** [comment]
No need for another mod, betterloadingscreen already has this function, it's just turned off in the config: <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/Betterloadingscreen/betterloadingscreen.cfg#L34-L35>
