### ISSUE TITLE
Breaking an upgraded Yabba Barrel voids everything above 64Stacks

### ISSUE THREAD

**Issue by MLellmann** [GTNewHorizons/GT-New-Horizons-Modpack#11494]
### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

If you break an upgraded Yabba Barrel with more than 64 Stacks of items in it, the barrel will only drop 64 Stacks of items.

Expect: Drop all items. This might we laggy, but it is the fastest way to combine two barrels with the same type of item in it.

### The Reality

Only 64 Stacks of Clean Stone got dropped and i lost 192 Stacks of it.

### Your Proposal

Fix it so everything drops.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Working as intended. This is a measure to prevent lagging the server (or break your SSP game by giving you 1fps). I don't see this will be changing.

**Comment by Glease** [comment]
BTW it's called JABBA for 1710.
