### ISSUE TITLE
repurpose the multiblock GUIs to actually make them useful

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#11496]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.2.0.0

### Your Proposal

- Rework the textures to remove the colored squares that are supposed to show  the structure done on the multis that still have them, as it's very outdated now, and we have the hologram projectors from structurelib, even autoplace.
- Replace the maintenance issue messages by an icon showing the tool to use to repair, with a small red cross at the bottom left corner, and when you hover it, it shows the maintenance issue message, so it becomes noob friendly.
- Add tick boxes for boolean flags of the machines, or dropdown buttons for availiable different modes, so you don't need anymore to remember what tool can change what on each multi, as well as to spam the tool to process the whole cycle of options because you were to fast to cycle between modes. Basically something inline with what's done in the cover GUIs.
- Display various informations, such as the machine efficiency, it's energy consumption, recipe time, item being processed,...

My proposal will require a lot of multiblock rework, but i think it'll be worth to do, just like structurelib did with the structurechecks.

### Your Goal

give an actual use to the multiiblock GUIs, because right now the scanner and the IC² nuclear control panels are greatly over used by people, because nothing can be done in the GUIs.

### Your Vision

Improve the player's experience.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Yeah I'm actually planning on MB GUI rework. But first I need to get migrating GT code to ModularUI done.

**Comment by realthecaffiend** [comment]
A great idea, these are pretty outdated at this point.

Obligatory shilling for https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10610 to be perhaps included
