### ISSUE TITLE
Chunk or block load crash

### ISSUE THREAD

**Issue by Danonimo22** [GTNewHorizons/GT-New-Horizons-Modpack#11492]
### Your GTNH Discord Username

Shinei Nouzen#4533

### Your Pack Version

2.1.2.2

### Your Server

SP

### Type of Server

Single Player

### Your Actions

As the crash report says, I think it's a chunk or block problem, but I don't know how to fix it.
I also tried to restore the chunk that doesn't seem to work also backup doesn't work as soon you load the chunk as a new chunk game crash again. I'm 75% sure the chunk was loaded before but in the second visit chunk crashed the game.
Any idea? 

If this is an already solved problem, I'm sorry to bother anyone, I just haven't found the solution.¨
I'd be grateful for your help.

### Crash Report

![Screenshot_42](https://user-images.githubusercontent.com/81676044/193332486-b67457b3-4295-4368-a6fe-8a5a56441085.jpg)
full log:[crash-2022-09-29_23.37.20-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9686849/crash-2022-09-29_23.37.20-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
thats just the minecraft version, not the version of the mod pack

**Comment by Danonimo22** [comment]
> thats just the minecraft version, not the version of the mod pack

yea thanks fixed
