### ISSUE TITLE
Work with programmed circuit and gt++ multicbock

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#11499]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Type of Server

Thermos

### Your Expectation

Trying to use GT++ mutltiblock cutter and ABS with busses on different circuits

### The Reality

Machine cant works with circuits on different busses

### Your Proposal

Machines can do bus separate

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
You can use wire cutter to toggle input bus separate on ABS.

**Comment by minecraft7771** [comment]
And on wire mill it should be screwdriver
