### ISSUE TITLE
Voiding with ABS

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#11498]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Type of Server

Thermos

### Your Expectation

Using Alloy Blast Smelter with void excess mode

### The Reality

If output full, machine continue to work with void excess mode enabled or disabled

### Your Proposal

Void excess mode can toggle machine work or idle if output full 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Should be fixed since new parallel helper was implemented. Else re-open.
