### ISSUE TITLE
Game crashing in world loading

### ISSUE THREAD

**Issue by omarkla** [GTNewHorizons/GT-New-Horizons-Modpack#11493]
### Your Pack Version

2,2.0.0

### Your Server

SP

### Your Actions

A few hours ago I was playing the modpack normally. But a few hours later when I tried to restart it, it crashed when I tried to start the world I was playing in. Retrying to reload it doesn't fix the problem. Seeing the log file indicates that there is another crash

### Crash Report

https://mclo.gs/HuWkuPg

https://mclo.gs/N0m1RX7

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
