### ISSUE TITLE
Crashing when generating Twilight Forest

### ISSUE THREAD

**Issue by DarkMagicSource** [GTNewHorizons/GT-New-Horizons-Modpack#11501]
### Your GTNH Discord Username

squishy wizard#6206

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

When trying to generate the Twilight Forest in a world initially created in v2.1.2.1, after jumping into the portal the game crashes back to the main menu with the mod at fault being listed as FastCraft.

Upon trying to reopen the world, it hangs on "Loading world Building terrain", and I needed to kill the process and then restart it before actually being able to rejoin, then the dimension generates, however, my head is stuck in a block underground and no exit portal is generated.

Deleting the DIM7 folder and retrying causes the same result. Retrying in a creative world generated in V2.2.0.0 doesn't crash the game but still spawned me with my head inside a block but also with an exit portal generated on the surface.

Removing FastCraft doesn't solve the issue, instead now listing the mods at fault as The Twilight Forest, GC Planets, GC Core

<img width="854" alt="image" src="https://user-images.githubusercontent.com/35950530/193409523-40b194f8-9ed1-45ef-8a5c-98c6719810fd.png">

### Crash Report

- https://paste.ubuntu.com/p/Dd7rxdSmqY/ initial crash with FastCraft
- https://paste.ubuntu.com/p/cVNFnzWMgv/ after removing FastCraft and regening dimension

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
