### ISSUE TITLE
Orefinder wand not detecting on quest submit 

### ISSUE THREAD

**Issue by r2go-beep** [GTNewHorizons/GT-New-Horizons-Modpack#11507]
### Your GTNH Discord Username

r2go#4415

### Your Pack Version

2.2.0.0

### Your Server

private server

### Type of Server

Don't know

### Your Expectation

I expected the Orefinder wand to detect upon quest completion. 
![image](https://user-images.githubusercontent.com/59456156/193417765-7e8420f2-df2b-4706-9f9c-48482db33fa7.png)
![image](https://user-images.githubusercontent.com/59456156/193417769-c109efd4-d4d0-45d0-a618-d0fa5d2703e9.png)

### The Reality

The Quest is not completing even after clicking detecting and reloading

### Your Proposal

Orefinder wand completes orefinder wand quest

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
unable to reproduce this. the quest works just fine
![image](https://user-images.githubusercontent.com/40274384/193483667-46a395c5-8e3e-42b7-8a7d-f40086aecc75.png)

**Comment by chochem** [comment]
tested again in latest version. all works.
