### ISSUE TITLE
CleanView

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#11503]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.2.0.0

### Mod Name

CleanView

### The Mod to Add

This mod removes potion effects from showing for the player.

### Your Reason

Potion effects start to become very annoying very quickly, especially when you get to the point of using items like the fire-proof GT++ gloves that cause the Fire Resistance buff to persist. 

### Preliminary Investigation

The source for 1.7.10 is [here](https://github.com/zlainsama/CleanView/tree/1.17.1) and is licensed under the MIT License; the source code for 1.7.10 also very clearly includes the license. I added this mod to GTNH 2.2.0.0 with no obvious problems.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by chochem** [comment]
We dont need that. That functionality has just been added to the pack.

**Comment by miozune** [comment]
Implemented in https://github.com/GTNewHorizons/Hodgepodge/pull/125. Is it not working?

**Comment by TwoTailedFox** [comment]
No, I just forgot to remove it from my pack, my bad.
