### ISSUE TITLE
Deuterium have been removed from Ross128ba underground fluid map (on delta at least)

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#11502]
### Your GTNH Discord Username

AdamR#0072

### Your Pack Version

2.2.0.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

to get my deuterium >:(

### The Reality

Been running around with a 31*31 scanner didn't find any deuterium at all + all the deuterium field that I had previously found in the past are getting updated to helium3

### Your Proposal

fix it >:(

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
it was never there. probably a visual bug like some others have reported.

**Comment by POPlol333** [comment]
Oh? well i'm closing this then, thx
