### ISSUE TITLE
The two new fresh servers from Zvezdolet Team

### ISSUE THREAD

**Issue by Askara** [GTNewHorizons/GT-New-Horizons-Modpack#11509]
### IP

gtnh2.114-7.com & gtnh3.114-7.com

### Whitelist Status

https://gtnh.miraheze.org/wiki/GT_New_Horizons#Servers

### Server Name

Zvezdolet 2.0 & Zvezdolet Hardcore

### Primary Language(s)

RU / English

### Region(s) of Service

CIS / EU

### Additional Info

Zvezdolet 2.0 is fresh softcore without pollution and Zvezdolet Hardcore is hardcore GTNH with pollution. Our discord link is https://discord.gg/2Kp5ZRB9eb Please edit it on Wiki for Zvezdolet, Zvezdolet 2.0 and Zvezdolet Hardcore

**Comment by Askara** [comment]
Please, organize it close together in server.dat and wiki =)

**Comment by BritishCynic** [comment]
This is on the Wiki now, so this issue no longer needs to be open.

**Comment by Askara** [comment]
> This is on the Wiki now, so this issue no longer needs to be open.

Please add a discord-link to the Wiki Page https://discord.gg/2Kp5ZRB9eb

There is no link on the Wiki, but I asked for this in the header section Additional Information

![image](https://user-images.githubusercontent.com/2502760/215356885-b7109938-c5dd-4416-9901-ab69fe4e7864.png)

**Comment by BritishCynic** [comment]
The changes have been made as requested.
