### ISSUE TITLE
"Search in nearby inventories" doesn't work on drawers now

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11504]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Press "T" to search items in nearby inventory.

### The Reality

It doesn't work on storage drawers.
![search](https://user-images.githubusercontent.com/85604068/193413653-07a62db5-fae5-4174-b5e0-a13852c58dc3.png)

I remember it worked on drawers in 2.1.2.3QF.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eldrinn-Elantey** [comment]
I confirm that this problem is relevant on version 2.2.0.0. There was no such problem on version 2.1.2.2QF2

**Comment by mitchej123** [comment]
Please grab the latest storage drawers if you can and test with that.

**Comment by miozune** [comment]
Confirmed fix

**Comment by ChromicRedBrick** [comment]
It works now, thanks.
