### ISSUE TITLE
tinkers construct

### ISSUE THREAD

**Issue by J4keSn4ke10** [GTNewHorizons/GT-New-Horizons-Modpack#11511]
### Your GTNH Discord Username

J4keSn4ke101#8117

### Your Pack Version

2.2.0.0

### Your Server

earthquake

### Type of Server

Thermos

### Your Expectation

trying to make aeon steel ingot and or queens gold ingot but both did not have a way of converting it 

### The Reality

nothing

### Your Proposal

let the ingot cast work or fix the clay cast so they work

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/TinkersConstruct/pull/58
