### ISSUE TITLE
NEI probl3ma

### ISSUE THREAD

**Issue by JavierPithod** [GTNewHorizons/GT-New-Horizons-Modpack#11510]
### Your GTNH Discord Username

JavierPithod #7362

### Your Pack Version

2.1.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Ver el listado de ítems del NEI normalmente

### The Reality

No puedo ver el listado de los ítems del NEI de la derecha del inventario el jugador. El resto de la interfaz la puedo ver perfectamente excepto eso. Ya probé pulsar la tecla "o" y "control +o", pero no es ese el problema. Si a cualquier objeto le pulso la tecla "r" y "u" puedo ver la receta y usos de dicho objeto sin problema. Pero al pulsar la tecla "e" veo toda la interfaz del NEI excepto el listado de objetos que debería aparecer a la derecha del inventario del jugador. Así mismo la barra de búsqueda siempre se muestra en rojo, cómo si no existiera ningún objeto para buscar. Adjunto una imagen para que se entienda mejor mi problema.
![IMG_20221001_171717_829](https://user-images.githubusercontent.com/114834530/193428860-ae7dbfc4-f5a3-45d9-aa19-12770f56aade.jpg)

### Your Proposal

Poder ver el listado de objetos del NEI correctamente.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
Without me checking anything, Deepl says:

Viewing the NEI item list normally

I can't see the listing of the NEI items on the right side of the player's inventory. The rest of the interface I can see it perfectly except that. I already tried pressing the "o" key and "control +o", but that is not the problem. If I press the "r" and "u" keys on any object, I can see the recipe and uses of that object without any problem. But when I press the "e" key I see all the NEI interface except the list of objects that should appear to the right of the player's inventory. Also the search bar is always shown in red, as if there was no object to search for. I attach an image to better understand my problem.

To be able to see the list of NEI objects correctly.

**Comment by boubou19** [comment]
Por favor, actualiza tu juego y verifica si el problema persiste

**Comment by bit2shift** [comment]
This is probably a *PEBKAC* because it can be reproduced on 2.2.0.0 by searching `     ` (5 spaces) on NEI.

**Comment by JavierPithod** [comment]
Ya actualicé el pack y el problema aún está ahí. La única diferencia es que ahora aparece un texto que dice "loading item list", pero ya llevo más de 3 horas con el juego abierto y no carga ninguna lista de objetos. Volví a reinstalar el pack y hasta incluso eliminé mi mundo anterior (para descartar la teoría de un PEBKAC) y aún así me sigue pasando lo mismo.

**Comment by bit2shift** [comment]
@JavierPithod just wondering, did you try erasing the NEI search box?
Might want to try deleting the `saves/NEI` folder.

**Comment by BritishCynic** [comment]
No response from original poster in some time, am closing this issue. If you can reproduce this issue on current dev (preferably with a visual confirmation that the NEI search bar is empty), please leave a comment to re-open with steps needed to reproduce.
