### ISSUE TITLE
Carpenters roof top blocks usable topside down

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#11525]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.2.

### Your Proposal

Please look at picture
![rooftop](https://user-images.githubusercontent.com/7759876/193517069-57921a16-4555-483b-9476-0ed817622f6f.GIF)

### Your Goal

Please extend the possibility that carpenters top roof block joining in a row also topside down. 

### Your Vision

more usecases of existing carpenters blocks

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
We have the source so it can be fixed im someone know how.
