### ISSUE TITLE
Turn some MV main quests into optional quests

### ISSUE THREAD

**Issue by BlueIceJAY** [GTNewHorizons/GT-New-Horizons-Modpack#11524]
### Your GTNH Discord Username

Neutron#6126

### Your Pack Version

2.2.0.0-RC3

### Your Proposal

Turn some MV main quests into optional quests

### Your Goal

Such as "First Kanthal" and "Solar Grade Ingots"
These quests take a huge amount of time to wait for the Chemical Bath but can easily be skipped
For example,I can use SMD Transistor to craft Advanced Circuit.Kanthal and Si(sg) ingots doesn't stop the player from entering HV and creates a Vacuum Freezer.SMD Transistor is simpler and cheaper,so I don't have to make Si(sg) ingots through the Chemical Bath.
But if you don't craft Kanthal and Si(sg) ingot,you can't progress your main quests ,even if you actually in HV.You have to go back and do these quests.
Since these are not necessary quests, and completing them will increase the difficulty, why not put them in the optional quests?

### Your Vision

Quests Should Make the Complex Simple

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
there is a skip quest already if you made smd
