### ISSUE TITLE
Steam Valve (LV) not working at advertised throughput

### ISSUE THREAD

**Issue by Godelboard** [GTNewHorizons/GT-New-Horizons-Modpack#11535]
### Your GTNH Discord Username

Godel#6372

### Your Pack Version

2.2.0.0

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Steam Valve (LV) has a tooltip of 1024 L/t (20480 L/s). When attached to a super tank full of steam prior to 2.2.0.0, was correctly exporting steam at this rate to power base.

### The Reality

After 2.2.0.0, it is no longer pushing out steam from the tank at advertised throughput amount. Seems to be maybe 1/10 of advertised rate.

MV and HV seem to be working correctly still but I would double check these and higher tiers, as my validation was counting in my head and watching numbers go up lol.

### Your Proposal

Correct pump output rate as it's still relevant for early game steam power storage. Although super tank auto output largely negates this, it's still helpful prior to super tanks being obtainable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by iBattery355** [comment]
Have the same issue at 2.2.8.0 (private server)
