### ISSUE TITLE
Allow us to use Indalloy (basically solder t4) and Living Solder (solder t5) in lower-tier recipes

### ISSUE THREAD

**Issue by Shadowsoftime99** [GTNewHorizons/GT-New-Horizons-Modpack#11533]
### Your GTNH Discord Username

Shadows#4865

### Your Pack Version

2.2.0.0

### Your Proposal

![image](https://user-images.githubusercontent.com/16748195/193680947-93d5c54e-9667-42fc-83ca-08d806f93302.png)

Using QProc Assembly as an example, look how we can use 4x Lead, 2x Tin, 1x Soldering Alloy. This ratio is the case for basically every recipe that allows them. Why not allow 1/4x Indalloy and 1/8x Living Solder (could do a different ratio but these things are expensive relative to base solder) on the recipes as well, similar to how you can use smaller amounts PTFE and PBI?

### Your Goal

Consistency with plastic and glue! Also a reward for using the higher tier version, because they're kind of just there to be difficult right now.

### Your Vision

More options, more happiness. Also it'd allow late-game players to set up mass production of the later game solders and use that for everything, exactly like how people use PBI now. Super glue will probably see this same usage too once people adapt to 2.2 changes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Connor-Colenso** [comment]
The main reason I dislike this is because firstly, you have to decide how much of product A is equal to product B, which is actually really hard to balance correctly when they are using vastly different products.

The second reason is recipe spam, this creates a lot more permutations and given fluids do not rotate as an ore dict ingredient would it pollutes NEI with useless information.

**Comment by shekurika** [comment]
I agree with the recipe spam, I already found the lead recipes annoying. Adding 2 more for each circuit (ignoring the different SMD versions, with that its even more) will confusing new players even more

**Comment by Shadowsoftime99** [comment]
Why do we care about recipe spam now, when we already have thousands upon thousands of recipes? The glue and plastic-using ones all have their collection of equivalents, and those are all fine. Yeah it's more things in the list, but a player is already sorting through thousands to find anything as it is.

Complexity with circuits is maybe a concern since they already have a bunch of variant, non-ore-dicted recipes, but the circuit NEI tab I used for the screenshot does a fair amount of work for organization, it's much nicer to look at here. There are only four slots in the fluid section though, but that _has_ to be fixable, right?

I think it's rather obtuse to care about not adding that complexity _now_, when we've already seen the addition of two new solder types that just serve to muddy the solder story for late-game bases; breaking things initially and then requiring maintaining production of three types of solder even once it's fixed. The very least we could do is let those people switch everything to Living Solder, and just be using tiny amounts of it for low-tier circuits along with normal amounts for high-tier ones.

As for the ratio of Sn9Sb to Indalloy, I gave 1/4 and 1/8 as examples but it can't be that hard to figure out a good ratio. It's been done for PBI and Super Glue already.

**Comment by boubou19** [comment]
when one adds hundreds of recipes in the pack, from the player's point of view, it's just recipe spam in NEI and that's all. From devs' point of view, we have a big for loop iterating over all the valid soldering alloys, which means an addition of one fluid will cause one more iteration of the loop, causing non neglectible booting time addition due to the hundreds of recipes to add. Therefore, it's better to add fluid oredict to recipes before even considering yet another recipe spam.

**Comment by Shadowsoftime99** [comment]
If we could just use fluid oredict and handle this that way (I see some chat in the discord about this) that'd be great
