### ISSUE TITLE
AE2 smelting patterns corrupt when shift-clicked from NEI

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#11538]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.2.0.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

Shift-clicking recipes from NEI into the ME pattern terminal should yield a functional recipe

### The Reality

On the first tab shown for Black Metal ingots (and all other smeltable GT++ materials that I have tested so far):
![image](https://user-images.githubusercontent.com/8459776/193836113-b4ecbb5a-0833-4f41-9242-15116a0316fa.png)
When importing patterns from the smelting tab the result looks fine, and all items involved appear to have the correct tooltip
![image](https://user-images.githubusercontent.com/8459776/193835254-50f59a20-ece1-4f4d-855f-4e34ec29b5e6.png)
But when actually trying to craft with the recipe, the input material is not found:
![image](https://user-images.githubusercontent.com/8459776/193835464-940ea6ad-67f5-4aac-9211-70dde5537d24.png)

### Your Proposal

Preferably I would not have to remove the autofilled dust with an actual dust from my ME to make the recipe work as expected.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTNHLib/pull/18
