### ISSUE TITLE
EnderIo generating tooltip in quest window crashes to main menu.

### ISSUE THREAD

**Issue by YasenGaming24** [GTNewHorizons/GT-New-Horizons-Modpack#11539]
### Your GTNH Discord Username

LazyFlesh#4533

### Your Pack Version

2.2.0.0

### Your Server

sp

### Type of Server

Single Player

### Your Actions

Tried to  open the Two Ethanols#3100 quest in the bio for the masses tab. It just crashed me immediately. Also crashes if I try to do it trough NEI. Also happens on the conduits quest in MV.
![image](https://user-images.githubusercontent.com/40587985/193840348-b21df78d-734a-4e52-b101-a4beccfa7a59.png)

### Crash Report

https://pastebin.com/k64wxruL
https://pastebin.com/tg6ynbWD
https://pastebin.com/B3ZHmyrq

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
I cannot reproduce this crash. This code is suspicious, it might be French local issue but not sure.
```java
// Handle french local 'non breaking space' character used to separate thousands.
// This is not rendered correctly and cannot be parsed by minecraft so replace it with a regular space
private static final boolean REPLACE_NBSP;
private static final char NBSP = (char) 160;

static {
    boolean res = false;
    if (INT_NF instanceof DecimalFormat) {
        DecimalFormatSymbols syms = ((DecimalFormat) INT_NF).getDecimalFormatSymbols();
        if (syms.getGroupingSeparator() == NBSP) {
            res = true;
        }
    }
    REPLACE_NBSP = res;
}
```

**Comment by YasenGaming24** [comment]
This fixed itself after the game was restarted. Might just be something from having it running for a long time on my not so good computer.

**Comment by chochem** [comment]
just comment to reopen if it happens again I suppose to you or anybody.
