### ISSUE TITLE
ME Crafting Terminal has no assembler receipe

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#11532]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.2.

### Your Proposal

Autocrafting without hand tools of ME Terminals.
Only ME Interface and Crafting Terminal have assembler receipt

### Your Goal

hand tools stucks ME Autocrafting

### Your Vision

Please add assembler receipt for ME Pattern Terminal

(I am not shure if there was in past that receipt, because I had such pattern in an assembler, but now it does not work)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Crafting, Interface, Pattern, Processing Pattern, and ME Terminals have assembler recipes for me. Fluid pattern, Fluid Processing Pattern (AE2FC) and Fluid Terminals (EC2) don't, but they don't require tools to hand craft.

**Comment by Ngar1** [comment]
ok

**Comment by Dream-Master** [comment]
i woll go over ae recipes soon and put all stuff o assembler etc

**Comment by Ngar1** [comment]
ok
