### ISSUE TITLE
Hologlasses Fatal Error

### ISSUE THREAD

**Issue by Spl1x6** [GTNewHorizons/GT-New-Horizons-Modpack#11543]
### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I looked at a villager with hologlasses on.

### The Reality

My world immediately closed giving me a fatal error. Every time I tried loading back into the world, it would fatal error again as I was still looking at the villager. I was able to fix this by removing the Holo Inventory mod from my game and reloading the world, deleting the holo glasses in the process. I then reinstalled the mod and attempted to spawn my self a new pair of glasses. As soon as I looked at a villager, the fatal error happened again (this is how I learned what caused the fatal error). I was able to replicate this several times.

### Your Proposal

This should be fixed idk

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Spl1x6** [comment]
Discord is Spl1x6#2702

**Comment by Ethryan** [comment]
Do you have a crashlog?

**Comment by Spl1x6** [comment]
Doesn't give a crashlog as it is a fatal error and the minecraft instance does not crash

**Comment by boubou19** [comment]
we need at least your client log

**Comment by Spl1x6** [comment]
Ight, I will get it to you when I get home

**Comment by Spl1x6** [comment]
So I have no idea what I did with it. Guess I can recreate it if it is that important

**Comment by Ethryan** [comment]
It’s hard to tell without a error log, what have caused the world to crash. So a log is appreciated when reporting these errors.

**Comment by repo-alt** [comment]
I guess, reopen with the client log.
