### ISSUE TITLE
Scheelite dust processing now produce gt++ CaCl3 instead of gt CaCl3

### ISSUE THREAD

**Issue by christianvdstap** [GTNewHorizons/GT-New-Horizons-Modpack#11548]
### Your GTNH Discord Username

Lalaru

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Your Expectation

All dusts are the GT variant

### The Reality

When processing Scheelite the gt++ CaCl3 is produced

### Your Proposal

Output gt CaCl3 instead (as previously)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
is there a gt one?? I thought we only had a bartworks and a gt++ one.

Anyway, they should be oredicted properly. The worst that can happen is a bad filter I guess.

I dont know why it was changed a few months ago but I dont think there is any reason to change it back either.

**Comment by christianvdstap** [comment]
> 

exactly what happened is that some filters got screwed up.

**Comment by christianvdstap** [comment]
Another interesting thing, in item filters the ghosts seem to have updated automatically? so that means it might only be an issue for item filter covers.

**Comment by chochem** [comment]
I know if affects AE2. They stayed the same. (I had the issue a few months back in some dev version. Since then I have both options in the filter.

Anyway, changing it back would just cause the same problem again, so I would say we leave things as is. Though its not ideal that it happened.
