### ISSUE TITLE
Fluid filter covers block energy transfer

### ISSUE THREAD

**Issue by christianvdstap** [GTNewHorizons/GT-New-Horizons-Modpack#11546]
### Your GTNH Discord Username

Lalaru

### Your Pack Version

2.2.0.0

### Your Server

ETA

### Your Expectation

When using fluid filter covers on machine hulls output facing, the machine hull can no longer transfer power. To make machine hulls with covers useful the should be able to transfer power past all the covers.

### The Reality

Power on output side is blocked.

### Your Proposal

Power on output side is not blocked.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
i don't understand the issue here: if you obstruct the output side, then it's normal it doesn't work.

**Comment by christianvdstap** [comment]
![2022-10-05_12 55 01](https://user-images.githubusercontent.com/8134651/194044689-c050d584-92f4-46b3-9c19-c0725ec73eda.png)
See above, most covers do pass energy just fine. It is the fluid filter cover that blocks it (below the lamps are energy detector covers)
