### ISSUE TITLE
Industrial Mixing Machine doesn't have separated busses

### ISSUE THREAD

**Issue by relaksoid** [GTNewHorizons/GT-New-Horizons-Modpack#11545]
### Your GTNH Discord Username

Богдалик#2964

### Your Pack Version

2.2.0.0

### Your Server

private server

### Type of Server

Ultramine

### Your Expectation

IMM should have separated input busses. And detect recipe depend on bus circuit.

### The Reality

Example: 
I have busses with circuit's #12 and #14. When I try to craft black steel dust in bus with circuit #14 I got tumbaga dust and rest of ingridient's still exists in bus #14.

### Your Proposal

As I know all GT++ machines should have separated input busses by default. Back to this or get a ability to switch mode between separated/not separated like in PA.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Already fixed by https://github.com/GTNewHorizons/GTplusplus/pull/379
