### ISSUE TITLE
Large Turbine Calculator sheet needs updates

### ISSUE THREAD

**Issue by joegnis** [GTNewHorizons/GT-New-Horizons-Modpack#11542]
### Your GTNH Discord Username

joegnis#6497

### Your Pack Version

2.2.0.0

### Your Server

private server

### Type of Server

Open To LAN

### Your Expectation

Results (specifically optimal flow in this case) of the [Large Turbine Calculator ](https://docs.google.com/spreadsheets/d/15dn8iBJJlNYCi_sKnpL0SJ-c3TaBvOSYpGZRI-TjowA) should match those in game.

### The Reality

For example, we made a large Ichorium turbine for our plasma generator but found out its optimal flow is 141 L/s in game instead of 47 L/s as calculated by the sheet. 

### Your Proposal

After digging into code history, I found out that [this commit](https://github.com/GTNewHorizons/GT5-Unofficial/commit/50f2e64c0c6e44da3881c3b075d11e63eaab256b) buffs Ichorium and other various materials by `setTurbineMultipliers`. I guess simply adding 3 columns for the 3 multipliers (steam, gas, plasma) to the material table and adding the factor to the formula of optimal flow should fix the calculator.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Rickbude** [comment]
It seems like nowadays [this calculator](https://docs.google.com/spreadsheets/d/11EgfbjJhL32haViLHt9zaShQprvdXD0t23e-x7erVtM/edit#gid=655714366) is the one you should use.
