### ISSUE TITLE
Change the way formatting AE2FC cells works

### ISSUE THREAD

**Issue by dipo33** [GTNewHorizons/GT-New-Horizons-Modpack#11559]
### Your GTNH Discord Username

Dipo#3713

### Your Pack Version

2.2.0.0-RC3

### Your Proposal

Change the way formatting AE2FC cells works from cells to an actual fluids.

Probably the best would be adding a new AE2FC Cell Workbench, that would format the cells with fluids.

### Your Goal

Currently the formatting is done in a regular ae2 cell workbench, by inserting a cell with the specific fluid.

This is an issue, since not all fluids have their own cell, such as water mixed dyes.

### Your Vision

It would be possible to format cells even with fluids that don't have their own cell.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
i didn't tried yet but can't you use drops of the fluid or any container with the fluid in it to format the cell?

**Comment by dipo33** [comment]
Didn't try drops yet, but IIRC any other containers like universal cells didn't work for me. Gotta try later today, since it was some time ago when I dealt with it the last time.

**Comment by GlodBlock** [comment]
universal cells should work. could you tell me which kind of fluid you are trying to format?

**Comment by dipo33** [comment]
Okay, you are right, it works now fine with the universal cells, guess I was doing something wrong then..

 Thanks
