### ISSUE TITLE
Crash with latest kekztech 0.6.16 in connection with nuclear control

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#11558]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.2.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Launched the pack with updated kekztech (0.6.16) to check the fix for the avg eu in/out.
Pack launched fine but crashed when trying to enter the world.

### Crash Report

[crash-2022-10-06_07.52.21-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9721615/crash-2022-10-06_07.52.21-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ProfessorStain** [comment]
Same problem. Pack version 2.2.3
https://www.youtube.com/watch?v=gURfrkHPYzQ
[crash-2022-10-09_15.56.48-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9741161/crash-2022-10-09_15.56.48-server.txt)
