### ISSUE TITLE
Journey map crashes when toggling on GT ore veins

### ISSUE THREAD

**Issue by henriblob** [GTNewHorizons/GT-New-Horizons-Modpack#11555]
### Your GTNH Discord Username

henriblob#0336

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Open To LAN

### Your Expectation

![journeymap](https://user-images.githubusercontent.com/115122064/194184323-77860e09-e4ef-45da-89e0-0c1be51aba8e.png)
It used to work when we started our world but then journeymap randomly started crashing when trying to display visual prospecting ore veins.

### The Reality

![error](https://user-images.githubusercontent.com/115122064/194184337-f847de6d-7ba2-4982-94bf-dcf5394c73bf.png)

Im running forge 10.13.4.1614 which is the version that came with the modpack but it says journey map requires 10.13.4.1588.
After it crashes it won't show my location or my player marker and wont fullscreen when I press J.
I have tried switching to journeymap unlimited but that didn't help. My friend (who I share the world with) does not have this issue and we are running the same version of journeymap. I am using MultiMC with the modpack downloaded from downloads.gtnewhorizons. It still crashes even if I'm not open to LAN.

I am able to toggle on visual prospecting ore veins with no problem in dimensions where I haven't prospected any ore veins. As soon as I discover one I get the journeymap crash.

This doesn't crash my game, just journeymap.

### Your Proposal

Help me fix the crash so i can see ores again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Please provide FML log

**Comment by henriblob** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9730369/fml-client-latest.log)

**Comment by miozune** [comment]
Is it still reproducible without "open to LAN"?

**Comment by henriblob** [comment]
Yes

**Comment by miozune** [comment]
I cannot reproduce the crash, and never heard of. Looking at code, this _might_ be your issue:
```java
Keyboard.getKeyName(VP.keyAction.getKeyCode())
```

Please check your keyboard state, LWJGL version, or something like that (I actually don't know well about them)

**Comment by henriblob** [comment]
How do i check my LWJGL version?

**Comment by miozune** [comment]
It turns out your keybind is bound to invalid value. Check your keybind for `VisualProspecting > Action button`

**Comment by henriblob** [comment]
Checking now

**Comment by henriblob** [comment]
Changed action button to left bracket and its working fine now. Thank you so much

**Comment by Xen0n123123** [comment]
same problem, but it didn't help me.
