### ISSUE TITLE
Reloading texture corrupts GT fluid texture

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11566]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0 (With all mods latest version on GitHub)

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Reloading texture and sounds with F3+T because I switched sound output to my headphone.

### The Reality

Before reloading:
![Snipaste_2022-10-07_00-27-42](https://user-images.githubusercontent.com/85604068/194389043-ab0e992a-3176-411f-8b70-00a27ae5a612.png)

After:
![Snipaste_2022-10-07_00-29-41](https://user-images.githubusercontent.com/85604068/194390673-c93f69fe-0212-415c-a19b-1e5bee31f400.png)
![Snipaste_2022-10-07_01-45-05](https://user-images.githubusercontent.com/85604068/194390691-87465d2f-51fa-4c81-bf4b-5a6258176281.png)

It can happen when you change language, resourcepacks, shaderpacks, because they all make texture reload.

I also reproduced it just now, here's the full log.

(reload texture started at [02:15:47])

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9727540/latest.log)

I have some additional mods installed, including: 
worldedit-forge-mc1.7.10-6.1.1-dist
ForgeNBTEdit-universal-1.0.0.test
OptiFine_1.7.10_HD_U_E7_MOD
SmoothFont-1.7.10-1.15.3
InputFix-1.7.10-v5
FTBUtilities-1.7.10-1.0.18.5-GTNH
FTBLib-1.7.10-1.7.10-1.7.10-1.0.18.4
OmniOcular-1.7.10-1.0build103
falsepatternlib-mc1.7.10-0.10.8
laggoggles-mc1.7.10-4.13.0

### Your Proposal

Find out what happened and fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SafariXiu** [comment]
I also encountered this problem

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1477
