### ISSUE TITLE
Add the missing half of cell/fluid versions to the vacuum freezer.

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#11567]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.2.0.0

### Your Proposal

Various vacuum freezer recipes added since 2.1.0.0 only come in fluid version, while in the past all recipes involving fluids were cell-only. 

The missing recipes to add are:

- [ ] Einsteinium plasma -> molten Einsteinium (cell version missing)
- [ ] Boron plasma -> liquid boron (cell)
- [ ] Helium -> liquid helium (cell)
- [ ] Thorium plasma -> molten thorium (fluid version missing)
- [ ] Tellurium plasma -> molten tellurium (fluid)
- [ ] Force plasma -> molten force (fluid)
- [ ] Liquid oxygen plasma -> liquid oxygen (fluid) (wtf?)
- [ ] Liquid nitrogen plasma -> liquid nitrogen (fluid) (wtf?)
- [ ] Noble gases plasma -> noble gases (fluid) 
- [ ] CO2 plasma -> carbon dioxide (fluid)
- [ ] Arsenic plasma -> molten arsenic (fluid)
- [ ] Dysprosium plasma -> molten dysprosium (fluid)
- [ ] Hypogen plasma-> Molten hypogen (fluid)

### Your Goal

Make everything consistent

### Your Vision

People should not be forced to use cells or no cells for seemingly arbitrary reasons.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by SweptWasTaken** [comment]
If nobody else is currently doing it i'll work on this.

**Comment by Dream-Master** [comment]
@SweptWasTaken sure feel free to add it.
