### ISSUE TITLE
Backport Modern Minecraft Textures 

### ISSUE THREAD

**Issue by Connor-Colenso** [GTNewHorizons/GT-New-Horizons-Modpack#11568]
### Your GTNH Discord Username

Colen#6943

### Your Pack Version

2.2.0.0

### Your Proposal

Modern Minecraft has moved well beyond 1.7.10 at this point, to keep GTNH relevant I propose we backport some more modern features into GTNH to prevent it "rotting". It will make GTNH feel fresh and up to date with the latest versions, without actually being there. 

With that in mind the latest versions of Minecraft have quite drastically changed the default textures, imo for the better. There is now a texturepack avaliable for 1.7.10 which backports these textures https://www.curseforge.com/minecraft/texture-packs/modernity. I suggest we make this the default for the pack (with obviously the option to switch back to current 1.7.10 textures left in the resource packs folder).

### Your Goal

Make GTNH feel more modern.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by DarkMagicSource** [comment]
I like the new textures. I use Modernity, however, this is mismatching between the modern MC textures and modded textures which pulled design from the "current" textures when they were designed ie ingots. I think it would be handy if it were pre-bundled with the pack, but not the default.

**Comment by Connor-Colenso** [comment]
Yes that is a fair point, some stuff (like ores) would need their background updated) but we can't continue to lag behind on this matter forever.

**Comment by glowredman** [comment]
In my opinion backporting new features is fine (see [Et Futurum](https://www.curseforge.com/minecraft/mc-mods/et-futurum) for a start) but modern textures should be opt-in at most.

**Comment by DarkMagicSource** [comment]
> some stuff (like ores) would need their background updated 
I know GregTech (and BartWorks etc) do funky stuff with texture mappings and just overlay the texture, ie the ores already "match" just by applying Modernity but that's far from the norm.
