### ISSUE TITLE
Add recipes for SMD inductors

### ISSUE THREAD

**Issue by NotAPenguin0** [GTNewHorizons/GT-New-Horizons-Modpack#11579]
### Your GTNH Discord Username

NotAPenguin#5179

### Your Pack Version

2.2.0.0

### Your Proposal

Following the conversation (https://discord.com/channels/181078474394566657/181078474394566657/1028043811068325959) in the Discord, I'd like to propose recipes for SMD inductors. The current recipes we arrived at are

1 neodymium rod + 16 fine platinum wire -> 32 smd inductor
1 neodymium rod + 16 fine iridium wire -> 64 smd inductor

(both recipes also take an appropriate amount of polyethylene, same as the other SMDs)

1 samarium rod + 32 fine hss-e wire + 4 tungstensteel bolt + PBI (same as other asmds) -> 64 advanced smd inductor

4 titansteel foil + 2 botmium foil + 1 superconductor base ZPM foil + 1 superconductor LuV wire + 144L Xenoxene -> 32 optical smd inductor

Along with these, circuit recipes should be added to use the SMD variants instead of small coils, at the same ratio as other SMDs.

### Your Goal

Add more consistency to the pack by providing recipes for items that currently don't have a recipe but really should.

### Your Vision

This would be consistent with other circuit components.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by querns** [comment]
Perhaps use Samarium for the advanced SMD variety and something else from the lanthline group for the opticals? Making it so that the lanthline-only material (erbium?) has a use, but the advanced can be brute forced with the two-step Samarium option.

**Comment by NotAPenguin0** [comment]
Current proposed advanced SMD recipe:

1 samarium rod + 32 fine hss-e wire + 4 tungstensteel bolt + PBI (same as other asmds) -> 64 advanced smd inductor

**Comment by NotAPenguin0** [comment]
Current proposed optical SMD recipe:

4 titansteel foil + 2 botmium foil + 1 superconductor base ZPM foil + 1 superconductor LuV wire + 144L Xenoxene -> 32 optical smd inductor
