### ISSUE TITLE
Make the Fusion Reactor use a stack of 4 Circuits instead of four times 1 Circuit

### ISSUE THREAD

**Issue by shekurika** [GTNewHorizons/GT-New-Horizons-Modpack#11575]
### Your GTNH Discord Username

shekurika#8884

### Your Pack Version

2.2.0.0

### Your Proposal

Currently the Fusion reactors MK1-3 require 4 lone circuits of the respective tier instead of 4x 1 circuit. This just makes the automation a tad more annoying as you now require 4 renamers. Nothing else changes, as the minimum assline length is already required for the field generators.

### Your Goal

Make Fusions slightly less annoying to automate.

### Your Vision

People are happier.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
the automation challenge is on purpose. you have multiple options on how to automate these recipes. It also applies to rocket plates any many other recipes. And no you dont need 4 renamers for 4 circuit obviously, but not 3 either. One multi that can even do other stuff on top works just fine.
