### ISSUE TITLE
Industrial Greenhouse can't plant Botany Germling...

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#11578]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.2.

### Your Proposal

Greenhouse is a great idea!

I tried in normal, input and output mode Botany Germling and ProjectRed Seed. I did never got any output. They were ignored.
(EDIT: Thaumic seeds working - it was my fail)

![GH_In](https://user-images.githubusercontent.com/7759876/194642681-9c8e0da8-39a6-4f1b-a8d3-7d29750dccbf.JPG)

### Your Goal

Support of ProjectRed seeds, botany germlings.

### Your Vision

For none IC2 seeds it would be nice to use this Greenhouse too. 
Actual no automated farming for botany flowers available, Greenhous would be a great solution to get the botany colors. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Szajkop** [comment]
The thaumic bases seeds are working for me. Atleast Redlon and Lazullia

**Comment by kuba6000** [comment]
Seems like all of the thaumic bases seeds are working.
And it looks like, botany germlings and ProjectRed seeds are not a real seeds, they can be placed on grass like flowers.

**Comment by Ngar1** [comment]
Botany germlings can´t grow on grass and automaticly harvested. 
In newer versions of forestry (12.1...) they can be farmed by multifarm, but our old version can´t. 
Thats why I ask if it would be possible to integrate it in the nice geenhouse

**Comment by Ngar1** [comment]
Kuba, would you please extend your greenhouse with botany germlings?

**Comment by Ngar1** [comment]
@kuba6000 - you wrote me, that you will look if botany flowers can be integrated?
The method as you wrote is the same as bees and you already implemented a Mega-Apiary. May be it is not so complicate for you?
