### ISSUE TITLE
Ugrade of the upgrade of the... quest requires unnecessary items

### ISSUE THREAD

**Issue by TheRustyBird** [GTNewHorizons/GT-New-Horizons-Modpack#11586]
### Your GTNH Discord Username

TheIronBird

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Should only require 1 shovel/axe head not.

![screenshot](https://user-images.githubusercontent.com/114885771/194723617-2f1591b8-dacc-4fd9-af6a-f883faaaf06a.png)

### The Reality

They require 2

### Your Proposal

They should only require 1

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
thats just the mattock.
