### ISSUE TITLE
Server don't boot by Zlib's error in VisualProspecting.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#11582]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.1.1.0 to 2.2.0.0 update

### Your Server

server

### Type of Server

Crucible

### Your Actions

Tried to install and start GTNH v2.2.0.0 server file (Opis removed)

### Crash Report

[2022-10-08-7.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9738432/2022-10-08-7.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
Try to remove visual prospecting folder. Re scan you area ingame . Some times the old data had some issues.

**Comment by yukieiji** [comment]
I tried removing it, but the server wouldn't boot.
Since the server would not boot, I couldn't join the world.

**Comment by Dream-Master** [comment]
why not use thermos?
	UCHIJAAA	Crucible{1.7.10-5.3} [Crucible Server] (minecraft.jar)

**Comment by Dream-Master** [comment]
maybe try this version of vp
https://github.com/GTNewHorizons/VisualProspecting/releases/tag/1.0.34

**Comment by Dream-Master** [comment]
this error is very old and i thought it was gone long time ago
[13:40:04] [Server thread/ERROR]: GT-ERR-01: @ ic2.itemRubber   Rubber

**Comment by Dream-Master** [comment]
@yukieiji can you check your visual prospecting file. Maybe redownload version 33 and/or 34 and see if that fix it. Can you open the jar file with winrar or zip programm ?

**Comment by yukieiji** [comment]
> why not use thermos?
UCHIJAAA Crucible{1.7.10-5.3} [Crucible Server] (minecraft.jar)

Because it's still being updated and maintained.

> maybe try this version of vp
https://github.com/GTNewHorizons/VisualProspecting/releases/tag/1.0.34

Not resolved.

> can you check your visual prospecting file. Maybe redownload version 33 and/or 34 and see if that fix it. Can you open the jar file with winrar or zip programm ?

Both files were correct.

**Comment by eigenraven** [comment]
Can you see if the server world save loads correctly in singleplayer (copy the world folder into your saves in the client)? Just to see if it's a problem with crucible or vp. Also if vp crashes with it in sp, try disabling vp and loading the world to see if it still loads in sp.

**Comment by Glease** [comment]
Try remove the VP jar. it currently cannot handle gzip world. 

Seriously though, isn't all 1710 world compressed using deflate though? why does it seem to be using gzip

**Comment by yukieiji** [comment]
> Can you see if the server world save loads correctly in singleplayer (copy the world folder into your saves in the client)? Just to see if it's a problem with crucible or vp. Also if vp crashes with it in sp, try disabling vp and loading the world to see if it still loads in sp.

Ok, but this world size is over 10GB, so it will take some time.

> Try remove the VP jar. it currently cannot handle gzip world.
Seriously though, isn't all 1710 world compressed using deflate though? why does it seem to be using gzip

Ok, I'll give it a try.
I'm not sure why it's compressed with gzip.

**Comment by yukieiji** [comment]
Server booted after uninstalling vp.
Please wait a moment for it to work in sp

**Comment by eigenraven** [comment]
Looks like Crucible <https://github.com/CrucibleMC/Crucible/blob/master/patches/net/minecraft/world/chunk/storage/RegionFile.java.patch#L334> (and thermos <https://github.com/GTNewHorizons/Thermos/blob/1.7.10/patches/net/minecraft/world/chunk/storage/RegionFile.java.patch>) have a custom save format for oversized chunks, which probably breaks VP's world scanning which uses a modified third-party library to scan region files directly.

**Comment by yukieiji** [comment]
I tried with SP and got the same error.

**Comment by yukieiji** [comment]
Doesn't having vp installed on the server cause any problems?

**Comment by Glease** [comment]
It basically means VP will not work, but beyond that no game changing issue.

**Comment by yukieiji** [comment]
So does this mean that everyone who connects to the server needs to uninstall vp?

**Comment by yukieiji** [comment]
Has this issue been fixed in v2.3.0.0?

**Comment by Dream-Master** [comment]
i am not sure but we get a few fixes on vp since 2.2.0.0

**Comment by yukieiji** [comment]
I just tried it and it wouldn't boot....

**Comment by boubou19** [comment]
that's a compat issue with crucible i guess, so if no one cared to test it, little chance that it changed. Try finding other crucible users with working 2.3.0 instance. In any case, it works on thermos and pure forge.

**Comment by yukieiji** [comment]
It works if I uninstall vp, but it is very distressing to force other users to do so....
I can share the world where this issue is happening if you need me to.

**Comment by boubou19** [comment]
@yukieiji have you tried to use pure forge to see what happens? if you replicate it on pure forge we will need your map to track it down, if you can't, then it's on crucible.

**Comment by yukieiji** [comment]
This isn't reproduced in SP, so it maybe work correctly in pure forge.

**Comment by yukieiji** [comment]
If Crucible is using its custom save format, I feel it would be difficult to switch to another server...

**Comment by boubou19** [comment]
try it on the same map (with backup ofc) just to be sure you didn't run through an edge case breaking VP. imo it's likely a missing lib or a code issue, crucible has no gain to change file format, as it would break a lot of assumptions for forge mods

**Comment by eigenraven** [comment]
We can probably implement zlib chunk decompression, it shouldn't be too difficult. Can't promise everything else will work with the changes to the save format though

**Comment by eigenraven** [comment]
@boubou19 I haven't looked at crucible but thermos does change the save format of chunks, adding a way for them to overflow if they exceed the 2mb limit at the very least
