### ISSUE TITLE
Backport GTCEu Surface stone vein Indicators

### ISSUE THREAD

**Issue by Irgendwer01** [GTNewHorizons/GT-New-Horizons-Modpack#11585]
### Your GTNH Discord Username

Irgendwer#5308

### Your Pack Version

2.2.0.0

### Your Proposal

Backporting the Surface stone vein indicators from GTCEu would help alot early in terms of searching veins, they spawn over a vein chunk and give you tiny pile of whatever in the vein spawns.
In the below picture there's an example on how they look like
![image_2022-10-08_191836868](https://user-images.githubusercontent.com/67506320/194719615-64b9b3c7-792d-48d1-b656-7f3c56b00036.png)

### Your Goal

Needing to have already ran around for a few hours in early game and searched for veins to make an Ore finders wand is kinda annoying early and then you also need to already have found the ore you search for before you can search it with it.

### Your Vision

It would help alot searching veins specifically in early game and can tell you straight out what ores are spawning in that vein chunk.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I guess this would make both our current small ore system and the ore finder wand largely obsolete. I guess at best it should be Overworld only to avoid that.
