### ISSUE TITLE
Programmed circuit doesn't work as intended in data orb repository (elemental duplicator)

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11583]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Insert a programmed circuit in data orb repository to choose recipe for elemental duplicator.

### The Reality

It seems that elemental duplicator only do 1 specific recipe, regardless of the programmed circuit number.

Video: https://youtu.be/eW5cYXlXCCI

### Your Proposal

Make programmed circuit work properly in data orb repository.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by cainiaojun** [comment]
Reproduced at 2.2.3 and 2.2.7.

**Comment by MarchingCube** [comment]
Can repro in latest dev pack as well.
