### ISSUE TITLE
AE2 interfaces' blocking mode detects battery slot items as items

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#11589]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.2.0.0

### Your Server

delta

### Type of Server

Thermos

### Your Expectation

I put blocking mode on my circuit assemblers, with a battery in it. I expected it to work normally.

### The Reality

The batteries were preventing the crafts from being inserted.

### Your Proposal

Exclude battery slots from blocking mode

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
This is still happening in 2.6.1
I have a dual interface pointing at a UHV singleblock assembler. Once I insert a battery into the power slot of the assembler, the blocking mode of the interface will see the singleblock as if it contained items, preventing insertion to actually craft something.
