### ISSUE TITLE
Compressor gives wrong stone plate

### ISSUE THREAD

**Issue by THE-CHOODICK** [GTNewHorizons/GT-New-Horizons-Modpack#11580]
### Your GTNH Discord Username

Discord_sound_bot_2#0219

### Your Pack Version

2.2.0.0

### Your Server

Private Server

### Type of Server

Open To LAN

### Your Expectation

It would be nice to get Stone Plate `#5828` from Compressor (HP `#2062/116`)

### The Reality

Unfortunately you get gt.metaitem.01.17299.name `#7122/17299` (Old Stone Plate)

### Your Proposal

As my best guess, it is being replaced automatically, so I propose swapping them around, so that all of gt.metaitem... ones are getting replaced by new stone plates.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by THE-CHOODICK** [comment]
![image](https://user-images.githubusercontent.com/84818316/194678013-6d48a834-1535-4da7-aeb2-9542d0f25b74.png)
Here is an screenshot of this bug

**Comment by chochem** [comment]
what is the problem with the gt one? I would say its better as is. They are also oredicted so usage should be fine or is that a problem somewhere?

**Comment by BritishCynic** [comment]
High Pressure Compressor converts Stone Dust to Stone Plate on 2.2.8, so we're unable to reproduce. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
