### ISSUE TITLE
Crash after update to 2.2.3

### ISSUE THREAD

**Issue by TimberDimber** [GTNewHorizons/GT-New-Horizons-Modpack#11596]
### Your GTNH Discord Username

TimberDimber#7872

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Actions

After update to 2.2.3 i can't enter to SP world. A crashlog appears referring to KekzTech, GregTech, NC2 and FastCraft. 

### Crash Report

[crash-2022-10-09_12.58.26-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9741285/crash-2022-10-09_12.58.26-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
* https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11558
