### ISSUE TITLE
NEI BUG in AE2 FLUID TERMINAL

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#11601]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

2.2.3

### Your Server

SP, MP

### Your Expectation

https://drive.google.com/file/d/1gZ2iyGCtkP1S8v4ZgvCK4vfxo6bUo9z9/view?usp=sharing

the video clearly shows that when adding liquid to the terminal from AE2 Fluid Craft, it does not add liquids, but capsules or buckets, but as soon as I hold down the left mouse button and swipe through the slots, it magically becomes a liquid. It used to be like this: you click on a capsule with water and it’s not a capsule that appears in the template, but 1000 ml of water.

I give you a hint right away, this is all because of NEI, when I install an older version of NEI (versions like 5-6 back from the announcements) it works perfectly.

### The Reality

fix

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by slprime** [comment]
This code is reason (it don't need fixed): 
![image](https://user-images.githubusercontent.com/31038811/195598567-1a7e361c-ed08-4b49-9171-ea27044b56e3.png)

for some reason, the ghost and real item work differently. need find and fix it

**Comment by GlodBlock** [comment]
it is neiaddon's issur. it hooks to the drag click of fake slot and mess up the ae2fc the slot https://github.com/GTNewHorizons/neiaddons/blob/master/src/main/scala/net/bdew/neiaddons/appeng/SetFakeSlotCommandHandler.java#L27
without neiaddon it can run well
