### ISSUE TITLE
5 busses 7 circuits or how to do wiremill

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#11605]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Type of Server

Thermos

### Your Expectation

Trying to use Wire Factory for new recipes with circuits. 

### The Reality

Structure cant be completed with more then 5 busses(6 without maintenance), but we have 7 different circuits.

### Your Proposal

Reduce minimum structure casings to 20.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
Make a second wiremill? If you are endgame enough for this to become an actual issue I think you can cope with the cost...
