### ISSUE TITLE
Microblocks tears ME cables at server restart

### ISSUE THREAD

**Issue by Ascard** [GTNewHorizons/GT-New-Horizons-Modpack#11606]
### Your GTNH Discord Username

LYnxZ#0324

### Your Pack Version

2.2.3

### Your Server

private server

### Type of Server

Ultramine

### Your Expectation

Cable stays connected to other cables and terminals

### The Reality

Several ME terminals connected to network and surrounded by microblock strips
![before](https://user-images.githubusercontent.com/1184531/194774545-3e2004e6-4e0c-4437-8adf-f8285c614987.jpg)
After server restart connections are broken
![after](https://user-images.githubusercontent.com/1184531/194774580-ae75282b-85a3-4024-828e-de965eafc99c.jpg)

### Your Proposal

fix, or drop

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
Looks like someone broke microblocks compat.
