### ISSUE TITLE
[CRASH] Crash the game at startup

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#11603]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.2.0.0

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Actions

Tried to start the client

### Crash Report

https://paste.ubuntu.com/p/M2RC5Qkdx4/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.
