### ISSUE TITLE
Grisium dust and maraging steel dust has no recipe

### ISSUE THREAD

**Issue by MrScorcher** [GTNewHorizons/GT-New-Horizons-Modpack#11617]
### Your GTNH Discord Username

Scorcher#5130

### Your Pack Version

2.2.3

### Your Server

private

### Type of Server

Don't know

### Your Expectation

Expected to see a recipe for a mixer or multi-block mixer.

### The Reality

Looking for recipes in NEI. Expected to see a recipe for a mixer or multi-block mixer, but there were none.

### Your Proposal

Add recipes for grisium dust and maraging steel dust

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by guineawheek** [comment]
The Alloy Blast Smelter only shows one recipe per NEI page -- have you checked if there are multiple pages?

**Comment by MrScorcher** [comment]
Alloy blast smelter have recipe "Grisium Dust → Molten Grisium" - this is fine.
Mixer **do not** have recipe for mixing this dust from others dusts.

**Comment by chochem** [comment]
> Alloy blast smelter have recipe "Grisium Dust → Molten Grisium" - this is fine.

just check the next page for molten grisium.

**Comment by benjamin-kirkbride** [comment]
Why was this closed? Appears to still be an issue, at least for Maraging dust

**Comment by benjamin-kirkbride** [comment]
JK you have to use the blast alloy furnace to make the liquid version.
