### ISSUE TITLE
Ghost circuit zero

### ISSUE THREAD

**Issue by mccarp** [GTNewHorizons/GT-New-Horizons-Modpack#11618]
### Your Pack Version

2.1.2.0

### Your Proposal

Add the functionality to select ghost circuit zero in the machine guis

### Your Goal

Base ztones blocks (like bitt(0) ) can be crafted in the assembler using a zero circuit to save on resources. Because you cannot select zero as a ghost circuit, you have to supply a physical zero circuit to it, which is inconvenient.

### Your Vision

it would make the ghost circuit function more complete

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
It won't be accepted as it's not on the allowed list.

**Comment by miozune** [comment]
Circuit number 0 is meant to be not used for recipes. https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9818
Plus Ztones recipes no longer use circuit 0. (https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/286, https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/423)
