### ISSUE TITLE
Assembly Line + Data bank lag

### ISSUE THREAD

**Issue by Eranicus** [GTNewHorizons/GT-New-Horizons-Modpack#11619]
### Your GTNH Discord Username

Eranicus#5476

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

.

### The Reality

After updating to 2.2.3 from pre-18 assembly lines + data bank  combination started to lag 7 time more 

Assembler connected to data bank (48 data sticks) on Pre-18

![2022-10-12_01 27 10](https://user-images.githubusercontent.com/92493145/195213189-a5e26119-2ba0-41d6-aa7d-ab802993c3ea.png)

Assembler connected to the same data bank (48 data sticks) on 2.2.3

![2022-10-12_01 56 54](https://user-images.githubusercontent.com/92493145/195213339-cf3daaaf-4b50-4dfc-8206-23d9388b0528.png)

### Your Proposal

please fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eranicus** [comment]
Did more tests and rescaned all the recipes in data bank, but results are the same as on screens. In my opinion this is very big problem considering amount of assemblers at end game bases and small time frame beetween recipes check. But the main question is what happened and why they lag x7 times compared to older pack versions ...

**Comment by Connor-Colenso** [comment]
23k ns is not really anywhere near serious issue, though I have to think this is because we now check if recipes are valid rather than just trusting the stick.

**Comment by Eranicus** [comment]
> 23k ns is not really anywhere near serious issue, though I have to think this is because we now check if recipes are valid rather than just trusting the stick.

I just pointed to the difference, maybe its not big... but its still x7 times per assembler with 20-30+ assemblers at endgame bases. Anyway if you guys from dev. team think its ok , just close the ticket.

**Comment by Sphyix** [comment]
i'm more worried about the worst time being 0.5ms honestly

**Comment by boubou19** [comment]
that is indeed concerning. We need to profile this and understand what's going on.

**Comment by Eranicus** [comment]
On my screens I was looking at recipes check moment on idle assembler and lag number also depends on amount of sticks inserted into databank

**Comment by Sphyix** [comment]
> On my screens I was looking at recipes check moment on idle assembler and lag number also depends on amount of sticks inserted into databank

all my databanks have around 100 sticks each

**Comment by minecraft7771** [comment]
This could possibly be fixed in newest TT release (Also needs newest GT5U)

**Comment by Eranicus** [comment]
> This could possibly be fixed in newest TT release (Also needs newest GT5U)

Thanks, looks like it is fixed (idle mode during recipe check)  My max tick also decreased 

![2022-10-22_16 15 42](https://user-images.githubusercontent.com/92493145/197341290-b8a0c764-5caa-4126-a799-2bd9db86c1dd.png)
