### ISSUE TITLE
Steam-tier NEI

### ISSUE THREAD

**Issue by theMegaTech** [GTNewHorizons/GT-New-Horizons-Modpack#11614]
### Your GTNH Discord Username

Мега.#3065

### Your Pack Version

2.2.3.0

### Your Server

Zvezdolet 2.0

### Type of Server

Ultramine

### Your Expectation

Tried to check some recipes in NEI for steam tier machines.
Expected to see actual info about steam total cost or usage per second.
Expected that steam machines consume 2x of EU cost.

### The Reality

![image](https://user-images.githubusercontent.com/36931007/194878860-212bbaf9-8ee5-4f56-9097-33d1b78cf36b.png)
Let's use polybenzamidole recipe for example, 1200*1.6=1920, not 960

Tried testing in creative, machine consumes 1920 steam for 960 steam recipe 
before processing
![image](https://user-images.githubusercontent.com/36931007/194879261-a5b98212-2fea-44d1-92c6-740bffc4dffa.png)
after processing
![image](https://user-images.githubusercontent.com/36931007/194879289-45ea11cb-4004-466d-a595-c76f22ae5e9c.png)
(YES, machine steam buffer is full)

That same recipe in EU
![image](https://user-images.githubusercontent.com/36931007/194880976-948ee32e-7f3a-4d28-ae85-c4c0cf062fd5.png)
It means actual recipe consumes x2 steam if steam->eu conversion is 2->1

### Your Proposal

 Reduce steam consumption in half. (Or note somewhere in questbook that steam machines consume 2x steam compared to classic steam->eu conversion).
 Fix NEI steam calculations by multiplying total cost by 2.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
Only the total seems to be incorrect. The usage and the duration are fine (1200*1.6=1920)

**Comment by chochem** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/1399 changed the usage but not the total I guess.
