### ISSUE TITLE
Make Healing Axe Quest Recipes Less Specific

### ISSUE THREAD

**Issue by henrydukepickle** [GTNewHorizons/GT-New-Horizons-Modpack#11611]
### Your GTNH Discord Username

henryduke#0140

### Your Pack Version

2.2.0.0

### Your Proposal

The recipes for some of the food items (feasts) involved in the healing axe quests should have multiple options.

### Your Goal

The healing axe quest can often feel very frustrating due to its specific nature- specifically, lavenders, coconuts, and blue orchids can be very difficult to find (lavenders for instance appear in one biome, among hundreds with BoP).

### Your Vision

The healing axe quest would remain challenging, but the challenge would be less monotonous.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
the reaction is pretty unanimous.
