### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by BenFRC5147** [GTNewHorizons/GT-New-Horizons-Modpack#11621]
### Your GTNH Discord Username

Benjamin#2348

### Your Pack Version

2.1.2.0

### Your Server

NA

### Your Actions

Trying to launch the pack from Technic Launcher, with version 2.1.2.0 selected.

### Crash Report

https://pastebin.com/Y3Xt4f4F
[crash-2022-10-11_18.44.03-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9760388/crash-2022-10-11_18.44.03-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
Looks like wrong version of CraftTweaker is downloaded. 2.1.2.0 is outdated anyway, try with later version. 2.2.0.0 has broken worldgen bug, so either using MultiMC or manually updating RWG is recommended.
