### ISSUE TITLE
Tumbaga don't have any pipe but Sterile Farm Casing need tyni pipe

### ISSUE THREAD

**Issue by Tokakitake** [GTNewHorizons/GT-New-Horizons-Modpack#11629]
### Your GTNH Discord Username

Toki#9029

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I want make Sterile Farm Casing

### The Reality

I cant make Sterile Farm Casing after update gt++ to 1.7.119-pre cuz it's need tyni pipe of tumbaga. line (2258) code from recipe  
`ALLOY.TUMBAGA.getComponentByPrefix(OrePrefixes.pipeTiny, 1)`
![image](https://user-images.githubusercontent.com/65546504/195459573-390ec14c-78ce-4166-8ee7-c2aa9862df5d.png)

### Your Proposal

fix this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Steelux8 can you first check if a material part is available before you make a recipe or plan the recipe from I ingame. And we need to discuss why the hell only gt++ need to many new alloys and can’t use some gt parts as well.

**Comment by Steelux8** [comment]
My apologies, I didn't test this one properly. I'll fix it right away.
