### ISSUE TITLE
Add MEGA Precision Laser Engraver and MEGA Mixer

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#11634]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.3

### Your Proposal

Add MEGA Precision Laser Engraver and MEGA Mixer

### Your Goal

A substantial increase in the present version of the later period, synthesis of demand, such as the gate with the new forging furnace, they are very synthesis time consumption, such as all kinds of circuit boards and alloy powders, now many piece of machine have been unable to bear the responsibility, maybe they before UEV is enough, but now it's not enough, parallel processing speed is too slow and too little, As a result, too much time is wasted on synthesis.

在现在版本的后期，合成需求大幅度增加，例如星门与新的锻造炉，他们非常消耗合成时间，例如各种电路板以及合金粉，现在的多方块机器已经无法承担应有的责任了，在UEV前或许他们是足够用的，但是现在已经不够了，处理速度太慢以及并行太少，导致在合成上浪费的时间太多。

### Your Vision

Later in the hundreds of thousands of machines to ensure that we don't have to lay their synthetic speed is enough, it can significantly improve their FPS and TPS, and later also will play more comfortable, I have to play to the MAX +, constantly hang up late and synthesis time visit really kill their own interest, I am a player from China, I hear a lot of the same thoughts

在后期我们可以不用铺设上百上千的机器来保证自己的合成速度是足够的，这可以显著的提升自己的FPS与TPS，并且后期也会玩的更加舒适，我自己就已经玩到了MAX+，后期不停的挂机与合成时间真的非常消磨自己的游玩兴趣，我是一名来自中国的玩家，我也听到了许多一样的想法

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
We have slightly different plans for new multiblocks. Check out the multiblock-madness channel on the discord. They will be much more performant (hopefully) than the current multiblocks and if we do it right they will also scale well to high tiers.
