### ISSUE TITLE
Adjust Brick/Bricks Pulverization Recipe

### ISSUE THREAD

**Issue by AnythingForProfit** [GTNewHorizons/GT-New-Horizons-Modpack#11638]
### Your GTNH Discord Username

Surreal(She/Her)#4519

### Your Pack Version

2.2.0.0

### Your Proposal

Change the brick/bricks pulverization recipe to be more common sense and inline with similar recipes 
![image](https://user-images.githubusercontent.com/51262708/195628431-7d7c0d25-902a-4e74-9573-f25a06eabc6c.png)
![image](https://user-images.githubusercontent.com/51262708/195628763-c92e50f4-3904-40c2-92e8-d178ee010e66.png)

Stone brick recipe included for comparison
![image](https://user-images.githubusercontent.com/51262708/195629003-f9840b38-6e6c-4bdc-a719-6f81b32e78fb.png)

### Your Goal

it fixes a small recipe issue that seems to not make much sense, it also affects the power used for gaining brick dust for things such as the BBF early on.

### Your Vision

Removes a small deviation from the packs standard approach to pulverization cost and time, and has a small effect on the time it takes to get brick dust early game. both improve consistency and overall quality of the pack.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
Since it changes early game balance this is unlikely to happen.

**Comment by Connor-Colenso** [comment]
No, I really oppose this. The BBF is annoying enough to get. No need to just make it more annoying by doing this.
