### ISSUE TITLE
Add a Recipe to "Cloud in a Bottle" from Chisel

### ISSUE THREAD

**Issue by DragonStorm25** [GTNewHorizons/GT-New-Horizons-Modpack#11639]
### Your GTNH Discord Username

Ant#3686

### Your Pack Version

2.2.0.0

### Your Proposal

Add a recipe to the Cloud in a Bottle item from the Chisel mod. It could be the default recipe shown here, as glass and quartz is fairly cheap for a decorative block.
![Screen Shot 2022-10-13 at 12 52 36 PM](https://user-images.githubusercontent.com/45071404/195657935-e7fe0a58-57e0-4207-b98e-e16de1f41961.png)

### Your Goal

Cloud blocks can currently only be obtained by mining the naturally spawned clouds in the Overworld. This would be very tedious for those who wish to use many cloud blocks in their builds.

### Your Vision

Adding a recipe for the Cloud in a Bottle would add another potential decorative block which is distinct from all the blocks currently available.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by cubic-chariot** [comment]
Thematically, it should be made by canning steam instead :)
