### ISSUE TITLE
Banded iron gives roasted iron dust

### ISSUE THREAD

**Issue by DlyanMatthews** [GTNewHorizons/GT-New-Horizons-Modpack#11632]
### Your GTNH Discord Username

Dlyan#9646

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Banded iron ore can be processed to get banded iron dust

### The Reality

Banded iron ore gives roasted iron dust in gregtech machines (enderIO sag mill correctly gives banded iron dust) 

### Your Proposal

Banded iron ore gives banded iron dust

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
so what you are really saying is that the enderIO sag mill is bugged/inconsistent on that.

**Comment by Dream-Master** [comment]
ender io sag mill recipes need to adjust or removed interedly. Did anyone use it ?

**Comment by DlyanMatthews** [comment]
I haven't used the sag mill recipe, just saw it in NEI. I assume banded iron ore should give banded iron dust, but if giving roasted iron instead is intended then I guess it's the sag mill that needs to be fixed
