### ISSUE TITLE
MEGA smelter does not support mineral dictionary replacement items(MEGA冶炼炉不支持矿物词典替换物品)

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#11633]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.3

### Your Server

SP

### Your Expectation

Under normal conditions, both ruthenium powders for GTPP and Bart are shown in the synthesis table for botmium alloy synthesis, and we can use the ruthenium powder of bart produced in platinum treatment for synthesis

正常情况下，合成博特姆合金时合成表中会显示支持GTPP与Bart的两种钌粉，并且我们可以使用铂处理中产出的bart的钌粉进行合成

![QQ截图20221013130225](https://user-images.githubusercontent.com/98251218/195506146-1a00821e-2b07-4434-833e-4113a5acdecb.jpg)

### The Reality

The botmium alloy will be synthesized with ruthenium powder during production, but in the current version of the synthesis table, only the ruthenium powder of GTPP is supported, but not the ruthenium powder of bart, so the botmium alloy cannot be fabricated

博特姆合金在制作时会使用钌粉进行合成，但是在现版本合成表中只支持GTPP的钌粉而不支持bart的钌粉，导致博特姆合金无法进行制作

![QQ截图20221013130148](https://user-images.githubusercontent.com/98251218/195506324-84e9afb5-0283-4fe3-a747-00556e057b54.jpg)

### Your Proposal

This is a nasty BUG that if not fixed makes it impossible to make Botham alloys and subsequent machines that need it

这是一个恶性BUG，如果不修正就无法制作博特姆合金以及后续需要它的机器

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
So someone broke https://github.com/GTNewHorizons/GTplusplus/pull/243...
But you can actually use BW ruthenium to craft Botmium. It's just visual bug.

**Comment by SafariXiu** [comment]
> No, I tried. It's not possible to use bart's. It's weird

**Comment by SafariXiu** [comment]
> So someone broke [GTNewHorizons/GTplusplus#243](https://github.com/GTNewHorizons/GTplusplus/pull/243)... But you can actually use BW ruthenium to craft Botmium. It's just visual bug.

Oh, I went to see it again just now. The MEGA smelting furnace does not support the ruthenium powder of bart

**Comment by SafariXiu** [comment]
> So someone broke [GTNewHorizons/GTplusplus#243](https://github.com/GTNewHorizons/GTplusplus/pull/243)... But you can actually use BW ruthenium to craft Botmium. It's just visual bug.

The MEGA smelter does not support bart ruthenium powder, ordinary smelter is no problem

**Comment by sintken** [comment]
bumping this to confirm MABS will not smelt botmium in 2.2.3.0, which breaks progression (botmium chemplant needed for living solder needed for UEV circuits etc)

**Comment by boubou19** [comment]
how does it break progression if it is smeltable in normal ABS?

**Comment by miozune** [comment]
Cannot reproduce on 2.2.7 with Eternal Coil + UMV glass

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
