### ISSUE TITLE
Ghost circuit support for super input buses

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#11637]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

2230

### Your Proposal

The new ghost circuit feature is really handy, it would be nice if we could use it with super buses.

### Your Goal

The GUI could look something like this, but without the extra buttons at the bottom: 
![image](https://user-images.githubusercontent.com/7230430/195604449-13cefab6-222b-433c-9b66-c5fcb6b0bc0c.png)
(GUI of super buffer)

The ghost circuit feature should be behind the Greg icon.

### Your Vision

Super buses with circuit is always a pain to setup, this would be a nice QoL change

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by kuba6000** [comment]
Already added in https://github.com/GTNewHorizons/GTplusplus/pull/349
Left mouse click with empty hand to set
