### ISSUE TITLE
[Witchery] Arthana not craftable due to Queen's gold knife blade

### ISSUE THREAD

**Issue by Dundun3Billion** [GTNewHorizons/GT-New-Horizons-Modpack#11630]
### Your GTNH Discord Username

Markua#0708

### Your Pack Version

2.2.0.0

### Your Server

SP

### Your Expectation

You cannot craft the queen's gold knife blade, which is needed to craft an arthana. The knife blade requires you to pour queen's gold into a clay knife mold. The clay knife mold has no recipe or way to craft. You cannot melt clay, clay dust, or clay compound in the smeltery, furthering that you cannot make the mold.

### The Reality

Clay knife mold to make queen's gold knife blade is not obtainable

### Your Proposal

Make mold or knife blade obtainable

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/TinkersConstruct/commit/35d4d04ee052fb6aa76908729038f524b2098f3f
