### ISSUE TITLE
Rename roasted zinc to garnierite, roasted iron to banded iron

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#11648]
### Your GTNH Discord Username

McFrugal#5033

### Your Pack Version

2.2.3.0

### Your Proposal

"Roasted" minerals are actually the oxides resulting from the roasting process.  They should be named as such, and should have the chemical formula displayed like other materials.
Iron Oxide, Nickel Oxide, etc.

### Your Goal

The problem with the "roasted" name is that it is currently overriding processed Garnierite and Banded Iron.  These are naturally formed oxides, not having been roasted at all, so it is confusing and inaccurate.
In addition, naming materials based on the chemical process used to arrive at them is a dangerous precedent as often more than one process can be used to arrive at a given chemical.  Naming items based on the physical change-- such as crushed, purified, impure-- makes sense as those are distinct physical states.

### Your Vision

Same realism, less confusion.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by McFrugal** [comment]
In addition, I have to ask if it was intended to remove the electrolyzer recipe for Banded Iron?  I can't remember if Garnierite had one too.

**Comment by chochem** [comment]
that is split intentionally. The oxide is something chemically pure that you can make in a LCR or similar. The roasted one is some impure thing of unspecified amounts that only comes from ores. This allows the roasted one to ignore chem balance without creating any undesirable loops.

See for example roasted cobalt vs cobalt oxide.

**Comment by McFrugal** [comment]
Sure.  Two issues with that:
1, does it add anything to the gameplay to have that distinction?
2, there's no nickel oxide or iron oxide, so garnierite and banded iron are still in a silly place.

**Comment by GlodBlock** [comment]
garnierite is nickel oxide and banded iron is iron oxide, they also have corresponding roasted iron/nickel. these names are kept unchanged for back compact issue.
> what loops would be possible

take cobalt for example.
you can make 2 cobalt oxide in chemal reactor with 1 coble and 1000 oxgyen, then you can smelt 2 cobalt oxide into 3 cobalt ingots in ebf with carbon dust. so you basically can turn carbon and oxgyen into these metals

**Comment by McFrugal** [comment]
> garnierite is nickel oxide and banded iron is iron oxide, they also have corresponding roasted iron/nickel. these names are kept unchanged for back compact issue.
No, when you process garnierite it turns into roasted nickel, and when you process banded iron it turns into roasted iron.  Except they shouldn't, because garnierite is a natural mineral, it has not been roasted, and literally every new player who plays the pack will be like "why is my garnierite turning into roasted nickel?!"
Adding two new item IDs will fix that.

> you can make 2 cobalt oxide in chemal reactor with 1 coble and 1000 oxgyen, then you can smelt 2 cobalt oxide into 3 cobalt ingots in ebf with carbon dust. so you basically can turn carbon and oxgyen into these metals
That's a new recipe.  Obviously if roasted minerals went back to being pure oxides, the recipes would be changed.

It occurs to me that these new recipes are completely different from how compound dusts are normally treated.  Like, to process brick dust you need 13 of it, to process basalt dust you need 16, to process olivine you need 5...  Why is cobaltite dust being treated as if each pile of it contains 1.5 piles of pure cobalt?  It should contain less than one, like every other compound.  It's inconsistent.  Is this the "chem balance" that was mentioned before?  You really, really should not ignore it.

**Comment by GlodBlock** [comment]
> It occurs to me that these new recipes are completely different from how compound dusts are normally treated. Like, to process brick dust you need 13 of it, to process basalt dust you need 16, to process olivine you need 5... Why is cobaltite dust being treated as if each pile of it contains 1.5 piles of pure cobalt? It should contain less than one, like every other compound. It's inconsistent. Is this the "chem balance" that was mentioned before? You really, really should not ignore it.

they aren't compounds since they aren't even pure, so you can get more matels from it. this recipe has been there since the gt5u added the roasted system

**Comment by McFrugal** [comment]
> they aren't compounds since they aren't even pure, so you can get more matels from it. this recipe has been there since the gt5u added the roasted system

...I'm not contesting roasted dust being impure.  I understand that conceit.  Though it would make more sense if you could only roast ore that hasn't been washed or put through a thermal centrifuge.  Also, the ebf recipes are new, regardless of what gt5u is doing.  They were added alongside roasting, which is new to GTNH.  GTNH is not gt5u.
However, there is an inherent problem with the argument of impure = more metal, because impurities are by definition NOT the metal the mineral mainly consists of.  The increased yield blast furnace recipes are just handwaving that, and are not a good foundation to argue anything.

Speaking of gt5u, it doesn't have roasted dust.  It has blast furnace recipes that take in oxygen and sulfurous minerals, outputting sulfur dioxide and various dusts.  Wanna know something cool about that?  It doesn't have the cobalt oxide recipe, so there's no loop!  If you're importing roasting into GTNH you should just do it like that.  Remove the cobalt oxide recipe, and any other recipes that let you create oxides that would result in loops.  There's no need for those recipes anyway, I don't think.
GT6 has a different implementation of roasting that uses a roasting oven block, and that also has no dusts named roasted.

I'm posting the gt5u "roasting" recipes here since it took a while for me to get a vanilla (non-GTNH) gt5u instance going and I'd like to save everyone else the time:
1 Sphalerite dust + 3000 Oxygen = 1 Zincite dust (ZnO), 1 tiny pile of Ashes, 1000 sulfur dioxide
1 Tetrahedrite dust + 3000 Oxygen = 1 Cupric Oxide dust (CuO), 3 tiny pile of Antimony Trioxide dust (Sb2O3), 2000 sulfur dioxide
1 Stibnite dust + 3000 Oxygen = 1 Antimony Trioxide dust (Sb2O3), 1000 sulfur dioxide
1 Pentlandite dust + 3000 Oxygen = 1 Garnierite dust (NiO), 1 tiny pile of Ashes, 1000 sulfur dioxide
1 Pyrite dust + 3000 Oxygen = 1 Banded Iron dust (FeO), 1 tiny pile of Ashes, 2000 sulfur dioxide
1 Galena dust + 3000 Oxygen = 1 Massicot dust (PbO), 1 silver ingot (because in that version of gt5u galena has silver in it), 1000 sulfur dioxide
1 Cobaltite dust + 3000 Oxygen = 1 Cobalt Oxide dust (CoO), 1 Arsenic Trioxide dust (Sb2O3), 1000 sulfur dioxide
1 Chalcopyrite dust + 1 Silicon Dioxide dust + 3000 Oxygen  = 1 Cupric Oxide dust (CuO), 1 Ferrosilite dust (FeSiO3), 2000 sulfur dioxide

I would say GTNH has a bad implementation of roasting.  There are no resource loops in vanilla gt5u so you're to blame if any loops happen by porting over roasting.  Spend just a little more time on it and I'm sure you can implement it better, without renaming dusts in such a silly way.

**Comment by McFrugal** [comment]
Right, I decided to help out a bit.  Apparently cobalt oxide is needed to make kevlar via a long manufacturing chain in EV.  However it requires an LCR in later steps, so the easiest solution is to just require oxygen in the first step alongside pure cobalt and acetic acid.  Also it doesn't look like kevlar is used for anything.
Zinc oxide is... oh wow there's ALREADY a loop there.  Zinc dust + oxygen = 2 zincite dust in a chem reactor.  2 zincite dust + 1 carbon dust = 3 zinc ingots in an ebf.  That's also... all it's used for, aside from electrolyzing it to get the oxygen back.  It's totally redundant with roasted zinc and all that needs to be done is removal of the zincite dust chem reactor recipe.
Cupric oxide is needed for PTMEG and butanediol (which I couldn't find any uses for, but I didn't try too hard).  Unfortunately the cupric oxide is used in an LCR recipe with completely filled slots so that's not as easy to fix...  I did some research and it looks like the dusts represent a catalyst used as a substrate so it would make more sense to simply include a CuBi/MgO-SiO2 alloy plate, which is returned in the output, perhaps at a 90% chance or something.  Regardless, the copper doesn't need to be an oxide in the first place.
Antimony Trioxide is used to make Xenoxene in what looks like a UHV or UEV recipe.  Xenoxene is completely made up so you could easily change the recipe to use pure antimony.
Garnierite isn't used for anything.
Banded iron isn't used for anything.
Massicot isn't used for anything.

My final recommendation is to specifically change roasted nickel and roasted iron back to garnierite and banded iron, as those oxides aren't used for anything and are the only ones that stand out as nonsensical.  It would be disruptive to existing factory setups to change the oxides to be non-manufacturable.  If in the future you wanted nickel or iron oxide to be manufacturable, you could just... add new dusts with those names.
The alternative is to just not have roasting at all, and/or to remove the carbon-boosting EBF recipes.  The carbon boosting recipes don't really make any logical sense anyway and will always be a risk for loops...

**Comment by miozune** [comment]
yes Zincite EBF recipe was removed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/433
