### ISSUE TITLE
Processing Array cannot pull more than 1A max for crafting and voids inputs

### ISSUE THREAD

**Issue by GDCloudstrike** [GTNewHorizons/GT-New-Horizons-Modpack#11641]
### Your GTNH Discord Username

GDCloud#2907

### Your Pack Version

2.2.3

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Trying to craft wetware lifesupport circuit boards in a PA with 64 UMV circuit assemblers downtiered to 256x UIV parallel.

### The Reality

The energy consumption of the PA becomes negative and the recipe finishes, but doesn't output anything whilst consuming all inputs.
![image](https://user-images.githubusercontent.com/93287602/195710527-b9f134e8-496c-46b7-a852-4b604834986a.png)

### Your Proposal

Make the PA support voltages above max properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueWeabo** [comment]
I am gonna look into this tomorrow and fix it. I have a clue as to why it can be happening....
