### ISSUE TITLE
Alloy Blast Smelter causes distortion of surface textures

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#11644]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The Multiblock should not be causing ground textures to distort enough to see the blocks below them.

### The Reality

![2022-10-14_09 18 43](https://user-images.githubusercontent.com/13187606/195800082-4917a576-f33d-4b14-b536-d2ddd09c9bc4.png)

This also happens to other blocks placed in there, like the Maintenance Hatch (although the texture corruption then moves to the multiblock's middle)  

### Your Proposal

Probably to fix it as this might be indicative of a bigger issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
can you try it on a vect 0 from ztones block? because i have no such issue in my base so if it reproduces with that block then it's likely an optifine/graphic card issue.

**Comment by TwoTailedFox** [comment]
This does not occur with a Vect 0 in its place.

**Comment by TwoTailedFox** [comment]
Also, I don't use Optifine with GTNH, nor am I using any shaders

**Comment by boubou19** [comment]
what are the blocks below? concrete?

**Comment by TwoTailedFox** [comment]
Yeah, Light Concrete

**Comment by miozune** [comment]
Another person reported similar issue.
![2022-10-15_02 15 17](https://user-images.githubusercontent.com/40035906/195969075-89c336e1-440d-490d-bcca-69099f4d8e4b.png)

**Comment by dvdmandt** [comment]
I've been seeing this too. Not only near GT multiblocks, but sometimes very far from them, between oak planks and cobblestone, though it seems significantly more common near them. I also have an issue with what appears to be greatly exaggerated AO of GT machines/multiblocks, that may or not be related.
