### ISSUE TITLE
integrated logic circuits aren't craftable anymore in a CAL

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#11651]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.2.0.0

### Your Server

delta

### Type of Server

Thermos

### Your Expectation

If i was kinda expecting some recipe changes in the CALs after the update, i wouldn't expect that such a low component get changed with the update.

### The Reality

It is totally gone from the CALs

![image](https://user-images.githubusercontent.com/12850933/195999702-7649876f-2137-420c-b586-516b1e91fa8c.png)

![image](https://user-images.githubusercontent.com/12850933/195999728-fbfc4798-e0ff-4e3d-bcd1-54b4bf9bb34c.png)

### Your Proposal

put the old recipe back

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
Nothing was removed intentionally as far as I know.

Looks like electronic circuits, good electronic circuits, and advanced circuits are also missing in the CAL. I am surprised anybody really uses any of these 4 in the CAL.

They all exist in the circuit assembler.

**Comment by minecraft7771** [comment]
> I am surprised anybody really uses any of these 4 in the CAL
But its way faster in the CAL and saves energy/solder too
