### ISSUE TITLE
Neutron Activator wont form

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#11657]
### Your GTNH Discord Username

Lord Peverell#3125

### Your Pack Version

2.2.3.0

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

Neutron Activator to form

### The Reality

Neutron Activator was working and formed prior to updating GoodGen to the latest jenkins build so we could cool Dalisenite as the recipe was gone. All 3 players with Activators cant get it to form. We also update Kekztech if that is at all relevant

### Your Proposal

Fix issue with GoodGen

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by joshaup1999** [comment]
The Neutron Activator does form without the maintenance hatch, but once i add it to clear the issue it unforms

**Comment by Connor-Colenso** [comment]
@GlodBlock this seems to make the multi unusable so you may want to take a look.

**Comment by GlodBlock** [comment]
it seems like the autobuild pr breaks something
