### ISSUE TITLE
Tree growth simulator not acting to documented behaviour

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#11650]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.2.0.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

The tree growth simulator acts according to the tooltip and NEI

### The Reality

1. Adding fertiliser prevents the output of logs and results in the exclusive production of saplings. This while NEI doesn't state that this is the case.
2. According to NEI the sapling should get consumed, this is not the case in practice.

### Your Proposal

There seems to be an explicit counter-incentive for using fertiliser in the current implementation. The number of produced saplings is lower and costs additional input resource in the form of fertiliser. For several groups of saplings this makes no sense at all:

- Pines have a 4x production output from logs compared to saplings (needed for ore processing)
- Natura saplings have identical postprocessing for saplings and logs, with logs winning due to the lower sapling yield.

Other versions of tree farms do always output both saplings and logs, without the need of fertiliser in the first place. I'd therefore highly recommend that the sapling output is **added** to the log output instead of replacing it.

The matter of the non-consumed sapling should of course be mentioned in NEI accordingly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Sphyix** [comment]
sapling wasn't supposed to be consumed, but just checked to change log type
not sure who added it in nei
