### ISSUE TITLE
Apple Silicon Support

### ISSUE THREAD

**Issue by LionZXY** [GTNewHorizons/GT-New-Horizons-Modpack#11666]
### Your GTNH Discord Username

Nikita Kulikov#1980

### Your Pack Version

2.2.0.0

### Your Server

SP

### Your Actions

**Steps to reproduce**
Just open GTNH client on Apple Silicon and try launch a game.

**How to fix**
- [x] Use patched version of Avaritia https://github.com/GTNewHorizons/Avaritia/pull/24
- [x] Use patched version of Eternal Singularity https://github.com/GTNewHorizons/Eternal-Singularity/pull/2
- [x] Use patched version of HydroEnergy https://github.com/GTNewHorizons/HydroEnergy/pull/18

**Result**

After the fixes above, the build works fine on MacOS Apple Silicon. Tested on the weakest notebook - MacBook Air M1
![2022-10-17_01 01 22](https://user-images.githubusercontent.com/5871715/196058270-ec533027-ff9a-4efe-8b39-8f9454fa8f61.png)

### Crash Report

[crash-2022-10-17_00.45.56-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9795684/crash-2022-10-17_00.45.56-client.txt)
[crash-2022-10-16_23.20.12-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9795686/crash-2022-10-16_23.20.12-client.txt)
[crash-2022-10-16_23.16.06-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9795687/crash-2022-10-16_23.16.06-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by draknyte1** [comment]
MacOS supports upto OpenGL 4.1, but it’s deprecated and will eventually be replaced by metal. This isn’t a permanent solution sadly.

**Comment by eigenraven** [comment]
4.1 is only supported in the core profile, while mc1.7.10 uses legacy calls (glBegin/glEnd and other immediate mode draw commands) which limits it to 2.1 on macos as is doesn't support the 3.2 compatibility profile. I don't think opengl will be removed any time soon, deprecated just means it won't get any updates or new development in this case. Too much CAD and other software depends on opengl for apple to just remove it outright
