### ISSUE TITLE
Max int shown on ender fluid conduit network instead of super tank capacity 

### ISSUE THREAD

**Issue by urso90** [GTNewHorizons/GT-New-Horizons-Modpack#11663]
### Your GTNH Discord Username

Urso

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Type of Server

Don't know

### Your Expectation

I have super tanks connected with ender fluid conduits (5625:2) and many other machines. When hovering over conduit I see all fluid storages and current fluid amount/capacity.

ETA server.
Personal World 238, x:9 z:-26, y: 53
Personal World Portal:  x:2951, z:8554, y: 65

### The Reality

Some of tanks are shown as <current fluid amount>/<max integer value> as seen on image (4 super tanks shown with this value)
![image](https://user-images.githubusercontent.com/10193495/196050717-8389a1dd-ebdd-4420-923a-e2c046776620.png)

### Your Proposal

show proper capacity value. In this case 4000000.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by fluffle** [comment]
This is because you've set voiding-when-full on them, or at least that's why mine show a capacity of maxint. I'm not a pack dev but I imagine it may be necessary for such voiding to work -- if the fill level and capacity were both 4,000,000, other mods might not realise they could still add fluid to the tank and have it voided.

**Comment by urso90** [comment]
You are totally right those 4 tanks are set to voiding mode. I didn't connect those two facts.

It still could show some more meaningfull value, but for that, I guess the change would need to be done in Ender IO mod which is probably out of scope. Just in case I am wrong, I will keep ticket open and leave closing it to some more intelligent devs.

**Comment by chochem** [comment]
please keep it open, yes. we have a fork of enderio.

**Comment by McFrugal** [comment]
As a side effect, this makes Fluid Detector Covers stop working on the tank.  They output redstone based on how full the tank is, and the capacity being set to max_int means the tank is never anywhere near full so the redstone output fails.
