### ISSUE TITLE
Make Normal Transistors Cheaper/More Accessible

### ISSUE THREAD

**Issue by henrydukepickle** [GTNewHorizons/GT-New-Horizons-Modpack#11669]
### Your GTNH Discord Username

henryduke#0140

### Your Pack Version

2.2.0.0

### Your Proposal

Normal (non-SMD) transistors should not require silicon plates - OR SMD transistors should require silicon plates/ingots

### Your Goal

As of right now, there is no reason to craft normal transistors at all- they come at a worse yield than SMD transistors, and more importantly, they are further gated than their SMD counterparts (they need kanthal to make, which needs an MV assembler + a lot of time and effort, whereas SMD just needs the MV assembler).

At the very least, if this feature is to be kept, the questline should be updated to reflect the lack of need for kanthal in MV.

### Your Vision

SMD components are supposed to be further gated than the normal version, so changing this would fix a discrepancy.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
> At the very least, if this feature is to be kept, the questline should be updated to reflect the lack of need for kanthal in MV.

there is a skip quest

**Comment by thibaut-fagart** [comment]
also... the basic transistor take sisg plate which take an eternity to make, so smd allow you to trade time for rare resources (gallium and/or tantalum)
