### ISSUE TITLE
Add redstone card support to AE2 ME interfaces

### ISSUE THREAD

**Issue by guineawheek** [GTNewHorizons/GT-New-Horizons-Modpack#11668]
### Your GTNH Discord Username

guineawheek#9117

### Your Pack Version

2.2.3

### Your Proposal

Add the redstone card as a compatible upgrade to ME Interfaces such that the ME interface will only push crafting ingredients with or without the presence of a redstone signal. This could be used in conjunction with the existing blocking mode to give more control over it. 

### Your Goal

When setting up autocrafting for more complicated setups, typically magic crafting like TC infusion or BM altars, one of the big challenges is keeping AE2 from overflowing intermediate buffers even with blocking mode. To solve this people usually either spam setups or just reach for OC/SFM 

It'd be nice for redstone logic to be able to signal "ok the setup is clear please push in the next set of items" 

This problem isn't really relevant for GT multis as there are known pure AE2/EnderIO solutions for things like assembly line

### Your Vision

Make cleaner setups and buff solutions that do not use OC/SFM 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Szajkop** [comment]
As a workaround, you could direct the interface into a gt pipe with machine controller + shutter cover. Your items will wait at "scheduled" state until the shutter is opened and you have ~1 sec to close it before a new recipe gets pushed.
