### ISSUE TITLE
Add Tiny Coal

### ISSUE THREAD

**Issue by Norm12345** [GTNewHorizons/GT-New-Horizons-Modpack#11679]
### Your GTNH Discord Username

Norm#4161

### Your Pack Version

2.2.3

### Your Proposal

Add Tiny Coal

### Your Goal

.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by POPlol333** [comment]
goal? how you see it?

**Comment by boubou19** [comment]
don't the small and tiny piles of coal/charcoal/lignite have burntime?

**Comment by Norm12345** [comment]
oh sorry i dident know they existed
