### ISSUE TITLE
[Project Red Transportation] The recipe Item Extractor Chip in the collector is more expensive than manual

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#11670]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.2.0.0

### Your Proposal

Usually in the collector recipes are more profitable but here on the contrary

![javaw_IrpqQVJoJB](https://user-images.githubusercontent.com/46845681/196298536-830d37fc-f5cc-490c-8893-7a19b53018e6.png)
![javaw_8sMrBbZLpI](https://user-images.githubusercontent.com/46845681/196298539-25f55e06-4585-4cee-9187-e9287d927140.png)

### Your Goal

Check if an error has crept in here

### Your Vision

As for me, I need to check these recipes and make corrections if necessary

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by OrderedSet86** [comment]
I mistakenly left the crafting table recipe for these as LV, they should be MV in line with https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/10802

**Comment by Eldrinn-Elantey** [comment]
> I mistakenly left the crafting table recipe for these as LV, they should be MV in line with https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/10802

I understand and support your position. We need to fix the recipes, otherwise there are problems not only with this chip

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/11889
