### ISSUE TITLE
Steam macerator and diamond hunting.

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#11688]
### Your GTNH Discord Username

Devtron#5306

### Your Pack Version

2.2.0.0

### Your Proposal

Macerator needs diamonds and newbies get stuck on getting them cause they skipped the upgrade your pickaxe  quest

### Your Goal

![image](https://user-images.githubusercontent.com/3405825/196718914-f35bcf96-ebce-4651-a802-57ce630e3444.png)
![image](https://user-images.githubusercontent.com/3405825/196719043-3901af3e-db70-4449-976b-e968cca50cd3.png)

Currently, this lovely macerator quest in the steam age needs diamonds to be able to make it, and many newbies get stuck on getting those diamonds, and cant figures out how to mine them diamonds.
To be able to mine diamonds you need 1 an upgraded bronze pickaxe, and 2 have its mining level increased by strip mining a mountain.

This explanation was in a few years ago, but the quests have been moved around and changed, so it looks like it has been lost and i would like too see it readded. 

### Your Vision

Make a new quest in front of the "Macerator v1.0" quest where they are told the following

------------------------------------
Quest name: "Put a ring on that finger"
------------------------------------
So you might have found a diamond vien at this point and have found that you are unable to mine them lovely diamonds.
Well, this might mean you skipped a step in the "Stone Age" tier,
After you have gotten your copper and tin ingots and made bronze dust, there is a quest next to it called "Making Better Tools"
This allows you to use a smeltery to upgrade your thinker's tools to bronze.

Are you still reading???

Let me guess you went mining with your shiny new bronze pickaxe and it still would not mine diamonds as the pickaxe's mining level was still too low and now you are angry at me?????

So you want to know how to increase the mining level of your now slightly used bronze pickaxe?
Well if you open your inventory and mouse over your pickaxe it will tell you its current tool level and mining level, when you upgrade a pickaxe with a new head, you need to go mine for a while to increase its mining level.
So to increase it I suggest you go mine some iron, copper, and tin, until the mining level goes up to that one level you are so desperate for at the moment.

Now excuse me while I go torture..... Sorry I mean help the next lost soul.

-----------------------------------
Quest requirements -  Hold two diamond ore.  
------------------------------------

The reason to hold two diamond ore, instead of diamonds is that some get diamonds from loot bags, or find them in the village or dungeon chests, and then later that they still complain they can't mine diamonds.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
mining level is explained already ('your first tool') and the bronze pick is marked as a main quest. I really dont see how a new quest would help with the problem of people not reading the quests or doing the main quests.

**Comment by Ethryan** [comment]
Maybe making the bronze tools quest should be required for the steam macerator.
That way they at least are forced down the correct tool path.

**Comment by Devtron3D** [comment]
I myself fell for this, as the last time I started from scratch, I had forgotten about this mining level upgrade, and so had a hard time getting diamonds.
I often see new players ask how to do it, cause they rushed into steam and have not looked back to stone age to see if they had a missing quest.
This is why i am suggesting a new quest to make them look back, to be honest, if we had a few quests early on forcing them to go back and look for new stuff anyway, it would help to engrave that habit in new players.

**Comment by chochem** [comment]
It is indeed a common question but spefically by people that dont read quests. Making a new quest that explains the same stuff again seems pointless. But yea adding that bronze tool requirement sounds good.
