### ISSUE TITLE
Can't use cheap assembler recipes to make compressed chest

### ISSUE THREAD

**Issue by BlueIceJAY** [GTNewHorizons/GT-New-Horizons-Modpack#11684]
### Your GTNH Discord Username

Neutron#6126

### Your Pack Version

2.2.0.0

### Your Server

SP

### Your Expectation

Keep them from recipe conflict then we can use cheap assembler recipes to make compressed chest.

### The Reality

Can't use cheap assembler recipes to make compressed chest.
No matter which recipe it is, it will give priority to making obsidian chest.
If you limit the number of dense obsidian plates, you can use the Circuit-2 recipe, but it is cumbersome and only saves 1 dense obsidian plates.
![J2HHHVQ`4W56P$KUJLIF (7](https://user-images.githubusercontent.com/63415263/196656229-1ea6852b-2f05-48a7-baac-9b4bc8361a27.jpg)
![Q}@WMB$% 30QOSTL`VM_{JA](https://user-images.githubusercontent.com/63415263/196653783-98415b64-5c9f-48a5-8b3d-2f2e0d111e89.png)
![9L5W6YF~$MG9EZ4TPK(%`2W](https://user-images.githubusercontent.com/63415263/196653795-0b15057d-2f97-48d7-a6e0-ac00ee685180.png)
![0CYBHILDL{BV%}91VA{3516](https://user-images.githubusercontent.com/63415263/196653935-291fa2cc-cf77-45cf-a080-f955b4384a26.png)
![)E}} _~VPN~TT$U (F4LRZ8](https://user-images.githubusercontent.com/63415263/196653948-0a04ade2-8b6d-476a-ae79-973489bc10ef.png)

### Your Proposal

add recipe circuit for obsidian chest.Keep them from recipe conflict.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
Fixed in Dev
