### ISSUE TITLE
change your first tool quests tasks (except from the end task) to optional

### ISSUE THREAD

**Issue by Norm12345** [GTNewHorizons/GT-New-Horizons-Modpack#11680]
### Your GTNH Discord Username

Norm#4161

### Your Pack Version

2.2.3

### Your Proposal

change your first tool quests tasks (except from the end task) to optional 
![image](https://user-images.githubusercontent.com/116118924/196537725-922d7708-88ec-4d07-8734-39c5d92770bf.png)
![image](https://user-images.githubusercontent.com/116118924/196537779-2f14ac4b-87ba-4083-9ba9-364634f96a67.png)

### Your Goal

almost all quests tasks (except from the end task) are optional so why not this?

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
early game quest dont have optional stuff and even have crafting quests. This has been discussed regularly and is not going to change unless Dreammaster changes his mind on that.

**Comment by miozune** [comment]
Some of the earlygame quests do have optional tasks. Patterns not being optional is just my oversight when I visited all the quests to make some tasks optional.
