### ISSUE TITLE
Make "any x circuit" craftable

### ISSUE THREAD

**Issue by ParagonX42** [GTNewHorizons/GT-New-Horizons-Modpack#11697]
### Your GTNH Discord Username

᲼᲼᲼᲼᲼᲼#3520

### Your Pack Version

2.2.0.0

### Your Proposal

Currently whenever you tier up you have to manually change certain tiers of circuits in many ae patterns, we can already encode most of them with "any" circuits but they're not craftable. Make them craftable so after setting more efficient circuit type we can just change one pattern - the one that makes "any X circuit" of given tier.

### Your Goal

Big QoL

### Your Vision

I've already played gtnh 3 times and it's mega cancer to change all circuits every time

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
"Any" circuits are a gross hack in NEI to display the circuit tiers in recipe. There only purpose is to be displayed, not crafted. Also if it was craftable, it would open many recipe loops via the disassembler.

**Comment by Divran** [comment]
just block it from being used in the disassembler then, make it one way. either that or make the oredicts button actually work

**Comment by POPlol333** [comment]
> "Any" circuits are a gross hack in NEI to display the circuit tiers in recipe. There only purpose is to be displayed, not crafted. Also if it was craftable, it would open many recipe loops via the disassembler.

Literally, they were never meant to be craftable, it's just there for nei purpose and because sometime some tiered circuit had oredictionnary issue.

**Comment by POPlol333** [comment]
You're out of context by so much. Programmable circuit allow to differenciate recipe that can actually have conflict between each other. Why in the actual world would you want to introduce craft for any x circuit ? We literally made circuit line on purpose? like if you want to use UHV circuit in your craft you most likely want to use the mainframe instead of the bio one which is more expensive. This is all about cost and choice, and if you're that much concerned about your pattern, turn on oredict in the encoder terminale ?

**Comment by POPlol333** [comment]
The fact that you're pointing out that you are switching circuit in your circuit that often make me think that you're not in the slightest near the end of this modpack and still haven't understood that each circuit line have their good and bad point. And that you basically have to select which line you want your circuit from depending on the actual tier you aim for. cf: iv->uv: crystal, uhv->wetware, uev-uxv> bio.

**Comment by boubou19** [comment]
can you stop being that aggressive and elitist? everyone plays like they want and the technical limitations have been stated. End of the story.

**Comment by ParagonX42** [comment]
> You're out of context by so much. Programmable circuit allow to differenciate recipe that can actually have conflict between each other. Why in the actual world would you want to introduce craft for any x circuit ? We literally made circuit line on purpose? like if you want to use UHV circuit in your craft you most likely want to use the mainframe instead of the bio one which is more expensive. This is all about cost and choice, and if you're that much concerned about your pattern, turn on oredict in the encoder terminale ?

1. We can still encode things with a specific circuit
2. Costs of circuits yes exactly - as you tier up certain circuits become cheaper and later you need tens of thousands of those circuits for varius things - so you're **forced** to change all your patterns **manually** to use the cheaper circuits
3. At certain point - that is after crystal circuit line - there's no point in changing patterns because crystal circuits are cheapest, but until then you have to put a lot unnecessary effort into updating your patterns
4. The point of using "any x circuit" is **for crafting things other than circuits** - obviously there are circuit lines and you can not use "any x circuit" to craft the higher tier of given line which is already a thing and refer to #1

If you're refusing to make life easier for people who play the modpack a lot (me and divran have reached uhv and higher 3 times so far and we're on 4th run) then at least try to figure out how to solve this issue in a different way. It's a terrible lot of clicking to change all the patterns once you FINALLY reach the best crafting method of a given circuit tier - e.g. microprocessors for lv in hv CA, nanoprocessors for hv in luv CA, quantumprocessor for ev in zpm CA etc.

Don't want to offtop but how was anyone here aggressive or elitist?

**Comment by boubou19** [comment]
> This idea would fix that entire issue easily. So instead, you'd simply encode all recipes using the "any" circuit and then encode the "any" circuit as being crafted from the circuit you're currently using. Then, when you need to upgrade to a better circuit of the same tier you'd just grab the encoded "any" circuit recipe and swap only that instead of having to swap 100 individual recipes.

Any circuits are oredicted, that is why they show up in NEI, this is also why if you turn off recipe filter input and allow for oredict swaps in AE, a pattern with encoded normal circuits will work.

So in the end, it's a false issue, it works for me 99% of the time like that, the 1% being the rare cases where some circuit combinations weren't registered in the game.

**Comment by iouter** [comment]
i thought the disassembler wouldn't output the "any x circuit" in theory. even if it could output, it shouldn't be able to make more advanced circuits.

and you can still choose the circuit you want to use, just change the pattern of a specific circuit.

i don't know if oredict mode is good or not. to be honest, I don't think it works fine when I want to use the new circuit.

**Comment by boubou19** [comment]
Then the proper fix is to make AE able to request any of the circuit oredicted, as it impacts basically any recipe with oredict, not just with circuits.

**Comment by iouter** [comment]
all in all, it's about how to make switching to a new circuit easier, right?

**Comment by ParagonX42** [comment]
> Then the proper fix is to make AE able to request any of the circuit oredicted, as it impacts basically any recipe with oredict, not just with circuits.

That may cause many issues with other recipes and I remember people mentioning that changing the ae simulation code is cancer. But if you could add another pattern button to allow ae not only use but also craft substitutions if it finds them - then that would be a huge QoL.

**Comment by ParagonX42** [comment]
There may be cases where AE has patterns for 2 things that share an oredict but one is more expensive than the other so you may not want to allow ae to request the more expensive one which is used in other crafting that doesn't allow oredict.

**Comment by Divran** [comment]
> You're out of context by so much. Programmable circuit allow to differenciate recipe that can actually have conflict between each other. 

boub's reason for why we shouldn't implement "convert any circuit of specific tier into wildcard item of the same tier" was that, "it would introduce recipe loops in the disassembler". I mentioned programmable circuits because they already have the ability to "convert any circuit of specific tier into wildcard item", even if the purpose of programmable circuits is different to the purpose of wildcard circuits. And since these programmable circuits already exist, yet they do not cause disassembler issues, his argument is moot.

> This is all about cost and choice, and if you're that much concerned about your pattern, turn on oredict in the encoder terminale ?

The problem is that oredict mode doesn't work, and it never has.

It's only able to use existing items of matching oredicts, but not able to request new ones. This means you are forced to manually update hundreds of encoded recipes every time you unlock the ability to craft new circuits.
Which means several hours of work.
Every time.

Of course, eigenraven's PR fixes the oredict issue, so that is absolutely definitely another way to fix this problem.
