### ISSUE TITLE
Move Platinum and SMD Quests

### ISSUE THREAD

**Issue by henrydukepickle** [GTNewHorizons/GT-New-Horizons-Modpack#11695]
### Your GTNH Discord Username

henryduke#0140

### Your Pack Version

2.2.0.0

### Your Proposal

Move the Platinum and SMD Quests in the HV tab to be at the beginning of the tab.

### Your Goal

Currently, these two are gated behind the workstations (EV circuits). The logic behind this was that platinum smelting needed kanthal coils, which were previously gated behind vac freezer. However, nowadays, kanthal coils are available and required in MV, and platinum can even be obtained without kanthal via the platline. For these reasons, there's no reason for the quests to be where they are.

### Your Vision

Players would be able to access these quests (and their rewards) earlier.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by POPlol333** [comment]
@chochem though?
