### ISSUE TITLE
GT++ ingots are not 3 -> 2 in Forge Hammer

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/GT-New-Horizons-Modpack#11699]
### Your GTNH Discord Username

ALongStringOfNumbers#9024

### Your Pack Version

2.2.0.0

### Your Server

SP

### Your Expectation

GT++ ingots should follow the 3 ingots -> 2 plates convention in the Forge Hammer, like other Gregtech ingots

### The Reality

GT++ ingots are instead 2 ingots -> 1 plate in the Forge Hammer.

This can be seen with things like Tumbaga and Potin

### Your Proposal

Change GT++ recipes to follow the 3 ingot -> 2 plate convention in the Forge Hammer.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
GT++ materials in general don't have many of the recipies that they should. I haven't played in a while, but i recall there weren't any lathe recipies for example. Maybe someone can confirm and provide more detail.
