### ISSUE TITLE
Explosion Log should include timestamp

### ISSUE THREAD

**Issue by patrick-hill** [GTNewHorizons/GT-New-Horizons-Modpack#11706]
### Your GTNH Discord Username

EventHorizon01#3263

### Your Pack Version

2.2.0.0

### Your Proposal

Basic enough request, have the Explosion.log file include timestamps so when looking to restore a backup, the timeframe is easily identified.

### Your Goal

Without this, multiple iterations of: restore backup, start server, see it's the wrong backup, rinse and repeat

### Your Vision

Will help server admins restore backups when noob's blow everything up ;)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Szajkop** [comment]
Another suggestion is not to clear the log after restart. For example: keep it by rename/zip the old explosion.log.
So when the server restarts by schedule or by crash, the previous explosions could be reviewed.

**Comment by Glease** [comment]
It really feels like we are reinventing log4j... hopefully not log4shell as well

**Comment by patrick-hill** [comment]
Commenting to remove stale label. I still think this is needed.
