### ISSUE TITLE
Fluid Input Tank: fill bug

### ISSUE THREAD

**Issue by slprime** [GTNewHorizons/GT-New-Horizons-Modpack#11703]
### Your GTNH Discord Username

slprime

### Your Pack Version

2.2.3

### Your Server

SP

### Your Expectation

*

### The Reality

![ezgif com-gif-maker (21)](https://user-images.githubusercontent.com/31038811/197239184-925c0a9d-9813-43d6-b5a4-713047853718.gif)

### Your Proposal

*

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
@Glease you may want to take a look at this
