### ISSUE TITLE
Structure failure debugger

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#11714]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

I dont play

### Your Proposal

Add a new tool(or mode to gt scanner) that will run structure check when used on multiblock controller and log information about structure check failure

### Your Goal

Will greatly reduce "why my multblock x isn't forming?" questions

### Your Vision

Will make our lives easier

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Duplicated of #10610
