### ISSUE TITLE
[QUESTION] I can't find a string to translate tinker effects

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#11713]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.2.0.0

### Your Proposal

I wanted to translate the names of improvements in the tinker tooltip, but I couldn't find their lines in the land file. It seems that they are not in either the ut or the kg file, perhaps they forgot to specify them

### Your Goal

It would be good to understand the reason for the lack of the necessary lines to be able to translate these names

### Your Vision

This will allow you to localize the assembly even more for a more comfortable game

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by wlhlm** [comment]
Tool improvents are handled by Iguana's Tinker Tweaks. Have a look in there.

**Comment by Eldrinn-Elantey** [comment]
> Tool improvents are handled by Iguana's Tinker Tweaks. Have a look in there.

There are mostly levels and there are no names of modifications in the tool tip

![image](https://user-images.githubusercontent.com/46845681/197527687-67f024cc-45f0-41c1-ac4d-c75b02c34961.png)

**Comment by Ethryan** [comment]
It’s set [here](https://github.com/GTNewHorizons/TinkersConstruct/blob/35d4d04ee052fb6aa76908729038f524b2098f3f/src/main/java/tconstruct/modifiers/tools/ModDurability.java#L62) I think, it isn’t localized from what i can see.

**Comment by Eldrinn-Elantey** [comment]
> It’s set [here](https://github.com/GTNewHorizons/TinkersConstruct/blob/35d4d04ee052fb6aa76908729038f524b2098f3f/src/main/java/tconstruct/modifiers/tools/ModDurability.java#L62) I think, it isn’t localized from what i can see.

It turns out that these values are not transferred to the lang file?
