### ISSUE TITLE
Add a way to specify preferred oredict items when clicking in from NEI into AE2

### ISSUE THREAD

**Issue by guineawheek** [GTNewHorizons/GT-New-Horizons-Modpack#11715]
### Your GTNH Discord Username

guineawheek#9117

### Your Pack Version

2.2.3

### Your Proposal

Add some new gui in NEI that would let you select preferred items for specific oredict values (e.g. always use crystal circuits when patterning a recipe that uses `circuitElite`)

### Your Goal

while fixing ae2's oredict crafting is good and all it's useful to be specific on certain crafts and you often only want to use one specific oredict option 

### Your Vision

it would be complementary to any ae2 oredict fixes because it increases specificity

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
There's already a config `transformItemPriorityList` in `NotEnoughEnergistics.cfg`. But it's not easy to use, so better way to configure would still be a good feature.
