### ISSUE TITLE
UHV Lubricant. Why and for what?

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#11720]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.2.0.0

### Your Proposal

Remove Lubricant from UHV Emitter, Sensor and Field Generator recipes.

### Your Goal

Other tiers of this components dont use Lubricant for craft.
(UV-UHV-UEV emitters for example)
![image](https://user-images.githubusercontent.com/70205464/197402254-50f51f4c-2cd9-4572-a801-074862b28e3d.png)
![image](https://user-images.githubusercontent.com/70205464/197402265-78e5b50d-c4b0-4a8e-96a9-cf43493f3312.png)
![image](https://user-images.githubusercontent.com/70205464/197402270-d1b303f7-a5be-4c3d-8032-a206ca39040a.png)

### Your Vision

This change will unify component recipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by joshaup1999** [comment]
Assline breaks arent as harsh anymore imo
