### ISSUE TITLE
Crash on server start

### ISSUE THREAD

**Issue by ImpTs** [GTNewHorizons/GT-New-Horizons-Modpack#11724]
### Your Pack Version

2.2.3

### Your Server

private server

### Your Actions

Crashes on server start

### Crash Report

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9847499/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by glowredman** [comment]
You ran out of block IDs, install [NotEnoughIDs](http://jenkins.usrv.eu:8080/job/Not-Enough-Ids/3/artifact/build/libs/notenoughIDs-1.7.10-982ffe2.jar) to fix this. This mod is required both on server and on client.

**Comment by boubou19** [comment]
this mod should be fixed with next update. Out of curiousity, how old is your map? and by any chance, do you remember what version of the modpack the map has been generated with?

**Comment by ImpTs** [comment]
My map is about 3 months old, started on 2.1.2.3qf, upgraded to a few of the pre 2.0 versions, and is now on 2.2.3. It's had a LOT of use from three pretty dedicated players over the past three months, though.

**Comment by boubou19** [comment]
that is very weird in that case because we ran into similar issue but with a map that is 7 years old. our test server never had such issues with all the updates it received.

**Comment by BritishCynic** [comment]
As this appears to be fixed with the inclusion of NotEnoughIDs (which now ships with the pack), I am closing this issue.
