### ISSUE TITLE
Quadruple Input Hatch voids input fluid

### ISSUE THREAD

**Issue by sxtyzhangzk** [GTNewHorizons/GT-New-Horizons-Modpack#11728]
### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Reproduction steps of this bug:
1. Build an LCR with IV+ input hatch so the recipe takes exactly 1 tick;
2. Place the LCR, output hatch, and the Quadruple Input Hatch (make sure to follow the order so the entities will update in this order);
3. Wrench the output hatch so the output fluid will directly go into the Quadruple Input Hatch;
4. Put 2000L hydrogen and 2000L of chlorine into the input hatch (or any other recipe that takes 1 tick);
5. Expect 2000L hydrochloric acid to appear in the input hatch.

(See the following video)

https://user-images.githubusercontent.com/7344200/197660952-d19ef4d8-c592-49aa-92f6-d4e3f37e5877.mp4

### The Reality

Only 1000L of hydrochloric acid is left in the input hatch. The other 1000L is voided.

Note that the bug also happens randomly when using AE (AE2FC) to automate the LCR.

### Your Proposal

A possible root cause of this bug is in [GT_MetaTileEntity_Hatch_MultiInput.java](https://github.com/GTNewHorizons/GT5-Unofficial/blob/d1d6c620c123c5001fb5b9670686f567991aafb5/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_MultiInput.java#L171):

```java
// public int getFirstEmptySlot()
if (mStoredFluid[i] == null || mStoredFluid[i].amount <= 0) return i;
// public void addFluid(FluidStack aFluid, int aSlot)
if (mStoredFluid[aSlot] == null) mStoredFluid[aSlot] = aFluid.copy();
// public int fill(FluidStack aFluid, boolean doFill)
addFluid(tFluid, getFirstEmptySlot());
```

When the LCR depletes the hydrogen (slot 0) and chlorine (slot 1) in the input hatch, the fluid amount becomes 0. As the `fill` method is called before the input hatch updates (the update order is LCR->output hatch->input hatch), it is not reset to `null`. 
The `getFirstEmptySlot` returns slot 0 but the `addFluid` refuses to put it inside since it is not `null`. The `fill` method did not check that and returns normally, which voids the input fluid.

A potential fix is to change 
```java
// public int getFirstEmptySlot()
if (mStoredFluid[i] == null || mStoredFluid[i].amount <= 0) return i;
```
to
```java
// public int getFirstEmptySlot()
if (mStoredFluid[i] == null) return i;
```
so the behavior matches `addFluid`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by guineawheek** [comment]
can confirm this bug, i have no idea how you managed to figure out how to reproduce it but kudos to you
