### ISSUE TITLE
Rework/balance of Crystal, Wetware and Bioware Circuits

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#11729]
### Your GTNH Discord Username

Lord Peverell#3125

### Your Pack Version

2.2.3.0

### Your Proposal

Rework of Crystal+ circuits at later tiers. Current Circuit tiering is a major mess up on late game. Being UEV i still heavily use Crystal Circuits as they are the much cheaper alternative to Wetware/Bioware circuits even though they should have cheaper alternatives.

I made 130 UHV lasers yesterday and chewed through 1.5+ million palladium not to mention a bunch of other lower tier resources and alloys since it needs Crystal components

Optical SMDs are an option for these circuits yes.. But all they do is increase time in the CALs and dont offer more yield

We need to focus on these changes before introducing UIV+ circuits imo cause its just a mess

### Your Goal

Make Wetware/Bioware more viable to use 

### Your Vision

Stop the mass spam of IV circuits at higher tiers. There should be less recursivness and more output for circuits than it staying the same or a marginally better time 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by joshaup1999** [comment]
Oh also, can we adjust the bloody mutated solder recipe... -1000k fluid is just not possible. More so for a pack that strives for "realisim" where it can

**Comment by POPlol333** [comment]
To make the bioware more viable we could maybe make the bio catalyst and neutronium sink less important

**Comment by joshaup1999** [comment]
Wetware is not fine, Its an sink for palladium and IV components and circuits

**Comment by POPlol333** [comment]
And ? it's literally the next circuit line, they aren't so far apart

**Comment by POPlol333** [comment]
indeed, circuit have better craft the further you get in the game, but I believe those lack because there was no further content at that time

**Comment by joshaup1999** [comment]
Times have changed, there now is indeed content at those tiers. So it should be revied before UIV+ circuits get implemented

**Comment by boubou19** [comment]
Boards in electronic are just dumb substrate. Why would one ever need to put circuits on a substrate? normally, you add discrete or localised components on the board or in the board to realise the function of your circuit. But the board itself is nothing more than a plate made of one or multiple layers of dielectric material.

In the current state, the boards are more of a circuit that gets upgraded than an actual board. It makes no sense.

Aside from wetware and bioware boards, do you see any sensor/pump used in the craft of the boards? no.

Why would these one be different? what does justify this non sense lorewise?

**Comment by joshaup1999** [comment]
Adam raised an interesting point of possible nanotech for circuit board, could use them as they’re adaptive. Hell even a bio gel board might be an idea for those tiers as they’re organic in nature

**Comment by AtomicGrog** [comment]
"Why would one ever need to put circuits on a substrate?" I saw the bio board having circuits as conceptually maintaining bio compatible environment to operate, along with the pump and petri etc. but lets fact it were way into theoretical. I question the tiering though... such an arrangement wouldn't need something like a UV circuit to manage the situation, and having a mainframe option in the recipe... well hmm how big exactly is this board?. Imho we should be targeting the equiv of simple arduinos. Maybe using simple circuits like the currently useless ulv line having 1 per board, not a complex one per 16.

**Comment by POPlol333** [comment]
We need stupid amount of those board later on, so that mean more ulv materials spams if we do 1:1 circuit:board, which is bad and we are trying to avoid it

**Comment by AtomicGrog** [comment]
Maybe attach a soc then? avoid the board.

**Comment by chochem** [comment]
I guess this can be closed. The CAL times are fixed, and the non-recursive board making in the new multi has been merged.
