### ISSUE TITLE
Typo: "Chicken Parmasan"

### ISSUE THREAD

**Issue by benjamin-kirkbride** [GTNewHorizons/GT-New-Horizons-Modpack#11726]
### Your Pack Version

2.2.3

### Your Server

private

### Type of Server

Don't know

### Your Expectation

The item would be spelled correctly.

### The Reality

![image](https://user-images.githubusercontent.com/3373830/197449111-628c4986-f23d-468f-bccb-eb6e2a8ae487.png)

### Your Proposal

![image](https://user-images.githubusercontent.com/3373830/197449246-e64c141a-22dc-4672-b470-7fc709132cb0.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by benjamin-kirkbride** [comment]
Also, if I may be so bold, require pasta noodles as an ingredient, and buff the hunger/saturation. Chicken Parm is my favorite food, is why I am so passionate about this.

**Comment by benjamin-kirkbride** [comment]
I can't seem to find the repo with the GT:NH Harvestcraft fork. The link in the README is dead (perhaps should be it's own issue). If someone can link me to it, I could probably put in a PR for this.

**Comment by glowredman** [comment]
The repository is private, which means the link only works if you have access.

**Comment by benjamin-kirkbride** [comment]
@glowredman I see, may ask why?

**Comment by POPlol333** [comment]
original mod author request

**Comment by boubou19** [comment]
wish of the original author

**Comment by benjamin-kirkbride** [comment]
Understood. Well, if I'm granted access I'd be happy to take a stab at it, but if that isn't possible and/or wouldn't be worth it for this issue, then I understand :)

**Comment by benjamin-kirkbride** [comment]
:raised_hands:
