### ISSUE TITLE
Active transformer explodes if formed with not enough High Power Casing

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#11727]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

delta

### Your Server

delta

### Your Expectation

Expected Active Transormer to never explode, since the rest of the explosions with it were disabled.
It now doesn't explode if hot-swapped

### The Reality

I placed too many energy hatches on one, leaving it with only 2 High Power Casing, it exploded

### Your Proposal

Remove this explosion aswell or update the description (it actually says that it will explode if broken while running, this is not true anymore)
![javaw_R7udmA78zN](https://user-images.githubusercontent.com/17811922/197474446-f0bd3bf8-f3b7-4455-a4a8-6e62154b9c8c.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by POPlol333** [comment]
I'll look into this this afternoon

**Comment by minecraft7771** [comment]
Who said it was removed? It's still intended to explode when broken while running

**Comment by POPlol333** [comment]
noticed it doesn't too on our instance with GD, unless I'm god at hot-swaping

**Comment by Sphyix** [comment]
so it's only possible to hot-swap, but if broken it's supposed to explode?

**Comment by POPlol333** [comment]
it should explode if at a structure check start and fail with a checkrecipe on

**Comment by boubou19** [comment]
it's plain dumb. Iirc we disabled dynamo explosions inside the turbines, so we might as well disabling it for the active transformer

**Comment by Sphyix** [comment]
Being able to hotswap is already decent, but it's luck based.
Shutting off an active transformer can be a pain, disabling explosions on it completely could be good.
I can make a new ticket with a suggestion if needed.

**Comment by boubou19** [comment]
well if i don't get how turning it off can be a pain. You'll need to turn it on again even if you unform it and it doesn't explode anymore

**Comment by Sphyix** [comment]
> well if i don't get how turning it off can be a pain. You'll need to turn it on again even if you unform it and it doesn't explode anymore

everything connected to it shuts off, it's like turning off an LSC with a bunch of dynamos on it, they all go offline

**Comment by Eranicus** [comment]
After several booms , I started to consider transformer behaviour as a feature :)

**Comment by boubou19** [comment]
> to continue the example, imagine a bunch of passive multis, all connected to an active transformer, normally they are redstone-controlled to avoid voiding/overfilling or just to stop when a certain number of items is reached,
Turning off the active transformers for those machines means removing redstone power to all of them, swap active transformer stuff, enable all of them again.

well disabling the multi exploding when dismantled while running doesn't prevent it to unform. So you still have to turn it on again, which means during the downtime, your machines stopped. Disabling the explosion won't change that.

**Comment by Szajkop** [comment]
Just make them to behave like the LSC. Im also tired of the explosions and the other pain what they introduce.
One workaround what we found to avoid soft malletting and mass voiding is to put a wireless redstone cover on all the machines and just flip the switch to shut down all the multis at the base. for one transformer...? With the LSC we could just break a not used casing and insert a new dynamo. I dont see it why we cant have this feature here.

**Comment by minecraft7771** [comment]
> Just make them to behave like the LSC. Im also tired of the explosions and the other pain what they introduce. One workaround what we found to avoid soft malletting and mass voiding is to put a wireless redstone cover on all the machines and just flip the switch to shut down all the multis at the base. for one transformer...? With the LSC we could just break a not used casing and insert a new dynamo. I dont see it why we cant have this feature here.

I can see why you think the explosion is annoying. However the transformers behaves exactly like the LSC otherwise. When you just break a casing and replace it with the new dynamo it wont explode if you're fast enough. On the LSC you also need to be fast enough, otherwise it would shut off and all your machines would void too.

**Comment by Sphyix** [comment]
If it shuts off, considering all the buffers of possible transformers, dynamos and energy hatches there's a good chance I can avoid any voiding.
If the whole transformer disappears, it's going to stay offline for at least 2 minutes while i rebuild it.

**Comment by Szajkop** [comment]
> > Just make them to behave like the LSC. Im also tired of the explosions and the other pain what they introduce. One workaround what we found to avoid soft malletting and mass voiding is to put a wireless redstone cover on all the machines and just flip the switch to shut down all the multis at the base. for one transformer...? With the LSC we could just break a not used casing and insert a new dynamo. I dont see it why we cant have this feature here.
> 
> I can see why you think the explosion is annoying. However the transformers behaves exactly like the LSC otherwise. When you just break a casing and replace it with the new dynamo it wont explode if you're fast enough. On the LSC you also need to be fast enough, otherwise it would shut off and all your machines would void too.

So its basically RNG that the transformer blows up. Or is there a specific waiting time for hot swapping before it blows up? I noticed that sometimes the LSC shuts down after replacing hatches but atleast that doest cause a chain reaction blowing up the whole base and forcing a backup. Im still standing behind the idea to disable the exploaions coming from modifications. However, overvoltaged hatches should blow up coz incorrect use of components, otherwise it should just turn off if the hotswap time window is exceeded and the structure is still invalid.

**Comment by Sphyix** [comment]
I agree, make it explode if an hatch on the active transformer explode.
Remove the explosion in any other case.
This should align it with the rest
