### ISSUE TITLE
Got a power jump, world got corrupted. 

### ISSUE THREAD

**Issue by xSpinel** [GTNewHorizons/GT-New-Horizons-Modpack#11731]
### Your GTNH Discord Username

Mifune#0001

### Your Pack Version

2.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Went AFK, came back and realised a power jump happened, so I loaded up the pack and my world, it crashed. I even used old saves (backups) and it still was crashing. "Reinstalled" the pack but still the same issue, even updated to 2.2.3 (as some people suggested on the discord), still was crashing.

### Crash Report

[crash-2022-10-25_18.20.15-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9862539/crash-2022-10-25_18.20.15-client.txt)
[crash-2022-10-25_18.20.09-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9862540/crash-2022-10-25_18.20.09-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
World corruption. Nothing we can do about it. Sorry.
