### ISSUE TITLE
Tantalum smelting change reversal

### ISSUE THREAD

**Issue by GeldVonTarsus** [GTNewHorizons/GT-New-Horizons-Modpack#11738]
### Your GTNH Discord Username

geldvontarsus#4366

### Your Pack Version

2.2.0.0

### Your Proposal

Tantalum should revert to being a furnace recipe, rather than requiring an EBF and vacuum freezer. 

### Your Goal

Ender IO is a great utility mod beginning in MV, which has already been nerfed by the silicon change. Requiring the player to have the facilities to create titanium (Kanthal coil EBF and vacuum freezer) before they can make their first basic capacitor is ridiculous and completely disincentivises the use of Ender IO for the player. A very useful mod in the early game of MV, this is reflected in the questbook with Ender IO being some of the first quests you receive. Moving the mod to the end of MV and into HV breaks the flow of questbook and there's little incentive for the player to go back and complete them.

### Your Vision

MV would be given some of the best early game content that was just taken away from it back, making progressing through it much more enjoyable as well as facilitating early game magic progression.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GeldVonTarsus** [comment]
A possible compromise is it remaining an EBF recipe but requiring cupronickel coils and producing a finished ingot not a hot one. Ender IO should be accessible from the start of MV, as is implied in the questbook.

**Comment by Dream-Master** [comment]
> A possible compromise is it remaining an EBF recipe but requiring cupronickel coils and producing a finished ingot not a hot one. Ender IO should be accessible from the start of MV, as is implied in the questbook.

The Questbook can be updated. Not sure about temp from tantalum. Reduce process time is possible.

**Comment by GeldVonTarsus** [comment]
Its not about the questbook its about paced and balanced gameplay. The beginning of MV is the perfect time to introduce Ender IO as more power options and magic content becomes available. Introducing it too late simply allows it to be cannibalised by higher tier alternatives.

**Comment by iouter** [comment]
putting tantalum in the ebf will just disgust the player because there are already too many materials need the ebf.

**Comment by boubou19** [comment]
i think that cooling ingots shouldn't happen before EV materials. For steel, aluminium and stainless steel you don't cool them. So why would you put it behind cooling? as it's supposed to be MV content, it looks weird.

**Comment by Dream-Master** [comment]
Tantalum have a very high melting point. We can make cooling shorter but breaking ebf temp logic is even more wired

**Comment by iouter** [comment]
or dont use tantalum at MV

**Comment by Dream-Master** [comment]
Beside ender io tantalum have no use. Smd parts can be made later

**Comment by iouter** [comment]
let aluminum can also make some eio simple components.

**Comment by Dream-Master** [comment]
> let aluminum can also make some eio simple components.

we have enough materials . Btw capacitors need to buff a bit 4 tantalum bolts are to much. Two must be enough or 4 from another material.

**Comment by iouter** [comment]
> > let aluminum can also make some eio simple components.
> 
> we have enough materials . Btw capacitors need to buff a bit 4 tantalum bolts are to much. Two must be enough or 4 from another material.

I suggest aluminium because there are aluminum capacitors in reality, and tantalum capacitors are more advanced capacitors.

**Comment by GeldVonTarsus** [comment]
Problem is if you go down that road tantalum essentially becomes pointless and you'd have to change ore generation etc. I think its a good middle ground where its a rare but specific ore. The real time consumption is then exploring which isnt a bad thing so early game. But adding a 2 step smelting process on top is insane.

**Comment by Dream-Master** [comment]
> Problem is if you go down that road tantalum essentially becomes pointless and you'd have to change ore generation etc. I think its a good middle ground where its a rare but specific ore. The real time consumption is then exploring which isnt a bad thing so early game. But adding a 2 step smelting process on top is insane.

This is pure GT Logic. Tantalum have a very high smelt temperature so it will be use a vac freezer. I make it more easy add a coolant recipe. Now with my pr the time is much shorter to process.

**Comment by Dream-Master** [comment]
<https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/439>

**Comment by Dream-Master** [comment]
i will add the capacitor change in a few mins

**Comment by GeldVonTarsus** [comment]
what is the capacitor change, are you cutting tantalum out?

**Comment by GeldVonTarsus** [comment]
look your change doesnt even begin to address the problem ive brought up and fixes nothing

**Comment by Dream-Master** [comment]
yes i use alu 4 bolts make 1 capacitor and using tantalum 2 bolts make 2 capacitor.
BTW i see we have silver capacitors backported from 1.12. Didnt the work as tier 1 capacitor as well ?

**Comment by GeldVonTarsus** [comment]
okay thats fair enough

**Comment by Dream-Master** [comment]
```JAVA
            GT_Values.RA.addAssemblerRecipe(
                    new ItemStack[] {
                            GT_OreDictUnificator.get(OrePrefixes.bolt, Materials.Aluminium, 4),
                            GT_OreDictUnificator.get(OrePrefixes.foil, Materials.Manganese, 4),
                            GT_Utility.getIntegratedCircuit(1)
                    },
                    Materials.Plastic.getMolten(288),
                    GT_ModHandler.getModItem("EnderIO", "itemBasicCapacitor", 1L, 0),
                    200,
                    30);
            GT_Values.RA.addAssemblerRecipe(
                    new ItemStack[] {
                            GT_OreDictUnificator.get(OrePrefixes.bolt, Materials.Tantalum, 2),
                            GT_OreDictUnificator.get(OrePrefixes.foil, Materials.Manganese, 4),
                            GT_Utility.getIntegratedCircuit(1)
                    },
                    Materials.Plastic.getMolten(288),
                    GT_ModHandler.getModItem("EnderIO", "itemBasicCapacitor", 2L, 0),
                    200,
                    30);```

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/198115656-5ac9bafb-555e-4450-8605-cc43346efecf.png)

**Comment by Dream-Master** [comment]
this is the silver capacitor. It must be even with basic capacitor. Maybe they wrongly integrated and not work fully never tested.

**Comment by GeldVonTarsus** [comment]
the silver capacitor is only really used as part of a long chain for making the dimensional transceiver so doesn't matter

**Comment by GeldVonTarsus** [comment]
no its not wrong every ender io capacitor has that same ID

**Comment by Dream-Master** [comment]
If you check here the capacitors are the same so my guess it the implementation dont work.
https://ftb.fandom.com/wiki/Capacitor_(Ender_IO)
