### ISSUE TITLE
GT New Horizons crashing on startup

### ISSUE THREAD

**Issue by Kinger-Burg** [GTNewHorizons/GT-New-Horizons-Modpack#11737]
### Your GTNH Discord Username

Kinder#4192

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I installed Optifine 1.7.10 E7, entered my singleplayer world, tried to open my food bag (I forgot it's name, that bag you get early on to store food with 3 slots), crashed the game (spice of life I think), removed optifine from my mods folder, crashes when i try to open the game, put that optifine mod back in the folder, still crashes, tried to use optifine D6, still crashes.
Can't open the game not even on the loading screen.

### Crash Report

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9869409/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
Openmodslib isn't present. try reinstalling your pack after you backed up your world.
