### ISSUE TITLE
Oil Drilling Rig

### ISSUE THREAD

**Issue by TimberDimber** [GTNewHorizons/GT-New-Horizons-Modpack#11733]
### Your GTNH Discord Username

TimberDimber#7872

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

When I interacted with people on Discord, I found out that one fluid source and a T4 Oil Drilling Rig should produce a LOT of fluid, enough for at least a week. After that, I was told that there is a formula on the wiki to calculate how much fluid I would get.

### The Reality

I went and found the source of the average amount, which can be found on the current tier:
![image](https://user-images.githubusercontent.com/22298720/197884444-c2224d28-2e67-48b9-b5e7-4a39a85b45fa.png)

Next, substituting the sum of all chunks into the formula, which was repeatedly mentioned in the discord
![image](https://user-images.githubusercontent.com/22298720/197884581-fb70e045-ddf1-43b0-9303-3d85162b047f.png)

I got a value that is sufficient for pumping for a long time, as well as sufficient for 321 distillation operations.
![image](https://user-images.githubusercontent.com/22298720/197884961-be776baa-207b-4e76-a5c8-77ed86539dff.png)

Leaving the system running for a few days, I noticed that the pump had practically stopped producing liquid, checking - I found that the source was almost completely extracted
![image](https://user-images.githubusercontent.com/22298720/197885418-05b260d7-78c3-4f09-8023-090807fb241c.png)

But at the same time, I got only 3 results of the work, which was 125 times less than what was calculated. (only ~309 750 000)
After that I repeated it on another source - I also got 125 times less than expected.

### Your Proposal

If it's really a bug - fix it so that the pump gets as much as it should, if it's a problem in the formula - make it correct or add the correct formula to the description of the pump.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
You are calculating with wrong parameters. 

1. X is 5, not 1.
1. The formula is for per chunk total output, not per vein total output. As you can see there is a N^2 in formula, so they cannot be simply added together. 
  You are calculating the total output of a chunk with 6400L (number simplified for the sake of illustration) output per work, not 64 chunk with 100L output per work. 
  After 1000 work your hypothetical chunk would still give out 1*6395L of fluid, while in reality it will only give 64*95=6080L of fluid. In your hypothetical case, the vein will last 1000*(6400/5) cycle. In reality it only last 1000*(100/5) cycle.
