### ISSUE TITLE
High tier Cable Diode

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#11736]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.2.0.0

### Your Proposal

Additional CableDiodes recipes for Tier UHV and above

### Your Goal

To prevent some issues and to manage power

### Your Vision

More advanced power management

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by POPlol333** [comment]
You mean the Diode from bartworks? the craft are basically bugged lol

**Comment by yukieiji** [comment]
> You mean the Diode from bartworks? the craft are basically bugged lol

Yeah, But it doesn't look buggy to me personally.

**Comment by POPlol333** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8536#issuecomment-1200288819

**Comment by yukieiji** [comment]
> https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8536#issuecomment-1200288819

Thank you.
That ticket is closed because it was missed
