### ISSUE TITLE
Cell disappears with Phthalic Acid Cells recipe.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#11744]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.2.0.0

### Your Server

private server

### Type of Server

Crucible

### Your Expectation

Oxygen Cell × 54 + Potassuium Dichromate Dust × 1 + 1,2-Dimethylbenzen 9000L  => Phthalic Acid Cells × 9 + Empty Cell × 45 + Water 18000L
Oxygen Cell × 6 + Tiny Potassuium Dichromate Dust × 1 + 1,2-Dimethylbenzen 1000L  => Phthalic Acid Cells × 1 + Empty Cell × 5 + Water 2000L

### The Reality

Oxygen Cell × 54 + Potassuium Dichromate Dust × 1 + 1,2-Dimethylbenzen 9000L  => Phthalic Acid Cells × 9 + Empty Cell × 9 + Water 18000L
Oxygen Cell × 6 + Tiny Potassuium Dichromate Dust × 1 + 1,2-Dimethylbenzen 1000L  => Phthalic Acid Cells × 1 + Empty Cell × 1 + Water 2000L

![2022-10-27_23 32 27](https://user-images.githubusercontent.com/40425798/198318019-24b93c61-6857-4bd3-ad2d-f3dbe4ade0eb.png)
![2022-10-27_23 32 39](https://user-images.githubusercontent.com/40425798/198318044-8e450a1d-24a1-44ba-bdd3-afc7ecba4a40.png)

### Your Proposal

Increase output of empty cells

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1489
