### ISSUE TITLE
Add recipe for Luggage from OpenBlocks

### ISSUE THREAD

**Issue by Minepolz320** [GTNewHorizons/GT-New-Horizons-Modpack#11749]
### Your GTNH Discord Username

Minepolz320#9473

### Your Pack Version

2.2.0.0

### Your Proposal

I think that would be an interesting thing in terms of use
![image](https://user-images.githubusercontent.com/42765118/198538178-a11f3b9e-af09-4e6e-a335-e3bf99f2deae.png)

### Your Goal

Add recipe in thaumcraft for Luggage 

### Your Vision

I think it will be a funny thing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
It does?
![2022-10-28_18 39 56](https://user-images.githubusercontent.com/40035906/198557081-366bc070-d4bf-4ae8-823c-b48261128972.png)

**Comment by Minepolz320** [comment]
Oh sorry
