### ISSUE TITLE
Forestry alveary displaying incorrect temp and humidity

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#11740]
### Your GTNH Discord Username

Tommeh#9804

### Your Pack Version

2.2.0.0

### Your Server

Private server

### Your Expectation

Bees normally only work at certain temps and humidity if no tolerance is present.

### The Reality

However, the temps and humidity displayed in the alvearies is wrong together with the humidity and temp displayed in the general info display at the top left 
![image](https://user-images.githubusercontent.com/39203645/198114348-e4e48fe5-92fc-4ef4-abef-dddf4f0b7ae6.png)
![image](https://user-images.githubusercontent.com/39203645/198114682-cd7e562c-88fe-4a9f-b153-c7a71345baf8.png)

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
I should note that initially the values were correct, but at some point they suddenly changed, both for existing and new alvearies, no matter where you put them in the world

**Comment by iouter** [comment]
https://github.com/GTNewHorizons/ForestryMC/blob/10df035419f069d93a70af8b2ee1dc6893363ed9/src/main/java/forestry/core/gui/ledgers/ClimateLedger.java#L32

**Comment by iouter** [comment]
looks like forestry will calculate the effect of y, but i dont know how it did.

**Comment by iouter** [comment]
found it, https://github.com/GTNewHorizons/ForestryMC/blob/10df035419f069d93a70af8b2ee1dc6893363ed9/src/main/java/forestry/apiculture/tiles/TileBeeHousingBase.java#L81.

**Comment by Tommeh1** [comment]
Although the commit above might fix it for ingameinfo, this will very unlikely fix it for the alvearies.

**Comment by Tommeh1** [comment]
Some more, perhaps useful details can be seen in my conversion with iouter in the GNTH discord here: https://discord.com/channels/181078474394566657/401118216228831252/1035379858437586997
