### ISSUE TITLE
Crash on canceling out of AE essentia craft dialog in Essentia Terminal

### ISSUE THREAD

**Issue by Zap0** [GTNewHorizons/GT-New-Horizons-Modpack#11751]
### Your GTNH Discord Username

Zap#7261

### Your Pack Version

2.2.3

### Your Server

private local solo server

### Type of Server

Vanilla Forge

### Your Actions

open essentia terminal and click a type you have none of, opening the craft dialog. After selecting an amount and proceeding to the cpu selection, hit cancel. Crash. Repeatable for me.

### Crash Report

https://pastebin.com/x619qLnY

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Zereff06** [comment]
I have the same, v 2.2.3, um and crash

**Comment by greesyB** [comment]
This is probably the same issue as #11628. Update AE2 to version 116 or later and see if issue persists.

**Comment by BritishCynic** [comment]
As fix appears to have been made, I am closing this issue. If issue persists on a cutting-edge version of AE2 please comment to reopen.
