### ISSUE TITLE
Singularity crafting optimization 

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/GT-New-Horizons-Modpack#11753]
### Your GTNH Discord Username

@dahgul#1726

### Your Pack Version

2.2.0.0

### Your Proposal

extend slot stck limit to ~8182 (2^13)

### Your Goal

now, due to the 64 block limit, you need a buffer (~iv) , and the recipe is divided into the number of blocks that can fit into it,

### Your Vision

automation of the production of singularities will consist of a neutronium compressor, an interface and a recipe for which materials will come in one operation

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
I'd go further and suggest that a GT machine should be added to do the recipes of the Avarita Compressor.
