### ISSUE TITLE
No player sound when "Friendly Creatures" are turned off

### ISSUE THREAD

**Issue by benjamin-kirkbride** [GTNewHorizons/GT-New-Horizons-Modpack#11752]
### Your Pack Version

2.2.3

### Your Server

private

### Type of Server

Don't know

### Your Expectation

When "friendly creatures" sound is off, it would have no effect on player sounds (walking, breaking blocks, etc)

### The Reality

https://bugs.mojang.com/browse/MC-36360

### Your Proposal

This may not be a feasible thing, but backporting this fix would be really cool.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cleptomania** [comment]
I've made a PR to fix this via Hodgepodge: https://github.com/GTNewHorizons/Hodgepodge/pull/143
