### ISSUE TITLE
inconsistent advanced nitinol plates in the matter fabrication cpu

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#11755]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.2.0.0

### Your Proposal

![image](https://user-images.githubusercontent.com/12850933/198729626-dbed8871-f36e-47f3-91df-26ae793a2a55.png)

the circled plate is actually a double, while the rest are simple ones. That makes no sense at all. Let's replace it for a normal one, just like the others.

### Your Goal

.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
lets collect stuff because there are much more recipe chnages and tweaks gt++ is needed
