### ISSUE TITLE
Pseudo-inversion sigil doesn't make stable ingots

### ISSUE THREAD

**Issue by Borjomm** [GTNewHorizons/GT-New-Horizons-Modpack#11756]
### Your GTNH Discord Username

Borj♿m#2232

### Your Pack Version

2.2.2.0

### Your Server

Zeta

### Your Expectation

Unstable ingot recipe with Pseudo-inversion sigil should produce stable version of unstable ingots (they don't explode)

### The Reality

Pseudo-inversion sigil crafts "boom-boom" ingots
![Снимок экрана (622)](https://user-images.githubusercontent.com/65873997/198750620-4d5baa6a-7c20-41cc-a0ca-1e3461c6a5b8.png)

### Your Proposal

Just a weird bug that significantly decreases the reward for stabilization shenanigans

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
more precisely, it should make Mobius "Unstable/Stable" Ingots.
