### ISSUE TITLE
Radon generation with ENDLESS catalik 

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/GT-New-Horizons-Modpack#11754]
### Your GTNH Discord Username

@dahgul#1726

### Your Pack Version

2.2.0.0

### Your Proposal

Add a new level of radon-generation recepie ,whithout plutonium cycle-smelting 
![image](https://user-images.githubusercontent.com/35747549/198714017-fb4a4aec-ab7b-406d-a62f-ad9e897e0052.png)
and
![image](https://user-images.githubusercontent.com/35747549/198714312-a5b7ec19-38d9-497a-834c-8114365707a2.png)
molten uranium whithout air 
Singulariti-unconsumeble 
iv tier (7600 eu/t) 60 sec 9 120 000 total

### Your Goal

Fewer - extra machines!
More - the possibility of overclocking!
Fun!

### Your Vision

-//-//-   /\
              |
              |

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Did you know about the decay radium mechanics in gt++ to get radon?  The Plutonium Uran recipe is nonsens and need a rework.

**Comment by Cinobi** [comment]
> Did you know about the decay radium mechanics in gt++ to get radon? The Plutonium Uran recipe is nonsens and need a rework.

Dont tell me u are serious xD

**Comment by dahgul333** [comment]
> Did you know about the decay radium mechanics in gt++ to get radon? The Plutonium Uran recipe is nonsens and need a rework.

Considering how many recipes for melting on radon, it sounds like everything will break everything ...

**Comment by Dream-Master** [comment]
> Did you know about the decay radium mechanics in gt++ to get radon? The Plutonium Uran recipe is nonsens and need a rework.

Maybe a rework sounds wrong. I mean change the recipe after a dicussion and add a new one for high tier radon making. And always remember a recipe change is not a nerf always it can be a buff too.

**Comment by Dream-Master** [comment]
And if no one undertsand what i mean i comment in German.

**Comment by Dream-Master** [comment]
And one thing more. If i write rework i mean a recipe tweak.
