### ISSUE TITLE
Montly Ticket for Quest Changes

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#11765]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.2.3

### Overview

A ticket for any large or small problems with any quests. Just post below. Of course, you can also make a dedicated ticket. In particular for more indepth suggestion or problems.

The most up-to-date quest files can always be found here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/betterquesting/DefaultQuests.json

Below are the remaining things from last month (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11385):

### Quest Changes
- [ ] **Quest.1305 For Fluid Recipes**

  It's better to mention that "AE2FC do fluid recipes better" or something in this quest, imo. EC2 is slow and buggy.

- [ ] https://github.com/GTNewHorizons/GT5-Unofficial/pull/1146 reworked turbine materials, so quests related to turbine materials need to be checked to confirm if any changes are needed.

- [ ] **Quest.1904 Helium is Not Just for Balloons**
  > It's probably better to get it from end stone dust or monazite from the Moon.

  https://github.com/GTNewHorizons/GT5-Unofficial/pull/1387 improved the helium output from cracked refinery gas, so refinery gas is also a good source of helium now.

- [ ] **Quest.3001 Using All the Fractions**

  Description about refinery gas needs updating.

- [ ] **Quest.3014 Raw Gasoline**
  > An important detail here is that Raw Gasoline is 80% Naphtha, and none of the oil types found in reservoirs produces that much of it.

  Now raw oil can.

- [ ] **Quest.3020 Largest Oil Drain**
  > until now. With a few stacks of Tungstensteel, you can put together the tier 3 of the Oil Rigs, and suck up all the fluid from a reservoir at once, covering the full 8x8 chunk size from a single spot.

  Tier 4. :(

- [ ] **Quest.3028 Hyperheated Steam**
  > You will need four turbine items for each multi, and you best bring the best ones you can make!

  Not four, it's 12.

- [ ] **Quest.3133 Nitrobenzene**
  > As a side note, Nitrobenzene shares an upgrade with Cetane-Boosted Diesel. They can both be used to make Super Fuels, which require more processing but are even more powerful.

  Why nitrobenzene can make super fuel?

- [ ] **Quest.3165 UV Power Per Turbine**
  > Large Ichorium 170% 342,720 EU/t (very durable)

  Ichorium turbine has been buffed. So this data is outdated.

- [ ] **Quest.3166 Powering-up Fluid Nukes**
  > Oriharukon and MAR-Ce-M200 are your best choices.

  MAR-Ce-M200 is LuV (need ZPM tier EBF) now. See https://github.com/GTNewHorizons/GoodGenerator/blob/33681ff5f240800c70b70c1e314d73ae262caf7c/src/main/java/goodgenerator/loader/RecipeLoader_02.java#L1145

- [ ] **Quest.2996 Oil Reservoirs**
  description of raw oil needs update.

- [ ] **Quest.2568 Infinity Helmet** and **Quest.2569 Infinity Breastplate**
   Infinity Helmet can't remove all negative debuffs, it's the ability of Infinity Breastplate.
 

### New Quests/Full Overhauls

- [ ] Add quests for AE2FC fluid cells in AE tab. They are good alternatives to EC2 ones.

- [ ] Add a quest for quad core and 16 core co-processing unit in AE tab.

- [ ] Add a quest for Quadruple Input Hatch, or mention it in some multiblock quests (for example, EBF).

- [ ] Add a quest in Multblock Goals tab listing what GT tools can do with multiblock controllers. (Or add them to each multi's tooltip or quest) Examples are as follows:
  - Screwdriver: (Right Click) Toggle mode for some multis, lock recipe for LCR, set prioritise circuit for MEBF, toggle input bus seperation for PA, EBF, Industrial Wiremill etc. (Shift Right Click) Lock recipe for PA
  - Soldering Iron: (Right Click) Toggle void excess for GT++ multis
  - Wire Cutter: (Right Click) Toggle UEV+ treated as UHV for PA, toggle input bus seperation for AdvEBF, MEBF, ABS, etc.
  - Plunger: (Right Click) Clear output hatch for GT++ multis

- [ ] Add a quest for Integrated Ore Factory in Multiblock Goals tab (maybe add a link in UHV tab as well). It is the ultimate solution for ore processing in late game.

- [ ] Add a quest for Tesla Tower in Multiblock Goals tab. It is a powerful power transmission option in HV~ZPM that should be mentioned in questbook.

- [ ] Add a quest/quests for YOTtank in Multiblock Goals tab. It is the ultimate fluid storage solution in middle & late game.

- [ ] Add a quest for Infinite Oil/Gas/Fluid Drilling Rig. There is already a quest for void miner, so add one for Infinite Rig is reasonable.

- [ ] Add a quest for GT++ Solar Tower in How to Generate Power tab, it is now a power generation option in IV, since https://github.com/GTNewHorizons/GTplusplus/pull/290 fixed and reworked it.

- [ ] Add XL Gas Turbine and XL Plasma Turbine quests in How to Generate Power tab, they are good upgrade for the large ones. XL Steam/HP Steam Turbine have a quest in Working with Oil tab already, might need a link in How to Generate Power tab too?

- [ ] Add a quest for Turbine Housing in How to Generate Power tab, it makes automating large turbine possible.

- [x] Add a quest for Industrial Forgehammer in GT++ tab.

- [ ] Add a quest for Elemental Duplicator in GT++ tab.

- [x] Add a quest for Boldarnator (Industrial Rock Breaker) in GT++ tab.

- [ ] Add a quest for Algae Farm in GT++ tab (I'm not sure whether this multi actually needs a quest).

- [x] Add a quest for Industrial 3D Copying Machine in ... maybe Building Better Bases tab? I don't know if anyone need this.

- [ ] Add a link of Steam Grinder quest (GT++ tab) in Tier 0.5 - Steam Age tab.

- [ ] Quest.1510 Biomes Everywhere, But Not the One You Want? Overhaul based on https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11385#issuecomment-1257110174

### Final Checklist

- [x] All of the quests in this ticket are fixed, and/or it is a new month, in which the unfinished quests will move to the next ticket.

**Comment by McFrugal** [comment]
- [ ] Quest 1335 (Infused Solars)

The jar reward is a bunch of empty Essentia Jars which don't stack and must be placed down then broken in order to be used.  They should be Warded Jars instead.

**Comment by wlhlm** [comment]
- [ ] Quest 482 (Animal farms)

Since the fix for https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7240 has been merged, I think we can remove the note about low mutton/calamari droprates and increase mutton amount to 100.

**Comment by SleepyMorfi** [comment]
Small error to fix, quest book says that to get vis bees you need eldritch and ethereal while in reality its ethereal and infernal

**Comment by chochem** [comment]
- [ ] Lutetium quests need an overhaul. Specifically, 'Faster Lutetium Excitement', 'High Temperature Super Breeder'.

**Comment by SPMoo66** [comment]
- [ ] Quest 1718 (Yttrium-Barium-Cuprate)
Ratio should be changed to 5 Yttrium, 10 Barium, 15 Copper. This produces 65 Yttrium Barium Cuprate Dust.

**Comment by Gofer2x** [comment]
- [ ] Quest 2359 (Visit the Infested Islands) and Quest 2361 (Ghost Amulet)
The Infested Islands quest requires Ectoplasm, but that is only obtainable after getting the Ghost Amulet, and the Ghost Amulet quest is locked behind the Infested Islands one. Probably move the Ectoplasm item requirement to the Ghost Amulet quest.

- [ ] Quest 2361 (Ghost Amulet)
The quest mentions needing to do a TC Infusion to purify the Amulet, but that is gated behind Draconium Ingots and the actual intended way of activating it is through a HEE Dragon Essence Altar infusion. Don't have to spell it out, maybe just add a hint about checking your HEE guide for alternative options.

**Comment by combusterf** [comment]
- [ ] Quest 2397 (Playing with the big boys/GT++ chemical plant) Instead of suggesting that UHV is the maximum tier, update the section on casings that the casing tier determines the hatch maximum tier, except for UHV casings which unlock all hatches including higher tiers and above.

**Comment by Glease** [comment]
- [ ] Quest 1227 HCl
This quest should add a OR dependency on sodium hydroxide, where you'd get plenty of hydrogen and chlorine to make lots of HCl en masse.

**Comment by Gofer2x** [comment]
- [ ] Quest 2293 (Nitrogen Tetroxide)
This quest in the Rocket Fuel quest chain requires 2310 (Palladium) to be completed, but it's the wrong Palladium quest. Quest 2310 is for processing Palladium Ammonia and Powder Dust into Salt and Reprecipitated Dusts, while it's 2878 that's the proper Palladium Dust quest and also the one that's obtained from doing the Palladium Skip. Change 2293's requirement from 2310 to 2878 and probably also change 2310's name to avoid confusion like this in the future.

**Comment by chochem** [comment]
- [ ] wireless booster
![image](https://user-images.githubusercontent.com/40274384/203987171-69c7f68c-00a7-4780-82f4-f5223cfc4aaf.png)

**Comment by AsGeNoCiide** [comment]
![image](https://user-images.githubusercontent.com/105320040/204063874-1369171e-8bd9-4a85-987d-93d54a97fd79.png)
quest 3103
change 35 blocks needed to 34 blocks needed ( like quest 83 high-speed charcoal)

**Comment by Skid-Inc** [comment]
Suggestions for changing required quests in the Blood Magic Tab.
- [ ] Quest 425 (Elemental Chalk) Chalk does not require an orb to craft, and the Ritual Diviner is needed for Ritual Dismantler. Suggestion, move Quests 425 (Elemental Chalk) and 428 (Rituals Made Easy) between Quests 433 (Rituals) and 2462 (Ritual Dismantler).
- [ ] Quest 927 (Blood Altar Tier 4) Since Large Bloodstones need the tier 3 orb, Quest 424 (Magican's Orb) should really be between it and Quest 421 (Tier 3 Slates).
These changes would probably require the Blood Magic tab to be reorganised slightly though.

In addition.
- [ ] Quest 411 (Potion Catalysts) Should have the requirement of Quest 860 (Titanium, Finally) as both catalysts need Titanium Dust.

Adept Thaumaturgy:
- [ ] Quest 1102 (Beacon) The beacon is a fusion crafting recipe, and can be crafted as soon as you have access to fusion crafting and have killed the wither, it does not need a Silverwood Wand. Suggest moving it left of Quest 265 (Creating a Better Wand).
- [ ] Quest 2268 (Who Needs Friends?) Luggage only needs 75 vis to craft so can be crafted with any wand that requires Energetic Screws, suggest moving the requirement of 2268 to be quest 266.
- [ ] Quest 2068 (Disenchanted) Same as above.
- [ ] Quests 303 (Pushing the Limits) and 304 (Enchanting Like a Pro) Are fusing crafting recipes and don't require a wand, but to keep things together should probably be moved with the above quest.

How to Generate Power:
- [ ] Quest 2819 (Toss Your Magic Junk in Here LV) Incorrect requirements, needs aluminium not stainless steel.
- [ ] Quest 2820 (Toss Your Magic Junk in Here MV) Incorrect requirements, needs stainless steel and HV circuits, not titanium and EV circuits.
- [ ] Quest 2821 (Toss Your Magic Junk in Here HV) Incorrect requirements, needs EV circuits, not IV circuits.
- [ ] Quest 2822 (Absorbing Magic Energy to Produce EU HV) Incorrect requirements, needs EV circuits, not IV circuits.

**Comment by Alrightsc** [comment]
The quest "Tungstate Processing - Step 1" states that you need 6 Sodium Hydroxide to make Sodium Tungstate, but you actually need just basic Sodium to make it.
![image](https://user-images.githubusercontent.com/38641296/207700104-c3e2762a-3038-4faf-a87f-5dd8bb59d817.png)

**Comment by Dream-Master** [comment]
Is Sodium or Sodium Hydroxide more realistic. I vote for SodiumHydroxide guess it is more reactive but sure i am not a chemist.

**Comment by Pxx500** [comment]
Change this (Tungstate into sodium tungstate)
![image](https://user-images.githubusercontent.com/81298696/207727721-37dcbcf0-f421-4976-ac96-ee032177f036.png)
Into this (Tungstate into scheelite)
![image](https://user-images.githubusercontent.com/81298696/207727765-4bb68f20-e065-4825-b3e4-804f4ed6ac44.png)
Sodium tungstate stays in game since those 2 exist:
(ferberite -> sodium tungstate)
![image](https://user-images.githubusercontent.com/81298696/207728191-37304b53-5a78-4dad-a1f9-88bad466a105.png)
(huebnerite -> sodium tungstate)
![image](https://user-images.githubusercontent.com/81298696/207728225-ee525030-81fa-4d80-98d2-20f22bb59a0a.png)

**Comment by Skid-Inc** [comment]
Sorry I should of double checked someone had reported this one rather then assuming it must of been caught. The issue in is both 2.2.3 and 2.2.7.
In the Flower Power tab, all quests involving flowers are can be completed by holding any botania functional or generating flower as they all have the same ID. I think ignoreNBT and partalMatch needs to be false for all these quests, quick test in creative seems to fix the problem.

**Comment by Gofer2x** [comment]
- [ ] Quest 1693 (2-Nitrochlorobenzene)
The Optional Task calls for 18 Nitration Mixture and 18 Chlorobenzene Cells, but the recipe using those is a 2:1 ratio. Up the amount of former to 36.

**Comment by Steelux8** [comment]
> Add a quest for Algae Farm in GT++ tab (I'm not sure whether this multi actually needs a quest).

Regarding this point, the Algae Farm doesn't just need a quest, it needs an entire questline where it's properly balanced. It can replace several early automations for specific chemicals if used, so it is my plan to make that questline when I finish the remaining adjustments.
