### ISSUE TITLE
Change cleanroom door requirement

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#11762]
### Your GTNH Discord Username

hallucinogender#1408

### Your Pack Version

2.2.3

### Your Proposal

I suggest changing the door required by the cleanroom from an IC2 reinforced door to one of the customizable doors from the Malisis door factory. The door factory itself probably doesn't need a recipe change for this, given that the reinforced door is not gating the cleanroom as strongly as any other cleanroom block _anyway_.

### Your Goal

Allowing players to use doors from the door factory would enable much better customization of cleanroom appearances.

### Your Vision

For anyone who wants to make their base look good, a requirement of an IC2 reinforced door counteracts that vision. This change would allow far more versatility with cleanroom appearances, and wouldn't meaningfully change the cost of a cleanroom.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I am not like against this, but you should know that the door is no longer required at all.

**Comment by hallucinogender** [comment]
> I am not like against this, but you should know that the door is no longer required at all.

That seems like a strange behaviour. If it's not intended, then the cleanroom will still need a door once the requirement is fixed. If it _is_ intended, then I still think it's worthwhile to have the cleanroom _allow_ a door from the door factory.

**Comment by chochem** [comment]
pretty sure thats intended
