### ISSUE TITLE
PSS power loss is twice as it should be

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11764]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Power loss should be the same as tooltip says ( 5% )
![tooltip](https://user-images.githubusercontent.com/85604068/198839595-cc11aa48-0c5d-425f-afef-c146472d767a.png)

### The Reality

When installing 1 HV energy hatch, it costs 51 EU/t, which is 10% of 512 EU/t.
![costs when installing 1 HV energy hatch](https://user-images.githubusercontent.com/85604068/198839584-083edbeb-c563-4ed5-acd1-2cfb62222acf.png)

When installing 1 EV energy hatch, it costs 205 EU/t, which is 10% of 2048 EU/t.
![EV Energy hatch](https://user-images.githubusercontent.com/85604068/198839588-1edb095e-4fd7-42f4-b42e-9d4fbb4f881b.png)

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
is it fully repaired and says efficiency 100%?

**Comment by ChromicRedBrick** [comment]
> is it fully repaired and says efficiency 100%?

Well I found that its efficiency is always at 0% even if I install an auto-taping maintenance hatch, and that might be the cause.
![efficiency](https://user-images.githubusercontent.com/85604068/198845552-505e058c-d665-4f16-ba24-85b27cc24838.png)

But literally PSS shouldn't need any maintenance. It doesn't need a maintenance hatch by default and never run into any maintenance issues. So I have no idea why in the code it consumes twice the energy when not in full efficiency.

**Comment by joshaup1999** [comment]
Think it might have been changed to 10% when it got nerfed and the LSC was buffed. Either way, i'd recommend the LSC, holds way more power

**Comment by Ethryan** [comment]
This sounds more like the tooltip needs to change instead of the percentage in the machine.

**Comment by chochem** [comment]
the nerf was to 5%. I don't know where the two of you heard otherwise. Efficiency just seems to be broken and probably should be ignored for this.
