### ISSUE TITLE
Add crafting recipes to different kinds of P2Ps

### ISSUE THREAD

**Issue by Alrightsc** [GTNewHorizons/GT-New-Horizons-Modpack#11767]
### Your GTNH Discord Username

Alright#2304

### Your Pack Version

2.2.0.0

### Your Proposal

Add a way to craft AE2 P2Ps into different types, such as slot 1 for item, slot 2 for fluid, etc.

Alternatively, those could be added via assembler recipe using circuits as the same above, though I think doing it in personal crafting 2x2 is a lot easier (although this only limits to four P2P types - maybe could have those be item, fluid, EU, and interface?). Would obviously have to add crafting recipes for all the other types to convert back to ME P2P.

### Your Goal

This is mostly for QoL.

### Your Vision

It would make our lives easier when we rename and prepare multiple p2ps to only realize they all aren't actually set on fluid, and so that you don't need to carry specific items to change modes on the fly when you can just place them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TheEpicGamer274** [comment]
Might work on this soon, likely tomorrow if anything, going to probably add recipes using lapis plates and chest, for fluid/item, etc, and these items will be non consumable as they normally are.

**Comment by EnderProyects** [comment]
Use a circuit instead, or make a loop recipe, like one convert to another and the second to the third and so on, until it completes the loop, so you can convert any p2p to any other p2p
