### ISSUE TITLE
Different circuit tier for PR's Chip in handcraft and assembler

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#11769]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.2.0.0

### Your Server

private server

### Type of Server

Crucible

### Your Expectation

Circuit tiers used in each chip are the same for handcraft and assembler

### The Reality

Different circuit tier for PR's Chip in handcraft and assembler

| Item | handcraft | assembler |
| --- | --- |  --- |
| Item Responder chip | LV circuit |  MV circuit |
| Dynamic Item Responder chip | LV circuit |  MV circuit |
| Item Overflow chip | LV circuit |  MV circuit |
| Item Extractor chip | LV circuit |  MV circuit |
| Item Broadcaster chip | MV circuit |  LV circuit |
| Item Stockkeeper chip | MV circuit |  LV circuit |
| Item Crafting chip | MV circuit |  LV circuit |

### Your Proposal

Circuit tier used in handcraft and assembler should be unified

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by benjamin-kirkbride** [comment]
I was coming here to report the same bug (?), didn't realize it was this bad
