### ISSUE TITLE
Nether star doesn't seem to effect alveary mutation chances

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#11774]
### Your GTNH Discord Username

Tommeh#9804

### Your Pack Version

2.2.0.0

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

From what i hear everywhere nether stars should guarantee a mutation when they're present in an alveary mutator when the mutation chance starts at 2% or more.

### The Reality

Instead of improving the chances they either don't effect it at all, or perhaps even plummet the chances, either way, it's very far from a guaranteed mutation, even when using 5 at once.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Runakai1** [comment]
Information about this was updated on the wiki.
