### ISSUE TITLE
Dislocation focus and mana pool

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#11779]
### Your GTNH Discord Username

ImpossibleVT#3997

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Tried to pick up a botania mana pool with dislocation focus. Crashed.

### Crash Report

https://paste.ubuntu.com/p/zqR99MkQxY/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by combusterf** [comment]
I can't open that log without giving someone else my information.

**Comment by Impos913** [comment]
BetterCrashes uploads it there 🤷

**Comment by Impos913** [comment]
[crash.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10019464/crash.txt)
here

**Comment by Impos913** [comment]
Tried in 2.4.0 private server MP. Server is java 8 and client is java 17. Disconnected from server without a crash log and the mana pool is gone.
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12578945/fml-client-latest.log)
