### ISSUE TITLE
Invisible Items in Player's Crafting Grid after opening NEI

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/GT-New-Horizons-Modpack#11784]
### Your GTNH Discord Username

ALongStringOfNumbers#9024

### Your Pack Version

2.2.0.0

### Your Server

Personal Server

### Type of Server

Vanilla Forge

### Your Expectation

When an item is placed in the player's 2x2 inventory crafting grid and then NEI is opened by using the R/U keybinds, after exiting NEI using `e`, `esc`, or `backspace` the item will be invisible in the player's 2x2 crafting grid. The item can still be retrieved from the crafting grid by clicking on the slot that holds the invisible item, but I would expect the item not to turn invisible in the first place.

### The Reality

Items turn invisible in the 2x2 crafting grid after exiting NEI.

### Your Proposal

Fix items turning invisible in the 2x2 crafting grid after exiting NEI. Thy should still render as they always would.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
similar (and very ancient) bug happens when you click on the arrow for recipes while holding an item. when you go back in the machine's gui, the item hold is invisible, and you have to click on an empty slot twice to make it reappear.
