### ISSUE TITLE
Botania Petal Apothecary whiteFlower Recipe Issues

### ISSUE THREAD

**Issue by MeGaGiGaGon** [GTNewHorizons/GT-New-Horizons-Modpack#11781]
### Your GTNH Discord Username

GiGaGon#1754

### Your Pack Version

2.2.3

### Your Server

private server

### Your Expectation

Not broken recipes.

### The Reality

All recipes in the petal apothecary that use an item with the ore id whiteFlower will have a three items indicator. Effects the recipes for the Pure Daisy, Kekimurus, Fallen Kanade, Daffomill, and Spectranthemum. This has no effect on the actual recipe used to craft the flower.

### Your Proposal

I checked the [new apothecary recipes file](https://github.com/GTNewHorizons/Botanic-horizons/blob/744aedff40740b534aaa007861979741cb1ddac8/src/main/java/net/fuzzycraft/botanichorizons/patches/ApothecaryPatches.java) and everything there looks good, so this is most likely a NEI issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by combusterf** [comment]
There have not been any changes to Botania's own NEI plugin code since this was working on stable, so this is most likely an external cause.
