### ISSUE TITLE
AR Glasses in wrong slot makes the server crash

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#11786]
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

delta

### Your Server

delta

### Your Actions

Linked AR Glasses to Glasses Terminal (not sure if it's a necessary step)
Opened inventory, then equipment and moved AR Glasses to this slot
![Fa6AwPbxIf](https://user-images.githubusercontent.com/17811922/199706997-2b0108f3-f77a-4fe2-84e7-6418f2901819.png)

### Crash Report

[crash-2022-11-03_12.06.25-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9927772/crash-2022-11-03_12.06.25-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Leanna147** [comment]
I've also had this crash on 2.2.8, running a local server. I had the same reproduction steps.

I tested the other slots, and have also had the crashed on the second row of the right most column of the left page (the one that looks like a boxing glove?). I have not tested the 3 below that in that column, but have tested the other non armor slots on that page.

It would be nice if the fix meant we could put it in that glasses slot, as it would free up the bauble slot and makes more conceptual sense than the bauble slot with an amulet symbol.

**Comment by repo-alt** [comment]
Interesting that it does not happen in single player. From the crash log it looks like the method `tconstruct.library.accessory.IAccessory.canEquipAccessory` is stripped from the OpenGlassesItem, but the interface itself is not.
