### ISSUE TITLE
ME OOTPUT HATCH

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#11783]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

last version

### Your Server

SP, MP

### Your Expectation

ME Output Hatch does not instantly teleport liquids to the ME system. 
Why would he then? or am I doing something wrong? i installed the latest version of gregtech and testing

### The Reality

null

### Your Proposal

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
looks like it's syncing with your AE2 once per second. This is done to avoid generating too much lag. Nothing to do about it, unless you want to end up with an unplayable map.
