### ISSUE TITLE
Air Intake hatches work in dimensions with no atmosphere

### ISSUE THREAD

**Issue by MixedTrails** [GTNewHorizons/GT-New-Horizons-Modpack#11798]
### Your Pack Version

2.2.3

### Your Server

SP

### Your Expectation

Air intake hatches should not work on dimensions such as space stations or the moon.

### The Reality

These hatches can generate air in these dimensions.

### Your Proposal

Blacklist these hatches in certain dimensions. The behavior doesn't make sense.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11778
