### ISSUE TITLE
Make AE2 Energy Acceptor actually use GT Enet instead of IC2

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#11795]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.2.0.0

### Your Proposal

move away from IC² enet when using EU P2P in favor of GT enet. The conversion from IC² to GT EUs is making the server lag
![image](https://user-images.githubusercontent.com/12850933/200088656-be4b9360-6eab-4b25-ac2a-6aceedbb84c4.png)

This is like 26 P2P EU on the server. 

### Your Goal

remove ic² laggy code usages from the pack 

### Your Vision

less lag the better

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
It is not p2p though, it is energy acceptor.
This needs  fixing anyway

**Comment by repo-alt** [comment]
Ok, I'm not sure how to "fix" that issue because ic2 discovers tileentities implementing IEnergySink by itself. But it is rather easy to work around by just disabling ic2 integration in config (in that case IEnergySink would be stripped from AE2 powered tiles at startup)
Config value is at 
modintegration {
...
    S:IndustrialCraft2=OFF
...
}
