### ISSUE TITLE
Railcraft Liquid Fueled Boiler Firebox Voiding Excess Liquid From GregTech Large Steel Fluid Cell

### ISSUE THREAD

**Issue by zombiethoughts** [GTNewHorizons/GT-New-Horizons-Modpack#11804]
### Your GTNH Discord Username

VelcroMittens#1180

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I inserted a GregTech Large Steel Cell filled to the 8L capacity with creosote into the top slot of the Railcraft Liquid Fueled Boiler Firebox. I expected the Boiler to empty the 8L capacity of the Large Steel Cell once there was available capacity for the 8L of creosote, and put the now emptied Large Steel Cell into the bottom slot.

### The Reality

When the Liquid Fueled Boiler Firebox reaches a state of 1L of available volume for liquid, it takes 1L of creosote from the Large Steel Cell's available 8L of creosote, voids the rest of the liquid, and deposits the empty Large Steel Cell into the bottom slot.

### Your Proposal

Not sure how long it would take for a proper fix, but disallowing containers larger than 1L into the Railcraft boiler might save some people a little fuel.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cleptomania** [comment]
My understanding of the large cells is they're really supposed to be a storage mechanism that needs fluid canning to be extracted out. Perhaps disallowing these to be used would be the best path forward(and that fix could look like explicitly disallowing the cells or maybe the proposed "larger than 1L" approach would make more sense).

I would think allowing the to fill directly off the large cells is a bit overpowered though
