### ISSUE TITLE
Recipes of fluid cells from AE2FC are not Greggified

### ISSUE THREAD

**Issue by OneEyeMaker** [GTNewHorizons/GT-New-Horizons-Modpack#11819]
### Your GTNH Discord Username

OneEyeMaker#4423

### Your Pack Version

2.2.3

### Your Proposal

Fluid cells from AE2FC should have the same recipe as regular AE2 cells. Right now ones have non-Greggified recipe (using **iron ingots** instead of stainless steel plates).

Source:
https://github.com/GTNewHorizons/AE2FluidCraft-Rework/blob/master/src/main/java/com/glodblock/github/loader/RecipeLoader.java#L73

### Your Goal

Recipes of all AE2 fluid cells should look like this:

![2022-11-12_11 21 46](https://user-images.githubusercontent.com/14104815/201465443-b0306cf9-2796-4219-acbc-6332d0e1d6b8.png)

not like that:

![2022-11-12_11 21 27](https://user-images.githubusercontent.com/14104815/201465460-6ba65372-96a0-4e1d-9478-33d638d6e1c3.png)

### Your Vision

I just want consistent and unified recipes for components with similar functionality. That's all.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [x] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
@OneEyeMaker yea indeed a few recipes need to be cheked. Nice to have you back play GTNH again :)
