### ISSUE TITLE
Extreme Extermination Chamber won't spawn Wisp and Hellfire Wisp 

### ISSUE THREAD

**Issue by fluffle** [GTNewHorizons/GT-New-Horizons-Modpack#11814]
### Your Pack Version

2.2.3

### Your Server

Local MP

### Type of Server

Vanilla Forge

### Your Expectation

I wanted to have a renewable source of Thaumcraft Essentia, so I created an EIO powered spawner and combined it with a Hellfire Wisp spawner I liberated from the nether. I expected this to produce wisp drops when placed in the Extreme Extermination Chamber (EEC) slot.

### The Reality

Placing this spawner in the EEC's slot does nothing. The only thing that drops essence from the EEC is the Eldritch Guardian, according to NEI.

### Your Proposal

Add Wisp and Hellfire Wisp to the list of mobs that work with the EEC.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
Intentional, they have some issues that prevent this, closing

**Comment by kuba6000** [comment]
> Intentional, they have some issues that prevent this, closing

It's not.

**Comment by Alastors** [comment]
> > Intentional, they have some issues that prevent this, closing
> 
> 
> 
> It's not.

What do you mean it's not, we've been over this before and last time you said it was too much overhead for the wisps because of their unique generation mechanics that cause the incompatibility with the EEC since they have to generate->generate aspects->die to drop their actual ethereal essence, which doesn't work in the EEC
