### ISSUE TITLE
Can't change the controls with AZERTY layout keyboard

### ISSUE THREAD

**Issue by Pip0une** [GTNewHorizons/GT-New-Horizons-Modpack#11810]
### Your GTNH Discord Username

Pipoune#0145

### Your Pack Version

2.1.1.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Change the controls for the hotbar with AZERTY controls as "&" = slot 1, "é" = slot 2, ...
press "&" = 1 = slot 1

### The Reality

Instead of accepting the control, the shortcut is put to "Fix!" and can crash the session if in SP (not tested in MP), I need to press SHIFT + & = 1 = slot 1

Tested with QWERTY layout, same result

### Your Proposal

accepting any controls from any layout.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
This is a limitation in LWJGL 2.x that MC 1.7.10 uses.  Can't easily be fixed.
