### ISSUE TITLE
pneumaticraft

### ISSUE THREAD

**Issue by aldro01** [GTNewHorizons/GT-New-Horizons-Modpack#11828]
### Your Pack Version

2.2.3

### Your Proposal

i think it would be nice to have pneumaticcrat in the pack

### Your Goal

because it will add a new crafting system of things through pressurized chamber ecc

### Your Vision

by adding the mod 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by mitchej123** [comment]
Open license but unlikely given the number of large more already

**Comment by aldro01** [comment]
ok but it is only one mod and it can be very useful, just think about. I asked because i try to add it but the pack crash with this
java.lang.IllegalArgumentException: mLPerBucket can't be < 0
    at pneumaticCraft.common.PneumaticCraftAPIHandler.registerFuel(PneumaticCraftAPIHandler.java:188)
    at pneumaticCraft.common.fluid.FluidFuelManager.registerFuels(FluidFuelManager.java:11)
    at pneumaticCraft.PneumaticCraft.postInit(PneumaticCraft.java:160)

**Comment by joshaup1999** [comment]
Dont see what benifits it would provide to the pack...

**Comment by aldro01** [comment]
by introducing the pressure in crafting and do some particular recipe in the pressurized chamber. i only asked it okay

**Comment by mecejide** [comment]
I like this mod, please reconsider adding it

**Comment by Nockyx** [comment]
> I like this mod, please reconsider adding it

@mecejide https://github.com/GTNewHorizons/GT5-Unofficial/pull/4299 this is an addition coming to the future that is similar to pneumatic craft in some manner
