### ISSUE TITLE
GT Tanks & Super Tanks showing their fill level & colour of the liquid in them

### ISSUE THREAD

**Issue by BeepBeep20** [GTNewHorizons/GT-New-Horizons-Modpack#11824]
### Your GTNH Discord Username

BeepBeep2020

### Your Pack Version

2.2.0.0

### Your Proposal

Tanks & Super tanks would show on the side of the block by a "thermometer" how full they are & what colour the liquid is that's inside them. My rough example below shows the tank is approx. 1/3 full & the fluid is clear/white.

![super tank suggest](https://user-images.githubusercontent.com/58308068/201509462-d8e99458-8265-44c1-994c-f52f74118e49.png)

### Your Goal

When I have lots of tanks I can't remember what liquid they have in them or how full they are from a distance
### Your Vision

It would look better, the tanks are very plain & more colour & information is a positive. I have no idea how easy or difficult this would be to add.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by greesyB** [comment]
There is already a "Fluid Storage Monitor Cover" that is sufficient for this imo
![image](https://user-images.githubusercontent.com/73182109/201509946-e04e60b9-7f1f-456d-a627-b45164add7e5.png)
