### ISSUE TITLE
Teleposer bug

### ISSUE THREAD

**Issue by ProfessorStain** [GTNewHorizons/GT-New-Horizons-Modpack#11825]
### Your GTNH Discord Username

ProfessorStain#1227

### Your Pack Version

2.2.3

### Your Server

Both SP and private server 

### Your Expectation

Я хотел настроить несколько точек телепортации в одном измерении.

### The Reality

После телепортации между измерениями с использованием Teleposer, возникает несколько неприятных багов. После каждой телепортации между измерениями они могут не произойти, могут пропасть, а могут и произойти в разных комбинациях.
1. Игрока телепортирует на расстояние в 2 раза дальше, чем находится teleposer. (8-16, 500-1000...).
2. Talisman of Nourishment перестаёт работать. (1:30 на видео)
3. Квесты не отмечаются и не выполняются.
4. Магниты не притягивают предметы.
Это только те ошибки, которые я заметил.
Выход и вход в мир или сервер решает проблему пока снова не используешь телепорт. 
Видео записанное в SP https://youtu.be/Hd-LDX8NAD8

Translation using Google

After teleporting between dimensions using the Teleposer, there are a few annoying bugs. After each teleportation between dimensions, they may not occur, they may disappear, or they may occur in different combinations.
1. The player is teleported to a distance 2 times farther than the teleposer is. (8-16, 500-1000...).
2. Talisman of Nourishment stops working. (1:30 on video)
3. Quests are not marked and not completed.
4. Magnets do not attract objects.
These are just the errors I noticed.
Leaving and entering the world or server solves the problem until you use the teleporter again.
Video recorded in SP https://youtu.be/Hd-LDX8NAD8

### Your Proposal

Исправьте это. Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
Please use English when reporting things.

**Comment by ProfessorStain** [comment]
I can use a translator. But in one of the discussions, users were asked to write using their native language if they do not know English well.
