### ISSUE TITLE
Torchberry IC2 Seeds Cannot be Planted

### ISSUE THREAD

**Issue by benjamin-kirkbride** [GTNewHorizons/GT-New-Horizons-Modpack#11823]
### Your Pack Version

2.2.3

### Your Server

private

### Type of Server

Don't know

### Your Expectation

Right clicking on a crop (sticks) with the IC2 seedbag for Torchberries results in them being planted.

### The Reality

Right clicking on a crop (sticks) with the IC2 seedbag for Torchberries does not result in them being planted.

### Your Proposal

Make it so right clicking on a crop (sticks) with the IC2 seedbag for Torchberries results in them being planted.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by benjamin-kirkbride** [comment]
Rose seeds cannot be planted either.

**Comment by Cardinalstars** [comment]
This seems to be an issue that they cannot be planted unless the light level is very low. Similar to Oreberries, we should add a " 'Ctrl' for extra info" and add this information. Light level is the same as OreBerries, 10 and below.

**Comment by benjamin-kirkbride** [comment]
duh, I should have tried that :sweat_smile: awesome!

**Comment by benjamin-kirkbride** [comment]
@Ethryan Is the lack of the ctrl tooltip not a bug?

**Comment by Ethryan** [comment]
Ah, that should ofc be there
