### ISSUE TITLE
problem with recipe

### ISSUE THREAD

**Issue by aldro01** [GTNewHorizons/GT-New-Horizons-Modpack#11837]
### Your Pack Version

2.2.3

### Your Proposal

there is a bug with the recipe, to obtain gallium arsenide you have to combine gallium dust and arsenic dust in the ebf but the nei show that this recipe need 120 eu/tick but it doesn't it use also lv energy

i'am doing something wrong or there is a problem in crafting, and if it is so how can i obtain gallium arsenide.

### Your Goal

fix the recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by OneEyeMaker** [comment]
Energy hatch used in multiblocks can receive 2 amps. So with 2 LV Energy hatches EBF can receive up to 4 amps of LV (in total up to 128 EU/tick).

If this resolves your problem, please close this issue.

**Comment by OneEyeMaker** [comment]
@aldro01 
Join [GTNH Discord](https://discord.gg/gtnh). There are many people glad to halp. Me too!
