### ISSUE TITLE
remove tectech's parametrizer tedium

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#11835]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.2.0.0

### Your Proposal

remove the parametrizers except the last one from the game, as well as downtiering the recipe of the parametrizer tXt.

![image](https://user-images.githubusercontent.com/12850933/201989535-032c3ed8-0c86-4a35-a24c-7528c56184c4.png)
This gui isn't that user friendly in the sense that if you want to get a precise value, you need to click buttons until you are satisfied.
but that's becomes a true pain when you want to get a negative exponent: the only way to do that is to find a way to express your number like that: $$X = \frac{Y}{2^n}$$ where X is the number you want, Y an integer to find, and n the amount of time you divise by 2 with the gui.

![image](https://user-images.githubusercontent.com/12850933/201990596-18df70e8-ebe8-4650-b3ab-5c99676e6865.png)
This gui is even more obscure, you must know your conversion between binary and double, as the principle of it is to basically create the double value by bit manipulation.

![image](https://user-images.githubusercontent.com/12850933/201991036-d157ff68-4c0c-47e0-ab8f-1a7f60686f09.png)
This gui is straight forward, as you can pick up the index of the parameter pair, then simply write values in it. Obviously it's the most expansive one, because the game wants you to suffer a lot.

### Your Goal

We should stop wasting players' time on something so trivial.

Like i used the heat simulator from the wiki for the quantum computer, converted it in python to run hundreds of simulations to fine tune my overclocking value and my overvolting value, as well as to check if the heat was stable in time. And now, i must spend some time figuring out how to input my values? that's plain dumb. I ended up crafting the parametrizer tXt because it was faster for me than trying to find a good approx for my numbers.

Also, let's be honest, with Modular UI being close to be 100% functional, such painful GUIs should disappear anyways.

### Your Vision

Remove tedium from the game, trying to put a precise value shouldn't even take more than 10s

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
Honestly, i can wait for a total rework of tectech's GUIs with MUI, but if it takes long enough to not be shipped in the next version, we might as well ductape it in the mean time by downtiering the parametrizer tXt.

**Comment by chochem** [comment]
hey, looks like there are now 3 people that know how the parametrizer X works. :) I am not counting tec as he left it in a broken state lol. I think I might be the only one using it though, so removing/disabling doesnt do much.

I would be super happy though with parametrizer tXt and uncertainty resolver X (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10374) to be downtiered.

**Comment by minecraft7771** [comment]
Fixed by https://github.com/GTNewHorizons/TecTech/pull/125
