### ISSUE TITLE
Diluted Acetone not processed into Fluid Heater

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#11834]
### Your GTNH Discord Username

BangBang#8842

### Your Pack Version

2.2.3

### Your Server

private

### Type of Server

Ultramine

### Your Expectation

Diluted Acetone not processed into Fluid Heater

### The Reality

Repair

### Your Proposal

Repair

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SweptWasTaken** [comment]
Hey, i've reproduced this on 2.2.8.

**Comment by shadowpho** [comment]
Can repro on 2.2.3, EV and IV fluid heaters have power but do not make acetone :(
