### ISSUE TITLE
Sparge towers apparently generate EU?

### ISSUE THREAD

**Issue by fluffle** [GTNewHorizons/GT-New-Horizons-Modpack#11830]
### Your Pack Version

2.2.3

### Your Server

Local MP

### Type of Server

Vanilla Forge

### Your Expectation

I have just built my first two Sparge towers. Yay! One processes U Salt, one processes T Salt. Both have IV energy hatches.

I bonked them both with a soft mallet to enable them, forgetting to plug them into power first. I *expected* them to turn off immediately, once I realised what I'd done. 

### The Reality

Instead, they both ran for 25 seconds, completing their recipes and producing outputs. NEI says these recipes should take 250s at IV, so that's also rather confusing. When I check the tower controllers with a tricorder it says "Probably generates: 7680 EU/t" so I suspect the tile entity is incorrectly marked as a generator in the GT++ code :-)

I poked about a bit but it's not immediately obvious.

### Your Proposal

The tower should consume power, not generate it? And it seems like NEI needs to be updated to reflect the processing time. The recipes are apparently 300s at voltage tier 3:

https://github.com/GTNewHorizons/GTplusplus/blob/80c790b8a7b2c61215d636b3ce14715580b2f5eb/src/main/java/gregtech/api/util/GasSpargingRecipe.java#L34

... but that's not IV, and so I guess there's some overclocking going on to give the 25s...

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by fluffle** [comment]
Ah. After some archaeology, I suspect it is because sparging originally happened in the LFTRs, and so the recipe was originally intended to generate power. The original version of checkRecipe for the sparge tower committed (in 0758af9) had a check to make sure mEUt was always negative:

https://github.com/GTNewHorizons/GTplusplus/commit/0758af954c7ef7892a723248a6aaa8018cb09c60#diff-42a9993691932a39029f0ae998765dc1fe8911714ffd40cf2d264c06b6886580R205

But when the code was heavily rewritten (in the next commit a1956ff) this check was removed. The recipes do appear to contain positive numbers, though that's no different to other recipes for different machines that consume energy. I 

@Steelux8 because they made the most recent changes in https://github.com/GTNewHorizons/GTplusplus/pull/345

You might like to know that the recipes are 25s rather than 250s because the sparge tower tile entity helpfully divides the duration by 10 for you, because "dev" :-)

https://github.com/GTNewHorizons/GTplusplus/blob/b5c2946f55ee5e44a341f545ce7565203803d74a/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_SpargeTower.java#L229

**Comment by Steelux8** [comment]
I'm not sure what the intended time for the sparging was, but having it be shorter at least doesn't hurt the setup.

Regarding what you said about the LFTR being the old sparger, that was true. It had 4 inputs and a ton of outputs until the process was moved to a different multi.

**Comment by fluffle** [comment]
Fixed by @Steelux8 in https://github.com/GTNewHorizons/GTplusplus/pull/716, thanks!
