### ISSUE TITLE
pneumaticraft

### ISSUE THREAD

**Issue by aldro01** [GTNewHorizons/GT-New-Horizons-Modpack#11831]
### Your Pack Version

2.2.3

### Your Server

private

### Your Actions

hi i add pneumaticraft version 152 and the pack crash this is due to version 5.09.41.74 because with 5.09.40.11 the pack did not crash. is there a way maybe in the config to fix this.

### Crash Report

https://pastebin.com/Uwi75WW2

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
this mod is not in the pack and not supported.
