### ISSUE TITLE
Germanium semiconductors

### ISSUE THREAD

**Issue by PowahGTNH** [GTNewHorizons/GT-New-Horizons-Modpack#11847]
### Your GTNH Discord Username

Powah#4273

### Your Pack Version

2.2.0.0

### Your Proposal

Add Germanium semiconductors to the game because germainium is actually better than silicon

### Your Goal

To create a new alternative to the average silicon line, and it would make alot of room for new machinery for advanced germanium semiconductors manufactoring, along with that, making germanium chips will be much more resource efficient(ie more chips) than silicon, this will make germanium a path of progression that is worth it

### Your Vision

It will add some more realism, because germanium is already being used a a material in high speed circuits in real life, and recently, Silcon-Germanium is recplacing Gallium Arsenide in wireless communication devices. It will also add new opportunities for the devs to make new multiblocks of advanced chip manufacturing, adding diversity to the multiblocks

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Elisis** [comment]
> germainium is actually better than silicon

Yeah in like two metrics. For the most part silicon is more feasible

>  Silcon-Germanium is recplacing Gallium Arsenide in wireless communication devices

Only in very specific applications, this is far from widespread


Either way we have no good source of germanium in this pack so it'd be hard enough to implement

**Comment by Dream-Master** [comment]
We can check how germanium will be processed. And we have a lot of useless ore mixes so we can exchange some stuff. I dont mean add germanium as material more like a material that have germanium.

**Comment by PowahGTNH** [comment]
GT++ already add Germanium in 2.2.0.0 but it is currently useless

**Comment by PowahGTNH** [comment]
Germanium can be obtained by processing sphalerite(zinc), and it is commercially produced in real life by recovering from silver, lead, and copper ores

**Comment by PowahGTNH** [comment]
i had a plan to add a new Germanium processing line (based on real life and Wikipedia research), and it might be coming soon, i just need some recorrrections

**Comment by Impos913** [comment]
Germanium processing is supposedly easier than silicon processing so idk what can you really make "germanium processing line"

**Comment by PowahGTNH** [comment]
make it IV, since its the time when you need alot more circuits
