### ISSUE TITLE
Visual Prospecting display incorrect information of Bartworks ore veins

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11849]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

VP provides correct information

### The Reality

It says there are chlorine, argon, calcium, scandium in ross128b forsterite ore vein which is not correct.
![ross128b](https://user-images.githubusercontent.com/85604068/202898386-d62e971f-0f40-40bd-9706-7171d6515e1b.png)
![ross128b-1](https://user-images.githubusercontent.com/85604068/202898387-ce39f99d-eb5f-41d9-a969-d22e7bcae27f.png)

Same in ross128ba.
![ross128ba](https://user-images.githubusercontent.com/85604068/202898389-5dd68ced-e82b-4a65-aced-c16a98c5bc5f.png)
![ross128ba-1](https://user-images.githubusercontent.com/85604068/202898415-4ba22fe2-adc4-4309-b342-a80029590ef2.png)

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by querns** [comment]
Related to this, could VP functionality also be added for the Toxic Everglades? Ore in this dimension spawns properly in veins.

Vein information is here: https://github.com/GTNewHorizons/GTplusplus/blob/master/src/main/java/gtPlusPlus/everglades/gen/gt/WorldGen_Ores.java

**Comment by chochem** [comment]
I think we fixed this by accident.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/VisualProspecting/pull/35 (fixed for new worlds post 2.3.5 only)
it looks like BW dims were always the only ones that use equispaced oregen while everything else use axisymmetrical.

**Comment by chochem** [comment]
should also fix nei ore overlay and IGI orevein info
