### ISSUE TITLE
Recipe conflit with Structural MK III (iron plate) in a MV assembler

### ISSUE THREAD

**Issue by THokert** [GTNewHorizons/GT-New-Horizons-Modpack#11841]
### Your GTNH Discord Username

Detective R34#9257

### Your Pack Version

2.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Trying to craft Structural MK III (Iron plate) upgrade from JABBA in a MV assembler
![craft](https://user-images.githubusercontent.com/45360601/202276371-386fbc13-1405-493e-bbb0-6b78306dd9ce.png)

### The Reality

 In a MV assembler this recipes give iron fence from IC2
![craft2](https://user-images.githubusercontent.com/45360601/202276896-e80778e0-06bd-4d3f-b888-0ffc5e5d4f23.png)

This craft in a LV assembler work fine, i can only test it in a MV assembler for now.

### Your Proposal

Craft change or recipe conflict solved

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BritishCynic** [comment]
Already reported here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11326

**Comment by miozune** [comment]
Closing as duplicate
