### ISSUE TITLE
LFTR: no fuel consumed for 100% power and byproducts

### ISSUE THREAD

**Issue by gberguy** [GTNewHorizons/GT-New-Horizons-Modpack#11856]
### Your GTNH Discord Username

gberguy

### Your Pack Version

2.2.3

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

Built LFTR and expected it to need fuel.

### The Reality

1: LFTR turns on without needing fuel, and 'powers up' from 0-100% efficiency.
While doing so it outputs between 1-4 amps (the higher the efficiency the more amps) of IV from the 4 buffered IV dynamos. I didn't test but I assume this would work with higher tier buffered dynamos as well.
When it hits 100% efficiency it waits for a moment, while checking for fuel, if there's no fuel it drops to 90% and climbs back to 100% generating EU all the while.

If the proper amounts of fuel are available upon hitting 100%, it consumes them and works as designed.

but;

2: IF there's fuel in the LFTR but at amounts lower than needed, yet greater than 0, the LFTR will consume zero fuel and generate full EU/byproducts exactly as though it consumed fuel.

### Your Proposal

fix it please.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChromicRedBrick** [comment]
Seems still not fixed in latest dev, I tested with GTplusplus 1.7.142-pre
@Steelux8

**Comment by DotJason** [comment]
Having the (probably) exact same issue on 2.3.4 (GT++ version [1.9.39](https://github.com/GTNewHorizons/GTplusplus/releases/tag/1.9.39))
The LFTR turns on by itself with empty input hatches, generates energy while its efficiency rises up to 100%, then turns off, and once its efficiency drops to 90% it turns on and does the whole loop again.
