### ISSUE TITLE
ThaumicTinkerer's equipments comsume memory abnormally

### ISSUE THREAD

**Issue by hoshinokiseki** [GTNewHorizons/GT-New-Horizons-Modpack#11859]
### Your GTNH Discord Username

KisekiUnofficial#2718

### Your Pack Version

2.2.0.0 & 2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Equipments from ThaumicTinkerer should not consume memory.

### The Reality

When someone wears an equipment from ThaumicTinkerer (e.g. Robes of the Stratosphere) even myself when i press F5 or E, gtnh begin to consume physical memory abnormally, ~30MB per second, and fps will reduce.

### Your Proposal

Equipments from ThaumicTinkerer should not consume memory.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
Can you provide some memory profiles from visualvm, or some other visual evidence to help track this down?

**Comment by hoshinokiseki** [comment]
i know nothing about what you said. would you like to give me a brief introduction about memory profiles from visualvm? i hava visualvm on my pc but i don't how to use it

**Comment by hoshinokiseki** [comment]
> Can you provide some memory profiles from visualvm, or some other visual evidence to help track this down?

[something.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10064897/something.zip)

I try to get something with visualvm.

**Comment by BritishCynic** [comment]
As this appears to be a driver issue, I am closing this issue. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
