### ISSUE TITLE
Using unintended feature to transmute(?) resources

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#11864]
### Your GTNH Discord Username

LazyFlesh#4533

### Your Pack Version

2.2.3.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I was upgrading Chests to Gold Chests to save some space, and was like, wait, can I disassemble these. I tried to do so, and succeeded. 

### The Reality

This however means that I used 2 double gold plates for iron to gold upgrade, and got back 3 double gold at the cost of 7 iron(6 for iron chest and 1 for iron to gold upgrade). This can also be used to double diamond plates, as the upgrade costs 2 while the chests costs 4.

### Your Proposal

I propose a small screening of the assembler recipes to weed out any which can be used to transmute(?) materials. The Iron Tank recipes can likely be used as well. Nvm, checked and they can't. But there are always others that can be done with in-world upgrades that can be dissed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
no longer relevant
