### ISSUE TITLE
Clicking the "NEI Sync" button on an EIO Inventory Panel crashes the game

### ISSUE THREAD

**Issue by TheBlizWiz** [GTNewHorizons/GT-New-Horizons-Modpack#11867]
### Your GTNH Discord Username

TheBlizWiz#6524

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

1. Make a proper Inventory Panel setup
2. Click the NEI sync button
3. ???
4. Game crashes
![image](https://user-images.githubusercontent.com/39657515/203405290-19e0cfab-225b-4ff2-918a-bef0475c81f9.png)

### Crash Report

[crash-2022-11-22_12.21.23-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10070455/crash-2022-11-22_12.21.23-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
Fixed by https://github.com/GTNewHorizons/EnderIO/pull/87 by accident.

To fix, upgrade ender io to https://github.com/GTNewHorizons/EnderIO/releases/tag/2.3.1.48

**Comment by TheBlizWiz** [comment]
Will this be merged into the next latest stable, or do I need to manually update this on my own?

**Comment by Glease** [comment]
Yes it will be in next stable. I mentioned the fix in case you want it now.
