### ISSUE TITLE
fluidblocksludge

### ISSUE THREAD

**Issue by aldro01** [GTNewHorizons/GT-New-Horizons-Modpack#11865]
### Your Pack Version

2.2.3

### Your Proposal

there is not a recipe for fluidblocksludge, so how i get it?

### Your Goal

add recipe 

### Your Vision

resolve problem

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
can you give some more details? what mod are we even talking about and what do you need fluidblocksludge for?

**Comment by aldro01** [comment]
gregtech and it is useful to produce with a programmed bio circuit in a dehydrator a small pile of material (in my case i will use it for iridium) and nitric acid

**Comment by chochem** [comment]
Sounds like gt++ not gregtech. And unfinished. 

If I had to guess its probably intended as a potential byproduct to add to future recipes but it was never used. Thats what the the name sounds like anyway. Don't think we want a direct recipe.

**Comment by aldro01** [comment]
ok so right now it is impossible to obtain
