### ISSUE TITLE
Bees are our friends 

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#11874]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Your Expectation

Trying to breed Chad bees

### The Reality

There is no my nickname _Rait_GamerGR_ here
![image](https://user-images.githubusercontent.com/70205464/203827473-0bbc1fd5-f910-4abf-8a3e-fcad3dbb31d8.png)

### Your Proposal

Add my nickname into list

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Runakai1** [comment]
Unfortunately, that's only for chads. Chads don't ask. Chads just exist 😎
