### ISSUE TITLE
Throttle Machine Controllers

### ISSUE THREAD

**Issue by AtomicGrog** [GTNewHorizons/GT-New-Horizons-Modpack#11872]
### Your GTNH Discord Username

AtomicGrog#7956

### Your Pack Version

2.2.3.0 (+ a few hot fixes)

### Your Proposal

When a gt machine operates without external intervention it appears to check for a recipe and run until materials deplete for the recipe and will then pause or a second waiting before attempting to run again.

When a gt is under the control of a machine controller cover there is no pause between attempts to run; the cover switches the machine from disabled to enabled in 1 tic intervals based on external control. When recipes approach 1 tic in length and with redstone control over stock (whether thats a output hatch/bus or externally managed) the switching speed appears to increase to the point of the machine scanning for recipe and running every tic. In some cases this can be seen as a race condition, with notable cpu increase.

Suggestion is for the machine controller (and maybe redstone receiver being used in similar manner) to only re-enable a machine once both when it's 'enable' condition is met and additionally a set period (suggesting a second) after to was last disabled has passed. This introduces hysteresis into the on/off cycle as well as reducing workload during the waiting state.

### Your Goal

Reduce workload, especially when recipe run periods start to and reach 1 tic periods and the machines switch state from disabled to scanning for recipe tic by tic.

### Your Vision

Reducing lag, delays, improve playability by reducing workload

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
On closer inspection, it appears machine controller will not actively wake up multi every game tick. I'm not sure since when this is the case but in dev I'm unable to have EBF checkRecipe to trigger every tick. Thus the whole suggestion become pointless since it's clear that it's suggesting to ducttap fix a bug that doesn't exist.
