### ISSUE TITLE
Pico Wafer requires Tiny Pile of Infinity Catalyst but doesn't get used up in the LCR

### ISSUE THREAD

**Issue by Dyonovan** [GTNewHorizons/GT-New-Horizons-Modpack#11870]
### Your GTNH Discord Username

Dyonovan#3279

### Your Pack Version

2.2.3

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

The tiny dust being used up when the recipe starts.

### The Reality

The tiny dust just sits in the input bus. It is required for the LCR to start working but doesn't get used

### Your Proposal

Either remove the tiny dust in the recipe or fix the recipe to actually use up the dust.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
what does NEI say? probably just meant to be a 'catalyst'

**Comment by Dyonovan** [comment]
Ahh my bad. Thanks for the catch.
