### ISSUE TITLE
Crash when press journey map buttons.

### ISSUE THREAD

**Issue by AderMeepo** [GTNewHorizons/GT-New-Horizons-Modpack#11876]
### Your GTNH Discord Username

Ader#8113

### Your Pack Version

2.1.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Actions

When I try to open a fullscreen map the game just crashes, same when trying to create a waypoint. The other buttons are the same.
Also no minimap.

### Crash Report

[crash-2022-11-25_06.16.28-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10088604/crash-2022-11-25_06.16.28-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
maybe try reinstalling journeymap and resetting the config?

**Comment by AderMeepo** [comment]
> maybe try reinstalling journeymap and resetting the config?

no, its not working :c

**Comment by Seba244c** [comment]
Can confirm, this also happend for me.

Worked fine in singleplayer, but after setting up my server this error happend.
My minimap has dissapeared and pressing j or b crashes the game.
Crash Report: https://hastebin.com/lezaqafufe.properties

**Comment by Seba244c** [comment]
Suddenly joining the server again, gave me this message.
Running latest forge version on both client and server. Also latest GT:NH version
![y1n7k82](https://user-images.githubusercontent.com/23051740/211211074-da258e41-1dac-480b-aba2-051135f4a108.png)

**Comment by mitchej123** [comment]
Could you paste the entire `fml-client-latest.log`?  There might be other clues in addition to the crash report.

**Comment by Seba244c** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10369363/fml-client-latest.log)
This is my log, the game has been running for quite a while, sry.

**Comment by Seba244c** [comment]
I restarted client, and repeated the issue again.
This time i recorded it, and made sure to post the logs immediately (So they aren't so big this time)

Crash Report: [https://pastebin.com/raw/TmnN9KCD](crash report)
FML-Log: [http://web-static.sebsa.dk/fml-client-latest.log](fml-client-latest.log)
Video: [web-static.sebsa.dk/recording.mkv](recording.mkv)

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/211217643-7cb78925-f291-40c4-9425-acc37bf0144d.png)
is that an actual path in your install?

**Comment by Seba244c** [comment]
Yes "D:\Games\Minecraft\Prism\instances\GT_New_Horizons_2.2.8_MMC\.minecraft" is the actual path of my install.

I think I found the issue. You can see in the log files that it's trying to create a folder with the servers ip. (149.102.150.160:27100)
The problem is that the port 25565 is already in use on the server, so the ip has a port number in it.
Therefore, it tries to create a folder with the ":" in it. Which is impossible.
So, there’s 2 ways of fixing this. Either I setup my dns so that the server doesn’t have a port specified in the ip. Or somebody goes in and patches the issue in JourneyMaps.

**Comment by boubou19** [comment]
looks like JourneyMaps dev is using a linux OS 😂.

**Comment by Seba244c** [comment]
Though a fix would be nice. Like in the JourneyMap code check if the name includes ":" and replace it with "_"
But since it's 1.17.10, I don't think that will happen.

**Comment by Alexdoru** [comment]
> But since it's 1.17.10, I don't think that will happen.

That's where mixins comes in :>
