### ISSUE TITLE
My game crashed when opening inventory, seems to be related to keybindings

### ISSUE THREAD

**Issue by PointedB** [GTNewHorizons/GT-New-Horizons-Modpack#11896]
### Your GTNH Discord Username

Pointed#6642

### Your Pack Version

2.2.3

### Your Server

SP

### Your Actions

i opened the inventory after loading a backup on a new instance, the game froze for a bit and then crashed.

### Crash Report

https://pastebin.com/0QNDgp4r thanks so much for the help. contact me on discord if you need anything love you bro

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
are you using some weird non-standard keys? Maybe reset your keybinds.

**Comment by PointedB** [comment]
?

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/NotEnoughItems/pull/358
