### ISSUE TITLE
Game crashes on startup of single player world with suspected cause being JABBA mod

### ISSUE THREAD

**Issue by king-gray** [GTNewHorizons/GT-New-Horizons-Modpack#11899]
### Your GTNH Discord Username

Vaughn#4093

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Actions

The game simply crashes whenever I try to load into my singleplayer world, and says the mod JABBA is the issue. Occasionally when I restart my pc and attempt to load into the world it will work, albeit with some buggy textures (in 6 resets it only worked twice), but after about 10 to 15 minutes of random actions in the world itll crash again.

### Crash Report

[crash-2022-11-30_15.30.37-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10127101/crash-2022-11-30_15.30.37-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
cleared up on discord. just in case anybody comes across searching: this is caused by microsoft saving some folders to cloud only by default without (some) users knowing. Obviously having your save folder on a cloud is not a good idea.
