### ISSUE TITLE
Glass using multiblocks don't accept any glass with tier.

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#11894]
### Your GTNH Discord Username

ImpossibleVT#3997

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Tried using Botania Alfglass for LSC, Bacterial Vat and MBF expected them to form because Alfglass is IV tier glass.

### The Reality

They did not form with Alfglass. They formed when I changed the glass to borosilicate glass so the glass was the reason of them not forming.
![2022-11-29_02 12 37](https://user-images.githubusercontent.com/36479271/204402794-6f700b51-d8dc-471c-bf4c-791bb5b92dcb.png)
![image](https://user-images.githubusercontent.com/36479271/204402805-2f6a1d76-b66c-4953-9a6c-047e97795489.png)
![2022-11-29_01 33 12](https://user-images.githubusercontent.com/36479271/204402818-786d97a6-95f2-49ec-8003-99a76571c573.png)
Later I tried to build LSC with IC2 Reinforced Glass, also did not work.

### Your Proposal

I was told this is a bug so here I am. Make the glasses work on multis.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
> It is not a bug. Only biovat accept non borosilicate glass and that is intentional.
> 
> Though it might be a good idea to change this. I like alfglass 😋

it doesnt work in the vat either: https://discord.com/channels/181078474394566657/224191655375273985/1046924201975611472

**Comment by Glease** [comment]
thorium-yttrium is also boroglass.

and biovat forms with alfglass.
![image](https://user-images.githubusercontent.com/4586901/204554009-47af7424-9b07-450b-a9c9-85ca2c14c178.png)
