### ISSUE TITLE
Certain recipes require uncraftable kind of honey

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#11893]
### Your GTNH Discord Username

Tommeh#9804

### Your Pack Version

2.2.3

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

For example, a recipe to craft biomass wants honey with ID 7197:58 and some plant like item to create biomass.

### The Reality

However, honey with ID 7197:58 cannot be crafted unlike its other also Gregtech counterpart with ID 7197:63.

### Your Proposal

Either Oredict both types of honey or change all recipes that require honey to use ID 7197:63

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
is that the honey from the nether? uncraftable does not mean unobtainable.

**Comment by chochem** [comment]
also, fluids cant be oredicted anyway

**Comment by Tommeh1** [comment]
> is that the honey from the nether? uncraftable does not mean unobtainable.

I'm pretty sure the honey from the nether has ID 1260

**Comment by chochem** [comment]
changing the recipes it is then. Is it only biomass brewing?

**Comment by Tommeh1** [comment]
It also has a recipe for the apiarist's pipe in the assembler and also a centrifuge recipe to convert it to the other kind of honey.

**Comment by chochem** [comment]
well those dont matter.

If I had to guess the cause is probably forge fluid registry picking an arbitrary one.
