### ISSUE TITLE
Volumetric Flask can no longer be set with ModularUI user interface

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#11898]
### Your GTNH Discord Username

querns#3785

### Your Pack Version

modularUI 1.0.23, gt5-unofficial 5.09.41.152-pre

### Your Server

SP

### Your Expectation

I expect to be able to resize a volumetric flask with its shift-right-click UI.

### The Reality

![image](https://user-images.githubusercontent.com/33518699/204875957-07e02e83-1d6c-445d-be48-2127a0cca646.png)

The new UI for flasks no longer accepts the Enter key for input. If a value is provided, either by typing it or with the +/- buttons, it is ignored and the flask remains the same size as before.

### Your Proposal

Revisit the flask UI to make sure it's compatible with the new modularUI framework.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@miozune
