### ISSUE TITLE
Auto oredict to Gregtech items doesn't work after some restarts

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#11892]
### Your GTNH Discord Username

Tommeh#9804

### Your Pack Version

2.2.3

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Normally, whenever for example the EnderIO pulsating iron or vibrant alloy are made they're instantly converted to their Gregtech counterpart.

### The Reality

However, sometimes, after a restart this is no longer the case until the server is restarted again, the same applies to anything else that is normally converted and even inserting them into for example a superchest with their Gregtech counterpart will not convert them.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Obviously one need something more concise than "it happens sometimes" to debug this.. especially when any given server instance take >5 min for a full restart.

Tagging this as can't reproduce for now, until someone else can confirm this.

**Comment by Tommeh1** [comment]
> Obviously one need something more concise than "it happens sometimes" to debug this.. especially when any given server instance take >5 min for a full restart.
> 
> Tagging this as can't reproduce for now, until someone else can confirm this.

I simply cannot give anything more concise, but lets say that at random, every 10 ish restarts it's broken.

**Comment by Glease** [comment]
Yeah I understand your confusion, but I'm just equally as confused 😌

Officials restarts daily, so we should see this at least once per month on zeta, except we haven't, so I doubt if this is something that is either extremely rare, or something that is specific to your setup, like additional mod, altered config, a wonky save, or even alignment of stars /s. If it's the former uh the cost doesn't justify reward, especially when a easy workaround i.e. restarting exist. If it's the latter we'd be powerless in this case..
