### ISSUE TITLE
Harvestor log spam

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#11904]
### Your GTNH Discord Username

Tommeh#9804

### Your Pack Version

2.2.3

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Whenever a harvestor runs the following error floods the log a few hundred thousand times a day:
https://gist.github.com/Tommeh1/3fac3b929f7844899b5d61773f96bd18

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
duplicate: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11613
