### ISSUE TITLE
TiC GregTech materials stats got shifted

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11903]
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.3 + dev update

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

GT materials' stats should be consistent between versions.

[My modlist after dev update](https://pastebin.ubuntu.com/p/G6mz6ckZRK/)

### The Reality

in 2.2.3:
![2 2 3](https://user-images.githubusercontent.com/85604068/205060280-7796a5de-7649-4b3e-99fa-488e69b2c4f7.png)

after dev update:
![dev](https://user-images.githubusercontent.com/85604068/205060318-ac1223a3-9eb5-41ad-bdb9-deb300348cb0.png)

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by querns** [comment]
I ran into this too after updating Bartworks to a version built by GHA yesterday. I believe it's due to TVP-alloy being added. To get the new version of bw to work, I had to delete my Tinkers Gregworks config file, and all of my tools that used GT (maybe just Werkstoff?) materials got shifted.

**Comment by iouter** [comment]
i can confirm this is not related to tpv or bartworks.

**Comment by iouter** [comment]
this bug is because gtnh has customized stat multipliers of materials in config. if you delete ths config, customized multipilers is be deleted.

**Comment by querns** [comment]
Yeah, I got one of those as well.

![image](https://user-images.githubusercontent.com/33518699/205082393-e4bb146e-6245-42fa-ba55-dd04b67ed3d7.png)

My oriharukon tools shifted to Black Plutonium and a shadow metal tool shifted to Rose Gold.

**Comment by Dream-Master** [comment]
i remeber there where some fix. Not sure if it was after 2.2.3

**Comment by iouter** [comment]
> new materials changing the tgregworks list is a pretty regular occurance and the reason one always needs to delete the config file when updating. It regenerates automatically. So no idea what iouter is trying to say. I also had to do this to update a few days ago. Otherwise you just crash with an id conflict as usual.
> 
> However, this seems to be the first time this id-shift is happening so might or might not be related.
> 
> I also get this: ![image](https://user-images.githubusercontent.com/40274384/205081731-6b5327b7-a9b1-42d0-a8bb-8031376a38ed.png) never had that before.

emm I explain the reason for the change of material stats.

here is code about id: https://github.com/GTNewHorizons/TinkersGregworks/blob/8ea605b426b77778b819323c0db9c3b5d01c43c6/src/main/java/vexatos/tgregworks/integration/TGregRegistry.java#L46

**Comment by chochem** [comment]
> just delete these config about material-id should solve this problem

> emm I explain the reason for the change of material stats.

can you elaborate then? what exactly should we delete? You said 'config about material-id'. Is that not the TGregworks.cfg? Because we deleted that already anyway.

**Comment by Glease** [comment]
> delete id config
> auto assigned id isn't the same as old id and stuff broke

I don't see anything wrong here. can anyone enlighten me? /s

why would you delete an id config anyway? it's not a fml controlled namespaced registry and it cannot correct itself. You should just fix the colliding ones and not just outright delete everything. You tried a easy and lazy fix and now the drawback hits you. Fair exchange I'd say.

Also I do not think we have anything like a "dev release" made beyond 2.2.3, so I have absolutely no idea what on earth you are talking about.

**Comment by iouter** [comment]
> can you elaborate then? what exactly should we delete? You said 'config about material-id'. Is that not the TGregworks.cfg? Because we deleted that already anyway.

only delete this part. 
![image](https://user-images.githubusercontent.com/62897714/205085382-35b4c089-f3fd-4c69-9904-6026b5b47189.png)
but it cant solved the id shifted.

**Comment by Dream-Master** [comment]
I make no official dev release but i still progress and add new stuff. When DAXXL is up i can make a dev release

**Comment by Glease** [comment]
[Do what dream do on every release where new material is inserted.](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/15768016abb62b366cfeef57ce6a8a68fdcc32ce#diff-547119cb804143c7203f75e284150317a7e9c6d6ccdcd9b3fd6cb525918a3197R2485) Do not delete the whole freaking thing. You get what you asked for.

**Comment by chochem** [comment]
Deleting the file has always been the advice on discord in the past but what you say makes sense.

I guess testing the pack is getting _even more_ complicated. That is depressing.

Is there no way to fix it more properly like assigning new materials to _actually available_ ids based on the existing file?
