### ISSUE TITLE
Crash Upon Logging into Server -- ClassCastException

### ISSUE THREAD

**Issue by TTiole** [GTNewHorizons/GT-New-Horizons-Modpack#11919]
### Your GTNH Discord Username

iole#2994

### Your Pack Version

2.2.0

### Your Server

Private Server

### Type of Server

None

### Your Actions

I was simply attempting to log into a server recently migrated into 2.2. This was my own server. The world was originally created in 2.1, that may be the reason I'm having this issue.

### Crash Report

[crash-2022-12-04_00.25.20-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10147992/crash-2022-12-04_00.25.20-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
Bug in bibliocraft.. 🤦 

For now try remove the entity item mentioned in crash report with nbtexplorer (or equivalenttool), or turn on removeErroringEntities in config/forge.cfg on server side. Be sure to turn it back off afterwards so it doesn't unintentionally delete something of value.

**Comment by Glease** [comment]
CORRECT: It's probably not what I thought. You probably had a corrupt chunk or a block id mismatch. Try a backup before upgrade.

**Comment by TTiole** [comment]
Yep, that did the trick. I had some issues with the migration initially (copied instead of replaced new files oops). Launching the server under that state likely corrupted world data. 
Thanks for your help!
