### ISSUE TITLE
Periodic, inevitable Lag Spikes

### ISSUE THREAD

**Issue by dhasial** [GTNewHorizons/GT-New-Horizons-Modpack#11910]
### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I did not expect lag spikes to make the pack unplayable. This issue is unique to this pack.

### The Reality

At a seemingly random interval, FPS drop from a range of 50-60 to 1-7 until I press F3 + A to reload all chunks. After doing so everything goes back to normal until the lag inevitably returns. Rinse and repeat. I made a new world wondering if it was a corrupted chunk or something, but no, within 3 minutes FPS dropped to unplayable levels until I pressed F3 + A again.

This is on an SSD, with autosaves set to every 30 minutes in case that's what causes it (I don't believe it is since the lag happens more frequently than that). I also disabled AromaBackup at one point to narrow it down, didn't change anything.

### Your Proposal

I'm honestly not sure where to start.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by dhasial** [comment]
I've found that I can fix the lag spikes by disabling optifine. I can't say I'm surprised to find that optifine/something added by the user was the issue. Optifine is for 1.7.10, version "HD U E7".

**Comment by chehob** [comment]
I have probably the same issue. Tried 2.2.0.0 on curse and 2.2.3 on multimc. At first I thought it was some GC problem. Tried Oracle java 8 with different memory allocations 6, 8, 12. Then tried RedHat java 8 with Shenandoah GC. Nothing changed. Then I found out it is lagging when crossing chunk borders, dunno what's the cause, maybe this will help you somehow. Right now it is really frustrating with exploration dropping frames from 75 to 0 every chunk.

**Comment by boubou19** [comment]
can you profile your game with visualvm or warmroast? this is the kind of stuff that is hard to reproduce

**Comment by chehob** [comment]
> can you profile your game with visualvm or warmroast? this is the kind of stuff that is hard to reproduce

I ran warmroast, I'm doing it for the first time, what exactly should I look for? Also I don't see any CPU usage spiking when it lags in game.

**Comment by chehob** [comment]
Ok, my problem was solved, dunno if it is related to op. I was having GPU spikes on chunk crossing from 30% to 60%. Did driver cleanup and reinstall newest drivers and now it is working normal.
gpu: radeon rx 580
drivers: amd adrenalin 22.11.2
