### ISSUE TITLE
Crashloop when using hologram projector

### ISSUE THREAD

**Issue by GDCloudstrike** [GTNewHorizons/GT-New-Horizons-Modpack#11911]
### Your GTNH Discord Username

GDCloud#2907

### Your Pack Version

2.2.3 + latest hodgepodge + dependencies

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Trying to use a hologram projector on a controller to look at a multi's structure in-world. The game freezes as it gets stuck in a crashloop. 

### Crash Report

Crash report: [crash-2022-12-02_23.15.13-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10144753/crash-2022-12-02_23.15.13-client.txt)
fml log: [fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10144754/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
I was immediately able to reproduce this in my dev install.

**Comment by querns** [comment]
This was happening to me as well (hodgepodge 2.0.10, structlib 1.2.0-beta.2). It happened regardless of whether I was asking for the hologram only or attempting an auto-build. Same infinitely generating crashlog with an `Already Tesselating!` error.

**Comment by YTXilo** [comment]
I have experienced it as well, Fixed by downgrading to latest 2.2.3 dev versions of these noted mods,

**Comment by YTXilo** [comment]
So some version or change in between 2.2.3 versions and Jenkins is obvious

**Comment by Glease** [comment]
autobuild will trigger hologram display regardless.

I don't quite recall changing anything regarding to hologram rendering these days. It could be anything.

**Comment by Glease** [comment]
Update structure compat to [v0.3.0](https://github.com/GTNewHorizons/StructureCompat/releases/tag/0.3.0).

**Comment by Glease** [comment]
As a side note: the better crashes mod is known to cause the final written crash report to be replaced by something that happens during its crash screen rendering or initialization. Developers should pay more attention to the full log for a (possible) original exception instead of the mysterious stack trace as reported by better crashes.

**Comment by chochem** [comment]
no more crash with update structure compat. thanks :)
