### ISSUE TITLE
Add "recycling" recipes to Railcraft boiler tanks

### ISSUE THREAD

**Issue by kaanyalova** [GTNewHorizons/GT-New-Horizons-Modpack#11912]
### Your GTNH Discord Username

kaanyalova

### Your Pack Version

2.2.3

### Your Proposal

Add recycling recipes to low/high pressure boiler tanks (similar to fireboxes)

### Your Goal

When the player starts using another power source (such as benzene) the tanks become completely useless

### Your Vision

It would at least give the player some raw resources. Instead of being useless

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
@kaanyalova didnt it work in arc furnace?

**Comment by kaanyalova** [comment]
> @kaanyalova didnt it work in arc furnace?

Not on the version I tested

**Comment by Dream-Master** [comment]
@kaanyalova try with 2.3.0-RC2

**Comment by kaanyalova** [comment]
> @kaanyalova try with 2.3.0-RC2

No recipes on 2.3.0-RC2 either.

**Comment by Dream-Master** [comment]
ok need to check what can do

**Comment by chochem** [comment]
caused by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/345 but that should still be fixable if we are careful about it
