### ISSUE TITLE
TPS Lag spikes

### ISSUE THREAD

**Issue by efaf543** [GTNewHorizons/GT-New-Horizons-Modpack#11929]
![image](https://user-images.githubusercontent.com/60048016/205718663-ff2de17b-9020-4069-acf7-f1dd89e114f6.png)
### Your GTNH Discord Username

xXx_Avokado_xXx#8656

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expected to play normally without tps lags

### The Reality

I downloaded gtnh one two months ago i used to play it normally, but the last time im experiencing alot lag spikes like mining block and it will drop alot later or even will not break.

I tried alot of things, started using multimc, optifine, reload modpack, reinstall, etc... Im really confused about it, i like gtnh and i dont want to stop play it. 
Pc
Ram-12gb
GPU-NVIDIA GeForce GTX 960
CPU-AMD FX(tm)-8300 Eight-Core-Processor 
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10157055/fml-client-latest.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10157057/latest.log)
In mc allocated 6gb and in pc left something bout 3gb to use

### Your Proposal

Dont know where to start

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by snoudin** [comment]
Have same problem. Looks like it happens because huge log dumps constantly. Now i am having 1GB log just before I have world loaded in singleplayer.

**Comment by snoudin** [comment]
Also moving game to ubuntu helped for a week) Just a bit better optimization here

**Comment by mitchej123** [comment]
Need a visual vm profile or equivalent

**Comment by snoudin** [comment]
Spent last 10 hours trying to config logs properly. Disabled forge logs and tps grew a lot
