### ISSUE TITLE
утечка памяти | memory leak

### ISSUE THREAD

**Issue by abitaredomdepo** [GTNewHorizons/GT-New-Horizons-Modpack#11922]
### Your GTNH Discord Username

AngelDust23

### Your Pack Version

2.2.3

### Your Server

private server

### Type of Server

Ultramine

### Your Actions

при открытии инвентаря начинается утечка памяти, и заканчивается сразу же при закрытии инвентаря. есть подозрение на NEI или на один из его аддонов

When you open the inventory, it starts leaking memory and ends immediately when you close the inventory. I suspect NEI or one of its addons

на видео был выключен мод "fastcraft". при этом моде тоже была утечка но менее заметна. без него это происходит быстрее

on the video, the "fastcraft" mod was turned off. with this mod, there was also a leak but less noticeable. it goes faster without it

https://youtu.be/FnSzen5z8jU

### Crash Report

1

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by hoshinokiseki** [comment]
are you using amd graphic card with the newest driver and wearing some equipment from ThaumicTinkerer?

**Comment by abitaredomdepo** [comment]
> Вы используете графическую карту AMD с новейшим драйвером и каким-то оборудованием от ThaumicTinkerer?

![Снимок](https://user-images.githubusercontent.com/51705777/205498417-46bdaf71-8e82-4757-a66e-56b70647f859.PNG)

по поводу "ThaumicTinkerer" вроде ничего из этого мода не использую пока-что
about "ThaumicTinkerer" I don't seem to use anything from this mod yet

**Comment by abitaredomdepo** [comment]
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10148866/latest.log)

**Comment by hoshinokiseki** [comment]
it seems like the newest driver has some question with gtnh. so i downgrade to 22.5.1.

**Comment by abitaredomdepo** [comment]
![image](https://user-images.githubusercontent.com/51705777/205500859-67c77d9a-a083-4f33-bf85-50fa1b7fffe2.png)

я выяснил. одевая эту шмотку начинается утечка памяти. можно это как то решить?
I found out. Wearing this clothes starts a memory leak. can this be solved somehow?
