### ISSUE TITLE
Server crash loop on replacing an output hatch of a bacterial vat

### ISSUE THREAD

**Issue by Dacer1** [GTNewHorizons/GT-New-Horizons-Modpack#11923]
### Your GTNH Discord Username

DacerFanAccount#4757

### Your Pack Version

2.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Actions

Tried to switch out the fluid output hatch of a Bacterial Vat but the Server crashes when breaking the hatch.

The hatch becomes breakable if the bacterial vat controller is removed before, but then crashes once again if the bacterial vat controller is placed inside the multiblock again

The setup was as follows

![2022-12-04_16 46 25](https://user-images.githubusercontent.com/23403241/205501569-50e23c51-8382-415a-9530-5f2506c0fd92.png)
Output Hatch Side of the Multiblock, the shutter module activates via the redstone signal of the fluid detector cover underneath the output hatch.
The Quantum Tank II sends out a wireless Redstone Signal for automated shutdowns once it is near full capacity (shown in the next image)

![2022-12-04_16 47 05](https://user-images.githubusercontent.com/23403241/205501594-0c1b8957-d8c3-4dd9-89aa-f7e5452f4ed4.png)
The Wireless Fluid Detector Cover on the Quantum Tank II

![2022-12-04_16 46 36](https://user-images.githubusercontent.com/23403241/205501615-a8c43692-ee29-4d09-a2b4-f3600cb8c1ad.png)
The Setup underneath the Vat, on the bottom right is the input hatch with the Mutagen fluid, top right has the ME Stock input bus with all the materials for Raw Growth Catalyst Medium, on the far right you can see the fluid detector cover setup for automated extraction of fluids to keep the hatch at 1/2 capacity. On the left you see a dropper setup for NQ+ Rods which is controlled by an IC circuit (shown later)

![2022-12-04_16 46 42](https://user-images.githubusercontent.com/23403241/205501655-c236969e-4e44-4b73-93a8-4f8a99403934.png)
IC Circuit whose purpose it is to drop in Long NQ+ Rods every 10.5s and send an activation signal to the controller AFTER the first rod has dropped, the Circuit stops sending Redstone signals once the input on the right is set to "on".

![2022-12-04_16 48 50](https://user-images.githubusercontent.com/23403241/205501691-f064b27a-3da4-4c21-9ee2-6591adf757eb.png)
The previously mentioned IC Circuit.

![2022-12-04_16 48 29](https://user-images.githubusercontent.com/23403241/205501707-8129087f-1be8-40f7-a20a-28c3b04a69a3.png)
Cover to the left side of the IC circuit (sends activation signal to the controller; shown next image)

![2022-12-04_16 46 55](https://user-images.githubusercontent.com/23403241/205501716-8cb3de92-7056-4a19-91b6-de9f411fab13.png)
Receiver Cover for the Controller

![2022-12-04_16 57 00](https://user-images.githubusercontent.com/23403241/205501795-89b5c301-7054-4a28-a0bf-e55e1a2e0889.png)
Cover to the right of the IC circuit, this one waits for the signal of the Quantum Tank II. 

### Crash Report

![211958995 17000002_image](https://user-images.githubusercontent.com/23403241/205501807-9b2fa600-863d-4337-8735-dfeac6a750bc.png)

The Server is also running 5 updated mods via Jenkins

bartworks-1.7.10-0.5.102.jar
GalaxySpace-1.7.10-1.1.17-GTNH-1-g2289f9b.jar
GoodGenerator-1.7.10-0.4.39-2-g6b97a71.jar
GT-PlusPlus-1.7.10-1.7.124-pre.jar
kekztech-1.7.10-0.6.18-pre-1-gfc64e68

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
You should be able to recover from the situation by
1. use an updated release of bw after https://github.com/GTNewHorizons/bartworks/pull/241 is merged
2. remove vat from save using NBTExplorer 
3. remove information panel pointing at the vat using NBTExplorer, or somehow disable it, or remove the sensor card from information panel

**Comment by miozune** [comment]
Next time please provide crash log as text file or external link, not as screenshot.
