### ISSUE TITLE
Native Clusters not Droping from GT Ores

### ISSUE THREAD

**Issue by dimondmine2** [GTNewHorizons/GT-New-Horizons-Modpack#11934]
### Your GTNH Discord Username

Deamondo#1982

### Your Pack Version

2.2.0.0

### Your Server

Private Server

### Type of Server

Don't know

### Your Expectation

When breaking GT ores using the Pickaxe of the Core or the Chameleon Pickaxe with the Fiery Core enchantment, native clusters should drop

### The Reality

The GT ores do not appear to drop native clusters as expected

### Your Proposal

Adjust the POtC and Fiery Core enchant to drop native clusters from GT ores.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
They are known to be not supported. Yet they can be made to do so. It has been under consideration for a while but uh no solid plans yet,
* See  https://github.com/Glease/TC4Tweaks/issues/17

**Comment by dimondmine2** [comment]
Sounds good. Thanks for taking interest. I look forward to when this meets priority requirements
