### ISSUE TITLE
Upon breaking a nuclear reactor, contents that were once inside of the reactor were multiplied and spit out

### ISSUE THREAD

**Issue by Koalacards** [GTNewHorizons/GT-New-Horizons-Modpack#11930]
### Your GTNH Discord Username

Koalacards#4126

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I was tearing down my nuclear reactor to move it- nothing crazy. I first removed all of the components inside (uranium cells, reactor plating, component vents, etc), then went to remove the reactor chambers and expected to get 5 reactor chambers and a nuclear reactor block only.

### The Reality

Upon breaking the nuclear reactor and the chambers, I received a TON of extra components, including 14 extra quad uranium cells (I had 4 in my machine design), and nearly a compressed chest's worth full of components I had used in my design.

Screenshots:
Original nuke design: 
![image](https://user-images.githubusercontent.com/44925247/205779606-80415d3c-427b-4ef2-8fd5-2b65dfe6bc76.png)
Compressed chest full of duped items:
![image](https://user-images.githubusercontent.com/44925247/205779772-246035f5-bb27-4f5d-8cfe-4d25bcb3486a.png)

### Your Proposal

Dont spit out a ton of duped items when removing reactor chamber

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Can't reproduce on 2.2.0.0.

**Comment by bruce-webb** [comment]
I had some funniness when I right click with a dolly on the reactor. It voided a lot of components that were left in the reactor. On version 2.2.0.0

**Comment by Koalacards** [comment]
One thing I noticed after creating this issue is one of the reactor chambers also broke and returned a basic machine casing- I'm not sure if that is expected functionality either, maybe the items were duped when that reactor chamber was broken?

**Comment by Glease** [comment]
Huh, are you using a IC2 wrench? I thought they are disabled?

**Comment by Koalacards** [comment]
Nope I definitely used a gregtech wrench! Just a default stainless steel wrench, about half durability if that helps.

**Comment by twinter838** [comment]
On a 2.2.0.0 server, our reactor was not outputting power for a reason we could not determine, we tried breaking and replacing it to try and fix the issue, and the same thing happened, reactor duped about 1000 of each component.

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.

**Comment by Reflex18** [comment]
From what i can determine from placing and breaking reactors. When breaking a reactor chamber i get the items back that were in that chamber area. However, when breaking a reactor main i void all of the items within the reactor itself.

**Comment by Pxx500** [comment]
https://discord.com/channels/181078474394566657/658620984714067968/1152701918188142715

The reactor itself is very bad since it's IC2 :/

**Comment by AronaDaal** [comment]
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/166624368/46c3c01d-d79b-4135-9422-1e0f08e72444)
I guess we can rule out the 6 items beeing dropped by breaking down the reactor chamber :D
