### ISSUE TITLE
Crash opening Gregtech input bus

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#11938]
### Your GTNH Discord Username

Tommeh#9804

### Your Pack Version

2.2.3

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Actions

I tried opening a regular Gregtech input bus on a volcanus containing nothing else but iron dust

### Crash Report

[crash-2022-12-08_23.24.39-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10190254/crash-2022-12-08_23.24.39-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
Hmm. Are you positive this is what you did? because the crash report is about a thaumic energistics gui (knowledge inscriber), not a volcanus.

**Comment by Tommeh1** [comment]
> Hmm. Are you positive this is what you did? because the crash report is about a thaumic energistics gui (knowledge inscriber), not a volcanus.

The only thaumic energistics terminal was 9 to 10 chunks away from me when it happened.

**Comment by Glease** [comment]
Perhaps somehow the wrong gui is being opened on client side. No doubt it'd crash.
