### ISSUE TITLE
tungsteensteel dust in GT++ mixer is 500 eu/t at base instead of 480

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#11936]
### Your Pack Version

2.2.3

### Your Proposal

i am unsure if this is a intended or not but it seems incorrect as its the only recipe ive seen so far (by the very end of IV) that is inconsistent with the normal power cost pattern. it is also the correct amount of 480 eu/t in a singleblock mixer

### Your Goal

fix the power cost to be in line with all the others

### Your Vision

consistency in recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Both recipes now use 1920 EU/t https://github.com/GTNewHorizons/GT5-Unofficial/pull/1211
