### ISSUE TITLE
Mixer recipe for Gallium Arsenide dust missing

### ISSUE THREAD

**Issue by bathtubhat** [GTNewHorizons/GT-New-Horizons-Modpack#11939]
### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Questbook implies placing gallium and arsenic in a mixer will make gallium arsenide dust for making diodes

### The Reality

There is no mixer recipe in nei, and no way to make the dust that I can find 

### Your Proposal

Add back in the recipe to allow players to progress.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you forgot to load the default quests after updating
