### ISSUE TITLE
Remove scanner dependency from Unknown seeds no more quest

### ISSUE THREAD

**Issue by kaanyalova** [GTNewHorizons/GT-New-Horizons-Modpack#11946]
### Your GTNH Discord Username

kaanyalova

### Your Pack Version

2.2.3

### Your Proposal

Remove(or add an OR dependency from Cropnylazer quest) the dependency of `Scanning Bees, Crops and Moooooore!` from the `Unknown Seeds No More` quest in the `Fishing, Farming, Cooking` quest line. 

### Your Goal

Most players will probably prefer to use the cheaper and portable cropnalyzer instead of (much) more expensive scanner

### Your Vision

Players shouldn't have to craft an expensive and unnecessary machine just to continue the quest book.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
fixed in dev. see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/11878, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11877
