### ISSUE TITLE
Regression rendering wrong textures with animations

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#11953]
### Your GTNH Discord Username

leagris

### Your Pack Version

All since someone broke this

### Your Server

Irrelevant

### Type of Server

None

### Your Expectation

All the turbine textures on the controller and surrounding casings should match exactly as it did before someone broke it and ran away.

### The Reality

Turbine controller texture overlay no longer matches casing texture animation. Either out of sync or wrong orientation.
![image](https://user-images.githubusercontent.com/1111474/206899963-fd94a9c7-8ee6-481c-b39b-3d89cf326a2d.png)

### Your Proposal

Fix the regression and render controller overlay exactly same as casing overlay so the turbine texture is rendered seamlessly and animated in sync between connected blocks as it did before.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Looks like mirrored.

**Comment by leagris** [comment]
> Looks like mirrored.

I always expressed concerns about this mirroring of controller overlay, and this is one of the reasons.

**Comment by Tommeh1** [comment]
Still exists in 2.2.10, please re-open

**Comment by Tommeh1** [comment]
I just checked, it also still affects turbines 
![image](https://user-images.githubusercontent.com/39203645/222927499-f4180013-5f7c-4257-8a15-38e4095aa4cd.png)

**Comment by chochem** [comment]
everything is fine on my end, but reopen cant hurt

**Comment by Ethryan** [comment]
Let’s test with new release and close this if it’s fixed.

**Comment by Tommeh1** [comment]
> Let’s test with new release and close this if it’s fixed.

It still exists in 2.3.0 
![image](https://user-images.githubusercontent.com/39203645/224794860-96f156fd-783f-4690-a911-9edaf1adc29f.png)

**Comment by leagris** [comment]
Before doing fancy rounded corner square turbine, maybe this should be prioritized.
Now we have two bugs with turbine texture.
This major setback regression
https://cdn.discordapp.com/attachments/224191655375273985/1118266800354906162/image.png
and This texture glitch!
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12457

Raised to bugMajor so people responsible for both bugs can do a rollback or fix their own code
