### ISSUE TITLE
Crash when setting up a template by dragging things from NEI

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#11955]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.2.3

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Actions

I put the recipe in the template via NEI and decided to change one item. He is glued to the cursor and throws it off the server when trying to remove it

Another player on the server where I play has the same error, even though we switched to the modpack version 2.2.3

### Crash Report

https://paste.ubuntu.com/p/gVH87sjdWH/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
Please update NEI; you're on 2.3.7, latest is 2.3.16; this was fixed circa 2.3.8

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11531
