### ISSUE TITLE
Animated items flash faster when there are more of them

### ISSUE THREAD

**Issue by IncandescenceSy** [GTNewHorizons/GT-New-Horizons-Modpack#11958]
### Your GTNH Discord Username

Incandescence~ ♡#8301

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

None

### Your Expectation

I put myself in a situation where multiple animated GT++ textures were onscreen at the same time, and I thought that nothing special would happen.

### The Reality

It seems that all copies of the same GT++ animated item share an animation counter. See attached videos for a demonstration.
Hypogen (eyestrain warning): https://streamable.com/sp2h24
Celestial Tungsten (eyestrain warning): https://streamable.com/nxuro3
Chromatic Glass (worse eyestrain warning): https://streamable.com/hrv2ft
An entire Compressed Chest of Chromatic Glass (there was a point when this was about half full where this was terrible to look at, but the full thing isn't that bad because it's too fast for the monitor / the human eye to keep up; still, pretty bad for the eyes): https://streamable.com/1pt3df

### Your Proposal

Fix all animated items ticking the counter so that the speed doesn't increase

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Probably because gtpp does gt style animation and is ticking the color in some method in Item class, instead of a method in gt_client.
