### ISSUE TITLE
Patterns with substitution enabled broken after updating

### ISSUE THREAD

**Issue by Miisi** [GTNewHorizons/GT-New-Horizons-Modpack#11957]
### Your GTNH Discord Username

Misi#3673

### Your Pack Version

2.2.7

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

craft stuff patterned in my ME system

### The Reality

![image](https://user-images.githubusercontent.com/46682682/206931976-c2c9e1ea-b6af-408d-9ccb-35a4e4cf47d8.png)
![image](https://user-images.githubusercontent.com/46682682/206931979-70686955-8932-4e61-a274-ba88e115323b.png)
![image](https://user-images.githubusercontent.com/46682682/206932073-c0af8470-3d63-4522-bfa2-ce923d056d96.png)

(not my images)

AE2 doesn't recognize patterns that have the "Can be a substitution: No" option. All patterns from previous versions were updated as to have that option disabled, so now they have to be redone. I initially thought the issue was related to tools in recipes but it seems to affect all of them, as I just found someone in Discord with the issue (gold ingot pictures above)

### Your Proposal

fix/change the default from updating to Yes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Miisi is this pure ae2 stuff or ec or other ae2 addon stuff ?

**Comment by Miisi** [comment]
> @Miisi is this pure ae2 stuff or ec or other ae2 addon stuff ?

this is all from AE2

**Comment by chochem** [comment]
both of these work for me:

![image](https://user-images.githubusercontent.com/40274384/206932712-1bd0479a-108e-41a5-bf1c-05e1fe09b2d0.png)
![image](https://user-images.githubusercontent.com/40274384/206932727-8f9c08a1-2b97-42cb-b200-0cf02da741db.png)

**Comment by Miisi** [comment]
> both of these work for me:
> 
> ![image](https://user-images.githubusercontent.com/40274384/206932712-1bd0479a-108e-41a5-bf1c-05e1fe09b2d0.png) ![image](https://user-images.githubusercontent.com/40274384/206932727-8f9c08a1-2b97-42cb-b200-0cf02da741db.png)

can you try removing every gold ingot stored in your system? I (and the person who also had the problem) had the issue with recipes that had to be done from the first steps

**Comment by minecraft7771** [comment]
> both of these work for me:
> 
> ![image](https://user-images.githubusercontent.com/40274384/206932712-1bd0479a-108e-41a5-bf1c-05e1fe09b2d0.png) ![image](https://user-images.githubusercontent.com/40274384/206932727-8f9c08a1-2b97-42cb-b200-0cf02da741db.png)

But the issue is about cascaded recipes, no?

**Comment by chochem** [comment]
removed all gold ingots. then crafted gold plates. still works fine.

**Comment by Impos913** [comment]
Substitution enabled patterns have issue.

**Comment by chochem** [comment]
ok so _only_ the people are screwed that have 'using substitutions: yes' for all their recipes I would assume.

**Comment by Miisi** [comment]
that'd align with what I had initially thought of patterns with tools breaking
![image](https://user-images.githubusercontent.com/46682682/206933722-9547b08b-90cb-49ec-9f7c-e5196fd0d324.png)
(for example)

I'm changing the issue's title

**Comment by chochem** [comment]
here is one thing I learned in testing that makes it a bit worse (and at least one person in zeta discord already stumbled over this):

If you have a recipe with 'using substitutions:yes' for example because there is a tool in there, it is not enough to add 'can be a substitution:yes' for just the tool. you also need to do so for all other ingredients.

A second observation for people playing around with this is that if you want to adjust your recipes and they are processing patterns, then you can't do it in the normal pattern terminal but you need to use the processing pattern terminal because of a bug (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11959).

**Comment by chochem** [comment]
this is still a problem in test-2.2.9-4-pre-dev. Was the fix reverted?

I just loaded up a 2.2.0.0 save and all the Use as substitution are false by default.

**Comment by Dream-Master** [comment]
> this is still a problem in test-2.2.9-4-dev-pre. Was the fix reverted?
> 
> I just loaded up a 2.2.0.0 save and all the Use as substitution are false by default.
> 
> ![image](https://user-images.githubusercontent.com/40274384/213871222-5eccec0f-2ca8-48d1-af9a-65e499f7fa4f.png)

2.2.0.0 has no substitution so far ik

**Comment by chochem** [comment]
2.2.0.0 does not have 'Use as substitution', correct.
That is why it gets some default value when you update to test-2.2.9-4-dev-pre.
The supposed fix here by miozune was to make that default 'true'. But it isnt, it is 'false'.

**Comment by eigenraven** [comment]
Use as substitute should probably remain off by default, because too many things have weird/many-item oredicts that could cause issues for matching patterns to items.

**Comment by chochem** [comment]
that is pretty be terrible for people that allow substitutions for all their patterns. They will need to redo all of them. (not me :P)

**Comment by chochem** [comment]
Alright, I tested it a bit more in the latest dev (7-dev-pre) and it looks like somebody actually did fix it without posting here.

The change being that:
if you craft A which has substitutions allowed and uses B; and B has a pattern with 'use as substitution:no'. Then it will actually now craft and use B despite it saying no!

So substition check now only seems to apply to stuff that is actually different from what you put in the pattern. Even works with tool durability as long as its the same tool.

That is good enough for me!
