### ISSUE TITLE
Industrial Mixing Machine No longer combining recipies across Input buses

### ISSUE THREAD

**Issue by NovanOfLowat** [GTNewHorizons/GT-New-Horizons-Modpack#11963]
### Your GTNH Discord Username

NovanIV#9146

### Your Pack Version

2.2.7.0

### Your Server

Private

### Type of Server

Don't know

### Your Expectation

To make an alloy dust (or similar) out of multiple types of dust in the Industrial mixing machine I should be able to feed each component material into its own separate input bus and have the machine combine them, as was the case in 2.0.0.0.

### The Reality

Mixer will not function unless ingredients are in the same bus.  This makes batch processing/automation difficult as if the bus fills up with one ingredient bus must be manually reset to have proper ratios.  Other GT++ multis may be similar (untested).

### Your Proposal

Revert previous behavior in 2.0.0.0, or allow toggle as with processing array.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
It was a bug that it did no seperation which got fixed, but I opened a ticket to add the toggle.
