### ISSUE TITLE
spice of life asm error

### ISSUE THREAD

**Issue by bengenie** [GTNewHorizons/GT-New-Horizons-Modpack#11967]
### Your GTNH Discord Username

bengenie#5497

### Your Pack Version

2.2.7

### Your Server

sp

### Type of Server

Single Player

### Your Actions

log: https://paste.atlauncher.com/view/aba822ff-df88-4d91-b006-55728fbc60fd
I got huge amuond of asm error when I open nei

### Crash Report

[crash-2022-12-12_21.31.48-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10213790/crash-2022-12-12_21.31.48-client.txt)
[crash-2022-12-12_21.19.39-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10213791/crash-2022-12-12_21.19.39-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by DerpityDoo** [comment]
I think I have the same crash. I have optifine installed.
[crash-2022-12-13_20.53.52-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10223905/crash-2022-12-13_20.53.52-client.txt)

**Comment by bengenie** [comment]
Didn't know it an duplicate of #11645
