### ISSUE TITLE
Dimensional Anchors Causing TC NEI to fail

### ISSUE THREAD

**Issue by Beannsss** [GTNewHorizons/GT-New-Horizons-Modpack#11961]
### Your GTNH Discord Username

Beangate#7274

### Your Pack Version

2.3.7

### Your Server

Personal Server, also SP.

### Type of Server

Vanilla Forge

### Your Expectation

Load into a world with just immibis core and dimensional anchors added, and be able to access TC recipes in NEI.

### The Reality

Loading into the world, either server or SP, game crashes back to server select screen (NOT TO DESKTOP). Then you can load into said world fine but without access to TC recipes in NEI.

### Your Proposal

Load into server without failure, and have access to TC recipes with dimensional anchors loaded.

I believe this came from 2.2.0, but I know for sure it wasn't a thing in 2.1.2.3.

Easily reproducible with just a fresh pack install of 2.2.3/2.2.7, immibis core, and dimensional anchors.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by YinScape** [comment]
When connecting to a server, the following error appears in latest.log

`[22:10:58] [NEI Plugin Loader/ERROR]: Failed to Load com.djgiannuzz.thaumcraftneiplugin.nei.NEIConfig
java.lang.NullPointerException
	at com.djgiannuzz.thaumcraftneiplugin.nei.recipehandler.ArcaneShapedRecipeHandler.<init>(ArcaneShapedRecipeHandler.java:43) ~[ArcaneShapedRecipeHandler.class:?]
	at com.djgiannuzz.thaumcraftneiplugin.nei.NEIConfig.loadConfig(NEIConfig.java:27) ~[NEIConfig.class:?]
	at codechicken.nei.NEIClientConfig$8.run(NEIClientConfig.java:453) [NEIClientConfig$8.class:?]
[22:10:58] [NEI Plugin Loader/INFO]: Initiated handler removing...
[22:11:00] [Client thread/INFO]: Starting NEI Filter scripting. This might take a moment to load all the modules...`

**Comment by YinScape** [comment]
I can confirm that this bug no longer occurs after updating to 2.3.2.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/TCNEIAdditions/pull/20
