### ISSUE TITLE
Shared scan item for two recipes

### ISSUE THREAD

**Issue by Miisi** [GTNewHorizons/GT-New-Horizons-Modpack#11964]
### Your GTNH Discord Username

Misi#3673

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

None

### Your Expectation

scan an item

### The Reality

![image](https://user-images.githubusercontent.com/46682682/207034808-fabefd48-b882-410d-b0cb-31dfd58c663d.png)
advanced assembly line
![image](https://user-images.githubusercontent.com/46682682/207034850-1b05bfeb-cfd4-44ec-9c21-eb890f82dbd8.png)
component assembly line

both share the same scan item, an assembly line controller

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
or we can add a control circuit to the scanner ? (ghost circuit ) @Glease
