### ISSUE TITLE
The ability to clean ME Glass Cable from paint

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#11960]
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.2.3

### Your Proposal

Add recipes for cleaning ME Glass Cable from paint

### Your Goal

There is not enough opportunity to clean ME Glass Cable from paint. ME Dance Cable has such an opportunity

### Your Vision

It is good when there is an opportunity to repaint the cable if you change your mind or for another reason

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by repo-alt** [comment]
Use a color applicator filled with snowballs?

**Comment by Eldrinn-Elantey** [comment]
> Use a color applicator filled with snowballs?

To be honest, I didn't know about this possibility. Anyway, the presence of crafting would be more convenient. As I wrote above, other cables have paint cleaning capabilities through craft

![image](https://user-images.githubusercontent.com/46845681/207742204-44cdc97e-832a-45a5-9bba-8b431d67f069.png)
