### ISSUE TITLE
Thorium Yttrium Glass is HV now

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#11970]
### Your GTNH Discord Username

ImpossibleVT#3997

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Realized thorium yttrium glass tooltip says it is HV tier.

### The Reality

![image](https://user-images.githubusercontent.com/36479271/207322221-a80e9e60-3d11-4856-8f97-da19d43e5092.png)
It has ore dict of blockGlassIV and it used to be IV tier glass and can be used as IV glass in crafting. I haven't tested them on glass using multis but it may break stuff for people.

### Your Proposal

Change it back to IV tier.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
Who changed it? I did it for my Lap Multiblock and it was IV.

**Comment by Impos913** [comment]
Could be related to https://github.com/GTNewHorizons/bartworks/pull/240

**Comment by chochem** [comment]
@Glease
