### ISSUE TITLE
ME Output Hatch ridiculous energy consumption

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#11971]
### Your GTNH Discord Username

ImpossibleVT#3997

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

My multis have been shutting down due to power loss. I tracked it down and it appears my ME system has been drinking it. I have an IV powered multiblock electrolyzer for sugar with ME Output Hatch (the only machine i have with me output hatch and outputting 250kL of oxygen and 50kL of water every 4 seconds).

### The Reality

![image](https://user-images.githubusercontent.com/36479271/207437061-c8e2e8e5-2f37-41ee-9be4-49432b172f3c.png)
![image](https://user-images.githubusercontent.com/36479271/207437091-d9b0fe9b-a59f-4e62-b9c9-f20b65f2c952.png)
The first picture is with it turned off and second picture is with it turned on. Energy usage of my network spikes when the electrolyzer outputs and pulls all the energy on the line. I couldn't run an EBF with 2 IV hatches on a 64A IV supplied cable (also powers the me system). The single me output hatch i have seems to average like 30kEU/t while it's working.

### Your Proposal

Greatly reduce the energy usage considering these output hatches will be used widely.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Impos913** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/1473 @GlodBlock's pr to add the hatch

**Comment by YTXilo** [comment]
I mean its usually better to store it in either yot tanks or just super/quantum tanks than ae2, faster transport and less lag causing, switching over all has the benefit of using almost no power.

**Comment by Impos913** [comment]
The fluid is not stored in ae2, it is stored in a bedrockium drum with fluid storage bus on it. It uses almost no power if I use the same setup outputting to a dual interface instead .And I believe you missed the point this is a bug
