### ISSUE TITLE
Big fps lag spikes caused by blockrenderer mod

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#11977]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.2.7 (+updated tctweaks)

### Your Server

SP

### Type of Server

None

### Your Expectation

no such lag spikes. (btw, I am using optifine E7)

### The Reality

steps to reproduce:

1. start game, fly around, everything is (mostly) fine, no massive spikes.
2. open up NEI and look at a multiblock preview (lets say CoAL)
3. fly around the base again. Suddenly there are massive lag spike whenever multis are coming into renderdistance. (its fps. \xu_tps shows that tps are not affected)

(I restarted twice and found the same each time)

control test:
1. start game without this mod.
2. never get such large lag spikes

more details from the pie chart in shift+F3:
the spike specifically stems from root.tick.level.entities.blockentities with the offender being "checkedPosition < toCheckCount". This one item literally causes the entire spike.

confirmation by others:
- Misi (on discord) also had large lag spikes when multis where coming into renderdistance and resolved it by removing the blockrenderer mod.
- Fiyorin (discord) 
![image](https://user-images.githubusercontent.com/40274384/207676499-1f6b5dba-bf6f-4eac-b6ed-e702743a143c.png)

### Your Proposal

try to fix it. Potentially this might be the cause of some of the other lag-tickets regarding 2.2.3+ but those are not very specified.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by cinch** [comment]
can confirm. tried it 2x and after showing the preview of the DTPF results in big stuttering/fps drops (1-2 seconds). before i could fly through my large base with gravtiy armor+boost key without a hiccup. 
tested on 2.2.3 without optifine

**Comment by chochem** [comment]
@Quarri6343 any ideas? there seem to be a lot of people on discord confirming this.

**Comment by chochem** [comment]
a discord search tells me the probably has been known for a while (just not reported to github)
![image](https://user-images.githubusercontent.com/40274384/207991426-8d26f646-1d0d-4ab7-bea7-1bf8ea27074b.png)

and that quarri is somewhat aware
![image](https://user-images.githubusercontent.com/40274384/207991478-7f10fd88-649b-41fc-9763-e6c119fc1f6b.png)
(link is to the madman post above)

I dont know if they looked into it though.

**Comment by Quarri6343** [comment]
`root.tick.level.entities.blockentities with the offender being "checkedPosition < toCheckCount". This one item literally causes the entire spike.`

I didn't touch tileentity ticking in my mod
it may caused by other mod that does tileentity ticking in the NEI preview scene...

**Comment by Quarri6343** [comment]
a memo
https://forums.minecraftforge.net/topic/18396-172unsolved-massive-lags-checkedposition-lt-tocheckcount/

**Comment by chochem** [comment]
luckily mitch and ALongStringOfNumbers where helping out on discord. For the record:

This is likely cause by not doing this
![image](https://user-images.githubusercontent.com/40274384/208003844-a99a83df-d506-4f87-b0d8-fbad9f9b9739.png)

specific code being here https://github.com/GregTechCEu/GregTech/blob/master/src/main/java/gregtech/api/metatileentity/multiblock/MultiblockControllerBase.java#L73-L86

Will need a fix on the gt5u side.

**Comment by miozune** [comment]
Hopefully this works http://jenkins.usrv.eu:8080/job/Block-Renderer/8/

**Comment by chochem** [comment]
that doesn't work sadly. Thanks for trying!

I have gone back to test a bit further. Specifically trying to capture the spike in visualvm. This would be much easier for people with potato PCs I think but I kind of had some success:

CPU hotspots for a single fairly controlled easily reproducable lag spike (aka moving a tiny bit to load in my fusion reactors and a few multis around that) (This is all with the fix attempt version by the way):

First, before using 3d preview. It feels smooth and the 'hotspots' look like this:
![image](https://user-images.githubusercontent.com/40274384/208218414-7a3b121a-c102-4c1e-8f8d-55827821ac86.png)

Second, after using 3d preview. It feels like a lag spike and the 'hotspots' look like this:
![image](https://user-images.githubusercontent.com/40274384/208218454-6cda56d4-5d5b-4be2-a6a3-213139bfaf1f.png)


I dont know what most of this does but what stands out to me is the gregtech.api.metatileentity.BaseMetaTileEntity.hasValidMetaTileEntity() as that broadly aligns with the previous theory.

**Comment by Glease** [comment]
@chochem may I suggest a seemingly completely unrelated experiment? try run `/ic2 uu-world-scan small`. The client will hang for a few minutes (not literal screen freeze, just that machine GUI won't open, new chunks won't be loaded, stuff like that) and after that you should see similar lags from happening.

**Comment by chochem** [comment]
I have tried. I only froze for like 10 seconds. I guess the 4 minute message is as old as IC2 :P

However, this did not create such lag for me. Not even a bit.

**Comment by chochem** [comment]
nice, this is fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1556.

**Comment by Zefix313** [comment]
This is still the case for the newest 2.3.0 version. Viewing the multiblock previews like Recipes and Usages still cause massive fps lag spikes every few seconds for the rest of the play time until relaunching the game. The CPU periodically goes up to 100%. Before using the multiblock feature, it constantly rests at 30-40%

**Comment by chochem** [comment]
with the precise problem described above? 'checkedPosition < toCheckCount' causing the spike? because that was fixed for me.

If its not that, make your own ticket. and analyse it more.

**Comment by Zefix313** [comment]
Yes it is 'checkedPosition < toCheckCount' being way too much time consuming. I thought this was fixed long ago

**Comment by chochem** [comment]
well it was. guess its back

**Comment by chochem** [comment]
of course in the meantime, the easiest is to just remove the mod. its terrible anyway.

**Comment by Zefix313** [comment]
I mean sadly it's a big part of this modpack because it contains all the recipes and the wiki is not up to date

**Comment by chochem** [comment]
Its not remotely a big part, no. It is very safe to remove blockrenderer, I do it myself. It adds nothing of value really except some (largely) incorrect visuals.

**Comment by Zefix313** [comment]
Don't you have to disable the entire Not Enough Items mod?

**Comment by chochem** [comment]
god no, not NEI. just blockrenderer.
