### ISSUE TITLE
fails to start minecraft from MultiMC Launcher

### ISSUE THREAD

**Issue by GeekyCactus123** [GTNewHorizons/GT-New-Horizons-Modpack#11973]
### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I am trying to install GTNH for the first time, but when trying to launch it, it fails. I go on the MultiMC instance page and double click the GTNH instance. Then it just fails to launch.

### Crash Report

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [65.8.174.64, 65.8.174.54, 65.8.174.51, 65.8.174.38]

session.minecraft.net resolves to:
    [34.197.32.8, 35.153.153.200, 100.24.172.95]

textures.minecraft.net resolves to:
    [13.107.227.51, 13.107.219.51, 2620:1ec:49::51, 2620:1ec:40::51]

api.mojang.com resolves to:
    [13.107.227.51, 13.107.219.51, 2620:1ec:49::51, 2620:1ec:40::51]

Minecraft folder is:
C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/instances/GT_New_Horizons_2.2.7_MMC/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 19.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/instances/GT_New_Horizons_2.2.7_MMC/natives

Libraries:
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [✔️] AdvancedSolarPanel-1.7.10-3.5.1a
  [✔️] adventurebackpack-1.7.10-1.0.5-GTNH
  [✔️] ae2fc-1.7.10-1.0.40-gtnh
  [✔️] ae2stuff-1.7.10-0.5.1.15-GTNH
  [✔️] AFSU-1.7.10-1.2.6-GTNH
  [✔️] AngerMod-1.7.10-0.6.3
  [✔️] AppleCore-1.7.10-3.2.3
  [✔️] appliedenergistics2-1.7.10-rv3-beta-122-GTNH
  [✔️] ArchitectureCraft-1.7.10-1.7.6
  [✔️] Aroma1997Core-1.7.10-1.0.2.16
  [✔️] AromaBackup-1.7.10-0.1.0.0
  [✔️] AsieLib-1.7.10-0.5.3
  [✔️] Automagy-1.7.10-0.28.2
  [✔️] Avaritia-1.7.10-1.31
  [✔️] Avaritiaddons-1.7.10-1.5.4-GTNH
  [✔️] backpack-1.7.10-2.2.7-GTNH-pre
  [✔️] bartworks-1.7.10-0.5.124-pre
  [✔️] battlegear2-1.7.10-1.1.2.1
  [✔️] Baubles-1.7.10-1.0.1.14
  [✔️] bdlib-1.7.10-1.9.8-GTNH
  [✔️] BeeBetterAtBees-0.3
  [✔️] BetterAchievements-1.7.10-0.1.0
  [✔️] BetterBuildersWands-1.7.10-0.9.3-GTNH
  [✔️] bettercrashes-1.7.10-1.1.7-GTNH
  [✔️] betterloadingscreen-1.7.10-1.3.36-GTNH
  [✔️] betterp2p-1.7.10-1.0.12
  [✔️] BetterQuesting-1.7.10-3.1.4-GTNH
  [✔️] BiblioCraft[v1.11.7][MC1.7.10]
  [✔️] BiblioWoods[BiomesOPlenty][v1.9]
  [✔️] BiblioWoods[Forestry][v1.7]
  [✔️] BiblioWoods[Natura][v1.5]
  [✔️] binnie-mods-1.7.10-2.0.46
  [✔️] BiomesOPlenty-1.7.10-2.1.0.2308-universal
  [✔️] BlockLimiter-1.7.10-0.55
  [✔️] blockrenderer6343-1.7.10-1.0.0-RC3
  [✔️] BloodArsenal-1.7.10-1.2.7
  [✔️] BloodMagic-1.7.10-1.3.18
  [✔️] Botania-1.7.10-1.9.11-GTNH
  [✔️] BotanicHorizons-1.7.10-1.0.12-GTNH
  [✔️] BrandonsCore-1.7.10-1.0.0.13-GTNH
  [✔️] bugtorch-1.7.10-1.1.6.5-GTNH
  [✔️] buildcraft-1.7.10-7.1.28
  [✔️] buildcraft-compat-1.7.10-7.1.12
  [✔️] BuildCraftOilTweak-1.7.10-1.0.3
  [✔️] CarpentersBlocks-1.7.10-3.3.8.2-GTNH
  [✔️] catwalks-1.7.10-2.1.3-GTNH
  [✔️] chisel-1.7.10-2.10.16-GTNH
  [✔️] chiseltones-1.7.10-1.0.4-GTNH
  [✔️] CodeChickenCore-1.7.10-1.1.6
  [✔️] CodeChickenLib-1.7.10-1.1.5.5
  [✔️] CoFHCore-[1.7.10]3.1.4-329
  [✔️] CoFHLib-[1.7.10]1.2.1-185
  [✔️] CompactKineticGenerators-1.7.10-1.0.1
  [✔️] Computronics-1.7.10-1.6.17-GTNH
  [✔️] Controlling-1.7.10-1.0.0.3
  [✔️] CookingForBlockheads-1.7.10-1.2.13-GTNH
  [✔️] craftpresence-1.7.10-1.8.3-GTNH
  [✔️] CraftTweaker-1.7.10-3.2.9
  [✔️] creativecore-1.7.10-1.3.27-GTNH
  [✔️] CropLoadCore-1.7.10-0.1.10
  [✔️] CropsPP-1.7.10-1.3.6.10-pre
  [✔️] CustomMainMenu-MC1.7.10-1.9.2
  [✔️] defaultserverlist-1.7.10-1.4.0
  [✔️] defaultworldgenerator-1.7.10-0.2
  [✔️] Draconic-Evolution-1.7.10-1.1.7-GTNH
  [✔️] DummyCore1.13
  [✔️] EMT-1.7.10-1.2.8.25
  [✔️] endercore-1.7.10-0.2.11
  [✔️] EnderIO-1.7.10-2.3.1.48
  [✔️] EnderStorage-1.7.10-1.4.12
  [✔️] EnderZoo-1.7.10-1.0.23
  [✔️] EnhancedLootBags-1.7.10-1.0.5
  [✔️] eternalsingularity-1.7.10-1.0.5
  [✔️] ExtraCells-1.7.10-2.5.28
  [✔️] extrautilities-1.2.13a
  [✔️] fastcraft-1.25
  [✔️] findit-1.7.10-1.0.11
  [✔️] FloodLights-1.7.10-1.2.8-137
  [✔️] Forbidden.Magic-1.7.10-0.6.4-GTNH
  [✔️] Forestry-1.7.10-4.5.6
  [✔️] forgelin-1.7.10-1.9.6-GTNH
  [✔️] ForgeMultipart-1.7.10-1.3.0
  [✔️] ForgeRelocation-0.0.1.4-universal
  [✔️] ForgeRelocationFMP-0.0.1.2-universal
  [✔️] gadomancy-1.7.10-1.0.8.5
  [✔️] galacticgreg-1.7.10-1.0.8
  [✔️] Galacticraft-1.7.10-3.0.57-GTNH-pre
  [✔️] GalaxySpace-1.7.10-1.1.22-GTNH
  [✔️] gendustry-1.7.10-1.6.5.5-GTNH
  [✔️] ggfab-1.7.10-0.0.2
  [✔️] GoodGenerator-1.7.10-0.4.62-pre
  [✔️] GraviSuite-1.7.10-2.0.68u
  [✔️] gregtech-1.7.10-5.09.41.166-pre
  [✔️] GT.Scanner.Mod-1.7.10-1.6.9
  [✔️] gtneioreplugin-1.7.10-1.0.18
  [✔️] GTNewHorizonsCoreMod-1.7.10-1.9.112
  [✔️] gtnhlanth-1.7.10-0.9.21-pre
  [✔️] gtnhlib-1.7.10-0.0.7
  [✔️] gtnhmixins-2.1.3
  [✔️] GTNH-TC-Wands-1.7.10-1.2.6
  [✔️] GT-PlusPlus-1.7.10-1.7.156-pre
  [✔️] GTTweaker-1.7.10-1.7.5
  [✔️] HardcoreDarkness-MC1.7.10-1.7
  [✔️] HardcoreEnderExpansion-1.7.10-1.9.3-GTNH
  [✔️] harvestcraft-1.7.10-1.0.18-GTNH
  [✔️] Healer-1.2.0
  [✔️] HelpFixer-1.0.7
  [✔️] hodgepodge-1.7.10-2.0.11
  [✔️] holoinventory-1.7.10-2.1.19-GTNH
  [✔️] HungerOverhaul-1.7.10-1.0.4-GTNH
  [✔️] hydroenergy-1.7.10-1.0.15-pre
  [✔️] IC2 Crop Plugin Version 1.7.10-1.3.1
  [✔️] IC2NuclearControl-1.7.10-2.4.16
  [✔️] ifu-1.7.10-1.9.5
  [✔️] IguanaTweaksTConstruct-1.7.10-2.2.3
  [✔️] industrialcraft-2-2.2.828a-experimental
  [✔️] InfernalMobs-1.7.10-1.7.7-GTNH
  [✔️] InGameInfoXML-1.7.10-2.8.3.93
  [✔️] INpureCore-1.7.10-1.1.2-GTNH
  [✔️] inventorytweaks-1.7.10-1.5.15
  [✔️] IronChest-1.7.10-6.0.71
  [✔️] IronChestMinecarts-1.7.10-1.0.8
  [✔️] irontanks-1.7.10-1.2.6
  [✔️] itlt-1.7.x-1.0.3
  [✔️] JABBA-1.7.10-1.2.21
  [✔️] journeymap-1.7.10-5.1.4p2-fairplay
  [✔️] kekztech-1.7.10-0.6.23-pre
  [✔️] kubatech-1.7.10-0.6.7-pre
  [✔️] littletiles-1.7.10-1.2.7-GTNH
  [✔️] logisticspipes-1.7.10-0.9.4.5.9-GTNH
  [✔️] lootgames-1.7.10-2.0.6
  [✔️] LunatriusCore-1.7.10-1.1.7-GTNH
  [✔️] magicbees-1.7.10-2.5.15-GTNH
  [✔️] malisiscore-1.7.10-0.14.5-GTNH
  [✔️] malisisdoors-1.7.10-1.13.6-GTNH
  [✔️] Mantle-1.7.10-0.3.5
  [✔️] mixingasm-1.7.10-v0.2.3
  [✔️] ModTweaker2-1.7.10-0.9.9
  [✔️] modularui-1.7.10-1.0.27
  [✔️] MouseTweaks-1.7.10-2.4.6-GTNH
  [✔️] MrTJPCore-1.1.0.33-universal
  [✔️] mxrandom-1.7.10-0.1.5
  [✔️] Natura-1.7.10-2.5.3
  [✔️] naturescompass-1.7.10-1.3.6-GTNH
  [✔️] NEIAddons-1.7.10-1.12.22
  [✔️] NEICustomDiagram-1.7.10-1.4.4.6
  [✔️] NEIIntegration-1.7.10-1.2.3
  [✔️] netherportalfix-mc1.7.10-1.1.1
  [✔️] NettyPatch-1.7.10-0.3.1
  [✔️] NodalMechanics-1.7.10-1.1.-6-GTNH
  [✔️] NotEnoughEnergistics-1.7.10-1.3.23
  [✔️] notenoughIDs-1.7.10-1.4.4
  [✔️] NotEnoughItems-1.7.10-2.3.16-GTNH
  [✔️] oauth-1.7.10-1.06.1-GTNH
  [✔️] OpenBlocks-1.7.10-1.6.9-GTNH
  [✔️] OpenComputers-1.7.10-1.8.0.2-GTNH
  [✔️] OpenGlasses-1.7.10-1.2.5-GTNH
  [✔️] OpenModsLibs-1.7.10-0.10.6
  [✔️] OpenModularTurrets-1.7.10-2.2.11-247
  [✔️] openprinter-1.7.10-0.1.2-GTNH
  [📁] OpenSecurity (folder)
  [✔️] opensecurity-1.7.10-1.0.119-GTNH
  [✔️] Opis-1.7.10-1.3.7-mapless
  [✔️] overloadedarmorbar-1.7.10-1.0.1
  [✔️] p455w0rdslib-1.7.10-1.0.4
  [✔️] Pam's Harvest the Nether 1.7.10a
  [✔️] personalspace-1.7.10-1.0.19
  [✔️] PlayerAPI-1.7.10-1.4
  [✔️] ProjectBlue-1.7.10-1.1.8-GTNH
  [✔️] ProjRed-1.7.10-4.7.9-GTNH
  [✔️] Railcraft-1.7.10-9.13.14
  [✔️] RandomThings-2.2.4
  [✔️] RemoteIO-1.7.10-2.4.7
  [✔️] roguelike-1.7.10-1.5.3-GTNH
  [✔️] RWG-1.7.10-alpha-1.3.3.0
  [✔️] Schematica-1.7.10-1.9.1-GTNH
  [✔️] SGCraft-1.7.10-1.3.13-GTNH
  [✔️] sharewhereiam-1.7.10-0.2.0
  [✔️] sleepingbag-1.7.10-0.1.4
  [✔️] SpecialMobs-1.7.10-3.3.13
  [✔️] SpiceOfLife-1.7.10-2.0.6-corrot-pre
  [✔️] SSP-1.1.2-GT-NH-Mod
  [✔️] StevesAddons-1.7.10-0.10.24
  [✔️] StevesCarts-1.7.10-2.0.2
  [✔️] StevesFactoryManager-1.7.10-1.1.1-GTNH
  [✔️] StorageDrawers-1.7.10-1.11.19-GTNH
  [✔️] StorageDrawersBop-1.7.10-1.11.17-GTNH
  [✔️] StorageDrawersForestry-1.7.10-1.11.17-GTNH
  [✔️] StorageDrawersMisc-1.7.10-1.11.17-GTNH
  [✔️] StorageDrawersNatura-1.7.10-1.11.17-GTNH
  [✔️] structurecompat-1.7.10-0.3.0
  [✔️] structurelib-1.7.10-1.2.0-beta.2
  [✔️] SuperTic-1.7.10-1.2.5
  [✔️] Tainted-Magic-r7.6
  [✔️] tcinventoryscan-1.7.10-1.0.12-GTNH
  [✔️] tcneiadditions-1.7.10-1.1.1.7.dirty
  [✔️] tcnodetracker-1.7.10-1.1.6
  [✔️] TConstruct-1.7.10-1.9.7-GTNH
  [✔️] TecTech-1.7.10-5.0.55-pre
  [✔️] TGregworks-1.7.10-GTNH-1.0.23
  [✔️] Thaumcraft-1.7.10-4.2.3.5a
  [✔️] Thaumcraft4Tweaks-1.4.23
  [✔️] ThaumcraftMobAspects-1.7.10-1.0.0-GTNH
  [✔️] thaumcraftneiplugin-1.7.10-1.7a
  [✔️] ThaumcraftResearchTweaks-1.7.10-1.0.3
  [✔️] Thaumic Machina-1.7.10-0.2.1
  [✔️] Thaumic-Based-1.7.10-1.4.31
  [✔️] thaumicenergistics-1.7.10-1.3.24-GTNH
  [✔️] Thaumic-Exploration-1.7.10-1.1.92-GTNH
  [✔️] ThaumicHorizons-1.7.10-1.2.1.8
  [✔️] thaumicinsurgence-1.7.10-0.0.8
  [✔️] ThaumicTinkerer-1.7.10-2.6.5
  [✔️] TiCTooltips-1.7.10-1.2.10
  [✔️] Tinkers-Defense-1.2.1d
  [✔️] TMechworks-1.7.10-0.2.16.4
  [✔️] TooMuchLoot-1.7.10-4.1.0-GTNH
  [✔️] torohealth-1.7.10-1.0.1
  [✔️] Translocator-1.7.10-1.1.2.20
  [✔️] TravellersGear-1.7.10-1.16.8-GTNH
  [✔️] TwilightForest-1.7.10-2.3.8.17
  [✔️] txloader-1.7.10-1.1
  [✔️] Universal-Singularities-1.7.10-8.6.5
  [✔️] visualprospecting-1.7.10-1.0.36
  [✔️] Waila-1.7.10-1.5.22
  [✔️] WailaHarvestability-1.7.10-1.1.10-GTNH
  [✔️] WAILAPlugins-1.7.10-0.2.5
  [✔️] WanionLib-1.7.10-1.8.3
  [✔️] WarpTheory-1.7.10-1.2.7-GTNH
  [✔️] Wawla-1.7.10-1.1.3-GTNH
  [✔️] WirelessCraftingTerminal-1.7.10-1.8.9.2
  [✔️] witchery-1.7.10-0.24.1
  [✔️] WitcheryExtras-1.7.10-1.1.12
  [✔️] WitchingGadgets-1.7.10-1.2.21-GTNH
  [✔️] WR-CBE-1.7.10-1.4.8
  [✔️] YAMCore-1.7.10-0.5.84
  [✔️] Ztones-1.7.10-2.2.2

Params:
  --username  --version 1.7.10 --gameDir C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/instances/GT_New_Horizons_2.2.7_MMC/.minecraft --assetsDir C:/Users/geeky/Downloads/mmc-stable-win32/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms6114m, -Xmx6114m, -Duser.language=en]

Minecraft process ID: 13724

Using onesix launcher.

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:110)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 5 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 13 Dec 2022 20:12:38 -0500
MultiMC: Log upload triggered at: 13 Dec 2022 20:12:44 -0500
MultiMC: Log upload failed!
Clipboard copy at: 13 Dec 2022 20:12:54 -0500

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Impos913** [comment]
> Java is version 19.0.1
You need java 8
