### ISSUE TITLE
AE2FC autocrafting bug

### ISSUE THREAD

**Issue by Rubijox** [GTNewHorizons/GT-New-Horizons-Modpack#11989]
### Your GTNH Discord Username

Rubijox#7659

### Your Pack Version

2.2.3

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

1. Request any craft that handles AE2FC autocrafting things using fluids.
2. There is no problem

### The Reality

1.Request a craft that uses fluids in the patterns
2.AE2 constantly tries to fill a machine that is already full with more fluid for a craft, fails but still fills the buffer with as much fluid as it can fit, and tries again (blocking mode cannot be used because of the cast)
3. auto-craft never finishes and you have infinity of whatever  component was being crafted, until you break the machine or the interface.(canceling the craft doesn't stop it from dumping fluid)

https://youtu.be/WfmSYScTHVA

### Your Proposal

AE2FC fluid crafting works properly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by asdflj** [comment]
fixed in https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/32
you can upgrade ae2fc version
