### ISSUE TITLE
P2P - Interface voids cards

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#11983]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Hi boubou, kuba and repolanien

### The Reality

How to reproduce:
place p2p interface
put some cards in it(i putted pattern capacity cards)
click on that p2p with item that transform it to other p2p( i clicked with fluix cable
puff - cards gone

patterns are voided too prob

### Your Proposal

Make it put it content in ae or drop on ground if not online

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Godelboard** [comment]
Same issue, different reproduction steps involving Advanced Memory Card (better P2P):

- Have p2p Interface on 2 spots with patterns on input designated side.
    - Shift right click with Advanced Memory Card on the _Input_ side P2P and select Bind Output for the Output side P2P(s)
    OR
    - Shift right click with Advanced Memory Card on the _Output_ side P2P and select Bind Input for the Input side P2P

Makes the interface on the Input P2P side void and reset everything, except its name (Patterns, Upgrade Cards, and Blocking mode status)

Additionally, wen you use a _regular_ Memory Card and you load settings for an Output side P2P, it _will_ spit out any patterns inside of it, but it will still also deletes any upgrade cards that were in the P2P interface, and it resets the interface's settings to default (no blocking). It doesn't matter if the output p2p was in blocking mode or not, nor if the input p2p is in blocking mode. The output p2p always ends up on blocking off.
