### ISSUE TITLE
Some GT++ cells using unlocalised names

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#11997]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The cells should show the correct name and should interact with tanks and fluid conduits normally.

### The Reality

The cells do not show the correct name, and cell contents can no longer be emptied into tanks, nor used on EnderIO conduits to put a matching fluid in the whitelist/blacklist.

### Your Proposal

Fix the cells.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by iouter** [comment]
which cell?

**Comment by BritishCynic** [comment]
Lots of them. Just to name a few, Coal Gas, Ethylbenzene, Anthracene, Coal Tar, etc. There's a whole range of cells not properly working, between the Dragonblood Plasma Cell and the Solar Salt (Hot) Cell in the NEI list.

**Comment by Dream-Master** [comment]
@iouter did gt++ need a patch about new fluid GT api as well ?

**Comment by iouter** [comment]
> @iouter did gt++ need a patch about new fluid GT api as well ?

maybe, but this already working fine.

**Comment by BritishCynic** [comment]
Upon further inspection in 2.2.8, these cells have the correct name, but still cannot be emptied into tanks, nor used in the EnderIO interface to set a fluid.
