### ISSUE TITLE
ModularUI crash and log spam with errors

### ISSUE THREAD

**Issue by FloatDoubling** [GTNewHorizons/GT-New-Horizons-Modpack#11994]
### Your GTNH Discord Username

DarkEastSider#3859

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I opened Advanced Assembling Machine UI, it just finished recipe, and i shift-right clicked on ghost circuit slot to clear ghost circuit, it was on 6 i suppose, but that doesn't matter. After that game just crashed with BetterCrashes suspecting that it was caused by 2 mods: ModularUI and FastCraft. I also have Optifine installed.

![2022-12-16_07 00 26](https://user-images.githubusercontent.com/115502326/208019199-b46d3771-ced0-455c-9394-789f6a37da07.png)

To add, crash happened after 2 hours of play, before that, i used all machines UI and shift-left\right clicked on ghost circuit slot just fine, but there was a lot of [modularui] issues in the log.

MultiMC Minecraft log (fml-client-latest) had a lot red lines with this errors:

[Client thread/ERROR] [modularui]: Window is not synced!
[Client thread/ERROR] [modularui]: Expected ModularGui screen on client, but got null

and also there was some more [modularui] errors with codechickencore in them or something similar.

I was able to reproduce some of these errors:
specifically, "Expected ModularGui screen on client, but got null" appears in log when i try quickly open and close any greg machine GUI, or any ModularUI one i think, and "Window is not synced!" appears when i try to close Ghost Circuit select window with [x], there is probably more errors with this mod, this is just what i found myself.

### Crash Report

Crash report says about Ticking memory connection with IndexOutOfBounds exception:
java.lang.IndexOutOfBoundsException: Index: 68, Size: 50

My guess that it's some memory leak issue, only happened to me after 2 hours of play, and before that, i opened ModularUI GUI's a lot of time, though sometimes with errors in minecraft log, as i stated above.

BetterCrashes screen after crash:
![2022-12-16_04 45 03](https://user-images.githubusercontent.com/115502326/208015892-b5776c6c-a887-49a5-aacd-17fd3e27f5a9.png)

Crash report itself:
[crash-2022-12-16_04.44.51-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10242429/crash-2022-12-16_04.44.51-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by FloatDoubling** [comment]
Here. It's not one from crash runtime, its more recent one, but it's still have tons of modularui issues, also ones such as 
[Client thread/ERROR] [modularui]: Expected ModularGui screen on client, but got codechicken.nei.recipe.GuiCraftingRecipe@2c2367b8

They all happens as i said when i interacted with ModularUiI GUI's

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10243141/fml-client-latest.log)

**Comment by miozune** [comment]
Fixed the log spam. Still I have no idea how client sent slot click packet from circuit configuration GUI...

**Comment by BritishCynic** [comment]
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.
