### ISSUE TITLE
Huge lag by requesting AE2 autocraft 

### ISSUE THREAD

**Issue by tankobuman** [GTNewHorizons/GT-New-Horizons-Modpack#11991]
### Your GTNH Discord Username

tnkB#4563

### Your Pack Version

2.2.7 + update AE2  from 122 to 127

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

No such huge lag (freeze) when I request AE2 autocrafing

### The Reality

![image](https://user-images.githubusercontent.com/90376144/207997871-a3165d16-5cb8-457c-88db-22e81fcb45fa.png)
Default 2.2.7 pack AE2 jar ( 1.7.10-rv3-beta-122-GTNH) has no such lag but updating AE2 newer jar (like 123~127, even 1.7.10-rv3-beta-122-GTNH-2-gd9d92c7 jar ) causes this lag. 

### Your Proposal

Please fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by sintken** [comment]
This is likely a known ae2 issue involving large amounts of crafting patterns (not processing patterns) especially with metadata. More information on what exactly youre trying to craft would be good.

**Comment by tankobuman** [comment]
This happens when I request wetware supercomputer( uv tier wetware) and assembler machine casing.  And disabling all crafting pattern by cutting network doesn`t help. 

I found it is happen when I enable their pattern using substitute and disabling them resolve this issue.

**Comment by asdflj** [comment]
don't use substitution and set pattern terminal substitution by the false

**Comment by Glease** [comment]
A CPU profiling result will help. See how to here: https://gtnh.miraheze.org/wiki/VisualVM#CPU_Profiling

**Comment by asdflj** [comment]
maybe we need revered [https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/204](url) this pr
@miozune

**Comment by tankobuman** [comment]
![スクリーンショット 2022-12-18 213629](https://user-images.githubusercontent.com/90376144/208298762-2c04457b-e333-4ef4-a577-bd76353ebde7.png)
![スクリーンショット 2022-12-18 212142](https://user-images.githubusercontent.com/90376144/208298281-710e5a45-6024-4305-a115-5d504fcdce09.png)
![スクリーンショット 2022-12-18 212250](https://user-images.githubusercontent.com/90376144/208298289-3de39aa7-0c40-47fa-854b-14650b42fbf5.png)

This lag almost always end up with freezing game completely.

**Comment by miozune** [comment]
Reverted the default. But it still doesn't solve the underlying the issue.

**Comment by asdflj** [comment]
you can try to use ae2 116 version and fc 1.0.37
this is a last normal version

**Comment by tankobuman** [comment]
Apparently new jar (appliedenergistics2-1.7.10-rv3-beta-126-GTNH-2-g2516bc1) works fine .  No lag happens .
