### ISSUE TITLE
Buff Utupu-Tanuri

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12008]
### Your GTNH Discord Username

Tommeh#9804

### Your Pack Version

2.2.3

### Your Proposal

Make the Utupu-Tanuri anywhere between 8 to 32 times faster when in dehydrator mode.

### Your Goal

Unlike many other multies this multi is barely faster than singleblock dehydrators on the same voltage, making it utterly useless for this purpose.
And to top this off the structure requirements(which forget to mention the coils btw) only really allow for 2 output hatches, limiting it so badly that currently one is likely better off using singleblocks instead.

### Your Vision

For the sake of performance and scalability multies are generally much faster than their singleblock counterparts, but this multi seems to entirely miss its purpose there, making it a rather useless multi when it comes to its dehydrator mode.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Tommeh1** [comment]
Any update on this?
As currently dehydrators are quite problematic, the singleblocks only go up to ZPM and make you deal with a ton of cells, the PA doesn't work with them and the Utupu cannot fit enough output hatches and is rather slow.

**Comment by Steelux8** [comment]
I'll look at it this week.

**Comment by PhoenixtheII** [comment]
Can confirm this, dehydrator mode is useless as is right now. 

ME busses don't work either on it. It'll just void your stuff.

**Comment by Tommeh1** [comment]
> 

The ME busses work fine for me.

**Comment by Tommeh1** [comment]
> Can confirm this, dehydrator mode is useless as is right now.
> 
> ME busses don't work either on it. It'll just void your stuff.

The ME busses work fine on it for me.
