### ISSUE TITLE
Matter Fabrication CPU not craftable

### ISSUE THREAD

**Issue by Godelboard** [GTNewHorizons/GT-New-Horizons-Modpack#12001]
### Your GTNH Discord Username

Godel#6372

### Your Pack Version

2.2.7.0

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Attempted to craft Matter Fabrication CPU using wetware tier UV circuits.

### The Reality

The recipe only lists "Any UV Circuit" and the Matter Fabrication CPU is uncraftable; it does not accept other tiers of UV circuits.

![image](https://user-images.githubusercontent.com/6662420/208170693-cd7bf8ff-6499-4c13-b11b-98e0f198af08.png)

![image](https://user-images.githubusercontent.com/6662420/208170738-683bcab7-f82f-4608-ab74-7944c51bc6dc.png)

### Your Proposal

recipe to work correctly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
```JAVA
                // Matter Fabricator CPU
                RecipeUtils.addShapedGregtechRecipe(
                        CI.getPlate(8, 1),
                        GT_OreDictUnificator.get(OrePrefixes.circuit.get(Materials.Superconductor), 1L),
                        CI.getPlate(8, 1),
                        GT_OreDictUnificator.get(OrePrefixes.cableGt04.get(Materials.NaquadahAlloy), 1L),
                        CI.machineCasing_UV,
                        GT_OreDictUnificator.get(OrePrefixes.cableGt04.get(Materials.NaquadahAlloy), 1L),
                        CI.getPlate(8, 1),
                        GT_OreDictUnificator.get(OrePrefixes.circuit.get(Materials.Superconductor), 1L),
                        CI.getPlate(8, 1),
                        RECIPE_IndustrialMatterFabController);
```

**Comment by Dream-Master** [comment]
This is the recipe so it is oredicted but not shown up as oredicted

**Comment by chochem** [comment]
I guess that is because gt++ does not directly use the gt function but has a translation layer
