### ISSUE TITLE
Crash when shift+left click when craft on Tinker's Construct Crafting Station

### ISSUE THREAD

**Issue by DancingSnow0517** [GTNewHorizons/GT-New-Horizons-Modpack#12007]
### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Vanilla Forge

### Your Actions

NEI shift+right click 

### Crash Report

https://paste.ubuntu.com/p/chxfkrPRf7/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
Is that a typo? Otherwise you should update. not much point trying to get help for a 5 year old version.

**Comment by miozune** [comment]
> gregtech-1.7.10-5.09.41.61.jar

it's actually 2.2.0.0

**Comment by DancingSnow0517** [comment]
> Is that a typo? Otherwise you should update. not much point trying to get help for a 5 year old version.

A typo, The correct version is 2.2.0.0, and There are drawers beside Tinker's Construct Crafting Station

**Comment by tager1199** [comment]
I also have this issue, happens whenever the crafting station has access to a drawer's inventory, if a chest is also next to it and it's accessing the chest's inventory instead the game does not crash. 
Game Version 2.2.0.0
Single Player Game
Discord Username: tinyman1199#6969
My Crash report: https://paste.ubuntu.com/p/Mwwfj2tsph/
