### ISSUE TITLE
Replace Galacticraft Machines with GT Machines

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#12013]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

2.2.7

### Your Proposal

Please consider replacing Galacticraft machines with a GT machine...Galacticraft machines make the entire world sad.

### Your Goal

Working with the Galacticraft machines always make me sad. Issues with everything dealing with them. Always people asking about them in Discord. Custom machines to replace them please? :)

### Your Vision

Would help unify the GT experience.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Or recode gc machines be gt machines accept eu

**Comment by shawnbyday** [comment]
I'm fine with having to refill oxygen in space with recent change...just don't want to use galacitcraft machines because they are aweful. Rather craft a new GT machine for each planet with a solar panel on it or something that I can just leave at each site. If we can fix galacticraft machines to interact with GT pipes and not be so "sided" that would also work.
