### ISSUE TITLE
Many Botania Quests Complete Upon Completing One

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#12012]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

2.2.7

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

I crafted the Daybloom for quest ID: 3254 and expected only that quest to complete.

### The Reality

The following quests completed when I crafted the Daybloom:

- Dark Energy 3256
- Violence is Blue 33260
- Anti-Magnetism 3259
- Roses Are Blood-Red 3261

### Your Proposal

Fix so only proper quest completes and not all of them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
already fixed that :)
