### ISSUE TITLE
Add a New Mica Ore Vein in T4+

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#12029]
### Your Pack Version

2.2.7

### Your Proposal

Add a new mica ore vein in T4+.
It should have more mica ores and be denser. For example:
Primary: Mica ore
Secondary: Mica ore
Between: Asbestos ore
Sporadic: Mica ore
Height: 20-40
Weight: 30 or 40

### Your Goal

To make coils easier.
Sometimes when I want to make some coils to upgrade my Mega EBF, it takes me a huge amount of time to find and mine some mica ore vein in the overworld. The quantity of mica in a mica ore vein is too small.

### Your Vision

Make it easier to make coils in later tiers.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Artificial Mica line (Fluorophlogopite) exists
