### ISSUE TITLE
Solar boilers are having extra slots

### ISSUE THREAD

**Issue by MCTian-mi** [GTNewHorizons/GT-New-Horizons-Modpack#12020]
### Your GTNH Discord Username

Tian_mi

### Your Pack Version

2.2.7.0

### Your Server

SP

### Type of Server

None

### Your Expectation

these two slots shouldn't exist
![image](https://user-images.githubusercontent.com/35869948/208300929-8179cf07-64bb-45c7-890e-e87b29859b35.png)

### The Reality

they exist

### Your Proposal

remove these two slots

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
It's the behavior from old GUI. If we accept deleting some items stored in someone's boiler, I can remove them.

**Comment by Glease** [comment]
Maybe make it not accept new item, but can be taken out.
