### ISSUE TITLE
EIG bug with Glieonia

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#12021]
### Your GTNH Discord Username

ImpossibleVT#3997

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Set up an EIG with sweed and glieonia and they work fine.

### The Reality

It has enough water and power but stops producing glowstone and specifically only glowstone after relog/restart. It works until next restart if I set it up again by pulling the seeds out and putting back in.

### Your Proposal

Glieonia normally acts like both a flower and a crop, planted on dirt/grass and not farmland. This could maybe cause it? Idk why else only glieonia would be affected. (sweed in the same EIG as glieonia makes sugar just fine, redlon and lazullia in another EIG also works perfectly)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
@kuba6000 is this fixed?

**Comment by kuba6000** [comment]
> @kuba6000 is this fixed?

no
