### ISSUE TITLE
Netty exception flood followed by hard exit

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12034]
### Your GTNH Discord Username

Tommeh#9804

### Your Pack Version

2.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Actions

At some point a player that often complains about interacting with everything sometimes taking up to literal minutes(while movement etc still appeared smooth) while the server experiences mere lagspikes of a few sec at worst decided to relog.
Usually his problems go away after some time for no apparent reason, but this time when he logged off to try relogging to see if it got any better netty threw a bunch of exceptions at exactly [06:23:53] and the server exited without the normal log catching any errors and without crash report, only the fml-server log caught it:
`[06:23:53] [Netty IO #12/ERROR] [FML/]: NetworkDispatcher exception
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[?:1.8.0_282]
	at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[?:1.8.0_282]
	at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[?:1.8.0_282]
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:503) ~[?:1.8.0_282]
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:249) ~[NioSocketChannel.class:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:680) [AbstractChannel$AbstractUnsafe.class:?]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:266) [AbstractNioChannel$AbstractNioUnsafe.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:488) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]`
	

### Crash Report

[Uploading fml-server-3.log…]()

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
crashreport link isn't working. Also from the things you tell us, it is likely his connection doing funny stuff. That kind of issues would be known given how painful it is, many people would have reported it already.

But just in case, send the crashlog again, so we can rule any pack issue out.

**Comment by mitchej123** [comment]
`Broken Pipe` is generally a network error

**Comment by Tommeh1** [comment]
> crashreport link isn't working. Also from the things you tell us, it is likely his connection doing funny stuff. That kind of issues would be known given how painful it is, many people would have reported it already.
> 
> But just in case, send the crashlog again, so we can rule any pack issue out.

[fml-server-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10260968/fml-server-3.log)

The problem is that if it is on his side that it's gonna be hard to find the cause of what makes things quite unplayable to him, his ping is stable, his internet speed is more than plenty and he has no packet loss.

**Comment by mitchej123** [comment]
Lol unrelated, I hope we've fixed the other spam
```
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[06:23:50] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.util.NoSuchElementException
[06:23:50] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.collect.Iterators$5.next(Iterators.java:550)
[06:23:50] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_CropHarvestor.onPostTick(GT_MetaTileEntity_CropHarvestor.java:268)
```

**Comment by Tommeh1** [comment]
> Lol unrelated, I hope we've fixed the other spam
> 
> ```
> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
> java.util.NoSuchElementException
> 	at com.google.common.collect.Iterators$5.next(Iterators.java:550)
> 	at gtPlusPlus.xmod.gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_CropHarvestor.onPostTick(GT_MetaTileEntity_CropHarvestor.java:268)
> ```

I'm well aware, i had to cut out like 200k lines of that to be able to even upload the log at all xD

**Comment by Tommeh1** [comment]
> > The problem is that if it is on his side that it's gonna be hard to find the cause of what makes things quite unplayable to him, his ping is stable, his internet speed is more than plenty and he has no packet loss.
> 
> Make him disable any antivirus/firewall on his computer. I recently helped someone on discord because after a while they'd lose connection to server then it was impossible to relog because it was timing out, despite the ping being fine and other people on it being fine. It was windows' firewall.

Alright, i'll tell him that, but that still leaves the server crash though.

**Comment by mitchej123** [comment]
> that still leaves the server crash though.

I didn't see any crash in the server.  Was there one that got missed?  Or did it just fall over.

**Comment by Tommeh1** [comment]
> > that still leaves the server crash though.
> 
> I didn't see any crash in the server log. Was there one that got missed? Or did it just fall over.

After that error the server exited, nothing in the normal log, no crash report, nothing other than that netty error.

**Comment by mitchej123** [comment]
Odd.  Hard to diagnose without any relevant logs.  Was there any other files dropped into the server dir, or log dir? hs_pid_xxx.log or something similar?  Plausible the OOM killer killed the server....

**Comment by Tommeh1** [comment]
There is nothing else, but the server normally comes nowhere close to its limit of 32GB RAM and the OOM killer from our control panel is disabled.

**Comment by boubou19** [comment]
looks like hard corrupted network packet transmission killed it then. Which is concerning because that means it's possible to kill a server with malfromed data

**Comment by bamik69** [comment]
Also caught this problem. The study of the issue revealed the following dependencies. When the output buffer is emptied in any way, metadata errors are spammed into the console and into the log. After a while, the log file overflows and the server crashes. If you do not take all the items, then there is no problem.
![image](https://user-images.githubusercontent.com/22926983/215354350-176524be-3f51-47c8-a71f-c0e33c569222.png)

**Comment by bamik69** [comment]
Tested on Crop Harvester 2K and 8K with different plants.

**Comment by Tommeh1** [comment]
That's an unrelated issue fixed in newer versions.

**Comment by bamik69** [comment]
Maybe then close the topic? With explanations.

**Comment by Tommeh1** [comment]
> Maybe then close the topic? With explanations.

I was talking about the issue you stated, not mine.
