### ISSUE TITLE
GT++ outputs an autoconverting thorium 232

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#12038]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.2.0.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

1: Oredicted items should not randomly switch between versions
2: Machines should not output items on the autoreplace list

### The Reality

Since the update the GT++ chemical plant has switched from producing the BartWorks Thorium-232 to outputting the GT++ version (using the boric acid recipe) This item then autoconverts back to the BartWorks version.

This also means that it's really annoying to update AE2 crafting for it since it changes when you pick it up and makes it very annoying to set up the appropriate crafting recipes with the new version.

### Your Proposal

The recipe should output the BartWorks version again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Steelux8** [comment]
It's either going to autoconvert to the Bartworks version or the GT++ version. Is there a specific problem if it's the GT++ version and not the BW version?
