### ISSUE TITLE
Client crashes upon server conection

### ISSUE THREAD

**Issue by Excavon** [GTNewHorizons/GT-New-Horizons-Modpack#12039]
### Your GTNH Discord Username

Excavon#5968

### Your Pack Version

2.2.3.0

### Your Server

Private server (ubuntu, on LAN)

### Type of Server

Vanilla Forge

### Your Actions

Trying to connect to a private server.

### Crash Report

client crash report: https://paste.ubuntu.com/p/PG6tBWQMSr/

server log said the following:

Excavon lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[02:36:04] [Server thread/INFO]: Excavon left the game

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ethryan** [comment]
Use pastebin please.

**Comment by Excavon** [comment]
Idk, that's what minecraft gave me, but here's a pastebin link.

https://pastebin.com/102PYwCd

**Comment by miozune** [comment]
BetterCrashes uses ubuntu pastebin to upload log. Pastebin requires API key to upload, while ubuntu pastebin does not.

**Comment by petrukhnov** [comment]
I have experienced similar problem with LAN server. Client hangs when somebody joins the server (maybe every 10th time).
Server OS: Debian
Client OS: Manjaro, EndevourOs
jre: openjdk-8.0.352, amazon-coretto-8.0.352
Others on the server play without problem.
