### ISSUE TITLE
BlockRenderer Crash on Preview of PCB Factory

### ISSUE THREAD

**Issue by cinch** [GTNewHorizons/GT-New-Horizons-Modpack#12033]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.2.7

### Your Server

private

### Type of Server

Vanilla Forge

### Your Actions

open the preview, eg: 
![image](https://user-images.githubusercontent.com/61357/208454246-230dde0f-2cb4-45f1-82b8-6043b03dc807.png)

pan around, zoom (maybe switch tier to 3) results in a repeatable crash

newer mods than 2.2.7:
blockrenderer6343-1.7.10-1.0.0-RC5.jar
gregtech-1.7.10-5.09.41.177.jar

### Crash Report

https://pastebin.com/raw/XMQW9T4q

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Godelboard** [comment]
I'm also getting crashes with this specific multiblock preview. Mine consistently happened when I would right click a block in the preview (supposed to show you what valid options are for the block)
