### ISSUE TITLE
EnderIO Enchanter Odd Text Behavior

### ISSUE THREAD

**Issue by DarkAmbientNoise** [GTNewHorizons/GT-New-Horizons-Modpack#12030]
### Your GTNH Discord Username

Not on the Discord

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

To have a normal EnderIO Enchanter NEI recipe screen.

### The Reality

Hovering over the EnderIO Enchanter NEI recipes while holding the shift key, give some odd results.

![2022-12-18_23 24 28](https://user-images.githubusercontent.com/12950685/208354291-e97c6490-c0c8-48da-af81-d6496dd7f894.png)

Unlikely, but it could have also caused a crash, I don't get crash reports, just hs_err_pid#### files.

### Your Proposal

That someone looks at it at some point if they have the time, it's not a big deal.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
It's called NEI btw

**Comment by DarkAmbientNoise** [comment]
Ah, yes. Thank you for that faithful correction. I've spent the majority of my Minecraft experience in 1.12.2 before playing this modpack. It's something I've struggled with for years for the packs that have it. Didn't help that I wrote that report late at night either.
