### ISSUE TITLE
Remove Circuit 0 in Component Assline

### ISSUE THREAD

**Issue by JustAlkaid** [GTNewHorizons/GT-New-Horizons-Modpack#12031]
### Your Pack Version

2.2.7

### Your Proposal

All Electric Motor after LuV need a circuit 0 to craft in Component Assline. Remove it plz.

### Your Goal

We have removed all the circuit 0 in other machines.

### Your Vision

Make crafting better.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Fixed in dev
![2022-12-19_21 55 07](https://user-images.githubusercontent.com/40035906/208431022-c9a20d5f-897b-4fdd-a6ea-2cf174cc92b2.png)
