### ISSUE TITLE
Garnierite Ore grinds to obtain crushed RoastedNickel

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#12040]
### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Garnierite grinds to get crushed Garnierite
SAG Mill：
![image](https://user-images.githubusercontent.com/62875887/208594111-6e3379d7-1c36-419d-b15d-8bedb3c564d8.png)

### The Reality

![image](https://user-images.githubusercontent.com/62875887/208594060-46c23c2d-0917-4e6e-b8a2-0a3e538c19e3.png)

### Your Proposal

Garnierite grinds to get crushed Garnierite

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
sag mil has his own config so it must be added or chamged manual

**Comment by miozune** [comment]
related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11632

**Comment by chochem** [comment]
I guess one ticket is enough.
