### ISSUE TITLE
PCB Factory Configuration Not Consistent with Behavior

### ISSUE THREAD

**Issue by Godelboard** [GTNewHorizons/GT-New-Horizons-Modpack#12052]
### Your GTNH Discord Username

Godel#6372

### Your Pack Version

2.2.7.0

### Your Server

private server

### Type of Server

None

### Your Expectation

For PCB Factory configuration to work as expected.

MB Mod author is aware but I don't see an actual issue ticket open for this MB.
https://discord.com/channels/181078474394566657/234936569360809996/1053926819411279883

### The Reality

List of issues I've noticed myself:
- Bio upgrade is applied when it's unselected. Selecting bio upgrade makes bio upgrade required recipes stop working.
- Cooler tower tier 1 upgrade _kind of_ works but hatch won't accept distilled water as a valid fluid that's allowed to go in it. I tried a variety of ways to insert the fluid and none of them worked (me fluid export bus, conduit, transvector interface, fluid translocator, SFM). The only way I could get distilled water into the hatch was manually dropping it in via cell.
    - The kind of works is because again I was getting inconsistent behavior. Was testing with the wetware boards on ZPM power.
- Sometimes it would work and be 13s recipe. Other times it would be 27s resource with OC1 upgrade on.
- Someone said coolant is supposed to go into the bottom of the tower but I also couldn't get this to work. I still had the issue of it not accepting distilled water either so either it's not a valid hatch for that position (which checks out, because it doesn't match texture with the rest of the multiblock) or it has same problem as above.
- Not able to test t2 OC upgrade as we're not at that stage yet.

### Your Proposal

- Make the configuration settings the player sets be consistent with what the multiblock actual does.
- Allow appropriate cooling fluid to be inserted based on cooling upgrade specified.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueWeabo** [comment]
Coolant Hatch goes on the Liquid Cooler and not the main multiblock

BioUpgrade Shenanigans might have been fixed in dev (pretty sure they have been)

The Coolant Hatch thing was fixed after 2.2.7 as I hadn't realize it

I would need more information about the OC1 Upgrade not OCing correctly

**Comment by YTXilo** [comment]
The coolant hatch also has to be in the middle of the coolant tower, at least from my knowledge it does

The latest gt5u has a lot of fixes for the PCB factory, if not auto place is usually required for placing the hatch

The oc thing is quite odd, should be fixed in the newest gt5u if not already, I personally have not had issues with oc on one of the most recent gt5u

**Comment by Godelboard** [comment]
So a couple things about the coolant tower then:
- The MB tooltip says the tower requires 21 reinforced photolithographic casings. The tower has exactly 21 blocks where these go so based on that I would assume need all 21 and there isn't room for a hatch. Updating the tooltip to list 20 + input hatch would be good.
- Also, said blocks are marked as hintblock 2, but the holograph projector doesn't tell you anything about what hintblock 2 is supposed to be. Updating the hologram projector hintdot 2 description would be helpful for this as well.

**Comment by YTXilo** [comment]
Well the hologram projector is showing the main structure, as it has never been used like this before so, but if anything yeah it should have 20 casings, and if it doesn't already I believe it already has it mentioned that in newer versions that the input hatch has to be on the center of the cooling tower, but more info should be supplied imo
