### ISSUE TITLE
NEI show's different required recipe amounts (on Pure Tear)

### ISSUE THREAD

**Issue by cinch** [GTNewHorizons/GT-New-Horizons-Modpack#12058]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.2.7

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

lookup the crafting recipe for pure tear

### The Reality

![image](https://user-images.githubusercontent.com/61357/208913005-fa287085-ed08-494a-a133-4ed0ced7a75d.png)

16x ichorium

click a couple of times again on Pure Tear in NEI to reload the recipe (or wait for the animation, where it cycles between similar items) until it changes: 

![image](https://user-images.githubusercontent.com/61357/208912649-0d0cbad6-88c1-45ab-81c2-2dd4357b03ef.png)
![image](https://user-images.githubusercontent.com/61357/208912673-3ccabbe9-604c-43f6-aca7-41de0e224529.png)

bonus points for looking up the usage of ichorium: 

![image](https://user-images.githubusercontent.com/61357/208912754-b951c25d-d597-4bfe-abcd-8038f2b8e7cf.png)

### Your Proposal

fix please

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Related: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11781

**Comment by cinch** [comment]
some other oddities: Cowl of the Abyssal Depths helmet won't infuse with raw calamari, but it will take raw fish.

Boots of the Horizonal Shield: NEI doesn't like the grass block:
![image](https://user-images.githubusercontent.com/61357/209205729-b07d12d0-438d-4af5-9eab-3aafc00402a4.png)
the infusion won't start and the grass block has a strange gray color: 
![image](https://user-images.githubusercontent.com/61357/209205928-2bbdde1b-852c-4d8f-a156-5c67325784f6.png)
