### ISSUE TITLE
Dissolution Tank recipes cannot be ? clicked into fluid processing pattern terminals

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#12060]
### Your Pack Version

2.2.7

### Your Proposal

to be able to encode recipes from ? in nei

### Your Goal

you cannot simply drag a fluid from nei to encode the pattern manually either. you have to do a workaround to bookmark an ae2fc fluid packet variant of the fluid to encode it manually, thus making it quite jank to encode things from this

### Your Vision

make bastline less painful :(

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by shekurika** [comment]
same for the digester in 2.2.0
