### ISSUE TITLE
Conflict with Invtweaker and GT

### ISSUE THREAD

**Issue by Blubstr** [GTNewHorizons/GT-New-Horizons-Modpack#12061]
### Your GTNH Discord Username

blub_me#2568

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Placed bronze solar boiler, then went to open UI, as Invtweaker replaced my empty hand with a bronze pipe.

### Crash Report

https://paste.ubuntu.com/p/CzyXrPBMDG/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
The mod is not compatible with replacement of gt items.  

As for the crash will need to look into that or see if it's already been fixed in the latest version
