### ISSUE TITLE
High server CPU usage by net.minecraftforge.event.ForgeEventFactory.canEntitySpawn ()

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12062]
### Your GTNH Discord Username

Tommeh#9804

### Your Pack Version

2.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Whenever there are spawners active within range of what i can only assume to be the GregTech monster repellator its CPU usage goes up considerably(to 18.1% of the entire server thread in this case): 
![image](https://user-images.githubusercontent.com/39203645/208990832-9dda5e7c-2d2d-4f9c-9e49-b9fe07f07f98.png)
[Snapshots.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10280690/Snapshots.zip)

### Your Proposal

Optimize the monster repellator in the presence of spawners.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
This issue continues to get worse, now taking up about 68% of the entire server thread, we've added FastCraft to fix other severe performance issues, but it didn't improve this one at all 
![image](https://user-images.githubusercontent.com/39203645/210840582-fae4ff3a-4dfa-4aad-9dda-7d96aee9b3ae.png)

**Comment by mitchej123** [comment]
Also, can you please expand the denyMobSpawn_CheckSpawn.Invoke()?

**Comment by Tommeh1** [comment]
> How many GT Mob Repellers do you have?

Roughly a dozen


> Also, can you please expand the denyMobSpawn_CheckSpawn.Invoke()?

![image](https://user-images.githubusercontent.com/39203645/210859537-dae4eeb0-9c90-4d0d-afb5-d31c46ea39a2.png)

**Comment by mitchej123** [comment]
Are they in chunks that are chunkloaded?

**Comment by Tommeh1** [comment]
> Are they in chunks that are chunkloaded?

Yes
