### ISSUE TITLE
Warp Sanitation Prevention Time Increase

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#12063]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

2.2.7

### Your Proposal

Is there any way to lengthen the duration of the warp warding/sanitation methods or allow them to stack based on how many you apply? Higher tier sanitation methods?

### Your Goal

Make managing warp less disrupting. Not eliminate it entirely but allow a person to prepare for a certain length of time without warp vs running back to spa all the time.

### Your Vision

Make managing warp less disrupting. Not eliminate it entirely but allow a person to prepare for a certain length of time without warp vs running back to spa all the time.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by shekurika** [comment]
you can just fill a drum with spa water and carry it around with you and place the fluid with a bucket when the timer runs out
