### ISSUE TITLE
nuclear control information panel extenders break graphically 100% of the time on dimension change until relog

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#12072]
### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

when i return to my home dimension of the personal world, that nuclear control panels look normal
![image](https://user-images.githubusercontent.com/13358034/209415295-93e28212-c2a4-40c9-9728-c6b9ad17975b.png)

### The Reality

they look like this with the main block being normal
![image](https://user-images.githubusercontent.com/13358034/209415366-0292096f-2aca-4872-a4f0-870afa75f85f.png)

### Your Proposal

that they dont break graphically on dimension change.

note: this does NOT happen if you log into a dimension without panels, and then travel to the dimension containing them. but will happen every subsequent travel after that

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GionaCantarutti** [comment]
This seems to still be an issue
