### ISSUE TITLE
Infernal blast furnance from witching gadgets not forming

### ISSUE THREAD

**Issue by maslanemaslo** [GTNewHorizons/GT-New-Horizons-Modpack#12079]
### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

![image](https://user-images.githubusercontent.com/121361112/209451026-0eb8b70a-4910-4f47-9a1d-1d542c67d338.png)
![image](https://user-images.githubusercontent.com/121361112/209451076-1b7072f8-694e-4093-ac9e-2104637288f9.png)
![image](https://user-images.githubusercontent.com/121361112/209451080-e608d183-a959-4e89-971e-2c72514f9355.png)
While testing machines from thaumcraft addons i tried to form infernal blast furnance as per thamonomicon instructions, layer by layer screenshots included.

### The Reality

Upon trying to form the multiblock with gamemode silverwood scepter that has 150 of every vis (so its not the matter of insufficient vis capacity), nothing happens.

### Your Proposal

I suspect it has sth to do with the fact that the infernal brick stairs show up as sandy brick stairs in the bottom right.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Impos913** [comment]
![2022-12-25_01 20 57](https://user-images.githubusercontent.com/36479271/209452213-71fb5943-e0f4-4c1a-9df8-8c28c7b9662b.png)
You built it wrong

**Comment by maslanemaslo** [comment]
Cheers, it works. Thank you
