### ISSUE TITLE
No mortar wood pulp recipe

### ISSUE THREAD

**Issue by SirAnanas** [GTNewHorizons/GT-New-Horizons-Modpack#12070]
### Your GTNH Discord Username

Ananas#6642

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Tried to craft wood pulp using a mortar and any type of wood, should get 2 wood pulp from 1 wood.

### The Reality

The crafting recipe does not exist on the latest 2.2.7 version.

### Your Proposal

Implement the recipe again, as it is a progression-stopping bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment]
Works for me
![image](https://user-images.githubusercontent.com/39595617/209208414-0ad40fbe-b60a-4b7e-a993-6dfd95dd88f5.png)
I am 2.2.7 + jenkins

**Comment by SirAnanas** [comment]
i am dumb, i forgot to the scripts folder
