### ISSUE TITLE
Add parallel to electric implosion compressor

### ISSUE THREAD

**Issue by GDCloudstrike** [GTNewHorizons/GT-New-Horizons-Modpack#12071]
### Your GTNH Discord Username

GDCloud#2907

### Your Pack Version

2.2.7+

### Your Proposal

The electric implosion compressor should gain the ability to do parallel processing.

### Your Goal

The electric implosion compressor is dwarfed in speed by the density^2 because of the lack of parallel. For this reason, and the fact that iTNT can be easily mass produced, players at higher tiers tend to not use the electric implosion compressor as their main compression method. This is sad to see as the EIC is a much higher tier machine than the density^2 and should therefore at least be able to compete (or overtake) the density^2 speed wise. This could be achieved by adding parallelism to the EIC.

### Your Vision

EIC would be able to fulfill the compression needs of high tier players and compete with the density^2.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
Maybe it could accept different metal blocks in the middle which determine parallel. For example infinity, space time etc.
