### ISSUE TITLE
Fluid Storage Bus and ME Dual Interface

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#12073]
### Your GTNH Discord Username

ImpossibleVT#3997

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Expect the fluid storage bus on dual interface keep working after restart/relog.
![2022-12-24_05 38 49](https://user-images.githubusercontent.com/36479271/209418457-36fc75e5-9387-4c1c-9a15-8d9beadc0ac6.png)
storage bus and fluid storage bus connected to dual interface for subnet i/o

### The Reality

Fluid terminal on the subnet after relog to sp world:
![image](https://user-images.githubusercontent.com/36479271/209418497-f1b77fb5-ce75-4ec7-92b7-454f2d458d2d.png)
No issue with items.

Connection is fixed after breaking and placing the fluid storage bus back.
![image](https://user-images.githubusercontent.com/36479271/209418560-1e3f0c4a-f44d-4e4e-8767-37411dd44aae.png)

### Your Proposal

I have no idea what could be the issue, I have asked around a bit and someone said it was working fine for them so ¯\_(ツ)_/¯

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by cainiaojun** [comment]
Confirmed.
Version 2.2.7
