### ISSUE TITLE
Sapling to Plantball NEI inconsistency 

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#12075]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The NEI recipe entry for Saplings to be compressed into Plantballs via the Compressor currently shows 1 Sapling > 1 Plantball.

### The Reality

In reality, it consumes 8 Saplings to obtain 1 Plantball.

### Your Proposal

This is more than likely a bug with the NEI entry rather than an intended buff to plantballs, so NEI just needs correcting.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by OrderedSet86** [comment]
Also seems to happen with pyrolyse oven as well - should be 16 wood 
![image](https://user-images.githubusercontent.com/88752681/209454491-fbd398a9-2bfa-46f8-a3d0-b42f3fdc8573.png)

**Comment by Dream-Master** [comment]
seems to be only to Natura, TC, BoP wood
