### ISSUE TITLE
Disable maintenance still gives maintenance issues

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#12082]
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I went to GregTech folder, MachineStats.cfg, and set 
B:MultiBlockMachines.disableMaintenance_false=false

But once I build a multiblock it still has plenty of issues, whereas in past all those issues would be gone by default.
And it still seems to me I am getting maintenance issue in progress.

### The Reality

Maintenace issues with disabled config.

### Your Proposal

Check why this started to happen with new update. In 2.1.0.0 this didn't happen.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Elisis** [comment]
> I went to GregTech folder, MachineStats.cfg, and set
> B:MultiBlockMachines.disableMaintenance_false=false

That's because the config refers to _disabling_ maintenance. To no longer get maintenance issues you need to set it to true

**Comment by nikitinalexx** [comment]
If it was called "disableMaintenance" I would agree. But it is called "disableMaintenance_false". 
It is both disable and false in one sentence.

**Comment by boubou19** [comment]
disableMaintenance_false means it is by default false. GT does this for all its config values.

**Comment by nikitinalexx** [comment]
Yes, by default maintenance is not disabled. What do you suggest?
If you download the server from scratch and look into the config you will see this config value is TRUE. I change it to FALSE. Which of the steps I made is incorrect?

**Comment by nikitinalexx** [comment]
> disableMaintenance_false means it is by default false. GT does this for all its config values.


No, it doesn't mean it is false.
It means that "disabledMaintenance" is false. False disabled maintenance == enabled maintenance.

**Comment by Impos913** [comment]
It is set to false by default, change it to true if you want to disable maintenance

**Comment by nikitinalexx** [comment]
Do you want to set disableMaintenance to false? I say "TRUE". It means disableMaintenance=false. which means maintenance is Enabled.


Do you want to set disableMaintenance to false? I say "FALSE". It means disableMaintenance=true. which means maintenance is Disabled.


So "TRUE" means maintenance is Enabled. "FALSE" means maintenance is Disabled.

**Comment by nikitinalexx** [comment]
Do you see that config name already has double negation?
"disabled", "false", and then also config value, which is a third factor?
![image](https://user-images.githubusercontent.com/4941736/209470082-10ebae7a-1282-43cc-a69c-296c1742cd60.png)

**Comment by Impos913** [comment]
Change it to true and see for yourself

**Comment by nikitinalexx** [comment]
Okay, I will check. But it works, then I have a concern for variable now. Why would it contain double negation. Then it should either say "disableMaintenance". or "maintenance_false".

**Comment by chochem** [comment]
not a double negation, just mentions the default after the name

**Comment by Impos913** [comment]
The part after the underscore is for telling the default value of a config. You will realize that if you look at other GT configs

**Comment by Ethryan** [comment]
b:MultiBlockMachines.disableMaintenance_false=false

The _false is what its default value is, the =false is its config value.

**Comment by nikitinalexx** [comment]
Ah okay, that explains a lot. I've tested it, thank you.
