### ISSUE TITLE
Crash to desktop when going fullscreen

### ISSUE THREAD

**Issue by TheEpicGamer274** [GTNewHorizons/GT-New-Horizons-Modpack#12083]
### Your GTNH Discord Username

TheEpicGamer274#5293

### Your Pack Version

2.2.8

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Actions

When I full screen on 2.2.8 with optifine installed it just crashes the game abruptly, If I uninstall optifine its fine, but then I get a memory leak and can play for about 5 mins total. I have a amd gpu, 6650 xt, I have heard that it doesn't work nice with optifine, but without optifine I cannot play reliably, fullscreen worked fine in 2.2.8. 

### Crash Report

There is nothing in logs that shows anything significant, any help is appreciated!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
post the logs anyway. And do you have any details on the mem leak? Try removing craft presence
