### ISSUE TITLE
Charcoal and Coal Gas from Steam and Wood not present in 2.2.8

### ISSUE THREAD

**Issue by ah-OOG-ah** [GTNewHorizons/GT-New-Horizons-Modpack#12091]
### Your GTNH Discord Username

OmniSlaves#6732

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Charcoal line from wood and steam, working in 2.2.3, should still work.

### The Reality

Old charcoal line using the Steam + Logs recipe stopped running. After checking NEI, it seems that the Steam + logs recipe for the Pyrolyze oven doesn't exist anymore.

### Your Proposal

Re-add the wood + steam > charcoal + wood gas recipe for the pyro oven.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
oh nice another pyrolyze oven bug

**Comment by shekurika** [comment]
https://github.com/GTNewHorizons/GTplusplus/pull/459

this is the PR that removed the recipes I think
