### ISSUE TITLE
Game crashing due to ticking entity (minecraft bat)

### ISSUE THREAD

**Issue by IceyPhantom** [GTNewHorizons/GT-New-Horizons-Modpack#12096]
### Your GTNH Discord Username

Icephantom#0300

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

None

### Your Actions

Was just in my base, setting up an electrolysis setup and the game crashed

### Crash Report

https://paste.ubuntu.com/p/SG4vxjtzvG/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
Please provide a log paste on a public medium like pastebin for us to be able to investigate this issue.
