### ISSUE TITLE
Incorrect plank amount display in recipe

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#12090]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

![image](https://user-images.githubusercontent.com/39595617/209476563-e0d165ef-2e94-47a6-8191-479b8a48716a.png)
Expected this recipe to work

### The Reality

It works with 8 planks, not 1

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
maybe same issue with pyrolyse oven show up 1 log but normal are 16 logs ?

**Comment by chochem** [comment]
yea some of these are probably connected:

**Comment by YasenGaming24** [comment]
THe Better Barrel recipe also shows 1 plank but takes 8. The Chest recipe also sometimes shows 1 instead of 8, and the alternative recipe shows 1 plank and 1 log instead of 2 each.
