### ISSUE TITLE
Make Bifrost Block LuV tier glass

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#12095]
### Your GTNH Discord Username

ImpossibleVT#3997

### Your Pack Version

2.2.8

### Your Proposal

![image](https://user-images.githubusercontent.com/36479271/209485135-9f0684d6-8a8c-4587-bffe-4d3afa7c51f8.png)
Change bifrost glass to LuV tier and make it usable on multiblocks. 

![image](https://user-images.githubusercontent.com/36479271/209485172-bd60637f-3a35-462d-884f-7fa1fda56fb6.png)
![image](https://user-images.githubusercontent.com/36479271/209485195-37b55959-2110-4339-89be-5d5986a4f782.png)
It is an upgrade to alfglass which is IV tier glass.

Although alfglass and bifrost glass are obtainable at the same time, both gated by alfheim portal. Rod of the bifrost can be gated a bit further to balance.

### Your Goal

Managlass is EV, Alfglass is IV and for the sake of consistency Bifrost Block should be LuV tier.

### Your Vision

Borosilicate glasses are boring. I have been enjoying alfglass on my multis, it would be great to have more tiers of magic glass.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
Personally against it. The additional difficulty is not LuV in any sense. If anything, this should only be an alternative IV glass for decorative purposes.

**Comment by boubou19** [comment]
agreed. If they unlock the same tier they should be the same tier of glasses
