### ISSUE TITLE
Extend hologram time

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#12092]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.2.8

### Your Proposal

not all multiblocks support autoplacements, and hologram time i was too short to build it , so u have to place few blocks then go back to controller use hologram and repeat, I suggest extending time of hologram to like 10x that it is now

### Your Goal

its too tedious now

### Your Vision

this thing aint fun u know

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
You can configure the time to your liking in the config of structure lib.
