### ISSUE TITLE
Graphics are Blurry in Updating from 2.2.3 to 2.2.8

### ISSUE THREAD

**Issue by schneid3306** [GTNewHorizons/GT-New-Horizons-Modpack#12093]
### Your GTNH Discord Username

schneid3306#7813

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I updated from 2.2.3 to 2.2.8 and I expected the graphics/rendering to be basically the same. I updated by creating a new instance and moving the save folder over. This is not what happened. Something changed that is causing everything to be very blurry. I have attached screenshots in the "The Reality" section.

### The Reality

When I updated from 2.2.3 to 2.2.8 the graphics are very blurry. This is particularly noticeable with trees and with things further in the background. I changed no settings between the two and in both cases I am on a GTX 1060 6GB.

The screenshots that are attached are running at the same time on my computer and are not stitched together. These show 2.2.3 and 2.2.8 open at the same time, on the same machine, with the same world, with identical in game Video Settings. I wrote .3 and .8 on both, but 2.2.3 is on the left in the screenshots, and 2.2.8 is on the right.
![blurry01](https://user-images.githubusercontent.com/101597354/209483877-2d5fdd83-a0f8-427f-b8a7-f3e179bf4c82.png)
![blurry02](https://user-images.githubusercontent.com/101597354/209483826-39c44691-b9be-4e17-af19-21fb3b44bdb0.png)

I have tried the official GTNH Discord, another Discord, and Google, and have done everything that was suggested and everything I know. This includes updating drivers, deleting options.txt and restarting, resetting my GPU settings to default, confirming the game is using my GPU to render and not internal graphics, and removing texture packs, I also created a totally new 2.2.8 new instance and created a new game, and the same blurry issue immediately appeared on 2.2.8.

I have attached the [latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10300724/latest.log) for 2.2.8 and I do not see any reference to "card" outside of redstone and there is no "graphic" or "Graphic" in the log. When playing, the Task Manager shows the GPU Engine as my 1060, not Intel.

### Your Proposal

This is a last ditch attempt to find a fix, and an inquiry to see if others have a similar issue. I have no idea what my proposal is as I do not know what is causing this to happen.

Thanks for any help!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TimeConqueror** [comment]
It happens when some mods have non-squared textures, like 64x3 or smth like that

**Comment by croftyraider** [comment]
I have seen the same thing, though for me I would say it's the opposite - in 2.2.8 the distance blurring is gone and things are too sharp which make them look noisy.

I took two shots from the exact same location (I copied the world folder) from 2.2.7 and 2.2.8. If you look at the faces of leaf blocks you'll see that those that are farther away and off-angle are smoothed in 2.2.7 but not in 2.2.8

![227 2023-01-01_14 26 26](https://user-images.githubusercontent.com/7588838/210186796-df0b883f-d7e4-4c74-9011-86636ffff586.png)
![228 2023-01-01_14 43 26](https://user-images.githubusercontent.com/7588838/210186800-c2ffbd35-ab19-4765-93b9-7ecd53db3668.png)

**Comment by TimeConqueror** [comment]
Quick fix for now: open `GT-PlusPlus-1.7.10-1.7.156-pre.jar` as archive and delete file `assets/miscutils/textures/blocks/Blank.png`
