### ISSUE TITLE
Dump aspect command from gt++ not working properly

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#12099]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.2.8

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

write all aspects of all items.

### The Reality

the file never gets finished. (checked with several friends, same situation)
do not even have iron ingot in the file.

### Your Proposal

someone have a look at the code.
https://github.com/GTNewHorizons/GTplusplus/tree/80c790b8a7b2c61215d636b3ce14715580b2f5eb/src/main/java/gtPlusPlus/xmod/thaumcraft
should be here.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
probably just use the dump aspect feature in NEI tools menu. 

If we don't have a replacement, then gt++ one will likely get a fix eventually. But when a substitute do exist, a fix is unlikely, especially for a console command.

**Comment by miaowwwwww** [comment]
thank u, never noticed that nei can dump aspect lol

**Comment by Alastors** [comment]
Fixed
