### ISSUE TITLE
High Server CPU usage by BetterQuesting

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12107]
### Your Pack Version

2.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

For the few things BetterQuesting has to do it using about 6% of the server thread on an i9 9900K, with the CPU thread the server thread is on nearly maxed is quite excessive, even by taking a few items out of an ME system i managed to see the usage by the onInventoryChange method go up to 10%.
I can see this become quite problematic with more than 5 or 6 players.
[Snapshots.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10304558/Snapshots.zip)
![image](https://user-images.githubusercontent.com/39203645/209577572-39b4dce8-1608-469b-9665-63887052950f.png)

### Your Proposal

Optimize checks by BetterQuesting or move them to their own thread if possible.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Shibva** [comment]
This I belive is the GTNH pack, but modifed with the additon of spark for sever performance monotering purposes (smart move)

the best thing about that is that link can be shared and others can view it; if your comfortable id recomend posting it; theres a lot of valuable data that can be used for server fixes and whatnot; after all it IS more data-rich than minecraft's debuger by a long shot

**Comment by Shibva** [comment]
its basically a greatly improved version of MC's debugger, and debugs can be a great tool

**Comment by Tommeh1** [comment]
I find VisualVM to do the very same thing considerably better than Spark can.

**Comment by boubou19** [comment]
> This I belive is the GTNH pack, but modifed with the additon of spark for sever performance monotering purposes (smart move)
> 
> the best thing about that is that link can be shared and others can view it; if your comfortable id recomend posting it; theres a lot of valuable data that can be used for server fixes and whatnot; after all it IS more data-rich than minecraft's debuger by a long shot

Alwyas recommanding sparks is a bad thing to do. Spark is command based, which means if your server starts to stop responding, spark is as useful as a brick. It is good to allow other staff to checkout lag sources, and it is good when your server host lets you only manage your server through a panel, no ssh.

Now if you don't fall under those two exact usecases, warmroast or visualvm are much better, visualvm is the most complete tool.

**Comment by Tommeh1** [comment]
Although this provides an improvement it might be even better to let the client check if inventory changes match a quest first, and then send a request to the server to double check and verify if the client claims it has a match that would progress a quest.
