### ISSUE TITLE
Tinkers aluminum ore cannot be processed in GT

### ISSUE THREAD

**Issue by Rubijox** [GTNewHorizons/GT-New-Horizons-Modpack#12113]
### Your GTNH Discord Username

Rubijox#7659

### Your Pack Version

2.2.3

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

Macerate aluminum ore (1002/5)
Get Crushed aluminum ore x2

### The Reality

Macerate aluminum ore (1002/5)
Does not macerate, there is no recipe

### Your Proposal

Make the Aluminum ore equivalent to aluminum ore gravel

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
Tinker alu need a change anyways. Maybe we can think of a better material to avoid gt issues. tico alu was never made to becomes gt alu
