### ISSUE TITLE
BiZnCu3 mixer recipe bug

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#12115]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.2.8

### Your Server

zeta

### Type of Server

None

### Your Expectation

all recipe should have equal materials.

### The Reality

https://cdn.discordapp.com/attachments/521008249844269061/1057396434422480926/image.png
https://cdn.discordapp.com/attachments/521008249844269061/1057396434888044614/image.png

### Your Proposal

change BiZnCu3 mixer recipe 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
look like all the various steel dust recipes are wrong. well, I got some time today.

**Comment by chochem** [comment]
It seems that nobody can agree on what the rules are for nested chem formulas, so I am not gonna do anything for now and wait for clarification. (I thought it was just atom counting but that doesn't seem to be the case). No matter what the rule is though, there is a lot that is wrong. :(
