### ISSUE TITLE
Blacklist AE2FC drops from recycler

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#12114]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.2.8

### Your Proposal

I suggest putting drops from ae2fc in recycler blacklist(no scrap made from drops)

### Your Goal

It kills all other methods of making scrap items, it requires no investments at all, just some ae and water which is infinite

### Your Vision

Scrap shouldnt be that easy to set up

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2222
