### ISSUE TITLE
Adv Assline uses fluids infinitely, outputs extra items

### ISSUE THREAD

**Issue by sintken** [GTNewHorizons/GT-New-Horizons-Modpack#12119]
### Your GTNH Discord Username

sintken #1312

### Your Pack Version

2.2.8

### Your Server

sp

### Type of Server

None

### Your Expectation

Use adv assline to make shit

### The Reality

Adv assline consumes inputs properly, then continues consuming all liquid inputs until one runs out, then outputs two of the output item. Bug happens on the version of ggfab included in v2.2.8 (v0.0.9) as well as the updated v0.0.10 of ggfab (according to misi).

edit: issue only happens using stocking input busses. does not happen when using normal input busses.

### Your Proposal

dont eat infinite fluids. you could keep the doubled outputs tho, i wouldnt mind ;)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by sintken** [comment]
https://thumbs.gfycat.com/BothSphericalFishingcat-mobile.mp4

gif provided by misi (if youre confused about "infinitely eating fluid"

**Comment by sintken** [comment]
addl info requested by glee8e: after the "craft" has finished and it's in the "eat fluid until i run out" stage, WAILA displays idle but on: 
![image](https://user-images.githubusercontent.com/72178165/209754333-1b8bc338-3e65-4f22-99e6-2c02c202d5b8.png)

**Comment by Glease** [comment]
Forget to mention. https://github.com/GTNewHorizons/GigaGramFab/releases/tag/0.0.11 should be able to fix this.

**Comment by Glease** [comment]
@sintken does 0.0.11 fix your issue? If yes I'd close this ticket.

**Comment by Glease** [comment]
![image](https://user-images.githubusercontent.com/4586901/210706711-5364278e-294c-4138-8d8d-059365d641d4.png)
