### ISSUE TITLE
Backport of "Angry Bees" mechanic and Smoker [Forestry Request/Personal Refrence]

### ISSUE THREAD

**Issue by Shibva** [GTNewHorizons/GT-New-Horizons-Modpack#12112]
### Your GTNH Discord Username

same as this one (Shibva_)

### Your Pack Version

------

### Your Proposal

The implimenation of a feature from forestry in 12.2 that makes it where small swarms will attack you if you try to break a hive (natural or/and man-made) and the smoker used to allow players to harvest wild hives without being subjected to their wrath for a short time.

### Your Goal

Adds more to the feel of beekeeping and realism factor; I mean theres pollution and many other things, that have some risk when doing it, but not bees (the ones that inflict effects dont count in this case - _-)

"Bees deserve the right to defend themselves too ya know"

### Your Vision

it would be more of an extra step towards beekeeping, and some bees could be naturally aggressive (making bee gear a must). Here I will list what I think should be added and I plan to try and contribute part of this but I might need some help 

- backport the bees attacking mechanic; code exists in 12.2 so I can use that as a base reference
- backport the smoker along with the neutralization mechanic to allow for harvesting hives
- (optional) Make higher-end bee scoops have the ability to smoke a hive (it's mechanical; what's to say you can't build one in it?) serves as the 2 tools needed for collecting wild specimens in one
- (optional) Thaumaturgic Smoker: a "Lamp of Cinders" modified into a smoker that uses aer and/ignis vis from a wand to fuel it (no passive drain or minuscule)

New mechanics/functions:
-The smoker will be acquirable somewhere between mid-to-late stone age, the fundamental difference is that the smoker, unlike in 12.2, will require fuel to burn in order to operate. It will take the fuel and burn for a time before it goes out [methods to prevent it not ticking in storage blocks would be nice but might impact performance] Smokers' burn time will drop quicker when being used and will use fuel up passively. **NO POLLUTION** 

-Smoking: like in 12.2 to avoid the wrath of the bee's sting you must smoke a hive to calm them down like you would in reality. I plan on having the smoker work like in 12.2 but might use something similar to an age countdown with animal mobs. Extra: using a smoker on entities (including players) in close range will blind them for 2-3 seconds with blindness II, useful for escaping.

Final Note: I'm aware this is a bit large, but this is also **for me to keep track of my idea as I attempt to work on it;** again I may need a hard to reach the end goal but overall am willing to do this. Any support is welcome ^w^

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by BritishCynic** [comment]
Closing as this is little more than a personal wishlist. If you make a PR for this you can still reference this ticket.
