### ISSUE TITLE
IsaMill doesn't check its state before damaging players

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12117]
### Your Pack Version

2.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

When the IsaMill is off or incomplete i expect it to not damage players in front of its controller block.

### The Reality

Before i even had the front build entirely, that thing, which comes with no warning whatsoever killed me.

### Your Proposal

Make the IsaMill behave like most other multies and not damage the player at all or make it check if it's running before doing so.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Furthermore it appears to entirely bypass armor.

**Comment by Tommeh1** [comment]
Additionally the milling balls it requires cannot be exported by ME unless you use the oredict name, but then you still encounter a problem where ME is unable to craft them on demand and only exports them once you order them manually.

**Comment by Dream-Master** [comment]
IsaMill is not done so far ik. Maybe its better to disable it until it works 100%

**Comment by Tommeh1** [comment]
It's the best way we've got to get rhenium currently, it's usable if the recipe you want works already(it doesn't want to process pentlandite ore) given that you're willing to jump through a decent few hoops to get it working.

**Comment by cainiaojun** [comment]
IsaMill has been useful so far. Although it is not completed, the function it provides is convenient.
The recipe of pineoil outputs tiny dusts. It would be better if there is a recipe outputs dusts instead of tiny dusts.
