### ISSUE TITLE
ME output hatch outputs very little fluid into ME system

### ISSUE THREAD

**Issue by Miisi** [GTNewHorizons/GT-New-Horizons-Modpack#12121]
### Your GTNH Discord Username

Misi#3673

### Your Pack Version

2.2.7 with several mods updated (including GT5u which is where the hatch comes from)

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

use the ME output hatch for crafting

### The Reality

not usable at all considering its speed
![image](https://user-images.githubusercontent.com/46682682/209777958-cce1eb77-8832-4d56-8f10-a6dd5c007a9d.png)
hatch filled with fluid 
![OWziGtbmrc](https://user-images.githubusercontent.com/46682682/209777011-6738e1e5-925e-4b8b-b740-ccd82d94253e.gif)
have tried on both a subnet and a large network

would bring this up in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11783 but it was closed as completed (and the issue author is probably referring to the second delay to input into the system, same as ME output bus)

### Your Proposal

fix/buff its speed

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1578
