### ISSUE TITLE
EV Gas Turbine does not show up on the gas turbine fuel tab.

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#12120]
### Your GTNH Discord Username

LazyFlesh#4533

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Ev gas turbine show up with the others on the side of the gas turbine fuel NEI tab

### The Reality

It's not there. 
![image](https://user-images.githubusercontent.com/40587985/209762828-72cf879d-30d4-4eac-ad0d-befca0e84e6d.png)

### Your Proposal

Add it there.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@miozune any idea how to add that ?
