### ISSUE TITLE
crashing during loading up of my SP world

### ISSUE THREAD

**Issue by croftyraider** [GTNewHorizons/GT-New-Horizons-Modpack#12129]
### Your GTNH Discord Username

croftyraider

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Just starting my world, the game began to render what I could see in my base then boom.

### Crash Report

[crash-2022-12-28_16.01.20-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10316990/crash-2022-12-28_16.01.20-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by croftyraider** [comment]
It did not occur when launching the world a second time. The crash screen within mincraft indicated the error may be attributed to NEI. My search bar for NEI had the word "calcite" in it.

**Comment by vovaksenov** [comment]
I also had a crash because of NEI when trying to join a server once. Also went away on 2nd try. 2.2.7.
[crash-2022-12-25_21.16.13-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10324825/crash-2022-12-25_21.16.13-client.txt)
