### ISSUE TITLE
Extreme lag from AE2 after requesting items

### ISSUE THREAD

**Issue by Miisi** [GTNewHorizons/GT-New-Horizons-Modpack#12134]
### Your GTNH Discord Username

Misi#3673

### Your Pack Version

2.2.7 with several mods updated

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

request items that I already had patterned in my system without lag

### The Reality

requesting certain items inexplicably drops my world's TPS to 0-1. lag persists for a while until it comes back to normal, and then if I try to request the same item then there is no lag. it's been quite hard to reproduce as I can't find anything that could be causing it in world

![image](https://user-images.githubusercontent.com/46682682/209983545-1c3d3e10-c796-4d68-a6ee-66476a252228.png)
(after requesting 4 dimensional bridges)

tried profiling with opis, absolutely no information in there (in fact it was not even measuring my dimension for some reason?), so I had to use warmroast

![image](https://user-images.githubusercontent.com/46682682/209982987-d0748842-4f02-442e-8def-772f1b62e807.png)

it's not every item that lags upon request, for example:
- really ultimate battery does not lag 
- dimensional bridges DO lag
- thousands of iron blocks do not lag

only changes to my crafting infrastructure before the lag started happening were a couple of patterns related to fluid solidifying

my AE2 versions were a bit outdated, so I updated every AE2 related mod (extra cells, ae2fc, not enough energistics, etc) to no difference

manii (in Discord) has a similar issue on Zeta, where requesting something like a bio mainframe almost completely shuts the server off, so I want to believe it's not only me with this issue

### Your Proposal

help fix/debug what could be causing this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by tankobuman** [comment]
#11991
Probably I faced same issue

**Comment by Miisi** [comment]
> #11991 Probably I faced same issue In my case it's caused by enabling using substitution for some recipes.

tried downgrading to the AE2 version mentioned in the issue and removed every pattern with substitutions enabled, huge tps drop still occurs after requesting 4 dimensional bridges

**Comment by Miisi** [comment]
just noticed this is a duplicate of #12103 (maybe), so I'm closing it and linking information there
