### ISSUE TITLE
LV  Rock Breaker uses 32 instead of 30 EU

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#12139]
### Your GTNH Discord Username

LazyFlesh#4533

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Rock Breaker to use 30 EU/t, per the recipe.
![image](https://user-images.githubusercontent.com/40587985/210015314-b5db1cec-d041-4913-a844-608f584296ae.png)

### The Reality

IT uses 32.
![image](https://user-images.githubusercontent.com/40587985/210015301-dbfd3201-ad0b-4676-a890-a6b8b18223f8.png)

### Your Proposal

Change either to match.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
yea display rounds it to 30. Need to check in gt code

**Comment by Dream-Master** [comment]
code say it use 30 eu/t

```JAVA
        GT_Recipe.GT_Recipe_Map.sRockBreakerFakeRecipes.addFakeRecipe(
                false,
                new ItemStack[] {ItemList.Display_ITS_FREE.getWithName(0L, "Place Lava on Side")},
                new ItemStack[] {new ItemStack(Blocks.cobblestone, 1)},
                null,
                null,
                null,
                16,
                30,
                0);
        GT_Recipe.GT_Recipe_Map.sRockBreakerFakeRecipes.addFakeRecipe(
                false,
                new ItemStack[] {ItemList.Display_ITS_FREE.getWithName(0L, "Place Lava on Top")},
                new ItemStack[] {new ItemStack(Blocks.stone, 1)},
                null,
                null,
                null,
                16,
                30,
                0);
        GT_Recipe.GT_Recipe_Map.sRockBreakerFakeRecipes.addFakeRecipe(
                false,
                new ItemStack[] {
                    GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Redstone, 1L),
                    GT_Utility.getIntegratedCircuit(1)
                },
                new ItemStack[] {new ItemStack(Blocks.obsidian, 1)},
                null,
                null,
                null,
                128,
                30,
                0);```

**Comment by LazyFleshWasTaken** [comment]
Ok yea, had to get home but it says 32.
![image](https://user-images.githubusercontent.com/40587985/210034835-ff57a2e5-1cc8-48a8-ad69-f2aceee7706b.png)

**Comment by iouter** [comment]
> code say it use 30 eu/t

that's fake recipe
