### ISSUE TITLE
Crushchunk in Overworld (ae2fc probably?)

### ISSUE THREAD

**Issue by Aivast** [GTNewHorizons/GT-New-Horizons-Modpack#12133]
### Your GTNH Discord Username

Aivast#1510

### Your Pack Version

2.2.3

### Your Server

private server

### Type of Server

Don't know

### Your Actions

I have tried to remove block from crashreport with world edit and ended up just with java.lang.NoSuchFieldError: SIDELESS_MODE
I had backups, but some of them already has this problem, and others were too old, so i'm stuck with trying to fix it.

### Crash Report

[crash-2022-12-22_19.34.33-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10320183/crash-2022-12-22_19.34.33-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by asdflj** [comment]
update your ae2 version
