### ISSUE TITLE
MEga Distillation Tower Overclocks too much

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#12132]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Expected my UV Mega distillation tower energy usage to not excessed 491k(standart uv voltage)

### The Reality

MEga Dt overclocks to the point where it uses 2x UV Amperes, it happens when recipe has half of ampere usage, like wood tar distillation recipe

### Your Proposal

dont put half ampere as recipe voltage, put half of effective voltage, like for hv its 480/2 = 240 eu/t

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
Do you have 1 UV hatch? Because if you do then this is intended behavior since megas prioritize maxing parallel and then look for possible overclocks if 256 parallels are reached. Nothing can be done about that since that's an advantage, use 2 ZPM hatches if you need 1A UV max machine.

**Comment by LewisSaber** [comment]
I know its intentended, its more about that multi shouldnt use 100% of hatch maximum energy, there should be room for loss

**Comment by Pxx500** [comment]
Problem with recipe then, all recipes should (and do) use little less EU/t than their tier to account for losses
