### ISSUE TITLE
Nature's Compass NEI recipe is incorrect

### ISSUE THREAD

**Issue by Doxinn** [GTNewHorizons/GT-New-Horizons-Modpack#12130]
### Your GTNH Discord Username

Doxinn#3729

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I tried to make a Nature's Compass and thought that it would only require 1 Sapling and 1 Log to create after looking at the NEI recipe
![image](https://user-images.githubusercontent.com/121594795/209903602-7a2bd5e1-1d6e-4cd2-ba22-d3deede649a1.png)
![image](https://user-images.githubusercontent.com/121594795/209903656-6b87a6a2-6ad5-4976-a57e-721de5371235.png)

### The Reality

The recipe wouldn't work, even after trying different types of woods and saplings. After asking for help in the discord, I found out that the recipe actually required 4 saplings and 4 logs, contrary to the NEI recipe

### Your Proposal

Fix the NEI recipe to show 4 saplings and 4 logs instead of 1 sapling and 1 log.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
This should have been fixed already by https://github.com/GTNewHorizons/NotEnoughItems/pull/327
