### ISSUE TITLE
LUV quest book paradox

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#12131]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

delta

### Your Server

delta

### Type of Server

Don't know

### Your Expectation

The Hi-Computation Station MK-I need a Elite Circuit Board 
![image](https://user-images.githubusercontent.com/59776356/209914195-17b36d9c-d39c-4a0b-a951-678c89225bb2.png)
however to unlock the "Elite Circuit Board" quest you need to do the "separation" quest which need a Neutron Activator and Precise Assembler they both need Hi-Computation Station MK-I 

### The Reality

it is a paradox

### Your Proposal

to report bug

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
your arrow is incredibly wrong, but I will have a look.

**Comment by Eason134HK** [comment]
> 

yep it should be a double arrow since it is a paradox
![image](https://user-images.githubusercontent.com/59776356/209974389-4d3a58ed-3a3e-464a-8aca-262b76e47f9e.png)

**Comment by chochem** [comment]
well no. but I understand what you are saying from your text.
