### ISSUE TITLE
Allow HV soldering Iron to be created with Silicone Rubber

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#12136]
### Your GTNH Discord Username

LazyFlesh#4533

### Your Pack Version

2.2.8

### Your Proposal

The HV soldering iron should be craftable with silicone rubber, rather than just butadine. 

### Your Goal

I have no desire to ever automate butadiene, and will likely use silicone until something better appears. The last time I did butadiene, it took me way too long as I did not have any oil infrastructure at all, making the venture an annoyance. 

### Your Vision

It will allow people who chose silicone rubber to make the HV soldering iron without an unnecessary complication.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
@LazyFleshWasTaken you just put a random fluid or make this sense chemistry wise ?

**Comment by LazyFleshWasTaken** [comment]
what?

**Comment by Dream-Master** [comment]
i mean why you choose silicon rubber? make this more sense than butadine ? chemistry wise ?

**Comment by LazyFleshWasTaken** [comment]
I have a good source of silicone, but no good source of oil stuff for styrene-butadiene rubber, so I automated Silicone rubber.

**Comment by LazyFleshWasTaken** [comment]
Or atleast,  I haven't done any of the oil infrastructure.

**Comment by Dream-Master** [comment]
ok but that sound more like you not have ingredient A let's change the game use B which you have ?

**Comment by LazyFleshWasTaken** [comment]
No, I'm saying let them be interchangeable, like everywhere else. In wires, components, and pretty much everywhere I checked,   
s-b rubber and silicone rubber are interchangeable, except here.

**Comment by Dream-Master** [comment]
ill check ingame to get what you mean :) or can you post a screen here ?

**Comment by King65868** [comment]
Pretty sure the MV and LV version require any type of rubber, just HV doesn’t

**Comment by LazyFleshWasTaken** [comment]
ok, so. HV soldering iron only has s-b:
![image](https://user-images.githubusercontent.com/40587985/210012162-c14bdc00-3a9e-4597-a42d-c99d5aac2a96.png)

quantium cables take both:
![image](https://user-images.githubusercontent.com/40587985/210012218-c4d7e59b-75ff-48d9-95e5-c02858ac9292.png)

luv components take both:
![image](https://user-images.githubusercontent.com/40587985/210012323-e38556f1-a33c-4899-a643-9b42ea2dbd83.png)


Therefore, they are interchangeable.

**Comment by Dream-Master** [comment]
ok make sense. Will check
