### ISSUE TITLE
ME Fluid Level Emitter

### ISSUE THREAD

**Issue by BlueWeabo** [GTNewHorizons/GT-New-Horizons-Modpack#12143]
### Your GTNH Discord Username

BlueWeabo#7517

### Your Pack Version

2.2.8

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

ME Fluid level emitter remembers what fluid it should check on server restart in subnets. It seems like it either doesn't recheck the fluid amounts in the system because of subnet shenanigans or it actually forgets the fluid (It may be the former as the fluid is still displayed as the correct one)

### The Reality

It forgets it needing the player to put in the fluid again through NEI or alike

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Rubijox** [comment]
afaik fluid level emitters should never be used, i remember someone using them a while ago and them lagging their server like mad, while the lag didnt show ingame on the tps, they only had 3 of them and it caused more than 10 times the lag of everything else combined. i don't know if that's been fixed but i don't  believe it has.

**Comment by chochem** [comment]
@BlueWeabo that item is deprecated now. is that still a problem with the replacement?
