### ISSUE TITLE
Eternal Singularity crafting recipe script bug

### ISSUE THREAD

**Issue by KhonaB** [GTNewHorizons/GT-New-Horizons-Modpack#12140]
### Your GTNH Discord Username

Khona Betwanhe#7122

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Browsing NEI, looked at the Xtreme Crafting recipe for Eternal Singularities, expected to see 7 different types of singularities in the recipe.

### The Reality

Saw only 2 kinds of singularity, as depicted in the screenshots, but labeled with 3 different names (all bottom half singularities are also "spaghattic" in tooltip), with 7 different recipes (apparently the correct recipes).
![image](https://user-images.githubusercontent.com/12417837/210029069-070353da-08a9-405d-9d0b-6ddef22873ec.png)
![image](https://user-images.githubusercontent.com/12417837/210029087-d94967e5-8d24-4690-b3e8-810f631544c2.png)
![image](https://user-images.githubusercontent.com/12417837/210029272-784ca0ad-3332-4a15-84a4-ce0ab2be2678.png)
![image](https://user-images.githubusercontent.com/12417837/210029340-2f9b7171-ff14-497e-9d67-68ffcb5fb714.png)

### Your Proposal

Something's gone weird with the recipe scripts, please un-weird it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
hmm. Somehow the singularity count is wrong at https://github.com/GTNewHorizons/Eternal-Singularity/blob/7353439bcd11e25b6461baf75761814a7dc2abb6/src/main/java/singulariteam/eternalsingularity/proxy/CommonProxy.java#L77. But I dont fully see why.
