### ISSUE TITLE
When you Compress Steel Ingot (Steam Compressor) It Turns into a IC2 Steel Block....

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#12151]
### Your GTNH Discord Username

StoneLegion#0026

### Your Pack Version

2.2.3

### Your Server

Stone Legion

### Type of Server

Crucible

### Your Expectation

Block of Steel from GT

### The Reality

Gave a Disgusting terrible looking steel block from IC2...

### Your Proposal

Make it give you a Block of Steel from GT!

I recommend not updating to 2.3.0 till this is fixed because it's Disgusting! 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by KaneHart** [comment]
Not sure how to mark a image NSFW but here is what one suffers through when they compress 9 steel ingots...

![image](https://user-images.githubusercontent.com/425853/210120432-d0f0fd9b-22ae-4067-a857-8ab564d4b5c7.png)

**Comment by Alastors** [comment]
Meme ticket, closing
