### ISSUE TITLE
Graphical Issue

### ISSUE THREAD

**Issue by Gtano1** [GTNewHorizons/GT-New-Horizons-Modpack#12153]
### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I heard about the modpack yesterday and decided to give it a try, expecting everything would run smoothly.

### The Reality

Instead, I was met with a bunch of graphical errors, such as dropped items being completely black, textures not loading and just being a single color, and the screen just turning into a solid color whenever I hold an item in my main hand.
![2022-12-30_20 34 28](https://user-images.githubusercontent.com/121701562/210121747-8636399b-6252-4861-b68e-a0dca7b940ef.png)

![Screenshot (12)](https://user-images.githubusercontent.com/121701562/210121941-339e5c1a-75a1-400d-adb8-bb9e09ff0cbd.png)

### Your Proposal

I don't think this is a graphics card issue, as the usage of my GPU doesn't go over 50% while the game is open according to Task Manager. It can also handle other high requirement mod packs such as Sev-Tech and Enigmatica 2 fairly well.
![Screenshot (11)](https://user-images.githubusercontent.com/121701562/210121901-7b625c5f-d7c6-4cca-a0d2-c544e828346d.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
Do you use Intel integrated graphics? They are often the cause of this problem. Try reverting to an older driver version to fix it.

**Comment by chochem** [comment]
discord bot says: If you experience weird rendering issues, it is possible that your game uses an intel graphic card to render. To know that, at the begining of your latest.log, there is a false crash report saying your graphic card. (it is also written in the crashlogs if you have any). Another way to know that is to look in the performance tab of the taskmanager on windows 10. If you have another AMD/NVIDIA card then switch to it for javaw.exe in your commutable graphic options. If you have only the intel graphic card, it has been reported that downgrading the intel graphic driver to around october 2021 works well.

actually just F3 will tell you if you use an intel igpu now.

**Comment by Gtano1** [comment]
I do have and Intel graphics card, but I don't know how to downgrade the driver

**Comment by Gtano1** [comment]
Yep, downgrading the driver worked.

**Comment by Gtano1** [comment]
Yep, downgrading the driver worked.
