### ISSUE TITLE
[Botania + Thaumcraft] The Focus of the Forest, the thaumaturge's alternative to the Wand of the Forrest

### ISSUE THREAD

**Issue by Shibva** [GTNewHorizons/GT-New-Horizons-Modpack#12150]
### Your GTNH Discord Username

Shibva_

### Your Pack Version

2.2.2.0

### Your Proposal

Create a thaumcraft wand focus whos soul purpose is to have the ability to act as if your holding a Wand of the Forest from Botania and be able to use it. TLDR: a "Wrench" focus for botania

### Your Goal

a research option to making things more space efficient 

### Your Vision

Researching this focus will allow for the player to have a focus that can do what a WotF would do and in turn, can be stored in one's focus pouch, saving inventory space and being convenient just like the IC2 Wrench focus can be quite useful. More of a QoL thing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
Neat

**Comment by Alastors** [comment]
@combusterf Think you would be able to make something like this?
