### ISSUE TITLE
Change Tungsten Steel Wire to TPV Wire in Some IV Single Block Machines

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#12155]
### Your Pack Version

2.2.8

### Your Proposal

The recipes of Alloy Smelter, Extruder, Thermal Centrifuge and Fluid Heater use 4x tungsten steel wire. Change them to 4x TPV wire.
If there are other recipes that use tungsten steel wire as heating wire, change them to TPV too.

### Your Goal

These machines use the same material as the heating coils. Cupronickel in MV, Kanthal in HV, Nichrome in EV, and Tungsten Steel in IV. Now since the coil has been changed from Tungsten Steel to TPV, those recipes should also be changed.

By the way, those machines in LuV+ don't follow the same rules(e.g. LuV Fluid Heater uses  4x Niobium-Titanium wire instead of 4x HSS-G wire, UV Extruder uses 8x Yttrium Barium Cuprate wires instead of 4x Naquadah wires, UMV Thermal Centrifuge uses 16x Bedrockium wires instead of 4x Awakened Draconium wires), I have no idea whether these recipes should be unified.

### Your Vision

Unify those recipes and make them follow the same principles.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Elisis** [comment]
I don't think the later recipes were specifically intended to be consistent with the coils

**Comment by cainiaojun** [comment]
I forget the Furnace and the Electric Oven. Have they been changed?
