### ISSUE TITLE
Advanced Coke Oven Quest Requires Wrong Number of Bricks

### ISSUE THREAD

**Issue by kaanyalova** [GTNewHorizons/GT-New-Horizons-Modpack#12156]
### Your GTNH Discord Username

kaanyalova

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

None

### Your Expectation

Craft the required amount of advanced coke oven bricks to make one multiblock. See that "Advanced Coke Oven" quest in "Bio for the Masses" quesline requires 35 bricks instead of 34 needed.

### The Reality

The quest should ask for 34 bricks , enough to make a multiblock.

### Your Proposal

Change the quest to require 34 advanced coke oven bricks instead of 35.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11765#issuecomment-1327933861
