### ISSUE TITLE
Creative Essentia Cell

### ISSUE THREAD

**Issue by Phineasor** [GTNewHorizons/GT-New-Horizons-Modpack#12167]
### Your GTNH Discord Username

Phineasor

### Your Pack Version

2.2.8

### Your Proposal

The creative essentia cell should be given a rename, and a recipe. It should be renamed to something not "creative" similar to the creative energy cell that was renamed to "neutronium energy cell." I propose that the crafting recipe should be something similar to this 
![image](https://user-images.githubusercontent.com/80113803/210169958-5e83a21a-4704-4231-8fe6-372cd46ebdd3.png)
With 2K of each primal essentia needed.
renaming it to something like "essentia wormhole."

### Your Goal

This would make it so that essentia can be reasonably managed, and produced later in the game, this would help add some alternatives for the fusion spam around UIV,by helping solve the essentia problem for the higher tiers of solar panel. The cell was considered over a year ago in ticket #8305. However while the points made good points, the solar panels are still incredibly expensive on the scales needed for the current and new UIV-UMV tier, the tier that you make this cell.  With the Eye of Harmony, and the Dyson Sphere on the way, this will not be the best way to produce power in UXV and higher tiers keeping it balanced.

### Your Vision

It would possibly reduce compact fusion MK III spam with helium plasma.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
I am fully against this, I have voiced my opinion on this time and time again, Thaumic Energistics should not take over more of the thaum meta, especially when we already have another that does the exact same thing.

Yes, I know the problem with the condenser as is, but until we solve the problem of certain essentias only coming from laggy sources such as wisps, it needs to stay as it is.

**Comment by greesyB** [comment]
I am in favor of this as long as the tiering is at least as late as what is shown. I don't remember the circuit tiering anymore, is this post DTPF?

Mass essentia generation is in an interesting spot around the time octuples become possible, with just three LES being able to support more than an octuple per hour worth of essentia and primals being common enough that resource generation is not terribly laggy yet. Once a player has gotten past this point of the game either
1. There is no reason to need essentia in mass amounts anymore, so why not have creative cells as a QoL for the random crafts they want to do from then on.
2. They are continuing to scale octuple production, in which case why not let them save a little extra tps by removing the need to smelt and store essentia.

**Comment by Phineasor** [comment]
> I am in favor of this as long as the tiering is at least as late as what is shown. I don't remember the circuit tiering anymore, is this post DTPF?
> 
> Mass essentia generation is in an interesting spot around the time octuples become possible, with just three LES being able to support more than an octuple per hour worth of essentia and primals being common enough that resource generation is not terribly laggy yet. Once a player has gotten past this point of the game either
> 
>     1. There is no reason to need essentia in mass amounts anymore, so why not have creative cells as a QoL for the random crafts they want to do from then on.
> 
>     2. They are continuing to scale octuple production, in which case why not let them save a little extra tps by removing the need to smelt and store essentia.

Yes, these circs need a UMV assline taking a DTPF.

**Comment by Phineasor** [comment]
> I am fully against this, I have voiced my opinion on this time and time again, Thaumic Energistics should not take over more of the thaum meta, especially when we already have another that does the exact same thing.
> 
> Yes, I know the problem with the condenser as is, but until we solve the problem of certain essentias only coming from laggy sources such as wisps, it needs to stay as it is.

in my mind this would fully replace the condenser, and it would work as the storage device it is supposed to be.

**Comment by greesyB** [comment]
> Yes, these circs need a UMV assline taking a DTPF.

Good, that would give them proper separation from when octuples are originally craftable. In that case I fully support this suggestion.

**Comment by Phineasor** [comment]
it seems @Alastors is onboard as long as the condenser is kept to resolve the early game laggy essentias for now.But that does sound like it needs to be a priority to fix.

**Comment by Phineasor** [comment]
I will start adding this to Thaumicenergestics.

**Comment by chochem** [comment]
was added
