### ISSUE TITLE
Add pre-painted Laser Vacuum Pipes

### ISSUE THREAD

**Issue by Jermaine-x** [GTNewHorizons/GT-New-Horizons-Modpack#12169]
### Your GTNH Discord Username

Jermaine#3569

### Your Pack Version

2.2.0.0

### Your Proposal

Add pre-painted Laser Vacuum Pipes of various colors.

### Your Goal

Currently, laser vacuum pipes need to be painted after placement, one-by-one.

### Your Vision

Creating a pre-painted version of the pipes will make setups of large active transformer networks more convenient.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by cainiaojun** [comment]
A pre-painted laser vacuum pipes, or maybe a painter that could paint a lot of pipes in one click?
I support this idea.

**Comment by leagris** [comment]
GT3 and GT4 had spray paint cans that had this specific option to paint multiple blocks in-world and with greater efficiency per dye consumed than say IC2 painter.
