### ISSUE TITLE
Undo Storage Drawer Config Changes

### ISSUE THREAD

**Issue by patrick-hill** [GTNewHorizons/GT-New-Horizons-Modpack#12161]
### Your GTNH Discord Username

EventHorizon01#3263

### Your Pack Version

2.2.8.0

### Your Proposal

Undo the config changes to limit the drawer controller reach & max drawers.

If server admins want to implement limitations, that should be up to them.
Most of us play SP and this just means for every single upgrade we have to remember to undo this change.

I get wanting to reduce lag, and when i ran servers, I did things like this too but to implement it as a default for all players, both MP & SP, seems rather silly to me.

### Your Goal

Remove the need to have to change the config back to its default on every pack upgrade ;)

### Your Vision

A bright future, little kids all fed, old people all wringly and happy n shit

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
And all Serverowner and Players on Server will suffer to death with lag. We limit it for good resons.

**Comment by Ethryan** [comment]
Make a patch folder instead that you use to overwrite the standard one, that way you can keep your changes easily.

I usually use **MyEditedPatch/Config/EditedConfigFile.cfg** and then just paste it over and overwrite the original one.
