### ISSUE TITLE
Change WireFactory InputBus Seperation to be true by default

### ISSUE THREAD

**Issue by player5** [GTNewHorizons/GT-New-Horizons-Modpack#12164]
### Your GTNH Discord Username

Belius#9686

### Your Pack Version

2.2.8

### Your Server

private server

### Type of Server

Ultramine

### Your Expectation

Trying craft 1x wire with circ1. Multiblock has 3 InputBus with 1,1,3 circ. Ingot go to circ1 InputBus.

### The Reality

Craft was like circ3

### Your Proposal

Make like BlastFurnance/Mixer/Assembler InputBus split different InputBus.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by King65868** [comment]
Screwdriver controller for separate bus mode

**Comment by player5** [comment]
That works. Thanks.

**Comment by player5** [comment]
Mb change default mode?
