### ISSUE TITLE
 lead lined chest should accept other two rubbers 

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#12162]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.2.8

### Your Proposal

![image](https://user-images.githubusercontent.com/49487505/210161795-1d6ac42d-c680-4b6f-b3ac-4ea1f2de302f.png)
The current recipe accepts only the basic rubber sheets, it should also accept or require the more advanced types of rubbers the quests hinted you should make in HV so players with a already established production line don't have to back down to make basic rubber. 

### Your Goal

QOL

### Your Vision

QOL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Yea gt++ moments :P
