### ISSUE TITLE
Oredict support

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#12168]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.2.8 with newest AE2&AE2FC from Jenkins

### Your Server

Private Server

### Type of Server

Ultramine

### Your Expectation

Trying to use autocraft withoiut oredict.

Updated mods versions
appliedenergistics2-1.7.10-rv3-beta-132-GTNH-2-g1af527f
ae2fc-1.7.10-1.0.43-gtnh

### The Reality

Me put items using oredict for items, put random fluid.

### Your Proposal

AE use oredict only if it alowed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I am not following, can you elaborate with some more details?

**Comment by Phineasor** [comment]
> I am not following, can you elaborate with some more details?

I think he is saying that his patterns have ordict in them when they are not supposed to, and are placing random fluids in things when they are supposed to do specific fluids.

**Comment by Phineasor** [comment]
> I am not following, can you elaborate with some more details?

I think he is saying that his patterns have ordict in them when they are not supposed to, and are placing random fluids in things when they are supposed to do specific fluids.

**Comment by ParagonX42** [comment]
᲼᲼᲼᲼᲼᲼ — Today at 16:07
When I requested something the request said e.g. "500 hss-s stored" and wanted to insert stuff into the dual interface/packet decoder (both broke) but when it inserted fluids it turned out to be something different
It did not request to craft e.g. molten quantum when it got inserted instead of hss-s
so it probably just inserted wrong fluid
as in created it out of nowhere

These patterns did not have oredict enabled.

**Comment by RaitGamerGR** [comment]
> I am not following, can you elaborate with some more details?

I have recipe like this, placen on the dual interface. If i try to craft it, AE can put other fluid with same amount (like 400mb molten redstone instead of needed  400mb distilled water.
![image](https://user-images.githubusercontent.com/70205464/210176547-53d5f703-ece8-4d4d-8931-b9770c965f67.png)
 
About oredict, i have this recipe, and AE try to put all things with _blockGlass_ oredict.
![image](https://user-images.githubusercontent.com/70205464/210176678-54ba6e2b-9005-4b1a-a2c6-ab138d9acb9f.png)

I put it into one issue beacuise i think this problem caused by problom with oredict supprort, like AE try to place any fluid because all drops of fluid packets have one oredict or something like this.
Sorry about name of the issue, i forgot word "oredict" and make mistake...
