### ISSUE TITLE
Dehydrator - Ammonium Tetrafluoroberyllate receipt is blocked by Beryllium Hydroxide dust receipt

### ISSUE THREAD

**Issue by MistrMxyzptlk** [GTNewHorizons/GT-New-Horizons-Modpack#12160]
### Your GTNH Discord Username

Mxyzptlk

### Your Pack Version

2.2.0.0

### Your Server

MMCC

### Type of Server

Don't know

### Your Expectation

remove the receipt for Beryllium Hydroxide dust
since the dust is useless.

### The Reality

This dust is made instead of other fluid

### Your Proposal

remove the receipt for Beryllium Hydroxide dust

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
We can add control circuits not need to remove a recipe

**Comment by MistrMxyzptlk** [comment]
Sure you can, but that dust does not have any use anyway.

While are you at it, you can't smelt Uranium 232 into U-232 since there are 2 dust getting converted into that one that can't be smelted, tho you can bypass it by puting furnace directly behind the output hatch, it's still a glitch.
