### ISSUE TITLE
Mega multis wrong energy usage with TT hatches

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#12177]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Expected to be able to smelt whatever i want in my Mega ABS

### The Reality

I supplied it with 256A/T luv lase(8mil eu/t) but it shut off due to not enough power, when i used scanner it told me that it can accept 320A Luv Amperes
![image](https://user-images.githubusercontent.com/39595617/210238326-82443501-2c50-4537-a814-a80f68312d83.png)
screen has notmal energy usage because its currently doing only 16 uv recipes, yesterday i saw sinken complaining with same issue  with his MEBF,
this bug also happens with multi amp hatche(64A zpm showed me 80A)

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by tankobuman** [comment]
We still have this issue in 2.2.9-dev-pre
