### ISSUE TITLE
Schematica Printer should increase range when player is wearing a Ring of Far Reach

### ISSUE THREAD

**Issue by Jermaine-x** [GTNewHorizons/GT-New-Horizons-Modpack#12175]
### Your GTNH Discord Username

Jermaine#3569

### Your Pack Version

2.2.0.0-stable

### Your Proposal

Schematica Printer should increase range when player is wearing a Ring of Far Reach

### Your Goal

Some multiblocks are not placeable with the Hologram projector, and are very tedious to build by hand - such as Compact Fusions.

As a result, many players get a schematic of the multiblock and build it that way. The mod will build within your normal player range, but it does not have a check to see if the player is wearing a Ring of Far Reach, which would increase building range by 3 blocks. With this change, building compacts is a lot more forgiving.

### Your Vision

SchematicPrinter.java:
```
   public boolean print() {
     ...
        final int minX = Math.max(0, trans.x - 3);
        final int maxX = Math.min(this.schematic.getWidth(), trans.x + 4);
        final int minY = Math.max(0, trans.y - 3);
        final int maxY = Math.min(this.schematic.getHeight(), trans.y + 4);
        final int minZ = Math.max(0, trans.z - 3);
        final int maxZ = Math.min(this.schematic.getLength(), trans.z + 4);


```

Add a check for Ring of Far Reach, and if true, modify those numbers (not the zeroes) to +3 of the original value.

I have tested this by modifying the source code (but without an item check) and it works in SP and MP. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Jermaine-x** [comment]
In SMP, increasing the range by 3 on the printer with the Far Reach ring seems to be inconsistent and sometimes fails in placing blocks. Works fine with a range increase of 2 however.

**Comment by Runakai1** [comment]
Since we have schematic Fairplay now, using any other version of schemstics printer is outside the scope of gtnh
