### ISSUE TITLE
Add sorting to betterp2p "Advanced Memory Card" + make the GUI larger

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#12176]
### Your GTNH Discord Username

hiagg

### Your Pack Version

2.2.3

### Your Proposal

currently the sort order of visible p2ps on the list is seemingly random and it can be a quite annoying task to locate the "input" p2p on a channel with over 4 p2ps. The name is bound to the p2p hash so you cannot simply name the input "input" either.
![image](https://user-images.githubusercontent.com/13358034/210215234-c13b76bf-32f3-4c4b-a219-d5e3950e3bf1.png)

I also would like the gui to be able to extend further up and down the screen on smaller gui sizes. Currently it is only 4 visible p2ps max with a ton of empty space above and below. 

I wasn't sure if I should open another ticket for this but AdamR#0072 gave me this screenshot, showing that the gui is a bit broken on 2.2.8 (green is highlighted as the one he opened, and blue are the other ones of that group)
![image](https://user-images.githubusercontent.com/13358034/210215703-0d49f6e0-66e6-4d8c-a459-f34eab44f577.png)

### Your Goal

We all use a whole bunch of p2ps for our mid-end game bases. And as the pack progresses it can be increasingly difficult to just hook up a p2p using this very useful card.  

### Your Vision

Saves time from scrolling through the list each time and hoping you don't miss it. Streamlines the p2p experience a huge deal.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by lonzodelorana** [comment]
It would actually be really useful if there was an option to hide outputs when searching for an input to bind (and I guess hide inputs when trying to rebind outputs)

If the outputs didn't show, searching for a particular named p2p tunnel would only return a single p2p which you can then very quickly bind the current p2p to that input, instead of sometimes looking through a fairly long list of outputs, trying to spot the input.

Would make it safer for not mis-clicking an output and breaking a p2p somewhere too. Happens extremely rarely, but I've had a delay where window scrolled another step after I found the input and then clicked the bind button, hitting the wrong item in the list.

I think this is relevant enough to the original feature request that I've mentioned it here instead of opening a new issue. Hope that's ok.

**Comment by firenoo** [comment]
I will work on the second (resizable GUIs) soon. For the first, I believe the sorting algorithm should put the input first already - at least in the dev version this is the case. However, I believe I have a better solution for this problem in my mind than changing how they are sorted and will open a new PR suggestion to get some feedback on it before I try to code it soon.

@lonzodelorana I offer two proposals:
1. Filter from the search bar using `@` tags: The idea is that to filter only inputs, add `@in` to the search query (space separated), and for outputs `@out`.
2. Add a checkbox button (well, 2 actually for input and output) which toggle their visibility.

Could do both, but the 2nd is going to be a lot more involved.

**Comment by lonzodelorana** [comment]
Sorting will help certainly!

Checkboxes do seem better for usability to me, especially if they toggle and stay on for the next time you use the card. I'm not sure about everyone but most times I use the advanced memory card, I'm looking to add something to an exiting input, or making a brand new connection, which is fine as unconfigured p2p tunnels default to inputs

However, as long as the @ tags will work in addition to the rest of the search so you can do "@in water" as a search to find any p2p tunnels with the word water but only the input p2p's, that would be absolutely usable and a huge qol improvement on using the advanced card. It would be more than enough if the effort for checkboxes is disproportionate imo!

Appreciate the work on this! :)
