### ISSUE TITLE
Mainframe (IV Circuit) recipe looks weird in NEI

### ISSUE THREAD

**Issue by ah-OOG-ah** [GTNewHorizons/GT-New-Horizons-Modpack#12180]
### Your GTNH Discord Username

OmniSlaves#6732

### Your Pack Version

2.2.8 w/ updated GT5u, GT++, MUI

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I use 2.2.8, with GT++ 1.7.176, GT5u 5.09.41.196, and MUI 1.0.37.

Amount of Annealed Copper Wire needed should display as 16, and an alternative with 24 Copper Wire is shown as well, or else only 24 Annealed Copper Wire is shown (this would match the QB).

![iv_circuit](https://user-images.githubusercontent.com/75745146/210278302-ffdfa956-1b65-4310-95d2-3f28f87c483a.png)

### The Reality

16 Annealed Copper Wire and 24 Annealed Copper wire is shown.

### Your Proposal

Fix the NEI display, possibly by changing recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
Yes it is broken and need to be fixed

**Comment by LazyFleshWasTaken** [comment]
There is 16 annealed copper wire if you're using advanced smd's, otherwise it's 24 annealed copper wire.
