### ISSUE TITLE
Vibrant alloy changed mods, became useless.

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#12185]
### Your GTNH Discord Username

Lazyflesh#4533

### Your Pack Version

2.2.8

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

I was trying ot make vibrant alloy plates as usual, melt and cast, then use the plates for fluid conduits.

### The Reality

they turned into gt++ vibrant alloy plates, rather than gt ones. I was unable to use them in any recipes except re-melting and turning into blocks. 

### Your Proposal

make em change back like all other plates/casings/etc. when you throw them to the grund.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
guess we can remove vibrant alloy and other ender io metals in GT++ code

**Comment by miozune** [comment]
GT++ variant of Vibrant Alloy is now removed by https://github.com/GTNewHorizons/GTplusplus/pull/729
