### ISSUE TITLE
Arcane assembler doesnt work properly

### ISSUE THREAD

**Issue by Team1Warlord** [GTNewHorizons/GT-New-Horizons-Modpack#12186]
### Your GTNH Discord Username

KOT_BHE_3AKOHA#7758

### Your Pack Version

2.2.8

### Your Server

private server

### Type of Server

Ultramine

### Your Expectation

Working like on 2.2.3, 2.1.2.1 or previous vers.

### The Reality

Problems with autocrafting more than 1 item
![image](https://user-images.githubusercontent.com/55826128/210360168-c5dc64f4-0302-42a0-8a52-ac0f9711ce97.png)
After server reboot assembler made 16 valves and stopped after that, and dont want to craft anymore, another recepie that dont want to craft
![image](https://user-images.githubusercontent.com/55826128/210360470-9d14a092-d0af-4c81-9379-5afc015d3be8.png)
Meanwhile this recepie was crafting properly
![image](https://user-images.githubusercontent.com/55826128/210360594-a1f023b4-9827-4f08-8c8c-931866f38d53.png)
After extracting and inserting core no any changes, but it makes 1 item of 16 for example and than stops.
If i want to get 1 item for example and u want to do that after server reboot or after extr/ins core - u will get phantom craft that will block any crafting in this processor, item was already done and got into ME
![image](https://user-images.githubusercontent.com/55826128/210361151-7d8c65b8-116f-4cb0-b4af-9a050aea5629.png)
Arcane assembler setup:
![image](https://user-images.githubusercontent.com/55826128/210361282-93f65dea-4ce4-4ff6-9556-0937d8508978.png)
![image](https://user-images.githubusercontent.com/55826128/210361327-93fbb07d-fc6b-48fa-8413-55980f16c1d7.png)
![image](https://user-images.githubusercontent.com/55826128/210361375-a8b560d5-0bb8-46c0-9e6b-9bd7fe7940cc.png)
Ver of AE2 is 129, not 132 bcs on 132 was broken fluid crafting, i tested this on 132 and everything was the same.
BTW about phantom crafting - after 10 min its still here, i think it will disappear after server rebooting, or just break and place some blocks of processor

### Your Proposal

Working recepie like on prev vers

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment]
@Team1Warlord provided me with a world download to test and I believe I have confirmed the breaking commit to be https://github.com/GTNewHorizons/ThaumicEnergistics/pull/27 though I do not know why.

I tested with AE versions 116, 130, and 134 and was able to reproduce, but could not reproduce after downgrading thaumic energistics to 1.20 (just before the referenced commit). I also cannot reproduce this on a fresh 2.2.8 world (which does include the referenced commit).

**Comment by cinch** [comment]
confirmed, getting the same issue on 2.2.8 
![image](https://user-images.githubusercontent.com/61357/211568711-e6701582-f243-4a98-894b-76c1704b1795.png)

**Comment by greesyB** [comment]
The issue seems to be a combination of the thaumic energistics change and some strange simulation behavior. I am waiting until https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/221 is done to make further changes here.

**Comment by greesyB** [comment]
Adding some info as I may not be able to get to this soon:

This happens for recipes with oredicted inputs when AE doesn't pick up the exact input in the pattern. More problematically, the input in the pattern can be changed by AE at some point after creation.
A bandaid fix could be to remove the hash/equality check on ingredients in ArcaneCraftingPattern, but I don't know about side effects of this and still want to figure out what is actually happening with the pattern in memory.

**Comment by Fiyorin** [comment]
someone should revert the changes made in https://github.com/GTNewHorizons/ThaumicEnergistics/pull/27/files

greesy approves 
![image](https://user-images.githubusercontent.com/61357/223160604-25ff7da5-2a7e-4829-827b-970f2b380277.png)
