### ISSUE TITLE
ME dual interface ignoring blocking mode

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#12181]
### Your GTNH Discord Username

Keyla#3300

### Your Pack Version

2.2.8

### Your Server

Own server

### Type of Server

Ultramine

### Your Expectation

Tried to make a setup with a dual interface, which outputs to a ingredient buffer, while interface had some conduits nearby. Enabled blocking mode on the dual interface, expected it not to push items when something is in the containers.

### The Reality

It completely ignores blocking mode if dual interface has conduits (empty containers) near it. Therefore, dual interface blocking mode outputs items in a full container if there is an empty container nearby. Making a dual interface directional helps, but that only allows to use interface+one container+conduits, howerever not interface+2 containers+conduits 

### Your Proposal

Make interface check each container if it is full or not, not allow input if any of the nearby containers is empty
### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by asdflj** [comment]
i can't reproduce the problem

**Comment by CatsLeftEar** [comment]
I cant either now, sorry

**Comment by CatsLeftEar** [comment]
If a ME dual interface has a chest which i want to input items to, Dual interface has a blocking mode, it works fine. As soon as ME dual interface has a conduit attached to it, doesnt matter if its only on input to the interface, blocking mode stops working because interface starts thinking that there is an empty inventory nearby (conduit) and inputs items in a chest with items already in it. 
Now i know how to reproduce this bug

**Comment by CatsLeftEar** [comment]
So if ME dual interface has a conduit attached to it (or some other containers which are empty), blocking mode to a chest will not work.
Blocking mode stops working for every containter if at least one of them is empty. Should check every container one by one, not all at once or something like that

**Comment by EnderProyects** [comment]
Are you using a full size interface?

**Comment by CatsLeftEar** [comment]
https://imgur.com/QOLRct5

**Comment by CatsLeftEar** [comment]
> Take a wrench and toggle the direction of the interface

it will help if i want to output only to one container, but in some situations i would want to output to different containers. normal interface works properly, so it needs a fix, i guess

**Comment by CatsLeftEar** [comment]
Because of this, for example, two dual interfaces can not stay next to each other (as well as near any conduits) if you want to use blocking mode on it. Normal interfaces dont try to push items into each other, dual interfaces push liquids into each other. Why not just copy the behaviour from a normal interface

**Comment by Divran** [comment]
I was about to create a ticket with the same name (ish) so I'll add to this ticket instead

How to reproduce it: Put any chest or item container on one side of a dual interface, and a fluid storage on the other side. It may also be reproducible if you use EIO conduits as people have mentioned above.

Below picture shows a super bus on the left side and a fluid p2p on the bottom. 

![image](https://user-images.githubusercontent.com/1485728/218564090-c7172d8f-d074-4ef1-9692-8028ec9bdfca.png)

**This worked in the previous version of ae2fc** but after we updated to

- ae2fc-1.0.65-gtnh-1-g8e230af.jar
- appliedenergistics2-rv3-beta-154-GTNH-1-gefadbe5.jar

it stopped working

**Comment by Divran** [comment]
Here are instructions on how to reproduce it

build this setup, and then enable blocking mode
blocking mode will be ignored
![image](https://user-images.githubusercontent.com/1485728/218570670-9b505cdf-094d-4a82-b659-5689056bc013.png)
