### ISSUE TITLE
Energy Hatch 2A->5A upgrade is too cheap

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#12188]
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

2.2.0.0

### Your Proposal

To update Dynamo hatch you need at least a Circuit of that tier.

To update Energy hatch, for example IV, it takes only 4 tungsten and 2 tungstensteel. That's a joke for a such upgrade. Because this upgrade gives a double profit, 2a->5a.

Make Energy hatch upgrade similar in price to Dynamo hatch upgrade.

And still an upgrade from 1/2a to 4a for just a 1 circuit is too cheap. It should be cheaper than making another hatch, okay.
But you are not paying just for doubling the amperage, but also for convenience, because it will take less space and cable management. And you should pay for convenience!

### Your Goal

Make good and convenient things expensive.

Make Energy and Dynamo hatch upgrade prices equal or similar.

### Your Vision

Increase the price of Dynamo hatch upgdate.
Gradually increase the price of Energy hatch upgrade.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by nikitinalexx** [comment]
Also another thing, the original name is "IV 4a Energy Hatch". But the tooltip says it can actually receive "5A". So the upgrade is even better than I thought for almost 0 price.

**Comment by minecraft7771** [comment]
- The TecTech hatches don't work on all machines
- They receive more than 4A to compensate loss

**Comment by chochem** [comment]
It 

> * The TecTech hatches don't work on all machines
> 
>     * They receive more than 4A to compensate loss

I think its still fair to say that they are pretty cheap for what they do. (laser hatches even more so)

**Comment by Glease** [comment]
Dynamo upgrade allows you to run generators 1 tier more advanced without exploding, which is crucial in all multiblock generators. Multi amp energy hatch does not have such capabilities.

**Comment by chochem** [comment]
> Dynamo upgrade allows you to run generators 1 tier more advanced without exploding, which is crucial in all multiblock generators. Multi amp energy hatch does not have such capabilities.

That is just false. Multi amp hatches do infact allow you to run (some, not all) machines at a higher tier. MBF for example, or other megas. Or nano forge.

**Comment by nikitinalexx** [comment]
Even if TecTech energy hatch can not be used in every machine possible, an upgrade that doubles the power of machine should not be 0 cost.

**Comment by Glease** [comment]
re: gating 

MBF are gated by glass tier and coils. So are other megas. In fact tier gating is the `#1` problem you need to consider when you want to allow multiamp hatch or lasers. The only exception is vacfreezer which doesn't need gating anyway. 

---

The OP really sound like he never actually used these hatches at all and questions if it is too cheap well before making his first. Multi amp hatch is really just for machines that need more than 2 amps, or power storage/transformer multis to not make it worse than a 16a battery buffer. For the multis that allow these hatches, they are never an upgrade, but a must.

**Comment by BlueWeabo** [comment]
> That is just false. Multi amp hatches do in fact allow you to run (some, not all) machines at a higher tier. MBF for example, or other megas. Or nano forge.

Nano forge was made with that in mind. While making it I even thought about making it take even more power than it currently does.

**Comment by cainiaojun** [comment]
I disagree.
Tectech multi-amp energy hatches are totally useless before LuV. Only a bit part of machines allows multi-amp hatches. If you want to nerf multi-amp hatches, you can just nerf the laser hatches instead, can't you?The laser hatches have been used more commonly than multi-amp hatches.
In fact, nobody cares the fact whether you can use a multi-amp hatch to get Neutronium in LuV.(well you couldn't) It surely is tier-skipping but it's not important. Players would continue to use them no matter what you change the recipe to. This change is like changing the water into distilled water when you use some methane to make hydrogen. It won't change anything it just makes players feel exhausted.
So forget this idea.

**Comment by nikitinalexx** [comment]
Here is my use case since some people say I didn't use this hatch.

I have a Power Station.
To feed it with energy in EV I had to build a lon of EV Energy Hatch, each being 2A. It wasn't quite easy.

But now I transfer to IV and it suddenly became very easy because I can easily make a 5A Energy hatch.
So compared to EV, in IV I am able to get a 2.5X boost for free. From 2a to 5a.

While struggling in EV trying to make a lot of different hatches, I got a very cheap and easy alternative in IV. Just make a single Energy hatch, update it to 5A and bam u have free 40k eu/t income.

I don't feel this is balanced.

**Comment by nikitinalexx** [comment]
I really don't understand your concerns, because I didn't run into your use cases.

But if we abstract from them and forget about any use case.
There is a machine that has a power of 2. Then you can make a machine with power of 5.
How much would you pay for such an upgrade?
I hope it won't be just 6 ingots, but at least a circuit!
We have so many difficult and hard things and this is the theme of the pack. I don't understand why everyone now is protecting a thing that is literally free. This is not in line with this pack at all.
I am not asking to make a price of that update ridiculous.
But at least a single IV circuit. I am pretty sure this will not affect your experience at all in IV stage.

**Comment by nikitinalexx** [comment]
Or please make an EV hatch with 2a->5a which will cost 4 titanium. Then I will say both EV and IV energy hatches are fair.
Otherwise I don't understand why do we have to struggle so much in EV with those hatches.

**Comment by nikitinalexx** [comment]
@cainiaojun , who said these hatches are useless before LuV?

I am using them for my Power Station in IV and they are goddamn strong. I can feed tons of Kinetics into it.

**Comment by YTXilo** [comment]
So instead of saying make those hatches more expensive, you should change it so that the lower tiers have multi-amp hatches?

**Comment by nikitinalexx** [comment]
Lol if you read the whole thread, all my messages before the last were "make them more expensive", right?

**Comment by YTXilo** [comment]
I did read the thread, and as others have mentioned, this can be used on like a total of 5-7 multis, so its use is balanced, as you mentioned the buffered dynamos, but there is also the multi-amp dynamos, so tbh the buffered does the same thing as multi-amp dynamos past iv, from what I've seen these recipes do not to be changed because the 64A multi-amp iv dynamos love eating tungsten, so multi-amp ev should be added before modifying the multi amp hatches imo

**Comment by nikitinalexx** [comment]
The amount of tungsten it eats for 16a and 64a is a joke.
TecTech Energy and Dynamo are equal.
My concern is that regular 4a Energy and Dynamo are not equal to 4a Energy and Dynamo TecTech. For some machines TecTech is a 100% option because it is very cheap.

I can't tell that the fact it is used in 5-7 multis justifies the price. The Power Station is a quite popular machine.
Even if it is not for the Power Station, the fact that this Hatch is niche, doesn't mean it should be free.
There are other niche things, but we are not making them free or very cheap.

**Comment by nikitinalexx** [comment]
If someone thinks that regular 4a version for him is better than TecTech 5a version, fine, go for it.
But the price should be equal. Otherwise I don't understand why machines that in certain circumstances provide exactly the same functionality have to be very different in price.
If someone says - "if they have the same price, why would someone use 5a tecTech rather than 4a regular", then my answer is "then it means that TecTech version is not needed and it can be removed from the game because it doesn't give extra functionality".
But if for some reason it gives extra functionality and some people would prefer 5a TecTech version rather than regular 4a version, then they should have equal price.

**Comment by Nxer** [comment]
Cheap or expensive ? This is just a Subjective concept .
If you want it become more expensive , you need give more overall numerical comparison about the Cost through whole GTNH , not just these subjective thinking .
It's just your thinkso .

**Comment by nikitinalexx** [comment]
Huh? Subjective? TecTech costs 4 tungsten ingot and 2 tungstensteel ingot.
Regular buffered hatch costs 2 tungsten ingot and 1 IV circuit.

So technically the question is, what is more expensive 2 tungsten and 2 tungstensteel OR 1 IV circuit.
I'm pretty sure 99% of people would rather take 1 IV circuit than 2 tungsten and 2 tungstensteel.
If you want to give a specific price to 1 IV circuit, then be it your pleasure, please provide data. But looking at my AE that's pretty a lot of components and especially time.

**Comment by nikitinalexx** [comment]
Btw I am not saying expensive, I am saying equal to the price of the Machine that we already have.
You don't need to compare anything. Just make the price similar - 1 circuit of respective tier. Similar to buffered dynamo hatch.

**Comment by Nxer** [comment]
> Huh? Subjective? TecTech costs 4 tungsten ingot and 2 tungstensteel ingot. Regular buffered hatch costs 2 tungsten ingot and 1 IV circuit.
> 
> So technically the question is, what is more expensive 2 tungsten and 2 tungstensteel OR 1 IV circuit. I'm pretty sure 99% of people would rather take 1 IV circuit than 2 tungsten and 2 tungstensteel. If you want to give a specific price to 1 IV circuit, then be it your pleasure, please provide data. But looking at my AE that's pretty a lot of components and especially time.

If u use buffer Dynamo Hatch on Energy Station or some high current generator , then suit yourself .
Nobody have times to do these , if u want u had better to pr .

**Comment by greesyB** [comment]
In my opinion these should be left as is, unless for some reason people want to make them _actually_ expensive (could be interesting, but probably just annoying). Simply adding a circuit does very little to increase the cost and only serves to force people to redo dozens of patterns they already have for energy hatches.

**Comment by Nxer** [comment]
> In my opinion these should be left as is, unless for some reason people want to make them _actually_ expensive (could be interesting, but probably just annoying). Simply adding a circuit does very little to increase the cost and only serves to force people to redo dozens of patterns they already have for energy hatches.

That's right

**Comment by nikitinalexx** [comment]
Okay, community decided this change is not needed, closing the issue.
