### ISSUE TITLE
Fortune and Auto-smelt enchants reproduce bartworks metal block

### ISSUE THREAD

**Issue by ocean922** [GTNewHorizons/GT-New-Horizons-Modpack#12199]
### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

None

### Your Expectation

Remove the recipes for ALL metal Block to metal Ingot in furnace.

### The Reality

If you a pickaxe have FORTUNE and AUTO-SMELT enchants,
[pic1]
![01](https://user-images.githubusercontent.com/122027748/210797617-67ba8e90-c3fd-4357-b229-3d4400e1564f.png)
And use it to dig the metal block of BARTWORK,
[pic2]
![02](https://user-images.githubusercontent.com/122027748/210797068-2cc34d43-b41f-4713-80f6-d131335b2000.png)
The ingots are reproduced.
[pic3]
![03](https://user-images.githubusercontent.com/122027748/210797986-7a93366f-557b-4da9-ad14-4fd6e91b6c87.png)
Because
[pic4]
![04](https://user-images.githubusercontent.com/122027748/210798258-ea0b48d0-8c1f-415e-9306-ba207335a35b.png)
The metal elements affected are : Cf,Ca,Ru,Rh...... 

### Your Proposal

FORTUNE and AUTO-SMELT enchants reproduce BARTWORKS metal block.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
@ocean922 can you check if https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/TinkersConstruct.cfg#L23 is set to true in your config?

**Comment by ocean922** [comment]
@boubou19 false. This enchant belong Eio, not Tic. I think this configuration is used to control Tic's lava crystal.
