### ISSUE TITLE
Update server and crush

### ISSUE THREAD

**Issue by Alsarus** [GTNewHorizons/GT-New-Horizons-Modpack#12195]
### Your GTNH Discord Username

Alsarus#5545

### Your Pack Version

2.2.8

### Your Server

private

### Type of Server

Ultramine

### Your Actions

Hi.
Always running my server on Ultramine core. Haven't played for a year. Today i update my server from 2.0.x to 2.2.8. But server didn't start. 
Checking versions 2.2.3 and 2.2.7: same situation.
But if i install 2.2.0 - works perfect. 
I know that is my local problem (guys from discord have Ultramine core with 2.2.8 installed). But i understand whats didn't working. Help me please.

### Crash Report

[crash-2023-01-04_12.03.24-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10342207/crash-2023-01-04_12.03.24-server.txt)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10342208/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
Remove NotEnoughIDs

**Comment by Alsarus** [comment]
Yep. Working.
Thank you!
