### ISSUE TITLE
Nature's Compass recipe incorrect in NEI

### ISSUE THREAD

**Issue by MursonThePerson** [GTNewHorizons/GT-New-Horizons-Modpack#12193]
### Your GTNH Discord Username

mason#5995

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to craft Nature's Compass in a Basic Assembler, NEI says it requires 1 log, 1 sapling, and 1 compass along with some refined glue.

### The Reality

Nature's compass did not craft, however it did craft once 4 logs and 4 saplings were inserted. (This appears to be the recipe from earlier versions according to members of the discord?)
![image](https://user-images.githubusercontent.com/121911067/210465160-f615d202-3989-4f7a-a230-b893d2aac801.png)
![image](https://user-images.githubusercontent.com/121911067/210465194-99a210a5-7152-489e-986b-0bf8dc0b510f.png)

### Your Proposal

Change the NEI recipe or change the assembler recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/NotEnoughItems/pull/327
