### ISSUE TITLE
Compact Fusions do not display correct energy usage

### ISSUE THREAD

**Issue by Jermaine-x** [GTNewHorizons/GT-New-Horizons-Modpack#12198]
### Your GTNH Discord Username

Jermaine#3569

### Your Pack Version

2.2.0.0

### Your Server

Private

### Type of Server

Single Player

### Your Expectation

Using Niobium Plasma as an example:
 Base EU/t consumption is 49,152 EU/t 
 Startup Cost is 200,000,000 EU (MK2 Fusion)
With a MK3 Compact, this will do 128 parallels, and overclock the recipe from MK2 to MK3
 49,152 * 128 = 6,291,456 EU/t
 * 2 (overclock) = 12,582,912 EU/t

### The Reality

The compact does consume 12,582,912 EU/t as expected, with 8 UHV Energy Hatches. However, the tricorder will show that it uses 6,291,456 EU/t.

This bug is present with various different fusion recipes. Have not tested it on other compacts (MK1, MK2) or other, non-compact machines; only tested with MK3 Compact.

The issue is present in SP and MP. Tested personally on 2.2.0.0. 
Sintken and Johny709 report this issue is present in 2.2.8.

NOTE: The WAILA tooltip introduced in dev versions (see below) does show the correct usage, but the tricorder result is still incorrect
![image](https://user-images.githubusercontent.com/121763446/210711482-20d17c41-11ad-44e0-98d0-782806ba7fe7.png)
![image](https://user-images.githubusercontent.com/121763446/210712688-c9088857-50ce-44a5-8841-50331574f15a.png)

### Your Proposal

Fix the energy calculation display to correctly take overclocks on compacts into account when scanning with a tricorder. The current implementation is very misleading and adds a lot of potential confusion for people are trying to get their setups running based off what the tricorder is telling them.

My best guess is this in the Good Generators code, LargeFusionComputers.java:
```           
      powerRequired = this.mLastRecipe.mEUt * this.para;
```

This should probably read something like:
```           
     powerRequired = this.mLastRecipe.mEUt * this.para * this.overclock(this.mLastRecipe.mSpecialValue)
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
how is it running at all? You dont have the startup power.

**Comment by Jermaine-x** [comment]
> how is it running at all? You dont have the startup power.

Sorry, to be clear there are 32 energy hatches in my setup, but only 8 connected to power (so that it has the startup power).
