### ISSUE TITLE
OС  getEUStored() -> value overflow

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/GT-New-Horizons-Modpack#12205]
### Your GTNH Discord Username

dahgul#1726

### Your Pack Version

2.2.0.0 and 2.2.3.

### Your Server

eta

### Type of Server

None

### Your Expectation

get information from the LSC with the Ultimate capacitor

### The Reality

It cant
![image](https://user-images.githubusercontent.com/35747549/210865629-d173e63f-3cca-4ab1-9201-789a1457fb99.png)

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/210884307-8f7dcbaa-1f00-4c5c-a6bd-bc0340596ead.png)
Can't reproduce that in 2.2.3, perhaps it happens when the stored amount is really high, but then it is an LSC bug, has nothing to do with OC, and should be visible in tricorder output.

**Comment by Zereff06** [comment]
![image](https://user-images.githubusercontent.com/17906427/211060027-0147096a-7c33-4649-81d5-3331857e7efa.png)

bug was with this value

**Comment by Zereff06** [comment]
(1 UHV and 8 iv cells)

**Comment by repo-alt** [comment]
What exactly version is that? Because I tested actually not on 2.2.3 but on 2.2.8 (Current Zeta)

**Comment by Zereff06** [comment]
i tested on 2.2.3

**Comment by repo-alt** [comment]
Can you look what OC version is there?

**Comment by repo-alt** [comment]
Interesting, 1.8.+ should work fine

**Comment by repo-alt** [comment]
String version of the functions is added, nothing more can be done for that issue I think.
