### ISSUE TITLE
Cannot start AE2 crafts even when all input items are present + weird substitutions

### ISSUE THREAD

**Issue by GDCloudstrike** [GTNewHorizons/GT-New-Horizons-Modpack#12207]
### Your GTNH Discord Username

GDCloud#2907

### Your Pack Version

2.2.9-pre

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Trying to order any craft in the ae2 network. Expect to always be able to start the craft if all input items are present.

### The Reality

As visible in the video below, even while having all items that are needed in the network, the start button is greyed out and cannot be clicked. 

https://user-images.githubusercontent.com/93287602/210885101-cfd43094-7529-4a7c-a92f-b66cc1baf13e.mp4

Also briefly visible is another issue that might or might not be related, namely that zpm batteries are being substituted into the uv microwave transmitter recipe even though substitutions are turned off in the pattern.
![image](https://user-images.githubusercontent.com/93287602/210885769-f1d69a51-541f-4913-a2ae-93d0db1fd1ac.png)

The start button issue also occurs when no such substitutions are present, like in the bioprocessor recipe, which I can order 100 but not 1000 of for some reason. 
This issue does not appear to happen with bio mutated circuit boards though.

### Your Proposal

Fix the weird behaviour

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miisi** [comment]
recipes with renamed items and weird oredictionaries (like ae2 certus, fluix and charged certus) are also broken

**Comment by GDCloudstrike** [comment]
Half of this seems to be working now, on 2.2.9-3-dev-pre I can press the start button, but the substitutions still appear to be broken. Upon ordering a bunch of zpm lapo batteries, ae was using the wrong renamed items for the assemblyline recipes and was trying to rename already renamed things in the forming press, causing it to stall.

**Comment by GDCloudstrike** [comment]
The initial issue seems to appear again in the latest dev version (2.2.9-4-dev-pre) where I cannot seem to be able to start the recipe even though I have all the necessary inputs, might be related to the EC2 fluid storage bus issue.
![image](https://user-images.githubusercontent.com/93287602/213894391-13a78fad-bd5d-4460-80bd-3f15fe846616.png)

**Comment by eigenraven** [comment]
If you have ec2 fluid storage buses, that's a known trigger for this bug now, we have to wait for Glod to fix ae2fc

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/218338079-53a9285e-7da3-4913-a5af-d572eb36c1a3.png)
