### ISSUE TITLE
Add a recipe for "Storage Downgrade" 

### ISSUE THREAD

**Issue by ashido96** [GTNewHorizons/GT-New-Horizons-Modpack#12203]
### Your Pack Version

2.2.0.0

### Your Proposal

Storage Downgrade (id: 10577) Does not have a recipe. 

### Your Goal

Allow drawers to store intermediary products without excess materials when used in early game automation setups for crafting. 

### Your Vision

Allow for more complex automated crafting in MV with project-red or conduits. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
@Dream-Master the last ticket about that you closed as fixedindev. https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11157
was there an attempt to add a recipe or what happened?

**Comment by LewisSaber** [comment]
![image](https://user-images.githubusercontent.com/39595617/210858294-6cf8705a-b1d5-4079-b6bf-871ffa5136f6.png)
i have recipe on 2.2.8

**Comment by chochem** [comment]
ah nice. just saw that the closed ticket was before 2.2.0.0 and so figured thats not actually true.
