### ISSUE TITLE
Quest ID 861: Tungstensteel Doesn't Detect

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#12210]
### Your GTNH Discord Username

shawnbyday #1337

### Your Pack Version

2.2.8

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Put 64 Tungstensteel Ingots into inventory. Expected quest to complete.

### The Reality

Quest did not complete. Tried dropping on ground and picking back up. Still quest did not complete.

### Your Proposal

Figure out why the quest isn't detecting the Tungstensteel Ingots and fix?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/211022619-1c1330ed-dd1e-45c8-a994-2cc305fd9516.png)
![image](https://user-images.githubusercontent.com/40274384/211022767-77a0a130-1289-4e58-9e96-bd3d9391272d.png)
![image](https://user-images.githubusercontent.com/40274384/211022737-8bb491a3-ed09-49de-802a-5026186b386f.png)

yea, unsurprisingly this works just fine.
