### ISSUE TITLE
galaxy space jetpack

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/GT-New-Horizons-Modpack#1221]
flying with the galaxy space jetpack then landing causes super high damage for no reason, i flew one block off the ground landed and got 1shot from 10hearts.

**Comment by Dream-Master** [comment]
Not using it. The Mod is not open source so nothing i can do.
And do me a favor and report it on his side. Thanks.

**Comment by Dream-Master** [comment]
https://github.com/BlesseNtumble/GalaxySpace/issues

**Comment by kokochicken** [comment]
ok thank you

**Comment by Dream-Master** [comment]
Will see if @BessNtumbe ever answering. Another issue on his mod he not answering yet.

**Comment by nanmumc** [comment]
It calculate the damage from the highest you reached, so that use a hangglider to resetting the height may help you a lot.

**Comment by Dream-Master** [comment]
Maybe i will update galaxy space in the future idk.

**Comment by Prometheus0000** [comment]
This can be fixed now if it's still an issue.

**Comment by glowredman** [comment]
I tested it and were not able to reproduce this bug.
