### ISSUE TITLE
Assembly line breaking with 8 uxv energy hatches

### ISSUE THREAD

**Issue by GDCloudstrike** [GTNewHorizons/GT-New-Horizons-Modpack#12219]
### Your GTNH Discord Username

GDCloud#2907

### Your Pack Version

2.2.9-pre

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Trying to use 8 wireless uxv energy hatches on an assembling line, expect it to OC to error voltage.

### The Reality

The recipe time changes to max int ticks and the power consumption becomes negative.
![image](https://user-images.githubusercontent.com/93287602/211083508-7c66193b-b368-4448-911d-95084d8b3e65.png)

### Your Proposal

Fix assline OC past max

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
As I remember AL not working with 8 energy hatches is intended as a lot of tiering depends on it. Or are you saying it works with all but UXV?

**Comment by POPlol333** [comment]
> As I remember AL not working with 8 energy hatches is intended as a lot of tiering depends on it. Or are you saying it works with all but UXV?

AL actually work with 8 wireless hatch, the thing probably going there is that assline doesn't have overclock beyond max implemented
