### ISSUE TITLE
Add a Debug Uncertainty Resolver in UHV or UEV

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#12213]
### Your Pack Version

2.2.8

### Your Proposal

Add a Debug Uncertainty Resolver in UHV or UEV.

### Your Goal

It would take a long time to complete a Uncertainty Resolver. Most of players don't understand how it works and just randomly click those button to complete it so it is a really annoying experience. Even more advanced players such as me can understand its rules, it is still too hard to complete it when you build a max-tier Quantum Computer. And after some time I have to repeat it.

### Your Vision

Make the use of Quantum Computer easier.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/TecTech/pull/267
