### ISSUE TITLE
[Suggestion] Rebalance the cost of iron plasma

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#12229]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.3.0

### Your Proposal

I want to change following recipe to:

32mb Magnesium +  16mb silicon = 288 iron plasma
time cost from 1.6s to 0.8s
Starting EU change to 60M EU

The detailed reason is in the following "Your Goal"

### Your Goal

This change effects the players who firstly build the fusion reactor (normal Mk1) not much.
Because at the beginning of fusion , the produced power can't make silicon and magnesium produced forever.(as infinit loop)
and doesn't help too much in processing tech level

But can reduce the AFK time of late game players a bit.And provide a new method to generate power from fusion,
And helps reduces the late game TPS drop because of the generator line too long.

This can be an alternative of power generation to late game players

### Your Vision

as above

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
what do you mean? Its super easy to make silicon and magnesium produced forever. You get them both from obsidian.

**Comment by chochem** [comment]
Further thoughts:

This sounds like a **massive** buff to fusion. 4x faster based on recipe and mk1 instead of mk3, so 4x from OCs. So a 16x buff to iron plasma. That would make it the no1 plasma for power by a mile correct? Like 2-3x helium?

**Comment by KamenriderZO** [comment]
> Further thoughts:
> 
> This sounds like a **massive** buff to fusion. 4x faster based on recipe and mk1 instead of mk3, so 4x from OCs. So a 16x buff to iron plasma. That would make it the no1 plasma for power by a mile correct? Like 2-3x helium?

Too many cost of raw silicon ingots will occupy the mega Blast furnace.
They will be used to make molten silicon.
 Getting raw silicon ingots is a bit harder than "Tin plasma line" ,which should generate more power than Tin plasma.

Maybe the balance above is a bit more OP

The total idea is the rank position of iron plasma should (be between Tin plasma and late Naquadah fuel )

**Comment by chochem** [comment]
No, raw silicon smelting is not hard. Its less than 10k eu per ingot (+36keu arc furnace I guess). That is at best a rounding error in the overall computation.

And one correction on my own guess above: Looking at the datasheet, with a 16x buff iron plasma is not worth 2-3x helium but **5.8x** (per fusion reactor). This is completely out of the question. We are not looking to massively buff fusion or really buff it at all, so I am going to close this.
