### ISSUE TITLE
Natura Redwood Tree Removal 

### ISSUE THREAD

**Issue by thundershock888** [GTNewHorizons/GT-New-Horizons-Modpack#12221]
### Your GTNH Discord Username

Tungstennedge#7364

### Your Pack Version

2.2.8

### Your Proposal

Remove the Natura Redwood Tree Quest from questbook, or add a clear warning not to plant near mainbase. The canopy of this tree is extremely difficult to remove, and can be quite laggy for some players. The lumber axe from tinkers does not remove the canopy, and the leaves and wood are not flammable, leaving little choice for players looking to remove these trees.

My suggestion is to: Remove the quest, or add a clear warning on it. 

Alternatively, make Natura wood flammable like the vanilla leaves so that players can burn down the canopy to dispose of it.

### Your Goal

Stop players from ending up with ugly Natura Redwood treetops near their base that cannot be easily removed.

### Your Vision

I would like to not have players get baited into planting these unremovable trees near their bases, or give players a way to remove these without hours of work manually scything.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Sure we can add a warning. Next requested warning "not put pets in microwave for dry them" :trollface:
