### ISSUE TITLE
Infinity Cell(Infinty Chest Cell)

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/GT-New-Horizons-Modpack#12235]
### Your GTNH Discord Username

dahgul#1726

### Your Pack Version

2.2.0.0

### Your Proposal

![image](https://user-images.githubusercontent.com/35747549/211578409-fe53a2ee-4a9f-4fbc-82f8-935e44be6c22.png)
Add posibility to put(craft) ME Storage Cell equivalent to Infinity chest (or make it part of ME) 

### Your Goal

Connecting the infinity chest to the ME network is inconvenient and creates lags

### Your Vision

Interaction with the stored volume will become much more convenient

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Cinobi** [comment]
Good idea. Infinity chest (or interraction methods with it, more precisely) lags as hell.

**Comment by dahgul333** [comment]
Maybe remake a block as an ME chest with 4 cells 63 type each ?

**Comment by chochem** [comment]
@dahgul333 what is the problem with the ME Quantum Storage and the ME Digital Singularity?

**Comment by repo-alt** [comment]
Storage bus on a infichest lags because it usually have to update the contents very often, it is just a usual storage bus. Just use an ME drive with some infinite cells as said above.
