### ISSUE TITLE
bartworks circuits dont have tier in tooltip

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#12234]
### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

to know what tier they are by mousing over

### The Reality

ha ha colors go brrrr

### Your Proposal

plz fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
not a fix but a personal recommendation, if you want to see the tiers at a glance use a good texturepack, like the usernm pack, see https://github.com/Usernm0/GTNH-Textures-Usernm/releases.
![image](https://user-images.githubusercontent.com/40274384/212435810-1b8c4dc2-fe10-4d45-b954-e7ef835d7b99.png)
