### ISSUE TITLE
NullPointerException in ModularUI when manually adding fluids to a machine

### ISSUE THREAD

**Issue by cubic-chariot** [GTNewHorizons/GT-New-Horizons-Modpack#12239]
### Your GTNH Discord Username

cubic-chariot#3803

### Your Pack Version

2.2.8 + updated jars

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I tried adding refined glue to the fluid slot of an assembler using a universal fluid cell. The game consistently crashes as soon as I click on the slot while holding a cell of refined glue. I get the same results using a large aluminium fluid cell, or when trying to add fluid to any fluid slot, including of tanks.

Updated jars:
```
appliedenergistics2-1.7.10-rv3-beta-133-GTNH-1-g2eaef34.jar
bartworks-1.7.10-0.5.135-2-g971c591.jar
GalaxySpace-1.7.10-1.1.31-GTNH-pre-11-g200b332.jar
ggfab-1.7.10-0.0.11-5-gbddbfde.jar
GoodGenerator-1.7.10-0.4.75-3-g8b36386.jar
gregtech-1.7.10-5.09.41.194-16-g5ade39d.jar
GTNewHorizonsCoreMod-1.7.10-1.9.126-1-g2a48700.jar
gtnhlib-1.7.10-0.0.8-1-g1353f4a.jar
GT-PlusPlus-1.7.10-1.7.184-2-gc02b2b8.jar
modularui-1.7.10-1.0.42-pre.jar
TecTech-1.7.10-5.0.70.jar
```

### Crash Report

[crash-2023-01-10_13.48.27-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10386318/crash-2023-01-10_13.48.27-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
I'm not sure where you got `5.09.41.194-16-g5ade39d`, but it should have been fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1643
