### ISSUE TITLE
Dual avaritia multiblock 

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#12236]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.2.8

### Your Proposal

Add a new multiblock that can make recipes from both the compressor and the dire crafting table, using energy and their respective inputs (if required with circuit it is used)

### Your Goal

- Right now the neutronium compressor is a slow machine that can only make one craft at a time, and having many requires space, especially with all the singularities that exist, with this new multiblock you could make as many singularities at once as inputs have, taking into account that all the necessary materials are present.

- For the autocrafting dire table we have a similar problem, although it is not slow, each one can only make one recipe at a time and automating all or at least the necessary ones requires space and time. Thanks to this great new multiblock with which the ingredients of a recipe are found in an input bus, the desired product will be automatically crafted, obviously using circuits so that there are no conflicts (the parts of the tinkers for example). 

- Obviously filling everything with WAs is out of context, they are a lag machine, for the shape of the blutiblock and its controller I have some ideas...

![image](https://user-images.githubusercontent.com/45178400/211595506-014cae75-119f-48a8-b2b7-3b53bb7e325f.png)
![image](https://user-images.githubusercontent.com/45178400/211598179-39d124c7-935c-4498-93d3-b0a2b5d7df3c.png)
( The infinity block is where you can place the controller)
On the top and bottom is where all the inputs and outputs are, the muffler, and the maintenance hatch,

### Your Vision

I think it is a good improvement for endgame or for those looking to get the stargates, otherwise on servers it will reduce the lag of putting WAs on everything, and although it requires a high cost it is a good investment

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Let better doing a multi for Extremcrafting, Neutronium Compressor in one Block. So we can do all the stuff in one multi and better automate it (include the singularites as well)

**Comment by Dream-Master** [comment]
@kuba6000
