### ISSUE TITLE
ME Interface on a gregtech pipe displays wrong name in interface terminal

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#12230]
### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

So I was sitting here extremely immersed in some gregtech new horizons gameplay, when I opened my interface terminal to put some recipes in. Instantly, I was taken completely out of the blocky world and back into reality at the sight of a "%material item pipe" label; reminding me that this cubed world is not the one I live in :(

![image](https://user-images.githubusercontent.com/13358034/211320517-c2fb1f38-9672-4cd4-a5d7-459aa637c738.png)

### The Reality

%material [type] pipe instead of what its made of

### Your Proposal

fix so i can re immerse myself

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
Seems to be fixed quite a while ago.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/23512002/f55f5dff-7b5d-4b8c-bb61-d3fe3a3ff883)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/23512002/f5a9959a-8a36-438b-a685-6d903fadeb24)
