### ISSUE TITLE
Conduit Improvements

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#12247]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

2.1.8

### Your Proposal

* Fix Item Conduit from connecting to GT wire.
* Modify ME Conduit to permit connecting to AE2 fixtures.
* Maybe make conduits a little bit bigger so easier to place?

### Your Goal

Make conduits better.

### Your Vision

Some QOL fixes for conduits.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Tommeh1** [comment]
I would also suggest to make the fluid conduits at least 10 times faster so they remain relevant past MV

**Comment by minecraft7771** [comment]
> I would also suggest to make the fluid conduits at least 10 times faster so they remain relevant past MV
There are upgraded versions

**Comment by Tommeh1** [comment]
> 

There are far too weak by the time you can make them

**Comment by Tommeh1** [comment]
> > I would also suggest to make the fluid conduits at least 10 times faster so they remain relevant past MV
> 
> There are upgraded versions

There are far too weak by the time you can make them

**Comment by YTXilo** [comment]
if you need faster than eio conduits after mv you are doing something wrong, I had a entire eio fluid conduit network running my base until like iv, when I started to use fluid p2p. and that was with the base ender fluid conduit

**Comment by Tommeh1** [comment]
> if you need faster than eio conduits after mv you are doing something wrong, I had a entire eio fluid conduit network running my base until like iv, when I started to use fluid p2p. and that was with the base ender fluid conduit and even, the recipes are fine how they are, the upgraded conduits are cheap and very good

We simply build big, like the building we're currently raising for our first 8 plasma forges.
But building big shouldn't automatically result in no viable options of fluid transport being available, forcing one to use an even less performant option.

**Comment by Tommeh1** [comment]
Additionally trying to upgrade the conduits is also a pain, you can right click existing ones with better ones to upgrade them, but this leads to problems on any connections where it will appear as if it is connected, but actually ain't, resulting in you have to break all the connectors to inventories, replace them and reconfigure them.

**Comment by YTXilo** [comment]
fluid p2p is more performant than eio conduits, like a lot more performant.

**Comment by Tommeh1** [comment]
> fluid p2p is more performant than eio conduits, like a lot more performant.

From what i saw fluid p2p performed even worse than the conduits, which were eating 25% of the server thread at some point.

**Comment by YTXilo** [comment]
damn what wild stuff are you doing, I had eio conduits destroy tps before, easily taking up most of the servers resources at what one of the highest usage on opis, and my fluid p2p net is extensive so idk how you guys are not getting performant with fluid p2p

**Comment by Tommeh1** [comment]
> damn what wild stuff are you doing, I had eio conduits destroy tps before, easily taking up most of the servers resources at what one of the highest usage on opis, and my fluid p2p net is extensive so idk how you guys are not getting performant with fluid p2p

Everything ME in general performs quite poorly, like it extracting items to craft now taking a constant about 30%

**Comment by shawnbyday** [comment]
Unstale.
