### ISSUE TITLE
Possible memory leak on server

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#12248]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

2270

### Your Server

priv srv

### Type of Server

None

### Your Actions

I noticed that my server gets unresponsive after running for a few days. Tick times are peaking at 5-8000ms and after a while it crashes with JAVA_HEAP error. The server keeps an UHV tier base chunkloaded all the time with ftblib.
My fix for it currently to keep restarting it in 1-2 days.
Im using the following command to start it:
`java -Xms8G -Xmn128M -Xmx8G -d64 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/media/Volume_2/" -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=2000 -XX:+UseCodeCacheFlushing -XX:ParallelGCThreads=4 -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui`

I tried to run it without the fancy -XX options but it feels like it is better if i add them.
I added the HeapDumpOnOutOfMemoryError option and managed to generate the dump file. Hope it helps, I upladed it to here:
[link](https://mega.nz/file/wst2xRqA#ep3M6DVDVGr4eLwvSENMz9gs-hzMzYhVGpqL_fNoc68)
Tried opening it up the dump with eclipse's MemoryAnalyzer but my pc got out of memory exception while reading it lol.

### Crash Report

[crash-2023-01-09_15.37.34-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10395209/crash-2023-01-09_15.37.34-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
official servers are restarted every 12h for a reason: it's near impossible to make sure a minecraft server with 280+ mods have no leak.

**Comment by mitchej123** [comment]
If someone can help track down the leaks, we're happy to help fix them!

**Comment by eigenraven** [comment]
![image](https://user-images.githubusercontent.com/1017004/211914018-71880996-6f1d-4dac-844c-7e02eb56542e.png)
Here is the top consumer. Looks like some mod is using IntCache without resetting it, so it accumulates >6.5million int[256] array objects

**Comment by Alexdoru** [comment]
It's buildcraft that is using the IntCache without resetting it, if anyone knows how to use the IntCache properly and wants to fix it..

**Comment by wohaopa** [comment]
https://github.com/GTNewHorizons/BuildCraft/blob/75d791f8fbbefc6ac9eb1597e418468677c7144d/src/main/java/buildcraft/energy/worldgen/GenLayerBiomeReplacer.java#L58
Indeed, I didn't find resetIntCache() in buildcraft.

 

> It's buildcraft that is using the IntCache without resetting it, if anyone knows how to use the IntCache properly and wants to fix it..

**Comment by eigenraven** [comment]
The buildcraft code looks fine, the minecraft worldgen code resets the int cache before calling that function in `net.minecraft.world.biome.WorldChunkManager`.

**Comment by Alexdoru** [comment]
which dimensions do you keep loaded ?

**Comment by Alexdoru** [comment]
it appears that you don't have fastcraft, that mod might be doing some optimizations, hence why I can't seem to reproduce your memory leak

**Comment by Szajkop** [comment]
I don't have fastcraft installed. This is a server instance, is it works on that too?

For the dims, idk the exact, but the main base is at garden (dim180) and there are a bunch of mining and pumping outposts (around 10-13) spread across the important dims.

**Comment by Glease** [comment]
My server restarts roughly once a month (for updates), and it has fastcraft installed. surely it's a rather low traffic server with at best ZPM bases, but I don't think there is any serious leak going on. 

I thought officials restart was to force unload the passive anchors, no?

**Comment by boubou19** [comment]
server are restarting twice a day for several reasons:
- If there is a memory leak, we flush it twice a day
- That forces 2 reboots per day to unload every tps hungry spots (usually bases, but lag machines too, etc)
- To purge AFK players in not chunkloaded zones.
- To make offsite backups every day

**Comment by Szajkop** [comment]
any updates here finding the cause or fix the for it? I recently upgraded the server to v234 and OOM errors are keep happening after 1or 2 days of runtime. I installed fastcraft but it did not help.
