### ISSUE TITLE
Invar and HSS-G cause a conflict on circuit 1 in mixer creating Nichrome

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#12244]
### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Be able to safely have 1 input bus per circuit number

### The Reality

Trying to do a recipe that requires HSS-G + Invar will create Nichrome and clog the mixer while breaking your request

### Your Proposal

plz fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
there is no actual recipe conflict here correct? you are just doing multiple at the same time.

I think it is unreasonable to expect that any combo of multiple recipes at the same time is conflict free.

Just use blocking mode if this is done with AE2.

**Comment by Hiagg** [comment]
wasnt the purpose of the circuit number thing meant to prevent conflicts to begin with?

**Comment by Dream-Master** [comment]
@Hiagg can you post both recipes here ?

**Comment by Dream-Master** [comment]
we not change HSS-G or Invar between 2.2.8 and the pre dev 2.2.9 version

**Comment by chochem** [comment]
in that case here are the recipes:
hss-g: 
![image](https://user-images.githubusercontent.com/40274384/211863037-f18015bc-1013-4390-bcfa-bca03ef26438.png)
invar:
![image](https://user-images.githubusercontent.com/40274384/211863154-a99c5dde-aa3b-49cd-a3e7-5012efd6447a.png)
nichrome:
![image](https://user-images.githubusercontent.com/40274384/211863232-79e40899-c24d-4524-a64a-c213a476e035.png)

There are no conflicts. What the ticket describes is just some throwing the ingredients for multiple (!) recipes into the machine at the same time and hoping for the best.

**Comment by Dream-Master** [comment]
ok here i cant see any conflict as well.
