### ISSUE TITLE
Change the recipe of Dyson Swarm

### ISSUE THREAD

**Issue by a5632645** [GTNewHorizons/GT-New-Horizons-Modpack#12253]
### Your Pack Version

2.2.8

### Your Proposal

The recipe of Dyson Swarm should be more like an assembly line than a craftTable-like recipe and it has too much duplicate items.

I hope you can change the recipe of it.

### Your Goal

The recipe for Dyson Swarm should be more like an assembly line than a craftTable-like recipe and has too much duplicate items.
![reciple](https://user-images.githubusercontent.com/78687653/212085804-d317f90b-8178-47c2-aa9e-7e666bf18ea5.png)

Too many duplicate items require the player to make these duplicated item have a unique name to make the assembly line work.
![pattern](https://user-images.githubusercontent.com/78687653/212085841-c802a7d6-9e7d-49ee-b3c9-0ba3af764aa3.png)

### Your Vision

The assembly line-like recipe would make the automation more easy and make player more happy.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
well that was the whole point of it: push your automations to its limit to see if you can handle full sized assline.

**Comment by chochem** [comment]
Full size is fine, but clearly these recipes were designed to look good in NEI and not to make any sense in the AL. Just look at the picture above. They put a hatch 'into each corner'. It's a bit ridiculous if you know that the AL is not a square.

**Comment by boubou19** [comment]
Since when order in the AL makes sense?

**Comment by dahgul333** [comment]
no more then 4 type of the same item in recipe pls!

**Comment by Steelux8** [comment]
It breaks the general rule of assline recipes. It's not a problem for gameplay if the 16 slots are meant to be used, it's just a different assline recipe style for no real reason.
