### ISSUE TITLE
Nerf stargate in a simple way

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#12250]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.2.8

### Your Proposal

Add to the recipe of one part of the stargate one item that can only be found in the dream world dim ( from witchery). In this dim you start from 0, you only have to disable personal inventories in this dimension, so people need to find a way to send the item back with a new crafted ender chest or something similar

### Your Goal

Stargate runners need a fast nerf, this will extend the stargate crafting for some months until new nerfs come... 

### Your Vision

Making nerfs a form of life

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
Tedium for the sake of it...
