### ISSUE TITLE
Internal server error when putting Forge microblocks in trash slot

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/GT-New-Horizons-Modpack#12252]
### Your GTNH Discord Username

dahgul#1726

### Your Pack Version

2.2.0.0

### Your Server

Eta

### Type of Server

None

### Your Expectation

![image](https://user-images.githubusercontent.com/35747549/212062605-6ded391c-ed2a-44d5-97df-b334a34d30e5.png)
Trying to put microblock in Wireless termilas's trash slot 

### The Reality

*after click
![image](https://user-images.githubusercontent.com/35747549/212062834-f6a8ffcb-2bbc-466b-821c-846def924089.png)
![image](https://user-images.githubusercontent.com/35747549/212062902-cede600d-43e9-43bc-b554-21c391f4145c.png)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boathouse2112** [comment]
Unable to reproduce on 2.2.0.0. Is there a specific microblock it breaks with?

**Comment by boubou19** [comment]
it happens randomly when one tries to flush more than one item stacks
