### ISSUE TITLE
Allow players to cast lead ingots from smelteries

### ISSUE THREAD

**Issue by 905Sunny** [GTNewHorizons/GT-New-Horizons-Modpack#12251]
### Your GTNH Discord Username

905Sunny#9728

### Your Pack Version

2.2.8

### Your Proposal

Allow players to cast lead ingots from the molten lead in smeltery

### Your Goal

So tragedy like this shall never happen again
![2023-01-12_20 03 51](https://user-images.githubusercontent.com/44795811/212061975-787a7d5d-fdbb-4359-98a2-51c560a6f026.png)
Caption: trying to batch cast the lead nuggets into ingots...

### Your Vision

more nuggets can be melted in the smeltery and casted into ingots

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I dont think we really want to expand on the smeltery use. This is a GT pack and we want to push people to use GT machines as soon as possible.

**Comment by 905Sunny** [comment]
even we can't cast them here, at least let us fluid solidify liquid metal from smeltery in a fluid solidifier

**Comment by Dream-Master** [comment]
we can add it.

**Comment by 905Sunny** [comment]
the nei usage of tinker molten lead is just bucket of molten lead and that's it
