### ISSUE TITLE
Schematica believes 2 slabs stacked is 1 slab

### ISSUE THREAD

**Issue by purebluez** [GTNewHorizons/GT-New-Horizons-Modpack#12268]
### Your GTNH Discord Username

gogy#0779

### Your Pack Version

2.2.8

### Your Server

Zeta

### Type of Server

None

### Your Expectation

tried to print a structure with schematica

expected schematica & its materials list knows the difference between slabs, stacked slabs, and a block

### The Reality

printer mode placed single slabs instead of things that look like blocks, and only asks for a single slab for every double slab block in the Materials tab

this is definitely annoying if youre dealing with building blocks that are hard to get, and dont have a cutting machine yet to perfectly cut them into the 1:2 ratio. 

### Your Proposal

make schematica be accurate and not tell me i need "96 quartz slab" or something when i really need 32 quartz blocks and 64 quartz slabs 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pengu1ns** [comment]
Looking into this one 👀

**Comment by kowonaa** [comment]
> Looking into this one 👀

🎯
