### ISSUE TITLE
Advanced Assembly Line WAILA bug when using >4A MAX

### ISSUE THREAD

**Issue by sintken** [GTNewHorizons/GT-New-Horizons-Modpack#12267]
### Your GTNH Discord Username

sintken#1312

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

None

### Your Expectation

WAILA displays energy usage and parallels/time for AAL; should work normally regardless of power usage

### The Reality

When AAL uses over 8589934592 EU/t (4A MAX, or 1 amp of whatever the next tier is) WAILA shows <ERROR> instead of the expected info. 

![image](https://user-images.githubusercontent.com/72178165/212424486-f2c201a5-a123-4f05-94d4-3b289d114a62.png)
 

### Your Proposal

Make AAL show waila data properly even when using big power

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by sintken** [comment]
turns out QFT has the same issue

**Comment by POPlol333** [comment]
It's working fine for me with 16A max 🤔

**Comment by minecraft7771** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1655
