### ISSUE TITLE
IV mixer quest should be triggered to complete by GT++ mixer quest , or be made into a checkbox

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#12264]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.2.8

### Your Proposal

make the iv mixer quest either a checkbox or detects the gtpp mixer quest

### Your Goal

qol

### Your Vision

qol

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
isnt the iv mixer needed to make the ++ one?

**Comment by LewisSaber** [comment]
you need, as of 2.2.8 at least

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/212375560-ef7ef3cb-4a05-4b98-8985-22d3b52fc130.png)
yep. so this is nonsense. you have to make the IV mixer one way or the other. Cant make IV superconductors and thus IV energy hatches without ever making one. So its all good as a main quest with a proper task. If you use it directly or make the multi is up to you.
