### ISSUE TITLE
ME Stocking Hatch

### ISSUE THREAD

**Issue by IsOobt** [GTNewHorizons/GT-New-Horizons-Modpack#12269]
### Your GTNH Discord Username

oobt#8431

### Your Pack Version

2.2.8

### Your Proposal

I would like for an ME Stocking Hatch to be added to the pack. It will work similar to the Stocking Bus, but for fluids.

### Your Goal

I find it annoying to spam P2Ps and Input hatches on all my LCRs and other multis.

### Your Vision

I think this would improve the pack by making it less needed to spam P2Ps on an AE2 network, and be able to more easily use AE2FC for passive processes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by thecodingchicken** [comment]
Interested to see if anything happens with this issue.

**Comment by trollolal** [comment]
It would be great if main network are able to filter and allocate desired amount of fluid to subnetwork

**Comment by kalenderdose** [comment]
i would totally love this.

**Comment by AltyMan** [comment]
bump

**Comment by MaGeBZz** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/133218866/f68d0d45-0e56-4158-9c01-0242ec995f81)
I would recommend this recipe (input hatch UHV), dual interface, hyper-acceleration cards and quantum tank 3 for the stocking input hatch
Hope that would be an idea to help with that

**Comment by kalenderdose** [comment]
Iimho, this is too expensive and too far into the late game compared to the other hatches. I would place it somewhere in IV. 
Another way would be to make two different hatches, one with multiple fluids in UHV and a single one that could be available earlier in the game.

**Comment by MaGeBZz** [comment]
> 

I think so too, would make the recipe the same as stocking input bus but with a dual interface instead a normal interface
Just talked with dream and he said he wants it UHV or better UEV
Not sure why because it's not a game changing thing in terms of progression but it's a big QOL thing and would really wanna see it finally and eventually not that high like dream wanted

**Comment by kalenderdose** [comment]
Currently, you are able to use a `Quadruple Input Hatch` (available at EV) in conjunction with an `ME Fluid Export Bus` and a `Capacity Card`. In my opinion, this new Hatch not offers a substantial QOL improvement but significantly reduces lag on servers.

**Comment by MaGeBZz** [comment]
@kalenderdose but for that it's more lag efficient what is enough to say we need it
And not only that you could have more than 4 fluids too for recipes that need maybe 5 fluids (not sure if there's a thing rn) and you didn't have to put it in the hatch for real it's in your system and the machine at the same time so I think and a good amount of oter people, that it is pretty useful

**Comment by Sopel97** [comment]
Without this hatch there is no way to split work between multiple machines in a robust way.
