### ISSUE TITLE
Make saltwater require a circuit

### ISSUE THREAD

**Issue by Datryum** [GTNewHorizons/GT-New-Horizons-Modpack#12274]
### Your GTNH Discord Username

Schnils#1542

### Your Pack Version

2.2.8

### Your Proposal

The saltwater Mixer recipe doesn't require a circuit, which causes the Multiblock Mixer to get stuck on the saltwater recipe if both are provided. 

### Your Goal

I discovered this when crafting all of the Monaline Mixer recipies in one multiblock mixer, which isn't currently possible due to this issue.

### Your Vision

It would be a way to remove some recipe conflicts, which is a great QoL improvment. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
I tagged this with GT++ because it concerns the mixer multi. I'll check it out.

**Comment by chochem** [comment]
this is not related to ++, just a recipe in gt. the multi one generates from there
