### ISSUE TITLE
I cannot start the modpack. I have mod issue(s). 

### ISSUE THREAD

**Issue by Roaring1** [GTNewHorizons/GT-New-Horizons-Modpack#12272]
### Your GTNH Discord Username

Roaring#4449

### Your Pack Version

2.2.0.0 (? I'm using the latest)

### Your Server

SP

### Type of Server

None

### Your Expectation

Alrighty. SO, I open the curseforge launcher, been watching threefold play forever and was thinkin other games were getting boring, so I'd give GTNH a try. I go into the launcher, browse and install the latest version of 'GT New Horizons', the modpack for it.

SO, I install it, run it, it all seems well, then install the mods on the first launch, then I go to launch it again TO PLAY IT. Then , I 
get an error. 

![image](https://user-images.githubusercontent.com/110640405/212449410-35c8fdc0-7efe-4f7f-9a88-950f8c07b49e.png)

Basically, It (the game) think's thaumcraft's version is incorrect. But ... 
It is in the mods folder. I see it, correct version, etc., _remember, this is a completely fresh install. _

I see the file is named, I forget the exact name, but I see there's a 'a' character at the end of the mod file, and the supporting mod file. for example , I think it said something like "Thaumcraft-1.7.10-4.2.3.5a.jar" ..
 well I removed the 'a' character form the supporting, and main mod file.
I go to launch it again, the same exact result. 
I think, "oh.. no."
I do a new install. 
same thing. 
then I do it again, slightly older version. 
SAME THING.
I wait overnight, do a new install, .. same error. 

I searched on google LAST NIGHT and replace the mod (Thaumcraft;  downloaded from ' 
 https://mediafilez.forgecdn.net/files/2227/552/Thaumcraft-1.7.10-4.2.3.5.jar  ') 
associated with it. Now it gives new mod errors. 
I'll actually do it again right now. It gives: (image) NEI, and Forestry. 

![image](https://user-images.githubusercontent.com/110640405/212449821-609ea43a-169f-4a5a-8d9f-e1bad90aacea.png)

This time, I'm like _"what the hell. I'm done."_ So, I go to sleep and cry.  
So, now im sitting here with a error on this pack. I wish and have wanted for a couple days to play it , but no. 

_Just text me on discord, I'll probably not reply here. Thanks._

Crash report attached. from fml-client-latest.log , like the text said. 

### The Reality

my bad, don't use this site I did it incorrectly ill .. 'simplify it' 

game no launch and game no work. :ang

### Your Proposal

Game launch and work. :happy

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Roaring1 which launcher you use?

**Comment by chochem** [comment]
it says curseforge. Also says they want an answer on discord so I wrote them there.

**Comment by Roaring1** [comment]
@chochem where do I find this ?

**Comment by Roaring1** [comment]
sorry I don't use this site

**Comment by chochem** [comment]
lol so you dont want discord after all but do come back here. I just wrote:

we try to support curseforge launcher but it's not easy for packs with lots of custom mods and it breaks all the time. Though I am really not sure what happened in your case. The crash report is not actually in your post.

Our general recommendation is to use Technic launcher (very easy) or Multimc (relatively easy, gets more regular updates). See https://gtnh.miraheze.org/wiki/Installing_and_Migrating.

And just ask more here (discord help channel) if you are having trouble. 🙂
