### ISSUE TITLE
Some Re-balancing Idea about Extreme Extermination Chamber

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#12289]
### Your Pack Version

2.2.7

### Your Proposal

1. Reconsider the position and usage of this machine.
a. It is a machine that produces items which can only be dropped by mobs, which means some items should be removed from its recipe, like sugar and redstone.
b. It is a machine that produce a huge amount of basic vanilla resources in the later stage, which means it doesn't need change.
2. Limit its parallel and the level of Looting it supports. 
2.1. I have no idea about how to limit its parallel. Link it to the sharpness level or thd damage the weapon has could be an idea. 
e.g. It could have n(or 2×log<sub>2</sub>(n+1)) times of perfect overclock or 4/4 parallel, where n is the sharpness level.
2.2. It shouldn't accept a weapon with a level of looting beyond a specific limitation. Looting X may be a reasonable limitation.

### Your Goal

1. Many players use EEC to produce sugar, snowball, meat and other items. EEC steals work that should belong to other machines, such as sugar from Greenhouse multi, snowball from Compressor, fish from Zhuhai Fishing Port, which does not help us to encourage players to build diverse factories.
2. Now the EEC has a ridiculous amount of output. Over 100 stacks of item in a single tick is unreasonable. Many players use a bug from the Overchanting Table to get a Diamond Spike with Looting 100, 1000 or more, though it would be a long process. Looting is good but too high level of looting will destroy the balancing of game. So as parrallels. I think Looting X or 20 is a sound level, which allows players produce items in a relatively quick speed. The same process could be operated on Sharpness but I think it won't have such a effect compared with Looting. The idea that 2×log<sub>2</sub>(n+1) times of perfect overclock or 4/4 parallel is also aimed to limit overchanting. If you want more parallels, you have to enchant your diamond spikes with a ridiculous level of Sharpness. That's fair, isn't it?
By the way, I think that fixing the bug Overchanting Table has isn't a good approach to rebalance EEC. Looting 3 is far from enough.

### Your Vision

Encourage players use a variety of method to get the item they need instead of making a lot of EEC.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
Regarding the variety of drops from the EEC, I don't see this as a flaw, more as a benefit to the pack as a whole. Pushing players to build one machine for each setup increases lag, and the examples you gave are all early game items. I don't see why a single lategame multi can't just output them all.

**Comment by cainiaojun** [comment]
> Regarding the variety of drops from the EEC, I don't see this as a flaw, more as a benefit to the pack as a whole. Pushing players to build one machine for each setup increases lag, and the examples you gave are all early game items. I don't see why a single lategame multi can't just output them all.

If it's a lategame machine, that's reasonable. But EEC can be made in EV and the Looting 1000 Spikes can be made at the same time, which means players could get thousands of items easily. My ideas are immature and need more consideration, but I think there must be an approach that could limit players in EV or IV and doesn't affect lategame players. 

At least I think the Looting 1000 is not fair. It easily increases EEC's output without more energy and it is too easy to get.
