### ISSUE TITLE
Industrial 3D Copying Machine Idling

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#12283]
### Your Pack Version

2.2.8

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

I do some wrong operation.
I put some vanilla glowstone in the input bus and forgot to put some chisel glowstone in the machine as templates.

### The Reality

It idles. It didn't consume those glowstone(it is the first item in the chisel page) but consume electricity pointlessly.

### Your Proposal

It shouldn't work.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment]
Can no longer reproduce this, looks to have been fixed by https://github.com/GTNewHorizons/GTplusplus/pull/638
