### ISSUE TITLE
Botania integration to the pack

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#12282]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.2.8

### Your Proposal

Replace some of the items used in basic thaumcraft recipes with botania materials and vice versa 
- String of the tallow candle for mana infused string ( tallow are kinda decorative, but this change make sense in a lore way)
- Manatide bellow leather for arcane below
- Arcane lamp glass pane for managlass pane advanced recipe, giving you 2
- Warded Jar glass pane for managlass pane, same for Thaumium reinforced jar, Tally box lens clear, Thaumic Iconograph, Mirrored glass, Fume filter, and all thaumic horizons lens
- Ichor Jar glass pane for alfglass pane
- Blood Stained glass glass for managlass
- Enchanted fabric cotton and string for manaweave cloth and mana infused string ( make this and advanced recipe that gives you 3 enchanted fabric)
- Silky cloth string for mana infused string
- Add mana infused string to the bewitched fleece recipe ( to add another magic string to the recipe)
- Change blaze, lavender, red and sunny quartz quartzs to mana quartz
- Miser´s pearl, weak orb, attuned stone, memory block, the two kettle diamon recipes, poppet shelf, pentacle, null catalyst? ( maybe) and runed obsidian diamond for mana diamond ( substituting a vanilla diamond for a magic one in a magic recipe, also makes much more sense in the attuned stone)
- Runed obsidian and wand focus-fire quartz to blaze quartz
- Wand focus frost, excavation and warding quartz to mana quartz
- Wand focus shock and feline amulet quartz to sunny quartz
- Wand focus equal trade quartz to botania smokey quartz
- Wand focus nine hells and diabolist fork quartz to redquartz
- Pure tear to mana or elven quartz
- Bottle of enchanting bottle to mana in a bottle
- Celestial pearl ender pearl to mana pearl
- Add final botania items to the avaritia armour and tools recipes at least this: Terra shatterer SS, Starcaller and thundercaller, terrasteel armour, or nebula armour from the advanced botany armour 
- Add a recipe for a catalyst that consumes all oe some of the gaia relics but can give a recipe for gaia spirit: catalyst (not consumed) + 9 blocks of terrasteel + one of each rune = 1 gaia spirt ( is tedious to kill gaia in a modpack that you can automate all)
- Change one mana powder from the Beegonia recipe to magic wax
- Make that botania flowers can spawn at Thaumcraft magic forests

### Your Goal

At this point botania is not so integrated into the pack, this will make players use it more and they will sugest some more ideas to integrate it more, we have to start fropm something

### Your Vision

Make players use some more of the botania contents, so maybe they like it instead of hating botania without trying it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by cubic-chariot** [comment]
Another thing is the alchemy catalyst transmutation cycles. For example, there's a cycle with all vanilla flowers which could be expanded to include Biomes O' Plenty flowers. The saplings one could include Biomes O' Plenty and Natura saplings. The foods one could also include foods from Pam's Harvestcraft. The fish one could include Pam's fish. A new cycle could be created involving only fruits from Pam's saplings. And so on.

**Comment by EnderProyects** [comment]
Add the cocoon of Caprice ( a block that acts like an spawn egg) to the recipe of the "The big egg" also because it uses a dragonstone in its craft and the last thing in the line of the egg is the dragon egg

**Comment by LazyFleshWasTaken** [comment]
spawn eggs are renewable, the mother spider and mother cave spider drop spider spawn eggs and cave spider spawn eggs respectively, even in a EEC.

**Comment by EnderProyects** [comment]
> spawn eggs are renewable, the mother spider and mother cave spider drop spider spawn eggs and cave spider spawn eggs respectively, even in a EEC.

Oh, I didn't know that, well if then it could also be implemented as a substitution of the spawn egg, and well since the cocoon isn't cheap to make, doesn't break progression

**Comment by EnderProyects** [comment]
Change lore and uses of the pixie dust, dragonstone, elementium. And make them lore correctly
- (lore) We have send some random items to the Dev-lves and they thank us with these strange pink objects, we should investigate them more (ask for one of each in a quest)... After further analysis they appear to be a magically enhanced version of our mundane items. ( change the recipe of the Elementium ingot to give you a Elementium gear that you can then melt to get the ingot)

- Dragonstone: (At first we thought it was a worthless gem, but seeing it up close it looks like a magic crystal, from a monster maybe... it seems as if it thinks and can process information... Now there's no doubt it's a dragon magic stone) Use it as a IV circuit for some magic themed recipes ( Grandmaster magic energy absorber, thaumium Omnitool, drill, chainsaw, and Quantum googles of revealing)

- Pixie dust: (When they asked us for sunnarium we did not think that they would return it to us something in the form of pink powder, it is nothing like what we have seen before, we will keep it for future use anyway) Dont change any current recipe but keep it in mind for a future use in solar pannels maybe... Make a recipe for the pixie in a jar from biomes o plenty...

- Elementium "gear": ( This seems like a good deal, they have returned a gear that is not only more resistant, but I see that it channels the magical and elemental power of the earth, and it seems more malleable. I wonder if we can melt it into other things) Use it as a gear in some magic tier recipes idk

**Comment by EnderProyects** [comment]
Gregteching some crafts:
- Change or make assembler recipes: All the grass tipes using their own seed and 8 of dirt gives you 8 of them ( Dry, Golden, Vivid, Scorched, Infused, Mutated, and Enchanted soil, this last gives you 4), change to assembler recipe the Shimmerrock and Shimmerwood recipes, add recipes for all the red string components using two of livingrrock instead of 7, same for the mana void ( change the obsidian for a obsidian plate) and mana detector, add recipes with circuit number for all the azulejo recipes, add a recipe for the ender air bottle (mana in a bottle+mana pearl+catalyst/ dragon egg, not consumed), manufactory halo

- Change or add materials of recipes: Alchemy catalyst brewing stand for chemistry set, Unstable cube mana pearl for unstable ingot, mana pump bucket for any electric pump, change mana storm charge recipe to livingwood and molten gaia in a electric implosion compressor, manatide bellow leather for arcane bellow, add redstone root and redstone soup to the red string recipe and change the string inside for a mana infused string, change hovering hourglass mana glass for mana prism, use plates or gold blocks for the golden laurel crown and charm of the diva... but no ingots xd, add a recipe for the hand of Ender using the Enderlinked bag because this item can be very usefull with the rod of shifting crust, change the chest of the bauble case and the flower pouch midle for a focus pouch,  add a recipe for the Botanurgist Inkwell using the crystal inscribing tools, change the terra blade of the starcaller for a thundercaller.

- Make all botania armour equipment in an update progresion, using the materials from one to the next: Manaweave > Manasteel > Terrasteel > Elementium >>> Random tiering in avaritia

**Comment by Alastors** [comment]
Closing because 1. Stale and 2. We are going in a vastly different direction in the integration
