### ISSUE TITLE
Add turbine shaft to XL turbine tooltips

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#12288]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.2.0.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

Getting correct build instructions for making the XL plasma turbine

### The Reality

Autoplace stops halfway on an unknown block without any information in either chat or tooltip which block is needed

### Your Proposal

Add `Turbine Shaft` with the appropriate usage count to the tooltip of the XL turbines

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/448
