### ISSUE TITLE
Extreme Extermination Chamber rendering issues

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#12291]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The Multiblock should render the internal blocks correctly

### The Reality

![2023-01-14_16 59 28](https://user-images.githubusercontent.com/13187606/212631405-fdb12893-e9fe-4957-8e73-27a415e1c5f1.png)

When placed into the chamber, the Diamond Spikes do not render and instead cause the blocks below to become transparent. Additionally, the Borosilicate Glasses also cause some top layer blocks when viewed from below to also become transparent.

The schematic for the multiblock also shows the Diamond Spikes facing downward, when the multiblock needs them facing upward.

### Your Proposal

Fix the rendering issues.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Quaerere-Git** [comment]
I have encountered the same issue after viewing the structure page in NEI.

**Comment by Quaerere-Git** [comment]
Large sifter is also affected.
The bug seems to be associated with NEI since the issue never happen until viewing the "Multiblocks Structure" page in NEI.

**Comment by nhouser9** [comment]
Same thing happens for me.
