### ISSUE TITLE
Mana Pool Multiblock ( botania integration)

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#12297]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.2.8

### Your Proposal

Add a multiblock to be able to process recipes that use mana in a possible endgame or advanced after gaia, that does not require throwing items into a pool and that uses a solid mechanic.

### Your Goal

 Starting with the fact that botania has to be integrated into gtnh somehow, I suggest the following multiblock and its controller
- It uses the mana tablet durability and extracts empty mana tablets from the output like the rest of the recipe, taking into account that every two mana tablets are equivalent to the capacity of one mana pool
- Changing the type of recipe with its appropriate circuit you can make 4 types of recipe, normal, alchemy, conjuration, and the one suggested in my other post of the chance of gaia spirit. (very useful in alchemy and conjuration as you can craft exactly what you want without cycling from one item to another or having thousands of redstone causing lag, duplicating on the ground)
- The more energy you put into it, the more recipes it will make at the same time, but the mana consumption will remain the same, so be careful, you better try using the creative mana tablet... ( The only item in a mana pool will be mana tablets, or no if a certain addon gets implemented that add a block that can charge items for mana of a near mana pool)

![image](https://user-images.githubusercontent.com/45178400/225707596-9106ebb3-2f36-4c2e-96af-b7d37a8ce350.png)
Ev mixer and autoclave, mana distribution objects

- Multiblock: the controller should go where any of the terrasteel block is placed
![image](https://user-images.githubusercontent.com/45178400/225697139-5667381a-b8a3-4cdd-90dd-32585a289b34.png)

### Your Vision

I think it's a good improvement for those who want to reduce lag, apart from the fact that it opens the door to using recipes that use mana or implementing a system that uses fluids at the same time, for example, one fluid + mana is converted into another, or directly being able to use mana in fluid form to move it

 PS terrasteel and recipes using elven trade are out of this usage for certain reasons

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
Seems janky af

**Comment by Alastors** [comment]
Also the recipe seems insanely excessive for the usefulness of botania as it is now.

**Comment by EnderProyects** [comment]
Its a proposal of a mechanic more than an idea for the goodlooking of the machine

**Comment by LewisSaber** [comment]
What if u gather all of your tickets in 1 document where you describe why need certain things, nobody will go through all your tickets to gather parts of information

**Comment by Alastors** [comment]
> > > > Also the recipe seems insanely excessive for the usefulness of botania as it is now.
> 
> > > 
> 
> > > 
> 
> > > Thats why I´m trying to make botania more usefull
> 
> > 
> 
> > Yeah, but it needs to be useful first before you start throwing in multis that are way past the current use tiers of botania, this would be like adding a UEV thaumcraft multi out of the blue
> 
> 
> 
> Let's see Alastor, don't play dumb, I have several issues open at the same time with what I want to do with botania and the things I want to change and integrate, if I propose the multiblock it's for a reason, and more than anything we just talked about it for discord, you don't need to duplicate the messages

I've not been made aware of these, I memorize thaum information not every ticket that's ever existed

**Comment by Alastors** [comment]
From what you have here, it looks like you're just proposing a one off multi that looks bad, will be a bitch to implement, will be useless by your own admission, is too expensive, and only performs using extremely janky mechanics that are unnecessary in the face of better systems

**Comment by EnderProyects** [comment]
> > > > > Also the recipe seems insanely excessive for the usefulness of botania as it is now.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Thats why I´m trying to make botania more usefull
> > 
> > 
> > > 
> > 
> > 
> > > Yeah, but it needs to be useful first before you start throwing in multis that are way past the current use tiers of botania, this would be like adding a UEV thaumcraft multi out of the blue
> > 
> > 
> > Let's see Alastor, don't play dumb, I have several issues open at the same time with what I want to do with botania and the things I want to change and integrate, if I propose the multiblock it's for a reason, and more than anything we just talked about it for discord, you don't need to duplicate the messages
> 
> I've not been made aware of these, I memorize thaum information not every ticket that's ever existed

I mean, I just talked to you about what the purpose of this multiblock would be, and you came here to say the same thing.
 I don't understand xd

**Comment by EnderProyects** [comment]
> From what you have here, it looks like you're just proposing a one off multi that looks bad, will be a bitch to implement, will be useless by your own admission, is too expensive, and only performs using extremely janky mechanics that are unnecessary in the face of better systems


Do you know what a proposal or an idea means that is more due to the mechanics and not due to the multiblock shape?

**Comment by Alastors** [comment]
But as I said there, Advanced Botany will already be doing most of the features here, the only feature present here that isn't in botany would be insanely easy to add in comparison to this

**Comment by EnderProyects** [comment]
> But as I said there, Advanced Botany will already be doing most of the features here, the only feature present here that isn't in botany would be insanely easy to add in comparison to this

Advanced botany doesnt solve any of the references here advanced botany solves charging and agglo the proposed multi is for infussing

**Comment by EnderProyects** [comment]
> > > But as I said there, Advanced Botany will already be doing most of the features here, the only feature present here that isn't in botany would be insanely easy to add in comparison to this
> > 
> > 
> > Advanced botany doesnt solve any of the references here advanced botany solves charging and agglo the proposed multi is for infussing
> 
> You've said you intend for this to be a 4 in 1, so literally adding one more machine to advanced botany is a better use of our limited time than implementing this as noted

The 4 in 1 I mean because there are 3 tipes of infussing, and then the proposed recipe for gaia

**Comment by Alastors** [comment]
> > > > But as I said there, Advanced Botany will already be doing most of the features here, the only feature present here that isn't in botany would be insanely easy to add in comparison to this
> 
> > > 
> 
> > > 
> 
> > > Advanced botany doesnt solve any of the references here advanced botany solves charging and agglo the proposed multi is for infussing
> 
> > 
> 
> > You've said you intend for this to be a 4 in 1, so literally adding one more machine to advanced botany is a better use of our limited time than implementing this as noted
> 
> 
> 
> The 4 in 1 I mean because there are 3 tipes of infussing, and then the proposed recipe for gaia

Do we really need a special new recipe style for literally one item

**Comment by EnderProyects** [comment]
> > > > > But as I said there, Advanced Botany will already be doing most of the features here, the only feature present here that isn't in botany would be insanely easy to add in comparison to this
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Advanced botany doesnt solve any of the references here advanced botany solves charging and agglo the proposed multi is for infussing
> > 
> > 
> > > 
> > 
> > 
> > > You've said you intend for this to be a 4 in 1, so literally adding one more machine to advanced botany is a better use of our limited time than implementing this as noted
> > 
> > 
> > The 4 in 1 I mean because there are 3 tipes of infussing, and then the proposed recipe for gaia
> 
> Do we really need a special new recipe style for literally one item

1 item? there are 165 mana pool recipes, not many, for now

**Comment by AlexisGoblot** [comment]
let's chill a bit ok? Github isn't supposed to be used as a discord chat. If you want to discuss about the issue with such a high frequency, you may as well want to talk about it on discord. Discussion on tickets is to add valid contributions to the ticket subject.

**Comment by Alastors** [comment]
> > You're proposing a completely new multi just for Gaia crafting
> 
> 
> 
> I am proposing a new multi for all the recipes that consume mana, there is literaly a multi for 3 items for draconic evolution xd, 
> 
> 

That doesn't make it necessary or good content

**Comment by Alastors** [comment]
Closing due to 1. Stale, 2. I am actually working on a similar thing in Botanic Thaumaturgy
