### ISSUE TITLE
Logistics Power Junction EU from wires

### ISSUE THREAD

**Issue by KhonaB** [GTNewHorizons/GT-New-Horizons-Modpack#12299]
### Your GTNH Discord Username

Khona Betwanhe#7122

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Attached a logistics power junction to a GT cable (with a generator on the other end), expected it to charge like it does when adjacent to a generator.

### The Reality

It does not charge when connected to a cable, only when touching a generator block (or presumably battery buffer/transformer)

### Your Proposal

Implement whatever fix was presumably needed to connect to the new reduced-lag EU network system for other non-GT blocks. I'm guessing this was just an oversight because nobody uses LP.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Can't reproduce anymore since nightly 2023-06-22

![2023-06-22_18 02 13](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1928113/4aa9d06a-dff3-4752-9ecd-2b66bd7cd103)
