### ISSUE TITLE
Recipe conflicts that need fixing

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12300]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.2.9-2-dev-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

@D-Cysteine introduced me to a nice ingame debug tool, https://github.com/D-Cysteine/nei-custom-diagram/wiki/Diagrams#gregtech-recipe-debugger, to check the game for recipe conflicts. This is a collection of the most relevant ones, feel free to check it out yourself!

### The Reality

Here are the relevant ones:

- [x] obsidian chest and compressed chest (from obsidian) in the assembler with circuit 2. might make obsidian chests even if one wants to do compressed ones.
- [x] bomb fuse vs net or egg box, all three in gt++
- [x] rock salt electrolysis (auto gt) conflicts with the electrolysis of rock salt+lithium chloride + air (gt++). If trying the latter one might do the former. Maybe best move that to a different machine?
- [x] same with potash vs potash+spring water+lithium chloride
- [x] cryolite electrolysis has 2 different recipes with differing EU amounts
- [x] zeolite electrolysis has 2 different recipes with differing EU amounts and outputs
- [x] ethylene and benzene to ethylbenzene (gt++) vs ethylene and benzene to styrene+hydrogen (should add a circuit to the former!)
- [x] 2 phosgene recipes from lanth that only differ in one having a circuit (not really a conflict)
- [ ] neutron accelerator IV vs conveyor belt IV in assembler
- [ ] neutron accelerator EV vs conveyor belt EV in assembler. This is https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9863, apparently it was never actually fixed.
- [x] smooth sandstone vs Roen (ztones)
- [ ] crafting logistics pipe vs logistics crafting table (2 recipes for that one)

another part of the debug tool lists cell descrepancies. The relevant ones are:

- [ ] 2-tert-butyl-anthrahydroquinone in a SB CR loses 10 cells (lanth)
- [x] formaldehyde in a SB CR loses 3 cells (lanth)
- [ ] phthalic anhydride dust in a SB CR loses 1 cell (lanth)

### Your Proposal

help me fix them :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by riking** [comment]
lithium chloride would definitely make sense in a chem reactor

**Comment by norbby42** [comment]
Just came here to report the Fluorite Dust electrolyzer recipes.  The circuit 1 recipe is HV, 5 sec, and 480 UE/t voltage.  The no-circuit recipe is MV, 10 sec, and 60 EU/t.  Under no circumstances should the circuit 1 recipe be used.

**Comment by serenibyss** [comment]
Going to remove the GT++ label from this issue since its listed recipe conflicts have now been resolved

**Comment by AdolMors** [comment]
I see that circuit 1 has been added to LCR ethylbenzene recipe using 2000L ethylene + 2000L benzene. However, I found the recipe is impossible while playing in 2.4.0. This is most likely caused by LCR styrene recipe using 1000L ethylene + 1000L benzene with NO circuit.

**Comment by chochem** [comment]
oh nice, that was probably suppressed from the collision before, will have a look
