### ISSUE TITLE
Thorium-232 ingot can't be made from non-radioactive Thorium-232

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#12303]
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I've been making thorium reactor.
It requires 2 radioactive plates. To make a plate, I need an ingot.
If I take a non-radiactive thorium-232, I can not make an ingot out of it.

### The Reality

I have to make a specific radioactive version of dust, then make an ingot and a plate.
If I accidentally put radiactive version into ME, it will make it non-radiactive and I need to start from the beginning.

### Your Proposal

It should be possible to make a Thorium-232 Ingot from a Non-radiactive version of Thorium-232 dust.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
so the LFTR is uncraftable.

**Comment by joshaup1999** [comment]
> so the LFTR is uncraftable. I guess because the furnace recipe doesn't use oredict.

More like unify the bloody BW and ++ materials that are the same since neither original dev is around to continue the pissing contest

**Comment by chochem** [comment]
well, thats what oredict means in a way.

A full redo and actual unification of all those materal definitions will maybe have to wait until the new Material API materializes.
