### ISSUE TITLE
Make Industrial Apiary Climate Upgrades Available Earlier

### ISSUE THREAD

**Issue by Dunkle-P** [GTNewHorizons/GT-New-Horizons-Modpack#12306]
### Your GTNH Discord Username

Dunkle#7836

### Your Pack Version

2.2.8

### Your Proposal

Reduce the technology gate for climate control in the single block Industrial Apiary to a lower voltage tier (HV or EV?). Specifically the Dryer, Humidifier, Cooler, and Heater Upgrades.

### Your Goal

Currently the single block industrial apiary upgrades for humidity/temperature control require the climate control module from Gendustry. This item requires an LuV motor and hence requires assembly line in addition to combs from relatively late in the breeding trees. This makes the industrial apiary an unreasonable alternative to the alveary at the tier where it becomes first available (HV, however most upgrades require platline components so it's mostly an EV machine in practice) for use with bees that aren't accustomed to climate of your base. Reducing the gate would help make these usable earlier, even though they are still somewhat worse than an upgraded alveary until higher tier apiary upgrades can be obtained.

### Your Vision

This would provide a way to use bees that are climate sensitive earlier on without having to place the bees in awkward locations. Especially considering the climate control upgrades for the alveary are inconsistent and buggy when used with hygroregulators. (see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11782, this is still occurring as of 2.2.8).  

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alrightsc** [comment]
@Runakai1 is already planning to look at/tweak the upgrade balance again so that they don't need the platline materials, but it's still up in the air as he wants them to cost some of the combs from bees so that you're forced to do some more breeding. Ideas are welcome here in adjusting those. I agree that the upgrades needing osmium/palladium and LuV parts for a HV machine is silly because they effectively make it IV-LuV+.
