### ISSUE TITLE
NEI Schematic Tool has wrong tiers for ExxonMobil Chemical Plant

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#12301]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The tool should correctly match up casings with tier.

### The Reality

Currently these seem to be incorrect.
![Thorium](https://user-images.githubusercontent.com/13187606/212786215-2fdb504f-d9d6-4cf7-983b-f6041f4c0b0f.PNG)
![ChemicalPlant](https://user-images.githubusercontent.com/13187606/212786220-3bb61c64-41db-4fcc-9c07-2cbe20c0486c.PNG)

The recipe listed here calls for Tier 4, but the Schematic Tool says Tier 4 needs Stainless Steel rather than Titanium, and the recipe does not work in this configuration due to Titanium casings needed.

### Your Proposal

Fix the tool so that the Tiers and their materials are properly respected

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
blockrenderer starts counting with 1 but the tiers start with 0.

**Comment by chochem** [comment]
it also shows incorrect numbers of catalyst hatches

**Comment by chochem** [comment]
and it meshed all the tiers together.

**Comment by chochem** [comment]
the last is a general problem by the way. For example MBF has the issue too and precise assembler

**Comment by chochem** [comment]
if that is changed on the gt++ side, then the book (done), questbook, and wiki need changing too.
