### ISSUE TITLE
Electric Implosion Compressor do not recheck structure if upper half changed + Volcanus tooltip and forming without pyrotheum heating vent

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#12307]
### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Electric Implosion Compressor to form when using 2 super busses for input. It does however, form with 1 super input and more normal inputs. 

For Volcanus to not form without a pyrotheum heating vent to prevent accidental voiding of items and confusion for first time users about where to insert pyrotheum. It also doesn't mention the heating vent in the tooltip at all so without checking the quest specifically there is no indication of needing it.

### The Reality

EIC doesn't form with 2 spuer busses

Volcanus forms and allows function without pyrotheum heating vent, and will just void most outputs if you use auto maintenance hatches.

### Your Proposal

plz fix 😔 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hiagg** [comment]
ok actually something else seems to be wrong here. i the setup is, form the EIC with both energy hatches, one on bottom and top, then remove one (top in my case) and the EIC stays formed. but then trying to alter the structure further breaks it until you re-place the controller.

**Comment by Glease** [comment]
Please submit one bug per issue. This makes it a bit hard on our side.
