### ISSUE TITLE
Add blast furnace function to DTPF

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12315]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.8

### Your Proposal

Add blast furnace function to DTPF
给DTPF加入高炉模式

### Your Goal

In the current version of the game, there is an increasing demand for post-firing metal ingot，Giant blast furnaces can no longer handle the amount of metal powder，We need blast furnaces that can handle more table at the same time，I think we can add blast furnace mode to DTPF，You can switch with the tool to get a blast furnace that performs 8192 synthesis tables simultaneously

在游戏后期中，烧制金属锭的需求越来越多，巨型高炉已经无法处理大量金属粉，我们需要能同时处理更多合成表的高炉。我认为我们可以给DTPF加入高炉模式，通过工具进行切换来获得一个同时进行8192个合成表的高炉

### Your Vision

Later we don't need to do a lot of repeated synthesis of giant blast furnaces，We can focus more on other production line machines，And a small amount of machines can significantly improve our game flow in the latter stages

后期我们不需要进行大量重复的合成巨型高炉，我们可以把精力放在其他机器上，并且少量的机器可以显著提高后期的流畅度

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by cainiaojun** [comment]
I support this idea.

**Comment by Connor-Colenso** [comment]
This will not happen, the DTPF does not exist as an EBF replacement, merely a subsidised alternative to some EBF recipes along with a few extra recipes. Future multis will fill this role post UXV in all likelihood.
