### ISSUE TITLE
About the nerfing of lightning rods

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12314]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.8

### Your Proposal

The lightning rod is too strong in the current version，It is cheap to build and easy to automate at high power levels，It should reduce power generation or increase production and maintenance costs，For example, putting him on an assembly line instead of a workbench limits his early appearance。
Replacing iron railings with other materials, such as superconducting wires at various voltages, increases the overall cost and makes lightning rods more reasonable

### Your Goal

Lightning rods generate too much power in the game，He can even replace all of EV-LUV's generators，Just go online and copy a code that automatically changes the weather，In this way you can get up to UV level power generation in LUV。

### Your Vision

Nerf the lightning rod to better reflect the characteristics of other generators，It also increases the depth of exploration in EV-LUV

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
better discuss on the existing ticket https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10462
