### ISSUE TITLE
Existing item filter got broken in the latest versions

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#12316]
### Your GTNH Discord Username

Keyla#3300

### Your Pack Version

2.2.8

### Your Server

Own server

### Type of Server

Ultramine

### Your Expectation

Tried to use existing item filter in a conduit

### The Reality

Buttons in the opened conduit do not work. it is still possible to use conduit by clicking on a chest or placing in a crafting grid for clearing

### Your Proposal

Remove or fix ui buttons of an existing item filter

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
these guis are relatively new backports I think.

some of the buttons work: show, blacklist/whitelist, etc,
but others do not: clear, snapshot, merge
![image](https://user-images.githubusercontent.com/40274384/217364806-f24b3bce-2e49-4738-b1e4-ec88da7e9f81.png)

@eigenraven you backported this, correct? Maybe you have some clue immediately.

**Comment by eigenraven** [comment]
It's possible the button ids got messed up for this (previously there was 1 set of ids, now there are 2 because they can appear on both the left and right sides)
