### ISSUE TITLE
Assembler recipes for GT++ bee frames

### ISSUE THREAD

**Issue by Gofer2x** [GTNewHorizons/GT-New-Horizons-Modpack#12317]
### Your GTNH Discord Username

Gofer#5776

### Your Pack Version

2.2.8

### Your Proposal

Add Assembler recipes for the GT++ bee frames. Accelerated, Working, etc.

### Your Goal

Most other useful Carpenter recipes (vanilla Forestry frames, Apiary parts) got Assembler recipes so the GT++ frames should as well. They probably just got missed cuz lol GT++.

### Your Vision

Feature parity/consistency, dunno I just hate Carpenters.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Hikari1nVoid** [comment]
which means it can be disassembled.Plutonium-241 rods in LV.huh
