### ISSUE TITLE
Mixin Adjustment. Remove Anvil too Expensive error if it's over 40 levels to use.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#12326]
### Your GTNH Discord Username

StoneLegion#0026

### Your Pack Version

2.2.8

### Your Proposal

Mixin an adjustment that updates the anvils to make it so you can use them no matter what the enchant cost is. I believe vanilla has a "hardcap" of level 40. It should not ever been that way in modded and makes those of us who enjoy more early game enchanting a little more thrilling. I'm sure there is ways around this later on but let us Anvil boys have this one! 

Example of doing it the wrong way in 1.7.10 by replacing the anvil:
https://github.com/vdvman1/betterAnvil-forge

Example of Mixins method in 1.19:
gtnh.miraheze.org/wiki/Backups_and_Recovery

Thanks. 

### Your Goal

Because boys will be boys. 

### Your Vision

To avoid Thaumcraft ;) 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
Avoid thaumcraft... there is just the void metal anvil for something, using a little magic ain't gonna hurt nobody
