### ISSUE TITLE
A new material as UHV+ Magnet: DTG alloy

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#12322]
### Your Pack Version

2.2.8

### Your Proposal

Add DTG alloy (Dysprosium-Terbium-Gadolinium) as UHV+ magnet.
The radio is to be determined. It would be proceed in alloy smelter instead of Blast Furnace or DTPF. Maybe UHV 64s per ingot is good?

### Your Goal

UHV+ motors need too many Samarium. We need a proper material to make UHV+ motors and maybe UHV+ coils, which are used  to make UHV+ energy hatches.

### Your Vision

Now Gadolinium could be produced with Samarium at the same time, but it is somewhat useless. We are supposed to make it useful.
Terbium can be produced from the Bastnaesite line. It offers more motivation for players to make the Bastnaesite line besides Holmium.
Dysprosium is a GT++ material. It can be produced by Isamill or Rare Earth III. It was noticed that some players didn't understood how GT++ ore works. Rare Earth III is easy to make and it wouldn't cause a lot of lag beacuse it only need 6 machines. The automated Rare Earth III could make players have a deeper understanding about GT++ without having a lot of trouble. And it also outputs Gadolinlum. The Isamill is more complex and challenging but players could choose whether to make it.
In the reality, we use Neodymium-Iron-Boron instead of only Neodymium, Samarium-Cobalt instead of only Samarium. So I think add a new alloy as a magnetic metal is reasonable. Why don't we use Alloy Smelter to process it? Players have had the Mega Alloy Smelter. The fluid could be easily used in Component Assline.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by cainiaojun** [comment]
#12324 has some interesting ideas, which can be used as reference.

**Comment by Steelux8** [comment]
UHV would be impossible if this magnetic rod was to be crafted in the DTPF. If this was added, it would have to be decided whether it should be a DTPF craft, an UHV assline recipe or something else.

**Comment by cainiaojun** [comment]
> UHV would be impossible if this magnetic rod was to be crafted in the DTPF. If this was added, it would have to be decided whether it should be a DTPF craft, an UHV assline recipe or something else.

The existing mechanism of DTPF needs to be improved. The catalyst line needs too many Laser Engraver and Mixer, which greatly increase mspt. I don't think add anything in DTPF is a good idea before the catalyst processing is rebalanced.
It seems that an assline recipe for a magnet is not reasonable.
A Blast Furnace recipe or Alloy Smelter recipe is easy and doesn't bother players. We can add a simple line with 3-5 steps like the issue I mentioned above, but not too time-costing or expensive.

**Comment by boubou19** [comment]
> The existing mechanism of DTPF needs to be improved. The catalyst line needs too many Laser Engraver and Mixer, which greatly increase mspt. I don't think add anything in DTPF is a good idea before the catalyst processing is rebalanced.

you say that but did you measured the mspt? because unless you seriously go fast, most of the time the machine is idling because structure check is done every couple of seconds, the inputs are processed on the first tick of the recipe, and the output is generated in the last tick. The maintenance check is done once every 50 seconds when the multi is working, so most of the ticks it's just decreasing energy from the energy hatch. Machine spam is an issue if you start to have hundreds of machines, or several one ticking machines.

> A Blast Furnace recipe or Alloy Smelter recipe is easy and doesn't bother players. We can add a simple line with 3-5 steps like the issue I mentioned above, but not too time-costing or expensive.

One of the main directives to keep modifying the pack is to remove unecessary tedium. Your suggestion shows you want to annoy the player. Why? Tedium != difficulty. For example, opening hundreds of files manually and one by one on your computer is tedious, but i don't think it is hard to open a file.

The only way such a process could be added is through new multis or new mechanics, because doing yet another chemical reactor/mixer/alloy smelter/blast furnace/centrifuge/biovat is already a no brainer for players at those tiers, you just need to order them in AE, build them, and plug them into your power grid.

**Comment by cainiaojun** [comment]
> > The existing mechanism of DTPF needs to be improved. The catalyst line needs too many Laser Engraver and Mixer, which greatly increase mspt. I don't think add anything in DTPF is a good idea before the catalyst processing is rebalanced.
> 
> you say that but did you measured the mspt? because unless you seriously go fast, most of the time the machine is idling because structure check is done every couple of seconds, the inputs are processed on the first tick of the recipe, and the output is generated in the last tick. The maintenance check is done once every 50 seconds when the multi is working, so most of the ticks it's just decreasing energy from the energy hatch. Machine spam is an issue if you start to have hundreds of machines, or several one ticking machines.

I have no idea about the optimization developers had done. That's my fault.

It has took me some time to ask other players about catalyst. A player who had made the stargate said he can't count how many Mixers he had because them covered an area of more than 20 chucks. A UMV player said he has 40+ MAX+ Mixers and 40+ MAX+ Laser Engravers. A UIV player said he wanted a mega Mixer and a Mega Laser Engraver. Another developer said he used to thought about bringing the catalyst recipe back to the fusion so that it got perfect overclock (He hadn't do anything about that). I have 100 Mixers and 100 Laser Engravers - about a half of my base. Those machines really have my computer suffered. It would be great if there was a machine that could produce a large amount of catalyst quickly.

Or, as another player said, "Just remove a zero from the time cost of the catalyst's recipe".
> 
> > A Blast Furnace recipe or Alloy Smelter recipe is easy and doesn't bother players. We can add a simple line with 3-5 steps like the issue I mentioned above, but not too time-costing or expensive.
> 
> One of the main directives to keep modifying the pack is to remove unecessary tedium. Your suggestion shows you want to annoy the player. Why? Tedium != difficulty. For example, opening hundreds of files manually and one by one on your computer is tedious, but i don't think it is hard to open a file.
> 
> The only way such a process could be added is through new multis or new mechanics, because doing yet another chemical reactor/mixer/alloy smelter/blast furnace/centrifuge/biovat is already a no brainer for players at those tiers, you just need to order them in AE, build them, and plug them into your power grid.

I don't want to bother players a lot. What I would like is a process like Yttrium Barium Cuprate. Players needn't to do something particular to made this magnet. They just need to use their machines that they had already made. But if there is a new multi in development, I'm glad to see it.

By the way, I think most of time we shouldn't add a new multi for a single recipe. Add a new multi only for magnets seems unreasonable. At least make it be able to do some recipes existed effciently.

**Comment by chochem** [comment]
we have a different one now
