### ISSUE TITLE
Adding ablility to combine Keybinds

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#12325]
### Your GTNH Discord Username

Ethryan ☢#4665

### Your Pack Version

2.2.9

### Your Proposal

Find some way to implement combination keybvinds for stuff, since most people are probably running out of keys to bind keybinds to. 

For example: Ctrl + B to open Backpack, and just B to open Adventure Backpack.

### Your Goal

Quality of life, It would allow you to have all backpacks on a single key, with the only change being if you held down Ctrl or not.

More Info: [Link](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2387347-key-combinations-are-here-over-9000-combos)

### Your Vision

Able to use more keybinds instead of toggling them on or off in the settings to use.
Maybe implement it in the Controlling mod.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by iouter** [comment]
maybe check this? https://github.com/Nova-Committee/ModernKeyBinding

**Comment by Ethryan** [comment]
Might work, i'm gonna do some more testing on that. Thanks iouter.

**Comment by dhasial** [comment]
I looked through their repo and they actually have their own fork of Controlling (ModernControlling) and there's a 1.7.10 branch for it.
