### ISSUE TITLE
Multiblock Miner Not Retracting Mining Pipes 

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#12321]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

2.2.8

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

Multiblock miner would retract pipes when finished mining.

### The Reality

Had to mine up pipes when miner was done. (This has happened on Mars and in Twilight Forest thus far for sure).

### Your Proposal

Find out why multiblock miners aren't retracting pipes and try to fix?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
Never had this happen. Though it could be a new problem ofc. More information is needed for sure.

You are checkmarking you can reproduce it based on certain steps? What are these steps to follow exactly? I guess that would be the obvious place to start.

Also, were they chunkloaded? was there anything suspicious in the log file? And other people have confirmed this?

**Comment by shawnbyday** [comment]
> Never had this happen. Though it could be a new problem ofc. More information is needed for sure.
> 
> You are checkmarking you can reproduce it based on certain steps? What are these steps to follow exactly? I guess that would be the obvious place to start.
> 
> Also, were they chunkloaded? was there anything suspicious in the log file? And other people have confirmed this?

Currently just plopping down miner (tier 1) and chunkloading using FTButils. So far happened on Mars and Twilight Forest. Currently have miners deployed on Moon and Nether to see if same behavior there. If happens there I'll check logs and post back.

**Comment by King65868** [comment]
My multiblock miners have retracted their pipes when done, havent experienced this. On 2.2.8 as well using FTB utilities for chunkloading.

**Comment by BritishCynic** [comment]
Also on 2.2.8, Multiblock Miners do retract their mining pipes. However, Oil Drilling Rigs do not retract their pipes.

**Comment by shawnbyday** [comment]
Why are we changing my ticket title? There is already an open ticket for the fluid rigs somewhere.

**Comment by chochem** [comment]
go get your own ticket if oil drilling rigs have problems :P

**Comment by shawnbyday** [comment]
Caught the end of my multiblock miner on the moon and it retracted all the pipes but instead of ejecting both stacks to the chests like it used to it ejects one stack of pipes to the chests and then redeploys the 2nd stack of pipes to the point it runs out then it shuts off saying "out of pipes". This is consistent with the behavior I experienced on Mars and in the Twilight Forest. Still waiting for my miner in the nether to finish.

**Comment by shawnbyday** [comment]
Upgraded to T2 miner and still not retracting the pipes.

**Comment by SweptWasTaken** [comment]
> 

At least for me on 2.2.8, drilling rigs don't retract their pipes if they don't reach bedrock, so if they're stopped by something else like warded glass, they'll never retract their pipes.

**Comment by shawnbyday** [comment]
Mine hit bedrock. Then will rubber band up and down forever unless there aren't enough pipes to go back down again then it just stops at 64.

**Comment by DotJason** [comment]
Not sure if it's the same problem (looks like mining pipes are out of whack generally) but my ore MBM does not retract pipes when if finishes working (regardless of dim). It retracts exactly 4 pipes and then shuts down. I can enable it, then it retracts 4 more pipes and shuts down. At least eventually I can retract all pipes like that.

Playing on 2.3.4 with updated GT

**Comment by Speecker** [comment]
Experiencing this issue as well in v2.3.5 and v2.3.6 - especially after a server restart.
Looks like the Miner runs fine after hitting bedrock and retracts fine but if there is a server restart in between the Miner seems to try to place another mining pipe where a block of bedrock is and cant recognize it hit bedrock already.
The controller block says "Missing Mining Pipe" even though there are still Pipes available but as soon as it hits bedrock it shouldnt need any further pipes right ?
Hope this gets fixed soon ;)
