### ISSUE TITLE
add a new magnetic material for uhv+

### ISSUE THREAD

**Issue by lost121** [GTNewHorizons/GT-New-Horizons-Modpack#12324]
### Your Pack Version

2.2.8

### Your Proposal

Add samarium-dysprosium alloy to the game
I want to use it on UHV+ part
There is my personal progressing thinks for the alloy
5Dy+12Sm+3Fe+2Cu+1Zr+1Hf+1000LXe（1000LOg）
EBF uhv 230s 10500k  
24 hot samarium-dysprosium magnet base Ingot

1 hot samarium-dysprosium magnet base Ingot
Vacuum Freezer uv 40s
1 samarium-dysprosium magnet base Ingot
 
1 samarium-dysprosium magnet base Ingot
Macerator LV 0.5s
1 samarium-dysprosium magnet base dust

1 samarium-dysprosium magnet base dust
Polarizer uhv 10s
1 Magnetic samarium-dysprosium magnet base dust

1 Magnetic samarium-dysprosium magnet base dust+144L 502 glue+Extruder Shape (Rod)
Extrusion Machine uhv 8s
1 Magnetic samarium-dysprosium rod

that's progressing reference bonding process in
reality. 

### Your Goal

In iv and before this,magnetic material have Fe steel 
and Nd.After this,We only have samarium to craft luv+ motor. that's so boring!To change the situation,
I suggest add a new magnetic material for uhv+ motors.

### Your Vision

Dy could be produced by rare earth III,that's not hard to get.Dy is also used to craft magnetic material in reality.
Hf is prouced in Lanthanide line and seemed useless.this change can make it more useful,
and it is also used to craft magnetic material in reality
502 glue is a interesting chemical plant product,but
don't have much use.In the reality,people use organic binder to craft magnetic material.that's why I choose 502 glue for this processing.it is also make 502 glue more useful.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [x] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
Ig this happened now https://github.com/GTNewHorizons/GT5-Unofficial/pull/1891. Needs proper recipe integration though.
