### ISSUE TITLE
Galacticraft 3.0.63 GTNH Crash the game on start

### ISSUE THREAD

**Issue by vasmark1** [GTNewHorizons/GT-New-Horizons-Modpack#12330]
### Your Pack Version

Mod

### Your Server

SP

### Type of Server

Single Player

### Your Actions

It works fine with latest version of GC I've found on Curse, but when I've tried to update to ur newest version this happened. 

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: tconstruct/client/tabs/AbstractTab

And I don't even have tconstruct in my modpack, but game constantly crashes because of something connected to it.

P.S.: I know that my modpack is bllsht, but if you can help - please, do it.

### Crash Report

[crash-2023-01-20_14.44.54-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10471255/crash-2023-01-20_14.44.54-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by vasmark1** [comment]
Update. 
When I've added tconstruct first error disappeared, but another one is here. 

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: gregtech/api/util/GT_ModHandler

[crash-2023-01-20_15.05.47-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10471267/crash-2023-01-20_15.05.47-client.txt)

Idk what I need to do next.

**Comment by Alexdoru** [comment]
if you don't have the full pack your game is going to crash because it's trying to load code that you are missing

**Comment by glowredman** [comment]
Also, we don't support the usage of our GC fork outside of GTNH because we don't have the permissions to do so.
