### ISSUE TITLE
Matter Fabrication CPU the actual number of parallelism is inconsistent with the tooltips

### ISSUE THREAD

**Issue by BlueIceJAY** [GTNewHorizons/GT-New-Horizons-Modpack#12339]
### Your GTNH Discord Username

Neutron#6126

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

None

### Your Expectation

Parallel:Scrap=64|uu=8*tier
If I provide the Matter Fabrication CPU UV to craft UU Amplifier,it should have 512(64*8) parallel number

### The Reality

The actual number of parallelism is inconsistent with the tooltips
I provide the Matter Fabrication CPU UV to craft UU Amplifier,it has 64(8*8) parallel number
provide ZPM the number of parallelism is only 56(7*8)

![7S BW~{ NS%RBN0W$0H5Z%0](https://user-images.githubusercontent.com/63415263/213924783-a8a341e8-50e6-443b-8ab8-2d49a10e2304.jpg)
![WMFN8D1G UI4Z_2R RMZMMO](https://user-images.githubusercontent.com/63415263/213924780-0db37e47-a2ee-4a35-b083-d71f8b0577c6.jpg)
![N4N`K3KF2MH~%6G)7@L5@(F](https://user-images.githubusercontent.com/63415263/213924785-51f0b1ba-aeb3-4905-912f-ed9fa13474a9.jpg)
![`~V(9~SYJH8Y ~@4ARIW)09](https://user-images.githubusercontent.com/63415263/213924788-5900a8d4-3dc0-4f8b-84d8-c62f173f948b.jpg)
![~3Y8{TVTJ4LL`_4G9T)KA17](https://user-images.githubusercontent.com/63415263/213924789-fdb28a04-3c97-4123-8265-bfa73b330010.jpg)

### Your Proposal

Align the Matter Fabrication CPU's parallel count with the tooltip

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
8x7=56, sounds correct? how did you get to numbers like 512?

**Comment by LewisSaber** [comment]
Tooltip tells you that UU has 8xTier parallel, UU is both UUA and UUM
