### ISSUE TITLE
tps card with Cofh tricks

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#12340]
### Your GTNH Discord Username

Кетцаль#0802

### Your Pack Version

last OC version (16.01.2023)

### Your Server

dev client

### Type of Server

None

### Your Expectation

Started making a program for tps_card and ran into problems.

### The Reality

1. there is no normal id for the end and the hell
2. the hell uses id -1, but cofh will not accept an id below zero. I loaded 1 chunk in hell and using the getChunkLoadedForDim(1) command i got chunks from hell. 
3. id from Personal space not wokrs for chunks, tile Entity and entity 

   
   
![image](https://user-images.githubusercontent.com/17906427/213937196-957bc6c1-b935-42a7-a2c5-2221fc8e590f.png)

### Your Proposal

hmm... fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
getChunkLoadedForDim is not implemented on PersonalSpace side:
https://github.com/GTNewHorizons/PersonalSpace/blob/d9d46e1cbfb55082cbe7e4273b5474df5da3fc69/src/main/java/me/eigenraven/personalspace/world/PersonalChunkProvider.java#L169 
I guess you have to convince @eigenraven to implement it

**Comment by eigenraven** [comment]
The 0 there is correct, this is what the vanilla worldgen providers do too (ChunkProviderFlat, ChunkProviderGenerate, etc.). ChunkProviderServer/Client is the one that returns a value there, and that wraps any generator chunk provider.

**Comment by repo-alt** [comment]
Ok, otherwise, all these functions accept not dimension privider id, but just an index in the world array, as returned by `getAllDims`, so I'm not sure if it actually _should_ be changed, except maybe for the docstring

**Comment by repo-alt** [comment]
I mean - dimension provider ids just do not look convenient to operate in LUA code

**Comment by Zereff06** [comment]
it is inconvenient when some methods work by id and others by index

**Comment by repo-alt** [comment]
All the methods take indices

**Comment by Zereff06** [comment]
This seems to require an id  getTickTimeInDim()

**Comment by Zereff06** [comment]
![image](https://user-images.githubusercontent.com/17906427/213990126-3bb532b0-c188-4052-94c4-70fc87b48e3a.png)
![image](https://user-images.githubusercontent.com/17906427/213990726-4d9d7ec0-c48f-46d9-974a-919000f0d32d.png)

**Comment by Zereff06** [comment]
loaded 3 chunks in spectre world and 1 in nether , went back to overworld and checked the index
![image](https://user-images.githubusercontent.com/17906427/213996416-1d4ad8f0-605c-4acb-98e9-8cc66d189aa3.png)

**Comment by repo-alt** [comment]
Actually now I'm not sure what to unify these functions to. Dimension index looks easy to use but dimension id looks more _logical_

**Comment by boubou19** [comment]
The fact that the dimension names are translated via locales in SP makes them not reliable to use.

**Comment by repo-alt** [comment]
nah, the names are irrelevant, I meant the diffrence between dimension _ids_ like the nether id is -1 and dimension _indices_, like the nether world index is usually 1, and the PersonalSpace ids are usually big (maybe 180+), but their _indices_ are just indices, 11,12,13 whatever. _ids_ are persistable, indices are runtime only, so that point is in favour of ids

**Comment by eigenraven** [comment]
Exposing indices would be exposing a minecraft implementation detail, the server just happens to use an array of dimensions instead of a map. You can easily iterate a id->value map in lua too, not any different from a regular array

**Comment by Zereff06** [comment]
It is much more convenient to use the id, so you can specify the desired world at once without having to go through the entire list of worlds. Also, getting statistics through the id will not break when adding a new world, for example a personal world
