### ISSUE TITLE
ME output busses keep losing items after update from 2.2.3 to 2.2.8

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12356]
### Your Pack Version

2.2.8

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

The following error appears in our console every few seconds since we updated from 2.2.3 to 2.2.8:
`[19:34:39] [Server thread/WARN] [GregTech GTNH]: An error occurred while loading contents of ME Output Bus, some items have been voided`

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
is the area where your ouput bus is properly chunk loaded ?

**Comment by Tommeh1** [comment]
> is the area where your ouput bus is properly chunk loaded ?

It turns out that chunkloaders were indeed shitting the bed after the update, just like ME P2P which we're forced to overhaul together with all ME stocking busses which quit updating, but after fixing chunkloading the error still occasionally occurs.

**Comment by Tommeh1** [comment]
Turns out that these errors were wrong and are instead due to the ongoing AE2 issues related to substitutions.
