### ISSUE TITLE
PCB Factory trace has abnormal performance

### ISSUE THREAD

**Issue by a5632645** [GTNewHorizons/GT-New-Horizons-Modpack#12351]
### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I tried to look at the source code to get how much the trace setting of the PCB factory would make the most boards output per second
I found that the trace settings and output of the PCB factory should have been
When trace is less than or equal to 100, the closer trace is to 50, the higher the probability of two copies being output
When trace is greater than or equal to 100, the closer trace is to 200, the lower the probability of output a piece of material

### The Reality

I speculated and actually verified the findings based on the code
Only if trace equals 50, there is a 100% probability of outputting two copies
When less than or equal to 100, 100% output of one material
When it is greater than 100, no product is output

It seems that the problem is due to this line of code
`int repeats = (int) Math.ceil(getMaxEfficiency(aStack) / 10000);`
When the trace is between 50 and 100, getMaxEfficiency will return an int value between 10000 and 20000, while ’Math.ceil (getMaxEfficiency(aStack)/10000)’ will make repeats be 1 due to the truncation of int division by int, and the following loop is only performed once, resulting in 100% output of one product
When trace is above 100, getMaxEfficiency will return an int value between 5000 and 10000, again truncation and repeats will be 0, the following loop does not proceed and does not output any products
`for (int k = 0; k < mCurrentParallel; k++) {
                    int remainingEfficiency = getMaxEfficiency(aStack) < 10000 ? 10000 : getMaxEfficiency(aStack);
                    for (int j = 0; j < repeats; j++) {
                        int chanced = getBaseMetaTileEntity().getRandomNumber(10000);
                        for (int i = 0; i < tRecipe.mOutputs.length; i++) {
                            if (chanced < remainingEfficiency) {
                                tOutputs.add(tRecipe.getOutput(i));
                            }
                        }
                        remainingEfficiency -= 10000;
                    }
                }`

### Your Proposal

I think it should be changed to this line of code so that the PCB factory has the correct expected result
`int repeats = (int) Math.ceil(getMaxEfficiency(aStack) / 10000.0f);`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueWeabo** [comment]
Thank you for this issue. I shall fix it soon.
