### ISSUE TITLE
Add Simple washer recipe for all Bart Ores

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#12367]
### Your Pack Version

2.2.8

### Your Proposal

Right now it's only possible to use cauldron or the washer (single and multiblock) to get washed BW ores, simple washer simply dont work.
![image](https://user-images.githubusercontent.com/49487505/214283532-a0469dcc-ae13-4da3-a6f4-5ddf04b3b884.png)
Add simple washer recipes for all BW ores .

### Your Goal

QOL

### Your Vision

QOL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by DStrand1** [comment]
Added in https://github.com/GTNewHorizons/GTplusplus/pull/611
