### ISSUE TITLE
GT++ Solar Tower does not work or has too little Tooltip Information

### ISSUE THREAD

**Issue by IkarusFalling** [GTNewHorizons/GT-New-Horizons-Modpack#12379]
### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

None

### Your Expectation

Build Solar Tower with Solar Reflectors expected it to Heat Solar Salt Inputted Into Input Hatch to Heat and turn into Heated Solar Salt in Fluid Output Hatch. 

(Maybe I build It wrong used Structure Hologram for Main Structure added Hatched fixed Maintenance Issues added Solar Reflectors on the Level of the Tower Base 7 Blocks from the Center Totaling to 36 Solar Reflectors also Malleted the Controller to activate it and waited till it reached 100% Eff. No Heated Salt) 

(If it is important it was in the Personal Dimension (Regular Solar Panels work there) was also not able to get it to work in Overworld)

(Used Basic Maintenance and EV Fluid In and Out Hatches) 

![2023-01-24_23 48 13](https://user-images.githubusercontent.com/111616675/214438421-64698aed-e9a5-4e00-b050-b44fa7c3d551.png)

Tooltip:

![2023-01-24_23 49 39](https://user-images.githubusercontent.com/111616675/214438550-d031d80a-bb71-42a8-9622-5c7ae75d9e8b.png)

Input Hatch:

![2023-01-24_23 53 54](https://user-images.githubusercontent.com/111616675/214439193-8aaed39f-dcc1-4912-ae4f-9e759c6f8400.png)

Controller Weila:

![2023-01-24_23 56 09](https://user-images.githubusercontent.com/111616675/214439540-7ec390fd-5f9f-41eb-a561-5d74a5504ea5.png)

### The Reality

Salt Does not Heat 

### Your Proposal

It should Heat the Solar Heat or have a clearer Tool or Weila why it does not

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Steelux8** [comment]
Did you allow the heat value to reach 30000? The salt heating will not happen until the heat reaches that value.

See https://github.com/GTNewHorizons/GTplusplus/pull/471.

**Comment by IkarusFalling** [comment]
How does one see the Heat Value of the Tower? As far as I can tell its not part of the Tooltip in the Version I am playing (2.2.0.0)

**Comment by Steelux8** [comment]
You can see it with a Portable Scanner used on the controller.

**Comment by IkarusFalling** [comment]
That seems to be the Issue I did not let the Heat Rise long enough (also either I am blind or does the Tooltip not say anything about a minimum of 30k Heat being Necessary? Thats kind of Important if the Tower has such long Heatup Times)

**Comment by cainiaojun** [comment]
By the way, it seems that the effeciency formula is wrong. 
Not $ \frac{\left (  \left | currentHeat-50000 \right |^{0.8} +7000 \right ) }{7000} $

But $ \frac{\left ( - \left  | currentHeat-50000 \right |^{0.8} +7000 \right ) }{7000} $
