### ISSUE TITLE
Turbine Housing not crafting (assembly line issue)

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#12377]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.2.0.0

### Your Server

Delta

### Type of Server

Thermos

### Your Expectation

Turbine housing is craftable according to the recipe

### The Reality

The ingredients sit in the assembly line, but the craft doesn't start. 

The data stick used was crafted using the current version. I also checked the stick with a Data Reader and got the same recipe from that as NEI.

### Your Proposal

Please correct this.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/467
