### ISSUE TITLE
Flat fluid interface bug. Ae2Fs.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/GT-New-Horizons-Modpack#12376]
### Your GTNH Discord Username

Pilad

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

None

### Your Expectation

Update mods. Latest modpack.
ae2fc-1.7.10-1.0.58-gtnh
appliedenergistics2-1.7.10-rv3-beta-149-GTNH

We check on any craft. For example, liquid rubber in plates.
![изображение](https://user-images.githubusercontent.com/9840821/214378897-b0527694-500d-432c-a495-abc7208b9328.png)
The recipe is in the terminal.
![изображение](https://user-images.githubusercontent.com/9840821/214378981-90ca80cf-ef68-4673-a15f-47e109eb0d28.png)

### The Reality

Now let's go to the main menu of the game and go back to the world. And the plate recipe is gone.
![изображение](https://user-images.githubusercontent.com/9840821/214379058-fbaa1191-ad7f-4f0a-b782-0721f4ae7ca3.png)

### Your Proposal

Fix flat fluid interface.
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/issues/235

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by asdflj** [comment]
fixed in https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/69

**Comment by GlodBlock** [comment]
fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/e424230f96e0a2b4697f1996588a3efef7cb785b
