### ISSUE TITLE
Output Hatch (ME) should be able to output multiple fluids at once

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12371]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.8

### Your Proposal

The space pump module should use 1 ME output bin to output all the fluid

太空泵模块应该使用1个ME输出仓就可以输出全部流体

### Your Goal

太空泵模块流体产量大，并且MK2可以同时进行4个合成表，使用4个普通输出仓并不能很方便的进行液体的传输

Space pump module has a large fluid output, and MK2 can carry out 4 synthesis tables at the same time, using 4 ordinary output bins is not very convenient for liquid transmission

### Your Vision

Reduced downtime and game flow due to cabins, and better fluid interaction

减少因为舱室所导致的卡顿与游戏流畅度降低，并且更好的进行流体的交互

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
That's a general limitation of the output hatch ME to only buffer 1 fluid. I will change the topic name to reflect that.

**Comment by minecraft7771** [comment]
Sorry I have been informed that it used to buffer multiple fluids at one point. I will look into what caused this to not work anymore.
