### ISSUE TITLE
Fluid processing pattern terminal recipe creation crash

### ISSUE THREAD

**Issue by Eranicus** [GTNewHorizons/GT-New-Horizons-Modpack#12380]
### Your GTNH Discord Username

Eranicus#5476

### Your Pack Version

2.2.9-5dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

.

### The Reality

Im not sure if this was already reported or not , but I cant find it.

Game crashes to main menu as soon as you try to create any pattern in fluid processing pattern terminal.

### Your Proposal

please fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
please provide a crashlog

**Comment by Eranicus** [comment]
> please provide a crashlog

Here it is , created on clean 2.2.9-5dev 

[crash-2023-01-25_03.32.09-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10495065/crash-2023-01-25_03.32.09-client.txt)

**Comment by Beannsss** [comment]
https://github.com/GTNewHorizons/NotEnoughEnergistics/pull/29

https://github.com/Beannsss/NotEnoughEnergistics/releases/tag/1.3.26
