### ISSUE TITLE
Energy hatch causes dynamo hatch stop working sometimes

### ISSUE THREAD

**Issue by Ressed** [GTNewHorizons/GT-New-Horizons-Modpack#12383]
### Your GTNH Discord Username

Ressed#3182

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Connect an energy hatch to the cable connected to a dynamo hatch

### The Reality

Just watch the video. Put down the energy hatch, rotate it to the cable but not connect to it, then the dynamo hatch stops working, outputs no energy until the enrgy hatch is connected to the cable.

https://user-images.githubusercontent.com/26176604/214623689-d088b38c-9ea5-4522-b442-478085676e06.mp4

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ressed** [comment]
maybe the cable between energy hatch and dynamo hatch should be straight ( i.e. not connect to other blocks ) to reproduce the bug

**Comment by chochem** [comment]
in my experience this is not really about the hatch you added but about the cable dead end. enet just kills itself sometimes in these situations. In hindsight that whole rewrite was probably a regression.

**Comment by zonkedzoey** [comment]
Done some testing, can confirm this issue relates to a cable stub 
(ie. when cable is only connected at one point, if the cable is connected to more than one point the issue does not occur)
