### ISSUE TITLE
Request for unblacklisting iron golem from powered spawner

### ISSUE THREAD

**Issue by sintken** [GTNewHorizons/GT-New-Horizons-Modpack#12386]
### Your GTNH Discord Username

Sintken #1312

### Your Pack Version

2.2.8.0 or whatever

### Your Proposal

NEI lists iron golem as possible in EEC, but eio configs have it blacklisted so iron golem powered spawner cant be created. Preferred change is to unblacklist iron golems (dim bridges for stargate need so much FUCKING iron), but failing that it'd be nice to remove the iron golem from EEC NEI to reduce confusion. tx

### Your Goal

stargate need too much iron

### Your Vision

less-laggy endgame iron generation (PA fluid solidifier meh)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
Wouldn't it be easier to pump molten iron either with inf drill or elevator pump?
