### ISSUE TITLE
T1 Microchip uses incorrect NEI Displayed Circuit

### ISSUE THREAD

**Issue by Lithorn** [GTNewHorizons/GT-New-Horizons-Modpack#12388]
### Your GTNH Discord Username

Lithorn#3961

### Your Pack Version

2.2.8

### Your Server

SMP

### Type of Server

Vanilla Forge

### Your Expectation

Went to make microchip for rocket controller 
![image](https://user-images.githubusercontent.com/4071258/214759517-65b6a7b4-115b-4b09-91a4-b080ffafc06b.png)

### The Reality

Needs to be set to Circuit 1 to function correctly, NEI lists Circuit 2

### Your Proposal

I didn't see anyone else mention this but, it aint no big deal to just flip the circuit number needed in NEI

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
Check the later pages, I think the last page contains the recipe with hv circuits.

**Comment by Ethryan** [comment]
I
