### ISSUE TITLE
Coal Ball missing multiblock mixer recipe

### ISSUE THREAD

**Issue by Zap0** [GTNewHorizons/GT-New-Horizons-Modpack#12385]
### Your GTNH Discord Username

Zap#7261

### Your Pack Version

2.2.8

### Your Server

Localhost

### Type of Server

Vanilla Forge

### Your Expectation

There is a recipe to craft a Coal Ball with 8 Coal Dust and 1 Flint Dust in the mixer. I'm generally expecting both the singleblock and the GT++ multiblock version to be able to craft the same recipes.

### The Reality

The recipe only exists for the singleblock mixer, not the GT++ multiblock mixer.

![image](https://user-images.githubusercontent.com/6502640/214711387-7b295e57-1c31-447d-9cc2-745e56865179.png)

### Your Proposal

Add recipe to GT++ mixer.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Zap0 @chochem all zen script recipes are not added to gt++. If we add this recipe to gt code or core mod the issue is solved.

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/595e30a4-524a-4979-828b-d5052250bbf3)
all fixed thanks to moving scripts to coremod
