### ISSUE TITLE
Multi Passive Farm

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#12392]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.2.8

### Your Proposal

Add a multiblock that can farm a majority of animal items passively, and those that are meat by consuming their respective food

### Your Goal

Being able to farm some items without having to go through the tedious bees or without having a bunch of mobs near my base:

- The multiblock should give a large number of raw meats from passive terrestrial animals, in turn feathers and eggs, protein, nutrient distillation... All of this using diferent circuits and food inputs, some rare ore unique drops could be made at this multi ( like horse meat or things that arent at the EEC)
-  Energy tier speed up the processing time, it should work similar as the Zhuhai

![image](https://user-images.githubusercontent.com/45178400/214893403-dfaf9945-998b-4c2b-a85e-70c82fa545a0.png)
 The heart blocks are Pure Love blocks with the #12370 recipe
 The controller should go where the infinity block is placed
![image](https://user-images.githubusercontent.com/45178400/214893556-1b8e984f-f154-41af-929e-0b781115f40e.png)

### Your Vision

I think it would help to improve the lag that having many mobs can cause, it also has a high cost so it doesn't break progression, simply once you have it it helps to get certain items, such as those required for cosmic meatballs, By the way, these should require some other items... like some more raw meats and the Triple Meat Threat from thaumcraft

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by DragonStorm25** [comment]
Is that extreme crafting table recipe the recipe for the controller? Why does it need to be in an extreme crafting table instead of an assembler or even AL?

**Comment by EnderProyects** [comment]
> Do we really need something like this? We can get animal byproducts from crops and bees

Not all items can be farmed this way, even at the EEC, this leads to explore the world or breeding animals, like you can also get fish of the crops, but there is the fishing multiblock

**Comment by EnderProyects** [comment]
> Is that extreme crafting table recipe the recipe for the controller? Why does it need to be in an extreme crafting table instead of an assembler or even AL?

It's only an idea of items that could be used in the recipe, it could be even a thaumcraft infusion if you wish😹

**Comment by BritishCynic** [comment]
I like this idea as a counterpart to the fishing port.
