### ISSUE TITLE
The InGameInfoXml covers the Thaumcraft wand vis level display

### ISSUE THREAD

**Issue by BeepBeep20** [GTNewHorizons/GT-New-Horizons-Modpack#12390]
### Your GTNH Discord Username

BeepBeep2020

### Your Pack Version

2.2.0.0

### Your Proposal

I'd suggest changing the default config setting as seen in the image below.

The top left corner image shows how it normally looks & the image below that shows how it looks when the "top left" is set to 105
![2023-01-26_08 52 29](https://user-images.githubusercontent.com/58308068/214797703-62f50b26-07f0-4a80-ba2d-070b4932b56c.png)

### Your Goal

It's mentioned in the questbook that igi can be customised by the player via /igi config. But I'd guess a lot of people just put up with the visual conflict  especially as they'd read the questbook early game but not be using Thaumcraft for quite some time.

Maybe a compromise to a config change would be to add to the questbook some text saying that changing the "top left" to 105 will allow the TC wand vis display to be more clearly visible.

### Your Vision

Just so they don't conflict

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
I'd prefer to move the wand vis display instead... you have igi on at all times, but wand vis display is on for <0.5% of your total game time (from start to stargate).

**Comment by Ethryan** [comment]
Wand dispaly moved
