### ISSUE TITLE
Make mega apiary structure more lenient with construction errors

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12394]
### Your Pack Version

2.2.8

### Your Proposal

Either severely simplify the mega apiary structure or have it allow for a certain amount of errors before not being able to be completed.

### Your Goal

We're currently trying to build our second mega apiary as we need a swarmer feeding about 1k queens into the first one to make it worth more than some industrial apiaries, and we might just have to take it down entirely and rebuild it like the last one just because it's marked as incomplete and with all its odd design and asymmetrical parts finding why is essentially impossible, wasting hours of multiple people each time.

Additionally it doesn't seem to want to use anything else than cosmic neutronium glass, auto place is not allowed for it and the hologram projector only likes to complain about the glass all the time, even on completed/formed ones.

### Your Vision

Make people waste less hours on horrendously unnecessarily tedious things.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by kuba6000** [comment]
There is survival auto place now. Fixed by https://github.com/GTNewHorizons/KubaTech/pull/38
