### ISSUE TITLE
QFT Should Be Able to Process Some Intermediate Products in Platline

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#12403]
### Your Pack Version

2.2.8

### Your Proposal

QFT should be able to transform Palladium Metallic Powder into Palladium, Iridium Metal Residue Powder to Iridum, Rarest Metal Residue Powder into Osmium and Iridium. 

Palladium and Iridium in tier 1, UV 10s, Osmium in tier 1, UV 15s.

96 Palladium Metallic Powder -> 64 Palladium Powder (slightly lower than the yield in platilne)
60 Rarest Metal Residue Powder -> 3 Osmium Powder+ 60 Iridium Powder (the same yield as platline)
64 Iridium Metal Residue Powder -> 64 Iridium Powder (the same yield as platline)

### Your Goal

My Void Miners constantly produces Palladium ore, Iridium ore and Osmium ore. After processing in Integrated Ore Processor, they become to Palladium Metallic Powder, Iridium Metal Residue Powder and Rarest Metal Residue Powder. They has piled up in my AE network and take up a huge amount of bytes. 

### Your Vision

Make those Intermediate Products be a useful resource in a single step and lag-free.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
QFT recipes need a minimum of 3 outputs per recipe, and the recipes themselves are supposed to cover many different items at the same time and not just a 1:1 conversion. Direct powder to the pure metal will not happen in the QFT.
