### ISSUE TITLE
[VisualProspecting]VisualProspecting judges that mod loading is to detect the jar name, not the registered name in forge

### ISSUE THREAD

**Issue by KuroPeach** [GTNewHorizons/GT-New-Horizons-Modpack#12404]
### Your Pack Version

2.2.8

### Your Proposal

VisualProspecting judges that mod loading is to detect the jar name, not the registered name in forge，I found it when I tried to changeJmap to journeymap-unlimited. I added a prefix to it to indicate the additional mod. As a result, VisualProspecting did not recognize it. When I checked the source code, I found that it is looking for a matching jar to determine whether the mod is loaded. 

It is recommended to change it to detect the registered name in the game

https://github.com/GTNewHorizons/VisualProspecting/blob/master/src/main/java/com/sinthoras/visualprospecting/mixinplugin/TargetedMod.java

### Your Goal

Change it to detect the registered name in the game

### Your Vision

Authors usually use the registry name to find other mods

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
looks like the author of VP was very well aware of what he was doing: 
https://github.com/GTNewHorizons/VisualProspecting/blob/29f5d04ce98b75e9e0bc7a4bc00ae158a493ac57/src/main/java/com/sinthoras/visualprospecting/mixinplugin/TargetedMod.java#L8-L17

**Comment by KuroPeach** [comment]
Yes, get high priority, but this can change VisualProspecting.jar to 00VisualProspecting.jar, or register as coremod

**Comment by eigenraven** [comment]
Hodgepodge had a fix for an almost exactly the same issue with renaming jars, maybe it could be reused

**Comment by mitchej123** [comment]
Vp should be updated to target gtnh mixins and early/late mixins, much like hodgepodge.   It's still using the deprecated jar identification as noted here.
