### ISSUE TITLE
LFTR energy generation is bad

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#12405]
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

2.2.8.0

### Your Proposal

LFTR 1 requires 200 million eu and 5400 seconds to generate 1 bucket, which is worth 600 million.
Overclocking LFTR unit from EV to IV doesn't make sense, because you will get 2 buckets (1200 million), but spend 200*4=800million.
So without overclock you get 400 million eu. With overclock you again get 400 million eu in the same amount of time.

So now we got 400 million eu profit in 5400 seconds. That is about 625 seconds of LuV amperage.
To make 1 amper of constant LuV you need ~9 LFTR multiblocks. And because overclock doesn't bring any profit, you can't have a single block with a bigger hatch. You need 9 LFTR with EV energy hatch.

Now let's compare this garbage to Kinetic Generator. Requires 1000x times less resources. Doesn't need any fuel, which is extremely hard to make for LFTR because it requires tons of different components and machines. Because Dehydrator requires different circuits and multiblock is ZPM+. And also requires monitoring, tons of space and other staff.

### Your Goal

Make LFTR 1 have a perfect overclock.
Make LFTR 1 fuel at least 3 times better. Because even after this it would be quite garbage compared to any kinetics.

### Your Vision

This could be a fine energy option for LuV.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by nikitinalexx** [comment]
Btw Lithium 7 dust also requires in total about 70 million eu to craft NON overclocked, which is also very slow.

**Comment by vovaksenov** [comment]
Idk, you need only 2 buckets of fuel 1 to start making fuel 2 (you get around 300l of U233 per bucket and you need 576l) which, although has an even longer recipe, makes a zpm amp. 
Though i can agree it needs an efficiency bump. The recipes are annoying and these machines are pretty much useless for anything else, so it is a substantial investment with better alternatives.

**Comment by querns** [comment]
The way LFTR was explained to me was that LFTR Fuel 1 is bad *on purpose.* Its role is for breeding nuclear material needed for LFTR Fuel 2. That being said, you have to invest a LOT of infrastructure just to run one LFTR on Fuel 1 fulltime:

Here's a flowchart for Fuel 1. https://i.imgur.com/jVB4Nvu.png . Not inlined because it's large. I gave up on trying to model Fuel 2 with this tool because of the percentage chance yields being too unpredictable.

**Comment by Steelux8** [comment]
I look at this line again in the near future, but not before the next stable.

**Comment by Steelux8** [comment]
This issue has been solved for some time with several changes I made to the LFTR chain. Closing it now.
