### ISSUE TITLE
Mega apiary unable to draw enough power for most of its bee storage

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12402]
### Your Pack Version

2.2.8

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

The mega apiary should be able to run with its bee storage full.

### The Reality

However, it will shutdown due to power loss around the moment its storage exceeds about 50% due to it not being able to draw enough power, despite bee storage capacity scaling with available power.

### Your Proposal

Calculate the bee storage capacity correctly or adjust the power draw to not exceed the max amount it can draw, even if bee storage is full.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
How many energy hatches do you use and what hatches they are?

**Comment by Tommeh1** [comment]
> How many energy hatches do you use and what hatches they are?

10 normal UHV hatches

**Comment by kuba6000** [comment]
Have you ever seen any multiblock that worked with more than 2 hatches (except BW megas)? Currently, only wireless hatches support >2 hatches on multiblocks to overclock

**Comment by chochem** [comment]
many of the ++ ones apparently work with 8 now. (they didnt used too back in the day afaik :P)
But not gt yea.

**Comment by Tommeh1** [comment]
> Have you ever seen any multiblock that worked with more than 2 hatches (except BW megas)? Currently, only wireless hatches support >2 hatches on multiblocks to overclock



> Have you ever seen any multiblock that worked with more than 2 hatches (except BW megas)? Currently, only wireless hatches support >2 hatches on multiblocks to overclock

It seems to effect bee storage accordingly, the swarmer usage, despite being negative matched well more than 2 hatches and instead matched all 8 it has access to, and the normal mega apiary is currently drawing well more than 2 hatches can provide and is functional, although it claims it can use less than the swarmer oddly enough.
https://cdn.discordapp.com/attachments/563042433777270785/1068566837291384952/image.png

**Comment by kuba6000** [comment]
Currently:
At most you can use 4 normal hatches in normal mode
Swarmer mode will not overclock with 4 hatches so it will use 2 of them (That applies to all GT multis)
If you use wireless hatches, then in theory it should work up to 4000 hatches (If there was a space :P)
It is not a bug, thats how GregTech works, it's balance

If your Mega Apiary worked with 8+ hatches then its because of this: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12401
