### ISSUE TITLE
make wireless covers check less often

### ISSUE THREAD

**Issue by Divran** [GTNewHorizons/GT-New-Horizons-Modpack#12419]
### Your GTNH Discord Username

Divran#4349

### Your Pack Version

2.2.8 + manual updates

### Your Proposal

it would be great if someone could increase the interval that wireless redstone covers check the redstone signal from once per tick to once every 5 seconds or so. Or give them a checkbox in the UI to toggle the update interval between fast and slow, or something.

Included pictures below shows the exact same processing array, both times idle, with wireless cover attached and removed. May not seem like a huge difference, but it adds up when you place wireless covers on every machine in your entire base. 
And the reason we have it on every machine is because it's extremely helpful to be able to turn off your entire base all at once, for example to upgrade power cables without deleting everything that's currently crafting and without then having to run around and hit everything with a hammer after to turn it back on.

![image](https://user-images.githubusercontent.com/1485728/215298697-5e77de4e-00b7-4b34-a858-7c763deb326a.png)
![image](https://user-images.githubusercontent.com/1485728/215298700-7135918c-8677-4c06-a62f-d7bbf316181d.png)

### Your Goal

Improve TPS

### Your Vision

Improve TPS

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Fiyorin** [comment]
bump so it doesn't get closed
