### ISSUE TITLE
New Bee Quests

### ISSUE THREAD

**Issue by hacatu** [GTNewHorizons/GT-New-Horizons-Modpack#12418]
### Your GTNH Discord Username

hacatu

### Your Pack Version

2.2.3

### Your Proposal

-Explosive: Makes ITNT, not as fast as a decent chem setup but can carry you pretty far especially in a no-space run

-Xenon: There's already the helium bee quest which mentions other gas bees exist, but given this is probably the only useful one it deserves special mention

-Valuable: maybe better left as an Easter egg

-Ardite/Cobalt/Manyullyn: note that these are kind of bugged (tcon nuggets can only become greg if you craft them into rounds)

-Certus/Fluix/Phosphorus/Mica/Pyrotheum/Cryotheum/Sunnarium/Void metal/Shadow Metal/Thauminite/Conductive Iron/Pulsating Iron/Electrical Steel/Dark Steel/Lapis: give resources with no need for acid.  NB none of these are duplicates, some bees just have the same name, eg there's a lapis bee in QB but it's different than this lapis bee.

-Lapotron: also gives energium

-Cryolite: good for fluorine

-D-O-B (what does this even mean)

-Sulfur: good because it can give firestone

-Air/Fire/Water/Earth/Order/Chaos/Nethershard/Endshard: first 6 are just better versions of primal dust bees, last two make ichor waaaaaaaaay cheaper

### Your Goal

Although there are 151 bee species documented in the bee breeding tab, there are 461 in total, and some of the missing ones are actually useful.  I've listed most of the reasonably useful unlisted ones here.

### Your Vision

The Explosive, Xenon, Sunnarium, Cryolite, Lapotron, DOB, Sulfur, and good thaumcraft shard bees especially should be brought to player attention

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by hacatu** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10842
Link to existing issue about tcon nuggets

**Comment by chochem** [comment]
Explosive, DOB, Xenon, and Sulfur/Firestone are covered now. Some of the rest feels a bit like spam. I think people are able to check if a particular resource has a bee.

The threshold to get on the page should be one of the following:
1) its needed for crafting (uranium, neutronium, etc.)
2) its really strong (indium, empowering)
3) its very easy to miss/unexpected/nontrivial (explosiv, empowering, wither, dob)
+intermediaries

**Comment by hacatu** [comment]
Yeah that's a good point.  Idk why I put sunnarium and Lapotron on the shortlist, they're good but as you said very obvious.  Thank you for adding the other quests!

The only remaining bee I think should have a quest is nether/endshard.

Combs themselves aren't needed for crafting, but they are very strong for ichor.  I don't know another way to get the shards besides in-world farms in both the nether and end, or the dreadful infusion recipes.

You could definitely make the argument they aren't easy to miss, just look at the second tab in nei.

However, players will often be viewing the ichor/ichorium recipe in the thaumonomicon, which will only link to the thaumonomicon page for nether/endshards, and there are already quests for the shard dust bees which makes the shard bees easier to miss imo.
