### ISSUE TITLE
Placing 2 AEFC2 Fluid Storage Buses on each other causes a crash

### ISSUE THREAD

**Issue by ussdefiant60** [GTNewHorizons/GT-New-Horizons-Modpack#12410]
### Your GTNH Discord Username

ussdefiant60#6571

### Your Pack Version

2.2.9-7-pre-dev-Java-8

### Your Server

SP

### Type of Server

Single Player

### Your Actions

in an effort to resolve #12408 , i decided to experiment with 2.2.9-7 and the shiny new AE2FC fluid storage buses to see if swapping out the Extra Cells ones would solve the problem. Sadly, placing 2 AE2FC storage buses facing each other to make a subnet resulted in an instant crash on placing the second one.

### Crash Report

[crash-2023-01-27_15.55.17-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10523782/crash-2023-01-27_15.55.17-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by GlodBlock** [comment]
fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/fc9893ac32e357817b851ac77092e43e5289bc4d
