### ISSUE TITLE
Consistent chain armor recipes in alloy smelter

### ISSUE THREAD

**Issue by newo-2001** [GTNewHorizons/GT-New-Horizons-Modpack#12415]
### Your GTNH Discord Username

newo2001#8471

### Your Pack Version

2.2.8

### Your Proposal

I suggets one of two changes to be made:

1. Remove the alloy smelter recipe to convert chain boots to a steel ingot.
2. Add similar recipes for the other armor pieces.

### Your Goal

Consistency

### Your Vision

It feels weird for only one of the armor pieces to be smelted back into ingots.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I think what is going on is that the others are not worth precisely one ingot. It should all be autogenerated.

I think its fine.
