### ISSUE TITLE
Task 2914 is wrong

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#12414]
### Your GTNH Discord Username

Mobius

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

CoAsS + 02 → Calcined cobalt + Calcined arsenic

### The Reality

The purpose of mission 2914 is to let me get cobalt from cobaltite, but he wants to retrieve my cobalt oxide

### Your Proposal

The task is changed to retrieve the roasted cobalt

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you just forgot to `\bq_admin default load`. or to search the github first. :P
