### ISSUE TITLE
Can't disable the potion effects from sleeping in a bed or sleeping bag

### ISSUE THREAD

**Issue by croftyraider** [GTNewHorizons/GT-New-Horizons-Modpack#12413]
### Your GTNH Discord Username

croftyraider

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

None

### Your Expectation

Currently if I sleep I always get the "You feel really well rested" message and then a random buff is applied.
However, there is no way to disable it as far as I can tell, or a least remove some of the buffs from being chosen.

For me personally, Speed II and Speed III cause eye strain and give me a headache so I would love to turn them off.

I have asked in the discord multiple times, but no one knows, so I'm asking here, sorry!

Thanks.

### The Reality

There seems to be no way to disable the effects from sleeping.

### Your Proposal

Let me disable the effects from sleeping please.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
>For me personally, Speed II and Speed III cause eye strain and give me a headache so I would love to turn them off.

If you play with optifine you play with the `Dynamic FOV: OFF`

**Comment by croftyraider** [comment]
Thanks for the suggestion. I don't need optifine so I've haven't been using it.
