### ISSUE TITLE
Europium fusion gate is kind of broken at the moment

### ISSUE THREAD

**Issue by vovaksenov** [GTNewHorizons/GT-New-Horizons-Modpack#12416]
### Your GTNH Discord Username

VovassGreat#2054

### Your Pack Version

2.2.8

### Your Proposal

The place of europium in GregTech progression has always been to separate the pre-fusion and the post-fusion content. Bart's ore is controversial but does not break this on its own, as you still need a Tier 5 rocket to access Ross128ab, where the ore generates. Now, however, it is possible to build this rocket before fusion, as europium is now a byproduct in the monazite line and can be obtained once you reach LuV. This means it is now possible to fully enter ZPM before building a fusion reactor. 

### Your Goal

First it is necessary to decide, whether this tier-skip is intended. 
If it is, the solution is to alter the LuV chapter in the questbook, removing fusion as the prerequisite from europium.
If it is not, here are a few things that could be done:
- Remove europium from the monazite line. This will pull the balance back to where it was before this issue.
- Alter the path europium is obtained from the monazite line. This can be done in a few ways, but what jumps to my mind is putting the EuO to EuS recipe into ChemPlant instead of the chemical reactor and to require a catalyst obtainable only after fusion (for example made from europium itself), or require some machine that can not have two energy hatches / tier-skip at ZPM (ABS / Assembler / Electromagnetic Separator). Basically force the player to already possess europium if they wish to get pure europium from the monazite line.
- Remove Bart's ore from Ross128ab. kind of don't want to do this, as it does not really address the issue, but it is precisely the access to this ore that makes the issue so important, because you do not get much europium from the monazite line itself. If the ore is removed, one would have to process a very large amount of monazite and have a very powerful ammonia line (read powergen) to get enough europium from it for all the further progression needs. The ore on the other hand can give you a thousand europium in like ten minutes, as by this time you already have the LuV prospector.

### Your Vision

Restore the europium tier-gate or properly finish altering the progression.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LewisSaber** [comment]
Another solution can be to replace europium in t5 rocket plating to duranium

**Comment by vovaksenov** [comment]
Yes, nice idea, but then quests should still be adjusted to not require fusion for europium. Crystal circuits are most certainly possible from monazite europium.

**Comment by cainiaojun** [comment]
Monazite enables players to get Crystal Circuits in LuV instead of late-LuV or ZPM. I think it is reasonable and can greatly keep players from the pain of making a lot of Quantum Circuits. In my opinion, we can just do nothing and edit quests.

The amount of Europium from Monazite is limited and it is slow to get enough Europium, so I think it is still necessary to produce Europium from Fusion.  Just remind players there are some alternative ways in quests and enable players complete the Europium quest and T5 rocket quest before Fusion.

By the way, changing the Europium block to Duranium block in the scanner recipe could force players to make Mk1 instead of Mk2 directly.

**Comment by vovaksenov** [comment]
I agree on crystal circuits, but I still feel that ZPM should be gated behind fusion. If you allow T5 rocket you basically open access to massive quantities of easy europium because of ross. Yes, you cant automate it, but you can get thousands in a matter of an hour. I think @LewisSaber's suggestion is the best yet and then if anyone desires to enter ZPM on monazite europium, let them have it, they probably deserve it. The quests dependencies then can be adjusted accordingly.

**Comment by cainiaojun** [comment]
> I agree on crystal circuits, but I still feel that ZPM should be gated behind fusion. If you allow T5 rocket you basically open access to massive quantities of easy europium because of ross. Yes, you cant automate it, but you can get thousands in a matter of an hour. I think @LewisSaber's suggestion is the best yet and then if anyone desires to enter ZPM on monazite europium, let them have it, they probably deserve it. The quests dependencies then can be adjusted accordingly.

Let the Bart's ore only be processed in a UV Centrifuge and everyone would be happy lol.

There are players who only mine Indium in Ross128b, we can't stop them from doing the same.

**Comment by AbdielKavash** [comment]
I will add to this that Europium can be obtained as early as *IV* with the monaline. The electrolyzer recipe to make the dust (the only "ZPM gate") takes 33,000 EU/t, which if you use the GT++ multiblock electrolyzer gets reduced to 29,700 EU/t. This can be provided by two IV energy hatches (32,768 EU/t obviously). Smelting the dust into ingots only requires a MV EBF and cupronickel coils. So you don't need any LuV machines or the assline at all to get europium.

Yes the electrolyzer recipe skip does actually work, I have tested it in 2.2.0.0 in creative.

**Comment by Alrightsc** [comment]
Yeah, the electrolyzer skip is mostly more of an issue than anything else. I think no one knew that GT++ electrolyzer could have more than two energy hatches, which is how this enables the fusion skip.

I imagine that nothing will get changed soon though, and eventually we will have MuTEs to replace all of this that would likely not make this tier skip possible. But to be honest, I don't think this is a big deal to have a skip for europium, as fusion is still needed anyway (just going off power generation that is a huge huge upgrade alone).

**Comment by vovaksenov** [comment]
No, nothing out of the ordinary with electrolyzer here. 2 IV or 1 LuV hatch is enough to do a LuV recipe. It is LuV and not ZPM because of a discount, but that is a separate matter, you dont need more than 2 energy hatches.

**Comment by Glease** [comment]
1. Tier skip was not intentional.
2. New recipe chain require europium dust to process europium oxide, so the tier skip is now impossible.
