### ISSUE TITLE
unlock the GT5-Unofficial PR #1671 （Allow materials to pick their processing tier）

### ISSUE THREAD

**Issue by wumingzhiren** [GTNewHorizons/GT-New-Horizons-Modpack#12421]
### Your Pack Version

2.2.9

### Your Proposal

unlock the GT5-Unofficial PR (https://github.com/GTNewHorizons/GT5-Unofficial/pull/1671)  （Allow materials to pick their processing tier）

### Your Goal

unlock the GT5-Unofficial PR (https://github.com/GTNewHorizons/GT5-Unofficial/pull/1671)  （Allow materials to pick their processing tier）

### Your Vision

unlock the GT5-Unofficial PR (https://github.com/GTNewHorizons/GT5-Unofficial/pull/1671)  （Allow materials to pick their processing tier）

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by SafariXiu** [comment]
![07VCLQ)SBM}% H5{H)%LO12](https://user-images.githubusercontent.com/98251218/215316622-0507e089-a767-4869-b8a8-e9a433dcb0db.png)
It doesn't make sense. I don't know that kind of person would think of that kind of PR. See for yourself

**Comment by SafariXiu** [comment]
The 9 largest wireless energy silos can't even be overclocked to 1tick

**Comment by Glease** [comment]
At least annotate the screenshot. No one knows what these 时空锭 means.

**Comment by cainiaojun** [comment]
There is a special community who can't express themselves on Discord and Github directly. We are a part of them and we are taking their ideas here. Now players are deliberately angry with some contributor's idea (not I).

**Comment by cainiaojun** [comment]
> At least annotate the screenshot. No one knows what these 时空锭 means.

Spacetime ingot

**Comment by SafariXiu** [comment]
> At least annotate the screenshot. No one knows what these 时空锭 means.

![T12N(A7$1%0_){%CAFU87$8](https://user-images.githubusercontent.com/98251218/215316719-8d1160ad-71bb-4ce4-80cd-9a6124036f50.png)

**Comment by cainiaojun** [comment]
I don't agree with most of players who want to kick Colen from Developers. But I think at least we should consider their opinions.

**Comment by chochem** [comment]
you open a ticket to discuss a merged pr that you link wrong? specifically a pr that is just locked as to heated? and then you post unrelated stuff?

what the hell is going on

**Comment by SafariXiu** [comment]
![AU8SQWZEY2LJB{ZCQ%7PJ{F](https://user-images.githubusercontent.com/98251218/215316844-ad51afe2-39cd-46f2-bd3a-b9aa258f089d.png)
Look at this. How many space-time cubes does he need?

**Comment by chochem** [comment]
Everything you post seeems utterly unrelated

**Comment by cainiaojun** [comment]
> Everything you post seeems utterly unrelated

https://github.com/GTNewHorizons/GT5-Unofficial/pull/1671

**Comment by cainiaojun** [comment]
The one who open this issue seemed wrong

**Comment by boubou19** [comment]
> you open a ticket to discuss a merged pr that you link wrong? specifically a pr that is just locked as to heated? and then you post unrelated stuff?

> what the hell is going on

 mad people expressing their disagreement.

@cainiaojun @SafariXiu i suggest you to stop posting your hate. Go cool your head. If you keep going, i'll prevent you from using the github tickets.

**Comment by iouter** [comment]
@boubou19 in any case, you should not prevent people from discussing. it's like removing PSS some time ago, the pack will only get better with more discussion, blocking discussion will only make people more angry.

**Comment by boubou19** [comment]
@iouter i am all for discussion, just not heated ones where some people shit on one of our devs just because of their frustration.

**Comment by iouter** [comment]
> @iouter i am all for discussion, just not heated ones where some people shit on one of our devs just because of their frustration.

well, everybody need to calm down, let's discuss again tomorrow, okay?

**Comment by POPlol333** [comment]
> ![AU8SQWZEY2LJB{ZCQ%7PJ{F](https://user-images.githubusercontent.com/98251218/215316844-ad51afe2-39cd-46f2-bd3a-b9aa258f089d.png) Look at this. How many space-time cubes does he need?

Hi, on this point assuming you use the Hypogen recipe this is 19008 cubes to get the Eternal dtpf for around 9 days-ish of processing time
