### ISSUE TITLE
Disassembler gives microprocessors instead of electronic circuits

### ISSUE THREAD

**Issue by 704009905** [GTNewHorizons/GT-New-Horizons-Modpack#12425]
### Your GTNH Discord Username

Hexadecimal#1191

### Your Pack Version

2.2.8

### Your Server

Self-hosted private server

### Type of Server

Vanilla Forge

### Your Expectation

In quest "Gimme My Stuff Back!" (Tier 1 - LV) it reads: "If there's an oredicted item like a circuit, it should return the least valuable one."
I suppose electronic circuit is the least valuable of LV-tier circuit(oredict:circuitBasic).

### The Reality

But the disassembler gives microprocessors when disassembling LV machines.
Tested with LV and MV disassembler.

### Your Proposal

Gimme My Least Valuables Back!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BritishCynic** [comment]
There is no reason why, if you're OK with the Electronic Circuit, to be unhappy over receiving a Microprocessor back. They're effectively the same for crafting.

**Comment by vovaksenov** [comment]
The idea of returning the worst circuit comes from how we want this circuit to be least upgradeable. For example there should be no way for people to convert quantum mainframes to a crystalprocessor zpm circuit which is upgradeable to UV crystal mainframe. Microprocessors on the other hand are not upgradeable by design, so in some way, tgey aee the least valuable, so if they are returned there is no problem. They can be converted to the electronic circuit through the configuration circuit, but that is another story.

**Comment by 704009905** [comment]
> The idea of returning the worst circuit comes from how we want this circuit to be least upgradeable. For example there should be no way for people to convert quantum mainframes to a crystalprocessor zpm circuit which is upgradeable to UV crystal mainframe. Microprocessors on the other hand are not upgradeable by design, so in some way, they are the least valuable, so if they are returned there is no problem. They can be converted to the electronic circuit through the configuration circuit, but that is another story.

I didn't think of this, so in some sense microprocessors can be considered the least valuable and it's OK?
I'm on HV so I don't know about the higher tiers. Just tried to disassemble ZPM disassembler and it gives quantum mainframes, seems works as intended.
