### ISSUE TITLE
Missleading Questbook entry in Bee breeding tab

### ISSUE THREAD

**Issue by TechnicFreak** [GTNewHorizons/GT-New-Horizons-Modpack#12430]
### Your GTNH Discord Username

AntiMaid#0421

### Your Pack Version

2.2.0.0

### Your Server

MyFTB

### Type of Server

Thermos

### Your Expectation

Tryed to breed a Platinum bee following the Questbook guideline. 
It tells me to use a platinum Block as foundation, did not work out.

### The Reality

Looked it up in NEI, there it tells me to use a Nickel block - That works.

### Your Proposal

Either update the NEI entry or the questbook entry

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
duplicate from https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11385
was fixed three months ago.
