### ISSUE TITLE
Wireless pattern terminals 

### ISSUE THREAD

**Issue by TechnicFreak** [GTNewHorizons/GT-New-Horizons-Modpack#12431]
### Your GTNH Discord Username

AntiMaid#0421

### Your Pack Version

2.2.0.0

### Your Proposal

Adding either new wireless terminals, or adding a pattern funtionality to existing ones ( maybe even Assline patterns )

### Your Goal

Beeing able to create new patterns on the fly while standing infront of the desired machine 

### Your Vision

Would make the life easier as it would not require the player to be infront of their stationary pattern terminals, and is in result not bound to run back to a terminal everytime a new pattern is needed

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by asdflj** [comment]
added https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/71
