### ISSUE TITLE
Microblocked lapis caelestis no longer renders

### ISSUE THREAD

**Issue by Jimbno** [GTNewHorizons/GT-New-Horizons-Modpack#12436]
### Your GTNH Discord Username

Jimbno

### Your Pack Version

2.2.8

### Your Server

single player

### Type of Server

None

### Your Expectation

In previous versions this worked without an issue

### The Reality

Now when converting lapis caelestis to micro blocks it becomes invisible
https://imgur.com/zmWloHV

### Your Proposal

revert to previous behaviour 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DarkStarBuster** [comment]
I have now encountered this in 2.3.0, is there any information that I can provide that would help diagnosing this?

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/77248928/214cd44b-4901-4457-ad3f-61704b58fc7c)

**Comment by dvdmandt** [comment]
Can confirm this is still an issue in 2.6.1 (Angelica alpha 50), or rather they are pitch black in 2.6.1:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11985732/67eb0045-292f-489a-9ac8-c10860a5dda6)
