### ISSUE TITLE
Terrasteel and tiberium both have "Tr" chem abbreviation.

### ISSUE THREAD

**Issue by vovaksenov** [GTNewHorizons/GT-New-Horizons-Modpack#12444]
### Your GTNH Discord Username

VovassGreat#2054

### Your Pack Version

2.2.8

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

Two completely different materials should not have same chemical "element" abbreviation.

### The Reality

Both tiberium and terrasteel use "Tr", which can be confusing especially considering very similar color of the two.
![Screenshot from 2023-01-30 20-33-01](https://user-images.githubusercontent.com/86674724/215577720-e75074b0-7f3a-49ba-9848-4dad4102a62c.png)
![Screenshot from 2023-01-30 20-33-59](https://user-images.githubusercontent.com/86674724/215577727-28a87ed0-2d4a-4134-a2ce-29cd88975e4b.png)

### Your Proposal

As far as the pack history is concerned, Tr was used for tiberium for a long time before botania was added, so terrasteel abbreviation should probably be changed. 
In my opinion, botania chem stuff is weird in general: using separate "elements" for livingrock/wood, manasteel, terrasteel and gaia spirit (and maybe even other stuff I have not yet paid attention to) feels unreasonable. I suggest removing chem abbr from all botania stuff as it is unnecessary for any related integration with gregtech. 
In case the developers wish to nevertheless leave something there for some reason, I would follow the example of thaumcraft here: Thaumium is FeMa so, something like SiO2Ma would fit livingrock, Fe50CMa for manasteel and maybe something of similar nature can be used for others too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leagris** [comment]
The suggestion here makes sense, is documented and justified. Botania is really a pure magic mod with nothing related to chemistry.
Whereas Tiberium, while also fictive; has been given some extensive chemical background as a crystal, ability to concentrate minerals and metals from ground and binding with carbon life forms as a toxic and cancerous agent.

I regret that such fictive materials were not prefixed or rendered with something very distinctive, like italic or even fictional alphabet symbols like the Standard Galactic Alphabet already used for Minecraft magic symbols.
So Tiberium Tr would turns out as T∷ (See: https://lingojam.com/StandardGalacticAlphabet)

**Comment by Steelux8** [comment]
All element notation that isn't referring to real life elements should definitely get some unique character(s) to differentiate them from the rest. Optimally, this would be standardized so that these new fictional elements are categorized in some way.

**Comment by combusterf** [comment]
There's three free options for elements: `T` for either, `Tu` for tiberium and `Tt` for terrasteel.
Based on the crafting recipe, `FeBeC2Ma` would be my suggestion.

And while standard galactic alphabet is nice visually, you can't type it to locate it in NEI that way
