### ISSUE TITLE
Make the GTPP machine support tectech's laser bay and high energy cabin(让GTPP支持tectech的激光仓与高能量仓)

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12449]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.9-dev7

### Your Proposal

Make GTPP multi-block machine support tectech laser bin and high energy bin

使GTPP的多方块机器支持tectech的激光仓与高能量仓

### Your Goal

In the new version, the processing voltage of later materials has been increased, and today's big machines can no longer handle these materials in sufficient power and parallel。In later games, it's normal to build a big machine with millions of materials, and it would be very painful to not have a way to mass produce materials at scale。We can design the GTPP machine so that it can only increase the voltage by 1 level but overclocking the power and parallelism to prevent jumping too much voltage to make it

在新版本中，后期材料的处理电压被提高，现在的大机器已经无法满足足的功率与并行去处理这些材料。在后期游戏中，制作一台大机器使用几百万的材料是很正常的，如果没有一种可以大规模量产材料的办法，那将是十分痛苦的。我们可以将GTPP的机器设计为只能提高1级电压但是对功率与并行进行超频来防止跳跃过多的电压来进行制作

### Your Vision

Overclocking and parallel of GTPP has always been an indispensable part of the game. However, due to the relatively small energy silo supported, a large number of overclocking and parallel cannot be carried out in the late stage. In the late stage, the selection has almost completely fallen to the processing array，By supporting the laser bay and the high energy bay, we have more options in the later stages

在游戏中，GTPP的超频与并行是游戏中不可或缺的一部分，但是因为支持的能源仓比较小，导致在后期无法支持较多的超频与并行，后期几乎只能使用处理阵列来进行大量的合成，在GTPP支持激光仓与高能量仓后，我们在后期就有了更多的选择

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alrightsc** [comment]
PAs already have 4x parallel per UEV machine (or something) which outright beat most GT++ machines for late game, and PAs also support lasers/TT hatches too.

Also, I believe we are going to get a new multi rework at some point which will replace PAs/most multis at some point, so it might be pointless to add this functionality for them at this stage.

**Comment by SafariXiu** [comment]
> PAs already have 4x parallel per UEV machine (or something) which outright beat most GT++ machines for late game, and PAs also support lasers/TT hatches too.
> 
> Also, I believe we are going to get a new multi rework at some point which will replace PAs/most multis at some point, so it might be pointless to add this functionality for them at this stage.

But it lowers the voltage of the machine, which is reasonable but in post-processing, high voltage is important，The processing array of the UMV machine requires 2.5s to process the recipe for 256 UEV voltages when the 4x function is enabled，
But in the later stage, the number of these things to deal with may be tens of millions, if only by stacking the number of machines to change this situation, I think it is not reasonable

**Comment by SafariXiu** [comment]
> PAs already have 4x parallel per UEV machine (or something) which outright beat most GT++ machines for late game, and PAs also support lasers/TT hatches too.
> 
> Also, I believe we are going to get a new multi rework at some point which will replace PAs/most multis at some point, so it might be pointless to add this functionality for them at this stage.

Of course, there's also the idea of adding a machine to make a lot of parts later in the game. If we can implement this, we may not need a lot of machines later in the game

**Comment by boubou19** [comment]
These are the reason why we did not added exotic energy hatch support to the GT++ multis:
- it can cause tierskip
- it can allow way more overclocks
- it can allow way more parallels

while the first point can be fixed in code, having way more parallels in addition to way more overclocks will just destroy the balance of the GT++ multis, which are already questionble as is.

So it will stay like that as long as we can't find a way to mitigate tons of free parallels and OC with exotic hatches. And to be honest, MuTEs (way better API for multiblock developpement) may happen before we find a solution. At that point we will move all the multis on it and we will rework all the multiblocks.

**Comment by SafariXiu** [comment]
> These are the reason why we did not added exotic energy hatch support to the GT++ multis:
> 
> * it can cause tierskip
> * it can allow way more overclocks
> * it can allow way more parallels
> 
> while the first point can be fixed in code, having way more parallels in addition to way more overclocks will just destroy the balance of the GT++ multis, which are already questionble as is.
> 
> So it will stay like that as long as we can't find a way to mitigate tons of free parallels and OC with exotic hatches. And to be honest, MuTEs (way better API for multiblock developpement) may happen before we find a solution. At that point we will move all the multis on it and we will rework all the multiblocks.

We urgently need something that can make a catalyst, which is one of the reasons we want the GTPP to support the laser bin.colen says one will be built, hopefully soon

**Comment by chochem** [comment]
yea, as boubou explained these are not supported on purpose.

If there is a problem with a specific endgame recipe, maybe talk to other endgame players about the balance of that particular one.
