### ISSUE TITLE
It's stupid to make carbon board from plant fiber

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#12441]
### Your GTNH Discord Username

Mobius

### Your Pack Version

2.2.8

### Your Proposal

Reduce the number of plant balls needed for making plant fiber

### Your Goal

It takes 18432 crops to make carbon board from plant fiber, and 6144 crops even if high octane gasoline is used

18432 → 2304 Plant ball → 144x0.33(Use of biomass) Plant fiber → 24 Carbon plate

Only 192 carbon powder is needed to make 24 carbon plates

### Your Vision

It will become more reasonable to use plant fiber to make carbon board

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
It would make sense that pure Carbon is much more efficient at making Carbon Plates than plants, no?

**Comment by iouter** [comment]
if this line can't be more efficient than pure carbon, it's useless.

**Comment by Steelux8** [comment]
So be it. The intended way of making Carbon Plates is to use pure Carbon, and you can also get it from crops in many ways.

**Comment by Glease** [comment]
Maybe the process can be made faster and done in larger batches, so it functions as a better trash can that at least give some useful.
