### ISSUE TITLE
Crash onloading world

### ISSUE THREAD

**Issue by BGURGEWR** [GTNewHorizons/GT-New-Horizons-Modpack#12446]
### Your GTNH Discord Username

BGURGEWR#1833

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I tried to launch my world via the single player menu

### Crash Report
https://paste.ubuntu.com/p/R7kzV3jH7X/
[crash-2023-01-31_12.20.37-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10541621/crash-2023-01-31_12.20.37-client.txt)
![image](https://user-images.githubusercontent.com/124010858/215637119-53823258-f409-47f2-952e-6dba430ada18.png)
doubt thats needed but just in case 
(first time making one)
extra little thing i made a new world and it didnt crash 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
every time or just once? This looks like a random vanilla minecraft network error.

**Comment by eigenraven** [comment]
You need to post the full log, the network packet handler crashes after the real crash happens

**Comment by BGURGEWR** [comment]
everytime works fine when i make a new world

**Comment by BGURGEWR** [comment]
> 

ill do that when i get home

**Comment by eigenraven** [comment]
This is still just the crash-report file, I need the full log that shows up in your launcher

**Comment by Dream-Master** [comment]
@BGURGEWR

**Comment by BGURGEWR** [comment]
> This is still just the crash-report file, I need the full log that shows up in your launcher

really sorry im very stupid ill do that now ty for being paitant

**Comment by BGURGEWR** [comment]
[2023-02-01-1.log.gz](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10563616/2023-02-01-1.log.gz)

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/216202656-0a60984c-b4e4-4f28-bebf-0c632d674909.png)


So some form of chunk corruption. Add it to the pile: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11640

The question is only if there is some common cause behind all these
