### ISSUE TITLE
Rendering errors will occur when the game is running on an xe graphics card

### ISSUE THREAD

**Issue by nano096** [GTNewHorizons/GT-New-Horizons-Modpack#12442]
### Your Pack Version

2.2.8

### Your Server

sp

### Type of Server

None

### Your Expectation

This is the text translated by Google：I updated the driver a few days ago, and it caused me to call the nuclear display by default.
Then there are some errors in the rendering of mc. My cpu is 12700h, gpu is 3060.I have attached a video at "The Reality"

### The Reality

like this

https://user-images.githubusercontent.com/122845037/215502727-4311b007-f205-4d4c-904b-9bf73ddd4b9c.mp4

### Your Proposal

I think fixing this problem will help gtnh to run on some low-end computers.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
yea, newer intel graphics drivers are known to be a problem. read https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10490 for example. Nothing we can do about it.
