### ISSUE TITLE
Thaumic Tinker Seeds Creating World Destroying Items

### ISSUE THREAD

**Issue by Cardinalstar16** [GTNewHorizons/GT-New-Horizons-Modpack#12445]
### Your GTNH Discord Username

Cardinalstar16#3425

### Your Pack Version

2.2.7

### Your Server

SP

### Type of Server

Vanilla Forge

### Your Actions

Harvesting Arbor aspect plant. 

These plants drop anything that has the oredict tag wood in it, giving some illegal natura items, it seems. It also breaks progression heavily by giving stuff like spacetime and infinity in arrow form (all gt metals) when you have infusion.

### Crash Report

[crash-2023-01-30_16.50.18-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10540674/crash-2023-01-30_16.50.18-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alastors** [comment]
Those seeds are glitchy as hell fam
