### ISSUE TITLE
NEI Highlighting for Text on AE2FC Fluid Storage Cells

### ISSUE THREAD

**Issue by patrick-hill** [GTNewHorizons/GT-New-Horizons-Modpack#12458]
### Your GTNH Discord Username

EventHorizon01#3263

### Your Pack Version

2.2.8.0

### Your Proposal

Would it be possible to have NEI highlighting to search the AE2FC Storage cells? The example being: partition a storage cell for a fluid, search for the fluid in NEI, double click the search bar to "highlight" all items with that search term, the storage cell for that fluid should be highlighted as well.

![image](https://user-images.githubusercontent.com/1435324/215912678-f86b2913-7d27-4ada-ad00-004b9a27ddff.png)

### Your Goal

Improve NEI and the new AE2FC fluid system that only allows 1 fluid per cell, basically making partitioning worth while now.

### Your Vision

Finding fluid cells that need upgraded/replace much, much easier as right now, with a ton of these, there's no other way than holding shift and manually searching through your dozens and dozens of cells :/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
@GlodBlock
