### ISSUE TITLE
Faucets dont work

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12455]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.2.9-8-pre-dev

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

faucets should work.

### The Reality

they dont
![image](https://user-images.githubusercontent.com/40274384/215904299-7e6393de-a257-4ae4-8fc2-3b4c15ffa428.png)
![image](https://user-images.githubusercontent.com/40274384/215904315-4f496048-1b95-4e4f-9a58-a1dffc86b5fd.png)

there is nothing in the logs. The smeltery itself works:
![image](https://user-images.githubusercontent.com/40274384/215904374-65101f8d-8a1e-4e39-ac38-311c6a7ef6a4.png)

### Your Proposal

fix it.

It broke somewhere between 1.9.12 and 1.9.16 tinkers version.

That doesnt narrow it down much though since @Alexdoru  did a big refactor:
![image](https://user-images.githubusercontent.com/40274384/215904505-083f7e07-100f-425e-a598-47933b6b27cb.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by runcreeper** [comment]
Just to clarify this occurs with the Java 19 version for me as well.

**Comment by eigenraven** [comment]
Should be fixed by <https://github.com/GTNewHorizons/TinkersConstruct/pull/70>

**Comment by chochem** [comment]
working in 9-dev
