### ISSUE TITLE
Project: Reactor rebalance

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#12451]
### Your GTNH Discord Username

iouter

### Your Pack Version

2.2.8

### Your Proposal

now, the reactor is unbalanced, it's not fun anymore, unlocked all its components at once in ev, the vacuum reactor is too powerful (or rather else reactor too weak or too expensive). so, i want to buff the reactor and add more components to make it more fun.

### Your Goal

this is my goal now:
1.add more components and more fuel rods, allowing the player to make more choices on the reactor, make this more powerful and fun. 
2.add advance components to make the reactor can be gated.
3.add magic components and fuel rods to reward players who play magic.
4.if possible, add more ways to use reactor.
5.a way to reduce losses after explosion

about these goals, i need more suggestions.

### Your Vision

let players have more choices at ev-luv.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by cainiaojun** [comment]
2x and 4x Glowstone Rods, which can make sunnarium faster than UU-matter method.

**Comment by cainiaojun** [comment]
Ichorium Cell: 480k, can be repaired by Ichor or Infusion. (I have no idea which to choose)

**Comment by iouter** [comment]
i think that if the player played the magic mod, then he should be rewarded. but rewards shouldn't be too much op.

i want to see more interesting designs, so i will start by adding new components.

**Comment by Dream-Master** [comment]
Can we add a new reactor multi to gt?

**Comment by iouter** [comment]
> Can we add a new reactor multi to gt?

what mechanism will it have? and i think the ic reactor is good enough.

**Comment by Dream-Master** [comment]
The fluid nuke is to weak and have to less stuff we can configure.  This "dry" varriant (no fluids) is ok but why we cant output multiple amp. And the Block must be much larger then this. Its a pocket Reactor. And the time between switch it on and off should be longer like a reactor in rl.

**Comment by InTheBackOf** [comment]
> The fluid nuke is to weak and have to less stuff we can configure.
It is not too weak. The only thing that cause it weak is GT++'s XL SHsteam Turbine in LuV instead of IV. So fluid nuke need many SHsteam turbine. A nuke with 1483HU/s need 14 turbine, 7 for SHsteam and other 7 for steam, only make ~34000EU/t. 
If here have XL SHsteam Turbine. 5 nukes only need 2 XL turbine. More effectly is it.

**Comment by Steelux8** [comment]
You will not be able to fix or replace IC2 nukes in their roles that easily. I'll start by replying to these points you made:

> 1.add more components and more fuel rods, allowing the player to make more choices on the reactor, make this more  powerful and fun. 

We already have plenty of custom rods, possibly as many as the rods that existed originally. However, almost none of the more expensive ones are used because they're not that powerful, they come too late in progression and documentation about them is not very good. Adding more components is not a good enough fix, and choices will be made redundant anyways when someone finds the optimal builds.

> 2.add advance components to make the reactor can be gated. 

IC2 nukes are placed around two tiers: EV and IV. You can use them in LuV to reach fusion, but there's only around 2 full tiers in which they're meant to be used: gating mechanics for something like this won't accomplish much.

> 3.add magic components and fuel rods to reward players who play magic. 

I don't see why magic powergen has to be built into nukes that follow realistic concepts. Magic power should come from its own setups.

> 4.if possible, add more ways to use reactor. 

Adding more ways is only worthwhile if you know to balance them well. Pre-LuV powergen balance is very hard to work with.

> 5.a way to reduce losses after explosion

Redstone control already minimizes the chance of explosions, and you can wall off the reactors with specific blocks. I don't see how explosions can be even less damaging than this, especially since fluid nukes don't even explode, but instead melt a couple blocks into lava and shut down.

**Comment by Nxer** [comment]
> Can we add a new reactor multi to gt?

Built-in a simulator GUI (like IC2 nuke) . 
At runtime, generate corresponding input and output models.
Centralize IO requirements.
Solve scalability and performance pressure at the same time.
I think of these  ^^_

**Comment by iouter** [comment]
>We already have plenty of custom rods, possibly as many as the rods that existed originally. However, almost none of the more expensive ones are used because they're not that powerful, they come too late in progression and documentation about them is not very good. Adding more components is not a good enough fix, and choices will be made redundant anyways when someone finds the optimal builds.

not just fuel rods, also components such as heat vent. the one problem with the custom rods is that it has too much heat, only can be used with coolant cell. these fuel rods absolutely need balance. the optimal build is inevitable, i want let the player choose which "optimal build" to use based on available components and its cost.

>IC2 nukes are placed around two tiers: EV and IV. You can use them in LuV to reach fusion, but there's only around 2 full tiers in which they're meant to be used: gating mechanics for something like this won't accomplish much.

when you get the fusion, that's basically the end of the luv. so that's 3 tier, short ev, long iv, and a relatively long luv. this also allows the optimal build to change by tier.

>I don't see why magic powergen has to be built into nukes that follow realistic concepts. Magic power should come from its own setups.

not magic powergen, i'm thinking of magic components that are slightly more powerful in some point. and wouldn't it be cool to combine magic with technology.

>Adding more ways is only worthwhile if you know to balance them well. Pre-LuV powergen balance is very hard to work with.

this one is hard and I don't have any ideas on it yet.

>Redstone control already minimizes the chance of explosions, and you can wall off the reactors with specific blocks. I don't see how explosions can be even less damaging than this, especially since fluid nukes don't even explode, but instead melt a couple blocks into lava and shut down.

reactor is the most destructive compared to other generators, and all components will disappear. i think reducing the frustration of a reactor explosion is worth discussing.

>Players already have tons of options in those tiers. I ask you to consider rebalancing what exists first, instead of reworking one of the most popular and essential powergen setups.

because the reactor is the most important, balance the reactor first. then let the other generators balance according to the reactor.

**Comment by iouter** [comment]
and this is definitely a long-term project that needs a period of testing and balancing.

**Comment by iouter** [comment]
> It is not too weak. The only thing that cause it weak is GT++'s XL SHsteam Turbine in LuV instead of IV. So fluid nuke need many SHsteam turbine. A nuke with 1483HU/s need 14 turbine, 7 for SHsteam and other 7 for steam, only make ~34000EU/t.
If here have XL SHsteam Turbine. 5 nukes only need 2 XL turbine. More effectly is it.

too much expensive, vacuum reactor only need 1 reactor and 2 vacuum freezer(hv or ev? i forgot), then you can get 43600eu/t. 
the only disadvantage is it has the risk of explosion, but you can use ic2nc or sfm control.

**Comment by joshaup1999** [comment]
> > The fluid nuke is to weak and have to less stuff we can configure.
> 
> It is not too weak. The only thing that cause it weak is GT++'s XL SHsteam Turbine in LuV instead of IV. So fluid nuke need many SHsteam turbine. A nuke with 1483HU/s need 14 turbine, 7 for SHsteam and other 7 for steam, only make ~34000EU/t. If here have XL SHsteam Turbine. 5 nukes only need 2 XL turbine. More effectly is it.

I dont get how you calculated that a 1483HU reactor needs 14 turbines total. A 1344HU reactor only needs 6 total with Ori turbines, this was prior to the addition of HSS-E so it could be the same amount for higher power output. I havent run the numbers yet with HSS-E

**Comment by InTheBackOf** [comment]
> I dont get how you calculated that a 1483HU reactor needs 14 turbines total. 

Oh, it is a mistake. Maybe i input a wrong number and copy to there.

**Comment by chochem** [comment]
> and this is definitely a long-term project that needs a period of testing and balancing.

I have to agree with dream. ic2 reactor is not particularly great and the mod is ARR anyway. Why not rather spend all that energy of a long-term project into an existing or new gt or gt-addon reactor?

**Comment by BritishCynic** [comment]
I would definitely be in favour of a Nuclear Reactor implemented on the back of GT code rather than IC2. Of course, _that's an ideal world_ view, this would definitely have to be a long-term project, but I think if it were to be realised it would have significant benefits.

**Comment by iouter** [comment]
any ideas on new gt reactor mechanism?

**Comment by Steelux8** [comment]
> any ideas on new gt reactor's mechanism?

I vaguely remember fission reactor mechanics in other mods. I think it's a good idea to go through those mods and see what ideas are worth considering and then adapt them to our pack.

**Comment by Glease** [comment]
So everyone is asking for a GT reactor, but who is going to do it? I like IC2 reactors and I'll probably stick to it, so not me.

**Comment by cainiaojun** [comment]
I like the mechanism of IC2 reactor, so I think the best idea is let the one who wants a GT reactor make it.

**Comment by iouter** [comment]
thoughts now:

components:
ender heat exchanger: excharge heat with components two grids away.
???: swap power generation and heat generation (too much magic).

feature:
add water/fluid cooling
show neutron moderator for fast neutron reactor
fertile, fertile efficiency
supercritical, subcritical
more mechanism in gt6?
nerf coolant cell?
xenon poisoning?

new reactor must have:
freedom

other mods:
nc/br: 3d, but i think the 3d reactor is difficult to design
hbm: also 3d? has xenon poisoning, complicated
gt6: more types of reactors with more variables, many mechanism

safe:
nothing now

**Comment by iouter** [comment]
that's plan now
[new nuke reactor.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10966181/new.nuke.reactor.txt)

1.  where is the gate control?
2. advantages of gas-cooled reactor.
3. advantages of each coolant.

**Comment by mitchej123** [comment]
I'm not in favor of any changes to ic2 nukes.  We need a gt reactor so we can yeet ic2 ;)

**Comment by Steelux8** [comment]
> I'm not in favor of any changes to ic2 nukes. We need a gt reactor so we can yeet ic2 ;)

But we need to decide mechanics for this reactor, which I thought was the point of this issue.

**Comment by iouter** [comment]
> You'll need to find a better way to present this. I don't really understand the concept, or why this is better than what we have, etc.

the Fuel Rods receive neutrons to produce heat and more neutrons, and then heat is converted to energy via steam(at least nominally). the first neutrons is provided by the Startup Neutron Source.
these current mechanisms are all made with reference to real life (except the accelerator), i want more mechanisms to improve these, but i have run out of ideas, so I need more suggestions.
in short, i wanted a more complex, more contradictory, more fun reactor. either ic2 or a new reactor both fine.

> I'm not in favor of any changes to ic2 nukes. We need a gt reactor so we can yeet ic2 ;)

i dont want 3d because i think it's hard to design, i dont want these lose the freedom to design, so these looks like ic2, and then i refer to the real life design mechanism, so these looks like hbm.
