### ISSUE TITLE
Limit voltage overclocking on advanced assembly lines

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12459]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.9-dev8

### Your Proposal

Limit the voltage overclocking of the advanced assembly line so that it cannot use the laser bin to make higher-order items at low voltage。

限制进阶装配线的电压超频，让它不可以在低电压的时候通过激光仓来制作高阶物品

### Your Goal

The laser bin in advanced assembly lines should not be used as a jump of a large number of voltage levels. It should be limited to prevent people from using the laser bin to jump to a higher level at a low voltage. For example, it is possible to make T8 rockets in LUV and even IV

进阶装配线的激光仓不应该被作为跳跃大量电压等级而存在，应对其进行一定限制，阻止人们在低电压的时候就能利用激光仓跳跃到高阶。例如在LUV甚至IV就能够制作T8的火箭

### Your Vision

Limit the overclocking level of the advanced assembly line to ensure that the early and mid-game runs do not jump quickly

限制进阶装配线的超频水平来保证游戏前中期的运行，不至于快速跳跃阶段

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by iouter** [comment]
https://github.com/GTNewHorizons/GigaGramFab/commit/938d5ca92ab5652885a7b5cb1674ad42da14feff
