### ISSUE TITLE
Botania Asgardandelion and Infinitato recipe change

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#12454]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.2.8

### Your Proposal

Asgardandellion doesnt use any of the botania materials and is a creative item, and the Infinitato is a meme recipe

### Your Goal

Change the Asgardandellion to a more neutral recipe
![image](https://user-images.githubusercontent.com/45178400/217290744-df4f0781-bda2-4290-bd01-70063dfd5631.png)
 It uses all the mana generating flowers and infinty plates instead of ingots
 
Make the Infinitato recipe more god looking
![image](https://user-images.githubusercontent.com/45178400/215813906-0ee1029e-ff1a-44c8-9f59-e6c0cacec179.png)
Since is a permanent potion effect giver, it uses all the botania incenses

### Your Vision

I thing this is a great change, at least the Asgardandellion one.
In addition, the dice of fate could be removed from the creative mana tablet, and put the Asgardellion in the middle

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Mr-Jeany** [comment]
Sounds logical...

**Comment by Alastors** [comment]
Don't think anything is going to come of this, maybe one day

**Comment by EnderProyects** [comment]
The first recipe if someone in a future wants to add it it should be something like this:

        ItemStack creativeFlower = new ItemStack(ItemBlockSpecialFlower.ofType("Asgardandelion"));
        ExtremeCraftingManager.getInstance().addExtremeShapedOreRecipe(
                creativeFlower,
                
                "R0D0B0E0M",
                "000iii000",
                "d0iIIIi0n",
                "00iIFIi00",
                "T0iIIIi0r",
                "010iii010",
                "t1102011H",
                "001121100",
                "e0K131S0m",
                'R', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_ARCANE_ROSE)),
                'D', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_DANDELIFEON)),
                'B', new ItemStack(ItemBlockSpecialFlower.ofType("Beegonia")),
                'E', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_ENTROPINNYUM)),
                'M', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_MUNCHDEW)),
                'd', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_DAYBLOOM)),
                'n', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_NIGHTSHADE)),
                'T', new ItemStack(ItemBlockSpecialFlower.ofType("Tainthistle")), 
                'r', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_RAFFLOWSIA)),
                't', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_THERMALILY)),
                'H', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_HYDROANGEAS)),
                'e', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_ENDOFLAME)),
                'K', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_KEKIMURUS)),
                '3', new ItemStack(ItemBlockSpecialFlower.ofType("Soarleander")), 
                'S', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_SPECTROLUS)),
                'm', new ItemStack(ItemBlockSpecialFlower.ofType(LibBlockNames.SUBTILE_NARSLIMMUS)),
                'F', new ItemStack(LudicrousBlocks.infinitato),
                '1', new ItemStack(LudicrousItems.resource, 1, 3), //Neutronium nugget
                '2', new ItemStack(LudicrousBlocks.resource,1, 0), //Neutronium block
                'i', "plateInfinity",
                'I', "DoubleplateInfinity" 
        );

**Comment by xingjiFIUG** [comment]
Personally, I think the design of this synthetic formula is unreasonable. For example, some raw materials of mana generating flowers can only be obtained by traveling on the map, and there is no other way to obtain them. The best example is Spectrolus, the raw material of this plant is Deathbloom, and Deathbloom will only appear in ominous wood. I used Nature's Compass to run for 200,000 meters without finding it. So the rationality of this formula is doubtful.

**Comment by EnderProyects** [comment]
Just saying, but you know the recipe has already changed again, right? xd

**Comment by FourIsTheNumber** [comment]
> there is no other way to obtain them.

Bees, including the most basic bees found in wild hives or even preloaded in village apiaries can produce all of these flowers.

**Comment by xingjiFIUG** [comment]
> > there is no other way to obtain them.
> 
> Bees, including the most basic bees found in wild hives or even preloaded in village apiaries can produce all of these flowers.

There is no recipe for these flowers in nei

**Comment by EnderProyects** [comment]
If you want that....
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18769

**Comment by FourIsTheNumber** [comment]
> There is no recipe for these flowers in nei

That's because they are not a direct bee product, they are spawned by the "flowering" effect.

**Comment by xingjiFIUG** [comment]
Thank you very much for your patient answer
