### ISSUE TITLE
Twilight Trophy consistency

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#12453]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.2.8

### Your Proposal

Add an extra item to each trophy recipe so you can put them all on the same input bus without crafting anything else unwanted

### Your Goal

Aside from adding consistency to recipes and making them a bit different, these items would make more sense, leaving the salis mundus by default:
- Fiery Blood: add one of Coagulated Blood and make a recipe for this one in the fluid solidifier.
- Snow Queen Blood: one snow ball 
- Lich Bone: two bones
- Naga Scale: four any tipe leave
- Fiery Tears: two of salis mundus
- Carminite: four of redstone

### Your Vision

The recipes looks nicer this way, and its not so complicated, they are basic items

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LazyFleshWasTaken** [comment]
This seems completely unnecessary. You need maybe 4-8 lich bones, and then if you're using fiery blood, you can just make it with ghast tears and ur-ghast trophy. I don't think any other trophy has a use, besides maybe getting the drop once or twice, but why automate it then?

**Comment by EnderProyects** [comment]
1 Why not, is a small change that only affects that all the recipes can be made at the same bus
2 There is also more consistency in the recipes, so you use the salis to make a magic version of that item, with the trophy as catalyst
3 There are more trophy items that are used in other recipes, and you need some of them, if you dont want to automate it you dont need to, but for example someone that want to make all the bracelets, or that want to craft magic solid super fuel, or that want to make some of the recipes that uses magical wood yes ( carminite)

**Comment by EnderProyects** [comment]
Also a new recipe could be added for the aurora block, using the snow queen trophy, 32 of salis mundus and 1 Ztones aurora block

**Comment by chochem** [comment]
careful with aurora. thats not just decorative but a helium source. would need proper balancing

**Comment by EnderProyects** [comment]
+ and 1 helium cell / 1000L in a bus
