### ISSUE TITLE
Nerf Magneto Resonatic Circuits

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#12450]
### Your GTNH Discord Username

Cainiaojun

### Your Pack Version

2.2.9

### Your Proposal

1. Change the soldering material needed in making Magnetio Resonatic Circuit. From IV it should start to use Molten Indalloy 140 and use Mutated Living Solder from UHV at the same amount of Soldering Alloy.
2. Replace the SMD Circuit Components with Advanced and Optical ones. From IV the common SMD circuit components should not be allowed to use. And the Advanced and Optical ones should behave the same as making normal Circuits. The same amount discount, the same time discount.
3. Double the amount of Magneto Resonatic needed in making Magnetio Resonatic Circuit. For example, a UEV Magnetio Resonatic Circuit needs 16 Exquisite Magneto Resonatic. Change it to 32.
4. Double the amount of low-tier circuit needed in making Magnetio Resonatic Circuit. For example, a UEV Magnetio Resonatic Circuit needs 16 UHV Magneto Resonatic Circuit. Change it to 32.

Maybe idea 3 and 4 nerf the Magneto Resonatic Circuit too much so they are for reference only

### Your Goal

Now the Magneto Resonatic Circuits are too cheap to make compared with normal ones. Many players are talking about use Magnetio Resonatic Circuits instead of Wetware and Bio Circuits to avoid expensive superconductors and other materials. Because the Circuit Assline has perfect overclock, it has a significant advantage compared with normal Assline, especially considering the Neuro Processing Unit and Bio Processing Unit, which can only be made with Assline at a low speed.

### Your Vision

Make Magneto Resonatic Circuit impossible to make and force players to make normal ones.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
I thought no one would use those meme circuits. It's by far the least efficient way of doing circuits.

**Comment by cainiaojun** [comment]
> I thought no one would use those meme circuits. It's by far the least efficient way of doing circuits.

I submit this issue because there are players who are making them. They were talking at QQ instead of Discord so you didn't know.

**Comment by Glease** [comment]
You will probably want to forward more info than this, e.g. how they made it, their current tier, how much they are able to make.

**Comment by chochem** [comment]
1 and 2 certainly make sense. 3 and 4 would need numbers to support that, yea.

**Comment by iouter** [comment]
now advanced circuits require a lot of advanced materials and components, but Magneto Resonatic Circuit doesn't. Its disadvantage is  needs recursion, but advantage is only needs recursion.

**Comment by cainiaojun** [comment]
I am trying arranging their ideas and calcuating the statistics we need, which may need some time.

4 seems to be ridiculous according to the reaction the players that are making Magnetio Resonatic Circuit reacts.

I remember Indalloy starts at Crystal? It is IV.

**Comment by chochem** [comment]
indalloy starts with LuV recipes. I am not talking about circuit tiers, you cant make crystal in IV.

**Comment by Steelux8** [comment]
More concrete numbers are definitely needed, it's one thing to see that a group of players are doing something unusual and another to find out how effective it really is, if at all.

**Comment by chochem** [comment]
I dont think numbers are really needed for 1 and 2. That is just consistency with the changes we did for other circuits.

**Comment by Steelux8** [comment]
Even with those changes, Magneto circuits might still be too cheap, or they might not be. The only way to know for sure is to check the numbers more closely.

**Comment by Tyrantgtnh** [comment]
Even with current magneto circuits the recursion alone along with being gated kinda far makes them not useful at all imo. 1 and 2 wouldn't be a bad change for consistency though.

**Comment by Nxer** [comment]
Actually, none of these will be used if you buff them . Now is PCB's Age , Magneto Circuits has no use . (Time is the biggest cost)

**Comment by chochem** [comment]
@cainiaojun happy enough for me to close this? I really don't think more is needed.
