### ISSUE TITLE
OC Components do not have recipes anymore

### ISSUE THREAD

**Issue by GDCloudstrike** [GTNewHorizons/GT-New-Horizons-Modpack#12463]
### Your GTNH Discord Username

GDCloud#2907

### Your Pack Version

2.2.9-8-pre-dev

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Trying to craft opencomputers parts for optical circuits (memory tier 3.5 for example), expected them to have recipes

### The Reality

They do not have recipes anymore

### Your Proposal

Re-add their recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@boubou19 have this todo with the sanitizer changes ?

**Comment by MarchingCube** [comment]
@GDCloudstrike Do you have recipes for input buses? Wondering if this is the same issue since in my 2.2.9-8-dev instance I cannot craft one.

**Comment by GDCloudstrike** [comment]
> @GDCloudstrike Do you have recipes for input buses? Wondering if this is the same issue since in my 2.2.9-8-dev instance I cannot craft one.
Nope, input buses don't have recipes either

**Comment by MarchingCube** [comment]
Block itself is from base GT but I have no idea what registers crafting recipe.
