### ISSUE TITLE
Macerating concrete bucket gives too much iron

### ISSUE THREAD

**Issue by thomas-lehericy** [GTNewHorizons/GT-New-Horizons-Modpack#12468]
### Your GTNH Discord Username

Nicopaganini

### Your Pack Version

2.2.0.0

### Your Server

Epsilon (official)

### Type of Server

Don't know

### Your Expectation

Crafting a concrete bucket : 
1 empty bucket (given back) + 1 water bucket + etc

macerating a concrete bucket : 
6 iron dust + etc

Since a bucket costs 3 iron to make, we have an extra 3 iron dust. 

This recipe seems to still be in 2.2.8.

### The Reality

see above.

### Your Proposal

Reduce the number of iron dust given to 3.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
probably stupidly autogenerated from the crafting recipe that takes 2 buckets (but gives one back!)
