### ISSUE TITLE
GT input/output hatches/buses below UEV tier don't have recipes

### ISSUE THREAD

**Issue by GDCloudstrike** [GTNewHorizons/GT-New-Horizons-Modpack#12466]
### Your GTNH Discord Username

GDCloud#2907

### Your Pack Version

2.2.9-8-pre-dev

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Expected GT input/output hatches/buses below UEV tier to have recipes

### The Reality

They don't

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@GTNH-Colen seems to be the same error like the single block machines has no recipes. Can you check ?
