### ISSUE TITLE
"Tile entity (entity name eg. IronChest at x,y,z) is meesing up with render states" In-game chat mess.

### ISSUE THREAD

**Issue by BaDaeEV** [GTNewHorizons/GT-New-Horizons-Modpack#12461]
### Your GTNH Discord Username

BaDaeEV#5907

### Your Pack Version

2.2.0.0

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Hey guy's, i need to turn off that, at this moment i cannot fix that just by myself.

### The Reality

![image](https://user-images.githubusercontent.com/118268366/216045559-41cbd165-1ef0-45a1-aa1f-346df9a6728e.jpg)

### Your Proposal

I need help with it, wish me luck :D

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by dahgul333** [comment]
endestorage
![image](https://user-images.githubusercontent.com/35747549/218258814-f36cdde3-54c5-4df6-9080-1b8d3a4fa198.png)
also malisis,botania ,thaumcraft etc ...

**Comment by dahgul333** [comment]
![image](https://user-images.githubusercontent.com/35747549/218258963-1c30a5e7-95c2-49e7-8c5a-df7ee3d1623a.png)
![image](https://user-images.githubusercontent.com/35747549/218258969-b6a65810-e04f-484c-8388-e39140237a41.png)
![image](https://user-images.githubusercontent.com/35747549/218258985-0965037d-869b-4498-99b3-f6c382e2af5b.png)
![image](https://user-images.githubusercontent.com/35747549/218258995-c6bf2a49-9837-45bc-b22f-aac713fcb346.png)

**Comment by dahgul333** [comment]
as i figured it out 
![image](https://user-images.githubusercontent.com/35747549/218259162-d9481555-1b1b-4ad8-aee6-6ad44289bb45.png)

**Comment by jollycar** [comment]
If anyone is searching where to set it to false: hodgepodge.cfg
Line 25/26:

`# Enable GL state debug hooks. Will not do anything useful unless mode is changed to nonzero.`
`B:renderDebug=false`

**Comment by Glease** [comment]
Huh weird, aren't these off by default?

**Comment by jollycar** [comment]
No, I just downloaded `GT_New_Horizons_2.2.9_(MMC)_Java9.zip` again from official sources and it's set to `true` by default

**Comment by Glease** [comment]
ah yeah. I was reminded the renderDebug is supposed to be true by default. It's the renderDebugMode that should default to 0. Maybe we should redo the renderDebugMode hotkey code so it's unbind by default. Currently there is no way to rebind it at all.

**Comment by chochem** [comment]
this looks resolved
