### ISSUE TITLE
Add XP gain for Tinkers Tools with mining speed below 1

### ISSUE THREAD

**Issue by vidaj** [GTNewHorizons/GT-New-Horizons-Modpack#12465]
### Your GTNH Discord Username

Vidaj#2601

### Your Pack Version

2.2.8

### Your Server

StoneLegion

### Type of Server

Don't know

### Your Expectation

Created a Tinker Hammer with the following tool parts:
- Carbon hammer head
- Carbon large plate
- Carbon large plate
- Obsidian tough tool rod

The tool ended up with mining speed 0.6. 

I expected that when I'm mining blocks with the hammer, the hammer should gain tool XP.

### The Reality

When mining, the hammer doesn't gain any XP.

If I swap out one of the carbon plates with a certus quartz large plate, the mining speed is 1.06, and the tool leveling works as expected.

### Your Proposal

Update iguana tool xp gain to handle mining speeds below 1.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
This is not a bug, but intended behavior by Iguana's, so I've turned this issue into a suggestion.

Iguana's only rewards tool XP when the block can be harvested by the tool and when the tool is sufficiently ["strong"](https://github.com/GTNewHorizons/IguanaTweaksTConstruct/blob/9ef99b513d4239ee666c28984ef641c216b9075c/src/main/java/iguanaman/iguanatweakstconstruct/leveling/LevelingActiveToolMod.java#L63). Where strong is a tool with a mining speed >= 1.0 as you've already noted.

A Carbon Hammer (or Lumberaxe, or whatever) is just a flimsy tool, I don't think the tool XP reward calculation needs to be adjusted here.
