### ISSUE TITLE
Advanced assembling line won't work in latest dev

### ISSUE THREAD

**Issue by tankobuman** [GTNewHorizons/GT-New-Horizons-Modpack#12478]
### Your GTNH Discord Username

tnkB#4563

### Your Pack Version

GTNH-2.2.9-9 pre dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Advanced assembling line should work fine

### The Reality

My Advanced assembling line was working properly but after update to latest dev (GTNH-2.2.9-9 pre dev, ggfab 0.1.6) it won't work. 
Downgrading ggfab 0.1.6 to 0.1.5 fix it.

### Your Proposal

fix it please

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Which recipe do you try and which energy hatch(es) do you use?

**Comment by minecraft7771** [comment]
And which recipe?

**Comment by tankobuman** [comment]
wetware mainframe & neuro processing unit
