### ISSUE TITLE
Ztones mod's Cycling between blocks feature isn't good

### ISSUE THREAD

**Issue by epic-coder-2976** [GTNewHorizons/GT-New-Horizons-Modpack#12472]
### Your GTNH Discord Username

euclid#7460

### Your Pack Version

2.2.7

### Your Proposal

Add the option in config or the game to turn it off, OR to rebind the keys to my liking, OR to tie the "Ctrl" function to minecraft's Sneak button.

### Your Goal

I am using a layout where the easier to hit Shift is set to Sprint, which is what it does by default in most videogames, and Ctrl is similarly set to Sneak.
Building with Ztones in creative (or, i imagine, in survival with creative flight) changes the ztone tile in my hand too often.

### Your Vision

Creativity without hinderance

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by nickdev456** [comment]
I like this change, please reconsider adding it.

I have crouch bound to Ctrl. You cannot place Ztones blocks at all while holding control, thus I cannot place Ztones blocks at all while holding crouch. This makes it very annoying to work with them.

**Comment by UltraProdigy** [comment]
Not that it's impossible, but ZTones is ARR so it's unlikely this issue is picked up
