### ISSUE TITLE
Remove or Buff the GT++ Th232 recipe by allowing boric acid to be made with Boron

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#12488]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.2.8

### Your Proposal

The current recipe looks like this:
![image](https://user-images.githubusercontent.com/49487505/216776070-120f0dbe-c751-4570-b465-4815282cd116.png)
I think this recipe's job is to provide players with a easier but less efficient way to convert Thorium into Th232, as the current line for that is almost 1:1 but needing more multies. And players already would have to make the titanium or higher Chemplant for T3 planets (that's about IV , and Th232 is used to unlock arcanite, which is an IV recipe that gates some gt++ multies). So I think up to this point the recipe is doing it's job quite well, it provide players with a less efficient method without gating the progression.
However,
It takes 1500mb of Boric acid to run this recipe, which then the recipe looks like this:
![image](https://user-images.githubusercontent.com/49487505/216776266-e17b4b5a-dea7-4f7a-9eae-b385c1270293.png)
It takes 23 pieces of BORAX dust to make and it's only from ore byproducts from salt veins. However, player at T3 would have access to Ross's Bart ores that gives Boron as byproduct.(as borosilicate glasses are everywhere in recipes,multis and stuff, players almost always will stockpile tons of boron at this point) ( The discussion to remove ross should not matter in here) But players would have to backtrack to mine salt ores for the same amount of 4 Boron dust to make this boric acid if they want to use this method. At T3 salt ores are basically not worth the extra effort because you can draw and process salt water for way faster for chlorine.
![image](https://user-images.githubusercontent.com/49487505/216776386-38ca952a-e700-410a-82a7-51e2898cba9f.png)
 (which evaulates to about at least 115 crushed salt ores) 
I think either allow boric acid to be made with Boron(Not allowing that is weird choice imo) for providing players at T3 a nice method to skip the Th232 line for now(as it's a pretty big loss compared to the line). Or just dump this method in favor for the Th232 line.

### Your Goal

QOL

### Your Vision

QOL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by tommy307507** [comment]
Note that I understand this is also a recipe in the Kevlar line and I dont think allowing crafting with boron will break anything. As borax dust in T7 is a common choice at that tier for players to get Boron compared to Boron byproducts from ores, it shouldn't matter to T7 players if that there's an alternative way of making this acid.

**Comment by vovaksenov** [comment]
Especially considering how little reason there is to actually mine/process salt ore, now that salty root exists.

**Comment by tommy307507** [comment]
Hey, is this suggestion not planned or considered not balanced? May I get some words from steelux

**Comment by chochem** [comment]
according to Reflex, who just wrote quests for th232, the chemplant way is literally already the best option and using the LCR/EBF route is basically a trap/mistake. I dont fully agree with that, but I dont see any reason we should buff the path that is already considered the strongest.

**Comment by tommy307507** [comment]
Allowing players to make boric acid with pure boron is for qol instead of a buff. Some might call it a buff as in iv, getting borax with salt vein is much slower and tedious than ores on Ross(T3 planet) . I suggested this mainly to reduce tedium, not for getting tons of Th232 easily, because ZnTh alloy is still way better in terms of ratio.

**Comment by Pxx500** [comment]
GT++ Thorium 232 is pretty much a one step recipe, while the proper Thorium232 line is several multis. Once GT++ recipe becomes easily automatable/easy to scale there will be no point to the longer more efficient line, since no one would care about efficiency when cost of GT++ line is this low

**Comment by tommy307507** [comment]
The difference between getting tons of borax or boron in iv for boric acid is repeating the same thing, i.e. placing miners on salt/ross veins and finding new ones when they run out, also ross requires T3 rocket + fuel to get to. Ore processing for borax is even cheaper in new update due to multiblocks buff, you can even do it efficiently without getting to iv tech. I don't see easier repeated labor being a huge favor for players to prefer boron recipe, as it still consumes the acid, while ZnTh is mostly recyclable. For that you just need to provide Th, Chemplant for Th232 is a popular short term solution now, and pretty much everyone will switch to ZnTh after the first few batches of arcanite.
