### ISSUE TITLE
Crash while loading SP 

### ISSUE THREAD

**Issue by oliverbejder** [GTNewHorizons/GT-New-Horizons-Modpack#12498]
### Your GTNH Discord Username

Oliver#2033

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Trying to login into my singleplayer world 

### Crash Report

[crash-2023-02-05_18.05.17-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10611651/crash-2023-02-05_18.05.17-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
I already fully explained this to you on discord

**Comment by chochem** [comment]
its also a duplicate, you are not the first :P 
e.g. https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11899, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12111
