### ISSUE TITLE
GT++ multiblocks get stuck on recipes that are impossible to complete, subsequently ignoring valid recipes.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#12493]
### Your GTNH Discord Username

Abdiel Kavash#2431

### Your Pack Version

2.2.0.0

### Your Server

Singleplayer, tested in creative mode.

### Type of Server

Single Player

### Your Expectation

If a multiblock has ingredients for several different recipes in its input buses/hatches, and one of the recipes can not be run for some reason, the other recipes should still be processed if their conditions are met.

### The Reality

Steps to reproduce the issue:

Build a GT++ multiblock mixer with the following components:
- Controller, muffler, maintenance hatch, at least LV energy hatch.
- Input hatch of any size.
- Input bus with at least two slots (LV or higher).
- Output bus of any size.

Provide the mixer with steady power, enable processing in it, make sure that void excess mode is **OFF**.

Fill the input hatch with water (at least 216L).
Set the phantom circuit on the input bus to [1].
Insert a piece of Bone Meal into the input bus and wait for several seconds.

The mixer has a circuit [1] recipe to turn water and bone meal into Water Mixed White Dye. However, since the mixer has no output hatch, and void excess mode is disabled, the recipe does not start. So far this is expected behavior.

Now insert a piece of Draconium Dust into the input bus.

There is a mixer recipe that takes a bone meal and a draconium dust and creates Floral Fertilizer (Botania). My expectation would be that, since all ingredients for the recipe are present, and the mixer has a valid empty output bus, this recipe would be processed.

However, in reality, the multiblock just sits idle and does not do anything. In fact, in this state, even if I add any other recipe into the input bus, it will not get processed by the mixer, even if the new recipe does not use or produce any fluids at all. The only way to make the mixer process anything at all is to either:
- Remove the bone meal (or water, or circuit) from the inputs.
- Add an output hatch to the structure (which produces white dye into the new hatch).
- Turn on voiding mode (which consumes bone meal and water, produces white dye, and voids it).

Additionally, getting the mixer into the stuck state depends on the order in which you place the ingredients into the input bus. With the same setup as above, starting with empty inputs, do the following:

Fill the input hatch with water, set the phantom circuit on the input bus to [1].
Place draconium dust into the input bus first.
Then place bone meal into the input bus too.

In this situation, Floral Fertilizer gets produced correctly, even though the dye recipe is still "available" (although unable to be run due to the lack of output hatch and disabled voiding mode).

I have originally run into this issue with a different set of recipes (in the middle of the Monaline), but I can reproduce it with any recipe that outputs a fluid. I have not tested this with other multiblocks that support voiding prevention, but I assume that they will all have the same issue.

Machines silently shutting down and requiring manual unclogging because of inserting input items in the wrong order is very unintuitive and frustrating to diagnose.

### Your Proposal

When a multiblock with voiding mode disabled encounters a recipe that it can not process due to insufficient output space, it should not stall forever until that particular recipe is made possible or removed. It should instead consider other items in its input buses/hatches and attempt to process other recipes which might have a valid output.

I realize that this issue only manifests with "secondary" recipe conflicts, when the inputs of two different recipes can together create a third item. As long as one machine processes only one recipe at a time, this will not occur (the recipe either runs or it does not). I understand that issues caused by these "secondary" conflicts are fairly low priority; nevertheless, I think that the machine completely shutting down and not processing anything at all is a more serious problem than it producing a wrong output in case of a conflict.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
The multi does not know which recipe you want. So this is pretty unsurprising. If it has ingredients for multiple possible recipes that is a user mistake.

How would the machine know that you arent interested in recipe 1 and just want to wait until the output has space (since you told it not to void!).

**Comment by AbdielKavash** [comment]
One of the recipes is possible to make, one of them isn't. I have expected the machine to work on any available recipe that it can complete. I don't need any kind of well-defined order of priority of recipes, but I would like the machine to work if it *can* work on something.

If this is currently intended behavior, could I change this issue to a feature request?

**Comment by chochem** [comment]
from what you said both are possible to make

**Comment by BlueWeabo** [comment]
The problem you are seeing that the recipe check doesn't care if it will void or not. As the recipe check only searched from ingredients and found the water mixed dye first instead of the floral fertilizer. There isn't really any way to prevent that unless the recipe check does the void protection.

**Comment by chochem** [comment]
basically what you are suggesting is that in ''no-voiding mode'' it goes over all valid recipes to see if anything has output space. correct?

**Comment by CatsLeftEar** [comment]
The most easy example is electrolyser. it wont work unless you input exact stacks of ingridients that are in the electrolyzer recipes. So you cant just input all your dust because if its not evenly divided by recipe amount, it will stop electrolyzing next dust after finishing with the first dust

**Comment by chochem** [comment]
> The most easy example is electrolyser. it wont work unless you input exact stacks of ingridients that are in the electrolyzer recipes. So you cant just input all your dust because if its not evenly divided by recipe amount, it will stop electrolyzing next dust after finishing with the first dust

no thats not true. if you dont have the full recipe it doesnt happen. source: I own a multi electrolyzer

**Comment by AbdielKavash** [comment]
> basically what you are suggesting is that in ''no-voiding mode'' it goes over all valid recipes to see if anything has output space. correct?

Correct, that is what I am suggesting.

**Comment by chochem** [comment]
that might need a deeper code rewrite. I leave it open for sure, maybe some dev agrees and wants to take it on.

**Comment by desagas** [comment]
> The multi does not know which recipe you want. So this is pretty unsurprising. If it has ingredients for multiple possible recipes that is a user mistake.

All multiblocks from my understanding already check for valid recipes if one fails, for all inputs, like the EBF, it will check if one is valid, first, specifically for the previously successful recipe, and if that fails, it will check again, for all inputs currently in its input inventory.

So, what you said is actually not inline with how GT multiblocks have been designed, or how they work, but maybe my user experience has always bugged in this regard, because that is how every pack I have played with GT has worked. It is entirely this new code that does not work in a similar fashion, and that is where my suggestion came from.

**Comment by chochem** [comment]
just read the rest and dont stop up there lol. its all explained

**Comment by miozune** [comment]
Resolved by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2247
