### ISSUE TITLE
Blockrenderer shows maceration stack wrong - autoplace is incorrect too

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12506]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.2.9-9-pre-dev

### Your Server

sp

### Type of Server

Single Player

### Your Expectation

it should actually form and be functional if one follows the preview.

### The Reality

![image](https://user-images.githubusercontent.com/40274384/216855627-c2cf7092-b0b6-429b-bc47-2cb5ecc5a91b.png)

this doesnt work. it needs outputs on all the upper tiers too.

### Your Proposal

fix it. :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Fiyorin** [comment]
looks like this was fixed already: https://github.com/GTNewHorizons/GTplusplus/commit/23543172c014c23a740148c3c9c2668fde574f96#diff-364b8fced2c63b555a5aed68b93e0a7379af5c9ac6a7deef6022a4a33f16f034
