### ISSUE TITLE
Fluid pattern terminal NEI crash

### ISSUE THREAD

**Issue by mattgriffi** [GTNewHorizons/GT-New-Horizons-Modpack#12507]
### Your Pack Version

2.2.9-9-pre-dev

### Your Server

SP

### Type of Server

None

### Your Actions

Open a fluid pattern terminal. Check the recipe of an item in NEI. Click or shift-click the ? to create a pattern from the recipe. The game crashes. This only happens in the fluid pattern terminal. All other pattern and processing pattern terminals work fine.

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10636859/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by asdflj** [comment]
try to update nee

**Comment by Alrightsc** [comment]
This issue is still present in the new 2.2.9 dev - crashing as I add anything from NEI to pattern in fluid pattern terminal.
