### ISSUE TITLE
Book of biomes from witchery has biome pages shifted by 1

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#12500]
### Your GTNH Discord Username

Keyla#3300

### Your Pack Version

2.2.8

### Your Server

Own server

### Type of Server

Ultramine

### Your Expectation

tried to get a page of Boneyard (page 311), got eldritch (page 310) instead. page 312 gives you boneyard though. When you are getting a paper, it will still be written the biome from the page, but the potion of changing biomes will show the real one.
I dont know from which page they start to shift like this

### The Reality

-

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Silkizuad** [comment]
I've encountered this as well, both in 2.2.8 and in 2.3.0 RC1.
Gave it a bit more look, and there's either a missing page or unobtainable biome that is still obtainable. The change happens between pages p198 (Mesa Plateau M) and p199 (Frozen Ocean). When trying to get Frozen Ocean, you get the page for biome "marsFlat", which doesn't seem to have it's own page. Every biome after that is shifted by one. It's possible to check what biome page you've actually obtained by linking it in the chat. The tooltip will still show the intended biome, but the item shown will portrait the actual biome you'll get when using the page in rituals or biome changing potions.
![image](https://user-images.githubusercontent.com/10547877/222406282-1b195717-8383-4a58-a865-1f033f58dd79.png)

**Comment by Caedis** [comment]
Bug is in galacticraft.

Only affects servers as the biome registration is dynamic so the server has all of them registered while the client most likely wont unless the player goes to that planet.
