### ISSUE TITLE
Can't Set Item in GT Item Filter

### ISSUE THREAD

**Issue by SSWZDDTI** [GTNewHorizons/GT-New-Horizons-Modpack#12513]
### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Grab item and click on the left side of gt item filter will set what item to filter.

### The Reality

Virtual item at left side will directly pop out and become a real item.

### Your Proposal

Fix the bug

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Are you really on 2.2.8? It should have been fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1543. Check if your GT version is >= 5.09.41.168

**Comment by SSWZDDTI** [comment]
Sorry I forgot to check the version at start menu. It is 2.2.7
