### ISSUE TITLE
Blockrenderer for neutron activator broken

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12516]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.2.9-9-pre-dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

should show things correctly.

### The Reality

I think a picture says it all:

![image](https://user-images.githubusercontent.com/40274384/217036604-9986e86c-f198-42d3-8d1e-195bbf5580fd.png)

### Your Proposal

fix it. :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Fiyorin** [comment]
i was staring at the source code for too long but couldn't find where it's wrong.

the hints show up fine, it builds with the hologram projector, but just the blockrenderer shows it incorrectly.

**Comment by Dream-Master** [comment]
works
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/2970688/33d08e3a-6d80-436c-8ec2-37e61073c156)
