### ISSUE TITLE
Some thought on redesigning GT solar panels

### ISSUE THREAD

**Issue by chris1380** [GTNewHorizons/GT-New-Horizons-Modpack#12522]
### Your GTNH Discord Username

Chris1380#7237

### Your Pack Version

2.2.8

### Your Proposal

Redesign/Improve current solar generators. Suggestions to changing current items are briefly discussed in #12437 but this proposal is about completely redesigning the system.

### Your Goal

Make GT solar energy a reasonable way for power generation, and nerf op features/ add more realistic features.
Or adding a post-EV powergen method based on direct solar-electricity conversion.
Make it a comparable substitute to other post-EV/IV generators.

### Your Vision

Current issue with solar power (from my point of view): 
1. Too expensive in early and mid-game. Require ~2.5 higher energy levels to make at earlier stages of the game, drops to ~1 level at later stages. Reasonable decision but makes solar cells rarely used by people. Agreed that solar energy should not be considered at beginning stages but it should become a more reasonable option after EV/IV.
2. Current solar panels require sidetrack technology unnecessary for other purposes. 
3. At later stages of the game when solar panels are _maybe_ affordable in large quantities, there are alternatives that are much cheaper, produce a lot more energy, and also do not need any maintenance (Referring to #12437, ). 
4. Only capital cost, no maintenance cost, which is kind of unrealistic and makes it too op (which is the main reason for high cost).

My thoughts:
Make solar panels more realistic:
1. Solar panels has durability that affect max efficiency, and decrease with time, speed of which affected by dimension, unrapairable.
2. Need revising~~Output of 1/16A per cell, each single block produces 4A max (or 1A with OC upgrade? Low priority.).~~
3. Need sunlight, output (in amps) changing w.r.t:
   a) Height (atmospheric effects) 
   b) Planet, galaxy (amperage linearly increasing wrt effective solar irridance) 
         *Space stations: unaffected, always generate max possible power (modify cost?)
   c) Time

Additionally, 
 1. Require doped single crystal semiconductors to produce single cells. Use current doped wafers (mostly p-type) but add recipes to make n-type wafers as raw material for cells. 
 2. Remove twilight forest materials as they clearly does not make sense in solar panels.
 3. Remove lower-tier solar panels as war material for higher-tier panels
 4. LV-IV panels require assembler in cleanroom, IV+ Panels require Precise Assembler.
 5. Still require MV superconductor for LV panel, HV superconductor for MV panel, etc.
 6. Potentially large multiblock solar farms available at LuV/ZPM, ignore durability, require UV voltage or something from t2/t3+ fusion to make; power up to 1A max equivalent, using UV panels.

Will add more later. 

e
### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
For "post-EV powergen based on solar", see the GT++ Solar Tower.

**Comment by chris1380** [comment]
> For "post-EV powergen based on solar", see the GT++ Solar Tower.

I should make it clear that the main idea is to make _solar panels_ as a comparable IV-stage powergen substitute, apart from nuclear(which is being redesigned currently), and lightning rods(which is powerful during IV-LuV but fps and mspt unfriendly). 
And yes, I am aware that there is a concentrated solar tower available at early IV (requiring alloy blast smelter only), but the power is generated by steam turbines, so that still counts as a normal generator. I couldn't get it to work properly but I did some calculations and found the power output is just uncomparable with other iv-stage powergen methods. the max possible efficiency is within the range of a basic 40 quad u238 nuclear plant (which is available back in early EV). (Correct me if I am wrong) And not to mention it takes up a lot of space and needs precise controlling for max efficiency.

**Comment by xiPakuL** [comment]
For me, solar panels fit the niche of "offshore small idepent automations power supply" really nicely and i don't think they should be an option for larger main-base power gen.
I really like multi-machine or chain solutions that do not consist of "one block output power" but require more to be built around it.
Even the solar tower is not standalone which makes it better designed for me.

**Comment by chris1380** [comment]
> For me, solar panels fit the niche of "offshore small idepent automations power supply" really nicely and i don't think they should be an option for larger main-base power gen. I really like multi-machine or chain solutions that do not consist of "one block output power" but require more to be built around it. Even the solar tower is not standalone which makes it better designed for me.

Automations that only work during the day? Really?
