### ISSUE TITLE
High Current Industrial Arc Furnace tooltip

### ISSUE THREAD

**Issue by King65868** [GTNewHorizons/GT-New-Horizons-Modpack#12523]
### Your GTNH Discord Username

King#4098

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

None

### Your Expectation

The arc furnace tooltip says the size is nx3xn (WxHxL) and I expected that to be true. 

### The Reality

The height is variable instead, instead of the width.

It also says processes 8 items per voltage tier x W/L, not sure if that’s incorrect though. 

### Your Proposal

Fix the tooltip. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by joshaup1999** [comment]
Have you placed the controller on the top centre block? Cause the height is definitely 3 tall as mine is working in 2.2.8

**Comment by King65868** [comment]
Woops, nwm

**Comment by King65868** [comment]
Was correct actually, my arc furnace is 7 blocks tall

**Comment by King65868** [comment]
> Have you placed the controller on the top centre block? Cause the height is definitely 3 tall as mine is working in 2.2.8

3 tall works yes, as n can be 3,5, or 7.
