### ISSUE TITLE
InPureCore versions after 1.1.2 fail to load a JavaScript engine on Java 8

### ISSUE THREAD

**Issue by jss2a98aj** [GTNewHorizons/GT-New-Horizons-Modpack#12527]
### Your GTNH Discord Username

jss2a98aj#3315

### Your Pack Version

N/A

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

When loading a world with InPureCore 1.1.3 or 1.1.4 installed and using Java 8, many items should be culled from NEI.

### The Reality

This appears in the log and nothing is culled from NEI:
[Client thread/INFO] [INpureCullingEngine]: Engine: JAVASCRIPT
[Client thread/WARN] [inpure|core]: Could not find a scripting engine for handling .js files. Available engine names: Scala Interpreter
[Client thread/INFO] [inpure|core]: A script error has occured. A log file has been created in config/INpureProjects/logs.
[Client thread/INFO]: [CHAT] §6[INpureCore]: §fA script error has occured. A log file has been created in config/INpureProjects/logs.

### Your Proposal

Someone that understands how this mod works should be able to restore intended functionality. Mitchej123 requested that I open this issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by jss2a98aj** [comment]
[202302071140-0.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10677573/202302071140-0.txt)
Additionally, here is the produced InPureCore log.

**Comment by Connor-Colenso** [comment]
Pack can't be released in this state so going to upgrade to major, NEI is absolutely flooded with random microblock parts, drums, tinkers etc.
