### ISSUE TITLE
Don't allow multiblocks to lost items

### ISSUE THREAD

**Issue by TheByKotik** [GTNewHorizons/GT-New-Horizons-Modpack#12525]
### Your Pack Version

2.2.8

### Your Proposal

Patch all multiblock to prevent lost items in inputs

### Your Goal

Removing illogical behavior

### Your Vision

It just makes everything more logical and comfortable. At the moment, all multiblock structures are simply unprofitable to use due to unstable behavior.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
it works perfectly fine if you provide enough power. Not sure what you want us to do about that, as it's a mechanic from the game: if you want easy machine process, you spam the single blocks, as it keeps the recipes on power failure, if you want efficient process, you must power your machines properly. It's just a mechanic here to push you to have a stable power grid.
