### ISSUE TITLE
Hardened clay shall consist of two clays

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#12526]
### Your Pack Version

2.2.8

### Your Proposal

Hardened clay shall consist of two clays

### Your Goal

4 clay ball → 1clay block→ 1 Hardened clay block

Use mortar：
1clay ball→0.25clay dust
1clay block→1clay dust
1Hardened clay block → 1clay dust

Use a pulverizer：

1clay ball→0.5clay dust
1clay block→2clay dust
1Hardened clay block → 1clay dust（According to the law, it should be two）

### Your Vision

If the burning process will lead to less clay：
Use mortar 1Hardened clay block → 0.5clay dust

If not：
Use a pulverizer  1Hardened clay block → 2clay dust

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
that would make it inconsistent with the color versions.

Let's just leave it as. Not everything has to be lossy in the mortar. There is no such law.
