### ISSUE TITLE
Industrial Sledgehammer (GT++) does not accept an input hatch

### ISSUE THREAD

**Issue by MarchingCube** [GTNewHorizons/GT-New-Horizons-Modpack#12532]
### Your GTNH Discord Username

MarchingCube#5764

### Your Pack Version

2.2.9-9-dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

One could use GT++ forge hammer for optical line crafts that require fluid inputs (purified water).

### The Reality

Multiblock does not form since in https://github.com/GTNewHorizons/GTplusplus/blob/master/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialForgeHammer.java#L113 input hatches are not listed as valid inputs.

### Your Proposal

Fix structure check and adjust tooltip.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by MarchingCube** [comment]
It seems that there are recipes with fluid outputs as well. So output hatch needs to be allowed as well.

**Comment by chochem** [comment]
structure fixed indeed. but recipes don't seem to work yet.
