### ISSUE TITLE
Add a way to mass paint vacuum tubes, data cables, and power cables

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#12539]
### Your Pack Version

2.2.8

### Your Proposal

A way to paint large amounts of paintable wires/tubes in a single click. Shift r-click on paint can for example could paint an entire straight line of cables/tubes up to a certain distance. Or if you shift r-click on a laser hatch, it would paint the entire tube line up to and including the next target hatch. 

### Your Goal

When you get to the point of needing active transformers or large amounts of asslines, it can be quite a chore just painting all the tubes and hatches to make them connect. especially over long distances and large setups

### Your Vision

I believe this would be a very nice QoL feature for late game players. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by SafariXiu** [comment]
I also think there is a need for such a function, perhaps to add a dyed composite table to the laser tube? Just like AE cable

**Comment by miozune** [comment]
Added by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1863
