### ISSUE TITLE
Hunger drains unusually when you leave Twilght Forest

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#12530]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The hunger ticker should not be ticking when the player is stationary

### The Reality

After returning from the Twilight Forest, usually when going from Easy back to Peaceful mode, the hunger ticker persists on ticking down when the player is stationary. This seems to disappear if you log out of the game and back in again, no obvious debuff can be seen.

### Your Proposal

Try and find out what is causing this so that the hunger ticking can be properly reset to not tick after getting back from TF when the player is stationary.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I tried but its all fine on my end. Best guess would be that it has nothing to do with TF and just something about changing game modes.

**Comment by BritishCynic** [comment]
It seems to happen after combatting monsters

**Comment by chochem** [comment]
2nd try: went to TF, fought mobs, came back, stood still. Nothing again
