### ISSUE TITLE
new 4m and 16m storage component have incorrect recipes

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12544]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.2.9-9-pre-dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

1m->4m->16m

### The Reality

1m->16m, 4m is skipped

![image](https://user-images.githubusercontent.com/40274384/218096751-33bb4c0f-6183-4ab2-a535-486bc511626a.png)
![image](https://user-images.githubusercontent.com/40274384/218096774-92d8851d-4baf-4248-a26b-0f9303007c4e.png)

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
yes we need to redo a lot of recipes and check all of them

**Comment by Dream-Master** [comment]
crafting cpu and some other stuff as well

**Comment by chochem** [comment]
was just a simple copy paste error
