### ISSUE TITLE
codechickencore with CCC with unimixins-all

### ISSUE THREAD

**Issue by Universal118** [GTNewHorizons/GT-New-Horizons-Modpack#12552]
### Your GTNH Discord Username

universe118#3841

### Your Pack Version

custom

### Your Server

custom

### Type of Server

Single Player

### Your Actions

trying to run falsetweaks with codechickencore 1.1.11 with unimixins-all

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10713791/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
unless things changed falsetweaks is not compatible with GTNH as the mod author specifically doesn't want that.

**Comment by chochem** [comment]
though you can check out whatever this person did: https://github.com/GTNewHorizons/GTNHMixins/issues/1#issuecomment-1370897369
