### ISSUE TITLE
Void ME Storage Cell (AE2 version) uses too much power

### ISSUE THREAD

**Issue by Crommus** [GTNewHorizons/GT-New-Horizons-Modpack#12555]
### Your GTNH Discord Username

Crommus#8127

### Your Pack Version

2.2.9-pre-dev with AE2 mods from jenkins

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Used the shapeless recipe to convert an EC Void storage cell to the AE2 version.

### The Reality

Putting it back in a drive dramatically increased the network's power usage, shutting it down in a few seconds. 

### Your Proposal

Probably an oversight, it should have the same power usage as the EC version.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
![image](https://user-images.githubusercontent.com/60341015/218448440-951dc478-05d3-47c5-a1f2-763acfcb2888.png)
![image](https://user-images.githubusercontent.com/60341015/218448485-4ed19416-026f-477a-999d-9d0a21af1312.png)
can't reproduce

**Comment by Crommus** [comment]
Apparently the EC void cell wasn't voiding before, so the subnetwork I was using it in had several ME output buses with billions of cached items that had nowhere to go. The AE2 void cell did work correctly, so when inserted in the drive it caused all the buses to push billions of items in the network, which I assume was the actual reason of the energy demand spike. After all the cached items were gone energy consumption went back to normal.

**Comment by GlodBlock** [comment]
then it isn't void cell's bug
