### ISSUE TITLE
Input hatch and input bus inconsistent behaiviour

### ISSUE THREAD

**Issue by Ydrec** [GTNewHorizons/GT-New-Horizons-Modpack#12553]
### Your GTNH Discord Username

Ydrec#7877

### Your Pack Version

2.2.9 predev 4

### Your Proposal

Input bus does not allow inserting items from sides(faces without input texture), however input hatch/quad input hatch does allow to insert fluid into it from sides. This behavior is inconsistent and break setups which rely on blocked input like interfaces in blocking mode.

### Your Goal

To allow for a bunch of AE automation setups with fluids and keep consistency of game mechanics.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
you forgot a proposal in your proposal. I certainly prefer input busses only taking items from one side. Makes the AL automation much easier. So does that mean you want hatches to be more restrictive?

**Comment by Ydrec** [comment]
Yes i want them to have same restrictions as input buses. Fluid p2p in 229 now properly transmits data necessary for blocking mode to work, so i need to connect it to a side of hatch in AL setup.

**Comment by AbdielKavash** [comment]
Could a cover or a toggle (click with some tool) be added to allow/restrict input for any side (whichever one is less desired as the default)? I know a few setups that could be simplified if I could input stuff into a bus/hatch from more than one side.

**Comment by Ydrec** [comment]
You already can use just any plate to block access from any side, however it has a different behavior of also blocking that side from appearing as holding fluid/item and such blocking mode just would considers that side empty.
