### ISSUE TITLE
New Universal Terminal

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#12566]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.2.9 with ae2fc-1.0.69-gtnh

### Your Proposal

Add new features for Universal Terminal from Wirelss crafting terminal:
 - Can be opened using hotkey
 - Can be placed in the Baubles slots
 - Magnet Card can be used
 - Magnet Card can be switched using hotkey

### Your Goal

These features were very useful and handy on the Wireless Crafting Terminal.

### Your Vision

This features will make new Universal terminal more user-friendly and handy.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by starstack14** [comment]
@GlodBlock

**Comment by asdflj** [comment]
@GlodBlock
