### ISSUE TITLE
Tinkers Construct lag when going up in slime islands

### ISSUE THREAD

**Issue by Polarite** [GTNewHorizons/GT-New-Horizons-Modpack#12564]
### Your GTNH Discord Username

Polarite#0001

### Your Pack Version

custom pack, not GTNH. using:

Tinkers Construct 1.9.19

### Your Server

https://modrinth.com/modpack/tsundere-nostalgia-blast official server

### Type of Server

Vanilla Forge

### Your Expectation

It not lagging client when going up in islands

### The Reality

It lags the player AND the server down to 5 frames/5 tps and it logs stuff like this:

https://paste.ee/p/jCF58

it lags after `Unable to play unknown soundEvent` part.

Logs are from a friend, same happens to me too.

### Your Proposal

I sadly have no idea how to fix this issue :(.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ilkerbey-01** [comment]
[fmllogs.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10716880/fmllogs.zip)

Here is the whole fml logs

**Comment by chochem** [comment]
oh wait, thats not actually GTNH is it?

**Comment by ilkerbey-01** [comment]
its not, I am making a modpack and this issue is happening.

**Comment by chochem** [comment]
I don't think Tinkers is actively supported for use outside of GTNH (in contrast to NEI for example).

**Comment by ilkerbey-01** [comment]
I mean if its planned to be used in gtnh, this is still an issue, its not because of any other mod

**Comment by chochem** [comment]
yep if it occurs there the prio goes up.
