### ISSUE TITLE
Crash to desktop while loading world (Java 19)

### ISSUE THREAD

**Issue by TerraSleet** [GTNewHorizons/GT-New-Horizons-Modpack#12561]
### Your GTNH Discord Username

terrasleet#6213

### Your Pack Version

GTNH-2.2.9-9-pre-dev-Java-19-PrismL

### Your Server

SP

### Type of Server

None

### Your Actions

Client was left idle for ~1 hour after loading to title screen. After this I attempted to load my world and it crashed to desktop. Don't have any other info besides the crash log, sorry. Client is the 2.2.9-9 pre-dev Java 19 version, unmodified, using the Prism Launcher.

### Crash Report

[crash-2023-02-12_14.26.12-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10716326/crash-2023-02-12_14.26.12-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bengenie** [comment]
I got the same on my end but it different; it return to main menu (no crash log) and for some resome the world is still running.
console log: https://mclo.gs/7ef38hP

**Comment by KiloJoel** [comment]
Just got this as well in 2.2.8
