### ISSUE TITLE
Client Crash when stabbing things with TC's Knockback on it

### ISSUE THREAD

**Issue by ussdefiant60** [GTNewHorizons/GT-New-Horizons-Modpack#12567]
### Your GTNH Discord Username

ussdefiant60#6571

### Your Pack Version

2.2.9qf-Java9

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I Attempted to stab a chicken with my Rapier with Knockback and other things on it. A prior instance of the same was had with a skeleton. I have had no successful attacks with my Rapier in 2.2.9.

### Crash Report

[crash-2023-02-12_14.58.00-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10717412/crash-2023-02-12_14.58.00-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Edguardia** [comment]
I had the same issue with a tinkers broadsword after hitting a concussion creeper.

Crash Report
[crash-2023-02-12_22.10.42-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10717439/crash-2023-02-12_22.10.42-server.txt)
