### ISSUE TITLE
crash ultramine 2.2.9 old java

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#12571]
### Your GTNH Discord Username

Keyla#3300

### Your Pack Version

2.2.9

### Your Server

Own server

### Type of Server

Ultramine

### Your Actions

tried to start the server

### Crash Report

[crash-2023-02-13_00.42.35-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10717636/crash-2023-02-13_00.42.35-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment]
hello, need the whole log of the server starting please

**Comment by chochem** [comment]
ah thats the same as the other, sorry, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12569
