### ISSUE TITLE
Advanced Muffler Hatch does not consume Air Filter durability

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#12577]
### Your GTNH Discord Username

Abdiel Kavash#2431

### Your Pack Version

2.2.0.0, 2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Using an Advanced Muffler Hatch with an Air Filter on a multiblock which generates pollution should consume one point of durability from the Air Filter with every pollution release.

### The Reality

It does not.

Pollution output into the environment is still reduced by the appropriate amount (including the filter), but the filter remains at full durability even after long periods of operation.

Tested with several different multiblocks and tiers of muffler hatches, with both T1 and T2 air filters.
Tested in both 2.2.0.0 and 2.2.8 in creative mode with the same result. Also tried manually crafting the filters just in case the ones spawned from NEI are unbreakable for some reason.

### Your Proposal

Advanced mufflers are already insanely good even without filters. Now one can get the filtered efficiency without ever actually using up any filters. This is overpowered. (Unless one modifies the server config to disable certain gameplay mechanics.)

Code that is supposed to consume filter durability:
https://github.com/GTNewHorizons/GTplusplus/blob/ead2c4639c4ec5c1a6e3285d266cd57de1f06227/src/main/java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_Muffler_Adv.java#L216

Strangely enough the same filters get properly damaged and used up in a Pollution Scrubber, which seems to be using basically identical code?
https://github.com/GTNewHorizons/GTplusplus/blob/ead2c4639c4ec5c1a6e3285d266cd57de1f06227/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/GregtechMetaAtmosphericReconditioner.java#L720

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Also it's worth noting adv muffler don't damage filter literally every tick. It does it once per 10000 pollution aggregated, so a 2500 use filter wears out after 25000000 would-be pollution has been processed by THIS muffler.

**Comment by AbdielKavash** [comment]
One of the machines I tested with was an Implosion Compressor, which should generate 10,000 gibbl per second (and thus release pollution and damage the filter every second). Pollution release was observed as expected using the portable scanner; the filter did not take any damage even after several minutes of operation.

**Comment by Glease** [comment]
Yeah, the bug is legit. I'm just more or less forwarding info on how this adv hatch works, given there is none on its tooltip.
