### ISSUE TITLE
AE2FC Certus Quartz Tank Content

### ISSUE THREAD

**Issue by CAHbl4** [GTNewHorizons/GT-New-Horizons-Modpack#12578]
### Your GTNH Discord Username

BeerHunter

### Your Pack Version

2.2.9

### Your Proposal

In EC2 we had the names of fluids in the Title. With the AE2FC version, there is no way to disguise the fluid inside.

### Your Goal

To have the ability to search for fluids in inventory.

### Your Vision

Add the fluid name to the tooltip.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GlodBlock** [comment]
added by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/0734dc4d0b30e75796f058b27cf5992693d85660
