### ISSUE TITLE
Scrolling items on pattern terminal grid causes crash

### ISSUE THREAD

**Issue by tankobuman** [GTNewHorizons/GT-New-Horizons-Modpack#12580]
### Your GTNH Discord Username

tnkB#4563

### Your Pack Version

2.2.9 + FTButil and lib

### Your Server

SP

### Type of Server

None

### Your Actions

Scrolling item on pattern terminal grid causes crash. 
Any item and crafting terminal  (even default) causes this.

### Crash Report

[crash-2023-02-13_21.00.48-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10721938/crash-2023-02-13_21.00.48-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by tankobuman** [comment]
It only happens on java9+ version

**Comment by Eranicus** [comment]
Can confirm , also just crushed while scrolling Me pattern processing terminal  (Java 9+)

**Comment by k3nw4y** [comment]
same happens with ME interface (java+9)
https://mclo.gs/gPx9K2D
