### ISSUE TITLE
Cells cannot interact with the UI of Railcraft Tanks

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#12584]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.2.9

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

To maintain previous behaviour of cells being refillable and emptyable using Railcraft Tanks

### The Reality

The cells cannot be placed at all into the UI of the tanks, nor right-clicked into them. This happens on both the J8 and J19 versions of 2.2.9.

### Your Proposal

Revert back to previous behaviour.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Btw in which version was it working? I went back to 2.1.2.0 and it didn't work either

**Comment by FloatDoubling** [comment]
Actually, cells never worked with RC tanks, even in 2.0.7.0 iirc.
