### ISSUE TITLE
Dual interface needs shared all sides blocking mode

### ISSUE THREAD

**Issue by Ydrec** [GTNewHorizons/GT-New-Horizons-Modpack#12588]
### Your GTNH Discord Username

Ydrec#7877

### Your Pack Version

Gtnh 2.9.9

### Your Proposal

Add a new toggle state to blocking button in interface gui to make it do a shared blocking check for all faces. So it would block any recipe from being outputted if any one side has any item/fluid.

### Your Goal

Currently dual interface in blocking mode would check for blocking individually per side. This generates a lot of problems for automation setups: Duals would ignore blocking to deliver pure fluid crafting orders if nearby chest is empty as It checks for blocking on chest, sees its empty, then fails to push fluid into chest and outputs it to any other side. Same for reverse with empty tank and only items crafting task.

This also prevents setups which require blocking if either tank contains fluid or inventory contains items as pretty much anything but ae2fc buffers can't move/accept fluids and items from same face of interface. Major pain when trying to automate complex multi blocks.

### Your Vision

Thia feature would allow to finally use dual interfaces in "item or fluid" blocking configuration and would allow to  bypass problems caused by #12181 and #12587. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GlodBlock** [comment]
concluded from https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12587 and https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12588:
- dual interface shouldn't output anything when anyside has fluid or item in blocking mode
- dual interface shouldn't output anything into eio conduit at any time in blocking mode
- dual interface should output item in eio conduit at last.

is there any missing or wrong? @Ydrec

**Comment by Ydrec** [comment]
@GlodBlock Yes that would fix the problem, though current block behavior may still have uses

**Comment by GlodBlock** [comment]
@Ydrec should interface push items into eio conduit when there is no item and fluid around it?

**Comment by Ydrec** [comment]
@GlodBlock fluid conduits work fine with blocking as they transmit fluid data to interface and don't need changing. 

Dual interface shouldn't start pushing items to item conduits while in blocking mode unless outputting excess items after it got unblocked on another side or if its set in non-blocking mode. Making it consistent with normal interface and allowing to use item conduits priority to send items in pattern order
