### ISSUE TITLE
HP alloy smelter can do MV recipes

### ISSUE THREAD

**Issue by viableusername** [GTNewHorizons/GT-New-Horizons-Modpack#12589]
### Your GTNH Discord Username

`¿Slime?`#6607

### Your Pack Version

2.2.0.0

### Your Server

Official Servers

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

I tried putting 3 Aluminium dust and 1 copper dust into High Pressure Alloy Smelter to create 4 aluminum brass ingots

It shouldn't work since it's an mv recipe
![ab-nei](https://user-images.githubusercontent.com/118540470/218602566-a034ceb5-83b6-490d-8645-f782b5c0eb52.png)

### The Reality

The HP alloy smelter (steam) can do MV recipes, only recipe i can confirm is aluminum brass ingot but if nei isn't wrong then all mv recipes are doable, the non-hp variant only does ulv/lv recipes
High Pressure steam machines can do MV recipes, only recipe i can confirm is aluminum brass (worked in hp alloy smelter but not in the LV smelter)
![ab-in](https://user-images.githubusercontent.com/118540470/218605022-0d947c8c-b750-48fd-bffa-d3811151f44b.png)
![bsdna](https://user-images.githubusercontent.com/118540470/218605455-100d7530-f94c-4863-abd9-2ae02241e66a.png)

![aslv](https://user-images.githubusercontent.com/118540470/218604427-ed671c1d-b861-469c-b66b-e454579b9f24.png)
![as-mv](https://user-images.githubusercontent.com/118540470/218600655-5c88f6a0-4d59-4b17-9322-85c8ac9c6799.png)
![as-steam](https://user-images.githubusercontent.com/118540470/218600656-b4be1d0b-0b23-49ec-b906-03baadc44fad.png)

### Your Proposal

change High Pressure machines recipes to match Steam/LV machine recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
that has always worked, not a bug.

**Comment by POPlol333** [comment]
> that has always worked, not a bug.

seem like a feature lol

**Comment by boubou19** [comment]
feature or not, the mere fact that you can do MV recipes 1 or 2 tiers below is questionable.

**Comment by viableusername** [comment]
> that has always worked, not a bug.

doesn't make sense for an LV machine to be able to do less recipes than a lower tier one, it's practically useless in that case

additionally if we compare MV and ULV/LV recipes, in an ULV/LV recipe MV overclocks, and HP doesn't, but in an MV recipe the HP runs at the same rate as MV, why wouldn't HP overclock ulv/lv recipes as well if it was intended to be as good as mv?
