### ISSUE TITLE
Recipes for Tinkesrs' Construct from gregtech Unstable ingots is not generated

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/GT-New-Horizons-Modpack#12582]
### Your GTNH Discord Username

@dahgul#1726

### Your Pack Version

2.2.0.0 ,2.2.7.0

### Your Server

Eta

### Type of Server

None

### Your Expectation

had tried to do :
![image](https://user-images.githubusercontent.com/35747549/218456967-fa438c27-dba2-4eab-9cb4-c7a85274e844.png)
from 
![image](https://user-images.githubusercontent.com/35747549/218457091-b9092b1f-a392-46b1-8a82-396955668534.png)

### The Reality

Recipes from greg-s Unstable ingots not generated
![image](https://user-images.githubusercontent.com/35747549/218457264-5fe042a1-7605-4bfa-ac24-738edb051bdd.png)
It just hasnt any extruder recipes 
![image](https://user-images.githubusercontent.com/35747549/218457580-18905de6-db1e-437b-a4ec-a9879bd88c9a.png)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I am not saying this is how it should work, but you can do:
alloy smelter ->semi-stable nuggets
crafting table -> unstable ingot (stable) from xutils
extruder -> plate
