### ISSUE TITLE
Use a MOD or script to automatically replace the EC2 fluid storage bus with the AE2FC fluid storage bus

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12590]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.9

### Your Proposal

Use a MOD or script to automatically replace the EC2 fluid storage bus with the AE2FC fluid storage bus

使用一个MOD或者脚本，让EC2的流体存储总线自动替换为AE2FC的流体存储总线

### Your Goal

Homes are too big and spread out, and manual replacement is too complicated and time-consuming

家里实在太大了而且十分的分散，手动替换太复杂并且费时间

### Your Vision

No need to rummage around the house looking for a hidden fluid storage bus

不需要再去翻遍家里找某个被隐藏起来的流体存储总线了

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
you make it sounds so easy lol. it isnt.

**Comment by SafariXiu** [comment]
> 

Ha ha, that's true, but I'm sure a lot of people would love to have this feature. After all, most people don't have the same level of archiving as some advanced players(

**Comment by firenoo** [comment]
I would be interested in scoping how this might work. Maybe will take a few days on planning to see what I come up with

**Comment by chochem** [comment]
firenoo has added replace methods
