### ISSUE TITLE
Conduit behaves wrongly with dual buffer

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#12597]
### Your GTNH Discord Username

Keyla#3300

### Your Pack Version

2.2.8

### Your Server

Own server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Wanted conduit to take items in a normal order, from last to first, like from any other container

### The Reality

Conduit started taking from what seems to be pretty random slots, works good every time with a normal diamond chest though

### Your Proposal

Make the order consistent

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by CatsLeftEar** [comment]
This breaks some automatisation when you want both fluids and items and you have both fluid and item ingridients in the recipe. For example, i wanted to use it in assembly line automation and ebf automation. I really wanted correct order to work, but it didnt, which causes a lot of problems for me and probably some other people who would want strict order of items in their setups

**Comment by CatsLeftEar** [comment]
For example, in this recipe it took 2 stone first, then alumina and carbon, then the last stone. Completely random and completely different order each time. Can forget about round robin with this bug.
https://imgur.com/jtMY7hb

**Comment by HikerL** [comment]
I have fogotten the actual behavior of item conduit in GTNH, but from my experience in using item conduit, the issue you report is because the conduit will remember the slot it took things out last time.

**Comment by CatsLeftEar** [comment]
> I have fogotten the actual behavior of item conduit in GTNH. Still, from my experience in using item conduit, the issue you report is because the conduit will remember the slot it took things out last time before the chest is clear. For diamond chest or larger chest it can't remember the slot due to the code limit. (But I'm unsure if it's right, for I used to play 1.12, and just get in touch with 1.7.10 GTNH)

i think it works normally with iron chests
