### ISSUE TITLE
Zombie brain recipe

### ISSUE THREAD

**Issue by loldapeep** [GTNewHorizons/GT-New-Horizons-Modpack#12591]
### Your GTNH Discord Username

peepdamonster#4415

### Your Pack Version

2.2.8

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Trying to craft zombie brain from one head and 1kL of smeltery blood

### The Reality

![image_2023-02-14_170308486](https://user-images.githubusercontent.com/70217220/218703194-f921ca2e-d54f-411a-bc83-a4695b8046be.png)
the recipe only works with gregtech blood which is unobtainable

### Your Proposal

make the smeltery compatible with the recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
i am not sure if the recipe need  smeltery blood or the Blood magic altar blood.

**Comment by EnderProyects** [comment]
If at the end you have to change something in the blood, could you add a recipe in the fluid solidifier that turns blood into coagulated blood?

**Comment by minecraft7771** [comment]
> i am not sure if the recipe need smeltery blood or the Blood magic altar blood.

The stuff thats in the blood altar yields the "Life Essence" fluid which is used in making BM slates.

**Comment by D-Cysteine** [comment]
The recipe might be using [Biomes O' Plenty blood](https://biomesoplenty.fandom.com/wiki/Blood), which I think you can just find in certain biomes in the Nether

**Comment by minecraft7771** [comment]
Maybe it would be worth to add a distillation recipe to convert it as alternative?

**Comment by Alastors** [comment]
Doesn't need a recipe, already drops 100% from angry zombies which can be spawned from EECs or from those obsidian obelisks

**Comment by boubou19** [comment]
Relying on mobs to get a unique resource is a bad design. It should have a recipe imo
