### ISSUE TITLE
Сrash on world startup Avaritia, Tinkers Construct

### ISSUE THREAD

**Issue by zircky** [GTNewHorizons/GT-New-Horizons-Modpack#12592]
### Your GTNH Discord Username

Zircky#6761

### Your Pack Version

2.2.9

### Your Server

Single Player

### Java Version

Java 8

### Type of Server

None

### Your Actions

When you try to load the world, it immediately throws you into the main menu of the game.

The following mod have been identified as potential causes: Avaritia, Tinkers Construct.

### Crash Report

[crash-2023-02-14_13.55.20-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10731730/crash-2023-02-14_13.55.20-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by AlexandrKanev** [comment]
Can confirm Tinker Construct related server crash, with almost the same crash log. In my case (as I play on dedicated local server) all running fine but crashes while im trying to fight a mob with any of Tconstruct tool: a sword, a pickaxe etc.
Tested on Java8 and Java9+ versions of 2.2.9 server all the same.

[crash-2023-02-14_16.48.19-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10733317/crash-2023-02-14_16.48.19-server.txt)
