### ISSUE TITLE
Renewable Lootbags and Questbook Completion

### ISSUE THREAD

**Issue by Rosenlied-Iris** [GTNewHorizons/GT-New-Horizons-Modpack#12599]
### Your GTNH Discord Username

Rosenlied#3858

### Your Pack Version

2.2.8

### Your Proposal

Lootbags should be obtainable through expensive, repeatable quests to prevent not-quite-softlock situations ("can't max out a tinkers weapon/can't finish the questbook even though you have a morbillion stargates")

### Your Goal

With the removal of the repeatable IV lootbags from chaos dragons, there is now no way to repeatably get most types of lootbag. While farming lootbags en masse is obviously not intended, this makes it possible to lock yourself of 100% completion from not having done all the lootbag trades. 

I don't think it's intended possible to be in a state where you have a 64-stargate network yet will *never* be able to get green checkmarks on every quest chapter in the book legitimately. Or "completed at least once" for the repeatable ones, at that.

Incidentally, this also shows the lack of repeatable sources for some of the other lootbags that could lock you out of 100% completion at lootbag trade tab of quest book, and thus the proposal: "Lootbag Synthesis" quests in coins tab, that take coins and field generators for corresponding lootbags (e.g. LV field generators for LV lootbags, adjust field generator amount as needed to balance). For bee/transportation/crop/... lootbags, those should take items of comparable cost that would make them inefficient but avoid the prior issues.

### Your Vision

While this doesn't solve all the issues highlighted above - particularly, the fact that some of the lootbag rewards are exclusive to them (creative tinkers modifiers, notably), and some other factors of "exploration/lootbag locked random progression boosts" (e.g. oblivion frames) - this would somewhat alleviate the former issue and would make it possible to legitimately complete every single quest in the questbook at least once, even the ones that aren't "worth it".

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
The issue of the Tinker modifier could be solved by just adding a creative recipe, avaritia or infusion one for example

**Comment by chochem** [comment]
handing out a few as a bonus does not mean they should be unlimited or have a recipe, no.
