### ISSUE TITLE
New Universal Wireless Terminal Part 2

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#12594]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.2.9 with ae2fc-1.0.69-gtnh

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Trying to change pattern using new universal wireless terminal. 

### The Reality

When i put encoded pattern into slot, there is no encoded recipe on the "crafting grid"
![image](https://user-images.githubusercontent.com/70205464/218752387-e971da87-4998-4e08-8749-e57c8c3be142.png)
![image](https://user-images.githubusercontent.com/70205464/218752442-287bd92e-5ef0-4cc5-881c-f0b132eae54f.png)
![image](https://user-images.githubusercontent.com/70205464/218752475-a8326b0e-dd3e-4a6a-9dc1-557ac104da39.png)

### Your Proposal

When i put encoded pattern into slot i want to see encoded recipe, like on the stationary terminals
![image](https://user-images.githubusercontent.com/70205464/218753132-6eab912f-b240-49c1-9388-083df6b09792.png)
![image](https://user-images.githubusercontent.com/70205464/218753182-53e19a98-d486-48a6-b66b-f2282e43deab.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/83

**Comment by RaitGamerGR** [comment]
Ah, okay, thanks
