### ISSUE TITLE
AE2 buffer input bus

### ISSUE THREAD

**Issue by JustBenji** [GTNewHorizons/GT-New-Horizons-Modpack#12608]
### Your GTNH Discord Username

Benji#0586

### Your Pack Version

2.2.2.0

### Your Proposal

Add a AE2 buffer input bus to machines.
Currently the stocking input bus is used with a subnet of a ME chest. In this chest (16000k cell.
To make it endgame, suggestion 1.
The ae2 input bus is infinite space
It requires 4x 16000k storage cells to make at least.
Available as UEV assembly recipe

### Your Goal

Avoid subnets with multiple stocking inputs being configured manually and reduce the stocking input bus amounts in general.

### Your Vision

Make endgame work more fluid with high amount of item requests

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by greesyB** [comment]
Possible duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11143
