### ISSUE TITLE
SkinPort - MIT license, support for modern skins

### ISSUE THREAD

**Issue by Rosenlied-Iris** [GTNewHorizons/GT-New-Horizons-Modpack#12602]
### Your GTNH Discord Username

Rosenlied#3858

### Your Pack Version

2.2.8-2.2.9

### Mod Name

SkinPort

### The Mod to Add

Adding built-in support for modern Minecraft skins, without the black bars.

### Your Reason

New skins on older versions display poorly - this should fix it and allow them to render normally.

### Preliminary Investigation

Attempting to add this mod to the 2.2.8 and 2.2.9 versions does not seem to have introduced issues, and this does not seem to significantly increase load time or lag.

This mod does not add any new items or features, and I assume it works on the client only as I couldn't seem to find a server file and it seems to work just fine on my locally hosted server - just not rendering for others without the mod.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by potato4444** [comment]
This is a mod I was considering my adding but to my own installation but did not to as it apparently causes rendering problems for Botania and Twilight Forest: https://github.com/zlainsama/SkinPort/issues/28, https://github.com/zlainsama/SkinPort/issues/9

**Comment by Rosenlied-Iris** [comment]
> This is a mod I was considering my adding but to my own installation but did not as it apparently causes rendering problems for Botania and Twilight Forest: [zlainsama/SkinPort#28](https://github.com/zlainsama/SkinPort/issues/28), [zlainsama/SkinPort#9](https://github.com/zlainsama/SkinPort/issues/9)

Wonder how hard it would be to fix this, and whether this would be on the end of a SkinPort fork or our Botania/Twilight versions.

**Comment by vovaksenov** [comment]
Mitch said foamfix adds support for newer skins as well, and since it is under lgpl, the related code could be transferred into hodgepodge or any other appropriate mod already included in the pack

**Comment by bombcar** [comment]
If someone who can reproduce the skin issue can try foam fix for 1.7.10 and confirm it fixes it, we can at least update the wiki.
