### ISSUE TITLE
Helium has two conflicting recipes in Replicator (Liquid vs Gas)

### ISSUE THREAD

**Issue by Shadowsoftime99** [GTNewHorizons/GT-New-Horizons-Modpack#12601]
### Your GTNH Discord Username

Shadows#4865

### Your Pack Version

2.2.0.0 (confirmed to exist on 2.2.8 as well)

### Your Server

Private

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I want to replicate Helium, and I expected to get the gas as the default form. Instead, I get the liquid form. This is especially inconvenient as there's a gas -> liquid recipe but NOT the other way around, so I can't get the gas at all.

### The Reality

So here's the issue. We have two recipes for "Helium", both using the Helium data orb, with no circuit or anything to disambiguate the one you want to run. So the Liquid one ALWAYS runs.

![image](https://user-images.githubusercontent.com/16748195/218953661-ce114602-e110-4519-85d3-73dc1a8c84ec.png)

![image](https://user-images.githubusercontent.com/16748195/218953687-e644a982-f710-4ba3-8bb5-6044857cd715.png)

### Your Proposal

Honestly, having the liquid helium recipe at all seems a bit funky. Most (all?) of the other elements only replicate into their "base" form, and then you have to handle the phase change yourself. We could just remove the liquid He replicator recipe wholesale. Alternatively, we could use a circuit or something to disambiguate between the gas and liquid recipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
liquid helium should be blacklisted. We cant generate plasma or other stuff than pure elements stuff

**Comment by minecraft7771** [comment]
Fixed by <https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/80>
