### ISSUE TITLE
Journey Map

### ISSUE THREAD

**Issue by Blocky106** [GTNewHorizons/GT-New-Horizons-Modpack#12604]
### Your GTNH Discord Username

Blocky#0377

### Your Pack Version

2.2.9

### Your Proposal

add a favourite option to the waypoints menu, so that the favorised waypoints are always at the top

### Your Goal

once you have to many waypoints it can get confusing and imo

### Your Vision

 if there would be a favorise button, it could improve the gameplay since you can make quicker menu interactions

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Add a 00 or similar prefix and sort by name instead of distance
