### ISSUE TITLE
Blur when I take item

### ISSUE THREAD

**Issue by undertakerJ** [GTNewHorizons/GT-New-Horizons-Modpack#12607]
### Your GTNH Discord Username

undertaker#2789

### Your Pack Version

2.2.0.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I'm tried to first time play it, for first look, almost all normal, but entities are invisible, and if i take item in my hand or open inventory entire screen is going blur

### The Reality

![image](https://user-images.githubusercontent.com/81556422/219112002-6fc98729-2f24-4922-8327-376cbf195b85.png)
![image](https://user-images.githubusercontent.com/81556422/219112041-4a3f7735-aa99-429d-947e-48f6b5ec75e3.png)

### Your Proposal

How to fix it?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
there are 2 options that people have claimed work:
1) backdate your drivers by 2 years
2) add neodymium mod (https://github.com/makamys/Neodymium, only works with optifine also added in latest release)
