### ISSUE TITLE
Dyson Swarm Problems 2.2.9

### ISSUE THREAD

**Issue by Eranicus** [GTNewHorizons/GT-New-Horizons-Modpack#12609]
### Your GTNH Discord Username

Eranicus#5476

### Your Pack Version

2.2.9-9dev

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

.

### The Reality

Dyson is not generating power after game is restarted ...

This screen is ones it is turned on. 
![Screenshot 2023-02-16 021648](https://user-images.githubusercontent.com/92493145/219214510-96264013-33aa-4f46-93df-7c62e80572ba.png)

and this one is after game restarted, the 3600sec cycle continues normal , but power is not generated 

![Screenshot 2023-02-16 021553](https://user-images.githubusercontent.com/92493145/219214629-2b2570bf-237e-4f3c-ac0c-6ae55c4f77b8.png)

Tested in T-Ceti and OW and both places are chunk loaded.

Also as far as I understood the config is wrong and should be 10mil per module with 10k modeles cap.  and 3.6 mil gelid cryotheum consumption. 

On the screens we can see 80k+ modules with 262k per module and only 1000 gelid cryotheum consumption...

### Your Proposal

Please fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
The power that modules generate is defined in the config file instead of code. To fix that try to regenerate the config file of galaxy space
