### ISSUE TITLE
The assembly line was unable to make the EOH case and the wireless power bin

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12603]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.9

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

The assembly line was unable to make the EOH case and the wireless power bin

### The Reality

I used AE to automatically fill the formula to make the sample, and sent it to the assembly line, but the assembly line did not start. I checked the formula sequence and fluid sequence, and there was no problem, and the flash memory was correctly placed in the data access warehouse

我使用AE自动填充了配方制作样板，发配到装配线中，但是装配线并没有启动，我检查了配方顺序与流体顺序，并没有任何问题，闪存也正确的放置在了数据访问仓中

### Your Proposal

The assembly line should work properly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
@SafariXiu can you confirm this is working now?

**Comment by chochem** [comment]
SafariXiu has confirmed on discord thta this works now
