### ISSUE TITLE
"Instance update failed because: Failed to read the assets index!" MultiMC error

### ISSUE THREAD

**Issue by Kinger-Burg** [GTNewHorizons/GT-New-Horizons-Modpack#12614]
### Your GTNH Discord Username

Kinder#4192

### Your Pack Version

2.2.9

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

1. I downloaded the 2.2.9 version (Client Prism/MMC Java 9+) from the Discord server.
2. Imported it to MultiMC
3. Every time I try to open the pack gives me the error : Instance update failed because: Failed to read the assets index!

### Crash Report

PollyMC version: 6.3

Launched instance in online mode

authserver.mojang.com resolves to:
    [54.230.232.55, 54.230.232.40, 54.230.232.58, 54.230.232.51]

session.minecraft.net resolves to:
    [18.214.12.3, 34.197.32.8, 100.24.172.95]

textures.minecraft.net resolves to:
    [13.107.238.44, 13.107.237.44]

api.mojang.com resolves to:
    [54.192.235.15, 54.192.235.94, 54.192.235.48, 54.192.235.56]

Minecraft folder is:
C:/Users/Beta Gabriel/AppData/Roaming/PollyMC/instances/GT_New_Horizons_2.2.9_(MMC)_Java9(2)/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 19.0.2, using 64 (amd64) architecture, from Oracle Corporation.

Instance update failed because: Failed to read the assets index!

Clipboard copy at: 16 Feb 2023 17:03:36 +0200

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
you are not using multimc, you are using polly. We do not support pirated Minecraft.
