### ISSUE TITLE
Fluid storage bus doesn't update when tank is broken/placed

### ISSUE THREAD

**Issue by Ydrec** [GTNewHorizons/GT-New-Horizons-Modpack#12610]
### Your GTNH Discord Username

Ydrec#7877

### Your Pack Version

2.2.9 predev 9 with ae2fc 1.0.56, 1.0.58, 1.0.67, 1.0.69 and 1.0.71pre

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

For fluid storage bus to be able to interact with tank when its placed before it. 

### The Reality

Fluid storage bus does not update when tank before it is broken and replaced. Ae can't output fluid to it or see/extract fluid amount in the tank until you either replace storage bus or update some setting in its gui. 
![busbug](https://user-images.githubusercontent.com/53411693/219227582-eeeaa260-6469-4d3f-83cb-07e58f99d9c9.gif)

Strangely it happens even in release right after the commit which should have fixed the bug. 
https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/ea4014fc1ecb74c02defac8717db08b540c96824

Found out that reloading the chunk updates storage bus and it starts working.

### Your Proposal

Add a check for block update/placement

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report. 
 *This was a closed issue on a2fc GlodBlock repo but i was told to move any issues to gtnh repo.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ydrec** [comment]
@GlodBlock can you take a look if this can be fixed before next stable comes.?

It is still happening in the latest ae and ae2fc builds

**Comment by GlodBlock** [comment]
can't reproduce it. am i doing something wrong?
![20230222211517](https://user-images.githubusercontent.com/60341015/220630976-11e33f8b-0f1c-4fc2-96ca-06bdbec17202.gif)

**Comment by Ydrec** [comment]
@GlodBlock Are you testing it in dev enviroment without some mods? I consistently get it in multiple versions of ae2fc, multiple pack versions and java8/java19 in both new and old world. Also confirmed this happens for other people in 2.2.11 The weirdest part is that i tested the fix at some point and it was working.

**Comment by GlodBlock** [comment]
i only tested it in dev environment. will check it in full pack later

**Comment by GlodBlock** [comment]
@Ydrec it only happens when ec2 is installed so it should be solved when ec2 is removed in next next stable

**Comment by chochem** [comment]
ec2 will be around this stable though
