### ISSUE TITLE
OAuth button doesn't open browser

### ISSUE THREAD

**Issue by cinch** [GTNewHorizons/GT-New-Horizons-Modpack#12617]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.2.9-9-pre-dev

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

after leaving the client open a long time, it shows "offline" as usual 
![image](https://user-images.githubusercontent.com/61357/219521737-8a428d5a-7b12-4b2e-b30b-6253f06df4fc.png)
click the button -> microsoft login should open a browser window 

### The Reality

no browser window opens and a NPE gets thrown
![image](https://user-images.githubusercontent.com/61357/219522092-61efde91-4f9e-49b5-9fe3-b560f051a77d.png)

workaround: restart the client

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/lwjgl3ify/commit/c622d3f3465aea9bf422b73cc236953fd60a904d
