### ISSUE TITLE
add method to filters input or output when searching with the advanced memory card

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#12615]
### Your GTNH Discord Username

Hucking#0193

### Your Pack Version

2.2.8

### Your Proposal

I suggest adding a way to filter to specifically input or output so when ur looking through your p2ps you can more easily bind inputs. I found quite often when looking for a specific input I have to sift through all the outputs.

### Your Goal

.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Hiagg** [comment]
yes please and make the gui be taller if it can fit in the screen space :(
