### ISSUE TITLE
LSC explodes when trying to send wireless energy as it uses the normal and laser hatches as voltage threshold

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#12620]
### Your Pack Version

2.2.7

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I was trying to send energy from BE to Overworld with 2 LSCs with wireless mode on. the 2 LSCs are bulit both with 9 UHV capacitors. The LSC on BE accepts energy generated by Dyson Swarm with a UMV 1048576 Laser, and the overworld one send energy using a UEV 65536 Laser. At that instance the server TPS is slightly below 20.

### The Reality

After minutes of waiting, energy was sent to the wireless network for a single time, but the LSC (on BE, the sender) exploded.
A backup was loaded, but the same explosion happend again.
The attempt to reproduce in singleplayer failed so I guess it was some server-client communication problem, or tps-related problem.

### Your Proposal

Fix the explosion.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
The LSC afaik has no explosion logic. So probably dyson exploded when it's dynamo hatch filled? Because that is a mechanic.

**Comment by BlueWeabo** [comment]
Question. How were you giving the drones to the dyson to fill it up?

**Comment by ChemEng227** [comment]
> Question. How were you giving the drones to the dyson to fill it up?

A ME Input Bus was used. At the moment the dyson had only around 10000 modules so I think the dyson shouldn't have exploded.

**Comment by BlueWeabo** [comment]
can you look into the explosion log to see what caused  the  explosion?

**Comment by minecraft7771** [comment]
Yes seems like the dyson exploded as explained before.

**Comment by ChemEng227** [comment]
> Yes seems like the dyson exploded as explained before.

But in the reproduction there was not even a dyson in the save; I used debug generators instead.

**Comment by ChemEng227** [comment]
I just did another reproduction and double-checked prievous logs. The log said "Energy Explosion, injected 1818156313541760EU/t in a 773094113280EU/t Machine!"
It seems that when sending energy to the wireless network some checking mistakingly compared the sending energy with the energy hatch...

**Comment by ChemEng227** [comment]
Sorry for the bothering but I meet the same problem again in 2.3.0RC.

**Comment by Hikari1nVoid** [comment]
LSC has an internal rate limit.When you exceed that then it exploded.

> The LSC afaik has no explosion logic. So probably dyson exploded when it's dynamo hatch filled? Because that is a mechanic.

We encountered another explosion event with LSC & GT wireless energy hatches.

**Comment by Hikari1nVoid** [comment]
Explosion.log says:
Energy Explosion, injected 73334457542003EU/t in a 24201134080EU/t Machine!
Machine at 8 | 141 | -6 DIMID: 250 exploded.[LSC Controller coordinates]

**Comment by Dream-Master** [comment]
@Hikari1nVoid @ChemEng227 did it explode with version 2.3.0 as well ?

**Comment by chochem** [comment]
> "Energy Explosion, injected 137438953472EU >= 2.74877906944E10Capacity of the Machine!"

just to preserve the info I posted on discord yesterday after looking into this for a second:
- the explosion mechanic seems to be in base gt (not kekztech/dyson/whatever)
- specifically https://github.com/GTNewHorizons/GT5-Unofficial/blob/f77689cb0ce4a8cecbd5958a5c51b7901525c5bf/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L1307
- given that number 2.74877906944E10 it seems to think that the capacity is just 2^37 and then explodes if >=5x that is injected.

however some of the logs are phrased slightly differently, so must be a different function. Are these all the controller or are either hatches?

**Comment by Hikari1nVoid** [comment]
> > "Energy Explosion, injected 137438953472EU >= 2.74877906944E10Capacity of the Machine!"
> 
> just to preserve the info I posted on discord yesterday after looking into this for a second:
> - the explosion mechanic seems to be in base gt (not kekztech/dyson/whatever)
> - specifically https://github.com/GTNewHorizons/GT5-Unofficial/blob/f77689cb0ce4a8cecbd5958a5c51b7901525c5bf/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L1307
> - given that number 2.74877906944E10 it seems to think that the capacity is just 2^37 and then explodes if >=5x that is injected.
> 
> however some of the logs are phrased slightly differently, so must be a different function. Are these all the controller or are either hatches?

The line I posted here is the controller energy explosion.The following explosions are "chain reaction" from the controller explosion.
As the controller exploded in Line 1 So I'll assume it's the first block exploded.

**Comment by chochem** [comment]
can you just post the log lol, why so cryptic?

**Comment by chochem** [comment]
ok luckily someone else provided me with a log. [Explosion.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10952237/Explosion.log) (starting line 15)

The above was just secondary. The first explosion is an overvoltage explosion https://github.com/GTNewHorizons/GT5-Unofficial/blob/daf7594696b55e7e9042e2af59215148080f5058/src/main/java/gregtech/api/metatileentity/BaseMetaTileEntity.java#L1947

the 'input voltage' is given here by lastinputtick https://github.com/GTNewHorizons/KekzTech/blob/47afd585fe8d3839c3d0373c1eddc72aa552a589/src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java#L769, with amperage 1.

dont quite understand how the machine voltage is determined from hatches.

**Comment by chochem** [comment]
its says the machine 'voltage' is  13 463 715 840 eu/t or 25680A UV.

based on the code here its just supposed to be sum of ampxvoltage
https://github.com/GTNewHorizons/KekzTech/blob/47afd585fe8d3839c3d0373c1eddc72aa552a589/src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java#L306

that would be 64a uv (normal)   4096uv and a 16384a uv(laser) -> = 20560A UV

so clearly I dont fully understand this yet. Either way the bigger question is why that applies to wireless transfers!

**Comment by miaowwwwww** [comment]
i'm the guy who provided the explosion log. a little more test by me. 2uhv capacitor transfer a full energy lsc into the wireless net did not go boom.

**Comment by Fiyorin** [comment]
same problem here (on a server, version 2.3.0, java 17). 

dyson on barnarda c -> uhv 1m a laser -> lsc with 1 uhv capacitor and wireless enabled -> leads to an explosion (twice, after restoring a backup)
explosion.log says the explosion came from the dyson controller block.

sofar so good with 2 uhv capacitors inside of it

**Comment by chochem** [comment]
@Fiyorin assuming my analysis is correct: temporary fix for LSC explosions should be to add the biggest (in terms of eu/t) laser input hatches that you can. you want to reach a very high nominal input eu/t from non-wireless. then wireless should be safe too.

**Comment by zgggz** [comment]
same problem at 2.3.0
dyson with 16k uiv laser sourse hatch -> lcs with 16k uiv laser target hatch and 1 UHV capacitor.
Worked normally until wireless mod was enabled. Immediately explosion after wireless enabled.
at log we see that first exloded machine - lcs controller.


Energy Explosion, injected 31 257 258 969 454 EU/t in a 687 194 767 360 EU/t Machine!
Machine at 105 | 77 | 178 DIMID: 32 exploded.
Explosion at : 107 | 78 | 178 DIMID: 32 NonWrench picking/Rain!
Explosion at : 107 | 78 | 178 DIMID: 32 due to near explosion!
Explosion at : 103 | 77 | 180 DIMID: 32 NonWrench picking/Rain!
Explosion at : 103 | 77 | 180 DIMID: 32 due to near explosion!
Machine at 67 | 77 | 187 DIMID: 32 exploded.
Machine at 65 | 77 | 187 DIMID: 32 exploded.
Machine at 72 | 75 | 184 DIMID: 32 exploded.
Machine at 71 | 77 | 180 DIMID: 32 exploded.
Machine at 76 | 77 | 185 DIMID: 32 exploded.
Machine at 69 | 76 | 179 DIMID: 32 exploded.

fix it pls.

**Comment by zgggz** [comment]
same problem at 2.3.0
dyson with 16k uiv laser sourse hatch -> lcs with 16k uiv laser target hatch and 1 UHV capacitor.
Worked normally until wireless mod was enabled. Immediately explosion after wireless enabled.
at log we see that first exloded machine - lcs controller.

Energy Explosion, injected 31 257 258 969 454 EU/t in a 687 194 767 360 EU/t Machine!
Machine at 105 | 77 | 178 DIMID: 32 exploded.
Explosion at : 107 | 78 | 178 DIMID: 32 NonWrench picking/Rain!
Explosion at : 107 | 78 | 178 DIMID: 32 due to near explosion!
Explosion at : 103 | 77 | 180 DIMID: 32 NonWrench picking/Rain!
Explosion at : 103 | 77 | 180 DIMID: 32 due to near explosion!
Machine at 67 | 77 | 187 DIMID: 32 exploded.
Machine at 65 | 77 | 187 DIMID: 32 exploded.
Machine at 72 | 75 | 184 DIMID: 32 exploded.
Machine at 71 | 77 | 180 DIMID: 32 exploded.
Machine at 76 | 77 | 185 DIMID: 32 exploded.
Machine at 69 | 76 | 179 DIMID: 32 exploded.

fix it pls.

**Comment by miaowwwwww** [comment]
i did some test and found that the explosion only happens when there is no other capacitor other then the Uhv capacitor. (For example, 1uhv +8empty explodes. 1uhv+7 empty+1ev doesn't explode, so if anyone don't want it to explode as a temporary fix, just add one more small capacitor.)

**Comment by chochem** [comment]
still very much exploding peoples bases, got another in discord today
