### ISSUE TITLE
QFT cannot output all products at once using ME output bin and ME output bus

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12628]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.10

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Using the ME output bin with the ME output bus in QFT, trying to output the product all at once to the ME network

在QFT中使用ME输出仓与ME输出总线，试图将产物一次性全部输出到ME网络中

### The Reality

ME output bin and ME output bus cannot output all items at once, items will be left in ME output bin and ME output bus

ME输出仓与ME输出总线无法一次性输出全部物品，物品会被留在ME输出仓与ME输出总线中

### Your Proposal

The ME output bus and ME output bin should deliver all products to the ME network at once instead of accumulating inside the compartment

ME输出总线与ME输出仓应一次性将所有产物输送到ME网络中而不是积压在舱室里面

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueWeabo** [comment]
Can you give more information as to how its broken

**Comment by BlueWeabo** [comment]
The only reason it won't output everything is if the network is full

**Comment by SafariXiu** [comment]
> No, I'm pretty sure that the ME output bin and ME output bus only in QFT is not able to output all products, in other machines there is no such problem

**Comment by SafariXiu** [comment]
> Can you give more information as to how its broken
Just like any other machine, put the ME output bin with the ME output bus and connect it to the ME network, that's all, but while running I scanned the compartment through the scanner and found more and more product buildup inside

**Comment by SafariXiu** [comment]
> Can you give more information as to how its broken

![Desktop 2023 02 18 - 17 49 39 02](https://user-images.githubusercontent.com/98251218/219853951-5a478767-29ee-439f-b030-c334c8d5b016.gif)

**Comment by BlueWeabo** [comment]
ME output hatches and ME output busses only output once every minute or 30 seconds.

**Comment by SafariXiu** [comment]
> ME output hatches and ME output busses only output once every minute or 30 seconds.

But I let the machine run for 2 minutes, the product in the machine compartment is still increasing

**Comment by SafariXiu** [comment]
I made sure there was enough room in my network for these products

**Comment by BlueWeabo** [comment]
is this only happening to the output hatch?

Also just looked in the code and its once every 2 seconds that it tries to send the outputs

**Comment by SafariXiu** [comment]
> is this only happening to the output hatch?
> 
> Also just looked in the code and its once every 2 seconds that it tries to send the outputs

This is the case in both the output bin and the output bus

**Comment by SafariXiu** [comment]
> is this only happening to the output hatch?
> 
> Also just looked in the code and its once every 2 seconds that it tries to send the outputs

He did try to output, but only part of the first one at a time

**Comment by BlueWeabo** [comment]
From the video you sent it can be see that the output hatch worked correctly. I am unsure what the problem is? Do you want the hatch to output everything every tick? If so that can't be done it would cause a lot of lag

**Comment by SafariXiu** [comment]
> From the video you sent it can be see that the output hatch worked correctly. I am unsure what the problem is? Do you want the hatch to output everything every tick? If so that can't be done it would cause a lot of lag

I think at the very least you need to be able to input all the products into the ME network at every output

**Comment by BlueWeabo** [comment]
Is that not every output? Also no. we cannot make the ME output hatch output whenever a multi outputs its fluids to it.

**Comment by SafariXiu** [comment]
> Is that not every output? Also no. we cannot make the ME output hatch output whenever a multi outputs its fluids to it.

GIF finally output all at once because I forced the machine to shut down, if not shut down the machine, he will not output all

**Comment by SafariXiu** [comment]
![image](https://user-images.githubusercontent.com/98251218/219854695-e991c0e6-dbf0-4f5c-b0d9-0fca358f8f12.png)
I used a simple red stone device to control the machine switch, which reduces the efficiency of the machine by at least 50 percent

**Comment by BlueWeabo** [comment]
So QFT doesn't allow the me output hatch and bus to output if its runnign constantly?

**Comment by BlueWeabo** [comment]
If so can you try to replicate it on other machines?

**Comment by SafariXiu** [comment]
> If so can you try to replicate it on other machines?

I'll try it. Give me a few minutes.

**Comment by SafariXiu** [comment]
> So QFT doesn't allow the me output hatch and bus to output if its runnign constantly?

It's that QFT's output bus and output bin are not fast enough to output so many items to the ME network at once

**Comment by SafariXiu** [comment]
Other machines have output buses and output bins that output all fluids and items at once, but QFT's can only output one at a time

**Comment by gjjjj-fmw** [comment]
I also have this problem。once i use the T4 QFT make pbi,only three fluids output into my network. at last ,there are 500G PBI in my me output hatch. Finally,I shutdown the QFT ,1s later,all the fulids output into my network.

**Comment by BlueWeabo** [comment]
That seems like a problem from the ME output hatch and not QFT then :concern:

**Comment by BlueWeabo** [comment]
Do you have a neutronium energy cell on your ME network?

**Comment by SafariXiu** [comment]
> Do you have a neutronium energy cell on your ME network?

yes

**Comment by gjjjj-fmw** [comment]
> Do you have a neutronium energy cell on your ME network?

yes
i have triple

**Comment by gjjjj-fmw** [comment]
![image](https://user-images.githubusercontent.com/125734357/219950441-fe5a7511-e5fc-4ee5-9686-6506ea60c612.png)
