### ISSUE TITLE
Can't Startup with MaryTTS installed

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#12621]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.2.9 J9 prism

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Migrate from 228 to 229 J9.

### The Reality

Marytts is a text to sound pack that mensioned in Opencomputers' addon Computrpnics.
This mod allow sounds and musics can be made or downloaded in GTNH.
There is a speechbox block with can turn text to sound by using component.say() api,which requires the language sound pack marytts.
But it GTNH can't launch with it.

### Your Proposal

Fix this if possible.
If can't this is not a large bug.
Whatever it could be used or not... but just a pity

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
apart from this not being a supported mod, you are also giving us zero information to work with.

**Comment by minecraft7771** [comment]
Provide a crash log.

**Comment by KamenriderZO** [comment]
[crash-2023-02-16_23.40.07-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10766685/crash-2023-02-16_23.40.07-client.txt)

**Comment by minecraft7771** [comment]
From quick googling this seems like a Java 19 issue.

**Comment by chochem** [comment]
oh sorry I thought that was some external addon, I had no idea this in.

And thanks for adding the log.

**Comment by KamenriderZO** [comment]
The speechbox can perform an AI message sound info,Which is quite cool.
I used this in Java8 version but J9 doesn't work

Imagine a sound reading "Warning:Not enough coolantcells in reactors!"
That's wonderful

**Comment by eigenraven** [comment]
Should be fixed in lwjgl3ify 1.1.30.
