### ISSUE TITLE
GTNH Freeze on start up ""construction: loading iguana Tinker Tweaks"

### ISSUE THREAD

**Issue by sethdark** [GTNewHorizons/GT-New-Horizons-Modpack#12630]
### Your GTNH Discord Username

sethdark#8143

### Your Pack Version

2.2.10

### Your Server

SP

### Java Version

Other versions in between

### Type of Server

Single Player

### Your Actions

Starting the Client

### Crash Report

There is no Crash report, it just freezes

last few lines from the Log from start up, where it freezes:

[11:10:18] [Client thread/INFO] [Config]: [OptiFine] Loading mcpatcher/font/ascii.properties
[11:10:19] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:10:19] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Starting up SoundSystem...
[11:10:19] [Thread-13/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: Initializing LWJGL OpenAL
[11:10:19] [Thread-13/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]:     (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[11:10:19] [Thread-13/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: OpenAL initialized.
[11:10:19] [Sound Library Loader/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:message:69]: 
[11:10:19] [Sound Library Loader/INFO]: Sound engine started

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by CatsLeftEar** [comment]
same

**Comment by chochem** [comment]
which 2.2.10? which java?

also please post the full log file

**Comment by sethdark** [comment]
Version 2.2.10 dev
tried with: JAVA 1.8  & JAVA 17
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10774542/latest.log)

**Comment by chochem** [comment]
so the normal one, got it. you need java 8 with the normal version, cant do java 17.

have the fml latest log?

**Comment by Alexdoru** [comment]
that's not the full log, what do you have in your java args ?

**Comment by sethdark** [comment]
that is latest.log
also added fml-client-latest.log

RN it's back to java 1.8
![image](https://user-images.githubusercontent.com/7458440/219873367-c31ee409-57d3-4a9e-abd3-a76f81342963.png)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10774572/fml-client-latest.log)

**Comment by chochem** [comment]
oh, so you actually crashed. it also says there should be a crashlog.

looks like lwjgl3ify is causing problems in the java8 version.

**Comment by sethdark** [comment]
No I did not crash, I killed the process manually

**Comment by eigenraven** [comment]
Can you remove betterloadingscreen and disable the forge spashscreen in `config/splash.properties` and try loading again? That might show more information in the log

**Comment by eigenraven** [comment]
It looks like the patches didn't apply, can you show a screenshot of your instance folder (the one above `.minecraft`) and the Version tab in the multimc pack settings?

**Comment by sethdark** [comment]
@eigenraven 
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10774604/latest.log)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10774605/fml-client-latest.log)
Throws exceptions now, still doesn't crash, just hangs there

**Comment by eigenraven** [comment]
Your multimc install is using lwjgl2, not lwjgl3, hence the crash. When switching to java 8, did you download that java 8 pack zip and import it fresh, or did you use the java 9+ instance?

**Comment by sethdark** [comment]
@eigenraven ![image](https://user-images.githubusercontent.com/7458440/219874319-df630220-dffb-4f50-ab37-e0aa60848d81.png)
![image](https://user-images.githubusercontent.com/7458440/219874389-7db3dbc1-e933-42ea-ba92-645a499b7800.png)

**Comment by sethdark** [comment]
@eigenraven 
I downloaded the normal client (first one in screenshot)

![image](https://user-images.githubusercontent.com/7458440/219874453-b4e0e74c-0156-485f-86f6-167986f319df.png)

**Comment by eigenraven** [comment]
Remove lwjgl3ify from the mods folder

**Comment by eigenraven** [comment]
I don't see lwjgl3ify in that zip so you probably merged the pack with an older java 19 instance or something like this

**Comment by sethdark** [comment]
@eigenraven  
I move config, mods, resources, scripts to an "old" map
then put in the new ones then move optifine to it, everytime since about 2.0

but removing the lwjgl3ify folder did make it load again it seems
