### ISSUE TITLE
Update from 2.2.8 to 2.2.10 stuck on com.sinthoras.visualprospecting.database.cachebuilder.DimensionAnalysis.processMinecraftWorld ()

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12638]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

While loading the server it eventually gets stuck after "[Server thread/INFO]: [VisualProspecting] Processing dimension with id 49 with fast scanning." on the method `com.sinthoras.visualprospecting.database.cachebuilder.DimensionAnalysis.processMinecraftWorld ()`
![image](https://user-images.githubusercontent.com/39203645/219882793-f968507b-e93a-47b8-a933-b5b2e66beba9.png)
[Snapshots.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10774938/Snapshots.zip)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10774941/latest.log)

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
It appears we forgot to carry the visualprospecting folder over from the previous server, but rebuilding it still shouldn't lock things up.

**Comment by eigenraven** [comment]
How much RAM do you have allocated to minecraft?

**Comment by Tommeh1** [comment]
> How much RAM do you have allocated to minecraft?

30GB

**Comment by eigenraven** [comment]
That is way too much unless you configured a large-heap GC such as shenandoah or zgc, g1gc can't cope with heaps larger than ~8gb on most non-server cpus

**Comment by Tommeh1** [comment]
> That is way too much unless you configured a large-heap GC such as shenandoah or zgc, g1gc can't cope with heaps larger than ~8gb on most non-server cpus

The server itself usually quickly uses just over half of that just fine using g1gc, it runs on an i9 9900k afterall, it will manage.

**Comment by Tommeh1** [comment]
> That is way too much unless you configured a large-heap GC such as shenandoah or zgc, g1gc can't cope with heaps larger than ~8gb on most non-server cpus

In fact, ZGC and Shenandoah struggled way harder after testing, G1GC wipes the floor with both and is very well capable of handling things without even the slightest lagspike, unlike the previous 2 buggers which by default let RAM fill entirely, and then clean out nearly 30GB at once, stalling the server for about 2 seconds.
