### ISSUE TITLE
Cursor position desync in GUI's

### ISSUE THREAD

**Issue by FloatDoubling** [GTNewHorizons/GT-New-Horizons-Modpack#12632]
### Your GTNH Discord Username

DarkEastSider#3859

### Your Pack Version

2.2.10

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Cursor position should stay synced

### The Reality

When you open first GUI (for example, chest), then close it, after it opening second GUI, (another chest), cursor position will stay in previous place where it was before closing first GUI. Easy to reproduce

### Your Proposal

Fix desync

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AlexandrKanev** [comment]
I also experienced the same problem, I fully confirm its presence. 2.2.10, dedicated server, java 19
