### ISSUE TITLE
ProjectRed Project Bench consumes Pam's cookware after crafting a single recipe.

### ISSUE THREAD

**Issue by ultranine1** [GTNewHorizons/GT-New-Horizons-Modpack#12634]
### Your GTNH Discord Username

ultranine#8872

### Your Pack Version

2.2.0.0

### Your Server

MMCC (Non-Ironman)

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

Tried to craft a batch of fried eggs with the Project Bench using a skillet and a handful of eggs. Expected it to give me the fried eggs and leave the skillet in the 3x3 grid, as all other crafting tables do.

### The Reality

Upon attempting to craft the fried eggs, I only picked up one, the skillet disappeared, and the remaining eggs were left in the grid. Upon further testing, the recipe worked normally with the Forestry worktable, but upon switching back to the PB, it voided the skillet again. I also tested it in a singleplayer world, and got the same result.

### Your Proposal

Fix the bug with the PB if possible, so that it leaves the Pam's tools in the grid like it should.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by dgealow** [comment]
duplicate/related to #11423
