### ISSUE TITLE
Can't run 2.2.9 (Java 9+) client on Java 11, 17 and 19

### ISSUE THREAD

**Issue by icanwalkonwater** [GTNewHorizons/GT-New-Horizons-Modpack#12646]
### Your GTNH Discord Username

icanwalkonwater#6969

### Your Pack Version

2.2.9 java 9+

### Your Server

Self hosted 2.2.9 java 19

### Java Version

Java 19

### Type of Server

None

### Your Actions

- Download the official zip for 2.2.9 java9 for MultiMC
- Import it from zip into PolyMC (fork of MultiMC)
- Allocate 8Gio of ram to it
- Change java version to 19 (19.0.2)
- Copy paste the official [java arguments](https://github.com/GTNewHorizons/lwjgl3ify#client)
- Launch the instance, a black window shows up
- `Segmentation fault`
- Change to java 17 (17.0.6)
- Starts but hangs with a black window indefinitely
- Change to java 11 (11.0.18)
- Crash: `Could not create SecurityManager`

So I have tried every supported java version of LWJGL3ify and well, none worked, java 17 was promising but yea no.

Might be important to note that I am on linux (archlinux) but I don't think this is an issue as I never ever had any problem running any java app and the 2.2.8 version of the pack runs fine on java 8 (although it consumes way more than the 8Gio it says it uses but that's irrelevant here).

The normal 2.2.9 of the pack using java 8 works fine.

### Crash Report

Crash java 19: https://mclo.gs/t2r7W3z
Log java 17: https://mclo.gs/JKPHbKa
Crash java 11: https://mclo.gs/RGfT4w7

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
dont think anybody tried on poly yet, so maybe the launcher is the problem.

however, prism works great (and you dont even need the args). Linux is not a problem, in fact the java9+ dev tests stuff there first. 2.2.9 has some issues in general including various crashes, maybe better use 2.2.10.

just a few thoughts, not a clear solution, I know.

**Comment by icanwalkonwater** [comment]
That's unexpected, I didn't think that the launcher could have anything to do with this but it works on prism and multimc.

By comparing the logs (java 19) it seems that polymc didn't load the native librairies, presumably causing the segfault.

I switched to prism and it works so I guess this is resolved.

Thanks
