### ISSUE TITLE
Sharing AE2fc fluid storage buses with PR gates/cables via Forge Multipart causes crashes

### ISSUE THREAD

**Issue by IsOobt** [GTNewHorizons/GT-New-Horizons-Modpack#12642]
### Your GTNH Discord Username

oobt#8431

### Your Pack Version

2.2.10

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Tried to use /home in my world. Nothing was loading and i got stuck. Tried leaving and rejoining, then got the crash you. Then if i try joining again, the screen gets stuck on "Building Terrain". I run into the same issue everytime I relaunch GTNH
![image](https://user-images.githubusercontent.com/114492400/219926052-ba78ce89-4dff-4f70-851e-c04ba7f78eb1.png)

### Crash Report

[crash-2023-02-18_23.21.19-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10776022/crash-2023-02-18_23.21.19-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by IsOobt** [comment]
Oh I forgot to mention, loading a backup world didn't help either.

**Comment by vovaksenov** [comment]
It is not a "fix" for the actual bug, but you can probably load the world if you delete this block using mcedit. It helped me when i had a similar type of issue a year ago.

Source block type: ID #917 (tile.multipart // codechicken.multipart.BlockMultipart)
    Block type: ID #917 (tile.multipart // codechicken.multipart.BlockMultipart)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-395,99,-1593), Chunk: (at 5,6,7 in -25,-100; contains blocks -400,0,-1600 to -385,255,-1585), Region: (-1,-4; contains chunks -32,-128 to -1,-97, blocks -512,0,-2048 to -1,255,-1537)
Not sure which dimension, but probably where your base is.

**Comment by IsOobt** [comment]
Yeah I looked into it some more, and it turns out the game doesn't like it if I have an AE2fc fluid storage bus and a ProjectRed AND gate occupying the same block, stopped doing that and it doesnt crash anymoree

**Comment by vovaksenov** [comment]
@IsOobt you should not close the issue. The bug is still there, you only found a workaround.
