### ISSUE TITLE
Search bar in advanced memory card hides/disappears "bind" button 

### ISSUE THREAD

**Issue by Ravioli-124** [GTNewHorizons/GT-New-Horizons-Modpack#12652]
### Your GTNH Discord Username

Ravioli_124

### Your Pack Version

Dev 2.2.10

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When using Advanced Memory Card from BetterP2P mod, using the search bar filters entries and still allows for binding. Works properly when nothing is searched (see image).
![2023-02-19_16 15 24](https://user-images.githubusercontent.com/59350550/219975648-8d63d675-dbf5-466f-a211-86694d43d608.png)

### The Reality

When typing anything into the search box, the results are filtered, but the "bind" button disappears. This occurs with all P2P types and with all card modes.
![2023-02-19_16 16 25](https://user-images.githubusercontent.com/59350550/219975696-b12dfdd5-24b0-4857-843c-a439d80508c4.png)

### Your Proposal

The "Bind" button does not disappear when using the search function.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment]
Can confirm, makes advanced p2p literally unusable

**Comment by chochem** [comment]
its certainly usable. I have used it.

**Comment by LewisSaber** [comment]
YEs but U have to scoll all the way to p2p u want to bind, which is problematic at late game base
