### ISSUE TITLE
Mega apiary impossible power demand and missing flowers

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12655]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

After updating to 2.2.10 the mega apiary not only demands more power than it can receive over 4 energy hatches to run, it also demands flowers, despite all possible flowers being near it and the contained bees all only wanting normal flowers to begin with.
![image](https://user-images.githubusercontent.com/39203645/219980066-59e2af96-7112-448e-b8a4-97a3f03d5e67.png)
![image](https://user-images.githubusercontent.com/39203645/219980087-6ff21c59-997a-479e-95a2-1dde0f6e1dbb.png)

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Ignore the flower bit, it apparently needed many minutes to notice them and suddenly turn on.

**Comment by kuba6000** [comment]
Tricorder shows 9 times more power because efficiency is 0 atm, when you start the apiary, it should take around 66,437,775 EU/t (32768 * 2048 * 0.99) and show it correctly on the scan when running

**Comment by Tommeh1** [comment]
> Tricorder shows 9 times more power because efficiency is 0 atm, when you start the apiary, it should take around 66,437,775 EU/t (32768 * 2048 * 0.99) and show it correctly on the scan when running

Seems like indeed also needed its time to update, oh well...
