### ISSUE TITLE
Ressources eaten alive while above Y:200

### ISSUE THREAD

**Issue by Momoliski** [GTNewHorizons/GT-New-Horizons-Modpack#12666]
### Your GTNH Discord Username

Momoliski

### Your Pack Version

1.7.10
GTNH 2.2.0.0 (2022-09-27)
Forge 10.13.4.1614 for Minecraft 1.7.10

### Your Server

BisectHosting

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

https://spark.lucko.me/SGJ5ekre3N here a spark result from the server support services

here is the server log and the client logs
[latest_2.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10788158/latest_2.log)
[latest (3).log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10788160/latest.3.log)

I don't have anymore informations other then once I saw in the console that the server wrote a memory excess usage on some bronze steam machine (the macerator to be more specific)

I would find it amazing if we can fix it, it would allow me to build higher in the sky and not worry for some timing out loop

### The Reality

I can avoid any issue or lag as long as I stay under Y:200

it got verified that's it's not a world problem, it's happening on any world
it's not entity cramming or item, bisechosting did a chunk fixing "thing"

Bisecthosting ain't really able to fix this issue for now, been trying multiple days to get that issue fixed without success
a good employe did fix it for a day tho, he optimized the server and increase the memory to 8 go of ram, I was able to stay up there
then for no reason it cameback the following day if not sooner

the issue started with me and my friend building a staircases all the way to the build limit, we were at the steam age in the pack with a world not older then 72 h on playtime on it
once we reached 200Y we started to get disconnecting on a loop and the console was spamming "can't keep up"
we tried one at a time to see if it was client side, which wasn't it was happening to either of us even with the third person that don't play on the server really
So since then I been avoiding to go above 200Y or else I would make the server choke on itself for minutes, then going back to normal real smooth
transition on that world between world is the smoothest I ever experienced yet, I can do a triple back and forth between the twitlight forest or the nether without any lag or slowdown, barely showing the loading for no more then a sec.
but as soon as you get at above 200Y, dead
I tried to go to the bedrock and the server don't struggle at all, I only have tiny lag rarely on my client, probably because of the particules, so nothing not normal here.

the stairs testing I did it on a totally new world, virgin, built a normal staircase and the same thing happened, I tried to ask bisecting if they could provide me test from other client using the same modpack as me. To see if they do a staircase in their own world if they have the same odd bug

***New progression***

the source may come from thaumic horizon

### Your Proposal

I don't understand the question here

I guess I propose to help fixing it and maybe help some other people with a similar issue as me to get it fixed

further testing 03-03
I did a dedicated server and I don't seems to have the height issues, only with the servers of bisecting hosting

further progress again going for a tentative on this version[GT_New_Horizons_2.3.0-RC-3_CLIENT.zip](http://downloads.gtnewhorizons.com/ClientPacks/GT_New_Horizons_2.3.0-RC-3_CLIENT.zip)
https://spark.lucko.me/UoVVP5w3sG
it's a fail

and here a nicer spark compare to the first one on this ticket
https://spark.lucko.me/n5dVSWDljQ
20 minutes of normal play under y200
then 5 minutes ish above 200y
(that issue still don't exist on my dedicated server, only happening on bisecting hosting for now)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Blocky106** [comment]
it could just be that there is no oxygen above y200

**Comment by Momoliski** [comment]
but it's not killing, it's killing the server

**Comment by boubou19** [comment]
all the officials servers have blocks above 200 and have no issue, remove any custom mod and retry.
