### ISSUE TITLE
Dual interface blocking mode is broken

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#12664]
### Your GTNH Discord Username

Keyla#3300

### Your Pack Version

2.2.10

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Expected dual interface blocking mode working normally to containers next to it

### The Reality

Dual interface ignores blocking mode if there are any "empty" containers next to it. 
Examples of when dual interface with blocking mode keeps sending items in a chest with items already inside:
when there is a conduit with only output to the dual interface
when there is a conduit which is fully disconnected from the dual interface
when there is a fluid pipe connected to the dual interface
when there is an empty chest connected to the dual interface
when there is another interface/dual interface next to the dual interface

### Your Proposal

Stop dual interface from pushing items in a container with items already inside with a blocking mode. Blocking mode should stop items from being pushed in a chest with items already inside, its in the name

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by CatsLeftEar** [comment]
This bug was in 2.2.9, it got worse in 2.2.10. In 2.2.9 at least fluid pipes didnt break the blocking mode, now they are breaking it as well.

**Comment by CatsLeftEar** [comment]
Normal behaviour: 
![normal behaviour](https://user-images.githubusercontent.com/67397297/220169267-0d1aac4f-3cdd-49e1-bc8e-65337b151a59.gif)
Bug with a conduit:
https://imgur.com/Snn7uZ9
Bug with a gt fluid pipe:
https://imgur.com/YFS3Rob
Bug with an energy conduit!!:
https://imgur.com/QUYFVbt

**Comment by Ydrec** [comment]
Confirmed this indeed happens in stock 2210. In 2210 + latest ae2fc and ae2 from jenkins conduits causing issue is fixed. Gt tileentities which cant take in items/fluids still cause this issue even if not connected. Happens even with gt wires for whatever reason. Possibly would be fixed once https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/86 is finished and merged.

**Comment by Ydrec** [comment]
Issue been fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/86/commits/fb003da0a3b6961d7faf0324a2406a51d4057c7f
