### ISSUE TITLE
sugar Charcoal in advanced coke oven 

### ISSUE THREAD

**Issue by Dadywar** [GTNewHorizons/GT-New-Horizons-Modpack#12661]
### Your GTNH Discord Username

dadywar#1335

### Your Pack Version

2.2.10

### Your Server

Sp

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Im using Sugarcane processes with Advanced Coke Oven to supply some ressources and energy 

in this process, i use Sugarcane to Sugar Charcoal and/or Sugar Coke then use this result in some other ways such refueling the Advanced Coke Oven 

### The Reality

Sugar Charcoal is used as a recipe in Advanced Coke Oven producing back Sugar Charcoal instead of the Sugar Coke (as the old RC Coke Oven does) creating an useless blocking loop in the processes
![2023-02-20_12 45 29](https://user-images.githubusercontent.com/102406657/220103602-c8eeee3a-86ec-424e-938a-ffbc0da7cd36.png)

### Your Proposal

Either , use the Sugar Charcoal only as fuel and not recipe in the Advanced Coke Oven
Or , transform Sugar Charcoal into Sugar Coke in the Advanced Coke Oven

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Steelux8** [comment]
I will look into this.
