### ISSUE TITLE
Scrolling ghost circuits in stocking interface crashes the game

### ISSUE THREAD

**Issue by Datryum** [GTNewHorizons/GT-New-Horizons-Modpack#12667]
### Your GTNH Discord Username

Schnils#1542

### Your Pack Version

2.2.10

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

I tried to scroll though the circuits in a Stocking Interface and Fluid Processing Terminal, when the game suddenly crashed.

### Crash Report

[crash-2023-02-20_23.53.31-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10788295/crash-2023-02-20_23.53.31-client.txt)

The first Crash Report is from the Stocking Interface and the second is from the Fluid Processing Terminal

[crash-2023-02-20_23.59.18-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10788296/crash-2023-02-20_23.59.18-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
the second one is fixed https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12580
