### ISSUE TITLE
Dual Interfaces Unable to send fluids through another dual interface linked to an AE2fc fluid storage bus. 

### ISSUE THREAD

**Issue by IsOobt** [GTNewHorizons/GT-New-Horizons-Modpack#12662]
### Your GTNH Discord Username

oobt#8431

### Your Pack Version

2.2.10

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Tried to craft AE2 processors with my Precise Assembler using an AE2 automation setup involving a dual interface facing another dual interface on a subnet hooked up to an item and fluid storage bus (from AE2fc).

### The Reality

The items were sent, but the fluids remained in the pattern-holding dual interface. Notably, upon breaking it, the fluid packet item would come out of the dual interface. Said item packets do not turn back into fluid when manually placing them in a fluid packet decoder.

### Your Proposal

Make it so that fluids properly go through dual interfaces and through AE2fc fluid buses.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by IsOobt** [comment]
Quitting and rejoining my world seems to have solved it, but i still do not know what caused it in the first place.

**Comment by Ydrec** [comment]
@IsOobt Can not replicate on stock 2210, try checking this is not caused by #12610 and provide screenshots of setup/interface settings/bus settings/pattern
