### ISSUE TITLE
Server console NPE spam without stacktrace, fml logging broken

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12679]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Our server console is constantly getting spammed with `[Server thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NullPointerException`
However, no stacktrace is attached to it and since either 2.2.9 or 2.2.10 the fml log is no longer being generated to check for further details there
![image](https://user-images.githubusercontent.com/39203645/220487620-0c424e6a-edce-4bc4-b6c8-c4eab5b8b480.png)

### Your Proposal

Fix FML debug logging so i can potentially get the stacktrace linked to this NPE so it can also be fixed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
I've reverted the server to java8, which brought performance up by about 50% and fixed the debug logging, however, even there no stacktrace is present.

**Comment by Tommeh1** [comment]
As there appears to be a slight misunderstanding about this issue outside of GitHub, the NPE and broken logging ain't related.
I ended up finding the NPE spam back in the Gregtech log however, but without further details.

**Comment by Dream-Master** [comment]
we not updated server to java 19. But 2.2.9 and 2.2.10 where not fully java 19 compatible. Try with 2.3.0

**Comment by Tommeh1** [comment]
> we not updated server to java 19. But 2.2.9 and 2.2.10 where not fully java 19 compatible. Try with 2.3.0

As java 19 offered no improvements at all we've no intentions of going back to it, even if compatibility got improved, however the NPE spam still exists in 2.3.0 and is present in the Gregtech log which i attached to #12889 due to various other NPEs that did include a stacktrace being present in it.

**Comment by Dream-Master** [comment]
You can play at  java 8 no one force you use new version

**Comment by Tommeh1** [comment]
> You can play at java 8 no one force you use new version

I know that well enough, but the spam still remains

**Comment by Dream-Master** [comment]
ignore it its not the end of the day. I see this spam on officials as well. i guess it not eats up a lot of memory

**Comment by Dream-Master** [comment]
if it is critical i guess we find a fix

**Comment by Tommeh1** [comment]
> ignore it its not the end of the day. I see this spam on officials as well. i guess it not eats up a lot of memory

It still should be fixed if possible, perhaps it will go away if the other 3 NPEs in that issue i referred to are fixed.

**Comment by chochem** [comment]
of course it should be fixed. difficult though with 0 info.
I dont see it in SP btw, all good here.

**Comment by Tommeh1** [comment]
Whatever the cause it, it has worsened and is spamming the log about 30 times faster than before now, up to quite a few times each second.

**Comment by Tommeh1** [comment]
> I've reverted the server to java8, which brought performance up by about 50% and fixed the debug logging, however, even there no stacktrace is present.

Even in 2.3.2 using a newer version of Java instantly breaks the forge debug log.

**Comment by Tommeh1** [comment]
Closing in favor of #13597
