### ISSUE TITLE
Concussion Creeper spawns within Tainted Lands

### ISSUE THREAD

**Issue by Rosenlied-Iris** [GTNewHorizons/GT-New-Horizons-Modpack#12670]
### Your GTNH Discord Username

Rosenlied#3858

### Your Pack Version

2.2.10

### Your Server

Private server/Single Player

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Expecting only tainted mobs to spawn within Tainted Lands biome, especially within Thaumcraft Outer Lands.

### The Reality

Tainted Lands is filled with concussion creepers instead of the expected tainted creepers. These teleport mobs, including bosses, out of bounds of the maze, resulting in not-legitimately-possible dungeons. 

### Your Proposal

Blacklist Concussion Creeper from natural spawning in Outer Lands dimension and/or in Tainted Lands biome.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Rosenlied-Iris** [comment]
I don't think the intended way to solve an outer lands dungeon if a concussion creeper somehow sends the boss out of bounds, is to use twilight canopy saplings to punch holes in the maze.

**Comment by Rika-TH** [comment]
this has just occured to me on the giant tainticle boss in 2.3.0 however it sent the BOSS OoB and I was unable to fight it or properly locate it until a concussion creeper sent me OoB aswell
