### ISSUE TITLE
Quest error!

### ISSUE THREAD

**Issue by NoNameISNoMan** [GTNewHorizons/GT-New-Horizons-Modpack#12673]
### Your GTNH Discord Username

nooneinparticular#8014

### Your Pack Version

2.2.10

### Your Proposal

Found a quest error! You can't wrap copper wire by hand.

![image](https://user-images.githubusercontent.com/85317599/220406930-3f3ee890-5f78-49b9-8269-a8064d86f205.png)

### Your Goal

Well it's an error.

### Your Vision

There will be no error.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by NoNameISNoMan** [comment]
Sorry if it's a wrong type, it seemed like the most appropriate one.

**Comment by chochem** [comment]
its says assembling machine, not by hand
