### ISSUE TITLE
Plutonium 239 Dust Showing as dustImpure

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#12678]
### Your GTNH Discord Username

shawnbyday#1337

### Your Pack Version

2.2.8

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Mining Plutonium 239 vein on Io. Expect Impure Dust to enter or processing system as Impure Pile of Plutonium 239 Dust.

### The Reality

Enters system as: impureDust.

![Screenshot from 2023-02-21 17-30-11](https://user-images.githubusercontent.com/33701188/220482665-bda4b0da-e96b-4818-b13d-fb9b3abba31e.png)

### Your Proposal

Fix please?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
It looks like the linked PR is working good
