### ISSUE TITLE
OpenComputer complains about Native Lua libraries are not available when update from 2.2.9 to 2.2.10

### ISSUE THREAD

**Issue by HikerL** [GTNewHorizons/GT-New-Horizons-Modpack#12688]
### Your GTNH Discord Username

Zeroling#5350

### Your Pack Version

2.2.10

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

The OpenComputer mod to not complain about a missing lib (Native Lua libraries are not available, computers will not be able to persist their state. They will reboot on chunk reloads.)

### The Reality

When update to Version 2.2.10, OC mod complains about the missing Lua libraries, but it works well with 2.2.9.
Actually the problem would also happen when I just replace the OC 1.8.0.9 within Version 2.2.9 to OC 1.8.0.12. 
So the problem must be due to the newer OC mod.

PC: Windows 11, Intel i5-12600

### Your Proposal

I tried to search for familiar questions and solutions but I still don't know what happened. It's frustrating that computer in game would always restart :c 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BritishCynic** [comment]
This is fixed in dev.

**Comment by HikerL** [comment]
> This is fixed in dev.

Wow, your reply is so quick. Thanks for your and your mate's hard work and great contribution to the community
