### ISSUE TITLE
[Crash] CoFHCore + Hodgepodge crash (Mixin classloading)

### ISSUE THREAD

**Issue by 007killer2** [GTNewHorizons/GT-New-Horizons-Modpack#12686]
Mods:

CoFHCore 3.1.4-329
GTNHMixins 2.1.13
lwjgl3ify 1.1.32
gtnhlib 0.0.12
hodgepodge 2.0.36
Java:

Oracle JDK 17.0.6
[log2.txt](https://github.com/GTNewHorizons/lwjgl3ify/files/10806015/log2.txt)

**Comment by eigenraven** [comment]
This is fixed by installing Mixingasm <https://github.com/GTNewHorizons/Mixingasm/>, and will be fixed in the mixins mod once we move from GTNHMixins to UniMixins (most likely after next stable) <https://github.com/LegacyModdingMC/UniMixins/>
