### ISSUE TITLE
High CPU use when viewing quest book, nei etc.

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#12687]
### Your GTNH Discord Username

KiloJoel'3044

### Your Pack Version

2.2.8

### Your Server

SinglePlayer

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Opened the quest book. Expected no significant change in CPU use.

### The Reality

CPU use went up a lot. Noticed by computer fan speeding up.

Some snapshots from VisualVM:

**GTNH version 2.2.8**
 -Quest book open on MV page with view mode on
[BQSample.nps.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10807316/BQSample.nps.txt)

 -Quest book open with no tab selected
[BQNoTab.nps.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10807493/BQNoTab.nps.txt)

 -Looking at open diamond chest half filled with items, holo glasses equipped
[DiamondChestNeiNoSearch.nps.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10807361/DiamondChestNeiNoSearch.nps.txt)

 -Inventory open, nei search "storage drawer" gui scale normal
[NeiStorageDrawersSample.nps.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10807430/NeiStorageDrawersSample.nps.txt)

**GTNH version 2.2.0.0**
 -Quest book open on MV page with view mode on, same save used as above.
[BQSample2.2.0.0.nps.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10807436/BQSample2.2.0.0.nps.txt)

If it's helpful to know, I have a stock ryzen 5600X

### Your Proposal

Reduce CPU use.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Although my performance issue with Betterquesting is constant it may not be a bad idea to reference it here: #12107 in case it's somehow related afterall.
