### ISSUE TITLE
Universal terminal pattenr making

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#12682]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.2.11

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Bug - shiftclicking puts recipe but all items are set to 1

step to reproduce
1.Open Universal terminal
2.Open pattern or processing pattern terminal
3.Open any recipe in nei
4.Click on "?" with shift to put recipe in pattern
5.Recipe is put but every item is set to 1 instead of amount needed for recipe

### The Reality

--

### Your Proposal

--

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by asdflj** [comment]
i can't reproduce it

**Comment by LewisSaber** [comment]
![image](https://user-images.githubusercontent.com/39595617/220836300-c441fa79-444a-43f2-b06e-562da48f18b7.png)
![image](https://user-images.githubusercontent.com/39595617/220836323-af58cf4c-468c-4430-addb-0f121cd276a9.png)
my ae2fc version is from blockingFix pr downloaded like 20h ago

**Comment by asdflj** [comment]
![55](https://user-images.githubusercontent.com/33802162/220857716-b0e2cca4-76b6-406c-b39e-df38c9041c03.gif)
nope

**Comment by asdflj** [comment]
i hold shift click ? to put recipe to slots
it's look like fine

**Comment by LewisSaber** [comment]
What ae Version U use
A guy got same problem with this
![image](https://user-images.githubusercontent.com/39595617/220858941-229b7c82-7cc4-42dd-9280-76aedbd10587.png)
I got same jars, but ae is 161 instead of 162

**Comment by asdflj** [comment]
i use ae2 162 and fc 1.0.81 version

**Comment by LewisSaber** [comment]
Its kinda strange, I just took new terminal from NEI and it works, and it started working in my old terminal without doing anything

**Comment by RaitGamerGR** [comment]
I think i find how to reproduce this problem. Turn terminal into "crafting pattern" and do shift click ?. If after clicking you switch it, all be work fine. If you turn into right mode before shift click ? terminal works fine.
@LewisSaber @asdflj

**Comment by asdflj** [comment]
fixed https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/95
