### ISSUE TITLE
Weird behaviour of crafting patterns with GT tools

### ISSUE THREAD

**Issue by Jenyariy** [GTNewHorizons/GT-New-Horizons-Modpack#12685]
### Your GTNH Discord Username

Jenyariy#9688

### Your Pack Version

2.2.11_nightly

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I have a simple test ME network with a ME chest for storage, a 1k crafting storage, ME terminals and a Molecular Assembler with an Interface attached to it. I made some patterns for testing. The first example is _Illuminated Panel_ and _Titanium Plate_. 
![image](https://user-images.githubusercontent.com/31546644/220646942-947816b7-2e8f-4f0b-8488-08070d63f2da.png)
![image](https://user-images.githubusercontent.com/31546644/220647145-b645029c-c69b-4022-8e2f-d5ff69b9179b.png)
Now I will try to craft _Illuminated Panel_. As you can see, there are no items in storage:
![image](https://user-images.githubusercontent.com/31546644/220649377-7fb64b96-0371-4c5a-8b7f-9c0a72cc299d.png)

If I try to craft a _Titanium Plate_ I get this:
![image](https://user-images.githubusercontent.com/31546644/220649701-1e8b23f0-49b2-4d71-af56-05a55fc6b6c8.png)

If I try to craft a _Illuminated Panel_ I get this:
![image](https://user-images.githubusercontent.com/31546644/220649977-c1811662-9bc6-4fd6-9245-a83f842ea557.png)

Then I add 1 item that is needed for _Illuminated Panel_:
![image](https://user-images.githubusercontent.com/31546644/220651789-5403afb5-212e-42b4-856d-705e264b13e9.png)

When trying to craft a _Titanium Plate_ the result is the same as before, but with _Illuminated Panel_:
![image](https://user-images.githubusercontent.com/31546644/220650987-7ce1355b-a86f-44d8-92c1-4996e1864360.png)

It actually lets me craft it! Then the crafting task is stuck forever:
![image](https://user-images.githubusercontent.com/31546644/220651307-1a06e4eb-966e-4f51-ae2e-051ebf5cc3a7.png)

Now I add all the items needed for _Illuminated Panel_:
![image](https://user-images.githubusercontent.com/31546644/220652819-a120a339-2eca-4579-8dd8-2e035413ca82.png)

It lets me craft the panel but the crafting task is stuck anyway, also it reserves 2 Titanium Ingots and a Hammer:
![image](https://user-images.githubusercontent.com/31546644/220653342-26741d1a-f6f4-4758-8cbd-548002eda46a.png)
![image](https://user-images.githubusercontent.com/31546644/220653429-41a7395f-08ad-4ea9-907d-fe67ef187090.png)

Then I add the second hammer:
![image](https://user-images.githubusercontent.com/31546644/220653846-cb260234-aabf-4025-9e63-5ac54d6d4232.png)

And then it finally works as intented:
![image](https://user-images.githubusercontent.com/31546644/220654143-3677798c-ba14-426b-b310-bc92d8d0f37b.png)

Interestingly enough after crafting only 1 hammer gets damaged:
![image](https://user-images.githubusercontent.com/31546644/220654395-e71fd4dd-9e93-4020-8cd9-a1e7e18eadea.png)

Then I've tried to reproduce this situation with another patterns:
![image](https://user-images.githubusercontent.com/31546644/220655462-9363b356-5133-48f6-bc2b-769772b1bb63.png)
![image](https://user-images.githubusercontent.com/31546644/220655632-d5ebe682-3abe-4a7c-b034-7dc855798b61.png)

So in this case the File is used twice when crafting a Titanium Ring. I put only 1 File to the network expecting that the task to craft a Titanium Ring is going to stuck. But for some reason everything worked as intended.
I didn't give up and made a pattern for Double Titanium Plate and put only 1 Hammer to the network. Well, when crafting a double plate the network for some reason displays that I only need 2 titanium ingots (when in reality I need 4) and the crafting task gets stuck:
![image](https://user-images.githubusercontent.com/31546644/220658278-25596068-40df-4c0e-8756-8f91b34af2a1.png)
![image](https://user-images.githubusercontent.com/31546644/220658337-30d99fff-b267-47b9-b9aa-e7dee1ceaf91.png)

Also I discovered that when the task gets stuck like this I can still craft something else despite my only Crafting Processor being busy: (!)
![image](https://user-images.githubusercontent.com/31546644/220658787-be9471f5-c582-4456-be28-919aa2f37286.png)

When I do it, I get my Titanium Rod crafted and also I get the reserved Hammer and 2 Titanium Ingots back from the stuck crafting task.

### The Reality

I'm not sure how do I sum it all up. So I figured out that if a craft involves 2-step ctrafting patterns with a GT Hammer it doesn't work properly and it needs a second hammer in the network to work as intended, also only 1 Hammer will get its Durability decreased in the process. A GT File in a similar situation works fine and there is no need in second File in the network.

During the tests I discovered that crafting calculation doesn't work in these scenarios. I shouldn't have been able to order crafting of an _Illuminated Panel_ when I only had Red Alloy Plates in storage.

Also I'm not sure that you should be able to give another crafting task to your one and only Crafting Processor when it's "stuck" with the previous crafting task.

### Your Proposal

Crafting calculations need some reworking.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
this is a lot of stuff mixed together. Lets try to order a bit. It seems to be 3 issues, one of which I cant reproduce.

1. if ingredients of the top level pattern (the one you are crafting) are missing, then one should get a list of missing ingredients, instead one gets the 'missing final item' (see titanium plate pic4). I have been able to reproduce this constantly with other recipes too. I am only getting this for the top level, if something is missing further down the line I get the proper visualization of what is missing.
2. when you then do the same recipe again with other random unrelated stuff present it suddenly pretends to be craftable? (pic7/8) I have NOT been able to reproduce that, even with the exact same isolated setup.
3. if multiple recipes need a tool, it seems to need one tool per recipe otherwise it will get itself stuck weirdly without complaining in the simulation. (pic9-14) It bugs out so much it even confuses the crafting cpus.

**Comment by chochem** [comment]
ah, I did 2 wrong, now I can see it to.

**Comment by chochem** [comment]
Logs:
1. [bug 1.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10805949/bug.1.txt)
2. [bug 2.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10805957/bug.2.txt)
3. [bug 3.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10805988/bug.3.txt) (just one hammer)

**Comment by Phineasor** [comment]
Does this problem occur with GTPP tools or is it the allowing substitution in patterns?

**Comment by Jenyariy** [comment]
> this is a lot of stuff mixed together. Lets try to order a bit. It seems to be 3 issues, one of which I cant reproduce.
> 
> 1. if ingredients of a pattern that contains tools are missing, then one should get a list of missing ingredients, instead one gets the 'missing final item' (see titanium plate pic4). I have been able to reproduce this consistantly with other recipes too. If there are no tools in the recipe but some item is missing, I get the proper visualization of what is missing.
> 2. when you then do the same recipe again with other random unrelated stuff present it suddenly pretends to be craftable? (pic7/8) I have NOT been able to reproduce that, even with the exact same isolated setup.
> 3. if multiple recipes need a tool, it seems to need one tool per recipe otherwise it will get itself stuck weirdly without complaining in the simulation. (pic9-14) It bugs out so much it even confuses the crafting cpus.

About the 3rd. BTW I wrote that when I tried to craft a Titanium Ring with only 1 File it worked fine, so sometimes it's not necessary to have 1 tool per recipe, which is even more weird.

Also sorry for closing and re-opening the issue, I was just confused with the interface.

**Comment by chochem** [comment]
it has nothing to with gt++. not sure what even gave you the idea.

**Comment by chochem** [comment]
just tested again.
all of it works now in 2.2.12 2-pre-dev!
