### ISSUE TITLE
ME pattern Substitution Omission of requirements and eventually deletion of everything involved

### ISSUE THREAD

**Issue by Kyrorichekku** [GTNewHorizons/GT-New-Horizons-Modpack#12684]
### Your GTNH Discord Username

kyori#4690

### Your Pack Version

2.2.10

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

auto crafting to select of of the possible items (or recipe for) when previewing and validating an autocraft

for a confirmed recipe to have accounted for all of the configured recipe requirements 

### The Reality

when auto crafting a recipe including substitutions somewhere when previewing the recipe requirements and when confirming the craft (in my case crafting table recipes) requirements in the pattern are omitted when nothing can fulfill the requirements 

the craft is permitted (despite not actually having the requirements) and is allow to "process" and other requirements (that were not omitted) are allowed to craft

once everything is crafted no item is produced, the que clears ready for another craft something else, and none of the materials involved are return to the system 

note: no tool crafting recipes are present in my ME system 

![image](https://user-images.githubusercontent.com/123538122/220646240-73be3ce9-d77d-4ca7-be72-8c1a7fa32076.png)

![image](https://user-images.githubusercontent.com/123538122/220646944-73235753-3cde-425d-a12b-5c5194613a89.png)

![image](https://user-images.githubusercontent.com/123538122/220647382-c6d26a89-3f63-4dfb-8c81-07df70eb0196.png)
(no hammer in ME system)
![image](https://user-images.githubusercontent.com/123538122/220647815-65efc1f5-1c07-4228-9a04-cf79b81d3fe4.png)

![image](https://user-images.githubusercontent.com/123538122/220648001-a66cf3f9-a4d3-4379-82a3-536d09159ef4.png)
(hammer in ME system)
![image](https://user-images.githubusercontent.com/123538122/220648276-ad1db419-94c7-4b43-aabd-82837f177b19.png)

### Your Proposal

make it work properly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by eigenraven** [comment]
This largely overlaps with #12685 and should be fixed in the latest ae2 build
