### ISSUE TITLE
suggest about optical circuit processor's material

### ISSUE THREAD

**Issue by truecyt** [GTNewHorizons/GT-New-Horizons-Modpack#12681]
### Your GTNH Discord Username

truecyt#2723

### Your Pack Version

2.2.1.0

### Your Proposal

add new recipe for optical compatible memory and optical perfected CPU used highly materials like hypogen,spacetime and shirabon
the higher material provides more production
e.g.:
optical compatible memory:
![image](https://user-images.githubusercontent.com/58604873/220530434-dbe94ac8-687a-4052-9087-28f97c2291cc.png)
use spacetime screw with UEV superconductor wire
![image](https://user-images.githubusercontent.com/58604873/220530911-3aa71066-b581-4469-b040-14e8557886dd.png)
ues hypogen screw with UEV superconductor wire
![image](https://user-images.githubusercontent.com/58604873/220530873-f2eac3ff-5696-42ba-af83-368d6ae0c71a.png)
use infinity screw with UEV superconductor wire
optical perfected CPU:
![image](https://user-images.githubusercontent.com/58604873/220531136-bfb88c57-0d5a-460d-98d3-3828f0b92cd7.png)
top:infinity 
bottom:spacetime
![image](https://user-images.githubusercontent.com/58604873/220531333-b88a9c4f-9f5c-4fa2-953e-eedfd4a4dbfa.png)
top:hypogen
bottom:shirabon

and i hope to add new T3.5 memory recipe by circuit assemblyline like this recipe
![image](https://user-images.githubusercontent.com/58604873/220532438-477d0249-0567-4021-81f4-7047c561ff82.png)
(sry about my limited capacity. i used zenscript to rewirte this recipe and the circuit assemblyline not support zenscript)

### Your Goal

the optical processor is toooooo expensive than the old nanoCPU's recipe

### Your Vision

🤔

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
if you complain we just nerf them more :)
