### ISSUE TITLE
shift+click pattern of Optically Perfected CPU

### ISSUE THREAD

**Issue by Fiyorin** [GTNewHorizons/GT-New-Horizons-Modpack#12698]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.2.12-2-dev

### Your Server

Private

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

if you shift+click the pattern in NEI it gets filled in a Processing Pattern Terminal, but not in a Fluid Processing Pattern Terminal (it stays empty instead).

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
When I put the newest AE2FC version into my GalaxySpace dev-instance it works fine to me. So it must be some weird mod-interaction which I am not aware of. Maybe someone if more NEI experience can say something about that.

**Comment by chochem** [comment]
@minecraft7771 this involves nee too probably
