### ISSUE TITLE
Universium texture bugs

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12693]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.2.11

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

It should look like this: 
![image](https://user-images.githubusercontent.com/40274384/221020469-59797fb4-d988-4545-9497-a5e583670ad3.png)

### The Reality

Bug1: adding optifine turns it into this:
![image](https://user-images.githubusercontent.com/40274384/221020606-20946dc7-4095-4415-82cf-2a51fa683176.png)

Bug2: not starting a brandnew testworld but instead loading a world with a lot of world time turns that into this:
![image](https://user-images.githubusercontent.com/40274384/221020749-5332d1f9-d5b3-4106-a95c-535e3c15b793.png)

### Your Proposal

fix it :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@GTNH-Colen

**Comment by Dream-Master** [comment]
with 2.2.12 spactime works universum not
![image](https://user-images.githubusercontent.com/2970688/221025205-ed1fd13c-78fc-4c19-bfd1-f269b6150f0c.png)

**Comment by chochem** [comment]
Should now all be fixed with https://github.com/GTNewHorizons/Avaritia/pull/37
