### ISSUE TITLE
ExtraCells2 fluid storage cells are missing their conversion recipe

### ISSUE THREAD

**Issue by Shadowsoftime99** [GTNewHorizons/GT-New-Horizons-Modpack#12695]
### Your GTNH Discord Username

Shadows#4865

### Your Pack Version

2.2.10

### Your Server

Private

### Java Version

Java 8

### Type of Server

None

### Your Expectation

EC2 deprecation! We all know it's coming. There's a big warning in chat when you log in, and in every EC2 item's tooltip. So I emptied out my one fluid storage cell, and tried to convert it in the crafting grid as advertised.

### The Reality

No recipe. I can't do anything with this fluid cell now. No way to take out the core, no way to convert it into the AE2FC version, nothing.

![image](https://user-images.githubusercontent.com/16748195/221118757-52cb0d03-524b-4ffd-aba2-0eebc2745c8a.png)

### Your Proposal

Just add a conversion recipe. It's honestly still a downgrade if it converts to a normal FC cell (not a multi one), but at least it's getting something for it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by CatsLeftEar** [comment]
Also when you disassemble a ae2fc fluid storage cell, it gives you a housing which is unusable
