### ISSUE TITLE
Gregtech plates changes to railcraft plates

### ISSUE THREAD

**Issue by rybijakKarpiowy** [GTNewHorizons/GT-New-Horizons-Modpack#12704]
### Your Pack Version

2.2.0.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I crafted/looked at iron/steel plates

### The Reality

Gregtech plates are crafted, then item changes to railcraft one (it is only a visual inconvenience), it may be because of save transfer after hard drive format.

### Your Proposal

Stop changing gregtech to railcraft plates

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
so what are these steps to reproduce that you say you have?

**Comment by rybijakKarpiowy** [comment]
> so what are these steps to reproduce that you say you have?

Yeah sorry, i missclicked this one. I think that problem occurs because of replacing some config files but i don't know which are responsible for this behaviour

**Comment by Glease** [comment]
Overwrite your current `.minecraft/config/GregTech/Unification.cfg` with the one from release zip.
