### ISSUE TITLE
Crash while scrolling out in Journeymap

### ISSUE THREAD

**Issue by Theguyhere0** [GTNewHorizons/GT-New-Horizons-Modpack#12709]
### Your GTNH Discord Username

Theguyhere#1421

### Your Pack Version

2.2.0.0

### Your Server

Earthquake

### Java Version

Java 8

### Type of Server

None

### Your Actions

I was in Journeymap and tried to scroll out. It then proceeded to show me a screen with tiled netherack textures before crashing.

### Crash Report

[crash-2023-02-25_18.20.32-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10832707/crash-2023-02-25_18.20.32-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by eigenraven** [comment]
Looks like journeymap ran out of the native memory limit, you can raise it with `-XX:MaxDirectMemorySize=1024M` (default is 64M). I don't think we could fix this without significantly modifying how JM handles images, and JM being closed source would make that very difficult.
