### ISSUE TITLE
Duplicate fluid with new hot AE2 Fluid Crafting

### ISSUE THREAD

**Issue by nanmumc** [GTNewHorizons/GT-New-Horizons-Modpack#12700]
### Your GTNH Discord Username

のき#4678

### Your Pack Version

2.2.10

### Your Server

private server and sp

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Expectation

**Just attach more than 1 Fluid Storage Bus on same fluid storage.**
![image](https://user-images.githubusercontent.com/25528572/221346564-c2a67c24-f65d-4583-8439-e90ecffc64c8.png)

**See gif:**
![动画](https://user-images.githubusercontent.com/25528572/221346567-4d06b268-2b12-4cba-883c-31b0da6871c1.gif)

### The Reality

see above

### Your Proposal

fix it!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment]
the fluid dupe fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/161e38cbda299f8f64860fb0aa9653016f48cfd7
but the display hasn't been fixed yet. anyway you shouldn't put multiple storage bus (both item and fluid one) on the same block, it will cause visual bugs

**Comment by nanmumc** [comment]
> the fluid dupe fixed by [GTNewHorizons/AE2FluidCraft-Rework@161e38c](https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/161e38cbda299f8f64860fb0aa9653016f48cfd7) but the display hasn't been fixed yet. anyway you shouldn't put multiple storage bus (both item and fluid one) on the same block, it will cause visual bugs

Thank you for the quick fix.
By the way, it seems that the fluid terminal of AE2FC does not compatible with NotEnoughCharacters (拼音搜索), but the terminal from Extra Cell2 can do that, do you have any idea about it?
