### ISSUE TITLE
Recipe conflict between drill head casting form and coinage mold

### ISSUE THREAD

**Issue by TealSeer** [GTNewHorizons/GT-New-Horizons-Modpack#12714]
### Your Pack Version

2.1.10

### Your Server

Private

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Should be able to craft a drill head casting form using the recipe shown in NEI
![image](https://user-images.githubusercontent.com/75404941/221430147-6e5199b6-1c6e-4d8f-ba4e-c4d9dd837b70.png)

### The Reality

That recipe instead outputs casting form for a coinage mold which appears to be on the same recipe
![image](https://user-images.githubusercontent.com/75404941/221430178-85f2ab98-6dd8-452e-ab49-a79b9ead70a2.png)

### Your Proposal

Make em different

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueWeabo** [comment]
fixed in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/532
