### ISSUE TITLE
Changing EnablePollution to false does not stop pollution from going up.

### ISSUE THREAD

**Issue by Srdra2k3** [GTNewHorizons/GT-New-Horizons-Modpack#12716]
### Your GTNH Discord Username

Srdra#7777

### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Changing EnablePollution:true into EnablePollution:false in the GregTech/GregTech.cfg would disable pollution all together.
Was done a week ago on a fresh world.

### The Reality

Pollution still goes up.

### Your Proposal

Either something wrong with configs or I'm doing something wrong.
I have asked around and am yet to get a response if anyone else has had this problem.
It is pretty weird why the config change would not work.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I cant reproduce this. Just tried on 2.2.12 3-dev-pre with java8 and the config works.

**Comment by Srdra2k3** [comment]
I think I might have found the issue, I had an EBF setup running with MV combustion generators. The EBF does not generate any pollution with the config disabled. But the generators still generate pollution.

**Comment by Srdra2k3** [comment]
Nope i was wrong

**Comment by Srdra2k3** [comment]
I will be updating to 2.2.12 3-dev-pre java 8 to see if the issue persists.

**Comment by Srdra2k3** [comment]
Everything seems to run fine after updating to dev. Maybe it was an issue with running on Java 17?

**Comment by Srdra2k3** [comment]
After installing jwjgl3ify and running the server on Java 17 again but on version 2.2.12 3-dev-pre, pollution seemed to stop increasing. Since this version is the "latest", I will just be closing the ticket.
