### ISSUE TITLE
AE pull prioritizes renamed stuff

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#12715]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.2.12-2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Expected ae to make pattern from clean item when i use shift+click on recipe

### The Reality

![image](https://user-images.githubusercontent.com/39595617/221430350-e759e04c-812d-4818-ba76-2fba6926cb3d.png)
it pulls renamed items instead of clean ones

### Your Proposal

Its annoying, u have to replace items manually to clean ones

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by asdflj** [comment]
it's not bug, when you in fc pattern terminal use shift click well be use exist item to fill pattern
if you want clean item just click ? button

**Comment by LewisSaber** [comment]
It works, thanks for the tip, I think this issue is irrelevant then
