### ISSUE TITLE
Redstone Transmitter (Internal) Not Working Properly

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#12713]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I wish to detect whether an EOH was running. Its main block has no free sides, so I decided to use an Activity Detector Cover, and a Redstone Transmitter (Internal) to send the signal wirelessly. A Redstone Receiver (External) on a steel frame box was attuned with the transmitter. 

### The Reality

No matter whether the EOH is running or not, the receiver received nothing but a 15 signal.

I tried Advanced types of the cover but nothing changed. 
Later I tested other covers like Fluid Detector and Item Detector, and none of them seems to act properly.

### Your Proposal

Make Redstone Transmitter (Internal) send the redstone signal outputed by other covers on the same block properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
If I understand the transmitter (internal) right then it works as expected. It does not transmit the strength of another cover, but instead the redstone output, which the controller has on that side. So if you use a Neutron Sensor for example you could put the cover on the side that would output redstone, and it would output the redstone through the transmitter.
