### ISSUE TITLE
Dysom Swarm formula optimizing suggestions

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#12720]
### Your Pack Version

2.2.10

### Your Proposal

I would like to suggest a new module loss formula for Dyson Swarm.

### Your Goal

In the current version, Dyson Swarm is an important way for generation in endgame period of the game. However, in recent updates the module amount of Dyson Swarm is limited to 9999, which means one set of Dyson Swarm can only generate 5GEU/t.
Imagine a player wants to provide energy for his newly comstructed T0 EOH; he decides to overclock it once to get a relatively rational process time. Therefore, he will need 683GEU/t generation, or 131 sets of Dyson Swarm. This can be balanced, but quite tps- and hand-unfriendly. 
Meanwhile, the current module loss formula is n=(2*0.001)/(exp(-0.0001*(m-1))+exp(0.001*cps)). This formula resulted that no matter computation is provided or not, it gives no higher loss of n=0.002, which means the Dyson Swarm will only loss 1 module each hour. This makes it meaningless to provide computation for Dyson Swarms, and the cost also seemed too little for its generation.

### Your Vision

A new formula of module loss could be a solution for the situation.
As an simple example, add an factor m to the formula: n=m*(2*0.001)/(exp(-0.0001*(m-1))+exp(0.001*cps)).
This new formula will make the cost more rational and computation more useful.
Back to the T0-EOH example; the player will need 1303355 modules to meet the energy need. If he doesnt apply any computation he will need to craft 2607 modules each hour. with more computation applied the crafting demand will be less: 1000cps = 958module/h, 2000cps = 352module/h, etc.. This seems more realistic.
(Of course the parameters and the form of formula can be changed for better balancing.)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Connor-Colenso** [comment]
My understanding is that the Dyson currently caps out at around 250B EU/t if used on the right planet, not 5B EU/t? I agree that dyson should lose more modules/cycle than it currently does but it's not impractical in its current state to use.

A dyson rework is hopefully in the works however and has been discussed among the dev team.

**Comment by TheEpicGamer274** [comment]
dyson has weird configs and the per drone or whatever they care called should be set to 10M eu/t by default, not whatever the tooltip says

**Comment by minecraft7771** [comment]
I think the config in the modpack was updated after 2.2.10. You could update the config on its own or update the full pack.
