### ISSUE TITLE
STATUS_STACK_BUFFER_OVERRUN hard exit crash

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#12728]
### Your GTNH Discord Username

KiloJoel#3044

### Your Pack Version

2.2.8

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

No specific action or trigger apparent.

I was standing next to en enderman spawner smeltery farm in a roguelike dungeon, but the same crash has happened in other circumstances.

![image](https://user-images.githubusercontent.com/17787093/221683068-748bbb9e-6fcc-48b8-9264-33a8db2f2e01.png)

### Crash Report

https://paste.ee/p/0LOZm - MultiMC log
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10844156/fml-client-latest.log)
[PlayerActivity.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10844160/PlayerActivity.log)
[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10844161/GregTech.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10844162/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by GamerSocke** [comment]
Got the same crash with 2.2.10 J9 in MultiMC.
