### ISSUE TITLE
Add macerator, fluid extractor recipes for Glass Bottles

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#12735]
### Your GTNH Discord Username

Abdiel Kavash#2431

### Your Pack Version

2.2.0.0

### Your Proposal

Add a macerator recipe that turns one (empty) glass bottle into one glass dust; and a fluid extractor recipe that turns an empty glass bottle into 144 mB of molten glass.

### Your Goal

A witch in an EEC is a fast and renewable source of several resources (redstone, glowstone, sugar, gunpowder). Witches also drop glass bottles, which flood the destination system. It would be nice if these bottles could be turned into regular glass. However, currently no direct recipe to do this exists. The quickest way to do this is to fill the bottle with water, and then the water bottle can be macerated or fluid extracted into the equivalent of one block of glass. It would be nice if this could be done with the empty bottle as well, without the unnecessary filling step.

### Your Vision

QoL when recycling empty bottles.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
@wlhlm why help wanted? looks finished, no?

**Comment by wlhlm** [comment]
@chochem That was an oversight on my part. Closing
