### ISSUE TITLE
Recipe for adding part assembly lines to UXV parts

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12732]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.10

### Your Proposal

Recipe for adding part assembly lines to UXV parts

### Your Goal

Materials for UXV components are very expensive and take too long

### Your Vision

Less pointless waiting time later, after all, we have more to do, right?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
you mean CoAL recipes? (machine translations, I know)
