### ISSUE TITLE
Buff large naquadah reactor

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12741]
### Your Pack Version

2.2.10

### Your Proposal

Significantly increase the power output of most fuels inserted into the large naquadah reactor and make its fuels considerably cheaper.

### Your Goal

Right now fusion and compact fusion are always a cheaper and easier option delivering more power than the naquadah reactor ever could while burning through expensive resources.

### Your Vision

Make the naquadah reactor a worthwhile option so it gets used.
A compact fusion can run basically for free, while a naquadah reactor currently eats through infinity and hypogen if you want it to deliver a worthwhile amount of power, and this for an end-game goal energy source

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Fiyorin** [comment]
bump

**Comment by Alastors** [comment]
This was basically done recently, so I think it’s completed?
