### ISSUE TITLE
Proposal for a giant 9-in-1 machine

### ISSUE THREAD

**Issue by CrJolin0783** [GTNewHorizons/GT-New-Horizons-Modpack#12744]
### Your Pack Version

2.2.9.7

### Your Proposal

Suggest a giant version of the 9-in-1 factory, like an alloy smelter

### Your Goal

I'm at the UV-UHV stage within version 2.2.9.7 I've currently put n nine-in-one factories in and I'm not only pulling wires for each of them Configuring them into automation and planning sensible locations for them But they're not processing as fast as I'd like them to. If I keep stacking them, it will look very bloated.
I hope to be able to launch a giant machine version of the 9-in-1 soon, the speed of my precision etching is really very unsatisfactory.
I hope it comes out soon. It will save us all.

### Your Vision

He can help us save a lot of space and time, so that we don't have to gaze at it every day after work, which in turn greatly optimizes our gaming experience, including improving fps.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
I think this will only be addressed when multi tile entities (mute) release soon™.

**Comment by 27yearoldminecraftgaymer** [comment]
I'd recommend a mega mega blast furnace, mega industrial centrifuge, and mega mega chemical reactor too. my speeds are very unsatisfactory.

**Comment by minecraft7771** [comment]
> I'd recommend a mega mega blast furnace, mega industrial centrifuge, and mega mega chemical reactor too. my speeds are very unsatisfactory.

Wdym mega blast furnace and mega chem reactor exist.

**Comment by chochem** [comment]
> I'd recommend a mega mega blast furnace, mega industrial centrifuge, and mega mega chemical reactor too. my speeds are very unsatisfactory.

you are at UV-UHV. the speeds are totally fine. MCR is already the most overpowered multi at that stage. And MBF is great at that level too.

If you were umv-uxv I might understand this, but uv-uhv makes no sense. You must be doing something wrong, this sounds like (large scale) user error.

**Comment by CrJolin0783** [comment]
> 9 in 1 was just alk being lazy to make 9 multies. If anything the 9 multis should be done now, as anyways if you passivate your automations, you only use one machine of the 9 in 1 multies. At least it would have more diversity on the walls of machines.

Can you specifically ask the team if they are preparing a giant 9-in-1 solution or are they preparing nine different big/giant machines?
At this stage, I'm using the nine-in-one extraction model to extract the Cetacean T-star algae
Autoclave mode to obtain crystal circuits
Precision etching to get n wafers to make circuit boards
It's two more parallelism per voltage increase, but he doesn't support lasers and I can't give him more current than I want, which causes me to switch to a higher level energy bin if I want him to do more each time, which is really hard.
We really need a high parallelism machine to fulfill our orders.

**Comment by CrJolin0783** [comment]
> 9合1只是懒得做9倍。如果现在应该做什么，9倍增，就像无论如何，如果你钝化你的自动化，你只使用9合1倍增中的一台机器。至少它在机器的墙上会有更多的多样性。

Can you specifically ask the team if they are preparing a giant 9-in-1 solution or are they preparing nine different big/giant machines?
At this stage, I'm using the nine-in-one extraction model to extract the Cetacean T-star algae
Autoclave mode to obtain crystal circuits
Precision etching to get n wafers to make circuit boards
It's two more parallelism per voltage increase, but he doesn't support lasers and I can't give him more current than I want, which causes me to switch to a higher level energy bin if I want him to do more each time, which is really hard.
We really need a high parallelism machine to fulfill our orders.

**Comment by chochem** [comment]
the thing that is worked on is a new multi system, not patchwork on the old.

Anyway, as I already said, if you are struggling in UV/UHV you must just be doing something wrong. So that is easy to fix just on your end. Make sure to upgrade your energy hatches, upgrade the coils/glass/laser on your MBF, and dont use just one machine for everything. Consider PAs for things you just want to throw 64A at to make things faster. And so on. Really better to ask on the help discord channel than here.

**Comment by CrJolin0783** [comment]
> the thing that is worked on is a new multi system, not patchwork on the old.
> 
> Anyway, as I already said, if you are struggling in UV/UHV you must just be doing something wrong. So that is easy to fix just on your end. Make sure to upgrade your energy hatches, upgrade the coils/glass/laser on your MBF, and dont use just one machine for everything. Consider PAs for things you just want to throw 64A at to make things faster. And so on. Really better to ask on the help discord channel than here.

Here's the thing, I have placed six or seven 9-in-1, each of which is divided into two UHV energy bins, because I am in the TPS situation of this server is not very good, at this stage there is no way to place higher-level energy bins, and 9-in-1 parallelism and voltage related, can not be placed on the laser to improve parallelism, which led to all my orders are now stuck in the 9-in-1 above the most important is Parallelism is too low
So I came to ask if there is a plan to come out with a high parallelism of the giant machine to make up for this stage of the embarrassing period

**Comment by CrJolin0783** [comment]
> In the future it is planned for a better multi for each of the machines inside of the 9-in-1

Okay,I'm looking forward to his launch now!

**Comment by Glease** [comment]
the spirit of nine in one is that you share the machine for a few less used recipe map. if some recipe lamp has become so frequently used it will need its own multi
