### ISSUE TITLE
GalaxySpace Lead Ore Generating in Overworld

### ISSUE THREAD

**Issue by litten8** [GTNewHorizons/GT-New-Horizons-Modpack#12752]
### Your GTNH Discord Username

Agwic#0141

### Your Pack Version

2.2.11-nightly

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Mining in overworld, expecting only to find Gregtech ores in Gregtech veins, such as the redstone vein I was mining at the time

### The Reality

I found this lead ore, which is not part of a Gregtech vein, and is also from GalaxySpace instead of Gregtech, lying around in the overworld
![image](https://user-images.githubusercontent.com/20496976/222311792-c0e6ffd8-89b4-47ea-8504-8a3844a831ba.png)

### Your Proposal

Ores in non-Gregtech veins probably aren't supposed to generate in the overworld.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Fixed by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/12717
