### ISSUE TITLE
Reduce cost of XL Turbines due to changes and clarification of advantages

### ISSUE THREAD

**Issue by Kyrorichekku** [GTNewHorizons/GT-New-Horizons-Modpack#12758]
### Your GTNH Discord Username

kyori#4690

### Your Pack Version

2.2.11

### Your Proposal

Reduce the cost of the XL steam turbines due to the addition of walls sharing of normal turbines

clarifying that the XL turbine no longer takes up the space of 12 turbines

### Your Goal

the addition of wall sharing large turbines completely defeats the point and claim of xl turbines taking the space of 12 turbines (at ridiculously higher price)

one of the current main advantage still remaining with the xl turbine however is still that they without the turbine a turbine housing however this is not mentioned in the tooltip

![image](https://user-images.githubusercontent.com/123538122/222414178-562d839a-b56b-41b9-b5b4-025011aa4dc6.png)

### Your Vision

XL turbines come at an extremely high expense for now far more minimal advantages ( the current turbines people likely use only need to switch out turbines blades a few times a month at most )

there should be more clear reasons to use something this prohibitively expensive but potentially more server friendly option

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
XL Turbines are too strong as it is, the only reasonable change in cost is to make them more expensive.
