### ISSUE TITLE
Ore generation Twilight Forest

### ISSUE THREAD

**Issue by AnmolBeep** [GTNewHorizons/GT-New-Horizons-Modpack#12751]
### Your GTNH Discord Username

ANMOL#4127

### Your Pack Version

2.2.10

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Entered/Generated Twilight Forest for the first time wanted to mine ore.

### The Reality

Not a single ore generated besides some in the hollow hills. Not a single small or normal ore found elsewhere after checking about 10 ore chunks and mined 10+ stacks of stone.
Confirmed with a freshly created world, in which I used the Prospector's Scanner. Not a single entry in the twilight forest, while I got dozens in the overworld.

![2023-03-01_22 49 40](https://user-images.githubusercontent.com/126725439/222274236-a494572c-2727-4436-b7f4-53d7884a56aa.png)

### Your Proposal

Ore generation in the twilight forest seems to be bugged in version 2.2.10 (Twilight Forest version 2.3.8.17) and should be fixed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
work just fine for me in both 2.2.10 and 2.3.0RC

**Comment by chochem** [comment]
my best bet would be that you broke you config files somehow. Best replace your config folder with a fresh one.

**Comment by AnmolBeep** [comment]
I actually had some troubles with corrupted saves before,  but I didn't expect it to corrupt the config files in such a way, that only the twilight forest ore generation didn't work. Especially because I never visited it before.

I must've somehow corrupted my backup config though. Took files from a new install and now it works.
Thanks a lot and sorry for the inconvenience, I should've figured it out by myself.
