### ISSUE TITLE
EnderIO Conduit Connection Colors Not Updating

### ISSUE THREAD

**Issue by MrNoe93** [GTNewHorizons/GT-New-Horizons-Modpack#12753]
### Your GTNH Discord Username

MrNoe#3937

### Your Pack Version

2.3.0 RC 1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Opened enderio conduit connector and attempted to change the color of the insert/extract.

### The Reality

When the GUI is closed the colors dont change.  When its opened again they are back to their original color.  Conduits placed in the previous version still have their coloring but attempts to change it dont work.

### Your Proposal

Bug that needs fixed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by trollolal** [comment]
I also have this problem. Maybe need to backport to previous version.

**Comment by Glease** [comment]
Seems to be broken by https://github.com/GTNewHorizons/EnderIO/pull/101 @eigenraven
