### ISSUE TITLE
Void world cannot change biome

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#12759]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.0-RC-1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Void World can changed biome with silverwood tree pure node.

### The Reality

It doesnt change and stay in the default biome

### Your Proposal

Fix it?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
@eigenraven I hope you have actually seen this. I am pretty sure this worked before in 2.2.x so I assume this is just a bug of sorts?

**Comment by eigenraven** [comment]
It seems that disabling trees and disabling aura nodes modifying biomes is controlled by the same variable in thaumcraft
