### ISSUE TITLE
Breaking gravel with GT hammer drops both gravel and sand

### ISSUE THREAD

**Issue by danielrab** [GTNewHorizons/GT-New-Horizons-Modpack#12755]
### Your GTNH Discord Username

danielrab#7070

### Your Pack Version

2.3.0-RC-1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When breaking gravel with a GT hammer, just sand should drop, gravel should be consumed.

### The Reality

Both sand and gravel are dropped

### Your Proposal

Consume gravel properly the same way it happens with other transformations like cobble to gravel.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AlexisGoblot** [comment]
finally 😂
