### ISSUE TITLE
Steel bee requires non-existent foundation block

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12750]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Although i've pointed it out in the discord months ago, i recently got someone asking me how i once bred the steel bee.
Only to notice that the foundation block it asks for still goes by the internal name of ic2.blockMetalAdvIron, which doesn't exist.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I am pretty sure I asked you to make a ticket back then. guess you forgot.

**Comment by Tommeh1** [comment]
> I am pretty sure I asked you to make a ticket back then. guess you forgot.

Iirc i got yelled at by multiple devs stating to just use a steel block, despite me stating that i tried it and that it didn't work, after which i didn't bother further given their negligence.

**Comment by Tommeh1** [comment]
> I looked at it and several other questions you had and told you to make a ticket for this one despite you not being nice at all :(

This shouldn't come as a surprise given the behavior of many devs, everyone i hear despises the behavior and priorities of most of this dev team.
This often also results in issues not being reported as it seemingly lacks functionality, i'm one of the few that bothers with reporting most issues, if we reported everything we would easily exceed 100 open issues right now.

**Comment by chochem** [comment]
I have had great experience with the rest of the dev team. :)

Your server is somehow more cursed and broken than anything I ever played on, not sure why. Some of your issues are rather exotic. Not this one obviously.

anyway I guess this is all a bit offtopic :P

**Comment by Tommeh1** [comment]
> I have had great experience with the rest of the dev team. :)
> 
> Your server is somehow more cursed and broken than anything I ever played on, not sure why. Some of your issues are rather exotic. Not this one obviously.
> 
> anyway I guess this is all a bit offtopic :P

This server is not more cursed, but i'm known for being able to break anything to the point that i've tested quite a few things here and there throughout the years for other projects.
I'm the one to ask for when issues have to be found.
