### ISSUE TITLE
Random Crash on 2.3.0 RC1 Possibly Caused by AE2FC

### ISSUE THREAD

**Issue by Srdra2k3** [GTNewHorizons/GT-New-Horizons-Modpack#12769]
### Your GTNH Discord Username

Srdra#7777

### Your Pack Version

2.3.0 RC1

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

I am getting random client crashes during gameplay on version 2.3.0 RC1.
I think the issue might be caused by AE2FC. At the moment I only have dual interfaces, fluid cells, fluid storage buses, fluid export buses and fluid storage monitors set up.

### Crash Report
Client Log:
https://mclo.gs/DsBJsqB

Server Log:
https://mclo.gs/gxxszfy

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by asdflj** [comment]
@GlodBlock

**Comment by firenoo** [comment]
Seems like an issue with OpenGL 3 and GL11 being incompatible.

**Comment by Glease** [comment]
Related: https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/254
