### ISSUE TITLE
AE2FC Fluid export bus voiding liquids on a subnet connected with "extract only" bus

### ISSUE THREAD

**Issue by terreo** [GTNewHorizons/GT-New-Horizons-Modpack#12763]
### Your GTNH Discord Username

rick#6896

### Your Pack Version

2.3.0 RC-1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I tried to make a subnet with a dual interface + fluid storage bus connection with extract only mode.

### The Reality

The fluid export bus continues to void liquids even after it's target hatch is full. This does not happen in bi-directional mode.
![fluidsubnetbug](https://user-images.githubusercontent.com/29600867/222487479-f9a4000b-2e47-4a9d-b13b-619f51a276bf.png)

### Your Proposal

Fluids shouldn't continue to be exported into a full hatch.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by asdflj** [comment]
don't set as extract only,fluid bus try to export real fluid,but target tank can't fill fluid, and u set as extract only, fluid can't be return to source tank

**Comment by asdflj** [comment]
fix by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/18f31ac3ef836d1cfe076beb887a59e37c6b38b3
