### ISSUE TITLE
AE2FC universal wireless terminal does not update view in real time

### ISSUE THREAD

**Issue by ZuOverture** [GTNewHorizons/GT-New-Horizons-Modpack#12761]
### Your GTNH Discord Username

AnCorp#8466

### Your Pack Version

2.3.0-RC

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Have working ME system with linked AE2FC universal wireless terminal.
Open wireless terminal.
Let ME system storage contents change (for example have import bus on a full chest in background)
See imported items show up in terminal immediately.

### The Reality

Item view does not update unless you switch terminal to a different mode or close it and reopen.

### Your Proposal

Send view update notices once a second maybe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by CatsLeftEar** [comment]
Also universal wireless terminal will kick you from the server if you try to take fluids with more cells than there is fluid in it, for example, take 40k with 64 cells with shift click

**Comment by asdflj** [comment]
> Also universal wireless terminal will kick you from the server if you try to take fluids with more cells than there is fluid in it, for example, take 40k with 64 cells with shift click

try update ae2fc
