### ISSUE TITLE
Local energy net stops responding after rotating an energy accepting block toward an unconnected cable

### ISSUE THREAD

**Issue by terreo** [GTNewHorizons/GT-New-Horizons-Modpack#12774]
### Your GTNH Discord Username

rick#6896

### Your Pack Version

2.3.0 RC-1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I added an energy hatch next to a cable and then rotated the input side to face the (not yet connected) cable. I expect power to continue working normally.

### The Reality

When the energy hatch is rotated towards the unconnected wire, all EU packets stop going to the other machines. Making new connections anywhere on the wire allows the EU to work properly again. The problem only occurs when rotating blocks and not when placing them in the "bad" orientation.
![3](https://user-images.githubusercontent.com/29600867/222636586-266fee92-0327-4a87-8819-cb576d502e20.png)

### Your Proposal

New unconnected blocks should properly update the energy system

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
I've had similar issues before when connecting new machines back in 2.2.3, forcing me to break the connection between source and a large group of machines to then re-connect it all.
