### ISSUE TITLE
Chemical Plant refuses to form under certain circumstances

### ISSUE THREAD

**Issue by Rosenlied-Iris** [GTNewHorizons/GT-New-Horizons-Modpack#12772]
### Your GTNH Discord Username

Rosenlied#3858

### Your Pack Version

2.3.0-RC

### Your Server

Singleplayer + private server

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

~ Additional note: Bug still occurs on vanilla forge server

Expectation: a chemical plant using HV machine casings, tungstensteel pipe casings, titanium solid casings, and nichrome coils should form, accept HV energy hatches+I/O hatches/buses, and function (running at 150% speed with parallels)
![image](https://user-images.githubusercontent.com/125097220/222618925-12200448-39d0-49f4-80c4-22125122aba1.png)

### The Reality

Chemical plant controller says "incomplete structure", even when replacing controller/placing maintenance hatch in other positions. Machine visually forms (hatches and controller change color), but will not turn on and recognize structure at controller.

### Your Proposal

Fix chemplant so it properly forms, as it otherwise makes chemplant-gated items impossible

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Rosenlied-Iris** [comment]
Relogging again results in different irregular behavior: chemplant forms but will not run recipes despite having everything in hatches.

**Comment by chochem** [comment]
Just tested with a brandnew chemplant on 2.3.0-RC1, same components as you.

1) immediately forms without issues
 2) immediately runs at 1.5x speed and 2 parallels (which is correct, the limit is power!)

![image](https://user-images.githubusercontent.com/40274384/222698986-dec5e44b-9475-4cb2-8eb0-b4ba62b1e8ab.png)

recipe is dense hydrazine
![image](https://user-images.githubusercontent.com/40274384/222699855-c2dc7f4c-b87e-47ab-b835-65ffc0d393c9.png)

**Comment by vovaksenov** [comment]
How many catalyst hatches do you have?

**Comment by nick-l-o3de** [comment]
This happened to me but it turns out that it refuses to form and behaves this way for me if I use a quad input hatch.  Normal input hatches work...

**Comment by koiNoCirculation** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/17c9b99a-4e3d-4654-81f4-c42c7f34dc0b)
doesn't form
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/17f47f55-7e35-4f8d-8b3a-7148c0848e30)
