### ISSUE TITLE
Thaumic Insurgence bugs

### ISSUE THREAD

**Issue by FloatDoubling** [GTNewHorizons/GT-New-Horizons-Modpack#12777]
### Your GTNH Discord Username

DarkEastSider#3859

### Your Pack Version

2.3.0-RC-2

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Thaumic Interfacer research should have localization, for both research name and description. Item missing locale too.
![image](https://user-images.githubusercontent.com/115502326/222794256-229f3b46-ffe9-4184-8a0e-7237452edd6d.png)

Also Sanitizing Soap Alpha and Alastor's Soap thaumonomicon pages show same recipe, while NEI shows different recipes.
![image](https://user-images.githubusercontent.com/115502326/222794299-2c536c3a-ba41-4f24-9d99-1b4bd884911b.png)

![image](https://user-images.githubusercontent.com/115502326/222794346-652c1fdf-fef5-45ec-910f-203eca87b05f.png)

### The Reality

Described above.

### Your Proposal

Fix this issues, should be pretty easy.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
These have been fixed
