### ISSUE TITLE
Cant Take/Put items in Universal Terminal

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#12778]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.3.0RC-2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Expected to be able to take item from terminal and to put them

### The Reality

It doesnt work

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Srdra2k3** [comment]
The same issue is also with the fluid pattern terminal
