### ISSUE TITLE
Wireless Fluid Detector Cover not working on high capacity fluid containers

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#12784]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.3.0-RC1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I tried to detect whether an input hatch is empty or not. It has no free surface so I decided to use the wireless version.

### The Reality

Despite how much fluid is in the hatch the cover sent no signal at all.

The cover worked all fine on Tanks and Super Tanks in privous usages.

### Your Proposal

The Wireless Fluid Detector Cover should properly send the signal.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Meanwhile with the non wireless version i'm noticing that the signal they send out does not visually update red alloy wire properly on larger tanks either.
It will blink on briefly and then render as if it ain't active, even if it is powering something at the end of the wire.
