### ISSUE TITLE
Aequalitas, Vesania, Primordium, Astrum, and Gloria incorrectly display as "Custom1", "Custom2"...

### ISSUE THREAD

**Issue by Rosenlied-Iris** [GTNewHorizons/GT-New-Horizons-Modpack#12786]
### Your GTNH Discord Username

Rosenlied#3858

### Your Pack Version

2.3.0 RC2

### Your Server

Singleplayer, private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Issue occurs on singleplayer as well.

Expecting to see new Thaumcraft aspects display properly in all cases.

### The Reality

![image](https://user-images.githubusercontent.com/125097220/222906437-0bde9979-4f68-4d10-8ce4-14945553353c.png)

Aspects are displayed in the alphabetical position of "custom1" on e.g. jarred nodes.

Aspects in thaumonomicon (e.g. Large Essentia Generator entry) incorrectly display as "Custom4" placeholders.

Aspects in WAILA when looking at nodes and essentia jars are listed as "Custom5" and the like.

### Your Proposal

Make the essentia display in the proper position alphabetically and fix references to placeholder "custom2" names.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
Reopened because only one part was adressed

**Comment by AbdielKavash** [comment]
I will add one more: The ME Essentia Terminal filtering uses the "custom" names, rather than the proper names:

https://i.imgur.com/jgEHTeI.png

https://i.imgur.com/RYnqq8v.png
