### ISSUE TITLE
Unequipping Piston Boots with Bibliocraft Armor Stand still gives you Step Height

### ISSUE THREAD

**Issue by slyk26** [GTNewHorizons/GT-New-Horizons-Modpack#12780]
### Your GTNH Discord Username

slyk26#2197

### Your Pack Version

2.2.9

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Context: Bibliocraft Armor Stand has the Shift+Right Click Interaction to swap its armor pieces with your equipped Armor 

What did i try to do: 

- Wear Piston Boots

=> I have the Step Height, 3 Block Jump, etc...

- Shift+Right another pair of Boots from the Armor Stand

=> i have an arbitrary pair of Boots equipped (or no boots)
=> I have no Step Height, Jump Height, ...  anymore

### The Reality

What happened instead:

- after putting the equipped Piston Boots with Shift+Rightclick on the Armor stand i still have the step height ( but not jump height, ...)

- after logging out to main menu and back into the world the step height is gone

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by CatsLeftEar** [comment]
Also if there are people with piston boots nearby, your boots with autostep, which are not piston boots, stop autostepping
