### ISSUE TITLE
Shift Clicking a pattern of Silicone Rubber Rings Puts in the Wrong Recipe for AE2FC terminals

### ISSUE THREAD

**Issue by Srdra2k3** [GTNewHorizons/GT-New-Horizons-Modpack#12782]
### Your GTNH Discord Username

Srdra#7777

### Your Pack Version

2.3.0 RC2

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Shift clicking the silicone rubber ring recipe into pattern terminal should have been:
Silicone Rubber dust = Silicone Rubber ring x4

### The Reality

Instead it is:
Rubber dust = Silicone Rubber ring x4

### Your Proposal

Make it:
Silicone Rubber dust = Silicone Rubber ring x4 again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Srdra2k3** [comment]
Another issue could be seen with encoding the IV pump assembler recipe, wherein the silicone rubber rings would be replaced by rubber rings with shift click.

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/222857757-e7c4fb33-14d3-4b72-bd22-196d6bf03185.png)
![image](https://user-images.githubusercontent.com/40274384/222857834-26500bda-04d4-42d9-8f6e-4c401ea4ad53.png)

Dont know what to say, it works flawlessly for me.

**Comment by LewisSaber** [comment]
Shift click now puts  items in pattern that u have in ae , if you want pattern with items as is, click without shift

**Comment by Tommeh1** [comment]
> ![image](https://user-images.githubusercontent.com/40274384/222857757-e7c4fb33-14d3-4b72-bd22-196d6bf03185.png) ![image](https://user-images.githubusercontent.com/40274384/222857834-26500bda-04d4-42d9-8f6e-4c401ea4ad53.png)
> 
> Dont know what to say, it works flawlessly for me.

It's inconsistent and will attempt using available OreDict substitutes, even if not allowed by the recipe like i mention in #12768

**Comment by chochem** [comment]
> Shift click now puts items in pattern that u have in ae , if you want pattern with items as is, click without shift

I tried with or without items in the system. did not change anything

**Comment by Tommeh1** [comment]
Chances are that it only tries alternatives when what it needs is not available, not sure.

**Comment by chochem** [comment]
yea thats not it

**Comment by Tommeh1** [comment]
It actually seems to not be a problem during all restarts, so i wouldn't be surprised if it links back to #11892 which still exists in 2.2.10

**Comment by chochem** [comment]
hmm. can you try in SP? maybe its a problem specific to servers. It obviously really shouldnt be, but its the only obvious difference I see.

also what terminal are you guys using? I am just using basic pattern terminal right now.

**Comment by Tommeh1** [comment]
I'm using the ME fluid pattern processing terminal, but right now i fail to trigger it again after the server restarted earlier today.

**Comment by Srdra2k3** [comment]
> > Shift click now puts items in pattern that u have in ae , if you want pattern with items as is, click without shift
> 
> I tried with or without items in the system. did not change anything

It happens when there is no silicone rubber rings and there is no recipe for the rings.
I've tried when the recipe was added and it worked fine.

**Comment by Srdra2k3** [comment]
I tried it on the fluid pattern terminal

**Comment by chochem** [comment]
ok. so normal pattern terminal always gets it right.

And in any ae2fc terminal (fluid or fluid proc or whatever): still works if you have the dust in the system.

no longer works correctly when you dont.

**Comment by chochem** [comment]
> This is intended feature

definetly not. this should only apply when the subsitution is valid in the recipe.

**Comment by chochem** [comment]
lesson today: please give more info in tickets ;)

**Comment by Srdra2k3** [comment]
Yeah sorry about that, still pretty new to making tickets and reporting stuff.

**Comment by asdflj** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12715

**Comment by chochem** [comment]
@asdflj here we are talking about items that cant work in the recipe.

**Comment by trollolal** [comment]
I can also reproduce in 2.3.0 RC-1
![image](https://user-images.githubusercontent.com/105285781/222879654-0d02b947-6851-446e-b35a-dd103f205292.png)
