### ISSUE TITLE
Buff Quantum Force Transformer

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12788]
### Your Pack Version

2.2.10

### Your Proposal

Buff the speed of the Quantum Force Transformer and reduce its energy usage by at least 75%.

### Your Goal

Currently, with how slow it is, even when given a stack of catalysts and max tier power it's nothing compared to some of the lines it replaces like an entire platline, neither in speed or the amount of energy used.

### Your Vision

These changes should make this multi a more worthwhile investment, simplifying certain processing lines near the end game while improving performance, despite the over 1ms spike each one currently causes when finishing a processing cycle.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by BlueWeabo** [comment]
Have you tried using neptunium and fermium plasma

**Comment by Tommeh1** [comment]
> Have you tried using neptunium and fermium plasma

These only make it less worthwhile due to how hard these are to come by

**Comment by BlueWeabo** [comment]
You can supply more than MAX voltage. Also the plasmas make it more worthwhile. As it can increase the chances significantly for all outputs.

**Comment by Tommeh1** [comment]
At that point i'm better off putting platline on something better than ZPM, at which tier it wipes the floor with the quantum

**Comment by BlueWeabo** [comment]
Are you sure about that? Platline only makes about 1/10th the osmium that the qft can make. QFT can make 2:1 for 5 dusts and 1:1 for one with all the plasma's supplied. Try to make platline do that.

**Comment by Tommeh1** [comment]
Or even opt for the much cheaper space elevator in the case of platline 
![image](https://user-images.githubusercontent.com/39203645/222922725-936dd2a0-f0f0-4c81-8822-5fc9f549c3c7.png)
The quantum is absolutely nothing against this

**Comment by Tommeh1** [comment]
> Are you sure about that? Platline only makes about 1/10th the osmium that the qft can make. QFT can make 2:1 for 5 dusts and 1:1 for one with all the plasma's supplied. Try to make platline do that.

I don't care much about the rates, things like platinum mixture dust are very cheap, i care about how fast and how cheaply i can process it.

**Comment by BlueWeabo** [comment]
alright if you say so.
1. MK3 Mining is needed, which is later than t1 QFT
2. At those distances, unless you use a UEV drone you will not be getting much out of that recipes
3. I am unsure how you can have problems with energy. Its more free than free resources in late game right now
4. Your platline with MCRs will be  much laggier than 1 QFT at max parallel and 2 compact mk4s (that is if you want 100% uptime for both plasma for two(2) QFTs at 64 parallel t4)
5. QFT is fast as fuck. it was able to delete all our pmp stock at t1 with just a 256A UMV laser. (if you can't spare the power for that at UEV... i wish you good luck for the DTPF plasma's)

**Comment by Tommeh1** [comment]
> alright if you say so.
> 
> 1. MK3 Mining is needed, which is later than t1 QFT
> 2. At those distances, unless you use a UEV drone you will not be getting much out of that recipes
> 3. I am unsure how you can have problems with energy. Its more free than free resources in late game right now
> 4. Your platline with MCRs will be  much laggier than 1 QFT at max parallel and 2 compact mk4s (that is if you want 100% uptime for both plasma for two(2) QFTs at 64 parallel t4)
> 5. QFT is fast as fuck. it was able to delete all our pmp stock at t1 with just a 256A UMV laser. (if you can't spare the power for that at UEV... i wish you good luck for the DTPF plasma's)

It's the fact that i would need to pump oh so many max amps into it for it to produce enough, we burn through various resources it makes by the millions

**Comment by BlueWeabo** [comment]
Alright please provide me with the numbers then. Tell me how much better a normal platline is than the one in the QFT.

**Comment by Tommeh1** [comment]
Closing this ticket, as i have been informed that, behind my back, boubou has ordered you to not deal with my issues.
