### ISSUE TITLE
Openblocks Golden Eye Broken

### ISSUE THREAD

**Issue by ArticulatedDrunk** [GTNewHorizons/GT-New-Horizons-Modpack#12789]
### Your GTNH Discord Username

Ozymandias#3078

### Your Pack Version

2.2.8

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Should be a reusable ender eye.

### The Reality

Does nothing and no buttons work.

### Your Proposal

Fix bug if possible or disable and remove item so people don't waste eyes of ender crafting it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by r1tsuu** [comment]
That's strange that it works (i cloned this repo and run dev env https://github.com/GTNewHorizons/OpenBlocks )
![image](https://user-images.githubusercontent.com/64744993/222936221-2fe2e7d2-4dbe-4d1f-8acb-157da1b7100d.png)
But i can confirm that it not works in GTNH
I'm thinking this https://github.com/GTNewHorizons/OpenModsLib/blob/024a52ca3566f39ecc500e0389d44a3ac9f1f880/src/main/java/openmods/world/StructureRegistry.java#L149 causes problems
(entry point of right clicking https://github.com/GTNewHorizons/OpenBlocks/blob/24cf30585a6ca1c421948cf52b9dc4701b46f603/src/main/java/openblocks/common/item/ItemGoldenEye.java#L42 )
but who knows..
