### ISSUE TITLE
ME Level Emitter with Crafting Card not working properly

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#12785]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.3.0-RC1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I tried to detect whether an item is being crafted or not in an attempt to automate EOH. I used ME Level Emitter with Crafting Card, with "emit signal when crafting" mode on. It is supposed to give a redstone signal when the item is being crafted, and stop giving signal when the crafting is finished.

The labelled item was a renamed paper, for sending hydrogen & helium through fake crafting.

### The Reality

Redstone signal was correctly given when crafting starts but it never went out anymore.

### Your Proposal

Make it go out properly when all crafting of the labelled item is finished.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Darkenlord1** [comment]
Still same in 2.6.1
Sending redstone when crafting but not stopping when craft is finished. 

However, working fine for my wither killing farm and for tree farm for some time, but broke recently for unknown for me reason.
