### ISSUE TITLE
Add KubaTech Teas to Spice of Life

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#12797]
### Your GTNH Discord Username

Abdiel Kavash#2431

### Your Pack Version

2.3.0-RC-2_(MMC)

### Your Proposal

The different types of Tea from Kubatech can be consumed and they restore hunger points. However, those points do not count towards bonus hearts from Spice of Life, and drinking tea does not advance the food variety ("Eaten N times out of the last 20 foods") counter on other food items.

I suggest adding compatibility so that tea counts as a proper "food" item.

### Your Goal

Expected bonus hearts when trying new foods. Received delicious tea and disappointment.

### Your Vision

More hearts.
More food variety.
More reason to build the tea line.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Oh i thought that was already integrated ?
Are there more food not integrated in spice of life ?

**Comment by chochem** [comment]
I seems they act more like potions at the moment.

**Comment by Dream-Master** [comment]
So food will be automaticly added ?
