### ISSUE TITLE
GT++ Thermal Boiler never outputs Pahoehoe Lava

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#12798]
### Your GTNH Discord Username

Abdiel Kavash#2431

### Your Pack Version

2.3.0-RC-2_(MMC)

### Your Server

Singleplayer

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Lava burning in a Thermal Boiler should output Pahoehoe Lava, in addition to other byproducts:

![](https://i.imgur.com/eUu52uW.png)

Pahoehoe Lava can then be further processed into other resources, generating a steady if slow stream if infinite lava is supplied to the Boiler.

### The Reality

Lava is consumed, all item outputs and steam are produced, but Pahoehoe lava is not produced.

### Your Proposal

The recipe is correctly defined here: https://github.com/GTNewHorizons/GTplusplus/blob/f9d022bbe6c2c2d30416731cbfa6a14526802fda/src/main/java/gtPlusPlus/core/recipe/RECIPES_GREGTECH.java#L1423

The Thermal Boiler code however only checks for solid outputs of the recipe, it never even looks at the fluid outputs when lava is the input: https://github.com/GTNewHorizons/GTplusplus/blob/f9d022bbe6c2c2d30416731cbfa6a14526802fda/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GT4Entity_ThermalBoiler.java#L103

Using Solar Salt properly checks and generates fluid outputs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by posiaden123** [comment]
am I correct in thinking that this is just an issue of making sure fluid outputs are checked if lava is the input?
