### ISSUE TITLE
Magic mods' recipes can not be encoded by importing recipe from NEI in AE2FC terminals.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#12795]
### Your GTNH Discord Username

Abdiel Kavash#2431

### Your Pack Version

2.3.0-RC-2_(MMC)

### Your Server

Singleplayer

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

To encode a recipe using any of the following systems:
- TC Crucible or Arcane Infusion,
- BM Blood Altar or alchemy,
- Botania Petal Apothecary, Pure Daisy, Mana infusion, Runic Altar, Elven Trade.
- Possibly other mods' recipe systems, these (particularly TC and BM) are the most commonly encountered.

Steps to reproduce:
Open an ME pattern terminal.
With the terminal open, look up a crafting recipe in NEI.
Click the [?] button to encode the recipe into a pattern.

### The Reality

In the ME Pattern Terminal and the ME Processing Pattern Terminal, the recipe is correctly encoded as expected. (Botania recipes have an additional issue where they include the crafting station as one of the ingredients, but the player can fix that simply by removing it from the recipe.)

In the AE2FC Fluid Pattern Terminal and the Fluid Processing Pattern Terminal, no items are moved into the recipe grid when the [?] button is clicked (or when shift-clicked). The only option to encode these recipes in AE2FC terminals is to add every input and output by hand.

[Video for demonstration](https://www.dropbox.com/s/qlbbsxlk46u6pv3/UtH5d7Ayc2.mp4?dl=0)

### Your Proposal

Consistent behavior between AE2 and AE2FC terminals.

Being able to use the same terminal to encode all recipes directly from NEI.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Bluedot55** [comment]
This bug has resurfaced again with infusion crafts in daily build 22. Attempting to pattern a thaumcraft infusion craft in a fluid  terminal will cause a fatal error, and a return to the main menu.
