### ISSUE TITLE
Multiblock tooltips errors and discrepancies (RC2)

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#12794]
### Your GTNH Discord Username

Abdiel Kavash#2431

### Your Pack Version

2.3.0-RC-2_(MMC)

### Your Proposal

Over the last few months, I have collected a variety of issues with different multiblock tooltips. Sometimes the tooltip does not list a requirement, sometimes it lists a requirement that is not actually needed, sometimes it is confusing about what can go where. Today I verified all of the issues I will list below in 2.3.0-RC-2 to make sure that they are still present in the current version, in hope that they can be fixed for the stable release, as correcting most of them would require only a small text change in the tooltip.

Generally I have accepted "multiblock forms correctly" as a sign that a setup is valid, I did not try actually running a recipe to see if it really works.

I also did not thoroughly test obviously unviable setups (like multis without an energy or input hatch); some multiblocks form like this, some don't; I think that enforcing strict consistency in such pathological cases would be unnecessary pedantry and not serve any purpose for the player.

However, I think that the player should be provided with a clear guidance on how to build a working version of a multiblock; or if sufficient guidance can not be provided due to space limitations of the tooltip, then at least not be given *incorrect* information through them.

Finally, I do not claim this list to be complete. These are only issues that I have either encountered in my survival playthrough or through creative derping. Thus the late-game multis or anything else that I have never used are not included.

&nbsp;

List below:

- [ ] Combustion Engine

The tooltip says that the muffler hatch must be in the top middle back. In reality, the muffler can replace any casing next to a gearbox (just like input or maintenance hatches).

I haven't tested the different engine variants, they might be in the same situation.

- [x] Lapotronic Supercapacitor

Tooltip lists the required amount of glass as 41-265. This was correct for the old maximum height (18 blocks), with the new maximum height of 50 blocks the amount of glass required for max size LSC is 777.

- [x] Oil Cracking Unit

The tooltip says that the middle ring hatch is for Steam/Hydrogen ONLY. In reality there are cracking recipes which use a different cracking fluid. That fluid still needs to go in the middle ring.

- [x] Distillation Tower

Tooltip says it requires 7 x h - 5 casings. In reality h should actually be the number of output layers, not the height of the entire structure. For example, a 3 block tall DT (one input layer, two output layers) forms with 9 casings.

Tooltip says that the energy hatch can replace any casing. In reality, the center of the top layer is not a valid position for an energy hatch. (Maintenance and output hatches work there.)

- [ ] Electric Air Filter

The tooltip says that the structure needs an additional muffler hatch in "middle center" [sic]. This is incorrect, no extra muffler other than the eight on the sides (already mentioned elsewhere in the tooltip) are required, and the multi will not form if you add a muffler in the center of either the top or the bottom layer.

This affects all three tiers of the EAF.

- [ ] Bacterial Vat

The multiblock only allows one (and requires exactly one) output hatch. The tooltip does not specify this anywhere, in the normal or shift-held variant.

- [x] Extreme Extermination Chamber

Tooltip states that all hatches can replace any casing. In reality hatches can only replace bottom layer casings, no hatches are allowed in the top layer.

Shift-clicking the controller with a hologram projector in creative mode places the spikes upside down. (The structure still forms though.) (Placing in survival mode works fine.)

- [x] Industrial Centrifuge

The tooltip says all hatches can replace any casing except the front. In reality, any hatch can replace any casing, the front is not restricted. It breaks up the fan texture, but the machine works normally.

- [x] Maceration Stack Controller

The tooltip says that energy and maintenance hatches must replace a bottom casing. In reality they can replace any casing. (Input has to be on the bottom, as per tooltip.)

- [x] Industrial Extrusion Machine

The tooltip says the muffler hatch must be in the back center. In reality it can replace any casing.

- [x] Industrial Mixing Machine

The tooltip specifies that two Titanium Turbine casings are the minimum. While this is technically true, it is slightly misleading: The multiblock requires *exactly* two turbine casings, there is nowhere to put more.

- [x] Zyngen

The tooltip says that the number of Integral Encasements and heating coils is a minimum (8 and 16 respectively). While this is technically true, both are also exact requirements, there is nowhere to place more.

- [x] Industrial Coke Oven

The tooltip says that hatches can replace any casing. This should specify "Any Structural Coke Oven Casing", as heat resistant/proof casings are not valid for hatches, even though they are still "casings".

- [x] Boldarnator

The tooltip says that the minimum number of Thermal Containment Casings is 16, and that hatches can replace any casing. While this technically gives the correct description, I think it would be more clear to the player if the number of Thermal Containment Casings was given as an exact required amount, and hatches were described as only replacing Thermal Processing Casings.

- [x] Dangote Distillus

The tooltip says that energy and maintenance hatches must replace a bottom casing. In reality they can replace any casing.

The tooltip says that the muffler hatch must be in the top casing. This is true only in a very technical sense. The Dangote looks for the muffler hatch, and whatever layer it finds that in, it considers that to be the top. For example, if you build a Dangote with four output layers, and place the muffler in line with the second output layer, the Dangote will only output the first two fluids because it does not consider the upper two layers a part of its structure.

The Dangote can also form and run with a hole (missing casing) in the middle of the top layer. This is likely a bug in the structure definition and not something that we should encourage players to do by telling them about it.

- [x] Cleanroom

Left this one for last as the tooltip is *very* out of sync with reality.

- The basic tooltip (without holding shift) says "Make sure your Energy Hatch matches! ?" [sic]. I'm not entirely sure what this line is even trying to say, there are no restrictions on the tier of the energy hatch in a CR.

- "5% of Plascrete can be replaced with Reinforced Glass" -- The reality is that the number of RG blocks can be up to 5% of the number of plascrete blocks, *not counting the plascrete blocks in the top layer*. With small CRs this can be a big difference.

- This is much more relevant for other types of glass which have much higher allowed percentages. For example, Borosilicate Glass, which has a limit of 50%, needs a ratio of 2:1 plascrete/glass, not 1:1, as the description "50% of Plascrete can be replaced by..." would suggest. Borosilicate Glass (any type or color other than the basic one) has a limit of 100% -- this does not mean that the CR can be *entirely* glass, just that the number of plascrete blocks and glass blocks can be equal.

- While not exactly a bug, since the tooltip *does* mention possible alternate glass in the config; I think it is a little disingenuous to hide the details from the player. The allowed number of the other glass types is *much* higher than reinforced glass, allowing for cheaper and more transparent cleanrooms. In my opinion the tooltip should at least mention Borosilicate glass.

- The tooltip says that energy and maintenance hatches can replace any casing. They are not valid in the top layer at all (even on the edges), and will not work as expected when replacing the southeast vertical edge (positive x, positive z) since the cleanroom uses plascrete blocks in that edge to determine its height.

- The tooltip specifies "1x Reinforced Door". This is neither required nor the maximum. A cleanroom forms with anywhere from 0 to 2 doors. (Technically four door blocks, if they are protruding through the bottom layer of the CR in some cursed setup.) "Up to 2 Reinforced Doors" would be much more accurate.

- The tooltip also does not mention Elevators, Rotating Elevators, and Travel Anchors, which are also valid blocks in the structure (up to 1 each).

### Your Goal

Clearer tooltips, fewer issues building multiblocks. OCD satisfied.

### Your Vision

* In cases where the tooltip is more restrictive than what the game actually allows, correct the tooltip to match reality. (Probably a simple textual change in most cases that could make it into the stable release?)

* In cases where the tooltip seems to allow for more varied placement than is actually possible in reality (e.g. the EEC), considering modifying the structure logic to actually allow placing of hatches in all places the tooltip says, to allow for more flexibility of setups.

* In cases where the in-game valid placement is actually unintended (likely the Dangote muffler, maybe some others?), fix the structure logic and correct the tooltip to be consistent with it. (This might break existing working setups.)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
some of these sound more like mistakes where made when converting things to structurelib (like the DT one). I guess we can fix them in either direction though. thanks for the nice list!
