### ISSUE TITLE
Add lava as underground fluid in the Nether.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#12808]
### Your GTNH Discord Username

Abdiel Kavash#2431

### Your Pack Version

2.2.0.0

### Your Proposal

The Nether currently has no underground fluids that can be pumped by multiblock pumps. My proposal is simple: add Lava as a valid underground fluid.

### Your Goal

Currently, unlimited sources of lava are either gated behind magic progression (Everburn Urns, BM rituals) or T3 rocket (pumping from Ross128b). The player has access to *effectively* infinite lava by pumping it from the nether with singleblock pumps, but that causes significant lag due to block updates. So adding it as an underground fluid will not have any balance impact, but it can save server TPS.

### Your Vision

Early-ish game available infinite lava source without destroying TPS.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
that certainly has a balance impact despite what you are saying. multiblock pumps are a lot better than having to move single block ones around over lava lakes.
