### ISSUE TITLE
Backspace button not working in Logistics Pipes Request Table/Security Station

### ISSUE THREAD

**Issue by wagon153** [GTNewHorizons/GT-New-Horizons-Modpack#12804]
### Your GTNH Discord Username

Wagon(Wagon153)

### Your Pack Version

2.3.0RC2

### Your Server

Private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I was trying to delete text I accidentally input into the logistics request table

### The Reality

 However, pressing the backspace button on my keyboard did nothing. To erase what was input already I had to exit out of and reopen the Request table UI. I was also able to replicate this in a single player world, and it seems to occur in Logistics Security Stations as well. I couldn't see anything in my logs either serverside or client side relating to the issue. 

### Your Proposal

Can't say I know enough to propose a solution. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wagon153** [comment]
Backspace function works fine in other UIs looks like, such as the questbook.

**Comment by Glease** [comment]
Cannot reproduce on a fresh install of 2.3.0 RC3. Maybe check if you have a bad keybind set?

**Comment by miozune** [comment]
I can repro with Java17 runClient
