### ISSUE TITLE
Crash Relating to EC2 Fluid Import/Export Bus

### ISSUE THREAD

**Issue by kstvr32** [GTNewHorizons/GT-New-Horizons-Modpack#12803]
### Your GTNH Discord Username

neoprop#4986

### Your Pack Version

2.3.0-RC2

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

I loaded my world from 2.2.3 on the new RC. No actions were taken. The world has many EC2 import/export buses. I tried to replace them with their new AE2FC counterparts, but crash before I am able to do so.

I saw that EC2 fluid storage busses were automatically replaced with AE2FC fluid storage busses, would it be possible to do this with import/export busses as well?

### Crash Report

[crashlog.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10892685/crashlog.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by firenoo** [comment]
Regarding autoconversion, should  be addressed by https://github.com/GTNewHorizons/ExtraCells2/pull/81 in the next dev version.

**Comment by Dream-Master** [comment]
@kstvr32 update to 2.3.0 and add replace your ec2 file with this one https://github.com/GTNewHorizons/ExtraCells2/releases/download/2.5.33/ExtraCells-2.5.33.jar
