### ISSUE TITLE
Hydroxide violates chem standardization and related chem errors

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12816]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.2.10

### Your Server

sp

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

every recipe should follow chem standardization.

### The Reality

1. Hydroxide recipe doesnt follow chem rules:

![image](https://user-images.githubusercontent.com/40274384/223247702-9eb0832f-4692-44cd-a3ec-f0fb4acb4aea.png)

2. Beryllium Hydroxide has an incorrect formula:

![image](https://user-images.githubusercontent.com/40274384/223248347-c1fe928c-655c-4db7-98e9-13afb55da9ab.png)

3. beryllium Hydroxide recipe  doesnt follow chem rules:
![image](https://user-images.githubusercontent.com/40274384/223248479-4dd9a96e-7e66-48bf-8589-e045031cff65.png)

### Your Proposal

1. it should produce just 1000L
2. It should be Be(OH)2, the dust too.
3. should be 1Be + 2000L OH -> 1000L Be(OH)2 (or is this considere a molten dust? then it might be different)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
The whole usage of hydroxide as a separate "chemical" is wrong. One does not use "hydroxide" as a reactive, but a base (sodium hydroxide, potassium hydroxide, whatever). A reasonable way to obtain beryllium hydroxide would be reacting any of its dissolvable salts (e.g. chloride) with diluted sodium hydroxide. In terms of the "gameplay over realism" philosophy, I would suggest redoing this line into the following steps:
1. React beryllium with either chlorine gas or HCl in a chem reactor to get beryllium chloride. 
2. React the obtained beryllium chloride with sodium hydroxide and water to get beryllium hydroxide and salt water.
Not exactly a beryllium chemistry enthusiast, I got this from different internet sources, but it seems to align with general concepts one learns at school.

**Comment by chochem** [comment]
I don't really care about chemistry. just our game mechanics. So 1) is the important one for me.

**Comment by Pxx500** [comment]
If it's possible hydroxide as a reagent should be deleted too and everything using it made into a reasonable recipe that makes at least some chemical sense. Things should not be done this way because you might as well shove beryllium, oxygen and hydrogen into a chemical reactor to get what you want, no fun in that.

**Comment by chochem** [comment]
its mostly used for scanners directly, the beryllium stuff is more niche. And again, I dont care.

**Comment by chochem** [comment]
made a fix for the hydroxide. The only part I care about here. If you guys care so much about the beryllium stuff you can make a separate ticket I guess
