### ISSUE TITLE
Garnierite cannot be quadruple with IC2 Crop

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#12813]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.0-RC-1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

![image](https://user-images.githubusercontent.com/105285781/223199637-7afea74f-75d8-4689-8757-2b3abbbf39b4.png)
this one should be roasted nickel
![image](https://user-images.githubusercontent.com/105285781/223199723-8476c23d-46ce-480f-b9b9-0e4a1d79dae2.png)

### The Reality

Garnierite ore cannot be quadrupled

### Your Proposal

Unify the name of roasted nickel and garnierite

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
dont make multiple tickets about the same thing please
