### ISSUE TITLE
2.3.0-RC3 is not converting Fluid Level Emitters to ae2fc

### ISSUE THREAD

**Issue by Qwasyx** [GTNewHorizons/GT-New-Horizons-Modpack#12815]
### Your GTNH Discord Username

Qwasyx#3000

### Your Pack Version

2.3.0-RC3

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

On updating from 2.2.10 to 2.3.0-RC3 the game is supposed to automatically change all fluid related EC2 blocks to AE2FC blocks.

### The Reality

Most things get converted, but Fluid Level Emitters are not converted.

### Your Proposal

Fluid Level Emitters should also be converted.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
Should be fixed by https://github.com/GTNewHorizons/ExtraCells2/pull/81 in the next dev version

**Comment by Dream-Master** [comment]
@Qwasyx update to 2.3.0 and replace your ec2 version with this
https://github.com/GTNewHorizons/ExtraCells2/releases/download/2.5.33/ExtraCells-2.5.33.jar
