### ISSUE TITLE
Add a method to transfer fluids/items to personal dimension, one way

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#12812]
### Your GTNH Discord Username

querns#3785

### Your Pack Version

2.3.0-RC3

### Your Proposal

Allow the personal dimension portal to transport fluid and items from the entrance portal to the exit portal inside the personal dimension.

### Your Goal

The personal dimension block is granted as a quest reward in HV. However, it can be infeasible to actually use one's personal dimension at this time -- cross-dimensional fluid and item transport from other mods is largely unavailable, and power systems reliant on the overworld (particularly, oil-based power) cannot be moved to the personal dimension without manual ferrying of oil or refined fuel.

### Your Vision

Allowing items and fluids to enter the personal dimension will help make the transition from overworld to personal dimension easier. 

The portal itself could be the target of incoming fluid or items, or there could be an additional block that facilitates the transfer, placed adjacent to the portal (allowing it to properly target the correct dimension for transport.)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
you make it sound like its in the middle of HV, its no. Its after the moon dungeon, so you are starting EV when you move. Quantum links should be available immediately (though expensive!). And EIO dimensional transceiver is only like half an age away.
