### ISSUE TITLE
ME (Fluid) Export Bus strange behaviour with Crafting Card

### ISSUE THREAD

**Issue by paulzzh** [GTNewHorizons/GT-New-Horizons-Modpack#12820]
### Your GTNH Discord Username

Paulzzh#9036

### Your Pack Version

2.2.10

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

I have a huge ME storage system with lots of ME (Fluid) Export Bus.
My TPS is very low and I found that ME (Fluid) Export Bus takes up 20% of the tick time.
It looks like it's crafting things.But my Crafting Processing Units are idle.
[20230307-034303.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10904103/20230307-034303.zip)
![image](https://user-images.githubusercontent.com/28055560/223286614-f1ea75e3-e008-4ff3-b90c-a49f07e46489.png)

### The Reality

I write some mixins to find out all the export bus.
https://gist.github.com/paulzzh/b2b05277304fe6d3b7b51924dc6c5d18
![XR {Q@J}WN}1M(2`0N8K45F](https://user-images.githubusercontent.com/28055560/223289786-b1724694-b665-4e2d-8c86-96047786ccf9.png)

**And I'm surprised why the container is full, but it is still trying to output and craft**
![CIZP1PBZD`05Y_A6Q`D A1Q](https://user-images.githubusercontent.com/28055560/223290551-fb447714-da00-463e-be16-6bcc12da7c85.png)
![NHFJ8C8E5 6$EZN2J)Z3 AG](https://user-images.githubusercontent.com/28055560/223290563-390c4321-64e9-4a6f-bf3d-fe3cfdfe2db4.png)

### Your Proposal

"Use stocked items, or craft items while exporting."
Don't run crafting simulation if the container is full. Or make it multithreaded.
Use stocked items first and don't run the crafting simulation.
Fix the lag.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by asdflj** [comment]
fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/commit/18f31ac3ef836d1cfe076beb887a59e37c6b38b3

**Comment by asdflj** [comment]
u need upgrade ae2fc

**Comment by asdflj** [comment]
try to upgrade ae2fc

**Comment by asdflj** [comment]
it's fixed

**Comment by paulzzh** [comment]
Latest ae2(rv3-beta-173) and ae2fc(1.0.91)
can reproduce in singleplayer
The export bus has a Crafting Card on CraftEither mode.
![image](https://user-images.githubusercontent.com/28055560/223440972-0aed2e76-1d47-4287-b662-4fef8034bae8.png)
![image](https://user-images.githubusercontent.com/28055560/223441022-1cc61303-a2fb-49dc-8ba1-0f76ce52c430.png)
![image](https://user-images.githubusercontent.com/28055560/223441182-536c0518-7889-4691-9091-844fa451b891.png)
We have enough stock, but it is still trying to output and craft.
https://gist.github.com/paulzzh/b2b05277304fe6d3b7b51924dc6c5d18

**Comment by MarchingCube** [comment]
Also from my testing it seems that if crafting craft requests a craft and that craft produces more than fits in the tank it will just void the rest.

**Comment by asdflj** [comment]
not bug,not need fix

**Comment by asdflj** [comment]
u mixin is incorrect

**Comment by asdflj** [comment]
u need mixin `appeng.me.cache.CraftingGridCache#submitJob`

**Comment by paulzzh** [comment]
> u mixin is incorrect
But these export bus are calling `appeng.helpers.MultiCraftingTracker.handleCrafting` and cause lag.
After I removed all the crafting cards,  tps 13->17. And they no longer call `handleCrafting`.
I think this is an AE2 bug.
