### ISSUE TITLE
Skookum Choocher Wrench mode doesnt return you the machine when breaking

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#12825]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.0-RC-1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

When I wrench with Skookum Choocher, it should give me back the circuit assembler

### The Reality

It gives me electrum dust back
![image](https://user-images.githubusercontent.com/105285781/223503585-7d24d2d3-1aa9-4cdd-80f3-dc734ac126ba.png)
![image](https://user-images.githubusercontent.com/105285781/223503609-c751a782-74d0-4da7-9dfe-ef1a0de56d08.png)

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
It's removed now https://github.com/GTNewHorizons/GTplusplus/pull/729
