### ISSUE TITLE
EC2 Fluid Storage Buses do not convert correctly to AE2FC

### ISSUE THREAD

**Issue by firenoo** [GTNewHorizons/GT-New-Horizons-Modpack#12823]
### Your Pack Version

2.3.0 RC-3

### Your Server

n/a

### Java Version

Java 8

### Type of Server

None

### Your Expectation

EC2 fluid storage buses convert correctly to their AE2FC counterpart (barring the need to insert capacity cards); all fluid slots transfer to the corresponding slot in AE2FC.

### The Reality

Before:

![image](https://user-images.githubusercontent.com/49818773/223318521-d8ca47a1-fdf7-465b-93b8-ab8bcb944bda.png)

After:
![image](https://user-images.githubusercontent.com/49818773/223320090-b9011e64-64f5-42f0-8057-d4fcdf929882.png)

Notice the missing inverter card and setting reset.

### Your Proposal

Keeping this on the tracker to raise awareness. Will fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SHIBUYAENNI** [comment]
The bad thing is that the memory card cannot copy any of the tags in the EC2 fluid storage bus 😔
