### ISSUE TITLE
ME autocrafting losing items

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12827]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Ever since we updated from 2.2.8 to 2.2.10 we regularly have to re-order something because ME will randomly state that something is crafting while what should be crafting is not present in the machine it should be in despite the pattern having the right recipe.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
retry on RC3, chochem already told you we fixed tons of stuff in AE2 since 2.2.10
