### ISSUE TITLE
"Shrimp Pork Okra Hushpuppies" do not contain pork

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#12837]
### Your GTNH Discord Username

hallucinogender#1408

### Your Pack Version

2.3.0 RC2

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Shrimp Pork Okra Hushpuppies (food item from Pam's Harvestcraft) should contain shrimp, pork, and okra in the recipe.

### The Reality

The item's recipe contains shrimp and okra as expected, but does not contain any pork. Tofu can be substituted for an egg in the recipe, but there is no option to include any pork despite the implication of pork in the item's name.

### Your Proposal

Add the option of either pork or a suitable tofu (oredictionary "listAllporkraw") to the "Shrimp Pork Okra Hushpuppies" recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lesdmark** [comment]
They don't contain pork in real life either. Not sure why they were called that even.

**Comment by hallucinogender** [comment]
That's odd. That's very odd. I also looked up the default recipe for them, and it also has no pork. Perhaps what's needed here is a name change to "shrimp and okra hushpuppies".

**Comment by BritishCynic** [comment]
Shrimp Pork Okra Hushpuppies in real life do not have pork either.

**Comment by lesdmark** [comment]
I did find a real life shrimp and okra recipe, but as I am someone who was born and raised in the American south, I had only ever heard of the plain ones until I hunted for alternate recipes

**Comment by hallucinogender** [comment]
> I suppose they could be renamed to just "Hush Puppies"?

There are already ordinary "hush puppies" in Harvestcraft. The shrimp and okra ones are a separate kind.
