### ISSUE TITLE
Protective Gloves for hot fluids not working

### ISSUE THREAD

**Issue by Marvun** [GTNewHorizons/GT-New-Horizons-Modpack#12833]
### Your GTNH Discord Username

IchHeißeMarvin#3647

### Your Pack Version

2.3.0-RC-3

### Your Server

SP

### Java Version

Java 19

### Type of Server

None

### Your Expectation

The protective gloves prevent damage when having hot fluids/ingots in the active slot.

### The Reality

In my current single player world the gloves do not have any effect when wearing them. I also tried both ways of wearing them even though i know only one way is correct. Here is a video of me showing the problem: https://youtu.be/-3BxizanfOk

The thing is in a new single player world, the problem does not occur.

Another thing i noticed was, that in my orginial sp world it felt like my gloves went missing, because i always have them equipped and they had a lot of durability left when all of the sudden they were gone. That is why i made new one, but they do not work anymore. They also do not lose durability.

### Your Proposal

Tell me what could be the cause and how i could possibly fix that. Or tell me a workaround if the world is just brickd now.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
yea the glows are reworked some time before, and you can't carry 10 buckets of lave and hold one in hand like before. But you can fill your tico tank with lava and hold it in your hand, or put buckets in the bag pack.

**Comment by Dream-Master** [comment]
Put the glows in the right slot works for me, so you did something wrong or have a second lava bucket in your inventory ?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/223711749-e26a470f-6fd3-4a0c-bc08-3904bf28150b.png)

**Comment by Marvun** [comment]
Hi, did you watch the video that i linked? In the video you can see, that i don't have anything else in my inventory, that could cause damage and i even tried both ways of equipping them.
I also said that it works in another sp world, so it isn't necessarily caused by RC3.

**Comment by Marvun** [comment]
Okay i found out why it was broken for me.
Since i gave myself the gloves via the /give command, the gloves where missing the the "durability" tag. I saw that when i opened the .baub file in the NBTExplorer. After adding in manually, the gloves work perfectly fine.

So in conclusion, if you give yourself the gloves via /give command, don't forget to specify the durability tag, otherwise the gloves won't work. ^^

The problem is solved and can be closed, but thank you for your time anyways. :)
