### ISSUE TITLE
milling related errors in gregtech log

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12839]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.3.0 RC3

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

no such errors

### The Reality

[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10925558/GregTech.log)

seems to be related to gt++ milling.

I have no idea either way if this has an actual in game impact or not.

### Your Proposal

fix whatever is broken. )

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Appears to be another EnumHelper issue.

**Comment by Glease** [comment]
This looks a bit concerning. it appears javac might use very convoluted ways to implement huge enum switch case block, and that is beyond the capability of any EnumHelper whatsoever. IMO maybe we should just eliminate this EnumHelper usage.

**Comment by Glease** [comment]
OrePrefixes are used in switch case a lot and this prevents it from being a valid EnumHelper target. Under the hood for huge enum switch cases, javac will generate a synthetic class with a synthetic static final int[] field to hold switch map. If the OrePrefixes is ever extended, said switch map will be smaller than actual and cause ArrayIndexOutOfBoundException.

For an example, look at GT_Proxy$1

**Comment by miozune** [comment]
I think we can just add `MILLED` prefix to GT. No need to spread prefix as well as material across addons.

**Comment by Glease** [comment]
BW also got 3... Currently in progress of moving them all to gt5
