### ISSUE TITLE
Fatal error and termination of connection after opening a GUI of a GT cover right after placing one

### ISSUE THREAD

**Issue by Srdra2k3** [GTNewHorizons/GT-New-Horizons-Modpack#12838]
### Your GTNH Discord Username

Srdra#7777

### Your Pack Version

2.3.0 RC3

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

Placed an input bus and put an HV conveyor module on the bus. 
I opened the conveyor GUI by shift right clicking as soon as i placed the belt. 
I was met with a blank GUI screen and then a fatal error screen soon after.

The same issue also happens with machine controller covers placed on LCRs.

I have optifine, FTBL and FTBU added to the modpack as extras.

### Crash Report

Log uploaded directly from prism:
https://mclo.gs/kx6cww7

fml-client-latest:
https://mclo.gs/I3BZwtJ

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
can confirm. also get disconnected if I do it fast:

[muidisconnect.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10925613/muidisconnect.txt)
