### ISSUE TITLE
Potential ghost chunkloading

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12835]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

While looking for performance issues i installed Foamfix which correctly diagnosed a lot of ghost chunkloading cases (constant loading and unloading of chunks by for example pipes entering an unloaded chunk or some sort of block updates crossing the chunk border) in other packs already and came across various potentially unwanted cases of it, including an unpatched vanilla one:
`
[2023-03-08 15:52:06] Block in chunk [37, 56] may be ghostloaded!
 net.minecraft.world.World.func_72964_e(World.java:419)
 net.minecraft.world.World.func_147439_a(World.java:345)
 gregtech.api.util.GT_Utility.isOpaqueBlock(GT_Utility.java:2358)
 gregtech.common.blocks.GT_TileEntity_Ores.func_145844_m(GT_TileEntity_Ores.java:163)
 net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:540)
 net.minecraft.entity.player.EntityPlayerMP.localOnUpdate(EntityPlayerMP.java:276)
 api.player.server.ServerPlayerAPI.onUpdate(ServerPlayerAPI.java:6101)
 net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java)
 net.minecraft.world.World.func_72866_a(World.java:2070)
 net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
 net.minecraft.world.World.func_72870_g(World.java:2034)
 net.minecraft.world.World.func_72939_s(World.java:1887)
 net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
 `

`
[2023-03-08 15:52:08] Block in chunk [40, 66] may be ghostloaded!
 net.minecraft.world.World.func_72964_e(World.java:419)
 net.minecraft.world.World.func_147439_a(World.java:345)
 net.minecraft.world.World.func_72879_k(World.java:3361)
 net.minecraft.world.World.func_94577_B(World.java:3391)
 net.minecraft.world.World.func_72878_l(World.java:3424)
 net.minecraft.world.World.func_72864_z(World.java:3429)
 thaumcraft.common.tiles.TileNode.checkLock(TileNode.java:950)
 thaumcraft.common.tiles.TileNode.func_145845_h(TileNode.java:115)
 makeo.gadomancy.common.blocks.tiles.TileExtendedNode.func_145845_h(TileExtendedNode.java:54)
 net.minecraft.world.World.func_72939_s(World.java:1939)
 net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
 `

`
[2023-03-08 15:52:08] Block in chunk [-13, -48] may be ghostloaded!
 net.minecraft.world.World.func_72964_e(World.java:419)
 net.minecraft.world.World.func_147439_a(World.java:345)
 net.minecraft.block.BlockFire.getChanceToEncourageFire(BlockFire.java:516)
 net.minecraft.block.BlockFire.func_149845_m(BlockFire.java:268)
 net.minecraft.block.BlockFire.func_149674_a(BlockFire.java:169)
 net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:550)
 net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:181)
 `

`
[2023-03-08 15:52:09] Block in chunk [36, 47] may be ghostloaded!
 net.minecraft.world.World.func_72964_e(World.java:419)
 net.minecraft.world.World.func_147438_o(World.java:2536)
 thaumcraft.common.tiles.TileInfusionMatrix.getSurroundings(TileInfusionMatrix.java:637)
 thaumcraft.common.tiles.TileInfusionMatrix.func_145845_h(TileInfusionMatrix.java:210)
 net.minecraft.world.World.func_72939_s(World.java:1939)
 net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1146)
 `

Whole log from less than 3 minutes of this logging being enabled:
[ghost.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10921882/ghost.txt)

### Your Proposal

Do not trigger loading of nearby unloaded chunks where not needed as this can severely degrade performance and in very rare cases even result in a chunk being loaded twice, resulting in very odd behavior or crashes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
@Tommeh1 it's the 3rd time we tell you to test on latest dev. Reporting bugs is cool, but reporting bugs on a outdated dev release is not.

**Comment by Tommeh1** [comment]
> @Tommeh1 it's the 3rd time we tell you to test on latest dev. Reporting bugs is cool, but reporting bugs on a outdated dev release is not.

None of this has been reported before, making it very unlikely that someone patched it, but i'll make sure to run this again in 2.3.0

**Comment by boubou19** [comment]
most of those are just getBlocks, and that is known tho
