### ISSUE TITLE
Quest book massively drops frame

### ISSUE THREAD

**Issue by TaterBlight** [GTNewHorizons/GT-New-Horizons-Modpack#12840]
### Your GTNH Discord Username

TaterBlight#8888

### Your Pack Version

2.3.0 RC3

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Open the quest book, read through it with stable frames per second.

### The Reality

Quest book is opened, frames drop massively and in the hundreds. (Before and after, respectively.)
![image](https://user-images.githubusercontent.com/113026604/223904441-e63162b6-36df-41b4-9bd0-13ac94041283.png)
![image](https://user-images.githubusercontent.com/113026604/223904461-26ab073e-ef77-4bde-bb10-5a172c367cce.png)

### Your Proposal

Opening the quest book, no matter where, tanks frames to humorous levels.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TaterBlight** [comment]
I forgot to clarify: I was using OptiFine 1.7.10 HD U E7 at the time of writing this. I will try reproducing this without it now.

**Comment by TaterBlight** [comment]
I accidentally closed this, but the issue happens even without OptiFine. Sorry about that.

**Comment by boubou19** [comment]
if this is true this is concerning. Why would a BQ them impacts fps?

**Comment by chochem** [comment]
I have not had the time to test this. just remember someone mentioning it.
