### ISSUE TITLE
Mark of the Falling Tower as a substitute for some rockets.

### ISSUE THREAD

**Issue by BestMod** [GTNewHorizons/GT-New-Horizons-Modpack#12847]
### Your GTNH Discord Username

beanie#0735

### Your Pack Version

2.3.0-RC2

### Your Proposal

For the meteor ritual that brings Mars cobble and its moons' subsurface rocks, you (whoever devs BM) should make it to where it brings all 9 rocks that are required for the quests instead, as an alternative to actually going to Mars and its moons. It's balanced because unlocking Mark of the Falling Tower is far more difficult and time consuming than actually going to Mars, so it wouldn't be an easy alternative. More of a byproduct and reward for actually getting the ritual set up. This could also be applied to higher tier planets up to some sort of limit, like tier 3-4 or whatever

### Your Goal

It wouldn't be super OP, but it would reward players who spent the days needed to get Mark of the Falling Tower if they did it before launching to xyz planet.

### Your Vision

It would help connect magic and tech more than it is already, making the pack feel more cohesive.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
skips are based on the main materials, not some silly rocks

**Comment by BestMod** [comment]
![image](https://user-images.githubusercontent.com/71246119/224467506-78930265-66bc-4957-a79c-496537c13ef2.png)
the ritual in question:

**Comment by chochem** [comment]
yea that was not question. still no imo.
