### ISSUE TITLE
Allowing AE to type k m g unit

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#12857]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.0-RC-1

### Your Proposal

In AE2, let the system able to type 2M instead of typing 2 000 000, it will be better for fluid crafting and requesting a large amount
![image](https://user-images.githubusercontent.com/105285781/224475545-dee2a7b9-26a2-4851-a158-a21e772088d9.png)

### Your Goal

QoL

### Your Vision

QoL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by StaffiX** [comment]
This would be a great quality of life feature for mid/lategame.

**Comment by StaffiX** [comment]
Was added by [ModularUI#58](https://github.com/GTNewHorizons/ModularUI/pull/58)
