### ISSUE TITLE
Negative ingredients in recipe

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#12851]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.3.0-RC-4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Try to craft/encode a Munchdew recipe 

### The Reality

It needs negative ingredients 
![image](https://user-images.githubusercontent.com/45178400/224416725-e9920127-00e4-463e-9854-5b61da0646ec.png)

### Your Proposal

Fix it or make that ae2 recognize negative ingredients as possitive ones, so if there is another negative ingredient recipe it will be fixed ;3

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by EnderProyects** [comment]
This was two issues in one, the negative number and then that it asks 4 vines instead of 1, so the last is not corrected

**Comment by miozune** [comment]
I have made items with < 1 stack size to be corrected to 1, so both issues are resolved

**Comment by EnderProyects** [comment]
So, similar issue in the 2.6.1 with the loonium
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/a5de766c-bffd-4984-aab8-a2121b596739)
