### ISSUE TITLE
Curse file downloader is a bit annoying

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#12858]
Two major issues i noticed when testing curse archive:

- if it errors out, despite the message saying to go read the logs, you won't see it until you press on the ok button
- it errors out at the first broken link, which is annoying because during testing you may have multiple broken links, so it would be nice if it errors out at the end pointing out in the logs which links are broken.

**Comment by Dream-Master** [comment]
to prevent this we need to upload much more mods to curse
