### ISSUE TITLE
Uphill step assist no longer works for all items that should provide it

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#12859]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Darksteel boot can auto walk up a block

### The Reality

It cannot even i turn on step assist with this dark boot
![image](https://user-images.githubusercontent.com/105285781/224484159-fbfb294a-7f20-4049-8cc4-abdda3868e51.png)

### Your Proposal

Make it walk one block automatically like walking on slab

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
if you hold shift like it tells you then you see that jump 3 apparently adds that already

**Comment by chochem** [comment]
somebody else explained it on discord: apparently the keybind is broken

**Comment by SHIBUYAENNI** [comment]
Maybe it needs the ability of traveler boots, but too many boots have that ability.

**Comment by Miruzuki** [comment]
> Maybe it needs the ability of traveler boots, but too many boots have that ability.

Looks like step assist in Traveller's Boots is also broken in 2.3.0

**Comment by Dream-Master** [comment]
i remember there where some changes before. Who break it?

**Comment by HikerL** [comment]
The same function of Draconic Boots is also broken

**Comment by chochem** [comment]
the EMT step assist works (sadly, I dont like it)

**Comment by dragagon** [comment]
> somebody else explained it on discord: apparently the keybind is broken. well if I understand it correctly.

I was the one who said something in discord, and even after setting the keybind and turning it on/off, step assist still does not work on dark boots. Incluing on 2.3.1.

I even made a fresh set to make sure it wasn't something with pre-existing dark boots. Still no step assist.

**Comment by Pilzinsel64** [comment]
> Looks like step assist in Traveller's Boots is also broken in 2.3.0

As what I can tell is that for us the hight step feature of the Traveller's boots are working fine.
We're using a some GTNH-forked mods on our own private server. At the moment we are using the mod versions from GTNH v2.3.0


> i remember there where some changes before. Who break it?

As the Traveller's Boots do work for us, I can't even tell what mod does break it or what mod you need to install to break it.

If we know the mod, we can go throw the changes between 2.3.0 and 2.2.? and check each single build. Might be a simple way to test around, maybe someone has the time to do this.

What I could do is going throw the commits of Ender Io tomorrow and check if I can detect any possible changes that could cause this, if you want. Also I could test the Ender IO Boots on our Test server tomorrow and check if they are working too for us.

**Comment by Pilzinsel64** [comment]
Yes, they work for us. Currently we are using that one from GTNH v2.3.0, not remembering yet what build number it has.
If you want I can also update TC to its latest build and check this, maybe I messed up something while the last update.

**Comment by dragagon** [comment]
I was on the 2.3.0 stable release for MMC for Java 8 in the announcements
section of the gtnh discord when the boots stopped working. Previously I
had been on 2.2.8 around Christmas. Since I use MMC, I could snag .9 and
.10 as well as the release candidates with my save and see when it broke.

**Comment by chochem** [comment]
yea I just tested on 2.3.0 and its broken there for me too. It would be strange if witchery breaks it but I guess I can try removing it. I bet its something different though

**Comment by Pilzinsel64** [comment]
Probably witchery has other depencies that we also don't use.
This is the full up-to-date mod pack that is installed on our server and our clients:
https://cloud.pilzinsel64.de/s/FL6tXr8XSNK6LKD

**Comment by chochem** [comment]
oh this like completely different. thought it was a slightly adjusted GTNH. well that doesn't narrow it down much then.

**Comment by FindMeSomeFun** [comment]
I have did some testing and here are the results:
				2.3.0	RC4	RC3	RC2	RC1		2.2.10
Piston boots		+		+	+	+	+		+
Boots of travel		+		+	+	+	+		+
Traveller's boots	-		-	-	+	+		+
Dark armor Boots	-		-	-	+	+		+

**Comment by chochem** [comment]
RC3 -> RC4 changelog:
https://github.com/GTNewHorizons/DreamAssemblerXXL/blob/master/releases/changelogs/changelog%20from%202.3.0-RC-3%20to%202.3.0-RC-4.md

**Comment by Pilzinsel64** [comment]
@FindMeSomeFun Ah, good job! :)

What you could test now (if you want and have the time is start with RC3 and update mod-by-mod (that is listed on the changelog one comment above) to the RC4 version and test again after each single mod.

As RC3->RC4 has no Tinker and Ender IO update, I only can assume what mod it could be, regarding the PR/commit message.
You could start with `LogisticsPipes` or `bartworks`, but without a good reason. Simply try each one from top to bottom.

**Comment by chochem** [comment]
yea I dont see anything obvious in that changelog. maybe the hovermode changes? even that isnt really related.

**Comment by FindMeSomeFun** [comment]
Well we need RC2 to RC3 not RC3 to RC4.

**Comment by FindMeSomeFun** [comment]
For me it is:
![rc2-3](https://user-images.githubusercontent.com/129369873/228825557-3854ea92-5515-4ba4-b6bc-c3da24b361c9.png)

**Comment by chochem** [comment]
guess that table does not format consistently. anyway:
https://github.com/GTNewHorizons/DreamAssemblerXXL/blob/master/releases/changelogs/changelog%20from%202.3.0-RC-2%20to%202.3.0-RC-3.md

**Comment by Pilzinsel64** [comment]
Probably this line:
https://github.com/GTNewHorizons/AdventureBackpack2/pull/12/files#diff-7369cdc8113818292e8b3604f7a7bb562821eef6889ee2804926f3db64877414L25

My suggestion is to either add that line back as ...
```
if (ConfigHandler.pistonBootsAutoStep) player.stepHeight = 1.001F;
else (itemStack == /* are that the boots this mod??? */) player.stepHeight = 0.501F
```
... or to adjust Ender IO and TC boots. But that's something someone else has to decide. xP

**Comment by chochem** [comment]
should be solved locally ideally. too many other places with step assist and at least one of the other options that is affected is ARR (Witchery)
