### ISSUE TITLE
Tesla Electric Tate Effects FPS Modification Suggestions

### ISSUE THREAD

**Issue by CrJolin0783** [GTNewHorizons/GT-New-Horizons-Modpack#12854]
### Your Pack Version

2.2.9.7

### Your Proposal

The Tesla Electric Tower will radiate an animation with GIF when charging the machine wirelessly (it should be), which will cause a slightly smaller/significant FPS reduction
I hope to modify this mechanism to set the charging special effects for him to open/close the style or make a separate glasses that can see Tesla animation or other items

### Your Goal

/

### Your Vision

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by SHIBUYAENNI** [comment]
# Set true to enable the cool visual effect when tesla tower running. [default: true]
    B:EnableTeslaVisualEffect=false

**Comment by SHIBUYAENNI** [comment]
Change it to FALSE in CFG

**Comment by Dream-Master** [comment]
@SHIBUYAENNI @CrJolin0783 is this false by default ? maybe because of lag?

**Comment by SHIBUYAENNI** [comment]
@Dream-Master the default is true, I think it should be changed to False 🙂
