### ISSUE TITLE
Crop manager consumes power while not harvesting anything

### ISSUE THREAD

**Issue by nhouser9** [GTNewHorizons/GT-New-Horizons-Modpack#12856]
### Your GTNH Discord Username

Secret_Fish#9978

### Your Pack Version

2.2.10

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

Steps:
1. Point a LV battery buffer into a crop manager next to some oreberries.
2. Put a LV batter in the buffer.
3. Wait for the oreberries to grow to tier 3 (one tier before max).
4. Observe the charge level in the batter buffer.

Expected Result:
Either the berries should be harvested, consuming EU from the battery; or, the berries should not be harvested, not consuming EU from the battery.

### The Reality

Actual Result:
The berries are not harvested but EU is slowly drained from the battery. It uses power without doing anything.

### Your Proposal

Make the crop manager behave as indicated on the tooltip; that is, consume EU when harvesting crops, and not consume EU when sitting idle.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by trollolal** [comment]
What berries are you harvesting? It only harvest when it is full stage
Can you provide more detail on the issue?

**Comment by nhouser9** [comment]
@trollolal I'm harvesting aluminum oreberries. I'm aware that it does not harvest until full stage. That's not the problem. The problem is that it consumes power from my batteries even while not harvesting.

**Comment by Kyrorichekku** [comment]
can also confirm this is the case even when not performing any secondary actions (watering, fertilizing) they chug power even with nothing to do 

they're meant to consume power when performing task however they seem to chug their power cost every tick regardless if they do anything

![image](https://user-images.githubusercontent.com/123538122/224486701-2f67ce6e-4164-43bf-a9a3-0fee462c7150.png)

currently I'm running 6 IV and 2 EV, yet 2 (boosted) combustion engines fully fueled running constantly cannot keep up with the power demand (note that they **do not** even take their full tier worth of power even if both harvesting and doing secondary functions every single tick(which should not happen in the first place)

![image](https://user-images.githubusercontent.com/123538122/224486972-966093d4-c389-417c-aa8c-b17a808f47c6.png)

**Comment by vovaksenov** [comment]
This sounds annoying and potentially very difficult to work around for anyone who has large crop fields. Hopefully this can be fixed inside gtpp only so that it could be fixed in-place without waiting for the next release.

**Comment by thehutch** [comment]
Have you checked with the portable scanner if the internal buffer of the crop manager is full?:

![image](https://user-images.githubusercontent.com/979878/225719564-486652fb-ee3d-4563-914d-00fa5e48c06f.png)

**Comment by nhouser9** [comment]
@thehutch I don't have a portable scanner and am not at the point in my play-through where i can make one easily.

However, the battery does not drain at all until the crops hit stage 3. It goes from not draining to suddenly draining. I think if internal buffer was the issue, the batter would start draining as soon as I put it into the batter buffer, right?

**Comment by Shuan97** [comment]
During my gameplay I also noticed that when I put Crop Manager on the field that contains only oreberries (gold, aluminium, etc.) - crops that have option to harvest them manually before final stage, (e.g. at 3/4 stage) it takes power from the power source (battery, generator) - slowly but everlastingly. For other crops that can be harvested only on final stage it takes power only on actual harvest action as expected. 

I don't use watering, weed-ex, fertelizer and anything else that potentially could lead to energy drain.
