### ISSUE TITLE
2.3.0 Crashes on launch with SmoothFont

### ISSUE THREAD

**Issue by ghostflyby** [GTNewHorizons/GT-New-Horizons-Modpack#12865]
### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Actions

With M1 MAX MacBook Pro, macOS 13, PrismLauncher pack, jdk 19
Install SmoothFont, launch, and crash.

### Crash Report

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10949931/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@ghostflyby 2.2.3 not support java 19 are you on this version or on 2.3.0 ?

**Comment by ghostflyby** [comment]
Yes, it’s 2.3.0, sorry for my misleading.
________________________________
发件人: Martin Robertz ***@***.***>
发送时间: Sunday, March 12, 2023 4:34:11 PM
收件人: GTNewHorizons/GT-New-Horizons-Modpack ***@***.***>
抄送: ghostflyby ***@***.***>; Mention ***@***.***>
主题: Re: [GTNewHorizons/GT-New-Horizons-Modpack] 2.2.3.0 Crashes on launch with SmoothFont (Issue #12865)


@ghostflyby<https://jpn01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fghostflyby&data=05%7C01%7C%7C8edae15c94844aba12cb08db22d48e95%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638142068564924777%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cHtanr7UO%2BcJ7NuiRFLjf4Gb1aVH%2B%2Fw9uYX6AdtF5M4%3D&reserved=0> 2.2.3 not support java 19 are you on this version or on 2.3.0 ?

―

**Comment by ghostflyby** [comment]
Seems that `SmoothFont` tries to reflectively access a protected field, which is disabled by default since java 9.


`--illegal-access=debug` has been useless since java 17, so the solution *in theory* is to `—add-opens <modulename>/<packagename>=<target package>` the package `net.minecraft.client.gui.FontRenderer`. 

However in practice, I don’t know its module name, or it, as a java 8 package, it don’t even have one?

**Comment by ghostflyby** [comment]
OK, it turns out that `fastcraft` is conflicting with `SmoothFont`, solved according to [wiki](https://gtnh.miraheze.org/wiki/Additional_Mods)
