### ISSUE TITLE
Nanosuit Boots of the traveller incorrectly boost speed while flying

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12864]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.3.0

### Your Server

sp

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Things should be the same as before we went to GraviNeo. The boots should not affect flying speed.

### The Reality

They give a roughly 4x speed increase.

I do not know if other boots are broken too.

### Your Proposal

Change things back to the old behaviour.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BritishCynic** [comment]
For me, the speed increase over regular nanosuit boots while in the air feels like a decent QoL upgrade

**Comment by chochem** [comment]
it also defeats the point of upgrading to anything else. And makes no sense whatsoever, your boots should not decide your flying speed.

This is just a bug.

**Comment by King65868** [comment]
Boots of the voidwalker speed up flying speed, so there is some sense in this

**Comment by vovaksenov** [comment]
I feel like this could be an EMT issue and related to my #12863

**Comment by DragonStorm25** [comment]
The same thing happens with Quantum Boots of the Traveller

**Comment by TimeConqueror** [comment]
Original Traveller's Boots give you extra movement boost while jumping. So the improved Traveller's Boots should also give you at least the same speed. Before that commit it was giving you less movement boost while jumping than orginal Thaumcraft's one. This is against the design of 'thing improvement craft' and discourages people once they crafted it. So if it needs a fix, it definitely shouldn't be done in a way of reverting the item to its previous mechanics.

**Comment by chochem** [comment]
ok so no clue? then we might have to revert.

**Comment by chochem** [comment]
timeconqueror looked into slightly more on discord and suggested this could be fixed on the gravisuite side

**Comment by chochem** [comment]
it looks like other forms of flight are affected too, e.g. copterpack. so a fix on the gravisuits side makes no sense. This has to either be fixed/reverted here or be declared a feature (which is what mitch wants without even trying it)

**Comment by chochem** [comment]
reopen as alastor mentioned he wants to look it into last week.
