### ISSUE TITLE
Add AE2 support for various upgrade cards to the ME input bus

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12866]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.3.0

### Your Proposal

Add support for various AE2 upgrade cards to the ME input bus, such as mineral dictionary cards, reverse cards, and fuzzy cards

给ME输入总线添加AE2各种升级卡的支持，例如矿物词典卡，反向卡，模糊卡

### Your Goal

It is easier to produce a large number of the same type of items in the game, such as various boards and cables

在游戏中可以更方便的进行大量相同类型的物品生产，例如各种板以及线缆

### Your Vision

Increase the efficiency of machine utilization instead of simply stacking the number of machines

提高机器的利用效率，而不是单纯的对机器数量进行堆叠

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LewisSaber** [comment]
There is auto-pull feature for stocking bus in active pr , it allows stocking bus to automatically provide 16 items it find in ae(refreshes list every 5 seconds), so you can make subnet and push items there using other things that support mineral dictionary , reverse , and fuzzy

**Comment by repo-alt** [comment]
(I still think that the "right" way to do that is a separate block combined with a storage bus, as described here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11143, but I can't find time/motivation to implement it.)
