### ISSUE TITLE
hasValidMetaTileEntity taking 6-11% of server load

### ISSUE THREAD

**Issue by Connor-Colenso** [GTNewHorizons/GT-New-Horizons-Modpack#12862]
### Your GTNH Discord Username

Colen

### Your Pack Version

2.3.0

### Java Version

Java 8

### Your Expectation

hasValidMetaTileEntity is taking 2% of the server load on eta and for other endgame players (such as GDCloud) a whopping 6% of server load, which is insanely high.

![image](https://user-images.githubusercontent.com/52056774/224505934-d0f33d3d-6d20-4221-b8bf-d8a96793a675.png)

The method itself does not appear to have much we can do in the way of optimisation, but perhaps we can see if there are any redundant calls?

```java
    @Override
    protected boolean hasValidMetaTileEntity() {
        return mMetaTileEntity != null && mMetaTileEntity.getBaseMetaTileEntity() == this;
    }
    @Override
    public IGregTechTileEntity getBaseMetaTileEntity() {
        return mBaseMetaTileEntity;
    }
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
It's even worse in my case: 
![image](https://user-images.githubusercontent.com/39203645/224517251-409f5453-6304-40ac-94c0-de33b04f6bcc.png)

**Comment by Tommeh1** [comment]
Any update on this?
As it continues to get worse bit by bit.
