### ISSUE TITLE
Tinkers' Construct Smeltery Acceleration with Mouse Wheel

### ISSUE THREAD

**Issue by Holit** [GTNewHorizons/GT-New-Horizons-Modpack#12867]
### Your Pack Version

2.2.0.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Use wheel to add ingredients to Smeltery construction shall resulting in same consumption of time. (or little delay exists)

### The Reality

![Example Record](https://i.postimg.cc/yxX3Mxm2/3.gif)
As picture shown, Aluminum dusts were added into oven by wheel, and its obvious the time was accelerated. (from progress of single dust and consumption of lava)

### Your Proposal

Repair wheel action.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Holit update to 2.3.0 and test again

**Comment by miozune** [comment]
Same issue as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9594. Can confirm on 2.3.0

**Comment by Holit** [comment]
Can confirm on 2.3.2, using Java 17, @Dream-Master
