### ISSUE TITLE
ASM7 error

### ISSUE THREAD

**Issue by beetree** [GTNewHorizons/GT-New-Horizons-Modpack#12872]
### Your GTNH Discord Username

beetree#8429

### Your Pack Version

2.3.0

### Your Server

Local

### Java Version

Java 17

### Type of Server

Open To LAN

### Your Expectation

![image](https://user-images.githubusercontent.com/12211793/224546324-aa1cb013-188d-4753-a7df-30e37748e5c2.png)

Seems some others on the discord channel are also seeing this error. I see no open issue with the words "ASM7".

Server still starts fine though.

### The Reality

![image](https://user-images.githubusercontent.com/12211793/224546340-137d378d-5e5c-4bc6-8cfe-c996e86a736b.png)

### Your Proposal

Do I need to install something else?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
full log please

**Comment by Ethryan** [comment]
[2023-03-12-7.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10950970/2023-03-12-7.log)

I just ran into this bug, check line 788 for start of the asm7 call

**Comment by eigenraven** [comment]
This is just fml scanning the jar for mods and failing to understand one of the libraries lwjgl3ify shades in. I'll work around it, but it is completely harmless

**Comment by beetree** [comment]
Great, thanks!
