### ISSUE TITLE
Items disappearing if using number keys with GT machine interface opened.

### ISSUE THREAD

**Issue by Nhlest** [GTNewHorizons/GT-New-Horizons-Modpack#12878]
### Your GTNH Discord Username

N`hlest#6101

### Your Pack Version

2.3.0

### Your Server

private

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

I pressed `1` while hovering over first slot in inventory, while having a GT machine GUI open. Expected for nothing to happen.

### The Reality

Item disappeared.

https://user-images.githubusercontent.com/7157355/224567091-2ee20be3-5bed-47d4-8d94-0ef988012bc1.mp4

### Your Proposal

For item to not disappear. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I cant reproduce it on my end

**Comment by niklasstich** [comment]
I can confirm that I can reproduce this. Item has to be in slot n and disappears when you press button n. Java 8, 2.3.0

**Comment by duanespeen** [comment]
skill issue

**Comment by theyugin** [comment]
Can confirm, same Java/GTNH versions. Tested without any backpack equipped.

**Comment by chochem** [comment]
ah, only with open GT machine gui. yea can confirm

**Comment by Glease** [comment]
It doesn't disappear. Resync your inventory in any way or just play SP it will reappear.

**Comment by chochem** [comment]
nothing reappears for me. not a sync issue. (play in singleplayer and sorting inventory/using all slots afterwards)

**Comment by Glease** [comment]
Weird. So something else at play here. In dev env it just shift to another slot due to MUI using a dummy inventory for slots.
