### ISSUE TITLE
Make Ztones Tinted Glass able to be chiseled to and from the different colors

### ISSUE THREAD

**Issue by thgotze** [GTNewHorizons/GT-New-Horizons-Modpack#12879]
### Your GTNH Discord Username

thgotze#6671

### Your Pack Version

2.3.0

### Your Proposal

Title: Make Ztones Tinted Glass able to be chiseled to and from the different colors

### Your Goal

Most if not all other Ztones blocks are able to be chiselled. I don't see why not to add this functionality to the tinted glass block.

### Your Vision

Will add more consistency to what blocks can and can't be chiselled. You'd assumed they could be in the first place.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
Simple, dyes exists and they aren't free.

**Comment by thgotze** [comment]
I think you misunderstand. You are able to Ctrl + Scroll Wheel all Ztones blocks into the different variants, which essentially is a different form of chiselling. Same applies to the tinted glass, so you can craft a red glass and change it into a blue one if you want. But for some reason you can't chisel the tinted glass, which is an inconsistency as every single other Ztone block can.
