### ISSUE TITLE
"ingredient went missing... report error to Alkalus"

### ISSUE THREAD

**Issue by beetree** [GTNewHorizons/GT-New-Horizons-Modpack#12874]
### Your GTNH Discord Username

beetree#8429

### Your Pack Version

2.3.0

### Your Server

Private server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

ME crafting working

### The Reality

![image](https://user-images.githubusercontent.com/12211793/224548163-3ec98072-3015-4081-8b46-9e793b22ee9b.png)

No errors in server log.

It happens every other time. But sometimes the same recipe works. And, it might work immediately after it didn't work so not sure it's dependent on what's in the ME system. It seems random.

Sorry for not being able of replicating the error better. Hopefully I'll learn more as I play about what truly causes it.

### Your Proposal

See if anyone else has the same error (reason for posting the bug), and work on trying to nail down when it's happening - ideally making it reproduceable. I posted it on discord, and didn't seem like anyone else there have had this issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Fiyorin** [comment]
that message is not a error/bug per see, but a helpful message telling you that certain items went missing during the simulation of the craft (example: export bus took it out of ae2). 
however, where does item.null come from? what were you crafting?

**Comment by eigenraven** [comment]
Looks like some GT++ item does not report a valid name in getUnlocalizedName

**Comment by beetree** [comment]
I was crafting this:

![image](https://user-images.githubusercontent.com/12211793/224548769-179464ea-46ec-4d3e-8fed-8d8a632413db.png)

It's Tetranitromethane, and it's a chained recipe.

**Comment by LewisSaber** [comment]
I linked wrong issue in commit, sorry

**Comment by beetree** [comment]
Yeah, was a little confused there for a few seconds :)

**Comment by LewisSaber** [comment]
I liked wrong issue in pr

**Comment by Tommeh1** [comment]
I've got the same error, yet spamming start seems to eventually cause it to start regardless.

**Comment by beetree** [comment]
Same, I can always eventually get it to start. And, it does not seem to be
related to what's in the ME system (e.g. missing item or such). It seems to
be with Dual Interfaces. You have the issue with Dual Interfaces too Tommeh?

**Comment by Tommeh1** [comment]
> Same, I can always eventually get it to start. And, it does not seem to be related to what's in the ME system (e.g. missing item or such). It seems to be with Dual Interfaces. You have the issue with Dual Interfaces too Tommeh?

I don't think we have any dual interfaces used directly by the ME system responsible for the actual order.

**Comment by beetree** [comment]
Ok, well, then the issue is something else :)

Is it happening mainly for fluids? That's the case for me.

**Comment by Tommeh1** [comment]
> Ok, well, then the issue is something else :) Is it happening mainly for fluids? That's the case for me.

As it failed to state what ingredient was missing i can't tell what it had trouble with given that it was a massive order.

**Comment by beetree** [comment]
Mine was also multi-step. Probably it’s when it’s more complexity then.

Oh well, we can’t reproduce :)
