### ISSUE TITLE
Crash exploring world

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12875]
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Exploring the world

### Crash Report

[crash-2023-03-12_08.04.24-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10951135/crash-2023-03-12_08.04.24-server.txt)
Affected region: 
[corrupted region.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10951124/corrupted.region.zip)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment]
I've spent a bunch of time on this, but have to throw in the towel. The crash report lists the following:
```
Details:
        Found chunk: true
        Location: World: (1748,54,2592), Chunk: (at 4,3,0 in 109,162; contains blocks 1744,0,2592 to 1759,255,2607), Region: (3,5; contains chunks 96,160 to 127,191, blocks 1536,0,2560 to 2047,255,3071)
```

Opening the chunk in NBT Explorer/Studio results in a crash, so I went through the file with a hex editor, extracting the chunk. This crash originates in the NBT code, however, looking at the byte for that block/tile entity, it does not appear corrupted to me, so I don't know why it happens to crash there.

```
00003BE0                                                03                 .
00003BF0  00 01 78 00 00 06 D4 03  00 01 79 00 00 00 20 03  ..x.......y... .
00003C00  00 01 7A 00 00 0A 20 08  00 02 69 64 00 12 47 54  ..z... ...id..GT
00003C10  5F 54 69 6C 65 45 6E 74  69 74 79 5F 4F 72 65 73  _TileEntity_Ores
00003C20  02 00 01 6D 42 1B 01 00  01 6E 01 00              ...mB....n..
```
[chunk.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11779550/chunk.zip)

**Comment by Tommeh1** [comment]
> I've spent a bunch of time on this, but have to throw in the towel. The crash report lists the following:
> 
> ```
> Details:
>         Found chunk: true
>         Location: World: (1748,54,2592), Chunk: (at 4,3,0 in 109,162; contains blocks 1744,0,2592 to 1759,255,2607), Region: (3,5; contains chunks 96,160 to 127,191, blocks 1536,0,2560 to 2047,255,3071)
> ```
> 
> Opening the chunk in NBT Explorer/Studio results in a crash, so I went through the file with a hex editor, extracting the chunk. This crash originates in the NBT code, however, looking at the byte for that block/tile entity, it does not appear corrupted to me, so I don't know why it happens to crash there.
> 
> ```
> 00003BE0                                                03                 .
> 00003BF0  00 01 78 00 00 06 D4 03  00 01 79 00 00 00 20 03  ..x.......y... .
> 00003C00  00 01 7A 00 00 0A 20 08  00 02 69 64 00 12 47 54  ..z... ...id..GT
> 00003C10  5F 54 69 6C 65 45 6E 74  69 74 79 5F 4F 72 65 73  _TileEntity_Ores
> 00003C20  02 00 01 6D 42 1B 01 00  01 6E 01 00              ...mB....n..
> ```
> 
> [chunk.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11779550/chunk.zip)

I should note that there is a massive amount of corruption(literal thousands of cases likely) between 2.2.0.0 and newer terrain, so it might be related to that in case this helps.
