### ISSUE TITLE
Neutron Activator requires a Stocking Input Bus for Molten Naquadah

### ISSUE THREAD

**Issue by Fiyorin** [GTNewHorizons/GT-New-Horizons-Modpack#12870]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.3.0

### Your Server

Private

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

trying to use this recipe 

![image](https://user-images.githubusercontent.com/61357/224544379-e0724a61-7217-4797-b995-1fb8dcf61f89.png)

### The Reality

it doesn't start

᲼᲼᲼᲼᲼᲼ says you need a stocking input bus for the dust and that fixes it

### Your Proposal

make it work with regular input buses

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Fiyorin** [comment]
maybe this causes it
![image](https://user-images.githubusercontent.com/61357/224544329-c5291ef8-ab21-481a-9216-873f220361b4.png)

**Comment by chochem** [comment]
could also just divide the recipe by 2 without changing the multi

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GoodGenerator/pull/151
