### ISSUE TITLE
Not opening / crashing world upon opening

### ISSUE THREAD

**Issue by maspace386** [GTNewHorizons/GT-New-Horizons-Modpack#12883]
### Your GTNH Discord Username

flamesmh#0163

### Your Pack Version

2.2.3

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

Was playing and got ambushed by buncha creepers and they destroyed part of my base. Didn't want to deal with rebuilding so i saved and exited minecraft then copied over a backup. Upon restarting gtnh it started telling me that Optifine was causing issues, so i removed that, but now the world just doesnt open, i tried a couple of backups not just the recent one.
[crash-2023-03-12_23.39.31-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10952351/crash-2023-03-12_23.39.31-server.txt)

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10952354/fml-client-latest.log)
[crash-2023-03-12_23.39.31-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10952357/crash-2023-03-12_23.39.31-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ethryan** [comment]
Hmm, the crash report suspects 

> Suspected Mods: FastCraft (FastCraft)

might wanna test removing it and see if it helps

**Comment by maspace386** [comment]
It worked thanks a lot
