### ISSUE TITLE
Wireless energy hatch achievements lacking translation

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12886]
### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

![image](https://user-images.githubusercontent.com/39203645/224795429-6ca88f38-5601-4baf-9e20-18ccb394c290.png)
![image](https://user-images.githubusercontent.com/39203645/224795461-d0505f33-dbb0-42ae-a3c7-6103d40bcd81.png)

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
yes this need to be lacalized
