### ISSUE TITLE
Ruby ore centrifuge having incorrect outputs

### ISSUE THREAD

**Issue by taranpitman** [GTNewHorizons/GT-New-Horizons-Modpack#12882]
### Your GTNH Discord Username

Taran#3079

### Your Pack Version

2.3.0 (official curse release)

### Your Server

PS

### Java Version

Java 8

### Type of Server

None

### Your Expectation

When centrifuging impure ruby dust, the stated byproduct should be jasper dust

### The Reality

When centrifuging impure ruby dust, you receive chrome dust as a byproduct

### Your Proposal

not a proposal, but both seem to be set as the result as if you check ruby ores processing chain through NEI, it shows jasper dust. Meanwhile if you check how to get chrome dust through NEI and go to the ruby ore processing page, it shows chrome dust.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you mixed it up with fools ruby in NEI

**Comment by Dream-Master** [comment]
hehe that was my guess as well but i was unsure. Some day we need to rename it to fools ruby

**Comment by Ethryan** [comment]
Maybe rename it into Red Sapphire,, since that mineral (Al2O3Mg) can contain Magnesium.
