### ISSUE TITLE
Slightly nerf Ancient Cobblestone recipe

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#12894]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.3.0

### Your Proposal

Nerf Ancient Cobblestone recipe or remove its stabilizing property.

----
### **Updated Proposal**: 
After some discussion on discord and here, it does seem there is some tenuous agreement to 1) adjust the recipe 2) make sure to not overnerf it.

Current proposal is: 8 X + 1 entropy cluster -> 8 ancient X for some small amounts of aspects.
where X is not just cobble but all the variants ( bricks, gravel, lapis, iron, gold,..).

### Your Goal

Ancient cobblestone was 'fixed' to work as an infusion stabilizer here: https://github.com/GTNewHorizons/ThaumicBases/pull/17
Sadly this was done without any regard for balance. As it stand it is ridiculously good compared to all other options.

It literally costs 1 perditio per 6 blocks, lol. This was a major balance change that was not supported by any discussion at the time.

### Your Vision

With ancient cobble removed from the stabilizers or nerfed in recipe, other options would be much more interesting and the pack would be much better.

Stabilizing wasnt that hard before either but this addition made it a joke.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/224851480-a74ca706-be64-4fc0-9998-3d83d64eca14.png)
Make this so it uses ancient stone in the recipe, this could be applied to all the ancient variants

**Comment by chochem** [comment]
that might be a bit too extreme, no? Maybe just arcane stone blocks instead and slightly higher aspect cost?

**Comment by EnderProyects** [comment]
Yes xd,  just replyed at discord xd

**Comment by Alastors** [comment]
I'm against it, it does no good for the pack as it doesn't change the underlying issue of mono-block stability spam, as such, why should we just revert people to spamming quicksilver? It's literally just the same problem

**Comment by EnderProyects** [comment]
Quicksilver is not as eassy to obtain, and you cant make 500 blocks of it in some minutes

**Comment by querns** [comment]
Could make the ancient variants cost a block of quicksilver along with the rest of the recipe if you want to make it cost a little more. Blocks of quicksilver are the "baseline" stabilizer, so retaining that cost while allowing for more block variation seems like a decent compromise. Anything to keep people from spamming FPS-devouring mob heads, I say.

**Comment by Alastors** [comment]
> Could make the ancient variants cost a block of quicksilver along with the rest of the recipe if you want to make it cost a little more. Blocks of quicksilver are the "baseline" stabilizer, so retaining that cost while allowing for more block variation seems like a decent compromise. Anything to keep people from spamming FPS-devouring mob heads, I say.

that's idiotic, people would just use quicksilver anyway then

**Comment by querns** [comment]
> that's idiotic, people would just use quicksilver anyway then

And that's fine. There's not really any room for increasing the cost above ancient cobblestone and below quicksilver blocks. A decorative option is added in all of the ancient blocks and the trivial, but nonzero cost of quicksilver blocks is maintained.

**Comment by EnderProyects** [comment]
Alastor, thats why it was suggested making it with arcane stone blocks, like its not that hard

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/224858331-b550a1b8-f03d-4aa8-a20f-9f187c94a18a.png)
( for the people that dont remember the recipe)

**Comment by Alastors** [comment]
why not just switch out the center of the ancient cobble with an entropy cluster at that point

**Comment by EnderProyects** [comment]
In that escenario I would suggest a balanced cluster

**Comment by Alastors** [comment]
> In that escenario I would suggest a balanced cluster

it doesn't use ordo vis

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/224862156-069d1a94-ea85-46df-9b57-445672c0dbf0.png)
I propose this one, gives you 6, change the vis to use 6 of perditio

**Comment by Alastors** [comment]
I propose 8 cobble, 1 entropy cluster in the middle for 8 perditio

**Comment by Alastors** [comment]
> if it return you only 4 of ancient cobble its okay for me

sir what are you trying to say

**Comment by EnderProyects** [comment]
8 cobble, 1 entropy cluster in the middle for 8 perditio for 4 ancient cobble

**Comment by Alastors** [comment]
> 8 cobble, 1 entropy cluster in the middle for 8 perditio for 4 ancient cobble

for 8

**Comment by EnderProyects** [comment]
![image](https://user-images.githubusercontent.com/45178400/224863278-1d143b57-865a-4f5f-bdea-a8b7db92177f.png)
And this one?

**Comment by Alastors** [comment]
> ![image](https://user-images.githubusercontent.com/45178400/224863278-1d143b57-865a-4f5f-bdea-a8b7db92177f.png) And this one?

no the cluster
