### ISSUE TITLE
Better Electric Implosion Compressor

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#12898]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.3.0

### Your Proposal

- EIC should be auto-buildable.
- Add batch mode fr EIC.
- Find out a balanced way to add parallel to EIC.

### Your Goal

Electric Implosion Compressor is becoming important and necessary in late-game.
However, most EIC recipes have low recipe time (e.g. 0.5s,or just 1t), which makes it usual to see EIC running 1t, and makes it impossible to overclock; Meanwhile, EIC have no parallel.
This makes it the only way to increace production to build large amoumt of EICs. All these EICs running 1t together is highly tps-unfriendly. To make it worse, EIC is not auto-buildable, which makes it a tiring job to build all the EICs by hand.
Batch and Autobuilding can help in these situation. A better solution could be adding parallel in an appropreciate way.
(As my personal suggestion: replace Nt blocks with SpNt blocks for 2x parallel, Infinity for 4x, Transcendent for 8x, etc.)

### Your Vision

Batch mode would significantly increase the tps performance.
Auto-building could make building EICs quite simpler.
Adding parallel would be a foundamental solution for both questions.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Cinobi** [comment]
![изображение](https://user-images.githubusercontent.com/25028786/230436434-31dd20d7-745f-4941-a906-07d8e95ad1fa.png)
This machine really lags, so batch mode is requred.
