### ISSUE TITLE
Electric Tinkers Smelter

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#12892]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.3.0-RC-4

### Your Proposal

Add a new multiblock that can make the same recipes as the normal tinkers smelter, but that uses energy instead of lava, upgradeable with coils for speed, and that can use busses and hatches, also change the output with a circuit if you want casting table mode or casting basin mode. 

### Your Goal

There are some recipes that need blocks that you can only get from the Smelter, adn having a low tier multi in midgame/endgame is so cursed, so I suggest the following multiblock and its controller:

- The multi: 9 coils, upgradeable, 3 of minimum height, you can make it taller for moore recipes at the same time, at the cost of velocity ( heat loss), it can use glass or a new seared block casing? Energy use: heat of the recipe x 9 = EU
![image](https://user-images.githubusercontent.com/45178400/224842897-3dd2e736-5e70-4e09-b275-82e21210a9c5.png)

- The controller: Multi smellter, Alloy blast smelter, smeltery controller, seared tank, blast smelter heat containment coils, smeltery drain, casting table, seared briks blocks, casting basin, liquid seared stone.
![image](https://user-images.githubusercontent.com/45178400/224842479-34bc312b-f4ef-4f38-92c0-666a07e48917.png)

### Your Vision

Not to use the smeltery until engame and have something more gregfied, also that can add some interestings uses

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I prefer the current idea, namely that you move to gregtech machines instead. Once you are in MV you should be able to get everything from alloy smelter/extruder/etc.
Which blocks are you unable to get?

**Comment by EnderProyects** [comment]
The one usable in mid game is the coagulated block, then there is the block of solid ender, and for decoration the seared blocks, those four ones cant be obtained out of the smeltery, maybe there are some mores, but idk

**Comment by EnderProyects** [comment]
P.s also there is the thing of the Drying Rack, an earlier block that doesnt have an electric variant ( yes but the recipes are not integrated) and some recipes of it are used during midgame... is so cursed lmao

**Comment by chochem** [comment]
electric variant for drying rack is chem bath, well at least the important one:
![image](https://user-images.githubusercontent.com/40274384/224846874-9317d0d0-1bc0-4157-8419-b4084a0862e8.png)

I would propose we just add recipes for the stuff that currently doesnt have any instead of electrifying the smeltery and extending it to later tiers.

block of solid ender (used in HEE) and seared stone. dont think there is a coagulated block?

**Comment by EnderProyects** [comment]
Coagulated blood sorry xd

**Comment by chochem** [comment]
ah the HEE curse of Vampire, I see. (everything else is just slime it seems)

**Comment by EnderProyects** [comment]
It was more fore this two xd 
![image](https://user-images.githubusercontent.com/45178400/224848586-92d54161-5c75-487d-9cbe-e3f20e18804f.png)
 That are only rack recipes

**Comment by chochem** [comment]
I feel like maybe Dehydrator would be a good fit for the other rack recipes?

**Comment by EnderProyects** [comment]
yes :3

**Comment by King65868** [comment]
The witchery athane takes stuff only obtained from the smeltery too
