### ISSUE TITLE
Make rhodium-plated palladium become actually plated

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#12896]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.0

### Your Proposal

Make a new line for rhodium-plated palladium by puting rhodium solution and a palladium plate in a electrolyzer to make rhodium-plated palladium

### Your Goal

doing mixer to get rhodium-PLATED palladium doesnt make sense to me
![image](https://user-images.githubusercontent.com/105285781/224916867-3cd15386-eb4d-4bc2-b614-fafedeaa5e4f.png)

### Your Vision

make the pack more gregified

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by trollolal** [comment]
Why not? it is PLATED. You can plate a dust with a mixer. It deserves another processing line. Also, shorter processing time can be used to encourage player to do this route, or maybe remove the mixer recipe because it doesnt make sense at all.

I suggest using a recipe on rhodium dust with aqua regia in a dissolution tank to make electroplating grade rhodium electrolyte. And then electrolyze it with palladium plate to get one rhodium-plated palladium plate.

It also encourage player to do the digester dissolution tank process. The machine is available in EV so it deserves a usage in LuV.

**Comment by boubou19** [comment]
i'm against removing mixer recipe because it will break many setups for someone which is not pleased with the pack not following reality. But adding alternative recipe has my full support.

**Comment by trollolal** [comment]
This is my proposed flowchart for the new line. It would reduce the cost and time of the process.
[Rhodium Plated Palladium.pdf](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10968589/Rhodium.Plated.Palladium.pdf)

**Comment by vovaksenov** [comment]
Maybe just rename the material? Rhodium-palladium alloy or something..

**Comment by Alrightsc** [comment]
I'm against the idea, IV definitely does not need more lines

We have already three quite long lines in the same tier (platline, PBI, monaline) plus general AE2/power/multi transition setups, etc.. And this line is also really uninteresting, it basically adds no new content or additional usage other than making it complicated for sake of complexity
