### ISSUE TITLE
Ticking entity crash on getting hit by wither skeleton with thorns armor

### ISSUE THREAD

**Issue by JonahLurton** [GTNewHorizons/GT-New-Horizons-Modpack#12890]
### Your GTNH Discord Username

L0b5terlick#6148

### Your Pack Version

2.2.0.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

I've got a little room in a nether fortress with cursed earth to spawn wither skeletons. When I get hit by one of them, the game frequently crashes. The crash report says the entity causing the crash is the skeleton, but it happens when they hit me. I am wearing thorns armor, and it didn't happen when I switched armor sets.

### Crash Report

[crash-2023-03-13_15.57.43-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10961617/crash-2023-03-13_15.57.43-server.txt)
[crash-2023-03-13_15.43.30-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10961619/crash-2023-03-13_15.43.30-server.txt)
[crash-2023-03-11_03.14.04-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10961643/crash-2023-03-11_03.14.04-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@JonahLurton update to 2.3.0 and retry

**Comment by JonahLurton** [comment]
[crash-2023-06-25_11.03.20-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12100272/crash-2023-06-25_11.03.20-server.txt)
[crash-2023-07-15_16.35.59-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12100273/crash-2023-07-15_16.35.59-server.txt)
[crash-2023-07-16_15.51.14-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12100274/crash-2023-07-16_15.51.14-server.txt)
[crash-2023-06-21_22.16.07-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12100275/crash-2023-06-21_22.16.07-server.txt)


Updated to 2.3.0, here are four crash reports that look related since then.
