### ISSUE TITLE
Level 3 space assemblers making optically perfected CPUs in 64 parallel mode will shut down

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12900]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.3.0

### Your Proposal

Level 3 space assemblers that use 64 parallel mode to make optically perfected CPUs will stop working because they can't get enough EU

3级太空组装机如果使用64并行模式，制作optically perfected CPU时会因为无法获得足够的EU而停止工作

### Your Goal

Increase the maximum amount of energy given to each module at once by the space elevator or reduce the EU consumption of the synthesis table

加大太空电梯一次性给予各个模块的能量上限或者降低合成表的EU消耗

### Your Vision

We don't want our materials to be swallowed and our pace slowed down by machine downtime while we're hanging, right?

我们都不希望自己的材料被吞掉而且在挂机的时候因为机器停机导致自己节奏被减缓，对吧?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
The Assembler will overclock and parallel, so you need to give it 64A of UXV if you want to use all parallels.

**Comment by SafariXiu** [comment]
> The Assembler will overclock and parallel, so you need to give it 64A of UMV if you want to use all parallels.

I actually used a larger laser bin to power it, but it would still actually shut down due to lack of power supply

**Comment by SafariXiu** [comment]
Because my space elevator carries many modules, I use a 4096A UMV laser bin for power

**Comment by minecraft7771** [comment]
Could you detail which recipe the assembler tries and which modules you have that are running at the same time?

**Comment by SafariXiu** [comment]
> Could you detail which recipe the assembler tries and which modules you have that are running at the same time?

At the same time running two MK3 space assembler module, one of them is making optically perfected CPU, and another is optically compatible memory synthesis table, using a one-time out of 32 versions, optically compatible memory power supply is not a problem, only optically perfected CPU will shut down due to insufficient power supply, the other space modules are in the shutdown state

**Comment by SafariXiu** [comment]
Probably because my optically compatible memory recipe is only running 2 parallel, it doesn't consume much power

**Comment by SafariXiu** [comment]
optically perfected CPU realistically uses 64 parallel

**Comment by SafariXiu** [comment]
I reused the space elevator to make optically perfected CPUs in the new archive, but it didn't seem to go wrong, could it be because the moment of block loading and unloading caused no power in the module?

**Comment by SafariXiu** [comment]
![image](https://user-images.githubusercontent.com/98251218/224961502-403d9190-7ddc-4189-a3af-17d135fe5a98.png)
Although energy reserves are just like doing a roller coaster, they all seem to be replenished in time ......

**Comment by minecraft7771** [comment]
When I tested it back then I also got it to work without an issue, but I could add a variable in the config to increase the buffer even more. Then users who have problems can increase the buffer themself.

**Comment by boubou19** [comment]
> When I tested it back then I also got it to work without an issue, but I could add a variable in the config to increase the buffer even more. Then users who have problems can increase the buffer themself.

that would be a very dirty fix to the issue.

**Comment by SafariXiu** [comment]
Maybe based on the module's more power cache, he can still have enough power to work until the block is loaded correctly, even if it's 1 second

**Comment by minecraft7771** [comment]
> > When I tested it back then I also got it to work without an issue, but I could add a variable in the config to increase the buffer even more. Then users who have problems can increase the buffer themself.
> 
> that would be a very dirty fix to the issue.

The issue seems unreproducable though. The internal buffer is big enough to allow all parallels, with other modules on the elevator too (assuming you give it enough power for all modules ofc).

**Comment by SafariXiu** [comment]
> > > When I tested it back then I also got it to work without an issue, but I could add a variable in the config to increase the buffer even more. Then users who have problems can increase the buffer themself.
> > 
> > 
> > that would be a very dirty fix to the issue.
> 
> The issue seems unreproducable though. The internal buffer is big enough to allow all parallels, with other modules on the elevator too (assuming you give it enough power for all modules ofc).

It seems to be because of a block loading problem, let me try

**Comment by SafariXiu** [comment]
I just tried, after exiting the game and re-entering the archive, the space assembler module will not receive EU if it is still running, and it will cause downtime

**Comment by minecraft7771** [comment]
So it's only on world startup. And after that it runs fine forever? That's something I can work with.
