### ISSUE TITLE
Crashing when loading/opening worlds

### ISSUE THREAD

**Issue by rwohmanmac** [GTNewHorizons/GT-New-Horizons-Modpack#12907]
### Your GTNH Discord Username

Rwohmanmac13#2210

### Your Pack Version

2.2.0.0

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I just load the world and it crashes and says shutting down internal server, does not even let me into the world at this point. it says the suspected error is unknown? not sure what to do after tat

### Crash Report

[crash report.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10973848/crash.report.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@rwohmanmac update to 2.3.0 and test again.

**Comment by boubou19** [comment]
no real reason in the crash, but i see you use a very ancient version of java 8. Try updating to latest java 8 to see if it helps

**Comment by rwohmanmac** [comment]
Okay thank you. I’ll try that and let you know if it works.

**Comment by rwohmanmac** [comment]
I updated to the most recent version and have been getting the same error
