### ISSUE TITLE
Renaming script doesnt work sometimes

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#12902]
### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Expect renaming script to always rename items

### The Reality

It sometimes fails to do so
Yesterday my ae2 creative cell was named 
"Creative Energy cell", today its "Neutronium energy cell"
![image](https://user-images.githubusercontent.com/39595617/224975348-a5bc30d1-ccf3-4b97-9259-0256cf14c8ad.png)
From HoloKraft:
![image](https://user-images.githubusercontent.com/39595617/224975477-45ed47ca-f3e5-428c-acfc-156484f0fb40.png)

Happens also for personal ender chest
![image](https://user-images.githubusercontent.com/39595617/224975398-5882c5d4-8abb-4a8a-acfd-4065b82b06c5.png)

Didnt try on other items from file, intresting thisg is that tooltip is loaded for both namings(its located in script file too)
Holokraft plays on 2.2.8 SP J8 , but I can confirm it breaking on stable
All those namings are located in scripts/renaming.za

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Scripts are moved to coremod now https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/13354
