### ISSUE TITLE
Europium sulfide in LuV multiblock electrolyzer stop working after updating to 2.3.0.0

### ISSUE THREAD

**Issue by sasha0552** [GTNewHorizons/GT-New-Horizons-Modpack#12903]
### Your GTNH Discord Username

sasha0552#5178

### Your Pack Version

2.3.0.0

### Your Server

private [(?)](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11573) server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Crafting `europium dust` from `europium sulfide` in a LuV multiblock electrolyzer, since the multiblock electrolyzer provides a 10% energy discount (33,000 * 0.90 = 29700)
![image](https://user-images.githubusercontent.com/45110640/224997355-8d030df9-16b0-4ca3-9c74-3cdcb741bcbb.png)

### The Reality

![image](https://user-images.githubusercontent.com/45110640/224997933-0e08bdd5-4b44-48c5-ae7e-0f57eaad4f54.png)
![image](https://user-images.githubusercontent.com/45110640/224998094-9c840ac8-c367-47ac-8c65-1a27028efe35.png)

Also reported on the official discord server:
https://discord.com/channels/181078474394566657/234936569360809996/1083559559081230397

### Your Proposal

Make multiblock electrolyzer working again in this and similar situations

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueWeabo** [comment]
Can you give a bit more info on how you built the electrolyzer? 2LuV energy hatches or?

**Comment by sasha0552** [comment]
Only one LuV energy hatch
