### ISSUE TITLE
Game crashes when trying to move into particular area of world

### ISSUE THREAD

**Issue by AnT313** [GTNewHorizons/GT-New-Horizons-Modpack#12904]
### Your GTNH Discord Username

AnT313

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

I try to move into certain area of my world and the game crashes. I started playing on CurseForge, tried migrating to prism but issue is still there.

### Crash Report

[crash-2023-03-14_15.30.31-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10969889/crash-2023-03-14_15.30.31-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
Chunk corruption.  You'll need to restore the affected chunks from backup, or remove & regenerate them.

**Comment by AnT313** [comment]
Ill try removing and regenerating, as they are in unexplored part of world, so backups wouldn't change much i guess.
