### ISSUE TITLE
Ztones Block Crafting QoL

### ISSUE THREAD

**Issue by Badluckhaha** [GTNewHorizons/GT-New-Horizons-Modpack#12912]
### Your GTNH Discord Username

YasirRiot#4760

### Your Pack Version

2.3.0 stable (MMC Java 9+)

### Your Proposal

Allow the use of modded dyes (for example Gregtech dyes) to craft their relevant Ztones blocks in an assembler, ideally with support for relevant oredictionary tags for future proofing.

### Your Goal

Currently, it is quite bothersome and is also somewhat inconsistent, in that aurora blocks (from the same mod), when made in an assembler, can be made with any vanilla dye. Thus, by the same venture, it (and other relevant Ztones blocks) should be able to use modded and vanilla dyes, wherever relevant.

### Your Vision

It will make it easier to produce some of the blocks from the Ztones mod, and will make rainbow cacti and coloured honey drops, etc. be more universal.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by trollolal** [comment]
I would also suggest further reduce the crafting time and cost of the Ztone block as it takes a massive amount of it to build a base.
