### ISSUE TITLE
reduce lag caused by laser vacuum pipes

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#12911]
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.3.0

### Your Proposal

Right now, after a certain point in the progression, players start to spam laser vacuum pipes to convey the energy. Two issues with them
- Each pipe alone is not much laggy (200ns according to @BlueWeabo on their server). But the sheer amount used in endgame makes them a non neglectible lag source for something this dumb. According to @BlueWeabo, in their stargate base they have at least 20k pipes, so it's at least 4 ms wasted in that, which is very concerning.
- Each pipe sends client updates to update the textures, so it lags the client in dense places. In addition to that, several blocks of the same link have different texture state, making it unpleasant to look at.

My proposal is to:
- turn the logic of the pipes to be the same as LDPs, as it's a 1:1 type of connection
- make the pipes have predefined animations that would be pure clientside rendering.

While one could argue that wireless energy hatches nuke the issue completely, it's more expensive and more importantly, we have the means to avoid players going a certain path in order for them to avoid lag, so this should be adressed.

### Your Goal

Reduce lag and improve user readability.

### Your Vision

Make endgame less laggy

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Team1Warlord** [comment]
maybe some of devs will remember about that ticket after my comment...
