### ISSUE TITLE
PersonalSpace dimensions spawn draconium ore

### ISSUE THREAD

**Issue by Connor-Colenso** [GTNewHorizons/GT-New-Horizons-Modpack#12919]
### Your GTNH Discord Username

Colen

### Your Pack Version

2.3.0

### Your Server

Eta

### Java Version

Java 8

### Pic
<img width="522" alt="Screenshot 2023-03-16 at 19 06 39" src="https://user-images.githubusercontent.com/52056774/225727802-903c59b4-154d-4e30-9d05-f0f8efb7555e.png">

### Your Proposal

Shouldn't spawn here. Honestly, we should probably just remove it from draconic evolution, we control the mod anyway and cutting unused content rather than adding patches seems like the better option.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
good old if(!ModLoader.isLoaded("dreamcraft")) wrapping should do the trick

**Comment by Connor-Colenso** [comment]
Honestly I'm more of a fan of actually removing content rather than polluting 8 year old mods we fully control with if (stuff) everywhere.

**Comment by eigenraven** [comment]
We shouldn't break the use of mods in other packs if it's so easy to avoid
