### ISSUE TITLE
Add Blacklist at WAs for botania flowers

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#12916]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.3.0

### Your Proposal

Add all the flowers of botania and its addons to the blacklist of the WAs, is so cheaty

### Your Goal

To not play all the botania progression with two endoflames, there are various tiered flowers for something

### Your Vision

Increasing progress throughout botania, and decreasing the lag that particles and poor management of your garden can cause 
- like this: 
 
![image](https://user-images.githubusercontent.com/45178400/225448020-fd6e7c58-9632-441f-b6c0-1dd9238e0893.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LewisSaber** [comment]
I will suggest blacklisting generation flora

**Comment by EnderProyects** [comment]
I also sugest the funcional flower for the one of the aspects above, the loonium, the mobs ones, and the orechilds

**Comment by EnderProyects** [comment]
In the generation terms you can just make better tier flowers ( Entropinnyum and Spectrolus) with one of those you have plenty of mana

**Comment by EnderProyects** [comment]
If this gets approved I could add it myself 🙃
