### ISSUE TITLE
Lapotronic Supercapacitor doesn't support EV Dynamo Hatch

### ISSUE THREAD

**Issue by dest1n1s** [GTNewHorizons/GT-New-Horizons-Modpack#12917]
### Your GTNH Discord Username

Dest1n1#5585

### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I've tried to use EV Dynamo Hatch (GregTech ones and TecTech ones) on Lapotronic Supercapacitor, and expected it to output eu. 

### The Reality

All these EV Dynamo Hatches don't output EU. Once I replace them with IV one, it can work correctly.

### Your Proposal

Male EV Dynamo Hatches work properly on Lapotronic Supercapacitor.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
just tried it and it works fine with both normal EV dynamo and 64A TT EV dynamo.

can you try again, check if the problem was elsewhere, and/or give more details?

**Comment by trollolal** [comment]
I have the same issue that the LSC doesnt form with EV hatch. However, after breaking and replacing the controller block, it work suddenly. Not sure is it the same issue with you.
