### ISSUE TITLE
Repurpose Tinkers Backpack Slot to Hold Focus Pouches

### ISSUE THREAD

**Issue by schneid3306** [GTNewHorizons/GT-New-Horizons-Modpack#12913]
### Your GTNH Discord Username

schneid3306#7813

### Your Pack Version

2.3.0

### Your Proposal

From what I can tell, the Tinkers Backpack slot isn't used in this pack. I don't see a way to make a backpack that can fit in it, and don't see any other purpose. Having the Focus Pouch and Bottomless Pouch of of your inventory is a great QoL for various reasons, but that means you can't use anything else in the belt slot. Since the Tinkers Backpack slot goes unused, it would be a great QoL change to be able to put the Thaum pouches in that slot and free up an inventory space and the belt slot.

### Your Goal

It is needed because bauble slots are limited, and this one is currently unused. The end result of this is to free up one inventory slot for the player, as most won't choose to equip the pouch on their belt slot when a sash is much better.

### Your Vision

This would have the same QoL as on the belt slot, but allows players to wear a belt and keep the Foci cases out of the main inventory.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by CatsLeftEar** [comment]
Great idea!

**Comment by Rika-TH** [comment]
I like the sound of this, although looks like an extended baubles mod is currently under review? Even so, this would be a nice change to allow you to keep a foci pouch while also using other things even within thaum itself

**Comment by Alastors** [comment]
I mean, you can just use the belt slot for the foci bag as is, not like you use the belt slot for much else

**Comment by thenextelement** [comment]
This would still be cool, and as someone who mainlines runic shielding having a slot to put the pouches in that *isnt* the belt slot would be a lot cleaner an experience.
