### ISSUE TITLE
Head moving when leaving menu after having moved mouse cursor

### ISSUE THREAD

**Issue by Ramodo** [GTNewHorizons/GT-New-Horizons-Modpack#12921]
### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Open a menu, move the cursor in the menu, close the menu. You should be looking at the same blocs you were looking at when you opened the menu.

### The Reality

Everytime I open a menu, my inventory or even the chat, if I move my cursor in that menu, then leave it, my character moves his head as if I had moved in the menu.

For exemple : 
Opening my inventory while staring there
![2023-03-16_23 06 20](https://user-images.githubusercontent.com/33554609/225763606-bdb57384-572c-44f4-b8f1-546eb739fc9b.png)

Moving my cursor to the down left corner of my inventory
![2023-03-16_23 06 27](https://user-images.githubusercontent.com/33554609/225763701-5262c4df-62a2-4861-a293-042c010c379f.png)

When I leave my inventory, I instantly end up looking there : 
![2023-03-16_23 06 49](https://user-images.githubusercontent.com/33554609/225763764-a3a32a90-872c-411d-b064-74734b44c5cf.png)

### Your Proposal

I have no idea what might cause this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Can you tell your OS and what additional mods (e.g. optifine, a different fastcraft). For reference this does not happen with the stock 2.3.0 release on win 10, but yeah I recall seeing this kind of behavior before.

**Comment by Ramodo** [comment]
I haven't been able to find a solution despite trying different things, should I try to update to Java 19 ?
