### ISSUE TITLE
No centrifuging ender goo in multiblock

### ISSUE THREAD

**Issue by tarundorairaj** [GTNewHorizons/GT-New-Horizons-Modpack#12927]
### Your GTNH Discord Username

Bay Gulls

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I expected that there would be a multiblock centrifuge recipe for centrifuging ender goo as there is one for the singleblock.

### The Reality

There isn't

### Your Proposal

Add the recipe in minetweaker.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@tarundorairaj the problem is the recipe was add via minetweaker is isnt in gt++ recipe map so the solution would be add the recipe to code
