### ISSUE TITLE
reduce lag caused by unnecessary tile entities in structures

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#12920]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.0

### Your Proposal

change all frames and all other unnecessary tile entities in a structure to non tile entities.
(frames are tile entities) the most part is frame. they were added a lot to the large structures recently.
proposal 1:
make all frames not te. they are te to only put covers on, but u can use some other blocks to put covers too.
proposal 2:
change the frames in structure to some other non te.(this will make version upgrade bit painful for late game players.)
proposal 3:
make a copy of all the frames in game, but this copy is not te, they can be changed between each other.

### Your Goal

to reduce lag. we should avoid unnecessary tile entities.

### Your Vision

helps gtnh to be less laggy.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
at best they are converted to non ticking tile entities. changing them to dumb block would exhaust the block id range.

**Comment by chochem** [comment]
we are making a new multiblock system where only the controller ticks. (well mitch and BlueWeabo are). Check out the discord if you want to learn more about it.

**Comment by miaowwwwww** [comment]
fixed with frames does not count as TEs
