### ISSUE TITLE
Fails to start with java 17.0.6

### ISSUE THREAD

**Issue by S3aW01f** [GTNewHorizons/GT-New-Horizons-Modpack#12924]
### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

I'm trying to load the pack for the first time in the MultiMC Launcher. I disabled pollution in the config and added ftb Utils and the required dependency ftb lib. 

### Crash Report

MultiMC version: 0.7.0-3732

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.67.58.44, 18.67.58.60, 18.67.58.61, 18.67.58.35]

session.minecraft.net resolves to:
    [13.107.226.40, 13.107.253.40]

textures.minecraft.net resolves to:
    [13.107.226.40, 13.107.253.40]

api.mojang.com resolves to:
    [13.107.226.40, 13.107.253.40]

Minecraft folder is:
C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/instances/GT New Horizons 2.3.0/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 17.0.6, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/instances/GT New Horizons 2.3.0/natives

Libraries:
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [✔️] AdvancedSolarPanel-1.7.10-3.5.1a.jar
  [✔️] adventurebackpack-1.0.9-GTNH.jar
  [✔️] ae2fc-1.0.92-gtnh.jar
  [✔️] ae2stuff-1.7.10-0.5.1.15-GTNH.jar
  [✔️] AFSU-1.7.10-1.2.6-GTNH.jar
  [✔️] AngerMod-1.7.10-0.6.3.jar
  [✔️] AppleCore-3.2.10.jar
  [✔️] appliedenergistics2-rv3-beta-175-GTNH.jar
  [✔️] ArchitectureCraft-1.7.10-1.7.6.jar
  [✔️] Aroma1997Core-1.7.10-1.0.2.16.jar
  [✔️] AromaBackup-1.7.10-0.1.0.0.jar
  [✔️] AsieLib-1.7.10-0.5.3.jar
  [✔️] Automagy-1.7.10-0.28.2.jar
  [✔️] Avaritia-1.34.jar
  [✔️] Avaritiaddons-1.7.10-1.5.4-GTNH.jar
  [✔️] backpack-2.2.9-GTNH.jar
  [✔️] bartworks-0.5.164.jar
  [✔️] battlegear2-1.1.2.4.jar
  [✔️] Baubles-1.0.1.16.jar
  [✔️] bdlib-1.7.10-1.9.8-GTNH.jar
  [✔️] BeeBetterAtBees-0.3.jar
  [✔️] BetterAchievements-1.7.10-0.1.3.jar
  [✔️] BetterBuildersWands-1.7.10-0.9.6-GTNH.jar
  [✔️] bettercrashes-1.7.10-1.1.9-GTNH.jar
  [✔️] betterloadingscreen-1.3.39-GTNH.jar
  [✔️] betterp2p-1.0.23.jar
  [✔️] BetterQuesting-3.1.8-GTNH.jar
  [✔️] BiblioCraft[v1.11.7][MC1.7.10].jar
  [✔️] BiblioWoods[BiomesOPlenty][v1.9].jar
  [✔️] BiblioWoods[Forestry][v1.7].jar
  [✔️] BiblioWoods[Natura][v1.5].jar
  [✔️] binnie-mods-1.7.10-2.0.48.jar
  [✔️] BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
  [✔️] BlockLimiter-1.7.10-0.55.jar
  [✔️] blockrenderer6343-1.7.10-1.0.0-RC7.jar
  [✔️] BloodArsenal-1.7.10-1.2.9.jar
  [✔️] BloodMagic-1.3.25.jar
  [✔️] Botania-1.9.15-GTNH.jar
  [✔️] BotanicHorizons-1.7.10-1.0.14-GTNH.jar
  [✔️] BrandonsCore-1.7.10-1.0.0.13-GTNH.jar
  [✔️] bugtorch-1.2.5GTNH.jar
  [✔️] buildcraft-7.1.31.jar
  [✔️] buildcraft-compat-1.7.10-7.1.12.jar
  [✔️] BuildCraftOilTweak-1.7.10-1.0.4.jar
  [✔️] CarpentersBlocks-1.7.10-3.3.8.2-GTNH.jar
  [✔️] catwalks-1.7.10-2.1.4-GTNH.jar
  [✔️] chisel-2.10.17-GTNH.jar
  [✔️] chiseltones-1.7.10-1.0.4-GTNH.jar
  [✔️] CodeChickenCore-1.1.11.jar
  [✔️] CodeChickenLib-1.7.10-1.1.5.5.jar
  [✔️] CoFHCore-[1.7.10]3.1.4-329.jar
  [✔️] CompactKineticGenerators-1.7.10-1.0.jar
  [✔️] Computronics-1.6.19-GTNH.jar
  [✔️] controlling-1.0.0.5.jar
  [✔️] CookingForBlockheads-1.2.14-GTNH.jar
  [✔️] CraftPresence-2.0.0-beta.2+1.7.10.jar
  [✔️] CraftTweaker-3.2.11.jar
  [✔️] creativecore-1.7.10-1.3.27-GTNH.jar
  [✔️] CropLoadCore-1.7.10-0.1.10.jar
  [✔️] CropsPP-1.7.10-1.3.6.12.jar
  [✔️] custommainmenu-1.7.10-1.9.4.jar
  [✔️] defaultserverlist-1.7.10-1.4.0.jar
  [✔️] defaultworldgenerator-1.7.10-0.2.jar
  [✔️] Draconic-Evolution-1.1.15-GTNH.jar
  [✔️] DummyCore-1.7.10-1.15.jar
  [✔️] EMT-1.2.8.28.jar
  [✔️] endercore-0.2.13.jar
  [✔️] EnderIO-2.3.1.68.jar
  [✔️] EnderStorage-1.7.10-1.4.12.jar
  [✔️] EnderZoo-1.7.10-1.0.23.jar
  [✔️] EnhancedLootBags-1.0.8.jar
  [✔️] eternalsingularity-1.0.10.jar
  [✔️] ExtraCells-2.5.32.jar
  [✔️] extrautilities-1.2.13a.jar
  [✔️] fastcraft-1.25.jar
  [✔️] findit-1.7.10-1.0.11.jar
  [✔️] FloodLights-1.7.10-1.2.9.jar
  [✔️] Forbidden.Magic-0.6.6-GTNH.jar
  [✔️] Forestry-4.5.8.jar
  [✔️] forgelin-1.9.7-GTNH.jar
  [✔️] ForgeMultipart-1.3.2.jar
  [✔️] ForgeRelocation-1.7.10-0.0.3.jar
  [✔️] ForgeRelocationFMP-1.7.10-0.0.4.jar
  [✔️] FTBLib-1.7.10-1.0.18.3.jar
  [✔️] FTBUtilities-1.7.10-1.0.18.3.jar
  [✔️] gadomancy-1.0.8.9.jar
  [✔️] galacticgreg-1.7.10-1.0.8.jar
  [✔️] Galacticraft-3.0.67-GTNH.jar
  [✔️] GalaxySpace-1.1.61-GTNH.jar
  [✔️] gendustry-1.7.10-1.6.5.5-GTNH.jar
  [✔️] ggfab-0.1.8.jar
  [✔️] GoodGenerator-0.4.88.jar
  [✔️] GraviSuite-1.7.10-2.0.3.jar
  [✔️] gravisuiteneo-1.0.8.jar
  [✔️] gregtech-5.09.41.317.jar
  [✔️] GT.Scanner.Mod-1.7.10-1.6.9.jar
  [✔️] gtneioreplugin-1.0.28.jar
  [✔️] GTNewHorizonsCoreMod-1.9.171.jar
  [✔️] gtnhlanth-0.9.29.jar
  [✔️] gtnhlib-0.0.13.jar
  [✔️] gtnhmixins-2.1.13.jar
  [✔️] GTNH-TC-Wands-1.7.10-1.2.6.jar
  [✔️] GT-PlusPlus-1.7.227.jar
  [✔️] GTTweaker-1.7.10-1.7.5.jar
  [✔️] HardcoreDarkness-MC1.7.10-1.7.jar
  [✔️] HardcoreEnderExpansion-1.7.10-1.9.7-GTNH.jar
  [✔️] harvestcraft-1.0.21-GTNH.jar
  [✔️] Healer-1.2.0.jar
  [✔️] HelpFixer-1.7.10-1.1.0.jar
  [✔️] hodgepodge-2.0.43.jar
  [✔️] holoinventory-1.7.10-2.1.19-GTNH.jar
  [✔️] HungerOverhaul-1.7.10-1.0.4-GTNH.jar
  [✔️] hydroenergy-1.0.19.jar
  [✔️] IC2 Crop Plugin Version 1.7.10-1.3.1.jar
  [✔️] IC2NuclearControl-1.7.10-2.4.16.jar
  [✔️] ifu-1.7.10-1.9.5.jar
  [✔️] IguanaTweaksTConstruct-2.2.9.jar
  [✔️] industrialcraft-2-2.2.828a-experimental.jar
  [✔️] InfernalMobs-1.7.10-1.7.7-GTNH.jar
  [✔️] InGameInfoXML-1.7.10-2.8.3.96.jar
  [✔️] INpureCore-1.1.5-GTNH.jar
  [✔️] inventorytweaks-1.5.16.jar
  [✔️] IronChest-1.7.10-6.0.71.jar
  [✔️] IronChestMinecarts-1.7.10-1.0.8.jar
  [✔️] irontanks-1.7.10-1.2.6.jar
  [✔️] itlt-1.7.10-1.0.4.jar
  [✔️] JABBA-1.2.22.jar
  [✔️] journeymap-1.7.10-5.1.4p2-fairplay.jar
  [✔️] kekztech-0.6.32.jar
  [✔️] kubatech-0.7.19.jar
  [✔️] littletiles-1.7.10-1.2.7-GTNH.jar
  [✔️] logisticspipes-0.9.4.5.13-GTNH.jar
  [✔️] lootgames-1.7.10-2.0.8.jar
  [✔️] LunatriusCore-1.7.10-1.1.7-GTNH.jar
  [✔️] magicbees-1.7.10-2.5.16-GTNH.jar
  [✔️] malisiscore-0.14.7-GTNH.jar
  [✔️] malisisdoors-1.13.7-GTNH.jar
  [✔️] Mantle-0.3.6.jar
  [✔️] mixingasm-v0.2.4.jar
  [✔️] ModTweaker2-0.9.10.jar
  [✔️] modularui-1.0.71.jar
  [✔️] MouseTweaks-2.4.8-GTNH.jar
  [✔️] MrTJPCore-1.7.10-1.1.4.jar
  [✔️] mxrandom-0.1.6.jar
  [✔️] Natura-1.7.10-2.5.5.jar
  [✔️] naturescompass-1.7.10-1.3.6-GTNH.jar
  [✔️] NEIAddons-1.7.10-1.12.22.jar
  [✔️] NEICustomDiagram-1.5.1.jar
  [✔️] NEIIntegration-1.7.10-1.2.3.jar
  [✔️] netherportalfix-1.7.10-1.1.2.jar
  [✔️] NettyPatch-1.7.10-0.3.1.jar
  [✔️] NodalMechanics-1.7.10-1.1.-6-GTNH.jar
  [✔️] NotEnoughEnergistics-1.3.30.jar
  [✔️] notenoughIDs-1.7.10-1.4.6.jar
  [✔️] NotEnoughItems-2.3.39-GTNH.jar
  [✔️] oauth-1.7.10-1.06.1-GTNH.jar
  [✔️] OpenBlocks-1.6.10-GTNH.jar
  [✔️] OpenComputers-1.8.0.13-GTNH.jar
  [✔️] OpenGlasses-1.7.10-1.2.5-GTNH.jar
  [✔️] OpenModsLibs-1.7.10-0.10.6.jar
  [✔️] OpenModularTurrets-1.7.10-2.2.11-247.jar
  [✔️] openprinter-1.7.10-0.1.3-GTNH.jar
  [📁] OpenSecurity (folder)
  [✔️] opensecurity-1.7.10-1.0.120-GTNH.jar
  [✔️] Opis-1.7.10-1.3.8-mapless.jar
  [✔️] overloadedarmorbar-1.7.10-1.0.1.jar
  [✔️] p455w0rdslib-1.7.10-1.0.4.jar
  [✔️] Pam's Harvest the Nether 1.7.10a.jar
  [✔️] personalspace-1.0.23.jar
  [✔️] PlayerAPI-1.7.10-1.4.2.jar
  [✔️] ProjectBlue-1.7.10-1.1.8-GTNH.jar
  [✔️] ProjRed-1.7.10-4.7.9-GTNH.jar
  [✔️] Railcraft-9.13.19.jar
  [✔️] RandomThings-1.7.10-2.4.3.jar
  [✔️] RemoteIO-1.7.10-2.4.8.jar
  [✔️] roguelike-1.7.10-1.5.3-GTNH.jar
  [✔️] RWG-1.7.10-alpha-1.3.3.2.jar
  [✔️] Schematica-1.7.10-1.9.2-GTNH.jar
  [✔️] SGCraft-1.7.10-1.3.13-GTNH.jar
  [✔️] sharewhereiam-1.7.10-0.2.0.jar
  [✔️] sleepingbag-1.7.10-0.1.4.jar
  [✔️] SpecialMobs-3.3.15.jar
  [✔️] SpiceOfLife-2.0.9-carrot.jar
  [✔️] SSP-1.1.2-GT-NH-Mod.jar
  [✔️] StevesAddons-1.7.10-0.10.27.jar
  [✔️] StevesCarts-1.7.10-2.0.2.jar
  [✔️] StevesFactoryManager-1.1.7-GTNH.jar
  [✔️] StorageDrawers-1.11.20-GTNH.jar
  [✔️] StorageDrawersBop-1.7.10-1.11.17-GTNH.jar
  [✔️] StorageDrawersForestry-1.7.10-1.11.17-GTNH.jar
  [✔️] StorageDrawersMisc-1.7.10-1.11.18-GTNH.jar
  [✔️] StorageDrawersNatura-1.7.10-1.11.17-GTNH.jar
  [✔️] structurecompat-1.7.10-0.3.0.jar
  [✔️] structurelib-1.2.6.jar
  [✔️] SuperTic-1.7.10-1.2.5.jar
  [✔️] Tainted-Magic-7.6.2-GTNH.jar
  [✔️] tcinventoryscan-1.7.10-1.0.12-GTNH.jar
  [✔️] tcneiadditions-1.1.1.10.jar
  [✔️] tcnodetracker-1.7.10-1.1.7.jar
  [✔️] TConstruct-1.9.25-GTNH.jar
  [✔️] TecTech-5.0.114.jar
  [✔️] TGregworks-1.7.10-GTNH-1.0.23.jar
  [✔️] Thaumcraft-1.7.10-4.2.3.5a.jar
  [✔️] Thaumcraft4Tweaks-1.5.3.jar
  [✔️] ThaumcraftMobAspects-1.7.10-1.0.0-GTNH.jar
  [✔️] thaumcraftneiplugin-1.7.10-1.7a.jar
  [✔️] ThaumcraftResearchTweaks-1.7.10-1.0.4.jar
  [✔️] Thaumic Machina-1.7.10-0.2.1.jar
  [✔️] Thaumic-Based-1.4.33.jar
  [✔️] thaumicenergistics-1.3.30-GTNH.jar
  [✔️] Thaumic-Exploration-1.7.10-1.1.94-GTNH.jar
  [✔️] ThaumicHorizons-1.2.1.12.jar
  [✔️] thaumicinsurgence-0.1.4.jar
  [✔️] ThaumicTinkerer-2.6.12.jar
  [✔️] TiCTooltips-1.7.10-1.2.10.jar
  [✔️] Tinkers-Defense-1.2.1d.jar
  [✔️] TMechworks-1.7.10-0.2.16.4.jar
  [✔️] TooMuchLoot-1.7.10-4.1.0-GTNH.jar
  [✔️] torohealth-1.7.10-1.0.1.jar
  [✔️] Translocator-1.1.2.21.jar
  [✔️] TravellersGear-1.7.10-1.16.6.jar
  [✔️] travellersgearneo-1.0.jar
  [✔️] TwilightForest-2.3.8.18.jar
  [✔️] txloader-1.5.jar
  [✔️] Universal-Singularities-8.6.6.jar
  [✔️] visualprospecting-1.7.10-1.0.37.jar
  [✔️] Waila-1.5.24.jar
  [✔️] WailaHarvestability-1.7.10-1.1.10-GTNH.jar
  [✔️] WAILAPlugins-0.2.6.jar
  [✔️] WanionLib-1.8.4.jar
  [✔️] WarpTheory-1.2.12-GTNH.jar
  [✔️] Wawla-1.7.10-1.1.3-GTNH.jar
  [✔️] WirelessCraftingTerminal-1.8.9.3.jar
  [✔️] witchery-1.7.10-0.24.1.jar
  [✔️] WitcheryExtras-1.1.14.jar
  [✔️] WitchingGadgets-1.2.27-GTNH.jar
  [✔️] WR-CBE-1.7.10-1.4.8.jar
  [✔️] YAMCore-1.7.10-0.5.84.jar
  [✔️] Ztones-1.7.10-2.2.2.jar

Params:
  --username  --version 1.7.10 --gameDir C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/instances/GT New Horizons 2.3.0/.minecraft --assetsDir C:/Users/mARYN/Downloads/mmc-stable-windows/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms4096m, -Xmx8000m, -Duser.language=en]

Minecraft process ID: 16500

Using onesix launcher.

Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by AtomicGrog** [comment]
Theres a bunch of java params to apply, likely the cause:

https://github.com/GTNewHorizons/lwjgl3ify

Underlying problem with the release seems to be that MultiMC doesn't support (bug) the inclusion of the params through the supplied files.

**Comment by Glease** [comment]
Copying from #faq on discord:
> 2. Symptom: Using MultiMC or its derivates, log contains error java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap'), e.g. this:
	```
	Failed to start Minecraft:
	java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	    at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:218)
	    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:253)
	    at org.multimc.EntryPoint.listen(EntryPoint.java:136)
	    at org.multimc.EntryPoint.main(EntryPoint.java:35)
	```
> Solution: copy mmc-pack.json AND patches folder alongside the .minecraft folder in downloaded zip. Do not ignore it. After that, restart your launcher.

**Comment by chochem** [comment]
its actually both of these things.
1) you downloaded the wrong version of the pack. download the java17-19 prepack, not the normal one (=java8) if you want to use that. (the prepack is easier than what glease suggests, though alternatively you can follow that)
 2) dont forget the args you need for MMC in java17-19 (not a bug despite what atomicGrog says)

if that is all too much for you can of course just use java8 as before.
