### ISSUE TITLE
lwjgl3ify Borderless Window Problems

### ISSUE THREAD

**Issue by ArticulatedDrunk** [GTNewHorizons/GT-New-Horizons-Modpack#12935]
### Your GTNH Discord Username

Ozymandias#3078

### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Inside the lwjgl3ify config there is a setting for removing the window decorations. I assumed it would make the game run borderless window mode.
![image](https://user-images.githubusercontent.com/22388690/226077609-ba1dc4a8-c924-44e6-bfed-60246cde3888.png)

### The Reality

Forces the game into a permanent full screen that can't be exited without exiting the game. Also does funky things with hdr monitors like crashing the brightness and applying a weird color scheme that lasts beyond the closing of the game.

### Your Proposal

Just make it a borderless window mode instead of weird fullscreen.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by eigenraven** [comment]
What is your operating system, and if on linux desktop environment/window manager? Also gpu driver version would be good to know.
lwjgl3ify simply passes that as a setting to the system library, there is no other way of making borderless windows that's available.

**Comment by ArticulatedDrunk** [comment]
At the time I was on windows 10 and whatever the latest amd driver was for the 6900xt
I have not tried doing this again since.
