### ISSUE TITLE
A more useful Lava Boiler

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#12931]
### Your GTNH Discord Username

leagris

### Your Pack Version

2.3.0

### Your Proposal

@Dream-Master [asked in Discord#mod-dev](https://discord.com/channels/181078474394566657/603348502637969419/1086333880254091436)
> Steam Age Question: is it possible to add a mini tank into the steam age lava boiler ? (like 4-8 buckets lava) rn this device is not relay usable or is it possible to pump in lava with no pumps ?

This is definitely possible but I also propose to expand the usefulness of the Lava Boiler by having it to generate an Obsidian Block.

1. Increase the size of both Internal Input Tanks: Lava 1600 L (or 16 lava buckets) and Water proportionally.
2. Add generation of an Obsidian Block each time the Boiler has run through 1000 L of Lava. The Boiler would stop heating Water to Steam until the generated Obsidian Block is removed (See Vision for removal methods)

### Your Goal

The Lava Boiler is of limited usefulness due to short run time and it can't really compete with Solar or small Coal Boilers in its current state.
- Increasing its internal input tanks size, would allow it to run for longer before inserting more lava.
- Having it generate Obsidian, would allow early access to obsidian blocks, before player can get a tool with high enough harvest level; and the mechanic of it creates a small but fair logistical challenge for a steam age player, with a reward for piping out efforts and laziness sanction with forced tool usage if no proper piping out.

### Your Vision

Only Lava and Water can be inserted from any side.
Depending on Fluid type, it is routed to the dedicated Internal input tank (Water or Lava).
Both Lava and Water can be inserted either:
- With In-World Block Interaction with a Container Item (Bucket, Cell…);
- Or Actively Piped-In.

The Obsidian Block would either be:
- Either Block Placed under the Boiler, if it has Empty Air Below it (requiring player to mine it with a proper tool);
- Either Stuck Inside the Boiler (requiring player to use a Crowbar to Dislodge it as an Item);
- Either Actively Pulled Out (using a Hopper, Pipe-with-Conveyor cover, EIO Conduit…).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
> Having it generate Obsidian, would allow early access to obsidian blocks, before player can get a tool with high enough harvest level

The machine needs steel, so its really at the same time as the pick. But I consider that a positive. Getting obsidian only after steel is indeed the intended progression. (even though there are like 2-3 ways to bypass that)
