### ISSUE TITLE
Fluid Pattern Terminal Crash on writing EIC recipes

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#12949]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Trying to write pattern for a EIC recipe including fluid. Clicked + button in NEI page. The game crashes to main menu immidately.
The crash appears on all kinds of fluid terminals(Standard, Extended, Portable).
Shift + Clicking leads to the same crash.

### Crash Report

https://paste.ubuntu.com/p/KXD4H8swzf/

[paste.ubuntu.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11342691/paste.ubuntu.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ekrauser** [comment]
Seeing the same exact thing on 2.3.2. Consistently reproduceable. https://paste.ubuntu.com/p/N4wcbhStyQ/

**Comment by Fiyorin** [comment]
same problem here on 2.3.2 with updated mods

https://pastebin.com/raw/XfD7csbY

**Comment by miaowwwwww** [comment]
same thing still in 2.3.5
