### ISSUE TITLE
Quantum Force Transformer doesn't overclock to reach recipe power tier

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12945]
### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

If the input hatch of the quantum force transformer is of a lower tier than what the recipe requires the quantum will never run, even if the hatch provides plenty of amps to overclock to the required tier.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
do you actually mean input hatch or do you mean energy hatch?

Either way might not be a bug but just bad documentation.

**Comment by Tommeh1** [comment]
> do you actually mean input hatch or do you mean energy hatch?
> 
> Either way might not be a bug but just bad documentation.

I mean energy hatch, and i don't see how this could be bad documentation.
Any other machine will overclock from a lower tier to the recipe tier just fine if it can.

**Comment by chochem** [comment]
precise assembler would be one such example.

anyway I dont know for this one. will need to wait for @Steelux8 or @BlueWeabo

**Comment by Steelux8** [comment]
I forgot exactly how Blue implemented this, but it is intended that a type of energy hatch gate exists here.
