### ISSUE TITLE
Confusing messages printed by Tinker's leveling.

### ISSUE THREAD

**Issue by immibis** [GTNewHorizons/GT-New-Horizons-Modpack#12946]
### Your GTNH Discord Username

immibis#3179

### Your Pack Version

2.2.3

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Tinker's tool level-up messages are clearly level-up messages

### The Reality

A couple of the messages are completely unclear since there is no reference to the tool name, nor any act of using a tool or leveling.

I saw one in my chat log and had to search the mod files to find out what it meant:

```
message.levelup.11=That decoration is surely going to do something.
message.levelup.15=Since name is not enough.
```

(also, the latter makes no sense at all?)

### Your Proposal

```
message.levelup.11=Decorating %s is surely going to do something.
message.levelup.15=As if %s wasn't already good enough.
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
the first one is fine, don't see the problem. fixed the second in https://github.com/GTNewHorizons/IguanaTweaksTConstruct/commit/9ef99b513d4239ee666c28984ef641c216b9075c

**Comment by immibis** [comment]
@chochem The problem with messages without %s is that it's not clear they are related to the tool you are using or the leveling system at all. I had to grep the mod files for the message to find out that it was a tool leveling message.
