### ISSUE TITLE
Server DoS attack via large AE2 orders

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12959]
### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Making a large AE2 order will take a lot of memory during calculations, this can quickly fill up memory and freeze the server, essentially acting as an easy DoS attack.
![image](https://user-images.githubusercontent.com/39203645/226228014-1be54ba1-dd1e-463e-98cb-dae6257ccdda.png)

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
I suppose that this should actually be labelled as a crash instead of a bug.

**Comment by Connor-Colenso** [comment]
How large/complex was the recipe you were ordering? Previously we've only seen this occur in very lategame.

**Comment by Tommeh1** [comment]
> How large/complex was the recipe you were ordering? Previously we've only seen this occur in very lategame.

The shielding cores for a T3 quantum were already sufficient to send the usage up about 2.5GB before i cancelled it due to how long it was taking to calculate.
After which i wondered if there was any form of protection to prevent people from crashing a server by abusing this, which turns out to not be the case
