### ISSUE TITLE
[RFC] Removing Magneto Circuits

### ISSUE THREAD

**Issue by Connor-Colenso** [GTNewHorizons/GT-New-Horizons-Modpack#12951]
### Your GTNH Discord Username

Colen

### Your Pack Version

2.3.0

### Your Proposal

I am formally proposing the removal of the magneto resonatic circuit line. These circuits serve no use but to mislead users and clutter NEI, generating them is a waste of time. 

There is no reason to keep these in the game as far as I can tell. But I am sure someone will find some extremely niche reason to keep them, so please (begrudgingly) feel free to comment if that is you.

And no before someone suggests it I don't think these should be rebalanced/reworked to be "better" they are a pointless alternative to bypass the circuit system. I've no idea why these were added by Bart but they clearly are long since abandoned.

Consider this a formal warning, so when I inevitably PR these out of existence you will have had prior notification.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
There are people using them:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12450

**Comment by Dream-Master** [comment]
No not remove them! make them usefull for any kind of production line or so. MAybe we can unbound the oredict and use this circuits for special stuff. We can still change recipes if they are not good desinged.

**Comment by chochem** [comment]
I was also surprised but they are in fact used

**Comment by Connor-Colenso** [comment]
> No not remove them! make them usefull for any kind of production line or so. MAybe we can unbound the oredict and use this circuits for special stuff. We can still change recipes if they are not good desinged.

I don't mind seeing the parts/textures themselves reused for something else, but an alternative circuit line is just a headache for no real gain.

**Comment by Connor-Colenso** [comment]
> There are people using them: #12450

Honestly if anything this proves that they need to be removed more, these are poorly balanced alternatives just thrown into the pack with little concern for wider balance. Why do we need two separate circuit lines completely independent of each other? It just makes the pack look messy and less unified.

**Comment by Dream-Master** [comment]
> > No not remove them! make them usefull for any kind of production line or so. MAybe we can unbound the oredict and use this circuits for special stuff. We can still change recipes if they are not good desinged.
> 
> I don't mind seeing the parts/textures themselves reused for something else, but an alternative circuit line is just a headache for no real gain.

why not alternative circuit line ? As i said before we can change the recipes make more sense. MAybe we let them in oredicted and set it as more high tier variant of a circuit tier get more per craft or use less material or steps each craft

**Comment by iouter** [comment]
> I was also surprised but they are in fact used

it's just that there have been too many changes in the general circuit.

**Comment by ChemEng227** [comment]
making magneto circuits in present version is actually just time-for-material exchange. magneto circuits can be crafted passively but ordering them with AE takes too much time.

**Comment by Rika-TH** [comment]
Seeing the linked issue, would this not be fitting as being set to open? Or is it now something written down as a "yes this will be done" eg, the vision

**Comment by Rika-TH** [comment]
Gotcha, the purging must continue ever more! Thanks for all your work

**Comment by Dream-Master** [comment]
> This will be done, but my purging crusade has not made its way to bartworks yet.

not purge the circuits we just use them in other machines/stuff. We not need to purge everything.
