### ISSUE TITLE
Dual Interface with Sub ME - Blocking Mode not working

### ISSUE THREAD

**Issue by minecraft7771** [GTNewHorizons/GT-New-Horizons-Modpack#12950]
### Your GTNH Discord Username

minecraft7771#0427

### Your Pack Version

2.3.0.0

### Your Server

MyFTB

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

![](https://cdn.discordapp.com/attachments/744192120742740039/1087000008542404709/image.png)
In 2.2.0.0 we build this dual interface into sub me contraption. The sub me has 2 fluid storage busses and one item storage bus, and is on an MCR which only holds patterns for recipes with exactly 2 fluid inputs.

![](https://cdn.discordapp.com/attachments/744192120742740039/1087000318698590359/image.png)
These are the settings of the main me dual interface. 

### The Reality

In 2.2.0.0 this worked fine. Now however the ME regulary puts one fluid each of two recipes inside which clogs the machine indefinetly.

### Your Proposal

Fix or tell me if I am missing something that needs to be set now.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Also once I cancel the task to empty the clogged input hatches the others fluids get still pushed into the input hatches I just emptied - However when I look into the dual interfaces all are shown empty. Idk where this fluid gets pushed that it can just come back.

**Comment by firenoo** [comment]
While not the same problem exactly, I can reproduce a similar "bug" where the interface ignores the contents of fluids present in a ME system. The setup is as follows:
![image](https://user-images.githubusercontent.com/49818773/234945483-d5ccefdf-3fe0-4615-9a4b-495a150fb298.png)

There are two dual interfaces connected into each other. The left system contains fluid/item storage buses on the tank and chest respectively. The right dual interface has blocking mode on, default insertion mode. Even when fluids (or even just items) are present in the left ME system, the dual interface on the right tries to push items and fluids.

However, I don't think this is a bug. Using a regular interface with items only, it exhibits similar behavior (that is, it pushes the items regardless of blocking mode). You could say that the previous behavior was in fact a bug-turned-feature.

**Comment by Ydrec** [comment]
So i guess the suggested feature then would be:

1. Make interfaces bypass item slots when accepting items, would solve not being able to accept much items if there is already something stocked and  a few niche problems with asslines and limited input stacks. 

2. Make interfaces/duals show what exists in the network storage? Like when networks are linked using storage bus on interface but always accessible as if it stored them like stocking bus, so other types of pipes can extract from it and blocking would work like suggested. 

Definitely gonna be useful to simplify some setups.

**Comment by Ydrec** [comment]
> Isn't the point of blocking mode to not block when any items are in the inventory? I feel like this defeats the whole purpose of the setting.
Maybe a typo but did you mean to block if there are any items in inventory?

Blocking doesn't do anything on the acceptor side im like 99% sure. It only affects how patterns being outputted. 

If you have something stocked in acceptor interface blocking wouldn't ever work iirc so bypassing them would just add an option to make it work by blocking from network contents and not interface buffer. 

If nothing is stocked you still can't really block using in between buffers like interface internal slots due to them just infinitely being extracted whatever possible.

 So bypassing them entirely wouldn't change blocking not working in interface -> interface setup, but would fix the mentioned 9 slots max problem and stocked items taking up space for item transfer

**Comment by Ydrec** [comment]
Would be really cool as an option to block from network. 

Bypassing was just suggested as fluids already do it and it would solve a niche problem with needing to transfer more than 9 items in same tick to keep item order consistent for asslines. Not really an issue and probably not necessary if it would break major parts of interface code.

**Comment by firenoo** [comment]
I'll add it but it'll be an upgrade.
