### ISSUE TITLE
Migration error from ExtraCells

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#12953]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

230

### Your Server

priv srv

### Java Version

Java 19

### Type of Server

None

### Your Expectation

- [ ] I tried to convert the fluid storage cell but it has no recipe

![image](https://user-images.githubusercontent.com/7230430/226195695-92836a19-e0f4-4acc-839a-d64dbb900878.png)

- [ ] after converting the item storage cell the partition data is lost

### The Reality

-

### Your Proposal

fix, thx

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
Automatic conversion has been now implemented in dev.
