### ISSUE TITLE
Silken Tofu giving a Raw fish in cooking table

### ISSUE THREAD

**Issue by LegendaryEvenWeeb** [GTNewHorizons/GT-New-Horizons-Modpack#12956]
### Your GTNH Discord Username

Maho_Yoshino#5341

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Trying to craft Silken tofu

### The Reality

The game gave me a raw fish

### Your Proposal

make it actually give silken tofu

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/226204545-ebb6ca30-e58c-4cb1-8ac8-f76668055a85.png)

seems to work fine

**Comment by LegendaryEvenWeeb** [comment]
it shows me that too but i click it and it gives me fish

**Comment by chochem** [comment]
yea I clicked and it worked too

**Comment by LegendaryEvenWeeb** [comment]
https://user-images.githubusercontent.com/62778359/226204714-0e687d5a-7c66-43d0-a077-122e0c8cdbcb.mp4

this is what is happening to me

**Comment by chochem** [comment]
so probably an issue with that particular crafting interface then. what is that?

**Comment by LegendaryEvenWeeb** [comment]
it's the cooking table from Cooking for Blockheads

**Comment by chochem** [comment]
nope, still works for me. hmm.
clearly it somehow conflicts with the same recipe without the pin. but I dont know how it breaks for you.

**Comment by LegendaryEvenWeeb** [comment]
I don't know how the recipe could be messed up as the only thing i did with config is turn pollution off in the Gregtech config. Though i guess it is notable that i use curseforge so that may be messing stuff up

**Comment by chochem** [comment]
I am not sure what we are doing differently: 
![image](https://user-images.githubusercontent.com/40274384/226205024-a1b8ba12-fce5-4947-af6e-7028bfe4608f.png)

**Comment by LegendaryEvenWeeb** [comment]
huh... i don't know then. As shown in the video that is what's happening to me for no reason

**Comment by LegendaryEvenWeeb** [comment]
the crafting says i need a rolling pin, which is gregtech:gt.metatool.01. Which is coincidentally the same ID as the gregtech knife

**Comment by LegendaryEvenWeeb** [comment]
![image](https://user-images.githubusercontent.com/62778359/226205231-404c902b-f944-44af-aa32-603e6288b73e.png)
![image](https://user-images.githubusercontent.com/62778359/226205248-e6542748-2712-403e-827e-4b9606470f7a.png)
and i don't have the rolling pin but i do have the knife

**Comment by chochem** [comment]
well if you dont actually have the tool that would explain it. (knife having same id means nothing the meta distinguishes that)

then tool is just a ghost and you are indeed correctly crafting a fish

**Comment by LegendaryEvenWeeb** [comment]
how does that even work, why am i getting a fish, and not the item back?

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/226205441-878235ee-cc0f-4d94-b7eb-6e5b62204e13.png)
all the fishoredict items craft into the vanilla fish.
