### ISSUE TITLE
AE2FC Fluid export bus void liquids when exporting with crafting card with "only crafting" mode

### ISSUE THREAD

**Issue by Filiz1** [GTNewHorizons/GT-New-Horizons-Modpack#12966]
### Your GTNH Discord Username

Filiz

### Your Pack Version

2.3.0

### Your Server

unofficial

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Fluid export bus not void liquids.

### The Reality

Fluid export bus void liquids. Not necessary to have a pattern, just fluid export bus with crafting card, fluid storage and empty tank. Specified liquid slowly (approximately 1 bucket in 1.5-2 sec.) disappear from ME system and not appear in destination point.

### Your Proposal

Fix this.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by trollolal** [comment]
Do you have more details about this issue?

**Comment by Ydrec** [comment]
When fluid export bus from ae2fc has crafting card, filtered to some fluid and set to only craft and not use stored fluid, it would start voiding stored fluid at the same speed as if it was outputting. IF fluid is crafted it outputs fine, but the fluid taken from storage in such case is just voided. Seems like some checks aren't in place to prevent in from taking fluid when in craft only mode

**Comment by MarchingCube** [comment]
I had to remove all usages of crafting card with AE2FC fluid export bus after updating. Before 2.3.0 if a craft produced more fluid than needed to export (for example there is 1 bucket space in the tank and craft produces 16 buckets) leftover fluid would just be sent back to the network. In 2.3.0 extra fluid will be just voided, if one cancels the craft then produced fluid ends up correctly in the network.
