### ISSUE TITLE
Vajra Replication Compacted Master Ritual Stone

### ISSUE THREAD

**Issue by SHIBUYAENNI** [GTNewHorizons/GT-New-Horizons-Modpack#12960]
### Your GTNH Discord Username

ENNISHIBUYA#3552

### Your Pack Version

2.3.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I use Vajra to open Silk Touch mode and right click to dig up the Compacted Master Ritual Stone

### The Reality

They are replicated

https://user-images.githubusercontent.com/96222276/226307991-f33430f2-4af7-43d3-86d5-b161d27d8605.mp4

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/Gravitation-Suite-Neo/pull/11
