### ISSUE TITLE
Add Infinite Water or lava fluid storage cell in AE2FC

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#12964]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.0

### Your Proposal

Add an item called Infinite Water fluid storage cell that allow AE to use infinite water, same goes for the lava. Instead of slapping a fluid storage bus on a tank filled with infinite water or lava created from reservoir and everfull urn.

### Your Goal

QoL and conserve channel and improve performance

### Your Vision

Allow AE system to have infinite water without an external storage bus

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
The everfull urn is not "infinity because yes, it uses vis per extraction, and there is the void miner, for watter I think its okay, but you could slap a bus to a reservoir hatch ( it should work)
