### ISSUE TITLE
Remove Gregtech arrow

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#12963]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.0

### Your Proposal

Follow up to magneto circuit line, since no one ever use gregtech arrow, I recommend to remove it to save thousands of recipe from chemical bath and crafting recipe.

### Your Goal

To make the pack less crowded with useless recipe

### Your Vision

Performance

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Maybe if possible only if gtnhcoremod is detected. They are obviously obsolete in the modpack, but they might not be for those who play standalone.

**Comment by boubou19** [comment]
GT arrows are from GT5U, but our GT5U is so modified it wouldn't make sense to enable it as our GT5U is made for NH only.

**Comment by Connor-Colenso** [comment]
I am in support of this and even if not removed from GT5u now I do not intend to support them in the new ModernMaterials system.

**Comment by vovaksenov** [comment]
Remove stale

**Comment by Dream-Master** [comment]
Maybe we can add such gt arrow effects to Tico. But if we remove arrows we need to check if we not remove the tools like pickaxe, shovel etc. as well. Player will do Tico tools anyway. Maybe the flint tools are the only gt tools (wrench, hammer, screwdriver etc. are not affected)
