### ISSUE TITLE
AE2FC Multi fluid storage cells accept filter for only one fluid

### ISSUE THREAD

**Issue by Filiz1** [GTNewHorizons/GT-New-Horizons-Modpack#12970]
### Your GTNH Discord Username

Filiz

### Your Pack Version

2.3.0

### Your Server

unofficial

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Multi fluid storage cells accept filter for 5 fluids as indicated in their description.

### The Reality

Multi fluid storage cells accept filter only for one fluid as red AE2FC storage cells.

### Your Proposal

Fix for according to their purpose.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ydrec** [comment]
This also affects single fluid cells, if partitioned to 2+ fluids it would only filter based on one.
Expectations: It would be able to take in either if it was initially empty
