### ISSUE TITLE
ME fluid storage bus priority ignored after restarts

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12975]
### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

After a server restart the priority set in ME fluid storage busses is ignored until the bus is replaced.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
Cannot reproduce in SP, so we'll need more details about the setup.

**Comment by Tommeh1** [comment]
> Cannot reproduce in SP, so we'll need more details about the setup.

They were all set to insert directly into input hatches, and all failed after restarts, there ain't much special about the setups given that it are all small subsystems.
