### ISSUE TITLE
AE2FC fluid terminal show thaumcraft essentias besides fluids

### ISSUE THREAD

**Issue by Filiz1** [GTNewHorizons/GT-New-Horizons-Modpack#12971]
### Your GTNH Discord Username

Filiz

### Your Pack Version

2.3.0

### Your Server

unofficial

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

AE2FC fluid terminal show only fluids because it's FLUID terminal.

### The Reality

AE2FC fluid terminal shows near 64 unnecessary thaumcraft esentias that becomes work with fluids in terminal much more difficult and uncomfortable.
After all, for essentias there is their own terminal.

### Your Proposal

Remove representation of essentias from AE2FC fluid terminal.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Runakai1** [comment]
I think that was intended. I remember talking to the ae2fc dev about this. Iirc there is a config (and an in-game card) to disable all fluid drops

**Comment by Filiz1** [comment]
It's not about fluid drops, it's about only essentias, which shouldn't be in FLUID terminal.

**Comment by firenoo** [comment]
Will look into it, but it'll be a toggleable setting like how the normal term does drops and items

**Comment by EnderProyects** [comment]
I don't think that essentias should be removed from fluid drops, is a great way to encode essentia for infusions and other recipes
