### ISSUE TITLE
EEC missing most recipes in 2.3.1

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#12979]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.1

### Your Server

zeta

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

eec works well like before.

### The Reality

eec has only 60 recipe left, most of them are not even complete. for ex, skeleton does not even have a recipe.
screenshots are taken in zeta server.

![image](https://user-images.githubusercontent.com/49871378/226498925-069ea307-c562-4c1c-b1c6-0c9261b44252.png)
this is a skeleton spawner, invalid. used to be valid.
![image](https://user-images.githubusercontent.com/49871378/226498947-efab2b90-b6a7-4848-ba0d-21e2e36f09f5.png)
60 recipe. the lava monstor should have at least sth in the recipe but no.

### Your Proposal

check the code, i have no idea where to look or how to fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@miaowwwwww 
test this version
<https://github.com/GTNewHorizons/KubaTech/releases/tag/0.9.3>
Zeta is on 2.3.1 + newer BQ files. MAybe i update other files as well.

**Comment by Dream-Master** [comment]
@miaowwwwww did it work with 0.9.3 version ? or is there so difference between 0.9.2 in sp ?
