### ISSUE TITLE
Crashing to main menu on world load

### ISSUE THREAD

**Issue by draaac** [GTNewHorizons/GT-New-Horizons-Modpack#12986]
### Your GTNH Discord Username

Drac#3479

### Your Pack Version

2.3.1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

Loaded world. I assumed the issue is the object submission station, based on a low-knowledge check of the crash report; removing it afterwards in 2.3.0RC1 and then loading the world in 2.3.1 fixed it. If you want any more info or logs, please @ me on discord. Prior version was 2.3.0 RC1.

### Crash Report

[crash-2023-03-22_03.22.27-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11029681/crash-2023-03-22_03.22.27-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by D-Cysteine** [comment]
Thanks for the report! Should be fixed by:
 * https://github.com/GTNewHorizons/BetterQuesting/pull/92/commits/6206e2d5547e13cbf1dcab3f7d9ab206639988b0

**Comment by Dream-Master** [comment]
@draaac 
test with this build
<https://github.com/GTNewHorizons/BetterQuesting/releases/tag/3.3.4-GTNH-pre>

**Comment by D-Cysteine** [comment]
Should now be fixed in dev
