### ISSUE TITLE
Crash when I attempt to move quest lines up

### ISSUE THREAD

**Issue by 905Sunny** [GTNewHorizons/GT-New-Horizons-Modpack#12985]
### Your GTNH Discord Username

905Sunny#9728

### Your Pack Version

2.3.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

Clicking the button that is highlighted in screenshot below

![2023-03-21_21 00 10](https://user-images.githubusercontent.com/44795811/226613527-83eb789c-3a56-4d99-bff6-6a198f9d520d.png)

### Crash Report

[crash-2023-03-21_20.54.42-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11028546/crash-2023-03-21_20.54.42-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by D-Cysteine** [comment]
Thanks for the report! Should be fixed by:
 * https://github.com/GTNewHorizons/BetterQuesting/pull/92/commits/d195cfad030a9a4f03d9af722ead13f973dd54f4

**Comment by Dream-Master** [comment]
@905Sunny 
this with this build
<https://github.com/GTNewHorizons/BetterQuesting/releases/tag/3.3.4-GTNH-pre>

**Comment by D-Cysteine** [comment]
Should now be fixed in dev
