### ISSUE TITLE
Small typo in quest book

### ISSUE THREAD

**Issue by nikolaK78** [GTNewHorizons/GT-New-Horizons-Modpack#12981]
### Your GTNH Discord Username

YourDesire#4628

### Your Pack Version

2.3.0-1.7.1.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Attempt instead of attept

### The Reality

A small typo in "Robotic Crop Pickers" quest at "Fishing, Farming, Cooking" section.
![Untitled](https://user-images.githubusercontent.com/115399438/226508952-f2618e9f-7b70-41a9-bcc5-db9f0eb2afd0.png)

### Your Proposal

Fix the small typo. :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/13004
Sorry, forgot to mention and link it.
