### ISSUE TITLE
Trojan Detected when downloading server and client files

### ISSUE THREAD

**Issue by esoop1** [GTNewHorizons/GT-New-Horizons-Modpack#12998]
### Your GTNH Discord Username

Esoop#7035

### Your Pack Version

2.3.0, 2.3.1 java 8 client

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

When downloading the files, windows defender freaks out
![image](https://user-images.githubusercontent.com/23713775/226997188-f8acf1f5-8b18-4c5a-b1eb-68bd5f826481.png)
![image](https://user-images.githubusercontent.com/23713775/226997926-8cc6744e-bedd-4906-9874-5b1ce8b95338.png)

Its the same for all the 2.3.0 files, as well as the 2.3.1 java 8 client file

### Crash Report

Irrelevant

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
also had 2 other reports for the 2.3.1 java17-19 (though it doesnt happen for me currently):
https://discord.com/channels/181078474394566657/234936569360809996/1087154665956851783
https://discord.com/channels/181078474394566657/241133365489696768/1087727711021183057

**Comment by esoop1** [comment]
Me neither, the 2.3.1 ones are fine, save for the one I listed

**Comment by boubou19** [comment]
:concern: What is the specific file causing the issue?

**Comment by esoop1** [comment]
Were not sure, as shown in provided images it will only display the zip file. I'm not a very inovative person so I don't know how too dive into it, maybe someone with a better grasp on windows defender could work it out?

**Comment by esoop1** [comment]
I tested again just too be sure and it still occurs on my end, Interesting. I have OS build 19045.2728 of windows 10 if it matters

**Comment by AtomicGrog** [comment]
Just did a deep scan of same file after downloading, using mcafee with latest dat file (22/3/2023) and it showed up nothing.

Thoughts:

1. Your scanner picked up a trojan others haven't
2. Your scanner falsely detected a signature as a trojan (we had same issue back at 2.2.3 iirc)
3. Your already infected and this got infected on download

I'd run a deep scan of your whole machine just in case it's 1 or 3.

**Comment by Blade8895** [comment]
Reported to Microsoft and they corrected the false positive scan.

![Screenshot_20230326_133034_com.android.chrome.jpg](https://user-images.githubusercontent.com/76847661/227772845-80b62e23-a5d0-4182-b8a6-5e74e7222d23.jpg)

![Screenshot_20230326_133028_com.android.chrome_edit_540096875480085.jpg](https://user-images.githubusercontent.com/76847661/227772846-cc50d341-9c87-4326-8bd4-b0faa5a974e8.jpg)

**Comment by chochem** [comment]
is this still an issue for anyone or did microsoft fix it?
