### ISSUE TITLE
Steam cracking butene guarantees power loss

### ISSUE THREAD

**Issue by Kyrorichekku** [GTNewHorizons/GT-New-Horizons-Modpack#12993]
### Your GTNH Discord Username

kyori#4690

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

steam cracker (powered by 2 **full** amps of EV) to be able to run the 240 eu/t (hv) steam cracking recipes  with hss-s coils (yes I know this is overkill but I had them leftover from another project)

### The Reality

oil cracker powers off immediately due to power loss regardless of how much energy it is fed whether under clocked (due to eu discount) or over clocked

**some notes:**

1. testing was done anywhere from (kanthal coil with HV power to ensure no clocking over/under was going on ) to (hss-s coils with IV power) all had the same result of shutting down due to power loss despite being fully powered and 162 billion eu stored at the source and more amps than my base could ever use (and while putting none of them to use for anything else) yet the result is all the same

2. no structural issues

3. no maintenance issues 

4. tests were repeated over all levels of stream cracking (light, moderate, severe) all shared the same end result of shutting off due to power loss

5. I'm using similar recipe with the the exact same power requirements (lightly steam cracked light fuel), power source, and configuration of oil cracker and it works with no issues at all (though not running at the same time for the sake of clarity in testing)

Edit #1: (additional info)

6. I've experienced a similar issue one other (gregtech) multiblock the large chemical reactors where they randomly shut down from power loss despite having more than enough power (often with similar resulting cannot turn on despite being fully powered with no other issues, often not even reporting having turned off from power loss) 

7. at times replacing the controller fixes the problem while at other times it consistently does not fix the problem 

8. can occur on a multi block that is neither across chunk boundaries that was never in an unloaded chunk (and within the same play session obviously)

9. can occur in multiblock that were previously working and though it is somewhat conjecture seems to be far less common in already built multiblock 

10. this problem is **very frequent** in my **large base** to be happening somewhere but is uncommon on a per multiblock basis 

11. shut off often occurs (on further attempts to turn on as well) when fully maintained with energy buffer full and no active recipe (which it should have no reason to choke when not consuming power)

### Your Proposal

correct whatever EU calculation is breaking it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
@BlueWeabo this is fixed in dev right?

**Comment by Kyrorichekku** [comment]
a bit of an update, after curiously realizing another oil cracker (in the same chunk) was also not working I'd decided to re-place the controllers (on a whim) and re-maintenance them 

afterwards they worked perfectly as intended so not quite sure what to make of it but the settings were simply as-is exactly as they were before when I picked them up other than needing to re-add the circuit to the controller 

definitely something wrong but perhaps not quite what I thought it was
