### ISSUE TITLE
Questbook does not update after completing quest

### ISSUE THREAD

**Issue by RambonL** [GTNewHorizons/GT-New-Horizons-Modpack#12994]
### Your GTNH Discord Username

Rambon L#7474

### Your Pack Version

2.3.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I am using the PrisimLauncher and downloaded the pack from the official site (same for the server files). I am expecting the questbook to track my quest in real time.

### The Reality

after completing the quest i have to relog so that the questbook shows the quest to be completed and shows me the next quests

### Your Proposal

check if this is really a mod bug or something else

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@RambonL 
test with this version
<https://github.com/GTNewHorizons/BetterQuesting/releases/tag/3.3.4-GTNH-pre>
