### ISSUE TITLE
Machine Light Overlay Issue with Texturepacks

### ISSUE THREAD

**Issue by UnknownTimelord** [GTNewHorizons/GT-New-Horizons-Modpack#12999]
### Your GTNH Discord Username

skibbidiwapapow#3185

### Your Pack Version

2,3,0

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I loaded a texture pack, expected the machine textures to be completely replaced

### The Reality

I instead was greeted with [overlapping textures](https://imgur.com/a/1Ixmnb9).

### Your Proposal

Make it so the light overlay for machines is properly replaced

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
This is something the texture pack maker has to fix on his end. Please report this to the texture pack repo instead.
