### ISSUE TITLE
Crash on various inventory interactions

### ISSUE THREAD

**Issue by CrunchyCol** [GTNewHorizons/GT-New-Horizons-Modpack#13000]
### Your GTNH Discord Username

CrunchyCol#4403

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

Has happened various times, usually when interacting with a tile entity (this time I was putting items into a JABBA barrel) or looking up something in NEI while in the UI of a machine. Has happened at least 3 times but I'm unable to reproduce it on purpose. This is new since I updated to 2.3.0 but I'm unsure if it's something I messed up with the transfer of files in MultiMC or something else.

### Crash Report

[crash-2023-03-22_16.51.57-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11044739/crash-2023-03-22_16.51.57-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by tolin99** [comment]
[crash-2023-03-22_17.22.38-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11045064/crash-2023-03-22_17.22.38-client.txt)

Crashed again when right clicking books onto a bibliocraft printing press. Error appears to be the same.

**Comment by trollolal** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12996
Not sure if it is the same issue
