### ISSUE TITLE
HV Semi-fluid generator recipe requires IV ABS for Inconel-625

### ISSUE THREAD

**Issue by kevin-wackman** [GTNewHorizons/GT-New-Horizons-Modpack#13002]
### Your GTNH Discord Username

Admiral#1878

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

I expect to be able to craft the generators of the tier while in the tier.  I can craft an MV semi-fluid generator in MV, and I can craft an EV semi-fluid generator in EV.  The quests also encourage you to craft a semi-fluid generator to power your distillation tower, so it definitely expects you to be able to do so.

### The Reality

The Inconel-625 gears (which are part of the recipe) are not craftable without using the ABS.  The dust can be smelted in the EBF, but there is no mixer recipe for the dust (unlike the gears required for EV).

### Your Proposal

Either Inconel-625 dust should be craftable in a tier-appropriate (HV or below) mixer, or a different material should be chosen for the gears in the recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
guess Ill do it then, 2 months is a long time
