### ISSUE TITLE
book parts

### ISSUE THREAD

**Issue by beaven233** [GTNewHorizons/GT-New-Horizons-Modpack#13018]
### Your GTNH Discord Username

beaven233

### Your Pack Version

2.3.0 and 2.3.1

### Your Server

sp

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Was going to make wood pulp to make paper 
 

### The Reality

when going through the quest book i got to the book parts quest and found that there is no early game way to make wood pulp and in the quest it said that sugar cane can not be used to make paper but when i went to look at the paper recipe there was only 2 ways to make it 1 way with sugar cane and the other one was not with wood pulp

### Your Proposal

try and fix the recipe to get past the quest.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you are just wrong and people already send you screenshots on discord and you ignored them.
