### ISSUE TITLE
Extracells migration: interface

### ISSUE THREAD

**Issue by player5** [GTNewHorizons/GT-New-Horizons-Modpack#13011]
### Your Pack Version

2.3.1

### Your Server

Private ultramine

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Trying to convert extracells interface (plated) to AE2FC interface.

### The Reality

No recipe for that/ for craft block interface.

### Your Proposal

Add convertion recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
Automatic conversion is now implemented in dev
