### ISSUE TITLE
High TPS usage by Yotta hatch

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13014]
### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

All of the sudden Yotta hatches are using a considerable chunk of the entire server thread:
![image](https://user-images.githubusercontent.com/39203645/227403790-49ef6c00-2ddb-4bfe-82da-7223f1cff6ea.png)
[Snapshot.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11057766/Snapshot.zip)

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment]
This can be mitigated on the user's end by putting yotthatches on subnets instead of main net, but it is still worth looking into if it may be optimized further.

**Comment by Tommeh1** [comment]
> This can be mitigated on the user's end by putting yotthatches on subnets instead of main net, but it is still worth looking into if it may be optimized further.

We have maybe 5 of those hatches at best

**Comment by joshaup1999** [comment]
Are they on a subnet or not? Subnetting them majorly reduces the load they cause. I have no issue on 2.3 and i have like 20 of them going

**Comment by firenoo** [comment]
This is caused by the yott hatches posting updates every tick to open terminals, and the majority of the cpu time you see there is from sending ME inventory updates over the network. I assume AE2 has a better way of handling updates across subnets, which is probably why that reduces lag drastically.

On the client side, you are probably getting flooded by packets. This should be fixed on GoodGenerator's side.

**Comment by Tommeh1** [comment]
Now that's we've updated to 2.3.2 the server is especially mad at them 
![image](https://user-images.githubusercontent.com/39203645/229678999-0458b8c1-d74a-4f09-83cb-a1d76915cf06.png)

**Comment by Tommeh1** [comment]
No matter what, we can't get them to perform decently in the slightest 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/39203645/30c61ee4-98fb-4b65-bf1a-2d4406f0016a)
