### ISSUE TITLE
Advanced Assembly Line underclock

### ISSUE THREAD

**Issue by pulsemageadvocate** [GTNewHorizons/GT-New-Horizons-Modpack#13026]
### Your GTNH Discord Username

pulsemageadvocate

### Your Pack Version

2.3.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Make Dyson Swarm Ground Unit using Advanced Assembly Line with UIV 16A Energy Hatch.
It consumes 32,000,000 EU/t over 120 seconds.
![20230325_1](https://user-images.githubusercontent.com/59131259/227711226-c03a580a-7b17-4849-baa8-1783056f7200.jpg)

### The Reality

It consumes 8,000,000 EU/t over 240 seconds.
![20230325_2](https://user-images.githubusercontent.com/59131259/227711253-9f4b814a-a938-49d6-ae86-11174ad5bd55.jpg)
![20230325_3](https://user-images.githubusercontent.com/59131259/227711750-0ad8725c-e001-4b6d-b880-d5924a39b792.jpg)

With normal UIV Energy Hatch it still consumes 8,000,000 EU/t over 240 seconds.
![20230325_4](https://user-images.githubusercontent.com/59131259/227712464-34be0617-eb1b-421b-9a97-8452cc9b77ba.jpg)

It doesnt run with UEV 64A Energy Hatch / normal UEV Energy Hatch.
Normal Assembly Line with UEV Energy Hatch fails immediately.

### Your Proposal

No underclock.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
This points into problems in super class. `gregtech.api.metatileentity.implementations.GT_MetaTileEntity_ExtendedPowerMultiBlockBase#calculateOverclockedNessMultiInternal` has a mysterious 5% headroom for "cable loss". I have no idea why it need to consider cable loss here. For now I'll use the new overclock calculator instead of the crappy one from super class, but eventually we need to look into this base class method for a fix across the board.
