### ISSUE TITLE
Crash generating new chunks in twilight forest

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#13033]
### Your GTNH Discord Username

KiloJoel#3044

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

Flew around in the twilight forest generating new chunks

### Crash Report

[crash-2023-03-25_16.26.20-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11069411/crash-2023-03-25_16.26.20-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
Awesome, a crash on a modern java version that gives a more insightful NPE
```
java.lang.NullPointerException: Cannot invoke "java.util.Random.nextFloat()" because "this.field_76813_b" is null
    at twilightforest.biomes.TFBiomeDecorator.func_150513_a(TFBiomeDecorator.java:162)
    ```

**Comment by mitchej123** [comment]
Still not obvious why it's null... 😡

**Comment by Glease** [comment]
patterns like this is probable why
![image](https://user-images.githubusercontent.com/4586901/227731716-d6f3f5eb-3caf-4d49-820d-dc40d97f4651.png)

**Comment by mitchej123** [comment]
Might just remove that setting to null?  I traced through the calls as best I could and didn't see a specific place that set it to null prematurely, but clearly missed something...

**Comment by mitchej123** [comment]
Hmm, could also just drop a log with a stacktrace when it's set to null and see where it's doing it prematurely... 🤔   Don't recall seeing any nested calls, but haven't looked at it in 6mo+

**Comment by Glease** [comment]
A bandaid patch would be to save `randomGenerator` to a local variable at the start of genDecorations and use that instead, though I have no idea how this will change the terrain gen and might cause all sorts of terrain glitch
