### ISSUE TITLE
Compressed Chest will not Autofill Recipes in Tinker's Crafting Table

### ISSUE THREAD

**Issue by BEEF-Gaming** [GTNewHorizons/GT-New-Horizons-Modpack#13034]
### Your GTNH Discord Username

ShrooMoo#4546

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Placed a compressed chest next to Tinker's Crafting Table, filled it with items, and shift clicked a recipe to autofill the crafting grid.

### The Reality

Recipes will not autofill the crafting grid from a compressed chest. They will from normal chest, chests from the Iron Chests mod, slightly larger chests, etc.

### Your Proposal

As it is a high tier chest, would be amazing to shift click recipes, as can be done with all other chests.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Astonyen** [comment]
I have the same problem. It would be awesome if this was fixed.

**Comment by Dream-Master** [comment]
There is no mod compat I guess

**Comment by Pxx500** [comment]
I would love to see this fixed if possible, would make crafting so much better

**Comment by skinke17** [comment]
Can we get an update on this please?
