### ISSUE TITLE
AAL(Advanced Assembly Line) slice stuck after server restart

### ISSUE THREAD

**Issue by 5lx** [GTNewHorizons/GT-New-Horizons-Modpack#13044]
### Your Pack Version

2.3.0

### Your Server

Modded Minecraft Club

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

I'm trying to use AAL to craft Bio UHV circuit (Bioware Supercomputer).
It worked well at the beginning, but after server restart, AAL slice 1-9 was stuck.
I'm expecting the AAL works well after the server restart

### The Reality

Based on the stuck slice number, I think this may because of the 10th ingredient is an ore dict item, which means I can use both Thin Silicon Rubber Sheet (default) and Thin Styrene-Butadiene Rubber Sheet.
I'm using SB Rubber to craft, and after server restart, seems the AAL pending slice switched to Si Rubber to craft.
I resolve the stuck by manually feeding Si Rubber to finish all the pending AAL crafting.

### Your Proposal

Please have a check if this is the root cause, and fix the AAL slice recipe checking logic that could handle ore dict item well after  server reboot.

Thanks

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
can't reproduce. also I'm unable to find a way for this to happen code wise

**Comment by 5lx** [comment]
I also reproduced this in single player game. You need to restart the Minecraft. Quite to title is not enough.
![2A9MQ}MREZ(450H~({%}JBJ](https://user-images.githubusercontent.com/6583339/227762180-a4da7b69-11ef-4d20-818e-26befc1377a5.png)

**Comment by Glease** [comment]
I still cannot replicate this, but I found something that might relate to this. Check if this build fix your problem http://jenkins.usrv.eu:8080/job/GigaGramFab/52/artifact/build/libs/ggfab-0.2.0-1-gb49007a.jar

**Comment by 5lx** [comment]
The provided ggfab build fixed the problem. Now the recipe won't stuck after restart.
