### ISSUE TITLE
Add more and bigger crafting storage to AE

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#13053]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.3.1

### Your Proposal

Add more and larger crafting storage to AE, such as compressed 16384K  crafting storage, or 65536K crafting storage, in increasing order, or perhaps use digital singularities as crafting storage

给AE添加更多更大的合成单元，例如压缩的16384K合成单元，或者65536K合成单元，依次递增，或许把数字奇点拿来做合成单元也可以

### Your Goal

In the late game 16384K has been unable to meet the needs of most of the recipes, such as the stargate and EOH shell and other items, in the future there may be more large machines, we need some larger crafting storage units

在游戏后期16384K已经无法满足大部分配方的需求了，例如星门以及EOH的外壳等物品，在未来或许还会有更多大型机器，我们需要一些更大的合成存储单元

### Your Vision

Less space and more efficient use, and we no longer need to go to batch orders for various machines

更少的占地与更高效的利用，而且我们再也不需要去分批下单各种机器了

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
they already exist

**Comment by chochem** [comment]
oh crafting storage. thanks glease for correcting the title or we would not stand a chance

**Comment by Tommeh1** [comment]
I would like to also suggest even larger co-processing units to go with it.

**Comment by LewisSaber** [comment]
I would like you to show us screen where u have 0 operations left while using biggest co-processors

**Comment by TheEpicGamer274** [comment]
co-processing units cause way too much lag when used in mass amounts
if they have not changed

**Comment by Tommeh1** [comment]
> co-processing units cause way too much lag when used in mass amounts if they have not changed

Yet larger ones of those will also be needed.
You don't want machines sitting idle because AE2 just hasn't send stuff over yet.

**Comment by TheEpicGamer274** [comment]
I've had 30ms increase because of 16 core-proc spam, its not very good

**Comment by greesyB** [comment]
Co-processors are unrelated to this issue, but regardless there is not a chance that anyone actually needs more than the already existing 4096 core ones.

**Comment by Tommeh1** [comment]
> Co-processors are unrelated to this issue, but regardless there is not a chance that anyone actually needs more than the already existing 4096 core ones.

With how heavy our processing is we could easily use that, once we overhaul our 64 existing CPUs.
And yes, AE2 handling crafting jobs is very heavy.

**Comment by greesyB** [comment]
You could trivially reach nearly 50k co-processors with only 12 4096 units. I don't care how expansive your base is, you do not have 50k interfaces for AE to want to use at once.

**Comment by TheEpicGamer274** [comment]
and even still I have a feeling that it would cause more lag than needed

**Comment by Tommeh1** [comment]
> You could trivially reach nearly 50k co-processors with only 12 4096 units. I don't care how expansive your base is, you do not have 50k interfaces for AE to want to use at once.

A single task, via a single interface can easily eat dozens of Co-processing units.

**Comment by TheEpicGamer274** [comment]
for me atleast, my crafts are rarely bottlenecked by co-proc and more by speed of machines/interface input speed

**Comment by Tommeh1** [comment]
We're currently planning CPUs to handle things like 168 Infinite Spacetime Energy Boundary Casings, this will be quite tedious with how tiny both are currently.

**Comment by firenoo** [comment]
I agree with Greesy here. There is no need to add a larger co-processor. Again, this issue is for crafting storage.

In fact, I'd suggest instead of adding larger and larger storage since we'll run into the same problem in the future again, just make a creative crafting storage of sorts that bypasses the byte restriction.

**Comment by Tommeh1** [comment]
I guess it will be 1 crafting storage with a few dozen co processors attached then.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13537
