### ISSUE TITLE
Better ME automation of Thaumcraft Infusion and Crucible recipes

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/GT-New-Horizons-Modpack#13051]
### Your GTNH Discord Username

monroth#4236

### Your Pack Version

2.3.1

### Your Proposal

When you record patterns for infusion or crucible in fluid terminal, it just puts item as ingredients. I suggest that it would also place essentia gas equivalent of needed essentia (so, if infusion needs 10 metallum, it would place 1280 metallum gas as it's ingredient).   Or in any way make it possible to enter essentia automatically and not by hand.

### Your Goal

This will make autocrafting with essentia as easy as is autocrafting with fluids/

### Your Vision

With distillation pattern encoder it was always possible to autocraft essentia in Thaumic energistics. By this I mean it was always possible to make autocraft recipes of type "item -> essentia". Now, with AE2FC it is now possible to do it in other direction and autocraft something FROM essentia by putting it's gas equivalent in fluid patterns. Main issue that unlike almost all other usages of AE, it severely lacks NEI support, and creating such patterns by hand is annoying.

I understand that this is a gimmicky solution, and in theory essentia should not be interpreted as fluids, but i think we need to have an option to autocraft with essentia and now we have it. It would probably be better to write some kind of addon to TE that adds smth like essentia pattern terminals, but that addon would need a lot of work, because current thaumic energistic essentia provider wants you to have all essentia in main network and don't have much support of subnetwokks. However, I suppose that my supposed solution, although gimmicky, will be substantially easier to implement and will give almost same feeling and functionality.

Main disadvantage of this solution is that usage of such patterns would need rework of current system if you were using item only patterns before --- for instance, essentia would be taken from main network for the recipe, and your essentia\infusion provider would need to be on a subnet that receives this essentia in gas form. But ME automation of infusions already needs some work, this would not make it much more complex to implement. Even if you don't want to change your setup
A) You can always use regular AE pattern\processing terminal,
B) You can always just click 5-6 times to remove all liquids --- it is infinitely easier than the other way, calculating correct gas amount by hand and entering them manually,
C) I suppose that button that make this behavior optional is easy to implement too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
The gas has been disabled in the latest dev, and will not be in the packs in future stables, this is impossible, I am sorry
