### ISSUE TITLE
New Clickable URL in questbook does not work properly

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#13050]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.3.2

### Your Server

sp

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

you should click on the text that has the link.

### The Reality

the clickable field is somewhere else entire, not visible, and very small. But they exist! I tried to mark them but this is not a precise science. I am sure they are rectangular at least:

On 'large' GUI (which I normally use)
![image](https://user-images.githubusercontent.com/40274384/227815464-e0f44033-debb-4247-a0b2-46e85b5dad20.png)

On 'normal' GUI:
![image](https://user-images.githubusercontent.com/40274384/227815514-2075e61f-b46d-450e-b758-79ce1254efa7.png)

some more info that might or might not be relevant:
BQ version: 3.3.8
resolution/window: 4k screen, maximized window
added mods: notfine, archaic fix, neodymium (no FC/OF) 

the specific lines in the questfile are:
`head on over to §1§n[url]https://gtnh.miraheze.org/wiki/Electricity[/url]§r to read more.`

### Your Proposal

Fix the clickable area

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by D-Cysteine** [comment]
Just to save a little time, here's a quick snippet to highlight affected area:

```java
        for (HotZone hotZone : hotZones) {
            RenderUtils.drawHighlightBox(hotZone.location, new GuiColorStatic(255, 255, 0, 127));
        }
```

<https://discord.com/channels/181078474394566657/949447391587733504/1089712129914966146>

**Comment by chochem** [comment]
thanks. now proper pictures. I wasnt very close:
GUI large:

![image](https://user-images.githubusercontent.com/40274384/227816668-50d90c0d-4f1e-4a38-a033-49b80e53ed9a.png)

GUI normal:
![image](https://user-images.githubusercontent.com/40274384/227816715-5fae5b3a-bce4-4a53-b860-4c4648f4139f.png)

**Comment by chochem** [comment]
this is not fixed

**Comment by chochem** [comment]
@Glease 

![image](https://user-images.githubusercontent.com/40274384/235300205-fe7919d6-2ac3-4d47-ab99-a3c09aa5d309.png)
