### ISSUE TITLE
Optifine not compatible with 2.3.2, with Fastcraft 1.25

### ISSUE THREAD

**Issue by Holit** [GTNewHorizons/GT-New-Horizons-Modpack#13059]
### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Display normally and nicely as GTNH 2.2.0.0 did.

### The Reality

It went all black and when I looking at them, Minecraft GUI crashed into single color screen.
There are too many display exceptions. Including chests rendering error, blocks error, entity rendering error, even quest book also went crazy.
By the way, single color screen also occurred  after uninstalling Optifine HD.

[Video](https://streamable.com/fhxc0t)
Please check this as soon as possible. Video expires 1 day.

![image](https://user-images.githubusercontent.com/20926583/228004682-8c5b7b90-8c3c-45af-96fe-5c70e8ccd7e4.png)
![image](https://user-images.githubusercontent.com/20926583/228004729-84e26265-3363-4fc3-af58-ab732e59087c.png)
![image](https://user-images.githubusercontent.com/20926583/228004837-6e35cd95-9826-48af-96e6-ce20cdfc73de.png)
![image](https://user-images.githubusercontent.com/20926583/228004869-88dbeb91-b06a-44aa-a734-3f586e6c44fd.png)
![image](https://user-images.githubusercontent.com/20926583/228004949-8a40445a-eaf0-49f7-9d2b-79efe3dd16b6.png)
![image](https://user-images.githubusercontent.com/20926583/228004983-a8585aff-7933-4410-ba49-79d9f97dfb4c.png)
![image](https://user-images.githubusercontent.com/20926583/228005046-72a0a4e1-1559-4d33-9330-ee8e2be32aea.png)

### Your Proposal

...
(╯‵□′)╯︵┻━┻

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
which version(s)?

1.23 and D6 work, 1.25 and E7 work, afaik.

**Comment by Holit** [comment]
Guys this bug just amused me a lot, seems my minecraft went mad completely.
Sorry for this informationless comment lol.

**Comment by chochem** [comment]
any chance you are using an intel gpu?

other people on discord report 2.3.2+fc25+OFE7 works just fine. so the problem is likely elsewhere

**Comment by Holit** [comment]
Inter UHD Rendering:
![屏幕截图(105)](https://user-images.githubusercontent.com/20926583/228127971-7fe179cf-2ddd-40db-beda-4acbd2023258.png)
![屏幕截图(104)](https://user-images.githubusercontent.com/20926583/228127973-433290fe-bd6c-49f6-bb28-f662c5c79f98.png)
-----
NVIDIA Rendering:
![屏幕截图(106)](https://user-images.githubusercontent.com/20926583/228128548-343351ec-50c9-4eea-85c3-a6c401bbfd1e.png)
@chochem You are correct, I would apologize for wasting your time.

**Comment by chochem** [comment]
If you actually want to play with the intel gpu you can try adding the neodymium mod. ( neodymium-1.7.10-0.1.8+nomixin.jar from https://github.com/makamys/Neodymium/releases). Lot's of people have confirmed that that works.

**Comment by Holit** [comment]
> If you actually want to play with the intel gpu you can try adding the neodymium mod. ( neodymium-1.7.10-0.1.8+nomixin.jar from https://github.com/makamys/Neodymium/releases). Lot's of people have confirmed that that works.

Thanks a lot, that helps!
