### ISSUE TITLE
2.3.2 Crash in Java20

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#13063]
### Your GTNH Discord Username

Hiakri1nVoid#9527

### Your Pack Version

2.3.2

### Your Server

zeta

### Java Version

Other versions in between

### Type of Server

None

### Your Actions

Launching the GTNH with Java 20(Since in announcement DM said Java17-20 so tried it)

### Crash Report

MultiMC version: 0.6.16-3431

Launched instance in online mode

authserver.mojang.com resolves to:
    [13.35.76.41, 13.35.76.65, 13.35.76.43, 13.35.76.50]

session.minecraft.net resolves to:
    [13.107.253.35, 13.107.226.35]

textures.minecraft.net resolves to:
    [13.107.253.35, 13.107.226.35]

api.mojang.com resolves to:
    [13.107.253.35, 13.107.226.35]

Minecraft folder is:
E:/MultiMC/instances/GT_New_Horizons_2.3.2_Java_17-20/.minecraft

Java path is:
C:/Program Files/Java/jdk-20/bin/javaw.exe

Checking Java version...
Java is version 20, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  E:/MultiMC/instances/GT_New_Horizons_2.3.2_Java_17-20/natives

Libraries:
  E:/MultiMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.2-SNAPSHOT-10/lwjgl-glfw-natives-windows-x86-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.2-SNAPSHOT-10/lwjgl-glfw-natives-windows-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.2-SNAPSHOT-10/lwjgl-glfw-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.2-SNAPSHOT-10/lwjgl-jemalloc-natives-windows-x86-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.2-SNAPSHOT-10/lwjgl-jemalloc-natives-windows-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2-SNAPSHOT-10/lwjgl-jemalloc-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.2-SNAPSHOT-10/lwjgl-natives-windows-x86-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-natives-windows/3.3.2-SNAPSHOT-10/lwjgl-natives-windows-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.2-SNAPSHOT-10/lwjgl-openal-natives-windows-x86-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.2-SNAPSHOT-10/lwjgl-openal-natives-windows-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.2-SNAPSHOT-10/lwjgl-openal-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.2-SNAPSHOT-10/lwjgl-opengl-natives-windows-x86-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.2-SNAPSHOT-10/lwjgl-opengl-natives-windows-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.2-SNAPSHOT-10/lwjgl-opengl-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.2-SNAPSHOT-10/lwjgl-stb-natives-windows-x86-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.2-SNAPSHOT-10/lwjgl-stb-natives-windows-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.2-SNAPSHOT-10/lwjgl-stb-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.2-SNAPSHOT-10/lwjgl-tinyfd-natives-windows-x86-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.2-SNAPSHOT-10/lwjgl-tinyfd-natives-windows-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2-SNAPSHOT-10/lwjgl-tinyfd-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/org/lwjgl/lwjgl/3.3.2-SNAPSHOT-10/lwjgl-3.3.2-SNAPSHOT-10.jar
  E:/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  E:/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  E:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  E:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  E:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  E:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  E:/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  E:/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  E:/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  E:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  E:/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  E:/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  E:/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  E:/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  E:/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  E:/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  E:/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  E:/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  E:/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  E:/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  E:/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  E:/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  E:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  E:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  E:/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  E:/MultiMC/libraries/com/github/GTNewHorizons/lwjgl3ify/1.3.3/lwjgl3ify-1.3.3-forgePatches.jar
  E:/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  E:/MultiMC/libraries/net/minecraft/launchwrapper/1.15/launchwrapper-1.15.jar
  E:/MultiMC/libraries/org/ow2/asm/asm/9.4/asm-9.4.jar
  E:/MultiMC/libraries/org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar
  E:/MultiMC/libraries/org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar
  E:/MultiMC/libraries/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar
  E:/MultiMC/libraries/org/ow2/asm/asm-util/9.4/asm-util-9.4.jar
  E:/MultiMC/libraries/org/ow2/asm/asm-deprecated/7.1/asm-deprecated-7.1.jar
  E:/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  E:/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  E:/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  E:/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  E:/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  E:/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  E:/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  E:/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  E:/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  E:/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  E:/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  E:/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  E:/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  E:/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  E:/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [✔️] AdvancedSolarPanel-1.7.10-3.5.1a
  [✔️] adventurebackpack-1.0.9-GTNH
  [✔️] ae2fc-1.1.5-gtnh-pre
  [✔️] ae2stuff-0.5.1.16-GTNH
  [✔️] AFSU-1.7.10-1.2.6-GTNH
  [✔️] AngerMod-1.7.10-0.6.3
  [✔️] AppleCore-3.2.10
  [✔️] appliedenergistics2-rv3-beta-184-GTNH
  [✔️] ArchitectureCraft-1.8.1
  [✔️] Aroma1997Core-1.7.10-1.0.2.16
  [✔️] AromaBackup-1.7.10-0.1.0.0
  [✔️] AsieLib-1.7.10-0.5.3
  [✔️] Automagy-1.7.10-0.28.2
  [✔️] Avaritia-1.34
  [✔️] Avaritiaddons-1.7.10-1.5.4-GTNH
  [✔️] backpack-2.2.9-GTNH
  [✔️] bartworks-0.6.5
  [✔️] battlegear2-1.2.0
  [✔️] Baubles-1.0.1.16
  [✔️] bdlib-1.7.10-1.9.8-GTNH
  [✔️] BeeBetterAtBees-0.3
  [✔️] BetterAchievements-1.7.10-0.1.3
  [✔️] BetterBuildersWands-1.7.10-0.9.6-GTNH
  [✔️] bettercrashes-1.2.0-GTNH
  [✔️] betterloadingscreen-1.3.39-GTNH
  [✔️] betterp2p-1.1.3
  [✔️] BetterQuesting-3.3.8-GTNH
  [✔️] BiblioCraft[v1.11.7][MC1.7.10]
  [✔️] BiblioWoods[BiomesOPlenty][v1.9]
  [✔️] BiblioWoods[Forestry][v1.7]
  [✔️] BiblioWoods[Natura][v1.5]
  [✔️] binnie-mods-1.7.10-2.0.48
  [✔️] BiomesOPlenty-1.7.10-2.1.0.2308-universal
  [✔️] BlockLimiter-1.7.10-0.55
  [✔️] blockrenderer6343-1.7.10-1.0.0-RC7
  [✔️] BloodArsenal-1.7.10-1.2.9
  [✔️] BloodMagic-1.3.25
  [✔️] Botania-1.9.16-GTNH
  [✔️] BotanicHorizons-1.7.10-1.0.14-GTNH
  [✔️] BrandonsCore-1.7.10-1.0.0.13-GTNH
  [✔️] bugtorch-1.2.7
  [✔️] buildcraft-7.1.31
  [✔️] buildcraft-compat-1.7.10-7.1.12
  [✔️] BuildCraftOilTweak-1.7.10-1.0.4
  [✔️] CarpentersBlocks-1.7.10-3.3.8.2-GTNH
  [✔️] catwalks-1.7.10-2.1.4-GTNH
  [✔️] chisel-2.10.17-GTNH
  [✔️] chiseltones-1.7.10-1.0.4-GTNH
  [✔️] CodeChickenCore-1.1.11
  [✔️] CoFHCore-[1.7.10]3.1.4-329
  [✔️] CompactKineticGenerators-1.7.10-1.0
  [✔️] Computronics-1.6.19-GTNH
  [✔️] controlling-1.0.0.5
  [✔️] CookingForBlockheads-1.2.14-GTNH
  [✔️] CraftPresence-2.0.0-beta.2+1.7.10
  [✔️] CraftTweaker-3.2.11
  [✔️] creativecore-1.7.10-1.3.27-GTNH
  [✔️] CropLoadCore-1.7.10-0.1.10
  [✔️] CropsPP-1.7.10-1.3.6.12
  [✔️] custommainmenu-1.7.10-1.9.4
  [✔️] defaultserverlist-1.7.10-1.4.0
  [✔️] defaultworldgenerator-1.7.10-0.2
  [✔️] Draconic-Evolution-1.1.15-GTNH
  [✔️] DummyCore-1.7.10-1.15
  [✔️] EMT-1.2.8.28
  [✔️] endercore-0.2.13
  [✔️] EnderIO-2.4.6
  [✔️] EnderStorage-1.7.10-1.4.12
  [✔️] EnderZoo-1.7.10-1.0.23
  [✔️] EnhancedLootBags-1.1.0
  [✔️] eternalsingularity-1.0.10
  [✔️] ExtraCells-2.5.33
  [✔️] extrautilities-1.2.13a
  [✔️] fastcraft-1.25
  [✔️] findit-1.1.0
  [✔️] FloodLights-1.7.10-1.2.9
  [✔️] Forbidden.Magic-0.6.6-GTNH
  [✔️] Forestry-4.6.0
  [✔️] forgelin-1.9.7-GTNH
  [✔️] ForgeMultipart-1.3.2
  [✔️] ForgeRelocation-1.7.10-0.0.3
  [✔️] ForgeRelocationFMP-1.7.10-0.0.4
  [✔️] gadomancy-1.0.8.9
  [✔️] galacticgreg-1.7.10-1.0.8
  [✔️] Galacticraft-3.0.67-GTNH
  [✔️] GalaxySpace-1.1.63-GTNH
  [✔️] gendustry-1.7.10-1.6.5.5-GTNH
  [✔️] ggfab-0.2.0
  [✔️] GoodGenerator-0.5.4
  [✔️] GraviSuite-1.7.10-2.0.3
  [✔️] gravisuiteneo-1.0.8
  [✔️] gregtech-5.09.42.15
  [✔️] GT.Scanner.Mod-1.7.0
  [✔️] gtneioreplugin-1.0.29
  [✔️] GTNewHorizonsCoreMod-2.0.6
  [✔️] gtnhintergalactic-1.0.6
  [✔️] gtnhlanth-0.9.30
  [✔️] gtnhlib-0.0.13
  [✔️] GTNH-TC-Wands-1.3.0
  [✔️] GT-PlusPlus-1.8.18
  [✔️] GTTweaker-1.7.10-1.7.5
  [✔️] HardcoreDarkness-MC1.7.10-1.7
  [✔️] HardcoreEnderExpansion-1.7.10-1.9.7-GTNH
  [✔️] harvestcraft-1.0.21-GTNH
  [✔️] Healer-1.2.0
  [✔️] HelpFixer-1.7.10-1.1.0
  [✔️] hodgepodge-2.2.4
  [✔️] holoinventory-1.7.10-2.1.19-GTNH
  [✔️] HungerOverhaul-1.7.10-1.0.4-GTNH
  [✔️] hydroenergy-1.0.19
  [✔️] IC2 Crop Plugin Version 1.7.10-1.3.1
  [✔️] IC2NuclearControl-1.7.10-2.4.16
  [✔️] ifu-1.7.10-1.9.5
  [✔️] IguanaTweaksTConstruct-2.2.9
  [✔️] industrialcraft-2-2.2.828a-experimental
  [✔️] InfernalMobs-1.7.10-1.7.7-GTNH
  [✔️] InGameInfoXML-1.7.10-2.8.3.96
  [✔️] INpureCore-1.1.5-GTNH
  [✔️] inventorytweaks-1.5.16
  [✔️] IronChest-1.7.10-6.0.71
  [✔️] IronChestMinecarts-1.7.10-1.0.8
  [✔️] irontanks-1.7.10-1.2.6
  [✔️] itlt-1.7.10-1.0.4
  [✔️] JABBA-1.2.22
  [✔️] journeymap-1.7.10-5.1.4p2-fairplay
  [✔️] kekztech-0.7.3
  [✔️] kubatech-0.9.5
  [✔️] littletiles-1.7.10-1.2.7-GTNH
  [✔️] logisticspipes-0.9.4.5.13-GTNH
  [✔️] lootgames-1.7.10-2.0.8
  [✔️] LunatriusCore-1.7.10-1.1.7-GTNH
  [✔️] lwjgl3ify-1.3.3
  [✔️] magicbees-1.7.10-2.5.16-GTNH
  [✔️] malisiscore-0.14.7-GTNH
  [✔️] malisisdoors-1.13.7-GTNH
  [✔️] Mantle-0.3.6
  [✔️] ModTweaker2-0.9.10
  [✔️] modularui-1.1.2
  [✔️] MouseTweaks-2.4.8-GTNH
  [✔️] MrTJPCore-1.7.10-1.1.4
  [✔️] mxrandom-0.1.6
  [✔️] Natura-1.7.10-2.5.5
  [✔️] naturescompass-1.7.10-1.3.6-GTNH
  [✔️] NEIAddons-1.7.10-1.12.22
  [✔️] NEICustomDiagram-1.5.1
  [✔️] NEIIntegration-1.3.0
  [✔️] netherportalfix-1.7.10-1.1.2
  [✔️] NettyPatch-1.7.10-0.3.1
  [✔️] NodalMechanics-1.7.10-1.1.-6-GTNH
  [✔️] NotEnoughEnergistics-1.4.0
  [✔️] notenoughIDs-1.7.10-1.4.6
  [✔️] NotEnoughItems-2.3.40-GTNH
  [✔️] oauth-1.7.10-1.06.1-GTNH
  [✔️] OpenBlocks-1.7.0-GTNH
  [✔️] OpenComputers-1.9.0-GTNH
  [✔️] OpenGlasses-1.7.10-1.2.5-GTNH
  [✔️] OpenModsLibs-1.7.10-0.10.6
  [✔️] OpenModularTurrets-1.7.10-2.2.11-247
  [✔️] openprinter-1.7.10-0.1.3-GTNH
  [📁] OpenSecurity (folder)
  [✔️] opensecurity-1.7.10-1.0.120-GTNH
  [✔️] Opis-1.7.10-1.3.8-mapless
  [✔️] overloadedarmorbar-1.7.10-1.0.1
  [✔️] p455w0rdslib-1.7.10-1.0.4
  [✔️] Pam's Harvest the Nether 1.7.10a
  [✔️] personalspace-1.0.24
  [✔️] PlayerAPI-1.7.10-1.4.2
  [✔️] ProjectBlue-1.7.10-1.1.8-GTNH
  [✔️] ProjRed-1.7.10-4.7.9-GTNH
  [✔️] Railcraft-9.14.0
  [✔️] RandomThings-1.7.10-2.4.3
  [✔️] RemoteIO-1.7.10-2.4.8
  [✔️] roguelike-1.7.10-1.5.3-GTNH
  [✔️] RWG-1.7.10-alpha-1.3.3.2
  [✔️] Schematica-1.9.3-GTNH
  [✔️] SGCraft-1.7.10-1.3.13-GTNH
  [✔️] sharewhereiam-1.7.10-0.2.0
  [✔️] sleepingbag-1.7.10-0.1.4
  [✔️] SpecialMobs-3.3.15
  [✔️] SpiceOfLife-2.0.9-carrot
  [✔️] SSP-1.1.2-GT-NH-Mod
  [✔️] StevesAddons-1.7.10-0.10.27
  [✔️] StevesCarts-1.7.10-2.0.2
  [✔️] StevesFactoryManager-1.1.7-GTNH
  [✔️] StorageDrawers-1.11.20-GTNH
  [✔️] StorageDrawersBop-1.7.10-1.11.17-GTNH
  [✔️] StorageDrawersForestry-1.7.10-1.11.17-GTNH
  [✔️] StorageDrawersMisc-1.7.10-1.11.18-GTNH
  [✔️] StorageDrawersNatura-1.7.10-1.11.17-GTNH
  [✔️] structurecompat-0.4.0
  [✔️] structurelib-1.2.6
  [✔️] SuperTic-1.7.10-1.2.5
  [✔️] Tainted-Magic-7.6.2-GTNH
  [✔️] tcinventoryscan-1.7.10-1.0.12-GTNH
  [✔️] tcneiadditions-1.1.1.10
  [✔️] tcnodetracker-1.7.10-1.1.7
  [✔️] TConstruct-1.9.25-GTNH
  [✔️] TecTech-5.1.2
  [✔️] TGregworks-1.7.10-GTNH-1.0.23
  [✔️] Thaumcraft-1.7.10-4.2.3.5a
  [✔️] Thaumcraft4Tweaks-1.5.3
  [✔️] ThaumcraftMobAspects-1.7.10-1.0.0-GTNH
  [✔️] thaumcraftneiplugin-1.7.10-1.7a
  [✔️] ThaumcraftResearchTweaks-1.7.10-1.0.4
  [✔️] Thaumic Machina-1.7.10-0.2.1
  [✔️] Thaumic-Based-1.5.0
  [✔️] thaumicenergistics-1.4.1-GTNH
  [✔️] Thaumic-Exploration-1.7.10-1.1.94-GTNH
  [✔️] ThaumicHorizons-1.2.1.12
  [✔️] thaumicinsurgence-0.2.2
  [✔️] ThaumicTinkerer-2.6.12
  [✔️] TiCTooltips-1.7.10-1.2.10
  [✔️] Tinkers-Defense-1.2.1d
  [✔️] TMechworks-1.7.10-0.2.16.4
  [✔️] TooMuchLoot-1.7.10-4.1.0-GTNH
  [✔️] torohealth-1.7.10-1.0.1
  [✔️] Translocator-1.1.2.21
  [✔️] TravellersGear-1.7.10-1.16.6
  [✔️] travellersgearneo-1.0
  [✔️] TwilightForest-2.4.0
  [✔️] txloader-1.5.2
  [✔️] unimixins-all-1.7.10-0.1.5
  [✔️] Universal-Singularities-8.6.6
  [✔️] visualprospecting-1.1.0
  [✔️] Waila-1.5.24
  [✔️] WailaHarvestability-1.7.10-1.1.10-GTNH
  [✔️] WAILAPlugins-0.2.6
  [✔️] WanionLib-1.8.4
  [✔️] WarpTheory-1.2.14-GTNH
  [✔️] Wawla-1.7.10-1.1.3-GTNH
  [✔️] WirelessCraftingTerminal-1.9.0
  [✔️] witchery-1.7.10-0.24.1
  [✔️] WitcheryExtras-1.1.14
  [✔️] WitchingGadgets-1.2.27-GTNH
  [✔️] WR-CBE-1.7.10-1.4.8
  [✔️] YAMCore-0.5.86
  [✔️] Ztones-1.7.10-2.2.2

Params:
  --username  --version 1.7.10 --gameDir E:/MultiMC/instances/GT_New_Horizons_2.3.2_Java_17-20/.minecraft --assetsDir E:/MultiMC/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms5120m, -Xmx10240m, -Duser.language=en]

Minecraft process ID: 15384

Using onesix launcher.

[21:35:29] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:125)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at cpw.mods.fml.common.launcher.FMLTweaker.<init>(FMLTweaker.java:35)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	... 10 more
[21:35:29] [main/ERROR] [LaunchWrapper]: Unable to launch
Program exited with code 1.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by eigenraven** [comment]
You're missing the multimc java arguments required to launch with newer java, copy them from <https://github.com/GTNewHorizons/lwjgl3ify#client>
