### ISSUE TITLE
Better P2P Crash

### ISSUE THREAD

**Issue by Blade8895** [GTNewHorizons/GT-New-Horizons-Modpack#13064]
### Your GTNH Discord Username

Blade8895#6067

### Your Pack Version

2.3.2

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Actions

Try to use the Better P2P Card on an p2p to link it using the GUI.
When the GUI should open it will crash to menu.

After rejoining the p2p interface is highlightet as intended. 

in short = open GUI = Crash

EXCEPT when using on interface terminal :D 

### Crash Report

[crash-2023-03-28_11.24.54-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11087946/crash-2023-03-28_11.24.54-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Beannsss** [comment]
I dont believe this is the fix that they will eventually go with, but I made a build here with the offending line commented out, it's just an icon being drawn so icons may be missing, but it looks fine from my initial testing...

https://github.com/Beannsss/BetterP2P/releases/tag/1.1.3-BW

**Comment by Beannsss** [comment]
Also wanted to say that this is not exclusive to java 17+, happens in java 8 with a fresh ae2 network with only 1 p2p interface.

**Comment by Rimuru-Tempest** [comment]
https://paste.ubuntu.com/p/WfgnnHz56D/
2.3.2服务器中会崩溃，即使没有optifine也是，单人就不会
