### ISSUE TITLE
BlockRenderer shows way too many Catalyst Housings for Chem Plant

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#13060]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

it should show the current structure. Which has at most one catalyst housing.

### The Reality

![image](https://user-images.githubusercontent.com/40274384/228014695-a5bb8198-e056-48b2-8bfa-d7deeba8c7c6.png)

### Your Proposal

fix it. :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Fiyorin** [comment]
i've been looking into this. the structure forms and it supports many catalyst housings.

however in recipecheckgeneric it says 
            if (mCatalystBuses.size() != 1) {
                return false;
            }

so why does it allow multiple in the first place?

**Comment by chochem** [comment]
whoever rewrote it to structurelib probably forgot about that check. no particular reason
