### ISSUE TITLE
New Advanced Memory Card are unable to type shift and number and space

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#13073]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.2

### Your Proposal

![image](https://user-images.githubusercontent.com/105285781/228510878-5b123a05-9e16-49b0-b80f-ca4318c2564c.png)
The old advanced memory card are used to be able to rename the channel with Capital and number.
However, now when i type space, shift, or number, it just hop out of the name editing mode

### Your Goal

QoL

### Your Vision

QoL for naming

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by firenoo** [comment]
I don't understand the request. You can rename tunnels with those characters at this time?

**Comment by madmacf** [comment]
It's the same as the issue I raised.
Naming a channel to eg "Chemical Reactors" is impossible. When pressing the SPACE button, the editing of name is exited.
Same goes for right SHIFT, CTRL and whole numpad keys,
Also makes it impossible to copy paste names as CTRL exits name editing.
Basically a lot of buttons works as ENTER, which should be the only key that ends the text editing.

Quite annoying when one is in the middle of a AE2 redesign of the base.

Also mouse right button deletes text. Mouse left button puts the text back.

Windows 11, v2.3.3.3, danish keyboard, english language. Fresh install from MultiMC, no extra mods.

**Comment by madmacf** [comment]
Cool Upgrading to BetterP2P 1.1.9 worked perfectly. Thank you.
