### ISSUE TITLE
Quest: safety first, spelling mistake

### ISSUE THREAD

**Issue by SomeonePerson123** [GTNewHorizons/GT-New-Horizons-Modpack#13070]
### Your Pack Version

3.2.0

### Your Proposal

In the quest description in the fourth paragraph it says "Note that cables are **batter** than" 

### Your Goal

To fix the mistake

### Your Vision

To fix the mistake

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
hello timetraveller. I hope you are wrong and we wont reintroduce the spelling mistake by 2020 when 3.2.0 comes out. Anyway its fixed at the moment
