### ISSUE TITLE
Exceeded Windows max directory character length(2.3.2)

### ISSUE THREAD

**Issue by wagon153** [GTNewHorizons/GT-New-Horizons-Modpack#13071]
### Your GTNH Discord Username

Wagon(Wagon153)

### Your Pack Version

2.3.2

### Your Server

Private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Was copying over files into my multimc instance from the 2.3.2 Java 19 mmc client download and expected it to go smoothly as it normally does. 

### The Reality

I got the attached error message. 
![Capture](https://user-images.githubusercontent.com/6232096/228376519-20af3738-e491-4b87-beeb-ccb9ab020aff.PNG)
Please note this is only one of the messages. It occurred with several other files in that directory. 

### Your Proposal

To my understanding this is a Windows 10 limitation. That said, the file and folder names in the betterquesting quest folder seem to have a lot of extra characters attached to the end, but I'm not sure whether this is necessary or not, since I'm unfamiliar with the internals of BetterQuesting. I was able to resolve the issue on my end by deleting some characters from the name of one of the parent folders, but that was before I checked to see where the issue actually was. 
Full directory name before I fixed it was C:\Users\(5 character username)\Desktop\MultiMC\instances\GT_New_Horizons_2.3.2_(PrismLauncher)_Java_17-19
Directory was from a previous download of the pack, I was just deleting old files and copy pasting. After changing it to GT_New_Horizons_2.3.2, it was fine.
![Capture](https://user-images.githubusercontent.com/6232096/228376906-4cbab4d6-06c5-4559-afc5-4f3addb487c9.PNG)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
it's a known issue, but sadly no ez fix possible. A simple workaround tho is to put the instance's root in something like `X:\GTNH` where X is the letter of your favorite drive to stock data.

**Comment by wagon153** [comment]
I will keep that in mind for the future when upgrading then.

**Comment by chochem** [comment]
> but sadly no ez fix possible

I wouldnt say that. We can certainly cut down the file paths by a good bit more.

**Comment by chochem** [comment]
This quest has 51 chars just for the questname. just always cut that off after 20 for example, same for questlines. Easily will fix it for many people and ensure we dont break stuff in the future by using an even longer quest name.

**Comment by chochem** [comment]
should be fixed by https://github.com/GTNewHorizons/BetterQuesting/pull/98
