### ISSUE TITLE
Rightclicking with network tool got crash

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#13074]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Try to rightclick AE network with network tool. Crash immediately

### Crash Report

![image](https://user-images.githubusercontent.com/105285781/228514232-3046bcf8-68c1-4a81-961c-49098f4c4a2c.png)
No crash report reported

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by firenoo** [comment]
For network errors there'll be a trace in your fml-client-latest log, please provide that.

**Comment by trollolal** [comment]
[fml-client-latest.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11102839/fml-client-latest.txt)
Not sure if it is this section

**Comment by firenoo** [comment]
Was likely an issue with a commit that is now out-of-tree.
