### ISSUE TITLE
Shift clicking Stack of Fluid container dupe the fluid when it is full in AE2 Terminal

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#13089]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

![image](https://user-images.githubusercontent.com/105285781/228887884-86ca7900-d5cc-4ba5-9dcd-d86c078d648c.png)
Expect it will be empty or stop if it is full

### The Reality

I am trying to empty 128 Certus Quartz Tank of Hydrogen
However, since it is full, the rest of the Hydrogen is put into the AE system and the rest is got duped.
64 Hydrogen -> 25 Empty Certus Quartz Tank + 65 Hydrogen

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
Cannot reproduce in dev, see https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/111

**Comment by trollolal** [comment]
> Cannot reproduce in dev, see [GTNewHorizons/AE2FluidCraft-Rework#111](https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/111)
I just retest it, it should be about full, and I shift click it, it will give me the filled tank.

For example, my AE system storage disc hold 33,554,368mb of fluid
If I shift click my container when AE system have 33,554,368 - 144 mb
it will not consume my filled container and give me the excess fluid tank

**Comment by tommmmmmmmm** [comment]
I also found that dupe, is that part of the same bug and already fixed or should i make a new issue?

https://cdn.discordapp.com/attachments/522098956491030558/1092500000967233627/2023-04-03_19-22-52.mkv
