### ISSUE TITLE
Buff Quantum Circuits

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#13082]
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

2.3.1

### Your Proposal

Either cut quantum circuits time in few times
Or decrease their tier to UMV to allow to be made in AAL pre EOH

### Your Goal

Make them more fair

### Your Vision

AAL was added for a reason, why do I have to build a lot of asslines if I was doing all off big recipes in AAL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by ramseyspace** [comment]
Having to wait 1000s to make UXV circuit, and trying to get more wireless energy done to reduce TPS and active transformer spam. I need to get t7 EOH to access UXV energy hatches. Im stuck with using normal assline bc AAL wont work unless i use UXV energy hatch
