### ISSUE TITLE
Crafting Advanced RE-Battery get you charged one

### ISSUE THREAD

**Issue by trollolal** [GTNewHorizons/GT-New-Horizons-Modpack#13085]
### Your GTNH Discord Username

Tim Lam

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

![image](https://user-images.githubusercontent.com/105285781/228790638-7e990345-4032-42ba-bb4f-f0e5c6edc64e.png)
This should give me empty charge one

### The Reality

It is magically charged

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by EnderProyects** [comment]
Batteries are usually made in such a way that they are already charged (in real life), so it could be instead of a bug a feature ( is not) xd
