### ISSUE TITLE
Better automation of different circuits in one multiblock.

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/GT-New-Horizons-Modpack#13096]
### Your GTNH Discord Username

monroth#4236

### Your Pack Version

2.3.2

### Your Proposal

Reducing amount of structural blocks that Volcanus needs from 8 to 3-5.
Adding "augmented (quad) input hatches", that can store not only fluids, but also item and\or circuit.
Adding "input extention master" and "input extension cables", can connect this master to tanks\inventories, and that will treat this inventories\tanks _AS SEPARATE INPUTS_
Adding ability to set "circuit slot" on input buses not only to circuits, but to arbitary items that can be put into head of multiblock.

### Your Goal

Reduce needs to make multiple multis if they are needed only for automation purposes.

### Your Vision

There are two examples of excellent multiblocks that can replace multiple monoblocks at the same time --- multiblock extruder, and multiblock assembler. They reduce need for multiple monoblocks because 
a) They are incredibly fast and allow parallels, and 
b) They have separate inputs --- so you can have different circuits\extruder shapes in different input buses, and do all or almost all recepies in one machine.

While (a) is shared between all multiblocks that i know of, many of them struggle with (b). Some examples are:

**Volcanus**
out of 18 avaible noncoil blocks, 2 goes to energy hatches, 1 to head, 1 maintenance, 1 pyrotheum, 1 output bus\hatch, 8 structure blocks, 1 muffler, 1 input bus\hatch, and that's all --- on a multi-purpose volcanus (by multi-purpose i mean that it needs input and output hatches) with 2 energy hatches you literally cannot have more than 1 input bus. This is ridiculous downgrade from normal EBF, who can have all the circuits of the world inside one machine. 

**Fluid Solidifier\Autoclave**
Fluid solidifier seems a lot like extruder --- put mold in, get item of this shape from fluid, instead of ingot --- but the problem is that mold is put into _buses_, but fluids go into _hatches_, so there is no obvious way to say to this multiblock smth like "fluid from this hatch should be solidified to ingots, and fluid from this hatch should be solidifier to plates". What's even worse, same machine in same mode is also an autoclave, but again, there is no way to say "this hatch should have circuit 21 and thus be hatch for autoclave, and this hatch should have circuit 22 and thus be hatch for solidifier". Theoretically I would not mind building separate machines for autoclave and solidifier, but head of this multiblock is stupidly pricey (6 iv machines+1 block in center that needs a lot of GT++ shit and thorium 232), precisely because it promises to automate 3 machines at the same time in one multiblock. It should be either be made cheaper, as other multiblock heads, or it should deliver it's promise to be 3 machines in one at the same time.

These examples are annoying, but at least they can be overcome with some external automation. For both of these cases I have SFM scheme that automatically inserts certain circuits\molds in input buses depending on which inventory got items for recepie. However. first of all, multiblocks should not rely on external automation just in order to have separated inputs, this should be their basic point. And second of all, some machines can't be automated even in this way, Let me introduce

**Auto chisel**
Even worse than previous examples, because in previous examples you could automatically extract and insert needed mold\circuit, on Auto Chisel this is impossible even in theory, because it's target blocks need to be placed in the head of mulotiblock. You can break head to automatically extract it's interior, but there is no way to automatically insert something inside of multiblock head.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
GT++ multis will slowly be ported over to the new MuTE multiblock system. This will include structure changes - no more cubes - and will also allow for more input buses, due to structures having more casings.

**Comment by monroth** [comment]
this would solve Volcanus issue, but won't solve other mentioned multis - they have plenty of space to have input buses, and they still are either awkward (solidifier) or impossible (chisel) to automate

hopefully this new system would solve that as well!
