### ISSUE TITLE
betterquesting Translation Problem

### ISSUE THREAD

**Issue by wohaopa** [GTNewHorizons/GT-New-Horizons-Modpack#13099]
### Your Pack Version

2.3.1/2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

When I use a lang file, I find that it doesn't work. I found that the betterquesting key was wrong. 
![~CT$V71~}5FIYYS`V(ELVA3](https://user-images.githubusercontent.com/30284813/229159266-2d483cfb-b606-4cba-a242-54197bf816c6.png)
Special characters in key are not supported in lang files. This is the essence of failure. 

### The Reality

questing internationalization is not available

### Your Proposal

Use other key naming methods.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by D-Cysteine** [comment]
This should be fixed by:
 * https://github.com/GTNewHorizons/BetterQuesting/pull/101
