### ISSUE TITLE
AE2FC: Encode (Fluid) Patterns can't be erased

### ISSUE THREAD

**Issue by nshepperd** [GTNewHorizons/GT-New-Horizons-Modpack#13094]
### Your GTNH Discord Username

nshepperd#2316

### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

AE2 Encoded Patterns (created with the ordinary Pattern Terminal) can be erased into blank patterns by crafting them in the crafting grid, which is useful when I encode a pattern then realize it won't work. The same should be possible for AE2FC Encode Patterns, created at the fluid pattern terminal.

### The Reality

There is no such recipe, so a useless Encode Pattern can only be voided.

### Your Proposal

Add an Encode Pattern -> Blank Pattern crafting grid recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by King65868** [comment]
You can clear them in world by just sift right clicking

**Comment by nshepperd** [comment]
Well, shit. I guess the recipe would still be nice to have?

**Comment by miaowwwwww** [comment]
not just nice to have, they are essential. image have 50 of them to empty and u can only use hand to change them. for me i'm throwing the not wanted ones rn.

**Comment by miaowwwwww** [comment]
Comment to reopen

**Comment by miaowwwwww** [comment]
fixed in https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/257 yeahhhhhh!
