### ISSUE TITLE
Ruby Juice missing from Ruby Ore processing page

### ISSUE THREAD

**Issue by riking** [GTNewHorizons/GT-New-Horizons-Modpack#13109]
### Your GTNH Discord Username

Riking#6902

### Your Pack Version

2.3.0

### Your Proposal

Add "Additional Mixer recipes" icon, and Ruby Juice Cell, to the Ruby Ore GT Ore Processing NEI page.

### Your Goal

I need more than just a questbook page to remind me this processing line exists when i'm doing ore sorting

### Your Vision

Completeness of ore processing chart reference

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by riking** [comment]
I might take a stab at fixing this

**Comment by D-Cysteine** [comment]
Should be fixed by:
 * https://github.com/GTNewHorizons/nei-custom-diagram/pull/31
