### ISSUE TITLE
Crashing when second player joins

### ISSUE THREAD

**Issue by Zarasaar** [GTNewHorizons/GT-New-Horizons-Modpack#13107]
### Your GTNH Discord Username

Zarasaar#3725 

### Your Pack Version

2.3.0

### Your Server

local network

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Actions

We are playing in Local Network over Hamachi. Got about 200 hours without problems. The other player on the server was fishing and got a turtle or something. Then the Game crashed on both of us. Now I can play on my own just fine, but if the second player connects it always crashes again
[crash-2023-04-01_22.36.08-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11130631/crash-2023-04-01_22.36.08-server.txt)
[crash-2023-04-01_22.43.32-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11130632/crash-2023-04-01_22.43.32-server.txt)
[crash-2023-04-01_23.03.24-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11130633/crash-2023-04-01_23.03.24-server.txt)

**Comment by firenoo** [comment]
Maybe world corruption at where the other player is at, does restoring a backup fix it?

**Comment by Zarasaar** [comment]
To be honest: I don't know, how to do that :X don't laugh at me please ^^

**Comment by Ydrec** [comment]
1st thing is to remove pasted log from issue and attach it as a text file

**Comment by Ydrec** [comment]
Seems like player is in corrupted chunk, you can use mcedit/nbtedit to move player out. it also can be possibly something in player inventory which causes crash on load. Recommend loading a backup if available and seeing if that fixes things

**Comment by Zarasaar** [comment]
I tried the backups 30 and 60 minutes before. Both give the same error. Is it worth going even further back or what could be the error?

**Comment by Zarasaar** [comment]
The problem was resolved by deleting the items of the second player. Changing his location didn't help.
What item exactly caused the problem is unknown.
