### ISSUE TITLE
Add Tiered Datasticks

### ISSUE THREAD

**Issue by chaosblade201** [GTNewHorizons/GT-New-Horizons-Modpack#13119]
### Your GTNH Discord Username

chaosblade#6706

### Your Pack Version

2.3.0.0

### Your Proposal

I believe their should be a higher tier data stick required for late-game recipes instead of a Low capacity Data-stick due to the complexity of the crafts

### Your Goal

to make the end game research to be more realistic instead of having for example a single data stick that houses the same data for example circuits why does the eye of harmony require the same level of data stick as a circuit from earlier in the game

### Your Vision

Provide a more realistic experience with the crafting complexity 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
what are you talking about? data access hatches? ae2 cells? storage in crafting cpus? me drive itself? research station because then you say research at some point? and what is that about circuits?

**Comment by minecraft7771** [comment]
It seems to me that they basically want tiered datasticks.

**Comment by chaosblade201** [comment]
Yeah that is what I meant should I edit the original suggestion

**Comment by chochem** [comment]
I see. and why?

**Comment by chaosblade201** [comment]
I believe that this would improve the end game "realism" 
As you don't have midgame crafts being the same storage complexity as late game research

**Comment by boubou19** [comment]
tiered datasticks wouldn't bring anything to the gameplay,as we already have scanner/research station as research progression. Also, we are past the point of realism with that content, so no need to add bloat into the pack.
