### ISSUE TITLE
AE2 sometimes sets too low 'to craft' amounts in orders

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13115]
### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

For some recipes, no matter if i try to order 50 or over 200, certain things will often show up with a small amount missing, preventing me from ever ordering it, despite the bigger order of the 2 showing that it can clearly craft more if it wants to:
![image](https://user-images.githubusercontent.com/39203645/229372941-f399fa2e-37d4-412f-913f-534066de9c85.png)
![image](https://user-images.githubusercontent.com/39203645/229373007-e9bc2e8c-b8e9-4651-8af7-1cb71fa3084a.png)

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Still exists in 2.3.2

**Comment by chochem** [comment]
maybe you can make a minimal reproducable setup for devs to try
