### ISSUE TITLE
Error Code 1 after trying to update from 2.2

### ISSUE THREAD

**Issue by Boisq** [GTNewHorizons/GT-New-Horizons-Modpack#13110]
### Your Pack Version

any

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

i was playing fine on 2.2 but after i tried updating it didnt work anymore for me AND for my friend, tried older and newer versions, clean installs, other launchers (i use curseforge and i tried mmc) everything gives me the same error

### Crash Report

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11131133/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ydrec** [comment]
Ask for help in modpack discord #help channel. Generally its an issue of the people installing the pack wrong and not the pack having an issue. Error code 1 means literally any error so need more info than that. Also that log is cutoff as hell and doesn't tell anything.
