### ISSUE TITLE
Items void when breaking barrel/drawer with lots of stuff

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#13117]
### Your GTNH Discord Username

Keyla#3300

### Your Pack Version

2.3.0

### Your Server

Other server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

Wanted items not to void

### The Reality

Items void when a lot of items drop on the ground, only 1 stack drops instead of amount in the barrel/drawer
Same with dropping lots of same item from adventure backpack on the ground, i guess its not a barrel/drawer problem, just a problem with handling dropped items on the ground

### Your Proposal

Let at least 64 stacks be on the ground

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by CatsLeftEar** [comment]
same with dropping lots of same item from adventure backpack on the ground, i guess its not a barrel/drawer problem, just a problem with handling dropped items on the ground

**Comment by boubou19** [comment]
it's not a bug but an anti-lag feature to avoid freezing tps to death
