### ISSUE TITLE
Tier 4 - EV // Obtaining a QuantumEye

### ISSUE THREAD

**Issue by Namikon** [GTNewHorizons/GT-New-Horizons-Modpack#13118]
### Your Pack Version

2.3.0.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

With the current progression set, Pitchblene/Uranium and Uranite can only be mined from Mars+. But, according to the Questline, you need those to get Radon, in order to get the Quantum Eye, in order to make the (Circuit) Assembler to get the T2 Rocket to fly to mars+.

The only way to reach Mars currently is to process Thorium Ore to get Radium 226, let it decay and then electrolyze it.

### The Reality

Can't reach mars without reaching mars...

### Your Proposal

In Tier 4 - EV, the Quest "Radon Decay" should include Purified Thorium Ore. That way one could continue the chain

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
do `\bq_admin default load`

**Comment by Dream-Master** [comment]
@Namikon welcome back. Didnt know you start a new run on GTNH :)
