### ISSUE TITLE
Raven kama not turning off

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#13116]
### Your GTNH Discord Username

Santa's Child#0408

### Your Pack Version

2.3.0

### Your Server

Private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Attempting to turn off the raven kama using travellers gear keybinds turns off the kama as it does the mantle allowing for better control

### The Reality

when playing on a dedicated server (bug seemed to be non present in SP) the kama requires you to unequip and reequip it between disabling and enabling it in order to function properly

### Your Proposal

valve pls fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by des-cuddlebat** [comment]
What I believe to be happening is Baubles not syncing its inventory to a dedicated server when you press the keybind. You can see the item change on the client side (whether it says "gliding disabled" or not), and removing and putting it back in the Baubles inventory applies the new state. It would also explains why the raven cloak works as expected - unlike belt slot, cloak slot doesn't come from Baubles.

I'd like to try to fix this, at latest I should get to it after exams in the second half of June.

**Comment by des-cuddlebat** [comment]
Fix pending GTNewHorizons/WitchingGadgets#53 (autolink from there doesn't seem to have worked)
