### ISSUE TITLE
Crash on startup after updating

### ISSUE THREAD

**Issue by TheBookAjah** [GTNewHorizons/GT-New-Horizons-Modpack#13111]
### Your GTNH Discord Username

The Book Ajah#5563

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

Tried to start the pack and almost immediately crashed. I have tried starting with a new instance and porting over only necessary bits from the old one, and I have tried starting with a completely fresh instance. It crashed each time. The crashlog posted is from the fresh one. I am using MMC args, and have not modified the pack. When I downgraded my original instance to 2.3.1 it worked again.
Thank you for your work on this pack. I hope this is helpful.

### Crash Report

https://paste.ee/p/HDa0x

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
it appears forgePatches jar isn't applied properly. maybe check if file in `libraries/com/github/GTNewHorizons/lwjgl3ify/1.3.3/lwjgl3ify-1.3.3-forgePatches.jar` is in good shape. You can check this by trying to open it with 7zip or equivalent zip file manager. If it fails, try delete it and let mmc redownload it. if mmc just cannot download it properly (we have seen this before), try download it manually from http://jenkins.usrv.eu:8081/nexus/content/repositories/public/com/github/GTNewHorizons/lwjgl3ify/1.3.3/lwjgl3ify-1.3.3-forgePatches.jar

**Comment by TheBookAjah** [comment]
MMC couldn't download it properly, but the manual download link file works perfectly. Thank you.

**Comment by TheBookAjah** [comment]
If I may ask, how can you tell what the issue is from the log there? It lists that file with the rest, and nothing abnormal.
