### ISSUE TITLE
NBT randomization happens only once for Thaumcraft treasure bags

### ISSUE THREAD

**Issue by cubic-chariot** [GTNewHorizons/GT-New-Horizons-Modpack#13128]
### Your GTNH Discord Username

cubic-chariot#3803

### Your Pack Version

2.2.8

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I opened hundreds of common, uncommon, and rare treasure bags from Thaumcraft. I got some enchanted books and vis stones. I expected the enchantments and contained vis to be random.

### The Reality

The enchantments and contained vis are the same in every opened treasure bag, even across different rarities of treasure bags. The enchantments and stored vis only change when the server restarts.

### Your Proposal

Determine enchantments and stored vis upon loot generation, rather than server initialization.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Vis amount is never meant to be randomized, but the book one is indeed a bug.
