### ISSUE TITLE
Fluid export bus void bug

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#13122]
### Your GTNH Discord Username

Sza#0522

### Your Pack Version

230

### Your Server

priv srv

### Java Version

Java 19

### Type of Server

None

### Your Expectation

I tried the "AE2 Fluid Crafting - ME Fluid Export Bus" to export fluid into a machine's UHV fluid input hatch.
When it requests existing fluid from ME, it works as expected. But when no fluid is available at storage it requests a new batch, around 8000mb of fluid but my pattern which provides this fluid makes like 8.000.000mb of it.

### The Reality

The 8 million fluid gets produced and the export bus instantly fills up the input hatch, voiding the rest of it what didnt fit in. this is especially bad when only a few 1000s of fluid is missing.
It supposed to store 7.992.000mb in fluid storage and send the requested 8.000mb to the output hatch.

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Szajkop** [comment]
Looks like https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12966 has the same issue

**Comment by firenoo** [comment]
Closing as its a dupe issue.
