### ISSUE TITLE
Lithium and Kevlar Bee cannot be mutated naturally

### ISSUE THREAD

**Issue by Graymare** [GTNewHorizons/GT-New-Horizons-Modpack#13129]
### Your GTNH Discord Username

Embri#3434

### Your Pack Version

2.2.8

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Salt x Aluminium Bees are expected to mutate into the Lithium Bee species at a rate of 5%, when a Lithium Frame Box is placed under the Apiary/Alveary.  Similarly Kevlar Bees are expected when Oil and Infinity are paired in a housing over a Kevlar Frame Box with a mutation rate of 4%.

### The Reality

Neither Lithium nor Kevlar mutate even when supplied with triple Mutagenic Frames that should put their mutation rates at >100%.  Other species in the same setup mutate correctly 100% of the time, including Salt which also requires a support block and has a similar 5% base rate.  Both Kevlar and Lithium were attempted until over a double chest full of bees were produced, but there were no mutations at all.
<img width="518" alt="SaltxAluminum" src="https://user-images.githubusercontent.com/121984725/229753568-cc6841db-ab11-4075-982f-6a41f772866e.png">

### Your Proposal

Change the support block code or requirement so that Lithium and Kevlar bees can be bred as intended, without the Mutatron.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Graymare** [comment]
Making both of these bees Mutatron only would be a fine solution too - NEI just needs to not make it seem like they're possible to breed naturally.  Three days and hundreds of attempts were spent on trying to get Lithium in my survival world because it looks like they should be attainable naturally.

**Comment by chochem** [comment]
we are not gonna declare this bug a feature, no.
