### ISSUE TITLE
Aluminium misspelling

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#13138]
### Your GTNH Discord Username

Santa's Child#0408

### Your Pack Version

2.3.0

### Your Proposal

Correct the spelling of Aluminium in EN_UK and potentially EN_US

### Your Goal

Aluminium is the correct spelling and internationally accepted outside of NA.

### Your Vision

As appears to be wanted by the pack devs aluminium should be the main spelling as it' internationally accepted there are cases in EN_UK where it should ALWAYS be aluminium where it is aluminum and EN_US is relatively inconsistent

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Aluminum (TiC) and aluminium (GT) are 2 different materials in the pack. Not going to happen.

**Comment by boubou19** [comment]
yup
