### ISSUE TITLE
Broken wiremill recipies in gt5 5.09.42.36 (latest)

### ISSUE THREAD

**Issue by technod999** [GTNewHorizons/GT-New-Horizons-Modpack#13149]
### Your GTNH Discord Username

Oreo#4444

### Your Pack Version

2.3.2 + updated gt5 to 5.09.42.36 for the disassembler

### Your Server

Private server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

The wiremill only has 66 pages of recipes, and alot of them are broken. When I put a wiremill down, it only makes graphene wires as the first recipe is nothing -> graphene wire.

again this is in the latest pack, but with gt5 updated to 5.09.42.36 for the disassembler fixes

![image](https://user-images.githubusercontent.com/43463874/230525080-4a0c5e0c-1e0e-4dd4-88d5-cc5609b186a0.png)

### The Reality

free graphene :3

### Your Proposal

fix the missing recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
looks like its trying to make wires from graphene rods which dont exist. But all the rest is broken too?

**Comment by Dream-Master** [comment]
i guess it is much more broken then only this. This is the tip of the iceberg. ra2 wasnt realy done and need some more fixes. I just work out a version we maybe can use after 2.3.2

**Comment by chochem** [comment]
yea I am assumed as much. hence me assigning boubou :P

but I will also maybe later update some mods and look around the recipes

**Comment by Dream-Master** [comment]
Downgrade this mods:
https://github.com/GTNewHorizons/bartworks/releases/tag/0.6.5
https://github.com/GTNewHorizons/GTplusplus/releases/tag/1.8.27-pre
https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.42.26
https://github.com/GTNewHorizons/NewHorizonsCoreMod/releases/tag/2.0.10

**Comment by Dream-Master** [comment]
From all other mods the latest tags can be used

**Comment by chochem** [comment]
ok so almost all recipes are missing. used to be 1342 (in 2.3.2) wiremill recipes. now just 132.

**Comment by chochem** [comment]
was a smaller fix after all. Though I find it concerning for RA2 that a single broken recipe breaks the entire recipe map and removes more than a 1000 recipes
