### ISSUE TITLE
Give the ABS an Input Bus Separation option

### ISSUE THREAD

**Issue by IsOobt** [GTNewHorizons/GT-New-Horizons-Modpack#13144]
### Your GTNH Discord Username

oobt#8431

### Your Pack Version

2.3.2

### Your Proposal

Give the ABS (Alloy Blast Smelter) Input Bus Separation

### Your Goal

I keep getting recipe conflicts when trying to craft casings that involve ABS alloys

### Your Vision

Would help with automating ABS crafts without major issues.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
It already has it. Use screwdriver or GUI.

**Comment by IsOobt** [comment]
Are you sure? Because I tried both and it was greyed out on the GUI and the screwdriver didn't do anything? If that's not intentional it might be a bug, at least on my end

**Comment by IsOobt** [comment]
Ok i tried again, it works with a screwdriver but not with the GUI. Weird

**Comment by minecraft7771** [comment]
I'll look into the gui later when I'm home.
