### ISSUE TITLE
GTPP Multiblock GUI input seperation doesn't work properly

### ISSUE THREAD

**Issue by IsOobt** [GTNewHorizons/GT-New-Horizons-Modpack#13145]
### Your GTNH Discord Username

oobt#8431

### Your Pack Version

2.3.2

### Your Proposal

Have the new Multiblock controller GUI indicate if a setting that can't be changed (Void excess on non GT++ multis or input bus separation) is on by default or not.

### Your Goal

It would make it easier to see if a multiblock has a forced void excess or input bus separation (such as the GT++ bender in forming press mode or the GT++ extruder)

### Your Vision

Makes it easier to see the default settings for players so they can work more easily with setting up multis.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
Wdym, it already does that? If an option is greyed out it can be greyed out in either state, on or off.

**Comment by IsOobt** [comment]
As far as I can tell it does not. 
![image](https://user-images.githubusercontent.com/114492400/230279247-927c2bc0-8aad-48fd-85e7-d09173c8293d.png)

**Comment by minecraft7771** [comment]
If it was on then it'd be a different icon (with lines separating the sides of the square). Greyed out only means it can't be toggled, so it can be greyed out either with (enabled) or without (disabled) lines.

**Comment by IsOobt** [comment]
I know, but the GT++ extruder definitely has input bus separation enabled, but it is not showing any lines

**Comment by minecraft7771** [comment]
So only overrides are missing. That's easy to fix.
