### ISSUE TITLE
Server entered crash loop after restart   (Exception in server tick loop)

### ISSUE THREAD

**Issue by WillCap** [GTNewHorizons/GT-New-Horizons-Modpack#13146]
### Your GTNH Discord Username

Dem#0069

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

I restarted my server due to it being overloaded and skipping ticks. After I restarted the server it entered a crash loop, constantly crashing at the same point. 

### Crash Report

[crash-2023-04-06_06.56.14-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11167254/crash-2023-04-06_06.56.14-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
can you post the full logs? I would suspect something already went wrong before what is in this crash report.

**Comment by WillCap** [comment]
Here's the full log from start to crash. If it's any help dreamcraft is mentioned to have been errored multiple times before the crash.

https://paste.shockbyte.com/uluyawikicihobawojug

**Comment by WillCap** [comment]
I did a fresh install of GTNH 2.3.2 and transferred my old files. It's working flawlessly now, no idea what caused the errors but the logs are there.
