### ISSUE TITLE
ME P2P Interfaces get stuck on "Scheduled"

### ISSUE THREAD

**Issue by nisn17** [GTNewHorizons/GT-New-Horizons-Modpack#13153]
### Your GTNH Discord Username

Nisn#4910

### Your Pack Version

2.3.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

**Video Explanation & Recreation of Bug**: https://www.youtube.com/watch?v=9RWszzxYJjw

Set up first machine with p2p interface, so that you can expand to multiple machines easier than using a normal interface.
Use p2p interface like normal interface.
When expanding, make first p2p interface just one of multiple output p2p interfaces, which are linked to a seperate input p2p interface, that holds the recipes.
Be able to request items like with a regular interface, just with parallelization

### The Reality

**Video Explanation & Recreation of Bug**: https://www.youtube.com/watch?v=9RWszzxYJjw

After Mining (using shift+rightclick with a wrench) the first p2p interface while still using it as the only interface and then replacing it and linking it to the other p2p interfaces as described above, all requested recipes are stuck on "scheduled" and dont get inserted into otherwise valid inventories until the first p2p interface is broken.

Step by step to recreate:
1. Place p2p interface A against inv.
2. Place dummy pattern in A
(3. Request dummy pattern)
4. Harvest p2p interface by shift+rightclicking with a wrench.
5. Place p2p interface B against other inv. Place p2p interface C against air.
6. Link up B&C with C being the input.
7. Replace A into same place as 1.
8. Place dummy pattern in C and link A as another output to C
9. Request dummy pattern. As demonstrated, it gets stuck as "scheduled" despite having valid inventories to output to.
10. After destroying A, the recipe gets sent into B, without having done anything to B itself.

### Your Proposal

What i cant recreate, but noticed when it first occured, is the first interface still showing the dummy recipe item in the HoloGlasses after being replaced. Even just placing a smart cable in its place made the HoloGlasses show the dummy recipe item.

It could be useful to **check if Data such as "stored recipes" is kept by the p2p interface when mined** via shift+rightclick. It already keeps its name and its p2p type (Interface), so it **might remember unwanted information.**

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
Tried to follow the steps exactly in AE2 beta-190 dev environment and could not reproduce. Maybe try updating to 190 to see if it still happens
