### ISSUE TITLE
does not craft the first Energy Module recipe

### ISSUE THREAD

**Issue by Merfey** [GTNewHorizons/GT-New-Horizons-Modpack#13156]
### Your GTNH Discord Username

Merfey#6756

### Your Pack Version

2.3.2

### Your Server

privat server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

trying to make assline EUV Energy Module according to the first recipe.

### The Reality

does not craft the first Energy Module recipe.
![image](https://user-images.githubusercontent.com/40973665/230669608-683e0526-e825-41a4-8173-901318539412.png)
the second recipe works.

trying to do assline EUV

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
They have different scanning items. Try to switch the data stick with the other one.

**Comment by AtomicGrog** [comment]
Had same issue with this and the energy cluster which also got updated to dual recipe. It was refusing to make with both old and new recipes; Had to remake the datastick for em and then it worked fine.

**Comment by Merfey** [comment]
Yes, thanks, I did not notice that they added two different scans of the same item. And it looks like my default data stick turned into a second recipe.
