### ISSUE TITLE
Retier MK3 Space Assembler to UMV

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#13168]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.3.2

### Your Proposal

Space Assebler MK3 should be retiered to late UMV or pre-UXV.

### Your Goal

Currently Space Assembler MK3 needs much UXV components to craft.
A single SA MK3 needs about 1.5ML of molten universium, which equals to several sets of mk5 space elevator.
Meanwhile, one SA MK3 is only equalent to 4~16 SA MK2. This makes it highly unworthy to make SA mk3; building a whole new space elevator full of SA Mk2 seems more worthy.

### Your Vision

Retiering Space Assenbler MK3 should make it more balanced and make the end-game base less repetative.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
going forward there will be recipes that need this tiers. so retiering is unlikely. its like assembler tiers
