### ISSUE TITLE
AE2 Fluid Export Bus Voids Fluids

### ISSUE THREAD

**Issue by BobGoldham** [GTNewHorizons/GT-New-Horizons-Modpack#13161]
### Your GTNH Discord Username

Bob Goldham#0339

### Your Pack Version

2.3.0

### Your Server

Bug first occured on private server, reproducible in SP.

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

NOTE: This appears related to #12966 but a crafting card was **not** used. 
It appears that the issue is either unrelated to the crafting card OR this is an entirely separate issue.

Steps to reproduce:
- ((Create any valid AE2 setup, since this bug requires ME busses))
- Place down a Super Tank I, fill part-way with a fluid (I used Sulfuric Acid)
- Connect an ME Fluid Storage bus, set to any priority >=1
- Hit the "Partition Storage" button in the Storage busses interface
- Place a fluid export bus (connected to the same AE system) facing the Super Tank
- Configure it to export the fluid stored in the tank

Expected outcome:
Any fluid stored elsewhere in my ME system should move into the tank. Fluid already within the tank should be exported last, since the attached storage bus has the highest priority. After all other fluids are moved, fluctuations of +-1k fluid are expected as the fluid cycles through the busses and tank.

### The Reality

Watch as the fluid from the tank disappear into nowhere in 1k increments.

### Your Proposal

For the fluid to not disappear.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BobGoldham** [comment]
After a bit of experimenting, the same issue remains when placing the export bus onto any part of the ME system's storage, including an ME interface and regardless of what cards are or are not used.

**Comment by firenoo** [comment]
I tried reproducing it in dev, and could not with this setup 
![image](https://user-images.githubusercontent.com/49818773/235331424-8c6e0731-c720-452e-a288-832dae2a6ca8.png)

I followed the steps you gave exactly, except I used a different tank, and I got the expected result: all tanks drained to the one with priority 1, with no voiding, then fluctuations of +/-1000 happened. Thus I suspect there is missing information in the setup you gave. Does the super tank have a different configuration, covers, etc?

**Comment by zhlkvz** [comment]
I have a similar issue.
Mine is very easy to reproduce:
Set up an ME system (controller, power, fluid storage cells)
Add a GT tank via a fluid storage bus, fill it with any fluid.
Add another empty tank, and attach a fluid export bus.
Put a crafting card into the export bus at set it to only craft new fluids.
The export bus will now void fluids from the first tank in 1k increments. If the export bus is not set to only craft, the fluctuation will happen instead.

**Comment by firenoo** [comment]
Thanks for providing a setup, but the crafting card bug is a separate issue (the author has already mentioned and linked it). This issue involves no crafting card.

**Comment by BobGoldham** [comment]
> I tried reproducing it in dev, and could not with this setup ![image](https://user-images.githubusercontent.com/49818773/235331424-8c6e0731-c720-452e-a288-832dae2a6ca8.png)
> 
> I followed the steps you gave exactly, except I used a different tank, and I got the expected result: all tanks drained to the one with priority 1, with no voiding, then fluctuations of +/-1000 happened. Thus I suspect there is missing information in the setup you gave. Does the super tank have a different configuration, covers, etc?

> ((Create any valid AE2 setup, since this bug requires ME busses))
> **Place down a _Super Tank I_, fill part-way with a fluid (I used Sulfuric Acid)**
