### ISSUE TITLE
Glitched Bee Frame craftable in Blood Altar

### ISSUE THREAD

**Issue by ReijiGazpacho** [GTNewHorizons/GT-New-Horizons-Modpack#13178]
### Your GTNH Discord Username

Reiji#8790

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

1. Construct a T3 Blood Altar and supply with 30000 LP.
2. Input an Impregnated Frame from Forestry.
3. Wait for the altar to craft a- "A fatal error has occured, this connection is terminated"

The item the altar tries to craft has no localized name, no texture, no associated mod, and a numerical ID of -1.
The string "Stirs bees into a frenzy." appears in the lang files of Blood Magic.
Screenshot of NEI recipe provided. Can be viewed in-game by checking uses for an Impregnated Frame.

I'm on a private server running 2.3.0 but lack the infrastructure needed to craft this in survival. If I pull it off (with permission, of course) I'll update with results.

![javaw_zvyqoZ6Pgs](https://user-images.githubusercontent.com/130375662/230917341-68c2e1ad-624b-4445-9631-5ac7dfe36fe5.png)

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11191279/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
maybe a frame that exist before and was removed later on ?
