### ISSUE TITLE
IDs maybe should not show in the questbook even with debug

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13172]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

![image](https://user-images.githubusercontent.com/39203645/230781159-9e40219d-1efa-41a2-a92e-f0d419ea12a7.png)

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
thats an id, not a name. and you have the F3+H debug mode on that specifically shows ids.

**Comment by Tommeh1** [comment]
> thats an id, not a name. and you have the F3+H debug mode on that specifically shows ids.

That's new and very annoying considering how many people play with that debug enabled.

**Comment by chochem** [comment]
No, its not new. Was always there.
But arguably less useful than before, hmm. I guess its also no longer really needed.

**Comment by D-Cysteine** [comment]
Should be done now in dev
