### ISSUE TITLE
Super/quantum tank variants of tank carts

### ISSUE THREAD

**Issue by mnewbold01** [GTNewHorizons/GT-New-Horizons-Modpack#13175]
### Your GTNH Discord Username

Drewdroid9#1341

### Your Pack Version

2.3.0

### Your Proposal

Adding larger variants of tank carts. Eg. super, quantum or iron tank varients.

### Your Goal

The only current tank cart is the default 32 bucket variant and the only viable way to move fluids with Railcraft is currently loading fluid cells into chest carts. Chest carts also already have iron tank variants so this will make fluid loading infostructure more viable.

### Your Vision

This would encourage more rail focused builds, which in my opinion look much cooler than spamming ender tanks/chests or LDFPs. This is just something I picked up on while doing a no teleportation run (only using cargo rockets/rails). 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
yes the size need to be reworked. Its not realy usable. A train cart should lood much more fluid at once.
