### ISSUE TITLE
Internal server error when 2x2 crafting in the inventory 

### ISSUE THREAD

**Issue by Kelpatrice** [GTNewHorizons/GT-New-Horizons-Modpack#13174]
### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

Hi im trying to host a GTNH 2.3.0 server but i keep getting kicked with the message internal server error when trying to use the 2x2. the server stays online. ive tried thermos and cauldron. does anyone know a fix or had this issue. it neither crashes the server or my client just kicks me off all crafting in the 3x3 works fine.

so i can put 2 gravel in the 2x2 and its ok but the moment i add the 3rd and the flint appears i get kicked.   

### The Reality

the result of the recipe is shown 

### Your Proposal

craft properly 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
it's because of crucible. We use this for thermos to fix this issue, maybe it might help crucible too: https://cdn.discordapp.com/attachments/305737190195986433/1084572592763064392/Gambiarras_BQThermosFix-1.0.1.jar
