### ISSUE TITLE
Quadruple pipes now need circuit #9, conflict with nonuple pipes.

### ISSUE THREAD

**Issue by fluffle** [GTNewHorizons/GT-New-Horizons-Modpack#13185]
### Your Pack Version

2.3.2

### Your Server

Private MP

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Quadruple pipes still craftable with circuit #4 as before.

### The Reality

Quadruple pipes need circuit #9 in an assembler now. But so do nonuple pipes, which means one or the other isn't craftable. At the moment my precise assembler seems to prefer quadruple over nonuple, thankfully.

### Your Proposal

Switch back to circuit #4 for quadruple pipes, please? I don't think this was intentional -- the change was made in the depths of https://github.com/GTNewHorizons/GT5-Unofficial/pull/1702 by @Connor-Colenso but there were a lot of changes there and this one is possibly a copy/paste error?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
they use different pipes, no?

**Comment by fluffle** [comment]
Argh; they do, somehow I missed that -- the nonuple requires small pipes /o\

Sorry!
