### ISSUE TITLE
Item Dislocator sound config confusion

### ISSUE THREAD

**Issue by kojul** [GTNewHorizons/GT-New-Horizons-Modpack#13184]
### Your GTNH Discord Username

kojul#1034

### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

Setting B:"Item Dislocator Disable Sound"=true in DraconicEvolution.cfg in the _client_ would disable the constant dinging sound when using a void item filter as described in https://github.com/GTNewHorizons/Draconic-Evolution/pull/33

### The Reality

Had to changed the config on the server. Assuming this is because the mod uses world.playSoundAtEntity in order to play the ding.

### Your Proposal

Would be nice if the sound was off by default knowing that most people will use a void item filter with it in the early game and also to prevent others who may not know this needs to be set on the server from being confused why the config flag "isn't working"

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lithorn** [comment]
Can confirm this bug in 2.3.2. However, changing the sound to disabled for the item dislocation only stops the infinite pinging. It dosent stop the sound played upon picking up blocks from minecraft. I pick up stone and hear it repeatedly, but if I pick up dirt I hear it play infinitely.
