### ISSUE TITLE
Dual interfaces randomly stop converting fluid packets

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13196]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

At random dual interfaces will stop converting fluid packets into actual fluids, thus failing to export the fluids and jamming until broken and replaced, this will occur to them almost every single day.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AtomicGrog** [comment]
I have this time to time, especially when it's dual interface facing dual interface which then points to a fluid and item storage bus. Would be useful to see the AE2 fluid packet that (invariably gets thrown out when you break the interface) in it's inventory same as you'd see items.
