### ISSUE TITLE
"Even more challenge needed?" Quest can be done infinite times. This causes an infinite exp dupe.

### ISSUE THREAD

**Issue by AndyDobrowolski** [GTNewHorizons/GT-New-Horizons-Modpack#13205]
### Your GTNH Discord Username

Lizard1255#4590

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

I expected the quest to finish, I get the reward, and then the quest to not reopen.

### The Reality

Upon submitting the quest, you gain the reward. The quest is then immediately completable again for the same reward (10 levels). This can be repeated seemingly forever  

### Your Proposal

Fix the quest so that it can not be infinitely repeatable, and thus the player can't use it to gain infinite levels.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed already
