### ISSUE TITLE
linked input but 'private' settings bug

### ISSUE THREAD

**Issue by zgggz** [GTNewHorizons/GT-New-Horizons-Modpack#13204]
### Your GTNH Discord Username

ZggZ#7290

### Your Pack Version

2.3.0

### Your Server

zvezdolet

### Java Version

Java 8

### Type of Server

None

### Your Expectation

linked input bus in private mod don't work in large processing factory in precision laser engraver mod.
looks like multiblok don't see items.

### The Reality

fix it

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
does it only break with private mode? because that shouldn't matter whatsoever.
