### ISSUE TITLE
Possible typo in botany item name

### ISSUE THREAD

**Issue by dhasial** [GTNewHorizons/GT-New-Horizons-Modpack#13206]
### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

I expected the Botania item "Cooper Insulated Tube" requested by the quest, to be called "Copper Insulated Tube"

### The Reality

I may be wrong and this is just an intentional typo by the mod author, but I believe it's meant to be "Copper", not "Cooper".

### Your Proposal

Fix typo if it's unintentional.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
oh... Botany
I was so confused there
