### ISSUE TITLE
Crash when approaching Twilight Forest Urghast castle

### ISSUE THREAD

**Issue by Finitie** [GTNewHorizons/GT-New-Horizons-Modpack#13215]
### Your GTNH Discord Username

Finitie

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Game crashes when trying to get near Urghast castle in the Twilight Forest after defeating the previous boss. Tried to go back to a backup to redo the last boss but it crashes consistently near Urghast castle.

### Crash Report

https://paste.ubuntu.com/p/xhQj6Wtvjc/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
Likely fixed by https://github.com/GTNewHorizons/twilightforest/pull/19  Try grabbing the latest TF release and see if that helps.

**Comment by Finitie** [comment]
Thanks, I got the latest version (TwilightForest-2.4.3.jar) but it results in the same crash and log: https://paste.ubuntu.com/p/4p53WfKNqg/

**Comment by mitchej123** [comment]
Lol... oh god... now it's crashing because of null `currentWorld`

```
java.lang.NullPointerException
    at twilightforest.biomes.TFBiomeDecorator.func_150513_a(TFBiomeDecorator.java:168)
    at net.minecraft.world.biome.BiomeDecorator.func_150512_a(BiomeDecorator.java:105)
    at twilightforest.biomes.TFBiomeDecorator.func_150512_a(TFBiomeDecorator.java:138)
```

![image](https://user-images.githubusercontent.com/1894689/232126479-6911cf6e-f0fb-4e99-bef6-4be9151b70af.png)

**Comment by mitchej123** [comment]
@Finitie Can you reliably reproduce this crash?  I'd love to get a copy of your TF dimension, and the coordinates you're having the issue at.  I've never been able to reliably reproduce the crash, which has made debugging it exceptionally challenging beyond bandaid fixes...

**Comment by Finitie** [comment]
Yes, I've gotten the crash lots of times, trying to find some way around it. This link contains the TF dimension (DIMS 7 if I'm correct): https://www.dropbox.com/s/0nuiopcuegph7r7/DIM7.zip?dl=0
Coordinates: x=528.94, y=50.25, z=-778.29

I did manage to get past it now, by closing multiMC after the crash, then logging into the same save again. Not sure if it's a good idea to just continue after such a crash though.

**Comment by mitchej123** [comment]
We still haven't found the root of the issue, but should be able to add another bandaid workaround.  Will see if I can reliably reproduce in a dev env with your save...
