### ISSUE TITLE
Electrolyzing zirconolite does not give zirconium

### ISSUE THREAD

**Issue by harrynull** [GTNewHorizons/GT-New-Horizons-Modpack#13219]
### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 19

### Type of Server

None

### Your Expectation

Electrolyzing zirconolite should give zirconium

### The Reality

Electrolyzing zirconolite does not give zirconium
![image](https://user-images.githubusercontent.com/7413706/232172957-a430df1f-55f0-4695-8841-d356775a6fbc.png)

### Your Proposal

Add zirconium to the recipe output.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/232173005-2eeb6b75-43e2-4a39-8f0e-d7e44a684adc.png)
