### ISSUE TITLE
Batch mode doesn't overclock correctly

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13218]
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Batch mode should overclock to the highest power tier available to go as fast as it can

### The Reality

Rather than overclocking to the highest power tier available, it will stick to the highest power tier the recipe could go to before hitting 1 tick with batch mode disabled.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
well it depends on the multi currently. But I agree that it needs to be consistent. the current state is not ok.

**Comment by Tommeh1** [comment]
@minecraft7771 I wouldn't consider this a suggestion.
It working on some multies and not for random others seems like a bug to me.

**Comment by minecraft7771** [comment]
It works on PA and PA only, by design. All others work like you described, so you are suggesting to change the design. PA is the outliner here, so if it will changed at all, then all machines will behave as you described.

**Comment by chochem** [comment]
it is technically design but inconsistent and undocumented design lol.

**Comment by minecraft7771** [comment]
Ye but the ticket was actually about changing everything but the PA.

**Comment by Tommeh1** [comment]
The current behavior leads to a massive increase in the required amount of machines, significantly affecting performance while making things very tedious.

**Comment by minecraft7771** [comment]
Well 1 ticking recipes causes huge performance issues too. That's why the intended behavior is not to 1 tick again.

**Comment by chochem** [comment]
the current behaviour (for all but PA) is just lag avoidance via batch, no gameplay impact.

**Comment by Tommeh1** [comment]
> Well 1 ticking recipes causes huge performance issues too. That's why the intended behavior is not to 1 tick again.

And now as a result you're forcing far more machines, negating the gain.

**Comment by chochem** [comment]
same machines as without batch

**Comment by Tommeh1** [comment]
> same machines as without batch

We've literally got dozens of the same machines in some cases stacked on top of each other due to this.

**Comment by chochem** [comment]
what you want is a buff. free infinite parallels at full efficiency for no cost. I am very much against that

**Comment by Tommeh1** [comment]
We've recently gotten our endgame base back to a stable 20TPS(as long as nobody has an ME terminal open), it's a shame to see so much performance go lost over you having the spam the identical machine dozens of times.
