### ISSUE TITLE
Launchpad is not put in Lander/Parachest after rocket launch

### ISSUE THREAD

**Issue by YeahImRose** [GTNewHorizons/GT-New-Horizons-Modpack#13213]
### Your GTNH Discord Username

Rose🌹ロズ#1877

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

In previous versions, the lander or parachest would contain both the rocket and the launchpad upon arrival. This is presumably the behavior expected for 2.3.2.

### The Reality

The rocket is present in the lander or parachest, but the launchpad is missing.

### Your Proposal

Insert the 9 launchpads into the chest.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
hmm, works just fine for me.

**Comment by YeahImRose** [comment]
I'll add that it's with a T1 Rocket to the moon

**Comment by YeahImRose** [comment]
After trying the launch 4 more times, I've not gotten the launch pad back 3 times, and have gotten it back 1 time. Not sure what the factor determining it is, but it's not 100% consistent.

**Comment by chochem** [comment]
well, we will see. I am at 3/3

**Comment by YeahImRose** [comment]
No, it's with base 2.3.2 install

**Comment by YeahImRose** [comment]
Issue still exists:

[https://discord.com/channels/181078474394566657/181078474394566657/1161317350851747850](Discord example 1)
[https://discord.com/channels/181078474394566657/181078474394566657/1149766964835778721](Discord example 2)

**Comment by Majora320** [comment]
To reproduce, quit and rejoin while the lander is falling to the planet. It looks like some kind of NBT save/load bug in EntityLanderBase.
