### ISSUE TITLE
Quest bug: Incorrect Potion IDs in quest: Stable Division Sigil

### ISSUE THREAD

**Issue by Mad-Gnome** [GTNewHorizons/GT-New-Horizons-Modpack#13230]
### Your GTNH Discord Username

Mad_Gnome

### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

In the quest "Stable Division Sigil" 5 of the potions that are listed have the right name, but have the wrong IDs.  This is what is listed in the quest.
Potion of Nausea (8199)
Potion of Weakness (8200)
Potion of Slowness (8202)
Potion of Healing (8197)
Potion of Water Breathing (8205)

### The Reality

It won't stop you from completing the quest, since they are optional tasks.  I did the ritual successfully with the current potion ID's (listed blow)

### Your Proposal

Update the potion IDs to the current ones in game.
Potion of Nausea (8231)
Potion of Weakness (8232)
Potion of Slowness (8234)
Potion of Healing (8261)
Potion of Water Breathing (8237)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
water breathing is 8205 for me. healing is indeed 8197. nausea indeed 8199.

weakness/slowness seems to be more a game problem not really just questbook. There somehow are 2 identical ones. I assume some mod is messing with them?
