### ISSUE TITLE
ME Fluid Pattern Table needs extention for Muddy Monazite receipt

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#13233]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.3.

### Your Proposal

Muddy Monazite has 3 material and a fluid. Fluid Pattern has only 3 Output.

-> If I try to takeover this receipt, client get crashed!

### Your Goal

Please extend fluid pattern for 4 output

It will ease the use of Dissolution Tank receipts.

### Your Vision

allignment of receipt definition and ME pattern

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
crashlog please. just because it doesnt fit shouldnt mean it can just crash

**Comment by Ngar1** [comment]
[Muddy bastanite](https://paste.ubuntu.com/p/3F5gTkrNC6/)

**Comment by Ngar1** [comment]
Muddy Bastanite receipt 
works well

**Comment by chochem** [comment]
those links dont lead anywhere useful?

**Comment by Ngar1** [comment]
please try the first again - I was not familar with this tool

**Comment by Ngar1** [comment]
Same problem with "Digester" receips

**Comment by kstvr32** [comment]
The crash is bad and should be looked into, but we don’t need to expand the fluid pattern terminal. You should be able to use the fluid processing pattern terminal for this recipe which allows way more than 3 outputs.

**Comment by firenoo** [comment]
Can't see ubuntu paste.

Need AE2 version, AE2FC version, and NotEnoughEnergistics version

**Comment by chochem** [comment]
[crash.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11243162/crash.txt)

**Comment by NeroOneTrueKing** [comment]
This is happening to me while using a fluid processing terminal as well. (Attempting to shift-click the [?] for a digester recipe)
https://pastebin.com/yTrPwcHL

**Comment by ShadeNYR** [comment]
Happening to me as well, maybe an issue with muddy monazite rare earth solution because that's the only constant between the two recipes below - 
https://pastebin.com/rRqXJLTr - crash when attempting to click the question mark in JEI for the muddy monazite rare earth solution digester recipe
https://pastebin.com/UwwxNz23 - crash when attempting to click the question mark in JEI for the diluted monazite rare earth mud dissolution recipe

**Comment by combusterf** [comment]
- This bug still happens in the current stable 2.4.0
- Upgrading the pattern terminal to a processing pattern terminal does NOT fix the problem
- All recipes from the Digester and Dissolution Tank are affected

A patch for the corresponding NEI plugin would be very much welcome.
