### ISSUE TITLE
Solar tower tooltip: heat efficiency formula seems incorrect

### ISSUE THREAD

**Issue by Spartends** [GTNewHorizons/GT-New-Horizons-Modpack#13238]
### Your GTNH Discord Username

Spartends#4798

### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 19

### Type of Server

Don't know

### Your Expectation

1. Tried to calculate the maximum amount of solar salt I can insert while keeping heat levels stable around 50000. 
2. Expected to see the greatest heat increase per cycle around 50000 heat

### The Reality

3. Used the formula in the solar tower tooltip in Desmos and it showed that heatEff is greatest at 0 or 10000 instead(a is equal to the currentHeat and the output is the total heat gained per cycle from a max solar tower)
![image](https://user-images.githubusercontent.com/130987644/232474263-b3910271-8374-4249-87e1-743e06ce395d.png)
![image](https://user-images.githubusercontent.com/130987644/232474350-fa70e609-84c2-4acf-9b75-c7d29940ddbe.png)

### Your Proposal

4. I assume that the tooltip formula for heat efficiency meant to be: 
$$\frac{7000}{{|currentHeat - 50000|}^.8 + 7000}$$
 - Heat efficiency would be highest at 50000 then.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Steelux8** [comment]
The tooltip formula might be wrong. I'll check what the output values are depending on heat value.
