### ISSUE TITLE
Add the beeteor

### ISSUE THREAD

**Issue by MeiTianyou** [GTNewHorizons/GT-New-Horizons-Modpack#13236]
### Your GTNH Discord Username

vk#7047

### Your Pack Version

2.3.2

### Your Proposal

Add a meteor that includes bee hives. It would use an alveary as its focus item.

### Your Goal

At present, to get new pristine queens you have three options:

- Generate new chunks
- Spend coins you got by farming nether wasps every five hours
- Use botania, which eats a ton of mana and takes 40 minutes per queen

The botania method is very strong, as it can turn swamer ignobles into pristines. However, sometimes you just want more wild queens for breeding. Adding a meteor with hives would be an easy way to get these on demand.

### Your Vision

Farming for coins isn't very fun, and neither is stacking world accelerators next to a flower and waiting. This would provide a nice, on demand method.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by MeiTianyou** [comment]
I don't know how to get this tagged RFC, but I will develop this feature if people want it.

(opened the issue because it would be new content below LuV)

**Comment by chochem** [comment]
>  However, sometimes you just want more wild queens for breeding. 

you say this is for breeding? I am confused. you really dont need many princesses for breeding. 10-20 are all I ever used for breeding. Less are doable too.

**Comment by MeiTianyou** [comment]
While it is true that you can jump anywhere in your breeding tree by using drones, it satisfies the collectors' itch to keep both a princess and her drones for each species.

**Comment by Ngar1** [comment]
Because of "coins to hive" in QB and many stone hives by mining which can be breeded easily to other variants I see no need for it.

**Comment by chochem** [comment]
so this is just for some ocd reasons, gottcha.

**Comment by EnderProyects** [comment]
There are many useless meteors, so adding one that only spawn mundane hives cant be that bad

**Comment by boubou19** [comment]
coins coins coins tab in quest book already covers this. Why would you use a more convoluted way of getting basic hives?

**Comment by EnderProyects** [comment]
> coins coins coins tab in quest book already covers this. Why would you use a more convoluted way of getting basic hives?

I don't think that having to use coins and quest to get resources is the appointment of the pack, like you could use them, okay, but better have another way to get them ( idk my opinion)

**Comment by MeiTianyou** [comment]
> I agree with a better method of getting new pristines than coin purchases. However I don't see why co-opting meteors for this should be the right solution. If you're already doing bees, you're probably getting resources from bees, and you wouldn't have the need to build up all the infrastructure needed for meteors.

En, I chose meteors for two reasons, the first is being able to call the feature the "beeteor." The second is that implementing this feature will require some work on how meteors are generated, which I hope would have the knock-on effect of letting @ScriptedPiky or others add some meteors which were not-feasible before. 

Really though, I am interested in other ideas, if you have something more fitting I will look into whether or not it's within my ability to do.

**Comment by Ngar1** [comment]
Mining can give you thousands of pristine rocky bees, which you can automatically rebreed for any other variety. With 5-8 drones or cycles it is done.
(I am not such a great fan of meteors, because of their impact) 

Excaple filling input chest and forget:
![grafik](https://user-images.githubusercontent.com/7759876/233284969-40c7002c-88e4-4f43-a701-2bd95fa8445e.png)
Below placed invisible item conduit take trash out

**Comment by EnderProyects** [comment]
> (I am not such a great fan of meteors, because of their impact) 
 What do you mean?

**Comment by repo-alt** [comment]
Theoretically it is not hard to add rocky hives support to the multiblock miner, which should produce "enough" bees

**Comment by EnderProyects** [comment]
Space hives to the space elevator drones 😹😹

**Comment by MeiTianyou** [comment]
> Theoretically it is not hard to add rocky hives support to the multiblock miner, which should produce "enough" bees

I think this is also a great solution, but it might upset some people who suddenly have their ore processing chain choking on bees/hives. MBMs already have a screwdriver behavior, do you have a suggestion on a way to toggle whether or not it mines hives?

**Comment by Alastors** [comment]
I'm against this, it just doesn't make sense and like boubou said, is already covered by the coins tab, @Runakai1 get ya butt in here boy and comment

**Comment by combusterf** [comment]
Ender quarry gives plenty of bees when you're LuV. On the officials the only additional step is that you have to move to the twilight forest (or the everglades) because of overworld limitations.

A better buff would be to add hives back to the ore finder wand, which was a very useful feature a few years ago despite being a very manual one.

**Comment by Gofer2x** [comment]
My own two cents - I agree on both the beeteor being a funny and useful idea on its own, and the changes to the meteor code opening up more possibilities for future meteors.

I'd also argue wanting to have a princess + drone pair of each type isn't some type of ocd behavior, but just playing it smart for the long run. Having bees of each type makes for easier future breeding.

As to the current methods for obtaining more princesses, the coins tab technically works but it really shouldn't be *the* way for it. You only get 1 beehive from each quest, have to click through them a whole lot, and there's also the waiting time. Just really annoying for getting large amounts of pristines.

Getting bees through mining is pretty counterintuitive too. Your average player probably wouldn't think of it at all.

I think another good solution to the bee problem would be adding a thaumcraft infusion crafting recipe for (multiple per recipe) beehives. Some annoying combs/waxes, royal jelly (aromatic lumps if you're feeling funny), honey, and some essentia. Thaumcraft also already has a bee connection through its Apimancy tab. I might make that its own suggestion/issue.
