### ISSUE TITLE
Server crashing upon start up

### ISSUE THREAD

**Issue by Knifedude1** [GTNewHorizons/GT-New-Horizons-Modpack#13248]
### Your GTNH Discord Username

Knifedude#8836

### Your Pack Version

2.3.2

### Your Server

private server 

### Java Version

Java 8

### Type of Server

None

### Your Actions

I tried to restart the server because one of the players had problems logging on than upon starting up the server it kept on crashing. 

### Crash Report

[crash-2023-04-18_05.31.38-server (2).txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11258207/crash-2023-04-18_05.31.38-server.2.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
same as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13146
that one is closed so I will leave this open

**Comment by chochem** [comment]
did you update/change any mods?

**Comment by Knifedude1** [comment]
No I didn’t update or change any of the mods.

**Comment by minecraft7771** [comment]
Seems to be some bad install, since the mod GTNH intergalactic is not supposed to be missing. Check if you have that mod in your mods folder. But the crash is fixed anyway by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/563
