### ISSUE TITLE
Dimensionally Transcendent Problem Forge

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#13255]
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.3.2

### Your Proposal

On this issue i want to talk about DTPF problems founded by me and other users from #russian-general discord channel.

1. Hatch problem. DTPF cant skip recipe, if it cant do it because of low coil tier.
2. Recipes problem. DTPF have a lot of recipes, but a lot tiered recipe have no circuits (like neutronium).
3. Sound problem. You cant off DTPF sound using muffler upgrade on controller

### Your Goal

We can offer these options to solve problems:

1. Add option to skiping recipe, if it cant do it because of low coil tier.
2. Add programmed circuits to all recipe with whis rule: if recipe use T1 catalyst (maded from 4 plasms) it have circuit with 1 configuration, 2 for T2 catalyst 3 for T3 and 4 for T4. If recipe use something else, like combs it have 10+catalyst tier configuration. What about recipes differing only coil coil tier? (Why you need lot-tier ceripe if you have high-tier?) it can have +5 configuration, added to prevous rules.
2.1. Add bus separation mode.
3. Muffler upgrade used on controller can block all sounds form this multiclock.

### Your Vision

With proposed features, DTPF will be nicer to use and automate. You will have the opportunity to use your first DTPF like other autocrafting machines.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Cinobi** [comment]
yes, make sence. Lusing all discount due to recalculating recipes after server restart is very sad.
