### ISSUE TITLE
Server crash on ordering smth on blocking ME interface

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/GT-New-Horizons-Modpack#13258]
### Your GTNH Discord Username

monroth#4236

### Your Pack Version

2.3.2

### Your Server

private server, single player

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

Place dual ME interface (cubic) that touches nonempty quad input hatch with one side, and transvector that is not connected to anything with another side. Put it in blocking mode. Order something that has pattern on that interface. Crash the server.

It happened on MP server once (and now we can't turn server on, i suppose ME maintainer orders something on this interface automatically), then I reproduced same thing in SP once. After that I could not reproduce it in that SP world.

### Crash Report

crash report after SP crash https://paste.ubuntu.com/p/D22vDg7Kmt/

crash report after second MP crash (when we tried to start server again after first crash)
[crash-2023-04-19_18.18.52-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11277105/crash-2023-04-19_18.18.52-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miaowwwwww** [comment]
i think this is the same problem i posted yesterday #13252

**Comment by firenoo** [comment]
I can't see the first crash but the second one has been fixed, reopen if the first one was differnt
