### ISSUE TITLE
Fish Catcher gives Thaumcraft Iron Nuggets

### ISSUE THREAD

**Issue by BeepBeep20** [GTNewHorizons/GT-New-Horizons-Modpack#13253]
### Your GTNH Discord Username

BeepBeep2020

### Your Pack Version

2.3

### Your Proposal

The fish catcher gives TC iron nuggets not the GT version.

### Your Goal

The nuggets convert to GT iron nuggets when put into a storage drawer. 

This means if you get a nugget & put it into a storage drawer manually the next nugget that comes along won't automatically go into that drawer because the drawer now has GT iron nuggets in it not the TC version that the fish catcher produces.

### Your Vision

It would make storing these nuggets easier.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Cardinalstars** [comment]
Which fisher is this? The Zuhai Port?

**Comment by King65868** [comment]
The GT++ fish catcher I would guess, it’s a single block

**Comment by BeepBeep20** [comment]
Yes, it's the single block GT++ fish catcher.
.

**Comment by BritishCynic** [comment]
I'm on 2.3.3 and the catcher for me is outputting GT iron nuggets.
