### ISSUE TITLE
Precise Assembler refuses to craft Iridium Neutron Reflector's C2 Recipe using Stocking Bus

### ISSUE THREAD

**Issue by SweptWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#13257]
### Your GTNH Discord Username

Swept#2000

### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

![ljhb](https://user-images.githubusercontent.com/49448379/233162433-252eb731-74ae-4aa8-975c-558111699e95.png)

### The Reality

Refuses to craft in a Precise Assembler in a stocking bus.
![image](https://user-images.githubusercontent.com/49448379/233162535-ab66e775-79d5-4866-8511-e43317489c46.png)

It crafts fine when the recipe is in to a normal bus. 

### Your Proposal

This recipe should work in a stocking bus.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hiagg** [comment]
additional info, you CAN do this recipe if you use circuit 1

**Comment by TimberDimber** [comment]
Still relevant in 2.3.4
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22298720/0fd95c3d-6e58-417d-a67f-23474ccdae44)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22298720/1f06f904-4d89-427d-aa96-dad3c4253265)

**Comment by minecraft7771** [comment]
There is a good chance this is fixed by https://github.com/GTNewHorizons/GoodGenerator/pull/176. But I didn't test this case in particular so I will not link it in the PR. It would be nice if someone could report back when they get to try this new version when it fully releases to dev.
