### ISSUE TITLE
Lignite coal for steel production 

### ISSUE THREAD

**Issue by captainp0wer** [GTNewHorizons/GT-New-Horizons-Modpack#13261]
### Your GTNH Discord Username

Captain_p0wer

### Your Pack Version

Unsure, at work. Assume current. Sorry

### Your Proposal

If sugar coke, cactus coke and charcoal can be used for steel production, I think lignite coal should be able to be used too. Although lignite coal may be weaker then regular coal, coal coke and charcoal, I don't think it's weaker then sugar coke and cactus coke, although I could be wrong haha

### Your Goal

An additional fuel to use for steel. Other than basic beginner fuel, there isn't much use lignite coal. 

### Your Vision

Again just one more fuel source for steel production, I don't think it would impact the pack too much. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
Lignite coal would be weaker than sugar and cactus coke, yes. I added the steel-producing recipes to those cokes from other players' requests, to make those unique automations more useful, but I don't see why lignite coal (not coke) would be a steel-producing coal.
