### ISSUE TITLE
Stockroom Catalog Dosen't List GT Ores and Dusts Correctly

### ISSUE THREAD

**Issue by Iamthepizzagod** [GTNewHorizons/GT-New-Horizons-Modpack#13268]
### Your GTNH Discord Username

AwesomeAliza#5430

### Your Pack Version

2.3.0

### Your Server

Personal Server hosted on Oracle Cloud

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

I started tracking my ore and dust and ingots chests to be able to see at a glance what I have and don't have. I want to be able to see the precise names of the ores and dusts I have, especially rarer ones but all of them in general.

### The Reality

https://cdn.discordapp.com/attachments/234936569360809996/1098789841879191572/image.png

All ores and dusts are listed as "%material/material ore/material dust"

### Your Proposal

Make it so that the correct names of dusts and ores are displayed in the stockroom inventory book.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
there is like 5 stale tickets about this already lol. And its ARR. dont get your hopes up. see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4828 for example
