### ISSUE TITLE
GT++ Assembler doesn't work

### ISSUE THREAD

**Issue by Fiyorin** [GTNewHorizons/GT-New-Horizons-Modpack#13267]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.3.2+

### Your Server

private

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

apparently in newer versions the gt++ assembler (large scale auto-assembler) doesn't work anymore

tested with small coils and a uhv muffler

see also: https://discord.com/channels/181078474394566657/522098956491030558/1096199869556850730

i'm using these updated mods:

![image](https://user-images.githubusercontent.com/61357/233495454-95e95b6c-191d-44a3-974e-6053cc3c8517.png)

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AtomicGrog** [comment]
I'm on plain release 2.3.2 server with the only notable additional mods being Forge essentials and can confirm this machine is working fine. I made a few stack of small coils to test same recipe etc.

Do you get any errors in the logs when loading and/or trying to use the machine?

**Comment by Fiyorin** [comment]
it was working fine on 2.3.2
nothing appears in the logs
