### ISSUE TITLE
lwjgl3ify-1.1.38-forgePatches.jar download fails

### ISSUE THREAD

**Issue by cek0060** [GTNewHorizons/GT-New-Horizons-Modpack#13272]
### Your GTNH Discord Username

coevke#8051

### Your Pack Version

2.3.0

### Your Server

NA

### Java Version

Java 17

### Type of Server

None

### Your Actions

http://jenkins.usrv.eu:8081/nexus/content/groups/public/com/github/GTNewHorizons/lwjgl3ify/1.1.38/lwjgl3ify-1.1.38-forgePatches.jar

Forgepatches.jar above isn't available on jenkins, causing issues when launching pack for the first time. Version seems to be missing.

### Crash Report

![image](https://user-images.githubusercontent.com/112097944/233753299-0b44b27f-5d95-4e19-ad23-b0b33e744459.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
Reuploaded

**Comment by chochem** [comment]
should be fixed now
