### ISSUE TITLE
mixer pa making hss-s dust makes osmiridium instead

### ISSUE THREAD

**Issue by Fiyorin** [GTNewHorizons/GT-New-Horizons-Modpack#13278]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.3.2+

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

if you setup a PA with mixers inside and feed it the recipe for HSS-S dust with circuit #2, it makes osmiridium dust instead

looks like a broken recipe
works fine in a gt++ mixer and a singleblock mixer

happens on 2.3.2 with these newer mods:
![image](https://user-images.githubusercontent.com/61357/233786331-9b2eaba6-ebe8-4882-9cbb-7b0fea5d9e6a.png)

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
just sounds like you are not separating busses and have a circuit 1 somewhere

**Comment by Fiyorin** [comment]
if you insert iridium + osmium (no circuit) it makes osmiridium, although nei says it requires circuit #1

"chochom: best bet would be PA cant handle RA2 and deletes circuits for some reason"

**Comment by chochem** [comment]
can confirm the bug. it doesnt need any circuits in PA right now

**Comment by chochem** [comment]
and its not just osmiridium. nichrome as well for example. but probably a lot lot more.
