### ISSUE TITLE
strong redstone signals broken

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#13270]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.3.2+updated mods, using gregtech-5.09.42.53

### Your Server

sp

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

if I turn on strong signal it should stay on.

### The Reality

turns back to weak after a tick or a few. (specifically energy detector cover on LSC turned strong with soldering iron)

### Your Proposal

Probably caused by
https://github.com/GTNewHorizons/GT5-Unofficial/pull/1816

I dont understand what the was supposed to fix anyway. maybe just revert and have another look at what that was about.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Fiyorin** [comment]
maybe related: https://github.com/GTNewHorizons/GT5-Unofficial/pull/1825

currently strong signals aren't being sent (except on the fluid dector cover if you activate the new checkbox)

**Comment by chochem** [comment]
I used the Soldering Iron. It works for a moment but then turns off again.

**Comment by chochem** [comment]
@NexusNull any ideas?

**Comment by NexusNull** [comment]
I believe that my commits caused this bug. It's best if we revert them for now.
I wasn't aware that there were other options to turn a cover redstone signals into a strong signals. I'll investigate this later, for now please revert.

**Comment by chochem** [comment]
alright so both https://github.com/GTNewHorizons/GT5-Unofficial/pull/1816 and https://github.com/GTNewHorizons/GT5-Unofficial/pull/1825 should be reverted. however this interacts with the forgedirections change so no automatic PR. and if we want to test a PR on master its better to wait a few days until forgedirections is done so that stuff can be tested. dont know if nexus will do it or someone else
