### ISSUE TITLE
Crash on opening cover guis

### ISSUE THREAD

**Issue by Lyfts** [GTNewHorizons/GT-New-Horizons-Modpack#13280]
### Your GTNH Discord Username

Lyft#9830

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

Opening the gui for item detector cover, fluid detector cover or void overflow cover insta crashes the game. Machine controller cover, conveyors or pumps have no problem.

### Crash Report

[crash-2023-04-22_16.13.59-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11301553/crash-2023-04-22_16.13.59-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment]
Can report that it was AlkGuiHider that caused the issue, which is not a mod shipped with the pack and thus is most likely not caused by gtnh. I will close the issue.

**Comment by miozune** [comment]
Update ModularUI and now you can use AlkGuiHider without crash https://github.com/GTNewHorizons/ModularUI-old/releases/tag/1.1.3
