### ISSUE TITLE
Apiarist's pipe is missing many species

### ISSUE THREAD

**Issue by nhouser9** [GTNewHorizons/GT-New-Horizons-Modpack#13298]
### Your GTNH Discord Username

Secret_Fish#9978

### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

I am trying to use the Apiarist's Pipe to filter bees by their species. I expected that I could do this for any bee species. 

### The Reality

The pipe works fine for the species that you can select in the UI, but there are a bunch of species that are missing from the UI and therefore cannot be filtered. For example: mysterious, arcane, supernatural, watery, earthen, fiery, windy, pupil, scholarly, and many many more. 

### Your Proposal

Include all the bees in the pack in the Apiarist's Pipe UI so that it is usable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@nhouser9 can you show which recipes are missing. Are they in older versions ?

**Comment by nhouser9** [comment]
@Dream-Master I'm not sure what the best way to show this is. I'll attach a few screenshots. 

The only way to select a bee in the Apiarist's Pipe is to click through each species. When clicking through it goes straight from Esoteric to Charmed, skipping over Mysterious and Arcane. They exist and can be bred but aren't filterable in the Apiarist's Pipe UI. This is just one example, there are many more species missing as well.

<img width="216" alt="Screenshot 2023-04-24 at 10 59 40 AM" src="https://user-images.githubusercontent.com/15316128/234036340-36e44d76-55ab-4fcd-8f75-4ab447d0c682.png">
<img width="244" alt="Screenshot 2023-04-24 at 10 59 19 AM" src="https://user-images.githubusercontent.com/15316128/234036344-29e92d69-55f0-463f-94b4-e769996a9581.png">

**Comment by Cardinalstars** [comment]
@nhouser9 is this issue only affecting MagicBees bees?

**Comment by nhouser9** [comment]
@Cardinalstars It's hard for me to tell. I don't know which bees are MagicBees bees. I've taken the past hour to click through each bee in the pipe UI and compare to NEI. As best as I can tell here's a full list of what's present in NEI but missing in the pipe UI:

supernatural, etherial, watery, earthen, fiery, windy, pupil, scholarly, savant, aware, spirit, soul, sulking, ghastly, spidery, smouldering, brainy, poultry, beefy, porcine, batty, sheepish, neighsayer, catty, timely, lordly, doctoral, infernal, hateful, spiteful, withering, oblivion, nameless, abandoned, forlorn, draconic, ferrous, auric, cuprum, stannum, argentum, plumbum, aluminum, ardite, cobalt, manyullyn, diamandi, esmereldi, apatine, silicon, certus, fluix, mutable, transmuting, crumbling, invisible, aer, ignis, aqua, solum, ordered, chaotic, vis, rejuvinating, empowering, nexus, flux, pure, ravening, wispy, void, electrum, platinum, nickel, invar, bronze, rooted, botanic, blossom, floral, vazbee, aelfheim, skystone, frugal, austere, exotic, edenic, ender, spectral, phantasmal, icy, glacial, vindictive, vengeful, avenging, leporine, merry, tipsy, tricky, agrarian, miry, boggy, monastic, secluded, hermetic, arid, barren, desolate, decomposing, gnawing, decaying, skeletal, creepy, robust, resillient, corroded, tarnished, rusty, leaden, galvanized, lustred, glittering, shining, valuable, lapis, emerald, ruby, sapphire, diamond, unstable, nuclear, yellorium, cyanite, plutonium, ancient, primeval, prehistoric, relic, fossilized, resinous, oily, distilled, refined, tarry, elastic, river, stained, growing, thriving, blooming, sweetened, sugary, ripening, fruity, bovine, caffinated, damp, sodden, fungal, furious, volcanic, glowering, infectious, virulent, vicious, gluttonous, sticky, corrosive, caustic, acidic, excited, energetic, ecstatic, frigid, absolute, shadowed, darkened, abyssal, maroon, prussian, natural, bleached, sepia, amber, turquoise, indigo, slate, azure, lavender, lime, fuscia, ashen, celebratory, jaded, chad, hazardous, quantum, abnormal, spatial, mystical, scummy

**Comment by Cardinalstars** [comment]
From what I can see, this is actually intended to happen. You can only filter species if you discover them. (this doesn't even seem to work right from what I'm seeing) I think this should change so that the pipe is usable for filtering species you are trying to breed.

**Comment by nhouser9** [comment]
@Cardinalstars It definitely isn't working that way now. I've had purebred lapis drones for a long time and I still can't filter for them. And I can filter for all the space bees that I'm not even close to discovering.
