### ISSUE TITLE
AE2FC fluid import bus crash when placing Ender IO conduit next to it

### ISSUE THREAD

**Issue by Goldensunboy** [GTNewHorizons/GT-New-Horizons-Modpack#13291]
### Your GTNH Discord Username

Goldensunboy#4061

### Your Pack Version

2.3.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

Placed an Ender IO item conduit next to an AE2FC fluid import bus and the world crashed, but not right away. Seemed like it crashed after AE2 did it's usual "thinking" to determine connected network components. Reloading the world would allow me in for a couple seconds before it crashed again. There was actually enough time to quickly break the conduit before it would crash, after which it stopped crashing for me locally.

![2023-04-23_11 08 49](https://user-images.githubusercontent.com/2107532/233857442-c734608d-3a7a-4941-b2b5-592640081bef.png)

### Crash Report

Initial crash:

[crash-2023-04-23_11.05.31-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11304507/crash-2023-04-23_11.05.31-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Brumpbo** [comment]
I have the same issue with the exact same description.
[crash-2023-04-24_19.40.31-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11325972/crash-2023-04-24_19.40.31-server.txt)
