### ISSUE TITLE
NEI KeyManager CME when joining server

### ISSUE THREAD

**Issue by Zilacon** [GTNewHorizons/GT-New-Horizons-Modpack#13292]
### Your GTNH Discord Username

Zilacon

### Your Pack Version

2.3.2

### Your Server

GTNH.APOCGAMING.ORG

### Java Version

Java 8

### Type of Server

Crucible

### Your Actions

Installed fresh pack on technic, launched, joined server, and crashed to main menu.

### Crash Report

[crash-2023-04-23_11.23.10-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11304539/crash-2023-04-23_11.23.10-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment]
@Zilacon @Tommeh1 How often does this happen for you? Did you encounter this crash only once or would you be able to reproduce it again?

**Comment by Zilacon** [comment]
Seems to happen the first time you join any server. And it will happen on the same server again if you do a fresh install.
From my experience anyways, We are a new server so dont have many players to give reports yet, just me and staff running into this.

**Comment by Denostrov** [comment]
@wlhlm Just happened to me aswell. Joining a single player world right after launching the pack normally, not a fresh install. Can't reproduce again even after relaunching pack and rejoining backup copy of the world.
[crash-2023-04-23_11.23.10-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11389949/crash-2023-04-23_11.23.10-client.txt)
