### ISSUE TITLE
almost all #10 circuit bending machine recipes are missing

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13293]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.3

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

restore them

### The Reality

for example, Pd foil has only one recipe,
![image](https://user-images.githubusercontent.com/49871378/233858940-5e820ef3-6ef3-4696-a6cb-5152464de19b.png)
![image](https://user-images.githubusercontent.com/49871378/233858962-e47f7101-bcce-4960-ab03-f9e5528a039f.png)
only 37 pages for #10 circuit

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
a little add on. 
![image](https://user-images.githubusercontent.com/49871378/233859134-688bcba8-2b96-4d42-a5d6-8102635e977f.png)
the circuit one in plate recipes are gone too

**Comment by ramseyspace** [comment]
Can confirm on this. I tried with circuits and still. Its not recipe hidden, indeed actually missing.
