### ISSUE TITLE
clear glass duplication in cutting machine

### ISSUE THREAD

**Issue by Fiyorin** [GTNewHorizons/GT-New-Horizons-Modpack#13308]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.3.2+ with newer gt5u

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

found this weird recipe that allows glass to be duplicated

![image](https://user-images.githubusercontent.com/61357/234084892-c9fcfffb-aa54-426d-85ff-ed4a7e4c53cc.png)

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Fiyorin** [comment]
also appears with all sorts of wood and stone slabs

**Comment by chochem** [comment]
yea fixed that already
