### ISSUE TITLE
Alveary Sieve assembler recipe error

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13300]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.3

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

fix the assembler recipe.
(The Alveary Sieve can be made with forestry machine, i am writing this only to make the assembler recipe work.)

### The Reality

1.Alveary Sieve only accept unknown pollen in assembler recipe.
2.the tubes in forestry machine and the assembler are not consistent.(iron & emerald)

![image](https://user-images.githubusercontent.com/49871378/233878355-75f5a50e-117d-43a4-b0ee-3b7d52c43f83.png)
![image](https://user-images.githubusercontent.com/49871378/233878623-0b695407-d299-40f2-a72a-b5691a93374f.png)
![image](https://user-images.githubusercontent.com/49871378/233878640-7e0e6e3a-7637-41ca-ba14-6b9bd53ae1ca.png)

i tested in sp, only the unknown can be used to craft in assembler.

### Your Proposal

1. change the unknown to something easier 
2. make the tube in both recipes to be the same.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
btw, the forestry recipe is fine, so i can still make this thing. just the assembler recipe need a fix.

**Comment by miaowwwwww** [comment]
just realized the tubes are not consistant. iron in assembler but emerald in forestry machine.

**Comment by BlueWeabo** [comment]
The chad bee is 1 way of getting that pollen. It also works with any tree pollen. So if you have apple oak saplings and grow them you can then use a pollen collection kit to get said pollen.

**Comment by miaowwwwww** [comment]
i am talking about the ASSEMBLER!

**Comment by miaowwwwww** [comment]
the assembler recipe is not accepting anything other than the unknown one. just tested.

**Comment by BlueWeabo** [comment]
Currently no GT machines accept ore dicted recipes. @Runakai1 this one is for you to decide. Either change the pollen to something else OR have fun adding oredict support to the recipe search and consume.

**Comment by joshaup1999** [comment]
This must have broke in 2.3.3, the recipe had other options in 2.3.2

**Comment by chochem** [comment]
> Currently no GT machines accept ore dicted recipes. @Runakai1 this one is for you to decide. Either change the pollen to something else OR have fun adding oredict support to the recipe search and consume.

GT can do oredict supported recipes (by making multiple). thats basically what this entire folder of recipes is about https://github.com/chochem/GT5-Unofficial/tree/master/src/main/java/gregtech/loaders/oreprocessing
but just using some basic version might be fine
