### ISSUE TITLE
Copper Wand Cap VIS too high to build during Iron Capped Greatwood Wand Quest

### ISSUE THREAD

**Issue by tbullock** [GTNewHorizons/GT-New-Horizons-Modpack#13307]
### Your Pack Version

2.3.0

### Your Proposal

Hi there,

The quest "Iron Capped Greatwood Wand" suggests building either an iron capped OR a copper capped greatwood wand as part of the progression to build the gold capped version of the wand.

However, the VIS requirements are too high to make the copper wand because of the 10% VIS penalty of the introductory iron capped thaumcraft wand.

![image](https://user-images.githubusercontent.com/1172997/234077087-d2fa0f90-2a69-419b-b4b6-ed576ff315ca.png)

The copper version of the wand requires 25 VIS but the penalty puts that up to 27.5 making it uncraftable during normal progression. Although it's possible to just make an iron capped wand as per the quest title, the copper wand should have it's VIS requirements lowered so that it can also be crafted (I suggest 22 VIS) at this stage of the game.

![image](https://user-images.githubusercontent.com/1172997/234078974-2dadec27-53d9-4efc-b0f6-32bc42d26e20.png)

### Your Goal

Lower the VIS requirements of the copper capped greatwood wand to 22VIS

### Your Vision

The quest description would align with what's actually possible at this stage of the game.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
you have zero discounts. try the help channel on discord for basic stuff like this.

**Comment by tbullock** [comment]
Yes I understand that there are zero discounts, that misses the goal of the the report. The issue is not that there isn't a mechanism to circumvent the VIS restriction, but rather, the quest progression to the point here hasn't made it plausible to receive such a discount by this point in the quest hierarchy.

**Comment by Srdra2k3** [comment]
I cannot find that quest on 2.3.0, are you sure you did /bq_admin default load after updating?

**Comment by chochem** [comment]
I mean if they actually read the quests they would also have gold caps not iron, so no malus...

**Comment by tbullock** [comment]
Pardon but this is incorrect again.

This is enroute to the gold cap quest. The player would not have gold caps by this point.

The issue here is that in normal progression TOWARDS the gold caps, the player is suggested to use copper caps. By the point in the quest hierarchy that the player is asked to do this, there is not a normal mechanism to receive the vis discount.

**Comment by tbullock** [comment]
Just to emphasize the ordering

The quest circled in orange suggests the copper wand caps, the earliest a player normally should be able to make it is the cyan circled quest

![image](https://user-images.githubusercontent.com/1172997/234105005-5114b55a-9ab8-4751-841c-f420a4815d12.png)

**Comment by tbullock** [comment]
Sigh; you're correct, my apologies for wasting your time here.

When reading through this we can misread that the gold caps were to be used only later on, not that we should make another regular wooden wand with gold caps right away.

The wording of that top quest could probably be improved though to not cause such confusion but it's not strictly incorrect.
