### ISSUE TITLE
2.3.3 Broken / Missing recipes

### ISSUE THREAD

**Issue by Borjomm** [GTNewHorizons/GT-New-Horizons-Modpack#13309]
### Your GTNH Discord Username

Borj♿m#2232

### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Java 19

### Type of Server

None

### Your Expectation

You can post all the missing/broken recipes for 2.3.3 under this post

### The Reality

Some general changes I noticed:
- [x] 13 DT recipes with circuits are missing (Heavy oil only has one recipe (for lubricant) instead of three
- [ ] About 100 Assembler recipes are also gone (14362 recipes in 2.3.2, 14259 recipes in 2.3.3)
- [x] Glass pane recipe in the cutting machine outputs glass as well (duping)
- [ ] Some recipes in cutting machines are missing as well (7633 recipes in 2.3.2, 7514 recipes in 2.3.3)
- [x] A bunch of weird compressor recipes (probably fixed already)

### Your Proposal

Please, add more recipes in comments below

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
counting numbers is not particularly helpful sorry

**Comment by Borjomm** [comment]
I will dive into it a bit later

**Comment by Fiyorin** [comment]
input bus uv requires 2 obsidian chests (used to be 1)

**Comment by ChaoticTabris** [comment]
Gold Foil and Electrum Foil recipes are also missing from the Bending Machine

**Comment by chochem** [comment]
> Gold Foil and Electrum Foil recipes are also missing from the Bending Machine, when I tried circuit 10 it output normal plates instead.

please update gt https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.42.80
