### ISSUE TITLE
all infinity tinker parts (made in dire crafting table) is gone in 2.3.3

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13315]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.3

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

get them back
the screenshot is from 2.3.2
![`CM{JDQOVS2(0(`KO5OGPQN](https://user-images.githubusercontent.com/49871378/234186382-91b2c357-b3b4-46e7-84c5-f574288456a9.png)

### The Reality

![B0)7 U %T2JQC3}@3@0{ {2](https://user-images.githubusercontent.com/49871378/234186402-6b34f3fa-8e0f-453b-ac07-be17c45e3533.png)
the total number of "infi ingot crafts" in dire table went from 37 to 8,lol.

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Connor-Colenso did you remove them by acident with your last avaritia cleanup pr ?

**Comment by Dream-Master** [comment]
re add with http://jenkins.usrv.eu:8080/job/Avaritia/69/
