### ISSUE TITLE
Neutronium(black) tinker items not showing correct name

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13314]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.3

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

fix the name.

### The Reality

![image](https://user-images.githubusercontent.com/49871378/234181607-8e1b285e-8914-4ce5-8471-55e9cbd0a40b.png)
![image](https://user-images.githubusercontent.com/49871378/234181641-12cf33a7-867d-4fba-afcb-6eb2876152e3.png)
![image](https://user-images.githubusercontent.com/49871378/234182286-9c07ca7b-4b6a-401e-be9f-2fe7e50e12a1.png)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
The first item is an avaritia block . Seems all infinity items affected ?

**Comment by miaowwwwww** [comment]
just Neutronium(black). infi is fine.

**Comment by miaowwwwww** [comment]
wait, i remember having some infi crazy-ass tinker parts crafted through dire crafting, are they all gone?
![image](https://user-images.githubusercontent.com/49871378/234183542-320e70d7-9578-4f57-8055-1cb0743daeed.png)

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/234227316-14f09517-7244-4e88-afe9-e919805040f6.png)
the seem to exist in NEI, but not in any recipes

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/808a5ee36ab374d892f6d41f01066c574d0f119a
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/9e187809973321409c9c7932dae0e1de6de7711f
