### ISSUE TITLE
ThaumicTinkerer KAMI Ichorium Recipe Reverted?

### ISSUE THREAD

**Issue by Aarliiyana** [GTNewHorizons/GT-New-Horizons-Modpack#13311]
### Your GTNH Discord Username

Aarliiyana#7897

### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Other versions in between

### Type of Server

Single Player

### Your Expectation

Ichorium recipe to include Osmiridium.

Java Version: 1.8.0_241

### The Reality

Ichorium recipe has reverted to Vanilla TTKami.

### Your Proposal

Make the recipe painful again please. <3
![2023-04-25_09 15 39](https://user-images.githubusercontent.com/131723535/234136879-d5764107-7fe7-459a-8533-8bf1868d2387.png)
![2023-04-25_08 53 54](https://user-images.githubusercontent.com/131723535/234136913-aa0f9de1-3505-4933-a9ce-ac03fa7b3ae1.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
![image](https://user-images.githubusercontent.com/49871378/234154279-0291eaac-a114-4f07-aa25-8c8a72605794.png)
i'm in zeta, 2.3.3, no such problem.

**Comment by chochem** [comment]
looks fine for me too on the nightly that dream made (24/4)

**Comment by Quetz4l** [comment]
The problem is in the improperly installed pack (The scripts didn't work)
