### ISSUE TITLE
Transvector interface breaks blocking mode on dual interface

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/GT-New-Horizons-Modpack#13335]
### Your GTNH Discord Username

monroth#4236

### Your Pack Version

2.3.2

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Put a dual interface for my chem recipes. One side touches quad input hatch, other side touch transvector that looks on input bus.
Turn on blocking mode (btw, probably related issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13258, so if you try to reproduce, turn on blocking _after_ you connect transvector). Ordered two recipes that needed 2 liquids to craft. Expected ME to put these liquids into quad hatch, wait untill it is empty, then put another two liquids.

### The Reality

It puts all 4 inside. It does not matter if input bus is empty or not. 

If transvector is destroyed, or replaced with either remote interface or inventory relay (even inventory relay that look on transvector), then blocking start to work.

### Your Proposal

Make blocking work with transvector interface.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by C0bra5** [comment]
I've also encountered this bug as I use transvector interfaces in a couple of setups for my on-demand machines; here is a video of it:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17766417/fc66e113-84ea-4e33-8484-4d405c56a0d8
