### ISSUE TITLE
let neutronium energy cell transfer ae energy to other cells

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13346]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.3

### Your Proposal

let neutronium energy cell transfer ae energy to other cells

(btw it looks funny to me that the cell right next to the endless power supply is empty.)
![image](https://user-images.githubusercontent.com/49871378/235285316-3871b368-9d08-4225-9ed0-10886a031cc2.png)

### Your Goal

let neutronium energy cell be the real endless ae power.

(this is mentioned in #11540)

### Your Vision

for now, every time server restarts, ME Quantum Ring in B world goes offline even though the network has a neutronium energy cell in world A and a normal energy cell in world B. I think letting it allow power transfer would make the experience better and reasonable.
(I do know it is pretty easy to setup some other power for ring usage, I just think this feature would be reasonable.)
### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I mean you should be rich enough to have a neutronium cell per quantum ring, no?

**Comment by miaowwwwww** [comment]
yeah i can just put one neutronium cell per ring, that's what I did in zeta, just think this suggestion makes more sense.
