### ISSUE TITLE
[Thaumcraft QOL] Add Alchemical Grate Mod to simplify working with the Adv. Alc. Furnace MB

### ISSUE THREAD

**Issue by IkarusFalling** [GTNewHorizons/GT-New-Horizons-Modpack#13356]
### Your GTNH Discord Username

//Null#7465

### Your Pack Version

2.3.0

### Mod Name

Alchemical Grate 

### The Mod to Add

Adds a Grate which can be placed inside the Adv. Alc. Furnace to make it have a regular Inventory and not rely on Dropped Items into it (Published under GPL (pretty sure thats an Open Source License?) Github Repo: https://github.com/TechnicianLP/AlchemyGrate )

### Your Reason

Would Simply working with the Advanced Alchemical Furnace Multi as it would remove the need to have Dropped Items in it and potentially remove the danger of accidentally letting it overfill and lag the server or Singleplayer besides the issue of having Entities constantly loaded

The only alternative I found was using an Arcane Dropper and a Translocator with stocking on which still requires Dropped Items while can escape if Pushed sufficiently 

### Preliminary Investigation

Recipe needs to be looked at if its appropriate have not noticed any Lag while pushing large Quantities of Materials through the Grate (2 Grates at 128 Redstone Blocks every roughly 4 seconds) 

I honestly don´t know how to do a proper Stresstest for it but considering its safer then the regular one that alone should be big favour for it (no risk of overspilling)

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Chaoschaot232** [comment]
License looks good: https://github.com/TechnicianLP/AlchemyGrate/blob/main/LICENSE.md

Since this Mod add's only one Block maybe we could simply implement it with a mention into Thaumic Horizons instead?

From what it does I am happy to see it implemented within the pack 😊

**Comment by chochem** [comment]
its LGPL, not GPL. so thats better anyway. technicianLP is also active in the discord and wants it included. Putting it in another mod would also work. But please not Thaumic Horizons, that doesnt have a good license.

**Comment by Chaoschaot232** [comment]
> its LGPL, not GPL. so thats better anyway. technicianLP is also active in the discord and wants it included. Putting it in another mod would also work. But please not Thaumic Horizons, that doesnt have a good license.

Ah, excuse me for my mistake here. I assumed that we have had our own Mod adding stuff but this comes from the coremod so I'll put it in there :)

I am currently thinking about it's recipe :)

**Comment by chochem** [comment]
if you are looking for a mod to put it, maybe thaumic insurgence?

**Comment by Chaoschaot232** [comment]
🤔 also not a bad idea, fine then it goes there, hopefully the choosen spot within the thaumonomicon is free ... it's every time hard to get the x/y coordinates correctly 😅

**Comment by EnderProyects** [comment]
The mod could not just be normal added since the grate goes to a normal thaum tab? Also for the recipe just changing the void ingots with plates and adding some more vis to it could be okey, since players should use this to reduce lag it shouldn't be a hard recipe

**Comment by Alastors** [comment]
> if you are looking for a mod to put it, maybe thaumic insurgence?

I mean possibly? But honestly it would be better to just stay as it's own mod

**Comment by Alastors** [comment]
@Dream-Master cmon lad, let's get on it, this needs to happen, it'll help reduce lag

**Comment by EnderProyects** [comment]
> @Alastors feel free to suggest the mod or re link the suggestion. We can put this in the dev pack(for testing and discussion/vote) when the license is open and the recipe is gregified.

Could you make for now a rep with this mod? https://github.com/TechnicianLP/AlchemyGrate

**Comment by EnderProyects** [comment]
For the recipe I also propose this:
4 void metal plates, 2 thaumium screws, 1 hungry chest ( from original recipe), 1 of mixed crystal cluster, 1 open crate ( an upgrade of current setups that uses the open crate to place items)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/5f6c3ae4-2bbe-46b1-b41f-93417f4da060)
