### ISSUE TITLE
Add crafting status button to arcane terminal

### ISSUE THREAD

**Issue by ZenMasterSych** [GTNewHorizons/GT-New-Horizons-Modpack#13355]
### Your Pack Version

2.3.0

### Your Proposal

This suggestion has already been done, but it was closed by bot. The feature is steel needed. In the default AE2 terminal there is a hammer button in the top-right corner which shows current crfting status. I would like to have the same in an arcane one.

### Your Goal

it's useful and balanced

### Your Vision

useful and balanced

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by pavluchenko** [comment]
Need this function too

**Comment by miaowwwwww** [comment]
maybe add arcane terminal to wireless terminal too? Since this is the only terminal missing in the wireless terminal.

**Comment by ZenMasterSych** [comment]
> maybe add arcane terminal to wireless terminal too? Since this is the only terminal missing in the wireless terminal.

would be nice

**Comment by ZenMasterSych** [comment]
@Dream-Master thanks

**Comment by ZenMasterSych** [comment]
123
