### ISSUE TITLE
Bug with cell ae2fc

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/GT-New-Horizons-Modpack#13369]
### Your GTNH Discord Username

Pilad

### Your Pack Version

2.3.3

### Your Server

Single game

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Non-universal cell with water disappear when you click on the tank with the ae2fs mod.

### The Reality

If you empty a non-universal water cell into a tank with the ae2fs mod, the cell disappear. If the cell is with any other liquid, then the cell is returned.`

### Your Proposal

Fix this bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Pilad thry this version https://github.com/GTNewHorizons/AE2FluidCraft-Rework/releases/download/1.1.11-gtnh-pre/ae2fc-1.1.11-gtnh-pre.jar

**Comment by Pilad** [comment]
> @Pilad thry this version https://github.com/GTNewHorizons/AE2FluidCraft-Rework/releases/download/1.1.11-gtnh-pre/ae2fc-1.1.11-gtnh-pre.jar

Also. Does not work.

**Comment by Pilad** [comment]
Work!
