### ISSUE TITLE
AE2FC Fluid amounts change rapidly in a terminal

### ISSUE THREAD

**Issue by Fiyorin** [GTNewHorizons/GT-New-Horizons-Modpack#13387]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.3.3-nightly

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

several fluids in AE2 are changing their amounts rapidly

example video: chlorine that is in a tank attached via a fluid storage bus

https://user-images.githubusercontent.com/61357/235375329-9d5a4711-d7d1-4c04-8189-cd9cbf3d046d.mp4

(the amount in the tank is not changing that quickly)

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
My guess is somewhere you have something pulling lots of fluid, or have a fluid export bus with those super upgrades? its probably extracting the maximum it can, putting as much as it can into its target, then putting the rest of the fluid back. Should be fixed once https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/120 is merged

**Comment by Fiyorin** [comment]
yea a fluid export bus with those super upgrades. alright, thanks for the fix
