### ISSUE TITLE
Avaritia "World Breaker" recipe doesnt show when pressing R

### ISSUE THREAD

**Issue by Fiyorin** [GTNewHorizons/GT-New-Horizons-Modpack#13386]
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.3.3-nightly

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

the recipe of the world breaker doesn't show when you click on it in NEI

![image](https://user-images.githubusercontent.com/61357/235374843-36fd8fe7-8565-42f1-a789-2a95b9d0a8f5.png)

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
as in every version of the last few years it only shows if you go by uses not if you go by recipe. Actually suprised I couldnt find a ticket on it

**Comment by Fiyorin** [comment]
ah right, it shows up if you browse all the recipes of the dire crafting table.
what do you mean with the uses? it doesn't show for me that way (pressing U)

**Comment by chochem** [comment]
press U on draconic pickaxe for example

**Comment by chochem** [comment]
still an issue and comes up all the time
