### ISSUE TITLE
On Intel iGPU, Questbook contains various visual glitches and rendering issues.

### ISSUE THREAD

**Issue by StereotropicTube** [GTNewHorizons/GT-New-Horizons-Modpack#13388]
### Your GTNH Discord Username

🐰Bunny🐰#4778

### Your Pack Version

2.3.2-2.3.3

### Your Server

Sp

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Running minecraft with an Intel iGPU, using an older pre 2022 driver along with the Neodymium mod (version 0.1.8)  and optifine (version E7).
After a fresh new install of 2.3.2 , I loaded my save and I expected to open the questbook and find it in a readable state.

### The Reality

 Turns out it's full of rendering issues that hide completion marks, notification marks, questbook menu entries, text etc.
![image](https://user-images.githubusercontent.com/132231338/235376876-b37a4b50-92ce-4ce3-b9e1-3654df7a7e23.png)
![image](https://user-images.githubusercontent.com/132231338/235376887-e2438147-fa3a-4e1a-af28-ced2d53acb76.png)

This does not happen on 2.3.1. It only happens on 2.3.2 and 2.3.2 (both have been tested by me).

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
does it occur on java 8 pack version? intel gpu are known to cause visual glitches. Some persons get away with it by downgrading their driver version, some others got away with it by installing neodymium

**Comment by boubou19** [comment]
this kind of glitches can't be seen on other stuff than intel gpus. It is way beyond the scope of stuff we can fix. Since you kinda fixed it, i'm closing this ticket
