### ISSUE TITLE
Eye of Harmony - Potentially not restart safe

### ISSUE THREAD

**Issue by AtomicGrog** [GTNewHorizons/GT-New-Horizons-Modpack#13390]
### Your GTNH Discord Username

AtomicGrog#7956

### Your Pack Version

2.3.2

### Your Server

Private

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Running eye of harmony without issues.

### The Reality

Twice in the last 24 hours, after suspected server restarts (Server is restarted twice day and the production volume aligns to it not working after restarts) the controller details look broken and on scanning how stats that imply that the progress has exceeded the total expected time (See screenshots for both).

In this situation it never completes operation and requires a break/make again to resume. 

It's worth noting I've only been running the EOH for a couple of days and on the first day I was playing around with overclocking to find a reasonable balance between power consumption and production rate.

![Screen Shot 2023-05-01 at 9 10 19 am](https://user-images.githubusercontent.com/9132219/235380293-1237f292-61ae-4aa5-8105-fb649aa28347.png)

![Screen Shot 2023-05-01 at 9 10 27 am](https://user-images.githubusercontent.com/9132219/235380300-1ed946ea-e91b-49c2-90a5-0000b5c282fb.png)

![Screen Shot 2023-05-01 at 8 59 01 am](https://user-images.githubusercontent.com/9132219/235380125-7da6f03a-30fa-4d97-b7ee-02ec43515923.png)

Over the next day I'll see if it happens on further restarts and report here if it does.

### Your Proposal

Can you please fix the timer so it completes if the current value exceeds max i.e. likely on restart.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by joshaup1999** [comment]
We're on 2.3.2, not 2.3.3 grog :p

**Comment by AtomicGrog** [comment]
Edited, opps

**Comment by AtomicGrog** [comment]
Tested with a restart. The counter has basically run through the intended end point and continuing. The mini solar system has now dropped from view:

![Screen Shot 2023-05-01 at 12 14 58 pm](https://user-images.githubusercontent.com/9132219/235391962-96bd76ce-068e-4e5d-951b-0e4bebbfa274.png)

Will restart and see if it completes without restart. It was prior so expecting it too.

**Comment by AtomicGrog** [comment]
It managed a cycle with no hassle with no restart.

**Comment by AtomicGrog** [comment]
Sorry little more than theory as to the cause. From what I can see people avoid putting fluids into the hatches because it voids them then not running which is a documented feature.

However i wasnt necessarily avoiding putting fluids into the hatches whilst it was running. Since the issues I've changed my pre-crafting arrangements which seems to be common practice based on setups (screenshots etc.) i've seen of other people's EOH crafting setups.

The theory therfor being that having a fluid in the hatches whilst it's running over a reboot cycle somehow induces the issue.

I've since seen about 4 server reboots with fluids not being present in the hatches whilst EOH is running without issue.

**Comment by Fiyorin** [comment]
i haven't faced this issue. got 4 eoh running and i restart the server occasionally. 
fluid is left over in the input hatch while it's running.

**Comment by AtomicGrog** [comment]
Agree, subsequent tests have shown no issues with fluids in hatch. My only real hope right now is it doesnt reoccur which it hasnt now for a number of days.

**Comment by AtomicGrog** [comment]
Still happening from time to time, spotted this on latest:

![Screen Shot 2023-06-15 at 9 24 49 am](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9132219/ae3098e5-9fe4-4c07-bd49-17bcf05deaee)

(Tipler recipe requires 8B of each fluid)

**Comment by miaowwwwww** [comment]
still same problem on latest, 2.4.1. tested in zeta
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/da25b6c9-1b8a-48a3-a87c-07743bd68729)

**Comment by AtomicGrog** [comment]
> still same problem on latest, 2.4.1. tested in zeta ![image](https://user-images.githubusercontent.com/49871378/271805016-da25b6c9-1b8a-48a3-a87c-07743bd68729.png)

I presently have 26 EOH, of which 6-8 will fail like this on a restart.

My best guess is that the  the cause is having fluids in the input hatches whilst it's running and having a server restart but out of interest what chunloading approach do you have?

**Comment by miaowwwwww** [comment]
the world anchors on the floor, btw this is in official zeta server.

**Comment by AtomicGrog** [comment]
ok we are using a different chunkloader setup so it's not likely that
also fwiw i changed my fluid input setup to ensure hatches have nothing in them when it's running and it stil happened
![2023-10-02_07 24 44](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9132219/8fc172e4-9133-4a20-8f1e-efca3813cebb)
