### ISSUE TITLE
AE2FC allows fluids on normal drives

### ISSUE THREAD

**Issue by Logos-Askrson** [GTNewHorizons/GT-New-Horizons-Modpack#13396]
### Your GTNH Discord Username

Logos#2981

### Your Pack Version

2.3.0

### Your Server

Eta

### Java Version

Java 19

### Type of Server

Thermos

### Your Expectation

When pushing fluids into a dual interface, those fluids should end up in the AE2FC fluid cell with higher priority with the rest of that fluid.

### The Reality

The fluids enter and are stored not in the existing fluid cell with that fluid and space for more, nor in any of the priority 1 empty fluid cells, but instead in the bank of item storage cells with priority 0.

I'm not sure what precise conditions result in this happening, just that somehow my setup is doing it, and it has recurred after three rounds of manually emptying the cells into fluid storage via a ME IO Port. Not all fluid insertion into the network appears to be doing this, but it's consistent enough to be worth reporting.

Item storage cells with fluids and the setup itself are available for examination at my base on Eta, in case that helps with determining further relevant details.

### Your Proposal

Item storage cells should be incapable of holding fluids.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Logos-Askrson** [comment]
Version number had a typo; one too many .3s. Fixed.

Here's some screenshots of what look to be the relevant parts of the setup, being the storage arrays with the fluids and the sources for those fluids. It should all be fairly standard, so I'm unsure which specific parts are needed to reproduce this error.
![2023-05-02_19 41 16](https://user-images.githubusercontent.com/23437451/235814824-0a40577e-d31f-446f-864c-6a29a2a84225.png)
![2023-05-02_19 30 45](https://user-images.githubusercontent.com/23437451/235814830-4dbbf2b2-3122-437c-854f-2ec873d2d4fe.png)
![2023-05-02_19 30 52](https://user-images.githubusercontent.com/23437451/235814834-4293ab9a-62dc-45f6-aaca-437f1b2bca6e.png)
![2023-05-02_19 31 34](https://user-images.githubusercontent.com/23437451/235814836-e042f161-7aaf-433f-8355-177536a15ccf.png)
![2023-05-02_19 31 52](https://user-images.githubusercontent.com/23437451/235814841-a74ce012-48e5-4b0b-ae65-9152c1facb5c.png)

**Comment by firenoo** [comment]
Thanks for the pics. Some questions:
- when you mean fluid output, you mean outputhatch directly into a dual interface, right?
- can you confirm that cutting off the electrolyzer/sources of oxygen entirely from the network immediately stops filling the item cells (just to double check if its being caused by the source, or something else near the source)?
- can you show me what the items in the drives look like - are they the drops or actual fluid packets, or something else?
- are the cells ae2fc cells and not legacy extra cells cells?
- anything getting crafted?

**Comment by Logos-Askrson** [comment]
- when you mean fluid output, you mean outputhatch directly into a dual interface, right?
 Yes, except on the LCR, where fluid output is pulled by an ender fluid conduit into a dual interface.

 - can you confirm that cutting off the electrolyzer/sources of oxygen entirely from the network immediately stops filling the item cells (just to double check if its being caused by the source, or something else near the source)?
Those should be the only sources of oxygen, but it's possible some other machine was set up with oxygen output as an incidental output, and had the oxygen excluded from the patterns

Argon gas and palladium enriched ammonia have ended up in the item cells as well, though, and I'm quite certain those only have a single source in the system.

 - can you show me what the items in the drives look like - are they the drops or actual fluid packets, or something else?
Looks like this in an ME chest with one of the drives:
![image](https://user-images.githubusercontent.com/23437451/235827347-70aa31a2-96c8-4ce4-b9e8-2bdb8f10b8ed.png)
Drive is a 64K ME Storage Cell, and is full.

 - are the cells ae2fc cells and not legacy extra cells cells?
They are indeed ae2fc cells. I only started making ME fluid once those became available, as the EC cells were said to be quite bad for server performance.

 - anything getting crafted?
The system does appear to be able to pull from those cells for crafting.
As for whether the fluids in question are going through a crafting computer, most likely yes. Automation for those fluids is done via level maintainers using a crafting recipe, rather than just pushing water into the electrolyzer for a passive source.

**Comment by firenoo** [comment]
Do you have a discretizer for the system?

**Comment by Logos-Askrson** [comment]
Yes.
