### ISSUE TITLE
[EnderIO] Game freeze when looking to a Farming Station

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/GT-New-Horizons-Modpack#13407]
### Your GTNH Discord Username

DV#9777

### Your Pack Version

2.3.3

### Your Server

Private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Actions

When looking to a farming station from EnderIO, the game freeze : I am obliged to kill the process to close the game. 
Farming Stations are working great... just i can't access anymore ^^' (since when ? I don't know :( )

Crash reports are created in loop.

Tested with or without theses mods : 
- ArchaicFix 0.5
- OptiFine_1.7.10_HD_U_E7
- SmoothFont-1.7.10-1.15.3

Test with EnderIO 2.4.6 too => Issue still present.

Test in Java 8 => Issue still present.

I haven't this issue with other EnderIO machines like Capacitor Bank, Soul Binder, Slice'N'Splice...

### Crash Report

[crash-2023-05-01_20.48.53-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11367350/crash-2023-05-01_20.48.53-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
Can you post full fml log?

**Comment by DV666** [comment]
Hi! 

I have located the problem: I tested in a single player game and I can access a farming station... so my tree farm on my server has a problem! (because the farming stations are several versions old... almost 2 years I would say lol).

I broke one of the farming stations with a Block Breaker from ProjectRed : I got it the block but as soon as I put it back, the game freeze again.

I suspect that the inventory is the cause : indeed, these farming stations have a Mattock from Tinkers' (in unstable ingots) : if i am not mistaken, since a version, it is necessary to refresh the data of the tool... but I forgot to do it for those...

Currently, it is impossible to grab the stuff inside my farming stations... meh, I'll craft it again, np ^^'

If my explanations are not enough, I can provide you the fml logs on client + server side if you want.

**Comment by miozune** [comment]
Yeah your crash log actually does not contain useful info; It crashed while going back to title screen, presumably because server crashed and client was disconnected. So full logs are needed.

**Comment by DV666** [comment]
No problem! I will send you asap when I will be on the game :)

**Comment by DV666** [comment]
Hi !

Sorry for the waiting, i was busy. However, I can no longer reproduce this issue anymore because i reset my farming stations ^^' (break it with a block breaker because i can't look at them).
I couldn't wait unfortunately otherwise it was going to be a problem for my plants ahah.

I replace them with an Ichorium Axe => No issue since.
But i am 100% sure that the previous inventory which make this crash! (with an OLD unstable Mattock from Tinkers')

I found an old log when i get this issue, i don't know if if can help you :/
[2023-05-02-1.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11405759/2023-05-02-1.log)
On server side, nothing at all : the server just see me entering or leaving.

**Comment by DV666** [comment]
Hi !

Sorry to bother you again but my farming station bugs again when i backup my world : i can access on the GUI but it's buggy and i get a message on the chat "There was error during rendering item. Please check log for details."

Here my fml-client-latest-log, you can see the issue at [01:05:29]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11456873/fml-client-latest.log)

When i try to access on the farming station (normally, i have more stuff in my inventory but it's quite buggy here ^^')
![2023-05-12_01 07 52](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17729817/f7e5ba78-3d2b-4afe-aeab-3634302d81fa)
