### ISSUE TITLE
Type filter doesn't filter all logWood

### ISSUE THREAD

**Issue by stddo** [GTNewHorizons/GT-New-Horizons-Modpack#13405]
### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Type filter with filter set to log should filter oak logs.

### The Reality

Oak logs don't pass through filter (some logs pass some don't even though e.g. oak log is listed in switching items list in type filter)

### Your Proposal

Seems like logs with ids with slash (`XXXX/XX`) don't pass e.g. 
oak log doesn't pass - id `#0017/0` (17)
butternut wood from Extra Trees passes - id `#1356` (1356:2)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GabrielSerealia** [comment]
I'm also experiencing this as well on 2.3.7
