### ISSUE TITLE
Crash (Modular UI, FastCraft)

### ISSUE THREAD

**Issue by The1stRonin** [GTNewHorizons/GT-New-Horizons-Modpack#13417]
### Your GTNH Discord Username

#Stallion

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

Just moving around.

### Crash Report

https://paste.ubuntu.com/p/fv86vYXrZP/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
"Just moving around" is not enough for diagnosing the issue. What GUI were you trying to open?

**Comment by The1stRonin** [comment]
I wasn't opening anything. I uploaded the full crash report. I was
literally just moving.

**Comment by miozune** [comment]
That's weird... Crash log says player clicked slot in the GUI made by ModularUI and server tried to process the click... Maybe corrupted packet

**Comment by Sheodar** [comment]
Game was crashed when i just open machine module selection UI. 
[crash-2023-07-20_22.34.43-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12113556/crash-2023-07-20_22.34.43-server.txt)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/23509297/48b1a503-613e-4860-8734-dc0baaddfef6)

**Comment by chochem** [comment]
so this one? https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13683
that was fixed

**Comment by Sheodar** [comment]
Cool. Just didn't find it :sadge:

**Comment by miozune** [comment]
It's different crash
