### ISSUE TITLE
Forbidden magic caps uses normal recipes

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#13413]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

This should be the recipes for this two caps:
![image](https://user-images.githubusercontent.com/45178400/235740679-5b79f6c8-9eae-4fb1-9fac-a71b1b825527.png)
![image](https://user-images.githubusercontent.com/45178400/235740715-11edd6ca-0429-4522-9524-040ac634f20d.png)

### The Reality

But the normal recipes still are present:
![image](https://user-images.githubusercontent.com/45178400/235740887-737ad03f-ad6c-42e5-82d4-d31fa9ab9068.png)
![image](https://user-images.githubusercontent.com/45178400/235740847-639c907e-920d-4d09-9d93-12fa319594f3.png)

### Your Proposal

Solve the issue and remove the eassy recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@kuba6000

**Comment by EnderProyects** [comment]
Also, another thing, where are the recipes located, I need to use two of this caps in the AB and I´m doing something wrong :3

**Comment by chochem** [comment]
are you running a version with updated coremod and scripts? coremod is also where the recipes should be now.

**Comment by EnderProyects** [comment]
no no, I mean that I´m adding this caps to a AB recipe in code
