### ISSUE TITLE
Sealed Sticks Recipes in Chemical Bath missing Seed Oil

### ISSUE THREAD

**Issue by RoomofR** [GTNewHorizons/GT-New-Horizons-Modpack#13411]
### Your GTNH Discord Username

RoomofR#6656

### Your Pack Version

2.3.3 w/gregtech-5.09.42.83 & gtnhcore_2.0.38

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Recipe for Sealed Sticks should use seed oil.

### The Reality

Recipe for Sealed Sticks is missing seed oil. The recipe with seed oil is actually there, but you can still use the first 3 recipes to ignore that requirement.

![javaw_1Ep4ljdwP8](https://user-images.githubusercontent.com/24485410/235695212-3d2fcc56-95b3-4306-9e5b-6f8dbdda6ebf.png)

### Your Proposal

Recipe for Sealed Sticks should use seed oil.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you are just off. was fixed in 5.09.42.84
