### ISSUE TITLE
I can't start this modpack (Crash on Startup)

### ISSUE THREAD

**Issue by huna3245** [GTNewHorizons/GT-New-Horizons-Modpack#13418]
### Your GTNH Discord Username

huna2897/hiderain#0360

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Was launching the game (CurseForge --> Minecraft Launcher) GTNH was loading and at the end, when the loading bar stated 100% this game is crash.

### Crash Report

[2023-05-03-3.log.gz](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11378326/2023-05-03-3.log.gz)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
you have duplicate mods, that cant work.

So you did something wrong installing it, or curseforge did. reinstall it, best with a better launcher like multimc.

**Comment by huna3245** [comment]
I try multimc ,thank you so much.
