### ISSUE TITLE
Warptheory Doppelganger Spawner Crashes Server

### ISSUE THREAD

**Issue by TealSeer** [GTNewHorizons/GT-New-Horizons-Modpack#13414]
### Your Pack Version

2.3.0

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Actions

If you capture a warptheory doppelganger in a soul vial and then go and make a powered spawner with it, it will spawn generic steve doppelgangers. But if you try to hit them the client who hit them will crash (presumably some NPE trying to find the player linked to the doppelganger to damage them too). This was funny but then someone put the thing back in a soul vial and brought it somewhere else, then placed it and tried to hit it again, but this time he shot it with a tcon bolt (before we were hitting it with our hands), and it crashed the whole server.

### Crash Report

[crash-2023-05-02_16.58.03-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11377761/crash-2023-05-02_16.58.03-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@TealSeer can you report if it is working ?
