### ISSUE TITLE
There are issues with the overclocking mechanism of GT++in the current version GT++的超频机制在现版本存在问题

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#13425]
### Your GTNH Discord Username

JodieRuth#2410

### Your Pack Version

2.3.2

### Your Proposal

Rewrite an overclocking mechanism for GT++multi block machines
为GT++的多方块机器重新编写超频机制

Example: Industrial ore washing plant
举例：工业洗矿厂

If I use ZPM energy storage, its rated power is 122280EU/t
如果我使用ZPM能源仓，他的额定功率为122280EU/t
If I use a UV energy warehouse, he will only use the rated power of 131072 (ZPM) and will not continue to attempt overclocking or increase parallelism
如果我使用UV能源仓，他只会使用131072（ZPM）的额定功率而不会继续尝试超频或者增加并行
If I use two ZPM energy bins for overclocking, its rated power will reach a very dangerous 524288 (UV), which does not allow any cable loss to occur
如果我使用两个ZPM能源仓进行超频，此时他的功率会来到极其危险的524288（UV），这不容许哪怕一点线缆损耗的发生

Large processing plants also have related issues, specifically manifested as:
大型加工厂也有相关问题，具体表现为：
In the case of using fluid extraction mode, the UV energy warehouse can already provide 16 parallel 1-tick formula speeds
在使用流体提取模式的情况下，UV能源仓已经能提供16个并行的1tick配方速度
By using two UV energy silos for overclocking, he will directly increase the rated power to the UHV level, but there is no speed increase except for the 2 parallel increases in voltage level, wasting a lot of EU in vain
而使用两个UV能源仓进行超频，他会直接将额定功率提升到UHV级别，但是除了电压等级提升所增加的2并行以外没有任何速度的提升，白白浪费了许多EU

### Your Goal

GT++'s multi block machines now have many bugs, and we hope to fix them and increase the parallel computing system appropriately. In the later stage, the parallelism provided by most GT++machines is very limited and will cause a lot of lag
GT++的多方块机器现在有很多的bug，希望能修复他们的bug并且适当加强并行计算机制，在后期环境下大部分GT++的机器所提供的并行非常有限，并且会造成大量的卡顿

### Your Vision

Make GT++great again

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by BlueWeabo** [comment]
What recipes were you doing?

**Comment by chochem** [comment]
how are we supposed to follow this and check the maths with recipes?

**Comment by JodieRuth** [comment]
![$6KH``%N@7V{QJKWGQLM{`H](https://user-images.githubusercontent.com/132600151/236278301-b7dd5f6f-44e7-4537-acd2-d95cc45f9006.png)
![OI66IT`~ EHR$9`23JL83T4](https://user-images.githubusercontent.com/132600151/236278331-222f1b6d-814e-40f3-a015-31cebf39d96f.png)
![F8WW`~ 9 4NDLHV$U0R1A3L](https://user-images.githubusercontent.com/132600151/236280794-714cb4d2-b4b5-42e0-a478-505288c3e826.png)
![YG}M%)NP2GWM1D3YUFE~O43](https://user-images.githubusercontent.com/132600151/236280811-27cf044e-2b7a-4273-9502-33a7acb3b965.png)
Please check Waila. When the raw materials are sufficient, it will not undergo lossy overclocking, even though the input power has reached the required conditions for overclocking. In most cases, large processing plants using solidification or fluid extraction modes will consume more than three times the energy incorrectly

**Comment by BlueWeabo** [comment]
What were you processing? aka what did you input in the input bus

**Comment by JodieRuth** [comment]
![$6KH``%N@7V{QJKWGQLM{`H](https://user-images.githubusercontent.com/132600151/236282017-a2271c55-f9d9-4df7-b1f5-074a12e74ef8.png)
I missed this one.

**Comment by chochem** [comment]
that tells me nothing. Give us some maths please, like at least the recipe.

**Comment by JodieRuth** [comment]
I put the molten silicone rubber into the input bin and set the large processing plant to fluid curing mode. The input bus contains the ingot mold.
Industrial ore washing plants have a lot of salt ore and endless water, and I believe that the speed of input water from UV level electric pumps is higher than the speed consumed by the ore washing plant.

**Comment by JodieRuth** [comment]
At the same time, in 2.3.2, the GT++machine may no longer be able to start up after the server crashes, unless the machine is removed and placed in another location

**Comment by JodieRuth** [comment]
不只是我提到的这两个配方，GT++机器在处理很多低电压配方时都会使用错误的超频和错误的功率，使得浪费了三倍以上的能源。

**Comment by chochem** [comment]
I see. fluid solidifying is a very short recipe so you hitting one tick and therefore wasting extra OCs just using power for nothing.

Just activate batch mode and you should be fine.

**Comment by miaowwwwww** [comment]
![image](https://user-images.githubusercontent.com/49871378/236283611-25582509-36b0-4482-9494-ee99203efd76.png)
uv voltage，32 parallel consumes 16*32  512eu/t 5s(100t) then 2048 50t  then 8192 25t then 32,768 12t then 131072 6t , so the first screenshot has no problem.

**Comment by JodieRuth** [comment]
![WEIVT2UY(9LEP_(74NBS G9](https://user-images.githubusercontent.com/132600151/236284769-fddaa74d-8c02-4dc3-9368-1746a0dfb1e2.png)
![NR~ZRXR)YQNN2I_T8TX5 19](https://user-images.githubusercontent.com/132600151/236284773-08521ee5-d577-43e8-bc61-ca497ba68fd0.png)
This is using two ZPM energy bins for overclocking, and the power they can provide should be consistent with the UV energy bin. However, as shown in the figure, overclocking was successfully performed at this time

**Comment by chochem** [comment]
> for the rubber, even without the gtpp bonus, ![image](https://user-images.githubusercontent.com/49871378/236286402-be6e9919-87a2-4a86-8cdf-09060b4a3e28.png) uv voltage: 7*16=112eu/t 32t then 448 16t then 1792 8t 7,168 4t 28,672 2t 114,688 1t . i do agree that the energy consumption seems off.

what are the numbers? I see multiple LPFs and some unclear statements if its UV or UHV

**Comment by miaowwwwww** [comment]
in his pic, he was processing rubber bars with solidifier with uv voltage. so 16 parallel with the original recipe 7eu/t for 32t. after that i wrote some overclocking calculation(without the speed bonus from gtpp), but the result expected energy consumption is still lower than his actual consumption 367002.

**Comment by chochem** [comment]
so UV, got it.

7*16*0.8*4^6 = 367001.6, looks spot on.

**Comment by JodieRuth** [comment]
I think this may be rounding down. After I used batch processing mode, although I couldn't believe his numbers, the calculation results showed that this would waste a lot less energy than not using batch processing. But I think it is still unreasonable to waste energy solely due to algorithms, as upgrading machines is not as good as stacking low-level machines. Many machines in GT++only outperform small machines in some stages, as shown in the figure above, because the number of simultaneous processing in high voltage environments is too small compared to the increase in voltage levels. But there are still problems with the washing plant in my game, and I don't understand what caused it. Many people have mentioned that large processing plants or other GT++machines are too weak in high voltage environments, such as large processing plants in laser etching mode or industrial mixers, where the benefits of increasing voltage are too small. I think we can design an upgraded chip like an industrial shredder and use them to increase the revenue of GT++machines, rather than repeatedly stacking low-level machines

**Comment by chochem** [comment]
(after some discord talk) looks like blue wanted it to stop at 1 tick, just a bug after all.

**Comment by chochem** [comment]
ulv recipes not stopping at 1 tick is changed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/1951

You said there is a second thing?

**Comment by miaowwwwww** [comment]
![Screenshot_20230506-042602](https://user-images.githubusercontent.com/49871378/236621324-52a0a27b-b29e-440a-8bfa-8bf4840357df.png)
u mean this？

**Comment by chochem** [comment]
as I didnt get a reply I am gonna take that as a no. can always make a second ticket if there is 2 issues. but this one is fixed
