### ISSUE TITLE
[2.3.3 w/ GTU5 5.09.42.82] Basic sifting machine indirectly requires polyethylene

### ISSUE THREAD

**Issue by NeveHanter** [GTNewHorizons/GT-New-Horizons-Modpack#13448]
### Your GTNH Discord Username

NeveHanter#1925

### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

In 2.3.2 the item filter recipe that is required by basic sifting machine does not require polyethylene and can be crafted from 64 fine steel wire and 16 zinc foil.

![image](https://user-images.githubusercontent.com/3267401/236701154-f41a3e73-6361-41a7-bf3f-58b474a24ffb.png)

### The Reality

In 2.3.3 with GregTech updated to 5.09.42.82 (to even have most of the recipes) the item filter recipe (and thus basic sifting machine) additionally requires polyethylene.

![image](https://user-images.githubusercontent.com/3267401/236701298-242a168e-49ad-449e-8c3a-3d4229a1eb72.png)

### Your Proposal

Either it should not require the polyethylene or the quest book should be updated to reflect pushing the machine post polyethylene.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
the old recipe was the bug, not the new
