### ISSUE TITLE
Missing recipe for foil (and potentially other)

### ISSUE THREAD

**Issue by oliverpowerboy** [GTNewHorizons/GT-New-Horizons-Modpack#13441]
### Your GTNH Discord Username

oliver#2563

### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Wanted to craft copper foil in the bending machine from copper ingots

### The Reality

![image](https://user-images.githubusercontent.com/84041335/236680443-9664795d-c4dc-494c-a533-016363b834cf.png)

Can only craft foil in table from plates

Also only this recipe for oil in the distillery exists

![image](https://user-images.githubusercontent.com/84041335/236680529-a8096277-a912-4ebd-a758-3d5f2b4b4629.png)

### Your Proposal

re add the bending machine recipe 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
This has been fixed in dev. Try out [GT 5.09.42.89](https://github.com/GTNewHorizons/GT5-Unofficial/releases/download/5.09.42.89/gregtech-5.09.42.89.jar).
