### ISSUE TITLE
Iron capped wooden wand has broken extra infusion recipe in NEI

### ISSUE THREAD

**Issue by Cardinalstars** [GTNewHorizons/GT-New-Horizons-Modpack#13445]
### Your GTNH Discord Username

Cardinalstar16#3425

### Your Pack Version

2.3.4-nightly-April72023

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

The augment is messed up for some reason.

### The Reality

This is not visible.

Depicted Issues:
![image](https://user-images.githubusercontent.com/42074409/236697623-f84ab4b7-1e5b-4895-b64e-812e4f72d178.png)

### Your Proposal
Find and fix the bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
to be more precise: the recipe shows correctly, this additional broken one only shows when looking at all infusion recipes.
