### ISSUE TITLE
Stone Plate uncraftable

### ISSUE THREAD

**Issue by aheirman** [GTNewHorizons/GT-New-Horizons-Modpack#13442]
### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Other versions in between

### Type of Server

None

### Your Expectation

Being able to craft stone plate for the "Cooking Table"

### The Reality

I can not, there is no recipe for either the  gtnh or the gt version. 

### Your Proposal

add a recipy

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by aheirman** [comment]
Oh, and the java version in the template does not allow java 20 to be selected. This is on java 20 (arch linux openJDK)

**Comment by wlhlm** [comment]
This has been fixed in dev. Try out [GT 5.09.42.89](https://github.com/GTNewHorizons/GT5-Unofficial/releases/download/5.09.42.89/gregtech-5.09.42.89.jar).
