### ISSUE TITLE
DiscordSRV (?) Startup Deadlock

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#13446]
### Your GTNH Discord Username

TimeConqueror#5294

### Your Pack Version

2.3.3

### Your Server

Private one

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

Server to be started :)

### The Reality

VisualVM found a deadlock:
[deadlock.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11415805/deadlock.txt)
Link to pastebin: https://pastebin.com/dbVV5JU2

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
From my experience, it happens when somehow the plugin lose connection with discord API. I encountered this issue many times with 1.24 and 1.25. It seems to have stabilized with 1.26 for us so maybe try this version. Anyways, it's out of the scope of NH, so i'm closing this issue.
