### ISSUE TITLE
Better Questing: Crash while trying to open quest 'Filtering By Type' in Logistics Pipes Category

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#13456]
### Your GTNH Discord Username

TimeConqueror#5294

### Your Pack Version

2.3.3

### Your Server

private one

### Java Version

Java 20

### Type of Server

Thermos

### Your Actions

Opened quest Filtering By Type, got crash

### Crash Report

[crash-2023-05-08_22.55.48-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11424721/crash-2023-05-08_22.55.48-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
is that the one with the null item?

**Comment by chochem** [comment]
if so that is fixed in dev https://github.com/GTNewHorizons/LogisticsPipes/pull/20

**Comment by TimeConqueror** [comment]
Seems to be broken since https://github.com/GTNewHorizons/LogisticsPipes/compare/0.9.4.5.13-GTNH...1.0.0-GTNH

Modules shouldn't be unloaded if there's no mod provided, that's what I researched when making it. Because every module type registers its own id and it should never be replaced by another optional module.

@mitchej123

**Comment by chochem** [comment]
so fixed, yea

**Comment by chochem** [comment]
apparently the fix doesnt work
