### ISSUE TITLE
Allow the fluid terminal to let you empty/fill up entire stacks of cells in one left-click similar to GT blocks/machines

### ISSUE THREAD

**Issue by IsOobt** [GTNewHorizons/GT-New-Horizons-Modpack#13450]
### Your GTNH Discord Username

oobt#8431

### Your Pack Version

2.3.2

### Your Proposal

Make the Fluid Terminal function similarly to other GT blocks that hold fluids to let you fill/empty a stack of cells in one left click, or fill/empty one cell at a time with right click.

### Your Goal

It takes an eternity to fill/empty out cells via the fluid terminal

### Your Vision

Would make it easier to fill/empty out larger amounts of cells for people needing to fill/empty cells quickly for whatever purpose

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ydrec** [comment]
You can already do that by holding shift? Shift with stack of cells filles them all or however much possible,  shift click from inventory empties entire stack

**Comment by joshaup1999** [comment]
They probably didnt know, just close this ticket since its already a thing
