### ISSUE TITLE
Quest Book potential bug and nitpick

### ISSUE THREAD

**Issue by amHunter98** [GTNewHorizons/GT-New-Horizons-Modpack#13460]
### Your GTNH Discord Username

amHunter#6137

### Your Pack Version

Stable Version 2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Just Quest Book stuff

### The Reality

Second Separation quest (EV section) - Nitpick - Steam Cell (you need 4) wants specifically IndustrialCraft2 Steam, won't accept Gregtech Steam.

Sodium Nitrate quest (EV section) - Possible Bug - When I tried to do this quest, it wants specifically the BartWorks Sodium Nitrate, but I can't hold it since it is instantly converted to Gregtech Sodium Nitrate (basically it goes from purple SN to blue SN), rendering the quest uncompletable.

### Your Proposal

Make both items be detected using either item that it needs?

It is quite possible this may be already fixed on the new dev releases, but I did not see any issues reported regarding this.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
that is both IV ;)
the sodium nitrate one is already fixed, based on oredict now so that it accepts either. will just remove the steam from the other, its not important
