### ISSUE TITLE
[TC] Thaumonomicon Researches and Categories names are rendered unreadable and the contents of the researches become unavailable.

### ISSUE THREAD

**Issue by StereotropicTube** [GTNewHorizons/GT-New-Horizons-Modpack#13462]
### Your GTNH Discord Username

🐰Bunny🐰#4778

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

I expected to open my Thaumonomicon and be able to use it without issues.

### The Reality

Many of the Research Categories and Names are rendered unreadable and their contents are not displayed at all.
Example:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132231338/9753416e-aef9-4fbd-8d44-e8c9d40b1e78)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132231338/7e367795-412a-4a45-973c-21aa823d1a02)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132231338/2dd9be88-2057-4a38-be61-65d6497564f8)

How this problem occurs/can be reproduced:
- While the save file is loaded, by changing resource packs. In my case I'm using the realistic skies resource pack, changing back to default doesn't fix the issue and the issue persists.
- Exiting the "Select Resource Pack" menu by pressing "Done" while the save file is loaded
- It happens completely randomly after a while that the save file has been loaded, even if no resource packs are being used. Once the problem appears, it doesn't go back to normal on its own.

Temporary fixes:
- Reloading the entire pack
- Exiting the save and reloading it (however, it seems that by doing this the issue presents itself _sooner_ than when reloading the entire pack)

List of Categories in which this problem occurs:
- New Horizons
- Witchery
- Blood Magic

List of Research topics where this problem occurs (but for which it does not happen to the category as a whole, nor to other elements in the same category):
- Every "Electro-magic tools" topic except "The One Ring" and "Macerating Native Ore Clusters"
- Some topics in the "Apocrypha"
- "Warp warning" in "Basic Information"
- Other possible topics that I couldn't find

This issue presents itself Always and only to the previous research topics and categories.

Do Note, crafting recipes are still left Untouched:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132231338/10e5e3fd-0661-4722-9b48-4e0449869109)

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
Fixed in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/482
