### ISSUE TITLE
Disassembly machine does not work

### ISSUE THREAD

**Issue by fengluo2** [GTNewHorizons/GT-New-Horizons-Modpack#13464]
### Your Pack Version

2.3.2

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I am trying to use a dismantling machine to recycle the machine.

### The Reality

He doesn't work, I'm sure the recycled items are the right ones.  
I'm trying to use a scanner.  
It prompts:This Device needs more power.  
![QQ截图20230509233504](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/61233076/a72131ca-b19a-47a2-a886-cb9ee4c0a4aa)
![QQ截图20230509233021](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/61233076/e339bf8c-7f42-4528-a5c1-a2ad3879ae40)

### Your Proposal

Can we fix him

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by fengluo2** [comment]
Thank you for your answer

**Comment by Alastors** [comment]
> Thank you for your answer

We are deeply sorry for the inconvenience, but yes, the disassembler is not coming back. Though the arc furnace has been buffed in response.
