### ISSUE TITLE
Cannot set Input Separation mode for certain multiblocks, like the Industrial Material Press.

### ISSUE THREAD

**Issue by Affixatticus** [GTNewHorizons/GT-New-Horizons-Modpack#13477]
### Your GTNH Discord Username

DroidMiner67#4037

### Your Pack Version

2.3.3

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I tried to change the Input Separation mode of certain machines for which it worked in a previous version.
Among them there are:
+ Industrial Material Press
+ Industrial Extrusion Machine
+ Large Processing Factory
+ Precies Auto Assembler

I also tried right-clicking and shift-right-clicking with a screwdriver, but the affected multiblocks just changed mode instead of setting Input Separation, for all but the Extruder, which just does nothing.

### The Reality

I would've expected it to still be possible to have Input Separation inside of these machines, but it was not.

### Your Proposal

Make it possible to activate Input Separation mode for these machines through the GUI.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
prass has input separation by default so that should be fine. dont remember the others

**Comment by Affixatticus** [comment]
The IMP in bending mode made me Plates instead of dense plates and foils, so it at least is not working as it was before the update.

**Comment by chochem** [comment]
that might just be 2.3.3 recipe bugs probably

**Comment by chochem** [comment]
use https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.42.87 if you really want to play on 2.3.3

**Comment by Affixatticus** [comment]
I will try that, thank you

**Comment by Affixatticus** [comment]
I tried that and it worked! Looks like my version was just not up to date. Thank you for your help
