### ISSUE TITLE
Wand screw tierings are incorrect

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#13475]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.3.3 + nightly updates

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Wand screw should gradually go up in GT tier. Specifically the current balance comes from here <https://github.com/GTNewHorizons/GTNH-TC-Wands/pull/10>. (which was broadly speaking a buff by one tier for most wands outside of the issues described here)

### The Reality

After stainless steel the wand screws suddenly go down in tier to energetic alloy and continue chaotically afterwards. energetic alloy is MV not HV, vibrant alloy is HV not EV, enderium is EV not LuV. Osmiridium and oriharukon are IV not zpm/UV.

The tiers in <https://github.com/GTNewHorizons/GTNH-TC-Wands/pull/10> also dont match the current game. maybe the eio alloys were downtiered at some point.

### Your Proposal

Adjust the materials to materials that actually fit the intended tier as outlined in <https://github.com/GTNewHorizons/GTNH-TC-Wands/pull/10>. Except for the LuV+ ones of course, those should remain IV materials.

Specifically, here is my first draft:

'LV' = Aluminium (Ironwood Wand/Scepter/Staff)
'MV' = Stainless Steel (Greatwood)
'HV' = Vibrant Alloy (thaumic, transmutative, elemental) (instead of energetic alloy)
'EV' = Enderium (silverwood)  (instead of vibrant alloy)
'IV' actually late EV = Tungstensteel (Primal Staff)
'LuV' actually IV = Oriharukon (Warpwood) (instead of enderium)
'ZPM' actually IV = Melodic Alloy (Warpwood Staff) (instead of oriharukon)
'UV' actually late IV = Osmiridium (Ichorium)

Of course the quest would also need to be adjusted accordingly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
I think this isn't a great change, it's just pushing wands back further, when you can literally craft nearly everything with a great wood scepter and some elbow grease.

Wands shouldn't be treated like proper tiering, because they absolutely aren't, every wand aside from ichor should be in EV or less

**Comment by chochem** [comment]
every important is and still would be in EV or less. as you say the high tier ones arent really in use

**Comment by Alastors** [comment]
I mean, it's planned to change the tiering down a tier (in the lower two at least) anyway, to give thaumcraft more use earlygame

**Comment by Alastors** [comment]
Why'd we reopen this lmfao

**Comment by chochem** [comment]
I thought thats what you wanted...'comment to reopen'.

maybe propose your own tiers, as clearly they seem to be different.

**Comment by Alastors** [comment]
Nah, was a separate thought

**Comment by chochem** [comment]
well nothing has been fixed so far due to the lack of any reactions on my ticket. so everything is still a mess currently.

I dont know if there is support to push it forward by a tier a second time.
