### ISSUE TITLE
Change Chemical Reactor fluid capacity with tier

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#13472]
### Your GTNH Discord Username

Pxx500#6984

### Your Pack Version

2.3.0

### Your Proposal

Change chemical reactor fluid capacity with tier (16kL LV, 32kL MV, 64kL HV)

Also maybe electrolyzer should scale too (seems to have 64kL on all tiers)

### Your Goal

Make chemical reactor less annoying to use, it will also scale like other machines (cutting machine, arc furnace scale too)

### Your Vision

Will make chemical reactor much less annoying to use by hand when the thing you are doing doesn't require full automation. Also it makes sense that higher tiered machine has higher capacity

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by wlhlm** [comment]
Same thing with the Centrifuge, which currently has 64kL at every tier.

The Distillery scales with tier (8, 16, 24, 32, 40), but maybe that could be adjusted with the number listed above?

The Brewery has 6kL at every tier, the Fermenter 1kL.
