### ISSUE TITLE
Ore finder wand disappears

### ISSUE THREAD

**Issue by HistoryCucumber** [GTNewHorizons/GT-New-Horizons-Modpack#13480]
### Your GTNH Discord Username

HistoryCucumber#4269

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Go into ore finder wand inventory and accidentally shift click the wand into inventory but it can't go into the inventory because you  can't put something inside itself unless you break the laws of space and time (but this pack does that all the time I guess).

### The Reality

The wand can go into it's own inventory and when you exit it, the ore finder wand disappears into thin air.

also the bug only happens when you shift click the wand

also the wand can be retrieved if you get another wand and go into it's inventory

### Your Proposal

make the ore finder wand so that it can't go into itself so it doesn't get deleted from existence when you exit the inventory or just make it so that you cant move it at all while in it's inventory

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ydrec** [comment]
Suggestion: Make it spawn hungry node when you put wand inside itself 😊
