### ISSUE TITLE
gt++ heat exchanger description and possibly working value wrong

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#13481]
### Your GTNH Discord Username

tom#6482

### Your Pack Version

nightly from 11/5/23 23:36

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Exchanger to eat 25600 L/s of hot coolant (1280 L/t)

### The Reality

The description isn't clear and It feels as if it uses more
https://imgur.com/3iRMQan

### Your Proposal

fix description

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by tommmmmmmmm** [comment]
i changed the hot coolant pipe from large to huge and the pump to IV; the problem still persists (it would have shown better if i did the video with that setup instead)

**Comment by LazyFleshWasTaken** [comment]
I noticed the same issue, but with lava. It eats 64k/s and prodces 5,120,000 SH/s
