### ISSUE TITLE
Easier placement of small hitbox cables/tubes

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13483]
### Your Pack Version

2.2.8

### Your Proposal

Add the feature from nomifactory that allows easy placement of small wires by holding shift. It brings up the wire cutter hover box but still places like a normal block would. I want this feature or similar on all wire/cable/tube type blocks 

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13358034/6d09723e-1fbb-4dc9-8476-026badfd7a1c)

### Your Goal

Placing smaller cable sizes such as superconductor is really annoying and this solves that

### Your Vision

Helps with taking away a slight but very very constant annoyance in the pack

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Hiagg** [comment]
I forgot to mention but this only shows up while holding the correct block type

**Comment by LazyFleshWasTaken** [comment]
what happens if you hold a wirecutter or wrench in battlgear and wires in the other hand? Does it give full hitbox but still allow you to place it?

**Comment by Hiagg** [comment]
you cannot add wire cutters or wrenches to battlegear slots to begin with so who knows
