### ISSUE TITLE
Nightly 5/12/2023 - Uncraftable crafting table and unremoved vanilla mod recipes

### ISSUE THREAD

**Issue by PolkageistHS** [GTNewHorizons/GT-New-Horizons-Modpack#13492]
### Your GTNH Discord Username

Pao

### Your Pack Version

2.3.3 Nightly build from #beta-testing 5/12/2023

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Expectation

I'm trying to craft a vanilla crafting table at the very beginning of the game.  

### The Reality

There are no shaped or shapeless crafting recipes for the vanilla crafting table.  Natura crafting tables have both shaped and shapeless crafting but vanilla has neither.  You can only craft the vanilla one with an assembler or by extracting a compressed crafting table.  

![](https://cdn.discordapp.com/attachments/522098956491030558/1106757577989181500/image.png)
![](https://cdn.discordapp.com/attachments/522098956491030558/1106759643000213584/image.png)

### Your Proposal

Fix crafting table so my noob ass can do more quests.  Probably has something to do with removing the scripts.  

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
there are also recipes for modded fences and fencegates that should not exist:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/fe351662-9c6e-440a-bd72-417480082795)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/8ec322d6-32ec-4597-bfee-4eb6321edcfe)

(these are chestnut, so forestry and extra trees)

**Comment by PolkageistHS** [comment]
Same with the various Tinkers Construct tables: 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9247381/81c002e0-d5f4-49c6-9c67-24a1ad830946)

Ditto with paper: 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9247381/11b026dc-84b2-438f-a9b2-93e4dbda9012)

**Comment by PolkageistHS** [comment]
Natura wood gives 4 sticks without a saw instead of 2
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9247381/95a3309b-b59a-4ce0-8055-a621bf8daaa4)

**Comment by chochem** [comment]
modded slabs also have a recipe that shouldnt exist 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/2decbe14-516d-433e-9032-1fa9b3683a68)

**Comment by PolkageistHS** [comment]
Natura fences and doors
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9247381/d2c5944c-1acd-422b-9426-531a0b3291e5)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9247381/8016024b-17f1-46ce-b507-78d18372057d)

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/c93ab216-e16c-4959-9b9c-9af2764ae714)
natura bookshelves should be chisel or assembler only

**Comment by PolkageistHS** [comment]
Backpacks have the cheap vanilla recipe
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9247381/0cb4251a-842c-467b-8704-9a1406555d34)

**Comment by chochem** [comment]
also the workbench variant

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/f25321ec-d667-4902-a6df-12a63491ddcf)
world breaker also has vanilla mod recipe

**Comment by PolkageistHS** [comment]
Wool slabs without tools
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9247381/daa9280a-8411-43b8-8fc7-6c020955317d)
