### ISSUE TITLE
AE2 interfaces dump recipe contents into same network interfaces.

### ISSUE THREAD

**Issue by Ydrec** [GTNewHorizons/GT-New-Horizons-Modpack#13496]
### Your GTNH Discord Username

Ydrec#7877

### Your Pack Version

2.3.4 nigthly from 12.05.23

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

When ordered a craft interface wouldn't start pushing recipe contents to adjacent interface of its own network

### The Reality

Normal fullblock interfaces output recipe contents to adjacent fullblock interfaces of its own network. Does not happen when blocking mode is enabled. Does not happen with dual interfaces. Happens only when outputting interface has an inventory to output recipe to, but its already full. 

This behavior is expected with panel interfaces placed on another interface, as they don't connect channels and can only be placed like that on purpose. However fullblock interfaces often are placed near each other in machine rows. This bug appeared around 230 and wasn't there before.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/53411693/d37341f2-9508-4e38-992d-e0e10c82a552

### Your Proposal

Please fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
Interfaces should not output to its own network on a crafting push, ever.
