### ISSUE TITLE
Filing Cabinets Strange Storage Behavior

### ISSUE THREAD

**Issue by Jaguarkia** [GTNewHorizons/GT-New-Horizons-Modpack#13498]
### Your GTNH Discord Username

Jaguarkia#4278

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I put various stackable items into an empty Extra Utilities Filing Cabinet, having heard that worked for someone. I didn't expect it to work.

### The Reality

Not only did the items go in, it seemed to break the cabinet and allow almost any items to be put in without restriction of various types at the same time, even allowing 830+ cobblestone at the same time as ores and wheat. If I emptied it and put in, for example, IndustrialCraft 2 unknown seeds, it then didn't allow other item types again.

### Your Proposal

From what I've read in the quest log and online resources, I don't think the cabinet is working as intended.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
I can say that I have seen this as well, on 2.3.3, but not just any items can go together in my world. Related items could. For example, a lot of things related to enchanting ... like paper, books, books and quills, empty bottled, enchanted books ... can all go together. Then, only potions of all kinds can go alone, same for ic2 crop seeds. Also armor types by mod only it one, not mixed. So, I wonder if this is actually already in a config somewhere in the mod?

**Comment by Tyecon** [comment]
Can replicate on 2.4.0
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/19357318/525c49f3-5b7c-4c4b-99ea-a14bbfcc6498)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/19357318/9c845576-30ba-493b-92b4-7e1ea922821d)
It seems to lock the cabinet to some 'item category' but I can't find code or config for it anywhere.

**Comment by anthistat** [comment]
i have the same issue. pack version is 2.7.2. java 21
