### ISSUE TITLE
Blockrenderer shows PA wrong

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#13501]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.3.3 + nightly updates (12 May nightly)

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Expectation

the preview should be correct.

### The Reality

It is not correct, it says to use a muffler. (also to mix ulv energy hatches and ev laser hatches for some reason)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/49f04d20-2a7c-4bfd-a026-32edfe1ff436)

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Fiyorin** [comment]
the laser + regular energy hatch should be fine though? not recommended but it should work

**Comment by chochem** [comment]
probably yea
