### ISSUE TITLE
chunk borders (f9) disappear above y 126

### ISSUE THREAD

**Issue by HistoryCucumber** [GTNewHorizons/GT-New-Horizons-Modpack#13504]
### Your GTNH Discord Username

HistoryCucumber#4269

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

chunk borders keep working at all altitudes

### The Reality

the chunk borders disappear once you get to y 127

https://youtu.be/0NLFZiGs1AE

### Your Proposal

make chunk borders work at all altitudes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Can't replicate in 2.3.0+j17:

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1928113/933c2460-8371-4a4f-9094-526b0a555c9f

**Comment by HistoryCucumber** [comment]
turned out it was my shaders
