### ISSUE TITLE
Stone and reinforced glass plates (possibly other items) replaced by GTNH coremod variant

### ISSUE THREAD

**Issue by Miisi** [GTNewHorizons/GT-New-Horizons-Modpack#13506]
### Your GTNH Discord Username

Misi#3673

### Your Pack Version

2.3.3 nightly 

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

use my stone plates and reinforced glass plates

### The Reality

both of them got "deprecated", with the GTNH coremod variant being the useful one, but they didn't get automatically converted. putting them in my inventory does not convert them either

![imagen](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/46682682/79c0aba5-0973-4ff1-be85-8f04a43e1b24)

![imagen](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/46682682/0975b4cb-964e-4ba4-a8b6-f68ae7da242a)

as the GTNH coremod has a lot of variants for items already existing in GT, I can only assume this happened with other items

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
do you have a link to this deprecation you are talking about?

**Comment by Miisi** [comment]
I'm not too sure what you mean, I said "deprecated" as in they got replaced by the coremod variant, and the recipes using them updated to use the coremod variant, like in
![imagen](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/46682682/2be8938b-eaba-4b21-a5be-ad1260cefec0)

**Comment by chochem** [comment]
alright so nothing depreceted. I just checked and they just look removed. What you have there is just a kind of left over item.

Not sure when that happened but I guess have just one is actually much better.

**Comment by chochem** [comment]
hmm there might be some broken recipes though that didnt use oredict

**Comment by chochem** [comment]
yea, cant make:
- draconic evolution tablet
- PR circuit plate
- bc cobble pipe (stone rod)
- wand focus shield
- thaumic restorer

**Comment by chochem** [comment]
I did some testing and it looks like they used to get forced in by scripts which are now gone.

I guess the best way forward is just to fix the up the recipes and be happy we only have one item each.
