### ISSUE TITLE
Amunra causing rendering issiues

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#13511]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

2.3.4 (latest nightly from betatesting)

### Your Server

beta testing pack

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Well, if I play it would be fine to not have any rendering problems to any 3D Models or other things like TES and no, this time it's not OF's fault. Amunra seems to cause rendering problems here.

### The Reality

Like you can see here, the body part from DE's Chest is missing and from GC the Solar Panals aren't rendered which isn't realy nice.

![](https://cdn.discordapp.com/attachments/522098956491030558/1107774400268345345/image.png)

It is interesting, how only one mod can have such a high impact to effect other mods within the pack.

### Your Proposal

Referencing #13510 which was also caused by this mod, resulted by deactivating it in no rendering issiues any more, like you can see here:

![](https://cdn.discordapp.com/attachments/522098956491030558/1107784414311751761/image.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Chaoschaot232** [comment]
Rendering Problem fixed with the newer build provided in #13510 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1703441/e57a110a-480f-4802-b2f0-c6cdc72e8048)

Hell good that we can go to the main menu even after a crash report was thrown.

**Comment by Dream-Master** [comment]
i have render issues as well with Cupronickel cables. Will provide screens later.
