### ISSUE TITLE
Amunra causing BiomeID conflicts

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#13510]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

2.3.4 (latest nightly from betatesting)

### Your Server

beta testing pack

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Loading the pack without any conflicts, crashes and so on, to load at last you SP world or be able to play MP

### The Reality

The Game crashes right before you are be able to see the menu which cames from AntiIDConflict mod. A mod to determine IDs used twice which shouldn't be used twice and I have it in the pack since I play the stable 2.3.0 without any problems so far like you can see here:
[AllIDs.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11482033/AllIDs.txt)

But with the latest dev nigthly build from today, it was triggered as smth. re-registered vanilla biomes and BoP Biomes to have the same IDs:

[AllIDs (1).txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11482049/AllIDs.1.txt)
[conflictedIDs.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11482051/conflictedIDs.txt)

Disabling Amunrar like suggestest in discord from @BritishCynic has shown that Amunrar seems to be the culprit here as I was now be able to fully load the client without triggering AntiIDC

Crashreport: https://paste.ubuntu.com/p/wrB295rqbF/
As file: [crash-2023-05-15_23.26.41-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11482102/crash-2023-05-15_23.26.41-client.txt)
onflict.

### Your Proposal

Look at Amunrar why it's now causing this problem and try to fix it or at last remove it from the pack as long as this is not fixable or fixed soon.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
yea biome ids are not configurable in. We need to have a config for it.

**Comment by Chaoschaot232** [comment]
*Sigh* ... hardcoding IDs for Biomes and so on is a bad idea

**Comment by glowredman** [comment]
I'm pretty surprised by this because Amun-Ra doesn't even use any custom biomes. It uses desert everywhere.

**Comment by Dream-Master** [comment]
i dont see any biome from amunra in the biome list maybe it override existing ones ?
[biome.csv](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11485591/biome.csv)

**Comment by Chaoschaot232** [comment]
Could be smth. like this class: https://github.com/GTNewHorizons/amunra/blob/master/src/main/java/de/katzenpapst/amunra/world/AmunraWorldChunkManager.java

Here, he references the *Desert* Biome and I assume it's the vanilla one but I doubt that this is the main cause 🤔

**Comment by glowredman** [comment]
@Chaoschaot232 Please try this build: http://jenkins.usrv.eu:8080/job/Amunra/37/
