### ISSUE TITLE
solid color fill the screen

### ISSUE THREAD

**Issue by Sumo3432** [GTNewHorizons/GT-New-Horizons-Modpack#13512]
### Your GTNH Discord Username

Sumo3432

### Your Pack Version

2.3.0.zip

### Your Server

sp

### Java Version

Java 8

### Type of Server

None

### Your Actions

when i log into a world everything looks normal but if i move around the screen turns into solid colors and the colors change if i move the mouse. the screen will reappear if i look at the spot where it was originally 

### Crash Report

logs/fml-client-latest.log

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Sumo3432** [comment]
by the way im using forge to play the pack and ive tried uninstalling the pack then reinstalling it and it didnt work

**Comment by chochem** [comment]
intel gpu? that is a known driver issue

**Comment by Sumo3432** [comment]
i dont really know what that means but if i look at the hardware my computer has it say 12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz

**Comment by chochem** [comment]
that is the CPU but with a integrated GPU in case you dont have a separate one. 

here is the advice from our discord bot:

> If you experience weird rendering issues, it is possible that your game uses an intel graphic card to render. To know that, at the begining of your latest.log, there is a false crash report saying your graphic card. (it is also written in the crashlogs if you have any). Another way to know that is to look in the performance tab of the taskmanager on windows 10. If you have another AMD/NVIDIA card then switch to it for javaw.exe in your commutable graphic options. If you have only the intel graphic card, it has been reported that downgrading the intel graphic driver to around october 2021 works well.
> It has also been reported that adding Neodymium can fix this. Be sure to grab the +nomixin version. https://github.com/makamys/Neodymium/releases

**Comment by chochem** [comment]
and yea there is nothing we can do from our side (see the other tickets under the tag)

**Comment by Sumo3432** [comment]
okay thanks for the advice
