### ISSUE TITLE
The electromagnetic separator cannot handle new material-purified tengam dust

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#13518]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.2.3

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I tried to make purified tengam dust by using a UV electromagnetic separator, but after checking the recipe, I found that I need a UHV voltage electromagnetic separator to make purified tengam dust, but the highest voltage of the electromagnetic separator is only UV.

我试图使用UV的电磁离析器制作purified tengam dust，但是在我查阅配方后发现制作purified tengam dust需要UHV电压的电磁离析器，可是电磁离析器最高电压只有UV

### The Reality

There is no machine that can handle purified tengam dust, which makes it impossible for us to make any parts between UEV-UMV

没有任何机器可以处理purified tengam dust，这导致我们无法制作UEV-UMV之间的任何零件

### Your Proposal

Recipe for making a multi-cube version of the electromagnetic separator and adding the UV-UMV mini-machine to the electromagnetic separator

制作一台多方块版本的电磁离析机并且给电磁离析机加入UV-UMV小机器的配方

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
oh I figured out what you mean sorry. you mean electromagnetic separator, I thought polarizer from your description

**Comment by chochem** [comment]
@glowredman
