### ISSUE TITLE
chest upgrade assembler recipes only work with natura wood

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#13513]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.3.3 + nightly updates (15 May nightly)

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/cf96e58a-14cf-42ab-8344-5690a705293d)
used to be from zs scripts and worked (only) with vanilla wood.

### The Reality

Now in coremod, only natura wood works. Specifically this is about the wood to iron upgrade and the wood to copper upgrade.

### Your Proposal

Make it work with any wood. But at least with vanilla wood.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
Works for me, for all of the wood in the game on the newest nightly
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/53441451/75957250-13e9-452c-bcaf-8af8a0e11e6b)

**Comment by chochem** [comment]
huh. it must have been something I did. sorry about that.

yes can confirm its working in pure nightly. gotta check what I did there that broke it.
