### ISSUE TITLE
java.lang.IllegalStateException: Already tesselating!

### ISSUE THREAD

**Issue by OriginalBacer** [GTNewHorizons/GT-New-Horizons-Modpack#13526]
### Your GTNH Discord Username

OriginalBacer#2750

### Your Pack Version

2.3.3

### Your Server

private

### Java Version

Java 20 and Java 8

### Type of Server

Ultramine

### Your Actions

Client crashing every time when try to log in into the world. (2 friends have same issue and I don't have it at all)

On client there is no Optifine. Also try to disable Fastcraft same result.

### Crash Report

[crash-2023-05-18_20.38.13-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11510939/crash-2023-05-18_20.38.13-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by leagris** [comment]
> Java Version: 20.0.1

Java20 is not supported, max is Java19

**Comment by OriginalBacer** [comment]
Same problem on java 8

**Comment by leagris** [comment]
I was late, Java20 is supported for playing. Thank you for testing it further with java8.

**Comment by chochem** [comment]
do you have a full log?

**Comment by OriginalBacer** [comment]
> do you have a full log?

I asked my friends to send these logs. But they send them probably later today.

**Comment by OriginalBacer** [comment]
[2023-05-18-1.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11514988/2023-05-18-1.log)
[2023-05-18-2.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11514989/2023-05-18-2.log)

**Comment by miozune** [comment]
Turned out it's an issue with notenoughIDs and Ultramine, which are incompatible and unsupported.
