### ISSUE TITLE
Add error messages for the thaumatorium and infusion matrix

### ISSUE THREAD

**Issue by MarvinALiu** [GTNewHorizons/GT-New-Horizons-Modpack#13529]
### Your GTNH Discord Username

MarvinA#5089

### Your Pack Version

2.3.0

### Your Proposal

if a player doesn't have enough vis to form the thaumatorium or infusion matrix, it just doesn't form, but there should be error messages, like "insufficient vis to form" "not yet researched" "structure incomplete"

### Your Goal

in the current version it might be hard for newer players to know why their thaumatorium/infusion matrix isn't forming

### Your Vision

it will help newer players by showing an error message when failing to form the thaumatorium/infusion matrix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
I regret to inform you this, but this is an infeasible suggestion for base thaum
