### ISSUE TITLE
Backbone Cable causing Game Freezing

### ISSUE THREAD

**Issue by Taskeren** [GTNewHorizons/GT-New-Horizons-Modpack#13534]
### Your GTNH Discord Username

Taskeren#7774

### Your Pack Version

2.3.3 with GT upgraded to 5.09.42.87

### Your Server

private

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Description
Connecting cables using P2P like:
Controller - Dense Cable - P2P - P2P - Backbone Cable - Dense Cable - Devices
will freeze the whole server thread, and players are not able to login to the game.

No crashes, even no any logs.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17310943/8464f880-5ae8-4be8-aafa-a2a31087647c)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
please add your logs.

**Comment by Ydrec** [comment]
Had similar problem happen on Ultramine server. Removing cables fixed them. Something about not being able to properly calculate channels.

**Comment by Dream-Master** [comment]
you must try the new version of the pack. This was in issue in 2.3.0 but may fixed in 2.3.4 nightly

**Comment by Taskeren** [comment]
@chochem 
As I mentioned, there is no any log when the server freezed.
But as you wanted, here it is: <https://pastebin.ubuntu.com/p/bXxWntxksk/>
The freezing happend after I resume the game after the esc pause([17:57:33]). Then it just freezed, before I quit the game.

@Dream-Master 
The version is 2.3.3 with GT upgraded to 5.09.42.87. I missed it.

**Comment by boubou19** [comment]
backbone cables are known to have non trivial issues since their creation.

**Comment by chochem** [comment]
> @chochem As I mentioned, there is no any log when the server freezed. But as you wanted, here it is: https://pastebin.ubuntu.com/p/bXxWntxksk/ The freezing happend after I resume the game after the esc pause([17:57:33]). Then it just freezed, before I quit the game.
> 
> @Dream-Master The version is 2.3.3 with GT upgraded to 5.09.42.87. I missed it. I will try 2.3.4 when it become stable.

try the fml log. its almost always better. has way more info

**Comment by Taskeren** [comment]
> > @chochem As I mentioned, there is no any log when the server freezed. But as you wanted, here it is: https://pastebin.ubuntu.com/p/bXxWntxksk/ The freezing happend after I resume the game after the esc pause([17:57:33]). Then it just freezed, before I quit the game.
> > @Dream-Master The version is 2.3.3 with GT upgraded to 5.09.42.87. I missed it. I will try 2.3.4 when it become stable.
> 
> try the fml log. its almost always better. has way more info

Sadly, it has been replaced by the newer logs.
You can reproduce it in local env to get it. :)

**Comment by yukieiji** [comment]
I reproduced this bug in my environment(v2.3.0.0).
I just broke the BackBone cable that was working correctly in v2.2.0.0 and reinstalled it.

There was also a problem where adding a new component to a network that was using BackBone cables would not recognize all the subnetworks that were connected by SSDs.
so there must be some bug in the change from v2.2.0 to v2.3.0.0

**Comment by boubou19** [comment]
backbone cables are deprecated and will eventually be removed. You should start to remove them from your base.

**Comment by chochem** [comment]
backbone cables have been deprecated in dev. They will be removed in the future (probably in 2.5.0).

They were just causing way to many problems both themselves and for the rest of AE2 (even for players not using them).

Please switch to p2ps or wireless

**Comment by Taskeren** [comment]
Our server has already resolved this problem with disable the network feature lol.
But I'll leave this issue open until backbones are fixed or removed for those players to avoid the pitfalls
