### ISSUE TITLE
Add assembler recipe for Storage Drawer upgrade templates using LV Pistons 

### ISSUE THREAD

**Issue by HFPTetraUro** [GTNewHorizons/GT-New-Horizons-Modpack#13530]
### Your Pack Version

2.3.2

### Your Proposal

Currently you can craft an Upgrade Template in the assembler and using a Vanilla Piston and a Drawer.
Crafting storage upgrades for Barrels is similar, but there's also a variant using an LV piston which also gives an increased yield, my suggestion is adding a similar recipe for Upgrade Templates, I have no problem implementing this feature myself, I created this issue to see if this idea is welcome.

### Your Goal

Vanilla pistons become niche after reaching LV, and crafting them isn't really expensive, but requires specialized components which you most likely don't have on hand and will specially craft for this specific reason. On the other hand you most likely always have the components needed to make LV pistons, which is why I believe there is a similar recipe for JABBA's Storage Upgrades. 

### Your Vision

Making Drawer Upgrades would be more streamlined and less annoying, even though it's more expensive than using vanilla pistons (Depends on the yield on the recipe, which for barrels it's 3 for 1 LV piston vs 1 for 1 Vanilla Piston).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by wlhlm** [comment]
I'd be fine with that, especially considering the existing JABBA recipe.

**Comment by HFPTetraUro** [comment]
> I'd be fine with that, especially considering the existing JABBA recipe.

Do you think the ratio of 1:3 similar to JABBA is good? 

Also, correct me if I'm wrong but looks like this recipe is part of the Storage Drawers fork and not the core mod?

**Comment by TheEpicGamer274** [comment]
I've already added a recipe for this on my client, not finished with a bunch of assembler recipes conversions so this should be implemented when that happens.

**Comment by HFPTetraUro** [comment]
> I've already added a recipe for this on my client, not finished with a bunch of assembler recipes conversions so this should be implemented when that happens. 

Nice! Could you link the PR here when you create it?

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/643
