### ISSUE TITLE
Magic progression should not block Dyson 

### ISSUE THREAD

**Issue by harrynull** [GTNewHorizons/GT-New-Horizons-Modpack#13538]
### Your GTNH Discord Username

harrynull#9630

### Your Pack Version

2.3.3

### Your Proposal

Up until UIV, magic never blocks main progression. However to make Dyson, you would need extreme primordial pearl for magical memory.

### Your Goal

Magic shouldn't block main progression and stay optional in my opinion.

### Your Vision

It is more consistent and avoid a very steep and sudden need for magic progression in lategame for someone who opts not to do magic for the most parts.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TheEpicGamer274** [comment]
Well even still magic is required for a few things after dyson such as Deep dark which is pretty recommended, even still in this pack you should invest in getting magic done because you will want it for dragonblood

**Comment by harrynull** [comment]
Well yea I forgot dragonblood and deep dark. Yea I wonder if there was ever a design decision to make magic progression mandatory in the pack, or should we always provide alternative ways (even if potentially harder).

**Comment by TheEpicGamer274** [comment]
If you can provide ideas to go around the forced magic progression, and then I can or anyone else can discuss these ideas with the rest of the team.

**Comment by harrynull** [comment]
I am only early UIV or so, so I might not have the full picture. But here are some ideas from me:

1. Dyson / magical memeory

Magical memory has "magical" in its name so make sense to keep it gated by magic.

Each magical memory uses 24 memory (tier 3.5), 2 APU (tier 3), and some other cheaper stuff. So, to keep the cost roughly the same, I suggest changing the recipe of Dyson Swarm Ground Control Unit to use 16 APU (tier 3) and 128 memory (tier 3.5)

2. dragonblood

Dragonblood with mixer:
27.5e9 energy, 700 sec UHV, 128 awaken draconium, per 288L
95e6 energy, 2.4 sec UHV, 0.44 awaken draconium, per L
** consumes dragon egg **

with DE fusion and normal dragon egg:
8.3e9 energy, 210 sec UHV, 64 awaken draconium, per 288L
28.8e6 energy, 0.73 sec UHV, 0.22 awaken draconium, per L

with DE fusion and infinity dragon egg: 
7e9 energy, 210 sec UHV, 64 awaken draconium, per 432L
16.2e6 energy, 0.49 sec UHV, 0.14 awaken draconium, per L

Some ideas: consumed dragon egg in mixer recipe makes it not viable at all. Given it already is slower than alternatives, might as well just make it NC.

Alternatively, add DTPF recipe that use dragon egg and infinity dragon egg NC, and produces dragonblood. Could be less efficient than DE fusion in earlier coil tiers and more efficient in more endgame tiers.

3. deep dark portal
Simpliest would be to produces the portal directly rather than make the raw first. If that's too much of a buff, then maybe allow the space elevator with a certain tier to be able to teleport to deep dark (an extra button or something because it's not galaxyspace). Alternatively, make DD entirely optional.

Let me know if you have any suggestions / concerns, or if I missed anything else.

**Comment by chochem** [comment]
which part of DD is not optional?

dragonblood is certainly intended like this.

dont know much about dyson. but magic solars also need magic, so sounds fine.

it doesnt actually sounds like magic blocks progression.

**Comment by TheEpicGamer274** [comment]
it surely doesn't block progression yes, but any non laggy version way to get enough power is dyson lategame until EOH, and dd just unlocks a whole bunch of useful ores, but dd is surely optional, dyson I would say is not

**Comment by GDCloudstrike** [comment]
Dyson can be replaced by naq fuel, johny for example made almost 1 trillion eu/t with only naq fuel

**Comment by Pxx500** [comment]
I agree with this issue, dyson sphere is a "tech" multiblock, why does it even have magical components to begin with?
What's the idea behind it? It's odd imo

**Comment by Alastors** [comment]
Thaum is LV-EV, Im not quite sure how you are having issues doing what amounts to extremely basic amounts of thaum by the point you would be making the Dyson sphere anyway

**Comment by Alastors** [comment]
I'm just going to point this out and leave it there, most of our players already rush thaum in IV once the pure tear becomes available, so it's kind of miraculous that there are some that hate magic enough to get to the Dyson sphere without touching it, given how much QoL it gates

**Comment by harrynull** [comment]
> Thaum is LV-EV

It's not fair to compare thaum with tech progression because thaum has its own progression system that takes a lot of time. It just happens to use LV-EV tech materials.

> how you are having issues

I don't have any issues with thaum / magic, but different people have different preferences. I have been fine without doing magic for the most parts until UIV, and so I intend to keep it this way if possible.

> it's kind of miraculous that there are some that hate magic enough to get to the Dyson sphere without touching it

I mean it's just personal playstyle. Magic serves as a QoL thing, or make progression easier and it's perfectly fine as that role. I don't have insights with the pack philosophy but I guess it's debatable if it is a good design to suddenly gate progression based on magic. Again if this is a magic-focused pack and requires magic in every stage of progression then I would have no complaint at all.

> which part of DD is not optional?
> but dd is surely optional

*dark iron enters the chat*. but yea if it stays optional I guess that's fine.

Additionally I would argue that dyson plays a very important role in endgame progression, and just because it is theoretically possible to generate power without, doesn't necessarily abate its value.

I'd also point out like @Pxx500 said, dyson swarm is a very tech thingy and thematically does not make sense to be gated by magic.

**Comment by chochem** [comment]
magic is not mandatory in these cases but super helpful. In a way this is perfect for the official vision of magic in the pack.

dark iron is a different story and there is likely gonna be changes there, the use for it was just added in dev and it should be considered wip.

**Comment by Pxx500** [comment]
Maybe magic in dyson should have the same role as in solars?
Base dyson without magic, better dyson with magic (perhaps some kind of upgrade that uses magic just like solars can get compressed by magic)
