### ISSUE TITLE
Please move Naga Queen to before elven trade in progression.

### ISSUE THREAD

**Issue by Star-Tube** [GTNewHorizons/GT-New-Horizons-Modpack#13533]
### Your GTNH Discord Username

Star_Tube#1336

### Your Pack Version

2.3.0

### Your Proposal

Move Naga Bees somewhere pre-elven trade by removing Mystical Drone from their breeding tree (likely by removing eldritch bees since they probably should be gated but I am not sure since I haven't explored Bees very much)

### Your Goal

I want to get into thaumcraft without needing to kill because I am running a pacifist run and without the torture (even by most greger's standard) of following the [stone age thaumcraft](https://docs.google.com/document/d/1VF9HJPsaJasY_V_3OeJOX5RIRzGx5Xjfr-iBzzjfZGU/edit) line.

### Your Vision

Naga Bees being somewhere pre-elven trade would allow pacifist players to progress into thaumcraft without killing a naga or being forced through the hell of [stone age thaumcraft](https://docs.google.com/document/d/1VF9HJPsaJasY_V_3OeJOX5RIRzGx5Xjfr-iBzzjfZGU/edit).

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by OrderedSet86** [comment]
1. Naga bees are not available in elven trade - that NEI page is extremely misleading. It needs to only show up for dreaming->alfheim, not every bee.
2. There are multiple routes available to get mystical bee before IV (when elven trade becomes possible):
- Trading for the Curious Hive in the questbook
- Finding the Curious Hive in world
- Using the Botania Hiveacynth flower, which drops mystical drones and ignoble princesses (among other things)

**Comment by Star-Tube** [comment]
Mystical drone does not come from elven trade. NEI seems to be glitched and links to the elven trade recipe for alfheim drones when I click on mystical drone in the naga bee breeding tree page. It also appears that the eldritch princess can be bred out of an unusual, attuned or sorcerous princess instead of a mystic one. It seems like this means that it is currently possible to do what I wanted.
