### ISSUE TITLE
Thaumcraft Iron caps and Phial can not be craftd or search in Nei/jei

### ISSUE THREAD

**Issue by hydrocrry** [GTNewHorizons/GT-New-Horizons-Modpack#13549]
### Your GTNH Discord Username

Tam#2519

### Your Pack Version

2.3.3

### Your Server

Apex hosting

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

I tried to update my greatech jar from https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.42.87 from the subjection of the discord people and 

had no luck 
trying to craft iron caps and phial bottles when I try searching up there should a a recipe

I heard from the discord that it also effected electrum foil but mine was fine

### The Reality

When trying to craft iron caps the it doesn't work the gose for Phial glass bottle and when looking it up in nei only this shows up 

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76569253/98e43774-38b1-4f5b-8841-a27811a93e95)

iron caps don't eve show up at all and crafting them doesn't show up

the discord ask me to look up electrum foil to see if there was a crafting recipe and there was 

### Your Proposal

Im not sure what to do maybe I could try install 2.3.2 on apex hosting but I'm not sure how to do since the files don't have all the mods since they need to be install frist.

### Final Checklist

- [ ] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
iron cap too https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13410

that jar fixes GT recipes like your electrum foil (and every other foil), but not stuff that went wrong in the script transition.

**Comment by hydrocrry** [comment]
ok so i install the wrong gregtech jar I should try dev thank you

**Comment by hydrocrry** [comment]
Now when ever i try to put the gregtech dev file into the server the server crashes and doesn't work

**Comment by chochem** [comment]
no, thats not what I said/meant. you had the correct GT jar but that only fixes a certain part of the recipe bugs in 2.3.3. namely the ones in GT, like foils.

the caps and phials are not in GT. no gt jar can fix them.
