### ISSUE TITLE
Forestry multifarm circuits go missing

### ISSUE THREAD

**Issue by christianvdstap** [GTNewHorizons/GT-New-Horizons-Modpack#13551]
### Your GTNH Discord Username

Lalaru#1365

### Your Pack Version

2.3.0

### Your Server

Eta

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

I have 4 multifarms setup for IC2. This means there is an intricate forestry circuit with 4 uranium tubes. Once setup everything works fine, however, after some time I notice circuits going missing. Usually it happens in the south east farm, however, today (22 May) at around 18:00 I noticed ALL 4 farms had their circuit missing. This of course leads to sadness as the crops start dying, weeds start growing and the base power supply starts failing.

### The Reality

Forestry multifarm circuits go missing

### Your Proposal

Forestry multifarm circuits do not go missing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by The-Minecraft-Scientist** [comment]
I've had this issue occur twice on my private server (on 2.4.0, 2.5.0)
