### ISSUE TITLE
circuit plate missing recipe

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#13550]
### Your GTNH Discord Username

tom#6482

### Your Pack Version

nightly

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

make a t5 rocket

### The Reality

Ae2 stuck on making a circuit plate from projectRed core, recipe doesn't exist anymore in NEI.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8298646/c039aac7-233d-40aa-a42c-8d406311ef59)

### Your Proposal

Add a recipe for circuit plate...

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8298646/78517037-682d-4084-b4f0-12d5e37213cf)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/618
