### ISSUE TITLE
collection of blocks and items that need tool free assembler recipes

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13563]
### Your Pack Version

2.3.3+

### Your Server

self hosted

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

not have to do recipes with tools that can take a long time to calculate

### The Reality

there is a still many to be had. some that are even used frequently

### Your Proposal

- [ ] all decorative blocks from galaxyspace (used to create space stations, one time each)
- [x] diamond gear (used in ender quarry and the like)
- [ ] EV singleblock bending machine, though all tiers IV and below also have wrench (used to create industrial material press)
- [x] cell workbench (plz)
- [x] titanium and
- [x] bronze and
- [x] steel gear box casings (multiblock pieces)
- [x] extreme engine intake casing (multiblock part)
- [x] hastelloy-x structural block (multiblock part, also part of gt++ assembler controller recipe)

should be given tool free recipe variants

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hiagg** [comment]
every fluid related storage housing from ae2 is missing assembler recipe

**Comment by hallucinogender** [comment]
Regular engine intake casings are missing an assembler recipe at present.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/e895dc2c-8ab8-44be-abfc-0a43a22534a8)
