### ISSUE TITLE
Crash when breaking clay block with hammer Ticking memory connection  NullPointerException

### ISSUE THREAD

**Issue by uuuulopta** [GTNewHorizons/GT-New-Horizons-Modpack#13579]
### Your GTNH Discord Username

uuuu#9777

### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

VIdeo link: https://www.youtube.com/watch?v=8i_VJnr4xsA
Hammer : https://imgur.com/LoAXide 
Potential cause: Fastcraft
Get hammer and break clay.
This happens in all chunks.
I cannot enter the world again before restarting.
~I could break them before now suddenly I can't.~  I don't actually remember
I made a new iron hammer and it still happens with the new hammer.

### Crash Report

https://pastebin.com/JqGm0mp7

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment]
Just tried this in nightly release and did not get a crash. Why is your hammer acting like a Shovel anyway? It's made for breaking stone...

**Comment by uuuulopta** [comment]
> Just tried this in nightly release and did not get a crash. Why is your hammer acting like a Shovel anyway? It's made for breaking stone...

I was getting some ore dust when I needed clay for something, so my brain went dust = hammer. 
Tested it in a new world still crashes.
I use [java17-20 23-april multimc release](http://downloads.gtnewhorizons.com/Multi_mc_downloads/)

**Comment by wlhlm** [comment]
What I meant is, you shouldn't be able to break clay with a hammer since it's meant to be harvested by a shovel.

Here is what happens when I try to harvest the Clay block with the Iron GT hammer in 2.3.3:

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1928113/b7c569cb-1cae-4186-a9a5-ec210c8672fc

Can you try using this version of GT: https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.42.89

This is mostly meant for recipe fixes, but maybe it helps.

**Comment by uuuulopta** [comment]
Yep, that was it.
My previous version was: gregtech-5.09.42.71
The issue was solved with switching it with the above version.

Thanks for your assistance!
