### ISSUE TITLE
Add assembler recipes for more ae2 components

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13570]
### Your Pack Version

2.3.3+

### Your Proposal

Add GT assembler recipes for the following components
crafting unit
me controller
me quantum ring
me quantum link chamber
me spatial pylon
me chest
me drive
formation core
annihilation core
me interface
me interface but flat
me dual interface
me dual interface but flat
energy cell
dense energy cell
all upgrade cards
wireless receiver
wireless connector

i hope i didnt miss any

### Your Goal

a lot of other important ae2 components got assembler recipes so it adds more consistency to the experience

### Your Vision

even further reduction of molecular assembler usage and more in line with the rest of the pack

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Yea AE2 recipes need a rework for sure
