### ISSUE TITLE
Make the Multiblock Machines halt their progress when out of power intead of voiding and turning off

### ISSUE THREAD

**Issue by Srdra2k3** [GTNewHorizons/GT-New-Horizons-Modpack#13577]
### Your GTNH Discord Username

Srdra#7777

### Your Pack Version

2.3.2

### Your Proposal

Although the multis running out of power and voiding is feature to punish players for poor power management, it starts to just turn into an hassle for early-midgame+ (post central power) players that want to upgrade their powerline or their energy hatches.

That's why I would like to propose that the multis should only halt their progress like in GT:CE and not turn off.

### Your Goal

This would spare the players the hassle of turning each machine on, or editing each machine controller whenever they would like to upgrade their powerline

### Your Vision

Less unneeded tedium

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by desagas** [comment]
From a pack seemingly designed to challenge and focus on every single micro detail, I would say that something like Nomni or Interactions would be better packs to play if you want this functionality. I like this feature, as it requires me to really manage my resources and generation. Just my opinion. When I am punished for not doing what I needed to do in order to get what I needed, it teaches me to do it differently in the future.

**Comment by Srdra2k3** [comment]
Once again I am not bothered at all by the voiding of materials. What bothers me the most is having to turn on every single machine once I want to upgrade my central powerline. But I can see why this change would be a very longshot.

Upgrading your powerline should not punish you IMO.

I've also finished both Nomifactory CE/CEU and Interactions.

**Comment by desagas** [comment]
If you create centralized power banks, and banks outside closer to your machines, this would 100% eliminate the need for this change. Batteries and their banks are not too expensive, especially not if you have enough machines where turning them all off and on again is a hassle when upgrading the powerlines.

**Comment by fluffle** [comment]
Also, you can design a redundant power network with multiple battery banks between producers and consumers, with hot/cold failover. When it comes to upgrade tiers, you swap out one buffer with the higher tier one (or hatches on one of two LSCs), and you power the old network with step-down transformers from the new buffer while you switch everything over. You don't *need* to turn everything off, you just haven't thought about how to build a system where this isn't necessary.

**Comment by Ismaster84** [comment]
For me this would be a welcome change. When you are in early mid game this is not an hassle at all but when you have hundreds of machines this is just and hassle. I think in my opinion people that give opinion should say what point of the game they are because people that are on hv and have a ebf and a cleanroom, for them this is not an hassle but late game players its a completly different story. Regards and sorry for the crappy english.

**Comment by chochem** [comment]
we have no interest in doing in this. as you can tell from singleblocks, this is all intentional. this has no relation to tedium whatsoever, this is about you thinking about how you set up your power and providing enough. Infrastructure challenges are interesting.

**Comment by Ismaster84** [comment]
> Since you appear to be asking for me to flex, I'm in UHV, almost UEV (taking the time to set up fusion plasmas and large-scale EBF smelting properly before mutated living solder) and have both built centralized and decentralized power networks for different parts of my base(s) :-)
> 
> Rewiring a base from one power tier to the next is probably one of the more stressful parts of GTNH, but broadly speaking you do that once every hundred hours of playtime or so past EV -- probably longer for higher tiers like UV+. But you don't _have_ to run everything at the highest power tier. I built my first backbone power network based on a 16A IV battery buffer and an IV hi-amp transformer to run LuV power to multiple chunks. Before that I powered individual groups of machines of a particular tier with localized generation, and much of the HV / EV stuff continued to be powered like that well into ZPM. My nitrobenzene plant _still_ powers itself, even though that is mostly laziness on my part ;-)
> 
> And as I said earlier, IMO you can already solve this problem with the tools the pack gives you. Having one massive network that reduces to `generators -> buffer -> machines` is simple but has drawbacks. It's entirely possible to build power networks that have enough redundancy that you can replace parts of them while other parts continue to power your machines. If you dislike the drawbacks you can engineer something better!

You are not flexing mate you are at the exact same spot as me in the game i just crafted my first uev circuit. And i moved my lsc yesterday and had to power 100 and somethings machines on and it was tedious. Im doing lasers now and its gona be a pain to power everything on again...

I did the same iv 64a to luv and im up to 256a uv now.
