### ISSUE TITLE
Advanced Dislocator 

### ISSUE THREAD

**Issue by King65868** [GTNewHorizons/GT-New-Horizons-Modpack#13573]
### Your GTNH Discord Username

King#4098

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Tried to use the advanced dislocator and expected to be able to close the GUI. 

### The Reality

The GUI did not close no matter what I did. 

### Your Proposal

Let the GUI be close-able.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
dont think we have anything called a _Advanced Dislocator_

**Comment by King65868** [comment]
> dont think we have anything called a _Advanced Dislocator_

Sorry, the Enhanced Charm of Dislocation.

**Comment by chochem** [comment]
ah, so every word different :D

hmm. esc works just fine for me.

**Comment by King65868** [comment]
That’s very strange, since it definitely doesn’t not work for me.

**Comment by King65868** [comment]
Seems it is already fixed in dev, after testing.
