### ISSUE TITLE
Recipe conflict in the Brewing machine

### ISSUE THREAD

**Issue by NepToasty** [GTNewHorizons/GT-New-Horizons-Modpack#13576]
### Your GTNH Discord Username

NepToast#1337

### Your Pack Version

2.3.3

### Your Server

Private Server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Get Lubricant as the result product from the Brewing machine, when using Oil and Redstone in it, just like in NEI.
A clip:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/103216308/d894772c-64fd-4569-853d-49fe6aff3dab

### The Reality

I get Mundane Brew 

### Your Proposal

Get as a result the output that is in NEI.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
update gt as recommended and try again please.

https://gtnh.miraheze.org/wiki/Dev_Release_Stability
https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.42.87

**Comment by chochem** [comment]
well I am going to claim it is fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1932
