### ISSUE TITLE
Crash at launch due to missing LWJGL 3 libs

### ISSUE THREAD

**Issue by Zenthae** [GTNewHorizons/GT-New-Horizons-Modpack#13588]
### Your GTNH Discord Username

🤯Zenthae🤯#9873

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

- Creating a new GTNH instance
- Starting it

Tested with Java 17.0.7 and 19.0.2.7
Tested with and without the java args from https://github.com/GTNewHorizons/lwjgl3ify#client

I tested with a newer version of the pack (2.3.3) and it's working, but I don't want to use this version since it's not a stable release

### Crash Report

https://mclo.gs/WiYZT5m

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment]
You are missing LWJGL libraries:
```
 C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.2-SNAPSHOT-10/lwjgl-glfw-natives-windows-x86-3.3.2-SNAPSHOT-10.jar (missing)
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.2-SNAPSHOT-10/lwjgl-glfw-natives-windows-3.3.2-SNAPSHOT-10.jar (missing)
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.3.2-SNAPSHOT-10/lwjgl-glfw-3.3.2-SNAPSHOT-10.jar (missing)
  C:/Users/********/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.2-SNAPSHOT-10/lwjgl-jemalloc-natives-windows-x86-3.3.2-SNAPSHOT-10.jar (missing)
...
```
Unfortunately, 2.3.0 for new java relies on a snapshot version of LWJGL 3 that is no longer available. We are working on an updated zip of 2.3.0 that fixes this. Should probably be released within 24 hours. You can use the Java8 release of 2.3.0 as a workaround for now.

**Comment by wlhlm** [comment]
Update has been release: http://downloads.gtnewhorizons.com/Multi_mc_downloads/GT_New_Horizons_2.3.0__Java_17-19_fixed.zip
