### ISSUE TITLE
Vending a fluid on Dual Interfaces doesn't disable full-network sharing like a normal ME Interface

### ISSUE THREAD

**Issue by Shadowsoftime99** [GTNewHorizons/GT-New-Horizons-Modpack#13585]
### Your GTNH Discord Username

Shadows#4865

### Your Pack Version

2.3.0

### Your Server

Private

### Java Version

Java 19

### Type of Server

None

### Your Expectation

When working with subnet logistics, I've set up a passthrough for specific items into a platline subnet. Stocking any item in there to offer to the subnet, makes it so that the subnet can only see those items instead of everything in the main net. That's fine, that's useful.

I expected the Dual Interface to give the same functionality for fluids: I don't want the subnet to "see" the UUMatter in my main net, for example.

Here's the joint in question:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16748195/3bd6a154-cde7-42b6-9529-1a939d87d956)

Fluix cable is main net, yellow is subnet. That's a Dual Interface on the left and a ME Fluid Storage Bus on the right.

### The Reality

Stocking a fluid into the Dual Interface looks fine, but in effect it does nothing. The subnet can still see and access ALL of the fluids from my main net.

Interface stocking only oxygen:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16748195/38a262ae-517a-48c0-8076-e58a33628a66)

Terminal on the subnet showing all the fluids (plenty of these do not exist in the subnet at all and thus should not be visible right now):
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16748195/c2e90d90-9c53-4cc2-aad5-5769110be97d)

Also, stocking a solid item in the Dual Interface DOES disable all network sharing. But then here's no way to let any fluids through at all.

### Your Proposal

Make the functionality match! 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
> Stocking a fluid into the Dual Interface looks fine, but in effect it does nothing. The subnet can still see and access ALL of the fluids from my main net.

This is intended behavior. In fact, the dual interface stores no real fluid inside itself.

> Also, stocking a solid item in the Dual Interface DOES disable all network sharing. But then here's no way to let any fluids through at all.

Not sure what you mean here. Unlike the fluids, the items stocked in a dual interface are real in that the dual interface has real item slots.

**Comment by Shadowsoftime99** [comment]
> the dual interface stores no real fluid inside itself.
This is something I've seen to be false. I have 64kL Ammonia storage, ask the Interface to stock Ammonia, and can watch as my storage is dropped to 48k in the tank and 16 in the interface (my LCR then refills the tank with another 16k, so I have 80 total in system)

If this is intended behavior then yeah I guess I could call it a suggestion instead, because it's inconsistent and leaves the user without the way to "hide" the main net fluids from a subnet, while the practice works perfectly fine with items.

**Comment by Ydrec** [comment]
a few minute facts
- Fluid storage bus can be placed on normal interface as well and see fluids if networks are linked.
- Both normal and dual interface would stop network linking if there is any item set in the stocking slot, that also includes fluids being visible in the subnet.
- Dual interface doesn't store fluids in its buffer when accepting them, instead directly trying to move them to available storage in network 
- It does store fluid in buffer when stocking, at least from player's perspective
