### ISSUE TITLE
When doing a craft involving fluid, having 2 or more patterns in one interface makes ae2 only input the minimum pattern size repeatedly cycling between the fluids

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13586]
### Your Pack Version

2.3.3+

### Your Server

self hosted

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

That ae2 will fill the input hatch or do bulk crafting

### The Reality

Only the minimum amount of fluid is ever sent out as long as there is 2 or more patterns called at once into an output hatch. causing the crafting speed to go from a mere few minutes to literal real life months with how slow it inputs. i reduced the pattern size to showcase the issue better

ae2fc-1.1.19-gtnh.jar is my version

https://youtu.be/hTqUu_pc1lo

### Your Proposal

plz fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hiagg** [comment]
was checking other bottlenecks in my craft and the same was happening for biocells + stemcells being done out of the same interface. after removing one pattern it instantly fills the entire bus

**Comment by firenoo** [comment]
Not a bug, looks like ae2 is trying to parallelize the craft but since the two patterns are on the same interface they switch between the two

**Comment by greesyB** [comment]
This feels like a bug to me since normal interfaces are smart enough to avoid this issue with items

**Comment by firenoo** [comment]
If you think so, but the behavior currently is "correct" in that the craft will finish.

I don't really care about how its categorized but feel free to look into it, i just put it as suggestion since it would obviously be an improvement but currently nothing is "broken" in the normal sense

**Comment by cainiaojun** [comment]
I think it should be instantly changed whether it is a bug or not. 
This behavior absolutely affects players. Even trying to craft 64 items needs a lot of time, which annoys me. In my opinion, AE should try to produce one single recipe at the highest possible amount, and then moves to the next.

**Comment by firenoo** [comment]
@eigenraven probably knows more about this
