### ISSUE TITLE
Sodium sulfate dust recipe in platline doesn't follow chem rebalance

### ISSUE THREAD

**Issue by OrderedSet86** [GTNewHorizons/GT-New-Horizons-Modpack#13589]
### Your GTNH Discord Username

Order#0001

### Your Pack Version

2.3.0

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

The formic acid precursor to palladium line should make sense.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/88752681/d98cb178-67fe-4aa3-8552-a7f7cb5c87ad)
2 (HCOONa) + 1 (H2SO4) -> 7 (Na2SO4) + 2 (CH2O2)
4H + 2C + 6O + 2Na + S ->  4H + 2C + 32O + 14Na + 7S
6O + 2Na + S -> 32O + 14Na + 7S ??

### Your Proposal

Adjust formic acid line to make sense with chem rebalance norms

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by OrderedSet86** [comment]
The total excess is 2 H + 4 (CH2O2) = 10H + 4C + 8O != the input 2 (H2O) + 2 (CO) = 2H + 6O + 2C

**Comment by DotJason** [comment]
I believe the chem balance is correct on this one, as dust formulas use a different principle, 7 Sodium Sulfate Dusts are equal to Na2SO4, _not_ 7(Na2SO4):
2 (HCOONa) + 1 (H2SO4) -> Na2SO4 + 2 (CH2O2)
4H + 2C + 6O + 2Na + S -> 4H + 2C + 6O + 2Na + S

Seems right

**Comment by chochem** [comment]
for reference: https://wiki.gtnewhorizons.com/wiki/Chemical_Balance
