### ISSUE TITLE
New Versions Bug Out EBF Energy Hatches

### ISSUE THREAD

**Issue by BuffaloBob1** [GTNewHorizons/GT-New-Horizons-Modpack#13584]
### Your GTNH Discord Username

Buffalo_Bob1#1405

### Your Pack Version

2.3.3 Java 17-20

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Provide constant power to an EBF and/or Volcanus

### The Reality

After updating to a new version of GTNH, from 2.2.8 to 2.3 and 2.3.3 (happened on both versions), energy input hatches no longer seem to work for more than a few seconds. They provide consistent power to the multiblock for maybe 10-15 seconds before shutting off and no longer accepting more power. I can power cycle the machine with a mallet, but it turns off after a split second, as if it has no power or flickering power.

I've completely make a new power system and even set up just test setups in a creative world, and EBFs can't seem to work for me in 2.3+. I've also tried in both Java 8 versions and Java 19.

Other multiblock machines on the same network function fine. Multi-smelters, LCRs, all fine.

### Your Proposal

The source of this bug can hopefully be found and the energy hatches for my EBF's/Volcanus' can work so that I can finally work in the newer versions of Java instead of my usual 2.2.8 Java 8 world.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BuffaloBob1** [comment]
Any recipe, but the most recent test was just with 16 stacks of Aluminum
circuit 1. EBF in the past was LUV, but it currently setup with ZPM, both
failed. Cable loss is zero, as I almost exclusively use superconductor
cables.
In that most recent test, it made it through a full stack & 1/4 of the next
before problem made itself aware.

**Comment by chochem** [comment]
the EBF most certainly works in 2.3.0

**Comment by BuffaloBob1** [comment]
I understand that it works for most people, that's why I'm confused as to
why I'm running into it.
I am unsure why, even with the exact same setup, or with a brand new test
setup, it would work for a few seconds before stopping and never restarting.

**Comment by chochem** [comment]
just double check everything. we had one player recently with super weird EBF problems recently and it turned out they had died and that put a grave directly ontop the muffler :D
yes just check everything and then check it again and try it slightly different.

**Comment by BuffaloBob1** [comment]
I've double and triple checked everything. This is an issue I've had
ongoing for months, with me trying every time there's an updated version of
the pack.
I've literally changed nothing from an already existing and working system,
but after the update my EBF's only work for 10-ish seconds. It seems like
whatever energy is stored in the energy hatch is all it uses, and then no
more is sent.
I just don't know why it's only EBF's and Volcanus's that are encountering
this issue. Slapping a quick LCR down on the same setup, and it works fine
forever.
