### ISSUE TITLE
Vanilla handcrafting/assembler recipes missing

### ISSUE THREAD

**Issue by KhonaB** [GTNewHorizons/GT-New-Horizons-Modpack#13583]
### Your GTNH Discord Username

Khona Betwanhe#7122

### Your Pack Version

Nightly 2023-05-29

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Tried to craft some ladders, looked up the recipe in NEI

### The Reality

Ladders have no recipe. Neither do some other vanilla hand-craft recipes (and their assembler counterparts?) like torches, although torches still seem to have some (maybe not all) assembler recipes.

### Your Proposal

Fix whatever recipe script got borked.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
> Fix whatever recipe script got borked.
which ones? just ladder?

**Comment by chochem** [comment]
confirmed to be a problem with the automatic nightly builds.

**Comment by chochem** [comment]
should be fixed with nightly build 7 (manual one on 31 May) or higher
