### ISSUE TITLE
"Can be a Substitution" doesn't work as expected

### ISSUE THREAD

**Issue by lostkira** [GTNewHorizons/GT-New-Horizons-Modpack#13598]
### Your GTNH Discord Username

EzrealC#0074

### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Crafting a Robot Arm (MV) with "Using Subsitution: Yes" in pattern, it can use any MV circuit which can be crafted

### The Reality

I used "Any MV Circuit" in pattern and enabled "Use Substitions", 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/25529970/d005958b-1fe5-44a2-b948-78eda1437efb)

 and Intergrated Processor (the third mv circuit) pattern enabled "Can be a substution".
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/25529970/ddf7fa7b-0da3-4432-aa28-b8abfb6689b3)

When there is any kind of MV Circuit _exists_ in ME Network, it works **perfectly**. But when there is _no existing_ MV Circuit in the ME Network, it will **not** request crafting the Intergrated Processor (which is the substituted components) properly.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/25529970/2b5b2bcf-4aa1-447b-92c3-95233076bc9f)

I haved tried: 
* Replace "Any MV Circuit" with all kinds of MV Circuit (actully) in Robot Arm pattern
* Tested Conveyor Module (which can use Rubber/Silicone Rubber/Styrene-Butadiene Sheet)

the problem persists

### Your Proposal

Properly request crafting substituted components 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
hmm maybe an ae2fc issue. anyway dont use the 'any x circuit' in a pattern, that is not what they are for.

**Comment by EzrealC** [comment]
> hmm maybe an ae2fc issue. anyway dont use the 'any x circuit' in a pattern, that is not what they are for.

I get that, but even if I use a specific circuit (such as Good Integrated Circuit, the second mv circuit) in pattern (same as  [this example](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/195#issuecomment-1287199106)), it still dont request crafting the substituted circuit. And does not work when crafting rubber sheet of the conveyor module, either.

so I feel like the problem might not be primarily related to 'any x circuit'

**Comment by EzrealC** [comment]
> hmm maybe an ae2fc issue. anyway dont use the 'any x circuit' in a pattern, that is not what they are for.

I tried LV Motor recipe (Iron Rod and Wrought Iron Rod are interchangeable), it works when crafting Iron Rod with Extruder (no fluid required), but not when using a Fluid Solidifier (require liquid iron).

maybe an ae2fc issue indeed

**Comment by AtomicGrog** [comment]
"When there is any kind of MV Circuit exists in ME Network, it works perfectly. But when there is no existing MV Circuit in the ME Network, it will not request crafting the Integrated Processor (which is the substituted components) properly."

There's also another hidden gem. If in a large recipe materials list there happens to be a circuit of the same tier intended for another component it's quite happy to use the alternative circuit even if it has the materials to make its own. Because of this it's quite unpredictable and often results in stalled crafts.

Really don't think the substitution can work as is in many cases.

**Comment by chochem** [comment]
probably: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12076#issuecomment-1364525149
however its not obvious at all that there is anything 'intended' here

**Comment by mjevans** [comment]
Not the original problem poster but this is the intent I have.

When shift clicking from NEI into the pattern it should use the 'ore' dictionary for similar parts (when they're not obviously wrong for the craft, like the copper / annealed copper issue) and 'just work' as better versions of circuits are brought online.

Currently you need to have a version of the chip to drag into the pattern and manually encode the correct quantity of the precise chip, and replace the pattern with the new chips each time a type of chip updates.

**Comment by mjevans** [comment]
Alternative solution:
Allow 'Any X-Tier' circuit to be crafted by the input of each other X-Tier circuit, so that only one Mollecular Assembler patch recipe for each upgrade will unify all created circuits to the X-Tier target.
