### ISSUE TITLE
Add Warp Ward as an effect on the Blood Magic alchemy potion flask

### ISSUE THREAD

**Issue by AltyMan** [GTNewHorizons/GT-New-Horizons-Modpack#13590]
### Your GTNH Discord Username

Alty#0661

### Your Pack Version

2.3.0

### Your Proposal

Just like making the Flight potion flask and other vanilla effects, there should be an option to do so with the Warp Ward effect from Warp Theory.

### Your Goal

The current gap between warp solutions and the final pure tear when in EV-IV range is too drastic. A potion flask is a viable and fair solution to this, seeing how you require a whole Blood Magic setup by the time you get to it.

### Your Vision

This item would offer a solution to the warp effects in the game interfering with current progression while you make your way to unlocking ichor and the pure tear. This item also provides an alternate path, as instead of a ton of thaumic research and infusion, a player can go down the Blood Magic route to suit them with warp defence. The idea would be to make it difficult enough to balance the gain, as perhaps the player would require a higher blood orb than the one required for the flight effect, making the task something you need to approach instead of have naturally. Perhaps also make the crafting materials of the potion effect more difficult, like adding an impure tear to the required combination in the alchemical set. Regardless, this feature would build a new solution for players dealing with warp before getting to the pure tear.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
You have the Sane Thoughts potion from botania

**Comment by AltyMan** [comment]
The same thoughts potion from Botania is inefficient to produce, and has 1 use. Unless there's some enchantment or something alike, that potion still isn't a very viable solution.

**Comment by EnderProyects** [comment]
Lmao do you know how boptania brewery works? The vials has 4 uses of 10 mins, the flasks 6 uses, and then you have the incense sticks.., 600 minutes of potion effect

**Comment by EnderProyects** [comment]
are you using glass bottles? ( if yes thats the problem)

**Comment by AltyMan** [comment]
I have no idea, I tried it a while ago. Could be that I did use them. What should I use instead of it, incense sticks? Also, is this a quest line? Because I found none of this on the quest book but maybe I missed it, and if it isn't I would argue that it should be mentioned somewhere.

**Comment by EnderProyects** [comment]
Idk if there is a quest since botania is not very integrated, you can use Managlass Vials ( 4 uses), Alfglass Flasks ( 6 uses), or infuse it with Incense Sticks (1 use, 10 hours)

**Comment by AltyMan** [comment]
Do the Alfglass flasks work in the Thaumic restorer? I gotta check out incense sticks then if it's not then. Also, I guess if I can I would change my suggestion to be adding this to the quest book then.

**Comment by chochem** [comment]
soul brazier and the new soap can deal with warp in early tiers too in case you are not aware

**Comment by AltyMan** [comment]
Yea that was my initial suggestion, to make something between that and the pure tear. Though if the botania flasks/alfglass/incense sticks work like I think all I would suggest is adding it to the quest book so new users would know of it

**Comment by Alastors** [comment]
> Yea that was my initial suggestion, to make something between that and the pure tear. Though if the botania flasks/alfglass/incense sticks work like I think all I would suggest is adding it to the quest book so new users would know of it

I'm actually planning on adding a new upgraded soap on top of my current one + buffing the recipes to all of my soaps

**Comment by Alastors** [comment]
But yeah I agree that the pure tear is stupid

**Comment by chochem** [comment]
pure tear is not stupid at all

**Comment by Alastors** [comment]
> pure tear is not stupid at all

it is stupidly balanced, "Oh yes, you're already past the tier where 99% of this content is and is useful? Okay, well you can finally deal with the thing that prevented you from doing it." It would be entirely different if Dream's historical position was that the pure tear was meant to be the only consistent warp removal item.

**Comment by chochem** [comment]
you are limited and have something that balances you power until you eventually overcome it fully later. sounds like pretty good design.

**Comment by Alastors** [comment]
> you are limited and have something that balances you power until you eventually overcome it fully later. sounds like pretty good design.

Chochom, I know you've done thaumcraft, and you know just how much warp is in the pack, this would be accurate if some effects didn't effectively just straight end a play through
