### ISSUE TITLE
Chance Outputs from Parallel Recipes should use multiple rolls or averages, not a single roll for all parallels

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#13594]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.3.2

### Your Proposal

**The Problem**
Recipes run in parallel should roll the chance for chance-based outputs for each parallel, instead of once for the sum craft.  An example will make much more sense:

1. You have an EV+ Industrial Centrifuge multiblock and give it 9 stacks of Moon Stone Dust.
2. It determines that it can run the recipe as a 16x parallel (36 * 16 = 576 = 9 * 64). 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/2b6b942d-471d-462e-b733-a66fc5912a22)

3. It rolls the chance for each possible output [once](https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/api/util/GT_ParallelHelper.java#L341), and multiples the output quantity by # of parallels (in this case, 16).
4. As a result, from your 9 stacks of Moon Stone Dust, all of the following are valid possible outputs:

Nothing (I got this once):
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/8800b566-b21d-41c0-b8df-60a182ef9fc7)
144 Silicon Dioxide Dust, 144 Manganese Dust, 144 Olivine Dust, 64 Rare Earth, 64 Platinum Metallic Powder Dust, 64 Tungstate Dust:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/a8937111-0d4e-4a19-860b-07f0bf884ba8)
144 Silicon Dioxide Dust, 144 Olivine Dust (I also got this output at one point):
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/5bff8629-29e5-4ae9-8b94-d812492f4f92)

None of these outputs make sense when looking at the % chances on the recipe

Given the input items, it is logical to expect the parallelized recipe output to roughly match the result of having run the recipe 16 times in non-parallelized singleblock machines:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/83a54a03-5458-45ef-8df8-8b7915b57df0)

----

**Proposed Change**
I propose that parallelized recipe processing be updated to roll the chance for each output item individually, or to otherwise fake it using averages.

### Your Goal

This would bring the behavior of singleblock and multiblock chance-recipe processing in line with each other.  

With the current implementation, it is more beneficial to a player to use a group of singleblock machines when processing recipes with chance outputs than to use a multiblock, simply because the outputs will be more consistent.

### Your Vision

This eliminates an unnecessary, unrealistic and unnecessary learning curve about paralellized recipes.

It doesn't make sense that if you process 16 tons of material/ore/etc in a single large batch it all magically has the exact same material composition, but differing composition when done in 16 smaller batches.
When *creating* materials, sure that could make some sense in some contexts.  But when decomposing materials, it makes no sense at all.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
we know how it works. dont see any problem with it though personally. Just a lot more efficient.

**Comment by norbby42** [comment]
The design and flow of the pack leads the player to understand that multiblocks are _better_ and should be upgraded to immediately (especially as many of them have flat out better stats/power usage/etc).

However this implementation makes them markedly _worse_ than singleblock machines when trying to obtain rare chance resources.

In my efforts to optimize and improve, does that mean that I should deconstruct & recycle my multiblock centrifuge and instead put up 9 individual centrifuge machines?  That seems directly counter to the pack's overarching design.

**Comment by chochem** [comment]
way better in my experience than singleblocks all in all.

**Comment by norbby42** [comment]
I disagree.  With singleblock centrifuges, I've gotten about half a stack of Tungstate Dust from Moon Stone Dust so far.  With the multiblock and ~63 stacks of Moon Stone Dust, I've gotten 0.  Yes, luck is playing into it, but that's the problem.

**Comment by wlhlm** [comment]
ALongStringOfNumbers mentioned on Discord how this is implemented in GTCEu:

> https://github.com/GregTechCEu/GregTech/blob/master/src/main/java/gregtech/api/recipes/RecipeBuilder.java#L595-L614
> It basically just adds a chanced output to the recipe for each parallel performed, and then later when the recipe is being finalized all chanced outputs are calculated at the same time, in the same way as normal chanced outputs. But since they are separate entries, each one gets rolled separately

**Comment by desagas** [comment]
Playing lots of GT recently, I agree with @norbby42 , I always hated it, as do many in the community, when ore excavation, or whatever happens, rolls the same fortune on multiple blocks. In my opinion as well, I know it takes a few more nanoseconds to roll and process, but, it makes it more authentic or immersive or realistic if each parallel rolls independently of the others. That is just my opinion. However, for a recipe with multiple chance outputs, like in the photos, I do not agree with the idea that each one should be rolled individually, I think they should all receive the same roll.

**Comment by boubou19** [comment]
average of a random variable is linear, but variance is not. This changes the recipes in a way. Depending if it's not a hot code, we could roll for each parallel to keep consistency with recipes.
