### ISSUE TITLE
ModularUI for GT gui crashing server

### ISSUE THREAD

**Issue by ramseyspace** [GTNewHorizons/GT-New-Horizons-Modpack#13604]
### Your GTNH Discord Username

Ramsey#7916

### Your Pack Version

2.3.4 Alpha

### Your Server

Private

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

When opening circuit assembly line, it crashed the server and we have the latest updated mods. TheEpicGamer said its caused by every single gregtech but like electric implosion compressor doesnt crash/processing assembler. etc EDIT: Some gregtech dont crash. Prass crashes according to TheEpicGamer. We believe its caused by modularUI. But yeah I need to be able to insert circuit imprint but its impossible, we tried to use a hopper and no work

### Crash Report

https://pastebin.com/VQ6TcXb6

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miaowwwwww** [comment]
i tried this in zeta server, server does not crash but i get the client crash.

**Comment by miozune** [comment]
Latest GT has some incompatible changes. Use [Nightly Builds](https://wiki.gtnewhorizons.com/wiki/Nightly_builds) instead of manual update unless you know what you're doing.
