### ISSUE TITLE
P2P GT EU tunnel missing

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#13608]
### Your GTNH Discord Username

Hiakri1nVoid#9527

### Your Pack Version

nightly-Jun/02

### Your Server

zeta

### Java Version

Java 20

### Type of Server

None

### Your Expectation

Trying to right click a p2p me tunnel with a GT cable to get "p2p tunnel gt-eu".

### The Reality

P2P ME tunnel instantly disappeared,only an air block in the same position.Also the P2P tunnel for gteu can no more found in NEI search result.

### Your Proposal

fix the p2p gt-eu tunnel.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/315

**Comment by chochem** [comment]
well I am no longer sure that is actually the fix.
it works in 318-pre though and the comparison lists that https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/compare/rv3-beta-217-GTNH...rv3-beta-218-GTNH-pre. however it doesnt list the actual file change

**Comment by chochem** [comment]
yea it was not the version. it works for me in both 217 and 218-pre (in SP)

**Comment by firenoo** [comment]
Fixed by updating craftpresence to 2.0.5
