### ISSUE TITLE
a few LCR recipes have 2 recipes with different circuits

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13605]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.4 Alpha

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

they don't look strange.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/ec63539a-fe63-4e60-9374-b8882f297c21)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/0bd90802-4487-498f-8bd4-831d7f9a3d2e)

### Your Proposal

erase one.
I guess it's something to do with recipe generations. RA2?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
the 9 one sounds like a 'optimize' problem. dont know about the other, will have to check
