### ISSUE TITLE
Add a method for automated music disc playing

### ISSUE THREAD

**Issue by OrderedSet86** [GTNewHorizons/GT-New-Horizons-Modpack#13609]
### Your GTNH Discord Username

Order#0001

### Your Pack Version

2.3.0

### Your Proposal

There is no method currently for automated music playing. The vanilla jukebox does not support automation and the Sir Mixalot (from GT++) is broken (voids music discs, broken UI). Either fix the Sir Mixalot or add another method of playing music automatically. This would greatly improve "vibes" inside a base and fits with the automation theme of the pack.

### Your Goal

See above.

### Your Vision

See above.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by wlhlm** [comment]
Along those lines, maybe we could add a disk with the GTNH intro song (if that doesn't exist already).

**Comment by chochem** [comment]
there is sirmixelot, but the gui is weird to interact with and I dont understand what it can do. probably unfinished and somewhat broken

**Comment by OrderedSet86** [comment]
@chochem sir mixalot has the following issues:

+ Clicking into the UI doesn't visually show the items placed in until you leave and re-enter the UI
+ If the machine is broken while operating, it will void all music discs
+ Under certain conditions, if broken while operating, it'll queue another song and play it despite being broken
+ Putting a hopper under the sir mixalot pulls items out of every slot, including inputs and currently playing songs

**Comment by chochem** [comment]
uff

**Comment by OrderedSet86** [comment]
Technically it's possible to automate it right now, but it's incredibly incredibly painful:
1. Create golem with use core on chest inputting into jukebox
2. Get the exact timing for the music disc
3. After the time is up, enable, then disable another golem using crystalline brain and redstone signal to take out the music disc and put it back into the original jukebox
4. Goto 1

**Comment by dragongod100** [comment]
One other way to automate playing of music in general would be using Computronics and OpenComputers. Computronics adds cassette tapes of varying lengths (iirc max is 128 min) which you can convert mp3 files to a special file type (DFPWM) and use a download link in OpenComputers to write that music to the cassette, attach some speakers to the computer and you can program play/pause/rewind stuff.

Here for more details: 
https://wiki.vexatos.com/wiki:computronics:tape
https://wiki.vexatos.com/dfpwm
