### ISSUE TITLE
EBF fluid void protection broken

### ISSUE THREAD

**Issue by KhonaB** [GTNewHorizons/GT-New-Horizons-Modpack#13607]
### Your GTNH Discord Username

Khona Betwanhe#7122

### Your Pack Version

Nightly 2023-05-29

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Trying to run an EBF with fluid void protection that produces CO2.

### The Reality

EBF does not run unless fluid void protection is disabled.

### Your Proposal

Fix fluid void mode on EBFs to recognize the lower and upper output hatches separately, as it appears that the issue is that the upper (CO2/SO2/CO) hatch is not recognized.

It is possible that DTs are also broken, but I have not tested it yet.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by KhonaB** [comment]
Update: DTs are also broken, distilling heavy fuel to toluene/benzene/phenol in a 4-tall DT (3 output hatches) doesn't work unless voiding fluids is enabled.

**Comment by Dream-Master** [comment]
@miozune any idea ?
