### ISSUE TITLE
Thaumcraft Inventory and Armor Charging Rings too expensive

### ISSUE THREAD

**Issue by Oculatus** [GTNewHorizons/GT-New-Horizons-Modpack#13611]
### Your GTNH Discord Username

Oculatus#3907

### Your Pack Version

2.3.0

### Your Proposal

I propose the Laptotrons be replaced with energy crystals, and the nuclear reactor with a second 8V solar panel or something else.

### Your Goal

The inventory and armor charging rings are too expensive to make, and not viable by the time you can make them because they require nuclear reactors and Lapotron crystals. They essentially require you to be EV before you can put make them, and then only charge a measly 32eu/t. 
The goal is to make the charging rings an actually viable build, as by the time you can make these you are better off just making a wireless charging setup, or have already made the advanced solar helmet which is not EV tier, and charges both inventory and armor. The rings are also a worse option than the helmet. as to do the same thing as the helmet you need both an inventory charging ring and armor charging ring using up both ring slots.

### Your Vision

With this change, the rings would be available at the same tier as the solar helmet, and would allow you to choose between them. This would also allow you to wear Nanosuit Goggles of Revealing instead of the solar helmet if you choose. Currently the rings are just plain not worth making, I believe they would be at least useable with this change.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Rakdarian** [comment]
updoot

**Comment by Alastors** [comment]
Yeah I'm in favour, the ring is absolute trash as it is

**Comment by chochem** [comment]
the comparison to wireless is not correct. this ring gives free power, it is more like a LV solar+ LV wireless. so maybe the recipe should be LV solar + LV wireless + a bit of cable/thaumcraft ring. (would be HV instead of EV)

**Comment by Oculatus** [comment]
I think that the wireless charger would be a bit out of place, how about we add more magic into the mix, and make it require adept magic energy absorber? Still requires HV circuits, while also now requiring a beacon. I think the cost is there but may be a bit too high at 7 HV circuits. Though honestly the novice one might be better, as it sticks with the theme of each of the generators for the ring recipe all outputting 32eu/t (except for the 8v solar). The Novice magic energy absorber requires mv circuits however it still requires a beacon. So maybe throwing in the LV solar panel instead of the 8V would be a good plan.

**Comment by chochem** [comment]
so like energy crystal + static boots + 2x of some wire + 32v solar + novice energy absorver + lv steam turbine + solid heat gen + x would all be doable in HV.

what about the kinetics? they also take titanium and platinum which I would kinda consider EV

**Comment by Oculatus** [comment]
Also, while further diving into this, it appears that both the Kinetic wind and water generators that are also in this recipe are EV tier. I imagine those will also have to be replaced with something else to bring the ring down to HV tier. Kinetic steam generator and electric kinetic wind generators may be a good option here. Both being HV. 

While they don't require circuits they do require stainless steel which is definitely an investment if trying to rush these rings for whatever reason. These rings are honestly still pretty bad even though it is "free" power. For perspective, if wearing a full suit of Nano it will take 26 minutes to charge one piece from 0 to full, or 1 hour and 44 minutes for the whole set. So therefore I don't believe that trying to make those 2 slots harder than those 2 generators would be the best of plans.

**Comment by Alastors** [comment]
> 

yeah that's fair

**Comment by Oculatus** [comment]
> 

I agree, they are pretty bad also for all of them including the cost of a beacon. But I suppose that is a topic for a different thread. Currently there is no incentive to make them if you can just wait for the hv ones.

**Comment by Alastors** [comment]
> > 
> 
> I agree, they are pretty bad also for all of them including the cost of a beacon. But I suppose that is a topic for a different thread. Currently there is no incentive to make them if you can just wait for the hv ones.

yes, it's been a point of contention for a couple years now

**Comment by Oculatus** [comment]
Another alternative would be, buff the charging rate of the rings to 128eu/t and make it require the master magic absorbers instead.
