### ISSUE TITLE
Add a laser reflector

### ISSUE THREAD

**Issue by IsOobt** [GTNewHorizons/GT-New-Horizons-Modpack#13610]
### Your GTNH Discord Username

oobt#8431

### Your Pack Version

2.3.2

### Your Proposal

Add a reflector block for lasers that can change their direction like the Active Transformer, but cannot merge or divide them (so you'd still need the AT for that)

### Your Goal

I think it is annoying to have to build and setup and active transformer everytime you want to change the direction of your laser, especially considering how volatile they are, when you could just have a block that does a similar task but with a lower price.

### Your Vision

I think having a Laser Reflector would improve moving lasers around, while keeping ATs relevant since unlike ATs the Laser Reflector cannot merge or divide lasers when needed (such as when setting up an array of power generators)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Hiagg** [comment]
i want this

**Comment by hardstylefox** [comment]
im iv but i still want it

**Comment by joshaup1999** [comment]
I'll be shocked if this ever happens. People have been suggesting it for years. Never went anywhere
