### ISSUE TITLE
Nano suit and Quantum suit wings should give Vis Discount

### ISSUE THREAD

**Issue by Oculatus** [GTNewHorizons/GT-New-Horizons-Modpack#13618]
### Your GTNH Discord Username

Oculatus#3907

### Your Pack Version

2.3.0

### Your Proposal

Currently the wings do not give any vis cost reduction even though they are made with Thaumcraft and their predecessor Thaumium wings do give vis cost reduction. I propose that they receive 6% and 7% vis reduction cost respectively.

### Your Goal

This is needed as both other nano and quantum version of Electromagic tools armor, being the nano suit goggles of revealing, and the nano suit boots of the traveler, and their quantum equivalents, all have vis cost reductions. The thaumium wings also have vis cost reduction, which currently disappear once you make the nano ones.

Additionally, if possible, the ability to change the binding for the button to activate the wings would be nice, or a toggle for turning them on and off. This way you don't jump even higher than you would be with nano equipped.

### Your Vision

This change would put them in line with them in terms of Vis reduction cost and give you another armor option for vis cost reduction. Variety is always nice. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Oculatus** [comment]
Not sure if should make a new issue or not for this also, but the wings show up at 8 protection, same as nanosuit chestplate. When you equip them there is 5 armor points above the health bar, while nano chestplate shows 7.

**Comment by vincentcarrier999-cyber** [comment]
Stop closing it if you don't wanna fix it ....
