### ISSUE TITLE
Zeta crashes on opening precise assembler controller

### ISSUE THREAD

**Issue by Borjomm** [GTNewHorizons/GT-New-Horizons-Modpack#13614]
### Your GTNH Discord Username

Borj♿m#2232

### Your Pack Version

Nightly

### Your Server

Zeta

### Java Version

Java 19

### Type of Server

None

### Your Actions

Trying to open precise assembler controller crashes both client and server

### Crash Report

[crash-2023-06-04_15.43.24-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11645638/crash-2023-06-04_15.43.24-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
Now Zeta has updated GoodGenerator
