### ISSUE TITLE
AE2 Wireless Access Point Incorrect Energy Usage

### ISSUE THREAD

**Issue by caleb-pennell** [GTNewHorizons/GT-New-Horizons-Modpack#13629]
### Your GTNH Discord Username

Xestion#0049

### Your Pack Version

2.3.0

### Your Server

Private dedicated

### Java Version

Java 19

### Type of Server

Don't know

### Your Expectation

I was trying to judge a good amount of boosters to add to the wireless access point to not use unreasonable amounts of energy. Expected the displayed energy tick rate to be correct.

### The Reality

Checking the network energy consumption reports a 10x increase for the specific component. 
![2023-06-06_23 45 36](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/96603112/daa71df2-a71a-4de0-b017-88f7133d12ad)
![2023-06-06_23 45 46](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/96603112/3f4fcdd6-705d-4b87-84f4-e1622f4f98fa)

### Your Proposal

I have seen mention that this is because AE2 doesn't properly handle a global modifier. Either 1) mention in the QB that it's off by a factor of 10 or 2) update the display in the block itself so it doesn't blindside and bring down power grids accidentally.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment]
Looks like network tool is right and WAP GUI is wrong
