### ISSUE TITLE
dungeonChest.xml has incorrect weight for Copper Ingots

### ISSUE THREAD

**Issue by Graymare** [GTNewHorizons/GT-New-Horizons-Modpack#13623]
### Your GTNH Discord Username

Embri#3434

### Your Pack Version

2.2.8

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Copper is an abundant resource and based on the distribution of other ingots in the dungeonChest loot pool, one would expect it to be fairly well represented with a high weight.  Similar ingots such as Tin and Wrought Iron have weights of 80 and 70 respectively.  

### The Reality

```javascript
<loot item="gregtech:gt.metaitem.01" damage="11035" weight="9" count_min="2" count_max="6"/>
``` 
Copper ingot is weighted 9.  Believe this to be a typo.
No checking required as the relevant line of code (123) can be seen here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/45537a775fc841f47a723d159f46e8ccc76b92ab/config/TooMuchLoot/loot/dungeonChest.xml#L123

### Your Proposal

Change weighting of copper ingots to 90.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Villy361** [comment]
Your link does not work, sorry. Can I have a working one?

**Comment by Villy361** [comment]
I looked.

**Comment by wlhlm** [comment]
Yeah, that looks like a typo.

**Comment by Villy361** [comment]
> Yeah, that looks like a typo.

Yea, I did a PR for it.
