### ISSUE TITLE
Turning energy hatch with wrench turns off power line

### ISSUE THREAD

**Issue by pckd** [GTNewHorizons/GT-New-Horizons-Modpack#13622]
### Your GTNH Discord Username

cooldev #5731

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 19

### Type of Server

None

### Your Expectation

Disconnected energy hatch does not affect power network

### The Reality

When connected energy hatch turn to the different side, wire disconnected. Than turn hatch back, wire still disconneted, but all wire network turns off. If connect wire back to hatch, power turns on.

Test setup: ev combustion generator 2048v -> transformer 512v 4a -> HV Macerator + HV Energy hatch (tested EBF and LCR)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22480209/5d8bc72e-f000-40f9-9db6-3665cd5b9c5e)
Now turn hatch, wire disconnected, macerator still works:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22480209/63ab94f2-003d-42dd-b544-419e0b7a3fd5)
Then turn hatch back, wire disconnected, macerator out of power:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22480209/28b16b3f-486f-4130-8915-9a06a5803a39)

### Your Proposal

Power line shouldn't be affected by disconnected energy hatch.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Probably same issue as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12383. Leaving this open since the linked issue is about non-connecting energy hatch, so another test scenario.

**Comment by pckd** [comment]
> in my experience this is not really about the hatch you added but about the cable dead end

Yeah probably cable disconnection is incorrect. If I disconnect cable with wire cutter, I can turn hatch without consequences.
