### ISSUE TITLE
Silent Dreamwood Rod doesnt have any recipe

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#13632]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

It should have a recipe

### The Reality

Alastor says it should have a recipe, now it doesnt
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/8107dcaa-4ac0-4c31-9049-3b645064879f)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
same in 7 June nightly

**Comment by kuba6000** [comment]
Also broken in 2.3.0 stable
Seems like the recipe is not modified from the default one, but the research is. Thus making research name differ between the research and the recipe.
It is visible in thaumonomicon
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/53441451/02ff2b8f-31af-4357-bc69-ad90411df940)
