### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by Balekderboy** [GTNewHorizons/GT-New-Horizons-Modpack#13637]
### Your GTNH Discord Username

Marcel Nouille#8911

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

I tried to load the game

### Crash Report

[hs_err_pid1176.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11691371/hs_err_pid1176.log)
It usually crash at 83% after loading gregtech materials

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ydrec** [comment]
Please provide more information on your situation
Where did you get the pack from?
Did you modify the pack in any way?
What hardware (CPU/GPU) are you using?
Have you tried updating cpu/gpu drivers to the latest?
What were you doing when the game crashed?  
Does it crash repeatedly?
Can you successfully launch any other modpack version or another modpack?

**Comment by Balekderboy** [comment]
In order:
-I'm getting the pack from the official website (https://gtnh.miraheze.org/wiki/Installing_and_Migrating), i use MMC
-I didn't modify the pack
-i have an AMD ryzen 5 3600x and a radeon 5600XT
-All the driver are updated
-I just try to launch the game so nothings
-It always crash
-i didn't try it but i will
