### ISSUE TITLE
Hologram Projector ignores Subchannel settings

### ISSUE THREAD

**Issue by IsOobt** [GTNewHorizons/GT-New-Horizons-Modpack#13635]
### Your GTNH Discord Username

oobt#8431

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When trying to autobuild the MEBF, I set the subchannels to osmium glass (6) and fluxed electrum coils (10) and the projection would show these correctly...

### The Reality

... but the master channel (how many projectors were in the stack) was still being followed when trying to autobuild, so 6 in a stack would not do anything because it wanted HSS-S coils, and 10 in a stack wouldn't do anything because it saw osmium glass where transcendant metal glass was supposed to go.

### Your Proposal

Make the hologram projector prioritize the set subchannels instead of the master channels properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Did you make a typo or something? this is working fine in dev env
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/4586901/d342ac0a-392f-4797-9f9c-8aeb32825e3b)
