### ISSUE TITLE
Anti-Universe Generator

### ISSUE THREAD

**Issue by BLocky104** [GTNewHorizons/GT-New-Horizons-Modpack#13636]
### Your GTNH Discord Username

Blocky#0377

### Your Pack Version

latest nightly

### Your Proposal

add a new multiblock wich gates the max tier

### Your Goal

stargate nerf

### Your Vision

firstly, it would gate the stargate more, secondly max tier components,

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
zero details on that proposal? well that is completely useless.

Dont worry, even more late game content will be made.
