### ISSUE TITLE
Fermented Biomass in Pyrolyse Oven

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#13634]
### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Insert Biomass, both forms, into the Pyrolyse oven, and the recipe work, making Fermented Biomass.

### The Reality

Pyrolyse oven, clearly setup correctly, with one LV energy hatch. It creates Biomass, both forms, just fine, works perfectly.

Recipe to ferment in the Porulyse oven for both kinds of Biomass to Fermented Biomass. Neither one of them work. I tried inputting two amps to the energy hatch, but it would not make sense, since both the Biomass, and both the Fermented Biomass recipes have the same Amp/Volt requirements. I tried removing the input bus, replacing it with another casing, and nothing worked. I turned it on and off again, I performed maintenance on it, and nothing worked.

To reaffirm it was working after removing and replacing a lot of the blocks, I tried going from water directly to Fermented Biomass, and this works just fine.

### Your Proposal

Make the two broken recipes work, and if there is an addition requirement for them to work, add that too.

Recipes in Question: 1000L of Biomass (Both Kinds) -> 1000L of Fermented Biomass (No Circuits or Anything else). At 10EU/t, at 5s, for 1000EU in total.

I also tried to look into the scripts to see if it was related to the disappearance of certain scripts as they are migrated to the core, I checked the code for GT5u, and everything appears to be fine, it is just simply not working.

Oh, ALSO, I am on the recommended version ***.87 or GT.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
I am on the .87 recommended by this page. And, there, with that recommended version, it is still present.

**Comment by chochem** [comment]
ah the edit

**Comment by chochem** [comment]
that is very different then

**Comment by chochem** [comment]
pretty sure I found the issue. will fix, thanks. Wont help you in 2.3.3 though, you will have to wait for 2.3.4 for this one.
