### ISSUE TITLE
Crash when opening backpack on Callisto

### ISSUE THREAD

**Issue by TheAimless** [GTNewHorizons/GT-New-Horizons-Modpack#13643]
### Your GTNH Discord Username

TheAimless#3450

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

FTBUtils is installed for chunk-loading. When opening the backpack from Backpack mod on Callisto (or any other Galacticraft planet), the game crashes to main menu and when trying to re-logging into the world, the game stucks on "Building terrain".

### Crash Report

https://mclo.gs/qKM9sJd

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment]
Thanks for the report. There is no 2.3.4 release yet. If you are playing a development/nightly version of the pack, please specify the date it was released in your report (it should say it on the zip file).

**Comment by TheAimless** [comment]
The version I'm playing on is gtnh-nightly-2023-06-08+18-mmcprism-new-java.zip
