### ISSUE TITLE
AE2 Wireless Crafting terminal crash

### ISSUE THREAD

**Issue by CarbonatedTea** [GTNewHorizons/GT-New-Horizons-Modpack#13657]
### Your GTNH Discord Username

CarbonatedMilk#0125

### Your Pack Version

2.3.2

### Your Server

private server

### Java Version

Java 20

### Type of Server

Don't know

### Your Actions

Simply used the wireless crafting terminal from AE2 Wireless Crafting. It immediately crashed my game and kicked me from the server with no error screen. It was linked to a security terminal, charged, and close to a wireless reciever. 

EDIT: appliedenergistics2-rv3-beta-209-GTNH-pre-2-gfbf0ed7 is the version

### Crash Report

[message (1).txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11713121/message.1.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by firenoo** [comment]
Try updating ae2 to beta-213 https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/releases/tag/rv3-beta-213-GTNH

**Comment by CarbonatedTea** [comment]
Hey, sorry took a break from GTNH for a while but am getting back into the swing of things, now on gtnh 2.5.1; default mods and everything, with server tweaks still in. same base, having the same issue on the new ae2 update for 2.5.1.
