### ISSUE TITLE
Add TipTheScales mod

### ISSUE THREAD

**Issue by DotJason** [GTNewHorizons/GT-New-Horizons-Modpack#13650]
### Your GTNH Discord Username

DotJason#2491

### Your Pack Version

2.3.3

### Mod Name

TipTheScales

### The Mod to Add

Mainly adds UI scale settings between "Large" and "Auto" for 2k screen users (I think with 4k vanilla has support for this, but it's still nice to have a slider instead of a toggle).

### Your Reason

"Large" is too small (and odd, 3x, ugh!), and "Auto" is too large (I think it's like 6x on my display??), at least for me personally.
Well anyway I'm sure I'm not the _only_ person who would like some extra UI scale options.

### Preliminary Investigation

Adding just TTS to GT:NH works fine, from my experience.

Now I know we're not supposed to provide support for OptiFine, but just in case, here's an interesting observation:
TTS says that it won't work if OptiFine is detected. This is true, but there's also a workaround for that:
1. Launch the pack with TTS enabled, OptiFine disabled
2. Set the slider to your desired UI scale.
3. Exit the game
4. Launch the pack again, this time enable OptiFine

The UI scale is saved! The only catch is that it's displayed in settings as "Auto" and clicking on it will reset it to "Small", and in order to restore it one needs to follow the steps above again. But if you don't touch the UI scale setting, it will remain like this on subsequent launches and you basically don't have do do anything anymore.

Only tested this myself, so I have no idea if this will work for other people, I can only suspect that it probably should.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by DotJason** [comment]
A bit of an update from the mod dev: the only part that's incompatible with OptiFine is the slider interface, the scale itself can be set with options.txt even without the mod, that's basically why the scale is saved even if the mod is disabled. So... Kind of a pointless addition? Still, it's nice to have an appropriate GUI for the setting, even if OptiFine breaks it.

**Comment by Dream-Master** [comment]
incompatible with optifine so we not add this mod.
