### ISSUE TITLE
Matter Fabrication CPU in recycler mode runs out of power when doing parallel processing

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#13662]
### Your GTNH Discord Username

combuster

### Your Pack Version

2.3.0

### Your Server

Delta

### Java Version

Java 17

### Type of Server

Thermos

### Your Expectation

When a multiblock is built and provided with power and resources, it should be able to run indefinitely.

I set up a matter fabricator CPU with a single UV energy hatch with 2 UV batteries in an attached 4x buffer, and am feeding it fish to generate a constant flow of scrap for later UUA/UUM stages

### The Reality

If the machine starts with more than 11 items in the input bus, the machine gives the out of power sound and no scrap is generated.

Querying the controller with the portable scanner after processing 1 item indicates that it consumes 24576 EU/t and the appropriate multiples with larger inputs. For a 1A UV, that gives room for 21 items being processed, or 42 for the full 2A of the hatch. In addition the block should be able to process another 15 items fully on its internal power storage. This total is less than the 64 parallels supported, but even so the machine fails to process 12 when the theoretical limit should be 57~58, which would mean that more power is consumed than indicated.

### Your Proposal

1: The multi should consume the actual power indicated to prevent observational errors and
2: The numbers should be tuned so that it is able to run indefinitely when provided with 1A of the tier's voltage. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by King65868** [comment]
#12805

**Comment by wlhlm** [comment]
Can this be closed?
