### ISSUE TITLE
Incorrect Stellar Armor durability display with DuraDisplay

### ISSUE THREAD

**Issue by Mr-Jeany** [GTNewHorizons/GT-New-Horizons-Modpack#13663]
### Your GTNH Discord Username

OuO#0803

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

I was expecting to have 2 numbers on my stellar armor (energy and durability) as was showed in GT:NH Discord server.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/72220793/535a3609-5467-462f-9b51-11a5b3048e13)

### The Reality

Reality I have **nothing** written on any of my stellar armor piece.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/72220793/f68ab09a-4e4b-4c23-8677-1d47298c99a5)

### Your Proposal

Show durability and energy of stellar armor

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Mr-Jeany** [comment]
UPD: I have just put my leggings in Thaumic Restorer and it showed energy for 3 seconds after I put them on (only energy, not durability. It wasn't at full durability

**Comment by Caedis** [comment]
Did you edit the config?

**Comment by Caedis** [comment]
Hmm, the helm is not full durability so it should show up.

Can you run `/cofh hand tag` and post a screenshot or copy and paste it here?

**Comment by Caedis** [comment]
@Mr-Jeany in case you forgot

**Comment by Mr-Jeany** [comment]
I'll make it today, sorry

**Comment by Mr-Jeany** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/72220793/2cf134e9-3db1-4b96-b791-ebcbfcd923d1)

I got this

**Comment by Caedis** [comment]
Not sure what the issue is. Probably has something to do with Crucible

**Comment by ghostflyby** [comment]
Reproduced in my private **vanilla forge** server on Ender Steel Armors and sword.

**Comment by ghostflyby** [comment]
I opened [a PR](https://github.com/GTNewHorizons/DuraDisplay/pull/7) describing and fixing this.
