### ISSUE TITLE
Copper cable recipe broken in crafting table.

### ISSUE THREAD

**Issue by mindcloud69** [GTNewHorizons/GT-New-Horizons-Modpack#13669]
### Your GTNH Discord Username

mindcloud.

### Your Pack Version

gtnh-nightly-2023-06-08+18

### Your Server

personal server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

craft a copper cable with a piece of copper wire and a rubber sheet in standard crafting cable. 

### The Reality

The copper cable recipe is missing for the crafting table with a sheet of rubber. Look briefly and didn't see any other cables missing the crafting table recipe.

### Your Proposal

Fix the recipe. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miisi** [comment]
MV+ cables aren't meant to be handcrafted

**Comment by chochem** [comment]
yea that never existed
