### ISSUE TITLE
The output bus (ME) and output hatch (ME) may not function properly in certain situations

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#13660]
### Your Pack Version

2.3.4

### Your Server

My own server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I am trying to synthesize something, and generally, the finished product will be sent to my ME network after a period of time.
我正试图合成某样物品，一般来说，成品会在一段时间后送入我的ME网络。

### The Reality

Both ME outputs have completely failed on my machine. They store items or fluids internally, but they will not be output to the network. The network connecting them does not have any storage function, but only sends their finished products to the ME network I synthesized for use. I have checked various reasons and cannot solve them. Sometimes, exiting the server and returning to single player mode cannot output correctly or output at an extremely slow speed.
两种ME输出在我的机器上完全失效了。它们内部存储有物品或者流体，但是不会输出到网络中，连接他们的网络并没有任何存储功能，只是把他们的成品送到我合成使用的ME网络中，我检查过各方面原因都无法解决，退出服务器回到单人模式有时也无法正确输出或者以极其慢的速度输出。

### Your Proposal

There must be something wrong. In version 2.3.2, they worked very well, but after the update, they became less useful. Please fix or roll back the adjustments made to them.
一定是有什么搞错了。在2.3.2版本，它们工作得非常好，更新之后就变得不那么好用了，请修复或者回滚对于它们的调整。

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Thanks for the report. There is no 2.3.4 release yet. If you are playing a development/nightly version of the pack, please specify the date it was released in your report (it should say it on the zip file).
