### ISSUE TITLE
Broken Distillery/DT recipes

### ISSUE THREAD

**Issue by TheAimless** [GTNewHorizons/GT-New-Horizons-Modpack#13667]
### Your GTNH Discord Username

TheAimless#3450

### Your Pack Version

2.3.4 

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Some distillery/DT recipes should have stayed the same as 2.3.0

### The Reality

Several broken recipes. Examples:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/77198928/5187c63b-64e1-452a-826e-be9208053c8a)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/77198928/b74c79ad-b1d0-42eb-bd92-5468f51fa498)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/77198928/bcaf0e61-d2fb-4dbf-aa0c-b1f23e7a0a5c)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/77198928/a0e82f21-15d8-4d1c-b841-e2b751d8e5aa)

### Your Proposal

Fix the distillery/DT recipes back to what they were in 2.3.0

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
uff
