### ISSUE TITLE
Phantom blocks in NEI

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/GT-New-Horizons-Modpack#13664]
### Your GTNH Discord Username

Pilad

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Phantom blocks in NEI

### The Reality

![2023-06-12_00 44 19](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/e8ff3399-dcff-4c20-b815-a831ffca2a51)

### Your Proposal

Fix please.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TheEpicGamer274** [comment]
It will not fixed anytime soon as its part of new multis and the textures, etc have not been added fully to master gt5 yet
