### ISSUE TITLE
Rename "Assembling Line" to "Assembly Line"

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13676]
### Your Pack Version

2.3.3+

### Your Proposal

I believe we should change the name back to its original form.

### Your Goal

Not a single person in the history of gregtech has ever thought it was called "assembling line" and it causes many of us to be confused. the common terms are "assline" and "assembly line" with "assembly line" being the true real actual name of the multi.

we have been confused for 6 years in gtnh and believed it was called assembling line and yet no one has adopted the new name so i think it is time for a revert to where it should be

### Your Vision

prevent confusion from everyone trying to find the assembly line controller in their ae2 system or nei when i doesnt come up for a search of "assembly" like were all used to

the places where this incorrect phony name are referenced are as follows
current name - real name that it should be
assembling line controller - assembly line controller
assembling line casing - assembly line casing

along with the data bank tooltip, and research station tooltip. 

On the contrary, it is called "Assembly Line" by all machine variants and related machines such as the "Component Assembly Line", "Circuit Assembly Line", "Advanced Assembly Line", and "Assembly Line Slave Connector", 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
was introduced here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/1252
