### ISSUE TITLE
Spamming errors in the gregtech log file

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/GT-New-Horizons-Modpack#13678]
### Your GTNH Discord Username

Pilad

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Spamming errors in the gregtech log file.
But if you compare the recipe in the code and in the screenshot, then all the components of the recipe are there.
There are a lot of such errors about missing items in the gregtech log.
These are erroneous messages, or perhaps some of the recipes are broken.

### The Reality

![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/d574ede4-876f-45ec-9a26-f44979419394)

### Your Proposal

Fix please.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
yea we know about that. havent had the time myself
