### ISSUE TITLE
Allow Big item filters insice Vacuum chest

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#13673]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.3.4

### Your Proposal

Change that only basic filters can be used and include big item filters to, or 

### Your Goal

To not have to use many vacuum chest for automating recipes that use dropped items

### Your Vision

its a nice qol feature and can make setups more nices and less messy

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by HJM9x** [comment]
Can this be reconsiderd
