### ISSUE TITLE
Add Infinity Catalyst recipe to GT compressor

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#13674]
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.3.4

### Your Proposal

Infinity Catalyst recipe added to GT5 compressor

### Your Goal

Later in the game a lot of endless catalysts are used to make endless ingots, using GT5U's compressor will be faster and easier to automate

游戏后期中大量使用无尽催化剂制作无尽锭，使用GT5U的压缩机会更快速，而且自动化更简单

### Your Vision

The original recipe for Endless Catalyst was too slow, and the normal compressor input and output were limited so that we couldn't quickly compress the powder to get Endless Catalyst

无尽催化剂的原配方制作方法过于缓慢，普通的压缩机输入与输出都被限制了，这样我们无法很快的压缩那些粉末获得无尽催化剂

However, in order to balance the recipe rationally, we can set the recipe used in GT5U compressor to UEV voltage or UHV voltage in order to use

不过为了平衡配方的合理性，我们可以将在GT5U压缩机中使用的配方设置为UEV电压或者UHV电压才能使用

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AtomicGrog** [comment]
Wondering how far through you are, maybe only just getting into infinity?

Endgame you use 2 catalysts to make 128 infinity ingots, and i get to make approx. 20 catalysts/sec in the neutronium compressor, so thats a fair bit of infinity/sec (2k?). Of all the things i have speed issues with (I'm umv/uxv) this doesn't features as a problem.
