### ISSUE TITLE
Liquid Air Distillation Tower recipe not working

### ISSUE THREAD

**Issue by coconuq** [GTNewHorizons/GT-New-Horizons-Modpack#13679]
### Your GTNH Discord Username

theday

### Your Pack Version

2.3.4

### Your Server

private

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/58561708/b64d6092-a9c1-4cd2-8f9a-b5124b3e9c82)
This recipe should work (ofcourse i use enough energy to run it)

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/58561708/1658b136-c993-4f1a-a915-291d54e2c3ed)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/58561708/252c2119-1017-4967-a63c-edd05bc575c2)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/58561708/0b83b58f-9915-4345-a081-28bd79a1576e)
Nothing happens

### Your Proposal

It worked in 2.3.2 before update to 2.3.4

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Do you have necessary space to dump all the fluid outputs? Either use larger output hatches or enable voiding excess fluids.

**Comment by coconuq** [comment]
> Do you have necessary space to dump all the fluid outputs? Either use larger output hatches or enable voiding excess fluids.

As i already wrote, before 2.3.4 update all works perfectly.
Surely i have giant output hatches for 1-3 outputs and hv one to the others, also tryed turning on voiding, replacing all the blocks the distillation tower has, turn on/off machine

**Comment by miozune** [comment]
Cannot reproduce. Does your setup work for other recipes?

**Comment by coconuq** [comment]
Maybe my world corrupted after update,because i  have some differwnt troubles for example ME system pereodically turning all connections off (all i mean really ALL: p2p, with cables and direct connection of me drives to controller. The most strange part of this is it only fixes itself only when i grab and place back one of storage cells in any drive. If this might be a point in world corruption then i maybe need to recreate the world or use a backup)

**Comment by desagas** [comment]
You said you have only 1-3 outputs, if you expand it to have 10 output hatches and 1 output bus, AND your inputs, does it work then? I am curious if that would work, because you have it set to void none, if the extras have no place to go ... just thinking outloud, maybe they are stuck in lalaland?

**Comment by coconuq** [comment]
@desagas, You read me incorrectly: firstly i said that recipe worked perfectly in 2.3.2, and actually i have full height dt (of 13 outputs i think? all possible hatches and a bus). Secondly.. i mean.. only 1-3 hatches are giant, because of recipe output, and the rest of them are not giant (hv in my case).

I think it's just my bad that this happened - i think i could do smth wrong in modpack update (never used technic launcher b4), so if noone else have ideas for me or no man can reproduce this, i'll close this issue

**Comment by desagas** [comment]
Out of curiosity: were you using an energy hatch where both amps were being used in order to step up the level of the machine? I am curious? Or, is it normal that everything except for the blast furnace, energy hatches only accept 1 amp? IE, in my cracking unit, with an MV energy hatch, it will not draw two amps, instead, I have to have two hatches which both will draw only one amp. I do not know if this is a new change, or an old one.

**Comment by coconuq** [comment]
I am using 2 ev hatches that makes iv of 4 amps ev. The recipe with liquid air have a base voltage of ev. I'll check this if maybe i need 1 hatch or what, but with other (not chwcked them all) liquids like creosote, cracked oil products, nq line all works. Surely i think this is because of something was done to multiblocks in this update.

**Comment by desagas** [comment]
Did you find a solution? If not, if you add two additional ev hatches, so there are four in total, does it work then? Because, as I mentioned before, it seems as though mutliblock structures outside of the EBF are no longer accepting more than one amp from a energy hatch in certain cases. This may be what is happening in this case?
