### ISSUE TITLE
Void miner can mine some gt.oresblock.xxx

### ISSUE THREAD

**Issue by hoshinokiseki** [GTNewHorizons/GT-New-Horizons-Modpack#13687]
### Your GTNH Discord Username

KisekiUnofficial

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

after updating to 2.3.4, my void miner III in deep dark mined some ores just like gt.oresblock.490.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/88672077/e7161e17-9849-49de-baec-15ad981ca8b6)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/88672077/776a33cd-0866-45b9-b10f-2a2684f51435)
so, what are they?

### The Reality

up

### Your Proposal

up

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
that would be Infuscolium. dont know why though

**Comment by chochem** [comment]
ah that is one of the metallurgy materials that we disabled. I dont know enough about the VM to know why it would still make it. maybe its based on when the dim was created, not sure.

**Comment by hoshinokiseki** [comment]
> ah that is one of the metallurgy materials that we disabled. I dont know enough about the VM to know why it would still make it. maybe its based on when the dim was created, not sure.

I create a new save and enter the deep dark. the same. the void miner still can mine ores like gt.oresblock.960

**Comment by Tommeh1** [comment]
Also note that their previously corresponding dusts still exist

**Comment by chochem** [comment]
depends what you consider _exists_. they dont get deleted. just remnants of items with the same id and meta
