### ISSUE TITLE
GT wireless EU bug and suggestion

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#13686]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

last version

### Your Server

MP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

/gt global_energy_join FoKuCNiK Paulo

this command combines both of their players into a common energy group. To leave the group, you need to register this command again. But when I do that, THE ENERGY IS STILL TOTAL. The essence of the bug is that it is impossible to leave the team in any way. Let's move on to the next bits:

All commands from the category "/gt global_energy" require OP rights. I, as a server admin, constantly receive NEW players who do not know each other, and I am not going to give them OP rights. Anyone who wants to create an alliance manually
 typing a command is also cringe. The fact that each player who has the right to create teams can connect any two players into a team, I am also silent. So, I am not empty-handed and offer a GREAT solution:
 
 1) Remove the OP's need for the /gt global_energy_join command

2) Allow the player to add ONLY to himself in the party (that is, so that he cannot unite other players in the party)

3) Make a command like "/gt global_energy_join [nickname]". And this command will add to your team a person with a nickname that is entered in the [nickname] field

it literally takes 10 minutes, but unfortunately I don’t know how, so I ask you to pay attention to my request.

### The Reality

up

### Your Proposal

up

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
It isn't a 10 minute task, really this should use some UI or other unified friend system like forestry offers but I don't really have the time to look into it.

Also you can leave a network by joining yourself i.e. /gt global_energy_join Colen Colen. It's not the prettiest system, but it's also only used by like 5 people because it's UMV tier tech, so not a huge burden to just run the command.

**Comment by FoKuCNiK** [comment]
/gt global_energy_join FoKuCNiK FoKuCNiK does nothing, our networks are still shared ... I write that this does not work

**Comment by FoKuCNiK** [comment]
1) add a friend to the group
2) NO FUCK YOU CAN'T REMOVE HIM FROM THE GROUP

**Comment by FoKuCNiK** [comment]
apparently you need to record a video, as always words are not enough

**Comment by FoKuCNiK** [comment]
It SHOULD be fixed to add ANY other player with ANY other players to the group.

The player should be able to add only some player to his group (even if he agrees to write a command without his knowledge)

**Comment by wohaopa** [comment]
I have the same problem, and I think I can use Quest's team system. The GC should also use Quest's team system. This eliminates the need for multiple team systems.

**Comment by FoKuCNiK** [comment]
party system through quests sounds healthy

**Comment by Connor-Colenso** [comment]
I would agree in the long run some unified team system would be ideal, but you don't always want to share everything and having some kind of permissions system would make it a much more complex endeavour.
