### ISSUE TITLE
offline-mode should not be unsupported

### ISSUE THREAD

**Issue by wohaopa** [GTNewHorizons/GT-New-Horizons-Modpack#13684]
### Your Pack Version

2.3.4

### Your Proposal

AmunRa does not support offline mode. 

### Your Goal

I don't think it's necessary, especially if it's because of UUID. The offline UUID is usually calculated from the user name, and each user name usually has a unique UUID. If it is to prevent hackers, especially should not be, generally offline mode server will have other means of authentication. I think it's a stupid decision to block offline server startup.

### Your Vision

The offline mode server can be started and played normally

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
RIP

**Comment by ChemEng227** [comment]
I wish it was just a temporary solution and will be fixed in future.

**Comment by boubou19** [comment]
well, for now it's our policy not to support it, and it's not planned to change it.
