### ISSUE TITLE
Steel dust should be able to be made into ingots with furnace.

### ISSUE THREAD

**Issue by Oculatus** [GTNewHorizons/GT-New-Horizons-Modpack#13682]
### Your GTNH Discord Username

Oculatus#3907

### Your Pack Version

2.3.0

### Your Proposal

I propose that steel dust should be able to be made into ingots with furnace, or at a minimum, dust in fluid extractor with solidifyer.

### Your Goal

This is needed because currently once you get steel dust, you have to throw it in the ebf, wasting tons of time, and is really pointless processing. Your other option is instantly turn it into steel ingots with a fraction of the processing time, no power consumed, and less work, by just simply throwing it into your tinkers smeltery. It makes no sense that now that you have access to electricity, your turning of dust to ingots gets slower. Ideally steel dust should be able to be put into a furnace to turn into ingots since either you get small amounts of it from mob drops, or you have to have already made the steel, and the dust is a byproduct of crafting things like rods in a lathe early game. 
Furthermore, the fluid extractor can turn everything else steel directly into molten steel which can be turned into ingots, but not dust, because its harder i guess??

### Your Vision

This will improve the early game by removing the unnecessary annoyance of not really being able to do anything with steel dust until EBF, and encouraging you to stop using your tinkers smeltery to reuse your hard earned steel ingots. Instead you get to use the machines you just built to make your dust into steel, which feels much better.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by querns** [comment]
Steel dust can be turned back into ingots using the TiCon smeltery before the EBF.

**Comment by Oculatus** [comment]
Thats basically my point. Why should it be able to be smelted in the tinkers smeltery, but not in say a fluid extractor?
Its gatekeeping for 0 reason.

**Comment by Oculatus** [comment]
Yeah that is basically my entire issue with it. Gatekeeping as in you cannot turn it back into ingots without using the tinkers smeltery until EBF. the tinkers smeltery can be sped up if you just attach more tables with more casting tables and pipes, and then you are faster than a MV ebf at that point. It does not make sense why the tinkers smeltery should be the better option, especially since the fluid extractors can already melt all the other steel items. 

I was one to save up all the dust, and then I would have stacks of steel dust i threw in the smeltery, cost me like what, 100mb of lava, and then it turns back into steel ingots with minimal effort over the course of half an hour or so, depending on how many casting tables you have. Its like, why would i use for instance the primitive blast furnace to turn my steel dust into steel, at 240 seconds per ingot. Thats just illogical, make more steel out of iron instead. To be honest, that recipe probably needs a buff too.

**Comment by Alastors** [comment]
No, this is intentional, now stop playing stupid games before someone ends up nerfing the TiCon dust to ingot recipe.

**Comment by Oculatus** [comment]
I believe that something can be intentional and incorrect/erroneous at the same time. At a minimum, the fluid extractor should be able to handle the dusts like it can with other dusts that don't need EBF, as at its core, steel dust does not need EBF, it only need a tinkers smeltery, or a primitive blast furnace.

**Comment by Alastors** [comment]
Would you be so kind to remind me how the fluid extractor handles aluminium dust love?

**Comment by Oculatus** [comment]
Alu requires EBF, steel does not

**Comment by Alastors** [comment]
> Alu requires EBF, steel does not
> 
> 

You see why I'm mentioning this right?

**Comment by Oculatus** [comment]
Well theres 2 ways you can interpret that. Either alu shouldnt require EBF or steel should. If steel should then the recipe for tinkers smeltery dust to steel should be gone.

**Comment by Alastors** [comment]
The latter would be accurate, so like I said, stop playing stupid games or you're gonna get stupid rewards.

Steel is a tiering metal, all tiering metals have to be prepared in the ebf even with their base dust form. 

You can make the argument for bronze and wrought iron, but the former isn't exactly the tiering metal and the latter is an extremely special exception that can't be made in the ebf in the first place.

**Comment by Oculatus** [comment]
I feel like if we can make steel in a primitive blast furnace, it should be able to be re-melted in a machine that already melts metals which require higher temperatures to melt.

**Comment by Alastors** [comment]
> I feel like if we can make steel in a primitive blast furnace, it should be able to be re-melted in a machine that already melts metals which require higher temperatures to melt.
> 
> 

That wouldn't be steel, it would be a variant called "crucible steel" https://en.m.wikipedia.org/wiki/Crucible_steel#:~:text=Crucible%20steel%20is%20steel%20made,not%20produce%20temperatures%20high%20enough.

**Comment by Oculatus** [comment]
How so? It's already steel dust, just being re-melted. If you want to get that specific then we shouldn't be able to melt anything that's already made out of steel in a fluid extractor else it becomes an entirely different steel.

**Comment by Alastors** [comment]
... did you not just read the thing I sent you? It's an impure alloy of steel that you can make in a crucible, not pure steel...

**Comment by Oculatus** [comment]
Okay so then the steel we are making in a Primitive furnace isnt correct so then make that different from the steel we are using, and then make regular steel dust able to be melted, easy.

**Comment by Alastors** [comment]
> Okay so then the steel we are making in a Primitive furnace isnt correct so then make that different from the steel we are using, and then make regular steel dust able to be melted, easy.

... sir do you know what a blast furnace is?

**Comment by boubou19** [comment]
that won't change, because it is intended.
