### ISSUE TITLE
Dense Black Plutonium Plate recipe missing circuit 9

### ISSUE THREAD

**Issue by harrynull** [GTNewHorizons/GT-New-Horizons-Modpack#13693]
### Your GTNH Discord Username

harrynull#9630

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 19

### Type of Server

None

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7413706/dc8a0607-34ad-43a0-ac79-cae4cf4e9533)

### The Reality

In addition to the one above, this also exists:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7413706/ef495d2b-34c7-492d-9317-4bf2585d185d)

which causes recipe conflicts

### Your Proposal

remove the no-circuit variant

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
Many other plate recipes are also missing the circuit in JEI/NEI or whatever it is now, ONLY! The Dense Obsidian plate is missing it in the search, but requires it in the bender. The same is true for many others.

**Comment by chochem** [comment]
looks like some old buggy code in scripts that never worked now suddenly works after scripts got converted to code. well will just remove that.
