### ISSUE TITLE
Thaumic Bases Node Manipulator Focus: Stability makes nodes bright

### ISSUE THREAD

**Issue by Nereidregulus** [GTNewHorizons/GT-New-Horizons-Modpack#13698]
### Your GTNH Discord Username

Nereid#2524

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

To boost a Pale node to Bright, you need to use the Node Manipulator from Thaumic Bases, with at first a Stability Focus to convert the pale node into a normal one, and then use a brightness focus to turn it into a Bright node.

### The Reality

With a Node Manipulator, you only need to use the Stability Focus to turn the node into bright. No Brightness Focus is needed

(I haven't tested if the Brightness Focus turns a Normal node into a Bright)

### Your Proposal

The Brightness Focus should be used instead, since it's much harder to craft.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
Ngl im fine with this, brightness effectively doesn't matter tbh, because by the time you can make bright nodes, you can just straight create 10k+ nodes for free
