### ISSUE TITLE
the LuV lapo is missing an assline recipe

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13690]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.4

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

have an assline recipe like it used to 

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/71e005a7-4ea0-4335-ba6b-2f6b1a3fb888)

### Your Proposal

readd the recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
was already fixed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/639
