### ISSUE TITLE
Gregtech pump redstone conditionals are wrong

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13706]
### Your Pack Version

2.3.2

### Your Server

Private server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

When pumps are placed on pipes or tanks they'll be active when set to only run with a redstone signal, despite not receiving any.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment]
Related (stale) ticket with some more info https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10335
