### ISSUE TITLE
Add UUIDoffline mod

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#13709]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.3.4Beta

### Mod Name

UUIDoffline

### The Mod to Add

UUIDoffline allows to sync Server-side and Client-side player UUIDs and prevents UUID corruptions in offline mode servers.

### Your Reason

In current version AnumRa stops offline mode server from starting due to UUID issues, and this mod might be able to fix it. Besides this mod also helps in quest book issues in offline mode servers.

### Preliminary Investigation

In offline server test (without AnumRa installed) no glitch was found.
In online server this mod does not function, but also add no extra burden.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by coconuq** [comment]
It would be really nice

**Comment by boubou19** [comment]
Offline mode isn't supported. If you need an alternative to do what can do online servers, that's on you but this kind of mods will never reach the pack as long as we keep our current policy about offline mode.
