### ISSUE TITLE
Enable Better Loading Screen Startup Sound

### ISSUE THREAD

**Issue by SkilledAlpaca** [GTNewHorizons/GT-New-Horizons-Modpack#13705]
### Your GTNH Discord Username

skilledalpaca

### Your Pack Version

2.3.0

### Your Proposal

Change `B:playSound=false` to `B:playSound=true` in [betterloadingscreen.cfg](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/Betterloadingscreen/betterloadingscreen.cfg#L34-L35)

### Your Goal

Assists with knowing when the pack has fully loaded. 

### Your Vision

This allows people to work or view other items while the pack loads in the background. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by wlhlm** [comment]
We've had that request [before](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11483), looks like it was just forgotten about. PR welcome, if you feel up for the task.

**Comment by boubou19** [comment]
a ding vs sweat dreams from the aviators :thinking:

**Comment by Dream-Master** [comment]
yea i guess we not need this ping sound. If the pack is loaded the music starts so you known well when it is done :)

**Comment by wlhlm** [comment]
It doesn't play if you have music turned off.

**Comment by boubou19** [comment]
well then you can turn on locally if you remove the sound. Or maybe we can change the channel of the music played by cmm so it's only controlled by master? Because we took care to put a music when the instance is loaded, so it's not to be polluted with a ding when the music starts.

**Comment by minecraft7771** [comment]
For me the music sometimes doesn't start immiedietly. Only few minutes after being in the main menu.

**Comment by wlhlm** [comment]
I just tested is and can confirm that the menu music only started playing ~15s after the 'ding'.
