### ISSUE TITLE
Industrial Wand Charging Station disconnects from power?

### ISSUE THREAD

**Issue by pokeball99** [GTNewHorizons/GT-New-Horizons-Modpack#13701]
### Your GTNH Discord Username

Kekel7#9661

### Your Pack Version

2.3.0

### Your Server

Private

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

The Industrial Wand Charging Station should work as intended when supplied with power via wires.

### The Reality

At seemingly random times it will suddenly not charge at all, and the wire has to be reconnected.

### Your Proposal

It should not disconnect itself from power randomly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
The thing is buggy as fuck, ngl
