### ISSUE TITLE
Negative bolt speed interferes with the Thaumometer

### ISSUE THREAD

**Issue by DotJason** [GTNewHorizons/GT-New-Horizons-Modpack#13708]
### Your GTNH Discord Username

DotJason#2491

### Your Pack Version

2.3.4

### Your Server

Self-hosted

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

This is rather obscure and convoluted.

First, you have to make a TC crossbow with negative arrow speed.
<img width="419" alt="Снимок экрана 2023-06-15 000705" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8113703/c8f47677-da69-425a-84b5-1104c7f2ef2c">

Then you have to fire it. It will not shoot a bolt, but it _will_ create an invisible entity that seems to just stay in place indefinitely.

### The Reality

If you look through a Thaumometer, it displays "entity.TConstruct.Bolt.name", in a rather large area around the place where the crossbow was used (seems to be ~8 blocks in all directions? Vertically too), regardless of the angle at which the player is looking. This does not disappear even after server restart, and you can't scan anything else because of it.

![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8113703/33b9ca64-9a39-4bb8-921d-87352a69f63d)

### Your Proposal

Make negative speed crossbows shoot backwards... Or just remove all negative arrow speed stats from GT materials and make them positive (I wonder why they were negative in the first place?)
![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8113703/1a666b8f-8948-4ecd-9b87-a514e94000de)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
This is an insanely small nitpick, TC = Thaumcraft, TiC = tinkers construct

**Comment by Alastors** [comment]
May seem stupid to point that out but it's important when two mods share content

**Comment by Alastors** [comment]
TCon would work too
