### ISSUE TITLE
Ender chest and Hand of Ender

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#13710]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.3.4

### Your Proposal

Add a recipe for Ender chest, so you can craft the hand of Ender from botania, or add a recipe for the Hand of Ender, so usefull with the Rod of the Shifting Crust:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/75f12330-7ec2-4f2a-9815-8293f033d551)

### Your Goal

Add the personal Ender chest crafteable, since right now you can still find it in some dungeons, and make the hand crafteable since is very usefull for building

### Your Vision

is a qol feature that dont harm anyone

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Srdra2k3** [comment]
I believe the ender chest used in the personal e-chest recipe might be a bit too expensive. As far as I know the personal e-chest does not allow any cross-dimensional item transfer. Gating it at MidLate-IV tier makes it a bit too obsolete imo since wireless crafting terminals and a whole load of backpacks already exist.

**Comment by Srdra2k3** [comment]
Technically yes. But the chest does not allow any insertion or extraction of items via automation, making it just a basic backpack. 
I am aware of gtnh being a non-wuss pack, I just don't see any reason why it should be as expensive for basically being worse than an ender storage ender chest.

**Comment by EnderProyects** [comment]
> Technically yes. But the chest does not allow any insertion or extraction of items via automation, making it just a basic backpack. I am aware of gtnh being a non-wuss pack, I just don't see any reason why it should be as expensive for basically being worse than an ender storage ender chest.

The issue is to be abble to use the Hand of Ender, not about adding or not a eassy ender chest, thats why I request a expensive recipe that uses the other ender chest to craft this one, so there are no issues about tiering

**Comment by EnderProyects** [comment]
The other possible thing is to add the EnderStorage Ender chest in the recipe of the Hand of Ender, making this act like another Ender pouch ( but that the rod can acces it)

**Comment by Srdra2k3** [comment]
I still don't see why the hand of ender should be that expensive overall. 

What makes it different than a normal backpack that's able to be crafted at late-steam tier?
Is it not just a re-texture of the backpack with the extra feature of the rod of the shifting crust compatibility?
Why should the hand of ender be held at the same level of cost as the ender storage ender chest?

I'm sorry if I seem like a "waa waa everything is so expensive!" guy, but i really don't understand why the recipe should be expensive for what the item offers which is yet to be answered.

**Comment by querns** [comment]
The entire point of adding this item is to get a "backpack" that is compatible with the Rod of the Shifting Crust (RotSC), Botania's version of the Equal Trade focus. Neither Equal Trade nor a RotSC can pull from a normal backpack, but RotSC specifically can pull from a Hand of Ender.

Given the suggested recipe is quite expensive and tiered to IV, when many interdim item teleportation options are unlocked (enderstorage ender chest, ender pouch, quantum bridge, dimensional transceiver,) I don't see the problem. Vanilla ender chests are hostile to automation, making this proposal useful pretty much only for expanding the inventory available to the RotSC.

**Comment by chochem** [comment]
this is the chest you can only find in the end currently right? I guess the tiering is fine with the IV ender storage ender chest required. Imo the question is more if we want to reduce exploration reasons.

**Comment by EnderProyects** [comment]
Yes, this chest you can find only in the end, I only want that the Hand of Ender is crafteable, so I dont care if you can craft the Ender chest or no

**Comment by EnderProyects** [comment]
I was thinking about reopening this or ask if at least the hand could be added for QOL for builders, but now that I think someone was doing the world edit item, so idk if this is usefull then

**Comment by Dream-Master** [comment]
> ### Your GTNH Discord Username
> Ender Proyects#6669
> 
> ### Your Pack Version
> 2.3.4
> 
> ### Your Proposal
> Add a recipe for Ender chest, so you can craft the hand of Ender from botania, or add a recipe for the Hand of Ender, so usefull with the Rod of the Shifting Crust: ![image](https://private-user-images.githubusercontent.com/45178400/246100056-75f12330-7ec2-4f2a-9815-8293f033d551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzODQxNDMsIm5iZiI6MTczNDM4Mzg0MywicGF0aCI6Ii80NTE3ODQwMC8yNDYxMDAwNTYtNzVmMTIzMzAtN2VjMi00ZjJhLTk4MTUtODI5M2YwMzNkNTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDIxMTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MzM2Njg5MmNiZjdhYTZkMWQ1MWFlZTAxNDQ3NTU5ZTk4Y2YyNzlhY2NiYzRmYTIxNTM0NDUyMmZjZDA3ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gYXOrmeC1ka5ibPp73L10DO4KhsqCcMxCeKXA98GC5g)
> 
> ### Your Goal
> Add the personal Ender chest crafteable, since right now you can still find it in some dungeons, and make the hand crafteable since is very usefull for building
> 
> ### Your Vision
> is a qol feature that dont harm anyone
> 
> ### Final Checklist
> * [x]  I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying _I like this feature please reconsider adding it_ will prompt us to investigate and reopen it once we confirm your report.
> * [x]  I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
> * [x]  I understand this change request may not attract enough attention and thus not be implemented.
> * [x]  I understand this change request may be rejected due to other community members thinking it's inappropriate.
> * [x]  I believe this feature would make the pack better.

why not use the ender chest from the mod for the hand of ender ? no need to add the vanilla ender chest. I not read any comment so maybe that was suggested already?

**Comment by Dream-Master** [comment]
or change it acess the mod ender chest

**Comment by EnderProyects** [comment]
either way the hand of ender needs a recipe, since it doesnt have one, also I was not going to add a recipe for the ender chest, since you can find this in some dungeons ( big nerf for GoG players xd)
