### ISSUE TITLE
Items craftable in AE2 main net show up in subnet at random

### ISSUE THREAD

**Issue by BobGoldham** [GTNewHorizons/GT-New-Horizons-Modpack#13711]
### Your GTNH Discord Username

BobGoldham#1790

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I have a subnet (for platline) on my AE2 network.
This network has a drive and a few storage busses attached.
I expect to see items stored in that subnet and nothing else.

### The Reality

About 9/10 times when opening a terminal attached to the subnet, it works exactly as expected.
around 1/20-1/10 times, the following happens.

It also shows all craftable items from my mainnet:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/55559236/bccdd9ac-89bd-4336-acb5-569aa3039e80)

They are not craftable in the subnet, the subnet lacks a crafting CPU, any recipe patterns and the materials for most those recipes. When attempting to craft a 1x copper wire for example:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/55559236/489047aa-2ff2-413b-a65a-3ff95eb9853b)
(it shows no crafting CPUs)

Both networks have a working (not red/failed) controller on them, there is no direct connection between the networks other than through p2p tunnels and storage busses (of which any pointing from sub to main net are set to only insert).

This bug is reproducible with some consistency by  spam clicking the ae terminal in subnet until eventually the recipes show.
(It also occurs at random when NOT spam-clicking, but simply using the terminal as intended)

### Your Proposal

Make it so the subnet does not show items only craftable in main net

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BobGoldham** [comment]
(The easy "fix" here would be setting the terminal to show only stored, since the subnet has no autocrafting capabilities... Or just ignoring the "Craftable" items)

**Comment by Tommeh1** [comment]
Can confirm this to also exist back in both 2.3.0 and 2.3.2

**Comment by repo-alt** [comment]
Can you check if that is still reproduecable in https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/releases/download/rv3-beta-226-GTNH/appliedenergistics2-rv3-beta-226-GTNH.jar? This may be a p2p reset issue

**Comment by Tommeh1** [comment]
> Can you check if that is still reproduecable in https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/releases/download/rv3-beta-226-GTNH/appliedenergistics2-rv3-beta-226-GTNH.jar? This may be a p2p reset issue

My similar case is triggered with merely storage busses and interfaces connecting the systems to get items transferred, it uses no P2P.

**Comment by EnderProyects** [comment]
This has also happened to me with other modpacks, it usually happens when there is a loop in the sunset (at least my cases have been those)

**Comment by repo-alt** [comment]
@BobGoldham So, the only connection to the main network are the storage buses (on the interfaces)?

**Comment by Eranicus** [comment]
I also experienced this problem , was seeing craft recipes from my main network on a subnet terminal.

The problem was the followng: several cable pieces not chunkloaded, ones I chunkloaded them , the problem was gone.

**Comment by BobGoldham** [comment]
> @BobGoldham So, the only connection to the main network are the storage buses (on the interfaces)?

yes. The only connection between networks are interface<->storage bus.
