### ISSUE TITLE
Invetory and machine ownership loss due to UUID change when server updating

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#13722]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.3.4Beta

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Online mode uuid are directly collected from mojang and seems shall never change.

### The Reality

On updating the server from 2.3.2 (Java17, offline mode) to 2.3.4Beta (Java8), the online uuid changed for no reason.
I know that some launchers (HMCL, for example) allows to change the offline-mode uuid so that I could access my former invertory, but the forced online mode of 2.3.4 servers prohibited me from that.
In the end I connected the server owner to transfer my player save from old uuid to the new one, but the wireless EU network, machine ownership, FTBU chunkloading and some other things are all gone.

update: It was then found out that the former 2.3.2 server used the offline uuid generated from username, which is different with my online mode one.

### Your Proposal

find out what caused the uuid changing. If possible fix it, or add a way to prevent such situation.

### Final Checklist

- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
if the server allows for cracked minecraft versions, that's a risk and we aren't going to fix it, but if you are in the only legit case, well a fix is being made.

**Comment by chochem** [comment]
HMCL, so very much not legit
