### ISSUE TITLE
Cargo Rockets Not Launching

### ISSUE THREAD

**Issue by mnewbold01** [GTNewHorizons/GT-New-Horizons-Modpack#13728]
### Your GTNH Discord Username

drewdroid9

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I'm trying to set up a cargo rocket system to transport items to my miners on Mars. My launch pad frequencies are correctly linked (as they are highlighted green), my rocket is fueled and my launch controller is fully powered.

Once the rocket is full, the rocket should launch to it's destination automatically.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/122412127/dcc0187f-4b71-44fe-a2e8-0c825b409f16)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/122412127/d5163c06-cfaf-46ea-8a4f-92ad457cc15f)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/122412127/3a6c8069-64ac-46b6-8333-ba5000c912e9)

### The Reality

The rocket does not launch. I have never had the cargo rocket launch when testing with any of the launch conditions shown.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/122412127/b5f6dba3-f5e9-46e4-8cf5-74a667c7e8fe)

There is an option to manually launch through the rocket GUI. But as soon as I press 'Launch', The status changes to 'Not Enough Fuel', even though fuel is at 100% (Using CBD).

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/122412127/be1ef503-0e36-4365-90d3-57fd4ea934be)

### Your Proposal

The cargo rocket should launch from this lad to the pad at mars, both by manual launch through rocket GUI or auto launch from conditions set by launch controller. 

I have two speculations as to why this may be bugged.

1. Rocket fuel changes not recognizing CBD as a fuel for cargo rockets? I've tested all rocket fuels in creative and can't get it to launch, but maybe some changes through fuel restrictions have not been applied to cargo rockets?

2. The quest book states that a change was made to how cargo rockets work to reduce lag. Perhaps this may be affecting the launch?

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/122412127/a1c6c2c5-4f09-46d6-a753-7b7a5355efd0)

I know this is a pretty niche issue as nobody really uses cargo rockets but I'm trying to play without using any TP methods, and plus moving stuff with rockets is cool af. 

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/122412127/08990605-abaf-4e5d-b0f7-66e305abec48)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mnewbold01** [comment]
It sounds like that quest book change to make launches quicker with a launch controller was designed for normal 'people' rockets. Is it possible it wasn't tested on cargo rockets too?

If so, is it possible to disable this change through a config file?

Cheers guys

**Comment by chochem** [comment]
maybe related: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13249

the launch controller change goes back 3 years now, but I doubt many people use cargos.

**Comment by mnewbold01** [comment]
Tested it again on 2.3.4 to see if it would at least explode (reference to ticket #13249)  but I'm still getting the same 'Not Enough Fuel' Error.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/122412127/f38b7873-3672-40c7-8a06-5b2e48756e80)
