### ISSUE TITLE
Mini-sun block

### ISSUE THREAD

**Issue by Erizid** [GTNewHorizons/GT-New-Horizons-Modpack#13725]
### Your GTNH Discord Username

Bonesnap

### Your Pack Version

2.3.3

### Your Proposal

A Thaumcraft-craftable block that acts as a "sun" when placed above a solar panel so it thinks it can see the sky/keep working at night.

### Your Goal

Some fun extra uses for Solar Panels/Solar Boilers.

### Your Vision

Finding fun ways to make solar panels more interesting.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
I think it's a good idea personally, might not be that hard to implement?
