### ISSUE TITLE
quest typo

### ISSUE THREAD

**Issue by csapka108** [GTNewHorizons/GT-New-Horizons-Modpack#13726]
### Your GTNH Discord Username

Csapka

### Your Pack Version

2.3.0

### Your Server

private

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

in better questing? quest:
y'all

### The Reality

ya'll

### Your Proposal

ya'll -> y'all 
*poof* magic

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you forgot to write which quest

**Comment by csapka108** [comment]
I didn't, it's the "Better Questing?", I just didn't use "", sry

**Comment by chochem** [comment]
hahaha. I expected something after the ":".

anyway looks like that is already fixed in here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/13416 which explains why I couldnt find anything when searching either.

**Comment by csapka108** [comment]
aight ^^
