### ISSUE TITLE
Map generation bug

### ISSUE THREAD

**Issue by MakinToge** [GTNewHorizons/GT-New-Horizons-Modpack#13729]
### Your GTNH Discord Username

makintoge

### Your Pack Version

2.3.4

### Your Server

Zeta

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

Having seamless world terrain

### The Reality

I encountered a giant vliff following chunks
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12732004/39b3a943-cd77-4330-b72d-933cb9c7b7b1)

### Your Proposal

Don't know

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
did you come from 2.2.0.0?

**Comment by Pxx500** [comment]
> did you come from 2.2.0.0?

It's zeta so probably happened between versions

**Comment by chochem** [comment]
so just good old 2.2.0.0 or maybe a 2.2.0.0RC if its zeta
