### ISSUE TITLE
Monomethylhydrazine cells can't be used in machines

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#13731]
### Your GTNH Discord Username

combuster

### Your Pack Version

2.3.0

### Your Server

Delta

### Java Version

Java 17

### Type of Server

Thermos

### Your Expectation

I was making purple rocket fuel (monomethyl hydrazine + nitric acid), and following the questline along to and got the needed GT++ monomethylhydrazine cells for the quest. However, when putting them back in the input hatch it didn't work

### The Reality

1: The input hatch did not extract the fluids from the cells
2: Clicking into the fluid slot of the input hatch converts the gray version to the orange version of monomethyl hydrazine, which does not trigger the recipe.
3: Distilling the orange flavour gives back the gray version which then turn the regular cells back into GT++ cells, perpetuating the cycle.

As a workaround I found that you can use the distillery to get the gray version back, and then click the output slot with volumetric flasks. These do work when put in the input hatch as cells to leave the correct gray version as input.

### Your Proposal

It's probably best to get rid of the GT++ fluid and GT++ cells altogether in all recipes and use only the orange flavour of monomethyl hydrazine.

As a quick fix, accepting GT++ cells in input hatches may also help.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I have cleaned up most of these duplicate fluids since 2.3.0 (hydrazine, formaldehyde, hydrogenperoxide).
but not this one it seems. will have a look.
