### ISSUE TITLE
New Lenses for Goggles of Revealing

### ISSUE THREAD

**Issue by schneid3306** [GTNewHorizons/GT-New-Horizons-Modpack#13735]
### Your GTNH Discord Username

schneid3306

### Your Pack Version

2.3.0

### Your Proposal

I think that the Lens feature from Thaumic Horizons could be expanded to be more utilitarian. My initial thought was to add three lenses which mimic the functionality of the following items:

- The Spectacles from Forestry
- The Monocle from Bibliocraft
- The Manaseer Monocle from Botania

#### The Spectacles from Forestry

The Spectacles highlight pollinated leaf blocks so the player knows what leaves to break when breeding Forestry trees. Without them, pollinated and un-pollinated leaves look the same.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/101597354/521ffaf4-928a-4515-b868-f681320fb12a)

Ignore the dashed pattern around the leaf, that is a texture pack I made for my own use. The standard pollinated indicator would be the leaf going from the darker green to the lighter green. The changes in leaf blocks are similar, but not completely identical for other trees. I don't know the back end mechanics there.

The Spectacles are equipped in the helmet slot.

Edit: Pao on discord pointed out that Darksteel Armor (Dark Helm) from EIO has a similar functionality via Naturalist's Eye. Just wanted to note that if the information is useful.

#### The Monocle from Bibliocraft

The Monocle from Bibliocraft shows information about the printing press, typesetting table, armor stand, shelf, and possibly more Bibliocraft blocks that is unable to be seen by an un-monocle'd player.
![Printing Press](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/101597354/7cb0f4f3-16aa-46be-b9cb-bfd3297edd5b)
![Typesetting Table](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/101597354/852e35fa-3d5d-4b3a-8639-3fcb362e24a7)
![Armor Stand](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/101597354/a5c1185b-a7d8-4b67-94e0-f96c5bffa9fb)
![Shelf](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/101597354/1a552223-8f76-4eef-9543-186468460ae3)

The Monocle is equipped in the helmet slot. I believe the Reading Glasses also provide the same functionality as the Monocle.

#### The Manaseer Monocle from Botania

The Manaseer Monocle allows you to see the functional radius of the flower that you are looking at. 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/101597354/1772e995-4b56-4fa2-a543-180a4318ae5d)

In addition, it shows the player all nearby Mana Bursts.

According to the Lexica Botania, it also shows info about vanilla redstone pieces, but I primarily use it for the flower and mana information.

Oddly, the Manaseer Monocle can only be equipped in the Amulet bauble slot.

### Your Goal

I think Lenses are under-utilized/easily ignored and this would be a cool way to add some additional functionality to various goggles and clean out inventory clutter at the same time.

### Your Vision

Lenses are much easier to swap out than your helmet slot. This would increase functionality of existing armor and would be a huge quality of life improvement.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
Could you describe what these lenses do?

**Comment by schneid3306** [comment]
@Alastors I updated the body of the ticket to include what the various items do along with some screenshots. I hope that is what you are looking for.

**Comment by Rika-TH** [comment]
I just mentioned this in a closed issue how combining the two issues would be cool (and in turn would like this), bad bot

**Comment by Alastors** [comment]
I mean now that we have license to this mod, I'll consider it Lmfaoo

**Comment by Rika-TH** [comment]
Just gotta have someone supply the textures (not me) :smile:

**Comment by Alastors** [comment]
I will do this if someone provides textures btw

**Comment by Ethryan** [comment]
I can probably whip some textures up for you this weekend, @Alastors

**Comment by Alastors** [comment]
Aight just make sure they stay in general style of the others and it'll be grand. 

If you don't mind though, make a few taint lenses as well, could be a great moment to do some integration with the new taint content coming up.

**Comment by EnderProyects** [comment]
If you need ideas for the crafts, some time agó I saw this issue and created some ones ( based on the thematic of each lens)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/d9542b65-b3d3-412e-bab0-27dc6a421aa0)
Spectacles - botania monocle - Normal monocle

**Comment by Ethryan** [comment]
Anytime @Alastors , anytime.
