### ISSUE TITLE
Wireless Energy Hatch causes Compact Fusion to power loss

### ISSUE THREAD

**Issue by harrynull** [GTNewHorizons/GT-New-Horizons-Modpack#13739]
### Your GTNH Discord Username

harrynull#9630

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 19

### Type of Server

None

### Your Expectation

UV Wireless Energy Hatches act as 2A UV energy hatch.

### The Reality

When I replace UV energy hatch to wireless UV energy hatch, the compact fusion losses power after a while (a couple minutes).

For example, doing titanium plasma recipe with 5 (or even more) wireless uv energy hatch with mark 3 compact fusion.

The recipe requires 5111808 EU/t which is 4.875 energy hatch with 2A each.

### Your Proposal

make it work like normal energy hatch.
e.g. increasing internal capacity (currently just 2x throughput)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AtomicGrog** [comment]
I'm possibly wrong but not sure your eu/t is right for titanium?

Mk3 compact gives a 192 parallel on recipes which require 160m eu (or less )to start and titanium is 100m.

So... titanium plasma uses 49,152 eu/tic * 192 = 9,437,184 eu/t

**Comment by harrynull** [comment]
Thanks for pointing that out. Yea you are right, a compact mk3 running at full parallel will require a lot more energy. Even higher than what you've calculated actually because there is overclocking. It still confuses me why it will work after I swap the wireless ones to normal ones.

**Comment by harrynull** [comment]
In fact, even with 32 UV energy hatch at 2A each, it would require `9437184*4/524288/2=36` energy hatches, so it's impossible to get full parallel this way. Might require better energy hatches (laser, 16As?)

**Comment by TheEpicGamer274** [comment]
use the 4A uv energy hatches
wireless works even better, compact mk3 will only accept uhv power per energy hatch and so 4A is the best

**Comment by kstvr32** [comment]
> In fact, even with 32 UV energy hatch at 2A each, it would require `9437184*4/524288/2=36` energy hatches, so it's impossible to get full parallel this way. Might require better energy hatches (laser, 16As?)

I think this math is wrong. Fusion overclocks 2/2 not 4/4. Therefore it would only require 18 UV energy hatches.

**Comment by harrynull** [comment]
@kstvr32 It overclocks twice because overclocking is depending on the start energy rather than eu/t

**Comment by kstvr32** [comment]
@harrynull 

I’m not in game right now, but I could’ve sworn titanium is a t2 plasma and will only OC once in a compact mk3.

**Comment by TheEpicGamer274** [comment]
fusion ocs are a lot different than normal overclocks, you can normally get double ocs if it has enough more starting power for enough oc, it sometimes is a bit buggy I find though.

**Comment by harrynull** [comment]
https://github.com/GTNewHorizons/GoodGenerator/blob/b6c69d71f9b85603621e599586c72aaee7c8b5fe/src/main/java/goodgenerator/blocks/tileEntity/base/LargeFusionComputer.java#L416

Fusion OC is purely based on start energy as far as I can tell. And titanium is T2 plasma because of its EU/t requirement rather than start energy. So I guess it's treated as T1 plasma for OC and parallel purpose

**Comment by arnoleo** [comment]
I still encounter this problem. When using a tricorder on energy hatches, I can see the buffer decreasing to 0 on them, starting with the wireless energy hatches the most far from the controller. When all the buffer are emptied, the controller failed due to power loss. It is as if the wireless hatch buffer is charged only at recipe switches.

It is pretty inconvenient at high level when crafting tons of a single plasma, Uranium 238 in my case, on a Compact Fusion MKV reactor with 32 UEV Wireless Energy Hatches

**Comment by madmacf** [comment]
Same problem as arnoleo.
UEV wireless x 32 on compact fusion mk 5
It runs dry of energy.
Wireless hatches seem useless right now. They don't work fast enough.

**Comment by arnoleo** [comment]
The problem does not occur if you use Wireless UIV Hatches. It can be a solution if you can afford it but I think that if a recipe cannot be processed with UEV hatches, it would be better if it were specified
