### ISSUE TITLE
Vanilla fog does not adjust to render distance changes.

### ISSUE THREAD

**Issue by compcoding** [GTNewHorizons/GT-New-Horizons-Modpack#13733]
### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Fog only covers the edge of loaded chunks around me.

### The Reality

Fog renders at a constant distance(seems like 8 chunks, not sure). When having render distance in client and server.properties set to more than 8 chunks fog covers loaded chunks. **Basically i can't play with render distance more than 8 chunks.**
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/136914889/1d25bd3d-e0b2-4247-a3b4-88854ba7758f)
P.S. I have fresh installment of server and client with no modifications except "view-distance" setting in server.properties. This bug does not appear in single player.

### Your Proposal

Vanilla fog should adjust to render distance and not be rendered at a constant distance from player.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fog should always be 25% of the renderdistance iirc

**Comment by compcoding** [comment]
This issue does not appear in singleplayer. Also im quite sure it does not appear in java 8 version of server and modpack(needs testing).

**Comment by compcoding** [comment]
@chochem Any updates on this issue? Seems like players still encounter this problem while playing multiplayer.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/136914889/0dfdc9a1-707e-46e2-acb2-b92d84750267)
_(image taken from official discord)_
I've done some testing, this issue also appears on Java 8 version.

**Comment by compcoding** [comment]
I can assume that this is a problem with the server-side code, because of this bug only works in multiplayer.
Maybe you can assign someone to this issue?
