### ISSUE TITLE
Ender Fluid Conduit Speed

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#13736]
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.3.4

### Your Proposal

Allow dual interfaces to push fluids into ender conduits faster.

### Your Goal

Insertion rate for fluids from interfaces is painfully slow. Interface is capable of pushing only about 1 recipe/s if you use fluid conduit (conduit tier doesn't affect it in any significant way) making systems like this unusable
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29033773/abc67068-9841-4402-a700-2c9150e904f4)
Your only choice to completely avoid fluid conduits and build systems like this
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29033773/da841178-b171-4d66-b984-f35de5e93992)

### Your Vision

Make usage of dual interfaces reasonable without intermediate steps like transvectors or decoders by increasing/removing speed limitation on insertion attempts from interfaces

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ydrec** [comment]
Its a way in which dual interface logic interacts with artificial conduit limits.

Duals go into cooldown if they can't output the whole size of fluid from pattern to prevent them causing lag spikes, and if fluid conduits thoughtput is lower or you attempt to output multiple fluids conduits would reject that and cause interface to bottleneck.

Use bigger conduits, use reasonable sized patterns, use fluid p2p, use multiple fluid conduit connections per same dual that allows multiple fluids to be pushed out in same tick

**Comment by Florexiz** [comment]
I use melodic conduits for pretty much non-existent fluid flow that inserted into multi input hatch. Its not fluid limit from transfer rate, nor from fluid slot capacity
