### ISSUE TITLE
Change LSC wireless balance amount / frequency

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#13732]
### Your GTNH Discord Username

hucking

### Your Pack Version

2.3.4

### Your Proposal

I suggest a way of changing the amount of EU the LSC keeps when wireless is enabled (or change the frequency with which it updates)

### Your Goal

Right now if you are using more than 10G EU/t with your LSC it will shut off since it can only update every 5 minutes and the it will only give your LSC power if it is below 60TEU. I have already ran into this issue because I am supplying my DTPF with 8.5GEU/t and the rest of my infra is around 6+ GEU/t

### Your Vision

Obviously one solution to this would be to make more LSCs or have 1 (or more) LSC (with wireless) supply another LSC (without wireless) with lasers. But this seems a bit janky and I think a better solution would be to be able to change the amount the LSC keeps or the frequency with which it updates.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
> it will only give your LSC power if it is below 60TEU
That is only true for UHV capacitor. There are higher tier capacitors, which allow higher throughput.

**Comment by hucking** [comment]
ah my bad it even says it on the tooltip sorry
