### ISSUE TITLE
Flippers Can't get it from village blacksmith fetch

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/GT-New-Horizons-Modpack#13742]
### Your GTNH Discord Username

Admin_XiaoMai

### Your Pack Version

2.3.4

### Your Proposal

![QQ图片20230618220218](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/7ef624fe-2c82-4ff0-973c-48195fcd72f1)
![QQ图片20230618220329](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/ba1f9312-4faa-496f-84b9-a7b6482e1022)
OverWrold and SpiritWorld 
10000*10000
Can't get it from village blacksmith fetch

### Your Goal

![QQ图片20230618221126](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/b9637a28-526d-4719-8072-713022780a52)
![QQ图片20230618221232](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/ebb0a085-db55-498d-af02-ab1239701d08)

### Your Vision

Coin exchange
Or add recipes
Or adjust the weights

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AdminXiaoMai** [comment]
![QQ图片20230618220218](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/3e035427-d726-45b0-9a0d-77e2a4e9b5ad)
![QQ图片20230618220329](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/5dc04774-6eb3-4bc8-b1e4-fdff1e7d7d85)

**Comment by chochem** [comment]
I spawned these chests in creative and got flippers so its not broken. I also went to a village and found a chest that used that loottable. just meaning I think its not broken, just maybe a touch to rare :P 
will increase the chance a bit.

**Comment by AdminXiaoMai** [comment]
I only found wadingboots it in this 1000*1000

**Comment by AdminXiaoMai** [comment]
3 pcs

**Comment by AdminXiaoMai** [comment]
Not all villages have blacksmith shops
