### ISSUE TITLE
Advanced memory card select wrong p2p

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#13740]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.3.2

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

look at p2p, r click with memory card, this p2p selected

### The Reality

a look at 
<img width="365" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/4caa6438-6ead-44cb-bd35-736c3ffd32aa">
after r click with memory card
<img width="653" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/eba9b771-eda7-41d8-930a-dd818d804ead">
and for some reason was selected p2p somewhere far away
<img width="390" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/0587e30f-c93e-41df-8de6-7cdbaa553cc6">

### Your Proposal

fix this 
This happens only for 1 p2p, not chain 
i have more than 100 p2p and found only 2 with this problem 
i restart server and it fix current p2p, but broke another one
I recently replaced ME controller for whole system, old one used only for channel transport and not connected to broke p2p
i use betterp2p-1.1.14
Replacing p2p not change anything

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
Has this fixed itself? Let me know the (x,y,z,face direction,dim) of both p2p tunnels.
The only way this can happen is if the hashes of the two different P2P tunnels match, which is rather unlikely (but it is concerning that it has happened, so a rewrite might be needed)

**Comment by lordIcocain** [comment]
first (i click on it) x:18 y:128 z:-14, facing: top, dim: 180
second (wrong selected) x:18 y:128 z:13, facing: top, dim: 180

**Comment by lordIcocain** [comment]
Until i restart server it select wrong, but after restart another p2p will broken. 
mb it also use random seed that i can somehow to know and tell you?
