### ISSUE TITLE
Slate cannot be made

### ISSUE THREAD

**Issue by h60299** [GTNewHorizons/GT-New-Horizons-Modpack#13743]
### Your Pack Version

2.3.3

### Your Server

sp

### Java Version

Java 8

### Type of Server

None

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/136983708/9c51ad50-9375-4caa-afb9-9a14d06860c3)

The production of stone buildings wands requires slabstone，but the slate cannot be made.

### The Reality

The production of stone buildings wands requires slabstone，but the slatestone cannot be made.

### Your Proposal

Slabsstone can be made.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Fixed in 2.3.4
