### ISSUE TITLE
Molecular assembler not working.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/GT-New-Horizons-Modpack#13750]
### Your GTNH Discord Username

Pilad

### Your Pack Version

2.3.4

### Your Server

Single game

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Assemble a simple network: controller, cable, assembler.
Indicates that the Molecular assembler is offline and not running.
Mods update to: ae2fc-1.1.22-gtnh, appliedenergistics2-rv3-beta-228-GTNH

### The Reality

![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/d9fcac54-ce15-4862-97d1-928fe509f9c1)

### Your Proposal

Fix please.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Runakai1** [comment]
Does this happen with the neutronium Energy cell only or with every energy source

**Comment by Pilad** [comment]
If you restart the game or log off/on, it turns on
![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/00e9b432-ea4b-4c8f-a44d-4ccff327797e)
If the Molecular assembler is broken and returned back, then it is disabled again.
![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/110ab90b-1695-4d80-8dcc-ad7d2cce3a1c)

**Comment by Pilad** [comment]
Offline
![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/dda0e540-1d37-455a-a5b5-b071ef20e4d3)
Online
![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/99e73c9d-fee0-4183-8036-18e6cc38eb81)
![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/3696f522-3f86-45fb-b09f-55b2a18dc2e9)

**Comment by Pilad** [comment]
![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/616707f4-c137-4d0f-be29-29090b2ea890)

**Comment by wlhlm** [comment]
@Pilad 

> This bug is on version 228.

Just to make sure--if you downgrade to 227, the problem is fixed?

**Comment by Pilad** [comment]
> @Pilad 
> 
> > This bug is on version 228.
> 
> Just to make sure--if you downgrade to 227, the problem is fixed?

225 work fine.

**Comment by Pilad** [comment]
I returned this line back and so it began to work.
src/main/java/appeng/me/cache/PathGridCache.java
![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/b78a9463-f73d-4928-aed0-3b0a092205c0)

**Comment by Pilad** [comment]
The problem is with this pull request.
After it, all builds are broken when working with the MA.
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/commit/edf5dd44fb402d4ffd2d388573f6ed8f844d5918#diff-d18c8cb705e28407a390ba8c707f7e9505f651376b046db2494c09a8a60424eeR371
