### ISSUE TITLE
Significant FPS Drop from Single Block Steam Turbines Not fed Consistent Steam

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#13755]
### Your Pack Version

2.3.4 but also from 2.3.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

No FPS Lag when moving energy through a battery buffer into other machines or transformers.

### The Reality

All LV and MV battery buffers (I assume higher voltage tiers as well), 1A to 16A with batteries in 1 or all 16 slots, it does not matter, running into both GregTech original transformers and the High Amp versions, as well as into other battery buffers and cable or wire lines moving power, their is a significant amount of FPS lag every time the buffer ticks IF, and this is the important part, IF the energy in the buffer is empty. How I feed power into the buffer does not matter, it can be from another buffer, from generators directly touching it, or into wires/cables and then into the buffer.

So, I have 16 Amp LV buffer going into a High Amp LV transformer, into a whatever, but, I only have 4 LV Steam Turbines powering it. So, of course, the buffer will eventually run out of stored power and input and output are both 128 (4A LV) after all batteries have emptied. When this happens, consistently until the batteries have a buffer in them again, they FPS reduces by around 10 to 25% (120fps to 85 lowest, with only 1 buffer). I would assume this had something to do with a machines animation, normally, but, buffers do not have animations, so I can not think about why this is happening.

I have tried every version of the core and gt from the pack version to the most current versions, and it also existed in 2.3.0 when I first started to play the pack.

### Your Proposal

Investigate why drawing power from an empty battery buffer with batteries inside causes FPS lag, and fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
hmm. doesnt happen for me or maybe I dont really understand what you mean.

You could try the pie chart in shift+F3 and then subselect with number keys, to find out what is causing it.

**Comment by desagas** [comment]
Change that, the FPS drop is coming from the steam turbines, low voltage (I have not tried the higher tiers) being fed with steam, but not enough steam to produce a full amp of power, and then passing that power to anything else. So, the animation halts very briefly and then starts again, and it will do this twice a second, the same rate I believe that the turbine ticks? There is no way for me to visually show this right now, as the line graph in future versions is not in this one, but, there is a stutter very visible.

My set up is this: 8 basic steam turbines all going into a high amp low voltage transformer ... of the 8 turbines, 2 are being fed consistently, and 6 are being feed equally the left overs, equally spread. It is the starting and stopping of this animation that is noticed, although it is not clear whether this is a symptom or the cause, but is related. Also, I am on an very buffed machine, so this will not be related to my machine stats. 380fps average in gtnh without restricting to my monitors refresh rate, but these 6 ticking turbines drop my max fps to between 85 and 105. So, I was wrong when I said it reduced it by about 15%, it drops it by about 66%.

And, yes, I know in game I can better design my fluid distribution to stop this from happening, but that is but a bandaid for a broken arm.

**Comment by desagas** [comment]
I tried going through the F# Shift folders, but I could not pin point one, it confused me a lot.

**Comment by desagas** [comment]
I believe a change in the code to not start and stop the animation would help this, changing it to start and continue for a short time, and then check if it should continue if conditions are still correct. Maybe this is already the case, if so, maybe that delay time could be increased and the animation time also increased?
