### ISSUE TITLE
Biomes O´Plenty flowers recipes 

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#13753]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.3.4

### Your Proposal

Add botania alchemy recipes for all the biomes flowers since they are used in some recipes ( a chain recipes like the vanilla ones)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/168aaf16-c63a-40fd-91ea-244f52defeb1)
Also add a way to start the cycle by adding a recipe for the clovers
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/ba901f15-9773-4017-947f-cf6c90863768)

### Your Goal

add some qol and botania integration

### Your Vision

Players will have a new recipes for some flowers instead of having to search for them all over the world

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
Clover starter:
        //BOP clover starter
        addOreDictRecipe(new ItemStack((Item) Item.itemRegistry.getObject("BiomesOPlenty:flowers"),4,1),
                "SBS","BFB","SBS",
                'S', "listAllseed",
                'B', "dustBone",
                'F', new ItemStack(ModItems.fertilizer)
                );
               
Chain recipes:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/3ce8d36e-3b7b-45a7-8b39-9058135e7c6f)

**Comment by EnderProyects** [comment]
@combusterf or @Alastors  I have a pr for this ready, if I get an aproval I can pr it:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/8d7a39ab-e1d8-4c15-a83f-0571d7f78634)

**Comment by Alastors** [comment]
yeah I'm fine with this, they're just cosmetic anyway

**Comment by wlhlm** [comment]
> yeah I'm fine with this, they're just cosmetic anyway

Not quite. The Lavender is used in Rainbow Curry and thus in the Healing Axe quest. Currently, it requires the player to go exploring for a specific biome (or bees). So this should be considered.

Similarly, the Goldenrod flower is used for the Daybloom. Currently, you to go looking for a Prairie biome (or do bees). Probably not a big deal, but I just wanted to note that.

**Comment by EnderProyects** [comment]
at the time you get Alchemy Catalyst in botania, most player would have healing axe and also you need the daybloom xd ( since it needs mana)

**Comment by EnderProyects** [comment]
Also the recipes that makes flowers that can be used to stract resources I make them harder ( double the mana amount needed)

**Comment by combusterf** [comment]
The current setup requires some level of exploration as well as adaptation - if the corresponding base flower is not present in your current biome then it might be better to look at different mana generation patterns.

This is a rather braindead as well as a rather unfair method of bypassing all these challenges. If you start with the wrong base flower you have to go through many cycles of mana usage to end up at the desired species.

Also, penalty points for sneaking a bunch of other things into the merge request.

**Comment by Alastors** [comment]
> BOP flowers GTNewHorizons/Botanic-horizons#23

I am going to point out bees already generate all these flowers for free, but I will take a look at those other sneaked in features

**Comment by Alastors** [comment]
but I do agree, it is sort of a braindead way to do it, even if it is consistent to base botania

**Comment by EnderProyects** [comment]
> The current setup requires some level of exploration as well as adaptation - if the corresponding base flower is not present in your current biome then it might be better to look at different mana generation patterns.
> 
> This is a rather braindead as well as a rather unfair method of bypassing all these challenges. If you start with the wrong base flower you have to go through many cycles of mana usage to end up at the desired species.
> 
> Also, penalty points for sneaking a bunch of other things into the merge request.

base botania also pass by all the flowers when you need one, here instead of passing by 15 you pass by 24, its not that bad, also in the pr I didnt sneak anything, in the description I comented that I also place a Vine and a mini cactus

**Comment by combusterf** [comment]
> I am going to point out bees already generate all these flowers for free

You need to get into bees, set up apiaries with enough grass space and patience. It requires actual effort advancing into other mods instead of just reusing your first daybloom for the purpose

**Comment by Alastors** [comment]
> > I am going to point out bees already generate all these flowers for free
> 
> You need to get into bees, set up apiaries with enough grass space and patience. It requires actual effort advancing into other mods instead of just reusing your first daybloom for the purpose

it doesn't actually, you can get apiaries from villages

**Comment by combusterf** [comment]
And by that time you're already exploring and able to pick up the flowers in question :shrug:

**Comment by Alastors** [comment]
> And by that time you're already exploring and able to pick up the flowers in question 🤷

I mean not really? You do have a point but it's not like using bees is any less braindead than this tbh

**Comment by combusterf** [comment]
Counterproposals:

- Add BoP flowers to the coins tab. This is very much in line with how silverwoods and all the other exploration stuff works, and those trees are even mandatory for Thaumcraft stuff whereas you can progress with one of a few options in Botania.

- Add conjuration recipes so you can turn one flower into many clones. This is also late enough that you don't get the daybloom spam which the flower scarcity discourages in general.

**Comment by LazyFleshWasTaken** [comment]
Hi! This sounds like a good idea. Would you consider it again?

**Comment by EnderProyects** [comment]
There is already a closed pr about this

**Comment by LazyFleshWasTaken** [comment]
Yea, I saw it. And the rules for requesting a change says to check if it's already been made, and to comment to reopen.

**Comment by EnderProyects** [comment]
Im not going to try to reopen this, but since there are flowers that are not generated by bees or any kind, only by exploring, shouldnt be a way to obtain this past midgame? ( I would like to get a renovable way to get BoP Burning Blossom, Eyebulb, Miner's Delight, and Root)
