### ISSUE TITLE
Add Mode Switching Buttons to Multiblocks that have multiple machine modes

### ISSUE THREAD

**Issue by SpaceMinere** [GTNewHorizons/GT-New-Horizons-Modpack#13763]
### Your Pack Version

2.3.3

### Your Proposal

Add buttons to the controller GUI for certain multiblocks (i.e. large processing factory, wash plant, etc) to change the machine's working mode. For example, the LPF would have GUI buttons to switch between metal, liquid, and misc modes. The wash plant would have buttons to switch between simple, regular, and chem bath modes. ETC.

### Your Goal

Using a screwdriver is a tedious way to switch modes in these machines. Many previously screwdriver-only functionalities (covers namely) have been given GUIs, so I don't think this feature is out-of-place.

### Your Vision

The large processing factory is a powerful multi, but having to use a screwdriver to switch between modes is tedious. The same goes for other multis with multiple machine modes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Remove stale
