### ISSUE TITLE
Machine Controller Not Saving after Safe Mode triggered

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#13766]
### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Machine controller settings should be able to be changed and saved at all times, regardless of redstone or disabled state.

### The Reality

I apologize, I was trying to find the commits that were merged to solve this issue, and comment on them directly, but I can not find them anymore, after searching, but, the machine controllers are not entirely fixed. They will save when freshly installed, and the settings can be changed and saved after this. This ability, however, stops once the controller automatically disables everything due to a safe mode issue in the machine it is attached to: out of power, etc. Once the controller is flipped off like this, it can no longer be changed back and saved. The only way I have found to save any changes again is to remove and replace it, and save the settings then, or very rarely, something about applying strong redstone and removing it will allow changes to be saved again. Perhaps it is that changes won't save when redstone is actively touching it? I am not too sure.

I am using GTCore 2.1.60, GT 5.09.43.93, and MUI 1.1.12

### Your Proposal

Investigate and fix, again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Cannot reproduce. Do you have consistent way to reproduce? Which setting are not saved?

**Comment by desagas** [comment]
No setting will save. As soon as the breaker breaks, as in, the machine fails, nothing will save afterwards unless I remove the controller and place it again. I will post photos of my setup tomorrow.

**Comment by desagas** [comment]
This may have been a one time break and replace non-repeatable java error or something, I myself am now unable to reproduce it. I will let you know if it happens again.
