### ISSUE TITLE
Advanced Genetics/Genetics Reborn

### ISSUE THREAD

**Issue by AltyMan** [GTNewHorizons/GT-New-Horizons-Modpack#13767]
### Your GTNH Discord Username

Alty#0661

### Your Pack Version

2.3.0

### Mod Name

Advanced Genetics/Genetics Reborn

### The Mod to Add

Mob genetics you can genetically extract and then insert into your body that provide you ability buffs (but also negatives like viruses during certain conditions in Genetics Reborn).

### Your Reason

This mod would be very useful for QOL and overall casual enjoyment. The QOL would come with some of the abilities, ex. water breathing, poison/wither protection, keep inventory (which I personally think should be available at some point in progression, but regardless any of these can all be turned off), and other neat features. This mod is complex in nature, which gives some meaning to completing it for its rewards and provide some enjoyment from progressing in a different mod from GregTech.

### Preliminary Investigation

I have not tried adding this mod to my pack, but I have checked and both the original Advanced Genetics and Genetics Reborn have licensing rules that allow for modifications to the code for the modpack. I thought since both the licensing isn’t a problem and the mod is very interesting, this mod can be properly gate-kept to a specific power tier (I would say somewhere in EV, or even HV if there’s proper barriers between the advanced/more powerful abilities), plus certain requirements (like RF power) can be adapted and fulfilled using GTNH materials.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by chochem** [comment]
neither seems to be a 1.7.10 mod

**Comment by AltyMan** [comment]
Advanced Genetics is 1.7.10, but yea I realize now Genetics Reborn is not which kinda sucks. For Advanced Genetics you probably saw that one mod on CurseForge with like 8000 downloads, here's the actual one: ag.teamdna.de

**Comment by chochem** [comment]
> You are not allowed to sell TeamDNA mods or earn money with them in any way.
You are not allowed to copy or reverse engineer any of the code that was released by TeamDNA.
You are not allowed to upload instances of TeamDNA mods without a written permission of the author.
You are allowed to create modpacks with TeamDNA mods.

**Comment by EnderProyects** [comment]
Just saying that if you whant keep inventory there is a botania item that is appliecable to almost all items and act like that (Resolute Ivy)

**Comment by AltyMan** [comment]
Ah crap, yea I realize now Genetics Reborn used original code and took inspiration, oh well
