### ISSUE TITLE
Rocket sometimes throws me out, which results in me losing the rocket

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#13779]
### Your GTNH Discord Username

Keyla#3300

### Your Pack Version

2.3.0

### Your Server

other server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

Trying to fly in the space

### The Reality

rocket had full fuel, it threw me out while the countdown was ticking. I got back inside, and it started flying. Threw me out second time mid-air, flew away without me. I have my hands off keyboard/mouse while in a rocket. Happend at least three times, happened once with low tier rocket, once with t5 and once with t6. I need help understanding why it is happening for it not to happen again.

### Your Proposal

help me :(

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
something wrong with your keyboard? maybe rebind/unbind that key to be sure

**Comment by CatsLeftEar** [comment]
> something wrong with your keyboard? maybe rebind/unbind that key to be sure

![bilde](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/67397297/d3554cb7-9e31-48e3-8907-6031ba3afff5)
seems like other people have had this problem before

**Comment by CatsLeftEar** [comment]
We both are from the same server though, maybe this bug for some reason happens only on our server? Still have no idea about what can be the reason

**Comment by chochem** [comment]
I mean that guy couldnt even decide on what actually happened. first they never were in the rocket, then they were, then the launchpad poofed, then it was on fire. was all over the place.
but if its on the same server I guess its fair to say your server has some problem.

**Comment by zgggz** [comment]
2.4.0 i have the same bug at another server
