### ISSUE TITLE
Eye of Harmony recipe EU cost decreases with overclock

### ISSUE THREAD

**Issue by Gofer2x** [GTNewHorizons/GT-New-Horizons-Modpack#13770]
### Your GTNH Discord Username

Gofer#5776

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 19

### Type of Server

None

### Your Expectation

I was writing a little EOH simulator (casings, tiers, etc) for myself using its code and noticed an oddity. With the [current recipe cost formula](https://github.com/GTNewHorizons/TecTech/blob/master/src/main/java/com/github/technus/tectech/thing/metaTileEntity/multi/GT_MetaTileEntity_EM_EyeOfHarmony.java#L1142), the recipe cost increases once then actually decreases as overclock increases.

### The Reality

Here are my findings in a spreadsheet. All lowest tier casings and the T0 recipe was used, btw.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45763255/c38a75ae-fc6c-4838-8d93-1deba2faffc4)
I tested it in-game, and indeed:
(wireless EU was reset between each attempt)
No OC
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45763255/e262f253-b25c-47a0-89ab-44a64830d4a9)
OC 1
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45763255/022d9508-a94c-4f52-ab74-88c8825c1b6a)
OC 2
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45763255/175f532a-abce-4b1e-a95c-c26784258e22)
OC 3
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45763255/bccc55ec-f97b-46db-b094-67ac5ecddc0a)
I think the problem in the formula is the second line, the `* pow(0.77, currentCircuitMultiplier)`. When I remove it, I get more reasonable? numbers from my simulator.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45763255/bdcd137f-df3e-4714-92e1-c67495c6ecc8)
Do note though that the output also increases then decreases, and that code also has the `pow(.077, currentCircuitMultiplier)`. So maybe also look into that?

### Your Proposal

So uh yes, fix pls I guess? Unless decreasing recipe time *and* EU cost with OC going up is an intended feature i guess lol.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GDCloudstrike** [comment]
This may seem weird at first but is intentional, as the EOH does not consume power constantly like a regular machine would, so the eu/t increases when recipe time decreases. If both recipe time decreases and EU per recipe increases, you end up with ludicrously high eu/t values, which used to be the case and also was the reason why the new formula got implemented.

The old formula was the usual 4x power, half recipe time overclock.

You can see a comparison of the eu/t values of the current and the old formula here: https://www.desmos.com/calculator/46gizo08do
