### ISSUE TITLE
Pristines Turning to Ignobles in Alveary Even Below 16x

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#13771]
### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

The wiki math should add up, and the 16x rule should apply, but it does not. The wiki claims that any bee speed with 2 diamond tubes in 1 stimulator and 1 diamond tube in another will never cause your pristine to turn ignoble, but this is not true. The wiki says that pristines will never change to ignobles in alvearies unless you go over this 16x mark, and that this is true for every speed of production.

### The Reality

There is a 100% chance in a lifespan that a pristine will turn ignoble with no other genetic decay frames or stimulators or mutators, other than a single stimulator with 2 diamond tubes, or 9.?x production chance, which is far below the 16x described. I have a slowest bee with a short life span, and it always turns from pristine to ignoble, 100% of the time. This should not be happening according to the quests and the wiki.

This tells me that 1 of 2 things is true: the quests and wiki are incorrect, not corrected after a change in code, or the alveary code is bugged, which always causes production multiplies via alveary stimulators to change a pristine to ignoble, regardless of how high the multiplier is. I assume this may have something to do with the 10x initial by using the alveary, which means at the very most, you can only every use a single diamond tube, which will make it 15x? Maybe I am wrong, but either way, it is not working even close to as the wiki or quests describe.

### Your Proposal

Either fix the code to match the quests and wiki, or update the wiki and quests to match the code.

This only seems to happen with the stimulators, for me, and I have not seen it happen with any frames, not yet, at least.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
I tried looking into the code of both forestry and binnie, and found where it says getProductionModifier > 16 to determine isOverWorked, but since other frames work fine from forestry, without causing these problems, I assumed it was a calculation error somewhere on Binnie's side within the code of for stimulator. I found in the code where it multiplies the current mod with a new mod, which is how it would calculate this, and also where it defines the 2.5f for the HighVoltage Tube, but I can not find where it or how this communicates with forestry's 16x previously mentioned. 

In the forestry code, the only modifier that is added rather than multiplies is the production modifier, I wonder if this is being added to the initial mod 1f to create 2f, and then being multiplies from there, causing a substantial increase? But, I have no way to test this, as my internet connection sucks for constant downloads for gradle.

**Comment by desagas** [comment]
If someone knows where this is being executed in the code, I could possibly see if I could create a fork myself to fix it?

**Comment by desagas** [comment]
Dream actually fixed this, so, ‘closed as not planned’ is highly misleading.

**Comment by Dream-Master** [comment]
changed

**Comment by ABelli99** [comment]
in 2.7.4 this issue still persists, production at 3.619 and still turns pristine into ignobles
