### ISSUE TITLE
Server log is spamming the same message

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#13772]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 19

### Type of Server

None

### Your Expectation

The server log should be much quieter with less spam around the Telsa tower.

### The Reality

I checked the server log and it is spamming the same messages around the Telsa tower.

I have pasted the image of the log

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127531099/dc2e5569-4702-497b-a2e5-4f27f5f6f499)

### Your Proposal

While the spam might be something I can ignore, I believe it might reveal a different issue such as tps issues from using the Telsa tower.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment]
Result of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13245 which affects just about everything related to Gregtech
