### ISSUE TITLE
Recipe Loophole in Grisium recipe

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#13786]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.3.4

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

The recent GT++ Multiblock downtiering made some GT++ Alloys had mixer recipes.

### The Reality

A Recipe Loophole Existed as Grisium Mixer recipe did not use Hydrogen as expected.
![HV5TX% 7R_ZLJF7W(%69C1U](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76087681/27bc01c4-a929-4f7b-b1d4-3f52ef79a866)
![TFF8%1{E~A8W9TB$5 @Z4K1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76087681/5634f454-6209-4d93-b16a-c9ecede82b24)

### Your Proposal

Grisium Dust mixer recipe shall consume hydrogen gas properly.
(I guess these recently downtiered GT++ Alloys may have other loopholes that are not found yet.)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GTplusplus/pull/678
