### ISSUE TITLE
"Recycle Titanium" Quest in LuV does not reflect reality of recipes?

### ISSUE THREAD

**Issue by BobGoldham** [GTNewHorizons/GT-New-Horizons-Modpack#13794]
### Your GTNH Discord Username

bobgoldham

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

For the quest to reflect actual recipes?

### The Reality

The quest states "or you can choose to electrolyze it directly" with regards to TiF3 dust.
This is not actually possible.

### Your Proposal

For an electrolyzer recipe to be added OR the relevant text to be removed from the questbook.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BobGoldham** [comment]
A similar issue exists with Gallium Hydroxide in the same questline.

**Comment by chochem** [comment]
yea the recipes were changed. just not the quests :P
