### ISSUE TITLE
nerf Large Essentia Generator

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#13792]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.3.4

### Your Proposal

LEG can achieve astonishing EU through simple coordination and a cost that can be considered non-existent. In the ZPM stage, it can obtain 670 million EU per tick through Liquid Death, Essential Generator: Tainted, and Aspect: Vitium. If Thaumium Golem and Golem Animation Core: Alchemy are used, a stable 136 billion EU per tick can be obtained
LEG通过简单的配合和可以被认为是根本没有的代价就能获取惊人的EU，在ZPM阶段通过Liquid Death，Essentia Generator:Tainted与Aspect:Vitium就能获得6.7亿EU每tick，如果使用Thaumium Golem与Golem Animation Core：Alchemy则能获得稳定的1360亿EU每tick

### Your Goal

For the ZPM stage, the combination of Liquid Death and Vitaum is too crazy. LEG should have a variety of choices, not just this one
对于ZPM阶段，Liquid Death与Vitium的配合太过于疯狂了，LEG应该拥有多样性的选择，而非只有这个选择

### Your Vision

Adjusting the combination of Liquid Death and Vitaum, or fundamentally limiting the Essentia Input Hatch of LEG from interacting with Golem, can prevent players from choosing to continue making Large Naquadah Reactors or XL Turbo Plasma Turbines after making LEGs in the ZPM stage and transitioning directly to Dyson Swarm Ground Unit, increasing the diversity of machine choices
调整 Liquid death与Vitium的配合，或者从根本上限制LEG的Essentia Input Hatch无法与Golem交互，这样可以防止玩家在ZPM阶段制作LEG之后不选择继续制作Large Naquadah Reactor或者XL Turbo Plasma Turbine而直接过渡到Dyson Swarm Ground Unit，增加机器选择的多样性

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
> 670 million EU per tick
> 136 billion EU per tick 
:concern: can you explain these numbers? I thought it was limitted to 64A ZPM (which is still too much but less insane).

**Comment by JodieRuth** [comment]
VITIUM has a basic fuel value of 4700 EU, but the liquid death has a bonus of (25000/basic fuel value) ^ 4, which is 800.5 times. Using IV level units, 1 VITIUM and some liquid deaths can reach 7504700 EU/tick, which is much higher than your estimate. In the Chinese community, this generator already has a general solution for generating 1048576A zpm, which is using VITIUM and liquid death

**Comment by chochem** [comment]
are you saying it still supports laser? damn I thought that was removed a while back. clearly I was mistaken

**Comment by JodieRuth** [comment]
Yes, it can still use lasers, but please do not remove this ability. Instead, modify the values to make it more diverse

**Comment by chochem** [comment]
the laser support is the main issue here. completely unbalanced.

**Comment by JodieRuth** [comment]
No, the combination of vitality and liquid death is much better than other combinations. You should not bury such a well-designed generator. You should remove unreasonable parts and strengthen other values. No one likes this, which directly makes a generator completely unusable

**Comment by chochem** [comment]
nobody is burying anything

**Comment by JodieRuth** [comment]
Yes, so don't remove his laser support. Adjusting the values is a better solution

**Comment by chochem** [comment]
both most likely yea. not just the one.

**Comment by JodieRuth** [comment]
Then LEG will be completely unusable, sad

**Comment by chochem** [comment]
8 million eu/t in zpm is unusable? you must be joking.

**Comment by JodieRuth** [comment]
These EUs may not even be sufficient to cover his maintenance costs when using Vitaum and Liquid Death

**Comment by chochem** [comment]
that would trivially be enough

**Comment by JodieRuth** [comment]
I think sometimes you should really open the game and play it yourself

**Comment by chochem** [comment]
I am playing right now lol

**Comment by JodieRuth** [comment]
Now that XL Plasma is lost in the ZPM stage, LEG is the last option. Without LEG, ZPM has difficulty having other options

**Comment by Miisi** [comment]
ZPM plasma is still usable with large plasma turbines and EHE

**Comment by chochem** [comment]
8 million eu/t in zpm and you are talking like its dead

**Comment by JodieRuth** [comment]
I said this is not enough to cover his maintenance costs, you must have never used LEG

**Comment by chochem** [comment]
show that calculation then how you somehow manage to use more than 8million eu/t

**Comment by JodieRuth** [comment]
Please use translation software to view this webpage
https://gtnh.huijiwiki.com/wiki/%E5%A4%A7%E5%9E%8B%E6%BA%90%E8%B4%A8%E5%8F%91%E7%94%B5%E4%BA%A7%E7%BA%BF

**Comment by chochem** [comment]
> In version 2.3.0, fusion power generation requires too much investment

first line lol. I dont think this is worth my read. or my translation software is garbage.

**Comment by JodieRuth** [comment]
I don't know if it's a cultural difference in the community, but in the Chinese community, 8 million EU is really not much in ZPM, and this does not include maintenance fees

**Comment by chochem** [comment]
8 million is very high in zpm for sure. LEG is just completely unbalanced (that part is not news). there is many layers to solving that but we had already discussed last year that laser is a big no for LEG.

btw I dont see any promised calculation or anything like that on that website.

**Comment by JodieRuth** [comment]
Considering his maintenance costs, the actual available amount is not as much as 8 million EU, and that website clearly has so many introductions and calculations about LEG..
