### ISSUE TITLE
Witching Gadgets has a lot of dependencies

### ISSUE THREAD

**Issue by Pyromanc3r** [GTNewHorizons/GT-New-Horizons-Modpack#13799]
### Your Pack Version

-

### Your Proposal

Is it possible to run Witching Gadgets outside of the modpack? I would like to play it separately.
I understand that this is a low priority task, but it would be nice if it were then given attention too.
![2023-06-25_17 09 10](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17619385/e06b43d2-4a7b-4850-9e7f-7874ba9ea522)

### Your Goal

Also I wanted to mess around with the localization, but it's a pain to load the modpack for ~5 minutes each time for a test.
I looked at the .lang file structure of the original mod (1.1.10) and this fork (currently 1.3.0) and they are significantly different.

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
copy paste from you other ticket :P :
this mod is on 'passive' support. which means it is primarily meant for GTNH and can or can not work outside. if somebody makes it workable outside of GTNH thats great and we wont break it (on purpose) but its not something any of our devs are actively working on.

fyi you can see that in this spreadsheet https://docs.google.com/spreadsheets/d/1LHd8c4FLLHiJqsuTppF2XFTE6bh-mXE7afVwGbzOKms/

**Comment by AnrDaemon** [comment]
You already broke it (on purpose), making it hard dependent on mods it had no strict dependency upon.
Why spending time changing it, and then saying that you would not break it, if somebody roll your changes back?

**Comment by chochem** [comment]
> You already broke it (on purpose)

it doesnt work outside of GTNH **on purpose**? then you must know more about it than me lol.

>  if somebody roll your changes back?

nobody is rolling back anything. if somebody wants to take this on, it would be about looking into why there is a dep and if it can be made into an optional dep. And if it literally cant or _actually_ is on purpose it would be removed from the passive list.

**Comment by boubou19** [comment]
> You already broke it (on purpose), making it hard dependent on mods it had no strict dependency upon.

No we did not break stuff on purpose. We aren't bad people, just volunteers working on an opensource mod for a modpack :)

Also you have to prove that it does not work outside of the pack: all we see on the screen is that you are missing the dependencies, not that the mod is broken. Now if you don't want to add said mods, that's not our fault.

**Comment by mitchej123** [comment]
This negative attitude is hardly the way to get anyone to be sympathetic to your request.

**Comment by chochem** [comment]
one of them is our gregtech boubou. that wont work outside the pack. agreed with the rest.

**Comment by mitchej123** [comment]
> one of them is our gregtech, boubou. that wont work outside the pack. agreed with the rest.

And if someone wants to turn it into a soft dep, great. Open a PR

**Comment by chochem** [comment]
exactly

**Comment by chochem** [comment]
back to the original topic. it looks to me like some where made hard deps by accident (including gt) here: https://github.com/GTNewHorizons/WitchingGadgets/pull/20
(going from compileonly to compile in a refactor)
