### ISSUE TITLE
New GT Tool: Squeegee

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#13790]
### Your Pack Version

2.3.4

### Your Proposal

I would love to see a tool added that could counter balance the need to clean the dirty solar panels one bucket (only tank allowed) at a time in the game. Two versions, just like every other tool, and regular version and an electric one.

With this tool, it would have an internal tank for water, or perhaps it will pull directly from a GT cell, single versions or bigger versions (1000L at a time). Or, perhaps its own liquid used, like vinegar at 50ml a wash, or something like that, since vinegar is gated past steel, this might help keep the balance.

### Your Goal

Make a solar playthrough less like the original facebook Farmville and more manageable.

### Your Vision

Enjoying the sun, casually cleaning my solars before dismantling them or before moving my miners or mass spamming them after the countless hours crafting them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by King65868** [comment]
There are block versions that don’t need to be cleaned so not sure how useful a tool for cleaning would be

**Comment by desagas** [comment]
Oh, I did not realize they are like that. I have only crafted ULV ones so far, and there is not a block version of those, not one I can see, anyways.

**Comment by chochem** [comment]
yea its LV+

**Comment by desagas** [comment]
Its actually IV ... because it requires the avarita crafting table, which requires an IV circuit.

**Comment by chochem** [comment]
no I mean LV+ solars (in contrast to 1 eu/t and ulv), not when you make them. And you can make them in HV. thats when you can make all that.

**Comment by desagas** [comment]
Yes, LV+ Solars, but you can not make the block versions until you have the avarita table.

**Comment by chochem** [comment]
yes. that is in HV, same as IV circuits. not that the LV Solars are easy in HV. trust me, I am doing a tech solar only run, it was rough. Just be grateful LV no longers needs sunnarium (which is EV).

**Comment by desagas** [comment]
Maybe my suggestion should be a IC2 / Advanced Solars solar for the 8V version?

**Comment by chochem** [comment]
I doubt I will get to it myself, but ULV solar having a blockform would be pretty nice, true.

**Comment by desagas** [comment]
ULV does have a block form ...

**Comment by desagas** [comment]
Just 1V, not 8V

**Comment by chochem** [comment]
8v = ulv

**Comment by desagas** [comment]
Hahah, well, 8V or Less, but I get what you are saying. My point does not change by changing the words. Lol.
