### ISSUE TITLE
Mega Fusions does not support Multi-Amp Wireless Hatches properly

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#13803]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.3.4

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

Wished to use a 64A wireless UMV energy hatch to power a MKV Mega Fusion, as I calculated that the maximum power cost is only 48AUMV. For safety I put 4 64A wireless UMV hatches, and other positions are filled with UEV energy hatch (no power provided to them).

### The Reality

The Fusion repetitively runs out of energy and stop, then restarts itself again.
Scanner tells me that "EU Required: 283115520 EU/t"(2.10A UMV). 
Replacing the 64A UMV wireless hatch with normal UMV wireless energy hatches shows the same phenomenon, so I infer that the fusion treated multi-amp wireless hatches same as non-multi-amp ones.

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Phineasor** [comment]
Read tool-tip, nonissue.

**Comment by TheEpicGamer274** [comment]
read the tooltip better next time, it clearly says it has a max amount of energy input per energy hatch,
