### ISSUE TITLE
Mega Oil Cracker does not support quadruple input hatch

### ISSUE THREAD

**Issue by hoshinokiseki** [GTNewHorizons/GT-New-Horizons-Modpack#13809]
### Your GTNH Discord Username

kisekiunofficial

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

i put a quadruple input hatch into a mega oil cracker. i expected the mega oil cracker should consume all four fluids in the quadruple input hatch.

### The Reality

but the mega oil cracker just consume fluid in the first slot and ignored fluids in the remain slots.

### Your Proposal

the mega oil cracker can consume all four fluids in the quadruple input hatch.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I would barely consider that a bug. A multi made for one fluid does not accept multiple magically.

**Comment by lordIcocain** [comment]
Actually, it support (tested in 2.3.5), but if in first slot liquid and amount not enough for recipe it just not check next slot, i had same issue with dangote in 2.3.2, but in 2.3.5 dangote working fine. So its bug, right?

**Comment by lordIcocain** [comment]
ehhh, anyway regular oil cracking unit working with quad, then mega should too, its bug, not suggestion

**Comment by lordIcocain** [comment]
bump
Please fix :lilcry:
