### ISSUE TITLE
Adding a higher voltage version of the MR circuit

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#13804]
### Your GTNH Discord Username

emskjd_114514

### Your Pack Version

2.3.4

### Your Proposal

Add more MR circuits to the GTNH, such as UIV UMV UXV with MAX voltage, to match the current board level

为GTNH添加更多的磁共振电路，例如UIV UMV UXV与MAX电压的磁共振电路，与现在的电路板等级相互匹配

### Your Goal

To match existing board systems and to prepare for future mass production of boards

匹配现有的电路板系统，并为未来的电路板大规模生产做准备

### Your Vision

Make MR boards more useful at a later stage instead of just sitting there polluting our NEI

让磁共振电路板在后期更有用处，而不是仅仅是放在那里污染我们的NEI

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I would say its rather unlikely to happen. I know that colen wanted to remove them completely for example https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12951

**Comment by Connor-Colenso** [comment]
These are on their way out of the pack, not being entrenched deeper, so absolutely not.
