### ISSUE TITLE
suggestion of the Ore dictionary filter card 

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#13807]
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

delta

### Your Proposal

the information of how to use the Ore dictionary filter card is not very clear in Wiki and also the quest book
it took me quite a long time to figure out how to use it
so I think it will be better to have a GUI of it
here is the concept GUI of the card
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/59776356/c8c43183-3aed-432f-8974-33b1e64ac14d)

### Your Goal

most people love graphical user interface and it is much more easy to use 

### Your Vision

I believe this feature would make the pack better. *

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
sounds tricky to get the same functionality in a gui unless the gui is optional.

by the way, I dont know whats on the wiki but you did read the quest right?

**Comment by Eason134HK** [comment]
> 
the quest copy a part of Wiki and have an example with it
that is not clear and not enough for a player to understand how the card work
it took me quite a long  to figure out _!something*_ is actually blacklisting **something** and _something*_ is whitelisting **something** 
the current description is not enough to explain clearly the relationship between ! and * relative to whitelist and Blacklist

**Comment by Eason134HK** [comment]
> 

the quest copy a part of Wiki and have an example with it
that is not clear and not enough for a player to understand how the card work
it took me quite a long to figure out !something* is actually blacklisting something and something* is whitelisting something
the current description is not enough to explain clearly the relationship between ! and * relative to whitelist and Blacklist

**Comment by chochem** [comment]
yea the quest explains that.

anyway thats the minor point. the bigger being how would a gui be able to capture such logic? I dont see it

**Comment by Eason134HK** [comment]
> yea the quest explains that.
> 
> anyway thats the minor point. the bigger being how would a gui be able to capture such logic? I dont see it

I don't know how those coding stuff work in background so if it is not going to work then never mind

**Comment by chochem** [comment]
its not the coding, its the functionality. Maybe this should rather be a separate thing than a replacement. gonna leave this open maybe some dev wants to think about/take it on.
