### ISSUE TITLE
Titanium tetrachloride processing is Chlorine POSITIVE

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#13815]
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.3.4

### Your Proposal

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49487505/c238a00a-fb62-446f-88f4-58bcd6740d88)
The EBF recipe uses 500mb to produce a ingot, and gives back 6 MgCl2 , which eventually returns 4 Buckets of Chlorine, thus making the line Chlorine positive.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49487505/7e8577de-0dee-4caf-907f-9b34b5d9b7d7)

### Your Goal

Balance the titanium line lol
this will clog lines and the extra chlorine comes out of nowhere

### Your Vision

Make it use 1000mb of titanium tetrachloride like other tetrachloride recipes. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by hoshinokiseki** [comment]
maybe you need to check your version. in 2.3.4 with nhcore and gt5u updated. this recipe is normall.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/88672077/ada56ebb-19c8-40cc-a45c-cc29457c44ee)
