### ISSUE TITLE
Rebalance the recipe of Low Power Laser Pipe

### ISSUE THREAD

**Issue by ZivilynNks** [GTNewHorizons/GT-New-Horizons-Modpack#13810]
### Your GTNH Discord Username

cteyit

### Your Pack Version

2.3.3

### Your Proposal

The pipe has a unreasonable recipe currently. Consturcting a Low Power Laser Network is almost impossible even upon LuV because of its quite expensive exquisite CubicZirconia gems in its recipe. To make one laser pipe will cost at least 37324800EU(EBF cost to process flawed CubicZirconia,HV2880s for 40, one pipe cost 54 of it) and lots of ITNTs. And even a low power laser device for transforming or receiving will cost 16 pipes. Hah anyone in EV wanted to build a laser power transmission pipeline must have to wait for several weeks in front of EBFs. 
BTW, the Low Power Laser Pipe is EVEN much expensive than Laser Vaccum Pipes. It is not reasonable at all. I think this part is like  being banned from GTNH currently.

### Your Goal

Remove those exquisite CubicZirconia from Low Power Laser Pipe's recipe.

### Your Vision

To make avaiable the Low Power Laser Networks. We will see them getting used but not staying in NEI.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Yes, otherwise just disable them at this point. Low power lasers costing less than actual ones is weird at best.

**Comment by vovaksenov** [comment]
Remove stale. The recipe balance is weird at best. Normal lasers are less annoying.
