### ISSUE TITLE
Slowing Down lander on the Moon caused crash

### ISSUE THREAD

**Issue by ScotchewahX** [GTNewHorizons/GT-New-Horizons-Modpack#13813]
### Your GTNH Discord Username

ScotchewahX

### Your Pack Version

2.3.0

### Your Server

Stone Legion

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

Went to moon, not first time. Used Tier 2 Rocket.

### The Reality

While slowing down lander for moon, at Y=450 game crashed.

### Your Proposal

Game not crash while slowing lander on moon.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
where is the crashlog? best also add the full fmlclientlatest on top
