### ISSUE TITLE
Fluid filling machines may lose containers when executing certain formulas

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#13814]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Sometimes, buckets containing fluids are opened in reward bags, or buckets containing fluids are obtained elsewhere, which cannot be stacked and difficult to store. I want to use a fluid filling machine to remove their fluids for more convenient storage. At this time, the fluid filling mechanism should output a container and some fluids
有时候会在奖励袋子中开出一些装有流体的桶，或者在其他地方得到了装有流体的桶，它们不能堆叠难以储存，我想使用流体灌装机将它们的流体取出以更方便的存储，这时候，流体灌装机理应输出一个容器与一些流体

### The Reality

These barreled or bottled fluids only output the corresponding fluid after passing through the fluid filling machine and do not return to the container correctly, such as some clay buckets, glass bottoms, and buckets, but filling the fluid into them requires a container
这些桶装或者瓶装流体经过流体灌装机之后只输出了对应的流体，并没有正确的返回容器，例如一些clay bucket，glass bottle和bucket，但是将流体灌入他们是需要容器的

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you gotta be more specific or there is nothing anybody can do.

**Comment by JodieRuth** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/b084d8b7-5a96-4b14-a69a-581f9db815f0)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/9ef67873-70dd-451b-9bf8-43f51382d17c)
Just like this. But in other formulas, it can correctly extract the fluid and return it to the corresponding container. Only a few formulas have similar issues.

Oh, wait, why is it not consumed during processing
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/d7b5604b-feac-4a96-be50-bf3e7ca7a71a)

**Comment by chochem** [comment]
looks like they all work fine in a tank, so use that for now

**Comment by JodieRuth** [comment]
Some other formulas can be returned to the bucket or bottle normally, and only a few formulas in the claim bucket will be returned

**Comment by desagas** [comment]
The same is true for using GT cells on all EnderIO machines. If you click on them with a fluid in a cell, the fluid will enter just as intended, but the cell will be voided.
