### ISSUE TITLE
Cleanroom provides perfect overclocks to singleblock machines inside of it

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#13823]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

2.3.4

### Your Proposal

I propose that singleblock machines in an active cleanroom will be buffed to provide a perfect overclock.

This overclock will only be active if the cleanroom power is equal or greater to the tier of the singeblock machine.

### Your Goal

This feature would allow the cleanroom to be viable for longer then late ev to early iv age where the age of multiblock arrives and makes the poor cleanroom obsolete.

### Your Vision

This would improve the pack as it would allow cleanrooms to not just be a throwaway mechanic but a mechanic that can be used to provide minor buffs to smaller systems that would not be setup in a multiblock setup.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
not only does that sounds crazy unbalanced. we also have no interest of incentivizing singleblocks in higher tiers.
