### ISSUE TITLE
Creating a SP world causes game to crash. World is unjoinable.

### ISSUE THREAD

**Issue by BobGoldham** [GTNewHorizons/GT-New-Horizons-Modpack#13824]
### Your GTNH Discord Username

bobgoldham

### Your Pack Version

2.3.4

### Your Server

SP world

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

- Create a new world in the Singleplayer menu
- Crash
- Return to main menu, try joining the (created and visible in world-listing) world I just created.
- Crash again
- World is and remains entirely unusable

### Crash Report

First crash report is the instance where I created the world
[crash-2023-06-28_02.07.25-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11888239/crash-2023-06-28_02.07.25-client.txt)

Second one is where I tried to join again
[crash-2023-06-28_02.07.57-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11888240/crash-2023-06-28_02.07.57-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Runakai1** [comment]
can confirm

**Comment by Alastors** [comment]
This has been confirmed to not happen in the latest nightly, if this doesn’t persist in 2.3.5 then it has already been fixed

**Comment by wlhlm** [comment]
Yeah, cannot confirm in nightly \#50. World creation works for me there.

**Comment by PolkageistHS** [comment]
Linked ticket has my crash logs, we're using a modified 2.3.4 with these mods, but it's been happening to me for a month.  Easily reproduceable. 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9247381/4f90a4d0-d2ea-4ac9-bc68-3305d1fc90db)

**Comment by BobGoldham** [comment]
Fixed in 2.4.0.
