### ISSUE TITLE
AE2 recursive Crafting

### ISSUE THREAD

**Issue by Ubus99** [GTNewHorizons/GT-New-Horizons-Modpack#13829]
### Your GTNH Discord Username

Ubus99

### Your Pack Version

2.3.0

### Your Proposal

Would it be possible to add recursive crafting to AE2?
i.e. when a recipe later in the pipeline returns a byproduct used earlier in the pipeline, to automatically split the recipe into batches and return the chemical to the beginning of a new batch instead of crafting it from scratch?

This often happens in Ore refinery pipelines, where chlorine and hydrogen get liberated at the end, but AE2 still electrolyzes them from water to create HCL instead of pulling from its own output.

### Your Goal

Streamlines and removes some conflicts from autocrafting

### Your Vision

This will make automated AE2 Chemical production lines much faster because it removes production steps that often bottleneck the system.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by hucking** [comment]
I'm also in favor of this (although I'm not sure how feasible or easy it would be to implement), and I will give another example that is pretty relevant:
In late-game after upgrading your DTPF to eternal coils you can switch your Raw Tesseract recipe to the better one however that recipe requires 32 Transcendent Metal Rods (and the only way to make those is with tesseracts)

If AE was able to handle recursive crafting it would be able to realize it just needs 2 tesseract to start the recipe and after that it can just make extra tesseracts as are required for the transcendent metal rods to make more tesseracts...
