### ISSUE TITLE
Dupe Bug, Node in a Jar Vajra

### ISSUE THREAD

**Issue by Marvallon** [GTNewHorizons/GT-New-Horizons-Modpack#13837]
### Your GTNH Discord Username

Marvallon#8026

### Your Pack Version

2.3.0

### Your Server

Eta

### Java Version

Java 19

### Type of Server

None

### Your Expectation

I tried to Silk Touch a Node in the Jar with my Vajra and expected to get one whole Node in a Jar. 

### The Reality

I Silk touched a Node in a Jar with my Vajra "shift+right click" and got two Nodes in a Jar. 
I checked if it was lagg, I checked if they disappear upon mining them, I checked if they can be used normally. The intended use was to make one into an activated one and it worked fine. 
My Team Mate tried as well to confirm the bug. 
As to kind of node, it is advanced jarring on different kinds of nodes tested. Advanced jaring, using the 26 warded glass and 9 warded silverwood logs. I do not know if the same happens to normal nodes in a jar. I don't even know if they have different IDs. ! I am that kind of helpless. 

Hey I just checked all the Final Checklist. Brilliant. 

### Your Proposal

Make my expectations a reality or tell me it is fine if I sell them as "handcrafted" to "Citizen"  and up rank, to avoid server clogging with money farm =). 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Fixed with https://github.com/GTNewHorizons/Gravitation-Suite-Neo/pull/11
