### ISSUE TITLE
Rectangular cleanroom won't form

### ISSUE THREAD

**Issue by Sopel97** [GTNewHorizons/GT-New-Horizons-Modpack#13833]
### Your GTNH Discord Username

sopel__

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Following https://github.com/GTNewHorizons/GT5-Unofficial/commit/b7cc73979867bbb18b937857aa072a91d87dac75, rectangular cleanrooms should work.

### The Reality

Rectangular cleanrooms don't form. I tested this in creative by building a square one (which formed) and trying to extend it to a rectangular one by extending one side by 2 blocks and fixing the top (didn't form).

### Your Proposal

Figure out why the commit linked earlier is wrong.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
(kinda, everyone tells me they have never seen a rectangular one)

**Comment by joshaup1999** [comment]
I've always known the cleanroom needing to be square. Perhaps that commit was never merged or it has been changed since back to needing to be square

**Comment by Sopel97** [comment]
The commit I linked is from the master branch and was found through git blame. There clearly is code in the current mater that is meant to support rectangular cleanrooms.

**Comment by chochem** [comment]
the code also says it has to be a square twice.

**Comment by chochem** [comment]
ah, comparing your description to the code: it sounds like you didnt do it symmetrically!

but the code needs at least documentation cleanup

**Comment by Sopel97** [comment]
it was symmetrical, I verified the controller is in the middle

**Comment by chochem** [comment]
yea, I am adding some more debugging parts currently
