### ISSUE TITLE
Visual Prospecting `oregenPattern` crash on loading world

### ISSUE THREAD

**Issue by voidei** [GTNewHorizons/GT-New-Horizons-Modpack#13832]
### Your GTNH Discord Username

voidei

### Your Pack Version

Nightly (2023-06-29+39)

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Notes: Crashing on Java 20, Java 17, and Java 8

1. Install latest build from [DreamAssemblerXXL Actions](https://github.com/GTNewHorizons/DreamAssemblerXXL/actions/workflows/nightly-modpack-build.yml)
2. Launch game
3. Create or load a world
4. Crash to menu

### Crash Report

https://mclo.gs/xaTl6fr
https://mclo.gs/w9SJi9Z

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment]
Please downgrade GT to this version: https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.43.100-pre

**Comment by wlhlm** [comment]
Upcoming nightlies should be fixed for now.
