### ISSUE TITLE
NEI Feature Request: Save/Load inventory command

### ISSUE THREAD

**Issue by Graymare** [GTNewHorizons/GT-New-Horizons-Modpack#13838]
### Your GTNH Discord Username

Embri#3434

### Your Pack Version

2.3.0

### Your Proposal

NEI originally had inventory state load/save commands, which were removed during various updates due to the annoyance of trying to implement a GUI for them.  I'd like to see the functionality make a return, but with a (hopefully much easier to do) text command.

According to mitchej123, 95% of what would be needed for this already exists:
(https://discord.com/channels/181078474394566657/234936569360809996/1124107328984191006)
just missing loadState(int) and saveState(int)

### Your Goal

At present the only way to move items between worlds, change loadouts or to restore things are one at a time with NEI.  While this is by no means a bad system, it does have some limitations and can be tedious if a large number of items need to be swapped or spawned, especially repeatedly.

### Your Vision

Saving inventory states would be helpful for testing things in creative (having separate swappable loadouts for building vs. testing or different projects) and migrating large quantities of items between worlds.  

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by desagas** [comment]
One of my biggest pet peeves with any system that works like NEI or JEI or even REI is that it is always the same across your instance, regardless of what world you go into. I wish each world had its own state, rather than a only one for a whole instance.

**Comment by wlhlm** [comment]
> One of my biggest pet peeves with any system that works like NEI or JEI or even REI is that it is always the same across your instance, regardless of what world you go into. I wish each world had its own state, rather than a only one for a whole instance.

What state do you mean specifically? NEI allows saving settings per world already.

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/85881f73-5bb0-48d8-8f83-bfa07581dbf2)

**Comment by wlhlm** [comment]
Also, you can click on this button to toggle between saving settings globally or per world:
![Screenshot 2023-07-02 222712](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1928113/c9d1fc28-2eca-4cd3-a7ad-d1d7efc2e5d3)

**Comment by desagas** [comment]
OMG, I am so sorry, I have seen that 1000 times before and never touched it ... laughing at myself here ... but I still like her idea of being able to cycle through saved versions.
