### ISSUE TITLE
galacticraft frequency module needs to be removed from slot, then put back, any time you want to hear sound in space

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13839]
### Your Pack Version

2.3.4 nightly (idk which)

### Your Server

self hosted

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

i expect the module to work from the slot

### The Reality

you must click it out then put it back to get sound every single time. a few people just thought its been completely broken the entire time

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
noticed this myself this week. has it always been like that? very strange.

**Comment by SEGPPMEJPTF** [comment]
Is your frequency module enchanted? Mine is (Soulbound) and I’ve noticed the same issue.

**Comment by vovaksenov** [comment]
No, this happens to any module, enchanted or not.
