### ISSUE TITLE
Batch mode for cyclotron, multi smelter, qft, and dtpf

### ISSUE THREAD

**Issue by meepmopper** [GTNewHorizons/GT-New-Horizons-Modpack#13841]
### Your Pack Version

2.3.4

### Your Proposal

Batch mode for cyclotron, multi smelter, qft, and dtpf

### Your Goal

My base would prefer not to have passive machines one ticking :C

### Your Vision

Improve performance

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
I dont think this should be closed without a response. Multismelter definitely should have one at least if it does not yet.
