### ISSUE TITLE
Staff Core of the Primal can't creare staff

### ISSUE THREAD

**Issue by tiankong-sky** [GTNewHorizons/GT-New-Horizons-Modpack#13847]
### Your GTNH Discord Username

tiankong#7933

### Your Pack Version

2320

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I want use the staff core of the primal to create staff .

### The Reality

the staff core of the primal dont have staff recipe, it just have staffter.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/85264564/17453972-2c1e-4bbd-859f-3980ea9f79a8)

### Your Proposal

it should have recipe of staff like other core

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GTNH-TC-Wands/pull/16
