### ISSUE TITLE
Infinite ender goo loop to get mass amounts of tungstate before T2 rocket

### ISSUE THREAD

**Issue by Spartends** [GTNewHorizons/GT-New-Horizons-Modpack#13843]
### Your GTNH Discord Username

Spartends#4798

### Your Pack Version

2.3.4

### Your Server

private

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

Expected for ender goo to not recycle completely.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/130987644/2c3033bf-059b-4453-9f5b-ede6c6280dee)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/130987644/44403239-ab72-48c2-9b25-1315ec3c5e07)

### Your Proposal

Either remove the liquid ender->ender goo recipe or make it not 100% recyclable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by joshaup1999** [comment]
To be fair, you can get mass tungstate from crops before T2. But yea this loop doesn’t seem right

**Comment by chochem** [comment]
as this is 2.3.4 and fluids in recipes: did you do the gt fix? https://gtnh.miraheze.org/wiki/Dev_Release_Stability

**Comment by Spartends** [comment]
This issue occurred even with these fixes:
https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.43.85
https://github.com/GTNewHorizons/NewHorizonsCoreMod/releases/tag/2.1.51

**Comment by chochem** [comment]
ah no this seems like a different problem. well 2 actually:
1) you have old script file messing with your game
2) i/o is swapped in dev
