### ISSUE TITLE
Buff space assembler

### ISSUE THREAD

**Issue by meepmopper** [GTNewHorizons/GT-New-Horizons-Modpack#13842]
### Your Pack Version

2.3.4

### Your Proposal

Add more parallels to space assembler mk2 or downtier mk3 space assembler to umv. They are way too slow once you begin crafting eoh and spamming se is obnoxious.

### Your Goal

Space assembler mk2 are way too slow and mk3 are super gated.

### Your Vision

Reduce spam of se

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by ramseyspace** [comment]
I have 2 SE on them, 24 total atm but i do agree its a bit obnoxiously too expensive mk3 assemblers

**Comment by Hiagg** [comment]
mk5 fusion is pretty sucky with the way it currently works since lapo skip is also in space elevator. space elevator should not be the spam multi that it has become. needing multiple space elevators just for assembling (then many more for pumps) seems to be the wrong direction for it
