### ISSUE TITLE
Botany Ceramics Quest items are not recognized

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/GT-New-Horizons-Modpack#13849]
### Your GTNH Discord Username

Admin_XiaoMai

### Your Pack Version

2.3.4

### Your Proposal

![1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/45018dae-532e-4d91-a242-a1510b7efa97)
![2](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/e794ec9d-577a-4d79-951d-e665181c2953)
Quest items are not recognized
quest id AAAAAAAAAAAAAAAAAAAHqQ==

### Your Goal

Complete the quest

### Your Vision

can get the quset done

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I am gonna guess you forgot `/bq_admin default load` after updating

**Comment by chochem** [comment]
ah ignore that. looks like I only fixed the quest leading up to this one <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/11793>

**Comment by wlhlm** [comment]
> I am gonna guess you forgot /bq_admin default load after updating

The questbook will now be automatically reloaded in 2.3.4: https://github.com/GTNewHorizons/BetterQuesting/pull/110
