### ISSUE TITLE
2 NPEs

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13840]
### Your Pack Version

2.3.4+

### Your Server

self hosted

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

to not get NPE

### The Reality

i get NPE when looking at item conduit that is not in a bundle, or an ME chest. caused by holoinventory i assume

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13358034/dfe726a6-a795-477b-b19a-d66ecb2b5f0d)

### Your Proposal

idk fix it i guess

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
https://discord.com/channels/181078474394566657/181078474394566657/1124145655821119579

I'm closing this, he did it as a joke.

**Comment by Hiagg** [comment]
but this is a real NPE with a listed cause still

**Comment by Alastors** [comment]
> but this is a real NPE with a listed cause still

Cool story bro, still a joke ticket, our issues list is not a joke

**Comment by TheEpicGamer274** [comment]
Its a valid issue with an actual npe, not a joke.

**Comment by Alastors** [comment]
The user himself said he posted this ticket as a joke, it maybe a valid issue but that has no bearing in the face of the bad faith that spawned this ticket

**Comment by xSkewer** [comment]
In Hiagg's defense, there isn't much else he could have written in the proposal section, and it doesn't seem like there's much more he could have provided.

**Comment by Alastors** [comment]
Again, it's not about the ticket it's about the bad faith joke nature that spawned this ticket

**Comment by Hiagg** [comment]
just because a joke causes the ticket doesnt mean im posting it with bad intention. i only post real issues whatever the reason i make the ticket. the goal is still to get things in the pack fixed
