### ISSUE TITLE
EIC structure detacting bug

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#13859]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.3.4

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

With any of the blocks missing EIC shall stop working and show "Incomplete Structure".

### The Reality

First build an EIC and let it detect its structure (the middle 5 blocks will disappear). and then break the middle blocks. If fast enough, the EIC will still function normally as if these neutronium blocks were still there!
Even replacing or breaking hatches still keep the EIC working. The only way to end such situation seemed to be breaking the main block, and resulting lose of 5 neutronium blocks.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ilithios06** [comment]
Can confirm that this issue also exists in 2.3.5
