### ISSUE TITLE
clay electrolyzing balance

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#13862]
### Your GTNH Discord Username

tom6482

### Your Pack Version

2.3.4
Recipe is unchanged in 02 jul nightly

### Your Proposal

Make it so that clay electrolyzing doesn't produce more power than it takes.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8298646/8fb7e383-1bb3-444e-ab70-fb74c9171086)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8298646/986b306c-03ed-474a-a9fd-d3a37c829c39)

Right now only the hydrogen pays 12x as much as the pwoer required for the recipe.

### Your Goal

make the pack more painfull.

### Your Vision

The pack is famous for being super-hard, this recipes makes it too easy.

However, i know that clay is balanced, so this might be intended?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
yea this also doesnt seem to be chembalanced. will probably have to revert this one. pxx tried to force in alumina whereever possible but didnt even think about the Hydrogen I think.

**Comment by Dream-Master** [comment]
before it was water but since so much oxygen is bound in alumina and h2O canged to H. Before it was AL dust

**Comment by chochem** [comment]
yea but now oxygen goes missing and the water electrolysis came for free energywise

**Comment by chochem** [comment]
well from a realism perspective there isnt that much hydrogen in there anyway. So here is my new proposal which should cover all aspects (make alumina available, dont produce hydrogen, satisfy chembalance, be more realistic, ...):

just change the formula itself and do
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/b58f5157-8fa0-4891-9033-dc120452c41a)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/15a5236f-90fd-4df6-9a0b-d7d18adcdb6d)
