### ISSUE TITLE
Avaritia chest crash with a lot of patterns

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#13860]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

2.3.0-RC-4

### Your Server

MP

### Java Version

Java 8

### Type of Server

Thermos

### Your Actions

a man put a chest from AVARITIA (compressed into 256 slots) and put about 150 templates from AssLine into it. Further (I don’t know the exact information) when he flew up close to the chest, constant crashes occurred. Here is a photo of what minecraft writes and logs:

### Crash Report

[LOG.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11928774/LOG.log)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/61422500/ec2ca133-2ff4-4b11-9fc4-ce24fccf2b33)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by FoKuCNiK** [comment]
I’ll add one more bug from myself: when you poke a scanner on IEG (a multiblock for selection for electricity) and I put about 4000 seeds in it), it also crashed the player when he entered the server (until the scanner was removed from the inventory, crashes continue) and also crash due to memory overload of some kind for reading data

**Comment by joshaup1999** [comment]
Scanner crash is known and fixed in updates, the issue of the infinity chest is player error. Patterns store a decent amount of nbt... Not much can be done apart from deleting the inf chest and telling them not to do that again. But i could be wrong
