### ISSUE TITLE
Add uxv machines

### ISSUE THREAD

**Issue by meepmopper** [GTNewHorizons/GT-New-Horizons-Modpack#13874]
### Your Pack Version

2.3.4

### Your Proposal

Add uxv machines for PA. 

### Your Goal

Umv pa are too slow

### Your Vision

help reduce umv pa spam.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by srdr2k3** [comment]
I think this would be a good addition, there are also some cases where GTPP machines are hard required for UXV progression due to no UXV singleblocks being available.

**Comment by EnderProyects** [comment]
But PAs are goin to be removed, no?

**Comment by srdr2k3** [comment]
MuTEs have a very long way to go, that's not a good argument IMO.

**Comment by evgengoldwar** [comment]
> MuTEs have a very long way to go, and PAs won't be removed until then iirc, that's not a good argument IMO.

Who's stopping you from making a PA replacement without MuTes

**Comment by Reflex18** [comment]
First you would need to isolate which of the machines that you are spamming the most that you want the PA for. Then once you understand which ones those are then you need to start thinking up a replacement multiblock with unique mechanics.

**Comment by EnderProyects** [comment]
I mean, I´m okay with the addition of new tier machines, but at that tier I think there should be only multi

**Comment by srdr2k3** [comment]
> > MuTEs have a very long way to go, and PAs won't be removed until then iirc, that's not a good argument IMO.
> 
> Who's stopping you from making a PA replacement without MuTes
My lack of Java knowledge.

This is an issue about adding UXV singleblock machines, not a PA removal issue. As far as i know, PA removal was delayed until further notice and UXV singleblocks would be a nice bandaid addition for now.
