### ISSUE TITLE
Add higher amp wireless hatches

### ISSUE THREAD

**Issue by meepmopper** [GTNewHorizons/GT-New-Horizons-Modpack#13875]
### Your Pack Version

2.3.4

### Your Proposal

Add higher amperage wireless hatches. 

### Your Goal

64 amps of uxv is only ~33b eu/t and way too small for anything endgame. Even for umv tier they are too small and they are unlocked after t7 eoh.

### Your Vision

Getting rid of lsc/at spam would help endgame. At uxv it is reasonable to get rid of lasers as the eoh operates wirelessly and it would help performance to get rid of hundreds of lsc/ats.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by ramseyspace** [comment]
I like this idea. I would like to stop using active transformers and lsc spam at some point end game after t7 eoh. I strongly agree this will help a lot with performance

**Comment by FoKuCNiK** [comment]
I think it's high time that the Wireless Energy Hatch had 256 1024 and so on amps as lasers. Lasers open completely very early, unlike non-conductive ones, and I think they should replace everything. (and improving the tps server will never hurt anyone)

**Comment by FoKuCNiK** [comment]
Also I don't see any problems in wireless dynamo of large amperages

**Comment by GDCloudstrike** [comment]
addressed in https://github.com/GTNewHorizons/TecTech/pull/228
