### ISSUE TITLE
New GT_Multiblock Machine:  Production Line Encapsulator

### ISSUE THREAD

**Issue by RealSilverMoon** [GTNewHorizons/GT-New-Horizons-Modpack#13871]
### Your GTNH Discord Username

real_silver_moon

### Your Pack Version

2.3.4

### Mod Name

BoxPlusPlus

## **Prologue**
- Throughout the course of your extensive gaming experience, you may have previously experienced frustration like **this**:
![%__39W @HOY8Z2I YTBR580](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/2cc1a069-a1b6-4d68-91f7-3d97d4f1d086)
- **This**:
![3AK3@3@MO2QX( 2Q@VQ_0H5](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/804ab58e-33b9-4f97-b1a7-168e0e8b6d9f)
('**PIPE MAZE**' are memes only)
- Or **this**:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/6eaa6102-ce8d-420b-af9d-67447e29ba99)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/6e641842-68ec-488d-bb6a-cea03cbc7be4)
This multiblock is dedicated to resolving these vexing issues. Intruduce a new GT_MultiBlock: Box, which machine type is **Production Line Encapsulator**.
## Why we need a new machine called Box?
In the late stages of the game, we observe a gradual emergence of progressively intricate production lines and recipes, including the Lanthanide Metal Production Line, Kevlar, PureWater process, and others. Unfortunately, our server TPS and client FPS frequently encounter difficulties when tasked with managing a substantial number of entity machines. Additionally, the processing time required for late-game recipes has undergone a significant increase, rendering the creation of a set of Stargates nearly impossible (1 year at least). While the Quantum Field Theory (QFT) offers a means to bypass intricate production processes, the box presents an alternative solution.
## What is Box?
The Box System is a GT multi-block machine with encapsulation capabilities. Its primary objective is to encapsulate intricate and multifaceted production lines, involving multiple machines, into a single unified machine. This innovative approach significantly mitigates the TPS decay attributed to the complexities of inter-machine logistics, such as the utilization of pipes and AE systems. Although you might draw parallels between the Box System and the Quantum Field Theory (QFT), it is important to note that the two operate in distinct manners. To provide more comprehensive information, I have created a video which elaborates on this topic:

https://youtu.be/25Rgx-aWPwE

## How does it work?
As you can see in the video, box need you to write every recipe into the machine. There are two ways to do that: 
1. put machine host and raw materials on inputbus/hatch;
2. read directly from NEI (WIP). 

Once every recipes are written down, it will build final recipe. You can adjust the coefficient on each recipe to get a better recipe. A perfect Box recipe should eliminate all intermediate products. For example, we have three recipes here:
- A+3B=C
- 2C=E
- 3F+A=G

Then, by adjust the coefficient, we get:
- 6A+18B=6C
- 6C=3E
- 3E+A=G

Build the Box recipe, we get:
- 7A=G

That would be our final recipe. The box will lock it and there's no way to change it (just like Cricuit Assembly Line with Circuit
Imprint ). Put 7A in the inputbus, it will run and output 1G. No any intermediate steps involved!
## More Pictures
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/0ddf7735-6d30-42a4-9c64-eb2714b202b1)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/3765b63a-cc86-4b8c-be1c-362faa08cfd9)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/e0a70add-90ff-4dfc-a50a-b438a43f23c7)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/839aaee9-8e75-4758-97d6-96dc5452a78d)
A sample encapsulation, which contains part of platinum metal processing:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31100241/a4b87633-78ec-47b2-9c69-081d8c5e971f)

## Link
This mod is under LGPL-3.0 license. You can find it here:
https://github.com/RealSilverMoon/BoxPlusPlus

### Your Reason

As above:
_In the late stage of the game, we witness increasingly complex production lines and recipes. Lanthanide Metal Production Line, Kevlar, PureWater process and so on. However, our TPS and FPS often struggle to handle such a large number of entity machines. Besides,the processing time for late-game recipes has also increased significantly, making it nearly impossible to make a set of Stargates._

### Preliminary Investigation

The development of this mod has been completed. It underwent testing in the Chinese GTNH community for approximately one month. Furthermore, I have successfully implemented it into my 50-players-online GTNH server, and it is currently functioning normally. However, it is important to note that there might still be undiscovered problems, necessitating additional testing for further refinement. Additionally, certain recipes may require adjustments if necessary.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [X] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by chochem** [comment]
this is a pretty massive change that would need some in depth discussion/tiering/etc.

Putting literally all processes into a single machine is kinda boring for the most part but it might be something for ultralategame I suppose, similar to EoH on the resource and power side. So maybe something for UMV/UXV? @GTNH-Colen @GDCloudstrike maybe you guys have some thoughts.

The pictures are a bit misleading as that is already overcome in IV with AE2.

**Comment by EnderProyects** [comment]
I think that since the machine has 3 tiers, each one should be gated different, the base one at ZPM, the second one at UHV, and the last at UMV, since it tier extends the recipes the multiblock can process

**Comment by Connor-Colenso** [comment]
Bruh, what.

Cool concept, I think @Glease toyed with something similar before. I would need to play with this ingame to get a proper idea but it's neat, but yea would have to be quite endgame. ZPM is way too early for this monstrocity. Definitely not something we should probably be shipping with nightly until we have a much firmer idea of what is going on here lag/balance wise.

**Comment by RealSilverMoon** [comment]
> I think that since the machine has 3 tiers, each one should be gated different, the base one at ZPM, the second one at UHV, and the last at UMV, since it tier extends the recipes the multiblock can process

Indeed. For now the recipe tierd between LUV to UMV, but i don't think it's something that would easy to make in LUV. According to AE's calculate, tier 1 ring require about 3,000,000 titanium and 300+ LUV motor&piston. Even if you make the ring, you are still need to build modules on it, while ring 1 tier 1 module can only do few jobs like large chemical reactor or furnace. And when it comes to ring 2&3, the cost is far more than the corresponding voteage. This machine is located at "the final productive forces of one tier" (in order to reduce tileEntity count and save tps), so i give it powerful function.

**Comment by minecraft7771** [comment]
The overall concept also heavily reminds me of how the advanced chemical processor MuTE works that's available on MuTEMaster branch of GT5U.

**Comment by BlueWeabo** [comment]
I think before deciding if we should add it or not. It needs to have proper descriptions and textures for all the things. It needs to have proper balance. 3M titanium is nothing dependent on when its unlocked. Please do not use textures you haven't been given access to. (Speaking for the Factorio Centrifuge image you have as an asset and many of the other textures i have seen by looking through it)

**Comment by S4mpsa** [comment]
The overall "UI/UX" feel of this is very different from the rest of the pack, and as BlueWeabo said the images used are questionable. Would definitely need a texture pass before even thinking of merging into main.

The primary name should also not be "Box", it's completely different to the naming scheme of everything else in the pack. Could come up with a sciencey name that abbreviates to BOX.

**Comment by EnderProyects** [comment]
BOX
Bottomless
Object
Xchanger

**Comment by boubou19** [comment]
@RealSilverMoon We can't accept such a mod because you violate multiple texture licenses.

**Comment by BlueWeabo** [comment]
https://github.com/RealSilverMoon/BoxPlusPlus/blob/master/src/main/resources/assets/boxplusplus/textures/gui/2.png
https://github.com/RealSilverMoon/BoxPlusPlus/blob/master/src/main/resources/assets/boxplusplus/textures/gui/7.png
https://github.com/RealSilverMoon/BoxPlusPlus/blob/master/src/main/resources/assets/boxplusplus/textures/blocks/modules/BoxModule1.png
https://github.com/RealSilverMoon/BoxPlusPlus/blob/master/src/main/resources/assets/boxplusplus/textures/blocks/modules/BoxModulePlus1.png
https://github.com/RealSilverMoon/BoxPlusPlus/blob/master/src/main/resources/assets/boxplusplus/textures/blocks/modules/BoxModulePlus13.png

At minimum these textures should be removed and replaced.

**Comment by chochem** [comment]
wtf is this mod

**Comment by boubou19** [comment]
yeah no, no NSFW will happen in NH.

**Comment by Dream-Master** [comment]
@boubou19 i would say we cant add the mod rn but i guess @RealSilverMoon can make the mod GTNH compatible.
If not we can close it later.

**Comment by Steelux8** [comment]
The single purpose of the QFT is to remove earlier tier processing lines from GTNH bases. Not all machines would end up replaced, even in the "best" QFT scenario, but a machine like this would have to be tiered around the same GT tier or later. Because of that, I feel like the two multis would exist for the same purpose.

**Comment by GDCloudstrike** [comment]
Two major issues I have with this multi: 
-It being able to replace 99% of all processing machines is too much, it has no niche like the qft, it just straight up replaces every machine in an endgame base from bending over fusion reactors to DTPFs
This should not be the goal imo, one machine that does literally everything is just boring

-This multi appears to be designed to be spammed. From what I'm gathering from the showcase video it seems that you have to binf the multi to one processing chain and that's it. So you'd need 1 of these for every processing chain which means extreme amounts of spam. 

So in the end you'd end up with replacing your entire base with hundreds of copies of this one multi, which sounds horrible.

**Comment by EnderProyects** [comment]
I just have to say that I doubt anybody will use this multy on a massive way, since the cost for each module are overexagerated
For example the alloy smelter module is not worth ( or any module) to just be making a line
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/cb0e4da3-a0ed-478c-a871-628e7080bafc)

**Comment by RealSilverMoon** [comment]
> yeah no, no NSFW will happen in NH.

These images and textures need to be replaced as they were only used for internal testing and are no longer suitable for release into the pack.



> Two major issues I have with this multi: -It being able to replace 99% of all processing machines is too much, it has no niche like the qft, it just straight up replaces every machine in an endgame base from bending over fusion reactors to DTPFs This should not be the goal imo, one machine that does literally everything is just boring
> 
> -This multi appears to be designed to be spammed. From what I'm gathering from the showcase video it seems that you have to binf the multi to one processing chain and that's it. So you'd need 1 of these for every processing chain which means extreme amounts of spam.
> 
> So in the end you'd end up with replacing your entire base with hundreds of copies of this one multi, which sounds horrible.


I did hesitate when adding some module adaptations, such as DTPF. So i apply an additional debuff to DTPF, increasing the recipe time by 400% and decreasing the output by 75%. I think it's necessarily to add a configuration file to determine which modules will be enabled.
As for the second point, there should be no need to worry. This machine may not be as "ideal" as it appears on the surface. In fact, due to the manual input and balancing coefficients required for the processes, it becomes quite challenging to obtain a truly suitable overall recipe. This demands a significant amount of thought and adjustments. The costly recipes and recipe locking further restrict the usage of Box. As a result, only a few processing chain can be perfectly encapsulated, and that exactly the largest difference from QFT.

**Comment by EnderProyects** [comment]
@RealSilverMoon Any chance of an extra module that brings together the neutronium compressor for making singularitys faster and the dire autocrafting table?

**Comment by RealSilverMoon** [comment]
> @RealSilverMoon Any chance of an extra module that brings together the neutronium compressor for making singularitys faster and the dire autocrafting table?

Neutronium compressor would be easy to add since this machine does support handling recipes with an extensive quantity of input items, but that definitely requires an ME storage input bus to detect and running recipe. It can be added to an existing module or enabling the reserved module-12 both.

**Comment by Phineasor** [comment]
I see no reason for this change, the point is to have complex assembly lines, there are ways to automate things in efficient manners, on the balls run we have about 10ms of lag, and we are UHV lag is not a problem if you read the quest book.

**Comment by chris1380** [comment]
> I see no reason for this change, the point is to have complex assembly lines, there are ways to automate things in efficient manners, on the balls run we have about 10ms of lag, and we are UHV lag is not a problem if you read the quest book.

When you get post UEV lag will become a big problem. You can't avoid spamming multis at later stages. I believe this mod will be a good end-stage solution if properly balanced. UEV might be a good start.

**Comment by Phineasor** [comment]
> > I see no reason for this change, the point is to have complex assembly lines, there are ways to automate things in efficient manners, on the balls run we have about 10ms of lag, and we are UHV lag is not a problem if you read the quest book.
> 
> When you get post UEV lag will become a big problem. You can't avoid spamming multis at later stages. I believe this mod will be a good end-stage solution if properly balanced. UEV might be a good start.

So, lag is not a problem UEV+, GDCloud just got the stargate today on the newest version, and his world runs at 20 tps, I also am UXV working on startgate in my personal world and have 20 tps. no lag problems late game.

**Comment by RealSilverMoon** [comment]
> > > I see no reason for this change, the point is to have complex assembly lines, there are ways to automate things in efficient manners, on the balls run we have about 10ms of lag, and we are UHV lag is not a problem if you read the quest book.
> > 
> > 
> > When you get post UEV lag will become a big problem. You can't avoid spamming multis at later stages. I believe this mod will be a good end-stage solution if properly balanced. UEV might be a good start.
> 
> So, lag is not a problem UEV+, GDCloud just got the stargate today on the newest version, and his world runs at 20 tps, I also am UXV working on startgate in my personal world and have 20 tps. no lag problems late game.

Seems that you doesn't consider multiplayer. In large servers, there may be multiple teams reaching the UMV+ stage, and no powerful CPU can support the mspt at this point (even a 6GHz 13900KS might be able to). This is an issue with Minecraft itself. While this mod may not have much significance in single-player games, it can bring significant optimization in the late stages of multiplayer gameplay, allowing players to avoid the pain of experiencing double or even triple machine processing time under low TPS.

**Comment by xSkewer** [comment]
I don't know what you would consider large, but we do have a couple of groups (~3-5 players on at a time) at UMV/UXV who are doing fine for TPS. Both are running on the same i5-13500 along with some other lower tier groups.

Personally I think the idea is cool and optimization is always good, but major performance optimizations like this aren't necessary yet and the multi would need a big rework to keep it from being useless/overpowered.

**Comment by Hikari1nVoid** [comment]
For sp ~10ms mspt for UEV bases on 5800X is easy.
While in MP You need to multiply the number of players in the server.
And for specific proclines u still need to do manual calculation on balancing.ME Network has already provided spam solutions so I don't see a difference between building multiple machines for one procline and AIO proclines.
It did reduce the color diversity of ur base and make it not that great on minimap tho.

**Comment by RealSilverMoon** [comment]
> I don't know what you would consider large, but we do have a couple of groups (~3-5 players on at a time) at UMV/UXV who are doing fine for TPS. Both are running on the same i5-13500 along with some other lower tier groups.
> 
> Personally I think the idea is cool and optimization is always good, but major performance optimizations like this aren't necessary yet and the multi would need a big rework to keep it from being useless/overpowered.

My server has 42 players online on average (with a total of approximately 300 players), till now 5 teams reaching the UMV+ stage and 10 teams at UV+. Even after best optimizations, the mspt can only be reduced to around 100ms. Certainly such a large server is rare, but smaller servers (with lower CPUs) can also face similar challenges, especially when the late game content is still expanding. 
Additionally, this idea aims to reduce excessive early or duplicate production lines (yes, i mean, LCRsssss!) so that more guys can enjoy the late game, but not to replace the Space Elevator or EOH. I'm also worried about whether DTPF should be in it...

**Comment by Phineasor** [comment]
> > I don't know what you would consider large, but we do have a couple of groups (~3-5 players on at a time) at UMV/UXV who are doing fine for TPS. Both are running on the same i5-13500 along with some other lower tier groups.
> > Personally I think the idea is cool and optimization is always good, but major performance optimizations like this aren't necessary yet and the multi would need a big rework to keep it from being useless/overpowered.
> 
> My server has 42 players online on average (with a total of approximately 300 players), till now 5 teams reaching the UMV+ stage and 10 teams at UV+. Even after best optimizations, the mspt can only be reduced to around 100ms. Certainly such a large server is rare, but smaller servers (with lower CPUs) can also face similar challenges, especially when the late game content is still expanding. Additionally, this idea aims to reduce excessive early or duplicate production lines (yes, i mean, LCRsssss!) so that more guys can enjoy the late game, but not to replace the Space Elevator or EOH. I'm also worried about whether DTPF should be in it...

This is exactly what the QFT does, it replaces
Silicone Rubber
Sty Bue
Polyphenylene sulfide
Rubber
PE
PVC
Polystyrene
PTFE
Epoxy
PBI
Platline
Thorium processing
Superglue
Advanced Glue
Indalloy
Soldering alloy
Bauxite/tungstate processing
Bee platline
Lanth Line
Mona Line
Naq Line, for all 3
Growth cat and cells
Bio cat and cells
Kevlar
Radox polymer
Xenoxene

There are not many more processing lines to replace, IMO if you have any in mind perhaps they can also be added to QFT.
but IMO a machine that replaces all of the automation that makes GTNH what it is is not good content.

**Comment by joshaup1999** [comment]
You need to tell your players to not build stupid bases like in the screenshots you have provided. If they learn how to properly use ae2 then you will gain a large amount of your ms back... This multi is just a bandaid on a solution and would make complex lines at late game useless when you just spam this one massive multiblock which is not a fun concept to me

**Comment by RealSilverMoon** [comment]
> You need to tell your players to not build stupid bases like in the screenshots you have provided. If they learn how to properly use ae2 then you will gain a large amount of your ms back... This multi is just a bandaid on a solution and would make complex lines at late game useless when you just spam this one massive multiblock which is not a fun concept to me

The screenshots are just meme. Haven't you seen this image during game startup? It was included in the better loading screen of GTNH. AE can't really save the late-game TPS if you've actually played on or run a 42-player server because these lags are actually caused by the TE machines themselves.

**Comment by RealSilverMoon** [comment]
This machine is in reworking for new texture and function now. Will open again when finished.
