### ISSUE TITLE
Singleblock Advanced Boiler [LV] - Incorrect Maximum steam storage - Waila Tooltip

### ISSUE THREAD

**Issue by ZephyrSparkFox** [GTNewHorizons/GT-New-Horizons-Modpack#13872]
### Your GTNH Discord Username

ZephyrSpark

### Your Pack Version

2.3.0

### Your Server

Self hosted multiplayer

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

The singleblock "Advanced Boiler [LV]" shows on its tooltip that it can hold 64,000mB of steam.
Under normal circumstances I would expect the block to be able to contain as much as it is displayed as holding.

### The Reality

 When the visual steam bar inside the GUI reaches maximum the tooltip is displaying close to 32,000mB and promptly vents steam as designed.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/137734138/a4d1493c-5f24-489b-83bb-223fa9e0485d)

### Your Proposal

Update the tooltip to show the proper maximum steam that the block can hold currently 32,000mB
Unless the block was designed to hold 64,000mB which then the actual storage of the block would need to be increased instead.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
I have been doing some testing and this holds true for all the advanced boilers, they will all assume that the water capacity is also steam capacity max.

They either dont respect `getSteamCapacity()` which I haven't been able to find a reason to or something is a little more broken. Commenting out 
```
if (mSteam.amount > getSteamCapacity()) {
            sendSound(SOUND_EVENT_LET_OFF_EXCESS_STEAM);

            mSteam.amount = getSteamCapacity();
        }
```
In the GT++ class also doesn't stop them venting their steam nor playing the sound. I'm probably missing something obvious somewhere though.
