### ISSUE TITLE
Parallels for higher tier precise prass

### ISSUE THREAD

**Issue by meepmopper** [GTNewHorizons/GT-New-Horizons-Modpack#13877]
### Your Pack Version

2.3.4

### Your Proposal

Add parallels and/or batchmode to precise mode prass. endgame crafts require 100ks of the circuits made in it and watching it 1 tick forever is painful. Another tier of prass casings would be nice for higher parallels as well.

### Your Goal

reduce prass 1 ticking and prass spam.

### Your Vision

I wouldn't be waiting on 1 ticking prass for hours.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment]
As for batch mode I already got a request for that from someone else. Will add it after https://github.com/GTNewHorizons/GT5-Unofficial/pull/2096 gets merged, because it makes it way easier. Might still take a few weeks though.

**Comment by chochem** [comment]
batch mode sounds good to improve performance. when we are talking about more parallels though we should rather find better late game solutions than buffing already powerful mid-tier stuff.
