### ISSUE TITLE
Bees to support Naquadah Fuel lines

### ISSUE THREAD

**Issue by fluffle** [GTNewHorizons/GT-New-Horizons-Modpack#13882]
### Your Pack Version

2.3.4

### Your Proposal

I would like a bee for at least:

- Tantalum (to make Bismuth Plasma)
   - 1152 phosphoric acid per 4 combs?
   -  Parents: aluminium + vibrant alloy?
- Infused Gold (to make Naq Fuel MkII)
    - 1152 Phthalic acid per 4 combs?
    - Parents: gold + haumea?
- Orundum (to make Naq Fuel MkIII+)
    - 2304 Phthalic acid per 4 combs?
    - Parents: tiberium + silicon? (matches the plate recipe, then also needs tiberium bee)

### Your Goal

It would be nice to know that I don't have to run VMs or the space elevator to have a stable power supply. Bees are a convenient way to generate a single resource passively in reasonable quantities, such that I can set them up and forget about them. These resources are not produced by any chains so they have to be mined.

Void Miners are too OP, after all ;-)

### Your Vision

These three resources in particular are not super convenient or efficient to get a consistent flow of, which makes the power chains based on them less suitable for long-term baseline generation usage. Adding bees would make life easier, so this is obviously a buff, but bees are also easy to gate appropriately.

I see bees are defined here:

https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/loaders/misc/GT_BeeDefinition.java

I'm happy to have a stab at doing this but ofc there's balance discussions etc to be had first.

@Runakai1 (lord of the bees)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Runakai1** [comment]
Tantalite can be gotten by one of the planet bees. 
Infused gold... Not sure why. But doesn't harm. 
Don't make naq fuel easy with bees now as it'll face the same fate as fusion then. Naq fuel is one of the few valid power gens left.

**Comment by chochem** [comment]
bees already make crazy amounts of useful stuff at this point. better leave some space for other resource production methods

**Comment by Runakai1** [comment]
> bees already make crazy amounts of useful stuff at this point. better leave some space for other resource production methods

Not a valid argument given that space elevator is already producing nearly every resource

**Comment by chochem** [comment]
'other thing bad too' does not invalidate the argument at all. We should continue to incentivize players to do more than just one thing. You shouldnt need *all* resource production options, but at least a few.

**Comment by Runakai1** [comment]
@fluffle I can see infused gold bee, preferably a centrifuge recipe but not the other two

**Comment by fluffle** [comment]
OK, that's better than nothing, thank you for considering it! Would you like me to have a go at putting together a PR? I found https://github.com/GTNewHorizons/GT5-Unofficial/pull/2058 which looks reasonable to cargo-cult from.

I 100% agree on Naq fuel being a great power gen option, but I have explored probably tens of thousands of chunks of Haumea looking for enough gold veins in proximity to make it worthwhile to shove down a miner. It is not fun gameplay at this point. Fluxed electrum is quite infused gold heavy, and you need a *lot* of it for MkII fuel. I think I've sunk nearly half a million infused gold dust into fuel in the past couple months...

The space elevator is almost too good -- it completely overwhelms my (ZPM era) ore processing. It also seems hugely wasteful to whitelist one or two ores that I actually need when it chews a whole bunch of power and resources to drill essentially at random. On the other hand I did manage to generate 250k infused gold in the space of a couple hours.

Void Miners have a similar, but opposite problem. Even on Haumea with xenon or oganesson the rate of infused gold generation is woefully slow, and yet there's still so much stuff that has to be voided. Having a bee that can target the resource shortfall directly is way more efficient, IMO.

**Comment by Runakai1** [comment]
Sure, have a try at making a new bee :) you can tag me on the discord preferably if you need help

**Comment by fluffle** [comment]
Fixed-ish by GTNewHorizons/GT5-Unofficial#2119.

I guess i'll have to rinse the space elevator for tiberium and orundum for MkIII+ fuels then :-)
