### ISSUE TITLE
Error in temperature and humidity required for beekeeping

### ISSUE THREAD

**Issue by FnTlv** [GTNewHorizons/GT-New-Horizons-Modpack#13880]
### Your Pack Version

2.3.4

### Your Server

pr

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

When I found the right temperature and humidity for beekeeping, he didn't work properly

### The Reality

It seems that the temperature and humidity system in the forestry industry is misaligned
Such as.
Waiting for the temperature to reach but showing cold
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/102719034/f20ed131-25c9-4f46-aa54-876394228ecd)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/102719034/605d854a-e628-4b80-9740-1d1fcfc4b0bd)

### Your Proposal

The temperature required for beekeeping has gone awry

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
Post the analyzed bee, showing its stats.

Here is exactly why your bee is not working:
1. A tropical bee needs a warm climate, not a normal climate. So it is too cold. Second, it needs a damp climate, not a arid climate, so it is too dry. 3. It will not work at night unless you have bred in that trait. 4. It will not work during the rain unless you bred that in as well. 5. It must have the correct flowers.

**Comment by desagas** [comment]
Temperature is based on biome, not based on time or anything else. A normal biome will never reach warm, without using something like an industrial apiary or alveary where you can change the climate in the hive itself!

**Comment by desagas** [comment]
If you want to learn how to mod, or not to use mods, I know the discord has a lot of information, but, a pack like FTB Academy will teach you all about them, including forestry.

**Comment by chochem** [comment]
I dont see any bug here. those wiki links are good, the help section of the discord is great too!
