### ISSUE TITLE
Give Hoppers full hitboxes when holding a wrench

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#13888]
### Your GTNH Discord Username

.querns

### Your Pack Version

2.3.4 plus some nightlies

### Your Proposal

The direction a hopper points at can be adjusted with a GT wrench. However, when the vanilla-style minimal hitbox was added that lets you reach things through the hopper's block space, it made it difficult to adjust the hopper with a wrench. Similar to how wires were changed, please increase the hitbox of the hopper to fill the entire block when holding a wrench.

### Your Goal

Slightly improves QoL for people who use hoppers in the early game. Or late game. I figure one is free to destroy their TPS as they choose.

### Your Vision

My people, they cry out for an infinitesimally easier hopper experience. As many as one person has pleaded, fervently, for this extremely important and not at all pointless change. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Rika-TH** [comment]
This sounds real nice, I tend to configure hoppers when toggling low end automation, also for removing them
Maybe full size on shift? As it'd still be nice to bypass them
