### ISSUE TITLE
Possible bug with Tungsten Trioxide Dust in the Electric Blast Furnace

### ISSUE THREAD

**Issue by OdinEidolon714** [GTNewHorizons/GT-New-Horizons-Modpack#13884]
### Your GTNH Discord Username

Odin Eidolon

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

I'm currenty plannig a production of tungsten ingots from end stone dust. At some point I need to transform Tungstic Acid Dust (H2WO4) in Tungsten Trioxide Dust (WO3) in the electrical blast furnace. It should give me water (H2O) as a byproduct as well. That water can be used to extract hydrogen to create Hydrochloric acid (HCl) for a previous chemical reaction so I can create a closed loop without the need of an external hydrogen production. I played enough with the modpack to see the logic of the various loop, for example in the titanium production, the intermediate products are all used to create more titanium in a closed loop.

### The Reality

The process to transform Tungstic Acid Dust (H2WO4) in Tungsten Trioxide Dust (WO3) in the electrical blast furnace doesn't give H2O at the end when it should. It just give Tungsten Trioxide Dust (WO3). I'm not an expert in chemistry but I know enough that matter should not disappear into nothingness just like it happen here. I even asked a fried who studied chemistry and He confirmed me that I should have water as byproduct.

Here's a link for the picture of the recipe
[https://i.imgur.com/i6JPxz6.png](url)

### Your Proposal

A simple fix for the recipe, so you get water or steam as byproduct.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
water can just evaporate, I dont see any chemical problem here

**Comment by chochem** [comment]
but if you want to add a steam output I am not going to stop you. Its a pretty minor thing and fine either way I would say.

**Comment by OdinEidolon714** [comment]
But a blast furnace has a way to collect fluids. There's plenty of other recipes with fluids that just evaporate and are collected in cells or hatch.

**Comment by BLocky104** [comment]
afaik, in a previous version, the hydrogen was actually in the recipe, but it was removed, due to it being unnescesary
