### ISSUE TITLE
Pam's fish can no longer be macerated into Minced Meat

### ISSUE THREAD

**Issue by fluffle** [GTNewHorizons/GT-New-Horizons-Modpack#13881]
### Your Pack Version

2.3.4 + extras

### Your Server

Personal MP

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

In 2.3.2 and before, I could happily feed the immense fish output of a Zhuhai into a macerator, for all my meaty needs.

### The Reality

Most types of Pam's fish no longer have a maceration recipe. The only one that does is Raw Walleye. This looks like the reverse of issue #5667, where a specific recipe for walleye was added.

I have to caveat this bug report with a few mod changes from 2.3.4. I fixed the GT++ mass fab multi to recycle correctly which forced me to upgrade from 2.3.2, and then additional mods needed to be updated (per https://gtnh.miraheze.org/wiki/Dev_Release_Stability) to fix the fluid recipe breakages, so this is rather a hacked up version. It is more than likely that mod version incompatibilities may be the source of my woes, but there are so many mods and I have no idea where this recipe might have once been created.

    GT-PlusPlus-1.9.39 -> GT-PlusPlus-1.9.49
    gregtech-5.09.43.84 -> gregtech-5.09.43.97
    modularui-1.1.10 -> modularui-1.1.12
    GTNewHorizonsCoreMod-2.1.50 GTNewHorizonsCoreMod-2.1.62

I figured it could be a coremod change but again nothing really jumps out. I can get by with voiding the trash, and technically crafting all the Pam's fish to Minecraft fish before macerating them still works, but I am guessing this recipe removal was not intentional.

### Your Proposal

Restore the listAllFishRaw -> mince meat macerator recipe, please?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
wtf, the code seems completely removed. why do I even fix this stuff if somebody just comes in with a sledgehammer and deletes everything! This is super frustrating.

**Comment by Dream-Master** [comment]
@chochem did you see which pr removed it ?

**Comment by fluffle** [comment]
Thank you <3
