### ISSUE TITLE
Enzyme recipe in Incubator broken

### ISSUE THREAD

**Issue by KhonaB** [GTNewHorizons/GT-New-Horizons-Modpack#13885]
### Your GTNH Discord Username

Khona Betwanhe#7122

### Your Pack Version

Nightly Build #45

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Trying to craft Enzyme from Sugar in an Incubator with Bacteria in the input tank and an empty output tank.

### The Reality

Output tank reports as full, despite containing no fluid. This persists across break-and-replace. Other recipes (including those that produce fluid) work normally.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12417837/88b117c5-c32c-4622-9988-3dad788f3587)

### Your Proposal

Fix the output tank check for the Enzyme recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TorvikW** [comment]
I'm having the same problem but with incubating larvae to drones instead on GTNH 2.3.5. I downgraded Binnie core to 2.1.5 and it fixed the bug.

**Comment by Dream-Master** [comment]
@minecraft7771 did this pr break stuff ? https://github.com/GTNewHorizons/Binnie/releases/tag/2.1.6

**Comment by nom457** [comment]
Same error when converting larvae to drone in incubator.

**Comment by minecraft7771** [comment]
> @minecraft7771 did this pr break stuff ? https://github.com/GTNewHorizons/Binnie/releases/tag/2.1.6

No the linked PR modified the shift-click method that is called when moving items between inventories.

**Comment by Quaerere-Git** [comment]
> > @minecraft7771 did this pr break stuff ? https://github.com/GTNewHorizons/Binnie/releases/tag/2.1.6
> 
> No the linked PR modified the shift-click method that is called when moving items between inventories.

Maybe the change in TransferRequest.java brokes the judgement of output tank :(

**Comment by nick-l-o3de** [comment]
fwiw, I'm affected by this too but in 2.4.0 - larvae placed in the incubator claim that they cannot incubate because the "output tank is full" (larvae do not produce fluids), so its definitely still active in 2.4.0.  Since genetically modifying larvae and then finally turning them back into drones is kind of the tip of the spear of the whole Genetics system, its a bit of a problem.

**Comment by Dream-Master** [comment]
@KhonaB can you test with this version?
https://github.com/GTNewHorizons/Binnie/releases/tag/2.2.0

**Comment by remyr** [comment]
Just to add a workaround for people who are on server and cannot upgrade/fix the bug, if you have a recipe and it say "tank is full", if you unload the chunk and reload, the recipe will be processed.

On official servers, I have a personal dim with incubators inside, if I leave the personal dim (which will un unloaded, without chunk loaders) and go back, the recipe work. But if I insert new recipe the bug is there.

**Comment by 847895947** [comment]
> @KhonaB 你可以测试这个版本吗？ [https://github.com/GTNewHorizons/Binnie/releases/tag/2.2.0 ](https://github.com/GTNewHorizons/Binnie/releases/tag/2.2.0)
When can I fix this problem?

**Comment by 847895947** [comment]
> @KhonaB 你可以测试这个版本吗？ [https://github.com/GTNewHorizons/Binnie/releases/tag/2.2.0 ](https://github.com/GTNewHorizons/Binnie/releases/tag/2.2.0)

When can I fix this problem?

**Comment by 847895947** [comment]
> @KhonaB 你可以测试这个版本吗？ [https://github.com/GTNewHorizons/Binnie/releases/tag/2.2.0 ](https://github.com/GTNewHorizons/Binnie/releases/tag/2.2.0)


May I ask when it can be repaired?

**Comment by Lyfts** [comment]
@847895947 Already fixed in the previously linked release.

**Comment by 847895947** [comment]
> @847895947 已经固定在以前链接释放。

2.4.0？

**Comment by 847895947** [comment]
> @847895947 已经固定在以前链接释放。

Restarting the server solved the problem
