### ISSUE TITLE
[Bartworks] Heated Fulvic Acid to Kerogene Recipe in PA (or LCR)

### ISSUE THREAD

**Issue by MMunier** [GTNewHorizons/GT-New-Horizons-Modpack#13896]
### Your GTNH Discord Username

MMunier

### Your Pack Version

2.3.0.0

### Your Server

Private

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

The Recipe works in a regular chemical reactor, so it should also work in 
1. the LCR
2. a PA of regular chemical reactors

### The Reality

It doesn't.
NEI doesn't even show a recipe for it in the LCR, however trying it in a PA also does nothing.
The fluid isn't even accepted by the input hatch. (Clicking with cells does work however)

### Your Proposal

The recipe should behave as expected.
The fluids should also be regularly listed in NEI, but thats a different issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
some recipes are singleblock only, thats not a bug per se. I dont know if there is a good reason for it here though

**Comment by Savallator** [comment]
I get that it does not have an LCR recipe, but it not working in a PA looks like a bug.
