### ISSUE TITLE
Multiblock machine overclocked incorrectly

### ISSUE THREAD

**Issue by homullily** [GTNewHorizons/GT-New-Horizons-Modpack#13892]
### Your GTNH Discord Username

homuhomu#9810

### Your Pack Version

2.3.4 nightly 2023-07-06

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When I ran a recipe for hv with a large chemical reactor equipped with one ev energy hatch, the machine should only overclock once

### The Reality

The large chemical reactor was overclocked twice，and I also found that other multiblock machines run with incorrect overclocking times
![Cache_-7bbc32c529b984f](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95575223/65551b6b-abfe-45d0-8324-d934b6c4bad1)
![Cache_-a2237bba820b84b](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95575223/a6e6df65-3e90-4bf3-948f-ef6e5315e2b3)

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I mean, you sure there isnt another energy hatch on there? any other. carefully double check please

**Comment by homullily** [comment]
> 我的意思是，你确定那里没有另一个能量舱口吗？任何其他。请仔细检查
I confirm that my large chemical reactor is only equipped with one energy hatch.

**Comment by homullily** [comment]
> 我的意思是，你确定那里没有另一个能量舱口吗？任何其他。请仔细检查

![{1C7C5E36-AD7A-4e79-BF0E-81C7CA1DAA6C}](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95575223/e279cb20-a027-4732-9016-068be5d0ef3c)

**Comment by chochem** [comment]
dont know what to tell you. works flawlessly on my end 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/35eda0eb-0f3a-442d-a3fe-7fccb1a84276)

**Comment by chochem** [comment]
what version of GT are you using?

**Comment by homullily** [comment]
> what version of GT are you using?

gregtech-5.09.43.112-pre

**Comment by chochem** [comment]
didnt see you said todays nightly, my bad. I guess it might be something from the last 3 days

**Comment by minecraft7771** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/commit/28bf67d88acb22cb043dc600d4f20b93a6d842a7
