### ISSUE TITLE
Painted Low Power Laser Converter is broken

### ISSUE THREAD

**Issue by reobf** [GTNewHorizons/GT-New-Horizons-Modpack#13899]
### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

1.Place a Low Power Laser Converter 
2.Paint it red with IC2 red painter 
3.Break it with GT wrench and pick up the block
4.Replace the block and switch it to receiving mode with GT soft hammer
5.Connect it to a laser source through laser pipe
6.It works fine

### The Reality

It generates a big explosion and destroys itself after step 5.

### Your Proposal

Fix it please.

More details:
Unpainted Laser Converter seems to work fine.
When a Converter is broken, 'Stored Energy', 'Stored EU' and 'Amp IO(max)' will drop to zero, which can be known via GT EU meter(see pictures below).
With 'Amp IO(max)'  dropping to zero, the power of Laser Source Hatch will always be greater than the Converter, so that might be the cause of the explosion.
![2023-07-08_23 22 50](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/117543727/93a6b895-d03c-45cc-96af-81b2263cf5b2)
before removing
![2023-07-08_23 23 02](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/117543727/b17e0ded-00d1-46ad-9751-3887b6b37010)
after replacing, Amp IO(max) is zero

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by antropod** [comment]
It seems that if you break painted laser converter its buffer sets to only 512 EU, maybe that is the issue
