### ISSUE TITLE
Day/Night cycle option in Personal Dimension

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#13897]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

2.3.4

### Your Proposal

I would like an option in the personal dimension to enable a Day/Night cycle similar to that of the overworld.

### Your Goal

I would like to be able to see light effects in the darkness as the world slowly changes to night time while in the personal dimension.

### Your Vision

Amazing dawn screenshots of lawn bases with the sun slowly setting would start to appear in the discord.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AlexeyZotov17** [comment]
Add a button when creating a personal world to turn on/off the day/night cycle
