### ISSUE TITLE
[GTNH]ArchaicFix+AE2U

### ISSUE THREAD

**Issue by mcmso** [GTNewHorizons/GT-New-Horizons-Modpack#13894]
### Your GTNH Discord Username

mc_mso

### Your Pack Version

2.3.0.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I hope you are compatible with ae2u and ArchaicFix

### The Reality

ArchaicFix+AE2U 
The server runs for  a lag problem

### Your Proposal

I hope you are compatible with ae2u and ArchaicFix
[https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/issues/317](url)
[https://github.com/embeddedt/ArchaicFix/issues/98](url)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BLocky104** [comment]
firstly, switch to the latest version 2.3.4 and see if the error still exists, it might already be fixed. 
if the bug is still existend in the latest version, please lmk

**Comment by chochem** [comment]
what exactly is the problem? archaicfix 0.5.0 works fine with any 2.3.x version of the pack including 2.3.0. I am using it myself. AE2 is always included anyways.
