### ISSUE TITLE
Delete the small dust recipe for Ta4HfC5 macerator recipe

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13891]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.4

### Your Proposal

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/ad60290b-8d05-4b99-8aa3-9535f26f26a7)
delete this recipe

### Your Goal

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/a44c9695-5b2a-494f-8314-9c0cd725817e)
so we can onlu get the nuggets with a pack of 9. there is no meaning to leave a small dust one. with this small dust recipe present, this recipe：
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/c525e37d-8c14-4239-8d11-b091c943b108)
gets mistaken as this
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/504f4601-4411-4d58-b63a-cb62f5289097)

### Your Vision

deleting it will make the automation smoother.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
also, why does that arc furnace recipe not give an ingot. Galaxy space is being sily

**Comment by miaowwwwww** [comment]
well, my guess is that someone added the "9 to 1" recipe to be more convenient, but there is a recipe conflict. (if we just make the arc furnace produce the ingot, that's way better too.)

**Comment by miaowwwwww** [comment]
and also, the inggot can't just go through alloy smelter to be ingot, I don't know if that's intended

**Comment by chochem** [comment]
the ingot cant be ingot?

**Comment by miaowwwwww** [comment]
Sry. Nuggets to ingot

**Comment by miaowwwwww** [comment]
Nuggets to ingot no
Nuggets to fluid to ingot yes
Nuggets to dust to ingot yes

**Comment by chochem** [comment]
well it sounds like I am about to make the nuggets irrelevant, so whatever
