### ISSUE TITLE
Add leaf multi block 

### ISSUE THREAD

**Issue by Dragondevi1** [GTNewHorizons/GT-New-Horizons-Modpack#13895]
### Your GTNH Discord Username

dragondevil

### Your Pack Version

Nightly # 29 or #30

### Your Proposal

I would like to suggest a multi block for leaves. In the game currently we have tree growth simulator but it does not give leaves. There are no other way other than manually grinding to get leaves. So I suggest a multi just like the tre growth simulator but the product be the trees leaves.

### Your Goal

Builders that want to build with leaves have an easy way to obtain them.

### Your Vision

The lead multi would help people build more nature into their builds 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EmeraldsEmerald** [comment]
just have a mode in TGS that can generate leaves (maybe with programmed circuit) lol

**Comment by MatttWasTaken** [comment]
Exactly that ^ easier then making whole new multi fot

**Comment by Dragondevi1** [comment]
I agree with that ^

**Comment by Savallator** [comment]
I think (not 100% sure) that you can put shears into a farming station to make it generate leafs. Might need a second one then for sapling generation though.
