### ISSUE TITLE
mytryl and mithril

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#13900]
### Your GTNH Discord Username

tom6482

### Your Pack Version

nightly

### Your Proposal

these two different materials are named in a way that it almost looks as if one is a typo of the other.
if they are different, can we have one of them to be called something slighly different? kinda how we have "neutronium" and "cosmic neutronium".
Also they don't have that many uses but both are required, so idk if merging them is an option.

### Your Goal

figuring out the correct way of typing "mythril", not even google is helping now.

### Your Vision

make the pack feel more consistent

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
dont think merging is an option. but renaming sure is. Any proposals?

**Comment by chochem** [comment]
also dont use google but open the original source. Tolkien spells it Mithril. Mith is gray (as in Mithrandir) and ril is glitter apparently. It's Sindarin.

**Comment by tommmmmmmmm** [comment]
i'd call one of the two "infused", like we have infused gold.

**Comment by EnderProyects** [comment]
Call the orange one Infused Mithril, and the purple one Meteoric Mithril

**Comment by desagas** [comment]
Can we also change "aluminum," bahahah. <- This was a joke. Sorry.
