### ISSUE TITLE
Locking recipe will lead to the chunk being unable to save

### ISSUE THREAD

**Issue by core-exe** [GTNewHorizons/GT-New-Horizons-Modpack#13908]
### Your GTNH Discord Username

core_exe

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When the LCR or other machine that enables recipe locking turns on recipe lock, the chunk should behave normally.

### The Reality

I have successfully reproduced it on a newly created world in 2.3.4, so it is not induced by porting.
There are a lot of Chinese characters, so I will try my best to describe what has happened.

We set up a valid LCR on a newly generated world, and give it some recipe to run. In this case, it is producing distilled water. It is behaving normally. Note that the recipe locking is not on yet.
![2023-07-11_00 02 05](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52733394/60bbd722-737e-43b3-bcd4-5dc2a3666aec)

Then, we make a pillar.
![2023-07-11_00 02 14](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52733394/b1084e00-9c96-4bca-a6db-a33c9b4f9f70)

We exit and re-entered the world. The pillar is still here.
![2023-07-11_00 03 06](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52733394/21efc8dc-dbfe-45f9-a7b6-065a5832e98a)

We turned on recipe locking, and make another pillar:
![2023-07-11_00 03 24](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52733394/5907b2cf-9754-4aad-988f-70af9ed5d44b)

We exit and re-entered the world, and all the changes has been reverted to the last re-enter, the new pillar is nowhere to be seen.
![2023-07-11_00 04 10](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52733394/764f32d2-ae86-4387-8b1f-dcd3c4197432)

### Your Proposal

I believe this is because recipe locking mess with some glitched nbt data, but i am not sure.
I also searched this issue here, but it seems not reported yet. When I tested out 2.3.3, this issue is also here.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2092
