### ISSUE TITLE
AE2 Timed Pattern Template

### ISSUE THREAD

**Issue by KhonaB** [GTNewHorizons/GT-New-Horizons-Modpack#13913]
### Your GTNH Discord Username

Khona Betwanhe#7122

### Your Pack Version

Nightly Build #50

### Your Proposal

Add a type of pattern (or a field in the pattern terminal) that sets a time limit on how long the associated crafting task is allowed to take. If the AE system does not receive the associated output item before the timer on that crafting task expires, the craft is considered to have failed, voiding all ingredients, and will re-request the ingredients for the task up to N times, with N also set through the pattern terminal, with 0 and infinity as allowed values. If the number of recrafts exceeds N, then it would automatically cancel the entire crafting task (logging the failure somehow so the player can see what went wrong).

### Your Goal

Currently, if a machine fails and voids items, AE will sit there waiting until the player comes and unsticks things. This is not ideal.

### Your Vision

This would allow for some level of fault-tolerance in large AE crafts and reduce the need for the player to babysit them. Moreover, it should be implementable without a huge overhead (assuming I understand how AE works) as it would basically consist of an extra field or two on patterns (or on a separate type of pattern) to track the user settings and as many timestamps as there are coprocessors on each crafting CPU, to keep track of when each sub craft has started.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
well AE2 is just a mean of interfacing machines for autocrafting. A base assumption when you do AE2 automation is that the automated machines are supposed to fully work. The reason you want to add such pattern is because you break that assumption. Why not fix your powergen issue instead?

**Comment by KhonaB** [comment]
Are there still percent-chance recipes that can't be easily avoided, or are all of those changed? If those are mostly circumventable, then nevermind I guess.

**Comment by chochem** [comment]
they have always been avoidable. I guess most people just passive or overproduce to overcome percentage based recipes, but you can also design a custom automation to do it if its critical or needs to be precise. Pretty much exactly the kind of automation you describe. the pattern itself is just the wrong place, do it after the pattern: timers, counters, a crafting card to reorder, ... its all doable.

**Comment by KhonaB** [comment]
Argh didn't even consider that aspect. Alright, thanks for the time though.
