### ISSUE TITLE
Hot Superconductor Base IV not registered under oredict card with description 'ingotHot'

### ISSUE THREAD

**Issue by AltyMan** [GTNewHorizons/GT-New-Horizons-Modpack#13914]
### Your GTNH Discord Username

alty2x

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I set up a system to autocraft stuff in the volcanus, which then moves automatically any requested hot ingots to the mega vacuum freezer I have set up, by using an oredict card on one of 2 storage busses (the higher priority one) in a subnet which then moves only the hot ingots to the vacuum freezer.

### The Reality

Specifically with this ingot, the hot ingot goes to the main net (which is the low priority storage bus), even though there is an oredict card with the label 'ingotHot' on a higher priority storage bus which moves it to another subnet that is hooked up to the vacuum freezer by using a stocking input bus with auto pull. This system works, as I tested this with both Energy Crystal and HSS-S and it works perfectly fine, just not Superconductor Base IV ingot for some reason.

### Your Proposal

Fix this by giving the ingot (and any other hot ingot that misses this) the oredic ingotHot properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AltyMan** [comment]
Adding an asterisk to the end of the oredic filter worked, not sure why/how it changed anything if without asterisk it worked for some stuff.

**Comment by TheEpicGamer274** [comment]
> Adding an asterisk to the end of the oredic filter worked, not sure why/how it changed anything if without asterisk it worked for some stuff.

its a wildcard meaning any hotIngot
