### ISSUE TITLE
Tier 2 Rocket Control Computer doesn't use EV Emitter and Sensor so is unlike all other RCC recipes

### ISSUE THREAD

**Issue by lewel-stamp** [GTNewHorizons/GT-New-Horizons-Modpack#13917]
### Your GTNH Discord Username

emc#1156

### Your Pack Version

2.3.0

### Your Proposal

Two EV Field Generators and a Tier 2 HD Plate seems weird, and out of scope. All other tiers of Rocket Control Computer utilize tier appropriate Emitter and Sensor. Tier 1 was HV Emitter and Sensor, and Tier 3 is IV Emitter and Sensor, and the tiers go on up like you might expect, but not Tier 2. I'd like to suggest Tier 2 be brought into line with the other tiers by replacing the EV Field Generator and HD Plate with above mentioned Emitter and Sensor.

### Your Goal

symmetry

### Your Vision

symmetry is beauty

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
thats intended

**Comment by lewel-stamp** [comment]
ouch

________________________________
