### ISSUE TITLE
Many recipes in 2.3.4 are wrong

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#13915]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.3.4-BETA

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Normal playing

### The Reality

1L refinary gas input multiple outputs.
![P V)9I~G}$((BR5WH2 MI92](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/77818313/395ab7b9-f4bd-4e28-b9f2-1b82d656e666)

Ender goo and liquid ender i/o reverse
![EJW}~%)X1JE7Z1FUL8A88{M](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/77818313/29218221-cf99-4537-8231-8524a809c72d)

No recipe for gravisuitchestplate
![M(UHU3YF93G5DV3DW$X4Q$U](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/77818313/721396fa-183d-4498-b647-e957f1eb9d2b)

### Your Proposal

Fix the recipes.
There is not only these recipes are wrong.

Actually many recipe of distillation tower are incorrect

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueWeabo** [comment]
It's fixed in dev

**Comment by BlueWeabo** [comment]
Wait. I am unsure about the ender goo one.

**Comment by BlueWeabo** [comment]
But the other two are fixed

**Comment by minecraft7771** [comment]
Ender goo fixed too.

**Comment by chochem** [comment]
please check out https://gtnh.miraheze.org/wiki/Dev_Release_Stability for the critical GT fix (a lot more recipes are broken). also has info and fix on gravichestplate. only endergoo I did later is not covered there as its not that easy to fix, you will need to wait for 2.3.5 there.
