### ISSUE TITLE
Logical crafting recipes (for gypsum and phosphoric acid)

### ISSUE THREAD

**Issue by Thor3005** [GTNewHorizons/GT-New-Horizons-Modpack#13911]
### Your GTNH Discord Username

Thor3005#8156

### Your Pack Version

2.3.4 java 8

### Your Proposal

A lack of two chemical recipes bugs me:
Sulfuric acid + Calcium = Hydrogen + Calcium sulfate (gypsum): literally the most basic chemistry can get, why isn't it possible? If, **by chance**, the reasoning is "would make blast furnaces too easy to obtain" then my response is you can make calcite from quicklime from ashes.
Phosphate + hydrogen = phosphoric acid: it seems really obvious, it's literally the constituent parts of phosphoric acid coming together.

While googling things for this suggestion, i came across sources stating that phosphoric acid is literally made by reacting phosphate minerals with sulfuric acid, leading to the formation of both calcium sulfate *AND* phosphoric acid. There's even a recipe like that in-game with apatite. The original reason i wanted to submit this issue was to be able to turn tricalcium phosphate (something found in rocks and in-game gotten from centrifuging pyrite) into phosphoric acid. Like genuinely all of this seems so blatantly obvious, and, as said, it bugs me.

### Your Goal

Make tricalcium phosphate useful as more than just mere fertilizer
Make gypsum easier to get so that primitive blast furnaces and steel production in LV are easier.

### Your Vision

More primitive blast furnaces
Another way of getting phosphoric acid because i know it's useful for something
Reason to centrifuge clean pyrite dust for phosphorus pentoxide because i love centrifuging
More chemistry

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
we have no plans to make bbf easier

**Comment by Thor3005** [comment]
> we have no plans to make bbf easier

but doesn't it sound logical that getting the bbf to **reach** LV would be difficult in order to make getting up a voltage not too easy but **during** LV getting more bbfs would be way easier when you're already set up in LV? If you don't want steel production in LV easy, at least add it as an MV thing, because merely the lack of the mentioned calcium sulfate recipe seems ridiculous.
