### ISSUE TITLE
creative spray paint

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13929]
### Your Pack Version

2.3.4 nightly 30(?)

### Your Proposal

add an infinite spray paint can for every color that costs a small amount of infinity. this makes it available a bit after you start spamming laser

### Your Goal

spray paint durability sucks compared to the amount of painting there is to be done and its annoying

### Your Vision

never refill a paint can again. everyone would love it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by MatttWasTaken** [comment]
I would love this

**Comment by ramseyspace** [comment]
I like the idea, I would love to make this happen

**Comment by Rika-TH** [comment]
Something like this would be awesome, some form of 1 slot multiple paints item with it too
