### ISSUE TITLE
Reedwater to whine 100:7 instead of 10:7

### ISSUE THREAD

**Issue by KhonaB** [GTNewHorizons/GT-New-Horizons-Modpack#13926]
### Your GTNH Discord Username

Khona Betwanhe#7122

### Your Pack Version

Nightly #50

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Reedwater to Whine recipe in the distillery should take 10 reedwater and produce 7 whine based on extrapolation from all other GT alcohol recipes.

### The Reality

100 reedwater is listed as the ingredient for 7 whine.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12417837/c7411ffc-390a-44fa-bece-e77b40ce7a71)

### Your Proposal

Remove (presumably) extraneous 0.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
from all I can see this looks intentional. what exactly are you even extrapolating here?

**Comment by KhonaB** [comment]
I am an idiot. Nevermind. Wine to vinegar is different, and this is a distillery recipe, not a fermenter recipe.
