### ISSUE TITLE
Ztone assembler recipes don't use oredict

### ISSUE THREAD

**Issue by 704009905** [GTNewHorizons/GT-New-Horizons-Modpack#13921]
### Your GTNH Discord Username

liselsiacesarini

### Your Pack Version

2.3.4 BETA

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11241929/be58e4ec-6d2e-483e-b26f-42d186982af8)
Ztone recipes like this should use oredict for dyes.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11241929/be58e4ec-6d2e-483e-b26f-42d186982af8)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11241929/8ef6a6cc-7eae-46e7-957d-aa064ed3bdcf)
These recipes only use light grey dye from vanilla, not gregtech chemical light grey dye. Not sure about other recipes since they usually don't need oredicts.

### Your Proposal

Add oredict support for such recipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eldrinn-Elantey** [comment]
I also think that this is necessary
