### ISSUE TITLE
Make Oxygen tanks prefilled 100%

### ISSUE THREAD

**Issue by ramseyspace** [GTNewHorizons/GT-New-Horizons-Modpack#13927]
### Your GTNH Discord Username

Ramsey#7916

### Your Pack Version

2.3.4 Beta

### Your Proposal

I make lots of infinite oxygen tanks for guests, so this recipe just doesnt make sense why its 11000/16000 to begin with
![Screenshot 2023-07-11 231729](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/61401431/e109d969-75f9-4ddc-a318-644ba05144ff)
It's frustrating when xtreme table requires full 100% oxygen tanks
![Screenshot 2023-07-11 232100](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/61401431/06e69ffc-3c9d-4fe2-859c-2a848fe0839e)
![Screenshot 2023-07-11 232229](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/61401431/783b6645-5607-4272-8f81-7df8ae20afa3)

or allow alternative recipe

### Your Goal

To make oxygen tanks 100% full when crafted

### Your Vision

This would stop the annoyance for automation for it. I believe this should be filled full especially when your UHV+

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by MatttWasTaken** [comment]
I second this request. I've refused to make creative oxygen tank as well purely out of spite of these tanks needing to be full, and encoding a tank into a oxygen compressor seems incredibly uncessary for a uhv craft

**Comment by chochem** [comment]
there is no oxygen in the crafting recipe, so they should be empty of course, not full or half-full.

**Comment by chochem** [comment]
was broken here it seems https://github.com/GTNewHorizons/Galacticraft/pull/20
