### ISSUE TITLE
Essentia Import/Export Bus 4 Acceleration Cards

### ISSUE THREAD

**Issue by AltyMan** [GTNewHorizons/GT-New-Horizons-Modpack#13928]
### Your GTNH Discord Username

alty2x

### Your Pack Version

2.3.4

### Your Proposal

Let these busses have 4 acceleration cards, as right now there is no nice way of getting/sending essentia fast enough into/out of the ME system, as the essentia provider is super bad throughput, and the busses are again limited to 2 accel cards

### Your Goal

To provide good extraction/throughput of essentia in the ME systems to multis that need lots of it

### Your Vision

To be able to use certain thaumcraft multis without worrying about how much essentia I provide them

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
> ### Your GTNH Discord Username
> alty2x
> 
> ### Your Pack Version
> 2.3.4
> 
> ### Your Proposal
> Let these busses have 4 acceleration cards, as right now there is no nice way of getting/sending essentia fast enough into/out of the ME system, as the essentia provider is super bad throughput, and the busses are again limited to 2 accel cards
> 
> ### Your Goal
> To provide good extraction/throughput of essentia in the ME systems to multis that need lots of it
> 
> ### Your Vision
> To be able to use certain thaumcraft multis without worrying about how much essentia I provide them
> 
> ### Final Checklist
> * [x]  I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying _I like this change please reconsider adding it_ will prompt us to investigate and reopen it once we confirm your report.
> * [x]  I understand this change request may not attract enough attention and thus not be implemented.
> * [x]  I understand this change request may be rejected due to other community members think it's inappropriate.
> * [x]  I believe this feature would make the pack better.

Yeah they genuinely aren't fast enough, and I swear to god they were able to take 4 back in 2.1.0.6b (the last time I used them)

**Comment by AltyMan** [comment]
Lesgooooo
