### ISSUE TITLE
Extreme inventory lag

### ISSUE THREAD

**Issue by mftgtg** [GTNewHorizons/GT-New-Horizons-Modpack#13933]
### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Opened inventory and searched for something. Expected it to have maximum 3 seconds of delay.

### The Reality

Game freezes completely while processing the search, in periods upward of 20 seconds. After the search is processed the game return to normal speeds.

### Your Proposal

Reduce lag caused by inventoy search.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
What are your PC specs.

**Comment by mftgtg** [comment]
12th Gen Intel(R) Core(TM) i7-12700F   2.10 GHz
16,0 GB RAM
359 GB of free space

**Comment by desagas** [comment]
I assume this is in the creative minecraft menu, rather than the NEI search? If so, this is common for almost every modpack ever. If someone could fix this, it would be awesome, but highly unlikely.

**Comment by serenibyss** [comment]
If it is creative menu, its a MC problem. It's been fixed in later versions though (at least 1.12+, unsure if earlier), so might have a potential fix in Hodgepodge one day?

**Comment by mftgtg** [comment]
Yes it is the creative menu search.
