### ISSUE TITLE
MK3 Fluid pump SE

### ISSUE THREAD

**Issue by ramseyspace** [GTNewHorizons/GT-New-Horizons-Modpack#13934]
### Your GTNH Discord Username

Ramsey#7916

### Your Pack Version

2.3.4 Beta

### Your Proposal

I wish mk3 was a thing to reduce Space Elevator spam to handle EOH, Allow it to x4 of the volume size. I would like it to be able to make it before t4 eoh, so you can make recipe cost white matter bolts or black. Thus would reduce chunk spam and overall load spam.

### Your Goal

To reduce SE spam

### Your Vision

A lot of end game players have to spam these SE and its looks abnormal

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by MatttWasTaken** [comment]
I second this. We are pretty much forcem to spam SE mk2 pumps in current state

**Comment by Hiagg** [comment]
i third this
