### ISSUE TITLE
TConstruct Bronze Pickaxe mining level upgrading method is unclear in quest book

### ISSUE THREAD

**Issue by Wacchi-Lorie** [GTNewHorizons/GT-New-Horizons-Modpack#13932]
### Your GTNH Discord Username

wacchi_lorie

### Your Pack Version

2.3.2

### Your Proposal

Bronze pickaxe mining level 'should' be tier-4 in unmodified game. GTNH modified it to tier-3 and says it could be upgrade to tier-4 in quest 'Making Better Tools #AAAAAAAAAAAAAAAAAAAAJg==' -> 'gather mining xp or use an upgrade slot'. I didn't found any way to use an upgrade slot to level up & it's bit to unclear about gathering mining xp. Precisely, you need to upgrade the pickaxe to lvl-2 or if your pickaxe is already lvl-3 or above, you'll need another one level of upgrade. I think these method should be included in quest book to prevent unwanted misunderstanding, since I spent lots of time browsering the quest book and googling,

### Your Goal

Add precise description of upgrading bronze pickaxe in quest 'Making Better Tools #AAAAAAAAAAAAAAAAAAAAJg==' in future vers

### Your Vision

Make quest and modified content easier to understand, reducing misunderstanding and unnecessary time spent on googling.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
sounds like the quest is correct. you start with 3 and either get mining xp or use an upgrade slot. getting lvl 2 or 3 has nothing to do with it, except for getting an upgrade slot
