### ISSUE TITLE
put the normal machine name in the tooltip of every tier singleblock

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13937]
### Your Pack Version

2.3.4 nightly (idk which)

### Your Proposal

title

### Your Goal

a lot of them have random name changes at certain tiers. macerator as an example, is lv-hv, ev, iv, luv-zpm, uv, uhv-umv

this is a horrible experience and it ends up making it so the only real way to find a machine of high tier is to check uses on the one you happen to know the name of and use the nei sidebar

### Your Vision

makes it less annoying and confusing to find high tier machines by allowing them to show up in search, while still keeping the sometimes interesting name changes for the tiers

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
clicking them in NEI is a horribly experience? that sounds a bit overdramatic.

**Comment by Connor-Colenso** [comment]
I would say just remove the weird names, we've discussed it before and that seemed agreeable but just no one actually did it. Wouldn't be hard.

**Comment by desagas** [comment]
Don't they all already state what category of machine they are? Or is this just a ++ thing?

And, Chochem is right, all you have to do is right click (in NEI) an item to craft and on the left hand side is a full column of every single machine or block that can craft the item, inclusive. So, if you already found one thing that can do it, but tier is an issue, it literally takes a single right click to find others that do the same, which is WAY FASTER than actually searching for them, and is significantly more accurate.

**Comment by Hiagg** [comment]
very few machines state their category currently in the tooltip which is why they dont show up in search with the rest of them. if colens for removing the weird names i am not opposed. could also put the strange names in the tooltip instead, reversing the currently requested order. there is no reason for it to be intentionally obtuse any longer

**Comment by xSkewer** [comment]
I'm not really sure I understand the push back on a simple QoL change like this. This has been a fairly common complaint in the past, and removing a minor inconvenience like this is always a plus.

**Comment by Gofer2x** [comment]
Eh, I'd say it's a good idea. It is slightly annoying if you wanna craft a, let's say IV Electrolyzer only for all the LV-ZPM tiers to show up except for IV. 

It's one of those things that's so minor if you're used to it you don't care, but it also should not be an issue in the first place (quality of life n all).

**Comment by Alrightsc** [comment]
Support this idea. It's annoying searching up machines after ZPM tier, and there's been cases where some are hidden/difficult to find and you have to specifically scrounge them (i.e uses of certain parts or checking catalysts). Worse case it saves a few seconds/clicks, best case it improves a lot of players' quality of life for a simple change.

Don't understand the elitist comments "just use NEI better" when clearly this is not even the case

**Comment by desagas** [comment]
"Elitist"? This is a highly advanced modpack made for users who have been playing hardcore modpacks for a long time. Elitist indeed ... but not as an insult like you just tried to state.

I support the idea of adding the category to all machines in GTNH.

But also, NEI
STEP 1: Search for electrolyzer.
STEP 2: right click electrolyzer.

That's it, it is literally that simple. Don't over complicate it! Once you have completed these literal 2 extremely simple steps, a full inclusive list of every single machine in the category of electrolyzers, inclusive, are listed here, with almost no exceptions, regardless of what the machine is called.

**Comment by Hiagg** [comment]
> But also, NEI
> STEP 1: Search for electrolyzer.
> STEP 2: right click electrolyzer.

> That's it, it is literally that simple. Don't over complicate it!

dont undercomplicate it either. electrolyzer specifically is step 1, search electrolyzer, step 2 right click, step 3 slide 5 tabs over to find the electrolyzer. but most other machines arent even on the first page of uses when you check a material recipe especially. saying this is a highly advanced modpack for advanced users isnt relevant at all. why have a quest book then to help new players? why give any QoL changes? sure we can do it. but we could do it better. also youre at pyrolyse oven tier you havent even run into the problem yet 💀 

also you advocated for multi handling void protections for you but THIS is where you draw the line? at least be consistent.

**Comment by xSkewer** [comment]
> "Elitist"? This is a highly advanced modpack made for advanced users who have been playing hardcore modpacks for a long time. Elitist indeed ... but not as an insult like you just tried to state.
> 
> I support the idea of adding the category to all machines in GTNH in NEI, but I do not support changing their names.
> 
> Above: "clearly this is not even the case ..."
> 
> ... ummm ...
> 
> But also, NEI STEP 1: Search for electrolyzer. STEP 2: right click electrolyzer.
> 
> That's it, it is literally that simple. Don't over complicate it! Once you have completed these literal 2 extremely simple steps, a full inclusive list of every single machine in the category of electrolyzers, inclusive, are listed here, with almost no exceptions, regardless of what the machine is called, whether it be 'electrolyzer' or 'monkey see monkey do.'

No need to be rude over a simple QoL change you disagree with. I don't really get why you're acting all high and mighty over this, considering everyone who is annoyed by this is also capable of doing the steps that you've outlined.

**Comment by desagas** [comment]
Oh, you're right, step three, click electrolyzer at the top of the page ... I used your example of the electrolyzer, I did not make up some set of steps, I simply did what you said was so complicated to do ... literally spell 'electrolyzer,' once, and click, 'twice.'

And, now you are really wrong ... I never supported void protection, not at all ... I think void protection is flawed, and I do not know why they added it. It provides support to players who do not know how to handle or builder systems that actually work. Never have I supported it ... and before you misquote me again, what I said was two fold: first, the latest comment of mine regarding the issue was THEIR system not working as implied. The second most recent comment was me saying: I do not support this, but go on ... that is not even related to this thread, so I will no longer reply to it.

@xSkewer , I was not rude, if literally quoting someone for insulting an entire community makes me rude, if showing someone the literal steps in how to solve their problem is rude, ... so be it, I guess I am rude. I was say 'direct' is a better word, but I was not rude.

**Comment by desagas** [comment]
I was not rude, I was giving a list. Second, @Hiagg was the one who called everyone who troubleshoots their experience with NEI 'elitist.' But, I digress. I support adding the category to the tool tips, and several are missing from the NEI lists, like the electrolyzer. I would suggest changing the issue name from 'put the normal machine name in the tooltip of every tier singleblock' to 'Multiblock machines missing from NEI Machine Categories.'

**Comment by Alastors** [comment]
The names are hardly an inconvenience, the names are a nice break from the humdrum of "hv centrifuge" or whatever, I suppose adding it to the tooltip though

**Comment by Alastors** [comment]
This should come down to a vote though

**Comment by MatttWasTaken** [comment]
Hey Elitists. I second the tooltip request🐝

**Comment by desagas** [comment]
@Alastors `the names are a nice break from the humdrum of "hv centrifuge" or whatever` I 100% agree!

**Comment by MatttWasTaken** [comment]
> 

Why thumbs down a fellow Elitists Elite opinion on this topic? Isnt that sort of harsh?

**Comment by GDCloudstrike** [comment]
Why not just add a line in the tooltip mentioning the machine type without changing the names? That solution would make nei search easier while keeping the names

**Comment by BritishCynic** [comment]
Easy way of solving this is by putting it to a vote on the Discord.

**Comment by desagas** [comment]
@MatttWasTaken

> Hey Elitists ... Elitists Elite

That is why ...

**Comment by Dragondevi1** [comment]
Yea just like multi blocks it would help when searching for machines.

**Comment by Alastors** [comment]
> Easy way of solving this is by putting it to a vote on the Discord.

a three way vote, 1 for no change, 2 for tooltip change, 3 for name change

**Comment by desagas** [comment]
@GDCloudstrike I 100% agree, Add the tool tip just like they exist for the multiblocks.

**Comment by MatttWasTaken** [comment]
Funny part is Clouds comment is literaly requoting the purpose of this entire ticket. So i dont get how you are arguing against it yet still agreeing with that 🥴

**Comment by chochem** [comment]
agreed that unique names can be nice and tooltips are a better place for that. I dont think anybody was actually against that in this thread.
Of course its a bunch of work for just a pretty small gain, but that just needs someone interested and motivated.

**Comment by BritishCynic** [comment]
> > Easy way of solving this is by putting it to a vote on the Discord.
> 
> a three way vote, 1 for no change, 2 for tooltip change, 3 for name change

Seconded

**Comment by desagas** [comment]
> Funny part is Clouds comment is literaly requoting the purpose of this entire ticket. So i dont get how you are arguing against it yet still agreeing with that 🥴

I'm not arguing against it, I am arguing against you using the words you are using in the fashion that you are using them.

**Comment by boubou19** [comment]
this will be renamed for the sake of consistency. Haters will just need to make a lang file custom

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2138 and https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/691
