### ISSUE TITLE
allow exporting crafting tree as PNG

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13935]
### Your Pack Version

2.3.4 nightly 58(?)

### Your Proposal

allow us to export crafting tree as png like journeymap can for its map

### Your Goal

currently even with the zoom out, end game recipes in crafting tree are kind of useless due to the scale and large horizontal scroll, with none of said tree being collapsible either. allowing export as png would at least make it possible to view the entire tree in a semi comfortable manner

### Your Vision

make crafting tree more betterer

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by greesyB** [comment]
Added by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/332
