### ISSUE TITLE
AE2 and IC2 crash

### ISSUE THREAD

**Issue by FnTlv** [GTNewHorizons/GT-New-Horizons-Modpack#13941]
### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Actions

I connect P2P Tunnel Redstone. ME Export Bus and ME Import Bus to Nuclear Reactor and Reactor Chamber. and then I broken the Nuclear Reactor and Reactor Chamber, the server closed. After the reboot, the error is generated every time the Chunk is loaded.like this.
https://youtu.be/gfb8sFmqcfE
But I can't reproduce it. Maybe it requires specific conditions.
How do I fix this?

### Crash Report

https://pastes.dev/K6hfXGFOHP

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by repo-alt** [comment]
Basically what's happening here: There is a reactor chamber in  the world w/o a reactor block. and an AE2 bus pointing to it. The bus tries to get an adjacent inventory which triggers reactor chamber checking for a reactor and not finding a reactor triggers a block update which leads to a loop. Essentially this situation is invalid and the chunk may be considered corrupted, fix it via external editor.

**Comment by FnTlv** [comment]
He seems to have something to do with Hodgepodge's fix for ic2. When I deleted Hodgepodge, the error did not occur. After a successful start, I rebooted and added Hodgepodge again, and the error didn't occur.

**Comment by repo-alt** [comment]
Indeed HodgePodge override in TileEntityReactorChamberElectric.getReactor does make the loop possible, but it is actually a dupe fix, and in a valid world that situation is not possible.
