### ISSUE TITLE
a button in ae2 pattern terminal to create very large recipes

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13946]
### Your Pack Version

2.3.4 nightly (idk which)

### Your Proposal

some way to easily create extreme pattern sizes in ae2. my proposed methods are either a separate button, or that when the "merge the same items" option is enabled, clicking (2x) or shift clicking (512x) the 2x button will instead keep them in the same item slot, allowing you to infinitely grow the pattern size. 

### Your Goal

this makes late/end game pattern creation much more streamlined to prevent lag and bottlenecks due to co processors.

### Your Vision

everyone would like this trust me

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by greesyB** [comment]
Is it ever desired anymore when doubling to limit stack size to <=127 and split stacks or should normal behavior be to double in place?

**Comment by joshaup1999** [comment]
I mean the other option is to middle click the item in the pattern then times it by however much you want. But a better refined setup to do it via the button is better sure

**Comment by Hiagg** [comment]
if item p2p, ME chest, or pushing directly into dual or otherwise interface are not limited by large stack size, then i think it would be safe to put it to default functionality.

**Comment by firenoo** [comment]
Sure that sounds fine, the button is old code and probably needs an update anyways
