### ISSUE TITLE
NEI Gregtech Pages Can Not be Interacted With

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#13954]
### Your GTNH Discord Username

Desagas

### Your Pack Version

Nightly 2023-07-13

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

When I click on items in the Gregtech NEI pages, it should cause an event / listener to trigger, updating. When I click on small or tiny dusts for uses, for example, it should update the tabs and displays, showing possible recipes, like it did in 2.3.4, but it no longer does. 

### The Reality

Gregtech NEI pages, all of the general ones: Lenses, Material Parts, Material Tools, Ore Processing and similar, while when hovering over items, it displays information, and they can be clicked on, there is no event that triggers when anything is clicked.

The machine tabs seem to be working perfectly, as far as I can tell.

### Your Proposal

Allow the content in the gregtech tabs to be interacted with again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Works with 2.3.70-GTNH, but broken in 2.3.73-GTNH. Looks like it's caused by https://github.com/GTNewHorizons/NotEnoughItems/pull/398

**Comment by desagas** [comment]
I love that new additional feature. REI for the win, but I am excited to see its full implementation!
