### ISSUE TITLE
buff component assembly time to 48x assline recipe time instead of 64x

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13953]
### Your Pack Version

2.3.4 nightly (idk which)

### Your Proposal

lower the recipe time

### Your Goal

coal spam is out of hand. the change to 64x recipe time means you either need power positive eoh or many many dysons to get decent speed out of only a few of them. i can think of 3 teams (mine, amp, and bee run), that have dozens of CoAL and are all planning more because its such a bottleneck (also 1 tick is slow. but thats another ticket)

### Your Vision

making the recipe time buffed vs assline would cut down a bit on the number required

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Runakai1** [comment]
Mega coal when

**Comment by JBadges** [comment]
wtf that aint amp run

**Comment by meepmopper** [comment]
you're mirin bruh

**Comment by meepmopper** [comment]
also coals just need parallels or better recipes :3 (so does literally everything endgame though).

**Comment by Eranicus** [comment]
I done know what is your problem, I got to my first T9 eoh with 5 CoaLs at 0.5T each and now I have 10 of them at 2T each (will add more if needed) 

This is not some kind of intermediary machine, but an endgame assembler for components, you just build more if needed. And it is perfectly fine without any changes , the only change / addition it needs is UXV component recipes added :)

**Comment by TheEpicGamer274** [comment]
> I done know what is your problem, I got to my first T9 eoh with 5 CoaLs at 0.5T each and now I have 10 of them at 2T each (will add more if needed)
> 
> This is not some kind of intermediary machine, but an endgame assembler for components, you just build more if needed. And it is perfectly fine without any changes , the only change / addition it needs is UXV component recipes added :)

UXV Components will not be happening, atleast not anytime soon

**Comment by meepmopper** [comment]
> I done know what is your problem, I got to my first T9 eoh with 5 CoaLs at 0.5T each and now I have 10 of them at 2T each (will add more if needed)
> 
> This is not some kind of intermediary machine, but an endgame assembler for components, you just build more if needed. And it is perfectly fine without any changes , the only change / addition it needs is UXV component recipes added :)

We have ~40 running at 8T each and they are still a major bottleneck in t9 eoh spam and stargate component crafts. Telling us to place more isn't very realistic. 

There is little point in a uxv coal as it would require a similar magnitude of uxv parts as a stargate.

**Comment by Hiagg** [comment]
@eranicus i dont think end game should be full of so much waiting. when the only solution to all the waiting is spamming the same machines, you run into the problems of lag and just bad gameplay in general. we're already at the point where someone with a bad pc cant play the current end game. i have a strong mid range pc and i struggle to keep decent tps with an almost entirely optimized base. changes need to be made i think :)

**Comment by Eranicus** [comment]
> @Eranicus i dont think end game should be full of so much waiting. when the only solution to all the waiting is spamming the same machines, you run into the problems of lag and just bad gameplay in general. we're already at the point where someone with a bad pc cant play the current end game. i have a strong mid range pc and i struggle to keep decent tps with an almost entirely optimized base. changes need to be made i think :)

well maybe its my slow playstyle because i dont like to rush things... I do agree with you regarding reducing lag on one hand but on the other hand things like t9 eoh's and stargate must require insane overall infrastructure,  but thats just my opinion...

**Comment by meepmopper** [comment]
> > @Eranicus i dont think end game should be full of so much waiting. when the only solution to all the waiting is spamming the same machines, you run into the problems of lag and just bad gameplay in general. we're already at the point where someone with a bad pc cant play the current end game. i have a strong mid range pc and i struggle to keep decent tps with an almost entirely optimized base. changes need to be made i think :)
> 
> well maybe its my slow playstyle because i dont like to rush things... I do agree with you regarding reducing lag on one hand but on the other hand things like t9 eoh's and stargate must require insane overall infrastructure, but thats just my opinion...

It is very hard to build any infra that can reasonably match a stargate's needs without waiting weeks/months for it to craft. We have ~1000 machines and crafts still feel slow due to the low number of parallels present in every machine. The only real power dumps endgame are aal and coal which become very unrealistic to oc past a certain amount and require tons of spam.
