### ISSUE TITLE
Recipe change for Centrifuge

### ISSUE THREAD

**Issue by Oculatus** [GTNewHorizons/GT-New-Horizons-Modpack#13951]
### Your GTNH Discord Username

Oculatus

### Your Pack Version

2.3.0

### Your Proposal

Centrifuge should use less electronic circuits, as the majority of other machines require only 2. I propose we change the recipe to have 2 less electronic circuits.

### Your Goal

A centrifuge is honestly a really simple machine in comparison to other machines. There are other machines that have the same concept of "spin thing" that only require 2 circuits. Most machines also only have 2 circuits and not 4, so the centrifuge feels like a sore thumb.
The circuits more so feel like filler for this recipe, not for complexity or gatekeeping reasons. I feel that the recipe needs to reflect more so of how it should work, like how the ore washers look pretty logical in their construction.

I would change the recipe to be like the following:
 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24788172/0382f16a-ba7f-4829-a450-511b5f16b4ed)

The plate acting as a lid/lock, the 3 glass acting as vials that could be where the dusts are seperated into (those could also be replaced with fluid cells, or reinforced glass for higher tiers), 2 motors to spin it all (keeping it in line with the original recipe of 2 motors) and then finally the machine block and 2 circuits.

Current recipe for reference:

![image (1)](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24788172/a30907f8-1069-4a4e-abc4-2af305ac13e3)

### Your Vision

This would help bring the centrifuge more in line with the other machines in the pack, and also help you visualize how the construction of the machine reflects how it would actually work, like most other GT machines do. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
i fail to see why it's an issue. 2 more circuits isn't much of an issue, you'll be forced to make a few stacks anyways

**Comment by Oculatus** [comment]
4 circuits implies complexity and processing power. But it just spin

**Comment by Dream-Master** [comment]
no please not any more recipes using glass. We play GTNh not a random vanilla pack.
