### ISSUE TITLE
Missing GT++ Dust Recipes

### ISSUE THREAD

**Issue by GelleSkelle** [GTNewHorizons/GT-New-Horizons-Modpack#13957]
### Your GTNH Discord Username

gelleskelle

### Your Pack Version

2.3.4

### Your Server

private

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

Trying to Craft the Volcanos Multiblock from GT++, can't craft the "Hastelloy-N".

### The Reality

Had no Recipe for this dust.
also following Dust i couldn't craft too:
* "Hastelloy-N"
* "Hastelloy-W" (Volcanos)
* "Maraging Steel 300 Dust" (various)
*  "Maraging Steel 350 Dust" (various)
* "Inconel-625 Dust" (IsaMill Grinding Machine)
* "Pikyonium 64B" (various high Tier stuff)
* "Watertight Steel" (Fishing Pond)
* "Zereon-100" (high current industrial arc furnance)
* "Lafium Compund Dust"

### Your Proposal

Make these Dusts craftable again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
yea because you make them in the Alloy Blast Smelter

**Comment by GelleSkelle** [comment]
Dumb, second page. embarrassed to the max...

**Comment by chochem** [comment]
not the first, wont be the last. at some point we will figure out the tech to bring it to first page :P
