### ISSUE TITLE
Can we remove material processing paradoxes?

### ISSUE THREAD

**Issue by FindMeSomeFun** [GTNewHorizons/GT-New-Horizons-Modpack#13959]
### Your GTNH Discord Username

FindMeSomeFun

### Your Pack Version

2.3.0

### Your Proposal

Remove material processing paradoxes like these:
"Look my friend, this is special alloy dust that needs a core of the star to be smelted into ingot, but after you get ingot you can toss it into your home oven to smelt it however you want!"

### Your Goal

Make specific tier materials to be processed in same+ tier machines.

### Your Vision

You got the point. This modpack is grindy enough so making it mandatory to use at least same tier machines for reprocessing as ones you need to make it would not make it more complicated and it would be logically consistent.
This one is really paradoxical.

Simply put: remove recipes that allow smelting/reprocessing high tier metal parts in a low tier machines. Make it tier consistent - reprocess in the same or higher tiers only.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I really dont know what you are talking about. could be almost anything

**Comment by FindMeSomeFun** [comment]
Concrete example:
Extremely Unstable Naquadah Ingot is made in ZPM EBF and cooled in LuV Freezer.
   = "Look my friend, this is special alloy dust that needs a core of the star to be smelted into ingot,
EUN Plate is made in LV machines and the same plate can be smelted back into Ingot using MC Furnance.
    = but after you get ingot you can toss it into your home oven to smelt it however you want!"

So it is paradoxically illogical.

**Comment by xSkewer** [comment]
This is the kind of change that makes sense in theory but in practice doesn't make the game any better. Retroactively changing all materials would take a lot of time to make sure overall processing times stay similar for the "benefit" of annoying players who like to take advantage of lower tier parallels.

**Comment by cainiaojun** [comment]
I think Colen had tried to nerf the tier of machines used to process materiels. Now you should process Infinity in a UV machine instead of LV, which makes players tired. Lategame players have to use a lot of GT++ machines or Processing Array with UEV+ machines, which is absolutely expensive and ineffective, to produce many materials.
The change you said is reasonible, but it would make players more annoyed.

**Comment by chochem** [comment]
> Concrete example: Extremely Unstable Naquadah Ingot is made in ZPM EBF and cooled in LuV Freezer. = "Look my friend, this is special alloy dust that needs a core of the star to be smelted into ingot, EUN Plate is made in LV machines and the same plate can be smelted back into Ingot using MC Furnance. = but after you get ingot you can toss it into your home oven to smelt it however you want!"
> 
> So it is paradoxically illogical.
> 
> Why is it so drastically hard to melt the dust but whole ass Plate (= ingot) is not a problem???

ah yea we have been starting to change that, well mostly Colen. and not same tier T but T-2. anyway this ticket is completely useless in its current state. I guess you have now mentioned exactly 1 (!) material we should adjust lol.

**Comment by boubou19** [comment]
tbh, aside from increasing the processing time, what does it bring to the game if it's fixed? what mechanic does it improve? I agree consistency is better and all, but sometimes, it is not worth the trouble gameplay wise.

**Comment by FindMeSomeFun** [comment]
Well many times while I was exploring new material possibilities usually among the first recipes that are shown are Furnace ones. When you see that parts of that material can be simply smelted in a simple Furnace it mislead you to think that you can make it right away, just need that dust. And after you plan it all to start production and get that dust you find out that you need to upgrade ton of machines and it simply demoralizes you.
