### ISSUE TITLE
Cannot Craft Hempcrete

### ISSUE THREAD

**Issue by Paada17** [GTNewHorizons/GT-New-Horizons-Modpack#13969]
### Your Pack Version

2.3.4

### Your Server

single player

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

tried to craft hempcrete powder with 8 sand and 1 wheat, shift click in crafting/ae2 says it recognizes sand but not the wheat. tried manually crafting but doesnt work

### The Reality

have all the materials but doesnt let me craft hempcrete powder

### Your Proposal

fix wheat to craft hempcrete powder

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TheEpicGamer274** [comment]
Should be fixed in dev.

**Comment by TheEpicGamer274** [comment]
Believe you have to update chisel/coremod

**Comment by chochem** [comment]
coremod really. if you can do that without dependency issues is a different question
