### ISSUE TITLE
Make odd recipes like 1:8 to conform to regular 1:9 ratio.

### ISSUE THREAD

**Issue by FindMeSomeFun** [GTNewHorizons/GT-New-Horizons-Modpack#13960]
### Your GTNH Discord Username

FindMeSomeFun

### Your Pack Version

2.3.0

### Your Proposal

Make odd recipes like: bolts, rounds, fine wires, etc to produce 9 instead of 8 items.

### Your Goal

In this way they can be easily reprocessed into nuggets/tiny dusts and later into ingots/dusts.

### Your Vision

A lot of time I am left with single or few mentioned items and cannot reprocess them in a useful way so I am forced to let them clog my inventory space or delete them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by S4mpsa** [comment]
This would have far-reaching consequences with very little gain, I don't think it's a good idea. The problem disappears with AE anyways.
