### ISSUE TITLE
Dual interface -> quad gt fluid pipe voids fluid

### ISSUE THREAD

**Issue by Sopel97** [GTNewHorizons/GT-New-Horizons-Modpack#13967]
### Your GTNH Discord Username

sopel__

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Fluid is not voided when pushed by a dual interface into a quad gt fluid pipe

### The Reality

I set up an LCR with a dual interface -> quad gt fluid pipe (stainless steel) -> quad input hatch (ev). When doing a larger batch (100k iron iii chloride) the pipe can't keep up and gets full. The craft never completes and residue fluid is left in the input hatch, signifying that quite a bit of fluid got voided. For now I replaced them with ender conduits and they work fine.

### Your Proposal

Fix either dual interface push or quad fluid pipe accepting fluid.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
Isn't it because the fluid flows from the pipe back into the interface?

**Comment by Sopel97** [comment]
Hmm, so setting a directional output on a pipe is not sufficient then? How to make it not slosh back?

**Comment by LazyFleshWasTaken** [comment]
You could have it go directly into the quad input hatch. Other than that, maybe a recipe buffer form which you then extract?
