### ISSUE TITLE
Hardened Conduit Facade recipe incorrect

### ISSUE THREAD

**Issue by LinoxGH** [GTNewHorizons/GT-New-Horizons-Modpack#13961]
### Your GTNH Discord Username

LinoxGH

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Trying to craft Hardened Conduit Facade with GT obsidian fluid.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/54643600/eaacf567-57ea-45b1-bd5b-8685039666e2)

### The Reality

No Hardened Conduit Facade was crafted and it required TC molten obsidian.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/54643600/017a79e4-5b57-4947-959e-9085714366f8)

### Your Proposal

Make the recipe only accept GT molten obsidian or both. This issue seem to occur in other molten obsidian related recipes as well.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I just checked and its fixedindev. was probably me tbh https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/653 but I dont recall.
