### ISSUE TITLE
Nei CMD+SHIFT+A not working

### ISSUE THREAD

**Issue by abulat189** [GTNewHorizons/GT-New-Horizons-Modpack#13976]
### Your GTNH Discord Username

abulat

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Being able to add the cool bookmarks by doing cmd+shift+a

### The Reality

Only the shif+a variant works unlike 2.3.2 where i got both working

### Your Proposal

map it back to cmd

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
When you say you got it working on 2.3.2, was that with java 8 or 17+?

**Comment by Abulat189** [comment]
java 8

**Comment by wlhlm** [comment]
Can you try running 2.3.4 under java 8 and let me know if that works?

**Comment by eigenraven** [comment]
Also please test Control+Shift+A, macos ctrl vs cmd mappings are not very consistently implemented

**Comment by Abulat189** [comment]
Control+Shift+A also doesn't work on 2.3.4 Java 20 but everything works the way it should on Java 8
