### ISSUE TITLE
remove gregtech requirement from witching gadgets

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/GT-New-Horizons-Modpack#13974]
### Your Pack Version

N/A

### Original Request

remove gregtech requirement from witching gadgets

### Responding developer

@alastorsgame

### Context

https://discord.com/channels/181078474394566657/603348502637969419/1130349341345849345

### Developer's Promise

Alastor's Game | Thaumic Dev — Today at 05:04
!tix it and I’ll try to have it fixed tomorrow

### Final Checklist

- [X] The developer in question has instructed me to create such an issue.
- [X] I believe the developer is not causally joking around.
- [X] I understand this reminder might take a long time to implement no matter what the developer has promised. (e.g. unforeseeable life difficulty, computer breakdowns, forgetting, laziness, etc)
- [X] I understand other people (developers or not) might not like this feature and would oppose its integration.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
Aight, I'll try to fix this in the morning, it's literally only one thing, so I'll just make it optional

**Comment by Abalieno** [comment]
There's Thaumic Bases as well with a similar problem, I think :)

And EMT, but that might be different...

**Comment by Abalieno** [comment]
Looks like this was forgotten :)

**Comment by chochem** [comment]
no its not. he is still working on it.

**Comment by Alastors** [comment]
> Looks like this was forgotten :)

Rude, no, I'm still working on it, but given that this is à labour of love and not something we get paid to do, it sometimes takes time, especially when irl things come up.

**Comment by Alastors** [comment]
If you really want an update on the change, it's a significantly bigger change than the original "I'll try to get it done tomorrow" because of how badly Bart bunged up this specific mod

**Comment by shadoxxhd** [comment]
Any progress? Is there something someone with no knowledge of the codebase could help with?
