### ISSUE TITLE
Universal Chemical Engine freeze server checking no more existing GTPP rocket fuel recipe sRocketFuel

### ISSUE THREAD

**Issue by Maxhy21** [GTNewHorizons/GT-New-Horizons-Modpack#13989]
### Your GTNH Discord Username

Largerthan2#3231

### Your Pack Version

2.3.2

### Your Server

private sever

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Pouring GTPP purple rocket fuel into UCFE.

If rocket fuel is intended to be banned from UCEF, then nothing should happpen.
If rocket fuel still working, it accept all fuel in input hatch

### The Reality

Sever spamming thousands of such logs, eventually kick every player with time out.
![D868@O2Y8M_@{XO{N)OMW2H](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/35527077/6b859cd1-9d79-4339-959f-0daf7ce92892)

### Your Proposal

Fix UCEF from try to use rocket fuel
or fix GTPP broken fuel api

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
the class exists and it also works perfectly fine for me. curious.

**Comment by Maxhy21** [comment]
GT-PlusPlus-1.8.18
GoodGenerator-0.5.4

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GoodGenerator/commit/8bdf6bf27fc17658e56b11bca0e7af7439a1f1b5 which is not included in 2.3.2
