### ISSUE TITLE
Remove All the Ashes in the Recipe of Electical Implosion Compressor

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#13988]
### Your GTNH Discord Username

cainiaojun

### Your Pack Version

2.3.4

### Your Proposal

Remove all the ashes and dark ashes in the recipe of Electical Implosion Compressor, like the recipe of Compressed Plates, Flawless and Exquisite Jewels, etc.

### Your Goal

The Electrical Implosion Compressor doesn't use any iTNT but produce ashes just like in the common Implosion Compressor with iTNT.

### Your Vision

Make recipes more reasonable, and save players' AE storage room.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by desagas** [comment]
Wouldn't ashes be considered the flux of the operation? It has nothing to do with the TNT being used. I know so many things are not as 'real' as we want them to be, but in this case, it is fairly accurate, if you heat up an ingot of iron or carbon or diamond to compress, using electricity or coal or whatever to press it in whatever manner, in real life, there will still be flux that comes off of it. Unless it is done in a completely "clean" environment from the original mining of the gems or metals until the final compression, which is nearly impossible.
