### ISSUE TITLE
buff the research completer

### ISSUE THREAD

**Issue by jevry** [GTNewHorizons/GT-New-Horizons-Modpack#13996]
### Your GTNH Discord Username

TheMightyJevry

### Your Pack Version

2.3.2

### Your Proposal

The research completer is a machine that is supposed to ease the burden of the extensive amount of research puzzles that need to be done to work through the thaumcraft mod, however in its current state it merely replaces the chore of doing 1000 researches with the chore of obtaining 1000 thaumcraft nodes to feed to the machine. As such it isn't a machine considered worth using. When i tested the machine on 1 EV amp, the node i used was destroyed after 20 seconds, meanwhile a single research takes 15 seconds, and the second research i inserted was destroyed. considering the fact that nodes cant really be automatically moved, the machine meant to automate a process instead needs to be watched constantly.

there are a few ways the research completer can be buffed:
-0 blatantly disable the mechanic that destroys the nodes
-1 simply increase the time a node survives from long enough to finish 1, maybe 2 researches, to long enough to finish 50 or 100
-2 add a way to keep the node alive or change the costs of the research completer, this could be with alternate costs like feeding it centivis or essentia. (i personally like the essentia idea)

To counterbalance the buff in cost, the research completer could (and probably should) be nerfed in its speed, from 20 seconds at EV to maybe 500 seconds or more. this way it's still beneficial to also do manual research if you're in a hurry, or to passively let a good amount of your research get completed while you're doing other things in the modpack

Additionally, a node being destroyed should not void the research paper in the machine, as the paper has no real value besides orderlyness. If for example one wanted to do every single non-forbidden research open to them, having some of them destroyed would have them require re-finding the destroyed papers

### Your Goal

After seeing the 100th thaumcraft research puzzle, you've seen all the thaumcraft research puzzles: spam ordo and instrumentum, convert to other essentia types where applicable, and move on. it doesnt help that a lot of the researches unlock unexciting stuff, like a less efficient way to make balanced shards, or.... banners.
The research completer should be in a usable and worthwhile state, to offer players a method to automate a monotonous process, while not invalidating manual research as soon as the player has access to the research completer.

### Your Vision

The research completer would offer an alternative to the monotonous grind of thaumcraft puzzles, and allow people to do other stuff in the pack. However it would still be an incredibly slow process, and  encourage reserving its usage only for low-priority researches like void-putty (which does nothing), banners, the entire golem tree and doors can however be fed to the research-completer. meanwhile players can manually do the high-priority researches like void metal and ichorium

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
empowering bees are a thing btw

**Comment by chochem** [comment]
the research completer doesnt eat nodes. It drains them. Which is _major_ difference that you can and should use to your advantage.

**Comment by Maxhy21** [comment]
> the research completer doesnt eat nodes. It drains them. Which is _major_ difference that you can and should use to your advantage.

drain 63 aspects every 10s for every 6 aspects note make no difference from eating a node, even bright hungry node take hours of feeding to be just able to survive a few minutes. The only practical way to use this machine is spaming WA bees.

**Comment by Alastors** [comment]
> empowering bees are a thing btw

I'm just going to say, if bees are required for something to not be shit, then it's still shit, bees and crops should never be the only way something is viable

**Comment by Alastors** [comment]
> the research completer doesnt eat nodes. It drains them. Which is _major_ difference that you can and should use to your advantage.

the difference is that draining nodes to 0 has a high chance of damaging them, if the research completer doesn't already, it should only reduce the nodes to 1 max, like how the non-iron/stick wand does

**Comment by jevry** [comment]
> > the research completer doesnt eat nodes. It drains them. Which is _major_ difference that you can and should use to your advantage.
> 
> the difference is that draining nodes to 0 has a high chance of damaging them, if the research completer doesn't already, it should only reduce the nodes to 1 max, like how the non-iron/stick wand does

I will double check this later today, but i am 99% conident the completer destroys by draining to 0, and then continues draining for damage instead

**Comment by chochem** [comment]
exactly, it drains. so all you need to do is make sure it keeps up.

**Comment by Reflex18** [comment]
What if the mutiblock had a stablising effect in it that stopped nearby nodes from eating themselves?

That would lead into the expandability of the machine setup and encourage players to expand it to add in more nodes. More nodes would mean more research being able to be completed at a time before taking a break to let the nodes recharge.

**Comment by jevry** [comment]
> empowering bees are a thing btw

And yes the reason i didnt even consider the possibility of using bees in the suggestion is because while i havent tried them yet, i dont think they are able to feed a node anywhere near the speed that a conpleter destroys them at. It would need to reliably gain 6.3 aspect of a single type per second to be sustainable. It would probably be possible with 100s of apiaries and 100s of princesses, and at that point its probably too much of an investment to justify not doing the researches manually

**Comment by chochem** [comment]
this really is more help-chat than github ticket at this point, but yes bees very much can keep up. Iirc EV acceleration with a single bee is enough.

ah yes, found Runa talking about it https://discord.com/channels/181078474394566657/1058353193949601792/1107265276275343370

**Comment by jevry** [comment]
> > the research completer doesnt eat nodes. It drains them. Which is _major_ difference that you can and should use to your advantage.
> 
> the difference is that draining nodes to 0 has a high chance of damaging them, if the research completer doesn't already, it should only reduce the nodes to 1 max, like how the non-iron/stick wand does

just wanted to add that, after testing with some world-accelerated bees, I noticed that the research completer does indeed drain to 0, and the node does receive the associated damage from having 0 of a vis type. and it drains from 1 type at a time untill it reaches 0, even if other types are available

**Comment by Maxhy21** [comment]
I also tested 3x3xn size researcher which allow multiple nodes inside to be drained. The controller with only drian 2nd node if 1st is fully destroyed, so it is just a larger buffer to eat nodes.
