### ISSUE TITLE
Rutile via Andradite should be rebuffed.

### ISSUE THREAD

**Issue by Eysla** [GTNewHorizons/GT-New-Horizons-Modpack#13995]
### Your GTNH Discord Username

sovy

### Your Pack Version

2.3.4

### Your Proposal

Andradite is an ore that can be found in the OW scarcely (40 weight, only spawns between y = 150-200) for pre-moon titanium for those that want to do challange runs that include avoiding other dimensions. Its viability for titanium pre-moon has been reduced by 300% as a result of changes to the amount of rutile required to produce titanium tetrachloride. (https://github.com/GTNewHorizons/GT5-Unofficial/pull/1927) The %chance of receiving rutile from centrifuging andradite should be increased from 2% to 6% to make up for this accidental nerf.

### Your Goal

Achieving rutile before rocket should be difficult to obtain in significant amounts, so as to encourage players to explore space/planets. Although, there is a history of support for making challenge runs possible without degrading the experience of playing the normal pack. The most reliable way of obtaining andradite is centrifuging yellow garnet that is obtained via garnydinia (IC2 Crop). The investment in infrastructure to obtain, process, and refine rutile from andradite is more than sufficient and did not need to be nerfed. Especially since it was nerfed completely unknowingly.

### Your Vision

The %chance of obtaining rutile dust from centrifuging andradite is changed from 2% to 6% to return it to its previous yield before https://github.com/GTNewHorizons/GT5-Unofficial/pull/1927 indirectly nerfed it.

Incidently, this also is a 300% nerf to all other sources of rutile with the intent to make titanium with it. Nerfing something this much does not seem fair without first having a discussion, **of which there was none**, on whether obtaining rutile from other means (specifically pre-moon ones) should be nerfed. There are much, much easier ways to obtain rutile pre-moon that are effected, as everything except bauxite and ilmenite are, that definitely could be tuned before andradite.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
was done (even if I dont like it :P), see linked PR.
