### ISSUE TITLE
Golemancer's Bell_TH crash on use

### ISSUE THREAD

**Issue by KhonaB** [GTNewHorizons/GT-New-Horizons-Modpack#13999]
### Your GTNH Discord Username

Khona Betwanhe#7122

### Your Pack Version

Nightly 50

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

Place a Thaumium Golem with a Golem Animation Core (Alchemy), spawn or craft an unused Golemancer's Bell_TH, and right click on any solid block without first selecting the golem. The game will crash to the crash report screen. This is confirmed to occur also in version 2.3.4.

### Crash Report

https://mclo.gs/ntSL30I

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alastors** [comment]
does this occur in stable as well? I kind of need to know if this was one of ours, or a historical issue lmfao, I'll figure it out either way

**Comment by KhonaB** [comment]
Not sure, someone else on Discord was on stable and tried it without causing a crash, but there wasn't a golem in the world at the time, as we hadn't yet figured out entirely how to reproduce it.

Also, not sure if this was new/a bug at all, but the vanilla bell appears uncraftable? I had thought the alternate recipe was just supposed to give the vanilla bell, not the TH alternative.

**Comment by Glease** [comment]
Looks like a bug with the hodgepodge golemancer bell patch. Let's just remove the patch as it exists in TC4Tweaks. I did check my code for this problem as well. It simply doesn't exist in TC4Tweaks version, since my code doesn't really use the same patching strategy.
