### ISSUE TITLE
VP Ore bug on Server

### ISSUE THREAD

**Issue by JBadges** [GTNewHorizons/GT-New-Horizons-Modpack#13992]
### Your GTNH Discord Username

chadges

### Your Pack Version

GTNH Nightly build 2023-07-17+61

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

![singleplayer](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7453013/9d1b22f3-89f5-4fb0-bd44-e075ef1bb545)

This image is a screenshot from a singleplayer world of identical seed. It does not match the visual prospecting done from orewand on the server. The server world is created with the same seed, it was not copy pasted from single player. Both client and server on graal Java 17

### The Reality

![server](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7453013/376e2670-ac74-4934-9eca-1967fe39e2fe)

This is what was shown in single player which marks the ores correctly.

"I left server, joined singleplayer with same seed prospector scanned like hundreds of ores with that 17x17 one, joined back to server and my map changed a bit I guess
i didnt even punch any of those copper ores (on the server) and my ore finder wand was empty"
below is server journey map after doing the above in quotes
![server2](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7453013/478a0aad-e821-48f3-8a02-756cfcb27376)

### Your Proposal

fix please 😸 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by JBadges** [comment]
I guess I should have been more specific in the ticket but this is all fresh gen. No mod changes nothing, that exact nightly version fresh gen on both single player and server

**Comment by JBadges** [comment]
Update: my map has just reverted back to the original screenshot that has the incorrect ore locations. I restarted my PC but not sure if only a game restart would also cause it

**Comment by JBadges** [comment]
Just joining the singleplayer world mentioned early and going back to server seems to have fixed the journeymap VP

**Comment by glowredman** [comment]
@JBadges Could you try this GT version? It needs to be on server and client.

http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/6158/artifact/build/libs/gregtech-5.09.43.141-fix-wrong-oregenpattern-on-servers.2+d212a0612c-dirty.jar

**Comment by JBadges** [comment]
Two main updates
- I tested with one ore vein near my base that was originally incorrectly marked. It is now marked correctly (same as the single player world)
- On first launch of server world, all of my previous vein markings are completely gone except for two coal veins. After logging out of server and back in all veins reappeared. They seem to be in the correct spots.

If I run into any issues or bugs ill update.
