### ISSUE TITLE
"Wooden door" quest marks itself complete before I actually craft a door

### ISSUE THREAD

**Issue by dgealow** [GTNewHorizons/GT-New-Horizons-Modpack#13993]
### Your GTNH Discord Username

@droideka30

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Unlocked the "wooden door" quest, and started crafting, expecting to see the incremental components pop up as complete in the "optional" part of the quest.

### The Reality

The components didn't show up--I realized this was because the overall quest was already showing as "complete" and waiting for me to choose a reward. I suspect this is because a completion flag of some sort was set when I received the free wooden door as my reward for an earlier quest.

### Your Proposal

~~Either change the logic to only complete quest steps once they are visible in the quest book (probably harder), or~~ (Edit: not actually the issue; see discussion below) 

Make this a "craft" task rather than an "obtain" task.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
ah yes, the quest directly before it gives it as a reward :P

**Comment by dgealow** [comment]
Oh so my first suggestion wouldn't actually solve the issue--the quest *is* unlocked by the time you get the reward door. Then yeah making it a crafting quest would do it.

**Comment by chochem** [comment]
ah no actually, my bad. its the quest after (pressure plate) - I got confused by the order there.

**Comment by chochem** [comment]
ah, but the bed quest has one

**Comment by chochem** [comment]
we can just set lockedprogress to false. then you can only work on it when unlocked.
