### ISSUE TITLE
Adding endgame ores to high-tier mining drones

### ISSUE THREAD

**Issue by Mystical4444** [GTNewHorizons/GT-New-Horizons-Modpack#14007]
### Your GTNH Discord Username

_mystical

### Your Pack Version

2.3.4

### Your Proposal

Add more/new ores to the UMV and UXV mining drones for materials that are painful to get, such as 
-Tritanium, 
-Astral Titanium, 
-Pure Tengam,
-Sunnarium and 
-Chaos Shards (As an extremely rare case, similar to draconic cores in earlier drones).

I want to highlight that if the UIV drone would have Platline, it would be fine in my eyes, but it is too cheap for the above mentioned ores to be obtainable through that drone.

### Your Goal

The UIV, UMV and UXV Drones (Mk-XI, Mk-XII, Mk-XIII) are too expensive to maintain to get any reasonable value out of them. The UEV (Mk-X) does the same, in (negligibly) smaller quantities (has SE platline though, higher ones **_do not_**), but is much easier to maintain and hence is the best choice for a SE mining setup.

### Your Vision

I believe that through these changes, UIV, UMV and UXV drones would have a genuine use that endgame players would likely want to invest in, since these materials are quite scarce. Materials such as tritanium or astral titanium are very painful to get in endgame and I believe that the cost of these drones' mining operations (infinity and transcendental metal) would be justified to obtain those ores.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Mystical4444** [comment]
If I remember correctly it was stated that Skyblock cannot be completed without an alternative way to get Chaos Shards, so this is one of the most reasonable ways i see fit to solve this issue.

**Comment by minecraft7771** [comment]
Yes their intention was to be able to mine high tier ores, it's just that no one got around to adding them yet. I also would be in favor in adding chaos shards to a high enough drone to enable skyblock runs to get them.

**Comment by cainiaojun** [comment]
And if it is possible:
 - Infinity, for UMV or UXV players to skip the slowest DTPF in the world.
 - Celestial Tungsten. Although players have got many Celestial Tungsten in the painful Transcendent Metal prosessing, I think players are happy to see more.
 - Terrasteel. No more Botania!
 - Duranium. If we can mine Tritanium instantly, why not Duranium?

**Comment by Mystical4444** [comment]
@cainiaojun 

I doubt infinity will be necessary, its not slow at all for me and never way

Celestial tungsten already is imo good enough with smelting and the new dtpf stellar recipe

Terrasteel I agree could be added, but i haven't seen any main prog use for it.

Duranium is kinda useless, i don't use it much and since Tritanium was added to EOH, i doubt there'll be a use for Duranium in the future. Although it would still be great to see Tritanium in the SE until you can get to EOH.

**Comment by Connor-Colenso** [comment]
Generally at this tier I oppose adding new ores, it's been done to death. New systems to generate resources should be the go to, not crap like ichorium ore.

**Comment by Mystical4444** [comment]
I agree that there are a lot of ores to stuff that is usually made in complex ways beforehand. 

The main reason i opened this issue was to highlight and suggest materials that could be added to the UIV-UXV drones, which have absolutely 0 usage and could extend the wasteland of content that is UEV to Stargate, even if its just a little bit, its something. 

Since Tritanium was added to EOH, i doubt there will be a shortage for anyone needing massive quantities of tritanium, so thats one of my main intentions with this issue gone.
