### ISSUE TITLE
Game crashes when loading world exception from EnderStorage

### ISSUE THREAD

**Issue by BinganHe** [GTNewHorizons/GT-New-Horizons-Modpack#14009]
### Your GTNH Discord Username

binganhe

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

trying to load world

### Crash Report

tried removing enderstorage and got a different exception
[latest_with_enderstorage.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12113000/latest_with_enderstorage.log)
[latest_no_enderstorage.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12113001/latest_no_enderstorage.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
looks like chunk corruption to me. probably best to use a backup

**Comment by BinganHe** [comment]
For some reason my backups are fucked and this is now my only copy of my world

**Comment by BinganHe** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/90933174/56e84cb6-e2b8-494c-8121-1c43a52554c1)
there is indeed a corrupted chunk but the program i used (https://github.com/Fenixin/Minecraft-Region-Fixer) diesnt see it as corrupted just "wrong" and didn't do anything with the chunk

**Comment by BinganHe** [comment]
I was able to delete the wrong located chunk with the before mentioned tool but it still crashes. I'm far from an expert in fixing corrupted mc worlds so please help.
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12123673/latest.log)
