### ISSUE TITLE
visualprospecting nodes

### ISSUE THREAD

**Issue by konvaa** [GTNewHorizons/GT-New-Horizons-Modpack#14004]
### Your GTNH Discord Username

konva#9953

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

I got blue death screen and world got corrupted. So I manually extracted the archive and override all files. When i reentered game, i see waypoints are fine, but prospected nodes went missing. Really no clue how to fix that, so i tried to copy datafiles from: minecraft\visualprospecting\server\13_370b72f5-75d1-4814-89c7-a40edebd4f70\ore    to: .minecraft\visualprospecting\client\konva_d0c92aa5-6a52-4574-9aa3-c59e99fc22ba\13_370b72f5-75d1-4814-89c7-a40edebd4f70\ore
Expected to see only veins previously explored, something around the marked screenshot. 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12657169/159cc292-ef6a-44c0-9795-d736aa28c592)

### The Reality

It shows all nodes existing in explored areas + something more
![2023-07-20_13 31 25](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12657169/866215e6-4393-4087-b860-6808d40ec625)
![2023-07-20_13 38 17](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12657169/12873d27-2509-4787-8623-e82b26b702b2)
![2023-07-20_13 38 20](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12657169/a4abed97-70ae-4a97-afd2-dd616c6dc861)
![2023-07-20_13 38 22](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12657169/895164a2-e388-4930-ac7a-55fdb2568a1b)
![2023-07-20_13 38 25](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12657169/293b3fa1-b29f-4b5d-8d8d-42a6ae2fc2db)

### Your Proposal

Dont know

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kumquat-ir** [comment]
That's because you copied the server-side cache to where the client-side cache should be. The server's cache contains every single generated ore vein, which is what you are seeing there. The client's cache is what has only the veins you prospected.

**Comment by konvaa** [comment]
Okay, then how was I supposed to restore visualprospecting correctly?
