### ISSUE TITLE
Change default keybind for CraftPresence config GUI

### ISSUE THREAD

**Issue by wlhlm** [GTNewHorizons/GT-New-Horizons-Modpack#14006]
### Your Pack Version

nightly 2023-07-09 no. 50

### Your Proposal

Currently, the CraftPresence config GUI is bound to the same key as the questbook (<code>`</code> on a US keyboard, the top left key in the alphanumeric cluster).

I'm not a CraftPresence user, but I think the config GUI is only rarely needed and should be moved further down the keyboard (possibly even the numpad). Alternatively, we could ask the mod author if they are willing to add a command for the config gui (similar to `/igi config`) so that we can forgo setting a keybind at all.

### Your Goal

The keybind change is needed since it prevents opening the questbook via keybind in the default config.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
if this isn't fixed yet, it certainly should be.
