### ISSUE TITLE
nerf kevlar bee

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#14005]
### Your GTNH Discord Username

emskjd_114514

### Your Pack Version

2.3.4

### Your Proposal

nerf kevlar bees, making kevlar production lines no longer useless and limiting the speed of tech line climbing

削弱凯夫拉蜜蜂，让凯夫拉产线不再没有用处，限制科技线攀爬速度

### Your Goal

It doesn't make sense that Kevlar bees can now be made without the use of chemical materials to make them; bees of any material should only be produced after that material has been made

凯夫拉蜜蜂现在不需要使用化工材料制作就可以制作，这是不合理的，任何材料的蜜蜂都应该在制作出该种材料之后才能生产

### Your Vision

What's the point of having players make kevlar spawn lines normally and mass-produce kevlar before they can use kevlar bees for production, otherwise what's the point of us making a Kevlar spawning line?

让玩家正常的制作出凯夫拉产线，量产凯夫拉后才能使用凯夫拉蜜蜂进行生产，否则我们做凯夫拉产线的意义是什么呢?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I would usually agree, you shouldnt be able to skip a tech line. But well, this is Kevlar. I havent met anybody yet that likes the Kevlar line. So well, lets maybe not enforce it.

Ideally we should do this, but only after somebody completely overhauls and redesigns kevlar. Which might not happen anytime soon.

**Comment by btly0711** [comment]
DO YOU SERIOUS?
Kevlar bees are great and everyone likes it
just because no one likes Kevlar line.
I believe this feature would make the pack very boring and unconfortable.
you can get much Indium by bees before you get a compelete Indium line
you can also get some Gallium by bees in IV without some other ways to get it
why you think"we should get a Kevlar line before we use the bees"?
I hope this will never add to the next update

**Comment by Hikari1nVoid** [comment]
You got tons of things to do between t8&t9 why forcing people to take an extra load?
