### ISSUE TITLE
Issue with Enchanting loot bag (AE Basic)

### ISSUE THREAD

**Issue by NateKasuma** [GTNewHorizons/GT-New-Horizons-Modpack#14001]
### Your GTNH Discord Username

NateKasuma

### Your Pack Version

2.3.4

### Your Server

Private server

### Java Version

Java 17

### Type of Server

Open To LAN

### Your Expectation

I was trying to craft the Fortune 3 AE basics loot bag

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/140047799/d5c17f66-32d3-4c4e-86ce-bdec978185c8)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/140047799/1ef24daf-7a61-450d-9eb2-7b7e067f602f)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/140047799/87f727c8-be35-4d89-ba36-bf70b6bb830f)
The crafting recipe does not seem to work I had a fortune 3 book as well as item processor tier 1 in crafting grid with loot bag but there was no valid recipe.

### Your Proposal

Recipe needs to be fixed

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Fixed in dev https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/661
