### ISSUE TITLE
Tier 9 Mehen Belt Void Miner Error

### ISSUE THREAD

**Issue by chfmfmd** [GTNewHorizons/GT-New-Horizons-Modpack#14008]
### Your GTNH Discord Username

초르릉

### Your Pack Version

2.3.4~2.3.6

### Your Server

private server

### Java Version

Java 20

### Type of Server

None

### Your Expectation

Wanted to get Awakened Draconium Vein from Tier 9 Mehen Belt with Void Miner 3

### The Reality

I installed void miner 3 to get Awakened Draconium Vein from Tier 9 Mehen Belt, but it doesn't work. It's already in the pipe.
I'll post a video instead of a screenshot
https://youtu.be/ij7Pn-wiJuo

### Your Proposal

please fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by POPlol333** [comment]
are VM3 even configured with T9 yet?

**Comment by chfmfmd** [comment]
> are VM even configured with T9 yet?
Other places work, only Mehen doesn't work
