### ISSUE TITLE
AE2 Autocrafting Missing Items when calculating large crafts

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#14023]
### Your GTNH Discord Username

hucking

### Your Pack Version

2.3.4

### Your Proposal

I propose a feature that will make it so you no longer need to worry about having on demand / passive stuff interact poorly with each other.

### Your Goal

For example let's say I have a LCR making me phosphoric acid and I have it set to turn off once I have a certain amount and I'm also using it passively for a bunch of different chem lines but I also want to craft some lumiinessence.

If between the time that I started the calculation for the craft and the time that it finishes it recognizes that some of the phosphoric acid was used it will tell me that I cannot start the recipe because it did not request enough phosphoric acid to get crafted in addition to what it initially thought the ME network had available.

and tell me if I'm wrong about this assumption of how the code works

### Your Vision

My proposal is to have an additional check after the craft is done calculating to see if some of the materials were used up and just request extra to be crafted as required.

Of course need to make sure it's not running in an infinite loop so another check needs to make sure it's not stuck calculating forever, although I think if coded correctly that shouldn't really happen...

So the result would be that I can actually request large crafts without having to find some annoying solution like separating the passive stuff to a subnet, turning it off, waiting for the perfect moment when nothing is used or requesting the craft in parts...

Alternatively you could also shove the items directly into crafting storage as soon as you request the craft but that is slightly less user friendly and can lead to some unintended interactions or annoyances especially in multiplayer.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by King65868** [comment]
This already exists, with the new precrafting option in https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/341
