### ISSUE TITLE
coke fuel block recipe fix

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#14020]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.4

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

1 to 9   not 1 to 1

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/2911b531-156f-4b37-bd66-210f9bb5d949)

### Your Proposal

fix the recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
even the block to 9 should just be forge hammer and not centrifuge. I will have a look.
