### ISSUE TITLE
Gregtech cash's the game on the start 

### ISSUE THREAD

**Issue by Gabriel-Sousa-Oliveira** [GTNewHorizons/GT-New-Horizons-Modpack#14039]
### Your GTNH Discord Username

Morgato#9571

### Your Pack Version

2.3.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I have my own modpack and I was adding everything that, as minecraft indicated to be necessary, came from GTNH to be able to use the GregTech version, but I came across this crash that I don't know what should be done to solve it

### Crash Report

[crash-2023-07-23_21.44.45-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12140961/crash-2023-07-23_21.44.45-client.txt)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12140964/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
our gregtech is very customized and not supported for outside use. compare https://docs.google.com/spreadsheets/d/1LHd8c4FLLHiJqsuTppF2XFTE6bh-mXE7afVwGbzOKms/edit?pli=1#gid=1469028684

**Comment by miozune** [comment]
Code indicated in the log is already refactored in dev, so not relevant now
