### ISSUE TITLE
Nutrition

### ISSUE THREAD

**Issue by Maycke25** [GTNewHorizons/GT-New-Horizons-Modpack#14033]
### Your GTNH Discord Username

maycke25

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

eat any food not give me 100% hunger
this crashes the game and opens the bug report. It doesn't close the game, I can go back to the menu
sorry for my English
![hunger](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13217682/cd3266d7-13aa-47fd-a1b7-e539f97c99fb)
Edit, better text:
eating any food that gives me less than 100% nutritional value crashes the game

### Crash Report

https://mclo.gs/NUodhdq
[crash-2023-07-23_16.40.20-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12139832/crash-2023-07-23_16.40.20-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by SilverStarship7** [comment]
I have the same issue for version 2.3.5 with java 19

Oracle hosted private server, optifine HD U E7 added

Pastebin of crash log: https://pastebin.com/1BtG8S5i
