### ISSUE TITLE
mApiary won't output combs

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#14036]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Got bees in mApiary
It has energy
Flowers too
Should output combs

### The Reality

It didn't output combs even if it should and everything works fine

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/133218866/9ae1de82-2033-4f45-9bdc-ef478de4a363)

### Your Proposal

Fix it? ^^

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@MaGeBZz can you test with this file ? <https://github.com/GTNewHorizons/KubaTech/releases/tag/0.12.4-pre>
and let me know if it is fixed.

**Comment by MaGeBZz** [comment]
> 

Sure I can, will test it soon texting you on discord after that

**Comment by istreee** [comment]
I'm having the same problem.  Tested with the fix jar does not seem to fix.  FWIW, only outputs which require mapiary are effected.  I tested with xenon, americium, and imperial. I get no xenon/americium combs, but I do get imperial outputs.  I did not do the same test on the initial version (0.12.3)  so I'm unsure if that is new behavior or not.

**Comment by MaGeBZz** [comment]
> 
The new version fixed it, thanks!
