### ISSUE TITLE
Broken recipes 

### ISSUE THREAD

**Issue by ZetsuboNemurase** [GTNewHorizons/GT-New-Horizons-Modpack#14045]
### Your GTNH Discord Username

reisen_light

### Your Pack Version

2.3.5

### Your Server

Private server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

1) Trying to craft stone plate (5907) from dust (7205/2299) with compressor.
2) Trying to craft Iron Cap (Thaumcraft)  

### The Reality

1) Getting broken item with name gt.metaitem.01.17299.name (7205/17299) that has no uses. It uses old sprite of a stone plate that used to work, tho.
2) No working recipe for that.

### Your Proposal

Honestly? Fixing recipe. I don't know

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ZetsuboNemurase** [comment]
Addition: Whenever you get normal stone plates in your inv they autoconvert in broken ones

**Comment by Ngar1** [comment]
receipt of iron cap worked on my side (zeta, 2.3.5)

**Comment by chochem** [comment]
stone plate works fine too 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/e3559bb9-c3c5-43d2-96b7-1761018505f3)

**Comment by chochem** [comment]
not sure what's going on on your end, maybe try reinstalling. My best bet would be that you have old scripts from previous versions hanging around but I am not sure.

**Comment by ZetsuboNemurase** [comment]
Thank you, will check

**Comment by desagas** [comment]
2.3.4 changed the version of stone plates for a new one, and all old ones now just have a localized name. I assume it was a result of adding a new material or something. This has nothing to do with this update.

As for iron caps, make sure you are actually click on very specifically spelled "Iron Cap" and are not clicking on "Iron Wand Cap." Why items are in NEI still that have no crafting recipes after multiple versions is a mystery to me, but, A LOT of people seem to think that both are the same, without even trying the other. There is also still errors in quests that talk about "Iron WAND Caps," even though they have been uncraftable since 2.2.8, I believe.

**Comment by ZetsuboNemurase** [comment]
> 2.3.4 changed the version of stone plates for a new one, and all old ones now just have a localized name. I assume it was a result of adding a new material or something. This has nothing to do with this update.
> 
> As for iron caps, make sure you are actually clicking on very specifically spelled "Iron Cap" and are not clicking on "Iron Wand Cap." Why items are in NEI still that have no crafting recipes after multiple versions is a mystery to me, but, A LOT of people seem to think that both are the same, without even trying the other. There are also still errors in quests that talk about "Iron WAND Caps," even though they have been uncraftable since 2.2.8, I believe.

Thank you for the answer, but that's not the issue with Iron cap. I linked (Thaumcraft) at the end because i was meaning specifically Iron Caps, not Wand Caps. And they do not have recipes. 

The problem is i believe server-sided, so... nothing i can do.
