### ISSUE TITLE
Hydrogen peroxide recipe will not run

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#14040]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I was trying to craft Hydrogen Peroxide in the chemical plant.

### The Reality

Instead of crafting the chemical plant stated that the output was full. However changing void mode to full or adding more hatches changed nothing.

### Your Proposal

Hydrogen Peroxide is critical to making rocket fuel in the chemical plant and will block players from progressing.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
do other recipes work?

**Comment by Reflex18** [comment]
On reloading the game to double check, the recipe just started working again. I am not entirely sure what happened but it seemed the fix was a server restart.
