### ISSUE TITLE
refactory capsulate for acclimatiser

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#14044]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.3.5

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I search receipt for refactory capsule for lava capsule for acclimatiser -> non found,

### The Reality

refactory wax  result by extruder (cell) in ordinary wax capsule

### Your Proposal

need solution for lava input in one slot in acclimatiser

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment]
Looks like a similar/duplicate issue of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13973
