### ISSUE TITLE
Thorium Reactor (LFTR) constantly outputs the materials on warmup

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#14041]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I have loaded in the fuel input and started the reactor.

### The Reality

The Thorium Reactor (LFTR) Constantly outputs the four fluid outputs on warmup at a fast rate.

### Your Proposal

The Thorium reactor should only output the fluids on recipe finish.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Exelion42** [comment]
Same here. My guess is that during warm up it is alreasy runnig the recepie, at least the output part. And since the warm up is ticking once per tick, it is outputing once per tick. So we get these extreme amounts of output material.
