### ISSUE TITLE
Add the creative machines of gregicality science to modpack

### ISSUE THREAD

**Issue by TNTAcPrLuPie** [GTNewHorizons/GT-New-Horizons-Modpack#14054]
### Your GTNH Discord Username

TNT_AcPrLuPie

### Your Pack Version

2.3.2

### Your Proposal

Add the creative machines of gregicality science to modpack.

### Your Goal

Because Gregicality Science is already dead.I don't want the creative machines of gregicaity science to disappear.

### Your Vision

This can make the modpack more diversified.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
gregicality-science is for 1.12.2

**Comment by Phineasor** [comment]
ya, I think he is recommending that we re add ALL of the things.
