### ISSUE TITLE
Pine planks from biomes o plenty missing compatibility with pine wood recipes 

### ISSUE THREAD

**Issue by Enzyme0** [GTNewHorizons/GT-New-Horizons-Modpack#14056]
### Your GTNH Discord Username

logan.dev

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62308489/c9b0f439-f6f6-4d08-bf6a-b2bf6fe08f9f)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62308489/7ce25027-6f29-4600-b670-f1df89dbbbfe)
I wanted to craft pine fences with the pine planks from biomes o plenty

### The Reality

pine wood is missing tag for pine
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62308489/452c889d-09b6-425f-b5ac-530243989b43)
> forestry pine
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62308489/7d1c7f06-18c1-4179-8c29-7a3dcb443655)

### Your Proposal

add the pinePlanks to biomes o plenty pine planks

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by JL2210** [comment]
Same here on 2.4.1. Tried to craft a pine fence for my tinkers' stencil table, was confused when the recipe didn't work. Ended up turning on cheats, deleting the items, and using `/give` to get the fence
