### ISSUE TITLE
Client crash when placing oil cracker

### ISSUE THREAD

**Issue by istreee** [GTNewHorizons/GT-New-Horizons-Modpack#14064]
### Your GTNH Discord Username

istree

### Your Pack Version

2.3.5

### Your Server

private

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

I noticed existing oil crackers were replaced with placeholder textures of .name, see [here](https://imgur.com/a/dLWWkjg). breaking them gives weird .name thing with no texture.  Placing new cracker controllers anywhere in the world causes immediate client crash.  Additional list of mods which were added to/updated: 
```
ae2fc-1.1.34-gtnh.jar
betterp2p-1.1.17-pre.jar
FTBLib-1.0.19-GTNH.jar
FTBUtilities-1.1.0-GTNH.jar
gregtech-5.09.43.148.jar
GTNewHorizonsCoreMod-2.1.90.jar
kubatech-0.12.4-pre.jar
worldedit-forge-mc1.7.10-6.0-beta-01.jar
```

### Crash Report

https://mclo.gs/GCV9Psm

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
can confirm. same issues here. same crash too.
