### ISSUE TITLE
[Thaumcraft][2.3.5] Alchemical Grate Missing research 

### ISSUE THREAD

**Issue by IkarusFalling** [GTNewHorizons/GT-New-Horizons-Modpack#14066]
### Your GTNH Discord Username

null7465

### Your Pack Version

2.3.5

### Your Server

--

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Expected for the research to exist if all Prerequisites are researched 

### The Reality

It doesn´t exist 

How to test:

1. Create new World
2. Run Unlock Research Command "/thaumcraft research [PlayerName] all"
3. Check if Recipe for Grate exists and or the research Exists:
Results: 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/111616675/2ba7674e-1239-4dab-bba5-ce3844cc1edd)
Alchemical Grate research should be next to normal Grate research or somewhere else it is neither 

### Your Proposal

Fix the Bug that is preventing the existence of the research 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
https://github.com/GTNewHorizons/AlchemyGrate/pull/3 

fixed
