### ISSUE TITLE
Leads to optimize server load in endgame bases

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#14061]
Here are several things that needs to be addressed at some point to make the servers run smoother:
- redo recipe matching in GT. Right now we use batch mode to avoid spamming every tick the recipe checks.
- Make AE2 not doing a copy of the stored items each time an item is retrieved: <details>
  <summary> issue </summary>

  ![image-10](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12850933/4e64f1b2-43f8-4204-97c9-5c62cdab5315)
  We might need to wrap the optimization in a if GTNH loaded block to keep backward compat outside of NH. While this may be a global issue, it becomes critical when the players start to use ME hatches in GT multis. For instance, this is what happens on the server hosting the stargate run:

  ![image-17](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12850933/0bac0d17-a1aa-48a9-b343-c2030298fcd2)
  </details>
  fixed by GTNewHorizons/Applied-Energistics-2-Unofficial/pull/363 and GTNewHorizons/AE2FluidCraft-Rework/pull/150

**Comment by Sopel97** [comment]
`ItemList,add` could use https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentSkipListMap.html#putIfAbsent-K-V- instead first trying to find the element and then inserting if not found.
