### ISSUE TITLE
AE2 crafting status interface location gets set only when pressing shift initially

### ISSUE THREAD

**Issue by Alaking** [GTNewHorizons/GT-New-Horizons-Modpack#14067]
### Your GTNH Discord Username

alaking

### Your Pack Version

2.3.4 with updated betterP2P

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

hold shift and hover over different crafts
expect to see the interface location be accurate to the craft im hovering over

### The Reality

only the first displayed location gets displayed until I release and press shift again

### Your Proposal

make it work properly if possible i guess, its a very minor bug so not really a big deal imho

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alaking** [comment]
did some more testing around this, its only happened between a craft split across multiple locations via interface p2p and a craft that isnt

**Comment by Hiagg** [comment]
i am unsure of the exact cause but i have issues with it not displaying the right interface as well
