### ISSUE TITLE
new machine name tooltips are not working on any* luv+ machines

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#14078]
### Your Pack Version

2.3.5 nightly 70

### Your Server

bee run

### Java Version

Java 17

### Type of Server

None

### Your Expectation

the new machine type tooltip to be on every tier

### The Reality

all but 3 LuV+ machines, mass fab, replicator, and scanner, are missing the tooltip so currently the feature is unfortunately effectively unusable as thats when the weird machine names start

### Your Proposal

plz fix so we can make use of this great new feature ty

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TheEpicGamer274** [comment]
So some machines were missed in this addition, and certain tiers of machines are in different mods, they will be added in future.
