### ISSUE TITLE
"You shall proceed" quest not registering wooden form (brick)

### ISSUE THREAD

**Issue by mftgtg** [GTNewHorizons/GT-New-Horizons-Modpack#14077]
### Your GTNH Discord Username

marzianom

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I have the wooden shape (brick) in my inventory and press the Detect/Submit button. I Expect the questbook to register the item and let me move on to the next task in the quest.

### The Reality

Questbook does not register the wooden form (Brick).

### Your Proposal

Make the questbook register the wooden form (brick) correctly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
that is an optional task, so that is not the reason you cant move on. If its not registering my best bet would be that you already completed quest maybe?

**Comment by mftgtg** [comment]
The issue was that it is a crafting task, but is not signaled as such in the questbook. I would propose proper signaling of the task.

**Comment by chochem** [comment]
nah, its optional.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/601d553f-c84c-41ad-9579-4ef17691863e)
