### ISSUE TITLE
Pseudo-Inversion Sigil craft does not return Mobius Unstable/Stable ingots

### ISSUE THREAD

**Issue by kalenderdose** [GTNewHorizons/GT-New-Horizons-Modpack#14075]
### Your GTNH Discord Username

kalenderdose

### Your Pack Version

2.1.51

### Your Server

private server

### Java Version

Java 19

### Type of Server

None

### Your Expectation

- I should be able to craft a `Mobius "Unstable/Stable" Ingot` using a `Pseudo-Inversion Sigil`.
- However, I should not be able to craft any "normal" `Unstable Ingots` with an unactivated `Division Sigil`.

### The Reality

It's possible to craft "Unstable Ingots" with an unactivated `Division Sigil`:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/34547197/795ba4cd-5248-458d-b35a-ef13c0a2f54b)

The result of a craft with "Unstable Ingots" with the `Pseudo-Inversion Sigil` results not in `Mobius "Unstable/Stable`
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/34547197/5b41d683-938b-42db-ae31-e154eea08442)

### Your Proposal

Please make the necessary corrections to achieve the expected behavior.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by nhwhirlwind** [comment]
This is still happening in 2.5.1

**Comment by SweptWasTaken** [comment]
This should be fixed for 2.6.0 since lots of unstable ingots are required for the first 4 eternal singularities.

**Comment by chochem** [comment]
there is a lot broken about these and has been for several years.

E.g., if you shift click craft a stack they cant explode.

**Comment by Dream-Master** [comment]
can this fixed via hodgepodge ?
