### ISSUE TITLE
Error during loading recipe with Dynamic Lights installed

### ISSUE THREAD

**Issue by captainjolt** [GTNewHorizons/GT-New-Horizons-Modpack#14076]
### Your GTNH Discord Username

captainjolt42

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Expectation

I updated my version from 2.2.0.0 to 2.3.5 and also added a couple of mods from the Additional Mods page of the wiki and expected everything to work.

### The Reality

Everything went fine when updating the modpack, but I would get an error in chat saying "There was error during loading recipe. Please check log for details." and time I tried to view a recipe using NEI. If it matters, I could still craft the recipes, but I couldn't view them in NEI. I tried removing the additional mods and restarting the client and everything worked again. I narrowed it down to Dynamic Lights causing the issue as any combination of mods I use works unless Dynamic Lights in the list.

### Your Proposal

I have no idea why Dynamic Lights would conflict with NEI recipes, but that should probably either be fixed or mentioned in the list of recommended mods.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
retry on a stock 2.3.6 to see if it changed the issue.

**Comment by Corfiot** [comment]
Still happening on 2.4.0
Exception is  class atomicstryker.infernalmobs.common.InfernalMobsCore cannot be cast to class com.kuba6000.mobsinfo.mixin.InfernalMobs.InfernalMobsCoreAccessor
Probably some infernalmobs / dynamiclight conflict?
