### ISSUE TITLE
Fix Loophole in MV/HV Progression, or Reorganize Quests Around It (SMD Transistors)

### ISSUE THREAD

**Issue by henrydukepickle** [GTNewHorizons/GT-New-Horizons-Modpack#14079]
### Your GTNH Discord Username

henryduke#0140

### Your Pack Version

2.3.5

### Your Proposal

Two Options:
1. Make SMD Transistors require Kanthal Coils to make. This would most likely take the form of either removing the annealed copper recipe, or perhaps making gallium ingots an EBF recipe.
2. Make the quest system reflect that making kanthal in MV is not required, by adding an optional quest line for SMD transistors that leads into the HV circuit quest required for progression.

### Your Goal

Currently, there is a large disconnect between what is required to progress and what the quest book requires to progress. This forces players to invest a lot of time into making something that isn't even really needed, and also allows players to bypass most of MV progression.

### Your Vision

It would close a somewhat strange loophole, or at least make it clear what is really required to progress.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by henrydukepickle** [comment]
It's worth adding that as far as I can tell, you don't ever need to get kanthal using a chem bath to cool it- I'm fairly certain you can postpone kanthal until you get a vacuum freezer

**Comment by chochem** [comment]
2 is reflected by a skip quest currently, so you are good with going either way in that regard already.

But iirc, dream was thinking about nerfing the SMD receipe at some point. like making it HV was one proposal.
