### ISSUE TITLE
Journeymap Ore-Veins at negative coords disappear after client restart

### ISSUE THREAD

**Issue by HellFirePvP** [GTNewHorizons/GT-New-Horizons-Modpack#14081]
### Your GTNH Discord Username

hellfirepvp

### Your Pack Version

2.3.5 dev, with GT5-Unofficial at 5.09.43.147

### Your Server

Dedicated Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

After the fix in the mentioned GT5-Unofficial build (Journeymap Ore-Vein overlay), the ore-vein hints should show up at the correct coordinates in F9 and the overlay in journeymap. Found veins should stay visible after being found.

Link to the build Dreammaster provided https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.43.147-pre

### The Reality

Ore-Veins in negative coordinate space (either -X or -Z coordinates) disappear after a pack restart.

Step-By-Step:

1. Startup Client (with the fixed GT5-Unofficial build or later in question)
2. Login to MP Server
3. Find ore vein in negative coordinates
4. Check journeymap it is present and discovered
5. Close Client
6. Startup Client
7. Connect to same MP Server
8. Check journeymap, the Ore-Vein(s) in negative coordinates are gone
9. Disconnect (No Client restart)
10. Reconnect to same MP Server
11. Check journeymap, the Ore-Vein(s) are back as expected

### Your Proposal

Always show discovered ore veins

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
@HellFirePvP please test this build: http://jenkins.usrv.eu:8080/job/Visual-Prospecting/101/artifact/build/libs/visualprospecting-1.1.12-fix-oregen-pattern-info-received-to-late.3+ef429f365f.jar

**Comment by HellFirePvP** [comment]
That fixes it, yup
