### ISSUE TITLE
2.3.5 - Missing recipe for Electrum Bees

### ISSUE THREAD

**Issue by garaiza-93** [GTNewHorizons/GT-New-Horizons-Modpack#14086]
### Your GTNH Discord Username

nowaaaay

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

I expected to have a method of breeding bees to create Electrum bees.

### The Reality

There is no breeding recipe listed in NEI. The only recipes are the generic recipes from Alfheim Portal, , Incubator, Scanner, and Lootbags.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57430880/da7e633c-8e35-4ec2-a734-176b05b27e39)

### Your Proposal

Include a breeding recipe for Electrum bees. I have no idea what it was before, if it existed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I dont think it was breedable in any recent version. not all bees that show in nei are.

**Comment by garaiza-93** [comment]
I have no way of changing tags, but I'd like to suggest making them breedable. It's annoying to have an NEI entry for them, only to see that there's only these generic entries.

**Comment by TechnicianFreak** [comment]
What's the dark UI texturepack? Looks great.

**Comment by Cardinalstars** [comment]
What mod even adds those bees. Looking in the code I can only find one mod that might add it; Magic Bees. Even then it shouldn't get loaded because there's no TE. Does anyone know what adds this?

**Comment by garaiza-93** [comment]
@TechnicianFreak https://github.com/Jimbno/Dark.UI
