### ISSUE TITLE
Add different Programmed Circuits for different spacetime formulations of Hypogen Coil and Eternal Coil

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#14087]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.3.5

### Your Proposal

Add different Programmed Circuits to allow the machine to recognize their differences. As a comparison, whether Infinity uses Infinity Comb's formula has been added with Programmed Circuit to prevent machine recognition errors

### Your Goal

Although there is not much difference between the two existing spacetime formulas, Hypogen Coil (Dimensionally Transparent Reside, Infinity, Hypogen, Energized Tesseract) and Eternal Coil (Dimensionally Transparent Reside, Infinity, Energized Tesseract, Hypervisor Matrix (fusion)), But when Eternal's spacetime recipe appears in DTPF along with Molten Superconductor Base UMV (Spacetime, Orndum, Hyphen, Titansteel, Dragonblood, Oxygen Plasma), the machine sometimes mistakenly believes that it is attempting to execute the spacetime recipe of the Hypogen Coil

### Your Vision

Reduce recipe conflicts in DTPF and prevent many fluids from getting stuck in Input Hatch, causing AE2 automatic synthesis to stop

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Is this still an issue @JodieRuth ?

**Comment by JodieRuth** [comment]
> Is this still an issue @JodieRuth ?

Before you use the crafting input buffer for DTPF, yes
