### ISSUE TITLE
Add Some New Recipes to QFT

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#14090]
### Your GTNH Discord Username

Cainiaojun

### Your Pack Version

2.3.5

### Your Proposal

1. Enable QFT to process some intermediate products ,like: 
 - Iridium Metal Residue to Iridium Dust at 1:1 ratio, just the same as that in normal Platline, T1 QFT, UV 5s with Platline Catalyst.
 - Rarest Metal Residue to Osmium Dust and Iridium Dust, respectively at 20:1 and 20:10 ratio, the same as those in normal Platline, T1 QFT, UV 5s with Platline Catalyst.
 - Palladium Metallic Powder to Palladium Dust at 2:1 ratio, a little lower than normal Platlinr, T1 QFT ,UV 5s with Platline Catalyst.
 - Cerium-Rich Mixture to Cerium Dust at 60:1 ratio, the same as normal processing, T2 QFT ,UHV 5s with Rare Earth Catalyst.

2.  Enable QFT to produce TCetiE Seaweed Extract in T4 QFT with Bio Catalyst.

### Your Goal

1. QFT should be able to process some intermediate products as they could be mined straightly by Space Elevator of Void Miner.
2. If QFT could produce seaweed ,there is no need to use Bacteria anymore in UMV+ tiers.

### Your Vision

1. Make full use of those ores.
2. Remove all Bacteria in my base.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by combusterf** [comment]
We've discovered this ore processing issue independent of each other. While the final recipes are different, they should address your primary point.

The QFT already handles seaweed-related crafts in the current version.
