### ISSUE TITLE
multi-machine not work

### ISSUE THREAD

**Issue by DarkLei** [GTNewHorizons/GT-New-Horizons-Modpack#14091]
### Your Pack Version

2.3.5nightly 71

### Your Server

sp

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

in 2.3.4,every mechine work well,but when upgrade to 2.3.5 nightly 71,multi-machine do not work,"power overflowed",I don't know what that mean.

### The Reality

mechine show "power overflowed"

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
which multi? what recipe? any more information?

**Comment by chochem** [comment]
looks like there were some more api changes in gt and not all mods have been adapted to it yet. Its work in progress.

**Comment by BlueWeabo** [comment]
fixed in dev

**Comment by chochem** [comment]
you can try https://github.com/GTNewHorizons/GTplusplus/releases/tag/1.9.71 and test that your gt++ multis now work correctly

**Comment by DarkLei** [comment]
> you can try https://github.com/GTNewHorizons/GTplusplus/releases/tag/1.9.71 and test that your gt++ multis now work correctly

THX

**Comment by DarkLei** [comment]
> you can try https://github.com/GTNewHorizons/GTplusplus/releases/tag/1.9.71 and test that your gt++ multis now work correctly

Actually,in nightly build 73,it performs normal.
