### ISSUE TITLE
Add dire crafting table quest skip 

### ISSUE THREAD

**Issue by truenachtara** [GTNewHorizons/GT-New-Horizons-Modpack#14098]
### Your GTNH Discord Username

Nachiebree

### Your Pack Version

2.3.4

### Your Proposal

Dire crafting table currently requires (a few quests before) the NASA workbench. Suggesting to add an OR unlock to the quest that "hold a stack of titanium to skip to EV" also unlocks.

### Your Goal

No-rocket runs have no reasons to get a NASA workbench.

### Your Vision

Allows no-rocket players more access to the quests, especially the solar panel quests later on.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
no rocket runs are not officially supported tho

**Comment by chochem** [comment]
the skip quests and a few other such changes allow no-rocket to at least have the main quest progression available to like UHV. But yea, dont mistake that for full support. Trying to make every sidequest available is not planned (at least for me).
