### ISSUE TITLE
GT pipes inputs item through the front of the machine

### ISSUE THREAD

**Issue by Samajjj** [GTNewHorizons/GT-New-Horizons-Modpack#14101]
### Your GTNH Discord Username

.samaj

### Your Pack Version

2.3.0.

### Your Server

dedicated lan private server

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

GT Pipe shouldn't put in hydrogen cells through the front of the chemical reactor, as seen on the screenshot
![unfortunately](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49820718/838b7e9c-c556-4b7c-9497-030ab26f1302)

### The Reality

If receiving chemical reactor has any hydrogen cells inside, they will go inside.

### Your Proposal

People on Discord said it's a bug, so I'm reporting it. I have no proposal.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
Can confirm the bug.
This bug also affects the output side. Even if input on output side is disabled, items still come in if there is a partial stack of the same item inside the machine already.

**Comment by chochem** [comment]
@kuba6000 could you have a look? It looks like you added some hashmap and logic for partially filled slots to optimize item transfer but I guess there is a check missing if the side is allowed or something like that?
from https://github.com/GTNewHorizons/GT5-Unofficial/pull/992

its possible I am wrong and its something completely different but this seems like a pretty likely cause.

**Comment by chochem** [comment]
uh, its actually even worse.

looks like stuff even goes into output slots or even battery/storage slots, if there is a partial stack there already. So the missing checks in the partially filled case are even broader.

**Comment by chochem** [comment]
was also reported last year already for the output slot case: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11442
