### ISSUE TITLE
java 17

### ISSUE THREAD

**Issue by FireV0id** [GTNewHorizons/GT-New-Horizons-Modpack#14103]
### Your GTNH Discord Username

FireVoid

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 20

### Type of Server

Open To LAN

### Your Actions

i was playing at java 8 trying to upgrade java 20 but its keep not opening ( using 17-20 files)

### Crash Report

MultiMC version: 0.7.0-3775

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.165.61.128, 18.165.61.121, 18.165.61.16, 18.165.61.6]

session.minecraft.net resolves to:
    [13.107.246.45, 13.107.213.45]

textures.minecraft.net resolves to:
    [13.107.246.45, 13.107.213.45]

api.mojang.com resolves to:
    [13.107.246.45, 13.107.213.45]

Minecraft folder is:
C:/MC/instances/GT_New_Horizons_2.3.4_Java_17-20/.minecraft

Java path is:
C:/Program Files/Java/jdk-20/bin/javaw.exe

Checking Java version...
Java is version 20.0.2, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/MC/instances/GT_New_Horizons_2.3.4_Java_17-20/natives

Libraries:
  C:/MC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.2/lwjgl-glfw-natives-windows-x86-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.2/lwjgl-glfw-natives-windows-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.2/lwjgl-jemalloc-natives-windows-x86-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.2/lwjgl-jemalloc-natives-windows-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.2/lwjgl-natives-windows-x86-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-natives-windows/3.3.2/lwjgl-natives-windows-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.2/lwjgl-openal-natives-windows-x86-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.2/lwjgl-openal-natives-windows-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.2/lwjgl-opengl-natives-windows-x86-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.2/lwjgl-opengl-natives-windows-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.2/lwjgl-stb-natives-windows-x86-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.2/lwjgl-stb-natives-windows-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.2/lwjgl-tinyfd-natives-windows-x86-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.2/lwjgl-tinyfd-natives-windows-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  C:/MC/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  C:/MC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/MC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/MC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/MC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/MC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/MC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/MC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/MC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/MC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/MC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/MC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/MC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/MC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/MC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/MC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/MC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/MC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/MC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/MC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/MC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/MC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/MC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/MC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/MC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/MC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/MC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/MC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/MC/libraries/com/github/GTNewHorizons/lwjgl3ify/1.4.0/lwjgl3ify-1.4.0-forgePatches.jar
  C:/MC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/MC/libraries/net/minecraft/launchwrapper/1.15/launchwrapper-1.15.jar
  C:/MC/libraries/org/ow2/asm/asm/9.4/asm-9.4.jar
  C:/MC/libraries/org/ow2/asm/asm-commons/9.4/asm-commons-9.4.jar
  C:/MC/libraries/org/ow2/asm/asm-tree/9.4/asm-tree-9.4.jar
  C:/MC/libraries/org/ow2/asm/asm-analysis/9.4/asm-analysis-9.4.jar
  C:/MC/libraries/org/ow2/asm/asm-util/9.4/asm-util-9.4.jar
  C:/MC/libraries/org/ow2/asm/asm-deprecated/7.1/asm-deprecated-7.1.jar
  C:/MC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/MC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/MC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/MC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/MC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/MC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/MC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/MC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/MC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/MC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/MC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/MC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/MC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/MC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/MC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/MC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [✔️] AdvancedSolarPanel-1.7.10-3.5.1a.jar
  [✔️] adventurebackpack-1.0.14-GTNH.jar
  [✔️] ae2fc-1.1.21-gtnh.jar
  [✔️] ae2stuff-0.5.1.16-GTNH.jar
  [✔️] AFSU-1.7.10-1.2.6-GTNH.jar
  [✔️] AmunRa-GC-0.4.30.jar
  [✔️] AngerMod-1.7.10-0.6.3.jar
  [✔️] AppleCore-3.2.10.jar
  [✔️] appliedenergistics2-rv3-beta-225-GTNH.jar
  [✔️] ArchitectureCraft-1.8.6.jar
  [✔️] Aroma1997Core-1.7.10-1.0.2.16.jar
  [✔️] AromaBackup-1.7.10-0.1.0.0.jar
  [✔️] AsieLib-1.7.10-0.5.3.jar
  [✔️] Automagy-1.7.10-0.28.2.jar
  [✔️] Avaritia-1.42.jar
  [✔️] Avaritiaddons-1.5.5-GTNH.jar
  [✔️] backpack-2.2.11-GTNH.jar
  [✔️] bartworks-0.7.17.jar
  [✔️] battlegear2-1.2.0.jar
  [✔️] Baubles-1.0.1.16.jar
  [✔️] bdlib-1.7.10-1.9.8-GTNH.jar
  [✔️] BeeBetterAtBees-0.3.jar
  [✔️] BetterAchievements-1.7.10-0.1.3.jar
  [✔️] BetterBuildersWands-1.7.10-0.9.6-GTNH.jar
  [✔️] bettercrashes-1.2.2-GTNH.jar
  [✔️] betterloadingscreen-1.4.1-GTNH.jar
  [✔️] betterp2p-1.1.14.jar
  [✔️] BetterQuesting-3.3.24-GTNH.jar
  [✔️] BiblioCraft[v1.11.7][MC1.7.10].jar
  [✔️] BiblioWoods[BiomesOPlenty][v1.9].jar
  [✔️] BiblioWoods[Forestry][v1.7].jar
  [✔️] BiblioWoods[Natura][v1.5].jar
  [✔️] binnie-mods-2.1.4.jar
  [✔️] BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
  [✔️] BlockLimiter-1.7.10-0.55.jar
  [✔️] blockrenderer6343-1.0.1.jar
  [✔️] BloodArsenal-1.2.10.jar
  [✔️] BloodMagic-1.4.1.jar
  [✔️] Botania-1.9.23-GTNH.jar
  [✔️] BotanicHorizons-1.0.15-GTNH.jar
  [✔️] BrandonsCore-1.7.10-1.0.0.13-GTNH.jar
  [✔️] bugtorch-1.2.10-GTNH.jar
  [✔️] buildcraft-7.1.33.jar
  [✔️] buildcraft-compat-7.1.14.jar
  [✔️] BuildCraftOilTweak-1.7.10-1.0.4.jar
  [✔️] CarpentersBlocks-3.4.0-GTNH.jar
  [✔️] catwalks-1.7.10-2.1.4-GTNH.jar
  [✔️] chisel-2.11.1-GTNH.jar
  [✔️] chiseltones-1.7.10-1.0.4-GTNH.jar
  [✔️] CodeChickenCore-1.1.11.jar
  [✔️] CoFHCore-[1.7.10]3.1.4-329.jar
  [✔️] CompactKineticGenerators-1.7.10-1.0.jar
  [✔️] Computronics-1.7.1-GTNH.jar
  [✔️] controlling-1.0.0.5.jar
  [✔️] CookingForBlockheads-1.2.14-GTNH.jar
  [✔️] CraftPresence-2.0.7%2B1.7.10.jar
  [✔️] CraftTweaker-3.2.12.jar
  [✔️] creativecore-1.3.29-GTNH.jar
  [✔️] CropLoadCore-1.7.10-0.1.10.jar
  [✔️] CropsPP-1.4.1.jar
  [✔️] custommainmenu-1.7.10-1.9.4.jar
  [✔️] defaultserverlist-1.7.10-1.4.0.jar
  [✔️] defaultworldgenerator-1.7.10-0.2.jar
  [✔️] Draconic-Evolution-1.1.16-GTNH.jar
  [✔️] DummyCore-1.7.10-1.15.jar
  [✔️] duradisplay-1.0.8.jar
  [✔️] EMT-1.3.1.jar
  [✔️] endercore-0.2.16.jar
  [✔️] EnderIO-2.4.18.jar
  [✔️] EnderStorage-1.7.10-1.4.12.jar
  [✔️] EnderZoo-1.7.10-1.0.23.jar
  [✔️] EnhancedLootBags-1.1.0.jar
  [✔️] eternalsingularity-1.1.0.jar
  [✔️] extrautilities-1.2.13a.jar
  [✔️] fastcraft-1.25.jar
  [✔️] findit-1.1.0.jar
  [✔️] FloodLights-1.7.10-1.2.9.jar
  [✔️] Forbidden.Magic-0.6.7-GTNH.jar
  [✔️] Forestry-4.6.7.jar
  [✔️] forgelin-1.9.7-GTNH.jar
  [✔️] ForgeMultipart-1.3.3.jar
  [✔️] ForgeRelocation-1.7.10-0.0.3.jar
  [✔️] ForgeRelocationFMP-1.7.10-0.0.4.jar
  [✔️] gadomancy-1.1.0.jar
  [✔️] galacticgreg-1.0.9.jar
  [✔️] Galacticraft-3.0.69-GTNH.jar
  [✔️] GalaxySpace-1.2.3-GTNH.jar
  [✔️] gendustry-1.7.10-1.6.5.5-GTNH.jar
  [✔️] ggfab-0.2.2.jar
  [✔️] GoodGenerator-0.6.9.jar
  [✔️] GraviSuite-1.7.10-2.0.3.jar
  [✔️] gravisuiteneo-1.0.13.jar
  [✔️] gregtech-5.09.43.84.jar
  [✔️] GT.Scanner.Mod-1.7.2.jar
  [✔️] gtneioreplugin-1.1.0.jar
  [✔️] GTNewHorizonsCoreMod-2.1.50.jar
  [✔️] gtnhintergalactic-1.1.17.jar
  [✔️] gtnhlanth-0.10.2.jar
  [✔️] gtnhlib-0.0.13.jar
  [✔️] GTNH-TC-Wands-1.3.0.jar
  [✔️] GT-PlusPlus-1.9.39.jar
  [✔️] GTTweaker-2.0.0.jar
  [✔️] HardcoreDarkness-MC1.7.10-1.7.jar
  [✔️] HardcoreEnderExpansion-1.7.10-1.9.7-GTNH.jar
  [✔️] harvestcraft-1.1.0-GTNH.jar
  [✔️] Healer-1.2.0.jar
  [✔️] HelpFixer-1.7.10-1.1.0.jar
  [✔️] hodgepodge-2.2.18.jar
  [✔️] holoinventory-2.2.2-GTNH.jar
  [✔️] HungerOverhaul-1.7.10-1.0.4-GTNH.jar
  [✔️] hydroenergy-1.1.0.jar
  [✔️] IC2 Crop Plugin Version 1.7.10-1.3.1.jar
  [✔️] IC2NuclearControl-2.4.19.jar
  [✔️] ifu-1.9.6.jar
  [✔️] IguanaTweaksTConstruct-2.3.0.jar
  [✔️] industrialcraft-2-2.2.828a-experimental.jar
  [✔️] InfernalMobs-1.7.8-GTNH.jar
  [✔️] InGameInfoXML-1.7.10-2.8.3.96.jar
  [✔️] INpureCore-1.1.5-GTNH.jar
  [✔️] inventorytweaks-1.5.16.jar
  [✔️] IronChest-1.7.10-6.0.71.jar
  [✔️] IronChestMinecarts-1.7.10-1.0.8.jar
  [✔️] irontanks-1.7.10-1.2.6.jar
  [✔️] itlt-1.7.10-1.0.4.jar
  [✔️] JABBA-1.2.22.jar
  [✔️] journeymap-1.7.10-5.1.4p6-fairplay.jar
  [✔️] kekztech-0.8.5.jar
  [✔️] kubatech-0.11.1.jar
  [✔️] littletiles-1.2.9-GTNH.jar
  [✔️] logisticspipes-1.0.1-GTNH.jar
  [✔️] lootgames-1.7.10-2.0.8.jar
  [✔️] LunatriusCore-1.7.10-1.1.7-GTNH.jar
  [✔️] lwjgl3ify-1.4.0.jar
  [✔️] magicbees-2.6.4-GTNH.jar
  [✔️] malisiscore-0.14.7-GTNH.jar
  [✔️] malisisdoors-1.13.7-GTNH.jar
  [✔️] Mantle-0.3.7.jar
  [✔️] ModTweaker2-0.9.10.jar
  [✔️] modularui-1.1.10.jar
  [✔️] MouseTweaks-2.4.8-GTNH.jar
  [✔️] MrTJPCore-1.7.10-1.1.4.jar
  [✔️] mxrandom-0.2.0.jar
  [✔️] Natura-2.5.7.jar
  [✔️] naturescompass-1.7.10-1.3.6-GTNH.jar
  [✔️] NEIAddons-1.7.10-1.12.22.jar
  [✔️] NEICustomDiagram-1.5.5.jar
  [✔️] NEIIntegration-1.3.1.jar
  [✔️] netherportalfix-1.7.10-1.1.2.jar
  [✔️] NettyPatch-1.7.10-0.3.1.jar
  [✔️] NodalMechanics-1.7.10-1.1.-6-GTNH.jar
  [✔️] NotEnoughEnergistics-1.4.2.jar
  [✔️] notenoughIDs-1.7.10-1.4.6.jar
  [✔️] NotEnoughItems-2.3.54-GTNH.jar
  [✔️] oauth-1.7.10-1.06.1-GTNH.jar
  [✔️] OpenBlocks-1.7.0-GTNH.jar
  [✔️] OpenComputers-1.9.8-GTNH.jar
  [✔️] OpenGlasses-1.3.1-GTNH.jar
  [✔️] OpenModsLibs-1.7.10-0.10.6.jar
  [✔️] OpenModularTurrets-1.7.10-2.2.11-247.jar
  [✔️] openprinter-1.7.10-0.1.3-GTNH.jar
  [📁] OpenSecurity (folder)
  [✔️] opensecurity-1.7.10-1.0.120-GTNH.jar
  [✔️] Opis-1.7.10-1.3.8-mapless.jar
  [✔️] overloadedarmorbar-1.7.10-1.0.1.jar
  [✔️] p455w0rdslib-1.7.10-1.0.4.jar
  [✔️] Pam's Harvest the Nether 1.7.10a.jar
  [✔️] personalspace-1.0.25.jar
  [✔️] PlayerAPI-1.7.10-1.4.2.jar
  [✔️] ProjectBlue-1.7.10-1.1.8-GTNH.jar
  [✔️] ProjRed-1.7.10-4.7.9-GTNH.jar
  [✔️] Railcraft-9.14.3.jar
  [✔️] RandomThings-1.7.10-2.4.3.jar
  [✔️] RemoteIO-1.7.10-2.4.8.jar
  [✔️] roguelike-1.7.10-1.5.3-GTNH.jar
  [✔️] RWG-1.7.10-alpha-1.3.3.2.jar
  [✔️] Schematica-1.9.3-GTNH.jar
  [✔️] SGCraft-1.7.10-1.3.13-GTNH.jar
  [✔️] sharewhereiam-1.7.10-0.2.0.jar
  [✔️] sleepingbag-1.7.10-0.1.4.jar
  [✔️] SpecialMobs-3.4.0.jar
  [✔️] SpiceOfLife-2.1.0-carrot.jar
  [✔️] SSP-1.1.2-GT-NH-Mod.jar
  [✔️] StevesAddons-1.7.10-0.10.27.jar
  [✔️] StevesCarts-1.7.10-2.0.2.jar
  [✔️] StevesFactoryManager-1.1.7-GTNH.jar
  [✔️] StorageDrawers-1.12.0-GTNH.jar
  [✔️] StorageDrawersBop-1.7.10-1.11.17-GTNH.jar
  [✔️] StorageDrawersForestry-1.7.10-1.11.17-GTNH.jar
  [✔️] StorageDrawersMisc-1.7.10-1.11.18-GTNH.jar
  [✔️] StorageDrawersNatura-1.7.10-1.11.17-GTNH.jar
  [✔️] structurecompat-0.4.0.jar
  [✔️] structurelib-1.2.7.jar
  [✔️] SuperTic-1.7.10-1.2.5.jar
  [✔️] Tainted-Magic-7.6.2-GTNH.jar
  [✔️] tcinventoryscan-1.7.10-1.0.12-GTNH.jar
  [✔️] tcneiadditions-1.2.2.jar
  [✔️] tcnodetracker-1.7.10-1.1.7.jar
  [✔️] TConstruct-1.9.36-GTNH.jar
  [✔️] TecTech-5.2.22.jar
  [✔️] TGregworks-1.7.10-GTNH-1.0.23.jar
  [✔️] Thaumcraft-1.7.10-4.2.3.5a.jar
  [✔️] Thaumcraft4Tweaks-1.5.7.jar
  [✔️] ThaumcraftMobAspects-1.7.10-1.0.0-GTNH.jar
  [✔️] thaumcraftneiplugin-1.7.10-1.7a.jar
  [✔️] ThaumcraftResearchTweaks-1.7.10-1.0.4.jar
  [✔️] Thaumic Machina-1.7.10-0.2.1.jar
  [✔️] Thaumic-Based-1.5.0.jar
  [✔️] thaumicenergistics-1.4.4-GTNH.jar
  [✔️] Thaumic-Exploration-1.7.10-1.1.94-GTNH.jar
  [✔️] ThaumicHorizons-1.2.1.12.jar
  [✔️] thaumicinsurgence-0.2.4.jar
  [✔️] ThaumicTinkerer-2.7.0.jar
  [✔️] TiCTooltips-1.7.10-1.2.10.jar
  [✔️] Tinkers-Defense-1.2.1d.jar
  [✔️] TMechworks-1.7.10-0.2.16.4.jar
  [✔️] TooMuchLoot-1.7.10-4.1.0-GTNH.jar
  [✔️] torohealth-1.7.10-1.0.1.jar
  [✔️] Translocator-1.1.2.21.jar
  [✔️] TravellersGear-1.7.10-1.16.6.jar
  [✔️] travellersgearneo-1.0.jar
  [✔️] TwilightForest-2.4.3.jar
  [✔️] txloader-1.5.2.jar
  [✔️] -unimixins-all-1.7.10-0.1.9.jar
  [✔️] Universal-Singularities-8.6.7.jar
  [✔️] visualprospecting-1.1.6.jar
  [✔️] Waila-1.6.0.jar
  [✔️] WailaHarvestability-1.7.10-1.1.10-GTNH.jar
  [✔️] WAILAPlugins-0.2.8.jar
  [✔️] WanionLib-1.8.4.jar
  [✔️] WarpTheory-1.2.16-GTNH.jar
  [✔️] Wawla-1.7.10-1.1.3-GTNH.jar
  [✔️] WirelessCraftingTerminal-1.9.2.jar
  [✔️] witchery-1.7.10-0.24.1.jar
  [✔️] WitcheryExtras-1.1.14.jar
  [✔️] WitchingGadgets-1.3.0-GTNH.jar
  [✔️] WR-CBE-1.7.10-1.4.8.jar
  [✔️] YAMCore-0.5.86.jar
  [✔️] Ztones-1.7.10-2.2.2.jar

Params:
  --username FireVoid --version 1.7.10 --gameDir C:/MC/instances/GT_New_Horizons_2.3.4_Java_17-20/.minecraft --assetsDir C:/MC/assets --assetIndex 1.7.10 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userProperties {} --userType msa --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx8096m, -Duser.language=en]

Minecraft process ID: 11236

Using onesix launcher.

[02:05:55] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
null
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:125)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:429)
	at cpw.mods.fml.common.launcher.FMLTweaker.<init>(FMLTweaker.java:35)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
	... 10 more
[02:05:55] [main/ERROR] [LaunchWrapper]: Unable to launch
Process exited with exit code 1 (0x1).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 30 Jul 2023 02:08:18 +0300
Clipboard copy at: 30 Jul 2023 02:10:23 +0300

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
you forgot the required arguments. please refer to the install instructions https://gtnh.miraheze.org/wiki/Installing_and_Migrating or try the help channel on our discord if that is still unclear. :)
