### ISSUE TITLE
World becomes invisible upon specific items being shown in NEI

### ISSUE THREAD

**Issue by max9076** [GTNewHorizons/GT-New-Horizons-Modpack#14100]
### Your GTNH Discord Username

gehoernchen

### Your Pack Version

first tested version 2.2.3.0, up to 2.3.5

### Your Server

SP/MP (irrelevant)

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I am browsing NEI and listing items. There should not be any changes, aside from the items coming into view. Any items on the fourth side of my search for "tool" make my world turn invisible.
Notably, I am using OpenJDK 1.8.0_382 on EndeavourOS (fork of Arch Linux). I have not encountered this bug on Windows with the same game instance (Prism Launcher).

![2023-07-29_14 01 57](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/56943128/3ec722ad-839e-4a42-8409-359cee295f56)

### The Reality

The world turns invisible. Upon opening a book (quest book, TiC, ...), the world turns visible again.
![2023-07-29_14 04 54](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/56943128/5195ef72-21b2-461e-a29c-be38f86ff8bf)
![2023-07-29_14 02 02](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/56943128/e6d30f56-0948-49be-9660-83ccb97b6c7b)

### Your Proposal

This seems to be a bug on my end; it would be great if you could help me fix this though.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
can you check if its the same as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12876?

**Comment by max9076** [comment]
Yeah, it is. Sorry, I could not find that one when searching for existing tickets.
