### ISSUE TITLE
LEG consumes significantly more catalyst fluid than intended.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#14104]
### Your GTNH Discord Username

abdiel_kavash

### Your Pack Version

2.3.4 with fixes from wiki

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

The Thaumonomicon describes the speed of consuming catalyst fluid of the LEG as:

> Basic consuming speed * Essentia coefficient * consumed Essentia amount

As an example, with the Air upgrade installed (160 L/s base consumption speed), using Aer essentia (1,000 EU, 1x coefficient) and Air catalyst fluid (1x efficiency), I expect the LEG to consume 160L/s of Air; or 8 L/t per point of essentia.

### The Reality

I have newly formed the LEG with novice diffusion casings and inserted 8 points of Aer essentia and some Air fluid. I started the LES. After consuming all the input essentia, the dynamo hatch has 8,000 EU stored (this should be correct), but 96 L of Air was drained from the input hatch. This corresponds to 12 L/unit of essentia, not 8 as the Thaumonomicon states.

### Your Proposal

The issue occurs here: https://github.com/GTNewHorizons/GoodGenerator/blob/aeb31bdfcd88c4d4a2ca256af564bb3f0a464253/src/main/java/goodgenerator/blocks/tileEntity/LargeEssentiaGenerator.java#L444C1-L462C1

The `getPerAspectEnergy` method used to calculate how much EU a single point of essentia should produce also already deducts the catalyst fluid from the hatch. However this method is also called in line 447 to check if the essentia type is valid. This call still uses up the catalyst fluid, but does not produce any energy. Therefore, if the essentia hatch receives 1 essentia/tick (as it would through essentia tubes, for example), this function is called and catalyst is used twice for every point of essentia burned.

In a more extreme situation, if the catalyst hatch is empty, and is only fed the bare minimum amount of catalyst necessary to sustain the LEG, it is possible for the first check to consume all of this catalyst and the LEG then never consumes any essentia nor generates any power. This I have also reproduced in a test world.

To fix this, either the result of `getPerAspectEnergy` should be cached, so that the catalyst is only consumed once; or the output calculation and catalyst consumption should be split into separate calls.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
is it still an issue with 2.3.6?

**Comment by KhonaB** [comment]
Something is clearly still broken, yes. I cannot claim to have necessarily been as thorough with the math, but I just repeated the experiment above (8 pts aer, fed via tube with the LEG already on and a full hatch of compressed air) and it generates 8000 EU each time but consumes 128 L of compressed air per run, which is 16 L/t for the 8 ticks it runs for.

**Comment by Caoga** [comment]
It seems like `getPerAspectEnergy` not being called twice, but being called each tick. I may be wrong here, but testing with Ira/Cryotheum on low voltages (HV 4A hatch) revealed unreasonable cryotheum consumption quite consistent with 10L/tick caused by this method on top of miniscule amount required to actually support whatever essentia is being burned.
