### ISSUE TITLE
[ProjectRed Transportation & Storage Drawers] Two way to crash using ProjectRed Transporation items with Storage Drawers

### ISSUE THREAD

**Issue by Elkatra2** [GTNewHorizons/GT-New-Horizons-Modpack#14108]
### Your GTNH Discord Username

.elkatra / 🌳 Elkatra 🌲 LV > ♾ 🌳

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions
I hope this somehow helps to improve one of my favorite mods :)

--- CRASH 1 ---

For the simpliest way to crash what you need:

1. Connect "Routed Intreface pipe" with "Item Extractor chip" with default parameters* to "Drawer Controller".
2. Connect 1 + n any kind of drawers (x1, x2, x4 or they thin variant) to the "Drawer Controller" (n must be >= 1). 
3. Put any item you want by hands to the drawer. 
4. Breack the drawer.
5. crash :trollface: + prevents to play in the save.

*right click on the air to open chip gui and then close that's enough for default parameters

--- CRASH 2 ---

The second crash is very similar to the first but instead of breaking the drawer, in this case we use an item which removes the driver from the storage system. The simpliest way to do is using for exemple "Dolly" from the JABBA mod or maybe other similar way. And again crash!

P.S. you may not be able to cause this crash the first time, repeat 2-3 times idk

### Crash Report
1) [crash-2023-07-30_18.24.46-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12209587/crash-2023-07-30_18.24.46-server.txt)
2) [crash-2023-07-30_18.43.16-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12209598/crash-2023-07-30_18.43.16-server.txt)

I noticed that in these two logs there is the same error, maybe there is a problem ?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Elkatra2** [comment]
I checked again and this crash does not always happen unfortunately (or fortunately). But for example, I just tried if after you put the chip that I described above and there was no crash, then you will need to take any item, put it in one of the drawers and then pull it out again and do such manipulations after 2-3 times it will crash again.

**Comment by boubou19** [comment]
is it still happening on 2.3.6?

**Comment by Elkatra2** [comment]
> is it still happening on 2.3.6?

I just checked in version 2.3.6 and... it still happening... 

[crash-2023-08-07_18.21.08-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12281981/crash-2023-08-07_18.21.08-server.txt)
