### ISSUE TITLE
Circuit Assembly Line Works with only 2 Slices

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#14109]
### Your GTNH Discord Username

Cainiaojun

### Your Pack Version

2.3.5 nightly

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

With Craft Input Buffer (ME) in the first slice and output bus in the second slice.
![QQ截图20230730221313](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/72213408/cdc9aac2-e492-4439-82c7-83b29baac76e)

### The Reality

IT WORKS!

### Your Proposal

DON'T fix it. It would be convenient to stack many 2-slices Circuit Assline in a relatively small area, which are much easier to control.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by hoshinokiseki** [comment]
please don't fix it. this smallest CAL relies on Crafting Input Buffer which can be made in UIV.

**Comment by joshaup1999** [comment]
This should be fixed, If things like the AAL or assline cant use the crafting input buffer then neither should the CAL

**Comment by hoshinokiseki** [comment]
> This should be fixed, If things like the AAL or assline cant use the crafting input buffer then neither should the CAL

But things are little different between CAL and AAL or assline. AAL or Assline has very strict limitation of item and fluid order but CAL can accept any item order. And Assline are the most important multi machine in the middle-late game. You cannot do somethings if you don't have a assline. But you can still make circuits without CAL. So in my opinion the support of crafting input buffer in CAL should not be removed.

**Comment by CaptGyrfalcon** [comment]
There is no need to fix this, it should be considered as a feature. As you need at least UIV to make this.
In late game stage, TPS falling is a very important issue, and things like this can improve performance, though, the price itself is much higher than the rest part of CAL. So, it's fair to take advantage of it to shorten the CAL and improve performance.

**Comment by cainiaojun** [comment]
> This should be fixed, If things like the AAL or assline cant use the crafting input buffer then neither should the CAL

I don't think so. Circuit Assline is different with Assline or Advanced Assline. It doesn't care about the order of input items, while it doesn't care about the voltage of recipe but the power of those. It would be a great QoL if we allow this bug existing.

**Comment by boubou19** [comment]
this will be fixed
