### ISSUE TITLE
High Current Industrial Arc Furnace Incorrect Voltage

### ISSUE THREAD

**Issue by bpwhelan** [GTNewHorizons/GT-New-Horizons-Modpack#14110]
### Your GTNH Discord Username

Beangate

### Your Pack Version

nightly-2023-07-29+73

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Industrial Arc Furnace to use 3A of 1 voltage level down from energy hatch.

### The Reality

Industrial Arc Furnace attempts to use 3A of Energy Hatch Voltage. If using two hatches, will attempt to use 3A of the tier above. This makes it to where the multiblock runs out of power instantly.

### Your Proposal

Require the "effective" voltage of one tier lower than the energy hatch as expected.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bpwhelan** [comment]
Saw this after i put in this issue, probably the same as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14105, GT5 API related likely.

**Comment by BlueWeabo** [comment]
Will take a look at it

**Comment by BlueWeabo** [comment]
Can you mention what hatches you used, what recipe was run, ect

**Comment by bpwhelan** [comment]
Yeah, Sorry was out.

Electric Arc Furnace Mode
Sand -> Glass, Also Tested Iron -> Wrought Iron
LuV Energy Hatch (both 1 and 2 tested)
HV Input Bus/Hatch
ME Output Bus
Uses like 91k EU (3A LuV) and runs out almost instantly.

Will test with plasma here in a sec.

**Comment by bpwhelan** [comment]
Plasma Mode seems to work as intended with 1 hatch, but attempts to draw 5 amps with 2 hatches.

Same Setup, Nitrogen Plasma, 1A LuV with 1 hatch, 5A LuV with 2 hatches.

**Comment by bpwhelan** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8314499/7b95b510-f916-4b04-bbb7-8d1fd1817a9e)
Ah, think it might be recipe related, numbers look fubar

**Comment by bpwhelan** [comment]
Seems like it might actually just be sand -> glass, tested out a few recipes that were at the same voltage as that recipe and worked just fine.

**Comment by Szajkop** [comment]
im having the same issue. updating to GT-PlusPlus-1.9.71 as mentioned in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14091 did not fix the issue.

**Comment by BlueWeabo** [comment]
Can you try if updating to https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.43.160 this version of gt5u can fix it? In the meantime i will test in gtpp dev

**Comment by bpwhelan** [comment]
> Can you try if updating to https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.43.160 this version of gt5u can fix it? In the meantime i will test in gtpp dev

Hmm, doesn't seem to fix anything with my original test case. It is weird tho, upgraded my multi a UV energy hatch and seems to be calculating properly.

**Comment by BlueWeabo** [comment]
Just made a PR about it as I found the error (most likely error)

**Comment by bpwhelan** [comment]
OK, I'll make a build of your branch to test real quick.

**Comment by bpwhelan** [comment]
Can Confirm fix works.
