### ISSUE TITLE
Binnie mods (Extra bees): Incorrect work of electrical stimulators

### ISSUE THREAD

**Issue by Zitata0** [GTNewHorizons/GT-New-Horizons-Modpack#14113]
### Your GTNH Discord Username

zitata

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I wanted to increase the range of the bee effect on my entire base, but I destroyed the world because of the modifiers on the territory.

### The Reality

Modifiers in electric tube do not add up, but multiply. Because of this, with the help of 2 intricate circuit boards with gold electrical tubes, it is possible to achieve x25 mutation, and with of 3 boards already x129. This applies to all modifiers except production. The territory modifier is the most dangerous, since with 4 boards (16 tubes) it is possible to lower the server's tps to 0.02 or more with a large number of tubes.

### Your Proposal

Modifiers in electric tube do not add up, but multiply in the electric stimulators of the hive. 
The maximum value of modifiers described in quests does not work, except for production.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/93836641/baade13c-d49c-4d51-abcc-440c16cb9ce7)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
Production does not work. How is it working for you? This may be related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13771

**Comment by desagas** [comment]
And, because I tried to solve my problem, and investigated heavily, modifiers never add, except for production, they multiply. This is the original code for forestry and binnnie, if I am not mistaken, it is GTNH that specifically changed the production to be additional, and only production.

**Comment by Zitata0** [comment]
Production is working properly after the corrections made 2 weeks ago (https://github.com/GTNewHorizons/Binnie/compare/2.1.6...2.1.8). In version 2.3.5, production does not ignore the maximum limit. Previously, production was multiplied and had an increase, as a mutation modifier, with which it was possible to achieve a 100% probability of obtaining any honeycomb.

**Comment by desagas** [comment]
Oh, sweet. Is it still turning them ignoble without passing the 16x like it was, or has that been fixed as well? I am excited to play with it again.

**Comment by Zitata0** [comment]
As before, bees with an increase in production of more than 16 become ignoble

**Comment by Zitata0** [comment]
"as before" is always. I've been playing with extra bees for a long time, but I don't recall that electric stimulators with diamond tubes have ever left bees pristine.
Diamond tubes give a high increase in production. Previously, diamond tubes worked the same way as everyone else, so even a small number of them made bees suffer. In 2.3.5, you can place 6-8 diamond tubes, and the bees will remain pristine.

**Comment by desagas** [comment]
Yes, but, that doesn’t fit in line with you 16x comment, nor the wiki, nor the quest lines, etc. 1 diamond tube is 2.5x, not 16x. It should not turn pristine ignoble. Therefore, it does not work as intended. And, if that is the intended code, then all of the quests related to it and the entire wiki is wrong. 

And, even extra bees original wiki states the same thing, and, since it doesn’t go over 16 x, it should not turn then ignoble.

Further, it is supposed to be a chance to turn, not 100 guaranteed, and even the in game overlay tooltips state that the diamond tube is identical in genetic decay to every other tube that can be used for production.

So, I’m just saying that something is very wrong in potentially many different places. Does that make sense?

**Comment by desagas** [comment]
I’m excited to try in 2.3.5. Thank you for letting me know that it was fixed. As my issue was never even commented on by a dev, I thought it was ignored. This is very exciting!

**Comment by Zitata0** [comment]
Why was the issue closed ?

**Comment by Dream-Master** [comment]
@Zitata0 maybe its fixed in newer GTNh version ? Did you test with 2.3.7 ?

**Comment by Zitata0** [comment]
I tested on version 2.3.7, but it wasn't fixed.

**Comment by Dream-Master** [comment]
@boubou19
