### ISSUE TITLE
AE2 Crafting Terminal's keyboard cursor is no longer at end of search characters

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#14112]
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

In 2.3.4 and previously, the keyboard cursor was always at the end of the character string in the search bar if one was present. This should still be the case in 2.3.5.

### The Reality

Instead, the keyboard cursor is now before all characters in a search string if one is present.

### Your Proposal

Change it back, as it interferes with muscle memory of using backspace, plus backspace is probably a more convenient option for deletion.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/366 ;)
