### ISSUE TITLE
ProjectRed project bench instantly breaking tools

### ISSUE THREAD

**Issue by 9551-Dev** [GTNewHorizons/GT-New-Horizons-Modpack#14127]
### Your GTNH Discord Username

dev9551

### Your Pack Version

GTNH 2.3.4 (2023-06-11)

### Your Server

SP

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

Trying to craft slabs/assumingly anything with tools inside the project bench should use the tools durability according to the amount of item crafted

### The Reality

Single item gets crafted and the tool breaks immedietly instead of just getting damaged

this was tested using the slab crafting recipe and a saw

### Your Proposal

having crafting with tools within the project bench handle tools the same way all other crafting stations do by just removing durability from the tool

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by dgealow** [comment]
Still an issue, it also consumes nonconsumables such as Pam's saucepan

**Comment by dgealow** [comment]
duplicate of / related to #11423
