### ISSUE TITLE
Coin trade for Empty Cells

### ISSUE THREAD

**Issue by HellFirePvP** [GTNewHorizons/GT-New-Horizons-Modpack#14126]
### Your GTNH Discord Username

hellfirepvp

### Your Pack Version

2.3.5

### Your Proposal

Add a new Coins trade for just a bunch of empty cells.

### Your Goal

Shortening the amount of time spent sitting around waiting on machines creating cells; especially LV-ish earlygame. The challenge is about creating and thinking out setups and actually building them & the machinery for it, less about sitting there watching your machine create 1 cell after another for the next half an hour.

### Your Vision

Usually when creating setups to juggle fluids or fluid filled cells around between machines, players might run into an issue of just not having cells around to add to the machines to properly handle the fluid transmissions or to just grab fluids out of machines and move them and reinsert the fluids.
Having to step away from creating and conceptualizing a machine line just to make cells and come back is very disruptive to the gameplay flow. A shorter alternative, such as just buying a bunch of cells with the plethora of coins around, would improve the situation.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I don't think I understand your problems. A cell is 5 seconds at 7 eu/t.

**Comment by Dream-Master** [comment]
we sell many items so i guess give cells for coins it not an issue.

**Comment by desagas** [comment]
I like this idea!

**Comment by boubou19** [comment]
why is waiting for empty cells an issue? automate it with hoppers or something and work on something else during that time?

**Comment by Hikari1nVoid** [comment]
With half an hour players could only craft less than 6 stacks of cells while in LV these things runs out fast. I don't get why people opposing so heavily on these small QoL updates.
Also, coins are being useless while they really kill storage spaces at early times!

**Comment by chochem** [comment]
not really opposing, no. Very much undecided myself. Just want to understand what is happening first and still don't see any explanation. Cells have always been very simple and fast in my runs.

How do you run out of cells? this sounds a bit like (the two of) you are using cells as mass fluid storage instead of making tanks?

**Comment by HellFirePvP** [comment]
Pretty much what Hikari also said.
You just run out of cells constantly in the earlier parts of the pack, moving liquids from here to there, leaving a stack here or there in combustion generators, so you don't have to babysit them, some cells being part of processing setups to can liquids and uncan them for machines, ...

If the argument is "just make them instead lol" then you can remove 90% of all coin purchases to begin with, as most of them are solved with "just go there and pick it up instead" or "just make 10 of them instead", ...

It's sometimes quicker to be able to buy 32 or whatever amount gets decided upon cells that you need at a moment's notice to move a machine that has liquids buffered up in it or such. You just.. need a good amount of cells to work on things. Needing to stop moving your diesel setup because you now have to sit in front of the extruder for the next half an hour just to empty out the machines and move their contents to another place is not riveting gameplay. Sometimes you just wanna make a stack or two more buffer cells to make the machines run for a while longer when you just wanna log off for the evening. I don't wanna sit there for half an hour waiting on more cells to be made when i actually wanna go sleep.

It's an early-game convenience thing, the same thing basically all the other coin trades solve/address. Moving fluids, buffering up fluids, ... is the most annoying LV to MV stage where everything also takes the longest. It's not about storage.

**Comment by BritishCynic** [comment]
There was a very specific point in my playthrough at the beginning when cells were just plain annoying to make, and honestly, a way to get empty cells at that point would have been welcome.

**Comment by Hikari1nVoid** [comment]
> How do you run out of cells? this sounds a bit like (the two of) you are using cells as mass fluid storage instead of making tanks?

The demands for cells are actually high. Let's start with your first EBF. It requires 4* any (let's assume combustion) and to keep it running overnight while players away keeping a half/full stack of light fuel (most durable fuel in LV) which easily takes 2/4 stacks of cells. And besides EBF You need to deal with those liquid byproducts from ores, early day chemicals such as oxygen/hydrogen/refined glue/rubber/.etc. Early day single-block machines CRs or electrolyzers also relies heavy on cells. And the early day GT pipe systems in LV are relatively expensive and not convenient compared to later fluid transport options in later stages.
As I mentioned above this is just a QOL quest. Tin is easy to acquire once you got a vein and I don't see the point of spamming this quest. It's just a great help so those poor guys in LV won't need to travel back to mining farm just for some cells.
