### ISSUE TITLE
Gas Sparging Recipes Can't Be Autocompleted in Pattern Terminal

### ISSUE THREAD

**Issue by RubiksImplosion** [GTNewHorizons/GT-New-Horizons-Modpack#14129]
### Your GTNH Discord Username

rubiksimplosion

### Your Pack Version

Latest Nightly

### Your Server

Private Server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Tried to auto complete a gas sparging recipe by shift clicking the question mark.

### The Reality

The question mark does not exist.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/39072130/bfaadbd6-646e-4f59-a46d-f17f8b666cc9)

### Your Proposal

Fix Sparge Tower recipes not being able to be autocompleted.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by fluffle** [comment]
Is it because the outputs are randomised, so perhaps the NEI plugin doesn't know what numbers to put there?

**Comment by boubou19** [comment]
more like the NEI handler wasn't made for this i guess.

**Comment by Steelux8** [comment]
What part of this is Galacticcraft? The recipe is from GT++.
