### ISSUE TITLE
Change back the way how Brickdust was handled within 2.3.0

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#14132]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

2.3.4

### Your Proposal

It seems that there was an undiscussed change for the recipe with the Brickdust which was turned into Raw Silicon Dust, Aluminium Dust and Oxygen.

Here is the old recipe from 2.3.0 pack:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1703441/46ced239-9159-4c82-8af0-8b810b59cb89)

This recipe was fine and has had also a nice supported processing line. But now it is gone and was replaced by an alternative ones where Alumina is used which I can't understand as Alumina has for me at last no proper usages compared to Aluminium Dust and where is the Oxygen from the old recipe? Vented by the Electrolyzer? I doubt this.

Here is the new recipe within 2.3.4 which at last I don't like:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1703441/b5f739a1-2b29-4f53-b612-b7599205c805)

### Your Goal

Revert that new recipe back to it's old one within the Chemical Centrifuge but change the required tier for it at last to MV one, if it's to early to get Aluminium just in LV.

If you are not satisfied with the Aluminium Dust as output then I am fine to deal with the Alumina ones but at last the Oxygen is it, what I would like to have back here even if it was also just fine to get Aluminium out of it within LV. Maybe it's just fine to adjust at last the tier to MV.

### Your Vision

It would not destroy the processing line to which it applied at 2.3.0 pack and I think that this was used by many players.
So let us discuss around it with the pro's and con's around that recipe, it's outputs, it's used machine and at last which tier you need to process it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
This recipe is LV. I am againt it to get pure alu dust at this stage.

**Comment by BritishCynic** [comment]
The obvious solution is for you to update your processing lines to accommodate this new change.

**Comment by Chaoschaot232** [comment]
> This recipe is LV. I am againt it to get pure alu dust at this stage.

Uhm, can re-read my inital post please? Like I said, I would also agree with the replacement from Aluminium Dust to Alumina Dust even if there are already plenty of ways in MV to get enough Alumina Dust out.
Also I stated that you can rais up the required tier to MV in addition to LV because I can understand you at this point that you don't want to give pure alu dust out at LV and since MV maybe is also not suiteable for you to give out pure alu then I am fine to get alumina out of it but at last within the centrifuge and with the oxygen in addition even on a reduced amount so maybe 3000L instead of the old value of 6000L

> The obvious solution is for you to update your processing lines to accommodate this new change.

In general this would be the easiest way. On the other side there speaks nothing against a conversation about a recipe change even if it's up to Deam at the end. But sometimes not every recipe change is good ones and to communicate this I have raised up that ticket for discussing about a back-change or at last a changed ones where you don't have to complealty swap out machines.

Well, tbh., there are many other players out and complaining about x and y but sometimes missing out a maybe suiteable compromise and this is what I have given here even when maybe a little bit hidden ;)

**Comment by desagas** [comment]
Further, to call it more "real" is really not even a correct way to describe the change in its PR. Silica will almost always be in clay, but they decided that this is best to nerf early game 'free' hydrogen. In essence as well do not like the changes that have happened to clay. The Dev team seem to have lost track of the message DreamMaster sent a few years ago, that there absolutely should multiple ways to get to certain points in progression, and just because one may be more appealing than the others does not mean that the others should be removed, blocked, or gated but, many of the 2.3.0 to now changes have put a dramatic choke hold on that concept.

So, I support this issue and request, I think bringing back the previous clay, clay dust, brick and brick dust recipes, as well as those related to titanium losing some magnesium in the process should be restored. Sure, remove hydrogen from the outputs, but, otherwise, keep it realistic.

I guess, in my opinion, things should fall in three pools when considering a change: two opposites -> does it do nothing to keep it the same, does it break anything to change, and lastly, is the required effort to change it worth the change it will make. Or, adversely, when considering a change, does the change break anything, does it do nothing for normal game play, and would the time to create the change be worth the limited changes.

**Comment by Chaoschaot232** [comment]
> Further, to call it more "real" is really not even a correct way to describe the change in its PR. Silica will almost always be in clay, but they decided that this is best to nerf early game 'free' hydrogen. In essence as well do not like the changes that have happened to clay. The Dev team seem to have lost track of the message DreamMaster sent a few years ago, that there absolutely should multiple ways to get to certain points in progression, and just because one may be more appealing than the others does not mean that the others should be removed, blocked, or gated but, many of the 2.3.0 to now changes have put a dramatic choke hold on that concept.
> 
> So, I support this issue and request, I think bringing back the previous clay, clay dust, brick and brick dust recipes, as well as those related to titanium losing some magnesium in the process should be restored. Sure, remove hydrogen from the outputs, but, otherwise, keep it realistic.
> 
> I guess, in my opinion, things should fall in three pools when considering a change: two opposites -> does it do nothing to keep it the same, does it break anything to change, and lastly, is the required effort to change it worth the change it will make. Or, adversely, when considering a change, does the change break anything, does it do nothing for normal game play, and would the time to create the change be worth the limited changes.

Thanks for the support :)

Would you accept that compromise to exchange raw alu for alumina dust? This should at last suite @Dream-Master so that you have to use other ways in LV to get raw alu in this tier and keep the oxygen (not hydrogen here, maybe in other recipes as well) or reduce it by 50% or maybe a bit more. Like a ratio from 9 Raw Silicon Dust and 3000L Oxygen which would be half of the current nerf here.

Do you also think putting it back to the Centrifuge would be better instead of letting it processed in the Electrolyzer? For me it is 50:50 because both machines are not wrong. Maybe most player would choose the Centrifuge here because it's well known for the recipe from 2.3.0 so better keep it there, how ever it would look at the end or moving it to the Electrolyzer instead 🤔

**Comment by Chaoschaot232** [comment]
Ok, I have done a little thing fast to get a better overview. Since it doesn't matter if the machine would be the Electrolyzer or the Centrifuge I have here 9 different recipes, including the old ones and the current ones. For now I placed them all in the Centrifuge.

Recipes a based around 13 and 17 Brick Dust as Input. For better splitting I added the Circuits which can be ignored because only one recipe should be picked or at last provided.

Time to discuss over them, I would say.

Recipe 1:

![](https://i.imgur.com/OMrV3Nc.png)

In: 13 Brick Dust
Out: 4 Raw Alu, 3 Raw Silicon Dust, 6kL Oxygen
Tier: MV (previously LV)

Recipe 2:

![](https://i.imgur.com/30jUH3i.png)

In: 13 Brick Dust
Out: 5 Alumina, 2 Raw Silicon Dust, 6kL Oxygen
Tier: LV

Recipe 3:

![](https://i.imgur.com/OYozBd0.png)

In: 13 Brick Dust
Out: 5 Alumina, 6 Raw Silicon Dust, 2kL Oxygen
Tier: LV

Recipe 4:

![](https://i.imgur.com/LSfuRdB.png)

In: 13 Brick Dust
Out: 5 Alumina, 4 Raw Silicon Dust, 4kL Oxygen
Tier: LV

Recipe 5:

![](https://i.imgur.com/vixqX4M.png)

In: 17 Brick Dust
Out: 4 Raw Alu, 7 Raw Silicon Dust, 6kL Oxygen
Tier: MV (previously LV)

Recipe 6:

![](https://i.imgur.com/nKGdFlM.png)

In: 17 Brick Dust
Out: 5 Alumina, 12 Raw Silicon Dust, no Oxygen
Tier: LV
**_Notice: I am against this one since the Formular states O11 which means that there is at last some Oxygen included._**

Recipe 7:

![](https://i.imgur.com/0f9ZWDG.png)

In: 17 Brick Dust
Out: 5 Alumina, 6 Raw Silicon Dust, 6kL Oxygen
Tier: LV

Recipe 8:

![](https://i.imgur.com/Xa53Nib.png)

In: 17 Brick Dust
Out: 5 Alumina, 9 Raw Silicon Dust, 3kL Oxygen
Tier: LV

Recipe 9:

![](https://i.imgur.com/MN0spY3.png)
In: 17 Brick Dust
Out: 5 Alumina, 3 Raw Silicon Dust, 9kL Oxygen
Tier: LV
