### ISSUE TITLE
Expand GT type filter categories

### ISSUE THREAD

**Issue by Solotov0** [GTNewHorizons/GT-New-Horizons-Modpack#14130]
### Your GTNH Discord Username

solotov5546

### Your Pack Version

2.3.5

### Your Proposal

Add additional filtering types to the GT Type Filters.  Some specific ones I'd personally want are wispy essence, essence shards, and combs.  Some other suggestions below
-Combs
-Drones
-Princess
-Wispy Essence
-Essence Shards
-Mana bean
-Seedbag
-*Chestslot item
-*Headslot item
-*Tool (Pickaxe, Hoe, Shovel, ETC)

### Your Goal

Nice to have a unified type of filter pre AE to deal with different items, all above requests are doable one way or another, but usually using several different mods

### Your Vision

Small QoL for pre AE timeline

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by YannickMG** [comment]
I'll add that a general review of the `OrePrefixes` enum is most likely needed. Many of them have always been there but are nearly empty and completely useless. For instance `mushroom` only matches a single item in the whole pack. Such empty categories should be removed or be made to include items they should reasonably match.
