### ISSUE TITLE
Recipe check error by across chunks

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#14133]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.3.0.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

Automated AssemblyLine, etc. across chunks and logged out (but all chunks are loaded).
![2023-08-03_12 38 39](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40425798/4052d4cf-55aa-4278-bd49-c5b75b4897a6)

### The Reality

Items are consumed halfway through the process, which interferes with the overall operation.

### Your Proposal

Everything was working correctly in v2.2.0.0, please fix
I think it is a combination with RailCraft's chunk loader because the problem does not occur with chunk loading due to the presence of a player (I think the behavior of the chunk loader has changed since v2.3).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
I assume they tell everyone in almost every guide ever, the quest book, and the wiki about gregtech multiblocks NOT working properly when put in multiple chunks for a reason.

**Comment by yukieiji** [comment]
I think this is probably due to a change in the chunk load specifications.

The following screenshots show the behavior when searching for the same item from the same network that is chunkloaded from the overworld and nether respectively.

overworld:
![2023-08-03_12 48 46](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40425798/e6617ec3-1250-49e8-a2c4-36a31ab58b3a)

nether:
![2023-08-03_12 49 16](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40425798/1442828f-fc71-4277-bb28-712237de1718)

**Comment by yukieiji** [comment]
> I assume they tell everyone in almost every guide ever, the quest book, and the wiki about gregtech multiblocks NOT working properly when put in multiple chunks for a reason. They actually go as far as to demand players NOT to do this.

But it was working correctly in ver 2.2
And obviously the same problem would occur with D.T.P.F., which needs to cross chunks.

**Comment by desagas** [comment]
> > I assume they tell everyone in almost every guide ever, the quest book, and the wiki about gregtech multiblocks NOT working properly when put in multiple chunks for a reason. They actually go as far as to demand players NOT to do this.
> 
> But it was working correctly in ver 2.2 And obviously the same problem would occur with D.T.P.F., which needs to cross chunks.

What I am saying is that it is clearly a known issue, it has been a known issue since multis were first introduced, they have told everyone who plays with GT how to prevent issues like this, they have said what can happen if it is done, like irreversible chunk corruption, etc. and people are still doing it. That is what I am saying.

I do understand your point, that it was working previously, but, that does not mean it was not working via a fluke or something else. I personally have had chunks corrupt a 400 hour world, and load order cause major crafting issues in many worlds, so, I recommend to everyone to always follow this principle rule when processing across chunks in every mod ever.

**Comment by desagas** [comment]
And, yes, I know what you mean. They recommend not to cross chunks, and then they create multis that must be built in something like 9 chunks. It makes end game in this pack worry me a lot..

**Comment by yukieiji** [comment]
> And, yes, I know what you mean. They recommend not to cross chunks, and then they create multis that must be built in something like 9 chunks. It makes end game in this pack worry me a lot..

These probably worked fine in v2.2. but they don't work in v2.3...

As per my second comment, I think this is probably not a GT issue, but a bug caused by the chunk loading not being reflected correctly.

**Comment by chochem** [comment]
Everything _should_ work fine if you chunkload it all. To my knowledge nothing at all was changed with RC chunkloaders.

However, thermos is a known source of such issues. And if you are playing with thermos (or in this case its crucible fork)
you should avoid chunkcrossing wherever you can.

**Comment by yukieiji** [comment]
> Everything should work fine if you chunkload it all. To my knowledge nothing at all was changed with RC chunkloaders.
However, thermos is a known source of such issues. And if you are playing with thermos (or in this case its crucible fork)
you should avoid chunkcrossing wherever you can.

I understand the issues around GregTech, such as AssemblyLine not working around chunks, but why are items not showing up on WirelessCraftingTable?

**Comment by yukieiji** [comment]
I used WorldAnchor and Anchor Sentinel to load the entire base again and it worked fine.
I have confirmed that this problem didn't occur in VanillaForge(only WorldAnchor), but only in Crucible.

**Comment by boubou19** [comment]
if it's happening only on crucible, it's beyond our scope of fixing.
