### ISSUE TITLE
Exxon Chemical plant batch mode gives the full output of a complete batch craft regardless of input quantity

### ISSUE THREAD

**Issue by johncabz** [GTNewHorizons/GT-New-Horizons-Modpack#14135]
### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

for It to craft the appropriate amount

### The Reality

Regardless of input quantities, it runs it as batch mode and gives you the full output as if you had a complete input full of materials.

Inputting 8000 air, 4000 nitric acid and 128 sandstone results in 1.5K fluorite ore output instead of the ~8-16 it should give back

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/21091833/1e652643-6101-4bda-9f0c-2e1ed494c5e3

### Your Proposal

correct batch processing, it was working correctly prior to 2.3.5

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Reflex18** [comment]
I can also confirm that this issue does occur in 2.3.5 with the chemical plant.
If you enable batch mode then it will always output the max batch amount regardless of the input of the recipe.
