### ISSUE TITLE
NEI shows recipe costs for steam grinder in EU rather than steam

### ISSUE THREAD

**Issue by dgealow** [GTNewHorizons/GT-New-Horizons-Modpack#14145]
### Your GTNH Discord Username

droideka30

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

I was trying to look up how much steam the grinder recipes take, so I looked up a recipe under "pulverization" and right-clicked the steam grinder. When I do that for the other steam tools (e.g. the steam macerator) it switches from showing the cost in EU to the cost in steam; but for the steam grinder it still shows EU.

### The Reality

Cost stayed in EU

### Your Proposal

Show cost in steam for steam grinder

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AtomicGrog** [comment]
All recipes are shown in EU as relative energy units not, in equivalent fuel cost. It's pretty much the standard energy type in this pack, sure there are a few odd machines that use RF etc. but they are by far the exception. In this case the recipes that the steam grinder processes are common throughout higher tiers as well.

Steam has a EU equivalent, looking at the basic steam turbine it's 2L of steam per EU so if you see a recipe needing say 10EU you know you need 20L of steam. Maybe that conversion could be clearer in the grinders info (Its depicted in the steam turbine for example).

**Comment by desagas** [comment]
I think you may have missed the point ... the way I understood it is that all steam GT machines when right clicked will show you how much steam it takes to process a recipe, where as the mutliblock steam machines do not. It would be beneficial to have the act the same, since they use the same inputs.
