### ISSUE TITLE
Nano Forge cannot run Perfect Overclock with Wireless hatches

### ISSUE THREAD

**Issue by CaptGyrfalcon** [GTNewHorizons/GT-New-Horizons-Modpack#14144]
### Your Pack Version

2.3.5 Nightly

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

When using wireless energy hatches, together with other conditions met, like Nanites and structure level over the recipe level, the Nano Forge should perform perfect overclock, as the tooltip suggests.

### The Reality

Nano Forge performed no Perfect Overclock, instead, all the overclocks performed are 4/2 ones.
However, it can perform Perfect Overclocks if using laser hatches(UHV 4096A in the test), but cannot perform with wireless hatches(UMV 64A in the test).

### Your Proposal

Make Nano Forge perform Perfect Overclock even with wireless hatches, just as the tooltip suggests

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TheEpicGamer274** [comment]
what is your current gt5u version?

**Comment by CaptGyrfalcon** [comment]
> what is your current gt5u version?
> 
> and which nightly/version are you on?

5.09.43.160
Version should be a nightly after 2.3.5 release, 2023.07.29-73. Though, I did update GT5u, BartWorks and GGFab
Bartworks is 0.7.36
GGFab is 0.2.3
