### ISSUE TITLE
2.3.4 LES Input Hatch bug

### ISSUE THREAD

**Issue by DarkRecent** [GTNewHorizons/GT-New-Horizons-Modpack#14140]
### Your GTNH Discord Username

Dark_Recent

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

I build a LES (Large Essentia Smeltery) in creative world I placed everything like it told me in NEI. but it didnot form correctly it told me structure is not complete.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/36361171/c3abfffe-7daf-47c2-a95b-039b8e00bab0)

### The Reality

Turns out u dont need a hatch altough it says mandotory on Tool tip.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/36361171/7170d78f-495c-45c4-80be-f8cdf72cc38b)
It formed when I removed the hatch.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/36361171/8698456b-07eb-4884-bcbc-c2e8cf34945d)

### Your Proposal

Either fix the tool tip or add the hatch function correctly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by yukieiji** [comment]
Also occurred in 2.4.0.0
