### ISSUE TITLE
Fastcraft Crash on My Server

### ISSUE THREAD

**Issue by Blursed12** [GTNewHorizons/GT-New-Horizons-Modpack#14143]
### Your Pack Version

2.3.0

### Your Server

Personal Server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Actions

I'm the local host and I'm trying to join my server so I can make a base for when my friends get on, but whenever I try to join the server I get a fastcraft error. When my friends try to join the server they also get the same error. It happens every time i try to join the server.

### Crash Report

[crash-2023-08-03_15.39.28-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12255569/crash-2023-08-03_15.39.28-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
that log is very useless I am afraid as fastcraft is closed source and obfuscated. please add the fml-client-latest and fml-server-latest, they might have much more info.

**Comment by Blursed12** [comment]
> that log is very useless I am afraid as fastcraft is closed source and obfuscated. please add the fml-client-latest and fml-server-latest, they might have much more info.

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12255612/latest.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12255613/latest.log)

**Comment by chochem** [comment]
so the same netty error as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13553
there the problem was the provider apparently

**Comment by Blursed12** [comment]
> so the same netty error as #13553 there the problem was the provider apparently

I'm running the server locally so does this mean its an issue with my IP?

**Comment by chochem** [comment]
more likely means they were wrong and it wasnt the provider.

**Comment by Blursed12** [comment]
interesting, do you have any idea what it is then?

**Comment by chochem** [comment]
maybe what miozune said

**Comment by boubou19** [comment]
Didn't Raven said FC was not supported on java 20?

**Comment by eigenraven** [comment]
FC is supported, I added specific compat for it (it was also only broken client-side originally)

**Comment by boubou19** [comment]
update your java 8 version (java 8u51 is ancient) and see if it happens again
