### ISSUE TITLE
Fluid brightness in GT machines changes when holding an item in hand

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#14146]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

2.3.4

### Your Server

private mp server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

If a mod is used to display anything over an item like DuraDisplay does it, it should never happen on any other items like in NEI or with any liquid in any machine. Just display that information on item x/y/z which needs it.

### The Reality

DuraDisplay causes an overlay error when you are holding an item in your hand, even if it's a simple torch.
This results in darker looking fluids in GT Machines, an shadow overlay over all NEI items and much more.

It vanish only when your hand is empty or when you completely disable that mod from the game, like f. e. removing it from your mods folder. It isn't enough to simply disable everything within the config.

### Your Proposal

Either throw this mod out of the pack as it doesn't makes sense to have it in or fix the overlay problem so that only items are getting the DuraDisplay values shown which are qualified but don't let it interact with any other item/liquid or what ever else hasn't todo with the mod. This means no shadow overlay in NEI, in GT Machines or where ever else this may happen.

It happens with plain vanilla textures but also with any other resourcepack.
It happens to every player on my server too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
still happens after removing duradisplay

**Comment by chochem** [comment]
but I can confirm that the fluid brightness in GT machines/tanks changes when holding an item in hand

**Comment by miozune** [comment]
I've been aware of the issue, but not sure how to fix it.

**Comment by Chaoschaot232** [comment]
Is there some "special" way how DuraDisplay or at last ModularUI handles this?
Is there in general a way to "tell" these mods only to "draw over that stuff" what is allowed to have an overlay? Means if there is a way to give this "overlay" smth. like a boundary and/or item limit 🤔
