### ISSUE TITLE
Too difficult to make GlowstoneNanites in UEV Tier

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#14152]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.3.0.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

I checked the recipe for Glowstone Nanites

### The Reality

GlowstoneNanites is needed to make the first UIV circuit in the UEV Tier, but UMV voltage is required.

### Your Proposal

Please implement another recipe for GlowstoneNanites, which is more costly and less amount, that works with NanoForge's Tier 1 UIV.
To run NanoForge at UEV tier with UMV voltage(Tier 2), you need a UEV 16A hatch and a facility that can output UEV 16A stably.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueWeabo** [comment]
I am not seeing how this is a problem. As I am pretty sure one only needs 1 nanite to do uiv circuits so it would be a one time cost. If one has the sufficient battery it can be done.

**Comment by yukieiji** [comment]
I haven't checked, but I'm assuming there are at most a few UIV circuits that can be done in a single run.

I have not been able to confirm how many UIV circuits are needed for the UEV and initial UIV, but I don't think that more than a few circuits will be enough. Then you would need to run the Tier 2 NanoForge on the UEV tier instead of battery power to keep it stable, right?

**Comment by BlueWeabo** [comment]
I would like to have more context on what you mean by 16A UEV is a lot. Could you elaborate what the problem is? Nano Forge uses voltage * amps to find recipes, so even using a laser hatch or multi-amp hatch will work.I just don't understand what the problem is.

**Comment by yukieiji** [comment]
The purpose of this ticket is to point out that it is wrong to require UMV at UEV tier.

I know of course that a multi-Amp hatch or laser hatch can input 16A, but isn't it wrong to require power generation systems that can withstand that early in the UEV?

**Comment by BlueWeabo** [comment]
Its normal. The higher tier you got your power needs grow exponentially more and more. In LV  you might need an amp or two, but as you go up you will see that you will be using way more than 1A of your tier to make anything. Thus you will need more than 1A of generation. I don't think its impossible or very hard even to get to 16A UEV for 1 multiblock, which isn't used that much. I think your whole base would be using more than that to keep running.

**Comment by yukieiji** [comment]
if it is normal for UEV to produce UMV, I don't see the need for NanoForge to have a tier 1 and a minimum operating voltage of UIV.
Why not just remove Tier 1 and make it all a UMV recipe? Currently, Tier 1 is just a passing point that is not thick enough to be called a tier.

**Comment by BlueWeabo** [comment]
No

**Comment by yukieiji** [comment]
Why?

Currently, NanoForge Tier 1 is only worthy of existence for making Neutronium Nanites, wouldn't it be very reasonable to cover the equivalent cost with AssemblyLine and ResearchStation

**Comment by BlueWeabo** [comment]
Just because it isn't used right now, doesn't mean it will never be used.

**Comment by S4mpsa** [comment]
Neutronium nanites are used for making the T9 mothership.

**Comment by yukieiji** [comment]
> Just because it isn't used right now, doesn't mean it will never be used.

Shouldn't the useless tiers be deleted rather than left alone, or should a new recipe be added as suggested in this ticket?

**Comment by BlueWeabo** [comment]
> > Just because it isn't used right now, doesn't mean it will never be used.
> 
> Shouldn't the useless tiers be deleted rather than left alone, or should a new recipe be added as suggested in this ticket?

No tiers will be deleted, nor will a new recipe be added. A recipe hasn't even been suggested and I can't see how its too difficult currently. The tier 1 currently doesn't have many uses and removing it right now makes no sense as the entire multiblock will have to be re-tiered to have 2 tiers and not 3.

**Comment by yukieiji** [comment]
> No tiers will be deleted, nor will a new recipe be added. A recipe hasn't even been suggested and I can't see how its too difficult currently. The tier 1 currently doesn't have many uses and removing it right now makes no sense as the entire multiblock will have to be re-tiered to have 2 tiers and not 3.


This is what the ticket says. "Please implement another recipe for GlowstoneNanites, which is more costly and less amount, that works with NanoForge's Tier 1 UIV."

Personally, I think that a recipe for about 1 GlowstoneNanites of quadruple Glowstone and LuV circuit etc.

**Comment by TheEpicGamer274** [comment]
I still don't see how this is an issue with it, if you are not making a umv amp+ in uev you have a bigger concern to worry about.
