### ISSUE TITLE
Reduce the "red" value on bloodmoon

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#14154]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

2.3.5 latest nightly 81

### Your Proposal

As you can see, the red overlay on a Blood Moon is somehow a bit of eye cancer. I understand the meaning behind this and I also found:

`# Purple is always better than Red. But I won't tell you how to live your life. Even if it is incorrect.
    B:"Is RED > PURPLE?"=false`

But is this rely the best solution, if it's that value which turns the red into purple on a Blood Moon?
I would say no because the red overlay in general is just fine but it's to hard.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1703441/91934efd-0e39-4712-9dad-4bc7b08bc3b8)

### Your Goal

I request to reduce the intensity of this red overlay and also it should get some opacity if possible.

Maybe it can be on the same level as HardcoreDarknes Mod doing it but instead of turning everything black
at night time or in an unlit area, turn it red. If the area is lit up with what ever light source let it emit then a red
light instead of the normal ones to indicate that there is a bloodmoon.

On top of that, maybe you can add some blood dips dropping from these light sources as effect (configurable)
on a Blood Moon.

But at last don't let it hurt our eyes so hard as it's currently happaning.

### Your Vision

It would no longer be killing your eyes with this high red value so that you can continue with your work.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by desagas** [comment]
Or, have it as a togglable alpha value. So, you can set it as strong or weak as you would like it to be.

**Comment by Dream-Master** [comment]
@Chaoschaot232 no i like how Bloodmoon look like.
