### ISSUE TITLE
Tee Growth Simulator overloading server when working on GT 5.09.43.162

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#14153]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.3.5

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

1

### The Reality

<img width="1496" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/29a894ad-229f-4aec-a42c-0d7a298fd4a9">

### Your Proposal

1

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Chaoschaot232** [comment]
Can you try to show us your setup without a running TGS and which sapling/recipe have you used?
Is the multie also within one chunk?

**Comment by lordIcocain** [comment]
Updating to GT++ to 1.9.74 fixed problem
