### ISSUE TITLE
Recipes for Molybdenum IV Oxide and Tellurium IV Oxide (for Kevlar) missing?

### ISSUE THREAD

**Issue by fluffle** [GTNewHorizons/GT-New-Horizons-Modpack#14159]
### Your Pack Version

2.3.4 + wiki fixes

### Your Server

Private MP

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

I finally bit the bullet and started digging through the kevlar chains to make a T9 rocket and get some tengam.

Deep in dependency hell, I discovered that making 1,4-Butanediol requires Te-Mo-O2 catalyst, which is made from MoO2 and TeO2.

They're defined here in GTNH-Lanthanides:

https://github.com/GTNewHorizons/GTNH-Lanthanides/blob/56813374074e3fb62d13328bfdba8b7f1a82e2f0/src/main/java/com/elisis/gtnhlanth/common/register/WerkstoffMaterialPool.java#L875

And the catalyst recipe exists:

https://github.com/GTNewHorizons/GTNH-Lanthanides/blob/56813374074e3fb62d13328bfdba8b7f1a82e2f0/src/main/java/com/elisis/gtnhlanth/loader/RecipeLoader.java#L1051

So I *expected* that recipes for these oxides would exist somewhere, so that I can make myself miserable with Kevlar.

### The Reality

Neither of these dusts appear to have recipes, AFAICT. At least, NEI says not, and there's no other references to those dusts in the GTNH-Lanthanides codebase. And there never have been according to some poking around in git history?

### Your Proposal

I am assuming there should be recipes along the lines of:

- 1 Te Dust + 2000 Oxygen -> 1 TeO2
- 1 Mo Dust + 2000 Oxygen -> 1 MoO2

Or does everyone just use the kevlar bee instead? :-)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
Probably you should use this recipe
<img width="415" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/bbf2eab6-d06b-4767-96e0-355dd612a040">
and Te-Mo-O2 catalyst should be remove, but who knows

**Comment by fluffle** [comment]
Arrgh of course there was a second page in NEI that I missed. Thank you!

This bug is still a bug, but not a show-stopping one.

**Comment by fluffle** [comment]
I'm happy to send a small PR to remove the Oxides, the catalyst and the 1,4-Butanediol recipe using it if that's what the devs want, should one of them see this bug.

**Comment by boubou19** [comment]
is it still happening on 2.3.6?

**Comment by fluffle** [comment]
I have not yet braved the upgrade since it has some major implications for my powergen setup, but I checked the master branch of GTNH-Lanthanides yesterday and couldn't find a recipe with `git grep -C3 TelluriumIVOxide` at HEAD, so I am guessing that it's still the case. Are you expecting these oxides to have recipes?

**Comment by fluffle** [comment]
Upgrade complete without problems so far, can confirm these recipes do not exist in 2.3.6 either. The Te-Mo catalyst route is a significantly less obnoxious pathway to 1,4-butanediol (provided you have sufficient butane) so I am assuming it is not intentional :-)
