### ISSUE TITLE
Allow custom multiplier in double patterning

### ISSUE THREAD

**Issue by ramseyspace** [GTNewHorizons/GT-New-Horizons-Modpack#14166]
### Your GTNH Discord Username

Ramsey#7916

### Your Pack Version

2.3.5 Beta

### Your Proposal

Allow us to set + or - multiplier amount in terminal (when right clicking 2x). Also, when multiplying make the same type not double stack slots in pattern like this *for processing pattern*.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/61401431/bd09ece5-c1ce-4d85-b8ca-f603606c4377)

### Your Goal

To reduce manual typing numbers and faster to pattern or repair size quicker.

### Your Vision

Many thousands of recipes need to be upgraded or make it larger for better parallel and interface counts would be reduced.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by firenoo** [comment]
Did you update to latest AE2+AE2FC? I doubt you need more than 2x or 8x with shift

**Comment by ramseyspace** [comment]
> Did you update to latest AE2+AE2FC? I doubt you need more than 2x or 8x with shift

I have not, but after hearing teg mentioned few mins after posted,

**Comment by ramseyspace** [comment]
I accidently closed, I havent updated but i would like to still set my own multiplier still so can be done within 1 click
