### ISSUE TITLE
ME controller randomly becomes gray (appears as if it loses power)

### ISSUE THREAD

**Issue by harrynull** [GTNewHorizons/GT-New-Horizons-Modpack#14167]
### Your GTNH Discord Username

harrynull

### Your Pack Version

2.3.5

### Your Server

private server

### Java Version

Java 19

### Type of Server

None

### Your Expectation

me network stays on stably

### The Reality

randomly becomes gray even though directly connected to a creative energy cell and appears as if it lost power. need to break and replace one of the controller to fix

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
this is because you don't have enough buffer in the network. Add some dense energy cells and it should solve the issue. Alternatively, there was a PR to avoid power calculation if a creative cell is placed, dunno if it made it through 2.3.6tho

**Comment by TimberDimber** [comment]
If you're using a Crafting Input Buffer, make sure it's only connected on one side. I had a similar problem and spent 12 hours looking for the cause. It turned out that one buffer was connected with two cables, which was causing network congestion.
