### ISSUE TITLE
Oddity with Barnarda C Saplings

### ISSUE THREAD

**Issue by Gofer2x** [GTNewHorizons/GT-New-Horizons-Modpack#14163]
### Your GTNH Discord Username

gofer776

### Your Pack Version

2.3.6

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Trying to craft this recipe. 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45763255/29b4f179-22b5-4861-9e95-db78e1763547)

### The Reality

It doesn't work.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45763255/414b14c1-a50f-43c5-ac04-d084fb793247)

(There was a whole bunch of stuff here, edited out because I missed something obvious)

There are two types of these saplings, one with a damage value of 0 and one of 1. 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45763255/09e6dc88-4cb4-435c-b019-d4bcab67e6cf)

Barnarda trees drop the variant with 1 damage, but placing one down and breaking it drops one with 0 damage.
The TGS recipe uses the 1 damage variant, and the Barnarda planet item recipe uses the one with 0.

### Your Proposal

Fix, maybe unify them into one or something.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
The screenshot you sent with the /nbtedit output shows that the two variants are not the same, they have different damage (meta) values. Should be rather easy to fix.

**Comment by Gofer2x** [comment]
Oh, I somehow missed it that completely multiple times, lol. Okay that explains a whole lot.
