### ISSUE TITLE
Titanium processing loop creates chlorine from thin air

### ISSUE THREAD

**Issue by truenachtara** [GTNewHorizons/GT-New-Horizons-Modpack#14160]
### Your GTNH Discord Username

Nachiebree

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 19

### Type of Server

None

### Your Expectation

The titanium loop should be a closed loop with no excess input or output other than rutile and titanium.

### The Reality

Excess chlorine is created from thin air.

### Your Proposal

Use 8000L chlorine in the rutile recipe instead of 4000L but keep everything else the same

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
4000Cl->1000TiCl
1000TiCl->6MgCl
6MgCl->8NaCl
8NaCl->4000Cl
I dont get where problem. 2.3.5 btw

**Comment by truenachtara** [comment]
seems to be fixed in later versions nevermind (2.3.4 seems to be the one with the issue)

**Comment by chochem** [comment]
check out https://gtnh.miraheze.org/wiki/Dev_Release_Stability
2.3.4 has a major bug about many fluid recipes.
