### ISSUE TITLE
rebalance magneto circuits by adding skip potential

### ISSUE THREAD

**Issue by FS21114** [GTNewHorizons/GT-New-Horizons-Modpack#14172]
### Your Pack Version

2.3.0

### Your Proposal

[BUFF] move magnetos earlier into progression making them avaiable since HV
[BUFF] make magnetos craftable in similar fashion to SOC circuits (for example:
SSOC + MV cassembler = ULV magneto
SSOC + HV cassembler = LV magneto
SOC + EV cassembler = MV magneto
SOC + IV cassembler = HV magneto
ASOC + LUV cassembler = EV magneto
ASOC + ZPM cassembler = IV magneto
etc)
[BUFF] make magnetos avaiable craft circuits up to current circuit assembler max circuit + 1 (so LUV for HV, or UV for IV)
[NERF] make magnetos significally more expensive, by requiring 4x of itself to uptier (so 4 EV magnetos into one IV)
[NERF] make each brand new craft of magneto more costly by requiring circuit of same tier in crafting (if you wish to craft HV magneto you must add HV circuit to it, you cant just make it from SOC or else it would be too cheap)
[BUFF] move advanced and optical SMD into higher circuit tiers along with making all other magneto components avaiable earlier to make crafting +1 tier circuits possible

### Your Goal

at current state magnetos serve no purpose, by being both too useless and too expensive, players clearly didnt like them since they demanded nerfs. so instead, we can make them even more expensive in exchange for actually having some other benefit, which is **access to circuits one tier higher than current circuit assembler limit**. i know some people dont like skips, that why im suggesting it to be avaiable only to one tier higher, along with neat price of 4096 magnetos in order to put your hands on single uptiered circuit!

### Your Vision

if magnetos have to be absurd in price, make them, make them even more expensive even, but give them some other benefit, in this case access to +1 tier circuits

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Why we not use this circuits for special cases (machines etc) and remove oredict so they more unique and usful?

**Comment by boubou19** [comment]
that's a nice idea tbh

**Comment by Steelux8** [comment]
I do like special circuits meant to be used in specific places, adds more diversity to content instead of using the same circuits in more and more recipes. I'm thinking of doing the same with some circuit ideas in the future.

**Comment by Reflex18** [comment]
Since this has been closed due to limited to no interest, why not start the discussion about the removal of the magneto circuits?

These circuits currently are there to serve as a confusion and clutter when viewing the circuit lists and should be slated for depreciation and subsequent removal.

**Comment by chochem** [comment]
> Since this has been closed due to limited to no interest, why not start the discussion about the removal of the magneto circuits?
> 
> These circuits currently are there to serve as a confusion and clutter when viewing the circuit lists and should be slated for depreciation and subsequent removal.

see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12951
