### ISSUE TITLE
Patterns which include fluids are not able to be doubled.

### ISSUE THREAD

**Issue by istreee** [GTNewHorizons/GT-New-Horizons-Modpack#14175]
### Your GTNH Discord Username

istree

### Your Pack Version

2.3.6

### Your Server

private

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

When clicking the x2 button in ae2 interface (both processing pattern terminal, and universal wireless) the fluid inputs for a pattern are doubled along with the outputs. 

### The Reality

Only the outputs are doubled. 

### Your Proposal

make the inputs be doubled too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by S4mpsa** [comment]
Fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/153
