### ISSUE TITLE
Crash opening some branches of questbook

### ISSUE THREAD

**Issue by berta24** [GTNewHorizons/GT-New-Horizons-Modpack#14174]
### Your GTNH Discord Username

Berta24

### Your Pack Version

2.3.6

### Your Server

private server

### Java Version

Java 20

### Type of Server

None

### Your Actions

when i start the game and open the questbook it works, as soon as i click on a category it crashes to main menu, the game stays on.

here is the crash report

### Crash Report

[crash-2023-08-07_20.25.11-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12284121/crash-2023-08-07_20.25.11-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by tommmmmmmmm** [comment]
We were using 2.3.4, this started to happen when we updated to 2.3.6

**Comment by boubou19** [comment]
looks like quests are missing somehow

**Comment by chochem** [comment]
I can have a look in the evening. what quest lines are we talking about? at least one example would be useful.

**Comment by berta24** [comment]
Steam - LV - MV - AE2 
all these make the game crash, havent checked about the others

**Comment by Dream-Master** [comment]
> Steam - LV - MV - AE2 all these make the game crash, havent checked about the others

remember to replace the questbook files each update not override them.

**Comment by berta24** [comment]
probably some files didnt copied  correctly over to the server or got corrupted...
after replacing every file again (from the dropbox site) and reloaded everything it's now working

thanks and sorry for having wasted your time
