### ISSUE TITLE
Client renders only as far as the server's render distance is

### ISSUE THREAD

**Issue by Niels1006** [GTNewHorizons/GT-New-Horizons-Modpack#14184]
### Your GTNH Discord Username

@niells

### Your Pack Version

2.3.6

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Cached chunks will still be rendered when flying around, as long as they are in the client's render distance.

### The Reality

When flying around, new chunks within render distance of 8 generate, and > render distance of 8 chunks unload randomly:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16525967/92fd6d40-1055-4179-9d45-914381fd6251)

This results in a render distance of 8 after a few seconds:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16525967/c2bed937-c5ed-46a3-b86d-5a0105af8f76)

I tried it without OF, but it didn't work. My client's render distance is 32.

### Your Proposal

Dont unload cached chunks within client's render distance.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
do you have any custom mod added to the pack outside of optifine?

**Comment by Niels1006** [comment]
Yes, ftblib and ftbu.
Removing them doesnt make a difference.
I also had this problem in 2.3.0, .2, .5 and now .6

**Comment by Niels1006** [comment]
I just made a new instance and now it suddenly works when i remove optifine. Was anything changed regarding rendering in 2.3.6? Because it definetly didn't work w/o optifine pre 2.3.6 for me.

Also, do you know what optifine setting causes this? I tried to play with the settings but i couldnt get it to work.
