### ISSUE TITLE
Processing Array overclocks instead of running parallel recipes

### ISSUE THREAD

**Issue by LordBoompa** [GTNewHorizons/GT-New-Horizons-Modpack#14186]
### Your GTNH Discord Username

boompa.

### Your Pack Version

2.3.6

### Your Server

private server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

With 16 hv macerators in a PA, it should parallel 16 hv recipes

### The Reality

The PA overclocks the 16 hv macerators into 1 IV macerator recipe, using extra power. For example, running 16x 5 sec 32 eu/t recipes (HV overclocked) should cost 512 eu/t and take 5 sec. However, it actually takes 1.25 sec and takees 4096 eu/t.

I have tried rebuilding the multiblock and changing all settings in the controller with no luck, and tested the same setup and recipe in 2.3.4, and it works perfectly fine in the earlier version.

### Your Proposal

Return PA back to normal functionality of paralleling instead of overclocking.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alaking** [comment]
wait so does the recipe youre testing with take 5 secs at 32 eu/t or at HV overclocked? 
also 4096 eu/t  for 16 HV machines sounds accurate, puts per machine power at 0.5A HV

**Comment by LordBoompa** [comment]
These are for ore processing so the base is 2 eu/t at 20 sec, at hv it's 32 eu/t at 5 sec. 16x that recipe should only cost 512 eu/t. I went back to 2.3.4 with the same setup and it was the correct 512 eu/t

**Comment by Sopel97** [comment]
It's incorrect in the first place that it overclocks higher than machine tier

**Comment by BlueWeabo** [comment]
Also no clue how you actually managed that.... It should do parallels first....

**Comment by Sopel97** [comment]
It is doing parallels correctly. 16x256EU/t
