### ISSUE TITLE
Chemplant generating empty catalyst carriers after every recipe

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#14191]
### Your GTNH Discord Username

.querns

### Your Pack Version

2.3.6

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

I expect to only receive empty catalyst carriers when a chemplant exhausts one of the catalysts, not during every cycle.

### The Reality

The reproduction scenario appears to be the following:

* Perform a recipe that uses a catalyst. E.g.: making 2-Ethylanthrahydroquinone using orange metal catalyst.
* Perform another recipe while a partial catalyst item is in the right side of the catalyst housing.
* The output bus should accrue a new catalyst carrier on every cycle of the chemplant.

### Your Proposal

Ensure that empty catalyst carriers are only ejected when they are truly exhausted.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hikari1nVoid** [comment]
Why not just change the catalyst to NC?
Also, catalyst got consumed sounds so freaking funny.

**Comment by querns** [comment]
> Why not just change the catalyst to NC? Also, catalyst got consumed sounds so freaking funny.

The design of the catalysts in the chemplant is such that they only become not-consumed when you've upgraded the multi enough. Otherwise, they slowly get used up over time.

**Comment by chochem** [comment]
yea lets not remove interesting good mechanics

**Comment by chochem** [comment]
well I cant really reproduce this. but the behaviour is also wrong on my end!

when I do step 1 (perform a recipe that needs a catalyst) all works fine. when I then do step 2 (perform a different recipe), then it incorrectly just continues to use the catalyst the recipe doesnt need. After it is fully used up a single catalyst carrier is spit out. And then the machine breaks down alltogether, claiming there is insufficient output, even though all output is empty. Had to break and replace controller to make it work again.
