### ISSUE TITLE
Introduce An Electromagnetic Seperator Multiblock

### ISSUE THREAD

**Issue by Ilithios06** [GTNewHorizons/GT-New-Horizons-Modpack#14192]
### Your GTNH Discord Username

ilith (legacy: Ilith#7274)

### Your Pack Version

2.3.6

### Your Proposal

Add a new dedicated Multiblock machine for the electromagnetic seperator. The Polarizer could also be moved from the LPF to this new Multi, such that it would serve as the "Magnet Multi". (I havent considered the gating of this multi yet, similar gating to most other gt++ multis is probably appropriate)

### Your Goal

With the introduction of Tengam and its necessary processing step in an electromagnetic seperator, people are realizing the missed potential of a dedicated seperator multiblock.

### Your Vision

This new multiblock could also make the electromagnetic processor a considerable step in ore processing, as its currently being held back by only being "viable" in a PA. It would also make the endgame more interesting, with a new multiblock rather than another thing you need to spam PAs for.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Steelux8** [comment]
This will happen with mutes. It's one of the multis I will add, if nobody else does, since I'm already going to break up the LPF into dedicated multis.
