### ISSUE TITLE
Add a Button to Disable Seperated Slots Mechanism of Crafting Input Buffer (ME)

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#14197]
### Your GTNH Discord Username

Cainiaojun

### Your Pack Version

2.3.5

### Your Proposal

Add a button that enable players to disable the seperated slots mechanism of Crafting Input Buffer (ME), so that players could cause artificial recipe conflicts or materials mixing.

### Your Goal

PCB need a lot of nanties to do its recipe with parallels. One slot is not enough (7 parallels). And so does 9 slots (10 parallels). I use a independent UHV super input bus filled with nanities to provide enough parallels.

_Of course, if you are willing to add 160 extra slots to the crafting input buffer, that's better!_

### Your Vision

Use a crafting input bus to provide materials while using a normal input bus to provide enough nanities.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
they are very much designed to be fully separated. if that is not what you want in a specific multi, maybe you should think about how to solve the automation with different tools.

**Comment by cainiaojun** [comment]
> they are very much designed to be fully separated. if that is not what you want in a specific multi, maybe you should think about how to solve the automation with different tools.

_Well so we can't add 160 extra slots for nanties?_
