### ISSUE TITLE
Name mold causes machine crash in large forming press when using crafting input bus

### ISSUE THREAD

**Issue by CactusCool** [GTNewHorizons/GT-New-Horizons-Modpack#14194]
### Your GTNH Discord Username

Cactus_Cool

### Your Pack Version

2.3.6

### Your Server

private server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Machine works and outputs named item.

### The Reality

![Screenshot 2023-08-09 135000](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/67992303/539ff31a-e751-40ff-b9e7-58f4ae4915f3)

the machine gives a crash error 

### Your Proposal

fix crafting input bus to work with name plates. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
anything in the log? maybe just post the fmlclientlatest

**Comment by harrynull** [comment]
Is this only happening with crafting input bus? Have you tried it with a regular input bus

**Comment by CactusCool** [comment]
> Is this only happening with crafting input bus? Have you tried it with a regular input bus

just tried with a regular bus and its also happening. When I have it not in void mode it says no output space despite having a me output bus.

**Comment by CactusCool** [comment]
nothing in logs as well.

**Comment by chochem** [comment]
what about all regular hatches/busses?

**Comment by CactusCool** [comment]
> what about all regular hatches/busses?

just tried super busses only that also cased crashes

**Comment by chochem** [comment]
guess I got to test myself then. Lets start simple:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/fd5907af-5f20-4928-92e6-c262ab271b10)

**Comment by chochem** [comment]
now ME output bus:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/c0779923-2a8f-472e-8451-a651d5bf35f1)

**Comment by CactusCool** [comment]
I have one large forming press that works find an another right beside it having issues.

**Comment by CactusCool** [comment]
I think I just figured out the issue. The multiblock had no energy hatch but it still formed and gave wrong error codes.

**Comment by chochem** [comment]
crafting input bus also works
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/da1ab7b6-50ee-4916-9748-4af6a0212ecd)

**Comment by miozune** [comment]
Since you're playing on server, error exists on server log, not client
