### ISSUE TITLE
Colouring Backbone In-world Changes them from smart to covered

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#14204]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

When colouring in-world by using the colour applicator form AE2 it should stay in its form, and not transmute to something else. So, it should become a backbone smart cable - red, not a covered backbone cable -red.

### The Reality

It converted to a covered backbone cable - red.

### Your Proposal

Fix?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
backbone cables are now deprecated in dev and will be removed in the future (but not yet in 2.4.0).
