### ISSUE TITLE
2.3.6 - Phthalic Acid Duplicate

### ISSUE THREAD

**Issue by SomeGuyDoinWork** [GTNewHorizons/GT-New-Horizons-Modpack#14205]
### Your Pack Version

2.3.6

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Reading the changelogs, there should now be only 1 Phthalic Acid Liquid.

### The Reality

There is 2. One from GT++ and one from Gregtech.

### Your Proposal

Merge into 1 liquid.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I think you misread the changelog. or there is a typo in it.

**Comment by SomeGuyDoinWork** [comment]
Regardless, it would be nice to have this on the roadmap.

**Comment by chochem** [comment]
yea would certainly be good to remove the gt++ one at some point after stable.

**Comment by SomeGuyDoinWork** [comment]
is it really that hard to merge the two? or maybe even rename one for the stable?

**Comment by chochem** [comment]
we are in feature freeze. Also cant say I see any point in renaming, that wouldnt change anything.

there is a reason we have a feature freeze before stables and not do such changes now. its far to easy to miss one recipe that uses the removed one, or a quest, or who knows what. We will get to it afterwards.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GTplusplus/pull/737
