### ISSUE TITLE
Molten Obsidian broken recipe

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#14212]
### Your GTNH Discord Username

hucking

### Your Pack Version

2.3.6

### Your Server

Private

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

when trying to make raw hardener to make Raw Hardener to make Galgadorian I saw the recipe is using the wrong type of molten obsidian.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1339552/39c50ad8-63bc-4aa0-bd22-300ca8cffa14)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1339552/fd23d821-082e-44e8-8301-07291a1fdd07)

### Your Proposal

Change the recipe to use the (what I assume is) newly added gt molten obsidian instead of the old TC fluid. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
nah thats not new. did the recipe used to be different? then its probably a wrong conversion from scripts.

**Comment by hucking** [comment]
idk if the fluid is new but this is the pattern i had in my MCR 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1339552/9e671219-7002-4248-a78c-68defbd988a0)

**Comment by chochem** [comment]
actually, just loaded up stable and you were actually right. it is new. looking back a bit it looks like dream added more parts to obsidian which probably included the fluid.

hmm that makes this less clear for me. Which type *should* this use? The gt one is gated by MV of course. There is also the REP from the wireless redstone mod with the same issue.

**Comment by hucking** [comment]
i mean considering in the past when you put obsidian in the fluid extractor it would make the TC molten obsidian I think it would make sense to either revert everything back to TC molten obsidian as it was or just use the new GT fluid for those recipes.

**Comment by AbdielKavash** [comment]
The fewer oddball TiC and other fluids that don't interact well with NEI and cells and all there are after stone age, the better.
