### ISSUE TITLE
Updating older world to 2.3.6 creates server log spam.

### ISSUE THREAD

**Issue by Alessandro404** [GTNewHorizons/GT-New-Horizons-Modpack#14216]
### Your GTNH Discord Username

Darmin404

### Your Pack Version

2.3.6

### Your Server

personal server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Nothing happens

### The Reality

Updating an older world makes so that a spam log happens every second or so.
New world made with the newer versions do not have this problem.

the problem seems to be inside the world folder in the server, and happens without players and only on the older world folder. For the player prospective, everything seems to play perfectly.

The last version of the world was 2.3.0

For my very limited understanding, something clientside tries to run in the server. The server modlist is the basic one, plus aroma backups and webmap, none of those ever gave me problems.

### Your Proposal

simply fix the logpsam

I searched the issues with " java.lang.NoClassDefFoundError: net/minecraft/client/audio/ISound " and similar, because those seems the beginning of the problems for me.

Probably I just goofed something, but I already tried to redownload everything a couple of times.

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12329709/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Looks like this is from recipe filter. @YannickMG can you look into this? This breaks recipe filter in MP.

**Comment by Alessandro404** [comment]
If this is  a recipe filter problem, I  do have some on my world.
