### ISSUE TITLE
crafting input buffer deleting inputs when u take the pattern out

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#14219]
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.6

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

no item lost

### The Reality

i was making tons of uev super conductor, when i take the pattern out of the buffer, all inputs lost, even after i put it back. lost like 100k of uev super conductor. QAQ. 

some screenshot evidence:
make a pattern:![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/b2191f9f-5600-4841-b29e-440ec0cbc8bf)
put it in:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/ac8b0a9e-9a9d-4ee3-818b-cf3ad80e17a8)
craft it :
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/c76d11a2-1be0-407e-8e36-33209278569c)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/2e163fc3-8cbe-4ffe-8cbb-803fcecbacbd)
remove pattern：
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/9140ef5b-8b34-4ccc-b801-ac28a11fea0f)
item gone:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/32d5e4d7-3cfa-4a0e-89fe-afd0ab692508)

put it back does not fix it.

### Your Proposal

fix, thx.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by harrynull** [comment]
When you remove the pattern, the items will be returned to your ME network (if one is connected and has free space)

当你把样板移除的时候，里面缓存的物品会被返还到所连接的 ME 网络里，除非 ME 网络满了。

**Comment by miaowwwwww** [comment]
there was indeed 100k of uev superdonductor went missing right after the pattern was taken out, i cant reproduce it right now. but it did happen. (storage was way more then enough). I will close this for now. will reopen if i got to reproduce it.
