### ISSUE TITLE
GT blocks get broken after being in spatial cell

### ISSUE THREAD

**Issue by TenyaThTM** [GTNewHorizons/GT-New-Horizons-Modpack#14229]
### Your GTNH Discord Username

tenyath

### Your Pack Version

2.3.6

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Trying to move Ore Drilling Plant II with Spatial storage cell. Expect same drilling plant on same place.

### The Reality

After moving drilling plant all GT blocks get broken. After reentry to world GT blocks returned but all items and fluids inside them gone. ![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/60298903/65107398-0f39-4fef-ac94-5aa0550ac2eb)
Also check other GT blocks in creative world:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/60298903/eba4fae4-f404-417c-9021-eb83777cabd4)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/60298903/b876e4be-ac3a-43e8-8f0b-0ff88c98c5bb)

### Your Proposal

Move GT blocks without changes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
Questbook warns about this

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/29943d06-adc4-4d70-98b2-1c7d80bd0498)

[This](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6186) issue contains information that reloading the chunk might fix the blocks, but you will need to test that yourself.

This bug is known, but I don't see any tickets made for it so I'll leave this open

**Comment by Hikari1nVoid** [comment]
They used to be fine in legacy versions(2.1.2.1).
Also it is weird that non-TEs are corrupted too.
