### ISSUE TITLE
broken recipe for world breaker / planet eater

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#14224]
### Your GTNH Discord Username

hucking

### Your Pack Version

2.3.6

### Your Server

Private

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

kind of a small issue but when trying to craft world breaker or planet eater the Advanced Drill is not the same metadata/NBT (I think metadata but not sure) as the one that you get when you craft one.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1339552/e67b1416-4d7d-44f8-ab84-dfb21050caea)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1339552/89521d7b-a923-441b-9460-56fa1842435b)
also the same with the chainsaw used for Nature's Ruin
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1339552/3fedd2c8-311b-44c0-9661-fe5b26d5d044)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1339552/7dd0326c-9015-4c35-9046-b592e95f0c5a)

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1339552/e57d616d-69c0-4514-b3b6-11c169760afd)
here is the /mt hand of both, the first one being the one in the recipe and the 2nd one being the one I crafted.

### Your Proposal

I know it's not a big issue and most people won't even get to this point and you can just cheat in the "correct" drill/chainsaw by bookmarking it from the NEI recipe but would be nice if this was fixed as I don't think it would be a hard fix lol

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
based on what you write, it should work when its fully charged

**Comment by hucking** [comment]
nope it does not craft with a fully charged drill/chainsaw.
here is for example the /mt hand of the drill used in the recipe followed by a fully charged drill 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1339552/9369a809-c5b3-494f-a9ed-8c390327fdbc)

**Comment by hucking** [comment]
ok I swear last time I tried charging it and it didn't work for some reason it worked now my bad.
