### ISSUE TITLE
NEI showing wrong Fusion Tier for certain recipes. ~~Progression block due to Rhugnor recipe~~

### ISSUE THREAD

**Issue by Ilithios06** [GTNewHorizons/GT-New-Horizons-Modpack#14228]
### Your GTNH Discord Username

ilith (legacy: Ilith#7274)

### Your Pack Version

2.3.6

### Your Server

Private server

### Java Version

Java 19

### Type of Server

Don't know

### Your Expectation

Crafting the FusionTech MkV is currently impossible in 2.3.6.

### The Reality

This is due to the Advanced Fusion Coil 2 needing Rhugnor plates, which need a FusionTech MkV since 2.3.6:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86689318/2b260bc4-374b-48e1-a041-47bf85b2816b)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86689318/d93f68a2-3fd4-4e84-9b82-9b1457cd9a0d)

### Your Proposal

Revert the Rhugnor fusion recipe back to Mk4 or remove the Rhugnor plates from the Advanced Fusion Coil 2 Recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
It seems the bug here is in NEI. Mk4 fusion should be able to reach the needed startup power.

**Comment by Ilithios06** [comment]
> It seems the bug here is in NEI. Mk4 fusion should be able to reach the needed startup power.

yea youre right, i just tested it and Mk4 is capable of running the recipe. So the issue does lay within NEI
