### ISSUE TITLE
The macerator recipe of blockClay has two duplicated recipe

### ISSUE THREAD

**Issue by hoshinokiseki** [GTNewHorizons/GT-New-Horizons-Modpack#14226]
### Your GTNH Discord Username

KisekiUnofficial

### Your Pack Version

2.3.6

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

1 blockClay should equal to 2 dustClay, not 9.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/88672077/66fe946d-d236-4fc7-bfbf-8e931bb126af)
with GT5U 5.09.43.162 and NHCore 2.1.97

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
[#mod-dev](https://discord.com/channels/181078474394566657/603348502637969419/1140619657200549908)
Looks like the recipe randomly appears on game start

**Comment by chochem** [comment]
the disables in config break when the recipe changes a bit. Not sure why this one changed, but that is what happened here.

its better to remove recipes properly.
