### ISSUE TITLE
ExxonMobil Chemical Plant doesn't have correct parallel

### ISSUE THREAD

**Issue by ChifengSouthSt** [GTNewHorizons/GT-New-Horizons-Modpack#14222]
### Your GTNH Discord Username

ND4

### Your Pack Version

2.3.6

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

ExxonMobil Chemical Plant install a Tungsten steel pipeline block should up to 8 parallel.

### The Reality

ExxonMobil Chemical Plant running on 1 parallel.only overclock

### Your Proposal

Is this a bug? or nerf? If this a"nerf",I don't think this is a good "nerf" I hope it will be repaired in future version.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ChifengSouthSt** [comment]
and Catalyst use is very fast.

**Comment by chochem** [comment]
there have been some fixes for Catalysts, maybe you can try https://github.com/GTNewHorizons/GTplusplus/releases/tag/1.9.76.

was there enough power for parallels? you didnt post much details.

**Comment by ChifengSouthSt** [comment]
![2023-08-14_16 37 15](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/119904245/47834097-ec32-4037-bb64-839149b70920)

I use this plan

**Comment by ChifengSouthSt** [comment]
the ExxonMobil Chemical on GTPlusPlus-1.9.75 can't use parallel. On GT-PlusPlus-1.9.45. it works correctly.

**Comment by ChifengSouthSt** [comment]
On GTPlusPlus-1.9.75. the Catalysts deplete speed is wrong.I use electrumflux coil.but the deplete speed is fast as cupronickel coil.
On GT-PlusPlus-1.9.45. it works correctly.

**Comment by ChifengSouthSt** [comment]
i use two zpm tier energy hatch.the ECP only make overclock. and no parallels.I will be make a test.

**Comment by chochem** [comment]
fixed the parallels. but catalysts seem to work fine for me. can you let me know how to reproduce that?

**Comment by chochem** [comment]
> I use electrumflux coil.but the deplete speed is fast as cupronickel coil.

oh I see. yea the coils are irrelevant for that. its the pipe casings.

**Comment by chochem** [comment]
as I said, it has no relationship with the coil (except for the awak. drac+ special case which does not apply here!)
