### ISSUE TITLE
Infinite and Cheap UUA can be Produced by Recycling Matter Balls and Singularities

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#14225]
### Your GTNH Discord Username

Cainiaojun

### Your Pack Version

2.3.5

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

This is a continuation of issue #14190.

### The Reality

You can use pump to input water(liquid) to the matter condenser and get infinite matter balls or singularities, and they can be used to recycle.

### Your Proposal

Put matter balls and singularities in the blacklist of recycler.
@miozune 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hikari1nVoid** [comment]
I don't see any necessities on this issue; Keeping band-aiding blacklist one by one like this is a waste of time.
Hope we don't reach an end of "someone put infinity ingot"in GT blacklist.

**Comment by boubou19** [comment]
we just want to avoid dumb easy ways of getting UUA. You can scrap tons of stuff, just not something you can have in trillions easily.
