### ISSUE TITLE
Improve Crafting Input Bus/Buffer Recipes

### ISSUE THREAD

**Issue by SomeGuyDoinWork** [GTNewHorizons/GT-New-Horizons-Modpack#14233]
### Your Pack Version

2.3.6

### Your Proposal

Currently, these recipes are ridiculously overpriced for what is essentially a replacement for an me interface, some pattern cards and an input bus. This is even more true for the Buffer - which supports fluids.

The crafting input bus should still be LuV, indalloy and assembly line - this is fine, but the recipe should be changed to an me interface, 3 pattern expansion cards, and an input bus.

The fluid version, the buffer, should be the same as the input bus, but the recipe should be: the input bus version + a dual interface + a fluid input hatch + a pump (to represent the conduits you usualyl use to extract the fluid) and a me ingriedient buffer which is usually done.

### Your Goal

All of this automation and tech is already available at this tier - gating a single block solution to LuV or even ZPM is fine, but theres no reason to gate it to UIV, and the recipes need to be the same price as the alternative, otherwise theres no reason to ever craft these blocks.

### Your Vision

This would help improve pack performance, and actually make these input hatches usable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
this was done on purpose, we are not going to retier the recipe of these blocks: this is QoL blocks to ease the automation of setups, but we decided players should at least prove they mastered the automation (hence why the LuV for the item version) and for the fluid version you don't really need one until endgame when you really start to spam multis.

**Comment by boubou19** [comment]
yes, and many stargate players agreed. Now move on, we decided it would be like that.
