### ISSUE TITLE
NPE when no circuits in LPF

### ISSUE THREAD

**Issue by harrynull** [GTNewHorizons/GT-New-Horizons-Modpack#14237]
### Your GTNH Discord Username

harrynull#9630

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

LPF with crafting input bus without circuits. Does not throw NPE

### The Reality

GPL shows recipe check failed due to crash

### Your Proposal

https://github.com/GTNewHorizons/GTplusplus/blob/66b4a01cceb445b4a5beef8d29e1b974f9a55d1e/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/processing/GregtechMetaTileEntity_IndustrialMultiMachine.java#L218

This might be null.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ALongStringOfNumbers** [comment]
I recently ran into the same issue, on version 2.4.0, when using Ghost Circuits, the Crafting Input Bus, and the Large Processing Factory. I had to place an actual circuit item into the manual inventory of the Crafting Input Bus.

This was the log snippet in the failed case https://pastebin.com/8FUViayw
