### ISSUE TITLE
Tier 3 Naquadah Fuel Refinery doesn't consume any power

### ISSUE THREAD

**Issue by S4mpsa** [GTNewHorizons/GT-New-Horizons-Modpack#14234]
### Your GTNH Discord Username

sampsa_

### Your Pack Version

2.3.5 with manual updates

### Your Server

Private

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Naquadah Fuel Refineries should consume the power stated on the recipe, including overclocks.

### The Reality

Upgrading to Ultimate Field Restriction Coils allows you to run the refineries without any energy input (They still require appropriate energy hatches). Tier 1 and 2 coils work as expected.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/69092953/ba93a35b-f96f-49c9-9ff9-d0e172057102)

### Your Proposal

Make them consume energy

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by fluffle** [comment]
This doesn't appear to be entirely fixed. I have just built my first refinery with T2 coils to make MkIV via the Praseodymium recipe. I threw a 16A UEV hatch onto it, which at least theoretically gives enough power for one overclock (128M EU/t in, recipe asks for 46M). It's currently making MkIV quite happily while consuming no power...

**Comment by fluffle** [comment]
Actually both my naq fuel refineries are consuming no power (with no overclocks). When I tried to run a patched GoodGenerator in a recent nightly to debug the issue everything worked fine, so perhaps this is just a 2.4.0 thing - even though @BlueWeabo's patch is in 2.4.0 AFAICT.
