### ISSUE TITLE
Add Pure Trichlorosilane LCR recipe

### ISSUE THREAD

**Issue by Teykn** [GTNewHorizons/GT-New-Horizons-Modpack#14231]
### Your GTNH Discord Username

Teykn#4647

### Your Pack Version

2.3.2

### Your Proposal

Add an LCR recipe that produces purely Trichlorosilane

### Your Goal

Currently, there is no LCR recipe that produces only Trichlorosilane, whereas there is a singleblock CR recipe that does. This is odd, as LCR recipes include both standard CR recipes, and better advanced recipes that reduce the steps required and/or improve efficiency.

Currently, the only LCR recipe that produces Trichlorosilane, also produces 3 other fluids, 2 of which cannot be turned into solar grade silicon, and must instead be electrolyzed (returning raw silicon, rather than solar grade). This marks an oddity where the LCR recipe is less efficient than the CR recipe

### Your Vision

This change would better align with the general philosophy behind how LCR recipes are designed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10356

**Comment by Teykn** [comment]
> see #10356

kk
