### ISSUE TITLE
Fluid Pattern Terminal -> "2x" does not multiply fluids in output slot

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#14242]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.3.6

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7759876/a59c0462-c0ac-4180-b6e8-3d0b1c29b3df)

### The Reality

![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7759876/7dfd3d96-6b9c-4e86-8ed4-bb0bc13fd9e2)

### Your Proposal

Fluids shall also be multipied by 2

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by S4mpsa** [comment]
Already fixed https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/153
