### ISSUE TITLE
Bee Changes RFC

### ISSUE THREAD

**Issue by hacatu** [GTNewHorizons/GT-New-Horizons-Modpack#14245]
### Your GTNH Discord Username

hacatu

### Your Pack Version

2.3.4

### Your Proposal

I have some ideas for changes to bees that I'd like to implement:

### Basic Balance Changes:
- alveary needs 3 stimulators instead of 2 to hit the soft cap now, so buffing them a bit would be nice but it's not necessary
- magic, resilient, and basic blood frames should be buffed.  After the additive production modifier change, frames that were 2x are now +1.  This makes them much weaker, which is fine in most cases but these frames are particularly expensive so I think they should be +2 in the case of magic/resilient/base blood
- The Lapotron bee should not be dim locked, the indium bee should not be Mutatron blacklisted, and the Drake Bee should be mutatron blacklisted.  For the indium bee in particular, it's currently not obtainable for no-space players, and this seems particularly egregious because while the mutatron is early LuV and the t5 (?) rocket is late LuV, it's really not that much of a progression skip to allow the mutatron to make indium bees when you include the bacterial sludge -> mutagen line.  If that's an unpopular opinion, it could also remain mutatron blacklisted but have its dim lock removed and instead require a base block of europium or something late LuV+

### New Bee Features:
- I'd like to add a new effect for the barnardac bee that transmutes saplings into barnardac saplings under certain circumstances.  My ideas include only working in the spectre dimension or only working on tree of transformation saplings, but maybe no such restrictions are necessary

### Your Goal

I'd like feedback on these proposed changes, mainly on how/if I should implement the mutation related changes and barnardac bee change

### Your Vision

I will implement these changes after @Runakai1, @kuba6000, @chochem, and if needed Dreammaster et al lmk anything I should change/skip

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miaowwwwww** [comment]
“the indium bee should not be Lapotron blacklisted”， u mean mutatron blacklisted?

**Comment by miaowwwwww** [comment]
indium bees need venus, which is t4, so yes, not much of a skip. it's early LuV

**Comment by Runakai1** [comment]
1) i don't like making breeding even easier
2) sure, buffing magic frames a bit would be nice
3) lapotron bee, okay. Drake bee, okay.  I don't like removing indium bee from mutatron. 
4) nice idea

**Comment by hacatu** [comment]
Cool.  To be clear about #1, I mean the production boosting electron tubes not mutation boosting ones.  But the more I think about it, it doesn't really matter, they're fine as is

Alright, would you be ok with removing the indium bee dim lock and making the base block more expensive (europium or something)?  I think I could also add a separate second, more expensive mutation for no space players, similar to how common bees can be bred in many ways, but I would have to test if that is possible for arbitrary bees

**Comment by hacatu** [comment]
Oh cool I don't have to link the the PRs

None of these are dependent on each other

I ended up not changing electrical stimulators, removing the Lapotron bee dim lock, or removing the Indium bee from the mutatron blacklist.

I blacklisted the drake bee, buffed the magic/resilient/base blood frames, and added the Tree Twister effect for the BarnardaC bee.

I also added a tentative much harder alternate mutation for the Indium bee for no space / skyblock players, take a look and feel free to strike it down.  I'm less attached to this after realizing the Naquadria bee can make Indium and isn't mutatron blacklisted (albeit it's very hard to process and you'd only use it for indium as a meme)

**Comment by Runakai1** [comment]
> Oh cool I don't have to link the the PRs
> 
> None of these are dependent on each other
> 
> I ended up not changing electrical stimulators, removing the Lapotron bee dim lock, or removing the Indium bee from the mutatron blacklist.
> 
> I blacklisted the drake bee, buffed the magic/resilient/base blood frames, and added the Tree Twister effect for the BarnardaC bee.
> 
> I also added a tentative much harder alternate mutation for the Indium bee for no space / skyblock players, take a look and feel free to strike it down. I'm less attached to this after realizing the Naquadria bee can make Indium and isn't mutatron blacklisted (albeit it's very hard to process and you'd only use it for indium as a meme)

Yes, please remove the indium bee changes you've done. 
Your stuff will be merged as soon as feature freeze is gone

**Comment by Alastors** [comment]
@hacatu I updated your original comment with the updated +2 for the base blood versus +3
