### ISSUE TITLE
Turbine Blades with "Steam Flow Multiplier" dont work with SC Steam

### ISSUE THREAD

**Issue by Persus1** [GTNewHorizons/GT-New-Horizons-Modpack#14257]
### Your GTNH Discord Username

persus

### Your Pack Version

2.3.6

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Specific materials (Duranium, Ichorium or Vulcanite for example) have a hidden Flow Multiplier for Steam which boosts their Steam flow so they can produce more EU/t in one Steam Turbine. The Tooltip doesnt show the actual multiplier and just shows the calculated Optimal Steam Flow
For example:
Huge Ichorium Turbines have a Steam Flow of 6400mb/t and a hidden Steam Flow Multiplier of 30 which results in a Optimal Steam flow of 6400mb/t*30=192000mb/t (as shown in the tooltip) which works fine for working with Steam and Superheated Steam

### The Reality

When trying to work with Supercritical Steam on the other hand the hidden Flow Multiplier doesnt apply.
This results in a false tooltip for The Optimal Steam Flow for Supercritical Steam

=> The Optimal Supercritical Steam Flow is actually 6400mb/t for Ichorium which you cant possibly know without using external tools

=> Scanning the Turbine while its running is also not working since it also calculates it with the not working Steam Flow Multiplier
example Duranium:
Shows as: 102400mb/t*16 = 1638400mb/t (Also shows as L/s in the scan instead of L/t)

Reality:  6400mb/t*16 = 102400mb/t

### Your Proposal

Activate the Steam Flow Multiplier for SC Steam (Would be a welcome change since there are no good alternatives besides Trinium and Infinity Catalyst Turbines imo with High Turbine Efficiency and a good Steam Flow without the need to spam a lot of XL's before getting Infinity)

Also fix whats shown on the image
![Screenshot 2023-08-18 182745](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/130587498/6fe9b3f3-8845-49b6-8051-acbb64f2ed5b)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hikari1nVoid** [comment]
I can confirm this on Ichorium turbine;They runs 30 times slower in XL SC steam turbine;
