### ISSUE TITLE
Some circuit computation missing

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#14262]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

v2.3.0.0(Also confirmed in the latest main branch)

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

Install Superconductor Magneto Resonatic Circuit in Computer Rack instead of BiowareAssembly

### The Reality

Computation is 0.
I also checked the code and noticed that there is no Computation in the circuit beyond Optical(https://github.com/Technus/TecTech/blob/da2529429f0745600a9e4afa2b7f358397271ae2/src/main/java/com/github/technus/tectech/thing/metaTileEntity/hatch/GT_MetaTileEntity_Hatch_Rack.java#L321-L325).

### Your Proposal

Please add a value
Magneto Resonatic Circuit is said to have no use etc., so I think it can be a little higher computation and less heat-generating than the same tier of circuits.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hikari1nVoid** [comment]
MRCs are not listed in the QC wiki list of all circuits with computational pwr iirc...

**Comment by Dream-Master** [comment]
we can add stuff there very easy. But i need values and suggestions here

**Comment by Hikari1nVoid** [comment]
And they are probably unnecessary...when there's creative APU&GPU T3 available for QC and all other GT circuits are no more needed in QC. I'll suggest a removal for all GT circuit computation/heat data.

**Comment by yukieiji** [comment]
I don't think it's good for QoL or EndGame to make QC huge for computation.
Also OC's APU/CPU/GPU generates a lot of heat and isn't recommended for running QC always...

So I think that GTCircuit's computation/heat should be reconsidered, GTCircuit's computation and RS's recipe computation should be normalized.

**Comment by boubou19** [comment]
> I don't think it's good for QoL or EndGame to make QC huge for computation.
Also OC's APU/CPU/GPU generates a lot of heat and isn't recommended for running QC always...

It the whole purpose of it: if you want to get powerful QCs, just tweak your QC so it doesn't explode. It has a complex mecanic of over/underclock and over/undervolt. Let's use make usage of it.

> So I think that GTCircuit's computation/heat should be reconsidered, GTCircuit's computation and RS's recipe computation should be normalized.

If anything non used GT circuits will have computation / heat values close from the creative APU from opencomputers. Again, we will not make a circuit give computation with 0 heat. That would kill QC's unique mechanic. You are right on the recipe computation required, it's purely random, but with the fact you can find OC/OV values to take advantage of the most powerful circuits and the fact you can add multiple QCs on a RS, it's low prio.

**Comment by yukieiji** [comment]
> If anything non used GT circuits will have computation / heat values close from the creative APU from opencomputers. Again, we will not make a circuit give computation with 0 heat. That would kill QC's unique mechanic. You are right on the recipe computation required, it's purely random, but with the fact you can find OC/OV values to take advantage of the most powerful circuits and the fact you can add multiple QCs on a RS, it's low prio.

It's not that I want the heat value to be 0, but from the current situation where Creative's APU is sufficient, I think we should reconsider the heat/computation of the circuit and reconsider computation such as RS'recipe.

**Comment by chochem** [comment]
@minecraft7771 has already been working on a wider rebalance a while ago. I think there is still an open branch. maybe ask him what the state is.

**Comment by Hikari1nVoid** [comment]
> has already been working on a wider rebalance a while ago. I think there is still an open branch. maybe ask him what the state is.

Just checked the computation balancing branch and I got an astonishing 50-90% nerf on oc parts. I think we should open a RFC issue before applying such a great balancing.
