### ISSUE TITLE
Buildcraft Quarry lag

### ISSUE THREAD

**Issue by SrYthan** [GTNewHorizons/GT-New-Horizons-Modpack#14263]
### Your GTNH Discord Username

ythan

### Your Pack Version

latest buildcraft version

### Your Server

SP

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

![quarry lag](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/78868186/8e385da1-05ee-4349-bb36-afb78c71556a)
when a query is cleaning an area before starting mining, it causes a lot of lag until the process of cleaning the place is finished.

### The Reality

.

### Your Proposal

I don't know what can be done to alleviate the problem, I believe that checking the blocks when placing the quarry to calculate how much energy will be needed to clean the place, thus preventing it from calculating the blocks that should be be clean.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
the buildcraft quarry isn't even supposed to be craftable for this exact reason. So not a bug, don't use the BC quarry, use the extra utility one, or better, use the GT miners.
