### ISSUE TITLE
Add end credits for GTNH

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#14266]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.3.5

### Your Proposal

Add end credits like a in regular minecraft, but for GTNH end. It should trigger when you go in stargate first time. Should contains GTNH stuff, like logo, soundtrack, some text, developers list, mb their quotes etc.

### Your Goal

Let people feels that is end.

### Your Vision

I think its cool.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Cool idea but the utility of implementing smth like this for 23.6 people is questionable. Messaging to remove the stale label.

**Comment by Dream-Master** [comment]
> Cool idea but the utility of implementing smth like this for 23.6 people is questionable. Messaging to remove the stale label.

i think they are more than 23,6 people . We more than 100 for sure. Yea it depends on the complexity if this will ever get added :)
