### ISSUE TITLE
thaumium drill from electromagic requiring an unavailable item

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/GT-New-Horizons-Modpack#14267]
### Your GTNH Discord Username

PoppyXabe

### Your Pack Version

2.3.6

### Your Server

private

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Using infusion to craft thaumium drill without facing any recipe problems

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40670872/4dc239d4-4bba-4a0d-89e9-8ff217ce03dc)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40670872/867b9504-cdcb-47b3-bd11-faa4b0350d93)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40670872/9b7ca10b-731a-4871-ba81-b9cfe1626fb7)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40670872/ef1201d8-e4d4-4188-8472-029ffa2a2d6d)

it appears to be uncraftable due to the drill type required and the only craftable Mv type being different items, the required type, probably has a titanium(?) handle is not available to craft, and the current drill version that is available to craft has an aluminium handle, i've tried all 3 battery types both charged and uncharged of the aluminum craftable drill and it didnt work, i cheated in the required drill and the infusion commenced 

### Your Proposal

The recipe using a drill that is possible to craft.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PoptartOverlord-Xabedo** [comment]
it should be noted that the same drill is also used in crafting the diamond omnitool

**Comment by chochem** [comment]
looks like somebody changed the secondary materials for the drills
