### ISSUE TITLE
Skookum choocher changes

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#14272]
### Your GTNH Discord Username

Santa's Child#0408

### Your Pack Version

2.3.4 custom

### Your Proposal

Modify or remove the skookum choocher.
My ideas for modifying would be either 
make it work for shift clicking like its base tools by making it shift rclick air/invalid block to switch.

make it behave as both tools in toolbox/maintenance hatch at the same time (it seems to only work as a wrench full stop within maintenance hatches as a side note).

or, increase it's durability by a notable degree

### Your Goal

skookum choochers are currently only 7/8ths an ingot cheaper than making a wrench and hammer while only gaining ~20% durability versus ONE of those and they can't even replace a wrench properly, this is disregarding electric wrenches being a thing disrupting this comparison even further.

due to this they don't serve to act as space saving for a toolbox, role compression for player usage, they also disrupt NEI usage for newer players, and are worse on material efficiency for anything else

because of all these issue currently they only serve as a potential trap due to player curiosity that is entirely useless outside of being a slightly more durable notably more expensive hammer that if you're lucky may actually be useful as a wrench at some point

### Your Vision

It aids in simplifying tools and user accessibility by way of removal or replacement of a tool that is currently irrelevant/harmful by merely existing within the pack

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
It's removed now https://github.com/GTNewHorizons/GTplusplus/pull/729

**Comment by Rika-TH** [comment]
Lets fucking goooooo
