### ISSUE TITLE
Server-Donation-Lootbags

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#14278]
We need to add Server Donation Lootbags.
This bags need to be better than normal Lootbags and not contain the Trash loot.
This bags can only obtain on Servers when a Donation goal is reached.
You will own some Donation coin you can exchange in the Questbook into a Lootbag of the tier you in.

I will add a Sheet where you can make suggestions for items you want to see in a bag.

<https://docs.google.com/spreadsheets/d/1ruauJxBeTq-U5_IuFexT_v7KSA1Vqbl-hX_ROp9BVbc/edit#gid=0>

**Comment by boubou19** [comment]
The issue is that Mojang has a new EULA so rules have changed for donations. We need to check if we still have the right to do this kind of stuff.

**Comment by Dream-Master** [comment]
Everyone get the lootbag when the Goal is reached no matter if he/she donate or not.
