### ISSUE TITLE
Skookum choocher does not act as hammer in maintenance hatch

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#14273]
### Your GTNH Discord Username

Santa's Child#0408

### Your Pack Version

2.3.4 custom

### Your Server

Private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Skookum choocher should behave as current set tool within a toolbox or manual use on maintenance hatch

### The Reality

as per #14272 skookum choocher does not behave as a hammer, rather it behaves as a wrench regardless of mode

### Your Proposal

For it to be fixed or removed as per my opinion on stated ticket

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
It's removed now https://github.com/GTNewHorizons/GTplusplus/pull/729
