### ISSUE TITLE
Backport EnderIO Limited Item Filter.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#14277]
### Your GTNH Discord Username

abdiel_kavash

### Your Pack Version

2.3.6

### Your Proposal

Backport the [Limited Item Filter](https://github.com/SleepyTrousers/EnderIO-1.5-1.12/wiki/Item-Filters#limited-item-filter) for EIO conduits from modern versions of EIO. The limited item filter works like the advanced item filter (allowing NBT/metadata/etc. conditions for filtering), but when used on the destination conduit it limits insertion to only a specified number of items. When used on the extraction side, it always keeps the specified number of items in the source inventory.

This would be useful for early to mid game automation, as there is currently no other simple and reliable way to do this in the pack that works with a generic destination inventory.

### Your Goal

See above.

### Your Vision

See above.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
we add a bunch things from 1.12 maybe someone are able to add those stuff back to 1.7.10

**Comment by miozune** [comment]
Added by https://github.com/GTNewHorizons/EnderIO/pull/143
