### ISSUE TITLE
Double edible consumption

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#14286]
### Your GTNH Discord Username

Santa's Child#0408

### Your Pack Version

2.3.4 custom

### Your Server

Private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

when consuming edibles (in this case drinking a flask) only one item/charge is consumed

### The Reality

on occasion if you don't switch from the item to a different slot a second item/charge is consumed

### Your Proposal

for only a single item/charge to be consumed more consistently

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
This is a minecraft vanilla bug. It has been around and unfixed for a long time in older versions at least.

**Comment by Rika-TH** [comment]
> This is a minecraft vanilla bug. It has been around and unfixed for a long time in older versions at least.

Even so, it still should be considered as something to be fixed

**Comment by Rika-TH** [comment]
> This is a minecraft vanilla bug. It has been around and unfixed for a long time in older versions at least.

Even so, it still should be considered as something to be fixed
