### ISSUE TITLE
alternative / new enzyme recipe

### ISSUE THREAD

**Issue by TenyaThTM** [GTNewHorizons/GT-New-Horizons-Modpack#14298]
### Your GTNH Discord Username

tenyath

### Your Pack Version

2.3.7

### Your Proposal

add alternative / new enzyme recipe in greg machines
i suggest add something like this
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/60298903/3f35414a-7517-4af7-bd48-38ba8e324ba0)

``Mixer.addRecipe(<Genetics:misc:3> * 3, null, [<minecraft:sugar>], <liquid:binnie.bacteria> * 10, 100, 120);``

### Your Goal

all main items in Genetics have gregified recipes beside enzyme
I also remind that the current recipe is broken (the incubator itself)

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Kriion** [comment]
I should also add that recently there was a problem on the Zeta server for about 2-3 days during which the incubator was not working properly. The recipe was not reproducing as the tank was full judging by the error. But the tank was empty, and there was no liquid coming out in the recipe.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142689341/a19614ca-b483-48ca-93b9-e3472ca3b42d)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142689341/8db50190-5b8a-430b-9060-d878db7664b1)

**Comment by TenyaThTM** [comment]
> I should also add that recently there was a problem on the Zeta server for about 2-3 days during which the incubator was not working properly. The recipe was not reproducing as the tank was full judging by the error. But the tank was empty, and there was no liquid coming out in the recipe. ![image](https://user-images.githubusercontent.com/142689341/262448230-a19614ca-b483-48ca-93b9-e3472ca3b42d.png) ![image](https://user-images.githubusercontent.com/142689341/262448270-8db50190-5b8a-430b-9060-d878db7664b1.png)

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13885
