### ISSUE TITLE
A Lot of Items Lose Their Recipe

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#14302]
### Your GTNH Discord Username

Cainiaojun

### Your Pack Version

2.3.7

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### The Reality

![Y1GQBZ(F196JF2XZ)R7AKZY](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/72213408/4c10c3ab-90ae-40c3-a667-b44538a6eba5)
Many items lose their recipe. From AE2, Blood Magic, Gravisuit, RemoteIO, etc. Those items in the picture are examples.

### Your Proposal

Fix itv plz

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by cainiaojun** [comment]
> I would say you probably have an old script folder hanging around.

My fault sorry

but I found only when I have the old script folder can I get those recipe, but my teammate have to delete them to get those recipe. What's the problem?

**Comment by chochem** [comment]
its not a thing anymore. get rid of them everywhere. server and all clients

**Comment by cainiaojun** [comment]
> its not a thing anymore. get rid of them everywhere. server and all clients

strange bruh

I would have a try thanks
