### ISSUE TITLE
Buff ME Essentia Providers and/or Import/Export Busses (ThE)

### ISSUE THREAD

**Issue by AltyMan** [GTNewHorizons/GT-New-Horizons-Modpack#14307]
### Your GTNH Discord Username

alty2x

### Your Pack Version

2.3.4 with newest ThE (so post original buff)

### Your Proposal

My original proposal a while back was to allow for the 4 card slots in Essentia Import/Export busses to allow 4 accel cards (previously capped at 2 oddly enough). This change was enough to balance out some stuff, but I find myself coming across similar problems with the speed of importing/exporting essentia into/out of my ME system to this day. My proposal is a buff to the import/export limits of the essentia provider, to allow for use of that with essentia production and keep up with heavier demands. That along with another slight buff to the calculation of accel cards and their boosts with essentia import/export busses would do justice. I also know that firenoo is working on essentia interfaces, but I still believe there should be other things doing this, especially since things like the essentia input hatch do not support any other essentia input other than the essentia provider for some reason (maybe that’s another ‘bug’ we should concern ourselves with).

### Your Goal

To have a working solution to using ME for larger scaled essentia production versus having to use external means to get it. In this case, users use golems to transport mass amounts of essentia, even though I personally believe there should be a proper method/solution rather than having to use golems.

### Your Vision

Not having to worry about the currently feasible transportation methods of essentia stopping me from producing large quantities of it and causing an inevitable and immovable bottleneck within the system due to a lack of proper solutions.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
*Please buff this for the LEG should be the name of this 😂

**Comment by Alastors** [comment]
Yeah maybe, up to @firenoo though, but it's clear this is just for the LEG, nothing else has an issue with obtaining essentia because of throughput limitations

**Comment by AltyMan** [comment]
> *Please buff this for the LEG should be the name of this 😂

Look, nerf the LEG I don’t mind, it’s just annoying seeing my adv alc furnace multi being full on flux and my essentia providers sending out 1 essentia per tick 😭

**Comment by Alastors** [comment]
> > *Please buff this for the LEG should be the name of this 😂
> 
> Look, nerf the LEG I don’t mind, it’s just annoying seeing my adv alc furnace multi being full on flux and my essentia providers sending out 1 essentia per tick 😭

“The entire Chinese GTNH community disliked that”

**Comment by chochem** [comment]
so this is mainly aimed at LEG, meaning power production?
You should start with some numbers then. What is your current setup? How much power does it make? How much power would it make with the buff? Or how much would it simplify the setup?

**Comment by Alastors** [comment]
> so this is mainly aimed at LEG, meaning power production?
> 
> You should start with some numbers then. What is your current setup? How much power does it make? How much power would it make with the buff? Or how much would it simplify the setup?

The setup on just the provider itself + leg makes 57 amp ZPM apparently

**Comment by AltyMan** [comment]
> > so this is mainly aimed at LEG, meaning power production?
> > 
> > You should start with some numbers then. What is your current setup? How much power does it make? How much power would it make with the buff? Or how much would it simplify the setup?
> 
> The setup on just the provider itself + leg makes 57 amp ZPM apparently 

My setup is running 59A LuV power, and I'm producing way more essentia than that. The problem is the inability to import/export essentia fast enough to supply it. The fix would just boost the setup to 64A LuV really cuz the LEG is limited to the single dynamo hatch u can supply it. A difference of 5A is not significant enough I feel like to un-justify having faster and more consistent/stable essentia transfer using ME

**Comment by AltyMan** [comment]
At best I see this as an indirect buff, but even then I just think there should be proper options to using ME essentia. Firenoo is developing an essentia interface, but I honestly think that the essentia provider itself should also have a buff, and the import/export busses should either allow hyper-accel cards or let accel cards add a bigger bonus to speeds

**Comment by boubou19** [comment]
Except for LEG, this is not needed. Since the LEG is a nightmare to balance in its current state but is fine-ish, we will not change anything. If we balance the LEG in the future, this will not be needed at all. Really i have the feeling that this ticket is all about "pls buff this but nerf LEG, i'll just hope that the buff of the essentia buses will overcome the LEG nerf with more LEG spam". I'm closing this.

**Comment by AltyMan** [comment]
Less about the LEG balance, more about how stuff shouldn’t be dependent of transfer speeds without any better solution. Nerf the LEG, regardless I think the current setup shouldn’t be as it is

**Comment by boubou19** [comment]
i said no
