### ISSUE TITLE
gtnh2.3.6+ lost compatibility with AM2

### ISSUE THREAD

**Issue by mcmso** [GTNewHorizons/GT-New-Horizons-Modpack#14308]
### Your GTNH Discord Username

mc_mso

### Your Pack Version

2.3.6+

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

Added am2-009 to mods

### Crash Report
After opening the manual for Thaumcraft 4, select ForbiddenMagic and click, this issue occurs
https://paste.ubuntu.com/p/ZG7TFxQZqj/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
sounds like you have a broken research definition - either it's a research without a category, or a research with a nonexistent parent. this checklist is all we will be offering 
1. try a clean install
2. try downgrade TC4Tweaks to the one in the last version that worked - if this solves your problem, please post a separate issue [here](https://github.com/Glease/TC4Tweaks/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=)

**Comment by mcmso** [comment]
> sounds like you have a broken research definition. From the log it appears either there is a research without a category, or a research with a nonexistent parent.
> 
> this checklist is all we will be offering
> 
> 1. try a clean install
> 2. try downgrade TC4Tweaks to the one in the last version that worked - if this solves your problem, please post a separate issue [here](https://github.com/Glease/TC4Tweaks/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=)

Yes, this is the newly installed 2.3.7(clean install)
I have tested it in both 2.3.6 and 2.3.7 respectively and can repeat this problem
Before I published this issue, I tried to change the 'TC4Tweaks' and 'ForbiddenMagic' versions to the ones that worked before, but nothing worked

**Comment by boubou19** [comment]
then as @Glease said, we won't provide further troubleshooting, as AM2 compat is not on our tofo list.
