### ISSUE TITLE
Items on fire? There was error during rendering item. Please check log for details. java.lang.IllegalStateException: Modelview matrix stack too deep

### ISSUE THREAD

**Issue by mjevans** [GTNewHorizons/GT-New-Horizons-Modpack#14311]
### Your Pack Version

2.3.7

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Reload the game, connect to the server, allow NEI to rebuild the block / item data.

Open a chest, your own inventory, an ME terminal of any sort... NOT 100% repeatable, but 'frequently' (10-100 times over several hours) happens.  Often with a stutter from the game as it tries to render the item previews.

It should just render correctly...

### The Reality

Others haven't mentioned this issue, which makes me wonder if it's another case of more lax driver stacks on more popular operating systems not having the same issues.

Offhand, I don't remember seeing this sort of error in GTNH 2.3.6 but I think I did very rarely in 2.3.4.

The in game and in launcher console spam is rather excessive, and repetitive.  I grabbed the first few examples, since the GIST refused to preview.

https://gist.github.com/mjevans/58710030c9ea22304b1dd506f6188444

### Your Proposal

I'm posting this in the hopes that someone else has also had the issue and that there might be other steps that can be taken to help isolate the cause.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Please post full fml log.

**Comment by mjevans** [comment]
Github like to truncate large files, such at the fml log file.

Please ensure you view / download the full file https://gist.github.com/mjevans/216ded519eebb55a96b953579ce6aff2/raw/40587b544491adef2e335fbeb39b93d230dc2349/fml-client.log
Rather than the GIST https://gist.github.com/mjevans/216ded519eebb55a96b953579ce6aff2 truncated file.

**Comment by mjevans** [comment]
I've been trying other things that might have even _remotely_ been related like a mod that added additional things to render, removed.

Even without that mod, the error still happens. fml-client-withoutCustomPlayerModels.log - 69781 lines total.

https://gist.github.com/mjevans/5fcd05bda3e9339a8f3611d1abebd10b

**Comment by mjevans** [comment]
After updating to GTNH 2.4.0 + the OpenComputer's no glNormal's patch, I've not seen this issue in a couple of days.  Hopefully it's no longer reproducible. ;)

**Comment by Wumianzhe** [comment]
I'm having same issue on 2.4.0. What is glNormal's patch you mentioned?
