### ISSUE TITLE
UXV Component Assembly Line Casing

### ISSUE THREAD

**Issue by ramseyspace** [GTNewHorizons/GT-New-Horizons-Modpack#14316]
### Your GTNH Discord Username

Ramsey#7916

### Your Pack Version

2.3.7 B

### Your Proposal

Add a recipe to make the casings. Discount same as like other tiers

### Your Goal

To reduce spam assembly line for them.

### Your Vision

It is clocking up my main assembly line area, All other tier below are handled by CoAL. I am getting to the point where I need to make AAL for them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TheEpicGamer274** [comment]
this will not be happening from what I've heard.
