### ISSUE TITLE
Remove shadow Iron recipe from EBF

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#14312]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.3.7

### Your Proposal

Remove shadow Iron recipe from EBF.
You can smelt shadow iron in regular furnace. 

### Your Goal

And when you try smelt Shadow Steel in universal EBF, shadow iron recipe not let you get shadow steel.

### Your Vision

this recipe make problem from nothing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
You kinda have it the wrong way around there. It has a custom EBF recipe, so it should not be in the furnace.

It also sounds like your EBF is not particularly universal. There is no recipe conflict here or anything like that.

**Comment by lordIcocain** [comment]
Just check fixes, shadow steel a lot faster, it should be fixed too i think.
About universal EBF, i mean i had oxygen, xenon in EBF and put shadow iron dust with 11 circuit, i want shadow steel, but get shadow metal
<img width="531" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/c6be4d0e-b5b5-4595-8c01-ffb26d583f9e">
<img width="554" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/f8e3027e-446a-4add-831a-90835e0c7511">

**Comment by lordIcocain** [comment]
Mb move shadow iron to circuit 1, without gases

**Comment by Alaking** [comment]
this is still annoying, maybe make shadow steel dust mixerable instead if the shadow iron gas recipes are supposed to stay?
