### ISSUE TITLE
buff tartarite smelting speed OR nerf tartarite requirements for fusion chain 

### ISSUE THREAD

**Issue by Alaking** [GTNewHorizons/GT-New-Horizons-Modpack#14320]
### Your GTNH Discord Username

alaking

### Your Pack Version

2.3.5 with updated betterP2P

### Your Proposal

decrease the amount of power needed for the tartarite used for celestial tungsten plasma

### Your Goal

my current powergen plan is to make celestial tungsten plasma in a dedicated mk3 compact and have that run constantly, aiming to produce ~6.5 billion eu/t via 9 infinity XLs at 300% flowrate.
this would requires 640l of tartarite per second to keep up with the compact.
using a mebf would result in this taking close to 500 million eu/t, while using 24x UEV volcanus it would require around 170 million eu/t.
those numbers are doable, but overall very high compared to the rest of the chain, especially because theyre concentrated in a single craft.
imo the titansteel for runite plasma isnt a problem comparatively, despite taking 80 million eu/t for a full mk2 compact, because it doesnt force one to choose between a massive powercost from a mega multi or just spamming machines to abuse efficiency

### Your Vision

make the fusion chain more accessible and easier to build
reduce amount of gt++ spam since the volcanus is way more efficient for stuff like this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
done in https://github.com/GTNewHorizons/GTplusplus/pull/745
