### ISSUE TITLE
Incorrect recipe for aura core essence

### ISSUE THREAD

**Issue by Kriion** [GTNewHorizons/GT-New-Horizons-Modpack#14338]
### Your GTNH Discord Username

Kriione[Kirill]#4672

### Your Pack Version

2.3.8 

### Your Server

Zeta

### Java Version

Java 19

### Type of Server

Open To LAN

### Your Expectation

See all 4 essences needed for the recipe.

### The Reality

Does not display the essence in the recipe nei
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142689341/32055d3d-cbc1-42bd-accc-333e1ce1f9ee)

### Your Proposal

Fix it 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
doesnt have any in the thaumonomicon either. so not sure what 4 you are talking about.

**Comment by Dream-Master** [comment]
this recipe looks very vanilla
