### ISSUE TITLE
EuO requires ZPM, but the gated step, EuO3 + Eu, requires LuV

### ISSUE THREAD

**Issue by SomeGuyDoinWork** [GTNewHorizons/GT-New-Horizons-Modpack#14330]
### Your Pack Version

2.3.7

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

When processing Europium Trioxide and Europium Dust into Europium Oxide, this step is at LuV, Then electrolyze Europium Oxide to EU + oxygen.

### The Reality

Upon trying to electrolyze the resulting Europium Oxide, you require a ZPM machine, despite there being no other way to make the dust other than the LuV step.

### Your Proposal

Change recipe for EuO -> EU + O to LuV, making it inline with the previous step thats already properly gated.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you can use 2 hatches
