### ISSUE TITLE
Precision Assembler Ignores Energy Hatch Level Restrictions

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#14333]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.3.7

### Your Server

SP

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

The Precision Assembler should not have been able to execute more advanced formulas than the Energy Hatch it installs

### The Reality

![U{31ZE~{~KRR`%YLEE1WIP](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/88690f2e-e16b-46a9-bce4-e3c45f3b1f3f)
![7P77D}C(CI 6%N1FGUSO$R4](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/9e7fb36c-fcbd-43a6-a8aa-0a53b35c4f12)
![AWS(JA %%(}TZJ9S`5Y(CH3](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/be3f877a-54d5-4ed4-8307-c848f4cd0990)
It runs normally and ignores that it only installs UEV 256A instead of UIV energy hatch

### Your Proposal

Add restrictions again

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by JodieRuth** [comment]
![U{31ZE~{~KRR`%YLEE1WIP](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/1914a5c8-f95e-49eb-acdc-53bebb2da235)
![7P77D}C(CI 6%N1FGUSO$R4](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/77714576-9626-426d-bc9a-4783d77d9c88)

**Comment by chochem** [comment]
there might a limit beyond which the restriction is lifted.

**Comment by JodieRuth** [comment]
No. Some machines have the right to use UHV+mechanical blocks to unlock all Hatch levels, and the Precision Assembler is also the same. However, the corresponding energy hatch still needs to be installed to prevent it from working, as it has always been the case before

**Comment by chochem** [comment]
ah it doesn't even matter, I just tried gtnh-nightly-2023-08-25+105 and its broken for low tiers too.

Just made a UV recipe with 64IV hatch and IV casings. Looks like it doesn't check anything anymore.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/50a6a28c-8b42-4d64-867f-f1982de189d5)

**Comment by JodieRuth** [comment]
Yes, please fix it as soon as possible. It seems that this modification to the OC algorithm has caused many errors, and perhaps some have not been discovered.
