### ISSUE TITLE
Electromagnet is not craftable

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#14347]
### Your GTNH Discord Username

Santa's Child#0408

### Your Pack Version

2.3.4 custom

### Your Proposal

make the enderio electromagnet craftable, 

### Your Goal

the Ender IO electromagnet is required to make the awakened item dislocator, and could be considered the inbetween of that and the base item dislocator, however it currently is only attainable by lootbags
assuming tech prog this would also seem to be the second item magnet you get access to before the awakened one

### Your Vision

electromagnet, and in turn awakened item dislocator would not be RNG whether it's possible to even attain them

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
seems fine in 2.3.7
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/03d23032-3194-403f-abbd-1d3c9af2f743)

**Comment by chochem** [comment]
its just empty vs full
