### ISSUE TITLE
A bauble that limits block breaking speed.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#14345]
### Your GTNH Discord Username

abdiel_kavash

### Your Pack Version

2.3.6

### Your Proposal

Add an accessory that caps the time it takes to break one block with a pickaxe, wrench, etc. to be not less than some minimum amount, for example 0.5s or 0.25s or thereabouts.

It would be probably best usable as a wearable bauble, I suggest vambraces as those really only have one valid item which also does something related to mining speed.

### Your Goal

Some blocks (obsidian, spawners, machine casings) have a very high hardness, and thus encourage the player to use a tool with a high mining speed. Additionally higher tier tool materials with higher durability also have a high mining speed (this is not a proportional relationship, but definitely a strong correlation). But when using such a tool, the player has to be extremely careful to not also break other blocks behind the one they intended to break because the mining speed is just *too* high.

Currently the only possible workarounds are to either carefully choose a material whose mining speed is just right to be controllable on soft materials, and deal with the fact that certain harder blocks will take a long time to break; be careful with where you aim when you break machinery; or have several picks/wrenches and swap between them depending on the hardness of the material.

If this item was implemented, the player would be free to use a tool with an arbitrarily high mining speed for tough blocks, but mining soft blocks would still take some minimum amount of time, so collateral damage to the background could be minimized.

### Your Vision

QoL for mining hard blocks, moving machine setups (especially multiblocks where the hardness of casings is usually high, and hardness of buses very low).

Incentive to use higher tier materials for tools, electric drills, or multiple levels of redstone upgrades on TiC tools.

More useful items to put in bauble slots that are not rings or amulets.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Use the alu foil head from gt++ . I guess it reduce speed.
