### ISSUE TITLE
Server Crash with "Can't find provided wand rod with id"

### ISSUE THREAD

**Issue by WitherdX** [GTNewHorizons/GT-New-Horizons-Modpack#14341]
### Your GTNH Discord Username

witherdcat

### Your Pack Version

2.3.6 with 1.1.38 AE2FC + FTBU Forks

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

We were trying to troubleshoot an issue with Thaumcraft's research page missing some Blood Magic's research. When pressing on the research it results in the client being disconnected from the server. 
Console output: https://pastebin.com/pGYmhNr2
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/59635769/fc09b388-91b8-4c84-8ecc-d52383b3551b)

As such, we attempted to fix this by replacing the individual mods (Thaumcraft-1.7.10-4.2.3.5a, ThaumcraftResearchTweaks-1.7.10-1.0.4) found from the GTNH server Java 8 downloads page.

After that, we encountered an issue where the server won't load the world anymore. Below I've attached a crash log. Thank you for taking the time to look into this.

### Crash Report

[crash-2023-08-26_18.59.04-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12447137/crash-2023-08-26_18.59.04-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Vinney88** [comment]
can any help pls

**Comment by chochem** [comment]
>  missing some Blood Magic's research

which one?

also absolutely do not replace thaumcraft version with anything else please. the other replacement wont help either.

**Comment by Vinney88** [comment]
this is what we need help with 
ava.lang.NullPointerException: Can't find provided wand rod with id: blood_wood. Be careful to register your custom rod before creating recipes.

**Comment by chochem** [comment]
thats from forbidden magic, not blood magic.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/e49a3095-3097-4401-aeb7-969e294deb96)
looks fine for me on 2.3.7

**Comment by Vinney88** [comment]
the server will not start just crashing and looking for blood wand

**Comment by chochem** [comment]
can you post logs without any mod changes?

**Comment by Vinney88** [comment]
[2023-08-25-1.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12448478/2023-08-25-1.log)

**Comment by chochem** [comment]
and which research is missing/caused the crash?

is posted the wrong above, I guess blood wood is related to one of these two:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/2536b867-d1be-4b84-94dd-17534ec965da)

**Comment by chochem** [comment]
> 



> [2023-08-25-1.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12448478/2023-08-25-1.log)

that seems unrelated, there is no crash in here

**Comment by Alastors** [comment]
Do me a favour and update to latest and see if this persists

**Comment by Alastors** [comment]
> > [2023-08-25-1.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12448478/2023-08-25-1.log)
> 
> that seems unrelated, there is no crash in here

Lmfao yeah that’s what I thought as well

**Comment by Vinney88** [comment]
[fml-server-1.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12448482/fml-server-1.log)

**Comment by Vinney88** [comment]
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12448483/fml-server-latest.log)

**Comment by Vinney88** [comment]
[message.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12448484/message.txt)
this what he was getting if this help but we replace the mod above to see if it would help but start the crashing

**Comment by chochem** [comment]
so this is a crash during server start and not a client disconnect when clicking the research like the ticket says?
I am so confused.

**Comment by Alastors** [comment]
> [message.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12448484/message.txt)
> 
> this what he was getting if this help but we replace the mod above to see if it would help but start the crashing
> 
> 

Replacing the mod does nothing, thaumcraft is ARR, all this indicates is that it can't find the research located at the data point

**Comment by Alastors** [comment]
But it doesn't tell us the data point so it's like having an arrow pointing in empty space

**Comment by chochem** [comment]
> [message.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12448484/message.txt) this what he was getting if this help but we replace the mod above to see if it would help but start the crashing

so the server crash is only after your mod replacements? well easy then: revert all that.

**Comment by Vinney88** [comment]
yes and we did revert them still will not work. and did a backup and still did not work to

**Comment by Alastors** [comment]
> yes and we did revert them still will not work. and did a backup and still did not work to

Try redownloading the pack, for the world and the clients, and then move the world over to the now download, might help

**Comment by Alastors** [comment]
Sometimes zombie errors get caught and make that required

**Comment by chochem** [comment]
gonna support the reinstall. this sounds like you messed around to much and broke some stuff in the process.

**Comment by Vinney88** [comment]
fix it ty

**Comment by Alastors** [comment]
Np, been there done that

**Comment by WitherdX** [comment]
Thank you for the support, Chochem and Alastors! Have a good one!
