### ISSUE TITLE
Add Thirst Mod to pack

### ISSUE THREAD

**Issue by payne-james** [GTNewHorizons/GT-New-Horizons-Modpack#14343]
### Your GTNH Discord Username

payn.jam

### Your Pack Version

2.3.6

### Mod Name

Thirst Mod

### The Mod to Add

Thirst Mod 1.7.10 adds a Thirst Bar along with other goodies such as Rain Collector, Drinks Brewer, Drinks Store and Drinks.
![Thirst Bar](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/134702235/5672da76-119c-4d70-9496-be9c2fa20926)

### Your Reason

Added Thirst Bar along with other goodies to make the game more fun and challenging.

### Preliminary Investigation

It seems to straightforwardly work fine. 

Github: https://github.com/thetorine/thirstmod
CurseForge page: https://legacy.curseforge.com/minecraft/mc-mods/thirst-mod

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [x] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by cainiaojun** [comment]
No.
This is GTNH, not Terra Firma: Rescue.

**Comment by boubou19** [comment]
yet another suggestion driven by realism instead of unique and enjoyable gameplay mechanic. I'm closing this.

**Comment by payne-james** [comment]
I know Terra Firma: Rescue, but add Thirst Mod can make the game more interesting.

**Comment by boubou19** [comment]
no it doesn't. see how food is quickly dealt with in the game. it's just annoying to deal with, we had to add reasons to grind for food. So to grind for drinks too... You have to understand that interesting != grind, and that grind != difficult.
