### ISSUE TITLE
mk3 space assembler and pump shut off randomly for seemingly no reason

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#14348]
### Your Pack Version

2.3.7

### Your Server

self hosted

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

mk3 space pump and assembler to not power fail when it has enough energy

### The Reality

i use a uxv 4,096 amp laser on my space elevators, which gives a solid 2 trillion eu/t to the main structure. each of the 24 assemblers uses 32 billion eu/t and the pump uses 503 million. and yet every morning i wake up and 4-5 of my mk3 pumps per elevator are dead, or 1-3 of my mk3 assemblers. i do not and have not had an issue with any of the other tiers so far

it also seemingly only happens when you use an ME output hatch or bus. as i have mk3 pumps using a normal giant output hatch (which is generally too small for the full output anyway) which have never shut off

### Your Proposal

plz fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hiagg** [comment]
bee run also had this issue so i can confirm this is an issue spanning multiple versions and is not just me

**Comment by minecraft7771** [comment]
> it also seemingly only happens when you use an ME output hatch or bus. as i have mk3 pumps using a normal giant output hatch (which is generally too small for the full output anyway) which have never shut off

So do I see this right you use void protection on all? Else it would not matter if it can't fill it completely from power perspective.
Also did you try to swap the pumps to see it really co-relates with the ME hatch and not just with their in world position.

**Comment by Hiagg** [comment]
the pumps using giant output rather than ME output do not shut off even when im not using void protection. 

also if its related to in world position then it would be quite a serious problem if all 120 of my mk3 elevator modules (mining and assembler split) just happened to be in the correct position to break. mk3 miner does not have this issue

**Comment by miaowwwwww** [comment]
can confirm, i have this problem in zeta too. 2.4.1
