### ISSUE TITLE
Partition of Fluid Disks

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#14340]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.3.5

### Your Proposal

I would suggest to make the fluid disks and multi-fluid disks be partitionable in the cell workbench
Maybe adding a new fluid cell workbench or just with the normal cell workbench

### Your Goal

In my opinion it's needed cause there are fluids like molten redstone or whatever that would need one seperate tank each or there's the way to make low priority disks or TFFT's but even then there could be problems if your bigger tanks are full and then the disks/TFFT's would get filled with stuff, that shouldn't be in it cause you can't partition them

### Your Vision

Make this happen?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
is the workbench not working? would be a bug then.

**Comment by chochem** [comment]
seems to work fine.

**Comment by joshaup1999** [comment]
I think phin said there were issues with this. Unsure whether this was fixed in dev or not

**Comment by chochem** [comment]
> I think phin said there were issues with this. Unsure whether this was fixed in dev or not

would need specifics obviously

**Comment by MaGeBZz** [comment]
I guess there is no problem it was just me lol
@chochem if you put the cells in the workbench it seems to work (on 2.3.5 rn) but it shows up as cells instead of the fluid itself
Maybe that could be fixed but were just confused about it cause only the cells show up
