### ISSUE TITLE
Biomes O' Plenty blood buckets do not empty properly.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#14358]
### Your GTNH Discord Username

abdiel_kavash

### Your Pack Version

2.4.0-RC1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Pick up Biomes O' Plenty blood that generates in the nether, and deposit it into a machine.

### The Reality

After adding the fluid to any machine, whether by clicking on the fluid slot or by placing the full bucket in the input slot of a tank, instead of a regular vanilla bucket, this is returned:

![](https://i.imgur.com/pRbzFoy.png)

This bucket doesn't stack with other buckets (regular or more glitched ones), although it can be turned back into a normal bucket in a crafting grid.

![](https://i.imgur.com/X3kunWb.png)

### Your Proposal

Inserting BOP blood into a machine should return a normal vanilla bucket.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bearsdotzone** [comment]
This bug still exists as of 2.5.1, the Certus Quartz Tank from AE2 Fluid Crafting works correctly however.
