### ISSUE TITLE
Zhuhai water consumption

### ISSUE THREAD

**Issue by Mc-Flausch** [GTNewHorizons/GT-New-Horizons-Modpack#14354]
### Your GTNH Discord Username

mcflausch

### Your Pack Version

MMC 2.3.7 Beta java 17-20

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Expectation

Zhuhai Multiblock consumes a manageable amount of water, for single or batch operation.

### The Reality

Zhuhai Multiblock consumes all the available water at the start of each operation. With each operation at IV-Tier lasting only a few ticks. Single or batch operation alike.

### Your Proposal

Make it Consume x amount of water for each operation.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
It also works without providing water at all (besides the initiall fill). Not sure if it is intended
