### ISSUE TITLE
Wrong link for Amun-Ra

### ISSUE THREAD

**Issue by TheFieryFalcon** [GTNewHorizons/GT-New-Horizons-Modpack#14367]
### Your GTNH Discord Username

quantum.in_true_form

### Your Pack Version

2.4.0-RC-1

### Your Server

N/A

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Upon clicking on the Amun-Ra mod link, I am brought to https://github.com/GTNewHorizons/amunra

### The Reality

I am instead taken to hhttps://github.com/GTNewHorizons/amunra with one extra H

### Your Proposal

Change the mod redirect to https://github.com/GTNewHorizons/amunra

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
where is that link?

**Comment by TheFieryFalcon** [comment]
I saw it in Prism Launcher's instance mods screen

**Comment by boubou19** [comment]
post a screen from where you found the link pls
