### ISSUE TITLE
Cannot make enticing crystal

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#14365]
### Your GTNH Discord Username

Santa's Child#0408

### Your Pack Version

2.3.4 custom

### Your Server

Private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

trying to craft enticing crystal, put soul vial and emerald in binder, crystal comes out

### The Reality

emerald will not go in regardless of shift clicking, hopper, import on a chest

### Your Proposal

enticing crystal to work

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
works fine in dev 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/de6ebb1e-a240-4e41-9634-3f8ff56ac77e)
