### ISSUE TITLE
Continuing to overclock a single block machine after reaching 1 tick actually reduces consumption

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#14377]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.4.0RC1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Single block machines should not continue overclocking after reaching 1 tick

### The Reality

Work well before reaching 1 tick. After reaching 1 tick, each machine level based OC (such as Luv's 1 tick formula in the ZPM machine) will halve the actual work demand EU. The higher the machine level, the less EU consumption

A 4EU/t, 40tick formula,When the machine level reaches LuV, it happens to be 1 tick (4096EU/t requirement). If the machine level is ZPM, it is 2048EU/t, and UMV is 32EU/t.

### Your Proposal

Not very important, but it should be easy to fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
this reminds me of the good old umv hatch LCR which uses 1eu/t

**Comment by JodieRuth** [comment]
> 这让我想起了老式的 umv 舱口 LCR，它使用 1eu/t

The principle is the same

**Comment by Rika-TH** [comment]
Thought this was intentional to make higher tiering machines have a greater draw for simple processing in a line

**Comment by JodieRuth** [comment]
Who wouldn't choose a PA or a multi block machine in this situation?

**Comment by iamblackornot** [comment]
Could you provide an example of the setup to reproduce issue? Machine name, recipe, etc

**Comment by JodieRuth** [comment]
Use any machine at will, as long as it is single block

**Comment by chochem** [comment]
this is old behaviour and intended code. could still change it but its not a bug
