### ISSUE TITLE
Project Red Transportation rebalance chip recipes

### ISSUE THREAD

**Issue by tbullock** [GTNewHorizons/GT-New-Horizons-Modpack#14371]
### Your Pack Version

2.4.0-RC1

### Your Proposal

Recently I conducted a clean play through of LV/MV with the intention of using the project red transportation mod. Project Red transportation is a reasonably useful item transportation mod that is available in Late LV/MV and has a balance issue with regards to the mods logic chips, especially when compared to Ender IO conduits.

In LV/MV progression the ender IO conduits are cheaper and largerly more powerful and much easier to use than the project red item pipes. There are only a handful of use cases that project red is superior, however the cost of the mod is drastically higher.

Project red uses chips to indicate whether an interface pipe should extract, store items, etc. Of course this functionality is built directly into ender io conduits.  Part of the balance problem betwen the mods is that ender io conduits don't require gregtech circuits where as project red chips currently require 2 different gregtech circuits in their production.

1. In the Nul chip
2. In each of the final chip recipe

**This change request is to remove the gregtech circuit from the final chip recipes (leave them in place for the nul chip).**

### Your Goal

To bring project red transmission costs closer into balance with Ender IO and encourage players to consider using this alternative item transportation mod.

### Your Vision

Improve the viability of LV->HV item transportation options before Applied energistics unlocks in EV

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by xXseesXx** [comment]
what this guy said, whe have so many items and searching 100 chest or 1000 drawers is just unfun
