### ISSUE TITLE
PrAss ignores additional current when installing TecTech energy storage and no longer overclocking or paralleling

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#14374]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.4.0RC1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

PrAss should correctly identify the total power brought by TecTech energy storage and arrange for parallel and overclocking

### The Reality

PrAss only executes its corresponding formula and basic possible overclocking according to the TecTech energy warehouse level when installing the TecTech energy warehouse, ignoring the additional current brought by the TecTech energy warehouse. For example, a UEV 4096A energy storage chamber produces UEV superconductors without any overclocking, only with basic 100% acceleration. If UHV superconductivity is produced, then due to the power of UEV being four times that of UHV, it is normal to overclock once, and then ignore the excess current and no longer overclock.

![I ~86GZ)@JIXV)MKOWSE8ZI](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/e9470d66-16f2-4daa-b0af-3935f4ac7519)

![OCS_ 2_P6I`6XZ74F8{)( 9_tmb](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/11220a0a-2e44-4c3d-8d1a-bf6b6ec1fb09)

![XVT6QPSSA1YXS}%(0U0{EHW](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/d98d8ff3-20bc-4bd6-9ae8-5a62d8b3f15f)

This is the production of UHV superconductor (UHV, 128 seconds), and it can be seen that the correct use of 100% acceleration and one overclocking arrived at UEV32 seconds, still ignoring the additional current.

![ZHP1I7X` 4NDO2I9MH}H$YJ_tmb](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/46f76df4-55da-42f8-9ce8-2aed4f65e79f)

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/99db975d-909e-443b-a123-2e047b03e735)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/4d2059c8-770c-493f-822c-0c5798c22e6b)

can confirm, this is important, should be fixed before stable

**Comment by chochem** [comment]
so it doesnt do parallel?

**Comment by chochem** [comment]
together with your other ticket that sounds like the modes are swapped regarding parallels?

**Comment by JodieRuth** [comment]
After more testing, it seems that this issue is only concentrated during overclocking.

**Comment by JodieRuth** [comment]
Ah yes, it only overclocking based on energy hatch level and formula level, completely ignoring the additional power brought by TecTech

**Comment by miaowwwwww** [comment]
so before:  UMV laser, do umv sc recipe, which is 80s umv. we can parallel and overclock if given enough energy.
 now: it does 80s per run with only 1 parallel regardless.

**Comment by BlueWeabo** [comment]
When was the before.

**Comment by JodieRuth** [comment]
Every version of PrAss that runs normally before non 2.4.0RC1

**Comment by chochem** [comment]
> Every version of PrAss that runs normally before non 2.4.0RC1

well thats not correct. it was broken way worse in 2.3.7. but I understand now I think.

in 2.3.0 for example it was restricting recipes based on energy hatch tier but still OCing them beyong energy hatch tier if they were allowed. is that correct?

**Comment by miaowwwwww** [comment]
yes

**Comment by JodieRuth** [comment]
First, use the 100% acceleration of the machine itself, and then overclock based on the additional power brought by TecTech energy hatch

**Comment by chochem** [comment]
> First, use the 100% acceleration of the machine itself, and then overclock based on the additional power brought by TecTech energy hatch

no thats false. that was the broken stuff in 2.3.7
