### ISSUE TITLE
New Mod Baubles Expanded

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#14378]
### Your GTNH Discord Username

Ethryan

### Your Pack Version

2.4.0rc1

### Mod Name

[Baubles Expanded](https://github.com/jss2a98aj/Baubles-Expanded)

### The Mod to Add

Baubles Expanded = more baubles slots and different types of them.

### Your Reason

A reminder for next dev cycle.

### Preliminary Investigation

Witching Gadgets needs to be edited to use this. And the rpg inventory mod should be removed.

As discussed off and on in magic_dev channel.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Alastors** [comment]
Yeah this needs to happen.
