### ISSUE TITLE
[JourneyMap] Some hotkeys for "create waypoint" overwrite default waypoint name.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#14376]
### Your GTNH Discord Username

abdiel_kavash

### Your Pack Version

2.4.0-RC1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Set the hotkey to JourneyMap's Create Waypoint function to a letter key. Press this hotkey in game. The "new waypoint" menu is opened, with the name of the waypoint defaulting to the player's coordinates.

### The Reality

Now set the hotkey to a key on the numpad (I tried Num 9, -, and +). Press this hotkey in game. Now the name of the waypoint defaults to the key you pressed. (E.g. the name is just "+" when you bind the button to Num+.)

### Your Proposal

Default the name of a new waypoint always to the player's coordinates, regardless of which key is bound to the function.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
Numpad asterisk does this, and drives me insane, as it is what I always use for create new marker. And, it is GTNH specific, not mod specific.
