### ISSUE TITLE
disable/ make toggleable light spread from awakened ichor leggings

### ISSUE THREAD

**Issue by TenyaThTM** [GTNewHorizons/GT-New-Horizons-Modpack#14381]
### Your GTNH Discord Username

tenyath

### Your Pack Version

2.4.0 RC1

### Your Proposal

disable/ make toggleable light spread from awakened ichor leggings

### Your Goal

when walking with these leggings on the ground, I notice a decrease in fps, also the light left after walking does not look nice

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
We have previously discussed being able to toggle the individual features of the ichorium armor on/off independently, similar to Draconic armor, and Alastor said it would be easy to implement. I support this.

**Comment by Persus1** [comment]
Its already possible to deactivate every armor piece individually. Just hold the armor piece in your hand and shift right-click them. It deactivates all features of that specific armor piece but at that point you are able to craft Ichor you dont really need fire resistance on your leggings anymore im pretty sure.
![Unbenannt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/130587498/279ca0d7-5931-4c98-9689-4a5a4ddffba7)

**Comment by TenyaThTM** [comment]
> Its already possible to deactivate every armor piece individually. Just hold the armor piece in your hand and shift right-click them. It deactivates all features of that specific armor piece but at that point you are able to craft Ichor you dont really need fire resistance on your leggings anymore im pretty sure. ![Unbenannt](https://user-images.githubusercontent.com/130587498/264632540-279ca0d7-5931-4c98-9689-4a5a4ddffba7.png)

Oh, i didnt notice it. Anyway, it would be useful to make every ability toggleable
