### ISSUE TITLE
MABS using normal ABS coils voids inputBus but doesn't run recipe

### ISSUE THREAD

**Issue by joutenchi** [GTNewHorizons/GT-New-Horizons-Modpack#14386]
### Your Pack Version

2.3.7

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

update to 2.3.7,run MABS

### The Reality

after updating to 2.3.7,my MABS does not run any recipe but void input bus.

when i changed normal ABS coils to any other coils,MABS ran well

### Your Proposal

fix it or change MABS structure requirements

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by binaryalgorithm** [comment]
I have the same issue in 2.4, Java 17, Multiplayer. I used default coils and it voids inputs while not running at all.

**Comment by BlueTRaven** [comment]
I'm encountering this issue also in 2.4.1. Looking at the controller shows a "power overflow" error, and inspecting with the scanner shows that it has a 100% discount. I'm assuming what is happening here is that the power consumption becomes zero and results in a divide by zero, thus the overflow.
