### ISSUE TITLE
Ore Finder Wand no longer activates until the GUI is closed

### ISSUE THREAD

**Issue by Novie53** [GTNewHorizons/GT-New-Horizons-Modpack#14387]
### Your GTNH Discord Username

Quintus#6363

### Your Pack Version

2.4.0-RC1

### Your Server

Private server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

Ore Finder Wand no longer activates(rotates & makes sounds) until the GUI is closed.

### The Reality

.

### Your Proposal

Intended change or bug?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
I think this makes sense. The moment an item is detected in its inventory, it should start working. That is just my opinion of course.
