### ISSUE TITLE
Behavior and Description does not Match: Boots of the Voidwalker Can jump 25 blocks High

### ISSUE THREAD

**Issue by KitoCedon** [GTNewHorizons/GT-New-Horizons-Modpack#14396]
### Your GTNH Discord Username

Cedon#7261

### Your Pack Version

2.4.0-RC-1

### Your Server

Both SP and Private Server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Jump with Boots of the Voidwalker (Only Boots of the Voidwalker)
In Previous versions it just jump about 4 blocks high

### The Reality

Boots of the Voidwalker jump 25 blocks high

### Your Proposal

Varieties of Boots of the Voidwalker, (Like Electric Boots of the Voidwalker, Nano Boots of the Voidwalker, Metroric Boots of the Voidwalker...and so on) They are working in correct.

if the new mod ThaumicBoots change the value? or it is a bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by KitoCedon** [comment]
Also, Voidwalker don't show the Vis Discount (it has 5%)

**Comment by Alastors** [comment]
Is it just the Voidwalker boot, the base boot

**Comment by KitoCedon** [comment]
> Is it just the Voidwalker boot, the base boot

Yes, just "Boots of the Voidwalker"
