### ISSUE TITLE
Mk4 Fusion not craftable

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#14398]
### Your GTNH Discord Username

lordpeverell

### Your Pack Version

2.4.0 RC1

### Your Server

Private

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Trying to craft mk4 fusion in assline, all parts are in there correctly. Have previously crafted without issue on 2.3.2

### The Reality

It no work

### Your Proposal

Fix please 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
user error
