### ISSUE TITLE
Change how the Industrial Apiary's temperature upgrades work

### ISSUE THREAD

**Issue by Gofer2x** [GTNewHorizons/GT-New-Horizons-Modpack#14406]
### Your GTNH Discord Username

gofer776

### Your Pack Version

2.3.4

### Your Proposal

Wasn't sure if to make this a bug or suggestion, so went with the latter.
Tweak the values of the upgrades (probably change 25% to 20%, would need to be tested) or change them in some other way (like making an upgrade shifting a temperature/humidity level by 1/-1, recipes and max stacks would need to be ajusted obviously).

### Your Goal

As it is right now, certain Temperature tresholds can't be hit in certain biomes, e.g. in a Cherry Blossom Grove biome (Normal temperature) you can't get to a Warm temperature. One upgrade isn't enough to change to Warm, but two make it Hot.
Humidity only has 3 levels as opposted to temperature's 5 (excluding Hellish), so it's not a problem with it.

### Your Vision

The iapiary is supposed to help solve bee problems such as climate, but in its current state it still leaves some blind spots with unreachable temperatures. This could possibly break some current setups, but would be better in the long run.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I am not saying this is like the ideal solution or anything. But:
You can actually get warm by using a jungle emulation upgrade.

**Comment by kuba6000** [comment]
Fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2091

**Comment by chochem** [comment]
1 upgrade in normal biome = hot (personal dim):
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/2ae28204-992c-40d4-ac89-2b3c5805df56)

I dont think that fix is working

**Comment by chochem** [comment]
ah that fix excludes heater specifically

**Comment by kuba6000** [comment]
> ah that fix excludes heater specifically

hmm. Can you put a heater and cooler upgrade together to get warm temp then?

**Comment by chochem** [comment]
yea I was thinking the same. you can:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/86c3187e-a9c5-459f-968e-e402e45e6f91)
but I guess its a similarly not-quite-perfect solution to using a jungle upgrade.

was there any reason heater was excluded?

**Comment by kuba6000** [comment]
> yea I was thinking the same. you can: ![image](https://user-images.githubusercontent.com/40274384/265704525-86c3187e-a9c5-459f-968e-e402e45e6f91.png) but I guess its a similarly not-quite-perfect solution to using a jungle upgrade.
> 
> was there any reason heater was excluded?

I don't remember any. @Runakai1
