### ISSUE TITLE
Dyed ME Glass Cable can't be un-dyed

### ISSUE THREAD

**Issue by truenachtara** [GTNewHorizons/GT-New-Horizons-Modpack#14404]
### Your Pack Version

2.3.7

### Your Server

private server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Ability to un-dye glass cable like any other cable

### The Reality

No uses for dyed glass cable, even in an un-dyeing recipe

### Your Proposal

Any dyed glass cable -> fluix dyed cable

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by querns** [comment]
A color applicator with snowballs inside can remove the dye from a dyed ME cable of any kind, when the color applicator is set to "fluix" mode.

**Comment by truenachtara** [comment]
It shouldn't be required to place it in-world to remove color- this isn't how smart or dense cables work, they have a crafting recipe to remove color
