### ISSUE TITLE
gtnh crashing my driver

### ISSUE THREAD

**Issue by kklgtf** [GTNewHorizons/GT-New-Horizons-Modpack#14409]
### Your GTNH Discord Username

lucccarade____

### Your Pack Version

2.4.0-RC2 java 17

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

i imported the pack in prism launcher, launched it and it crashed my driver , my graphics card is an radeon RX550/550 series

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12504283/fml-client-latest.log)
[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12504284/GregTech.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12504285/latest.log)
when the modpack gets into [22:29:58] [Client thread/INFO] [GregTech GTNH/gregtech]: BulkRemoveByRecipe: tList: 23314 it crashes my driver

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
Sounds more of a driver or hardware issue than a modpack issue. It looks like each time the pack is putting a load on the computer, it crashes. Logs are looking perfectly normal, just that the game is terminated by the computer. Nothing we can do, as it is beyond the scope of the help we provide here.

**Comment by Glease** [comment]
Try adding `-Djava.util.concurrent.ForkJoinPool.common.parallelism=1` to java argument. This will reduce the load we put on computer and probably give some breathroom for the half-broken driver. Note this will have negative effect on the loading time and some minor aspect of the game will be slower.

try replace `1` with greater number for greater gaming experience. Usually it's best to have it as many as your CPU has cores, but given your driver crashes, I guess we must make a compromise here...

**Comment by kklgtf** [comment]
thanks for the help
