### ISSUE TITLE
Make the talisman of nutrition fill your nutrition tab

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#14400]
### Your GTNH Discord Username

maniifestantes

### Your Pack Version

2.4.0 RC-2

### Your Proposal

With the addition of the nutrition mod, you need to eat different kinds of food to balance out the five types of nutrients in you, but that can be circumvented by the healing axe, but not with the tin can or the talisman of nutrition.

### Your Goal

Making the talisman of nutrition and tin can slowly fill the nutrition bars as well.

### Your Vision

having more options to circumvent the nutrition and having to hold the healing axe would be nice to have

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Quetz4l** [comment]
Also up to 50% or 100%? 100% looks ok because you have to waste food for the cans and the talisman.

**Comment by chochem** [comment]
should be 50% as you are not interacting with the system at all.

**Comment by Savallator** [comment]
I don't think tin cans work. Nutrition stays at 0% and you end up getting debuffs.

**Comment by mitchej123** [comment]
I'm fairly certain tin cans send your nutrition to neutral (50%) unless you've changed the configs.  Or at the very least, that's the intent.

**Comment by Savallator** [comment]
It did not. I only eat tin cans, nutrition was constantly at 0%. Had to remove the mod, since the config is also not helpful, can't even disable the debuffs.

**Comment by mitchej123** [comment]
Can always submit a PR with bug fixes, or post an issue with modlist/logs ;)

**Comment by mitchej123** [comment]
EIther way, things like the healing axe _not_ sending nutrition to 50% is a bug as far as I'm concerned and should be fixed.

**Comment by Savallator** [comment]
I commented here because this issue already talked about it, but i can make a seperate one, sure.
