### ISSUE TITLE
Four Aqua Regia recipes that are identical in the Multiblock Mixer, but have different Programmed Circuits.

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#14405]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.4.0RC2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

/

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/4a48d3cd-9e41-422e-b749-7fed29a9e97d)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/2ec0226d-73c6-42a4-92d2-b3e215f04528)
Exactly the same, but sometimes it can cause it to fail to run

### Your Proposal

Delete the recipe for 2-4 Programmed Circuit

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by JodieRuth** [comment]
The single block Mixer also has four different Aqua Regia recipes. Please also delete the Aqua Regia recipes for the 2-4 programming circuits of the single block Mixer together

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/bfc7560e-31d7-4711-8d02-da3b78a3ac35)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/bda7be9a-3beb-486b-953d-97b11d8ab5e0)

**Comment by Dream-Master** [comment]
why? i think is is good use all combination if possible. Later one you use the lcr sure.

**Comment by JodieRuth** [comment]
Essentially, they are different programming circuit forms of the same recipe. Aqua Regia can only be produced by Mixer, and these four different recipes sometimes cause Multiblock Mixer to encounter abnormal problems that cannot be started.

**Comment by JodieRuth** [comment]
Oh, if you're talking about their programming circuits in a single block mixer, but in reality they don't conflict with each other, deleting the programming circuits in the recipe is safe

**Comment by JodieRuth** [comment]
There are also errors in the recipe of a single block Mixer, such as the two recipes in the picture that are completely identical but have different programming circuits. I think deleting the programming circuit requirements of 2-4 and then deleting an incorrect recipe is suitable for single block modifications. As for the mutilblock mixer, delete all additional recipes
