### ISSUE TITLE
IC2 electric items show incorrectly in ME system when there are multiple

### ISSUE THREAD

**Issue by Reinforced23** [GTNewHorizons/GT-New-Horizons-Modpack#14408]
### Your GTNH Discord Username

reinforced23

### Your Pack Version

2.4.0-RC-2

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Wanted to craft up some Ultimate Batteries for Lapatronic Supercapacitor, but then noticed, that lapotronic crystals from IC2 had not crafted.

### The Reality

Flew up to Precise Autoassembler, but lapotronic crystals didn't stuck anywhere, then checked my AE2 system and noticed that all lapotronic crystals had energy value of (0/0 EU) then it is needed to be (0/10m EU).
Tried to extract crystals from AE2 and ordered new ones, but problem remained the same.
Even made a new instance on MultiMC and made a new world, but it is still the same (screenshot)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127662941/a0a3d3f1-7190-4c59-9c7d-741abb15873b)

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
hmm, works fine on my end (2.4.0RC2):

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/9a50171a-3f15-4d5b-8a2c-c0d72d39edbf)

I dont use precise assembler, thats the only difference I can see, maybe check if its related to that?

**Comment by Reinforced23** [comment]
Well, as we found out it is a visual bug and the problem was with the patterns.
Updated them and it works fine for crafting, but the bug remains for now

**Comment by chochem** [comment]
yea the remaining bug I can reproduce is that all IC2 electric items (not just lapo) break visually in AE2 storage or patterns when there are multiple:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/2555137e-c2b2-4452-bbf9-4c95762fe08b)


however this seems to be just a visual bug
