### ISSUE TITLE
Boots of Comet series + base Comet Boots do not provide fall protection

### ISSUE THREAD

**Issue by KitoCedon** [GTNewHorizons/GT-New-Horizons-Modpack#14402]
### Your GTNH Discord Username

Cedon#7261

### Your Pack Version

2.4.0-RC-2

### Your Server

Both SP and Private Server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Jump with Boots of Comet series

### The Reality

Take Fall Damage, Boots of Comet doesn't use Election instead of Damage

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/69830608/8e79e14f-cc28-443c-a644-716552bc55bb

### Your Proposal

Add fall protection to Boots of Comet series

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
As you clearly demonstrated, this isn’t specific to the Thaumic boots comet series, this is from the base comet boots

**Comment by Alastors** [comment]
Do the base electric boots even provide fall protection? I took the code directly from them?

**Comment by Alastors** [comment]
Been informed they do in the pack, will add this
