### ISSUE TITLE
larvae recipe in Incubator broken

### ISSUE THREAD

**Issue by shenpan2330** [GTNewHorizons/GT-New-Horizons-Modpack#14416]
### Your Pack Version

2.4.0rc2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Trying to craft bee
![FDQ9 6M WWY_YS(A7FW2`}1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/141908880/17539907-7caf-40ab-8998-ab88b73b1253)

### The Reality

![X63K0KH)T}~0S4LD%KKGHL5](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/141908880/10f1f2c5-b96c-4a52-a546-731019ec0bc4)

### Your Proposal

Fix the output tank

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TenyaThTM** [comment]
same as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13885

**Comment by Pxx500** [comment]
duplicate
