### ISSUE TITLE
weird texture bug

### ISSUE THREAD

**Issue by buchitomil** [GTNewHorizons/GT-New-Horizons-Modpack#14412]
### Your GTNH Discord Username

buchitomilX

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

i tried to join a world called "Speed Raun" that i made. i expected to play normal gtnh

### The Reality

the whole screen became the color of the block i was looking at. to see normally i had to hold the quest book i had and punch the block below me while looking in a cardinal direction. even then there were a ton of gray blocks, and i had to break snow to un-gray the blocks. seed is -1779887420996239449 if it helps.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/143905372/72604a2f-e275-4598-825f-852d0e78fafc)

### Your Proposal

idk just fix it ii guess

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
Please supply a log, to see what happened. But offhand i would guess graphics driver issue, probably intel drivers.
Check #13512
or search for issues tagged with intel drivers.
