### ISSUE TITLE
Ctrl + Alt + C not terminating OpenComputer programs

### ISSUE THREAD

**Issue by Zeruel13** [GTNewHorizons/GT-New-Horizons-Modpack#14421]
### Your GTNH Discord Username

zeruel1169

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

When running OpenComputer programs, hitting Ctrl + Alt + C should terminate the program. However, it doesn't seem to be doing anything. 

I tested with previous versions, and found that in 2.3.4 Beta, this started for me. 

2.3.3 Beta has no issues with terminating programs.

I tried to find causes such as key bind conflicts but couldn't find anything. All testing was done with fresh instances and nothing changed. 

The only cause I could find that might have caused it was in 2.3.4 Beta, OpenComputer code was changed but I don't know enough to determine if that code changes caused this. 

### The Reality

Nothing happened when hitting Ctrl + Alt + C

I set up a macro to ensure it wasn't user error. Macro worked in 2.3.3 Beta, not in 2.3.4 Beta and onwards and including 2.4.0 Stable

### Your Proposal

Make Ctrl + Alt + C terminate programs again. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
what happen if you try the java 8 pack version?

**Comment by Zeruel13** [comment]
> what happen if you try the java 8 pack version?

2.4.0 Stable Java 8 works with no issues.

To confirm, 2.3.3 Beta was Java 20 when it was working. Anything after that with Java 20 doesn't work.
