### ISSUE TITLE
failure when starting minecraft in version 2.4.0

### ISSUE THREAD

**Issue by coolness20099** [GTNewHorizons/GT-New-Horizons-Modpack#14426]
### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

just upgrade my world from version 2.3.2 to version 2.4.0 and I'm done.

### Crash Report

https://paste.atlauncher.com/view/0ce1fc30-ea8c-4224-b3cb-68bc30fc042c

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
You have a bunch of duplicated / missing mods, check your install https://gtnh.miraheze.org/wiki/Installing_and_Migrating
