### ISSUE TITLE
Uninsulated wires don't deal damage

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#14431]
### Your GTNH Discord Username

pxx500

### Your Pack Version

2.3.0/2.4.0

### Your Server

Irrelevant (Tested on SP, confirmed by multiple players not sure where they tested it))

### Java Version

Java 20

### Type of Server

None

### Your Expectation

get electrocuted after coming in contact with uninsulated wires and without armor

### The Reality

I didn't :(

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
Sanity check: was the cable actually under load?

**Comment by Pxx500** [comment]
my test (2.4.0, niobium tianium, LuV, 1A)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/9fc0eca7-c6c0-4317-99ca-ef9872468c87)

From xskewer
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/5a9ed323-d484-4194-b4af-f9b2ac1f7676)

From ghostipedia
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/db4b2652-1ee2-40fe-a6a7-b6329110590a)
