### ISSUE TITLE
Voiding mode not working for processing array

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#14435]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.4.0

### Your Server

Delta and SP

### Java Version

Java 17

### Type of Server

Thermos

### Your Expectation

PA should start processing a recipe with a number of parallels

### The Reality

The PA claimed "Not enough output space" despite all output buses/hatches being empty and their capacity being large enough for the recipe involved.

Enabling `voiding mode: fluids` starts the processing, but neither consumes the input cells, nor produces filled cells.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8459776/8f7aec21-4d85-4617-9d12-4596f04cfd05)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8459776/ce711f36-7f09-4932-ba79-9af94aba79b2)

Inputs:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8459776/35be3800-94ea-42aa-b618-86988064c9ca)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8459776/0e0fadc7-d999-4abd-a68b-c30fcd05c680)
Outputs:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8459776/beac4869-7759-4e26-bbf5-6e893efa4261)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8459776/3d7f999d-2f8c-4096-8be9-980fbe1af290)

### Your Proposal

Fix the voiding check.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by combusterf** [comment]
Looks like everything involving electrolysers and cells is broken

**Comment by chochem** [comment]
its not really broken. But replaced by cell-free recipes. I guess its not really documented or at least not well.

**Comment by boubou19** [comment]
PA will soon enter in deprecated mode anyways, meaning you won't be able to craft controllers anymore. This multi is a nightmare to maintain, it's time to put it into retirement.

**Comment by combusterf** [comment]
It's an annoying change and breaks existing setups :pensive:
