### ISSUE TITLE
Compressor producing wrong stone plates

### ISSUE THREAD

**Issue by Tristatus** [GTNewHorizons/GT-New-Horizons-Modpack#14433]
### Your GTNH Discord Username

tristatus

### Your Pack Version

2,4,0

### Your Server

Private / Unofficial Community Server

### Java Version

Java 19

### Type of Server

None

### Your Expectation

2 of my Players where throwing Stone Dust into a Compressor as suggested by the recipe to produce Stone Plates.
![Recipe](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/44020195/245ca987-14ab-464b-a698-9008ff2d4eb8)

### The Reality

Instead of a stone plate they get "gt.metaitem.01.17299.name" from the compressor. For Myself its a normal Stone plate

![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/44020195/19d508d3-4555-402e-858c-67fa7b1e3b2c)

![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/44020195/894e6bc2-5774-478c-9f94-c3fff96832d0)

### Your Proposal

That every player gets the same item / shown the same

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
there is only one stone plate in 2.4.0
if you have 2 then you probably have old scripts files hanging around. Make sure that your script folder is empty.

**Comment by chochem** [comment]
that looks correct yea. only the other one matters.

**Comment by Tristatus** [comment]
Resolved.
I emptied the scripts folder from the Server (got updated from 2.3.0 to 2.4.0) and now the correct plates get produced.
Thanks @chochem
