### ISSUE TITLE
When bees set Aura Node as a honey collection object and have magicbees.effectNodeEmpower, they can directly charge tens of thousands of vis to Aura Node in one operation.

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#14436]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Use bees with the magicbees.effectNodeEmpower trait to power up the Aura Node

### The Reality

The bee added tens of thousands of random vis points to Aura Node at a time. The first job will always add to the existing vis instead of random additions, and then randomly add a composite vis with tens of thousands of vis points. Finally, because the vis has passed Multiple stops work, forming an Aura Node with only several tens of thousands of vis, instead of the previous version of Aura Node with many random vis.

### Your Proposal

Adjust the value so that the Vis charged by the bee for one work becomes the normal value.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
unfortunately, this is not a bug, as has been confirmed by @Runakai1
