### ISSUE TITLE
add a multi for un/canning (item+fluids)

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#14446]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.4.0

### Your Proposal

add a multi that will be doing both canner and fluid canner recipes.

### Your Goal

there is no multi for them rn, PA is the only way to do this at high speed.

### Your Vision

Adding this will add more consistency to the single block -> multi progression, and will remove one reason to keep the PA to the game.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by FourIsTheNumber** [comment]
Resolved: https://github.com/GTNewHorizons/GT5-Unofficial/pull/2729

**Comment by NotAPenguin0** [comment]
Fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2729
