### ISSUE TITLE
add new specialised multis to replace the large processing factory.

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#14444]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.4.0

### Your Proposal

The Large Processing Factory is a 9 in 1 multi. I propose to make a dedicated multi for each of the 9 machines it replaces:
- compressor
- lathe
- polariser
- fermenter
- fluid extractor / fluid solidifier
- extractor
- laser engraver
- autoclave

This feels like the original author didn't wanted to make a multi for those niche machines, during time when it was annoying to add a multi. But now that we have GPL and structure lib (and soon MuTEs). It feels like we need a dedicated machine for each of those machines. This is also inline with the PA removal, as conceptually this multi is just another PA.

### Your Goal

Add missing multis and be inline with PA removal

### Your Vision

Add cohesion to the pack, as every single block should have a multi.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
Consider that even having three of the less-used machines (compressor/lathe/polarizer; to a degree engraver/autoclave also works for most recipes) in one multiblock, only distinguished by the input bus, is still fairly useful. If each machine gets its own multi, each of these recipes will need a dedicated machine, even if it is only used a tiny number of times.

**Comment by boubou19** [comment]
LPF can coexist with those specialised multi, but there is still a need for dedicated multis.

**Comment by AbdielKavash** [comment]
If both exist at the same time, what would make someone choose one over the other? Cost? Tiering? Bonuses (speed/energy/parallels/etc.)?

**Comment by boubou19** [comment]
to be defined, but since the LPF is more general than those specialised multis, they are going to be faster. Now, to define faster... this will be discussed with others. But thoses are balancing details, tweaking numbers can be done later, but we need the multi in the pack.

**Comment by joshaup1999** [comment]
> If both exist at the same time, what would make someone choose one over the other? Cost? Tiering? Bonuses (speed/energy/parallels/etc.)?

The fact the LPF will be getting depreciated as well I figure would have people use it

**Comment by Eranicus** [comment]
Please correct me if Im wrong or maybe I dont understand something... but since MuTEs will replace all existing multiblocks and PA's in future, what is the reason for all these new separate machines now ? Isnt it just a waste of "development and testing time" or these machines will be possible to easy convert to MuTEs later on ?

**Comment by joshaup1999** [comment]
These will be MuTE multis, Boubou is just getting a list together of what needs to be done in terms of MuTE replacements for highly used PAs

**Comment by AdolMors** [comment]
Would it be a good time as well to try to tackle the solidifier problem? Solidifier getting its own multi does not solve the problem of input hatches not having a slot for mold.

Introduce a new input hatch with mold slot? Add mold slot to all existing input hatch (solidifier is the only user though)? Introduce single use mold like single use tools?

Or this is to be solved by MuTEs.

**Comment by isadora-6th** [comment]
> Introduce a new input hatch with mold slot? Add mold slot to all existing input hatch (solidifier being the only user)? Introduce single use mold like single use tools?
Also, would love to set circuits for certain liquids in chemical reactors. You simply can't use single chemical reactor for palladium extraction and palladium solution if you want full dusts at the moment.

**Comment by BobGoldham** [comment]
Should this be added anytime soon (heh..), I propose that the polarizer-multi can be screwdrivered into a separator mode for the 3 or so recipes (notably: tengam) that use it. It seems to make sense, since both are essentially a big magnet.

**Comment by FourIsTheNumber** [comment]
![4171b1b35e0c25ed4871c1109372ea4c-1](https://github.com/user-attachments/assets/a3ecceb3-bce0-414e-b08a-1bcd5866f5d7)
