### ISSUE TITLE
Rename false ruby to spinel

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#14443]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.4.0

### Your Proposal

Rename the fake "ruby" material, with the formula MgAl2O4, to "spinel". This material has the chemical formula of spinel.

### Your Goal

Changing the name of the material would alleviate confusion due to there being two identical looking "ruby" materials with different chemical formulae. The duplicate "ruby" has the chemical formula of spinel, so the alternative name would accurately reflect what the material _is_.

### Your Vision

The name change would alleviate confusion and make it so that people no longer have to account for two almost-identical "ruby" materials. This is especially relevant now that _real_ ruby has the ruby juice processing method, while fake "ruby" (the one I propose a name change for) lacks this processing chain.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
The confusion is intended. The fake rubies have already been nerfed many times, like moving them to tf only and adding a chem formula. Initially you were not supposed to be able to distinguish the two whatsoever, except by using them and realizing that the recipes do not work.

**Comment by Rika-TH** [comment]
And originally, that sucks, I think renaming them to fake ruby however could be more entertaining if a player were looking for rubies
It gets you once, and then past that until you have automation it's just annoying, same with most gems from TF, imo they'd be fine gone, less crap everywhere

**Comment by desagas** [comment]
Have you tried the easy minecraft mode called "creative." I mean ... I love that you actually have to think about what you are doing for once in a modpack. It is because of these quirks that I love GTNH!

**Comment by Alastors** [comment]
> Have you tried the easy minecraft mode called "creative." I mean ... I love that you actually have to think about what you are doing for once in a modpack. It is because of these quirks that I love GTNH!

Could you be any less ***condescending?*** You’re highkey being a dick, if you don’t have anything constructive to say, don’t say it man.

**Comment by Alastors** [comment]
Anyway, I think changing it to Spinel is a warranted change, especially with how few informal names we use throughout the pack

**Comment by hallucinogender** [comment]
Since it is clearly not self-evident to everyone, my reason for suggesting this change is that I do not believe there is any benefit to having a game mechanic whose _sole_ function is to deceive even players who are experienced enough to be fully familiar with it. GTNH makes plenty of changes to GT5U in order to make the modpack better than if GT5U were left in its default state, so I don't think that "deceptive fake ruby is _intended_" is grounds to summarily dismiss any discussion of whether it should be altered.

What gameplay benefit does the false ruby provide? What is its _function_? It does two things: first, it confuses people who are new to the modpack, or new to Gregtech in general; and second, it frustrates anyone who is designing a sorting method for ore processing systems because it is so easy to simply _forget_ that there is a fake "ruby" to consider in the first place, even when it is known about. I don't think these effects make the modpack better; I opened this issue to argue the stance that these features in fact make the modpack _worse_.

**Comment by vovaksenov** [comment]
Idk, i dont think that a very minor inconvenience to some players is enough of a justification to get rid of an ancient easter egg kind of a thing. In fact, what this discussion shows is that it is not only supposed to work as a sort of a troll, but actually succeeds: causing mild irritation with *negligible* harm. My point is not to shut down the discussion, but to point out that this mechanic works as intended and your points only make its case for existence stronger. If you really want to address problems with stuff not corresponding to real life chem, i would suggest you look into gt++ nonsensical lines and alloys (which actually matter when it comes to gameplay) rather than this.

**Comment by Alastors** [comment]
@vovaksenov bad example bud, we already killed off all of those this dev cycle

**Comment by vovaksenov** [comment]
Bad example does not mean my point is invalid, especially as it is not even something i am supposed to be aware of. And anyway, "oh ho, got the player" can be certainly be funny. I am amused by how serious and heated this discussion got at the very least, considering that fools ruby problems are solvable with one click.

**Comment by SunsfuryAlpha** [comment]
As someone who "got got" when managing inventories and getting confused over the two types of rubies, once I noticed the different chem fomulas, my response was confusion and a big "why on earth does this even exist". The difficulty of GTNH should be in challenges that actually respect the player, not in a cheap 'gotcha' moment that ticks off earlygame players
