### ISSUE TITLE
add a multi for the brewing machine

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#14448]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.4.0

### Your Proposal

add a multi for the brewery, as it can be required for bacteria, and it's missing right now.

### Your Goal

This is one of the rare cases PA is relevant to use, as there is no alternative.

### Your Vision

Adding this will add more consistency to the single block -> multi progression, and will remove one reason to keep the PA to the game.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
this multi already exists and is called the Bacterial Vat. And yes that includes bacteria.

**Comment by dahgul333** [comment]
mb add brewing mode to fluid heater multi ?

**Comment by chochem** [comment]
I guess we should close this as we have a multi

**Comment by bombcar** [comment]
It doesn't come up when you search "brew" in NEI, so maybe we need a quest to point to it? Or modify the tooltip so it does.

**Comment by chochem** [comment]
the quest says so of course. but more never hurts

**Comment by dahgul333** [comment]
> I guess we should close this as we have a multi

If you mean Bacterial vat ,it-no 
Because each base have array what doin lube from oil and i am don't see recipe in vat (even if there was one I would prefer Arrey)

**Comment by chochem** [comment]
that just means adding recipes
