### ISSUE TITLE
issues holding PA deprecation

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#14441]
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14440
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14445, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16707
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14446
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14447, https://github.com/GTNewHorizons/GT5-Unofficial/pull/2723
- [x] ~~https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14448~~
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14449

bonus round:
- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14444

**Comment by Caedis** [comment]
Related issues:

- [ ] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17271
Description: Some machines like the brewery could use a multi or the dehydrator multi could be downtiered (or a new, lesser one is added) to fill the gap

**Comment by chochem** [comment]
PA is deprecated in 2.7.0
