### ISSUE TITLE
Tier down precise assembler to IV with new tier 0 precise casings

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#14449]
### Your GTNH Discord Username

chochom#0271

### Your Pack Version

2.4.0

### Your Proposal

Add a new 'Imprecise Electronic Unit Casing'/'Precise Electronic Unit Casing mk 0'. this should be
- IV tiered
- not allow for precise mode (or have a new tier 0 precise tier where currently there are no recipes)
- have 16 parallels (consistent with doubling for each casing)

### Your Goal

This is part of the efforts to remove the PA in a smooth way. Giving the player a multiblock assembler in IV for parallels, cleanroom, and multi hatch/bus management.

Currently, the controller of the precise assembler is already craftable in IV as is. But the 'Precise Electronic Unit Casing mk 1' casings need a zpm-voltage EBF recipe (2x luv hatches) and Cerium (doable in IV but not everyone does), so early/mid LuV overall.

Keeping the precise mode in LuV means that the nq line stays where it is.

### Your Vision

This is part of the efforts to remove the PA in a smooth way.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by querns** [comment]
I took a look at the precise assembler code with this ticket in mind. What I found is that the code is pretty reliant on the existing block metadata values of 0/1/2 on casings to drive its logic. Adding a fourth casing tier would mean a lot of exception cases.

I thought of an alternate solution: make an "Imprecise Assembler", that extends the precise assembler and overrides the structure and logic a bit. Doing it like this would also allow us to down tier it more -- e.g., there could be tier 1 imprecise casings at EV that let you do 16 parallels, and tier 2 imprecise casings at IV for 24 parallels. 

Here's the options as I see it.
* Add a T0 casing as metadata 3, and code in a bunch of exception cases in the precise assembler to support them.
* Add a T0 casing as metadata 0, and write a messy conversion script to convert any existing precise assemblers in-world to the new metadata values.
* Add a separate imprecise assembler as described above.

Any thoughts?
