### ISSUE TITLE
Compressed Chest will not autofill Recipes in Tinker's Crafting station

### ISSUE THREAD

**Issue by skinke17** [GTNewHorizons/GT-New-Horizons-Modpack#14454]
### Your GTNH Discord Username

sJ (canyoushootme)

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

The crafting station from Tinkers doesn't work with a compressed chest and you can't shift-click the stuff from the chest into the crafting station.

I see that it has been an issue before but it was fixed as well, so maybe something broke in the 2.4.0 update? 

Here is the link to the issue from march this year https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13034

### The Reality

The items doesn't go into the crafting station so you can't craft anything.

### Your Proposal

If possible, make it work again or if it can't be added, then i understand.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Don't make duplicated ticket if you know there's already one
