### ISSUE TITLE
Search in Nearby Inventories not closing Inventory if searched item is in said inventory.

### ISSUE THREAD

**Issue by IntoxicatedPlatypus** [GTNewHorizons/GT-New-Horizons-Modpack#14451]
### Your GTNH Discord Username

cyanplatypus

### Your Pack Version

2.4

### Your Proposal

f.e. If an item being searched is in a chest that I am currently viewing, search function shouldn't close the UI, but instead only highlight the item in the current chest (maybe keeping the particles if I also wanted to look elsewhere)

### Your Goal

QoL

### Your Vision

QoL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by desagas** [comment]
I love this idea. Simply updating the GUI if in said chest would be awesome, rather than closing it.
