### ISSUE TITLE
Please change the color of industrial wiremill

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/GT-New-Horizons-Modpack#14457]
### Your Pack Version

2.3.6

### Your Proposal

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/51e6d7dd-4cbe-4db3-97d6-ba3cd3720b85)
Like the picture shows, it could make player confused of what they did wrong when wiremill didn't form, until he discovered he mistaked the Chemically Inert Machine Casing as Wire Mill Block.
Please change the color of industrial wiremill to make it easy to distinguish.

### Your Goal

change the color of wiremill

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by joshaup1999** [comment]
Fairly sure the wiremill casings is a light grey and look completely different to inert casings

**Comment by querns** [comment]
> Fairly sure the wiremill casings is a light grey and look completely different to inert casings

Hasn't been that way for a while now.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/33518699/c50930bd-1b75-4b00-8b49-abe6ad79d6e6)

**Comment by desagas** [comment]
All the controllers blend in, I like this feature. That is why WAILA is a thing.

**Comment by koiNoCirculation** [comment]
> Fairly sure the wiremill casings is a light grey and look completely different to inert casings

The block I am looking at is Chemical inert, others are wire mill casings. SO YOU THINK THERY ARE COMPLETELY DIFFERENT?
This case is tested with default texture.

**Comment by joshaup1999** [comment]
Chill out yea… they were light grey until recently. I was wrong and other corrected me. No need to be an ass

**Comment by koiNoCirculation** [comment]
> All the controllers blend in, I like this feature. That is why WAILA is a thing.

It's on the top side, so it was not spotted until I checked every block with waila. It's hard to discover without checking.
