### ISSUE TITLE
YOTTanks voiding 2.4.0

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#14455]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

You have a yottank store fluids in them and they stay in it

### The Reality

I got my YOTTanks attached with a yothatch to my fluid-subnet controller
Everything worked fine until I switched from 2.3.5 to 2.4.0
Now I save some hypogen and if I quit the game and start on the next day it's from let's say 23M down to 14M again
Third time in a row that happens

### Your Proposal

It shouldn't happen, like that's a big thing!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
This is in SP and only happens when you exit and load back in right?
If so, can you try moving the offending tank a couple chunks away and check if it still occurs?

**Comment by MaGeBZz** [comment]
@Lyfts yeah it's in SP and happen when I quit and load again
Not even anytime I guess but often enough to be enough especially for spacetime rn before eternal coils

What do you mean with couple chunks away? Like away from what? I have a pretty big base I would say and don't know where I should keep it tbh
Would start using fluid digital singularities but they are too expensive rn before t3 QFT so yeah

And even if that would work it won't solve the problem technical-wise

**Comment by MaGeBZz** [comment]
Sorry, accidently closed it lol

**Comment by Lyfts** [comment]
Is it just 1 tank voiding or all of your yottanks?

**Comment by MaGeBZz** [comment]
@Lyfts two that I recognized but can't really tell cause I don't write down the numbers
For now it only was hypogen and spacetime what I've noticed but that are the worst tanks to void like at all rn

**Comment by MaGeBZz** [comment]
@Lyfts I saw that it voided many things from chromatic glass too, probably all yottanks have that problem

**Comment by SMSum** [comment]
I've had a similar problem since switching to 2.4.0 as well, YOTTank ME hatches randomly disconnect from network and never reconnect or completely void fluids. There are multiple people in the discord who have brought it up, only now finding this issue report. There is no rhyme or reason to it as far as I could tell in my earlier testing, it just sorta happens.
