### ISSUE TITLE
Ender IO? Travel Anchor, Staff of Traveling, The Ender (With Travel) don't working. 

### ISSUE THREAD

**Issue by GreedReaper117** [GTNewHorizons/GT-New-Horizons-Modpack#14456]
### Your GTNH Discord Username

peter117#9393

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

I wanted to move around the base to Travel Anchora or through the wall. 
But there is no way to move to higher floors, you can only teleport down. It doesn't matter if it's through the wall or into the Travel Anchor. 

Me was restarted the game, tested on another world and nothing changed.

### The Reality

Moving with the items "Travel Anchor, Staff of Traveling, The Ender (With Travel)" does not work up, only one floor below.
And to the lower set Travel Anchors

### Your Proposal

Verry please check this and help. Because it's not cool that you can't move around the base well

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Please clarify your distance to the anchor, the mean you triggered travel (that whether you used an item, or you were standing above an anchor, or both) and whether you tweaked EIO config on the anchor distance. I cannot replicate the case in dev even when I moved very far away from the anchor, probably just when the icon of anchor is about to disappear

**Comment by Glease** [comment]
Please try with this build: http://jenkins.usrv.eu:8080/job/Ender-IO/249/artifact/build/libs/EnderIO-2.4.24-fix-travel.2+0a92304ed5.jar

It won't fix your problem, as it is virtually the same as the one come with 2.4.0. However, this one will give a bit more logging when the travel breaks, so it will make us easier to locate the true cause of the problems.
