### ISSUE TITLE
Nutrition 

### ISSUE THREAD

**Issue by MLellmann** [GTNewHorizons/GT-New-Horizons-Modpack#14459]
### Your GTNH Discord Username

Tywien

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

When eating good foods (like Delighted Meals) i expect the Nutrition values to go up

### The Reality

Eating good food (in my case 4 Delighted Meals and nothing else) i expected to gain around 12% in each of the Nutrition Scores. The reality is, that i lost 1% in each one.

### Your Proposal

That you actually gain Nutrition with good Foods.

It works for bad foods with low food values, but for all the good foods, you gain barely anything, or even loose as in the case of Delighted Meal.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DarkAmbientNoise** [comment]
I can verify this as an issue (GTNH 2.4.0, Java 17, SP, running Optifine). Just as well it seems the nutritional value listed, is divided evenly across the categories listed (Hearty Breakfast 4.1 pts, but gives 1 pt for the 4 categories), or has a 0.5 multiplier (config says 1.0) for Epic Bacon (8 pts Protein, but only gives out 4 pts). I can get a category (fruit is the easiest) to give out buffs, but getting any other category to that point is either broken, or requires a very, very specific "optimal" food set to even have a chance to get to it. High quality foods, almost do more harm than good. While stuff below 3, maybe 4 food notches can give small gains, but the decay modifier (1.0 in config) makes high quality foods near worthless, at least for the effects as a Delighted Meal practically keeps all values stuck at a near neutral change.

I'm assuming this mostly helps players early game, so I'm assuming this is broken.  Thought the extra info might help.

**Comment by ProTriforcer** [comment]
I'm having this issue too in singleplayer on 2.6.0.-nightly-324, 2.5.1 and 2.3.7 on java Semeru 8 and Eclipse Adoptium 17 and 20 (not respectively). Tried clean installs too. 
I lose 0.2% of each nutrient per hunger point restored when i eat, and the numbers MLellmann and ShyZShark got are consistent with it. It appears to be caused by this: https://github.com/GTNewHorizons/Nutrition/pull/5
If i got it right, it's not supposed to fire when you actually eat, but it does. The only way i could make it work properly was to downgrade to nutrition 0.0.1, a version before that pull request was merged.

**Comment by AlpacaStorm** [comment]
same issue on 2.5.1 on java8,20,21
