### ISSUE TITLE
Tinkers Defense Tool Station Texture Missing

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/GT-New-Horizons-Modpack#14467]
### Your GTNH Discord Username

brandyyn

### Your Pack Version

tinkersdefense-1.3.7 and TConstruct-1.7.10-1.9.1-GTNH

### Your Server

Private modpack

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

normal tinkers construct with normal tinkers defense
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11356565/1bdc6c61-0093-4af5-8177-a5eec701f956)

### The Reality

and then this is using GTNH tinkers with normal tinkers defense, i dont have GTNH tinkers defense but nothing in the commits alludes to a fix for this 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11356565/74183574-fe5d-495f-bddb-bfd2a6c1923d)

### Your Proposal

since it's normal with normal tconstruct, your guys fork breaks this, i'm using a slightly older version of tconstruct because I don't like the later changes of the mod- can it be fixed in the tinkers defense fork?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@brandyyn we use tinkers defence 1.2.1. Other versions are not supported so far but feel free to fix all the issues and i am willing to update.

**Comment by mitchej123** [comment]
When using our forks, you'll need to use other closely related forks as well.  Just like NEI doesn't work with stock CCC/CCL, tinkers-NH likely won't work with any non NH tinkers addons.

If someone wants to look into it in fix it, but no plans here.
