### ISSUE TITLE
Minor new feature: fullers earth to bleach coloured blocks in the very early game

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#14465]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.4.0

### Your Proposal

The feature is fairly simple: for all dyeable blocks and items (e.g. wool, stained clay, Extra Utilities colored blocks), I would like recipes to be added which craft one dyed item with one **fullers earth dust** to return the undyed (usually the white-coloured) version of the item. This would specifically affect the early game, prior to the low voltage tier where chlorine bleaching serves the same purpose.

### Your Goal

While white dye, which normally can serve this purpose anyway, is usually fairly easy to come by, this change would have a distinct benefit: it would give a use to fullers earth prior to the ability to electrolyze it into component elements at the MV tier.

Additionally, there is the minor advantage that players who wish to do a lot of decorative building in the early game would gain a non-bone method of bleaching their building materials, but the main benefit is that fullers earth would gain a function at the time it is generally first acquired.

### Your Vision

Fullers Earth is notable as an ore material which is pretty much impossible to _avoid_ collecting, due to its presence in the only ore vein source of the gypsum needed for the bricked blast furnace. The vast majority of players will excavate a lot of gypsum from this ore vein, and so will tend to accumulate at least a few stacks of fullers earth in the steam age. There is even a requirement to collect some fullers earth ore blocks as part of the "Gypsum" quest which points players in the direction of the vein.

Currently, this ore is almost certainly obtained by all players very early in the game, and yet it does little other than clog storage chests until players acquire their first MV electrolyzer many hours, days, and even weeks after they first gather some. I am proposing this change so that fullers earth can be of some use _at the time it is first obtained_.

This feature also has the secondary justification of realism (or, more accurately, being inspired by reality): a major real-world use of fullers earth is as a bleaching and cleaning agent. This fact has no real impact on gameplay, it is simply worth mentioning as the information which inspired this idea.

[If others agree that this minor feature is a worthwhile addition, I am happy to take the time to create the relevant recipes if I can be shown an example of how to code them efficiently.]

### Edits:
- Corrected spelling of fullers earth to reflect in-game convention rather than real-world convention.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Cool idea. Not just because giving a generic electrolyzable material a nice use makes the pack feel more thought through, but also because there is no reason for bleaching to be gated by chembath either imo, considering that it mostly is for decorative use. Not sure how you would implement this many recipes in a reasonable way though.

**Comment by vovaksenov** [comment]
Should not be closed. This is a rather good idea.

**Comment by hallucinogender** [comment]
If no one else is going to add this feature, the issue can probably be closed for now, and I'll return to the idea when I'm in a situation where I'm able to work on it.

**Comment by Dream-Master** [comment]
No the idea is good but I hadn’t the time to add it right now.
