### ISSUE TITLE
GT++ Vibrant Alloy Plate invalid for Ender Fluid Conduit

### ISSUE THREAD

**Issue by christoffaloffagus** [GTNewHorizons/GT-New-Horizons-Modpack#14468]
### Your GTNH Discord Username

christoffaloffagus

### Your Pack Version

2.4

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

Recipe: Ender Fluid Conduit
Ingredients:
- Tiny PTFE Fluid Pipe (Gregtech)
- Vibrant Alloy Plate (GT++) (from fluid solidifier)
- Molten Polyethylene

### The Reality

Recipe does not produce Ender Fluid Conduit. 

I can confirm that the exact same items when I swap the fluid solidified plates with ones from the bender (Gregtech) does indeed produce the conduits. The issue is that fluid solidified (GT++) plates are not working, despite being listed in the recipe.

### Your Proposal

Either remove the recipe that shows GT++ plates as valid or make it so that they produce the conduits.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
GT++ variant of Vibrant Alloy is now removed by https://github.com/GTNewHorizons/GTplusplus/pull/729
