### ISSUE TITLE
Wireless Crafting Terminal Keybind automatically unbinds

### ISSUE THREAD

**Issue by Ilithios06** [GTNewHorizons/GT-New-Horizons-Modpack#14463]
### Your GTNH Discord Username

ilith (legacy: Ilith#7274)

### Your Pack Version

2.4.0

### Your Server

Private server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

I would expect a keybind not to automatically unbind every time the minecraft instance is restarted
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86689318/5dbac5d0-f58c-4252-b6f3-3a9f5039eaf1)

### The Reality

The "Open Wireless Crafting Terminal" (Wireless Crafting Terminal) Keybind is unbound every time the minecraft instance is restarted
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86689318/fedd5689-5d99-4184-8431-129969602539)

### Your Proposal

pls fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment]
Note: This is about the legacy terminal from AE2 Wireless Crafting Terminal. Maybe instead of fixing this we should port all missing features to the AE2FC terminal and deprecate this. To my knowledge this terminal is quite network intensive compared to AE2FC one.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/WirelessCraftingTerminal/pull/31 / https://github.com/GTNewHorizons/WirelessCraftingTerminal/commit/075d77b14ec299a1518c7a7dcac64be85ccadc4e
