### ISSUE TITLE
Let ME output bus/hatch accept cable connection from back side

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#14462]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.3.7

### Your Proposal

Let accept cable/ME connection from back side too

### Your Goal

Use ME outputs in Quad wall shared multi
<img width="474" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/04e51ea2-59c8-44e7-aaaf-3869ee5e9257">

### Your Vision

Mb add mode that toggle with screwdriver 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AtomicGrog** [comment]
Please be considerate when working throigh this. I presently use the ME Output Bus for advanced assembly lines which are adjacent to Stocking Input BUS's. Only the fact that theu don't accept AE from anything other than the front face allows this to work.

**Comment by ALongStringOfNumbers** [comment]
> Please be considerate when working throigh this. I presently use the ME Output Bus for advanced assembly lines which are adjacent to Stocking Input BUS's. Only the fact that they don't accept AE from anything other than the front face allows this to work.

It could be a nice addition then, to allow shutter covers to block the connection between AE cable and the ME buses. If they cannot already. This would be beneficial for solving the issue that you have brought up
