### ISSUE TITLE
modtweaker, extendedsupport and amtweaker dont work with crafttweaker, only minetweaker

### ISSUE THREAD

**Issue by brandyyn** [GTNewHorizons/GT-New-Horizons-Modpack#14469]
### Your GTNH Discord Username

brandyyn

### Your Pack Version

CraftTweaker-3.2.13.jar - ModTweaker2-0.9.10.jar - extendedsupport-1.1.0.jar - AMTweaker-1.7.10-1.0.jar

### Your Server

Private modpack

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

switch from minetweaker to crafttweaker seamlessly 

### The Reality

game crashes on world load 
[crash-2023-09-08_06.53.31-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12556007/crash-2023-09-08_06.53.31-client.txt)

### Your Proposal

add support for these 3 minetweaker addons?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by brandyyn** [comment]
not planned now, could be in the future? :( @mitchej123

**Comment by mitchej123** [comment]
This is for modpack issues.  Also these mods are not supported

**Comment by brandyyn** [comment]
fixed by only having 1 folder in the scripts folder
https://www.reddit.com/r/feedthebeast/comments/84p8at/comment/dvrfsxv/?utm_source=share&utm_medium=web2x&context=3
