### ISSUE TITLE
Spice of Life food mouseover crashing to main screen

### ISSUE THREAD

**Issue by MakerOfDopamine** [GTNewHorizons/GT-New-Horizons-Modpack#14471]
### Your GTNH Discord Username

psi(e_W+1)#1225

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Log into game
Hovering over any food items.

Not sure if this is an os-specific / platform-specific problem.
Mac OS X, Monterey, ARM M1 Chip

### Crash Report

[crash-2023-09-09_00.03.50-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12561779/crash-2023-09-09_00.03.50-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by MakerOfDopamine** [comment]
Maybe not the best title but whatever

**Comment by Jonas-Seiler** [comment]
This happens for me too.

Pack version 2.4.0
Java 17 (OpenJDK 17.0.7 64-bit)

Occurs upon hovering over any food item in own or external inventory:
https://mclo.gs/wfqNYG3
https://mclo.gs/x1yIlVD

Also occurs when selecting food item in hot bar:
https://mclo.gs/udLCUgm

Moreover, seems to also sometimes happen with no obvious relation to food items:
https://mclo.gs/wXEVAV8

Seems to only happen on one specific world. Other/new worlds seem to be unaffected

Let me know if y'all need me to test anything else.

**Comment by BorisIgnatov** [comment]
Same here

**Comment by Mugboy97** [comment]
Had this issue aswell. Reinstalling the pack seemed to fix it.

**Comment by bombcar** [comment]
IIRC there were some null checks added after 2.5.1, if someone can reproduce it and try a nightly, it might be nice, but it sounds like it's already a Heisenbug 

See https://github.com/GTNewHorizons/SpiceOfLife/pull/36

**Comment by chochem** [comment]
see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12696 for an older ticket an attempted (but failed) fix.
also see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14709 for some more similar reports

**Comment by boubou19** [comment]
This seem to be heavily related on corruption during pack download/install. Got it to happen to me once, a pack reinstallation indeed fixed the issue. Looks like it's a generic error caused by something being improperly downloaded.
