### ISSUE TITLE
Game freezes on loading sound engine

### ISSUE THREAD

**Issue by LionEl-johnson14** [GTNewHorizons/GT-New-Horizons-Modpack#14470]
### Your GTNH Discord Username

lion_eljonson14

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Actions

I recently installed the mod and have not been able to launch the game past the loading screen because every time it runs, the engine always freezes at "Sound Engine Started"
Here's a screenshot of the last messages:
![Capture](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/64676704/c2b69654-9296-4ed3-8c8d-7bb9d7e6f6c6)
I've tried everything from different Java editions to reinstalling the modpack, but it always gets frozen at that one step.

### Crash Report

[error.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12560748/error.txt)
no crash report generated, here's a copy of the console.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
check your java arg. it says `java.bacojase/java.lang=ALL-UNNAMED` which is not correct. Try copy clean from https://github.com/GTNewHorizons/lwjgl3ify#client
