### ISSUE TITLE
Recipe Conflict: Lemon Juice / Biomass with Pam's Harvestcraft Lemon

### ISSUE THREAD

**Issue by Graymare** [GTNewHorizons/GT-New-Horizons-Modpack#14476]
### Your GTNH Discord Username

embri_

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

NEI shows all three variants of lemon (GT, Forestry, Pam's) as being usable for creating Lemon Juice in the Brewery:
<img width="531" alt="Screenshot 2023-09-08 at 8 31 01 PM" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/121984725/d3a80bab-1456-48ff-a170-6a33f2dd3c88">
<img width="514" alt="Screenshot 2023-09-08 at 8 34 54 PM" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/121984725/b2256fba-948c-40bc-8acb-de54523c9f91">

### The Reality

Attempting to make Lemon Juice with Pam's Harvestcraft Lemons & Water yields biomass instead.  The other two variants of lemon make lemon juice as expected.

### Your Proposal

Either don't show Pam's Harvestcraft lemons as usable for lemon juice (and maybe provide a conversion craft recipe to get one of the other two) or resolve the recipe conflict.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
PHC Lemon and water is the recipe for biomass, if you look at the ingredients ... lemon and DISTILLED water is the recipe for lemon juice. Did you try distilled water? Even in the photos you showed, it is very visibly distilled water. Does it work when you use that recipe?

**Comment by Graymare** [comment]
Lemon (GregTech) works with regular water just like Lemon (Forestry) in 2.3.0; I guess it's just strange that the Pam's lemon is the only one that _doesn't_ work and requires Distilled.  Probably not a bug then, though.  It must have gotten flipped in 2.4.  I'll close this.
