### ISSUE TITLE
Bruised Tea Leaf recipe missing

### ISSUE THREAD

**Issue by ODevil97** [GTNewHorizons/GT-New-Horizons-Modpack#14474]
### Your GTNH Discord Username

odevil

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Trying to craft a Bruised Tea Leaf (for Oolong Tea) from KubaTech by putting a Dehydrated Tea Leaf into a cutting machine (as was the recipe in 2.3.0).

### The Reality

Recipe no longer works.

### Your Proposal

Fix Recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
Fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2271
