### ISSUE TITLE
Allow Large Fluid Cells to open inventories and machines when in hand.

### ISSUE THREAD

**Issue by Graymare** [GTNewHorizons/GT-New-Horizons-Modpack#14475]
### Your GTNH Discord Username

embri_

### Your Pack Version

2.3.0

### Your Proposal

Have inventory and machine GUI interactions take priority to the "you can't use this right now" message.  I'm not asking for Large Fluid Cells to work as buckets, just for the ability to interact with storage and other containers while holding one as normal.   Right now when you attempt to click on a chest, machine or most other blocks while holding a Large Fluid Cell, all that happens is a purple text message.  

### Your Goal

Getting a random chat message that "this item can't be used right now" when not even attempting to use it is frustrating, so is always having to switch to a different item or tool just to open a machine and drop in a fluid from a Large Fluid Cell.

### Your Vision

This would improve the end user experience because it aligns with how most people expect storage and machines to work - if it can't be used by clicking or right-clicking on the block, then the GUI should open.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LazyFleshWasTaken** [comment]
Being able to use them to turn p2p's to fluid would also be nice.

**Comment by bombcar** [comment]
So either the super tank can dupe, or the large steel cell booming isn't needed anymore .....

Because I can use a supertank as a 4,000 bucket cell (try it) and if I right-click a machine with it, it opens the GUI.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/533931/c7bd3fc4-1b15-45c3-9121-b6e89bfb6ace)

**Comment by bombcar** [comment]
btw this means don't right click on your max size steam tank with a supertank 😢

**Comment by Graymare** [comment]
> So either the super tank can dupe, or the large steel cell booming isn't needed anymore .....

Is that why large fluid cells were set to non-intractable on machines, they were causing a duplication bug?

**Comment by bombcar** [comment]
> > So either the super tank can dupe, or the large steel cell booming isn't needed anymore .....
> 
> Is that why large fluid cells were set to non-intractable on machines, they were causing a duplication bug?

Yes there were many dupe bugs (or loss of container bugs) and many have been fixed. But the thunder rolls ….
