### ISSUE TITLE
Lanthanides Line need rework

### ISSUE THREAD

**Issue by Nxer** [GTNewHorizons/GT-New-Horizons-Modpack#14486]
### Your GTNH Discord Username

Nxer#6847

### Your Pack Version

2.4.0

### Make all Lanthanides processing line start at the ore , not start at the Monazite . 
For example , Samarium ore ,  dust SamariumOreConcentrate has its own processing line and the processing line do not need anything about Monazite to increase production . The Sm line itself has the most complete production . Monazite line can produce lanthanides, but lanthanide lines do not have to require monazite .

### Your Goal

* Lanthanides proccessing line is Lanthanides proccessing line . Monazite is just Monazite . Monazite is not all of the Lanthanides .
* Now Monazite line has a terrible number balance , and most output are useless . Increase output , decrease power requirement and time .
* The main part of Lanthanides line should be these Lanthanides ores , not Monazite . In real life these Lanthanides may just be produced in Monazite or some other processing , but in game we have The most enriched single ore . These most enriched single ores should not be the adjunct of Monazite processing line . 

### Your Vision

* The Lanthanides material can be produced smoothly when it is needed in tier .
* The Lanthanides line's product can be locked by Rocket Tier . Convenient to control the stage .
* Players don't feel particularly powerless in LuV - UV .

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by ChemEng227** [comment]
Throw monazite into IsaMill!

**Comment by JodieRuth** [comment]
Most of the steps are also of unclear significance. The repetition of meaningless steps makes the lanthanides even more distasteful

**Comment by Nxer** [comment]
These lanthanide ores should be more than just additives .

**Comment by joshaup1999** [comment]
> Throw monazite into IsaMill!

How about hell no. That multi should die along with the concept of milling
