### ISSUE TITLE
Mod suggestion: Multithreadingandtweaks

### ISSUE THREAD

**Issue by ChromaPIE** [GTNewHorizons/GT-New-Horizons-Modpack#14480]
### Your Pack Version

2.4.0

### Mod Name

Multithreadingandtweaks

### The Mod to Add

```
This mod add multithreading for some features in 1.7.10. that can improve tps and fps in some situations.
This mod add some tweaks in the config file to fix bugs.
This mod is in early stages, so he can have somes bugs and unexpected behavior.
this mod isn't a solution to fix magically all tps issues.
```
 from the CurseForge page of the mod.

### Your Reason

I do added some other optimizing mods, either suggested on https://gtnh.miraheze.org/wiki/Additional_Mods or from browsing curseforge/modrinth, they didn't make much change to the framerate.

Stage 0, basically in the wild, just some chests as tile-entities around so the game may not perform this well when you got yourself among a bunch of humongous machines. My setup was considered mid even 4 yrs ago, so if yours is better, the performance may be better too, unlike the vanilla game where the set up won't matter much.

Before: framerate at about 50 when standing still, frequent drop spikes to 30-40 when moving around. With OptiFine shaderpack on, under 20, miserable gameplay.

After: around 160 when standing still, got a steady 100, extremely rare spikes to no less than 60 (you know this happens to all versions). With Complementary Shaders on, 40-50, totally playable bc it's relatively steady.

It's said to be _in early stages_, but hey, I got into the game hanging around a bit without a crash, that's not bad already.

It don't have to be in the pack, but you sure will want to add it to the Additional Mods list. (but have a try first, bc I can't give it a further and precise test.)

### Preliminary Investigation

Yes I tried.
What happened: Goosebumps all over when I saw the tremendously boosted and steadied framerate.
Nothing needs to be tweaked maybe?

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by boubou19** [comment]
All the game and many modded stuff has been written around the fact that the game is singlethreaded. At worse some stuff may require additional support. At best the rest doesn't make usage of the multithreading. Anyways, this is considered highly experimental, so we will not recommand such a mod.

**Comment by Connor-Colenso** [comment]
This is definitely interesting, I just tried the mod on ETA in an endgame base and am now getting a solid 144 FPS with it. That combined with LGPL is worth looking into more.

**Comment by ChromaPIE** [comment]
above was the result with version 0.8.7.4.4 of this mod, we got 3 updates from em in one day today, but im experiencing performance drop with the latest version, yall might want to wait till the release of a relatively more stable version, that wont be long tho according to its highly active maintenance.

**Comment by Pxx500** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/6d059066-afe7-44d5-85fa-5ced63077608)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/7f9ca26b-c66a-4c3c-a133-c78e306740f6)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/c627a330-19fa-41e4-9455-11680b006ba1)

I performed some testing and didn't notice any noticeable changes, I can only assume that effects depend on the hardware

**Comment by ChromaPIE** [comment]
i got i7-9750H with 6 cores and 12 threads btw, and apparently the mod made some pretty decent use of them

**Comment by Pxx500** [comment]
> i got i7-9750H with 6 cores and 12 threads btw, and apparently the mod made some pretty decent use of them

My tests were on Ryzen 7 5800H (8c, 16thr)

**Comment by ChromaPIE** [comment]
> My tests were on Ryzen 7 5800H (8c, 16thr)
could be that its powerful enough to carry singlethread tasks

**Comment by ChromaPIE** [comment]
@Pxx500 I don't know if ur using nvidia graphic card but i did a couple of tests recently bc i cant remember what change did i make that caused the framerate to drop below 60 the day after i found this mod useful. If you actually got a nvidia card, go to the nvidia control panel, set Threaded Optimization to OFF for the javaw.exe you run ur minecraft on (it might be useful for other games so i wont recommend setting it globally). from my test the framerate came back to what it was in my very first test with the mod.
