### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Evanev7** [GTNewHorizons/GT-New-Horizons-Modpack#14481]
### Your GTNH Discord Username

caedesyth

### Your Pack Version

2.4.0

### Your Server

private server

### Java Version

Java 20 (GraalVM)

### Type of Server

Vanilla Forge

### Your Actions

Starting up the server, medium sized world, 10GBs out of 24 allocated. Running on an oracle cloud server with ampere architexture, on linux. The server after startup has around 6.5GBs of memory used. After around 15 minutes, seemingly regardless of the number of players (maximum 10, minimum 3 in my exploration), the memory usage spikes up to around 22GBs and tick time goes up to a few thousand ms, the server silently fails with no crash report, simply returning to the console. Can't reproduce with just one player in the world.

### Crash Report

[latest.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12566377/latest.txt)

We also have AIImprovements, AromaCore, AromaBackup, DiscordIntegraiton, FoamFix, FTBLib, FTBUtilities, gtnh-web-map and squidless for optimisations, though removing AIImprovements and FoamFix had no effect.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Hikari1nVoid** [comment]
Try dumping the memory on your server. Expect a large time consider Oracle's outbound traffic is not that fast...

**Comment by Evanev7** [comment]
I have now replicated this with just one player online, it still took around 15 minutes of server uptime, generating a spark heapsummary here:
https://spark.lucko.me/poECuAwHMh
and a spark profile here:
https://spark.lucko.me/4ozCM144sg
but a full heap dump didn't complete before the server died.

**Comment by Evanev7** [comment]
Unable to reproduce on jdk-20 without GraalVM, though performance has suffered as a side effect.
