### ISSUE TITLE
Reenable Thaumic Tinkerer Imbued Fire

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT-New-Horizons-Modpack#14487]
### Your Proposal

Reenable Thaumic Tinkrerer Inbued Fires.  As of TT [2.8.0](https://github.com/GTNewHorizons/ThaumicTinkerer/releases/tag/2.8.0) the fire is no longer a lagfest that destroys worlds and servers and should be safe enough to re-enable.

### Your Goal

Botania Cake Reactor!

<img width="739" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1894689/069c7e3f-408b-4c42-a567-49de8832cc9e">

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [x] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
Yeah go for it, we only disabled it since it was insanely broken (code wise) so if it’s not anymore, (which it isn’t) then it should be re-enabled

**Comment by AbdielKavash** [comment]
How laggy is the setup pictured above? It is not only causing many block updates, but also lighting updates and flowing liquids. My concern is that if such a laggy method of mana generation becomes "meta", some emergency measures will have to be added to make people not break servers with it.

**Comment by chochem** [comment]
> How laggy is the setup pictured above? It is not only causing many block updates, but also lighting updates and flowing liquids. My concern is that if such a laggy method of mana generation becomes "meta", some emergency measures will have to be added to make people not break servers with it.

no noticable impact on my end. but if you have other data let us know.

**Comment by mitchej123** [comment]
The impact should be pretty negligible in a confined space -- in my example it was 7x9, and I can't imagine it being significantly more laggy than any other in world botania mana generation method.
