### ISSUE TITLE
NEI not being able to search items when using the search bar

### ISSUE THREAD

**Issue by ZombieKiller9549** [GTNewHorizons/GT-New-Horizons-Modpack#14498]
### Your GTNH Discord Username

ZombieKiller#5949

### Your Pack Version

2.4.0

### Your Server

N/A - SinglePlayer

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

tried to search in NEI

### The Reality

NEI didn't work. 

### Your Proposal

fix the issue. please? :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ydrec** [comment]
guy used the wrong box to search
