### ISSUE TITLE
Unable to open multiblock GUIs after Multiblock Drill change

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#14496]
### Your GTNH Discord Username

.querns

### Your Pack Version

2.4.0 + GT5U 5.0.9.44.08

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

When attempting to open a multiblock GUI, it won't let you, and the following error is printed in the console.

https://pastebin.com/N8XANUjq

### The Reality

n/a

### Your Proposal

n/a

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by querns** [comment]
Tested with the full pack. Upgrading to ModularUI 1.1.17 fixes the problem.

**Comment by miozune** [comment]
That's why nightly builds are recommended over manual updates...
