### ISSUE TITLE
Viewing the Teleport pad recipe prompts a crash

### ISSUE THREAD

**Issue by Webmage101** [GTNewHorizons/GT-New-Horizons-Modpack#14490]
### Your GTNH Discord Username

Webmage101#4883

### Your Pack Version

2.4.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

Viewed the EnderIO telepad recipe, and mousing over some components caused my game to crash.

### Crash Report

https://mclo.gs/nMEQPkA

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
Can you provide full fml log?
