### ISSUE TITLE
Uranium Hexafluoride imbalance

### ISSUE THREAD

**Issue by mjevans** [GTNewHorizons/GT-New-Horizons-Modpack#14505]
### Your Pack Version

2.4.0

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I'm not sure if they built up while previously running LFTR Fuels 1 and 2, however now the base is running off of LFTR Fuel 3 and reprocessing with LFTR base and Thorium Tetrafluoride.

I've been trying to track down where all the fluorine is going, and finally happened to glance at the EBF that's making LFTR base.

I hadn't thought to check there since the quest book talks about LFTR 3 finally being recyclable.

### The Reality

My team has almost an HV hatch (16 stacks) filled with Uranium Hexafluoride Cells, 886 according to the holo glasses.  There are zero Stable Molten Salt Base Cells.

I can't find any way of correcting this imbalance in NEI.  That's why this is more than a change or feature request, those categories expressly exclude things someone believes they _should_ be able to do (while still being balanced).

Understandably there isn't a shortcut past running the LFTR to make components of the base fuel independently.

### Your Proposal

Some method of taking overflow or leftovers from the LFTR processes out of those loops.

E.G. an Electrolizer recipe that breaks Uranium Hexafluoride down (??? 233U x1 dust + F x6 fluid ???)

For completeness all of the other components might have similar uses in an electrolizer, centrifuge, dehydrator, etc, some machine.

It might also be nice if one or the other of the LFTR fuel base components could be crafted.

The NSP takes Fluorine x3 + (7)LiFBeF2UF4FP (Helium Sparged U Salt) to make UF6F2FP + Impure Molten Salt Base.  This implies that Molten Salt Base is (Lithium 7) (7)LiBeF2 ; Maybe an LCR recipe that takes 1x Beryllium Dust +  1x Lithium 7 Dust and 2000 drops ~ 'mL' ~ 'mB' of Fluorine to yield Impure Molten Salt Base, or something that could be heated or otherwise processed to create it.

This would still leave Uranium Hexafluoride as a component that depends on the LFTR reprocessing steps and thus still gate it behind using Fuel 3.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by fluffle** [comment]
I can confirm I also see this. I've had LFTRs feeding into my power mix since late LuV and over the course of what is probably now 9 months of server uptime i've amassed a 34k bucket backlog of UF6 and trashed god knows how much of the other tetra/hexafluorides after filling a 4k bucket super tank. Some way of extracting useful materials from them would be nice, though I can see how the intent might be that the excess should be voided if it is not desired, as the loop is supposed to be UF6-positive.

**Comment by chehob** [comment]
Questbook is absolutely misleading.
I wanted to try the LFTR power generation, but only got frustrated by finding out that the LFTR 2input Tier 3 fuel recipe is not fully recyclable as the quest states. The recipe for fuel base takes 1000L salt base and after full cycle you get back only 833L of salt base with the only option to refill it is by running the 4input fuel recipe.
I guess the balance was normal some time before when the 2input recipe was 10k output, but then it got rebalanced or something.
Either fix the quest or the recipe to match the expectations of this power generation line.

**Comment by fluffle** [comment]
I don't think that's correct, at least here on 2.4.0 I see:

900 LFTR fuel base -> 1000 fuel 3
1000 fuel 3 -> 1000 U salt
1000 U salt -> 1000 He sparged U salt
1000 He U salt -> 2000 Impure salt base
2000 impure base -> 500 stable salt base
500 stable salt base -> 1500 LFTR fuel base

So you get roughly 1.67x LFTR fuel base after one trip around the loop.

**Comment by chehob** [comment]
Yes, you are right, somehow my calculation was wrong
