### ISSUE TITLE
Oh no! DEV's recipe is no longer respected and used! We need more restrictions!

### ISSUE THREAD

**Issue by kierkking** [GTNewHorizons/GT-New-Horizons-Modpack#14507]
### Your Pack Version

2.4

### Your Proposal

This is a destructive cheat mod added by many players     】  Here are some anti-cheat precedents and mods
这是很多玩家添加的破坏性作弊mod                                   】     这是一些反作弊先例和mod
1.https://github.com/RealSilverMoon/BoxPlusPlus              】   1.https://www.curseforge.com/minecraft/mc-mods/enigtech2-util
2.https://github.com/Taskeren/gtnh-no-nerf                       】    2. https://www.mcmod.cn/class/6578.html
3.https://github.com/BucketOfCompasses/Torcherino         】    3.https://www.curseforge.com/minecraft/mc-mods/bat-happy-mod
4.https://github.com/mekanism/Mekanism                         】
5.https://www.mcmod.cn/class/589.html                             】
Here are some examples of modifications that disrespect the GTNH modpack
这是一些不尊重GTNH整合包的修改案例
https://www.bilibili.com/video/BV1Zm4y1T7Zm/?spm_id_from=333.788&vd_source=dd176ed060e1600978083f7b3f077134

### Your Goal

 because I found that many people now play the GTNH integration package at will and modify GTNH at will and publish it online, and most of the added mods are mods that destroy the game content. I think this is very bad. This is a blatant provocation to dev luck. Fortunately, I have worked hard to modify the recipes and works, and there is already a mandatory genuine setting in the new version. Why not directly force the installation of mods that are not recommended by the integration package? In this case, I recommend the above ideas to complete the anti-cheating process.

因为我发现现在很多人随意玩GTNH这个整合包并且在网上随意修改GTNH并且发布，而且添加的mod大多还是破坏游戏内容的mod，我觉得这样非常不好，这是在公然挑衅dev幸幸苦苦修改的配方和作品，并且在新版本中已经有强制正版的设定，为什么不直接强制不能安装非整合包推荐的mod呢，如此我推荐上面几个思路，用来完成反作弊

### Your Vision

I think players don’t have to update, but DEVs must update the game. Players can complain about the content created by devs, but they can’t stop playing it. Players who don’t respect the authors of the integration package should be excluded to make GTNH even greater!
我认为玩家可以不更新，但是DEV们必须更新游戏，dev做的内容玩家可以喷，但是不能不玩，而且应该排斥那些不尊重整合包作者的玩家，让GTNH更加伟大！

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by KamenriderZO** [comment]
I agree with you

**Comment by AEpoi1** [comment]
make GTNH even greater!

**Comment by JodieRuth** [comment]
![{8FXIIQS1 }HTSTC5KT1FYK](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/c648989c-1187-466a-a95a-a7fe9340de7a)

**Comment by kierkking** [comment]
> 让GTNH更加伟大！

make GTNH even faster!

**Comment by xkball** [comment]
funnnnnnnnnnnnnnnnnnnnnnny
乐

**Comment by boubou19** [comment]
You have to understand that we provide a modpack so players can have fun with it. Now if they feel like they can get fun on GT:NH only with those mods added, well so be it, why would we set up protections against this? As long as it doesn't allow to cheat on regular GT:NH servers, it's your instance, your decisions. We respect this. At no point we take this as a provocation. The only thing we don't want from these players is to report bugs with such custom GT:NH instances. Added mods may break the game in several ways, and we don't want to support those mods.
