### ISSUE TITLE
There is a bug in the LCR recipe！

### ISSUE THREAD

**Issue by DarkLei** [GTNewHorizons/GT-New-Horizons-Modpack#14512]
### Your Pack Version

2.4.0 with gregtech 5.09.44.09

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

normal recipe!

### The Reality

![1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18422805/ccafa75f-b800-4af4-85f3-b1cdaa1a2a29)
Not only is this recipe, but other recipe also have this issue.

### Your Proposal

plz fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
whats the recipe?

**Comment by DarkLei** [comment]
> whats the recipe?

I wanted to build a oil processing production line, but I found a bug. For example, I wanted to use LCR to process sulfic  light fuel to producing light fuel and hydrogen sulfide, but in reality, I produced more hydrogen sulfide cell and empty cell.

**Comment by DarkLei** [comment]
with gregtech 5.09.44.12,this bug still exists.

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/126625dc-9a55-439e-92df-7387432e1200)
looks fine on 2.4.0

**Comment by chochem** [comment]
ah but looks like this in todays nightly
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/756176f9-060c-4ccd-9e4b-3fd2a8d3ddb0)

so you hurt yourself there with the gt updates
