### ISSUE TITLE
Add more modern milkshake flavours/mixins

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#14519]
### Your GTNH Discord Username

lily_blanc

### Your Pack Version

2.4.0RC2

### Your Proposal

add more modern milkshake flavourings such as Peanut butter, Caramel, Coffee, Cherries, and Bacon (fiveguyswhy)

### Your Goal

moar nomnoms and drakn

### Your Vision

To bring a sweet flavoured realism to the pack

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by HFPTetraUro** [comment]
I don't mind implementing this if it's wanted
