### ISSUE TITLE
Missing ExtraCells cells 

### ISSUE THREAD

**Issue by Aivast** [GTNewHorizons/GT-New-Horizons-Modpack#14518]
### Your GTNH Discord Username

aivast

### Your Pack Version

2.2.3 migrating to 2.4.0

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

Nice and smooth migration

### The Reality

After migrating server to newer versions all of EC2 cards disappeared from drives.

### Your Proposal

I have found some Issues related to it, but i'm little confused where to look for whole story or which keywords to use for search.
So please give me a least some links to piled up info related to problem.

It will be very helpfull if you also know how to just fix that without lots of manual labor for players while ALSO having server migrated

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
EC2 is removed in the 2.4.0, so it's not a bug. We deprecated them in 2.3.0. If you have a backup, you can restore it on a 2.3.0 instance, migrate the stuff you have from EC2, then upgrade again on 2.4.0.

**Comment by vovaksenov** [comment]
Yes, i had to restore a backup to convert some cells i had forgotten. Late to do anything with it now that it is released

**Comment by Aivast** [comment]
Got it. Soo.. There is now no easy way to just convert all server's cells (without players doing it one by one)?

Can I just add ExtraCells2 from 2.3.0 in 2.4.0 server and convert them later?

**Comment by boubou19** [comment]
You technically can, as we just removed the mod, so it still should be compatible, but this is now unsupported by the modpack, so please don't report any issue related to EC2 if you add it back to the pack.
