### ISSUE TITLE
Game Crashing on startup following new update

### ISSUE THREAD

**Issue by DYstebo** [GTNewHorizons/GT-New-Horizons-Modpack#14528]
### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

1. Updated from 2.3.0 to 2.4.0 in Curse
2. Click Play in Curse. 
3. Click Play in Minecraft Launcher.
4. Game Crashes with error code 1

Checked logs and the important part is:

[16:22:16] [main/WARN]: =======================================================================================
[16:22:16] [main/WARN]: WARNING / WARNING / WARNING / WARNING / WARNING / WARNING / WARNING / WARNING / WARNING
[16:22:16] [main/WARN]: =======================================================================================
[16:22:16] [main/ERROR]:  - Detected incompatible jars: [mixingasm-v0.2.4.jar]
[16:22:16] [main/ERROR]: The game will almost certainly crash!
[16:22:16] [main/FATAL]: ======================================================================================
[16:22:16] [main/ERROR]: Unable to launch

### Crash Report

[2023-09-15-4.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12623613/2023-09-15-4.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by DYstebo** [comment]
After downgrading back to 2.3.0, I am still receiving the same issue.

**Comment by Lyfts** [comment]
Curse strikes again.
Reinstalling from scratch would probably be best as you have about a gazillion duplicated mods.

**Comment by DYstebo** [comment]
I'm not sure why reinstalling from scratch didn't work the first time I did it before I submitted this, but it seems to be working with 2.3.0 again now.
I will check back in after 2.4.0 reinstalls

**Comment by chochem** [comment]
mixingasm-v0.2.4.jar is not in this version

**Comment by DYstebo** [comment]
> mixingasm-v0.2.4.jar is not in this version

I'm aware. When using the version update in Curse, it wasn't removed from the mod directory. Removing it manually caused an error with files being out of sync

**Comment by chochem** [comment]
curse install is tricky, but curse updating is hopeless I guess. recommended launchers are multimc/prism with technic and ATL also having some place (as long as you dont use forge within them).
see https://gtnh.miraheze.org/wiki/Installing_and_Migrating

**Comment by DYstebo** [comment]
Downloading 2.4.0 from scratch doesn't fix the issue unfortunately. There must be something wrong with the way Curse is deploying the whole version

**Comment by DYstebo** [comment]
I just tried it again and now it worked downloading from scratch. However now all my multiblocks are making a consistent deep noise regardless if they're on or off after the save migration.
