### ISSUE TITLE
Improve cost of Quantum goggles of revealing

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#14520]
### Your GTNH Discord Username

Lily_blanc

### Your Pack Version

2.4.0

### Your Proposal

Quantum goggles should have an alt recipe which uses some form of "quantum goggle catalyst" made with all the parts between nanosuit helmet and quantumsuit helmet.
eg, a scuba helmet, 5 iridium alloy item casings, 8 reinforced glass lens', and then the final recipe to turn quantum parts into quantum helmet
this quantum goggle part would ofc not be wearable/usable in any way other than to upgrade nano goggles to quantum goggles

### Your Goal

Currently Quantom Goggles require you to craft multiple sets of NanoSuit Helmets due to the Nano goggles requiring one and the quantum goggles also requiring one, this is dumb

### Your Vision

QoL/streamlining of upgrading goggles for someone who thaums 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/38961580/7a5b8b44-ca25-4bd9-a977-079eb89faa0d)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
really not a big deal to make quantum goggles with the current recipes (source: have recently crafted quantum goggles)
