### ISSUE TITLE
Stop enderman breaking TF portal

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#14525]
### Your GTNH Discord Username

lily_blanc

### Your Pack Version

2.4.0

### Your Proposal

stop enderman from being able to break the portal to the twilight forest (maybe even a config for stopping their shenanigans outright :eyes:)

### Your Goal

enderman breaking TF portals may be rare, but I've had it happen atleast once and don't want it to happen again, without adding extra mods or changing gamerules that affect more than just enderman :pensive: 

### Your Vision

QoL fookin endeeeerman

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
you always have a way to get back with the quest.
