### ISSUE TITLE
A bunch of multiblock centrifuge recipes have their outputs reversed on latest nightly

### ISSUE THREAD

**Issue by TorvikW** [GTNewHorizons/GT-New-Horizons-Modpack#14536]
### Your GTNH Discord Username

Torvik

### Your Pack Version

Nightly 135

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Centrifuging a bunch of impure tantalite dust in the multiblock centrifuge will give me tantalite dust with a bit of manganese.

### The Reality

I instead got a bunch of manganese and a bit of tantalite dust. Some other recipes also have the outputs wrong in the multiblock centrifuge, like purified meteoric iron dust. The regular gregtech centrifuge's recipes are correct and work as intended as far as I can tell.

### Your Proposal

Fix the incorrect multiblock centrifuge outputs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TorvikW** [comment]
![2023-09-17_12 34 41](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11652949/c64ddc0e-50dd-4cfc-971e-b75cd0f14b30)

**Comment by chochem** [comment]
@Kyium might this be caused by the deduplication code you added? maybe it can mix the order without keeping track of chances. After all you probably check for duplicates independent of order.

dont have any other obvious idea.

**Comment by Kyium** [comment]
Yeah I can take a good guess at what causes that. Will fix

**Comment by Kyium** [comment]
> @Kyium might this be caused by the deduplication code you added? maybe it can mix the order without keeping track of chances. After all you probably check for duplicates independent of order.
> 
> dont have any other obvious idea.

just pushed a pr that should fix this. ty for ping
