### ISSUE TITLE
Mega Vac Freezer using full 2A of a single 1A energy hatch

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/GT-New-Horizons-Modpack#14534]
### Your GTNH Discord Username

ipielover

### Your Pack Version

2.4.0.0

### Your Server

Delta

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

Mega Vac Freezer should only use a single A of power when only given a single 1A energy hatch.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/c3174371-c517-454f-8c8b-847c53ca44c9)
It is using both A of power from a single energy hatch when supplied 2A of power
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/8d0ee5b3-b466-4063-b257-f4396c931c89)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/743f5511-4bd8-4377-b085-e1ab37d5182c)
If only a single A is supplied, the machine would shut off due to not enough power

### Your Proposal

Please fix the Mega Vac Freezer to only pull 1A when using a 1A energy hatch

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AtomicGrog** [comment]
Am intrigued, what was you cooling at the time?

**Comment by fluffle** [comment]
I vaguely recall running into this a while ago when I was in ~LuV and "fixing" it by always using 2 EHs of the previous tier so it pulls 4A max but you're expecting it to. You kinda need to do this anyway a lot of the time for cooling the next tier's superconductor base ingots.

**Comment by fluffle** [comment]
All BW multis declare they have 1A of whatever the max input voltage is available for processing:

https://github.com/GTNewHorizons/bartworks/blob/bf6cbcd41c2cf7825552d9fc6dda7dca9ca2e9e2/src/main/java/com/github/bartimaeusnek/bartworks/common/tileentities/multis/mega/GT_TileEntity_MegaMultiBlockBase.java#L173

This overrides the standard logic here:

https://github.com/GTNewHorizons/GT5-Unofficial/blob/050553dc3262e15e8e016ce19419bd7e428d9f67/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_ExtendedPowerMultiBlockBase.java#L134

getMaxInputEu ends up multiplying the voltage and amperage of all input EHs:

https://github.com/GTNewHorizons/GT5-Unofficial/blob/050553dc3262e15e8e016ce19419bd7e428d9f67/src/main/java/gregtech/api/util/GT_ExoticEnergyInputHelper.java#L64

I would recommend removing the processing logic power override in the bartworks code...

**Comment by fluffle** [comment]
Oh ... this will probably stop you from being able to smelt or cool e.g. UMV ingots very slowly with a 64A UHV input hatch in a mega EBF or mega VF. I imagine the wailing and gnashing of teeth will be a sight to behold.

**Comment by chochem** [comment]
@fluffle its not unusual for the internal voltage numbers to not always represent a voltage but sometimes represent a power value with amperage set to one, if the multi doesnt have specific voltage restrictions.
I dont think that is related to this bug though. it just calculates the number wrong that it takes as the power. To be specific: 1 single HV hatch should be amps=1 voltage=512, not amps=1 voltage=1024.

**Comment by Pxx500** [comment]
The player can just supply the 2A through one hatch. Changing the behavior is just a slight nerf since it disables 2 parallels with one energy hatch structure. But it's not a big nerf since it's not like you save energy or anything, just time. So we can either forbid 2x parallel or add a note in the QB that the machine does that

**Comment by noobyaran9** [comment]
> Am intrigued, what was you cooling at the time?
I'm doing the air to liquid air recipe.


![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/122d3bcc-bfc1-4244-8f93-b9521c89de32)
The MVF will use up all of the EU/t that the energy hatch that it can receive to perform parallelization.
Here we have a LuV tier energy hatch where the MVF is using 65280 EU/t to process a total of 135 parallelization because the LuV Energy Hatch supports upto 65536 EU/t of input.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/42f5061a-f3d1-456a-be77-3ea45ebfe989)
This weird behaviour stops once the MVF reaches the maximum 256 parallelization and doesn't use up both amps of the ZPM energy hatch can provide.
Liquid air recipe: 480*256 = 122880 EU/t

It doesn't care what energy hatches is installed to perform parallelization as long as there is enough EU/t before hitting the 256 parallelization limit.
IMO, MVF should always try to limit the amount of parallelization to 1A of any tier of power when the (number of Amps provided to the MVF % 4)  is not 0 after factoring OC if the recipe required to be OC-ed before applying parallelization.

**Comment by noobyaran9** [comment]
> The player can just supply the 2A through one hatch. Changing the behavior is just a slight nerf since it disables 2 parallels with one energy hatch structure. But it's not a big nerf since it's not like you save energy or anything, just time. So we can either forbid 2x parallel or add a note in the QB that the machine does that

The problem with using both A from a single energy hatch is that, as soon as any maintainence issue pops up, the multiblock would stop working until you fix the issue. And this also voids your input.
This will be an issue until you gain access to auto maintainence hatch.
As for using 2 energy hatch or multi-Amp hatch to OC, you are taking the risk of the multi voiding your item when it fails as soon as any maintainence issue pops up or you already have access to the auto maintainence hatch to mitigate the issue.

~~Accidentally pressed the wrong button and closed the issue~~
