### ISSUE TITLE
Thaumcraft - Thauminite Bossed Amber Staff

### ISSUE THREAD

**Issue by Thelonite** [GTNewHorizons/GT-New-Horizons-Modpack#14542]
### Your GTNH Discord Username

TheloniteMonk

### Your Pack Version

2.4.0

### Your Server

Earthquake

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

Made the Thauminite Bossed Amber Staff for regenerative Foci use.

### The Reality

Staff created fine but it refuses to accept Foci, Holding F while wielding the staff does not even bring up the Foci selection wheel. The F key is assigned properly because Foci can be attached to my wands.

### Your Proposal

Thauminite Bossed Amber Staff to accept Foci properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Rafadaz** [comment]
Did you perchance accidently make a staffter instead?

**Comment by Thelonite** [comment]
Yeah, someone who knew, finally mentioned it on server. The existence of Staffters = Staff + Scepter. Being a staff but gaining the inability to use Foci like a Scepter. I understand the reasoning where the Amber Staff regens 100% but it is not fast, so use as a weapon is pointless.
