### ISSUE TITLE
ME level maintainer - Add `Level Maintainer Terminal` and wireless version vice versa

### ISSUE THREAD

**Issue by Laiff** [GTNewHorizons/GT-New-Horizons-Modpack#14554]
### Your GTNH Discord Username

laiff

### Your Pack Version

2.4.0

### Your Proposal

**ME Level Maintainer Terminal**:
A unified terminal connected to the ME Network that brings together the functionality of all individual Level Maintainers. It offers:

**Aggregated View**: Lists all Level Maintainers connected to the network, showcasing the items they monitor, the set thresholds, and their current status.

**Bulk Editing**: Users can change the set thresholds of multiple Level Maintainers simultaneously or apply templates to standardize configurations.

**Notifications**: The terminal will highlight Level Maintainers that have detected anomalies or are not maintaining the desired levels, offering a quick way to identify issues.

### Your Goal

**Centralized Management**: Eliminates the need to check individual Level Maintainers manually. All settings, statuses, and configurations are available in one place.

**Enhanced Efficiency**: Rapid adjustments can be made across multiple Level Maintainers, making resource management faster and more intuitive.

**Consistency**: Applying bulk changes ensures uniformity across all Level Maintainers, reducing the risk of errors or misconfigurations.

#### **Design Philosophy**:

Drawing parallels with the Interface Terminal of AE2, the Centralized ME Level Maintainer Terminal's design will prioritize user-friendliness while incorporating more advanced management functionalities for Level Maintainers.

#### **Key Features & Technical Details**:

- [x] Interface Design:

    - [x] **Display Panel**: On opening the terminal, players will see a list of all connected Level Maintainers. Each entry will display the Maintainer's name, the maintained resource, current count, set threshold, and status.

    - [x] **Interactive UI Elements**: Next to each entry, there will be clickable icons/buttons for quick actions like requesting crafts or editing settings.

- [x] Craft Request:

    - [x] **Direct Request**: Players can click on the maintained resource's icon/name in the terminal to request a crafting operation directly. An input box will pop up to specify the quantity.

    - [x] **Crafting Status Integration**: After a craft request, the terminal will display a progress bar or indication, similar to the Crafting Terminal, showing the status of the request.

- [x] Grouping & Tags:

    - [x] **Name Grouping**: Level Maintainers can be organized/grouped based on their names. Players can expand or collapse these groups for efficient navigation.

    - [x] **Tagging System**: Players can assign custom tags to each Level Maintainer's name, e.g., "Ores," "Gems," "Food." Using these tags, Maintainers can be quickly filtered or grouped together in the display panel.

- [x] Filtration System:

    - [x] **By Maintainer Name**: An integrated search bar allows players to filter the list of Level Maintainers based on their names. This is useful for quickly locating a specific Maintainer.

    - [x] **By Maintained Resource**: Another option in the search bar is to filter based on the maintained resource, e.g., "Iron Ingot" or "Redstone." This aids in identifying all Maintainers associated with a specific resource.

- [x] Crafting & Installation:

    Crafted using a combination of ME Interface components, Level Maintainers, and additional GregTech elements, ensuring that it integrates seamlessly with the existing infrastructure.

    Once crafted, the ME Level Maintainer Terminal can be connected to the ME Network like any other terminal. It will automatically detect and communicate with all Level Maintainers on the network.

    Can be combined in assembler with wireless terminal to receive Wireless version of this terminal

    Universal terminal should also require to craft ME Level Maintainer Terminal

- [x] **Future Expandability**:

    The terminal's design should be modular, allowing for future upgrades or expansions. Potential upgrades could include integration with other AE2 devices, additional filtration options, or even automation templates for crafting based on resource levels.

#### Conclusion:

The ME Level Maintainer Terminal is the next logical progression in resource management for GTNH players. It encapsulates the essence of advanced organization and control, allowing players to focus on innovation rather than micromanagement. The addition will not only streamline the AE2 experience in the modpack but also offer a deeper layer of immersion and satisfaction.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Laiff** [comment]
If this is confirmed, I can implement it myself

**Comment by vovaksenov** [comment]
This is a fantastic addition. I think you already implied adding the following via "centralized management" and "notifications", but i want to make sure because these would be great:
- making it possible to turn all level maintainers on/off with one button. Would make using i/o ports less of a pain.
- when a maintainer cant start a craft due to missing resources, the status should indicate so instead of staying green as if everything is in order.

**Comment by Laiff** [comment]
First one the answer is yes this is a part of centralized management of maintainers.

Second one, it a bit different I still in thoughts about this. The main problem here is we have two different track of indication crafting status (idle, missing items, crafting, exporting) and storage status (match, under threshold) and it's not a good option to mix all of them in one status bar. I think we can at least add new status into Level maintainer

**Comment by Eranicus** [comment]
Since I have a separate base with 30+ ME level maintainers , this will be a really great addition in my option If you can implement it

**Comment by firenoo** [comment]
Great idea. Additional requirement from me is that opening it must not bring down TPS, FPS in a noticeable way for a mid- late base, and it must not send packet storms.

**Comment by Alastors** [comment]
I think this is a really cool idea, if you make this, can you please make a separate one for Thaumic Energistics as well? It has a separate level maintainer system (or maybe you could just add that functionality into this one through optional methods or whatevs

**Comment by boubou19** [comment]
yet another content that will be gated far into the game if it's added...

**Comment by firenoo** [comment]
Why? its just an interface terminal for level maintainer...

**Comment by Eranicus** [comment]
I also dont understand why some people talk about gating. I see these changes as QoL to help control all the maintainers from one place and to troubleshoot possible problems. 

Also if is possible to add an option to config or ingame for a delay ? Currently mainteiners check around every 10sec ?

**Comment by Divran** [comment]
I've had a long list of "things I'd like to see at some point maybe" here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11349 for a while now

And one of the things on the list is a terminal that allows you to search for configs for any ae component, not just recipes. Including storage buses, export buses, import buses, and interface stock. But also level maintainers. My request was much much simpler than the proposed terminal here, though, since I'm not even saying it needs to be able to remotely adjust the settings. But I of course wouldn't say no to remote editing. I'm just saying that a search box and a button to highlight the block would be enough.

And regardless of how many of these features are implemented, it shouldn't be gated any higher than the interface terminal.

**Comment by Laiff** [comment]
After a deep dive into the ticket, I can say that I was also thinking about how to implement some of the functionality. I think I can take them after this story. 

In particular, improving the interface for crafting status, and adding a terminal for buses.

I think it makes sense to discuss them in separate tickets

**Comment by Laiff** [comment]
Current progress is here, now I'm working on improving view and add edit mode

<img width="693" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/575885/448ffd4e-2cdb-48eb-884b-fd3c328640d8">

**Comment by firenoo** [comment]
FYI I've been trying to get this merged ([massive changes to native interface terminal](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/394), both front and backend). I was planning on migrating these changes to ae2fc. Hope this isn't going to block your work too much

**Comment by Laiff** [comment]
Short keys
[Shift] -> rename machine
[Ctrl][Shift] -> open machine interface (works only when infinity booster card installed)
[Mouse3] -> craft item

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/575885/48a1aa1c-24aa-4de3-98b5-8808a5e0897d

**Comment by Darkenlord1** [comment]
Hi, maybe make players able to configure maintainers with cable connected level terminal? Because it is quite useless in my opinion.
