### ISSUE TITLE
SubOneTick sometimes skips an overclock

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#14559]
### Your GTNH Discord Username

pxx500

### Your Pack Version

Stable and newest nighly

### Your Server

Irrelevant

### Java Version

Java 20

### Type of Server

None

### Your Expectation

When overclocking 3tick EV recipe in chemical reactor to IV I expect 4x parallel 3tick recipe

### The Reality

Chemical reactor refuses to consume IV
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/828a14dc-b0f1-49c0-90aa-dd8b000d15d5)

### Your Proposal

I didn't look at the code but maybe something with the fact that the recipe is 3ticks and overclock would reduce it to 1tick and 2 parallel which would end up as a 6/4 OC so it just skips this tier and at LUV you get 3tick 4 parallel recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
I can confirm this happens. I think it started after i updated from 2.3.2 to 2.3.7. Very annoying because it makes it difficult to predict the bottlenecks when planning long chem lines until you build and see them run.

**Comment by LazyFleshWasTaken** [comment]
I have it on 2.4.0 with palladium enriched ammonia recipe form palladium metallic powder and ammonia. Currently running IV, 3 ticks, 1 ev amp consumption, but if I OC it to Luv, it runs at a full amp luv, but still on 3 ticks and with no added benefit.

**Comment by Pxx500** [comment]
> I have it on 2.4.0 with palladium enriched ammonia recipe form palladium metallic powder and ammonia. Currently running IV, 3 ticks, 1 ev amp consumption, but if I OC it to Luv, it runs at a full amp luv, but still on 3 ticks and with no added benefit.

It has 4 parallels at LuV, the issue is that it skips one OC at IV

**Comment by LazyFleshWasTaken** [comment]
Normal LCRs shouldn't have parallels at all, though? That's only an MCR thing.

**Comment by LazyFleshWasTaken** [comment]
Huh. Okay. You're right, it does indeed get a parallel.

**Comment by iamblackornot** [comment]
To make things clear, LCR overclocks at 4:4 ratio, so for the abovementioned recipe the numbers will be:

For **EV** - **3** ticks **1** parallel
For **IV** - **1** tick **1** parallel
For **LuV** - **1** tick **4** parallels
