### ISSUE TITLE
Update GS versioning scheme back to 1.1

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT-New-Horizons-Modpack#14555]
### Your Pack Version

2.4.0

### Original Request

Update GS versioning scheme back to 1.1

### Responding developer

@mitchej123

### Context

Also fix DAXXL and re-tag the existing misversioned assets.

### Developer's Promise

. s

### Final Checklist

- [X] The developer in question has instructed me to create such an issue.
- [X] I believe the developer is not causally joking around.
- [X] I understand this reminder might take a long time to implement no matter what the developer has promised. (e.g. unforeseeable life difficulty, computer breakdowns, forgetting, laziness, etc)
- [X] I understand other people (developers or not) might not like this feature and would oppose its integration.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
@mitchej123 should this block 2.5.0? GS is now up to 1.2.1.4

**Comment by Dream-Master** [comment]
@bombcar this can be done after stable.
