### ISSUE TITLE
Desync after upgrading Maceration Stack Controller with Upgrade Chip

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#14558]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.4.0

### Your Server

Delta

### Java Version

Java 17

### Type of Server

Thermos

### Your Expectation

I needed more maceration capacity to match the space elevator, so I made a bunch of maceration stacks and upgrade chips in one go, then tried building and upgrading them in sequence.

### The Reality

The chip needs to be placed in the inventory slot in the UI. The controller would consume one chip from the stack after a delay, after which I would move the stack back to my inventory and move to the next controller (using shift-clicks). The controller would turn yellow, but every other attempt the tooltip would keep saying "tier 1" and the chip would reappear in my inventory.

Waiting a few seconds extra on purpose so far prevents the desync. 

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8459776/3fdfefa8-f554-4b06-b897-56e05ce0bde5)

### Your Proposal

1. The change should not be calculated client side but only sent from the server (I think this is the implementation detail causing the bug)
2. It would be more user friendly if you could simply right-click the controller with the chip to perform the upgrade. Even if there's lag you could upgrade a few in sequence without getting botched upgrades.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Glease any idea ?
