### ISSUE TITLE
Bound Armor should have the Hazmat protection effect

### ISSUE THREAD

**Issue by GigaMegaV** [GTNewHorizons/GT-New-Horizons-Modpack#14569]
### Your GTNH Discord Username

GigaMegaV

### Your Pack Version

2.3.0

### Your Proposal

Blood magic bound armor should have hazmat.

### Your Goal

This will let blood magic bound armor compete with Void Fortress from thaum. Both are gated by similar items, with VF being gated by the vacuum freezer, and bound armor being gated by titanium. Someone who is into blood magic should not need to switch to Thaum armor, or a tech-based hazmat.

### Your Vision

It will let blood magic play alongside Thaumcraft. Perhaps instead of giving it outright, it should allow regular Hazmat armor to be socketed in, or using a sigil to add an effect.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by CanadianWinter** [comment]
Two issues with socketing a sigil.
1: You need a sigil that doesn't already have an effect when socketed
2: by wearing a single piece of bound armor you get Hazmat which would make this OP (and probably a nightmare to code)

Instead I think it should work like similar armors where you get the hazmat protection effect if all 4 pieces you are wearing give the hazmat effect.
