### ISSUE TITLE
Add Netherlicious in the future 

### ISSUE THREAD

**Issue by Minepolz320** [GTNewHorizons/GT-New-Horizons-Modpack#14574]
### Your GTNH Discord Username

Minepolz320

### Your Pack Version

2.3.0

### Mod Name

Netherlicious 

### The Mod to Add

Biomes/mobs/some mechanics are backported from the Nether Update to 1.7.10
This is looks absolutely insane 

### Your Reason

This will make nether a lot more interesting.

### Preliminary Investigation

Changes to recipes or disabling some features via config

### Final Checklist

- [ ] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Dream-Master** [comment]
@Minepolz320 did it work with the bop changes together and all other mods that change stuff in the nether ?

**Comment by chochem** [comment]
its not open source

**Comment by Dream-Master** [comment]
if it is not open source it has no chance for get added

**Comment by Minepolz320** [comment]
@Dream-Master Yes

**Comment by EnderProyects** [comment]
@Minepolz320 Hi, you know if this mod add netherite related stuff?, since I found a mod that add less things but is open source, and also adds a lot of compats around netherite ( NetheritePlus+)
