### ISSUE TITLE
Bacterial Vat dont boosted recipe "Fermented Bacterial Sludge"

### ISSUE THREAD

**Issue by kirilwapj** [GTNewHorizons/GT-New-Horizons-Modpack#14579]
### Your GTNH Discord Username

あなたが仲間の猫#5106

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

When crafting for example "Bacterial Sludge" I get 1001mb instead of 1mb for 16 dust of Mars if the output hatch is half full.

When crafting "Fermented Bacterial Sludge"
There should also be some kind of output boost.

### The Reality

When crafting "Fermented Bacterial Sludge"
regardless of how full the hatch is, I always get 1mb per
10mb Enriched Bacterial Sludge

### Your Proposal

Fix this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by querns** [comment]
Does your bacteria vat have more than one output hatch? If so, you will be penalized and the efficiency will be at minimum always.

**Comment by kirilwapj** [comment]
One exit hatch, other recipes that I made in the same bacterial vat are made with boost.

**Comment by hacatu** [comment]
This is just how the bacterial vat works: it multiplies both output AND input fluid amounts.  There are definitely some recipes (like oil bacteria) that are probably intended to be better, but that's the way it is

**Comment by chochem** [comment]
> I always get 1mb per 10mb Enriched Bacterial Sludge

yea that is intended an not a bug. the fluid ratio stays the same
