### ISSUE TITLE
Allow 'R' and 'U' to work on encoded patterns

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/GT-New-Horizons-Modpack#14570]
### Your GTNH Discord Username

alongstringofnumbers

### Your Pack Version

2.4.0

### Your Proposal

Allow the 'R' and 'U' shortcuts to work on the item encoded into an ME crafting pattern

### Your Goal

This would allow for easy checking of uses for encoded items, to see if it is used at all in your current setup, or has been obsoleted by some new setup.

It would also allow easy comparison between the recipe that you are using (which is encoded on the pattern), and any other recipes that exist for the output item, which you may have unlocked later.

### Your Vision

This would make it nicer to check on recipes and uses for items, especially when looking in the interface terminal, as instead of having to go to NEI for the item, you can directly go from encoded patterns

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by firenoo** [comment]
This seems like a change in NEI. Does NEI have an API for a mod to override the recipe that is looked up for a particular item?

**Comment by ALongStringOfNumbers** [comment]
Hm, I know JEI does, not sure about NEI though

**Comment by Caedis** [comment]
Logic comes from: https://github.com/eutro/dynamistics
