### ISSUE TITLE
Mobs that can't be in soul vials show up in EEC menu

### ISSUE THREAD

**Issue by Dr-Nye** [GTNewHorizons/GT-New-Horizons-Modpack#14577]
### Your GTNH Discord Username

DrNye

### Your Pack Version

2.4.0

### Your Server

Private

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Mobs that cannot go into soul vials can't be bound into a powered spawner. They therefore cannot be used with an EEC. They should not show up in NEI cause it just adds extra pages without any useful information

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22504802/923c49ab-e7de-4f09-b83e-fa88d76508c2)

### Your Proposal

Run a check on soulvialability of mobs before adding them to the recipe chain on EEC

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
Mobs Info tab show general information about mobs, it isn't exclusive to EEC

**Comment by Dr-Nye** [comment]
it's still what shows up when you hit usages on the EEC, maybe make it different menus
