### ISSUE TITLE
Ethanone chemical should be renamed to Ethanal

### ISSUE THREAD

**Issue by VexXzu** [GTNewHorizons/GT-New-Horizons-Modpack#14576]
### Your GTNH Discord Username

VexX

### Your Pack Version

2.3.0

### Your Proposal

Chemical "ethanone" doesn't exist. The chemical should be renamed to ethanal to be accurate.

*warning: chemistry autism ahead* In terms of the chemistry, ethanone would be refering to the functional group "ketone" and this refers to a double bonded oxygen to a carbon in the middle of the chain. It can't exist on the end of a chain. The problem with ethanone is there are only 2 carbons, meaning the double bonded oxygen would infact exist on the end of the chain. Instead of this being a ketone, this would now be considered an aldehyde. Aldehyde's are functional groups that have a double bonded oxygen on the very end of the hydrocarbon chain. The chemical would therefore be called "ethanal" and not "ethanone".

### Your Goal

Needed cuz it's accurate

### Your Vision

Improves the pack cuz its the right name

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pxx500** [comment]
I'm not sure what're you talking about, there is no such thing as ethanone in gtnh, it's ethEnone
https://en.wikipedia.org/wiki/Ethenone

**Comment by hallucinogender** [comment]
There is no chemical in GTNH with the name "ethanone" _or_ "ethanal". Ethanal is a completely different chemical to eth_e_none, which is in the modpack. Ethenone and ethanol are different chemicals with different structures, they are produced in different ways and are used for different things.

The error here is that the person who opened this issue simply misread "ethenone" as "ethanone". There is no such problem with the modpack, so this issue can be safely closed.
