### ISSUE TITLE
Crash on resizing window on MacOS 

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#14588]
### Your GTNH Discord Username

bombcar | 💣🚙#1042

### Your Pack Version

2.4.0-2.4.1

### Your Server

SP

### Java Version

Java is version 17.0.8.1, using 32-bit architecture, from Eclipse Adoptium.

### Type of Server

None

### Your Actions

* Start GTNH from MultiMC 0.7.0-3814 on macOS 13.5.2 (M1 Pro).
* Try to resize the window it is running in
* It blows up.

This happens both with and without Optifine E7.

Sometimes it will happen even if in fullscreen and I switch out and back. Never crashes going out, only coming in in that case.

I can reliably get it to happen, but if I very carefully resize the window, sometimes it doesn't explode.

If I wait until it is full loaded or in game, same thing.

### Crash Report

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               java [7826]
Path:                  /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java
Identifier:            java
Version:               ???
Code Type:             ARM-64 (Native)
Parent Process:        MultiMC [11241]
Responsible:           MultiMC [11241]
User ID:               502

Date/Time:             2023-09-25 15:24:52.4112 -0500
OS Version:            macOS 13.5.2 (22G91)
Report Version:        12
Anonymous UUID:        3A8E64DF-67D7-41C7-BB25-0EE7F784E52E

Sleep/Wake UUID:       D497EC21-666E-4154-8FCC-FF0B01FE5D3F

Time Awake Since Boot: 270000 seconds
Time Since Wake:       22777 seconds

System Integrity Protection: enabled

Crashed Thread:        45  Java: BLS Splash renderer

Exception Type:        EXC_BAD_ACCESS (SIGABRT)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000100
Exception Codes:       0x0000000000000001, 0x0000000000000100

Termination Reason:    Namespace SIGNAL, Code 6 Abort trap: 6
Terminating Process:   java [7826]

VM Region Info: 0x100 is not in any region.  Bytes before following region: 105553518919424
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)

Application Specific Information:
abort() called

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
[problem_report.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12719107/problem_report.txt)

[hs_err_pid7826.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12719113/hs_err_pid7826.log)

**Comment by Connor-Colenso** [comment]
I can confirm that I also get this issue a lot, especially in a dev instance. Very annoying.

**Comment by bombcar** [comment]
I just noticed it is complaining it's a 32 bit version of Java 17, hmmm.

I also get this when hitting "test"

Java test succeeded!
Platform reported: aarch64
Java version reported: 17.0.8.1
Java vendor reported: Eclipse Adoptium

Warnings:
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0

**Comment by bombcar** [comment]
I think multimc may be slightly confused because:

bombcar@lappy486 ~/Downloads/GT New Horizons 2.4.0/.minecraft $ /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home/bin/java --version
openjdk 17.0.8.1 2023-08-24
OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode)

**Comment by bombcar** [comment]
Using graalvm gives the same weird 32 warning, but I think that's multimc not understanding (the process uses 64 bit as far as I can tell)

It barfed out without a resize this time, but this could be unrelated and maybe caused by Graal, will switch back.

[hs_err_pid20406.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12720780/hs_err_pid20406.log)
[graalgrash.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12720783/graalgrash.txt)

**Comment by bombcar** [comment]
I've updated to macOS Sonoma and it happens _less_ but it still occurs:

```#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000185b31420, pid=13261, tid=8707
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.8.1+1 (17.0.8.1+1) (build 17.0.8.1+1)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (17.0.8.1+1, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# C  [libobjc.A.dylib+0x9420]  objc_msgSend+0x20
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Applications/MultiMC.app/Data/instances/GT_New_Horizons_2.4.1_Java_17-20/.minecraft/hs_err_pid13261.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Process crashed with exit code 6 (0x6).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
```

Would a core dump be useful to anyone, anywhere?

**Comment by mitchej123** [comment]
`hs_err_pid13261.log` would be the most helpful, assuming it's any different from the one you posted earlier.

**Comment by bombcar** [comment]
[hs_err_pid13261.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13241557/hs_err_pid13261.log)

They all look the same to me, but I had to shake the window fairly hard to get it to blow up this time

**Comment by bombcar** [comment]
This occurs on J21+ with dev, though maybe a tiny bit less.
