### ISSUE TITLE
JEIUTILITIES recently viewed bar

### ISSUE THREAD

**Issue by xtrux** [GTNewHorizons/GT-New-Horizons-Modpack#14589]
### Your GTNH Discord Username

xtrux

### Your Pack Version

2.4.0

### Your Proposal

JEIUTILITIES is a 1.12.2 mod that has one feature that would be a massive quality of life addition should it be backported. this feature is having a list of recently viewed recipes in the bottom right corner of NEI. I believe that this feature would make the pack better.

### Your Goal

makes it easier to remember what i was doing

### Your Vision

this would make the pack easier to track what item you are working on without having to bookmark it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vfyjxf** [comment]
try [NeiUtilities](https://github.com/vfyjxf/NEI-Utilities)!
