### ISSUE TITLE
Multi-smelter not working with Crafting input buffer

### ISSUE THREAD

**Issue by berta24** [GTNewHorizons/GT-New-Horizons-Modpack#14587]
### Your GTNH Discord Username

Berta24

### Your Pack Version

2.4

### Your Server

private server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Being able to craft huge batches since with eternal coil the parallel is 16k at 1tick

### The Reality

i'm limited by the input bus size and also the machine continue on/off because the interface has delay to push items inside the Input bus, item buffers are still slow compared to the machine

### Your Proposal

make the multismelter support crib

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by fluffle** [comment]
I think this seems to be fixed in 2.5.x?

**Comment by Dream-Master** [comment]
@berta24 can you test with 2.5.0/2.5.1 ?
