### ISSUE TITLE
GT++ 2.4.1-related issues

### ISSUE THREAD

**Issue by FloatDoubling** [GTNewHorizons/GT-New-Horizons-Modpack#14596]
### Your GTNH Discord Username

quitebased

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Things work properly like they were before

### The Reality

So, after update to 2.4.1 i noticed some issues related to GT++:
1. Games crashed on GT++ Achievements page when you hover cursor over some quests or places on screen.
2. Wireless chargers completely stopped charging, it doesn't work in either of 3 charging modes.
3. EIO Machine chassis recipe that used removed GT++ Electrical steel variant now have a fire animation in NEI recipe:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/115502326/c5f17a0e-cade-4f66-a243-2537bc7c3577)
There could be other recipes that used some of removed GT++ materials and wasn't deleted properly.

These are the issues with GT++ i found so far after the update. They could be related to recent huge cleanup and others commits after that.

Crash logs related to GT++ achievements page:

[crash-2023-09-26_08.57.34-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12723746/crash-2023-09-26_08.57.34-client.txt)

[crash-2023-09-26_09.29.08-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12723747/crash-2023-09-26_09.29.08-client.txt)

### Your Proposal

Fix these issues.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
The wireless charger was always buggy, not sure why.

**Comment by chochem** [comment]
@minecraft7771 reworked/fixed it at some point. but it just went from one set of bugs to somewhat different ones if I understand correctly.
