### ISSUE TITLE
Add an assembler recipe for Yottank casings

### ISSUE THREAD

**Issue by NotAPenguin0** [GTNewHorizons/GT-New-Horizons-Modpack#14590]
### Your GTNH Discord Username

notapenguin

### Your Pack Version

2.4.0

### Your Proposal

Add an assembler recipe for yottank casings instead of only a shaped craft.

### Your Goal

Consistency with most other recipes.

### Your Vision

It's just nicer

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
good idea. we need to ad much more items/blocks as machine recipes
