### ISSUE TITLE
Unable to start server due to mod errors

### ISSUE THREAD

**Issue by Jigglyy** [GTNewHorizons/GT-New-Horizons-Modpack#14591]
### Your GTNH Discord Username

_jiggly

### Your Pack Version

2.4.0

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

None

### Your Actions

Closed server, disabled pollution from config and started it up again with bash startsertserver.sh

### Crash Report

[crash-2023-09-25_22.46.50-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12719936/crash-2023-09-25_22.46.50-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
`cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: The Enum 'Pollution_Cleaner_LV' has not been set to an Item at this time!
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

Do you have any LV pollution cleaners in the world or inventory? Remove or otherwise delete/disable them?

**Comment by Jigglyy** [comment]
> `cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: The Enum 'Pollution_Cleaner_LV' has not been set to an Item at this time! at cpw.mods.fml.common.LoadController.transition(LoadController.java:163) at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744) at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319) at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`
> 
> Do you have any LV pollution cleaners in the world or inventory? Remove or otherwise delete/disable them?


How does one find/delete items?
