### ISSUE TITLE
Liquid Air cannot be made in a vacuum freezer from "fluid" air

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#14606]
### Your GTNH Discord Username

.querns

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

I expected to be able to make liquid air using the old recipe of 2000mB "fluid" air -> 1000mB liquid air in a vacuum freezer.

### The Reality

This recipe has been removed. Oddly, the GT++ cryogenic freezer still has it.

### Your Proposal

Put the recipe back.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bpwhelan** [comment]
Can confirm, same can be said for some other fluids such as water -> crushed ice.

**Comment by miaowwwwww** [comment]
and nitrogen same problem

**Comment by miaowwwwww** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/d81a88cc-8def-4192-b6df-6d4d1acb700c)
no recipe for this too, which effect endgame craftings like uxv wirless laser, compact MKV fusion
