### ISSUE TITLE
Add ability to convert any tier circuit to "Any *TIER* Circuit"

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#14607]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.3.7

### Your Proposal

Add ability to convert any same tier circuit to "Any *TIER* Circuit".

### Your Goal

use in every crafting patterns "Any *TIER* Circuit"
encode which "same tier circuit" used for "Any *TIER* Circuit"
when you want swap to next level "same tier circuit" you just change "Any *TIER* Circuit" pattern

### Your Vision

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/a0d2954c-9f42-41d2-8a08-e19f2e82176a)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by RitumsC** [comment]
I believe this would be an amazing QOL, why was it closed?

There are no existing alternatives and currently changing to new-tier circuits is needlessly tedious.
