### ISSUE TITLE
Add a "pattern count" to the ae2 crafting preview screen

### ISSUE THREAD

**Issue by Ilithios06** [GTNewHorizons/GT-New-Horizons-Modpack#14617]
### Your GTNH Discord Username

ilith (legacy: Ilith#7274)

### Your Pack Version

2.4.0

### Your Proposal

Add a button to the ae2 crafting preview screen, next to the crafting screen button, that switches the way item counts are displayed in the crafting screen:
"Item Mode":
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86689318/f82a324d-1554-4743-a6dd-c73a89cc5902)

"Pattern Mode":
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86689318/c42be75b-a0fc-4cf8-8e32-41f7bf9d48ca)

### Your Goal

This is to help visualize which patterns are too small at any given point in time, most dominantly in the later stages of the game, where the amount of items needed is extremely high

### Your Vision

If you have crafting CPUS with any number of coprocessors greater than like 1k, the server has a hard time processing all of the coprocessors trying to send items at once. Thus too small patterns can lead to tps going down immensly at the start of a craft and perhaps even until the server gets restarted. Knowing beforehand if any (initial) crafting step would need multiple thousand patterns be pushed can help reduce the occurence of these lag spikes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by RaitGamerGR** [comment]
What about new row with pattern amount?

**Comment by Hiagg** [comment]
i agree adding something like this would be great
