### ISSUE TITLE
Better document the GT++ Cryogencic Freezer tooltips

### ISSUE THREAD

**Issue by mjevans** [GTNewHorizons/GT-New-Horizons-Modpack#14618]
### Your Pack Version

2.4.0

### Your Proposal

Presently the GT++ Cryogenic Freezer controller block, on non-shift says "Consumes 1L/t of Gelid Cryothium during operation".

Zeroth Description bug: Operation is weasel word vague.  Someone uninformed, such as myself, and such as someone more experienced that I'm playing with, reasonably equates operation with "performing work".  The multiblock has other ideas.  "Consumes 1L/t of Gelid Cryothium **while turned on** "  If we'd seen that, other ingot solidifying solutions would have been sought.

First Description bug: It also says "Constructed _exactly the same_ as a normal Vacuum Freezer".  This is incorrect on at least two fronts.  It only resembles the SHAPE of a Vacuum Freezer, but does not share the casing blocks.

Second Description bug: The shift tooltip mentions quite a number of other blocks, but fails to mention a specific type of input block, which should be enumerated separately.  Cryothium Cooling Hatch

Third (validation) bug: the Multiblock Structure Hologram Projector (blueprint tool), when shift right clicked on the controller with the multiblock lacking a gelid cryothium input hatch, uses the same incomplete list of required blocks that I the player was to arrive at the incorrect conclusion that the multi-block structure was valid and complete.  This is likely due to the full requirements not being expressed in both cases.

Someone I'm playing with linked me to a screenshot from an __older version__ which does mention the cryothium cooling hatch.  That is not present in pack version 2.4.0.

### Your Goal

Players should be able to complete the multiblock with in-game documentation limited to the current version of the game.

### Your Vision

The shift list should list distinct types of blocks differently, ideally with required blocks first.

Machines frequently display a range requirement for E.G. minimum casing blocks.

Maximum counts should also be in the shift list, E.G. for machines that only accept one energy hatch.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Im on 2.3.7 and cryotheum is only consumed during operation (actually cooling smth down). While the multi is turned on but idle, no cryotheum is consumed, so i am not sure what you mean by the 0th complaint unless this mechanic changed between 2.3.7 and 2.4.0.
