### ISSUE TITLE
Sugar's Electrolyzer To Oxygen recipe is missing.

### ISSUE THREAD

**Issue by ussdefiant60** [GTNewHorizons/GT-New-Horizons-Modpack#14611]
### Your GTNH Discord Username

ussdefiant60

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

My Sugar Beet Processing chain providing a secondary oxygen supply as it has in 2.2 and 2.3 both.

### The Reality

The disapperance of the Sugar Electrolyzing recipe, in combination with #14606 , has completely starved my base of oxygen as my two steady sources of it are cut off.

### Your Proposal

Please find where the sugar electrolyzing recipe went off to and convince it to start working again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by querns** [comment]
Weird, I have it.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/33518699/4808cf06-f21b-4c6f-80f9-f5e2790b2e8a)

**Comment by Glease** [comment]
try a clean install maybe? cannot replicate either

**Comment by ussdefiant60** [comment]
My apologies. It appears that i was too tired last night to notice the two electrolyzer tabs in NEI being present, and that the issue with the sugar not producing oxygen was actually a unrelated bit of legacy cruft related to my base setup. Closing the issue.
