### ISSUE TITLE
MouseTweaks config becomes corrupted. Scroll moves 2 items at once

### ISSUE THREAD

**Issue by DmitryScaletta** [GTNewHorizons/GT-New-Horizons-Modpack#14626]
### Your GTNH Discord Username

DmitryScaletta

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

MouseTweaks config never becomes corrupted.
Scroll moves 1 item at a time.

### The Reality

Sometimes MouseTweaks config becomes corrupted.
I don't know why.
Maybe it happens after a crash or unexpected shutdown (power outage) but not always.

Because of that the config is no longer a text file and can't be read by MouseTweaks so it uses the defaults.
By default the scroll items feature is enabled and it moves 2 items at once because similar feature in NEI is also enabled.

There are several people in discord with similar problem:
<details>
  <summary>screenshots</summary>
  
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/8cecf12e-dca4-4d4a-a571-e088028c054a)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/d3226ddb-6075-499e-bca4-e500c88e1edf)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/e9a6eade-601d-4189-b883-156e79d3c7f7)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/261ac07a-38af-4ad0-b909-ec51672d7559)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/bf808f41-4f3f-4fa8-9ce6-947656e20842)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/37358fcf-fe59-4857-b3fa-c1bd58b72c69)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/0c7e4428-085f-42e4-97e9-8d8e63292b09)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/47415f53-cd48-41f2-a633-71cd11a0cc8f)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/ed0fe669-3cb4-4bc1-b2f2-6e566034f14c)

</details>

Here is an example of my corrupted config
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/37e2c63b-02ff-4768-8140-8f9ffe5ff183)
[MouseTweaks.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12771230/MouseTweaks.zip)

And one example from discord
https://discord.com/channels/181078474394566657/234936569360809996/1054107866153361418
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/87e44f78-998d-4c4c-b2e3-bdc89c7e1574)

<details>
  <summary>Sublime Text opens it as a hex</summary>
  
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/540ea999-4a0b-452a-9374-5e20713a17af)

</details>

<details>
  <summary>P.S. Another small bug in MouseTweaks</summary>
  
Scroll items in MouseTweaks is buggy and sometimes it moves items from inventories to player inventory even if you didn't scroll.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5096735/5ccec680-9aad-4844-9745-84a9671d2a6f)

</details>

### Your Proposal

\-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DmitryScaletta** [comment]
### Temporary fix

Restore the original `config/MouseTweaks.cfg` file:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/MouseTweaks.cfg

**Comment by Glease** [comment]
maybe something wrong with the defaultconfig's ini parser... sigh
