### ISSUE TITLE
Make Obsidian Pulverize into 9 Dust

### ISSUE THREAD

**Issue by Dr-Nye** [GTNewHorizons/GT-New-Horizons-Modpack#14621]
### Your GTNH Discord Username

DrNye

### Your Pack Version

2.4.0

### Your Proposal

Vanilla Obsidian blocks should pulverize into 9 obsidian dust

### Your Goal

Obsidian can be alloysmelted into 9 ingots which each can be pulverized into 1 dust for 9 times the yield of obsidian dust.

### Your Vision

Consistency of material ammounts

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
I like having things that are more "efficient" if you use them right, but the alloy smelter is *before* the macerator, so perhaps the macerator should pulv into 9 and the smelter into 4? Dunno, hmm.

**Comment by HFPTetraUro** [comment]
> I like having things that are more "efficient" if you use them right, but the alloy smelter is *before* the macerator, so perhaps the macerator should pulv into 9 and the smelter into 4? Dunno, hmm.

Don't forget that the alloy smelter recipe requires an Ingot Mold which requires Steel (Unless you get lucky and find one in a Loot Game) which is after getting the Macerator, so I think this is fine
