### ISSUE TITLE
machines and some block entities breake after rentering chunks

### ISSUE THREAD

**Issue by 7312jp2137** [GTNewHorizons/GT-New-Horizons-Modpack#14624]
### Your Pack Version

2.3.2

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

after returning to previously unloaded chunks the textures are gone . i cant open machines , when i click on them the items show in my inventory (even fluids) crashes after some time . works fine if i just reenter the world. i am also using optifine. the world has been updated one time to the current version (using curseforge).
![2023-09-29_15 25 11](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/146450490/14fec661-712f-4404-9b10-1d0abc76cfc0)
![2023-09-29_15 24 01](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/146450490/60964e48-6dd0-4740-8c2c-c0cd9046e9ca)
![2023-09-29_15 23 53](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/146450490/5681cf6f-6873-473c-95a2-849c0f1420c9)

### Crash Report

[crash-2023-09-29_15.33.57-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12766074/crash-2023-09-29_15.33.57-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
"using curseforge"

this is almost certainly the problem; some mod(s) got partially updated or you may even have duplicate mods.

If you want, try https://wiki.gtnewhorizons.com/wiki/Installing_and_Migrating section "Migrating to a different launcher", perhaps with Prism as maybe the easiest? You should be able to copy your world save over.

**Comment by AbdielKavash** [comment]
Even though the OP specifies an older version, this still happens in 2.4.0 (I haven't encountered it in 2.4.1 yet, but that is because most of my machines are constantly chunkloaded).

It is not a curse issue either, it happens with the official download using Prism too.

Relogging fixes the problem, the machines are not actually lost/destroyed.

**Comment by RaeKiyari** [comment]
looks like a chunkloading issue

**Comment by fluffle** [comment]
Are you using optifine? It has an option that changes chunk loading behaviour and that can cause this.

**Comment by 7312jp2137** [comment]
> Are you using optifine? It has an option that changes chunk loading behaviour and that can cause this.
I am how can i change that option

**Comment by MrAkells** [comment]
I'm having the same problem on my server. The problem is not Optifine, because all players on the server see broken machines, even without Optifine.
