### ISSUE TITLE
Is the current nerfs on end-game power generation approaches that making Nq reactor the only viable choice intentional

### ISSUE THREAD

**Issue by Iridium771394** [GTNewHorizons/GT-New-Horizons-Modpack#14630]
### Your GTNH Discord Username

Do I even need to have one of this shit

### Your Pack Version

2.4.0-RC2

### Your Proposal

How about leave your nerfy-hands off from SC Steam and Dyson swarm?
I am in ZPM stage now and I really appreciated and enjoyed the diversity of power generation now. For now I run a UCE with H8N4C2O4 rocket fuel for my primary power generation, a THTR with SC Steam to tackle passive comsumptions, few vaccum reactors running with excited fuels, and a XL gas turbine for firing all those annoying alkanes. I am also building a line for LEG to try out this fun and engaging system. 
In this stage I got so much choices and capability to achieve them but from now on I will surely step on a tedious and repetive way of spamming LNQ reactors since Dyson swarm nerfed (Without the promised solar cover recipe rework) and SC Steam from plasma seems doomed to be nerfed.
Literally this have kept me from going further on the tech tree.

### Your Goal

Take a grain of salt when considering nerf something
Or at least let us know your vision on mid/late game power generation (post UV )

### Your Vision

Make post UV power generation more diverse, fun and engaging instead of spammingh LNQ reactors or EOHs

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
you should try out the new fusion chain :)
Well you are only zpm anyway, so not a surprise you are not aware of all the options.

Anyway, I dont see any actually relevant suggestion here, so this is getting closed.
