### ISSUE TITLE
Warpwood Rod recipe accepts any wood type

### ISSUE THREAD

**Issue by mM4ri** [GTNewHorizons/GT-New-Horizons-Modpack#14631]
### Your GTNH Discord Username

mMari_

### Your Pack Version

2.4.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Warpwood Rod recipe should only accept Warpwood logs as an ingredient.

### The Reality

The recipe accepts any type of wood, so you can skip making the warpwood sapling.
![Warpwood2](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/125275951/db77e0e5-970b-4f69-b695-33f98f9eac1f)

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Rika-TH** [comment]
can you confirm this is actually craftable with any log? many TC infusions are bugged to hell in NEI, shards most notably but generally any time you see a cycle in NEI it's fake (boots of traveller are a common example)

@Alastors forget if warpwood was mentioned last this was brought up

**Comment by Glease** [comment]
Infusion recipe does auto oredict, and both are just logWood, so you can indeed just use a oak log instead

**Comment by AdolMors** [comment]
My experiences align with Rika's statement that oredict cycles in NEI infusion recipes are incorrect. Instead the Thaumonomicon lists the correct items required. A few examples below:
Boots of the Traveller accepts only Raw Fish, Raw Salmon, Clownfish and Pufferfish but all raw fishes are shown in NEI.
Wand Augmentation Charge Buffer accepts only Silverwood Log but all logs are shown in NEI.

Back to the reported issue. Warpwood Wand Rod recipe shows only Warpwood in the Thaumonoicon and if there is any pattern shown by examples above, only Warpwood will work.

I would recommend fixing the oredict problem in NEI infusion recipes as auto oredict seems to be used liberally when those recipes do require specific items.

**Comment by Alastors** [comment]
> can you confirm this is actually craftable with any log? many TC infusions are bugged to hell in NEI, shards most notably but generally any time you see a cycle in NEI it's fake (boots of traveller are a common example)
> 
> 
> 
> @Alastors forget if warpwood was mentioned last this was brought up

I can Lmfao

**Comment by Alastors** [comment]
> My experiences align with Rika's statement that oredict cycles in NEI infusion recipes are incorrect. Instead the Thaumonomicon lists the correct items required. A few examples below:
> 
> Boots of the Traveller accepts only Raw Fish, Raw Salmon, Clownfish and Pufferfish but all raw fishes are shown in NEI.
> 
> Wand Augmentation Charge Buffer accepts only Silverwood Log but all logs are shown in NEI.
> 
> 
> 
> Back to the reported issue. Warpwood Wand Rod recipe shows only Warpwood in the Thaumonoicon and if there is any pattern shown by examples above, only Warpwood will work.
> 
> 
> 
> I would recommend fixing the oredict problem in NEI infusion recipes as auto oredict seems to be used liberally when those recipes do require specific items.

Traveller's also uses any shard (likely because of Thaumic nei, given this doesn't happen outside the pack) Glee has explained the problem to me before but I have since forgotten.

It's not just nei, this does have plenty of ingame accidents as well that aren't supposed to happen

**Comment by AdolMors** [comment]
Shards? Maybe. I definitely tried using raw squid for Traveller and that did not work.

**Comment by Alastors** [comment]
> Shards? Maybe. I definitely tried using raw squid for Traveller and that did not work.

There's no maybe in this, I've tried it myself. All thaumcraft shards are interchangeable for god knows what reason (I know the general reason but not what's causing it)

**Comment by Alastors** [comment]
That's part of the reason why it's better practice to use clusters over shards in recipes.

**Comment by Alastors** [comment]
Pam's fish do not work though, only vanilla fish

**Comment by AdolMors** [comment]
> There's no maybe in this, I've tried it myself. All thaumcraft shards are interchangeable for god knows what reason (I know the general reason but not what's causing it)
Thanks for confirming. I answered maybe because I was not sure about the shards. I vividly remembered only the fish part. I have not been keeping up with updates to recognize those are vanilla fish before looking up the item history.

**Comment by AdolMors** [comment]
The boots recipe requires air cluster now. I started playing at 2.3.4 so chances are I missed the old recipe.

On the other hand... I was able to complete the warpwood wand infusion with any wood log (checked with abacus and then performing the infusion).

**Comment by LazyFleshWasTaken** [comment]
Yup, I made warpwood with spruce too and told someone in magic dev, but didn't make a ticket for it since making warpwood isn't a real gate, just a step.

**Comment by Glease** [comment]
I plan to fix this soon™. The underlying recipe code is ready. just need adoption in NEI addon and recipe declaration
