### ISSUE TITLE
Currently Unobtainable Foods

### ISSUE THREAD

**Issue by hacatu** [GTNewHorizons/GT-New-Horizons-Modpack#14638]
### Your GTNH Discord Username

hacatu

### Your Pack Version

2.4

### Your Proposal

There are currently about 1264 foods which can be eaten to gain hearts, 2 that seem to be bugged and not count even after eating, and 28 unobtainable foods.

Here is a breakdown of the 30 unobtainable or bugged foods:

* Sap/Latex Bucket/Capsule/Can/Glass/Capsule(refractory): Glass/Capsule(refractory) are hidden in NEI.  The fluids "sap" and "latex" are simply unobtainable
* Missed Fluid: this is just a placeholder item for Binnie Core
* Ambrosia: Kelp and Celestial Crystal Shards are unobtainable because their spawning is disabled (ocean biomes don't generate and the crystals don't generate in the end)
* Turnip: turnip seeds are supposed to drop from Koru (an alternate BOP grass used in some biomes) but does not seem to, it's probably broken by whatever disables getting seeds from grass normally.  Tilling ground in the relevant biomes does not also give turnip seeds.  IC2 turnips drop Pam's turnips, not BOP
* Sand Pear/Papayimar: unused foods from extratrees
* Terra Wart: never counts as eaten, even after eaten
* Taintberry: unobtainable
* Unidentifiable Meat/Cooked ""/"" Nugget: this is supposed to drop from Tumorous Clouds which are supposed to spawn in Pocket Planes, but only basic Clouds were ever implemented afaict, and bart axed even those five years ago
* Toast: the cooking for blockheads toaster makes Pam's toast, so its own toast is unobtainable
* Quantum Bread: this is the weirdest one.  This item can be obtained from Haute cuisine loot bags or crafted from "Breads" in a UV slicing machine.  Before eating it, it is hidden in NEI and counted as not eaten.  After eating it, it is counted as eaten, but when you relog, it is no longer hidden in NEI and will show as not eaten there, but will show as eaten in the food journal
* 14 gregtech drinks that are hidden in NEI and can be seen by looking at uses for glass bottles/empty thermos in a fluid canner: these should have recipes

Honorable mentions:
* Bowl of Rice: BOP rice is unobtainable since Land of the Lakes biomes do not generate, but BOP rice itself is not edible and this food can be gotten as a quest reward
* Curative Mead: Crafted from Short Mead bottle + Pollen Cluster in an Infuser, recipe not in NEI
* Bacon: only vanilla tcon pigiron has the tasty trait, tgregworks doesn't
* Wolf, Ocelot, and Blaze meat: virtually require EEC, or in the latter case literally require it because in world blazes always turn into specialmobs which don't drop it.  These should probably be added to other wolf/cat/blaze like mobs
* Binnie capsules: honestly, why is turpentine or polymerized bacteria even edible?

### Your Goal

Aside from Missed Fluid, these foods should be obtainable to sate utter completionists.  Also, the bugs with terrawart and quantum sliced  bread should be fixed.

For many of these items, there are "obvious" ways that they should be obtainable.  I will go over these and offer suggestions in other cases:

* Sap/Latex: I think these are supposed to come from forestry logs in the forestry squeezer, but this isn't implemented.  But honestly the Binnie fluid containers are the sketchiest foods
* Missed Fluid: should not be obtainable
* Turnip: seeds should drop from tilling grass in "swamp" biomes
* Sand Pear/Papayimar: IMO these should drop from Cultivated Pear and Papaya trees that have been bred to grow on sand and grown there
* Taintberry: idk lol, I guess add it to a loot bag?
* Unidentifiable Meat: while it would make more sense to me for this to be a result of mobs dying in the curative vat, the mod author's intention was clearly for it to come from pocket planes, so that should be the case.
* Toast: the cooking for blockheads toaster should make this instead of Pam's toast

Random Greg drinks (excl transitive):
* Old Man Snitches glitched Diablo Sauce: probably should be craftable from Diablo Sauce (32122)
* Scotch: suggest barley + distilled water in brewing machine / biovat @ G.P. fermenting bacteria
* Golden Apple Juice: should be craftable from golden apple + distilled water in brewing machine
* Salty Water: add distillation recipe from Salt Water?
* Cave Johnsons Grenade Juice: throwable bomb + leninade in brewing machine?
* Diablo Sauce (32123): probably should be removed
* Diablo Sauce (32122): these both have the same fluid registry name "potion.diablosauce" (OMSgDS has name "potion.diablosauce.strong") but they have different item ids when bottled.  Suggest demon heart + hot sauce in brewing machine
* Idun's Apple Juice: this is supposed to be craftable from notch apple + distilled water, but it might make sense for this and Golden Apple Juice to use higher tier waters, like green vitriol water solution and tier 1 purified water
* Dark Coffee au lait: should be dark coffee + sugar in brewing machine
* Sweet Tea: should be tea + sugar in brewing machine
* Lait au cafe: suggest molten sugar + coffee in a mixer

### Your Vision

I should be able to add ways to obtain most of these.  I don't know how to fix the bugs with terrawart or quantum bread though, and there are a couple that are questionable:

* How should ambrosia be obtainable?  Just swap out the kelp and celestial crystal for algae and hee arcane shard?
* I can probably whip up something for completing pocket plane creation, but I think that obviously warrants more discussion
* Are any of the other recipes suggested bad for some reason?
* Also, I think some of the foods mentioned in "Honorable Mentions" might be too obtuse as-is

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Is there a chance some of the greg drinks have a hidden recipe? Something like dragon blood for wetwares before the line change?

**Comment by hacatu** [comment]
That's definitely possible, I have no idea how to check for that though.  Already purple drink and holy water are loot only so hidden recipes aren't a stretch

**Comment by Rika-TH** [comment]
a note should be made that some things like terrawart do not trigger the negative effect of overeating and atleast for terrawart this should not be changed, I'd guess atleast for that both of these things (not yet eaten, and no downside) are caused by it not having any nutritional value when eaten (despite it saying otherwise)

**Comment by hacatu** [comment]
So vovaksenov was right: Cave Johnsons Grenade Juice, Golden Apple Juice, Idun's Apple Juice, Sweet Tea, Dark Coffee au Lait, and Lait au Cafe are all crafted exactly how you would think; their recipes just don't show in NEI.  Still not sure about Scotch, Salty Water, and Diablo sauce

**Comment by hallucinogender** [comment]
> So vovaksenov was right: Cave Johnsons Grenade Juice, Golden Apple Juice, Idun's Apple Juice, Diablo Sauces, Sweet Tea, Dark Coffee au Lait, and Lait au Cafe are all crafted exactly how you would think; their recipes just don't show in NEI.
> 
> I checked the code and Scotch also has a recipe (ferment wheaty juice) but this obviously conflicts with the fermented wheat recipe, and salty water has no recipe

These aren't intuitive, and the lack of NEI recipes means people won't necessarily even know they exist, much less begin to guess at what the recipes might be. Perhaps there should be a late-game quest explaining how to get these drinks; anyone who is dedicated enough to want to eat all of the edible things in the modpack will probably be attempting to reach the late-game anyway, so putting a quest there to say "here's how to get these extra secret foods" makes some degree of sense.

**Comment by jose9222** [comment]
I would like to address some points as a food completionist:

- The cooking for blockheads toast is obtainable the normal way in 2.5.1

- There are more hidden recipes (As alredy pointed sap and latex are unobtainbale):
   Sap/Turpentine/Latex/Resin capsule using the Refractory capsule (The red one)
   Growth medium into every capsule/bucket/glass bottle except the cylinder
   Acid/Poison/Nitorgen/Sap/Resin/Latex/Turpentine for the glass cylinder

- Glass bottles not counting growth medium and the ones alredy said by the original post:   
   Golden Cider
   Notches Brew
   Glen McKenner
   Potato Juice
   Diabolo Sauce ( Commeted by the op as Diablo Sauce (32122))
   Sap/turpentine/Resin/Latex/Poison/Acid/Nitrogen Glass
   
All the above recipes have edible values, some of them are obtainable and some not
   
As a completionist my suggestion is to add to the nei the obtainable ones and delete/ create a recipe for the unobtainable 
ones, but its a mess to have hidden recipes and some that u can see are impossible to get. All the foods that u can see in the nei should be edible so u can complete them all (maybe terrawart is an exception if its impossible to keep the effect removing the nutritional value), and the quantum bread issue should be also adressed


Srry if my english is not the best and idk how to quote on github
Anyway lets keep dreaming about NEI showing 0 recipes when typing not*yet*eaten (Assuming there are no hidden recipes)
