### ISSUE TITLE
Indium Gallium Phosphide and HSS-G recipe conflict

### ISSUE THREAD

**Issue by Rubijox** [GTNewHorizons/GT-New-Horizons-Modpack#14639]
### Your GTNH Discord Username

Rubijox

### Your Pack Version

2.4.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Put all circuit 1 mixer recipes in the same input bus

### The Reality

Putting Indium Gallium Phosphide and HSS-G recipes in the same Circuit 1 input bus makes Vanadium-gallium instead and clogs up the mixer

### Your Proposal

Make vanadium Gallium/indium gallium phosphide require a different circuit,

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
this is not a recipe conflict but a multi-recipe overlap. so not something we would consider a bug.

In particular `Put all circuit 1 mixer recipes in the same input bus` is not something you should except to be able to do without issues.

**Comment by Iridium771394** [comment]
> In particular `Put all circuit 1 mixer recipes in the same input bus` is not something you should expect to be able to do without issues.
Then I'd like know why would even programming circuit exists?
Weren't they introduced to prevent multi recipe overlap?
WHY A "CIRCUIT 1" IS EVEN THERE
BECAUSE IT IS MADE TO ENABLE US TO PUT ALL CIRCUIT 1 RECIPE IN THE SAME BUS
pure stupidity

**Comment by glowredman** [comment]
@Iridium771394 Please remain calm and civil.

**Comment by Iridium771394** [comment]
> @Iridium771394 Please remain calm and civil.

OK sry

**Comment by chochem** [comment]
circuits are there to avoid recipe conflicts. meaning put in one recipe, get out another.

making sure there is no overlap in _any combination_ of 3+ recipes is not something we have done or a desire to do really. That part can easily be resolved by a better setup. While a recipe conflict (as described above) can not.

**Comment by chochem** [comment]
tbh, if you didnt even realize what they are for, that is kind of saying its working flawlessly. you would only notice when its not working.

**Comment by Iridium771394** [comment]
OK I got it
Since this is not you have done or desired to do, feel free to close this issue and tag as "work as intentioned" .
