### ISSUE TITLE
LCR displays error instead of processing scheelite dust to tungstic acid

### ISSUE THREAD

**Issue by cornymorty** [GTNewHorizons/GT-New-Horizons-Modpack#14642]
### Your GTNH Discord Username

dadzooks#4965

### Your Pack Version

2.4.1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I tried to process Scheelite Dust in the LCR into Tungstic Acid.

I am sure I did this processing already, but it was probably prior to upgrading to 2.4.1.

### The Reality

There was an error, stating the recipe was found, but it will not process.
![errr](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/146761525/1768d3ac-c7a5-405b-a0bd-f582f518119f)

### Your Proposal

Don't display error, and process instead.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
please post your logs. like fml-client-latest from the log folder

**Comment by cornymorty** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12784883/fml-client-latest.log)

**Comment by BlueWeabo** [comment]
Any other logs you can provide?

**Comment by BlueWeabo** [comment]
server as that would be where the machine is running its code

**Comment by cornymorty** [comment]
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12785146/fml-server-latest.log)


I restarted the server. Logged in, interacted with LCR to verify it was turned on, and then placed the HCl and dust into their respective inputs - checked the LCR for the error - removed one ingredient and error was removed. Logged out and turned off server, and this is the latest log. Hopefully it is small enough to find what you need.

Thanks for such swift replies btw guys did not expect that at all

**Comment by BlueWeabo** [comment]
is there a gregtech.log or a latest.log in the logs of the server? there doesn't seem to be anything wrong with the fml-server-latest.log

**Comment by cornymorty** [comment]
latest.log had nothing of interest, and there is a gregtech.log

I looked through it and didn't notice anything glaring - I will upload it if you think it could help

**Comment by cornymorty** [comment]
I tried to recreate the issue in singleplayer and it didn't give the error. I was able to use a single block machine to progress on my hosted map.

**Comment by BlueWeabo** [comment]
So it only happens in multiplayer? and it working on single blocks is expected as it doesn't use the same logic for them. But it is concerning that it works on singleplayer and not multiplayer.

**Comment by cornymorty** [comment]
Whatever logs might be applicable, I will provide from both client and server this evening. I'll do the same method of restart, get in and get an error, log off and shut down.

If there's anything else that might help, I'll do what I can.

**Comment by cornymorty** [comment]
Client:

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12786567/fml-client-latest.log)

[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12786569/GregTech.log)

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12786570/latest.log)

Server:

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12786574/fml-server-latest.log)

[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12786578/GregTech.log)

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12786580/latest.log)

[PlayerActivity.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12786582/PlayerActivity.log)


Again, the method to generate the logs were: 
1)  Restart server.
2)  Log in.
3)  Interact with LCR to verify machine is powered, states "no recipe available"
4)  Place dust and HCl into machine, states "recipe found, but had internal error"
5)  Remove dust, message changes to "no recipe available"
6)  Logged out, shut down server.
