### ISSUE TITLE
Add a new mod: Notes

### ISSUE THREAD

**Issue by kamenskyi** [GTNewHorizons/GT-New-Horizons-Modpack#14649]
### Your GTNH Discord Username

proventus569

### Your Pack Version

2.4.0

### Mod Name

Notes

### The Mod to Add

You can leave notes via the key

### Your Reason

You can add any notes, save them in a file on the server side or single-player. You can write any text and transfer it to the game

### Preliminary Investigation

There have been no problems with this mod.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Caedis** [comment]
Because this mod is client-side only, I could see this being added to https://gtnh.miraheze.org/wiki/Additional_Mods.

**Comment by bombcar** [comment]
As a “note” the in game solution is the clipboard - but it doesn’t provide the simple ease of an out of band tool. 

Though it can be left for other players.

**Comment by kamenskyi** [comment]
https://www.curseforge.com/minecraft/mc-mods/notes
