### ISSUE TITLE
Low Power Laser Pipes not connecting to a Low Power Laser Hatch

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/GT-New-Horizons-Modpack#14659]
### Your GTNH Discord Username

ipielover

### Your Pack Version

2.4.0.0

### Your Server

Delta

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

I'm trying to use the Low Power Laser Pipes to connect a Low Power Source Hatch to a Low Power Target Hatch
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/9349f0b9-ca21-48b7-99c9-cdd18c329713)

### The Reality

After painting the pipe and the hatch correctly to the same colour, using the wire cutter on the low power laset pipes wouldn't connect them.

### Your Proposal

If the pipe connection is bugged, please fix them.
If the intention to not use them, please put a tooltip on the item and remove the following line in the quest book.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/ca1d4113-8d27-4b6e-81e8-851d2daadf06)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by jude123412** [comment]
Can confirm this still affects 2.6.1 and its quite annoying, to work around this is to connect the low power laser pipe to an air block then place the laser hatch. Like I said not perfect but could do with a fix to make it more convenient
