### ISSUE TITLE
NBT error when AE2 pattren uses NEI automatic filling

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#14650]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

gtnh-nightly-2023-10-01+153

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

NEI automatically fills the Pattren terminal with the correct items and NBT

### The Reality

When automatically filling a recipe with multiple NBTs and its own battery capacity, it can cause errors in the NBT of the filling material, sometimes accompanied by stacking errors. Like the recipe of Chaotic Capacitor Bank and Lapotronic Supercapacitor. Please note that this error only occurs when automatic filling items such as Extreme Crafting Table are stacked together, or when non stackable items with NBT are stacked multiple times in the same grid in the assembly machine (Lapotronic Supercapacitor). If such items of the automatically filled recipe are stacked properly in the recipe (Charging Lapotron Crystal)

### Your Proposal

Make the nbt of automatically filled items correct

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
Need to specify which terminal, ae2 or ae2fc
