### ISSUE TITLE
Adjust the Extreme Air Intake Hatch to the same speed as the Reservoir Hatch

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#14654]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.4.0

### Your Proposal

Adjust the Extreme Air Intake Hatch to the same speed as the Reservoir Hatch

### Your Goal

When using air to produce radon or Liquid Air, due to the large amount required, it usually requires a lot of Extreme Air Intake Hatch. Adjusting the speed of air collection to be consistent with Reservoir Hatch can reduce many unnecessary delays

### Your Vision

Reduce lag caused by air collection (and no longer require a wall filled with Extreme Air Intake Hatch and pipes)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
maybe a higher tier one that is faster?

**Comment by JodieRuth** [comment]
> maybe a higher tier one that is faster?

The Extreme Air Intake Hatch is already a Level 2 (and highest level) Air Intake Hatch, with a speed of only 8 times that of the Air Intake Hatch, but its cost is far more than that. The speed of Extreme Air Intake Hatch is still far from enough

**Comment by chochem** [comment]
yea so lets make it 4 tiers with 8x each or something like that.

**Comment by JodieRuth** [comment]
> yea so lets make it 4 tiers with 8x each or something like that.

Well, I don't think the performance of each layer * 8 is as good as that of Reservoir Hatch, and it's not reasonable to pay a lot of ZPM (or higher level) circuit boards for some air

**Comment by JodieRuth** [comment]
> the meaning is to not having this hatch ticking every tick, to reduce server load. for example, used to be a 1000l hatch, ticks every tick, so 1000l/t, we change it to a 1000,000l hatch, ticks every 1000t, still 1000l/t. It is NOT about BUFF.

2000000000 mB of air in 5 seconds is obviously better, and it also eliminates the unnecessary cost of paying for some air

**Comment by chochem** [comment]
> the meaning is to not having this hatch ticking every tick, to reduce server load. for example, used to be a 1000l hatch, ticks every tick, so 1000l/t, we change it to a 1000,000l hatch, ticks every 1000t, still 1000l/t. It is NOT about BUFF.

jodie was very clearly asking for a buff ;)
but yea, either higher tier variants or a larger buffer with less often ticking (at same effective speed) should resolve things.

**Comment by JodieRuth** [comment]
> > the meaning is to not having this hatch ticking every tick, to reduce server load. for example, used to be a 1000l hatch, ticks every tick, so 1000l/t, we change it to a 1000,000l hatch, ticks every 1000t, still 1000l/t. It is NOT about BUFF.
> 
> jodie was very clearly asking for a buff ;) but yea, either higher tier variants or a larger buffer with less often ticking (at same effective speed) should resolve things.

Obtaining 8000mB for a 2tick or 2000000mB for a 2000tick is essentially the same and won't change anything. In order to achieve higher speed, many, many Extreme Air Intake Hatches are needed, just like the previous Reservoir Hatch

**Comment by miaowwwwww** [comment]
my bad, he is indeed asking for a buff

**Comment by Divran** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1485728/7dc4ce48-7768-49f3-b855-b4a28f563d25)

The tier 2 hatch is gated so far back that the setup in the image becomes very common. Even if you can afford it, it's just not powerful enough to be worth spending the resources on the tier 2 hatch until you're one or even two tiers higher than that. This is bad for tps. I've not done any comparisons but it wouldn't surprise me if a PA full of compressors is faster than an equivalent resource cost of either tier 1 or tier 2 hatches while using less TPS. 

I'd like to see the current speed of the tier 2 intake hatch be given to the tier 1 intake hatch (maybe increase its capacity and slow down the update rate to save tps but keep its throughput the same as tier 2), and then also the tier 2 intake hatch should be as fast as the water reservoir.
