### ISSUE TITLE
Making Trains Great Again

### ISSUE THREAD

**Issue by Psimekai** [GTNewHorizons/GT-New-Horizons-Modpack#14652]
### Your GTNH Discord Username

Energist

### Your Pack Version

2.4.0

### Your Proposal

Change Summary:

Long Distance Item and Fluid pipes now require active power at the inlet to maintain pressure. Each time they transmit a bucket of fluid, or a stack of items, an energy cost is incurred. For items, this cost scales with the number of items in the stack, starting at a nominal cost for 1 item and 64x that for a full stack, and the number of blocks distance transported. 

Long Distance Fluid pipes are now MV tier, requiring MV components to craft.

Long Distance Item pipes are now HV tier, requiring HV components to craft.

Edit:

After some testing, more should be done to help trains. Fluid pipes should obviously be the best way to transport fluids. There is no doubt about that, but item pipes really infringe upon the realm of trains.

Here are some ideas.

1) As it stands, item pipes can transfer x stacks per second across any distance while trains must travel. A train would need to transport x stacks for every second of travel it takes in order to equal the same volume per second. A simple way to enhance the ability of trains would be by reducing the transfer speed of pipes from x/ second to x/second/distance travelled. So a pipe with a transfer rate of 1 stack/ second, across 5 blocks would be 1 stack/5 seconds. The exact distance value could be tweaked. For example, it could be every 5 blocks instead. This would bring item transport pipes into the same scaling realm as trains. The benefit to trains being the ability to transport many stacks at a time.

2)Simply making item pipes more expensive would go a long way. That way, anything more than a few blocks or one chunk, it would be more economical to use trains. Item pipes  should be much more expensive than fluid pipes of the same tier due to their magical ability to transport items the way fluids are transported.

3) In order to transport items, they must go through an item transport packager. This block is the only thing that can export into  item pipes. There must be a packager on both sides (One to pack and one to unpack). It takes time and energy to package a stack for transport. 
. 

### Your Goal

Trains and rails are overshadowed by more powerful options that are too cheap and easy to use. These changes, simple in nature, give trains more economic viability, especially in the early game.

### Your Vision

Trains and rails open up many logistical opportunities. They are fun to use and can be rewarding if done properly. These changes make long distance pipelines more challenging and expensive to use, opening the door for lower cost rail systems.

Normal item and fluid pipes are fairly well priced compared to rails, but long distance pipes are clearly too cheap and simple to use for the vast capability they provide. This change would greatly incentivize the use of rails without requiring significant modification to the game.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
As i mentioned in another issue, this should be combined with making rail related recipes easier and more convenient in order for the whole plan to work. This initiative shouldnt feel like taking away the convenient option from early game players leaving them with the one that causes suffering, but rather, as presenting them with the opportunity to play around with an up to now neglected part of the pack. 
Some recent additions with the intent of increasing "QoL" have had a huge effect on early game balance and not always in a particularly well thought out way.

**Comment by Psimekai** [comment]
> As i mentioned in another issue, this should be combined with making rail related recipes easier and more convenient in order for the whole plan to work. This initiative shouldnt feel like taking away the convenient option from early game players leaving them with the one that causes suffering, but rather, as presenting them with the opportunity to play around with an up to now neglected part of the pack. Some recent additions with the intent of increasing "QoL" have had a huge effect on early game balance with not all of them feeling as if they were intended.

Yes, rails should be the cheapest way to transport fluids and items. I think a simple way to make them more cost effective would be to tweak the recipe output for wooden ties. If the output were doubled, that would go a long ways, getting 2 ties per bucket of creosote.

I do like having some of the more advanced elements of a rail system having a steeper price as mentioned in the other issue ( I appreciate your help coming up with these ideas).

Perhaps the cargo manager and the railcraft loader/unloader recipes can be swapped. IMO, the cargo manager is too expensive right now, and the unloader/ loader too cheap. I also do think the unloader/loader should use an item filter if only because right now it seems like a loophole around the item filter being an important automation milestone.

**Comment by Rika-TH** [comment]
Jesus, guess atleast it makes sense for items to be HV if they're gonna have a cost like that, long distance item pipes are also meant to help with lag, personally I'd just cease to use em and use basic pipes or wait till titanium to start AE

**Comment by vovaksenov** [comment]
You usually cant use basic pipes to get oil from many chunks over. Waiting until titanium generally also would not make sense, since we are talking about multiple tens if not a hundred+ hours of gameplay it takes for most to get through HV. If introduced in early HV-late MV, the long distance pipes still have a good use while leaving the early early game for the rebalanced rail.

**Comment by Rika-TH** [comment]
But what about before HV, imo late X tier may aswell be X+1 tier

This issue seems to also want nerfing of item / fluid pipe recipe, whether that is by complicating or weakening them, you still have a lot of things that rely on them (ignoring that anything past recipes is also gonna be a potentially big breaking change)

For fluid you'd HAVE to have exceptions, steam exists after all

For items still, if you add anything to the recipe it's now much worse as they are so simple on purpose, if they can't be extruded then they will barely be usable, they're already somewhat undesirable anyway as early game the only "good" ones are more pricey

Rail as a whole is also going to be more laggy and already has issues with it (chunkloading, lightning, mobs, etc) it's also clunky and buggy (I have a solar cart set to mine redlon as I decided that was actually the best way in LV-MV ish and it requires a player right-click every few in-game days or one day if the night lasts more than 20 seconds)

My final thing here is that having rail become the defacto early game just doesn't seem feasible nor really fun for a lot, while also implementing breaking changes, the most you could do is cheapen rail stuff to make more people try it out and otherwise stick to using it for your own challenges, early game is already meant to be mostly set (think that's moreso progression, but this would be a pretty big change)

If it's not clear I'm against this personally as it's affecting fundamental stuff and is very over reaching

**Comment by Rika-TH** [comment]
Absolutely this
Knew there were some bad bugs but not that bad
Make trains great by buffing them, they'll still maybe be irrelevant, but that doesn't stop you using em, they have their niches even now imo

**Comment by Psimekai** [comment]
I appreciate the discussion on this subject .

If the idea as posed seems overreaching, that is not the intent. Rather,
it's to see rails fill a space similar to that of real world industry.
Namely, the transportation of goods.

I whole heartedly agree that rails should not step on the toes of fluid
pipes, which are perfectly sensible best in class transportation for fluids.

For items, however, it seems that trains should have a place to themselves.

Lag is admittedly not an issue for me as I play on a small private server.
To that, I have no opinion. If it's a big enough issue that new tools were
created to avoid, I understand.

Based on this discussion, I think the best option is # 2. Making item pipes
more expensive relative to trains allows for both. Imo, the convenience of
item pipes over rails should come with an added cost.

**Comment by Psimekai** [comment]
Appreciate the feedback.

What are your thoughts about simply making item pipes a bit more expensive
to make the use of trains slightly more enticing?

Also are you opposed to any changes to long distance pipes or just these
changes?

**Comment by mitchej123** [comment]
The long distance pipelines were put in because they only require the two endpoints to be loaded.  I'm opposed to pushing them later because it was done for a very specific reason on servers.

As mentioned, if you enjoy rails/trains, are ok with the bugs, and want to make them more available - by all means.  I've seen server owners who hate rails, who love them, and everything in between.  For something like this, I don't think adjusting the balance of other things early game should be done because a subset of people prefer an alternative.  If the rails are currently too expensive, or tiered too late, I have no issue with that being adjusted in isolation, but I'm not a fan of any changes to the long distance pipes or other options to "make them more enticing".

**Comment by Psimekai** [comment]
I think the simplest way would be to tone down the extreme benefit of item
pipes. This could be achieved by making them slightly more expensive.

Based on this conversation, I would reframe my suggestion as follows.

Leave long distance item pipes as they are mechanically, but slow down
their rate of transfer.

Mathematically if I could transport one stack of items every  4 seconds by
a pipe, I would need to have a train able to carry one additional stack for
every four additional seconds it takes to get to its destination to keep
up. This seems like a simple timing change to make rails and trains more
enticing.

Secondly, I would propose  making item pipes more expensive relative to
fluid pipes. This gives people the option of spending a little bit more for
the great benefit of the magical item pipe without necessarily pushing it
out of the way. Conceptually, this could be achieved by making item pipes,
one of the capstone achievements of each tier, requiring the capstone alloy
of that tier to create.

No changes would need to be made to the ability to extrude pipes. I
understand that automation of pipe crafting is important. I am suggesting
just making the ingredients themselves a little bit more costly.

**Comment by mitchej123** [comment]
I don't see the problem that is being solved by the proposal of adjusting item pipes. They're currently limited by the conveyors/speed you can push into them.    

I don't personally thing comparing them to rails (a much laggier and buggier form of transit) is not applicable.

**Comment by Impos913** [comment]
Don't touch pipes, do whatever you want to trains

**Comment by Psimekai** [comment]
I put forward the idea specifically to integrate rails a little bit more
directly into the production chain. I don't see why rails should be
optional when item pipes and fluid pipes are not.

Seems to be a bias against trains as sort of relegated to optional status
when just about everything else is a requirement to progress.

If that is the case, I question why we even have the rails to begin with?
As it stands, there is no real advantage to using them. They don't provide
anything more than a trap option.

There is also a quest book chapter almost entirely dedicated to using rails
for automation. It seems a little bit misleading to entice the player to
use rails, but then subtly show them that they are irrelevant.

Would it be so bad that rails filled a niche? Are they really any harder to
work with than cantankerous multi-blocks with maintenance issues and other
quirky intentional misbehaviors?

Trains seem to be a very greggy tool that is unfortunately underutilized
and appreciated. It's a system that rewards creativity and unique setups
rather than magical one block solutions to all problems.

**Comment by mitchej123** [comment]
I do not want trains to be anything other than optional.  If you want to use them, great.  If you don't... don't.

They're bad for TPS.  They're buggy - they random disappear.

Please go search discord history for 0lafe's railworld run and see all of the bugs that popped up.  Most of them would require invasive forge changes that nobody wants to do.


Pipelines will not be nerfed without a good reason that include math, and the reason cannot be "because I want trains to be required"

**Comment by Psimekai** [comment]
Okay those are fair points. I've never had these issues but I suppose the
mod pack would not be designed as it is if they were not a big enough
concern.

I think the math is simple. Enough. Items can travel in a certain quantity,
across a certain distance, in a certain amount of time. Tweaking any of
these three variables without more than changing a variable is certainly
possible.

However, it seems there is simply no desire here to see trains shine in
that way.

If nobody has a problem with trains being underutilized, then so be it.

Personally, I like using trains so I put forward the idea of further
integrating them into the supply chain. Obviously if the game itself cannot
properly handle trains then I understand why they are relegated to optional
status.

That is unfortunate. Trains are such a cool and very greggy system.

**Comment by Glease** [comment]
We had a lot of prior discussion on how to make trains better. The final conclusion is we cannot get past the technical difficulties and eventually lead to the introduction of long distance pipelines

**Comment by Psimekai** [comment]
Ok thanks.

This is by far the best modpack I e played, and I'm happy to be able to
discuss it's development here. I appreciate everyone's input here.

**Comment by Psimekai** [comment]
> I do not want trains to be anything other than optional. If you want to use them, great. If you don't... don't.
> 
> They're bad for TPS. They're buggy - they random disappear.
> 
> Please go search discord history for 0lafe's railworld run and see all of the bugs that popped up. Most of them would require invasive forge changes that nobody wants to do.
> 
> Pipelines will not be nerfed without a good reason that include math, and the reason cannot be "because I want trains to be required"


A mathematical standard should probably be based on trains even if trains aren't considered for reliability and performance reasons. This would atleast allow for trains to have a theoretically useful value.

Consider transfer volume per unit time as stacks per second across a given distance. Let's say a train travels for 40 seconds, and delivers 40 stacks. It's effective volume per time is 1 stack per second. A pipe, with a 1 stack per second limit, would have the same transfer rate.

IMO, the train transfer rate should be the maximum in order to give trains the greatest transport volume metric. It's there if people want to use it, but they don't have to if they don't want to. 

Conceivably, no pipe should transport items across distances more effectively than the best train. 

A heuristic would have to be chosen for distance in order to make this work.  This distance would probably be the long distance item pipe minimum distance, since trains really begin to lose out to those, and no one wants to see those rebalanced apparently. So let's say that heuristic is 64 blocks.

So if a maximum payload for a train is 40 stacks, and the time it takes to cross 64 blocks (the standard set by long distance item pipes), would determine the maximum that a non long distance item pipe should be able to transfer. 

Arbitrary numbers here, but let's say it moves 4  blocks per second. That's 40/16 stacks per second transfer volume. A pipe would need to transfer less than 2.5 stacks per second to not overshadow trains.


Anyways, I'm done here. Thanks for engaging with me on this. If any of my thoughts are useful, in full or in part, please consider them.

**Comment by bombcar** [comment]
The thing trains are best at isn't really emphasized early on - *player* transportation. 

Make rails a bit cheaper or make it easier to get lots of them, and use them for moving players and items incidentally  - repair trains, new build trains, etc.

They're just not reliable enough to be part of a automated factory unless you like that kind of challenge.

Maybe item pipes could be designed to have a rail on the top and you could drive trains on them.
