### ISSUE TITLE
Large Essentia Smeltery does not consume EU at all

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#14656]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

normal operation

### The Reality

It completely does not consume any EU, replacing the energy hatch has no effect, and there is no laser mode debug generator or anything else

### Your Proposal

Correct consumption of EU

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
yes, had this in zeta, it even says generating xxx eu in waila.

**Comment by Rika-TH** [comment]
Debug power generator has a laser mode I believe, might be weirdly titled in the Chinese localisation?

**Comment by JodieRuth** [comment]
> Debug power generator has a laser mode I believe, might be weirdly titled in the Chinese localisation?

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/1675517d-1b77-46aa-9003-5968b27cf0d8)
It seems normal, but its ability to transport EU to Laser Target Hatch has indeed been enabled

**Comment by Rika-TH** [comment]
Nice nice 👍
