### ISSUE TITLE
EBF does not consume Yttrium Oxide Dust when processing Flawed Cubic Zirconia recipe

### ISSUE THREAD

**Issue by cornymorty** [GTNewHorizons/GT-New-Horizons-Modpack#14653]
### Your GTNH Discord Username

dadzooks#4965

### Your Pack Version

2.4.1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

As explained in title. I noticed that I was not losing my yttrium oxide dust, it just stays chillin' in the input bus.

### The Reality

I get some material for free.

### Your Proposal

Consume yttrium oxide dust as expected.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
Why do you think that it should be consumed? its catalyst, no?

**Comment by cornymorty** [comment]
Combining 10x of one dust and 1x of another dust, and only one dust gets consumed does not make sense to me. How would 1 pile of dust be good for making 1m crystals? If it was consumed, and then given back as a byproduct that can be recycled back into the 1 dust necessary to be a catalyst, I could see that making sense.

**Comment by lordIcocain** [comment]
you forgot 20kl of oxygen

**Comment by cornymorty** [comment]
I actually hadn't noticed there is an "NC" marking on the yttrium oxide dust on the recipe - I'll close this 'issue' but feel free to steal my suggestion for consuming the dust and providing a byproduct to deal with (yttrium slag, which can be processed into carbon dust and yttrium dust, is one example I thought of).
