### ISSUE TITLE
Suggestion: Time Dilation Field Generator

### ISSUE THREAD

**Issue by NotAPenguin0** [GTNewHorizons/GT-New-Horizons-Modpack#14663]
### Your GTNH Discord Username

notapenguin 

### Your Pack Version

2.4.0

### Your Proposal

I want to propose a new endgame multiblock: The time dilation field generator (TDFG for short for now). 

The TDFG works similarly to a beacon in factorio. It creates a radius in which machines are sped up, at the cost of power.

This multi aims to mitigate two problems:
- Lategame multiblock spam (cfr. shirabon large plate extruding, etc). Spamming the same multi over and over is not interesting gameplay. 
- Lategame TPS. As also shown in factorio megabases, speeding up existing machines should have significantly less TPS impact than copying the same machine many times.

Some additional notes/details:
- Obviously this would be tiered pretty late game (UIV/UMV?)
- Some multiblocks may need to be blacklisted for balance reasons
- A machine can only be affected by a single TDFG. If it is in range of multiple TDFGs, it overloads and shuts down.
- Using the upgrade block system MuTes will have, the range and speedup factor can be tweaked with tiered upgrade blocks. This way there is an additional trade-off to make between having larger ranges or faster machines.
- Operating a TDFG should naturally not be free. It can cost a lot of power, or consume some catalyst while running.
- On the other hand, there should be an incentive to use the TDFG over simply adding a bigger laser hatch on the machines you want to speed up. Perhaps using the TDFG can use less power overall if you use it on multiple multis (this would also incentivise trying to pack as many machines as you can into the TDFG radius)?

None of this is finalised, I mostly want to gather some feedback on the idea to see if it’s worth spending time creating a prototype for it.

### Your Goal

As described above, there is nothing fun about copying the same setup over and over again. Adding a new puzzle to solve instead (how to optimally configure my TDFG?) is much more interesting in my opinion.

### Your Vision

To add more varied gameplay elements to the pack.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
if this is a tick speedup like WA then it probably makes TPS worse and not better, we are more interested in removing that kind of stuff, not adding. So this would only work if its fully integrated in the machine logic.
Personally I would say we rather work on the multis themselves though.

**Comment by NotAPenguin0** [comment]
I'd try to specifically not make this work like WA to avoid TPS issues yeah. Integrating it in machine logic seems like the better way to implement this. I figured since we are making new multis anyway, adding support for logic like this is not too much of an additional hassle.
