### ISSUE TITLE
Rock Salt and Salt tools 

### ISSUE THREAD

**Issue by Minepolz320** [GTNewHorizons/GT-New-Horizons-Modpack#14662]
### Your GTNH Discord Username

Minepolz320

### Your Pack Version

2.3.0

### Your Proposal

Nerf or disable Rock Salt / Salt tools  
because it is illogical and unrealistic 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/42765118/6dff743c-8a82-4727-b135-744ed0389331)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/42765118/a1b4706e-646d-4316-a1f6-1d70bf5b3b69)

they are stronger than iron (durability)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/42765118/d2bad19f-35c6-467e-b25d-47e55d8010da)

### Your Goal

This is to make GTNH a little more realistic and logical

### Your Vision

For science! 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Rika-TH** [comment]
Iirc they're also only really accessible past when their durability is useful (might be thinking of electric wrench) as I have thought the same thing but opposite angle before

**Comment by Minepolz320** [comment]
I'm thinking of keeping them around the clay-compound level.
