### ISSUE TITLE
A Bee For Neodymium and Europium?

### ISSUE THREAD

**Issue by Iridium771394** [GTNewHorizons/GT-New-Horizons-Modpack#14669]
### Your Pack Version

2.4.0-RC2

### Your Proposal

I would like a bee for Europium production.
Since a higher tiered material e.g. americium can be produced by bees , why not europium?
I DO know Vega B bees can produce vega v stardust that can be centrifuged into europium but it's too inefficient.
My proposal:
Redstone + Indium(for preventing fusion skip, can be any other metal) = Rare Earth
Rare Earth + Iron = Neodymium
Neodymium + Hydrogen = Europium (With a block of Europium below the apiary or mutatron)

Europium bees products:
Prod:Eu2O3 dust/Neodymium comb (preventing fusion skip)
Spec:Europium comb(IAADDS Only)

Processing:
For Neodymium comb 1152 Phthalic acid per 4 combs?
For Europium ones 2304 Phthalic acid per 4 combs?

### Your Goal

To mass-produce europium without stacking fusion reactors.

### Your Vision

Americium is higher in tier than europium but can be mass-produced by bees.
Both americium and europium are very annoying to be made with fusion reactors.
Europium ores are also gone with updates of the pack.
Add a europium bee is a QoL improvement I think?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [x] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LazyFleshWasTaken** [comment]
I disagree with indium for rare earth, that gates it unnecessarily, it'd be better with something else, maybe osmium since osmium also replaces zinc for indium?

Regardless, for neodymium rare earth + moon would be better, and for europium I recommend doing it the same way sunnarium is bred and not gating it to mega apiary. So breed on fusion coil or coil block and produce europium in perfect temperature, but at a lower rate.
