### ISSUE TITLE
CuttingFactory with CraftingInputBus installed doesn't work

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#14677]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.4.0.0

### Your Server

private server and single

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

I built up an AE2 craft system where craft items are supplied to CuttingFactory using CraftingInputBus and only lubricant is supplied separately.
And then use it.

### The Reality

Don't work.
![2023-10-09_06 55 47](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40425798/7690f3e9-e19e-41dd-943e-7350dc5d6bd8)

CraftingInputBuffer is confirmed to work

### Your Proposal

Fix it.
I haven't checked, but if you do the same thing with IndustrialArcFurnace or EBF, it might not work.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by King65868** [comment]
Separate fluid from the crafting input bus doesn’t work, you need to use the crafting input buffer if the recipe needs a fluid

**Comment by yukieiji** [comment]
Do I need to do so even if no fluids are registered in the crafting pattern?

**Comment by King65868** [comment]
There is lubricant still required for the recipe, even though you didn’t add it to the pattern, so still required

**Comment by yukieiji** [comment]
Lubricant is supplied separately using an input hatch
I believe that ME Interface + Input Bus + Input Hatch and Crafting Input Bus(Item) + Input Hatch will have the same behavior.

**Comment by King65868** [comment]
They don’t have the same behavior, crafting input bus/buffer both have separate inventories that don’t interact with any input hatches on the multiblocks to prevent conflicts. In this case this means crafting input bus doesn’t work with the cutting machine since they need a fluid input

**Comment by yukieiji** [comment]
I see what you mean.
I was mistakenly thinking that since it was named 'Input Bus', it could be used in the same way as Input Bus.

It might be a good idea to change this name(Crafting Interface Bus?) or adding a detailed description to prevent this kind of thing.

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/15bafc35-9d8f-46e5-baea-d8702cc00fd8)
tooltip seems fairly clear to me.

**Comment by yukieiji** [comment]
I misread `patteerns including fluids` as referring to `AE2 Fluid Crating pattern`(purple)
