### ISSUE TITLE
Make Quantum armor disable super/quantum tank debuffs

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#14673]
### Your GTNH Discord Username

pxx500

### Your Pack Version

Stable

### Your Proposal

Quantum armor gives player many abilities which suggests it's some kind of an exoskeleton, it makes sense that a lategame armor would delete debuffs from carrying tanks.

### Your Goal

Stop annoying debuffs in the lategame

### Your Vision

Nice QoL change that quantum armor (and similar) users would enjoy

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by BritishCynic** [comment]
+1, would be great QoL change

**Comment by vovaksenov** [comment]
Maybe tying it to spacesuit would be a good idea in terms of broader support, now that all the good armor has spacesuit functions.
