### ISSUE TITLE
Logistic Pipes Mod Request Table

### ISSUE THREAD

**Issue by KyriaThor** [GTNewHorizons/GT-New-Horizons-Modpack#14682]
### Your GTNH Discord Username

kyriathor

### Your Pack Version

2.4.0

### Your Proposal

- [x] The Requesttable has an integrated Crafting Grid, but the Quests don't accept crafted items from there as crafted, only as retreaval and you can not shift-rightclick to craft a whole stack, you need to click per item, so it is annoying to craft bulk products. Maybe this could be changed. 
- [ ] maybe there could be another button to reset the set request amount. Right now if you want to reset the request amount, you either have to click -/--/--- several times (especially if you requested a high amount of bulk) or exit the table and reenter the menu.

### Your Goal

Crafting bulk is very annoying with that Logistic System, if you use it as an ME-Alternative in the Early Game and crafting Questitems just to realize you have to craft it another time, as he did not register it is annoying as well.

### Your Vision

it would make the Logistic System more viable for early to mid game especially for Bulk Crafting, as that is often needed. (Just take torches as example, you dont just want 1 or 2, but Stacks of that)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
huh why wasn't this closed

**Comment by Glease** [comment]
oh there was 2 requests..
