### ISSUE TITLE
Advanced blocking card doesn't work when accepting items from transvector interface

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#14685]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

Nightly 2nd October

### Your Server

solo

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I have this setup : 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57050655/33cb8b94-14cb-4314-b0a3-4a9f4cc5ac74)
On the left the p2p dual interface contains patterns for my assembly lines and is pushing into a dual interface that has an advanced blocking card. When I place the patterns in the p2p at the top (directly on the interface), the advanced blocking is working and it's only pushing recipes one by one. 
I expect it to do the same thing when I place patterns in the p2p below that is facing the transvector interface since the transvector interface is linked to the dual interface right above.

### The Reality

when placing patterns in the p2p on the transvector interface, it doesn't respact the blocking mode and it just push every recipes at once

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment]
As a workaround u don't need the transvector, just use another dual interface
