### ISSUE TITLE
nonsense temps

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#14689]
### Your GTNH Discord Username

lily_blanc

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

temperatures for liquids make sense

### The Reality

they don't, attached is a list of fluids whos temp is 1 character generated by dumping fluids in NEI and running
`grep '.*,.*,.*,.,.*,.*,.*,.*,.*,' ./fluid.csv > ./1characterfluidtemps.txt` (beautiful I know)
(the first number is the temperature)
[1characterfluidtemps.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12872943/1characterfluidtemps.txt)
some of these can be argued correct, but a few easy ones to say don't make sense polystyrene, kevlar, RAISIN JUICE

here's the original dump aswell
[fluid.csv](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12872977/fluid.csv)

### Your Proposal

fixma

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
I'm for just to add some more pipe requirements and not use ptfe/pbi for everything like I am rn.

**Comment by Rika-TH** [comment]
> I'm for just to add some more pipe requirements and not use ptfe/pbi for everything like I am rn.

without looking too hard most of these look to be that they should be either insanely hot or probably just around or below plastics?

**Comment by Rika-TH** [comment]
you could probably modify my command to find some other temps, think regex also has ranges which you could use? the . without an * afterwards is the temp so just replace that with whatever logic you want and keep inbetween the commas and it should be fine

**Comment by GDCloudstrike** [comment]
spacetime and its derivatives being 0K is sort of canon now (spacetime is used as a coolant in multiple places), so those can stay the way they are imo

**Comment by Connor-Colenso** [comment]
We're kinda at a point that certain materials probably just shouldn't display temperature as it doesn't really make much sense.

That said I do like spacetime being 0K even if a little whack physics wise.

**Comment by AbdielKavash** [comment]
Temperature is an emergent property of a large group of particles. Even something like a single atom doesn't have a temperature that we can talk about in a physical sense. So in that direction I agree that stuff that is not really atomic matter anymore (spacetime & co) doesn't need (and maybe shouldn't even have) a temperature tooltip.

On the other hand for realistic(-ish) materials yes this should be hopefully an easy fix.
