### ISSUE TITLE
Multiblock Ore Drill gives impure/crushed stone dust when on moon

### ISSUE THREAD

**Issue by cornymorty** [GTNewHorizons/GT-New-Horizons-Modpack#14694]
### Your GTNH Discord Username

dadzooks#4965

### Your Pack Version

2.4.1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Set up a multiblock ore drill on the moon, ore is nice but I wanted to get moon stone dust.

### The Reality

I'm getting stone dust/impure stone dust.

### Your Proposal

Give dust appropriate to the surface being mined when using multiblock ore drill.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by cornymorty** [comment]
Moon Rock/Dirt/Turf?

**Comment by Pxx500** [comment]
> Moon Rock/Dirt/Turf?

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/12a026fb-5e1e-4b33-b532-77dc449fc917)
Those are the variants.
Also, why do you think this will be useful? Any particular situation or just for consistency?

**Comment by Dream-Master** [comment]
if we want it we need to add more many planets some ore variants. We will flood gt item ids by 10000 or more

**Comment by cornymorty** [comment]
Logically, it made sense that if I put the drill on the moon, I would get moon stone dust. Part of the reason to use that drill is it pre-macerates, so I'm saving a step towards my tungsten production by not having to process moon rock/dirt/turf before centrifuging. But the drill isn't even providing the material I'm after.

If I use single block miners, I do not get this material on the moon, but moon rock/dirt/turf. This should be the same for the multiblock, imo.

**Comment by querns** [comment]
I talked about this a bit in #github-discussion . Rather than adding new ore variants, we could have a small check in the MBM code to substitute the returned stone dust for a planet stone.

**Comment by Dream-Master** [comment]
> I talked about this a bit in #github-discussion . Rather than adding new ore variants, we could have a small check in the MBM code to substitute the returned stone dust for a planet stone.

you mean get moon turf or dust out of stone dust at some ev centrifuge recipe ?

**Comment by querns** [comment]
> > I talked about this a bit in #github-discussion . Rather than adding new ore variants, we could have a small check in the MBM code to substitute the returned stone dust for a planet stone.
> 
> you mean get moon turf or dust out of stone dust at some ev centrifuge recipe ?

More like this: after the MBM mines something, it replaces any stone dust that it mined with a stone dust relevant to the dimension it's in before it outputs the items.

**Comment by Dream-Master** [comment]
if this is possible why not. feel free to add it :)
