### ISSUE TITLE
Allow Selecting No Circuit in the Circuit Selection GUI

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/GT-New-Horizons-Modpack#14692]
### Your GTNH Discord Username

alongstringofnumbers

### Your Pack Version

2.4.0

### Your Proposal

Allow selecting No Circuit in the config circuit selection GUI in machines

### Your Goal

This would make it easier to clear any config circuit from a machine/input bus. Currently you have to select circuit 1, and then change it to no circuit with an additional click. Being able to go directly to no circuit will save that additional click, making it easier to clear any config circuit.

### Your Vision

This would make it easier to clear any config circuit from the circuit configuration slot in machines/input buses

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Yeah shift+right click exists. Tooltip explains it.
