### ISSUE TITLE
I am trying to join the server and the game crash

### ISSUE THREAD

**Issue by elpalermofut** [GTNewHorizons/GT-New-Horizons-Modpack#14695]
### Your GTNH Discord Username

Palermo8033

### Your Pack Version

GTNH 2.3.2

### Your Server

CraftersLand

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

Nothing, i am just new in the launcher, i tried to join this modpack server and i cant join

### Crash Report

The crash report is the following: 

---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-10-12 20:06:35 CEST
Description: Ticking screen

java.lang.NullPointerException
    at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5107)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I uninstalled already java and installed new version etc.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/147751850/96e30d65-dcd0-4fb3-9db6-35ca7427b29e)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
there is nothing here to go on. please post logs and let us know what launcher. but mostly logs.

**Comment by elpalermofut** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/147751850/3b6eeb29-d04f-44e0-a72a-275db4806810)
this is the launcher.
Logs:
[crash-2023-10-12_22.35.25-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12886889/crash-2023-10-12_22.35.25-client.txt)

**Comment by Dream-Master** [comment]
@elpalermofut i would update to 2.4.0
this error is a random one so i cant see a GTNH mod is involved

**Comment by Dream-Master** [comment]
if you on a server you need to convinced them to update to 2.4.0

**Comment by chochem** [comment]
> ![image](https://user-images.githubusercontent.com/147751850/274724796-3b6eeb29-d04f-44e0-a72a-275db4806810.png) this is the launcher. Logs: [crash-2023-10-12_22.35.25-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12886889/crash-2023-10-12_22.35.25-client.txt)

never even heard of that launcher before.

is the crash consistent or just a one-time? nothing in the crashlog stands out to me, nothing GTNH related. you could try us with the full log from your log folder, assuming your launcher has those.

**Comment by elpalermofut** [comment]
Is consistent but is only on the server, if i go into singleplayer, i dont have the problem, i will talk with the staff of the server.

Thank you for your quick response 👍
