### ISSUE TITLE
Questbook Description for ME Fluid Storage Cell incorrect

### ISSUE THREAD

**Issue by Data-Shark1** [GTNewHorizons/GT-New-Horizons-Modpack#14696]
### Your GTNH Discord Username

data_shark

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

The line of ME Fluid Storage Cells' descriptions should reflect that the cell that is asked to retrieve can only store 1 fluid type, and should say the correct amount of fluid that can be stored in the cells.

### The Reality

The quest description states (only in the 1k cell quest) that it can store 5 fluid types, when the quest item can actually only hold 1 type. Every fluid cell quest description also has the incorrect max storage capacity for the cell.

### Your Proposal

Description should say that it can store 1 fluid type, and the correct max capacity for that cell.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
sure but what *is* the max capa? nothing I can do on that front except just removing the lines I guess.

**Comment by Data-Shark1** [comment]
Apologies, I don't check my email as often as I should.
I believe these numbers are correct. I can open up a creative world and
test this afternoon to confirm.

**Comment by Data-Shark1** [comment]
I tested a majority of the cells and those numbers seem to be correct.
