### ISSUE TITLE
[DuraDisplay] does not show durability on Spool of Wire.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#14693]
### Your GTNH Discord Username

abdiel_kavash

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

To see the remaining durability on the Tinker's Mechworks Spool of Wire displayed in any way.

### The Reality

![](https://i.imgur.com/gh26euJ.png)

Other tools shown for comparison. I tried toggling various settings in DD mod options, but I can't get either a number or a bar to show for the spool.

### Your Proposal

Probably add it in the Gadget category?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
What is the Spool of Wire used for?

**Comment by Caedis** [comment]
Got it
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18713839/3e971961-6f0c-43de-95a4-2de0f61855e5)
