### ISSUE TITLE
Crashing on opening interface terminal

### ISSUE THREAD

**Issue by Team1Warlord** [GTNewHorizons/GT-New-Horizons-Modpack#14697]
### Your GTNH Discord Username

KOT_BHE_3AKOHA#7758

### Your Pack Version

2.4.2-170

### Your Server

private server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Actions

Opened with universal terminal iterface section and got crash of the server

### Crash Report

[crash-2023-10-13_17.12.59-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12896416/crash-2023-10-13_17.12.59-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miaowwwwww** [comment]
fixed in nightly (interface terminal still have some other bugs but at least no crashes now.)
