### ISSUE TITLE
Allow GT wrenches to open the conduit connection GUI with Shift-Left-Click

### ISSUE THREAD

**Issue by mM4ri** [GTNewHorizons/GT-New-Horizons-Modpack#14698]
### Your GTNH Discord Username

mMari_

### Your Pack Version

2.4.0

### Your Proposal

Shift-Left-Clicking a conduit (with a Yeta Wrench) with multiple connections opens this window, which allows you to choose the connection without looking directly at it.
![Conduit](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/125275951/965c95b2-d74d-40ea-ae00-4c0e0120b433)
GT Wrenches should also open this window. (And maybe fix the inventory/tank names if possible)

### Your Goal

I don't think many people use that feature because they don't want to have multiple wrenches in their inventory, so adding that for GT Wrenches would help a lot.

### Your Vision

QoL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Yes this would be especially appreciated by early game players i think

**Comment by Rika-TH** [comment]
I didn't even know this was a thing on the yeta so haven't bothered making it, this would be incredibly nice I've just today been getting annoyed having to dig holes for temp conduit setups
