### ISSUE TITLE
"There was error during rendering item. Please check log for details."

### ISSUE THREAD

**Issue by Rika-TH** [GTNewHorizons/GT-New-Horizons-Modpack#14705]
### Your GTNH Discord Username

lily_blanc

### Your Pack Version

2.4.0RC2

### Your Server

Private

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

(J21) typing "advanced" in NEI causes no issues

### The Reality

my first time typing it this session caused a massive stream of errors in chat, posted here to expose it
https://mclo.gs/cxHKyBH

### Your Proposal

fix any potential bugs (also the spelling on this error message)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cardinalstars** [comment]
Could you please give a line number to when these errors start? I see a large spam of something from optifine, but since I don't know exactly what you're talking about I can't tell which one is the issue.

**Comment by Cardinalstars** [comment]
Looks like a rendering bug when displaying items using NEI from adventure backpack. Could be wrong but at a glance that's what I'm seeing.

**Comment by bombcar** [comment]
Wasn't there a recent NEI/backpack fix I saw just come across the line?

**Comment by Cardinalstars** [comment]
> Wasn't there a recent NEI/backpack fix I saw just come across the line?

There was one for bookmarks that crashed you when the bookmark key was the same as the close backpack key. I'm guessing this is unrelated.

**Comment by Cardinalstars** [comment]
@Rika-TH If you have a chance can you get reproduction steps in a single-player world?
