### ISSUE TITLE
GT:NH 2.4.1 java 17 freezes on loading screen: "NO X11 DISPLAY 

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#14708]
### Your GTNH Discord Username

trainersnow

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Launch GT:NH 2.4.1 from MultiMC

### Crash Report

Java args used:
```
--illegal-access=warn -Djava.security.manager=allow -Dfile.encoding=UTF-8 --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens jdk.naming.dns/com.sun.jndi.dns=ALL-UNNAMED,java.naming --add-opens java.desktop/sun.awt.image=ALL-UNNAMED --add-modules jdk.dynalink --add-opens jdk.dynalink/jdk.dynalink.beans=ALL-UNNAMED --add-modules java.sql.rowset --add-opens java.sql.rowset/javax.sql.rowset.serial=ALL-UNNAMED
```

Ubuntu 23.04

Crash report (generated after I kill the instance from MultiMC): 
[Crash Report](https://paste.ee/p/HcoAk) after killing the instance from MultiMC
```
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by eigenraven** [comment]
Do you have XWayland installed on your ubuntu system? This looks like either an X11/XWayland installation issue or some incompatibility between your java version and your os.

**Comment by TrainerSnow** [comment]
I don't remember installing either of those, they may be shipped with ubuntu by default.
In `/etc/gdm3/custom.conf` `WaylandEnable` is set to `false`. 
M yjava version is a normal openjdk 17

**Comment by TrainerSnow** [comment]
Setting `WaylandEnable` to `true` doesn't solve this.

**Comment by bombcar** [comment]
can you try launching a stock version of Minecraft with that Java? Try 1.18 perhaps.

**Comment by TrainerSnow** [comment]
Launching 1.18.2 vanilla works without issues from MultiMC

**Comment by TrainerSnow** [comment]
Actually I just realized MultiMC uses jdk 19 not 17, when I switch that to 17 it works, for whatever reason that may be.
