### ISSUE TITLE
Crashes nonstop

### ISSUE THREAD

**Issue by 1kozaczek** [GTNewHorizons/GT-New-Horizons-Modpack#14709]
### Your GTNH Discord Username

a.lex

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Log back into game and it crashes after a bit

### Crash Report

[crash-2023-10-14_20.32.24-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12907902/crash-2023-10-14_20.32.24-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
I guess https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12696 wasn't fully fixed :(

**Comment by bombcar** [comment]
Voybe reports a similar crash 
[crash-2023-11-06_10.32.06-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13271546/crash-2023-11-06_10.32.06-client.txt) - the code seems to be shadowing (as it gets deep into evalex) - and the Expression$Tokenizer.class is present in the Jar at the expected area.

**Comment by Voybe** [comment]
[94fe1ab3-7399-4770-97c7-c1031a3b4bf9.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13272439/94fe1ab3-7399-4770-97c7-c1031a3b4bf9.zip)
Player file of the person the issue was occurring on

**Comment by ikickurmule** [comment]
Hi I am getting what I believe is the same issue when I open an inventory. Are there any fixes?

[https://mclo.gs/KE48w8V](url)

**Comment by chochem** [comment]
gonna close this in favor of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471
