### ISSUE TITLE
Patterns inside component assembly line

### ISSUE THREAD

**Issue by berta24** [GTNewHorizons/GT-New-Horizons-Modpack#14715]
### Your GTNH Discord Username

Berta24

### Your Pack Version

latest nightly 10-15

### Your Server

private

### Java Version

Java 20

### Type of Server

None

### Your Expectation

I saw many crafting werent' advancing, upon inspection i tought the pattern were wrong, but then i saw that the pattern are fine, the problem is the crib, showing wrong recipe in the slot
as you can see in the image below:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/25983005/bfddda0f-113f-484e-8a8b-abf00d5429cb)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/25983005/66f97602-7be9-4e07-bef5-65d3f8c28249)

### The Reality

it's not crafting anything because it gets stuck not knowing where to put the items, so items never get into the crib

### Your Proposal

make it like last version

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment]
Try breaking and replace crisb, It helped for me when crisb was storing old recipe instead of new one I placed

**Comment by berta24** [comment]
even replacing the crafting input buffer didnt solve the issue, had to redo all existing patterns to solve it.
they got bugged somehow with the update
