### ISSUE TITLE
Dark matter shards uncraftable

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#14717]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.4.0

### Your Server

Delta

### Java Version

Java 17

### Type of Server

Thermos

### Your Expectation

Complete the quests for the Mothership

### The Reality

The "Does it contain a black hole" quest requires two dark matter shards, one for each item of the quest. Unfortunately there is no recipe and the preceding quest offers a maximum of one - and that is as an optional quest reward.

This in turn means that the Artificial Gravity Generator and the Artificial Gravity Disruptor have very limited availability.

### Your Proposal

Recipes should be added, or the item should be replaced with something else in the dependent recipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GDCloudstrike** [comment]
You can find dark matter in the core of some mehen belt asteroids, maybe the quest could be updated with this info to avoid confusion.
![2023-10-16_22 22 06](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/93287602/76ee095d-6149-4af9-bafb-d5280c60a2f3)

**Comment by EnderProyects** [comment]
Based on this, it's annoying that you can't compress the shards together in one block, since it's an interesting block. ( shiny black caelestis)
