### ISSUE TITLE
Even huge AuraNode cannot supply Vis to LargeEssentiaSmeltery 

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#14710]
### Your GTNH Discord Username

yukieiji

### Your Pack Version

2.4.0.0

### Your Server

sp, private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

Set up length 7 LargeEssentiaSmeltery with Grandmaster Essentia Diffusion Cell and supplied Vis(At nodes where everything is over 100 ctVis).

### The Reality

Node too smalling is displayed and continuous operation is impossible.

### Your Proposal

I would like to see the logic to get Vis fixed or be able to create a strong Vis from EU.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by JodieRuth** [comment]
In fact, the more powerful the Essentia Diffusion Cell used and the longer the structure, the more cv is needed for LES. Based on your setup, I think you might need an Aura Node with everything over 160.

**Comment by yukieiji** [comment]
To make an AuraNode that supplies more than 160 vis, it would require an Aspect of more than 25600 by simple calculation.
To be honest, I think it is too poor cost performance to make such an AuraNode....

**Comment by JodieRuth** [comment]
You can use bees or Node Randomization, they are both great and cost effective (Node Randomization requires Crystal Studded Cosmic Neutronium Wand)

**Comment by yukieiji** [comment]
I haven't tried that technique(Is there no  Node Randomization in v2.4.0.0?), but I suspect it would take an enormous amount of time even with those.
In fact, it took me several weeks to make this AuraNode (about 100ctVis) using Growing AuraNode. Now I'm trying to make it faster by increasing the Wisp spawner to make it stronger, but that itself is causing lag, and it's a real downfall.
![2022-09-26_01 26 14](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40425798/582d91a6-22a6-4a7f-9e7d-5d3b5e95d78b)

**Comment by JodieRuth** [comment]
Node Randomization has always existed. It doesn't take much time, and you can use WA. a current bug in a bee has also led to a bee that likewise doesn't take much time on the matter. It's in the book here:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/ac2f6579-7e3b-47ba-b1a0-d24e718caba7)

**Comment by yukieiji** [comment]
I remember that even if the phase increased using NodeManipulator(Node Randomization), it was only by a small amount (in fact, I used it to make Growing AuraNode, but I was under the impression that it only increased by about 10 at most).

**Comment by Alastors** [comment]
> ys existed. It doesn't take much time, and you can use WA. a current bug in a bee has also led to a bee that likewise doesn't take much time on the matter. It

25k isn't hard to make tbf

**Comment by JodieRuth** [comment]
Node Randomization can work on the same node many times, plus WA, or you can just configure it and go do something else, and when you come back you'll be very happy with the size of the node

**Comment by Alastors** [comment]
> Node Randomization can work on the same node many times, plus WA, or you can just configure it and go do something else, and when you come back you'll be very happy with the size of the node

lmfao yeah I know, I've used it before :kekw:

**Comment by JodieRuth** [comment]
> it's the only way to make a growing node as well

Now there are bees, and the bee bug can do the maximum nodes needed for LES in less than five minutes. Even without the bug, if it's just to drive the LES, bees are the best solution until you have a Crystal Studded Cosmic Neutronium Wand

**Comment by Alastors** [comment]
> > it's the only way to make a growing node as well
> 
> 
> 
> Now there are bees, and the bee bug can do the maximum nodes needed for LES in less than five minutes. Even without the bug, if it's just to drive the LES, bees are the best solution until you have a Crystal Studded Cosmic Neutronium Wand

No a "growing node" is a specific type of node, the literal modifier is "growing"

**Comment by Alastors** [comment]
> > Now there are bees, and the bee bug can do the maximum nodes needed for LES in less than five minutes. Even without the bug, if it's just to drive the LES, bees are the best solution until you have a Crystal Studded Cosmic Neutronium Wand
> 
> Even if you can make it in less than 5 minutes now because of a glitch, won't it take an enormous amount of time once the glitch is fixed?

technically, vis bees aren't a glitch, they're completely intentional, annoyingly

**Comment by JodieRuth** [comment]
> > > Now there are bees, and the bee bug can do the maximum nodes needed for LES in less than five minutes. Even without the bug, if it's just to drive the LES, bees are the best solution until you have a Crystal Studded Cosmic Neutronium Wand
> > 
> > 
> > Even if you can make it in less than 5 minutes now because of a glitch, won't it take an enormous amount of time once the glitch is fixed?
> 
> technically, vis bees aren't a glitch, they're completely intentional, annoyingly

I mean https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14436，Is this intentional?

**Comment by Alastors** [comment]
> > > > Now there are bees, and the bee bug can do the maximum nodes needed for LES in less than five minutes. Even without the bug, if it's just to drive the LES, bees are the best solution until you have a Crystal Studded Cosmic Neutronium Wand
> > > 
> > > 
> > > Even if you can make it in less than 5 minutes now because of a glitch, won't it take an enormous amount of time once the glitch is fixed?
> > 
> > 
> > technically, vis bees aren't a glitch, they're completely intentional, annoyingly
> 
> I mean #14436 ，Is this intentional?

unfortunately, yes

**Comment by JodieRuth** [comment]
> > > > > Now there are bees, and the bee bug can do the maximum nodes needed for LES in less than five minutes. Even without the bug, if it's just to drive the LES, bees are the best solution until you have a Crystal Studded Cosmic Neutronium Wand
> > > > 
> > > > 
> > > > Even if you can make it in less than 5 minutes now because of a glitch, won't it take an enormous amount of time once the glitch is fixed?
> > > 
> > > 
> > > technically, vis bees aren't a glitch, they're completely intentional, annoyingly
> > 
> > 
> > I mean #14436 ，Is this intentional?
> 
> unfortunately, yes

Okay. Whoever made the bee like this must be upset about its recharging process XD

**Comment by yukieiji** [comment]
> technically, vis bees aren't a glitch, they're completely intentional, annoyingly

Is that mentioned anywhere? Do I think that is critical information that should be stated in the quest etc.?

**Comment by Alastors** [comment]
> > technically, vis bees aren't a glitch, they're completely intentional, annoyingly
> 
> Is that mentioned anywhere? Do I think that is critical information that should be stated in the quest etc.?

Dev channels you can't access

**Comment by JodieRuth** [comment]
> > > technically, vis bees aren't a glitch, they're completely intentional, annoyingly
> > 
> > 
> > Is that mentioned anywhere? Do I think that is critical information that should be stated in the quest etc.?
> 
> Dev channels you can't access

Hey I want to know one thing, was this planned all along. I was asked about half a month ago how this bug is triggered, its an issue that can only be triggered in Industrial Apiary, where a single charge will just hit the cap causing the bee to stop charging. So I guess it could be a bug rather than something decided? Otherwise this doesn't explain why the number of charges at once can reach tens of thousands

**Comment by Alastors** [comment]
> > > > technically, vis bees aren't a glitch, they're completely intentional, annoyingly
> > > 
> > > 
> > > Is that mentioned anywhere? Do I think that is critical information that should be stated in the quest etc.?
> > 
> > 
> > Dev channels you can't access
> 
> Hey I want to know one thing, was this planned all along. I was asked about half a month ago how this bug is triggered, its an issue that can only be triggered in Industrial Apiary, where a single charge will just hit the cap causing the bee to stop charging. So I guess it could be a bug rather than something decided? Otherwise this doesn't explain why the number of charges at once can reach tens of thousands

you're asking the wrong person, I was told it was intentional, that is all I know.

**Comment by yukieiji** [comment]
> Dev channels you can't access

Unless it's a temporary fix, I think that's information that should be made public.

And shouldn't 'Growing', which has a similar or higher cost, be buffed as well?

**Comment by Hikari1nVoid** [comment]
Just general warning node randomization will  spawn thunders for bigger nodes and you may lose your lovely cosmetic wand in the process.

**Comment by Alastors** [comment]
> > Dev channels you can't access
> 
> Unless it's a temporary fix, I think that's information that should be made public.
> 
> And shouldn't 'Growing', which has a similar or higher cost, be buffed as well?

the modifier from Gadomancy? I mean probably, but I'm also one of the only people that know about it.

**Comment by JodieRuth** [comment]
> > > Dev channels you can't access
> > 
> > 
> > Unless it's a temporary fix, I think that's information that should be made public.
> > And shouldn't 'Growing', which has a similar or higher cost, be buffed as well?
> 
> the modifier from Gadomancy? I mean probably, but I'm also one of the only people that know about it.

Maybe state this in the mission or something

**Comment by Alastors** [comment]
> > > > Dev channels you can't access
> > > 
> > > 
> > > Unless it's a temporary fix, I think that's information that should be made public.
> > > And shouldn't 'Growing', which has a similar or higher cost, be buffed as well?
> > 
> > 
> > the modifier from Gadomancy? I mean probably, but I'm also one of the only people that know about it.
> 
> Maybe state this in the mission or something

What are you talking about man?

**Comment by JodieRuth** [comment]
> > > > > Dev channels you can't access
> > > > 
> > > > 
> > > > Unless it's a temporary fix, I think that's information that should be made public.
> > > > And shouldn't 'Growing', which has a similar or higher cost, be buffed as well?
> > > 
> > > 
> > > the modifier from Gadomancy? I mean probably, but I'm also one of the only people that know about it.
> > 
> > 
> > Maybe state this in the mission or something
> 
> What are you talking about man?

About this change in bees. Maybe it could be stated in its mission
