### ISSUE TITLE
Split the client and server config file

### ISSUE THREAD

**Issue by ghostflyby** [GTNewHorizons/GT-New-Horizons-Modpack#14716]
### Your GTNH Discord Username

ghostflyby

### Your Pack Version

2.3.4

### Your Proposal

Split the client and server config file.
For example, server in `.minecraft/config ` and client in `.minecraft/client`

### Your Goal

Client config are intended to be customized, which make it hard updating tha pack and restore the changes in config.

### Your Vision

Improving the update experience.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [x] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Caedis** [comment]
While I like the idea, this is a difficult ask since it would involve updating all mods that create a config file.
