### ISSUE TITLE
Memory Leak by tesla

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/GT-New-Horizons-Modpack#14727]
### Your Pack Version

2.4.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Server runs in 20 TPS, and consumes about 4-6GB Memory.

### The Reality

TPS drop down after 10-30minutes since server start, /forge tps shows that there is a lag in personal space contains tesla.
The heap memory is almost full and top -Hp shows ZWorker(ZGC) consumes most of cpu time.
Through Memory Analyzer I discovered that tesla coil eats most of memory. 
Deleting that personal space fixex the problem.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/0b015f7e-75f7-406a-81fe-18aed3889fb7)

These instances are referenced from one instance of java.util.HashMap$Node[], loaded by <system class loader>, which occupies 931,864 (0.01%) bytes.
[heapdump2023-10-17-22-362628212631873181506_Top_Components.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12982850/heapdump2023-10-17-22-362628212631873181506_Top_Components.zip)
[heapdump2023-10-17-22-362628212631873181506_System_Overview.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12982854/heapdump2023-10-17-22-362628212631873181506_System_Overview.zip)
[heapdump2023-10-17-22-362628212631873181506_Leak_Suspects.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12982856/heapdump2023-10-17-22-362628212631873181506_Leak_Suspects.zip)

### Your Proposal

Fix memory leak.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cardinalstars** [comment]
Is this problem only in personal dimensions? What was the state of this tesla coil? Was it on? Transmitting? We need more details to figure this one out.

**Comment by koiNoCirculation** [comment]
> 

it's in personal dim.

**Comment by Caedis** [comment]
@koiNoCirculation can I get a copy of your world?

**Comment by koiNoCirculation** [comment]
@Caedis
My world is here. Personal DIM 182 is laggy.
http://minecraft.youtiao.dev:19999/backup.zip
backup.zip is large(7.3GB), so it may take time.
You may have to use wget or IDM to download because of hsts settings of browser.

**Comment by koiNoCirculation** [comment]
@Caedis hello, the save is given in the link and if there's any findings just reply.
