### ISSUE TITLE
recipe using Vinteum gem not working anymore, change the recipe to Vinteum dust

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#14721]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

build 178

### Your Server

zeta

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

Vinteum used to be a gem, now it does not have one, so the recipe using the gem is not usable, change the recipe.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/c62455ad-d5ea-4039-8bab-d11283402783)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/268b0ab5-7af8-4983-a25f-784cc683d7c4)

### Your Proposal

change the recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
I could've sworn there was a proper gem in Forbidden magic? not just a GT one?

**Comment by miaowwwwww** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/c44ea09d-69d2-465a-80a0-16e8437f2fbe)
nah, anyway this is not craft-able right now. just change the recipe.

**Comment by miaowwwwww** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/76674f08-e7e1-4419-8b90-4bcc5decf89f)
there is an icon with the gem but it's just the dupe of it, so might wanna change the icon too
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/4ca157b0-b549-45f4-be20-ca291cd9306e)

**Comment by JodieRuth** [comment]
Maybe add it back in its gem form

**Comment by Dream-Master** [comment]
where the gem is gone ?

**Comment by miaowwwwww** [comment]
gem is lost in darkness. (i thought it's intentional, in some update it was removed.)

**Comment by miaowwwwww** [comment]
its gem form only has this one usage so maybe we just don't need it.

**Comment by chochem** [comment]
you know when it was removed? I can have a look. highly doubt it was intentional

**Comment by chochem** [comment]
ah the gem was probably forced in by scripts and then removed with script removal like the GT stone plate
