### ISSUE TITLE
Portal the the Last Millenium is unusable in Nightly 180

### ISSUE THREAD

**Issue by TorvikW** [GTNewHorizons/GT-New-Horizons-Modpack#14728]
### Your GTNH Discord Username

Torvik

### Your Pack Version

Nightly 180

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Right-clicking the Portal to the Last Millenium would teleport me to the Last Millenium.

### The Reality

Nothing happened.

### Your Proposal

Restore portal functionality. Downgrading to Nightly 178 makes the portal functional again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TorvikW** [comment]
After playing with the files I have discovered that the specific mod causing the portal to be unusable is Galacticraft-3.0.75-GTNH-pre

**Comment by Dream-Master** [comment]
> After playing with the files I have discovered that the specific mod causing the portal to be unusable is Galacticraft-3.0.75-GTNH-pre

@TorvikW did it work before ?

**Comment by TorvikW** [comment]
@Dream-Master Yeah. A large portion of my base is in the Last Millenium so I'm manually using Galacticraft-3.0.74-GTNH so I can still playtest the nightlies. As long as Galacticraft doesn't get updated the portal is functional.

**Comment by LewisSaber** [comment]
Same issue for portal to deep dark

**Comment by Dream-Master** [comment]
i revert it

**Comment by Dream-Master** [comment]
test build 200
