### ISSUE TITLE
Left clicking on an item from Mine & Blade: Battlegear 2's grid will simply make it disappear

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#14720]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

gtnh-nightly-2023-10-14+174

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Normal access to items

### The Reality

![52K@XI(J`6%V%%`1CZ7T5JR](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/ae9dff1c-7fc1-474d-942c-f836dc807586)
![A6FRVI%OS@EJKQ(~BZ0}H}P](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/93649649-3d9b-4969-a0bc-f9b039623d4d)
Any item you can put on it, click on it and it just disappears. shift-click on it to take it off.

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
this is the commit that introduced the bug however I don't understand why https://github.com/GTNewHorizons/Battlegear2/commit/abf9ebfe8d0ac24ee8e9fca38227692d411c7e63
