### ISSUE TITLE
Logistics pipes questline causes intel graphical issues

### ISSUE THREAD

**Issue by KLewis144** [GTNewHorizons/GT-New-Horizons-Modpack#14734]
### Your GTNH Discord Username

yeat1328

### Your Pack Version

2.4

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Open quest line contents page in the quest book

### The Reality

Screen gets filled with solid colour

### Your Proposal

Just wanted to put it here in case anyone else has the same issue even with neodymium installed and cannot downgrade drivers easily. Problem is fixed by using the edit mode to change the icon of "Handle Logistics with Pipes".

Sorry if this isnt the place for that I just wanted to put an easy fix somewhere easy to find, since when I was looking I couldn't find anything that worked for me.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
that would be the basic logistics pipe. does that cause issues with intel outside of the QB too?

**Comment by KLewis144** [comment]
just hopped into a creative world to test it and yeah it does, whenever the item is held, clicked on in the inventory, and looked at while placed it causes the graphical issue. Im just wondering if other random items will set it off in the same way and if so what they have in common lol

**Comment by KLewis144** [comment]
happens with any other pipes from that mod at a quick glance as well

**Comment by chochem** [comment]
this is fixed as we added core tweaks, see https://github.com/makamys/CoreTweaks/releases/tag/0.3.3
