### ISSUE TITLE
Hand Pump no longer works with ME Fluid Terminal

### ISSUE THREAD

**Issue by Shadowsoftime99** [GTNewHorizons/GT-New-Horizons-Modpack#14736]
### Your GTNH Discord Username

Shadows#4865

### Your Pack Version

2.4.0

### Your Server

private

### Java Version

Java 17

### Type of Server

None

### Your Expectation

I've still been using my Simple Hand Pump to move small amounts of fluids (i.e. UUM) around, and in previous versions have had no issue using it with my ME system.

### The Reality

As of updating to 2.4, the pump just doesn't interact with the terminal anymore. I can't take from it, and if I fill it from another machine I can't insert into it. Other "non-full cell" items, like barrels and vol flasks, work fine.

### Your Proposal

Restore previous functionality.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
If you are talking about the one from gtpp, it should probably be deprecated now that direct buffer interaction is possible. No reason to fix something that has no currently viable use.
