### ISSUE TITLE
level maintainer doesn't work

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#14732]
### Your GTNH Discord Username

tom6482

### Your Pack Version

nightly 181

### Your Server

private

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

level maintainer to work

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8298646/b098f2de-2919-41a7-bdb7-4b4f6382fcb8)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8298646/7d00c2f0-ec2c-46f6-a298-65085ed35122)

and also all the stuff i had setted inside all of them got resetted.

### Your Proposal

make them work again or help me fix this bug

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by tommmmmmmmm** [comment]
the issue seems to be world-related; doing a new creative wolrd in singleplayer doesn't have this issue

**Comment by binaryalgorithm** [comment]
Try running it on demand; any error which occurs or lack of materials silently fails when the level maintainer tries to keep stock by inserting a similar on demand request.

**Comment by miaowwwwww** [comment]
not fixed in build 190

**Comment by miaowwwwww** [comment]
fixed in dev. can close now

**Comment by Laiff** [comment]
Fixed here [AE2FluidCraft-Rework#162](https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/162)
