### ISSUE TITLE
Quest: Searching for Answers not recognizing Quick and Dirty portal generator

### ISSUE THREAD

**Issue by heccindragon** [GTNewHorizons/GT-New-Horizons-Modpack#14738]
### Your GTNH Discord Username

heccindragon

### Your Pack Version

2.4.0

### Your Server

Personal server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I was trying to complete the Searching for Answers quest in Novice Thaumaturgy, I got a quick and dirty portal generator and then used it to create the twilight forest portal to complete the requirements of the quest.

### The Reality

The portal was made and the portal generator was made but the quest didn't complete and it wouldn't recognize the portal generator was in my inventory. It should be noted that I tested this in singleplayer and the quest works fine so it seems to be some multiplayer issue

### Your Proposal

Have the quest recognize the quick and dirty portal generator so that the quest can be completed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
nothing changed here so I think its fair to assume this is just you.
Probably not the quest but some issue with your server.

**Comment by vovaksenov** [comment]
Do other quests work? Have you tried force detecting with a button? Are you sure the edit mode is off? "/bq_admin edit" to switch. If nothing works and the ussue is specific to this quest, yet nobody can confirm the bug i suggest you use the edit mode inbuilt designer to force complete the quest.
