### ISSUE TITLE
openning gui for space elevator any module get fatal error in client.

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#14737]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

build 180

### Your Server

zeta

### Java Version

Java 8

### Type of Server

Thermos

### Your Actions

openning gui for space elevator mining module 3 get fatal error in client.

### Crash Report

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/443813c9-7bd9-4314-a6a0-cf303159613f)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13038784/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by berta24** [comment]
i can confirm, it happens for me too

**Comment by miaowwwwww** [comment]
this is happening again in build 217, plz reopen and fix
