### ISSUE TITLE
Thaumcraft block that doesnt have item texture

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#14749]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Expectation

That this block has an item texture ( I´m adding recipes for the maze blocks and I cant add a recipe for this block because with no texture the thaumonomicron crash)

### The Reality

The block has no texture at all:
The block:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/9c3e91d9-c91b-4ccf-b7a6-a40d7c366610)

The non texture:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/5d4d400d-a6c2-44bd-83dd-57b2d2684018)

### Your Proposal

Add the texture of the item somehow

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
Too much work for 0 reward, given this mod is ARR

**Comment by Alastors** [comment]
For reference, the infusion pillar is the same way, you weren’t ever meant to have them in your inventory
