### ISSUE TITLE
shift click in crafting page not highlighting most pattern locations(might be all crib s) 

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#14755]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.4.2 build 188

### Your Server

zeta

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

work well like before

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/1e24342f-a019-4656-bb06-cea8fd813de5)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
I can confirm that the highlight feature does not work (does not highlight anything) when the pattern is inside a p2p interface too.

(2.4.1)

**Comment by Laiff** [comment]
fixed https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/394

**Comment by miaowwwwww** [comment]
fixed in dev. confirmed
