### ISSUE TITLE
Add Pipe Support

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#14751]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

last version

### Your Proposal

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/61422500/0a023741-b740-4c62-9dce-d8c3dec83ee2)

If I can use a pipe to supply water here to wash out the dust at the beginning, that would be great.

### Your Goal

null

### Your Vision

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
I _believe_ this is intentional, but there is the Sink from Cooking for Blockheads that might work.

**Comment by Alastors** [comment]
This is 100% intentional

**Comment by Alastors** [comment]
If you want an automated dust washer, we have a machine for that, multiple actually

**Comment by chochem** [comment]
yea, intentional. the simple washer is what you are looking for.

**Comment by Rika-TH** [comment]
As a note, if you really want to automate the basic cauldron then golems will work
