### ISSUE TITLE
Draconic evolution item render in interface terminal is broken

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#14754]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.4.2 build 188

### Your Server

zeta

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/b1ff31e2-91d5-4f1f-9b5f-b52ec5228e4b)
work well like before

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/3d8b0982-3897-4089-a6e2-5eef87f21e26)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Laiff** [comment]
fixed for interface terminal here [Applied-Energistics-2-Unofficial#394](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/394)
for level terminal here [AE2FluidCraft-Rework#162](https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/162)

**Comment by miaowwwwww** [comment]
fixed in dev, confirmed
