### ISSUE TITLE
Java 22 incompatibility

### ISSUE THREAD

**Issue by ah-OOG-ah** [GTNewHorizons/GT-New-Horizons-Modpack#14753]
### Your GTNH Discord Username

aptugongermatherinn

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

Used latest GraalVM built from source (effectively Java 22 snapshot), slightly altered lwjgl3ify with ASM bumped to 9.6.
ServerUtilities, JECalulation, Neodymium, CoreTweaks, and GregtorioOverlays were added and FastCraft removed, but almost certainly not the cause of the crash.

As far as I can tell some default ASM version in lwjgl3ify or forgePatches is using an older version, and is having problems reading Java classes.

### Crash Report

[crash22.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13062204/crash22.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ah-OOG-ah** [comment]
Note: Notfine was also built from source, although again that _shouldn't_ matter

**Comment by ah-OOG-ah** [comment]
After further testing, CoreTweaks breaks the pack even with Java 17 and full defaults, no modified lwjgl3ify.
However, Java 22 crashes before CoreTweaks becomes a problem, so I believe the log is still valid.

**Comment by eigenraven** [comment]
You'd have to rebuild unimixins with a newer asm shaded in.
