### ISSUE TITLE
Crash after killing enderdragon

### ISSUE THREAD

**Issue by Cyl18** [GTNewHorizons/GT-New-Horizons-Modpack#14756]
### Your GTNH Discord Username

cyl18

### Your Pack Version

2.4.1

### Your Server

home.cyan.cafe:7002

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Actions

killing enderdragon

### Crash Report

[crash-2023-10-22_19.11.33-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13063047/crash-2023-10-22_19.11.33-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Cardinalstars** [comment]
Pr should fix.

**Comment by Glease** [comment]
fixed by https://github.com/GTNewHorizons/BugTorch/pull/20
