### ISSUE TITLE
Change quest book search color. 

### ISSUE THREAD

**Issue by tomasz-brak** [GTNewHorizons/GT-New-Horizons-Modpack#14757]
### Your GTNH Discord Username

baron#9972

### Your Pack Version

2.4.0

### Your Proposal

1. Change the color when you search for a quest in the book. As a color blind person you are not able to differentiate between done quests and the searched one.

1. Make it zoom to the quest you've searched. This would be a good solution too.

### Your Goal

To increase acessability

### Your Vision

It would be easier for colorblind people to play the game.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
As a *not* colorblind person I still sometimes have problems finding the "highlighted" quest. Something like a pink or blue color would be much more noticeable.

**Comment by bombcar** [comment]
Or concentric rings that appear for a moment or something similar. 

I think the zoom in option might be the best, as then “you can’t miss it”.

**Comment by tomasz-brak** [comment]
bump
