### ISSUE TITLE
Formally move the DE multi from EMT to like Draconic Evolution

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#14765]
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

N/A

### Your Proposal

Doesn't make sense for a DE multi to be in EMT, I know the thought is "oh well it's kind of magic" but DE isn't really magic by the classical standard to the point we don't consider it magic in the CoC, likewise, the multi isn't related to thaumcraft whatsoever, so it doesn't make sense for it to be in a thaum addon anyway.

### Your Goal

EMT is drifting toward active support outside the pack, currently with the GT hard dependency, it can't be, if we just move the DE multi to a different mod (perhaps DE) we can just straight nuke Bart's dependency instead of going through the motions to make it soft.

### Your Vision

To finally be able to use EMT outside the pack.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
since it is a GT multi, it probably makes more sense to move it to a GT addon. Since kuba was involved, maybe kubatech?

**Comment by Alastors** [comment]
> since it is a GT multi, it probably makes more sense to move it to a GT addon. Since kuba was involved, maybe kubatech?

Lmfao we can move it where y'all want to, I just want to excise a non-sensical multi placement and put it somewhere else

**Comment by Alastors** [comment]
I can terminate the GT hard dep easily if we move this, and move to a more optional dep at a later date if we wish for something new.
