### ISSUE TITLE
Wireless Energy hatch + Energy hatcg bug

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#14763]
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

last version

### Your Server

MP SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

check VIDEO with bug. No comments

https://drive.google.com/file/d/1KlQUKW9B-_lDQWy77iEPrNaQsiz9aaAE/view?usp=sharing

my research showed that in a minute of operation at 1.700 EU/t, the multiblock consumed 2,100,000 EU from the wireless network.

AND 2 test in a minute of operation at 10,300 EU/t, the multiblock consumed 12,700,000 EU from the wireless network.
As I understand it, this manipulation allows having 1 Wireless Energy hatch 2A to consume more than 2A from the wireless network
I see that the bug is not critical, but it still exists

### The Reality

null

### Your Proposal

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
I watched ur video, what part is wrong?

**Comment by Divran** [comment]
wireless energy hatches have very large buffers so they don't have to pull from the wireless network very often. If you use a scanner and check the internal storage of the wireless energy hatch while doing this test you should see it go down and eventually when it reaches zero the machine won't start again until it syncs. Pretty sure this is what happens at 0:50 in your video.
