### ISSUE TITLE
Rendering bug with AC slopes C1-4

### ISSUE THREAD

**Issue by NotAPenguin0** [GTNewHorizons/GT-New-Horizons-Modpack#14769]
### Your GTNH Discord Username

notapenguin

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Correct rendering of AC slopes C1-4. See below for illustration.

### The Reality

When making AC slopes C1-4, wrong amounts of ambient occlusion are applied to the thin slices. Illustration below:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/26485755/5a917851-5ddd-45e6-9434-66b5a9b5934b)

This is especially visible with light blocks such as lave 12 and hempcrete. Shaders don't seem to fix this issue.

### Your Proposal

To fix the way AO is calculated for these slopes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leagris** [comment]
What modded blocks are used here?
I have tested this in Carpenter's blocks and shading looks ok
![2023-10-28_20 14 47](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1111474/ff4f5e3b-3d24-4117-93c3-a15993d8e987)

**Comment by NotAPenguin0** [comment]
This is with architecturecraft slopes. I've only seen it happen when they're placed sideways too.
