### ISSUE TITLE
Add LCR recipe for calcium cabonate dust from GT++

### ISSUE THREAD

**Issue by danzaharrr** [GTNewHorizons/GT-New-Horizons-Modpack#14768]
### Your GTNH Discord Username

danzah

### Your Pack Version

2.4.0

### Your Proposal

Calcium cabonate dust from GT++  is a byproduct of processing in gt++ machines. It can be processed in a chemical reactor, but it cannot be done in LCR
![изображение_2023-10-24_223423862](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/148888677/70c3db80-798c-42e4-936b-84cb0e6b66bd)

### Your Goal

To avoid using small chemical reactor

### Your Vision

1) Convertation calcium carbonate to calcite with crafting table(chemical formula is same)
2) chenge calcium carbonate id on calcite id (due to the reason described in paragraph 1)

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
yea circuit 18 doesn't create a LCR recipe.

@Steelux8 is this on purpose or a mistake/oversight?
