### ISSUE TITLE
extra utilities two portals not working, including DD portal!

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#14764]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.4.2 build 190

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

right click the two portals, teleport to the dims

### The Reality

no respond. 

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
probably same as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14728

**Comment by miaowwwwww** [comment]
oh ye the same one, just make sure DD get fixed too. close if u want
