### ISSUE TITLE
More convenient placement of multi-block machines

### ISSUE THREAD

**Issue by yuanju-qwq** [GTNewHorizons/GT-New-Horizons-Modpack#14778]
### Your Pack Version

2.4.1

### Your Proposal

A new block -- Endimage Infinite Cheats. All Endimage Infinite cheats will be connected to one space, which will allow ae to pack multiple block machines into the Endimage Infinite cheats by writing templates, so that players do not need to take materials from ae.
If possible, give the projector access to the Endimage version of the Infinity Bin.

### Your Goal

Every time when placing multi-square blocks, it is necessary to take materials from ae, often take more and take less, and need to put them in again, which is extremely inconvenient.

### Your Vision

Alleviates the player's pain when playing multiple blocks.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
What?

**Comment by yuanju-qwq** [comment]
It can be similar to the original enshadow box. The main reason is that the original enshadow box is too small to hold the materials of multi-block machines, such as multiple machines and multi-block machine materials that occupy 3 blocks
