### ISSUE TITLE
Stacking Drones

### ISSUE THREAD

**Issue by Phiapsi** [GTNewHorizons/GT-New-Horizons-Modpack#14776]
### Your GTNH Discord Username

phiapsi

### Your Pack Version

2.4.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Stack two exactly the same drones 

Video:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40121239/3c1504e4-376f-4e55-a8c7-d20c0d424a73

### The Reality

The NBTData is in a different order and so the drones do not stack

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40121239/c3eddef4-96cf-4ec8-a179-c123dd3eb267)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40121239/a9211ead-0bd0-43fd-b9e0-00dd4ad7c2c7)

Already discussed it on the Discord Help Chat Channel:
https://discord.com/channels/181078474394566657/234936569360809996/1166984037705990234

### Your Proposal

Change the Method to attach the NBT Data? Just a hobby-programmer here.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cardinalstar16** [comment]
Hmm, looks like this is something I could tackle. Not sure if it would retroactively work though. I'm guessing not. Do you have steps for reproducibility? Maybe a world download that has the bees would help.

**Comment by Phiapsi** [comment]
Hey, sure, i will prepare a single-player world download and maybe a guide to reproduce the bug if i succeed.

**Comment by Phiapsi** [comment]
Hey, thank you for trying to fix the problem.

### Reproduction:
**What you need:**

- Alveary + stabilisier / Apiary
- Princess with 2 different species, but exactly the same traits. (Look at the picture at the top)
- Drones with 2 different species, but exactly the same traits. (Look at the picture at the top)
- _Oblivion Frame for faster testing_

**Steps to recreate:**

1. Breed the princess with the provided drones. After 5 generations you will find most likely both types of drones.
2. There are no more steps ...

**When to find the problem:**
Mostly pure breeding. 
For my case: I always go back to the eldritch princess and start from there. I only need to get the desired species once and start to breed the desired species drone with a purebred eldritch princess. The first couple of times i only breed the resulting drones with pure breed eldritch princess until i have a eldritch XY drone with the same traits. Then i start to try to pure breed to the desired species and now happens the bug.

**World-download:**
You have everything(also the 2 kinds of drones) you need in the chest between the apiary and the alveary. You will also find a chest full with drones, they are for testing purposes and should be used to recreate the example.

[Drone Stacking.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13186479/Drone.Stacking.zip)

**Comment by chochem** [comment]
doesnt sound like a bug. you have 2 of every property and order matters

**Comment by chochem** [comment]
yea your discord link confirms it. not a bug. just one gene being dominant so the two different bees have the same active one genes and thus look the same in the beealyzer
