### ISSUE TITLE
Quest "Making Better Tools" not up to date with clay cast

### ISSUE THREAD

**Issue by Napstablook2** [GTNewHorizons/GT-New-Horizons-Modpack#14777]
### Your GTNH Discord Username

napstablook_

### Your Pack Version

2.4.0

### Your Proposal

The quest "Making Better Tools" in the Stone Age **should let you use clay cast instead of forcing the use of an aluminium brass cast**

### Your Goal

With the addition of the **clay cast**, it is now possible to craft Tinkers Construct tools **without using aluminium brass casts**.
However, the quest "Making Better Tools" **forces you to craft those to validate it**, and it **locks a bunch of quests** in the Steam Tier as it considers that you can't have diamonds without validating those and thus without having those cast.
However, **now that there's clay cast you can now craft tools using only those** and thus **should be able to validate the quest using those instead of the aluminium brass casts.**

### Your Vision

With the actual quests, you can **have quests locked even if you have the tools** only because you **used the clay cast instead of the aluminium ones**, and you're **forced to explore** to find aluminium only to **create those casts that you're not gonna use simply to validate the quest.**

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [x] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TheVava89** [comment]
Btw, I just saw that the next quests (about making a bronze rapier, sword and javelin also need those aluminum brass cast and that the change I proposed would also be nice for those

**Comment by bombcar** [comment]
One way to cheese it as it currently is (if you’re using clay) is to keep melting down the aluminum brass forms to make the next one. 

Leaving the quest as it and making the forms optional and somehow triggering off the actual item (can it detect “any axe head”) might be the way to go, with a note on clay if desired.

**Comment by TheVava89** [comment]
It'd work if you already have some aluminum, the problem is that it locks you if you still haven't find any, or if your aluminum bushs aren't ready yet, but yes making the cast an optional requirement would also solve the problem

**Comment by bombcar** [comment]
@Dream-Master this is a Stone Age quest change, however I see that the rapier one is already "optional" - if you're fine with it, I will change the aluminium brass requirements to optional and add a clay note to the first quest.

**Comment by Dream-Master** [comment]
need to look into the questbook.

**Comment by bombcar** [comment]
If we do the above, there's a way to get aluminum brass without having any, via the quest reward from "Bronze Javelin" and the other weapon quests (these already exist but it's gated behind having some to begin with in "Making Better Tools".

**Comment by TheVava89** [comment]
Wouldn't it be possible to only give the aluminium brass if the aluminium brass casts were used to validate the quest ?

**Comment by bombcar** [comment]
That's the other way, have split quests (like with building the smeltry itself) which in general I'm moderately against (complicates the quests for no major reason).

I don't think you can have conditional rewards.
