### ISSUE TITLE
adding nutritional value to warm blood for vampirically inclined playstyles 

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/GT-New-Horizons-Modpack#14771]
### Your GTNH Discord Username

poppyxabe

### Your Pack Version

2.4.0

### Your Proposal

Giving Warm blood;   "witchery:ingredient:163"  , an all rounded nutrition value, similar to an enchanted golden apple, which has all 5 nutrition values at 0.4%, to alleviate the drawbacks of lack of nutrition to vampire players.

### Your Goal

Since the addition of nutrition, non mainstream playstyles like playing vampire suffered from the downsides of having low nutrition, which made it necessary for the vampire player to use "undesirable" means of regaining the nutrition such as making food, and eating it, but the thing is a vampire cannot eat food unless their blood is completely drained and even then they don't gain anything from it except adding it to the list of eaten foods, if not eaten before, and nutritional value, with no hunger or saturation gained (its actually lost, as you're perpetually starving due to lack of blood and hunger effect from eating normal food), as the vanilla witchery method of gaining blood is from drinking from villagers or players, which does not contribute anything to the nutrition values (blood isn't nutritious how shocking) 

the only non-food roundabout way to alleviate this would be using a healing axe as apparently that maintains the nutritional value to 50%, but that is not possible unless the vampire is drained of blood, which at that point they're basically good as dead 

Besides this assumes the vampire player has access to proper early thaumcraft setup and has thrown infernals with regen into their tinker's smeltery (or themselves)  to get access to warm blood, which is a fair investment (same with how enchanted golden apples require a silly amount of gold (for the early game) and an Lv chemical reactor 

### Your Vision

This Band-Aid solution to one of the non mainstream playstyles that were negatively affected by the addition of the nutrition mod, will be giving said player a chance to stay engaged within their own playstyle and not be punished by it 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by mitchej123** [comment]
I'd also be fine making vampires trend towards 50 as other food bypassing methods do.  Hadn't really thought about them.

**Comment by Ethryan** [comment]
Hmm, maybe have it set so that vampires is permanently at 50, since they don’t eat food at all anyway.

**Comment by Caedis** [comment]
Which mod would handle it?

**Comment by Ethryan** [comment]
> Which mod would handle it?

WitcheryExtras maybe?

**Comment by mitchej123** [comment]
Nutrition could also have an optional witchery dep and peg it to 50

**Comment by Caedis** [comment]
Could probably just clamp it from 50 -> 100 if the player is a vampire
https://github.com/GTNewHorizons/Nutrition/blob/master/src/main/java/ca/wescook/nutrition/events/EventWorldTick.java#L111
