### ISSUE TITLE
Reduce the number of parallels on the volcanus to prevent it from kneecapping itself most of the time.

### ISSUE THREAD

**Issue by C0bra5** [GTNewHorizons/GT-New-Horizons-Modpack#14774]
### Your GTNH Discord Username

c0bra5

### Your Pack Version

2.4.0

### Your Proposal

Reduce the number of parallels on the volcanus to prevent it from kneecapping itself most of the time or add a notice that you have to regulate the number of items when you insert them to reach maximum efficiency. The current max of 8 slows it down by 50% or more of its maximum speed most of the time.

### Your Goal

Since parallels take priority over OC, the volcanus will often skip an entire overclock and run at 50% of the maximum speed it should achieve.

Here is an example:

Setup:
- 2x ZPM energy hatches
- Electrum Flux coils
- Superconductor Base LuV Dust
- Radon Gass

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17766417/b6d6cf0f-a53e-40db-b1ba-e72e204eb5b2)
with 8 ingots at a time
- 8 ingots at a time:
- 334 ticks per recipe
- 8 items / 334 ticks * 20 = 0.4 ingots per second

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17766417/b29368f8-4d73-4657-8b00-bc986856d7db)
- 5 ingots at a time
- 83 ticks per recipe
- 5 items / 83 ticks * 20 = 1.2 ingots per second (a 2.5x increase over 8 ingots at a time)

### Your Vision

Either add a mention somewhere that it's better to regulate the number of items that enter the input buses to 5 for most ingots (naquadah alloy being a notable exception that benefits from the 8 parallels) or prevent the volcanus from intentionally kneecapping itself most of the time.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
Strong disagree. Part of the beauty in automating the Volcanus is that you are supposed to feed it items in carefully calculated batches (usually 5 or 6), to maximize the efficiency of parallels and overclocks.

In your scenario (Recipe: 7,680 EU/t, 147s, 6,000K minimum heat; multiblock: UV tier, 9901 heat) the optimal batch size is 5. This will result in smelting one item every ~0.84 seconds. Both 4 parallels (1 every ~1.05s) and 8 parallels (1 every ~2.09s) are worse.

The same idea is true for any other machine that does parallels (maxing out the number of parallels is not always the best use of overclocking power). But most other machines work so fast that the difference in practice is negligible.

**Comment by C0bra5** [comment]
> Part of the beauty in automating the Volcanus is that you are supposed to feed it items in carefully calculated batches (usually 5 or 6), to maximize the efficiency of parallels and overclocks.
The issue is that, as far as I know, this part is never mentioned anywhere, either in a tooltip or the quest book.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17766417/e830cf4c-cc20-455c-8090-2d752cf6ed33)

TBH I hadn't considered that it could do 5 at a time, I do odd number patterns on my mbf so idk why it didn't cross my mind...

Anyhow it would be nice to at least have a notice to people that you have to do something if you don't want your volcanus to not shoot itself in the foot 90% of the time.

**Comment by chochem** [comment]
you are mistaken anyway. 90% of the time there is no 'shooring yourself in the foot' because its rare to have spare heat OCs you arent using.

**Comment by C0bra5** [comment]
> you are mistaken anyway. 90% of the time there is no 'shooting yourself in the foot' because its rare to have spare heat OCs you arent using.

Where are you pulling that 90% of the time from? I've done some testing and it's hard to find an ingot that isn't affected by this issue. This is an issue I have been able to observe and notice this issue ever since I made my first volcanus in IV.

Using the setup described in the original post, I ran some tests and recorded the optimal item count, recipe time and un-optimal (8 item at a time) recipe time for many materials.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17766417/23295342-7e2b-41e1-955b-11bde141ec52)

**Comment by querns** [comment]
I don't know if it will change anything, but try re-running the experiment with batch mode on.

**Comment by C0bra5** [comment]
i'll rerun them for as many as can fit in a batch mode of that setup and post the results

**Comment by C0bra5** [comment]
> I don't know if it will change anything, but try re-running the experiment with batch mode on.

As expected batch mode had no effect
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17766417/d6395d13-d887-458d-b33d-bfadffc9f485)

**Comment by C0bra5** [comment]
for the sake of transparency here's my current methodology:

I use an open computer computer with an adaptor to read the length of a recipe. Catching a 2 tick recipe isn't that easy using the personal scanner, so I switched to a computer to make my life easier.

```lua
local volcanus = require('component').gt_machine
local gpu = require('component').gpu
local term = require('term')

-- clear the terminal
term.clear()
local last = nil;
while true do
	-- when max progress changes to a new value that isn't 0 (no recipe)
	local now = volcanus.getWorkMaxProgress();
	if now ~= 0 and last ~= now then
		last = now;
		-- display recipe time in ticks with big number
		gpu.setResolution(#tostring(now),1)
		term.clearLine()
		term.write(tostring(now))
	end
	os.sleep(0.05)
end
```

1. Set the circuit in an input bus.
2. Right-click the controller of the volcanus to open it's interface
3. ensure it's off
4. place the amount of dust I want to test with in the item slot of the controller.
5. double-click the power switch button to turn let the machine process the items.
6. record the time displayed on the screen by the open computer program.

A picture of the setup
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17766417/f956e72d-ab83-42fd-81a9-6da7fb05fdfd)

**Comment by AbdielKavash** [comment]
Just for the record, the parallel/overclocking logic is not some dark magic, it is public and well documented :-)

I have a spreadsheet where I can just input the recipe and the configuration of the Volcanus (power + coils), and it automatically calculates both the processing speed, and also the optimal batch size to minimize time per ingot.

**Comment by C0bra5** [comment]
> I have a spreadsheet where I can just input the recipe and the configuration of the Volcanus (power + coils), and it automatically calculates both the processing speed, and also the optimal batch size to minimize time per ingot.

Mind posting the link to that spreadsheet?

> Just for the record, the parallel/overclocking logic is not some dark magic, it is public and well documented :-)

oh, I know that, but it's more of an issue of people not being aware of it. I've mentioned the fact that the 8 parallels have a bad tendency to slow down the volcanus a couple of times in the last few months in the discord. I can't remember a time when I didn't encounter someone who thought that the 8 parallels prioritized production speed.

I opened this issue because of one such conversation.

**Comment by chochem** [comment]
> > you are mistaken anyway. 90% of the time there is no 'shooting yourself in the foot' because its rare to have spare heat OCs you arent using.
> 
> Where are you pulling that 90% of the time from? I've done some testing and it's hard to find a material that isn't affected by this issue. This is an issue I have been able to observe and notice ever since I made my first volcanus in IV.

I dont understand what you are testing. 90% was not a precise number. just saying that most of the time you don't have and unused 1800k to spare which is the only case where you would be 'shooting yourself in the foot' by letting it do 8 parallels. If you dont have that you are fine anyway and this change would just make things less energy efficient.

**Comment by bombcar** [comment]
So it’s totally calculable and we just need to expose inefficient activity. So we add code that makes the volcanus have a chance to giggle if it detects it ran an inefficient batch b

**Comment by Pxx500** [comment]
Even if it's not perfectly efficient it still saves player EU by not doing an imperfect overclock

**Comment by King65868** [comment]
Volcanus can do perfect OCs, just like EBF
