### ISSUE TITLE
LV Distillers are very noisy.

### ISSUE THREAD

**Issue by xxf62263mxd** [GTNewHorizons/GT-New-Horizons-Modpack#14783]
### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

LV Distillers are very noisy.It sounds like it's in a cave.

### The Reality

LV Distiller sound back to normal, like 2.2.0

### Your Proposal

Might be able to check the sound files?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
Muffler Upgrade perhaps?

**Comment by xxf62263mxd** [comment]
I compared the sound files of the two versions and found that they are indeed different, is this a change in the new version of GT?

**Comment by chochem** [comment]
yea @minecraft7771 added a bunch of new sounds. Most of them turned out well, but you are not the only one that feels forced to use a muffler on every distillery. xD

**Comment by chochem** [comment]
I think with https://github.com/GTNewHorizons/GT5-Unofficial/pull/2370 we can consider this fixed.
