### ISSUE TITLE
Make smeltry liquids more obviously distinct

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#14782]
### Your GTNH Discord Username

bombcar1042

### Your Pack Version

2.4.1

### Your Proposal

It's almost a daily occurrence that someone tries a GT recipe that needs liquid tin, say, and tries to use the smeltry version.

You have to dig somewhat in NEI, or just know that the smeltry version is almost always NOT what you need, or you get confused why the recipe doesn't run.

### Your Goal

Make this easier for new players by making it obvious in NEI.

### Your Vision

Change the textures on the smeltry fluids, or at least make it so a smeltry fluid in an assembly machine appears with an S on it or something so it is obviously visibly different than what NEI shows.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by PeculiarSana** [comment]
I recently fell victim to this myself and can agree that having the liquids distinguishable would have helped save me some headaches and time.

**Comment by Ethryan** [comment]
Maybe change the names of the liquids to “Dirty” versions, to give them a different name too.

**Comment by LazyFleshWasTaken** [comment]
I fell victim to this too back when I just started out.

**Comment by chochem** [comment]
The textures are very distinct already. Don't think that is the actual issue.

Glass:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/f6699ee3-4fcb-479f-82ca-dcc32ed8a7d4)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/7631d40e-8dd9-42af-8b0b-bf569b19e971)

Iron:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/11c72d62-a3ea-4e87-82ce-8e3cfa48ddf2)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/e754f148-bfc7-40f9-97ef-92107526d7e2)

I guess Tin is the only where they are randomly similar.

Changing names would be the bigger thing for sure.

**Comment by GTNH-Afx237v7** [comment]
Additional info in tooltip?
