### ISSUE TITLE
Terminate BArTiSNeK itemset

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#14784]
### Your GTNH Discord Username

You know who I am

### Your Pack Version

N/A

### Your Proposal

As brought up in: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/13901#issuecomment-1783646613

A user has requested a BArTiSNeK meteor, from what I’m aware, the item set only really has one use, that being tier 6 purified water. I propose we switch that to some other lens and terminate this terrible set.

### Your Goal

To an extent, I’m fine with items have dev’s names on them, though I personally find this set tacky and jarring (not to mention chemically incorrect) 

### Your Vision

Rather than entrench ourselves further with painful reminders of old and frayed rope ends, I propose we switch out the current uses of the item to something else around its general tier. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
you mean remove the material I suppose?

**Comment by lordIcocain** [comment]
also source of europium

**Comment by vovaksenov** [comment]
Frequently used as a source of neon for the 1st void miner afaik

**Comment by Hikari1nVoid** [comment]
Please leave that ore there.Also I suggest adding thaumium dust to oreprocessing output for filling the missing 'Ma' element in that ore.

**Comment by vovaksenov** [comment]
@Hikari1nVoid thaumium is not Ma, it also has Fe, so it wouldnt fit. The composition is fine as is and is consistent with how "Ma" sometimes disappears during electrolysis. If you really have to add something, add salis mundus.
