### ISSUE TITLE
World Crash with Adventure Backpack

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#14785]
### Your GTNH Discord Username

Ethryan

### Your Pack Version

2.4.0

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

The world crashes or you disconnect from the server when using the open backpack button (V) while inside the backpack. 

Steps to reproduce: 
1: Equip the backpack.
2: Press the button to open the backpack GUI. (V) in my case.
3: Press the button (V) to close the backpack.
4: Watch the world Crash, or watch a client disconnect from the server.
5: Be annoyed.

### Crash Report

Will upload later.

### Info

I haven’t tested newer versions of the pack, but when I checked the commits in that repository I didn’t see anything about this issue, so I believe it’s still unfixed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Cardinalstars** [comment]
This is a bug related to NEI actually. V is your key likely for pulling up bookmarks. It seems the GUI for adventure backpacks closes first, then we get a NullPointer because NEI thinks your still in an inventory. I think I have a fix.

**Comment by scrubnmuhtub** [comment]
https://mclo.gs/JcO4PyV

I may have had a similar issue.  Same keybind.  NEI + Adventure Backpacks blamed.

**Comment by miozune** [comment]
@scrubnmuhtub You're on 2.4.0, which doesn't include the fix.
