### ISSUE TITLE
Unable to start server / keep server running for long

### ISSUE THREAD

**Issue by Nwod611** [GTNewHorizons/GT-New-Horizons-Modpack#14796]
### Your Pack Version

2.4.0

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Actions

Tried many versions of java, but still refuses to work

### Crash Report

https://cdn.discordapp.com/attachments/1167182509390434344/1167920207067615262/image.png?ex=654fe174&is=653d6c74&hm=cc85b2b7f5cb3560304077d98aec0fbcd69ecda3a9b446542a790d9a062c31f5&

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
sounds like a problem with your java or java arguments. Good chance it is not related to GTNH. you can try posting the core dump, but I probably cant make sense of that myself.

Not sure why you checkmarked the third point. are there more people with this error, that seems unlikely? But if so, then best get them to post here to compare notes.

**Comment by Nwod611** [comment]
It works without mode, but when ran with GTNH shits itself

**Comment by Hikari1nVoid** [comment]
Segmentation fault even before launching FML...Need a precise guide on how to reproduce this.
