### ISSUE TITLE
Same missing texture across machines

### ISSUE THREAD

**Issue by Fitmit** [GTNewHorizons/GT-New-Horizons-Modpack#14791]
### Your GTNH Discord Username

fitmit

### Your Pack Version

2.4.0

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

The area for machines that use the same face have a missing area for a texture, and it also gets scaled up with Faithful from the resource packs on the GTNH encyclopedia. 

### The Reality

Doesn't match the rest of the texture, and also on other machines like the Distillery, Assembler, Extruder, Wiremill.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40080125/9ac58332-ab2c-48af-9f89-4f1b64da643a)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40080125/89e6509f-7315-419f-8f3b-fc199b2d27d0)

### Your Proposal

I guess fixing the texture if it's supposed to be an indicator? :p 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
what missing texture?

**Comment by Ethryan** [comment]
I think he means the white/gray checkerboard pattern on the right.

**Comment by chochem** [comment]
that is just part of the texture is it not?

**Comment by Ethryan** [comment]
Yes

**Comment by Fitmit** [comment]
I thought with the other light being for if the machine is off/on, this one would be for if there's a problem with the machine, like insufficient power or if it's running, kinda like with assemblers in Factorio. It does turn the top 3 pixels bright green while its on, but shouldn't it be in the entire box?
