### ISSUE TITLE
Multiblock to automate dire crafting table

### ISSUE THREAD

**Issue by Blocky106** [GTNewHorizons/GT-New-Horizons-Modpack#14802]
### Your GTNH Discord Username

Blocky1377

### Your Pack Version

latest nightly

### Your Proposal

add a multiblock for the dire crafting table, since the dire crafting table is one of the most unnecessary
endgame spams. its always very slow and annoying to automate and keeps getting on the players nervs

### Your Goal

because the dire crafting table is annyoing and bad and very lag inefficient.

### Your Vision

a new multiblock automating the dire crafting tables recipes, using perfect overclock thus eliminating the need to spam them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
There is already two opened issues like this one:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12236
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/735#issuecomment-1773957307
