### ISSUE TITLE
Disable Achievement Fireworks or lower their volume option

### ISSUE THREAD

**Issue by BaneWilliams** [GTNewHorizons/GT-New-Horizons-Modpack#14823]
### Your GTNH Discord Username

banewilliams

### Your Pack Version

2.4.0

### Your Proposal

Achievement Fireworks come steady during the early times of the game. They are LOUD compared to everything else in the game, and can also get you killed (for instance if they go off while a creeper is soon to blow up on you)

An option to disable these, or if it's part of a modpack option, making that option more transparent to the user (questbook) would be great. Alternatively lowering the volume of them might work.

### Your Goal

The fireworks in the early game come very frequent and they are extremely loud. This creates a situation of sensory overload for the player, particularly for certain types of ASD people.

### Your Vision

Minecraft is a chill relaxing game for the most part, even in a complex modpack environment. Giving the player panic attacks is antithetical to the nature of the game, early on.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Why? Fireworks is great i like it. You have options to lower the sound effect in your games.

**Comment by ghostflyby** [comment]
This can be disabled in the config of EnderCore.

**Comment by Dream-Master** [comment]
@BaneWilliams just change the config on your end.
