### ISSUE TITLE
add Metastable Oganesson Screw recipe to solidifier 

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#14827]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.3.7

### Your Proposal

add Metastable Oganesson Screw recipe to fluid solidifier 

### Your Goal

less steps to get Og* screws

### Your Vision

yes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
stuff like that is autogenerated. what mod is it from?

**Comment by lordIcocain** [comment]
bartworks

**Comment by Lyfts** [comment]
Should already be available in 2.4.1 and above
https://github.com/GTNewHorizons/GoodGenerator/pull/212

**Comment by lordIcocain** [comment]
So quick, thank you
