### ISSUE TITLE
Minor - Quest tells you about coins and suggests you use them without telling you how.

### ISSUE THREAD

**Issue by BaneWilliams** [GTNewHorizons/GT-New-Horizons-Modpack#14822]
### Your GTNH Discord Username

banewilliams

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

The quest Main Quests and Secondary Quests in the tab And So, It Begins tells you about the coins you've been getting as a reward, and suggests you spend some. 

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/80081089/8a3c4a18-9f0d-401a-a224-4b3dc8a013be)

My expectation was that I would be able to go somewhere and spend the coins.

### The Reality

Instead, I could not figure out how to spend the coins. I tried looking in places that seemed obvious. 

It was only much later, when I did a secondary quest that was unlocked after the quest that told me I could spend coins in the shop, that told me how to do so.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/80081089/4d1e9948-11d0-431e-951e-4855f12df6cf)

### Your Proposal

The initial quest should incorporate some of the dialogue from the secondary quest, to make it clear to the player how to spend their coins. I put this in as a bug because the way the two quests read makes me feel like in an earlier version these quests were in likely different places, as narratively it doesn't make sense for the game to flow this way.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I dont get it. its says it right there.
