### ISSUE TITLE
QB adding Parametrizer Memory Card Quest

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#14825]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.4.0

### Your Proposal

We need a quest for the parametrizer card to know that there's this card
It can copy space elevator pump settings for example and can be pretty useful for that

### Your Goal

Adding a quest for the parametrizer card

### Your Vision

I had to ask in discord and having it in-game is better for people who aren't active on discord for example

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
should just be an adjustment of the current quest
