### ISSUE TITLE
Return from The End dimension is considered as death by the game

### ISSUE THREAD

**Issue by Miklebe** [GTNewHorizons/GT-New-Horizons-Modpack#14830]
### Your GTNH Discord Username

mike_be

### Your Pack Version

2.4.0

### Your Server

Private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Upon entering the exit portal from The End dimension, i expect to get back to my spawn point in Overworld in the same state i entered the portal.

### The Reality

The game triggers death flag upon spawning in overworld, spawning me with 6 hunger bars, Soul Fray and removes all non permanent potion effects.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/48237322/4eb61bda-d5ad-415f-938d-2e549556a0ae

### Your Proposal

I expect to keep my buffs (even if it's just 1-2 minutes of flying), hunger and no Soul Fray.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
This is actually how vanilla Minecraft works btw, leaving the end Kills you and you arrive home dead (but area instead alive).

We might be able to intercept that somehow.

**Comment by chochem** [comment]
As a hardcore player I can say that luckily it doesnt reaaly do that. XD

**Comment by Miklebe** [comment]
Well, yeah, it's not that bad and at most is just a minor inconvenience, but considering there are still penalties for "dying", would be nice to not have it. Also, as a guess, maybe it's tied to the End Poem/Credits screen? In new versions after the first time return you don't see End Poem again, so i haven't noticed that type of bug in other modpacks.

**Comment by Ethryan** [comment]
Nah, in this version, I think the portal just straight up kills you, and then restores a saved version of your inventory and hardcore flag setting. It doesn’t warp you anywhere, it just piggybacks off the death system.
