### ISSUE TITLE
AE2 Memory Card does not copy settings of p2p interfaces.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#14834]
### Your GTNH Discord Username

abdiel_kavash

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Use the AE Memory Card (basic, not advanced) to copy settings from one p2p interface to another: blocking mode, insertion mode, priority.

Shift-right-click the input p2p interface, then right-click the output.

### The Reality

The two p2p interfaces are linked (this is desired), but none of the settings are copied over.

### Your Proposal

The memory card should still link the interfaces as it does now, but it should also copy all settings as it does for other AE components.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Added by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/401
