### ISSUE TITLE
VisualProspecting not adding scans to JourneyMap for non-host players

### ISSUE THREAD

**Issue by adamcadot** [GTNewHorizons/GT-New-Horizons-Modpack#14831]
### Your Pack Version

2.4

### Your Server

SP LAN

### Java Version

Java 20

### Type of Server

Open To LAN

### Your Expectation

When using the Prospector's Scanner(HV) to scan some stone as a non-host in a single-player LAN game it says it discovered ores in the host's chat and updates their map with the scan results.

### The Reality

As a non-host, my map doesn't update with the ores.

### Your Proposal

Fix VisualProspecting to work for all players in a single-player LAN world.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
Use a dedicated server instead, LAN off singleplayer isn’t supported.

**Comment by vovaksenov** [comment]
@adamcadot please close the issue. There are no plans to fix problems with LAN servers. You should consider Ethryan's suggestion and move to a dedicated server if you want to play with others, otherwise you are bound to run into even more severe problems. The setup is not difficult and you can find a guide on the wiki if you have trouble doing it yourself.

**Comment by bombcar** [comment]
As an aside (if it is not clear) you can run a dedicated server *on your PC* if you have enough RAM (many do) - you don't have to *actually* have a separate piece of hardware.

And this can improve performance for single-player, too. Poor man's multithreading!
