### ISSUE TITLE
Double Gasoline Recipe

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#14832]
### Your GTNH Discord Username

eldrinn_elantey

### Your Pack Version

2.4.1

### Your Proposal

Fix a double gasoline recipe

### Your Goal

The only difference in these recipes is the presence of a Programmed Cicuit

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/46845681/16aa6ab1-7926-49e4-bf6b-649dffa145c4)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/46845681/8d60476b-ce9d-4277-aed3-bda77631a377)

### Your Vision

I don't see the point in having the same recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
on yesterdays nightly I only see the one with circuit. so either _fixedindev_ or _cantreproduce_ terretory.

**Comment by chochem** [comment]
ah actually that might be because that has a super broken gt. let me update gt and try again :P

**Comment by chochem** [comment]
ok yea it was that. I see it now. should be easy to remove one.
