### ISSUE TITLE
Add Random TP support as a server utility

### ISSUE THREAD

**Issue by Loreili** [GTNewHorizons/GT-New-Horizons-Modpack#14839]
### Your GTNH Discord Username

loreili

### Your Pack Version

2.4.0

### Your Proposal

When running a Bukkit or Spigot server, there are several plug-in options available for Random Teleport (/rtp) functionality but none of these work with an OOTB Forge server implementation. When using Java 8, it is possible to install Thermos (as with the official servers) but this isn't an option for Java 17-20 installations.

It would be useful if FTB Utils or similar included this functionality out of the box so that players could spread themselves out in an area pre-configured by the server administrator with a cooldown.

### Your Goal

Allow players to randomly tp to new locations so that their bases are spread

### Your Vision

Players would not be building on top of each other on servers and could more easily try to find new biomes which match the environment they want to build in

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
One QoL specifically for GT:NH would be to make said /rtp *also set character spawn* as if they'd slept in a bed, but this may not be possible. Otherwise perhaps it could set /home when it is done so if they die and reappear at spawn they can get back to where they are.

**Comment by Lyfts** [comment]
https://github.com/GTNewHorizons/ServerUtilities has this feature.

**Comment by Lyfts** [comment]
I can confirm that SU has /rtp.
Setting player spawn for rtp is more hassle than it's worth. If the player were to die they can do a cheeky /back provided they have the right permissions.

**Comment by bombcar** [comment]
This is implemented in SU.
