### ISSUE TITLE
Infusion Claw server crash and a possible fix

### ISSUE THREAD

**Issue by reobf** [GTNewHorizons/GT-New-Horizons-Modpack#14842]
### Your Pack Version

2.4.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Thermos

### Your Actions

Active an Infusion Claw on Thermos server witch AuthMeReloaded and the server crashes.
reopen old issue https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3027

Possible cause:
TileInfusionClaw.java uses ItemInWorldManager to simulate player RMB click, but it just create one ItemInWorldManager instance without setting field 'thisPlayerMP'of ItemInWorldManager (as EntityPlayerMP.java does——assign 'this' to thisPlayerMP in its constructor).
This causes no problem on single player mode, because field 'thisPlayerMP' is never used in such condition.
When on bukkit server, PlayerEvent generated by this class might be cancelled, and  field 'thisPlayerMP' will be used ,thus resulting in NPE.

Possible fix:
assign the fakeplayer to ItemInWorldManager.thisPlayerMP
change from ...
``` 
TileInfusionClaw.java

if (this.im == null) {
    this.im = new ItemInWorldManager(world);
 } else {
    this.im.setWorld((WorldServer) world);
 }

 ```
... to ...
 ```
TileInfusionClaw.java

if (this.im == null) {
    this.im = new ItemInWorldManager(world);
   this.im.thisPlayerMP=fakePlayer;
 } else {
    this.im.setWorld((WorldServer) world);
 }

```
![P@3SQ3X1 1`$LB_$FE@%EI3](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/117543727/21e8c268-53b1-495c-9a22-23ba5802576e)
field_73090_b(a.k.a. thisPlayerMP) IS null on sigle player

![8A7)9S{BTIN8W`$W@1R3M}D](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/117543727/856a288e-e5b2-4e79-bf86-321736c634ea)
decompiled ItemInWorldManager.class dumped from Thermos server, when event canceled, field_73090_b(a.k.a. thisPlayerMP) is used

![VN@1LR3VM39D_KSSS{_(A_K](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/117543727/22d7bd87-2d92-48aa-bd56-1c3a600ba6a1)
manually cancel the forge PlayerInteractEvent, and the SP game crashes the same way as dedicated server(with same stacktrace)

I tried version 2.3.0, 2.3.4, 2.4.0, they are all the same. 

### Crash Report

dedicated server crashreport
[crash-2023-04-16_19.39.29-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13263829/crash-2023-04-16_19.39.29-server.txt)

signle player crashreport when PlayerInteractEvent is cancelled
[crash-2023-11-06_14.21.04-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13263848/crash-2023-11-06_14.21.04-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Hekkmac** [comment]
Major now in 2.5.1, every time infusion claw triggers -> Server Crash with Java 21.
No Problems  on 2.4.0 with Java 8.

Even Items render wired:
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76559913/a8a03744-554d-41c8-a092-a97be615fba9)

**Comment by Hekkmac** [comment]
i updated to 2.5.1 and installed ServerUtils. Every time infusion claw fired -> server crash!
Changing to this settings fixed it:(in ServerUtils)
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76559913/55978260-7c78-4ae6-9243-87912619f049)

**Comment by Dream-Master** [comment]
> ### Your GTNH Discord Username
> _No response_
> 
> ### Your Pack Version
> 2.4.0
> 
> ### Your Server
> private server
> 
> ### Java Version
> Java 8
> 
> ### Type of Server
> Thermos
> 
> ### Your Actions
> Active an Infusion Claw on Thermos server witch AuthMeReloaded and the server crashes. reopen old issue #3027
> 
> Possible cause: TileInfusionClaw.java uses ItemInWorldManager to simulate player RMB click, but it just create one ItemInWorldManager instance without setting field 'thisPlayerMP'of ItemInWorldManager (as EntityPlayerMP.java does——assign 'this' to thisPlayerMP in its constructor). This causes no problem on single player mode, because field 'thisPlayerMP' is never used in such condition. When on bukkit server, PlayerEvent generated by this class might be cancelled, and field 'thisPlayerMP' will be used ,thus resulting in NPE.
> 
> Possible fix: assign the fakeplayer to ItemInWorldManager.thisPlayerMP change from ...
> 
> ```
> TileInfusionClaw.java
> 
> if (this.im == null) {
>     this.im = new ItemInWorldManager(world);
>  } else {
>     this.im.setWorld((WorldServer) world);
>  }
> ```
> 
> ... to ...
> 
> ```
> TileInfusionClaw.java
> 
> if (this.im == null) {
>    this.im = new ItemInWorldManager(world);
>   this.im.thisPlayerMP=fakePlayer;
> } else {
>    this.im.setWorld((WorldServer) world);
> }
> ```
> 
> ![P@3SQ3X1 1`$LB_$FE@%EI3](https://private-user-images.githubusercontent.com/117543727/280624872-21e8c268-53b1-495c-9a22-23ba5802576e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjE3MTMsIm5iZiI6MTcwMzg2MTQxMywicGF0aCI6Ii8xMTc1NDM3MjcvMjgwNjI0ODcyLTIxZThjMjY4LTUzYjEtNDk1Yy05YTIyLTIzYmE1ODAyNTc2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxNDUwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OTM3MmY1YjQwNWFiNTYzODUxMDg5NmI4ODAyZjBlMmQ0MzAxMTdiMzZhNjI5OTYzMmQyNDZiNmVkZTQzYjE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZAleBuDExGAd5Xa5T4VJRhdaQ5kuUJH3CG4Pj_Dturo) field_73090_b(a.k.a. thisPlayerMP) IS null on sigle player
> 
> ![8A7)9S{BTIN8W`$W@1R3M}D](https://private-user-images.githubusercontent.com/117543727/280625468-856a288e-e5b2-4e79-bf86-321736c634ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjE3MTMsIm5iZiI6MTcwMzg2MTQxMywicGF0aCI6Ii8xMTc1NDM3MjcvMjgwNjI1NDY4LTg1NmEyODhlLWU1YjItNGU3OS1iZjg2LTMyMTczNmM2MzRlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxNDUwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTIxZmMxN2JlNTMxOGM2Mjc2ZjRlZDIwY2M0MjRiM2I5Mjg4NmJlMjRlNmVjNzEwNjk0MzNiNWZjYThmNjg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OSyvJC55OwJzfC9Na90NOA4Rsa0ernRsxcTaXXbeK8k) decompiled ItemInWorldManager.class dumped from Thermos server, when event canceled, field_73090_b(a.k.a. thisPlayerMP) is used
> 
> ![VN@1LR3VM39D_KSSS{_(A_K](https://private-user-images.githubusercontent.com/117543727/280626053-22d7bd87-2d92-48aa-bd56-1c3a600ba6a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NjE3MTMsIm5iZiI6MTcwMzg2MTQxMywicGF0aCI6Ii8xMTc1NDM3MjcvMjgwNjI2MDUzLTIyZDdiZDg3LTJkOTItNDhhYS1iZDU2LTFjM2E2MDBiYTZhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjMxMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyOVQxNDUwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZTc4NTcyYTY3NmI3NGE5ZDAyODkxNmFkMDY4MmZlNmYwNDQzMTA0N2U3NGQ0ZGYwNjc2YjkyODY3ODVkODM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6aqwUeIKwaznCPHSXLPV6JrK7n-tFVC0ws9XIDOmGCQ) manually cancel the forge PlayerInteractEvent, and the SP game crashes the same way as dedicated server(with same stacktrace)
> 
> I tried version 2.3.0, 2.3.4, 2.4.0, they are all the same.
> 
> ### Crash Report
> dedicated server crashreport [crash-2023-04-16_19.39.29-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13263829/crash-2023-04-16_19.39.29-server.txt)
> 
> signle player crashreport when PlayerInteractEvent is cancelled [crash-2023-11-06_14.21.04-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13263848/crash-2023-11-06_14.21.04-server.txt)
> 
> ### Final Checklist
> * [x]  I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
> * [x]  I can reproduce this crash consistently by following the exact steps I described above.
> * [x]  I have asked other people and they confirm they also crash by following the exact steps I described above.

feel free to post a fix.

**Comment by boubou19** [comment]
you play with a cracked server. Try again in a supported configuration.

**Comment by Hekkmac** [comment]
Wow, i don't and bug is real.
