### ISSUE TITLE
Imposible to complete Violence Is Blue Quest

### ISSUE THREAD

**Issue by jose9222** [GTNewHorizons/GT-New-Horizons-Modpack#14840]
### Your GTNH Discord Username

jose_oton

### Your Pack Version

2.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Expectation

I try to complete the Violence Is Blue quest on the botania tab (Get a Dreadthorne) 

### The Reality

I can't because the "Enderlotus" flower from Biomes O' Plenty is not obtainable, this flower only spawns in the end in a block called "Spectral Moss" , but this block doesnt spawn naturally nor is it obtainable by any means making the quest impossible to get (The flower and the block are still on NEI), this is probably caused by the HEE generation overlapping (same as uncrafteable ambrosia due to Celestial Crystal Shard generation)

### Your Proposal

Change the Dreadthorne apothecary recipe or give the Enderlotus flower a crafting recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you can get them with bees right?

**Comment by Ethryan** [comment]
Might wanna create a different way too for those that don’t like bees.

**Comment by chochem** [comment]
tested and yes its obtainable
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/ea89d1c0-fa43-407e-8a1f-d9c1d50e5965)
