### ISSUE TITLE
Xenoxene lacks fluid canner recipe/universal cell ID, cannot be partitioned with AE2

### ISSUE THREAD

**Issue by SMSum** [GTNewHorizons/GT-New-Horizons-Modpack#14858]
### Your GTNH Discord Username

summer_g123

### Your Pack Version

2.4.0

### Your Server

Private

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Tried to partition an ME fluid cell to Xenoxene but couldn't find a cell, attempted to push the fluid into cell w/ interface + tank and it goes inside

### The Reality

You cannot partition the cell based on it contents from that either. There is currently no way I can find to partition an ME fluid cell to Xenoxene

### Your Proposal

Add listing for xenoxene in cell format/support xenoxene partitioning on AE2FC.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
Use universal fluid cell wit xenoxene for partition

**Comment by SMSum** [comment]
> Use universal fluid cell wit xenoxene for partition

This works, still probably shouldnt have to resort to using this to partition the fluid considering every other fluid has a cell to readily use.
