### ISSUE TITLE
Add EXTREME BIG EXPLOSIONS to Colen machines

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#14851]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.3.7

### Your Proposal

Touch plasma mixer while working? BOOM HALF OF YOUR BASE DOSNT EXISTS ANYMORE
Touch DTPF? NOBODY WILL KNOW THAT THERE WAS BASE
EOH? EVEN DIM DOENT EXISTS

Rain?

### Your Goal

Late game ppl too relaxed, they forgot the basics

### Your Vision

We have many machines that can explode before lategame, but on lategame we dont get new :(

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Connor-Colenso** [comment]
No.
