### ISSUE TITLE
Wireless Data for Asslines

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#14855]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.4.0

### Your Proposal

We need some kind of wireless data access hatches for asslines for example to avoid spamming data banks cause it would be more efficient in terms of performance instead of spamming more multis

### Your Goal

Get wireless data from data banks

### Your Vision

Less data banks for assline spam in endgame

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by SMSum** [comment]
I liked the idea, implemented it and there is a PR on the TecTech branch.

https://github.com/GTNewHorizons/TecTech/pull/255

Not within my authority but I'd say that probably all future suggestions/requests be forwarded towards the PR. Thanks :)
