### ISSUE TITLE
Extruder has a superfluous machine face on the top

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#14850]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Extruder would be normal

### The Reality

The basic extruder has a machine face on the top of it, in addition to the actual machine face:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/533931/be29f846-0544-44df-8eb0-210accc165f7)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
Wdym fix? It always has been like this and i like it.
