### ISSUE TITLE
Vibrant Alloy plate solidifier recipe wrong

### ISSUE THREAD

**Issue by SMSum** [GTNewHorizons/GT-New-Horizons-Modpack#14869]
### Your GTNH Discord Username

summer_g123

### Your Pack Version

2.4.0

### Your Server

private server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

NEI recipe for solidifying vibrant alloy into plates shows it will output a gregtech plate
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/39743349/742fdbe1-e361-4d09-9f42-1259491bf155)

### The Reality

It outputs GT++ plate and the craft never finishes without manual adaptation of the pattern for this one specific material.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/39743349/e9052e98-8aad-4a2a-90ae-a497bd326acb)

### Your Proposal

Fix the output of said recipe :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GTplusplus/pull/729
these gt++ plates dont exist anymore
