### ISSUE TITLE
Give heretics the crimson rite

### ISSUE THREAD

**Issue by Star-Tube** [GTNewHorizons/GT-New-Horizons-Modpack#14860]
### Your GTNH Discord Username

Star_Tube

### Your Pack Version

2.4.0

### Your Proposal

Add a trade to the Heretic Villager to grant the Crimson Rite tome. This grants a thematically consistent method for the player to get access to the Crimson Rite research in thaumcraft without having to fight the Crimson Cultists. Ideally it should probably require something from within Thaumcraft probably gated past MV or HV or possibly in the Eldritch tab (void metal comes to mind) or requiring warp to research or craft (maybe a madman's lens?)

### Your Goal

Give more purpose to the heretic other than the profane wand. Also to grant peaceful mode challenge a method of getting the last millenium dimension.

### Your Vision

Players would be more easily able to get the Crimson Rite without rng drop-rates or combat requirements getting in their way.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
Yeah possibly if someone proposed a recipe

**Comment by EnderProyects** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/1c32b274-c653-45b2-b23a-3941de45b5df)
Something like this could suit well,

**Comment by Alastors** [comment]
> ![image](https://user-images.githubusercontent.com/45178400/281756150-841a8ac9-1ca2-4bbb-8b4c-53773eaec7c2.png)
> Something like this could suit well,

Lmfao no, miss me with those Steve’s Cart’s Eyes and BM

**Comment by EnderProyects** [comment]
The Bm is for the blood of the tome, it could use some kinf of blood like ghast blood of T.forest, and the eye of galagor is for replacing the ones used in the eldrich eyes

**Comment by EnderProyects** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/94a6882c-ee59-47c6-a007-fae19423aa04)
If this suits better xd, is fiery blood and a sacrificial knife
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/80e18609-eac3-4e0c-aa8e-3db8530b0d4e)

**Comment by Star-Tube** [comment]
I'm not sure if there is a source later for the mixed fragments but atm they seem like the hardest thing to source there. Otherwise it looks good.

**Comment by EnderProyects** [comment]
Is not hard, is rosa misteria + mixed crystal block

**Comment by Alastors** [comment]
> ![image](https://user-images.githubusercontent.com/45178400/281760120-94a6882c-ee59-47c6-a007-fae19423aa04.png)
> If this suits better xd, is fiery blood and a sacrificial knife
> ![image](https://user-images.githubusercontent.com/45178400/281760293-80e18609-eac3-4e0c-aa8e-3db8530b0d4e.png)

No blood magic man

**Comment by EnderProyects** [comment]
lmao is just a knife

**Comment by Alastors** [comment]
> lmao is just a knife

The answer is no, end of story

**Comment by Star-Tube** [comment]
Maybe some voidmetal or voidseeds could replace the vials there to represent the warped nature of the cult.

**Comment by Alastors** [comment]
> Maybe some voidmetal or voidseeds could replace the vials there to represent the warped nature of the cult.

Def in favour of the seeds

**Comment by Alastors** [comment]
@EnderProyects if you want a knife, literally part of Tainted Magic is the Crimson Cult module

**Comment by Alastors** [comment]
> the vials are for the blood on the cover, they are from the twilight forest

There’s already crimson cult blood in tainted magic

**Comment by EnderProyects** [comment]
Yea, but you need the rites in order to get the research for that blood, and you are crafting here the rites

**Comment by Star-Tube** [comment]
I need to check the prereqs but crimson cult attire might also be pre-crimson rite and might be usable. just checking the research chains now.

**Comment by Alastors** [comment]
> I need to check the prereqs but crimson cult attire might also be pre-crimson rite and might be usable. just checking the research chains now.

I’m pretty sure it’s pre crimson

**Comment by Star-Tube** [comment]
Yep, just checked and it seems to be pre-crimson so they could be needed to be worn to use the crimson rite or used in infusing it. idk mostly spitballing.

**Comment by EnderProyects** [comment]
Oh, then replace the blood with crimsom blood and the knife with crimsom cap

**Comment by Star-Tube** [comment]
Also as far as essentia I would think that Ira, Strontio and Alienis would make sense. Maybe even Vesania but I don't know of a source for that yet...

**Comment by Alastors** [comment]
> Also as far as essentia I would think that Ira, Strontio and Alienis would make sense. Maybe even Vesania but I don't know of a source for that yet...

There's not a source of Vesania besides wisps so no, and no strontio

**Comment by Star-Tube** [comment]
Looks like strontio can be sourced from Alumite but I don't mind.

**Comment by EnderProyects** [comment]
Praecantatio, telum and cognitio also suits well

**Comment by Alastors** [comment]
> Praecantatio, telum and cognitio also suits well ( in addition to the other aspects)

How does Telum suit it

**Comment by EnderProyects** [comment]
Since is the weapon aspect and the cult only use violence

**Comment by Alastors** [comment]
> Since is the weapon aspect and the cult only use violence

Ehhh, I don't really see the connection so much, perhaps instrumentum instead, or maybe even a new magic tool aspect or something

**Comment by Star-Tube** [comment]
Victus or Sano might represent the blood infused into the book if there isn't a better option... I'm not entirely sure of the established lore for the crimson cult nor if the pack has any ideas already for what they are meant to represent other than "that warp cult over there"

**Comment by Star-Tube** [comment]
Iter for their dimensional travel could be an option.

> they are not even a warp cult, since the warp atacks them

Ah. fair enough. My lack of knowledge on them is clear then.

**Comment by Star-Tube** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50463083/8a490f0e-e1ef-4cd6-9c08-8fddbccd7b82)

This is my edited proposition. The top right are some options for things which could be put in the top middle spot. The snow-queen blood may gate it too late depending on opinions, the botania vial obviously requires botania which I suspect maybe unwanted and the GT blood vial would need a new recipe which idk what that might be. I also don't know much about the tainted magic vial's source barring that it uses the crystal dagger which should be available pre-rite but since @Alastors mentioned it I thought I would include it. I am leaning toward the bucket o' blood or the snow-queen blood personally depending on gating.

**Comment by Alastors** [comment]
> ![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50463083/8a490f0e-e1ef-4cd6-9c08-8fddbccd7b82)
> 
> 
> 
> This is my edited proposition. The top right are some options for things which could be put in the top middle spot. The snow-queen blood may gate it too late depending on opinions, the botania vial obviously requires botania which I suspect maybe unwanted and the GT blood vial would need a new recipe which idk what that might be. I also don't know much about the tainted magic vial's source barring that it uses the crystal dagger which should be available pre-rite but since @Alastors mentioned it I thought I would include it. I am leaning toward the bucket o' blood or the snow-queen blood personally depending on gating.

Crystalizing dagger on the top 

Cultist blood instead of the wither skulls

**Comment by Star-Tube** [comment]
That foci is Effreet's flame from Thaumic Tinkerer... not sure if that changes anything but I don't mind switching it for void metal (even up to a void metal block or charged void metal cap would be balanced but probably an ingot would make thematic sense)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50463083/9c1af3eb-ba62-466c-ac1d-df365040abf5)
Here is the recipe after those changes and I am happy with it either with the void metal ingot/block/cap or the efreet foci.

**Comment by LazyFleshWasTaken** [comment]
> That foci is Effreet's flame from Thaumic Tinkerer... not sure if that changes anything but I don't mind switching it for void metal (even up to a void metal block or charged void metal cap would be balanced but probably an ingot would make thematic sense)
> 
> ![image](https://user-images.githubusercontent.com/50463083/281799448-9c1af3eb-ba62-466c-ac1d-df365040abf5.png) Here is the recipe after those changes and I am happy with it either with the void metal ingot/block/cap or the efreet foci.
> 
> (edit: I am also glad for the lack of wither skulls because those are a pain to get in peaceful in my experience so far... but pain is what I come to Greg for so I shouldn't complain)

idk about others, but this is great cuz skyblock can make it, unless the knife has a weird recipe. Also, the research itself could be gated behind something like scanning an eldritch guardian, like the anti-tain plant in the alchemy tab.

**Comment by Alastors** [comment]
> That foci is Effreet's flame from Thaumic Tinkerer... not sure if that changes anything but I don't mind switching it for void metal (even up to a void metal block or charged void metal cap would be balanced but probably an ingot would make thematic sense)
> 
> 
> 
> ![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50463083/9c1af3eb-ba62-466c-ac1d-df365040abf5)
> 
> Here is the recipe after those changes and I am happy with it either with the void metal ingot/block/cap or the efreet foci.
> 
> 
> 
> (edit: I am also glad for the lack of wither skulls because those are a pain to get in peaceful in my experience so far... but pain is what I come to Greg for so I shouldn't complain)

Yeah this recipe would work for me

**Comment by EnderProyects** [comment]
The skulls where palced in refernce of the skull in the book

**Comment by Star-Tube** [comment]
> The skulls where palced in refernce of the skull in the book

Yeah they make thematic sense but sounds like they don't make progression sense so I would tend to agree with people who know more about the magic/thaumcraft progression and the progression with certain challenges.

**Comment by EnderProyects** [comment]
P.s you could change the void ingot with the thaumic alloy, it makes more sense since is like a plate, suits well in progression, and looks like the covers of the rites

**Comment by Star-Tube** [comment]
> P.s you could change the void ingot with the thaumic alloy, it makes more sense since is like a plate, suits well in progression, and looks like the covers of the rites

Not sure it makes thematic sense personally but it does make progression sense.

**Comment by LazyFleshWasTaken** [comment]
Would it be possible to also make a recipe for the banners? They also gate Kami :/

**Comment by EnderProyects** [comment]
That could be a crafting recipe that use a normal thaum banner ( red) greatwood, crimsom platings or blood, and string of some tipe ( like gold string or mana string)

**Comment by EnderProyects** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/90741d93-b54a-46c9-af95-076d08ef6a31)
1 Greatwood rod, 1 red banner, 3 crimson stained cloth, 4 golden thread

**Comment by Alastors** [comment]
> ![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/90741d93-b54a-46c9-af95-076d08ef6a31)
> 
> 1 Greatwood rod, 1 red banner, 3 crimson stained cloth, 4 golden thread

Frankly you could remove the greatwood rod, but this looks fine to me

**Comment by EnderProyects** [comment]
Well, then change the banner with some kind of cape, or leather

**Comment by LazyFleshWasTaken** [comment]
Ok, so I was looking through options, and banners/flags/capes/etc. are really limited for some reason. I found one perfect for it, though: crimson-stained cloth. It's in tainted magic and is used for the creation and upgrade of crimson cult armour. It's gated behind shadow metal and firey blood, therefore gating behind Ev/freezer. 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40587985/fb1c72be-f214-48c7-bba0-309ab044dc1d)

Another 2 that may fit: bloody enchanted fabric and nullified leather. One is thaumcraft the other witchery. The nullified leather is 8 leather around a null catalyst, the one that's used to dupe nether stars.

**Comment by LazyFleshWasTaken** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40587985/709f2392-b60c-42d9-840c-62f08f4051d8)

Here's the one redone: Crimson cloth, Crimson plating in the middle, Greatwood for the stake, and Witching Gadgets Golden Thread as binding.

**Comment by kyoi-the-fox** [comment]
i know this is technically closed,but if if I submitted a pull request would you still be interested in adding it, and if so what should the research look like? I was thinking eldritch revelation or a new research dependent on it for both book and banners.

**Comment by EnderProyects** [comment]
If you add the proposed recipes is ok I think
