### ISSUE TITLE
Quick one-way pipes

### ISSUE THREAD

**Issue by evgengoldwar** [GTNewHorizons/GT-New-Horizons-Modpack#14868]
### Your GTNH Discord Username

EvgenWarGold

### Your Pack Version

2.4.2

### Your Proposal

Now the pipes are closed by clicking each pipe. Why not do it the same way as with painting laser pipes, so that the entire pipe line is closed 1 click.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/69961523/3a62ffde-7d5b-409e-a1f2-c3b080e22e76

### Your Goal

Helps beginners close pipes.

### Your Vision

Easier to manage pipes with low tires

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
hmm video didn't finish loading

**Comment by evgengoldwar** [comment]
> hmm video didn't finish loading
> 
> The idea is with a pipe, if you (shift+ctrl or something maybe just shift) right click with the wrench to make it one way, it makes ALL the pipes it's connected to one way (until it reaches a end or a cross) I believe

Upload video

**Comment by bombcar** [comment]
This should have a limit to how far "it will go" and I propose 65 pipe segments without a cross or T at which point it prints a message like "maybe you need to use a LDFP"
