### ISSUE TITLE
can the heart colors be more distinguishable?

### ISSUE THREAD

**Issue by EndlessGemji** [GTNewHorizons/GT-New-Horizons-Modpack#14864]
### Your GTNH Discord Username

gemji

### Your Pack Version

2.4.0

### Your Proposal

third and fourth heart color (counted from the basic color so red>orange>light green>light green) looks the same for red green colorblindness, is it possible to make the colors more distinguishable?

### Your Goal

third and fourth heart color looks the same for red green colorblind people.

### Your Vision

people with similar color blindness could differentiate the hearts.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EndlessGemji** [comment]
![2023-11-10_07 49 09](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/111256730/4f5544bd-634b-4bad-a2a0-531e350496e4)

**Comment by Star-Tube** [comment]
Would it be possible to have either an item or a ui option to display health as a solid health bar with number?

**Comment by bombcar** [comment]
I believe you can use IngameXML to show health data.

**Comment by chochem** [comment]
and even without any such changes you can check your total heart count (as a number) in the equipment screen
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/5a511d3f-498f-4c98-b72c-1d594e1fe623)

**Comment by Star-Tube** [comment]
> and even without any such changes you can check your total heart count (as a number) in the equipment screen ![image](https://user-images.githubusercontent.com/40274384/282260319-5a511d3f-498f-4c98-b72c-1d594e1fe623.png)

The point of having an option to display it as a number would be to know what your current health is accurately, not your current max health.

**Comment by bombcar** [comment]
Anyone interested in looking into it (and starting their dev journey!) can start here: 

https://github.com/GTNewHorizons/TinkersConstruct/blob/master/src/main/java/tconstruct/client/HealthBarRenderer.java

Or potentially add a config option to override src/main/resources/assets/tinker/textures/gui/newhearts.png
![](https://github.com/GTNewHorizons/TinkersConstruct/blob/master/src/main/resources/assets/tinker/textures/gui/newhearts.png)

**Comment by Hikari1nVoid** [comment]
Hey why not just display the HP bar as numbers?
