### ISSUE TITLE
thaumcraft research table went back to old layout (zeta server only)

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#14876]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.4.2 build 217

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/a60381a0-5bd9-4eb4-b5b4-bfca75cf66b2)

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/020593df-aa59-4aa6-ae10-f9b393af9e5e)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Cannot reproduce in 219, can you post full FML log?

**Comment by bombcar** [comment]
Turns out it only happens when connected to Zeta

**Comment by Dream-Master** [comment]
The mod from Elan is not on Zeta because he told me it’s a client mod. I try to re add it later and we can test it again

**Comment by TheElan** [comment]
That's odd, I clearly remember being able to use it without having it on the server side. I am not sure what is going on here, if it helps - add it to server for now, I'll investigate some time later.

**Comment by miaowwwwww** [comment]
fixed, we need the mod in server, haha

**Comment by Dream-Master** [comment]
ok i add it to zeta and it works fine.
