### ISSUE TITLE
Crashes then search in BetterQuesting

### ISSUE THREAD

**Issue by bm2ademon** [GTNewHorizons/GT-New-Horizons-Modpack#14878]
### Your GTNH Discord Username

bm2ademon#7470

### Your Pack Version

2.4.2 (2023-10-13)

### Your Server

sole client

### Java Version

Java 8

### Type of Server

None

### Your Actions

Open Quests
Push @Search@
Start typing.
Game crashes on 1st-4th letter

### Crash Report

[crash-2023-11-12_15.59.46-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13328057/crash-2023-11-12_15.59.46-client.txt)
[crash-2023-11-12_16.00.35-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13328058/crash-2023-11-12_16.00.35-client.txt)
[crash-2023-11-12_16.08.14-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13328059/crash-2023-11-12_16.08.14-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
hmm, a nightly from a month ago. did you check on a more current nightly?

**Comment by Pxx500** [comment]
Update the game

**Comment by bm2ademon** [comment]
[crash-2023-11-13_22.56.29-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13340759/crash-2023-11-13_22.56.29-client.txt)
[crash-2023-11-13_22.56.51-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13340760/crash-2023-11-13_22.56.51-client.txt)
[crash-2023-11-13_23.06.38-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13340761/crash-2023-11-13_23.06.38-client.txt)
[crash-2023-11-13_23.11.50-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13340762/crash-2023-11-13_23.11.50-client.txt)
 I`ve updated to [2.4.2-nightly-2023-11-12]. The problem is still here.

**Comment by bombcar** [comment]
Mine doesn’t crash - what exact search term did you use?

**Comment by bm2ademon** [comment]
any. it doesn`t matter

**Comment by bombcar** [comment]
I cannot get this to reproduce, but I have optifine.

It's almost certainly a rendering issue caused by something, but I can't trigger it, even after going into view mode and going to every tab, or searching various strings.

**Comment by Pxx500** [comment]
> [crash-2023-11-13_22.56.29-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13340759/crash-2023-11-13_22.56.29-client.txt)
> [crash-2023-11-13_22.56.51-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13340760/crash-2023-11-13_22.56.51-client.txt)
> [crash-2023-11-13_23.06.38-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13340761/crash-2023-11-13_23.06.38-client.txt)
> [crash-2023-11-13_23.11.50-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13340762/crash-2023-11-13_23.11.50-client.txt)
>  I`ve updated to [2.4.2-nightly-2023-11-12]. The problem is still here.
> If ### kubatech mod is off, then all is ok.

From the logs it looks like you didn't update the game correctly since the kubatech version doesn't match

**Comment by chochem** [comment]
yep, pxx is right. based on the gt version you are on a build from around september 24-27. Which probably means 2.4.1.

I think what has happened is clear. you just updated the QB (or probably the entire config repo) but not the actual pack. That doesnt work of course. here is the wiki for nightlies https://wiki.gtnewhorizons.com/wiki/Nightly_Builds, though I would **highly** recommend you just stay on stable, or at least proper released dev versions.
