### ISSUE TITLE
Batter Tool Box

### ISSUE THREAD

**Issue by GreedReaper117** [GTNewHorizons/GT-New-Horizons-Modpack#14871]
### Your GTNH Discord Username

peter117#9393

### Your Pack Version

2.4.0

### Your Proposal

I suggest adding a new item called Electric Tool Box. So that the tools in the toolbox can be charged/Not waste energy.

### Your Goal

I noticed by accident that in the basic toolbox you cannot charge items that have their own energy. Therefore, I suggest adding such an item or changing the current one so that you can load your tool easily and conveniently.

I hope my proposal will be listened to :)

### Your Vision

A new item to achieve in the Quest book, an item that will be especially useful for those who use the toolbox.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GreedReaper117** [comment]
> You can charge them if you wear appropriate ic2 armor/bat/lappack. Someone also claimed on discord that wireless chargers charge the tools inside, but i cant confirm rn. ic2 armor definitely works.

The main problem I am referring to is the fact that after putting tools into the toolbox and using them, energy is consumed and is not charged in any way unless the tool is removed from the toolbox. Which is moderately effective in my opinion. My assumption is that the energy that would naturally be taken from the tools will be taken from the toolbox, which can be charged normally. Of course, the function of loading tools in it is an addition/2 option if it is easier to implement in the code.

**Comment by vovaksenov** [comment]
I never have to take out my tools from the toolbox and they are always charged automatically anyway. I dont think i understand your problem

**Comment by GreedReaper117** [comment]
> I never have to take out my tools from the toolbox and they are always charged automatically anyway, while they stay inside. I dont think i understand your problem

if you say so, I probably have a bug that prevents items from being charged in the toolbox. Using Remote Charging from GregTech which I have

**Comment by vovaksenov** [comment]
As i said before, mine get charged due to me wearing ic2 armor. I was not sure about if wireless worked as it was a claim made by someone else. If you say it doesnt work, they were probably mistaken. If they dont get charged by wireless, then yes, it should be implemented.
