### ISSUE TITLE
Fluid Processing Patterns and the Assembly Line

### ISSUE THREAD

**Issue by BobGoldham** [GTNewHorizons/GT-New-Horizons-Modpack#14877]
### Your GTNH Discord Username

@bobgoldham

### Your Pack Version

2.4.0

### Your Proposal

For the Fluid Processing Pattern Terminal to have the "put fluids first" mode be its default setting, not an option that has to be explicitly enabled.

I'm not certain how exactly the logic works here, but it should be as simple as to invert a default flag or a check somewhere.

### Your Goal

The FPPT is used almost exlusively for assemblyline recipes.
The "fluids first" mode **actually works relatively well** with assemblyline recipes.

... It doesn't really get much more obvious than that.

Moreover, the default mode leads to frequent breakages in which basically everyone who automates an assline with ae2fc for the first time has to come to the Discord, ask, be confused and go through a whole cycle-of-grief before realizing they can just click a button and then only have to just  _redo all their existing patterns_. This is not ideal. In fact, it is very annoying for everyone involved.

### Your Vision

A world in which ae2fc patterns in the assline work out-of-the-box, without needless confusion.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Afaik there is no explicit use case for the "fluids last" mode. Imo the option could be removed outright after reversing the default to clean up the buttons a bit.
