### ISSUE TITLE
Enhance Crop Matrix and Crop Harvester or remove them

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#14885]
### Your Pack Version

2.4.0

### Your Proposal

You can consider reducing their power consumption. The power consumption of 32eu/t is too much compared to the consumption of 4eu or 1eu per operation of Lv Crop Manager
Or modify the tasks, don't let players make them anymore

### Your Goal

The Crop Matrix and Crop Harvester are really weak. Their combined functionality is equivalent to the LV Crop Manager, and they consume a lot more power.
They are not as good as Lv Crop Manager in terms of energy consumption, wiring, and cost。
But there are two tasks that require me to manufacture them。

### Your Vision

It will definitely make the package better

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
I think it is intended for crop managers to be better. I would leave the ic2 ones in the pack at least to not break existing setups, but yes, it should be mentioned somewhere in the QB or tooltip that their use is discouraged.

**Comment by LazyFleshWasTaken** [comment]
The crop harvester has a very specific use: Harvesting before maturity for crops like potatoes, ore berries, and a few other niche crops. Crop manager harvests only at maturity. If the crop harvester wasn't gated by aluminium, we would have used it to harvest xp ore berries due to the increased production from harvesting early vs full maturity.

**Comment by chichun2002** [comment]
The quest should be replaced with the lv crop manager, much cheaper to make while being just as good outside of nieche cases

**Comment by chichun2002** [comment]
reopen

**Comment by chichun2002** [comment]
reopen
