### ISSUE TITLE
Assembling machine doesn't assemble anything

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#14883]
### Your GTNH Discord Username

bombcar

### Your Pack Version

GTNH-2023-11-10+217-mmcprism-new-java

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

I wanted to make a wood to iron chest upgrade

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/533931/3ebf5c5f-9c45-4e1c-9f70-2489290dcbfb)

it sits there doing nothing

machine is powered (battery is charged) and it is not disabled (checked with mallet)

Now interestingly enough NEI is only shifting through SOME woods out of the entire oredict, but I'd think "oak wood" would work even in "jungle wood" was excluded

### Your Proposal

Check oredicts on assembler recipes 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Wrenching it and putting in "Redwood planks" which do appear in NEI - still no work

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/533931/cbb14ab5-a2d0-4333-85a6-7adf20b8b74c)

Tried it with a real circuit, too.

**Comment by bombcar** [comment]
Confirmed apparently *no* assembler recipes work (can't make a chest) so trying the latest from GitHub 

Latest from GitHub fails.

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13342670/fml-client-latest.log)

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/23f1ff20-7d69-4120-ac4c-eb258514d8d0)
works on my nightly-219 instance with gregtech-5.09.44.77

**Comment by bombcar** [comment]
Confirmed, 77 worked, 78 doesn't

I suspect: https://github.com/GTNewHorizons/GT5-Unofficial/pull/2358/files

**Comment by chochem** [comment]
I thought you are on a much older nightly? I guess it was just a typo in the ticket?

**Comment by bombcar** [comment]
I'm not sure how it registers, I'm on GTNH-2023-11-10+217-mmcprism-new-java with a few changes from GitHub (mainly I had pulled in the latest GT5 which blew up)

**Comment by bombcar** [comment]
Ok now I'm terribly confused, because .77 didn't work either, maybe my pack is corrupt somehow. Will do a complete redownload of the nightly.

**Comment by bombcar** [comment]
`GTNH-2023-11-13+220-mmcprism-new-java` is also broke

**Comment by bombcar** [comment]
A fresh download of the "zeta nightly" and a creative world doesn't work.

Machine has power (both basic and advanced tried) and tricorder says "not enough power".

Tried oak and redwood planks

**Comment by bombcar** [comment]
Ok so my test world in creative will make chests (wood + 8) but will not make the upgrades (wood + dense iron plates x3, circuit 2)

**Comment by Dream-Master** [comment]
@HoleFish any idea ?

**Comment by bombcar** [comment]
I'm now leaning to it being something with the chest upgrade recipe itself, but it worked for @chochem - I can't get it to work in any nightly

**Comment by Dream-Master** [comment]
@bombcar https://github.com/GTNewHorizons/GT5-Unofficial/pull/2364

**Comment by chochem** [comment]
looks like the recipes are just gone in nightly 220

**Comment by bombcar** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/2364 fixes it

**Comment by chochem** [comment]
collision count in the recipe debug is up from around 10k normally to 56k. meaning that 46k recipes are falsely flagged as collisions and removed. ouch.
