### ISSUE TITLE
Add support for Rainbow Cactus in the EIG

### ISSUE THREAD

**Issue by srdr2k3** [GTNewHorizons/GT-New-Horizons-Modpack#14882]
### Your GTNH Discord Username

@srdra

### Your Pack Version

2.4.0

### Your Proposal

What the title says. 
Add Rainbow Cactus support to the EIG for faster dye production.

### Your Goal

EIG supports normal crops. Rainbow Cactus is a crop, so it should be supported.
Also would make getting dyes in bulk way simpler.

### Your Vision

A world with color is a happy world :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by mitchej123** [comment]
I believe things like cinderpearl were made into crops in crops++ and then magically worked here.  Id suggest the same route for rainbow cactus and any others we want to work here

**Comment by vovaksenov** [comment]
No, i dont like the crops++ way. EIG is very underwhelming even when using max stats on those seeds because it stacks only to 1 instead of 64 per slot. This is why everyone uses sweed over sugar beet.

**Comment by mitchej123** [comment]
If it's not a crop, it has no business being in the EIG.  Adding it as a crop is the correct way to do this; and if there are issues with seeds those should be addressed.  EIG works off of ic2 crops, and crops++ is the best place to add that.

>  max stats on those seeds because it stacks only to 1 instead of 64 per slot

If you're talking about seeds, you're incorrect - I adjusted seeds a while back so seeds with the same NBT.  If it's something EIG specific then I'm unclear on the issue.

**Comment by vovaksenov** [comment]
Afaik, the 1 seed per stack issue is EIG only sence around 2.3.7. Otherwise, as you said, they stack now.

**Comment by mitchej123** [comment]
That feels like something that should be addressed then unless it's intended, especially if other things stack?

**Comment by EnderProyects** [comment]
I dont think that placing a annihilation plane on top of the cacti is to much work

**Comment by vovaksenov** [comment]
Its not about how much work it takes. It is about appropriate solutions for the tier you are in. Why should you keep the annihilation plate farm when everything else is either getting moved to eig or demolished?

**Comment by srdr2k3** [comment]
The issue is about getting faster dye out of rainbow cacti. Annihilation plane would just lead to a tps/fps waste. 

Most vanilla and magic crops work in the EIG normal seeds mode, I don't get why the rainbow cacti should not be working.

**Comment by mitchej123** [comment]
The EIG was made to reduce entities/in world interactions... an annihilation plane is not an appropriate way to deal with this.  A crop variant is.
