### ISSUE TITLE
Inverted Scroll Wheel tweak by NEI

### ISSUE THREAD

**Issue by imTheSupremeOne** [GTNewHorizons/GT-New-Horizons-Modpack#14888]
### Your GTNH Discord Username

imthesupremeone

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

NEI has a wheel scrolling tweak that moves items. Usually it moves items into a chest on scrolling up, and from chest upon scrolling down...

### The Reality

It seems that in GTNH with other hard-coded features to NEI this behavior was inverted... And it's some hard-coded NEI feature that never had a config to either reverse or disable by config option.

### Your Proposal

Please make a version or tell what needs to be changed to make it invert back...

P.S. this is NEI feature btw, it's not inventory tweaks, and not mouse tweaks. In older version it was known that you need to disable mouse tweaks wheel scroll to not overlap in a buggy way with NEI, and I see wheel feature is completely disabled in Mouse Tweaks, so inverting it there doesn't change anything...

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
"And it's some hard-coded NEI feature that never had a config to either reverse or disable by config option."
What do you mean? There is an option in NEI settings to invert it. Not sure about disabling though, but i would assume its there as well

**Comment by Caedis** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18713839/7f2028ea-df17-4ac3-9e04-5749a0009dfd)

**Comment by imTheSupremeOne** [comment]
> Config -> Inventory ![image](https://user-images.githubusercontent.com/18713839/283184541-7f2028ea-df17-4ac3-9e04-5749a0009dfd.png)

Damn, I
