### ISSUE TITLE
Reduce Power Consumption in LCR with Higher Tier Coils

### ISSUE THREAD

**Issue by ChaosFiller** [GTNewHorizons/GT-New-Horizons-Modpack#14887]
### Your GTNH Discord Username

chaos_filler

### Your Pack Version

2.4.0

### Your Proposal

For most multis, using higher tier coils provides a power discount incentivizing their use. In the LCR however, a Cupronickel coil is equivalent to an HSS-S coil since it is just a required block. It would be a nice bonus if using higher tier coils provided a discount, either x0.95 like the EBF or -5% up to -50%, similar to the Oil Cracker.

### Your Goal

When building multis, there are a lot of different ways to give yourself discounts, but when building LCRs, there's next to no thought about the recipe power, only where you are placing input / output hatches / busses. Additionally, since other multis already award discounts based on coil tier, it seems more fitting if the LCR followed that trend. 

### Your Vision

More consideration will be placed on wall-sharing LCRs to split coils and coils giving discounts on power will be a more established theme.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
LCR is already overpowered and does not need a buff. Also, wallsharing is not actually an intended mechanic afaik, so its unlikely that there would be a change to encourage it in this case.

**Comment by chochem** [comment]
Yea, we are not buffing the LCR. It has perfect OCs.

**Comment by bombcar** [comment]
> Yea, we are not buffing the LCR. It has perfect OCs.

what if it only had perfect OCs with the right coil 😈

**Comment by vovaksenov** [comment]
This is unironically a great idea, but everyone will hate it

**Comment by ChaosFiller** [comment]
> wallsharing is not actually an intended mechanic afaik

Ah damn, I didn't know what the consensus on wall-sharing was. I see it talked about a lot and it makes for interesting multiblock construction so I thought it was just a happy accident.

> what if it only had perfect OCs with the right coil
Evil, but also achieves part of my original intention with this idea (that being unifying the effects of higher tier coils), so I wouldn't exactly be opposed 😨

**Comment by vovaksenov** [comment]
Yes, i like wallsharing as well, but it will basically be removed once MuTEs come out. Their introduction is another reason that multis are unlikely to receive significant changes for the time. You can find more info in #multiblock-madness on gtnh discord.
