### ISSUE TITLE
Add ore vein list for easy finding

### ISSUE THREAD

**Issue by Gregor505** [GTNewHorizons/GT-New-Horizons-Modpack#14880]
### Your GTNH Discord Username

Poseidonftw99800

### Your Pack Version

2.4.0

### Your Proposal

Please add an interactive list of all discovered ore veins so you can find the ore veins easier like how the aura nodes has a list

### Your Goal

It would be easier to find a needed vein than searching your map for a specific vein

### Your Vision

It would improve the finding of veins on your map instead of searching for a while trying to find a specific vein

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
To expand, maybe it could be opened by shift clicking the show/hide deposits button in JM.

**Comment by Gregor505** [comment]
> To expand, maybe it could be opened by shift clicking the show/hide deposits button in JM.

That could work

**Comment by chochem** [comment]
you can highlight specific veins with the highlight function in the nei search bar. should probably resolve this right?

**Comment by bombcar** [comment]
> you can highlight specific veins with the highlight function in the nei search bar. should probably resolve this, right?

it can help, but if you have veins discovered over thousands of chunks, you have to pan around quite a bit.

And the highlight feature isn't readily discoverable

**Comment by chochem** [comment]
maybe it should go in the new VP quest

**Comment by Gregor505** [comment]
Nei feature helps but like bombcar said its really unpleasant searching thousands of chunks just for that one vein you know

**Comment by chochem** [comment]
not saying you are wrong, but that sounds pretty niche. usually people dont spread their prospecting thousands of chunks apart :P

**Comment by Gregor505** [comment]
> not saying you are wrong, but that sounds pretty niche. usually people dont spread their prospecting thousands of chunks apart :P

Just depends on what your looking for since some veins can be quite rare it took me forever just to find a mica vein

**Comment by chochem** [comment]
the highlight function is perfect for mica :)

**Comment by Gregor505** [comment]
Just saying it would be a nice little feature nothing big
