### ISSUE TITLE
Move NEI checkbox to upper left to not overlay counts

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#14898]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.4.2-200

### Your Proposal

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/533931/4b7a4251-d3d7-4120-be8c-4f100111658b)

The checkboxes overlay the number of items you need.

Moving them to the left, or better upper left, would allow the numbers to be seen at a glance.

### Your Goal

Make it so quick reference in NEI shows counts

### Your Vision

You wouldn't have to open the recipe to check counts.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Top left might cover the NC note

**Comment by Caedis** [comment]
Would 1 solution be to just shade the entire slot to red or green?
Not sure if it would useful for people who are colorblind
