### ISSUE TITLE
Adittional files failed to install ATlauncher and Multimc Bug??

### ISSUE THREAD

**Issue by carrotee123** [GTNewHorizons/GT-New-Horizons-Modpack#14899]
### Your Pack Version

2.4.0

### Your Server

SP 

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

i installed GT new horizons on ATlauncher and clicked launch but it gave me this error on both ATlauncher and Multimc
![failed](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/84941224/c29ae634-195a-412e-9db0-6d4574f3a093)
This has nothing to do with servers or single player since i cant even get in game

### Crash Report

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13394926/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
The download server changed to HTTPS - for multiMC download the zip directly from https://downloads.gtnewhorizons.com/Multi_mc_downloads/ (highly recommend the j17+ pack, see https://gtnh.miraheze.org/wiki/Installing_and_Migrating

**Comment by chochem** [comment]
dream says curse (which was used here) is fixed now.
