### ISSUE TITLE
Multiplication in NEI Search Bar

### ISSUE THREAD

**Issue by ChaosFiller** [GTNewHorizons/GT-New-Horizons-Modpack#14904]
### Your GTNH Discord Username

chaos_filler

### Your Pack Version

2.4.0

### Your Proposal
If you type an equation beginning with an = into the NEI search bar, it will perform the calculation.
Examples:
=7\*64\*10   = 10752
=0.95^4\*7680   = 6255.41

Similar idea to that of NEU, a mod for Hypixel's SkyBlock gamemode (https://github.com/Moulberry/NotEnoughUpdates). Screenshot below is taken from that mod.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95202140/b6e06672-f041-4362-963e-b7d91f98aa5a)

There is currently a chat calculator, however I believe an NEI search calculator to have an advantage in quick calculation since you can easily edit numbers.

### Your Goal

Often times I find myself alt-tabbing to Google, or opening my calculator on my phone to do some basic math, being able to do that by opening my inventory would be a nice quality of life feature.

### Your Vision

I cut down on the amount of times I alt-tab to different windows, keeping my immersion.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
I could have sworn there was a calculator built into chat or something

**Comment by ChaosFiller** [comment]
> I could have sworn there was a calculator built into chat or something

Oops let me revise this suggestion. I was unaware that there even was a chat calculator so I'm revising this suggestion to request a quest in "And So, It Begins" section of the quest book explaining its existence and its functions.

**Comment by bombcar** [comment]
Don't trust me on the chat calculator, I can't get it to work, so maybe it was an optional add-on.

**Comment by bombcar** [comment]
Ah, it is there, you need to put a space:

= 3+3
