### ISSUE TITLE
Anvil deletes items when opening Quest Book

### ISSUE THREAD

**Issue by anexoticllama** [GTNewHorizons/GT-New-Horizons-Modpack#14909]
### Your GTNH Discord Username

anexoticllama

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

When repairing an item in an anvil, I opened NEI to review recipes related to the item. When doing so, I clicked on a linked quest through NEI which opens the quest book. Upon closing the quest book, I would expect the items to remain in the anvil, or have been returned to my inventory as if closing the anvil interface normally.

### The Reality

Any items in the anvil are deleted

### Your Proposal

Proposal is to fix the item deletion issue and, preferably, ensure that functionality matches user expectation from vanilla anvil usage

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/BetterQuesting/pull/118
