### ISSUE TITLE
Add Right Proper GUI Scale for more fine grained GUI scale control

### ISSUE THREAD

**Issue by bertcardinaels** [GTNewHorizons/GT-New-Horizons-Modpack#14917]
### Your GTNH Discord Username

verknaller

### Your Pack Version

2.4.0

### Mod Name

Right Proper GUI Scale

### The Mod to Add

Features (Taken from https://modrinth.com/mod/rightproperguiscale)
- GUI Scale slider like it was always meant to be
- Configs to change the limits and step size of said slider
- An in-game command to change the GUI Scale in a more convenient way
- Full support for OptiFine and SmoothFont

### Your Reason

I recently upgraded to a 1440p monitor and to me the "normal" GUI scale is too small, the "large" GUI scale is too large. 
This mod allows me to pick something in the middle.

### Preliminary Investigation

Does work with the j8 version of the pack.
Does NOT work with the j17+ version of the pack so would need some adjusting so it works with both versions.
An issue I made with a bit of a crash log https://github.com/basdxz/RightProperGUIScale/issues/5
#mod-dev told me FalsePattern stuff might rule this one out but I'm hopeful.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by mitchej123** [comment]
Were not adding any mods that depend on falsepattern lib.  They are actively hostile to compatibility with NH and lwjgl3ify

**Comment by bertcardinaels** [comment]
I was able to find a setup that works for me, while not perfect, it does the job for me and is compatible with j17+
SmoothFont mod and the mod found in this [YouTube video](https://youtu.be/pPnjWv6VXoU).
I then put my GUI scale to normal in settings and used the mod's command `/guiscale 0.4`
Normal 
![javaw_2MNnsFALnx](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18063446/03b4a233-1ec1-440b-a6e0-55a83bf1f065)
Normal 0.4
![javaw_2N8vy2U1Pb](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18063446/c0820db9-59ce-4537-9d91-552bd21cd7df)
Large
![javaw_wTrUvTdg7m](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18063446/467ecffc-99d9-4cc3-ba90-3cd7375569f9)

**Comment by bombcar** [comment]
Smoothfont is ARR: https://www.curseforge.com/minecraft/mc-mods/smooth-font and GUIScale is presumably the same: https://www.mediafire.com/file/c669rr13901ck96/guiscale-1.7.10.jar so it's unlikely to be added or supported in the pack, but maybe someone will find it useful until Angelica removes the need.
