### ISSUE TITLE
New nether backport features

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#14919]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.3.4

### Mod Name

NetheritePlus+

### The Mod to Add

Backport some new nether features, like netherite ( generates in Mars) and some cool compats

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/05175f72-0173-4dc2-aa56-99778205d4e3)

### Your Reason

Have more exploration, more items to use, and have a renovated fresh air, also adds compats items for other mods, that can suit well into the pack

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/384d2d1f-fdf2-4efa-aaaa-75bc18833eca)

### Preliminary Investigation

Some recipes need to be gregfed and thaumcrafted, and some items could be added to other recipes, not a hard thing since there is not a lot of new items, also some generation features needs to be changed, but since there are configs for this, it cant be so much work, also its a recomeded mod by Netherlicious, so if @Minepolz320 gets the change of the license some day in there https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14574 the two mods could be combyned very well

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by chochem** [comment]
yea that one I found

**Comment by EnderProyects** [comment]
Wtf why it has a rep and is empty 😑

**Comment by vovaksenov** [comment]
The dev seems to have multiple mods which have in total like tens of millions of downloads. Id say he is probably active and likely to respond if contacted.

**Comment by EnderProyects** [comment]
If the project seems death, the dev don't answer and the code is not ARR, it's legal  to decompile the last jar and create a github rep with it?

**Comment by Dream-Master** [comment]
> If the project seems death, the dev don't answer and the code is not ARR, it's legal to decompile the last jar and create a github rep with it?

i would say yes if the License is open

**Comment by EnderProyects** [comment]
It's MIT

**Comment by Alastors** [comment]
We’re already playing in adding et futurium requiem, I don’t see the point

**Comment by EnderProyects** [comment]
I will close this since a dev has merged this mod code with EFR
