### ISSUE TITLE
Blast furnace glass is silly

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#14914]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.4.2-212

### Your Proposal

This recipe exists:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/533931/1262eb43-7127-49e8-a6c1-8a9d667f0072)

Clear glass to glass in the blast furnace.

### Your Goal

Chisel does the same thing for free instantly in stacks, so this is silly.

### Your Vision

Make it sand or something, even then it would be silly but less so.

Or just remove, what is it a noob trap?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
@bombcar this recipe was added before chisel recipe was added. Its silly but its not bad so let it in.
