### ISSUE TITLE
Removing a server from a default server list for not being nice

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#14927]
### Your GTNH Discord Username

Keyla3300

### Your Pack Version

2.4.0

### Your Proposal

I suggest removing a server "Craftersland GTNH" from the list of default servers. The server is actively selling crates, casino keys for lootboxes, ranks with stuff like creative mode, straight up selling unbans.
proof: http://craftersland.buycraft.net/category/GT-bundle

### Your Goal

The goal is to keep community clean and not associating with a bad and corrupted servers

### Your Vision

My vision is simple, the stuff that goes against main minecraft rules and even constitutions of some countries should not be welcome anywhere. And people who dont know better should not even have a chance to accidentally choose a server like this.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Savallator** [comment]
Why only remove them from the Server list though? I looked into it, and it is really bad... sicne this is against ToS, why not exclude them from future updates by making the game unplayable on this Server?

**Comment by bombcar** [comment]
> Why only remove them from the Server list though? I looked into it, and it is really bad... sicne this is against ToS, why not exclude them from future updates by making the game unplayable on this Server?

Any attempt at "devious defensive coding" like that is itself against ToS, and extremely dangerous from an unexpected side-effects point of view.

**Comment by CatsLeftEar** [comment]
2.5.1. server is still in the list, remove it pls

**Comment by boubou19** [comment]
> Why not exclude them from future updates by making the game unplayable on this Server?

That's one of the most stupid idea i read in a while... Have you ever heard of any drama related to this kind of stuff? There are tons of occurences of this in the modding scene history, even among the NH history.

**Comment by Savallator** [comment]
oh, you kind of misunderstood me there... i would not want to make the game unplayable as soon as the Server name equals "x"... But it would be a shame if some mods would behave just slightly different if these types of "crates" and "keys" are present... 
But anyways, since this is a clear violation of Minecraft ToS and it seems to be a UK-based company doing this, i just reported them to Microsoft, they have a report form specifically made for these cases.

**Comment by mitchej123** [comment]
> oh, you kind of misunderstood me there... i would not want to make the game unplayable as soon as the Server name equals "x"... But it would be a shame if some mods would behave just slightly different if these types of "crates" and "keys" are present... But anyways, since this is a clear violation of Minecraft ToS and it seems to be a UK-based company doing this, i just reported them to Microsoft, they have a report form specifically made for these cases.

Not happening.  Drop it.
