### ISSUE TITLE
A locked supertank can replace the fluid

### ISSUE THREAD

**Issue by WJBA1111** [GTNewHorizons/GT-New-Horizons-Modpack#14929]
### Your Pack Version

2.4.0

### Your Server

私人服务器

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

超级缸锁定流体后，即使为空，也要在背包显示储量0，而不是放置超级缸后才显示，这会导致我误以为这是一个空的超级缸，当我提取其他超级缸的流体时，之前的锁定的液体会被装满

### The Reality

超级缸在锁定状态下（比如锁定氡） ，被丢到另一个空的超级缸里面，超级缸在背包中不会显示氡的容量为0，然后直接在另一个装满氧气的超级缸的gui界面，用超级缸拿走，此时不显示氡的超级缸会显示氧气，但是放置超级缸后 又显示氡，此时就完成了用氧替换氡，这是一个漏洞
![111](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/110332908/e73cb00d-3f3e-47d8-aa56-cc0a901b2022)
![22222](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/110332908/82be9aa2-285a-4538-b9f3-0118f4e6fe21)
![33333](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/110332908/cec10485-7fd3-40e6-a8c9-30c85ba7113c)
![444](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/110332908/53b0e8da-4a4e-48ff-82ec-2ad7fe8df79d)
![5555](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/110332908/2ebaca0d-40be-4251-9f72-2ec44447d5c9)
![666](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/110332908/29b76a6b-bfca-475c-a89a-51d19cee6080)

### Your Proposal

修复这个问题

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2341
