### ISSUE TITLE
At least one circuit assembler recipe doesn't work on Nightly 233

### ISSUE THREAD

**Issue by TorvikW** [GTNewHorizons/GT-New-Horizons-Modpack#14935]
### Your GTNH Discord Username

Torvik

### Your Pack Version

Nightly 233

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

The recipe for HV circuit would work. I tried all kinds of trouble shooting methods (ensure clean room is running, break and replace, put in battery for power) and nothing worked.

### The Reality

The recipe refused to process. I downgraded my gregtech to gregtech-5.09.44.76 and when I reloaded the world the recipe started functioning as normal.

### Your Proposal

I'm not sure which gregtech update broke the recipe, and I also don't know how many other recipes aren't working. I chose gregtech-5.09.44.76 as the downgrade version simply because it's the last one I remember making these circuits with lol.
![Uploading 2023-11-24_14.40.15.png…]()

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TorvikW** [comment]
![2023-11-24_14 40 15](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11652949/329c28b5-27b6-45ab-b184-e00adc29eec1)

**Comment by miaowwwwww** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14892, there was a fix for cir ass. but i guess that does not fix it.

**Comment by Dream-Master** [comment]
@TorvikW is this the only recipe or others wont work ?

**Comment by TorvikW** [comment]
@Dream-Master I tested some more recipes for you.

- integrated processor: recipe works
- processor assembly: **broken**
- workstation: **broken**
- mainframe: recipe works
- microprocessor: recipe works
- nanoprocessor: **broken**
- nanoprocessor assembly: **broken**
- elite nanocomputer: **broken**
- nanoprocessor mainframe: **broken**

**Comment by Dream-Master** [comment]
that a lot of recipes

**Comment by TorvikW** [comment]
@Dream-Master And again just to confirm I double-checked, and yeah, when I downgrade gregtech to gregtech-5.09.44.76 then all those recipes work again.

**Comment by Dream-Master** [comment]
yes it was caused by some pr. miozune will look into it at Monday

**Comment by Dream-Master** [comment]
@TorvikW did 77 work or only 76 of GT ?

**Comment by TorvikW** [comment]
I just tested the recipes on 77 and they are all working fine.

**Comment by Dream-Master** [comment]
test 78

**Comment by TorvikW** [comment]
Okay this is weird now. On 78 only some of the recipes broken on nightly 233 are broken. The processor assembly recipe is broken but the workstation works fine.

**Comment by TorvikW** [comment]
I just realized that on builds where the processor assembly recipe is broken, it has two near-identical recipes. This may be the cause? 
![2023-11-25_14 14 44](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11652949/96c2556c-3b46-4c44-a94b-6d36532bdfab)
![2023-11-25_14 14 49](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11652949/acf058d0-807b-4990-b041-241ea48b0300)

**Comment by chochem** [comment]
the key difference being not the eu but that the second only takes the smd capacitor. this was removed automatically as a duplicate in the past but now isnt due to some changes in the recipe check code.

best to remove it properly though. I will do that.

**Comment by TorvikW** [comment]
So I've been testing a bunch of stuff while Discord PM'ing Dream so a lot of testing information is in there but I'll summarize what we found out here:

- gregtech 78 is when the processor assembly and mainframe break. The processor assembly has duplicate recipes but the mainframe doesn't. The integrated processor also has dozens of duplicate recipes.
- gregtech 86 is when the nano line breaks. The workstation breaks too but the mainframe recipe starts to work again. None of the nano line have duplicate recipes so this probably isn't a recipe dupe problem.
- I always verified that the cleanroom was functional and all these problems go away when I switch to gregtech 77

**Comment by Dream-Master** [comment]
> the key difference being not the eu but that the second only takes the smd capacitor. this was removed automatically as a duplicate in the past but now isnt due to some changes in the recipe check code.
> 
> best to remove it properly though. I will do that.

There is more broken than a recipe. it seems the modification of GT_Recipe.java cause it

**Comment by TorvikW** [comment]
The broken recipes are fixed when I use the fix posted above by @HoleFish.

**Comment by HoleFish** [comment]
If my theory works, mainframe should be broken and nanoprocessor should not. More mistakes are here maybe

**Comment by TorvikW** [comment]
The mainframe recipe is working fine for me with your fix

**Comment by HoleFish** [comment]
> * integrated processor: recipe works
> * processor assembly: **broken**
> * workstation: **broken**
> * mainframe: recipe works
> * microprocessor: recipe works
> * nanoprocessor: **broken**
> * nanoprocessor assembly: **broken**
> * elite nanocomputer: **broken**
> * nanoprocessor mainframe: **broken**

i mean this

**Comment by TorvikW** [comment]
@HoleFish With the gregtech fix you made today, all those recipes are working normally for me. All of those recipes that I found broken are fixed, and the recipes that I tested and were working fine are still working fine.
