### ISSUE TITLE
Ferrite Mixture Dust missing Circuit in recipe

### ISSUE THREAD

**Issue by Ralsch** [GTNewHorizons/GT-New-Horizons-Modpack#14932]
### Your GTNH Discord Username

Osul

### Your Pack Version

2.4.0

### Your Server

Community Server

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

Trying to mix Ferrite Mixture Dust in MV Mixer.

### The Reality

I always got Invar Dust instead.

### Your Proposal

By trial and error I figured that the Mixer recipe is missing the information about the Programmed Circuit to use, which would be 2. This should be fixed. ^^

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
![no circuit](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/4586901/c4ba5154-c127-433f-8350-a630dea17230)
![with circuit](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/4586901/ff4d221d-1b6f-4244-862f-dca9995e249f)

it works without or without a configuration circuit 🤷‍♂️ not sure what's so wrong with your setup

**Comment by Ralsch** [comment]
That's weird. I testet your setups and they worked just fine. So I tried to recreate my setup to reproduce my outcome.
And I figured it out.
The recipe doesn't specify a Circuit, so I didn't bother to change the current one, which was the 1. So I put in the dusts, but the Iron first, then the Zinc and the Nickel last. Invar uses the 1, so the mixer did exactly that.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8625703/b0087249-eec5-4a5a-a7af-efe18174505d)
After that, putting in the Dusts in any order will always produce Invar, until I change the circuit to something else.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8625703/c03763f2-dbcb-461e-bc5b-2e77c5e656b9)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8625703/71d062bd-29f4-48d0-ab7d-d250e2df97c4)
So the bug is not the missing Circuit information in the recipe, but the conflict with Ivar in the mixer under my presented circumstances.
So, to reproduce:
1. Mixer with Circuit 1
2. Insert Iron Dust
3. Insert other Dusts
4. Get Invar
5. Insert Dusts in any order
6. Get Invar.
7. Change Circuit to soemthing else
8. Insert Dusts
9. Get Ferrite Mixture Dust

**Comment by Glease** [comment]
Guess we should add a circuit to this recipe
