### ISSUE TITLE
Circuit boards cannot be renamed

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/GT-New-Horizons-Modpack#14930]
### Your GTNH Discord Username

Admin_XiaoMai

### Your Pack Version

nightly-231

### Your Server

private server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/46d1be25-7aa6-4e33-9a8d-2f43045e5b5a)

### The Reality

Circuit boards cannot be renamed

### Your Proposal

fix bug

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AdminXiaoMai** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/4fd61754-3cf4-49ef-9601-737ab03dfe38)

**Comment by GTNH-Afx237v7** [comment]
Was the board that you were trying to rename already renamed? This may happen when you have „substitutions enabled“ on a pattern and AE inserts the already renamed item again - which can cause problems.

**Comment by GTNH-Afx237v7** [comment]
What circuit board exactly, as there are several? Or do you mean all circuit boards?

**Comment by AdminXiaoMai** [comment]
> What circuit board exactly, as there are several? Or do you mean all circuit boards?

all circuit boards
