### ISSUE TITLE
CAL Multi-Amp Support

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#14939]
### Your Pack Version

2.4.1

### Your Proposal

Add the possibility to use multi-amp hatches for CALs
Maybe only up to 64a or higher (depends on discussion) and if it's too overpowered then make it only a 2/4 oc instead of 4/4 after UXV is reached

### Your Goal

Getting multi-amp support for CALs

### Your Vision

It would make spamming CALs more usable + better for performance cause it's less CALs for endgame, you wanna have multiple anyways especially if you cap it at 64a UXV hatches

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by MaGeBZz** [comment]
Or if not balanced enough laser ocs after UXV

**Comment by chochem** [comment]
that would obviously be very unbalanced. We shouldnt change a LuV mechanic because of UXV problems.

**Comment by vovaksenov** [comment]
Yea, even if something like this gets added, it must be gated to late/endgame somehow to not destroy the CAL balance of mid/lategame.

**Comment by joshuan123** [comment]
Allowing only multi-amp lasers could work? Gated by Shirabon which is eternal DTPF, and that’s around when CAL spam gets bad

**Comment by MaGeBZz** [comment]
I wouldn't call it unbalanced, like I said could maybe get something like every multi-amp hatch can get laser ocs adn then you could use things like UXV 4k laser on them but they would be pretty shit in terms of energy/speed ratio
So you would have to think about if you wanna spam more and be more energy efficient or if you wanna get some inefficient ones with a shitty energy ratio

**Comment by lordIcocain** [comment]
mb add support only for wireless multi amp
