### ISSUE TITLE
Livingrock plate Recipe

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#14946]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.4.0

### Your Proposal

Lingrock plates currently require an lv cutting machine to make, unlike most other stone dust plate recipes such as stone, black granite, red granite, marble, and even some non-stone such as quartz, quartzite, and certus. 

Because Livingrock plates require a cutting machine, that means that botania is completely gated behind lv, but that seems unintended as the rest of early botania can be made with only hand tools.

### Your Goal

Ungate Botania

### Your Vision

with early botania possible, several people may choose to do it for the benefit of earlier good tools.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
Why not make a harder alternative recipe for the dilued mana pool that doesnt need livingrock plates?

**Comment by LazyFleshWasTaken** [comment]
Consistency. THe other rock plates can be compressed from dust.

**Comment by chochem** [comment]
botania being LV is intended. mostly from what combusterf told me the intended gate was TF, but certainly LV.

**Comment by LazyFlesh** [comment]
Can this be reconsidered? Botania has the most use as early as possible, so being able to get into it in stone/steam would be really cool. This only really ungates mana generation and pool use, and at most the botania enchanter, though that needs arcane crafting.

Not even the sojourner's belt can be crafted, which is the mobility item from botania, since that needs runes, which need infusion.

**Comment by EnderProyects** [comment]
I'm okay in reopening or changing this, but I suppose another dev should also agree

**Comment by sisyphussy** [comment]
If it doesn't have any sort of impact on early-game progression, i don't think it'd be harmful. But at the same time, most of the recipes are gated behind thaumonomicon/other LV+ stuff, so i don't think you get much out of progressing botania, though i could be mistaken

**Comment by LazyFlesh** [comment]
> If it doesn't have any sort of impact on early-game progression, i don't think it'd be harmful. But at the same time, most of the recipes are gated behind thaumonomicon/other LV+ stuff, so i don't think you get much out of progressing botania, though i could be mistaken

mostly just manasteel for armour and tools, yeah. But it gives something more to do in steam, and the more you have done now, the less you have to do later when tc infusion unlocks for more botania progress. Also, stone age thaum is a thing, has been for a long time, now legitimised with entries in the QB, so you can get quite a bit done, if nothing that relies on infusion, runes, or technology-gated materials.

Some examples are the hourglass, some lenses, which does not include magnetising for the ring, though that just needs lv polariser, the seed things for different soils, biscuits of totality, though those cost a _lot_ of mana, and some cosmetics,.

~~removing botania manasteel tools from the blacklist could be nice too, esp considering thaumium ones aren't blacklisted.~~ did this and its merged

**Comment by LazyFlesh** [comment]
Now that feature freeze is over, can we continue discussion on this?
