### ISSUE TITLE
Crash when I hold a golem

### ISSUE THREAD

**Issue by jose9222** [GTNewHorizons/GT-New-Horizons-Modpack#14940]
### Your GTNH Discord Username

jose_oton

### Your Pack Version

2.4

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

"Whenever I hold a golem in my hand, the game crashes. When I reconnect to the world, if I don't touch anything, 50% of the time I experience an instant crash the other 50% I join the world holding the next hotbar slot, so I avoid a crash. If I spam 1 or another hotbar slot where I don't have a golem, I load holding that item (without any error 20% of the time, 60% the item or the right click is useless and it makes a little sound if u right click until you swap to another hotbar slot, and 20% when you right-click, you place the golem). I can't place it in the altar for an infusion with this bug. I have used golems before in version 2.3 without errors. My team and I updated the pack when the stable version was released, and we noticed this issue as we rebuilt the thaum system to use the Thaumic Energistics stuff.

I can't get my two teammates to try it because they have potato PCs, and they experience so much lag while the world is loading that crashes scare them."

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/131607623/36d18f25-0dcb-4e4a-abe0-8eb2b5a51bd4

### Crash Report

[crash-2023-11-25_23.40.13-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13465407/crash-2023-11-25_23.40.13-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by jose9222** [comment]
> 60% the item or the right click is useless and it makes a little sound if u right click until you swap to another hotbar slot

This is what u can see in the video as I just reconected from a crash

**Comment by jose9222** [comment]
This bug also happen to my teammates but we used a droper to insert it to the altar so I think any quest is obtainable with this bug

**Comment by Caedis** [comment]
Can you make a copy of the server and test it with 2.4.1?
http://downloads.gtnewhorizons.com/ServerPacks/betas/

**Comment by jose9222** [comment]
The admin of my server its a friend but he has exams rn so he probably wont enter into all that server stuff at the moment, anyway it doesnt happen in sp so maybe its a bug in the server config that randomly spawned?
