### ISSUE TITLE
draconic Chaos fragment recipe

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#14945]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.4.1

### Your Proposal

So now we have Chaotic fusion casings for the DEFC but no recipe needed for it, why no adding a new recipe for crafting the chaos fragment and needing this casings ( that need chaos fragment)... so I propose this:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/6bce75e9-a4c3-4c2b-a816-8171871cb7b2)
- 2 dragon eggs
- 32 chaotic propolis
- 1 transference gem
- 2 fluxed shards
- 1 vapor of levity bucket
- 1 or more dragonstones
- 1 chaos cookie
- 1 awakened core
-  some spacetime fluid

### Your Goal

Add a recipe so the end recipes dont require to visit many islands of the chaos dragon

### Your Vision

Adding a recipe that touch othger parts of the pack 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
Why not kill the Dragon ?

**Comment by EnderProyects** [comment]
For this you need to kill the dragon a pair ofd times, since the casings needs chaos fragment, this is only if you want to craft some of the endgame stuff in quantities, ( also is good for servers)

**Comment by chochem** [comment]
I definetely like the placement in a chaotic tier DEFC. That makes a lot of sense. I think this or something close to it would be a good addition.

**Comment by EnderProyects** [comment]
Since now I have more free time I can work on this, my plan is to add two recipes, one with awakened cores, that lest you craft the smallest fragments and is very costly, so people that are doing a challenge mode can get shards but that is better to kill the guardian for the rest of the players, and the a second recipe with chaotic coils, that let you craft the big shard, and that is costly but not as much as the other

**Comment by EnderProyects** [comment]
I accept suggestions for the recipe, but I would like to add the ones above at least distributed in both recipes

**Comment by LazyFleshWasTaken** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40587985/d73bddce-bf7e-47ff-9b47-2bb3e00b8b75)

What do you think of this?
Left to Right, we have:
1. Chaotic Propolis
2. 420k Spacetime
3. 32 Null Catalyst
4. 16 Elements of Darkness
5. 4 Dark Matter Foci
6. 32 Quantum Eyes
7. 32 Exquisite Probably Crystals
8. 4 Entropy Crystal Clusters 
9. 4 Perditio Imbued Fires
10. 1 Infinity Egg
11. 4 Dragon Hearts
12. 32 Dragon Essence
13. 32 Dragon Blood INgots
14. 16 Shards of Creation
15. 16 Ender Shards 
16. 4 Dragon Stone Blocks


As a Gog player, all of these materials are obtainable, if tedious, such as the eldritch eyes. We have to farm Eldritch Guardians from warp events for them, and we can't make spawners to do it automatically.

**Comment by EnderProyects** [comment]
I like it, but there is a problem, the DEFC only accept 9 stacks

**Comment by kyoi-the-fox** [comment]
i would suggest dropping the following first if needed

-   Chaotic Propolis
-   32 Null Catalyst
-    4 Entropy Crystal Clusters
-    4 Perditio Imbued Fires
-    16 Ender Shards
-    4 Dragon Stone Blocks
-    32 Dragon Essence
 as they are trivial to get anyway

leaving

- Liquid    420k Spacetime

1.    16 Elements of Darkness
2.    4 Dark Matter Foci
3.   32 Quantum Eyes
4.    32 Exquisite Probably Crystals
5.    1 Infinity Egg
6.    4 Dragon Hearts
7.    32 Dragon Blood Ingots
8.    16 Shards of Creation
9.    one more free for any of the trivial ones

**Comment by LazyFleshWasTaken** [comment]
Could do a time focus in the free space.

**Comment by EnderProyects** [comment]
Since I dont want to add focus, because is adding tedious because the sake of it, I have redone the recipes but maintaing them hard p.d the first items of each recipesare not consumed ( are like catalyst)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/f3472fff-3d72-468b-a8c6-5b1d185fccf0)
( now I just need to fix my kubatech repo because is not working xd)

**Comment by LazyFleshWasTaken** [comment]
Just a quick question, what exactly are the items in the harder recipe?

**Comment by EnderProyects** [comment]
4 Inf dragon eggs ( not consumed)
1 Element of darkness
8 blocks of dragonblood ( it could be changed to a superconductor block)
8 Enhanced filling agent
1 laputa shard ( first tier, but could be made tedious just placing other tier)
32 chaotic propolis
32 exquisite probable crystals
32 dragonfruits
8 resureccion stones
640k Spacetime

**Comment by EnderProyects** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/c7b83769-4d73-45c2-aae9-4e4330e5c32f)

**Comment by LazyFleshWasTaken** [comment]
You changed out the probably crystals for 4 zpm solars? Also, whats the output fluid?

**Comment by EnderProyects** [comment]
Well yes, the code gas a problem and when I place the probability crystals in the recipe Minecraft crash, I forgot to say that the solars are a temporal item, and I want to place something else than the crystals or solar, also the fluids are like a waste of the chaos produced in the recipe ( and both draconium) I could substitute the one that use the bucket with some iron like the recipe doesn't consume the bucket and only the fluid

**Comment by EnderProyects** [comment]
Also should I change the voltage?

**Comment by EnderProyects** [comment]
@chochem its this fine?

**Comment by Dream-Master** [comment]
Put random stuff together make no good recipes

**Comment by EnderProyects** [comment]
Well they are not random, all of them are chaos or dragon themed ones, also the idea is that players prefer to kill the chaos guardian than doing this recipe, so the players that do special runs and cant finish de game because they can get chaos shards can ( and also that the players that invest into the chaos coils can get more chotic shards with easy items at endgame)

**Comment by EnderProyects** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/b64725a6-de25-4454-b957-bccda941ed42)
I changed the fluxed shards to strange crystals, and added the 2 originar Exquisite ( in the code was failling because an oredict issue)

**Comment by LazyFleshWasTaken** [comment]
What are the output fluids?

**Comment by EnderProyects** [comment]
Molten iron for the not consumed bucket and molten glass for the not consumed phials ( idk it appears to me like the recipe should have some ressidue to deal with)

**Comment by EnderProyects** [comment]
Also since I asked but I have no answer back, should I change the voltage tier?
