### ISSUE TITLE
Cinderpearl crop needs non-existent block to mature

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#14941]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Cinderpearl base block, block of blaze, can be crafted in some way.

### The Reality

It can not.

### Your Proposal

Change to a different base, like blaze lamp from botania.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I am pretty sure it used to be craftable. so just fixing that should be the goal I suppose.

**Comment by Dream-Master** [comment]
It has a custom recipe maybe it wasn’t transferred during to script to code process .

**Comment by chochem** [comment]
hmm dont see anything custom
Looking into the game I think it is the botania addition that broke things as the 'blaze lamp' is oredicted and replaces the block in the autogenerated recipes. That recipe just gave the (GT) blaze block before.

**Comment by lordIcocain** [comment]
But blaze lamp from botania works too

**Comment by lordIcocain** [comment]
<img width="1123" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/ea126bde-ba1a-4899-a441-3ef4905eff48">
<img width="1045" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/f83dcbea-ea8a-42b3-b1bd-087d157c3ed3">

**Comment by chochem** [comment]
well adding it chisel makes sense anyway. all the other blocks which are added by multiple mods are there.
