### ISSUE TITLE
1.x-Dimethylbenzen electrolysis

### ISSUE THREAD

**Issue by Darkenlord1** [GTNewHorizons/GT-New-Horizons-Modpack#14943]
### Your GTNH Discord Username

ljedamos

### Your Pack Version

2.4.0

### Your Proposal

Allow 1.x-dimethylbenzen to be inserted in fluid slot in electrolyzer, as well as hydrogen output to fluid slot. 
Because there is only recipe with cells which is quite not handy.

### Your Goal

Make electrolysis of 1.x-dimethylbenzen more convenient and simpler.

### Your Vision

Less unnecessary automation and manipulation of empty cells.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14843
