### ISSUE TITLE
Add a focus ring to quests when you select them in the Quest Book Search menu

### ISSUE THREAD

**Issue by BiffBish** [GTNewHorizons/GT-New-Horizons-Modpack#14951]
### Your GTNH Discord Username

biffbish

### Your Pack Version

2.4.0

### Your Proposal

When using the search feature in the quest book add a vignette or some animated circle to surround the selected quest 

### Your Goal

When using the quest book and searching for a quest when you find a quest in the search list and click it it takes you to the tab its in and colors the quest yellow or whatever depending on the theme. I find that if the quest is small or there is a lot of quests on screen there is so much visual noise that it makes finding the yellow highlighted quest near impossible. I understand you can click the quest icon to open the quest directly but it would be nice to also know where it is in relation to everything else
<img width="1356" alt="javaw_S7vHZtnP4o" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/42410516/efd8444e-4b3d-4d1d-8c95-81c1b3cacb46">

### Your Vision

There should be some form of vignette or animated circle that zooms in on the quest to help you identify the quest quicker

I have a program that helps find the mouse, So using that heres an idea of what it would look like

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/42410516/43dc4a94-0fba-4865-bbb0-3e4179989482

![ApplicationFrameHost_vOrwRAlaA1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/42410516/29a87be1-801a-426e-93c1-697117af87bd)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
This would also be useful when you have a “quest done” notification - I can never find the blue icon among all the other pulsating and excited icons. Even spacebar or shift to hide all but searched/has reward for pickup could be useful.

**Comment by Caedis** [comment]
Or a screen to show only quests with rewards available/non-repeatable

**Comment by BiffBish** [comment]
Yea adding a vignette might be tough but some sort of better flashing indicator for the searched one might make it identifable quicker. Perhaps flash gold and grey once every second or half second. That would be quicker to implement id think
