### ISSUE TITLE
OpenComputers config file resets after chaging

### ISSUE THREAD

**Issue by Cyl18** [GTNewHorizons/GT-New-Horizons-Modpack#14958]
### Your GTNH Discord Username

cyl18

### Your Pack Version

2.4.1

### Your Server

private

### Java Version

Java 17

### Type of Server

Open To LAN

### Your Expectation

changed `internet -> filteringRules`, and it resets to default

OpenComputers-1.9.17-GTNH
GTNH 2.4.1

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/14993992/e0e6f33f-bd9d-4c80-8fed-0a6ac1ea4949)

### Your Proposal

fix this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
does it happen on a pure SP world or on a real MP server?

**Comment by Cyl18** [comment]
happen in sp too

**Comment by tbscope** [comment]
You can manually prevent the reset by changing the line `version="%VERSION%"` to `version="1.9.14-GTNH"` in the OpenComputers.cfg file.

It looks like the correct version number isn't being added to the config file after a reset.
