### ISSUE TITLE
Fluid pipes not accepting water from Water Tank

### ISSUE THREAD

**Issue by KYDuck123** [GTNewHorizons/GT-New-Horizons-Modpack#14967]
### Your GTNH Discord Username

kyduck

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

The Water Tank (early game infinite water multiblock) should output into a large wooden fluid pipe, as it does normally.

### The Reality

I noticed that my Railcraft boiler was low on water. Upon checking why, I found that my water pipes were empty, and not taking water from my water tanks. I broke and replaced the water tank, which did not fix the problem. I was playing on nightly when i noticed, so I tested an older save in the stable 2.4 branch, and found the same issue. This problem started occuring after a certain point (I don't know when though) as it previously worked in 2.4. The problem also occurs with other types of fluid pipes, though other machines are working with liquids, so it is an issue with the tank specifically.

### Your Proposal

Figure out why this happens

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
They are connected to the bottom layer? Can you show a picture? Preferably while holding a wrench and looking at the pipe.

**Comment by BritishCynic** [comment]
I'm using the latest nightly, and I cannot reproduce this issue. Water will flow into wooden pipes no matter where I position them on the water tank, plus I have bronze pipes working just fine.

**Comment by BritishCynic** [comment]
Considering that water coming out of the top would defy gravity in the absence of a pump, I think leaving that behaviour as-is is fine.

**Comment by bombcar** [comment]
Railcraft water tanks have always only discharged from the bottom layers of blocks. Perhaps multiple tanks were chained together in such a way as to imitate flow from the top layer.
