### ISSUE TITLE
Something causing null pointer exception and stacktrace taking 5% of cpu time

### ISSUE THREAD

**Issue by joshuan123** [GTNewHorizons/GT-New-Horizons-Modpack#14965]
### Your GTNH Discord Username

joshuan123

### Your Pack Version

Nightly 2.4.2 #218, gtnhintergalactic-1.2.3-master.1+2a4fc1028a

### Your Server

Private server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Expected stacktrace to not take significant tick time, and log not to be full of null pointer exceptions

### The Reality

Both of those things happened. Spark profile and log (abbreviated to ~last 5,000 messages) attached:

[shorterlog.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13504527/shorterlog.txt)

https://spark.lucko.me/U2TncHc1eC

### Your Proposal

Example comment

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Wow, it's happening so much that there's no hint as to what it might be.

Can you look in the full log for anything that is NOT that NullPointerException?

**Comment by Glease** [comment]
check GregTech.log. It should have slightly more info.
