### ISSUE TITLE
TF knightmetal block is uncrafteable

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#14962]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Expectation

That the normal TF block has a recipe or at least that can be crafted using chiessel

### The Reality

You can´t get this block or craft the block and chain weapon

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/39ce2b72-37d5-4146-b94a-e1f28d57e25d)

### Your Proposal

Add some recipe or add the two ( TF one and GT variant) to the chiessel 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
This recipe looks much vanilla. it need to have rings and screws maybe

**Comment by EnderProyects** [comment]
idk the recipe is already in the pack, but since you can´t craft the block you cant make this recipe
