### ISSUE TITLE
AE2FC Fluid Pattern Terminal Dupe any item

### ISSUE THREAD

**Issue by Wo0kiee** [GTNewHorizons/GT-New-Horizons-Modpack#14961]
### Your GTNH Discord Username

wo0kieee

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

ALT+RMB should do nothing or clear ghost items

### The Reality

You can extract any "ghost" item from "ME Fluid Pattern Terminal"

1. Open Fluid/Fluid Processing Pattern Terminal
2. Place any item from NEI or Inventory into pattern
3. ALT+RMB click any item
![bug2](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/33743476/fc7a14f6-366b-467e-a485-3ae9734cf159)

### Your Proposal

Fix it ;)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/393
