### ISSUE TITLE
Tinkers Construct Versions of GT Tools 

### ISSUE THREAD

**Issue by Devoid-Of-Spelling** [GTNewHorizons/GT-New-Horizons-Modpack#14968]
### Your GTNH Discord Username

jovian.devoid

### Your Pack Version

2.4.0

### Your Proposal

I would like Tinkers Construct Versions of GT Tools that follow tinker's rules instead of GT's tool rules

### Your Goal

i want GTNH versions of tinkers tools to save my sanity a little bit even if it is just a wrench

### Your Vision

auto repairing wrench or maybe Pocket Multitool if you want to go all the way

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
There really is no reason for this. Make an electric wrench. Make a vajra. Craft a tool belt if you are annoyed about too many slots taken up by tools. The problem of tools breaking is already simplified a lot in the pack and there are no reason for further buffs here i think.

**Comment by bombcar** [comment]
If you’re choosy with quest rewards you can build basically one wrench until you can build an electric one. 

It would be amusing to have tinkers wrenches but I don’t know it would provide a tremendous amount to the game. Tools are designed to be used up and encourage us to move to automating in machines.

**Comment by Devoid-Of-Spelling** [comment]
Yeah that is very fair, i wish i could be bothered to learn to code to make it myself, cheers for the reply though
