### ISSUE TITLE
Ring of Nutrition from forbidden magic Increase Nutrition

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#14966]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.4.0

### Your Proposal

Currently, I searched the github for what interacts with the Nutrition mod, and it seems to be normal foods, Healing Axe, Tin Cans, and the talisman of Nutrition. I want to add the ring of nutrition to that list, as it would fit thematically, and is otherwise unused due to the recipe requiring a whole block of nether stars. I also propose it fill the nutrition to 80%, or whatever the first level where you get positive effects is as you still have to eat 6 different foods, and can't just stop eating entirely. Should also fill all nutrition groups regardless of what you actually eat.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40587985/f817f2b3-07d1-40c0-9b49-9b0573dbfba1)

### Your Goal

I want to add this accessory to the list of things that interact with the mod because it would fit thematically, and otherwise has no use.

### Your Vision

People make use of the positive effects it will bring, and make an otherwise unused accessory. It also adds an alternative to tin cans in lv-ish, since you need a lathe and thaum shards to make it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
shouldnt it maybe boost the nutrition you get? instead of just randomly setting stuff to 80%.

**Comment by LazyFleshWasTaken** [comment]
Per the thaum entry and the thoughts of the creator of it, you should be able to get all food groups even though you're eating just cookies. The entry was made with vanilla food in mind, not mods like spice of life or nutrition. 

And yes, not randomly setting it to 80%, but gradually increasing it to 80%, where it will stop unless you're actually eating that food group.

So say you'rea eating 6 different jelly sandwiches, you'll get everything rising until 80% then when you reach it, you will only keep getting grain and fruit above 80%, and up to 100 if you keep eating it.

**Comment by LazyFlesh** [comment]
Can this be reconsidered? One can already use this with Terra wart, a nutrition-excluded food item, to keep nutrition high without having to eat 10 times to refill your hunger from half. 

Though, admittedly, I was a bit uhhh... dense? no, not that, inconsiderate? not that either. Whatever, you get it. Greedy, maybe.

Anyway, boosting to 80% is definitely a bit much, so keeping it at 50% unless actively consuming the food group would be great anyway, as that makes it superior to the other options, which keep it at 50% regardless of what you do, with no way to increase it beyond that, but requires you to keep eating stuff to keep said nutrition, not starve, and go beyond 50%.

**Comment by LazyFlesh** [comment]
Now that feature freeze is over, can we continue discussion on this?
