### ISSUE TITLE
Fiery steel ingot doesnt have a texture

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#14963]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Expectation

That the fiery steel ingot and the double fiery stell ingot has a texture

### The Reality

they doesnt have any texture 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/2a3cf9a6-6138-4a52-ba2a-48ff58fc418a)

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by EnderProyects** [comment]
@chochem now that you are fixing stuff, could you also check this one's?

**Comment by chochem** [comment]
I dont make textures

**Comment by EnderProyects** [comment]
The textures should be there somewhere ( since time ago this items have textures)

**Comment by EnderProyects** [comment]
This was already fixed so closing
