### ISSUE TITLE
Rubber and blaze electron tubes retain vanilla recipes

### ISSUE THREAD

**Issue by vovaksenov** [GTNewHorizons/GT-New-Horizons-Modpack#14976]
### Your GTNH Discord Username

vovassgreat

### Your Pack Version

nightly 183

### Your Server

unrelated

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

All forestry electron tubes have gregified recipes in thermionic fabricator.
![image-30](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86674724/6c4bbf73-b2d9-4666-a874-ee7a31022c50)

### The Reality

Rubberized and blazing e.t. retain vanilla recipes in addition to the gregified ones.
![image-38](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86674724/6be94999-645f-45c7-a6d0-58a19918cf86)
![image-36](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86674724/d4688f98-42e6-47a2-ac1c-0c1fd4c172f2)

### Your Proposal

Remove the vanilla recipes (while making sure the gregified ones remain).
This issue was made on behalf of EvgenWarGold.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
i try to remove the remove code in core mod and now all recipes are back FR one and gt one. only Blaze, Obsidian and Rubber 4 four different recipes.
