### ISSUE TITLE
Steam Grinder does not want to fill the Output Bus

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#14973]
### Your GTNH Discord Username

britishcynic

### Your Pack Version

GTNH-2023-11-29+239

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

When I place two stacks of Magnetite Ore into the Input Bus (Steam), this should be processed without issue into four stacks of Crushed Magnetite Ore into the Output Bus (Steam)

### The Reality

The multiblock only processes one stack of magnetite ore, for two stacks of Crushed Magnetite Ore, and refuses to process more unless I remove one of the stacks of Crushed Magnetite Ore, and even then, it will only fill a maximum of two cells out of four in the Output Bus.

### Your Proposal

Fix the Grinder so that it will fill up the Output Bus correctly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Mobius0526** [comment]
The same goes for small machines. When the first grid is full, it will stop
For example, centrifuges and electrolyzers
It seems to be because the product can only be output to specific cells according to the formula

**Comment by Dream-Master** [comment]
did that have todo with void mode/non void mode maybe? or some other mode is active ?
