### ISSUE TITLE
The game crashes shortly after the world is loaded on Nightly 240

### ISSUE THREAD

**Issue by TorvikW** [GTNewHorizons/GT-New-Horizons-Modpack#14975]
### Your GTNH Discord Username

Torvik

### Your Pack Version

Nightly 240

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I'm not exactly sure what triggers the crash. The first time it was maybe 30 seconds after I loaded into the world, while I was searching something in NEI. The second time was also maybe 30 seconds after I loaded in, moved around, and started browsing NEI. After that crash, the game started crashing as soon as I joined the world each time I tried to enter. I have downgraded CodeChickenLib to 1.1.8 and now everything seems to be working fine so the update to the mod may be causing the crash.

### Crash Report

[crash-2023-11-30_12.26.06-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13516026/crash-2023-11-30_12.26.06-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by TorvikW** [comment]
If I'm understanding the crash report correctly, this is the block at (433,66,353) that is causing the crash.
![2023-11-30_12 45 51](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/11652949/a5eda4f0-f705-46c4-88d2-f9130cf5a647)

**Comment by bombcar** [comment]
Only change really is https://github.com/GTNewHorizons/CodeChickenLib/commit/d6e2b946b14d0fe19f376e5ca4baa817745a415e

@miozune is possible it’s crashing?
