### ISSUE TITLE
Controler and vr support

### ISSUE THREAD

**Issue by samiscool51** [GTNewHorizons/GT-New-Horizons-Modpack#14980]
### Your GTNH Discord Username

carsonslefthand

### Your Pack Version

2.4.0

### Your Proposal

adding controler and vr support to gtnh

### Your Goal

Allows for better immersion and more options for user input and intractability.

### Your Vision

to allow for immerse and portable gregifcation.

but i all seriousness playing with a controler would allow more relaxed gameplay options and vr would allow for more imersive options.

there is a joystick mod that already exists and does partly load up on gtnh https://github.com/ljsimin/MinecraftJoypadSplitscreenMod but it doesn't currently work and would require some work to get it running.
for vr vivecraft is an option http://www.vivecraft.org/ but it has integrated optifine and may interfere with the gtnh optifine

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Hikari1nVoid** [comment]
sancheck

**Comment by vovaksenov** [comment]
Im not sure if the controller part is feasible considering how many keybinds are needed for a smooth gtnh experience. VR feels like a stretch too because of controls..
