### ISSUE TITLE
Holding Alt disables the input of other buttons

### ISSUE THREAD

**Issue by AiramProvoker** [GTNewHorizons/GT-New-Horizons-Modpack#14982]
### Your GTNH Discord Username

sivol45

### Your Pack Version

2.4.0.0

### Your Server

Anywhere

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Being able to press other buttons while holding LAlt. 

### The Reality

Holding LAlt prevents the input of other keyboard button presses.

### Your Proposal

Allow other button inputs when holding Alt.
I have Sprint bound to LAlt and it can be very jarring and unresponsive to use it. Alt is not bound to any other command and does not conflict with them in the keybind settings.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
for this kind of issue we need to also know your OS and have you checked if its an issue in 2.5.1

**Comment by bombcar** [comment]
This likely (certainly) an issue with lwjgl3ify (similar but not the same as https://github.com/GTNewHorizons/lwjgl3ify/issues/91 probably) - so we will need your OS, specific Java version (output of `java --version`) and the _exact_ keyboard layout you are using (e.g, French AZERTY, etc).

**Comment by eigenraven** [comment]
There have been a lot of keyboard fixes in lwjgl3ify 2.0 alphas, so this should be resolved by now.
