### ISSUE TITLE
Breaking a Railcraft iron tank gives you parts with different NBT somehow

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#14994]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.4.2-pre-whatever

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Iron tank parts would stack even if they're brand new or broken in-world

### The Reality

If I place any part of an iron tank from a stack of parts (say an iron tank wall), if I break it with the pickax, it gives me something that won't stack with the original parts.

All broken ones stack with themselves, and if I NBT wipe it with the little single block, they stack with the originals again.

### Your Proposal

Not give a different NBT on breakage.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BritishCynic** [comment]
This is due to how Railcraft inserts NBT data for blocks that were previously part of tanks. As a workaround, I coded in functionality in the Name Remover machine. Put your recently-destroyed tank blocks in it, and it'll wipe the NBT data so that they can stack with unused blocks.

**Comment by ah-OOG-ah** [comment]
> Why does Railcraft store NBT data for parts that were in tanks? Does it try to store the "contents" if you break the bottom center block?

Yes, yes it does.
