### ISSUE TITLE
AE2FC Fluid Disappeared!

### ISSUE THREAD

**Issue by DarkAhri** [GTNewHorizons/GT-New-Horizons-Modpack#15006]
### Your Pack Version

nightly 244

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

The terminal showed 31900mB of water. I wanted to use the empty unit to access 31B. I took the empty cell and clicked it while sneaking. All the water in the terminal disappeared. I expected that there should be 900mB of water in the terminal.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18422805/5029cc25-ce9e-4fae-a48c-b439a64711f4)
After click with empty cell
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18422805/be1e90f7-92d1-4afe-a456-ed3e3fa3b13a)

### Your Proposal

Plz fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hikari1nVoid** [comment]
can't repro in wireless terminal.sneak clicked with empty cell and does not lost 200mb of fermented biomass
![20231205231138](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24840795/fe9405db-c9cc-4f89-80b4-67de3331a19f)
.

**Comment by Dream-Master** [comment]
try out 248

**Comment by DarkAhri** [comment]
> can't repro in wireless terminal.sneak clicked with empty cell and does not lost 200mb of fermented biomass ![20231205231138](https://private-user-images.githubusercontent.com/24840795/288087247-fe9405db-c9cc-4f89-80b4-67de3331a19f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MjI5NzAsIm5iZiI6MTcwMTgyMjY3MCwicGF0aCI6Ii8yNDg0MDc5NS8yODgwODcyNDctZmU5NDA1ZGItYzljYy00Zjg5LTgwYjQtNjdkZTMzMzFhMTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAwMzExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MGIyMzE3NDAyOWRiNjRjY2E4NjcyYWQzM2VhNDdjMDQzNzU2ZjcxNTIzYjJmZTE2NDFmMjU5NGIwMDllZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.njTBmanmJp76B6PN85RwLuzT5m06MdUr0zqx3vSOu2Q) .

Try to sneak clicked with more empty cell than fluid in terminal!

**Comment by DarkAhri** [comment]
> can't repro in wireless terminal.sneak clicked with empty cell and does not lost 200mb of fermented biomass ![20231205231138](https://private-user-images.githubusercontent.com/24840795/288087247-fe9405db-c9cc-4f89-80b4-67de3331a19f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MjI5NzAsIm5iZiI6MTcwMTgyMjY3MCwicGF0aCI6Ii8yNDg0MDc5NS8yODgwODcyNDctZmU5NDA1ZGItYzljYy00Zjg5LTgwYjQtNjdkZTMzMzFhMTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAwMzExMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MGIyMzE3NDAyOWRiNjRjY2E4NjcyYWQzM2VhNDdjMDQzNzU2ZjcxNTIzYjJmZTE2NDFmMjU5NGIwMDllZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.njTBmanmJp76B6PN85RwLuzT5m06MdUr0zqx3vSOu2Q) .

Try to sneak clicked with more empty cell than fluid in terminal!

**Comment by Hikari1nVoid** [comment]
![QQ截图20231206185905](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24840795/cf31f762-3c77-4ecb-bf1d-5a01d6cacd87)
TEST#2:tried with exceeding cells:leftover fluid disappears.
Test#3:universal fluid cells(including those GT ones)have no issue.The root cause is the last cell could not be formed due to insufficient fluids.

**Comment by MCTBL** [comment]
I tested after this RP https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/177 and can't repro
But I only test with vanilla buckets
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/30978504/8cfdc33c-3871-48b9-8375-d9dd5f3d8c20)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/30978504/e5d06243-7167-49d3-90da-0a52277b7ba1)

**Comment by boubou19** [comment]
I suspect it fixed it too, but i'm no expert of the AE2/FC code base, so i asked the PR author for confirmation, waiting for it
