### ISSUE TITLE
An error is reported after loading a multiplayer server

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/GT-New-Horizons-Modpack#15003]
### Your GTNH Discord Username

Admin_XiaoMai

### Your Pack Version

nightly-23-12-04  245

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

![II 6 IUD8Z5@_TW6DCV$OHK](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/06adb97b-dae5-40bf-82ea-01387d865b05)

join server

### Crash Report

https://paste.ubuntu.com/p/d7rvNDzf2g/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Hikari1nVoid** [comment]
trophies related.I don't think it's finished
