### ISSUE TITLE
Algae Farm show "Machine turned off  due to crash"

### ISSUE THREAD

**Issue by DarkAhri** [GTNewHorizons/GT-New-Horizons-Modpack#15005]
### Your Pack Version

nightly 244

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I originally wanted to design an ammonia production line, but encountered this problem.
Looking at the log, it may be a problem with parallel processing, so I rolled back the GT version to GT 5.09.44.77, and then it ran normally.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18422805/abde5ad3-b961-4108-8b66-525d751797be)
Log's here:
https://paste.gg/p/anonymous/241c6ad3d2a84ec2a9a2d87e4b196677

### Your Proposal

Plz fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
I think it's been fixed by [this](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2389)
