### ISSUE TITLE
Add configuration option to change potion effect intensity on picking up fluid tanks

### ISSUE THREAD

**Issue by asoftbird** [GTNewHorizons/GT-New-Horizons-Modpack#15011]
### Your GTNH Discord Username

tufted_titmouse

### Your Pack Version

2.4.0

### Your Proposal

Add a configuration option to change the multiplier of potion effects on picking up super/quantum tanks. Currently, this is hardcoded, so the debuffs cannot be disabled. 

This could either be a multiplier (1.0 as default) or a true/false enable/disable setting. 

### Your Goal

For reference, see [discussion on GTNH Discord](https://discord.com/channels/181078474394566657/603348502637969419/1181543559183212554). 
See also: [discussion on where the code related to this effect is likely located](https://discord.com/channels/181078474394566657/603348502637969419/1181578793199083621).

In my opinion, this should be an effect that can be disabled or reduced if players (ie. me) desire so. 
Currrently this is hardcoded (which is defined [right here](https://github.com/GTNewHorizons/GT5-Unofficial/blob/a72f4c3fef4256cdb943af329a5f4759b7eeebf1/src/main/java/gregtech/common/blocks/GT_Item_Machines.java#L354) afaik) and cannot easily be changed.

### Your Vision

Allows people to better finetune their experience.

(In my opinion the effects should be reduced in general. I have [opened a separate issue for this](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15014).)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/2393

will be added after stable

**Comment by karikamiya** [comment]
Is there any plan to have this available as a config option for all tanks? The linked PR only had changes re: quantum tanks

**Comment by bombcar** [comment]
> Is there any plan to have this available as a config option for all tanks? The linked PR only had changes re: quantum tanks

There's no plan for such, and if someone wanted to code something adding "armor immunity" to tank pickup for the appropriate armor might be an option - but wrapping the debuff in a config option wouldn't be terribly hard.
