### ISSUE TITLE
Reduce debuff effects of picking up tanks containing fluids for higher-tier tanks / lategame players

### ISSUE THREAD

**Issue by asoftbird** [GTNewHorizons/GT-New-Horizons-Modpack#15014]
### Your GTNH Discord Username

tufted_titmouse

### Your Pack Version

2.4.0

### Your Proposal

See discussion on the GTNH Discord [here](https://discord.com/channels/181078474394566657/603348502637969419/1181543559183212554) for reference.

I have also created a related issue that does not concern changing the mechanic itself, but just for [adding a configuration option](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15011) so the effect can be changed or disabled on a end user level.

The mechanic is defined in code [right here](https://github.com/GTNewHorizons/GT5-Unofficial/blob/a72f4c3fef4256cdb943af329a5f4759b7eeebf1/src/main/java/gregtech/common/blocks/GT_Item_Machines.java#L354).

---

**Proposal:** Change the way debuff effects scale with tank contents/capacity in a way that proportionally affects late-game players less than early-game players.

**Alternative proposal:** Make higher tier armors (quantum+) completely negate the debuffs, similar to the way the hazmat modifier works. (See also: [this related issue](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14673).

**Background**  
In my opinion the debuff potion effects that get applied when picking up a tank containing fluid should be changed so this proportionally affects lategame players less. The effect is used to deter people from just hauling giant amounts of fluid around with no effort, and encourages people to use pipes.

However, later in the game, cells with sufficient capacity become available which can completely bypass this mechanic. At this point, the debuffs become a nuisance, something you're well equipped to have to deal with but shouldn't have to. 

The debuffs also scale with capacity, so despite having cells available that can carry 500kL of liquid, the potion effects for picking up a tank that big will still last 10 minutes and pretty much kill you if you don't apply an effect removing item (milk, terra wart) and get some food in. To me this seems reversed; why does the effect become more intense for people who can instantly delete the effect just by applying an effect removal item? 

Having to deal with this in late game phases is not a deterrence, since it can be dealt with, but it certainly is very annoying.

### Your Goal

Late game players should be able to focus on things that matter and should not get intense debuffs for things that don't really matter at their technology level. Much like pizza gloves and hazmat suits, it should change earlygame debuffs into something that is no longer as big of problem for later-game players. 

### Your Vision

This change should not affect earlygame players. However, players who progressed further into the game (can fly / short range teleport / remove potion effects easily, etc) should be able to focus on building infrastructure and should not have to deal with incredibly intense potion effects (which don't scale down with progression or armor tier!) resulting from picking up a full fluid tank. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Another way of doing the same might be to declare quantum tanks as different (since they use field generators) so they just don’t apply any debuff whatsoever. By the time you can make them you’re pretty far along.

**Comment by Dream-Master** [comment]
good idea maybe only super tanks have a debuff.

**Comment by CactusCool** [comment]
I like this idea but sometimes you only want to have a certain size buffer of something and quantum tanks might be too big for that purpose. I like the idea of quantum armor/other high-tier armor negating the debuffs more.
