### ISSUE TITLE
Fusion Reactor should not deduct EU when running one recipe and immediately switching to another recipe

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#15015]
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

GTNH Nightly 248

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Use Fusion Reactor and switch between multiple recipes

### The Reality

For example, an mk2 Fusion Reactor is running a recipe for tin plasma. After its run, it detected that there was not enough tin plasma recipe material in the input chamber, but there was enough zinc plasma recipe material. When it switched to zinc plasma, it deducted 180000000 EU.This situation can also occur in Compact Fusion.

This leads to frequent switching of recipes when using Fusion Reactor, which requires waiting for a period of time to charge. If there is not enough EU to deduct, it will not start. Due to the high input power and fast charging speed, the waiting time for Compact Fusion will be slightly shorter. But none of them should have happened.

### Your Proposal

Modify its logic to prevent this situation from happening again

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by JodieRuth** [comment]
> What about earlier version?

Early versions will not deduct EU. Only when there are no available recipes and it is completely shut down, will EU be deducted from the next startup.

**Comment by vovaksenov** [comment]
I dont think its a bug. It is a feature request. I dont think it should be as simple as this, but maybe a cool idea if limited to mk4/5 compacts or something. Normally i would call this an unnecessary buff but i feel like thus might be useful if support for cribs is implemented (iirc there was a ticket for this), with how priority usually works there.

**Comment by JodieRuth** [comment]
> I dont think its a bug. It is a feature request. I dont think it should be as simple as this, as this behavior is specifically intended to discourage you from using small recipes, but maybe could be a cool idea if limited to mk4/5 compacts or something. Normally i would call this an unnecessary buff but i feel like something similar to this might be useful if support for cribs is implemented (iirc there was a ticket for this), with how priority usually works there.

However, it is currently not possible to input EU into the internal cache of Fusion during its runtime, and even Conpact Fusion must wait for a period of charging time when switching recipes. It's obvious that it shouldn't work this way

**Comment by Alaking** [comment]
Afaik it's only not possible to input eu into the buffer if not all energy hatches are getting power, this also seems like bugged behavior imo and iirc there's an issue for it already

**Comment by JodieRuth** [comment]
> Afaik it's only not possible to input eu into the buffer if not all energy hatches are getting power, this also seems like bugged behavior imo and iirc there's an issue for it already

Even with 32 wireless energy hatches, it is not possible to input any EU for its internal cache during Compact Fusion runtime

**Comment by HoleFish** [comment]
I'm modifying compact fusion, which is a possible reason for it. But how could it possibly affect the normal one?

**Comment by JodieRuth** [comment]
> That might be a different, wireless hatch related, bug then. 

Just to illustrate that it is unlikely to be caused by a lack of electricity. Both Compact Fusion and regular Fusion exhibit this phenomenon

**Comment by HoleFish** [comment]
failed to reproduce in 248. Neither mk2 nor compact mk3. I can even hot update energy hatches without stopping machines...

**Comment by Glease** [comment]
can't reproduce either.
