### ISSUE TITLE
Remove rock crusher recipes

### ISSUE THREAD

**Issue by vovaksenov** [GTNewHorizons/GT-New-Horizons-Modpack#15010]
### Your GTNH Discord Username

vovassgreat

### Your Pack Version

nightly 183

### Your Server

unrelated

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Rock crusher does not have recipes, as it is uncraftable anyway.

### The Reality

The following two recipes still load.
![image-34](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86674724/5fdcbe4f-46a4-49b2-b6d4-f630d1f1853c)
![image-40](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86674724/f8030c4a-85c9-4d97-8a9d-d1d08d9f834a)

### Your Proposal

Remove these to avoid an extra NEI tab and to avoid confusion.
This issue was made on behalf of EvgenWarGold.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
we could disable it in rc code if core mod is loaded ? maybe same for other machines we not use
