### ISSUE TITLE
Carbon element non conservation in HeadedBauxiteSlurry formula

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#15026]
### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

I am trying to use HeadedBauxiteSlurry to produce aluminum

### The Reality

I found that carbon dioxide cannot be fully recovered
Each recipe consumes 5000L of carbon dioxide, but I can only obtain 3500L of carbon dioxide from the product

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
yea, some loss is allowed even with chem balance. Some of the CO2 going into the atmosphere in this case, makes perfect sense.
