### ISSUE TITLE
Blueprint autobuilding don't replace frame box

### ISSUE THREAD

**Issue by HoleFish** [GTNewHorizons/GT-New-Horizons-Modpack#15021]
### Your Pack Version

nightly 248

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Autobuild oil drilling rig/miner/compact fusion/other machines by blueprint. 

### The Reality

All of the casings/glass/other blocks are placed, but the frame boxes are not if there're other type of frame boxes in the same position. 

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Not a bug. Anything other than fluid, vine, short snow, fire and air need to be dug up manually.
