### ISSUE TITLE
Revert AE2FC essential cell ids.

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#15020]
### Your GTNH Discord Username

Hiakri1nVoid#9527

### Your Pack Version

nightly248

### Your Server

zeta

### Java Version

Java 20

### Type of Server

Thermos

### Your Expectation

Load the world with thaumometric essentia cell.

### The Reality

It turned into a 256k-essentia cell.

### Your Proposal

@MCTBL You messed up item ids. plz change the mod item id back in AE2FC.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by MCTBL** [comment]
working on it now

**Comment by MCTBL** [comment]
change for index: https://github.com/GTNewHorizons/ThaumicEnergistics/pull/56
change for recipes: https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/771
Now the index of creative cell changes back to 4
Left to right is 4 to 10
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/30978504/2e6c28c8-4317-441a-a5fd-c78ea0398b79)
