### ISSUE TITLE
Switch positions of "Import/Export" text in pump/regulator/conveyor cover to mirror the actual position of the buttons.

### ISSUE THREAD

**Issue by karikamiya** [GTNewHorizons/GT-New-Horizons-Modpack#15025]
### Your GTNH Discord Username

<blank>

### Your Pack Version

2.4.0

### Your Proposal

The buttons on the Pump/Regulator/Conveyor cover are in the order "Export/Import" but the text is in the order "Import/Export"

![inout](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45744547/090af8e3-df95-48a5-8e66-81f7fd4d35b7)

My proposal is to switch either the text or the buttons so they match

### Your Goal

It's gotta match bro, it's just gotta.

### Your Vision

If it matches then it won't be confusing to noobs

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by karikamiya** [comment]
That is my actual discord user name

**Comment by Dream-Master** [comment]
I just change the text. If someone want to change the buttons make a new pr and close my pr.
