### ISSUE TITLE
Overflow Valve (LV) is missing a recipe

### ISSUE THREAD

**Issue by vovaksenov** [GTNewHorizons/GT-New-Horizons-Modpack#15045]
### Your GTNH Discord Username

vovassgreat

### Your Pack Version

nightly 248

### Your Server

unrelated

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Should be craftable, as it there is quest for it.

### The Reality

Has no recipe (other overflow valves are still craftable though).

### Your Proposal

Either add a recipe or remove the quest.

This issue was made on behalf of EvgenWarGold.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
looks like the higher tier ones exist but all the recipes are shifted by one
