### ISSUE TITLE
Coal Boilers still drop tiny dusts when Coal or Charcoal are used.

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#15049]
### Your Pack Version

GTNH-2023-11-29+249

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

With the move away from Tiny Dusts, these should have a proportional chance to drop full dusts rather than tiny dusts

### The Reality

Coal Boilers still drop tiny dusts with certain fuels

### Your Proposal

Unify the behaviour with other blocks in moving away from tiny dusts to full dusts

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
If you use coal blocks for boiles i am ok with drop a full dust but coal should give obly tiny dust with a chance x

**Comment by Dream-Master** [comment]
But that means a boiler can run much longer without maintenance. Guess he stopped when the slot is full.
