### ISSUE TITLE
Input Hatches stops accept gases

### ISSUE THREAD

**Issue by JohnWarrior01** [GTNewHorizons/GT-New-Horizons-Modpack#15048]
### Your GTNH Discord Username

deusmechanicus

### Your Pack Version

2.4.2-253

### Your Server

SP

### Java Version

Other versions in between

### Type of Server

Single Player

### Your Expectation

Working normally hatches

### The Reality

After update to nightly - find out my gas turbine stop accept gases. First - checked fluid regulators, gases successfully transmit between tanks. But when I try to pump it into hatch - no result. Also tries EIO pipe, auto-output GT tanks, pumping through GT pipes and ME Fluid Export bus.

### Your Proposal

Please, fix :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
works fine for me 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/a596364c-9caf-42ae-afa1-8bb8c5917b6a)

who did you ask that confirmed the issue?

maybe provide some more details. starting with (but not limited too) what gas. what are the steps to reproduce?

**Comment by JohnWarrior01** [comment]
Very strange that.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/28770016/09de3a17-ed47-49d9-9aa9-68b7ebe4a175)
Wireless - export bus - input hatch. 
Tried methane, nitrobenzene, lpg, also just try benzene - nothing.

Maybe it's turbines' problem?

Step - just regular setup with FR

**Comment by JohnWarrior01** [comment]
Yes, after update - it suddenly became "incomplete", so i rebuild it)

**Comment by bpwhelan** [comment]
I have this same issue, might be a GT++ thing? I've noticed it on the XL turbines, and Thermal Boiler (explosion lol) in particular... Doesn't seem to be all GT++ machines though, since the multi electrolyzer doesn't seem to have the same problem.

Stocking hatches work though.

**Comment by TorvikW** [comment]
I'm having the same issue on Nightly 252. When I break and re-place the input hatch it works for a few seconds and then breaks again. I'm using a Large Gas Turbine.

**Comment by miozune** [comment]
I have made a fix. Note that you need to break and re-place hatches if your save has loaded nightly 244-254.

**Comment by JohnWarrior01** [comment]
> I have made a fix. Note that you need to break and re-place hatches if your save has loaded nightly 244-254.

so we need to upgrade to next nightly? or justto replace GT5?)

**Comment by miozune** [comment]
I'm working on fixes for other mods as well. But for gas turbine / advanced gas turbine, yes, you can drop-in GT5 105-pre.

**Comment by JohnWarrior01** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/28770016/0ea94da6-9673-49ac-b0ae-b6c231903482)
XL turbine still not working :) Should
