### ISSUE TITLE
Large Chemical Reactor Single-step sulfuric acid formulation lost

### ISSUE THREAD

**Issue by xiaoxing2005** [GTNewHorizons/GT-New-Horizons-Modpack#15046]
### Your Pack Version

2.4.2-nightly-2023-12-7

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

![_2088665266_Cache_54d0f532d1641138_1702038763000_xg_0](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/140354230/34b67b92-3013-466a-a760-2424701a11ac)
The original recipe.

### The Reality

Current recipe
<img width="1280" alt="1" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/140354230/e62171f7-617e-4fc5-ba04-2350c38e4685">
<img width="1280" alt="屏幕截图 2023-12-08 203929" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/140354230/42c38d10-e017-49da-827a-2d04126e862d">

### Your Proposal

Repair single-step sulfuric acid formula

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
According to EvgenWarGold, the normal recipes are present on nightly 248

**Comment by xiaoxing2005** [comment]
I made a mistake, I used Jenksins to update nightly and it doesn't seem to be working out。
