### ISSUE TITLE
LV Semifluid Generator has 4000mB of fluid storage, should be 16000mB

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#15047]
### Your GTNH Discord Username

britishcynic

### Your Pack Version

GTNH-2023-11-29+249

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

After the recent standardisation of fluid storage per tier, the LV semifluid generator should be able to hold 16000 mB of fluid

### The Reality

The LV semifluid generator only holds 4,000 mB of fluid storage

### Your Proposal

In keeping with the rest of the tier, this block should be changed to allow 16000 mB of fluid storage. Have not checked the rest of the tiers for the Generator yet, but they should also be checked for consistency.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
semifluid is 4000l per tier, so 4k, 8k, 12k, will submit a PR to make it match the GT normal gens at flat 16k for all tiers.
