### ISSUE TITLE
Add recipe to make pulsating iron in bulk

### ISSUE THREAD

**Issue by garaiza-93** [GTNewHorizons/GT-New-Horizons-Modpack#15050]
### Your GTNH Discord Username

nowaaaay

### Your Pack Version

2/4/0

### Your Proposal

Add a recipe that makes pulsating iron in bulk, similar to how there are recipes to make 9kL sulfuric acid instead of 1k.
This recipe could be available at a higher tier (HV+) and take more energy, but it makes more pulsating iron.

### Your Goal

Pulsating iron is used extensively for item conduits, at 1 ingot per conduit. However, the recipe only makes 3 at a time.

### Your Vision

Access to more pulsating iron in one operation as opposed to many smaller operations can improve QoL.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
due to batch mode there really is no point anymore to these bulk recipes
