### ISSUE TITLE
Pam's Energy Drink should drop a bottle when consumed

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#15053]
### Your GTNH Discord Username

britishcynic

### Your Pack Version

GTNH-2023-11-29+249

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

When drinking the Energy Drink, an empty bottle should be returned to the player's inventory in its place, the same behavior as the Mineral Water or Purple Drink performs when consumed.

### The Reality

An empty bottle does not drop.

### Your Proposal

Fix the behavior so that an empty bottle does drop. The ingredient of Bubbly Water can only be created by using a GT Mineral Water in a shapeless recipe to convert it, and that can only be created with a glass bottle.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
did it use a bottle in recipe?

**Comment by BritishCynic** [comment]
It doesn't directly, as I have mentioned, but the item used to make one of the recipe's components does, hence why it should drop a bottle.

**Comment by Dream-Master** [comment]
so far ik pams mod never drop bottles or bouls in any recipes. But sure it can be changed.

**Comment by BritishCynic** [comment]
I don't think many of Pam's foods incorporate a bottle, if at all, it's only due to a quirk of the Bubbly Water being converted from a GT item that *does* use a bottle that makes this change request appropriate.

**Comment by bombcar** [comment]
There is no other way to get bubbly water?

**Comment by BritishCynic** [comment]
Nope, the NEI entry is a single shapeless recipe with a GT Mineral Water as the sole component.

**Comment by Mobius0526** [comment]
> I don't think many of Pam's foods incorporate a bottle, if at all, it's only due to a quirk of the Bubbly Water being converted from a GT item that _does_ use a bottle that makes this change request appropriate.

When I turned it into soda, the system had already returned an empty bottle in your backpack
