### ISSUE TITLE
Black screen after Thaumcraft's warp effect's vignette

### ISSUE THREAD

**Issue by JohnWarrior01** [GTNewHorizons/GT-New-Horizons-Modpack#15063]
### Your GTNH Discord Username

deusmechanicus

### Your Pack Version

2.5.0-beta 1

### Your Server

SP

### Java Version

Other versions in between

### Type of Server

Single Player

### Your Expectation

---

### The Reality

After triggering warp effect (no matter which) - screen, except GUI, become black and become to normal only after full-restart.
Google said, reason is conflict optifine-thaum.shaders, but in this pack there is no opti and thaum shaders are off in settings.

Also, I tried Java 21 graal, Java 21 Adoptium and Java 8 - effect was in all.
Also, effect is pretty random, and some people can confirm, some not even meet it, so i doenst check 2 and 3 checkpoint.

 

### Your Proposal

---

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Which video card do you have?

**Comment by RaeKiyari** [comment]
by any chance do you use the (idk the name) holo glasses from Open computers. I only noticed that bug while running nidas and then getting the thaumcraft effect. also un-equipping the glasses fixes the black screen.
