### ISSUE TITLE
Move arrow crafting recipes into a separate NEI category

### ISSUE THREAD

**Issue by evgengoldwar** [GTNewHorizons/GT-New-Horizons-Modpack#15067]
### Your GTNH Discord Username

EvgenWarGold

### Your Pack Version

Nightly 248

### Your Proposal

Move arrow crafting recipes into a separate NEI category
![изображение_2023-12-11_134136297](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/69961523/f923adc8-b6f1-4a58-bcfa-788bd9352a81)
![изображение_2023-12-11_134155154](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/69961523/e41b375b-faac-49ea-8d37-26d23e58fe37)

### Your Goal

It will be easier to navigate with crafts

### Your Vision

When viewing the necessary recipes, useless arrow recipes will not be displayed for nothing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Alternative to #12963

**Comment by miozune** [comment]
It cannot be alternative of #12963, since there would still be crafting table recipes and NEI entries.
