### ISSUE TITLE
GT++ Output Super Busses turning into .name items

### ISSUE THREAD

**Issue by Jackol03** [GTNewHorizons/GT-New-Horizons-Modpack#15060]
### Your GTNH Discord Username

Propainchan

### Your Pack Version

2.5.0 Beta 1

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

I updated the pack from 2.4.0 stable to 2.5.0 beta 1 and all the gt++ output busses turned into GT .name items making machines incomplete.

### The Reality

New output busses placed in world seem to be okay only the ones existing before updating broke.

### Your Proposal

Fix maybe? 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
Do you refer to Gregtech output busses on GT++ multis or the GT++ Super Busses (O)?

**Comment by chochem** [comment]
or steam output bus? (from the gt++ steam multis)

**Comment by Jackol03** [comment]
This is for GT++ Super Busses O.

**Comment by chochem** [comment]
which tier?

**Comment by Jackol03** [comment]
Super Bus O MAX I'm pretty sure
