### ISSUE TITLE
Crafting Calculator (Just Enough Calculations) no longer allows clicking recipes from NEI for GT Machines

### ISSUE THREAD

**Issue by Dyonovan** [GTNewHorizons/GT-New-Horizons-Modpack#15077]
### Your GTNH Discord Username

Dyonovan

### Your Pack Version

2.5.0-beta-1

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I know that Just Enough Calculations is not in the pack by default, but it is on the optional mods list on the wiki. Up until this beta release, it had no issues being able to shift click the recipe into the calculator from NEI. The ? from NEI is no longer available on GT Machine recipes.

### The Reality

You are no longer able to shift click recipes from NEI into the calculator.

### Your Proposal

Return the ? mark to nei?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dyonovan** [comment]
If its not supported, remove it from the Additional Mods List on the wiki

**Comment by chochem** [comment]
none of those are from the GTNH team with the exception of server utilities.

**Comment by mitchej123** [comment]
https://docs.google.com/spreadsheets/d/1LHd8c4FLLHiJqsuTppF2XFTE6bh-mXE7afVwGbzOKms/edit#gid=1469028684

**Comment by litten8** [comment]
Even without JEC, the ? button is missing, so this isn't an unsupported mod issue.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/20496976/7147474c-6312-44cf-bb91-a4066c9f9a64)

**Comment by miozune** [comment]
> Even without JEC, the ? button is missing, so this isn't an unsupported mod issue.

In which screen? GT machine GUIs don't support overlaying recipe in the first place.

**Comment by litten8** [comment]
Yeah, but the ? button used to show regardless in the NEI screen

**Comment by chochem** [comment]
here is a 2.4.0 screenshot since you dont believe miozune 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/38170abb-2ae3-44e3-95e2-faecdc113d1a)

**Comment by litten8** [comment]
oh ok, i still feel like it'd be really nice if this were fixed, since JEC is just so handy for major projects before reaching ae2

**Comment by Caedis** [comment]
Give this a shot: https://github.com/GTNewHorizons/JustEnoughCalculation/releases/tag/1.7.10-4.0

**Comment by Dyonovan** [comment]
Thanks very much.

**Comment by vovaksenov** [comment]
@Caedis should the link on the gtnh wiki then lead to the gtnh jec repo instead of the original one then?

**Comment by bombcar** [comment]
Link should now be like Server Utilites where it goes to the general releases page on github

**Comment by Caedis** [comment]
@vovaksenov yes please

**Comment by Graymare** [comment]
Wiki has been updated to the correct mod fork, thanks for the heads up.

**Comment by KYDuck123** [comment]
I've installed the new GTNH JEC version after seeing it linked here, but still cannot add GT recipies to JEC.
