### ISSUE TITLE
Assembling Machine Circuit 24 Visual Bug

### ISSUE THREAD

**Issue by BEEF-Gaming** [GTNewHorizons/GT-New-Horizons-Modpack#15079]
### Your GTNH Discord Username

ShrooMoo

### Your Pack Version

2.5.0 Beta 1

### Your Server

I run my own dedicated server on same machine. I'm the only player. 

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Circuit 24 should look the same as other circuits when selecting in the assembler. I had this bug in 2.3.x, but it went away in 2.4.x, and is back in 2.5.0.

This happens with and without texture packs, shaders, and optifine.

Image here: https://imgur.com/a/UZGfv2L

### The Reality

Circuit 24 has what looks like an opaque block over it. 

### Your Proposal

Fix :D

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you really asked people that can confirm it? maybe compare notes with them to see what is special about your setups.

doesn't happen for me.

**Comment by BEEF-Gaming** [comment]
> you really asked people that can confirm it? maybe compare notes with them to see what is special about your setups.
> 
> doesn't happen for me.

I just recently posted this in the in the General chat to see if anyone else has experienced it and was told to make a ticket by staff member Bombcar, hence this ticket.

**Comment by chochem** [comment]
so no? gonna remove the checkmark then

**Comment by BEEF-Gaming** [comment]
So. I changed my Java Version from 17 to 20, and now the visual bug is on circuit 23 instead of 24. I have no idea if that helps, but thought I'd share.

**Comment by chochem** [comment]
that sounds utterly unrelated. just means its random or that you changed something different

**Comment by BEEF-Gaming** [comment]
> that sounds utterly unrelated. just means its random or that you changed something **different**

That's legit all I changed. I know nothing of Java, so I believe you lol. I'm going to swap back to 17 to confirm. In reality, I'm not really bothered by this btw. Just wanted to share it. 

Swapped back to 17 and the bug is still on 23, so definitely unrelated, but does seem to be random. 

UPDATE: So it does NOT happen on a singleplayer world, only when I'm playing on my server.

**Comment by BEEF-Gaming** [comment]
And in another update, I copied my server world to a singleplayer world, and it's there again, so it's baked into my save somehow :D

**Comment by miozune** [comment]
It's caused by z level of item block under the panel being higher than circuit item, not by Java version / modpack version / save.
I'm really not sure how to fix this issue properly...

**Comment by miozune** [comment]
I cannot reproduce though, what item block under the circuit is there?

**Comment by BEEF-Gaming** [comment]
> I cannot reproduce though, what item block under the circuit is there?


It's far beyond my understanding. I did notice it's not limited to the assembler, it's the circuit 23/24 (it was 24 suffering earlier, now it's 23) on ALL machines. Basically the circuit menu itself seems to be bugged, not limited to any specific machine.

**Comment by miozune** [comment]
I mean I want to see your inventory. You have configuration panel over inventory, right? What is the inventory item placed at the same position where circuit item is rendered incorrectly?

**Comment by BEEF-Gaming** [comment]
Omg, it's the dev null lol. If I have it off to the side, it's not an issue.

**Comment by bombcar** [comment]
what is a dev null

**Comment by miozune** [comment]
It can't be /dev/null though... I cannot reproduce with it, nor it has block shape like the image you sent

**Comment by bombcar** [comment]
that shape looks like the thaum scanner thing

@BEEF-Gaming can you screenshot your inventory before opening the circuit GUI

**Comment by BEEF-Gaming** [comment]
I'm in bed currently.  It is 1000% the dev null. Mine currently has cobblestone in it. I can move the dev null to any inventory slot corresponding to the circuit menu, and the bug appears in its respective slot. 

I will give video proof tomorrow if you need. The shape is exactly like any square block (look at an alloy smelter mold for blocks ), which makes since since its same shape as cobblestone in the dev null.

**Comment by miozune** [comment]
Ah I see, block needs to be put into the /dev/null. Now I can reproduce the issue. But the fix is... different story
