### ISSUE TITLE
ME Interface Terminal not hiding ME Interfaces/Dual Interfaces when set to hide

### ISSUE THREAD

**Issue by Dyonovan** [GTNewHorizons/GT-New-Horizons-Modpack#15076]
### Your GTNH Discord Username

Dyonovan

### Your Pack Version

2.5.0-beta-1

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

When ME Interfaces/Dual Interfaces are set to hide, the ME Interface Terminal should not show them

### The Reality

Even when set hidden, they are still appearing.

### Your Proposal

Have the ME Interface Terminal hide them when hidden.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
doesn't happen for me on 2.5.1
