### ISSUE TITLE
Essentia bottler and unbottler

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#15075]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.5.0

### Your Proposal

Add a block where you can insert essentia phials and essentia by pipes/golems/essentia provider, and fill them with essentia ( it could also work with basic jars) Also that if you place filled phials, it gives you the empty vial and export the essentia to any kind of pipe ( or an inside buffer)

Recipe for the proposed block:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/e66ea4a5-0c7d-492d-b002-96286c2b6028)

4 arcane stone block
2 Golem animation core ( Use and Alchemy)
1 Essentia funnel
1 Essentia pump
1 Dynamism tablet

### Your Goal

1. so you can automate certain crafts that uses essntia phials in them
2. you could make a essentia  package magic version of the ae2 fluid crafts  ( all this can be done using jars and dynamism tablets)
 

### Your Vision

This fill make setups that uses essentia more automatable and controlable, also I think that is a nice feature / QoL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
that's actually pretty neat
