### ISSUE TITLE
multiplying the number of items in a pattern

### ISSUE THREAD

**Issue by yarikbrek** [GTNewHorizons/GT-New-Horizons-Modpack#15073]
### Your GTNH Discord Username

captchaqq

### Your Pack Version

Nightly modpack build #250

### Your Proposal

Please make a mechanism for changing patterns (multiplication)

### Your Goal

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/68470638/94010746-94c9-4de5-8a49-b50ddfba55f9)

or you can do something similar as in 1.12.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/68470638/3a6c237e-d7f2-4673-b4f2-761d7bf95466)

### Your Vision

It is necessary to add this function for the convenience of the game for later stages

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by lordIcocain** [comment]
<img width="619" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62835225/11f53907-0b53-4e1f-997b-9b8cbad829d7">
this?

**Comment by yarikbrek** [comment]
> <img alt="изображение" width="619" src="https://private-user-images.githubusercontent.com/62835225/289819599-11f53907-0b53-4e1f-997b-9b8cbad829d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzYwNjAsIm5iZiI6MTcwMjM3NTc2MCwicGF0aCI6Ii82MjgzNTIyNS8yODk4MTk1OTktMTFmNTM5MDctMGI1My00ZTFmLTk5N2ItOWI4Y2JhZDgyOWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEwMDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhNDZiNDc3NTZhZjMyMzZmZjdkNzk1NTIyOWI4ZjYxOWQzYmM1MGRiZGRkYWU3OTcwZjJkMjNmZmZkNDIxZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sr2ZAVcFAYdpCqoHGI6l0sws4pt4V-aqX0S3GIYP_fs"> это?

It's inconvenient when you need to redo 100+ patterns

**Comment by vovaksenov** [comment]
Maybe just add a button inside the interface gui that doubles all patterns? Also ofc to cribs and stuff.

**Comment by yarikbrek** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/68470638/2fa624ec-37af-42bd-b179-ed12d2b05571)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/68470638/91cf1f7d-7966-4bfe-955c-e2daf0331dc8)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/68470638/53c1a586-af47-4d74-b4a3-7f5a9387f4ae)
I'd like to see something like this

**Comment by vovaksenov** [comment]
This would make it hard to specify recipes. How does it know if you want a recipe from ingot in bending machine or from fluid in a solidifier..
Interface multiplication is more intuitive

**Comment by yarikbrek** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/68470638/8f80b613-c0a0-48e2-a942-670f712893d9)
or you can do something similar as in 1.12.
