### ISSUE TITLE
Massive TPS lag spikes when leaving personal dimension.

### ISSUE THREAD

**Issue by Liether234** [GTNewHorizons/GT-New-Horizons-Modpack#15081]
### Your GTNH Discord Username

Liether345

### Your Pack Version

2.4.1 BETA

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Tried to leave my personal dimension and expect no TPS lag spikes to occur.

### The Reality

I get massive TPS spikes, which according to /xu_tps i get around 300 to 1200 (I do not know what unit of measurement for TPS it uses).
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/153777585/6a230407-5c2d-4c01-87e9-723b43bba893)

Interestingly, pausing the game for a short amount of time causes the TPS spikes to stop and the game returns to running normally.

### Your Proposal

Maybe a suggestion as to what I can do for now would be appreciated.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
When leaving pdim are you returning to chunkloaded chunks. 

Make a nether portal, do you see the same issue

**Comment by boubou19** [comment]
check the chunkloading in your personal dim: a half loaded AE2 system will tend to tank the TPS by performing constant chunk load/unload

**Comment by Liether234** [comment]
> When leaving pdim are you returning to chunkloaded chunks.
> 
> Make a nether portal, do you see the same issue

Responding to the both of you, i do not use any chunkloaders. Perhaps you guys are referring to when the game loads chunks in when entering a dimension. As to bombcar, where do you want me to make the nether portal, I tried making a nether portal in my pdim and it did not make a portal when I tried lighting it.

**Comment by boubou19** [comment]
so when you quit the dim, no machine is supposed to work right?
put admin anchors to chunkload your whole base then quit the dim. If the spikes are gone it was some improperly unloaded chunks otherwise we will have to dig deeper

**Comment by Liether234** [comment]
"so when you quit the dim, no machine is supposed to work right?"
Correct, everything in the dim does not work (intentional) and is frozen while im not in the dimension.

"put admin anchors to chunkload your whole base then quit the dim"
Did that and the lag spikes are gone. It appears Minecraft does not like it when it has to unload an entire base within the span of like 3 seconds. But I am curious though, before this, the lag spikes would disappear after a short while or sometimes never at all, why was that?

**Comment by bombcar** [comment]
Likely it’s because it has to load all your chunks and that spikes lag.  If they remain loaded, it doesn’t have to bring them in. 

The nether portal idea was from overworld at the same point you arrive when coming back from pdim.

**Comment by Liether234** [comment]
So is this usual Minecraft shenanigans or an actual GTNH bug?

**Comment by boubou19** [comment]
the issue here is that during the unloading of your base, something does a circular load, so it endlessly loads/unloads, which tanks the TPS. It's not a minecraft issue per se, but more about weird interactions between mods. This happens from time to time, you just need to be aware of the symptoms and how to fix it.
