### ISSUE TITLE
GT++ Half Complete Casing II recipe broken

### ISSUE THREAD

**Issue by gerben838665** [GTNewHorizons/GT-New-Horizons-Modpack#15080]
### Your GTNH Discord Username

gerben838665

### Your Pack Version

2.4.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Recipe available to craft "Half Complete Casing II".
Which is needed to craft "Vanadium Redox Power Cell (EV)".

### The Reality

No recipe is available.

### Your Proposal

Fix/restore "Half Complete Casing II" recipe.
2nd available "Half Complete Casing I" seems to be meant for the II version.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/23479081/b0ddba4a-b861-46ae-b622-4def53fbd62d)

Checking the github history the recipe seems to have been broken in the following commit:
https://github.com/GTNewHorizons/GTplusplus/pull/739/files#

Where it seems to have changed from:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/23479081/b576668c-1db6-4233-9ad1-4c5e7c7630f0)
To:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/23479081/bd61e14e-1604-4bb3-a25f-1f6582b04e14)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
As a reminder this recipes  need some rework after stable
