### ISSUE TITLE
Using NEI to open the quest book can cause closing the quest book to show an invalid UI stack

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#15098]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.5.0-RC1

### Your Server

Private Dedicated

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Testcase:

1. Put an item into a chest.  The item must have a use in a quest (such as a music disc)
2. Open the chest and press U on the item (or whatever you have "find uses" bound to)
3. In NEI, navigate to the Quest Book tab and click on a quest name to open the quest
4. Repeatedly press Escape to close the Quest Book, NEI, and chest inventory UIs
5. Open the Quest Book directly using its shortcut key
6. Press Escape to close the Quest Book
7. (Point of Bug) The Quest Book should close without bringing up any other UIs.

### The Reality

A specific set of interactions with NEI and the quest book can cause closing the quest book to open unexpected and/or invalid windows.

The incorrectly opened UI windows do not appear synced to the server, as demonstrated in the video (trying to take the music disc out of the "ghost" chest inventory UI does not actually move the music disc on the server).

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/a37ea8a2-b36e-40b3-b7e4-6a1b1df09c59

### Your Proposal

Feeeex please <3

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
I’ve run into this issue too in 2.4.2nightly,

fixed it by logging out and logging back in again.
