### ISSUE TITLE
Items/fluid packets are getting stuck in interfaces/dual interfaces/p2p dual interfaces when requesting a craft.

### ISSUE THREAD

**Issue by cytrus224** [GTNewHorizons/GT-New-Horizons-Modpack#15090]
### Your GTNH Discord Username

Cytrus

### Your Pack Version

2.5.0-rc1, but had those issues in 2.4.0 aswell

### Your Server

private MP server

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

Ask ae2 to craft a recipe, for example raw tesseract in DTPF, or Robot Arm UIV in assline, some plasma recipe in fusion. DFPF super input bus(max) didn't receive ZPM circuit, Assline didn't get UIV circuit in input bus ULV slice number 5, or couldn't input things into input hatches on compact fusion. Items were stuck in dual interface/p2p dual interface. Doesn't happen with 99% recipes, just some.

### The Reality

I tried checking what might be happening. Some items got stuck in dual interface/p2p dual interface. Placing storage bus on the subnet places missing item in the chest, also destroying dual interface/p2p dual interface gave back item or fluid. I can replicate issue on my server. Blocking mode doesn't matter. checked with off/on

### Your Proposal

Check why the heck items get stuck with some recipes in dual interface/p2p dual interfaces and why it inputs the recipe partially in inventories(or subnets)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by cytrus224** [comment]
Video of the issue: https://drive.google.com/file/d/1Q-Mb3IEYbhhchAqMu-QBeq2mGY7HFHo-/view?usp=sharing
Robot Arm UIV recipe gets inputted into assembly line, however UIV circuits are stuck in Dual Interface untill i place another storage bus and chest, magically circuits are getting inputted into the chest. Typical assline setup, p2p dual interfaces, multiple asslines with subnets and advanced blocking cards. I have this problem with random crafts, no idea why this happening.

**Comment by Rikenbacker** [comment]
Exactly same problem. All recepies in ass line containing processors are broken. Processors are stuck in interface or dual interface.
Version 2.5.1
Game: solo

**Comment by cytrus224** [comment]
@Rikenbacker that one was fixed. Some input buses turned on filter mode. If you click with screwdriver and turn it off, it will start working again. 
I will close the issue. If i can reproduce issue with p2p and fluids, will create new issue.

**Comment by Rikenbacker** [comment]
Yea, after clicking by screwdriver it is start working.
Thank you!
