### ISSUE TITLE
Assembler recipe for advanced bending machine III

### ISSUE THREAD

**Issue by mnewbold01** [GTNewHorizons/GT-New-Horizons-Modpack#15091]
### Your GTNH Discord Username

Drewdroid9#1341

### Your Pack Version

2.4.0

### Your Proposal

Add an assembler recipe for Advanced bending machine III

### Your Goal

to allow if to be AE autocrafted without a wrench. (crafting recipe has wrench)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/122412127/76cfecdb-c7b3-4efd-b986-14f7387585a6)

### Your Vision

improve ae autocrafting

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Dev has single use 🔧  now but an assembling machine recipe would be nice.

**Comment by Dream-Master** [comment]
We can also replace it with a cable if this not give a recipe duplication
