### ISSUE TITLE
Low Power Laser Hatches Aren't Working

### ISSUE THREAD

**Issue by El-Basurero** [GTNewHorizons/GT-New-Horizons-Modpack#15109]
### Your GTNH Discord Username

SeñorSplitpush

### Your Pack Version

2.5.0

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

After updating to 2.5.0 machines connected to active transformers that are connected to a  Lapotronic Supercapacitor (LSC) should receive power. This setup works on 2.4.0.

### The Reality

The machines didn't receive power.

### Your Proposal

After some testing I found that the issue seems to be related to sending power from a LSC to an active transformer with any low power laser hatches. I tested with both ZPM 64A and LuV 128A. ~~The low power hatches send power between active transformers fine~~, but aren't able to send from a LSC to an active transformer. I also confirmed the debug generator was able to send power to an active transformer.

Tests from LSC with 1,024 laser hatches were successful. 

Edit: Test between two active transformers with low power hatches was unsuccessful. Since the debug generator can send to a target hatch I'm thinking it may just be an issue with lower power source hatches.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
There was a fix to the LSC to actually do a specific structure check. That may be affecting this.

**Comment by SomeGuyDoinWork** [comment]
Can confirm I am also having this issue. Voided a ton of crafts :/ Oh well.

**Comment by chochem** [comment]
dont see how it can be related to LSC changes. There was however a refactor of the low-power lasers here https://github.com/GTNewHorizons/bartworks/pull/354

**Comment by glowredman** [comment]
> dont see how it can be related to LSC changes. There was however a refactor of the low-power lasers here [GTNewHorizons/bartworks#354](https://github.com/GTNewHorizons/bartworks/pull/354)

I looked through the changes in that PR that are related and couldn't find any issues.

**Comment by Dream-Master** [comment]
@El-Basurero its not a bug. Low Power laser hatches works different than High power lasers. I have a discussion with @S4mpsa about it. I am sure it is not worked that way in 2.4.0 also. If yes, it was broken in this version. If you or others want it to work like high power laser, we need to have a balance disunion first.
