### ISSUE TITLE
Reduce number of Weed-EX required by quest

### ISSUE THREAD

**Issue by AdolMors** [GTNewHorizons/GT-New-Horizons-Modpack#15100]
### Your Pack Version

2.4.0

### Your Proposal

The Weed-EX quest has a retrieval task of 32 IC2 Weed-EX, which is a non-stackable item. 32 inventory slots have to be freed temporarily to complete the quest.
Compare that to IC2 Hydration Cell which is another non-stackable item. The Hydration Cell quest requires only 1 Hydration Cell.

### Your Goal

Reduce the number of Weed-EX being made. Generally people side-step it by using crops with lower than 24 growth. The use of _that_ OpenComputer robot further undermines the use of Weed-EX by doing the trimming itself during operation (at the cost of a lot of crop sticks).

### Your Vision

This is really just about a minor annoyance of requiring 32 non-stackable items in the inventory to complete one quest.
Probably would need to nerf the quest reward a little if reducing the number.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Perhaps the reason weed-ex is unstackable should be investigated

**Comment by Glease** [comment]
It's an spraycan that can be damaged. why should it be stackable?

**Comment by AdolMors** [comment]
Fertilizer, Hydration Cell and Weed-EX affect the 3 respectively named stat for crops.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/71854daa-33ad-4040-8aee-6afadf642ee8)
Hydration Cell and Weed-EX are multi-use items. When used by hand, they take durability damage to add stats, up to 100 (Hydration Cell) and 50 (Weed-EX). The durability is most likely why they cannot be stacked. Extra points to hydration cell taking damage according to the added hydration stat so it may be damaged less or more.

**Comment by karikamiya** [comment]
Lots of damageable/changeable items can be stacked when they are in their pristine condition and/or when they are identical. @bombcar is right, there is no reason an unused spray can cannot stack with its similarly-full brethren.

**Comment by boubou19** [comment]
it's the same thing as unfolded dollies or buckets of water, or any minecraft vanilla tools or armors for instance. Why this one should be different?
