### ISSUE TITLE
Forgot to install Muffler Hatch in EBF in Trophies

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#15102]
### Your Pack Version

2.5.0-rc1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

![2023-12-17_17 15 35](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62875887/e9ca07e0-d1f3-48d8-91ef-60a5d3ba0bae)
![Uploading 2023-12-17_17.15.35.png…]()

### The Reality

。

### Your Proposal

。

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
it's just set up to point inside the multi 😉

**Comment by Mobius0526** [comment]
> it's just set up to point inside the multi 😉

I think this one is really beautiful, especially the Cleanroom
