### ISSUE TITLE
ULV Fluid Tank can't be emptied through crafting grid

### ISSUE THREAD

**Issue by dimazha** [GTNewHorizons/GT-New-Horizons-Modpack#15107]
### Your GTNH Discord Username

Lord_Tachanka

### Your Pack Version

2.4.0

### Your Proposal

Add an option to empty fluid tank by placing it into crafting grid
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/106115870/8eae405a-2f12-40ab-9a00-5b66b0ac95f5)

### Your Goal

Supertank has such option, fluid tank doesn't, it looks strange

### Your Vision

This will make GTNH better

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
The recipe already exists, but it is a shaped craft. You need to put the tank in the top left corner of the crafting grid.

![](https://i.imgur.com/Kw8HpUe.png)

Yes, it would be better and more intuitive if it was shapeless and the position didn't matter.
