### ISSUE TITLE
Wire Factory Controller Bug

### ISSUE THREAD

**Issue by zoroffGG** [GTNewHorizons/GT-New-Horizons-Modpack#15103]
### Your Pack Version

1.7.10

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I tried to input copper ingots in the Wire Factory Controller with a programmed ghost circuit number of 3 to get fine copper wire.

### The Reality

I got 1x copper wire(s) instead.

### Your Proposal

I would like this issue fixed to get the intended item(s) I wanted from this recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
1.7.10 is the minecraft version, not the pack version. All pack versions run on 1.7.10 so it does not help. Please check and specify which version of the modpack you are using.

**Comment by zoroffGG** [comment]
My bad, 2.2.0 I think.

**Comment by vovaksenov** [comment]
2.2.0 is like more than a year old at this point. The bug you have reported has most likely already been fixed..

**Comment by boubou19** [comment]
this version is ancient, try on later versions of the pack to see if it still happen

**Comment by vovaksenov** [comment]
I dont think 2.2.0 even had wiremill circuit support yet...

**Comment by zoroffGG** [comment]
Alright thanks guys
