### ISSUE TITLE
Removing Ender Zoo causes modloading to hang on "Loading Gregtech"

### ISSUE THREAD

**Issue by JL2210** [GTNewHorizons/GT-New-Horizons-Modpack#15101]
### Your GTNH Discord Username

JL2210

### Your Pack Version

2.5.0-RC1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

1. Download 2.5.0-RC1 and migrate 2.4.1 profile using https://gtnh.miraheze.org/wiki/Installing_and_Migrating
2. Disable/delete Ender Zoo
3. Wait for bell
4. Main menu does not load
5. Reenable Ender Zoo
6. Game loads to main menu after bell

<img width="429" alt="image" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/38843657/26a86843-bedd-45f2-bda2-6006a2f93666">

Java 21 wasn't an option but that's what I'm using

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13695052/fml-client-latest.log)

Can't find anything that looks relevant

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
And the very end mobsinfo does its thing. 

Try disabling ender zoo AND mobsinfo

**Comment by JL2210** [comment]
Disabled mobsinfo and the issue still occurred.

**Comment by Glease** [comment]
I have to remind you this is not an optional mod and we do not support removing it. leaving it open for a few more days in case someone else would like to help.

**Comment by JL2210** [comment]
Is disabling all the mobs a supported configuration?

**Comment by boubou19** [comment]
try peaceful mode, still not a supported way of playing the pack but at least you have no mod edits to perform.

**Comment by JL2210** [comment]
Disabling the mobs in the config works without issue. I can just do that
