### ISSUE TITLE
BlockRenderer-NEI Previews missing for multiple multis

### ISSUE THREAD

**Issue by LeoGuys1** [GTNewHorizons/GT-New-Horizons-Modpack#15110]
### Your GTNH Discord Username

LeoGuys

### Your Pack Version

2.5.0

### Your Server

PS

### Java Version

Other versions in between

### Type of Server

Don't know

### Your Expectation

I wanted to see, but there was no structure

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76493533/73aed84c-d1e8-4687-aa11-0c7834447d6a)

When I clicked on "Extreme Industrial GreenHouse", there was no display, although previously in version 2.4.0, there was one. Now it's gone

1) Extreme Industrial GreenHouse
2) Electric Air Filter T1
3) Dissolution Tank
4) Digester
5) High Temperature Gas-Cooled Reactor

### Your Proposal

I think it's enough to understand what I wanted to convey.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LeoGuys1** [comment]
6) Bacterial Var
7) Water Tank Siding (I'm not sure what was shown earlier.) 
8) Density^2
9) Solid-Oxide Fuel Cell Mk I 
10) Solid-Oxide Fuel Cell Mk II

That's all I could find, unfortunately. I hope you can find it further, if possible

**Comment by Dream-Master** [comment]
@LeoGuys1 can you write down from which mod every multi is. I guess it need to be added in the code.
