### ISSUE TITLE
The ME interface unable to deal with Crystalprocessor Assembly

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#15113]
### Your GTNH Discord Username

Eason1134HK

### Your Pack Version

2.5.0

### Your Server

delta

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

Crafting with the ass line 

### The Reality

https://www.youtube.com/watch?v=9M8HbIHYYuQ
The ME interface unable to deal with Crystalprocessor Assembly
other things can go into the input bus but the Crystalprocessor Assembly don't
the set up work 100% fine in 2.4.0 

### Your Proposal

Fix it 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eason134HK** [comment]
this bug seems only happen on some ass line , some for my ass line work fine but some don't

**Comment by cytrus224** [comment]
@Eason134HK i have the exact same issue with crystalprocessor assembly and DTPF and UIV circuits in asslines. Funny some of them work fine, some not. https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15090

**Comment by boubou19** [comment]
@Eason134HK what happens when you type /iih while holding thr crystalprocewsor assembly?

**Comment by Eason134HK** [comment]
> @Eason134HK what happens when you type /iih while holding thr crystalprocewsor assembly?

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/59776356/44ce4060-0ab6-464a-917d-80646560504d)

**Comment by chochem** [comment]
it would be nice if you could narrow down the issue somewhat. like is it AE or the AL? (aka test with chests instead of busses, or test with pipes instead of ae) and things like that.
that should also help you to give us devs a 'small setup to reproduce'.

**Comment by cytrus224** [comment]
It's hard to reproduce. This is whats happening in my DTPF with p2p dual interfaces. First one has the issue second does not, both have exactly the same subnet setups with p2p dual interfaces. I've also checked using only dual interface with subnet, or without subnet, didn't help. For sure this is issue with dual interfaces/p2p dual interfaces, since i also had issues with crafting in compact fusions. https://drive.google.com/file/d/10mfANEKTAKJLR0QlgN5k3zPWAfEgAaLr/view?usp=sharing

**Comment by SomeGuyDoinWork** [comment]
I have two identical asslines, using the setup from the wiki. I can confirm this is happening to one of them, but I also had an issue with crystalprocessors AND 180k NaK coolant cells.

This issue needs to be bumped to urgent - its going to break ALOT of worlds.

**Comment by SomeGuyDoinWork** [comment]
This is still an issue as of 2.5.1 @chochem.

It almost appears to be an issue with AE2 rather than anything else. Specifically around P2P items or Interfaces.

**Comment by cytrus224** [comment]
Looks like turning off filter mode in input buses with screwdriver fixes the issue. No idea about my issue with p2p dual interfaces and fluid packets getting stuck when crafting plasmas
