### ISSUE TITLE
Ghost text in Industrial Information Panel

### ISSUE THREAD

**Issue by AdolMors** [GTNewHorizons/GT-New-Horizons-Modpack#15119]
### Your Pack Version

2.4.0

### Your Server

Private

### Java Version

Other versions in between

### Type of Server

Don't know

### Your Expectation

Java version is 21 (2.4.0) but this happened when Java 8 was used (2.3.0, 2.3.6).

Industrial Information Panel is used to display LSC info here.

### The Reality

After some time (and some moving around so the panel becomes off screen), ghost text would appear. It seems like at some point the panel cannot properly clear the screen while continuing to display updated info. Below are 2 screenshots showing the on state with ghost text, and the off state with just the static snapshot. The basic info panel should not be able to display anything when it is off to begin with.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/02df1244-852f-42ee-b500-e3e6abe95f85)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/62dc6b14-4064-40bc-a29d-e1d2d0a5543f)
After breaking the extenders, the ghost text persists.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/dab241fa-1070-4e99-978c-5d5a2dcc93b0)
Panel and extenders are in the same chunk but I suspect it does not matter. The chunk should be loaded by FTBUtil but it may also not matter.

### Your Proposal

Very briefly looking into the code, this seems to be the only place screen.destroy() is called for info panel. I suspect this issue is caused by the condition somehow preventing the execution of screen.destroy() when it is needed.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/9ee817f0-f27a-4fee-91b5-6a176e878cc5)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hekkmac** [comment]
Please, please fix this! It affects like every player/playthrough!

**Comment by vovaksenov** [comment]
F3+A helps with this in my experience. Still would be great if it was fixed.
