### ISSUE TITLE
Trophies using items rotate incorrectly.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15121]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Display the new trophies.

### The Reality

Trophies that show items rotate the displayed item with the edge towards the player, making the item almost invisible.

Quick video of the problem: https://www.dropbox.com/scl/fi/tjqowfjtfapbi62vmoltn/WIsloYzglN.mp4?rlkey=zryr8wsmbu2q6u2zc6cwmtq3s&dl=0

Trophies that display blocks or multiblocks show up fine.

### Your Proposal

Display the item in a plane orthogonal towards the player so that it is always visible.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
I just opened a PR to fix this. In the meantime, consider playing with "Fancy Graphics" if possible. The renderer is broken with "Fast Graphics".

**Comment by AbdielKavash** [comment]
I can confirm that with fancy graphics the items use 3D models (one "pixel" thick) that remain in consistent orientation regardless of the position of the player. 👍
