### ISSUE TITLE
GT wrench can no longer dismantle some AE2 components.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15123]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Use shift + right-click with a GT wrench to instantly break an AE2 component.

### The Reality

Most components only disappear for a moment, and then reappear rather than being broken. To help narrow down the problem:
* The following components don't break: ME controller, crafting storage, co-processor, IO port, ME chest
* The following components break correctly: cables, various fixtures (buses, interfaces), fluid discretizer, energy cells

Notably shift-right click on a component with distinct sides (IO port, ME chest) ends up rotating the component, rather than dismantling it.

Non-GT wrenches (I have tested with the Yeta wrench and the AE2 certus wrench and network tool) still dismantle AE components properly.

### Your Proposal

Shift-clicking with a GT wrench should be equivalent to shift-clicking with any other wrench, and simply break the component clicked on.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
do you have a me security station ?

**Comment by AbdielKavash** [comment]
My system has a security station, with a blank biometric card giving all permissions to everyone. (I'm playing SP, the only one who could touch my system is Herobrine.)

Removing the station from the system does not fix the issue. In fact, I can simply place an isolated AE block on the ground not connected to anything, and I still can't break it with a GT wrench.
