### ISSUE TITLE
ServerUtilities is missing an in-game configuration option.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15128]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Configure ServerUtilities using Esc -> Mod Options.

### The Reality

The Config button is greyed out.

![](https://i.imgur.com/zmDrrnC.png)

### Your Proposal

This might be related to the SU configs being located in a strange place; instead of `.minecraft/config/serverutilities` the actual location of the config folder is `./minecraft/serverutilities`. I don't know if this is intended.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
> This might be related to the SU configs being located in a strange place; instead of .minecraft/config/serverutilities the actual location of the config folder is ./minecraft/serverutilities. I don't know if this is intended.

This is most likely not the reason. If there is an ingame config GUI depends on whether mods provide one or not. This doesn't happen automatically.

**Comment by AbdielKavash** [comment]
That does not allow customization of most of the options actually present in the config file.

(I was specifically looking for disabling automatic backups, as I use Aroma.)

**Comment by Lyfts** [comment]
Yeah it's client-only settings in the ingame menu atm. But I guess it wouldn't hurt to add the "server" settings to the mod config menu for sp purposes.
