### ISSUE TITLE
Elven Gateway Trophy displays incorrectly.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15127]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Display the Elven Gateway Trophy.

### The Reality

Only the pylons show up in the trophy model.

![](https://i.imgur.com/Ip0Cd11.png)

### Your Proposal

Display the entire model of the gateway.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment]
I know @GTNH-Colen has fixed this but there is no PR yet. Maybe he intends to do more fixes to the complex structure renderer, as this is not its only bug.
