### ISSUE TITLE
Revision Needed: Thaumometric Essentia Cell's Quest Text

### ISSUE THREAD

**Issue by LeoGuys1** [GTNewHorizons/GT-New-Horizons-Modpack#15137]
### Your GTNH Discord Username

LeoGuys

### Your Pack Version

2.5.0

### Your Proposal

Let's jazz up the Thaumometric Essentia Cell with a new description that captures its infinite potential. How about something that pokes fun at the never-ending supply?

### Your Goal

The aim here is to inject a bit of humor into our thaumaturgical grind. We're not just crafting; we're conjuring with style and a smirk. This change will not only reflect the boundless nature of the cell but also bring a smile to our fellow mages.

### Your Vision

Imagine a description that goes. Photo
This playful take will surely get a chuckle and make the quest even more memorable.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76493533/2b6876af-664a-4d0b-9d67-1c49ed5a42b9)

`Behold the §5Thaumometric Essentia Cell§f, your unlimited magic §3credit card§f. Feeling a little low on §aessentia§f? With this §bbaby§f, you'll be rolling in it like a §5wizard§f in a §3potion shop§f! Try to run this §cwell dry§f — dare ya, it's like trying to spend §eBill Gates'§f fortune in a §fdollar store§f!`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by MCTBL** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/30978504/3fcce565-bcea-4d92-9df9-8bab9547b98b)
will, white may doesn't seem very suitable.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/30978504/0d6a866e-2396-4372-aad2-ee82c364a2d4)
I think this may better?
