### ISSUE TITLE
UI and Translation Correction for Circuit Programmer

### ISSUE THREAD

**Issue by LeoGuys1** [GTNewHorizons/GT-New-Horizons-Modpack#15139]
### Your GTNH Discord Username

LeoGuys

### Your Pack Version

2.5.0

### Your Proposal

There's an issue with the "Circuit Programmer" device UI: an incorrect translation into Russian and a missing English version. Corrections are proposed
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76493533/45f90f83-420a-4d54-a18a-b7503241d7f4)

### Your Goal

To correct the name to "Программатор" in the Russian version and to add an English translation to make the device user-friendly and accessible to all players

### Your Vision

An accurate translation and a complete interface in both languages will enhance user interaction with the device, prevent confusion, and make the process of programming circuits more intuitive

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment]
Issue with your resource pack.
![2023-12-19_11 27 14](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40035906/b920567d-033e-4d82-a811-5a134a826ed5)
