### ISSUE TITLE
Complexifying Crafting and Updating Quest Line of Crafting Co-Processing Unit

### ISSUE THREAD

**Issue by LeoGuys1** [GTNewHorizons/GT-New-Horizons-Modpack#15136]
### Your GTNH Discord Username

LeoGuys

### Your Pack Version

2.5.0

### Your Proposal

I propose to make the crafting process more complex for all versions of Crafting Co-Processing Unit (1, 2, 16, 64, 256, 1024, 4096) by introducing sequential crafting and increasing its difficulty

### Your Goal

This change is aimed at aligning the crafting process with the overall complexity of the assembly, thus raising the level of challenge and interest for the player

### Your Vision

Complexifying the crafting process for versions (1, 2, 16, 64, 256, 1024, 4096) will deepen game immersion and ensure a more balanced and consistent development progression. Additionally, it is proposed to include versions "64, 256, 1024, 4096" in the quest line, as they are currently missing, while earlier versions are already included

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
I mean fair enough, but this is all pretty vague. what's the proposal?
