### ISSUE TITLE
Trophies are very hard on fps

### ISSUE THREAD

**Issue by LeoGuys1** [GTNewHorizons/GT-New-Horizons-Modpack#15134]
### Your GTNH Discord Username

LeoGuys

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Other versions in between

### Type of Server

Don't know

### Your Expectation

I expected my fps to be :D

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76493533/fa774d93-f3f3-42a5-8299-f33f5ee1978b)
Dyson Swarm Trophy
Dimensionally Transccendent Plasma Forge Trophy

### Your Proposal

It is possible to simplify the animation of the trophy by reducing the details or the number of frames. Maybe lower the animation refresh rate or disable it altogether on some more that have a lot of animations

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
I mean I'm not really sure what you were expecting, that is the most complex trophy out of all of them. Each one has 6k blocks being rendered and you've placed 24 down, you're meant to have 1.

**Comment by LeoGuys1** [comment]
@Connor-Colenso 
This was a very crude example of its use

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76493533/0a86a8a5-5c3d-4143-a4e5-77d19651ae91)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76493533/34c9f08a-6e97-4047-b487-92973ee529d3)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/76493533/1b7a5e8f-ad5b-4714-ab88-e7945f3e2dd9)

**Comment by Connor-Colenso** [comment]
The substantial TPS drop from holding it is worth looking into. But I am limited on what I can do on this topic, there are already substantial optimisations going on inside of the renderer. I will take a look.

**Comment by LeoGuys1** [comment]
@Connor-Colenso It's okay, my job was to tell you, and you're already deciding there yourself

**Comment by boubou19** [comment]
fixed with latest version of the mod
