### ISSUE TITLE
ME patterns using reusable GT tools no longer calculate correctly.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15149]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Encode an ME crafting pattern using a reusable GT tool, such as a wrench. Turn substitutions on.

![](https://i.imgur.com/e5ivCZx.png)

Have a wrench in the ME system.

Request a craft of a number of items using this pattern.

### The Reality

This is the crafting plan for 100 frames using a pattern that was encoded before 2.5.0:

![](https://i.imgur.com/XxwQ5zK.png)

I have encoded an identical pattern in 2.5.0, this is the crafting plan when I request it:

![](https://i.imgur.com/W4OKumf.png)

It seems that for the new patterns, ME expects a new tool for every repeat of the craft, and is not able to reuse the same tool.

### Your Proposal

Restore pre-2.5.0 functionality, when the same tool can be used repeatedly to craft multiple runs of the same pattern.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment]
Problem seems to not exist on nightly 270 (despite seemingly no related fixes.
![image-44](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86674724/b0c4acca-80df-443d-a275-5fd092bcba24)

**Comment by vovaksenov** [comment]
Nevermind, it does indeed occur. The workaround is to replace the default NEI instruments with an actual one as was done up there.
![image-47](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86674724/52fd3115-92af-49c3-bdc1-018532df54d1)

**Comment by S4mpsa** [comment]
Honestly this is a blessing in a disguise, the player should really be incentivized to use the new single-use tools added in 2.5.0 as that is a thousand times better for AE2 performance.

**Comment by boubou19** [comment]
The issue is that the tool pulled from NEI when shiftclicking the recipe is not the one you'll use, so even with the substitution enabled, it does not work.
