### ISSUE TITLE
Client Crashes on opening certain quest tabs

### ISSUE THREAD

**Issue by K12akinskulz** [GTNewHorizons/GT-New-Horizons-Modpack#15156]
### Your GTNH Discord Username

K12akinskulz

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

Opening HV and BEE Breeding quest tabs

### Crash Report

[crash-2023-12-19_20.47.37-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13721975/crash-2023-12-19_20.47.37-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by erwinvc** [comment]
Can confirm, my client crashes when I open the search menu of the quest book. Crash report:
[crash-2023-12-20_13.57.08-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13727602/crash-2023-12-20_13.57.08-client.txt)

**Comment by boubou19** [comment]
@erwinvc @K12akinskulz what was your download source for the pack?

**Comment by K12akinskulz** [comment]
I followed the link from Technic launcher, and i downloaded the 2.5.0 java 8 edition

**Comment by K12akinskulz** [comment]
Rn, the tabs that are crashing are <Bee Breeding> <Hv> and multiple tiers above it, the coin shop, and building better homes.

**Comment by erwinvc** [comment]
@boubou19 "MMC archive for Java 17-21" in the announcements channel on Discord.

**Comment by boubou19** [comment]
> I followed the link from Technic launcher, and i downloaded the 2.5.0 java 8 edition @boubou19

When you say this @K12akinskulz you just clicked on the 2.5.0 version when you reinstalled the pack or did you manually tweaked your instance?

**Comment by boubou19** [comment]
> @boubou19 "MMC archive for Java 17-21" in the announcements channel on Discord.

@erwinvc did you directly imported the zip or did you manually updated mods and config folder?

**Comment by erwinvc** [comment]
Manually updated as instructed on the wiki: https://gtnh.miraheze.org/wiki/Installing_and_Migrating.
(deleted mods & config folder and then dropped the new files in)

**Comment by boubou19** [comment]
can you try making a new instance by importing the zip directly to see if it's a migration issue or a pack issue?

**Comment by K12akinskulz** [comment]
@boubou19 I completely uploaded the new file except for documents for player and world data

**Comment by erwinvc** [comment]
Making a new instance solves the issue for me!

**Comment by boubou19** [comment]
So it looks like it's a migration issue, so @K12akinskulz do a backup of your data then do a full reinstallation of the pack. It should solve the issue. I'm closing this.

**Comment by erwinvc** [comment]
For future reference, the issue wasn't my client but it was the server. Resetting the config folder fixed the issue.
