### ISSUE TITLE
Add missing EoH Recipies/Resources

### ISSUE THREAD

**Issue by Speecker** [GTNewHorizons/GT-New-Horizons-Modpack#15153]
### Your GTNH Discord Username

speecker

### Your Pack Version

2.4.0/2.5.0

### Your Proposal

EoH is missing a recipe for Ross128b and Ross128ba and is missing some resources from the deep dark like Tritanium Dust.

### Your Goal

Replace/make VMs obsolete in the DD and on Ross128b/Ross128ba for the BartWorks and other Ores that can only be obtained there.

### Your Vision

Add a recipe for Ross128b/Ross128ba. Add Tritanium Dust as output to the DD EoH Recipe.
Probably add other missing Resources i may have missed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

Edit #1: T9: Horus does have a EoH Recipe but has no crafting recipe for its "catalyst" item. T9: Mehen Belt is missin both (not even shown in NEI Ore Tab).

**Comment by Speecker** [comment]
. ?

**Comment by chochem** [comment]
Tritanium looks fine and like it always was fine. Horus and mehen belt were fixed.
bw/gt++ ores could be added but that will probably not happen until after the material system overhaul.

**Comment by chochem** [comment]
indeed tritanium works in 2.7.0 https://discord.com/channels/181078474394566657/401118216228831252/1316472861363277824
