### ISSUE TITLE
IV Transformer don't give 4A energy output and limits to 1A

### ISSUE THREAD

**Issue by NyrZ** [GTNewHorizons/GT-New-Horizons-Modpack#15157]
### Your GTNH Discord Username

nyrz

### Your Pack Version

2.5.0

### Your Server

Locally hosted on computer

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

My Large Gas Turbine setup consists of 4 HSS-E Turbines running with Benzene producing each 7956 EU/t. I transform those 4A EV up to 1A IV using an Extreme Transformer (EV one) in step up mode and run it through a 1x Vanadium-Gallium cable (LuV) which then gets transformed back down to IV into my IV battery buffer filled with 16 Lapotronic Energy Orbs. I should be getting an input of around 32824 EU/t into the buffer.

### The Reality

In reality my battery buffer only receives 8192 EU/t.
<img width="1103" alt="Screenshot_1" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50527996/77946339-f78d-4643-87a1-b0c7b6dde268">
The only way to fix it I found was to either swap my IV Transformer to its Hi-Amp version OR keeping the IV Transform feeding my battery buffer BUT swapping all my EV Transformers to IV in step up mode.

4 EV Transformers step up mode + 1 IV Hi-Amp Transformer step down mode :
<img width="1157" alt="Screenshot_2" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50527996/9f7c7944-d461-471f-bd1b-443720b6370b">

4 IV Transformers step up mode + 1 IV Transformer step down mode :
<img width="1194" alt="Screenshot_3" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50527996/1a7a6d67-6960-452d-a48b-da8303b752d1">

Proof that the battery buffer is filled with 16 Lapotronic Energy Orbs :
<img width="660" alt="Screenshot_6" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50527996/304dee25-1489-4a54-9286-96c54e91af53">

GT Scanner on the cable connecting to the step down transformer with each setup all give around 32744 :

- IV Transformer
<img width="1903" alt="Screenshot_5" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50527996/3c047214-b0d5-482b-ae6d-6dc5138a96ce">
- Hi-Amp IV Transformer
<img width="1886" alt="Screenshot_7" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50527996/76579847-d6f4-4cbc-a413-1ee81dcce1aa">
- 5 IV Transformers total
<img width="1741" alt="Screenshot_4" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50527996/cfbc0146-ecb1-4487-b73d-24ebc45736a8">

I reproduced the bug using a Debug Power Generator and find the same result :

- Debug Power Generator settings (simulating a turbine)
<img width="623" alt="Screenshot_8" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50527996/02348e67-4743-42b9-9a7d-b8f8a1f92558">

- I use 2 of them to simulate 2 turbines which should result in around 15912 EU/t but I only get 8192 EU/t input if I use an IV Transformer
<img width="1252" alt="Screenshot_9" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50527996/d3ab222b-c7ec-40b9-815b-280d589bf028">

- Swapping the IV Transformer to Hi-Amp IV gets me back to the normal input amount
<img width="1187" alt="Screenshot_10" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/50527996/088a5666-e7b5-40eb-b477-007de9696a3c">

### Your Proposal

Fix IV Transformer throughput back to 4A IV instead of limited to 1A for a weird reason I don't understand

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
no bug here as far as I can see. just because you use a LuV cable doesnt make the voltage LuV magically.

**Comment by boubou19** [comment]
you produce 4A IV but use an insane transformer that takes in 1A up to LuV and outputs 4 A IV. feeding more amps will do nothing. Just plug the EV transformers in step up mode to the IV battbuffer directly. Btw you should ask this in #help on our discord channel, this is not a bug at all.

**Comment by NyrZ** [comment]
> Btw you should ask this in #help on our discord channel, this is not a bug at all

Hi, I did ask multiple times on discord #help channel and people weren’t able to help me. Even stargate player were saying they didn’t understand so I made the issue thinking it was a bug. Sorry.
