### ISSUE TITLE
Stocking input hatch does not work with regular and mega oil cracker

### ISSUE THREAD

**Issue by NotAPenguin0** [GTNewHorizons/GT-New-Horizons-Modpack#15155]
### Your GTNH Discord Username

notpenguin

### Your Pack Version

2.5.0

### Your Server

Private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Stocking input hatch works with mega oil cracker, given the hatches are still in the correct locations.

### The Reality

The controller shows no valid recipe is found

### Your Proposal

Make stocking hatch work with mega oil cracker.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Chococar-NSW** [comment]
2.5.1 it's same
Can formed with stocking input hatch
but can't work

**Comment by GTNH-Afx237v7** [comment]
Can confirm on 2.5.1. that the stocking input hatches also do not work on the regular oil cracking units... :(

**Comment by RitumsC** [comment]
Still a problem in 2.6.0-beta1
https://discord.com/channels/181078474394566657/234936569360809996/1227560314082426921
