### ISSUE TITLE
Crafting input buffer is not displayed in the me interface terminal

### ISSUE THREAD

**Issue by homullily** [GTNewHorizons/GT-New-Horizons-Modpack#15161]
### Your GTNH Discord Username

homuhomu#9810

### Your Pack Version

2.5.0 (appliedenergistics2-rv3-beta-303-GTNH)

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Crafting input buffer should be displayed in the me interface terminal

### The Reality

Crafting input buffer is not displayed in the me interface terminal.
![1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95575223/08678773-605a-4aa3-a828-9092218a5045)
![2](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95575223/bab35eaa-71bf-4f07-b1ae-6603cd37f9f8)
![3](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95575223/a29e5efc-b325-4b9b-ae71-6e7694573a76)

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
did it work before or is it a suggestion?

**Comment by homullily** [comment]
> did it work before or is it a suggestion?

In version 291 ae, it will display Crafting input buffer
