### ISSUE TITLE
Stocking Input Hatch bugs Chemplant

### ISSUE THREAD

**Issue by ChaosFiller** [GTNewHorizons/GT-New-Horizons-Modpack#15162]
### Your GTNH Discord Username

chaos_filler

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Expected that the Chemplant would recognize the new Stocking Input Hatch.

### The Reality

When a Stocking Input Hatch is added to a Chemplant, the Chemplant will no longer form. The Chemplant will refuse to form even if the Stocking Input Hatch is replaced with a normal Input Hatch. This can only be fixed by breaking the Chemplant controller.
Normal Input Hatch:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95202140/9ca30b4c-882c-408f-9c24-90540dbe4f5b)
Replaced with Stocking Input Hatch:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95202140/e359eb6f-7290-41ab-8322-9463b793264c)
Replaced again with a Normal Input Hatch:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95202140/ea04afc3-9bff-4293-a664-d29e378d0d36)

### Your Proposal

Chemplant should behave as normal if the Stocking Input Hatch is removed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
are you sure its not just a tier issue?

**Comment by ChaosFiller** [comment]
Do chemplants require a certain tier to be able to use the stocking input hatch? But regardless of that, placing the stocking input hatch prevents the multi from ever forming again (unless it is broken and placed back down), even if the stocking input hatch is removed and replaced with a normal HV input hatch.
