### ISSUE TITLE
Wireless charger does not charge items in battlegear slots

### ISSUE THREAD

**Issue by NotAPenguin0** [GTNewHorizons/GT-New-Horizons-Modpack#15177]
### Your GTNH Discord Username

notapenguin

### Your Pack Version

2.5.0

### Your Proposal

Wireless charger should charge items in battlegear slots.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/26485755/17adb9e0-6443-4804-abc3-80ea8169203e)

### Your Goal

They charge armor and items in your inventory, I see no reason why battlegear slots should be excluded.

### Your Vision

It's really inconvenient to have to take out your chargeable weapons every now and then to charge them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Battle gear slots avoid many things that things in inventory do but maybe someone could figure out how to mod battle gear to be more like inventory
