### ISSUE TITLE
I updated GTNH on Curseforge to 2.5.1

### ISSUE THREAD

**Issue by LosuTheGregic** [GTNewHorizons/GT-New-Horizons-Modpack#15187]
### Your GTNH Discord Username

losutheman

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

I updated from 2.4.0 to 2.5.1, and when I did, most mods got duplicated (I don't know if it did anything else).
After deleting the old versions of the duplicates, I tried launching the game, and it crashed on the loading screen with code -1.

I tried Prism and MMC, but they're just worse, so saying "don't use Curseforge" is not helpful.
Does someone know what could've happened?

### Crash Report

It's in Curseforge, so it doesn't show me the crash log, only the crash code (-1 in this case).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
Something drove deploader wild. Does curse allow you to "reinstall" or repair? Otherwise, you may want to look at the "migrate" section of https://wiki.gtnewhorizons.com/wiki/Installing_and_Migrating#Migrating_to_a_Different_Launcher and make a full and complete backup of your setup (the entire `.minecraft` folder) somewhere Curse can't touch it, and then remove/reinstall 2.5.1 fresh, and bring back your saved files. Or retry a Prism migration to get Java 21.

**Comment by LosuTheGregic** [comment]
> Something drove deploader wild. Does curse allow you to "reinstall" or repair? Otherwise, you may want to look at the "migrate" section of https://wiki.gtnewhorizons.com/wiki/Installing_and_Migrating#Migrating_to_a_Different_Launcher and make a full and complete backup of your setup (the entire `.minecraft` folder) somewhere Curse can't touch it, and then remove/reinstall 2.5.1 fresh, and bring back your saved files. Or retry a Prism migration to get Java 21.

I "repaired" the pack 3 times and I still have the same error.
Should I reinstall the pack?
(like, deleting it and then reinstall it on the new version from scratch)

**Comment by bombcar** [comment]
> Should I reinstall the pack?

Yes but you need 100% (1000%) to make sure you've backed up your saves and other folders as described on the link or you will lose your world, your map, or other things.

**Comment by LosuTheGregic** [comment]
> > Should I reinstall the pack?
> 
> Yes but you need 100% (1000%) to make sure you've backed up your saves and other folders as described on the link or you will lose your world, your map, or other things.

Thanks.
I'll grab the visualprospecting, journeymap, and saves folders then.
I didn't use anything else (although I'm planning on installing FTB Utilities), so...

**Comment by boubou19** [comment]
This is exactly why we say that curse is bad. a CF instance gets easily damaged by things the user aren't expecting to break the instance.

About mmc and prism, the java 8 zip archive can be imported directly without any other action required. For the java 17-21 version however, if prism supports it outside of the box just like the java 8 version, it's not the case on the mmc launcher. After importing the java 17-21 archive on mmc launcher, you need to add the required java parameters.

Those archives have been tested numerous times by me, so i guarantee they work.

**Comment by LosuTheGregic** [comment]
I reinstalled it.
It worked.
Thanks for the help.
