### ISSUE TITLE
Suggestion: Replace/sidegrade Mega-type Multiblocks 

### ISSUE THREAD

**Issue by divine-ray** [GTNewHorizons/GT-New-Horizons-Modpack#15183]
### Your GTNH Discord Username

divine_ray

### Your Pack Version

2.4.*

### Your Proposal

I personally feel that the mega versions of the EBF, distillery tower, etc. are big ugly cubes with little detail to them aside from enormous single-resource and space consumption. 
I’d like to suggest more varied upscaled versions of these MBs, in a similar vein of what Gregicailty Multiblocks (Addon to GTCEu on 1.12.2) did, in where they’re still larger but without unneeded massiveness. 

### Your Goal

Alternatives to the mega-multis offer variety and certainly are an improvement over plain huge cubes with little detail to them. 
(This does apply to many 3x3x3 multis though) 
The addition of more complex/involved multis before the late game of UV+ would prepare oneself to the oncoming increases in costs, as well. 

### Your Vision

The addition of more diverse large multis adds variety and doesn’t just end up shoving a MEBF into a big floor hole. 
Asides, the Mega-Versions’s I/O placements are simply ridiculous and dwarfed by a megaDT several dozen blocks high.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by divine-ray** [comment]
I might have reinvented the wheel as this seems to overlap with MuTEs as far as i gathered

**Comment by chochem** [comment]
Its in the works yea
