### ISSUE TITLE
When I use AE2FluidCraft-Rework, the search function for NotEnoughItems does not work.

### ISSUE THREAD

**Issue by LSK-LW** [GTNewHorizons/GT-New-Horizons-Modpack#15186]
### Your Pack Version

AE2FluidCraft-Rework 1.1.74-GTNH | NotEnoughItems 2.4.3-GTNH

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Searching for items works normally.

### The Reality

Unable to search for items.

### Your Proposal

Try fixing search issues.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by MCTBL** [comment]
could  you give some screenshots or information about this issue?

**Comment by LSK-LW** [comment]
> could you give some screenshots or information about this issue?

The search function does not work, or only some irrelevant items are found.

![20231226014026](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12579533/38cdfac0-f675-4340-b2a1-ddcc5845d928)
![20231226014052](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12579533/5d0e48e8-9c50-4b41-b5aa-b4e420ca1bfd)
![20231226014131](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12579533/9a8bd8ec-db9b-4a28-bd1f-1322af200cc0)

**Comment by MCTBL** [comment]
had you ever changed the lang file?
or you just create a new pack and only have these two mods?

**Comment by LSK-LW** [comment]
> had you ever changed the lang file? or you just create a new pack and only have these two mods?
I  just create a new pack and only have these mods:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12579533/979d43c5-efbf-407c-b50a-511e033d8caa)
