### ISSUE TITLE
T10 Deep Dark EoH item recipe change

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#15188]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.5.0

### Your Proposal

To change the stack of cobblestone from the recipe to 1 octuple commpressed coblestone, or 1 Raw Deep Dark Portal Block

### Your Goal

To make some equal cost to the most spammed EoH dim

### Your Vision

Creating a DD dim and minning it should cost one part of the creation of the portal, also to encourage the use of pararell in EoH and stop the spam of it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Hikari1nVoid** [comment]
The entrance cost has never been that dimblock.
