### ISSUE TITLE
Deleting a world doesn't delete associated data outside /save (Journeymap, NEI, visualprospecting, etc)

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#15190]
### Your GTNH Discord Username

bombcar

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Create a world.

Create another world.

Delete the first world. There should now be only one folder in /journeymap

### The Reality

The mapping data for the deleted world is not removed.

For large worlds, the map could be relatively large; it can also be confusing which one is right if you're trying to migrate.

This may also cause an issue eventually if you never name your worlds, because you get "New World" and then "New World 1" but if you then delete "New World" it may be confused about the map (not actually tested).

### Your Proposal

When a world is deleted, also delete it's journeyman folder (if exists) OR have journeyman move unknown world maps off to an obvious location.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FloatDoubling** [comment]
Same thing with 'TCNodeTracker', 'visualprospecting' and 'saves\NEI\local\*World name*' folders.
