### ISSUE TITLE
Black screen during quest popups after Thaumcraft headache effects

### ISSUE THREAD

**Issue by GrieverStormborn** [GTNewHorizons/GT-New-Horizons-Modpack#15193]
### Your GTNH Discord Username

Xarimna

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Questbook popups to not impact screen visibility

Steps to reproduce:
1. Trigger a Thaumcraft headache effect
2. After the effect finishes, complete any quest
Result: The screen, except for the GUI elements, remains black until the questbook notification(s) is complete

### The Reality

After the first Thaumcraft headache effect in a session, all future questbook popups make the screen black until the next full restart
    - GUI elements not impacted, see screenshot

A similar issue exists in #15063, but their bug impacts the entire session, and the holo lens were not equipped during the last occurrence. This issue occurs only during the questbook notification popups.

![2023-12-21_19 15 20](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/70297611/823bb5a8-7442-4074-8453-0b9873f54271)

### Your Proposal

Do not impact the rendering of the world during quest popups

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by norbby42** [comment]
I also just had this happen.  Java 17.0.9x64 here

**Comment by norbby42** [comment]
Nope, still got the full black screen, using BetterQuesting 3.5.1-GTNH.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/330db64c-7293-442b-91f4-5d078a37c65a).  On the plus side, the food meter isn't freaking out any more...

**Comment by sussybaka67** [comment]
Experiencing this bug, but I don't have a thaumcraft headache. Seems to be anytime that I complete a quest.

**Comment by Caedis** [comment]
Sounds in line with thaumcraft

**Comment by lao-pan** [comment]
The same thing happens to me when I'm completing some tasks. Sometimes when other members of my team finish their tasks, my screen goes black along with theirs, but sometimes it doesn't happen. It seems to be an occasional occurrence.

**Comment by chochem** [comment]
daily reports on discord
