### ISSUE TITLE
Soldering iron right click on GT++ multi not cycling redstone signal strength

### ISSUE THREAD

**Issue by NyrZ** [GTNewHorizons/GT-New-Horizons-Modpack#15191]
### Your GTNH Discord Username

nyrz

### Your Pack Version

2.5.0

### Your Proposal

Make right click with soldering iron change cover redstone signal strength on GT++ multis and shift right click to change voiding mode

### Your Goal

Be able to change cover redstone signal on GT++ multis AND voiding mode using soldering iron

### Your Vision

Same as goal

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pilad** [comment]
https://github.com/GTNewHorizons/GTplusplus/commit/4173fc97c7b753aaea396293869e7b798d38c242
