### ISSUE TITLE
Render Issues with Chiseled Glass

### ISSUE THREAD

**Issue by slyk26** [GTNewHorizons/GT-New-Horizons-Modpack#15200]
### Your GTNH Discord Username

slyk26

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

I made a wall of chiseled glass. That's it, i made one so i can see outside my base so i can view all the pretty infernal mobs.

### The Reality

On some chunks, there are render issues looking outside the base with most types of  chiseled glass.

I didn't have this issue on 2.4.0, i tested 2.5.0 as well where it happened too.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/102811034/feab724b-2024-4b62-b1f3-5dafc4b1f70b

### Your Proposal

fix render issue with chiseled glass

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Do you have Optifine loaded?

**Comment by slyk26** [comment]
> Do you have Optifine loaded?

no, forgot to say, tested with and without FTBLib + FTBUtils from [here](https://wiki.gtnewhorizons.com/wiki/Additional_Mods)
