### ISSUE TITLE
shift right click the new singularity essentia cell crashes zeta server.

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15207]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

251

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Actions

shift right click the new singularity essentia cell

and, if i rejoin server, it crashes again.
(btw i might need some help in zeta to get the bug item removed from my inventory)

### Crash Report

[crash-2023-12-23_02.54.13-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13758835/crash-2023-12-23_02.54.13-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Hikari1nVoid** [comment]
Can reproduce with a freshly cheated singularity cell in sp

**Comment by Hikari1nVoid** [comment]
[crash-2023-12-24_15.00.19-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13761109/crash-2023-12-24_15.00.19-client.txt)

**Comment by Hikari1nVoid** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24840795/49bd7ddb-0a30-4d35-b7d4-f319e3c89fea)
Can't crash server tho.But it will kill sp saves.

**Comment by Hikari1nVoid** [comment]
UPDATE:
We are not expected to disassemble a singularity cell into storage component...
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24840795/53033cb1-2829-4b3b-9a50-03ed2e514c8a)
