### ISSUE TITLE
V keybind crash in Tinkers Crafting station

### ISSUE THREAD

**Issue by fw4hre0xxq** [GTNewHorizons/GT-New-Horizons-Modpack#15206]
### Your GTNH Discord Username

hifunc

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Don't know and Single Player

### Your Actions

With the GUI for a Tinkers' Construct Crafting Station open, press the V key, if the V key is bound to something. This causes a crash. I tried this with the V key bound to Inventory, Nutrition GUI, and Battlegear Draw Weapons. All such bindings cause a crash. If the V key is unbound, this doesn't cause a crash.

I also noticed this crash doesn't happen if there is a vanilla chest next to the Crafting Station. I also want to mention that the pack I'm playing on has been modified with a build of EnderIO based on [this PR](https://github.com/GTNewHorizons/EnderIO/pull/144), and TrashSlot mod added ([this one specifically](https://www.curseforge.com/minecraft/mc-mods/trashslot/files/2267308)).

### Crash Report

[crash-2023-12-22_20.55.22-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13758046/crash-2023-12-22_20.55.22-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by TheUnderTaker11** [comment]
I just loaded up on Vanilla GTNH instance, went into a singleplayer world, spawned a crafting station, and the crash also immediately happened when I hit V in the station.
https://mclo.gs/R2PGTzv
