### ISSUE TITLE
NEI Shortcuts such as R and U don't work and missing recipes which actually exists

### ISSUE THREAD

**Issue by logic0412** [GTNewHorizons/GT-New-Horizons-Modpack#15203]
### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I upgraded my server and client from 2.3.4 to 2.5.1 and it supposed to show scripts while pressing R and U when mouse is on something.

### The Reality

It turned out that my R and U doesn't work while the settings are just as usual. 
Besides, loads of recipes are missing on both server and local games, but these recipes still can work in machines etc. They just don't show up in NEI.

### Your Proposal

Maybe it's caused by java version issue but while I was running 2.5.0 on java8 recently, the shortcut issue still exists, but my friend seems not having it.
Maybe I should be informed with a list of things to check?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
If you upgraded directly, did you clean out your /scripts/ folder? All native GTNH recipies have been migrated to code.

Can you try a fresh install of the client or single player world and see if that works correctly?

**Comment by logic0412** [comment]
YEAH I indeed use a fresh client installed with multimc and the scripts folder is totally clean. By the way, the recipes just don't show up in nei, they actually work in machines.

**Comment by logic0412** [comment]
I retried on java8 and installed a fresh client with HMCL, it still won't work, the problems are all the same.
