### ISSUE TITLE
Volcanus Parallel not working

### ISSUE THREAD

**Issue by Polybomber** [GTNewHorizons/GT-New-Horizons-Modpack#15210]
### Your GTNH Discord Username

Polybomber

### Your Pack Version

2.5.1

### Your Server

Personal LAN Server

### Java Version

Java 17

### Type of Server

Other MCPC+ fork

### Your Expectation

Volcanus parallel doesn't work properly. Instead recipe times seem to be multiplied. I'd expect that 8 Aluminum ingots would get smelted in 3.7s, not 3.7s * 8 seconds. I've included an image of a Volcanus smelting aluminum at 3.7s (running at IV power) and then the same Volcanus downgraded to an EBF doing it at 4.1s per aluminum ingot. 

The speed difference between the two would seem to be accounted for in the speed boost of the Volcanus over the EBF but is certainly not 8 times faster. This issue also seems to affect other ingots like Tungstensteel.

### The Reality

Volcanus parallel isn't working.

![Aluminium](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/53232010/2ee00429-da72-4dea-9c3b-c068b4c6f3c8)
![Aluminium EBF](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/53232010/da53e039-fa94-440e-a44c-d2a1a1913cf4)

### Your Proposal

Volcanus Parallel should work as intended and ingot crafting times suitably sped up.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
whats the recipe time, voltage, and heat? What the provided voltage and heat?

**Comment by Polybomber** [comment]
The recipe time is 65.75 seconds to craft one aluminum ingot from one aluminum dust at HV voltage using Kanthal coils and on circuit 1. The voltage was provided from an LSC with a 16A IV dynamo hatch connected by 8x Platinum cables, connected to a 4A IV diode, which in turn is connected to a 4x Platinum cable and then an IV energy hatch. The Volcanus/EBF coils are HSS-S.

**Comment by chochem** [comment]
seems all fine then. 8 parallels, speedbonus, no ocs. Coil upgrades don't help since no ocs

**Comment by Polybomber** [comment]
How are there 8 parallels though when the recipe time is effectively multiplied? Crafting 8 ingots takes 29.6 seconds vs crafting one ingot in an EBF takes 4.1 seconds?

**Comment by chochem** [comment]
Its not multiplied.

**Comment by Polybomber** [comment]
So the intent then is that a Volcanus can only craft 8 aluminum ingots in 29.6 seconds (using the above recipe and voltage) while an EBF can craft 8 aluminum ingots in 4.1 * 8 = 32.8 seconds? I'm not saying that's wrong, but I thought the whole point of parallel processing was that in the case of the Volcanus, it would process 8 ingots in less than the time it takes the EBF to do one ingot (due to the Volcanus's speed boost)?

**Comment by StaffiX** [comment]
480x8=3840 so above ev thus not being able to overclock 

Ebf can do two perfect ocs, which would be the equivalent of 16 parallels

But the 2.2x speed bonus of volcanus would make it slightly faster

If you would process 4 aluminium at a time, it would process it every 7.5 seconds

**Comment by Polybomber** [comment]
Ok that makes sense. Thanks for the explanation, all the dev. work, and sorry for the inconvenience. Happy holidays.
