### ISSUE TITLE
ME Dual Interface blocking mode no longer ignores circuits in machine.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15214]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Place an ME interface pointed directly at a singleblock machine. Toggle blocking mode of the interface on. Place a programmed circuit in the input slots of the machine. Request a craft using a pattern in this interface.

Previously, (pre-2.5.0), the blocking mode would ignore circuits in the machine's input, and push crafting ingredients regardless. This allows the player to use multiple circuits in the same machine, as long as one is careful about avoiding recipe overlaps.

### The Reality

As of 2.5.0-2.5.1, an interface in blocking mode will not insert ingredients into a machine, if the input inventory of the machine contains programmed circuits. Removing the circuits allows the interface to insert items again. Disabling blocking mode also allows the interface to insert items (although it makes dealing with recipe overlaps much harder).

### Your Proposal

Restore previous functionality: blocking mode should ignore programmed circuits (and lenses, extruder shapes, etc.)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by MCTBL** [comment]
Maybe virtual circuit can help you?

**Comment by Filiz1** [comment]
I have the same issue on 2.5.1 and this is serious issue that breaking the game. Please, fix it as soon as possible.

**Comment by Caedis** [comment]
Found the issuing code

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18713839/88ecaf58-8886-4709-b809-4f9f8c636a9b)


shouldCheckFluid is just looking at the target TE's name

**Comment by Caedis** [comment]
Changed in https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/250
