### ISSUE TITLE
AE2 block container cells not showing content name in description

### ISSUE THREAD

**Issue by AnrDaemon** [GTNewHorizons/GT-New-Horizons-Modpack#15212]
### Your GTNH Discord Username

AnrDaemon

### Your Pack Version

2.5.0

### Your Proposal

Since migration of ExtraCells' features to AE2 itself, some of the usability was lost.
Among it an ability to clearly see, which block container contains which block.

Surprisingly, AE2FC single-fluid containers show this information right away.

### Your Goal

This restores feature parity between ExC and AE2.

### Your Vision

This restores feature parity between ExC and AE2.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by MCTBL** [comment]
could you post some screenshots about this feature?

**Comment by Hikari1nVoid** [comment]
Sounds like an AE2 freature request.

**Comment by MCTBL** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/30978504/3f7765f8-97eb-45a6-8468-9107897fbbc0)
like this?

**Comment by MCTBL** [comment]
![D`(LHXZQ}0CBG KGAGGBK1P](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/54751df9-7141-4b70-baee-16b557f4438a)

![NA%X75AHL96 B@0_R9B{8O0](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/af17eb64-e8c7-4d7f-9aac-4745295e8d8e)

![V4V`2GW73YYIKA )B5IOX7Q](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/assets/30978504/eced104a-834f-4f47-bd7c-a98ed356bc2e)

And it won't show up if nothing in the cell.
