### ISSUE TITLE
Major ENet issues with two GTEU p2p tunnels connecting a pair of LSCs.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15216]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

I was trying to transfer power from one LSC to another using GTEU p2p. To make the transfer faster, I wired two GTEU p2p tunnels in parallel, each connected to a 64A IV dynamo/energy hatch.

In the picture below, the left LSC is the "input", the right is the "output". Both p2ps go *in the same direction*, from the input to the output, from left to right -- this is not a problem with a loop of some kind.

![](https://i.imgur.com/oEue8KQ.png)

### The Reality

It is honestly hard to say what exactly goes wrong, because I am encountering such a vast range of problems every time I break and replace something in the setup (LSC controllers, dynamo/energy hatches, p2p connection, energy source/sink...)

Sometimes the right LSC continues drawing power from the left one indefinitely, even though it is full and no power is being drained from it. Sometimes it reports negative values of EU input (see picture above). Sometimes it magicks up EU out of thin air, and even after breaking both of the p2p connections it is able to keep filling itself. Sometimes the *left* LSC keeps getting power from somewhere, even when I destroy its power source.

None of the issues happen with only one p2p connection between the two LSCs.

### Your Proposal

Investigate and fix. Could be an integer overflow somewhere? If I break everything and replace the LSCs with EV capacitors (with 300M EU storage), I couldn't replicate the issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I dont know. I rebuild the exact same setup and everything is working fine.

input on right looks correct:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/841bcfa7-d921-47bb-ab5a-ae97758b3a86)

when I shut off the power for left, it no longer gets power
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/fde8c535-4a37-4f56-a4e8-f7544a2e35d6)

after the one on the right is full nothing crazy happens either. the energy transfer slows down to a tiny trickle (to fill up whats lost from the passive LSC loss)

The only thing weird I could find is that sometimes the one on the right would then read small negative numbers for input (well small on average, it seems like an occasional 1tick burst) 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/e8b9fee0-f7b9-45b5-ae98-86c8908d60a8)
I dont know if those are real though or if the scanner is the issue, I have learned to not trust any EU/t scanners, only absolute EU numbers. And the overall EU numbers seem completely fine for both LSCs.
