### ISSUE TITLE
Advanced Assembly Line laser overclock with Multi Amper Energy Hatch

### ISSUE THREAD

**Issue by joutenchi** [GTNewHorizons/GT-New-Horizons-Modpack#15225]
### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

7x AAL with 16AUHV Energy Hatch begins a 7 input items UHV tier recipe

### The Reality

 AAL begins Laser Overclock

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Quaerere-Git** [comment]
Can confirm in 2.4.0
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/42565872/1ffad501-bf11-4225-abf2-ba9c08ce7a86)
A UMV 64A Energy Hatch is used to process this recipe. By normal it should cost 2,048,000,000 EU/t at 4 parallel, but in reality the EU/t cost is 2,201,600,000 = 512,000,000 * 4.3 which represents a laser overclock.
![2024-01-05_02 51 48](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/42565872/61a5d873-368b-4a43-a200-25edf4ce3fcb)

**Comment by StaffiX** [comment]
4 parallel + 2 normal overclock = 512 000 000 eu/t
umv 64a is 8 589 934 592 

with full parallel it would be 13*8000000*4*4 (1 664 000 000)
that's 5 times less power than the hatch can supply, so it can do 1 laser overclock, which multi amp still does, since it's not a regular energy hatch
