### ISSUE TITLE
LV muffler hatch recovers 5% while tooltip says 0%

### ISSUE THREAD

**Issue by CondoSlime** [GTNewHorizons/GT-New-Horizons-Modpack#15223]
### Your GTNH Discord Username

Condoslime

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I made roasted cobalt dust in an electric blast furnace. The blast furnace was made completely out of LV busses and hatches. I expected to get 1000L of sulfur dioxide and one pile of roasted cobalt dust.

### The Reality

I got 50L of sulfur dioxide instead.

### Your Proposal

Change the LV muffler hatch from 5% recovery to 0% or change the NEI tooltip from 0% to 5%
Also add in NEI that the sulfur dioxide gained from this EBF recipe is affected by the muffler hatch recovery (as well as other similar recipes)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
looks like the tooltip is correct: https://github.com/GTNewHorizons/GT5-Unofficial/pull/391
so bug is in the processing.
