### ISSUE TITLE
shadow under entities are cursed

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#15229]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.5.1

### Your Server

Delta

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

I expected to play normally.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12850933/39d84237-51be-4252-8903-7dee0ae9e2a1)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12850933/5fc37baf-14d1-4f57-a49a-d5b226e3b548)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12850933/9293cab3-ee96-48fd-8720-e2cb08468827)

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ALongStringOfNumbers** [comment]
I have seen a similar issue on a vanilla forge server with java 19. This was on version 2.4.0, as I have not updated yet.

**Comment by Tree-er233** [comment]
same issue on vanilla forge server with java 21 and java 8 , verison 2.4.0 to 2.5.1
