### ISSUE TITLE
Move NEI keybinds to main menu

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#15220]
### Your GTNH Discord Username

chochem

### Your Pack Version

2.5.1

### Your Proposal

Move all the keybinds from the NEI settings to the main keybind config menu.

### Your Goal

- make it actually possible to check for keybind conflicts
- make it easier for newer (and tbh many not so new) people that will otherwise assume there is no setting for these keybinds. This happens all the time.

### Your Vision

make NEI better.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment]
Where does NEI _store_ its key binds? because if they're not in options.txt this would move them there and make them more portable.

**Comment by chochem** [comment]
in the config/NEI folder. and yes thats a great extra point.

**Comment by bombcar** [comment]
It's quite likely NEI could keep them where they are and "virtually" make them appear.

I mean, if you were a mixinMaster it'd be possible.
