### ISSUE TITLE
MK4 Compact Fusion consumes more energy than it's minimum (or installed) hatch level can support

### ISSUE THREAD

**Issue by binaryalgorithm** [GTNewHorizons/GT-New-Horizons-Modpack#15230]
### Your GTNH Discord Username

binaryalgorithm

### Your Pack Version

2.5.0

### Your Server

private server

### Java Version

Java 19

### Type of Server

None

### Your Expectation

All recipes should work if 32 of the same energy hatch is installed (the min. in tooltip for MK4 is UHV, but I was using UIV).

### The Reality

Internal EU runs out and the recipe crashes. Note that it was similar behavior in 2.4.0, but didn't stop the machine from operating. I believe it was Duranium but there are a few recipes (not all) that "OC too much" and do this. Every recipe however runs properly in the MK5 Compact fusion for some reason with 32x UIV energy hatches; I only had issues in the MK4 compact.

### Your Proposal

Controller should check what OC level it can support (sustainably) based on the installed energy hatches.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
What's the eut of compact MK4 when it run duranium?

**Comment by noobyaran9** [comment]
I'm also seeing the same issue with MK4 compact fusion with 32 UHV energy hatch.
The recipe is taking 268,435,456 EU/t for Duranium which is more than enough EU/t than what the tooltip of MK4 compact fusion stated.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/6f757a5b-3ea7-4061-906b-d45d470ff63a)
MK4 compact fusion reactor supposed to be able to handle upto 33,554,432 * 32 EU/t = 1,073,741,824 EU/t of recipe.


Taking Duranium recipe:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/bb7d6019-6d16-423e-9108-b2c335c5c1bd)
16,384 * 256 * 64(OC 3 tier) = 268,435,456 EU/t which is way lower than what MK4 compact fusion can handle.

**Comment by binaryalgorithm** [comment]
Neon and Force plasma are the highest EU usage MK1 plasmas. They use 19A UMV in a MK5. Which means it should require 19A UIV in a MK4. The MK4 says "UHV hatches or better" and the MK5 is UEV hatches; however the minimum hatch in the tooltip is misleading in the sense that you can't run every recipe with those level of hatches, and the machine does not make adjustments for lower hatches vs. some recipes.

**Comment by noobyaran9** [comment]
From what I understand on fusion reactor logic, it doesn't matter what tier hatch you use, it should always respect this description.
And UHV hatch should be plenty enough to supply 33,554,432 EU/t for each of the hatch.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/36248e04-aa7a-48c0-a6d5-200ad71d2c8f)
