### ISSUE TITLE
Cannot set Needs Maintenance Cover to output strong signal with soldering iron

### ISSUE THREAD

**Issue by OperativeLoop** [GTNewHorizons/GT-New-Horizons-Modpack#15232]
### Your GTNH Discord Username

clearlydefectiv

### Your Pack Version

2.5.0 -2.5.1

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Used to be able to set Strong Redstone Signal with a soldering iron (and solder) so that a lamp or alarm could be triggered with redstone when maintenance is needed. Now the soldering iron only changes void mode. 

### The Reality

Soldering iron changes void mode instead of changing needs maintenance cover to output strong signal. This seems to work on some GT machines but not others, probably GT++ machines don't work. Confirmed not working on LPF and MB Mixer. 

### Your Proposal

Restore previous functionality or offer same functionality on a different tool. How else are early/mid game players supposed to monitor for maintenance issues? 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
Is it not working only for GT++ machines? If so then this is https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15191.

If it is also not working for something else, this should be investigated further.

**Comment by OperativeLoop** [comment]
Woops duplicate
