### ISSUE TITLE
Cleanroom Renderer

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#15234]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.5.0

### Your Proposal

There is no renderer in NEI for the cleanroom and would be nice to have one

### Your Goal

Getting a cleanroom NEI renderer

### Your Vision

Improving the look at multiblocks for all multis, just recognized this in the 2.5.0

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Lyfts** [comment]
Same problem as: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15110
Fixed in 2.5.1
