### ISSUE TITLE
UNKNOWN CRASH PLEASE HELP

### ISSUE THREAD

**Issue by Warsniper1918** [GTNewHorizons/GT-New-Horizons-Modpack#15243]
### Your GTNH Discord Username

Warsniper1999

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Shot at a ghast with a TC Longbow 

### Crash Report

[crash-2023-12-29_09.04.04-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13794452/crash-2023-12-29_09.04.04-server.txt)
[crash-2023-12-29_09.04.08-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13794454/crash-2023-12-29_09.04.08-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
that server log looks like corruption
