### ISSUE TITLE
Flowering Oak sapling turns into sacred oak sapling after a while

### ISSUE THREAD

**Issue by NAMER3334** [GTNewHorizons/GT-New-Horizons-Modpack#15244]
### Your GTNH Discord Username

N2Namer#8500

### Your Pack Version

2.5.0

### Your Server

private server

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

trying to place flowering oak sapling, expected flowering oak sapling to be placed, (I have optifine and worldedit as extra mods)

### The Reality

sometimes in personal dimension when a flowering oak sapling is placed it will eventually turn into a sacred oak sapling instead of growing, this may be a visual bug as when the "sacred oak" sapling is broken it drops the flowering oak sapling

### Your Proposal

remove the glitch i guess im not really sure

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Majora320** [comment]
I'm getting this same bug in 2.8.4 but with redwood saplings. This might be a general BOP sapling issue. Here's a video of it happening.

https://github.com/user-attachments/assets/0b541d0a-8592-4c2b-a73d-6b8304691fce

**Comment by dipo33** [comment]
I believe this issue is actually different from the one it was closed in favor of.
