### ISSUE TITLE
Advanced Blocking Card does not ignore Bio and Breakthrough Circuits.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15256]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Use a typical crafting subnet setup with an ME storage bus on the input bus of a multiblock.

Insert an Advanced Blocking Card to the receiving interface.

Make sure Default Blocking Mode (*ignore circuits, etc.*) is toggled on.

Place a programmed Bio Circuit or a Breakthrough Circuit into the input bus.

Request a craft through this subnet setup.

Per description of blocking mode, the circuits should be ignored, and items inserted into the input bus.

### The Reality

Blocking mode blocks indefinitely, until the programmed bio/breakthrough circuit is removed from the input bus.

### Your Proposal

Note that this is *not* a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15214, although both could possibly be fixed at the same time. With an interface directly pointed into a single-block machine, any programmed circuit causes the problem. With a subnet and storage bus setup, regular circuits are correctly ignored, only bio and breakthrough ones block.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
Can confirm this behaviour, it's currently messing up my ChemPlant automation... :(
