### ISSUE TITLE
GT++ Large Scale Auto-Assembler doesn't work with multi-ampere energy hatches

### ISSUE THREAD

**Issue by Valor760** [GTNewHorizons/GT-New-Horizons-Modpack#15251]
### Your GTNH Discord Username

valor760

### Your Pack Version

2.5.0 (2.6.0-Nightly too)

### Your Server

Private (SP tested too)

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Assembler works with multi-ampere energy hatches

### The Reality

Even though the structure is completed successfully and machine even sees, increases and fills the energy buffer, the tier of the machine stays at ULV.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31585840/abbda3ae-6a0a-44e6-a61b-d0f53fcb4729)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31585840/4e356ceb-c13e-4933-acde-a7b824026541)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31585840/5b13813a-40c9-41f6-b44b-2a87ff8a6a9d)

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
thats not a tectech machine nor does it say it would work

**Comment by Valor760** [comment]
@chochem - None of the machines say they support multi-ampere energy hatches. The other question is then why the structure successfully completes if this block is not supported?
