### ISSUE TITLE
ME Level Maintainer checks recipes in an unexpected order.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15253]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Use an ME Level Maintainer to continuously produce different items, as long as the ME network has recipes. To this end, I set the desired amounts to an impossibly large value.

I expected the level maintainer to poll the network in periodic intervals, and when the ingredients for one of the maintained items are available, start the craft.

### The Reality

The maintainer *technically* does what I described, but it does it in a *very interesting* way:

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/19243993/e97d81cc-8ecc-49d6-a2d8-679adef5cf3e

The first item is checked every other operation. The second item is checked every fourth operation. The third every eighth operation. Finally, the last item in the maintainer's GUI would only be checked once every 32 operations. This means that the rate at which the maintainer responds to demand depends on the order you define the items in the UI.

### Your Proposal

The maintainer should check all requested items with the same frequency; ideally in a round robin way.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Laiff** [comment]
This is a trade-off for tps spike when TLM trying to schedule all 5 configured items in the same tick. I think it can save last checked item and continue to iterate over starting from it on next tick.

**Comment by AbdielKavash** [comment]
I understand that you don't want to request everything at the same time every time. But the order of requests is currently:

1 - 2 - 1 - 2 - 3 - 1 - 2 - 1 - 2 - 3 - 4 - 1 - 2 - 1 - 2 - 3 - 1 - 2 - 1 - 2 - 3 - 4 - 5

I want the order to be instead:

1 - 2 - 3 - 4 - 5 - 1 - 2 - 3 - 4 - 5 - etc.

The frequency or simultaneity of orders etc. is not the issue here.
