### ISSUE TITLE
Blood Magic Arsenal: Blood Staff damages player instead of using network

### ISSUE THREAD

**Issue by Fibis-Ra** [GTNewHorizons/GT-New-Horizons-Modpack#15266]
### Your GTNH Discord Username

Fibis

### Your Pack Version

2.4.0

### Your Server

Private dedicated server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Crafted a Blood Wand Staff (two staffs with different caps), equipped in hotbar. It should sip from my blood network and recharge vis.
I already checked that staff is bound to me exactly, and my blood network contains millions of LP (should be enough to recharge)

### The Reality

Vis actually restored, but staff damages me instead of sipping blood network.

### Your Proposal

Make staff work as described in Thaumonomicon - sip blood from the network instead of harming player.
Investigation results from my side:
Blood staff ticks here - https://github.com/GTNewHorizons/BloodArsenal/blob/master/src/main/java/com/arc/bloodarsenal/common/thaumcraft/BloodWoodStaffUpdate.java 
Logic looks fine with assumption that "SoulNetworkHandler.syphonFromNetwork(itemstack, cost * deficit) > 0" could work wrongly. 
So, main concerns here - https://github.com/GTNewHorizons/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/api/soulNetwork/SoulNetworkHandler.java

Since I have no established environment to debug it myself - it would be great if anyone could look into it. 
Thanks!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Fibis-Ra** [comment]
Shortest reproduction steps: 
1. Create new Creative world
2. Get "Orb of Testing" and use it
3. Get "Divination Sigil" and check that there is plenty LP in your netword
4. Get "... Blood Wood Staff"
5. Switch gamemode to Adventure or Survival
6. Put staff in hotbar
7. Die (that's the issue)

**Comment by Fibis-Ra** [comment]
Actually, blood wand works fine. Blood staff doesn't. That's weird.

**Comment by Fibis-Ra** [comment]
And the reason is - staff has "player.attackEntityFrom(DamageSource.starve, 1F);" even if network has enough LP. Looks weird for me.

**Comment by AbdielKavash** [comment]
The Thaumonomicon entry for the staff core suggests that this is intended.

![](https://i.imgur.com/DqlLB0l.png)
