### ISSUE TITLE
Typing /help 9 crashes the game.

### ISSUE THREAD

**Issue by CondoSlime** [GTNewHorizons/GT-New-Horizons-Modpack#15264]
### Your GTNH Discord Username

Condoslime

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

I typed the command /help 9 in the chat. The game crashes immediately afterwards. This is the error that happened after the game booted me out.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10517450/615fd342-19b5-46db-b804-bdab36675574)

### Crash Report

[crash-2024-01-02_21.49.36-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13813855/crash-2024-01-02_21.49.36-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
it looks like some command is returning a null help text and that won't play well with anything.

**Comment by leumasme** [comment]
Can't reproduce - there seem to be 3 commands with missing usage text, but they're getting caught by HelpFixer. No crash, only a WARN in (integrated) server
```
[01:34:04] [Server thread/WARN]: [HelpFixer] Identified command with null usage, Ignoring: iguanaman.iguanatweakstconstruct.leveling.commands.IguanaCommandLevelUpTool
[01:34:04] [Server thread/WARN]: [HelpFixer] Identified command with null usage, Ignoring: iguanaman.iguanatweakstconstruct.leveling.commands.IguanaCommandToolXP
[01:34:04] [Server thread/WARN]: [HelpFixer] Identified command with null usage, Ignoring: info.inpureprojects.core.NEI.gtfoMicroblocks.Commands.CommandReload
```
(I didn't test with ServerUtilities installed, which you seem to have)

**Comment by Lyfts** [comment]
I can only reproduce this with Server Utilities installed. I'm guessing HelpFixer doesn't work with command override.

Same issue was reported here by another player using SU: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15145
