### ISSUE TITLE
The Mutator for the Alveary should have a clearly defined multiplier

### ISSUE THREAD

**Issue by garaiza-93** [GTNewHorizons/GT-New-Horizons-Modpack#15267]
### Your GTNH Discord Username

nowaaaay

### Your Pack Version

2.5.1

### Your Proposal

On behalf of @boubou19
> *the multiplier for the alveary mutator is unclear, and from the source code, there is a weird hidden cap not mentioned anywhere*

Clarify, in the code and questbook, what is the Mutator's multiplier. Additionally, remove/revisit the cap to the mutation multiplier.

### Your Goal

Note the source for the mutator: https://github.com/GTNewHorizons/Binnie/blob/master/src/main/java/binnie/extrabees/apiary/machine/mutator/MutatorModifierComponent.java#L16

This doesn't clearly state what the multiplier is. Looking at the definition for [getMutationMult](https://github.com/GTNewHorizons/Binnie/blob/master/src/main/java/binnie/extrabees/apiary/machine/mutator/AlvearyMutator.java#L19), it's determined by an item, but now that is unclear as well.

Additionally, there's a cap to the mutation multiplier that isn't mentioned in-game or anywhere else. It looks arbitrary.

### Your Vision

This would prevent players from being confused on how the mutator works.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by garaiza-93** [comment]
It's been shared in the Discord's help channel that the Mutator isn't reliable, and can even stop mutation completely. Could this have something to do with it?

**Comment by chochem** [comment]
that does not look unclear (outside of the cap). I guess the question is though if it is working correctly

**Comment by boubou19** [comment]
ic2 copper block below btw

**Comment by chochem** [comment]
>  it's determined by an item, but now that is unclear as well.

these are here https://github.com/GTNewHorizons/Binnie/blob/ef4dd3710ab140cf973f493216c3650007c93acd/src/main/java/binnie/extrabees/apiary/ModuleApiary.java#L36
