### ISSUE TITLE
Selecting void mode on EBF crashed with NPE

### ISSUE THREAD

**Issue by gromitinnam** [GTNewHorizons/GT-New-Horizons-Modpack#15263]
### Your GTNH Discord Username

Gromit it nam'

### Your Pack Version

2.4.0

### Your Server

i no use server

### Java Version

Java 8

### Type of Server

None

### Your Actions

I tried selecting the voiding option on EBF when itsaid no ouput space and I crash :( I was after or the void fluid option.

### Crash Report

https://mclo.gs/juYgUMx

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
Can you try on 2.5.1?

**Comment by chochem** [comment]
works fine on 2.5.1 and dev
