### ISSUE TITLE
Ruthenium Tetroxide solution does not work with input hatches

### ISSUE THREAD

**Issue by lor1113** [GTNewHorizons/GT-New-Horizons-Modpack#15273]
### Your GTNH Discord Username

Neuro

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Other versions in between

### Type of Server

Single Player

### Your Expectation

I tried to automatically input Ruthenium Tetroxide solution into an input hatch (of an oil cracker). I expected it to work

### The Reality

It simply does not work/enter. To be more specific, it is a little inconsistent. I first tried with EnderIO fluid conduits, which seemed to work sometimes, but otherwise not. I then tried with GT fluid pipes, which seem to not work at all.

NB that the oil cracker works fine. I can move the Ruthenium Tetroxide solution into the hatch manually and it all runs and works just fine. The problem is automatically inputting the fluid into the hatch, seemingly.

Note that my java version is java 21. I'm not sure why it's not listed as an option, as the GTNH wiki does say "Java 17-21"
(https://gtnh.miraheze.org/wiki/Installing_and_Migrating)

![2024-01-05_17 00 00](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/15572735/eb851997-0c4c-43a7-9c66-66e97079b8d8)
![2024-01-05_17 00 04](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/15572735/155d61b9-0595-4f11-9cea-52342387f49b)

I have asked on the discord a few times, nothing particularly helpful was said. Nobody seemed to try to replicate it. I have replicated it on a separate creative world, at least.

### Your Proposal

I propose that it works (the fluid inserts correctly into the input hatch, if it really needs to be spelled out).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AdolMors** [comment]
It is likely at some point the input hatch has been smacked with a GT hammer at some point. It toggles the auto-input status of the input hatch (default enabled), which if disabled would make input hatch accept no input from outside (using a pump cover on the hatch to import still works). You should try using GT hammer on the hatch to see if that is all it takes to fix the problem.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/cce745b6-3489-4b2e-87af-10a744cebf62)

**Comment by lor1113** [comment]
It's not that. Firstly when I logged back on today I rightclicked the input hatch and it said "auto input: disabled" (implying it was enabled before) and secondly when I hit it again to toggle back the behaviour, it still does not work.

![2024-01-06_12 47 47](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/15572735/79dfb3d0-025b-4c0d-9b57-5e7c458ba147)

I have already moved the hatch once (when I changed from trying to use a conduit to trying to use a pipe) and it didn't work either time, and it's unlikely I accidentally bonked it with a hammer twice (asides from the evidence above).

Two further details to note:

The input hatch is wallshared between a DT and a Oil Cracker. It's on the right side of the Oil Cracker which is shared with the left side of a DT. The entire setup does work with both sides processing normally (if I manually input the ruthenium tetroxide with cells) but I guess it could be causing some weird interactions.

Secondly, the act of the Oil Cracker turning on (ie; starting processing) seems to allow ruthenium tetroxide to enter normally. If I manually add in a single cell of the tetroxide, it doesn't immedially allow more to flow in, but then when the oil cracker starts processing, more flows in normally. I tried to get a video recording of this but it crashed, my laptop struggles already playing GTNH.

**Comment by GTNH-Afx237v7** [comment]
If you share a hatch between two different multis (with different recipe maps), the hatch may not allow input. Better to give each multi its own hatch.

**Comment by lor1113** [comment]
They do have their own input hatches, but they can both see each other's input hatch, due to how the wallsharing works.

It still really doesn't make sense. The oil cracker can also see the DT input hatch, which takes in Hot Ruthenium Tetroxide Solution, which is not a valid input for any oil cracker recipie but works nonetheless.

**Comment by lor1113** [comment]
I was able to fix the issue by moving the hatches around, and it does now work. Closing this because I doubt this behaviour is getting changed even if it is quite unintuitive (why can't they just take in any liquid? I can dump anything I want into an input bus)

Thanks for the help
