### ISSUE TITLE
Crash when open tinkers tool station / part builder

### ISSUE THREAD

**Issue by byulbaragi** [GTNewHorizons/GT-New-Horizons-Modpack#15272]
### Your GTNH Discord Username

Byulbaragi

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Crash when open GUI of Tool Station & Part Builder every time, so i can't continue game.
Regardless of where the block is located, the crash will occur.
I added just korean chat mod. 

### Crash Report

[crash-2024-01-05_18.42.21-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13840543/crash-2024-01-05_18.42.21-client.txt)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13840573/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by byulbaragi** [comment]
I solved problem. 
[Korean chat mod was the cause the crash, now i removed it - GUI opens well.
[b69_1710.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13840858/b69_1710.zip)

**Comment by Glease** [comment]
try disable bfe in its config if you want to keep the mod
