### ISSUE TITLE
Rework quest "Input chest for Ghetto ME System"

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#15274]
### Your GTNH Discord Username

Marcel|Chaoschaot234#7964

### Your Pack Version

2.6.0 nightly (latest)

### Your Proposal

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1703441/2eef0f6b-2449-41ce-9366-49e978830d5f)
As you can see in the screenshot above and also as reference here https://canary.discord.com/channels/181078474394566657/949447391587733504/1192886498186514543 you can see that the questbook tells something about "Extraction Pipes" but ProjectRed has no Extraction pipe so I suggest the following correction:

`To be able to put items into the Ghetto ME system you need just a few additional pipes.
The Routed Interface pipe should be connected to the chest you want to take items from.
Inside the Routed Interface pipe you need to put the Item Extractor chip and configure it to blacklist, if you want it to take all items from the chest.`

The 2nd paragraph looks fine :)

For the rewards I would remove the `Network Latency pipe`since it's not craftable and is nowhere described how to use it (maybe google knows more about it). This makes these 8 pipes somehow obsolet. A valid replacement could be just normal PR|Transportation pipes.

### Your Goal

With this change I want to get rid of the caused confusion speaking from a pipe which doesn't even exists in Project Red Transportation and to get rid of a somehow useless reward where nobody knows how to use it correctly.

### Your Vision

With this change I want to get rid of the caused confusion speaking from a pipe which doesn't even exists in Project Red Transportation and to get rid of a somehow useless reward where nobody knows how to use it correctly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
we can do a rework after the pipe recipe change i add is in the pack.
