### ISSUE TITLE
Game crashes when using Java17+

### ISSUE THREAD

**Issue by superDoubleXZ** [GTNewHorizons/GT-New-Horizons-Modpack#15270]
### Your GTNH Discord Username

superDXZ#0458

### Your Pack Version

GT_New_Horizons_2.5.1_Java_17-21

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Launch the game and it crashes, proxy used. Starting GT_New_Horizons_2.5.1_Java_17-21 with Java8 everything works fine. 

### Crash Report

Exception caught from launcher
java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:94)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:86)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Exiting with ERROR

full: https://paste.ubuntu.com/p/2TKPPrB6kK/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
Which launcher are you using?

**Comment by eigenraven** [comment]
`C:/Users/Administrator/AppData/Roaming/PrismLauncher/libraries/com/github/GTNewHorizons/lwjgl3ify/1.5.7/lwjgl3ify-1.5.7-forgePatches.jar (missing)` suggests prism launcher couldn't download a component of lwjgl3ify when setting up the pack (try <http://jenkins.usrv.eu:8081/nexus/content/groups/public/com/github/GTNewHorizons/lwjgl3ify/1.5.7/lwjgl3ify-1.5.7-forgePatches.jar> as that's what the launcher would try to download from)

**Comment by superDoubleXZ** [comment]
Problem solved, I think it was a proxy issue, HTTP ERROR 502 when using proxy to access http://jenkins.usrv.eu:8081/
