### ISSUE TITLE
IC2 Nightvision googles randomly dissapear

### ISSUE THREAD

**Issue by yanny7** [GTNewHorizons/GT-New-Horizons-Modpack#15271]
### Your GTNH Discord Username

Yanny7

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

After I take off my NanoSuit helmet, it does not dissapear

### The Reality

I got NanoSuit helmet from loot bag. Sometimes when I want to charge it, after I put it to inventory and then open LV battery buffer, helmet act as ghost item - when I take it, it dissapear. Also after restarting client item is no more there.

### Your Proposal

No dissapear of NanoSuit helmet after take off

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AdolMors** [comment]
Use of English notwithstanding, I cannot seem to follow the description to reproduce the issue.

Nanosuit helmet cannot be acquired from lootbag. The closest thing I can find is the IC2 nightvision goggles.

**Comment by yanny7** [comment]
I see, both helmets looks similar. Then they are IC2 Nightvision googles (sorry I reported it after loosing them, but it happened to me three times|

**Comment by yanny7** [comment]
Getting googles in creative doesn't cause this problem. I noticed that when I was googles that was often dissapearing, I can't shift-click to move them to armor slot and vice versa.
