### ISSUE TITLE
List of high-demand crafting recipes that have no assembler alternative

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15276]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.1

### Your Proposal

A list of items that are needed in large quantities in late- to end- game, but only have a crafting table recipe. Molecular Assemblers are slow and can not multiply patterns, which leads to long crafting plan calculations and crafting times. These recipes are slow to craft, difficult to parallelize, and likely worse for performance than running a machine that can do dozens of parallels at the same time. For all of the below items, a machine recipe with reasonably similar components should be added, likely to the assembler, or other machines where this is thematic. Similar recipes have been added for other components in the past, I intend to do a thorough job at adding anything else that is in demand.

- [x] Fusion coil block: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15174
- [x] YoTTank casings: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14590
- [x] AE2 Advanced Card, Pattern Capacity Card, Acceleration Card, Hyper-Acceleration Card: used to craft ME I/O hatches.
  - [x] Maybe other AE2 cards as well, as needed; or at least for consistency.
- [x] AE2 Blank Pattern
- [x] AE2FC fluid import/export bus
  - [x] Do a pass of other ME components to check.
  - [x] Possibly add a direct recipe for flat interfaces? Maybe using the same components as a block interface but different circuit?
- [x] All Pipe Casings
- [ ] Project Red Red Alloy Wire (possibly a wiremill recipe)

Please add more in the comments, I would really appreciate help primarily from endgame or gate players from their experience.

**Comment by AdolMors** [comment]
The red alloy wire has an interchangeable shapeless recipe between ProjectRed and GT 1x. How would this be handled?

I suppose I should also mention the 3 types of programmed circuits (normal, bio, breakthrough) can be made only from a shapeless recipe from LV, ULV and HV circuits respectively. Among those, only LV's programmed circuit has a shapeless recipe to return a LV circuit. These programmed circuits see uses from time to time in multis when there is no input bus to provide ghost circuit so a real programmed circuit needs to sit in the controller block.

**Comment by BigKeaner** [comment]
The solar panels: tiers lv-uv are only made in the dire crafting tables, considering how early the dire crafting table is available i think adding (maybe uhv tier) assembling recipes for the solar panels would be great. even after spamming dozens of dire autocrafting tables the recipes for them are super slow. the same can be said for digital singularities and infinity chests, which you need hundreds of thousands of to make a stargate

**Comment by EnderProyects** [comment]
I think that digital singularity and inf chest suits better in an assline alternate recipes ( using the metals such as infinity as fluids)

**Comment by BigKeaner** [comment]
> I think that digital singularity and inf chest suits better in an assline alternate recipes ( using the metals such as infinity as fluids)

The only problem with that is that you'll still be tick limited in creating them, so one aal will only ever be as good as 10 dire crafting table, and you'll still need to spam dozens more aals in order to make gate. I think a space assembler recipe could be good for getting around this tho.

**Comment by dgealow** [comment]
> The red alloy wire has an interchangeable shapeless recipe between ProjectRed and GT 1x. How would this be handled?

I'd say just do red alloy ingot in wiremill on circuit 24 -> PR red alloy wire

**Comment by serenibyss** [comment]
Since this issue is mostly resolved, closing in favor of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17890, which has the remaining point
