### ISSUE TITLE
Mixin apply for mod hodgepodge failed cause GTNH nightly cannot start

### ISSUE THREAD

**Issue by Chococar-NSW** [GTNewHorizons/GT-New-Horizons-Modpack#15279]
### Your GTNH Discord Username

chococar

### Your Pack Version

2.6.0-nightly-2024-01-06

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

Load the modpack then start, can't open the game

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13850586/fml-client-latest.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13850587/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Chococar-NSW** [comment]
Same as the Java 8 version
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/79390577/2eaee4cf-2b83-48aa-812c-ba00ad526441)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13850590/fml-client-latest.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13850591/latest.log)

**Comment by Dream-Master** [comment]
ik use hodgepodge 2.4.6
https://github.com/GTNewHorizons/Hodgepodge/releases/tag/2.4.6

**Comment by Chococar-NSW** [comment]
bruh enderpearl
2.4.6 it's normal
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/79390577/b5b629eb-79cf-4cee-a327-988469e581bf)
thanks

**Comment by Dream-Master** [comment]
will make a new nightly asap

**Comment by Dream-Master** [comment]
@Chococar-NSW did you join a game?

**Comment by Chococar-NSW** [comment]
@Dream-Master Yes I did
