### ISSUE TITLE
Some of Avarita gear became Universium like

### ISSUE THREAD

**Issue by Chococar-NSW** [GTNewHorizons/GT-New-Horizons-Modpack#15280]
### Your GTNH Discord Username

chococar

### Your Pack Version

2.6.0-nightly-2024-01-06

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

look like normal version

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/79390577/8f107197-0de4-49de-a015-049b6be1e7ed)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/79390577/dbc6ff97-377e-45a8-b313-b552f42a4081)

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by UltraHex** [comment]
Caused by GTNewHorizons/Avaritia#37. My bad.
