### ISSUE TITLE
ASFU Mod Preventing joining to private server 

### ISSUE THREAD

**Issue by chaosblade201** [GTNewHorizons/GT-New-Horizons-Modpack#15282]
### Your GTNH Discord Username

chaosblade_.

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

i have downloaded a brand new server from the gtnh website 2.5.1 accepted the Eula but when i go to join it using the 2.5.1 client also downloaded from the website i should be able to join the server however i cannot as when i join i get the following message 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/115968394/d0332899-1617-4641-bd9d-c5996c968ff1)
 when looking the client vs server i noticed  the following in the client 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/115968394/4ba25d5f-cf46-4992-bfc6-addfdc57ae77)
but not the server
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/115968394/5de70b1f-5795-4267-90bc-d9ac0fb12edb)

### The Reality

i was rejected from accessing the server due to the mod lists differences

### Your Proposal

resolve mod list differences between client and server versions

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
What is ASFU?

**Comment by chaosblade201** [comment]
i looked and it is An addon to IC2 that adds a tier five energy storage unit. as seen below https://github.com/GTNewHorizons/AFSU

**Comment by chaosblade201** [comment]
accidental disabling of mod with prism launcher apologies for any confusion caused
