### ISSUE TITLE
Cryogenic Freezer shouldn't form with TT energy hatches 

### ISSUE THREAD

**Issue by player5** [GTNewHorizons/GT-New-Horizons-Modpack#15284]
### Your GTNH Discord Username

Belius#9686

### Your Pack Version

2.5.1

### Your Server

Private ultramine

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Trying to cool Naqadah alloy ingot in Cryogenic Freezer.

### The Reality

Cryogenic Freezer running fine in waila. Have input bus ae and 4a luv energy hatch. When hot ingot in bus machine, controller write: not enough energy need * iv tier. When add 1 2A  luv energy hatch and connect to power - crafting starts normal

### Your Proposal

Add support for multiamps hatches or machine go to incomplite structure

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
GT++ Multis don’t work with multi-amp or laser hatches.

**Comment by AbdielKavash** [comment]
IMHO, multis should either be able to form and also be able to draw power from advanced hatches, or not be able to form with them at all. There are some multis that will form with an advanced hatch, but then inevitably powerfail because they can't draw power from it.
