### ISSUE TITLE
Dense Obsidian Plate Recipe Missing Circuit Number

### ISSUE THREAD

**Issue by ProphecyOak** [GTNewHorizons/GT-New-Horizons-Modpack#15289]
### Your GTNH Discord Username

prophecyoak

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Put 9 obsidian plates in a bending machine and expected a dense obsidian plate.

### The Reality

nothing. Setting it to circuit 1 just made obsidian foil. Trying setting 9 made it work.

### Your Proposal

It should note that you need circuit 9 to to make it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by StaffiX** [comment]
The version of your pack is really old, you should update

**Comment by chochem** [comment]
both dense obsidian plate recipes have a circuit on 2.5.x
