### ISSUE TITLE
Electrolyzer Multiblock

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#15285]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.5.1

### Your Proposal

The electrolyzer multiblock is capped at IV although all other multiblocks got a downtier a good time ago to EV
I would suggest to change the electrolyzer too to EV, wouldn't know why it shouldn't maybe there are some things against it but I wanted to suggest it at least

### Your Goal

Make all oreproc multis EV instead all except the electrolyzer one

### Your Vision

Make the tiering of the multis a bit more consistent

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
was not an oversight, electrolyzer is not oreproc :P

**Comment by MaGeBZz** [comment]
@chochem it isn't? I would consider macerator, ore washing plant, centrifuge, electrolyzer, thermal refinery as ore proc multis iirc
