### ISSUE TITLE
EMN Backpack slot voids backpacks

### ISSUE THREAD

**Issue by buildcraftenjoyer** [GTNewHorizons/GT-New-Horizons-Modpack#15281]
### Your GTNH Discord Username

joe_shmoe999#8931

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

I put a backpack from my inventory into my backpack slot. After closing the backpack slot GUI I should be able to open my backpack.

### The Reality

The backpack is gone. The backpack hotkey does nothing, and reopening the backpack slot GUI show I'm not wearing any backpack. Its also not in my inventory or dropped anywhere.

My laptop died while playing and I loaded my most recent backup and got into this state. The backpack I had equipped is gone, and any new backpacks I equip get eaten. Not sure how to reproduce this but I can sent a zip of my save if that helps. The issue persists after restarting, re-restoring backup etc.

### Your Proposal

Equipped backpacks shouldn't disappear.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
Can you start up the game load he world and sacrifice a backpack and then upload fml-latest.log?

**Comment by buildcraftenjoyer** [comment]
Here's fml-client-latest.log
https://www.dropbox.com/scl/fi/akixzpd97ul6xrcsp174r/fml-client-latest.log?rlkey=wjdjjmmkhexqrzddn9hhpcnay&dl=0

The file size is 35mb which is apparently too big for github comments so I put it on dropbox.
