### ISSUE TITLE
EnderIO 2.6.2 and EnderCore 0.2.19 Crash by themselves

### ISSUE THREAD

**Issue by ranger135xp** [GTNewHorizons/GT-New-Horizons-Modpack#15294]
### Your GTNH Discord Username

Ranger135xp

### Your Pack Version

N/A

### Your Server

Private

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Just make a pack with only these 2 mods, it crashes with the same error whether in a larger pack or solo.

### Crash Report

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13856094/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
It wants itemtravelstaff but can’t find it. Maybe a mod-dependent item isn’t wrapped properly.

**Comment by chochem** [comment]
you just missing stuff it depends on. no surprise whatsoever that it crashes.
show what happens in full pack or in a proper dev env with dependencies.

**Comment by boubou19** [comment]
it should display that it lacks them explicitely tho, crash makes little sense for people who don't underdstand crash reports

**Comment by bombcar** [comment]
I can add "required-after" for cofh-lib, which gives a reasonable error.

**Comment by ranger135xp** [comment]
Sorry, it was late and I was getting pretty exhausted.
I did have them in a pack with CoFH items present before I tried them solo to single them out.
I can get you a new test from a pack soon.
I'm not certain if I have CoFH lib, although I can say that the Ender IO Unofficial you can get from CF works as I was just doing an update/swap of those for these more modern GTNH versions.

**Comment by ranger135xp** [comment]
I added CoFHLib and it works solo.
It looks like this wasn't an issue after all but I'm glad we got something resolved.
