### ISSUE TITLE
NEI crash at startup with latest 2.5.0.

### ISSUE THREAD

**Issue by ranger135xp** [GTNewHorizons/GT-New-Horizons-Modpack#15292]
### Your GTNH Discord Username

Ranger135xp

### Your Pack Version

N/A

### Your Server

Private

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Upgrade NEI to 2.5.0, with or without the latest CodeChickenLib and CodeChickenCore, so use either 1.1.10/1.1.13 respectively or 1.2.0.
Even in an empty modpack through GD Launcher and only including these items, the crash occurs just the same with slightly different messaging beforehand, but the ERROR line is the same. @staffix on GTNH Discord was able to reproduce.

### Crash Report

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13855607/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
@bombcar dependencies.info is not just for downloading jars. It also adds them to classpath.

**Comment by bombcar** [comment]
> @bombcar dependencies.info is not just for downloading jars. It also adds them to classpath.

So having it with no url will disable download but add it to classpath?

**Comment by Glease** [comment]
That I'm not sure. However, my bet would be it'd crash as well without url.

**Comment by Glease** [comment]
It looks like it will not crash if CCL is present in mods/1.7.10/ folder, but if not, it'd still crash as it won't disable download.

**Comment by bombcar** [comment]
Ok will re-add with 1.2.0 links correcting inserted.

**Comment by ranger135xp** [comment]
I'll add, my test was with CCL in the mods\1.7.10\ folder.
