### ISSUE TITLE
Storage bus doesn't put chips in assline

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#15296]
### Your GTNH Discord Username

bangbang2142

### Your Pack Version

2.5.0 2.5.1

### Your Server

private

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Good day. Since version 2.5.0 in assline automation stopped laying chips in the input bus from the storage bus. If there is an interface without advanced block card in the scheme, the chips are placed in its slot. If with the card - disappear unknown where until you do not re-install the input bus

### The Reality

Always quietly the chips went into the input bus

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
i got this issue as well, dismantling and replacing the storage buses fixed the issue. It's annoying but as a work around you can dismantle them all then place them back, then use a memory card to batch set the priorities.

**Comment by PredVesTNiK2142** [comment]
That wouldn't be a bad thing, but it didn't help. Not reinstalling the input bus. Neither reinstallation of Assline as a whole.

**Comment by PredVesTNiK2142** [comment]
Checked your idea - reinstalling storage bus did not solve the problem

**Comment by PredVesTNiK2142** [comment]
The advice to disconnect the input bus filter with a screwdriver helped
