### ISSUE TITLE
Backport of Littletiles (from 1.12) and Effortless Building 

### ISSUE THREAD

**Issue by divine-ray** [GTNewHorizons/GT-New-Horizons-Modpack#15299]
### Your GTNH Discord Username

divine_ray

### Your Pack Version

2.5.1-server

### Mod Name

Little Tiles || Effortless Building

### The Mod to Add

Having Littletiles for 1.7.10 in the state of the 1.12.2 version would dramatically change the building aspects of bases, since it allows for quite complex (and large, think entire building facades!) designs, similar to Chisels&Bits/FMP but on a polygonal way. If i recall correctly, it would be able to replace carpenter‘s blocks and the slope sections of Architecturecraft, since it can do arches/round shapes as well. 

Regarding Effortless Building: This mod, as i know from NomiCEu, is capable of supporting builder‘s wands, as it allows to build large basic shapes (cube, plane, sphere) at three clicks. Possibly a alternative to backporting Building Gadges and survival friendly designed, as it consumes the used blocks from the player‘s inventory (“legitimate” player’s alternative to WorldEdit)

### Your Reason

Duplicate mentions, elaborated above.
Littletiles: large-scale high-detailed multiparts, decorations, etc. 
Effortless Building: Survival-Friendly alternative to WorldEdit, complementary to the Builder’s wand.

### Preliminary Investigation

The 1.7.10 version of littletiles is intensely lacking and nearly unusable due to its division mechanism of blocks. 
 Infuriatingly finicky to use. I had it once on a creative MP server, and it got mostly ignored due to how awful it was to use. It also does not have any slopes or additive/subtractive modifier options, which the 1.12 version has.
 
 Effortless building does not exist on 1.7.10, and other tools to achieve such have been rather unfriendly to me (RFTools builder is straight up OP, worldedit is considerable as cheating)

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by divine-ray** [comment]
Just checked, LT is under LGPL-3.0, EB has No License(?).

**Comment by mitchej123** [comment]
There's a LGPL EB (fabric) available.  

I'm in favor of both (or building gadgets) however it's really a matter of finding someone 1) skilled enough 2) motivated enough - to actually do the backport.

**Comment by mitchej123** [comment]
(Also their CF page says it's LGPL)
