### ISSUE TITLE
Fluid cells with fluids are rendered incorrectly or do not render

### ISSUE THREAD

**Issue by DarkAhri** [GTNewHorizons/GT-New-Horizons-Modpack#15308]
### Your GTNH Discord Username

Dark_Ahri

### Your Pack Version

Nightly 301

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Fluid cells with fluids are rendered correctly.

### The Reality

![Screenshot_20240110_090755](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18422805/7b68e1bf-8898-4a46-8a4f-41e6f5c8d315)
All fluid cells are filled with water.

### Your Proposal

Plz fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by UltraHex** [comment]
Fixed by GTNewHorizons/GT5-Unofficial#2476
