### ISSUE TITLE
Crash attempting to launch the game with Prism 8.0

### ISSUE THREAD

**Issue by crusader3456** [GTNewHorizons/GT-New-Horizons-Modpack#15300]
### Your GTNH Discord Username

crusader3456

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Other MCPC+ fork

### Your Actions

Installed new variant of the pack.

Launch the pack. Pack get hung up for a minute on fetching libraries.  Then proceeds and immediately crashes

Troubleshooting steps:

Updated to from Java 17.0.7 to 17.0.9

Updated from Prism 7.1 to 8.0

Removed and re-added account

Verified that my older 2.3.4 and 2.4.0 instances launch (they do)

Verified that the Java 8 Version launches by switching my Java version

Upon investigating in the discord #help channel It appears that it is connectivity to the Jenkins repo

### Crash Report

https://pastebin.com/70hjWsTx

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by xandora** [comment]
It appears to be a failure when downloading the (or some of) the additional files: 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/2021268/5f165c8a-7042-4343-befd-5a25a5edca1f)

The above download either fails or times out and the process exits.

**Comment by crusader3456** [comment]
The jenkins repo can be reached and the library files manually installed but they fail to get downloaded by Prism

http://jenkins.usrv.eu:8080/job/lwjgl3ify/

**Comment by bombcar** [comment]
If you manually update lwjgl3ify to the latest from its repo (replace the jar with jar) it should start working again.

**Comment by bombcar** [comment]
We fixed tha janky jenkins
