### ISSUE TITLE
Tinkers' Construct Smeltery size limitation does not match the wiki.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#15307]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Other versions in between

### Type of Server

Single Player

### Your Expectation

Based on the wiki, the size limitation should be an 11x11 area for the Smeltery.
https://wiki.gtnewhorizons.com/wiki/Smeltery

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3158887/f11c01a5-a0c3-409b-b212-ddd34d977e70)
This is an 8x8 example smeltery, where the GUI does come up *but* the ability to add in materials is blocked.

### Your Proposal

Ideally I would suggest to fix the bug rather than change the wiki, since an 8x8 base is great to work with when it comes to bulk smelting (as each vertical layer is a stack of items).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
I hate to quote the source that you said was "wrong," but, and a big one at that, the wiki quite clearly states that the max size is 7x7. So, it is no wonder why 8x8 does not work.

**Comment by bombcar** [comment]
It may be limited to a 7x7 base, but it can go very tall.

**Comment by StaffiX** [comment]
> I hate to quote the source that you said was "wrong," but, and a big one at that, the wiki quite clearly states that the max size is 7x7. So, it is no wonder why 8x8 does not work. It is quite possible that you may have googled the wiki for it and landed on the new TC wiki, which does allow bigger size limits, while the wiki you posted here is simply not that.
> 
> That being said, in the side notes on the page itself, it states 11x11, but in the actual wiki, it states max size is 7x7. I wish it was bigger too!

the wiki was edited 2 hours after the issue was posted

**Comment by PlayfulPiano** [comment]
yeah was about to say, the wiki was changed within the past like 12h. It was at 11x11 for much longer.

And either way although the vanilla TC is limited to 7x7, considering this is GTNH and a lot of mods are modified anyways, it should be changed to what was previously mentioned in the wiki for the reasons I mentioned.

**Comment by bombcar** [comment]
As a note, there is 

`private static final int MAX_SMELTERY_SIZE = 7;` soooooo if someone wants to do all the testing I could try making one with SIZE=12 (we would have to be bigger).

**Comment by bombcar** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/533931/2ba0bf8e-3970-446b-973b-6121e25aa735)

(maybe this should be a config, no idea if this big would cause TPS to go to hell)
