### ISSUE TITLE
[NEI] Backport EMI's craftable toggle.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#15306]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.5.1

### Your Proposal

Add a toggle to the Index panel in NEI to see what items you can craft dependent on your current inventory / UI storage access.

### Your Goal

This would be an extremely nice QOL addition to the mod for GTNH, considering there are a couple issues (especially in early game) where getting the proper recipe shape or figuring out what recipes you have available is fairly difficult and frustrating. 

### Your Vision

I can see multiple benefits from adding this feature:
- Pam's Harvestcraft food items won't be nearly as annoying to craft variety-wise, since you can put a bunch of food items in your inventory and match ones you haven't made yet.
- When doing earlygame crafts, you can more easily bulk craft items without having to over rely on the bookmarks tab.
- Requires less reliance on the quest book to progress, which should help players new to modding (see this here: https://www.reddit.com/r/feedthebeast/comments/1bqcjjb/modded_minecraft_is_missing_one_key_feature_to/)
- Goes around issues with GT tool crafting recipes not being bookmarked properly for specific materials (image example of the issue below). A craftables panel means you can more easily quickcraft tools for a specific material since it's specifically grabbing from the available items in your inventory.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3158887/d855ae58-f5bd-4840-a739-9adabb15720d)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by PlayfulPiano** [comment]
This might actually be an EMI feature and not a JEI feature, my bad.

**Comment by PlayfulPiano** [comment]
Slight edits to fix accuracy of the suggestion, + a post made in the FTB subreddit that complements this idea well.

**Comment by slprime** [comment]
I tried to implement something similar, but there are a some of problems that are difficult to solve. Not every handlers indicates a connection to the interface, and with modularui this is even more difficult to do.

**Comment by PlayfulPiano** [comment]
> I tried to implement something similar, but there are a some of problems that are difficult to solve. Not every handlers indicates a connection to the interface, and with modularui this is even more difficult to do. no ideas yet. maybe later

Aww, dang. Guessing it's more complex than determining recipes based on the machine your GUI has open & items or fluids in that machine or your inventory, correct?

**Comment by slprime** [comment]
> > I tried to implement something similar, but there are a some of problems that are difficult to solve. Not every handlers indicates a connection to the interface, and with modularui this is even more difficult to do. no ideas yet. maybe later
> 
> Aww, dang. Guessing it's more complex than determining recipes based on the machine your GUI has open & items or fluids in that machine or your inventory, correct?

yes. the easiest way is to do this only for crafting grids. 
Link: machine - GUI - recipe not always available

**Comment by PlayfulPiano** [comment]
> > > I tried to implement something similar, but there are a some of problems that are difficult to solve. Not every handlers indicates a connection to the interface, and with modularui this is even more difficult to do. no ideas yet. maybe later
> > 
> > 
> > Aww, dang. Guessing it's more complex than determining recipes based on the machine your GUI has open & items or fluids in that machine or your inventory, correct?
> 
> yes. Link: machine - GUI - recipe not always available the easiest way is to do this only for crafting grids.

honestly even that functionality (for now) would still be pretty useful for newer players in the modpack. Since generally speaking you won't have access to specific machine GUIs till steam, and a lot of players unfamiliar with modding could quit while in stone due to the overwhelming amount of items in nei.

**Comment by PlayfulPiano** [comment]
.

**Comment by PlayfulPiano** [comment]
.
