### ISSUE TITLE
Cant craft Woven Cotton from Pam with Cotton from Pam

### ISSUE THREAD

**Issue by timb8g** [GTNewHorizons/GT-New-Horizons-Modpack#15311]
### Your Pack Version

2.5.1

### Your Proposal

Hello Guys,

I have seen I can craft Woven Cotton only with Cotton from Natura.
Is it wanted like that?

I would suggest to change the crafting recipe to oredict Cotton "cropCotton".

Best regards

### Your Goal

I dont see any reason why I need specific cotton from Natura mod to craft Woven Cotton.

### Your Vision

Woven Cotton craftable with every cotton.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by timb8g** [comment]
Same with the cotton recipe for "String". I cant craft it with Pams Cotton.

**Comment by chochem** [comment]
you can craft pams cotton into Natura cotton
