### ISSUE TITLE
Crash by inventory shuffle event.

### ISSUE THREAD

**Issue by CondoSlime** [GTNewHorizons/GT-New-Horizons-Modpack#15317]
### Your GTNH Discord Username

Condoslime

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

If a warp theory inventory shuffle event happens while you are using combat mode, the game crashes.

### Crash Report

https://mclo.gs/3x8cArN

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by CondoSlime** [comment]
I got this crash again. Except this time it happened a couple minutes after the inventory swap. I pressed the button to enter combat/dual wield mode right as the crash happened.

**Comment by leumasme** [comment]
https://github.com/GTNewHorizons/WarpTheory/blob/007f4d7852bddbd34261a0871e6ec8cb1b75924c/src/main/java/shukaro/warptheory/handlers/warpevents/WarpInventorySwap.java#L51

https://github.com/GTNewHorizons/WarpTheory/blob/007f4d7852bddbd34261a0871e6ec8cb1b75924c/src/main/java/shukaro/warptheory/handlers/warpevents/WarpInventoryScramble.java#L27

Warp InventorySwap and InventoryScramble assume that the `player.inventory.currentItem` is part of the `player.inventory.mainInventory`. The Combat hotbar slots are not part of the mainInventory, so it errors when these events occour while the combat hotbar is selected.

**Comment by CondoSlime** [comment]
Thanks for confirming the issue. I wonder how it went unnoticed this long. Does no one walk around with their weapons out constantly while on high warp? My healing axe is in my weapon loadout so I carry it around all the time.
