### ISSUE TITLE
MAtmos crashes at startup

### ISSUE THREAD

**Issue by timb8g** [GTNewHorizons/GT-New-Horizons-Modpack#15310]
### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

Have added MAtmos v1.12.2-36 to my pack.

Now minecraft crashes at startup.

I have added optifine too.

Does anyone have a solution?

Thank you a lot.

### Crash Report

[crash-2024-01-10_13.37.02-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13887722/crash-2024-01-10_13.37.02-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
I dont know what you expected. this is not a 1.12 pack and that mod might break all kinds of stuff anyway.

**Comment by Ethryan** [comment]
Try using the 1.7.10 version instead.
