### ISSUE TITLE
Game Crash Potentially due to class error in sharewhereiam

### ISSUE THREAD

**Issue by Tertell** [GTNewHorizons/GT-New-Horizons-Modpack#15319]
### Your GTNH Discord Username

turtleturtle_

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

Install has been modified by the replacement of the journeymap fairplay mod, and addition of a new journeymap mod, and the installation of FTB utilities, FTB library.
![InstallationChanges](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52684629/7318d733-4924-4bb6-885a-4f7d3fa3349a)

Some files were also then transferred over from the previous installation as this is a new installation created to update from 2.3.6
However removing these files one by one and attempting to launch the game results in an identical crashlog.

The crash proceeds as follows:

Launching game, launch becomes stuck at some number between 30 and 99 on the post initialization loading gregtech stage, 
![BufferScreen](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52684629/1ec9b1cc-2ba1-43ea-ae58-93c7f16e9199)
crash log shows fatal errors within sharewhereiam's command WaypointSave, as pointed out by chochem at midnight on the 11th of january
Chochem: Caught exception from sharewhereiam
java.lang.NoClassDefFoundError: com/muxiu1997/sharewhereiam/command/CommandWaypointSave

Investigating the file of sharewhereiam it is clear that there is a class for the CommandWaypointSave however
![ClassEvidence](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52684629/9073239d-b324-441f-bc7d-3b4443bb1220)

Therefore it is unclear to me what the crashlog is referring to

i am totally lost

### Crash Report

[TCrash2.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13896141/TCrash2.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment]
We have Serverutilites that updates ftb (replaces it). Might be worth a try.

**Comment by bombcar** [comment]
What was the fix?

**Comment by Tertell** [comment]
Almost too embarrased to admit, not an issue with the pack at all, had the wrong version of the journeymap mod swapped in so the sharewhereiam mod couldn't loop in properly, all resolved.
