### ISSUE TITLE
Ebf ore processing with circuit 4 has incorrect yield 

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#15314]
### Your GTNH Discord Username

hebiwashere#0000

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I should get 1.5x the yield with ebf when I process with carbon dust. 

### The Reality

![Screenshot_20240111_011414_com discord](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49487505/4abd75ae-5a48-43ce-ae3c-2ab16f51e2f9)
![Screenshot_20240111_011132_com discord](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49487505/eaef08ed-d954-4491-974f-dbbc76c51a44)

The yield is same as smelting only with circuit 4.Heres two examples. 

### Your Proposal

fix the yield to.1.5x

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by tommy307507** [comment]
I asked someone to provide me screenshot of their 2.5.1 game as I have closed my game and was asking to verify...

**Comment by chochem** [comment]
oh wow those additions are *all* creating recipe conflicts https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/743.
