### ISSUE TITLE
Switching multiple recipes to assembler + adding of multiple assembler recipes

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#15318]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.5.1

### Your Proposal

Switching recipes to assembler cause the extreme autocrafting terminal is pretty slow and don't have a good alternative way to do it

Recipes that I would think of to get as assembler recipes:
 - Solar Panel (LV) up to Solar Panel (UV)
 - Microcontroller Case (Tier 3)
 - Drone Case (Tier 3)
 - ME Digital Singularity Cell
 - ME Fluid Digital Singularity Cell
 - Infinity Chest
 - Neutronium Compressor
 - ME Quantum Storage Cell
 - Fusion Coil Block
 - Pattern Capacity Card
 - Advanced Card (needed for Pattern Capacity Card too)
 - Acceleration Card (from Applied Energistics 2 # 4354/30)
 - ME Interface (the small one # 4355/440)
 - Advanced Blocking Card
 - Hyper-Acceleration Card
 - Processor Machine Casing
 - Wireless Booster (from Applied Energistics 2 # 4354/42)
 - Heat Conductor (from IndustrialCraft 2 # 4102/5)
 - UV Microwave Energy Transmitter
 - Blank Pattern (from Applied Energistics 2 # 4354/52)
 - PBI Pipe Casing
 - Automatable Data Access Hatch
 - Advanced Data Access Hatch
 - Data Access Hatch
 - Fuzzy Card
 - YOTTank Casing
 - PTFE Pipe Casing
 - 4096 Core Co-Processing Unit
 - 1024 Core Co-Processing Unit
 - 256 Core Co-Processing Unit
 - 64 Core Co-Processing Unit
 - Teleporter (the one used in DTPF Controller Recipe)
 - Magical Memory (Creative)
 - Singularity Crafting Storage
 Needed for Singularity Crafting Storage:
 - Reactor Stabilizer
 - Reactor Stabilizer Rotor Assembly
 - Reactor Stabilizer Focus Ring
 - Reactor Stabilizer Frame
 - Reactor Stabilizer Inner Rotor
 - Reactor Stabilizer Outer Rotor
 - Draconic Flux Capacitor
 - Wyvern Flux Capacitor
 - ME Fluid Export Bus
 - ME Fluid Import Bus

Other AE2 Cards eventually too for consistency
Other Pipe Casings eventually too for consistency again

And eventually there is the thing too, that I think there should be a alternative to get chaos shards instead of just farming chaos shards from the chaos guardian
Thought about maybe some mixer/assembler recipe made from things like eternity + spacetime + magnetohydrodynamically constrained star matter or so to avoid the annoying chaos guardian farming if you wanna have some bigger processors with the new singularity crafting storage cause you need some of them and it's not hard to get but an expensive alternative to get them from tech instead of just exploring is a good way to handle it imo

### Your Goal

Get some changes that I think would make the modpack even better and these things are needed in most runs that get far and the dire autocrafting table is just a shitty mechanic here
If we get a multi for that it would be fine too but spamming the tables with world accelerators just isn't a thing I can see in late/endgame at all

### Your Vision

It would definetely be a good change imo and I guess many people would agree with that

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
ill leave it but really duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15276

**Comment by MaGeBZz** [comment]
@chochem would say it's way more, I look at the other thing rn and add them to mine as well

**Comment by chochem** [comment]
I would also add that direcrafting table recipes are very different in this regard from normal ones.
1) they have a serious gate as to when you can first make them 2) they are even more annoying super-late

**Comment by EnderProyects** [comment]
P.s for the chaos shard recipe I made this a while ago 
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14945

**Comment by GDCloudstrike** [comment]
imo instead of a crafting recipe for chaos shards it would be cooler to buff the amount the draconic reactor outputs and make it a viable renewable option

**Comment by EnderProyects** [comment]
Also for all the direcrafting table stuff, when MuTE come out there are people that says to make a multi, so that is going to be kinda solved ( Kuba self asigned one of those a year ago)

**Comment by MaGeBZz** [comment]
Yeah and MuTEs won't be a thing for a long time probably so we can't rely on that lol
And yeah draconic reactor buff by a big amount could be an idea or some other stuff but wanted to mention it as well definetely

**Comment by MaGeBZz** [comment]
Bump or so

**Comment by mamiemru** [comment]
4096 Core Co-Processing Unit
1024 Core Co-Processing Unit
256 Core Co-Processing Unit
64 Core Co-Processing Unit

i wanted to make an issue for them. those are quite long with MA
