### ISSUE TITLE
Mega Chemical Reactor has no "Input Separation" mode

### ISSUE THREAD

**Issue by Rikenbacker** [GTNewHorizons/GT-New-Horizons-Modpack#15316]
### Your GTNH Discord Username

Rikenbacker

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

The large size of the device assumes a lot of entrance hatches and buses, but the recipes begin to conflict with each other even on two buses and three hatches.

### The Reality

Mega Chemical Reactor has no "Input Separation" mode. Therefore, the probability of conflicts in recipes is very high.

### Your Proposal

Add "Input Separation" mode for input buses.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
separation does not affect hatches anyway

**Comment by NotAPenguin0** [comment]
This would only do something for recipes that take item + fluid presumably. I don't really think this is a necessary change though. MCR is already strong as it is, allowing multiple input buses would buff it even further.

**Comment by AbdielKavash** [comment]
> This would only do something for recipes that take item + fluid presumably. 

Still a significant portion of recipes.

> Besides, what should happen if there is a circuit 1 and a circuit 24 recipe that only take fluid, but both circuits are present? I think this would just lead to a lot of unexpected recipe conflicts.

Up to the player to figure it out.
