### ISSUE TITLE
Missing water in an infinity water recipe

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#15324]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.5.0

### Your Proposal

Add water to the reservoir hatch recipe ( or change a pipe from the water reservoir to a bucket of water or similar)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/a2f9e32c-f049-482f-8793-7173cf6c18c7)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/5bd08b3f-001c-4f37-b685-91afb70572c9)

### Your Goal

Where all this infinity water come from, condensation inside the block or something?

### Your Vision

Add a litle more sense to the block, and also to use it as an ingredient in the recipe of the inf ae2 water cell

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Savallator** [comment]
"Where all this infinity water come from, condensation inside the block or something?"
And where is it coming from when there is a single bucket in the recipe?
In my opinion, that is just making the recipe annoying for the point of making it annoying...
