### ISSUE TITLE
WAILA no longer shows CRIB machine/name

### ISSUE THREAD

**Issue by kstvr32** [GTNewHorizons/GT-New-Horizons-Modpack#15321]
### Your GTNH Discord Username

kstvr

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Crafting Input Buffers show their name or machine name and circuit (default behavior) in WAILA.
<img width="500" alt="Screenshot 2024-01-10 at 10 35 00 PM" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/109012629/72a7a88c-1409-494b-b6c6-68e0fcbe8e21">

### The Reality

Crafting Input Buffer's don't show their name in WAILA.

![Screenshot 2024-01-10 at 10 29 51 PM (2)](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/109012629/6e1f41d5-6d1c-4b75-8367-9e9331c1d633)

### Your Proposal

Revert this commit https://github.com/GTNewHorizons/GT5-Unofficial/pull/2272 that removes the name from WAILA. Alternatively, we can only show the name if it can pull the name from a multiblock or is renamed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kstvr32** [comment]
On further testing, WAILA is not showing the renamed name of AE2 interfaces or dual interfaces like it used to. That was really useful. I'm not sure where that got removed.

**Comment by lucassun14** [comment]
In 5.09.43.192 (Official GTU version 2.4.0) is still working but when I update GTU to 5.09.44.03, It just disappeared.
