### ISSUE TITLE
Industrial Apiary only auto-outputs the first slot

### ISSUE THREAD

**Issue by divine-ray** [GTNewHorizons/GT-New-Horizons-Modpack#15325]
### Your GTNH Discord Username

divine_ray

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Industrial Apiary (the one that accepts upgrades) only ejects the first of nine slots of items, eventually leading to a jam. 
It should eject all slots.

### The Reality

Only the first slot of nine (with the princess) is pushed to piping and adjacent inventories.

### Your Proposal

It should just put all the items out of the inventory. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AdolMors** [comment]
Unsure if GT item pipes are being used here, but there is this peculiar behaviour in regards to the transfer speed of GT pipes known as item capacity on the tool tip.

When iapiary auto outputs to a GT item pipe, the number of output slots getting pushed to the item pipe is limited by the item capacity. Only 1 item is pushed (so only the princess) when the capacity is not higher than 1 stack per second. If the pipe is capable of pushing more than 1 stack per second, then that many items get pushed (4 stacks per second equal 4 stacks, so princess, drone and 2 other items).

To get around this, the iapiary can directly output to a (empty) chest.

Alternatively, use an EnderIO item conduit to accept the iapiary output. Set the conduit to extract from output side of iapiary. The conduit does not need to be activated in any way. The iapiary will push all output items into the conduit and the conduit will deliver all items to a connected inventory. Interestingly the item conduit is clearly pushing more than 4 items per operation in this use case.

**Comment by AdolMors** [comment]
This does imply iapiary tries to output all items at once at the end of a bee life cycle, which is different from normal GT machines continuously performing auto output.
