### ISSUE TITLE
Add ArchaicFix to the pack

### ISSUE THREAD

**Issue by ah-OOG-ah** [GTNewHorizons/GT-New-Horizons-Modpack#15335]
### Your GTNH Discord Username

aptugongermatherinn

### Your Pack Version

Nightly [#304](https://github.com/GTNewHorizons/DreamAssemblerXXL/actions/runs/7497268222)

### Mod Name

ArchaicFix

### The Mod to Add

Backport of Phosphor (major lighting engine improvements) and a smattering of other bugfixes and performance tweaks.

### Your Reason

Less bugs, more performance. Duh.
Honestly not sure why it wasn't already added.

### Preliminary Investigation

I've run AF since 2.1.2.3 and noticed no issues. It's possible some of the features overlap with Hodgepodge, but if so they aren't hard crashes/serious bugs.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by bombcar** [comment]
https://github.com/embeddedt/ArchaicFix link

I know some of this is merged into Angelica (or planned to) but the server-side things could be useful. It's actively developed by @embeddedt who has helped @mitchej123 with Angelica also so they may already have plans about how it would look when Angelica is finalized.

**Comment by chochem** [comment]
have used for over a year, very happy with it. (and yes I know, not exactly a benchmark :P)

**Comment by ah-OOG-ah** [comment]
Does there need to be more discussion, or is this just waiting for someone to add it?

**Comment by Caedis** [comment]
Is AF client only?

**Comment by mitchej123** [comment]
> Is AF client only?

It's both - phosphor (The lighting engine) has server and client side components.

**Comment by Caedis** [comment]
It is already on the [additional mods list in the wiki](https://gtnh.miraheze.org/wiki/Additional_Mods) so i am going to go with no

**Comment by mitchej123** [comment]
I'd vote yes, I'd love to get the lighting engine replaced with something less laggy

**Comment by Ethryan** [comment]
Hmm, looks interesting.

**Comment by mitchej123** [comment]
It's in the latest nightlies, along with coretweaks.
