### ISSUE TITLE
Salty Root Turns Adjacent Double Crops to Single Crops

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#15339]
### Your GTNH Discord Username

Desagas

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

When trying to cross breed, I would expect that if a double crop stick is to disappear, it would either have a mutation on it, replacing the double crop with the mutation and a single crop, or, it would turn into a weed.

I am not watering them by any means.

I am in a meadow, 14C and 70 Humidity, but all biomes I have tried them in causes the same thing to happen.

### The Reality

However, when in a field of salty root, trying to breed them, granted, above a dry humidity, double crops simply turn into singles. They sometimes make weeds, like the rest of the crops, BUT, they more often simply change into singles.

Now, I want to clear up what I know someone is going to say: but all crops can die off sometimes ... which is true, but, that usually happens to plants on crops, NOT on double crops without plants. In my 17 years in game time, or 289 days IRL time, this is the only crop I have seen this happen with. If it is intended, I do not see it mentioned anywhere, if it is not intended, I believe it may be a bug.

Is it possible that they are both breeding and dying in the exact same game tick?

### Your Proposal

If it is intended, say so in its quest for Salty Root crops. Personally, it is more realistic, as salt will destroy everything around it, including untreated wood, but it is not normal within this pack.

If it is not intended, make it act like all the other crops when breeding.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
Are you watering the salty root through a cropmatron or any other means?

**Comment by desagas** [comment]
No, no water what so ever. Just the environment. But, it does the same thing with or without water.

**Comment by desagas** [comment]
But, again, as I mentioned, the salty root was not affected at all, just the double crop sticks adjacent to the plants.

**Comment by desagas** [comment]
Environment is at 14C and 70 Humidity. But, every biome I have tried to grow this in has had the same affect. The one I am breeding in is a Meadow.

**Comment by AdolMors** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/65a8a471-e788-4dd6-97aa-1f50df7f2198)
This is in 2.5.1 and I found no problems. The personal dimension is plains so definitely worse than meadow in terms of biome stats.

**Comment by AdolMors** [comment]
If you haven't, you should use GT portable scanner on the crop to verify it is just crop stick.

**Comment by desagas** [comment]
To the image posted above: as I said, if you read what I wrote: it doesn’t always happen, I said it happens a lot.

To the reply suggesting I scan the crops: I didn’t make this issue thinking it “might be” happening, but thank you for the suggestion. Perhaps it will help others who “might think” that no plants are growing. When I first started, a few plants disappeared on the garden soil, as it is a full height block, but I learned fast that there were plants on the crops. That is not the case here. My issue is sound.

**Comment by desagas** [comment]
@AdolMors 289 IRL days playing this pack, alone, and, further, I've been playing with IC2 crops since the mod IC2 was first released with crops included. So, I do, in fact, know how they work. And, against your self proclaimed expertness ... all sources and all testing state that you are in fact 100% wrong when it comes to humidity and temperature, what was it you said, having absolutely no affect on crops what so ever. Al least, that is what I think you just said? So, lets not immediately jump to "you are not too familiar with IC2 crops," no, rather, let us stick to the actual issue at hand. Don't be condescending, and let's fix this.

So, please, reread my issue posted above, and the comments below it, BEFORE we continue. But, let me reiterate this: every single crop with out exception, meaning no exceptions what so ever, have worked completely fine, and not a single one, other than salty root, has had this problem.

Regards, and, please, do better!

**Comment by AdolMors** [comment]
I am just as confused as you are to this problem so I was trying to eliminate options. There should not be recent IC2 crop changes. and I had no problems trying to crossbreed with salty roots.

As far as I am aware, there is no correlation between the temperature and humidity percentage reported in ingameinfoxml and the biome bonus. I was pointing that out because I know those should not be treated the same as biome bonus. For example I can tell you maple woods has -19C and 50% humidity in ingameinfoxml. It does not help the discussion here. Maple woods provides 5 nutrients and 7 humidity to IC2 crops, exactly the same as meadow at 14C (somewhere y > 130) and 70% humidity. If the ingameinfoxml temperature and humidity do prove themselves to be culprit on this matter, I apologize for any inconvenience caused.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/88955956-48b0-4257-abe4-57b219d62e59)
Nutrients: 5 from maple woods + 3 from up to 3 dirt blocks below farmland
Humidity: 7 from maple woods + 2 from hydrated farmland

**Comment by desagas** [comment]
Anyways, can you please revert the conversation back to the issue actually posted?

This salty root thing has happened for a long time, I am simply reporting it now. I believe I started plating on 2.2.0 or something like that. I first used crops in 2.2.8, and from what I remember, salty root has always delete double crop sticks beside it.
