### ISSUE TITLE
Please add a way to toggle the Slimesling between having finite and infinite durability (it used to be infinite).

### ISSUE THREAD

**Issue by TheKhopesh** [GTNewHorizons/GT-New-Horizons-Modpack#15331]
### Your Pack Version

2.5.1

### Your Proposal

Add an easily activated/deactivated option to make the Slimesling have infinite durability like it used to (a change I feel doesn't have any benefit to, but does have a detriment).

### Your Goal

It's fairly self-explanatory.
It would be nice to have the option to not have to replace an item at all (let alone so frequently) that requires this much effort to replace.
A simple toggle on whether or not it has durability is all that's really needed here, even if it's off by default.

### Your Vision

I wholeheartedly disagree with the change to the sling making it have durability, but Tinker's Construct (apparently) did so anyway, and in a way that is extremely odd to say the least.
It doesn't even have a standard visible durability value (tricking those who see it before they make and use it into thinking it remains an infinite use item like it used to be), it simply has a percentage that ticks down one percent per use.
But as much as I disagree with the change, I highly doubt I could convince them to change that.
Regardless, they at least made the recipe FAR more accessible and far cheaper by default than it's altered cost is in Gregtech, and sadly the altered recipe makes it excessive by requiring steam tech so you can't even use it in until many many hours (or days) IRL time into your playthrough.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Quetz4l** [comment]
As I recall, it can all be repaired with slime in the Crafting Table

**Comment by TheKhopesh** [comment]
> As I recall, it can all be repaired with slime in the Crafting Table

I just tried it and it didn't seem to work, nor is there a recipe for repairing it in the NEI recipe table.
Even if there were one, it would still require tying up precious inventory space for repairs when simply allowing players to choose between infinite and finite durability would be preferable (though the repair idea is a good one).

**Comment by TheKhopesh** [comment]
Still no progress on this?
Honestly, I find that though it's a minor inconvenience making sling after sling once you have a good +30hrs into your playthrough and have the machines needed to get all the materials to craft them, the addition of durability to the item detracts from the experience on the whole.

Outright removing durability functionality would solve the issue with the least amount of work, and would be most suiting given that the strange and unusual non-repairable durability function prevents all forms of repair or prolonging of the durability.
