### ISSUE TITLE
Crash on dismantling energy cell with gt wrench

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#15342]
### Your GTNH Discord Username

FalseColor

### Your Pack Version

GTNH Nightly build 2024-01-13+310

### Your Server

Zeta

### Java Version

Java 8

### Type of Server

None

### Your Actions

Shift + RMB with GT electric wrench on installed dense energy cell

### Crash Report

[message.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13931611/message.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2395

specifically I would guess its raytrace in https://github.com/GTNewHorizons/GT5-Unofficial/blob/0794b1c7b9105e3343c2b1881483e2dc484e736e/src/main/java/gregtech/common/tools/GT_Tool_Wrench.java#L213 being client-side only

**Comment by Dream-Master** [comment]
@chochem is this fixed or on a todo list ?

**Comment by chochem** [comment]
not by me, no. finding the problem doesnt mean I know how to fix it.
