### ISSUE TITLE
Stargate Controller should be craftable

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#15345]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.5.1

### Your Proposal

The Stargate Controller from SG Craft isn't craftable
I know there is the OC interface but for people that didn't know anything about OC it would be pretty nice to get access to a Stargate Controller Recipe to have another way to launch it

### Your Goal

Make the stargate more usable for people, that didn't know OC at all

### Your Vision

It would be nice to see it, cause it is a bit weird imo to have OC skills to make the gate itself be usable

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Chaoschaot232** [comment]
> Well, at least this fits the Stargate "lore", maybe that was the intention behind it? In Stargate, they only found the gate on earth, but the DHD (the controller) was missing, so they used a powerful computer to operate it instead. But apart from that, i totally agree with you...

Sure that you can count this to the SG-1 lore but only for the beginning and it's initial movie because as they arrive for there first time on Abydos there is clearly a DHD otherwise how could they have been be able to travel back home?

Means that it makes only 50:50 sense to force a usage over OC so in general the SGC should be craftable after all :)

**Comment by MaGeBZz** [comment]
@Chaoschaot232 I don't know anything about the gate in the movies but I would say I like the idea that the gate gets some lore + we get the chance to craft the actual controller and not only the OC version of it
Like there could a very expensive kind of recipe to make it and another one which is like you say maybe get some specific things that you can find on other planets so you could choose between exploring vs an expensive way to make it

**Comment by Chaoschaot232** [comment]
@MaGeBZz Yes, that was my intension at this point. I like the exploring way more compared to a totaly over-expensive recipe for it but this can also be made. Only the parts would be missing (for now) and I am currently moving into my new flat so for now I am out as I can't focus on programming until I am done with everything :)

**Comment by MaGeBZz** [comment]
@Chaoschaot232 yeah I'm more like the technical guy and not being a fan of exploring too much especially in this modpack cause it's mostly based on tech imo with ways to use exploring, magic etc to get QoL
But yeah I'm not a programmer so I can't do it by myself anyways I could only give ideas and would be fine with talking to someone who could let this happen but I like the idea definetely

**Comment by Hikari1nVoid** [comment]
OC is fun.
Also working solutions for sgcx has been available for years.

**Comment by boubou19** [comment]
It is intended to be uncraftable. Stargate is the ultimate flex in the pack. Therefore you must at least know how to use OC to pretend you really defeated the pack.
