### ISSUE TITLE
Errors in crafting items with energy 

### ISSUE THREAD

**Issue by MrLeonardosG** [GTNewHorizons/GT-New-Horizons-Modpack#15349]
### Your GTNH Discord Username

MrLeonardos

### Your Pack Version

-

### Your Server

Private

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Post the crafts of any item (example: MFU), which contains energy items from IC2, in the template terminal.

### The Reality

When I first log in, I get that crystals are laid out without NBT and I can only lay them out. Further, if I look at crafting from half-charged crystals, then MFP crafting will now have only half-charged crystals and I can only use them in crafting (even manually) and so with any other item. 
After tests, it was determined that this error was caused by a mod NotEnoughEnergistics(1.5.0 version), attempts to change its configuration yielded nothing.
(The video will show an example with a mod that is not present in the build, but everything also works with a regular industrial)

https://youtu.be/TNKp7EBrLgc?si=8PQ5u1DgkVhjHtSM

### Your Proposal

Missing... 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
This is very hard to understand. Probably a language barrier.
Is there a crafting recipe thats broken? or some bug in NEI?
also, that doesnt look like GTNH. does the problem exist in GTNH and if so in which version?
