### ISSUE TITLE
Stargate should not automatically close itself

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#15344]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

The stargate shouldn't automatically turn off
Another group tried the OC interface and it turned off after some time and I tried the stargate controller from SG Craft and this method would turn off automatically too although it shouldn't

### The Reality

The stargate portal will close itself after a short time, not sure why but that makes it pretty useless tbh and I know only a few people will see that at all - but it would be nice if you achieve the gate, that you can at least use it correctly

### Your Proposal

Make the gate not close itself automatically

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Savallator** [comment]
Does it close itself after 38 minutes?

**Comment by MaGeBZz** [comment]
@Savallator I didn't know the exact time but I'm pretty sure it's faster than 38 minutes

**Comment by Connor-Colenso** [comment]
I'm confused what is wrong here, in the actual stargate universe lore, a stargate will close after 38 minutes unless you can supply an absurd amount of energy (black hole or maybe ZPM, which in the stargate universe is way more powerful than our ZPMs).

The stargate mod has always worked this way, I don't think it is a bug at all.

**Comment by MaGeBZz** [comment]
@Connor-Colenso I mean only if it was the whole time like this it shouldn't be I guess
I mean if you get to that point and can't even really use it cause you need to put in the code everytime you wanna use it basically that's not the point of the gate I guess
I know it's just about the journey to that but if you get there it should be functional imo

**Comment by Savallator** [comment]
I really don't see how that is preventing to use it. If you want it to be open all the time, then just make your script redial immediately after it closes, so i really don't get the hassle here.
In my opinion it is working exactly as intended and should not be changed.

**Comment by MaGeBZz** [comment]
I mean I don't know something about OC at all and just said to colen that there should be a way to craft the normal stargate controller for people who don't know OC at all and that is not configurable like OC

**Comment by Savallator** [comment]
It takes hardly any effort to copy an opencomputers script from someone else. "Not knowing anything about a mod" should not be a reason to change the game... "I don't know anything about blood magic, so i demand to get Meteors with a gt machine" would sound weird as well, right? Anyone else would tell me to just learn how to use BM.
It closing after 38 minutes is how it should be...
