### ISSUE TITLE
Talisman of Remedium disappears in amulet slot after enchanting with unbreaking

### ISSUE THREAD

**Issue by GrieverStormborn** [GTNewHorizons/GT-New-Horizons-Modpack#15347]
### Your GTNH Discord Username

Xarimna

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

1) Enchanted the Talisman of Remedium (Thaumic Tinkerer) with unbreaking III (used the void metal anvil)
2) Activate the talisman
3) Shift click the talisman into the amulet slot
4) Take some negative effect damage (tested with Ender Goo)

Expectation: The talisman does not void itself

### The Reality

Reality: The talisman is sometimes voided

Example: https://streamable.com/bkptb1 (message me on discord if clip expires)

### Your Proposal

Prevent talisman from being voided after a tick of damage

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GrieverStormborn** [comment]
Could be related to https://github.com/GTNewHorizons/ThaumicTinkerer/pull/36

**Comment by AbdielKavash** [comment]
That's right; the linked PR makes the Unbreaking enchantment works as intended, instead of, well, breaking the talisman.
