### ISSUE TITLE
Crash on loading world

### ISSUE THREAD

**Issue by rasenk1** [GTNewHorizons/GT-New-Horizons-Modpack#15354]
### Your GTNH Discord Username

rasenk.

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Game crash probably due to the wireless transmitter. 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/38162550/d863ab36-1b5c-484e-ab47-b8a2357f1bbf)

### Crash Report

https://mclo.gs/q91fuoN

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
seems to witchery stuff in an infinte loop

**Comment by rasenk1** [comment]
> seems to witchery stuff in an infinte loop

I never did witchery actually.
Probably that's something from this list:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/38162550/d6a7baba-2f06-465c-b324-563bcec58f1e)

**Comment by chochem** [comment]
its says witchery 1314 times in that log you posted. mixed up the log maybe?

**Comment by rasenk1** [comment]
I've tried to disable automagy mod and now it gives such crash report
https://mclo.gs/nInKTJy

**Comment by bombcar** [comment]
reenable automagy (run full pack)

and provide fml-latest.log

**Comment by rasenk1** [comment]
Starting in SP, so that's what i have (if i understood correctly)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13943791/fml-client-latest.log)

**Comment by Caedis** [comment]
happen to have any buttons or pressure plates next to an AE2 cable?

**Comment by rasenk1** [comment]
> happen to have any buttons or pressure plates next to an AE2 cable?

Probably i have a lever near the terminal, but surely no any buttons or pressure plates in the personal dimension

**Comment by leumasme** [comment]
What's at the coordinates roughly (46,227,-24) to (16,225,-19)?  
From a brief look at the latest log, it seems like a very large amount of witchery blocks at that location is getting destroyed at the same time (basically accidentally built an [update supressor](https://youtu.be/0Fwuve4njcY))

**Comment by rasenk1** [comment]
> What's at the coordinates roughly (46,227,-24) to (16,225,-19)? From a brief look at the latest log, it seems like a very large amount of witchery blocks at that location is getting destroyed at the same time (basically accidentally built an [update supressor](https://youtu.be/0Fwuve4njcY))

On that location i have this setup:
https://youtu.be/HVNGN6MJG6I?t=112
![2024-01-06_00 42 03](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/38162550/1d12ef63-8943-45ba-a09c-9536b3cf0847)
This includes the following items:
https://imgur.com/a/WRPiWKA

**Comment by rasenk1** [comment]
May this also help?
https://mclo.gs/xpGUh3R
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13944098/fml-client-latest.log)

I  tried deleting some region files from the save.
