### ISSUE TITLE
Colored Bees Bugged

### ISSUE THREAD

**Issue by Kyramesh** [GTNewHorizons/GT-New-Horizons-Modpack#15357]
### Your GTNH Discord Username

Kyramesh

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

I expect Bees for the various colors (white bee, blue bee etc.) to behave like any other bee, but they do not. See next point.

### The Reality

Colored Bees are bugged in various ways in the current version. Specifically tested for: white, blue, light blue, yellow and lime. I suspect all are affected.
1. Their breeding seems to be ignoring increases to mution chance. Tested with 2 setups: Apiary with 3 Maddening Frame of Frenzy and Alveary with 4 Boards of 4 golden tubes. This should give 100% chance for mutation. Breeding parents that result in color bees do not mutate 100% of the time, but rather in some random capacity. I did not fully test this, but it feels like the base chance is applied without the expected modifiers.
2. Colored Bees can not be "researched" in the Escritoire. This may be intended, but that honestly feels strange at least. You can put colored Bees in the centre spot, but than not add any bees in the left slots to be consumed. If you already have bees in the left slots, then you can click the Examine Specimen button. This will consume the left slot bees but not actually do anything on the board. You might be able to still win the memory game, but with the normal ruleset and no hints being allowed i did not try to do that. So no idea if you can generate research notes or not.

### Your Proposal

Clarify if observed behaviour is intended or make those bees behave like all the other ones.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
Can confirm #1

**Comment by chochem** [comment]
got around to some testing. Alveary with 2 estims (4x gold). and oblivion frame

for white (wintry+diligent): all bees mutate, it really is 100%. I am at 60/60 genes, I think I can stop there. However most are frigid, only a bit of white.

same now also with blue (and growing)

so I can _not_ confirm your findings, but there is still something very weird here.

**Comment by chochem** [comment]
ok for anyone else wanting to test it, the post just really messed up the examples. Just try Green Bee for example instead.

**Comment by Crommus** [comment]
I encountered this bug when trying to breed a magenta bee. I did some testing and it also happened with other mixed colour bees. Every other bee I've made using a 4x4 gold tube alveary had 100% mutation chance so far. 
I assume cross-breeding gendustry coloured bees is what's bugged, basic colours work fine because they are made by cross-breeding vanilla forestry bees.

**Comment by TrubbleAC** [comment]
Not sure if this ties in with the issues stated above, but colored bees also don't seem to have textures anymore.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/102751145/61de82e8-6e29-401d-8b9d-061e21fa902b)

**Comment by hron84** [comment]
I can confirm the missing textures for the Gendustry bees. This is the whole Blue gene mutation table:

![2024-05-06_07 46 20](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/88636/41d7b1e1-667a-44a2-9f28-5695448b7bfc)
