### ISSUE TITLE
All multi assemblers fail to craft Nano helmet

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#15352]
### Your GTNH Discord Username

Hiakri1nVoid#9527

### Your Pack Version

nightly310

### Your Server

zeta

### Java Version

Java 17

### Type of Server

None

### Your Expectation

craft nano helmet in PrA/gtpp Assembler by sending ingredients to crib.expect it tp craft

### The Reality

None of these multi respond.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by JodieRuth** [comment]
Quantum Suit Helmet can be produced normally

**Comment by HoleFish** [comment]
Have you tried PrAss precise mode

**Comment by chochem** [comment]
is there an item in there that needs charging? also, does singleblock work for you?
