### ISSUE TITLE
Some Large Cells showing incorrect colours when they contain fluids

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#15355]
### Your GTNH Discord Username

britishcynic

### Your Pack Version

Nightly 310 dated 13/01/2024

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

The Large Cells should replicate the colours used for fluids seen in other containers like cells.

### The Reality

![Fluids](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13187606/644c83fc-734b-4764-aa01-36204c20f4d2)

The two grey-filled cells in the centre are Refined Glue and Seed Oil, these previously would have had their colours the same as cells with that fluid. This is not happening with all large cells, as the one at the bottom of the image is correctly displaying black for Molten Rubber

### Your Proposal

Fix the cells so that the correct colour can be observed when they're filled with fluids.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
i have this in my testworld as well. Oxygen has ligth green color

**Comment by desagas** [comment]
Mine look like they have some letters of hatch marks on the front window in front of the incorrect fluid color. This has happened since updating to 2.5.1. However, with shaders installed, for some reason the colors are solid, not hatched, but the colors are all wrong.

**Comment by UltraHex** [comment]
Fixed by GTNewHorizons/GT5-Unofficial#2476
