### ISSUE TITLE
Incorrect mipmapping and anisotropic filtering on GregTech ores and other blocks.

### ISSUE THREAD

**Issue by UltraHex** [GTNewHorizons/GT-New-Horizons-Modpack#15359]
### Your GTNH Discord Username

0xUltraHex

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

![Screenshot 2024-01-15 200813](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3904250/baec6f19-332d-4d76-9c4e-f2f02dba7824)
This image was obtained by hacking the stone background to only render on pass 0 and the amethyst overlay to only render on pass 1 with several gl calls to setup correct blending.

### The Reality

![Screenshot 2024-01-13 123222](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3904250/d0708478-99a9-4b8a-acb7-f1bdb2e18610)
![Screenshot 2024-01-13 123155](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3904250/6e7bbd0e-08ad-4441-9b9e-316859492a20)

GregTech ores (and other blocks) use a series of overlayed textures for their appearance. This looks fine straight-on and close-up, but when viewed from far away or at an angle the textures begin to pixelate in odd (incorrect) ways. This is due to a lack of alpha blending between the mipmapped/filtered overlay and the texture behind it.

### Your Proposal

As usual, there are several potential solutions:

The sledgehammer: bake all overlayed textures into single, fully opaque textures when loading resources.

The scalpel: Enable correct blending for these textures during render pass 0. (I've attempted this myself and Minecraft doesn't seem to allow it and I can't determine why or how.) UPDATE: **Not feasible.**

The third option: Make fully opaque textures render on pass 0 and transparent overlays render on pass 1 with correct blending.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment]
How much additional texture memory does the sledgehammer involve?

Does it matter at all anymore?

**Comment by UltraHex** [comment]
Some folks on the Discord did some rough calculations the other day. The VRAM cost isn't nothing, but it's relatively small and low-end PCs should still be able to handle it. I think the number they came up with was about 10-50 MB.

**Comment by UltraHex** [comment]
I'd really prefer the scalpel approach, but I seem to be missing something so far.
