### ISSUE TITLE
Rape to Canola Deletes all Rape Plants, it does not Remane Them.

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#15351]
### Your GTNH Discord Username

Desagas

### Your Pack Version

2.5.1+312

### Your Server

SP

### Java Version

Java 19

### Type of Server

None

### Your Expectation

The crop simply would have been renamed.

### The Reality

But, someone way over engineered the change to remove the crop named Rape and then add the crop named Canola. This is a horrible decision, but I assume it was not a GTNH code that did this, rather a IC2 requirement??

This means that all fields that have the crop in it will simply revert to single crops.

### Your Proposal

Change the name of the crop only, do not delete the crop and then add another one..

Further, as someone living less than 8km away from where RAPE was created, this change is horrible. Sure, Canola is a great name as well, but why on earth would you deny its accuracy?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
For anyone who needs to have seeds given to them to fix this:

`/give @p IC2:itemCropSeed 18 0 {growth:21,gain:31,resistance:0,name:Canola,owner:gregtech,scan:4}`

**Comment by chochem** [comment]
its not IC2, its in gregtech. The internal name/tag was changed as well, so yea that means its a different plant and the old one is useles

**Comment by Caedis** [comment]
Thought they would auto swap to the new crop since they were in the same ID. Guess not. Undid the internal name in the attached PR.
