### ISSUE TITLE
EBF tooltip about output hatch is confusing

### ISSUE THREAD

**Issue by StaffiX** [GTNewHorizons/GT-New-Horizons-Modpack#15365]
### Your GTNH Discord Username

StaffiX

### Your Pack Version

2.5.1

### Your Proposal

EBF tooltip about the output hatch should say that the only fluids that goes at the top are the ones that are mentioned on the muffler hatch.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/32968022/7cf91a7e-13fe-4aa7-a246-3faaf098b149)

### Your Goal

Currently the tooltip states that the top output gasses
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/32968022/f102de04-0045-4cb9-8870-0554adf3341d)
but for example steam goes to the bottom hatch even though it is technically a gas

### Your Vision

This would make the EBF tooltip less confusing about the top vs bottom output hatch differences

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
Suggestion:

"Output Hatch: Exhaust Gases (CO2/CO/SO2), Any top layer casing"

**Comment by bombcar** [comment]
It’s confusingly worse than that. All pollution recovered by the muffler comes to hatches on the top. 

Some actual outputs go to hatches on the bottom. Except some that go out the top because bartworks. 

The EBF is cursed.

**Comment by desagas** [comment]
It says "pollution" already, why create new words. Use the word pollution again: Recovered pollutions to top layer hatches (CO2, SO2, CO), All other fluid outputs to bottom layer hatches.

Further, "reduces to x%" is horrible. It should say "recovers x%."

There are many many places in this pack where you can tell there are multiple people working on it, some trying to be proper, and some just throwing it together, when it comes to language.
