### ISSUE TITLE
EOH does not give half of start EU back when recipe fails like NEI says

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15362]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

251 build 310

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

EOH gives half of start EU back when recipe fails

### The Reality

![85Q2G9QVHY6EFU6F0TN4ROQ](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/533cdb64-a52a-476d-8bd6-06a2fb223760)
i tested many times, failed and not failed included(checked output to know if it failed). all have the same EU impact. 

### Your Proposal

fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GDCloudstrike** [comment]
It says it in the tooltip, or is it mentioned somewhere else?

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/93287602/48457392-16de-4ecd-934a-796f734a3fd2)

**Comment by miaowwwwww** [comment]
sry my fault， localization problem，closing this
