### ISSUE TITLE
inconel 625 recipes missing

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15363]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.5.1 build 310

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

all recipes like liquid to ingot available

### The Reality

some recipes misisng

### Your Proposal

add recipe back

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
should be fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2461
