### ISSUE TITLE
EoH controller + CAL change/additional feature

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#15367]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.5.1

### Your Proposal

I would suggest a little change/additional feature of the EoH controller eventually
My idea is to let it be as it is rn + adding the oppurtunity to craft the EoH controller together with a planet to make the placing of the EoH itself a bit nicer if you wanna place multiple ones
I would say if you do so you can't remove it anymore just like the CAL controller with the imprints in it

Maybe the same could be done with the CAL controller that you can craft it together too to make it less annoying especially for later if you need to place hundreds of them eventually

### Your Goal

Improve EoH and CAL placement instead of need to place multiple planets/imprints in the controller manually

### Your Vision

Improving spamming these multis

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by MaGeBZz** [comment]
Bump

**Comment by Amarozo** [comment]
I'd really love to see this in game. Maybe addind right-click action like it's done in GT++ Macerator or Dangote Distillus (upgrade chip) would be an option?

**Comment by MaGeBZz** [comment]
@Amarozo yeah would like the idea, would be nice to see it, if we haven't got another CAL alternative
