### ISSUE TITLE
Wireless connectors colors

### ISSUE THREAD

**Issue by EuroZona** [GTNewHorizons/GT-New-Horizons-Modpack#15371]
### Your GTNH Discord Username

eurozona

### Your Pack Version

2.5

### Your Proposal

Since GT spray can change che color of AE cables it would be cool if they could change the color also for wireless connectors

### Your Goal

Change the color of wireless connectors with GT spray instead of color applicator

### Your Vision

color applicator suck

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by CoreeZz** [comment]
And a paintbrush with different dyes.
