### ISSUE TITLE
Spreadsheet linked in Discord help channel is ancient

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#15387]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.5.1

### Your Proposal

I know this does not really belong here, but i don't know any other place to put it. I would ask to please redirect this to the correct person and then close/delete this issue.

The spreadsheet (google doc) pinned in the help channel is quite old, and it is unclear who is able to update it.
"MineAnPlay ENTR" is listed as owner. It needs to be either updated or removed from the channel or at least given a disclaimer.
Since a lot of stuff is apparently here: https://gtnh.miraheze.org/wiki/Quick_Links maybe pin that instead? Or otherwise, give a selected group of players edit permissions so the doc can be updated.

### Your Goal

Don't confuse new players.

### Your Vision

Have it up to date.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ethryan** [comment]
Look in the FAQ channel in discord, there is a link to the wiki there.

**Comment by Savallator** [comment]
How does that solve the problem of having outdated information advertised in Help channel?

**Comment by mitchej123** [comment]
This feels like something that should be brought up in #discord-feedback, instead of github TBH
