### ISSUE TITLE
add colors to me drives

### ISSUE THREAD

**Issue by tommasopanni** [GTNewHorizons/GT-New-Horizons-Modpack#15385]
### Your GTNH Discord Username

eurozona

### Your Pack Version

2.5

### Your Proposal

add colors to me drives

### Your Goal

add the colors so I can put the me drives close together without switching channels

### Your Vision

add the colors so I can put the me drives close together without switching channels

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ethryan** [comment]
What do you mean?

A more complete explanation please, is it colored lights?, different texture?, something else?

Some more information is needed @EuroZona

**Comment by EuroZona** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/114698219/c1508340-fb73-432a-8755-37826ce2f37f)
Like this, it would be useful to color the drives, maybe with an outerline color idk.
In this case the 4 drives are all connected, with the color change they will be in separated channels

**Comment by Ethryan** [comment]
Ah, you want to be able to paint the drive bays in order to separate them from each other.

**Comment by MCTBL** [comment]
Well, If there is a drive connected to wire with six different colors. Which color should it been painted?

**Comment by EnderProyects** [comment]
Just make priorities, like top, botom, right, left, back, front

**Comment by Ethryan** [comment]
Maybe they could only connect to the same colored cable and unpainted ones. That way they are consistent with the cables.
