### ISSUE TITLE
Gooseberry juice & Banana juice do not have any nutrients

### ISSUE THREAD

**Issue by BeepBeep20** [GTNewHorizons/GT-New-Horizons-Modpack#15384]
### Your GTNH Discord Username

beepbeep20

### Your Pack Version

2.5.1

### Your Server

stonehuts

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

The other juices give 1% fruit nutrition, Banana & Gooseberry don't have the tool tip & I presume probably don't give the nutrition.

### The Reality

The 2 new juices (Gooseberry & Banana) do not have nutrient information in the tool tip. 

### Your Proposal

To make Gooseberry & Banana juice the same nutrition % & tool tip as the other juices.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leumasme** [comment]
Added in https://github.com/GTNewHorizons/harvestcraft/pull/49 

Seems like they forgot changing https://github.com/GTNewHorizons/Nutrition/blob/b7dc7c2ba1182f76e22761cf391dabc12dcf86ba/src/main/resources/assets/nutrition/configs/nutrients/fruit.json

**Comment by leumasme** [comment]
This should be closed since the fixing PR was merged

**Comment by Quarri6343** [comment]
fixed by https://github.com/GTNewHorizons/Nutrition/commit/9367474b71d356b91dce79f66768411c518d8d38 #
