### ISSUE TITLE
[TiC] Traveller's Gloves do not take effect when equipped through the Equipment screen.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15399]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.1

### Your Server

Private SMP

### Java Version

Client Java 21, server unknown

### Type of Server

Vanilla Forge

### Your Expectation

Equip Traveller's Gloves from TiC with the Haste modifier. Raise my block breaking speed using bare hands.

### The Reality

Equipping the gloves through the "Equipment" screen (book icon in the inventory screen) does not apply the block breaking bonus.

Equipping gloves in the "diamond armor" (nameless) tab in the inventory works as expected; even though the Equipment screen shows the gloves in the same slot.

Moreover, if I equip the gloves through the "diamond armor" tab, and then remove them through the "equipment" screen, this causes a server/client desync about my block breaking speed.

Both UIs point to the same equipment slot, this is not a "gloves on your feet" moment.

Video demonstrating all of the above:

https://www.dropbox.com/scl/fi/5wwntyjr7wblyh34vno8r/GIxb4q5fLM.mp4?rlkey=8u61fcao54iqg53njwh53bvsq&dl=0

### Your Proposal

Apply or remove the mining speed boost properly, regardless of which UI is used to equip the gloves.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
Another issue with the rpg inventory mod…

Sigh, #14378 really needs to happen.

**Comment by Caedis** [comment]
Will need to be able to import any items that the user has in their TG slots which should be doable since its just NBT on the player
