### ISSUE TITLE
Radon loop does not overclock properly

### ISSUE THREAD

**Issue by RitumsC** [GTNewHorizons/GT-New-Horizons-Modpack#15397]
### Your GTNH Discord Username

e35

### Your Pack Version

2.5.0 (confirmed also on 2.5.1)

### Your Server

N/A

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

LCR should overclock radon recipe when using double hatches.

### The Reality

Running radon LCR recipe with 2 MV energy hatches doesn't overclock the recipe. 

Namely, it runs at exactly the same power and speed as it did with single energy hatch (28eu/t, 4x7eu/t, as base recipe would expect for mv power).

Also confirmed it doesn't overclock when going from single HV hatch to double HV hatches (uses 112 Eu/t).

Also confirmed on 2.5.1 by other person, discord message link: https://discord.com/channels/181078474394566657/234936569360809996/1199132525449195660

Example of not overclocking:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43823559/bb62ff91-6b01-41bf-a356-7b4a62cdcee4)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43823559/857d0f82-d839-46de-bcee-c779539565c3)

### Your Proposal

Recipe should be properly overclocked.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
can confirm

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/db28322f-5721-43e4-b05c-4f0cee788c99)
this is the recipe. might be related to it being 'ulv'? dont see the issue in the code though.

**Comment by chochem** [comment]
so here is the problem (dont know how to fix it without breaking other stuff though):

this line compares actual voltages instead of full eu/t
https://github.com/GTNewHorizons/GT5-Unofficial/blob/68b5c6598f9373bf7430733647c198e639e7c94f/src/main/java/gregtech/api/util/GT_OverclockCalculator.java#L397
thats the issue, that limits the ocs to just 1 here in the  2 MV energy hatch setup.
