### ISSUE TITLE
Correct parenthesization on loading screen

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15395]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

The operator || is undefined for the argument type(s) int, boolean

### The Reality

![](https://i.imgur.com/3Qo7FQx.png)

### Your Proposal

`((MultiMC | Prism) > Curse) && (Technic > Curse) : true`

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@AbdielKavash feel free to change it https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/Betterloadingscreen/tips/en_US.txt
