### ISSUE TITLE
Nutrition mod breaks tin cans

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#15402]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.5.1

### Your Server

private

### Java Version

Java 21

### Type of Server

None

### Your Expectation

The tin cans should also fill up the nutrition value or send it to a fixed value.

### The Reality

After using tin cans for some time, nutrition will drop to 0% each and stay there.

### Your Proposal

Make tin cans increase nutrition to a value where you don't get debuffs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Graymare** [comment]
Having zero nutrition makes Tin Cans worthless, it would make sense if they worked similarly to the Healing Axe / other auto-feeding options.

**Comment by Dream-Master** [comment]
we need to register tin can as normal food (if possible) and need to add a standard nutrition value on them.
