### ISSUE TITLE
Minor Inconvenience: Quest inconsistencies

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#15405]
### Your GTNH Discord Username

Boldar#1676

### Your Pack Version

2.5.1

### Your Server

private

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Since i have not found a better place, I wan't to collect a few minor quest issues i noticed here. I will continue to collect these minor changes needed here, and if anyone else has some, please comment and i can edit it into the list.

### The Reality

- [x] Quest for Crafting Raw Crystal chip (Crystal Chips, LuV Tab) should expect 72 Exquisite Emeralds for the 8 Molten Europium, not 64.
- [x] The same quest should also not talk about the "Low Gravity" since it got removed
- At least for me the Nq skip was not working. It did trigger the hidden quest, but i still needed to cheat the "Almost success" quest in LuV tab, so i can advance further (Because the Nq Alloy quest depends on it). Maybe i missed some other hidden trigger though, can someone confirm this?

### Your Proposal

Fix these in some future release.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
the second point sounds like a recipe bug, not a quest bug though

**Comment by Savallator** [comment]
I am quite sure the low grav requirement was removed deliberately and the quest was forgotten.

**Comment by chochem** [comment]
no, I checked. looks like it was by accident in a refactor.

**Comment by Savallator** [comment]
Then maybe this should be used to discuss the state of them. People used multis to circumvent it anyway. To have that requirement mean anything I would then propose to actually force people to use the low grav environment at least for some time... maybe make the multi recipe one tier higher, but half the time, so in the end it does not change much, but at the start you need to setup a machine in another dim at least for some time? (And exclude pa, or make it have both recipes) Then it would actually mean something, and it could be the right point  to reference a quest for the quantum ring. To not destroy no-rocket-runs maybe give a 10% chance to succeed without kow grav.
Just a few ideas, because right now I think that mechanic is boring, because it does not matter anyways.

**Comment by chochem** [comment]
just tested: nq skip works for fine. 'Almost success' is exactly the one you get.

**Comment by chochem** [comment]
I guess that were all of them
