### ISSUE TITLE
Show empty oil fields in the JourneyMap overlay.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15400]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.5.1

### Your Proposal

Some oil fields have no fluids in them. When the player scans the field by right-clicking bedrock with a handheld prospector's scanner, a message about this is displayed, but the JM overlay does not show anything. It would be nice if the overlay at least showed something like "Empty" or "No fluid", so that the player knows they have already scanned that field and don't need to scan it again in the future.

### Your Goal

QoL

### Your Vision

QoL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by desagas** [comment]
I would love to see the same for ores. Otherwise, I have to make 1000 waypoints to say "nothing."
