### ISSUE TITLE
Large fluid cells has a weird texture

### ISSUE THREAD

**Issue by skinke17** [GTNewHorizons/GT-New-Horizons-Modpack#15407]
### Your GTNH Discord Username

sJ (canyoushootme)

### Your Pack Version

2.6.0-nightly-2024-01-23

### Your Server

private server

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

All of the large fluid cells (aluminium, titanium, stainless steel, etc) has a weird texture whenever they're filled with any gas/liquid

![billede](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/144228003/6c384e7d-1dad-418a-b6ef-482787a99ba7)

![billede](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/144228003/b0537a44-066e-4d55-a791-38df48488d2f)

### The Reality

The large fluid cells has a weird texture whenever they're filled with any gas/liquid

### Your Proposal

Probably just a bug

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
Oil from BC looks like Glass texture.

**Comment by chochem** [comment]
see also https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15355
not quite sure if you both mean the same thing.

**Comment by DarkAhri** [comment]
#15308

**Comment by UltraHex** [comment]
Fixed by GTNewHorizons/GT5-Unofficial#2476
