### ISSUE TITLE
Better Questing in general crashes after using /bq_admin default load, trying to recover from a config reset causes missing quests, spontaneous crashing issue.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#15416]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Opening the "Search" within the Quest Menu in the LV page.

This just started happening today, did not have this issue previously using the same list of mods. World was created within 2.5.1, so no it didn't come from updating.

### Crash Report

https://mclo.gs/4kVIkf0

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by PlayfulPiano** [comment]
Edit: tried on a previously made creative test world, crashed when clicking any button. 

In a completely new world it crashes when opening up the quest menu entirely.

**Comment by PlayfulPiano** [comment]
https://mclo.gs/Iyk3Rap for the new crash

**Comment by PlayfulPiano** [comment]
fresh installation carrying over some of my save data, also still crashes.
https://mclo.gs/G5boKqv

**Comment by bombcar** [comment]
`java.lang.NullPointerException: Cannot invoke "betterquesting.api.questing.IQuest.isComplete(java.util.UUID)" because "quest" is null`

your player quest completed database is corrupt. Not sure what can be done to fix it, but maybe we can at least capture this error

**Comment by PlayfulPiano** [comment]
> `java.lang.NullPointerException: Cannot invoke "betterquesting.api.questing.IQuest.isComplete(java.util.UUID)" because "quest" is null`
> 
> your player quest completed database is corrupt. Not sure what can be done to fix it, but maybe we can at least capture this error

I can send over my folders that had the corrupted instances at least.

I just finished giving myself all the quests I completed historically from a fresh book and have no crash issues now, so it's def independently just BQ being the issue here (no world issues as far as I can tell).

Tell me which files I need to send over.

**Comment by PlayfulPiano** [comment]
[backup bq.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14059942/backup.bq.zip)

Here's my save data for betterquesting that had the crash. Of note, you should be able to reproduce the crash issue with a clean instance by just loading in this save data and then doing /bq_admin default load.

I've had it crash just from a clean installation and fresh config setup using only my save data and that was enough to trigger the crash.
