### ISSUE TITLE
Change bronze thermal boiler output 

### ISSUE THREAD

**Issue by LionEl-johnson14** [GTNewHorizons/GT-New-Horizons-Modpack#15412]
### Your GTNH Discord Username

lion_eljonson14

### Your Pack Version

2.4.0

### Your Proposal

Currently, using poehoehoe lava in a thermal boiler with a lava filter, the resultant bronze nugget that can be is output is the Tinker's Construct nugget rather than the Gregtech nugget. I would like the nugget to be made into the GT variant

### Your Goal

The nuggets cannot be alloy smelted, macerated, or used except in the tinkers smeltery (which should be unused at the point where the thermal boiler is available) or as essentia, and accessing the tin and copper in that nugget could be useful.

### Your Vision

It would give the thermal boiler a more viable usage and allow for easier access to tin and copper, which are materials needed for circuit crafting.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ethryan** [comment]
Have you tested this in 2.5.1?
