### ISSUE TITLE
naquadah/samarium/cerium line can be skipped in 2.5.1

### ISSUE THREAD

**Issue by comet13579** [GTNewHorizons/GT-New-Horizons-Modpack#15411]
### Your GTNH Discord Username

Comet13579

### Your Pack Version

2.5.1

### Your Server

own server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Simple washer should be giving out that (enriched)naquadah/naquadria oxide mixture dust

### The Reality

The simple washer would give out the purified form directly shown in NEI. The enriched naq/naquadria has the same problem as well but not pasted here
![2024-01-25_04 26 52](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/67854955/97ee602d-7d8a-443d-b49b-30b5e7a6c064)
This is the Samarium line
![2024-01-25_04 42 09](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/67854955/1b3e4ac0-0878-49cc-a06b-d27a5c72fa62)
This is the Cerium line
![2024-01-25_04 42 23](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/67854955/3bdfaca2-9b1f-4b43-8ee5-c1a05f358a4f)

### Your Proposal

change the simple washer recipe back to its oxide mixture dust /ore concentrate dust/rich mixture dust instead of the purified form

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
fixed in [https://github.com/GTNewHorizons/GoodGenerator/pull/229](https://github.com/GTNewHorizons/GoodGenerator/pull/229) and [https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/80](https://github.com/GTNewHorizons/GTNH-Lanthanides/pull/80)
