### ISSUE TITLE
Carpenter Blocks considered Connected Tree Blocks for Lumber Axe

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#15417]
### Your GTNH Discord Username

Desagas

### Your Pack Version

2.5.1+322

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Carpenter blocks would not be destroyed in mass when accidentally cutting down a tree directly beside them. It would then not destroy a line of 60 blocks long and 30 blocks tall worth of carpenter blocks.

### The Reality

It does, it considers carpenter blocks (mine were filled with log materials) as valid parts of a tree when a real tree becomes connect, directly or diagonally to them. I don't know what the search rules are for the TC Lumber axe, but it destroyed hundreds of carpenter blocks that were connected.

I am unsure if this would be the same for all carpenter blocks, or just those filled with logs, where an axe is the required tool.

### Your Proposal

Remove carpenter blocks from list of valid tree blocks in the TC lumber axe list.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by QuantumBlink1337** [comment]
To my knowledge, Carpenter's Blocks takes on the material type of whatever block is in it. E.g concrete takes a pickaxe to break.

**Comment by QuantumBlink1337** [comment]
I can second the issue however - stone Carpenter's blocks are also able to be 3x3 removed.
