### ISSUE TITLE
non-bulk roasted copper EBF recipe should have circuit requirement

### ISSUE THREAD

**Issue by Redmountain0** [GTNewHorizons/GT-New-Horizons-Modpack#15414]
### Your GTNH Discord Username

rM (csin_)

### Your Pack Version

2.5.1

### Your Proposal

non-bulk roasted copper EBF recipe should have circuit requirement. (maybe 1)

### Your Goal

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/65642577/ea46b3db-63ea-4ead-88e1-6ee06cb3e7a8)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/65642577/372a45c7-0a45-4825-ac5f-454b91eb94e2)

first recipe is more effecient on quartzite usage. But it can easily disrupted by the second one. because it has no circuit requirement so it can be activated even when **circuit is set to 4**.

### Your Vision

It can remove unnecessary quartzite usage and AE2 stoppage arising from that.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
already overhauled and fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2445 and https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/791
