### ISSUE TITLE
Problem with Chisel/Gregtech 6

### ISSUE THREAD

**Issue by VadimFlex** [GTNewHorizons/GT-New-Horizons-Modpack#15424]
### Your Pack Version

No pack, chisel 2.13.4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Normal crafting of glass and glass panels from chisels, as well as their color options.

### The Reality

GT6 spoils the crafting. The developer says this is a chisel problem. I note that the problem is also present in the official version of chisel.
![2024-01-26_00 37 35](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132595752/5464ac6f-a88d-46e1-973b-d5b13e76ec65)
![2024-01-26_00 37 37](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132595752/76a3853e-cd2c-4a72-88bd-c7f25c8e6986)
![2024-01-26_00 37 40](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132595752/8bd7f549-4bf7-418e-b5a4-a90e85f32467)
![2024-01-26_00 37 43](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132595752/b03c3362-662e-47d3-8b25-b811b45e20ec)
Without GT6, crafting becomes normal.

![2024-01-26_00 25 32](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132595752/acf1cb2e-cc8d-4556-b44f-e59f450ebaca)
![2024-01-26_00 25 38](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132595752/e5535079-f8b3-4eef-ba6a-aaef237f258a)
![2024-01-26_00 25 43](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132595752/cdffd593-f0e9-44a7-875f-1b3deda8079d)
![2024-01-26_00 25 47](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132595752/ba490f9c-1120-4662-93d1-6c2513e6599b)

The gt6 version doesn't matter. This is a long-standing problem. The problem is not only in the correct display. In fact, sometimes there is a discrepancy between what chisel shows and what the block actually is. These problems do not only occur with glass (requires additional testing).
Link to my topic: https://forum.mechaenetia.com/t/problem-with-chisel/3032
A similar topic: https://forum.mechaenetia.com/t/two-problems-about-gt6-chisel-and-mekanism/2203

### Your Proposal

Solve the gt6 compatibility issue. If possible, add gt6 block support to chisel to create decorative blocks. If my topic needed to be started elsewhere, please tell me about it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SmollKaliberr** [comment]
I've just seen that now. It's just that Greg adds the ore:glass oredict. If you could change the one chisel uses to ore:blockGlass and ore:paneGlass, it would work beautifully.
