### ISSUE TITLE
QoL improvement for updating AE2 patterns with circuits

### ISSUE THREAD

**Issue by RitumsC** [GTNewHorizons/GT-New-Horizons-Modpack#15425]
### Your GTNH Discord Username

e35

### Your Pack Version

2.5.0

### Your Proposal

Add a craftable "any TIER circuit" circuit that can be many from any TIER circuit.

### Your Goal

When upgrading circuits, switching them involves changing numerous patterns, which is needlessly tedious.

Instead, add an option to make one "any TIER circuit" crafting recipe that can be used to define a single pattern that can be replaced as needed, thus reducing the number of overall needed pattern changes.

### Your Vision

One of the possible implementations is proposed in ticket #14607. From discord #mod-dev discussions, I understand that the problem with this implementation is that those are supposed to be NEI-exclusive.

Therefore, possible alternatives I can imagine are:

1. Introducing, similarly to one-time tools, a "one-time TIER circuit".
2. Introducing "crafting TIER circuit" that can partially reuse the NEI any-tier circuit textures.
3. Using the NEI-exclusive any-tier circuits and changing their purpose. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Divran** [comment]
For this to be balanced, you would have to block the "any circuit" item from being used to craft other circuits. Otherwise you could skip the recursion requirement of certain circuit recipes which would make them cheaper than they were meant to be.

Other than this one minor point, I 100% support this feature.

**Comment by LazyFleshWasTaken** [comment]
I too 100% supprot this feature. Also, circuit lines are already non-oredicted, except iv mainframe for some reason, so adding the conversion should be trivial. There's already an item for it too.
