### ISSUE TITLE
Energy Packets Bugged?

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#15423]
### Your GTNH Discord Username

Desagas

### Your Pack Version

2.5.1+327

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

First noticed in 322: World has to be restarted, diodes are not receiving full amps from transformers, or transformers directly from generators? Something along those lines. Or, machines are not asking for as much as a diode or the others should be able to send., OR, lossless cables are actually losing??

Oh, yeah, one of the machines is not getting a constant supply of power, and is stopping. With the scanner, I can accurately see that power going down. Sometimes it is the machine at one end that dies, sometimes it is the one at the other end of the line, which means, it does not matter how far the cable has to send power. The diode is not maintaining its power, neither, not consistently, and or the cable is not sending a full 8 amps or the machine is not requesting what it needs accurately.

### The Reality

Duplicate my set up, please: 1 Turbo Centrifuge directly into a Medium Voltage Transformer directly into a Hi-Amp Low Voltage Transformer directly into 2 8amp LV Diodes, using 8 lossless redstone alloy cables into 8 centrifugues, one centrifuge per cable.

### Your Proposal

This only just started happening as of 322, and persists to 327. It actually broke my entire power system, as something with the diodes or transformers broke in the update.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
Here is my setup: https://imgur.com/a/NEglkXX

I am processing stone dust, each uses 30eu/t.

**Comment by chochem** [comment]
what is the actual problem? you didnt say. just machines failing from too much loss?

**Comment by desagas** [comment]
Updated, sorry, I had it written, I must have accidently deleted it.

**Comment by chochem** [comment]
isnt the calc 512-8-16-16=472<480=16*30?
no bug, just a bad setup.

**Comment by desagas** [comment]
I knew you would say user error. Quick to pass it too.

Turbo generators generator how much? 512, no? Or is all your documentation in the entire mod?

**Comment by desagas** [comment]
And, it was working perfectly for over 200 hours or world time, until this update. So, stop with your quick dismissiveness, and listen to what is being said, please, for the love of gtnh.

**Comment by desagas** [comment]
Why are you removing 8 and 16 twice?

**Comment by desagas** [comment]
Either way, it worked before these updates. So, it was either broken then, or it is broken now.

**Comment by chochem** [comment]
> Why are you removing 8 and 16 twice?

just regular gt loss. applies to both transformers and diodes

**Comment by desagas** [comment]
So then something in the update caused it to suddenly start applying? Or was it not applying previously, when it should have been?

**Comment by StaffiX** [comment]
512 (hv gen)- 8 (hv to mv transformer loss) - 16 (mv to lv transformer loss) - 16 (diode loss)

**Comment by chochem** [comment]
I am not aware of any change.
