### ISSUE TITLE
TiCon Molten Lead produced by TiCon Smeltery

### ISSUE THREAD

**Issue by ehami** [GTNewHorizons/GT-New-Horizons-Modpack#15422]
### Your GTNH Discord Username

e.hami

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Melting GT Lead Ingot/Dust in TiCon smeltery produces GregTech Molten Lead.

### The Reality

Melting GT Lead Ingot or Dust in TiCon smeltery produces TiCon Molten Lead. This molten lead is basically useless.it is not able to be turned back into Ingots, either with the casting table + ingot form, nor in the fluid solidifier. It also cannot be poured into an Empty Cell to create a molten lead cell.

![2024-01-26_09 54 16](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/14036987/e0b1c259-8e5b-4c1e-ba03-2c7d504e66a3)

### Your Proposal

TiCon smeltery produces GregTech Molten Lead instead of TiCon molten lead.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I am pretty sure these are separate on purpose. To make sure you use GT machines, not ticon smeltery, as you advance

**Comment by AbdielKavash** [comment]
Working as intended, the smeltery produces "impure" fluids, which can't be used in most GT machines. This "encourages" (read: forces) the use of a powered fluid extractor.

Although I think it would be nice for the different fluid versions to be more distinct; for example, call the TiC variant "Impure Molten Lead", or something like this.

**Comment by bombcar** [comment]
Not being able to at least make it back into lead seems abnormal.

**Comment by AbdielKavash** [comment]
You should be able to cast it back into ingots in the TiC casting table using an ingot mold. If this does not work specifically for lead (or some other metal), then that *is* a bug.

**Comment by budak7273** [comment]
This is a bug and not a suggestion, it produces an unusable fluid that can't be cast back into an ingot either

**Comment by chochem** [comment]
what bombcar says might be one yea, but not what it says in the ticket.
