### ISSUE TITLE
Unable to see any recipes in NEI

### ISSUE THREAD

**Issue by Imagine0123** [GTNewHorizons/GT-New-Horizons-Modpack#15428]
### Your GTNH Discord Username

imagination12

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Trying to look at any recipe makes me look at recipe

### The Reality

Trying to look at any recipe makes chatlog say [TIME] [Client thread/INFO]: [CHAT] There was error during loading recipe. Please check log for details. Here are the logs (I assume anyway)
[message.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14072342/message.txt)
Full log 
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14072349/latest.log)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14072347/fml-client-latest.log)
This happens anytime I try to look at any recipe

### Your Proposal

For me to be able to see recipes in NEI.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
Another user had the same problem https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15379

For them deleting the NEI folder in .minecraft/saves worked.

**Comment by Imagine0123** [comment]
Alright it was caused, somehow, by Dynamic Lights and deleting the NEI folder in saves worked like you said.

**Comment by Imagine0123** [comment]
Removing Dynamic Lights somehow resolved the issue

**Comment by chochem** [comment]
just got more confirmation by another user on discord that this is caused by adding 'dynamic lights' mod. as this is not a mod we support I will close this
