### ISSUE TITLE
Obscure startup crash involving OpenSecurity

### ISSUE THREAD

**Issue by divine-ray** [GTNewHorizons/GT-New-Horizons-Modpack#15421]
### Your GTNH Discord Username

divine_ray

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

The game enters a state of suspense/not responding, whilst producing a crash, after the loading bar hits 33% (Hunger Overhaul). Scrolling up the log output shows that all OpenComputers addons failed to initialise due to a error in OpenComputers. 
So far the only fix i found to this was to delete the config of OC and to try again, which typically works. 
Note that this issue only occurs after closing down prism completely or changing mods. 

(I haven't tried if this issue exists with nightly builds of OC due to not wanting to update the server for me and clients)

### Crash Report

https://mclo.gs/OXWGNFp

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
hmm, does this still happen with OpenSecuritiy 1.1.1-GTNH? It almost looks like someone potentially fixed this by moving recipes from preinit to init.

**Comment by chochem** [comment]
but yea, maybe that is just by chance and your config file is corrupted as the error suggests. Have you tried what it says?
`Error parsing configuration file. To restore defaults, delete 'OpenComputers.cfg' and restart the game.`

**Comment by divine-ray** [comment]
I have to delete the opencomputers.cfg file every startup in which configuration or mods changed.

**Comment by bombcar** [comment]
> I have to delete the opencomputers.cfg file every startup in which configuration or mods changed.

I swear there is/was a bug with opencomputer configfiles that I either investigated .... or tried to fix

yeah it's https://github.com/GTNewHorizons/OpenComputers/pull/114 - but that's post 2.5.1

Maybe that fix would fix your issue?

**Comment by glowredman** [comment]
Did you just update or were you running 2.5.1 for a while? If you just updated, which version did you play on before? Seems to be similar to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14364. in that case, the solution would be:
1. Go to the root directory of the modpack
2. Open `localconfig.cfg`
3. Remove the line which starts with `OpenComputers.cfg/opencomputers.client/*:nanomachineHudPos=`

**Comment by divine-ray** [comment]
i've been running 2.5.1 since about mid december-ish, but fiddled with various extra mods (JM unlimited, worldedit, JEC, etc.) since then
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29178731/ec6ee5d6-df42-4385-bf2c-dd5e949f0922)
my localconfig.cfg file; no nanomachineHudPos to be seen. 

https://mclo.gs/ek2zcAa here's a crash log of such incident, in case that it is relevant
