### ISSUE TITLE
Compact fusion mk IV does not receive energy with 32 UHV energy hatches

### ISSUE THREAD

**Issue by RitumsC** [GTNewHorizons/GT-New-Horizons-Modpack#15436]
### Your GTNH Discord Username

e35

### Your Pack Version

2.5.0 (confirmed also on 2.5.1)

### Your Server

Private MP

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Fusion reactor should properly receive energy and work when powered with 32 UHV energy hatches.

### The Reality

When the compact fusion reactor has 32 UHV energy hatch and all are powered, the stored energy always remains 0:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43823559/86036be2-9e55-49c0-833d-29189806e6ec)
When starting a recipe it shows non-sensical numbers:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43823559/46679bbc-d3c5-4a79-832f-e8b3d9e8cf5c)

Upon changing one of the energy hatches to 64A UHV energy hatch, the fusion reactor properly receives energy:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43823559/ab998aae-900e-4e06-9686-a04530248f2f)

Another report of the same bug in discord of it happening in epsilon server:  https://discord.com/channels/181078474394566657/234936569360809996/1200571713084198953

### Your Proposal

The fusion reactor should properly receive energy.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
should never use 2A uhv energy hatches on this. you will always get a power failure since they cannot meet the recipe requirement
