### ISSUE TITLE
DTPFs do not use any power

### ISSUE THREAD

**Issue by Jocroy** [GTNewHorizons/GT-New-Horizons-Modpack#15431]
### Your Pack Version

2.5.1

### Your Server

Eta

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

DTPFs should use power and power fail if not connected to a power source.

### The Reality

In the attached screenshot, you can see the DTPF happily running with a disconnected laser. It has no other energy hatches. But even with a connected energy hatch, it does not seem to consume any power either. This one uses a 4kA UHV laser, but I also tried other ones.

![2024-01-27_20 51 32](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40837644/d75e12b7-deb8-4503-a374-350bc4b171d7)

### Your Proposal

Make it consume power.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Divran** [comment]
maybe related? <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15364>
