### ISSUE TITLE
Make Spray Can "chaining" stop when it encounters a different type of block

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#15434]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.5.1

### Your Proposal

Have the Spray Can chained/sneaking mode stop when it encounters a different block than was targeted for the initial spray.

For example: If you are spraying an AE2 cable, it should stop chaining the spray upon reaching a different block.

### Your Goal

This will make the chain mechanism more useful and intuitive, as well as prevent "overspray".  An example of annoying overspray which went on for 256 blocks:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/24d050fb-2187-4acf-8ae5-b8e2439e311f)

The Hex blocks I am using support being colored, but this has happened with other people for example when a wire/cable turns and a different wire/cable starts.

### Your Vision

Reduces accidents and makes the the spray cans even easier to work with.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Caedis** [comment]
Already fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2478
