### ISSUE TITLE
New ME interface terminal doesn't predictably sort interfaces

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#15435]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.5.1

### Your Server

Delta

### Java Version

Java 17

### Type of Server

Thermos

### Your Expectation

In all versions up to 2.4.0, the order in which ME interfaces with the same name name show up was consistent across restarts. This allows you to group your recipes and be able to find them, as well as allowing one a good inventory of what's in your system, what's not, and to predict in advance when to craft more interfaces/molecular assemblers.

### The Reality

Since 2.5.0, interfaces are no longer in a stable order, and changes after each restart.

### Your Proposal

Please restore said functionality. It doesn't need to be exactly the same order as before, as long as it's predictable, like sorting on {name,x,y,z,facing} instead of just name

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
I second this, this is especially annoying for molecular assemblers, where I would like to have recipes grouped logically in the terminal, and there is no easy way to distinguish recipe "groups" (for example, by machine, or circuit setting, etc.)
