### ISSUE TITLE
Vajra's right-click can break RandomThings's Spectral Blocks

### ISSUE THREAD

**Issue by emveevme** [GTNewHorizons/GT-New-Horizons-Modpack#15439]
### Your GTNH Discord Username

has_problems, FluorineQueen

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

I went to the Spectral Dimension from Random Things, right-clicked the wall for some reason, and was rewarded with a free void dimension and unbreakable blocks. You can re-place and break the spectral blocks, which I believe are supposed to behave like bedrock.

The two cropped screenshots were from another user on another discord, figured it was worth including.

![2024-01-28_17 11 45](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142725474/8a384e0e-6429-47b1-bd3a-c7aaa2c51492)
![2024-01-28_17 11 49](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142725474/68157ca6-2f15-441d-ac6c-4e324a73524d)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142725474/c9e99b91-fb5c-4ec7-93d1-67bf07971d8a)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142725474/6415533e-1cd0-4d4e-be3e-3af3ca9006b2)

### The Reality

nothing, i.e. these blocks should behave like bedrock and do nothing when right-clicked. 

### Your Proposal

I know the Vajra's right-click had some interesting behavior that was mostly fixed with 2.5.0, but looks like there's still at least one case where this is can be used in presumably unintended ways.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by emveevme** [comment]
Uploaded the wrong screenshot for one them
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142725474/bbfc756a-8142-4940-8186-3c7e2d4bb9a7)

**Comment by Cardinalstars** [comment]
I can confirm this only happens when the Vajra has silk-touch mode enabled.
