### ISSUE TITLE
Inconsistent formation of compact fusion reactors with stocking input hatches

### ISSUE THREAD

**Issue by RitumsC** [GTNewHorizons/GT-New-Horizons-Modpack#15437]
### Your GTNH Discord Username

e35

### Your Pack Version

2.5.0

### Your Server

Personal MP

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Compact fusion reactors should consistently form/not form with stocking input hatches.

### The Reality

Mk III reactor forms with stocking input hatch.

Mk IV reactor does not form with stocking input hatch.

### Your Proposal

The structure of compact fusion reactors should be consistent.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
Stocking input hatches are UV hatches, while compact fusion mk4 requires UHV or higher.

**Comment by RitumsC** [comment]
This could be made more clear in the tooltip of the hatch then, as it is not clear what defines the hatch tier.

Also, this is confusing because the output hatch (ME) works perfectly on both compacts.

**Comment by HoleFish** [comment]
the tier (for structure check) of ME output hatch is 14. maybe we can do the same thing to ME input hatches

**Comment by GDCloudstrike** [comment]
I'd argue we should rather go with the tooltip update because the higher tier stocking hatch exists, which does work on mkIV and V compacts and is achievable by the time you can make these multis

**Comment by HoleFish** [comment]
I don't think so: Crafting Input Buffers are LuV hatches.

**Comment by GDCloudstrike** [comment]
the fluid version is not an luv hatch, it is gated by spacetime and the item version is worthless on compact fusions as they do not take item inputs

**Comment by HoleFish** [comment]
I mean this is how it's written in the code: buffer is still a tier 6 hatch. Compact fusions form with it just because I intentionally don't apply tier check to it

**Comment by GDCloudstrike** [comment]
> I mean this is how it's written in the code: buffer is still a tier 6 hatch. Compact fusions form with it just because I intentionally don't apply tier check to it

yeah that makes sense, what I'm trying to argue here is that it's fine for the buffer to work on all compacts because it is technically a UIV tier hatch (because of the spacetime gate) even if it isn't defined as such in code. 
Now with the stocking hatch there is a sufficiently high tier variant that works fine, so I dont see how allowing a lower tier to work here makes sense.

**Comment by RitumsC** [comment]
Thanks HoleFish for adding the tooltips!

I will link issue #15180 since it seems that advanced stocking hatches are currently bugged when used for parallelisation with no clear solution; the intended setup, however, works with regular stocking hatches.
