### ISSUE TITLE
Tell players how to move Pam's Harvestcraft gardens

### ISSUE THREAD

**Issue by Tarhalindur** [GTNewHorizons/GT-New-Horizons-Modpack#15432]
### Your GTNH Discord Username

tarhalindur

### Your Pack Version

2.5.1

### Your Proposal

Add something telling players that it's possible to right-click gardens to move them, and that putting a bunch of them near your base can let you get more.

### Your Goal

I didn't know you could do this until I looked at the wiki, because the QB only says you can destroy them for things. This does need an explanation in-game because I shouldn't have to read the wiki to know how game mechanics work.

### Your Vision

New players would be able to take advantage of this mechanic without needing external guidance.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pallinaama** [comment]
If someone could verify that desert gardens actually spawn in 2.5.1, i would appreciate it. Can't seem to find any after hours of flying around in single player.
