### ISSUE TITLE
Distillation Tower Shuts Off w Distilled Water w High Voltage?

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#15433]
### Your GTNH Discord Username

Desagas

### Your Pack Version

2.5.1+322

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

A distillation tower at any tier should be able to process distilled water from water.

With OC, 1024 EU should run at .8 seconds, as described below.

### The Reality

I have two hv energy hatches, 2 hv output hatches, 1 hv input hatch, 1 maintenance hatch, and the controller. The rest are casings. Each energy hatch is fed with a single gas turbine gas turbine, so, 2 in total.

 BUT ... it runs for maybe .25 seconds, and then makes the sound of no power or problem, and shuts off. It also triggers machine controller covers just the same, shutting that off. Is it considering 1024 as EV (which it is not EV) energy and trying to OC again, but has not enough power to do so? Should it not know its own limits, bahah.

I first noticed in a 2x2 tower setup I had, so, I went to a creative world, set up the multi by itself, tried again, and it is 100% reproducible every time. If I remove an energy hatch, having only 1, it runs just fine, but, you know, .8 seconds is significantly slower than .4 seconds in GTNH. Further, at a full EV hatch and turbine, it runs perfectly fine with only a single hatch.

### Your Proposal

Let me make my water. LOL

And, since I know a certain someone in this pack is going to say: you should only have one hatch, or a higher hatch, or more of this or more that ... if this is true, please disallow this multiblock from allowing more than 1 energy hatch, and adjust the documentation to not say "x1+ Energy Hatch." That should be extremely simple to change.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNH-Afx237v7** [comment]
iirc the recipe for water -> distilled water in a distillation tower is 120eu/t. With 2 HV energy hatches it runs at EV voltage which then requires 1,920 eu/t. If you are only providing 2x512= 1,024eu/t (not accounting for any loss) it is simply not enough energy.

**Comment by desagas** [comment]
I knew this modder would claim user error. This is clearly a bug, but whatever.

**Comment by desagas** [comment]
Then, lets talk about the blast furnace ... possibly using 1733us/t, but providing it 2048 ... hmmm, there is a bug there, if what you just said is intended behavior, after all, I am providing it too much ... ugh.

**Comment by chochem** [comment]
not a bug as Afx explained. As you seem to have many questions about the GT eu power system (and it can be quite overwhelming inititally!), I would recommend the discord help channel. the wiki also has a few good pages.

**Comment by desagas** [comment]
Hello, do you not know your own code? The distillation tower does not!!! run two amps per energy hatch ... therefore, 2 energy hatches is 1024 EU/t, and not the flippant answer of "it is 1920eu/t.

But, of course ... call it user error, rather than taking two seconds to recognize a bug.

**Comment by desagas** [comment]
> not a bug as Afx explained. As you seem to have many questions about the GT eu power system (and it can be quite overwhelming inititally!), I would recommend the discord help channel. the wiki also has a few good pages.

I was pointing out a bug ... I did not have question about the power system ... DTs accept only a single amp per hatch, not two, you should know that. Therefore, 1024 is the amperage, not 1920 as stated. This shows in the waila display, in the internal display, and in documentation ... if that is in correct, it is still a bug, because it is inaccurate to how it is actually working.

I overly use the wiki, and when things do not match, I search the discord, and when I can not find it there, I post it as a bug, here.

**Comment by desagas** [comment]
Strange ... and, yet, fermented biomass ran through it at the EXACT same voltage works perfectly with 2 HV energy hatches. But, I digress, just user error.

**Comment by srdr2k3** [comment]
I just ran the fermented biomass recipe with your setup as provided and it runs out of power as it normally should 
(Provided EU/t = 1024 / Needed EU/t = 1920). 
Are you sure you are not using a different setup?
You are using 2 HV energy hatches, which means the machine will try to overclock an MV recipe **twice** to EV (Base EU -> 4x -> 4x)

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/99605300/d16c59d6-1d64-4446-8034-c7fb5c133fce

**Comment by desagas** [comment]
In 331 femernted biomass does not stop with two energy hatches. Not even once in four hours of building.

**Comment by desagas** [comment]
Did you not read my report? It clearly states 2 hv energy hatches.

**Comment by desagas** [comment]
You know what, I’ll just record a video of it and post it explaining how you are all calling it user error when two identical setups running two identical voltages, where one fails and one does not.

Clearly, again, a bug.

Message ID: ***@***.***>

I’ll post a link to the YouTube video once I have it posted.

**Comment by desagas** [comment]
User error: In my setup, I have 2x2 towers, I accidently put energy hatches in the middle, rather than moving them to the edge, this meant that it had four energy hatches feeding energy at once. with another turned off. That explains a lot.

Thank you for the video. What texture/shader packs are you using?

> I just ran the fermented biomass recipe with your setup as provided and it runs out of power as it normally should (Provided EU/t = 1024 / Needed EU/t = 1920). Are you sure you are not using a different setup? You are using 2 HV energy hatches, which means the machine will try to overclock an MV recipe **twice** to EV (Base EU -> 4x -> 4x)
