### ISSUE TITLE
Switching back to the game caused crashes

### ISSUE THREAD

**Issue by Herminos** [GTNewHorizons/GT-New-Horizons-Modpack#15442]
### Your GTNH Discord Username

herminos666

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Using m1 macbook, zulu jre 21 to play, when i finished looking for information on the browser and switched back to the game, it crashed.
The crashes had happened 3 times today, all of them happened when i switched the game to other program  or reverse.

### Crash Report

no ```logs/fml-server-latest.log``` was found, these are the logs ,i thought, may be useful
[2024-01-29-3.log.gz](https://github.com/GT
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14080069/fml-client-latest.log)
NewHorizons/GT-New-Horizons-Modpack/files/14080068/2024-01-29-3.log.gz)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Herminos** [comment]
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000185405c20, pid=72288, tid=10499
#
# JRE version: OpenJDK Runtime Environment Zulu21.30+15-CA (21.0.1+12) (build 21.0.1+12-LTS)
# Java VM: OpenJDK 64-Bit Server VM Zulu21.30+15-CA (21.0.1+12-LTS, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# C  [libobjc.A.dylib+0x9c20]  objc_msgSend+0x20
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Applications/MultiMC.app/Data/instances/GT_New_Horizons_2.5.1_Java_17-21/.minecraft/hs_err_pid72288.log
[1192.065s][warning][os] Loading hsdis library failed
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
That is the ending part of MMC's log.
I am not an expert in Java, but does the log means it's the JRE's fault not the modpack's?

**Comment by Cardinalstars** [comment]
@Herminos 
What additional mods do you have installed? Seems you have at least optifine.

**Comment by Herminos** [comment]
@Cardinalstars 
Optifine,FTB Utilities, NEI Utilities, Veinminer, Twist Space Technology...
But it seems not to be the pack's fault, because when I turned to Zulu's newest Java17, the problem disappeared.
Maybe I need to report the bug to Azul.
By the way, the problem java version is 21.0.1

**Comment by Herminos** [comment]
And this time I was i the main menu, not in the game, and it crashed
