### ISSUE TITLE
Stargate to a new Horizon !

### ISSUE THREAD

**Issue by Rick8484** [GTNewHorizons/GT-New-Horizons-Modpack#15444]
### Your GTNH Discord Username

Rick or idris84

### Your Pack Version

2.5

### Your Proposal

So instead of stargate opens to a another stargate it could open to a new place. But NOT like a new dimension or something (that would be lazy and boring feature). What I think is some kind a beautiful place like Heaven. But nothing exaggerated. 

### Your Goal

I think the endgame-item is not much making anything special. The uses it brings (teleportation) is allready can be achieved with other devices. (or just enderpearls). With this new feature I believe it could make players more motivated to play. 

### Your Vision

It could make the pack more worth to finish it. Why suffer for 5000 to 8000 hours to achive a thing that can be already done with nether portals ? I also believe this new feature could bring more meaning to pack end-goal and maybe also a small story. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment]
Yes, ive been thinking of something like this myself. It is also a good alternative to the end credits that have been in discussion for a while.

**Comment by Herminos** [comment]
I think the stargate's recipe makes it like a universe generator?
so it can send you to a new universe, and in that universe, the world (as well as the other dim) is as same as the original, but the player didn't modify it.
It's like creating a new world by the stargate using the same seed.

**Comment by boubou19** [comment]
The stargate is a meme multi that is used to give a use to the Eye of Harmony, as well as a way for us to see what stuff is poorly adjusted in the endgame balance. Content wise the game stops with the latest tier of the EoH. Also we are not going to change how the gates work because after we will get all the fans to complain here. I'm closing this.
