### ISSUE TITLE
[AE2] Sticky Card does not work with Oredictionary Filter Card

### ISSUE THREAD

**Issue by rentrox4** [GTNewHorizons/GT-New-Horizons-Modpack#15448]
### Your GTNH Discord Username

rentrox_

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

If storage with Sticky Card and Oredictionary Filter Card is full (chest on the left), then Sticky Card will not allow overflow to go elsewhere in the system, even if available (chest on the right).
![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/158158870/dabcbea2-5b4d-4590-a352-181d10e76ce6)

### The Reality

When storage with Sticky Card and Oredictionary Filter Card is full (chest on the left), then overflow ends up in the other available storage (chest on the right).

### Your Proposal

Add interaction with Sticky Card and Oredictionary Filter Card.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cardinalstars** [comment]
I will add this in. I consider it a big.

**Comment by Catastrophica** [comment]
Has this been fixed yet? Experiencing the same issue.
