### ISSUE TITLE
Advanced Panel Extender recipe significantly differs between crafting table and assembler

### ISSUE THREAD

**Issue by karikamiya** [GTNewHorizons/GT-New-Horizons-Modpack#15452]
### Your GTNH Discord Username

ミク

### Your Pack Version

2.5.1

### Your Server

private server and sp

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

The Advanced Panel Extender assembler recipe should be as difficult or easier than the 3x3 recipe.

### The Reality

The Advanced Panel Extender requires an Industrial Panel Extender when it is crafted in a crafting table, but requires an Industrial Information Panel when crafted in the assembler. 

### Your Proposal

Change Advanced Panel Extender assembler recipe to require the Industrial Panel Extender.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
Fixed in dev.

https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/788
