### ISSUE TITLE
Charcoal Pile Igniter Tooltip

### ISSUE THREAD

**Issue by ItzPix3l** [GTNewHorizons/GT-New-Horizons-Modpack#15451]
### Your GTNH Discord Username

_pix3lated

### Your Pack Version

2.5.1 (Stable)

### Your Server

Private server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

When I made a 6-high charcoal pile) I expected it to work since i only counted the air blocks inside. When I made the structure 1 block shorter, it started working. The structure started working at 7 blocks high(counting the top controller+dirt and bottom brick layers). The structure shouldn't have worked at a height of 7 blocks as stated by the tooltip sizes.

### The Reality

The structure started working at 7 blocks high, unlike what the tooltip says.
![Screenshot 2024-01-30 232240](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/111655460/980e7653-0baa-4558-897a-b0f4c043e4fd)

### Your Proposal

The tooltip of the charcoal pile igniter should be changed to between 3-7 blocks high instead of 3-6 blocks.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by dgealow** [comment]
Relatedly: Only blocks within 6 x/z from of the controller actually count, so you must place the igniter dead center if you want a full 11x11 pile. This is also currently not specified.
