### ISSUE TITLE
ME Fluid Level Emitter does not update its state

### ISSUE THREAD

**Issue by Ya9yu** [GTNewHorizons/GT-New-Horizons-Modpack#15462]
### Your GTNH Discord Username

ya9yu

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

ME Fluid Level Emitter should update its state when there is no filter in it, just like ME Level Emitter does

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142943657/a28ca00f-9e04-4912-a33c-08db32438321

### The Reality

ME Fluid Level Emitter updates its state only when you simply click on the filter with an empty hand (re-entering the world updates ME Fluid Level Emitter)

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142943657/a3cb0e08-a202-4e20-a5dd-97ab9360e9b1

### Your Proposal

I want the ME Fluid Level Emitter to update its state just like a regular ME Level Emitter

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mchernykh** [comment]
this issue is relevant for me too
