### ISSUE TITLE
Mouse over multiblock controllers in NEI bookmarks changes Multiblocks Structure preview

### ISSUE THREAD

**Issue by niklasstich** [GTNewHorizons/GT-New-Horizons-Modpack#15464]
### Your GTNH Discord Username

cluuuuub

### Your Pack Version

2.5.1

Mods removed:
- Hardcore Darkness
- Infernal Mobs

Mods added:
- ftblib
- ftbutils

Mods swapped:
- Journeymap Fairplay for Unlimited

### Your Server

Private

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

1. Left-click any controller block (e.g. Maceration Stack Controller) in NEI to open it's crafting recipe
2. Switch to the Multiblocks Structure preview tab
3. The preview of the multiblock you've clicked on appears
4. Mouse over another multiblock controller that's saved to your NEI bookmarks list
5. The preview should stay on the multiblock you've initially clicked on

### The Reality

1. Left-click any controller block (e.g. Maceration Stack Controller) in NEI to open it's crafting recipe
2. Switch to the Multiblocks Structure preview tab
3. The preview of the multiblock you've clicked on appears
4. Mouse over another multiblock controller (e.g. Ore Washing Plant) that's saved to your NEI bookmarks list
5. The preview changes to the multiblock you've just moused over

Seems to happen in both multiplayer and singleplayer for me. I've got some mixed reports of other people being able to reproduce it. Restarted my game once and it continues to happen. For me it seems to happen with the 4 Machines shown in the video, but not with the Industrial Extrusion Machine for example.

See attached video for example. For the record I'm only left-clicking once on the Maceration Stack Controller, after that I'm only hovering with the mouse over the other blocks not clicking.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/32730297/38eedff4-d64a-4165-99d7-1aadc65f4a11

### Your Proposal

Stop preview from switching to the moused over multiblock structure

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
After much testing I have found a way to reproduce this consistently. This happens when you hover over any multiblock that is bookmarked in a way that show the NEI recipe widget.

The widget in question:
![widget](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127234178/9390a2db-11fc-44dc-a540-b9af18f72655)

1. Bookmark atleast two multis from their crafting recipe in order to have the widget shown.
2. View one of their previews. While viewing that hover over the other multi that has been bookmarked.

**Comment by Lyfts** [comment]
It seems to have been fixed by: https://github.com/GTNewHorizons/NotEnoughItems/pull/451
