### ISSUE TITLE
Constant GTNH Lib, Hodgepodge Crash with Terrain Loading/Unloading (Moving around world)

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#15460]
### Your GTNH Discord Username

Desagas

### Your Pack Version

2.5.1+331

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

As I move around, chunks to chunks, the world crashes, not the game. It takes me back to the home screen with a display saying GTNH Lib, Hodgepodge.

This is the generated and saved report.

### Crash Report

 https://mclo.gs/0sOuZKi

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by desagas** [comment]
PS, the instant is not modified in any way, except for tip the scales, and world edit, but, it happens both the same with them added, and without them added, or, vanilla 331. 331 wont even allow Opti-fine to run past the loading screen, not even for a second, or the world will not load.

**Comment by Caedis** [comment]
Known issue, i think a fix is being worked on

**Comment by chochem** [comment]
the optifine part is fixed

**Comment by desagas** [comment]
But, OMG, i do not know what changed, but everything terrain gen runs super fast now.

**Comment by mitchej123** [comment]
This has already been fixed.  He's running `hodgepodge-2.4.17-pre.jar` it was fixed in [2.4.19](https://github.com/GTNewHorizons/Hodgepodge/releases/tag/2.4.19)
