### ISSUE TITLE
Lost the access to drives and patterns behind p2p.

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/GT-New-Horizons-Modpack#15461]
### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

AE works properly.

### The Reality

When I open the terminal, I cannot see items stored in the network, but I can still access patterns through interface terminal.
Disconnecting the power from the network and start it up again can fix it for short time, but when I close the terminal the problem occurs again.
Drives are connected to network properly with ME storage bus and P2P.
When I use a new ME controller to build a new network, I can access my items in that new one.
![071e962c740acb3fae6878544ebff791](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/6374df63-103e-4b63-aba5-7233fde25547)
![1c0099a4e1722f5962262c8e668ea31b](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/89fa667e-e587-4317-9281-9449e3afc4ef)
![18a5c399f30f8722935c6efc5b283e99_720](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/5a6618f5-7668-4768-8b64-6a4aa1e9bf4b)
![70b8b447b57fa498c87082fe0aeadcd3](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/e685d442-a6f3-4884-bf56-747c71f0d125)
![4014d684a9f73543f59b453f3e552ae5](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/1c08e025-a62a-4eaf-a6a2-2bba83633a46)

This video shows that I cannot access my items after closing the terminal.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/e67ce5be-1430-40a5-b2db-e6168ec0d6fd

The video shows some patterns that doesn't exist in interface terminal are shown in pattern terminal.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/a3600138-95a0-45c1-a8bd-ab6894b5ecc7

Restarting the server can get the problem fixed for a short period of time, but it will happen again after a few minutes.

### Your Proposal

I cannot use AE properly because I cannot access drives that are properly connected to network.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by koiNoCirculation** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/5b61951b-c728-488a-9f2c-7013fd7f0289

**Comment by koiNoCirculation** [comment]
When I try to take out items from network, the item disappears, no matter how many there was. And then after closing the terminal I cannot access them anymore, until I replace the ME Controller.

**Comment by koiNoCirculation** [comment]
Rolling back the whole world solves the problem.

**Comment by chochem** [comment]
sounds like a power problem to me. but hard to say from the distance.

If you are really convinced there is a bug, you will need to try to narrow it down to something small and reproducible or there is nothing that can be done probably.
