### ISSUE TITLE
"Asteroid Outpost" space project did not properly apply recipe discount to the space miner

### ISSUE THREAD

**Issue by iamgqr** [GTNewHorizons/GT-New-Horizons-Modpack#15465]
### Your GTNH Discord Username

StageChan

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 19

### Type of Server

None

### Your Expectation

Built a space project manager for my space elevator, went through the codes and found it may apply a plasma and computation discount to the space mining module, then built an asteroid outpost at kuiper belt. After it finished I expect the space mining module to consule less plasma.

### The Reality

It consumed the same amount of plasma, i.e. 2000 Bismuth plasma at 4x parallel. Breaking and replacing the space mining module did not help.

### Your Proposal

Properly apply the plasma and computation discount.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by 0xAdachi** [comment]
uh does the module even do anything? i cant find anything about it in wiki

**Comment by UltraProdigy** [comment]
> uh does the module even do anything? i cant find anything about it in wiki

This isn't currently a completed feature. We temporarily hid it from NEI for that reason. Hopefully it gets finished in the future.
