### ISSUE TITLE
Spontaneous game crash upon world load

### ISSUE THREAD

**Issue by FormulaGecko** [GTNewHorizons/GT-New-Horizons-Modpack#15469]
### Your GTNH Discord Username

FormulaGecko

### Your Pack Version

2.5.1

### Your Server

sp

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

I just tried to open my world today after logging off the night before and suddenly i can't get into the world. Every time i try to join it i get the same exact crash report, which is linked below. I have managed to get onto the world for brief periods a couple times, but it always crashes again shortly after. I cannot identify what is causing the crash.

### Crash Report

https://mclo.gs/88fCFCu

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by leumasme** [comment]
Could you upload your world file (if this is still reproducable)?
