### ISSUE TITLE
Some crash in relation to NEI's bookmark feature

### ISSUE THREAD

**Issue by divine-ray** [GTNewHorizons/GT-New-Horizons-Modpack#15466]
### Your GTNH Discord Username

divine_ray

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Editing the bookmarks, in this case Simple Catalyst from Blood Magic, crashed the game, caught by bettercrashes.

### Crash Report

https://mclo.gs/2twmirz

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by slprime** [comment]
you use NEI from https://github.com/GTNewHorizons/NotEnoughItems/pull/451 PR?

**Comment by chochem** [comment]
it says 2.5.6-GTNH-pre
so a version of that pr from 3 weeks ago is in there, yes.

**Comment by slprime** [comment]
please update NEI
