### ISSUE TITLE
Suggestion: Add higher tiered variants of the ME Output Bus/Hatch

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#15476]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.5.1

### Your Proposal

Add ways to use direct-to-ME output for items and fluids to the multis that currently cannot use them due to hatch tier restrictions (ex: LFTR, probably others too).
Additional recipes for higher tiered output ME busses/hatches can keep the cost investment that high tier multis have.  For example, an Output Bus (ME LuV) could be crafted from an Output Bus (LuV) + Output Bus (ME).

### Your Goal

Outputting directly to ME is very helpful as a QoL, and it's unfortunate that we lose the ability to do this at higher tier.

Additionally, I suspect it is more performant to have a single TE to handle sending the result to the AE2 system than having 2 that talk to each other.

### Your Vision

This would allow consistent use of direct-to-ME output throughout the rest of the pack once it has been unlocked, and reduce confusion when building multis with hatch tier restrictions.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by HoleFish** [comment]
ME outputs don't have such tier restrictions.

**Comment by norbby42** [comment]
Then perhaps it's specifically an issue with the LFTR - It refused to form with 4 Output Hatch (ME), but formed just fine with 4 Output Hatch (IV).  The LFTR says it requires hatches of tier IV or higher.
