### ISSUE TITLE
EBF Recipe Alumina wrong output

### ISSUE THREAD

**Issue by Executorder** [GTNewHorizons/GT-New-Horizons-Modpack#15470]
### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

EBF melts 10 Alumina + 3 Carbon and produces 4 Aluminum Ingots + 3000L CO²

### The Reality

EBF melts 10 Alumina + 3 Carbon and produces 4 Aluminum Ingots but only gives 150L of CO²

### Your Proposal

change recipe / NEI whatever supposed to be right

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
its a pollution gas. read the muffler tooltip or EBF quest. you just get a percentage based on the tier.

**Comment by Executorder** [comment]
LV Muffler should give 0% tho

**Comment by chochem** [comment]
yea thats correct. that part is fixed in dev
