### ISSUE TITLE
Added a high current Dynamo Hatch for Active Transformer

### ISSUE THREAD

**Issue by kAGuyAk** [GTNewHorizons/GT-New-Horizons-Modpack#15471]
### Your Pack Version

2.5.1

### Your Proposal

added high current Dynamo Hatch for Active Transformer

### Your Goal

The 64A Dynamo Hatch is inconvenient and unattractive when used in Active Transformer，When I want to run very high currents from an active transformer to a large number of machine machines, I always need to put a lot of generator hatches
![QQ截图20240204201225](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/158818662/63b6494f-a887-435b-842a-115e515df595)

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by wagon153** [comment]
Most generators that support multi amp hatches, support lasers. Why are you using multiple dynamo/energy hatches instead of a single laser source/target pair?

**Comment by King65868** [comment]
I’m assuming it’s not for generators, it’s for machines instead since you need a dynamo hatch on the active transformer to get power out

**Comment by kAGuyAk** [comment]
> 我假设它不是用于发电机，而是用于机器，因为您需要在有源变压器上安装发电机舱口才能断电

Yes, I intended for the Active Transformer instead of the generator

**Comment by Hikari1nVoid** [comment]
NO.Laser spam has caused all these cursed numbers in late game recipes, which are still growing exponentionally. Upgrading power hatch to 64+ is just another round of laser spam.
