### ISSUE TITLE
Quest: 2nd half of LFTR Breeding wants wrong variant of Xenon Cell

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#15477]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.5.1

### Your Server

Private Dedicated

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Collecting sparged Xenon from the AE2 system with a cell would complete the quest "Second Half of LFTR Breeding"

### The Reality

The quest does not complete because it wants the GT++ version of the cell, but the BartWorks cell is the default cell for interactions (taking out of AE, fluid canner, picking up out of fluid inventory)

### Your Proposal

Fix the quest criteria

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I guess removing one of the two materials fully might also be an option. Alternatively the quest change.
