### ISSUE TITLE
Thorium Tetrafluoride disambiguation

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#15478]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.5.1

### Your Proposal

Rename one of the Thorium Tetrafluorides to make it less confusing which is which.  Both versions report the same chemical formula, and the GT Material Parts page in NEI confuses them with each other (dust from LFTR version, fluid from Thorium 232 version).

There is also no visible cell for the LFTR version in NEI, but there is an unused BartWorks variant visible.

### Your Goal

There are 2 different versions of Thorium Tetrafluoride in the pack, with _significantly_ different sources and difficulty of obtaining:

1) **Thorium 232 Line**: Created in an LCR with Hydrofluoric Acid and Thorium Hydroxide  (easy to obtain)
2) **LFTR Progression**: Tier 3 LFTR fuel is gated behind Thorium Tetrafluoride, which can only be obtained by operating the LFTR using fuel 1 or 2 and then sparging the outputs for very small amounts

These 2 variants are non-interchangable.

### Your Vision

Having a clear naming distinction between them would prevent confusion and also make it easier to configure AE2 Fluid fixtures (such as Import/Export Bus).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
> Both versions report the same chemical formula

actually different formulas (th232 for gt++) but same name. Unless there is a third variant confusing it even more.

**Comment by norbby42** [comment]
> > Both versions report the same chemical formula
> 
> actually different formulas (th232 for gt++) but same name. Unless there is a third variant confusing it even more.

There is.  It doesn't show up in NEI as a standalone cell, which is part of the confusion aspect:

LFTR variant/no cell in NEI (look at crafting LFTR Fuel 3):
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/38b4474d-dda7-4544-b51b-d1bba9e5e737)

Throium 232 line variant:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/2a137655-f43e-44b5-881d-1dae02fa1bb6)

And the no uses version:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/d5e73a4b-3e86-461a-9287-29a480d89df5)
