### ISSUE TITLE
Suddenly crashed. It says that TiC Toolips and ModularUI may be the cause

### ISSUE THREAD

**Issue by LosuTheGregic** [GTNewHorizons/GT-New-Horizons-Modpack#15489]
### Your GTNH Discord Username

losutheman

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

It was completely random.
I don't know what triggered it.

### Crash Report

[crash-2024-02-06_11.57.24-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14182057/crash-2024-02-06_11.57.24-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
It could be corrupted jar if you're using CurseForge launcher. Try reinstalling modpack or using PrismLauncher.
