### ISSUE TITLE
Fully mature cactus grown on IC2 crops tiles produces tiny cactus which cannot be used to make water

### ISSUE THREAD

**Issue by ccankov** [GTNewHorizons/GT-New-Horizons-Modpack#15480]
### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

The quest book guides players to grow cactus on IC2 crops blocks, suggesting that it can be used to create water. 

### The Reality

Harvesting a fully mature cactus plant on an IC2 crops block yields a tiny cactus, which cannot be turned into cactus juice to fill a water bucket.

### Your Proposal

A fully  mature cactus plant grown on an IC2 crops block should produce a cactus, not a tiny cactus.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by C0bra5** [comment]
This bug has already been addressed by https://github.com/GTNewHorizons/Crops-plus-plus/pull/64. Release 1.6.0 is a drop in replacement for crops++ 2.5.1
