### ISSUE TITLE
SC Steam to Regular Steam conversion ratio

### ISSUE THREAD

**Issue by cleonin** [GTNewHorizons/GT-New-Horizons-Modpack#15483]
### Your GTNH Discord Username

minderbinder

### Your Pack Version

2.5.1

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

In the wiki, the SC Steam:Steam ratio is 1:100, so the math in the calculator should have supported a big number of steam output from the XL SC Turbine.

"In the Supercritical Steam turbine, Supercritical Steam converts to EU and Steam in a 1:100:100 ratio."

### The Reality

It seems that the XL SC Turbine outputs 1 steam unit for every 1 SC steam input unit.  This means the field of XL Steam turbines are unable to get enough to run at more than a double digit EU output, even though the calculator indicated the expected ROI would be 14M eu/t.

### Your Proposal

Update the wiki (https://gtnh.miraheze.org/wiki/The_Fluid_Nuke_Cult%27s_Guide_To_Nuclear_Power#) to 1:1, or change the config (that I was unable to find ...) to match the wiki at 1:100, per above.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
This GitHub is not for the wiki. The wiki is open anybody can change stuff there or post a discussion
