### ISSUE TITLE
Field generator (IV) recept change

### ISSUE THREAD

**Issue by zgggz** [GTNewHorizons/GT-New-Horizons-Modpack#15486]
### Your GTNH Discord Username

ZggZ#7290

### Your Pack Version

2.5.1

### Your Proposal

too much conflicts with another patterns if we have have shared fluid storage.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/64369015/de9bc1e5-c702-488e-9708-2fbd6c951ed1)
For example if we craft LUV field generators we will got IV
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/64369015/97341f17-bd19-488f-9711-cddca7d0dbf9)

### Your Goal

-

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
Sorry, we are not going to change a regular IV recipe because it is inconvenient for someones CoAL setup much later.

**Comment by boubou19** [comment]
And that's the point in CoAL: you have to deal with this difficulty with your automation, so it's a non issue. I'm closing this.

**Comment by Dream-Master** [comment]
We could add a control circuit to these recipes to seperate them.

**Comment by boubou19** [comment]
Not a fan of the idea since this would mean adding circuit to both recipes but the config circuit isn't consumed so you'd have to handle it's extraction/reinsertion, which would be too tedious so you'd end up making separated CoALs, which is also a fix for the current recipes, so i don't think it's a good idea.

**Comment by EnderProyects** [comment]
Then tweak the IV recipe so it use another extra component ( but very cheap)
