### ISSUE TITLE
Allow Industrial Apiary to not void products with item auto-output

### ISSUE THREAD

**Issue by AdolMors** [GTNewHorizons/GT-New-Horizons-Modpack#15487]
### Your Pack Version

2.5.1

### Your Proposal

The iapiary has 9 internal output slots. In reality, only 7 slots are reserved for products, as princess and drones will always take 2 slots. When I noticed eon life does exist, I suspected it is possible to produce more than 7 slots of products. 

Example: Default Rune bee. Eon life (600 bee ticks), fastest production, 30% Mysterious Comb, jubilant 2.5% Rune1 Comb, jubilant 1.3% Rune2 Comb
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/62f38281-4113-44ab-9e20-5691a41e7eeb)
Using Hell emulation and x256 acceleration to reduce the runtime from 24750s to ~97s, the result of running 3 times is as follows:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/78e8a62b-d190-4c04-b8e9-381f86769845)
Now, before this screenshot is made, iapiary actually spit out rune1 and rune2 combs instead in earlier testings. In any case, some products are clearly voided.

### Your Goal

When using item auto-output mode, iapiary will eject all outputs instead of voiding due to the 9 slot limit.

### Your Vision

Using eon life is a definitely a fringe case. However, it means that certain bee traits are to be avoided in iapiary. Also it feels somewhat strange that a single block machine is capable of voiding products.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by aka13-404** [comment]
This makes a lot of multi-product bees unable to produce their combs assuming acceleration and productivity is high enough. For example, I can not produce plutonium combs with blinding+longest combo with luv accelerator and 8x prod.
