### ISSUE TITLE
Rubber Sheets Quest

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#15485]
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

2.5.1

### Your Proposal

Rubber Sheets quest says make a Sheet Mold to make Rubber Sheets. The only recipe in Bronze age that uses a Mold and makes Rubber Sheets is 2 rubber ingots into 1 rubber sheet.
But at this moment we already have a Bronze age Forge Hammer which takes 3 ingots and makes 2 rubber sheets. It doesn't require a mold and makes more. Why then would the quest require a useless mold for an inefficient recipe?

### Your Goal

Make quests up to date and consistent

### Your Vision

Remove the mold requirement from the quest.
Make the quest simply say "Put your rubber bars into the Forge Hammer and get 3 to 2 ratio", that's all.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
that forge hammer recipe is removed again in dev. so this is resolved.
