### ISSUE TITLE
Entering my private dimension in the server crashes

### ISSUE THREAD

**Issue by zeroCNM** [GTNewHorizons/GT-New-Horizons-Modpack#15491]
### Your GTNH Discord Username

zero_cm0126

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

    I just enter the server and send it to my private dimension through the command will crash.,The server is shut down directly.,The client is directly disconnected.,But the strange thing is,I extract my private dimension folder separately into a new archive in stand-alone mode and there will be no problem.,And the folder of my private dimension in the server is extracted from an old local archive and put into the server's new archive.,I won't have any problem loading the old archive on the client side at all.,He only happens in the server. I don't know if it's because I just moved my private dimension to a new save on the server or if some kind of unknown bug was triggered.
    And when I get an error block described in the crash report through the command in the server, I find that I don't crash, there is no problem, the block will disappear after a second when placed on the ground, and the block has no name, only its key name (I don't know if I said that he has the right key name, because I am not proficient in programming), I will put the key name displayed by this block here: tile.floodlights:tileuvLight.name 3662.
    I wonder if it's some kind of glass that I used on the old version of the multi-block machine, but it was deprecated in the new version, the version I played before I went to 2.5.1 was 2.3.3, I didn't play gtnh for almost three months, I don't know what changed, for some reason, I didn't double-check in the old save machine for any missing blocks and machine errors, so I can't be sure what kind of block this glass-like block is in 2.3.3
    I had to start from scratch on my server due to this bug, my previous save had grown to UHV, which made it extremely difficult for me to make this decision, and I hope to fix this bug soon so that I can continue with my old save

### Crash Report

Here's the crash report for my server:https://mclo.gs/CGbAtJB

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Hikari1nVoid** [comment]
Is this really an AE2FC issue instead of Floodlights one...?
