### ISSUE TITLE
The saw eats my logs

### ISSUE THREAD

**Issue by Jaanai-AAM** [GTNewHorizons/GT-New-Horizons-Modpack#15498]
### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When I use a nearly broken saw to transfer my logs to planks, it is expected that few logs should be consumed with my saw breaks down, and the game returns me the rest logs.

### The Reality

However, the rest logs that aren't consumed disappeared. For example, I use a saw with just 1 durability to cut 64 logs, I should get 63 logs and 4 planks, but I just get 4 planks with those logs disappeared.

### Your Proposal

It's not a severe bug, but it's sometimes disgusting.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by p3rsonUnknown** [comment]
I've tested this myself with a saw that had few uses (1%) left and my logs didn't technically disappear, but they mostly got used like I wasn't using a saw. It should cancel the craft when the tool breaks mid-craft so the rest won't be consumed.

**Comment by Jaanai-AAM** [comment]
> I've tested this myself with a saw that had few uses (1%) left and my logs didn't technically disappear, but they mostly got used like I wasn't using a saw. It should cancel the craft when the tool breaks mid-craft so the rest wouldn't be consumed.

I tried it again in creative mode. Indeed the rest logs are consumed is just illusion, they are transferred to 2 planks just like making planks handly. Maybe I count my planks wrongly in my survival game. I think it should be adjusted to that when the saw is broken, stop consuming rest logs.
