### ISSUE TITLE
Renaming an interface from the wireless interface terminal cause client disconnect

### ISSUE THREAD

**Issue by 3jlowes** [GTNewHorizons/GT-New-Horizons-Modpack#15493]
### Your GTNH Discord Username

3jlowes

### Your Pack Version

2.5.1

### Your Server

Dedicated, with serverutilities 2.0.14

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Renaming an interface (or dual interface) from the wireless interface terminal, or universal wireless terminal (interface section) causes client to guaranteed disconnect from server.
upon re-log interface is named.

Hold shift and location button changes to rename

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31297398/b94f6a8d-72f5-4622-a1aa-1e4e41f64dc2)

Was told over at the ae2fc github, where i first reported this, that this is ae2fc GTNH fork and issue was marked not planned.
https://github.com/AE2-UEL/AE2FluidCraft-Rework/issues/140

1.) Attempt to rename interface from interface terminal (can be any name, any characters, or blank)
2.) Client disconnect, interface is named
3.) relog

"I have asked other people and they confirm they also crash by following the exact steps I described above." left unchecked:

I have tried asking in #help channel in discord a few times and other people that gtnh and the people that can help are not using wireless interface terminal and or not on 2.5.1

Can provide more information if needed! thanks!

### Crash Report

[log.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14186923/log.txt)

[16:53:37] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel ae2fc
java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
...

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
Please post the full crash log

**Comment by 3jlowes** [comment]
Full server-latest, Thanks!
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14188784/fml-server-latest.log)

**Comment by Lyfts** [comment]
Fixed by https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/183

Manually updating to https://github.com/GTNewHorizons/AE2FluidCraft-Rework/releases/tag/1.2.4-gtnh might work.

**Comment by 3jlowes** [comment]
Let's fucking gooooo 🥳🥳🥳 thanks so much this was driving me insane I really appreciate it
