### ISSUE TITLE
Change (Nano) Boots of the Meteor

### ISSUE THREAD

**Issue by slyk26** [GTNewHorizons/GT-New-Horizons-Modpack#15492]
### Your GTNH Discord Username

slyk26

### Your Pack Version

2.5.1

### Your Proposal

2 Suggestions regarding the ~~Advanced NanoChestPlate~~ Boots of the Meteor:

1. lower the particle ~~height of the Jetpack engine~~ of the boots. they are literally in your face and you don't see much (even with decreased particle settings). 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/102811034/07dadf91-9f50-4f5c-9ba2-4785ff327659)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/102811034/a6ca3e60-2da7-490e-acce-d58746b4fb17)

realistically it should be around your ~~hip height~~ legs 

2. if you wear the Nano Boots of the Meteor while flying/hovering with the Advanced NanoChestPlate, it will almost always create a   explosion. even if you fly up 3 blocks, spam shift to go down very slowly, you will always create a explosion once you hit the ground.... independent of your velocity

### Your Goal

it is literally unusable if you don't disable all particles and explosion sounds are annoying if you hover around

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AdolMors** [comment]
I am almost certain the fire particles of case 1 come from the meteor boots and has nothing to do with the nano chest plate (it uses electric jetpack and has no particle effects to my understanding).

**Comment by chochem** [comment]
both points seem to be about boots of the meteor, not nanochestplace

**Comment by slyk26** [comment]
updated the initial request based on previous comments

**Comment by rekongstor** [comment]
Maybe it's possible to disable boots abilities with some keybind? Boots of the meteor is slam, maybe jump-dashing. Boots of the comet is ice generation. 
Particles can be disabled in Optifine effects settings for now, but some of my animals are afraid of my boots (some died)

**Comment by Filiz1** [comment]
Boots of the Meteor are best pre-ichor boots, alowing cover a big base in few jumps, also handy for travelling. But this terrible particles, this is what that can't be accepted, especially in howering mode. When you trying to made your setups and can't see anything.
I understand the ideological reason but you can't play with that. Particles are best turned off or at least greatly reduced.
