### ISSUE TITLE
Applied Energistics Quest 'Tools of the Trade', 'Need More Information' Unobtainable

### ISSUE THREAD

**Issue by Wacchi-Lorie** [GTNewHorizons/GT-New-Horizons-Modpack#15494]
### Your GTNH Discord Username

wacchi_lorie

### Your Pack Version

2.5.1

### Your Proposal

'Tools of the Trade' requires 'Need More Information'
'Need More Information' requires '64k Component, Tools of the Trade'
which is a loop, making both quest unobtainable.

'Tools of the Trade' should require 'Storing Your ME Data'

'64k Component' -> AAAAAAAAAAAAAAAAAAAE6A==
'Tools of the Trade' for Network Tool and Network Visualisation Tool -> AAAAAAAAAAAAAAAAAAAJ6Q==
'Need More Information' for Advanced Network Tool -> 5ObFHI5BQ5Oxv0yca7morA==

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/f86f9f81-0e8b-4fea-8d5d-ac27a77a2e62)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/eaeccfbe-cbe5-4fea-a1c4-d3d1c6f0c4bd)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/9e09c9d3-ff07-4650-bdf4-22412a6bccb7)

### Your Goal

Correct the quest requirement

### Your Vision

Those are pretty important ME tools, AE2 learners may ignore these useful tools.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
sounds like you are in 2.5.0
thats fixed in 2.5.1

**Comment by chochem** [comment]
my bad. looks like there is secondary bug here on top of the one that I fixed between 2.5.0 and 2.5.1.
