### ISSUE TITLE
Wooden Form (Brick) stacking wrong when crafted in a Crafting Station.

### ISSUE THREAD

**Issue by p3rsonUnknown** [GTNewHorizons/GT-New-Horizons-Modpack#15495]
### Your GTNH Discord Username

p3rsonUnknown

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Crafted a Wooden Form (Brick) while there's already one that isn't 100% durability in my inventory or a nearby chest. Shouldn't stack with it.

### The Reality

It ends up stacking with the less durability one when shift clicked inside a crafting grid or the craft result box. It looks like this only happens with a full durability one.

### Your Proposal

Full durability Wooden Form (Brick) shouldn't stack with a less durability one (obviously). I've also tested again, but with a vanilla crafting table instead of a crafting station and the vanilla crafting table doesn't have this issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
Can you post a screenshot of the wooden forms?

**Comment by p3rsonUnknown** [comment]
![Desktop Screenshot 2024 02 07 - 07 32 09 61](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/8e8faff9-c6cc-4504-931f-61821dcf6494)
![Desktop Screenshot 2024 02 07 - 07 32 12 15](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/259883df-c08a-449d-97c5-c787c347e324)
![Desktop Screenshot 2024 02 07 - 07 32 16 40](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/b99f59e3-8cdf-40a3-bc9d-ed989ae97d26)

**Comment by p3rsonUnknown** [comment]
It seems like the crafting station is ignoring the numbers after the ( : ) If the crafted item doesn't have them so It just merges It with the others.

**Comment by p3rsonUnknown** [comment]
Resending the screenshots one by one as I wasn't able to display the other 2 after upload

**Comment by p3rsonUnknown** [comment]
![Desktop Screenshot 2024 02 07 - 07 32 09 61](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/0e70b743-466a-4ae0-ae55-09441b68bbda)

**Comment by p3rsonUnknown** [comment]
![Desktop Screenshot 2024 02 07 - 07 32 12 15](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/57b41613-75c8-4540-8631-bc7299785812)

**Comment by p3rsonUnknown** [comment]
![Desktop Screenshot 2024 02 07 - 07 32 16 40](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/2f21ab07-de1d-46b0-bbbc-30f7c7483ebd)
After SHIFT clicking it. They can't be manually merged.
