### ISSUE TITLE
Incorrect NEI recipe for Mass Fabricator

### ISSUE THREAD

**Issue by AdolMors** [GTNewHorizons/GT-New-Horizons-Modpack#15505]
### Your Pack Version

2.5.1

### Your Proposal

This is current state of EV mass fabricator using UUA recipe. 512EU 20s.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/dc5722b6-33bb-4d8b-8775-010e4340af4a)
If the EV recipe is looked up through usage of EV mass fabricator in NEI, it shows 2048EU 20s base, 2048EU 5s UUA.
If the EV recipe is looked up through the EV mass fabricator's progress arrow, it shows 512EU 80s base, 512EU 20s UUA.

### Your Goal

I know that #15209 is about incorrect OC in mass fabricator which should hopefully fix incorrect recipe time. However, if using UUA should make both efficiency and speed only 25% of the base, then I believe the recipe from looking at block usage in NEI does not report the correct EU discount.

### Your Vision

There are two ways to look up a recipe, each giving a different result and are both partially correct. It seems like OC fix should also fix the recipe time, meaning the correct EV recipe using UUA should be 512EU, 5s. It would mean the recipe from block usage does not reflect the correct EU discount from UUA.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
shows the same thing in nightly 363. 2048 eu/t with 5s (UUA) or 20.05s
