### ISSUE TITLE
Steam Compressor consumes the entire bucket for the Snow block recipe

### ISSUE THREAD

**Issue by p3rsonUnknown** [GTNewHorizons/GT-New-Horizons-Modpack#15502]
### Your GTNH Discord Username

p3rsonUnknown

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Put a water bucket into a Steam Compressor to make Snow block, shouldn't consume the bucket.

### The Reality

It just consumes the bucket entirely.

### Your Proposal

I'd understand it being consumed If I used a IC2 Cell, but It shouldn't consume a bucket.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by p3rsonUnknown** [comment]
Extra: If this was intentionally done this way, I'd suggest changing it or just remove the bucket recipe.

**Comment by Dream-Master** [comment]
The compressor has only on output slot, so how it can give two items back ? I would remove this recipe and just only compress snowballs and later make it in the vac freezer as water to ice/snow.

**Comment by p3rsonUnknown** [comment]
Well, alot of recipes require water buckets but they don't eat the bucket with them, so I thought something similar can be implemented for the compressor.

**Comment by AdolMors** [comment]
> The compressor has only on output slot, so how it can give two items back ? I would remove this recipe and just only compress snowballs and later make it in the vac freezer as water to ice/snow.

Vacuum Freezer has recipe to make crushed ice from water, but crushed ice cannot be made into some sort of block form.
