### ISSUE TITLE
All GT machine pages are missing from NEI

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#15506]
### Your GTNH Discord Username

chochem

### Your Pack Version

nightly 340

### Your Server

sp

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

To find all the recipes in NEI.

### The Reality

ALL nei pages related to gt machines are missing.

Example: All the remaining visible uses for an iron ingot are in
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/7a9c78ac-b4b2-4517-bd52-7b5ca481fb32)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/a5d05dfe-7cba-43ed-a3b1-ea8e7096365c)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/e57c322f-737d-40f6-a7a3-360b7bc92474)

the recipes themselves seem to work. just NEI is completely broken.

### Your Proposal

Fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cleptomania** [comment]
Can confirm this is in Nightly 341 as well

**Comment by slprime** [comment]
I tested it in 324 build with latest nei. nei work fine
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31038811/6c3545b7-093c-40b5-b4ea-9a2eefc66d23)

**Comment by slprime** [comment]
339 is ok, 340 and 341 is broken

**Comment by chochem** [comment]
> 339 is ok, 340 and 341 is broken

alright, so:
ae2: 316-pre->316
gg: 0.8.8pre->0.8.9
gt5u: 5.09.45.60->5.09.45.61
Hodgepodge: 2.4.21-pre ->2.4.22-pre
NotEnoughIds: 1.5.5 -> 1.5.7-pre
lwjgl3ify: 1.5.14 -> 2.0.0-alpha-2-snapshot
ServerUtilities: 2.0.15-pre->2.0.17-pre

added: CoreTweaks, Archaicfix

**Comment by slprime** [comment]
> > 339 is ok, 340 and 341 is broken
> 
> alright, so: ae2: 316-pre->316 gg: 0.8.8pre->0.8.9pre gt5u: 5.09.45.60->5.09.45.61 Hodgepodge: 2.4.21-pre ->2.4.22-pre NotEnoughIds: 1.5.5 -> 1.5.7-pre lwjgl3ify: 1.5.14 -> 2.0.0-alpha-2-snapshot ServerUtilities: 2.0.15-pre->2.0.17-pre
> 
> added: CoreTweaks, Archaicfix

Java: 17
build: pure 341

rollback: lwjgl3ify-1.5.14, patches
remove: libraries

And handlers works

**Comment by slprime** [comment]
Wrong lwjgl3ify version
