### ISSUE TITLE
Glass Pane+Glass Block chiseling is inconsistent

### ISSUE THREAD

**Issue by pionoplayer** [GTNewHorizons/GT-New-Horizons-Modpack#15503]
### Your GTNH Discord Username

pionoplayer

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Attempting to make regular glass panes through Chiseling clear glass panes (due to it being more efficient to make panes through smeltery than sawing blocks in half). Should be able to use Chisel to convert from clear glass to regular glass, just like able to do with full blocks.

### The Reality

Only about half of the options for chiseling glass are only accessible from vanilla glass panes, and clear glass panes can't be chiseled at all.

### Your Proposal

Make glass panes Chisel group contain all of the same types that the glass blocks Chisel group does, instead of a bunch only being chiselable as blocks.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by p3rsonUnknown** [comment]
First of all, some glass variants you can chisel don't have a glass pane version at all (They're under the "Chisel" mod btw, you can only paint the glass/glass pane in 1.7.10 vanilla) and If you're trying to get colored glass panes you need a paintbrush and the paint material, then you can use the chisel again to change the glass pattern. **With that said, clear glass panes are can't be chiseled, which should be changed.**

**Comment by chochem** [comment]
this looks very much intended. as 1) the ratios are different and 2) there is an ebf recipe for clear to non-clear
