### ISSUE TITLE
Carbon, Chemically quest should require completion of MV electrolyzer quest

### ISSUE THREAD

**Issue by Earlh21** [GTNewHorizons/GT-New-Horizons-Modpack#15507]
### Your Pack Version

2.5.1

### Your Proposal

My proposal is that the quest should require completion of Electrolyzing All The Things (MV electrolyzer crafting quest).

Or at least change the quest text to mention the MV requirement.

Alternatively, change the sugar electrolysis recipe to work in LV.

### Your Goal

Sugar electrolysis, which is part of the Carbon, Chemically quest (Bio for the Masses tab) for carbon monoxide, requires MV.

Without knowing this, in LV, I set up everything required for automated CO production for power, and I realized it wouldn't work because of the MV requirement I had no idea existed.

The quests for CO even give LV loot bags.

It was frustrating and I ended up cheating for the first time for an MV turbine and machines to replace my LV ones for CO production.

### Your Vision

Players wouldn't be blindsided by the MV requirement.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by isadora-6th** [comment]
Can't you electrolyze dark ashes from steel production for 2 carbon?

**Comment by chochem** [comment]
I mean cheating for that is very silly. but the quests are clearly misplaced.

**Comment by Earlh21** [comment]
> Can't you electrolyze dark ashes from steel production for 2 carbon?

It's not the carbon dust, it's the oxygen that's required for CO production.

**Comment by Dream-Master** [comment]
I don't see an issue here. Most things are not doable in LV. I am myself in late MV going to HV now, and I play the game with no issues. Sure it's possible to mentioned things in a Quest but nei said clear if a thing is lv or mv.

**Comment by Earlh21** [comment]
>I don't see an issue here. Most things are not doable in LV.

Most things are not doable in LV, true. If those things have quests they're typically gated by MV or higher quests and don't give LV quest bags.

Sure, I could have noticed that the recipe requires MV. But I still think this simple questbook change makes the pack better.

**Comment by chochem** [comment]
> I don't see an issue here. Most things are not doable in LV. I am myself in late MV going to HV now, and I play the game with no issues. Sure it's possible to mentioned things in a Quest but nei said clear if a thing is lv or mv.

there is nothing broken. Just that this particular quest to electrolyze sugar opens up in the steam age/LV part of that tab. But the recipe is MV.
Just needs to be move up a bit with slightly different prereq.

> But I still think this simple questbook change makes the pack better.

patience. I dont do daily quest PRs. (and everyone else is even slower typically :P)
