### ISSUE TITLE
Add leaf block recipe

### ISSUE THREAD

**Issue by Logos-Askrson** [GTNewHorizons/GT-New-Horizons-Modpack#15513]
### Your GTNH Discord Username

logos_askrson

### Your Pack Version

2.5.1

### Your Proposal

Add a recipe to the tree growth simulator to obtain leaf blocks from saplings in large quantities.

The way I see it working is that, in place of or in addition to the saw, one could add a shears or branch cutter to the tree growth simulator, and it would then produce leaf blocks corresponding to the provided sapling instead of wood blocks.

### Your Goal

Leaf blocks are great for decoration. Actually getting leaf blocks involves a lot of manual mining and tree growth. This is slow, and if a method is found to make it fast probably won't be great for servers due to the tree growth involved.

### Your Vision

Adding a way to get leaves that doesn't require mass tree growth and block breaking would make leaf blocks more available for decoration work, and thus make large custom trees easier to build. This would generally encourage prettier and more colorful bases.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
It would be nice if the TGS could also produce fruit from Pam's and Forestry (and a couple other) trees.

I'm not sure what the best method of selecting output would be. I personally like different tools for different drops (axe/chainsaw = logs, branch cutter = leaves, ?? = saplings, ?? = fruit?)

**Comment by LazyFleshWasTaken** [comment]
Could do a knife for fruit/nuts, for cutting em down from the tree.
