### ISSUE TITLE
Apimancer's Drainer Update breaks magical apiary item extraction

### ISSUE THREAD

**Issue by RaidhoSketch** [GTNewHorizons/GT-New-Horizons-Modpack#15510]
### Your Pack Version

2.5.1 (tested with GTNH-2024-02-10-342-mmcprism-java8 nightly build)

### Your Server

private server

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Extracting items from Magical Apiary item slots should work.

### The Reality

No methods of item extraction work (bees can still be loaded in);
![2024-02-10_22 55 25](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/73392166/51c2f8ea-73a3-4d4f-9acb-593fb4ed9987)

![2024-02-10_22 55 31](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/73392166/78928bd6-c465-4013-8dfe-24d9438150b3)

Fixed by downgrading to magicbees-2.7.4-GTNH.

### Your Proposal

Correct the bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Quantumlyy** [comment]
This might have been due to my changes. Going to check and report back.

**Comment by Zero-ui9** [comment]
Can confirm, auto extraction is now broken. They will also only input from the top, not the sides as regular apiaries do.

**Comment by RaidhoSketch** [comment]
Oh, you can close it fully, one of the latest magicbees releases fixed it.
