### ISSUE TITLE
LV Cable Diode recipe requires Railcraft Steel Plates

### ISSUE THREAD

**Issue by Mr-Kasugano** [GTNewHorizons/GT-New-Horizons-Modpack#15512]
### Your GTNH Discord Username

mr_kasugano

### Your Pack Version

2.5.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Trying to craft 4A LV Cable Diode using 4x Tin wire, LV Machine Hull, Diodes, and GT Steel Plates.

![image_2024-02-11_121734891](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13224330/189729e1-1382-4557-a947-b84bb8cb294f)

### The Reality

Unable to craft any LV Cable Diode using Tin wires, LV Machine Hull, Diodes, and GT Steel Plates, recipes requires Railcraft Steel Plates which are unobtainable.

![image_2024-02-11_121653785](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13224330/3e730004-e8ae-4705-802b-2fe8deceaad0)

### Your Proposal

Oredict the recipe or correct it to the GregTech steel plates.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
cant reproduce

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/4a60e9e9-e8f3-47a1-8c21-23b7bb79b597)

**Comment by bombcar** [comment]
Railcraft steel plates usually indicates an upgrade error. Make sure that you don’t have a scripts directory with things in it
