### ISSUE TITLE
Thaumic parts give wierd amount of mods

### ISSUE THREAD

**Issue by imTheSupremeOne** [GTNewHorizons/GT-New-Horizons-Modpack#15519]
### Your GTNH Discord Username

imthesupremeone

### Your Pack Version

2.5.1

### Your Server

Private

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

The same parts either don't stack or stack in a logical way

### The Reality

x4 thaumic parts give +2 mods on a fresh axe
x3 thaumic parts give +1 mod
x2 thaumiv parts give 0 mod

We have x2 Thaum parts but 0 modifiers :
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13508453/4fa95346-035b-4688-b4af-79e60a548649)

The x3 Thaum parts give 1 mod : 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13508453/f651dac4-3ac0-44df-9639-657c64c71665)

And x4 gives 2 : 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13508453/bd5d70ff-1fef-417d-8397-08e52b1e8eaa)

The thing that I can't exchange another thaumic part for netherrack may hint onto the reason of this bug : 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13508453/d338a493-c8be-48b7-8db0-57f65d1550b5)

### Your Proposal

Make it intuitive; also the thing that I can't exchange back parts on 2-mod thaumium to 1-mod may hints that there is some bug and modifiers are wasted...

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leumasme** [comment]
Keep open, this is still an issue (nightly 2024-09-24)

https://github.com/user-attachments/assets/538646a3-8857-4591-8d9c-a5e40d879736
