### ISSUE TITLE
Infernal Mobs attacks ignoring FTB Utilities land claims

### ISSUE THREAD

**Issue by Drecondius** [GTNewHorizons/GT-New-Horizons-Modpack#15525]
### Your GTNH Discord Username

Drecondius

### Your Pack Version

2.5.1

### Your Server

Private dedicated

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

 All explosions are supposed to be disabled so no block damage can occur. 

### The Reality

Infernal Mob Skeleton with Explosive arrows destroying base under a claimed area, chests, dirt, stone. it's any skeleton that fires explosive rounds

### Your Proposal

I'm not sure what to propose here as this is multiple mod interactions here. it was acting as if I generated the explosion even though it was an infernal mob skeleton firing arrows at me, destroying blocks. I'm not really sure how we are supposed to go about fixing this. I am open and willing to test proposals. My only gripe is I don't have anything recording to show what happened. I am unsure if it's repeatable unless another mob with the same attack shows up, i'm about to setup a small claim to test with and report back.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
FTBUtilities has been deprecated and will no longer recieve updates. Try replacing it with https://github.com/GTNewHorizons/ServerUtilities and check if it still occurs.

**Comment by Drecondius** [comment]
Ok, server utilities fixes the block destruction but a warning is good, the buttons draw behind potion effects

**Comment by Lyfts** [comment]
Like I told you on discord 10 minutes ago there's a toggle to put them just above the potion label. 

Also they don't draw behind potion labels usually so it's likely some mod on your end causing it. Feel free to open a new ticket regarding that though.
