### ISSUE TITLE
Steam Turbine Putting Out Bad Power

### ISSUE THREAD

**Issue by WaterPasta** [GTNewHorizons/GT-New-Horizons-Modpack#15526]
### Your GTNH Discord Username

waterpasta

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Expectation

The generator should output the appropriate amount of energy from the dynamo, go into the battery buffer, and fill the batteries.

### The Reality

I made a large steam turbine with both a regular and buffered dynamo and different types of turbines. It turns on and everything seems to work, but when the energy goes into the battery buffer, it seems to fill up the buffer but does so very slowly and doesn't go into the batteries. (tooltip shows energy in the buffer but there is no power in the batteries (pictures attached)). I've tried restarting the world, game and my PC. The tooltip shows 127 EU/t (for an HV setup, different for EV) as the average input, and jumps from 0 to that back and forth, regardless of how much steam is being input. Single block generators seem to still work and is able to input power into the buffer with the glitched energy in it.

![2024-02-14_13 33 39](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45742920/de88b9e8-ea0a-4507-843f-a92cc1f6e87f)

![2024-02-14_13 33 42](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45742920/75b0170f-f786-4a15-bf92-3a01040b696a)

### Your Proposal

It should work as expected

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
hmm. they might have some restriction as to incoming voltage. So feeding MV power might not work. Have you tried transforming your mv power to hv?

**Comment by WaterPasta** [comment]
> n

I'm using an HV dynamo feeding power into HV wires and into an HV battery buffer with HV batteries in it. There shouldn't be any MV involved anywhere. I'll also add that I have since tested this on v2.4 of the pack and tested it on Java17 and the issue persists. I'll also also add that after triggering this glitch, it sometimes also applies globally, preventing generators that definitely work to show the same behavior.

**Comment by chochem** [comment]
127 is mv

**Comment by WaterPasta** [comment]
That's the weird part. The HV dynamo is putting out 128, and the EV dynamo is putting out 512. But this doesn't really make sense because the dynamo should be putting out power in proportion to the amount of steam going in up to the maximum EU/t for the power level, not inconsistently dribbling out power equal to one step down in voltage. I could try feeding current from an MV battery buffer into an HV battery buffer to see if that reproduces the bug, but it seems like the Steam Turbine multiblock or the dynamo itself is the problem since everything seems to work fine until I try to run that.

**Comment by WaterPasta** [comment]
I tried the above test and got even stranger results. I fed an MV buffer straight into an HV buffer, and initially the power went in and just sat in the buffer without filling the batteries, but after a few seconds it the batteries started to fill, but only a fraction of the total energy received actually went into the batteries.

Also, I was able to repeat this weird behavior with the large turbine. Also I tried to feed the HV dynamo into an MV->HV transformer before going into the HV buffer, but it just exploded like I thought it would.

Just for laughs, I tried feeding an HV buffer into an HV buffer, and even that wasn't working correctly. I think there's just something broken about the power system in general.

I'm gonna make an entirely fresh install of the pack and see if the issue still exists.

**Comment by chochem** [comment]
ok got to some testing. only bat buffs for now. you would need to provide more details on that steam multi setup.

>  I fed an MV buffer straight into an HV buffer, and initially the power went in and just sat in the buffer without filling the batteries, but after a few seconds it the batteries started to fill, but only a fraction of the total energy received actually went into the batteries.

I tried this and it worked completely fine and as expected. only some small amount of loss as expected. no bugs.
I think you are just confused because you forget about internal buffers.
