### ISSUE TITLE
Dark Clear Glass Does Not Block Light

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#15527]
### Your GTNH Discord Username

Desagas

### Your Pack Version

2.5.1+342

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Dark Clear Glass, as the tooltip suggests, should block light.

### The Reality

The Dark Clear Glass does not block light.

### Your Proposal

Let Dark Clear Glass block light as the tooltip suggests.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment]
Same is true for Dark Fused Quartz, and Dark Glass from Extra Utilities!

**Comment by leumasme** [comment]
Can not confirm on 2.5.1 with OF

Please check if the light level (in info hud top left corner) is properly set to 0; if so, its just a rendering issue and you should check with different graphics settings
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29953391/8eb35953-549c-4363-8027-25409a52762a)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29953391/62ccc12b-94bf-4a8b-8cca-6add5e1039b3)

**Comment by desagas** [comment]
Hmm, sorry for the delay. I tried this multiple times, and a completely fresh install of the pack, and it still happened, with no OF or anything else added. I tried logging off and back on, I tried to remove all light, and then uncover them again, and it still happened. Keep in mind that I am using that included patches and the LWJGL alpha2...6 included with the pack.

As for light level, both the light overlay and the hud both showed light.

I will log on again and try again in the next day or two.

**Comment by desagas** [comment]
It is still happening.

![2024-02-27_19 14 59](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8404632/b9ec30fd-9372-41f0-a2e6-66594f70fbbe)
![2024-02-27_19 14 16](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8404632/67eeaafc-30ba-4dcf-a9eb-fa14eaff6a14)
![2024-02-27_19 14 01](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/8404632/851caca2-4708-4a5b-bb66-8abee4fe71d2)

**Comment by chochem** [comment]
fixed by https://github.com/embeddedt/ArchaicFix/commit/6eaca760d2185b1cd158c4b753844f01885976cd
