### ISSUE TITLE
A fatal error detected by Java Runtime Environment

### ISSUE THREAD

**Issue by EpicPlayzGames** [GTNewHorizons/GT-New-Horizons-Modpack#15522]
### Your GTNH Discord Username

epicplayzgames

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

None

### Your Actions

Seems to happen at random intervals either while actively playing, or upon server startup, after dumping an error to console. Attempted changing startup parameters but doesnt seem to have any effect. Not sure if this is considered an issue due to GTNH or strictly Corretto 21, Gives me different problematic frames each dump.

### Crash Report

fml-server-latest.log 
[https://pastebin.com/ezQ7Js2c](url)

hs_err_pid1.log
[https://pastebin.com/8bXnShT1](url)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by EpicPlayzGames** [comment]
Switched java versions from 21 to 20 just out of curiosity, issue still persists just trying to start the server, so im unsure whats happening

**Comment by bombcar** [comment]
Link didn’t work unless I typed it https://pastebin.com/8bXnShT1

**Comment by EpicPlayzGames** [comment]
Was able to duplicate this effect after copying old world file and visual prospecting data to a new instance, removed old visual prospecting data and kept old world file only, and the server has since been stable and able to start. closing this issue accordingly.
