### ISSUE TITLE
Add Sticky Card support for AE2FC ME Fluid Storage Bus

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#15524]
### Your GTNH Discord Username

skproch

### Your Pack Version

2.5.1

### Your Proposal

Currently AE2 `Sticky Card` don't support AE2FC.  
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29896317/af1f3fed-4995-4210-95ba-a2efb9926dbc)

My proposal to add Sticky Card support for AE2FC `ME Fluid Storage Bus`.

### Your Goal

Currently Sticky Card makes managing items in AE2 a lot simpler and foolproof. I want this feature also added to AE2FC `ME Fluid Storage Bus`. 

### Your Vision

Add support for sticky card in AE2FC `ME Fluid Storage Bus`.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by StaffiX** [comment]
this feature was added via https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/190

**Comment by SKProCH** [comment]
Wow, missed it. Cool! Thanks!

**Comment by SKProCH** [comment]
Hmm, seems like this PR adds it for all fluid storage cells, but not for `Me Fluid Storage Bus`. I've changed PR description to indicate that.
