### ISSUE TITLE
Lava Bucket does not damage the player when put in a Battlegear mod's slot.

### ISSUE THREAD

**Issue by p3rsonUnknown** [GTNewHorizons/GT-New-Horizons-Modpack#15531]
### Your GTNH Discord Username

p3rsonUnknown

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I'm supposed to take damage when I keep a lava bucket that's not in my equipped hand slot (you also need gloves for that).

### The Reality

Battlegear mod's slots do not count as an inventory slot for some reason and I don't take damage from it. I even tried taking the gloves off and It still don't damage me.

### Your Proposal

Why are we allowed to put buckets in the battlegear slots in the first place? I'd suggest removing the ability to put buckets into the battlegear interface If It can't be registered as a "inventory slot".

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by p3rsonUnknown** [comment]
![battlegearissue](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/41a73200-4332-4238-a1e1-bde485004a95)

**Comment by leumasme** [comment]
Can confirm on 2.5.1 with OF and FTBU, which is very odd since it looks like Hazardous Items is coded to specifically account for Mine&Battlegear combat slots:
https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/modhazardousitems/HazardousItemsHandler.java#L402-L425
The `battlegear.changed` messages are *not* in the log.

**Comment by Ableytner** [comment]
On closer inspection, using breakpoints, the code fails on [this line](https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/modhazardousitems/HazardousItemsHandler.java#L407). This results in the battlegear slots not being checked. 
Strangely, the log message is not appearing in the logs.
