### ISSUE TITLE
Duradisplay tanks the memory by abusing streams

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#15532]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12850933/5146b114-b612-408f-8845-54aeb3950be9)
https://github.com/GTNewHorizons/DuraDisplay/blob/76194979b1a97a8a50b81858f8f04eda5ac27af9/src/main/java/com/caedis/duradisplay/overlay/OverlayDurabilityLike.java#L53
https://github.com/GTNewHorizons/DuraDisplay/blob/6eb865747ea90247a38e72947791875ba4993ba1/src/main/java/com/caedis/duradisplay/render/DurabilityRenderer.java#L73

**Comment by Caedis** [comment]
Please make sure you are referencing the master branch

https://github.com/GTNewHorizons/DuraDisplay/blob/master/src/main/java/com/caedis/duradisplay/render/DurabilityRenderer.java#L27 only happens once since its in a static constructor

The other one does need work though
