### ISSUE TITLE
GT++ Extruder outputs wrong amount of NaN-Certificates

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#15530]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Craft the "Certificat of not being a noob anymore" in the GT++ multiblock extruder. Input 128 blocks of neutronium and expect one certificate.

### The Reality

Neutronium blocks are consumed but output two certificates.

### Your Proposal

Seems to be an incorrect calculation of outputs based on two identical input stacks.
_What am I going to do with two certificates? ;)_

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
One crafted, one free!
