### ISSUE TITLE
Crafting tasks cant count correctly

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#15539]
### Your GTNH Discord Username

chochem

### Your Pack Version

nightly 340

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

The count of items in a crafting task should reflect the amount of items crafted.

### The Reality

They cant count correctly.

steps to reproduce:
1) unlock quest 'wired, weird?!', make sure all counts are zero or reset the quest so that they are.
2) put 4 copper plates and a wire cutter in the standard 2x2 inventory crafting grid
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/a24a3a15-b0aa-4a42-87e1-c16082314bae)
3) take copper wires out one by one
4) result: even though just 4 wires were crafted, the quests says 10
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/b02edd2a-00d7-4e14-a6f9-d9bf05a7dfd4)

some testing indicates the 10 is coming from 1+ 2 + 3 + 4. Indeed, doing the same with 6 plates gives 21=1+2+3+4+5+6.

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by dibbydoda** [comment]
This is happening as [forge fires](https://github.com/GTNewHorizons/MinecraftForge/blob/1.7.10/fml/patches/minecraft/net/minecraft/inventory/SlotCrafting.java.patch) the OnItemCrafted event with a reference to the itemstack currently being held by the player. As each wire craft fires the event individually, first it sees you are holding one wire, then two, then three, then four and adds them separately. If you place each wire in your inventory before clicking the next this does not occur. You can test this by crafting one wire but collecting it while holding many more. The amount crafted immediately jumps to the total itemstack.

For the same reason this is why shift clicking returns the amount crafted as 0 (and BQ mod author had to work around this). No items are held by the player at the time the time the event is triggered.

https://github.com/user-attachments/assets/1df3b17d-1393-4ddb-91bc-3cb154464e13
