### ISSUE TITLE
Unknown World Crash

### ISSUE THREAD

**Issue by BladeColdsteel** [GTNewHorizons/GT-New-Horizons-Modpack#15534]
### Your GTNH Discord Username

Blade_Coldsteel

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Open world, on world load crash occurs.

### Crash Report

https://mclo.gs/kkRtFbs

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BladeColdsteel** [comment]
Forgot to add but Optifine is installed on my client, yet up until now, had not been an issue.

**Comment by chochem** [comment]
not much to go on there. please post the full log (fmlclientlatest). Maybe that has something interesting

**Comment by BladeColdsteel** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14302939/fml-client-latest.log)

**Comment by chochem** [comment]
`java.lang.ArrayIndexOutOfBoundsException: -1676
	at net.minecraft.world.chunk.NibbleArray.func_76582_a(SourceFile:26) ~[apv.class:?]
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76665_b(SourceFile:75) ~[apz.class:?]`

looks like corruption. Best use a backup from before.

**Comment by BladeColdsteel** [comment]
So this happened again when I entered the Nether. Here's the crash log: https://mclo.gs/Pfn69EY

Is there something I can do to fix that? Or would it be better to just start a new world?

**Comment by BladeColdsteel** [comment]
I ended up deleting the nether folder and it seems to work fine now, hopefully this will continue to be the case
