### ISSUE TITLE
ME Fluid buffers do not correctly expose their "stored" fluid to subnetworks

### ISSUE THREAD

**Issue by maximeRaoult** [GTNewHorizons/GT-New-Horizons-Modpack#15541]
### Your GTNH Discord Username

thatguycalledmax

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

The subnetwork has access to the fluid in the ME fluid buffer

### The Reality

The subnetwork does not have access to the fluid in the ME fluid buffer
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/71221100/6625b417-0bf2-4f5c-91d1-c92322dfeb1e)
(In picture, yellow network does not display oxygen as an available fluid in a fluid terminal/fluid export bus)

### Your Proposal

The subnetwork should have access to the fluid in the ME fluid buffer

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AdolMors** [comment]
Going by documented info (coming from AE2 Fluid Crafting mod, seems like only https://www.mcmod.cn/item/777485.html has an entry) and some quick testing, I believe the Fluid Buffer is working as intended.

The Fluid Buffer is very similar to the ME Dual Interface's fluid stocking feature, where pipes/conduits/etc can extract stocked fluid from the interface.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/5a85fc65-8117-4e65-9f80-14d7359a326c)
The main difference between the Fluid Buffer and Dual Interface is that the interface has an internal buffer of 16000L while Fluid Buffer has no internal buffer (ironically). The internal buffer reduces the fluid extraction fluid throughput as faster extraction method is used.

The Fluid Buffer seems to be an interface block with the sole purpose of extracting fluid.

**Comment by maximeRaoult** [comment]
I see that makes sense, thanks. 
Unfortunately dual interfaces also do not work in that manner. When trying to use them to stock fluids to a subnet, it always just exposed every fluid rather then just the ones added to the interfaces buffer.
