### ISSUE TITLE
Simple Washer III requires alloy smelter which is IV tier

### ISSUE THREAD

**Issue by infant-crusher** [GTNewHorizons/GT-New-Horizons-Modpack#15552]
### Your GTNH Discord Username

_hairydog

### Your Pack Version

2.5

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Being able to craft the HV Simple Washer at HV

### The Reality

It requires Inconel-625 which in turn requires an Alloy Blast Smelter to produce, which isn't available until IV due to the tungsten requirement

### Your Proposal

add a mixer recipe for Inconel-625 or change the washer recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
this is a more general issue, not just simple washer. in that gt++ classes Inconel-625 as one of its HV materials. should probably be swapped with something else

**Comment by DarkYuan** [comment]
The alloys for the simple washer 1 (Tumbaga), 2 (Eglin Steel), 4 (Incoloy-DS), and even 5 (Nitinol 60) can all be made in the mixer. The Inconel-625 for number 3 just seems out of place. Perhaps it was meant to be **Inconel-792** which is mixable?

Bearing that in mind, I propose one of two changes:
- A mixing recipe for Inconel-625 dust, the simplest fix, adding only one recipe, or
- Swapping the alloys used in recipes for HV and EV GT++ recipes to molten Inconel-792 for the HV and molten Inconel-625 for EV. Possibly also changing the solid materials in their EV upgrades to 792 to follow the same pattern of using the previous tier's metal.
