### ISSUE TITLE
Server Utilities trash can very broken

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#15551]
### Your GTNH Discord Username

chochem

### Your Pack Version

nightly 353 +angelica

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

I have the trashcan turned off in config. it should do anything.

### The Reality

Clicking it gives this flickering GUI
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/2e9e03a4-6258-46a9-9d93-3481e8ca187f)
it also puts an error in chat
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/85dea289-b698-4c0f-8f10-08397289d9c0)

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
I'm guessing this is a nightly config situation since everything is turned off. Turning on "B:trash_can" should fix that.
The button should probably be hidden if the command is turned off though.

**Comment by chochem** [comment]
I dont want to turn it on. and we certainly shouldnt force cheats on all servers.
