### ISSUE TITLE
Precise Auto Assembler (Normal Mode) doesn't work with Crafting Input Buses

### ISSUE THREAD

**Issue by Dyonovan** [GTNewHorizons/GT-New-Horizons-Modpack#15556]
### Your GTNH Discord Username

Dyonovan

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Trying to use Crafting Input Bus (ME) with the precise assembler (Normal Mode)

### The Reality

The items just sit in the Crafting Input Bus but the Assembler doesn't seem to recognize them.

### Your Proposal

Allow crafting input busses on the Precise Auto-Assembler

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
several people are telling me it works just fine.
Make sure to check that you satisfy all the requirements: minimum casing count and energy hatch tier at least as high as recipe tier come to mind.

**Comment by kyoi-the-fox** [comment]
same base different player, tested with 
vibrant alloy frame box -> worked,
copper cable -> doesn't work,
Ii assume the issue is liquids coming from a stocking input hatch. which worked fine for example with the mixer,but not the precise auto assembler in normal mode

**Comment by chochem** [comment]
crafting input bus doesnt work with liquids (outside of some bugs that have been fixed since)

**Comment by kyoi-the-fox** [comment]
ok,so the industrial mixing machine grabing the liquid from the stocking imput hatch is the bug then?

**Comment by chochem** [comment]
seems to work.
