### ISSUE TITLE
Add option to process gunpowder to regain source materials.

### ISSUE THREAD

**Issue by LionEl-johnson14** [GTNewHorizons/GT-New-Horizons-Modpack#15566]
### Your GTNH Discord Username

lion_eljonson14

### Your Pack Version

2.4.0

### Your Proposal

Add a machine recipe to process gunpowder into it's source materials.

### Your Goal

Gunpowder is a common product from many sources, including creeper, ghast, and fusewood farms, but does not have any mid-late game usages outside of the very memey powderbarrel, which is only needed in small quantities anyway.

### Your Vision

It would give alternative renewable access to its core materials of saltpeter, sulfur, and carbon, which are all common enough to be farmed through other sources, and give a use for an otherwise fairly useless material.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LazyFleshWasTaken** [comment]
Has this been written off as a "No, gunpowder centrifuging will not be added" or "No one has worked on this, or said they would, but should they do, this can be added"?
