### ISSUE TITLE
Pollution scrubbed by air filter is not correct.

### ISSUE THREAD

**Issue by DeveloperLewis** [GTNewHorizons/GT-New-Horizons-Modpack#15573]
### Your GTNH Discord Username

leeewiisss

### Your Pack Version

2.5.1

### Your Server

sp

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

I have an electric air filter with an mv energy hatch and 8 mv mufflers. This should scrub 1350 pollution a second

### The Reality

It only scrubs 1280 to begin with. I have 2 of these air filters and they scrub a combined 2560. However in the isolated chunk with pyrolose ovens and a coupel generators (1500 pollution a second total) the pollution still rises. This shouldn't be the case as there is 1060 roughly that should be scrubbed every cycle. But after hours it still does not go down.

### Your Proposal

It feels like its half of what the air filters are saying they are scrubbing. 64/t feels like 32/t. Up the amount to 128/t or just double the overall pollution scrubbing?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
Would you mind answering a few questions for me:
* Which turbine are you using in the filter?
* If you scan the filter controller, how much does it say it filters?
* Are you running the filter in sequential or random mode? Are you using the full 3x3 range, or did you set it to 1x1 only?
* Could you list all the machines generating pollution in the chunk? (Maybe the pollution generated is incorrect, not the filter's amount.)

**Comment by DeveloperLewis** [comment]
Sure no problem!

- A small ardite turbine (90% efficency)
- 64/t
- Sequential in 1x1 only (2 air filters in the same chunk)
- 4 pyrolose ovens, 6 generators in 1 chunk / An adjacent chunk has 6 generators too as well as another air filter with same specs as the other 2. (So 3 air filters in 2 chunks, with 4 pyrolose ovens and 12 generators total)

**Comment by AbdielKavash** [comment]
It looks like you are falling victim to rounding of small numbers.

Every MV muffler contributes to pollution cleaning rate by an additive factor of 2.5^2 = 6.25, which gets rounded to 6. With 8 such mufflers, this is 8 \* 6 = 48. The base cleaning rate is 30, your turbine efficiency is 0.9 (90%), which gives 30 * 48 * 0.9 = 1,296 pollution cleaned per second. This is the actual amount that the filter really does. Scanning it gives you the amount per tick, which is 1,296 / 20 = 64.8, which gets rounded to 64, as you can see. This appears correct.

With three air filters like this, you are clearing 3 \* 1296 = 3,888 pollution/sec.

A pyrolyze oven produces 300 pollution per tick with an LV muffler, or 261 with an MV one (I don't know which one you are using). Generators (assuming gas turbines?) produce 200 pollution per second if they are LV, or 180 pollution per second if they are MV.

Together, with LV mufflers on the pyrolyze ovens and LV generators, you are making 4 \* 300 + 12 \* 200 = 3,600 pollution/sec.

If you are using MV mufflers and MV generators, this is 4 \* 261 + 12 \* 180 = 3,204 pollution/sec.

While yes, you should be cleaning pollution faster than you are making it, the margin might be thinner than you think. Possibly you have some other polluting machines running nearby (Vanilla furnaces? Coke ovens?), or pollution spilling in from other adjacent chunks. Or maybe the pollution amount in your chunks is so large that it is really just taking the filters a long time to go through it all.

Let me know if my math matches yours.

**Comment by DeveloperLewis** [comment]
Oh that makes sense I forgot about the floor(). In the questbook it says something different but the controller includes the floor() into the formula. However the controller removes the mufflers so its a little confusing. The pyros are using mv muffler hatches. My gas turbines should only produce 36 pollution per second I thought, not 180? The ingame tooltip says this so maybe its different? 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62842266/60588004-e1ab-4c3b-8b9f-5191aa1fa772)

So there should be a significantly higher amount of pollution scrubbing than pollution created so its a little confusing still. I don't have any other chunks aside from those 2 creating the pollution to begin with. The pollution in my chunks are relatively small (500k).
