### ISSUE TITLE
Unable to use T5 rocket to reach Enceladus

### ISSUE THREAD

**Issue by Apochy** [GTNewHorizons/GT-New-Horizons-Modpack#15579]
### Your Pack Version

2.5.1

### Your Server

private sever

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

``I want to use the T5 rocket to go to Enceladus and obtain the T6 rocket blueprint.

### The Reality

Other planets that T5 rockets can reach, such as Titan and Ross Ba.But only Enceladus cannot go.
![E23275393B2465BD490972542861C067](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/160820615/8e37c62d-12c5-419d-bfd4-929601d11ea5)
<img width="1280" alt="917B54382CE51C3DB2248DB4ABF24392" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/160820615/e05b0129-9d36-4147-a38a-e6402d4f7517">

By the way, in single player mode, I can use the T5 rocket to travel to Enceladus.

### Your Proposal

I hope you can tell me the solution,thanks.

### Final Checklist

- [ ] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/9eeaabb0-9f9a-426f-a7f8-330cf3dc9618)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/b131ae72-a2a7-4789-8df8-501f7b59f7e5)

works just fine
