### ISSUE TITLE
"New Features" spotlight on the loading screen.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15575]
### Your GTNH Discord Username

Abdiel Kavash

### Your Pack Version

2.5.1

### Your Proposal

The loading screen currently displays a random "tip of the day", which is nice and useful. But I had an idea: it could also highlight some new features from the latest update. Maybe using the same interface, just mix the features with the tips; or maybe even in a separate place.

### Your Goal

Currently the best way to learn about new features added to the pack is through the discord, and even then not everything is mentioned in #upcoming-features. Or one can read the release notes, which are far too verbose for a casual player, and hide cool new things among many "refactored this thing" notes.

### Your Vision

Players who don't interact with discord, and don't have the will to read through release notes/wiki, could still have an easy way to learn about what's new in the pack with every update.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by PlayfulPiano** [comment]
Bumping and supporting. Example here would be the new change to the boots of the traveler series having modifier keybinds for speed and jumping now.

**Comment by AbdielKavash** [comment]
Bump, if anyone is interested.
