### ISSUE TITLE
Yottank not saving contents on server restart

### ISSUE THREAD

**Issue by NotAPenguin0** [GTNewHorizons/GT-New-Horizons-Modpack#15572]
### Your GTNH Discord Username

notapenguin

### Your Pack Version

2.5.1

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Yottank should properly save its contents on server restart

### The Reality

When I restart my server some or all of my yottank revert their contents to a previous state (e.g. I restart the server and 70m biocat turns into 20m).

I am aware this is probably very difficult to reproduce and track down, but I'll try my best to provide any logs necessary. I have a relatively large amount (64) of yottanks on a subnet with yothatches. 

- The tanks are always chunkloaded
- The tanks do cross chunk borders
- The server exits normally, no errors are logged anywhere from what I can tell
- I'm using 2.5.1 with the exception of hodgepodge, gtnhlib and ggfab which are updated to the current latest nightly version
- This seems to happen to both fluids >2.1b and <2.1b

Attached logs below:

Running server that was stopped: https://gist.github.com/NotAPenguin0/d5da58a2fc60f7bf782028bd38b863ce
[restart]
Server startup: https://gist.github.com/NotAPenguin0/bdb4e8a16d4228098201d39d64b73f9f

After logging in to the started server, the yottanks had reverted to some previous save, not the point they were at when I stopped the server

### Your Proposal

Please don't make my yottanks delete my precious bio catalyst when I have to restart my server

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leumasme** [comment]
Can you test if other world changes in the same chunk as the tank in question are being saved correctly?

**Comment by NotAPenguin0** [comment]
Sorry for the late response, I've been very hesitant to try this out, but finally had to update some mods on my server. Looks like everything went fine, tanks kept their contents and blocks are still there. Sorry for the confusion.
