### ISSUE TITLE
java.lang.IllegalAccessError: class tconstruct.tools.TFToolEvents tried to access protected field net.minecraft.util.EntityDamageSource

### ISSUE THREAD

**Issue by mchernykh** [GTNewHorizons/GT-New-Horizons-Modpack#15589]
### Your GTNH Discord Username

murderless

### Your Pack Version

2.5.x nightly 359

### Your Server

sp

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

shoot skeleton with crossbow. world crashes with the same reason after restart

Java arguments: 
--illegal-access=warn -Djava.security.manager=allow -Dfile.encoding=UTF-8 --add-opens java.base/jdk.internal.loader=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/java.text=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens jdk.naming.dns/com.sun.jndi.dns=ALL-UNNAMED,java.naming --add-opens java.desktop/sun.awt.image=ALL-UNNAMED --add-modules jdk.dynalink --add-opens jdk.dynalink/jdk.dynalink.beans=ALL-UNNAMED --add-modules java.sql.rowset --add-opens java.sql.rowset/javax.sql.rowset.serial=ALL-UNNAMED -Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader

### Crash Report

[crash-2024-02-24_19.01.30-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14393531/crash-2024-02-24_19.01.30-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
Source: https://github.com/GTNewHorizons/twilightforest/blob/master/src/main/java/tconstruct/tools/TFToolEvents.java#L226

**Comment by mchernykh** [comment]
revert from twilight forest 2.5.14 to 2.5.13-pre allowed to load the world and finaly kill the skeleton
