### ISSUE TITLE
Server restart when not all items have been pushed from an AE2 craft voids the remainder

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#15583]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.5.1

### Your Server

Delta

### Java Version

Java 19

### Type of Server

Thermos

### Your Expectation

My base keeps running properly after a server restart

### The Reality

Everytime it restarts, partially inserted crafts get their remainder voided. This applies to several machines: every restart 256 items - the size of one craft - are lost from the Mega EBF if it was busy at that time. The situation is much more annoying with the component assembly lines, which get completely stuck and have to be manually reset after every reboot because the hatches are filled with only a fraction of a recipe and can't accept a different craft. 
I now have to add extra subnets and logic to prevent crafts from being continually pushed to prevent erratic behaviour.

### Your Proposal

ME Interfaces should properly remember the items that have not been pushed across a server restart

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Are you using patterns with >127 item per stack? I'd assume yes since you are using a MBF, but it never hurt to get a confirmation.

**Comment by combusterf** [comment]
@Glease yes, that's indeed the case
