### ISSUE TITLE
Worlds not working

### ISSUE THREAD

**Issue by Polyphare** [GTNewHorizons/GT-New-Horizons-Modpack#15585]
### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I start the game, load my save and start playing

### The Reality

When i start the game, it works fine but when i try to load a save i get this message
![aw yep](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/161072840/4d377a05-29f3-4c43-8964-a64c50e1d0cc)
 and then it sends me on the tittle screen. I just added optifine, tried to delete it and still didn't work, i tried to delete/reinstall the modpack. Yesterday, i had the same problem, but after reloading the game, it worked just fine, but today i can't load my save, or create a new one.
When i try to create a new world, the new world file appears in the saves files, but it isn't in the in-game worlds list.

### Your Proposal

maybe finding the reason of this error, so i can continue playing this modpack.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
nothing anybody can do without logs.
but if the game is corrupted you should use a backup.
