### ISSUE TITLE
Thaumcraft - Golemancy: Golem are not dropping upgrades

### ISSUE THREAD

**Issue by Jendx** [GTNewHorizons/GT-New-Horizons-Modpack#15591]
### Your GTNH Discord Username

jenda1429

### Your Pack Version

2.5.1

### Your Server

sp

### Java Version

Java 20

### Type of Server

Open To LAN

### Your Expectation

When using Golemacer's Bell_TH I would expect that the upgrades inserted into golems would drop when using the Item / killing them
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62170918/0204a753-b9c2-4391-91ba-885bfb968a77)

### The Reality

If Golemacer's Bell_TH is used to dismantle them. I get the core back but only 1 upgrade and when killed you get nothing

### Your Proposal

Make them drop theyr upgrades when dismantled or killed

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leumasme** [comment]
The limited drop chance when dismantling with bell is intended, see Thaumonimicon Entry:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29953391/6175a648-17d5-4e24-9f3c-4a444050092c)

**Comment by Jendx** [comment]
Ah okey, sorry. 
I though it was consistent last time I played it. ^^'
