### ISSUE TITLE
2 recipes for Fluorite in exxon chem plant

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15609]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.0 build 3.6.1

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

just one recipe

### The Reality

![9XDD AOK6@_M1S8L$YK_34G](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/6c9a7dc8-d03a-4560-b2d0-25a23ab94518)

### Your Proposal

delete one

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
isnt that just sand vs sandstone?

**Comment by miaowwwwww** [comment]
lol u r right, i guess just leave it like this?

**Comment by chochem** [comment]
yea
