### ISSUE TITLE
Quest fix&change for bee

### ISSUE THREAD

**Issue by Wacchi-Lorie** [GTNewHorizons/GT-New-Horizons-Modpack#15600]
### Your GTNH Discord Username

wacchi_lorie

### Your Pack Version

2.5.1

### Your Server

private

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Theres a symbol mistake in quest 'Busy Bees Buzzing Boldly' (ID: AAAAAAAAAAAAAAAAAAAILA==)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/f989ad9d-41a8-4a72-be43-b1df02feeb46)
Should be 'Water - Temp-10%, Humidity+20%\n'
--- has been fixed for a while ---

Thus, crushed ice(7205:30702) also works for alveary hygroregulator
for 'Crushed Ice - Temp-20%, Humidity+40%\n'

I think information of energy and material comsuming rate should also be given out:
Alveary Fan - 10RF/t
Alveary Heater - 10RF/t
Alveary Hygroregulator (Water) - 1L/t
Alveary Hygroregulator (Lava) - 0.1L/t
Alveary Hygroregulator (Crushed Ice) - 0.1L/t

### The Reality

Quest 'Busy Bees Buzzing Boldly' (ID: AAAAAAAAAAAAAAAAAAAILA==) has minor mistake

### Your Proposal

change a text and add my proposal if necessary

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
is fixed already
