### ISSUE TITLE
Bisphenol A not being produced in LCR with all input items

### ISSUE THREAD

**Issue by innsightt** [GTNewHorizons/GT-New-Horizons-Modpack#15602]
### Your GTNH Discord Username

iaintjp

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I have a wallshared LCR that is supposed to produce Bisphenol A, and even though it has one LV input hatch filled with Acetone, another filled with Hydrochloric Acid, and another filled with Phenol, and two output buses for water and Bisphenol A, the machine does not work. I have a Circuit 1 Programmed Circuit inside the controller block, it has an HV energy hatch with an HV gas turbine attached to it. Maintenance has been performed, and the controller says "No valid recipe found". I tested another recipe in the same wallshared LCR, and it worked normally. However, for Bisphenol A it did not. I then tested a separate LCR to produce Bisphenol A, and in that separate LCR it worked. However, while having all conditions in order to produce Bisphenol A in the wallshared LCR, it did not work.

What is wrong? I have energy, maintenance, all inputs, space to output, correct circuit, all the input buses are completely filled so there's also enough input, the LCR is correctly built as the controller does not state anything wrong, there is a minimum of 8 chemically inert machine casings...

### The Reality

Alrerady explained above.

### Your Proposal

Bisphenol A to be produced correctly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
since you have it working on a separate LCR, this just sounds like a problem in your setup and not a bug.
