### ISSUE TITLE
crash when shift writing a pattern in ae

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15603]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.0 build 3.6.1

### Your Server

zeta

### Java Version

Java 8

### Type of Server

Thermos

### Your Actions

open a pattern terminal, shift click "?" to write a pattern.

### Crash Report

universal wireless:
[crash-2024-02-26_22.51.57-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14415922/crash-2024-02-26_22.51.57-client.txt)
fluid pattern terminal:
[crash-2024-02-26_22.52.28-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14415927/crash-2024-02-26_22.52.28-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Hikari1nVoid** [comment]
Cannot repro with following hardware&software set:
MacOS running 390 with Java8
Windows 11 running 390 with Java 21.
need more detail.
Also shift and control does not make any difference for me.the shift/ctrl to request craft feature is missing.

**Comment by miaowwwwww** [comment]
i was running win10 with java8, gonna check again

**Comment by miaowwwwww** [comment]
with a pure instance nothing happens, my fault, closing this.
