### ISSUE TITLE
crash when change universal wireless terminal to Level Maintainer page

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15604]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.0 build 3.6.1

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Actions

change universal wireless terminal to Level Maintainer page
when it crashed, the operate-able space shrink
![QWQ@`_}9B6UL)Q6AT7WD%LY](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/b43d9932-56f5-440e-b684-85d1b46d8c6a)
![3WKQZ{@0J%MPX3 5~9R4MV](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/415610aa-8f90-45bf-9d55-8808531787b6)
even with the vanilla fix working, player would still need to restart client to solve the issue.

### Crash Report

[crash-2024-02-26_23.37.56-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14415988/crash-2024-02-26_23.37.56-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
caused by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/474
