### ISSUE TITLE
crib not fully isolated from other hatches/buses

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15608]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.0 nightly 361

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

crib fully isolated from other hatches

### The Reality

fluid in crib, item in a normal bus.
the machine runs.

![5H5YGW M3M{KEH`JM)}FQ%C](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/c1c766bc-f0d0-4ae6-9f96-890b71fd8055)
molten  Energetic Alloy 

![33)K C@668(ARVPL{ODGFSR](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/98474382-1b71-451a-8204-7f793105d94e)
[Energium Dust)

![8}~OBW {LWL(Z09667_N`~M](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/fb04754d-5d80-426f-a9af-5d266d3e6d87)
machine runs

### Your Proposal

my guess is that when the machine sees the fluid in crib, it searches not only crib but also the outside for possible recipes. if i guessed right, need to change this part to search only this slot of the crib.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by RitumsC** [comment]
Can confirm that this exists; in discord help discussions with Divran and Staffix, we found that this happens if the machine has an available toggle between input separation and its toggled-off.

Not sure if feature or bug tho :^ )

**Comment by chochem** [comment]
> Not sure if feature or bug tho :^ )

bug. crib bus and buffer are intended to be fully separate and isolated.

**Comment by chochem** [comment]
it looks like this is mainly caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2266
