### ISSUE TITLE
Inconsistent assembler recipe for Advanced Heat Exchanger

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15621]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

NEI should show the correct ingredients required for crafting the IC2 "Advanced Heat Exchanger" using the assembler recipe.

### The Reality

The assembler recipe for the Advanced Heat Exchanger implies that each instance of the item will require _two_ of the more basic "Heat Exchanger" items, also from IC2. The two Heat Exchangers shown in NEI are displayed in separate inventory slots in the assembler UI, because the Heat Exchanger items do not stack.

When I crafted an Advanced Heat Exchanger using an assembler, I set the programmed circuit first, and then I placed the lapis plates, diamond plates, and EV circuits (the other required ingredients) into the assembler, before inserting the basic Heat Exchangers _last_ using shift click functionality. As soon as I placed just _one_ Heat Exchanger into the assembler, it immediately consumed that single Heat Exchanger plus the remaining ingredients, and crafted an Advanced Heat Exchanger from only one Heat Exchanger rather than the two that NEI implies are required.

### Your Proposal

I don't know whether NEI is erroneously showing an extra Heat Exchanger in the recipe for the Advanced Heat Exchanger, or whether the recipe _does_ require two Heat Exchangers and the assembler is malfunctioning due to the unstackability of the Heat Exchanger items; whichever is the case, the solution should be to make the _intended_ recipe consistent between both NEI and the assembler itself.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
probably the same as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15606
