### ISSUE TITLE
QFT (quantum force transformer) don't work with crafting input buffer

### ISSUE THREAD

**Issue by zgggz** [GTNewHorizons/GT-New-Horizons-Modpack#15623]
### Your GTNH Discord Username

ZgggZ#7290

### Your Pack Version

2.5.1

### Your Server

private

### Java Version

Java 8

### Type of Server

None

### Your Expectation

fix it pls

### The Reality

-

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/829
