### ISSUE TITLE
Builder's Wand doesn't work on Salt

### ISSUE THREAD

**Issue by Logos-Askrson** [GTNewHorizons/GT-New-Horizons-Modpack#15629]
### Your GTNH Discord Username

logos_askrson

### Your Pack Version

2.5.1

### Your Server

Eta

### Java Version

Java 17

### Type of Server

Thermos

### Your Expectation

When trying to build with blocks of salt, I might expect to be able to do bulk work with a builder's wand, as normal.

### The Reality

When trying to use the builder's wand on barworks Block of Salt blocks, it simply does nothing.

### Your Proposal

I don't know exactly what needs to be changed to have this work, but it's weird that it doesn't, and if there's not a good reason for it not working it should probably work.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leumasme** [comment]
In creative mode, it places a Bartworks "Block of _NULL" - same id, but meta 0 instead of 20. In general, BBW seems to behave very weirdly here.
Related BBW code should be here: https://github.com/GTNewHorizons/BetterBuildersWands/blob/master/src/main/java/portablejim/bbw/core/WandWorker.java#L44
