### ISSUE TITLE
Obsidian should macerate into 9 dust

### ISSUE THREAD

**Issue by extszombiemaster** [GTNewHorizons/GT-New-Horizons-Modpack#15625]
### Your GTNH Discord Username

ZombifieDoll

### Your Pack Version

2.5

### Your Proposal

....at the very least give us 8 dust by product in HV Macerator

Right now it feels wrong that you can cut it into 9 plates or alloy smelt it into 9 ingots, where's our extra dust?

### Your Goal

Make the dust not magically disappear.

### Your Vision

More obsidian dust :D

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14621 but I guess its closed
