### ISSUE TITLE
SuperTank I - Wrong max storage number in tooltip

### ISSUE THREAD

**Issue by Blaiin** [GTNewHorizons/GT-New-Horizons-Modpack#15631]
### Your GTNH Discord Username

Blain_#4587

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Looking at supertank tooltip i expected x amount of fluid/4,000,000L 

### The Reality

Saw positive integer limit instead ![2024-03-01_21 51 58](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/96704158/bc9cc24b-5456-4e2d-af6e-e59f6e055f3c)

### Your Proposal

It's not a huge bug so just letting you know.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
caused by overflow void specifically

**Comment by Lyfts** [comment]
This has apparently been a problem since 2.3.6 and affects all tanks with void overflow.
It's present on all MUI versions after https://github.com/GTNewHorizons/ModularUI/pull/48
