### ISSUE TITLE
[Forestry] Frame housing recipe misconfigured

### ISSUE THREAD

**Issue by ChaosTheLegend** [GTNewHorizons/GT-New-Horizons-Modpack#15635]
### Your GTNH Discord Username

chaosthelegend

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22730799/d9c3e478-db02-4705-b7a4-bf36c02aa310)

Frame housing recipe should use 4 Proven frames for the craft

### The Reality

It uses 1

![Frame Housing](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22730799/e5e30c00-3288-46ef-8a32-0e6ab26856b1)

Crafter in EV assembler

### Your Proposal

Tweak the recipe to use 4 frames (or change it to 1, but that's ungreggy)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
should be fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2516
