### ISSUE TITLE
ME interface does not save direction when using gt wrench

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15637]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.0 build 3.6.1

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

ME interface don't lose direction

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/98a4c33e-d033-4c24-ba9f-4840968697b9)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/976bdaab-051b-4772-8235-ed4facd3a066)

OR
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/92a11de1-2a93-4039-b4af-d04032d1e486)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/05b856a4-81d7-41bf-900d-e0bca1edf13e)

OR 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/db1fc0b6-b16e-4547-8c80-500c8104514d)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/685ff4aa-a376-4e83-8f2f-feec82de8a79)

### Your Proposal

fix, should be related to the new "me interface using gt-like wrench behaviour" pr

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
possibly cased by this https://github.com/GTNewHorizons/GT5-Unofficial/pull/2395

**Comment by Wacchi-Lorie** [comment]
issue persists with 2.6.0-beta3 @boubou19

**Comment by ghostflyby** [comment]
> issue persists with 2.6.0-beta3 @boubou19 ![image](https://private-user-images.githubusercontent.com/57549294/326182879-5f9a25c8-a5e3-463e-86af-b4956b2a7461.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODA4MzcsIm5iZiI6MTcxNDI4MDUzNywicGF0aCI6Ii81NzU0OTI5NC8zMjYxODI4NzktNWY5YTI1YzgtYTVlMy00NjNlLTg2YWYtYjQ5NTZiMmE3NDYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA1MDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiNmEyOTc2MzM2ODhhMDkwNjNlZTEyNmZkOTYyYzJkY2M0ZmU2MjYzYmJmYjFkMzRiOGY2MzgxZDliMDNhMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7-gWrgX8EwgoQBdYUyU1X3BnW4JGb7wlvkss6EN4ntM)

Can you provide details on your GT5 mod version? I can't reproduce it in the latest GT5 dev environment.

**Comment by Wacchi-Lorie** [comment]
[client modlist](https://github.com/GTNewHorizons/Angelica/files/15140616/server.info.txt) and [server modlist](https://github.com/GTNewHorizons/Angelica/files/15140616/server.info.txt)
using 2.6.0-beta3 and GT5 5.09.45.144, not the latest dev
