### ISSUE TITLE
Essentia Terminal right click crash back to menu

### ISSUE THREAD

**Issue by steveas77** [GTNewHorizons/GT-New-Horizons-Modpack#15634]
### Your GTNH Discord Username

Dru Blood

### Your Pack Version

latest dev build updated with GTNH Jenkins Downloader

### Your Server

private server

### Java Version

Other versions in between

### Type of Server

Vanilla Forge

### Your Actions

Just trying to open the essentia terminal 

### Crash Report

[crash-2024-03-02_10.37.02-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14469010/crash-2024-03-02_10.37.02-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by slprime** [comment]
this PR https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/482 fix it
