### ISSUE TITLE
Removal of Ender tanks and Ender chest from lootbags 

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#15642]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

2.5.1

### Your Proposal

Ender chests and ender tanks from lootbags should be removed from the reward pool.

### Your Goal

These items require a decent amount of magic progression in thaumcraft 4 and are a strong integration into the mod. Allowing the player to freely obtain them through lootbags devalues the magic player's progression and reduces the engagement of players on the fence of trying the magic content. The ender tank and ender chest are also very strong at the point that the player receives them due to the items requiring iridium from the platinum line.

### Your Vision

I would hope that the removal of the ender tank and ender chest from the lootbag pool will increase engagement in the side content which will fit into the push that the space age did for thaumcraft 4. As the space age quests push the player towards thaumcraft to craft null catalyst for nether stars.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
> Most of the GT:NH players dislike magic.

I don't want to either agree with or argue against this point; but I would like to see some numerical data supporting it.
