### ISSUE TITLE
Glow Flowers (Pam's Harvest the Nether) get destroyed by a random tick update when planted on tilled Fertilized Dirt.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#15649]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

The expectation is when planting glow flower seeds onto tilled fertilized dirt, it would be planted and grow at an accelerated tick rate.

### The Reality

The reality is that the planted crop randomly gets destroyed with what I'm assuming is a random tick update, therefore cannot be farmed with fertilized dirt.

### Your Proposal

Fix the bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Majora320** [comment]
It looks like the flowers get destroyed when the block is updated, as placing blocks adjacent to the glowflower also destroys it.
