### ISSUE TITLE
Allow input seperation in Cutting Factory

### ISSUE THREAD

**Issue by hiroscho** [GTNewHorizons/GT-New-Horizons-Modpack#15640]
### Your GTNH Discord Username

hiroscho

### Your Pack Version

2.5.1

### Your Proposal

Cutting Factory should allow input seperation.

### Your Goal

For example Livingrock Slab and Livingrock Plate cannot be made in the same Cutting Factory since inputs are not seperated.

### Your Vision

More use for the multi

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
alternatively, the recipes in botanichorizons could be made more regular like all the others.
