### ISSUE TITLE
simple washing machines eats HUGE chunks of tps when supplied with water&EU while not running

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15646]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.0 build 3.6.1

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

no tps eater

### The Reality

running tps:  57
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/4ea85e08-ba53-4e14-aa9e-926963b0c407)
not running:  400
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/e5e4aa37-3402-41d8-b891-bab5005d615d)

### Your Proposal

fix it, or just delete it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Filiz1** [comment]
Same on 2.5.1

**Comment by Hikari1nVoid** [comment]
![Cache_-481551f8349ef7f4.png](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24840795/354547c3-b931-4a9f-ad95-03c3a4b33027)

idk why it is searching for recipes even when machine is disabled.
