### ISSUE TITLE
"Minecraft" Certus Quartz Ore can be generated in the nether instead of the GregTech ore.

### ISSUE THREAD

**Issue by p3rsonUnknown** [GTNewHorizons/GT-New-Horizons-Modpack#15656]
### Your GTNH Discord Username

p3rsonUnknown

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I thought the "Minecraft" Ores were disabled.

### The Reality

I've found some "Minecraft" Certus Quartz Ore generated, and in the vanilla mc style too, not in a vein style.

### Your Proposal

I don't know If it was purposefully left like this. I asked about in the general channel in discord and they said vanilla ores are not supposed to generate unless they're forced by certain terrain, and I don't think there's any specific terrain around the ores that I found.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by p3rsonUnknown** [comment]
![Uploading Desktop Screenshot 2024.03.04 - 18.38.26.20.png…]()

**Comment by p3rsonUnknown** [comment]
![Desktop Screenshot 2024 03 04 - 18 38 26 20](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/f6cd6122-24e2-4e1a-9e4a-e57bbae43685)

**Comment by p3rsonUnknown** [comment]
![Desktop Screenshot 2024 03 04 - 18 43 29 36](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/195b9451-1877-41ec-9346-fbc969cd7935)

**Comment by Ethryan** [comment]
It generates around Nether Hives.

**Comment by p3rsonUnknown** [comment]
thanks for the fast info
