### ISSUE TITLE
Receipe Error of OC keyboard

### ISSUE THREAD

**Issue by Wacchi-Lorie** [GTNewHorizons/GT-New-Horizons-Modpack#15653]
### Your GTNH Discord Username

wacchi_lorie

### Your Pack Version

2.5.1

### Your Server

private

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Fix Assembling machine OC keyboard receipe issue

### The Reality

Receipe of keyboard(Open Computer)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/3cb50a7f-c358-4e19-b70f-c6ea9e8cf9f5)
contains 104 buttons, but actually it only consumes 64 buttons and 64 buttons in assembling machine can also trigger the receipe.
NEI receipe is wrong.

### Your Proposal

fix receipe as consuming 104 buttons since realife keyboard has 104 keys

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed in dev https://github.com/GTNewHorizons/GT5-Unofficial/pull/2516

**Comment by Wacchi-Lorie** [comment]
> Fixed in dev [GTNewHorizons/GT5-Unofficial#2516](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2516)

havent tested but seems any assembler receipe which has material of more than 64, causing more than 1 stack of a single material, will simply skip check and not comsumed or needed for receipe check. is it fixed generally?
