### ISSUE TITLE
LCR recipe in assembler is more expensive than in crafting table

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#15651]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

LCR recipe in assembler should be equal to crafting table or cheaper.

### The Reality

LCR recipe in assembler is more expensive than in crafting table: 3 motors instead of one.
Also, HV machine casing is used instead of hull.
![2024-03-04_13 37 57](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18097458/9610c112-c6d1-48a1-ac31-b72c57fdcf1b)
![2024-03-04_13 37 54](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18097458/12e246dd-a5ba-4ccf-bd5b-82e3bbcc76ee)

### Your Proposal

Fix LCR recipe in assembler.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
just one for me (nightly 353)

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/783
