### ISSUE TITLE
Raw ores unable to be processed by GT singleblocks

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#15655]
### Your GTNH Discord Username

Hiakri1nVoid#9527

### Your Pack Version

nightly-373

### Your Server

zeta

### Java Version

Java 21

### Type of Server

Thermos

### Your Expectation

Process "new raw ores"

### The Reality

Non of GT singleblock and process them.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24840795/f977a7c0-9ad9-43e3-8ab6-01b092e56fde)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24840795/d9be1d0b-f6d7-4253-b135-032da46e432e)

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
Confirmed

@Ethryan
