### ISSUE TITLE
Blueberry from Natura doesn't plant on IC2 crops

### ISSUE THREAD

**Issue by fade0n** [GTNewHorizons/GT-New-Horizons-Modpack#15657]
### Your GTNH Discord Username

a1caida

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Trying to plant Blueberry from Natura on IC2 crop but it doesn't work. I tried to plant Blackberry and other berries and it can be planted.

### The Reality

Blueberry doesn't plant on IC2 crop

### Your Proposal

Blueberry should be planted on IC2 crop

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ProTriforcer** [comment]
Bump
2.7.0, java 21

I suspect this line is the problem
https://github.com/GTNewHorizons/Crops-plus-plus/blob/4ed65aa1e2a243bae33ece5f0e0892186cdd39fe/src/main/java/com/github/bartimaeusnek/cropspp/crops/natura/BlueberryCrop.java#L16
