### ISSUE TITLE
Crash when opening conduit ui. (running only this mod in a singleplayer world)

### ISSUE THREAD

**Issue by unspecifiedz** [GTNewHorizons/GT-New-Horizons-Modpack#15663]
### Your GTNH Discord Username

unspecifiedz

### Your Pack Version

2.6.7

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

**Origin:**
I initially tried to install/upgrade enderio to this mod version(2.7.1) on an FTB Direwolf 20 1.7.10 server with a couple extra mods like mekanism installed. Reason: I want to be able to edit the transciever buffer and like to have the extras from this mod version.
 I ran into multiple problems causing the server to crash but I was able to resolve it by deleting all entities from the old enderio version, switching to the 2.6.7 version and load the new mod over it. I now run into a problem that crashes my game when I try to configure the conduits in their ui. It does not matter what type of conduits I try to edit.
So I tried troubleshooting and the problem even persists when I load a new instance of forge with only this mod and its requirements installed, I guess I maybe need specific mods in GTNH as a requirement because this enderio is specifically built for GTNH? but I couldn't find anything saying that, just some reddit user guessing the same.

**Problem now:**
World: Single Player
MCP v9.05
FML v7.10.99.99
forge version:    first this version--> forge-1.7.10-10.13.4.1558   then updated to forge-1.7.10-10.13.4.1614 (no changes)
Launcher: GDLauncher
mods installed:
EnderIO-2.6.7
CoFHLib-[1.7.10]1.0.3-175
EnderCore-1.7.10-0.2.0.40_beta (I tried the 0.2.0.39_beta aswell)

**How to replicate**
1: Install a forge version of 1.7.10 without any mods,  forge-1.7.10-10.13.4.1558  or  forge-1.7.10-10.13.4.1614
(I used .1558 first because that is the version my server is running it on, while troubleshooting I switched to .1614 to maybe fix the problem but it didn't work)
2: Install EnderIO-2.6.7 (GTNH/EnderIO version)
3: install CoFHLib-[1.7.10]1.0.3-175
4: installl EnderCore-1.7.10-0.2.0.40_beta  or   EnderCore-1.7.10-0.2.0.39_beta
5: Open a SP creative world and place any type of conduit on a block it can connect to (I always used Dimensional Transceiver)
6: Try to open the UI from the conduit to configure its parameters (The UI does not even open it just immediately crashes the game)
![Screenshot (145)](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/162453463/ea9917e7-ecb6-4dc9-ba16-0c11a964a131)
7: Crash :) 
GDLauncher Crash message:
![gdlauncher crash message](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/162453463/c10d7d70-2126-4fd6-bbef-8de9c81ab8ec)

### Crash Report

[crash-2024-03-06_14.13.24-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14510422/crash-2024-03-06_14.13.24-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
This mod is on our passive list

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18713839/47adc5cd-cbb8-4ab9-af0c-fde63c7f6b2e)

**Comment by Caedis** [comment]
Where did you get 2.7.1?

**Comment by Lyfts** [comment]
Try with the GTNH fork of Endercore,
https://github.com/GTNewHorizons/EnderCore/releases/tag/0.4.6

**Comment by unspecifiedz** [comment]
> Try with the GTNH fork of Endercore, https://github.com/GTNewHorizons/EnderCore/releases/tag/0.4.6



> also COFHCore 3.1.4-329 is required https://www.curseforge.com/minecraft/mc-mods/cofh-core/files/2388750


Thanks, I didn't knew about the fork of endercore mod for GTNH. I now installed 
endercore 0.6.4 
EnderIO-2.7.1
COFHCore 3.1.4-329
CoFHlib1.0.3-175

and everything works as intended. I Installed those on the FTB presents Direwolf 20 (+some other mods) server aswell and it works right now. I hope I won't run into more issues/crashes with all the other mods further into the game. 

Was the requirement for the fork version listed somewhere? I was looking everywhere but I couldn't find any req for GTNH EnderIO.

> Where did you get 2.7.1?

It's the official release from 2 weeks ago: https://github.com/GTNewHorizons/EnderIO/releases/tag/2.7.1

Thanks you all for the help!!!!
