### ISSUE TITLE
Tungsten in MK1 Combustion Gen

### ISSUE THREAD

**Issue by dimazha** [GTNewHorizons/GT-New-Horizons-Modpack#15675]
### Your Pack Version

2.5.1

### Your Proposal

Replace the tungstensteel cable with aluminum cable in the recipe of MK1 Combustion Generator 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/106115870/e26e371c-e60e-45e6-b6d7-caf7d852c36d)

### Your Goal

Combustion Generator needs more infrastructure (fuel, oxygen, lubricant production) and produces less energy than Vacuum Nuclear Reactor (6k against 8k). With all this Combustion Gen has tungstensteel in recipe that is available on middle-EV, while Vacuum Nuke needs only EV Assembler.

### Your Vision

Reduction of Combust Gen price will give players an equal choice between Combustion Generators and Vacuum Nukes. Now Combustion Gen MK1 is useless

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by StaffiX** [comment]
well considering that you need an ev buffered dynamo hatch to get out 6144, which also does take tungstensteel, i dont really see an issue with this recipe

unless you aren't going to boost it, which in that case, an hv buffered would be enough, but that's only a single ev amp.

**Comment by dimazha** [comment]
> well considering that you need an ev buffered dynamo hatch to get out 6144, which also does take tungstensteel, i dont really see an issue with this recipe
> 
> unless you aren't going to boost it, which in that case, an hv buffered would be enough, but that's only a single ev amp.

Buffered EV Dynamo doesn't need tungstensteel
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/106115870/c5108b83-3158-4a1b-bd99-8126fbab38ae)
