### ISSUE TITLE
Fire in recipes ( last nightly) 

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#15676]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.6.0 gtnh-nightly-2024-03-09+379

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

That the recipes works and that you cant craft fire ( well if a legit recipe for fire is added is okay)

### The Reality
- [x] ![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/f494902d-9b5b-4d19-966a-338bbe33fc40)
- [x] ![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/b72ab480-f302-417c-a857-7f86cb3b7f8c)
- [x] ![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/8f7700c0-8c67-4658-b0a2-643638b1aec2)
- [x] ![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/26f0d2cd-2c5d-4149-8144-b566696043c8)
- [x] ![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/052f73f4-5625-4e5b-b3b0-663ff0e632c9)
- [x] ![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/9f2bfe92-cad4-42bb-9f6e-549f191162b8)
- [x] ![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/15e81034-880f-4546-824c-112832ac6cb5)

( in the last one yes, there are 16 recipes because the output is missing)

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
`Your Pack Version` should be the release + nightly number if you are playing nightlies

**Comment by EnderProyects** [comment]
Lmao I changed it just before you coment
