### ISSUE TITLE
[ExxonMobil Chemical Plant] Pink Metal Catalyst be consumed 100% with Tungstensteel Pipe Casings(Nitric acid recipe)

### ISSUE THREAD

**Issue by KitoCedon** [GTNewHorizons/GT-New-Horizons-Modpack#15677]
### Your GTNH Discord Username

Cedon#7261

### Your Pack Version

2.5.1

### Your Server

Both SP and MP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Use CP's Nitric acid recipe with Tungstensteel Pipe Casings and HSS - S coil, because Chemical Reactor's recipe is too slow with IV Energy Hatch

### The Reality

The Pink Metal Catalyst be consumed 100% with each crafting.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by KitoCedon** [comment]
Conclusion first, I'm wrong. The CP working as intended.
If use tungstensteel pipe casing, there are 8 parallels, each parallel will Calc the consumption of the Catalyst separately. (but idk, i think it will be Calc first and applied to each parallels.)

Tested with HSS - S coils, tungstensteel pipe casing, any machine casing can run the recipe.infinite tank for air, outputting nitric acid into fluid trash can.
Case 1: Just provide the water of 1 parallel, the catalyst can be consumed in correct rate.
Case 2: Provide the enough water, the CP is running in 8 parallels, the catalyst be consumed 100% with each crafting.(but is still in correct rate if compared with steel pipe casing)

Sorry for the inconvenience.

**Comment by Pxx500** [comment]
all good
