### ISSUE TITLE
Using ArchitectureCraft cladding can crash client and brick save

### ISSUE THREAD

**Issue by dvdmandt** [GTNewHorizons/GT-New-Horizons-Modpack#15683]
### Your GTNH Discord Username

DvDmanDT

### Your Pack Version

Nightly 2024-03-09-379

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Created a test world in creative, cheated in an Architects saw bench or whatever it's called and a stack of bricks. I tried making a "Cladding", and as soon as I tried grabbing the output, the game crashed. I can't even reopen the world without crashing, even after removing my playerdata/{guid}.dat.

The AC version is ArchitectureCraft-1.9.4

### Crash Report

[crash-2024-03-10_01.33.37-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14548311/crash-2024-03-10_01.33.37-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by dvdmandt** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14548360/fml-client-latest.log)

**Comment by Superfrogman98** [comment]
There is an open pull request with a fix for this issue: https://github.com/GTNewHorizons/ArchitectureCraft/pull/18

**Comment by dvdmandt** [comment]
Ahh, so that's where I saw it! I was so sure I had seen some changes to it which is why I tested it in the first place, then I got confused when I looked through the commit log and couldn't find anything. :) Well, we should perhaps consider merging that then given how bricking this is currently.
