### ISSUE TITLE
Suggestion: Increase Indium yield from IsaMill chain

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#15686]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.5.1

### Your Proposal

Increase the yield of Indium Dust from the IsaMill/Flotation Cell/Vacuum Furnace chain from 1 per 8 Crushed Sphalerite.

The LCR method, for comparison, yields 1 Indium Dust per 9 Purified Sphalerite.

### Your Goal

The milling chain should be worth the investment.

Said chain has expensive multiblocks, including one (the Flotation Cell) which permanently locks to its recipe once used.  It also requires additional infrastructure to support it (Pine Oil, Sodium Ethyl Xanthate Dust).

Its exceptionally slow speed (especially when compared to a LCR doing the Indium Concentrate recipe), high power drain, and additional upfront costs do not merit the current benefit of not consuming Aluminium Dust or yielding Copper/Iron/Cadmium.  
Keep in mind, this chain unlocks at ZPM, at which point most players will already have enormous stockpiles of all 4 of these dusts, thus making them a non-factor in the chain's value.

### Your Vision

Processing chains should reward based on the investment required to create them.  A great example of this is the Thorium 232 chain.  The easy way produces significantly less output than the hard way, matching the needed investment and chain complexity: 
* The easy way is doable entirely in a multiblock you already have.  It uses 2 recipes.
* The hard way is 9 recipes spread across 5 machine types.

The two Indium chains have a similar architecture, and should have proportionally improved yield.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Reflex18** [comment]
![Indiumzpmlcr](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127531099/30f9e451-f16f-4472-9c32-cf534e823151)
![Indiumisamill float](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127531099/45b39cca-db4b-4b44-b374-8d05ac73f966)

I used the GTNH-flow tool to create a graph of two of the indium processes at ZPM age which is when the IsaMill chain is unlocked.

The parameters were that there is a limit of one Floattion Cell machine in the IsaMill chain and a limit of one LCR in the LCR chain.

Scale up as needed, but it should showcase just how slow the Milling chain is.

**Comment by Steelux8** [comment]
I personally did not want to rebalance this multi chain, and instead wanted to rework it with new mechanics because stuff like "permanently locks to its recipe once used" is not what I'd like to reinforce with this special oreproc. However, new multi development is currently not encouraged. 

Someone else might want to fix this, though, so thank you for coming forward with the information.

**Comment by chochem** [comment]
x3 increase with bees done in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/967

**Comment by Ableytner** [comment]
It should be noted that the 3x increase with bees was also added to the LCR method, making this suggestion still valid.
