### ISSUE TITLE
Crafting input buffer/bus not working in Chemical Plant

### ISSUE THREAD

**Issue by jimgo514** [GTNewHorizons/GT-New-Horizons-Modpack#15695]
### Your GTNH Discord Username

klim_chicken

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Please fix it, thanks

### The Reality

I tried:
Living solder (catalyst+item+fluid)
Thorium 232 (circuit+item+fluid)
Force comb (item only)
All of them not working

I saw some people have same problem in discord while making living solder.
The answer they get is the catalyst got isolate.
But in my test the item only one doesn't work too.

### Your Proposal

It should work

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
Are you playing in nightly

**Comment by jimgo514** [comment]
no

**Comment by HoleFish** [comment]
Fixed in https://github.com/GTNewHorizons/GTplusplus/pull/821
