### ISSUE TITLE
Client crash Arcane Terminal - Autocrafting

### ISSUE THREAD

**Issue by Xfos** [GTNewHorizons/GT-New-Horizons-Modpack#15698]
As the title says every time I use AE2 autocrafting thrue the Arcane terminal from Thaumic Energistics the games crashes.
[crash-2024-03-11_21.10.51-client.txt](https://github.com/GTNewHorizons/DreamAssemblerXXL/files/14564155/crash-2024-03-11_21.10.51-client.txt)

**Comment by Caedis** [comment]
Please include all relevant information found in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/new?assignees=&labels=Type%3A+Crash%2CStatus%3A+Triage&projects=&template=000-report-crash.yml

**Comment by Ethryan** [comment]
Resubmitted ass a new issue #15699.
