### ISSUE TITLE
Arcane Litmus Paper seems to not work whatsoever

### ISSUE THREAD

**Issue by ReignOfFROZE** [GTNewHorizons/GT-New-Horizons-Modpack#15702]
### Your GTNH Discord Username

reignoffroze

### Your Pack Version

2.5.1

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Arcane litmus paper is supposed to give warp readouts

### The Reality

Arcane litmus paper reads 0 warp in all categories. It also never leaves my inventory, despite it momentarily disappearing after using it, if I open my inventory and click the slot it was in it will reappear.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16232674/6a38b315-fb09-4371-a998-89861e374973)

### Your Proposal

Arcane litmus paper properly displays the warp a player has

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/73b4490e-8940-401f-a947-4ebf1177f4d2)
seem to work just fine (SP nightly 374, but also in older versions)

**Comment by ajheflin** [comment]
Yeah, I'm not really sure how to reproduce it, honestly. I just know that it doesn't work for me but for other players on my server they don't seem to have issues. I was hoping maybe someone more knowledgeable than me could provide some context as to what may be happening and why I'm the only one affected.

**Comment by ReignOfFROZE** [comment]
Yeah, I'm not really sure how to reproduce it, honestly. I just know that it doesn't work for me but for other players on my server they don't seem to have issues. I was hoping maybe someone more knowledgeable than me could provide some context as to what may be happening and why I'm the only one affected.

**Comment by LazyFleshWasTaken** [comment]
If you have a very low amount of warp, it doesn't consume the litmus paper, as it doesn't 'turn sickly yellow' or 'burn up'

**Comment by jose9222** [comment]
Having 0 ward doesn't consume the paper

**Comment by ReignOfFROZE** [comment]
Let me provide some examples from my end. Check the warp readout in the ingame info (this one seems to be accurate) and the readout in chat and observe the differences.

I currently have 0 warp and the arcane litmus paper works as expected.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16232674/89202b05-7300-453e-ba3d-739644d8eead)
If I set my normal warp to 50, it still says 0, despite the ingame info readout saying 50 sticky warp
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16232674/8082c86f-ce5c-4676-9428-c4c4844de29c)
If I take this a step further and set my sticky and temp warp to 50, and my perm warp to 20, still reads 0 in the chat while the ingame info reads correctly.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16232674/50af15d1-8161-4da4-bc1d-f794a643eaa1)

Now, I did discover the ingame info feature after I made this ticket, and I have no problem with continuing to use that workaround as it covers the necessity for me to know my exact warp for various reasons (such as avoiding nasty warp effects), so if you'd like to close this ticket that's fine as well, just wanted to give this data for awareness.

**Comment by Glease** [comment]
Do you happen to have a nickname of some sort? That is somewhere you will be referred to by the game in a name different from the one you used to login.

For example you have a nickname set via FTBU/ServerUtilities

**Comment by ReignOfFROZE** [comment]
Ah, that could be it. I do have a nickname set via SU ingame.

**Comment by ReignOfFROZE** [comment]
I also noted that this affects pure/impure tears as well... so that is a bit more game breaking. Forgot to include that in my initial comment.
