### ISSUE TITLE
Multiblock Structure Hologram Projector display incomplete display bug

### ISSUE THREAD

**Issue by kAGuyAk** [GTNewHorizons/GT-New-Horizons-Modpack#15703]
### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

I want to know the Multiblocks Structure of a machine

### The Reality

The Multiblocks Structure is not completely displayed,such as Nano Forge
![QQ图片20240312112100](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/158818662/42e931e6-3eaf-485d-adec-ba5e9529878c)
![QQ图片20240312112104](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/158818662/e9693fbf-2483-4abb-9044-599feb1415aa)

### Your Proposal

Let the Multiblock Structure Hologram Projector display normally

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
Fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2475
