### ISSUE TITLE
Computer Monitor Cover: dye alternatives not working in Assembler receipe

### ISSUE THREAD

**Issue by konradmoesch** [GTNewHorizons/GT-New-Horizons-Modpack#15701]
### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Trying to craft CMC in Assembler using GT dyes (vor e.g. Botania `Floral Lime powder`, `soapstone dust` etc.), as is possible in `Shaped Crafting` (crafting table)

### The Reality

Only original minecraft dusts shown in NEI for Assembler receipe, using GT dye not working

### Your Proposal

I think the Assembler receipe should also allow alternatives to the minecraft dyes, as is the case for the crafting table receipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by konradmoesch** [comment]
I want to join GTNH development. Starting with this issue, I took a look at `AssemblerRecipes.java` (l. 1073 does contain the recipe, I suppose)
Using
``` java
GT_OreDictUnificator.get("dyeBlue", 1L)
```
etc. in the recipe does not add any `dyeBlue` items except for `Lapis Lazuli`

``` java
GT_OreDictUnificator.get("dye", 1L)
```
just leads to switching between all vanilla dyes, but does not add any items from GT, Botania, etc.

Using for example `plateIron` in above expression allows using any of the different iron plates in oredict (from various mods)

**Comment by konradmoesch** [comment]
The assembler not accepting `dye*` items seems to also affect other recipes added by other mods (e.g. Steve's Carts "Red Pigment", which is not added in `AssemblerRecipes.java`).

**Comment by norbby42** [comment]
I just came to the Issues page to suggest this very change.  Please make it happen 👍

**Comment by konradmoesch** [comment]
If I find time, I might take a look again.
I think one would want to use the "normal" OreDict instead of `GT_OreDictUnificator`, however I did not find any other usage of OreDict in the recipes 🤔
While at it, one might also take a look at other recipes (at least the Assembler ones) and add other dye alternatives

**Comment by NotAPenguin0** [comment]
I remember I looked into this a while ago. Assemblers (and other GT singleblocks by extension) don't use oredict matching to find recipes. The way other recipes do this is by adding copies of the recipe for each permutation (see for example chests). 

I had a quick conversation about this with @chochem, and we decided it would probably not be worth it to generate a permutation for each possible combination of dyes. One good alternative would be to make an alternate recipe that only uses the GregTech dyes though.

**Comment by konradmoesch** [comment]
So it is even not possible to use OreDict with GT Singleblocks? Seems to me like another issue that should be fixed to improve UX.
I think this might also make NEI recipes better (not one recipe/page for each material alternative, but rather grouping in one recipe page where the item alternatives rotate)

**Comment by konradmoesch** [comment]
Could someone remove the label? I believe I am not allowed to do so.
Thanks!
