### ISSUE TITLE
Questbook url hotzones are wrong (again)

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#15709]
### Your GTNH Discord Username

chochem

### Your Pack Version

nightly-374

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

the clickable hotzones should line up with the link text.

### The Reality

as one can see with the debug that highlights the zones, they are off:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/fc54129e-c36b-44e3-89ec-389800e3d400)

### Your Proposal

fix it :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/BetterQuesting/pull/130

**Comment by chochem** [comment]
oh, I am blind. I saw that PR but didnt see the fix down there sneaking in the comments. will try!

**Comment by chochem** [comment]
alright, nice. indeed all fixed with BQ 3.5.9-GTNH. Thanks!
