### ISSUE TITLE
Processing Arrays cannot do UMV recipes with  down tiering enabled

### ISSUE THREAD

**Issue by Cheimuu** [GTNewHorizons/GT-New-Horizons-Modpack#15715]
### Your GTNH Discord Username

Cheimuu

### Your Pack Version

2.6.0 nightly 382

### Your Server

privately hosted 

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Trying to run a processing array using 64 UMV fluid solidifiers with down tiering enabled in 2.5.1 allows it to run recipes using UMV voltage
![251umvsolidifiers](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52509517/eee05dc5-9eba-4513-a1a0-a84da1066dd0)

### The Reality

trying to run the same processing array setup in 2.6.0 using the same UMV solidifiers prevents it from running. 
![260umvsolidifiers](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52509517/76a51b2d-9e43-4a56-bb65-01c0a8427896)

presumably related to https://github.com/GTNewHorizons/GT5-Unofficial/pull/2470 as it is the only PA related change i was able to find

### Your Proposal

Id like to see the 2.5.1 behaviour restored where downtiered processing arrays are still able to run UMV recipes so long as the machines are able to while only applying down tiering to recipes of UIV.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
This is how Down Tier works. It being able to work like this in 2.5.1 is a bug, and it's **fixed** by that pr
