### ISSUE TITLE
FastCraft crash when joining my server

### ISSUE THREAD

**Issue by Encore-Games** [GTNewHorizons/GT-New-Horizons-Modpack#15710]
### Your GTNH Discord Username

ultima_gaming_yt

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

Started up the world gen, then after it was done then I joined, then I crashed

### Crash Report

https://mclo.gs/RccFYHL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
well that log is super obfuscated and useless. but fastcraft is removed in nightlies and next stable!

**Comment by Encore-Games** [comment]
Well, thanks for letting me know about the new update.
