### ISSUE TITLE
Removal of Angelica crashed the whole game.

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#15722]
### Your Pack Version

nightly-390

### Your Server

zeta

### Java Version

Java 21

### Type of Server

None

### Your Actions

Removed angelica as I want shaders/it's not that stable in visual fx and attempt to join MP server.

### Crash Report

[crash-2024-03-14_21.21.34-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14602867/crash-2024-03-14_21.21.34-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Hikari1nVoid** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24840795/e8163b5a-f074-4b54-8267-235b9b7f211e)

**Comment by Caedis** [comment]
Can you post the latest FML client file?

**Comment by Caedis** [comment]
Also can you try with settings `fixRenderersWorldLeak` to false in hodgepodge.cfg

**Comment by Hikari1nVoid** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14603520/fml-client-latest.log)

**Comment by Hikari1nVoid** [comment]
> Also can you try with settings `fixRenderersWorldLeak` to false in hodgepodge.cfg

Seems not working for me

**Comment by Hikari1nVoid** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14603866/fml-client-latest.log)
Updated FML logs for crashes with HP-2.3.7-pre

**Comment by Caedis** [comment]
Is that connecting to a SP world or a server?

**Comment by Hikari1nVoid** [comment]
> Is that connecting to a SP world or a server?

sp.

**Comment by Caedis** [comment]
Can you try with the latest nightly, with 0 mod changes/additions besides disabled angelica?

**Comment by Caedis** [comment]
dont copy over anything from a previous save or configs

**Comment by Hikari1nVoid** [comment]
> dont copy over anything from a previous save or configs

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14604274/fml-client-latest.log)
All these crashes are happened when"creating new world" on SP.
System Rebooted to prevent any hardware related issue.
No configs are modified.

**Comment by Hikari1nVoid** [comment]
After I nuked my OS and reinstalled can't repro now.
