### ISSUE TITLE
The Thaumic Energistics crafting terminal only shows 3 rows of items PLUS does not allow fluids to be hidden

### ISSUE THREAD

**Issue by BeepBeep20** [GTNewHorizons/GT-New-Horizons-Modpack#15721]
### Your GTNH Discord Username

beepbeep20

### Your Pack Version

2.5.1

### Your Proposal

If the terminal style is left at 'small centred' the Thaumic Energistics crafting terminal only shows 3 rows of items, the normal AE2 crafting terminal shows 6 rows of items on this setting.

The Thaumic Energistics crafting terminal also has no option to 'Filter types' (ie. show items, show fluids or show both), the normal AE2 crafting terminal has this feature.

### Your Goal

The terminal only shows a very few items unless the terminal style is set to 'tall centred' & AE2 fluids cannot be hidden.

### Your Vision

A consistent style/proportion/size for the normal AE2 terminals, the fluid AE2 terminals & the Thaumic AE2 terminals.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AdolMors** [comment]
To be fair, I think the arcane crafting terminal is behind in features compared to other terminals. I heard that there should be some kind of rework going on for Thaumic Energistics, but since there is an issue here I might as well mention some other things I have found:
- Crafting CPU status (top right corner) cannot be checked
- Item count is displayed under the item instead of over the item
- Wand/scepter is not charged evenly in the terminal, as in aspects are charged at different speeds. Arcane crafting table and vis charge relay on top charge each aspect evenly. Have not bothered to check but I believe the terminal has a better charge rate overall

**Comment by NotAPenguin0** [comment]
Not to mention the arcane crafting terminal is horribly laggy.

**Comment by joseoton** [comment]
> * Wand/scepter is not charged evenly in the terminal, as in aspects are charged at different speeds. Arcane crafting table and vis charge relay on top charge each aspect evenly. Have not bothered to check but I believe the terminal has a better charge rate overall

Doesnt it depends on the amount of cv in your net?

**Comment by AdolMors** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/2e7a593b-c32d-40ac-847d-ebc091e11e92)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/c6ef80b9-ad76-40e2-a9db-965f7f4d5cc2)
I am using the same energized node to power arcane table and terminal so i have an AB comparison. 30 CVs on each aspect are way higher than the rate both stations can work with.

**Comment by AdolMors** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/d8c43c86-893b-4338-8760-25904dd6a0ba)
Seems like I made a premature conclusion. Using an empty ichor wand, the charge rate of the terminal does seem to be directly proportional to the CVs (refer to node screenshot above).
