### ISSUE TITLE
No Fluid Extractor Recipe for Tinted Honey Drops

### ISSUE THREAD

**Issue by justalyssa** [GTNewHorizons/GT-New-Horizons-Modpack#15726]
### Your GTNH Discord Username

justalyssa_

### Your Pack Version

2.5.1

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

When Centrifuging Red Colored Combs from the Red Bee (Or any of the Dye Bees), you get **Red Tinted Honey Drop's**, and then those **Red Tinted Honey Drop's** are able to be fluid extracted.

### The Reality

When Centrifuging Red Colored Combs from the Red Bee, you get **Red Tinted Honey Drop's**, and then those **Red Tinted Honey Drop's** have no Fluid Extractor recipe to turn them into Honey.

### Your Proposal

Give the Red Tinted Honey Drop's a fluid extractor recipe for 200mb of honey, and red dye.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AdolMors** [comment]
There exists this series of bees that make tinted honey (maroon, saffron etc). All tinted honey should have a fluid extract recipe to make 200L honey and 1 dye.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/7fa70afc-07b2-4e41-9810-c0ecc29885bd)

**Comment by chochem** [comment]
I mean that it is already a dye itself without extracting

**Comment by justalyssa** [comment]
> I think they are just meant to be a dye. what do you want to extract for, honey? If I remember correctly those bees give regular honey on top.

Yeah, they are both named the same, but one you get from the Maroon, saffron ext bees, which do have a recipe as you shown, but the ones from the coloured name bees, the Red Bee for example, those combs produce honey drops that arent able to be fluid extracted.

**Comment by EnderProyects** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/ce0d591b-7244-4fd2-a127-1671cdfb8007)
Well you can turn those in red chem dye, but they are already a dye themself, and the comb they come from already gives you honey drops
