### ISSUE TITLE
Storage Drawer icons flicker/become darker when close, but are normal when further away

### ISSUE THREAD

**Issue by dhasial** [GTNewHorizons/GT-New-Horizons-Modpack#15725]
### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Expect storage drawer icons to not flicker depending on where I'm standing

### The Reality

Storage drawer icons appear to almost change lighting levels when I'm close, and go back to normal when I'm further away

### Your Proposal

Here's a (pretty bad quality) video that should hopefully show the issue clearly enough

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/44693166/907605e0-75e4-4d0c-b3e4-df50a0219767

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
What happens if you hide holoinventory/take off the hologlasses

**Comment by dhasial** [comment]
It doesn't make any difference. I think it's able to be replicated by going outside of whatever the render distance is set to (centered on the drawers), and teleporting back into range, but I'm not completely sure.

**Comment by dhasial** [comment]
Totally by random chance, I found that toggling when WAILA I found that the drawers only had the weird shadow issue when WAILA's overlay was showing. When I toggle it off they appear normal.
