### ISSUE TITLE
Animated block textures don't work unless I look directly at them at close range.

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15720]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Animated block textures should be animated when the block in question is visible to the player.

### The Reality

Animated block textures do not animate unless I am looking _directly_ at the block in question (or a block of the same type) at close enough range to allow interactions such as mining said block.

This is _not_ an issue with TPS; the data displayed by the "xu_tps" command demonstrates that I consistently have 20 TPS with no issues. I have attempted to ask about this issue in the Discord, but there has been no response.

### Your Proposal

Fix this? I can provide additional information if I'm given some guidance on _what_ additional information to provide.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DryCryCrystal** [comment]
I'm also experiencing this on 2.6.0, multiplayer, Java 21, & without angelica.
