### ISSUE TITLE
Output Hatch (ME) can't have its output go directly into a fluid storage bus

### ISSUE THREAD

**Issue by Shadowsoftime99** [GTNewHorizons/GT-New-Horizons-Modpack#15727]
### Your GTNH Discord Username

Shadows#4865

### Your Pack Version

2.5.1

### Your Server

private

### Java Version

Java 17

### Type of Server

None

### Your Expectation

I have an LCR running a recipe in a subnet. I want to push its fluid outputs (a mix of intermediate and byproducts) into the subnet, and then have the byproducts go through a filtered fluid storage bus into the main net while the intermediate fluids stay within the subnet and are routed to their next step.

Basically, the flow for the byproducts should be:
ME output hatch -> subnet -> fluid storage bus -> mainnet
and the intermediates just go:
ME output hatch -> subnet -> next machine (ME export bus)

### The Reality

The byproducts get stuck in the hatch, because it perceives them as having nowhere to go. Putting generic fluid storage into the subnet lets them get pushed out, but only into there and they now just "sit" there instead of being routed into the main net.

Also, this concept works freely with normal GT hatches and interfaces. So this flow:
fluid hatches -> dual interface -> subnet -> fluid storage bus -> mainnet

works totally fine. Even though the ME output hatch should be _identical_ to the [fluid hatches -> dual interface] chunk.

For what it's worth, I've also observed this behavior with the solid equivalent (the ME output bus). It can't seem to place items directly into a storage bus; it puts them in an overflow chest first which is being constantly pulled from by a conveyor, and then they'll get put into the storage bus after one cycle.

### Your Proposal

Make the GTxME output blocks work identically to what they're supposed to be replacing here.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
ME hatch itself = fluid hatch + dual interface. Just use cable to connect it to your net .

**Comment by Shadowsoftime99** [comment]
Like I literally said, the ME hatch isn't working the same way the normal hatch + dual int work. They SHOULD be the same, for sure.

**Comment by Persus1** [comment]
> ME output hatch -> subnet -> next machine (ME export bus)

Thats not how ME output hatches work (In your case just swap the ME export bus for a storage bus). Your ME System cant access the contents of an output hatch/bus like its an ME Drive. Thus it gets stuck if not every single content has a destination. You need to make a little storage inside your subnet for all products that should be kept in your subnet. Imo everything works as intended.

**Comment by Shadowsoftime99** [comment]
The "subnet" segment in there includes some storage that the fluid can (and does) pass through, if needed. That has nothing to do with the inconsistency here, anyway. That portion works fine, in either case.

**Comment by Persus1** [comment]
So you mean something like this? I really cant see any inconsistency.

Byproducts get directly sent into Mainnet(Partitioned storage busses):
![2024-03-18_16 59 37](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/130587498/a2da8487-ca93-4e04-b880-6f037e03ab9a)
Same Setup just with the ME variant:
![2024-03-18_17 00 57](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/130587498/d17e3e82-764a-4fe1-b68a-bba0f1b2d31b)

Both setups work exactly the same (2.5.1)

**Comment by Shadowsoftime99** [comment]
Those are nice pics to show what I'm talking about.

Yeah, those two setups, except the bottom one _does not work_ for me and hasn't in the multiple different ways I've tried. The top works fine despite the fact that they should be logically identical.

One guess: is it maybe only an issue with multiple fluid outputs in the same ME hatch? For example the one LCR had both NO and Oxygen byproducts and both of them should be routed back into the main net.

**Comment by Persus1** [comment]
I tested it with the same recipe (I assume its the Potassion Dichromate Dust one) and both fluids end up in the mainnet. Are you sure you have enough space for both fluids in your mainnet? Or you maybe accidentally partitioned the wrong fluids? Or you used a normal Interface on your mainnet side? Try the NO only recipe with ammonia and oxygen for example and see if it works.

**Comment by NotAPenguin0** [comment]
ME hatches and buses can get stuck when trying to push things into the network if there's not enough room for *everything* in the hatch.

**Comment by Shadowsoftime99** [comment]
And does it consider a storage bus as only having one "type" space? That'd be an explanation.

> Are you sure you have enough space for both fluids in your mainnet? Or you maybe accidentally partitioned the wrong fluids? Or you used a normal Interface on your mainnet side?

Yes to all the sanity checks; the biggest thing was that the hatch -> interface version DOES work, which wouldn't be the case if most of the other things were configured wrong. I might go back into the discord with screenshots for comparisons
