### ISSUE TITLE
Wand Focus: Maintenance Frugal upgrade not working

### ISSUE THREAD

**Issue by Kyramesh** [GTNewHorizons/GT-New-Horizons-Modpack#15736]
### Your GTNH Discord Username

Kyramesh

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Upgrading the Maintenance Focus should reduce the vis cost of using it. 

### The Reality

Applying the upgrdes does not affect the focus. See screenshot of the focus in the focal manipulator: 
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/154308959/26df6630-1199-4cbc-8cd4-a56842488fb9)
The vis cost is still identical withe the base cost, even with 5 upgrades applied. Using the Focus in a satin capped greatwood wand (5% inherint vis discount from caps) and with no further discount from gear shows a cost of 45% (5 from caps and 5x10 from the upgrades) 
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/154308959/2aecec7f-32de-49a1-9fd0-520b953faeda)
The thaumcraft wand UI shows the expected cost of 11.25 vis.
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/154308959/c61b8ef2-68af-4b2d-8d06-9ab642b40013)
Using the focus deplets about 23,75 Vis though (this value in the UI is rounded). Only using the vis discount of the caps, but not of the frugal upgrades.
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/154308959/b338c60f-35cf-4b77-a337-15e11d4984e0)

Using discount 40% vis discount gear reduced the cost to 13,74 vis (total discount of 72,52%) when it should be 2.5 vis (90% discount, which i assume is the cap). 
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/154308959/52c4c38a-fc12-4fc0-80e9-091a77f4d91a)

### Your Proposal

Make the wand focus correctly use the discount from the frugal upgrades. If the upgrade is not supposed to be useable with this focus then do not let players apply it. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Aurastorm** [comment]
I am experiencing this same problem. I crafted a thauminite capped amber staff so I could use the maintenance focus but actual usage tells me that I'm getting a 66.48% total cost as opposed to the advertised 16.48% as shown by the staff.
Kinda sucks when I'm doing maintenance rounds to only be able to use the focus once or twice before having to wait for the staff to completely recharge.

**Comment by dimazha** [comment]
The same problem in 2.6.1

**Comment by ebmusicman84** [comment]
Having the same issue still, 07/27/24

**Comment by hacker-on-steroids** [comment]
bump

**Comment by Ethryan** [comment]
Has been fixed in dev

**Comment by ZenMasterSych** [comment]
GTNH 2.7.2, issue persists
