### ISSUE TITLE
Molecular Assembler has unintended easy mode recipe

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#15739]
### Your GTNH Discord Username

chochem

### Your Pack Version

nightly 388

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

it should require titanium and an ev assembler, like this one 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/043a5d93-2cec-4cc7-9280-19d4dceba9e6)
which does exist.

### The Reality

This one also exists:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/b3d4bfb7-a10c-476d-9fb8-29be791cfc85)

### Your Proposal

remove it and double check other AE recipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
also: nether quartz wrench, nether quartz knife

**Comment by EnderProyects** [comment]
The smelt recipe for the skystone has been nuked, and any of these can´t be crafted
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/a52a9751-d167-4c56-aa5a-bf15c734773b)
