### ISSUE TITLE
GTNH crash when loading world

### ISSUE THREAD

**Issue by Beans5** [GTNewHorizons/GT-New-Horizons-Modpack#15737]
### Your GTNH Discord Username

beans6942

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

Was playing normally last night but got on today after closing the game and it instantly crashes, but better crashing stops the game from exiting

### Crash Report

making a new singleplayer world fixes works fine i just 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Beans5** [comment]
[57MbihLa.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14623012/57MbihLa.txt)
for whatever reason i couldnt get the file to attach to the original one so here it is
also note i have no coding experience so i have no idea whats up with this code

**Comment by Pxx500** [comment]
try a backup, probably just a chunk corruption

**Comment by Beans5** [comment]
> try a backup, probably just a chunk corruption

using curseforge and cant seem to find any backups

**Comment by Pxx500** [comment]
Try reinstalling game, best with multimc or prism launcher. If this does not help and you don't have any backups than I'm afraid it will take much more effort to get your save back and running, but I don't know how to help in that case. Backups are a must playing GTNH.

**Comment by chochem** [comment]
> > try a backup, probably just a chunk corruption
> 
> using curseforge and cant seem to find any backups

in the backup folder

**Comment by Beans5** [comment]
so i gave up and created a new world played like normal logged off the first day and it was fine, the second day i logged off the same and was not receiving the any error, i logged on today and its happened again, ive gone back 3 backups (1.5 hrs) and they all are broken any help on this please i am actually enjoying this mod and dont wanna start again
