### ISSUE TITLE
EoH controller scanner gives predertemined output

### ISSUE THREAD

**Issue by Cheimuu** [GTNewHorizons/GT-New-Horizons-Modpack#15747]
### Your GTNH Discord Username

@Cheimuu

### Your Pack Version

2.6.0 nightly 382 + TecTech 5.3.40

### Your Server

privately hosted

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Using the electric scanner to show the expected dwarf matter or universium aswell as plasma mixture results should the run succeed while considering the factors that would affect their output. namely nei output, parallels, yield.

### The Reality

When starting a run of the EoH and then using the scanner on the controller, rather than just showing the estimated matter output values based on their factors, it currently shows a value that has already determined whether or not the current run has succeeded or failed and how much it will actually output once the current run finishes.

this allows you to break the controller and restart the run without waiting for it to finish, effectively letting you speed up the current run at the cost of the power output.

### Your Proposal

Return the old behaviour of it only showing how much it would yield should the run succeed, rather than predetermining what the output will be.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
The old one works in the same way
