### ISSUE TITLE
Cerium-doped Lutetium Aluminium Garnet laser engraving lenses seem to be flipped

### ISSUE THREAD

**Issue by Cheimuu** [GTNewHorizons/GT-New-Horizons-Modpack#15748]
### Your GTNH Discord Username

@Cheimuu

### Your Pack Version

2.6.0 nightly 382

### Your Server

privately hosted

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

When upgrading laser engraving for crystal SoCs and raw advanced crystal chips i would expect the engraving to change the ingredient while keeping the same colour of lens to do the engraving with.

### The Reality

When upgrading from their previous version to Cerium-doped Lutetium Aluminium Garnet for both Crystal SoCs aswell as Raw Advanced Crystal Chips the colour of their lenses seems to be flipped.
As all existing wafer engraving recipes keep the same colour of lens when moving to a higher grade wafer, this seems to have been flipped by accident.

Crystal SoCs
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52509517/ba58d6aa-4f66-4c21-baf1-94c666a88c2a)
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52509517/b2f1ac8c-a770-4ba5-bb7d-d29292b17609)

Raw Advanced Crystal Chip
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52509517/427c9fe4-9c8c-45ae-8b85-5ef57703fd06)
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/52509517/c66a9f35-f37c-4828-8e37-9bba607d21c0)

### Your Proposal

Either switch the lens colours between these two to their original or tell me that its indeed intended and close the issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Nxer** [comment]
Is it necessary or if I flipped these two recipes' lens may cause someone problems?

**Comment by NotAPenguin0** [comment]
Shouldn't cause any problems, but consistency is nice IMO.
