### ISSUE TITLE
GraviChestplate quantum shield does not work with the Quantum Boots of the Voidwalker

### ISSUE THREAD

**Issue by Johny00225** [GTNewHorizons/GT-New-Horizons-Modpack#15745]
### Your GTNH Discord Username

Johny002

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Turn on the quantum shield while wearing the Quantum Boots of the Voidwalker from the Thaumic Boots mod. Expect the shield to work, since i am technically wearing full quantum armor (I am wearing fully charged Solar Goggles of Revealing, GraviChestplate, QuantumSuit Leggins, Quantum Boots of the Voidwalker).
![2024-03-17_00 38 40](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/163686853/5ddfbd42-6ee3-4545-9f99-46bd8fdbf2cb)

### The Reality

GraviChestplate states: Error: Can't find Shield relays; Shield cannot be activated
![2024-03-17_00 38 59](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/163686853/d7c996b7-6041-47cb-99e4-473b2e27829c)

The game probably doesn't recognize the boots as a part of the quantum armor set.

### Your Proposal

Add the Quantum Boots of the Voidwalker to the list of allowed boots for the quantum shield. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
already fixed by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/15438
