### ISSUE TITLE
AE facade not letting EU through

### ISSUE THREAD

**Issue by HeavenOfAngels** [GTNewHorizons/GT-New-Horizons-Modpack#15753]
### Your GTNH Discord Username

Heaven of Angels

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

AE facade used to cover a hole in a wall with a GT cable (specifically a 64x EV superconductor) running through so I can cover that hole in the wall while power should still be transferred through. Cable will not connect through the facade.
![Top cable not connected](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/131214549/77aa5741-d3c1-42c0-82d2-7bbe4ec9719b)
![Bottom cable connected](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/131214549/8fd69ef1-a343-4be0-a1fb-d3c56f382dbb)

### The Reality

Power is not transferred through the AE facade. After removing the facade power was available again at machines behind the facade.

### Your Proposal

Make it that AE facades used to cover a hole in a wall where a GT cable runs through still transfer power to the cable behind the facade by making it that GT cables connect through AE facades like AE cables connect through AE facades.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
iirc there is a way to do this, but forgot which tool it is. So try right clicking with the screwdriver or the wirecutter. But the default is intended to let nothing to pass. Not a bug.

**Comment by HeavenOfAngels** [comment]
Hmmm I did try some stuff with the wirecutter and the screwdriver, and I think I got it to work. However it is far from intuitive, as first you have to set the facade with the screwdriver to "Energy" and then connect the wires through the facade with the wirecutter. But yes, the problem seems solved.
