### ISSUE TITLE
GTNH randomly bricks server

### ISSUE THREAD

**Issue by Nillaes** [GTNewHorizons/GT-New-Horizons-Modpack#15756]
### Your GTNH Discord Username

nillaes

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

None

### Your Actions

I have a (home) server that is running exactly as the setup guide says, using all the default settings. Occasionally the server freezes and bricks my server. with "bricks" I mean that i can't ssh into it, ping it, or access any other services running on it. The computer is still running though and (based on the amount of log files) the server is technically still running since it doesn't try to restart.

The GTNH server is very new (setup 3 days ago) and initially had not given any issues for over 27h. at some point last night it crashed for the first time and has crashed again today. 

After the first day of playing (before the first crash) I have added to the server ServerUtilities for backups, claims, etc

### Crash Report

[fml-server-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14628929/fml-server-3.log)

I think the cause of the crash is the ServerUtilities mod backup function i think when it tries to backup it gets stuck and bricks the server.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
if your server is saturated by the pack that's an issue indeed. What is your cpu and what's your total amount of memory/memory given to the NH server?

**Comment by Nillaes** [comment]
The CPU is amd ryzen 1500 the server has 8gb of RAM 6 of which are dedicated to NH.
