### ISSUE TITLE
IronFox Nexus

### ISSUE THREAD

**Issue by maya343** [GTNewHorizons/GT-New-Horizons-Modpack#15769]
### IP

23.139.82.94

### Whitelist Status

no whitelist

### Server Name

IronFox Nexus

### Primary Language(s)

English

### Region(s) of Service

US/EU

### Additional Info

Join our discord! https://discord.gg/7bUSN5P64m

**Comment by Dream-Master** [comment]
@maya343 server location ? EU or US ?

**Comment by maya343** [comment]
> @maya343 server location ? EU or US ?

its US
