### ISSUE TITLE
Tile entities turning transparent

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15767]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

N/A

### The Reality

Many tile entities have started to turn transparent in my save; they are not completely invisible; instead, they become almost entirely translucent. This happens entirely at random, and does not always affect the same blocks. Additionally, there appear to be certain very specific camera angles at which the blocks in question return to normal; if I change the angle of my view away from these specific angles, the issue returns.

The tile entities in question do not appear to lose any functionality, and the visual bug can be _temporarily_ resolved by the "F3+S" key combination, which - as far as I understand - forces a reload of some kind. However, the issue returns very quickly after doing this (although it usually chooses a different random subset of applicable tile entities).

I have never observed this issue occurring with Gregtech tile entities or Architecturecraft blocks (though I don't know whether those even _are_ tile entities), nor have I observed it occurring with any tile entities whose model is merely a standard block. I have most commonly noticed the issue affecting chests (vanilla chests, compressed chests, or chests from the Iron Chests mod), Ender IO blocks (such as the enchanter, though _not_ including conduits (whether conduits are not susceptible or whether I have simply not observed them to be affected is unclear)), and a few other tile entities with complex models (such as vacuum hoppers).

### Your Proposal

I have asked in the GTNH Discord about this issue. Several people have said that it is an issue with either Optifine or Angelica. I have neither of those mods installed, so this is false. I do not have any TPS issues according to the "xu\_tps" command, so this cannot be a TPS issue either. I have so far been unable to find _any_ conclusive information about what could be causing this problem, so determining the cause is likely the first step that must be taken in order to resolve the issue. If there is any other information that I _could_ provide that would be beneficial, please let me know what sort of information that would be.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by hallucinogender** [comment]
Update on this: I also just checked whether this is based on specific chunks. It is not. This issue tends to affect _only some_ tile entities of the same type within the same chunk, even if there are many tile entities of that type present. It is also independent of remote chunkloading methods, as far as I can tell.

**Comment by chochem** [comment]
sounds a lot like this mystery ticket that nobody could reproduce https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12974

**Comment by BeepBeep20** [comment]
I had a similar problem, with chests (vanilla + modded chests) where they were transparent from some angles, but normal from other viewpoints & I found out what caused the problem for me.

I place items on the walls quite a lot. using the Draconic Evolution way of placing things in world & I had placed an item that had the enchanted glow, it was a golden lasso with a villager inside.

Once I removed the golden lasso from the wall, the chests went back to looking normal.

**Comment by TimeConqueror** [comment]
I got such glitches about half a year, when enchanted spikes from Extra utilities were in the world. And chests became semi-transparent when spikes were in the screen, but not always. Maybe this is you case too?

**Comment by BeepBeep20** [comment]
> I got such glitches about half a year, when enchanted spikes from Extra utilities were in the world. And chests became semi-transparent when spikes were in the screen, but not always. Maybe this is you case too?

Yes, it might be linked. Both of our problems were caused by enchanted items from the same mod, Extra Utilities.

**Comment by hallucinogender** [comment]
My world does not contain any items placed using the Draconic Evolution mechanic. However, I _do_ have some enchanted diamond spikes, so that is additional correlation. I have not encountered the problem since updating to 2.6.0 Beta 1, though I don't think I can be certain that this means that the problem is gone.
