### ISSUE TITLE
All wireless energy gone after updating to Nightly (396)

### ISSUE THREAD

**Issue by Eranicus** [GTNewHorizons/GT-New-Horizons-Modpack#15765]
### Your GTNH Discord Username

Eranicus#5476

### Your Pack Version

Nightly (396)

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

.

### The Reality

After loading my world from 2.5,1 (clean stable) to Nightly (396) all the wireless energy is gone...

![Screenshot 2024-03-20 014830](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92493145/f454f280-e14b-4c5e-a253-748237992641)

![Screenshot 2024-03-20 015042](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92493145/14b3ace8-a6ad-43f6-9530-42ea6b02c0fc)

Prior to v396 I loaded v390 and the situation was the same. 

### Your Proposal

Fix please.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
(just gonna rewrite the info from discord here again. )
I'm in zeta and on nightly 390, no issues with wireless EU so might be inconsistent.

**Comment by Hikari1nVoid** [comment]
Can not repro with command set wireless networks from 2.5.1 ->396
Need fml-client-latest for details
seems like a LSC crash.

**Comment by Eranicus** [comment]
Will update here also.

After updating from 2.5.1 to v361 or v373  and entering world  LSC  is broken 

![Screenshot 2024-03-20 053528](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92493145/95b70efd-24ef-454d-a66f-4e40622fbfbd)


After restarting it, energy is jumping like crazy

![Screenshot 2024-03-20 050113](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92493145/97ab87c2-b32f-4c85-8ebd-01d4ff2d206e)

![Screenshot 2024-03-20 050600](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92493145/961eb38f-21ca-4a6c-bc4e-16c19dcd94a3)

![Screenshot 2024-03-20 051159](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92493145/1e1e651c-14f4-4edf-b689-8a3fc62f9b87)




As for updating to 396  LSC  is ok but energy is 0 

![Screenshot 2024-03-20 055542](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/92493145/c2c3f4ff-43d3-4cbb-bf35-b2cd268434b7)


fml-client-latest.logs :

[361 fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14661696/361.fml-client-latest.log)

[396 fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14661706/396.fml-client-latest.log)

**Comment by Lyfts** [comment]
You are using a pirate launcher...
Feel free to reopen if you manage to reproduce with a legit account.

**Comment by pulsemageadvocate** [comment]
I update from 2.5.1 to 2.6.0-beta-1 and I have same issue.
I use vanilla forge server and Java17.
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14758267/fml-server-latest.log)

2.5.1
![20240326_251](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/59131259/7e9f4590-cc4f-4821-b4ae-fb4434041348)

2.6.0-beta-1
![20240326_260b1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/59131259/c801f14d-1d8f-4f03-b7b6-1a51f1783bfc)

I see EoH error log but removing EoH Controllers before update did not work.

**Comment by pulsemageadvocate** [comment]
Reproduced data
[GregTech_WirelessEUWorldSavedData.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14791543/GregTech_WirelessEUWorldSavedData.zip)

**Comment by Hikari1nVoid** [comment]
> Reproduced data [GregTech_WirelessEUWorldSavedData.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14791543/GregTech_WirelessEUWorldSavedData.zip)

Did you always use online mode?need to ensure that you did not turn online mode on/off during update.

**Comment by t-jk-co-jp** [comment]
> > Reproduced data [GregTech_WirelessEUWorldSavedData.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14791543/GregTech_WirelessEUWorldSavedData.zip)
> 
> Did you always use online mode?need to ensure that you did not turn online mode on/off during update.

I was playing single player, and moved to online during 2.5.1 about 3 months ago.
I have never been back to single player.

**Comment by pulsemageadvocate** [comment]
> > Reproduced data [GregTech_WirelessEUWorldSavedData.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14791543/GregTech_WirelessEUWorldSavedData.zip)
> 
> Did you always use online mode?need to ensure that you did not turn online mode on/off during update.

I was playing single player, and moved to online during 2.5.1 about 3 months ago.
I have never been back to single player.

**Comment by NotAPenguin0** [comment]
Can confirm, updated from 2.5.1 to 2.6.0-beta3 and my entire wireless EU network was cleared.

**Comment by pulsemageadvocate** [comment]
Fixed in 2.6.0 in my case.
