### ISSUE TITLE
Apply Kuba's pattern optimization to the rest interface which can hold patterns.

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15766]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.0 build 3.9.0

### Your Proposal

add support to the rest 3 items that can hold patterns. "dual-interface", "item crib", "item&fluid crib"
(I did comment under the original pr but no reply yet, I guess a suggestion is better.)
update:
dual is done, cribs left

### Your Goal

to make the pattern optimization function work well as a whole. I love the function.

### Your Vision

make GTNH greater.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by kstvr32** [comment]
This seems to have been implemented for AE2FC by Kuba in GTNewHorizons/AE2FluidCraft-Rework#200.

I'm going to take a look at adding support for CRIBs

**Comment by kstvr32** [comment]
After some testing it looks like this does work for CRIBs. I think this issue can be closed.

**Comment by miaowwwwww** [comment]
> After some testing it looks like this does work for CRIBs. I think this issue can be closed.

![image](https://github.com/user-attachments/assets/1123bb51-76ab-475c-8c46-a11acdd65522)
![image](https://github.com/user-attachments/assets/690d8d89-323e-41ac-8de1-6118d434ec96)
it does not have this 2 buttons at the left

**Comment by kstvr32** [comment]
CRIBs are supported for the pattern optimization matrix (done when crafting). 

I cab add support to disable optimization and double/half in the CRIB itself.

**Comment by chochem** [comment]
was resolved
