### ISSUE TITLE
Can push but unable to pull batteries out of battery buffers.

### ISSUE THREAD

**Issue by MrGundum** [GTNewHorizons/GT-New-Horizons-Modpack#15764]
### Your GTNH Discord Username

MrGundum

### Your Pack Version

2.5.1

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Unable to pull batteries out of battery buffers. I tried Conduit,hoppers and item pipes.
I tried LV and MV battery buffers, both had the same result of being unable to pull batteries out of the buffer.

### The Reality

Items where not pulled out of the battery buffer

### Your Proposal

You can use a hopper or conduit to push batteries into a battery buffer but you are unable to pull the batteries back out of the battery buffer. I don't know if this is a bug or intended behavior. I tried a couple search for open/closed tickets and didn't see any other mentions of this.

Trying to create a train network of transporting batteries to various outposts rather than fuel.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
This is intended. The quest mentions it, iirc.
