### ISSUE TITLE
Frame boxes being a tile entity and its effects on server performance.

### ISSUE THREAD

**Issue by Sixtal** [GTNewHorizons/GT-New-Horizons-Modpack#15761]
### Your GTNH Discord Username

Clta

### Your Pack Version

2.5.1

### Your Proposal

Change frame boxes to non-tile entity or replace multi-block frame boxes with non-tile blocks.

### Your Goal

Frame boxes being tile entities causes unnecessary lag and should not be a part of multi-block structures. This mostly effects end-game bases with a lot of compact fusion rings and long neutron activators. Here are surveys for the players on eta
-using an average of 202ns per frame box-
(220,300,230,90,220,322,278,80,80,92,180,225,245,190,290 Average [**202 ns**] per frame box)

C=Compact Fusion (128 blocks)
A = Neutron activator (n,Height,Wall Sheared?)
P = PCB Factory (49 blocks)
S = Space elevator (56 blocks) 
N = Nanite tower (T1=170,T3=252)

Logos = A:(3,9,No)=[21,816ns], P:1=[9,898ns]
Total = [**31,714ns**]

Delay___ = 1245 frame boxes told in person 
Total = [**251,490ns**]

Clta = C:1[25,856ns], A:(3,48,No)=[116,352ns], P:1[9,898ns], S=1[11,312ns]
Total = [**163,418ns**]

Jocroy = C:14[361,984ns], A:(3,65,Yes)=[105,040ns], P:1[9,898ns], S:1[11,312ns], N:T3[50,904]
Total = [**539,138ns**]

Jocroy's (UXV) personal dimension usually costs about 10 ms and he is wasting 0.54 ms on frame boxes that do absolutely nothing. that is a 5% possible improvement and is easy to implement.

### Your Vision

Reduces unproductive lag that frame boxes cause on multi-block structures.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
can't really turn them into non ticking blocks because the frameboxes are also used to apply covers on them, like wireless redstone cover. A biggest offender are the laser pipes.

This is the kind of stuff that cannot be easily changed unless all the players agree that their multi will unform with an hypothetical update changing the blocks required by the structure check.

**Comment by LewisSaber** [comment]
Is it not possible to start ticking when player places any cover?

**Comment by Sixtal** [comment]
Why not have a frame box that is a non-tile entity with the existing one that is a tile entity so people can pick and choose which one they want, at least for the frame boxes that are used in multi-block construction. I feel like this is something that needs to be done eventually.

**Comment by Eranicus** [comment]
I dont think its a big problem if a special announcement will be given together with some pack update.

On the other hand, Mutes should eventually remove this problem in future.

But 0.54/50ms is alot considering these are just frames which were probably made as ticking by mistake.

**Comment by Connor-Colenso** [comment]
ModernMaterials tackles this issue by making all frames by default non-ticking "dumb blocks", with some frames allowed to opt into being a TE if they need a TESR attached (think universium type renderering). Same for all ores.

But like boubou says this has substantial wider concerns and is not something we can just throw into the pack without way more discussion. People would need a significant warning period to move their important stuff off of frames.

**Comment by boubou19** [comment]
This is also why i yeeted all the muffler hatches in the MBF.

But really if you want to tackle lag on official servers, optimise your AE systems with the advices on the wiki. the passive lag described here is only .5 ms, while the AE2 systems are responsible for between 20% and 30% of the server load, and it's not shown in any tps measure. This also means most of the time the TPS measured are always off.

**Comment by Sixtal** [comment]
I understand now that this has a wider concern and going through with the change will need significant warning time for the players who do use frames with covers. Also the part where AE systems cost 20-30% of all server resources but its not feasible to control players to build the most efficient and optimised systems to lower server load and the difficulty of determining the lag from an AE system in the first place. I already deploy all the good practice rules myself. If we really want to reduce AE lag on official servers we would need better tools for lag control made for AE. Finally the frame box change suggestion will have an instant effect albeit small (3%-5%).

**Comment by miaowwwwww** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12920
