### ISSUE TITLE
Earthquake server domain name change

### ISSUE THREAD

**Issue by FlandreS** [GTNewHorizons/GT-New-Horizons-Modpack#15770]
### Your GTNH Discord Username

flan.cat

### Your Pack Version

2.5.1

### Your Proposal

Change the previous domain holder's information to the server's new domain info.

New IP/domain: flancat.ddns.net
Old: aragil.ddns.net

### Your Goal

Corrected connection details in next stable release.

### Your Vision

Multiplayer : )

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by FlandreS** [comment]
Bumping with hopes to get this in for 2.6.1 - Currently we're dead on the default server list.

**Comment by BattleGuy03** [comment]
I was so confused by this for a few weeks, I finally looked it up on the discord server and found out the IP had been changed!
This needs to be updated.
