### ISSUE TITLE
Fortress Blade renders incorrectly when in Battlegear weapon slots

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15772]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

The Thaumium Fortress Blade from Tainted Magic has a custom model that is attached to the player model when the blade is in the player's inventory.

Under _normal_ circumstances (i.e. when the blade is contained within a player's vanilla inventory), the blade has a sheath to the wielder's left side; the sheath is always in the same position as far as I can tell, and it changes its appearance depending on whether or not the sword is in the active hotbar slot. The normal appearance is illustrated here:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/7af7b140-78ea-4903-a764-0c2eed41d356)

The blade is able to be placed in Battlegear weapon slots. The sheath _should_ render correctly when the sword is in the Battlegear slots.

### The Reality

When the Thaumium Fortress Blade is in a Battlegear weapon slot, the sheath is not rendered as far as I can tell. The sword itself shows up properly when it is in the active weapon slot, but at all other times it will be incorrectly scaled and will clip through the player model at a strange angle, as illustrated here:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/1fdfbf2c-41f3-4d96-be0e-3ae39f5947d3)

### Your Proposal

The Thaumium Fortress Blade should have its custom model adjusted so that it works properly with Battlegear weapon slots. Additionally, while I have not yet tested the _other_ "fortress blade" variants in Tainted Magic, they should be checked for the same issue and likewise be fixed if needed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
something similar also happens with the kikoku, iirc.

**Comment by hallucinogender** [comment]
It seems to be something to do with the way Battlegear renders inactive weapons. Further testing has revealed that the broken render only shows up at all when the weapon slot containing the sword is the most recently active weapon slot prior to switching back to the normal hotbar; this is the same weapon slot that determines which inactive weapons are to be rendered. It seems that Battlegear is attempting to render the blade's unsheathed form (i.e. the model that gets held in the player's hand), and does not properly handle weapons with special models such as this one.
