### ISSUE TITLE
microblock+ae crash

### ISSUE THREAD

**Issue by sinandds** [GTNewHorizons/GT-New-Horizons-Modpack#15788]
### Your GTNH Discord Username

xebecnyc

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

i was trying to put down an AE smart cable onto a forge microblock pillar of a caelest i expected it to just place 

### The Reality

it crashed when i tested it again it crashed again and it replaced a handful of blocks randomly in the world with blood rune blocks

### Your Proposal

i dont know

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
Not sure how you expect anyone to help without a log of sorts....
