### ISSUE TITLE
CraftPresence erroring on server update to 2.6.0 Beta 1

### ISSUE THREAD

**Issue by twgecko** [GTNewHorizons/GT-New-Horizons-Modpack#15786]
### Your GTNH Discord Username

twgecko

### Your Pack Version

2.6.0.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

Attempting to update to 2.6.0 beta 1, craftpresence unloading and erroring

Running a linux server with an oracle VM, went through standard process of deleting mods, configs, libraries, and scripts folder when updating from 2.4.0 and replaced with latest beta versions. Also updated lwjgl3ify-forgePatches.jar, java9args.txt, startserver-java9.bat, and startserver-java9.sh

Starting server with command bash startserver-java9.sh

### Crash Report

https://pastebin.com/awMj05cQ

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by CDAGaming** [comment]
CraftPresence is *not* a server-side mod. This issue should be considered invalid as-such...

**Comment by twgecko** [comment]
> CraftPresence is _not_ a server-side mod. This issue should be considered invalid as-such...

So really the "fix" from this post is that Craftpresence should be removed from the server pack in future updates, as it doesn't belong there

**Comment by Caedis** [comment]
Its not. It seems like you used a client zip for the server

especially given you also have DuraDisplay
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18713839/cbf35556-e1e6-4ed5-8370-59859963e7d0)


![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18713839/bed57171-a225-4053-9338-1001dc4ab693)


![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18713839/a42abe05-7dbf-4b77-b18b-57958d594263)
