### ISSUE TITLE
Un-nest gt++ energy cores

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#15782]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.5.1

### Your Proposal

Energy cores from gt++ are used in several recipes, including but not limited to compact fusion coils, elemental duplicator stuff, several multiblock controllers, and energy buffers of their associated tier.

### Your Goal

This would help lower recipes in the end-gam, and remove unnecessary steps, therefore trimming crafting trees. It might also push people into trying out energy buffers at their tier, especially lower tiers, where such big storage are a great boon.

Making these buffers craftable in the late stages of that tier would also help with that, though I'm not sure that that would be an acceptable balance change.

### Your Vision

Trim crating trees and remove unneccessary nesting of recipes. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Impos913** [comment]
They used to require 4 of the previous tier to craft 🤣

**Comment by Hikari1nVoid** [comment]
typical gtpp moment

**Comment by Reflex18** [comment]
The energy cores also vastly inflate the costs of the portable energy buffers along with the fact that the mv and up buffers are not even craftable untill iv age due to needing the gt ++ materials from the alloy blast smelter.
