### ISSUE TITLE
2.6.0 Beta 1: I left-clicked on a thaumometer in my inventory and the game crashed

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15794]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.6.0 Beta 1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

I left-clicked a thaumometer in my inventory and the game crashed. This is after updating from 2.5.1 to 2.6.0 Beta 1. The same thing happens now every time I try to click on the thaumometer.

### Crash Report

[crash-2024-03-23_18.58.09-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14733341/crash-2024-03-23_18.58.09-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BritishCynic** [comment]
Can confirm, happens with 2.6.0-b1 and my world came from Nightly 396

**Comment by marcinmagazyn** [comment]
Same, got the 2.6 beta, https://mclo.gs/HD5bmaV

**Comment by chochem** [comment]
seems like its caused by https://github.com/GTNewHorizons/ThaumicInventoryScanning/pull/6
