### ISSUE TITLE
Missing drops from some trees in TGS

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#15795]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.6.0 Beta 1

### Your Server

SP 

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

A helbark sapling from natura should drop Persimmon in a TGS, as it does in-world

### The Reality

It doesn't. I don't blame you, though. The helbark has 5 leaves, and the chance for it to drop one is quite low. The persimmon doesn't even have an oredic recipe to convert to a pams one. 

### Your Proposal

Add it, please?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
Dark Oak also does not drop its fruit in the TGS.

**Comment by AbdielKavash** [comment]
Persimmon are indeed rare drop from some (though not all (I think)) Natura trees. I must have missed this one, will fix! Thanks for the report.

**Comment by LazyFleshWasTaken** [comment]
Another one is redstone from bloodwood.

**Comment by LazyFleshWasTaken** [comment]
Dark oak is also only 5 wood, while it is a 2 by 2 tree. Spruce and Jungle are 10.

**Comment by AbdielKavash** [comment]
> Another one is redstone from bloodwood.

Noted.

> Dark oak is also only 5 wood, while it is a 2 by 2 tree. Spruce and Jungle are 10.

Wood amounts are right now based on just eyeballing how much wood the actual tree has, and it is not possible to tune them very finely right now (multiples of 5 is best I can do). While Dark Oak is 2x2, it does not have anywhere as much wood as a large spruce or a jungle tree.

I would rather be conservative with the amounts for now and maybe implement more precise scaling in the next release cycle.

**Comment by LazyFleshWasTaken** [comment]
Some more missing fruits: 
Tree of time makes clocks
Canopy, mangrove, and transformation make fireflies for some reason, though only transformation drops it as a fruit, the others grow them like vines/cocoa on a jungle.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40587985/807b5955-6dcc-4067-885d-671a05859a92)

**Comment by LazyFleshWasTaken** [comment]
Golden Oak drops golden apples, though it needs to be cut with a branch cutter in-world to do so, so not sure if you want to add it.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40587985/7830dcf2-05bd-479a-944e-06f68df11557)

**Comment by AbdielKavash** [comment]
> Tree of time makes clocks

Intentionally omitted right now, mostly for thematic reasons.

> Canopy, mangrove, and transformation make fireflies for some reason

Similar to above, if it is not "logically" a part of the tree, I don't want to add it. For example, vines don't come from jungle (and other) trees either.

> Golden Oak drops golden apples, though it needs to be cut with a branch cutter in-world to do so

Rule of thumb for "fruit" is "does it drop when leaves naturally decay" (with some obvious exceptions like Pam's trees). Again, hesitant to add more than that for balance/consistency reasons.
