### ISSUE TITLE
Items displayed by holo glasses vibrate if the player moves while looking at an inventory with holo glasses equipped

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15799]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.6.0 Beta 1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Items displayed by holo glasses should be displayed in a consistent position relative to the inventory being looked at, even while the player moves.

### The Reality

Items displayed by holo glasses vibrate back and forth when the player wearing holo glasses moves about while looking at an inventory with items in it.

### Your Proposal

Restore the more normal behaviour of holo glasses item display from the prior modpack version. If Holo Inventory itself is not at fault, my best guess at the culprit would be Angelica.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by hallucinogender** [comment]
Addendum for clarification: changing the camera angle doesn't cause this; only moving the player's physical position has this effect.

**Comment by LazyFleshWasTaken** [comment]
can confirm
