### ISSUE TITLE
Conduit Bundle Crash between Enderio and Angelica

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15798]
### Your GTNH Discord Username

hallucinogender

### Mod Version

1.0.0 alpha 35

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

I installed the first GTNH 2.6.0 beta version. I ported forward a save from 2.5.1 to the new instance. I had previously installed Server Utilities for chunkloading purposes. I noticed that Server Utilities is included by default in 2.6.0, so I did not install it manually

When I loaded my save for the first time in the new version, I noticed a lack of chunkloading functionality with Server Utilities. I was informed in the GTNH Discord that this functionality is disabled by default, so I re-eanbled it in the config.

When I re-launched the game after making this config change, the game crashed upon loading my save again. I posted the crash report in the Discord and was informed that the crash is due to Angelica. The crash report is attached.
[crash-2024-03-23_18.16.45-client.txt](https://github.com/GTNewHorizons/Angelica/files/14733268/crash-2024-03-23_18.16.45-client.txt)

### Mod List or GTNH Pack Version

GTNH 2.6.0 Beta 1. Both this and my 2.5.1 instance also have Better Foliage 2.0.17 installed, and my 2.5.1 instance had Server Utilities as an additional mod. There are no other additional mods.

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Caused by EIO & Angelica, fix should be in EIO.

**Comment by hallucinogender** [comment]
This issue seems to be the same thing: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15866

I didn't realize at the time, hence the duplicate bug report. There are several more crash logs there, in case those might be helpful for finding a solution.

**Comment by hallucinogender** [comment]
I've found a new one. GTNH-2024-03-30-418-mmcprism-new-java. This crash report also seems to indicate some Gregtech block. I don't know how to find out _what_ Gregtech block is the source of the problem, but it seems as though an interaction between Gregtech, Ender IO, _and_ Sodium could be the source of this crash.

[crash-2024-03-30_18.25.29-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14812972/crash-2024-03-30_18.25.29-client.txt)

**Comment by hallucinogender** [comment]
I've been trying to localize the problem to a specific graphics setting, with no luck. Selectively disabling graphics settings does nothing to prevent the crash from occurring.

However, changing the quality preset from "fancy" to "fast" results in a _different_ crash while loading the world. 
[crash-2024-03-31_16.18.43-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14816493/crash-2024-03-31_16.18.43-client.txt)

**Comment by hallucinogender** [comment]
I can't do anything helpful by testing in a creative world. There are simply too many possible combinations of conduits, which means that it is completely impossible to exhaustively test them all. I cannot reproduce this bug except by entering my singleplayer survival save, in which case the crash occurs almost immediately, every single time I load the save, unless I remove Angelica from the instance entirely.

The save game is here, I hope this can be helpful: https://drive.google.com/file/d/1QxUWH0XH3Hh7a_KGMOC-7y3lcG8uITOf/view?usp=sharing
