### ISSUE TITLE
Incorrect Number of Items in The Superchest

### ISSUE THREAD

**Issue by Tree-er233** [GTNewHorizons/GT-New-Horizons-Modpack#15809]
### Your GTNH Discord Username

tree_er

### Your Pack Version

2.6.0-beta-1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Right click to open the gui of the superchest and see the number of items.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/110247896/537d4b91-4a5d-4be3-af5a-6f3fa902a0dd)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/110247896/3f0898bd-6fa3-4c98-b2b5-e8d591e5c2e4)
Incorrect amount

### Your Proposal

please fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2532
