### ISSUE TITLE
TGS not producing Barnada C Tree Products Correctly

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#15808]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.6.0beta1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Trying to produce BC log for my radox production line.

### The Reality

When BarnadaC sapling is put into the controller slot it is consumed instantly when the machine is turned on, and the machine doesn't start the process at all.

Tested with Oak,Birch and Sacred oak saplings and they runs just fine.

### Your Proposal

fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
it looks like https://github.com/GTNewHorizons/GTplusplus/pull/839 refactored all the tree recipes. will need to check what else is broken.

**Comment by chochem** [comment]
well just gonna fix the one for now
