### ISSUE TITLE
Can't select proper blocks at Multiblocks Structure NEI,and has weird black border

### ISSUE THREAD

**Issue by XeonKA** [GTNewHorizons/GT-New-Horizons-Modpack#15802]
### Your GTNH Discord Username

 XeonKA

### Your Pack Version

2.6.0 Beta1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Right click blocks can select the block,then it display what blocks what I can place.

### The Reality

Right click can't select the block what I need,and GUI has weird black border.
![what](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/33470743/ea3e9aa8-8543-442e-adb8-1d5c717a09da)

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by hallucinogender** [comment]
I've encountered a similar black edge on the petal apothecary NEI view, but only on one side. That aspect looks like the same bug.

**Comment by Lyfts** [comment]
Caused by Angelica and also reported on its issue tracker https://github.com/GTNewHorizons/Angelica/issues/383
