### ISSUE TITLE
Night vision enchantment broken

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15803]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.6.0 Beta 1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

I put the night vision enchantment (from Thaumic Exploration) on my thaumium fortress helm using an osmotic enchanter. The night vision enchantment is supposed to provide night vision while wearing the helmet.

### The Reality

The night vision enchantment fails to provide night vision while wearing the helmet. I have also searched through the GTNH Discord and found many mentions of this same issue, on several different types of helmet; these messages go back to before 2.6.0, so it is not a newly introduced bug.

### Your Proposal

Fix the night vision enchantment (from Thaumic Exploration) so that it actually provides night vision.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
It's a bit odd but as of https://github.com/GTNewHorizons/Thaumic_Exploration/pull/2 & https://github.com/GTNewHorizons/EnderIO/pull/2 you are supposed to toggle it with the EnderIO nightvision keybind. I just tested it and it actually does work, but I highly doubt most players would expect or know about it.

**Comment by hallucinogender** [comment]
The thaumonomicon page for the night vision enchantment should probably be edited to explain this; I don't know if there's any way to find this information in-game except by accident.
