### ISSUE TITLE
Black bars in some NEI recipe pages.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15816]
### Your GTNH Discord Username

Abdiel Kavash

### Your Pack Version

2.6.0 beta 1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

View NEI recipes. This issue usually manifests when looking at the usages of the "crafting station" block; sometimes viewing the same page by looking up the recipe for an item does not show the black bars.

### The Reality

Check uses of:

<details><summary>Master Ritual Stone</summary>

![](https://i.imgur.com/pssRXjy.png)
</details>
This one is particularly annoying, as it obscures the LP cost or radius of the meteor.

&nbsp;

<details><summary>Mana Pool</summary>

![](https://i.imgur.com/NeY6jb1.png)
</details>
Most other Botania crafting stations also have a similar bar on the right side.

&nbsp;

<details><summary>Vanilla crafting table</summary>

![](https://i.imgur.com/MSKDy4v.png)
</details>
Note the black bar behind the smelting recipes (fire) icon.

&nbsp;

<details><summary>Multiblock macerator, arc furnace</summary>

![](https://i.imgur.com/Uj6JnkY.png)
![](https://i.imgur.com/Jyc53xU.png)
</details>
Again black bars behind some other NEI tabs. This only affects the multiblock versions of the machines. It might be more multiblocks than just these two, I haven't checked all of them.

### Your Proposal

I have not checked every possible crafting station, but I tried to poke around various mods to see where this happens. Hopefully this can be isolated to some common root cause and fixed everywhere at once.

Might be related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15802.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by EnderProyects** [comment]
Same some times for the Lexica botania, and I have seen it vertical and horizontal

**Comment by Ethryan** [comment]
Another one, Furnace Cart.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3237986/6492ad8b-3c78-44c3-b942-c262a2d62c6f)

**Comment by chochem** [comment]
gonna claim its fixed by https://github.com/GTNewHorizons/NotEnoughItems/pull/528
