### ISSUE TITLE
Mod suggestion: MatterOverdrive

### ISSUE THREAD

**Issue by EngineerXL** [GTNewHorizons/GT-New-Horizons-Modpack#15812]
### Your GTNH Discord Username

EngineerXL

### Your Pack Version

2.4.0

### Mod Name

MatterOverdrive

### The Mod to Add

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/37447286/864d0478-4af7-4893-8342-2e045ecf699f)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/37447286/a5c1cd28-675d-461d-9951-f85449e6fe9d)

Mod adds android mobs and mechanic for player to become android. Mobs can attack player in melee or using a futuristic gun, such as plasma rifle, shotgun or sniper. Of course, player can obtain these weapons from mobs, or craft them.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/37447286/5f71d163-a08b-4ad6-a071-19165cdf5b76)

Also player can become an android switching from hunger to RF charge. This non human form opens android station, where player character could be upgraded, like player infusion in Thaumic Horizons mod.

Another feature of the mod is matter system, that is not needed in GTNH and I think should be disabled. Gravitational anomaly generator could be added as an alternative power generator

### Your Reason

Android mobs could be added to GalactiCraft dimensions and dungeons to add challenge for player. Of course the weapon damage and mob hp should be buffed, so player at least need a decent weapon and armor to fight.

MatterOverdrive dungeons add more exploration to GalcticraftDims. There are crashed ships and android bases.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/37447286/22d27cf3-0866-49af-8964-51ec4833f07d)

Android form removes need in all spacesuit and oxygen, this feature may be useful at high tiers. Android station adds a non-magic way to upgrade the character.

### Preliminary Investigation

Androids may be added at T3 rocket, damage of the plasma weapons may be slighlty higher than damage of the Tinker tools.

I think android form should not be unlocked early, so the player should build oxygen setup and craft thermal padding.

When I add MO to the pack, it crashes with no minecraft enchantment class found.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by danRP408** [comment]
Is it compatible with GalactiCraft?

**Comment by EngineerXL** [comment]
I played it with GalactiCraft on other modpacks, didn't notice any problem
Probably some work should be done to allow android player live in space without equipment
On 1.12.2 MatterOverdrive is compatible with GalactiCraft oxygen setup and ExtraPlanets spacesuit out of the box, but I used GalactiCraft Tweaks to prevent android mobs from dying in the space

**Comment by chochem** [comment]
does not look like there is any interested. it does not really fit the pack well
