### ISSUE TITLE
Crash in Spice of Life when using the Food Bag for the first time

### ISSUE THREAD

**Issue by RichardCritten** [GTNewHorizons/GT-New-Horizons-Modpack#15813]
### Your GTNH Discord Username

Wack149

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I had just received the quest reward: 3 slot Food Bag (spice of life) and was shift clicking food into it from my inventory.

### Crash Report

https://mclo.gs/hDmqjPm

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by idksomeone351** [comment]
happened to me twice
