### ISSUE TITLE
add new skystone meteor to BM

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#15828]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.6.0

### Your Proposal

Add a new meteor that gives you applied skystone, and maybe some fluix blocks or similar, idk to fill it with something more, or certus glass

### Your Goal

Some BM recipes need sky stone, and the only renobable source is bees, so we have another source

### Your Vision

make the pack better and use the new method of meteors of @AbdielKavash 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
There is a TC alchemy recipe that transmutes obsidian to skystone.

Though I wouldn't mind putting it into a meteor somewhere (more likely one of the existing ones, no need to make a new one just for this).

**Comment by EnderProyects** [comment]
oh, I forgot about the alchemy recipe, my bad

**Comment by AbdielKavash** [comment]
Since there is already a renewable source, I don't want to scope creep the changes during a feature freeze. But if and when there is a pass over the meteor drops after 2.6.0, this could be added.
