### ISSUE TITLE
Massive Lag and Freeze in ME Terminals when pressing shift

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#15826]
### Your GTNH Discord Username

impvt

### Your Pack Version

2.6.0 beta-1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Hold shift in terminal gui without issues

### The Reality

Holding shift in various ME Terminals cause massive lag and freeze.

### Your Proposal

https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/449
likely caused by this, when held shift it locks items sorting and I assume on a large system with items constantly changing it cause a freeze

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
can you post a recording on this?

**Comment by Impos913** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/36479271/cdb0f08a-7f42-4fdd-9c16-1afc50ada226

**Comment by Caedis** [comment]
Thanks! That makes it clear

**Comment by MushroomDynamo** [comment]
I also had this issue appear on my server last week for myself and my players (2.5.1 Java 20, updated to appliedenergistics2-rv3-beta-326-GTNH). Removed all drives and reinserted them one at a time--was able to reproduce even with a relatively small amount of items, though fps would drop to maybe ~75% of its normal amount instead of completely freezing. Issue persisted through server restarts.

Worryingly, the issue went away by itself after most of a day and we haven't seen it since.

**Comment by Glease** [comment]
is there a base download (or your test creative world, or even just a few chunks) that can replicate this problem? It sounds highly base dependent.

**Comment by Impos913** [comment]
No invalid patterns. I'll try to make a download later, just keeping the base chunks

**Comment by Impos913** [comment]
https://discord.com/channels/181078474394566657/401118216228831252/1227530644398276619
