### ISSUE TITLE
Crash at launching

### ISSUE THREAD

**Issue by KamenriderSuperBee** [GTNewHorizons/GT-New-Horizons-Modpack#15821]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.6.0-beta

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Updated from 251 to 260

### Crash Report

[crash-2024-03-25_11.04.03-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14741962/crash-2024-03-25_11.04.03-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment]
Remove either the FTB mods or serverutilities.

**Comment by KamenriderSuperBee** [comment]
solved
