### ISSUE TITLE
Stocking input hatches cause AALs to Fail/void all crafts when not enough items to start crafting first slice

### ISSUE THREAD

**Issue by cytrus224** [GTNewHorizons/GT-New-Horizons-Modpack#15836]
### Your GTNH Discord Username

Cytrus

### Your Pack Version

2.6.0 beta

### Your Server

private MP server

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Stocking hatches work fine with AALs

### The Reality

![316829945-ddb9d44c-cfe9-449c-9c87-069b4b6cff1b](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17723060/dfa2caff-b11e-4214-9cea-f98ba4c44621)
My setup: Dual interface inputs items and fluids into subnet, which stores items and fluids on ME Drive disks. Items and fluids are distributed to multiple AALs via stocking input buses and hatches.
When big craft is close to finished(last items are being crafted in AALs), AALs "fails" to pull items&fluids, because there is no more to craft, and voids all crafts that are being crafted in other slices.
I have 12 Pico circuit AALs, 4 Gallifreyan TIme Dilation AALs, 12 Optical Mainframe AALs, all of them have this issue.

### Your Proposal

Fix AALs so they do not void all pending crafts when trying to start a new slice

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
this could be the same with what i mentioned here. I could not figure out what was going on. #15612

**Comment by Tomekosi** [comment]
> this could be the same with what i mentioned here. I could not figure out what was going on. #15612

It is the same issue, I'm playing on the very same server as Cytrus, and this happens all the time

**Comment by cytrus224** [comment]
Found out that if AALs are overclocked enough and 1ticking slices, they tend not to crash anymore

**Comment by NotAPenguin0** [comment]
Fixed in GTNewHorizons/GigaGramFab@0f6bb0f
