### ISSUE TITLE
JABBA Better Barrels and Logistics Pipes

### ISSUE THREAD

**Issue by SoskaOneLol** [GTNewHorizons/GT-New-Horizons-Modpack#15835]
### Your GTNH Discord Username

SoskaOneL9l

### Your Pack Version

2.6.0-nightly-2024-03-24

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

In 2.5.1 attached provider logistics pipes to better barrels and then could access to barrels through request logistics pipe

### The Reality

Did the same thing in 2.6.0-nightly-2024-03-24 and couldn't access the new ones and the old ones. After downgrading to 2.5.1 everything worked

### Your Proposal

fix bug

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TimeConqueror** [comment]
Seems like this pull request fixes the issue (https://github.com/GTNewHorizons/LogisticsPipes/pull/34)
Tested with 1.2.15-GTNH version of Logistics Pipes
