### ISSUE TITLE
Is low-gravity processing condition planned to be removed?

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/GT-New-Horizons-Modpack#15831]
### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Crystal recipes requires cleanroom & low gravity condition.
![5415cc3b87deedfd16b98f47b8f4fd28](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/4c0772b9-8008-4146-bf39-dadef08456c3)

### The Reality

Only cleanroom condition displayed in NEI.
![0909619a8e7062fd993f1cd9dcc67213](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/98e943b0-5847-4f9a-9a5a-d6923504e12a)

The crystal recipes can be processed only with cleanroom condition.
![df02073323d832eb739be4b57281a491](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/a52e2f3a-7c4d-4c13-9c8e-f2f8bb54d0d7)

### Your Proposal

I didn't find any issues or discussion related to the removal.
If the removal is not intended, it needs to be restored.
And to make it effective, large processing factory needs a nerf to make it can't provide low gravity condition anymore.
As we known, large processing factory is unlocked in IV tier, and crystal chip is unlocked after fusion MK1, in LuV tier.
So players can just skip low-gravity condition to make chips.
If the low-gravity condition should be kept, this nerf is necessary.
Like what we have done on integrated circuit, cleanroom condition can be skipped after 2 tiers since first occurance(early/mid HV), in EV tier(for nano circuit), IV tier(for circuits, with processing array). We can add a new multi block to contain nerfed large processing array, which is used to provide low gravity condition on the earth. It should be unlocked in UV/UHV-tier.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by koiNoCirculation** [comment]
@Dream-Master Is that removal intended?

**Comment by chochem** [comment]
that was a bug when converting the recipes. and its fixed.
