### ISSUE TITLE
Downtier CALs to IV tier

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#15834]
### Your Pack Version

nightly412

### Your Proposal

Followup on this:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14440

As they are luv machines this is the one last step blocking them as PA replacements.

### Your Goal

make CAL proper PA replacement(for CA part)

### Your Vision

One step further to end PA deprecation drama.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
luv/zpm is content starved as is. lets not move one the few bits of content it has to IV, no.

**Comment by Impos913** [comment]
IV tier would need a circuit assembler multiblock replacement after PAs removal.

**Comment by boubou19** [comment]
Is it really a bad thing to use the singleblocks in IV? blocking mode on a line of CAs with same patterns achieve the same thing, AE2 will balance the items properly among the machines. Correct me if i'm wrong, but PAs of CAs have the same recipe costs as the single block compared to CALs, the only convenience is to have them in a single machine. But strictly speaking, it's not required at this stage of the progression.

**Comment by boubou19** [comment]
yes, but it's part of the game. A possible change about how multis work with cleanroom based recipes could happen with the debate sparked by https://github.com/GTNewHorizons/GTplusplus/pull/861. But in the meantime, strictly the PA isn't required, and we aim to remove all the strict dependencies on the PA before replacing it. Conveniency comes after.

**Comment by Hikari1nVoid** [comment]
Glad to see that chochem has no knowledge about what he is talking about and PA deprecation is such a drama.
I don't see the point of fun when crafting 96 quantum mainframes with single blocks.
And this makes CAL CA mode a completely joke.TIred of this now.

**Comment by IncandescenceSy** [comment]
> luv/zpm is content starved as is. lets not move one the few bits of content it has to IV, no.

This doesn't really do that; imprinting as a mechanic would still be exclusive to LuV+, in IV you'd just have a Circuit Assembler mode CAL, which functions very differently from a CAL mode CAL

I would definitely be in favor of a change like this, but I think it's understandable why it's not planned. Using singleblock CAs for Assline without PAs would kind of suck, but it wouldn't be that bad
