### ISSUE TITLE
AALs can't work at maximum slice

### ISSUE THREAD

**Issue by Tree-er233** [GTNewHorizons/GT-New-Horizons-Modpack#15848]
### Your GTNH Discord Username

tree_er

### Your Pack Version

2.6.0-beta-1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

AALs work at max slice to craft products, such as the bioware supercomputer.

### The Reality

When using the normal input hatches/buses, only a few slices are working in a loop. It has been checked that the normal input hatches/buses are large enough.
![e1e80777badb71226ee46eda7c22baf8](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/110247896/2d486e91-e286-49e6-9df8-b4ab1979b42f)
Works fine when using stocking input hatches/buses.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/110247896/2a3e9975-4427-4d40-850a-bbafecead722)

### Your Proposal

AALs worked fine in 2.5.1, so please fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
Are you using batch mode?

**Comment by Tree-er233** [comment]
> Are you using batch mode?

No

**Comment by NotAPenguin0** [comment]
One thing AALs do (intentionally) is that they only check the first slot in each input bus for items, maybe it's related to that somehow.
