### ISSUE TITLE
Cactus/Sugar Coke/Charcoal should have a block

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#15845]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.6.0 Beta 1

### Your Proposal

Cactus coke and charcoal, and the sugar equivalents, are materials used to make Steel in the BBF. Unfortunately, they can only run 32 minutes at a time and are high maintenance; this is due to outputting 8 tiny ashes after being burned. Had it not been for that amount of ashes, they would run for longer. Charcoal, on the other hand, can run for 96 minutes, 64 if it wasn't for the 50% time penalty for sub-par fuel. As blocks, it can go for 6 hours before it stops due to steel filling up its output.

My proposal is therefore, to add blocks of each item to condense the ashes into smaller parts, though maybe not with an efficiency increase. The recipes could be wholly multiplied by 9, making 9 steel with 8 cactus coke blocks, for example. 

### Your Goal

This is a good feature to have because people who use cactus and sugar coke, and not charcoal due to its 50% longer production time, will need to worry less about letting the BBFs run out. It would lessen stress, and increase parallel workload.

### Your Vision

Less stress, more work.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
Lmfao, based? Love to see it
