### ISSUE TITLE
freezing crash while loading probably due to BM meteors

### ISSUE THREAD

**Issue by SoskaOneLol** [GTNewHorizons/GT-New-Horizons-Modpack#15841]
### Your GTNH Discord Username

SoskaOneL9l

### Your Pack Version

2.6.0-nightly-2024-03-26

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

loading to the game

### Crash Report

[crash-2024-03-26_22.21.32-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14764300/crash-2024-03-26_22.21.32-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
hmm no, looking at the mods this cant be 414.

wait, did you just update the config repo? That you say '2.6.0-nightly-2024-03-26' kind of suggests that.

Then that is the cause of your crash.
