### ISSUE TITLE
Anvils taken from the Ur-Ghast tower cannot be used for any recipes

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15850]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.6.0 Beta 1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Vanilla anvils looted from the Ur-Ghast tower should be the same as vanilla anvils, and be able to be used in recipes that require vanilla anvils.

### The Reality

Vanilla anvils looted from the Ur-Ghast tower are somehow different than vanilla anvils. They cannot be used in any recipes as they entirely lack the "craftingAnvil" ore dictionary tag, and they also have no Thaumcraft aspects.

### Your Proposal

Make the vanilla anvils that spawn in the Ur-Ghast tower the same as regular vanilla anvils.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
That's because most of them are damaged, it's intentional.

**Comment by hallucinogender** [comment]
> That's because most of them are damaged, it's intentional.

I specifically picked up undamaged ones. The _undamaged_ ones have this problem.

**Comment by Ethryan** [comment]
Must be a nbtData mismatch then.

**Comment by chochem** [comment]
do '/mt hand' and let us know the result
