### ISSUE TITLE
Architect's Sawbench regularly suffers texture randomization

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15852]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.6.0 Beta 1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

The texture of the Architect's Sawbench should always be the texture of the Architect's Sawbench.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/46674412-26f4-4884-8352-672b03da1f64)
Every so often, I look at the Architect's Sawbench and discover that its texture has been randomized to the texture of some other block. Breaking and replacing it sometimes works, but sometimes does not. I have been unable to find a way of triggering this bug aside from restarting the game with an Architect's Sawbench placed in the world.

### Your Proposal

Make sure the Architect's Sawbench always uses its own texture.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GirixK** [comment]
I've noticed this happen when I change resourcepacks, I've usually chucked it up to Optifine, though I can't say I'm certain
Might be worth looking into reloading textures as a potential way to reproduce, though

**Comment by hallucinogender** [comment]
I do not have Optifine, and it also occurs without Angelica too.
