### ISSUE TITLE
Space Mining Module Parallel seems to be bugged

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/GT-New-Horizons-Modpack#15863]
### Your GTNH Discord Username

ipielover

### Your Pack Version

2.5.1

### Your Server

Delta

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

Space Mining Module parallel should be limited to the number of parallel stated in the description.

### The Reality

I'm using this recipe for output calculation:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/29ca733d-b721-4029-90ee-b6f48ad60671)
This is a mining module configured to 8 parallel:

Power usage: 425,672 EU/t = 53,209 * 8
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/c2f5fca8-5c8e-43a7-bf53-1e087ce4a399)
I've ran 3 cycle of the mentioned recipe and here are the outputs:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/353a88ec-bb6b-487e-bd79-a01fa7759a69)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/4314e57d-08a4-4bb4-a6b3-1a1b7f689b7d)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/45bda5d1-1593-447a-96b4-01c2edd2f261)

After changing the parallel config to 80:

Power usage: 2,234,778 EU/t = 53,209 * 42(?)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/2223fbd7-f532-4f66-a42d-f206e3a1b81f)
The same 3 cycle output:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/8452dcd1-6c17-41b0-bc6c-573d05cd6ad7)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/008a81d6-8cb3-4a8b-ac78-88f4461171f8)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/e3045be7-b41f-4ae7-b19b-eae7857d9f51)

Based on the power usage calculation and the output count, it seems to be applying the 42 parallels with the output being 5x of the 8 parallels config.
I might be limited by the computation that I provide so it only handles upto 42 parallels.

### Your Proposal

Can anyone check if this is suppose to be the expected behaviour?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
Each parallel needs computation separately, if you don't provide 8x computation you won't get 8x parallel.

**Comment by GTNH-Afx237v7** [comment]
Just for clarity: are we talking about 8x or 80x parallel?

**Comment by Georggi** [comment]
Still reproduceable in 2.6.1.

**Comment by kstvr32** [comment]
This should be closed. Was fixed by GTNewHorizons/GTNH-Intergalactic#67
