### ISSUE TITLE
[Blood Magic] BM Book does not appear in game.

### ISSUE THREAD

**Issue by IcaroKaue** [GTNewHorizons/GT-New-Horizons-Modpack#15861]
### Your GTNH Discord Username

IcaroK

### Your Pack Version

2.6-nightly-390

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

There have been reports of a [.lang file in the BM .jar](https://github.com/GTNewHorizons/BloodMagic/tree/master/src/main/resources/assets/alchemicalwizardryBooks). One would expect this file to appear as a book. The book's name is [Sanguine Scientem](https://ftbwiki.org/Sanguine_Scientiem).

![javaw_MzWESYKCd5](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/73764500/148de8b7-dd55-4f59-b16e-745007acea52)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/73764500/e2f2c165-e5e5-4b94-b76d-332ddc25788f)

### The Reality

The book does not appear in game. It seems that, although it was implemented in 1.12.2, it was never implemented in 1.7.

### Your Proposal

Either implement the book, or remove it from the .jar file entirely. It appears that there is some stuff in the book that's not in game (due to 1.12.2 vs 1.7.10), so that would warrant axing it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kamenskyi** [comment]
Sanguine Scientiem is a item from [Guide API].

**Comment by kamenskyi** [comment]
found it here https://ru-minecraft.ru/mody-minecraft/49131-guideapi.html

**Comment by kamenskyi** [comment]
you need to check if the book will appear when adding the mod

**Comment by IcaroKaue** [comment]
Adding Guide-API adds the books, but they're glitchy.

![javaw_1UOTVXayGm](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/73764500/82694a57-2ea6-4021-82ed-364d938ca9f0)
![javaw_rL04n0b9Yj](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/73764500/32e6e8ee-7cf3-471c-ac83-8947a468a2a5)
![AsPowerBar_S9nIIEOiAQ](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/73764500/3442c2af-19e2-482f-9419-37fc6a966117)

**Comment by kamenskyi** [comment]
Then these are questions for the moderators. Maybe they will find a mistake and fix it

**Comment by IcaroKaue** [comment]
> Then these are questions for the moderators. Maybe they will find a mistake and fix it

I see. For the time being, we don't translate these right? Since it takes up ~60k words.

**Comment by kamenskyi** [comment]
We will not resolve this issue. If we leave the book, we need to mod this and solve display problems. If we don’t add it, we leave it as is. let the modders decide

**Comment by kamenskyi** [comment]
It’s too early to translate the book yet. you have to decide whether to keep the book or not

**Comment by Alastors** [comment]
> We will not resolve this issue. If we leave the book, we need to mod this and solve display problems. If we don’t add it, we leave it as is. let the modders decide. It’s too early to translate the book yet. you have to decide whether to keep the book or not

Who won’t resolve this issue? I presume you aren’t talking about the GTNH dev team

**Comment by kamenskyi** [comment]
@Alastors @Dream-Master the book works great. only need a stable version. here are screenshots from the game
https://github.com/TeamAmeriFrance/Guide-API/tree/1.7.10
https://www.curseforge.com/minecraft/mc-mods/guide-api
stable version - https://www.curseforge.com/minecraft/mc-mods/guide-api/files/2241379
![2024-09-27_01 31 33](https://github.com/user-attachments/assets/e151faa6-aa36-4159-9b8b-43734f1cc160)
![2024-09-27_01 31 35](https://github.com/user-attachments/assets/186d359d-7a92-494f-a7e8-9454decf01c7)
![2024-09-27_01 31 38](https://github.com/user-attachments/assets/6e0d6fcd-9d37-4f07-8107-0f86b47e1a99)
![2024-09-27_01 31 40](https://github.com/user-attachments/assets/1fd81233-ae4a-4628-ae06-79945927815d)
![2024-09-27_01 31 51](https://github.com/user-attachments/assets/61d8f98b-196d-420f-b89b-fa56548d333c)
![2024-09-27_01 31 52](https://github.com/user-attachments/assets/4b75a22c-c8f5-4af4-abf6-b330b7af3574)
![2024-09-27_01 31 54](https://github.com/user-attachments/assets/dce0b264-0b56-4988-a4b7-0bedf2f9e72a)
![2024-09-27_01 31 56](https://github.com/user-attachments/assets/de9739d5-9c92-47c8-95ab-8377432cdee2)
![2024-09-27_01 31 57](https://github.com/user-attachments/assets/79cc5b94-0aef-4118-b64d-5ce203cbb0d8)
![2024-09-27_01 31 59](https://github.com/user-attachments/assets/98f3f773-b5a8-44e5-94b3-d201a967f898)
![2024-09-27_01 32 05](https://github.com/user-attachments/assets/672d65b2-a322-43f1-8589-d68f7a803413)
![2024-09-27_01 32 08](https://github.com/user-attachments/assets/ef368e09-18e7-45bc-8e39-e237a6102eb2)
![2024-09-27_01 32 09](https://github.com/user-attachments/assets/7fbed4a7-a990-4eea-87d0-ceabfa0ef77c)
![2024-09-27_01 32 10](https://github.com/user-attachments/assets/7f079b08-416e-48f6-a7ce-472c5f5fb230)
![2024-09-27_01 32 45](https://github.com/user-attachments/assets/daa8ed93-90da-4bdc-a63f-36b0690840cd)
![2024-09-27_01 32 46](https://github.com/user-attachments/assets/51a63880-c812-4c0e-9eef-54f9d1a0bd61)
![2024-09-27_01 33 02](https://github.com/user-attachments/assets/cd512c8f-22f1-4ac1-b641-2b2c975bd398)
![2024-09-27_01 33 35](https://github.com/user-attachments/assets/80c9facc-67df-4857-af62-ace2d1f32690)
![2024-09-27_01 33 38](https://github.com/user-attachments/assets/9fe6e69b-79f0-4848-9f08-5efe28a80e7d)
![2024-09-27_01 34 01](https://github.com/user-attachments/assets/ab9bc7f5-530b-4493-aeed-9257ca6edc93)
![2024-09-27_01 34 24](https://github.com/user-attachments/assets/2fe681cb-bbf7-41b2-b4d8-594bad9233d7)
![2024-09-27_01 34 33](https://github.com/user-attachments/assets/91b23e5d-7ec6-459c-931a-d680d6ce3973)

**Comment by Alastors** [comment]
Nice

**Comment by kamenskyi** [comment]
![Uploading 6666.png…]()

**Comment by chochem** [comment]
since the book is not particularly relevant/accurate for gtnh, why would we add a mod to the pack just to make it work?
