### ISSUE TITLE
Terrasteel caps use incorrect thaumonomicon entry

### ISSUE THREAD

**Issue by mchernykh** [GTNewHorizons/GT-New-Horizons-Modpack#15868]
### Your GTNH Discord Username

murderless

### Your Pack Version

2.5.x nightly 359

### Your Proposal

Terrasteel caps shall be buffed significantly

### Your Goal

Wands and other stuff created from terrasteel caps shall be buffed according to high effort you spend to get them

### Your Vision

Terrasteel caps are nerfed very badly. I spent a day to get them (~ev) and got scepter that is MUCH worse than iron capped. I checked other terrasteel-based wands and they are all awful
So basically i took magically infused material, infused it even more and got absolute garbage with 150% vis usage
So well.. they need buff. Reasonable vis usage would be nice. I'd expect that terrasteel caps would be better than thaumium

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by mchernykh** [comment]
Expectation: terrasteel caps are a little better than manasteel
Reality: worse than trash

**Comment by EnderProyects** [comment]
And why you didnt read the thaum entry? 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/64cff4fb-3d3e-4763-8a79-ddd7123063fe)

**Comment by mchernykh** [comment]
> And why you didnt read the thaum entry? ![image](https://private-user-images.githubusercontent.com/45178400/318087992-64cff4fb-3d3e-4763-8a79-ddd7123063fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3Mjg1NTYsIm5iZiI6MTcxMTcyODI1NiwicGF0aCI6Ii80NTE3ODQwMC8zMTgwODc5OTItNjRjZmY0ZmItM2QzZS00NzYzLThhNzktZGRkNzEyMzA2M2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDE2MDQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3MTRjYTI0MjVlMDJkYjRkMDBmNTNiMjkwOWIxZDA2YjAxZTEwZjJmNDlmYjQ1ODVlZmMzYzdlYzk0YzAwYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.enMCkytq7cTIKaayhKMMjjiuOwjbdC6EmnboBjUAIUw)

I didn't find it even after your reply:)

**Comment by mchernykh** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1153490/2168233f-eddb-4546-88fd-f6e67a7d94b3)
It is probably was changed in 2.6.0 but it is this way in my version

**Comment by chochem** [comment]
was not changed recently. both entries exist in the code. Looks like the wrong one is used

**Comment by Dream-Master** [comment]
remeber me to add the botania materials to GT to add some more stuff than only vanilla looking ingots 🤮

**Comment by mchernykh** [comment]
> was not changed recently. both entries exist in the code. Looks like the wrong one is used

may they change one to another by some trigger... that didn't happen?

**Comment by Filiz1** [comment]
Come on, it's all right there. It's pure irony. Over those who don't look at the spreadsheet and not test in creative. I think it's funny :)

**Comment by mchernykh** [comment]
Irony is ok but i need external information out of the game to conclude that terrasteel caps are bad intentionally:)

**Comment by Filiz1** [comment]
If you give advance warning of a joke, it stops being a joke. There's nothing wrong with that. Made terrasteel wand, laughed/drunk with grief and made right wand ;)
