### ISSUE TITLE
Vibrant Alloy to Phased Gold

### ISSUE THREAD

**Issue by StrawberrySweet22** [GTNewHorizons/GT-New-Horizons-Modpack#15865]
### Your GTNH Discord Username

fallfromgrace

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Trying to fluid extract vibrant alloy into fluid vibrant alloy twice over

### The Reality

First time GTvibrant alloy is extracted turns into molten vibrant alloy. When solidified back gives enderio vibrant alloy. When enderio is fluid extracted again gives phased gold which is useless. 
![2024-03-29_03 16 22](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/128013731/3f146aad-dba4-41a2-8340-df9d828ad9eb)

### Your Proposal

1. Change fluid solidifier output from enderio vibrant alloy to gregtech vibrant alloy.
2. Change fluid extractor of enderio vibrant alloy from molten phased gold to molten vibrant alloy
3. Remove phased gold

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Impos913** [comment]
Fluid extracting Block of Vibrant Alloy also gives phased gold.

**Comment by chochem** [comment]
On 2.6.0-beta1: the enderio vibrant alloy block extracts into molten vibrant alloy for me. Which then solidifies back to the same block.
can you try on the beta?

**Comment by Impos913** [comment]
On 2.6.0-beta1, enderio vibrant alloy block, single player
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/36479271/c21f6309-4168-435c-829e-fac01a25d8cd)

**Comment by Impos913** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/36479271/8a5e839c-2fa1-4f0d-9f6d-958a16310f92)

**Comment by chochem** [comment]
interesting. I have the same setup and get the other. Probably a recipe conflict then, Ill check more.
