### ISSUE TITLE
Remove or change requirement for LV semifluid generator quest due to a recipe change

### ISSUE THREAD

**Issue by LionEl-johnson14** [GTNewHorizons/GT-New-Horizons-Modpack#15860]
### Your GTNH Discord Username

lion_eljonson14

### Your Pack Version

2.4.0

### Your Proposal

To remove or change the quest requirements for the LV semifluid generator from the MV fluid extractor to something similar to the other generators of the tier
![Capture](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/64676704/43034a35-5c3c-457b-9c55-8bbde27db98f)

### Your Goal

Many newer players would be shown one of the better generators of the tier without advancing into MV and missing out on many of the benefits

### Your Vision

Gate the semifluid generator quest behind the LV piston quest, in line with the combustion generator and gas turbine, as reflecting the actual and current requirements of the machine. The recipe was changed long ago in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6507 but the quest was not updated to reflect this. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
this is fixed already. you are on an older version.
