### ISSUE TITLE
Placed HSS-S turbine casings use the wrong texture

### ISSUE THREAD

**Issue by Evan555alpha** [GTNewHorizons/GT-New-Horizons-Modpack#15864]
### Your GTNH Discord Username

evan555alpha

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

The casing should be reddish, a la the texture the item uses.

### The Reality

The block uses the solid steel casing texture instead, becoming gray.
Attached are examples- All UU-tex, UU-Tex with overridden solid steel texture, and vanilla.
![](https://cdn.discordapp.com/attachments/234936569360809996/1223124145555116082/image.png?ex=6618b620&is=66064120&hm=09ee67947d917c89f4c0f52ee5b42cb0248a0ecbdfc2ab19415af6b9ec649337&)
![](https://cdn.discordapp.com/attachments/234936569360809996/1223128639856447518/image.png?ex=6618ba50&is=66064550&hm=3e580b4e5a964c8c7c207afa43d02b2b535aa7dcad9a5917165b6eed5e155fb9&)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10338511/82d33462-59f2-4461-9532-366061962508)

### Your Proposal

Fix pls

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3276
