### ISSUE TITLE
Item Processor Tier II needs IV in assembler, NEI shows EV 

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#15871]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.6-Nightly 412

### Your Server

Test Server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7759876/d764a8d4-4c69-47d6-a0a6-aaa1ebde249c)
Assembling according NEI in EV Assembler

### The Reality
EV not working:
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7759876/9400068e-1c2c-4181-9315-d7206a3da9c4)
IV working
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7759876/c3c2a486-2576-44f6-a2c0-611f7ead9acc)

### Your Proposal

please shift receipt back to EV like NEI 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
works just fine in ev

**Comment by Ngar1** [comment]
at this version? I tested local and at test server

**Comment by chochem** [comment]
thats a circuit assembler XD

**Comment by Ngar1** [comment]
ok, you are right, what an idiot....
