### ISSUE TITLE
Ding plays a sound when the pack is finished loading

### ISSUE THREAD

**Issue by BeepBeep20** [GTNewHorizons/GT-New-Horizons-Modpack#15872]
### Your GTNH Discord Username

beepbeep20

### Your Pack Version

2.5.1

### Mod Name

Ding - plays a sound when the pack is finished loading

### The Mod to Add

https://www.curseforge.com/minecraft/mc-mods/ding

The mod is under the GNU general public license.

The mod by default plays a sound when the pack is loaded, but can be changed by config to play a sound on world load too.

### Your Reason

It means you can leave the pack loading in the background but Ding alerts you when it's ready to play.

### Preliminary Investigation

I have added this mod to every pack I've played (including GTNH) without any problems for more than 5yrs.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by eigenraven** [comment]
BetterLoadingScreen already has the same functionality, and is even enabled: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/Betterloadingscreen/betterloadingscreen.cfg#L35 - does it not work for you?

**Comment by BeepBeep20** [comment]
You're right it does play the same sound.

I always add ding to every modpack/version before I load it for the 1st time so I assumed ding was playing the sound.
