### ISSUE TITLE
Increase the block range for IC2 special blocks from 4 to 5 blocks.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#15882]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.5.1

### Your Proposal

Increase the range for special blocks to affect a crop by one. (e.g. glowstone for glowflowers, aluminium blocks for aluminum oreberries, etc.).

### Your Goal

By increasing the range by one, this would allow special blocks to affect a full 3 stack setup when using crop managers or similar crop collecting machines. 

### Your Vision

Good quality of life and compact presentation for the full reward.

**Note: If this has the potential issue of balancing due to the strength/power of crops, I would rather have an overall nerf to the crop rate as compensation for this change, as this is closer to a QoL suggestion than a balance one.**

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by PlayfulPiano** [comment]
.

**Comment by PlayfulPiano** [comment]
,

**Comment by Dream-Master** [comment]
@PlayfulPiano not sure this is possible. Ic2 itself is closed source

**Comment by PlayfulPiano** [comment]
> @PlayfulPiano not sure this is possible. Ic2 itself is closed source

Hm, and I'd take it that the mechanics surrounding ic2 crop special blocks can't be modified externally? (like via a mixin)

**Comment by Dream-Master** [comment]
@Alexdoru are you able to write a patch ?
