### ISSUE TITLE
Malis door causing client crash and program complete dead

### ISSUE THREAD

**Issue by Wacchi-Lorie** [GTNewHorizons/GT-New-Horizons-Modpack#15881]
### Your GTNH Discord Username

wacchi-lorie

### Your Pack Version

2.6.0-beta1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

Malis door tile entity exists at overworld base, not causing any trouble while using 2.5.1 release, no matter using angelica or not.
After i updated to 2.6.0-beta-1, rendering any malis door will cause a complete client dead, with log contiuous generating crash message. server side is fine.
![client](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/8dd00176-ee9e-4f35-9fbb-95d5b76b4630)
![server](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/abae2908-225a-4ee2-bf7f-430ad1618ed7)

### Crash Report

crash reports here:
[crash-2024-03-31_09.19.04-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813770/crash-2024-03-31_09.19.04-client.txt)
[crash-2024-03-31_09.19.05-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813771/crash-2024-03-31_09.19.05-client.txt)

lastest log file(kinda big since itz generating tons of crash report):
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813772/latest.log)

server latest:
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813777/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Pilad** [comment]
malisisdoors-1.16.2-GTNH , work fine.

**Comment by ah-OOG-ah** [comment]
@Wacchi-Lorie does the crash happen with malisisdoors 1.16.2 or 1.16.1?

**Comment by chochem** [comment]
> @Wacchi-Lorie does the crash happen with malisisdoors 1.16.2 or 1.16.1?

beta1 has malisisdoors-1.16.3-GTNH

**Comment by ah-OOG-ah** [comment]
Fixed in [this PR](https://github.com/GTNewHorizons/MalisisDoors/pull/15)
