### ISSUE TITLE
Breaking things with GT Crowbar sometimes causes server crash

### ISSUE THREAD

**Issue by AbdullahHossain2000** [GTNewHorizons/GT-New-Horizons-Modpack#15880]
### Your GTNH Discord Username

arabadullah

### Your Pack Version

2.6.0 Beta 1 Java 17-21

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

Broke a red alloy wire with a gt crowbar and it caused my private server to crash. Once it came back up I tried with redstone dust, and it crashed again. Next I tried mining a full block, spruce planks in this instance, and none of the cracking effects showed up on the block since crowbars can't mine it, but after holding left click for a little bit on it, I crashed again. I made a MAR-Ce-M200 Steel Crowbar and the first time trying to break redstone dust didn't crash, but after some attempts I did crash. Appears to be somewhat random, not guaranteed.

### Crash Report

First two are client+server logs of first crash, second two are client+server logs of second crash, likewise for the other two sets. (Times are an hour off because the machine I host the server off of has the wrong timezone set)

[crash-2024-03-30_15.21.49-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813131/crash-2024-03-30_15.21.49-client.txt)
[crash-2024-03-30_14.21.47-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813135/crash-2024-03-30_14.21.47-server.txt)

[crash-2024-03-30_15.28.42-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813132/crash-2024-03-30_15.28.42-client.txt)
[crash-2024-03-30_14.28.41-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813136/crash-2024-03-30_14.28.41-server.txt)

[crash-2024-03-30_15.39.00-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813150/crash-2024-03-30_15.39.00-client.txt)
[crash-2024-03-30_14.38.59-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813186/crash-2024-03-30_14.38.59-server.txt)

[crash-2024-03-30_15.58.11-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813174/crash-2024-03-30_15.58.11-client.txt)
[crash-2024-03-30_14.58.10-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14813185/crash-2024-03-30_14.58.10-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Pilad** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/78668b68e3020e06e2ff8dfcc1955987c4087288#diff-c77ef976ad01194a1be313620e8411cf434c3413b342ec52c4e9b01382fde957

**Comment by chochem** [comment]
can confirm on first try. Breaking PRT red alloy wire with gt crowbar results in this crash.
