### ISSUE TITLE
"Not enough soldering material" message appears when it shouldn't; while using toolbox

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#15890]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.6.0 Nightly 417

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

The "Not enough soldering material" message should only display in the chat output when there is not enough soldering material. It should not display when there _is_ enough soldering material.

### The Reality

The "Not enough soldering material" message displays when I use a toolbox (that contains a charged soldering iron and some solder) on a maintenance hatch from the maintenance hatch UI. The repair still happens correctly, but the message displays as though the repair had not been possible.

This only happens when using a soldering iron and soldering material which are contained within the IC2 toolbox, and when using the toolbox from inside of the maintenance hatch UI. It does not occur when right-clicking the maintenance hatch in the world while holding the same toolbox, nor does it occur when the soldering iron and its soldering material are used independently of the toolbox.

### Your Proposal

Ensure that the message only displays when there is _actually_ not enough soldering material.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ReaganAR** [comment]
Should be an easy fix, just need to test and update tomorrow.
