### ISSUE TITLE
Duradisplay shows both durability and charge for some items

### ISSUE THREAD

**Issue by Wacchi-Lorie** [GTNewHorizons/GT-New-Horizons-Modpack#15893]
### Your GTNH Discord Username

wacchi_lorie

### Your Pack Version

2.6.0-beta1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

2.5.1 release's duradisplay 1.1.7 dont show durability for electro tools like vajra, but displays for things both have true durability and charge like gt electro wrench, which is perfect.
2.6.0-beta1's duradisplay 1.2.2 displays both durability and charge for every tools anyway. makes the infos wierdo looking
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/3327866f-c5c5-4fd7-bbc5-c074085ea980)

changing mod config doesnt help

### The Reality

duradisplay displays unnecessary durability for charging tools

### Your Proposal

durability of charging items shouldnt be displayed if it doesnt have true durability

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
can you put one of those pieces in your hand and run `/iih` and post a screenshot of it?

**Comment by Wacchi-Lorie** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/a040b9e2-ce10-46b4-bea6-1fb8aed00611)
this is quantum helmet

ive watched some item's nbt, some dont storage maxcharge, but everything like having 26/27 durability dont acturally store this number in their nbt

like vajra, dont store maxcharge:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/a6ba76ca-b02b-4ccf-9870-f480ef4279e8)
but gt wrench stores all usable infos:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/275f4f6e-982f-4653-92c5-c12c09566897)

and iirc only gt tools have both durability and charge useful and all well stored, mb itz the point to get on with

**Comment by Caedis** [comment]
For some items, I am able to pull the max charge from elsewhere, like IC2 armor, which the quantum armor extends.

**Comment by Caedis** [comment]
You can also change the charge to show as a horizontal or vertical bar. I like mine being on the left edge
