### ISSUE TITLE
MCR Glass does not Limit Energy Hatch Tier for Regular Energy Hatches

### ISSUE THREAD

**Issue by BobGoldham** [GTNewHorizons/GT-New-Horizons-Modpack#15905]
### Your GTNH Discord Username

@bobgoldham

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

The tooltip for the "Mega Chemical Reactor" states: "The glass tier limits the Energy Input tier"
So that is how I expect things to be...

### The Reality

... And it does indeed work that way for multi-amp hatches (so ZPM glass and a 16A UEV hatch, for example, doesn't form).

HOWEVER, this restriction seems to not apply for "regular" energy hatches.
An MCR with "Iridium Reinforced Borosilicate Glass Block" (ZPM) and a "UIV Energy Hatch" (UIV, which is more than ZPM) will form and run.

### Your Proposal

For that to be fixed to where either
A: The restriction applies to regular energy hatches, too or
B: The restriction is removed from this multiblock and the tooltip adjusted accordingly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
Fixed by https://github.com/GTNewHorizons/bartworks/pull/3.
