### ISSUE TITLE
LSC not forming and causing mass lag

### ISSUE THREAD

**Issue by jadeneta** [GTNewHorizons/GT-New-Horizons-Modpack#15909]
### Your GTNH Discord Username

golden0000

### Your Pack Version

2.6 BETA

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Expectation

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/23616799/f16ebc51-c9bf-4997-9179-1f51c145b9a5

upgrading my server from 2.5.1 to 2.6 beta causing the LSC to break, any existing ones i had are fine but if i try to place a new one it will not form and then cause mass lag dropping the server to 1 tps.

### The Reality

upgrading my server from 2.5.1 to 2.6 beta causing the LSC to break, any existing ones i had are fine but if i try to place a new one it will not form and then cause mass lag dropping the server to 1 tps.

### Your Proposal

upgrading my server from 2.5.1 to 2.6 beta causing the LSC to break, any existing ones i had are fine but if i try to place a new one it will not form and then cause mass lag dropping the server to 1 tps. Asked around and no one says they have any issues like this.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by jadeneta** [comment]
also pressing the power button has nothing to do with the issue just placing it down will cause the lag

**Comment by Lyfts** [comment]
Can you upload fml-server-latest from the logs folder on your server?

**Comment by chochem** [comment]
which version are you on actually?

**Comment by jadeneta** [comment]
I was on the newest version 2.6.0-beta-2
But i also was experiencing the bug on 2.6.0-Beta-1
I upgraded from 2.5.1 stable which didnt have the bug, I downgraded and its still fine.
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14860797/fml-server-latest.log)


also haven't really heard about this from anyone else so it might be a me specific issue

**Comment by NickBjurstrom** [comment]
If you updated to 2.6.0 Beta 2, could it be related to the 17x casing check being fixed? https://github.com/GTNewHorizons/KekzTech/pull/83

**Comment by chochem** [comment]
I dont understand the bug yet. thats just a controller in the video, of course that is enough to form the multiblock.

AlLso, when I do the same thing I dont get any tps impact.
