### ISSUE TITLE
IC2 Nightvision googles cannot be charged in MV/HV machines

### ISSUE THREAD

**Issue by kotkowski** [GTNewHorizons/GT-New-Horizons-Modpack#15904]
### Your GTNH Discord Username

kotkowski

### Your Pack Version

2.5.1

### Your Server

Arcturus Network

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

When I instert IC2 Night Vision Googles into machine's charge slot - it should charge - in HV voltage, as it requires HV circuits and is part of HV Nano set (not final)

### The Reality

Charge slot doesn't charge the googles, neither in MV nor HV machines

https://imgur.com/a/1zzTD0T

### Your Proposal

Upon insertion of the item in the charge slot - it should get charged.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
seems to be LV

**Comment by Ethryan** [comment]
Maybe time to add a tooltip for it perhaps @chochem ?

**Comment by chochem** [comment]
go ahead :)
