### ISSUE TITLE
Grossular vein not showing on journeymap

### ISSUE THREAD

**Issue by waylenwasywas** [GTNewHorizons/GT-New-Horizons-Modpack#15901]
### Your Pack Version

2.1.1.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

For overworld grossular veins to show on journeymap

### The Reality

they dont

### Your Proposal

Make them show up

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
Try updating the pack, you are playing on a 2 year old version atm.
