### ISSUE TITLE
Im/Pure Diamond dust centrifuging

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#15900]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.6 beta 2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

The I centrifuge those dusts in the appropriate amount of time, 25-30 seconds, for some graphite for my first arc furnace.

### The Reality

IT takes 5 whole ass mintues????
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40587985/96e5a251-84e0-4ea6-97f4-d45988004be1)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40587985/8934c9ec-b3ed-4a6d-a90d-2c848456d204)

No other steps in oreproc are modified.

It seems other materials also have random centrifuging values, like emerald at 7.4 secs, aruby at 9.6,and garnets at 9.2. Was there some kind of weight based pr I missed for them?

### Your Proposal

Fix???

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
> for some graphite for my first arc furnace.

you know there was graphite ore in the same vein right?

**Comment by LazyFleshWasTaken** [comment]
> > for some graphite for my first arc furnace.
> 
> you know there was graphite ore in the same vein right?

Challange run, nether only. Im just more incredulous about the time it takes for centrifuging, is that intended?

**Comment by LazyFleshWasTaken** [comment]
Welp, just confirmed with someone else too, and huh. guess I just never noticed.
