### ISSUE TITLE
Ram usage increases slowly until instance crashes/ schematica spams console with block not rendering

### ISSUE THREAD

**Issue by JUSTRECT** [GTNewHorizons/GT-New-Horizons-Modpack#15907]
### Your GTNH Discord Username

x_rect

### Your Pack Version

2.5.1

### Your Server

Private server and SP

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

After Playing usually for about 30 min to an hour suddenly Ram usage increases slowly over time until it runs out of space and crashes. I have not recognized a pattern when exactly it happens, sometimes just afking or when moving around the base. 
ive tried different instances / newly downloaded but all are affected. 

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
Can you upload a log of some sort?

**Comment by JUSTRECT** [comment]
so whats the best thing i can do to solve that issue?

**Comment by Pxx500** [comment]
> so whats the best thing i can do to solve that issue?

update the game

**Comment by JUSTRECT** [comment]
its already on the latest stable release

**Comment by Pxx500** [comment]
> its already on the latest stable release

there's a new stable candidate in the announcement channel on discord, use that

**Comment by chochem** [comment]
> > so whats the best thing i can do to solve that issue?
> 
> update the game

its fixed? Just to be clear, I was not claiming that. I just tried to track down where it breaks.

**Comment by JUSTRECT** [comment]
> > its already on the latest stable release
> 
> there's a new stable candidate in the announcement channel on discord, use that

the server im playing on would still be on 2.5.1 so changing version is not an option yet.

**Comment by Pxx500** [comment]
> > > so whats the best thing i can do to solve that issue?
> > 
> > 
> > update the game
> 
> its fixed? Just to be clear, I was not claiming that. I just tried to track down where it breaks.

Hm, it may be not, but since you said the class doesn't exist it is fair to assume it may be fixed and is worth investigating this way since it may just solve the issue altogether.
