### ISSUE TITLE
Wireless EU Network Teaming is gone when server restarts

### ISSUE THREAD

**Issue by ChemEng227** [GTNewHorizons/GT-New-Horizons-Modpack#15918]
### Your GTNH Discord Username

XuDongWan#3232

### Your Pack Version

2.6.0beta1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Wireless EU Network Teaming created with /gt global_energy_join shall be stable in multiplayer.

### The Reality

When the server stop and restarts, all teaming is gone and tons of machines shut down.

### Your Proposal

If it was a bug, fix it.
If it was caused by lost file or something, tell me how to fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alaking** [comment]
still an issue on 2.6.0

**Comment by Wargenflorgen** [comment]
Also getting this issue on 2.6.0. Pretty major bug since any EU spent by people who aren't the network owner will be "refunded" upon rejoining the network, meaning parts of your base essentially won't cost any EU at all until fixed. Feels very cheaty and there's no way to avoid it.

**Comment by boubou19** [comment]
fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/3000
