### ISSUE TITLE
Improve ore vein / name consistency regarding Banded Iron, Garnierite, Roasted Iron, and Roasted Nickel by replacing the former two with the latter two.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#15912]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.5.1

### Your Proposal

Current Ore Veins that contain Banded Iron Ore:
- Change it to Roasted Iron Ore

Current Ore Veins that contain Garnierite:
- Change it to Roasted Nickel Ore

Separately, potentially add a centrifuge output from some dust or similar for Garnierite Dust (FeO), like with Banded Iron Dust and Diatomite/Ashes.

### Your Goal

Improve naming consistency and avoids confusion when looking through NEI or similar. Simultaneously fixes the SAG Mill alt recipe bug.

### Your Vision

As per the past issues https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11648 and https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11632 via @chochem, it seems that the intended behavior is for the aforementioned ore veins to give the player roasted iron/nickel ore. It also seems that the SAG Mill recipes to get crushed Banded Iron & Crushed Garnierite are both unintentional/bugs. That's fine to have, but the ores themselves should be replaced by their properly named versions instead, to keep consistency between ore block names and the crushed forms they yield.

Plus, Roasted Iron Ore and Roasted Nickel Ore aren't even currently obtainable (as far as I know). So if the current processing paths of Banded Iron and Garnierite aren't meant to be accessible through the Sag Mill, then why not simply swap these two ores? Both ore pairs through standard GT ore processing yield the same results (*including* byproducts), so it shouldn't even interfere with current processing. And it fixes the issue of the sag mill alternatives, since neither Banded Iron Ore nor Garnierite Ore would be obtainable as well.

Now yes, Garnierite Dust and Banded Iron Dust do have the aspect of electrolyzing for oxygen (compared to their Roasted alternatives), but both dusts don't have to become inaccessible, just earned through byproducts or similar. Banded Iron Dust already has that through Diatomite and Ashes. Garnierite doesn't, but that could be added in a later update. There's probably some NiO compound that could be earned through centrifuging.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Prometheus0000** [comment]
My quick google search indicated that roasted iron/nickel are not something naturally occurring, are you sure they are?

**Comment by PlayfulPiano** [comment]
> My quick google search indicated that roasted iron/nickel are not something naturally occurring, are you sure they are?

Are you referring to real life or in terms of within GT?

**Comment by Prometheus0000** [comment]
Real life, obviously. Like, I don't think a vein of steel makes sense, so why would we have an ore vein of something similar? That isn't ore anymore.

**Comment by PlayfulPiano** [comment]
> Real life, obviously. Like, I don't think a vein of steel makes sense, so why would we have an ore vein of something similar? That isn't ore anymore.

In game, as per NEI, there *are* ore block variants for both roasted nickel and roasted iron. And this suggestion is more in terms of game design clarity over direct realism (which like, this modpack isn't a full "everything is realism" structure whenever possible).

**Comment by Ethryan** [comment]
Roasted ores suggest that they have passed some kind of processing. And the straight up ore blocks are generated together with the other ore materials, Crushed, Purified and so on. Including the recipes. So to decouple the blocks from that material tag is frankly more work than its worth.

This doesn’t mean that the Roasted ore blocks will ever be used in a vein.

In my opinion this is working as intended and shouldn’t be changed.

**Comment by PlayfulPiano** [comment]
> Roasted ores suggest that they have passed some kind of processing. And the straight up ore blocks are generated together with the other ore materials, Crushed, Purified and so on. Including the recipes. So to decouple the blocks from that material tag is frankly more work than its worth.
> 
> This doesn’t mean that the Roasted ore blocks will ever be used in a vein.
> 
> In my opinion this is working as intended and shouldn’t be changed.

That might be obvious to someone with a chemical background, but it's also a video game modpack and the naming conventions become confusing without that context. My point is that the change in the ore name in the vein, that doesn't change any actual gameplay functionality, would be a clear positive in game clarity and shouldn't be a big deal at all.

**Comment by joshaup1999** [comment]
This hasnt caused any sort of confusion for the last 8 or so years. Not sure why its a needed change apart for the sake of realism. The roasted stuff in the game was only a recent addition within the last 2 years or so, which in and of itself was an annoyance

**Comment by hallucinogender** [comment]
The ores should still be Banded Iron and Garnierite. If anything is to be changed, it should be the "roasted" versions. That said, I don't think they really need to be changed.

**Comment by PlayfulPiano** [comment]
> The ores should still be Banded Iron and Garnierite. If anything is to be changed, it should be the "roasted" versions of the processed items. That said, I don't think they really need to be changed.

I'm personally fine with either or (banded/banded and garnierite/garnierite or roasted/roasted for both). Keeping it roasted might make more sense though just in terms of current version storage and filtering.

**Comment by chochem** [comment]
I dont care one bit about the naming, but the idea is that one of them is 'chemical pure' can potentially by synthesized and follows chem balance and the other comes from ores and is impure without clear composition, does not follow chem balance and thus allows for the multiplication recipe in the blast furnace.

So you should be clear if you want to change some aspect of that or just naming.

**Comment by PlayfulPiano** [comment]
> I dont care one bit about the naming, but the idea is that one of them is 'chemical pure' can potentially by synthesized and follows chem balance and the other comes from ores and is impure without clear composition, does not follow chem balance and thus allows for the multiplication recipe in the blast furnace. This split allows for the blast furnace multiplication without creating infinite loops.
> 
> So you should be clear if you want to change some aspect of that or just naming.

Just naming so the ore and the item you get from processing stay consistent with each other. I.e. mining "x" ore and putting it into a macerator yields "x" crushed ore, not "y" crushed ore.

If it's intended for the early iron ore vein's iron ore (that isn't limonite) to not have extra processing options or whatever, then the suggestion would be to replace "banded iron" with "roasted iron". If it's intended to be specifically the "banded iron ore" block for that vein, then have banded iron ore process into crushed banded iron ore and similar.

**Comment by PlayfulPiano** [comment]
.

**Comment by Ethryan** [comment]
I'm still against renaming these.

**Comment by PlayfulPiano** [comment]
> I'm still against renaming these.

I just think that keeping the names of ores and their crushed variants consistent is much less confusing for new players and makes little difference to veteran plays of GT. Realism is not really so important for this, that the new player experience has to be made worse for it.

**Comment by PlayfulPiano** [comment]
.
