### ISSUE TITLE
Quick and dirty portal generator recipe

### ISSUE THREAD

**Issue by Fieos** [GTNewHorizons/GT-New-Horizons-Modpack#15911]
### Your GTNH Discord Username

fieos

### Your Pack Version

2.5.1

### Your Proposal

Remove first tab of quick and dirty portal generator recipe.

### Your Goal

The first recipe is completely redundant because it just shows the diamond + integrated logic circuit. Second page cycles through all available options. 

### Your Vision

Reduces confusion for players who see the recipe and think they need to make the integrated logic circuit instead of the lower tier LV circuit that is available to them. It's come up a few times in #help recently in the GTNH discord.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
guess circuit need to change to oredict. And 1 step can be optional if not already.
