### ISSUE TITLE
Smelting nether or end gem ore does not have 2x yield

### ISSUE THREAD

**Issue by Tyrantnh** [GTNewHorizons/GT-New-Horizons-Modpack#15910]
### Your GTNH Discord Username

Banned :3

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

All ores except gems yield 2x product in nether/end form

### The Reality

Does not have 2x ore
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/124327404/96e9b9f9-c53b-41e4-bc2a-cfaf2b1c397d)

### Your Proposal

Change it so all gems ores get 2x product when smelting end and nether form

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
What about the output of a gem ore in the hammer? Is that halved?

**Comment by Tyrantnh** [comment]
> What about the output of a gem ore in the hammer? Is that halved?

No, only smelting for some reason
