### ISSUE TITLE
Quantum ring uses 2k eu a tick instead of 1k as per quest

### ISSUE THREAD

**Issue by elak93** [GTNewHorizons/GT-New-Horizons-Modpack#15920]
### Your GTNH Discord Username

elak93#1348

### Your Pack Version

2.5.1

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

Quantum ring quest says quantum rings are 1000 EU per pair

### The Reality

Eu used per ring is close to but not quite 2000 EU per pair

### Your Proposal

Fix which ever side of this is the unintended result. Quest updated to 2000 eu per pair or quantum ring brought back to 1000 eu per pair ![1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47580025/23b4ff35-396d-4f08-92c4-4609633e5e36)
![2](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47580025/ac969da7-397d-4426-8635-4730e7bf715e)
![3](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47580025/e1e78363-1ec1-4353-9cd9-da4bf36f2f20)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
yea its definetely 1k per ring, not per pair. somebody got confused there.
