### ISSUE TITLE
Waila display wrong capacity of super tank when overflow voiding is enabled

### ISSUE THREAD

**Issue by hoshinokiseki** [GTNewHorizons/GT-New-Horizons-Modpack#15923]
### Your GTNH Discord Username

kisekiunofficial

### Your Pack Version

2.6.0-beta-2

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Waila displays wrong capacity of super tank when overflow voiding is enabled. But the real capacity is still 4000,000mB for super tank I.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/88672077/ab17d22b-0632-44fd-baaf-37f366184fdc)

### Your Proposal

capacity of super tank displayed by waila shouldn't be influenced by overflow voiding mode.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Quarri6343** [comment]
Already fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2571
