### ISSUE TITLE
Recursive Pattern cause recursive items uncraftable

### ISSUE THREAD

**Issue by reobf** [GTNewHorizons/GT-New-Horizons-Modpack#15921]
### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Use Crafting Calculator v2 
Encode two Patterns like:
![1712294833006](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/117543727/50394c8f-9fd7-4e8a-b929-509856de2619)
![1712294856924](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/117543727/5a3d1c9e-ae93-411f-a16b-ae2d4cca4421)
Stone should be craftable via the second Pattern.

### The Reality

Stone is uncraftable, even if priority of the sencond pattern is set higher.
![1712294885709](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/117543727/c1b59945-2fcc-4e97-9448-3e2ba62ddf85)
And get a warning in log
```
[13:23:57] [Server thread/WARN]: Error encountered when trying to generate the list of CraftingTasks for crafting {}
java.lang.IllegalStateException: Invalid pattern crafting step for CraftingRequest{request=1xtile.stone@0<Stone>, substitutionMode=PRECISE_FRESH, remainingToProcess=1, byteCost=0, wasSimulated=false, incomplete=false}
	at appeng.crafting.v2.resolvers.CraftableItemResolver$CraftFromPatternTask.<init>(CraftableItemResolver.java:126) ~[CraftableItemResolver$CraftFromPatternTask.class:?]
	at appeng.crafting.v2.resolvers.CraftableItemResolver.provideCraftingRequestResolvers(CraftableItemResolver.java:600) ~[CraftableItemResolver.class:?]
......
```

CraftingContext.getPrecisePatternsFor(IAEItemStack stack) searches for Pattern whose outputs matches the stack.
However, constructor of CraftFromPatternTask will remove recursive items, which makes outputs no longer matches the stack.
Then CraftFromPatternTask will throw a java.lang.IllegalStateException and abort the resolving progress.
```
public CraftFromPatternTask(CraftingRequest<IAEItemStack> request, ICraftingPatternDetails pattern,
                int priority, boolean allowSimulation, boolean isComplex) {
            super(request, priority);
            this.pattern = pattern;
            this.allowSimulation = allowSimulation;
            this.isComplex = isComplex;

            HashBasedItemList pInputs = new HashBasedItemList();
            HashBasedItemList pOutputs = new HashBasedItemList();
            HashBasedItemList pRecInputs = new HashBasedItemList();
            calculatePatternIO(pattern, pInputs, pOutputs, pRecInputs);
            //'pOutputs' does not contain recursive items
            this.patternInputs = pInputs.toArray(new IAEItemStack[0]);
            this.patternOutputs = pOutputs.toArray(new IAEItemStack[0]);
            this.patternRecursionInputs = pRecInputs.toArray(new IAEItemStack[0]);
            IAEItemStack foundMatchingOutput = Arrays.stream(patternOutputs).filter(this::isOutputSameAs).findFirst()
                    .orElse(null);
            if (foundMatchingOutput == null) {
                // if the requested item is recursive in this pattern, 'foundMatchingOutput' will be null
                state = State.FAILURE;
                throw new IllegalStateException("Invalid pattern crafting step for " + request);
                //an Exception, forcing the resolving progress to terminate, even if other Patterns are valid
            }
            this.matchingOutput = foundMatchingOutput;
        }
```

### Your Proposal

1.At least silently ignore invalid CraftFromPatternTasks instead of aborting the resolving progress.
2.Maybe make CraftingContext.getPrecisePatternsFor(IAEItemStack stack) always return Patterns valid for CraftFromPatternTasks.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
yes this was not an issue, it became an issue after a recent update

**Comment by reobf** [comment]
> yes this was not an issue, it became an issue after a recent update

It seems that the bug has been there since the initial commit of Crafting Calculator v2.
Switching to v1 might workaround.
