### ISSUE TITLE
Super Fuel Binder Can be made with unobtainable item

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#15922]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.6 beta 2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Fuel binder would be made with glue, like super, advanced, or normal.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40587985/4873f9a0-46ac-4a9d-ba62-d302e69e8a9f)
its made with an unobtainable fluid. An id issue of some kind?

### Your Proposal

Fix?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
its obtainable. you can find it in world.
