### ISSUE TITLE
Use of bucket(Iron) crash's game when trying to pick up water.

### ISSUE THREAD

**Issue by SpawnsLilHope** [GTNewHorizons/GT-New-Horizons-Modpack#15928]
### Your GTNH Discord Username

valanwolfzahn

### Your Pack Version

2.6.0-beta-2

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Trying to pick up a bucket of water. Just planted Slime Trees prior to the crash happening.

### Crash Report

https://mclo.gs/nawfw7s

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
thats sounds pretty concerning. however, everything seems fine on my end in 2.6.0-beta2

**Comment by Pxx500** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/bb58051b-2387-4792-a152-45c2b63dab46)
No problems here either (2.6.0 beta2, j21)

**Comment by SpawnsLilHope** [comment]
Odd. I just encountered it again trying to get Lava. https://mclo.gs/zp3a8ib

**Comment by OtherGamer** [comment]
Yes, same issue...
[crash-2024-04-30_18.08.07-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15166903/crash-2024-04-30_18.08.07-server.txt)
[crash-2024-04-30_18.08.17-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15166904/crash-2024-04-30_18.08.17-client.txt)

**Comment by SnackJunkie** [comment]
I'm experiencing the same issue on 2.6.1 and disabling sodium fluid rendering in angelica seems to fix it

**Comment by mitchej123** [comment]
> disabling sodium fluid rendering in angelica seems to fix it

Good to know, but it's disabled by default for a reason....

**Comment by LightDimf** [comment]
> I'm experiencing the same issue on 2.6.1 and disabling sodium fluid rendering in angelica seems to fix it
Indeed fixed it. Thanks.

**Comment by Supersonic2510** [comment]
> I'm experiencing the same issue on 2.6.1 and disabling sodium fluid rendering in angelica seems to fix it

I'm experiencing the same but disabling sodium fluid rendering didn't fix it. Tried to disable sodium render and nothing changed
