### ISSUE TITLE
Dozens of different type of item, especially enchanted ones, getting fps ruined

### ISSUE THREAD

**Issue by Wacchi-Lorie** [GTNewHorizons/GT-New-Horizons-Modpack#15936]
### Your GTNH Discord Username

wacchi_lorie

### Your Pack Version

2.6.0-beta1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

fix item render lag, maybe caused by angelica

### The Reality

Staying still at my base is 220fps
Watch full compressed chest of minerals is around 40-60fps
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/b6666b96-aaac-4f55-9781-0405e05acb4a)
a chest of different weapons and equipments, some animated, around 40fps
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/d4ec2a5a-fb76-45d1-aa16-9ce0d989eefd)
some soul vials will kill fps to 20fps
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/031ce496-a88b-4b30-8522-2e1219376a20)
only few kinds of bees with enchanted aura could make fps never exceed 10, not if they dont have enchanted aura
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57549294/033562ec-2c49-4649-93d9-41710e6506dc)

fps lagging exists by direct view or holo lens
watching my ME terminal is around 50fps
p.s. tested later without any resource packs, same number

### Your Proposal

this issue is not very noticable at 2.5.1 with angelica-1.0.0-alpha35 installed
maybe some thread safe issues?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Wacchi-Lorie** [comment]
items at nei, enchanted or not, dont kill fps

**Comment by Caedis** [comment]
Did you test without angelica?

**Comment by Wacchi-Lorie** [comment]
same without angelica
