### ISSUE TITLE
Crash while pressing toolbelt swap button inside TiC Crafting station GUI

### ISSUE THREAD

**Issue by GL8192** [GTNewHorizons/GT-New-Horizons-Modpack#15930]
### Your GTNH Discord Username

gl1892

### Your Pack Version

2.5.1

### Your Server

sp and private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

After pressing key for Traveller's Belt to swap hotbar inside crafting station, game crashed, this happened on server originally, server did not crash. after re-testing in single player i got same results

this bug did not happen in vanilla bench

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/157964435/6b301dca-0ccb-4146-a37a-d518190aa9b4

key is bound to "v" if that is any relevant, no conflicts in controls tab

### Crash Report

https://pastebin.com/L4zTVu8u

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ReaganAR** [comment]
I can replicate this in 2.5.1, but not in the 2.6.0 beta. Definitely seems to be an issue with favorites and "Pull items from favorites to inventory" rather than the toolbelt.

**Comment by ReaganAR** [comment]
Probably fixed in https://github.com/GTNewHorizons/NotEnoughItems/pull/451, which adds checks to the 'pullBookmarkItems' causing the above crash

**Comment by chochem** [comment]
seems to be fixed
