### ISSUE TITLE
Water Bottle no longer craftable in Fluid Canner

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15935]
### Your GTNH Discord Username

Abdiel Kavash

### Your Pack Version

2.6.0-beta-2

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Craft a Water Bottle in a Fluid Canner, using 1 Glass Bottle + 250 Water

### The Reality

Recipe no longer exists.

### Your Proposal

Restore the canner recipe. Water bottles are used in some magic crafts (for example, Aquasalus from Blood Magic) and there should be some way to autocraft them.

Might be caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2494?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
> there should be some way to autocraft them.

a tank should do just fine.

can have a look at canner later, its been a while. But 250 would be strange, a tank would still be the way to go then.

**Comment by AbdielKavash** [comment]
I know that a tank works, but the canner is already needed for coolant cells and such, and also late game it is faster (not that it particularly matters here). It's not that it's *needed*, it's that I see no reason for not having it there if the player wants.

I can add an explicit recipe for this in coremod.

**Comment by Ethryan** [comment]
> I know that a tank works, but the canner is already needed for coolant cells and such, and also late game it is faster (not that it particularly matters here). It's not that it's _needed_, it's that I see no reason for not having it there if the player wants to use it.
> 
> I can add an explicit recipe for this in coremod.

Don’t it belong in GT5U instead?
Sounds like a main setting instead of modpack only.

**Comment by chochem** [comment]
seems to work just fine 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/74b8beed-33a8-4868-853c-931648f5cffe)

**Comment by AbdielKavash** [comment]
Oh, I see. The bottle still fills up, but it does not drain any water from the input tank. The recipe also doesn't show in NEI.

I suppose this is consistent with how we decided to handle water bottles some time ago (a bottle is worth 0 mB of water). Still it makes automation fairly annoying. Essentially you *need* a separate device just for water bottles; you can't pump fluid + container anywhere (canner or a tank), as the water would stay in the container and block subsequent operations.

**Comment by GTNH-Afx237v7** [comment]
I can reproduce this in 2.6.1.
Same opinion here as AbdielKavash - water bottles are needed in various places (personally, I needed them for Aquasalus from Blood Magic) and a proper automation would be nice. Using a fluid canner filles them up but uses up 0 water, therefore blocking the fluid input slot.
