### ISSUE TITLE
Odd Biome Updating Interaction between Soul Brazier and Ethereal Blooms

### ISSUE THREAD

**Issue by D0rako** [GTNewHorizons/GT-New-Horizons-Modpack#15931]
### Your GTNH Discord Username

dorako_

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I have set up a Soul Brazier with a constant feed of Mortuus essence and Ignis centi-vis, as well as 11 Ethereal Blooms covering the 16x16 area the Brazier can turn into Tainted Lands. As the Brazier seems to only convert one tile every 3 seconds (compared to the Blooms' 1 second) there should not be many tiles being Tainted Lands, and those that do should convert in a few minutes back to the original biome due to the Blooms.

### The Reality

The Tainted Lands-turned tiles do not change back into the original biome after 10-20 minutes. Closing the game or moving between dimensions causes >70% of converted tiles to immediately change back to regular biome. This is not traditionally reloading a chunk as I've had a chunkloader loading the effected chunks, as well as Soul Brazier acting as a singular chunkloader.

### Your Proposal

I successfully managed to recreate this in creative and this still happens after spamming the entire area with Ethereal Blooms. Trying to look over decompilations, etc, to figure out if I was stuffing up at some point my best guess would be this is some sort of weird tile biome updating thing where the Brazier correctly flags the tile as changed but the Blooms don't.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
were you within 32 blocks range of ethereal bloom? if not it might have difficulty propagating the changes to the logical client

**Comment by Glease** [comment]
Try upgrade TC4Tweaks to 1.5.22 and see if it fix your problem

**Comment by LazyFleshWasTaken** [comment]
Can confirm this happens. Tainted a part of then Nether to try and turn it to magical forest, didn't work, so I placed some ethereal blooms to turn it back. It didn't update until I relogged.

**Comment by D0rako** [comment]
Oh whoops I didn't realize there were patches to base Thaumcraft in here, somehow managed to miss it looking around.

> Try upgrade TC4Tweaks to 1.5.22 and see if it fix your problem

This is still reproducible after I did this from a fresh 2.5.1 install and updating to the latest version of TC4Tweaks.

> were you within 32 blocks range of ethereal bloom? if not it might have difficulty propagating the changes to the logical client

I'm testing this by idling over the tainted lands tile and surrounding it with like 20-30 blooms, so distance doesn't seem to be it.
