### ISSUE TITLE
NEI search does not correctly parse string expressions with Mod ID

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15934]
### Your GTNH Discord Username

Abdiel Kavash

### Your Pack Version

2.6.0-beta-2

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Enter a string such as `@chisel|@ztones` into the NEI search bar.

See all blocks from both mods in NEI.

### The Reality

Only blocks from the first mod (`@chisel` in this example) are shown.

### Your Proposal

I remember that this used to work at some point in the past, as this was the method I used to search for decorative blocks. However I can't get the search (also playing around with spaces and various NEI options, as suggested by discord) to work in either 2.6.0-beta-2, 2.5.1, or 2.5.0.

Also, currently, the expression works if only item names are used (so for example, `dirt|stone` does what you would think). It is only when mod names are involved that this breaks.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by slprime** [comment]
I reviewed the changes in the "Subsets" filter. The last change to the filtering method was 3 years ago. and the only thing that was changed was the separator `->` between the mod and the item. Perhaps you used a third-party mod or it was not available in 1.7.10
