### ISSUE TITLE
Blackscreen When Looking at Heretic Vilager with Holo Glasses

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#15947]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.6 beta 2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When looking at Heretic villager, or any at all, with the holo glasses, the trades pop up above. This does not happen 2.5.1+

Specifically though, even though nothing renders, the screen blacks out when looking at specifically the heretic villager. Might be a specific trade doing it.

### The Reality

Screen blacks out with heretic.

### Your Proposal

Fix? It's probably angelica. I don't have Optifine. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
Fixed on Beta 3.

Trades still arent showing though.

**Comment by chochem** [comment]
if it is an angelica bug, please try with a newer version and if it still happens post on angelica tracker https://github.com/GTNewHorizons/Angelica/issues
