### ISSUE TITLE
Centrifuge Multiblock No Valid Recipe Found

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#15948]
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

2.6.0-beta-1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Centrifuge should detect and start the recipe

### The Reality

My Naquadah line already made about 20k dust, but at certain moment the centrifuge run out of energy.
I switched it on with Soft Mallet, after that I started having the issues.

It will stop working saying no recipe found, but there are all ingredients inside and output space  also available.

This is the Centrifuge recipe for "Low Quality Naquadah Solution".
I do not change any mode on the Multiblock controller.
The recipe just doesn't work.
If I replace the controller, it immediately starts to work and it  sees the recipe. It works for some time and then it stops working saying again there is no recipe.
Can it be related to the fact I have a lot of LV input buses and somehow that is breaking the multiblock?
![Screenshot_6](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/4941736/6078bb49-92ab-47ce-a0e1-95f23120af0a)

### Your Proposal

Fix Centrifuge to not stop accidentally.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
works just fine for me. including with lv input bus.
