### ISSUE TITLE
2.6.0 beta-3 - with optifine 1.7.10 is not starting

### ISSUE THREAD

**Issue by AtHisF1nest** [GTNewHorizons/GT-New-Horizons-Modpack#15950]
### Your GTNH Discord Username

athisf1nest

### Your Pack Version

2.6.0 beta-3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Using optifine 1.7.10 HD U E7, game stuck at loading

### Crash Report

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/41022571/9bf9a3cf-31cc-454a-b057-b2fb82c63798)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14935340/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by hallucinogender** [comment]
This is not a bug, nor is it any kind of error. There is a mod called "Angelica" which _replaces_ Optifine. You cannot install both. Remove Optifine, and you will be fine.

**Comment by mitchej123** [comment]
> Is it possible to have shaders with Angelica?

soon ™️
