### ISSUE TITLE
Crafting Station does not show NEI recipe preview in grid when "?" clicked

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#15952]
### Your GTNH Discord Username

britishcynic

### Your Pack Version

2.6.0-beta3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

When the Crafting Station UI is open, and when an item in NEI is clicked that has a crafting grid recipe, pressing the "?" button in the UI should cause the crafting recipe's items to be superimposed into the crafting grid

### The Reality

This does not happen and the "?" button is functionally useless.

### Your Proposal

Restore the functionality.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
can confirm.

Also went back and this did indeed work on 2.5.0.

**Comment by chochem** [comment]
I started up some old nightlies I had to narrow things down:
This was broken at some point between 2.5.0 (17 Dec '23) and nightly-310 (13 Jan '24)

**Comment by chochem** [comment]
ok I was able to narrow it down further. Its definetely NEI and specifically between 2.5.4 and 2.5.5-pre: https://github.com/GTNewHorizons/NotEnoughItems/compare/2.5.4-GTNH...2.5.5-GTNH-pre
