### ISSUE TITLE
Intermittent flickering of some machines/chests/etc 2.6.0 beta 3 java 21

### ISSUE THREAD

**Issue by rbraunm** [GTNewHorizons/GT-New-Horizons-Modpack#15955]
### Your GTNH Discord Username

Toshiro4269

### Your Pack Version

2.6.0 beta 3 java 17-21

### Your Server

private server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Entities do not flicker intermittently

### The Reality

Entities do flicker intermittently but only some entities. (Video provided)

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/5680061/e0956f61-5b1c-40b6-ad62-aad4830e8366

CPU: Ryzen 7 3800X
GPU: GeForce RTX 2080 Ti
Win10
Drivers and Windows fully up to date

### Your Proposal

Stop entities from flickering

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Yamnasm** [comment]
Does not seem to be any more reports similar to this issue on flickering entities in the last 6-8 months (nothing on post-2.6.1, though it seems the consensus from previous issue that it was angelica causing some visual issues like this. Labelling this as Stale.
