### ISSUE TITLE
Add the ability to convert an LV Machine Hull to a Maintenance Hatch by right clicking with a Tool Box.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#15954]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.5.1

### Your Proposal

When you have a Tool Box filled with the necessary tools to normally craft a maintenance hatch in a crafting table, you can right click that tool box onto a placed LV Machine Hull to immediately convert it into a Maintenance Hatch. Doing so uses 1 durability per tool needed in the craft.

### Your Goal

Makes creating maintenance hatches a lot easier, especially when considering the annoyance of having to place tools in specific spots in the 3x3 crafting grid. 

### Your Vision

Useful QoL, makes logistical sense.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
you should use the assembler recipe
