### ISSUE TITLE
fastcraft suspected causing crash when joining server

### ISSUE THREAD

**Issue by auntoy69** [GTNewHorizons/GT-New-Horizons-Modpack#15953]
### Your GTNH Discord Username

auntoy

### Your Pack Version

2.5.1

### Your Server

private

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

was able to play in single player, but crashes when trying to join server

### Crash Report

https://mclo.gs/LxWzy3L

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
fastcraft is removed in dev
