### ISSUE TITLE
Diamond Dolly didn't work

### ISSUE THREAD

**Issue by Proficus** [GTNewHorizons/GT-New-Horizons-Modpack#15968]
### Your GTNH Discord Username

mihailgrand

### Your Pack Version

2.5.1

### Your Server

Eta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I try to pickup spawner with Diamond Dolly but its not work
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31763068/ed1d4bba-6d29-4616-bf73-e27dc37c910c)

### The Reality

I tried to pickup using the right mouse button, as well as using the shift, but it did not give any results.

### Your Proposal

I noticed that dolly's appearance has changed, I assume that something has happened to her. I do not know how to find a solution and how to pickup a spawner

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@querns

**Comment by querns** [comment]
The diamond dolly can only move vanilla Minecraft spawners. The spawner you're trying to move is a Hardcore Ender Expansion variant spawner, which isn't explicitly whitelisted in the diamond dolly code. Extra code would have to be added to allow these types of spawners to be moved.

**Comment by Dream-Master** [comment]
was this not added to support HEE spawners?

**Comment by querns** [comment]
Yes, https://github.com/GTNewHorizons/Jabba/pull/34 . This can be closed as completed.
