### ISSUE TITLE
Logistics pipes tier rebalance

### ISSUE THREAD

**Issue by imTheSupremeOne** [GTNewHorizons/GT-New-Horizons-Modpack#15969]
### Your GTNH Discord Username

imthesupremeone

### Your Pack Version

2.5.1

### Your Proposal

**Problem :** 
LP is effectively too close to AE. AE items are just gated by titanium and at that stage otherwise are very cheap, easy and affordable.

LP is spread all over MV till it's end and for regular player it's better to always get the next thing before setting up system (Drawer Controllers: requires Stainless steel; Type Filter Module and Upgrade chips: stupidly overcomplex requiring Kanthal processing; absurd variety of things, including AE2 chips).

If player chooses to setup early he will be punished by requiring a large amount of expensive low tier modules; doing extra effort for filtering a system; for all of that to become obsolete in a next day of progression.

**Proposed solution:**
Since you prob won't touch and make AE harder as it will make players mad; I think LP should be aggressively buffed : 
1) it should be pushed to Late LV (being gated by EBF material just like AE by Titanium?)
2) with such a small spread in progression to not being punished player should be able to get all the convenience items at once : 
- singular **Drawer Controller** should be rewarded for completing basic LP quest chain and prob sacrificing some LP items;
- a Type Filter Module should be straight accessible;

- either Extractor Module MK1 and MK2 speed should be rebalanced inside of LP mod itself or the MK3 version should be accessible for players right from start. The current difference of MK1 being 1 item per billion years; MK2 -- 1 item a sec; MK3 -- whole chest per sec may indicates that they may be originally balanced on how they load a server rather than a progressive throughput and they are not meant to be an age apart from each other.

- while AE has it's own lootbags; I think some really generous rewards in LV?-MV lootbags would be really welcome.

=======

Also another thing that isn't like bad or anything just feels off and misalignment from intent of original mod.... It's prob would be a nerf but you can prob compensate by buffing an original path....

So the Logistics Chassis recipes from MK1 to 5 were given additional GregTech treatment so that those chassis could be either step-by-step upgraded from MK1 to 5; or crafted straight from the basic pipe.. AND it's actually far more efficient than upgrading.

I believe not everything should get a GT treatment just for a sake of it. In this case like with GT machines they are not exactly better with upgrades (they consume x2 energy) while LP Chassis there is no downsides and only upsides from going straight to "da best". I feel it's kinda stupid; it's FOMO if you like craft a tier below and then regret by having to upgrade it and it's also braindead : you are not getting rewarded by planning your system to use the exact right tier of Chassis(you are actually getting punished in a future if you wish to upgrade to better ones). This is like for some smallest flow of 100 L/s; to use megaexpensive omegalarge pipe with radius of Uranus, and still be rewarded for it.

### Your Goal

Backstory : I'm playing with my friend but both of us kinda separate. My friend goes vertically through progression when I've decided to go wide to experience more of modern 1.7.10 since I'm not sure if there would be anything like GTNH in a foreseeable future.

I am early HV and my friend is mid(late?) HV -- already been on the Moon. I was selling my friend LP since the beginning as it's super cool watching items flow in pipes; but him being more of a main-vertical progression guy skipped it.

I was never checking the AE recipe. I thought it to be something of an EV+ tier like mid EV having a lot of nasty components. So I've put some time to learning LP again; getting used to GTNH recipes; experimented how to do sorting with really small amount of modules  (Drawer Controller + GTNH's Type Filter Module for GT microcraft stuff); and so I've proposed my friend to make him small system too thinking that he's still far from AE; but he replied that it's easy and he already working on Ti; so he doesn't need that... :< 

So I've finally checked it for myself and was shocked from like how cheap AE is; like it's only just gated by Ti; how inconsistent balance between them... Mb that's because AE is the main thing and being constantly tweaked and played for players to point out inconsistencies; while LP is not played by many as it's probably already daunting to learn; it's only an early game mod and sits in a weird balance that at the point you get everything it's just better to rush Moon and AE.

This is why here I want to share my playtest and thoughts about balance.

### Your Vision

I believe that GTNH's early game is fantastic; and the pack should make it's way to actually encourage players to play with LP and stay and experience different mods in early game too since you just can't go back and play with Steve's Carts. 

Right now you don't have a full package of convenience till like late MV; and after that there's there isn't huge difference between going into LP or rushing AE and considering that LP is definitely going to become obsolete; players who are not explicitly wanting to play with LP have no reason or even discouraged to play with it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
a full rework of lp recipes are planned after 2.6.0
LP will be doable in lv and mv in the future.

**Comment by hallucinogender** [comment]
There _is_ the Project Red item pipe system in LV. Logistics Pipes being pushed to LV will make the Project Red equivalent largely obsolete, given that it is markedly less capable of doing a similar job. This isn't necessarily a bad thing, but it does mean that the place of the Project Red transport pipe system in the pack will need to be reconsidered.

**Comment by Dream-Master** [comment]
Project red pipes are now using only lv components. I work on them too

**Comment by imTheSupremeOne** [comment]
> There _is_ the Project Red item pipe system in LV. Logistics Pipes being pushed to LV will make the Project Red equivalent largely obsolete, given that it is markedly less capable of doing a similar job. This isn't necessarily a bad thing, but it does mean that the place of the Project Red transport pipe system in the pack will need to be reconsidered.
> 
> If the Project Red transport pipe system is pushed _earlier_ in LV (e.g. by removing the requirement for MV circuits) then this would help to solve the issue. Logistics Pipes could still be an upgrade to the Project Red system, but one gated later in LV.

They are just objectively a worse copy of LP. LP right now is too dated and worse AE; but at least it's different and interesting in a way.

I think making them cheaper could be cool if somebody wants to play with them; but I'd say they shouldn't be made into a progression so that player makes them -> LP -> AE; since rebuilding a system that is a bunch of GUI filters isn't that interesting...

P.S. also the LP has a HUGE thing in it added by GTNH somebody that is "Type Filter ItemSink Module". Without it it would be pretty despair to filtering even with polymorphic all of the forms that all GT materials, alloys can be in...

**Comment by imTheSupremeOne** [comment]
I've looked at Project Red's stuff and damn that shit is expensive too....

Yea I hope a balance would be more gated rather than being expensive and complex at the same time. The AE 4k storage is built from ULV lamps and LV circuit; while even for Project Red's basic stuff like "provider" or "polymorphic filter" you need MV(which at point of LV and early MV is a top tier) to make only one..... ._.

(and you need so much more of them to store stuff in chests...)

**Comment by imTheSupremeOne** [comment]
Btw is applying upgrades to Modules is broken in GTNH or globally in 1.7.10 ?..
https://ftbwiki.org/Upgrade_Manager

There is no item like this, but some upgrades like Fuzzy or Crafting ones still are saying that they can be applied to Module cards...

**Comment by imTheSupremeOne** [comment]
Idk if this is in 1.7.10 Logistics Pipes or was it hidden by GTNH; but this in theory could allow to pass LP network inside a cleanroom : 🤔 
https://ftbwiki.org/Logistics_Inventory_System_Connector

**Comment by imTheSupremeOne** [comment]
> Project red pipes are now using only lv components. I work on them too

This is also complete pain and unviable if somebody wish to use other mods from EnderIO (this does the round-robin)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13508453/99e6804b-05e1-4a3f-82ff-8a7fbdaae470)

**Comment by Dream-Master** [comment]
> > Project red pipes are now using only lv components. I work on them too
> 
> This is also complete pain and unviable if somebody wish to use other mods from EnderIO (this does the round-robin) ![image](https://private-user-images.githubusercontent.com/13508453/329694237-99e6804b-05e1-4a3f-82ff-8a7fbdaae470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzMyMzEsIm5iZiI6MTcxNTM3MjkzMSwicGF0aCI6Ii8xMzUwODQ1My8zMjk2OTQyMzctOTllNjgwNGItMDVlMS00YTNmLTgyZmYtOGE3ZmJkYWFlNDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDIwMjg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNTZiN2ZiMTg3NDMwMDliOGRhMDA3MmE4NjlhNmUzMzdhZWZlM2UxZDg3MDdmMjEyOTQyNWViM2ExNzAwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mSERCGKIqLk2hIV4nUOccFgOTy1e98tyoSVN5QReqBo)

yea will be reworked as well. But first LP

**Comment by dgealow** [comment]
Some ProjectRed chips currently require MV circuits, but this honestly looks like a mistake--the chips that you'll need a lot of (Item Responder, Item Extractor) take MV circuits, but some of the more niche ones (broadcaster, stockkeeper, crafting) only require an LV circuit. Would make a lot more sense if all only required LV; would put them in the same "tier" as each other and the equivalent LP component (ItemSink module)

**Comment by LazyFleshWasTaken** [comment]
we're on the nightly version with the rebalance merged, and its fine.

**Comment by dgealow** [comment]
Ah yeah, I'm on stable.

**Comment by Dream-Master** [comment]
Lp will be after the rework mostly lv available

**Comment by imTheSupremeOne** [comment]
> > > Project red pipes are now using only lv components. I work on them too
> > 
> > 
> > This is also complete pain and unviable if somebody wish to use other mods from EnderIO (this does the round-robin) ![image](https://private-user-images.githubusercontent.com/13508453/329694237-99e6804b-05e1-4a3f-82ff-8a7fbdaae470.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzNzMyMzEsIm5iZiI6MTcxNTM3MjkzMSwicGF0aCI6Ii8xMzUwODQ1My8zMjk2OTQyMzctOTllNjgwNGItMDVlMS00YTNmLTgyZmYtOGE3ZmJkYWFlNDcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDIwMjg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjNTZiN2ZiMTg3NDMwMDliOGRhMDA3MmE4NjlhNmUzMzdhZWZlM2UxZDg3MDdmMjEyOTQyNWViM2ExNzAwNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mSERCGKIqLk2hIV4nUOccFgOTy1e98tyoSVN5QReqBo)
> 
> yea will be reworked as well. But first LP

Could you also look on this ?
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13508453/80c5b14d-84a0-4dfb-abfa-a47e1d5cb227)

This was a hit in a balls because everything else is LV and easy : the blocks(Workbench & Printer), the Chip. 

Epoxy board in blueprint is the only expensive thing that I absolutely missed; and it feels bad when something is gated by a single item that is not very clear. Epoxy is far too complex, as it's actually become needed only in EV...

I'd say make it require a regular plastic, polyethylene board, or even lower... Usually the further you progress the less janky your machines and setups are and you don't need such fine controls...

Mb chip can be changed from LV to MV to encourage usage of regular gates; because constructing anything through Integrated Circuit is always cheaper.

**Comment by chochem** [comment]
resolved in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/904 and related PRs
