### ISSUE TITLE
Allow Charging input bus to be used in TGS

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#15960]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.6 beta 3

### Your Proposal

Title. The TGS should be able to accept the charging input bus. It'd be perfect for it, since it uses the charge on tools that always stay in a bus.

### Your Goal

Easier TGS automation through a bus _specifically designed_ to act like it does. And is older than the TGS itself.

### Your Vision

Tools won't be ejected into an ME bus behind a queeu of millions of logs. Thye will instead simply disintegrate once charge runs out.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
sounds like some abandoned gt++ block. Does it work for anything?

**Comment by Glease** [comment]
That bus really isn't what you think it is. It's charging **battery** bus for Power Substation, not a generic input bus that can somehow (but how?!) charge items in it.

It's probably a good idea to add what you said tho

**Comment by LazyFleshWasTaken** [comment]
its being worked on here https://github.com/GTNewHorizons/GT5-Unofficial/pull/3225 actually
