### ISSUE TITLE
Industrial centrifuge texture bug

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#15963]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Any hatches/buses in industrial centrifuge on front side will accept rotor texture.

### The Reality

Any hatches/buses in industrial centrifuge on front side do not accept rotor texture.
Some people said it's a feature, but as for me, this is weird feature.
![2024-04-12_11 48 41](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18097458/77cd90a7-8d36-493c-8721-d514b12cf84a)

### Your Proposal

Fix centrifuge rotor texture.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
It should probably be fixed for hatches that do not face the front of your structure (as in your picture).

**Comment by BlueHero233** [comment]
I couldnt fix this because the turbine textures are “pre baked”
If the hatch isnt facing the same front face of the centrifuge it wont render properly
I believe this could be fixed if the centrifuge controller used the same method glease implemented for the large turbines

**Comment by BlueHero233** [comment]
![2024-11-30_15 52 21](https://github.com/user-attachments/assets/179d7253-4b33-4f3b-ab5c-bfe15ae69155)
