### ISSUE TITLE
AALs crashing

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#15962]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.6.0 Beta 2/3

### Your Server

Self-Hosted Server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

The AALs should work as intended but they got stuck without a reason

My setup is:
P2P Dual Interface -> Dual Interface (with blocking mode obviously cause universal AALs)
Then 20 subnets (16 one per item slot + 4 for 4 different fluids max) and it still got this crash saying this:
"Failed to extract expected amount of fluids from stocking hatch. This can be caused by attaching multiple storage fluid buses to the same tank"
This shouldn't be a thing and I thought it was because of batch mode cause another person (@Amarozo) got this problem too in beta 3 with batch mode and without it but I'm on beta 2 without batchmode and it also happened so it's not fixed in beta 3

### The Reality

They didn't work as intended with stocking hatch
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/133218866/d8531b30-438d-4d2b-aee0-9f5fafb76c01)

### Your Proposal

Let the AALs work as they did before with stocking hatch

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Amarozo** [comment]
I can confirm this issue happening all the time. It wasn't the case before changes to stocking hatch. 
Keeps happening no matter if stocking hatch mode, auto pull or not.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/96630673/000769df-7f41-49d6-9f12-830ef9593b26)
Additionally, AAL controllers turn invalid if fluids are supplied with stocking hatch, that stopped happening after replacing hatches to regular ones.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/96630673/bafb7f06-0a42-453b-b5f0-aa2f8250c021)
To reproduce, simply let AAL run  some recipes in pipleline and let it run out of fluids.

**Comment by NotAPenguin0** [comment]
Fixed by GTNewHorizons/GigaGramFab#37
