### ISSUE TITLE
Neodymium only rendering one region of chunks, and ice occlusion issues

### ISSUE THREAD

**Issue by MarshTheBacca** [GTNewHorizons/GT-New-Horizons-Modpack#15976]
### Your GTNH Discord Username

marshthebacca

### Your Pack Version

2.5.1

### Your Server

private server and SP

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

I installed Neodymium 0.2.5 (no-mixin), Optifine HD U E7, Archaic Fix 0.7.2 and created a new world. 

Archaic Fix's occlusion was disabled, and threaded chunk loading was enabled and disabled with no effect. Optifine's Adanced OpenGL was disabled and enabled with no effect.

I expected there to be no chunk loading or occlusion issues like so:
![2024-04-14_16 36 46](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/34864792/ef64ce6e-6ba6-42ce-845b-3f04b7f90280)

### The Reality

The spawn area chunks were not loaded, but in the distance, a large strip of chunks did render, although with occlusion issues on an ice river. Chunks outside the strip's edges would not render:
![2024-04-14_16 27 53](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/34864792/449777da-2e81-43a6-9134-dcf4dfc8ed5d)
![2024-04-14_16 27 41](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/34864792/b52b3ccb-21aa-4c34-83c2-2dcfaed85f3f)

### Your Proposal

Identify if the issue is the responsibility of GTNH, Neodymium, Optifine or Archaic Fix
Identify if the issue is due specific combination of configure options
Identify if the issue is due to an incorrect mod configuration on my part
Identify if the issue is due to specific case of my hardware, [here is my laptop](https://www.dell.com/en-uk/shop/laptops/inspiron-14-2-in-1/spd/inspiron-14-7425-2-in-1-laptop)

My laptop has the following specs:
AMD Ryzen 7 5825U with Radeon Graphics  2.00 GHz, 16 threads
16 GB DDR4 3200 MHz RAM
512 GB M.2 2280 PCIe NVMe Gen4 x4, SSD

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
> Neodymium, Optifine

These more aren't supported and Angelica is being worked on to eliminate the need for them
