### ISSUE TITLE
Cannot pull block from me system when using infinity booster card

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#15981]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.6.0 Beta 3

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

The holo projector should be able to pull out of the system but you need a wireless access point nearby, even with infinity booster card

### The Reality

It needs a wireless access point even with infinity booster card

### Your Proposal

If you have a wireless terminal with an infinity booster card you should be able to pull out of the system everywhere and not only near access points

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ogdae** [comment]
Got on this afternoon to try and recreate myself after having a conversation with both Marvin and NotAFrog last night, can confirm issue is present in 2.5.1 also - placing a default Mega Chemical Reactor seemed to work fine (?) without booster cards in the wireless access point, however when I stacked 8 holograms to use T8 glass it was a no go without a wireless access point.

**Comment by Glease** [comment]
the structure compat currently can't understand infinity booster card. it will get implemented at some point, but definitely not until I fully understand how many different types of me wireless terminal we have now

**Comment by Amarozo** [comment]
> the structure compat currently can't understand infinity booster card. it will get implemented at some point, but definitely not before I fully understand how many different types of me wireless terminal we have now

We have 2 that support infinity booster card. Ultimate one (crafted from elementary wireless terminals) and the crafting, laggy one. To check you can look for uses of infinity booster card

**Comment by Glease** [comment]
closed by https://github.com/GTNewHorizons/StructureCompat/pull/5
