### ISSUE TITLE
Make input filter on by default on single block machines.

### ISSUE THREAD

**Issue by RitumsC** [GTNewHorizons/GT-New-Horizons-Modpack#15989]
### Your GTNH Discord Username

e35

### Your Pack Version

2.6.0beta3

### Your Proposal

Make the input filter, the setting that allows machines only to accept items/fluids that are part of the recipe map, enabled by default.

### Your Goal

1. The default behaviour for multis is that the input filter is enabled, so this change would make it consistent with multis.
2. There isn't any widely used logistic reason for single-block machines to accept items that are not part of their recipe map.
3. This input filter feature is not well known and simplifies early automation setups (i.e., solar-grade silicon can easily be made in a 2x2 system with no additional pipes).

### Your Vision

Improved consistency and user experience for players who don't read the Wiki (which should not be a requirement for early logistics).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
No. This was the case before, and it was extremely confusing for a lot of players. Sadly we will not go back to this being enabled by default.

**Comment by Glease** [comment]
just set mSingleBlockInitialFilter_false to true in your config/GregTech/Client.cfg
