### ISSUE TITLE
Crash when right clicking a howler alarm with stainless steel ingots in your hand. (???????)

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#15986]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Was taking out stainless steel ingots from an output chest in my EBF area. Accidentally right clicked a howler arm after. Immediately crashed.

### Crash Report

https://mclo.gs/Arkhpon
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14986832/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by PlayfulPiano** [comment]
Ok looks like I can replicate it for whatever reason. Probably not a good sign then.

**Comment by PlayfulPiano** [comment]
Oh, it's specifically when right clicking a howler alarm with stainless steel ingots in your hand.
?????????????????

**Comment by Caedis** [comment]
@Cleptomania smells NEID metadata related
