### ISSUE TITLE
[Nutrition] Eating food with all five food groups does not increase nutrition values.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#15995]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.6.0-beta-2

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Consume food which contains all five nutrition groups. (For example, Random Taco, Ploughman's Lunch, Deluxe Chicken Curry, etc.)

Gain an improvement in all five food group values, eventually up to 100%.

### The Reality

Instead, the values of all food groups tend to 50%, increasing if they are below, decreasing if they are above; as if using a Healing Axe or a similar item.

I have replicated this in a brand new test world, this is not an issue with some other equipment overriding food values.

The issue does not happen with food which has 4 or fewer different food groups.

### Your Proposal

Correctly increase values of all five nutrition groups when this food is eaten, so that the player is properly rewarded for crafting complex foods and interacting with the mechanic.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
tested and works fine now. was probably fixed at some point.
