### ISSUE TITLE
Endless "cascading worldgen lag" console spam after oom crash

### ISSUE THREAD

**Issue by Wargenflorgen** [GTNewHorizons/GT-New-Horizons-Modpack#15997]
### Your GTNH Discord Username

Wargenflorgen#0402

### Your Pack Version

2.6.0 beta 3

### Your Server

Private MP Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Worldgen lag and associated logs should stop after worldgen stops

### The Reality

Error logs have continued spamming the same line dozens of times per second for 4+ hours, following an oom crash while generating new chunks (in the end hunting chaos guardians). Attached are an image of a couple lines of the log spam, as well as the oom crash that (I think) started the spam. The offending chunk [1774, -625] is constant. Full logs available if needed.
[crash-2024-04-17_17.46.51-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15019801/crash-2024-04-17_17.46.51-server.txt)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127348659/503de7ae-4dfa-483b-861e-301726a7f2bf)

### Your Proposal

Investigate why the log spam continues long after the problem is apparently resolved.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by jurrejelle** [comment]
Happened to me too in 2.6.0-beta-3. After upgrading the server to 2.6.0 stable release, it still continues.

**Comment by elak93** [comment]
Also receiving endless spam on a 2.6 server 
[console going crazy.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15197115/console.going.crazy.txt)
