### ISSUE TITLE
Launcher Crash

### ISSUE THREAD

**Issue by SkyBois** [GTNewHorizons/GT-New-Horizons-Modpack#15992]
### Your Pack Version

2.1.5

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

I attempted to start GTNH multiple times, and the launcher keeps crashing at either 83% or 99%, both at the "Post Initialization: Loading Gregtech" text
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/68835756/897b8369-b061-4d9e-8818-f3bd358a5db2)

### Crash Report

https://paste.ee/p/L8f8d

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by LazyFleshWasTaken** [comment]
Are you on curse forge?

Also, 2.1.5 is a very, very old version. I'd try a newer one.

**Comment by SkyBois** [comment]
I'm using MultiMC; I'll try a newer version and get back to you, I was under the impression that it was the newest one 🤦

**Comment by SkyBois** [comment]
I just opened 2.5.0, it works fine :)
