### ISSUE TITLE
Blocks on Space Stations are invisible

### ISSUE THREAD

**Issue by bobolpwnz** [GTNewHorizons/GT-New-Horizons-Modpack#15998]
### Your GTNH Discord Username

bobolpwnz

### Your Pack Version

2.6.0-beta3

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Go to a space station and see the structure and blocks around me.

### The Reality

All blocks are invisible, but WAILA confirms they are there. See the images:
https://imgur.com/a/fsMUquw 

I've tried playing with graphic settings but without any progress.

### Your Proposal

Make the blocks visible.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
duplicate of https://github.com/GTNewHorizons/Angelica/issues/379
