### ISSUE TITLE
Add a more efficient Certus quartz rod recipe.

### ISSUE THREAD

**Issue by Cyber1551** [GTNewHorizons/GT-New-Horizons-Modpack#16000]
### Your GTNH Discord Username

cyber1551

### Your Pack Version

2.6.0 beta-2

### Your Proposal

My proposed change is to add a rod extruder recipe at HV+ to allow for 1 crystal -> 2 rods.

If you don't want it to be simple for whatever reason, you can instead make a 1:1 long-rod extruder recipe, so they still have to use the cutting machine to use it for AE2.

Another idea to keep complexity (if that is the goal of the lathe recipe) is to make it 1 _pure_ crystal -> 2 rods. 

Since a cheaper recipe already exists via charged certus quartz's 1 crystal -> 1 rod recipe. We could also keep that pattern by adding a fluix recipe. 

- Certus: 2:1
- Charged Certus: 1:1
- Fluix (New): 1:2 

Although, adding fluix breaks the **Quartz** naming in "Quartz Fiber" 

### Your Goal

Currently, the only way to make Certus quartz rods is with the lathe at a 1 crystal -> 1 rod ratio.  
Also, it gives 2 small dusts which needs to be handled which is annoying. 

Considering you need 2 rods for a single quartz fiber, this seems like an overly grindy recipe that doesn't add any meaningful complexity. 

### Your Vision

Due to the large scale AE2 networks needed in this pack, and the limited use cases for quartz rods (only used for AE2, nothing that would break balance or skip progression), I feel like this would improve the pack significantly especially in the early phases of AE2.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
Two comments, not to detract from the suggestion, but as existing alternatives:

The AE Crystal Growth Chamber can grow pure crystals with guaranteed chance, practically unlimited (36x64) parallels, and no extra cost other than RF power.

Quartz Fibers can also be made from Charged Certus rods, which are more efficient than regular Certus. You trade extra materials needed to charge the quartz for fewer rods needed total (and thus less lathe time).

**Comment by Cyber1551** [comment]
> Two comments, not to detract from the suggestion, but as existing alternatives:
> 
> The AE Crystal Growth Chamber can grow pure crystals with guaranteed chance, practically unlimited (36x64) parallels, and no extra cost other than RF power.
> 
> Quartz Fibers can also be made from Charged Certus rods, which are more efficient than regular Certus. You trade extra materials needed to charge the quartz for fewer rods needed total (and thus less lathe time).

I was not aware of the Growth Chamber. For some reason, I assumed that was a 1.12.2 only feature. My bad. 
I edited the original to fix that mistake. Thank you.

As for the charged rods, that is a cheaper way than using regular crystals, however, it still gives 2 small dusts. 
Maybe a final recipe can be using fluix crystals for a 1:2 ratio following the pattern while removing the small dusts. 

- Certus: 2:1
- Charged Certus: 1:1
- Fluix: 1:2
