### ISSUE TITLE
Stairs have wrong ratio in architect's sawbench

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#16008]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.6.0 Beta 3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Stairs in the architect's sawbench are supposed to be made in a ratio of 3 to 4 (according to the ratio stated in the sawbench UI).

### The Reality

Stairs instead have a ratio of 3 to 2.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/e6851afb-b0fa-4f5b-90dc-dbf4187652b0)

### Your Proposal

Correct the ratio.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
I know exactly what you did wrong, you right clicked
it turns 3 into 4 but since u right clicked it picked up just 2 and left 2 on the slot, it still only consumed 3 blocks to make 4 stairs
