### ISSUE TITLE
Drone Centre Memory Leak

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#16005]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.6.0-beta2

### Your Server

Private Dedicated

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Drone DownLinks would properly switch from 1 Drone Centre to another when the active centre is destroyed.

### The Reality

1. Construct a Drone Centre and insert a Tier 3 Drone
2. Place several Drone Uplink Hatches on multiblocks and confirm they link to the Drone Centre
3. Build a 2nd Drone Centre within range of the 1st Drone Centre (< 512 blocks) and insert a Tier 3 Drone
4. Place several new Drone Uplink Hatches on multiblocks until they start linking to the 2nd Drone Centre
5. Using a Vajra, destroy the 2nd Drone Centre in its entirety
7. Go to the 1st Drone Centre and observe that its connection count in WAILA is rising steadily and quickly goes above the actual number of connected machines
8. Attempting to view the connected machines may cause you to be disconnected after a certain point, presumably due to the list becoming too long

### Your Proposal

There's a bug of some kind, good luck!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by norbby42** [comment]
I just noticed that GT_MetaTimeEntity_Hatch_DroneDownLink#tryFindConnection does not break on registering with the first found drone centre.  If there are 5 centres in range, it will establish a connection with all 5 (but not retain 1-4 locally).

https://github.com/GTNewHorizons/GT5-Unofficial/blob/b9aaf5b191bd2b00cd3ca8079d962178dc1d2985/src/main/java/gregtech/common/tileentities/machines/multi/drone/GT_MetaTileEntity_Hatch_DroneDownLink.java#L193

**Comment by HoleFish** [comment]
@RealSilverMoon
