### ISSUE TITLE
Switching Batch Mode does not update UI values correctly.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#16003]
### Your GTNH Discord Username

Abdiel_Kavash

### Your Pack Version

2.6.0-beta-2

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

Turn on or off batch mode on a multiblock via button in the GUI.

Expect the output amounts to update correctly.

### The Reality

Before:

![](https://i.imgur.com/Nf7FF3z.png)

After:

![](https://i.imgur.com/2MxPHGQ.png)

You can see that the processing time updates correctly, but the amount of items is still reported per recipe, not per batch. This results in the items per second being wrong.

Closing and reopening the GUI fixes the issue, and new values are now reported correctly.

This is purely an UI problem, actual amount of items produced is correct.

### Your Proposal

Batch mode setting needs to be properly synced to the client when the button is pressed, not only when the UI is opened.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3561
