### ISSUE TITLE
Stop "Shut down due to incomplete structure" from turning off Safe Mode machine controller covers.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#16002]
### Your GTNH Discord Username

Abdiel Kavash

### Your Pack Version

2.6.0-beta-2

### Your Proposal

A machine controller cover in safe mode is intended to shut down the machine permanently in the event of a power failure, in order to prevent continued item loss. However, as of 2.6 beta, the safe mode gets also triggered by the "incomplete structure" error, and even while the machine is not currently processing any items.

This means that when a machine is equipped with such a cover, even when it is not processing any items, replacing any casings/hatches triggers the safe mode switch, and the cover needs to be manually reset. This makes upgrading or modifying multiblocks more arduous than it was before.

Errors encountered by the machine while it is not processing any recipe should not trigger safe mode like this.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by HoleFish** [comment]
Actually currently machine will be shut down in case of power loss. So the cover may be no longer useful if you use it like that
