### ISSUE TITLE
client crashes before main menu

### ISSUE THREAD

**Issue by swr9** [GTNewHorizons/GT-New-Horizons-Modpack#16019]
### Your GTNH Discord Username

ppgun

### Your Pack Version

2.6.0 Beta 3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Client crashes at Post Initialization: Loading Gregtech 83%. To update the game I just cloned my instance then copied the new config and mods files I downloaded from "https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/releases/tag/2.6.0-beta-3".

### Crash Report

https://mclo.gs/K2QUySb

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment]
You have all the mods of 2.5.1 but the configs for 2.6.0.
Download the beta from here instead http://downloads.gtnewhorizons.com/Multi_mc_downloads/betas/
