### ISSUE TITLE
Crash when opening LV lootbag

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#16018]
### Your GTNH Discord Username

britishcynic

### Your Pack Version

2.6.0-beta3 with Angelica-a38 and HoloGlasses 2.4.4

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

LV Lootbag should be opened without crashing the client

### The Reality

Opening an LV lootbag caused a client crash, https://pastebin.com/enexcMAp

### Your Proposal

Resolve the error so that the crash does not occur again

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
Does this happen with any loot bag or LV specifically?

**Comment by BritishCynic** [comment]
This appears to be a one-off error, it hasn't happened with any other lootbag since, be it LV or something else. It would have been easier to diagnose if there was a text output for what the lootbag dropped.

**Comment by NotAPenguin0** [comment]
I assume there's one item in its loot table that causes it, will be annoying to track down but not impossible.

**Comment by chochem** [comment]
cant reproduce it on my end either. might not be related to the bags but purely something in inventory tweaks
