### ISSUE TITLE
Changes to the recipes of the Large HP Steam Turbine and XL HP Steam Turbine

### ISSUE THREAD

**Issue by EdenExecutive** [GTNewHorizons/GT-New-Horizons-Modpack#16012]
### Your GTNH Discord Username

Eden Executive

### Your Pack Version

2.5.1

### Your Proposal

Currently the Large HP Steam turbine is gated behind IV and the XL HP Steam Turbine is gated behind LuV though both materials used in their recipe and the tier of the tier of the assembler recipe. My proposal is to bring these to EV and IV respectively through the following changes:

Large HP Steam Turbine:
- Replace LuV circuit with EV circuit
- Replace Tungstensteel components with Titanium components
- Replace IV machine hull with EV machine hull

XL HP Steam Turbine:
- Make the Assembler recipe IV tier
- Replace Zeron-100 components with components of a GT++ alloy available in IV or below (e.g Hastelloy-X)

### Your Goal

Power generation through steam isn't particularly strong and through gating the multis that process high pressure steam at IV and LuV these options become even less viable/attractive to use in a playthrough. This would make these turbines accessible at the point where power requirements rapidly increase as well as multis that produce HP steam become available.

### Your Vision

By making these turbines available earlier they can better compete with the other power options when it comes to selecting a main power source in EV and IV, making more methods of power generation viable and possibly leading to more varied power plants in EV and IV

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EdenExecutive** [comment]
comment to get this back in there

**Comment by StaffiX** [comment]
This is done by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/867 and https://github.com/GTNewHorizons/GT5-Unofficial/pull/2806
