### ISSUE TITLE
Recipes which take more than a stack of input in consume much less than intended

### ISSUE THREAD

**Issue by FourIsTheNumber** [GTNewHorizons/GT-New-Horizons-Modpack#16028]
### Your GTNH Discord Username

fouristhenumber

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Found when crafting black steel in singleblock mixer with the circuit 16 recipe attached. Expect the recipe to consume 80 black steel as per the recipe.

![2024-04-20_21 42 26](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/33456283/f4c9f1cc-3834-45e0-8a46-6c2f4b7ae2b7)

### The Reality

Recipes in at least mixer and assembling machine which require more than a stack of some input, will begin recipe as soon as they have a single stack. If they have the full amount that the recipe requires at time of recipe check, they will consume all of it as intended.

For example, the blue steel recipe will start if you insert the other ingredients and finally 64 black steel, even though it does not have the full 80. If you instead input all 80 black steel first and then the other ingredients, it will correctly consume 80.

I have verified that this happens in both singleblock AND multiblock machines, and verified it with at least the following recipes:

-Blue Steel Dust skip recipe (Mixer)
-Cerium-doped Lutetium Aluminium Oxygen Blend Dust (Mixer)
-Iridium Neutron Reflector circuit 2 recipes (Assembler)

Notably, iridium neutron reflectors take over a stack of tin plates and over a stack of graphite, and it will start with just a stack of each.

### Your Proposal

Correct recipe checking!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2516
