### ISSUE TITLE
Tinkers Tools cannot be renamed after initial craft

### ISSUE THREAD

**Issue by imTheSupremeOne** [GTNewHorizons/GT-New-Horizons-Modpack#16035]
### Your GTNH Discord Username

imthesupremeone

### Your Pack Version

2.5.1

### Your Server

Private

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Tool should be renamed after going through Tool Forge :
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13508453/53ec2929-d421-4ca7-9ab8-a67fb8d52378)

### The Reality

Nothing happens.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13508453/18be2716-d271-4520-b1f6-5eff0adac8ce)

As you can see the font is already italic and it's because I've tried battling it before and failed but was too lazy to report it here. Even if tool at 100% durability; I also tried mb to enforce it by doing repair + rename at the same time but it stays with the name it was crafted.

If tool wasn't given any custom name at first assembly it can not be renamed either : 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13508453/ce5c33a4-9517-4040-899b-739bdcc9e2dd)

Renaming tool with anvil isn't perfect too. It changes it's font to italic and technically the Tinker Name still stays on the tool : 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13508453/17a87147-d86d-45d3-b124-36ac35550094)

### Your Proposal

Fix Tool Forge Renaming.

Prob look at anvil renaming too as it's clearly isn't fully supported to work at Tinker's tools.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by RealSilverMoon** [comment]
[    public static boolean canRename(NBTTagCompound tags, ItemStack tool) {](https://github.com/GTNewHorizons/TinkersConstruct/blob/ee32be8a0d1ef5ed7c31fdb1947dc6931a923905/src/main/java/tconstruct/tools/logic/ToolStationLogic.java#L186)
This means a tool can **only** be renamed once. Seems that this logic was decided at the very beginning. I would say it's time to change that—give renaming permissions to players doesn't hurt anything.

**Comment by chochem** [comment]
you should be able to rename it again with a nametag, that is the intention anyway.

**Comment by chochem** [comment]
I tested it to be sure, and yea works just fine

![image](https://github.com/user-attachments/assets/8c7807a4-eb59-4028-b40a-613fa62a92ca)
![image](https://github.com/user-attachments/assets/83ec036b-2be6-457f-8854-42b6de8d65d2)
![image](https://github.com/user-attachments/assets/98c2897e-3723-40bc-b9e5-c618f0ee445f)
