### ISSUE TITLE
Volcanus does not get coil temperature bonus from energy hatch

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#16031]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Volcanus as an advanced EBF will have all its bonuses.

### The Reality

Volcanus does not get coil temperature bonus from energy hatch (+100K from every tier starting at HV):
![2024-04-21_13 35 51](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18097458/b1566187-f513-41ac-8295-d5e6d0cb4a5c)
![2024-04-21_13 35 57](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18097458/13a42c06-53bf-4bce-9d0e-0107c40a3f57)

### Your Proposal

Make Volcanus get coil temperature bonus from energy hatch.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
thats not a bug. its even documented in the questbook.

**Comment by FireWarrior2** [comment]
> thats not a bug. its even documented in the questbook.

Where? Can't find..
Quest about volcanus looks like this:
![2024-04-21_14 03 40](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18097458/a5110675-8338-4017-875a-60f31458391d)

**Comment by chochem** [comment]
looks like twice: the place where the bonus is first explained and the place where it comes up the most often

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/587412cf-1475-40d9-8e14-ca2b05475caa)


![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/40274384/9db087e2-8a30-4206-86f1-cbaaaa66e120)
