### ISSUE TITLE
Optifine causes Gregtech blocks with "mobs cannot spawn on that block" tooltip, to actually be able to spawn mobs

### ISSUE THREAD

**Issue by luc666** [GTNewHorizons/GT-New-Horizons-Modpack#16047]
### Your GTNH Discord Username

lucisl.

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

make a base using gregtech blocks only, with "mobs cannot spawn on that block" tooltip, to have a nice mob free base

### The Reality

mobs spawns at night or under roof where there is not enough light on gregtech blocks with "mobs cannot spawn on that block" tooltip . Using F7 from More Overlays mod, shows yellow and red Xs on those blocks

### Your Proposal

i searched online, found one old thread about that issue. https://forum.mechaenetia.com/t/enemy-mob-spawning/1530
tested it by myself and it seems to be true, optifine for some reason causes mobs to spawn on gregtech blocks with "mobs cannot spawn on that block" tooltip.
tested that on test world, and here are screenshots.
![2024-04-24_09 00 19](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12979725/629332fe-0df8-4689-a11a-d767e4f7baf1)
![2024-04-24_09 09 25](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12979725/840404d2-7e9c-4aa7-acdf-26f263aea6e2)

you guys dont have to fix that, just please add that info to tooltip so people will know. i have enough explosions in my base even without random mobs spawning :D 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
optifine is not supported and not included in GTNH.

Also 2.6.0 has Angelica which a superior, open-source, supported&included replacement (upto shaders for now, that comes later).
