### ISSUE TITLE
Steam Squashers have 4x energy efficiency than intended (?)

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#16040]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Assume the Compressed Air Cell Recipe.
2EU/t recipe for 15s
Steam Squasher does 8x parallel, so 2EU/t -> 16EU/t
Steam Ratios are 2L:1EU, so this means 32L/t usage
Then include the 50% efficiency of Steam Machines, this would double *again* to 64L/t usage. Or 1280L/s.

LV Fluid Heaters generate 960L/1.5s of steam, i.e. 640L/s.
Therefore, you would need 2 LV Fluid Heaters to keep up with a single Steam Squasher.

### The Reality

In game I set up 2 steam squashers in a wallshared setup with a single steam hatch, powered by a single LV fluid heater. Assuming the above ratios, this should mean I would be unable to keep uptake of even a single squasher. Instead, **both** squashers are able to run consistently with 0 fluid loss overtime from the single LV fluid heater. i.e., 4x more efficient than ratios would intend.
This probably skips both the 50% efficiency AND the 2:1 steam L : EU ratio, or is otherwise just weird.

### Your Proposal

Considering that a steam squasher is supposed to be equivalent to an HV compressor in terms of parallel, or an MV compressor in terms of parallel & efficiency, this should probably either get its ratios fixed to their intended values, or alternatively give it a smaller discount (2x over 4x?) so the sudden spike in steam cost isn't as harsh to newer players. Or make fluid heaters worse idk

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PlayfulPiano** [comment]
I will say though that giving steam multis some discount bonus would be cool, although I guess it would make more sense to do that with the grinder than the squasher (as you'd be using HV macerators for byproducts but the squasher would just be objectively better than any EU based compressor till like EV or LPF).

**Comment by PlayfulPiano** [comment]
ok just tested the macerating of an iron ingot in an LV macerator, a steam grinder, and a HP macerator:
all three have 2.8s durations
HP macerator costs "about 8eu/t" on tooltip
both LV macerator and steam grinder costs 4eu/t on tooltip

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3158887/9a47c94c-a9af-4839-b5d3-5ce952c817f0)
also, as per the gtnh, there seems to be an outdated bonus discount documented here that doesn't seem to match the above functionality?

so maybe there was some past discount that isn't easily viewable now? or something weird across versions?

As per wiki history, the discount mentioned was posted back in 2022 when the page was first made, so idk

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3158887/4c473acd-7824-43de-aa24-82fa6f240414)

**Comment by Glease** [comment]
large steam multi does not have the steam:energy 2:1 ratio. it instead treats it as 1:1. It also doesn't have the 50% effi of single block bronze machines. 

I can't say if this is intended though.

**Comment by chochem** [comment]
there is nothing in the code history suggesting any intentional discounts. but in the end we can just decide on one.

**Comment by chochem** [comment]
dream wants the 4x bonus to stay and just be documented properly

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GTplusplus/pull/875
