### ISSUE TITLE
Breaking EIO Item Conduits with ANGELICA is causing a crash

### ISSUE THREAD

**Issue by Fatrude** [GTNewHorizons/GT-New-Horizons-Modpack#16056]
### Your GTNH Discord Username

_Lirue

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

when I break an EIO conduit the screen turns light blue and crashes. with my hands, pickaxe or wrenches.
I only have Angelica, and updated its 3 dependancies: CodeChickenCore, GTNHLib and hodgepodge. I removed Aromabackups and Fastcraft.

### Crash Report

https://mclo.gs/NXQHfWK

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
Fixed in updated versions of EIO.
