### ISSUE TITLE
Cant Bookmark fluid packets anymore (NEI)

### ISSUE THREAD

**Issue by Persus1** [GTNewHorizons/GT-New-Horizons-Modpack#16069]
### Your GTNH Discord Username

persus

### Your Pack Version

2.6.0 Beta 3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

When you bookmark a fluid packet in 2.5.1 and prior you get a ae2fc:fluid_packet bookmarked
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/130587498/fb3725f3-9122-4de2-a8fa-2908e4be79ff)

### The Reality

Now the bookmarked fluid packet always turns into a gregtech:gt.GregTech_FluidDisplay item
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/130587498/1206487d-6ff1-4dae-be6a-ae67f5021f5e)
Thats quite annoying because you can no longer bookmark fluid packets to use them as filters for certain setups

### Your Proposal

Revert this change

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
can't repro on 2.6.0:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12850933/1bbf2014-f575-4722-9e3d-b0360e65e8fd)

**Comment by Persus1** [comment]
> can't repro on 2.6.0: ![image](https://private-user-images.githubusercontent.com/12850933/326303946-1bbf2014-f575-4722-9e3d-b0360e65e8fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDM2NjcsIm5iZiI6MTcxNDQwMzM2NywicGF0aCI6Ii8xMjg1MDkzMy8zMjYzMDM5NDYtMWJiZjIwMTQtZjU3NS00NzIyLTllM2QtYjAzNjBlNjVlOGZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE1MDkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjRlZTRkMWVmNWUwNDljNWU3YjBlOGUzYWExZWZkODBkOTljZmI1NzM2Zjk4ZjIyNDc3MmZkMjgwYTY3MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4A8LTwiFZf1po-UsIi7K2a3aTmKoBiBImrrribMXS5Q)

I admit the title is not exactly what i meant but i hope the new example shows exactly what i meant:

2.5.1:
![2 5 1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/130587498/86a24cd0-edef-4e9c-8031-f704eafc58da)

2.6.0:
![2 6 0](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/130587498/b553edf5-74a7-4a7a-8fef-80c5b3c2c04c)

As you can see in 2.5.1 the Fluid packet is a perfect match in the bookmark as the item in the inventory

In 2.6.0 on the other hand the fluid packet just defaults into the fluid variant which is no longer a packet and also lost the fluid amount

Its like you try to bookmark a bucket of water and just end up with water in you bookmark  <= (not actually the case just an example!)

**Comment by slprime** [comment]
Can you give an example where this behavior interferes?

**Comment by Persus1** [comment]
I mainly used this feature for 2 things.

- Bookmark fluid packets to easily partition me export busses/storage busses for some setups (Eye of harmony automation or sending packets into subnets)
- bookmark a recipe via ctrl+shift+a and adjust the recipe size to some custom numbers like x138 and insert the packets back into the pattern and encode them(The ME system can just easily do multiples of 2 or you manually have to change every items/fluids amount). Mainly used for advanced assembly line recipes

The first thing can now only be done when you carry a packet with you at all times. The second use just isnt possible anymore because you can only encode patterns with fluid packets which you cant bookmark anymore since they turn to the unusable non packet fluid variant.

I know this small change is not a big of a deal if there was a good reason for it and there isnt really a urgent reason to fix it. But arent bookmarks supposed to save an exact copy of the item you just bookmarked? Seems strange that there are now exceptions to this rule.
