### ISSUE TITLE
Angelica crash; render-related; AE2-related apparently; same type of crash as previous Ender IO issues

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#16077]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

I opened the modpack on the 2.6.0 release version, and opened my save that I have ported forward from previous versions. After a short time simply existing in the world, and interacting with very little, the game screen turned blue and then crashed to main menu.

This is precisely the same set of circumstances as those that resulted in previous issues (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15798) I have experienced with Angelica in the various 2.6.0 beta versions, except that the crash-to-main-menu screen instead warned about an interaction with AE2 and did not mention Ender IO this time. Since my previous attempts to play the modpack with Angelica installed (all of which resulted in the same crash, forcing the removal of Angelica), I have begun work on basic AE2 infrastructure. Some Ender IO conduits have been removed but many still exist in the save.

### Crash Report

[crash-2024-04-29_00.25.27-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15144194/crash-2024-04-29_00.25.27-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
duplicate issue of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16077

**Comment by VectorKappa** [comment]
> duplicate issue of #16077

huh

**Comment by Caedis** [comment]
whoops, meant https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16075
