### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by ButterChild** [GTNewHorizons/GT-New-Horizons-Modpack#16076]
### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

When I tried to enter the world

### Crash Report

[crash-2024-04-29_08.28.41-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15144179/crash-2024-04-29_08.28.41-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
Can you attach the client-fml log?

**Comment by ButterChild** [comment]
[2024-04-29-4.log.gz](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15144209/2024-04-29-4.log.gz)

**Comment by ButterChild** [comment]
[Uploading fml-client-latest.log…]()

**Comment by Caedis** [comment]
Can you try uploading that again? Think you submitted the comment too early

**Comment by ButterChild** [comment]
sry, Is this correct?
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15144238/fml-client-latest.log)

**Comment by Caedis** [comment]
Yep, thanks!

**Comment by Caedis** [comment]
Same underlying issue as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16075
