### ISSUE TITLE
Shit click bugging 

### ISSUE THREAD

**Issue by jaydenx4** [GTNewHorizons/GT-New-Horizons-Modpack#16073]
### Your GTNH Discord Username

jaydenx4

### Your Pack Version

2

### Your Server

gtnh server

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

when you shift click something than get another stack of that and shift click on that it bugs it out and makes the splitting between it messed up

### The Reality

it messed up me crafting the bronze for steam pipes

### Your Proposal

fix it please and thank you. and some other isuse that fallow with it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
could you elaborate? 'bugs out' isnt very specific
