### ISSUE TITLE
Crosshair Visual Bug

### ISSUE THREAD

**Issue by BobGoldham** [GTNewHorizons/GT-New-Horizons-Modpack#16074]
### Your GTNH Discord Username

@bobgoldham

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I use a resourcepack (Sphax, specifically) that modifies the in-game crosshair.
When loading the relevant pack on 2.5.1, no issues occured.

### The Reality

On 2.6, a white square, slightly larger than the crosshair itself, starts flickering in and out of existence behind the crosshair rapidly (several times a second).
This effect persists in the pause menu, but stops when entering the chat window.

### Your Proposal

For whatever rendering bug this is (probably Angelica?) to be fixed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BobGoldham** [comment]
Upon further investigation, a screen capture of the affected area does NOT show the flicker.

**Comment by Caedis** [comment]
thats the hug caching
