### ISSUE TITLE
Can't launch the thermos UNOFFICIAL server

### ISSUE THREAD

**Issue by XeonKA** [GTNewHorizons/GT-New-Horizons-Modpack#16087]
### Your GTNH Discord Username

XeonKA#9433

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Thermos

### Your Actions

1.Unzip the server pack.
2.Unzip Thermos-1.7.10-1614.UNOFFICIAL bundle.
3.set the startserver.bat 
"C:\Program Files\Java\jdk-1.8\bin\java.exe" -d64 -server -Dlog4j2.formatMsgNoLookups=true -Djdk.tls.rejectClientInitiatedRenegotiation=true -XX:MaxGCPauseMillis=50  -XX:+UseG1GC  -XX:+UseStringDeduplication -Dfml.queryResult=confirm -Xms13G -Xmx13G -XX:+AggressiveOpts -XX:hashCode=5  -jar Thermos-1.7.10-1614.UNOFFICIAL-server.jar nogui

### Crash Report

https://pastebin.ubuntu.com/p/YtH2qtQRk5/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
remove archaic fix from your mods folder. Also thermos is unsupported, use it at your own risk.
