### ISSUE TITLE
Ineffable Glass connected texture displays incorrectly.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#16080]
### Your GTNH Discord Username

Abdiel Kavash

### Your Pack Version

2.6.0 release

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

A layer of Ineffable Glass (Extra Utilities) to display with connected textures.

### The Reality

![](https://i.imgur.com/WB6BaIL.png)

It seems that connected textures are applied to the front side (closest to the player), but not to the other sides of the glass.

Issue seems to only affect Ineffable Glass, other glass is fine (including Dark Glass from ExU too).

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Nikolay-Sitnikov** [comment]
Can confirm this issue exists and is quite annoying. (On a client without any mod or config changes.)

**Comment by Cleptomania** [comment]
Will be fixed in Angelica beta22
