### ISSUE TITLE
All entity flickering

### ISSUE THREAD

**Issue by Perfection7** [GTNewHorizons/GT-New-Horizons-Modpack#16084]
### Your GTNH Discord Username

Perfection7

### Your Pack Version

2.6.0 (Stable)

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

I updated the pack to the new version and as you can see in the video, all the entities (including chests) have this strange effect

### The Reality

I updated the pack to the new version and as you can see in the video, all the entities (including chests) have this strange effect
Idk if can help but this is my pc:
cpu ryzen 7 2700x
gpu 1080 ti
ram 16Gb ddr4 3200mhz

https://youtu.be/10Di5Go7RLQ

### Your Proposal

Fix flickering

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Perfection7** [comment]
I want to add even this, block need 1 sec to load and unload if they're break

https://youtu.be/Pzsl2qx2yf4

**Comment by jusvit** [comment]
Angelica related - https://github.com/GTNewHorizons/Angelica/issues/421

**Comment by Caedis** [comment]
Closing due to duplicate issue
