### ISSUE TITLE
Rotating Elevator doesn't work inside cleanroom

### ISSUE THREAD

**Issue by Miklebe** [GTNewHorizons/GT-New-Horizons-Modpack#16083]
### Your GTNH Discord Username

Mike_Be

### Your Pack Version

2.6.0

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Using Rotating Elevator inside cleanroom in place of plascrete blocks in the floor.

### The Reality

Rotating Elevator breaks the clearoom. Other movement options (normal elevator and travel anchor) still work.

### Your Proposal

Pls fix :violinhampter:

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
I can't reproduce this in a fresh install of 2.6.0. Cleanroom forms and works correctly. [image](https://i.imgur.com/T25UqBM.png)

Are you sure you didn't modify your config? Or that you didn't accidentally put another rotating elevator somewhere else in the structure (only one is allowed)?

**Comment by Miklebe** [comment]
Yes, i am certain that there was no other rotating elevators, only travel anchor and rotating elevator were present. But i am not sure about config since it was on a server. I asked my friend about it and am waiting for his reply.

**Comment by Miklebe** [comment]
Surely, my mistake, don't know how my friend ported the config files, but this is what it looked like 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/48237322/768d52f3-c245-4b4b-802e-f3ea89f8d2bd)
No idea how or where he took this scuffed config to port, but yeah, was a user problem, both client and server config in downloads seem to be correct one.
