### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by elak93** [GTNewHorizons/GT-New-Horizons-Modpack#16090]
### Your GTNH Discord Username

elak93#1348

### Your Pack Version

2.6.0

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Actions

Unable to launch server to completion on crucible or java 8, hope your going to tell me I've done something stupid but keep getting stuck with a space team error that lyft is aware of from discord chat. I have copied what I believe to be a single attempt to start the server without crucible into a txt below as it is not recording logs or crash logs for this. Any help greatly appreciated unfortunately after 4 hours of this I have to sleep and will attempt to bash my head further against it tomorrow.

### Crash Report

[Console output.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15148556/Console.output.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
`FAILED TO LOAD: spaceTeams.json[21:29:48] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.io.FileNotFoundException: ./World/spaceTeams.json (No such file or directory)
`
Did you have space teams before?

**Comment by elak93** [comment]
Not that I'm aware of I deleted the json files for before I run that console output I posted
