### ISSUE TITLE
shift in AE2 terminals are tanking the fps

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#16098]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.6.0

### Your Server

delta

### Java Version

Java 21

### Type of Server

Thermos

### Your Expectation

use AE2 normally, like before.

### The Reality

the instance is freezing

### Your Proposal

fix this huge cpu load source:

WCT GUI open without pressing shift:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12850933/f99e102b-54ec-4560-96d0-56c217809f54)

WCT GUI open while i press shift:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12850933/344467f8-c828-42fb-a447-5ba2712e6e89)

Regular crafting terminal while i press shift:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12850933/d4c6a97e-f3ca-43c1-8e0a-eeee3c2f1b83)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/502 did not fix anything apparently

**Comment by Caedis** [comment]
We are going to rewrite this at a later point, or work off what firenoo already has in https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/tree/feature/shift_freeze
