### ISSUE TITLE
Fast leaf decay on thaumcraft trees cause lag

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#16092]
this is happening on eta (2.6.0)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12850933/a843665d-d869-462b-a084-dbeb8c89d9f4)

Couldn't find yet if it's a player doing a tree farm or if it's just this bad with fast leaf decay (probably the first option)

https://github.com/GTNewHorizons/Random-Things/pull/6

**Comment by chochem** [comment]
feature merge during feature freeze. :(

**Comment by boubou19** [comment]
the bug seems to be in crappy thaumcraft code, the feature works well ;)
