### ISSUE TITLE
Scrolling items in the inventory brings it to the crafting grid, not the hotbar (as was before)

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#16095]
### Your GTNH Discord Username

skproch

### Your Pack Version

2.6.0-beta3

### Your Server

Private

### Java Version

Java 21

### Type of Server

Ultramine

### Your Expectation

In 2.5.1 while scrolling above item in the inventory it will prefer go to hotbar. 

### The Reality

In 2.6.0-beta3 and (2.6.0 apparently) it will go to the crafting grid.

### Your Proposal

Scrolling above item in the inventory should bring it to hotbar or have it configurable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SKProCH** [comment]
I've looked through changes in MouseTweaks and seems like only noticeable change - migration to another config solution. 

Probably there is some errors in this (or in config reading). 

I suspect that WheelSearchOrder config property should determine the current logic, but all the values (0 and 1) seems currently has identical behavior. Probably there is some config reading issue.

**Comment by Krydax** [comment]
FWIW. I am a fan of the new behavior over the old, if it had to just be one or the other. Obviously being able to set which one it does would be optimal. Or even some combination of the two.

**Comment by chochem** [comment]
> configurable.

it should be already. meaning you turn if off in one mod and turn it back on in the other. I think mousetweaks and NEI.
