### ISSUE TITLE
Neutronium Compressor Bug

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#16106]
### Your GTNH Discord Username

lordpeverell

### Your Pack Version

2.6

### Your Server

Private

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Ability to properly craft singularities

### The Reality

https://discord.com/channels/181078474394566657/234936569360809996/1234472388784291921

Anything with more than 64 blocks just dupes and stalls up the neutronium compressor

### Your Proposal

Fix the above bug, maybe look at migrating the singularities to the EIC. Inf cat, iron and fluxed electrum singularities have already been added 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ReignOfFROZE** [comment]
I wasn't able to reproduce this in any dev environment or 2.6 myself

**Comment by NotAPenguin0** [comment]
@joshaup1999 did you try this in a blank 2.6 install?

**Comment by joshaup1999** [comment]
I haven’t tested this, have seen multiple people on discord mention the issue hence why I made a ticket with the attracted discord link of a video

**Comment by Alexdoru** [comment]
this machine is now disabled in the game anyways
