### ISSUE TITLE
Server closed on my SP world

### ISSUE THREAD

**Issue by Duaris** [GTNewHorizons/GT-New-Horizons-Modpack#16109]
### Your GTNH Discord Username

megamanx8 changed to Duaris in the server

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

I got my battery buffer, good miner and a diamon chest full of ores and other stuff and was jumping/gliding with a glider and a piston boots returning to my base.

after restarting the game and trying to load back it says "Server closed" then returns me back to server list and not the single player worlds.

attemting to enter again just keeps it at 0% and never load.

### Crash Report

https://mclo.gs/7Gi64jj

I was playing on a 2.5.0 world using java 8

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
that error looks like corruption. best use a backup

**Comment by Duaris** [comment]
Another thing I noticed very late that my Drive was ful and the latest backup stopped early and got corrupted in the process, I thought of adding this since it may be related one way or another.
