### ISSUE TITLE
Crash: Already tesselating!

### ISSUE THREAD

**Issue by ShadowOnWiiU** [GTNewHorizons/GT-New-Horizons-Modpack#16100]
### Your GTNH Discord Username

shadmew

### Your Pack Version

2.5.1 and 2.6.0 (both versions crash)

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

My friend and I are playing together on a forge server (hosted on my PC), and are currently mid EV. I had played with OptiFine from the start of the playthrough, my friend did not. At some point in MV/HV, my friend started crashing with the error "already tesselating!". He also installed optifine, and the crash went away. Now that we are updating to 2.6.0, optifine no longer exists, and angelica immediately crashes us out of the world (Chunk build failed, which looks to be a common angelica crash at the moment). Removing angelica gives us the same "already tesselating!" error as before. This happens within a few seconds of joining the server.

I have attached the latest crash report of this happening.

There are a few instances of closed issues that seem to have similar issues, but they all were resolved with stuff that doesnt affect us (Ultramine, Optifine being installed; which it isnt for us)

### Crash Report

[crash-2024-04-29_22.37.16-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15154911/crash-2024-04-29_22.37.16-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ShadowOnWiiU** [comment]
Update: Java 17 + OptiFine fixed the Already Tesselating error, however I'm guessing the underlying error still persists, since not using OptiFine still crashes.

**Comment by chochem** [comment]
> Chunk build failed

thats extremely vague. we will need logs

**Comment by SpencerGerdes** [comment]
I have an additional log from Detla if it helps any. same error "chunk build failed". crash happened over an hour after I was on the server, screen went black while I was in my inv for 20 seconds before crash. no optifine or any changes to the latest version.
[crash-2024-05-01_01.13.40-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15174074/crash-2024-05-01_01.13.40-client.txt)

**Comment by Caedis** [comment]
@SpencerGerdes please have them (and you and the server) try
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/releases/download/rv3-beta-354-GTNH-pre/appliedenergistics2-rv3-beta-354-GTNH-pre.jar

**Comment by madmacf** [comment]
I think I have the same. Crash in 2.6.0
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15209421/latest.log)
