### ISSUE TITLE
Catwalks's Support Column not rendering correctly

### ISSUE THREAD

**Issue by YamiKami-Sama** [GTNewHorizons/GT-New-Horizons-Modpack#16108]
### Your GTNH Discord Username

yamikami_sama

### Mod Version

GT:NH 2.6.0

### Java Version

Java 8

### Graphics Card Vendor

NVidia

### Bug Report

The item is rendered properly
![image](https://github.com/GTNewHorizons/Angelica/assets/25430031/769b719a-49de-4750-a9dd-ccde48a054ed)

### Mod List or GTNH Pack Version

GTNH-2.6.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Glease** [comment]
For the non-dev: catwalks repo is private per author's request. It's fixed internally and soon a new version will be released for this. For now you can use this jenkins build http://jenkins.usrv.eu:8080/job/Catwalks-2/35/
