### ISSUE TITLE
Add a auto-launch option to relauncher

### ISSUE THREAD

**Issue by srdr2k3** [GTNewHorizons/GT-New-Horizons-Modpack#16103]
### Your GTNH Discord Username

@srdra

### Your Pack Version

2.6.0

### Your Proposal

There should be a checkbox option to have the instance launch automatically each time relauncher is opened.

### Your Goal

Should save an extra click, which was not needed before 2.6.0.

### Your Vision

Less carpal tunnels. Imagine the effects it would have on the human health overall!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
that should not pop up at all. I suspect a somewhat incorrect install.

**Comment by srdr2k3** [comment]
I did remove all the non updated files before updating but i could try again on a fresh instance.

**Comment by chochem** [comment]
https://gtnh.miraheze.org/wiki/Installing_and_Migrating

**Comment by srdr2k3** [comment]
It was indeed an incorrect install... Thanks.
