### ISSUE TITLE
Search Button at QB ends in crash

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#16117]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.7. Nightly - 455

### Your Server

Zeta

### Java Version

Java 8

### Type of Server

None

### Your Actions

open QB -> activate search button -> client crash

### Crash Report

[crash-2024-04-30_21.34.07-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15170171/crash-2024-04-30_21.34.07-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
no crash for me in 2.6.0

**Comment by Ngar1** [comment]
> no crash for me in 2.6.0

report it is related to Nightly

**Comment by Ngar1** [comment]
same on opening page MV at QB

**Comment by Glease** [comment]
Try run `/bq_admin cleanup_questline`. This will prune invalid questline entry and it might fix this problem. Be sure to make a backup of `"saves/<save name>/betterquesting" before doing so though.

**Comment by Ngar1** [comment]
> Try run `/bq_admin cleanup_questline`. This will prune invalid questline entry and it might fix this problem. Be sure to make a backup of `"saves//betterquesting" before doing so though.

Thanks! Restart of Zeta solves it too

**Comment by Glease** [comment]
oh didn't notice you were on zeta. Then it's probably something in net code being broken. That's slightly more concerning...

**Comment by Dream-Master** [comment]
@Glease Are we need a fix here ?

**Comment by Glease** [comment]
Need further investigation first

**Comment by Ngar1** [comment]
Solved in Nightly version 420
