### ISSUE TITLE
Toxic everglade crash 

### ISSUE THREAD

**Issue by Captainhd7** [GTNewHorizons/GT-New-Horizons-Modpack#16115]
### Your GTNH Discord Username

Captainhd7

### Your Pack Version

2.6

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

spawn in new world (or old world)
make and open portal to toxic everglade
walk in, wait a few seconds crash
(first crash takes longer)
(when friend tested took a few min to crash)

### Crash Report

[crash-2024-04-30_13.11.04-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15168533/crash-2024-04-30_13.11.04-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
can you post a full log?

**Comment by Lyfts** [comment]
Same issue as https://github.com/GTNewHorizons/Angelica/issues/404

**Comment by Glease** [comment]
Totally unrelated note: you are using java8, not java 17
