### ISSUE TITLE
World not appearing in menu screen after updating to 2.6, but reappears when uninstalling Angelica

### ISSUE THREAD

**Issue by Blemmingan** [GTNewHorizons/GT-New-Horizons-Modpack#16119]
### Your GTNH Discord Username

joacobanfield

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

I updated my pack using MultiMC.

I cloned the original instance, and changed its name to GTNH 2.6. Then, I deleted its **mods** and **config**, as well as **scripts** (I did not have **resources**) folders, and replaced them with the downloaded ones. I also replaced the **libraries**, **patches**, and **mmc-pack.json** in the correct folder, and pasted the downloaded **config** and **mods** folders correctly.

Upon starting the new instance, the game crashed with an error asking me to add a JVM argument to the command line arguments, which I did, at the very tail end of all arguments. 

Then the game launched, and entered the main menu. However, upon clicking singleplayer, my world was not there, despite being in the saves folder and MultiMC recognizing it as a world.

Deleting Angelica with MultiMC solved this issue and allowed me to enter the world in 2.6.0. All was fine, however of course performance suffered. Is there a way I can fix this?

The world had been corrupted before, but I managed to save it via backup. I can provide anything you might need.

Thanks for all your time and effort, I'm having lots of fun with this pack.

### Crash Report

https://paste.ee/p/OsOMJ

This is the crash that asks me to add a java argument. I add it at the end after others.

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15171846/fml-client-latest.log)

This is the fml-client-latest once I launch the game with the Java argument provided. The world does not show up in the menu despite being in the saves folder. Once I delete Angelica, this is fixed.

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15171898/fml-client-latest.log)

This is the same log without Angelica. I launched the game, entered the world, and walked around a bit before exiting normally.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
It looks like you didnt properly update your pack

**Comment by Ethryan** [comment]
I usually create a new pack instance, and then copy in the saves and journeymap folder from the old instance.

**Comment by chochem** [comment]
I mean the first problem you had is just forgotten to update java args. sounds like you followed all the other step in the wiki but dropped this one.
actually more than one changed, so please try again with doing it properly.

**Comment by Blemmingan** [comment]
I've tried to use the "Migrating to a different launcher" approach, but still no luck. The world still doesn't show up in the menu screen. I've even tried copying only the saves folder, but that didn't work. Maybe I could generate a world with the same seed and name as the old one, then paste the saves folder over that?

I'm using these Java arguments. Are they correct?

https://pastebin.com/SpiNkLJ6

**Comment by Alphozone** [comment]
I have the exact same issue but then with using prism and also trying to upgrade it multiple times.
