### ISSUE TITLE
Crafting Input Bus (ME) changed behavior

### ISSUE THREAD

**Issue by Joze97** [GTNewHorizons/GT-New-Horizons-Modpack#16118]
### Your GTNH Discord Username

noname0452

### Your Pack Version

2.6.0

### Your Server

SP & private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Trying to use patterns "Crafting Input Bus (ME)". Those patterns require fluids or items, with are stocked in a differend Hatch/Bus. I expect the "Crafting Input Bus (ME)" to work the same as an item "Input Bus" with an "ME Interface".

This has worked in 2.5.0

### The Reality

The Multiblock dosn't start the craft.

Example Cutting Factorory:
- Cutting Factory is correctly formed and stocked with "Lubricant"
- Cutting Factory produces Wafer if a Boule is put into the "Input Hatch"
- Cutting Factory dosn't produce Wafer if requested over AE2 System

![2024-04-30_21 32 42](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/109675471/cf00648f-2b29-4c33-9f57-0fadce21982d)
Items reach the "Crafting Input Bus (ME)"

EBFs and MEBFs show the same behavior.

### Your Proposal

"Crafting Input Bus (ME)" should work with items/fluids stocket in a different bus/hatch

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
this never worked, crafting inputs are forced to separate from any other inputs including ur lubricant hatch.

**Comment by chochem** [comment]
it worked in some situations due to a bug but was fixed
