### ISSUE TITLE
Change scroll wheel functionality

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#16128]
### Your GTNH Discord Username

lordpeverell

### Your Pack Version

2.6

### Your Proposal

Change scroll wheel functionality back to putting item into hot bar instead of  inventory crafting grid

### Your Goal

Getting config change to be reverted 

### Your Vision

Make it so players dont have to suffer with muscle memory of scroll wheeling to move items to hot bar instead of it going to inventory crafting grid

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by SKProCH** [comment]
@joshaup1999 https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16095#issuecomment-2085248384
