### ISSUE TITLE
New Thaumic Boots negative durability disconnection

### ISSUE THREAD

**Issue by fw4hre0xxq** [GTNewHorizons/GT-New-Horizons-Modpack#16129]
### Your GTNH Discord Username

hifunc

### Your Pack Version

2.5.1

### Your Server

Private

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

I made Nano Boots of the Voidwalker, and they had -32442 durability, as indicated in the tooltip. Equipping them and attempting to press a binding to modulate speed or jump height results in a forced disconnection from the server. Putting them in a charger resolved the issue.

### Crash Report

This isn't a crash, but it does abruptly end a game session.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alastors** [comment]
I’m going to need you to update to latest and tell me if this still happens, a lot has happened between 2.5.1 and 2.6.0

**Comment by Alastors** [comment]
Also wrong repo, thaumic boots is active supported so in the future post it here: https://github.com/Alastors/ThaumicBoots
