### ISSUE TITLE
Crashing at 83% or 99% loading and sometimes causing a blue screen

### ISSUE THREAD

**Issue by bruh213123** [GTNewHorizons/GT-New-Horizons-Modpack#16122]
### Your GTNH Discord Username

pleasework#2281

### Your Pack Version

2.6.0

### Your Server

None, on startup

### Java Version

Java 8

### Type of Server

None

### Your Actions

I tried using other launchers and a different java and modpack version but it didn't help.

### Crash Report

I couldn't get the crash log for 99% or bluescreen cause I cant find them but here is the 83% crash. I do know that some people have already experienced crashes at 83% but never a bluescreen.
[hs_err_pid22748.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15174953/hs_err_pid22748.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
you are having an hardware issue sadly, it's nothing we can do. Try testing your ramsticks or check your drivers.
