### ISSUE TITLE
Drone Downlink Hatch does not work with Cleanroom

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#16127]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.6.0

### Your Server

Private Dedicated

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

The Drone Downlink Module placed on a Cleanroom would detect and attach to the Drone Centre.

### The Reality

The Cleanroom will form with a Drone Downlink Module (instead of a Maintenance Hatch), but the Drone Downlink Module never manages a connection to a Drone Center within range.

As a result, the Cleanroom is considered broken due to machine damage and unusable.

### Your Proposal

Fixit pls <3

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by RealSilverMoon** [comment]
The drone downlink can't find cleanroom's mainframe since cleanroom has a completely different checkStructure method. I can add plascrete block as an exception but other blocks allowed in config still cause downlink to fail to find mainframe.
It's not recommend to use drone on cleanroom.
