### ISSUE TITLE
Holo glasses making UI disappear

### ISSUE THREAD

**Issue by thebigcheesish** [GTNewHorizons/GT-New-Horizons-Modpack#16123]
### Your GTNH Discord Username

thebigcheesish

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Looking at a chest with a Twilight Forest magic map inside with the hologlasses equipped should show all UI as normal

### The Reality

All UI elements disappear except items when opening personal inventory. Items are still interactable when invisible.

Open Chest:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43917611/358d821a-45b8-452d-be07-32dca8e47058)

Open Inventory:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43917611/b1d35b29-5285-47b7-abf2-51a610681538)

Escape Menu:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43917611/d445e119-e1d6-4a38-82ed-957176d48da6)

Quest Book:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43917611/5203da9a-fce8-47e3-ac0e-17e26ce9e403)

Adventure Backpack:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43917611/771fc075-7ce8-4cfe-9476-c1fbf4688249)

### Your Proposal

Show the UI as normal

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Jade3375** [comment]
getting the same thing but all my ui is gone minus journeymap

**Comment by Tristatus** [comment]
I second this error as described in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16144 after the 2.6.0 Update 
![2024-05-03_22 04 20](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/44020195/8f62c8a4-6cc1-4a77-88f0-cd26d5a73ecf)

**Comment by konradmoesch** [comment]
I have the same error on one single chest. Holo glasses make the UI disappear when I look at the chest. Furthermore, the whole chest UI is invisible.
I was able to extract all items one by one from the chest and the issue seems to be connected to a "Magic Map" (The Twilight Forest). This map is the only item left. Removing it resolves the issues. Moving the map to a different chest moves the glitches to that chest, as well
