### ISSUE TITLE
Shift + RClick painting with spray cans doesn't paint laser hatches anymore

### ISSUE THREAD

**Issue by srdr2k3** [GTNewHorizons/GT-New-Horizons-Modpack#16131]
### Your GTNH Discord Username

@srdra

### Your Pack Version

2.6.0

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Shift Rclick to paint a line of laser pipes, expect the hatches in the line to be painted as well.

### The Reality

The laser pipes get painted in a line. The hatch remains unpainted.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/99605300/8b77e827-3dab-4df0-a989-f1442b3cefd3

### Your Proposal

Fix it so hatches can also be painted with the line painting.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by srdr2k3** [comment]
Also to note, spray cans have duplicated tooltips

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/99605300/8a38ed93-1c41-4ddc-9c40-40b93426a7d4)

**Comment by Caedis** [comment]
Expected behavior. Paint will now only chain to matching blocks

**Comment by srdr2k3** [comment]
Still, the laser pipes being painted together with laser hatches was a good QOL. 
I don't think this should be removed. Maybe adding a special case for laser pipes and hatches would be nice. 
Might come off as too needy, but I really find it irritating having to do extra when setting up ATs which are already as painful as it currently is.
