### ISSUE TITLE
Blood Magics teleposer does not teleport one to the end unless the chunks are loaded. Works differently than other planets.

### ISSUE THREAD

**Issue by NewGuyGames** [GTNewHorizons/GT-New-Horizons-Modpack#16139]
### Your GTNH Discord Username

NewGuy

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Other versions in between

### Type of Server

Single Player

### Your Expectation

Attempted to use teleposers to go from the overworld into the end.

### The Reality

I've used teleposers to go go back and forth between the overworld and other planets such as the moon and mars. However, now setting a teleposer to take me to the end, I found I could teleport from the end to the overworld but not the other way around. I tested and put down a passive anchor and now the teleporting works. I made a video to show it as well as how a chunk loader is not needed for mars as an example. I recreated the problem on a server with a friend where he experienced the same problem.

https://www.youtube.com/watch?v=V1DOTBV7UfI

After making the video I tried the same thing in a pdim and the same rule applies. Is there a difference between dims that one appears in versus dims where one goes through a physical portal?

### Your Proposal

Teleport the user regardless of loaded chunk in specific dims.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
The teleposer never loads the destination side, if it works then it is because the destination is loaded somehow (for example, by being in the spawn chunks).

It would be a nice feature to add though.

**Comment by NewGuyGames** [comment]
I see, for other planets I've always placed the teleposer wherever I land, so that makes sense. Thank you for the reply.
