### ISSUE TITLE
Different dimension/server chunk rendered on the wrong dimension/server (yea, it's very strange)

### ISSUE THREAD

**Issue by YamiKami-Sama** [GTNewHorizons/GT-New-Horizons-Modpack#16136]
### Your GTNH Discord Username

yamikami_sama

### Your Pack Version

GT:NH 2.6.0 without Angelica

### Your Server

Eta / custom server / SP

### Java Version

Java 1.8.0_411

### Your Expectation

Having chunk rendered correctly and don't see my base on an other server

### The Reality

Without Angelica, a cache of chunk or something else is renderer when the chunk is not loaded (sended to the client) but instead of the same dimension chunks, it render other dimension chunks, and even on another server, i disconnect, join my build/test server, and i can see my ETA base from afar.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/25430031/bea255b4-7a38-4eef-942a-f1fd8072d6bf)

Even in solo
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/25430031/e421df9b-5263-4138-9476-a5e0d4a2300d)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TheMilso** [comment]
I am getting this same issue and also seeing a lot of console spam (may be related)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/699986/7a34689b-d5cd-41de-9bf8-70036196a3d2)

I'm running same 2.6.0 without angelica
But I'm running on Java 17.0.9
