### ISSUE TITLE
Circuit Assembly Line mishandling voltage tiers

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#16135]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.6.0

### Your Server

Delta + SP

### Java Version

Java 17

### Type of Server

Thermos

### Your Expectation

CALs keep running after the update

### The Reality

A CAL that was working in 2.5.1 is now voiding ingredients. 

This one was configured with first tier wetwares and had a single UV energy hatch. The recipe for the later SoC variant uses 600K EU/t which is 1.2A of UV, and using the 2 amp capacity of the energy hatch this setup was working for all relevant SoCs ever since the circuit assembly line was introduced.

Now it will void the ingredients pretty much instantly after starting, despite having enough EU/t available for the recipe to run. Upgrading the energy hatch to UHV also makes the machine work as expected.

### Your Proposal

Restore old behaviour for the circuit assembly line, or prevent undervolted recipes from starting

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
the thing here is that the hatch can take 2A in, so voiding with 1.2A sounds weird

**Comment by chochem** [comment]
extra amount is only intake to cover for loss, same as always. (except PA which was never fixed)

**Comment by chochem** [comment]
however, it probably shouldnt be starting.
