### ISSUE TITLE
Suggestion: Log AE2 crafts

### ISSUE THREAD

**Issue by OrderedSet86** [GTNewHorizons/GT-New-Horizons-Modpack#16138]
### Your GTNH Discord Username

.order

### Your Pack Version

2.6.0

### Your Proposal

Add a config option to log player AE2 crafts, or if sufficiently small log size, just enable for all users.
Have a simple format like `{'alias': 'lcr parts', 'name': 'tripwire hook', 'quantity': 5, 'timestamp': <utc timestamp>}`.

**Back of the envelope math for how reasonable the storage would be:**
If a player does 2 ae2 crafts per minute, plays 4 hours per day, and plays for 1 year, and each log is 1000 bytes, that would be 175MB at the end (this is completely uncompressed JSONL so any kind of compressed format would be much better).

### Your Goal

Would create a very interesting dataset simply by the user playing the game!

Users could analyze it themselves or pass it to the devs for balancing research.

### Your Vision

See above

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
could also be used to tell where the pattern is located, in case of unexplained AE2 crafting load for server admins :)
