### ISSUE TITLE
Crash, and big problems with filling my memory on hard disk

### ISSUE THREAD

**Issue by GreedReaper117** [GTNewHorizons/GT-New-Horizons-Modpack#16142]
### Your GTNH Discord Username

peter117#9393

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

Hey, I'm reporting 2 bugs. The first one led to a crash (reference 1). And the second is the endless filling of space by the launched game. (Reference 2)

1. I got a crash that keeps recurring when I enter the Crafting interface and want to pull out a specific item that I have previously searched for in the system.
2. I have a strange problem with memory filling up both at rest (Main manu) and while being in the world. 30 GB of free space leaks to 0.

Due to the possibility of correlation between the two, I have included 2 Bugs in 1 topic.

I'm adding a link to Crash, if it expires, I also have it saved, so please contact me:
https://mclo.gs/Ms5FUvO 

### Crash Report

https://mclo.gs/Ms5FUvO 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
memory != storage space

Is it filling up RAM or storage?

**Comment by GreedReaper117** [comment]
> memory != storage space
> 
> Is it filling up RAM or storage?

Hard disc, Storage (partition C)

**Comment by chochem** [comment]
a massive log file or what is happening?

**Comment by GreedReaper117** [comment]
> a massive log file or what is happening?

I don't know what the reason is, I use prism. In the earlier version of GTNH it took me a maximum of 8-10 GB and now it's so much 15+ GB and 10 GB on Launch game
