### ISSUE TITLE
Clicking "Single Player" Button in main menu crashes the game and leaves annoying textures in menu after re-launch

### ISSUE THREAD

**Issue by Iris-HalfWayDown** [GTNewHorizons/GT-New-Horizons-Modpack#16147]
### Your GTNH Discord Username

iris_halfwaydown

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

![GT_ New Horizons 2 6 0 5_3_2024 10_01_49 PM](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/168881174/e50afa01-7a80-4c08-8304-4da5ea75f057)

This screen suddenly displays after clicking the single player button.

![GT_ New Horizons 2 6 0 5_3_2024 10_16_41 PM](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/168881174/d68c7995-a179-4be8-a959-35e6410d3364)
 
After booting up again, the world menu has some texture stretched across the screen. The edge of my world's text is visible. This stretched texture is present in lots of menus.

![GT_ New Horizons 2 6 0 5_3_2024 10_25_17 PM](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/168881174/180da698-b2bf-4d6b-9141-c829e42b4ee9)
![GT_ New Horizons 2 6 0 5_3_2024 10_25_29 PM](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/168881174/77c0eb46-962c-490b-8306-a8a8b23192b2)
![GT_ New Horizons 2 6 0 5_3_2024 10_26_23 PM](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/168881174/03f07d3e-55e4-4248-8ca8-29c889979eb0)

After re-launching, it persists:

![GT_ New Horizons 2 6 0 5_3_2024 10_33_50 PM](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/168881174/48255336-274c-42dd-8a2c-ff2a4e9a0e9f)

### Crash Report

[crash-2024-05-03_22.00.58-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15206347/crash-2024-05-03_22.00.58-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
Can you try updating to the latest version of Angelica?
https://github.com/GTNewHorizons/Angelica/releases/download/1.0.0-alpha42/angelica-1.0.0-alpha42.jar

**Comment by Iris-HalfWayDown** [comment]
> Can you try updating to the latest version of Angelica? https://github.com/GTNewHorizons/Angelica/releases/download/1.0.0-alpha42/angelica-1.0.0-alpha42.jar

Fixed it, thank you for the link.
