### ISSUE TITLE
View Cell toggle switch

### ISSUE THREAD

**Issue by tomasz-brak** [GTNewHorizons/GT-New-Horizons-Modpack#16156]
### Your GTNH Discord Username

baron9972

### Your Pack Version

2.6.0

### Your Proposal

Add toggle switches to all view cell slots in all terminals that accept them
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62989490/18ab5fa2-f4ab-47fa-bd8a-dfcd461665b8)

### Your Goal

Having view cells in your inventory takes a lot off space, and having to search for them in ae2 is annoying.

### Your Vision

It would be a quality of life improvement. You could encode view cells like this:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62989490/a541837a-c315-439f-adcd-b92c715b89a8)
to have all important stuff for building multis and your base at hand.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by samsonsin** [comment]
There currently is a way to toggle the cells between enabled and disabled by holding them in your hand, and then right clicking. Perhaps a conditionally shown UI element next to the view cell can simply trigger this already present functionality?

<img width="406" height="158" alt="Image" src="https://github.com/user-attachments/assets/b0c66b62-3082-483a-8821-4df142e8a97f" />

**Comment by usagirei** [comment]
You can right click to toggle in Core AE2 terminals, but it'll just get picked up if you right click on a (non Core AE2) terminal from AE2 Fluid Crafting or AE2 Wireless Crafting
