### ISSUE TITLE
Improve liquid nuclear reactor IC2.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/GT-New-Horizons-Modpack#16157]
### Your GTNH Discord Username

Pilad

### Your Pack Version

2.6.0

### Your Proposal

In the modpack, the nuclear reactor multiplier is 5. Gregtech also gives a multiplier of 2. As a result, the reactor multiplier is 10.
The liquid nuclear reactor's multiplier remained silent. Initially, the efficiency of a liquid nuclear reactor is 2 times higher than that of a nuclear reactor. That is, for balance in the modpack, a liquid nuclear reactor should have a multiplier of 20. A liquid nuclear reactor with a maximum output circuit produces heat of approximately 1200-1400 heat units per second. The reactor produces the same amount of hot coolant. That is, 1200-1400 l/s. The reactor tank capacity is 10,000 l. If the multiplier is 20, then the capacity of the reactor tank should be 1200 * 20 = 24000 l.
In its current state, the reactor will not be able to store such amounts of cold and hot agent. I propose to add the capacity of the reactor tank to the configuration file. Then it will be possible to set, for example, 30000l. This will be enough for a reactor multiplier of 20.
![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/b00de78e-6e25-47fd-86f2-59c49875f0b1)

### Your Goal

Will help you adjust the balance between the two types of nuclear reactors.

### Your Vision

This change will improve the attitude towards liquid nuclear reactors as they will become better than dry nuclear reactors. As the authors of mod industrialcraft2 intended.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by HoleFish** [comment]
Multiplier is applied in heat exchanger.

**Comment by Pilad** [comment]
> Multiplier is applied in heat exchanger.

If we compare a dry and liquid nuclear reactor with the same number of rods, the liquid nuclear reactor loses in complexity and energy. That is, we need a heat exchanger and two more turbines. And in the end, it is easier to make a dry nuclear reactor than to make an installation from a reactor, a heat exchanger and two turbines.
