### ISSUE TITLE
Can't do EIO Soul Binder recipes via AE2 patterns

### ISSUE THREAD

**Issue by FloatDoubling** [GTNewHorizons/GT-New-Horizons-Modpack#16153]
### Your GTNH Discord Username

quitebased

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Be able to autocraft recipes that available in Soul Binder via AE2 patterns.

### The Reality

You can't do that, because Soul Vials with certain mob in them don't recognized by AE2 at all, whether you have "Using substitutions" enabled or not. Probable because mob type in soul vial stored in NBT or in a different way.

So when i try to request, for example, 16 Frank'N'Zombies, AE2 just doesn't see that i already have 16 soul vials with zombies in them in my system, that's with substituion off in pattern. However, if i enable substition, then any soul vial will go in soul binder, like enderman, and the recipe obviously will not start.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/115502326/d20b9138-158f-4bb4-8d91-32299748552b)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/115502326/888c2154-3193-4393-9c72-9cd263b70169)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/115502326/8040d29b-818a-46b0-9964-1fba4a20be81)

### Your Proposal

AE2 to recognize different soul vials with different mobs in them correctly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
Are you encoding the pattern from NEI, or by clicking with a real soul vial that you crafted manually? The latter should work.

**Comment by chochem** [comment]
as pointed out this works just fine if one encodes the recipes correctly.

**Comment by dogunbound** [comment]
GTNH 2.8.3. I tried manually creating the pattern instead with a real soul vial that was in my ME system. ME is still unable to find said soul vial despite me putting that exact one I used to create a pattern with back into my ME system.

It seems like the issue may have gotten worse potentially.
