### ISSUE TITLE
Sticky Card breaks Autocrafting

### ISSUE THREAD

**Issue by BobGoldham** [GTNewHorizons/GT-New-Horizons-Modpack#16152]
### Your GTNH Discord Username

@bobgoldham

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I use an ME system with a number of singularity storage cells.
They usually have sticky cards, because I don't want the things they're filtering for to go anywhere else.
I also engage in some occasional autocrafting, as one does.
I expected to be able to combine those two features.

### The Reality

Autocrafting any item that is filtered onto a cell with a sticky card (carbon dust, in my case) in a multiblock with an me output bus (electrolyzer in my case) seems to just never register as "done" with the crafting CPU in question. This leads to the entire job being stuck, even though the items have long since arrived in the ME system and can be manually removed, used, crafted, etc.

### Your Proposal

For a crafting CPU to recognize items put into the ME system, even if they are put into a sticky location.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by madmacf** [comment]
+1
Same when fluid crafting in to a T.F.F.T tank with fluid storage bus to access it. 
With sticky card crafting job is never registered as finished even though it is.
Removing the sticky card makes it work as normal.
On Beta 3 2.6.0

**Comment by pacomesoual** [comment]
I'm having this issue in 2.6.1, I've been told it's a known issue and it seems resolved here, is there anything I can download to fix it while staying in 2.6.1 or do I need to wait for a future stable version ?
