### ISSUE TITLE
Slow Thaumcraft item wheels with angelica

### ISSUE THREAD

**Issue by the-bukkit** [GTNewHorizons/GT-New-Horizons-Modpack#16166]
### Your GTNH Discord Username

the_bukkit

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

I expected the item wheels for Thaumcraft to open at the same speed as 2.5.1 or without the Angelica mod.

### The Reality

The opening and closing animation is way slower when Angelica is installed.

[Screencast_20240505_004336.webm](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/23724545/26d630d3-7907-4a93-8191-b270ed845900)

### Your Proposal

Fix what causes the slower animation speed

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by the-bukkit** [comment]
Forgot to show that it also happens with the lens selection wheel.

[Screencast_20240505_014830.webm](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/23724545/48528d6e-4a43-4df0-8673-4d0e202d5e9e)

**Comment by mitchej123** [comment]
Likely hud caching/reduced fps

**Comment by hallucinogender** [comment]
It is slow like this for me as well, and I have been continually forced to _remove_ Angelica due to an unrelated issue causing a crash. This issue with the wand focus selection wheel is, therefore, independent of Angelica, and must be caused by something other than Angelica.

**Comment by the-bukkit** [comment]
@hallucinogender That's weird. For me it only happens with Angelica installed.

I've tested it with a new install of 2.6.0 with Angelica installed (tried the default alpha40 and alpha42) and the animation is slow until I remove Angelica.
Also tried it on both Linux and Windows in case something else was going on but that doesn't seem to make a difference.
