### ISSUE TITLE
Switching thaumcraft focus takes significantly longer

### ISSUE THREAD

**Issue by ReaganAR** [GTNewHorizons/GT-New-Horizons-Modpack#16164]
### Your GTNH Discord Username

shimmeringcircuits

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Switching wand focus takes as long as in 2.5.1 

### The Reality

in 2.5.1
![OldSpeed](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45805674/87dfa246-50cb-4343-aa7a-5cd3cce8cf3f)

in 2.6.0
![NewSpeed](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45805674/391441f2-e69a-4c28-a1f6-9b2a10dadd4c)

### Your Proposal

Return to previous speed

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
@mitchej123 could be angelica?

**Comment by ReaganAR** [comment]
Fixed in most recent nightly / by [Angelica/559](https://github.com/GTNewHorizons/Angelica/pull/559)
