### ISSUE TITLE
Journeymaps and Visual prospecting/Ore Vein fullscrean Map bug

### ISSUE THREAD

**Issue by SophieFox23** [GTNewHorizons/GT-New-Horizons-Modpack#16169]
### Your GTNH Discord Username

kumokitty

### Your Pack Version

2.6.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I open the Fullscreen Journey map and go the the Ore Vein button and click it and expected to see the found ore veins around show up

### The Reality

When I click the Ore Vein button, the full screen map closes and won't open anymore. instead I get this message instead
![Screenshot (957)](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/83872862/e2c5469e-0aee-41f5-a108-2642657d689d)
I also went into the server files and deleted the Visual prospecting file and restarted the server, when I do that the full screen map will open but clicking the Ore Vein button causes the issue to happen again.

### Your Proposal

I dont know how to fix this current issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SophieFox23** [comment]
ADDITIONAL NOTE:
 I started a new server and at first when I clicked to view ore veins it worked until I went into creative and Visual prospected an ore, once I did that the map crashed again

**Comment by SophieFox23** [comment]
After a fresh install of the pack from the client end it has seemed to resolve itself

**Comment by KleinGrrmpf** [comment]
So, this is back in the new 2.7.0-beta-1. From what I could test, it only happens when selecting the TC Nodes tab this time.
