### ISSUE TITLE
Crash after pouring creosote into water

### ISSUE THREAD

**Issue by Vsevolod090** [GTNewHorizons/GT-New-Horizons-Modpack#16173]
### Your GTNH Discord Username

vsevkur

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

I pour creosote from bucket of water into block of water in river. The creosote spread for a second and the crash occurred

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/116996345/7136b369-eda6-484a-a834-978968659a15

### Crash Report

https://mclo.gs/IeytW47

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment]
Seems to be related to the crash here https://github.com/GTNewHorizons/Angelica/issues/404
