### ISSUE TITLE
Mistake in quest book

### ISSUE THREAD

**Issue by ChocolateyHash** [GTNewHorizons/GT-New-Horizons-Modpack#16175]
![2024-05-02_22 51 56](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127671022/0b4708b7-ffbe-4542-8d5f-ee7ee0095040)
### Your GTNH Discord Username

ya.baldezhniy

### Your Pack Version

2.5.1

### Your Proposal

Questline "Bio for masses" quest "Faster Charcoal" has errors in the calculations. For 3x4x3 max sized low pressure boilers needed 19 coke ovens (~18,225) according to sources bellow:

1) https://gtnh.miraheze.org/wiki/Railcraft_Boiler
2) https://ftbwiki.org/Steam_Boiler_Statistics

So i think quest needs to be changed or mistakes in quest needs fixes. 14 coke ovens provides enough charcoal and creosote to run my 2x2x2 steel boilers. With this setup i have ~8-10 LV Amps. And there are excess of charcoal and creosote though.

The goal in the quest is more suitable just for the setup that i menshion above. 2x2x2 both creosote and charcoal feeded steel boilers provide a lot power to run EBF, and LV setup of machinery constantly. It's about 272 eu/t after transformation steam to eu in the basic steam turbine.

So i achieve the goal but can't move further along the quest line because of mistakes in calculations.

Screenshots. Here you can see, that one cock oven is even scheduling, because of excess of creosote and charcoal. According to calculation for 2x2x2 steel boilers 13,5 coke oven is needed. For 3x4x3 max sized low pressure boilers - 19 ovens

![2024-05-02_22 47 15](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127671022/897faa6d-0286-4d79-ae9f-2600f998acf7)
![2024-05-02_22 50 47](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127671022/d4c2610d-017b-4c45-9e6f-6cef19c13ed8)
![2024-05-02_22 51 00](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127671022/547ccf6c-4eb4-4201-9e85-167adadaf254)

### Your Goal

Try my best to improve this wonderfull modpack

### Your Vision

Due to an error, the players is forced to make much more effort that is disproportionate to the established goal

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by ChocolateyHash** [comment]
Setup:
![2024-05-02_22 51 56](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127671022/6696cbf2-2372-41eb-8949-de81f3fb9bb9)

**Comment by chochem** [comment]
thats already been changed. you are not on the latest version.
