### ISSUE TITLE
Tree Growth Simulator destroys chainsaws after they are reduced to <100 energy remaining, regardless of durability

### ISSUE THREAD

**Issue by ShyGuyOmega** [GTNewHorizons/GT-New-Horizons-Modpack#16170]
### Your GTNH Discord Username

shy.guy

### Your Pack Version

2.6

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

The TGS typically, in 2.5.1, ejected the saw after it could no longer be used to its output hatch, where I had AE do stuff to charge it again and re-input bus it

### The Reality

As of 2.6, when a chainsaw with usable charge is used in a TGS process, then falls below a usable amount of energy eventually, the TGS just deletes the saw regardless of the fact the tool still has lots of durability remaining

### Your Proposal

guh pls fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
I can't reproduce this in a test world, I tried a variety of saw materials and tiers, and both normal and AE output buses. An empty chainsaw always gets output when it runs out of power.

Would you mind sharing more details about your setup? What material/tier chainsaw are you using, how is your output wired, etc. Is it possible that your automation stores the output saw in a different place than you expect, or voids it? Can you reproduce this in some minimal setup?

**Comment by ShyGuyOmega** [comment]
Attempts by myself and others to reproduce it outside of my own world haven't worked, so I just scrapped the entire setup and rebuilt it and everything is fine again, so at this point I have no idea what made that setup in particular kill them. Thanks for the confirmation
