### ISSUE TITLE
Unable to start version 2.6.0

### ISSUE THREAD

**Issue by AugustoAmaral** [GTNewHorizons/GT-New-Horizons-Modpack#16174]
I'm actually using the MMC loader, but I can't load the game; it always crashes.
My java version:
```sh
java version "1.8.0_401"
Java(TM) SE Runtime Environment (build 1.8.0_401-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.401-b10, mixed mode)
```
Here is the link for the logs: https://paste.ee/p/7eqWm

**Comment by AugustoAmaral** [comment]
I really found it strange to only have 7 issues open.
Anyway, sorry for the mistake and thanks for the help!

**Comment by BlueHero233** [comment]
Is this issue still relevant? have you tried java 17-21 on the prism launcher? doesnt need extra arguments and the "installing and migrating" wiki page has a useful link for a java 21 SDK
