### ISSUE TITLE
Angelica intermittently crashes my world every hour or so

### ISSUE THREAD

**Issue by BigChainsaw** [GTNewHorizons/GT-New-Horizons-Modpack#16172]
### Your GTNH Discord Username

BigChainsaw#6773

### Your Pack Version

2.6

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

The world will run fine until the screen goes entirely white and then crashes. This happens randomly every hour or two. It did not happen before I updated to 2.6. 

### Crash Report

[crash-2024-05-05_00.40.53-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15212985/crash-2024-05-05_00.40.53-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by AkTi4** [comment]
Exact same issue for me. Even if I afk it would randomly crash. I play on a server so its not a single player issue

**Comment by ReaganAR** [comment]
Have you tried with [the most recent AE2 version?](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/releases/download/rv3-beta-400-GTNH/appliedenergistics2-rv3-beta-400-GTNH.jar) It adds null checks for the various cables causing this crash although I haven't seen if it fixed this crash for me yet.

**Comment by DannyKerstens** [comment]
Updating to the most recent AE2 version seems to have fixed it for me.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16143

**Comment by chochem** [comment]
should be resolved
