### ISSUE TITLE
Shift-clicking recipes from NEI also shift-clicks items in the actual inventory behind the NEI view

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#16181]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

When NEI is displaying recipes, shift-clicking and similar keybinds should be blocked for the player inventory.

### The Reality

When I shift-click a recipe from NEI into my fluid pattern terminal (this is probably also the case for other similar situations), if my cursor is hovering over the same location on the screen as an inventory slot containing an item, that item is also shift-clicked into my AE system as if I had shift-clicked it without the recipe view being open.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/19e12b56-be15-4ef0-bda3-75eedf6a70b4)
In this screenshot, the item in my ninth inventory slot is seen while I have my fluid pattern terminal open.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/b504233d-31c5-4670-b99f-e090eb9ab635)
In this second screenshot, you can see the location of the lower question mark icon in the recipe view. In this case, and in many other cases, part of that question mark icon is directly over the top of the same part of the screen as my ninth inventory slot.

If I now shift-left-click the recipe to set up a pattern, the item in my ninth inventory slot also gets shift-clicked into the storage system. There is a brief moment where the item _is_ visible after doing this.

### Your Proposal

Block shift-click inputs made in the NEI recipe view from also being applied to an item in the player inventory the moment the recipe view closes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
Huh, i wonder if this is also the cause of an item sometimes moving into the crafting table when clicking from nei

**Comment by hallucinogender** [comment]
What appears to be happening, after a bit of examination of the issue, is that the NEI recipe window closes, and for a brief moment the shift-left-click keybind remains active, and thus also shift-left-clicks whatever the cursor is hovering over the moment the NEI window closes. Therefore, the problem seems to be a combination of two behaviours: firstly, shift-left-clicking inside of an NEI window does not count as an independent input to a shift-left-click onto an inventory item (this may be related to the way Inventory Tweaks allows holding down this same key combination and dragging the cursor across many inventory slots to rapidly move multiple stacks at once); secondly, the NEI recipe window closes more-or-less _immediately_ upon shift-left-clicking a recipe, which means that there is no time to release the key combination (it may only be held down for a tiny fraction of a second, but that is evidently long enough for it to shift-left-click an item).

I'm not sure where the change would need to occur, but it seems like there needs to be some kind of input blocking behaviour added so that if an input is made while browsing a recipe, that exact same input cannot be interpreted by the inventory as an attempt to manipulate items.
