### ISSUE TITLE
Blood magic crashes game when I pick up my orb

### ISSUE THREAD

**Issue by jurrejelle** [GTNewHorizons/GT-New-Horizons-Modpack#16189]
### Your GTNH Discord Username

jurrejelle

### Your Pack Version

2.6.0

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

I tried to get my orb out of a chest. The orb has glitched before and said it was "unnamed", but I thought it was just a visual bug. But the error (java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
    at WayofTime.alchemicalWizardry.api.soulNetwork.SoulNetworkHandler.getCurrentMaxOrb(SoulNetworkHandler.java:42)) implies I have 0 orbs in my network

### Crash Report

[crash-2024-05-06_11.25.36-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15218911/crash-2024-05-06_11.25.36-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by jurrejelle** [comment]
[jurrejelle.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15218956/jurrejelle.txt) this is my playerdata file (should be .dat, I renamed it to .txt so github would allow it)

the orb in question is a Transparent Orb
I think it might have something to do with this?
![4a01b4fbb198129a61a47b412716e1f5](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/36511264/3f7f1c09-1e60-4032-b4d0-fd860298a102)

the item with id 9914 is a vampire cape, which we never had in our server. It also has a tag "ownerName" which makes it seem like my orb morphed into a vampire cape somehow, causing the indexOutOfBounds

**Comment by Lyfts** [comment]
It's running out of bounds on `MinecraftServer.getServer().worldServers[0]`
Which could indicate that it's running that client-side while connected to a server, adding a simple `if(!world.isRemote) return` check to the transparent orbs onUpdate method may fix it.
