### ISSUE TITLE
Game Freezing Crash on Launch, sometimes Freezes or Blue Screens PC

### ISSUE THREAD

**Issue by nomadpop** [GTNewHorizons/GT-New-Horizons-Modpack#16180]
### Your GTNH Discord Username

nomadpop.

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Actions

Crashing with a clean install. Game worked on a clean windows install for one day before crashing again. I have tried Java 8, 17,19,21. I have tried on both MultiMC and Prism Launcher. I have tried older and updated Graphics drivers. I tried a clean install of 2.5.1. 

PC Specs:
Windows 11 version: 10.0.22631 Build 22631
ASRock Z790-C
13th Gen Intel(R) Core i9-13900KF, 3000 Mhz, 24 Cores, 32 logic Proc
64 GB Ram
NVIDIA GeForce RTX 4070

### Crash Report

[crash-2024-05-05_13.05.32-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15214099/crash-2024-05-05_13.05.32-client.txt)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15214100/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
that just looks like a bunch of corrupted config files to me. a redownload/reinstall would fix that though

**Comment by boubou19** [comment]
BlueScreen is always caused by something external to the pack. Check your hardware, google the stop code of the BSoD, but this is beyond the scope of help we provide.

**Comment by nomadpop** [comment]
Your saying this is a hardware issue when that game ran fine for months and now doesn't based off of 1 in 8 crashes on CLEAN install having a blue screen when the supplied logs are from a NON blue screen crash? And how is it that I'm getting the same EXACT crash on my 8th CLEAN install being and issue with the downloaded configs?
