### ISSUE TITLE
The text in the Quest book goes beyond the boundaries

### ISSUE THREAD

**Issue by IHKBIZITOP** [GTNewHorizons/GT-New-Horizons-Modpack#16197]
### Your GTNH Discord Username

LemingQ

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Reading the text in the quest book, I expect to see it in its entirety

### The Reality

When I read the text in the quest book, I don't see it completely
![Снимок экрана 2024-05-07 112859](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/155494703/5f052542-fe84-4b80-8b50-091c0f9289e1)
![Снимок экрана 2024-05-07 114844](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/155494703/0aa6c747-f8a9-47b1-a0f9-a0b21ca6cfbb)
![Снимок экрана 2024-05-07 120843](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/155494703/b698970d-9ba9-4c8c-be05-a89f82723b63)

### Your Proposal

When you change the scale of the interface in the settings, the problem remains.
modpack has not been changed. resolution 1080x1920. Language -> Unicode: on

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by IHKBIZITOP** [comment]
resolution 1080x1920

**Comment by Vsevolod090** [comment]
You can change "Text Width Correction" in general tab in BetterQuesting settings (set to 1.1-1.2). Also please don't click on checkboxes falsely
