### ISSUE TITLE
Miner's Backpack does not accept Raw Ores

### ISSUE THREAD

**Issue by Samario1** [GTNewHorizons/GT-New-Horizons-Modpack#16207]
### Your GTNH Discord Username

Samario#0

### Your Pack Version

Nightly GTNH-2024-04-30+455-mmcprism-new-java

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Raw Ores can automatically be picked up by the Forestry Miner's Backpack and be stored within it.

### The Reality

Raw Ores are incompatible with the Miner's Backpack and cannot be placed within it - despite the fact that ore blocks and impure dust piles can be placed within it. This is inconsistent behaviour.

### Your Proposal

Allow Raw Ores to be placed into the Miner's Backpack properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
Just puched a config change that should fix this.

**Comment by Ethryan** [comment]
Yep, but it don't support it.
