### ISSUE TITLE
Game crashes upon launch

### ISSUE THREAD

**Issue by pcel0l** [GTNewHorizons/GT-New-Horizons-Modpack#16216]
### Your GTNH Discord Username

pcel0l

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Clicked the launch button, and then crash log pops up right away.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/112572122/c21ef449-6929-49bb-a4d9-b7df2253451a

Only thing I did is allocate more RAM.

### Crash Report

https://paste.ee/p/BWbMz

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
use java 8 or use new java release

**Comment by pcel0l** [comment]
oh I didn't realize multimc had a section for what java version it was using, my bad

**Comment by chochem** [comment]
follow https://gtnh.miraheze.org/wiki/Installing_and_Migrating
