### ISSUE TITLE
I'm crashing after adding some new mods in version 2.6.0 java 21

### ISSUE THREAD

**Issue by LeviSimioni** [GTNewHorizons/GT-New-Horizons-Modpack#16215]
### Your GTNH Discord Username

_null__

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Add optifine, Dynamic Surrounds and Just Enough Calculation

### Crash Report
[Stomp.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15257157/Stomp.txt)
[crash-2024-05-08_23.58.15-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15257087/crash-2024-05-08_23.58.15-client.txt)
![shot](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/108428807/ffa43bf5-69a1-4d5c-a393-fd9fa6e7a72b)
it just keeps charging endlessly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
angelica is not compatible with optifine. remove either to fix

**Comment by LeviSimioni** [comment]
ok, removing optifine worked, but now I want to add FTBUtilities but every time I add FTBLIB minecraft crashes

**Comment by slprime** [comment]
> ok, removing optifine worked, but now I want to add FTBUtilities but every time I add FTBLIB minecraft crashes

in 2.6.0. has Server Utilities. alternative to FTBUtilities

**Comment by LeviSimioni** [comment]
ohh I see, is there any way to activate the chunk loader? and sethome?

**Comment by slprime** [comment]
> ohh I see, is there any way to activate the chunk loader? and sethome?

https://github.com/GTNewHorizons/ServerUtilities or ask other players in discord

**Comment by Ethryan** [comment]
Find the serverutilities folder in the .minecraft pack folder and edit the configs within.

**Comment by LeviSimioni** [comment]
OK thanks for everyone
