### ISSUE TITLE
Nagastone causing a crash: Chunk build failed, BaseMetaPipeEntity cannot be cast to class twilightforest.tileentity.TileEntityTFNagastone

### ISSUE THREAD

**Issue by tomasz-brak** [GTNewHorizons/GT-New-Horizons-Modpack#16212]
### Your GTNH Discord Username

baron9972

### Your Pack Version

2.6.0

### Your Server

Private Dedicated, Remote

### Java Version

Java 21

### Type of Server

Don't know

### Your Actions

Just walking around the world. Crashes every 2, 3 minutes.

### Crash Report

Log from the better crashes: https://mclo.gs/DDBZdQZ
Log from prism launcher: https://mclo.gs/LsCIxOg

Crash log
[crash-2024-05-08_22.24.41-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15254491/crash-2024-05-08_22.24.41-client.txt)

*im not compleatly sure this isnt a duplicate, but idk what to search for*
This only occurs with angelica, if i use optifine it goes away but the fps suffer quite a bit.

### Final Checklist

- [ ] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by tomasz-brak** [comment]
Using ```//replacenear 200 0848 0``` to destroy all *nagastone* in the world fixes the issue and allows you to play normally.

**Comment by N2K2021** [comment]
is this really work?

**Comment by PlumpyChicken** [comment]
same issue using 2.6.1,
tried reinstalling - didnt work.
[crash-2024-06-20_15.49.45-server.txt](https://github.com/user-attachments/files/15909280/crash-2024-06-20_15.49.45-server.txt)

**Comment by chochem** [comment]
long fixed including this variant
