### ISSUE TITLE
Xray with the Blueberry Bush from the Natura Mod

### ISSUE THREAD

**Issue by Aaron13139** [GTNewHorizons/GT-New-Horizons-Modpack#16213]
### Your GTNH Discord Username

ok.7570

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

When placing the bush down after it was broken, I am able to see through the blocks around the bush. I have tried to turn off the setting "Chunk Multi-Draw" as asked by another person on the GTNH discord but it doesn't fix it.

### The Reality

When placing the blocks down, was able to see through the blocks around the bush.
![2024-05-08_01 50 07](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/54523708/0c42f4f6-00e8-4bbf-8533-853ef6abe6db)

### Your Proposal

I'm not sure of a solution but the block could be removed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Aaron13139** [comment]
This issue seems to happen to any block that can be translucent or blocks with gaps such as the bushes and now leaves. 
![2024-05-12_02 03 58](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/54523708/a185ed86-fd41-4d46-9769-a6c336b93e93)

**Comment by Connor-Colenso** [comment]
I get this (for the berry bushes only) but it only occurs on fast graphics. Windows.

**Comment by Aaron13139** [comment]
> I get this (for the berry bushes only) but it only occurs on fast graphics. Windows 11.

This still occurs on fancy graphics for me. Also on windows 11 too.

**Comment by Aaron13139** [comment]
Solve this by changing the "Foliage" setting to something other than "Fast"
