### ISSUE TITLE
Collapse due to using forestry mod soldering iron

### ISSUE THREAD

**Issue by Makisekuasd** [GTNewHorizons/GT-New-Horizons-Modpack#16229]
### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Collapse the world when using an electric soldering iron to sneak around and right-click on the multi block structure of the farm。
But creating a new world and repeating the above steps in the same version and configuration did not cause a crash.

### Crash Report

[crash-2024-05-10_17.33.22-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15273956/crash-2024-05-10_17.33.22-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
do you still have the broken soldering iron? can you please show us what `/mt hand` tells you while holding it? It looks like the item is broken somehow.

**Comment by BlueHero233** [comment]
@Makisekuasd could we have a return on this?

**Comment by BlueHero233** [comment]
Closed by no return from OP
