### ISSUE TITLE
GTNH not launching

### ISSUE THREAD

**Issue by asaachy** [GTNewHorizons/GT-New-Horizons-Modpack#16230]
### Your GTNH Discord Username

heypeter1killmothers

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

Just tried to launch the game and got the crash report

### Crash Report

MultiMC version: 0.7.0-3857

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.64, 13.107.213.64]

textures.minecraft.net resolves to:
    [13.107.213.64, 13.107.246.64]

api.mojang.com resolves to:
    [13.107.246.64, 13.107.213.64]

Minecraft folder is:
C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/instances/GT_New_Horizons_2.6.0_Java_17-21/.minecraft

Java path is:
C:/Program Files/Eclipse Adoptium/jre-17.0.11.9-hotspot/bin/javaw.exe

Checking Java version...
Java is version 17.0.11, using 64-bit architecture, from Eclipse Adoptium.

Main Class:
  com.gtnewhorizons.retrofuturabootstrap.Main

Native path:
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/instances/GT_New_Horizons_2.6.0_Java_17-21/natives

Libraries:
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-arm64/3.3.2/lwjgl-glfw-natives-windows-arm64-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows-x86/3.3.2/lwjgl-glfw-natives-windows-x86-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw-natives-windows/3.3.2/lwjgl-glfw-natives-windows-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.2/lwjgl-glfw-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-arm64/3.3.2/lwjgl-jemalloc-natives-windows-arm64-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows-x86/3.3.2/lwjgl-jemalloc-natives-windows-x86-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc-natives-windows/3.3.2/lwjgl-jemalloc-natives-windows-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.2/lwjgl-jemalloc-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-natives-windows-arm64/3.3.2/lwjgl-natives-windows-arm64-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-natives-windows-x86/3.3.2/lwjgl-natives-windows-x86-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-natives-windows/3.3.2/lwjgl-natives-windows-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal-natives-windows-arm64/3.3.2/lwjgl-openal-natives-windows-arm64-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal-natives-windows-x86/3.3.2/lwjgl-openal-natives-windows-x86-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal-natives-windows/3.3.2/lwjgl-openal-natives-windows-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.2/lwjgl-openal-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-arm64/3.3.2/lwjgl-opengl-natives-windows-arm64-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows-x86/3.3.2/lwjgl-opengl-natives-windows-x86-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl-natives-windows/3.3.2/lwjgl-opengl-natives-windows-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.2/lwjgl-opengl-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb-natives-windows-arm64/3.3.2/lwjgl-stb-natives-windows-arm64-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb-natives-windows-x86/3.3.2/lwjgl-stb-natives-windows-x86-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb-natives-windows/3.3.2/lwjgl-stb-natives-windows-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.2/lwjgl-stb-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-arm64/3.3.2/lwjgl-tinyfd-natives-windows-arm64-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows-x86/3.3.2/lwjgl-tinyfd-natives-windows-x86-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd-natives-windows/3.3.2/lwjgl-tinyfd-natives-windows-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.2/lwjgl-tinyfd-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.3.2/lwjgl-3.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/google/code/gson/gson/2.10.1/gson-2.10.1.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/instances/GT_New_Horizons_2.6.0_Java_17-21/libraries/lwjgl3ify-2.0.7-forgePatches.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [✔️] +unimixins-all-1.7.10-0.1.17.jar
  [✔️] AdvancedSolarPanel-1.7.10-3.5.1a.jar
  [✔️] adventurebackpack-1.1.3-GTNH.jar
  [✔️] ae2fc-1.2.28-gtnh.jar
  [✔️] ae2stuff-0.7.0-GTNH.jar
  [✔️] AFSU-1.3.0-GTNH.jar
  [✔️] alchgrate-1.1.0-GTNH.jar
  [✔️] amazingtrophies-1.2.1.jar
  [✔️] AmunRa-GC-0.5.1.jar
  [✔️] angelica-1.0.0-alpha40.jar
  [✔️] AngerMod-0.7.1.jar
  [✔️] AppleCore-3.3.0.jar
  [✔️] appliedenergistics2-rv3-beta-352-GTNH.jar
  [✔️] archaicfix-0.7.2.jar
  [✔️] ArchitectureCraft-1.9.5.jar
  [✔️] Aroma1997Core-1.7.10-1.0.2.16.jar
  [✔️] AromaBackup-1.7.10-0.1.0.0.jar
  [✔️] AsieLib-0.5.5.jar
  [✔️] Automagy-1.7.10-0.28.2.jar
  [✔️] Avaritia-1.49.jar
  [✔️] Avaritiaddons-1.7.1-GTNH.jar
  [✔️] backpack-2.3.0-GTNH.jar
  [✔️] bartworks-0.9.21.jar
  [✔️] battlegear2-1.3.7.jar
  [✔️] Baubles-1.0.4.jar
  [✔️] bdlib-1.10.0-GTNH.jar
  [✔️] beebetteratbees-0.4.0-GTNH.jar
  [✔️] BetterAchievements-0.2.0.jar
  [✔️] BetterBuildersWands-0.11.1-GTNH.jar
  [✔️] bettercrashes-1.4.0-GTNH.jar
  [✔️] betterloadingscreen-1.6.1-GTNH.jar
  [✔️] betterp2p-1.2.1.jar
  [✔️] BetterQuesting-3.5.13-GTNH.jar
  [✔️] BiblioCraft[v1.11.7][MC1.7.10].jar
  [✔️] BiblioWoods[BiomesOPlenty][v1.9].jar
  [✔️] BiblioWoods[Forestry][v1.7].jar
  [✔️] BiblioWoods[Natura][v1.5].jar
  [✔️] binnie-mods-2.3.4.jar
  [✔️] BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
  [✔️] BlockLimiter-0.6.0.jar
  [✔️] blockrenderer6343-1.1.6.jar
  [✔️] BloodArsenal-1.3.2.jar
  [✔️] BloodMagic-1.5.2.jar
  [✔️] Botania-1.10.12-GTNH.jar
  [✔️] BotanicHorizons-1.1.2-GTNH.jar
  [✔️] BrandonsCore-1.1.0-GTNH.jar
  [✔️] bugtorch-1.2.13-GTNH.jar
  [✔️] buildcraft-7.1.39.jar
  [✔️] buildcraft-compat-7.1.17.jar
  [✔️] BuildCraftOilTweak-1.1.1.jar
  [✔️] CarpentersBlocks-3.5.3-GTNH.jar
  [✔️] catwalks-2.2.1-GTNH.jar
  [✔️] chisel-2.14.1-GTNH.jar
  [✔️] chiseltones-1.1.0-GTNH.jar
  [✔️] CodeChickenCore-1.2.1.jar
  [✔️] CodeChickenLib-1.2.1.jar
  [✔️] CoFHCore-[1.7.10]3.1.4-329.jar
  [✔️] CompactKineticGenerators-1.7.10-1.0.jar
  [✔️] Computronics-1.7.2-GTNH.jar
  [✔️] controlling-2.0.2.jar
  [✔️] CookingForBlockheads-1.3.4-GTNH.jar
  [✔️] CoreTweaks-1.7.10-0.3.3.2+nomixin.jar
  [✔️] CraftPresence-2.3.9-1.7.10.jar
  [✔️] CraftTweaker-3.3.1.jar
  [✔️] creativecore-1.4.0-GTNH.jar
  [✔️] CropLoadCore-0.2.0.jar
  [✔️] CropsPP-1.6.5.jar
  [✔️] custommainmenu-1.11.2.jar
  [✔️] defaultkeys-1.2.0.jar
  [✔️] defaultserverlist-1.5.0.jar
  [✔️] defaultworldgenerator-0.3.0.jar
  [✔️] Draconic-Evolution-1.3.5-GTNH.jar
  [✔️] DummyCore-1.18.0.jar
  [✔️] duradisplay-1.2.3.jar
  [✔️] EMT-1.4.6.jar
  [✔️] endercore-0.4.6.jar
  [✔️] EnderIO-2.7.4.jar
  [✔️] EnderStorage-1.5.1.jar
  [✔️] EnderZoo-1.1.0.jar
  [✔️] EnhancedLootBags-1.1.1.jar
  [✔️] eternalsingularity-1.2.1.jar
  [✔️] extrautilities-1.2.13a.jar
  [✔️] findit-1.2.5.jar
  [✔️] FloodLights-1.3.0.jar
  [✔️] Forbidden.Magic-0.7.0-GTNH.jar
  [✔️] Forestry-4.8.9.jar
  [✔️] forgelin-1.9.9-GTNH.jar
  [✔️] ForgeMultipart-1.4.8.jar
  [✔️] ForgeRelocation-0.1.2.jar
  [✔️] ForgeRelocationFMP-0.1.0.jar
  [✔️] gadomancy-1.3.2.jar
  [✔️] galacticgreg-1.1.0.jar
  [✔️] Galacticraft-3.1.5-GTNH.jar
  [✔️] GalaxySpace-1.1.83-GTNH.jar
  [✔️] gendustry-1.7.0-GTNH.jar
  [✔️] ggfab-0.3.19.jar
  [✔️] GoodGenerator-0.8.22.jar
  [✔️] GraviSuite-1.7.10-2.0.3.jar
  [✔️] gravisuiteneo-1.1.5.jar
  [✔️] gregtech-5.09.45.163.jar
  [✔️] GT.Scanner.Mod-1.8.0.jar
  [✔️] gtneioreplugin-1.2.0.jar
  [✔️] GTNewHorizonsCoreMod-2.3.50.jar
  [✔️] gtnhintergalactic-1.3.4.jar
  [✔️] gtnhlanth-0.12.12.jar
  [✔️] gtnhlib-0.2.11.jar
  [✔️] GTNH-TC-Wands-1.4.0.jar
  [✔️] GT-PlusPlus-1.11.58.jar
  [✔️] GTTweaker-2.1.0.jar
  [✔️] HardcoreDarkness-MC1.7.10-1.7.jar
  [✔️] HardcoreEnderExpansion-1.10.1-GTNH.jar
  [✔️] harvestcraft-1.1.10-GTNH.jar
  [✔️] Healer-1.2.1.jar
  [✔️] HelpFixer-1.2.0.jar
  [✔️] hodgepodge-2.4.43.jar
  [✔️] holoinventory-2.4.7-GTNH.jar
  [✔️] HungerOverhaul-1.7.10-1.0.0.jenkins104.jar
  [✔️] hydroenergy-1.2.0.jar
  [✔️] IC2 Crop Plugin Version 1.7.10-1.3.1.jar
  [✔️] IC2NuclearControl-2.6.2.jar
  [✔️] ifu-1.10.2.jar
  [✔️] IguanaTweaksTConstruct-2.4.1.jar
  [✔️] industrialcraft-2-2.2.828a-experimental.jar
  [✔️] InfernalMobs-1.8.1-GTNH.jar
  [✔️] InGameInfoXML-2.8.8.jar
  [✔️] INpureCore-1.2.0-GTNH.jar
  [✔️] inventorytweaks-1.6.2.jar
  [✔️] IronChest-6.0.85.jar
  [✔️] IronChestMinecarts-1.1.0.jar
  [✔️] irontanks-1.3.0.jar
  [✔️] JABBA-1.3.3.jar
  [✔️] journeymap-1.7.10-5.2.3-fairplay.jar
  [✔️] kekztech-0.10.4.jar
  [✔️] kubatech-0.14.7.jar
  [✔️] littletiles-1.3.0-GTNH.jar
  [✔️] logisticspipes-1.1.5-GTNH.jar
  [✔️] lootgames-2.1.1.jar
  [✔️] LunatriusCore-1.2.0-GTNH.jar
  [✔️] lwjgl3ify-2.0.7.jar
  [✔️] magicbees-2.7.15-GTNH.jar
  [✔️] malisisdoors-1.16.4-GTNH.jar
  [✔️] Mantle-0.4.1.jar
  [✔️] mobsinfo-0.2.6-GTNH.jar
  [✔️] ModTweaker2-0.10.0.jar
  [✔️] modularui-1.1.42.jar
  [✔️] MouseTweaks-2.4.17-GTNH.jar
  [✔️] MrTJPCore-1.1.7.jar
  [✔️] mxrandom-0.3.0.jar
  [✔️] Natura-2.6.1.jar
  [✔️] naturescompass-1.4.0-GTNH.jar
  [✔️] NEIAddons-1.15.0.jar
  [✔️] NEICustomDiagram-1.5.17.jar
  [✔️] NEIIntegration-1.4.0.jar
  [✔️] netherportalfix-1.2.0.jar
  [✔️] NodalMechanics-1.2.1-GTNH.jar
  [✔️] NotEnoughEnergistics-1.5.1.jar
  [✔️] notenoughIDs-2.0.3.jar
  [✔️] NotEnoughItems-2.5.27-GTNH.jar
  [✔️] nutrition-0.0.10.jar
  [✔️] oauth-1.2.2-GTNH.jar
  [✔️] OpenBlocks-1.9.1-GTNH.jar
  [✔️] OpenComputers-1.10.11-GTNH.jar
  [✔️] OpenGlasses-1.5.0-GTNH.jar
  [✔️] OpenModsLibs-0.10.9.jar
  [✔️] OpenModularTurrets-2.3.2.jar
  [✔️] openprinter-0.2.0-GTNH.jar
  [📁] OpenSecurity (folder)
  [✔️] opensecurity-1.1.1-GTNH.jar
  [✔️] Opis-1.4.2-mapless.jar
  [✔️] overloadedarmorbar-1.1.0.jar
  [✔️] Pam's Harvest the Nether 1.7.10a.jar
  [✔️] personalspace-1.0.30.jar
  [✔️] PlayerAPI-1.4.4.jar
  [✔️] ProjectBlue-1.2.0-GTNH.jar
  [✔️] ProjRed-4.9.5-GTNH.jar
  [✔️] Railcraft-9.15.8.jar
  [✔️] RandomThings-2.5.3.jar
  [✔️] RemoteIO-2.5.2.jar
  [✔️] roguelike-1.6.0-GTNH.jar
  [✔️] RWG-alpha-1.4.1.jar
  [✔️] Schematica-1.11.1-GTNH.jar
  [✔️] ServerUtilities-2.0.35.jar
  [✔️] SGCraft-1.4.4-GTNH.jar
  [✔️] sharewhereiam-2.1.1.jar
  [✔️] sleepingbag-0.2.1.jar
  [✔️] SpecialMobs-3.5.0.jar
  [✔️] SpiceOfLife-2.1.7-carrot.jar
  [✔️] StevesAddons-0.12.3.jar
  [✔️] StevesCarts-2.1.1.jar
  [✔️] StevesFactoryManager-1.2.3-GTNH.jar
  [✔️] StorageDrawers-1.13.5-GTNH.jar
  [✔️] StorageDrawersBop-1.12.0-GTNH.jar
  [✔️] StorageDrawersForestry-1.12.0-GTNH.jar
  [✔️] StorageDrawersMisc-1.12.0-GTNH.jar
  [✔️] StorageDrawersNatura-1.12.0-GTNH.jar
  [✔️] structurecompat-0.5.0.jar
  [✔️] structurelib-1.3.1.jar
  [✔️] Supersolarpanel-1.1.3.jar
  [✔️] SuperTic-1.3.0.jar
  [✔️] Tainted-Magic-7.6.4-GTNH.jar
  [✔️] tcinventoryscan-1.1.4-GTNH.jar
  [✔️] tcneiadditions-1.3.6.jar
  [✔️] tcnodetracker-1.2.0.jar
  [✔️] TConstruct-1.11.15-GTNH.jar
  [✔️] TecTech-5.3.45.jar
  [✔️] TGregworks-1.7.10-GTNH-1.0.26.jar
  [✔️] Thaumcraft-1.7.10-4.2.3.5a.jar
  [✔️] Thaumcraft4Tweaks-1.5.22.jar
  [✔️] ThaumcraftMobAspects-1.1.0-GTNH.jar
  [✔️] thaumcraftneiplugin-1.7.10-1.7a.jar
  [✔️] ThaumcraftResearchTweaks-1.1.0.jar
  [✔️] Thaumic Machina-1.7.10-0.2.1.jar
  [✔️] Thaumic-Based-1.6.7.jar
  [✔️] thaumicboots-1.2.1.jar
  [✔️] thaumicenergistics-1.6.5-GTNH.jar
  [✔️] Thaumic-Exploration-1.2.5-GTNH.jar
  [✔️] ThaumicHorizons-1.5.3.jar
  [✔️] thaumicinsurgence-0.3.1.jar
  [✔️] ThaumicTinkerer-2.9.4.jar
  [✔️] TiCTooltips-1.3.1.jar
  [✔️] tinkersdefense-1.2.2.jar
  [✔️] TMechworks-0.3.1.jar
  [✔️] TooMuchLoot-4.2.0-GTNH.jar
  [✔️] torohealth-1.1.0.jar
  [✔️] Translocator-1.2.1.jar
  [✔️] TravellersGear-1.7.10-1.16.6.jar
  [✔️] travellersgearneo-1.1.0.jar
  [✔️] TwilightForest-2.5.23.jar
  [✔️] txloader-1.7.0.jar
  [✔️] Universal-Singularities-8.7.0.jar
  [✔️] visualprospecting-1.2.11.jar
  [✔️] Waila-1.7.3.jar
  [✔️] WailaHarvestability-1.2.1-GTNH.jar
  [✔️] WAILAPlugins-0.4.0.jar
  [✔️] WanionLib-1.9.0.jar
  [✔️] WarpTheory-1.3.7-GTNH.jar
  [✔️] Wawla-1.2.0-GTNH.jar
  [✔️] WirelessCraftingTerminal-1.11.2.jar
  [✔️] witchery-1.7.10-0.24.1.jar
  [✔️] WitcheryExtras-1.2.2.jar
  [✔️] WitchingGadgets-1.4.3-GTNH.jar
  [✔️] WR-CBE-1.5.0.jar
  [✔️] YAMCore-0.6.0.jar
  [✔️] Ztones-1.7.10-2.2.2.jar

Params:
  --username asaachy --version 1.7.10 --gameDir C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/instances/GT_New_Horizons_2.6.0_Java_17-21/.minecraft --assetsDir C:/Users/shrom/OneDrive/Desktop/mmc-develop-win32/MultiMC/assets --assetIndex 1.7.10 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userProperties {} --userType msa --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[--illegal-access=warn, -Djava.security.manager=allow, -Dfile.encoding=UTF-8, --add-opens, java.base/jdk.internal.loader=ALL-UNNAMED, --add-opens, java.base/java.net=ALL-UNNAMED, --add-opens, java.base/java.nio=ALL-UNNAMED, --add-opens, java.base/java.io=ALL-UNNAMED, --add-opens, java.base/java.lang=ALL-UNNAMED, --add-opens, java.base/java.lang.reflect=ALL-UNNAMED, --add-opens, java.base/java.text=ALL-UNNAMED, --add-opens, java.base/java.util=ALL-UNNAMED, --add-opens, java.base/jdk.internal.reflect=ALL-UNNAMED, --add-opens, java.base/sun.nio.ch=ALL-UNNAMED, --add-opens, jdk.naming.dns/com.sun.jndi.dns=ALL-UNNAMED,java.naming, --add-opens, java.desktop/sun.awt.image=ALL-UNNAMED, --add-modules, jdk.dynalink, --add-opens, jdk.dynalink/jdk.dynalink.beans=ALL-UNNAMED, --add-modules, java.sql.rowset, --add-opens, java.sql.rowset/javax.sql.rowset.serial=ALL-UNNAMED
, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms6000m, -Xmx6000m, -Duser.language=en]

Minecraft process ID: 1368

OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0
WARNING: Unknown module: ALL-UNNAMED
 specified to --add-opens
Using onesix launcher.

Failed to start Minecraft:
java.lang.IllegalStateException: System classloader not overwritten, add -Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader to your JVM flags
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:152)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 10 May 2024 15:37:49 +0100

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment]
MMC needs new launch args for 2.6.0
 https://github.com/GTNewHorizons/lwjgl3ify#client
