### ISSUE TITLE
Chest shadow flickering

### ISSUE THREAD

**Issue by Qimb-A** [GTNewHorizons/GT-New-Horizons-Modpack#16233]
### Your GTNH Discord Username

qimb

### Mod Version

angelica-1.0.0-alpha45

### Java Version

Java 17

### Graphics Card Vendor

NVidia

### Bug Report

had some problem with flickerign shadows on chest
showcase: https://www.youtube.com/watch?v=GANCW9KRPiE

### Mod List or GTNH Pack Version

gtnh 2.6 no another modifications except newerverision of angelica

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [X] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by Qimb-A** [comment]
after some playing around and removing some block find out that removing all logistic pipes fixes issue with chests
angelica-1.0.0-alpha45 is enabled and no shadow flickering on chests

**Comment by Krydax** [comment]
I am experiencing a similar bug, however, I have ZERO logistics pipes in my save.
This bug was NOT occuring in 2.6.0, I updated to 2.6.1, and now the bug is happening and I cannot seem to get rid of it!
https://www.youtube.com/watch?v=ryb5y40YjQI

I would love any ideas on how to fix this as it's making my game almost unplayble when this is happening constantly.

**Comment by Krydax** [comment]
Disabling GL State caching did not fix the issue either (unless that setting requires game restart. I didn't disable and then restart)

**Comment by Caedis** [comment]
Oh hey, its Krydax. Love the videos. Didnt read the name and only noticed the base.

Can you send me your world in discord so I can see if I can replicate it?

**Comment by Caedis** [comment]
Disabling the GL State caching module does require a pack restart btw
