### ISSUE TITLE
Huge quest IDs in BetterQuesting-3.6.0-GTNH mod

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/GT-New-Horizons-Modpack#16249]
### Your GTNH Discord Username

Pilad

### Your Pack Version

2.6.0

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When creating new quests, the IDs should increase from the last value

### The Reality

But instead, the IDs become huge values and also negative. Previously, IDs were added from the last value, that is, for example, there was a quest with number 2560, if you create a new quest, the ID will become 2561

Example with large IDs.
"questIDHigh:4": -6127592698954038432,
"questIDLow:4": -5092663277638354864,
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/914e09c7a95123b2738120681a5a6bcff837233d

### Your Proposal

Fix please. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pilad** [comment]
If you erase the quest database from the config and just create one quest in the new database, then it will also immediately have a strange ID.

![изображение](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9840821/9dd6fe25-fe61-467d-b4ba-dcea31bf5149)

**Comment by chochem** [comment]
> the IDs should increase from the last value

luckily they dont anymore. it used to be a huge pain.

**Comment by chochem** [comment]
its a uuid and very much on purpose. This avoids merge conflicts, allows quest removals, and makes the files much more manageable.
