### ISSUE TITLE
Vacuum Freezer keeps saying incomplete structure

### ISSUE THREAD

**Issue by asaachy** [GTNewHorizons/GT-New-Horizons-Modpack#16243]
### Your GTNH Discord Username

heypeter1killmothers

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

Replaced the energy hatches on my vacuum freezer from mv to hv energy hatches changing nothing else about the multiblock that was working fine before hand and does not violate any chunk boundaries

### The Reality

The vacuum freezer controller just keeps saying incomplete structure and only recognises the front of the multiblock as part of it
![2024-05-12_00 27 48](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/169469269/2eea3c63-ccc7-40ce-b8fe-0ba9e29e74fa)
![2024-05-12_00 28 11](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/169469269/6e8aab40-7ffc-4349-b979-3b592179fe2e)
![2024-05-12_00 28 26](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/169469269/44dd5836-e37f-4eda-9ec4-db234ac577b4)
![2024-05-12_00 28 32](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/169469269/1342d8df-d7cf-486a-b261-9239b36daa52)

### Your Proposal

Recognise the full structure as complete

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ReaganAR** [comment]
BTW in case you didn't mean to close the issue or if anyone else comes here, muffler hatches aren't supposed to be included in the multiblock and stopped working in 2.6.0. If you just remove the muffler hatch it should form normally.
