### ISSUE TITLE
Allow auto inserting to solidifier hatch

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#16252]
### Your GTNH Discord Username

skproch

### Your Pack Version

2.6.0

### Your Proposal

Solidifier hatch should insert items into "mold" slot instead of inserting it info "in" slot.

Currently items inserted here:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29896317/af43ff6e-041b-4f83-80cb-23f9a1cb9502)

Should be inserted here:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29896317/edb408f4-71eb-4dd2-8553-b79debe0b98d)

### Your Goal

This needed cuz we have some recipies in solidifier, what requires non mold in item slot, for example Lumiinessence:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29896317/40ffcce0-7e89-4724-b254-7a0fe141b628)

Currently items inserted to a "in" slot, and doesn't inserted at all if "in" slot was occupied.

### Your Vision

This allows proper crafting Lumiinessence dust in multis.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ngar1** [comment]
Special for mold less receipt, like glass, we need a solution. In older version you was able to put glass by hand in mold slot and it works. Now (nightly 583) you can't produce Glass with Solidifier Hatch.
![grafik](https://github.com/user-attachments/assets/a291f659-1b1f-41ff-acb5-bdc3b61d79a9)

**Comment by SKProCH** [comment]
Still relevant

**Comment by Ruling-0** [comment]
You can do this in a multi, you just use a normal input bus/hatch like you do for any other multi. The solidifier hatch is a specific solution just to input separate molds before crafting input buffer.

**Comment by FourIsTheNumber** [comment]
This has been clarified as intended behavior and the slot now only accepts molds: https://github.com/GTNewHorizons/GT5-Unofficial/pull/2679
