### ISSUE TITLE
Client crashes when connecting to J21 Server

### ISSUE THREAD

**Issue by divine-ray** [GTNewHorizons/GT-New-Horizons-Modpack#16259]
### Your GTNH Discord Username

divine_ray

### Your Pack Version

2.6.0 J21

### Your Server

Private

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Trying to connect to the server yields a NPE crash (attached). 
Client has additional mods (Hodgepodge 2.4.6, WorldEdit v0.0.5, Just Enough Calculation 1.7.10-4.0)

### Crash Report

https://mclo.gs/w40hHQ9

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
and JM update was made because it has fixes for memory leaks. You should use the corresponding unlimited version from CF rather than a plain dowgrade.
