### ISSUE TITLE
significantly increase the rate of success of the biolab recipes

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#16266]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.6.0

### Your Proposal

significantly increase the rate of success of the biolab recipes. No but seriously, it's insanely stupid as it is right now. The list of the geometrical laws associated to the items:

-  xenoxene culture: 7.5% of success, so on average it requires 13.33 tries with a standard deviation of 12.82
- TcetiE culture: 75% of success so on average it requires 1.33 tries, with a standard deviation of 0.667
- [BarnardaF plasmid sample: 7.5% of success: so on average it requires 13.33 tries with a standard deviation of 12.82
- The required Data orb containing the DNA of the BarnardaF culture: 7.5% of success: so on average it requires 13.33 tries with a standard deviation of 12.82
- The DNA sample flask of the Barnarda F culture to get the data orb: 7.5% of success: so on average it requires 13.33 tries with a standard deviation of 12.82
-  BarnardaF culture: 75% of success so on average it requires 1.33 tries, with a standard deviation of 0.667

Aside from the cultures, the success rates are insanely awful, because by design of the biolab, those recipes are meant to be hand made, so the geometrical law modeling the first success is way more impactful than the binomial law corresponding to the amount of success in a finite amount of tries.

to get plasmids, you go this way:
culture -> DNA sample flask -> data orb -> Plasmid sample flask
My suggestions:
- change culture -> DNA sample flask to be 33% (new average: 3.03 tries, std of 2.48)
- change DNA sample flask -> data orb to be 100%
- change orbs -> plasmid sample flask to be 50% (new average: 2 tries, std of 1.41)

The xenoxene culture can keep its low success rate, with those rates, you can make the xenoxene in a reasonable amount of time,  while keeping the same chance based mechanic.

### Your Goal

make the micro interactions with the biolab more interesting than "spamming the recipes and afk"(tm)

### Your Vision

yeet tedium

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
isn't the usual way to solve these are to add some additives to boost chance/speed? just like what CoAL is doing. not saying it should be implemented that way, just mentioning it might be an alternative way to achieve the same goal
