### ISSUE TITLE
Crash related to AE2 Dense Cable rendering

### ISSUE THREAD

**Issue by TrkSlc** [GTNewHorizons/GT-New-Horizons-Modpack#16265]
### Your GTNH Discord Username

Trk_Slc

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Attempted various actions related to Applied Energistics 2 (AE2), including connecting Fluid Storage Buses, autocrafting items, and managing the AE2 network.

The crashes occur intermittently during different AE2 operations, including but not limited to connecting Fluid Storage Buses and autocrafting items. Error messages consistently reference rendering issues with dense cables from AE2.

### Crash Report

[crash-2024-05-13_08.55.09-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15300582/crash-2024-05-13_08.55.09-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
Check the various other ae2/angelica issues.  Resolved in latest nightlies afaik.

**Comment by mitchej123** [comment]
Also I'll note 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1894689/3e41f31d-4080-48b2-bde3-8cf4c62e5aee)
