### ISSUE TITLE
Lost Better Quest progression after upgrading to 2.6.0

### ISSUE THREAD

**Issue by Hirikols** [GTNewHorizons/GT-New-Horizons-Modpack#16263]
### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

After upgrade to new version from 2.5.1 i am expecting to have progress in Better Quest be saved. 

### The Reality

json file with progression exist in .minecraft/saves/<my-world>/betterquesting/questprogress , but on load to world it creates a new one and Progress is gone. 
Running /bq_admin default load doesnt help

### Your Proposal

no ideas

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
just double check that you are online and using the same account.

**Comment by Hirikols** [comment]
I am playing with offline account in Prism Launcher,and after upgrade it treated me as new uuid , even though my username was the same, manually changing uuid in old json to new uuid and deleting old json resolved the issue
