### ISSUE TITLE
NPE because "quest" is null

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#16277]
### Your GTNH Discord Username

DreamMasterXXL

### Your Pack Version

nightly latest

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Open up The Quest Book and hit MV Tab crash the game. When i re-enter the game and open QB it crash again.

There is some issue that look similar but i using the newest Quest format after update in 3.6.1
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15416

### Crash Report

https://pastebin.com/UQHpvrb6

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment]
I got someone on discord reporting this as well, i told him to reinstall the pack and it fixed the issue. So probably a corruption on the questbook files

**Comment by Dream-Master** [comment]
i compare the quest files from dev branch and my files and they identical so they not corrupted

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/tree/dev

**Comment by Dream-Master** [comment]
even with a new game it crash when i open the quest book and hit the mv tab.

**Comment by Dream-Master** [comment]
Guess the crash only happen when i add the new Ore Quests from @Ethryan and Ender IO Quest from @D-Cysteine to the Quest Database.

**Comment by D-Cysteine** [comment]
I think this is caused by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/16034
I will comment with the problem and fix on that PR

**Comment by halloo123** [comment]
I am still having this issue on Zeta
