### ISSUE TITLE
The crash occurred while attempting to update private server 2.6.0 17-21 Java.

### ISSUE THREAD

**Issue by BenGFly** [GTNewHorizons/GT-New-Horizons-Modpack#16271]
### Your GTNH Discord Username

bengfly

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

None

### Your Actions

I've been following the steps to update my server from the page: https://gtnh.miraheze.org/wiki/Server_Setup.

### Crash Report

https://pastebin.com/W8hULgXA

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment]
Did you accidentally delete thaumcraft while updating?

**Comment by BenGFly** [comment]
> Did you accidentally delete thaumcraft while updating?

You were right, it seems that when uploading the new mods folder, many mods didn't transfer correctly. Thank you very much for the help.
