### ISSUE TITLE
Crashes after entering a specific area

### ISSUE THREAD

**Issue by ART33** [GTNewHorizons/GT-New-Horizons-Modpack#16272]
### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I teleported to an area in the main world where I deployed a basic pump and a combustion Generator, and then the game crashed. 
![屏幕截图 2024-05-14 143800](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22309539/9cf9215e-96fe-49e5-8438-d803cc683a84)
Crash Report: https://mclo.gs/Lnmoxlo

Unable to re-enter the world: 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22309539/9518ff4e-e635-4de2-94ca-7ec077cf92d2)
Crash Report: https://mclo.gs/t9VEwgC

The crash still exists after restoring the latest backup. Unfortunately, the backups from earlier in the day seem incompleted due to the shortage of storage space and the backups from the previous day were removed permanently due to the same reason.

It seems like world corruption after searching in issues, so I also tried to replace the following files from a new-created world with the same seed, but the issue still exists:
> level.dat
> level.dat_mcr
> level.dat_old
> session.lock

I am looking for a way to solve this issue, please let me know if more information is needed. Thanks!

### Crash Report

https://mclo.gs/Lnmoxlo
https://mclo.gs/t9VEwgC

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
Try restore from a backup. Not much we can do for chunk corruption

**Comment by Glease** [comment]
What's your seed then?

**Comment by ART33** [comment]
> What's your seed then?

Thanks, the issue is solved. Removed all corrupted chunks. Closing issue.
