### ISSUE TITLE
Wrong chemical formulae when making lithium fluoride dust

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#16288]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

Nightly 472

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Chemical formulae should be correct, and recipes should be based on correct chemical formulae.

### The Reality

Some more broken recipes with GT++ lithium compounds. [Note: this is all relating to lithium-7 compounds; I've omitted the atomic weights because they're not relevant to the recipe imbalances.]

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/948c2d49-e746-4fd1-bd80-66e302b42b05)
Making lithium fluoride dust from lithium hydroxide dust currently has the formula:
5LiOH ==> 5LiF
This takes a chemical where 1/3 of the atoms are lithium, and turns it into a chemical where 1/2 of the atoms are lithium, with a 1:1 ratio between the two, thus duplicating lithium.
This recipe should be corrected to the following recipe, which does not duplicate lithium:
"Lithium Hydroxide Dust" x3 + "Industrial Strength Hydrochloric Acid" x288 mb ==> "Lithium Fluoride Dust" x2 + "Water" x432 mb

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/1841ec42-58a9-45d6-a77f-2d0495ffc537)
Making lithium fluoride dust from lithium carbonate dust currently has the formula:
Li2CO3 ==> LiF
Similarly, this takes a chemical where 1/3 of the atoms are lithium, and turns it into a chemical where 1/2 of the atoms are lithium, with a 1:1 ratio between the two, thus duplicating lithium.
This recipe should be corrected to the following recipe, which does not duplicate lithium:
"Lithium Carbonate Dust" x3 + "Industrial Strength Hydrochloric Acid" x288 mb ==> "Lithium Fluoride Dust" x2

### Your Proposal

Change the recipes according to the corrections that I have outlined. I have also adjusted fluid quantities to preserve the existing ratios. Recipe time should probably be adjusted so that the lithium fluoride output takes the same amount of time per item as it currently does.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
was done a while back
