### ISSUE TITLE
Silverwood leaves are darkened

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#16283]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

Nightly 468

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Silverwood leaves should be their normal blue colour in a magical forest biome.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/e693d16f-67f0-4301-a67e-c9bb9e0a0b13)
This is a magical forest biome, generated by the node inside of this tree. The leaves are blackened.

### Your Proposal

Fix the visual issue. It's probably Angelica again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
have you checked how it looks without angelica?
