### ISSUE TITLE
Strange glyphs in WAILA when looking at things containing Thaumcraft aspects

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#16282]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

Nightly 468

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Waila should display aspect names normally when looking at things containing aspects.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/37e46890-b8a5-4f7a-830c-9ea4a9f072e9)
These strange glyphs appear after the aspect name whenever I look at anything containing a Thaumcraft aspect, such as alchemical furnaces or warded jars.

### Your Proposal

Remove the strange glyphs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
I blame warp :trollface:
