### ISSUE TITLE
Very long GC runs causes freezes/stutters in 2.6.0

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#16285]
### Your GTNH Discord Username

skproch

### Your Pack Version

2.6.0

### Your Server

Private

### Java Version

Java 21

### Type of Server

Ultramine

### The Reality

Everything run smoothly on 2.6.0-beta3, but after upgrading to 2.6.0 several players start experiencing long freezes (for a couple of seconds) every 5-10 minutes approx.

On 2.6.0-beta3 latest angelica was already used.

Seems like this is happens due to long GC.

### Your Proposal

This issue was created to track progress of investigating this problem in one place. If somebody also experience this and can share some info - leave a comment.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SKProCH** [comment]
If I enable `-XX:+PrintGCDetails`, so we can se that GC actually is the reason for that.

One part of gc log during one of these freezes: https://gist.github.com/SKProCH/c7048f0dd3ab30d90057a82489f2ae06

I've actually doesn't understand so much, but here is AI analysis:
> The GC(56) cycle took a long time (around 12.112 seconds).
> - Young Generation Promotion: During this GC cycle, a significant number of objects (47M) were promoted from the Young Generation to the Old Generation. This process involves copying the live objects from the Young Generation to the Old Generation, which can be time-consuming, especially when dealing with large amounts of data.
> - Major Compaction in the Old Generation: The log indicates that a major compaction occurred in the Old Generation during GC(56). This process involves relocating live objects in the Old Generation to reduce fragmentation and reclaim contiguous free space. Compaction can be a very expensive operation, especially when dealing with large amounts of data, as it involves copying and updating object references.
> - Large Object Relocation: The log shows that there were large objects (316M) in the Old Generation that needed to be relocated during the compaction phase. Moving large objects can be a costly operation and contribute significantly to the overall GC pause time.

Also, here is the allocation telemetry from yourkit (it's actually an html file, but GH doesn't allows to upload an html)
[Allocation-telemetry.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15325405/Allocation-telemetry.txt)

**Comment by chochem** [comment]
are you sure they are all on java21 like you claim? That would be unusual indeed.

**Comment by SKProCH** [comment]
Yep,
```
Java is version 21.0.1, using 64 (amd64) architecture, from Eclipse Adoptium.
```
But I'm using `ZGC` as suggested to me by someone from devs, probably this is the reason to such long full GC runs (as i discovered recently). Currently I'm testing `-XX:ConcGCThreads=12` to see, does this make any difference.

**Comment by SKProCH** [comment]
Ok, apparently this is a problem with ZGC.

Apparently 12 GB RAM allocated isn't sufficient for ZGC properly working for GTNH amount of allocation. Using `-XX:ConcGCThreads=12` (with my 8 cores/16 threads CPU) makes the freeze appears rarely, but it still appears.

Seems like ZGC trying to work without performing full GC, but seems like RAM amount is insufficient and sometimes full GC required.

I've also will test a little more and report results here.

**Comment by PlayfulPiano** [comment]
Have you tried generational ZGC over regular ZGC?

**Comment by chochem** [comment]
or just G1 (the default).
its not like you need to handle multi-terrabyte heaps

**Comment by PlayfulPiano** [comment]
> or just G1 (the default). its not like you need to handle multi-terrabyte heaps

Doesn't GZGC have better performance over G1?

**Comment by SKProCH** [comment]
I've already used generational ZGC from the start.

Also, seems like switching back to G1 resolves the problem.
