### ISSUE TITLE
Component Assembly Line missing Styrene-butadiene rubber recipe for LuV conveyor modules

### ISSUE THREAD

**Issue by VectorKappa** [GTNewHorizons/GT-New-Horizons-Modpack#16284]
### Your GTNH Discord Username

vectorkappa

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Tried to craft LuV conveyor module in Component Assembly Line (UV-Tier)

### The Reality

The only recipe available is using Silicon Rubber, there is no Styrene-Butadiene rubber recipe available:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29167842/953e50bc-e962-4e35-8447-401229c4ccc8)

### Your Proposal

Add an alternative recipe using styrene-butadiene rubber sheets

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lainiel** [comment]
Would be nice to have this fixed.
