### ISSUE TITLE
Positive calcium loop when making lithium hydroxide via lithium carbonate

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#16287]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

Nightly 472

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Chemical formulae should be correct, and recipes should be based on correct chemical formulae.

### The Reality

I've identified multiple recipes that need to be fixed due to incorrect chemical formulae.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/8d5cf230-7a6b-477e-9c3f-facc926bac3c)
"Li2CO3 + Ca(OH)2 Compound Dust" actually has the formula "Li2CO3 + CaOH2", with brackets omitted; one oxygen atom has vanished, and a compound that should contain eleven atoms per unit instead contains ten atoms per unit. The formula needs to be corrected to "Li2CO3 + Ca(OH)2", and the recipe I screenshotted needs to be corrected to the following:
"Lithium Carbonate Dust" x6 + "Hydrated Lime Dust" x5 ==> "Li2CO3 + Ca(OH)2 Compound Dust" x11

This results in the correct chemical formula, with eleven atoms on each side:
Li2CO3 + Ca(OH)2 ==> Li2CO3 + Ca(OH)2

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/ea2b0c67-7491-4570-8543-819d2d50bc6b)
This second recipe, in the dehydrator, needs to be corrected to the following:
"Li2CO3 + Ca(OH)2 Compound Dust" x11 ==> "Lithium Hydroxide Dust" x6 + "Calcium Carbonate Dust" x5

This results in the correct chemical formula:
Li2CO3 + Ca(OH)2 ==> 2LiOH + CaCO3

### Your Proposal

Correct the chemical formula of "Li2CO3 + Ca(OH)2 Compound Dust", and make the recipe corrections I have outlined.

When correcting the second recipe, the duration of the recipe needs to be doubled. This is because the current, incorrect ratio of the first recipe to the second ratio is 1:2, whereas the corrected recipes will have a ratio of 1:1. Doubling the duration of the second recipe with the aforementioned correction will mean that the same amount of energy and recipe time is still required in order to process the same starting quantity of lithium carbonate into lithium hydroxide.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
Fixed by author
![2024-10-10_22 04 50](https://github.com/user-attachments/assets/0ed572b7-f04d-44b4-b739-87dfd4c5fdac)
![2024-10-10_22 05 05](https://github.com/user-attachments/assets/ad866b17-199c-4685-a24e-ba4f7cf74194)
