### ISSUE TITLE
Another lithium hydroxide chemical formula error

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#16289]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

Nightly 472

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Chemical formulae should be correct, and recipes should be based on the correct chemical formulae.

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/60ab9ebe-7d51-4db2-8de2-cd379f8e83f2)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/0e38787b-5ddc-4a27-8597-5a18a5eeeb36)

The sequence of the two recipes screenshotted results in a massively lower amount of lithium on the output side versus the input side.

The first of the two recipes takes 16 lithium-7 dust and outputs 2576 liters of fluid lithium hydroxide. Via the second recipe, this quantity of fluid lithium hydroxide yields (17 + 8/9) lithium hydroxide dust - with an exact ratio, this is 144 lithium-7 dust in to 161 lithium hydroxide dust out. Lithium-7 dust is pure lithium, whereas lithium hydroxide is a compound in which 1/3 of the atoms are lithium.

If this process is _intended_ to be extremely lossy, then it is fine as-is. It seems likely, however (based on the fact that there are several other chemical formula errors and corresponding recipe errors with related lithium compounds), that this recipe is erroneously lossy. Assuming that this is the case, I recommend the following corrections:

The dehydrator recipe is fine as-is. The chemical reactor recipe that turns lithium-7 dust into fluid lithium hydroxide should be changed to the following:
"Lithium 7 Dust" x16 + "Water" x8000 mb + "Oxygen" x8000 mb ==> "Lithium Hydroxide [fluid]" x6912 mb

I've increased the quantity of oxygen and water needed for the recipe based on the standard that 1 bucket of each of these fluids accounts for 1 unit of the chemical, which means that the each of the 16 units of lithium-7 on the input side has exactly 1 unit of hydrogen and 1 unit of oxygen to combine with.

### Your Proposal

Implement some form of the correction I have proposed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
Fixed by author
![2024-10-10_22 10 25](https://github.com/user-attachments/assets/de4e060e-197f-47de-8630-40ba077f0d6d)
