### ISSUE TITLE
Downtiering of the advanced coke oven from mv tier to lv

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#16295]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

2.6.0

### Your Proposal

The advanced coke oven should be downtiered from the mv tier (coolant required mv mixer) to the lv tier. I propose that the recipe no longer require the ebf or coolant and instead use steel and nether bricks in an alloy smelter to make the infernal bricks then use an assembly machine to create the advanced coke oven brick blocks.

This will then put it squarely in the lv tier where it is viable for players that want to make use of automation methods such as conveyers that unlock at its tier. 

### Your Goal

The advanced coke oven converts wood to charcoal much faster then the normal coke oven but needs fuel to operate and does not produce any oil. Which means this is a specialised machine with more automation needed then the standard oven. This puts the oven at a disadvantage from the get go for players to want to use it.

### Your Vision

The vision would be that this completely forgotten mulitblock has a solid use for players that invested heavily into wood farms in lv tier to early mv. They can then process them effectively and use automation methods to transport the charcoal and wood.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
pretty normal to use it for benzene. really not forgotten in any way.
The competition is the pyro and really not the much slower regular coke oven. So I think MV makes a lot of sense.

**Comment by Reflex18** [comment]
> pretty normal to use it for benzene. really not forgotten in any way. The competition is the pyro and really not the much slower regular coke oven. So I think MV makes a lot of sense.

That makes alot more sense now that i relook into the idea of the advanced coke oven and the speed that it brings to the table. It is vastly faster then the normal coke oven which might allow a player to use steam into hv if they wished with a strong enought setup.
