### ISSUE TITLE
Buff output of initial Chronic Singularity recipe

### ISSUE THREAD

**Issue by Wargenflorgen** [GTNewHorizons/GT-New-Horizons-Modpack#16297]
### Your GTNH Discord Username

Wargenflorgen#0402

### Your Pack Version

2.6.0

### Your Proposal

Make the initial Chronic Singularity recipe (the forge hammer one) output 4-8 singularities instead of just 1
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/127348659/504ddd91-2996-4a82-9eb3-037d0aac2eff)

### Your Goal

Make it so unlucky players do not get potentially screwed over by a 1% chance and forced to wait additional hours or days to progress.

Eternity QFT is a self-sustaining loop, which once started, allows you to keep it running using a cheap recipe. In order to start it, it can take potentially days of Eye of Harmony runtime, for an 81% chance of successfully starting it. In reality you get two attempts before having to make another batch of universium nanites, and there's a ~33% chance out of the failure outcomes to get more attempts (by getting a Timepiece). All told the chance of failing twice is around 1%. Failure means going back to afking.

By buffing the output of the forge hammer recipe to 4-8 singularities, the user is given more attempts to start their QFT successfully, making the odds of failure incredibly low.

### Your Vision

Without fundamentally changing how QFT or eternity loop works, this is the easiest way to alleviate bad luck, saving people from the pain of having to wait days to finish a grind they've already done. Buffing the recipe in this way also does not make the recipe in any way desirable to use in the future, as once the Eternity QFT is started you would only ever use the plasma arc furnace recipe for chronic singularities.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Connor-Colenso** [comment]
@GDCloudstrike
