### ISSUE TITLE
Crash due to the Twiilight Forest and Pam's HarvestCraft

### ISSUE THREAD

**Issue by woshiqinjian** [GTNewHorizons/GT-New-Horizons-Modpack#16296]
### Your GTNH Discord Username

wireless_mouse.

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

create Magic Map and move to Naga
After crashed，the archive can sometimes start successfully and crash after I move. Sometimes it just cannot start.
I have tried use backups to trace back to the time before I make Magic Map, but after I drew the map and moved around it crashed too.

### Crash Report

https://mclo.gs/k8DNiyz
The mods mentioned in title is given by Minecraft.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by woshiqinjian** [comment]
My silly English level...Pardon me

**Comment by BlueHero233** [comment]
Can you update Twilight Forest to 2.6.12? this is a known issue involving the nagastone block that has already been fixed
