### ISSUE TITLE
Crash on respawning

### ISSUE THREAD

**Issue by creativforce** [GTNewHorizons/GT-New-Horizons-Modpack#16292]
### Your GTNH Discord Username

Creativ™

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Got killed, tried respawning, it took a hot second before crashing

### Crash Report

https://mclo.gs/fzRAXzl

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by anonymusdennis** [comment]
i get a similar crash but mine also appears randomly
https://pastebin.com/QTRRiB8w
also tried removing optifine and with/without angelika

**Comment by anonymusdennis** [comment]
I resolved my issue: I forgot to plug in my headphones
