### ISSUE TITLE
Aluminum nuggets can not be combined into ingots.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#16304]
### Your GTNH Discord Username

Abdiel Kavash

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Combine 9 Aluminum Nuggets into an ingot in an alloy smelter (using an ingot mold).

### The Reality

No such recipe exists, putting the nuggets into an AS with the mold anyway does nothing.

### Your Proposal

Fix the missing recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
wasnt that on purpose? With nuggets only being for dusts not ingots for early game I mean?
Can look around a bit later.

**Comment by chochem** [comment]
here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/f5465ab2ce52c110c592eb98f52350375982fc8b#diff-3b39b2900d94ef6841758ca734fd80269cbb509ba5c1402f24003f3dbea98093

**Comment by AbdielKavash** [comment]
Is there a specific reason why this was disabled? And if so, is this reason still valid today? (The commit is from 2015).

I find it odd since Aluminum seems to be the *only* ingot which can't be combined in this way. Of course I haven't checked all 200+ materials, but among the major progression ones everything else works.

**Comment by chochem** [comment]
I already gave you my guess on that. you will need to ask dream for more or look a bit around yourself.

**Comment by Dream-Master** [comment]
i guess it was added that you cant use ore berries to make alu ingots and skip ebf. But it was disabled long time ago so maybe i am wrong.

**Comment by AbdielKavash** [comment]
> i guess it was added that you cant use ore berries to make alu ingots and skip ebf. But it was disabled long time ago so maybe i am wrong.

Is it possible to make a recipe specifically only with the GT nuggets, and disable any oredict substitutions?

Specific use case that I ran into, this is not just a hypothetical: Thaumic duping of aluminum makes GT nuggets, which I am trying to combine into ingots.

**Comment by chochem** [comment]
make them into dust and smelt them :P

**Comment by Dream-Master** [comment]
This recipe was added against my concept many years later. (With the alumina change) maybe Alu processing need to be redone once again?

**Comment by greentea-cup** [comment]
Maybe tier-gate the alloy smelter recipe by something that would definitely require ebf instead of completely disabling it?

**Comment by Alastors** [comment]
yeah this has always annoyed the hell out of me

**Comment by AbdielKavash** [comment]
I will note here that aluminum ingots can be obtained as a drop from Kobolds in the TF. This combined with the crucible duping would then allow the player to skip the EBF for some time at the start of MV, as this provides a reasonably efficient early source of aluminum; especially on a server allowed to run without the player's presence.

Now I am not saying that it should *definitely* be disabled because of this; I think that the effort required to set this up is non-trivial, the essentia required for the duping is Volatus, which is not that easy to get early on at the scale required to make this viable. I also think that it would be fine to have in game as an alternative hidden progression path. The EBF will be both desired and required for many other recipes soon anyway.

Gating specifically the alloy smelter combining recipe to MV/HV seems really inconsistent to me (as is the recipe just not existing).

As an alternative, the aspect required to dupe aluminum could be changed to something less available in early game. This would not impact mid/late game setups which rely on mana beans/bees/etc. to provide unlimited essentia, but it would hinder early manual setups.

But once again, if the only reason for keeping the recipe disabled is the EBF skip, then I would not be opposed to re-enabling it and keeping it there as an alternate path for players who are willing to figure it out and invest time and resources into it. Acknowledging that, once again, aluminum is only one of the many other things that you will need an EBF for anyway.

**Comment by Alastors** [comment]
> Now I am not saying that it should _definitely_ be disabled because of this; I think that the effort required to set this up is non-trivial, the essentia required for the duping is Volatus, which is not that easy to get early on at the scale required to make this viable. I also think that it would be fine to have in game as an alternative hidden progression path. The EBF will be both desired and required for many other recipes soon anyway.
> 
> Gating specifically the alloy smelter combining recipe to MV/HV seems really inconsistent to me (as is the recipe just not existing).
> 
> As an alternative, the aspect required to dupe aluminum could be changed to something less available in early game. This would not impact mid/late game setups which rely on mana beans/bees/etc. to provide unlimited essentia, but it would hinder early manual setups.
>
> But once again, if the only reason for keeping the recipe disabled is the EBF skip, then I would not be opposed to re-enabling it and keeping it there as an alternate path for players who are willing to figure it out and invest time and resources into it. Acknowledging that, once again, aluminum is only one of the many other things that you will need an EBF for anyway.

I'm against this further proposal, I think silly things like this do actually encourage people to heavily invest in thaumcraft if we were to fix the alu nuggets, and frankly, one bypass only effecting the literal smallest tier in earlygame is hardly a bother, especially when getting people to use magic in the first place is like pulling teeth at times, even if it's consistently 100% better in moments, and like I've reiterated time and time again, magic is best enjoyed in the earlygame where you don't juse wait to IV to skip everything, missing the entire point.

**Comment by Dream-Master** [comment]
I will change the material anyways away from Alunium /Aluminum to something else to solve this gt tier issue

**Comment by Alastors** [comment]
> I will change the material anyways away from Aluminium /Aluminum to something else to solve this gt tier issue

How would that solve the Gt tier issue

**Comment by Dream-Master** [comment]
> > I will change the material anyways away from Aluminium /Aluminum to something else to solve this gt tier issue
> 
> How would that solve the Gt tier issue, it's not a problem in tier

this isnt a serious question? :trollface: Did you ever play the pack?
