### ISSUE TITLE
Glitchy screen rendering

### ISSUE THREAD

**Issue by Hide-Stampede** [GTNewHorizons/GT-New-Horizons-Modpack#16302]
### Your GTNH Discord Username

Hideawaay

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

When I go to click on serverUtils leaderboards or other menus within the mod the background of the screen gets very glitchy as suppose to being able to look at the leaderboards and other menus of serverUTil without visual issues

### The Reality

Game freaks out and becomes glitchy within the background and some of the functions do not work

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/56775343/3fec32b0-7802-4b4f-8041-7ed35060ff0b

### Your Proposal

When loading up the leaderboards I don't expect my instance to freak out the way that it does. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
Try setting enableFontRenderer to false in Angelica config or update to latest Angelica https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-alpha50

**Comment by Hide-Stampede** [comment]
Thank you. Just simply updating angelica has fixed the issue. It also apparently fixed travel anchors appearing as glowstone as was being asked about in other discord servers I am apart of

**Comment by BlueHero233** [comment]
Looks resolved
