### ISSUE TITLE
Twilight Forest Enter Dedicated Server Crash

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#16308]
### Your GTNH Discord Username

timeconqueror

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Actions

Crash upon entering Twilight Forest because of using client-side only class. Twilight Forest's version is 2.6.10-pre.

### Crash Report

[crash-2024-05-18_23.14.12-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15366562/crash-2024-05-18_23.14.12-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ruling-0** [comment]
Same crash report as https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16393
