### ISSUE TITLE
Adding a coin quest for mushrooms for early Botania

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#16317]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

2.6.0

### Your Proposal

I propose a coin quest that allows the player to trade in there botania Garden coins for botania mushrooms.

### Your Goal

I have found that I was spending a large period of time just running around the twilight forest looking for mushrooms just to start the mod proper. The other methods of obtaining the pedals would be going into thaumcraft to turn mushrooms into flowers or to get infusion which is standard HV tier for thaumcraft. Therefore having an early game way of trading some coins for mushrooms to get some starter progress would be amazing/

### Your Vision

Simply a nice way of reducing the running around time required looking for RNG based spawning for mushrooms. This would allow the player to get a foothold into botania in lv to get some mana steel for tools and a magnet.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by King65868** [comment]
Floral fertilizer is also craftable in the mixer, I don’t remember what tier it requires though.

**Comment by LazyFleshWasTaken** [comment]
the mushroom to other mushroom is an alchemy recipe. So you could turn grey shroom to white, or smth like that.
