### ISSUE TITLE
Wireless quartz fiber and passthrough power using toggle bus

### ISSUE THREAD

**Issue by ivelieu** [GTNewHorizons/GT-New-Horizons-Modpack#16318]
### Your GTNH Discord Username

Ivelieu

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

toggle bus shouldn't provide wireless power. 

### The Reality

![2024-05-20_10 34 32](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/28797826/88c4d92b-9ee3-4ab9-a958-f1274d637a5f)
Both level emitters are set to emit when below limit of 1 item, in other words, they should turn on if the network has power since there is no item storage. 

There is a quartz fiber on the multipart with the second light blue terminal. Add then remove the pink wire to the energy acceptor to kick start it, then it acts as a wireless quartz fiber which is still connected to the energy acceptor. According to the network tool, the network still consumes power but has 0 stored power and power generation. So this is what it looks like before you break the pink cable next to light blue cable:
![2024-05-20_10 56 56](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/28797826/d13910fa-f089-408d-a3e7-aa1141540111)

Adding and removing components can change the status of lime subnet between on and off. The power is all provided through the quartz fiber originally connecting the pink and light blue subnet, all other components can be removed and replaced and this quartz fiber still draws power from the energy acceptor. 

The toggle busses can be removed after the kick start and the quartz fiber will continue to provide power. Although the way they are configured, it doesn't make sense why the lime subnet depowers, and it is more strange that it can passthrough power to the red subnet without being powered itself. Removing the toggle busses makes the lime subnet power back on.

Another closely related issue, I also found that putting toggle bus and inverted toggle bus on the same block multipart facing one level emitter was able to get a subnet stuck permanently in network recalculation, but I could not figure out how to reproduce that example. Here are screenshots of how it occurred for me, removing the red cable in the image makes the network finish recalculating. You can see the colour of the storage bus and devices on the red subnet are light orange, meaning that they have the "device missing channel" status.
![2024-05-20_10 52 09](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/28797826/24ab63b3-6487-4fb8-9a73-b3b115da1152)
![2024-05-20_10 51 51](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/28797826/68127258-bdea-4bc9-a371-4ec153bac3fb)

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by psehr** [comment]
seems like similar issues are also showing in 2.7.1, wasn't able to properly setup an ME toggle for my base because of this
