### ISSUE TITLE
Boost IsaMill+Flotation Cell Regulator recipes

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#16325]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.5.1

### Your Proposal

Boost ore processing in IsaMill Grinding Machine and Flotation Cell Regulator by one or several options:

- decrease recipes time by ~4-8 times
- lower voltage by 1 tier
- increase amount of ore processed at one time (now 2 stacks)
- add parallels to these machines
- downgrade IsaMill and Flotation Cell Regulator recipes to IV

### Your Goal

IsaMill+Flotation ore processing gives rare resources, but works too slow and wants too much energy.
2 stacks of ore for 6 minutes (without overclocking) that also needs additional resources is extremely annoying.
![2024-05-20_23 31 50](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18097458/6b3d8f34-811a-4e0c-8ed4-51922e9b7eb2)
![2024-05-20_23 31 53](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18097458/efb6e624-dae8-472f-8229-afc541056cf0)

### Your Vision

Boosting IsaMill+Flotation ore processing will make this way of getting rare resources much less annoying than now.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by NotAPenguin0** [comment]
The line should get reworked entirely, not necessarily be given huge buffs randomly

**Comment by FireWarrior2** [comment]
> The line should get reworked entirely, not necessarily be given huge buffs randomly

I think nobody has enough time/resources to rework it entirely, so some buffs (not huge) can be given with these small edits.

**Comment by chochem** [comment]
there have already been around 3-4 buff rounds for this one xD
and yes, the dev team is aware they are still not great.

**Comment by chochem** [comment]
actually its probably more than that.

if you update to 2.6.0 you get another one of them ;)

**Comment by FireWarrior2** [comment]
4/4 overclocks for IsaMill and FlotationCell again

This one?

**Comment by chochem** [comment]
nah thats a bug fix, I dont even count that. though its big if you thought they dont ;)

I meant the downtiering from zpm to luv

**Comment by FireWarrior2** [comment]
As i know, it was about vacuum furnace, which is not enough for these recipes

**Comment by FireWarrior2** [comment]
Though perfect overclocks may make processing better. Waiting for 2.6.1. where angelica won't crash my world..

**Comment by FireWarrior2** [comment]
Really became better with perfect overlocks, so closing as completed.
