### ISSUE TITLE
Galacticraft Config options do not cause actual changes when done in game.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#16327]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

When changing the config, it impacts how galaticraft functions in your world. E.g., enabling both "bottom" and "left" for the oxygen HUD position should put it in the bottom left of your screen.

### The Reality

This doesn't work if done through the ingame config method.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3158887/2b969596-a105-4d67-9ab0-f8121c071c24)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3158887/061065fb-e77e-4f02-8466-8994b83f837a)
It can only change if you modify it from the config file itself.

### Your Proposal

Allow the mod config changes ingame to function.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@PlayfulPiano maybe a reload is needed?

**Comment by PlayfulPiano** [comment]
> @PlayfulPiano maybe a reload is needed?

I tried using a reload when just changing in game, and all that did was revert settings back to default.

The only way I was able to modify a setting for galacticraft core and for it to stick was if I did it within the game file, not the in game config.
