### ISSUE TITLE
Nanosuit Boots of the Traveler omni mode restricts forward speed when strafing.

### ISSUE THREAD

**Issue by mvdstam** [GTNewHorizons/GT-New-Horizons-Modpack#16337]
### Your GTNH Discord Username

maximized3353

### Your Pack Version

2.6.1

### Your Server

Private SMP server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

I expected the diagonal (strafing **and** moving forward at the same time) speed to have at least the same speed as the modified walking/running speed when omni mode is enabled.

### The Reality

Moving diagonally (strafing **and** moving forward at the same time) reduces the **forward** speed to standard (0% speed boost) walking speed.

In other words, moving orthogonally works as expected. Moving diagonally only strafes in the correct speed.

### Your Proposal

I suggest the changes introduced in https://github.com/GTNewHorizons/ThaumicBoots/compare/1.2.1...1.2.3 to be reverted, or the new omni mode to be fixed if this behaviour is indeed considered a bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by jude123412** [comment]
If i'm moving forward and try to move left or right it locks movement speed in that direction until I stop moving xD
