### ISSUE TITLE
Can't extract from magic apiary

### ISSUE THREAD

**Issue by buildcraftenjoyer** [GTNewHorizons/GT-New-Horizons-Modpack#16336]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

After a queen dies hoppers/EIO conduits should be able to pull the products, drones, and princesses out of the magic apiary.

### The Reality

Neither hoppers or EIO conduits can pull anything out of the magic apiary, from any side.

### Your Proposal

Enable item extraction. The magic apiary is an upgrade from the apiary, which already supports automation so the magic apiary should too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
lmfao, doesn't surprise me, that's an intentional custom support on our side. shit like this tends to get missed

**Comment by RaidhoSketch** [comment]
#15510
