### ISSUE TITLE
Random crash (probably EIO)

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/GT-New-Horizons-Modpack#16334]
### Your GTNH Discord Username

barsikus07

### Mod Version

1.0.0-alpha50

### Java Version

Other (Please Specify)

### Graphics Card Vendor

NVidia

### Bug Report

https://mclo.gs/9g6xoSC

Java: graalvm-22

### Mod List or GTNH Pack Version

2.6.0

### Final Checklist

- [X] I have searched the issues and haven't found a similar issue.
- [X] I have read the known incompatibilities and this is not related to one of those.
- [X] I am running an officially released version.  (Or, if I've compiled it myself I plan to fix the issue)
- [x] This issue is not related to a feature that is disabed by default - Shaders, MCPF, etc.  [They'll be enabled when they're ready for testing]

**Comment by mitchej123** [comment]
Thread saftey/concurrency issue in EIO exposed via Angelica

**Comment by barsikus007** [comment]
> Thread saftey/concurrency issue in EIO exposed via Angelica

any way to temporary fix this (like font rendering in my another issue)?

**Comment by barsikus007** [comment]
idk, is it fixed, or I removed enough conduits, but I cannot catch this bug anymore

(now I sometimes catch render crash loop, but it is very rare cause I moved to void)
