### ISSUE TITLE
Basic Rocket Engine produces to much pollution

### ISSUE THREAD

**Issue by Fanasuul** [GTNewHorizons/GT-New-Horizons-Modpack#16331]
### Your GTNH Discord Username

Fanasuul#6878

### Your Pack Version

2.6.0

### Your Server

Pricate server

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

Tried to burn excess Rp1-Fuel with moderate Pollution

### The Reality

Gut around 1000000 Pollution from burning 2,000L in 40s with equals to 25000 Pollution per second.

### Your Proposal

Reduce Pollution to the promised 250 to 2000 per second

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Fanasuul** [comment]
![Basic Rocket Engine](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95087252/f817e0a8-9e91-4af6-a1d0-188ecf48319c)

**Comment by chochem** [comment]
I think it might be going per tick instead of per second.
