### ISSUE TITLE
Change the Twilight forest materials in Tech solars to a tech based material

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#16338]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

2.6.0

### Your Proposal

I propose to change the materials of the following solars to another material

hv solar - Steel leaf to Bed rockium. HV solar is made in EV and Bedrockium is made within ev age as a tech based process that is out of the normal progression.

EV Solar - Knight Metal to Thorium 232 - This material is also made out of the normal progression and requires a chemical plant or a long processing line to make more efficiently.

IV Solar - Fiery metal to Luteium: This material is also made out of the normal progression and while it can be made in EV age to make it for solars you would need a dedicated setup for it.

### Your Goal

Tech based solars needing magical based materials always felt like a strange requirement. The complexity of the materials were also fairly low as it required hunting down a mob within twilight forest and then making an Extreme extermination chamber to spawn and obtain the materials. This was the same for all three materials for the solars.

### Your Vision

With changing it to tech based materials it would fit more thermically within the pack while challenging the players to produce different setups to automate these tech based materials.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
as one of the few people who has extensively used them, I can tell you that it fit very seemlessly and there was nothing strange about it.

**Comment by Reflex18** [comment]
> as one of the few people who has extensively used them, I can tell you that it fit very seamlessly and there was nothing strange about it.

I understand that you might consider it that way as a user of the current system. I consider it as a thermically strange that tech solars must also be created in the same kinda way as magic based solars with those material requirements.

It only makes logical sense that tech solars should embrace the requirements of complex tech based materials while magic solars get to keep there magical materials.

**Comment by chochem** [comment]
just to clarify: there is no magic involved. we are talking about a mob farm (EEC) and some salis from ore processing.

**Comment by Reflex18** [comment]
> just to clarify: there is no magic involved. we are talking about a mob farm (EEC) and some salis from ore processing.

The complexity is weak for a machine that should require enchanced complexity as per the development vision documents around the power generation method of machines. Alongside this the player is forced to venture into magical progression to find these mobs all of which is somehow tied to a tech based solar.

This kind of progression makes perfect sense for the magical based solar counterpart and in theory that line could be expanded as recursive crafting is a copout for poor design. However that is out of the scope for this ticket.

**Comment by hallucinogender** [comment]
I don't really think these Twilight Forest metals being included in solars is any weirder than ender pearls and nether stars (and related ingredients) being included in much simpler and more common technological devices. If mob farms (and, in the case of nether stars, some degree of magical effort) are either necessary or at least very convenient for much more _mandatory_ and much simpler technological devices (why can't I make a mining drill or a laser engraver without the eyes of these strange teleporting entities who live at the end of time?) then I don't see what makes it so much worse to have a similar situation for solars.
