### ISSUE TITLE
Ghost item in chest stops farm from working

### ISSUE THREAD

**Issue by mnsnownutt** [GTNewHorizons/GT-New-Horizons-Modpack#16349]
### Your GTNH Discord Username

mnsnownutt

### Your Pack Version

2.5.1

### Your Server

SP - local server setup though

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Using an Ender IO farmer with redstone conduit to chests and comparators and item collectors to shut the farmer off when items are in the chests.  I assume it would continue working without breaking.

### The Reality

Using an Ender IO farmer with redstone conduit to chests and comparators and item collectors to shut the farmer off when items are in the chests.

If I leave the server running and log the client off, occasionally when I log back on the farm will stop running and there will be a "ghost" spruce log in a chest. 
![2024-05-23_09 59 43](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31514693/2a041878-7478-4e24-b90d-d772f6d0c522)

This will not stack or pull into the drawer and then it will not allow the farmer to turn back on.  I thought it was an NBT issue so I tried to put the log in to the Name Remover, but when I shift clicked it the log simply disappeared.
![2024-05-23_09 59 51](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31514693/59834bb9-8c40-4c00-a76c-32c67dde780c)

### Your Proposal

That there would not be a ghost item showing up in the chest.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
wdym by ghost items? all those logs arent real?

**Comment by mnsnownutt** [comment]
Where did I say that?  Please read what I wrote.

**Comment by mnsnownutt** [comment]
It must be the Random Things Advanced Item Collector causing the issue.  Does it occasionally with saplings as well

![2024-05-25_07 55 27](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31514693/bb6ac336-b64e-4062-976e-563a55fb5e0d)

**Comment by BlueHero233** [comment]
Maybe try replacing the item collector with a vaccum hopper?
![2024-10-23_17 09 35](https://github.com/user-attachments/assets/85515067-13d4-440c-80f4-8124e3d864d4)

Also cant reproduce in current version, i figured a dupe glitch but no ghost items
![2024-10-23_17 15 51](https://github.com/user-attachments/assets/b543709c-3d52-44f6-8e0c-f18b3c0819b8)

**Comment by BlueHero233** [comment]
Closed, cant reproduce in current version
