### ISSUE TITLE
Tier 0 Quest causes TiC tooltip/BQ-related crash

### ISSUE THREAD

**Issue by eternalconstellation** [GTNewHorizons/GT-New-Horizons-Modpack#16347]
### Your GTNH Discord Username

unknowable._

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

Attempted to open "Upgrade 2.0" and "Your First Tool" in the Stone Age tab, resulting in a crash related to tooltips and BetterQuesting

### Crash Report

https://mclo.gs/1YclLpX

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by drakodra** [comment]
Similar issue but on a different place:

the crash is specifically linked to toolparts for some reason and i have managed to get to steam age without it triggering before.
i openend up my world and it started crashing at seemingly random times as i moved along my inventory.
started paying attention and at first it was when i was holding shift over my tinkers tools.
so i just watched out but then my old hoe broke and i wanted to make a mattock and i still had the quest for it open but any toolpart i had would immediatly crash the world if i hovered over it in my inventory
[crash-2024-05-26_18.38.18-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15448321/crash-2024-05-26_18.38.18-client.txt)
