### ISSUE TITLE
Suggestions for the FTB quests mod

### ISSUE THREAD

**Issue by evgengoldwar** [GTNewHorizons/GT-New-Horizons-Modpack#16341]
### Your GTNH Discord Username

EvgenWarGold

### Your Pack Version

2 6 0

### Your Proposal

Since the pack already has server utilities and this is a backport of FTB from new versions. It would be nice to make a backport of ftb quests. If this happens, I want to put forward my candidacy for the transfer of quests to the new mod if this needs to be done manually.

### Your Goal

New quest design
Convenient UI
Convenient creation of quests
Support for pictures, videos, gifs

### Your Vision

t’s easier to create quests, which means more people can help change quests or create new ones.
Due to the fact that it will be possible to insert pictures, videos and gifs into quests, it will be possible to create a separate tab for training beginners. The same NEI now it contains a colossal number of qol features that many people do not know about and may not find out about at all.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Quarri6343** [comment]
FTB quests in modern version is under All Rights Reserved License so you can't really do anything about it.
