### ISSUE TITLE
Quantum boots of the traveller should respect the boost key as before

### ISSUE THREAD

**Issue by illyrius-dev** [GTNewHorizons/GT-New-Horizons-Modpack#16345]
### Your GTNH Discord Username

illyriusx

### Your Pack Version

2.6.1

### Your Proposal

Previously in 2.5.1 when flying with the quantum suit/gravi chestplate and the quantum boots of the traveller you went at a slower speed in all directions until you pushed the boost key which then increased your speed. In 2.6.1 this is not the case and the boost key only applies to strafing while moving forwards and back is at the previous boosted speed.

### Your Goal

Make it so the boost key applies to forwards and backwards motion as well as the strafing.

### Your Vision

Would be more consistent with the behaviour with the base quantumsuit boots.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dark6910** [comment]
i have same issue with boots , if u activate omni mode the strafe is fixed but forward and backward is broken

**Comment by illyrius-dev** [comment]
After playing around on this some more it seems mostly to happen when the boots boost speed is set to 100%. At lower levels a boost from the quantum suit is applied. However, being able to control this as before would make flying much more controllable.
