### ISSUE TITLE
EOH progress/2 each restart

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/GT-New-Horizons-Modpack#16348]
### Your GTNH Discord Username

@dahgul

### Your Pack Version

2.6.1

### Your Server

Eta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

run EOH 
Spacetime Compression field Grade: Advanced(3)
Time Dilation field Grade: Crude(0)
Stabilisation Field Grade: Crude (0)
planet T4: IO
overclock circuit -1
34574s to finish

### The Reality

each restart progession ~*0.5-0.333
GTM +2 3.30 (2.5h before restart) :
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/35747549/1058bf91-f798-4032-9215-e5d8b869dd14)
GTM +2 14:41 (10-20 min after I first load base after restart) :
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/35747549/d4c641db-58e7-4cbb-9950-864e352d481b)
I noticed it before but I always thought that it was faill and I didn't follow the spacetime in AE then, this time it is clear that 4 thousand seconds after the finish of the simple process could not have passed.
also no spacetime or success products have been added.

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Georggi** [comment]
Not sure that it is specifically in half, but I could reproduce progress decrease of at least a minute even in single player, when rejoining the world, although it is inconsistent. Checked with maxed EOH on 2.6.1 in creative.

**Comment by sem04rus** [comment]
I also timed the same thing on 5 machines before and after the restart, here are the results
1) 1180 984
2) 1233 454
3) 980  207
4) 360  180
5) 1155 680
