### ISSUE TITLE
StackOverflowError on connecting

### ISSUE THREAD

**Issue by Oberdiah** [GTNewHorizons/GT-New-Horizons-Modpack#16367]
### Your GTNH Discord Username

oberdiah

### Your Pack Version

2.6.1

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Don't know

### Your Actions

Crash on login. This happens about 50% of the time I attempt to connect. If I repeatedly connect, I'll eventually get in.

### Crash Report

[crash-2024-05-25_15.24.49-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15443935/crash-2024-05-25_15.24.49-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Zdesl** [comment]
Add this to your Java Arguments:
`-Xss4M`
