### ISSUE TITLE
Game crashes on 2.6.1

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#16363]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Open the game and enter the world

### Crash Report

https://mclo.gs/tiVf10u

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
This is definitely not thread safe https://github.com/GTNewHorizons/EnderIO/blob/master/src/main/java/crazypants/enderio/conduit/liquid/LiquidConduitRenderer.java#L116

**Comment by KubaObeast209** [comment]
I start the world, I see my main inventory with my items, some text that usually appears on game startup and a black screen. Few seconds later it shows me a crash report.
