### ISSUE TITLE
Hyper-acceleration card for molecular assemblers

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#16369]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.6.0

### Your Proposal

Giving access to hyper-acceleration cards for the molecular assemblers cause the molecular assembler multiblock is laggy af (afaik not sure if that was ever fixed but I don't think so)

### Your Goal

We got some recipes that need assembler recipes and if we don't have it it would be nice to be able to use hyper-acceleration cards for molecular assemblers too

### Your Vision

It would make molecular assemblers better
Instead of this re-work of the molecular assembler multiblock could be nice too

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Caedis** [comment]
The MA multi is going to be deprecated.
Let us know what crafting recipes need assembler recipes so they can be added

**Comment by MaGeBZz** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15318

Already done that not all things were added up to now
Examples would be the problem with the dire table that there should be an alternative or move all recipes to assembler

But except this there are a lot of things that would be nice to have an assembler recipe like for example:
- Fluid Import/Export Bus
- 64/256/1024 and 4096 core co-processing units
- PTFE Pipe Casing
- PBI Pipe Casing
- YOTTank Casing
- Fuzzy Card (most other cards are fixed at least iirc)
- All 3 versions of the data access hatch
- Blank Patterns (the ME ones, crazy that they aren't added for now ngl lol)
- Wireless Booster (not that important but would be nice to see it as well)
- Processor Machine Casing
