### ISSUE TITLE
Casings changing texture

### ISSUE THREAD

**Issue by illyrius-dev** [GTNewHorizons/GT-New-Horizons-Modpack#16375]
### Your GTNH Discord Username

illyriusx

### Your Pack Version

2.6.1

### Your Server

Local server/SP

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Looking around the world I noticed the wrong textures being applied to some casings. They should be the correct casing for the machine.

### The Reality

Some casings appear to be partially wrong. Shifting and unshifting while looking at my compact III fusions the casings seem to change quite a lot.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/15990543/ca6435c0-ba59-4eaf-ad86-a596415ffcdf

![wrong_texture](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/15990543/e221732b-cffd-4a1b-b105-c9e3cf0369cd)

### Your Proposal

The correct casings should be shown and they shouldn't change after player movement.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
has ticket on the angelica side
