### ISSUE TITLE
Post death interactions with mobs

### ISSUE THREAD

**Issue by Thnatos0071** [GTNewHorizons/GT-New-Horizons-Modpack#16379]
### Your GTNH Discord Username

thanatos0071

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Attempting to interact with any mob, passive or agressive after dying with them still spawned. Involves Villagers, and agressive mobs,

### The Reality

Agressive mobs still attack but attacking with a sword results in an inability to kill mobs. Outside of using a bow there is no other awy for mobs to die except if they are despawned, killed by other mobs or the void. aattempting to communicate with villagers also results in this issue after dying. WAILA does not displaay the mob or it's status, but infernal mobs healthbars can still be displayed for an unkown reason. Dying again does not fix this issue, nor does restarting the client. 

### Your Proposal

Fix mobs so they can be interacted with regardles of dying. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Vrajs16** [comment]
Facing this issue, Everytime I die, I can't interact with villagers or mobs such as skeletons from grave stones (Sky only run)

**Comment by BlueHero233** [comment]
Can you explain what you mean with "interact with hostile mobs" im not sure i follow, can this be fixed by closing and opening your save?

**Comment by BlueHero233** [comment]
Closed, no return from OP
