### ISSUE TITLE
Naga quest is incompletable due to missing Nagastone task

### ISSUE THREAD

**Issue by Quarri6343** [GTNewHorizons/GT-New-Horizons-Modpack#16380]
### Your GTNH Discord Username

Quarri6343

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

t

### The Reality

![スクリーンショット 2024-05-26 170611](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/39122497/b6190592-bc81-4229-961c-e107870141b1)

### Your Proposal

t

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
@Gordon-Frohman

**Comment by Dream-Master** [comment]
the nagastone just need to be updated i guess. Maybe the block name change.
<TwilightForest:tile.TFNagastoneBody>
<TwilightForest:tile.TFNagastoneHead>
<TwilightForest:tile.TFNagastonePillar>
There is no ore dict name
