### ISSUE TITLE
Server crashes while starting up. State engine in incorrect state

### ISSUE THREAD

**Issue by Mysterious-Banana** [GTNewHorizons/GT-New-Horizons-Modpack#16386]
### Your GTNH Discord Username

gmansalternativeaccount

### Your Pack Version

2.6.1

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

I updated my server from 2.5.1 to 2.6.1 following the necessary steps in order to update it correctly. After following the steps and trying to start the 2.6.1 server the server gets close to starting and then ends with "The state engine was in incorrect state ERRORED and forced into state SERVER_STOPPED." I do not get this issue when I load the world in single player.

### Crash Report

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15449232/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by matvey19999** [comment]
Good afternoon, which kernel do you use to run the server?

**Comment by Mysterious-Banana** [comment]
I am using the latest NT Kernel to run the server.
