### ISSUE TITLE
Collision of TPV and Indium Gallium Phosphide recipes in Mixer

### ISSUE THREAD

**Issue by dimazha** [GTNewHorizons/GT-New-Horizons-Modpack#16384]
### Your GTNH Discord Username

Dart_Voider

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

I requested TPV and Indium Gallium Phosphide at the same time

### The Reality

Mixer mixed Vanadium-Gallium instead of TPV and Indium Gallium Phosphide

### Your Proposal

Change config circuit in TPV recipe to 4

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by hallucinogender** [comment]
Not that this doesn't warrant a fix, but as an interim solution based on the assumption that you are requesting this via AE2 (and good AE2 practice in general) is to enable "blocking mode" on your crafting interfaces for machines that accept multiple inputs. If you do this, the machine won't be able to accept new inputs until existing ones are processed, which will prevent _any_ conflicts like this.
