### ISSUE TITLE
Crash 1.7.10  server 

### ISSUE THREAD

**Issue by matvey19999** [GTNewHorizons/GT-New-Horizons-Modpack#16390]
### Your GTNH Discord Username

Motya#140711

### Your Pack Version

2.6.1

### Your Server

Localhost

### Java Version

Java 8

### Type of Server

Crucible

### Your Actions

I changed the server core, Thermos, Crucible, Mohist , well, only works on Vanila Forge

### Crash Report

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15453479/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by N2K2021** [comment]
You don't need to have plugins on this modpack already. Just use Forge

**Comment by matvey19999** [comment]
> You don't need to have plugins on this modpack already. Just use Forge

I need this kernel because I use self-written plugins

**Comment by mitchej123** [comment]
Crucible etc are not supported.  It's including an out of date version of fastutils that's being loaded before the one included with GTNHLib.  Update the deps on the server.
