### ISSUE TITLE
"java.lang.NoClassDefFoundError: net/minecraft/item/crafting/CraftingManager" crash on boot

### ISSUE THREAD

**Issue by Samario1** [GTNewHorizons/GT-New-Horizons-Modpack#16392]
### Your GTNH Discord Username

Samario#0

### Your Pack Version

Nightly GTNH-2024-05-27+484-mmcprism-new-java

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Actions

Loading the game

### Crash Report

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15454678/fml-client-latest.log)
Seems to be caused by an attempt to fix https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16381 ?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/a93fbe5770f987e1e47fb7f2a551c29c117a9e5b

which wasnt tagged so its not in the nightly, but you can change the config yourself
