### ISSUE TITLE
"NoClassDefFoundError: net/minecraft/client/audio/ISound" crash when entering Twilight Forest

### ISSUE THREAD

**Issue by Samario1** [GTNewHorizons/GT-New-Horizons-Modpack#16393]
### Your GTNH Discord Username

Samario#0

### Your Pack Version

Nightly GTNH-2024-05-27+484-mmcprism-new-java

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Entering the Twilight Forest portal kicks player from server and simultaneously crashes the server, leading to the player entering the portal being unable to play as they immediately crash the server upon joining

### Crash Report

[crash-2024-05-27_13.33.20-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15456687/crash-2024-05-27_13.33.20-server.txt)
[crash-2024-05-27_13.37.47-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15456688/crash-2024-05-27_13.37.47-server.txt)
Also attached is [a snippet of what happens on the client side](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15456754/clientdc.txt) just in case

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Samario1** [comment]
uh, known problem apparently, considering https://github.com/GTNewHorizons/twilightforest/pull/44#discussion_r1605891257 mentions the crashes... should i close this?

**Comment by chochem** [comment]
if its not fixed and not a duplicate, no reason to close it

**Comment by Gordon-Frohman** [comment]
Should be fixed in that PR already
More testing required though

**Comment by Lyfts** [comment]
This should be fixed in latest nightly, if not you can update to the latest pre version.
