### ISSUE TITLE
Client crashing after PC wakes up from sleep

### ISSUE THREAD

**Issue by twgecko** [GTNewHorizons/GT-New-Horizons-Modpack#16395]
### Your GTNH Discord Username

twgecko

### Your Pack Version

2.6.1

### Your Server

Private server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Actions

After PC wakes up from sleep with client open, attempting to open either the single play or multiplayer menu will cause the client to crash.

### Crash Report

[crash-2024-05-27_14.42.29-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15461298/crash-2024-05-27_14.42.29-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by TerraSleet** [comment]
Having the same issue, I cannot reproduce the bug by sending the PC to sleep for ~10 seconds, but after long periods (30 minutes or so) it will reliably cause this crash when unpausing the game
[crash-2024-06-07_14.03.45-client.txt](https://github.com/user-attachments/files/15739915/crash-2024-06-07_14.03.45-client.txt)

**Comment by boubou19** [comment]
deep hibernation mode is known to sometimes improperly restore memory, nothing we can do here.

**Comment by TerraSleet** [comment]
After some testing my crash seems unrelated to sleep mode as in OP's crash report, sorry for the faulty report
