### ISSUE TITLE
Immediate crash on startup of "gtnh-nightly-2024-05-28+485-mmcprism-new-java" instance

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#16397]
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

Nightly 485

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

I attempted to update my save from nightly 484 to nightly 485. I installed the new instance correctly and migrated all necessary data correctly, following the exact same method that I use every time I update to a new instance (which I currently do regularly, to keep reasonably up-to-date with the nightly builds).

The download for the "gtnh-nightly-2024-05-28+485-mmcprism-new-java" version of the nightly build is missing the "Natives" folder within the main folder for the instance (I re-downloaded the same zip file several hours after the original attempt to double-check that the first download didn't run into some kind of error that caused the folder to go missing; this action seems to confirm that the "Natives" folder is entirely absent from this download for the nightly build). The absence of this folder results in a near-immediate crash upon trying to start up the modpack.

### Crash Report

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/de884bc1-2e71-4364-9a20-5f6e775cf29f)

[crash-2024-05-28_04.11.39-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15464493/crash-2024-05-28_04.11.39-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@hallucinogender i check 2.6.1 and 2.6.0 and older version but i see no nativ folder. What do you mean with nativ folder?

**Comment by hallucinogender** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/107995536/9ac8672f-c390-461e-a618-b62ea31afca3)
The one that is visible in this screenshot of my nightly 484 instance. On hindsight, I think this might be an automatically-generated folder and I, not realizing this, mistook its absence as a likely cause of the broken instance.

**Comment by eigenraven** [comment]
This is an automatically generated folder indeed, the launcher creates it on first launch.
