### ISSUE TITLE
Division by zero crash - AE2 fluid crafting

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#16399]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Filled a vanilla glass bottle with water. Intended to shift-click it in the AE system via Universal Wireless Terminal. Unfortunately, I had selected the fluid terminal and not the crafting terminal. Expected the bottle to remain my inventory. However, the game crashed with a "division by zero". See paste below from fml-client-latest.log
I had hoped for "bettercrashes" to generate a full crash report, unfortunately it didn't - or is it not supposed to do this?

### Crash Report

https://pastebin.com/RFvESHx9

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
that crash report link doesnt work
