### ISSUE TITLE
Solidifier Hatch Mold Check

### ISSUE THREAD

**Issue by dagger8243** [GTNewHorizons/GT-New-Horizons-Modpack#16405]
### Your GTNH Discord Username

Dagger8243

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

I tried to craft borosilicate glass variants in solidifer hatch.

### The Reality

It crafted when its supposed to just accept molds rather than anything.

### Your Proposal

Add a mold check to the slot.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Closed by linked issue
