### ISSUE TITLE
Ability to turn off Quicksand generation

### ISSUE THREAD

**Issue by StellarHarbour** [GTNewHorizons/GT-New-Horizons-Modpack#16407]
### Your Pack Version

2.6.0

### Your Proposal

Ability to turn off Quicksand generation

### Your Goal

Villagers dying from it all the time, also it's unbearable infuriating to play, and bugged with StepUp because it doesn't counts like real block

### Your Vision

Will be great option for people who don't like it

Basically it always was here, but for some reason devs removed it in 1.7.10

Some sources about it: 
https://github.com/Team-RTG/Realistic-Terrain-Generation/issues/377
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.7.10-2.1.x/src/main/java/biomesoplenty/common/biome/decoration/OverworldBiomeFeatures.java#L8
https://github.com/Glitchfiend/BiomesOPlenty/blob/BOP-1.7.10-2.1.x/src/main/java/biomesoplenty/common/biome/overworld/BiomeGenTropicalRainforest.java#L49C9-L49C69

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
no why. GTNH loose more and more content. And btw we cant edit Bop its ARR mod and i wont.

**Comment by Dream-Master** [comment]
if someone add a config option is off by default i have nothing against it.
