### ISSUE TITLE
StepUp for better QoL 

### ISSUE THREAD

**Issue by ghost** [GTNewHorizons/GT-New-Horizons-Modpack#16402]
### Your Pack Version

StepUp

### Mod Name

StepUp

### The Mod to Add

https://www.curseforge.com/minecraft/mc-mods/stepup

### Your Reason

Enrich QoL of modpack

### Preliminary Investigation

Requires this patch for 1.7.10 https://github.com/NotTooManyItems/StepUp/issues/18

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by StellarHarbour** [comment]
> Its all rights reserved mod so it doesn't meet the "This mod is released under an open source license. Yes, this is required now." requirement. https://github.com/NotTooManyItems/StepUp/blob/master/src/main/resources/META-INF/mods.toml#L3 https://www.curseforge.com/minecraft/mc-mods/stepup

You are free to use StepUp in modpacks

**Comment by Speiger** [comment]
@chochem 
Not a big fan of a Open Source requirement. I can see why you want that, but that kinda defeats also the purpose to some degree. A Modpack on CF is designed to also support the devs who make original works, taking it over just because you disagree and dwarfing the original project doesn't make the Open Source Project that does that look good.

Ignoring that, Competition should exists and the Mod is so small that you could easily make your own version and as long there isn't something that could say: "You copied my Sourcecode" you are basically in the clear.
And you can't really claim how step assist was implemented in the first place since there are so many implementations out there that its not really claimable in the first place. Just his own exact implementation is.

**Comment by chochem** [comment]
I mean I am not in charge here. XD
Having said that, I agree with the policy. GTNH is a extremely tightly integrated modpack like a 1000 contributors and 10 years of dev time. We have fixed stuff in a lot of mods and supporrt plently for the wider 1.7.10 community. ARR mods just hinder such work.
You can develop one and thats totally fine, but we are not going to use it.

**Comment by StellarHarbour** [comment]
> @chochem Not a big fan of a Open Source requirement. I can see why you want that, but that kinda defeats also the purpose to some degree. A Modpack on CF is designed to also support the devs who make original works, taking it over just because you disagree and dwarfing the original project doesn't make the Open Source Project that does that look good. At that point you are not much better than closed source projects that basically chokehold your ecosystem.
> 
> Ignoring that, Competition should exists and the Mod is so small that you could easily make your own version and as long there isn't something that could say: "You copied my Sourcecode" you are basically in the clear. And you can't really claim how step assist was implemented in the first place since there are so many implementations out there that its not really claimable in the first place. Just his own exact implementation is.

Agreed, there's many proprietary mods in modpack with unknown license state, which basically "All rights reserved" by default as I know, on the other hand the guy who created mod and just abandoned it so we have to create our own implementation now...

**Comment by StellarHarbour** [comment]
> I mean I am not in charge here. XD Having said that, I agree with the policy. GTNH is an extremely tightly integrated modpack with like 1000 contributors and 10 years of dev time. We have fixed stuff in a lot of mods and support plently for the wider 1.7.10 community. ARR mods just hinder such work. You can develop one and thats totally fine, but we are not going to use it.

Yep, cool, unless it's Biomes O' Plenty which ARR too, whey you trying to remove it from modpack everything breaks to pieces, so such ideology not always works I guess...

**Comment by chochem** [comment]
some ARR were in the pack long before the policy was implemented and it takes a lot of work to replace them (if ever). not just BoP, but also thaumcraft and ic2 for example.

**Comment by StellarHarbour** [comment]
I don't even want to replace it, I want to remove it all together because in 1.7.10 it's impossible to turn off Quicksand generation and you didn't fixed it, most cheap and infuriating feature I ever found in any mod

**Comment by dvdmandt** [comment]
> I don't even want to replace it, I want to remove it all together because in 1.7.10 it's impossible to turn off Quicksand generation and you didn't fixed it, most cheap and infuriating feature I ever found in any mod

Which is a prime example of why we only want open source mods. There's too much depending on it for it to be removed, any existing servers would get broken worlds etc, and bugs or features like that can't be easily fixed due to it not being open. I think someone is working on a way to get rid of it, but no idea about the state of that effort.

**Comment by chochem** [comment]
> > > I don't even want to replace it, I want to remove it all together because in 1.7.10 it's impossible to turn off Quicksand generation and you didn't fixed it, most cheap and infuriating feature I ever found in any mod
> > 
> > 
> > Which is a prime example of why we only want open source mods. There's too much depending on it for it to be removed, any existing servers would get broken worlds etc, and bugs or features like that can't be easily fixed due to it not being open. I think someone is working on a way to get rid of it, but no idea about the state of that effort.
> 
> It's about modularity, you made it this way because integrated hard-coded recipes and other things I guess, I can add and remove it to my modpack without any issues

we also support plenty of mods (like AE2, NEI, lwjgl3ify, etc) for the wider community to allow such modularity. But again that is only possible because they are open source and would not be a thing otherwise.

**Comment by mitchej123** [comment]
A lot of 1.7.10 mods have been abandoned, and mod authors eventually move on - even if the mod is active right now.  We're a long running, big modpack -- we're not adding new ARR mods that the author might abandon/not fix bugs for.  

You don't have to agree with the policy, but it's not changing.  You're free to add whatever mods you'd like locally.  Existing ARR mods have been grandfathered in unless someone ambitious writes a clean room drop in replacement :)

Also being FOSS doesn't preclude someone from distributing via CF and maintain artistic control of the mod.

**Comment by StellarHarbour** [comment]
> A lot of 1.7.10 mods have been abandoned, and mod authors eventually move on - even if the mod is active right now. We're a long running, big modpack -- we're not adding new ARR mods that the author might abandon/not fix bugs for.
> 
> You don't have to agree with the policy, but it's not changing. You're free to add whatever mods you'd like locally. Existing ARR mods have been grandfathered in unless someone ambitious writes a clean room drop in replacement :)
> 
> Also being FOSS doesn't preclude someone from distributing via CF and maintain artistic control of the mod, we want assurances that we'll be able to fix bugs whether or not the author is available, and not having to resort to ASM/Mixins all the time.

I can't add mods locally because BOP is unbearable to play with at 1.7.10

**Comment by mitchej123** [comment]
You're free to remove it or swap it out with whatever you want locally.  There might be some breakage if the items are used in recipes, but you can fix that.

We prioritize backwards compatibility with existing worlds, and removing BOP without a drop in replacement isn't feasible, so Mixins the are only option right now.

**Comment by dvdmandt** [comment]
> I can't add mods locally because BOP is unbearable to play with at 1.7.10

So why did you want to add StepUp to the pack at all if you can't even bear to play it?

**Comment by StellarHarbour** [comment]
> > I can't add mods locally because BOP is unbearable to play with at 1.7.10
> 
> So why did you want to add StepUp to the pack at all if you can't even bear to play it?

Because I added it by myself to be able to play game and found out that Quicksand is there to ruin it

**Comment by mitchej123** [comment]
Add a mixin to remove it, or prevent it from spawning, or be replaced by another block ;)

**Comment by StellarHarbour** [comment]
I dont know anything about mixins, and there's no way to stop it from spawning because there's no config in 1.7.10 for some reason, while it was in versions before and after

**Comment by mitchej123** [comment]
Exactly why we no longer allow new ARR mods to be added.  It's probably a trivial(ish) mixin for anyone familiar with them....

**Comment by Speiger** [comment]
Yeah if moddevs want to leave and their mod is closed source it sucks then if you want to continue said mods.
Though this can also be solved without a FOSS requirement IMO.

For one, there could be special licenses made just for GTNH in this example that allow continued development or taking over of the project, even if there are special conditions behind it.
Second projects could be recreated as needed.

My point was more of a "FOSS Requirement" on Actively developed projects of people who have closed source software, seems a bit offputting and simply get rejection from the developer itself to be included.

And i know you guys have a few projects from me in there too, which are closed source.
So hearing a FOSS requirement being added is offputting to put it lightly ^^"

On the other hand I am actively maintaining projects even if it takes time and i am accessible so i don't worry to much here ^^"

Lets put it this way its a delicate topic and both sides want assurances ^^"

**Comment by Cleptomania** [comment]
> @chochem Not a big fan of a Open Source requirement. I can see why you want that, but that kinda defeats also the purpose to some degree. A Modpack on CF is designed to also support the devs who make original works, taking it over just because you disagree and dwarfing the original project doesn't make the Open Source Project that does that look good. At that point you are not much better than closed source projects that basically chokehold your ecosystem.

Would like to mention that if there is a mod we want in the pack that is Open Source and is still actively developed for Minecraft 1.7.10, then we will gladly use the upstream work and contribute to that, the fact is that there are extremely few mods that fit that description today. With no active upstream all we can do is maintain our own fork, and if a mod isn’t open source it removes the ability for us to maintain it past the point that the original author is no longer interested in doing it.

**Comment by mitchej123** [comment]
> Yeah if moddevs want to leave and their mod is closed source it sucks then if you want to continue said mods. Though this can also be solved without a FOSS requirement IMO.

Sure, we'd examine an exception on a case by case basis, but it's a good default rule/starting point IMHO.

> For one, there could be special licenses made just for GTNH in this example that allow continued development or taking over of the project, even if there are special conditions behind it. Second projects could be recreated as needed. Edit: Those assume the project is not FOSS and the developer doesn't want to open source the project.

We've got a few mods we've forked, that were already in the modpack, with permission from the author for bug fixes.  We'd also be ammenable to an abandonware license -- limited rights unless abandoned for X months... then <fallback license> -- I believe there's one of those from glee8e.

> My point was more of a "FOSS Requirement" on Actively developed projects of people who have closed source software, seems a bit offputting and simply get rejection from the developer itself to be included.

There aren't many actively developed 1.7.10 projects that we'd consider putting in at this point; it's not a hard and final rule but it's a good starting point and the reasons behind it are more important than the implementation.

> And i know you guys have a few projects from me in there too, which are closed source. So hearing a FOSS requirement being added is offputting to put it lightly ^^"

Most of those are grandfathered in, we'd have to evaluate a new one if it were brought up.
 
> On the other hand I am actively maintaining projects even if it takes time and i am accessible so i don't worry to much here ^^"
> 
> Lets put it this way its a delicate topic and both sides want assurances ^^"

I agree, and we'd be willing to have those discussions with any authors, but we're not going to compromise on it for someone who isn't the author and is proposing a new mod addition.

**Comment by Speiger** [comment]
@mitchej123 reasonable terms IMO.

**Comment by Speiger** [comment]
Anyways, sorry for derailing the conversation a bit ^^"
But it gave some valuable but assuring insight into the project.

**Comment by huntindeed** [comment]
> We already have a number of items that allow a player to do this, adding this mod would mess with balance.

Which items allow this?

**Comment by FourIsTheNumber** [comment]
> > We already have a number of items that allow a player to do this, adding this mod would mess with balance.
> 
> Which items allow this?

Boots of the traveler, sojourner’s sash, like a dozen others

**Comment by huntindeed** [comment]
> > > We already have a number of items that allow a player to do this, adding this mod would mess with balance.
> > 
> > 
> > Which items allow this?
> 
> Boots of the traveler, sojourner’s sash, like a dozen others

Modpack called GT, can I get name of at least one Tech endgame item that does this? Or adding step assists without items will break balance only because there's bunch of junky magic items there?

**Comment by FourIsTheNumber** [comment]
> Modpack called GT, can I get name of at least one Tech endgame item that does this? Or adding step assists without items will break balance only because there's bunch of junky magic items there?

Magic isn't junk, it's part of the pack. Don't want to do it, don't get the stuff it offers.

Anyways I think the DE armor has it as does enderio.

**Comment by Caedis** [comment]
Piston Boots and the new (2.8) GT Modular Armor have step assist
