### ISSUE TITLE
[ThaumicBoots] Diagonal running with/without omnidirectional toggle is not at a 45° angle.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#16414]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

When running in a diagonal direction using a ThaumicBoots-supported pair of boots, running at a 45° angle would match a similar angle and speed, akin to the below 2.6.0 clip (nano boots of the traveller are used):

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3158887/0d64ad5e-6094-477b-b292-f70eeb00b4eb

### The Reality

When using 2.6.1 and having access to the new ThaumicBoots configurations, sprinting diagonally no longer has the same angle and speed level at a 100% modifier. This is understandable when the omnidirectional toggle is disabled, but not when the toggle is enabled.
Below is a clip in 2.6.1, using ThaumicBoots 1.3.5 (latest), where I am sprinting at the same angle using nano boots of the traveller, with the omnidirectional toggle turned on & off (potentially sorry about the compression):

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/3158887/6cd2fefe-a40d-4788-9106-d27a651fdf99

Note how unlike the 2.6.0 angle which was near identically 45°, with omni disabled it follows what is closer to a 15° angle, and with it enabled it follows what is closer to a 75° angle (relative to walking straight forward).

### Your Proposal

While the omnidirectional toggle is turned on, the mechanisms for moving at a 45° angle should match the movement done in 2.6.0 (while still affected by thaumicboots' speed modifier keybind). With it off, it could either be kept the same as it is now or maybe give it a slight horizontal boost so it's closer to a 20° or 30° angle instead of a 15° angle.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment]
Not a bug, merely a relic of how Minecraft’s limited amount of support for this sort of movement works

**Comment by PlayfulPiano** [comment]
> Not a bug, merely a relic of how Minecraft’s limited amount of support for this sort of movement works

Oh, so basically it's due to how thaumicboots allow for speed modulation? Well that sucks.

**Comment by Alastors** [comment]
Sure does, it sure does suck

**Comment by Darkenlord1** [comment]
Strafing literally suck with or without omnidirection
Nanosuit boots of the traveller experience in 2.6.1:
https://youtu.be/TFXJEkpu3rg

**Comment by PlayfulPiano** [comment]
this doesn't need to be bumped it was fixed because alastor is a magician (fitting)
