### ISSUE TITLE
Vanilla chests lighting flickering after JABBA code change

### ISSUE THREAD

**Issue by leafi** [GTNewHorizons/GT-New-Horizons-Modpack#16410]
### Your Pack Version

2.6.1, Nightly 486

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

In 2.6.0, I could look around my base without lighting flickering on vanilla chests.

In 2.6.1 and in Nightly 486, there are lighting problems. Substituting an old JABBA jar restores expected behaviour.

### The Reality

Nightly 486, all mods left as-is, just my 2.6.0 world transplanted:

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/2166555/82385dcb-7cba-431f-afc7-975986d6a714

I bisected the mods/ folder between 2.6.0 and 2.6.1, and determined JABBA changes were the cause. (Makes sense - I use the barrels.)

Nightly 486, but with JABBA reverted from 1.4.2 to the 1.3.3 version shipped with pack ver 2.6.0:

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/2166555/158c630c-d4ae-420b-b332-84c5af72164a

(Taking these captures on Wayland on Linux was amazingly painful.)

### Your Proposal

Presumably https://github.com/GTNewHorizons/Jabba/pull/30 is the cause - there has been very little code change in JABBA.

That PR was made to address https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15563 . (I haven't put ores in any barrels in my Steam Age base yet.)

Please fix the code so it does not break lighting on vanilla chests. Or, well, my base, I guess.

My base does **not** use any pipes from the Logistics Pipes mod (AFAIK).

If you'd like my save (~ 260 MiB), tell me and I'll see if I can upload it somewhere along with coords.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leafi** [comment]
Let me try to fix the videos...

**Comment by Quarri6343** [comment]
Tested in dev env, The bug did not occur without Angelica
