### ISSUE TITLE
IC2 crops breaking despite me not running

### ISSUE THREAD

**Issue by godlyvex5** [GTNewHorizons/GT-New-Horizons-Modpack#16427]
### Your GTNH Discord Username

godlyvex

### Your Pack Version

GTNH 2.6.0

### Your Server

SP (using exaroton server host)

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Walked near IC2 crops and expected them not to break. People in the discord have said they break if you run near them, so I specifically am not doing that to avoid any breakage. I also am not wearing any armor or other equipment aside from an adventure backpack.  https://i.imgur.com/vsVRiBZ.png  this image should prove that well enough. The only item I was holding was the unstable mattock you get from one of those quests.

### The Reality

Crops were broken as if I had jumped on them. 

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/35678328/0a66a89e-efaf-4b57-af28-560738bc4906

As you can see in this video, all I did was walk near the crops, then stand still for a moment. It's lucky that this happened right after I started recording, as it's been really inconsistent to reproduce. At this moment I am the only person on the server, but in the past other people have had the same thing happen on my server. It only happens with IC2 crops as far as I know, we have not had this happen a single time on tilled dirt without a crop stick. Anecdotally I have been able to reproduce this more often right after tabbing back into the game, but that is not the sole cause, as things have broken without needing to do that.

### Your Proposal

IC2 crops should only break if you jump or run on them, not from just walking on them. Or at least, if they are going to do that, they should do it consistently, not 1 in every 100 times you do it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by godlyvex5** [comment]
I'll add that others in the GTNH discord have said things like "IC2 crops break if you breathe on them" which seems to suggest that others have had issues with IC2 crops breaking for no reason. Due to the inconsistent nature of this bug it's hard to say exactly what's going on, but hopefully me reporting it is the first steps to something being done.

**Comment by ReaganAR** [comment]
Can you link to the message where you uploaded (if in the GTNH discord) or upload it to a different site as discord CDN links expire now and the video is inaccessible

**Comment by godlyvex5** [comment]
https://youtu.be/iIfyO6EFnLk

Here is a video of more ic2 crops breaking from mere walking. This is not the same video I uploaded before, but is even more compelling evidence as it's clearly not just a fluke, the crops are constantly breaking as I walk over them. Usually this does not happen so constantly, usually a mere one or two crops will break.

**Comment by Cardinalstars** [comment]
It'd be very nice if we could have something that would just disallow the easy breaking or just walking breaking at all. IMO all it adds is tedium and really nothing more. IC2 crops are already cancerous.

**Comment by godlyvex5** [comment]
> It'd be very nice if we could have something that would just disallow the easy breaking or just walking breaking at all. IMO all it adds is tedium and really nothing more. IC2 crops are already cancerous.

I agree, I've been grinding at these crops for 10+ hours and it's unimaginably frustrating for your only copy of a rare crop to break for seemingly no reason, just because you walked near it, and it doesn't even have a chance to drop a seed. What does this add to the game other than frustration and heartbreak? Given how frequently this occurs I'm not sure it's a bug, but bug or not, this just shouldn't be in the game.
