### ISSUE TITLE
Crash when right clicking Railcraft boiler in NEI multiblock preview

### ISSUE THREAD

**Issue by Quarri6343** [GTNewHorizons/GT-New-Horizons-Modpack#16421]
### Your GTNH Discord Username

Quarri6343

### Your Pack Version

v2.6.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

title

### Crash Report

https://mclo.gs/ZqgIuby

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
can confirm. right-clicking the pressure boiler tank specifically

**Comment by chochem** [comment]
@Glease you might have some idea what is happening

**Comment by Glease** [comment]
I'm out on vaction - will check later

**Comment by Blubstr** [comment]
I guess "Don't do that."

https://mclo.gs/KcdCWuV
