### ISSUE TITLE
Multi-Smelter lags

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/GT-New-Horizons-Modpack#16423]
### Your GTNH Discord Username

ipielover

### Your Pack Version

2.6.1

### Your Server

Delta

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

N/A

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/13598309/d2b1e3b0-0d85-41f6-a2c0-586a57e5ec42)

### Your Proposal

Enable batch mode feature for Multi-Smelter.
1-ticking is bad for server

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
already fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2604
