### ISSUE TITLE
Buff MK6 naquadah based fuel and tweak the space/time costs in Large Naquadah Reactors

### ISSUE THREAD

**Issue by srdr2k3** [GTNewHorizons/GT-New-Horizons-Modpack#16425]
### Your GTNH Discord Username

@srdra

### Your Pack Version

2.6.0

### Your Proposal

Naquadah Fuel at MK5 and MK6 are considered a meme by many and rightly so, the rates are just horrible.
This is even more true for MK6 which is just a joke in its entirety.

Currently, Naquadah Fuel MK6 recipe when overclocked needs 17 DTPFs running shirabon at base voltage, not even counting the Spacetime DTPFs that would be needed for both shirabon and the efficient MK5 fuel recipe and the fact that spacetime needs even more passive DTPFs running Infinity and other stuff for residue doesn't help at all.

Adding on, one refinery running MK6 fuel needs 5 running MK5 which needs 10 running MK4 which in turn needs 40 running MK3.
This is calculated with the fact that all recipes below MK6 are done via the more efficient route. 
This means you need 56 fuel refineries and 125 LNRs with each their separate inputs **JUST** to make 11T eu/t...
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/99605300/e7bccbe0-964f-47ed-8f03-ead5de64cc72)

Of course, this was calculated with Large Naquadah Reactors running with 16x speed and 2.75x efficiency.

Also the "more efficient" recipe for MK6 is actually worse EU/t-wise. It needs T4 coils to run and is base 12 seconds, wherein the other recipe is also base 12 seconds with only needing T3 coils. This lowers the power generated from one refinery to around 8T EU/t while also needing post-EOH materials, due to no overclocks from the refinery.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/99605300/683e8466-8e83-4f46-a53e-4061761996cd)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/99605300/f9030d6d-f242-4316-a877-e0af86f69ecb)

Now the other issue at hand, LNRs boosted with space/time.
On the surface, the 64x more speed and 5x more efficiency sounds pretty nice. It would lower the LNR count from 125 to 31.25 and up the total power gen to 20.7T eu/t
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/99605300/6701dae2-66ad-4f67-a03d-4f4fcabf7a4a)
But the LNR uses 1000L/s of coolant (Time/Tachyon Rich Temporal Fluid), which amounts to at least 1562.5L/t of spacetime just to boost all the reactors. One DTPF producing spacetime at 128B EU/t makes 230.4/s of spacetime. 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/99605300/92d1b762-40ba-4953-a19f-d33e3a1c36d3)
I would understand if the EOH tiers before T7 actually gave out spacetime at a reasonable rate, but here is what the calculator has to say.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/99605300/cf658df9-a167-457d-b690-71f07175e48c)
This is, as far as I know, the last recipe you can run before EOH turns power positive.

My proposals are:
- Lower the Shirabon cost for MK6 substantially.
- Lower the time for the more efficient MK6 recipe to 9 seconds, which would have the power generated be the same but at a much lower shirabon cost.
- Add a special case for Tachyon Rich Temporal Fluid/Time cooled LNRs to only use 20L/s per reactor, just like the Spatially Enlarged Fluid/Space, and maybe up the efficiency it provides. 
- Maybe add a one-step recipe for MK4 naqfuel.

### Your Goal

Give an actual good alternative to the Dyson spam, by not having the player wait for days to build up power just to run one EOH recipe.

### Your Vision

Stated above with the goal. Alternatives are always good, they just need to be able to compete.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by srdr2k3** [comment]
I took a look at the code after being made aware and Tachyon Rich Temporal Fluid seems to already have a special case in LNRs, it's just not documented anywhere at all. 

Other than that the issue with mk6 naqfuel still stands, all discussion or criticism is welcome. The more I set this up in my world, the more absurd it becomes. It's just sad that a multi available in UIV generate more power way way way easier than a powergen method in UMV.

I really wanna see dyson have not just a viable competitor but also something that players actually want to set up in their bases.
I saw so many players go up to MK4-MK5 and then swap to dyson because it was so tedious to continue scaling up for MK6.

**Comment by comet13579** [comment]
I think that the MK VI recipe is only viable after having access of the shirabon QFT recipe
That should be what they are expecting

**Comment by NotAPenguin0** [comment]
Correct, but the Shirabon QFT recipe does not unlock until T7 EoH, after which the EoH is a much better power generation method than naqfuel, so it comes a bit too late.

**Comment by fluffle** [comment]
My thoughts for this discussion; apologies for the wall of text:

The balance is definitely off here. Dyson power is almost free, which makes it hard for any other powergen at the same tier to compete. But asking players to spend huge amounts of lategame materials to generate power is too far in the other direction and pretty much an insurmountable disincentive for filthy casuals like myself. The later tiers of Naq fuel also feel a bit like lazy game design to me, because they are simply "take the previous tier's fuel and put more power and some expensive materials into it".

For me, Naq fuel 1-3 was fun because it provided a more interesting alternative to plasma generator spam. You needed to build and scale some multi-step passive production lines *with different machines* (looking at you, celestial tungsten plasma). You didn't need to spam too many multiple copies of the same machine to generate enough power to keep things going. Naq 4 I simply ignored until I needed it for Naq 5, and Naq 6 was never going to happen because at that point switching to Dyson power is the only reasonable choice for someone with 20h/week to play the game.

I think there are two parts to making this more balanced.

1. Dyson running costs need to be increased.
    * The drones are OK at the moment, IMO. I think the inclusion of materials that require an EEC to produce was neat -- having to figure out the best way to get steeleaf and fiery blood was an interesting challenge. No-one is going to completely passive a craft of this complexity, but the level maintainer trivializes keeping them in stock for the amounts currently needed.
    * It might be interesting to introduce QFT tiering materials into the construction of these drones. Thematically, superconductor rare earth composites and self-healing adhesives would be pretty useful for a dyson swarm and having a sink for these materials would be useful.
    * The other major running cost of the Dyson, gelid cryotheum, is pretty trivial to meet. I think this is where something more interesting could be done, perhaps a 3-4 step chain that uses gelid cryotheum, super coolant and it's byproduct crushed ice, oganesson, and perhaps small quantities of energized tesseracts or spacetime and some other "rare" (i.e. not produced by SE) things.
    * A couple of tiers of coolant could change Dyson power outputs in the same way that works for the Naq reactors.
    * Computation requirements are also an interesting twist, but the current multi design means you can build one QC for 4 Dysons with wall sharing, again trivializing the cost. I don't have any clever ideas here that are not hideously expensive in terms of dev time, e.g. making players build a "datacenter" for their QCs to reside in that has additional cooling / material consumption reqs.
2. Naq 4-6 should be reworked a little, so that instead of just adding expensive lategame materials directly, players have to add smaller amounts of these materials via processing chains that are more interesting than "spam 17 shirabon DTPFs".
    * Naq 3 is pretty good here IMO, with the effort required to make the high density uranium / plutonium and the outputs of the naq fuel line.
    * In a similar vein to Naq 3, each subsequent tier of fuel could have an "additive" fluid and some more "high density" materials, that have short processing chains consuming some smaller amounts of high-tier materials alongside significantly larger amounts of stuff that can be more easily acquired. Again this could be a good place to consume QFT tiering materials, or new QFT outputs with matched tiering -- Mk4 == QFT2, Mk5 == QFT3, Mk6 == QFT4.
    * The reduction in fuel output per tier could be relaxed somewhat, so that there's not such a need to scale early tiers to support later ones. On this note I don't think that having two recipes per tier really adds all that much, especially given the current recipe design choices. I think a single recipe for each fuel tier, with a straight 2:1 reduction from the last tier, and a requirement for the next tier of field restriction coil, would probably be enough -- as long as the recipe for each tier's fuel has more interesting stuff going into it.

Thank you for coming to my TED talk :-)

**Comment by fluffle** [comment]
I started writing up rough ideas I had while thinking about the first part of this. Let me know if you'd like me to do more work, either creating spreadsheets or dev effort. I'm mostly waiting on stargate crafts rn so, y'know, I have a little spare time.

- Cap Dyson power output at 100% (60%?) when cooled with Cryotheum.
- Add new coolant "black-body radiation sink" (I am bad with names)
    - 1 bucket/s of this coolant unlocks full Dyson power.
    - Recipe:
        - 1x Quantum-entangled black body nanoparticles
            - PLE with Quantum Anomaly lens:
                - Outputs: 10x quantum-entangled black body nanoparticles
                - Inputs: 1x naquadria supersolid dust + 144mb spatially enlarged fluid => 14.4mb/s spatially enlarged / 28.8mb/s spacetime per Dyson
                - Power: 10s UEV => 1 PLE at UEV per Dyson (fewer with LPF ofc)
            - Macerator:
                - Outputs: 4x Naquadria super-solid dust
                - Inputs: 1x naquadria black-body supersolid -> 4x naquadria supersolid dust
                - Power: 2.5s UIV => 1 Macerator at UIV can support 16 Dyson
    - 1000mb Temporally-liberated Coolant
        - Mixer (DTPF maybe but thematically problematic)
          - Outputs 10000mb coolant
          - Inputs:
              - 2 crushed ice (byproduct of super coolant)
              - 2 Icy needle (EIG for witchery crop, because thematic fit so why not, if you want to trololol use Crystallos from blood magic instead but that will make people scream)
              - 5000mb gelid cryotheum (probably bees)
              - 1000mb liquid nitrogen (or oxygen or helium, vacuum freezer)
              - 2000mb super coolant
              - 2000mb grade 5 purified water (trololol, requires T4 QFT + water catalyst but uses the least-useful stuff)
              - 144 mb tachyon-rich temporal fluid (to use up the byproduct from spatial for the nanoparticles
            - Power: 10s UEV => 1 Mixer at UEV per Dyson (modulo multiblock mixer discounts)
   
Dev costs: a few recipes, 2 new liquids and a new item. I thought about basic balance w.r.t. large naq reactor running costs, but didn't really try for balancing against naq fuel, with the assumption that those would be reduced anyway.
