### ISSUE TITLE
Logistics fluid insertion pipe is limited

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#16434]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

When using the fluid insertion pipe i expected to be able to power steam mv turbines from the input by using a steam valve to push fluids into the pipe.

### The Reality

The pipe itself could bearly output much more then the fluid extraction pipe even thought it is intended to transfer as much as the gt pumps push into it.

### Your Proposal

The fluid insertion logistics pipe needs to be fixed to handle the amount of fluids that gregtech demands.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Atlantis102** [comment]
Hello, I am using google translate.

Max size fluid container ~5 bucket. This is not a bug. Recommend using "speed upgrade" 2*64 stack

**Comment by Reflex18** [comment]
> Hello, I am using google translate.
> 
> Max size fluid container ~5 bucket. This is not a bug. Recommend using "speed upgrade" 2*64 stack

Thankyou.

That did make a marked improvement since it appears that the pipe only sends more fluid once the fluid hits the destination.
