### ISSUE TITLE
Add Sound Reloader

### ISSUE THREAD

**Issue by JL2210** [GTNewHorizons/GT-New-Horizons-Modpack#16432]
### Your GTNH Discord Username

jl2210

### Your Pack Version

2.6.1

### Mod Name

SoundReloader https://www.curseforge.com/minecraft/mc-mods/sound-reloader

### The Mod to Add

This mod allows you to change your sound device without reloading all resource packs with F3+T.

### Your Reason

This saves around 10s of time when e.g. switching from headphones to internal speakers.

### Preliminary Investigation

Works great even with lwjgl3ify and Angelica. The keybind needs to be rebound, as it's set to P by default. \*The mod is released under the Unlicense but the 1.7.10 branch technically doesn't have the license file

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Quarri6343** [comment]
We already have F3 + S which reloads sound.
It was removed in 1.9 so you might don't know.
https://minecraft.fandom.com/wiki/Debug_screen

**Comment by JL2210** [comment]
Thanks, forgot about that. Is there something like f3+q that shows all the key combos?

**Comment by Quarri6343** [comment]
I have searched around discord and github but couldn't find one.
I think it is difficult to list all of them since F3+ has no unified registration method.

**Comment by JL2210** [comment]
I'll close this then
