### ISSUE TITLE
[Electro-Magic Tools] Changing Compressed Solar Panels to GT's EU base 4 rates.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#16437]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.6.1

### Your Proposal

Instead of requiring **8** compressed panels of the previous tier to make the next compressed panel for a **25% EU** bonus, you now require **6** compressed panels of the previous tier to make the next compressed panel for a **33% EU** bonus (rounded). Also, instead of needing only 1 plate for double and single compressed panels, you need 3 plates (matching with the infusion recipes for 3x+ compressed panels).
Specifically, you can see the changes below:

| Panel | Old Raw Cost | Old EU/t    | Old Base EU/t | Old Output Rate EU/t |   | New Raw Cost | New EU/t   | New Base EU/t | New Output Rate EU/t |   | Δ in Raw Cost | Δ in EU/t | Δ in Base EU/t |
|-------|--------------|-------------|---------------|----------------------|---|--------------|------------|---------------|----------------------|---|---------------|-----------|----------------|
| 1x    | 8            | 10          | 1.25          | 1A LV 3.2t (4t)      |   | 6            | 8          | 1.33          | 1A LV 4t             |   | -25%          | -20%      | +6.67%         |
| 2x    | 64           | 100         | 1.56          | 1A MV 1.28t (2t)     |   | 36           | 64         | 1.78          | 1A MV 2t             |   | -43.75%       | -36%      | +13.78%        |
| 3x    | 512          | 1,000       | 1.95          | 1A EV 2.05t (3t)     |   | 216          | 512        | 2.37          | 1A HV 1t             |   | -57.81%       | -48.8%    | +21.36%        |
| 4x    | 4,096        | 10,000      | 2.44          | 1A LuV 3.28t (4t)    |   | 1,296        | 4,096      | 3.16          | 2A EV 1t             |   | -68.36%       | -59.04%   | +29.45%        |
| 5x    | 32,768       | 100,000     | 3.05          | 1A ZPM 1.31t (2t)    |   | 7,776        | 32,768     | 4.21          | 1A LuV 1t            |   | -76.27%       | -67.23%   | +38.08%        |
| 6x    | 262,144      | 1,000,000   | 3.81          | 1A UHV 2.10t (3t)    |   | 46,656       | 262,144    | 5.62          | 2A ZPM 1t            |   | -82.20%       | -73.79%   | +47.29%        |
| 7x    | 2,097,152    | 10,000,000  | 4.77          | 1A UIV 3.36t (4t)    |   | 279,936      | 2,097,152  | 7.49          | 1A UHV 1t            |   | -86.65%       | -79.03%   | +57.11%        |
| 8x    | 16,777,216   | 100,000,000 | 5.96          | 1A UMV 1.34t (2t)    |   | 1,679,616    | 16,777,216 | 9.99          | 2A UEV 1t            |   | -89.99%       | -83.22%   | +67.58%        |

### Your Goal

The main goal behind this proposal is to keep compressed panels within the GT EU base 4 voltage system. The fact that it slightly improves the base EU / t rate per 1EU/t solar panel is a nice side benefit. But you'd need to build more higher tier panels to compensate, as the EU/t rates are decreased.

### Your Vision

A big issue with the current formula is that compressed solar panels are base 10 with its generative output. I.e., 10EU/t, 100EU/t, etc. When GT at large is using a base 4 number system on the '2' digit (aka 8 = 20, 32 = 200, 128 = 2000, 512 = 20000, etc.). Meaning when outputting compressed panels, it doesn't cleanly output within the EU transferring system. Things like 10EU/t outputting at 1A LV means it takes 3.2 ticks to output 1A. Since ticks are literally the smallest time interval within minecraft, requiring decimal amounts of ticks gets annoying for users who want to calculate specific amounts of EU for their solar panel system.

Changing it to the proposed ratios would fix this issue, keeping it within the GT base 4 voltage system. 1x panels would output 1A LV every 4 ticks exactly, with no decimal amount extra. 2x panels would output 1A MV every 2 ticks, 3x panels would output 1A HV every tick, etc. etc.

Plus, when considering the multipliers from the infused panels, the numbers in the proposal can more easily and cleanly get cut into the GT base 4 EU system as well.

Edit: Note this might require some adjustments on what plates are used per compressed panel, as well as changing how the quest requirements work. Also, this would open up the ability to add in 9x (1A UMV) and 10x (2A UXV) compressed panels as an option for later EU voltage tiers.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by PlayfulPiano** [comment]
.

**Comment by PlayfulPiano** [comment]
Could we possibly review this as a potential balancing change for 2.7.0 before the feature freeze @Dream-Master ?

There were discussions in the past about having compressed solars' EU/t rate get nerfed in general, and I figured if that eventually is planned, this would be a good way to do so. Not to mention as per mentioned in the OP, it would allow compressed solars to integrate a lot better with GT's voltage system being in base 4 and not base 10.

**Comment by boubou19** [comment]
i'm against. It's a nerf for the sake of it. Those who start the octuple challenge have to overcome infra, lag, and magic. What you suggest is purely obliterating a fun challenge. Remember that one octuple is nice and all, but you need several tons of them to get anywhere in the endgame. I guarantee you that you'll prefer to use other power gens at these tiers as those are more efficient.Octuple are a non issue. Same applies for lower compressed solar panels, given powercreep happens around LuV.

**Comment by PlayfulPiano** [comment]
> i'm against. It's a nerf for the sake of it. Those who start the octuple challenge have to overcome infra, lag, and magic. What you suggest is purely obliterating a fun challenge. Remember that one octuple is nice and all, but you need several tons of them to get anywhere in the endgame. I guarantee you that you'll prefer to use other power gens at these tiers as those are more efficient.Octuple are a non issue. Same applies for lower compressed solar panels, given powercreep happens around LuV.
In terms of actual material costs, the amount of raw solar panels you need to reach pre and post change EU output is the same. It would require building more octuple compressed panels yes, but each panel is cheaper to craft comparatively.

Current: ~17m base solar panels for 1 octuple, generates 100m EU/t
Proposed: ~1.7m base solar panels for 1 octuple, generates ~17m EU/t. 

In terms of purely the panel cost, it's actually a base EU/t buff for base panels. The only extra cost would be infrastructure planning (requiring more physical octuples placed), and the non-panel resources.

And if the issue is regarding current infra for post update receiving a huge power output nerf, there could be the option of adding a nonuple and tierskipping all current compressed up for free as a possibility.

**Comment by PlayfulPiano** [comment]
Also I thought you were the one who brought up the need to nerf panel values in the past? Or was I misremembering.
