### ISSUE TITLE
Sound imbalances [Nightly-503]

### ISSUE THREAD

**Issue by 48a3efa65c881ef567345b17f3910e06** [GTNewHorizons/GT-New-Horizons-Modpack#16442]
### Your GTNH Discord Username

33yy

### Your Pack Version

nightly 503

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Play the game normally, all volume sliders at 100% except music, sound levels of actions are as normal

### The Reality

Sound levels are imbalanced on the latest nightly; walking and mining sounds are a lot quieter but breaking and other sounds are the same volume, if not louder [recording [39.4MB|vp9_opus]](https://files.catbox.moe/793v3o.mp4)

### Your Proposal

Fix volume imbalances - I was linked someone's issue that may have caused this but i misplaced the link

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Quarri6343** [comment]
sorry my bad

**Comment by Quarri6343** [comment]
Does this fix you issue?
https://github.com/GTNewHorizons/Hodgepodge/releases/tag/2.5.14-pre

**Comment by 48a3efa65c881ef567345b17f3910e06** [comment]
thanks this fixed it
