### ISSUE TITLE
Drop Cobbled Ores instead of Raw ones with base pickaxe to be hammerable

### ISSUE THREAD

**Issue by 48a3efa65c881ef567345b17f3910e06** [GTNewHorizons/GT-New-Horizons-Modpack#16441]
### Your GTNH Discord Username

33yy

### Your Pack Version

nightly 503

### Your Proposal

If players do not like the raw ore change too much as they cannot hammer them from stone age, we could use the GT6 system of dropping "cobbled ores" when not mined with fortune or silk touch that can be placed and hammered without the use of an auto hammer, that do not drop raw ores when mined with fortune.

### Your Goal

Players in the stone age may mine a lot of coal with a pickaxe, dropping raw ores, only to find they cannot get coal items out of it with a hammer.

### Your Vision

It would allow Raw Ores to be useful in that fortune would affect ores (see [here](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16440) for a bug related to raw ores), but players would be able to use ores mined before fortune as blocks, in that blocks are hammerable (for example for coal items) while items require the auto hammer. Cobbled Ores would not be re-fortuneable, as this makes Silk touch obsolete.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Ethryan** [comment]
You can hammer the raw ore in your crafting table, it has a shapeless recipe for crushing it.
