### ISSUE TITLE
Cosmic Neutronium Blocks not Craftable in Crafting Input Buffer anymore

### ISSUE THREAD

**Issue by Xauronx** [GTNewHorizons/GT-New-Horizons-Modpack#16449]
### Your GTNH Discord Username

xauronx

### Your Pack Version

2.6.1

### Your Server

Epsilon Official

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Used same Large Processing Factory I always used to make Cosmic Neutronium Blocks from Ingots. 
LPF is in Metal Mode, no obstructed Muffler, 2 supplied UHV Energy hatches, No Maintenance Issues.

![2024-06-02_19 45 48](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/48490605/afef9a9c-2eb1-4924-8793-8059f6cdeb3d)

### The Reality

Like in the first Screenshot ingots just sit in Crib doing nothing. Doesnt work in Electric implosion compressor Crib as well. Switching to a normal input bus worked. Other Recipies in Crib work fine.

### Your Proposal

Check/Fix described problem. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
LPF is now deprecated
