### ISSUE TITLE
Fortune not working on silktouched ores (for raw ore drops)

### ISSUE THREAD

**Issue by 48a3efa65c881ef567345b17f3910e06** [GTNewHorizons/GT-New-Horizons-Modpack#16440]
### Your GTNH Discord Username

33yy

### Your Pack Version

nightly 503

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Place silk-touched ore blocks, and fortune affects them and allows them to drop multiple Raw Ore pieces.

### The Reality

Fortune does NOT affect ore blocks placed manually from silk touch, and only affects ones you mine out of the ground
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/134875831/aacc4020-5274-4d74-ad3e-89940a5e5dae)
(notice single raw lazurite drop)
dmxxl sent a video of it working on his singleplayer world, and I confirmed that it did work for me for naturally generated ores, but not hand placed ones

### Your Proposal

Allow fortune to affect placed silk-touched ores, as they do in GT6. It doesn;t make much sense to silk touch ores only to not be able to break them with fortune any more.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cardinalstars** [comment]
This is working as intended. @Ethryan coded it this way, but I'd be fine with changing it. Not really my call.

**Comment by Dream-Master** [comment]
i am against this sugested changes.

**Comment by UselessAqua98** [comment]
Can this be an option inside a config file so players can choose if they want to use it?
