### ISSUE TITLE
Add direct function alternatives for information retrieved from getSensorInformation

### ISSUE THREAD

**Issue by Zeruel13** [GTNewHorizons/GT-New-Horizons-Modpack#16458]
### Your GTNH Discord Username

Zeruel1169

### Your Pack Version

2.6.1

### Your Proposal

Add a direct function alternative for any information that can be retrieved from getSensorInformation. Since getSensorInformation was changed in Pull request #21 https://github.com/GTNewHorizons/Computronics/pull/21, any calls made via getSensorInformation waits until the next server tick to get info. This breaks code my code https://github.com/Zeruel13/gt_MachineOS which updates every second. 

Specific information that this code requires:

- maintenance status (working perfectly / has 1 problem)
- current and max fluid levels in a GT tank
- Avg EU in / out for LSC (getAverageElectricInput() and getEUInputAverage() are not accurate)

### Your Goal

There should be a way to retrieve this information besides using .getSensorInformation. It would allow a way to get the info without yielding and waiting a server tick which .getSensorInformation does. 

### Your Vision

Adds more ways for users to retrieve information about machines other than .getSensorInformation which isn't direct. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
Have you tried to access them via a transposer?

**Comment by Zeruel13** [comment]
While you can access it via a transposer, adding direction functions would simplify user interaction. Especially when working on larger OC programs. Using a transposer solely for this info is a workaround and doesn't fit with it's intended role of moving items and fluids.
