### ISSUE TITLE
Witchery - Arthana quest potentially wrong choice reward

### ISSUE THREAD

**Issue by makaiss0n** [GTNewHorizons/GT-New-Horizons-Modpack#16453]
### Your GTNH Discord Username

makaisson

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Witchery - Arthana provides a choice reward between `minecraft:enchanted_book` with Looting III and LootBag (Witchery Adept).

### The Reality

Witchery - Arthana provides a choice reward between `minecraft:book` with Looting III and LootBag (Witchery Adept).

### Your Proposal

Update quest book to provide `minecraft:enchanted_book` with Looting III.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by des-cuddlebat** [comment]
On Nightly 488, I'm actually seeing a total of three enchanted `minecraft:book` rewards:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/55840769/7d3e55af-f226-47c8-9a6a-b9a9256e9705)

(Not sure what's up with the duplicate Are You Prepared entry)

Checking in-game, neither instance looks like a deliberate choice.

I can take care of this, should be a relatively quick fix to change item IDs in the instances found.
