### ISSUE TITLE
Render issue with blocks at a distance

### ISSUE THREAD

**Issue by Florinlego** [GTNewHorizons/GT-New-Horizons-Modpack#16454]
### Your GTNH Discord Username

Florinlego

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I updated the pack from version 2.5.1 to 2.6.1 and ported my 2.5.1 world to this current version.

### The Reality

Upon entering the world, I encountered the bug, regarding the rendering of blocks at a distance of 2-3 chunks. Dots appear on the edges of blocks. I tried to modify the graphics settings, but none of them seem to affect this bug. I attached pictures of said bug, and pictures of my settings.
Pictures of bugged render:
![2024-06-01_20 50 25](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31806051/f0c9812c-33b5-42dd-afaa-cf54c2e383e9)
![2024-06-03_10 57 53](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31806051/97168481-94db-441b-a218-ad8f97cb4bd5)
(^Click on this one to see the white dots on the grass)
![2024-06-01_20 30 30](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31806051/4fa98def-47a8-42b5-af2a-1025f413c4b1)
Pictures of my graphics settings:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31806051/7e5ff201-416c-4b1e-819e-bdab040b7f85)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31806051/5d06dc72-5c47-4892-957c-0c2919c41561)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31806051/7ebbf50b-912c-46c7-8d66-06bcf59cb526)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31806051/6dca79dd-5e78-4ed4-b2fd-b9f1d698245c)

### Your Proposal

I have no idea what may cause the problem, I played with the settings to no avail. If needed, I can provide additional info (specs, drivers etc)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Florinlego** [comment]
**Update**: initially, I used the CurseForge version of GT:NH, so I moved to MultiMC (according to the tutorial provided by the devs).
I also tried to run the game with both java 8 and java 17 (I had some problems for java 21, as the game would refuse to start, I could not find the reason online).
In both cases, running the game on MultiMC, with a different Java version (and their respective 2.6.1 zip file for the modpack), the bug would still occur and blocks would not be rendered correctly.

**Comment by Glease** [comment]
Try disable compact vertex format in advanced tab

**Comment by Florinlego** [comment]
Disabled it in both Java 17 and Java 8 version, does not resolve the problem. Also tried disabling most options in the advanced tab, but still does not fix the problem. I can't say for sure, but I think it is a problem with rendering the faces furthest away from the camera (but don't take this for granted, I have no idea what could cause this, as I can't find anyone else that has this problem).

**Comment by Caedis** [comment]
Does the issue occur in a new world?

**Comment by Caedis** [comment]
Can you try with this version (latest nightly)?
https://github.com/GTNewHorizons/DreamAssemblerXXL/actions/runs/9360422660/artifacts/1565081977

**Comment by Florinlego** [comment]
Will do. I'll keep you posted after I try. Cheers!

**Comment by Caedis** [comment]
Dont copy anything over, try it from scratch

**Comment by Florinlego** [comment]
Still does not fix the issue (check attached). Tried it with and without Compact Vertex Format. I have tried it on a new world, without porting anything from the other instances.

I also want to add that the Java 8 version I have is the official one (from www.java.com) and the Java 17 version I have is downloaded from the link provided in the GT:NH website. I am pretty sure that I installed them correctly, as checking the virtual machine in MultiMC works, for both of them.
However, I also want to add that in order to run GT:NH for Java 17, I have to add the following to the Java args:
--illegal-access=warn -Djava.security.manager=allow 
-Dfile.encoding=UTF-8 --add-opens java.base/jdk.internal.loader=ALL-UNNAMED 
--add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED
--add-opens java.base/java.lang=ALL-UNNAMED 
--add-opens java.base/java.lang.reflect=ALL-UNNAMED 
--add-opens java.base/java.text=ALL-UNNAMED 
--add-opens java.base/java.util=ALL-UNNAMED 
--add-opens java.base/jdk.internal.reflect=ALL-UNNAMED 
--add-opens java.base/sun.nio.ch=ALL-UNNAMED 
--add-opens jdk.naming.dns/com.sun.jndi.dns=ALL-UNNAMED,java.naming 
--add-opens java.desktop/sun.awt.image=ALL-UNNAMED 
--add-modules jdk.dynalink 
--add-opens jdk.dynalink/jdk.dynalink.beans=ALL-UNNAMED 
--add-modules java.sql.rowset 
--add-opens java.sql.rowset/javax.sql.rowset.serial=ALL-UNNAMED -Dfile.encoding=UTF-8 -Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader -Djava

I found this way of fixing the boot-up crash by searching for the initial error messasge I got:
java.lang.IllegalStateException: System classloader not overwritten, add -Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader to your JVM flags

The same behavior occurs, even with the version you provided:
![2024-06-04_14 31 49](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/31806051/4d97e71f-8f99-48ca-a29c-29a75fa9f28a)

**Comment by Florinlego** [comment]
**Update**: The problem does not have anything to do with the game, but with settings in the NVIDIA Control Panel. If they are left on the default settings, the game should work. I will close the ticket. Sorry for the bother and thanks!
