### ISSUE TITLE
Extreme Industrial Greenhouse not using all available slots

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#16466]
### Your GTNH Discord Username

Afx237v7

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Operate an EIG with 2 ZPM hatches, making it UV-tier and therefore providing 16 slots for crops/seeds. Give it 16 full stacks of sugar cane and have it produce 16x64= 1,024 sugar cane per operation.

### The Reality

You can insert 16 full stacks of sugar cane, but once you start the EIG, it will void one full stack from the slots and output 15x64= 960 sugar cane.
Also tested with Nether wart, it will void one of the 16 full stacks that is inserted.

### Your Proposal

It should not void any input stacks and produce the proper amount of items.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment]
Greenhouse tooltip:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/53441451/2ab0e8b5-1676-4189-bccb-91b53b458b36)

**Comment by GTNH-Afx237v7** [comment]
This has nothing to do with what I explained, as it describes the IC2 crops, not vanilla sugar canes or vanilla nether warts.

**Comment by kuba6000** [comment]
> This has nothing to do with what I explained, as the tooltip describes the IC2 crops, not vanilla sugar canes or vanilla nether warts.

The part about weedex applies to all types of crops

**Comment by GTNH-Afx237v7** [comment]
For some reason I believed it was IC2 crops only… thx for the info.
