### ISSUE TITLE
Increase BC Builder and Filler range

### ISSUE THREAD

**Issue by aka-zaratustra** [GTNewHorizons/GT-New-Horizons-Modpack#16461]
### Your GTNH Discord Username

aka_zaratustra

### Your Pack Version

2.6.1

### Your Proposal

BC Builder and Filler range should be more than 4 chunks. For example 16.

### Your Goal

It's painful to build a base at a high tier using a builder whose work range is only 4 chunks. 

### Your Vision

By now the construction site has to be divided into several parts (each 4 chunks max), which is inconvenient. (see picture)
![2024-06-04_15-40-11](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24389462/dcd34c08-e044-4071-bd8b-eabd3fc53789)
If the range will be larger (for example 16), this will allow to be built whole construction site in one piece, which is more convenient.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by GTNH-Afx237v7** [comment]
Afaik there is a config entry already.

**Comment by kaev-i** [comment]
> Afaik, запись конфигурации уже есть.

The config itself does not give a reason to change the build, I prefer to legally get it from the author, otherwise following your logic you can change any config!

**Comment by aka-zaratustra** [comment]
> Afaik there is a config entry already.

Нes, it is in the config. But I'm a streamer who streams GTNH, and I shouldn't change the configs, because... Viewers will wonder what modpack I'm playing, because that's not the case in GTNH. Therefore, I ask you to add a change to the config. Change from 64 blocks to at least 256 blocks.
