### ISSUE TITLE
Textures for HSS-S Turbine Casings (Large Advanced Gas Turbines) are bugged

### ISSUE THREAD

**Issue by Zenovis** [GTNewHorizons/GT-New-Horizons-Modpack#16460]
### Your GTNH Discord Username

zeno3772

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Large Advanced Gas Turbine forms correctly and looks cool 

### The Reality

HSS-S turbine casing textures are bugged and do not return the correct textures. They default to the solid steel machine casing textures. First Image is in game, and Second image is with the Solid steel textures replaced with the advanced gas turbine textures. Happens without a texture pack as well.
![1717443034882604](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/171630307/223e86b5-9660-43e3-b8cf-150239a4d95b)
![1717501223387806](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/171630307/6be8ef1c-53e3-4cb4-87f0-4dd717c9c11a)

### Your Proposal

I would like this to be fixed. I am not 100% sure, but it seems the root cause is the function 
> src/main/java/gregtech/common/blocks/GT_Block_Casings8.java
`public IIcon getIcon(IBlockAccess aWorld, int xCoord, int yCoord, int zCoord, int ordinalSide) `

which is defaulting to the "MACHINE_CASING_SOLID_STEEL" icon instead of the correct advanced turbine icon. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
I've seen this before yeah, should be a simple fix. I'll have a proper look later today.
