### ISSUE TITLE
The hv and ev transformers do not have a recipe in the assembler.

### ISSUE THREAD

**Issue by Juniorent** [GTNewHorizons/GT-New-Horizons-Modpack#16471]
### Your GTNH Discord Username

juniorrent

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Create an HV and EV transformators in assembler.

### The Reality

All other transformators have crafting in assembler that does not require the participation of a vanilla workbench, but HV and EV transformators do not have such crafting. They only have crafting via IC2 transformatiors in assembler, which in turn is created from the same GT transformators. 

### Your Proposal

It is necessary to add this craft because all other transformators have a craft that allows you to make them without a vanilla workbench.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Worive** [comment]
It may be because of my lack of knowledge about the modpack. Can someone confirm me if I'm right?

The task is to add the equivalent workbench craft but into the assembler for the following blocks:

**High Voltage Transformer:**
- Ingredients: 
- - 2x Ultra Low Power IC
- - 5x "1x Gold Cable"
- - 1x "HV Machine Hull"
- Total 153,600 EU
- Usage: 1,920 EU/t (EV)
- Time: 4 secs

**Extreme Voltage Transformer:**
- Ingredients: 
- - 2x Low Power IC
- - 5x "1x Aluminium  Cable"
- - 1x "EV Machine Hull"
- Total 307,200 EU
- Usage: 7,680 EU/t (IV)
- Time: 2 secs

Note: I've used the craft of the Medium Voltage Transformer to scale based on the craft using the IC2 transformer.

**Comment by Juniorent** [comment]
> Это может быть из-за моего недостатка знаний о модпаке. Может ли кто-нибудь подтвердить, что я прав?
> 
> Задача состоит в том, чтобы добавить эквивалентный верстак, но в ассемблер для следующих блоков:
> 
> **Высоковольтный трансформатор:**
> 
> * Ингредиенты:
> * * 2x ИС сверхнизкого энергопотребления
> * * 5x "1x Золотой кабель"
> * * 1x "Корпус машины HV"
> * Всего 153 600 ЕС
> * Использование: 1920 EU/т (EV)
> * Время: 4 сек.
> 
> **Трансформатор экстремального напряжения:**
> 
> * Ингредиенты:
> * * 2x маломощных ИС
> * * 5x "1x Алюминиевый кабель"
> * * 1x "Корпус электромобиля"
> * Всего 307 200 ЕС
> * Использование: 7680 EU/т (IV)
> * Время: 2 сек.
> 
> Примечание: Я использовал поделку трансформатора среднего напряжения для масштабирования на основе поделки с трансформатором IC2. Ингредиенты те же, что и в поделке верстака

Since this is a transformer, the craft must use two types of cables; for example, let’s take an HV transformer. Since it uses 1 amp EV dash and makes it into 4 amp HV dash, the craft uses 1x aluminum cable and 4 1x gold cables. 
then the recipe will look like this:
Ingredients:
2x Ultra Low Power IC
4x "1x Gold Cable"
1x "1x Aluminium Cable"
1x "HV Machine Hull"

**Comment by Juniorent** [comment]
> It may be because of my lack of knowledge about the modpack. Can someone confirm me if I'm right?
> 
> The task is to add the equivalent workbench craft but into the assembler for the following blocks:
> 
> **High Voltage Transformer:**
> 
> * Ingredients:
> * * 2x Ultra Low Power IC
> * * 5x "1x Gold Cable"
> * * 1x "HV Machine Hull"
> * Total 153,600 EU
> * Usage: 1,920 EU/t (EV)
> * Time: 4 secs
> 
> **Extreme Voltage Transformer:**
> 
> * Ingredients:
> * * 2x Low Power IC
> * * 5x "1x Aluminium  Cable"
> * * 1x "EV Machine Hull"
> * Total 307,200 EU
> * Usage: 7,680 EU/t (IV)
> * Time: 2 secs
> 
> Note: I've used the craft of the Medium Voltage Transformer to scale based on the craft using the IC2 transformer. The ingredients are the same as the one used in the workbench craft

Since this is a transformer, the craft must use two types of cables; for example, let’s take an HV transformer. Since it uses 1 amp EV dash and makes it into 4 amp HV dash, the craft uses 1x aluminum cable and 4 1x gold cables.
then the recipe will look like this:
Ingredients:
2x Ultra Low Power IC
4x "1x Gold Cable"
1x "1x Aluminium Cable"
1x "HV Machine Hull"
