### ISSUE TITLE
Multiblock Versatility - EBF (and others ?)

### ISSUE THREAD

**Issue by Shikifuyin** [GTNewHorizons/GT-New-Horizons-Modpack#16485]
### Your Pack Version

2.6.1

### Your Proposal

To my surprise, the EBF doesn't accept any bus/hatch on the top layer !
Coming from CEu where blocks can be placed anywhere, this is a real disapointment because it breaks many compact
setups and automation, mostly for shared walls (quads).
I am only at my first EBF in the pack, but if this is also the case for many multiblocks going forward, I think this is definitely
something that requires improvement.

All I/O and interactive blocks on multiblocks should be placeable anywhere (except some exceptions because of shape design
of course). In CEu, the NEI multiblock preview shows each allowed block at each position, along with sharing conditions,
which I think is just perfect.

### Your Goal

This feature should be there to allow more freedom when designing base/automation/compacting, etc ...
Having all interactions on the bottom layer of the EBF is very restrictive and prevents most of my setups I had
in CEu ...

### Your Vision

Any unecessary restriction that prevents setup ingenuity and automation complexity should be removed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
oh you can definetely do quads. I guess you just have to think about it for a moment.

EBF also definetely accepts a hatch at the top but it behaves differently, hence the different behaviour.
