### ISSUE TITLE
Allow clearing of Wireless Setup Kit state

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#16486]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.5.1

### Your Proposal

1: I'd like to be able to undo accidental misclicking of an AE2 wireless connector. Shift-clicking the air would be preferable since this does the same with a AE2 memory card.
2: I'd like to see the remembered link's dimension in the tooltip

### Your Goal

User convenience:
- Within the same dimension you can undo a misclick without having to link two connectors and then breaking them to retry
- If a link was remembered from an external dimension, the wireless setup is effectively bricked until the user travels back to that dimension, assuming they know which dimension it was. This scenario can be triggered if the user (like me) forgets that interdimensional AE2 requires a quantum ring and they get the error message clicking the second connector.

### Your Vision

I think this would improve usability and help with unnecessary frustrations (particularly in the second scenario)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by NotAPenguin0** [comment]
Clearing the setup kit is implemented in GTNewHorizons/AE2Stuff#18, this should also address most of your dimension troubles.

**Comment by combusterf** [comment]
It doesn't add those fixes to the current wand though

**Comment by NotAPenguin0** [comment]
It says it does at the bottom of the PR text.
