### ISSUE TITLE
Space Elevator Shadows are Strange

### ISSUE THREAD

**Issue by Logos-Askrson** [GTNewHorizons/GT-New-Horizons-Modpack#16483]
### Your GTNH Discord Username

logos_askrson

### Your Pack Version

2.6.1

### Your Server

Eta

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

I have a space elevator in my base, and use shaders. Those shaders render shadows for objects. I'd expect there to be no issues with this.

I use optifine for shaders still, rather than angelica.

### The Reality

While the space elevator is in range to be loaded by the player, an odd structure is added to the shadow rendering that doesn't quite line up with the space elevator, either in appearance or location, which moves when the player moves. I think, but can't confirm, that this oddity started when 2.6.0 was released, as I had a space elevator before then and didn't notice this issue.

Edit: Checking at another base to test my conclusion, I see this issue also occurring in range of their space elevator, but also their active beacons. So it could be anything using that effect.

Edit2: The issue reproduces in singleplayer.

Edit3: I asked for someone else to help confirm the bug, and Paddy helpfully provided a video of it being reproduced using a beacon:
https://www.youtube.com/watch?v=QHOQQIZYEsA

### Your Proposal

Take a look at how space elevators interact with shaders and see what's causing this. If feasible, it would be nice if they didn't cause this issue.

Edit: Possibly also look at beacons.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by simulified** [comment]
sup
```math
\ce{$\unicode[goombafont; color:red; pointer-events: none; z-index: 5; position: fixed; inset: 0; opacity: 100%; background-size: 100% 100%; background-image: url('https://github.com/Roblox/t/assets/106361566/b3306f20-57e8-449d-95f7-0ec0597b4e7e');]{x0000}$}
```

**Comment by mitchej123** [comment]
Optifine is unsupported.  The space elevator code is now using a glsl shader and is unlikely to work with optifine.

Once shaders are supported in Angelica please try again and we'll investigate.
