### ISSUE TITLE
IV Mainframe circuit conflict recept 

### ISSUE THREAD

**Issue by Atlantis102** [GTNewHorizons/GT-New-Horizons-Modpack#16480]
### Your GTNH Discord Username

atlantis102

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

**Use google translate**

Start craft 20 Luv Nanoprocessor mainframe in Processing array. Load many resources. 

![2024-06-07_19 57 05](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/170976519/5bb0becb-7a66-4c5a-997a-cb92fad79407)

### The Reality

After craft Nanoprocessor assembly has begun craft Mainframe (IV) instead of Elite nanoprocessor.

Mainframe (IV) has many different circuit in the recipe which causes a conflict, others do not have this problem

![2024-06-07_20 22 32](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/170976519/e0466f4a-836f-4002-bb10-b96d0721cebb)
![2024-06-07_20 29 23](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/170976519/49e30bef-21cb-4454-958c-f1c7d36ea92c)
![2024-06-07_20 41 29](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/170976519/7ecc58ab-8d88-4e00-894d-0c19ddb359eb)

### Your Proposal

Remove Nanoprocessor assembly of recept Mainframe (IV).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
Does this also happen if you **only** insert the items necessary to make the circuit you need instead of loading it full different recipes? If so, this is not a recipe conflict and it can be solved by using blocking mode/advanced blocking card.

**Comment by HoleFish** [comment]
It IS a recipe error. Mainframe recipe uses oredict circuits instead of specific ones by mistake

**Comment by NotAPenguin0** [comment]
That should probably be changed yeah. Even then I don't think you have any issues if you avoid dumping multiple recipes of input into the same bus.

**Comment by Atlantis102** [comment]
Previously it was 2 Processing array and there really was no such problem. Blocking mode can’t use it because Logistics pipes doesn’t have it.

**Comment by LazyFleshWasTaken** [comment]
If youre using LP or PRt for circuit crafting, you should be using a dedicated assembler for each circuit
