### ISSUE TITLE
world crashes when loading in due to fastcraft but still crashes even after disabling it

### ISSUE THREAD

**Issue by BoriswazHere245** [GTNewHorizons/GT-New-Horizons-Modpack#16509]
### Your GTNH Discord Username

bigget_migget

### Your Pack Version

2.5.1

### Your Server

sp

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

I was exploring then crashed after loading a chunk and tried restarting the world but every time I load in it starts constructing the world and I log on for a few seconds before the world crashes. I tried disabling fast craft as its the suspected mod but it still has the same crash problem but then it says unknown problem mod. I also opened a new world with the same seed and went to the same coords but the new world didn't crash when I went there.

### Crash Report

original crash log: https://mclo.gs/voNFgHk
After disabling FastCraft: https://mclo.gs/udA5cCr

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
looks corrupted. best use a backup
