### ISSUE TITLE
Incomplete multiblocks structures preview

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/GT-New-Horizons-Modpack#16507]
### Your GTNH Discord Username

Admin_XiaoMai

### Your Pack Version

nightly-512

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

incomplete structure preview
It's the same with all multi-block machines

### The Reality

![3f04c5fddd43b5f5663fe2f962842853](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/e18a27e0-463e-4bd3-bb33-01915113569a)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/22012110/d331a9cb-f0f0-44b0-a848-76691d7cc67c)

### Your Proposal

fix structures preview

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
can you explain a bit more what the problem is and how to reproduce it?

**Comment by AdminXiaoMai** [comment]
> can you explain a bit more what the problem is and how to reproduce it?

simply by using the projector could reproduce the issue 
almost every multi is influented

**Comment by AdminXiaoMai** [comment]
I tested nightly-503 and had the same issue

**Comment by Dream-Master** [comment]
?
