### ISSUE TITLE
Ichorium Block Compressor Addition

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#16504]
### Your GTNH Discord Username

lordpeverell

### Your Pack Version

2.6.1

### Your Proposal

Allow ichorium to be compressed in a GT machine instead of it being purely via infusion

### Your Goal

See above

### Your Vision

Dont see why it isnt a thing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
I support this, I’ll add it to the script

**Comment by chochem** [comment]
this is something dream disabled on purpose years ago.

**Comment by joshaup1999** [comment]
Doesn’t make sense to me, we can mine ichorium late game via SE. Why can’t we also compress it into blocks? Even if the recipe for the blocks requires UEV voltage

**Comment by Alastors** [comment]
Yeah gotta agree with Pev on this one, course who’s to say who’ll jump outta the woodwork once the PR is up

**Comment by LazyFleshWasTaken** [comment]
Yea, doesn't make sense to me either. The recipe also existed for a bit in 2.3.0 or 2.4.0 for a while, since I had to use it for blood soaked ichorium blocks, and it made basically no change to the gameplay. Ichorium block also arc furnace it into 9 ingots, so I don't see why the reverse can't be.

**Comment by chochem** [comment]
it was removed in 2017 so long before 2.3.0 or 2.4.0 from what I can see

**Comment by LazyFleshWasTaken** [comment]
Well, since there is literally no other way outside of the infusion recipe to make it, and I did not cheat it in, idk what to tell you.

**Comment by Dream-Master** [comment]
I will check the recipe but there was some reason to not build it via gt.

**Comment by Stetsed** [comment]
Noticed this same issue in our current run, currently at UIV and we need dragon blood. We had started mining icho and are up to 26mil now. We have 0 use for this icho except basically the draconic fusion stuff, which we can't use it for to make because we can't turn that 26mil into the blocks we need.

Kinda weird that the ONLY way to get those blocks even after the UEV icho gate, is still with the infusion recipe.
