### ISSUE TITLE
Serious lag caused by Drone Center

### ISSUE THREAD

**Issue by skyinr** [GTNewHorizons/GT-New-Horizons-Modpack#16506]
### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

no lag

### The Reality

I forgot to load chunk for Drone Centre.
When Drone Centre is not loaded

Drone DownLink Module has become lagging behind.
Drone DownLink Module is also unable to maintain the machine.
Drone Centre cannot find Drone DownLink Module.

Rebuild Drone DownLink Module or Drone Centre is also invalid

I checked the lag using LagGoggles
![2024-06-10_22 44 58](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/41814896/29d530ef-0d01-49c3-8f9c-9d349992bd2f)
![2024-06-10_22 44 19](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/41814896/3011a099-fc9c-43e7-a19e-f64d1134006f)
![2024-06-10_22 44 39](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/41814896/5e85474e-2716-4707-8823-88321cee09a0)
![2024-06-10_22 54 08](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/41814896/f61c80a9-f661-490a-a1b5-b9a163609dd9)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by skyinr** [comment]
I remove the Drone Center And I have rebuild the Drone downlink module. but drone downlink module reconnect to old Drone Center.
![2024-06-11_13 52 45](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/41814896/a5fac88c-9d31-422a-a9fb-368245ee1fb5)
![2024-06-11_13 52 47](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/41814896/6c1a87e5-edca-403e-a562-380b442c39fd)

**Comment by Dream-Master** [comment]
Update to 2.6.1. and try again .

**Comment by skyinr** [comment]
Can be replicated in the GTNewHorizons/GT5-Unofficial@master latest testing environment

Restart world can run

Perhaps it's because of this?
When the controller coordinates are the same but the content is different, it will repeat the put `GT-MetaTileEntity-DroneCentre`
``` java
 //gregtech.common.tileentities.machines.multi.drone.GT_MetaTileEntity_DroneCentre#onFirstTick

 public void onFirstTick(IGregTechTileEntity aBaseMetaTileEntity) {
        super.onFirstTick(aBaseMetaTileEntity);
        if (aBaseMetaTileEntity.isServerSide()) {
            if (droneMap.containsValue(this)) return;
            centreCoord = new Vec3Impl(
                getBaseMetaTileEntity().getXCoord(),
                getBaseMetaTileEntity().getYCoord(),
                getBaseMetaTileEntity().getZCoord());
            droneMap.put(getBaseMetaTileEntity().getWorld().provider.dimensionId, this);
        }
    }
```
