### ISSUE TITLE
Line Mode for wrenches does not work in multiplayer?

### ISSUE THREAD

**Issue by Tempurs** [GTNewHorizons/GT-New-Horizons-Modpack#16520]
### Your GTNH Discord Username

tempur.

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Attempted to shift + right click a wrench in multiplayer to switch to line mode.

### The Reality

Nothing happens when shift + right clicking the wrench.
Works fine in singleplayer.

### Your Proposal

Fix it to work in multiplayer if intended.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2611
