### ISSUE TITLE
Recipe for BOP quicksand 

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#16527]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.6.1

### Your Proposal

Add a way to get quicksand, since is needed for a quest and also for crafting the Book of biomes, ( and is bit hard to find)

### Your Goal

Complete all the quests withot having a map of 20Gb

### Your Vision

Right now this block is only used to complete an exploration quest, and creating a book, gating in HV might be fine for early exploration.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
> Complete all the quests withot having a map of 20Gb

thats ridiculous.

**Comment by LazyFleshWasTaken** [comment]
Could be useful if a world was generated without rwg, and is just a vanilla world

**Comment by EnderProyects** [comment]
Can then this be added, or I close it :3 ( if not for 2.7 for  2.8)

**Comment by BlueHero233** [comment]
If you dont want to get a 20+gb save file, might i suggest using mca selector to delete the chunks you found nothing interesting? Also BOP biomes populate a "vanilla" generation regardless
"Fact: 90% of greggers quit before they find a desert with quicksand, keep gambling!" - Tony Soprano
