### ISSUE TITLE
Nagastone Twilight Forest Crash 

### ISSUE THREAD

**Issue by mcarreon** [GTNewHorizons/GT-New-Horizons-Modpack#16529]
### Your GTNH Discord Username

perplexagus

### Your Pack Version

2.6.1

### Your Server

Dedicated Local Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Saw another issue opened for this, but for SP and a different version, so figured it was worth opening. 

Twilight Forest was generated in 2.6.0, and had no issues initially entering/exploring. Upgraded to 2.6.1, and now running into crashes when Naga arena blocks are loaded in. 

### Crash Report

https://mclo.gs/NanBk1X

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
Update to https://github.com/GTNewHorizons/twilightforest/releases/download/2.6.12/TwilightForest-2.6.12.jar

Duplicate issue
