### ISSUE TITLE
Buff the Cryo freezer

### ISSUE THREAD

**Issue by Zenovis** [GTNewHorizons/GT-New-Horizons-Modpack#16521]
### Your GTNH Discord Username

zeno3772

### Your Pack Version

2.6.0

### Your Proposal

Buff the Cryogenic freezer. It's become a running joke as to how bad it is. It's an expensive, slow, and borderline useless multiblock compared to the Mega Vacuum freezer. 
I propose:

- Increasing the parallel count to 8, to match with Volcs
- Halving the rate of Cryotheum usage
- Tier shifting it down to IV

### Your Goal

- The cryo freezer is locked behind LuV, depriving IV players of an alternative to the Mega vacuum freezer at a time when they are building multiple Volcs and scaling up their EBF production. This creates a vacuum freezer bottleneck, which is solved by the (much easier to craft) MVF, which also offers a staggering 256 parallels compared to a Cryo freezer's 4 (albeit effectively 8 due to the speed bonus). 
- Cryotheum is much more lengthy to automate compared to pyrotheum and has hilariously bad rates from a blizz EEC. 
- The HG-1223 and lafium compound needed for the casings are painfully slow to craft, and just serve to add to the tedium of making the cryo freezers. A player can get through all of IV with a single alloy blast smelter, yet as soon as they hit LuV the recipe times increase dramatically, again discouraging crafting the cryo freezers. This is without mentioning the tedium of patterning all the other GT++ materials. (I had to set up a distillery and fluid heater for NaK cells, just for this one casing recipe. Seriously?)
- There is no reason to ever craft a cryo freezer after crafting a MVF. 
- A Cryo freezer often cannot keep up with a single Volc. Smelting ZPM superconductors at ZPM voltage with neon takes 8.2s per ingot, while chilling a ZPM superconductor ingot takes 10 seconds.

### Your Vision

Buffing the cryo freezer would give the player more choice. As it currently stands the only advantage the cryo freezer has over the MVF is using half the EU per ingot. Almost all GT++ multiblocks have their place in the pack, while the cryo freezer feels abandoned.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Reflex18** [comment]
There is a fundamentally issue with the cryo freezer is that the only reason why one would make it over the mega vac freezer is the size and power cost.

If the player is already freezing enought ingots to warrant it then they have already scaled enought to care less about power. Which leaves the only issue being the size of it compared to the GT ++ version.

Since the player needs space for other megas, whats more space for the mega vac?

Really there is no place for it in this pack.

**Comment by chochem** [comment]
I dont think people really like the 8 parallels on the volcanus in the first place (not close to a power of 4). but I dont see the harm in slightly increasing bonusses or somewhat decreasing the cryo usage.

**Comment by Shadowsoftime99** [comment]
The cryo usage is the biggest killer of it for me (why is it double the Volcanus equivalent?), but I agree that any of its numbers could use a bit of help. It just falls behind the Volcanus on every number right now which makes it less desirable than the mega GT equivalent.

> Really there is no place for it in this pack.  

Player choice moment :D. I just think the smaller ++ versions are neat and have cool designs, so I'd like to use them over the giant boxes if possible. And right now, it's extremely hard to justify the Cryo Freezer exactly.
