### ISSUE TITLE
Missing item ( fire) in Splicer recipes

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#16530]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.6.1

### Your Server

private

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

No fire?

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/3fe29cd1-1d45-4f17-b7c9-b93043153886)

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
![image](https://github.com/user-attachments/assets/cf42a3c1-a390-441e-b306-06e44434e784)
inoculator has some issues too
