### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by ShenRedfield** [GTNewHorizons/GT-New-Horizons-Modpack#16548]
### Your GTNH Discord Username

kami_no_kotoba

### Your Pack Version

2.1.6

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Just played as normal. But after i launched the modpack today, i get crash every 3-5 minutes

### Crash Report

[crash-2024-06-18_15.03.25-client.txt](https://github.com/user-attachments/files/15886353/crash-2024-06-18_15.03.25-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment]
@Darkmorro your issue is completely different and updating to 2.6.1 would solve it.

**Comment by Darkmorro** [comment]
> @Darkmorro your issue is completely different and updating to 2.6.1 would solve it.

Thanks.

**Comment by BlueHero233** [comment]
Does it persist in 2.6.1?

**Comment by chochem** [comment]
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471
probably some corrupted mod files, try redownloading.
