### ISSUE TITLE
Electric Boots of the Traveller Don't Work

### ISSUE THREAD

**Issue by thisjaiden** [GTNewHorizons/GT-New-Horizons-Modpack#16542]
### Your Pack Version

1.6.1

### Your Server

Private SMP

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Electric Boots of the Traveler acted in the same way as standard Boots of the Traveler when it comes to run speed and jump height in 2.5.1.

### The Reality

Movement speed is not increased, jump height is not increased, and movement slows when jumping.

### Your Proposal

Electric Boots of the Traveler should be patched to return to earlier behavior, or a note created in their respective quest that they do not function the same.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
THey follow thaumic boots now. Use the keybinds for em to toggle speed and jump boost.

**Comment by thisjaiden** [comment]
Ah, this works perfect. Thanks 👍
