### ISSUE TITLE
Add Fluid Solidifier recipe for Precious Metals Alloy Screw

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#16547]
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.6.0

### Your Proposal

Add a fluid solidifier recipe to turn Molten Precious Metals Alloy into Previous Metals Alloy Screw

### Your Goal

PMA is used in large quantities, and being able to solidify directly from fluid would allow bypassing the bolt extrusion and lathe step of producing them.

### Your Vision

Bring parity with other fluids that can be solidified directly into screw form.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by norbby42** [comment]
Actually, it looks like all of the GoodGenerator metals (except Metastable Oganesson and Shirabon) are lacking the specialized fluid solidifier recipes (ie bolts, screws, gears, ring.

**Comment by NotAPenguin0** [comment]
Some of this was added in GTNewHorizons/GoodGenerator#228, which I don't think should've been rejected.

**Comment by Caedis** [comment]
@NotAPenguin0 its not rejected, it just needs checked over after _**THE GREAT MERGENING**_

**Comment by Dream-Master** [comment]
I would not merge it because you can skip ebf and vac freezer . Read my comment !

**Comment by NotAPenguin0** [comment]
You can already "skip" the freezer. Currently the ABS recipe for molten precious metal alloy exists, as well as a fluid solidifier recipe to make it into ingots. This means that *currently* you can already do either of these routes
- Mix the dust -> EBF -> Freezer -> Extruder for screws
- ABS the fluid -> Ingot solidifier -> Extruder for screws

The PR simply adds recipes to skip the ingot solidifier step, so it would go 
- ABS the fluid -> Screw solidifier

Which I think is quite sensible, it exists for most other materials as well.

**Comment by Dream-Master** [comment]
Ok but then we need to better balance ABS against EBF/VAc freezer recipes to not make recipes oboslete or to cheap.

**Comment by norbby42** [comment]
After reading Dream's comment, I went and looked at the recipes ingame.  The Molten Precious Metals ABS recipe is actually *significantly slower* than mixing, smelting, and cooling the Precious Metals Ingots via EBF/VF.  Especially when comparing with MABS vs MEBF/MVF.

**Producing Fluid directly:**
MABS: Assume ~10% speed boost due to using high tier coils (Infinity+).  The recipe is UEV: 540 seconds for 6 ingots worth of fluid.   So 90 * 0.9 per ingot.

"UEV" duration: **81** seconds

**Producing Ingots directly:**
Mixer: Dust is 1.2 seconds at LV.  Trivial, will 1-tick a small mountain of dust
MEBF: Assume Krypton as the noble gas (ie best SE pumpable), the recipe is UEV: 53.3 seconds.  The required heat capacity is 10,000K, so with equivalent coils (Infinity+) on the MABS, we're going to see 1 heat OC for 1 perfect OC.  So we're already down to 26.65 seconds before adding in the remaining normal OCs.
MVF: 22.05 seconds at MV.  This will also be a trivial duration at UEV.  Just for the funsies, we can assume a duration of 2 ticks.

"UEV" duration: **27** seconds


----

It seems the main difference between the 2 approaches in terms of operation cost is number of machines and a noble gas. 

All of this is napkin math, but it's an interesting look.  I never considered this originally due to needing the Precious Metals for the DTPF (and thus natively in fluid form), but now I'm thinking about swapping away from the MABS to MEBF/MVF (after my base finishes the big crafts it has ongoing that are preventing me from changing it right now >.>).

----
Disclaimer: The OC math for the MEBF recipe is technically wrong at UEV (cause missing power for the perfect OC), but you're not going to be running this recipe with UEV-level power anyways.
