### ISSUE TITLE
Mojang copyright text does not appear correctly on auto GUI scale on 1080p resolution

### ISSUE THREAD

**Issue by dinkley** [GTNewHorizons/GT-New-Horizons-Modpack#16569]
### Your GTNH Discord Username

Dink (doinkywoinky)

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

1. Launch GTNH.
2. Observe the text at the bottom right of the screen.

Expected the "Copyright Mojang AB. Do not distribute!" text to appear normally.

### The Reality

It does not appear normally. Everything after "Copyright Mo" is cut off due to the auto GUI scale not respecting the length of text on the main menu screen.
![2024-06-21_07 02 30](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24577847/e7b12a52-f6f6-48e6-8d34-1005ea20afd6) (1920x1080, fullscreen)

### Your Proposal

The copyright information should ideally be on its own line under the Forge version information. This way, both the GTNH and Forge versions are on their own lines with the Mojang copyright notice at the bottom.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Yamnasm** [comment]
The Mojang copyright notice has issues wrapping/reflowing with aspect ratio.
