### ISSUE TITLE
ME интерфейсы требуют 2 ядра формирования в одном рецепте (плоский) и 1 в другом (обычный)

### ISSUE THREAD

**Issue by Gramilys** [GTNewHorizons/GT-New-Horizons-Modpack#16578]
### Your GTNH Discord Username

Gramilys

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

ME интерфейс должен требовать 1 ядро формирования.

### The Reality

ME интерфейс (плоский - cover) требует 2 ядра формирования, при этом для крафта обычного МЕ интерфейса требуется 1 ядро формирование (его можно положить в сетку крафта и получить плоскую версию).

![2](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17285610/67a6ca83-7b92-44d7-9dee-95e76c127dd5)
![1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/17285610/80d7b0b5-d9cd-4862-91b6-a9e0ba033819)

### Your Proposal

ME интерфейс должен требовать 1 ядро формирования в обоих рецептах.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
Duplicate of #16479, already fixed in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/862

**Comment by chochem** [comment]
also please english only.
