### ISSUE TITLE
SC Steam Turbine automate turbine replacement

### ISSUE THREAD

**Issue by Polybomber** [GTNewHorizons/GT-New-Horizons-Modpack#16589]
### Your GTNH Discord Username

Polybomber

### Your Pack Version

2.6.1

### Your Proposal

Currently SC Steam Turbines don't have any way of automatically replacing turbines. I think it would be a good idea to provide them with an input bus so that turbines could automatically be inserted, or possibly some other type of method. It's annoying that at ZPM I can't fully automate a power source like this, so if I want to have my server running 24/7 I have to worry about replacing turbines manually, until I can get the XL version.

### Your Goal

Worry free automatic power gen.

### Your Vision

At LuV and above, players want to be able to automate essential systems like powergen so they don't connect 24hrs later to find their AE is offline because of a maintenance issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LazyFleshWasTaken** [comment]
Does it not take the turbine housing?

**Comment by Zenovis** [comment]
![Screenshot_4](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/171630307/b9f90a4f-3a96-4f50-addf-0347dc7a3fe2)

> Does it not take the turbine housing?
NOPE
They don't work
turbine housings don't function with SC steam turbines, at least not in 2.6

**Comment by ddoubleo** [comment]
IIRC this functionality is reserved for XL turbines on purpose and it is not an oversight

**Comment by Pxx500** [comment]
doesn't look like an intended mechanic to me

**Comment by LazyFleshWasTaken** [comment]
> IIRC this functionality is reserved for XL turbines on purpose and it is not an oversight

Literally all other turbines support the turbine housing. I've used it for a normal steam turbine and it worked.
