### ISSUE TITLE
Conveyor cover inserting items into output slot of BBF

### ISSUE THREAD

**Issue by DapCuber** [GTNewHorizons/GT-New-Horizons-Modpack#16581]
### Your GTNH Discord Username

dapcuber

### Your Pack Version

2.6.1

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Expected a conveyor cover to pull items out a drawer and for the input slots of a BBF to be filled, and re-filled when items were used in crafting.

### The Reality

Instead the conveyor cover pulls items out and inserts them into the BBF's input slots as well as output slots, causing items to be voided.
![Screenshot 2024-06-22 202338](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/173571042/76cb55cb-0716-49dd-a0bc-826f603c2326)
![Screenshot 2024-06-22 202424](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/173571042/87ba2dff-f434-4223-83d5-99e3e486bcf0)

### Your Proposal

Not allowing the BBF to have items be able to be inserted into the output slots.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@DapCuber BBF is not desinged for automation. Use a EBF
