### ISSUE TITLE
You can craft fish from Firm Tofu????

### ISSUE THREAD

**Issue by p3rsonUnknown** [GTNewHorizons/GT-New-Horizons-Modpack#16588]
### Your GTNH Discord Username

p3rsonUnknown

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

isn't tofu a kind of cheese?

### The Reality

You can craft raw fish with firm tofu for some reason.

### Your Proposal

Why can you convert something that's made out of soy milk to a fish? It doesn't make any sense.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by p3rsonUnknown** [comment]
![huh](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/bd3ab645-47a4-429b-9160-53aff3bc6391)

**Comment by chochem** [comment]
its not that particular one. its oredict based.

**Comment by p3rsonUnknown** [comment]
I realised that now yes. You can use it to make a hot dog or a burger :D (or many more things that shouldn't be)
Then the oredict part should be fixed? There's 31 pages of crafts and 2/3rd of them are just cursed.

**Comment by chochem** [comment]
is this a crusade against vegan hotdogs?

**Comment by p3rsonUnknown** [comment]
That's called a sandwich?..

**Comment by BlueHero233** [comment]
It is intended behaviour, firm tofu has the listAllfishraw oredict, therefore it can be turned into fish (for the sake of unifying all the fishes from pams)
