### ISSUE TITLE
Mage's Mace Only Adds Damage Once

### ISSUE THREAD

**Issue by Ruling-0** [GTNewHorizons/GT-New-Horizons-Modpack#16597]
### Your GTNH Discord Username

ruling_

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Applying the focus Mage's Mace to a staff, removing it, then re-applying it should mean the staff has the empowered damage (in this case, 60x2=120).

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47913168/806a22ac-258e-4cb9-bf63-9f019c8cedf5)

### The Reality

Applying the focus, removing it, and then applying it again will not add the damage. Stated otherwise - the focus, if ever removed from a staff, means that specific staff can never make use of the focus again. Bookmarking the staff in this state, deleting it, and spawning one from the bookmark (which preserves item data) will again not properly use the focus. Only spawning a fresh version of the staff will the focus work properly, until it is removed. Name Remover does not fix it. Aside from the screenshotted staff, I have also tested on the creative one (Orichalcum Studded Cosmic Neutronium Staff).

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47913168/8dae951d-fe12-4d17-b437-1af7605191f3)

### Your Proposal

I suspect there's an anti-bug bit of code designed to prevent being able to rapidly swap the focus to boost damage. However, it's currently not working, and it means a staff must be dedicated to Mage's Mace, which is not ideal, and if the focus is ever accidentally removed a new staff must be made (or spawned in). This bug should thus be fixed so the focus can be removed and reapplied as all other focuses can be.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Shahelion** [comment]
Wait...one of those screenshots shows 120 damage, and the other only 6? What's up with that huge difference? The staff bonus should only be x2, and the base damage of the focus is supposed to be around 8 before modification.
