### ISSUE TITLE
The assembler recipe for Ztones Tinted Glass disappeared in 2.6.1

### ISSUE THREAD

**Issue by truepurpledino** [GTNewHorizons/GT-New-Horizons-Modpack#16600]
### Your GTNH Discord Username

purpledino

### Your Pack Version

2.6.1

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

There should be an assembler recipe for tinted glass using 4 aurora blocks and 1 glass block, as there was in 2.5.1.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/75775263/38a2b397-4e85-4ae5-88c8-802f330908c5)

### The Reality

This recipe is simply missing in 2.6.1, others have confirmed this also being the case for their 2.6.1 instance

### Your Proposal

Restore/fix the recipe being missing.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ableytner** [comment]
Seems to be fixed, is it still missing for you in newer versions (beta / nightly)?
