### ISSUE TITLE
Game freezes during initialization, possibly related to openAL

### ISSUE THREAD

**Issue by lePirateMan** [GTNewHorizons/GT-New-Horizons-Modpack#16613]
### Your GTNH Discord Username

lepirateman

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

The freeze happens during the launching process. Usually during "registering gregtech materials" right after "Initializing LWJGL OpenAL" appears in the log, followed by 
"[Thread-21/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.IllegalStateException: Only one OpenAL context may be instantiated at any one time." among other related errors. The game window freezes completly, but some stuff still happens in the multimc log (mostly just craftpressense trying to connect to discord). Sometimes, rarly, it crashes after waiting a bit.

This begun after the game crashed while searching for aura nodes in the twillight forrest with a thaumometer, I have managed to launch the game succesfully once since then, but the game crashed after a few seconds when I swapped held item to thaumometer.

I have managed to launch other modpacks through multimc, and 1.7.10 with forge activated without more problems than normal

OS: Arch linux
GPU: Nvidia 2060
GPU driver: Nvidia open
Multimc version: 0.7.0
Forge version: 10.13.4.1614
java8: openjdk 1.8.0_412

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/16019394/fml-client-latest.log)
[multimc log](https://paste.ee/p/StaUw)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by eigenraven** [comment]
Known LWJGL2 bug on linux, using the java 17+ pack build with lwjgl3ify solves this issue.
