### ISSUE TITLE
KAMI locked behind Primordial Pearl

### ISSUE THREAD

**Issue by MCmaxl17** [GTNewHorizons/GT-New-Horizons-Modpack#16612]
### Your Pack Version

2.6.0

### Your Proposal

As of right now, to unlock Ichorium and all its uses, one needs to unlock - among other things - the alchemical grate (ALCHGRATE), which is locked behind the Advanced Alchemical Furnace (ADVALCHEMYFURNACE), which requires the player to scan a primordial pearl with the thaumometer.
(Technically, Eldritch Epiphany is also required, but doing all the KAMI required research achieves this on the way.)
This is the only Eldritch research required to unlock KAMI.

I suggest either one of the following two improvements:
a) Remove the ALCHGRATE requirement to unlock KAMI.
b) Add other Eldritch related research to the KAMI requirement, but add a warning to the player as early as possible somewhere in the questbook! Possible location: after Warp warnings, since these also warn the player about changes from "vanilla" Thaumcraft.

### Your Goal

In "vanilla" Thaumic Tinkerer KAMI does not require any Eldritch research to be unlocked.
The fact that in GTNH it does comes as a surprise to experienced players.
(Technically it doesn't because one could check with /iskamiunlocked, and then use NEI to figure out that ALCHGRATE depends on the Adv Chemical Furnace, which needs Adv Chemical Construct, which needs Primordial Pearl, but who would check this beforehand?)
Implementing either one of the above mentioned options would remove bad surprises and sudden roadblocks for the player.

### Your Vision

I believe that the KAMI requirement was accidentally added or left in when adding the alchemical grate, as it is absolutely out of place being the only Eldritch research required for KAMI, and also in the questbook the dependence of e.g. Ichor on Primordial Pearls doesn't exist.
Removing the ALCHGRATE requirement would allow for KAMI, Ichorium, and therefore - among other things - the Pure Tear and Purification Talisman research to be crafted earlier, at probably the envisioned progress level of the player and not later.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alastors** [comment]
My guy, the primodial pearl is quicker to get than Kami is as a qjole

**Comment by joshaup1999** [comment]
I dont think alchemical grate should be taken out. If you are using the advanced alchemical furnace construct then sure as hell should be using the alchemical grate or something similar to it. Besides, its 1 extra research

**Comment by MCmaxl17** [comment]
If the vision of the devs is that KAMI should be locked behind the Primordial Pearl and some Eldritch research, then I don't want to argue against that. After all, GTNH is supposed to be a difficult/challenging pack ;-)

However, one remark: ALCHGRATE is the one and ONLY Eldritch research required to unlock KAMI. Other Eldritch research is not explicitly required, only by virtue of being a prerequisite to the ALCHGRATE research. In other words, running /kamiunlocked does **not** tell you to research for example ELDRITCHMAJOR or PRIMPEARL. This way of implementing the requirement of primordial pearls is somewhat "interesting". To be consistent with the other KAMI requirements, every single prerequisite Eldritch research (for example: ELDRITCHMINOR, ELDRITCHMAJOR, PRIMPEARL, ...) should also show up in the list when running /iskamiunlocked.
However, this just as a remark. I also understand if people have higher priorities than this.


My original motivation to open this issue was the repeatable quest (1 week) that allows you to get a Pure Tear. In the quest it is written: "Think wisely about using it, since it's a very long journey to unlock it through research." So my naive expectation is that as long as I have all the materials required in the quest, and then unlock the recipe through a very long journey of research, I can craft Pure Tears myself. This research I could do in peace in my base needing nothing but paper, ink sacks, and research points. But the quest lied to me. I need to do more than research. I need to explore a dungeon and fight a Thaumcraft boss mob while being annoyed by now acquired 70+ Warp effects.
My point is not that this is too difficult. Again, after all, it's GTNH. My point is that the phrasing of the quest is misleading and could lead to annoying surprises.

So, please let me expand on my original suggestions in point b):

- "Think wisely about using it, since it's a very long journey to unlock it through research." (Repeatable Pure Tear quest): Add to this quest text:
- 1) If you want to stay with Thaumcraft philosophy of being vague: "Think wisely about using it, since it's a very long journey to unlock it through research, exploration of far places and crafting powerful wands."
- or
- 2) If you check in the prerequisites of the Purifications Talisman on the KAMI questbook page, it tells you anyways that you need a Primordial pearl. So if you don't care about making it a secret: "Think wisely about using it, since it's a very long journey to unlock it through research, acquiring a Primordial Pearl by killing a boss in The Outer Lands, and having a wand being able to craft recipes with at least 125vis each."
- Add a similar hint/explanation to the Ward Warnings questbook page, for example: "Later on the questbook will give you a repeatable quest to get a Pure tear, which will purge all your warp. However, to craft one yourself, you need to find a Primordial Pearl."
- optional bonus: Add ELDRITCHMINOR, ELDRITCHMAJOR, PRIMPEARL, etc to /iskamiunlocked


I hope I could make my main point clear: I feel badly surprised by the way the Pure Tear quest this quest is written. So either a) remove the bad surprise (ALCHGRATE, probably not the preferred option), or b) rewrite the quest text in a way that it doesn't raise false hopes.


PS: I understand that people could be bewildered about why I am so scared of or annoyed by fighting a boss in The Outer Land. I guess I just prefer sitting in my base all the time. After all, this pack allows you to get Twilight Forest boss drops by using bees...

**Comment by Alastors** [comment]
Frankly I think the Pure Tear quest should be fully removed from the pack instead, the pure tear in itself is just a major crutch
