### ISSUE TITLE
Temporal Harmonizer Catalyst Uncraftable

### ISSUE THREAD

**Issue by Josh5minus1** [GTNewHorizons/GT-New-Horizons-Modpack#16615]
### Your GTNH Discord Username

Due by: Then

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I was testing to craft the catalyst, which is a UXV recipe, with 2 UMV energy hatches, with 2 A UMV supply each. This is only possible in the Precise Assembler: Normal Mode since UXV singleblock machines do not exist.

![2024-06-28_17 09 53](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/54713920/e8bd686a-932f-410a-a33b-555295fe38be)

### The Reality

The controller says needs more power. Using a UXV energy hatch works fine as expected, but it requires UXV components, which requires eternity, which also requires the temporal harmonizer catalyst, which loops back to the unobtainable issue.

![2024-06-28_17 07 51](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/54713920/5a2265cf-0040-423b-bc10-1dcecbdc1c0b)
![2024-06-28_17 08 10](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/54713920/1f35c5f3-553f-4b28-97e9-99abb417790c)

### Your Proposal

Move the recipe tier to UMV, since I don't think precise assembler will be changed to allow the use of two lower voltage hatches to upgrade to next voltage tier (can cause tier skips)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
The lsaa is the uptiering assembler, not the prass

**Comment by Josh5minus1** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/54713920/daf75c11-8d5a-42c4-b13a-807637a24998)
I somehow missed this when looking, I thought it would appear near the PrAss in the end of column lol
