### ISSUE TITLE
Add configuration to control multi auto-building hatches in Multiblock Structure Hologram Projector

### ISSUE THREAD

**Issue by Nxer** [GTNewHorizons/GT-New-Horizons-Modpack#16628]
### Your GTNH Discord Username

Nxer

### Your Pack Version

2.6.1

### Your Proposal

Add a switch to control whether automatic construction automatically places the hatches which makes people very annoying.

### Your Goal

Auto building hatches this function always makes the machine messy and makes people angry. So just add a switch to disable this function.

### Your Vision

Then people will not need to separate those me net to let the auto building do not place hatches.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AtomicGrog** [comment]
Like this, bugs the crap outa me.

**Comment by joshaup1999** [comment]
Would save having to filter a view cell to only access the build blocks

**Comment by FourIsTheNumber** [comment]
Resolved by addition of gt_no_hatch channel
