### ISSUE TITLE
Game Freezes Immediately After Loading

### ISSUE THREAD

**Issue by PFleur** [GTNewHorizons/GT-New-Horizons-Modpack#16632]
### Your GTNH Discord Username

patchoulifleur

### Your Pack Version

2.6.1_Java_17-21

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Launching the game from Prismlauncher under Open-JDK 22.0.1.u0-1, after the xp sound for the modpack having loaded the game freezes.

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/16043043/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
try removing opis I guess its not really needed anyway. But I am not sure exactly what the error means, it might be an issue with graphics drivers.

**Comment by chochem** [comment]
closed in favor of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17421 which has more information
