### ISSUE TITLE
Architecture craft window frames

### ISSUE THREAD

**Issue by Jimbno** [GTNewHorizons/GT-New-Horizons-Modpack#16634]
### Your GTNH Discord Username

Jimbno

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

![Screenshot 2024-06-30 113703](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/80066034/f22223e0-10df-4a1f-a041-1431413a5ded)
If you place window frames together you can click the frame hitbox with a chisel to hide them, but in the latest version this function doesn't seem to work anymore

### The Reality

![Screenshot 2024-06-30 113124](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/80066034/0e01c0af-f1c1-42fb-a399-0a30f7d73fc4)

### Your Proposal

Add the old functionality back where you can seamlessly connect window frames together

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@Jimbno did you know which commit change/break it ?

**Comment by Jimbno** [comment]
I do not know sorry

**Comment by Superfrogman98** [comment]
Forgot I had looked at this a while ago and found that the Thread safety commit was where it broke, specifically the changes around the renderShape function in the Window class

**Comment by Chaoschaot232** [comment]
I can confirm that this bug still exists within 2.7.0 Beta 1

![image](https://github.com/user-attachments/assets/5cc7bb57-1eb5-4575-939a-4722a856a67d)

So I assume what @Superfrogman98 has written is still not fixed, right?
