### ISSUE TITLE
Move some recipes from NEI reycling tabs

### ISSUE THREAD

**Issue by FourIsTheNumber** [GTNewHorizons/GT-New-Horizons-Modpack#16639]
### Your GTNH Discord Username

fouristhenumber

### Your Pack Version

2.6.1

### Your Proposal

The addition of the recycling tabs is really great for reducing clutter, but some of the recipes that have been moved to it really belong in their original tabs. Specifically, I think fluid extracting/macerating ingots should be in the fluid extractor/macerator tab, not recycling. Some examples:
![2024-06-30_14 59 12](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/33456283/1a00cde2-e83f-4330-be6f-147a9f8404f6)
![2024-06-30_15 07 54](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/33456283/88992dc9-96cf-4428-a4fc-4ddaf6a7a5cb)
![2024-06-30_14 59 29](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/33456283/bdf3f068-5f89-45c9-9707-28468dbe3937)
![2024-06-30_14 59 23](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/33456283/d6b72351-038e-4d64-b35e-6f09390920a9)

### Your Goal

Clarity - I spend a lot of time in the help channel, and there is frequent confusion among new players (especially molten tin and obsidian dust) when they cannot find these recipes in NEI. 

### Your Vision

The recycling tabs mostly exist as a dump for the unused recipes that used to clutter their respective tabs, and they are very effective at that - but fluid extracting an ingot is not "recycling" it (recycling something should be reducing a product to its raw resource,  but ingots are already a form of raw resource) - it's just the intended, most obvious way to get molten ingots.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
hmm, this is not that straightforward. nobody manually assigned anything to either tab, these are fully autogenerated based on the recipe generation.
