### ISSUE TITLE
EMT Thaumic Boots upgrading

### ISSUE THREAD

**Issue by Aaur1s** [GTNewHorizons/GT-New-Horizons-Modpack#16630]
### Your Pack Version

2.6.1

### Your Proposal

From now on I will call nano/quantum boots **upgraded** if they are merged with voidwalker/meteor/comet

Thuamic boots from Electro-magic Tools should be craftable from their upgraded versions, e.g. quantum boots craftable from nano boots with voidwalker upgrade

### Your Goal

This is dumb to force players to craft new nano boots for quantum boots if they already upgraded nano. (and vice versa for lower tier)

### Your Vision

Adding simple craft recipes to craft quantum boots(maybe already upgraded) from upgraded nano boots and etc. Cause currently i don't want to upgrade my nano bootss until i get quantum, and it really bothers me.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Aaur1s** [comment]
Still exists

**Comment by StaffiX** [comment]
This has been done by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1072
