### ISSUE TITLE
Broken Spawner infusion recipe

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#16640]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.6.1

### Your Proposal

Add a recipe for the Broken spawner, something difficult so as not to take away the fun of exploring, but if in endgame you want to make an EEC work you don't have to waste time going to a dungeon
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/7f6a4030-6d50-42c2-9ec2-e06a07ddaf86)

- Crucible of souls
- 2 soulariom bars, 2 dark iron bars, 2 sentiend edner, 2 enticing crystals, 2 grains of the end, 2 grains of prescience, 2 unstable dust, 2 soul mould

### Your Goal

Being able to craft a broken spawner

### Your Vision

Qol

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45178400/859e95ab-742c-4a09-9f37-62861605d188)
( Adding a life aggregator, that needs defeating gaia)

**Comment by chochem** [comment]
I know that dream wants us to keep a level of exploration in the pack. And I do agree with that. (feel free to ask him directly when he is back obviously)

but to explore this a bit further, maybe I am missing something: Is there ever any point where you need to massproduce spawners for anything? Keep in mind that already just a single rogue-dungeon gives you a decent number.

**Comment by SMSum** [comment]
> I know that dream wants us to keep a level of exploration in the pack. And I do agree with that. (feel free to ask him directly when he is back obviously)
> 
> but to explore this a bit further, maybe I am missing something: Is there ever any point where you need to mass-produce spawners for anything? Keep in mind that already just a single rogue-dungeon gives you a decent number.

I'll make my rare appearance. While Dream has a totally valid point about wanting to explore, it can get pretty annoying. Mid to late game, you're going to want to set up quite a few EECs for random things, and hunting down 10-20 broken spawners isn't exactly fun. Early game exploration is interesting, but once you've seen everything, you've seen it. At that point, you’d rather not waste time scouting dungeons like a hawk from above.

Ultimately this really just boils down into a nice QOL addition, it's just a simple recipe that I don't see causing any real balancing issues or wasting any item ID's.
