### ISSUE TITLE
Two Oil Cracking Unit will be incomplete if their Clean Stainless Steel Casing close to each other

### ISSUE THREAD

**Issue by mxancl** [GTNewHorizons/GT-New-Horizons-Modpack#16655]
### Your GTNH Discord Username

mxancl#8054

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Form two Oil Cracking Unit whose Clean Stainless Steel Casing close to each other

### The Reality

Incomplete Structure. But if you separate them, leaving an one block interval, both multiblock machine can be formed.

### Your Proposal

Two Oil Cracking Unit can be formed if their Clean Stainless Steel Casing close to each other, or write a tip to notice that you need to separate them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
please post some pics

**Comment by mxancl** [comment]
this problem can't be reproduced in a complete new save, I forgot to test it in a new save rathar than existing save before I open this issue, sorry
