### ISSUE TITLE
please save my gameథ౪థ

### ISSUE THREAD

**Issue by SheIsAnElf** [GTNewHorizons/GT-New-Horizons-Modpack#16654]
### Your GTNH Discord Username

Easypopo#8422

### Your Pack Version

2.6.0.0

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I updated the pack from 2.5.1to 2.6.0. and it appears one minute after I enter the game everytimes.

### Crash Report

[crash.docx](https://github.com/user-attachments/files/16051739/crash.docx)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
Please upload your crash log to https://mclo.gs/ or directly here as a text file.

**Comment by FourIsTheNumber** [comment]
Update to 2.6.1. This is most likely the ae2/enderio + angelica bug that was fixed.

**Comment by SheIsAnElf** [comment]
> Please upload your crash log to https://mclo.gs/ or directly here as a text file.

[crash-2024-07-02_06.10.01-client.txt](https://github.com/user-attachments/files/16059441/crash-2024-07-02_06.10.01-client.txt)
this is my crash log

**Comment by SheIsAnElf** [comment]
> Update to 2.6.1. This is most likely the ae2/enderio + angelica bug that was fixed.

ok let me try this :D

**Comment by chochem** [comment]
that should be fixed by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/517
please update to 2.6.1
