### ISSUE TITLE
Better Questing keeps reloading default quests when it should not be

### ISSUE THREAD

**Issue by Shahelion** [GTNewHorizons/GT-New-Horizons-Modpack#16661]
Mod: Better Questing

I was altering some quests and questlines in a test world. I usually make quite a few changes before saving as defaults. Normally, the world-specific quests do not revert themselves.

Right now, every time I quit and rejoin that world, any changes I had made that were not saved to the defaults are undone. I tested this by adding a basic new quest and changing one of the questline backgrounds, leaving the world, and rejoining. When I loaded in to the world, that new quest was gone and the background had reverted to what it was before.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
reloading on start is on purpose. its very nice for players.

if you are working on big quest PR you should certainly save and commit regularly so that shouldnt be an issue.

**Comment by Shahelion** [comment]
It should be a config option, it is not default behaviour for the mod. Also, if the game crashes, any changes made in that world would be lost. I expected it to save, and lost about an hour of work because of this change.
