### ISSUE TITLE
Add a multi type massive item cell for UMV/UXV tier

### ISSUE THREAD

**Issue by srdr2k3** [GTNewHorizons/GT-New-Horizons-Modpack#16663]
### Your GTNH Discord Username

@srdra

### Your Pack Version

nightly 533

### Your Proposal

Add a massive cell to hold possibly billions of items aimed towards UMV/UXV tier with limited item types (10-12).

### Your Goal

Currently, with the new pattern optimization feature and Stargate craft needing billions of items, some patterns get multiplied higher than the item limit of 16384k cells and break universal automation. 

It's semi-hard to avoid it due to the sheer amount of patterns to keep an eye out for and horrible to fix since you can't know until the craft gets stuck.

That's why I propose a multi-type quantum cell. It'd hold around 2 billion items in total with 10-12 types of items. That way Universal automation would be less PITA later on.

Yes, I know cribs exist. But it'd have me re-do my entire infrastructure right before gate... again.

### Your Vision

Make other automation setups viable!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
apparently they forgot to close this
