### ISSUE TITLE
Allow T3 maintenance Hatch (Auto-tap) Wall-shareable

### ISSUE THREAD

**Issue by ramseyspace** [GTNewHorizons/GT-New-Horizons-Modpack#16676]
### Your GTNH Discord Username

Ramsey#7916

### Your Pack Version

2.6.1

### Your Proposal

Since Auto Maintenance (T2) can share through multiple machines. Why not allow T3 Auto-tap to share multiple machines.

### Your Goal

Allows us to make compact wall sharing setups and allows more energy hatches & buses.

### Your Vision

This would reduce spam of needing more quad machines and now you can infinitely row multi blocks instead.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
It could also be gated with a new tier of maintenance hatch, that uses a T3 hatch + endgame material, and that can be shared through multiple machines
