### ISSUE TITLE
AE2 flat interface assembler recipe incorrect

### ISSUE THREAD

**Issue by nullmana** [GTNewHorizons/GT-New-Horizons-Modpack#16683]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

All AE2 interface recipes use the same items (4 titanium plates, 2 fluix cables, 1 of each core)

### The Reality

Only the assembler recipe for the flat interface inexplicably uses 2 annihilation cores instead of 1
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/84821967/32615752-68d1-408b-ae2e-5a536932dcd3)

### Your Proposal

Make all AE interface recipes consistent

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment]
Fixed in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/862
