### ISSUE TITLE
Chunk build failed

### ISSUE THREAD

**Issue by Yoshy2002** [GTNewHorizons/GT-New-Horizons-Modpack#16709]
### Your GTNH Discord Username

yoshy1952

### Your Pack Version

2.6.1

### Your Server

private Server

### Java Version

Java 17

### Type of Server

None

### Your Actions

Playing the Game normally, when i suddenly crash to Main Menu with the Error "Chunk Build Failed". Happens at random Times, while being AFK or actively playing. Happens like 5-10 Times per Day. I've tried updating EnderIO, still happens multiple times per Day, sometimes even within 5 Minutes. 

### Crash Report

[crash-2024-07-08_19.21.58-client.txt](https://github.com/user-attachments/files/16133423/crash-2024-07-08_19.21.58-client.txt)
[crash-2024-07-08_17.10.24-client.txt](https://github.com/user-attachments/files/16133436/crash-2024-07-08_17.10.24-client.txt)
[crash-2024-07-08_19.17.38-client.txt](https://github.com/user-attachments/files/16133438/crash-2024-07-08_19.17.38-client.txt)
[crash-2024-07-08_16.34.17-client.txt](https://github.com/user-attachments/files/16133439/crash-2024-07-08_16.34.17-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/1894689/6ac3c1e9-1d63-41f7-9912-6bc735fdb24f)

Did you?

**Comment by Yoshy2002** [comment]
only found 1 post referring to updating enderio, which i did but didnt help

**Comment by mitchej123** [comment]
I'd rather revive old tickets, or existing tickets than making new ones; or at the very least if the old issues are closed then link them.

I've seen a few of this issue pop up both here and on the angelica issue tracker....

**Comment by mitchej123** [comment]
Commenting on the github issue that suggested updating, would be super helpful context that 1) you did update 2) the expected fix didn't work for all cases

**Comment by Yoshy2002** [comment]
Ive opened a new one because all the ones that are currently open, dont describe exactly my error/crash. And sorry for not linking closed ones with this issue, im new to github and especially writing issues here.

**Comment by mitchej123** [comment]
👍 

Please link any existing closed ones and indicate they were not fixed; I'll reopen this one

**Comment by Yoshy2002** [comment]
#16586 Same Crash with newest EnderIO Version.
#16363 Same Error, but not crashing on world enter, just random times.
[crash-2024-07-09_00.20.09-client.txt](https://github.com/user-attachments/files/16134961/crash-2024-07-09_00.20.09-client.txt)
the other crash reports only had enderio 2.8.9, tho it already had "Work around CME by @mitchej123 in https://github.com/GTNewHorizons/EnderIO/pull/166"
newest crash report is with enderio [2.8.12-pre](https://github.com/GTNewHorizons/EnderIO/releases/tag/2.8.12-pre)

**Comment by toadjaune** [comment]
We seem to have the same crash, here are a few logs : 
[crash-2024-07-09_22.04.54-client.txt](https://github.com/user-attachments/files/16168448/crash-2024-07-09_22.04.54-client.txt)
[crash-2024-07-09_22.05.50-client.txt](https://github.com/user-attachments/files/16168449/crash-2024-07-09_22.05.50-client.txt)
[crash-2024-07-09_22.08.46-client.txt](https://github.com/user-attachments/files/16168450/crash-2024-07-09_22.08.46-client.txt)
[crash-2024-07-10_22.12.11-client.txt](https://github.com/user-attachments/files/16168451/crash-2024-07-10_22.12.11-client.txt)

* modpack version `2.6.1`
* Java 21
* Prism launcher

Crash occurs after up to a few minutes (sometimes as fast as a few seconds) ; I can provide a world zip if that helps with debugging.

Disabling Angelica makes the crash disappear entirely (so far)

**Comment by Pxx500** [comment]
this issue didn't automatically close after the merge, I'll do it now

**Comment by toadjaune** [comment]
I gave it a quick run with version `2.8.14` of EnderIO on my local test world, that sporadically exhibited the crash, and so far it looks like it fixes it.

I'd gladly test it on our server as well, but I can't connect with the mod only updated client-side, and I can't go patch a single mod on the server in the short term.

By any chance, is there any way to make this work with mismatched versions of the client and server mod ?

**Comment by mitchej123** [comment]
I'd say grab the commit the server is using, cherry pick the commit, and then compile it locally with `VERSION=<override> bash gradlew build`

**Comment by toadjaune** [comment]
I was hoping to not have to set up the entire development toolchain ^^'

But ok, I'll try to find some time and motivation to give it a try :)
Thanks for the exact command, this will save me some time.

**Comment by toadjaune** [comment]
I can confirm that the fix works !
Thanks :)


Also, I have to say, I'm impressed at the tooling, allowing a complete build without any manual toolchain install, that's some pretty neat work :)
