### ISSUE TITLE
crashing with no warning

### ISSUE THREAD

**Issue by xlk9000** [GTNewHorizons/GT-New-Horizons-Modpack#16700]
### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Actions

Exploring

### Crash Report

Launched instance in online mode

login.microsoftonline.com resolves to:
    [40.126.28.13, 40.126.28.23, 40.126.28.14, 40.126.28.19, 40.126.28.21, 20.190.135.2, 40.126.28.20, 40.126.28.11]

session.minecraft.net resolves to:
    [13.107.246.35]

textures.minecraft.net resolves to:
    [13.107.246.35]

api.mojang.com resolves to:
    [13.107.246.35]

Minecraft folder is:
C:/Users/localadmin/AppData/Roaming/PrismLauncher/instances/GT_New_Horizons_2.6.0_Java_8/.minecraft

Java path is:
C:/Program Files (x86)/Common Files/Oracle/Java/java8path/javaw.exe

Java is version 1.8.0_411, using 64 (amd64) architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/instances/GT_New_Horizons_2.6.0_Java_8/natives

Libraries:
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [🖿] 1.7 (folder)
  [✔] AdvancedSolarPanel-1.7.10-3.5.1a
  [✔] adventurebackpack-1.1.3-GTNH
  [✔] ae2fc-1.2.28-gtnh
  [✔] ae2stuff-0.7.0-GTNH
  [✔] AFSU-1.3.0-GTNH
  [✔] alchgrate-1.1.0-GTNH
  [✔] amazingtrophies-1.2.1
  [✔] AmunRa-GC-0.5.1
  [✔] angelica-1.0.0-alpha40
  [✔] AngerMod-0.7.1
  [✔] AppleCore-3.3.0
  [✔] appliedenergistics2-rv3-beta-352-GTNH
  [✔] archaicfix-0.7.2
  [✔] ArchitectureCraft-1.9.5
  [✔] Aroma1997Core-1.7.10-1.0.2.16
  [✔] AromaBackup-1.7.10-0.1.0.0
  [✔] AsieLib-0.5.5
  [✔] Automagy-1.7.10-0.28.2
  [✔] Avaritia-1.49
  [✔] Avaritiaddons-1.7.1-GTNH
  [✔] backpack-2.3.0-GTNH
  [✔] bartworks-0.9.21
  [✔] battlegear2-1.3.7
  [✔] Baubles-1.0.4
  [✔] bdlib-1.10.0-GTNH
  [✔] beebetteratbees-0.4.0-GTNH
  [✔] BetterAchievements-0.2.0
  [✔] BetterBuildersWands-0.11.1-GTNH
  [✔] bettercrashes-1.4.0-GTNH
  [✔] betterloadingscreen-1.6.1-GTNH
  [✔] betterp2p-1.2.1
  [✔] BetterQuesting-3.5.13-GTNH
  [✔] BiblioCraft[v1.11.7][MC1.7.10]
  [✔] BiblioWoods[BiomesOPlenty][v1.9]
  [✔] BiblioWoods[Forestry][v1.7]
  [✔] BiblioWoods[Natura][v1.5]
  [✔] binnie-mods-2.3.4
  [✔] BiomesOPlenty-1.7.10-2.1.0.2308-universal
  [✔] BlockLimiter-0.6.0
  [✔] blockrenderer6343-1.1.6
  [✔] BloodArsenal-1.3.2
  [✔] BloodMagic-1.5.2
  [✔] Botania-1.10.12-GTNH
  [✔] BotanicHorizons-1.1.2-GTNH
  [✔] BrandonsCore-1.1.0-GTNH
  [✔] bugtorch-1.2.13-GTNH
  [✔] buildcraft-7.1.39
  [✔] buildcraft-compat-7.1.17
  [✔] BuildCraftOilTweak-1.1.1
  [🖿] carpentersblocks (folder)
  [✔] CarpentersBlocks-3.5.3-GTNH
  [✔] catwalks-2.2.1-GTNH
  [✔] chisel-2.14.1-GTNH
  [✔] chiseltones-1.1.0-GTNH
  [✔] CodeChickenCore-1.2.1
  [✔] CoFHCore-[1.7.10]3.1.4-329
  [✔] CompactKineticGenerators-1.7.10-1.0
  [✔] Computronics-1.7.2-GTNH
  [✔] controlling-2.0.2
  [✔] CookingForBlockheads-1.3.4-GTNH
  [✔] CoreTweaks-1.7.10-0.3.3.2-nomixin
  [✔] CraftPresence-2.3.9-1.7.10
  [✔] CraftTweaker-3.3.1
  [✔] creativecore-1.4.0-GTNH
  [✔] CropLoadCore-0.2.0
  [✔] CropsPP-1.6.5
  [✔] custommainmenu-1.11.2
  [✔] defaultkeys-1.2.0
  [✔] defaultserverlist-1.5.0
  [✔] defaultworldgenerator-0.3.0
  [✔] Draconic-Evolution-1.3.5-GTNH
  [✔] DummyCore-1.18.0
  [✔] duradisplay-1.2.3
  [✔] EMT-1.4.6
  [✔] endercore-0.4.6
  [✔] EnderIO-2.7.4
  [✔] EnderStorage-1.5.1
  [✔] EnderZoo-1.1.0
  [✔] EnhancedLootBags-1.1.1
  [✔] eternalsingularity-1.2.1
  [✔] extrautilities-1.2.13a
  [✔] findit-1.2.5
  [✔] FloodLights-1.3.0
  [✔] Forbidden.Magic-0.7.0-GTNH
  [✔] Forestry-4.8.9
  [✔] forgelin-1.9.9-GTNH
  [✔] ForgeMultipart-1.4.8
  [✔] ForgeRelocation-0.1.2
  [✔] ForgeRelocationFMP-0.1.0
  [✔] gadomancy-1.3.2
  [✔] galacticgreg-1.1.0
  [✔] Galacticraft-3.1.5-GTNH
  [✔] GalaxySpace-1.1.83-GTNH
  [✔] gendustry-1.7.0-GTNH
  [✔] ggfab-0.3.19
  [✔] GoodGenerator-0.8.22
  [✔] GraviSuite-1.7.10-2.0.3
  [✔] gravisuiteneo-1.1.5
  [✔] gregtech-5.09.45.163
  [✔] GT.Scanner.Mod-1.8.0
  [✔] gtneioreplugin-1.2.0
  [✔] GTNewHorizonsCoreMod-2.3.50
  [✔] gtnhintergalactic-1.3.4
  [✔] gtnhlanth-0.12.12
  [✔] gtnhlib-0.2.11
  [✔] GTNH-TC-Wands-1.4.0
  [✔] GT-PlusPlus-1.11.58
  [✔] GTTweaker-2.1.0
  [✔] HardcoreDarkness-MC1.7.10-1.7
  [✔] HardcoreEnderExpansion-1.10.1-GTNH
  [✔] harvestcraft-1.1.10-GTNH
  [✔] Healer-1.2.1
  [✔] HelpFixer-1.2.0
  [✔] hodgepodge-2.4.43
  [✔] holoinventory-2.4.7-GTNH
  [✔] HungerOverhaul-1.7.10-1.0.0.jenkins104
  [✔] hydroenergy-1.2.0
  [🖿] ic2 (folder)
  [✔] IC2 Crop Plugin Version 1.7.10-1.3.1
  [✔] IC2NuclearControl-2.6.2
  [✔] ifu-1.10.2
  [✔] IguanaTweaksTConstruct-2.4.1
  [✔] industrialcraft-2-2.2.828a-experimental
  [✔] InfernalMobs-1.8.1-GTNH
  [✔] InGameInfoXML-2.8.8
  [✔] INpureCore-1.2.0-GTNH
  [✔] inventorytweaks-1.6.2
  [✔] IronChest-6.0.85
  [✔] IronChestMinecarts-1.1.0
  [✔] irontanks-1.3.0
  [✔] JABBA-1.3.3
  [✔] journeymap-1.7.10-5.2.3-fairplay
  [✔] kekztech-0.10.4
  [✔] kubatech-0.14.7
  [✔] littletiles-1.3.0-GTNH
  [✔] logisticspipes-1.1.5-GTNH
  [✔] lootgames-2.1.1
  [✔] LunatriusCore-1.2.0-GTNH
  [✔] magicbees-2.7.15-GTNH
  [✔] malisisdoors-1.16.4-GTNH
  [✔] Mantle-0.4.1
  [✔] mobsinfo-0.2.6-GTNH
  [✔] ModTweaker2-0.10.0
  [✔] modularui-1.1.42
  [✔] MouseTweaks-2.4.17-GTNH
  [✔] mxrandom-0.3.0
  [✔] Natura-2.6.1
  [✔] naturescompass-1.4.0-GTNH
  [✔] NEIAddons-1.15.0
  [✔] NEICustomDiagram-1.5.17
  [✔] NEIIntegration-1.4.0
  [✔] netherportalfix-1.2.0
  [✔] NodalMechanics-1.2.1-GTNH
  [✔] NotEnoughEnergistics-1.5.1
  [✔] notenoughIDs-2.0.3
  [✔] NotEnoughItems-2.5.27-GTNH
  [✔] nutrition-0.0.10
  [✔] oauth-1.2.2-GTNH
  [✔] OpenBlocks-1.9.1-GTNH
  [✔] OpenComputers-1.10.11-GTNH
  [✔] OpenGlasses-1.5.0-GTNH
  [✔] OpenModsLibs-0.10.9
  [✔] OpenModularTurrets-2.3.2
  [✔] openprinter-0.2.0-GTNH
  [🖿] OpenSecurity (folder)
  [✔] opensecurity-1.1.1-GTNH
  [✔] Opis-1.4.2-mapless
  [✔] overloadedarmorbar-1.1.0
  [✔] Pam's Harvest the Nether 1.7.10a
  [✔] personalspace-1.0.30
  [✔] PlayerAPI-1.4.4
  [✔] ProjectBlue-1.2.0-GTNH
  [✔] ProjRed-4.9.5-GTNH
  [✔] Railcraft-9.15.8
  [✔] RandomThings-2.5.3
  [✔] RemoteIO-2.5.2
  [✔] roguelike-1.6.0-GTNH
  [✔] Schematica-1.11.1-GTNH
  [✔] ServerUtilities-2.0.35
  [✔] SGCraft-1.4.4-GTNH
  [✔] sharewhereiam-2.1.1
  [✔] sleepingbag-0.2.1
  [✔] SpecialMobs-3.5.0
  [✔] SpiceOfLife-2.1.7-carrot
  [✔] StevesAddons-0.12.3
  [✔] StevesCarts-2.1.1
  [✔] StevesFactoryManager-1.2.3-GTNH
  [✔] StorageDrawers-1.13.5-GTNH
  [✔] StorageDrawersBop-1.12.0-GTNH
  [✔] StorageDrawersForestry-1.12.0-GTNH
  [✔] StorageDrawersMisc-1.12.0-GTNH
  [✔] StorageDrawersNatura-1.12.0-GTNH
  [✔] structurecompat-0.5.0
  [✔] structurelib-1.3.1
  [✔] Supersolarpanel-1.1.3
  [✔] SuperTic-1.3.0
  [✔] Tainted-Magic-7.6.4-GTNH
  [✔] tcinventoryscan-1.1.4-GTNH
  [✔] tcneiadditions-1.3.6
  [✔] tcnodetracker-1.2.0
  [✔] TConstruct-1.11.15-GTNH
  [✔] TecTech-5.3.45
  [✔] TGregworks-1.7.10-GTNH-1.0.26
  [✔] Thaumcraft-1.7.10-4.2.3.5a
  [✔] Thaumcraft4Tweaks-1.5.22
  [✔] ThaumcraftMobAspects-1.1.0-GTNH
  [✔] thaumcraftneiplugin-1.7.10-1.7a
  [✔] ThaumcraftResearchTweaks-1.1.0
  [✔] Thaumic Machina-1.7.10-0.2.1
  [✔] Thaumic-Based-1.6.7
  [✔] thaumicboots-1.2.1
  [✔] thaumicenergistics-1.6.5-GTNH
  [✔] Thaumic-Exploration-1.2.5-GTNH
  [✔] ThaumicHorizons-1.5.3
  [✔] thaumicinsurgence-0.3.1
  [✔] ThaumicTinkerer-2.9.4
  [✔] TiCTooltips-1.3.1
  [✔] tinkersdefense-1.2.2
  [✔] TMechworks-0.3.1
  [✔] TooMuchLoot-4.2.0-GTNH
  [✔] torohealth-1.1.0
  [✔] Translocator-1.2.1
  [✔] TravellersGear-1.7.10-1.16.6
  [✔] travellersgearneo-1.1.0
  [✔] TwilightForest-2.5.23
  [✔] txloader-1.7.0
  [✔] -unimixins-all-1.7.10-0.1.17
  [✔] Universal-Singularities-8.7.0
  [✔] visualprospecting-1.2.11
  [✔] Waila-1.7.3
  [✔] WailaHarvestability-1.2.1-GTNH
  [✔] WAILAPlugins-0.4.0
  [✔] WanionLib-1.9.0
  [✔] WarpTheory-1.3.7-GTNH
  [✔] Wawla-1.2.0-GTNH
  [✔] WirelessCraftingTerminal-1.11.2
  [✔] witchery-1.7.10-0.24.1
  [✔] WitcheryExtras-1.2.2
  [✔] WitchingGadgets-1.4.3-GTNH
  [✔] WR-CBE-1.5.0
  [✔] YAMCore-0.6.0
  [✔] Ztones-1.7.10-2.2.2

Params:
  --username  --version 1.7.10 --gameDir C:/Users/localadmin/AppData/Roaming/PrismLauncher/instances/GT_New_Horizons_2.6.0_Java_8/.minecraft --assetsDir C:/Users/localadmin/AppData/Roaming/PrismLauncher/assets --assetIndex 1.7.10 --uuid  --accessToken  --userProperties  --userType  --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Launcher: standard

Couldn't extract native jar 'C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar' to destination 'C:/Users/localadmin/AppData/Roaming/PrismLauncher/instances/GT_New_Horizons_2.6.0_Java_8/natives'
Couldn't extract native jar 'C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar' to destination 'C:/Users/localadmin/AppData/Roaming/PrismLauncher/instances/GT_New_Horizons_2.6.0_Java_8/natives'
Couldn't extract native jar 'C:/Users/localadmin/AppData/Roaming/PrismLauncher/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar' to destination 'C:/Users/localadmin/AppData/Roaming/PrismLauncher/instances/GT_New_Horizons_2.6.0_Java_8/natives'

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by xlk9000** [comment]
and i tried to use different launchers

**Comment by Lyfts** [comment]
Something didn't close correctly, restart your pc.
