### ISSUE TITLE
I can not log in to the server after I took in the inventory ore that has no name

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#16712]
### Your GTNH Discord Username

eldrinn_elantey

### Your Pack Version

2.6.1

### Your Server

privat server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Was processing ore and noticed an ore named Unnamed in a chest. I took it into my inventory and after a second I got an error message and got kicked off the server. Crash-report attached

### Crash Report

https://mclo.gs/kKKCsg9

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Eldrinn-Elantey** [comment]
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/46845681/0756f844-2563-4a10-92b2-00cb99a0422d)

**Comment by Lyfts** [comment]
Hmm, what could possibly be the reason that you have a self compiled version of Hodgepodge and AmunRa specifically 🤔

**Comment by Lyfts** [comment]
Yeah I thought as much. Feel free to reopen once you have managed to reproduce it with official release versions of the mods and perhaps a paid account.

**Comment by Eldrinn-Elantey** [comment]
I have a license. The server runs in offline mode so that friends without a license can access the server. Moreover, I myself could not access the server until I replaced these two mods.

What do they have to do with the GregTech ore?

**Comment by Eldrinn-Elantey** [comment]
The problem turned out to be due to the translation of GTNH-ru_RU-Translation-Nightly-2024-07-07+128

**Comment by Eldrinn-Elantey** [comment]
@Lyfts The problem is not the mod but the lang file from GTNH-ru_RU-Translation-Nightly-2024-07-07+128

**Comment by Lyfts** [comment]
Okay

**Comment by Eldrinn-Elantey** [comment]
@Lyfts I don't have the option of reopening

**Comment by Eldrinn-Elantey** [comment]
The problem was the translation. In several lines %material was written as %Material
