### ISSUE TITLE
Transcendent Plasma Mixer doesn't identify circuit in Crafting Input Buffer

### ISSUE THREAD

**Issue by hoshinokiseki** [GTNewHorizons/GT-New-Horizons-Modpack#16710]
### Your GTNH Discord Username

hoshinokiseki

### Your Pack Version

Nightly 520

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Transcendent Plasma Mixer can identify circuit in Crafting Input Buffer

### The Reality

Transcendent Plasma Mixer doesn't identify circuit in Crafting Input Buffer

### Your Proposal

FIX IT

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16579   like this？
