### ISSUE TITLE
Alchemy Grate crashes game when viewing its research page

### ISSUE THREAD

**Issue by AnrDaemon** [GTNewHorizons/GT-New-Horizons-Modpack#16726]
### Your GTNH Discord Username

AnrDaemon

### Your Pack Version

private/non-GTNH

### Your Server

private MP

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Researched the item and tried to look up its research page in the Thaumonomicon.

The game client crashed instantly blaming impossibility to render the research.

### Crash Report

[crash-2024-07-11_00.17.36-client.txt](https://github.com/user-attachments/files/16169570/crash-2024-07-11_00.17.36-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by EnderProyects** [comment]
private/non-GTNH ? The alchemy grate recipe is modified and uses gregtech and botania items

**Comment by AnrDaemon** [comment]
Outside the pack, it does not use GTNH specific recipe.
Botania's Open Crate, it do use.
May be it uses OpenBlocks something if Botania is not present, I'm not in the mood to experiment.

**Comment by EnderProyects** [comment]
If you are using the fork of GTNH of the mod it should use the GTNH specific recipe, since there is no other recipe in the code
( I know this because I´m the one that changed the recipe lmao)

**Comment by AnrDaemon** [comment]
Then you did it wrong. Please fix it. The recipe is visible in NEI, but it's not craftable ingame.

**Comment by EnderProyects** [comment]
> Then you did it wrong. Please fix it. If the mod is not GTNH exclusive, the recipe should be wrapped into control block.
> 
> The recipe you added is useless, the original recipe was very intentionally an upgrade of an existing grate to the new one. With new recipe, all you could do with all your existing grates is to throw them into infernal blast furnace and watch them burn for a few moments.

The mod just adds one recipe, you could just take the mod out of curse, I dont have time at the moment to "fix" something of a year ago, also that I´m far away from my computer

**Comment by Alastors** [comment]
Lmfao just download the normal version of alchemy grate, there’s literally no difference besides recipe

**Comment by EnderProyects** [comment]
> all you could do with all your existing grates is to throw them into infernal blast furnace

Also since you dont play GTNH maybe you dont know that the hungry chest recipe uses the existing grate in the recipe, so is just an upgrade, you dont have to trash anything

**Comment by AnrDaemon** [comment]
Thanks for explanation guys. Let's call it a misunderstanding.
I've seen a number of releases, but did not paid attention to specifics.

**Comment by Alastors** [comment]
Yeah that's one thing that annoys me about how GTNH does some things, we feel an intrinsic need to push a BS update every two seconds to every mod for no particular reason
