### ISSUE TITLE
Raw Ores cannot be molten in the TiC Smeltery

### ISSUE THREAD

**Issue by GirixK** [GTNewHorizons/GT-New-Horizons-Modpack#16738]
### Your GTNH Discord Username

GirixK

### Your Pack Version

Nightly 2024-07-12 550

### Your Server

Private

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Attempting to smelt Raw Ore--for this example we'll use Malachite--in the TiC Smeltery results in the ore being molten into it's.. molten form--in this case copper

### The Reality

Attempting to smelt the previously mentioned ore does nothing

As you can see in these images, no progress bars are appearing, and there exists no "Smeltery" tab, note the lack of arrow buttons at the top
![image](https://github.com/user-attachments/assets/9e3cee2b-4f50-44bd-b60c-f6355d7cac6a)
![image](https://github.com/user-attachments/assets/dc246921-f527-47aa-a4aa-8c58e4718396)

### Your Proposal

Make Raw Ores behave identically to it's full-block counterparts; allowing for the ability to smelt Raw Ores in the smeltery

Image showcasing (Fullblock) Malachite Ore having a smeltery recipe
![image](https://github.com/user-attachments/assets/a9101d41-3266-43b5-8799-631ffea383d1)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
yea need to be added

**Comment by chochem** [comment]
should be fixed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/901
