### ISSUE TITLE
Any Item dupe using Quest Book

### ISSUE THREAD

**Issue by RubyGeoduck** [GTNewHorizons/GT-New-Horizons-Modpack#16731]
### Your Pack Version

2.6.1

### Your Server

Private server

### Java Version

Java 17

### Type of Server

Open To LAN

### Your Expectation

claim loot bag

### The Reality

claimed loot bag and can do it again and again as long as I don't disconnect
[https://youtu.be/burNwuuxNgI](url)

### Your Proposal

UHHHH patch it pls?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
> Type of Server: Open To LAN

We do not support Open To LAN due to the nature of how it is coded to support multiple players in a single player session and adding many bugs.
