### ISSUE TITLE
something from create

### ISSUE THREAD

**Issue by 610610gg** [GTNewHorizons/GT-New-Horizons-Modpack#16736]
### Your Pack Version

1.7.10

### Mod Name

create (not all of it tho, just some things)

### The Mod to Add

so, basically, there are 3 things some people would like (they could also just be added in a fork of gtnh but would be nice to see them in the official one): sequenced processing, the sequenced processing from the create mod could be something that could add  unique use to some things and it could be a mid to late game thing. movable contraptions and trains, just whatch this video and you will understand why they could be nice: https://www.youtube.com/watch?v=rR8W-f9YhYA , also, it could be made so that the trains can go to both the twilight forest and space and also the end truh some wormhole like thing (or for space, a funnier options would be rocket trains, or simply rockets attached to trains that need refueling when they land, and they would also need a ramp and a rail that makes them speed up based on the voltage and tier, needing the max tier and voltage for getting to the most far planet/moon reachable).

### Your Reason

it would be a good implementation because it could make the players be able to build some interesting stuff, like gigantic create styled wood farms that generate lots of wood, maybe even of every type, or just making some gigantic stuff like houses that hide themselfs (or lawn bases that hide themselfs) and it would be great in general (another thing from create that could be added are minecart contraptions, but that's optional).

### Preliminary Investigation

(i just put something to fill this here bc i alredy said everything, also, i tried seeing if create mod was an open source mod but didn't find anything about it, but it would be nice if this was done with the official create team for the basics, or with just a smol part of it)

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by Cleptomania** [comment]
Backporting this stuff is a tremendous amount of work and not likely to happen unless someone who wants it does the work, regardless of wether it makes sense for the pack or not.

**Comment by benjamin-kirkbride** [comment]
> i tried seeing if create mod was an open source mod but didn't find anything about it


https://github.com/user-attachments/assets/a4d5dd74-f448-44f6-ac60-1828bbe3ff72

**Comment by FourIsTheNumber** [comment]
> > i tried seeing if create mod was an open source mod but didn't find anything about it
> 
> simplescreenrecorder-2024-07-12_17.42.14.mp4

It does not exist for 1.7.10, someone would have to backport the entire mod.

**Comment by benjamin-kirkbride** [comment]
> someone would have to backport the entire mod. Or the parts of it that they want, at least.

all he wants is sequenced processing, movable contraptions, and trains

**Comment by srdr2k3** [comment]
that is the entire mod

**Comment by Leclowndu93150** [comment]
thanks for the good laugh

**Comment by ReclipseTheOne** [comment]
Greate New Horizons

**Comment by benjamin-kirkbride** [comment]
> that is the entire mod

Not true! Create has a potato gun, which is not part of this request. I may open an issue for that separately though

**Comment by 610610gg** [comment]
with my requests am slowly becoming a meme at this point

**Comment by Dream-Master** [comment]
:trollface:

**Comment by Leclowndu93150** [comment]
> with my question and suggestions am slowly becoming a meme at this point

https://www.reddit.com/r/feedthememes/comments/1e1twfg/most_sane_create_fans/

**Comment by 610610gg** [comment]
right, there is that, that i had alredy seen on discord i think
