### ISSUE TITLE
Extreme Industrial Greenhouse doesn't accept all advertised lamps

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#16748]
### Your GTNH Discord Username

Combsuter

### Your Pack Version

2.6.1

### Your Server

Delta

### Java Version

Java 17

### Type of Server

None

### Your Expectation

The tooltip says "Purple lamps are from ProjectRedIllumination. They can be powered and/or inverted"

I expect therefore that both purple lamps with a redstone signal to turn them on, and inverted purple lamps that are on by default would create a functional multiblock

### The Reality

- The inverted purple lamps are not accepted. The multiblock does not form.
- Unpowered normal lamps _are_ accepted

### Your Proposal

I'd like to see the inverted lamps work, because it saves me from setting up a lot of redstone to light up the thing and make it look as intended.

As an optional extra, it would be nice if the multi is aware of the redstone state and only accept either lamp as long as they give off light.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
should be fixed in dev with https://github.com/GTNewHorizons/GT5-Unofficial/pull/2616
