### ISSUE TITLE
Please save my saves again〒▽〒

### ISSUE THREAD

**Issue by SheIsAnElf** [GTNewHorizons/GT-New-Horizons-Modpack#16759]
### Your GTNH Discord Username

Easypopo#8422

### Your Pack Version

2.6.1.0

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

https://github.com/user-attachments/assets/5901488c-78bb-4c96-9a38-a4603502a35d

Acknowledge what happen and solve this problem

### The Reality

Good evening.
The convey wont work while on the input bus on the mb. It just cant import or export items. And not only convey, things like SFM alse not worked. This happened on the machine build recently, because convey and SFM works perfectly on those mbs that build long time ago. I tried to reinstalled the pack, this problem fixed by doing this. But my ae network crushed without any reasons. Fortunately I backup my saves and the old versions of game(just the game before my reinstalled, not really old version. it is also 2.6.1) . I can provide that if you need.

### Your Proposal

solve the problem. either fix the old version problem which is inputbus bug, or fix the ae crushed problem happened after reinstall the pack

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SheIsAnElf** [comment]
> can.t.replicate.mp4 
> can't replicate, but maybe i'm not noticing something

I know you can't repeat. It just happened in this save.

**Comment by Pxx500** [comment]
maybe there's something in the logs when you tried to send items

**Comment by SheIsAnElf** [comment]
Also, just knowing that reinstall can't fix this problem.

**Comment by SheIsAnElf** [comment]
> maybe there's something in the logs when you tried to send items

is there anyway to fix that?

**Comment by Pxx500** [comment]
you didn't even provide any logs to check that, I can't say anything since I have no information about the error to begin with

**Comment by SheIsAnElf** [comment]
> you didn't even provide any logs to check that, I can't say anything since I have no information about the error to begin with

I saw a folder named logs. There is ton of file in it. Is that what we needed?

**Comment by Pxx500** [comment]
send fml clients, and gregtech, also latest

**Comment by SheIsAnElf** [comment]
[latest.log](https://github.com/user-attachments/files/16237054/latest.log)
[latest.log](https://github.com/user-attachments/files/16237056/latest.log)
I found gregtech and latest, but not fml clients

**Comment by Pxx500** [comment]
send the world if possible

**Comment by SheIsAnElf** [comment]
that file is like 1.83GB. but i can upload it to the google drive

**Comment by Pxx500** [comment]
yeah

**Comment by Ethryan** [comment]
C:\Users\85926\AppData\Roaming\.technic\modpacks\mcnewhorizons\mods\forgelin-1.9.9-GTNH.jar - probably a corrupt zip

Found this in your log, might want to test redownloading it and see if it fixes anything.

**Comment by Pxx500** [comment]
In that case it would be better to move to prism and java 21/22 
https://gtnh.miraheze.org/wiki/Installing_and_Migrating

**Comment by SheIsAnElf** [comment]
> In that case it would be better to move to prism and java 21/22 https://gtnh.miraheze.org/wiki/Installing_and_Migrating

let me try this

**Comment by SheIsAnElf** [comment]
> C:\Users\85926\AppData\Roaming.technic\modpacks\mcnewhorizons\mods\forgelin-1.9.9-GTNH.jar - probably a corrupt zip
> 
> Found this in your log, might want to test redownloading it and see if it fixes anything.

i will try this

**Comment by SheIsAnElf** [comment]
> C:\Users\85926\AppData\Roaming.technic\modpacks\mcnewhorizons\mods\forgelin-1.9.9-GTNH.jar - probably a corrupt zip
> 
> Found this in your log, might want to test redownloading it and see if it fixes anything.

do you mean redownload "forgelin-1.9.9-GTNH.jar"?

**Comment by Pxx500** [comment]
you won't have to do that after you move to newer java and prism anyway

**Comment by SheIsAnElf** [comment]
https://drive.google.com/file/d/1Rrqpl9nLt-DnCPfXkVqCfVE98aLfXZ-F/view?usp=sharing
and this is my world.

**Comment by Pxx500** [comment]
So you launched the game using java 21/22 on prism and the conveyor still didn't work? Or did the game not work

**Comment by SheIsAnElf** [comment]
in my world, you can see a multi smelter just near the fusion reactor, and there is a crystal chest and input bus with conveyor on it. this conveyor is working, because this set up was built long time ago. you can try to build a new mb, with a input bus with conveyor, it wont work.

**Comment by SheIsAnElf** [comment]
> So you launched the game using java 21/22 on prism and the conveyor still didn't work? Or did the game not work

what is java21/22

**Comment by SheIsAnElf** [comment]
i may use java8

**Comment by Pxx500** [comment]
![image](https://github.com/user-attachments/assets/7177d468-0a73-4bc7-9634-1f6a26b3b731)
there is no broken ebf on the save from what I can see

**Comment by SheIsAnElf** [comment]
> ![image](https://private-user-images.githubusercontent.com/81298696/348788402-7177d468-0a73-4bc7-9634-1f6a26b3b731.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNjI0MDAsIm5iZiI6MTcyMTA2MjEwMCwicGF0aCI6Ii84MTI5ODY5Ni8zNDg3ODg0MDItNzE3N2Q0NjgtMGE3My00YmM3LTk2MzQtMWY2YTI2YjNiNzMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDE2NDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwMTM3NDBjN2IzYTE2ZDI1OWQ5Y2FmODM0YmUxMTM5MTA5NmNkNDdmZTIzNzI3NTZhZmNkYTAwODAxN2QwYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmRmB59joSPSJRodu3nJEaj2Ltqg_EPwSJat6pAcJB4) there is no broken ebf on the save from what I can see

you can build one with input bus and conveyor, then try to use that conveyor to import items from chest or so

**Comment by Pxx500** [comment]
go to discord if you can't reintall the game to prism ill help yuu

**Comment by Pxx500** [comment]
fixed after moving to new java
