### ISSUE TITLE
When placing  4 "Blue Orchid" on cropsticks, it converts to rose seeds instead

### ISSUE THREAD

**Issue by qunYp3dZSyLjoEoEg** [GTNewHorizons/GT-New-Horizons-Modpack#16757]
### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

I tried to place 4 blue orchids on cropsticks in order to grow them for rainbow curry.

### The Reality

Fully grown rose seeds appeared on the cropsticks. 

### Your Proposal

Please make it so that it makes a blue orchid seed which maybe even drops blue orchids when grown (so as to increase the viability of rainbow curry as a regular food for gtnh) or blue dye, or doesn't place them on the cropsticks at all. Or make a confirmation screen appear that ttells the user that the orchids will be converted to rose seeds. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
thats normal and not a bug. there is no blue orchid ic2 crop.
