### ISSUE TITLE
Client freeze after playing some hours: 2.7. Nightly - 520 / Zeta

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#16755]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.7. Nightly - 520

### Your Server

Zeta

### Java Version

Java 8

### Type of Server

None

### Your Actions

Playing up to ZPM at my home -> freeze of the client but not closed.

Tested with different launcher (MMC, myFTB, ATLauncher) and different Computer and Internet Connections

### Crash Report

https://paste.myftb.de/uxitucozev

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
i will update zeta soon to see if the problem still exist
