### ISSUE TITLE
GTNH 2.6.1 crashes with Et Futurum Requiem installed

### ISSUE THREAD

**Issue by Gcat101** [GTNewHorizons/GT-New-Horizons-Modpack#16758]
### Your GTNH Discord Username

gcat101

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

1. Install GTNH 2.6.1 using the Prism jar
2. Download EFR 2.6.0 from curseforge and add to the pack
3. Launch the instance
4. Experience the crash

### Crash Report

Notice: I tried launching the game with 2 different EFR configs, so there are 2 crash logs. More info in the comment below.

1. https://pastebin.com/SvYmUk4P
2. https://pastebin.com/UVq3HB8h

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Cleptomania** [comment]
There are config changes that have to happen for EFR to work, and we are intending to include EFR in the pack in 2.7.0.

See #16436

**Comment by Gcat101** [comment]
As mentioned in the original post, I used 2 separate configs. The first one is a minimal config which disables most of the mod's functionality except spectator mode. The second one is the default config (obtained after deleting the custom config, regenerating and launching the game again)

I have some more logs from both attempts, so I'll attach them here:

1 (lightweight config):

* [GregTech.log](https://github.com/user-attachments/files/16236147/GregTech.log)
* [fml-client-latest.log](https://github.com/user-attachments/files/16236149/fml-client-latest.log)
* [latest.log](https://github.com/user-attachments/files/16236150/latest.log)

2 (default config):

* [GregTech.log](https://github.com/user-attachments/files/16236168/GregTech.log)
* [fml-client-latest.log](https://github.com/user-attachments/files/16236170/fml-client-latest.log)
* [latest.log](https://github.com/user-attachments/files/16236158/latest.log)

No other changes have been made to the pack, only the addition of EFR and the config change.

**Comment by Gcat101** [comment]
> There are config changes that have to happen for EFR to work, and we are intending to include EFR in the pack in 2.7.0.
> 
> See #16436

oh didn't know there is a recommended config, knew about the plans to add it in 2.7.0 but I am currently hosting an event where I need the spectator mode so I am trying to add it by myself

**Comment by Gcat101** [comment]
Whoops, forgot about one section in my "lightweight" config, which is apparently the required one. Disabled it and it launched successfully, thanks!
