### ISSUE TITLE
 Weird consumption on DTPF Infinity recipe

### ISSUE THREAD

**Issue by RealSilverMoon** [GTNewHorizons/GT-New-Horizons-Modpack#16768]
### Your GTNH Discord Username

real_silver_moon

### Your Pack Version

2.7.0 Nightly 514

### Your Proposal

DTPF recipe should have some advantanges with high tier coils.

### Your Goal

Considering these two recipes:
![1](https://github.com/user-attachments/assets/43cc21ed-5c6a-47cd-bc16-0d435cf4aa2e)
![64](https://github.com/user-attachments/assets/20a3732a-02a6-47c7-b3f7-0f593ab9425a)
A: 62,400,000eu + 920 excitedDTCC + 1.95s = 144ml infinity
B: 512,000,000,000eu + 58932 excitedDTCC + 250s = 64*144ml infinity
If we multiply A by 64 times:
64A: 3,993,600,000eu + 58000 excitedDTCC + 124.08s = 64*144ml infinity
more DTCC, more electricity, more time, what is the point of the B recipe existing?

### Your Vision

Buff the poor recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by NotAPenguin0** [comment]
You get more molten infinity per infinity catalyst.

**Comment by RealSilverMoon** [comment]
I believe Infinity catalyst would be the most insignificant thing in the recipe, no matter using EIC or Neutronium comprseeor. 63  Infinity catalyst can't worth 777,332,851,000 eu at all.

**Comment by pionxyz** [comment]
In the version DTPF first appeared, there was no 1 toc and infinity catalyst can only be obtained from the Void Mining Machine. So this recipe is useful.
For the current version, I think this recipe should indeed be modified.
