### ISSUE TITLE
To the GTNH mods team, can you add ElectricalAge to the GTNH Modpack?

### ISSUE THREAD

**Issue by xxeer** [GTNewHorizons/GT-New-Horizons-Modpack#16767]
### Your GTNH Discord Username

[NEEDY GIRL OVERDOSE] 糖糖 OR needygirloverdose.

### Your Pack Version

1.7.10 2.6.1

### Mod Name

ElectricalAge

### The Mod to Add

It can simulate the circuits, voltages, etc. of real factories, or build monitoring systems for nuclear power or any power generation facilities. It can also decorate factories because ElectricalAge adds many realistic lamps and poles.

I downloaded it from https://github.com/age-series/ElectricalAge

### Your Reason

Want to decorate my base and build a power generation monitoring system

### Preliminary Investigation

Yes, I tried to put it into GTNH modpack. It works, but all his blocks and items have no crafting recipes. Then his Chinese translation is incomplete and needs to add more ways to detect the machine status. It currently only supports monitoring redstone signals.

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by xxeer** [comment]
Yes I know it is a beta version, but it takes up very little performance, but its functions are also very useful for decorating the base

**Comment by xxeer** [comment]
If you try to play this mod, you will definitely feel its fun.

**Comment by boubou19** [comment]
it's not just a matter of dropping the mod into the pack, we also need to check if the mod is compatible with the vision we have of the modpack. Rn it seems to be some additional bloat. Maybe fun, but still bloat.

**Comment by xxeer** [comment]
Okay, but if you have the opportunity, please consider joining the electrical age

**Comment by dvdmandt** [comment]
I looked at this for a bit, and it looks like a really cool, ambitious, polished and so on mod, with a compatible license (LGPL). It is however based on a completely different power system with some very similar concepts, yet not the same or compatible. From a glance, almost all of the functional content it adds already has counterparts/duplicates in GTNH, and the art style (while looking very good!) is completely different from anything in GTNH, so it would look really weird and out of place. Basically, it looks like a really cool mod, but not something that belongs in GTNH.

Just looking at the art style, it might make more sense to try to integrate this mod with HBMs NTM and possibly some of Reikas stuff.

**Comment by xxeer** [comment]
This mod seems to have the ability to convert the energy it emits into RF energy
