### ISSUE TITLE
Dragging from NEI to bookmarks pane crashes

### ISSUE THREAD

**Issue by Ruling-0** [GTNewHorizons/GT-New-Horizons-Modpack#16763]
### Your GTNH Discord Username

ruling_

### Your Pack Version

Nightly 553

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

1. Click and drag item from NEI on the right, pulls a stack
2. Drag to open bookmark pane on the left, anywhere
3. Click to release
4. Crash

### Crash Report

[crash-2024-07-15_19.11.13-client.txt](https://github.com/user-attachments/files/16241495/crash-2024-07-15_19.11.13-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by mitchej123** [comment]
Are you sure you attached the correct crash log?  That one is from may 12th, and is related to the texture cache and the loading screen.  (also of note - that has been fixed)

**Comment by Ruling-0** [comment]
> Are you sure you attached the correct crash log? That one is from may 12th, and is related to the texture cache and the loading screen. (also of note - that has been fixed)

Yeah, that's my bad (one window had dates sorted one way, the other another. Edited with a fresh crash report.

**Comment by mitchej123** [comment]
That makes significantly more sense....

```
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "handlerName" is null
    at codechicken.nei.BookmarkPanel.addOrRemoveItem(BookmarkPanel.java:1280)
    at codechicken.nei.PanelWidget.handleClickExt(PanelWidget.java:268)
    at codechicken.nei.LayoutManager.mouseClicked(LayoutManager.java:216)
    at codechicken.nei.guihook.GuiContainerManager.mouseClicked(GuiContainerManager.java:459)
    at net.minecraft.client.gui.inventory.GuiContainer.mouseClicked(GuiContainer.java)
    at net.minecraft.client.gui.GuiScreen.handleMouseInput(GuiScreen.java:296)
    at net.minecraft.client.gui.inventory.GuiContainer.handleMouseInput(GuiContainer.java)
```

**Comment by Ruling-0** [comment]
Fixed on nightly 560
