### ISSUE TITLE
Please save my saves again〒▽〒

### ISSUE THREAD

**Issue by SheIsAnElf** [GTNewHorizons/GT-New-Horizons-Modpack#16760]
### Your GTNH Discord Username

Easypopo#8422

### Your Pack Version

2.6.1.0

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

https://github.com/user-attachments/assets/5901488c-78bb-4c96-9a38-a4603502a35d

Acknowledge what happen and solve this problem

### The Reality

Good evening.
The convey wont work while on the input bus on the mb. It just cant import or export items. And not only convey, things like SFM alse not worked. This happened on the machine build recently, because convey and SFM works perfectly on those mbs that build long time ago. I tried to reinstalled the pack, this problem fixed by doing this. But my ae network crushed without any reasons. Fortunately I backup my saves and the old versions of game(just the game before my reinstalled, not really old version. it is also 2.6.1) . I can provide that if you need.

### Your Proposal

solve the problem. either fix the old version problem which is inputbus bug, or fix the ae crushed problem happened after reinstall the pack

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
duplicate

**Comment by Pxx500** [comment]
![image](https://github.com/user-attachments/assets/cef3204c-d018-4fd1-a72c-5b9d48ef0fd3)
no one else has this problem, it would break the entire game so how could we even miss this
