### ISSUE TITLE
The stick texture of GTplusplus is wrong

### ISSUE THREAD

**Issue by FurnaceGT** [GTNewHorizons/GT-New-Horizons-Modpack#16772]
### Your GTNH Discord Username

empty

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

nothing

### The Reality

![663C7DBC0F124C708540F9CCFC8AEA3B](https://github.com/user-attachments/assets/6b3dad10-392e-4c6a-a8be-dc96dec50797)
![994CE844F46BAB52130C521EB60EACED](https://github.com/user-attachments/assets/47d794a5-0ecc-4bd2-8e83-422e6476588e)
![F3F623B59332E9308E39DAFCC65DF55F](https://github.com/user-attachments/assets/5c4c658a-5287-45b8-97fe-401e475ae640)

### Your Proposal

repair it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
which stick is this?

**Comment by FurnaceGT** [comment]
Every  stick texture of GTPP  is like this ,it has a wrong color block .
