### ISSUE TITLE
Game crashing right after loading into game

### ISSUE THREAD

**Issue by koelekinker123** [GTNewHorizons/GT-New-Horizons-Modpack#16777]
### Your GTNH Discord Username

Timon._.

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

My SSD got full and my game crashed. Now my game crashes every time I load into it.

### Crash Report

[crash-2024-07-17_18.46.05-server.txt](https://github.com/user-attachments/files/16270577/crash-2024-07-17_18.46.05-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
use a backup from before
