### ISSUE TITLE
Gregtech is crashing on startup at 83% on initializing gregtech consistantly

### ISSUE THREAD

**Issue by Aglacor434** [GTNewHorizons/GT-New-Horizons-Modpack#16783]
### Your GTNH Discord Username

Glacors

### Your Pack Version

2.6.1 java 17- 21

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

1. Launching the pack from either the curseforge launcher or from Prism launcher
2.  will consistantly crash at the 83% mark on initializing gregtech

So i was interested in playing this pack and initially tried it from curse forge and had this issue. The nice people in the discord led me to using prism launcher so I tried to launch the 2.6.1 java 17-21 version through that and unfortunately it crashed at the same exact spot. 
I have tried launch from both launchers, reinstalling the pack, and trying to launch the pack with angelica removed because I saw that mentioned on a thread here, but sadly it consistently crashes at the same spot every time and I am not sure why.

a friend of mine who is also new to the pack launched it with no issue so im not sure what issue i seem to be having.

### Crash Report

https://pastebin.com/yb8y2cAV pastebin with the crash log

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
upload it to https://mclo.gs/, not pastebin

**Comment by Aglacor434** [comment]
https://mclo.gs/nbBxA8Z posted to mclo

**Comment by Caedis** [comment]
Can you try https://adoptium.net/temurin/releases/ ? JRE 21

**Comment by Aglacor434** [comment]
so i uninstalled my java and installed the JRE 21 msi and loaded the pack up and it did work, walked around. Closed the pack to try and open it again to make sure it was not a one time thing and it crashed at the same spot. 

here is an attached Mclo of the new crash https://mclo.gs/X0JjGln 
there was some progress at least though but im not sure why it would have hitched up again after a successful launch

**Comment by Pxx500** [comment]
Quick Google search suggests that it's more of a PC issue instead of a modpack issue. Try some basic fixes that can be searched on Google maybe they'll help.

**Comment by Aglacor434** [comment]
do you have any suggestions as to what fixes? I was googling this issue and the only thing I saw was something about Ram, I have a pretty high end pc and other modpacks are working for me so im not entirely sure what i should even be trying as far as basic fixes go, i don't know a ton about pcs so ive been searching for fixes related to the pack crashing on startup but that seems to mostly just lead me back here.

**Comment by dvdmandt** [comment]
Do a memory test and some form of CPU stress test, in particular multithreaded performance. GTNH has a few steps on loading that are very CPU intensive (multithreaded) and that has triggered hardware faults for other people in the past (pretty recently). Very few other modpacks, if any, have such intensive steps that can fully saturate a modern high end CPU.

**Comment by Aglacor434** [comment]
awesome thank you i will try those today after work, sorry for asking that i just am very much a noob when it comes to pc related things as I use it just mostly for work and games so this is very much out of my depth

**Comment by Aglacor434** [comment]
so  I think I found a solution, I didn't have Xmp enabled in the bios setting for my Ram which seems to have allowed the pack to load up consistently.  I really appreciate all of your guy's help with my issue. Excited to finally start playing the pack
