### ISSUE TITLE
Gregtech Plascrete Mob Spawning

### ISSUE THREAD

**Issue by AhoyCapn** [GTNewHorizons/GT-New-Horizons-Modpack#16788]
### Your GTNH Discord Username

Capn#4296

### Your Pack Version

2.6.0

### Your Proposal

Mobs should not be able to spawn on Plascrete. It doesn't make sense that aggressive mobs can spawn inside a Cleanroom, as it is a sterile area.

### Your Goal

So that you don't have to use specific items that prevent mob spawns, or place anything unnecessary inside the cleanroom. I understand that what I mentioned are pretty simple fixes, but I would love to have the option not to use them/

### Your Vision

It would make it less of a headache overall and make more sense "realistically" (obviously it's a video game but I like these types of additions to the game.)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LazyFleshWasTaken** [comment]
Mobs _don't_ spawn on plascrete.

On the other hand, if you have an elevator inside, they can spawn on it.
