### ISSUE TITLE
WAILA Running Mode Incorrect for Material Press

### ISSUE THREAD

**Issue by Ruling-0** [GTNewHorizons/GT-New-Horizons-Modpack#16799]
### Your GTNH Discord Username

ruling_

### Your Pack Version

Nightly 553

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Industrial Material Press should state the correct running mode in the WAILA HUD, such as Bending for bending machine and Forming Press for forming press.

### The Reality

They are flipped - below is an IMP in forming press mode:
![image](https://github.com/user-attachments/assets/489b6142-f116-41a4-9a6b-2e2543666230)

One in bending mode shows forming press:
![image](https://github.com/user-attachments/assets/07e08ac9-1642-45d1-b025-b562178cf552)

### Your Proposal

The WAILA HUD should be accurate to the machine mode.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Whoops. This is definitely my fault, on it

**Comment by Dream-Master** [comment]
@FourIsTheNumber yea i saw somethings in the commit that flip it but i thought it was intended. just make a fix i can approve it.

**Comment by FourIsTheNumber** [comment]
I did flip it intentionally since it was reversed for me - Ruling says they don't have the button, so they don't actually have my changes. I think the flip I did will actually _fix_ this rather than causing it

> @FourIsTheNumber yea i saw somethings in the commit that flip it but i thought it was intended. just make a fix i can approve it.

**Comment by Ruling-0** [comment]
@FourIsTheNumber has it fixed in their latest build (merged with their mode switch PR), closing.
