### ISSUE TITLE
Replace Maceration Stack output to bottom layer, delete outputs on each layer

### ISSUE THREAD

**Issue by dimazha** [GTNewHorizons/GT-New-Horizons-Modpack#16804]
### Your GTNH Discord Username

Dart_Voider

### Your Pack Version

2.6.1

### Your Proposal

Give an opportunity to place output in bottom layer of Maceration Stack. Remove upper outputs

### Your Goal

Nobody uses upper outputs in Maceration Stack. They was added long ago to prevent void when Macerator produces a lot of items in output. But since that time we got ME Output and Super Buses, so now upper ouputs are an useless, outdated and annoying feature.

Also without upper outputs the only remaining output will be able to place in any casing including bottom layer like in structures of other GT++ mechs.

### Your Vision

It will make building and using Maceration Stack more convenient. In order not to break the already built Macerators the new structure must include output buses in any casing and limit of structure casings like in other GT++ mechs. So the update of Macerator will not break setups

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by evgengoldwar** [comment]
I agree. To put 5 outputs to not use them seems like nonsense

**Comment by boubou19** [comment]
it's non sense only if you want to use the ME output buses/ super buses. The 5 buses are here only because since you can have parallels on something that yields a lot of outputs (lapis or redstone for instance) you need some buffer. Ok nowadays everyone wants to use the ME output buses, but the arguments given in favor of the removal are too light to really consider it:

> It will make building and using Maceration Stack more convenient.

> Also without upper outputs the only remaining output will be able to place in any casing including bottom layer like in structures of other GT++ mechs.

Structurelib and survival autoplace already take you by the hand to build the maceration stack. And once it's built with one hatch or 5, what's the difference in usage if you place the ME output bus at the bottom? I feel like this issue is more an issue with the survival autoplace that places the hatches randomly rather than an issue with the maceration stack structure.

**Comment by dimazha** [comment]
> And once it's built with one hatch or 5, what's the difference in usage if you place the ME output bus at the bottom

With ME Output Bus in bottom layer I can hide all cables in basement like I can do with other GT++ mechs.

> Structurelib and survival autoplace already take you by the hand to build the maceration stack.

Yes and after that I need to turn excess buses inside to hide them and fill them with junk like cobblestone if I don't use ME Output Bus. Additional actions for nothing. If 1 Output Bus is too little you will be able to put 2-3-4 buses in any structure casing like other GT++ mechs allow. We will receive Macerator with same options like today, but also with QoL changes for those who are tired of mumbo jumbo every time you need to build a Macerator

**Comment by boubou19** [comment]
> > And once it's built with one hatch or 5, what's the difference in usage if you place the ME output bus at the bottom
> 
> With ME Output Bus in bottom layer I can hide all cables in basement like I can do with other GT++ mechs.

and you can do this with or without the proposed change.
> 
> > Structurelib and survival autoplace already take you by the hand to build the maceration stack.
> 
> Yes and after that I need to turn excess buses inside to hide them and fill them with junk like cobblestone if I don't use ME Output Bus. Additional actions for nothing. If 1 Output Bus is too little you will be able to put 2-3-4 buses in any structure casing like other GT++ mechs allow. We will receive Macerator with same options like today, but also with QoL changes for those who are tired of mumbo jumbo every time you need to build a Macerator

Realistically, how many maceration stacks do you build in a run? 10? Buses could be optional yes, and they will probably be, but wrench 4 blocks after a survival autoplace is more than acceptable.

**Comment by dimazha** [comment]
> and you can do this with or without the proposed change.

No, I can't
I need to lower it by one block if I want to hide cable. So why other mechs have an ability to place ME Output in bottom layer and Macerator don't?
![image](https://github.com/user-attachments/assets/459cf5ff-03a1-4205-be3c-a354c8bd0b47)


> but wrench 4 blocks after a survival autoplace is more than acceptable

Yes, It is, but it is still a crutch that does nothing except interfere. I have a suggestion that will not harm to players who use or want to use old Macerator structure. I know a dev who already said that he can and want to realize my suggestion. Maybe it's better to make pack a little bit better than search for reasons why that's fine and we don't have to do anything

**Comment by evgengoldwar** [comment]
I'm willing to try to do it if it doesn't get thrown out.

**Comment by boubou19** [comment]
go ahead then

**Comment by chochem** [comment]
apparently thye forgot to close this
