### ISSUE TITLE
Left/Right click and drag inventory out of the 3x3 crafting slots in crafting table loses the placed inventories in the slots 

### ISSUE THREAD

**Issue by nahso** [GTNewHorizons/GT-New-Horizons-Modpack#16806]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

The placed inventories still in the slots even if I drag the item out of the 3x3 area.

https://github.com/user-attachments/assets/3c758ada-94ca-44ad-b91c-ad837c4d8745

### The Reality

The placed items loses.

https://github.com/user-attachments/assets/4710641c-4f66-47c8-8060-943d0b229c0e

### Your Proposal

The placed items should still be in the 3x3 slots.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by nahso** [comment]
Solved by enabling RMBTweak in Mouse Tweak Configuration

**Comment by Impos913** [comment]
This is an annoying behavior and mousetweaks config default should be changed to enable RMB Tweak. Not everyone would know to change mousetweaks config, but most likely it is annoying to everyone.

**Comment by wlhlm** [comment]
I too stumble over this from time to time.

@chochem It looks like you were the last person to change that setting in #16145. Was this an intentional change? I can see the old config had it [enabled](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/2d1db6f074db5c1fc8497d59aeb8b2261f2964cd/config/MouseTweaks.cfg#L4)

**Comment by chochem** [comment]
I only changed LMBTweakWithItem because its very broken, I did not touch this one.
