### ISSUE TITLE
EnderIO Farming Station not compatible with most modded saplings

### ISSUE THREAD

**Issue by sojourner-fishsticcc** [GTNewHorizons/GT-New-Horizons-Modpack#16807]
### Your Pack Version

2.6.0

### Your Proposal

The EnderIO Farming Station cannot accept saplings from other mods like Biomes O' Plenty and GT+, afaik it only allows vanilla saplings and rubber saplings from IC2. 

### Your Goal

At the moment GT+ rainforest oak saplings aren't compatible with the farming station which makes automating them much more difficult

### Your Vision

I don't think this is a super major change, I just think that the farming station should be compatible with all saplings, especially ones important for automation.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EngineerXL** [comment]
I'm playing EnderIO 2.9.22 and have the same issue. Farming station can't plant MineFactoryReloaded rubber sapplings.

**Comment by Dream-Master** [comment]
we have the source so a fix can be added i would say.
