### ISSUE TITLE
Crashing on startup at 33% with GTNH Nightly build 2024-07-21+559

### ISSUE THREAD

**Issue by kexes** [GTNewHorizons/GT-New-Horizons-Modpack#16810]
### Your GTNH Discord Username

☣ KeXe5 ☢

### Your Pack Version

GTNH Nightly build 2024-07-21+559

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Nothing, waiting for the game to start up.

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/16324043/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
nightly not working rn . use older versions

**Comment by Dream-Master** [comment]
version older than 19.7.24
