### ISSUE TITLE
[Quest] Keeping Your Network Happy - AE Energy Cell AE Quantity

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#16816]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Quest mentions 200k AE cell (100 kEU)

### The Reality

Actual is 2m AE cell (1 mEU)

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by OlliedeLeeuw** [comment]
can be closed, fixed in (#16828)
