### ISSUE TITLE
In the "Bio for the Masses" quest tab the "Faster Charcoal Quest" has inconsistent information compared to the "Two Big Ovens Quest "

### ISSUE THREAD

**Issue by qunYp3dZSyLjoEoEg** [GTNewHorizons/GT-New-Horizons-Modpack#16822]
### Your Pack Version

2.6.1

### Your Server

private Server

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

I tried to find out how long a coke oven takes to produce one charcoal for my own calculations and since I could remember reading something like that in the questbook, I decided to go look for that info (wasn't 100% sure how many ticks were in a second). 
As I couldn't manage to find the 90s figure in the FC-quest for quite some time, I decided to look up the individual charcoal (Cc) time in the TBO-quest and multiply it by 19 to get the actual time, as that was the number of coke ovens that was mentioned in the FC quest, expecting the correct time as the result. 

### The Reality

As I got 71.25 second from that calculation however I decided to look some more since I doubted the mod authors would make a recipe take that long. I decided to divide the tick-number by 20 since that was the number I could remember for ticks/second for normal gameplay, which got me 90 seconds which sounded a lot more believable. 
Then, after taking a look at the FC quest it also says 90s for one Cc in there. So I decided to divide the 90 by 3.75 to find out the nnumber of coke ovens (CO) to produce a Cc every 3.75 seconds, and got to 24. 
After reading the TBO-quest again, I also found out that it says 24 COs for two RC LP boilers in there. The previous quest however says 19 COs for two RC LP boilers. 

### Your Proposal

Change the quest-text for one (or both if needed) of the quests so that both of them have the accurate numbers. According to the wiki (https://gtnh.miraheze.org/wiki/Railcraft_Boiler), the 3*4\*3 RC LP boilers consume 16.2 burntime of fuel per tick at max heat, so 1600/16.2=98,76543209876543 ticks per Cc equals 98,76543209876543/20=4,938271604938272 s per Cc. If we divide 90 by the seconds per charcoal to find out how many COs we need to fuel one LP boiler with Cc, we get 90/4,938271604938272=18,22500000000000. So, rounding up, the 19 CO figure does seem correct for now. 

As, according to the wiki and NEI in game, the Creosote Oil gets produced at the same speed in regards to fuel burn time, and according to the wiki Creosote Oil outside of buckets does have the same burn-time since 2.5.0, we would need the same amount of COs to fuel the liquid RC LP boiler (it produced 250mb of creosote oil per charcoal which has a burn time of 1600 ticks as well, as 1000mb of creosote oil has 6400). 

In summary, change the TBO quest text so that it says it only takes 19 COs for 2 RC LP boilers to run full time with a little headroom in terms of Cc and Creosote Oil production, and that 19 COs produce a charcoal every 4,736842105263158 seconds. As long as the numbers on the wiki are correct I believe the calculations should be too, feel free to double-check please. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by qunYp3dZSyLjoEoEg** [comment]
Also sorry for the long proposal-text, didnÄ't know where else to put the calculations.

**Comment by chochem** [comment]
so much text but I guess you just mean that one was adjusted from 24 to 19 and the other forgotten.

**Comment by qunYp3dZSyLjoEoEg** [comment]
Well I just wanted to show the calculations as I thought saying sorta "Muh change the numbers from 24 to 19 trust me bro" would be potentially ill-received, but yes. And the text to make the numbers and calculations legible.

**Comment by Keridos** [comment]
One thing to note: I have a 24 CO setup feeding 2 LP RC Boilers. I noticed that the creosote oil is all used up by the fluid boiler. However the charcoal (turned to blocks) is not and is backing up. 
Is that due to me compressing the charcoal or might the fuel values for Creosote  be too low?
