### ISSUE TITLE
basic microwave not compatible with stated LV power

### ISSUE THREAD

**Issue by chris-freimuth** [GTNewHorizons/GT-New-Horizons-Modpack#16825]
### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

placed basic microwave in my main machine room on a 4 amp lv cable

### The Reality

explosion about 1 second after placing it. Didn't even open the GUI

### Your Proposal

i guess the basic microwave falsely has lv power in its tooltip or rather isn't implemented as lv machine. the machine itself looked different and i guess its actually ULV.

Checked in creative and it didn't explode instantly on a 4 amp lv cable. I guess, it exploding once you place anything metalic in it is intended, but thats not what i did

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
![image](https://github.com/user-attachments/assets/b9eb7b7b-a72a-4b3a-be65-5c5f59601e6c)
works just fine in LV

**Comment by chochem** [comment]
all working
