### ISSUE TITLE
The moon buggy does not accept fuel

### ISSUE THREAD

**Issue by brnaaaa** [GTNewHorizons/GT-New-Horizons-Modpack#16826]
### Your GTNH Discord Username

.barnac

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

It would be cool if moon buggy could be fuel loaded

### The Reality

Yes, almost no one crafts moon buggy, but you can't load fuel into it at all. I've tried diesel, cetane-boosted diesel and rp-1 rocket fuel, but it didn't work. I also was looking a similar troubles in discord, but i didn't find anything.
![изображение](https://github.com/user-attachments/assets/139f7ad1-a428-4c8f-a293-4163fe788fd4)

### Your Proposal

Ability of fuel loading in moon buggy.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Shinusei** [comment]
Pull request with fix created
https://github.com/GTNewHorizons/Galacticraft/pull/93
