### ISSUE TITLE
Text in thaumonomicon

### ISSUE THREAD

**Issue by rikktav** [GTNewHorizons/GT-New-Horizons-Modpack#16820]
### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

I waneI wanted to read the text in thaumonomicon, but I can't because it goes off the screen
![image](https://github.com/user-attachments/assets/a05313cf-5b73-4ec8-aad0-54516f32f96e)

### The Reality

I wanted to read the text in thaumonomicon, but I can't because it goes off the screen

### Your Proposal

I wanted to read the text in thaumonomicon, but I can't because it goes off the screen

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by rikktav** [comment]
I solved the problem, she ended up in a texture pack

**Comment by chochem** [comment]
resolved
