### ISSUE TITLE
Add recipes for different types of p2p tunnels

### ISSUE THREAD

**Issue by dimazha** [GTNewHorizons/GT-New-Horizons-Modpack#16837]
### Your GTNH Discord Username

Dart_Voider

### Your Pack Version

2.6.1

### Your Proposal

Add craft recipes for different types of p2p tunnels like redstone tunnel, GT EU tunnel fluid tunnel etc. It can be done as shaped crafts on workbench with a screwdriver or as recipes with config circuit in assembler.

### Your Goal

It would be very useful in setup building. It won't be necessary to hold chest, bucket or redstone in inventory to change type of tunnel. It is especially important when you use Ring of Loki. You place 100 tunnels in one click but must to click on each to change their type

### Your Vision

It will make setup building more comfortable

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by S4mpsa** [comment]
You can already change the type of the tunnel using the Advanced Memory Card, only need a single item which you likely are using anyways when working with tunnels.
