### ISSUE TITLE
[Questbook] Wireless Setup Quest (Security Terminal) is a prerequisite to automating cleanrooms

### ISSUE THREAD

**Issue by jusvit** [GTNewHorizons/GT-New-Horizons-Modpack#16843]
### Your Pack Version

2.6.1

### Your Proposal

This issue is for bad quest book design regarding automating your cleanroom. The quest requiring you to make a Security Console which is way more difficult than a Wireless Setup Kit and Wireless Connector (Which doesn't need the security console).

I just bypassed the prerequisite quest and automated my cleanroom with the quest after it after someone told me about it.

This quest:
![image](https://github.com/user-attachments/assets/4367686f-d8eb-4a2a-8ce2-d4a1ede26be2)

Is before this quest:
![image](https://github.com/user-attachments/assets/4a30a0b6-4674-47a8-b160-942c97f099d1)

In the Applied Energetics tab:
![image](https://github.com/user-attachments/assets/014cfe7a-6fd1-4be5-b054-4e08c8de9cda)

However, the "ME in Your Cleanroom" quest has no requirement for anything in "Wireless Setup", and is actually much easier to do than crafting a security console (Which requires EV and HV machines of types you probably wouldn't have).

I recommend flipping it or moving the "ME in Your Cleanroom" quest to be a direct child of " Storing your ME Data"

### Your Goal

NA

### Your Vision

NA

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
maybe something has changed in AE or I dont remember exactly. But how do you link it to the network without the terminal?

**Comment by chochem** [comment]
oh just the wireless connectors. yea they dont need that
