### ISSUE TITLE
Scaffold/Catwalk Duplication when broken by TC hammer AoE

### ISSUE THREAD

**Issue by AlexanderChenhall** [GTNewHorizons/GT-New-Horizons-Modpack#16844]
### Your GTNH Discord Username

Alex

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Breaking a 3x3 grid of scaffolds with a hammer, you would expect 9 to drop, or in the case of the catwalk mod for 9 to be added to your inventory.

### The Reality

The 9 scaffolds are added to your inventory, however the blocks that are broken by the hammers aoe are also dropped as physical items. End result is that 9 scaffolds become 17.

![2024-07-27_19 04 18](https://github.com/user-attachments/assets/f1750577-56dc-4cd2-a5f4-e6138e4bf57c)

![2024-07-27_19 04 21](https://github.com/user-attachments/assets/b50dac6d-8947-42fd-8deb-a105a72a8f5d)

![2024-07-27_19 04 24](https://github.com/user-attachments/assets/6027c1e8-b873-461c-80ee-136d2d98d187)

### Your Proposal

Make scaffolds unable to be destroyed/affected by the TC hammer AoE

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AlexanderChenhall** [comment]
Talked to dev, problem found, presumed fixed or to be fixed

**Comment by Caedis** [comment]
i'll close this with the pr
