### ISSUE TITLE
Crashing when attempting to search in my AE2 system

### ISSUE THREAD

**Issue by NewGuyGames** [GTNewHorizons/GT-New-Horizons-Modpack#16848]
### Your GTNH Discord Username

newguy274

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Other versions in between

### Type of Server

Don't know

### Your Actions

When I attempt to search in my AE2 network, be it through a normal terminal, crafting terminal, pattern terminal, wireless, etc. I crash from the server. This only happens when searching in my main nets, my subnets acted fine.

This issue started when I logged in today and found power had run out due to a machines failure in my nitrobenzene line. After putting in my backup reserve and getting AE2 back up and running is when it started.

### Crash Report

[crash-2024-07-27_12.41.38-client.txt](https://github.com/user-attachments/files/16401026/crash-2024-07-27_12.41.38-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Pxx500** [comment]
Simplest solution is to update pack to the newest stable, please do so and say if the problem persists, otherwise close the issue.

**Comment by NewGuyGames** [comment]
> Simplest solution is to update pack to the newest stable, please do so and say if the problem persists, otherwise close the issue.

Sorry, what is the newest stable? I'm on 2.6.1 but it did not give me that option when making the report.

**Comment by NewGuyGames** [comment]
Nevermind. I'm not sure what happened but it appears it ended up being a client side issue. I reinstalled the pack and all is fine.
