### ISSUE TITLE
Recipe for grinding Cooked Human Meat into macerator

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#16853]
### Your GTNH Discord Username

eldrinn_elantey

### Your Pack Version

2.6.1

### Your Proposal

At the moment, Cooked Human Meat can only be ground into mincemeat through a mortar.
![image](https://github.com/user-attachments/assets/25b0df31-d14c-42c1-983c-0c26af059583)

### Your Goal

I suggest adding a recipe for grinding Cooked Human Meat to the macerator

### Your Vision

Other cooked products have this option.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment]
It was fixed in dev so far ik.

**Comment by Pxx500** [comment]
should be fixed in dev
