### ISSUE TITLE
Ardite Tinkers extruder recipes are not in the Part Extruding Tab of NEI

### ISSUE THREAD

**Issue by 2ndDerivative** [GTNewHorizons/GT-New-Horizons-Modpack#16852]
### Your GTNH Discord Username

2ndDerivative

### Your Pack Version

2.6.1

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

The recipes should be in the "Part Extruding Tab"

### The Reality

they are in the "Extruder Recipes" tab

### Your Proposal

Move it over to the other tab

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
![image](https://github.com/user-attachments/assets/b352d9c0-3902-42db-9e4e-d298000bad89)
Appears to be fixed
