### ISSUE TITLE
groundhog day: pollution

### ISSUE THREAD

**Issue by MrJakobLaich** [GTNewHorizons/GT-New-Horizons-Modpack#16860]
### Your GTNH Discord Username

MrJakobLaich

### Your Pack Version

idk, most recent one

### Your Proposal

pollution sucks ass, we all know it, nobody wants to work on it, nobody wants to touch it,  etc etc
read from https://discord.com/channels/181078474394566657/603348502637969419/1267136001751646320 to at least https://discord.com/channels/181078474394566657/603348502637969419/1267143874267316284
tldr: make chunkloading (from ftblib or serverutils or whatever) spread pollution in chunks so pollution isn't just a thing localized entirely in someone's kitchen (one hell chunk and maybe the surrounding ones)
I can elaborate but don't want to right now because I expect this to get shot down with the usual "I don't want to touch it because it's ass as is right now and lack the creativity to actually imagine a better system, so let's not change the _not_ running system" stuff (I'm annoyed by this, sorry for rambling about this in here)

### Your Goal

same as always, make pollution an at least more interesting or engaging or immersive or expanded system than it is right now, I just want things to be nicer than they are right now

### Your Vision

balancing out the fact that the pack _is_ about investing a lot of time and work and chunkloading gives you _free_ time (you chunkload your ebf, put iron in it, go to sleep irl and get free steel when yu come back tomorrow, with zero downsides at all)
the balancing would be that it makes such time dilation at least something you need to consider once you get into later (past steam lol) tiers instead of just going "fuck it, it's free" (vis consumption also got suggested to me as a balancing act for pollution, but I won't spend/waste more time on this because experience tells me the reaction to this is just "kill him, burn him at the stake for trying to change what is in limbo right now" xD (this is a slight exaggeration thh))

anyways, make chunkloading balanced while giving pollution a bit more depth (could tie pollution into magic thaumcraft stuff somehow as well, open to discussion, can come up with creative stuff if needed)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
pollution already spreads.

**Comment by koiNoCirculation** [comment]
Some suggestions:
1. Pollution can decrease cleanness of cleanroom
2. Pollution can decrease the succeed rate of cleanroom recipes that processed in LCR, GT++ multiblocks(same as 1).
So players have to deal with the pollution.

**Comment by boubou19** [comment]
No plan to work on pollution rn. Maybe one day.
