### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by leonidas1283** [GTNewHorizons/GT-New-Horizons-Modpack#16863]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

how do i install this
makes no sense to me where to put it in curseforge?

### Crash Report

https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
Please dont post multiple tickets on the same thing. maybe check by the discord if you want to update a mod and dont know how or similar basic stuff.
