### ISSUE TITLE
Lava bucket prevents sleep in Peaceful despite damage supposedly being disabled.

### ISSUE THREAD

**Issue by AlexanderChenhall** [GTNewHorizons/GT-New-Horizons-Modpack#16879]
### Your GTNH Discord Username

Alex

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Try to sleep with lava bucket in inventory, not in primary hand, on peaceful difficulty.

### The Reality

When difficulty is set to peaceful, if the user attempts to sleep, they will be kicked out of the bed if they have a lava bucket (or clay fired lava bucket) in their inventory.
Timing by which you are kicked out of bed seems to coincide with the timing at which the lava bucket would *normally* damage you (however, since we are on peaceful that sort of damage is disabled).

### Your Proposal

Unless this is an intended feature, let the user sleep, disable (properly) whatever is occurring whenever game is in peaceful.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
Honestly I wouldn't want to sleep with lava in my bed ngl

**Comment by boubou19** [comment]
peaceful is not supported in the first place, so no wonder why we never found this bug. Maybe if someone has time to dig into this it'll be fixed.

**Comment by AlexanderChenhall** [comment]
Presumed fixed, see above PR
