### ISSUE TITLE
IC2 seed disappearing a small time after planting on cropstick

### ISSUE THREAD

**Issue by heccindragon** [GTNewHorizons/GT-New-Horizons-Modpack#16878]
### Your GTNH Discord Username

Heccindragon

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I planted a seedbag onto a cropstick and expected it to grow normally and remain until I tried to reclaim it.

### The Reality

After placing the seedbag it suddenly disappears leaving an empty cropstick which can then spread weeds to the rest of my crops.

https://github.com/user-attachments/assets/c24af6d3-656a-4666-92d8-9afb749a4ddc

### Your Proposal

After placing the seedbag it should remain until I break it or it is otherwise trampled.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
That's cuz youre placing a high-statted plant on basically no nutrients. It dies because the environmental stats are insufficient. I'd recommend switching to normal farmland, since that gives some more hydration, and moving to a different biome.
