### ISSUE TITLE
Add parallels in Circuit AssLine like in EEC

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#16889]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.5.1

### Your Proposal

I suggest adding to Circuit AssLine a possibility to make several recipes in parallel if recipe time goes less than certain limit (should be discussed, but probably 2-4 ticks will be ok?).
EEC has something similar now: if recipe goes under 1 sec, parallels are activated.

### Your Goal

Building hundreds of CALs in the endgame and setting them is awful game experience.
One CAL with parallels will consume same amount of energy but will occupy much less space.

### Your Vision

It will reduce abnormal spam of CALs in the endgame.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by NotAPenguin0** [comment]
CALs have sub 1 tick overclocking like almost every multiblock, so there's no speed penalty from overclocking further. Simply enable batch mode to reduce lag and it'll be fine.

This doesn't really address the CAL spam problem, you do need a lot of them, but straight up buffing it like EEC is not the solution. I'd rather see some sort of advanced CAL with special mechanics that allow it to scale much better than the current CAL can.

**Comment by chochem** [comment]
already works.

**Comment by FireWarrior2** [comment]
@chochem @NotAPenguin0 then why not allow wireless multiampere hatches to CAL? 
This will boost even opticals a lot.

**Comment by S4mpsa** [comment]
Because it has perfect overclocking. That would mean you need a single CAL per circuit, which is way too big of a buff.

**Comment by FireWarrior2** [comment]
> Because it has perfect overclocking. That would mean you need a single CAL per circuit, which is way too big of a buff.

And they will just use same amount of energy but without spam of hundreds of CALs.
Did you really enjoy spamming them?..

**Comment by S4mpsa** [comment]
There's a middle ground between 1 and 1024 CALs, namely a new circuit multi in the later tiers.

**Comment by FireWarrior2** [comment]
Hope it won't be in 10 years

**Comment by chochem** [comment]
anyway this discussion has nothing to do with the ticket which asked for something that was already in the game.
