### ISSUE TITLE
Crop Manager Tooltip Wording

### ISSUE THREAD

**Issue by SkilledAlpaca** [GTNewHorizons/GT-New-Horizons-Modpack#16886]
### Your GTNH Discord Username

SkilledAlpaca

### Your Pack Version

2.6.1

### Your Proposal

Crop Manager Tooltip says "Can harvest 1 block level above and below itself." Per the [wiki](https://wiki.gtnewhorizons.com/wiki/IC2_Crops#/media/File:Crop_Manager_positioning.png), several members of the Discord and my own testing. This tooltip is not correct and should be changed from `1` to `2`. 

> Can harvest 2 blocks level above and below itself

![image](https://github.com/user-attachments/assets/ae9cdbae-213c-4747-a0df-9f9e93010dd0)

### Your Goal

Clearer information regarding the device and how to best utilize it. 

### Your Vision

Same as goal. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by leumasme** [comment]
Agree / this should be type:bug, not suggestion

Crop manager tooltip says "Radius: N blocks each side (Nx3xN)" where N depends on tier.
![image](https://github.com/user-attachments/assets/a0bb3309-3a28-44ac-aa7e-f75c32c41e17)
https://github.com/GTNewHorizons/GT5-Unofficial/blob/daaebf5e39946a2197c750acb8cd345fe48d2e0b/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTECropHarvestor.java#L518

The 3 is incorrect here; it should say 5 as the crop manager [will harvest up to 2 blocks above and below itself](https://github.com/GTNewHorizons/GT5-Unofficial/blob/daaebf5e39946a2197c750acb8cd345fe48d2e0b/src/main/java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/basic/MTECropHarvestor.java#L212-L222), thus forming a box with the height of 5.

If the height of 3 was correct, the farm design [shown in the wiki](https://gtnh.miraheze.org/wiki/IC2_Crops) would not work
![image](https://github.com/user-attachments/assets/ac092072-1f23-469a-adbc-3dd3c0596b78)
