### ISSUE TITLE
When dropping multiple GregTech arrows to the ground, only one displays

### ISSUE THREAD

**Issue by BlokyX** [GTNewHorizons/GT-New-Horizons-Modpack#16880]
### Your GTNH Discord Username

BlokyX#8504

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Throwing multiple items should show various items on the ground.
Example:
![a](https://github.com/user-attachments/assets/9363186e-48e0-46a8-a7de-ca90bb1b9e41)

### The Reality

But when throwing multiple greg tech arrows, this happens (there are 64 arrows here):
![image](https://github.com/user-attachments/assets/9f4d8bb4-14b8-45b7-8ce1-da81ad88826e)

### Your Proposal

Show properly the amount of arrows when dropped.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
'fixed' by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2692
