### ISSUE TITLE
Glowstone duplication

### ISSUE THREAD

**Issue by RecursivePineapple** [GTNewHorizons/GT-New-Horizons-Modpack#16894]
### Your GTNH Discord Username

recursive_pineapple

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

You shouldn't be able to duplicate glowstone

### The Reality

By creating galaxyspace glowstones in a mixer then centrifuging them, you end up with more glowstone than you put in by 4 times.

![2024-08-02_14 42 48](https://github.com/user-attachments/assets/3eeb9906-ad82-45e7-ae44-addf4e9c9bdd)

![2024-08-02_14 42 51](https://github.com/user-attachments/assets/28953412-44d7-44ca-83f9-4b9c579dd176)

### Your Proposal

Fix the centrifuging recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
already fixed I guess 
![image](https://github.com/user-attachments/assets/dd76cd2a-539b-4fd2-83aa-05f31fe9cdd2)

**Comment by chochem** [comment]
see https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/844
