### ISSUE TITLE
aluminium vanishing in indium processing

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#16892]
### Your GTNH Discord Username

tom6482

### Your Pack Version

569

### Your Proposal

the sphalerite+galena processing setup for making indium eats an absurd amount of aluminium which just vanishes without an apparent reason. make the aluminium come back, at least in part if not fully from the "lead-zinc solution"....

maybe the whole process should be reviewed, the "lead-zinc solution" is mostly sulufur too.

### Your Goal

not using 99% of my aluminium in the indium line

### Your Vision

people wouldn't be asking asking themselves once a day where all their aluminium is going after they hit IV.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
we could output a useless item if that helps the realism.

**Comment by NotAPenguin0** [comment]
Aluminium is not really a rare thing to come by in IV, and removing this cost from indium production would make it a lot easier. Indium isn't *easy*, but you don't need it in huge amounts before ZPM-UV and by that point you get void miners to deal with aluminium supplies more reliably.

**Comment by chochem** [comment]
not a change we want
