### ISSUE TITLE
[ModularUI 2] FluidSlotSyncHandler logic differs from FluidSlotLongSyncHandler 

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#16899]
### Your GTNH Discord Username

timeconqueror

### Your Pack Version

ModularUI 2: 2.0.13

### Your Server

-

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Works as expected

### The Reality

1.
-Mundane phantom fluid slot can't clear the fluid with Shift+LMB. (tryClickPhantom content differs), but tooltip says it can (because it works so in Long version)
-Mundane phantom fluid slot can't be set on LMB

2.
Also SyncHandlers#fluidSlot uses mundane FluidSlotSyncHandler even if IFluidTankLong is passed.

3.
Also some methods of FluidSlotLong still uses internal FluidSlotSyncHandler, which remains null and produces NullPtrException for example in FluidSlot#onMouseTapped (RMB).

4. NetworkUtils#readFluidTank: FluidTankLongDelegate is created with fluid, which is required to be not-null, but it can be null

### Your Proposal

make Long version of fluid slot and handler share the same logic as mundane ones have and do not use copypaste

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/ModularUI2/pull/12 and https://github.com/GTNewHorizons/ModularUI2/commit/d677199dbafa20f0f000a8c363b1404a8915c506
