### ISSUE TITLE
crash with betterquesting

### ISSUE THREAD

**Issue by kassu458** [GTNewHorizons/GT-New-Horizons-Modpack#16900]
### Your GTNH Discord Username

k455u

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Anytime i try open up the quest page for steam age the game crashes, but with any other quest page the works just fine

### Crash Report

https://mclo.gs/DIEVpbo
[crash-2024-08-03_22.13.20-client.txt](https://github.com/user-attachments/files/16482599/crash-2024-08-03_22.13.20-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lithorn** [comment]
I've a simular issue, I cant click on anything in betterquesting without crashing. https://mclo.gs/ccNMLGC
