### ISSUE TITLE
LSC "Time to Full/Empty" parameter is breaking a conuter of lines

### ISSUE THREAD

**Issue by AwonGardino** [GTNewHorizons/GT-New-Horizons-Modpack#16903]
### Your GTNH Discord Username

awongardino

### Your Pack Version

2.6.1

### Your Server

nwmqpa hardcore server

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

Dissapearance of a line in a middle of data pack may disrupt power monitoring. Great example - IC2 informational panels, in which dissapearance of a parameter making them flickering with unwanted info. It may or may not break some OC power monitoring programms, i dont have such info.

### The Reality

When "Time to empty" = 0
![image](https://github.com/user-attachments/assets/1994a622-785c-4717-a7af-837496f9c8dc)

When "Time to empty" != 0 (+1 line "Operational Data" got hidden above because of minecraft)

![image](https://github.com/user-attachments/assets/159cf214-7d01-45b3-8dce-b62fad2bb7c0)

### Your Proposal

Make this parameter display constant, without it disappearing randomly when LSC is not outputing any power for some reason. Just type "Never" or something.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cybertick** [comment]
I am having the same issue, but mine is happening with the "wireless mode: disabled" line, even though I've turned that line off many times.

**Comment by Ruling-0** [comment]
I am experiencing this issue on Nightly 695. When that line flickers in and out, it actually deletes the line from the list, bringing the count from 22 to 23. This means any lines past it are shifted by ID up/down one, hiding and unhiding lines after it.
