### ISSUE TITLE
The Twilight Forest crash issue.

### ISSUE THREAD

**Issue by pexel5** [GTNewHorizons/GT-New-Horizons-Modpack#16919]
### Your GTNH Discord Username

pexel5

### Your Pack Version

2.6.1

### Your Server

SP/LAN

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Actions

Just traveling through The Twilight Forest. I turned on the peaceful difficulty mode to exclude crash due to some mob, everything repeats on peaceful difficulty.

### Crash Report

[crash-2024-08-06_12.04.16-server.txt](https://github.com/user-attachments/files/16508130/crash-2024-08-06_12.04.16-server.txt)
[latest.log](https://github.com/user-attachments/files/16508165/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by pexel5** [comment]
I forgot to add, after a second attempt to log in to the same save, the world does not load, you have to use backup to return the world

**Comment by lenawanel** [comment]
I am experiencing the same crash. ([report](https://mclo.gs/26GIfbK))

**Comment by Lyfts** [comment]
@lenawanel your issue is not at all the same and can be solved by updating TF to https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12
