### ISSUE TITLE
NEI Bookmark Grouping breaks with GroupIds bigger than 127

### ISSUE THREAD

**Issue by AxelandersGH** [GTNewHorizons/GT-New-Horizons-Modpack#16917]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

I'm using the new NEI Bookmark Groups Feature and when clicking the bracket on the left of the items, the Group should collapse/expand.

### The Reality

Suddenly all new groups automatically expand to one item per line and I am unable to collapse them (clicking on the bracket does nothing on normal items, and just reverse item order for recipes, without collapsing)

I noticed this bug in 2.6.0 and it persists after upgrading to 2.6.1.

### Your Proposal

I have looked into the reason, and with the help of the bookmarks.ini, I found out that this happens, when I reach groupId 128
All Groups with ID 128 or higher can't be collapsed.

I don't actually have that many groups, but new groups always get the highest ID +1, which can lead to large gaps between group IDs, that don't get filled.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by slprime** [comment]
please attach bookmark.ini file
