### ISSUE TITLE
Why do you need a circuit "1" to laser wafers?

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#16938]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.7. Nightly - 583

### Your Proposal

Until now: At one-of-nine Multi you just need a circuit to configure type

With new version you need a circuit to define if you laser without or with water with a tiny advantage.
For selection you have to put extra config circuit or putting both ("1" and "2") in input bus. 

### Your Goal

Generally only as many configuration circuits in the input bus as are really needed. Normally without.

### Your Vision

Solution ideas:

If this "water - thing" is it realy worth, machine should look them self, If correct water is available and no circuit is needed

Alternativly you need a circuit only if you want to use purified water for lasering.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by FourIsTheNumber** [comment]
Isn't this the standard? i.e. EBF circuit 1 versus 11

**Comment by chochem** [comment]
that sounds like a mistake or oversight. Engraver uses lenses to distinguish recipes, not circuits.
