### ISSUE TITLE
"tileEntity" Frames

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#16937]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.7. Nightly - 580

### Your Server

Zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

There are two versions of frames of same material. I expect only one, and receipt, they use the frame handle only one type.

### The Reality

![grafik](https://github.com/user-attachments/assets/754ec2e0-4703-4c31-affe-b0390b1c8197)

from some frame receipt (at same machine/Interface) make with "TileEntity" some normal. Same on ME stock.

### Your Proposal

please convert in same type

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
i will update zeta agian to remove this feature for now until notapenguin fix it

**Comment by NotAPenguin0** [comment]
Yeah this is a work in progress feature, eventually the TileEntity version will be completely hidden from the user

**Comment by Ngar1** [comment]
Solved with nightly 583
