### ISSUE TITLE
GregTech WIndmill multiblock does not form

### ISSUE THREAD

**Issue by rabitibike112** [GTNewHorizons/GT-New-Horizons-Modpack#16948]
### Your GTNH Discord Username

rabi.tiberius

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When I build the windmill I expect it to be able to macerate wheat.

### The Reality

I tried building it both in survival and creative, with schematic, with NEI 3D visualized, with and without door, with and without dispenser, with and without stuff inside of it. No matter what combo of things I try the multiblock does not form.
![image](https://github.com/user-attachments/assets/cb6d8a31-49b7-4bca-8825-11075afe1600)
![image](https://github.com/user-attachments/assets/f7abc29f-80b4-40d1-abc1-dbd9f51dc0dc)

### Your Proposal

I expect the multiblock to work if it's in the game. Maybe buff it a little too since basically no one uses it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by YannickMG** [comment]
At this time the windmill seems to form properly, with the caveat that it only really checks the structure when you place it down or when the world loads. The experience isn't necessarily intuitive but it seems to work for me.

**Comment by rabitibike112** [comment]
so it only checks when the controller block is placed or when the world loads? I will try and confirm

**Comment by rabitibike112** [comment]
Okay, I checked and indeed it works.  Extremely unintuitive tho.
