### ISSUE TITLE
Make Ceria Dust follow chem balance rules.

### ISSUE THREAD

**Issue by HalloweenNowi** [GTNewHorizons/GT-New-Horizons-Modpack#16944]
### Your GTNH Discord Username

halloweennowi

### Your Pack Version

2.6.1

### Your Proposal

Change Ceria Dust recipe to follow chem balance. Current Recipe is 2 Cerium Dust + 3kL oxygen -> 2 Ceria Dust. If it followed chem balance the recipe would be 2 Cerium Dust + 3kL oxygen -> 5 Ceria Dust. 
![image](https://github.com/user-attachments/assets/243c5c44-689c-405c-9fb3-8afacbacbebf)

### Your Goal

Improve consistency of chem balance.

### Your Vision

Proper chem balance is important in maintaining consistency in the pack even if it is minor.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
hmm. there also is a Cerium Dioxide. But I dont think unifying is an option as that is in the middle of the samariumline.

maybe we should rather consider this Cerium(IV) oxide or something like that to separate the two?

**Comment by chochem** [comment]
well not IV. the recipe suggests Cerium(III) oxide, we just need to change the output to 5. sounds good?

**Comment by chochem** [comment]
oh no. cerium trioxide exists as well in samariumline.
