### ISSUE TITLE
Missing LCR recipe

### ISSUE THREAD

**Issue by Iamworking12** [GTNewHorizons/GT-New-Horizons-Modpack#16940]
### Your GTNH Discord Username

iamworking

### Your Pack Version

nightly 574

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Ae2 autocrafting attempted to craft chromium dioxide recipe in a large chemical reactor.

### The Reality

The LCR was not crafting chromium dioxide and upon observation, the recipe was missing.

No large chemical reactor tab can be seen below
![image](https://github.com/user-attachments/assets/6cd9219a-f3f8-4bf8-9149-f102ccf64432)

### Your Proposal

A simple recipe fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
some recipes are only in singleblock or only in multiblock

**Comment by Atlantis102** [comment]
**use google translate**

In 2.6.1 there is a crafting recipe LCR, please clarify whether this was changed intentionally or is it a bug.
![2024-08-08_12 48 26](https://github.com/user-attachments/assets/c6b68928-f00a-4a2c-a694-6fa70bbbb9f7)

**Comment by chochem** [comment]
its already done
