### ISSUE TITLE
Industrial Arc Furnace multiblock has incorrect parallel

### ISSUE THREAD

**Issue by nullmana** [GTNewHorizons/GT-New-Horizons-Modpack#16950]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Industrial Arc Furnace is described as having a parallel of 8 * Voltage tier * W / L.
E.G. with IV == tier 5 voltage, parallel should be 40/66/93

### The Reality

Actual parallel with IV is 120/200/280, which seems to be 8 * Voltage tier * W, as described by both the portable scanner, and the functions of the machine itself.

### Your Proposal

Either update the description for the arc furnace or fix the divisor

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
W and L used to be the same and this meant 'W or L', not division.
But it looks like some dev flipped the multi at some point. weird. so yea the its the tooltip that needs fixing.
