### ISSUE TITLE
single player tf world corrupts

### ISSUE THREAD

**Issue by matin33333** [GTNewHorizons/GT-New-Horizons-Modpack#16959]
### Your GTNH Discord Username

matin#1219

### Your Pack Version

2.6.1

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

first time i thought it was the teleport from journey map, then i realized it made my save unplayable so i had to use a backup, then it crashed again when i was walking, there wasn't a specific action being done at the moment

### Crash Report

[crash-2024-08-09_18.23.23-server.txt](https://github.com/user-attachments/files/16568471/crash-2024-08-09_18.23.23-server.txt)
[crash-2024-08-09_19.19.56-server.txt](https://github.com/user-attachments/files/16568472/crash-2024-08-09_19.19.56-server.txt)
[crash-2024-08-10_01.18.56-server.txt](https://github.com/user-attachments/files/16568473/crash-2024-08-10_01.18.56-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by matin33333** [comment]
there are similar issues but different cases

**Comment by Caedis** [comment]
Update TF with latest version: https://github.com/GTNewHorizons/twilightforest/releases/download/2.6.31/TwilightForest-2.6.31.jar

Duplicate issue

**Comment by matin33333** [comment]
Thanks sorry for the inconvenience
