### ISSUE TITLE
About Biome

### ISSUE THREAD

**Issue by QianQiuawa** [GTNewHorizons/GT-New-Horizons-Modpack#16951]
### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

I've found that in the 2.6.1 server, the ocean biome has a lot of poppy like the garden biome.

### The Reality

I updated the server and client versions from 2.5.1 to 2.6.1

### Your Proposal

After the update, the 261 server had a problem with biomes, for example, Garden biome became Ocean biome in the server
![server](https://github.com/user-attachments/assets/2c9cdb26-82ee-4137-8a34-50e1fadcee33)
![client](https://github.com/user-attachments/assets/7e52cc90-f1c2-498c-9535-7f914a06a591)
The biomes displayed in single-player are the same as in the 2.5.1 server
The screenshot above is from the server, and the screenshot below is from the single-player game, and the save was copied from the server folder

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment]
Thermos issue. It didnt actually change. I think we fix the issue already
@boubou19

**Comment by boubou19** [comment]
yup, use the latest release here: https://github.com/GTNewHorizons/NotEnoughIds/releases
