### ISSUE TITLE
Kick from world after opening Redstone Transmitter GUI

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#16952]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

I opened Redstone Transmitter Cover GUI (it had no GUI) and got kicked from world:
![2024-08-09_13 05 27](https://github.com/user-attachments/assets/dc3df0c3-5878-45b5-bd50-ae7406368ec4)
Video:
https://github.com/user-attachments/assets/227dfd69-747b-4e9c-8ee5-7064a6418259

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/16559829/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by toaster-god** [comment]
Disconnect happening for me in one of the newest nightly builds.
it appears to happen if you open any covers config gui quickly after placing it as shown in my video.

https://github.com/user-attachments/assets/8500c932-7f47-42ea-9c10-529e8fcceb3e

I only got it to work on pipes with conveyors and pumps but I can make it occur consistently.
