### ISSUE TITLE
Hiding JourneyMap labels when approaching

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#16957]
### Your GTNH Discord Username

eldrinn_elantey

### Your Pack Version

2.6.1

### Your Proposal

I suggest to consider porting one feature from a newer version of JourneyMap if possible. Namely automatic hiding of labels when approaching them. I don't know exactly in which version it appeared, but it is for MIinecraft 1.12.2.

### Your Goal

Reducing the number of unnecessary elements on the screen

### Your Vision

In my opinion this is to improve the interface as those tags that are close to the player will not clog the view

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Caedis** [comment]
Make the request to https://github.com/TeamJM/journeymap-legacy

**Comment by Eldrinn-Elantey** [comment]
https://github.com/TeamJM/journeymap-legacy/issues/31
