### ISSUE TITLE
Discord General x In-game chat.

### ISSUE THREAD

**Issue by N2K2021** [GTNewHorizons/GT-New-Horizons-Modpack#16968]
### Your GTNH Discord Username

yakhusu

### Your Pack Version

request

### Your Proposal

I suggest a mod like minetogether but connected with discord channel so it can connect to your account and send messages via game to discord so you can chat easier or an IRC for GTNH like minetogether again.

### Your Goal

Socializing.

### Your Vision

Less boring with chit-chat.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by S4mpsa** [comment]
You can just install [DiscordIntegration](https://www.curseforge.com/minecraft/mc-mods/discordintegration) on the server you play on. It requires a lot of setup on the Discord side, so I don't see much benefit in including it by default; Those who can set up the Discord bot can install a single extra mod.

**Comment by N2K2021** [comment]
I was talking about connecting to discord account and talk in GTNH discord server via in-game it's not about my personal server. That will save up CPU usage and RAM usage because we don't use discord to answer people instead we can chat via game.

**Comment by S4mpsa** [comment]
Does this mod exist?
Would we have to code one from scratch?
Either way, extremely unlikely addition to the pack.

**Comment by N2K2021** [comment]
I don't think this exists but it is possible imo. It was just a suggestion.

**Comment by Glease** [comment]
That basically makes gtnh a third party discord client (you enter your discord password in game config)
Or we will be handing out our discord bot api secret in cleartext (we enter our discord password in game config)

neither are possible

**Comment by N2K2021** [comment]
> That basically makes gtnh a third party discord client (you enter your discord password in game config) Or we will be handing out our discord bot api secret in cleartext (we enter our discord password in game config)
> 
> neither are possible

Tokens are possible.
