### ISSUE TITLE
Make fluid storage components from AE use fluid processors

### ISSUE THREAD

**Issue by AlexCatze** [GTNewHorizons/GT-New-Horizons-Modpack#16966]
### Your GTNH Discord Username

alexcatze

### Your Pack Version

2.6.1

### Your Proposal

Make fluid storage components from AE use fluid processors, like it does item and essentia ones.

### Your Goal

Make crafts more hard. Make fluid processors more useful.  Bring more logic to crafts.

### Your Vision

Currently all storage components reqires processors of the same type, except of fluid. It makes no sense for me. In addition quest book says that player should make fluid processors before making components, but it isnt realy required.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
done in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/915
