### ISSUE TITLE
Antenna Casing Item id error

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/GT-New-Horizons-Modpack#16969]
### Your GTNH Discord Username

Admin_XiaoMai

### Your Pack Version

nightly-583

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

![image](https://github.com/user-attachments/assets/991a7f27-49ae-44ed-8f70-c2e916f73ef4)

### The Reality

![image](https://github.com/user-attachments/assets/96e6d8f5-9287-4bb9-89b0-d2cf8eb59668)

### Your Proposal

wrong item id required

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by RecursivePineapple** [comment]
Looks like this is fixed in the latest nightly. I think this issue can be closed.

![2024-09-08_12 47 53](https://github.com/user-attachments/assets/2c34167e-973d-4134-bc0d-234f49b0f3e1)
![2024-09-08_12 47 17](https://github.com/user-attachments/assets/f4fe34e3-08eb-460d-86d4-6262305a21e0)
