### ISSUE TITLE
Hammer not mining emerald sometimes

### ISSUE THREAD

**Issue by Star-Tube** [GTNewHorizons/GT-New-Horizons-Modpack#16984]
### Your GTNH Discord Username

star_tube

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Hammer should mine all blocks of equal or lower mining level and which are mined with a pickaxe in it's three by three area.

### The Reality

Hammer is not mining emerald ore even though hammer shows mining level of 06 and emerald ore is a mining level of 04.
![image](https://github.com/user-attachments/assets/ea180c1e-d1cb-4888-a2f9-36e288415927)
![image](https://github.com/user-attachments/assets/68bff3f4-7d2a-4fd5-9140-82bf1c0e7226)
![image](https://github.com/user-attachments/assets/310909a2-7ee6-4641-bff7-edd341d49ef1)

### Your Proposal

Find bug and fix it?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Star-Tube** [comment]
Would love if someone could verify if this is a thing in newer versions.

**Comment by LazyFleshWasTaken** [comment]
This was answered in another issue too, but basically, since emerald takes so much longer to mine than netherrack, so the hammer skips it. Same happens with obsidian

**Comment by Star-Tube** [comment]
huh. is that intended or should it be fixed?

**Comment by Star-Tube** [comment]
Also if this is adressed in another issue then feel free to link it and I will look there.

**Comment by LazyFleshWasTaken** [comment]
> huh. is that intended or should it be fixed?

its intended in base tinkers, but dreammaster was ok with changing it to mine it, however no one has worked on it

> Also if this is adressed in another issue then feel free to link it and I will look there.

[#9987](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9987)

**Comment by Star-Tube** [comment]
Thx
