### ISSUE TITLE
Energetic Alloy quest description mismatch

### ISSUE THREAD

**Issue by greentea-cup** [GTNewHorizons/GT-New-Horizons-Modpack#16994]
### Your GTNH Discord Username

greentea_cup

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

-

### The Reality

Direct direct mixer recipe requires HV, not EV, fix quest description please.

### Your Proposal

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you are mistaken
