### ISSUE TITLE
Add a method of obtaining Tartarite outside of Rockets / Deep Dark

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#16997]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.6.1

### Your Proposal

Add a method to obtain Tartarite without requiring the need to go to other dimensions (rocket / deep dark). Meteor Ritual or convoluted processing path just to be evil, whatever you prefer.

### Your Goal

Allows for full automation of the Avaritia Infinity Catalyst Recipe without the need to go to other dimensions, as far as I can tell from searching through the recipe.

### Your Vision

Let people have fun dumb automation.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LazyFleshWasTaken** [comment]
You don't need tartarite for anything required, including the avaritia infinity catalyst, and it can be obtained rocketless through the deep dark.
Although, putting it in the space elevator would be rather nice.

**Comment by PlayfulPiano** [comment]
> You don't need tartarite for anything required, including the avaritia infinity catalyst, and it can be obtained rocketless through the deep dark. Although, putting it in the space elevator would be rather nice.
Ah, although the deep dark generates based on world creation right? In that case i'll modify the suggestion for GoG void runs.

**Comment by LazyFleshWasTaken** [comment]
> Ah, although the deep dark generates based on world creation right? In that case i'll modify the suggestion for GoG void runs.
it doesn't. Even as a void it has everything. There are no actual ores, which is why you have to use a void miner.

**Comment by PlayfulPiano** [comment]
> > Ah, although the deep dark generates based on world creation right? In that case i'll modify the suggestion for GoG void runs.
> 
> it doesn't. Even as a void it has everything. There are no actual ores, which is why you have to use a void miner.

Oh, I didn't realize that void miners literally generated all ores without requiring movement. In that case never mind, I'll close this issue.

**Comment by LazyFleshWasTaken** [comment]
already completed via a meteor someone added.

**Comment by FourIsTheNumber** [comment]
> already completed via a meteor someone added.

so you reopened it :tootroll:
