### ISSUE TITLE
Possibly wrong recipe of Advanced Fusion Coil II

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17000]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Advanced Fusion Coil II (basic Fusion MkV) is crafted from Advanced Fusion Coil (basic Fusion MkIV).
It's even researched from it:
![2024-08-14_11 22 50](https://github.com/user-attachments/assets/27b27e9f-bcea-4e6f-8cac-9f337789c4a3)

### The Reality

Advanced Fusion Coil II (basic Fusion MkV) is crafted from Advanced Compact Fusion Coil (compact Fusion MkIII).
![2024-08-14_00 04 46](https://github.com/user-attachments/assets/17ca4313-879a-439b-85e7-374a67b613dd)
![2024-08-14_00 04 50](https://github.com/user-attachments/assets/440a19b4-e7af-4925-97b6-34831b5eb61f)

### Your Proposal

Fix Advanced Fusion Coil II recipe, if it is not intended.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FireWarrior2** [comment]
Seems like intended, but will leave issue open:
https://discord.com/channels/181078474394566657/181078474394566657/1273197456171077672

**Comment by chochem** [comment]
intended.
