### ISSUE TITLE
Mod Suggestion: Wood stuff 

### ISSUE THREAD

**Issue by xronin01** [GTNewHorizons/GT-New-Horizons-Modpack#17009]
### Your Pack Version

2.6.0

### Mod Name

Wood stuff 

### The Mod to Add

This mod adds wooden objects for several mods planks, such as Biome's O'Plenty, Botania, Thaumcraft, and others. With this, you can create blocks like bookshelves, buttons, fences, fence gates, pressure plates, chests, and crafting tables, all made from the woods of these mods. Additionally, the mod allows you to add support for any block you want, just check the config file to see how to do it.

### Your Reason

This mod is needed because mods like Biome's O'Plenty add new biomes and woods, but often don't include the corresponding wooden objects.

### Preliminary Investigation

https://legacy.curseforge.com/minecraft/mc-mods/wood-stuff

https://github.com/buttilda/WoodStuff

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by chochem** [comment]
hmm....

![image](https://github.com/user-attachments/assets/a9569d7b-5732-48cc-8486-e85c71456982)
![image](https://github.com/user-attachments/assets/8f595e53-7253-47af-8249-3e626d9315c8)

**Comment by xronin01** [comment]
Sorry, at least it's on github

**Comment by xronin01** [comment]
Is a fork possible?
I don't understand licenses

**Comment by FourIsTheNumber** [comment]
> Is a fork possible? I don't understand licenses

Not possible due to license.
