### ISSUE TITLE
ME Level Maintainer from AE2FC Causing HUGE Lag

### ISSUE THREAD

**Issue by Taskeren** [GTNewHorizons/GT-New-Horizons-Modpack#17010]
### Your GTNH Discord Username

Taskeren

### Your Pack Version

2.6.1

### Your Server

Private

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

https://spark.lucko.me/FmoWKzEglM

ME Level Maintainer causing the server thread very laggy.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
This can happen for a couple reasons
- Overuse of level maintainers on huge networks
- Badly optimized item storage (deeply nested subnets)
- Small request size for level maintainers (try ordering large batches at once)
- Badly optimized patterns (multiply your patterns to minimize crafting steps)
- Missing raw resource inputs for crafts, a continuously failing maintainer can cause a good amount of lag, especially combined with the reasons above.

**Comment by boubou19** [comment]
![image](https://github.com/user-attachments/assets/b35e95ac-9a9b-438e-85d8-38f6a3524c3d)
Clearly your system storage is either huge, defragmented, or both. We have a bunch of advices here: https://gtnh.miraheze.org/wiki/Good_Practices_With_AE.
