### ISSUE TITLE
Singleblock Electrolyzer Carbon Monoxide Recipe (likely accidentally) Changed

### ISSUE THREAD

**Issue by Ruling-0** [GTNewHorizons/GT-New-Horizons-Modpack#17027]
### Your GTNH Discord Username

ruling_

### Your Pack Version

Nightly 583

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Previously, I had an MV electrolyzer set up to passively run the below recipe:

![electro1](https://github.com/user-attachments/assets/47269fac-41a8-4273-b9ee-f96bb472434d)

### The Reality

This setup broke, and now the only two Carbon Monoxide recipes are the below ones. Neither was available previously, and I assume result from RA2:

![electro2](https://github.com/user-attachments/assets/1f438913-b6bf-430a-8554-16df4d763405)

This recipe, besides breaking my setup because it's now fluid-input only instead of cells, is also nearly 3 times slower than the old one.

### Your Proposal

The old recipe should be restored - I don't think singleblock electrolyzers, if they are used, need to be subjected to a breaking change like this, unless it was done for balance reasons (which I haven't seen mentioned).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
The time change was done due to a "cheaper than water" electrolysis of hydrogen and oxygen, the cell to cell recipe can be brought back but we'll have 3 recipes :/
