### ISSUE TITLE
Visual glitch with drawers and trim

### ISSUE THREAD

**Issue by Black-Noise** [GTNewHorizons/GT-New-Horizons-Modpack#17024]
### Your GTNH Discord Username

complex_color

### Your Pack Version

2.6.1

### Your Server

localhost

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Made a drawer wall with framed drawers (lave12 & cubit0), connected to a controller via framed trip (castle roof tile), getting a weird visual effect, inconsistently changes when I interact with the drawers or change tool to/from a wrench even when too far to interact. (screenshots 1 and 2)

The problematic block seems to be the trim, by itself drawers/controller don't seem to cause the issue.

Have tried turning off GL state cache to no effect (though the visual reload when changing settings briefly fixes it)

Can reproduce the issue in a singleplayer test world with regular oak drawers and framed trim connecting to a controller, though the visual glitchiness seems more limited to the trim. (screenshot 3)

### The Reality

screenshots of issue:
![bug](https://github.com/user-attachments/assets/fb771a17-8715-43f3-90d3-b53b4e13af82)
![bug2](https://github.com/user-attachments/assets/3cff5710-0591-4442-8a0a-9bea4c97277f)
![bug3](https://github.com/user-attachments/assets/15e72327-8e9c-484e-b084-eac11e678f5a)

### Your Proposal

pls fix, drawers are nice for early game organization and this makes less usable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cleptomania** [comment]
I think this will be fixed by https://github.com/GTNewHorizons/StorageDrawers/pull/38

**Comment by Cleptomania** [comment]
I've reproduced reliably and fixed with that PR, gonna consider this fixed

**Comment by Chaoschaot232** [comment]
Can confirm this as I don't have any more artefacts. Helped with the testing out and provided as much information as possible :)
Thanks for the great work @Cleptomania 👍
