### ISSUE TITLE
a QoL update where you can auto-pattern all the items in a NEI saved hotbar subset

### ISSUE THREAD

**Issue by jevry** [GTNewHorizons/GT-New-Horizons-Modpack#17033]
### Your GTNH Discord Username

themightyjevry

### Your Pack Version

2.6.1

### Your Proposal

Context: In NEI you can save items to a "saved hotbar", in this saved hotbar you can then group items in subsets which are marked with a "[" symbol.
Implementation idea: Allow players to create a 'special subset' (possibly marked with  differently colored "[") that they can save a number of recipes to. when the player then opens a pattern terminal GUI they can press a new button to automatically create a pattern of all recipes saved to in the special subset, allowing them to create a large number of patterns with much fewer clicks. 

estimated required functionality to make this work:
-the ability to save individual recipes to a new special subset of the NEI saved hotbar
-ensure player only the 1 recipe they need is saved recipe in NEI, for example have the [?] button add it to the subsection with ctrl+lmb (WITHOUT CLOSING THE NEI PAGE). it would also be great if only that recipe showed when viewed later on.
-while in pattern terminal GUI, allow player to auto-pattern all recipes saved in NEI saved subset
>.each pattern uses the settings specified in the terminal GUI (such as allow substitutes)
>.if possible, have recipe multiplier be specified by the number selected in the special subset (so 1x wire recipe saved as 256
>would lead to recipe "128 ingot -> 256 wire")

if more patterns are created than the player has inventory, spill the remaining patterns on the floor.
if there are more patterns to be created than there are patterns available in the GUI, don't make any patterns at all and write out a chat message warning the player of the issue.

### Your Goal

sometimes you need to create a huge amount of recipe patterns for some new item you want to craft. a good example would be solar panels, or drones. with this feature it is possible to quickly flip through the recipes in NEI and add all recipes you are still missing. then instantly create all recipe patterns when you are satisfied with your selection.

one obvious shortcoming is that wrong items might be used in the automatically created patterns, which the player will have to manually adjust. (for example AAL recipes with multiple stacks of the same item, which need to be renamed)

### Your Vision

this would reduce pattern creation fatigue for when you need to make loads of new patterns.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by boubou19** [comment]
this is too much, if you can't do 4 clicks per pattern... + you'd need to take into account some recipes which have oredicted stuff: you don't necessarily want to use the first suggestion of the shiftclick. This would require overengineered logic, if it's even possible to account for user preferences on oredicted recipes. Really, all you have to do pattern wise is to create them. We even have in game tools to optimise patterns without reencoding them.
