### ISSUE TITLE
can't play reika mods with galacticraft and industrialcraft2

### ISSUE THREAD

**Issue by ghost** [GTNewHorizons/GT-New-Horizons-Modpack#17038]
### Your Pack Version

custom

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

i was trying to play minecraft with reika's mods with galacticraft and industrialcraft2, but GC's mixins have issue with IC2

### Crash Report

https://mclo.gs/wM2clBd

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
The support status of Galaticraft jar is GTNH only. We do not support use of this mod beyond in the latest official GTNH release. 

Leaving  this open for now in case someone else is interested.

**Comment by mitchej123** [comment]
Dragon api falls under reikas mods :)

**Comment by Glease** [comment]
ic2 happens to be the first mod to load the class that both gc and dragonapi tries to modify. it's the first witness/victim, not the first culprit

**Comment by GirixK** [comment]
We don't extended support for Galacticraft outside of GTNH, closing the issue
