### ISSUE TITLE
Active Transformer Upgrade Module

### ISSUE THREAD

**Issue by Iamworking12** [GTNewHorizons/GT-New-Horizons-Modpack#17035]
### Your GTNH Discord Username

iamworking

### Your Pack Version

nightly 593

### Your Proposal

I propose two different upgrades for the Active Transformer.

The first upgrade, "High Power Resistant Casing" would prevent explosions of dynamo and energy hatches upon transformer failure. However, the controller will still explode and destroy itself due to it's primitive circuitry being unable to handle the sudden shift in current. This would replace all high power casings on a transformer to properly form the structure. Thought about gating it to DTPF via a high infinity cost. It can be crafted before hand, but the high infinity cost will make it rather inconvenient to make lots for multiple transformers. The reason for this is due to the recent laser nerfs will now push players to upgrade their lasers to more expensive and stronger lasers as they settle into a new tier, which can get pretty costly with increasing infrastructure and requiring more power to each machine.

The second upgrade would be to upgrade the Active Transformer controller block with an upgrade chip. It will allow modifying the active transformer and will not stop the active transformer while modifying its structure, perhaps by delaying disabling the multiblock by waiting 5-10 seconds after a structure check which did not find the full multiblock. After the prescribed time, a second structure check will occur and if that fails, the controller will destroy itself. If it succeeds, the multiblock will continue to operate normally. The tier 2 transformer will consume 20 times as much power, should not be a problem by the time this upgrade is available. This upgrade will be gated by hypogen and small transcendent metal costs within the chip.

### Your Goal

With how transformers are currently used, they are usually built in a chain. Breaking the chain earlier will cut off power to everything down the line and quickly cause a base powerfail, voiding precious materials. With the recent laser nerfs, players will be upgrading their line of transformers, aka "backbone", to higher voltages and amperage more often. Personally, I start having a panic attack when swapping lasers between structure checks. Turning off the transformer will basically have the same effect of exploding it, voiding all my lines down the chain. These upgrades will ease the upgrading process in later tiers starting from late UHV/UEV. It makes sense to be able to reinforce the AT using new and improved materials way past ZPM.

### Your Vision

This is mostly a quality of life feature and not necessarily required in progression with its current design. Players willing to take the risk of explosions can continue using the basic level transformer and save on some power. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Reflex18** [comment]
Why not just use the drone station and turn off your factory while replacing power?

**Comment by Iamworking12** [comment]
I hadn't thought about that, but this is just another way to swap lasers in a much more expensive way.

**Comment by Glease** [comment]
There are cover controlled machines that cannot really be turned off with drone station

**Comment by Iamworking12** [comment]
AT explosions were removed altogether.
