### ISSUE TITLE
Can't properly build Oil/Gas/Fluid Drilling Rig II (Stainless Steel Frame Boxes)

### ISSUE THREAD

**Issue by dhasial** [GTNewHorizons/GT-New-Horizons-Modpack#17044]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Trying to craft the "Oil/Gas/Fluid Drilling Rig II" multiblock with stainless steel parts, but I get an "Incomplete Structure, Has Problems" error.

### The Reality

complete error is:
"Pipe is loose.
Screws are loose.
Something is stuck.
Platings are dented.
Circuitry burned out.
That doesn't belong there.
Incomplete Structure"

The "Multiblock Structure Hologram Projector" item shows hint blocks where the "Stainless Steel Frame Boxes" are on the multiblock, even though "Stainless Steel Frame Boxes" are what the multiblock asks for in NEI. It even auto-builds  correctly by shift right-clicking on the main "Oil/Gas/Fluid Drilling Rig II" with the Multiblock Structure Hologram Projector, and I get a message saying "The multiblock has completed!" but the hint blocks never go away on the blocks with "Stainless Steel Frame Blocks" in them.

I'm also trying to fix up the maintenance issues using a toolbox containing these items:
crowbar,
hammer,
soldering iron + fine soldering alloy wire,
screwdriver,
wire cutter,
file,
saw,
soft mallet,
wrench (LV),

but I think there's an issue specifically with the multiblock thinking the stainless steel frame boxes don't belong because of the Hologram Projector hint blocks. I'm never able to actually apply the tool box repair the maintenance hatch, even though some fine soldering alloy wire is consumed on right clicking it.

I originally tried replacing a functioning T1 Oil/Gas/Fluid Drilling Rig in-place with the upgraded stainless steel parts, but had the above issues. I also tried building it from scratch in a completely different place juuust in case it was locational, but I got the same issues.

### Your Proposal

=

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
ensure you have at least one output hatch and exactly one energy hatch installed. the hint block is just a visual effect. It is not present on the server and cannot interfere with structure check in any particular way.

closing this now as you should try #help on official discord first

**Comment by Glease** [comment]
btw I just built one myself and yes it formed just fine

**Comment by dhasial** [comment]
I found what my issue was - I was using an "advanced energy hatch" when it required an "advanced II energy hatch". It makes logical sense that it would be this way, being on the same tier, but there is no direction to the player that this is the case. The NEI multiblock structure blocklist shows "ULV energy hatch". It was also confused by the fact that the maintenance hatch showed issues that imply it could be fixed with a properly stocked toolbox + soldering wire, when the energy hatch tier was the real issue.

**Comment by FourIsTheNumber** [comment]
> I found what my issue was - I was using an "advanced energy hatch" when it required an "advanced II energy hatch". It makes logical sense that it would be this way, being on the same tier, but there is no direction to the player that this is the case. The NEI multiblock structure blocklist shows "ULV energy hatch". It was also confused by the fact that the maintenance hatch showed issues that imply it could be fixed with a properly stocked toolbox + soldering wire, when the energy hatch tier was the real issue.

It is mentioned in the structure definition tooltip ("Energy Hatch: 1x HV+"). Unformed multiblocks always show maintenance issues because the maintenance hatch has not connected to the controller and thus maintenance cannot be performed.
