### ISSUE TITLE
Loot bag in quest books is error

### ISSUE THREAD

**Issue by XeonKA** [GTNewHorizons/GT-New-Horizons-Modpack#17057]
### Your GTNH Discord Username

XeonKA#9433

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Loot bag in quest books is error.After open the error loot bag,game crashed.
Single player don't have this issue.
![7B25648255759AC7A5C57F645A1E737E](https://github.com/user-attachments/assets/3f2a306f-690c-4c7e-98f2-2bbab30343fe)

### Crash Report

![421C642DF14E14029B5060D35994271C](https://github.com/user-attachments/assets/bbac9c2b-7b8a-4ce2-bbeb-d1a91175df6b)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
works fine 
![image](https://github.com/user-attachments/assets/d7a29726-95f1-47ab-bd42-b7869b727d50)
![image](https://github.com/user-attachments/assets/2f9c708b-de79-4c4c-bf20-7151cfc4e06b)
![image](https://github.com/user-attachments/assets/6a9f3e13-8732-43ad-bfc3-e04bd1b49903)

**Comment by XeonKA** [comment]
Found LootBags.xml is missing.What the......
