### ISSUE TITLE
Tree Growth Simulator is bad

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#17070]
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

2.6.0

### Your Proposal

Make TGS produce the amount of wood proportional to energy consumed.

### Your Goal

Make the electricity cost curve less steep

### Your Vision

Right now the multiplier formula is
2 * tier ^ 2 - 2 * tier + 5.
Let's count
tier 5 = EV = 45
tier 6 = IV = 65
tier 7 = LuV = 89

We already have an internal Energy penalty for most machines, when the Power cost is 4x and the production speed is 2x.

What we have here, the Power Cost is 4x, and the production rate is 
65/45=1.44
89/65=1.36

This means that not only we are Not getting at least 2x, but we are getting dramatically  reduced and reducing outputs whenever we increase the tier of energy.
This makes the whole tree chain that for examples transforms into benzene become useless extremely fast. We need that multiplier at least to stay at 2x level.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Pxx500** [comment]
Tree chain is not supposed to scale and it won't be buffed just so people can get more benzene. Trees are just a supplementary source of some resources
