### ISSUE TITLE
GT++ materials cooling recipes are duplicated

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17076]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

GT++ materials cooling recipes won't be duplicated.

### The Reality

GT++ materials cooling recipes are duplicated:
![2024-08-21_18 33 40](https://github.com/user-attachments/assets/a02460dd-b97f-4f5e-b6c6-d0274754bebe)

### Your Proposal

Delete duplicated recipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
seems to be fixed in dev 
![image](https://github.com/user-attachments/assets/b67711de-a20f-477e-9ff2-e24a89351f00)
