### ISSUE TITLE
Space Project does not save on restart

### ISSUE THREAD

**Issue by Iamworking12** [GTNewHorizons/GT-New-Horizons-Modpack#17079]
### Your GTNH Discord Username

iamworking

### Your Pack Version

nightly 593

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

After restart, I should still be in my teammates' space project team.

### The Reality

I was removed from the team and cannot obtain wireless power.
![image](https://github.com/user-attachments/assets/09c9b1f8-0aa4-4b02-9ce4-2d855ca6f614)

### Your Proposal

Save teams

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
@BlueWeabo maybe related to https://github.com/GTNewHorizons/GT5-Unofficial/pull/2700?

**Comment by Iamworking12** [comment]
Fixed https://github.com/GTNewHorizons/GT5-Unofficial/pull/3000
