### ISSUE TITLE
Ore Finder Wand corrupt player data

### ISSUE THREAD

**Issue by Derghust** [GTNewHorizons/GT-New-Horizons-Modpack#17071]
### Your GTNH Discord Username

Derghust#2175

### Your Pack Version

PreRelease 602

### Your Server

SP

### Java Version

Java 21

### Type of Server

Open To LAN

## Ore Finder Wand corrupt player data

Version: PreRelease 602

### Reproduction

Added ore item to Ore Finder Wand

### Cause

Corrupt playerdata so you will not be able to play SP or join MP server until Ore Finder Wand is removed from inventory with nbt editor.

### Crash Report

[crash-2024-08-21_16.09.32-server.txt](https://github.com/user-attachments/files/16692898/crash-2024-08-21_16.09.32-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by leumasme** [comment]
Not a player data corruption.

IFU wand crashes on init because it uses deprecated stuff https://github.com/GTNewHorizons/IFU/blob/f7f25c48feba2374685a7c75a32bafa563900368/src/main/java/com/encraft/dz/items/ItemOreFinderTool.java#L187-L204
that was removed 5 days ago in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2904

**Comment by Derghust** [comment]
Thanks for your response.

So, I guess the current alternative to the Ore Finder Wand is the Prospector's Scanner.
