### ISSUE TITLE
Precise Assembler annihilates TPS

### ISSUE THREAD

**Issue by Iamworking12** [GTNewHorizons/GT-New-Horizons-Modpack#17077]
### Your GTNH Discord Username

iamworking

### Your Pack Version

nightly 593

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Prass crafting works as normal.

### The Reality

Every time the assembler does a recipe check on normal mode, it causes immense lag to the server.
![image](https://github.com/user-attachments/assets/622f3724-8123-49d3-8bdb-8d1812a2a883)

### Your Proposal

I think there needs to be a cleanup for how many recipes exist in the assembler, perhaps use more of the breakthrough/bio circuits and allocate a mod's recipes to 1-2 circuits of its own.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by StaffiX** [comment]
Worth noting that the cpu usage scales with recipe count, c1 with the over thousand items uses 1-2mspt on its own, while circuit 21 only uses 210k.

Somehow crafting input bus and buffer doesnt have the same issue, it only uses 30k on recipe check, just like how much and empty prass would.

This isnt affecting only stocking bus, but regular input bus as well.

Having multiple input bus with programmed circuit in it increases cpu usage even more.
For example, 30 C1 Input bus uses 22m on the highest spike.

**Comment by GirixK** [comment]
Believe this is fixed, re-open if it persists on beta-4 or further
