### ISSUE TITLE
Lead-Lined Box (GT++) interaction immediately crashes server on Nightly

### ISSUE THREAD

**Issue by xTwi** [GTNewHorizons/GT-New-Horizons-Modpack#17084]
### Your GTNH Discord Username

neotwilight.

### Your Pack Version

2.7.0 Nightly 2024-08-07

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

Place lead lined box from GT++ down, right click it.
Server CTDs, client kicked back to menu.

### Crash Report

[crash-2024-08-22_21.42.56-server.txt](https://github.com/user-attachments/files/16718526/crash-2024-08-22_21.42.56-server.txt)
[crash-2024-08-22_21.36.42-server.txt](https://github.com/user-attachments/files/16718531/crash-2024-08-22_21.36.42-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/ModularUI2/pull/12
