### ISSUE TITLE
602 no ore veins spawning on ross moon

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#17087]
### Your GTNH Discord Username

tom6482

### Your Pack Version

602

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Expectation

trying to find new veins on ross128ba

### The Reality

![image](https://github.com/user-attachments/assets/722179f7-95d6-49f9-b60c-ee86ca7a747b)
no new veins found, even by digging, it's all rock.

also, the veins from visualprospecting seems wrong
![image](https://github.com/user-attachments/assets/de4b03e1-1456-4a84-89fd-160b77078649)
![image](https://github.com/user-attachments/assets/e632cad9-e824-49a4-9026-5d2e281cb5e8)

### Your Proposal

make veins spawn again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bpwhelan** [comment]
This is a problem also with ross128b, went to the planet for the first time and no ores spawned whatsoever.

**Comment by Miklebe** [comment]
Latest "stable" nightly 637 also doesn't have any ores on Ross128ba 
![javaw_27ab3LYGIl](https://github.com/user-attachments/assets/1f27de8d-315e-4abb-a863-b4542053728d)
Ross128b doesn't have GT ores, only random vanilla ones? 
![image](https://github.com/user-attachments/assets/73d158fd-272d-4525-9e62-b0b1d5643eea)
