### ISSUE TITLE
Electric boots of the traveller doesnt work

### ISSUE THREAD

**Issue by blackicecurry** [GTNewHorizons/GT-New-Horizons-Modpack#17088]
### Your Pack Version

2.6.1.0

### Your Server

sp

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

The Electric boots of the traveller should faster than traveller boots.

### The Reality

![image](https://github.com/user-attachments/assets/26fd8a1a-d141-4d81-96c9-405483185652)

### Your Proposal

The Electric boots of the traveller, as well as the Nano and Quantum upgraded versions, did not work as expected: even when fully charged, neither the speed nor the jump height increased; they only provide immunity to fall damage.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by cargocats** [comment]
There are settings to control how fast the boots go, including the jump height. They are under the Thaumic Boots key category.

**Comment by blackicecurry** [comment]
> There are settings to control how fast the boots go, including the jump height. They are under the Thaumic Boots key category.

Thank you , now they working suceecessfuly
