### ISSUE TITLE
Convert tiny dusts form extracting metal leaves from crops into full dust on chance

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#17081]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.6.1

### Your Proposal

Title. It goes with the tiny dust removal, and it'd make processing them just a tiny bit better.

### Your Goal

consistency and small qol.

### Your Vision

minorly improve crop processing for metal crops, and bring consistency, working towards full removal of tiny and small dusts, which afaik is an end goal.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LazyFleshWasTaken** [comment]
actually, 9 to 1 full dust would probably be better.

**Comment by chochem** [comment]
is resolved
