### ISSUE TITLE
Game crashed when chopping tree

### ISSUE THREAD

**Issue by Shoes4Clues** [GTNewHorizons/GT-New-Horizons-Modpack#17098]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Chopped a tree. Shortly after the leaves decayed, the game froze up and crashed. No crash report was created.

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/16737658/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BlueHero233** [comment]
Can you add more information? can you reproduce the crash somehow?

**Comment by BlueHero233** [comment]
Closed, No useful information to go on
