### ISSUE TITLE
Crashloop starting AE autocraft with Ignore Missing Craft Mode

### ISSUE THREAD

**Issue by Yabdat** [GTNewHorizons/GT-New-Horizons-Modpack#17097]
### Your GTNH Discord Username

Yabdat#9929

### Your Pack Version

2.6.1

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Tried starting a AE autocraft with the "Ignore Missing Crafting Mode" in AE, since what that was missing was a couple of items on passive, so it could wait. As soon as i started the craft, instant server crash with the server crashlooping afterwards. 
Had to restore from backup.

### Crash Report

[crash-2024-08-24_20.05.16-server.txt](https://github.com/user-attachments/files/16737601/crash-2024-08-24_20.05.16-server.txt)
[fml-server-latest.log](https://github.com/user-attachments/files/16737602/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by hiroscho** [comment]
Fixed in dev
see https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/518

**Comment by Yabdat** [comment]
Ah, nice, no problem then
