### ISSUE TITLE
Chat or GUI calculator?

### ISSUE THREAD

**Issue by murilogoedert** [GTNewHorizons/GT-New-Horizons-Modpack#17091]
### Your GTNH Discord Username

_gueda

### Your Pack Version

2.6.1

### Your Proposal

It would be great to have a calculator for quick calculations directly in the game chat or as a GUI. Some mods already implement this feature in the chat, but not for Minecraft version 1.7.10:

- https://www.curseforge.com/minecraft/mc-mods/chatcalculator
- https://www.curseforge.com/minecraft/mc-mods/chat-calculator

### Your Goal

A convenient in-game calculator would be much easier to use than switching to the OS calculator.

### Your Vision

Although NEI provides grouping and total resource counts for crafting, there are still times when some additional math is needed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Volence** [comment]
Pretty sure there already is one in chat if you start it with "= " (without quotes of course) and then type in your function.

**Comment by murilogoedert** [comment]
Oh, nice! I hadn’t noticed that before. I tried using =4+4 and, with a space, it works perfectly. Thanks for the tip! Closing the issue.
