### ISSUE TITLE
Massive FPS Lag when loading chunks

### ISSUE THREAD

**Issue by Iamworking12** [GTNewHorizons/GT-New-Horizons-Modpack#17101]
### Your GTNH Discord Username

iamworking

### Your Pack Version

nightly 605

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Trying to travel across my base smoothly

### The Reality

I freeze every time a chunk with some machines load in. This did not happen in angelica before 1.0.0 betas. Loading in void chunks or chunks with just a 1 block layer of floor do not lag.

### Your Proposal

Fix lag (probably angelica tbh)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment]
Please provide profiles, and try to narrow down to a specific commit/set of commits.

**Comment by Iamworking12** [comment]
Fixed: https://github.com/GTNewHorizons/GT5-Unofficial/pull/2987
