### ISSUE TITLE
Update structure button overlaps the parralel configuration button on waterline machines [nightly]

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#17109]
### Your GTNH Discord Username

skproch

### Your Pack Version

2.6.1 nightly with gregtech-5.09.49.23

### Your Server

Private

### Java Version

Java 21

### Type of Server

Ultramine

### Your Expectation

Buttons shouldn't overlap each other.

### The Reality

Here is update structure button on default multis:  
![image](https://github.com/user-attachments/assets/9b1c7192-4d59-4b89-97db-4573f07d1821)

Here is on waterline multis:  
![image](https://github.com/user-attachments/assets/abdebb72-3bd1-453e-936c-35043bd6e23a)

Its still possible to open parallels config popup by clicking slightly upped than the update structure button.

### Your Proposal

Move the button for waterline.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
Known issue and will be fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2957
