### ISSUE TITLE
Barley seed cannot be crafted.

### ISSUE THREAD

**Issue by Glatiuss** [GTNewHorizons/GT-New-Horizons-Modpack#17107]
### Your GTNH Discord Username

glatiuss

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

I was trying to craft a barley seed from pam's harvestcraft mod.
![2024-08-25_20 39 17](https://github.com/user-attachments/assets/dc80cacc-695e-4442-9892-d17a79775fb8)

### The Reality

I will make flour from the Natura mod
![2024-08-25_20 39 22](https://github.com/user-attachments/assets/1aff5a88-93c7-4edc-8c1a-dd5e8115d99e)

### Your Proposal

Combine flour recipe from Natura mod, with flour recipe from pam's harvestcraft.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
Seems to be fixed in 2.7
![2024-10-10_20 51 29](https://github.com/user-attachments/assets/f1f6f5d3-82b4-4b63-aca2-9c11bb057366)
