### ISSUE TITLE
Filtered water from a new water line doesn't stacks [nightly]

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#17108]
### Your GTNH Discord Username

skproch

### Your Pack Version

2.6.1 nightly with gregtech-5.09.49.23

### Your Server

Private

### Java Version

Java 21

### Type of Server

Ultramine

### Your Expectation

All fluids can be merged.

### The Reality

After clarifier purification unit consumes a part of filtered water to increase the chance of recipe no filtered water can be added to hatch.

It can't be inserted via storage bus:  
![image](https://github.com/user-attachments/assets/146b2b51-e070-4099-9f2a-4522bb46cb34)  
![image](https://github.com/user-attachments/assets/86ca838c-fbbd-42a9-958e-787cdbb45a0f)  
![image](https://github.com/user-attachments/assets/1e4eaa0c-e67d-4da3-8e57-34b3ba14b020)  
![image](https://github.com/user-attachments/assets/cf21b0f5-8d1b-4b3d-9a7c-9a62d0ee2ccb)  

Or via cell:
![image](https://github.com/user-attachments/assets/eb05adca-4a10-435c-9f49-72978a41ee22)

But if empty cell by clicking onto water it will add the fluid:  
![image](https://github.com/user-attachments/assets/c34f19ab-4720-4a3d-bc81-01e92732462e)  
![image](https://github.com/user-attachments/assets/5ce33504-9dc1-407d-9fc2-cc99a941f958)

But it can be perfectly inserted into fresh input hatch:  
![image](https://github.com/user-attachments/assets/170626cd-d041-4570-a0dd-1b41d46f027b)  
![image](https://github.com/user-attachments/assets/e62f5f1a-f32b-485e-a652-c6b7a3b0a22d)

### Your Proposal

Fix inserting fluid after some of them already consumed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SKProCH** [comment]
Also, pinging the @NotAPenguin0 as the author of waterline rework.

**Comment by NotAPenguin0** [comment]
Ah this might be the hatch locking to a recipe and only accepting regular water as that's part of the recipe input. Should be an easy fix, I'll take care of this tomorrow, thanks for reporting!
