### ISSUE TITLE
search anything in AE crashes client

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#17110]
### Your GTNH Discord Username

miaow246

### Your Pack Version

270 build 602

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Actions

search anything in my ae in zeta. Crash
I tested a small newly built ae, works fine.
I don't know if it's because ae too big.

### Crash Report

[message-3.txt](https://github.com/user-attachments/files/16741615/message-3.txt)
The end part, should be what went wrong.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment]
the error message you have posted is completely unrelated to searching. it's nei structure preview. try another log

**Comment by miaowwwwww** [comment]
was using old version of not enough characters. good now
