### ISSUE TITLE
Mithril Dust can be smelted with HSS coils when it should need Naquadah

### ISSUE THREAD

**Issue by j0r1s** [GTNewHorizons/GT-New-Horizons-Modpack#17115]
### Your GTNH Discord Username

j3wels

### Your Pack Version

2.6.1

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

I tried to smelt some Mithril Dust and realized in my ZPM (2x LuV Energy Hatches) Volcanus that I could not do it with HSS Coils : 
![image](https://github.com/user-attachments/assets/98184491-d14d-4692-b73d-14ee9b9da37a)

I would then expect my LuV (2x IV Energy Hatches) HSS Coils EBFs to not work as well.

### The Reality

I noticed my LuV (2x IV Energy Hatches) HSS Coils EBFs were smelting the Mithril without any issue : 
![image](https://github.com/user-attachments/assets/df75fbec-8cf4-4295-8a11-5b461c0878ea)

I was able to reproduce the same behavior in a creative world.

### Your Proposal

HSS Coils EBF should not be able to smelt Mithril Dust

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
This is not a bug. Electric Blast Furnace gets +100K per voltage tier past MV. Volcanus does not get this bonus.

**Comment by j0r1s** [comment]
Oh, I had thought about the heat bonus but my math were off, sorry for reporting.
