### ISSUE TITLE
Crashing while launching a rocket

### ISSUE THREAD

**Issue by Arjun96** [GTNewHorizons/GT-New-Horizons-Modpack#17130]
### Your GTNH Discord Username

invincible7554

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Launching a rocket

### Crash Report

[crash-2024-08-27_11.05.46-server.txt](https://github.com/user-attachments/files/16767223/crash-2024-08-27_11.05.46-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
best try a backup.
