### ISSUE TITLE
Mv cable only makeable with Adv. rubber

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#17138]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Trying to make a better mv cable that can transfer more amps, I would make electrical steel and cover it with rubber

### The Reality

Electrical steel cable can only be covered with advanced rubber, like silicone and styrene

### Your Proposal

Make it use normal rubber

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
Just checked, and this si also true for Energeti alloy, an hv cable, and vibrant alloy, an ev cable.

**Comment by chochem** [comment]
whats the bug?

**Comment by chochem** [comment]
oh so thats its not strictly by tier. I guess.

**Comment by LazyFleshWasTaken** [comment]
> oh so thats its not strictly by tier. I guess.

So, should it be coatable by normal rubber, or are you saying that the requirement for advanced rubber isn't just being an iv+ cable?
