### ISSUE TITLE
Limited Capacity ME Output Bus Probably* voiding on exceeding capacity

### ISSUE THREAD

**Issue by joshuan123** [GTNewHorizons/GT-New-Horizons-Modpack#17135]
### Your GTNH Discord Username

joshuan123

### Your Pack Version

Nightly 602, gt5u 5.09.49.30, ae2 rv3 beta 426

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Machine with void protection should be unable to parallel to beyond the output capacity of its ME output bus.

### The Reality

Parallel exceeds bus capacity, items get voided. Especially problematic with high parallel machines at high overclocks

### Your Proposal

Limit recipe parallel, or disallow busses voiding items and simply tell the machine there's no output space if the bus is at orexceeds capacity

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by S4mpsa** [comment]
Are you sure things are actually *voiding*?
The ME output buses always allow a full recipe to go in them, they will not void a recipe partially.

The only way they should be able to void is if you have multiple machines sharing an output bus, as the void protection status is checked at recipe start. This is similar behavior to normal output buses.

**Comment by miaowwwwww** [comment]
completely agree with sampsa, ME Output Bus does not void things with single use. i think we can close this.
