### ISSUE TITLE
Bio Lab Recipes not working

### ISSUE THREAD

**Issue by joshuan123** [GTNewHorizons/GT-New-Horizons-Modpack#17144]
### Your GTNH Discord Username

joshuan123

### Your Pack Version

Nightly 602, gt5u 5.09.49.30, ae2 rv3 beta 426

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Bio Lab TCeti Culture and BarnardA plasmid recipes work

### The Reality

They do not

https://github.com/user-attachments/assets/be03ee8f-f565-43bf-93fd-6bd759a56d47

### Your Proposal

Make Bio Lab work

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
![image](https://github.com/user-attachments/assets/9bf997f8-0a55-405f-a36e-2ea326df66f8)
Seems to work in nightly 618
