### ISSUE TITLE
Chat calculator ( = math) isn't working

### ISSUE THREAD

**Issue by NickTTD** [GTNewHorizons/GT-New-Horizons-Modpack#17150]
### Your GTNH Discord Username

nickttd

### Your Pack Version

Nightly 614

### Your Server

Open in LAN by a friend

### Java Version

Java 20

### Type of Server

Open To LAN

### Your Expectation

Wanted to do = 3+3 

### The Reality

![image](https://github.com/user-attachments/assets/f1c3c64a-b70f-434b-b521-e3e1d0235ff9)

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
fixed https://github.com/GTNewHorizons/Hodgepodge/pull/415
