### ISSUE TITLE
Rework IGI - Reduce memory allocations

### ISSUE THREAD

**Issue by Caedis** [GTNewHorizons/GT-New-Horizons-Modpack#17152]
### Your GTNH Discord Username

caedis

### Your Pack Version

nightlies

### Original Request

Reduce memory allocations due to config being reparsed every tick

### Responding developer

@Caedis

### Context

https://discord.com/channels/181078474394566657/603348502637969419/1278959203423092860

### Developer's Promise

Every game tick, the config is parsed on the client. For each alignment, the lines are parsed using regex to gather the tags that are present. This can be approved upon so that it is only parsed on start up and when the config is reloaded.

Initial idea:
Convert each line into a stringbuilder or formatted string and extract and store the tags so that they can be updated independently.
When the line is being drawn, utilize the stringbuilder/formatted string to add back the tag values.

### Final Checklist

- [X] The developer in question has instructed me to create such an issue.
- [X] I believe the developer is not causally joking around.
- [X] I understand this reminder might take a long time to implement no matter what the developer has promised. (e.g. unforeseeable life difficulty, computer breakdowns, forgetting, laziness, etc)
- [X] I understand other people (developers or not) might not like this feature and would oppose its integration.
- [X] I believe this feature would make the pack better.

**Comment by AnrDaemon** [comment]
Related #15537
