### ISSUE TITLE
No texture and wrong block name for Steel frame box

### ISSUE THREAD

**Issue by VasyaOrk** [GTNewHorizons/GT-New-Horizons-Modpack#17163]
### Your GTNH Discord Username

VasyaOrk

### Your Pack Version

2.7.0 Nightly 618

### Your Server

SP

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

1. Place Solid steel Framebox in World
2. See placed block with correct tooltip
3. 
![изображение](https://github.com/user-attachments/assets/ac15c279-17c5-4661-a623-f9d2b70be63a)

### The Reality

1. Place Solid steel Framebox in World
2. See a block without texture and incorrect name in tooltip
3. 
![изображение](https://github.com/user-attachments/assets/defad6cf-8cc8-443d-9cdb-cbe355e23ec9)
4. Also : same operation in Nightly 602 causes crash
5. 
[crash-2024-08-31_18.42.00-client.txt](https://github.com/user-attachments/files/16825374/crash-2024-08-31_18.42.00-client.txt)

### Your Proposal

Please fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by VasyaOrk** [comment]
Also : aluminium frame box places correctly
Also : when seeing on bugged block FPS drops from 180 to 18-19

**Comment by mkrutov** [comment]
placing a steel frame box "soft-crashes" client: https://mclo.gs/31tADzp
 
can relog back into server right away

**Comment by Ngar1** [comment]
- occures with tungstensteel, osmiiridium and so on.
- Black wire - frame (touch area) can be seen, if you fokus on that block
- this metal frames can be brocken by empty hand !
- this metal frames can unmounted as knowen by wrench

**Comment by VasyaOrk** [comment]
2.7.0 Nightly 641
-- still present at least with Steel and Tungstensteel frame boxes
-- also frames work as described in the Ngar1 comment above
-- frame texture and name becomes correct after relogin, multiblocks with frames see their structure correctly and works

**Comment by Dream-Master** [comment]
should be fixed in https://github.com/GTNewHorizons/DreamAssemblerXXL/actions/runs/10825695170

**Comment by Miklebe** [comment]
As of latest nightly 646, all the mentioned frames and problems seem to be fixed.
Frames don't break with the breeze of the hand and they render without the need to re-log. 
And i don't experience crazy frame drops. This one is kinda dependant on the system/world, so would be good if someone else could confirm, perhaps?
![ezgif-5-fa66e7af83](https://github.com/user-attachments/assets/073f9275-cf45-475c-9b36-2ed585a1ff01)

**Comment by Ruling-0** [comment]
Can also confirm on 646, all the frames had texture when placed and needed tool to break (using private server)
