### ISSUE TITLE
Putting a music disc into new IV Electric Jukebox causes server crash

### ISSUE THREAD

**Issue by arabadullah** [GTNewHorizons/GT-New-Horizons-Modpack#17167]
### Your GTNH Discord Username

arabadullah

### Your Pack Version

Nightly 613

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

I connected the IV Electric Jukebox to IV power, linked the headphones, then opened the inventory and shift clicked the vanilla music disc '11' in. Caused an immediate crash loop on the client side, cannot remember if the server stayed up. No client logs were generated, only server logs.

After this first try, I created a singleplayer test world to see if it was a fluke. I placed the IV jukebox with no power and shift clicked the same disc inside, and it worked as expected, no crash.

Later in the day I loaded a backup of my main world onto my server again and repeated the steps of connecting the IV jukebox to power and shift clicking the same disc. This time I didn't link the headphones, but still crashed, and this time the server crashed as well for sure. Still no client logs were generated, only server logs.

I'd ask others to try to reproduce but they don't seem to want to crash their server q.q

### Crash Report

First Attempt
[crash-2024-08-31_10.24.07-server.txt](https://github.com/user-attachments/files/16825764/crash-2024-08-31_10.24.07-server.txt)
[2024-08-31-4.log](https://github.com/user-attachments/files/16825765/2024-08-31-4.log)

Second Attempt
[crash-2024-08-31_14.58.21-server.txt](https://github.com/user-attachments/files/16825794/crash-2024-08-31_14.58.21-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Tctcl** [comment]
Going to try and reproduce this now

**Comment by Tctcl** [comment]
Was able to reproduce this in Nightly 618, doesn't crash in singleplayer, does crash in multiplayer.

can confirm that only the server side crashes, client just disconnects.

Steps taken:

- give IV Jukebox, IV battery, disc 11
- place Jukebox
- put battery in Jukebox
- place disc 11 in Jukebox

server log files:
[GregTech.log](https://github.com/user-attachments/files/16826070/GregTech.log)
[latest.log](https://github.com/user-attachments/files/16826071/latest.log)
[fml-server-latest.log](https://github.com/user-attachments/files/16826072/fml-server-latest.log)

**Comment by Tctcl** [comment]
This might be caused by Vanilla disks not having soundDuration data, checking that right now

**Comment by chochem** [comment]
`java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "net.minecraft.launchwrapper.Launch.minecraftHome" is null`

seems to be more about how it is trying to find the config folder
