### ISSUE TITLE
BC Pipe Plug and BC Facades not applicable on Logistics Pipes

### ISSUE THREAD

**Issue by BohneMPs** [GTNewHorizons/GT-New-Horizons-Modpack#17175]
### Your GTNH Discord Username

bohnemps

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Tried to apply Buildcraft Pipe Plugs and Buildcraft Facades to any Logistics Pipes (by simply rightclicking), was possible in 2.5.1
(survival and creative modes)

### The Reality

Both plugs and facades are not applicable to any Logistics Pipes, right clicking them does nothing.
Also existing pipe plugs on Logistics Pipes were removed from the world in the update from 2.5.1 to 2.6.1

### Your Proposal

Fix if unintentional
Not sure if this is intentional or not, have not found the change in any changelogs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Atlantis102** [comment]
Buildcraft Pipe Plugs and Buildcraft Facades apply in Logistics Pipes 1.2.19
![2024-09-01_23 19 05](https://github.com/user-attachments/assets/8190c232-74ae-4a50-8d4a-9e12e6d74675)

**Comment by BohneMPs** [comment]
Every flash of red particles here is one right click, it doesn't work for me (GTNH 2.6.1 on MultiMC)

https://github.com/user-attachments/assets/0ece889a-708e-4470-b51b-0a6736084145

**Comment by BohneMPs** [comment]
Now it somehow magically fixed itself
