### ISSUE TITLE
GT5-U crashing on startup

### ISSUE THREAD

**Issue by NeoNC72** [GTNewHorizons/GT-New-Horizons-Modpack#17170]
### Your Pack Version

nigtly 617

### Your Server

not in game

### Java Version

Java 21

### Type of Server

None

### Your Actions

Start game, i think its caused by https://github.com/GTNewHorizons/GT5-Unofficial/commit/b22ab538b762de1fdc83d3a2e45fc21adcab5efd as version before this commit (5.09.49.41-pre) works (also need to downgrade emt to 1.5.7 as it depends on the 49.42 version of gt5)

### Crash Report

<html>
<body>

<html>
<body>

cpw.mods.fml.common.LoaderException: java.lang.IllegalAccessError: The Enum 'SpaceElevatorController' has not been set to an Item at this time!
5406 | at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
5407 | at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
5408 | at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
5409 | at net.minecraft.client.Minecraft.startGame(Minecraft.java:552)
5410 | at net.minecraft.client.Minecraft.run(Minecraft.java:5099)
5411 | at net.minecraft.client.main.Main.main(SourceFile:148)
5412 | at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
5413 | at java.lang.reflect.Method.invoke(Method.java:580)
5414 | at net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:250)
5415 | at net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
5416 | at net.minecraft.launchwrapper.Launch.main(Launch.java:60)
5417 | at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
5418 | at java.lang.reflect.Method.invoke(Method.java:580)
5419 | at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:207)
5420 | at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105)
5421 | at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
5422 | at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
5423 | Caused by: java.lang.IllegalAccessError: The Enum 'SpaceElevatorController' has not been set to an Item at this time!
5424 | at gregtech.api.enums.ItemList.sanityCheck(ItemList.java:2764)
5425 | at gregtech.api.enums.ItemList.get(ItemList.java:2667)
5426 | at com.github.technus.tectech.loader.recipe.ResearchStationAssemblyLine.addEOHRecipes(ResearchStationAssemblyLine.java:2379)
5427 | at com.github.technus.tectech.loader.recipe.ResearchStationAssemblyLine.run(ResearchStationAssemblyLine.java:93)
5428 | at com.github.technus.tectech.loader.recipe.BaseRecipeLoader.run(BaseRecipeLoader.java:44)
5429 | at com.github.technus.tectech.loader.MainLoader.postLoad(MainLoader.java:101)
5430 | at com.github.technus.tectech.TecTech.PostLoad(TecTech.java:109)
5431 | at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
5432 | at java.lang.reflect.Method.invoke(Method.java:580)
5433 | at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
5434 | at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
5435 | at java.lang.reflect.Method.invoke(Method.java:580)
5436 | at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
5437 | at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
5438 | at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
5439 | at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
5440 | at com.google.common.eventbus.EventBus.post(EventBus.java:275)
5441 | at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
5442 | at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
5443 | at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
5444 | at java.lang.reflect.Method.invoke(Method.java:580)
5445 | at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
5446 | at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
5447 | at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
5448 | at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
5449 | at com.google.common.eventbus.EventBus.post(EventBus.java:275)
5450 | at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
5451 | at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
5452 | ... 15 more
5453

<br class="Apple-interchange-newline">
</body>
</html>

</body>
</html>

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by VasyaOrk** [comment]
has same error on Nightly 620
(gregtech-5.09.49.44   GTNewHorizonsCoreMod-2.6.15)
[crash-2024-09-01_11.17.44-server.txt](https://github.com/user-attachments/files/16828973/crash-2024-09-01_11.17.44-server.txt)
But no error with gregtech-5.09.49.43-pre   GTNewHorizonsCoreMod-2.6.14

**Comment by Caedis** [comment]
already fixed, use https://github.com/GTNewHorizons/GTNH-Intergalactic/releases/download/1.4.11-pre/gtnhintergalactic-1.4.11-pre.jar
