### ISSUE TITLE
Iron springs in BM recipe

### ISSUE THREAD

**Issue by LavenThaRaven** [GTNewHorizons/GT-New-Horizons-Modpack#17184]
### Your GTNH Discord Username

LavenThaRaven

### Your Pack Version

2.6.1

### Your Server

None for now

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Trying to craft Iron Springs in bending machine with recipe 'Iron rod to 2 Iron springs with #1Pc.

### The Reality

Instead I get an Iron wire and saw it has the same recipe input for the Pc and item for 2 different results.

### Your Proposal

Either you could remove the wire to spring data as the material usage from manually crafting them to machine craft makes sense for 2 out of a rod, or if the player wants to use wires to craft them then you could  make it faster and resulting 1 to 1 for crafting biggest thing to fix is just changing the Pc to a different number for the crafting recipe itself.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LavenThaRaven** [comment]
Actually it gets even worse, the wired get turned into fine wire instead of springs so currently the only way to craft them is permanent manual

**Comment by chochem** [comment]
seems to be fixed. only have the one recipe in nightlies 
![image](https://github.com/user-attachments/assets/91ef036a-8978-482a-a7a1-a1ccbb53a0a5)

**Comment by LavenThaRaven** [comment]
Ah if that's case nvm
