### ISSUE TITLE
storage drawers upgrade template missing recipe

### ISSUE THREAD

**Issue by xSaucychan** [GTNewHorizons/GT-New-Horizons-Modpack#17189]
### Your GTNH Discord Username

saucy4869

### Your Pack Version

DEV

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

crafting drawer template with any sticks from natura should result in a valid recipe 
![2024-09-02_10 54 17](https://github.com/user-attachments/assets/0594fc28-0fd5-4bc2-9263-a9c713ad9efc)
![2024-09-02_10 58 10](https://github.com/user-attachments/assets/4135859b-0a54-4e91-9488-4353433b67ef)

### The Reality

No recipe for upgrade template exist even when updating to version storage drawers 1.13.10. recipe also isn't visible in nei recipe lookup when using nei 2.6.34-GTNH
![2024-09-02_10 49 33](https://github.com/user-attachments/assets/ddd47773-6c67-43a3-baad-e1f8a1e7681d)

### Your Proposal

Add recipe for upgrade template for use outside gtnh modpack. recipe should support ore dictionaried sticks including all sticks from natura, rivercane from biomes o plenty and all drawer variants. screenshot taken with version 1.10.9
![2024-09-02_09 48 50](https://github.com/user-attachments/assets/af53d21a-da4b-4716-9bb7-79d8409a5d00)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Cleptomania** [comment]
FYI this is due to the GTNH Integration module being enabled I think. Check your config and disable the `B:enableGTNH` setting under the `integration` section.

I will follow up with making that disabled by default in the mod. The GTNH specific config already has it enabled

**Comment by Cleptomania** [comment]
Actually on second look, it does look like for some reason that recipe is commented out in the Storage Drawers code. I'll also add that back, but the enableGTNH setting being turned on would also make it disappear so make sure that's disabled if it isn't.

**Comment by Cleptomania** [comment]
This is fixed with Storage Drawers 2.0.2-GTNH
