### ISSUE TITLE
uxv 4M laser target 2 scanning result 

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#17188]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.1 build 618

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

no 2 scan result for 1 item in research station

### The Reality

2 scan result for 1 item in research station

### Your Proposal

change the UXV 16M target hatch scan item from 4M uxv to 16M umv

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by POPlol333** [comment]
UMV 16M Laser hatch doesn't exist, as UIV 4M either these last upgrades are added per tier

**Comment by POPlol333** [comment]
I don't speak about the conflict, miow ask the recipe to be replaced by a 16M UMV Laser Hatch, but those don't exist (at least not in latest commit of gt)

**Comment by chochem** [comment]
sampsa mentioned that one of the ones you make here doesnt work properly anyway. so easiest solution would be to remove it, if that is indeed the case.

**Comment by POPlol333** [comment]
remove what?? the UXV 16M hatch?

**Comment by chochem** [comment]
potentially fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3106 it seems, so maybe it should stay.

so yea just put in some new scan item that you think fits. what was proposed here or not isnt super important.
