### ISSUE TITLE
Change Thaumcraft leaves from a Tile Entity into a normal block

### ISSUE THREAD

**Issue by MrGundum** [GTNewHorizons/GT-New-Horizons-Modpack#17199]
### Your GTNH Discord Username

MrGundum

### Your Pack Version

2.6.1

### Your Proposal

Thaumcraft leaves should behave like normal vanilla leaves and be simple blocks instead of ticking tile entities 

thaumcraft tile entitys:
![image](https://github.com/user-attachments/assets/ae7b9a81-f14d-4337-87cd-ca10a3dcdb8e)

### Your Goal

To reduce system usage and tile entity ticks on servers.

![image](https://github.com/user-attachments/assets/6c422829-aea2-4caa-816f-e73c162b6e7b)

### Your Vision

It will make the modpack run smoother for anyone using thaumcraft leaves in their base building.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Lyfts** [comment]
They aren't tile entities.
Are you certain that you're not on 2.6.0 instead of 2.6.1 as this was fixed in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16092

**Comment by MrGundum** [comment]
> They aren't tile entities. Are you certain that you're not on 2.6.0 instead of 2.6.1 as this was fixed in [GTNewHorizons/Hodgepodge#359](https://github.com/GTNewHorizons/Hodgepodge/pull/359)
> 
> Related ticket #16092

Ah your right i thought i was on 2.6.1 to be honest
