### ISSUE TITLE
Advanced Botany Crash on Startup

### ISSUE THREAD

**Issue by xSaucychan** [GTNewHorizons/GT-New-Horizons-Modpack#17192]
### Your GTNH Discord Username

saucy4869

### Your Pack Version

DEV

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Launch the game
Mods used
Advanced Botany 1.4.4
Botania 1.11.5-GTNH
Bettercrashes 1.4.0-GTNH
Baubles 1.0.1.10
CodeChickenCore 1.3.7
Gtnh Lib 0.5.3
Hodgepodge 2.5.55
NotEnoughItems 2.6.34-GTNH
Unimixins 0.1.17
Waila 1.8.1

### Crash Report

[crash-2024-09-02_22.12.39-client.txt](https://github.com/user-attachments/files/16843038/crash-2024-09-02_22.12.39-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by EnderProyects** [comment]
Just saying, advanced botany needs botania and thaumcraft

**Comment by boubou19** [comment]
this mod is not supported by the team at the moment.
