### ISSUE TITLE
Right clicking output busses places blocks

### ISSUE THREAD

**Issue by zTotto** [GTNewHorizons/GT-New-Horizons-Modpack#17201]
### Your GTNH Discord Username

totto.

### Your Pack Version

Nightly 610

### Your Server

Private Server

### Java Version

Java 20

### Type of Server

None

### Your Expectation

Right Clicking an output bus with any block in hand won't do anything apart from opening the GUI

### The Reality

Right clicking an output bus with any block opens the GUI and places the block

### Your Proposal

Right clicking an output bus will only open the GUI when having a block in hand

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3113
