### ISSUE TITLE
industrial lathe can't form with only cribs as input

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#17209]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.1 build 618

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

industrial lathe can form with only cribs as input

### The Reality

industrial lathe can't form with only cribs as input.    
![image](https://github.com/user-attachments/assets/adb59aca-fec0-416c-8b57-f8afab664965)
![image](https://github.com/user-attachments/assets/f1724148-cdc4-4c53-a796-3a7f31fbf1bd)

### Your Proposal

 same bug was present with nano forge when crib was introduced. can probably fix with same approach.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
@Volence
