### ISSUE TITLE
some recipes are consuming exactly 1A

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#17205]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.1 build 618

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

no exact 1A

### The Reality

![image](https://github.com/user-attachments/assets/5bfdbe17-05f0-422e-81fa-80819d7f6297)
According to discord conversations. not just 1 recipe is effected, Four and Chochem is on it.
https://discord.com/channels/181078474394566657/401118216228831252/1280630465291751464
just wanna write the ticket down so people know this is known.

### Your Proposal

have a good day.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
(Mostly, this instance at least + many others) fixed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/965
