### ISSUE TITLE
Unable to rotate XL Gas/Plasma Turbines

### ISSUE THREAD

**Issue by bobolpwnz** [GTNewHorizons/GT-New-Horizons-Modpack#17216]
### Your GTNH Discord Username

bobolpwnz

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Able to rotate XL Turbo Plasma/Gas Turbines to change their alignment from North-South to East-West. This would allow to have Rotor Assembies on East-West sides as well, instead of only on North-South sides.

### The Reality

XL Turbines are locked to North-South alignment making it impossible to have Rotor Assembles on West-East sides of the multiblock. This is only am aesthetic issue.

On this screen, all RAs are on North-South sides, it should be possible to have them on West-East sides as well.
![xl turbs](https://github.com/user-attachments/assets/88957706-337f-401f-b7ba-e0d7fd773bf9)

### Your Proposal

Make it possible for XL Turbines to be rotatable or allow RAs to be places on West-East sides.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
This is on purpose, the rotor assembly code forces it to be facing north or south, to render the turbine blades texture properly, this could also be fixed with a already existing method

**Comment by Miklebe** [comment]
![javaw_bn3kyCisJW](https://github.com/user-attachments/assets/afa9683f-011a-40c7-afc2-530591c7bdcc)
It's not on purpose, the turbines can already be rotated without issues (at least on 2.7 beta), they just don't have texture rotating like some other multis.

**Comment by bobolpwnz** [comment]
I've double checked this on 2.7-beta2 and indeed the controller can be rotated and the multi is formed. Just the texture of the controller isn't rotated which makes it hard no notice what is the current orientation of the multi. Also, there's a delay between rotating the controller and the multi forming which can give a wrong sense that the multi cannot be rotated.
