### ISSUE TITLE
World gen bug

### ISSUE THREAD

**Issue by phoenixfire3721** [GTNewHorizons/GT-New-Horizons-Modpack#17218]
### Your Pack Version

im up to date on versions

### Your Server

Kinetic hosting 

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

everything is running fine and smooth

### The Reality

everything is running fine and smooth except there are massive mushroomIslands everywhere 

### Your Proposal

me and my friend just started the modpack and we keep having a problem where we get massive mushroom islands constantly spawning around the map ruining other biomes 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you changed the world gen or didnt set world gen correctly if its a server. one of the first quests also explains it.
