### ISSUE TITLE
AE2 fluid drops freeze the game when bookmarked (Nightly)

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#17221]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

Nightly 628

### Your Server

SP

### Java Version

Java 19

### Type of Server

None

### Your Actions

On book marking a fluid from an ae2 recipe, so effectively book marking the fluids drops. These drops appear as an invisible bookmark in nei on the left. If clicked then it freezes the game with the only option to close it.

The freeze also occurs if there is any other bookmark in that page while the fluid drop is bookmarked.

### Crash Report

[message.txt](https://github.com/user-attachments/files/16887706/message.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ramseyspace** [comment]
Getting same issue on 629

**Comment by chochem** [comment]
author says its fixed
