### ISSUE TITLE
Multiblock for massively interchange items/fluids between networks

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#17225]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.6.1

### Your Proposal

Small multi that can interchange items/fluids between input an output buses/hatces, should be compatible with ae2 me buses, also it could consume a bit of energy passively, or that the energy configures the throughput, being infinite using me busses

### Your Goal

Add a way to mass transfer things between network without using storage bus to interface, or the crafting items method. 

### Your Vision

I think is a nice feature that can help to make large setups of ore processing, filter items between networks, or send many items to arrays of machines instead of using me io port.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
that sounds super hacky and not like a reasonable gt multiblock. I am sure there already good ways of doing what you want to do
