### ISSUE TITLE
Magic Energy Absorber causes explosion

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#17246]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.1 build 618

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

no explosion

### The Reality

the moment i insert the ev battery, explode
![image](https://github.com/user-attachments/assets/5b75e2c7-f865-479b-abc3-0ccb5a47485a)
![image](https://github.com/user-attachments/assets/93ccb778-bfba-45f4-8f93-ceb9b934566d)

### Your Proposal

no idea, fix plz

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hebbu** [comment]
Not sure if we have the same problem but the recent changes in nightlies to config format seem to changed the AllowMultipleEggs from true to false, causing Magic Energy Absorbers to explode if you have more than 1 with an egg. This didnt happen is 2.6.1 and most likely isnt intended
