### ISSUE TITLE
GT Chunk borders show ore chunk center in wrong place

### ISSUE THREAD

**Issue by AngelifNight** [GTNewHorizons/GT-New-Horizons-Modpack#17247]
### Your GTNH Discord Username

angelifnight

### Your Pack Version

nightly 626

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Want see blue lines for middle of chunk be in same chunk as showed in map.

### The Reality

Current state for chunk borders and ore prospecting on map. https://imgtr.ee/image/hmlxjj. Create new world and have same problem

### Your Proposal

Show borders properly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ramseyspace** [comment]
Yeah i noticed this also happens on PDIM too

**Comment by chochem** [comment]
looks the gt rename is still incomplete lol https://github.com/GTNewHorizons/NotEnoughItems/pull/525
hopefully its just that

**Comment by chochem** [comment]
seems to be fixed
