### ISSUE TITLE
Marble, Granites, etc are all Missing from World Gen in the Overworld. 

### ISSUE THREAD

**Issue by StoneLegion** [GTNewHorizons/GT-New-Horizons-Modpack#17242]
### Your GTNH Discord Username

StoneLegion

### Your Pack Version

2.7.628 Nightly

### Your Server

StoneLegion

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

To Mine and find the stones.

### The Reality

Mined and all the stones are missing. 

![image](https://github.com/user-attachments/assets/72927eeb-5da7-48c8-bbeb-0e254524c5e2)

### Your Proposal

To add them back in. I assume when they were switching to the new ore system it prob got fried lol.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/3112
