### ISSUE TITLE
Firebrick block uncraftable without assembler

### ISSUE THREAD

**Issue by TotallyNotOndre** [GTNewHorizons/GT-New-Horizons-Modpack#17251]
### Your Pack Version

nightly 618, 633

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Trying to craft firebrick block. Expect to craft it in crafting table
![image](https://github.com/user-attachments/assets/57788e08-5dea-49f9-978e-d4830967a566)

### The Reality

There is no crafting table recipe for firebrick block, instead there is 2 duplicate assembler recipes
![image](https://github.com/user-attachments/assets/2e02ad4e-3e97-4c20-82bd-337bd5d5dc7a)
also recipe is not just hidden, it does not exist
![image](https://github.com/user-attachments/assets/3e316ddc-2b31-42bc-897b-7b5061fb4cbc)

### Your Proposal

Add recipe back

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/981
