### ISSUE TITLE
XL Turbo Plasma Turbine has incorrect consumption/generation values

### ISSUE THREAD

**Issue by Miklebe** [GTNewHorizons/GT-New-Horizons-Modpack#17258]
### Your GTNH Discord Username

mike_be

### Your Pack Version

nightly 637

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

When using XL version, both consumption and generation multiplied by 16.

### The Reality

XL version of Plasma Turbine is the same as Large version.
Loose mode:
![image](https://github.com/user-attachments/assets/0b58c53f-3220-445b-98c2-2dfa9921ab12)
![image](https://github.com/user-attachments/assets/a19a4f22-3dc1-42fd-97dd-92000550147f)
Tested usuing gaia spirit turbine
![image](https://github.com/user-attachments/assets/c5da26f6-ba14-4080-9c94-014b39ffcb2f)
Other XL versions (steam/gas) consume and produce correct values (16 times more) than their Large counterparts

### Your Proposal

Make XL Turbo Plasma Turbine great again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by S4mpsa** [comment]
Should be fixed https://github.com/GTNewHorizons/GT5-Unofficial/pull/3075/commits/491764b5b8c1f4a660586e82adbc577a3a782f46
