### ISSUE TITLE
Naga Boss Fight Crash Twilight Forest

### ISSUE THREAD

**Issue by romeguy82** [GTNewHorizons/GT-New-Horizons-Modpack#17268]
### Your GTNH Discord Username

porthos_82

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

During Naga boss fight, am unable to do anything, crashes shortly upon loading in.

### Crash Report

[crash-2024-09-08_19.36.29-client.txt](https://github.com/user-attachments/files/16924021/crash-2024-09-08_19.36.29-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by EnderProyects** [comment]
update to latest version

**Comment by EnderProyects** [comment]
or at least to this one
https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12
