### ISSUE TITLE
Crash Initializing Game

### ISSUE THREAD

**Issue by TFCrash** [GTNewHorizons/GT-New-Horizons-Modpack#17264]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

After fixing a problem with the Twilight mod and updating it to the latest version, the game does not load at all and stops at this screen, tried launching in offline mode, and no change
![image](https://github.com/user-attachments/assets/ebeba356-0d7f-40d2-9245-25127d9277c6)

### Crash Report

[crash-2024-09-09_00.41.57-client.txt](https://github.com/user-attachments/files/16923770/crash-2024-09-09_00.41.57-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment]
Use https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12 or update Mobs-info
