### ISSUE TITLE
Precise assembler tooltip is wrong

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#17278]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

Nightly 637

### Your Proposal

![image](https://github.com/user-attachments/assets/acc8faf2-43cf-4dc7-abd7-c92adc8e8525)
It says "Machine Casing and Energy Hatch limits the voltage tier the machine can work on"
It seems to be changed and that you now need the glass tier too, imo that should be changed

### Your Goal

Making the tooltip better

### Your Vision

It would be possible to understand without trying why machines didn't work anymore for example

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by serenibyss** [comment]
Precise assembler does not have tiered glass mechanics, this may have been a nightly bug but I'm not able to reproduce it in newer versions
