### ISSUE TITLE
Crash after restoring save

### ISSUE THREAD

**Issue by Neko-Yukari** [GTNewHorizons/GT-New-Horizons-Modpack#17273]
### Your Pack Version

2.6.1

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

We had a explosion in our base so we unzip our full-backup zip in the main diretory.
But then the server can't start with the following crash.
We 're running the server with the server pack from official website. But replace the old java with dragonwell which did't break anything before. And we also playing with Twist Space Technology mod.Which is the only one addtional content addon.

### Crash Report

[crash-2024-09-09_12.38.05-server.txt](https://github.com/user-attachments/files/16932903/crash-2024-09-09_12.38.05-server.txt)
[crash-2024-09-09_12.47.36-server.txt](https://github.com/user-attachments/files/16932904/crash-2024-09-09_12.47.36-server.txt)
[crash-2024-09-09_22.48.16-server.txt](https://github.com/user-attachments/files/16932905/crash-2024-09-09_22.48.16-server.txt)
[crash-2024-09-09_22.53.06-server.txt](https://github.com/user-attachments/files/16932906/crash-2024-09-09_22.53.06-server.txt)
[crash-2024-09-09_23.00.19-server.txt](https://github.com/user-attachments/files/16932908/crash-2024-09-09_23.00.19-server.txt)
[crash-2024-09-09_23.04.17-server.txt](https://github.com/user-attachments/files/16932910/crash-2024-09-09_23.04.17-server.txt)
The server-latest log have been accidently removed by another operator

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by fbfnysnshnsgnwg** [comment]
By the way isn't there aromabackup

**Comment by Lyfts** [comment]
It's failing to read your banned-players.json file so there's probably some messed up entry in there.
