### ISSUE TITLE
Allow Advanced Heat Vent to Be Crafted with Regular Diamonds

### ISSUE THREAD

**Issue by SparkedTheorem** [GTNewHorizons/GT-New-Horizons-Modpack#17279]
### Your GTNH Discord Username

SparkedTheorem

### Your Pack Version

2.6.1

### Your Proposal

The Advanced Heat Vent should be able to be crafted with both Industrial Diamonds and regular Diamonds.

### Your Goal

The Advanced Heat Vent is the only recipe that outright requires the Industrial Diamond rather than have it as an alternative to the regular Diamond, forcing you to also pattern/make Industrial Diamonds for this one recipe that is used frequently (Volcanus).

### Your Vision

The Industrial Diamond is easy to obtain from the regular Diamond by the time you are making the Advanced Heat Vent, making this a rather arbitrary restriction on the recipe. This would make crafting Volcanus casings in particular slightly less annoying.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Reflex18** [comment]
It would be nice if this was just ore dictionary with diamonds since it is rather strange that this one recipe enforces industrial diamonds.

**Comment by chochem** [comment]
this is intentional
