### ISSUE TITLE
Steam Mixer won't form Tier 2

### ISSUE THREAD

**Issue by Dyonovan** [GTNewHorizons/GT-New-Horizons-Modpack#17287]
### Your GTNH Discord Username

Dyonovan

### Your Pack Version

Nightly-612 (Also tried Nightly-628)

### Your Server

Private

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

That the Steam Mixer multi forms when built.

### The Reality

Using the following:

100 Solid Steel Machine Casings
2 Steel Gear Box Casing
2 Steel Pipe Casing
8 Iron Blocks
Steam Hatch
ULV Input/Output Hatch
Input/Output Bus (Steam)

Have tried replacing all busses/hatches with LV still nothing. Works fine for Tier 1 but just wont form with Tier 2

### Your Proposal

Have the multiblock form

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Baerschen** [comment]
Try it without the input hatch maybe. The centrifuge does not accept an input hatch aswell since its now allowed to do fluid recipes. That same restriction should be on the mixer.

**Comment by PlayfulPiano** [comment]
> Input hatch is mandatory. Tier 1 wont form without it. I also checked the code and its required.
> 
> > Try it without the input hatch maybe. The centrifuge does not accept an input hatch aswell since its now allowed to do fluid recipes. That same restriction should be on the mixer.

huh, that doesn't seem right. Mixer might be able to have a fluid hatch output but definitely not input.

**Comment by Miklebe** [comment]
Since it's in more info/testing/confirmation, after the rework on how steam multis work, they mixer forms in Tier 2
![image](https://github.com/user-attachments/assets/3883bd87-fadb-4615-9992-4dd51866fbcb)
![image](https://github.com/user-attachments/assets/09aefc49-a489-4ed8-a73e-6ced49d15e7c)
