### ISSUE TITLE
Ore Diagramm not showing all possibilites or not everything for GT++ Ores from Toxic Everglade

### ISSUE THREAD

**Issue by Phiapsi** [GTNewHorizons/GT-New-Horizons-Modpack#17282]
### Your GTNH Discord Username

Phiapsi

### Your Pack Version

2.6.1

### Your Server

Private

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Gregtech Ore Processing Diagramm in NEI shows all Outputs and possible processing steps for GT++ Ores

### The Reality

For Example: Kashinite Ore
![grafik](https://github.com/user-attachments/assets/c0add032-b4fe-466d-8328-f510484dff34)
 Has a Thermal Centrifuge Recipe:
![grafik](https://github.com/user-attachments/assets/5c912ade-ccd5-4184-b9f3-195da3c22d74)
and a secondary output in the Macerator
![grafik](https://github.com/user-attachments/assets/836b76ee-41b0-4493-ad32-73ab9c27d366)

### Your Proposal

Correcting the Ore-Diagrasms for the Ores in the Toxic Everglades

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
looks fine from what you are showing? the red circled thing certainly is in there.

**Comment by Phiapsi** [comment]
Oh yeah sorry, this was my fault. But the Thermal Centrifuge Recipe is missing

**Comment by chochem** [comment]
what is it?
