### ISSUE TITLE
AAL batch mode not working

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#17280]
### Your GTNH Discord Username

lordpeverell

### Your Pack Version

2.6.1

### Your Server

Aussie Private

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Enabling batch mode on 1 ticking AALs to function like all other multis. 

### The Reality

Batch mode on AAL for optical assembly is 128 @ 57.6s despite it 1 ticking with 4kA UXV on it. This does not make any sense 

Also have been told AALs are extremely laggy on nightly by TEG

### Your Proposal

Fix the issue with batch mode on AAL to help cut down on tps hit

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
isnt it just 9 slices x 6.4s?
