### ISSUE TITLE
Blocks get exchanged

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#17281]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

Nightly 637

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

The world should be normal

### The Reality

Some blocks get changed into other ones
A few examples that I noticed:
Randomly korp 14 turning into korp 0 (not all in the base, just randomly 
![image](https://github.com/user-attachments/assets/8543b540-9fb9-46d0-a073-e5d467e6766b)
Compact Fusion Coil MK-II Finaltype (the compact mk5 ones) turn into ameliorated superconduct coils
![image](https://github.com/user-attachments/assets/9683d0f4-2f7e-478d-8be6-72074b509e47)
UHV machine casings that were for buiding the precise assemblers turned into ULV machine hulls
![image](https://github.com/user-attachments/assets/1d0b22c4-63e0-4b14-aeaf-014a8c9c9067)

### Your Proposal

Would be nice that it can be fixed that blocks didn't kinda randomly change to other ones cause that could brick whole bases

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by RecursivePineapple** [comment]
It looks like the metadata is getting set to zero. Did you keep this world @MaGeBZz? Did the korp change affect all korp blocks in the same chunk?

**Comment by MaGeBZz** [comment]
@RecursivePineapple yeah I got the both the world before and after updating

![image](https://github.com/user-attachments/assets/7a4c818c-890e-4e14-8737-74a6cb20e680)
And yeah seems to be a chunk thing I guess but not 100% sure
You can see the black antiblocks are metadata 0 and the korp changed but it's really weird cause the other korp blocks one block next to it are fine
Seems to be random and even machine hulls etc can be changed from that

**Comment by Chaoschaot232** [comment]
Possible affected is also my bug #17334 where the same random block change happens and when the area isn't chunkloaded this problem is much more aggressive.

See also Discord: https://canary.discord.com/channels/181078474394566657/522098956491030558/1285065040722001950

**Comment by Cleptomania** [comment]
This has been fixed with NotEnoughIDs 2.1.5
