### ISSUE TITLE
Crash may be caused by TF?

### ISSUE THREAD

**Issue by rstonghua** [GTNewHorizons/GT-New-Horizons-Modpack#17296]
### Your Pack Version

2.6.1

### Your Server

private server(with LAN)

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Actions

My friends puresky(ID) was staying in the twilight forest. He is searching for Twilight Lich. He haven't found yet and the server crash. After the crash, I restart the server. My another friend stay in the overworld can join the server and play normally. However, when my friend puresky login again, the server crashed again. It seems that he can't join, if he join, the server will be crashed.

### Crash Report

[crash-2024-09-09_21.30.54-server.txt](https://github.com/user-attachments/files/16962313/crash-2024-09-09_21.30.54-server.txt)
The report on 09.09 is the first crashed happend.
[crash-2024-09-10_21.38.10-server.txt](https://github.com/user-attachments/files/16962322/crash-2024-09-10_21.38.10-server.txt)
[crash-2024-09-10_21.46.26-server.txt](https://github.com/user-attachments/files/16962354/crash-2024-09-10_21.46.26-server.txt)
The report on 09.10 are the puresky's try to join the server which caused the crash again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by PoseidonTsunami11** [comment]
I have the same problem but i went back to an earlyier save it happens every time. I think its twighlight forest if f'd I only get it when joining twighlight forest. Worst case until its fixed reload to earlyier version and proceed as necessary until the dev fixes it. If you need my save/ crash report just ask :)

**Comment by UZ-Queen** [comment]
Try downgrading your TF version. In my case, Downgrading to 2.4.3 stopped the server from crashing.
Maybe the new version of Twilight Naga generation seems to make some problems.

**Comment by Lyfts** [comment]
2.4.3 is over a year old, don't downgrade to that. The problem in this case is with world corruption not with whichever TF version you're using.

**Comment by Fundevoge** [comment]
We had the same problem in our world, "hotfix" is to tp the player to the TF entrance by changing the world data with nbt explorer (tp command does not work because the server crashes before it can be executed). Then don't go near the structure again until this bug is fixed.
