### ISSUE TITLE
GT Wood Pulp to GT Wood Planks has a 1x and 8x recipe in the Compressor. 

### ISSUE THREAD

**Issue by StoneLegion** [GTNewHorizons/GT-New-Horizons-Modpack#17291]
### Your Pack Version

2.7.639 Nightly

### Your Server

StoneLegion

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

One Recipe...

### The Reality

Two Recipes lol 
![image](https://github.com/user-attachments/assets/70159b1f-da9d-41cc-92d7-6d8782c1c9f3)
![image](https://github.com/user-attachments/assets/a6352771-1890-4081-8ce6-866cd93028a3)

### Your Proposal

One Recipe Only:
![image](https://github.com/user-attachments/assets/b0e72d28-ee98-4e63-9890-b544bbb36062)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
https://discord.com/channels/181078474394566657/252440750174765057/1277248046446547015
