### ISSUE TITLE
Some Log Pipe Modules Can't be Crafted Till HV

### ISSUE THREAD

**Issue by Dyonovan** [GTNewHorizons/GT-New-Horizons-Modpack#17297]
### Your GTNH Discord Username

Dyonovan

### Your Pack Version

Nightly-612

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Trying to craft the Active Supplier Module but the recipe doesn't fit into a LV or MV Forming Press. Having these blocked behind HV seems to be far into progression and should be available in MV

### The Reality

The recipe for some modules require a LV Forming Press. (eg: Active Supplier Module) The recipe is 3 items yet the Forming Press for both LV/MV only has 2 slots.

### Your Proposal

Make the recipes require an Assembler instead of a Forming Press

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by StaffiX** [comment]
Active Supplier in particular was fixed by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/971

**Comment by Dyonovan** [comment]
Sorry totally missed that
