### ISSUE TITLE
Chembalance Electrotine dust

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#17307]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Making and centrifuging electrotine dust would use and make 1 redstone and 1 electrum respectively.

### The Reality

1 electrum and 1 redstone are used to _create_ 1 electrotine, but _8_ electrotine is centrifuged into 1 redstone and 1 electrum.

![image](https://github.com/user-attachments/assets/905d0b7b-401b-4f4f-aa9b-6afc056cf51b)
![image](https://github.com/user-attachments/assets/fee1a14f-3ddc-456b-9545-c546c4ad91de)

### Your Proposal

Balance it to be like other dusts. 1 + 1 creates 2, and 2 centrifuges into 1 + 1.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
Pretty sure this issue is stale now since electrotine mixer recipe was removed
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/7c14aed2ea262208c529761933eccabc3fe7a580

**Comment by chochem** [comment]
not removed no. but was fixed apparently (was probably a conflict)
![image](https://github.com/user-attachments/assets/a78cb96f-4b22-46bc-9876-999adc1cc470)
