### ISSUE TITLE
hodgepodge and gt++ throwing 474 exceptions on client start.

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#17302]
### Your GTNH Discord Username

chochem

### Your Pack Version

nightly-636 mostly

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

no exceptions

### The Reality

```[Hodgepodge/miscutils]: An Exception occured while invoking Item.getUnlocalizedName() after registering the item miscutils:blockBlockSelenium (gtPlusPlus.core.item.base.itemblock.ItemBlockGtBlock)! Using fallback unlocalized name.```
and 473 similar entries one after the other in gt++ preinit.

full log: 
[fml-client-latest.log](https://github.com/user-attachments/files/16969120/fml-client-latest.log)

### Your Proposal

fix it :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
likely caused by https://github.com/GTNewHorizons/Hodgepodge/pull/398 and likely related to this not showing proper names
![image](https://github.com/user-attachments/assets/ad46f0b9-dad3-4c57-9760-8a0413ea8f3c)

**Comment by glowredman** [comment]
Summary of my Discord mesage:
The stats GUI not showing localized names is a different issue. The log spam has been solved.
