### ISSUE TITLE
Flesh root is 1 to 1 mince meat by hand, 9 to 1 in macerator

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#17315]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

That macerating flesh root would yield the same or more mince meat than hand grinding it.

### The Reality

It doesnt. You need 9 flesh root for macerator recipe, but only 1 by hand

![image](https://github.com/user-attachments/assets/c2a21e1a-34f9-4912-9504-2521e021cad6)
![image](https://github.com/user-attachments/assets/01c9f886-276a-4c26-a73e-9fa88ce6ad5a)

### Your Proposal

Make it equivalent?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ERRRR0R** [comment]
In Daily 433 this problem exists with the new Fleshroot from Fether

<img width="327" height="125" alt="Image" src="https://github.com/user-attachments/assets/ff80881b-316d-4bc2-acdc-5b62eeaabace" />

<img width="345" height="216" alt="Image" src="https://github.com/user-attachments/assets/02753def-884d-4583-86e6-5b760e3cae09" />

**Comment by ERRRR0R** [comment]
Still a problem in Daily 499
