### ISSUE TITLE
Cleanup startup errors/warnings

### ISSUE THREAD

**Issue by TotallyNotOndre** [GTNewHorizons/GT-New-Horizons-Modpack#17324]
### Your Pack Version

nightly

### Your Proposal

Wipe startup warnings and errors from existence (at least most of them)

### Your Goal

Improving pack stability and log readability
also reducing log size in about a half

#### Over some time modpack collected a big amount of startup warnings and errors making log harder to read
So i launched clear installation of latest nightly(645) and recorded log from launch to main menu
Here is what we currently have:
![image](https://github.com/user-attachments/assets/09011f86-4c30-47d3-9284-132d3236e2bc)
_(about a half of startup log are warnings and errors)_

[full.log](https://github.com/user-attachments/files/16997536/full.log) - full log recording
[errors.log](https://github.com/user-attachments/files/16997531/errors.log) - mostly WARN and a bit of ERROR

Fixing those errors can not only improve log readability and free 612kb of data on each startup but also improve modpack stability

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TotallyNotOndre** [comment]
Related https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17299

**Comment by chochem** [comment]
'please fix all bugs' is not a useful ticket. Make tickets for specific stuff. Though all (?) client start errors already have indivudual tickets so thats just duplicate.
