### ISSUE TITLE
[Nightly] Steam Tier Furnace has an incorrect tooltip type

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#17329]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.7.0 nightly 645

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

![image](https://github.com/user-attachments/assets/d606b49e-8084-4064-a6f1-d39c829329b1)

### The Reality

![image](https://github.com/user-attachments/assets/0f813c23-d632-4dcd-91af-e05287bcd36f)
![image](https://github.com/user-attachments/assets/f568cca8-33ae-4a37-a909-059f1f9e04fe)
(also the NEI page text is layered on top of tooltips lol)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
isn't you that changed this code recently ?

**Comment by PlayfulPiano** [comment]
> aren't you the one that changed this code recently ?

Only the string name with HP having "steam" included, anything else wasn't touched at all. The only significant changes I did were regarding the multis.

**Comment by FourIsTheNumber** [comment]
Closed by above pr
