### ISSUE TITLE
Change Callisto/Jupiter Queen to produce the correct Callisto Ice Dust

### ISSUE THREAD

**Issue by DiddyG** [GTNewHorizons/GT-New-Horizons-Modpack#17327]
### Your GTNH Discord Username

DaddyDiddy

### Your Pack Version

2.6.1

### Your Proposal

The Callisto and Jupiter Queen produces the Dreamcraft Version of Callisto Ice Dust. It should be changed to produce the GregTech version of the dust instead. 

![callisto queen](https://github.com/user-attachments/assets/5d38333b-0827-4f39-b15e-0c52c73385f0)
![jupiter queen](https://github.com/user-attachments/assets/b52ee89d-05d4-45d3-9b70-f504bbdba3d7)

### Your Goal

Once you pick up the Dreamcraft version of the Callisto Ice Dust, it auto ore-dictionaries to the GregTech version, so there is no need for the bee to produce the other variant. 

### Your Vision

It would make passive setups for Super Coolant more accessible. Every server restart requires changing the Callisto ice dust back to the Dreamcraft variant because AE auto-dictionaries

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
better yet, remove one. :)
