### ISSUE TITLE
can't place pipes or cables one after an other

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#17325]
### Your Pack Version

645

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

wiring 2 machines by placing a line of cables one over the other

### The Reality

![image](https://github.com/user-attachments/assets/2e6a7b01-a1c1-4ed0-8a34-62db91fcfa6b)
i can't click with a new pipe over the last one to make a continuous conduct. i have to palce it on some block and the connect them with a wrench.
same goes for cables.

### Your Proposal

fix the bug?

offtopic: can we merge the expetation/reality/proposal fields? i don't get the point of separating those three fields and i always end up typing down obvious/meme stuff in the other 2

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by tommmmmmmmm** [comment]
ok, the "issue" is "fixed" by shift-clicking.

**Comment by fbfnysnshnsgnwg** [comment]
Should be closed

**Comment by FourIsTheNumber** [comment]
I don't think this should be closed. I am fairly sure this is lost functionality and it is pretty irritating, since you now have to use shift when building cable lines while flying. I believe this was not the case until recently.

**Comment by Reflex18** [comment]
Four is correct, this never used to be the case that it required a shift right click. This is a regression in the code that has come up since nightly 644.

**Comment by chochem** [comment]
broken by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3160
