### ISSUE TITLE
No way to make clay bucket without first having a bucket

### ISSUE THREAD

**Issue by alphaomega21** [GTNewHorizons/GT-New-Horizons-Modpack#17337]
### Your GTNH Discord Username

schrodingercatz

### Your Pack Version

Nightly 2.7.0 646

### Your Proposal

As far as I can tell there is no way to make a clay bucket without first making an iron bucket which is much harder to get the resources for early game. The current clay bucket uses clay dust which doesn't really make sense. I suggest that this is changed to using normal clay as that makes more sense from a realism perspective and is easier to achieve.

### Your Goal

Make the early game a bit less tedious and more predictable.

### Your Vision

Make the early game a bit less tedious and more predictable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by FourIsTheNumber** [comment]
> ### Your GTNH Discord Username
> 
> schrodingercatz
> ### Your Pack Version
> 
> Nightly 2.7.0 646
> ### Your Proposal
> 
> As far as I can tell there is no way to make a clay bucket without first making an iron bucket which is much harder to get the resources for early game. The current clay bucket uses clay dust which doesn't really make sense. I suggest that this is changed to using normal clay as that makes more sense from a realism perspective and is easier to achieve.
> ### Your Goal
> 
> Make the early game a bit less tedious and more predictable.
> ### Your Vision
> 
> Make the early game a bit less tedious and more predictable.
> ### Final Checklist
> 
>     * [x]  I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying _I like this change please reconsider adding it_ will prompt us to investigate and reopen it once we confirm your report.
> 
>     * [x]  I understand this change request may not attract enough attention and thus not be implemented.
> 
>     * [x]  I understand this change request may be rejected due to other community members think it's inappropriate.
> 
>     * [x]  I believe this feature would make the pack better.

Clay dust is made with clay balls and a mortar. You do not need an iron bucket.

**Comment by Miklebe** [comment]
@FourIsTheNumber Actually it's not. 
![image](https://github.com/user-attachments/assets/5d7e3326-4e94-4a69-a56e-34c6fa9366cc)
![image](https://github.com/user-attachments/assets/a6a0235a-4743-446d-96cf-c7bdaeb00efd)
I mean i guess looking for hardened clay in mesa/desert biomes is an option, but not the best one?

**Comment by FourIsTheNumber** [comment]
> @FourIsTheNumber Actually it's not. ![image](https://private-user-images.githubusercontent.com/48237322/367532687-5d7e3326-4e94-4a69-a56e-34c6fa9366cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMzM3NDIsIm5iZiI6MTcyNjMzMzQ0MiwicGF0aCI6Ii80ODIzNzMyMi8zNjc1MzI2ODctNWQ3ZTMzMjYtNGU5NC00YTY5LWE1NmUtMzRjNmZhOTM2NmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE3MDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZDdlZTlmMTZlM2U0YmE5YmRlN2Y5ZDViZWVmZjAyNWIyY2MwZTBmNDU3MmRiOTRlODU1NTU2ZDU5NmFlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gv9JaQm1OcbNqJ8SE_WGD5iqoUvrPBsEoGxP85tSQR8) ![image](https://private-user-images.githubusercontent.com/48237322/367532699-a6a0235a-4743-446d-96cf-c7bdaeb00efd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMzM3NDIsIm5iZiI6MTcyNjMzMzQ0MiwicGF0aCI6Ii80ODIzNzMyMi8zNjc1MzI2OTktYTZhMDIzNWEtNDc0My00NDZkLTk2Y2YtYzdiZGFlYjAwZWZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE3MDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZWZjNjg0YmFlNjcyYTE0MGRlOTdiOTZlNTI0ODFjOGFkMmE2Yzg1Y2QxODA3NjM1ZTVlZDY1MzE1OTQ2NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BieToXWDe4zaBlbicDBRbFh1dB7L8Rq1arqxTuUJ918) I mean i guess looking for hardened clay in mesa/desert biomes is an option, but not the best one?

Check uses for clay ball. It makes small piles of dust.

**Comment by Miklebe** [comment]
Ah, shit, my bad, forgot that clay has shit ratio to dust.

**Comment by alphaomega21** [comment]
> Check uses for clay ball. It makes small piles of dust.

Ahh, you are right. Not sure how I missed that recipe.
