### ISSUE TITLE
Certain stargate crystal slurry ingredients uncraftable

### ISSUE THREAD

**Issue by fbfnysnshnsgnwg** [GTNewHorizons/GT-New-Horizons-Modpack#17336]
### Your Pack Version

2.7.0 nightly 645

### Your Server

sp

### Java Version

Java 17

### Type of Server

None

### Your Expectation

stargate crystal slurry components such as infinity plasma are craftable

### The Reality

isn't craftable

### Your Proposal

Make plasmas like infinity plasma and six phased copper craftable in plasma fabricator

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by fbfnysnshnsgnwg** [comment]
uncraftable ones are infinity, six phased copper and bedrockium

**Comment by NotAPenguin0** [comment]
Craftable in the godforge, which is still disabled by default in some nightlies (it will be enabled soon)
