### ISSUE TITLE
Crash with world and Railcraft while updating it to newer pack version / World corruption when updating from 2.5.1 to nightly

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#17334]
### Your GTNH Discord Username

Marcel|Chaoschaot234

### Your Pack Version

GTNH Nightly build 2024-09-13+645

### Your Server

private mp server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

I downloaded the nightly build, replaced Angelica (unfinished) with Fastcraft and Optifine (for shader usage). I also replaces ServerUtilities (not getting the stuff from FTBL/FTBU) with FTBLib and FTBUtilities so that our homes and chunkloads are working correctly and intended

### Crash Report

Logfile from MMC: https://paste.ee/p/Co6AF

Crash reports:
[crash-2024-09-14_07.19.07-server.txt](https://github.com/user-attachments/files/17001249/crash-2024-09-14_07.19.07-server.txt)
[crash-2024-09-14_07.44.51-server.txt](https://github.com/user-attachments/files/17001250/crash-2024-09-14_07.44.51-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Chaoschaot232** [comment]
Here is also a uploaded version from the game: https://mclo.gs/EB6Foej

**Comment by Chaoschaot232** [comment]
Update 2: https://mclo.gs/AIu3i6B

This crash behaves even without using optifine

**Comment by Chaoschaot232** [comment]
Another update:

There seem to a problem with a changed made within this pack to some vanilla items like stone slabs because after this error I migrated from 2.5.x to 2.6.1 stable and it loaded in perfectly. After this I loaded the converted and saved world into this nightly build and here is what triggered this crash:

![image](https://github.com/user-attachments/assets/e778cb22-923d-473b-b507-04e28393b6eb)

As you can see the port flipps levers and regulare vanilla quartz slabs are turned into normal stone slabs at the wrong position. Unsure why this happends because our entire track is made out of nether quarz slabs so why where they turned into the wrong item? Sounds for me after a horrible wrong going migration bug.

here you can see that we are useing vanilla quarz slabs and not stone slabs:

![image](https://github.com/user-attachments/assets/aed8cfab-776b-4658-9812-5a11b5e17617)

**Comment by Chaoschaot232** [comment]
Here I am sahring two new screens with waila info which is missing due to an 10MB image upload limit within github itself.

2.7.0 - nigthly Screenshot with replaced vanilla quarz slabs (meta ID = 7) into vanilla stone slabs (meta ID = 0). Also you can see that levers are flipped:
![image](https://github.com/user-attachments/assets/b382eeca-b5d7-44e2-a05f-5217c43a5c48)

2.6.1 - stable Screenshot, where slabs aren't changed:
![image](https://github.com/user-attachments/assets/7b2e5113-760d-4b9a-a2ba-6f71d8eb9603)

**Comment by Cleptomania** [comment]
This is fixed with NotEnoughIDs 2.1.5
