### ISSUE TITLE
tengam meteor requires slightly more than 1b lp

### ISSUE THREAD

**Issue by fbfnysnshnsgnwg** [GTNewHorizons/GT-New-Horizons-Modpack#17338]
### Your Pack Version

2.7.0 nightly 645

### Your Server

sp

### Java Version

Java 17

### Type of Server

None

### Your Expectation

try to spawn tengam/salt meteor. it spawns

### The Reality

nausea with blood orb of armok
![2024-09-14_13 50 12](https://github.com/user-attachments/assets/4faa6467-00a2-4688-9fbe-f8a74060e781)
![2024-09-14_13 50 53](https://github.com/user-attachments/assets/e9da7928-3516-4d88-8fe5-1052b317b86e)

### Your Proposal

decrease cost by 1 lp

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
Intended. YOu need to hold armok, then place it in a blood altar  with orb runes to charge.

**Comment by NotAPenguin0** [comment]
This is intended
