### ISSUE TITLE
Cleanroom Allows Elevator but not Rotating Elevator

### ISSUE THREAD

**Issue by Ruling-0** [GTNewHorizons/GT-New-Horizons-Modpack#17341]
### Your GTNH Discord Username

ruling_

### Your Pack Version

Nightly 646

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

As worked previously and as the tooltip states, cleanroom should work with a rotating elevator in the floor.

### The Reality

The migrated cleanroom (N583 to N646), with a rotating elevator in the floor, registered as incomplete structure until the rotating elevator was replaced with either a normal elevator or plascrete.

### Your Proposal

Let rotating elevator work in the floor again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miklebe** [comment]
The problem lies in the default config that is getting shipped 
![image](https://github.com/user-attachments/assets/49c12463-1921-4030-b786-a6299bdc2dbc)
it has no rotating elevator entry. Stable releases had it.

**Comment by KleinGrrmpf** [comment]
Now (2.7.0-beta-1) the Cleanroom doesn't even accept the normal elevator despite the config saying that it allows one...
Tested it by having a normal Elevator in the hull (Structure Incomplete) and replacing the Elevator with a Plascrete Block (works). And yes, that was my only elevator.
![grafik](https://github.com/user-attachments/assets/f47c7212-a204-42eb-9000-0b0f857b37d0)

**Comment by OvermindDL1** [comment]
Machine Hulls as part of the cleanroom wall was also broken (was using it to send items/fluids through, questbook says hulls should work), though Diodes still work fine for power at least?
