### ISSUE TITLE
Electrolyzing sphalerite recipe collision

### ISSUE THREAD

**Issue by copinwr** [GTNewHorizons/GT-New-Horizons-Modpack#17344]
### Your GTNH Discord Username

copin ruimdade pura

### Your Pack Version

nighly 645

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

expected to receive gallium when electrolyzing sphalerite
![2024-09-14_19 32 40](https://github.com/user-attachments/assets/2b91c6c2-406a-404f-bcaa-e5b966daade3)

### The Reality

did not receive due to recipe collision

### Your Proposal

solve recipe collision for sphalerite electrolyzing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
https://discord.com/channels/181078474394566657/252440750174765057/1277248046446547015
