### ISSUE TITLE
Idea: Casting/modifying GT tools with Tinker's equipment.

### ISSUE THREAD

**Issue by seventh-june** [GTNewHorizons/GT-New-Horizons-Modpack#17343]
### Your GTNH Discord Username

neura#2020

### Your Pack Version

2.6.1

### Your Proposal

Have GT tools (hammers, files, wire cutters, etc) be made or upgraded with Tinker's modifiers and repair system, and to be cast with smeltery fluids.

### Your Goal

Increases the need for the Tinker's smeltery, and gives incentive towards improving your own tools since you wouldn't want to use a good material on a tool that would break in a stack or two.

### Your Vision

I think it's a good QOL addition and gives a new incentive for using the smeltery.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LazyFleshWasTaken** [comment]
COuld be good for like, wrench/wire cutter.

But at the same time, not very much use when you get manasteel/shadowmetal/vanadiumsteel/vibrant alloy since at that point gt tools have a ton of durability.

Also, the smeltery is cumbersome to use, and the good parts aren't in the smeltery anwyay, but shape-extruded in the gt extruder.

**Comment by chochem** [comment]
we don't really want (more) incentives for using the smeltery. And yea very limited on materials in tinkers.
This is a gt pack.
