### ISSUE TITLE
Updating World Breaks All Framebox-Using Multis

### ISSUE THREAD

**Issue by Ruling-0** [GTNewHorizons/GT-New-Horizons-Modpack#17340]
### Your GTNH Discord Username

ruling_

### Your Pack Version

Nightly 646

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Multis should cleanly migrate their frameboxes.

### The Reality

Migrating a world from Nightly 583 to 646 broke every framebox using machine, all were incomplete structure and projector highlighted the frame box (which were names Frame Box (Tile-Entity)). Replacing just the frame boxes with non-TE version fixed them. Migrating the same world with Postea 1.0.9 worked.

### Your Proposal

Fix what broke between Postea 1.0.10 and 1.0.9.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
This is fixed right @NotAPenguin0 ?

**Comment by NotAPenguin0** [comment]
I think Clepto fixed this yes

**Comment by Alexdoru** [comment]
> I think Clepto fixed this yes

I tagged the wrong person then haha !
