### ISSUE TITLE
Fluid pipe connection not functional

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#17356]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.7. Nightly - 618

### Your Server

Zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

just one connection:

![grafik](https://github.com/user-attachments/assets/7766fab0-64ad-4279-9bb1-51d6e211ca66)

### The Reality

connection over all

![grafik](https://github.com/user-attachments/assets/309ee17c-2633-4c19-85f0-e384c13a5d8c)

no cross or side connection possible

![grafik](https://github.com/user-attachments/assets/9d9846da-1e1b-4d7d-ac87-a8e5f014dae9)
 

### Your Proposal

Additional functions for fluid pipe shall active by alternative keys like ALT or Ctl or...
Standard function without key shall be original

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miklebe** [comment]
Change your wrench mode using shift-right click in the air?

**Comment by Ngar1** [comment]
New unknown funktion
