### ISSUE TITLE
Acetaldehyde has duplicate recipes in LCR

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17354]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Acetaldehyde has one recipe in LCR.

### The Reality

Acetaldehyde has duplicate recipes in LCR: with 4 and 5 circuits and same input fluids:
![2024-09-15_14 57 33](https://github.com/user-attachments/assets/442774a5-b386-428d-a463-40af0d9f04e9)

### Your Proposal

Delete one of recipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
Should be fixed in 2.7
![2024-10-10_20 38 25](https://github.com/user-attachments/assets/28438c0a-ba9b-484c-a867-0e14a14663a8)
