### ISSUE TITLE
Make Forestry Cinnamon Trees produce Cinnamon instead of Apples.

### ISSUE THREAD

**Issue by Halloerik** [GTNewHorizons/GT-New-Horizons-Modpack#17365]
### Your GTNH Discord Username

Halloerik

### Your Pack Version

2.6.1

### Your Proposal

Currently Forestry Cinnamon Trees have Apples as produce. They should instead produce their namesake cinnamon.

### Your Goal

Me and my friend were not able to find pam's cinnamon in the world. So I spent multiple irl days breeding forestry trees to get cinnamon that way.  
However that work was completely wasted upon the realization that the forestry cinnamon trees do not produce cinnamon.

### Your Vision

This change would prevent multiple irl days being wasted and make the pack function in a more realistic and intuitive way.  It would be rewarding ingenuity and perseverance instead of punishing new players for their initiative.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
I think that since cinnamon comes from the wood, some extraction recipe from wood could fit better :3
