### ISSUE TITLE
Bucket of Chocolate Milk has no recipe

### ISSUE THREAD

**Issue by Star-Tube** [GTNewHorizons/GT-New-Horizons-Modpack#17364]
### Your GTNH Discord Username

star_tube

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Liquid chocolate milk can be put in buckets and then used in the recipe for chocolate icecream

### The Reality

chocolate milk cannot be put in buckets

### Your Proposal

gimme my choccy milk

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Persus1** [comment]
You get chocolate milk buckets by milking chocolate cows from thaumic horizons.

![image](https://github.com/user-attachments/assets/212645ff-4d0f-4665-bb12-a4b22df1b883)

**Comment by Star-Tube** [comment]
pain. fair enough then.
