### ISSUE TITLE
Upload Mods to curseforge

### ISSUE THREAD

**Issue by xSaucychan** [GTNewHorizons/GT-New-Horizons-Modpack#17376]
### Your GTNH Discord Username

saucy4869

### Your Pack Version

DEV

### Your Proposal

upload the following forks to curseforge for use in modpacks
https://github.com/GTNewHorizons/AdventureBackpack2
https://github.com/GTNewHorizons/AE2FluidCraft-Rework
https://github.com/GTNewHorizons/ae2stuff
https://github.com/GTNewHorizons/AkashicTome
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial
https://github.com/GTNewHorizons/BetterCrashes
https://github.com/GTNewHorizons/BetterP2P
https://github.com/GTNewHorizons/BugTorch
https://github.com/GTNewHorizons/Botania
https://github.com/GTNewHorizons/Chisel
https://github.com/GTNewHorizons/ChiselTones
https://github.com/GTNewHorizons/CookingForBlockheads
https://github.com/GTNewHorizons/FindIt
https://github.com/GTNewHorizons/HoloInventory
https://github.com/GTNewHorizons/MalisisDoors
https://github.com/GTNewHorizons/Mantle
https://github.com/GTNewHorizons/Natura
https://github.com/GTNewHorizons/NaturesCompass
https://github.com/GTNewHorizons/NEI-Integration
https://github.com/GTNewHorizons/NotEnoughEnergistics
https://github.com/GTNewHorizons/Nutrition
https://github.com/GTNewHorizons/OpenBlocks
https://github.com/GTNewHorizons/OpenModsLib
https://github.com/GTNewHorizons/ProjectRed
https://github.com/GTNewHorizons/SpiceOfLife
https://github.com/GTNewHorizons/TCNEIAdditions
https://github.com/GTNewHorizons/TinkersConstruct
https://github.com/GTNewHorizons/ThaumcraftMobAspects
https://github.com/GTNewHorizons/thaumcraft-research-tweaks
https://github.com/GTNewHorizons/ThaumicEnergistics
https://github.com/GTNewHorizons/twilightforest, specifically the version that provided tinkers construct integration 
https://github.com/GTNewHorizons/WirelessCraftingTerminal

### Your Goal

Make it easier for the community to distribute the mods in their own modpacks and all the work that has went into improving the old mods available to a winder player base

### Your Vision

Have the following mods available on curseforge for use in my own modpack and allow the developers that contributed to improving and fixing bugs in their forks of the mods get the credit they deserve

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Cleptomania** [comment]
We only upload mods to curseforge or modrinth which are under active support according to the [states of mod support spreadsheet](https://docs.google.com/spreadsheets/d/1LHd8c4FLLHiJqsuTppF2XFTE6bh-mXE7afVwGbzOKms/edit?gid=1469028684#gid=1469028684).

In order for a mod to be under active support, it needs to have at least one volunteer in the org being the primary maintainer for it outside of the pack.

**Comment by xSaucychan** [comment]
Some of the mods listed on the spreadsheet are not available on curseforge though but are listed as active. Could some of them be reconsidered for upload that are active. I can gladly edit the request and remove any that are passive

**Comment by joshaup1999** [comment]
> Some of the mods listed on the spreadsheet are not available on curseforge though but are listed as active. Could some of them be reconsidered for upload that are active. I can gladly edit the request and remove any that are passive

Never gonna happen, curseforge does not allow it. Hence why NH has to use a custom loader for the curseforge version and why everyone recommends not using curseforge

**Comment by mitchej123** [comment]
Some of them are already there... (spice of life).

Some of them I'm holding off on until they stabilize a bit (Twilight forest)

And some I'd be open to... FindIt jumps to mind...  I have permission from mydio on Tinker's (Unofficial), but have.. been lazy

**Comment by xSaucychan** [comment]
> Some of them are already there... (spice of life).
> 
> Some of them I'm holding off on until they stabilize a bit (Twilight forest)
> 
> And some I'd be open to... FindIt jumps to mind... I have permission from mydio on Tinker's (Unofficial), but have.. been lazy

Thank you for the response. I only ask because I was interested in using some of them for my own modpack and don't want to rely on downloading them from external sources if it can be helped. Cause if curseforge decides to one day stop mods that allow the downloading of additional files especially full mods it could break things for people that decide to play my modpack. I'd also like the people that worked on the mods to get recognition or cf points or other compensation if they have that enabled for any of their projects

**Comment by EndangeredNayla** [comment]
Regardless they are now in the CF database so modpacks including yours can add them w/o the mods being on the site aka being in the overrides.

**Comment by EndangeredNayla** [comment]
> Never gonna happen, curseforge does not allow it. Hence why NH has to use a custom loader for the curseforge version and why everyone recommends not using curseforge

Your suprisonally wrong, i requested and they didnt have an issue with it. Seeing its a fork and not the same version of CF.

**Comment by EndangeredNayla** [comment]
From my private DMs with Saucy. Out of those 35 mods, 31 got approved, 1 got rejected due to me filling out the form wrong, 1 got rejected due to licensing, and 1 has unknown status. (I think i forgot to submit it)

**Comment by mitchej123** [comment]
Out of curiosity, which got rejected due to license?

**Comment by EndangeredNayla** [comment]
I think it was NEI I Integrations. I think it had to bw because it was dual licensed or something stupid

**Comment by EndangeredNayla** [comment]
Not stupid licensing but stupid rules

**Comment by mitchej123** [comment]
NEI integrations isn't even dual licensed... it was re-licensed (as allowable by MIT) to LGPL...

**Comment by EndangeredNayla** [comment]
I'll ask again about that one could of been me filling the info wrong
