### ISSUE TITLE
Add the ability to select and cycle through tools within the Tool Box.

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#17379]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.6.1

### Your Proposal

When holding the Tool box, you can cycle between stored tools (either through a hotkey or maybe something like shift+scroll wheel), and then you can use that tool's functionalities without having to take it out of the tool box itself.

### Your Goal

QoL addition, less inv management woes / annoyances with using tool boxes.

### Your Vision

Idea concept is based on the Tool Belt mod for more recent versions (I just saw it mentioned in Monifactory, figured a similar implementation could be done for GTNH)

https://www.curseforge.com/minecraft/mc-mods/tool-belt

(obv this mod shouldn't be backported as it's ARR, but the concept of scrolling through the tool box makes sense for our purposes here)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
that sounds like the multitool we backported from gt6?

**Comment by PlayfulPiano** [comment]
> that sounds like the multitool we backported from gt6?

Yeah I'm aware of the multitool, but from what I've heard with its implementation is that it causes some issues when using shift related actions, that or with wrench actions specifically. People in the discord recommended against it from what I've seen and asked previously.

I guess the alternative suggestion here would be to modify the multitool to have swapping and shift click actions completely separate?
