### ISSUE TITLE
Steam Blender multiblock does not form without input and output liquid hatch

### ISSUE THREAD

**Issue by UnnamedBeast** [GTNewHorizons/GT-New-Horizons-Modpack#17378]
### Your GTNH Discord Username

UnnamedBeast

### Your Pack Version

Nightly 645

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Forming a Steam Blender multiblock with just input and output bus and no liquid hatches of any kind.

### The Reality

Steam Blender multiblock did not form until adding both input and output liquid hatches.
![Screenshot 2024-09-18 101252](https://github.com/user-attachments/assets/6e1a77c5-f71f-471b-ba0e-c93dbb472461)
![Screenshot 2024-09-18 101311](https://github.com/user-attachments/assets/b3cc2e19-1971-4fb0-8b66-0c53917bc7ad)

### Your Proposal

Either allow Steam Blender to form without input and output liquid hatches, due to the questbook saying that it both doesn't require it (item list does not list the hatches) and also due to it not being able to process liquids, or allow the Steam Blender to process liquids through the liquid hatches.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PlayfulPiano** [comment]
technically a repeat of #17287 no?

**Comment by UnnamedBeast** [comment]
> technically a repeat of #17287 no?

Not really, because its about the tier 1 not forming unless it has input and output hatches, which are completely useless on the multi because the multi can't use them

**Comment by Miklebe** [comment]
> technically a repeat of #17287 no?

In that ticket the problem was with forming in earlier nightlies, when steam multis still "could" do MV recipes with tier 2 upgrade. After their logic was reworked to only allow LV recipes, Steam Blender started forming.
![image](https://github.com/user-attachments/assets/21500cce-3e76-45f5-9539-1444bc39b660)
Meanwhile quest says that it doesn't support fluid crafting at all, and doesn't ask you for fluid hatches
![image](https://github.com/user-attachments/assets/8fee9d4b-c9eb-4248-b1fa-68cd9da4d7fb)
