### ISSUE TITLE
Ash dust recipe conflict

### ISSUE THREAD

**Issue by AX3Lino** [GTNewHorizons/GT-New-Horizons-Modpack#17370]
### Your GTNH Discord Username

AX3Lino

### Your Pack Version

Nightly 651

### Your Proposal

Remove making carbon dust from ash in centrifuge.

### Your Goal

Centrifuging ash dust does have 2 recipes:
1. to carbon dust
![image](https://github.com/user-attachments/assets/5fcfe31f-5d17-4a8d-8a88-5b6c5831816b)
2. to quicklime, potash, magnesia, phosphorus pentoxide, soda ash and banded iron dust
![image](https://github.com/user-attachments/assets/9e2f43ac-2f87-419c-bf80-92dbc22b7f83)

There is no way to force the 2nd.

### Your Vision

Remove ash dust → carbon dust in centrifuge, and move it for example to electrolyser.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by FourIsTheNumber** [comment]
Please use the collision java flag on nightlies, the collision checker is currently disabled: 
-Dgt.recipebuilder.recipe_collision_check=true

**Comment by fbfnysnshnsgnwg** [comment]
this should be marked as a duplicate

**Comment by FourIsTheNumber** [comment]
> this should be marked as a duplicate

If there's an open ticket for this it should be closed, this is fixed even without the flag.
