### ISSUE TITLE
Logistic Pipes bugging inventory render

### ISSUE THREAD

**Issue by Gabrieldor** [GTNewHorizons/GT-New-Horizons-Modpack#17374]
### Your GTNH Discord Username

lanium

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Itens icon on inventory were not supposed to act like they have "shadows" on them

![image](https://github.com/user-attachments/assets/a20df3e6-7213-4087-9346-bb1d6c229cb3)

### The Reality

However If I have some pipes from logistics craft those itens icons get "shadowed"

![image](https://github.com/user-attachments/assets/cf786f6f-d3e7-4c34-a742-8b1486183807)

### Your Proposal

Make itens not get "shadowed" when having logistics pipe in inventory

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Atlantis102** [comment]
probably fixed in this update https://github.com/GTNewHorizons/LogisticsPipes/pull/69
