### ISSUE TITLE
Jet Fuel no3 recipe not working

### ISSUE THREAD

**Issue by noahfusi** [GTNewHorizons/GT-New-Horizons-Modpack#17389]
### Your GTNH Discord Username

k0rregan#9754

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Crafting some jet fuel no3 using this recipe :
![2024-09-20_11 58 31](https://github.com/user-attachments/assets/dc7afce5-eec0-408b-9057-81aaf94189ef)

### The Reality

Large chemical reactor doesn't produce jet fuel no3. No valid recipe found
![2024-09-20_11 57 57](https://github.com/user-attachments/assets/46ed98a7-836a-4235-b039-310f1d9bd21b)
Checked the inputs multiple times : 
![2024-09-20_11 58 23](https://github.com/user-attachments/assets/b7c81760-790c-4d96-ac22-2bbefb1d4117)
![2024-09-20_11 58 21](https://github.com/user-attachments/assets/cf1f7ed7-c27e-4669-a674-ea370193befd)
Tried to change large chemical reactor, rebuild the inputs / outputs, recipe not working

### Your Proposal

Make the recipe working 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
32k < 40k. insufficient ingredient
