### ISSUE TITLE
Bartworks render problem

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#17396]
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.7.0 beta1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Build lapotron capacitor

### The Reality

The bartwork glass render as air block.
HV EV IV glass all like air.

### Your Proposal

fix the texture?
![21a8e0aa90b6997d60c91d9a1e0f3f5e](https://github.com/user-attachments/assets/79da50d3-962b-481c-8a40-4f05b886b2ff)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
Does this still happen in 2.7 beta 2?
Have you tried turning off your resource pack and if yes, have you tried refreshing your textures with f3+t?

**Comment by KamenriderZO** [comment]
Fixed

**Comment by zeyechun** [comment]
I also found this bug in 2.6.1, and even caused the entire block to stop showing
