### ISSUE TITLE
Render

### ISSUE THREAD

**Issue by Miklebe** [GTNewHorizons/GT-New-Horizons-Modpack#17391]
### Your GTNH Discord Username

mike_be

### Your Pack Version

Nightly 647

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Looking up recipe used in a machine and not having problems.

### The Reality

When i open NEI recipe for grade 6 water, each tick it will add extra set of lenses to the recipe, making it laggier and laggier with each second.
UPD: Correction, seems like it affects every NEI recipe, where chance of success increases with volume increase, so:
Water tier 2 (Ozonation)
Water tier 3 (Fllocculation)
Water tier 4 (pH Neutralization)
Water tier 5 (Temperature Fluctuation)
Water tier 6 (Laser pew pew)

https://github.com/user-attachments/assets/e24b9f2f-1885-44cd-b74b-82deb1cf3a1b

Seems to reset when relogging (the first line in nei was from another world)

### Your Proposal

Valve pls fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
Fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/3256
