### ISSUE TITLE
WorldEdit cannot move, copy, replace and/or delete Frame Boxes

### ISSUE THREAD

**Issue by wantayanamirei** [GTNewHorizons/GT-New-Horizons-Modpack#17409]
### Your GTNH Discord Username

wantayanamirei (or contact with me via @evgenwargold)

### Your Pack Version

2.7.0-beta-1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Open To LAN

### Your Expectation

Trying to move Neutron Activator two blocks for the side (because "design"). I can move glass, controller, casings, but not frames.

### The Reality

In the console, you can see a message like "wrong ID: 305; maximum value = 15" (not an accurate record).

### Your Proposal

This makes my life very difficult because I use frame boxes not even in the multiblocks (more like scaffold analog), so it would be great if someone fixed it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
world edit will need a compat with NEID

**Comment by Lyfts** [comment]
Fixed in https://github.com/GTNewHorizons/worldedit-gtnh/pull/9 update WE to https://github.com/GTNewHorizons/worldedit-gtnh/releases/tag/v0.0.7
