### ISSUE TITLE
orevein names in nei are broken

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#17404]
### Your GTNH Discord Username

chochem

### Your Pack Version

2.7.0 beta1

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

the localisation worked before (just default english here)

### The Reality

![image](https://github.com/user-attachments/assets/5fcae90e-eeef-48fe-8398-7961bf9a0ad9)

### Your Proposal

fix it :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
the lang file still seems to be there. I am not sure whats going on.

https://github.com/chochem/VisualProspecting/blob/master/src/main/resources/assets/gregtech/lang/en_US.lang
https://github.com/GTNewHorizons/GT5-Unofficial/blob/7838937a6df4513ac5829f3b81554f51fae9c64a/src/main/java/gtneioreplugin/plugin/gregtech5/PluginGT5VeinStat.java#L96

**Comment by Lyfts** [comment]
Wtf https://github.com/GTNewHorizons/GT5-Unofficial/blob/7838937a6df4513ac5829f3b81554f51fae9c64a/src/main/java/gtneioreplugin/plugin/gregtech5/PluginGT5VeinStat.java#L95-L97, it was using VP to translate it and that was removed recently.
That should either be localized in GT5U or it should use something else entirely.

**Comment by boubou19** [comment]
ah i love random intermod hard deps to do trivial stuff...

**Comment by chochem** [comment]
its not a hard dep. its has vpmodloaded check and a backup alternative. but of course vp is still loaded, the lang file was just nuked.
