### ISSUE TITLE
Make the fortune of  singleblock miner work on raw ores

### ISSUE THREAD

**Issue by missile-toe1** [GTNewHorizons/GT-New-Horizons-Modpack#17407]
### Your Pack Version

2.7.0-beta-1

### Your Proposal

Make the fortune of  singleblock miner work on raw ores

### Your Goal

I hate digging for minerals manually, and I'm sure there are many players who are, but now the by-products of raw ore are reduced(10%→5%)

### Your Vision

This change will allow HV and EV early players to use singleblock miner more comfortably without worrying about less by-products.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by FourIsTheNumber** [comment]
Not working on raw ores is intended. This is a worthwhile sacrifice for automated mining and still very much worth using, we do not need to triple all of the ore outputs.

**Comment by chochem** [comment]
yea that is intended. and was all debated in detail.
