### ISSUE TITLE
Stocking Input Hatch reliably fails on MBF when runs out of certain liquid

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#17400]
### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

My Mega Blast Furnace has 4 liquids inside a Single stocking input hatch. 
Radon, Oxygen, Hydrogen, Nitrogen.

At certain moment I started to run out of Nitrogen in my base. MBF would immediately stop operating with an error "Failed to extract expected amount of fluids from stocking hatch. This can be caused by attaching multiple storage fluid buses to the same tank".

I switched the machine on. One minute later when again not enough Nitrogen it again switches off.
The only workaround is to have enough Nitrogen lol. Of crouse I will reach that point. But whenever any of the hatches on my base runs of certain liquid the machine would stop.

### The Reality

Stopping machines all the time.

### Your Proposal

The machine should not stop all the time it has not enough liquid.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by nikitinalexx** [comment]
Maybe this should help to reproduce. Nitrogen should be constantly going inside the AE and be drained quickly by another machine, other than MBF.

**Comment by kuba6000** [comment]
Fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/2655 (nightly/beta 2.7.0)
