### ISSUE TITLE
Add Alternative Method to Obtain Processed Koboldite 

### ISSUE THREAD

**Issue by SparkedTheorem** [GTNewHorizons/GT-New-Horizons-Modpack#17408]
### Your GTNH Discord Username

SparkedTheorem

### Your Pack Version

2.6.1

### Your Proposal

Koboldite Nuggets should have an alternative way to be obtained rather than just trading, such as a Crucible recipe to turn 4 Koboldite Dust into a Koboldite Nugget and then a Compressor Recipe to turn 9 Koboldite Nuggets into a Koboldite Ingot.

### Your Goal

Koboldite and thus the Pentacle/Statue of Hobgoblin Patron are currently extremely annoying to obtain, as the only method of obtaining processed Koboldite is through trading with Hobgoblins, which is highly subject to RNG.

### Your Vision

This would make Witchery less of a pain in the ass as it would make obtaining a useful item (Pentacle for your Altar) no longer reliant on RNG finally deciding you to give you a Hobgoblin with the Koboldite trade and allow you to better access Mog and Gulg for an even more consistent form of getting processed Koboldite.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment]
Instead of a compressor, since is in the magic area I would use blood magic alchemy ( using less nuggets so less koboldite ) fussing it with other materials, like: 1 mana ingot at the top, 2 koboldite nuggets, and 2 koboldite dusts
