### ISSUE TITLE
Hovering over GT steel crowbar with Shift crashes the game

### ISSUE THREAD

**Issue by Awoogas** [GTNewHorizons/GT-New-Horizons-Modpack#17401]
### Your GTNH Discord Username

awooga

### Your Pack Version

2.7.0-beta-1

### Your Server

Local dedicated

### Java Version

Java 21

### Type of Server

None

### Your Actions

Whenever I press shift and hover over steel crowbar the game crashes on client side.
How to reproduce:
~~0) Open GT Machine(?)~~
~~1) Open inventory~~
~~2) Hold Shift button~~
~~3) Hover over steel crowbar~~

EDIT:
After further inspection the reproduction process is the following:
1) Open *any* GT UI
2) Hold Shift key
3) Hover over *any* GT instrument

### Crash Report

[crash-2024-09-21_10.22.11-client.txt](https://github.com/user-attachments/files/17083272/crash-2024-09-21_10.22.11-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Awoogas** [comment]
Same thing happens when hovering over GT iron wrench, seems like some GT tools are affected in general

**Comment by lailani-f** [comment]
Having the same issue with an Iron Screwdriver. 
Doesn't crash when not inside a GT machine GUI but instead tooltip displays "Unnamed" 
![image](https://github.com/user-attachments/assets/2f941a95-2506-4ded-ab13-8d90590d4de1)
