### ISSUE TITLE
Incomplete Gregtech Ore Processing page and missing furnace recipes.

### ISSUE THREAD

**Issue by Novie53** [GTNewHorizons/GT-New-Horizons-Modpack#17417]
### Your GTNH Discord Username

Quintus#6363

### Your Pack Version

Nightly 662

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Gold Ore, Silver Ore, Iron Ore and Diamond ore all have incomplete/broken Gregtech Ore Processing pages. They, Crushed Gold Ore and Crushed Silver Ore are also missing furnace recipes. 

running with -Dgt.recipebuilder.recipe_collision_check=true

**EDIT: Bug not present in 2.7.0-beta-1!**

![page](https://github.com/user-attachments/assets/f0b1afd7-7469-4257-8b4d-88c465cec347)
![furnace](https://github.com/user-attachments/assets/ae88c54d-0666-4cb4-a092-1245c8336f75)

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
can confirm on a beta1-instance **with updated gt and nhcoremod**
