### ISSUE TITLE
Ore prospecting bug on 2.7

### ISSUE THREAD

**Issue by Chumgod** [GTNewHorizons/GT-New-Horizons-Modpack#17412]
### Your GTNH Discord Username

randompixl

### Your Pack Version

2.7-beta-java_17-21

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

prospect ore; ore shows proper vein on journeymap e.g a salt vein showing as a naquadah/tungsten vein for some reason
![image](https://github.com/user-attachments/assets/a62253a7-f230-4716-9e7c-3d4bb5516a5e)

### The Reality

ore is prospected but wrong vein shows on journeymap

### Your Proposal

fix prospecting as to how it was in earlier versions

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miklebe** [comment]
https://github.com/GTNewHorizons/VisualProspecting/pull/57
Was already fixed, you can download new VisualProspecting jar and replace it on both server and client, will work as intended here: 
https://github.com/GTNewHorizons/VisualProspecting/releases/tag/1.3.23-pre
