### ISSUE TITLE
Crush when interacting with steam machines 

### ISSUE THREAD

**Issue by KostiantynNaumenko** [GTNewHorizons/GT-New-Horizons-Modpack#17426]
### Your GTNH Discord Username

kostya7726

### Your Pack Version

2.7.0-beta-1_Java_17-21

### Your Server

On my PC

### Java Version

Java 21

### Type of Server

None

### Your Actions

Crush appeared few times when I was opening the inventory of steam machies 

### Crash Report

https://mclo.gs/5pJsMCI

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment]
Duplicated of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17401
