### ISSUE TITLE
Tainted Magic Fork is outdated??

### ISSUE THREAD

**Issue by Shahelion** [GTNewHorizons/GT-New-Horizons-Modpack#17436]
### Your Pack Version

N/A

### Your Proposal

I noticed that the GTNH fork of Tainted Magic is based on an old version of the mod. In version 8.0, a lot of things were changed or improved. Perhaps take a look and possibly integrate into the GTNH fork?

### Your Goal

It looks like CurseForge has the latest version, 8.1.1.

### Your Vision

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
a lot of the changes were not well liked and were incompatible with gtnh

**Comment by Shahelion** [comment]
Fair enough. I mainly noticed it because the GTNH fork is a lower version number, so it keeps printing the message in chat about there being an update available.
