### ISSUE TITLE
[2.7.0 BETA-1] Certain quests complete automatically due to OR being added to a quest with optional tasks.

### ISSUE THREAD

**Issue by NotWhiteRice** [GTNewHorizons/GT-New-Horizons-Modpack#17435]
### Your GTNH Discord Username

notwhiterice

### Your Pack Version

2.7.0-beta-1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

I had opened my GoG run in the new version and didn't expect anything out of the ordinary

### The Reality

The tool forge quest completed automatically, presumably due to an OR condition being added to the optional task of getting all the materials to make one.

### Your Proposal

Remove the OR condition from the tool forge quest and any others that have optional tasks. I haven't gotten too far through the questbook, so the tool forge quest is the only one that procced for me but there might be others.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/17437
