### ISSUE TITLE
Weird Pam's Harvest crop recipe

### ISSUE THREAD

**Issue by XeonKA** [GTNewHorizons/GT-New-Horizons-Modpack#17433]
### Your GTNH Discord Username

 XeonKA

### Your Pack Version

2.7.0 beta1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

.

### The Reality

![image](https://github.com/user-attachments/assets/0be61043-1f0c-40db-a057-a29f60f7c037)
Other Pam's HarverstCraft also have this recipe.
Also found in single player.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by XeonKA** [comment]
nightly#676 still have this issue.

**Comment by FourIsTheNumber** [comment]
Yeah this is an old oredict thing built into pam's, not a bug and not new

**Comment by Dream-Master** [comment]
we have source from pams so we can fix it i guess?
