### ISSUE TITLE
2.7.0-beta1 Twilight forest portal generator quest has bugged firefly

### ISSUE THREAD

**Issue by luisantonioa** [GTNewHorizons/GT-New-Horizons-Modpack#17440]
### Your GTNH Discord Username

agelian

### Your Pack Version

2.7.0-beta1

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Tried to complete quest to get TF portal gem But the firefly is of the type I can get anymore.
The fireflies I have work with the sticks quest but not this one.

![image](https://github.com/user-attachments/assets/787851de-7c80-4d11-b40a-6a6396890160)

### The Reality

Nothing happened since I cannot complete the quest

### Your Proposal

Adjust the quest so it uses the same firefly as the sticks quest.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
are you sure you are on the beta? this was fixed a month ago

**Comment by luisantonioa** [comment]
I updated when it came out will double check

**Comment by luisantonioa** [comment]
I have this file in my mods.. did a diff check with with the 2.7.0-beta1 zip

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/2.7.0-beta-1/config/betterquesting/DefaultQuests/Quests/NoviceThaumaturg-AAAAAAAAAAAAAAAAAAAAFg%3D%3D/StuckintheTwilig-AAAAAAAAAAAAAAAAAAAFWA%3D%3D.json

Is there another place to look?

**Comment by luisantonioa** [comment]
I can see the firefly is different in the sticks quest

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/2.7.0-beta-1/config/betterquesting/DefaultQuests/Quests/NoviceThaumaturg-AAAAAAAAAAAAAAAAAAAAFg%3D%3D/LowonSticks-AAAAAAAAAAAAAAAAAAAHLg%3D%3D.json#L53

**Comment by chochem** [comment]
ah there is a second quests
