### ISSUE TITLE
 got another version of AE2 seeds in beta1

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#17442]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.7.0 beta1

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

no item change when updating versions

### The Reality

let me call the 2 versions: seed-old seed-new
when u upgrade to 2.7.0 beta1. all the AE2 seeds in recipes gets changed to seed-new, which makes seed-old not craft-able.

### Your Proposal

the only effect is that u need to change 4-6 pattern, not too big of a deal. just put this here in case someone wanna fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by yothersm** [comment]
This also appears to break the "Purifying the Impure" quest in the quest book, which asks for 32 of each of the AE2 seeds (presumably the seed-old version).

**Comment by chochem** [comment]
the reports are confusing.
testing it shows the recipe is unchanged. people are claiming that ae2 patterns are corrupted though.

**Comment by chochem** [comment]
item output went from `<appliedenergistics2:item.ItemCrystalSeed:1200>.withTag({progress: 1200})` to just `<appliedenergistics2:item.ItemCrystalSeed:1200>`

**Comment by Ruling-0** [comment]
This is not just a one-off change from 2.6.1>2.7. My pattern, which I had previously fixed using shift click from NEI, broke again (Nightly 646). This time, the PrAss was producing item `<appliedenergistics2:item.ItemCrystalSeed:1200>.withTag({progress: 1200})` while shift-clicking the pattern from NEI was `<appliedenergistics2:item.ItemCrystalSeed:1200>`.

This sounds like some race condition during startup, as I've definitely had this back and forth happen a couple times now, but only ever with server restarts between instances.

**Comment by DarkRecent** [comment]
I had same problem fixed it by wiping all seed related stuff from the ae2 storage like old crafting and old seeds gone to trash
I gave the same advice to some on in the help chat https://discord.com/channels/181078474394566657/234936569360809996/1298411403207643191
the person told me it worked 
![image](https://github.com/user-attachments/assets/04d0114a-68a1-4c21-8b3b-b7f1999065f6)
so I belive nei or ae2 pulling old seed data from the storage of ae2 for some reason but not sure
