### ISSUE TITLE
 Redesign the form of all blockie multies

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#17458]
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.7.0 nightlys

### Your Proposal

Now that some block form multis are gone / deprecated, I think is time to change the shape of some multies that are very cubic or doesnt have any interesting shape

- [ ] Wire Factory
- [ ] Cutting Factory
- [ ] Utupu-Tanuri
- [ ] Zyngen
- [ ] Volcanus?
- [ ] Cryogenic Freezer?
- [ ] Industrial Extrusion Machine
- [ ] Industrial Sledgehammer
- [ ] Industrial Electrolizer
- [ ] Industrial Material Press
- [ ] Industrial Mixing Machine
- [ ] High Current Industrial Arc Furnace
- [ ] Large Thermal Refinery
- [ ] Maceration Stack
- [ ] Industrial 3D Copying Machine
- [ ] Boldarnator
- [ ] ... devs add what any more you want ( is just for clarifing the "block shape" ones)

### Your Goal

Be in corcondancy with all the new good looking multies

### Your Vision

Have interesting builds and adding some bonusses to the new multies so we dont need to spam a ton of same looking machines

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by NotAPenguin0** [comment]
What is your plan to preserve compatibility for bases between versions

**Comment by EnderProyects** [comment]
Same plan as all the other deprecated multiblocks in the past, add a tag that is marked for deprecation, and make that you can form the old and the new shape for some versions ( one or two) until the complete removal of the old one

**Comment by chochem** [comment]
thats sounds like a terrible idea. Just breaking every base for no reason.

this can happen once we switch to mutes.

**Comment by FourIsTheNumber** [comment]
Not at all worth the damage for aesthetic reasons. If these multis are replaced due to MuTEs or some other reason, we can consider new structures.

**Comment by EnderProyects** [comment]
They are going to be replaced anyway, it can be done in the 2.8.0 or in two years when Mutes come to be a usefull thing

**Comment by Dream-Master** [comment]
> thats sounds like a terrible idea. Just breaking every base for no reason.
> 
> this can happen once we switch to mutes.

maybe 2.8.0 have mutes

**Comment by boubou19** [comment]
even if we have mutes, we need a proper plan, and MuTEs will probably warrant a 3.0. In any case, it's not a suggestion that will be worked on a ticket. I'm closing this, the discussion will happen naturally anyways.
