### ISSUE TITLE
Lumber axe didn't work on mahogany trees

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#17457]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.7 Beta 1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

The lumber axe should be able to fell all trees completely (as long as you have enough durability or it's unbreakable)
It seems to work but not for mahogany trees whatever why

I noticed that and got some other proof here:
https://discord.com/channels/181078474394566657/181078474394566657/1288496146892980249

### The Reality

It doesn't work

### Your Proposal

Make mahagony trees be able to fell completely with lumber axe again (maybe there are some other trees as well)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Awoogas** [comment]
Can confirm, it owrks only partially on mahogany trees.
In addition - it doesn't work on slime trees as well (Leaves stay while the tree is gone until you break one block of leaves manually)
