### ISSUE TITLE
Iron saw blade recipe doesn't show up in NEI search

### ISSUE THREAD

**Issue by Virunas** [GTNewHorizons/GT-New-Horizons-Modpack#17466]
### Your GTNH Discord Username

@Virunas, im in the discord

### Your Pack Version

2.6.1

### Your Server

mc.virunas.com

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

search Nei for an iron saw blade

### The Reality

Doesn't show up but others do if i remove iron
https://i.imgur.com/FAlH423.png

### Your Proposal

add the recipe there.

my friend says Gregtech mod saw blades don't show up in nei so maybe make them?

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
probably just hidden because someone wanted to minimize how much is shown in nei. try the materials page for iron

**Comment by Virunas** [comment]
Any idea how I could get them to show up for my client/server? It would be better if the blades that are currently shown were hidden and vice versa.
