### ISSUE TITLE
Steam separator hatch

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#17471]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.7 Beta 1

### Your Proposal

The steam seperator needs an output hatch but there are recipes like sticky resin -> raw rubber dust where you maybe just wanna make the multiblock to make the rubber dust faster and just void the fluid but you can't build the multiblock without the output hatch (ulv) and that would need minimum rubber before
Maybe it could be considered to not have the need of using an output hatch (so you can just void the fluid) or at least maybe have a output hatch (steam) to make it really viable in steam area

### Your Goal

Make the machine more "usable"? Not sure how to describe it

### Your Vision

In best case the steam separator don't need an output hatch at all for forming the multiblock, getting a steam output hatch or even both

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by NotAPenguin0** [comment]
It seems fine to me to gate fluid outputs to LV instead of steam age, the multiblocks are already extremely powerful and I don't think they should be made much stronger.

**Comment by Wyrmlet** [comment]
While gating fluid outputs for multis is fine, this also causes the steam water pump to be inaccessible until you're firmly in LV. Maybe shuffle around quests to make it apparent that this is the case?
