### ISSUE TITLE
Using the newest Tinkers Construct crashes the game during the mod loading phase.

### ISSUE THREAD

**Issue by mainrs** [GTNewHorizons/GT-New-Horizons-Modpack#17473]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

I used the newest TiC version `1.12.10` that included a patch I PR'd. While the game is loading all mods, I get a NPE that originates in Tinker-Defense; an error occurred during item registration.

Just to keep track of this somewhere.

### Crash Report

https://mclo.gs/pACXnxY

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
2.6.1 is old. better try in the beta
