### ISSUE TITLE
Vein names differ between prospecting and NEI Vein Stats Page. In new nightly Ores not shown anymore

### ISSUE THREAD

**Issue by Novie53** [GTNewHorizons/GT-New-Horizons-Modpack#17477]
### Your GTNH Discord Username

Quintus#6363

### Your Pack Version

beta-1 with updated mods: visualprospecting-1.3.23-pre, gregtech-5.09.50.12

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

The name of Overworld veins differ between NEI Page and journeymap/chat log

Prospecting Name   -   NEI Page
Chalcopyrite   -   Copper
Graphite   -   Diamond
Brown Limonite   -   Iron
Kyanite   -   Mica

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@chochem i guess this was fixed ?

**Comment by Dream-Master** [comment]
Update:
I dont see any ore on Journeymap with nightly 673. https://github.com/GTNewHorizons/DreamAssemblerXXL/actions/runs/11063768271
They not get displayed when i use a scanner or mine a new ore.

**Comment by chochem** [comment]
> @chochem i guess this was fixed ?

no. I just reinstated the lang to be used by gt nei ore plugin. VP is not using that (anymore). I dont know why vp was moved away from the lang but that should probably be reverted yea.

> Update:
I dont see any ore on Journeymap with nightly 673. https://github.com/GTNewHorizons/DreamAssemblerXXL/actions/runs/11063768271
They not get displayed when i use a scanner or mine a new ore.

That sounds like a way bigger and separate issue :P

**Comment by Lyfts** [comment]
I'll write up another way to get the correct vein name while still using the localized ore names to present it.

There's no point in using the vein name when it's not being localized in GT5U like all the ores are. If someone decides to add a new vein at some point they would have to remember that it should be localized in GT5NEIthingy so that it and VP can use it which makes no sense.

**Comment by chochem** [comment]
feel free to move it back to VP, it sounds like you changed your mind on that since last week.

GT sounds fine though because that is also where the vein is defined.
