### ISSUE TITLE
Game crashes to main menu when hovering over items in my inventory

### ISSUE THREAD

**Issue by NotWhiteRice** [GTNewHorizons/GT-New-Horizons-Modpack#17478]
### Your GTNH Discord Username

notwhiterice

### Your Pack Version

2.7.0-beta-1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

This crash had happened three times so far, all of which were moving items from my inventory and a machine, but it was all different machines and there was nothing specific about each case that caught my eye other than my mouse being over the item in my inventory.

I had just gotten a thaumometer and scanned all my items, so maybe it had to do with that, but the last time I crashed I was certain I hadn't even had my finger on the shift key and was just hovering over the item normally and the other times I had been rushing very quickly to move items between places and at least one of the first two crashes had all the aspects being shown.

The first crash was moving copper dust from my inventory into a steam furnace (I wasn't paying too much attention so idk if I was holding shift at the time I crashed but I was moving the dusts very quickly and could've easily been holding shift whole hovering over the dusts), the second was moving some wrought iron dust into my EBF (I had my finger on the shift key when I crashed since I remember seeing the aspects), and the third was moving the copper ingots into a wiremill (my hand wasn't near my shift key and I hadn't gotten around to actually clicking on the item, so it wasn't trying to display the aspects in the item and I only just now decided to scan them so nothing would be rendered)

### Crash Report

https://mclo.gs/TBKBnnP

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
duplicate and already fixed

**Comment by chochem** [comment]
see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17401
