### ISSUE TITLE
Server crashes when I open EBF's controller GUI

### ISSUE THREAD

**Issue by Awoogas** [GTNewHorizons/GT-New-Horizons-Modpack#17479]
### Your GTNH Discord Username

awooga

### Your Pack Version

2.7-nightly-672

### Your Server

Local dedicated

### Java Version

Java 21

### Type of Server

None

### Your Actions

Simply open EBF controller, game crashes.

### Crash Report

[crash-2024-09-26_20.01.23-server.txt](https://github.com/user-attachments/files/17155384/crash-2024-09-26_20.01.23-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment]
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17470
