### ISSUE TITLE
AE2 sometimes cant withdraw or put liquid in storage

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#17476]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.7.0-beta-1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Put/withdraw liquid anytime

### The Reality

You just cant put or withdraw liquid. You can see in terminal, but cant do anything. Need replace controller or energy for fix.

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
anyway to reproduce?

**Comment by lordIcocain** [comment]
idk how reproduce, but i have subnet which get broken after while.
