### ISSUE TITLE
Placing an Eye of Harmony voids power

### ISSUE THREAD

**Issue by IncandescenceSy** [GTNewHorizons/GT-New-Horizons-Modpack#17485]
### Your GTNH Discord Username

envoidia

### Your Pack Version

2.7.0 Nightly 631

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Placed down an Eye of Harmony controller block. Expected it to only consume power for recipes

### The Reality

Placing an Eye of Harmony controller block immediately voids a large chunk of power every time, This power does not appear to be stored inside the controller, and it will not use it for recipes. For instance, I could have something in the realm of 10^18 EU stored, place an EoH, and then it won't turn on because it needs 7.48*10^17 EU to start, and I suddenly only have around 10^17

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment]
I can't reproduce this, are you certain that nothing else in your base is utilising power? Can you try this in a test world as well?

**Comment by serenibyss** [comment]
This may be similar to an LSC issue I fixed recently, where it only happened in multiplayer if:
- The placer is already part of a wireless net, and
- The placer is not the owner of the wireless net

See https://github.com/GTNewHorizons/GT5-Unofficial/pull/3078

**Comment by IncandescenceSy** [comment]
Yeah, its probably the same root cause as that LSC bug, which would make it multiplayer-only. I just placed another EoH controller and it went even worse than ever before -- the buffer instantly dropped from 3.30*10^19 to 0 the moment i placed it. There is absolutely nothing in the base that could use this much power,

**Comment by IncandescenceSy** [comment]
The wireless voiding issue appears to have been greatly exacerbated as of late, for unknown reasons. Now it regularly voids all power on its own.
I used a command to set power to 10^54, looked away for 30 seconds, our power is 10^16 now.
TPM is off (and couldn't use anywhere near that much power anyway), EoHs didnt start (and also couldnt use anywhere near that much power), nothing in the entire base could come even close to using that much.
The entire wireless net is literally just regularly voiding somehow, making the game entirely unplayable in the process.

I have no idea how you would even begin to debug this, the only thing I feel somewhat confident in is that it's a multiplayer bug and almost certainly won't happen in singleplayer

**Comment by IncandescenceSy** [comment]
I think I discovered the problem. Some of our EoHs weren't chunkloaded, and it appears that EoH controllers void power not only when placed, but also when first loaded (I would assume this happens on server restart as well). This presumably only occurs in multiplayer when the EoH is owned by someone that does not own the wireless network, similar to the LSC voiding bug
