### ISSUE TITLE
Black hole multi didnt check only fluid recipe without circuit in crib

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#17483]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.7.0-beta-1

### Your Server

ps

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Order eternal singularity, put black hole seed, multi doing craft.

### The Reality

nothing happen until i set ghost circuit

### Your Proposal

idk

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
![image](https://github.com/user-attachments/assets/76c2a699-27ec-4021-ac5b-77fb0867427d)
what's wrong with that?

**Comment by lordIcocain** [comment]
i set circuit 1 and its start work, also it making super dense without any circuit

**Comment by miaowwwwww** [comment]
then "crafting without the correct circuit" is the problem, right?

**Comment by lordIcocain** [comment]
seems like, with 20 circuit still doing neutronium compressor recipe.
