### ISSUE TITLE
cover placed on frames lose render when moving away and come back.

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#17498]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.7.0 beta1

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

no render bugs

### The Reality

![image](https://github.com/user-attachments/assets/94708bbe-e075-483d-86a0-a96b234559b7)
looking good, now leave until frame out of render
![image](https://github.com/user-attachments/assets/942d25b2-4a80-4b77-b25a-bbafe98546f0)
![image](https://github.com/user-attachments/assets/165dd7fb-337c-467c-9e25-1a15f98cbe97)
and now come back
![image](https://github.com/user-attachments/assets/8f8aa1cc-d8e0-4244-858c-53f78e4b2892)
![image](https://github.com/user-attachments/assets/934acd1c-323d-47ff-8a1b-7a105bf59067)
the cover is still there, just not rendered well.

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment]
@miaowwwwww can you check with new nightly i will add later ?

**Comment by miaowwwwww** [comment]
which one, build 675?

**Comment by Dream-Master** [comment]
> which one, build 675?

no i make a new one. Will be 676 i guess

**Comment by chochem** [comment]
@NotAPenguin0 are you looking into issues regarding the new frames?

**Comment by NotAPenguin0** [comment]
I think this should also fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3578, if it's not please reopen this.
