### ISSUE TITLE
crashing to desktop

### ISSUE THREAD

**Issue by LeviSimioni** [GTNewHorizons/GT-New-Horizons-Modpack#17493]
### Your GTNH Discord Username

_ null_ _ (without the spaces)

### Your Pack Version

2.7.0-BETA-1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

https://youtu.be/byR7OchgaP8
The game Crashes on startup 

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/17172021/fml-client-latest.log)
[fml-junk-earlystartup.log](https://github.com/user-attachments/files/17172022/fml-junk-earlystartup.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
sounds like some corrupted config file. I would reinstall or at least redo the config folder.

**Comment by LeviSimioni** [comment]
its works for my thanks
