### ISSUE TITLE
2.7 issue: nether ores drop only one raw ore, resulting in half the yield after macerating compared to 2.6

### ISSUE THREAD

**Issue by Patrick-Fiedler** [GTNewHorizons/GT-New-Horizons-Modpack#17490]
### Your GTNH Discord Username

paddijaddi

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

- in 2.7 mining ores drops 1 (without fortune) of the new "raw ore"type
- macerating normal overworld ores (both 2.6 and 2.7 versions) gives 2 crushed ore
- macerating v2.6 nether ores gives 4 crushed ore
-> mining nether ores in 2.7 should drop either the v2.6 nether ore or  2 v2.7 raw ores so the ratios stay the same

### The Reality

mining v2.7 nether ores will only drop 1 raw ore
->nether ore yield is essentially halfed

### Your Proposal

nether ores should drop 2 raw ores (plus fortune bonus) so yield is like it used to be

a discord used suggested this might also be the case with end ores, wich i have not checked yet (I am mid LV so not much experience in this pack)

Edit: I just tested it again (sadly I only have tools infused with luck so sometimes i do get multiple drops...) but sometimes I definetly get only 1 raw ore from a nether ore

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
Nether and end ores drop double the amount of raw ore in comparison to stone ore.
