### ISSUE TITLE
AE2 cables render bug

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#17507]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.7.0 build 676

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

no weird looking render

### The Reality

![image](https://github.com/user-attachments/assets/4fb35ef8-7a55-4201-81ee-cbf2568842a7)
looking good, now place a new cable
![image](https://github.com/user-attachments/assets/1714892c-538d-4d73-aaf6-7f2d3619101e)
or another place
![image](https://github.com/user-attachments/assets/41ff1149-a6b0-4390-bdf4-4cfb38e5e4c2)
just visual
![image](https://github.com/user-attachments/assets/5b5fe2d4-ee1e-4fd9-9764-45259cc7d840)
i was facing south if anyone need the info
### Your Proposal

make proper visuals

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by querns** [comment]
I also experience this on 674 nightly and with different cables (covered regular, covered dense.)

![image](https://github.com/user-attachments/assets/24ef4b3e-0cba-4327-a3cf-943129bdbc0f)

**Comment by Alexdoru** [comment]
I can reproduce this by doing the following in the full pack : https://cdn.discordapp.com/attachments/224191655375273985/1296646795333468261/AE2_Cable_bug.mp4?ex=67130bee&is=6711ba6e&hm=8fc348d78084c2c360e8b9cdf56e035af57890c1a2f3d650925c77dad6b85429&

the bug is present with or without angelica, however I can't reproduce it in ae2 dev env

**Comment by Alexdoru** [comment]
this bug was introduced in nightly 668 by upgrading malicious doors from `malisisdoors-1.16.4-GTNH` to `malisisdoors-1.17.1-GTNH.jar`

**Comment by Alexdoru** [comment]
I'll try to look into it
