### ISSUE TITLE
Catalyst carriers being (produced?) by chemical plant

### ISSUE THREAD

**Issue by Spicydduck** [GTNewHorizons/GT-New-Horizons-Modpack#17516]
### Your GTNH Discord Username

spicy_duck

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Produce nitrobenzene on a chemical plant with titanium casings, HV machine casings, and steel pipe casings on breakthrough circuit number 12. 

### The Reality

Nitrobenzene is produces as expected however at the start of every recipe, one GT++ Catalyst carrier is found in the output bus. Over time, more are produced until the bus fills up. This does not cause the error of no item output space.
![image](https://github.com/user-attachments/assets/ca4683f5-9465-4a26-8bcf-a30ea5854557)

### Your Proposal

Not make the chemical plant produce catalyst carriers out of thin air.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Can confirm this issue on up to nightly 645. Does it for many different recipes, not just nitro

**Comment by Reflex18** [comment]
The chemical plant has always created empty catalyst carriers when the full ones are consumed.
However, it should give the error of a full output spot and only void them when set to voiding mode.

**Comment by FourIsTheNumber** [comment]
> The chemical plant has always created empty catalyst carriers when the full ones are consumed. However, it should give the error of a full output spot and only void them when set to voiding mode.

No, you are not understanding. It generates empty catalyst carriers randomly, not when catalysts are consumed (even on recipes that don't use catalysts. It makes literally thousands of them and they clog up the output.

**Comment by chochem** [comment]
that was literally the first bug the chem plant ever had but was fixed 4 years ago. (https://github.com/alkcorp/GTplusplus/issues/710)
nice to see that someone broke it again XD
