### ISSUE TITLE
Bug with Zirconium Ingot/Dust

### ISSUE THREAD

**Issue by Darkmaxsas** [GTNewHorizons/GT-New-Horizons-Modpack#17522]
### Your GTNH Discord Username

Darkmaxsas

### Your Pack Version

2.7.0-beta2

### Your Server

private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

having all my ressources still there after updating from 2.6.1 to 2.7.0

### The Reality

all my zirconium dust and ingots got converted to _NULL Ingot and _NULL Dust.
The Quest for Zirconium also shows _NULL Ingot
![image](https://github.com/user-attachments/assets/0f0e5717-a32d-4b5c-a7f7-9be9324954c4)

after looking through NEI, Zirconium still exists and is obtainable, only my existing stash got converted.
![image](https://github.com/user-attachments/assets/9c0cfe67-13ba-423e-aefa-b50e69a3c4fa)

### Your Proposal

Fix pls :D

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Closed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3306
