### ISSUE TITLE
Galaxy space ores do not process normally

### ISSUE THREAD

**Issue by CookieBrigade** [GTNewHorizons/GT-New-Horizons-Modpack#17527]
### Your GTNH Discord Username

bucketbrigade

### Your Pack Version

Nightly 674

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Galaxyspace ores process like any other ore
![image](https://github.com/user-attachments/assets/c3b16051-a33c-4d31-aced-ce7f6c0c901f)

### The Reality

Galaxy space ores only process if the equivilant gt ore was processed before hand.

### Your Proposal

Have it process normally

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
the recipe looks fine. its specifically different based on what the previous recipe was.
Almost certainly a bug in the recipe check code.

**Comment by chochem** [comment]
also super important for shadow ore. but might affect all kinds of stuff.

**Comment by Ngar1** [comment]
Galaxy ores are not able to macerate - may be a relative problem?

![grafik](https://github.com/user-attachments/assets/96417c28-51e5-45a7-8380-f2d36659e0ce)

**Comment by FourIsTheNumber** [comment]
> Galaxy ores are not able to macerate - may be a relative problem?

Already fixed by linked pr.
