### ISSUE TITLE
infinite spray can not working with altered keybindings

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#17528]
### Your Pack Version

2.7.0-beta-2

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

the infinite spray can does not work if you change your "use item" keybinding

![image](https://github.com/user-attachments/assets/dbb53328-3cd9-4c6d-ba24-60694dbfd2eb)

### The Reality

.

### Your Proposal

can you make it work with inverted mouse buttons?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ruling-0** [comment]
Should be fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3431

**Comment by Ruling-0** [comment]
Closed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3431
