### ISSUE TITLE
Quest change

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#17520]
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.7 Beta 1

### Your Proposal

The quest "Silicon Wafer" in the MV tab here:
![image](https://github.com/user-attachments/assets/3d2924f2-d002-4b81-9aa2-f1fa378ceb46)
It says it will need the MV cutting machine and the text says that this would be the best but it isn't required so I would say it would better to make the MV cutting machine optional instead of a retrieval task

### Your Goal

Making the questbook better

### Your Vision

Make the quest fit better cause you didn't need it but it's recommended so changing it to optional seems good for me

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Miklebe** [comment]
But then it would be required for both of those quests. 
![image](https://github.com/user-attachments/assets/bb4ae9a6-9ed9-49ad-a09e-ca201ef5ed0e)
Even if boule can be cut in LV machine, all the engraved wafers still need MV cutting machines. It is _optional_ till you get to the next 2 quests, where it's mandatory, but it's more clean to add the requirment to the intersection of those 2 quests, rather then in both of them.

**Comment by chochem** [comment]
looks like its fine as is
