### ISSUE TITLE
Remove NEI duplicate machine recipe tabs

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#17533]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

GTNH 2.7.0 beta 2

### Your Proposal

In NEI, for some recipes there is duplicate tabs such as a "centrifuge tab" and a "mutliblock centrifuge tab" I suggest removing the multiblock centrifuge tab, it just adds clutter in NEI

![image](https://github.com/user-attachments/assets/dfaaf4da-6d33-4cdb-aa8f-b44c4fa4e288)

### Your Goal

remove clutter in NEI

### Your Vision

make NEI easier to browse

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Yamnasm** [comment]
Some GT multiblocks have some recipe changes which could be the case for the Centrifuge (though I have no specific example).

**Comment by Ethryan** [comment]
Look at sulfuric acid in the LCR for a good example.

**Comment by Alexdoru** [comment]
Right, the recipe maps are not exactly the same
