### ISSUE TITLE
GT‘s Vibrant Alloy can't bending

### ISSUE THREAD

**Issue by XeonKA** [GTNewHorizons/GT-New-Horizons-Modpack#17538]
### Your GTNH Discord Username

XeonKA

### Your Pack Version

2.7.0 beta2

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

![QQ20241001-215208](https://github.com/user-attachments/assets/3127651e-f937-4af6-9b61-60e72be0bc7d)

### The Reality

GT’s alloy didn't work,Ender IO's works well.
![image](https://github.com/user-attachments/assets/22456e41-93e7-4645-b0d8-04da0c1f71f9)

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by XeonKA** [comment]
Might be related to #17530

**Comment by chochem** [comment]
tested a bunch and seems to be fixed by https://github.com/GTNewHorizons/EnderIO/pull/175
