### ISSUE TITLE
Molecular transformer recipes seems to be gone

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#17531]
### Your GTNH Discord Username

Alexdoru

### Your Pack Version

GTNH 2.7.0 beta 2

### Your Server

solo

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

find molecular transformer recipes such as carbon dust -> graphene dust

### The Reality

they seem to be missing

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment]
I don't think you can craft carbon directly into graphene?

**Comment by chochem** [comment]
pretty ironic ticket. it looks to me like you yourself broke into advanced solar panels and deleted everything XD
<https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/964>
