### ISSUE TITLE
Nether causing black screen crashes; have to force pc to turn off. Possible corrupt world??

### ISSUE THREAD

**Issue by dima970234** [GTNewHorizons/GT-New-Horizons-Modpack#17547]
### Your GTNH Discord Username

Dima

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Actions

I was exploring the nether and looking for quarts, i started digging down with the ore finder wand in hand, instant black screen. No alt tabbing, alt f4-ing, ctrl alt deleting works to fix. So, I force my computer to turn off, turn it back on, start up the world again and it works for a few minutes before it crashes exactly the same way. This last time however, it crashed and now it won't let me in my world. It gave me a crash report though.  I forgot to mention, I have 11 gb of ram dedicated (any less and I get crashes and stutters in random spots, but no big deal)

### Crash Report

[crash-2024-10-01_20.51.08-server (GTNH).txt](https://github.com/user-attachments/files/17219541/crash-2024-10-01_20.51.08-server.GTNH.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by dagger8243** [comment]
are u using curseforge

**Comment by dima970234** [comment]
> are u using curseforge

No, technic launcher. Sorry, forgot to include that

**Comment by dima970234** [comment]
Edit: the black screening was a loose cable on my graphics card, upon further research, world is corrupt. Glad it happened early  in my playthrough and not 800 hours in.
