### ISSUE TITLE
Cant Launch

### ISSUE THREAD

**Issue by Ughass** [GTNewHorizons/GT-New-Horizons-Modpack#17559]
### Your GTNH Discord Username

whatthekcjr1

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

All I did was download the 2.6.1 modpack and dragged it into the MultiMC launcher and tried to start up the game

### Crash Report

MultiMC version: 0.7.0-3863

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [2620:1ec:bdf::46, 13.107.246.46]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::46, 13.107.246.46]

api.mojang.com resolves to:
    [2620:1ec:bdf::46, 13.107.246.46]

Minecraft folder is:
C:/MultiMC/instances/GT_New_Horizons_2.6.1_Java_8 (1)/.minecraft

Java path is:
C:/Program Files/Common Files/Oracle/Java/javapath/javaw.exe

Checking Java version...
Java is version 17.0.10, using 64-bit architecture, from Oracle Corporation.

Main Class:
  net.minecraft.launchwrapper.Launch

Native path:
  C:/MultiMC/instances/GT_New_Horizons_2.6.1_Java_8 (1)/natives

Libraries:
  C:/MultiMC/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar
  C:/MultiMC/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl/2.9.4-nightly-20150209/lwjgl-2.9.4-nightly-20150209.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.4-nightly-20150209/lwjgl_util-2.9.4-nightly-20150209.jar
  C:/MultiMC/libraries/com/mojang/netty/1.8.8/netty-1.8.8.jar
  C:/MultiMC/libraries/com/mojang/realms/1.3.5/realms-1.3.5.jar
  C:/MultiMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/MultiMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/MultiMC/libraries/java3d/vecmath/1.3.1/vecmath-1.3.1.jar
  C:/MultiMC/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar
  C:/MultiMC/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar
  C:/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/4.5/jopt-simple-4.5.jar
  C:/MultiMC/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar
  C:/MultiMC/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar
  C:/MultiMC/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar
  C:/MultiMC/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar
  C:/MultiMC/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar
  C:/MultiMC/libraries/io/netty/netty-all/4.0.10.Final/netty-all-4.0.10.Final.jar
  C:/MultiMC/libraries/com/google/guava/guava/17.0/guava-17.0.jar
  C:/MultiMC/libraries/org/apache/commons/commons-lang3/3.3.2/commons-lang3-3.3.2.jar
  C:/MultiMC/libraries/commons-io/commons-io/2.4/commons-io-2.4.jar
  C:/MultiMC/libraries/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
  C:/MultiMC/libraries/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
  C:/MultiMC/libraries/com/mojang/authlib/1.5.21/authlib-1.5.21.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  C:/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
  C:/MultiMC/libraries/tv/twitch/twitch/5.16/twitch-5.16.jar
  C:/MultiMC/libraries/net/minecraftforge/forge/1.7.10-10.13.4.1614-1.7.10/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
  C:/MultiMC/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar
  C:/MultiMC/libraries/org/ow2/asm/asm-all/5.0.3/asm-all-5.0.3.jar
  C:/MultiMC/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar
  C:/MultiMC/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar
  C:/MultiMC/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar
  C:/MultiMC/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar
  C:/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar
  C:/MultiMC/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar
  C:/MultiMC/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar
  C:/MultiMC/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar
  C:/MultiMC/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar
  C:/MultiMC/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar
  C:/MultiMC/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar
  C:/MultiMC/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar
  C:/MultiMC/libraries/com/mojang/minecraft/1.7.10/minecraft-1.7.10-client.jar

Native libraries:
  C:/MultiMC/libraries/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar
  C:/MultiMC/libraries/org/lwjgl/lwjgl/lwjgl-platform/2.9.4-nightly-20150209/lwjgl-platform-2.9.4-nightly-20150209-natives-windows.jar
  C:/MultiMC/libraries/tv/twitch/twitch-platform/5.16/twitch-platform-5.16-natives-windows-64.jar
  C:/MultiMC/libraries/tv/twitch/twitch-external-platform/4.5/twitch-external-platform-4.5-natives-windows-64.jar

Mods:
  [✔️] +unimixins-all-1.7.10-0.1.17.jar
  [✔️] AdvancedSolarPanel-1.7.10-3.5.1a.jar
  [✔️] adventurebackpack-1.1.4-GTNH.jar
  [✔️] ae2fc-1.2.29-gtnh.jar
  [✔️] ae2stuff-0.7.0-GTNH.jar
  [✔️] AFSU-1.3.0-GTNH.jar
  [✔️] alchgrate-1.1.0-GTNH.jar
  [✔️] amazingtrophies-1.2.1.jar
  [✔️] AmunRa-GC-0.5.1.jar
  [✔️] angelica-1.0.0-alpha50.jar
  [✔️] AngerMod-0.7.1.jar
  [✔️] AppleCore-3.3.0.jar
  [✔️] appliedenergistics2-rv3-beta-357-GTNH.jar
  [✔️] archaicfix-0.7.2.jar
  [✔️] ArchitectureCraft-1.9.5.jar
  [✔️] Aroma1997Core-1.7.10-1.0.2.16.jar
  [✔️] AromaBackup-1.7.10-0.1.0.0.jar
  [✔️] AsieLib-0.5.5.jar
  [✔️] Automagy-1.7.10-0.28.2.jar
  [✔️] Avaritia-1.49.jar
  [✔️] Avaritiaddons-1.7.1-GTNH.jar
  [✔️] backpack-2.3.1-GTNH.jar
  [✔️] bartworks-0.9.26.jar
  [✔️] battlegear2-1.3.8.jar
  [✔️] Baubles-1.0.4.jar
  [✔️] bdlib-1.10.0-GTNH.jar
  [✔️] beebetteratbees-0.4.0-GTNH.jar
  [✔️] BetterAchievements-0.2.0.jar
  [✔️] BetterBuildersWands-0.11.1-GTNH.jar
  [✔️] bettercrashes-1.4.0-GTNH.jar
  [✔️] betterloadingscreen-1.6.1-GTNH.jar
  [✔️] betterp2p-1.2.1.jar
  [✔️] BetterQuesting-3.5.15-GTNH.jar
  [✔️] BiblioCraft[v1.11.7][MC1.7.10].jar
  [✔️] BiblioWoods[BiomesOPlenty][v1.9].jar
  [✔️] BiblioWoods[Forestry][v1.7].jar
  [✔️] BiblioWoods[Natura][v1.5].jar
  [✔️] binnie-mods-2.3.4.jar
  [✔️] BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar
  [✔️] BlockLimiter-0.6.0.jar
  [✔️] blockrenderer6343-1.2.8.jar
  [✔️] BloodArsenal-1.3.2.jar
  [✔️] BloodMagic-1.5.4.jar
  [✔️] Botania-1.10.13-GTNH.jar
  [✔️] BotanicHorizons-1.1.2-GTNH.jar
  [✔️] BrandonsCore-1.1.0-GTNH.jar
  [✔️] bugtorch-1.2.13-GTNH.jar
  [✔️] buildcraft-7.1.39.jar
  [✔️] buildcraft-compat-7.1.17.jar
  [✔️] BuildCraftOilTweak-1.1.1.jar
  [✔️] CarpentersBlocks-3.5.5-GTNH.jar
  [✔️] catwalks-2.2.2-GTNH.jar
  [✔️] chisel-2.14.1-GTNH.jar
  [✔️] chiseltones-1.1.0-GTNH.jar
  [✔️] CodeChickenCore-1.2.1.jar
  [✔️] CodeChickenLib-1.2.1.jar
  [✔️] CoFHCore-[1.7.10]3.1.4-329.jar
  [✔️] CompactKineticGenerators-1.7.10-1.0.jar
  [✔️] Computronics-1.7.4-GTNH.jar
  [✔️] controlling-2.0.2.jar
  [✔️] CookingForBlockheads-1.3.4-GTNH.jar
  [✔️] CoreTweaks-1.7.10-0.3.3.2+nomixin.jar
  [✔️] CraftPresence-2.3.9-1.7.10.jar
  [✔️] CraftTweaker-3.3.1.jar
  [✔️] creativecore-1.4.0-GTNH.jar
  [✔️] CropLoadCore-0.2.0.jar
  [✔️] CropsPP-1.6.5.jar
  [✔️] custommainmenu-1.11.3.jar
  [✔️] defaultkeys-1.2.0.jar
  [✔️] defaultserverlist-1.5.0.jar
  [✔️] defaultworldgenerator-0.3.0.jar
  [✔️] Draconic-Evolution-1.3.5-GTNH.jar
  [✔️] DummyCore-1.18.0.jar
  [✔️] duradisplay-1.2.3.jar
  [✔️] EMT-1.4.7.jar
  [✔️] endercore-0.4.6.jar
  [✔️] EnderIO-2.7.6.jar
  [✔️] EnderStorage-1.5.2.jar
  [✔️] EnderZoo-1.1.0.jar
  [✔️] EnhancedLootBags-1.1.1.jar
  [✔️] eternalsingularity-1.2.1.jar
  [✔️] extrautilities-1.2.13a.jar
  [✔️] findit-1.2.5.jar
  [✔️] FloodLights-1.3.0.jar
  [✔️] Forbidden.Magic-0.7.0-GTNH.jar
  [✔️] Forestry-4.8.10.jar
  [✔️] forgelin-1.9.9-GTNH.jar
  [✔️] ForgeMultipart-1.4.8.jar
  [✔️] ForgeRelocation-0.1.2.jar
  [✔️] ForgeRelocationFMP-0.1.0.jar
  [✔️] gadomancy-1.3.2.jar
  [✔️] galacticgreg-1.1.0.jar
  [✔️] Galacticraft-3.1.5-GTNH.jar
  [✔️] GalaxySpace-1.1.84-GTNH.jar
  [✔️] gendustry-1.7.2-GTNH.jar
  [✔️] ggfab-0.3.19.jar
  [✔️] GoodGenerator-0.8.24.jar
  [✔️] GraviSuite-1.7.10-2.0.3.jar
  [✔️] gravisuiteneo-1.1.6.jar
  [✔️] gregtech-5.09.45.168.jar
  [✔️] GT.Scanner.Mod-1.8.0.jar
  [✔️] gtneioreplugin-1.2.0.jar
  [✔️] GTNewHorizonsCoreMod-2.3.54.jar
  [✔️] gtnhintergalactic-1.3.4.jar
  [✔️] gtnhlanth-0.12.13.jar
  [✔️] gtnhlib-0.2.11.jar
  [✔️] GTNH-TC-Wands-1.4.0.jar
  [✔️] GT-PlusPlus-1.11.63.jar
  [✔️] GTTweaker-2.1.0.jar
  [✔️] HardcoreDarkness-MC1.7.10-1.7.jar
  [✔️] HardcoreEnderExpansion-1.10.1-GTNH.jar
  [✔️] harvestcraft-1.1.11-GTNH.jar
  [✔️] Healer-1.2.1.jar
  [✔️] HelpFixer-1.2.0.jar
  [✔️] hodgepodge-2.5.5.jar
  [✔️] holoinventory-2.4.10-GTNH.jar
  [✔️] HungerOverhaul-1.7.10-1.0.0.jenkins104.jar
  [✔️] hydroenergy-1.2.2.jar
  [✔️] IC2 Crop Plugin Version 1.7.10-1.3.1.jar
  [✔️] IC2NuclearControl-2.6.2.jar
  [✔️] ifu-1.10.2.jar
  [✔️] IguanaTweaksTConstruct-2.4.1.jar
  [✔️] industrialcraft-2-2.2.828a-experimental.jar
  [✔️] InfernalMobs-1.8.1-GTNH.jar
  [✔️] InGameInfoXML-2.8.8.jar
  [✔️] INpureCore-1.2.0-GTNH.jar
  [✔️] inventorytweaks-1.6.2.jar
  [✔️] IronChest-6.0.85.jar
  [✔️] IronChestMinecarts-1.1.0.jar
  [✔️] irontanks-1.3.0.jar
  [✔️] JABBA-1.3.5.jar
  [✔️] journeymap-1.7.10-5.2.3-fairplay.jar
  [✔️] kekztech-0.10.6.jar
  [✔️] kubatech-0.14.9.jar
  [✔️] littletiles-1.3.0-GTNH.jar
  [✔️] logisticspipes-1.1.14-GTNH.jar
  [✔️] lootgames-2.1.1.jar
  [✔️] LunatriusCore-1.2.0-GTNH.jar
  [✔️] magicbees-2.7.16-GTNH.jar
  [✔️] malisisdoors-1.16.4-GTNH.jar
  [✔️] Mantle-0.4.1.jar
  [✔️] mobsinfo-0.2.6-GTNH.jar
  [✔️] ModTweaker2-0.11.0.jar
  [✔️] modularui-1.1.43.jar
  [✔️] MouseTweaks-2.4.17-GTNH.jar
  [✔️] MrTJPCore-1.1.7.jar
  [✔️] mxrandom-0.3.0.jar
  [✔️] Natura-2.6.4.jar
  [✔️] naturescompass-1.4.0-GTNH.jar
  [✔️] NEIAddons-1.15.0.jar
  [✔️] NEICustomDiagram-1.5.17.jar
  [✔️] NEIIntegration-1.4.0.jar
  [✔️] netherportalfix-1.2.0.jar
  [✔️] NodalMechanics-1.2.1-GTNH.jar
  [✔️] NotEnoughEnergistics-1.5.2.jar
  [✔️] notenoughIDs-2.0.3.jar
  [✔️] NotEnoughItems-2.5.28-GTNH.jar
  [✔️] nutrition-0.0.10.jar
  [✔️] oauth-1.2.2-GTNH.jar
  [✔️] OpenBlocks-1.9.1-GTNH.jar
  [✔️] OpenComputers-1.10.11-GTNH.jar
  [✔️] OpenGlasses-1.5.0-GTNH.jar
  [✔️] OpenModsLibs-0.10.9.jar
  [✔️] OpenModularTurrets-2.3.2.jar
  [✔️] openprinter-0.2.0-GTNH.jar
  [📁] OpenSecurity (folder)
  [✔️] opensecurity-1.1.1-GTNH.jar
  [✔️] Opis-1.4.2-mapless.jar
  [✔️] overloadedarmorbar-1.1.0.jar
  [✔️] Pam's Harvest the Nether 1.7.10a.jar
  [✔️] personalspace-1.0.30.jar
  [✔️] PlayerAPI-1.4.4.jar
  [✔️] ProjectBlue-1.2.0-GTNH.jar
  [✔️] ProjRed-4.9.5-GTNH.jar
  [✔️] Railcraft-9.15.8.jar
  [✔️] RandomThings-2.5.3.jar
  [✔️] RemoteIO-2.5.2.jar
  [✔️] roguelike-1.6.0-GTNH.jar
  [✔️] RWG-alpha-1.5.0.jar
  [✔️] Schematica-1.11.1-GTNH.jar
  [✔️] ServerUtilities-2.0.38.jar
  [✔️] SGCraft-1.4.4-GTNH.jar
  [✔️] sharewhereiam-2.1.1.jar
  [✔️] sleepingbag-0.2.1.jar
  [✔️] SpecialMobs-3.5.0.jar
  [✔️] SpiceOfLife-2.1.7-carrot.jar
  [✔️] StevesAddons-0.12.3.jar
  [✔️] StevesCarts-2.1.1.jar
  [✔️] StevesFactoryManager-1.2.3-GTNH.jar
  [✔️] StorageDrawers-1.13.5-GTNH.jar
  [✔️] StorageDrawersBop-1.12.0-GTNH.jar
  [✔️] StorageDrawersForestry-1.12.0-GTNH.jar
  [✔️] StorageDrawersMisc-1.12.0-GTNH.jar
  [✔️] StorageDrawersNatura-1.12.0-GTNH.jar
  [✔️] structurecompat-0.5.1.jar
  [✔️] structurelib-1.3.1.jar
  [✔️] Supersolarpanel-1.1.3.jar
  [✔️] SuperTic-1.3.0.jar
  [✔️] Tainted-Magic-7.6.8-GTNH.jar
  [✔️] tcinventoryscan-1.1.4-GTNH.jar
  [✔️] tcneiadditions-1.3.6.jar
  [✔️] tcnodetracker-1.2.0.jar
  [✔️] TConstruct-1.11.16-GTNH.jar
  [✔️] TecTech-5.3.47.jar
  [✔️] TGregworks-1.7.10-GTNH-1.0.26.jar
  [✔️] Thaumcraft-1.7.10-4.2.3.5a.jar
  [✔️] Thaumcraft4Tweaks-1.5.23-beta.1.jar
  [✔️] ThaumcraftMobAspects-1.1.0-GTNH.jar
  [✔️] thaumcraftneiplugin-1.7.10-1.7a.jar
  [✔️] ThaumcraftResearchTweaks-1.1.0.jar
  [✔️] Thaumic Machina-1.7.10-0.2.1.jar
  [✔️] Thaumic-Based-1.6.7.jar
  [✔️] thaumicboots-1.2.3.jar
  [✔️] thaumicenergistics-1.6.10-GTNH.jar
  [✔️] Thaumic-Exploration-1.2.7-GTNH.jar
  [✔️] ThaumicHorizons-1.5.4.jar
  [✔️] thaumicinsurgence-0.3.1.jar
  [✔️] ThaumicTinkerer-2.9.4.jar
  [✔️] TiCTooltips-1.3.1.jar
  [✔️] tinkersdefense-1.2.2.jar
  [✔️] TMechworks-0.3.1.jar
  [✔️] TooMuchLoot-4.2.0-GTNH.jar
  [✔️] torohealth-1.1.0.jar
  [✔️] Translocator-1.2.1.jar
  [✔️] TravellersGear-1.7.10-1.16.6.jar
  [✔️] travellersgearneo-1.2.0.jar
  [✔️] TwilightForest-2.5.25.jar
  [✔️] txloader-1.7.0.jar
  [✔️] Universal-Singularities-8.7.0.jar
  [✔️] visualprospecting-1.2.11.jar
  [✔️] Waila-1.7.3.jar
  [✔️] WailaHarvestability-1.2.1-GTNH.jar
  [✔️] WAILAPlugins-0.4.0.jar
  [✔️] WanionLib-1.9.0.jar
  [✔️] WarpTheory-1.3.7-GTNH.jar
  [✔️] Wawla-1.2.1-GTNH.jar
  [✔️] WirelessCraftingTerminal-1.11.2.jar
  [✔️] witchery-1.7.10-0.24.1.jar
  [✔️] WitcheryExtras-1.2.2.jar
  [✔️] WitchingGadgets-1.4.4-GTNH.jar
  [✔️] WR-CBE-1.5.0.jar
  [✔️] YAMCore-0.6.0.jar
  [✔️] Ztones-1.7.10-2.2.2.jar

Params:
  --username Gaypotato5 --version 1.7.10 --gameDir C:/MultiMC/instances/GT_New_Horizons_2.6.1_Java_8 (1)/.minecraft --assetsDir C:/MultiMC/assets --assetIndex 1.7.10 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userProperties {} --userType msa --tweakClass cpw.mods.fml.common.launcher.FMLTweaker

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1792m, -Xmx3072m, -Duser.language=en]

Minecraft process ID: 3292

Using onesix launcher.

Failed to start Minecraft:
java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 03 Oct 2024 12:55:45 +0900

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Miklebe** [comment]
Why are you using Java 8 modpack version with Java 17?
You either download modpack for modern java version and follow installation guide (will require a bit more than just dropping it into the MMC), or download and install (or actually just set path) to Java 8 installation.
https://gtnh.miraheze.org/wiki/Installing_and_Migrating

**Comment by Ughass** [comment]
I downloaded the [GT_New_Horizons_2.6.1_Java_8.zip] one so I figured that java 8 would work

**Comment by dagger8243** [comment]
if u downloaded the java 8 .zip then use java 8, its trying to use java 17 to launch the java 8 .zip which just wont work

**Comment by dagger8243** [comment]
get the java 17 .zip and try again please

**Comment by Ughass** [comment]
Just did and im getting the error message again am I not using java 8 or something? Ig Ill try and get java 17
