### ISSUE TITLE
Reduce required number of casing for new extractor multi.

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#17551]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.7.0-beta-2

### Your Proposal

Currently extractor cant form with 8 energy hatch 1 maintanance and 2 IO hatchs.
<img width="635" alt="image" src="https://github.com/user-attachments/assets/848830e1-b153-44c6-855f-9030c3bf0033">

### Your Goal

Able use multi with 8 energy.

### Your Vision

Need reduce required casings to 22.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Reflex18** [comment]
When has eight energy hatches ever worked on a mutliblock and allowed double overclocking?

**Comment by StaffiX** [comment]
Ever since wireless energy hatches was added.
Those kind of energy hatches have massive buffer, which is the main reason regular ones don't really work,

**Comment by Reflex18** [comment]
> Ever since wireless energy hatches was added. Those kind of energy hatches have massive buffer, which is the main reason regular ones don't really work,

Since 16 amps = two tiers of power then this would have no issues working on assembly lines and chemical plants.

Buffer of power doesn't mather since the input is being met.

**Comment by Nockyx** [comment]
> When has eight energy hatches ever worked on a mutliblock and allowed double overclocking?

it is common practice in endgame to 8 hatch most multis, getting max+1 in umv or max+2 in uxv makes a lot of difference, even more with the removal of PA

**Comment by lordIcocain** [comment]
> but what recipe exactly is important in the extractor multiblock? my uxv base has 0 of them currently

seaweed extract

**Comment by LazyFleshWasTaken** [comment]
> > but what recipe exactly is important in the extractor multiblock? my uxv base has 0 of them currently
> 
> seaweed extract

qft it

**Comment by lordIcocain** [comment]
> qft it

qft make both, extract and seaweed, so i put seaween in extractor for extra extract
