### ISSUE TITLE
Inexplicable Level Maintainer Erroring

### ISSUE THREAD

**Issue by IncandescenceSy** [GTNewHorizons/GT-New-Horizons-Modpack#17560]
### Your GTNH Discord Username

envoidia

### Your Pack Version

Nightly 631

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Use a level maintainer to level maintain something

### The Reality

The level maintainer errors everything I try to put into it no matter what, for no apparent reason, despite all of the needed resources and patterns being present. They used to work, but at some point they stopped. They might still work for others on my server; I know someone else said their teammate had this issue, but they did not (it wasn't a security terminal, it was consistent across all subnets). It's also seemingly not always all items -- I saw someone else say that it only inexplicably errored for some specific items, and others worked fine

### Your Proposal

Make level maintainers actually work. Probably also make them show the reason for erroring, as that would make it much easier to track down the cause of the bug

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ruling-0** [comment]
I did not personally experience this, but I had a friend where they experienced the described error (every single craft would fail). This was not a security card issue - I had them build a full network from scratch, and it still errored for them while it worked fine for me. This eventually fixed but I have no idea why.

**Comment by boubou19** [comment]
probably AE2 failing to reserve blocks for the craft, like items seen twice.

**Comment by IncandescenceSy** [comment]
I tried to level maintain 1 bronze ingot (I have the resources to make easily many billions) and it instantly failed. There's no way it couldn't reserve enough for 1 bronze ingot

**Comment by Ruling-0** [comment]
The tiny test network we had was two storage busses onto drawers, one with infinite gravel and the other empty, a neutronium energy cell, a molecular assembler + interface with a pattern for gravel to flint, a terminal, crafting storage, and the aforementioned level maintainer. We tried with and without security terminal and it didn't matter - my friend could not set flint to be maintained, but I could. There is 0 reason the network should fail that craft.

As context, both of us were also op'd and the server runs locally on my machine.

**Comment by jdlovins** [comment]
I'm also running into this on beta2. Existing level maintainers seem to work but adding anything new is not playing nice. It also seems to be caching the maintain amount / batch size which is not something I've seen previously (or remembered). I'm playing on a server with 1 other friend and neither of us can actually set anything to be maintained. We've tried this on main net and subnet but it instant fails either way.

**Comment by tomasz-brak** [comment]
Im also expirencing this issue, i can manually craft molten neodymium but a crafting card or a level maintainer fail to start the craft

**Comment by jdlovins** [comment]
I was seemingly able to solve this on beta2. I previously had given subnets full access to main due to filtering being bad and not fun to use. I know in the beta that has been fixed so i went ahead and filtered the subnet to only have access to what it should have, not blanket extract. I specifically did this on subnets that had a level maintainer / cpus, not all of mine do. This seemingly fixed my level maintainers and they now all work across the board, even for friends on the server. I need to do more testing to really see if that is the fix but it worked for me.

Maybe some issue with the new storage bus filtering?

**Comment by hiroscho** [comment]
I can't reproduce this with Ruling-0's described setup. Anyone got a save where this is consistently broken?

**Comment by jdlovins** [comment]
Hmm I made a new server using the backup I made prior to updating to beta2 and it is not happening on this installation which is really weird.

**Comment by IncandescenceSy** [comment]
After several weeks of never working, my level maintainers magically started working again. I didn't change anything related to them, it just happened on its own, which brings more questions than answers

**Comment by Kyramesh** [comment]
I started having this issue after updating 2.6.1 to 2.7. beta 3. All my old maintainer setups work, but any new ones immidiatly fail without apparent reason. Going by the other comments: Is it possible that the system does not recoginze me as the owner after updating? I also loaded a backup 10 minutes after starting the new instance, so this could also be the issue instead.

**Comment by Kyramesh** [comment]
a way to reproduce this bug / workaround:
if you click the item in the interface it looks like this
![grafik](https://github.com/user-attachments/assets/c8141aca-37c1-48ce-b9c8-dfea55d6fc17)
I can set the values to whatever i want and it will always fail now. But if i shift click it in there it looks like this
![grafik](https://github.com/user-attachments/assets/99627752-fa01-473b-b4b4-b67f9dce7bbd)
and it'll work like normal.

**Comment by NyrZ** [comment]
Also having the same issue on nightly 712. @Kyramesh work around is working for me too

Playing on locally hosted server

**Comment by bluhbipo** [comment]
having this same issue on beta 3, out of all of my previously working level maintainers pre updating (both fluids and items alike), specifically neutronium rods and resplendant/exotic catalyst now instafail despite being able to queue regularily.

after some testing of various setups i also managed to get a "phantom" maintainer craft where exotic will just queue itself despite not being in a maintainer anywhere

shift clicking did not solve my issue, updating to latest ae2fc did not solve it either

**Comment by Kyramesh** [comment]
You can try to pull in (drag and drop) a fake NEI item instead of something from your inventory. That also works for me.

**Comment by XeonKA** [comment]
RC2 still have this issue

**Comment by tazgoth2305** [comment]
2.7.4 you need to specify the correct amount of resources for it to start working.
