### ISSUE TITLE
Volume slider to machines

### ISSUE THREAD

**Issue by fishaxe** [GTNewHorizons/GT-New-Horizons-Modpack#17561]
### Your GTNH Discord Username

fishaxe

### Your Pack Version

2.6.1 - 2.7.0

### Your Proposal

Machines and multiblocks should have a volume slider, or a way to alter volume seperate from the Blocks section

### Your Goal

As it stands the machine sounds are far too loud compared to the current sounds in the "block" section, and i would like to be able to hear machine sounds alongside block breaking and placing sounds without being deafened by the machine sounds. I understand mufflers exist, but I still like hearing the cool sounds the machines make, it's just hard when they are so loud, and I would prefer if we could still hear sounds like block breaking and placing

### Your Vision

Being able to hear the cool new sounds while not being deafened and still being able to hear other sounds associated with the "Blocks" section in the sound settings would be a nice addition to the pack

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Lyfts** [comment]
https://www.curseforge.com/minecraft/mc-mods/extreme-sound-muffler-legacy :)

**Comment by fishaxe** [comment]
That solves that issue then I suppose! Haha. Thanks for the link, wasn't aware of this mod :D

**Comment by fishaxe** [comment]
While I'm here, is there a way to remove muffler upgrades from existing machines? Or do they require a recraft to get an unmuffled version?

**Comment by AbdielKavash** [comment]
> While I'm here, is there a way to remove muffler upgrades from existing machines? Or do they require a recraft to get an unmuffled version?

The Name Remover should be able to do it. Think of it as a "factory reset" for anything you throw in.

**Comment by LazyFleshWasTaken** [comment]
> > While I'm here, is there a way to remove muffler upgrades from existing machines? Or do they require a recraft to get an unmuffled version?
> 
> The Name Remover should be able to do it. Think of it as a "factory reset" for anything you throw in.

Does it also remove the circuit lock on the Cal?

**Comment by AbdielKavash** [comment]
> > > While I'm here, is there a way to remove muffler upgrades from existing machines? Or do they require a recraft to get an unmuffled version?
> > 
> > 
> > The Name Remover should be able to do it. Think of it as a "factory reset" for anything you throw in.
> 
> Does it also remove the circuit lock on the Cal?

If it does I would consider that a bug. I haven't tried.

**Comment by Yamnasm** [comment]
> While I'm here, is there a way to remove muffler upgrades from existing machines? Or do they require a recraft to get an unmuffled version?

> The Name Remover should be able to do it. Think of it as a "factory reset" for anything you throw in.

Name remover does not remove the Muffler Upgrade (video below). As far as I am aware of, nothing does.


https://github.com/user-attachments/assets/c679341e-90e8-4403-b38a-1d2369a1758a

Issue closed due to initial suggestion being resolved (to the satisfaction of author).
