### ISSUE TITLE
Breaking crop matron with pickaxe gives IC2 Teleporter

### ISSUE THREAD

**Issue by NyrZ** [GTNewHorizons/GT-New-Horizons-Modpack#17563]
### Your GTNH Discord Username

nyrz

### Your Pack Version

2.7 beta 2

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Breaking Crop Matron with pickaxe should give IC2 machine hull

### The Reality

gives an IC2 teleporter which if broken gives an IC2 extreme heat exchanger, breaking extreme heat exchanger gives back the IC2 Teleporter

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
Its not just the crop matron, other uncraftable machines drop it too or drop the liquid heat exchanger
![2024-10-04_19 47 50](https://github.com/user-attachments/assets/97286600-504d-4383-bae7-27784a6eda74)
![2024-10-04_19 48 05](https://github.com/user-attachments/assets/ec5d7db3-92ee-4b73-a598-4a2d7b2ab9da)
