### ISSUE TITLE
Advanced Blocking Mode (still) does not work with fluids without a subnetwork discretizer

### ISSUE THREAD

**Issue by PeterKlimk** [GTNewHorizons/GT-New-Horizons-Modpack#17584]
### Your GTNH Discord Username

poltergeist1305

### Your Pack Version

2.6.1 and 2.7 Beta 2

### Your Server

Tested on Private Server / SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

I have a trivial ae2 network that is attached to a trivial subnetwork. The subnetwork has a single fluid storage bus attached to a supertank.

![image](https://github.com/user-attachments/assets/f17fece9-cd5e-4dc4-bd2d-3d7be1da1996)

I have a test recipe that pushes a fluid into the subnetwork. I have advanced blocking mode set up, and thus it shouldn't push fluids into the network if there's a fluid in the tank already.

- Blocking mode is enabled
- The interior interface has an advanced blocking card
- The fluid storage bus is in bi-directional mode

This setup works when I instead have a storage bus and use item-based recipes. I expect that when fluids are in the tank, it doesn't push any new fluids into the subnetwork when I order a recipe.

### The Reality

Blocking mode does not work and fluids are pushed into the subnetwork despite there being existing fluids.

Adding a fluid discretizer to the subnetwork resolves the issue.

https://github.com/user-attachments/assets/22966347-7fa2-4615-9c40-71ff760c4931

### Your Proposal

Make it more clear that the advanced blocking card requires a discretizer on the subnetwork to work properly with fluids, or have it work without one.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment]
It seems to break only when the main net interface is a interface part or an interface block without explicit target. For example this configuration works perfectly
![config](https://github.com/user-attachments/assets/f88632db-acfe-4653-b2ca-a5a73988d814)
