### ISSUE TITLE
Crash when I enter my world

### ISSUE THREAD

**Issue by LeviSimioni** [GTNewHorizons/GT-New-Horizons-Modpack#17585]
### Your GTNH Discord Username

_null__

### Your Pack Version

2.7.0-BETA-2

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

As soon as I enter my world it is an unknown error and I can no longer enter. Watch the video to understand better

Please help me, I don't know what I should do

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/17273877/fml-client-latest.log)
[2024-10-07-7.log](https://github.com/user-attachments/files/17273895/2024-10-07-7.log)
https://youtu.be/B97mpOIveq0
[crash-2024-10-07_03.05.52-server.txt](https://github.com/user-attachments/files/17274013/crash-2024-10-07_03.05.52-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Miklebe** [comment]
![image](https://github.com/user-attachments/assets/29f28aa4-e4d7-44cb-be4f-55bf2d71bdc8)
TileEntityOres error is the usual message saying your world got corrupted. Try loading the backup.

**Comment by LeviSimioni** [comment]
Yay thank you so much it worked now you are a genius

**Comment by ravenu11** [comment]
same probem hapened to me when i was exploring twilight forest

I have no idea how to load the backup please help
