### ISSUE TITLE
Molecular Transformer missing recipe

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#17595]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.7.0 beta2

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

at least Graphene should be in there, i don;t remember the others.

### The Reality

![4bd9cd2e656e0dcc882f3a3d8c30a974](https://github.com/user-attachments/assets/6eeb9b39-f06a-408a-a784-2ef97f4ef2c8)
![ce2992335c977778831fbaa20f9cf3b8](https://github.com/user-attachments/assets/29117fb8-953e-48c3-ad7b-0c5eecd9bb3c)
![097d6b8fb57fbf1ec3a070871f080a31](https://github.com/user-attachments/assets/fdd1305f-aac4-439d-a3a9-1d5ec3f5d54a)
only glowstone left

### Your Proposal

at least Graphene should be in there,

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Fixed already by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3327
