### ISSUE TITLE
Server Utilities Unclaim all Chunks in Nether not Working

### ISSUE THREAD

**Issue by Ced1999** [GTNewHorizons/GT-New-Horizons-Modpack#17599]
### Your GTNH Discord Username

ced0115

### Your Pack Version

2.7.0 beta 2

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Unclaim all chunks in nether Button should work

### The Reality

![image](https://github.com/user-attachments/assets/841681e9-63e1-4488-aab9-bfdbbace27d7)
It only shows unknown command

### Your Proposal

Make it work properly again

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
Turn on the chunks command in config
