### ISSUE TITLE
Log spamming when opening a AE terminal & can't pattern certain recipes from NEI

### ISSUE THREAD

**Issue by Quaerere-Git** [GTNewHorizons/GT-New-Horizons-Modpack#17608]
### Your Pack Version

2.7.0 Beta-2 (with world migrated from 2.4.0)

### Your Server

SP

### Java Version

Java 19

### Type of Server

None

### Your Expectation

No so many error message when playing, and all pattern can be encoded instantly after clicking the "+" button

### The Reality

![image](https://github.com/user-attachments/assets/08c87979-6fab-4090-9ab4-6c420fcec81a)
The game keeps spamming messages like 
```
[Client thread/ERROR] [NotEnoughItems]: Exception filtering 0x@22 with codechicken.nei.ItemList$PatternItemFilter@[Random hexadecimal string]
java.lang.ArrayIndexOutOfBoundsException
```
Also, for certain recipes nothing happens after clicking "+" button, even for identical output.

### Your Proposal

Fix it or at least let me know why do these happen

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by slprime** [comment]
1. spam because you have broken items in AE. Strange, you definitely have a version 2.6.39-GTNH of NEI?
2. Need an example of which recipe is not added and in which terminal
