### ISSUE TITLE
playtime counter can't tell when player is AFK

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#17606]
### Your Pack Version

2.7.0 beta2

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

see how much time i activly play and how much i afk

### The Reality

![image](https://github.com/user-attachments/assets/8eda647f-ddcb-40ce-be4a-861b273423ea)
![image](https://github.com/user-attachments/assets/16af396d-8be1-4364-bb0e-8af10f59f300)
![image](https://github.com/user-attachments/assets/91f58e95-cf5f-4bdf-9530-5e2ecfe490c7)

pretty sure i have left the game open running for at least 2h without interacting with the game multiple times, i'd expect to have 100h afk by now

### Your Proposal

fix it or remove the afk-non-afk stats

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
Do you have the afk timer turned on in config?
