### ISSUE TITLE
Can not craft UMV energy hatch 

### ISSUE THREAD

**Issue by Koishi255** [GTNewHorizons/GT-New-Horizons-Modpack#17607]
### Your GTNH Discord Username

Chieri#4235

### Your Pack Version

GTNH 2.7.0 Nightly build 2024-10-10+693

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Trying to craft umv energy hatch,use the nei recipe.

### The Reality

No valid recipe found,with countless checks.
![image](https://github.com/user-attachments/assets/59bee940-310b-4a43-8403-2f89ece2b79f)
![image](https://github.com/user-attachments/assets/e59bbdfa-b7a1-4c62-a142-962616bec3a7)
![image](https://github.com/user-attachments/assets/2a575c1a-181e-42e6-9c1b-763b2411b7ab)

### Your Proposal

fix this recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by aminbahrehmnd** [comment]
### ``

**Comment by lordIcocain** [comment]
Probably because using traditional circuit. So its related to bug where AL not accept traditional circuit, it want only Any circuit.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3397
