### ISSUE TITLE
Removal of the molecular transformer mutliblock and reinstatement of the singleblock

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#17616]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

Nightly 644

### Your Proposal

I propose that the gt ++ Molecular transformer mutliblock should be depreciated from the pack.

### Your Goal

The mutliblock is made to be slow as it only has one energy hatch allowed with slow recipes. Despite this it is a rather large mutliblock that is expensive and tiered to luv.

It also comes with tiered casings within it but there is no way to use those to improve the mutliblock making it appear to be imcomplete.

This mutliblock has also recently had various recipes removed from it so that it only creates sunnarium now.

![image](https://github.com/user-attachments/assets/366eb675-e7cb-4115-be2c-f56e39dae26a)

### Your Vision

Not everything in the pack needs to be an expensive mutliblock if there is no additional complexity with said mutliblock. If it amounts to just input item and output new item then it can be served in a singleblock.

This is one such mutliblock where the entire purpose of it is to simpliy the creation of materials at this tier of the game. A common state in gregtech progression. However unlike other examples of machine mechanics this mutliblock is simply worse to use in every way then the standard methods.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by FourIsTheNumber** [comment]
The removed recipes were a bug that is already fixed. I don't see why we would want to remove a multiblock and gt integration instead of just buffing it.

**Comment by Reflex18** [comment]
> The removed recipes were a bug that is already fixed. I don't see why we would want to remove a multiblock and gt integration instead of just buffing it.

That is good to hear that it was only a bug. The reason for a removal rather then a rebalance is that the original singleblock allowed for unlimited energy input so it scaled well with the player. So to match the original it would need to allow for tec tec hatches and function accordingly to consume that power.

I do not think that will happen.

**Comment by chochem** [comment]
recipes are fixed. And reverting to the single with unlimited power and no tiering is not gonna happen.
