### ISSUE TITLE
AAL Machine Crash

### ISSUE THREAD

**Issue by StaffiX** [GTNewHorizons/GT-New-Horizons-Modpack#17613]
### Your GTNH Discord Username

StaffiX

### Your Pack Version

Modified Nightly 631

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

AAL going back to "No Valid Recipe"

### The Reality

AAL Crashes with these steps:
- Connect 2 AALs to the same subnet 
- Powerfail one of them while they're running recipes
- stop the input for AALs or let the other AAL finish the craft
- empty the subnet (might not be necessary) so there is no items left
- turn on the powerfailed AAL, now it keeps crashing whenever it forms, not even replacing the controller or laser hatches fixes this
![image](https://github.com/user-attachments/assets/7df7d36c-f677-45c0-9eb6-2c38fc75b1aa)
The way to fix this is to make the AAL run a valid recipe again.

### Your Proposal

Fix AAL so it properly resets the machine state.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment]
logs please

**Comment by StaffiX** [comment]
[latest.log](https://github.com/user-attachments/files/17366833/latest.log)
[GregTech.log](https://github.com/user-attachments/files/17366835/GregTech.log)
[fml-client-latest.log](https://github.com/user-attachments/files/17366837/fml-client-latest.log)

This only happens with stocking bus on autopull mode, regular stocking bus behaves normally.
