### ISSUE TITLE
Stone brick masonry variants textures lost with microblock saw

### ISSUE THREAD

**Issue by Hannes-Keunen** [GTNewHorizons/GT-New-Horizons-Modpack#17628]
### Your GTNH Discord Username

Hannes-Keunen

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Tried to cut microblocks from chiseled stone bricks (masonry variants) using an iron saw from forge microblocks

### The Reality

The texture got lost
![Screenshot 2024-10-13 165258](https://github.com/user-attachments/assets/408d12a7-cd93-483e-b89c-448eecc6b317)
![Screenshot 2024-10-13 165357](https://github.com/user-attachments/assets/6f82071d-fcd3-4d36-a006-aa1b09d76d2d)

### Your Proposal

Make the texture not disappear

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Yamnasm** [comment]
I was able to reproduce this issue in Nightly Build 730, though I also found 116 other blocks that shared the same issue. 

Because of the massively expanded scope the bug, I've created a new issue with all the faulty textures listed:.

New issue:
[#17937 ](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17937)
