### ISSUE TITLE
Add Unformed Fluorophlogopite recipe in QFT

### ISSUE THREAD

**Issue by dimazha** [GTNewHorizons/GT-New-Horizons-Modpack#17621]
### Your GTNH Discord Username

Dart_Voider

### Your Pack Version

2.6.1

### Your Proposal

Replace Polystyrene with Unformed Fluorophlogopite in QFT recipe

### Your Goal

Fluorophlogopite is needed for coils through whole pack and this is the only line that you have to use even after QFT (if you do not want to mine Mica). Polystyrene is needed only for Bio Labs so it's useless after UV.

### Your Vision

It will standartize Fluorophlogopite crafting, make it similar to other high-tier polymer crafts, and remove useless output from recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by serenibyss** [comment]
I don't think that this should be added, coils already require some unique setups for gathering raw rubber etc that are not over-scaled like other QFT products and I don't think they need later alternative recipes
