### ISSUE TITLE
GT++ stuff was not fixed

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17623]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.7.0 beta 2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

All according https://github.com/GTNewHorizons/GT5-Unofficial/pull/3119

### The Reality

1) Barite (Ra) ore and some dusts names are reset.
![2024-10-12_20 08 14](https://github.com/user-attachments/assets/10399068-5a82-4044-8cb4-d2a71ae081b3)
2) Charge pack and energy core names are still [MAX], not [UHV].
![2024-10-12_20 08 23](https://github.com/user-attachments/assets/9714d70f-1563-40fc-beed-f8d4233b61af)
![2024-10-12_20 08 25](https://github.com/user-attachments/assets/4bf7a853-2591-4aaa-a6fa-7f769e10d023)

### Your Proposal

Fix or tell me how to do it)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miklebe** [comment]
![image](https://github.com/user-attachments/assets/6e9e1308-e396-445a-9e1e-7dce757cdf74)
![image](https://github.com/user-attachments/assets/e66b7583-bc3d-4005-97ee-4640bb4536a5)
Latest nightly, charge packs are actually renamed
but the Barite Ra ore processing chain names are fucked
