### ISSUE TITLE
Electric Air Filter - Wrong calculation for cleaning amount.

### ISSUE THREAD

**Issue by MarinMiha** [GTNewHorizons/GT-New-Horizons-Modpack#17639]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 11

### Type of Server

Single Player

### Your Expectation

Setup used for testing:

- Electric Air Filter T1
    - **8x** HV Muffler Hatch
    - **x1** MV Energy Hatch
    - LV input/output bus
 - Advanced Gas Turbine ( MV )
 - Superconductor wire ( MV )
 - Pollution detection device
 - Small turbine ( Steel - 80% efficiency )
 - No absorption filter in input bus.

I wanted to do test calculations for cleaning speed of my setup for my world. Energy hatch is most important part of this test.
If I add only one **MV Energy Hatch** powered by one **Advanced Gas Turbine** to multiblock this setup according to **Pollution detection device** cleans **1,152** pollution per ~1 second ( not sure about this one but I spam click and wait for change on PDD ).

I wanted to try overclocking **Electric Air Filter** by adding second **Advanced Gas Turbine** and second **MV Energy Hatch**  and expected faster cleaning speed which is case with **HV Muffler Hatch**. Now I'm getting **2,880** ~1 second.

### **Some side notes to avoid confusion:**
[Reason I wanted to overclock](https://gtnh.miraheze.org/wiki/Pollution#:~:text=Using%20higher%20tier%20muffler%20hatches.%20However%2C%20the%20highest%20%22effective%22%20tier%20of%20a%20muffler%20hatch%20is%20the%20same%20as%20the%20power%20tier%20you%20use%20to%20run%20the%20EAF.%20For%20example%2C%20if%20you%20run%20the%20EAF%20on%20HV%20power%2C%20even%20if%20you%20have%20IV%20mufflers%2C%20they%20will%20still%20only%20count%20as%20HV.) is to get **4A of MV** power which is **1A of HV** power so my **HV Muffler Hatches** are worth placing.

I know I made mistake before because in this case **x2 Advanced Gas Turbine** outputs only 2A of MV, but I discovered this before I had time to place **x4 Advanced Gas Turbines** and send 4A of MV power...

### The Reality

After some reordering and testing, I found out that you can add a second **MV Energy Hatch** to multiblock, and give power to only one MV **Energy Hatch**  and you will still benefit in cleaning speed.

This is the end setup:

- Electric Air Filter T1
    - **8x** HV Muffler Hatch
    - **x2** MV Energy Hatch ( only one is connected to **Advanced Gas Turbine** )
    - LV input/output bus
 - **x1** Advanced Gas Turbine ( MV )
 - Superconductor wire ( MV )
 - Pollution detection device
 - Small turbine ( Steel - 80% efficiency )
 - No absorption filter in input bus.

Adding more Energy Hatches won't overclock and improve cleaning speed further.

### Your Proposal

Check how the energy tier of the multiblock is calculated for the Electric Air Filter.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
> After some reordering and testing, I found out that you can add a second MV Energy Hatch to multiblock, and give power to only one MV Energy Hatch and you will still benefit in cleaning speed.

Working as (currently, at least) intended. The EAF does not overclock at all, it will always consume the same amount of power based on its tier, regardless of what hatches you give it. See [wiki](https://wiki.gtnewhorizons.com/wiki/Pollution#Electric_Air_Filters) for details. 

The numbers you report exactly match the formula on the wiki; note that in your first example using an MV hatch limits your effective muffler tier to MV.
