### ISSUE TITLE
Transistor in crafting windows when connecting to server

### ISSUE THREAD

**Issue by alphaomega21** [GTNewHorizons/GT-New-Horizons-Modpack#17630]
### Your GTNH Discord Username

schrodingercatz

### Your Pack Version

Nightly 2.7 697

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

When I connect to a server I should not have a free transistor

### The Reality

When I connect to a server I have a free transistor

![image](https://github.com/user-attachments/assets/aee1dba3-7f8d-4a7e-935a-7f80fedc02da)

### Your Proposal

Do not hand out free transistors to everyone who joins a server

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by alphaomega21** [comment]
I suspect this is the source of the issue. It appears there is a recipe for a transistor with no inputs.
![image](https://github.com/user-attachments/assets/9bf4957b-7ac4-4191-bb59-674c1e7eec80)

**Comment by Dream-Master** [comment]
@Chaoschaot232 please change the recipe be only enabled when oc cfg is on. If cfg is off disable the recipe. Otherwise i reverse the exchange recipe.

**Comment by Chaoschaot232** [comment]
> @Chaoschaot232 please change the recipe be only enabled when oc cfg is on. If cfg is off disable the recipe. Otherwise i reverse the exchange recipe.

What a nasty dupe bug! I'll look into this for a fix after my shift. Haven't assumed that smth. could happen ... *sigh*
Will be home tonight at 11 pm (CEST), can't guarantee to get this fixed within my shift because I at a different gas station today ;)

**Comment by Ableytner** [comment]
With an AE2 crafting terminal, you can also shift-click to get stacks of transistors.

**Comment by chochem** [comment]
fixed by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/3d06e071aea1e41b4551a3898c3ffc2e3f31f457
