### ISSUE TITLE
Amazing trophies don't display properly on 2.7-Beta2 with Optifine

### ISSUE THREAD

**Issue by lynxx131** [GTNewHorizons/GT-New-Horizons-Modpack#17637]
### Your GTNH Discord Username

Lynxx131

### Your Pack Version

2.7.0-Beta2

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Amazing trophies display with no graphical glitches when Optfine is installed

### The Reality

Amazing trophies display with graphical glitches when running Optifine.

![2024-10-15_12 13 46](https://github.com/user-attachments/assets/4a46e3c8-990a-4726-bec4-ca39c5cab345)

I have no shaders or resource packs enabled in that screenshot.

Steps to reproduce are:

1. Make sure Angelica is disabled
2. Install Optfine
3. Place down a Trophy and witness the above

### Your Proposal

Display Amazing trophies correctly when Optfine is installed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
Optifine isn’t supported, the pack ships with Angelica, which is a replacement for Optifine.

Don’t try to use optifine in the pack.
