### ISSUE TITLE
Make some efforts to get away from cell chemistry

### ISSUE THREAD

**Issue by Wyrmlet** [GTNewHorizons/GT-New-Horizons-Modpack#17641]
### Your Pack Version

2.6.1

### Your Proposal

Replace cell + fluid recipes in chemical reactors, electrolyzers, etc. with fluid only recipes by adding extra input and output slots for fluids

### Your Goal

Having to move cells around and empty or fill them unnecessarily inflates the amount of infrastructure needed in the early game, hindering automation of stuff like early petrochem

### Your Vision

Fluids and chemistry can be handled easier by only using pipes instead of having to place canners and uncanners every other step, along with not needing to recycle and move empty cells back to their starting positions

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Wyrmlet** [comment]
Mind you, I am unsure if this is even feasible to do, as it might require some rather extensive modifications to pretty much all existing recipes.

**Comment by Reflex18** [comment]
It would be great and put gtnh further towards the standard of gtceu which has zero cell chemistry.

**Comment by ogdae** [comment]
While I think everyone can agree cell chemistry is a little tedious, I believe it plays a pretty important role in early game. While potentially frustrating for the new player, there's a lot of rewarding ways you can learn to automate cell chemistry and early petrochem that work quite flawlessly and efficiently. Additionally, it makes unlocking the LCR all the more rewarding imo.

You could probably argue that the electrolyzer mb feels a lot lore restrictive, since you're stuck with cell outputs until you unlock it, but aside from that the system as a whole feels fine to me. Realistically, the LCR isn't that far away from LV anyway...

My two cents

**Comment by Wyrmlet** [comment]
This might be just a skill issue on my end, but this still contributes quite significantly to the whiplash of coming to gtnh from modern versions. The cell juggling always felt entirely unnecessary to me.

Also, I've never thought of using ULV tanks for this! Did I skip a mention of this somewhere in the questbook?

**Comment by ogdae** [comment]
I mean, we all start somewhere :p so not I'm not just gonna call it a skill issue, however GTNH has a noticeable difficulty/learning curve associated to it, and yes, at lots of points you require decent infrastructure to support your base, especially in regards to petrochemical processing.

**Comment by chochem** [comment]
we have no intention of doing that. This is indeed a challenge to overcome.

A theme you will find often in GTNH is that you have to overcome all kinds of difficulties, and only ~2 tiers later or when you are required to do it a lot will you get an easier more streamlined hightech version (LCR in this case).

**Comment by Ryan6794** [comment]
Would still love to option for this.

**Comment by PLASMAchicken** [comment]
> Would still love to option for this.

You can easily use a ULV Tank to turn cell into fluid or the other way around so no biggie

**Comment by Ryan6794** [comment]
> > Would still love to option for this.
> 
> You can easily use a ULV Tank to turn cell into fluid or the other way around so no biggie

It's not too bad but I would still prefer to work with just fluid/gas if that is all the recipe needs
