### ISSUE TITLE
Avenging bee crashes server

### ISSUE THREAD

**Issue by MarkinoTeck** [GTNewHorizons/GT-New-Horizons-Modpack#17649]
### Your GTNH Discord Username

its_markk

### Your Pack Version

2.7.0 beta2

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

Crafted avenging bee, after putting it on a multiblock alveary server crashed constantly

### Crash Report

https://pastebin.com/raw/uhdAcd1v

**Comment by leumasme** [comment]
Likely caused by https://github.com/GTNewHorizons/ForestryMC/pull/72 ( @Connor-Colenso )
