### ISSUE TITLE
3 million electronvolts

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17658]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

nightly 690

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Other recipes have thousands, tens of thousands of eV, but not millions.

### The Reality

NPIC recipe in target chamber needs from 1 thousand to 3 million electronvolts, which is a very wide range.
![image](https://github.com/user-attachments/assets/fbf324b4-66ef-41ee-a5d5-e713c2ffb6ff)

### Your Proposal

Fix if it is a bug.
In #beta-testing people say that it can be a holdover from the test recipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Elisis** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3504
