### ISSUE TITLE
AL not consume SRSSC in RSSC recipe

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#17663]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.7.0-beta2

### Your Server

ps

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

![image](https://github.com/user-attachments/assets/b74aa8b6-9c60-42ef-8c15-6e4c80d247bb)
![image](https://github.com/user-attachments/assets/12293410-df2f-478c-9e7a-8bd01f7e9e20)

### The Reality

![image](https://github.com/user-attachments/assets/25f16931-2252-4368-8beb-eb49a2cfcd74)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
fixed?

**Comment by lordIcocain** [comment]
yes
