### ISSUE TITLE
Allowing battery buffers to extract

### ISSUE THREAD

**Issue by Reflex18** [GTNewHorizons/GT-New-Horizons-Modpack#17678]
### Your GTNH Discord Username

Reflex18#9829

### Your Pack Version

Nightly 687

### Your Proposal

Battery buffers currently allow insertion of batteries but not extraction.

As showcased in the video below.

https://github.com/user-attachments/assets/1053b377-1819-4402-b645-625a3e2aba4b

### Your Goal

This feature would allow players to setup minor automations such as the one i want to do in the personal dim world with solar panels to avoid having to waste 5% of the power on eu p2p.

![image](https://github.com/user-attachments/assets/77d6634a-f78b-4806-8586-cd834e973a6e)

### Your Vision

This just appears to be a strange decision by a dev long ago to the point where it first appears to be a bug before confirming that it was intended.

However, just because it was always like this doesnt mean it always needs to be.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by LazyFleshWasTaken** [comment]
don't gt++ energy buffers keep their energy when broken?

So you could use them to automate power transfer.

**Comment by Reflex18** [comment]
> don't gt++ energy buffers keep their energy when broken?
> 
> So you could use them to automate power transfer.

Already tried a setup for this.
The result of the testing was that the power doesnt flow when the block is broken. It requires the player the manually disconnect and reconnect.
![image](https://github.com/user-attachments/assets/2ea548bc-4aa8-4aa6-a07e-74f76cc1c3ea)

**Comment by LazyFleshWasTaken** [comment]
> > don't gt++ energy buffers keep their energy when broken?
> > So you could use them to automate power transfer.
> 
> Already tried a setup for this. The result of the testing was that the power doesnt flow when the block is broken. It requires the player the manually disconnect and reconnect. ![image](https://private-user-images.githubusercontent.com/127531099/378058864-2ea548bc-4aa8-4aa6-a07e-74f76cc1c3ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMjI3NTIsIm5iZiI6MTcyOTMyMjQ1MiwicGF0aCI6Ii8xMjc1MzEwOTkvMzc4MDU4ODY0LTJlYTU0OGJjLTRhYTgtNGFhNi1hMDdlLTc0Zjc2Y2MxYzNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQwNzIwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmZjM2NjYjY5NDkzY2JmMmI1MTlmZDRiMjYwYzc0YzQzYjM3ZDFmZmNmNWFjMTIxZjE2ZTY3MDhjYzA5ZDEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PA1ulNDKtEu2a4moAC-hbFtsH-1fxYJpCQclchv4WOo)

I see. Unfortunate.

**Comment by chochem** [comment]
this is intentional in basic GT and GTNH. The goal is actual power infra and not item transport as a lazy replacement.

**Comment by Reflex18** [comment]
> this is intentional in basic GT and GTNH. The goal is actual power infra and not item transport as a lazy replacement.

Was that a concern in the past?
