### ISSUE TITLE
OreDict not working in AL for UMV UXV circuits

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#17671]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

698

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

OreDict working in AL for UMV UXV circuits

### The Reality

OreDict not working in AL for UMV UXV circuits

### Your Proposal

make OreDict working in AL for UMV UXV circuits

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
which recipe?

**Comment by lordIcocain** [comment]
seems like every
