### ISSUE TITLE
Stuck in the Twilight Forest? Quest still does not work

### ISSUE THREAD

**Issue by Semetix** [GTNewHorizons/GT-New-Horizons-Modpack#17673]
### Your GTNH Discord Username

Semetix

### Your Pack Version

2.7.0-beta-2

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

The Quest should detect the fireflys. Every other item gets detected, except the fireflys.

### The Reality

It does not detect

### Your Proposal

It should detect the quest

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Semetix** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17440 Same Issue

**Comment by chochem** [comment]
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17440
