### ISSUE TITLE
[NEI] Logistics Pipes Soldering Table recipes not showing

### ISSUE THREAD

**Issue by Shahelion** [GTNewHorizons/GT-New-Horizons-Modpack#17679]
### Your Pack Version

N/A

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Tried to check recipes for Logistics Pipes in NEI.

### The Reality

Only the basic crafting table ones show. Anything requiring the Soldering Table (most of the pipes) doesn't show. The Soldering Table DOES have a little "Recipes" thing when hovering over the arrow, but clicking it does nothing.

### Your Proposal

Soldering Table handler needs to be added, I guess. I am unfortunately unable to confirm whether the recipes exist and simply are not being shown, or are actually gone, as I cannot find the recipes listed ANYWHERE online for 1.7.10.

Mod versions tested with:
NEI 2.6.42
LP 0.10.0.79

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Atlantis102** [comment]
google translate

Logistics Soldering Table disabled in GTNH

**Comment by Shahelion** [comment]
I couldn't actually find any downloads for LP for 1.7.10 anymore, this was the last version that was available before the 1.7.10 archive went down. I've had this file for a while now.

Also, this is outside the GTNH pack but using the GTNH fork of NEI. Didn't know that there were new recipes in the GTNH pack.

**Comment by Atlantis102** [comment]
for GTNH download versions LP from here
https://github.com/GTNewHorizons/LogisticsPipes/releases

GTNH 2.6.1  -   1.2.21  LogisticsPipes or 1.2.22 or older
GTNH 2.7.0 beta+/nightly   - 1.2.25 or newer

**Comment by Shahelion** [comment]
[crash-2024-10-19_03.30.44-client.txt](https://github.com/user-attachments/files/17445147/crash-2024-10-19_03.30.44-client.txt)

**Comment by Shahelion** [comment]
I have put the crash report into a Gist for those who don't want to download the file. https://gist.github.com/Shahelion/a1f7203f4b29d094f20bb31aa1e42626

**Comment by Shahelion** [comment]
The GTNH version of LP requires the ModularUI2 mod, even though this is not clearly stated anywhere. With that, the issue is resolved.
