### ISSUE TITLE
World always crashing after loading

### ISSUE THREAD

**Issue by salaxia** [GTNewHorizons/GT-New-Horizons-Modpack#17680]
### Your GTNH Discord Username

Salaxia

### Your Pack Version

2.7.0 beta 2

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

Every time loading my world it crashes saying exception in server tick, after the initial crash, it stops loading at 0%.

I backup my world and reenstalled my modpack several times.

### Crash Report

[crash-2024-10-19_12.37.49-server.txt](https://github.com/user-attachments/files/17444890/crash-2024-10-19_12.37.49-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by fbfnysnshnsgnwg** [comment]
appears to be world corruption
