### ISSUE TITLE
AE2FC icon mismatch between ID#4368 - ID#4377  

### ISSUE THREAD

**Issue by mcarreon** [GTNewHorizons/GT-New-Horizons-Modpack#17687]
### Your GTNH Discord Username

Brando#7216

### Your Pack Version

2.6.1

### Your Server

Selfhosted Local Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Items in NEI and in world between ID#4368 - ID#4377 should have the correct items

### The Reality

The items icons are jumbled. ie. ME Fluid Input Bus having the icon of a Flat Dual Interface or the ME Fluid Level Emitter having the Icon of a Fluid Export Bus. 

I haven't figured out how to reproduce this mismatch, but I notice it starts to happen if the server has been running for too long. Sometimes, I will log into the server and the ID is mismatched, requiring a restart to fix. AFAIK the icon mismatch 
only happens when logging in to the server, it has not changed while I was on the server. 

![java_dJMHHTFCEO](https://github.com/user-attachments/assets/1c44e33d-2bb7-4a45-925a-e55dc48cc938)
![java_1Q6O411Xtb](https://github.com/user-attachments/assets/cca1438d-d3bc-48ec-b7e7-6a551bef1c86)
![java_fZn7MfVfD2](https://github.com/user-attachments/assets/d66aa678-8b85-41d8-8e82-35856709ec8a)

### Your Proposal

Icons are displayed properly for their appropriate IDs 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
seems to be fixed (if it ever was broken)

![image](https://github.com/user-attachments/assets/5213f018-2254-4154-ba52-9e71545215fb)

![image](https://github.com/user-attachments/assets/dde95dfb-8a0f-4cc7-9373-3d088725f51f)
