### ISSUE TITLE
blood altar ddon't stop crafting

### ISSUE THREAD

**Issue by gourdindu32** [GTNewHorizons/GT-New-Horizons-Modpack#17689]
### Your Pack Version

2.6.1

### Your Server

sp

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Hello,
I'm not familiar with the mod blood magic
but until now when an object was made in the altar, then it stopped, but now it continues without removing the object
do you know what I did wrong please?

### The Reality

craft again and again

### Your Proposal

does not reject objects, i use AE2

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by gourdindu32** [comment]
not a bug ...

**Comment by querns** [comment]
To add a little more context -- this is what the blood altar is supposed to do. When you put (e.g.) a blank slate into the altar, it crafts it up into a reinforced slate. The altar will then pause for a few moments, and then start the next recipe to craft it up into an imbued slate. It's up to you to pull the slate out at the right time.
