### ISSUE TITLE
Quantum Voidwalker boots created with negative durability

### ISSUE THREAD

**Issue by Demiu** [GTNewHorizons/GT-New-Horizons-Modpack#17682]
### Your GTNH Discord Username

Demiu#1527

### Your Pack Version

2.6.1

### Your Server

private

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

I make the infusion craft for quantum boots of the voidwalker, I charge them, everything is great

The quantum boots I used were take off straight from me so they were almost fully charged

### The Reality

Boots got crafted with negative durability and refuse to get charged in both EV and IV battery buffer
![image](https://github.com/user-attachments/assets/1a4dc838-357e-4f7b-a5a0-895b8ece8822)
![image](https://github.com/user-attachments/assets/c3b9c719-60dd-4c17-8346-3bbfa6107163)

I searched the discord for negative durability and somebody had the same issue, and like them I can charge the boots in an HV battery buffer (durability immediately went positive), so it may just be that the boots have a wrong voltage tier

### Your Proposal

Have them be crafted properly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by EyeDeck** [comment]
Their voltage tier is definitely not set correctly. 
[Here](https://github.com/GTNewHorizons/ThaumicBoots/blob/master/src/main/java/thaumicboots/item/boots/voidwalker/ItemQuantumVoidwalkerBoots.java)'s where they're defined, the voltage tier is not explicitly set, so they inherit from [Electric Boots of the Voidwalker](https://github.com/GTNewHorizons/ThaumicBoots/blob/master/src/main/java/thaumicboots/item/boots/voidwalker/ItemElectricVoidwalkerBoots.java) which are tier 3/HV. Ought to be at least set to EV like the `QuantumSuit Boots`, and `Quantum Boots of the Traveller`, or arguably even IV, given their 10x power capacity increase over the other quantum stuff.

Can also confirm that they don't like charging with negative durability, but tossing 'em in an HV battery buffer _specifically_ does fix their durability to non-negative, and after they they'll charge like any other HV thing.
