### ISSUE TITLE
NEI bookmarked recipes don't tell me if my ME system has the ingredients for crafting, Normal NEI does with red background.

### ISSUE THREAD

**Issue by pacomesoual** [GTNewHorizons/GT-New-Horizons-Modpack#17695]
### Your GTNH Discord Username

theaspectofgreed

### Your Pack Version

2.6.1

### Your Server

Dedicated private server

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Tried checking if my ME had enough materials for a craft (blank pattern), right clicked the crafting terminal and went looking for the recipe in NEI, while hovering the ? symbol got this result : 
![image](https://github.com/user-attachments/assets/b24c8420-41aa-4803-af83-e2b3b3a2b88b)

Bookmarked the recipe, tried hovering it with my mouse, which should basically do the same thing hovering the ? symbol did.

### The Reality

instead I got no information on if my ME had enough materials or not.
![image](https://github.com/user-attachments/assets/ad43b9ce-3019-40a4-9bd2-16e1ab32d890)

got the usual red cross, that tells me I don't personally have the materials on me, but no red background for AE2.

### Your Proposal

I have no idea how any of this works, just felt like an inconsistency, figured its either a known unimportant issue or a small thing no one bothered bothering devs about as it's pretty inconsequential.
I just happen to use those features regularly out of habit and got slightly annoyed when it didn't work as expected.

if its a quick fix, that's a great qol feature to squeeze in an update somewhere down the line, if it requires an overhaul of some systems for this to work I'll let you judge if it's worth it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by slprime** [comment]
similar problem: https://github.com/GTNewHorizons/NotEnoughItems/issues/489
