### ISSUE TITLE
Lepidopterist's Chest not craftable

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#17691]
### Your GTNH Discord Username

Marcel|Chaoschaot234

### Your Pack Version

2.7.0 beta 1

### Your Server

private mp server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

It should somehow be possible to optain this Chest.

### The Reality

The Chest isn't craftable what ever I am doing.

![image](https://github.com/user-attachments/assets/fc264bb9-c035-499e-9c7b-9eba9084364b)

### Your Proposal

Add an recipe well suited for this Chest and the packs recipe style.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment]
The recipe infact exists i just cant figure out why it doesnt load
