### ISSUE TITLE
Antimatter forge, Gorge and Blackhole central objects are not localized

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17705]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

nightly 704

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

If these objects will be visible to player in non-debug mode at stable version, they should have localized names.

### The Reality

Antimatter forge (???), Gorge (neutron star) and Blackhole central objects are not localized:
![2024-10-21_13 10 14](https://github.com/user-attachments/assets/ec2a05d8-2749-4292-903b-1b3b5476e781)
![2024-10-21_13 46 47](https://github.com/user-attachments/assets/256f76ed-7e01-4686-98ec-96651dda916c)
![2024-10-21_13 10 03](https://github.com/user-attachments/assets/5c2416a6-db78-4a4c-b168-cc220aae5592)

### Your Proposal

Fix names of these objects.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
This is true for other renderers as well such as eoh, I believe.
