### ISSUE TITLE
Cost disparity between flight options

### ISSUE THREAD

**Issue by Voidlinked** [GTNewHorizons/GT-New-Horizons-Modpack#17701]
### Your Pack Version

2.7.0 beta 2

### Your Proposal

Flight is great. It saves food, the manoeuvrability is great, and it is overall supremely satisfying, and a huge qol improvement. My biggest gripe with it is the frankly unreasonable cost for the angel ring, a perma flight option that is for some reason tiered to the same place as the gravi chestplate, when it doesn't use _tech_ to fly, but magic, and is also _only_ flight, not an op piece of armor.

Let's look at flight options per tier, at least the ones I know:

The earliest, mv: Flight potion. Not directly infinite flight, but is mv, and has infinite durability with the thaumic restorer.

HV: THaumostatic Harness, and girdle. Together they are free flight, though they consume potentia as fuel, which is basically infinite and easily sourceable. Can be paired with thaumostatic spire from automagy to achieve a large area in which fuel is supplied automatically. This is the recipe of the harness: 
![image](https://github.com/user-attachments/assets/d75fb07a-56f3-4d6a-9847-efe040e24187)

Another in HV, though more like late mv, Thaumium reinforced wings. The flight is more like a jetpack, but it no doubt offers a reasonable type of infinite rflight for its price, even if its kinda shitty.

EV: golden feather, another form of limited flight. Unlimited in a 50 block range of a beacon. Considering it needs a beacon to function, I would argue it's even expensive/underpowered, but not much I can do about that. This is the recipe: 
![image](https://github.com/user-attachments/assets/aa1c2eb1-d798-440d-ac96-58d7446cdf8b)

IV: Robes of the stratosphere, an ichorium-based chestplate, completely unlimited flight, and the only reason it's even iv is because ichorium ingots need osmiridium.
![image](https://github.com/user-attachments/assets/3fd3c58c-96d0-4f65-9a20-3e4b9274b63d)

Considering all these options, how does _this_ look reasonable?
![image](https://github.com/user-attachments/assets/76b5964f-6abb-4aed-be9f-6d6cad2d3300)
Gated to tritanium, at the same tier as gravichestplate, an armor piece that offers basically invulnerability so long as you have energy.

### Your Goal

Make a reasonable recipe for the angel ring. It offers no benefit other than cosmetic look, and should therefore be gated at most to the tier of the robes of the stratosphere. Here is an example recipe that seems much more reasonable in my eyes: 
![image](https://github.com/user-attachments/assets/a957ca70-71b6-4579-a7ed-6bb3c197bca4)
It keeps most of the current recipe, but downtiers it by removing the tritanium and cheapens it slightly by lowering the extremely primordial pearl to a normal pearl, tho it keeps the iridium ring and adds thaumostatic harness and gradle to align it more with 'magical means of flight'

### Your Vision

It would offer another form of flight available at the same tier other permanent forms of flight become available. I have no doubt there are other forms of flight that I don't know of.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by duckedddd** [comment]
Looks good, in the current state, the ring is practically never made / never has a need to be. It even uses rare aspects that can only be initially sourced by wisps so it looks completely reasonable to me.

The ring also has the massive downside of taking up a ring slot that loki would otherwise be in, which means that it is never really used lategame.

**Comment by Voidlinked** [comment]
How come? The wings look great cosmetically; I love the golden ones. 

Does he really dislike them in some way?

**Comment by chochem** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6491 XD

**Comment by Voidlinked** [comment]
Oh. I see. I saw that, but I had thought he changed his mind in the 4+ years since.

**Comment by chochem** [comment]
well clearly they were reenabled since, but only with a late/expensive recipe as compromise.

**Comment by Dream-Master** [comment]
I close this now. If the recipe to expensive I can disable the ring again
