### ISSUE TITLE
Degasser Control Hatch with top 2 in my server load [Nightly]

### ISSUE THREAD

**Issue by VladiSl4ve** [GTNewHorizons/GT-New-Horizons-Modpack#17717]
### Your Pack Version

nightly 705

### Your Server

dedicated r9 9750x3d

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Setup the 7 tier water 3 weeks ago and noticed lags, waited fix but nothing changed.

### The Reality

![image](https://github.com/user-attachments/assets/e65d036d-0f45-49ae-b10c-d766b7069e94)
![image](https://github.com/user-attachments/assets/e6d4df7c-426c-4163-8414-4c6ac7a82bc0)

### Your Proposal

do something, only precise assembler lags more

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by VladiSl4ve** [comment]
why devs always respond by writing a ticket if they are mostly ignored...

**Comment by mitchej123** [comment]
So they don't get lost....
