### ISSUE TITLE
NEI GregTech Material Tabs have now mouse coordiante errors

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#17715]
### Your GTNH Discord Username

Marcel|Chaoschaot234

### Your Pack Version

2.7.0 beta 3

### Your Server

private mp server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

No wired behavior within NEI when hovering over an item with the mouse in any of the GT Material Tabs.

### The Reality

Like reported in DC from xecheet4th (https://canary.discord.com/channels/181078474394566657/522098956491030558/1298072548570959882)
I checked it out myself and can confirm this behavior is present in all the GT Tabs within NEI: https://canary.discord.com/channels/181078474394566657/522098956491030558/1298074409168277585

At last on my image you can see where my mouse hover over and where it is hovering within the UI so we have here a coordiante problem when hovering over items there:

![image](https://github.com/user-attachments/assets/5285b307-a74b-475e-9f04-0fdd448683d5)
![image](https://github.com/user-attachments/assets/915c9b89-84d2-48a2-9553-5c714f69a5f1)
![image](https://github.com/user-attachments/assets/a7b6634e-6a17-4064-990e-07dc6c454580)

### Your Proposal

Look what has changed before this happened in earlier nightlies and maybe revert some commits to it or try to supply any kind of hotfix :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment]
fixed in https://github.com/GTNewHorizons/nei-custom-diagram/pull/43/files
