### ISSUE TITLE
Crash related to AE2FC

### ISSUE THREAD

**Issue by d1ssolvedz** [GTNewHorizons/GT-New-Horizons-Modpack#17718]
### Your GTNH Discord Username

d1ssolved

### Your Pack Version

2.7.0 beta 3

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Actions

Ordering Ammonia in an LCR ( circ 24) via dual fluid interface crashed my SP server. Reloading didn't work. I've gotten into a crash loop and cant play the game.
Can't test if there are any other AEFC related crashes.

Reverting the mod back from (1.3.41)  to (ae2fc-1.3.36-gtnh) fixed the issue.

### Crash Report

[crash-2024-10-22_04.59.18-server.txt](https://github.com/user-attachments/files/17468958/crash-2024-10-22_04.59.18-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by lordIcocain** [comment]
Can you show setup?

**Comment by d1ssolvedz** [comment]
Replied in discord
https://discord.com/channels/181078474394566657/401118216228831252/1298114000533459107
