### ISSUE TITLE
Many recipes are now duplicated with and without -Dgt.recipebuilder.recipe_collision_check=true

### ISSUE THREAD

**Issue by Chaoschaot232** [GTNewHorizons/GT-New-Horizons-Modpack#17716]
### Your GTNH Discord Username

Marcel|Chaoschaot234

### Your Pack Version

2.7.0 beta 3

### Your Server

private mp server and sp world

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Since -Dgt.recipebuilder.recipe_collision_check=true is no longer needed within beta3 it should also not happen that recipe duplications are showing up within NEI and they should have been gone after the fix anyways.

### The Reality

As you can see with the diamond there are now two recipes where one is still only ic2 diamond into diamond block and a 2nd ones which allows both diamond version (oredict) to be used to get a block of diamond.

This is repeated with Diamond blocks cutted down into diamond plates which are now be able to be made with six different recipes where it should only have three.

![image](https://github.com/user-attachments/assets/61ca10cc-81d2-4303-b0dd-9cf93a4ed829)

### Your Proposal

Go through the entire Recipes and remove any duplicates to reduce this overheat.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
This particular recipe is not a duplicate and is not new.

Besides that, there _are_ duplicate recipes after the fixes, but they are known and intended. If it bothers you a lot, you can re-enable the collision checker.

**Comment by Chaoschaot232** [comment]
> This particular recipe is not a duplicate and is not new.
> 
> Besides that, there _are_ duplicate recipes after the fixes, but they are known and intended. If it bothers you a lot, you can re-enable the collision checker.

Well, I did this but it shows them anyways instead of hiding it. Also I think that there would have been a way to yeet every duplicated recipe. Just wipe them all out and put them like they should be within the scripts file in the coremod.

**Comment by FourIsTheNumber** [comment]
> Well, I did this but it shows them anyways instead of hiding it. Also I think that there would have been a way to yeet every duplicated recipe. Just wipe them all out and put them like they should be within the scripts file in the coremod.

No it does not. This is not a duplicated recipe.

No, it is not even remotely that simple. What you are saying here makes literally zero sense.
