### ISSUE TITLE
Distillation Towers Do Not Recognize Space in ME Hatches for void protection

### ISSUE THREAD

**Issue by Ruling-0** [GTNewHorizons/GT-New-Horizons-Modpack#17711]
### Your GTNH Discord Username

ruling_

### Your Pack Version

Nightly 695

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

The Distillation Tower / Dangote / Mega DT should recognize it has enough space in an ME output hatch to run a recipe and then run the recipe.

### The Reality

If the DT is built using ME output hatches, even if they are large enough, it will refuse to run unless set to void overflow (it doesn't void anything, it does correctly place in the output). It works fine with normal output hatches.

### Your Proposal

ME Output hatches should work.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by pilchard436** [comment]
this only occurs when you mix me output hatch with normal output hatch.

**Comment by Yoshy2002** [comment]
Same Bug in Nightly 719. DT for Distilled Water with Me Output Hatch at 2nd Layer and Normal UHV(doesnt matter how big) Output Hatch at 3rd layer wont work, even tho the Output is only affecting the Second Layer with the ME Output Hatch.

**Comment by Ruling-0** [comment]
![image](https://github.com/user-attachments/assets/f2adc823-dc38-4350-863f-8e24542129a7)
![image](https://github.com/user-attachments/assets/23766c60-6159-4389-959d-8a4015918c6c)

Appears the fix has broken things further - this DTPF is producing the eternal coil hypogen recipe. After update it shut down, and only runs if void protection is on. A key thing to note is that the spacetime DTPF runs fine, leading me to believe it's an issue for recipes that output multiple fluids.

On talking on the Discord, it appears it requires 1 ME hatch per fluid in the output to function. https://discord.com/channels/181078474394566657/181078474394566657/1312961226111713320

All tested on RC2.

Reopening and flagging critical because this will now certainly break many existing setups.

**Comment by Ruling-0** [comment]
I also think even when it would run with void protection on, void protection just wasn't working.
I watched it keep running a recipe and eating all the ingredients while having no output space.
