### ISSUE TITLE
Target chamber crashes if no mask provided

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17710]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

nightly 704

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Target chamber won't crash, it will just say that there is no mask.

### The Reality

Target chamber crashes if no mask provided
![2024-10-21_19 54 47](https://github.com/user-attachments/assets/30604705-f358-44a4-bc8f-edfcd1386eaf)

### Your Proposal

Fix crash.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Elisis** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3504
