### ISSUE TITLE
Assembler Recipe for PTFE pipe casing

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#17727]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.7.0 beta 3

### Your Proposal

Assembler Recipe for PTFE pipe casing
![image](https://github.com/user-attachments/assets/2e0545d5-17ce-475d-9d7c-de41947a0730)

### Your Goal

Speeeed

### Your Vision

Less molec use

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by BlueHero233** [comment]
None of the pipe casings have assembler recipes, why ptfe in specific?

**Comment by LazyFleshWasTaken** [comment]
It's used a lot in lcr and mcr? Adding recipes for all pipe casings is probably a good idea too, tbf, tho I think the item pipe casings have assembler already.
