### ISSUE TITLE
HP solar boilers void and continue to produce steam as soon as internal buffer is full

### ISSUE THREAD

**Issue by qunYp3dZSyLjoEoEg** [GTNewHorizons/GT-New-Horizons-Modpack#17734]
### Your Pack Version

2.6.1

### Your Server

StoneHuts

### Java Version

Java 21

### Type of Server

Thermos

### Your Expectation

I'm still in late LV and tried to upgrade my steam production by placing more HP solar boilers. Since I don't have reservoirs yet I calculated that I neded 3 RC water tanks for my setup. As those aren't exactly fast at producing, my plan was to place the boilers one after another, after the previous one had flled with 1-2 buckets of water, as with the 1:160 ratio it would fill the boiler and still have water left over, so that when water got to it again it wouldn't explode. And only after every boiler had filled with water to place the pipes for steam. 

I expected that, after I was away for some time, that they would be full of water and steam. I didn't wanna place the steam-pipes right away because of the low but enough (in theory) water production. 

### The Reality

After some time being away, to let them fill up with water, I noticed that a lot of them still weren't full of steam. 
After observing for some more time I noticed that as soon as the internal buffer filled to the 32 buckets it is, it reset itself to 24 buckets. I then tried to block off the output with cobblestone and place pipes there, but the boilers still voided 12 buckets of steam as soon as their internal buffer reached 32 buckets. 

### Your Proposal

The HP solar boilers (I did not test with the normal ones) should not void. At the very least, they should not void if there is a block in front of the output or a pipe that is full. 

Otherwise it gets really difficult to build a lot of them in a way so that they don't explode.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miklebe** [comment]
It's an intended mechanic for all bronze and HP boilers from Gregtech. If you don't want voiding, try RC boilers (idk what the do on full steam) or advanced boilers.

**Comment by Baerschen** [comment]
This gets somewhat easier in 2.7 too since there is a Steam water pump multi introduced that bridges the geap between the water Tank and the EIO reservoir/thristy tank
