### ISSUE TITLE
Item conduit connected to dual interface crash

### ISSUE THREAD

**Issue by sudgy** [GTNewHorizons/GT-New-Horizons-Modpack#17731]
### Your GTNH Discord Username

sudgy

### Your Pack Version

2.7.0 beta 3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Make a dual interface with a pattern that uses a fluid in it and put an item conduit next to it (any configuration).  Then request to craft whatever the pattern makes.  The game crashes.

### Crash Report

[crash-2024-10-22_17.59.33-server.txt](https://github.com/user-attachments/files/17483703/crash-2024-10-22_17.59.33-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by FourIsTheNumber** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17718
Duplicate, already fixed
