### ISSUE TITLE
Make High Pressure Steam Turbine viable (resurrect it from dead 💀)

### ISSUE THREAD

**Issue by imTheSupremeOne** [GTNewHorizons/GT-New-Horizons-Modpack#17742]
### Your GTNH Discord Username

imthesupremeone

### Your Pack Version

2.6.1

### Your Proposal

This is the recipe of High Pressure steam turbine : 💀 
![au5L7ja](https://github.com/user-attachments/assets/f82173c1-2b75-4424-bf20-e4ff030f2718)

.... while this is the fricking gas turbine : 💀 💀 💀 
![image](https://github.com/user-attachments/assets/1dc36d7e-0542-4a8d-8d81-eb08cda35d38)

I looked on Vanilla Greg and the HP-steam turbine actually requires an IV casing which in term contain tungsten steel and circuits. But I suggest removing it completely from recipe and making it something like this : 
![image](https://github.com/user-attachments/assets/3b64661f-d136-4c96-bb3d-5bd562370b28)

### Your Goal

Achieve better balance and provide more options.

### Your Vision

I don't understand or missing smth why is this thing so expensive. In vanilla Greg it requires Tungsten Steel (for IV casing) but here everything is much harder and is processed in big processing chains so I believe it should be removed from recipe.

And even with the changes I suggest Gas would still be better option since it's easy to get passively, it's easy to handle, and the multiblock is made from HV basic Stainless Steel while the poor HP Steam Turbine casings are Titanium.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by imTheSupremeOne** [comment]
High pressure steam is not Supercritical, it's the one that gives 1 EU from 1 L instead of 0.5.

**Comment by StaffiX** [comment]
This is already done by https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/867

and the xl version by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2806

**Comment by imTheSupremeOne** [comment]
> This is already done by [GTNewHorizons/NewHorizonsCoreMod#867](https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/867)
> 
> and the xl version by [GTNewHorizons/GT5-Unofficial#2806](https://github.com/GTNewHorizons/GT5-Unofficial/pull/2806)

Nice, but there was a second part I suggested of removing tungsten steel from recipe completely, and as far as I understand programming it's still there : 
https://i.imgur.com/XaT3Rpf.png

My reasoning is that it's much harder to obtain than in vanilla Greg and mb even he went to hard on putting it right there especially considering Benzene option.

It's also has to be used in pair with Titanium boiler which is really cheap Multi gated only by Titanium. Also those cables in Recipes are Gold HV ones (!)
![image](https://github.com/user-attachments/assets/c9508867-d51b-4470-a60b-68ff7c53428c)


Also I don't know if "OrePrefixes.circuit.get(Materials.Elite)" is IV or EV. I suggest making it EV to make it easier for people who might not yet have AE/LP autocrafting as like how you can see from boiler recipe it's just an early EV.


=======
I believe this further simplifications are needed because even with my proposed changes it still be much harder, and much more expensive than Gas Turbine which only requires Titanium casing and is built from Stainless Steel, and doesn't require bigass Titanium Boiler. (distil tower is Stainless Steel as well)

In a world where it's perfectly balanced I think it's need to be even easier while Gas has to be nerfed; but idk about such changes and if they are going to be fun... So what I'm saying I think the changes I've proposed of further reducing complexity (remove IV tungstensteel requirement) and cost (cheaper EV circuit insted of IV) are pretty safe to do, and Gas turbine still be less expensive.

**Comment by imTheSupremeOne** [comment]
I wanna ask one more time to reconsider not removing Tungsten Steel from HP turbine.

I was thinking about this and understood that I've put too much emphasis into HP turbine itself and not the actual thing I'd wanted to be "fixed" -- **Large Titanium Boiler**.

The "problem" is that it was actually "buffed" in GTNH and it's producing High Pressure steam instead of regular one. This ripped him from his proper place in progression(early EV) and it was put against much more advanced generators that are sharing the same HP-steam mechanic : Large Heat Exchanger, Liquid Nukes & Solar Salts; while the numbers were chosen clearly to compete with early EV options : Large Gas Turbine & Large Combustion.

I think this is a problem and makes Titanium boiler really weak option that feels bad to play -- at the point of getting Tungstensteel why go for complexity of the Boiler and Super fuel(the only type it accepts both in GTNH and Vanilla) when you can go for easy Lava + it will give you Tantalum, which I know people put this thing for a Tantalum even without power gen setup...


----
I don't think it should be buffed to compete with mid EV+ options because there already are a plenty, while at early EV only a few and it was ripped from that place with a buff to it.

My vision is that Large Titanium Boiler should be fixed and put in it's proper place by shuffling gating items from the commonly used HP-Turbine, to the respective mechanics itself.

So in Vanilla Greg, and it's still in GTNH, LHE doesn't require any Tungstensteel. In Vanilla it was inside a HP-Turbine because HP mechanic was only used by this block and IC2 fluid nukes. I suggest changing the recipe of LHE from and to : 
![image](https://github.com/user-attachments/assets/53f699ed-9918-410d-bb42-eace14547f99)

I believe that change is also better because it will better identify at what point of progression you suppose have access to multiblock, because I did indeed miss it looking only on the Titanium boiler and not the HP turbine requirements.

And with that change, and maybe putting Tungstensteel into other options if they don't have it and were relying on turbine to have it, you could safely change the HP steam turbine to something like this : 
![image](https://github.com/user-attachments/assets/11c4e771-f0b5-4408-9d21-1e75ba75bef1)


====

Adding options when there are only a few is gigagood; and removing options further is even more giga but bad -- which what is happening right now after Titanium Boiler got "buffed" to HP-steam.

This is why I believe it should be fixed in a way that I'm asking, to it's original place in vanilla progression. 

In terms of numbers even with the buff it received they are still on level of Gas Turbine and Distilation Tower while being much much more complex and producing 3,000 pollution/sec. 
![image](https://github.com/user-attachments/assets/e96a60d5-26da-4315-bbc3-c77c158ba0dd)
![image](https://github.com/user-attachments/assets/f01834f7-4ed0-4a0f-9e2b-267ce54b1d3e)
