### ISSUE TITLE
New Thaumcraft Essentia FindIt functionality crashes

### ISSUE THREAD

**Issue by Miklebe** [GTNewHorizons/GT-New-Horizons-Modpack#17748]
### Your GTNH Discord Username

Mike_be

### Your Pack Version

2.7.0 Beta3

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Can be seen in beta-test channel on discord. https://discord.com/channels/181078474394566657/522098956491030558/1299064660179554406
When looking up essentia that either doesn't exist nearby from infusion recipe, or primal charm, or looking up item recipe after trying to find essentia results in crash.

### Crash Report

[crash-2024-10-24_21.36.44-client.txt](https://github.com/user-attachments/files/17510811/crash-2024-10-24_21.36.44-client.txt)
[crash-2024-10-24_21.37.04-client.txt](https://github.com/user-attachments/files/17510812/crash-2024-10-24_21.37.04-client.txt)
[crash-2024-10-24_21.37.46-client.txt](https://github.com/user-attachments/files/17510813/crash-2024-10-24_21.37.46-client.txt)
[crash-2024-10-24_21.38.06-client.txt](https://github.com/user-attachments/files/17510814/crash-2024-10-24_21.38.06-client.txt)
[crash-2024-10-24_21.38.21-client.txt](https://github.com/user-attachments/files/17510815/crash-2024-10-24_21.38.21-client.txt)
[crash-2024-10-24_21.38.39-client.txt](https://github.com/user-attachments/files/17510816/crash-2024-10-24_21.38.39-client.txt)
All the individual crashes that happened during recording.
And some before i recorded the video:
[crash-2024-10-24_21.32.34-client.txt](https://github.com/user-attachments/files/17510807/crash-2024-10-24_21.32.34-client.txt)
[crash-2024-10-24_21.34.14-client.txt](https://github.com/user-attachments/files/17510808/crash-2024-10-24_21.34.14-client.txt)
[crash-2024-10-24_21.34.36-client.txt](https://github.com/user-attachments/files/17510809/crash-2024-10-24_21.34.36-client.txt)
[crash-2024-10-24_21.34.59-client.txt](https://github.com/user-attachments/files/17510810/crash-2024-10-24_21.34.59-client.txt)
The full log is available in the same place on discord (too big for github).
https://discord.com/channels/181078474394566657/522098956491030558/1299066437398429887

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by leumasme** [comment]
Caused by https://github.com/GTNewHorizons/FindIt/pull/24
Will try to check and fix tomorrow
