### ISSUE TITLE
Buff High Octane Gasoline and the ECE

### ISSUE THREAD

**Issue by Zenovis** [GTNewHorizons/GT-New-Horizons-Modpack#17745]
### Your GTNH Discord Username

zeno3772

### Your Pack Version

2.7.0 Beta 2

### Your Proposal

I am proposing:

- Buffing the Fuel Value of High Octane Gasoline from 2.5M to 2.75M
- Reducing The Liquid Oxygen consumption of a boosted ECE to 15L/s instead of 40L/s

### Your Goal

After automating High Octane Gasoline I've found it to be rather underwhelming and not as rewarding as I expected, considering the complex processing chain and time investment needed to set it up. 

**Buffing the Fuel value of HOG**
Considering the amount of effort it takes to set it up, 2.5 Million EU/ cell is too low. A decent EV HOG setup will require:

- ~11-12 distillation towers, 
- 2-3 LCRs, 
- 2-3 Oil crackers, 
- realistically a multiblock mixer + electrolyzer. 
- A pyro oven / ICO + A wood farm (for methanol / acetone, if using the most efficient route)
- An Oxygen source

This is much more complex and poses many more logistical challenges to automate and scale than the alternatives. For that reason I suggest the fuel value should be changed up to 2.75M, which would offset a large chunk of the production costs and make it more worthwhile.

**Buffing the ECE**
The ECE is bad. Really bad. the 40L/s Liquid Oxygen consumption is a flat and boring energy tax that cuts into HOG's efficiency.
The current LOX recipe at HV produces 1000L every 60s, meaning it takes 2.3 Vacuum freezers to provide enough LOX for 1 ECE. An MVF at early IV just for lox is not fun.
The ECE is also effectively gated behind platline (Iridium for IV Dynamos), at almost the same point as the UCFE (Requires Osmium, Rhodium Palladium, and Iridium). If a player can afford to set up and run an ECE, they will (almost) always be able to theoretically set up a UCFE instead.  
That's why in order to make the ECE a more attractive and usable medium between the LCE and UCFE, the LOX requirement should be lowered to 15L/s (just enough for 1 Vacuum freezer per ECE).

### Your Vision

HOG is currently in a much better place right now compared to in 2.6, but it is still very much mediocre compared to the alternatives, while requiring way more time invested. These buffs would help it shine, and make it a much more appealing source of power generation. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Zenovis** [comment]
Also, the pollution on the ECE needs to be reduced ASAP. It's absurd. It produces more than almost any GT++ multi available at the tier, besides the implosion compressor.
For comparison, these are some other pollution numbers:
- Large / Advanced Large Gas Turbine - 300/s
- Large Combustion Engine - 480/s
- XLGT - 4000/s

I propose changing the pollution to 700/s
![image](https://github.com/user-attachments/assets/0b55ca56-c110-4ae0-99b9-e6e1c3116fe4)

**Comment by Reflex18** [comment]
It will be very hard to support any additional changes to HOG since it has already been buffed by a factor of four times the amount for its net powergen/t

https://github.com/GTNewHorizons/GT5-Unofficial/pull/2762

**Comment by dimazha** [comment]
I've been thinking recently about HOG balance and how to make it better and remembered that almost all dieselgens IRL are two-stroke engines. So you need to mix fuel with engine oil. There is a moment where progression can be added. Prgression of fuel mixtures which will need to be filled into the Combustion Engine instead of fuel. For example: 

1 lvl – just fuel
2 lvl – fuel + engine oil (+20% fuel efficiency)
3 lvl – fuel + engine oil + NO2 (+40% fuel efficiency)
4 lvl – fuel + engine oil + smth else (+60% fuel efficiency)

Numbers are random, I wrote it only to show the idea. Use fuel mixtures instead of just fuel

**Comment by Steelux8** [comment]
I've already buffed HOG extensively. The ECE is in a bad state, but I didn't want to try to buff it even more to salvage it, since it seems like an old, outdated generator in the first place when compared to the UCFE.

**Comment by Zenovis** [comment]
> I've already buffed HOG extensively. The ECE is in a bad state, but I didn't want to try to buff it even more to salvage it, since it seems like an old, outdated generator in the first place when compared to the UCFE.

Why not buff it and make it usable? the LCE is already old and outdated as well, but despite that it's a major milestone in oil processing. Compared to gas turbines both the LCE and ECE are more work to set up. It's still a decent stepping stone to the UCFE, since that also requires more processing and ideally an automated chem plant to get set up, and will effectively almost always have less efficiency than ECEs with the benefit of producing much more power and needing less generator spam.

**Comment by Steelux8** [comment]
I'm not thinking of buffing the LCE or ECE because they're old, basic and honestly outdated multis. The ECE especially has no place in progression after the appearance and balancing of the UCFE, which uses Titanium just like the LCE and increases complexity in order to give the big reward of limitless throughput.

The way I would like to do this is to make the LCE a mini-UCFE, simpler and smaller and with a much smaller throughput, to escalate to the UCFE itself, while the ECE would be deprecated.

**Comment by chochem** [comment]
has gotten a clear reply. 2.7 has a massive buff.
