### ISSUE TITLE
Rare Earth I, II, and III, don't properly show all ore processing lines in NEI diagram

### ISSUE THREAD

**Issue by DarkYuan** [GTNewHorizons/GT-New-Horizons-Modpack#17743]
### Your GTNH Discord Username

DarkYuan#5002

### Your Pack Version

2.6.1

### Your Proposal

For some reason, the thermal centrifuge path doesn't show up on this diagram where it's supposed to be
![image](https://github.com/user-attachments/assets/6108ee17-3bee-483c-8c1b-1469eb2d4336)

### Your Goal

It's important to know all the options to process something

### Your Vision

Seeing another path to get Yttrium from RE1, for example

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Alexdoru** [comment]
duplicate : https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17537

**Comment by DarkYuan** [comment]
Ah, my mistake. I only searched the issue tracker for rare earth, didn't find that one.

**Comment by Alexdoru** [comment]
np
