### ISSUE TITLE
Server failure after updating from 2.6.1 to 2.7.0 nightly build 708

### ISSUE THREAD

**Issue by bricklayer25** [GTNewHorizons/GT-New-Horizons-Modpack#17768]
### Your GTNH Discord Username

proudpolitician

### Your Pack Version

2.7.0 nightly 708

### Your Server

SP

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

After following steps to update the server in https://gtnh.miraheze.org/wiki/Server_Setup#Server_Files, and attempting to start the server results in a very early crash.  Updating from 2.6.1 server to 2.7.0 nightly build 708. The only logs created every time the server crashes are an updated fml-server-latest and fml-junk-earlystartup.

Regarding the checkbox about asking other people, nobody seems to have tried the same thing as me, and people are not answering in discord.

### Crash Report

[fml-server-latest.log](https://github.com/user-attachments/files/17530713/fml-server-latest.log)
[fml-junk-earlystartup.log](https://github.com/user-attachments/files/17530714/fml-junk-earlystartup.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment]
you said that you are using java 8 but your java version is `Java is OpenJDK 64-Bit Server VM, version 17.0.12`. Either install GTNH for java 8 properly or install GTNH for modern java properly by using the correct java args as well as an appriopriate java distribution
