### ISSUE TITLE
Shadow Iron/Shadow Steel recipes conflict

### ISSUE THREAD

**Issue by dimazha** [GTNewHorizons/GT-New-Horizons-Modpack#17784]
### Your GTNH Discord Username

Dart_Voider

### Your Pack Version

2.7.0-nightly-700

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Trying to craft Shadow Steel in main autocrafting MEBF

### The Reality

Shadow Iron and Shadow Steel recipes have the same config circuit, so instead of Shadow Steel I receive Shadow Iron. Moreover I can't use main MEBF for Shadow Steel crafting, I need to have a separate MEBF for Shadow Steel recipe
![image](https://github.com/user-attachments/assets/89abdb66-f556-4654-ba2b-2fe944d568aa)

### Your Proposal

Change Shadow Steel config circuit from 11 to 1

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
the fluids are different so they dont conflict.

**Comment by Nockyx** [comment]
> the fluids are different so they dont conflict.

an ebf setup usually has the fluids stocked in the hatches of the multiblock instead of sent into patterns with blocking mode, so it often uses the different fluid, for this recipe, without bribuffer, in specific you ususally need to pattern in a different ebf or with a different setup than all the other patterns, or manually batch it. otherwise it will "conflict"

**Comment by chochem** [comment]
a problem with a setup is not a bug in the game

**Comment by Nockyx** [comment]
it's not a bug, but it could be changed to not cause issues 👍

**Comment by evgengoldwar** [comment]
> a problem with a setup is not a bug in the game

It is worth playing the game to begin with to say what is a bug and what is a problem with the setup

**Comment by chochem** [comment]
> > a problem with a setup is not a bug in the game
> 
> It is worth playing the game to begin with to say what is a bug and what is a problem with the setup

you should really start doing so yea. its great
