### ISSUE TITLE
Twilight Forest contains Manganese vein

### ISSUE THREAD

**Issue by StaffiX** [GTNewHorizons/GT-New-Horizons-Modpack#17788]
### Your GTNH Discord Username

StaffiX

### Your Pack Version

Nightly 715

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Not having manganese veins in Twilight Forest

### The Reality

![image](https://github.com/user-attachments/assets/91641af0-679e-42fa-a731-22a8e6710795)
![2024-10-28_22 46 19](https://github.com/user-attachments/assets/c09ebc4e-fa79-4ac1-9235-ba57c55690aa)
Twilight Forest contains Manganese vein according to VisualProspect and actual worldgen

But according to NEI, it doesn't generate there, and I'm quite sure it isn't actually supposed to be
![image](https://github.com/user-attachments/assets/3689d150-3b15-478a-a106-ffc87b6c8139)

### Your Proposal

Remove Manganese veins from Twilight Forest

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miklebe** [comment]
![image](https://github.com/user-attachments/assets/c43a8a03-ba5d-412e-8d6d-e27f16dcfa94)
Basaltic sand spawns above y50, so it's rare to find in TF, but somehow it's still being generated there.

**Comment by StaffiX** [comment]
It looks like every single OW vein got added to Twilight Forest, lot of them just doesn't appear due to height
