### ISSUE TITLE
Crash due to "Unkown" mod when creating a Single Player world

### ISSUE THREAD

**Issue by C-A-T-T** [GTNewHorizons/GT-New-Horizons-Modpack#17781]
### Your GTNH Discord Username

c.a.t.t.

### Your Pack Version

2.6.1 (2024-05-20)

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I use GDLauncher.

Opened GDL
Download GT:NH
Launch GT:NH
Create a New Single Player World
Loading Reaches 0%
Crash
![Screenshot 2024-10-27 160714](https://github.com/user-attachments/assets/8e524613-e8b3-4686-8b15-4b577230829c)

### Crash Report

https://mclo.gs/gTz8wUT

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by C-A-T-T** [comment]
Also, please, note that this is my third attempt at getting this to work.

**Comment by hiroscho** [comment]
May help you: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16310#issuecomment-2143643868

**Comment by lordIcocain** [comment]
same when i delete angelica from mods

**Comment by C-A-T-T** [comment]
> May help you: [#16310 (comment)](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16310#issuecomment-2143643868)

I'm going to download a couple of other Mod Loaders to see if that works.

**Comment by C-A-T-T** [comment]
> same when i delete angelica from mods

Deleting Angelica worked, Thank you.
