### ISSUE TITLE
Update Info Text "LuV Laser Engraver"

### ISSUE THREAD

**Issue by Fr4rrow** [GTNewHorizons/GT-New-Horizons-Modpack#17796]
### Your Pack Version

2.7.0 Beta 3

### Your Proposal

Change LPF (Large Processing Factory) to Hyper_Intensity laser Engraver

### Your Goal

game experience

### Your Vision

game experience

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
LPF is deprecated and this doesnt make any sense anyway

**Comment by Nockyx** [comment]
> LPF is deprecated and this doesnt make any sense anyway

I think this issue is referring to the questbook

**Comment by Baerschen** [comment]
Yeah there are some mentions of it in quests still. I will take care of them tough!

**Comment by Baerschen** [comment]
he was def talking about this 
![image](https://github.com/user-attachments/assets/c88a50a6-84aa-4194-b031-dd21f9bf4bf0)
