### ISSUE TITLE
Java IO: Packet was larger then i execpted, found x bytes extra whilst reading packet 53

### ISSUE THREAD

**Issue by mamiemru** [GTNewHorizons/GT-New-Horizons-Modpack#17793]
### Your GTNH Discord Username

mamiemru

### Your Pack Version

2.5.1

### Your Server

private hosted server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

When i don't use "data sticks" and "ae crafting patterns" on my assembling lines, i put those in a compressed chest from avaritia.
My expectation is to store all items in the chest and don't make any issues when i load the chunk.

here, the content of the two chests:

With all unused AE crafting patterns
![aepatterns](https://github.com/user-attachments/assets/0a9ab63b-7305-42ef-9ff7-7d6dc878a4c4)

With all unused datasticks
![datastick](https://github.com/user-attachments/assets/6bfe0df9-6128-45e4-b24d-47b00b127c02)

### The Reality

The issues is this

![image](https://github.com/user-attachments/assets/dcfd07ce-0d6a-4b6d-92cd-c7a3b589fb3c)

it doesn't append in single player, it only append in hosted server and local server (using server.jar).
My conclusion is this happens when the game has some network stuff to do.

My steps to find the issue:
- I download a world.zip from the hosted server
- I loaded my world in local server with 2gb ram to make it loading chunks slow then i traveled my base chunk by chunk until i got disconnected with the message above, now i have the area
- I opened mc edit2 and pick the coordinates of when i was when the game disconnect me.
- I remind of actions i have done in this region (0-1.mca).
- I deletes some blocks in single players and/or with mcedit until i found those 2 chests.
- I opened mcedit in order to delete the tile entity of those 2 chests.
- I loaded the local server and it works fine, but the 2 chests was empty now.

Steps to fix my world:
- i loaded a fresh unzipped world in my local server.
- with mcedit i have deleted the 2 chests tile entities.
- i start the local server.
- everything works fine.

I have an other compressed chest filled with AE crafting patterns, and i never has any problems with this chest, so i think the issue come from the datastick chest, the last time i was filling it up it was to put the 3 last rows.

### Your Proposal

My proposal, in term of code or network, i don't know,
but in term of gaming, put those things in regular chest or limit theirs number in a single chest may fix the issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
It is called chunkban, also fixed on newest GTNH versions. 2.5.1 pretty old, try 2.6.1 (newest stable).

**Comment by Ruling-0** [comment]
Should indeed be fixed on 2.6.1+. Issue is that it tries to send too large a packet for that chunk due to item data. Hodgepodge now has a value in its config to control this (and the default value was increased 128x).
