### ISSUE TITLE
TGS can't copy TF sapligns

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#17806]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.7.0 beta 3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

I put grafter and robust twilight oak sapling in TGS, I get more robust oak saplings.

### The Reality

Sickly twilight oak saps came out 
![image](https://github.com/user-attachments/assets/bd3ae9af-3855-46b7-be10-832ad7074625)

### Your Proposal

Fix? It prob has to do with not respecting meta id or smth.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
Working as intended. The Robust sapling is supposed to be very rare, and even growing it manually only drops Sickly saplings, not Robust ones.

**Comment by LazyFleshWasTaken** [comment]
Fair enough.
