### ISSUE TITLE
Receiving Warp Effects With No Warp

### ISSUE THREAD

**Issue by EthanHand** [GTNewHorizons/GT-New-Horizons-Modpack#17816]
### Your GTNH Discord Username

newpacket

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Open To LAN

### Your Expectation

No constant fake mobs.

### The Reality

I hear fake explosion sounds often and just thought it was a consequence of eating a zombie brain early on in my playthrough but it has gotten worse and I now see fake mobs constantly (up to three at a time) and one of them doesn't seem to leave. I sat in the sauna for warp ward and nothing changed. I used a warp litmus paper and I have 0 of all types of warp (see screenshot).
![FakeSpiders](https://github.com/user-attachments/assets/58a14afd-98e4-446a-81a1-5b8a04a4e737)

I have tried rejoining the server and restarting it and nothing has changed.

### Your Proposal

Temporarily disable warp effects

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you can absolutely have warp effects queued up still while having 0 warp. but you say its been a long time already? any warping gear?

this is gonna be hard to do anything about without any way to reproduce it.

**Comment by EthanHand** [comment]
It turns out that after I deleted my character a few days later my resident magic expert informed me he had cursed me with insanity. This is not a bug.
