### ISSUE TITLE
Recipe conflict for Raw Cinnabar Ore in Crucible

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/GT-New-Horizons-Modpack#17825]
### Your GTNH Discord Username

alongstringofnumbers

### Your Pack Version

 Nightly 718

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

No warning about recipe conflict

### The Reality

When starting a server, the following warning is printed about a recipe conflict

```
[17:14:04] [Server thread/WARN] [FindCrucibleRecipe]: Recipe CrucibleRecipe{key=PURECINNABAR,catalyst=[1xgt.metaitem.03@5826],output=1xitem.ItemNugget@21,aspects=1xMetallum;1xOrdo} ignored due to collision with CrucibleRecipe{key=PURECINNABAR,catalyst=[1xtile.blockCustomOre@0, 1xgt.blockores@826],output=1xitem.ItemNugget@21,aspects=1xMetallum;1xOrdo} for hash 2098103745
```

### Your Proposal

No conflicting recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I dont get anything in the log but yea I do see the recipe conflict
![image](https://github.com/user-attachments/assets/e722fc91-9fe8-4375-8d4f-5db1ee61f898)
![image](https://github.com/user-attachments/assets/0023b07d-ef96-47dc-8658-7b62211a6e1e)

**Comment by chochem** [comment]
@Ethryan it looks like you added both recipes. so I guess you gotta to decide which one you want more :P

**Comment by Ethryan** [comment]
On it… Tomorrow…
