### ISSUE TITLE
Soul brazier acts as an admin anchor

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#17832]
It would be cool if it was configurable, so i don't end up digging in files to guess what perma load the dims on the officials...

**Comment by AbdielKavash** [comment]
A config for this already exists, however it defaults to true (chunkloading enabled).

Note that if you change the config from true to false, existing braziers continue chunkloading, and need to be broken and replaced (or at least run out of cvis) for the new config to take effect.

**Comment by boubou19** [comment]
Ah that's annoying, because it means i need to parse all the forcedchunks.dat on all the servers to spot them all and break them all. Can't we just make it so it removes itself from the forcedchunks when config is false? with this it's fixed in 2 reboots.

**Comment by AbdielKavash** [comment]
> Can't we just make it so it removes itself from the forcedchunks when config is false?

Sure, I can try, give me a bit.
