### ISSUE TITLE
Add info about blackhole stability and lifetime

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17834]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.7.0 beta 3

### Your Proposal

Add info to scanner or waila about blackhole stability and its lifetime after it became unstable.
Or add lifetime in tooltip if it is constant.

### Your Goal

Info about stability is needed to insert spacetime at correct time (now you can guess stability only by blackhole texture or parallels).
Info about lifetime can be needed if player wants not to close blackhole with collapser, but to use something like timer.

### Your Vision

These suggestions are small qol features for this multi.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by StaffiX** [comment]
Adding stability to scanner means with Opencomputer, it's way easier to automate the compressor than without.
While it's still easier with OC, to not futher encourage OC automation, it's intentionally not displayed there

https://github.com/GTNewHorizons/GT5-Unofficial/pull/3215
Waila stability has been removed by Boubou's request, you can read the discussion here https://discord.com/channels/181078474394566657/522098956491030558/1285559596869750816

Tooltip states the lifetime, just not the most direct way
"It starts from 100 and decreases by 1 every second, and decays 25% slower while running recipes"
