### ISSUE TITLE
Artificial universe storage recipe accepts uncharged battery

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17855]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.7.0 beta 3

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Only fully charged battery can be accepted for recipe.

### The Reality

Artificial universe storage recipe accepts uncharged battery despite only fully charged required:
![image](https://github.com/user-attachments/assets/23328ce2-72be-4dc3-afa0-412c074d92b2)

### Your Proposal

Fix space assembler ignoring nbt (?)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
space assembler has no method currently to use nbt from what I can see and sadly does not use ra2
