### ISSUE TITLE
AE2. Crafted fluid registering twice in crafting queue.

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#17853]
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.7.0-beta-3

### Your Server

ps

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Request 1000 drops of fluid. Machine did 500, crafting queue registered 500 and wait next 500.

### The Reality

crafting queue registered 1000, craft done.

### Your Proposal

Yes please

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Vlamonster** [comment]
This issue occurs after 2.6.1.

**Comment by Vlamonster** [comment]
It seems related to the presence of a discretizer in the system. Without a discretizer the expected number of items are registered for requested crafts. This PR might be related to this issue: https://github.com/GTNewHorizons/AE2FluidCraft-Rework/pull/225.

**Comment by Demiu** [comment]
Yea the problem is from that PR, there is both the CraftingGridCacheFluidInventoryProxyCell and the fluid discretizer's fluid crafting inventory do the same thing of registering inserted fluids as droplets in CPUs. The Proxy is more flexible (always works, no need for discretizer, is not a fake inventory), so the fluid crafting inventory should be removed IMO

**Comment by lordIcocain** [comment]
@Demiu Can make pr?
