### ISSUE TITLE
Removal of ultra dense me conduit 

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#17869]
### Your GTNH Discord Username

Lord Peverell

### Your Pack Version

Nightly 687

### Your Proposal

Remove the EIO ultra dense conduit as this was the EIO equivalent of the backbone cable

Also why do we still have the eio me conduits craftable? From what I’ve seen they’re extremely buggy and a lot cheaper than standard ae cables that got changed by dream a while ago 

### Your Goal

Removal of the ultra dense conduit 

### Your Vision

Removal of ultra dense conduit 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by AbdielKavash** [comment]
> Also why do we still have the eio me conduits craftable? From what I’ve seen they’re extremely buggy

Do you have anything reproducible? I never had any issues using them. Admittedly I haven't used them at a massive scale either; but definitely more than never.

**Comment by joshaup1999** [comment]
Admittedly I haven’t used them in years. But  making them with a large networks caused them to corrupt the world

**Comment by AbdielKavash** [comment]
If this is at all possible, I would rather see them fixed and possibly rebalanced; rather than just out right removed. They still have place in some very compact setups.

(I agree that backbones should go, just talking about regular/dense conduits.)
