### ISSUE TITLE
Ender fluid link cover crashing client when toggling private mode

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#17863]
### Your GTNH Discord Username

skproch

### Your Pack Version

2.7.0-beta3

### Your Server

private

### Java Version

Java 21

### Type of Server

Ultramine

### Your Actions

When i toggle ender fluid link cover on output hatch while being in space station i get client crash handled by better crashes. Server doesn't crash, private mode doesn't became toggled.

### Crash Report

[crash-2024-11-05_18.36.16-client.txt](https://github.com/user-attachments/files/17635033/crash-2024-11-05_18.36.16-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ngar1** [comment]
It is not solved in 2.7 RC1

https://mclo.gs/4pv95ZA
