### ISSUE TITLE
Advanced Gas turbine

### ISSUE THREAD

**Issue by wotikama** [GTNewHorizons/GT-New-Horizons-Modpack#17861]
### Your GTNH Discord Username

wotikama

### Your Pack Version

2.7.0-beta-3

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Open To LAN

### Your Expectation

The advanced large gas turbine cant accept benzene or any gas below 800.000eu

### The Reality

The Large Advanced Gas Turbine (the small red one, which no one makes) works with benzene even tho its tooltip says only gases above 800.000eu. This is quite OP but at the same time no one makes them because of xlgt.

### Your Proposal

Remove the limitations because its a forgotten multi but with this people maybe see a usage. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
@Steelux8 do you know what the current plan for this machine is and what we should do here?
