### ISSUE TITLE
Electric/nano/quantum boots of the voidwalker/meteor/comet should be able to upgrade

### ISSUE THREAD

**Issue by truenachtara** [GTNewHorizons/GT-New-Horizons-Modpack#17866]
### Your Pack Version

2.7.0-beta3

### Your Proposal

"Combined" electric thaumic boots should be able to upgrade to the next tier the same way the non-combined boots can.
![image](https://github.com/user-attachments/assets/ffc0d2c7-20bd-44fd-b16a-f21d99a5d432)
![image](https://github.com/user-attachments/assets/c1b444d4-f71f-4b68-ba8a-caa8c7b2686a)

### Your Goal

If you crafted, say, the Electric boots and then want Nano later you can just upgrade. If you instead made the Electric Boots of the Voidwalker, and then you want to upgrade to Nano, you'd have to make a completely new set of each base boot and combine later- and god help you if you want to make quantum in IV!

### Your Vision

This would simply reduce material cost and remaking gear solely to get an upgrade.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Nockyx** [comment]
I have a WIP branch to add this, i'll probably get back to it soon.
