### ISSUE TITLE
Barnada C Bee Crashing Server and in SP

### ISSUE THREAD

**Issue by duckedddd** [GTNewHorizons/GT-New-Horizons-Modpack#17876]
### Your GTNH Discord Username

dukced

### Your Pack Version

2.7.0 Beta-3

### Your Server

Private, and SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

To replicate:
- Obtain a Barnada C Bee
- Acclimatize it to the specific environment
- Put it in an apiary so it can work
- Instant crash of server / SP world

### Crash Report

https://mclo.gs/u4J070W

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
seems to be caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2507
