### ISSUE TITLE
Change "Warp warnings" quest to include that friendly creepers can spawn infernal and blow up stuff

### ISSUE THREAD

**Issue by qunYp3dZSyLjoEoEg** [GTNewHorizons/GT-New-Horizons-Modpack#17873]
### Your Pack Version

2.6.1

### Your Proposal

Add a bracket to the quest AAAAAAAAAAAAAAAAAAAG8g==, in which the warp warning are explained, right next to the friendly creeper effect at 40 warp, that friendly creepers can spawn infernal and just suddenly explode , even though they usually are friendly. [Note: Friendly creepers can spawn infernal in ways that make them explode when near you and destroy blocks/items]. 

### Your Goal

Bcs without it unknowing players are kinda led to believe that they won't ever explode unless manually flinted or otherwise ignited if they never ask in a discord or someone that does know that, which why would they, and a "friendly" creeper that suddenly spawned can destroy quite a lot of items. 

### Your Vision

It would give players who may not ask about every little thing (especially when you have a otherwise rather thorough quest) or might not be able to ask about these kinda things more information, and is a very small and easy change.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by qunYp3dZSyLjoEoEg** [comment]
As for a recollection of the events, I was looking down to open the filing cabinet for my seeds or chest, saw a creeper dropping from the sky suddenly, first reaction was ah shit, second reaction was oh ok it is a friendly creeper anyway, and then it just suddenly exploded completely eliminating the filing cabinet and its contents

**Comment by chochem** [comment]
I think the modifier is berserk. but I also think we changed this 5 years ago and I havent heard of any case of this happening since.

**Comment by chochem** [comment]
ah here we go: familiar author lol <https://github.com/GTNewHorizons/Infernal-Mobs/pull/1> 

hmm maybe not beserk though, the repo says its double damage. It probably just exploded naturally then. They certainly used to throw negative potions and ghast fireballs before. XD

the only thing I can think of after reading all that is that maybe they lost 'neutral' status because you punched them or because they took damage in some other way. I dont know if that actually changes their status but that would make sense to me.

**Comment by qunYp3dZSyLjoEoEg** [comment]
Well it's the only possibility of why the creeper could explode for me I have heard. If it's something else then I'm sorry, but I have killed punched theses friendly creepers to death without exploding, and in a singleplayer world I also tested whether normal creepers would explode when exposed to a steam pippe since an exposed steam pipe was right by. And they didn't. Maybe there is some infernal status that makes them explode when they touch an exposed steam pipe?

**Comment by chochem** [comment]
anyway, what we are saying is that its not intended that these go and harm you, so if the modifier and circumstances can be figured out, it should be fixed, not documented.

**Comment by qunYp3dZSyLjoEoEg** [comment]
Okay thanks a lot ^^!. In that  case I'm just happy to have reported the issue.

**Comment by wlhlm** [comment]
`@Toperoco` on Discord mentioned a similar case: https://discord.com/channels/181078474394566657/401118216228831252/1303821401450352804

> this happened on my server, in case you guys want to look into it

> Prism logs say "creeper blew up" so it might be something else. The thing about it being an infernal with e.g. ghastly was just an idea I threw around in the discussion with the player

Hmm, looks more like the Creeper blew itself up. Maybe there's some weird interaction here...

**Comment by wlhlm** [comment]
I think I found the problem: WarpTheory actually provides to types of Warp Creepers: "Passive Creeper" and "Fake Creeper". The former will actually do nothing, but the latter can actually blow up like a normal creeper, it's just that it's explosion will do no damage to player and world. Passive Creepers are actually [excluded](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/a852704fdc4d126a2f79061dabacc6264fb9e341/config/InfernalMobs.cfg#L180) from receiving infernal modifiers, so in the reports above, it seems like it was actually Fake Creepers that were spawned as those are currently allowed to receive infernal modifiers. Modifiers on Fake Creepers actually behave like on normal Creepers, so for example Blinding or Sapper will still apply to the player.

Seeing as Passive Creepers are currently exempt from infernal status, it makes sense to do the same for Fake Creepers.

**Comment by Ethryan** [comment]
> I think I found the problem: WarpTheory actually provides two types of Warp Creepers: "Passive Creeper" and "Fake Creeper". The former will actually do nothing, but the latter can actually blow up like a normal creeper, it's just that it's explosion will do no damage to player and world. Passive Creepers are actually [excluded](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/a852704fdc4d126a2f79061dabacc6264fb9e341/config/InfernalMobs.cfg#L180) from receiving infernal modifiers, so in the reports above, it seems like it was actually Fake Creepers that were spawned as those are currently allowed to receive infernal modifiers. Modifiers on Fake Creepers actually behave like on normal Creepers, so for example Blinding or Sapper will still apply to the player.
> 
> Seeing as Passive Creepers are currently exempt from infernal status, it makes sense to do the same for Fake Creepers.

Is probably this one in the list https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/a852704fdc4d126a2f79061dabacc6264fb9e341/config/InfernalMobs.cfg#L1015

**Comment by qunYp3dZSyLjoEoEg** [comment]
Just wanted to add that I recently had 3 creepers from warp explode & damage blocks without being infernal, at least as far as I could tell. They didn't have the bubbles effect or the health bar at the top that is usual for infernal mobs.

**Comment by qunYp3dZSyLjoEoEg** [comment]
![image](https://github.com/user-attachments/assets/537b9224-ca56-4bab-8469-40e03e7499d7)
Friendly creepers still seem to be able to get infernal effects, happened in my pdim
