### ISSUE TITLE
High Energy Laser Purification Unit wrong NEI Multiblock Structure

### ISSUE THREAD

**Issue by Yoshy2002** [GTNewHorizons/GT-New-Horizons-Modpack#17871]
### Your GTNH Discord Username

yoshy1952

### Your Pack Version

Nightly 719

### Your Server

private Server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Correct Items for Multiblock Structure shown in NEI for HEL Purification Unit.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17752 had this Issue in it, got marked as completed
"High Energy Laser -
Mentions 24 High Energy Ultraviolet casings, should be 29
NEI structure preview also has 2 lens housings instead of 1 indicator"

but only 
- Mentions 24 High Energy Ultraviolet casings, should be 29
got fixxed.

### The Reality

NEI shows 2 Lens Housings instead of 1 Lens Housing and 1 Lens Indicator. Multiblock wont form with the Structure shown in NEI until you replace the Housing in the back with an Indicator.
![image](https://github.com/user-attachments/assets/2dcf68e8-ccd5-417d-8e79-867c1e5af3b6)

### Your Proposal

Fix the NEI Structure Preview to match the Multiblock Tooltip.
![image](https://github.com/user-attachments/assets/9d0f0b03-7ede-411f-8f0e-d4dee22db9ee)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ruling-0** [comment]
Issue still exists on Nightly 727
