### ISSUE TITLE
Pollen Collection Kit Crashes Client from Server and World on SP

### ISSUE THREAD

**Issue by duckedddd** [GTNewHorizons/GT-New-Horizons-Modpack#17877]
### Your GTNH Discord Username

dukced

### Your Pack Version

2.7.0 Beta-3

### Your Server

Private, and SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

To Replicate:
- Obtain Pollen Collection Kit
- Obtain Apple Oak Leaves
- Use Pollen Collection Kit on the Leaves for Pollen
- Game instantly crashes

### Crash Report

https://mclo.gs/ivaozlX

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
works fine for me 
![image](https://github.com/user-attachments/assets/af9b2236-e495-4664-8623-89c9e978b357)
