### ISSUE TITLE
ETF Purification Unit wrong NEI Multiblock Structure

### ISSUE THREAD

**Issue by Yoshy2002** [GTNewHorizons/GT-New-Horizons-Modpack#17884]
### Your GTNH Discord Username

yoshy1952

### Your Pack Version

Nightly 719

### Your Server

private Server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

The NEI Multiblock Structure showing the correct/possible Places for each Input Hatch.

### The Reality

NEI only shows 2 out of the 3 Necessary Input Hatches in the Preview.
![image](https://github.com/user-attachments/assets/9db1ebb8-5339-452f-b2ac-f915814c2f4d)

### Your Proposal

Add the 3rd Input Hatch (Plasma) like shown in the Structure Preview at the 3-Dot Spot, without which the Multiblock does not form:
![image](https://github.com/user-attachments/assets/9445bfea-8836-4c40-9cbc-c07838b839d9)
![image](https://github.com/user-attachments/assets/6a429778-b367-46be-a609-44e1271ece88)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ruling-0** [comment]
Still missing on nightly 727
