### ISSUE TITLE
Pollution Detection Device doesn't exist.

### ISSUE THREAD

**Issue by ilov3gam3z** [GTNewHorizons/GT-New-Horizons-Modpack#17885]
### Your Pack Version

2.6.1 (whatever the newest stable version is)

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Obtaining a PDD to check pollution levels in my base, since my crops are beside my machines and i don't want any issues.

### The Reality

The Pollution Detection Device doesn't exist, anywhere. I looked through every GT: New Horizons recipe in NEI as well as every GregTech recipe. Nothing. Cant find anything in the quest book either. The only video that contains it on the internet says its called "Pollution Detection Device" I searched that, as well as "Pollution", and there doesn't seem to be any PDD in the game.

### Your Proposal

Bring back the PDD or make a new machine for LV to see pollution.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
Have you disabled pollution in your config? That also removes recipes for most pollution-related utilities.

**Comment by chochem** [comment]
yea probably that. either way, the pollution detection device is very much around in nightlies
![image](https://github.com/user-attachments/assets/e67c0b84-7119-4926-9504-61473480a033)

**Comment by ilov3gam3z** [comment]
ah accidentally removed pollution cause i thought it was a weird mechanic when i started the game, welp ima put it back and craft it.
