### ISSUE TITLE
YotHatch crash over night

### ISSUE THREAD

**Issue by Starkewe** [GTNewHorizons/GT-New-Horizons-Modpack#17896]
### Your GTNH Discord Username

Starkewe

### Your Pack Version

2.7 Beta 3

### Your Server

Private Server

### Java Version

Other versions in between

### Type of Server

Don't know

### Your Actions

Running a private server through MMC on Java 23.0.1.

There was no one on the server at the time of the crash and the server does not boot up without a backup.

It looks like the crash is related to the Yothatch which I recently setup for my Yottank. It has a fluid storage bus and a fluid detector cover on it which isn't fully setup yet.

I can't fully duplicate this issue without the crashing world save, which if necessary I can provide.

![2024-11-07_14 16 53](https://github.com/user-attachments/assets/76786e54-e063-4fb5-a327-f5183527d1f1)

[crash-2024-11-07_13.40.53-server.txt](https://github.com/user-attachments/files/17672023/crash-2024-11-07_13.40.53-server.txt)

```
### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Pxx500** [comment]
Please add log as a file/link not as a text next time

**Comment by Starkewe** [comment]
Further inspection into the issue points to the yottank running dry. Recently had the crash again and used a backup. The tank was draining pretty quick and about to empty out.

**Comment by Ruling-0** [comment]
Crash occurs when storage bussing an Yothatch on empty yottank

@Starkewe in the interim, you don't need the storage bus - you can directly connect AE to the yothatch
