### ISSUE TITLE
Infusion altar suddenly stops working

### ISSUE THREAD

**Issue by Rakdarian** [GTNewHorizons/GT-New-Horizons-Modpack#17901]
### Your GTNH Discord Username

Rakdarian#7628

### Your Pack Version

2.7.0 beta 2

### Your Server

sp

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Trying to perform an infusion recipe, any infusion recipe

### The Reality

Attempting to activate the infusion altar doesnt accomplish anything, as though items are missing from the recipe.

### Your Proposal

stop the bug that prevents the infusion altar from activating

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Give a specific example please. Many infusion recipes claim to accept oredict items in nei but do not. The altar itself should work, as this would be a very high profile bug and no changes have (or easily can) be made to the infusion altar.

**Comment by Ruling-0** [comment]
Saw in help they were trying to craft an ethereal shard (https://discord.com/channels/181078474394566657/234936569360809996/1304265963444633641), tested and working on Nightly 727. Ensure you have the required research and essentia in range.

![image](https://github.com/user-attachments/assets/304aa6ed-3f28-483a-812e-875d8c52b573)

**Comment by Rakdarian** [comment]
Im very foolish. The issue was that the ancient pedestal counts as a pedestal for this, ancient pedestals are needed to feed the essentia condensor elements of darkness, i left one in there when it was fully upgraded as decoration.
