### ISSUE TITLE
Can't craft attuned Gadomancy Aura Core

### ISSUE THREAD

**Issue by Maxhy21** [GTNewHorizons/GT-New-Horizons-Modpack#17903]
### Your GTNH Discord Username

largerthan2#3231

### Your Pack Version

2.6.1

### Your Server

Whitelisted community

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Tuning Gadomancy Aura Core to any primal aspect.
![image](https://github.com/user-attachments/assets/d0d21a2a-21a3-45f0-81d1-a2a32ebffaa9)
Expecting an Aura Core attuned to the aspect of the cluster used.

### The Reality

Only got Terra Aura Core, no matter what is used
![image](https://github.com/user-attachments/assets/6d973866-96ab-4adf-91cb-75ce086abf79)

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ruling-0** [comment]
This is not how aura core functions, though you are not the first person to be confused by that. It depends on the aspects of all blocks in _some_ radius, of which the primal shard is just one. Crafting over a large body of water, for example, produces an aqua core.

![image](https://github.com/user-attachments/assets/c9eaafbd-190f-4ab1-b542-220c33ca5498)
