### ISSUE TITLE
Wrong nether star cable recipe

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17928]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Nether star cable (UIV tier) can be insulated only with silicone or styrene-butadiene rubber.

### The Reality

Nether star cable can be insulated with basic rubber:
![image](https://github.com/user-attachments/assets/16781d28-5dda-438c-93dc-4da5cf97952e)

### Your Proposal

Delete recipes with basic rubber.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
was fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/3055
