### ISSUE TITLE
Increase open block elevator range

### ISSUE THREAD

**Issue by Ciubix8513** [GTNewHorizons/GT-New-Horizons-Modpack#17929]
### Your Pack Version

2.6.0

### Your Proposal

Increase elevator vertical range

### Your Goal

The current elevator range allows for floors to be only ~16 blocks tall, if you want  your floors to be bigger you need to add intermidiate elveators, which is incredibly annoying. Increasing that range will make bigger, buildings less of a pain to navigate

### Your Vision

Increase elevator range to be more than 16 blocks, potentially infinite

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
It is 20, both in GTNH and outside. And as you point out you can chain them (not sure what annoys you there, never seemed like a problem to me), so I dont think there is any desire to change this.

There is a config though you can adjust if you think this is absolutely necessary for your own game.
