### ISSUE TITLE
Blood Altar has no NEI Recipe Usages

### ISSUE THREAD

**Issue by Yoshy2002** [GTNewHorizons/GT-New-Horizons-Modpack#17949]
### Your GTNH Discord Username

yoshy1952

### Your Pack Version

Nightly 732

### Your Server

private Server/SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

NEI showing every possible Recipe in the Blood Altar.

### The Reality

NEi not showing a single Recipe that you can perform in the Blood Altar. 
"Usage" of Blood Altar:
![image](https://github.com/user-attachments/assets/9911c574-10b2-480e-af61-2537395ea90e)
Recipe of T1 Slates(No Blood Altar Recipe at the Top):
![image](https://github.com/user-attachments/assets/3b9fad1e-a4f4-4814-b2e0-5f1bc566b9c0)

### Your Proposal

Fix NEI to show the Recipes again. This happened somewhere between Nightly 719 and 732, everything worked fine on 719.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Yoshy2002** [comment]
This also applies to the Alchemic Chemistry Set (Usage of it):
![image](https://github.com/user-attachments/assets/e24c7c0b-6132-4537-b24b-047cc9351581)
For example, recipes of Aether:
![image](https://github.com/user-attachments/assets/6d12ebb5-b2c5-4cac-a603-f77cc92c0b59)

**Comment by chochem** [comment]
can you post your logs? there might be some errors in there that indicate whats wrong.

**Comment by Yoshy2002** [comment]
Okay so it seems like the whole Problem is gone after restarting my game like half an hour ago. I cant explain how this could have happened(especially because every other recipe was functioning), but if you still want/need any logs, i can provide them. If not, you can just close the Ticket.

**Comment by chochem** [comment]
certainly looks fine in 2.7.0beta4. I am gonna close this for now. Let us know if the problem returns.
