### ISSUE TITLE
Vanadium Redox Power Cell (EV) only accepting Advanced Circuits

### ISSUE THREAD

**Issue by NobleKev** [GTNewHorizons/GT-New-Horizons-Modpack#17945]
### Your GTNH Discord Username

phoenixskykevin

### Your Pack Version

2.7.0-nightly-3

### Your Server

Private Server, SP

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

Crafting Vanadium Redox Power Cell (EV) with any HV Circuit

### The Reality

The Vanadium Redox Power Cell (EV) is only accepting Advanced Circuits
![image](https://github.com/user-attachments/assets/02459cbc-6249-499c-a66d-c4ba1be70ad2)

### Your Proposal

Change the Recipe to use any HV Circuit

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by RAFAEL-SOSA-UH** [comment]
Test it, in nightly 729, and this seems the only recipe that exclusively uses those HV circuits.
