### ISSUE TITLE
Make Multis with CRIBS/CRIBRs also work with Non-Consumables placed outside of them if the machine is not set to "Input Separation".

### ISSUE THREAD

**Issue by Speecker** [GTNewHorizons/GT-New-Horizons-Modpack#17946]
### Your GTNH Discord Username

Speecker

### Your Pack Version

Stable v2.6.1

### Your Proposal

As the title already says i noticed that CRIBS/CRIBRs only work if they have the Non-Consumable inside them.
As of now any Non-Consumable has to be placed inside correcponding CRIBS/CRIBRs and these are unaffected from the machines Input Separation setting.
it was apparent to me when setting up new Nano Forges and PCB Factories.
Nano Forges already have 8 different Non-Consumables but no conflicting recipes so far.

### Your Goal

Would be nice to be able to have machines also work with such Non-Consumables not placed inside the CRIB/CRIBR when the "Input Separation" button is explicitely set to allow using any Input Bus/Hatch - including CRIBS/CRIBRs.

### Your Vision

It should be possible for the user/player to decide if he wants to define a machine to work with any non-consumable placed in any of the machines inputs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
no, they are fully separated. They have internal slots for nonconsumables though.

**Comment by boubou19** [comment]
thing is the nanite must be in the controller to enable the next tier, so it's counter intuitive to add one more in the cribs, even tho it's intended to have cribs fully isolated. Idk how we should proceed to make this clear to the player.
