### ISSUE TITLE
new laser engraver multi accept non-borosilicate glass

### ISSUE THREAD

**Issue by brnaaaa** [GTNewHorizons/GT-New-Horizons-Modpack#17959]
### Your GTNH Discord Username

.barnac

### Your Pack Version

nightly 733

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

![изображение](https://github.com/user-attachments/assets/b80a47d1-3380-4210-ba5e-e8b7b0314969)
hyper-intensity laser engraver should accept only borosilicate glass

### The Reality

![изображение](https://github.com/user-attachments/assets/6a9d1997-33ee-4f8b-bc70-48cc5b581c30)
![изображение](https://github.com/user-attachments/assets/b46b4f97-3ef7-4cef-adff-949029ba2f98)
with managlass and thorium yttrium glass block laser engraver running fine

### Your Proposal

fix this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdielKavash** [comment]
There is as of right now no method to accept some types of glass and reject others of the same tier (despite what some comments in Bartworks' code indicate). We have had a discussion about whether this is something we want to support in the future, but the results were inconclusive.

**Comment by FourIsTheNumber** [comment]
I approve removing the tooltip and probably just switching to the standard glass method for this. If someone wants to clear it up before I get around to doing it myself, feel free.
