### ISSUE TITLE
Quest Rubber Soft Mallet

### ISSUE THREAD

**Issue by PostMoonPhos** [GTNewHorizons/GT-New-Horizons-Modpack#17958]
### Your GTNH Discord Username

ciel6

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

The quest Rubber Soft Mallet should not have been completed.

### The Reality

The quest Rubber Soft Mallet was completed instantly after completing the previous quest Wire-Wrap, despite me never crafting a Soft Mallet with rubber.

### Your Proposal

Fix the detection (idk)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment]
Maybe make it ask for a Mallet in your inventory, instead of just the materials for one?

**Comment by PostMoonPhos** [comment]
> Maybe make it ask for a Mallet (Any Kind) in your inventory, instead of just the materials for one?

The quest already asks to craft a rubber mallet

**Comment by chochem** [comment]
I tried, but can not reproduce this.

**Comment by Ethryan** [comment]
I think it remember the craft for the wooden mallet that is don during the earlier chapter.

**Comment by chochem** [comment]
ah yes that seems to be it
