### ISSUE TITLE
Steam Solar Boiler can no longer fill cells

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/GT-New-Horizons-Modpack#17966]
### Your GTNH Discord Username

alongstringofnumbers

### Your Pack Version

Nightly 718

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

On Nightly 592, you could insert cells into the `IN` slot of the GUI of the HP Solar Boiler to fill them with steam. On Nightly 718, you can no longer do so. I would expect this behavior to remain the same.

### The Reality

Cannot fill cells from GUI of HP Solar Boiler

### Your Proposal

Be able to fill cells from the GUI of the HP Solar Boiler

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by RAFAEL-SOSA-UH** [comment]
test it in nightly 729 and you can't put any type of cells, but when you right click it with a universal fluid cell it fills up.

**Comment by YannickMG** [comment]
That change is from https://github.com/GTNewHorizons/GT5-Unofficial/pull/2871 because I simply didn't consider this to be a valid use case.
