### ISSUE TITLE
Gorge Exoticiser module DOESN'T consume and void excess fluids it didn't ask for

### ISSUE THREAD

**Issue by ERRRR0R** [GTNewHorizons/GT-New-Horizons-Modpack#17978]
### Your Pack Version

Nightly +711

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

The module would void everything it didn't ask for so if you want to be efficient, you will have to input precise amounts and play the automation challenge 

### The Reality

It ignores the excess, which makes the machine solve itself. Showing the type of plasma through dust pile type and the amount through the difference of fluids is completely pointless because you can just stock all fluids it might ask for in hatches and it itself will pick what it wants, how much it wants, and nicely leave the rest for the next time.

### Your Proposal

Make it consume every fluid in hatches and void everything it didn't ask for. If you're lazy, you can still solve it by inputting max of every plasma. For a better setup, you can input max plasma only of the type it asks for. And only if you really want that 50 average instead of max 100 you do the full challenge.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
on beta-2 it not start recipe if you give more than required. it was changet on beta-3 i guess.
