### ISSUE TITLE
Akashic tome lacks some functionality

### ISSUE THREAD

**Issue by Ushupiuck** [GTNewHorizons/GT-New-Horizons-Modpack#17985]
### Your Pack Version

N/A (Individual mod; akashictome-1.1.8.jar )

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

*Sneak-right clicking a modded block from will transform the tome into its documentation book, if available in the tome. If you have multiple books from the same mod, it'll give you the first book added.

* To untransform back into the tome, punch the air.

### The Reality

Neither of the above behaviors were reproducible when attempting to use the tome, rendering it as nothing but a glorified bundle. (as you can select a book and read it, but are unable to change to any others, without sneak-dropping the current one onto the floor)

To reproduce, simply craft/spawn yourself an akashic tome, store some books in it via crafting (Ie.: lexica botania, thaumonomicon, etc. You name it), open the akashic tome, select a book, and attempt to perform either of the steps mentioned above

### Your Proposal

It is likely that the problem is caused by how air/null blocks are handled across versions, as both interactions listed require world interaction with empty space.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
just sounds like incorrect documentation. I dont see this anywhere though, where are you quoting from?

**Comment by Lyfts** [comment]
![akashic_morhp](https://github.com/user-attachments/assets/e1d474ea-dd5d-4af8-8247-0e669e558e5e)

I really can't reproduce your first point. Which block from which mod are you using it on and what books are in your tome?
