### ISSUE TITLE
EOH should give purified Tengam

### ISSUE THREAD

**Issue by Voidlinked** [GTNewHorizons/GT-New-Horizons-Modpack#17988]
### Your Pack Version

2.7.0 beta 3

### Your Proposal

The EOH give ready-to-use versions of naqline and platline metals, and the lanthanides that need processing. It does not give ready-to-use Tengam, however.

### Your Goal

Consistency, less multiblock spam.

### Your Vision

Avoid multiblock spam and add some consistency.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by NotAPenguin0** [comment]
Using the magnetic separator multiblock spamming for purified tengam is not needed at all. I don't see a good reason to take away even more gameplay and shove it into the already overused EOH.
