### ISSUE TITLE
Graviton Shard has no indication of how to make it

### ISSUE THREAD

**Issue by lolqqqq123** [GTNewHorizons/GT-New-Horizons-Modpack#17983]
### Your Pack Version

2.7.0 beta 3

### Your Server

sp

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

looking at recipe in nei

### The Reality

i tried to click to show me the recipe and nothing showed up

### Your Proposal

add the recipe or show in nei

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lolqqqq123** [comment]
i ment dust

**Comment by serenibyss** [comment]
Graviton shards are made by getting a max upgraded godforge and enabling graviton shard ejection in the UI. I agree though that this could be clearer, either with a fake NEI page or tooltip or similar

**Comment by lolqqqq123** [comment]
yes people use nei for recipes and recipes should be clear
