### ISSUE TITLE
Make Heat Sensor Hatch Accept > and <

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#17990]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.7.0 beta 3

### Your Proposal

Title. It'd help with making an RS latch that stops the multi at 66% (20 seconds of work at aw drac coils to reach 100%) and turns it on again at 10% or less. The hatch also doesn't seem to turn on at 0%, which is the primary reason for < and >.

### Your Goal

Make it more consistent with other detector hatches, like the electron volt ones, and the detector covers, who have different modes of operation with these parameters.

### Your Vision

Consistency, mostly, but also better automation. Not easier, perse, but better.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by FourIsTheNumber** [comment]
The heat sensor works exactly the same as all the other sensor hatches - neutron sensor hasn't been able to take '>' or '<' for a while now. It is threshold-based and this is implicit behavior - if you set the threshold to 66, it will turn on at >= 66. If you set it to 66 and invert signal, it turns on at <= 66.

**Comment by LazyFleshWasTaken** [comment]
O. I se

**Comment by LazyFleshWasTaken** [comment]
Should probably be stated it works like that though.
