### ISSUE TITLE
Switch Ender Fluid Link Cover to private result in crash

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#17991]
### Your GTNH Discord Username

ngar

### Your Pack Version

2.7. Nightly - 712

### Your Server

Zeta

### Java Version

Java 8

### Type of Server

None

### Your Actions

put an Ender fluid cover on input hatch
configure name and dir.
configure to "private" -> crash

### Crash Report

https://mclo.gs/pgzpaRM

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ngar1** [comment]
same crash, if switching from private to non-private an other Ender Fluid Cover 
https://mclo.gs/LpayG1A

After this the server is not reachable in "multiplayer" server selection.

**Comment by Ngar1** [comment]
#17863 covers issue

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17863

**Comment by NyrZ** [comment]
close this issue if it's already opened in #17863

**Comment by RAFAEL-SOSA-UH** [comment]
yes, issue it's already in #17863
