### ISSUE TITLE
Tellurium in OW VM

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#18006]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.7.0 beta 3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

No tellurium from OW VM

### The Reality

Tellurium in OW VM

### Your Proposal

Decide if intended or not?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by StaffiX** [comment]
[It's intended](https://github.com/GTNewHorizons/GT5-Unofficial/blob/bb74217d4f8a24bb1e6d85ff16c1b5684633906c/src/main/java/bwcrossmod/galacticgreg/VoidMinerUtility.java#L129)

**Comment by chochem** [comment]
it's in the questbook too
