### ISSUE TITLE
DTPF, Dimensional Convergence, Crafting Input Buffer

### ISSUE THREAD

**Issue by TimberDimber** [GTNewHorizons/GT-New-Horizons-Modpack#18000]
### Your GTNH Discord Username

timberdimber

### Your Pack Version

2.7.0-beta-3

### Your Server

Private

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

When using a dtpf for craft via a crafting buffer, provided that it works on passive crafting, a switch from passive to ordered occurs. However, with Dimensional Convergence enabled, the catalyst will not be spent from the stocker, where it is used for passive crafting, but directly from the crafting buffer, where it is needed for the craft .

### The Reality

.

### Your Proposal

Make the consumption of the catalyst not together with the recipe, as it happens now in the form of adding this catalyst to the cost of the recipe, but direct consumption by dtpf itself or a separate calculation, which does not affect the recipe itself.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by StaffiX** [comment]
Crafting input busses and buffers have dedicated and separate crafting storage, to avoid conflicts, it's fully intentional that they don't work with outside hatches, if you wanna use convergence, either dedicate DTPFs with passive stocking, or figure out a way to on demand it via stocking bus/hatch.
