### ISSUE TITLE
Datasticks in NEI do not always render correctly

### ISSUE THREAD

**Issue by CookieBrigade** [GTNewHorizons/GT-New-Horizons-Modpack#18003]
### Your GTNH Discord Username

BucketBrigade

### Your Pack Version

Nightly 733

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

In a fresh world in single player. Data sticks in assembly line recipes and research recipes render exactly as expected.
![image](https://github.com/user-attachments/assets/670edb74-fec9-462d-9202-82b412163933)
I would expect it to work for an older world as well.

### The Reality

The data sticks do not work properly in an older save on the same version.
![image](https://github.com/user-attachments/assets/fd7b9616-e224-4d9a-b5f6-7b7ad8a3ddbc)

### Your Proposal

Have it always work.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
I would suspect this was broken by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2917

that functionality doesnt really work currently as the ids are somewhat hardcoded and dont correspond to world ids which likely also causes this
