### ISSUE TITLE
Simulated (missing) items in AE2 crafts doesn't consumed from storage busses

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#18009]
### Your GTNH Discord Username

skproch

### Your Pack Version

2.7.0-beta3

### Your Server

private

### Java Version

Java 21

### Type of Server

Ultramine

### Your Expectation

When items are simulated in crafts by turning on ignore missing when starting craft or by having level emitter with a crafting card it should be consumed from storages attached to [fluid] storage busses.

Consider the following setup: two simple recipes, start crafting with ignore missing, add items/fluid to storages linked to network via storage busses, items shows in network, but doesn't consumed by craft. If i extract it from the terminal and put it back it will be consumed by a craft successfully. 

Here is the example:

https://github.com/user-attachments/assets/dec2209a-26cb-4000-b28d-d56db6947e13

This issue also applies to fluids as well

### The Reality

Items available via storage busses doesn't get consumed for a crafts.

### Your Proposal

Fix problem. 

I've doesn't very familiar with AE2, but probably should make an crafting grid scans the network for the missing items, or storage busses propagate items to crafting if required.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by hiroscho** [comment]
The crafting grid is itself just another inventory with the absolute highest priority. Once you have started the craft it will not look into any of the other inventories. Any item injected into the ME system will first attempt to go into the crafting grid. As such any items that magically appear in your storage-bus-inventories will not be considered. The item has to be injected into the ME system where the crafting processor is to be registered. You can store it in any other system or inventory afterwards but the injection to the network has to take place.

**Comment by SKProCH** [comment]
Its working fine for explicitly set "ignore missing" before starting craft, but seems like it doesn't support level maintainers with a crafting card.

You can put crafting card in a level maintainer, so AE2 will auto apply ignore missing to item specified in level maintainer (or a fluid drop). And this PR seems like doesn't work for such ignored missing items. 

@lordIcocain probably you can take a look?

**Comment by lordIcocain** [comment]
@SKProCH How you can put crafting card in maintainer? i never heard about that functional and dont see something about that in mainatainer code

**Comment by SKProCH** [comment]
@lordIcocain Oh, sorry, I got mixed things up. I meant level emitter with crafting card.

![image](https://github.com/user-attachments/assets/e9b7879a-3b06-44ce-ac45-bd8c94c2a5ec)

**Comment by lordIcocain** [comment]
@SKProCH Now should work fine, you can check with https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/645

**Comment by SKProCH** [comment]
@lordIcocain yeah, with this fix it works now. Thanks! ❤️
