### ISSUE TITLE
 Bending machine cannot craft double silver plates

### ISSUE THREAD

**Issue by mxHuber** [GTNewHorizons/GT-New-Horizons-Modpack#18010]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Trying to craft the item "Double Silver Plate" in the bending machine for the item "Simple Solar Boiler". I put the item "Double Silver Ingot" and a "Programmed Circuit" on configuration 1 inside the bending machine. Expected it to consume the "Double Silver Ingot"  and to give me "Double Silver Plate" in return.

 I also put the item "Silver Plate" and a "Programmed Circuit" on configuration 2 inside the bending machine. Expected it to consume two "Silver Plate" and to give me "Double Silver Plate" in return.

### The Reality

The bending machine does not create the item "Double Silver Plate".

Note: Other items are processed just fine in the bending machine, such as the item "Bronze Ingot" to "Bronze Plate".

### Your Proposal

Consume "Double Silver Ingot" and produce "Double Silver Plate" .
Consume two "Silver Plate" and produce "Double Silver Plate" .

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
that sounds like you are just trying to use an LV machine for an MV recipe.
