### ISSUE TITLE
"Frugal" Focus Enchantment does not work on Maintenance Focus

### ISSUE THREAD

**Issue by FourIsTheNumber** [GTNewHorizons/GT-New-Horizons-Modpack#18011]
### Your GTNH Discord Username

fouristhenumber

### Your Pack Version

2.7 Nightly 709

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Put "Frugal V" on Maintenance Focus using the Focal Manipulator, expecting it to reduce vis cost from 25 to 12.5 (50% total reduction)

### The Reality

Cost remains at 25. Interestingly, the gui in the bottom left reports that it will cost 12.5 vis, but the tooltip for the focus says 25 and the actual drain is 25.

### Your Proposal

Frugal should reduce focus use cost.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Claims to be fixed in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15736
Still occurring for me.

**Comment by Impos913** [comment]
This bug still exists on 2.7.2

**Comment by aka13-404** [comment]
Still occurs on 2.7.4
