### ISSUE TITLE
findIt crash when searching nearby containers for thaumcraft knowledge fragments ("stackAspects" is null)

### ISSUE THREAD

**Issue by Flakxo** [GTNewHorizons/GT-New-Horizons-Modpack#18017]
### Your GTNH Discord Username

.flaxo

### Your Pack Version

2.7.0-nightly-2024-11-11

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Using findIt to try and locate knowledge fragments from thaumcraft in nearby containers causes a crash to menu screen

### Crash Report

https://mclo.gs/NqsBdB9

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment]
this is fixed already you can download the updated version of the mod here https://github.com/GTNewHorizons/FindIt/releases

**Comment by wlhlm** [comment]
The crashlog above shows a different NPE. This will hopefully be fixed by https://github.com/GTNewHorizons/FindIt/pull/26
