### ISSUE TITLE
Gorge incorrect formula in IMKG upgrade description

### ISSUE THREAD

**Issue by ERRRR0R** [GTNewHorizons/GT-New-Horizons-Modpack#18014]
### Your Pack Version

Nightly +711

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

The formula is ((Fill level/Max capacity)-0.5)^2*(-0.6)+0.15
Meaning 1/2 filled batterey gives 15% discount and 1/4 filled gives 11.25% discount

### The Reality

The formula seems to be something like ((Fill level/Max capacity)-0.5)^2*(-0.6)+0.10
Because the results are 1/2 filled batterey is 10% discount and 1/4 filled is 7% (rounded 0.0625) discount. Although 1/10 filled batterey for some reason gives 4% discount, which fits neither formulas?

### Your Proposal

Fix the formula in upgrade description 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment]
For plasma module the listed formula is correct.

For other modules, the formula is:
(((Fill level/Max capacity)-0.5)^2*(-0.6)+0.15) * 2 / 3

This should definitely be described to the player in the upgrade description though
