### ISSUE TITLE
network switch doesn't form with optical reception connector

### ISSUE THREAD

**Issue by pilchard436** [GTNewHorizons/GT-New-Horizons-Modpack#18029]
### Your GTNH Discord Username

pilchard436

### Your Pack Version

2.7.0 beta 4

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

network switch should form with optical reception connector. 

### The Reality

It doesn't form due to incomplete structure. It does form with transmission connector. This did not happen in beta 3. 

### Your Proposal

make it form

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by pilchard436** [comment]
still broken in rc-2

**Comment by serenibyss** [comment]
This is a result of https://github.com/GTNewHorizons/GT5-Unofficial/pull/3432, optical reception hatches are now only allowed on the centers of any given side of the multi instead of anywhere
