### ISSUE TITLE
Regex Isn't Working in AE2 Terminals

### ISSUE THREAD

**Issue by sean-m-simpson** [GTNewHorizons/GT-New-Horizons-Modpack#18039]
### Your GTNH Discord Username

comradeMonk

### Your Pack Version

2.7.0-beta-4

### Your Server

Private

### Java Version

Java 17

### Type of Server

Open To LAN

### Your Expectation

look for "crush.*ore" in ae2 terminal search box.  Get crushed ore in the results.

### The Reality

Look for "crush.*ore" in ae2 terminal.  It doesn't allow me to even enter the * character.

### Your Proposal

Should be able to look for things in ae2 terminal using some sort of wildcards.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miklebe** [comment]
![javaw_mHwgOaHslu](https://github.com/user-attachments/assets/5ce1e9c5-2c72-4a52-9605-cc0525b05221)
You have to enabled regex search in NEI

**Comment by sean-m-simpson** [comment]
Thanks!  Must not have transferred the setting when I upgraded.

**Comment by slprime** [comment]
> Thanks! Must not have transferred the setting when I upgraded.
or 
`r/.../` - standard java regex (r/^m\w{6}ft$/ = minecraft)
