### ISSUE TITLE
Forestry backpack doesn't close container when removed with player interface

### ISSUE THREAD

**Issue by leumasme** [GTNewHorizons/GT-New-Horizons-Modpack#18035]
### Your GTNH Discord Username

leumasme

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

When a forestry backpack is removed from the player inventory in any way, the backpack gui should close to prevent dupe glitches

### The Reality

If the backpack is removed from the player inventory via a RandomThings "Player Interface", the backpack GUI is not closed, allowing item duplication of anything that fits in a forestry backpack

https://github.com/user-attachments/assets/8d4c21e7-ab6a-4a4f-8501-4eb6f7c6f692

- Open the backpack
- Get backpack removed from inventory
- Take items out of backpack (The backpack can't save this update as it's not in the players inventory anymore)
- Close backpack
- The items are now in the backpack and in the player inventory

### Your Proposal

Forestry should implement `canInteractWith` on the backpack Container to check if the backpack is still in the inventory. This is how the other backpack mod does it: https://github.com/GTNewHorizons/Minecraft-Backpack-Mod/blob/master/src/main/java/de/eydamos/backpack/inventory/container/ContainerAdvanced.java#L52-L68
If it returns false, the container is closed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
fixed in dev
