### ISSUE TITLE
FindIt + Thaumcraft still crashing when aspect containing items are in a container

### ISSUE THREAD

**Issue by truenachtara** [GTNewHorizons/GT-New-Horizons-Modpack#18034]
### Your Pack Version

2.7.0-beta4

### Your Server

Private server

### Java Version

Java 21

### Type of Server

None

### Your Actions

Search for enchanted fabric in a chest
Then the next chest I open contains phials of essentia (while findit is still "hot")
![image](https://github.com/user-attachments/assets/2a961f97-4d94-4db0-b0f2-2f9bb6e883f0)

This also works with crystallized essentia, mana beans, and ethereal essence,

### Crash Report

https://mclo.gs/iC6HYLN
https://mclo.gs/JJbNmzJ

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment]
I have a potential fix for this, but wasn't able to reproduce the crash. Can you please confirm if the problem goes away with the following build: https://github.com/GTNewHorizons/FindIt/suites/31077234850/artifacts/2208477534

If it still crashes, please post the crashlog.
