### ISSUE TITLE
AE2 recipes stuck on "Scheduled"

### ISSUE THREAD

**Issue by NC1107** [GTNewHorizons/GT-New-Horizons-Modpack#18054]
### Your GTNH Discord Username

nc1107

### Your Pack Version

2.7.0 beta 4

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

When i attempt to craft a 64k drive in ME, like normal, I expect it to complete successfully since I have crafted hundreds of them before.

### The Reality

When trying to craft **anything** in AE2 suddenly, the recipes do not get inserted into the machines. These recipes have been working perfectly for hundreds of hours and now they just get stuck.
![image](https://github.com/user-attachments/assets/4943a91e-8242-47f6-9a74-9505d91a4b48)

This happens with almost any recipe now.
![image](https://github.com/user-attachments/assets/4f7ebde6-434c-4ed0-9810-d6b991be652a)

I have tried:
- turning on/off ME
- ensuring the fluid encoder is working
- making sure there is enough drive capacity
- updating server from 2.6 beta 3 ->  2.6 beta 4  ->  2.7 beta 4

###  Proposal

 This issue is beyond me, its something more complex so I do not have a proposed solution.
 
### Current Fix
   I am able to fix _some_ of the recipes by breaking the interfaces and machines and then replacing them the exact same way they were originally. (which is why i believe it to be a bug)

### Disclaimer
   I don't normally write GitHub tickets, so if you need something of me in terms of logs or screenshots be slightly more specific so that i can respond asap with the correct information. I wrote this ticket because I was not the only one facing this issue in the discord.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
beta-4?

**Comment by NC1107** [comment]
@lordIcocain 
yes, I'll update the ticket to include that

**Comment by NC1107** [comment]
sorry haha, didn't mean to close it.

**Comment by lordIcocain** [comment]
@NC1107 Can you show setup?

**Comment by NC1107** [comment]
> @NC1107 Can you show setup?

Its a whole base so its a bit segmented, I can provide screenshots of misc. parts of it if that would help? is there anything specific you want to know/see? I've managed to fix most of the issues by breaking and replacing all of the machines and interfaces, I am just unsure why it even happened in the first place. So I can at least confirm the AE2 setup is _fine_

**Comment by lordIcocain** [comment]
@NC1107 surroundings of dual interface with that pattern.

**Comment by NC1107** [comment]
sure @lordIcocain, here is an example:

Here is a screenshot showing the interface online and connected, with the pattern inside, with the machine below being powered and setup
![image](https://github.com/user-attachments/assets/889d43ac-04a4-4274-8c28-27808741b50e)

Here is a screenshot of what it gets stuck on
![image](https://github.com/user-attachments/assets/eba88d19-b12b-4ea3-9f9e-1cbf3b9f1c24)

here is a screenshot of the beginning half of the recipe functioning:

![image](https://github.com/user-attachments/assets/34f01738-756b-4d11-b690-405351232a0d)

**Comment by lordIcocain** [comment]
@NC1107 i see this is issue. Try disable using substations on pattern.
![image](https://github.com/user-attachments/assets/acd15c13-b9d8-4279-9a99-3b2bfcd7d88c)

**Comment by NC1107** [comment]
@lordIcocain 
![image](https://github.com/user-attachments/assets/a1a48c8b-ce5a-4d23-ad7f-d5484229b785)
its disabled now, still no luck

**Comment by lordIcocain** [comment]
@NC1107 When its stuck are circuit assembler empty?

**Comment by NC1107** [comment]
@lordIcocain yes, unless there is some sort of invisible item I can't see

**Comment by RAFAEL-SOSA-UH** [comment]
@NC1107 are the chunks loaded? Also, the output face of the machine is not facing the me interface, right?

**Comment by NC1107** [comment]
> @NC1107 are the chunks loaded? Also, the output face of the machine is not facing the me interface, right? 

@RAFAEL-SOSA-UH 
The chunks are loaded,
The output face is forward 

I've been mitigating the problem all day and it feels like it was some sort of short term corruption in my world that messed up the connection between the interfaces and the machines. But everything seems to be working again, or at least I haven't encountered a craft that causes the problem again

Thanks for the ideas though

**Comment by RAFAEL-SOSA-UH** [comment]
@NC1107 mmm oke, so i'll close the issue, if something happens again feel free to reopen it.

**Comment by NC1107** [comment]
> @NC1107 mmm oke, so i'll close the issue, if something happens again feel free to reopen it.

Sounds good, it's definitely a bug, but idk how to replicate it rn lol, thanks for the help
