### ISSUE TITLE
Crash on Startup with v2.6.1 using Java 21, "Security Manager is deprecated"

### ISSUE THREAD

**Issue by andrewlalis** [GTNewHorizons/GT-New-Horizons-Modpack#18056]
### Your GTNH Discord Username

____andrew____

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Actions

1. Downloaded the MultiMC pack at https://downloads.gtnewhorizons.com/Multi_mc_downloads/GT_New_Horizons_2.6.1_Java_17-21.zip
2. Imported to a new MMC instance.
3. Started up. Game crashed on startup and prompted me to add `-Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader` jvm flag.
4. Added JVM flag and started again. Game crashes with the following error:
```
Failed to start Minecraft:
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
Exiting with -1
```

### Crash Report

https://paste.ee/p/6hPvJ

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment]
This a drawback with MultiMC launching GTNH on java17+. Those java versions need additional arguments to be passed in, but that requires a manual step by the user on MultiMC. See point 5 in our [Installation guide](https://gtnh.miraheze.org/wiki/Installing_and_Migrating#MultiMC_or_Prism_Launcher_with_Java_17-21).

Alternatively, I recommand you try out PrismLauncher which doesn't need these additional setup steps.
