### ISSUE TITLE
Space Elevator Space Pump overflows me output hatch with big batch sizes

### ISSUE THREAD

**Issue by StaffiX** [GTNewHorizons/GT-New-Horizons-Modpack#18053]
### Your GTNH Discord Username

StaffiX

### Your Pack Version

Nightly 730

### Your Server

Single Player

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

ME output hatch should not display negative fluid values, and void fluids as a result

### The Reality

When you set batch size to a number that would max int overflow the space pump (usually with a later tier pump, such as Mk3), it overflows the me output hatch, due to the hatch not being able to accept more than max int at a time.

![image](https://github.com/user-attachments/assets/05d0df93-96b5-4fad-a62d-11bc16c52e78)

https://discord.com/channels/181078474394566657/181078474394566657/1209995090941055006

### Your Proposal

Space pump should have a special handling for this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eranicus** [comment]
negatives are new thing, maybe after changes to ME output hatches?

Just tested on 2.6.1  MK3 x4 hydrogen 

Batch size 20 

![Screenshot 2024-11-21 184759](https://github.com/user-attachments/assets/e82e14de-e6bd-4f07-8a2b-f2df5e325b3f)

Batch size 64

![Screenshot 2024-11-21 184949](https://github.com/user-attachments/assets/dac3eb45-6e19-4e5c-9a0e-b468ab224d08)

Batch size 128 

![Screenshot 2024-11-21 190117](https://github.com/user-attachments/assets/11b8efb3-fc47-4151-9bef-1ba40c197792)
