### ISSUE TITLE
electric jukebox only supports vanilla discs

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#18055]
### Your GTNH Discord Username

keyla3300

### Your Pack Version

2.7 beta 3

### Your Server

idk

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Expected to be able to listen to Hardcore Ender Expansion discs, as well as probably others, like from botania i guess?

### The Reality

Hardcore ender expansion cool music discs are just silent

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
I've looked into this and concluded that there is no way to support both vanilla records and HEE discs through the `RecordItem` API unless HEE registers each disc as its own item (with unique ID) which is wasteful. (though maybe I've missed something)

Alternative is to add HEE-specific disc handling to the GT Jukebox, which disgusts me too much. Somebody else can do that.

**Comment by CatsLeftEar** [comment]
Then remove the support of vanilla discs, HEE are actual music while there are barely 2-3 vanilla music discs

**Comment by eigenraven** [comment]
@wlhlm I have plans to support all of the discs, it just involves writing a new API and I got busy irl

**Comment by wlhlm** [comment]
@CatsLeftEar Just to clarify: your request is totally valid, you should be able to play all the discs. Though the only ways I could think of to implement that are ugly (not generic enough) and I'm passing the buck to another dev.
