### ISSUE TITLE
VisualProspecting Identifying Ore Veins Incorrectly

### ISSUE THREAD

**Issue by SamuelPtolemyDawson** [GTNewHorizons/GT-New-Horizons-Modpack#18058]
### Your GTNH Discord Username

Lazorati\9174

### Your Pack Version

2.7.0 Beta 4

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

For Visual Prospecting to correctly record my ore vein data and display properly to Journeymap.

### The Reality

When upgraded my world to Beta 4, I ensure to move across Journeymap and VisualProspecting data.
However, I've noticed that veins are all being identified incorrectly.
Existing 'found' veins have had their labels changed, and newly prospected ones are being identified incorrectly.
Below screenshot shows a vein being newly scanned in beta 4 with an LV Prospector's Scanner - the chat readout identified it as a Terra & Aer vein, despite being in the overworld. However it also detects ores typical of an Apatite vein.
 
![image](https://github.com/user-attachments/assets/9e8f3a1c-49b2-43c2-a015-c3c36e2e91f9)

Example of existing prospecting data that has been changed, after being ported over from Beta 3. The highlighted Naquadah vein was in fact a Mica vein.

![image](https://github.com/user-attachments/assets/89f29a35-af2f-4906-9853-cf9f69e04317)

### Your Proposal

For ore veins to be correctly identified and recorded.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
Did you delete/forget to copy the veintypesLUT file in the visualprospecting folder?

**Comment by SamuelPtolemyDawson** [comment]
I recopied over the veintypesLUT file from my previous instance and that seems to have fixed the issue.
I thought this was done originally but it may have been missed. Seems to have been user error during migration.
Apologies for the timewaste!

**Comment by Bober682** [comment]
> Did you delete/forget to copy the veintypesLUT file in the visualprospecting folder?

if i deleted what should i do?

**Comment by JorisvanRoy** [comment]
> > Did you delete/forget to copy the veintypesLUT file in the visualprospecting folder?
> 
> if i deleted what should i do?

I have a similar issue. With the 2.7.0 update i thought of starting up my old server. It is hosted locally on my own server. I dont have the client files anymore. When i connect with a freshly installed client to my local server, then I get the message that 77 new ore veins have been discovered. These are however the wrong ore veins...
When i rediscover the veins they also are not overwritten and i see no way to delete or clear the discovered veins. I tried deleting journeymap data via the UI and the folders, but that did not fix the issue.

**Comment by Lyfts** [comment]
Nothing in the pack will automatically discover veins for you on login, sounds like whatever you have installed that is doing that is using some outdated info.

If you are starting with a completely fresh visualprospecting folder on the client you don't need your old veintypesLUT file it's only needed if you intend to use your old cache.
