### ISSUE TITLE
Gunpowder Centrifuging

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#18060]
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.7.0 beta 3

### Your Proposal

Gunpowder is kinda useless. It's made out of sulfur, saltpeter, and coal, which are pretty nice, and could be an incentive to set up a farm of some kind. 

### Your Goal

More use for gunpowder, an incentive to use it all, and another fair source of sulfur and coal. Well, coal if it centrifuges into coal, like fire charge.

### Your Vision

^

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by ogdae** [comment]
I'd welcome this change as currently, you easily accrue large amounts from an EEC (as an easy example) and there's nothing better to do than void it. The rates dont have to be crazy good, but at least having a use would be nice!
