### ISSUE TITLE
Logistic Pipe : When I break a basic logistics pipe, game crashed

### ISSUE THREAD

**Issue by DaTouJun** [GTNewHorizons/GT-New-Horizons-Modpack#18077]
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Break a basic logistics pipe

### Crash Report

[crash-2024-11-24_00.27.05-client.txt](https://github.com/user-attachments/files/17881388/crash-2024-11-24_00.27.05-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Atlantis102** [comment]
this should be fixed in 2.7.0
