### ISSUE TITLE
Plasma mixer shows wrong recipe consumption

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#18075]
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Plasma mixer will show consumption according to nei:
![nei](https://github.com/user-attachments/assets/8cb91289-7420-4480-a2c9-aa84677558f6)

### The Reality

Plasma mixer shows wrong recipe consumption when energy is insufficient.
The number is very close to total energy spent on recipe.
![mixer](https://github.com/user-attachments/assets/d8eb3c65-d9f7-4a7e-ae9b-0bb3673622c0)

### Your Proposal

If it is just total energy spent on recipe, then "/t" should be removed from this string.
If number displayed is really 100 times bigger than needed, it should be fixed.
Also, players said it may consume all energy at the start of recipe.
But even in this case x100 times consumption is misleading.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2778
