### ISSUE TITLE
Food shanks information when food moused over showing in random positions on scree/not showing at all

### ISSUE THREAD

**Issue by mundaj** [GTNewHorizons/GT-New-Horizons-Modpack#18081]
### Your GTNH Discord Username

jmunda

### Your Pack Version

Nightly 748

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Food shanks "attached" at the bottom-right of food information box 

### The Reality

![image](https://github.com/user-attachments/assets/87b5685f-11ff-44aa-938f-c84f228647c5)

### Your Proposal

Pls fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
already has a pr https://github.com/GTNewHorizons/AppleCore/pull/32
