### ISSUE TITLE
Precise Assembler quest requires wrong tier casings

### ISSUE THREAD

**Issue by MCmaxl17** [GTNewHorizons/GT-New-Horizons-Modpack#18105]
### Your Pack Version

2.7.0 beta 4

### Your Proposal

Quest-ID: AAAAAAAAAAAAAAAAAAAMEg==

The Precise Assembler quest requires 21x IV Machine Casings. The machine casings limit the tier of possible crafting recipes.
However, basically the first required craft (for the Neutron Activator) is the Hi-Computation Station Mk-II, which is an LuV recipe.

Problem: Naively following the questbook without reading the tooltip of the Precise Assembler doesn't let you craft the "next" recipe.

Suggestion: At least, change 21x IV Machine Casings to 21x LuV Casings.
Even better, completely remove Machine Casings from the quest requirements and just write about it in the text. Since higher tier casings are craftable already at LuV, and the Precise Assembler already required 63 ZPM Casings, people might want to decide to skip LuV Casings and go for ZPM+ Casings directly. They are just different platline materials after all.

### Your Goal

-

### Your Vision

-

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
Its IV now, so that is fine. Neutron activator is later. But the casings should be optional for sure.

**Comment by FourIsTheNumber** [comment]
The casings are already optional and Precise Assembler can be used as a multiblock assembler (and can be made in IV) so the quest is accurate.
