### ISSUE TITLE
Thermic heater doesn't multiply outputs in batch mode

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#18116]
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.6.1

### Your Server

Delta

### Java Version

Java 21

### Type of Server

Thermos

### Your Expectation

Turning on batch mode should improve lag effects - particularly for one-ticking machines.

### The Reality

Turning on batch mode for fluid heaters kills machine performance, since the same output is generated for the batch recipe time.
Batch mode off, 1.4M steam per second
![image](https://github.com/user-attachments/assets/c1b17761-7d72-45c5-ae51-0c995eb68308)
Batch mode on, 11K steam per second, over a factor 100 worse:
![image](https://github.com/user-attachments/assets/c52530b6-baa3-4867-a84d-10f1eefcaca4)

### Your Proposal

Batch mode should correctly multiply recipe outputs

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Did you close and open the ui? Afaik the actual bug is that the output doesn't update when you click the button and that you have to refresh the screen.

**Comment by combusterf** [comment]
That did solve the issue. I tried it with another machine and noticed that it's only the fluids that do not get correctly updated. Items work fine.
