### ISSUE TITLE
2.7 RC-1 Crash

### ISSUE THREAD

**Issue by xValditor** [GTNewHorizons/GT-New-Horizons-Modpack#18121]
### Your GTNH Discord Username

Valditor#8025

### Your Pack Version

2.7 RC-1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

I opened the questbook, went to the "kill all things" section, left clicked "Hail to the king" and then it crashed. It crashes every time I click on it.

### Crash Report

[crash-2024-11-26_21.22.08-client.txt](https://github.com/user-attachments/files/17925415/crash-2024-11-26_21.22.08-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Iamworking12** [comment]
Unfortunately I could not reproduce it on the same version, but on java 21. 
![image](https://github.com/user-attachments/assets/b15a4316-e545-4cbc-b282-4ad0acaa65b8)
The page loads just fine.

**Comment by xValditor** [comment]
Then the problem is in the java version?

**Comment by Iamworking12** [comment]
Wouldn't know for sure, you could try but I just wanted to point out that I was not using the exact same settings.

**Comment by boubou19** [comment]
almost each time we see `NoClassDefFoundError` crashes mentionning `squeek` it's a corrupted instance. So maybe try to redownload and reinstall the pack to see if it wasn't a fluke.

**Comment by xValditor** [comment]
Okay, I will. Thanks a lot, appreciate your time!

**Comment by Kremnari** [comment]
Testing with fresh install, prism launcher, java version jdk1.8.0_351 , new world.
QB entered view mode, and clicked...

no crash.
