### ISSUE TITLE
Covers on frames disappear and stop working after reloading the game

### ISSUE THREAD

**Issue by incuboprist** [GTNewHorizons/GT-New-Horizons-Modpack#18124]
### Your GTNH Discord Username

Incubo

### Your Pack Version

2.7.0-RC1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Covers placed on frames should remain visible and functional after re-entering the game.
![2024-11-27_15 59 11](https://github.com/user-attachments/assets/d850d565-01b9-4ac4-9ddf-f084f04e36b3)

### The Reality

Upon re-entering the game, covers stop rendering and functioning. They can be removed with a crowbar or by breaking the frame, at which point the covers drop as items.

![2024-11-27_15 59 49](https://github.com/user-attachments/assets/9d938a45-40a9-44d4-a896-f89f0aa5450b)

![2024-11-27_16 01 10](https://github.com/user-attachments/assets/758e52e0-b108-4b02-bc22-f468d1f40691)

![2024-11-27_16 02 03](https://github.com/user-attachments/assets/be2ba837-1688-4fd5-a7e6-2a5d52e4651f)

### Your Proposal

Fix it pls

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Miklebe** [comment]
In the essence the same as this one..?
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17498

**Comment by Ruling-0** [comment]
> In the essence the same as this one..? #17498

I believe partly related in the render vanishing. However, the frame cover not functioning after restart is new data.

I can confirm experiencing this issue on Nightly 732 - wireless transmitter on a frame box would cease working on restart, noticable as it held all connected machines online.
