### ISSUE TITLE
Transcendent Plasma Mixer incorrect NEI Multiblock Structure

### ISSUE THREAD

**Issue by Yoshy2002** [GTNewHorizons/GT-New-Horizons-Modpack#18147]
### Your GTNH Discord Username

yoshy1952

### Your Pack Version

2.7.0 RC-1

### Your Server

private Server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Plasma Mixer correctly shown in NEI Preview.

### The Reality

- Maintenance Hatch is shown in Preview, but is not needed at all
![image](https://github.com/user-attachments/assets/cd9adacf-32c1-4d6c-8cc6-fb64dc416e0d)

- Input Bus, Input Hatch, Output Hatch are looking at the inside, instead of the outside like on other Multiblock previews
![image](https://github.com/user-attachments/assets/2c918936-9bc7-4369-b72c-cac93439829a)

### Your Proposal

Remove the Maintenance Hatch and turn around the Hatches/Busses

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment]
The maintenance part of this is somewhat expected, since TPM does allow maintenance hatches as it used to require them, but now doesn't require them. They are still allowed so structures do not break. May be some way to not show this hatch in the NEI preview though

**Comment by Glease** [comment]
I don't think we can do anything with the "point inwards" thing without overcomplicating the structure definition, but surely something can be done with the maint hatch problem

**Comment by HoleFish** [comment]
make it filled with air inside?
