### ISSUE TITLE
Compressor gives TiCon aluminium block instead of GT one

### ISSUE THREAD

**Issue by qunYp3dZSyLjoEoEg** [GTNewHorizons/GT-New-Horizons-Modpack#18146]
### Your Pack Version

2.6.1

### Your Proposal

When putting 9 aluminium ingots in a compressor, it should craft the GT aluminium blocks

### Your Goal

All crafting recipes with TiCon aluminium blocks are craftable with GT alu blocks as well, but in order to grow the Bauxia crop one needs the GT blocks. 

### Your Vision

It would cut out the unecessary step of chiseling the TiCon blocks to be able to grow Bauxia and not block any other recipes that are available. And also create consistency with the fact that all other (from what I have seen) crop required blocks are able to be used directly out of the compressor. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
already done in https://github.com/GTNewHorizons/GT5-Unofficial/pull/3023

**Comment by qunYp3dZSyLjoEoEg** [comment]
Sorry then about this issue, couldn't fine the other issue with either aluminium block or aluminum block in the query

**Comment by chochem** [comment]
there might not have been one. I linked a PR not a ticket.
