### ISSUE TITLE
Make NEI search search items that are in Forestry backpacks

### ISSUE THREAD

**Issue by qunYp3dZSyLjoEoEg** [GTNewHorizons/GT-New-Horizons-Modpack#18142]
### Your Pack Version

2.6.1

### Your Proposal

When searching for an item in NEI NEI should also scan all Backpacks from Forestry for that item and highliht all Forestry Backpacks that have that item in it. 

### Your Goal

Miners Backpacks can pick up way too many different items, and when you accidentally drop smth due to lag it automatically gets put into the backpack. If you don't assume the item is able to go there, you won't lok at the backpack.

### Your Vision

It would make it easier to find lost items when the thing described in the point above happens but aklso not restrict players in which items are able to go in Forestry backpacks. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by TaterBlight** [comment]
This has already been implemented since 2.7.0 beta2, exactly like how you outline here.
![image](https://github.com/user-attachments/assets/0173a244-31eb-42ad-80fb-996d56743309)
![image](https://github.com/user-attachments/assets/5dcf7628-12ea-4226-bbb9-3d01e2f8bd9c)
![image](https://github.com/user-attachments/assets/78b3ee06-47f3-466f-8df4-7884503da7fb)

**Comment by qunYp3dZSyLjoEoEg** [comment]
Sorry then, I literally searched through 5 or six of the 8 pages on github that came up when searching with "is:issue forestry backpack" and nothing showed up about that :/. Really sorry
