### ISSUE TITLE
Fusion Coils for Compact Fusion Reactors not showing their "used Structure"

### ISSUE THREAD

**Issue by Yoshy2002** [GTNewHorizons/GT-New-Horizons-Modpack#18145]
### Your GTNH Discord Username

yoshy1952

### Your Pack Version

2.7.0 RC-1

### Your Server

private Server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Every Multiblock showing for all their used Blocks after this PR:
https://github.com/GTNewHorizons/BlockRenderer6343/pull/22#pullrequestreview-2456540606

### The Reality

Compact Fusion Reactors not showing up as a Multiblock for the specidif Coil Block of this Tier.
Compact Fusion Coil Mk-II Prototype (used in Compact Mk4):
![image](https://github.com/user-attachments/assets/260a7cd8-68e0-439d-ac44-c753404ea799)
Advanced Compact Fusion Coil(used in Compact Mk3):
![image](https://github.com/user-attachments/assets/8e41c5c2-91dc-40fc-8756-d865aca6711e)
Also affected:
- Ameliorated Superconduct Coil
- Compact Fusion Coil
- Compact Fusion Coil Mk-II Finaltype

### Your Proposal

Like Lyfts mentioned in the PR: "If any major ones are missing just lmk".

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
https://github.com/GTNewHorizons/BlockRenderer6343/pull/23 addresses this among other things, but it's not gonna be in 2.7.0.

**Comment by Yoshy2002** [comment]
Sad to hear its not gonna be in 2.7.0, but thanks for the clarification.

**Comment by Ableytner** [comment]
https://github.com/GTNewHorizons/BlockRenderer6343/pull/24 also addresses this, which is only a bugfix and could be merged for 2.7.0
