### ISSUE TITLE
Botania bugged? Help please. 

### ISSUE THREAD

**Issue by vasmark1** [GTNewHorizons/GT-New-Horizons-Modpack#18151]
### Your Pack Version

Nope

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Well, I've installed Botania updated by GTNH and sadly it crashes when I try to open creative tab of botania. All the rest features are working as intended. This is duplicate of issue from Botaina-GTNH repository. 

### Crash Report

https://paste.ee/p/EkXWJ
[latest (2).log](https://github.com/user-attachments/files/17951036/latest.2.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
you already made a ticket in the right place https://github.com/GTNewHorizons/Botania/issues/63
