### ISSUE TITLE
NEI Tab order shuffled

### ISSUE THREAD

**Issue by JMan-Zx** [GTNewHorizons/GT-New-Horizons-Modpack#18159]
### Your Pack Version

2.7.0 Beta4

### Your Server

Private server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Group similar NEI tabs together: e.g. recycling recipes at the end, bee related tabs together.
This is existing behavior in 2.6.0.

### The Reality

NEI tabs are ordered differently now. Recycling tab shows up in the middle of other recipe tabs, bees are separated, etc.

### Your Proposal

Either a revert to previous behavior, or a clarification that it's an intended change because of ___

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kstvr32** [comment]
These are controlled in `/config/NEI/handlingorder.csv`. 
Looks like GTNewHorizons/NotEnoughItems#519 broke this functionality by using the wrong function to parse ints. 

I will make a small PR to fix this.

**Comment by KleinGrrmpf** [comment]
This is back in 2.7.0. The one that I noticed especially is the "Materials" being the last tab in NEI instead of the first one.

**Comment by KleinGrrmpf** [comment]
This is back in 2.7.0. The one that I noticed especially is the "Materials" being the last tab in NEI instead of the first one.

**Comment by wlhlm** [comment]
That odering change was done deliberately. See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/18184

**Comment by KleinGrrmpf** [comment]
Good to know, thanks. Any config or other way to revert back? Because that tab being the first tab was really good!

**Comment by FourIsTheNumber** [comment]
Material page being first is preferable imo. Not sure why this was changed.

**Comment by Caedis** [comment]
> Good to know, thanks. Any config or other way to revert back? Because that tab being the first tab was really good!

You can edit the order file at `config/NEI/handlerordering.csv`

**Comment by wlhlm** [comment]
Specifically, the last two line in that files:
```
[...]
neicustomdiagram.diagramgroup.gregtech.materialtools,1499
neicustomdiagram.diagramgroup.gregtech.materialparts,1500
```

Add a negative sign to the numbers at the end to get the old ordering:
```
neicustomdiagram.diagramgroup.gregtech.materialtools,-1499
neicustomdiagram.diagramgroup.gregtech.materialparts,-1500
```
