### ISSUE TITLE
Item holder placement

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#18165]
### Your GTNH Discord Username

magebzz_2

### Your Pack Version

2.7 Beta 4

### Your Proposal

If you place the item holder (at least the "Good Item Holder" on a singleblock machine and open the UI of it after leaving the UI of the singleblock machine it will always reset itself to the "standard position"
![image](https://github.com/user-attachments/assets/1bfddf89-21b1-43f1-8283-6687bee39055)
This is it and I would suggest to permanently save the last position you moved the UI of it like this for example
![image](https://github.com/user-attachments/assets/d08474ce-77fb-4f72-9392-452792d4c978)

### Your Goal

I like the idea of the item holder early on for extruders etc. but the ability to move the UI is almost not a thing because it won't save the position after leaving the machine and going back to it

### Your Vision

Improve the use of item holders

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Miklebe** [comment]
Duplicate of this...? https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17770
I guess the first one didn't suggest where default opening space should be (or i am illiterate)

**Comment by MaGeBZz** [comment]
@Miklebe yeah you're right haven't seen it mb, will close this then!
