### ISSUE TITLE
Cleanroom EV Circuit Assembler not crafting result

### ISSUE THREAD

**Issue by DanilAndreevich** [GTNewHorizons/GT-New-Horizons-Modpack#18160]
### Your Pack Version

2.7.0 beta 4

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

https://github.com/user-attachments/assets/a648e8fd-05ca-4f16-9fa9-528600c0a5ee

I didn't notice any problems with crafting MV - tier circuits, but I saw a bug when crafting HV- tier circuits. Resources are spent on crafting, the progress bar is displayed, but there is no result of crafting.

There are no pipes or chests for this assembler. Crafting takes place in a cleanroom

### The Reality

Resources are spent on crafting, the progress bar is displayed, but there is no result of crafting.

### Your Proposal

get 1 circuit

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
smells like a cleanroom not running at 100% of efficiency. You must always ensure your cleanroom has no problem maintenance wise otherwise it can void the output.

**Comment by DanilAndreevich** [comment]
my cleanroom works without errors at 100% of efficiency

**Comment by DanilAndreevich** [comment]
I have a full video where I make several MV circuits without any problems, but as soon as I start making HV circuits, they get voided

**Comment by Miklebe** [comment]
> wait a minute , "pipe is loosing" can void output?

Each maintenance problem results in 10% efficiency loss, the controller should mention the current efficiency counting the maintenance problems.

**Comment by boubou19** [comment]
> I have a full video where I make several MV circuits without any problems, but as soon as I start making HV circuits, they get voided

then maybe it's because the MV ones don't require the cleanroom check. In any case, it's not a bug.
