### ISSUE TITLE
The Extreme Engine Intake Mechanical Block contains 7 Tungsten Steel, but can be obtained with an Extractor for 8 Tungsten Steel

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#18173]
### Your Pack Version

2.7.0-rc1

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

The Extreme Engine Intake Mechanical Block contains 7 Tungsten Steel, but can be obtained with an Extractor for 8 Tungsten Steel

### The Reality

rt

### Your Proposal

rt

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Mobius0526** [comment]
对不起，我算错了，应该是7.75

**Comment by chochem** [comment]
which is what it gives now

**Comment by Mobius0526** [comment]
In addition, the recipe for EAF recycling is also wrong

**Comment by chochem** [comment]
whats EAF

**Comment by chochem** [comment]
make a new ticket and be more clear about it: multi or single arc furnace, plasma or not, which tiers?

**Comment by Mobius0526** [comment]
ok
