### ISSUE TITLE
Programming circuit refresh is not timely

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#18170]
### Your GTNH Discord Username

Mobius_0526

### Your Pack Version

2.7.0-rc1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

after modifying  programming circuit, there must throw the item out to refresh 

### The Reality

![2024-11-30_10 21 10](https://github.com/user-attachments/assets/1eef614b-aa8a-43f5-90a5-41ab603b999e)
![2024-11-30_10 21 15](https://github.com/user-attachments/assets/64748fc7-a3e7-4b87-b7c3-ce22a4eee96b)
![2024-11-30_10 21 19](https://github.com/user-attachments/assets/97b1456f-6230-422f-8ab5-2ec08011c570)
![2024-11-30_10 21 21](https://github.com/user-attachments/assets/30c6358d-060e-4880-87ef-6177ae0fcb29)
![2024-11-30_10 21 25](https://github.com/user-attachments/assets/3843dae3-087d-4f3b-949d-53393974bb71)

### Your Proposal

fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by RecursivePineapple** [comment]
This is fixed by this PR: https://github.com/GTNewHorizons/Hodgepodge/pull/444
