### ISSUE TITLE
WirelessFluidDetectorCover always manipulates blocks redstone output to true

### ISSUE THREAD

**Issue by Sanduhr32** [GTNewHorizons/GT-New-Horizons-Modpack#18177]
### Your GTNH Discord Username

san32

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

I tried if the wireless fluid detector cover also manipulates the block it's placed on redstone output like the non-wireless version. I expected it to output a redstone signal matching the threshold ruling.

### The Reality

the cover manipulates any block it's placed on to output a redstone signal, regardless of threshold.

### Your Proposal

wireless covers in addition to the wireless signal transmission also should correctly manipulate the blocks redstone output to be the same as the signal thats transmitted, like their non-wireless variants. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Sanduhr32** [comment]
if desired, i can also try to patch it to not take up the teams time.

**Comment by serenibyss** [comment]
@Sanduhr32 That would be appreciated, thanks!

**Comment by Sanduhr32** [comment]
i'll try my best to fix the bug then, that the first init of the cover on a face causes a constant redstone signal.
subsequent cover installs (and presumably inits) do not cause a constant signal.

should the cover also intentionally manipulate the faces redstone output to match the wireless signal?

**Comment by Sanduhr32** [comment]
I believe i could trace it to here: https://github.com/GTNewHorizons/GT5-Unofficial/blob/5bbee72c52ca26597c14266642aa368b0fe964c6/src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java#L506

Whenever a wireless detector cover is installed with `manipulatesSidedRedstoneOutputImpl()` returning true, causes to pick redstone output from `mSidedRedstone[side.ordinal()]` being initially `15`.

I believe thats the bug, redstone output being set to 15.

Any other cover emitting redstone seems to update the redstone value by it's logic being run fast enough.

When a cover is removed this code is ran
https://github.com/GTNewHorizons/GT5-Unofficial/blob/5bbee72c52ca26597c14266642aa368b0fe964c6/src/main/java/gregtech/api/metatileentity/CoverableTileEntity.java#L419
setting the sides redstone to `0` (a sane default imo).

**Comment by Sanduhr32** [comment]
My mentioned commit in my previous comment seems to it for wireless detector covers.

However i am hesitant to PR, as i'ld like to know whether the "simple & stupid" patch shall be chosen or the default redstone output shall be adjusted to a sane `0` default for each side of coverable tiles.

**Comment by Sanduhr32** [comment]
Example images use the discord media proxy, as githubs is currently not working for me :/
Example 01:
![Example 01](https://media.discordapp.net/attachments/181078474394566657/1312748651461869628/2024-12-01_12.54.14.png?ex=674ef174&is=674d9ff4&hm=ecfd09df7280712718de1c3d60f2bcc54b9629a323c7249cb81122827a3e585a&=&format=webp&quality=lossless&width=1618&height=910)
Example 02:
![Example 02](https://cdn.discordapp.com/attachments/1049781602378580030/1312570057964130344/image.png?ex=674ef3e0&is=674da260&hm=71629e37019d86d3f5e1cdb5089930f009a595b32a0c78e79183c3d7678af161&)
