### ISSUE TITLE
Creating new world after updating to 2.7.0 RC1 ServerUtilites Causes crash.

### ISSUE THREAD

**Issue by C-A-T-T** [GTNewHorizons/GT-New-Horizons-Modpack#18189]
### Your GTNH Discord Username

c.a.t.t.

### Your Pack Version

2.7.0 RC1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Noticed a different bug and wanted to load a new world to test the issue.  Got a report that ServerUtilites caused a crash.

![image](https://github.com/user-attachments/assets/148e327d-dd18-4750-9b3f-8e274b6caa4f)

### Crash Report

https://mclo.gs/BZ5aJTo

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment]
I see almost exclusively the 2.6.1 versions of mods, something has definitely gone wrong with your update.

**Comment by chochem** [comment]
please follow this https://gtnh.miraheze.org/wiki/Installing_and_Migrating
