### ISSUE TITLE
Rename Cl3Fe to FeCl3

### ISSUE THREAD

**Issue by DanAzev** [GTNewHorizons/GT-New-Horizons-Modpack#18181]
### Your GTNH Discord Username

danazev

### Your Pack Version

2.6.1

### Your Proposal

Change the molecular formula of the Iron (III) Chloride from Cl3Fe to FeCl3, since it is most common to have the cation at first and the anion at last.

### Your Goal

More precision in the GTNH.

### Your Vision

Would correct the notation for the molecular formula.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Yamnasm** [comment]
I agree with this suggestion, as it also aligns with other chloride compounds.
