### ISSUE TITLE
After updating to 2.7.0 RC1 Questbook doesn't work.

### ISSUE THREAD

**Issue by C-A-T-T** [GTNewHorizons/GT-New-Horizons-Modpack#18190]
### Your GTNH Discord Username

c.a.t.t.

### Your Pack Version

2.7.0 RC1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Open the quest book to see if I have any quests to complete.

### The Reality

Quests dont show up.

![2024-12-01_15 33 49](https://github.com/user-attachments/assets/9c0d5453-ad43-414f-b8d4-df7b1b86ded7)
![2024-12-01_15 35 56](https://github.com/user-attachments/assets/ca71c35e-0d54-4d92-a7e1-26ad21add53c)

### Your Proposal

Not sure

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
This is gonna be related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18189#issuecomment-2510240218 assuming this is the same 2.7.0 RC1 that you're using in that ticket.

**Comment by C-A-T-T** [comment]
It is

**Comment by chochem** [comment]
certainly looks related yea. are you using a different account than before?

**Comment by chochem** [comment]
oh I see lyfts comment. yea that is definetely not 2.7.0RC1

**Comment by chochem** [comment]
please follow this https://gtnh.miraheze.org/wiki/Installing_and_Migrating
