### ISSUE TITLE
Travellersgear ability keybinds not working

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#18193]
### Your GTNH Discord Username

impvt

### Your Pack Version

2.7.0 RC-2

### Your Server

Private

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Tried binding Mantle of the Raven to a key for easy toggle.
![2024-12-02_03 18 42](https://github.com/user-attachments/assets/6cc1144a-ddc3-4a78-ab8a-f1a6a53b6cab)

### The Reality

The command doesn't work. No return in chat or log

### Your Proposal

Something between beta 4 and RC2 broke it, could be this https://github.com/GTNewHorizons/TravellersGearNeo/pull/3 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment]
Apologies for breaking things. This is weird: it works as expected in the development environment, but indeed, it's broken in 2.7.0-rc2. However, if I manually build the TravellersGearNeo branch, and copy that jar into GTNH, it works again.

Can you please test the following mod jar? [travellersgearneo-1.2.3-master+a293ef5397-dirty.zip](https://github.com/user-attachments/files/17971442/travellersgearneo-1.2.3-master%2Ba293ef5397-dirty.zip)
(make sure you extract the jar within the zip as GitHub doesn't allow me to directly upload .jars; also don't forget to remove/disable the old TravellersGearNeo jar)

**Comment by Impos913** [comment]
It works. thanks.

**Comment by wlhlm** [comment]
Fixed in [1.2.4](https://github.com/GTNewHorizons/TravellersGearNeo/releases/tag/1.2.4).
