### ISSUE TITLE
2.7.0 RC 2 opencomputer MFU can't read gt_machine

### ISSUE THREAD

**Issue by PinkYuDeer** [GTNewHorizons/GT-New-Horizons-Modpack#18208]
### Your GTNH Discord Username

PinkYuDeer

### Your Pack Version

2.7.0 RC 2

### Your Server

private server

### Java Version

Other versions in between

### Type of Server

Vanilla Forge

### Your Expectation

When I use MFU, I can't get the gt_machine remotely, either through component.list() or component.proxy(). there is no gt_machine in the list, and the proxy returns nil straight away. however, I can get the other machines normally such as blood magic's Altar and enderIO machines.

### The Reality

https://github.com/user-attachments/assets/062b621f-d502-4866-9e00-41d5c227e61b

### Your Proposal

use MFU get gt_machines' state

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by PinkYuDeer** [comment]
Java is zulu23.30.13-ca-jre23.0.1-win_x64

**Comment by PinkYuDeer** [comment]
Meanwhile, while hanging out in a private dimension with four dysfunctional MFUs, entities are constantly spawned and cleared, but the clearing is incomplete. This results in thousands of loaded entities being spawned every 20 minutes. Going out, re-entering the private dimension as well as returning to normal after removing the dysfunctional MFUs.

**Comment by C0bra5** [comment]
I've been trying to replicate this bug in the latest nightly, but I couldn't do so.
https://github.com/user-attachments/assets/b76b7167-8aea-42aa-a1da-adcfc8d2cd18

I tried with j20 and zulu23.30.13-ca-jre23.0.1, both gave the same result.

**Comment by PinkYuDeer** [comment]
I will update to RC-3 today to try and see if this problem occurs.

**Comment by PinkYuDeer** [comment]
The problem is happening again.Sadly, the problem has happened again. But since it's not happening in the production environment, perhaps because of a couple extra modules I added, I'll close this issue.
