### ISSUE TITLE
Mixer slots

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#18207]
### Your GTNH Discord Username

magebzz_2

### Your Pack Version

2.7 Beta 4

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

Wanna make this recipe here
![image](https://github.com/user-attachments/assets/242e4afb-95dc-47a1-9170-67500d7a1dd6)
It should make energetic alloy then with the shortcut recipe

### The Reality

The HV mixer didn't have enough slots to make this recipe
![image](https://github.com/user-attachments/assets/51157f16-6ba8-4a72-b295-175955b57a3b)
Probably other recipes are like this too

### Your Proposal

Change the mixer slots for HV mixer to more than these 6 (probably 9?) or the recipe needs to be changed cause it's impossible to make like this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
Ev+ mixers have 9 slots, and therefore can. The skip is acknowledged as Ev+ in the QB quest, iirc.

**Comment by MaGeBZz** [comment]
![image](https://github.com/user-attachments/assets/80a397da-311b-414d-9958-e4a6d4f1ad10)
It says something about it in the energetic alloy quest, still very weird if the recipe is HV then, could be changed to EV 6 seconds then eventually to not change the time but just the tier for this

**Comment by chochem** [comment]
we are not making macerator recipes with 2 outputs all HV either
