### ISSUE TITLE
ME output hatch have "Not enough fluid output space"

### ISSUE THREAD

**Issue by Egos90** [GTNewHorizons/GT-New-Horizons-Modpack#18223]
### Your GTNH Discord Username

Egos

### Your Pack Version

2.7.0-RC-2

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

I tried to use  machines with ME output hatch. I expected ME output hatch put fluids in to ME.

### The Reality

I tried to use  machines with ME output hatch. Machines with 1 fluid product works fine. But if machine have multiple fluid product wont work. It says "Not enough fluid output space". Even though i have enough place for new fluids in ME

### Your Proposal

Try to repair 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TheEpicGamer274** [comment]
Try Updating to the newest version of GT5U

**Comment by miaowwwwww** [comment]
it's fixed in rc3
