### ISSUE TITLE
Add stabitity info into Black Hole scanner data

### ISSUE THREAD

**Issue by dimazha** [GTNewHorizons/GT-New-Horizons-Modpack#18227]
### Your GTNH Discord Username

Dart_Voider

### Your Pack Version

2.7.0 beta 4

### Your Proposal

Add a row with stabitity info into Black Hole scanner data

### Your Goal

There is no options how know about stability, so OC programs can work only on timers and it will lead them to mistakes. So there is no possibility to make a reliable OC program for Black Hole. Other multis like water plants indicate thair states in scanner data, so Black Hole also needs such an indication

### Your Vision

OC program is the only reliable way to use Black Hole with highest efficiency. A possibility to use OC will give another opportunity to those who wants to make an OC program or to use such a program

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by FourIsTheNumber** [comment]
This is the exact reason why it does not provide scanner info.

**Comment by FourIsTheNumber** [comment]
> Am I understand correctly: the reason is to prevent using OC for Black Hole control?
No, you can still use OC. The _point_ is that it requires timing-based automation, whether it's with OC/redstone/sfm, instead of oc giving a direct readout. If I were going to put this information in scanner I would just add a hatch.

It's been reliably automated with redstone-only systems several times by now anyways.

**Comment by EnderProyects** [comment]
The reason is to prevent a fast and eassy soulution that people can just copy from the discord

**Comment by FourIsTheNumber** [comment]
I'm not trying to prevent people from copying solutions, I'm trying not to invalidate the concept of the automation. Which is that you have to track stability and design a control circuit rather than using a direct readout and another rs latch.

**Comment by boubou19** [comment]
time based automation is a fresh air to the pack, I understand it can be frustrating but it's needed otherwise it just becomes yet another boring multi to automate.
