### ISSUE TITLE
BetterQuesting + Smooth Font: Texts exceed quest & item tooltip boxes within the questbook

### ISSUE THREAD

**Issue by haobawobufu** [GTNewHorizons/GT-New-Horizons-Modpack#18251]
### Your Pack Version

2.7.0-beta4

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Texts should be covered by the tooltip boxes.

### The Reality

Texts exceed quest & item tooltip boxes when using Smooth Font mod

<img width="1799" alt="1" src="https://github.com/user-attachments/assets/1d1cce86-463b-46fa-9446-21f6746a82ff">

<img width="1801" alt="2" src="https://github.com/user-attachments/assets/90ebcbdd-5838-4f2d-bf02-b6b75cf35b64">

### Your Proposal

I would like to suggest implementing a new setting option in BetterQuesting, similar to 'textWidthCorrection', that allows users to adjust the length of tooltips in the quest book.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Mobius0526** [comment]
In Chinese, when changing the zoom ratio (3x), many places will be misaligned, including the above situation. Restarting the game can improve the misalignment.

**Comment by haobawobufu** [comment]
> In Chinese, when changing the zoom ratio (3x), many places will be misaligned, including the above situation. Restarting the game can improve the misalignment.

Is the zoom ratio here meaning the GUI scale in video settings? I didn't see this option in BQ config panel. I tried to change the GUI scale and restart the game though, but it's not working.

**Comment by haobawobufu** [comment]
To resolve this issue, please utilize a monospaced font in the Smooth Font mod. Otherwise, the mismatch between texts and tooltip boxes tends to occur.

If you are using Chinese, the Chinese characters are generally monospaced. However, the English characters in the font may not be. To avoid this issue, please modify the English part of the font to be monospaced (this requires the use of font editing software).
如果你在使用汉语，汉字一般是等宽的，但是字体中的英文未必，想要避免这个问题，请将字体的英文部分修改至等宽（需要使用字体修改软件）。
