### ISSUE TITLE
Questbook broken in 2.7.0

### ISSUE THREAD

**Issue by ClayDK** [GTNewHorizons/GT-New-Horizons-Modpack#18264]
### Your GTNH Discord Username

AssassinDK

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

i open the quest to start 2.7.0 and see the quest and questlines

### The Reality

i open the questbook and its empty no quest lines or quests
![billede_2024-12-08_153511514](https://github.com/user-attachments/assets/564ebcb2-c62b-49ac-9ab4-63d4542fb252)

### Your Proposal

pls fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by maxflc** [comment]
I am also experiencing this exact issue

**Comment by chochem** [comment]
sounds like either an install or an account issue on your end. you are not providing much information to go on.

**Comment by ClayDK** [comment]
the issue is that i basically freshly installed from the technic launcher opened an SP world opened the quest book saw it was empty cant explain it much more than that

**Comment by ClayDK** [comment]
i got it working again... full reinstall is needed though
