### ISSUE TITLE
Upgrading to 2.7.0 has broken the modpack

### ISSUE THREAD

**Issue by 2005-Toyota-Prius** [GTNewHorizons/GT-New-Horizons-Modpack#18261]
### Your GTNH Discord Username

2005toyotaprius

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

After upgrading the modpack to the version 2.7.0 released today, the launcher comes up again after only a few seconds when trying to launch the game. Downgrading back to the previous version (2.6.1) doesn't seem to fix it either. Note: I am using the Curseforge version but I don't think this is really relevant. Also the Minecraft launcher gives the exit code of 1.

### Crash Report

I have very little knowledge in coding and the closest thing I could find to the required files are the entire logs of the few seconds before the crash but I prefer not sending it in case it contains any sensitive data, however the line which I think is the issue here is this:
"[main/ERROR]:FML appears to be missing any signature data. This is not a good thing"

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
well without a log there is nothing we can do.

I guess I can recommend you follow the install instructions at https://gtnh.miraheze.org/wiki/Installing_and_Migrating

**Comment by 2005-Toyota-Prius** [comment]
![image](https://github.com/user-attachments/assets/ec05616c-30ec-48f7-a672-5b249fb61be7)
This is every file in the logs folder, should I send the latest.log file? (The one I talk about in the crash report section

**Comment by Caedis** [comment]
fml-client-latest.log should also be one

**Comment by Caedis** [comment]
just latest.log should be fine

**Comment by 2005-Toyota-Prius** [comment]
Well according to the wiki linked above I shouldn't be using CF so I'm downloading the regular version rn to see if it's fine

**Comment by 2005-Toyota-Prius** [comment]
It now works fine with a regular Forge installation (that just uses the MC launcher and not CF)
