### ISSUE TITLE
Minecraft crashing with GT

### ISSUE THREAD

**Issue by minecraftfan333** [GTNewHorizons/GT-New-Horizons-Modpack#18260]
### Your Pack Version

custom

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

i was trying to play gt5.09 by gtnh in my own custom pack
am i missing some dep? the issue is with GT++
and it even crashes if i put clean gt with all deps it asks, without need to install other mods

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/18051637/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ah-OOG-ah** [comment]
GT5u is not supported outside NH.

**Comment by Dream-Master** [comment]
gt++ is part of gt now and was included in the mod.

**Comment by minecraftfan333** [comment]
yeah i know, but its crashing no matter in what pack i use it, i mean with other mods or standalone(gt w/ deps) it works only inside of GTNH, so my question is how do i even run gt outside GTNH?

**Comment by Dream-Master** [comment]
check the dependencies file this mods are needed as a minumum. but again this version of gt is not supported outside GTNH.

**Comment by creatorofspark** [comment]
so it technically can work outside GTNH, it's just not supported if so, then i'll give it a try
