### ISSUE TITLE
(value = "com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader"). To use archived non-system classes, this property must not be set

### ISSUE THREAD

**Issue by brotherman123** [GTNewHorizons/GT-New-Horizons-Modpack#18276]
### Your Pack Version

2.7.0

### Your Server

private server

### Java Version

Java 21

### Type of Server

None

### Your Actions

It would enable everything on the server then do a reboot loop (here i ended the process early to show it all in one frame)
![image](https://github.com/user-attachments/assets/a06d06c5-4fb4-4ad2-ba7e-23576bce640f)
I don't know what this means 

### Crash Report

I don't have a log

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment]
Update java9args.txt

**Comment by brotherman123** [comment]
how do i access this file?

**Comment by Lyfts** [comment]
its in the server pack zip like everything else

**Comment by brotherman123** [comment]
> its in the server pack zip like everything else

I have found the file what is to edit?

**Comment by Lyfts** [comment]
replace your old one with it...

**Comment by brotherman123** [comment]
> replace your old one with it...

this has made a new bug 
![image](https://github.com/user-attachments/assets/44dfc0a6-8c3f-4813-b525-5eac0db1bf64)

**Comment by Lyfts** [comment]
You've changed something in the launch script because it's now looking for `java9args.txt-Dfile.enconding=UTF-8` which looks to be missing a space.

**Comment by brotherman123** [comment]
> You've changed something in the launch script because it's now looking for `java9args.txt-Dfile.enconding=UTF-8` whic
h looks to be missing a space.

this is what it looks like in nano
![image](https://github.com/user-attachments/assets/b6774e0a-53ed-4d7c-8f79-31b1ac2311e4)

**Comment by Lyfts** [comment]
```
-Dfile.encoding=UTF-8
-Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader
-Djava.security.manager=allow
--add-opens
java.base/java.io=ALL-UNNAMED
--add-opens
java.base/java.lang.invoke=ALL-UNNAMED
--add-opens
java.base/java.lang.ref=ALL-UNNAMED
--add-opens
java.base/java.lang.reflect=ALL-UNNAMED
--add-opens
java.base/java.lang=ALL-UNNAMED
--add-opens
java.base/java.net.spi=ALL-UNNAMED
--add-opens
java.base/java.net=ALL-UNNAMED
--add-opens
java.base/java.nio.channels=ALL-UNNAMED
--add-opens
java.base/java.nio.charset=ALL-UNNAMED
--add-opens
java.base/java.nio.file=ALL-UNNAMED
--add-opens
java.base/java.nio=ALL-UNNAMED
--add-opens
java.base/java.text=ALL-UNNAMED
--add-opens
java.base/java.time.chrono=ALL-UNNAMED
--add-opens
java.base/java.time.format=ALL-UNNAMED
--add-opens
java.base/java.time.temporal=ALL-UNNAMED
--add-opens
java.base/java.time.zone=ALL-UNNAMED
--add-opens
java.base/java.time=ALL-UNNAMED
--add-opens
java.base/java.util.concurrent.atomics=ALL-UNNAMED
--add-opens
java.base/java.util.concurrent.locks=ALL-UNNAMED
--add-opens
java.base/java.util.jar=ALL-UNNAMED
--add-opens
java.base/java.util.zip=ALL-UNNAMED
--add-opens
java.base/java.util=ALL-UNNAMED
--add-opens
java.base/jdk.internal.loader=ALL-UNNAMED
--add-opens
java.base/jdk.internal.misc=ALL-UNNAMED
--add-opens
java.base/jdk.internal.ref=ALL-UNNAMED
--add-opens
java.base/jdk.internal.reflect=ALL-UNNAMED
--add-opens
java.base/sun.nio.ch=ALL-UNNAMED
--add-opens
java.desktop/com.sun.imageio.plugins.png=ALL-UNNAMED
--add-opens
java.desktop/sun.awt.image=ALL-UNNAMED
--add-opens
java.desktop/sun.awt=ALL-UNNAMED
--add-opens
java.sql.rowset/javax.sql.rowset.serial=ALL-UNNAMED
--add-opens
jdk.dynalink/jdk.dynalink.beans=ALL-UNNAMED
--add-opens
jdk.naming.dns/com.sun.jndi.dns=ALL-UNNAMED,java.naming
```

This is what needs to be in the file idk why you've put the file name on the first line

**Comment by brotherman123** [comment]
giving me the same error
[0.019s][warning][cds] Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader"). To use archived non-system classes, this property must not be set
WARNING: package java.util.concurrent.atomics not in java.base

**Comment by Lyfts** [comment]
i pasted the wrong one but please just use the one from the serverpack zip without editing it

**Comment by brotherman123** [comment]
> i pasted the wrong one but please just use the one from the serverpack zip without editing it
the server pack one is the one giving me the issue

**Comment by Lyfts** [comment]
its only giving you issues because you editing the first line and put the filename there

**Comment by brotherman123** [comment]
> its only giving you issues because you editing the first line and put the filename there

i installed the one off of the server setup guide for linux why is the download name called 2.6.0 and it didnt work
