### ISSUE TITLE
Suggest removing servers selling keys/gambling for real money from the official servers list

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#18281]
### Your GTNH Discord Username

Keyla3300

### Your Pack Version

2.7

### Your Proposal

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16814
In this topic, admins all agreed on removing servers which sell keys/gambling for real money from the list. They are still there.

### Your Goal

 no trashy servers on the list

### Your Vision

removing bad servers

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by wlhlm** [comment]
oof
