### ISSUE TITLE
Cloud computation not working

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/GT-New-Horizons-Modpack#18292]
### Your GTNH Discord Username

ipielover

### Your Pack Version

2.7.0

### Your Server

Delta

### Java Version

Java 21

### Type of Server

Thermos

### Your Expectation

Cloud computation working as what shown in #upcoming-features

### The Reality

![image](https://github.com/user-attachments/assets/ca8d5c6a-d923-44d0-8178-4111a360f6e7)

![image](https://github.com/user-attachments/assets/e405a2a1-dbe5-443f-88d1-93aa47da62da)

![image](https://github.com/user-attachments/assets/4acc09d8-f4fc-4c3d-9325-3d0b63c0975c)

### Your Proposal

Pls fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
Are you enabled wireless mode on QC?
