### ISSUE TITLE
Xp consumed upon teleporting to personal dimension

### ISSUE THREAD

**Issue by Castabull** [GTNewHorizons/GT-New-Horizons-Modpack#18313]
### Your GTNH Discord Username

Castabull

### Your Pack Version

2.7.0

### Your Server

Private server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

I was attempting to rename an item in an anvil and went out into the overworld to get the required 5 levels from xp to rename the item and teleport back to the anvil in my personal dimension. 

### The Reality

I got the 5 levels of xp but when I teleported back into the personal dimension I had lost all but a little bit of my xp in the teleportation. 
![image_2024-12-09_210939167](https://github.com/user-attachments/assets/8216a131-859a-44a5-aff9-b9de7eddec75)
![image_2024-12-09_211011291](https://github.com/user-attachments/assets/27ecd976-66d2-4358-a147-05420463acd4)
before and after using bottle O' Enchanting to get xp for reproduction purposes.

### Your Proposal

XP has not been consumed in previous versions when teleporting to personal dimension. Is this the new expectation with 2.7.0?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LazyFleshWasTaken** [comment]
Common vanilla mc bug on dimension change. You just need to relog, to gain/lose a bit of experience, for example with an xp obelisk, killing something, or smelting something in a furnace.
