### ISSUE TITLE
Lan game quests resetting after completion 

### ISSUE THREAD

**Issue by pouncer61** [GTNewHorizons/GT-New-Horizons-Modpack#18312]
### Your GTNH Discord Username

pouncer61

### Your Pack Version

2.7.0

### Your Server

lan world

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Expectation

I have completed quests and after completion some of them have re set to the not done status
![44554](https://github.com/user-attachments/assets/846e3dfb-0d3d-42b0-bd69-f360c0748ffa)

ones circled in blue were the ones i did.
to repeat this open a lan game and be on the account that joins not the one that hosts, play for a while do some of the beginning quests and after a while some of them will reset after completion. Leaving and rejoining on the lan world has also caused some quests to reset.

### The Reality

the quest re set after one reason also i re did it again and it still reset i got more rewards each time too

### Your Proposal

fix the quests that are not repeatable so that they are fully complete

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
LAN worlds are not supported. please use a (local) server

**Comment by wlhlm** [comment]
Here is our server setup documentation: https://wiki.gtnewhorizons.com/wiki/Server_Setup
