### ISSUE TITLE
Searching by mod in NEI crash

### ISSUE THREAD

**Issue by KauliFlowar** [GTNewHorizons/GT-New-Horizons-Modpack#18314]
### Your GTNH Discord Username

KauliFlowar

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Did a mod search with the "@" symbol in NEI but didn't delete all previous text in NEI search bar so it looked something like "Opencom@", and crashed world. Logging back onto a world and opening the inventory crashes world again. Was able to reproduce in a new world, but was not able to reproduce upon closing and relaunching the game. Not 100% sure what is going on.

### Crash Report

https://mclo.gs/1HBPL8D

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by slprime** [comment]
same issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18265
