### ISSUE TITLE
QuestDatabase.json not changing when updated from 2.6.1 to 2.7.0

### ISSUE THREAD

**Issue by p3rsonUnknown** [GTNewHorizons/GT-New-Horizons-Modpack#18326]
### Your GTNH Discord Username

p3rsonUnknown

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

The file should get updated when I update the game as that file specifically don't have any direct effect on the quest **progres status** and so I can get the quests of newer multiblocks etc.

### The Reality

![image](https://github.com/user-attachments/assets/af7c59fb-353e-436e-b5d4-b89c9354873f)
The file don't get updated from 2.6.1 to 2.7.0 and is not showing the newer ores as a requirement (This is just one example)

### Your Proposal

I have Imported that specific file from a new world created in 2.7.0, to my own world that I was playing on 2.6.1 that I updated to 2.7.0 and then I got the new quests/quest requirements with no setbacks that I'm aware of.
This file should be fine to pull outside the world save file *unless* it actually stores some **progress** data? Like just giving a specific file path to pull the quest database when the world is starting?
Step 1: Create a world in version **2.6.1**.
Step 2: Update the pack to version **2.7.0**.
Result: There's no version **2.7.0** quest content showing up because the database file didn't update.
**Alternate** Step: Update from version **2.6.1** to **2.7.0**, and create a new world.
**Alternate** Result: The questbook should be empty. I'm adding this because It might help determine the underlying issue.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
do you use technic launcher?

**Comment by p3rsonUnknown** [comment]
yes, I use technic launcher

**Comment by boubou19** [comment]
turns out the updating module of technic launcher does not erase old files, so you need to do a fresh install to avoid this bug (backup your world first). Nothing we can really do here.
