### ISSUE TITLE
SuperCritical Steam Turbine Multi has no fuel (Not XL Variant)

### ISSUE THREAD

**Issue by Dragonhatch1** [GTNewHorizons/GT-New-Horizons-Modpack#18328]
### Your GTNH Discord Username

Xyrth

### Your Pack Version

2.7.0

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

SC Steam Turbine would accept SC Steam and produce power.

### The Reality

There is no **SC Steam** other than **DENSE SC Steam**, which is only accepted by the XL SC Steam Turbine. 

2nd thought would be the XL SC Steam Turbine would do Dense SC -> SC Steam. Nope. Dense SC -> Dense SH is what happens.

The overall reality is regular SC Steam does not currently exist as an item, thereby rending this multi useless.

### Your Proposal

Easiest would be to have it accept Dense SC Steam? As these multis get capped at 4a with a buffered Dynamo, so it doesnt really break balance. It was feeling like a natural build to do SC Steam Turbine at 4a per turbine -> XL SC Steam Turbine to start getting into my 200a+ LUV. XL SC Steam Turbine does not unlock till ZPM, which still measures up with where your power should be. 

Other Idea would be to create SC Steam? That seems like alot more hassle and balancing than just having it accept Dense SC Steam, but yall are already madmen for this pack so *shrug*. 

Currently, this multi does nothing, so lets make it do something?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Impos913** [comment]
There is regular SC steam, made with lava, hot solar salt or hot coolant in Extreme Heat Exchanger but all the plasmas make dense

**Comment by Dragonhatch1** [comment]
Interesting. You are correct. It looks liek it doesnt show up in the NEI search for whatever reason. We were searching all day yesterday for it. tyvm.
