### ISSUE TITLE
[2.7.0] Steam Input Bus needs a ghost circuit

### ISSUE THREAD

**Issue by PlayfulPiano** [GTNewHorizons/GT-New-Horizons-Modpack#18333]
### Your GTNH Discord Username

PlayfulPiano

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Steam Multis have a built in ghost circuit.

### The Reality

The steam input bus lacks a ghost circuit. But if you manually craft/set a ghost circuit via the LV circuit recipe and put that inside of the steam input bus, then that ghost circuit is recognized and the multi starts running the ghost circuit specific recipe.

### Your Proposal

While yes the steam input bus isn't well, electricity powered per se, it still is a mechanic which is greatly necessary for some of the new steam multiblocks (especially the blender/mixer, where most dust mixing has a non-default ghost bin requirement).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment]
Seems like a reasonable suggestion
