### ISSUE TITLE
Jabba hopper facade increase output rate from items to stacks

### ISSUE THREAD

**Issue by Ruthgar** [GTNewHorizons/GT-New-Horizons-Modpack#18339]
### Your GTNH Discord Username

ruthgar2550

### Your Pack Version

2.7.0-beta-3

### Your Proposal

Not long ago new hopper facade recipe was introduced it pack by bug report #12796
When using this facade in-game it pushes items into item pipes by one instead of stacks of items.
This behavior makes jabba hopper facade almost useless even early game.
IMHO this behavior need to be changed to push stacks of items into item pipes.

### Your Goal

jabba hopper facade is way underpowered in items transfer into item pipes

### Your Vision

jabba hopper facade must push stack of items from better barrel into item pipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
the hopper facade acts exactly like a hopper. that should not change, no.
