### ISSUE TITLE
LSC scanner readout is wrong

### ISSUE THREAD

**Issue by Kyramesh** [GTNewHorizons/GT-New-Horizons-Modpack#18335]
### Your GTNH Discord Username

Kyramesh

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

LSC scanner should give correct acounts of power input and output, so you know how your base is doing in terms of power stability and potential room for scaling.

### The Reality

TLDR: LSCs that are supplying the wireless network report 2x MORE EU input for the mid/long termin EU readouts. LSCs that are withdrawing from the network report 2x LESS EU. This is probably caused by a simple error in the code that calculates these values. The 5s redout is probably unaffected, because it's almost never affected by the wireless power rebalance that happens on a 5 minute timer. 

The result shown by the scanner are inaccurate. It displays 2x the real values for 5 minute and 1 hour avarage readout.
This is the results for my Horus LSC, which is currently being fed by 1 max Dyson:
![grafik](https://github.com/user-attachments/assets/973171c1-b036-45d2-9a6c-4e817099fda5)
(This screenshot shows a nucleacraft information panel with information provided by a metrics transmitter cover. This does just seem to be the same as the scanner readout and so i think the issue lies with what the scanner says/the multiblock outputs as information)
Here is the Power that's being produced for this LSC:
![grafik](https://github.com/user-attachments/assets/f86010e7-5406-4e3e-883c-df6497c77289)
Nothing else is inputting power into this LSC:
![grafik](https://github.com/user-attachments/assets/f730e3a9-8c07-4a79-8d92-97b7430017a5)

Because of this the avarage for 5 minutes and 1 hour should match the 5 seconds value, but the instead show roughly 2x of what the 5 seconds value is. The "EU IN" shows a really large number, 2.2T, which is i assume because of really large EU packets and not something that needs fixing. 

I only noticde this issue after i started to use wireless mode on my LSCs, so i assume it's linked to that somehow. 

My main net LSCs Power Output can't be correct either:
![grafik](https://github.com/user-attachments/assets/e479822d-24af-41e9-ac75-8641fd0011f5)
The 5s value seems to be correct, but this time the 5 minute an 1 hour values are half of that. The latter onces have to be wrong, because i'm feeding my DTPF about 77 B EU/t in a passive process that has run for longer than an hour:
![grafik](https://github.com/user-attachments/assets/3ddae4f2-a447-40f8-8d8e-e3622cb30810)
![grafik](https://github.com/user-attachments/assets/7b61f17f-094f-4feb-8042-8c62d3deb43d)
This LSC is withdrawing power from my wireless network.
iamworking on discord also reported this in the past.

### Your Proposal

Fix. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
i will fix.
