### ISSUE TITLE
BetterQuesting not recognizing raw ores

### ISSUE THREAD

**Issue by MalkavianDream** [GTNewHorizons/GT-New-Horizons-Modpack#18331]
### Your GTNH Discord Username

MalkavianDream

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Attempted to complete a request requiring ore.

### The Reality

Though I mined the required number, the quest did not update, as the quest requires the stone version but the latest update added in raw ores.

### Your Proposal

Update BetterQuesting to recognize the raw ores in addition to original stone versions of ore.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
then you dont have the updated questbook. can be various reasons for that. might be that you are using technic launcher, it does not update the config folder correctly as a whole. or maybe a different launcher and you just kept your old config folder. either way, an install/update issue.
