### ISSUE TITLE
Precise Assembler big lag

### ISSUE THREAD

**Issue by Eranicus** [GTNewHorizons/GT-New-Horizons-Modpack#18347]
### Your GTNH Discord Username

Eranicus#5476

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

This is how precise assembler operate in 2.6.1 (normal mode, not working and around 10 full buffers with recipes)

![Screenshot 2024-12-12 104615](https://github.com/user-attachments/assets/1f1dc4fd-0ab1-407b-b5e2-e30683ddcb24)

And this is the same assembler in 2.7 (same conditions)

![Screenshot 2024-12-12 102449](https://github.com/user-attachments/assets/9f589632-9242-4b61-b109-a64fbdcdc8df)

### The Reality

.

### Your Proposal

fix please.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eranicus** [comment]
I did a bit more tests in new created world  (this lag is during the moment of machine check every 5sec or so)

Precise with x4 normal input bases (no circuits)

![Screenshot 2024-12-14 043821](https://github.com/user-attachments/assets/67ea2f08-c1a4-4a1c-af1a-ccc68a43017a)

Precise with same 4 bases but with circuit nb1 in one of them  (more buses with more circuits, the worst it will get) 

![Screenshot 2024-12-14 044032](https://github.com/user-attachments/assets/a94b61bb-3ba6-4928-9ff5-488e2006782e)

Precise with 2 crafring input buses set for circuit nb1 and with 10 random recipes in each (it will get crazy with lots of recipes)
 
![Screenshot 2024-12-14 044932](https://github.com/user-attachments/assets/3b48942b-09ad-4b7a-8fa5-db484ae77568)

Anyway as im not a programmer and I have no idea why the recipe check was changed this way,  on version 2.6.1 nothing is laging,

If this was intended just close the ticket,

**Comment by HoleFish** [comment]
Should be fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3655
