### ISSUE TITLE
Minecraft running on my integrated GPU

### ISSUE THREAD

**Issue by Damyan23** [GTNewHorizons/GT-New-Horizons-Modpack#18341]
### Your GTNH Discord Username

tamqnko

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

I am not sure what to say here. I am using a laptop and I have 2 gpus - one integrated and one main with the integrated one being weaker. It should not run on the integrated one as it should automatically swap to the more powerful one.

### The Reality

I dont know what to say here.

### Your Proposal

I explained everything in "your expectation"

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
you have to specify to your computer to use explicitely the high perf GPU instead of the iGPU for javaw. Nothing we can do here.
