### ISSUE TITLE
Minecraft crashes whenever I open the Applied Energistics ME crafting terminal.

### ISSUE THREAD

**Issue by Damyan23** [GTNewHorizons/GT-New-Horizons-Modpack#18355]
### Your GTNH Discord Username

tamqnko

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

I was in the ME crafting terminal, I tried to search for gas turbine and it just crashed. It said that the problem was because of ae2 and NEI. After that I got in the server again, opened the terminal, it crashed again and this time it said its only related to ae2.

### Crash Report

[crash-2024-12-12_19.36.25-client.txt](https://github.com/user-attachments/files/18115519/crash-2024-12-12_19.36.25-client.txt)
[crash-2024-12-12_19.39.17-client.txt](https://github.com/user-attachments/files/18115524/crash-2024-12-12_19.39.17-client.txt)
The first crash is the one where both NEI and ae2 caused the problem. The second one is where only ae2 was the problem. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by slprime** [comment]
same issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18265
