### ISSUE TITLE
Change power requirement for final CAL recipe of ZPM Bioprocessors

### ISSUE THREAD

**Issue by mvdstam** [GTNewHorizons/GT-New-Horizons-Modpack#18352]
### Your GTNH Discord Username

maximized3353

### Your Pack Version

2.6.1

### Your Proposal

All CAL recipes take 0.5A of power, making them easy to scale because you can build them in multiples of 4 thanks to wallsharing. The only exception in this, for some reason, is the hypogen-based CAL recipe for ZPM Bioprocessors which don't take 0.5A of power, but rather 1A of power.

I propose the hypogen-based ZPM Bioprocessor CAL recipe to have its power requirement changed from 1A to 0.5A.

### Your Goal

For consistency, as well as being able to wallshare endgame ZPM bioprocessor CAL's in multiples of 4 rather than in multiples of 2. Since CAL's don't take multiamp hatches, players can't scale this tier of CAL's the same way they can't scale _every other_ CAL.

### Your Vision

I believe making the pack more consistent where possible is preferable, also to make upgrading existing (quad-wallshared) factories with higher-tier recipies possible.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
recipes are not going to be designed around your particular setup.

these very low amp recipes are pretty unusual, so if anything the change is going to be the other way around.

**Comment by mvdstam** [comment]
Okay, thanks for your time @chochem !
