### ISSUE TITLE
Add variable extraction to conveyor belts

### ISSUE THREAD

**Issue by Iamworking12** [GTNewHorizons/GT-New-Horizons-Modpack#18360]
### Your GTNH Discord Username

iamworking

### Your Pack Version

2.7.0

### Your Proposal

Allow changing how many items a conveyor belt can export/import per action. 

### Your Goal

Fluids have a way to manage precise movement with regulators. Would be nice to do the same with items without relying on other mods as I have tried them and none come out to be a consistent solution for some automation challenges in late game.

### Your Vision

More variation in the solutions to various automation challenges in the pack.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment]
if anything, precise movement functionality belongs to robot arms, not conveyor belts.

**Comment by chochem** [comment]
> Fluids have a way to manage precise movement with regulators.

so do items, with the (block) regulators instead of fluid regulators. Just gt, no other mods.
This exists already. (not robot arms though)
