### ISSUE TITLE
Twilight Forest Crash

### ISSUE THREAD

**Issue by SynJewels** [GTNewHorizons/GT-New-Horizons-Modpack#18378]
### Your GTNH Discord Username

putinmcshootin#2027

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

in the twilight forest loading new area to find new ores and crashed

### Crash Report

https://mclo.gs/jfgbgyr

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment]
Update the pack

Duplicate ticket of too many others
