### ISSUE TITLE
LV semifluid generator recipe change

### ISSUE THREAD

**Issue by Wyrmlet** [GTNewHorizons/GT-New-Horizons-Modpack#18379]
### Your Pack Version

2.7.0 (stable)

### Your Proposal

Replace the cobalt cable in the recipe for the LV semifluid generator with a tin cable.

### Your Goal

This would unlock an extra power generation option in LV besides steam, which is overall easier to set up than others, but requires a backlog of creosote.

### Your Vision

Besides making energy easier to come by in LV, this would give a use to creosote besides lubricant at that stage in the game, as well as making the recipe more consistent with every other generator available (even semifluid generators from future tiers use a tier-appropriate material). The questbook is also incorrect about the generator being craftable in LV as of right now, so if this was an intentional change, that quest would need to be changed, too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
this is obviously craftable in LV

**Comment by Wyrmlet** [comment]
I've checked it; cobalt needs ardite tools to mine (which in turn need an EBF to get ingots), and the cobalt itself also needs an EBF. I have tried shoving the dusts and ores into a TC smeltery, but it didn't work.

**Comment by LazyFleshWasTaken** [comment]
> I've checked it; cobalt needs ardite tools to mine (which in turn need an EBF to get ingots), and the cobalt itself also needs an EBF. I have tried shoving the dusts and ores into a TC smeltery, but it didn't work.

there are several work around to mining level, one of which is the lv miner, TNT, and gt tools. You also get cobalt as a byproduct of copper ore.

**Comment by Wyrmlet** [comment]
> there are several work around to mining level, one of which is the lv miner, TNT, and gt tools. You also get cobalt as a byproduct of copper ore

True, but still, it's not actually useable until you get an EBF.

**Comment by Wyrmlet** [comment]
After playing with this for a while, this doesn't feel all that bad since creosote can be used for steam power before you can directly burn it for EU. I do feel like this should be communicated though, every other machine uses tin cables so it's easy to miss the cobalt one in this recipe.

**Comment by Nockyx** [comment]
In my opinion it makes no sense for this generator to be gated basically on MV already. All LV generators are tiered the same and i see no reason to desincentivize people to scale creosote oil production, given it needs some degree of automation and isn't just free power.

Also we all know this recipe uses cobalt wire because GT++ likes to be the special kid when it comes to recipes.

**Comment by Pxx500** [comment]
Cobalt gates this gen after EBF so it makes sense to change it to tin just so it can be used as any other gen, it still won't scale nearly as much so players will have to transition to other gens anyway

**Comment by serenibyss** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3719

**Comment by Wyrmlet** [comment]
This is still a thing as of GTNH v2.7.3, with GregTech v5.09.50.118. Did something go wrong, or is this fixed in dev?

**Comment by FourIsTheNumber** [comment]
> This is still a thing as of GTNH v2.7.3, with GregTech v5.09.50.118. Did something go wrong, or is this fixed in dev?

This is not a change that went into 2.7.3. x.x.x versions have specific cherrypicked changes to minimize impact, they're meant to be very minor updates primarily with fixes.

**Comment by Cas-P** [comment]
Is this change not going to be included? I'm on 2.7.4 and it is still the case that u need a EBF for a cobalt wire

**Comment by FourIsTheNumber** [comment]
> Is this change not going to be included? I'm on 2.7.4 and it is still the case that u need a EBF for a cobalt wire

2.7.4 is also a minor version like 2.7.3. The change will be included in 2.8.

**Comment by Cas-P** [comment]
Oh sorry I misunderstood your previous comment, thanks for replying ^^
