### ISSUE TITLE
Luck modifier not working on all ores

### ISSUE THREAD

**Issue by MattIsAderp** [GTNewHorizons/GT-New-Horizons-Modpack#18391]
### Your GTNH Discord Username

usernamesnipe

### Your Pack Version

2.7.0

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

I was mining gypsum and calcite ore, hoping they would drop multiple raw ores 

### The Reality

They all drop 1 raw ore, while things like magnetite drop multiple

### Your Proposal

This could be intended but I remember reading fortune worked on all ores, so that confused me a bit

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
It only works on naturally spawned ores, if you placed ore it will not work. Otherwise, just rng.
