### ISSUE TITLE
Getting random gt.metaitem.02.25335.name in inventory

### ISSUE THREAD

**Issue by wojtakbar** [GTNewHorizons/GT-New-Horizons-Modpack#18394]
### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Not getting random empty item w/o any texture nor craft and use

### The Reality

Sometimes getting up to half stack of this item. Details: gt.metaitem.02.25335.name (#7296/25335) (mod - gregtech), it has sharpness V always, even in stacks

### Your Proposal

Not getting random item.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
this is what happens to removed gt items. apparently you had some gt arrows. Those are gone now
