### ISSUE TITLE
2.7.0 client crashes on startup

### ISSUE THREAD

**Issue by TiSiMo13** [GTNewHorizons/GT-New-Horizons-Modpack#18390]
### Your GTNH Discord Username

tisimo

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Actions

Launching GT_New_Horizons_2.7.0_Java_17-21 with MultiMC 5 Version 0.7.0-3863

java.lang.NullPointerException: Cannot invoke "net.minecraft.util.IIcon.func_94209_e()" because "icon" is null

### Crash Report

[fml-client-latest.log](https://github.com/user-attachments/files/18137353/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
you added ftb mods. that is not going to work since we have serverutilities (same thing mostly)
