### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Chardude** [GTNewHorizons/GT-New-Horizons-Modpack#18392]
### Your GTNH Discord Username

Chardude36

### Your Pack Version

2.70

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Opened the game

### Crash Report

[console.log](https://github.com/user-attachments/files/18137688/console.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
lots of mod duplicates, that cant work. best follow this when installing/updating: https://gtnh.miraheze.org/wiki/Installing_and_Migrating
