### ISSUE TITLE
```java.lang.IllegalStateException: Failed to create Display window```

### ISSUE THREAD

**Issue by DrakeFlame000** [GTNewHorizons/GT-New-Horizons-Modpack#18408]
```java.lang.IllegalStateException: Failed to create Display window``` 
I guess that is the actual error. (I would recommend posting logs as files, that is much easier to read)

that might indicate an issue with graphics drivers/gpu.

_Originally posted by @chochem in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18299#issuecomment-2536589792_
            

this is the error code
https://mclo.gs/Mo3382O

**Comment by chochem** [comment]
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18299. dont open multiple tickets for the same issue please.
