### ISSUE TITLE
The Mining Backpack/Woven Mining Backpack of Forestry cannot hold raw ore

### ISSUE THREAD

**Issue by Archintone** [GTNewHorizons/GT-New-Horizons-Modpack#18416]
### Your GTNH Discord Username

Archintone

### Your Pack Version

2.7.0

### Your Server

2.7.0

### Java Version

Java 8

### Type of Server

None

### Your Expectation

When we are mining, let the Mining Backpack/Woven Mining Backpack can automatically hold the ore, gemstone and raw ore.

### The Reality

This backpack cannot hold the raw ore after the Pack Version 2.7.0, because the excavated ore has turned into the raw ore.
Can this still be called a 'Mining Backpack'?

### Your Proposal

Let the Mining Backpack/Woven Mining Backpack of Forestry add a list of raw ore.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
hmm no that seems to work just fine.

![image](https://github.com/user-attachments/assets/87673460-8184-4322-9a55-69b0dc0a182e)

so 2 options:
1) only some *specific* ore is broken
2) you configs files arent updated or are somewhat broken. For example, there are many people on technic launcher that just press update and assume it works but it doesnt really.

**Comment by Learwin** [comment]
I can also confirm that my mining backpacks pick up raw ore. I had a clean install of 2.7.0 though and did not update from a prior version.

**Comment by Ethryan** [comment]
Ping me again if you find out what ore that won’t go into the backpack.

**Comment by 864004899** [comment]
![F0DEC0E804EADEEC4B915E45B4AB9E72](https://github.com/user-attachments/assets/1717cd6c-8bfc-44d6-baab-252a4b1c07a5)
:(
