### ISSUE TITLE
Loading a backup while quitting old save from respawn screen will cause backpack to disappear

### ISSUE THREAD

**Issue by FredStb** [GTNewHorizons/GT-New-Horizons-Modpack#18421]
### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

When I load a backup, previous saves / states should not impact any files in the world folder.

### The Reality

It's not that uncommon that you die, and want to load a backup. If you go back to main menu in the respawn screen, load a backup, and join the world (without restarting the game), your backpack is gone.

### Your Proposal

A fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment]
Which backpack is it?

**Comment by FredStb** [comment]
The one that is in the backpack slot, from forestry. Also, it's probably connected to, getting killed by something that does 10k+ damage, leaving respawn page via main menu -> loading backup, will give you "Immortal" achievement / 10k damage trophy.

**Comment by Lyfts** [comment]
That's almost certainly fixed by https://github.com/GTNewHorizons/ServerUtilities/pull/156, try updating SU to https://github.com/GTNewHorizons/ServerUtilities/releases/tag/2.1.3

**Comment by FredStb** [comment]
Cool!
