### ISSUE TITLE
Client crash when typing letter "I" into ME terminal

### ISSUE THREAD

**Issue by HydroCNs** [GTNewHorizons/GT-New-Horizons-Modpack#18434]
### Your GTNH Discord Username

HydroCN

### Your Pack Version

2.7.0

### Your Server

private server

### Java Version

Java 20

### Type of Server

None

### Your Actions

Crash happens on both singleplayer and dedicated server

Typed the letter "I" into any ME interface that shows my items in storage, and the game crashes. Server does not crash though

Crash only happens if there is items stored in the ME network, happens for any item. Does not crash when there are no items in the network

Restarting the client stops the crash, not sure what will trigger it again

### Crash Report

https://mclo.gs/KlrL2oq

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by slprime** [comment]
same issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18265
