### ISSUE TITLE
Crash about Advanced Blocking Card

### ISSUE THREAD

**Issue by XC-rzs** [GTNewHorizons/GT-New-Horizons-Modpack#18436]
### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I'm trying to automatically transfer leftover items to the AE main network after Infusion finished.
First of all, I requested more than one(refers to number of item rather than type) item's crafting in the AE main network (only requesting one item's crafting will not cause the game to crash).When I marked these residual items in any slot of the me interface that has Advanced Blocking Card, the game crashed.After that I crashed every time I entered this level.

If you want to replicate this crash, I've found a suggested way.
Requires an AE master network capable of requesting item crafting, two ME Interfaces, a ME Storage Bus, a Chest, and an Advanced Blocking Card.
![007997151ccae1438da246113b0658d5](https://github.com/user-attachments/assets/1a3d37b7-ace8-4050-96dd-2a0c338f5dcc)
The interface of the main network set Blocking mode
The interface of the sub network set Loose mode (Put advanced block cards inside).
Then request more than one (refers to number of item rather than type) item's crafting in the AE main network (Doesn't matter what the content of the pattern is).
Finally, mark the input items (you set in the pattern) in any slot of the subnet ME Interface,the game will crash

### Crash Report

[crash-2024-12-19_19.42.31-server.txt](https://github.com/user-attachments/files/18200337/crash-2024-12-19_19.42.31-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by lordIcocain** [comment]
@XC-rzs looks like crash report didnt uploaded correctly, can you reupload?

**Comment by XC-rzs** [comment]
[crash-2024-12-19_19.42.31-server.txt](https://github.com/user-attachments/files/18200288/crash-2024-12-19_19.42.31-server.txt)

**Comment by XC-rzs** [comment]
> @XC-rzs looks like crash report didnt uploaded correctly, can you reupload?

[crash-2024-12-19_19.42.31-server.txt](https://github.com/user-attachments/files/18200486/crash-2024-12-19_19.42.31-server.txt)
More information I replaced the original upload failed place

**Comment by lordIcocain** [comment]
How you expect this setup should work?

**Comment by XC-rzs** [comment]
I just found out that marking residual items in ME interfaces without advanced blocking cards does not cause crashes.This way I can use the conveyor belt to pull items from the me interface directly back to the main net. Maybe the bug doesn't need to be fixed because it has so few uses and can be circumvented

**Comment by lordIcocain** [comment]
Nah, interface can't push items in interface which requesting items from network.
