### ISSUE TITLE
Macerating purified crushed salt ore provides no borax

### ISSUE THREAD

**Issue by frooploopz** [GTNewHorizons/GT-New-Horizons-Modpack#18435]
### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Macerated Purified crushed salt ore, and expected borax.

### The Reality

but received none out of multiple stacks

### Your Proposal

Ore gets crushed, 10% chance to receive borax

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
you dont get maceration byproducts in lv/mv
