### ISSUE TITLE
Game crashes when opening ME crafting terminal

### ISSUE THREAD

**Issue by hyperlexus** [GTNewHorizons/GT-New-Horizons-Modpack#18448]
### Your GTNH Discord Username

hyperlexus

### Your Pack Version

2.7.0

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

mc crashes on ME crafting terminal open with this error
pattern terminal and fluid terminal work fine*
it worked 1 minute before, i wanted to search for titanium and as soon as i pressed t it crashed
if i change the search in NEI to idk 'heuiahduawd', i go back into the terminal and it crashes again, after which the nei bar will have 't' in it again

pattern terminal crashes when entering 't', after which it will keep crashing until I clear the T out of the search bar using the fluid terminal. it crashees with this error: 
![image](https://github.com/user-attachments/assets/22575cae-a60b-4df1-aa8c-64ba7b2c67a9)

the crafting terminal always crashes with the crash report below.

### Crash Report

[crash-2024-12-20_11.47.05-client.txt](https://github.com/user-attachments/files/18209987/crash-2024-12-20_11.47.05-client.txt)
[crash-2024-12-20_12.01.05-client.txt](https://github.com/user-attachments/files/18209988/crash-2024-12-20_12.01.05-client.txt)

(different crashes)

this seems to not be reproducible as the other person on the server can use the terminals just fine.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by slprime** [comment]
same issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18265
