### ISSUE TITLE
conspicuous features with ingot smelting and bolt textures

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#18454]
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.7.1

### Your Server

Zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Two cases with naquadria:
1) No textures for naquadriabolt -> also for other materials
2) Naquadria ingots can't smelt into fluid, plate or other can be 

### The Reality

1) bolt: 
White field, instead of Bolt texture (Tested with original texturepack and MISA).
![grafik](https://github.com/user-attachments/assets/b65cf929-b18c-499e-a7b2-0561277cdd7d)

2) ingot:
no receipt for ingot smelting, but nugget
![grafik](https://github.com/user-attachments/assets/35bed391-53b2-4679-b93b-0971934b996e)

### Your Proposal

1) reactivation of Bolt texture

2) Ingot smelting should similar to all other material parts like plates

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment]
Can confirm the issue with bolt textures. For naquadria ingot, some things recently moved, and naquadria ingot -> fluid in fluid extractor was moved from the recycling tab to the normal tab. Do you see it in the normal tab?

**Comment by Ngar1** [comment]
Recycling contain all parts but no ingot. Ingot is the only which is available fluid extractor. Tested wiht fluid naquadria.

**Comment by serenibyss** [comment]
This is an intentional change
![image](https://github.com/user-attachments/assets/f71e9151-f3f0-492d-acd3-af7b13971ee5)

For bolt textures, the issue only occurs on Java 8. Working on a fix now

**Comment by serenibyss** [comment]
Bolt issue fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3678, ingot change is intentional

**Comment by DYstebo** [comment]
The game crashes on start if not using JRE 1.8 using the Curseforge installation. I have tried starting it with Java 17, Java 21, and Java 23 with no luck on any.
Log is attached for an attempt to launch with Java 17 as requested.
[launcher_log.txt](https://github.com/user-attachments/files/18267983/launcher_log.txt)

Suggesting a change in the Curseforge release of 2.7.1 to force it to use Java 17.
