### ISSUE TITLE
Lapotronic Supercapcitor Shuts Itself Off, Disabling My Entire Base. No Special Errors Displayed

### ISSUE THREAD

**Issue by Shaunythunder** [GTNewHorizons/GT-New-Horizons-Modpack#18453]
### Your GTNH Discord Username

Shaunythunder

### Your Pack Version

2.7.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

LSC should stay on during normal operation, like in any version before 2.7.1.

### The Reality

My LSC will not stay online no matter what I try. It will stay on for a random short period of time and then will turn itself off. Breaking the LSC cause it to stay on and then shut itself off later. There are no special errors or anything indicating that I did anything wrong or that there is a new requirement as of 2.7.1. The LSC also gains power a 327,680 per tick after breaking, even though I cut the power to it and not a single EU is going in.

I have a theory that as soon as the machine hits 100% charge it will shut off. Putting an always on cover "fixes" the issue but it basically cycles on and off at 30-60 hz which makes anything that reads the system like NIDAS completely unusable. At LuV, the game is still technically playable, but I would consider this as game breaking. Attached a video of the issue happening.

https://github.com/user-attachments/assets/20e99566-6539-4d9a-8992-487400b51302

### Your Proposal

If my theory is correct and the LSC shuts itself off upon reaching 100%, fix it so that it does not shut off. Otherwise fix the LSC so that it runs.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment]
Can you describe your setup in more detail? What capacitors, what energy input and output

**Comment by Shaunythunder** [comment]
> Can you describe your setup in more detail? What capacitors, what energy input and output

When the system is fully running I got 48 amps EV and 24 A IV. I have 18 capacitors IV in the LSC. Attached are pictures of it running on 2.7.0


![2024-12-20_11 21 21](https://github.com/user-attachments/assets/10de780c-9a49-43c7-8b99-da932d54004e)
![2024-12-20_11 22 18](https://github.com/user-attachments/assets/46079721-bf01-47ae-9091-0a7745babd0d)
![2024-12-20_11 22 04](https://github.com/user-attachments/assets/a4aae038-7caa-45ec-99d5-9b46a5b5ca82)
![2024-12-20_11 22 10](https://github.com/user-attachments/assets/86480dda-5245-49cc-bf71-f42d8072aa13)
![2024-12-20_11 22 15](https://github.com/user-attachments/assets/478f4b50-c4bf-4daf-a148-6385ae99a7a2)
