### ISSUE TITLE
restone alloy before machines

### ISSUE THREAD

**Issue by yagdra-nihlahorn** [GTNewHorizons/GT-New-Horizons-Modpack#18458]
### Your Pack Version

2.7.0

### Your Server

singleplayer

### Java Version

Other versions in between

### Type of Server

Single Player

### Your Expectation

i was smelting my ores down in a tinker's smeltery and it created red alloy, i proceeded to cast and pickup that ingot. later the ingot auto changed to Redstone alloy just like how different mods' ingots will be changed into one type to prevent problems. i was told we werent supposed to be able to do this so im reporting it

### The Reality

n/a

### Your Proposal

n/a

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DownerCase** [comment]
Just checked on 2.7.1 and the smeltery produced a ProjectRed Red Alloy Ingot which, after a few seconds in hand, turned into a **red alloy** ingot; not a _**redstone**_ alloy ingot.
