### ISSUE TITLE
Betterquesting 'How to Make Rubber' does not detect Raw Ores as Ore Blocks

### ISSUE THREAD

**Issue by McDuck** [GTNewHorizons/GT-New-Horizons-Modpack#18468]
### Your Pack Version

2.7.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Getting closer to completing the quest when mining the required Ore Blocks.

### The Reality

Since the latest update (I'm using Technic Launcer) I'm only collecting Raw Ores when mining instead of prior Ore Blocks.
One of the next quests I was doing was 'How to Make rubber' quest. However it does not detect any mined Ore Block, ofcourse because I can only receive Raw Ores when mining Ore Blocks. Also when I'm pressing the Detect/Submit button it does not detect them. Any idea what I'm doing wrong?

![GregtechHowToMakeRubber](https://github.com/user-attachments/assets/e70930c3-63b5-4b63-96e4-0abd5d73dc7c)
![GregtechRawOres](https://github.com/user-attachments/assets/b044ae21-fb03-4904-85c8-a67a68e8e707)

### Your Proposal

A way to complete the quest.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment]
Make sure you update correctly and don't forget the config folder.
If its technic launcher, don't trust the update button
