### ISSUE TITLE
Artificial universe storage cell Not crafting with quantum circuit

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#18466]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

271

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

i can craft it with quantum circuit

### The Reality

![image](https://github.com/user-attachments/assets/0acad5f5-b438-456b-8f54-c703a5fea92f)

i can craft it with "any UXV circuit" but not quantum circuit

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
very sorry, wrong pattern

**Comment by chochem** [comment]
it shows in nei that it should work. but maybe that is not true.

Do you have the same problem for other space assembler recipes with circuits?

**Comment by chochem** [comment]
also make sure the battery is fully charged of course

**Comment by miaowwwwww** [comment]
the battery is fully charged of course

**Comment by miaowwwwww** [comment]
i usually just use "any xxx circuit" for everything, haven't try others
