### ISSUE TITLE
ME Chest does not connect via Wireless Connector

### ISSUE THREAD

**Issue by Ruling-0** [GTNewHorizons/GT-New-Horizons-Modpack#18464]
### Your GTNH Discord Username

ruling_

### Your Pack Version

2.7.1

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

As worked on RC3, place a wireless connector on an ME chest, then on an ME controller, and the ME chest should work given the network has power.

### The Reality

The ME chest no longer works, and the wireless connector shows 0 channels. Running a cable from the wireless connector to the ME chest works.
![image](https://github.com/user-attachments/assets/752aac32-5102-42e3-a9b0-84b60afa5852)
![image](https://github.com/user-attachments/assets/a0196b08-56f5-4b6b-99c5-63cb1a8bdba9)

### Your Proposal

Restore the functionality of wireless connecting the chests.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment]
ME chests now work like other AE2 parts and connect based on their color rather than always connecting

**Comment by Ruling-0** [comment]
Nevermind, this is because sprayed chests now do not connect to mismatched colors, which is likely better functionality.
