### ISSUE TITLE
For Multiblocks, append their acronym in their descriptions

### ISSUE THREAD

**Issue by Lxran** [GTNewHorizons/GT-New-Horizons-Modpack#18486]
### Your GTNH Discord Username

Lxran

### Your Pack Version

2.7.0

### Your Proposal

Edit the description of multiblock machines such that they have their acronym in their description, similar to how it is on EEC, seen here:

![EEC](https://github.com/user-attachments/assets/c879053b-e4cd-4110-9b75-2f951fc9eaff)

### Your Goal

GTNH has *a lot* of multiblock machines, and the community does like to throw acronyms, like EEC, PrAss, Assline, etc. I am aware of the existence of `!wtf` on the Discord server, but for sake of convenience (and satisfying my and many other players' laziness) just being able to search `EIC` to search for `Extreme Industrial Greenhouse` for example is better.

### Your Vision

Makes NEI easier to use, lets people learn the acronyms/lingo faster, reduces use of `!wtf` (even though it's a hilarious command).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by CrystieColon3** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/3560
This PR of mine i think does exactly what you proposed, except maybe it misses some common acronyms that i wasn't able to gather from people i asked, if you have any suggestions i didn't include be sure to share them so i know what more to add

**Comment by boubou19** [comment]
i'm not sure what is the suggestion here, as it is already implemented in 2.7.0 / 2.7.1
![image](https://github.com/user-attachments/assets/eb3befb3-a40d-431b-b8d6-5cddb8be8e2b)

**Comment by Lxran** [comment]
Oh.

Definitely not in 2.7.0 proper, but probably in 2.7.1. I'll update and take a look, ty 💖

I think I just missed this change in changelog from 2.7.0 to 2.7.1. It was a lot of links and I didn't check them all, so apologies for wasting time.
