### ISSUE TITLE
Unreasonable lag while holding RMB with food in hand and full food bar

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#18488]
### Your GTNH Discord Username

Pxx500

### Your Pack Version

2.7.1 and before

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Game not lagging while doing stuff with food

### The Reality

Holding RMB while having food in your hand and having full food bar will make the game lag, I consistently see drop of FPS from 60 to 54 with vsync on and from ~530 to ~430 w/o vsync
Moving while holding RMB (for example while harvesting crops) will reduce FPS even further
With a macro I can get to  ~1FPS or less

### Your Proposal

Fix whatever is lagging this much

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ItzPix3l** [comment]
Noticed that same thing happens when trying to till dirt(or already tilled farmland) or just right clicking a fence, might be an issue with how mc 1.7 handles in-world interactions(though im not sure what that would have to do with eating food)

**Comment by C-Remilian** [comment]
Same with Thaumcraft staves, both without and with an equipped focus (tested with Illumination, Charging, Warding, but Flux scrubber does not lag for some reason).
Also lag: (almost) all GregTech tools (including simple ones like picks and shovels), Hose (Adventure Backpack, any mode), Smoking Pipes with no tobacco (Thaumic Bases), Bow with no arrows (vanilla), Rapiers Bows and Crossbows with and without ammo (Tinker's Tools)

Do not lag (out of RMB-action items): Wand of the Forest (Botania), Tinkers' Tools with no RMB actions like picks and hammers (just to contrast against GregTech no-RMB items), Primordial Gauntlet and Arcane Abacus (Witching Gadgets), Thaumometer, Memory Card (AE2), Conduit Probe and Yeta Wrench and Soul Vials (EnderIO), Portable Scanner (Gregtech), Ofanix (Ztones), Covers (GregTech)

**Comment by Pxx500** [comment]
Client
https://spark.lucko.me/3p4cfUV1Jd

**Comment by Pxx500** [comment]
> Noticed that same thing happens when trying to till dirt(or already tilled farmland) or just right clicking a fence, might be an issue with how mc 1.7 handles in-world interactions(though im not sure what that would have to do with eating food)

I can't replicate that

**Comment by Pxx500** [comment]
> Same with Thaumcraft staves, both without and with an equipped focus (tested with Illumination, Charging, Warding, but Flux scrubber does not lag for some reason). Also lag: (almost) all GregTech tools (including simple ones like picks and shovels), Hose (Adventure Backpack, any mode), Smoking Pipes with no tobacco (Thaumic Bases), Bow with no arrows (vanilla), Rapiers Bows and Crossbows with and without ammo (Tinker's Tools)
> 
> Do not lag (out of RMB-action items): Wand of the Forest (Botania), Tinkers' Tools with no RMB actions like picks and hammers (just to contrast against GregTech no-RMB items), Primordial Gauntlet and Arcane Abacus (Witching Gadgets), Thaumometer, Memory Card (AE2), Conduit Probe and Yeta Wrench and Soul Vials (EnderIO), Portable Scanner (Gregtech), Ofanix (Ztones), Covers (GregTech)

I've tested with thaumcraft staff, seems to be the same thing
https://spark.lucko.me/rKcKbDrklw
