### ISSUE TITLE
Cant add fourth pattern capacity card to dual interface

### ISSUE THREAD

**Issue by Stoo42** [GTNewHorizons/GT-New-Horizons-Modpack#18484]
### Your GTNH Discord Username

Stoo42

### Your Pack Version

2.7.1

### Your Server

Private Server

### Java Version

Java 17 for server, Java 21 for client

### Type of Server

Vanilla Forge

### Your Expectation

I have a dual interface against an EV assembler. It has three pattern capacity cards in it.
I tried to add a fourth card, but it would not accept it.
I then shift clicked the card in my inventory, expecting it to be added to the capacity slots, but it does not. 

### The Reality

Expected the fourth card to be added, however, this card just goes into my AE2 storage. I have a wireless crafting terminal with a magnet card.
When I try this again without the wireless terminal in my inventory, all hell seems to break loose, with all the contents of the dual interface being dumped out.
I can put back three of the cards, and the patterns I have, but still the fourth pattern capacity card cannot be added.

### Your Proposal

Allow dual interfaces to accept four pattern capacity cards.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Three is the maximum. There are only four rows in an interface, and the first is unlocked by default.

**Comment by Stoo42** [comment]
> Three is the maximum. There are only four rows in an interface, and the first is unlocked by default.

Ah man, I was _so_ sure that I'd maxed out the slots with capacity cards before... :-/

**Comment by Dream-Master** [comment]
@Stoo42 welcome back btw. Long time not seen you 😎
