### ISSUE TITLE
Velocity Issue

### ISSUE THREAD

**Issue by Avalanche7CZ** [GTNewHorizons/GT-New-Horizons-Modpack#18505]
### Your GTNH Discord Username

Avalanche7CZ

### Your Pack Version

2.7.1

### Your Server

Every server thats uses a Proxy

### Java Version

Java 21

### Type of Server

Crucible

### Your Expectation

To join

### The Reality

Unable to connect to a server that is behind a proxy (Velocity)
Last working version: 2.6.1
With 2.7.+ its dont work

Logs:
https://pastes.dev/4yAj3Tr3tV
https://pastes.dev/PoxAC7LuKP
https://pastes.dev/8fMK7Qktge

Alp on official discord:
"my best guess is ae2 related.
opis remove client-side errors decoding
all left is to guess what is kicking"

Reproduce:
- Download Latest version of Velocty
- Crucible server with latest version of modpack
- Setup the proxy and server etc..
- Try to connect to the server

### Your Proposal

Fix?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
yeet Opis server and client side and try to check it. Also Velocity is highly unsupported. We might be able to fix it but it's low priority.

**Comment by Zilacon** [comment]
I am also having this issue on bungeecord with this error: https://pastes.dev/7isLJbWhOz

**Comment by superhealing** [comment]
By setting 
```
    # Fix an overflow of the dimension id when a player logins on a server [default: true]
    B:fixLoginDimensionIDOverflow=false
```
worked, due https://github.com/GTNewHorizons/Hodgepodge/pull/341

**Comment by Avalanche7CZ** [comment]
Yep fixed my Velocity issue
```java
B:fixLoginDimensionIDOverflow=false
B:increasePacketSizeLimit=false
```

**Comment by boubou19** [comment]
i guess we can close this then

**Comment by boubou19** [comment]
we could, but that means we must keep track of each problem corresponding to each proxy and all. That's going to be a burden for something we don't support.

**Comment by Dream-Master** [comment]
i mean a message in the config option not mean to turn this off by default
