### ISSUE TITLE
Wireless assenbly line Reception Connector crashing AALs

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#18518]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

build 789

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

wireless datastick hatch working

### The Reality

u can't get AALs(possibly all assembly lines) to work with wireless data, if u have a regular data hatch, it is fine.

here is a vid for the issue:
https://discord.com/channels/181078474394566657/522098956491030558/1321780082087297036

### Your Proposal

tbh idk what caused this, i looked at the prs but did not see any recent changes on wireless data hatch.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
after reboot issue still happens? i had same issue on rc-3, but after reboot all fine.

**Comment by miaowwwwww** [comment]
click reboot does not help, it goes back to crash again

**Comment by Dream-Master** [comment]
On zeta there some unmerged prs as pre tags . From ae2 core mod and gt for sure. Or did it crash with regular mod version as well ?

**Comment by miaowwwwww** [comment]
cause written here #18548, closing this.  dup
