### ISSUE TITLE
Greek Translations

### ISSUE THREAD

**Issue by mgiannopoulos24** [GTNewHorizons/GT-New-Horizons-Modpack#18515]
### Your GTNH Discord Username

DeathwishXXIV

### Your Pack Version

2.7.1

### Your Proposal

I propose adding Greek translations for the modpack to make the game more accessible to Greek-speaking players.

### Your Goal

Greek-speaking players might struggle to understand the modpack’s content, limiting their ability to enjoy and engage with the game.

### Your Vision

Adding Greek translations will make the mod more inclusive, allowing Greek-speaking players to fully experience the game and encouraging a broader player base.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment]
please look at the guidance at https://discord.com/channels/181078474394566657/1213877739937865808

**Comment by chochem** [comment]
as well as https://discord.com/channels/181078474394566657/1211326539648729200
