### ISSUE TITLE
Molten Cf lost a recipe

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#18517]
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

build 789

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

![3729cbeff6d21e5e9c8d2f587b7ad9a9](https://github.com/user-attachments/assets/78756fb4-c6d9-4037-a893-833f2dc93816)

### The Reality

![ebf5ed83e803b6bf7fef224fa66fd51a](https://github.com/user-attachments/assets/e29331cd-7c38-409c-9e90-c16ac77a3d44)

### Your Proposal

add back

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by StaffiX** [comment]
This is intentional
https://github.com/GTNewHorizons/GT5-Unofficial/pull/3695

The other recipe is worse in terms of production due to losing the overclock and extra parallel than the mk3 one
