### ISSUE TITLE
Brick Dust Missing Recipe

### ISSUE THREAD

**Issue by DarkScorpyon** [GTNewHorizons/GT-New-Horizons-Modpack#18516]
### Your GTNH Discord Username

DarkScorpyon#8242

### Your Pack Version

2.7.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Brick Dust recipe from macerating Bricks (block) is not showing, but it works

### The Reality

Macerating Bricks give you proper Dust, even if there's no recipe on the recipes list

### Your Proposal

Add recipe properly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
Did you check the macerator recycling tab

**Comment by miaowwwwww** [comment]
![image](https://github.com/user-attachments/assets/91a33098-04ff-4e04-b306-380f250bf656)
four is right
