### ISSUE TITLE
Quests not showing

### ISSUE THREAD

**Issue by Ell618** [GTNewHorizons/GT-New-Horizons-Modpack#18522]
### Your Pack Version

2.7.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Opened the quest book to see what was availble

### The Reality

there are no quests showing at all

### Your Proposal

please bring back quests lol

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment]
If using technic, try not doing that

**Comment by chochem** [comment]
Make sure to install the pack priperly
