### ISSUE TITLE
Follow button for craftings jobs does not update without closing the GUI

### ISSUE THREAD

**Issue by Baerschen** [GTNewHorizons/GT-New-Horizons-Modpack#18521]
### Your GTNH Discord Username

Baerschen

### Your Pack Version

2.7.1

### Your Server

Private Server

### Java Version

Other versions in between

### Type of Server

Vanilla Forge

### Your Expectation

When I press the button to follow crafting jobs I should get feedback that I now follow it 

### The Reality

The button for following crafting jobs does not update and say "followed" without closing the GUI and reopening it which led to me to believe it didnt work at first. Four told me I should close the GUI so others encounter the bug aswell and it should be easily reproduceable 

### Your Proposal

Thats probably a bug causing it and that should be fixed

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment]
the author of the function know about this since the start. It has been this way. It has something to do with crafting statues change and refreshing. I'm no expert. He can explain it better @MCTBL .

**Comment by Baerschen** [comment]
Ah well sounds like a pain  to deal with but a great feature none the less.

**Comment by MCTBL** [comment]
That gui will only reflashing when your crafting status is changing. Not only that **FOLLOW** button, but also the [elapsed time](https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/491) counter at the top of gui
