### ISSUE TITLE
Recipe broken: LuV Solenoid Superconductor Coil is uncraftable

### ISSUE THREAD

**Issue by MarloGr** [GTNewHorizons/GT-New-Horizons-Modpack#18536]
### Your GTNH Discord Username

mako_g

### Your Pack Version

2.7.1

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

The recipe for **LuV Solenoid Superconductor Coil** takes a 2-stack of **540K Sp Coolant Cells**, which are unstackable. Crafting is impossible unless a 2-Stack of the item is cheated in via NEI. Putting 2 single Coolant cells in any configuration does not work.
![image](https://github.com/user-attachments/assets/638a9971-0764-4cc1-93c9-aac26ca577b4)

### The Reality

The recipe is impossible without using NEI cheat mode.

### Your Proposal

Split the stack for the recipe to take 2 single 540K Sp Coolant Cells.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment]
Fixed in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/1112 (though, you can work around this in the mean time with a stocking bus)
