### ISSUE TITLE
Server not starting after updating

### ISSUE THREAD

**Issue by Atpxmelody** [GTNewHorizons/GT-New-Horizons-Modpack#18534]
### Your GTNH Discord Username

atpxmelody

### Your Pack Version

2.7.1

### Your Server

BisectHosting

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

I updated through the website

### Crash Report

https://mclo.gs/ROymXO1

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment]
You have lots of mod duplicates, that cant work. Just a incorrect updating process, best reinstall from scratch at this point after securing your data.
