### ISSUE TITLE
Most AE Autocraft requests fail to initiate

### ISSUE THREAD

**Issue by Rubijox** [GTNewHorizons/GT-New-Horizons-Modpack#18533]
### Your GTNH Discord Username

Rubijox

### Your Pack Version

2.7.1

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Request an item via autocrafting.
Request works and begins crafting the items.

### The Reality

Request an item via autocrafting.
No items are missing, pressing start does nothing at all.
pressing shift start on the select amount menu also fails to start the craft.

### Your Proposal

I have tried multiple auto-crafts, even trying to make items earlier in the crafting tree, some auto-crafts work, others don't.
auto-crafts that have fluids in them have a higher tendency to fail, but not all of them are broken.

I have also tried to update AE to latest (beta-508 at the time) and the issue still persists.

Issue is present in both 2.7.0 and 2.7.1.
Issue is also present in singleplayer.
Nothing shows up in either client or server logs.

here are a few recipes that fail to initiate:

Inert machine casings
![image](https://github.com/user-attachments/assets/92ba2fc9-8cf8-4e80-bf27-2c52c52d0f28)
EV circuits(nano)
![image](https://github.com/user-attachments/assets/7df81fd0-afa3-4709-a6f5-41aacab5ab51)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by lordIcocain** [comment]
Can you share world?

**Comment by Rubijox** [comment]
it's currently uploading, ill edit this comment with the link in 10-15 mins
