### ISSUE TITLE
crystalline alloy ingot has two identical recipes in the fluid extractor

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#18560]
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.7.1

### Your Server

delta

### Java Version

Java 21

### Type of Server

Thermos

### Your Expectation

only get one of these: 
![image](https://github.com/user-attachments/assets/119bb935-c4ad-4c71-b782-b43a31665eb1)

### The Reality

i got two identical recipes

### Your Proposal

remove the dupe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment]
same for energetic silver

**Comment by boubou19** [comment]
![image](https://github.com/user-attachments/assets/1189652a-1128-413a-b922-115a577bb919)

looks like the oredict is going wild

**Comment by StaffiX** [comment]
This is the https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17933 issue, which will be fixed after the new material system
