### ISSUE TITLE
Massive lags when changing world

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#18572]
### Your GTNH Discord Username

Pxx500

### Your Pack Version

2.7.1

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Not having massive lags for 10sec whenever teleporting (be it interdimensional or not)

### The Reality

Teleporting to another location (for exaple overworld -> pdim) causes massive lags.
During teleportation RAM caps to 8GB twice, after increasing max RAM to 16GB the issue is less severe but still noticeable.
While 16GB is allocated the game can still jump from 3,5GB to 16GB and force a GC (though sometimes it just doesn't), meaning the game uses massive amounts of RAM while loading the world.
The teleportation from OW base (which has many machines) can be less laggy then teleportation to pretty much empty pdim at times

Using normal Java GC seems to perform better than ZGC while teleporting but is unplayable for me due to lags on normal GC.
ZGenerational seems to perform better than ZGC but is still very laggy while teleporting.

The issue does not seem to be affected by angelica much but I think my findings about this might be inconclusive
I tried to profile the game during teleportation with YourKit, here is the collected data:

Allocation:
[Allocation-telemetry.csv](https://github.com/user-attachments/files/18271013/Allocation-telemetry.csv)

Threads:
[Allocation-telemetry-threads.csv](https://github.com/user-attachments/files/18271012/Allocation-telemetry-threads.csv)

Flame Graph:
![Allocation-flame-graph](https://github.com/user-attachments/assets/8900ab66-feca-4de3-b22b-5a823a5a21e4)

### Your Proposal

Investigate and fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment]
This is what I get on 8GB ram with ZGC:
https://github.com/user-attachments/assets/f7a3709e-22e9-48ef-826c-3a1edbe40bc9

This with 16GB ZGenerational:
https://github.com/user-attachments/assets/3e9481c7-ac6d-4abd-a008-ebd24bb49466

**Comment by Lyfts** [comment]
NEI`s TooltipFilter & CollapsibleGroup are taking up some awfully big spots on that flame graph. 

This is probably related to  https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18565. Seems like NEI has some pretty major performance issues atm.

**Comment by Pxx500** [comment]
possibly fixed by https://github.com/GTNewHorizons/NotEnoughItems/pull/583
