### ISSUE TITLE
Download of additional files failed

### ISSUE THREAD

**Issue by ItsNeverLight** [GTNewHorizons/GT-New-Horizons-Modpack#18587]
### Your GTNH Discord Username

NeverLight

### Your Pack Version

2.7.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

1. Download Modpack.
2. Start.
3. Error + crash! 

https://downloads.gtnewhorizons.com/Mods_for_Twitch/Thaumcraft4Tweaks-1.5.28.jar
"Not Found"

![image](https://github.com/user-attachments/assets/913343af-4a0e-4589-80df-e0623efa3bc6)
![image](https://github.com/user-attachments/assets/627dcda9-01d6-4ef2-b743-ceff18482271)

### Crash Report

Ln 2240
[fml-client-latest.log](https://github.com/user-attachments/files/18283251/fml-client-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment]
@ItsNeverLight just redownload from curse in 5 mins. i fixed the problem. make a new instance and delete the old one.

**Comment by Dream-Master** [comment]
i just run the newest curse pack and i can join my server. Issue is fixed

**Comment by ItsNeverLight** [comment]
I checked it out. Everything is fine now. **_Спасибо._**
