### ISSUE TITLE
2.0.0.0 Galacticraft lander gets stuck

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/GT-New-Horizons-Modpack#1967]
#### Which modpack version are you using?
2.0.0.0
#
#### If in multiplayer; On which server does this happen? 
Multiplayer private server
#
#### What did you try to do, and what did you expect to happen?
Landed on a planet, tried to open a lander and it didn't open the GUI. The lander can't even be destryoed. This means that the player gets stuck on the planet without a way to get back until they run out of oxygen.

**Comment by Dream-Master** [comment]
Is this area maybe protected ?. Did it work in sp @Lainiel ?

**Comment by Lainiel** [comment]
It doesn't happen every time. The area is not protected. It didn't happen to me in singleplayer yet.

**Comment by Dream-Master** [comment]
Galaxy space and Galacticraft not updatet since (GC 29.07.2017 and GS 24.11.2016)

**Comment by Dream-Master** [comment]
@Lainiel can you open up an issue here ?
https://github.com/micdoodle8/Galacticraft/issues

**Comment by Lainiel** [comment]
It might be related to this issue. Should I open a new one?
https://github.com/micdoodle8/Galacticraft/issues/2914

**Comment by Dream-Master** [comment]
@Lainiel Add more info there below. Describe the error.

**Comment by ko5h** [comment]
This problem occurs if you leave the boarding module before landing

**Comment by Dream-Master** [comment]
ah ok. @ko5h Can you open up a issue for it because i am not sure if this is similar to the posted one by @Lainiel

**Comment by ko5h** [comment]
I can open a new issue ... but the problem is identical with @Lainiel (open a lander and it didn't open the GUI. The lander can't even be destryoed.)
it is necessary to clarify with @Lainiel , did he get out before landing or after?

**Comment by Dream-Master** [comment]
@ko5h sure do that first.

**Comment by Lainiel** [comment]
The first time it happened I got disconnected while I was going to the moon right when I was transfering to the moon dimension. After I reconnected to the server I wasn't in the lander and fell down to the surface. The lander was on the surface and couldn't be opened. I used creative mode to fly up and look if it wasn't stuck in the air. And sure enough there was another lander flying in the air that wasn't moving and was stuck there. Both of them couldn't be destroyed or opened.

The second time it happened was on mars. And if I remember right I did exit the module a short while befire it stopped moving. It couldn't be opened or destroyed as well.

I was away for a few days and completely forgot about the isssue, sorry about that.

**Comment by ko5h** [comment]
well  https://i.imgur.com/CChB5Cs.png tested in sp
The problem is relevant to everything described above, If you leave the boarding module before full boarding

**Comment by Dream-Master** [comment]
Nothing i can do here.
Please open up an issue on Galaxy space and Galacticraft side thanks.

**Comment by Prometheus0000** [comment]
We should be able to fix this ourselves now.
