### ISSUE TITLE
[Suggestion] Lower Poison duration of "Alchemist" Infernal Mobs

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/GT-New-Horizons-Modpack#2033]
The duration seems too high to me. I usually get struck for 24-30 seconds poison which takes all 10 hearts and more.
~10 seconds seems more appropriate to me.

**Comment by Drobac** [comment]
+1

**Comment by Dream-Master** [comment]
The code is open source but i guess i not that advanced in programming to change it.

**Comment by Dream-Master** [comment]
we have now a config option so lets test and we can adjust values later.
