### ISSUE TITLE
[Bug] Automagy Glowing Amber Research missing aspect

### ISSUE THREAD

**Issue by DukeGrimm** [GTNewHorizons/GT-New-Horizons-Modpack#2070]
#### Which modpack version are you using?
2.0.1.0
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
I was trying to research Glowing Amber. I placed the research on the research table. There should be two or more aspects you need to connect in the research grid in order to complete your research into that subject.
#
#### What happend instead? (Attach screenshots if needed)
The research grid opened but only had one aspect in the grid. T His did not prevent me from researching it. I was able to research it by adding one aspect to connect to the one on the grid.
#
#### What do you suggest instead/what changes do you propose?
The research recipe needs to have one more aspect added for glowing amber.

**Comment by Dream-Master** [comment]
Automagy not neferd rn. Will do this in the future

**Comment by SirAzazel** [comment]
Not a bug.
```java
(new ModResearchItem("NITORLIGHT", (new AspectList()).add(Aspect.LIGHT, 2), -5, 0, 1, new ItemStack(ModBlocks.translucent, 1, 32767))).createPages(new Object[]{"1", new ItemStack(ModBlocks.translucent), new ItemStack(ModBlocks.translucent, 1, 1)}).setParentsHidden(new String[]{"NITOR"}).setSecondary().registerResearchItem();
```

**Comment by Dream-Master** [comment]
Ok but i will change the recipes anyway so for me a reminder.

**Comment by SirAzazel** [comment]
Whats the point though? block doesnt do anything much, its just amber block.. that glows. thats all. no need to overcomplicate it, default recipe is already nerfed due to materials used for it being harder to make.

**Comment by Dream-Master** [comment]
Automagy not nerfed yet will do later
