### ISSUE TITLE
Large plasma generator. 2 bugs.

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/GT-New-Horizons-Modpack#2167]
2.0.1.3 singleplayer

1. "Needs maintenance cover" always emit signal "rotor needs maintenance".
2. Sometimes all Large plasma generators change status from "enabled" to "disabled"(until no have plasma). Sometimes my base deenergized, because automated plasma generators not started.

**Comment by Dream-Master** [comment]
@Technus any idea.

**Comment by Prometheus0000** [comment]
Is this still happening?

**Comment by johnch18** [comment]
> Is this still happening?

Why are you necroing threads bro

**Comment by Prometheus0000** [comment]
So that they can be closed if they're not still relevant.

**Comment by yukieiji** [comment]
The second issue also occurs in the current version.
