### ISSUE TITLE
Infernal mobs Fixes

### ISSUE THREAD

**Issue by damug** [GTNewHorizons/GT-New-Horizons-Modpack#2176]
#### Which modpack version are you using?
2.0.1.3

I believe when an infernal mob that has the choking ability attacks you and you kill it before the effect wears off (possibly) the little air bubbles for the choking effect never go away.  

I tried killing myself with the /kill command first to attempt to remove them.

Then I tried reconnecting to the server (a personal one).

Then I tried drowning myself to remove them.

Then I tried reconnecting to the server again (still no dice).

Finally, restarting and reconnecting the server didn't appear to fix the issue.

I've also attempted to search google for solutions, but was unable to find any, even though this bug with choking mobs is reported as early as 2014.

Any help or guidance would be most appreciated.  Thanks!

P.S. moronwmachinegun wants me to post asking for reflect and ninja to be removed from the template for infernal mobs as well.  He'll have to post for specifics on those two.

**Comment by richardhendricks** [comment]
I was kinda sorta joking-not joking about those two.

**Comment by damug** [comment]
![image](https://user-images.githubusercontent.com/29874719/32479354-44b35e28-c33e-11e7-9830-eae391aef482.png)

Pictures!  My hunger/air bar has looked like that for about an hour now.

**Comment by damug** [comment]
Was finally able to force spawn another infernal mob with choking, and managed to get the effect to go away.

**Comment by Dream-Master** [comment]
Fell free to recode or change stuff you don't like. Infernal mobs are open source mod.

**Comment by alphaest** [comment]
Restarting the client works.

**Comment by KaneHart** [comment]
Ninja should be removed or if possible fixed. Them blinking into the terrain during a fight is very annoying. Just a suggestion if someone tending to look at the source or maybe just disable via the config.

**Comment by WarlordWossman** [comment]
Yeah I think the gimmicky ones that don't work well anyways could just be disabled in the config tbh.

**Comment by richardhendricks** [comment]
The source for Infernal Mobs is at https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/tree/1.7.10
It looks like the original author put all his mods into one repo. :-1:

**Comment by damug** [comment]
Moronwmachinegun tells me that it may also be possible to force spawn a mob with choking with the command below rather than pitching spawn eggs and hoping you get lucky.

- /spawninfernal x y z ENTCLASS X spawns an Infernal Mob of class ENTCLASS at x,y,z with Modifiers X
- example /spawninfernal -112 65 234 Zombie Bulwark Fiery Vengeance Choke Regen 1UP Sticky Rust Wither

**Comment by Dream-Master** [comment]
Yes thus guy is crazy. I will try to fork only infernal mobs to GTNH.

**Comment by Dream-Master** [comment]
repo is here i need to remove all other mods
https://github.com/GTNewHorizons/atomicstrykers-minecraft-mods/tree/1.7.10

**Comment by Dream-Master** [comment]
Ok now i remove all folder except Infernal Mobs.
Need help now with code fixes.

**Comment by shawnbyday** [comment]
What is the name of the reflect modifier in the config? It's not "reflect" hence the question.

**Comment by repo-alt** [comment]
Vengeance

**Comment by richardhendricks** [comment]
Ninja
- [ ] Ninjas teleporting inside walls and making hurt sounds there, possibly forever if coupled with regen is surely a strange aesthetic, but perhaps it better be fixed.
https://github.com/GTNewHorizons/atomicstrykers-minecraft-mods/blob/1.7.10/InfernalMobs/src/main/java/atomicstryker/infernalmobs/common/mods/MM_Ninja.java#L70 found the code in question that needs to be fixed.
GitHub
GTNewHorizons/atomicstrykers-minecraft-mods
atomicstrykers-minecraft-mods - Repository for my open source Minecraft Mods

It finds the block to stand on, but doesn't check it also has space above it.


Choking - Choking indicator doesn't always go away when mob is killed.


Vengeance - Damage needs better scaling

**Comment by Dream-Master** [comment]
@richardhendricks Did you need the repo in GTNH? I can fork it

**Comment by Dream-Master** [comment]
@richardhendricks hope we get ever a fix

**Comment by wlhlm** [comment]
I've fixed some problems with Infernal Mobs. Have a look/test it out: https://github.com/GTNewHorizons/atomicstrykers-minecraft-mods/pull/1
