### ISSUE TITLE
[Galacticraft] Unable to retrieve rocket from landing module

### ISSUE THREAD

**Issue by finkledoodle** [GTNewHorizons/GT-New-Horizons-Modpack#2192]
#### Which modpack version are you using?

2.0.1.3

#### If in multiplayer; On which server does this happen? 

Prospercraft.com

#### What did you try to do, and what did you expect to happen?

I attempted to retrieve my Galacticraft rocket from the lander after landing on a planet

#### What happend instead? (Attach screenshots if needed)

I was unable to open the GUI and claim my rocket & fuel

#### What do you suggest instead/what changes do you propose?

I'm not sure what causes this exact issue, I don't recall ever seeing it in previous versions of the modpack, however now I am seeing it somewhat frequently, with players either having to recraft rockets from scratch, or request assistance from admins to reclaim their rockets.

**Comment by alphaest** [comment]
This is caused by when you leave the landing module before it rests in its final location - most common to click shift on the bouncing ball. You can retrieve your rocket by placing a hopper under it. Can't do anything about the fuel tho.

**Comment by Dream-Master** [comment]
So can this be closed because i think this isnt a real bug?
@finkledoodle 
@alphaest

**Comment by alphaest** [comment]
It is definitely a bug. And the thing i wrote is just a way to get around the bug.

**Comment by Dream-Master** [comment]
Any suggestion how it can be fixed? @alphaest

**Comment by alphaest** [comment]
There's nothing we can do. It's a galacticraft problem.

**Comment by Prometheus0000** [comment]
We should be able to fix this ourselves now.

**Comment by glowredman** [comment]
Duplicate of #1967
