### ISSUE TITLE
Pump delets Biomes O' Plenty Honey

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#2246]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to pump the Honey from a WhispHive in the Nether to a drum.
#
#### What happend instead? (Attach screenshots if needed)
The honey was deleted.
#
#### What do you suggest instead/what changes do you propose?
Fix the pump to not delete it, please :)

**Comment by Dream-Master** [comment]
Maybe the honey are not proper registered as fluid.

**Comment by Dream-Master** [comment]
You mean BoP Honey ?

**Comment by Dream-Master** [comment]
I need a few pics from your setup too.

**Comment by LOKKO12** [comment]
Yes its BoP Honey, ill make some pictures ASAP

**Comment by LOKKO12** [comment]
Made it like this (with 16A BatBuffer instead of creative one):
![2017-12-09_21 01 38](https://user-images.githubusercontent.com/33183715/33799047-4fb3aea4-dd24-11e7-905f-711d1db3c724.png)
In one of these:
![2017-12-09_21 03 36](https://user-images.githubusercontent.com/33183715/33799056-70e27be6-dd24-11e7-8227-5a4eae345be9.png)

**Comment by Dream-Master** [comment]
Can you test it with blood. If this not work too i guess biome o plenty fluids not work at all.

**Comment by LOKKO12** [comment]
Blood is working. Same setup.
![2017-12-09_21 13 02](https://user-images.githubusercontent.com/33183715/33799140-c3614fea-dd25-11e7-93ca-bd2ac25aeb38.png)

**Comment by Dream-Master** [comment]
Mh
@Technus any idea if Honey have a different behavior and not standart registered as fluid in Forge?

**Comment by trollolal** [comment]
![image](https://user-images.githubusercontent.com/105285781/180259338-36f244c4-3dde-4524-8994-5b8a1c8617fd.png)
In 2.1.2.4-18-pre version, it still have this issue and the pump get a split second of honey in hologlass and then disappeared
