### ISSUE TITLE
Infernal Mobs drowning ability

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/GT-New-Horizons-Modpack#2324]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
Apart from unpleasant death above void, I got drowned by Infernal with NO BUBBLES showing above my bar, meaning I had no idea I'm running out of breath.
Also had Quantum Suite on which normally replenishes air bubbles.

Yes I'm raging right now but with no visible bubbles that really seems like a bug that should be fixed/disabled.

**Comment by Dream-Master** [comment]
Yes hope we get a fis soon when @richardhendricks is back.

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2176
