### ISSUE TITLE
Bug with enhanced build guide from OpenBlocks

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/GT-New-Horizons-Modpack#2398]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Right clicking block on the enhanced build guide should place the block according to the shape I've set but it's not working.
#
#### What happend instead? (Attach screenshots if needed)
#https://github.com/OpenMods/OpenBlocks/issues/755
#
#### What do you suggest instead/what changes do you propose?
Potentially fix it? As according to the issue i referenced, it seems to be some issue for non-forge server.

**Comment by Ugachaga** [comment]
There is untested PR fixing it: https://github.com/OpenMods/OpenBlocks/pull/826.

**Comment by Dream-Master** [comment]
Ok another mod we take over :)

**Comment by Ghengis88** [comment]
any progress in this ?

**Comment by Dream-Master** [comment]
not realy

**Comment by Ghengis88** [comment]
do the modpack have any other item that can do somewhat the same thing?

**Comment by Dream-Master** [comment]
i guess no. @bartimaeusnek  @richardhendricks @mitchej123 @draknyte1 @Technus should the code ugachaga links maybe work if we pullopen blocks over and make a custom build ?

**Comment by richardhendricks** [comment]
No guarantees, but I will try to look at it.

**Comment by boubou19** [comment]
still not working in 2.1.0.0

**Comment by boubou19** [comment]
ok so i did put https://github.com/OpenMods/OpenBlocks/pull/826 in code with https://github.com/GTNewHorizons/OpenBlocks/commit/845238aaa066baf6c65097fef206b1beade31a17, and tested with local thermos server, and it worked.
