### ISSUE TITLE
Universal Fluid Cell broken - Problem with input/output from GT Pipes and Tanks

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#2404]
#### Which modpack version are you using?
2.0.2.6
#

#### If in multiplayer; On which server does this happen? 
Dirthuts
#

#### What did you try to do, and what did you expect to happen?
**Issue:  Universal Fluid Cells**
**Prior to 2.0.2.6; the functionality below was possible:**
GT Pipes
 Insert 1000mb
 Extract 1000mb
 Insert <1000mb (excess appears as new cell in inventory)
 Extract <1000mb (exact amount available in pipe is extracted if less than 1000mb)

Tank (Iron Tank Mod)
 Insert 1000mb
 Extract 1000mb
 Insert <1000mb
 Extract <1000mb

GT Machines/Tanks/RC Tanks appear to be unaffected

**After patch 2.0.2.6:**
X indicates broken functionality:

GT Pipes
X  Insert 1000mb
X  Extract 1000mb
X  Insert <1000mb (excess appears in new cell in inventory)
X  Extract <1000mb (exact amount available in pipe is extracted if less than 1000mb)

Tank (Iron Tank Mod)
 Insert 1000mb  (still working)
 Extract 1000mb  (still working)
X  Insert <1000mb
X  Extract <1000mb

#
#### What happend instead? (Attach screenshots if needed)
I use universal fluid cells a lot for specific crafting that requires an exact amount of fluid (assembler recipes etc).  I've been using this technique for a long time now and suddenly its broken, a lot of my setup needs to be changed.

#
#### What do you suggest instead/what changes do you propose?
fix

**Comment by Dream-Master** [comment]
@mitchej123 any idea ?

**Comment by Dream-Master** [comment]
@tranceplanet test it with 2.0.2.7 if available

**Comment by mitchej123** [comment]
Can you include a screenshot/short clip of a previously working setup?  Did the pipe require any sort of cover on it?  Or just directly clicking on the pipe work?
