### ISSUE TITLE
Warded glass placed with better builder wand doesnt allow  to remove glass later

### ISSUE THREAD

**Issue by ForTheHorde01** [GTNewHorizons/GT-New-Horizons-Modpack#2416]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Multiplayer EU delta server
#
#### What did you try to do, and what did you expect to happen?
I was  trying to place warded glass with better builder wand, i thought i will be able to remove the glass later like it was placed without wand
#
#### What happend instead? (Attach screenshots if needed)
Warded glass reacts like it wasnt placed by me  when im trying to remove it with Thaumcraft wand
#
#### What do you suggest instead/what changes do you propose?
Dunno, disable placing warded glass with better builders wand or fix?

**Comment by tranceplanet** [comment]
The better builders wand seems to have bugs with a few things.  I tried to place Fir Drawers with it and the new drawers were invisible although they were there (even after restart).  I've personally avoided using better builders wand for anything except basic blocks

**Comment by Dream-Master** [comment]
The mod itself we cant fix and how i can disable placing a specific block? is there a config for it?

**Comment by richardhendricks** [comment]
BBW has a blacklist option in the config file.  Need to update with warded glass, and maybe drawers?

https://github.com/GTNewHorizons/NewHorizons/blob/master/config/betterbuilderswands.cfg

**Comment by Prometheus0000** [comment]
Blacklist didn't work when I tried it. :(
