### ISSUE TITLE
Brown smart cables missing recipe

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/GT-New-Horizons-Modpack#2439]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Missing recipe for smart cable (Brown)
#
#### What happend instead? (Attach screenshots if needed)
![2018-01-15_21 57 10](https://user-images.githubusercontent.com/13598309/34982223-cdd1a02e-fae4-11e7-957c-11e51c89c9d9.png)

#
#### What do you suggest instead/what changes do you propose?
Add the recipe. Just 8 smart cable of any type surrounding a brown dye of some sort.

**Comment by Dream-Master** [comment]
will check

**Comment by Ghengis88** [comment]
Still not working in 2.0.5.1

**Comment by Dream-Master** [comment]
maybe. Look at the number of issues I have to work on. There is no priority list and btw it's very simple so if you do a pull request it will be done sure. @Ghengis88

**Comment by GTNH-Afx237v7** [comment]
fixed with https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7953
