### ISSUE TITLE
CESU not craftable in AE

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#2441]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Encode CESU recipe in AE (used in OC power distributor)
#
#### What happend instead? (Attach screenshots if needed)
Recipe requires discharged battery (damage value 26),
but crafting returns the battery w/o damage value
#
#### What do you suggest instead/what changes do you propose?
Fix the recipe, or add an alternative.

**Comment by Dream-Master** [comment]
If i use meta id 27 people complain if i use 26 also and if i not use any meta id people complain too. So what i need to change. I cant give them a wildcrad value in my script. If i use * we get other errors and i cant put all recipes into code.

**Comment by repo-alt** [comment]
Add a shapeless recipe to convert discharged battery to a battery w/o damage value? 
Because looks like original IC2 recipe uses the version w/o damage value, like in "Advanced Charging Battery"
In rev. 544afd8 you changed the battery recipe to return the version w/o damage value (which is ok), and at the same revision, changed CESU recipe to accept batteries with damage value 26, which is inconsistent.
As for the wildcard - you cannot use it in return values, but not in parameters, so if you change CESU (IC2:blockElectric:7) recipe to use <IC2:itemAdvBat:*> it would probably also work
Advanced Batpack (IC2:itemArmorAdvBatpack) is also affected

**Comment by Dream-Master** [comment]
damage value one is stupid. * give many errors. So i have the choiche between 26 or nothing. Add for all recipes a converter recipes take long time to add.

**Comment by repo-alt** [comment]
What exactly errors did you get by wildcard usage? I assumed it is a general rule to use wildcard whenever chargeable item is used in the recipe.

**Comment by repo-alt** [comment]
I may test in SSP if the wildcard version actually accepts both variants of the battery.

**Comment by Ugachaga** [comment]
IIRC, only wildcards in IC2:itemArmor* cause problems. 
https://github.com/GTNewHorizons/NewHorizons/issues/1084, https://github.com/GTNewHorizons/NewHorizons/pull/1088

**Comment by Dream-Master** [comment]
maybe I have to put all ic2 recipes some day to gt code

**Comment by repo-alt** [comment]
btw, I verified that the recipe 

```
// --- CESU
recipes.addShaped(<IC2:blockElectric:7>, [
[<ore:cableGt01AnyCopper>, <ore:plateBronze>, <ore:cableGt01AnyCopper>],
[<IC2:itemAdvBat:*>, <gregtech:gt.blockmachines:12>, <IC2:itemAdvBat:*>],
[<ore:plateBronze>, <IC2:itemAdvBat:*>, <ore:plateBronze>]]);

```
works both with freshly crafted and with discharged batteries. Also there are no errors in the logs.

**Comment by Prometheus0000** [comment]
This is already in.
