### ISSUE TITLE
Biomass quests shouldn't require machines in the quest

### ISSUE THREAD

**Issue by Bluebine** [GTNewHorizons/GT-New-Horizons-Modpack#2445]
#### Which modpack version are you using?
2.0.2.7
#### What do you suggest instead/what changes do you propose?
In the MV tier, there's several quests that detail the biomass creation process. These quests each request an MV machine for each function. But this isn't actually necessary- these quests don't NEED an MV machine, and are more efficient with an LV one. I'd suggest just making these quests only need the product, and not request a machine at all.
The quests that need changed-
Plant balls
Plant mass
Bio chaff
Way two: Brewery
Fermented biomass
Seed oil

**Comment by Dream-Master** [comment]
I will do machine optional in a seperate quest.

**Comment by McFrugal** [comment]
The Fermented Biomass quest still requires an MV Fermenter.
