### ISSUE TITLE
Add Schematica as an optional mod

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/GT-New-Horizons-Modpack#245]
We already have LunatriusCore from InGame Info XML
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1285818-schematica

**Comment by Namikon** [comment]
Well.. isn't that a clientside mod? You can just add it then. Sadly, solder doesn't allow "optional" mods as ATlauncher does. So either it's part of the pack, or it is not

**Comment by Dream-Master** [comment]
Can add it as optinal mod and include it (xxxx.optinal)

**Comment by Namikon** [comment]
The Mod would be disabled with every update, but yes that could work

**Comment by Dream-Master** [comment]
Added to the Testpack

**Comment by Dream-Master** [comment]
Added via Testpack.
