### ISSUE TITLE
Openblocks Graves items get lost

### ISSUE THREAD

**Issue by Ranzbold** [GTNewHorizons/GT-New-Horizons-Modpack#2450]
#### Which modpack version are you using?
2.0.2.6
#
#### If in multiplayer; On which server does this happen? 
on my local server playing with a friend
#
#### What did you try to do, and what did you expect to happen?
i died to an overpowered mob and reclaimed my stuff by destroying the grave. expected to get all my items back
#
#### What happend instead? (Attach screenshots if needed)
Lost a few items (Almost half of it) This bug occured 2 times. Lost my tinker tools 2 times now
#

**Comment by richardhendricks** [comment]
Did you have any Forestry backpacks?  I know the miner's pack tends to gobble up weird stuff.

**Comment by Dream-Master** [comment]
just restore the grave /ob_inventory restore Your-username file.dat

**Comment by magicced01** [comment]
I did not have any bagpack or any form of extended inventory

**Comment by Dream-Master** [comment]
did you restore you grave with the command @magicced01 ?

**Comment by magicced01** [comment]
No i didnt. read that too late. Just cheated my items back in. I will try it next time if the error occurs again

**Comment by Zudwa69** [comment]
Bad english, sorry. Same story. Black textured blaze, do not remember wich kind of. Twise. Without Forestry backpacks, neither now, neither first time. @Backpack in use. As i remember, in inventory all items was not renamed. Command does`t help: https://nyazo.jp/ISWb36b.jpg

**Comment by richardhendricks** [comment]
Please verify that you are using unhacked version of Minecraft and are on-line with Mojang authentication servers.

**Comment by magicced01** [comment]
I was playing online and unhacked. 100%

**Comment by richardhendricks** [comment]
Probably related to Ember special mob blazes using setHealth.  Need to retest after Alk's fix.

**Comment by Prometheus0000** [comment]
A grave was produced when I was killed by one, so I guess it's fixed? Unless someone says otherwise.

**Comment by d1n0z** [comment]
.minecraft\logs\latest.log OR .minecraft\logs\year-month-day-somenumber.log.gz<-inside you will find anything.log
find 

> openblocks.common.PlayerDeathHandler$GraveCallable.tryPlaceGrave(PlayerDeathHandler.java:217):` Grave for ...

at the end you will find coords of your death, something like (-256,77,-13)
