### ISSUE TITLE
Powering turrets with GT power doesn't work

### ISSUE THREAD

**Issue by j2ghz** [GTNewHorizons/GT-New-Horizons-Modpack#2465]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
My private server
#
#### What did you try to do, and what did you expect to happen?
Connect like this: ![](https://i.imgur.com/r1oSCHI.png)
#
#### What happend instead? (Attach screenshots if needed)
The turret didn't receive any power. After putting an EnderIO conduit inbetween, it worked.
![](https://cdn.discordapp.com/attachments/234936569360809996/404004718021705738/unknown.png)

**Comment by Dream-Master** [comment]
@mitchej123 any idea if you can ad gt pipe support here too ?

**Comment by Dream-Master** [comment]
https://github.com/OpenModularTurretsTeam/OpenModularTurrets/tree/master
here the source

**Comment by Technus** [comment]
Gt wires are not supposed to convert. 
Here looks like the cobduit converts. Use a gt transformer if u want a full gt setup.

**Comment by mitchej123** [comment]
I thought GT wires were supposed to convert from GT EU to RF? (but not RF to EU)

**Comment by Dream-Master** [comment]
So close the issue or make it gt wire compatible @mitchej123 @j2ghz ?

**Comment by mitchej123** [comment]
I'm fine making it compatible as long as there's no arguments against it -- other RF things can be powered w/ GT cables.

Will look into it when I'm back from vacation.

**Comment by nikitinalexx** [comment]
Could we look into this issue? How can we solve this problem right now? Use a transformer? Which kind?

**Comment by Dream-Master** [comment]
is the turret mod open source?

**Comment by Dream-Master** [comment]
@mitchej123 I guess you back from vocation 😅

**Comment by mitchej123** [comment]
Is this still an issue?

**Comment by Prometheus0000** [comment]
This does not work. Why it won't convert to RF in this one case I have no idea. As soon as I added a capacitor it got power from that instead.

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/155889183-8f491624-564c-4b58-ac8c-baa5138ded48.png)
works just fine
