### ISSUE TITLE
Fluids in/out Cells from Hatch, Diesel Engine

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#2482]
Normaly i can take fluids in and out via cells into the Fluid hatch from EBF or the Diesel Engines. Now only fluid input via cells work but no otput in cells.

**Comment by Dream-Master** [comment]
@richardhendricks thanks for looking into it.

**Comment by richardhendricks** [comment]
Maybe upstream can add a screwdriver/crowbar/soldering iron option to pumps for that. But for single blocks that have only a single tank like assemblers, autoclaves, and diesel generators, really should allow extracting from the tanks.

**Comment by richardhendricks** [comment]
@Technus commit https://github.com/GTNewHorizons/GT5-Unofficial/commit/eadaa798805a18a6d9fbaf5c55ea2a01aeacdb10
removed generator ability to load containers or be pumped out.

Tec, you recall why?

**Comment by richardhendricks** [comment]
I would also like to increase the tank size from 16000 to scaled size based on tier.  MV generator should be able to accept large aluminium fluid cells!

**Comment by richardhendricks** [comment]
Bluebine suggested 4B for LV, 16B for MV, 64B for HV.

**Comment by richardhendricks** [comment]
For generators, allow pumping only from the bottom (no cells)?

**Comment by richardhendricks** [comment]
Looks like the fix is related to this

https://github.com/GTNewHorizons/NewHorizons/issues/759

**Comment by richardhendricks** [comment]
Also, this commit disables emptying input hatches

https://github.com/GTNewHorizons/GT5-Unofficial/commit/eadaa798805a18a6d9fbaf5c55ea2a01aeacdb10

**Comment by richardhendricks** [comment]
re-enabled draining generator tanks with fluid cells, will need to keep eye on any cell dupe/destroying issues, but it looked like it worked fine to me. 

Waiting for feedback on changing the sizes of the generator tanks.

**Comment by richardhendricks** [comment]
Hatches currently unchanged, need to verify they can be drained via pumps.
