### ISSUE TITLE
Applied Energistics - Can't craft automatically, terminal window closes

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#2483]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Dirt Huts
#
#### What did you try to do, and what did you expect to happen?
Using AE. I have created a pattern and put it in an interface -> Molecular Assembler.

However, in ME Crafting Terminal - the recipe comes with an option to craft.  When I press the recipe, the window closes and I am unable to complete the craft.

I have checked my network and successfully crafted this using Export Bus -> Crafting Card -> Chest combination. 

The next screen asking for the number of items to craft should come up, followed by CPU selection... but they don't.

#
#### What happend instead? (Attach screenshots if needed)
Nothing happens, the ME Crafting Terminal closes.

#
#### What do you suggest instead/what changes do you propose?
AE Fixes.  It looks like a few things aren't working right since 2.0.2.7.

**Comment by tranceplanet** [comment]
Could be related to #2435

**Comment by bartimaeusnek** [comment]
is not related to #2435, but is the fix for #2432. what help here is: A) to move the AE outside of a custom dim, B) die in that dim, DO NOT MINE ANYTHING and use ur AE, C) clear your hotbar and use your AE.

**Comment by Dream-Master** [comment]
@bartimaeusnek what i can do here

**Comment by tranceplanet** [comment]
A) My AE is in the Overworld.
B) Above
C) Cleared my hotbar and still the same result.

There are no P2P junctions involved in this setup for info.

**Comment by tranceplanet** [comment]
Correction

I reviewed B again.  I died in the overworld, didn't mine and then interacted with AE and it's working again now.

**Comment by tranceplanet** [comment]
do I need to do that everytime or does it fix it temporarily going forward?

**Comment by Dream-Master** [comment]
@richardhendricks @technus

**Comment by Dream-Master** [comment]
Need help here

**Comment by bartimaeusnek** [comment]
@tranceplanet i realy cant say that, for me this only happened in a void dim.

**Comment by repo-alt** [comment]
No sense to keep it open, since it cannot be reproduced.
