### ISSUE TITLE
thaumcraft broken recipes

### ISSUE THREAD

**Issue by dahgul333** [GTNewHorizons/GT-New-Horizons-Modpack#2506]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
offical gtnh server 2 EU (epsilon)
#
problems with such recipes:
Ore Destruction ; Salis mundus duplication at thaumic Bases
Emerald transmutation at Apocryha
From what I found at the moment

**Comment by Dream-Master** [comment]
Thaumic base recipe get a rework soon. The others I will check.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35435311-8317945a-028a-11e8-8d25-103b08e4be20.png)

**Comment by Dream-Master** [comment]
Thaumic base get nerfed at a later point.

**Comment by monroth** [comment]
another thaumic base recepies that don't work - amber from spruce and quicksilver from silverwood log

**Comment by Dream-Master** [comment]
@monroth will check

**Comment by monroth** [comment]
found another one 
Thaumium ingon -> 8 thaumnite nuggets

**Comment by Dream-Master** [comment]
need to check this too.
