### ISSUE TITLE
foul fume recipe broken

### ISSUE THREAD

**Issue by MakinToge** [GTNewHorizons/GT-New-Horizons-Modpack#2518]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
epsilon
#
#### What did you try to do, and what did you expect to happen?
try to make foul fume in a witchery oven.
#
#### What happend instead? (Attach screenshots if needed)
oak wood won't burn
![2018-01-25_20 12 49](https://user-images.githubusercontent.com/12732004/35407530-8db1cf76-020c-11e8-90d0-0441425d8cf1.png)
![2018-01-25_20 12 59](https://user-images.githubusercontent.com/12732004/35407532-9053719e-020c-11e8-840b-829f9e03a4a1.png)

#
#### What do you suggest instead/what changes do you propose?
fix ? only keep the distillation recipe of the foul fume ?

**Comment by Dream-Master** [comment]
guess it not work because i remove  logs to coal. Use the distillery.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/35409252-ef9919d8-0211-11e8-9431-205a098b26d3.png)

**Comment by heatskr** [comment]
@MakinToge you can use alder and other saplings.
![fume](https://user-images.githubusercontent.com/348713/35439392-55cb2496-0279-11e8-95ba-151772ad782a.png)

**Comment by Dream-Master** [comment]
Ah yes this works too ofc

**Comment by MakinToge** [comment]
@heatskr Nope, those recipes are not in the pack. They don't appear in NEI and don't work (tried just nowwith 16 acacia,did not get a single fume even with fume funnel on both side )

**Comment by Dream-Master** [comment]
I can add it.
