### ISSUE TITLE
IC2 cells bugs

### ISSUE THREAD

**Issue by Proha5** [GTNewHorizons/GT-New-Horizons-Modpack#2523]
2.0.2.7

1. Sometime AE2(extracell) can't fill IC2 cells (ANY fluids), except "molten redstone" and "molten epoxid"- its works fine.
I should restart the client.
![image](https://user-images.githubusercontent.com/29812448/35435999-805f7f7c-02d8-11e8-86b2-0d9c4090aa84.png)

2. Highlighten IC2 cells (molten redstone, molten epoxid) - contain 144L. instead 1000L.
![image](https://user-images.githubusercontent.com/29812448/35436244-67b0188c-02d9-11e8-9b13-e67e08bd17b6.png)

Both bugs only with IC2 cells. GT cells - ok. But recipes requere IC2 cells.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2482

**Comment by Proha5** [comment]
"Reload game" not fix bug N1 anymore.
I reloaded 3 times. How manualy fix? i can't continue play, because need craft recipes with IC2 cells.
