### ISSUE TITLE
AE and void world shenanigans

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/GT-New-Horizons-Modpack#2529]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
All my farming station is shut off after i logged out althought the chunk is loaded with a world anchor. Which is shown in the below picture.
![2018-01-27_16 38 35](https://user-images.githubusercontent.com/13598309/35470365-4d14612c-0383-11e8-91d5-74e2f4f42f92.png)

![2018-01-27_16 38 44](https://user-images.githubusercontent.com/13598309/35470291-b809b970-0381-11e8-882f-08aa23d27be5.png)

This is how i connect my power to the farming station. Using RF p2p.
![2018-01-27_16 43 28](https://user-images.githubusercontent.com/13598309/35470292-b83d91dc-0381-11e8-8b76-be69fe94b13a.png)
![2018-01-27_16 44 03](https://user-images.githubusercontent.com/13598309/35470294-b86f3de0-0381-11e8-925f-4869b46a1e9f.png)

#
#### What happend instead? (Attach screenshots if needed)
It happens only when im not online. (Yes, the chunk is absolutely loaded which u can see from the 1st picture where all the crops is grown fully.) What i suspect was the quantum link unlinked when im not online which causes all my farming station to power off. I'm also supplying power to the quantum ring as shown in below through a energy acceptor and a naquadah reactor.
![2018-01-27_16 52 05](https://user-images.githubusercontent.com/13598309/35470338-80d40284-0382-11e8-8cb2-fb77a8e1bd58.png)

The quantum ring should reconnect itself when it disconnect after awhile (Thats how AE quantum ring works and it shouldn't disconnect once they are connected, it only happens in this pack. I've reported this long time ago but no fixed. *oh well, nvm*) but it isn't doing that.
Once I logged in, the quantum ring reconnects and all the farming station is now getting power thus harvesting everything. Possibly related to all the void world and AE interaction issue that is been going around for some time after the void world fix. (Not sure if this also happens in old void world but it seems that old void world AE system don't have much issue.)
#

**Comment by noobyaran9** [comment]
Just checked, it seems like rf p2p is voiding all my power

**Comment by bartimaeusnek** [comment]
@noobyaran9 please contact me in discord.

**Comment by Dream-Master** [comment]
@bartimaeusnek can we close this?
