### ISSUE TITLE
Huge plasma turbines

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/GT-New-Horizons-Modpack#2557]
#### Which modpack version are you using?
Delta one
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I'm testing different awakened draconium turbine rotors in large plasma generators. Here is the results:
Nitrogen plasma awa drace turbine testing sheet:
Small Turbine:
   Overflow: 103218
   Optiflow: 109204
   Need 13\sec
Normal turbine:
   Overflow: 235584
   Optiflow: 249984
   Need 25\sec
Large turbine:
   Overflow: 416509
   Optiflow: 441261
   Need 38\s
Huge turbine:
   Overflow:  486368
   Normalflow: 516096
   Need 50\s

As u see, Huge turbines completly useless, they give almost none energy boost, but need way more material and americium.

Need to be reworked i think...
... or i do something wrong?

**Comment by repo-alt** [comment]
It was always so in vanilla GT5, I think from the beginning of the large turbines, but it does indeed look strange. That is - I never bothered to craft a large turbine, because they are useless, but also never thought to ask Bloody wtf he was thinking when adding them...

**Comment by CalterOK** [comment]
in the work of plasma turbines there definitely is an error. For the rotors indicated by you, the plasma consumption and the energy produced should be such (based on calculations from the wiki formulas). also noticed that in addition to the wrong output of energy, there is an erroneous consumption of plasma. When the regulator is tuned to the optimum flow, the plasma accumulates
![image](https://user-images.githubusercontent.com/35035276/35773690-363cd122-096a-11e8-8e45-41b9141c7840.png)

**Comment by CalterOK** [comment]
I compared the work of turbines with vanilla greek and horizon. As a result, poor performance of turbines is the only problem of this assembly. in the original they have not lost their relevance. The energy density of the plasma is also greatly increased, and I suspect that the turbine calculation formulas have been changed. For clarity, comparison of small cobalt rotors working on nitrogen plasma.
GTNH
![2018-02-04_07 00 11](https://user-images.githubusercontent.com/35035276/35774254-7967c370-097a-11e8-8b57-bcc483989b90.png)
GT
![2018-02-04_07 06 12](https://user-images.githubusercontent.com/35035276/35774260-909ddd2c-097a-11e8-8d39-3b61be159a78.png)
At the same time I want to note that the energy density of the azat plasma is very different.
GTNH =129 024 Eu/L
GT = 14336 Eu/L

**Comment by CalterOK** [comment]
the difference between Lv and TV 2: 1. but for turbines this is unacceptable since they are much more complex than single-block variants. and if their effectiveness is worse then their use will be a big question.

**Comment by richardhendricks** [comment]
I think it is OK to have lower efficiency, but the flow rate needs to be more than just +20%.  Maybe more like 60-80%?  So from 5 to 8 or 9?  That would reduce the # of turbines needed a decent amount.

**Comment by bartimaeusnek** [comment]
i think alk also did this... not quite sure @draknyte1

**Comment by draknyte1** [comment]
Didn't do larger plasma.
