### ISSUE TITLE
Galacticraft canisters not being consumed by Tier 1 Rocket Engine recipe or Small Fuel Canister Recipe

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#2558]
#### Which modpack version are you using?
2.0.2.7
#
#### What did you try to do, and what did you expect to happen?
Crafting tier 1 rocket engines and small fuel canisters
#
#### What happend instead? (Attach screenshots if needed)
Crafting successful, but did not consume canisters - they were returned to me for both recipes.

**Comment by richardhendricks** [comment]
Pic showing rocket engines and returned canisters

![2018-02-04_12 30 26](https://user-images.githubusercontent.com/1214811/35780823-385cf814-09a7-11e8-8c7c-d15e65b029c2.png)

**Comment by Dream-Master** [comment]
Empty or full canister?

**Comment by richardhendricks** [comment]
Empty canisters

**Comment by Dream-Master** [comment]
Ok so not a bug.

**Comment by richardhendricks** [comment]
So it is supposed to return the canisters when making rocket engines and the fuel tanks?

**Comment by repo-alt** [comment]
There is some inconsistency with that recipe. When crafting engines/boosters manually, empty canister is returned, but when autocrafted by AE, canister is consumed. Not that it is a big deal, but still.

**Comment by Dream-Master** [comment]
Nothing I can do. We need to do a code change and pull it to gc side

**Comment by Prometheus0000** [comment]
We've brought GC over, cracked it open, and changed other stuff, so this should be fixable now, right? BTW it should be any recipe that uses the canisters that isn't filling it with fluid.

Though the Empty Fuel Tank is GS, so we probably can't fix that one. And it's the primary use unfortunately. ASM?

**Comment by Prometheus0000** [comment]
So we have GS forked now too, so maybe we can finally fix it?

**Comment by Dream-Master** [comment]
@glowredman

**Comment by glowredman** [comment]
Is on my list, should be very easy
