### ISSUE TITLE
issue with farming stations

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#2582]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
On Delta
#
#### What did you try to do, and what did you expect to happen?
I wanted to plant cherry hill sapplings and apple oak sapplings with a farming station
#
#### What happend instead? (Attach screenshots if needed)
It appears that forestry sapplings can't be placed in the farming station. It forces the player to use forestry's farms that's not fair IMO.
#
#### What do you suggest instead/what changes do you propose?
I suggest to add a compatibility for forestry sapplings in the farming station in order to provide the same choice of farms as vanilla sapplings

**Comment by Dream-Master** [comment]
We fork Ender io but i cant add it myself.

**Comment by mtesseracttech** [comment]
Ender IO addons may have a solution. Not sure though.
