### ISSUE TITLE
Rework of EMT Machinery

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#2590]
#### What do you suggest instead/what changes do you propose?
- [x] Right now, only Ordo Compressed Solar panels are really usefull (the others produce less and need special requirements), i would suggest to rework all of them. Maybe even add Quadruple, Quintuple, etc. Compressed Solars

- [x] Same for Essentia Generators, they are only usefull in MV/HV. Maybe we could add higher tiered Versions, and other Essentia Versions of them.

- [ ] The Ethereal Macerator is kind of useless aswell, we could redo it as an update for GT Pulverizers.

- [ ] Finially we could add a "Wand Buffer" which is basically two Industrial Wand Rechargers combined with a Battery Buffer (IV+) what uses Wands as Batteries.

**Comment by benstuwie** [comment]
The problem with more solars is that they are all on ic2 power not GT, and seem to need an ic2 buffer instead of the GT transformer method. The highest I've found is the 8192eu/t afsu, so i don't know how they could pass that and still be useful.

**Comment by bartimaeusnek** [comment]
@benstuwie we could add an internal buffer and a gui for them, or recode them entirely to output GT power 😄

**Comment by benstuwie** [comment]
if you can only pull 8192eu/t and internal buffer wouldn't help

**Comment by bartimaeusnek** [comment]
You can pull more, see Kinetic Generators for example, but you need GT transformer behind them...

**Comment by benstuwie** [comment]
yea exactly. If they're gonna do more than 8192 we need gt to be involved

**Comment by bartimaeusnek** [comment]
Essentia Gens GUI + Tooltip finished. One more Type of Essentia Gen added.
