### ISSUE TITLE
Creating a fence with anything other than oak planks makes a wood slab that looks like a fence

### ISSUE THREAD

**Issue by Snaggerr** [GTNewHorizons/GT-New-Horizons-Modpack#2592]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Made a fence manually with Spruce Planks.  I expected to create a fence that could be used in other recipes or in the assembler.
#
#### What happend instead? (Attach screenshots if needed)
A Wood Slab is created instead.  In your inventory it has the appearance of a fence, but has the item description for a Wood Slab.  If placed in the world, it looks and acts like a fence normally would.
#
#### What do you suggest instead/what changes do you propose?
Fix it so I can use my Spruce Wood to create fences that can be used in other recipes.
![2018-02-10_16 00 47](https://user-images.githubusercontent.com/13313518/36067900-068fe050-0e7d-11e8-9a41-3fa90ba25942.png)

**Comment by Dream-Master** [comment]
guess this only a localizer bug (visual)

**Comment by Cinobi** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/2259 old knowing issue :D

**Comment by UpstreamEDA** [comment]
It's not just a visual bug, the Wood Slab/Fence cannot be used in any recipes that require fences.
