### ISSUE TITLE
Heavy fuel not processing steam in bronze large boiler

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#2604]
#### Which modpack version are you using?
Latest version on twitch
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I put heavy fuel in bronze large boiler and it started working. It says its working perfectly but it wasnt produce any steam. 
#
#### What happend instead? (Attach screenshots if needed)
It burned heavy fuel and did nothing. Just wasted fuel. 
#
#### What do you suggest instead/what changes do you propose?
Fix it. If it's a bug.

**Comment by Wolozo7** [comment]
Tested in 2.7, after usual warmup period the boiler started producing steam.

![image](https://user-images.githubusercontent.com/34921674/36212334-f3cd7908-11a3-11e8-9346-93f35e08ab4e.png)

![image](https://user-images.githubusercontent.com/34921674/36212347-fb249baa-11a3-11e8-8901-0df700a0803a.png)

**Comment by Dream-Master** [comment]
So no issue onaymore ? @Impos913

**Comment by Impos913** [comment]
I tryed it again and not produce any steam then I tryed some other fuels it
produced steam.

14 Şub 2018 18:47 tarihinde "Martin Robertz" <notifications@github.com>
yazdı:

**Comment by richardhendricks** [comment]
Which fuel did you use, exactly?  There's a difference between Sulfuric Heavy Fuel and Heavy Fuel.  Sulfuric has much lower EU output and I think that affects warmup speed.

**Comment by Impos913** [comment]
Normal heavy fuel

14 Şub 2018 18:52 tarihinde "Richard Hendricks" <notifications@github.com>
yazdı:

**Comment by richardhendricks** [comment]
I don't see in the code where it even processes the liquid fuels in the boilers.  Is that done in custom code somewhere @Dream-Master @Technus ?

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/boilers/GT_MetaTileEntity_Boiler_Bronze.java#L117

**Comment by Dream-Master** [comment]
Its new for me to so far ik only coal/hard fuels burn in the steam boiler but i not 100% sure.

**Comment by Dream-Master** [comment]
It says Diesel fuels have a 1/4 Efficency
![image](https://user-images.githubusercontent.com/2970688/36216605-8a808e20-11af-11e8-8a51-8f9670f72818.png)

**Comment by Impos913** [comment]
So, do we know why heavy fuel dont produce steam on my large bronze boiler?

**Comment by Dream-Master** [comment]
idk

**Comment by MineAnPlay** [comment]
Liquid fuels in Large Boilers have been there from the start (not from GTNH) but it's not worth using them because of efficiency. Though about it not outputting steam, I'm not to sure and might test it later on but don't really think it's that important (since even a normal combustion generator has a higher efficiency then it ).

**Comment by richardhendricks** [comment]
yeah ignore my comment I was looking at the singleblock boiler, not the multiblock.  The multiblock boiler code is here

https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeBoiler.java#L112

I don't see anything that would prevent liquid fuels from producing steam.  It does look like there could be some weirdness if there are multiple fuel types, like liquid and solid, but if it's burning, it should be producing steam.

The only difference I see is the SuperEfficiency variable, which doesn't make much sense to be honest.

**Comment by Impos913** [comment]
I think the problem is input and output things are LV. It worked in steel
boiler with MV input and output.

20 Şub 2018 10:50 tarihinde "Richard Hendricks" <notifications@github.com>
yazdı:

**Comment by Prometheus0000** [comment]
Did not produce steam, but after first cycle, it exploded instead.

**Comment by Prometheus0000** [comment]
Haha, I forgot to add water before, it totally works now. And probably has for a while.
