### ISSUE TITLE
[RFC] Discussion on Electro Magic Tools: Essentia Generators

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#2611]
Discussion on balancing and use for the EMT essentia generators

Are these intended to be primary power sources?

Should they be automatable?

What kind of tiering structure should they have?

How hard should they be to make?

Should generators be essentia-specific, or setup in some more generic way?

Should there be side effects?

**Comment by richardhendricks** [comment]
My proposal is 3 tiers of generators
Tier 1 - MV-class generator accepts 1 base essentia, puts out 128 eu/t - requires aluminum + a wand(?)

Tier 2 - HV class generator accepts simple compound essentia (2 base essentia), puts out 512 eu/t - requires stainless + everful urn

Tier 3 - EV class generator accepts compound essentia (3+base essentia), puts out 2048 eu/t - require titanium + everburning urn

Equivalent EU for essentia
Single essentia - 200 k EU
2 base compound essentia - 600k EU
3+ base compound essentia - 1800k EU

Would be nice if there was some way to require maintenance and/or potential side-effects or catastrophic incidents.  

IE, require Ordo as well for HV, with Aqua for EV to keep the machines safe or something, and if those happen to run out, flux up the area.

**Comment by bartimaeusnek** [comment]
What are these atm (2.0.2.7):
Generators that take Essentia from Jars within 4x4x4Blocks, and generate IC2EU. They have an insaine internal buffer (1GEU=1.000MEU=1.000.000kEU=1.000.000.000EU) but no fuel buffer. They create between 25-100EU/t depends on the essentia they use (Auram>Potentia>Ignis>Arbor>Aer). There are no Information about this anywhere but in the Sourcecode. They have a very strange way of generating and using fuel. (every 20ticks, they consume 1 essentia and produce energy/30)
What i did (see my Repo):
Added a fuel buffer of 64 Essentia, made them accept Essentia via Pipes, reduced the buffer to 1MEU (changeable in config), rewrote the Generation of Essentia to a more logical way (now they use 1 Essentia per 20ticks and generate energy every tick). Added a Gui and a Tooltip.

**Comment by bartimaeusnek** [comment]
My ideas for Essentia Gens differs from morons one:
1. Single Gen: Like they are now
2. Compressed Gen: Like they are now but takes x9 gens and fuel and produce x10 energy
3. Double Compressed Gen: ^
4. Triple Compressed Gen: ^
5. Infused Gens: 
Ordo Infused: more efficient less energy/t
Perditio Infused: more energy/t less efiicient
Aer Infused: Can take in CV to modify Efficieny and/or EU/t
Fire Infused: Needs Lava to "run hotter", normal efficiency, more energy/t
Terra Infused: ???
Aqua Infused: Needs Water to "run cooler", more efficient than Ordo one, less energy/t
6. Primal Generator: Takes in everything and creates 75% energy out of it.
7. Anti-Generator: Takes in EU and creates Essentia from Energy and UUM.

**Comment by richardhendricks** [comment]
yeah 25-100 EU/t isn't a useful range. Are there cheap/plentiful ways to get Aer?  I don't know if I agree with it being the 'simplest' one

**Comment by bartimaeusnek** [comment]
sugarcanes.

**Comment by richardhendricks** [comment]
How about Terra as the lowest, then aer etc as given above?

**Comment by richardhendricks** [comment]
Since terra is just rocks, sugarcanes actually require a little effort.

**Comment by richardhendricks** [comment]
Compressed gens are 9x, 81x, and 729x.  Can the arcane worktable be automated to make that many gens? How about 3x, 9x, and 27x, or maybe 4x, 16x, 64x.  with recipes in the arcane worktable then they can be gated with recipe requirements.

**Comment by bartimaeusnek** [comment]
yes it can be automated with the thaumcraft AE2 addon.

**Comment by bartimaeusnek** [comment]
"Aer Output"=15000
"Aqua Output"=5000
"Ignis Output"=20000
"Ordo Output"=16000
"Perditio Output"=10000
"Terra Output"=2000

these are the outputs as they are now.
Compunt aspects are calculated by them.

**Comment by bartimaeusnek** [comment]
@Dream-Master can we nerf the acutal Potentia Gen Recipe a bit, so it will be aviable at MV? (by replacing the energy-crystals with a CESU)

**Comment by richardhendricks** [comment]
Will check them out this weekend

**Comment by richardhendricks** [comment]
OK, crazy idea.  How about having them double output when in a MAGICAL tagged biome?  We can tune the outputs so that they're viable options against cetane/large block boilers.  Maybe have them emit a little flux now and then since they wouldn't be generating GT pollution.

This way a player can choose to go down a magical powergen path once they have started thaumcraft.  I'd like to see a better way to discriminate between basic/low/middle/high tiers though than "just add compression".  

Possible idea, along the line of kinetic generators.  Instead of essentia-specific generators, each tier can burn any essentia (with configurable EU/essentia).

Basic essentia gen - Same as current ones, no chance of flux, low MV tier. Max around 120 EU/t. (double in biome with MAGICAL oredict tag).  
Low essentia gen - Requires 4 basic essentia gens crafted in arcane worktable, has a tiny chance of emitting flux gas. Max around 480 EU/t
Mid essentia gen - low gen + stuff in an infusion, requires machine, electrum, motus essentia at least. Mid chance of emitting flux gas + tiny chance of liquid flux? Max around 1920 EU/t
High essentia gen - High instability, high tier items - include radioactive essentia? Lots of flux gas and decent amount of liquid flux - basically needs a flux scrubber setup to keep clear or else ground will become tainted. Make sure the amount of flux generated does not allow the flux scrubber to make more EU than used.

Higher tier generators might need a bonus on essentia burn time.

I think this would really open up options for mages on gameplay.

Nice clean white towers setup in magical forests.....

Druid strongholds in cherry blossom groves....

Ugly looking ruins in sludge pits surrounded by alchemical furnaces and high tier essentia gens belching out flux...

Dark necromancer's tower in an eerie biome with cages filled of skeletons and zombies to be fed into the essentia furnaces....

Love it. :D
