### ISSUE TITLE
[Bug]Coke Oven Brick can harvest by hand, but shows not harvestable.

### ISSUE THREAD

**Issue by Yesterday17** [GTNewHorizons/GT-New-Horizons-Modpack#2618]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
In SinglePlayer Mode.
#
#### What did you try to do, and what did you expect to happen?
I just managed to harvest a coke oven brick by hand, but it shows not harvestable in waila.
#
#### What happend instead? (Attach screenshots if needed)
I got the coke oven brick.
#
#### What do you suggest instead/what changes do you propose?
--

**Comment by Dream-Master** [comment]
Yes this is a Railcraft/Waila/Wlava issue. Not much we can do here i guess.

**Comment by yukieiji** [comment]
Now that RailCraft is available for development, isn't this something that should be fixed?
This issue exists in v2.1.1.0.
