### ISSUE TITLE
Circuit not Oredicted in Assembler recipes

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#2639]
Some recipes in the assembler show up all circuits from one tier other not.

LV works well
MV not
HV works well
EV not

Tested in my dev pack 2.0.2.8

Might be a visual bug only.

**Comment by richardhendricks** [comment]
#circuitData shows the 3 EV tier circuits.

Assembler shows 6 recipes for QuantumProcessor and Nanoprocessor Assembly.

Workstation shows 19 recipes

Hyper-Rationing Pipe shows Workstation and Data Stick
Schematics Rocket Tier 1 shows Workstation
Field Generator Tier 2 shows Workstation
Schematics Moon Buggy Chip shows Workstation
Schematics Rocket Tier 2 shows Workstation
etc, rest of additional recipes are more rockets

Are these recipe properly oredicted to circuitData?  Hyper rationing pipe looks like a spelling error (data stick vs circuitData)

#circuitGood shows 3 MV circuits

Assembler shows 8 recipes for Good Electronic Circuit
Assembler shows 5 recipes for Good Integrated Circuit
Assembler shows 5 recipes for Integrated Processor

Cropnalyzer shows Good Electronic Circuit
Empty Map (OpenBlocks) Scale 1:8 shows Good Electronic Circuit
Filter Pipe (Extra Utilities) shows Good Electronic Circuit

Maybe those recipes are missing oredict to circuitGood?

**Comment by Dream-Master** [comment]
Maybe i update first and we see if this is fixed or still exist.

**Comment by Dream-Master** [comment]
@richardhendricks any news here?

**Comment by Prometheus0000** [comment]
This appears to be fixed by adding separate recipe pages for each rather than cycling through them on the same one? Can that be considered fixed, or is it going to be _more_ fixed later?
