### ISSUE TITLE
Can't put Tinker's Construct tools/weapons in Battlegear slots

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/GT-New-Horizons-Modpack#2652]
#### Which modpack version are you using?
2.0.2.7
#
#### What did you try to do, and what did you expect to happen?
Attempted to put Tinker's Construct tools in Battlegear slots. Tested with pickaxe, shovel, axe, shortbow & arrows, and throwing knives. Not yet tested with other Tinker's Construct tools.
#
#### What happened instead?
None of the aforementioned tools or weapons can be placed in the Battlegear slots. Torches also cannot be placed in them.

**Comment by Dream-Master** [comment]
A few you can place there allready in 2.0.2.8. The rest later.
