### ISSUE TITLE
[RFC] High Tier Ores without purpose

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#2669]
#### What do you suggest instead/what changes do you propose?
Make some recipes for Samarium, Ceruclase, Vulcanite, Rubracium, Alduorite, other high tier ores without purpose... maybe for LuV/ZPM/UV+ recipes...

**Comment by codewarrior0** [comment]
Isn't Samarium used for LuV motors? 

The other ones you listed are Metallurgy ores... I seem to recall being able to make Blaze Rods from Vulcanite the last time I played with Metallurgy?

**Comment by bartimaeusnek** [comment]
yupp samarium used only for motors...

**Comment by benstuwie** [comment]
Some of the ones you mentioned, I can't remember which exactly, but I know vulcanite, ceruclase and rubracium for sure, we're used in high tier motors before 2.0. The latter two were what gated UV for the most part. It sucked though. You had to quarry planets in the t7-t8 region if you wanted motors. I think I even like the current 256 superconductor recipe for UV more. I was really happy when samarium was gone from the recipes, wish that didn't come back. If you add them, don't add them for motor parts. Maybe just some centrifuge recipes that give useful stuff, or conversions like that one dust that is thaumium, or infused gold/shadow iron sorts of things.

**Comment by Dream-Master** [comment]
Sure make suggstions but not in 2.0.3.0 anymore.

**Comment by Zoko061602** [comment]
Many of these unused Metals are Metallurgy Metals, so I gave them all uses which kinda fit to their original use.
 I also gave them Chemical Formulars from when I played a bit with the GregTech API:
- Hepatizon (SnCu3)Au []
- Angmallen AuFe [No real use, but annoys players when using the smeltery, can be sperated in a Centrifuge]
- Adamantium Ad [Alloys to Tartarite]
- Atlarus Aa [Alloys to Tartarite]
- Tartarite AaAd [Infinity Catalyst (by default)]
- Ignatius Si(FeS2)5CrAl2O3Hg3(CSMa)2 [Pyrotheum ?]
- ShadowIron Fe* [Turns with Mercury to Iron and Salis Mundus]
- ShadowSteel VMaCr(Fe*50C) []
- Sanguinite PuMa [BloodMagic ?]
- Oureclase TiMa [Ichor Stuff ?]
- Midasium AuMa [Original Metallurgy usage: turns every othe Metal into gold]
- Vyroxeres PbMa [Soldering Metal for Thaumcraft ?]
- Aldurite AlMa [Alloys to Inolsahite]
- Inolashite (AlPb)Ma2 []
- Kalendrite PdMa []
- Amordrine PtPdMa []
- Prometheum PmMa []
- Carmot (AgAu)2Ma []
- Rubracium RbMa []
- Haderoth Rb(Pt2FeMa)2 []
- Infuscolium VMa [Alloys to Shadowsteel]
- Orichalcum OsSp [Additional Wand Tier (Orichalcum Studded Cosmic Neutronium Wand)]
- Celenegil PtOsSp []
- Ceruclase TiSp [Material for Machine Parts]
- Lemurite AlSp [Maybe useful for EnhancedPortals ?]
- Vulcanite Si(FeS2)5CrAl2O3Hg3(CSMa)2Sp [Pyrotheum ?]

**Comment by Drobac** [comment]
Those ores/metals are leftover from old assembly line recipe before reworks. Would be a pain to re-add the to recipes, should probably replace the mixes with something useful or get removed completely

**Comment by benstuwie** [comment]
I agree on that

**Comment by Dream-Master** [comment]
We found a use for it.

**Comment by Zoko061602** [comment]
@Dream-Master ?

**Comment by Dream-Master** [comment]
For the unused stuff

**Comment by Zoko061602** [comment]
Yeah but what will you use it for?

**Comment by Dream-Master** [comment]
Idk yet

**Comment by MakinToge** [comment]
Would love to have a Fluid Catalytic Cracking system using those ! Might open a discussion on this ...
