### ISSUE TITLE
Electromagic tools infusion recipes and gregtech metaitems

### ISSUE THREAD

**Issue by ruSauron** [GTNewHorizons/GT-New-Horizons-Modpack#2694]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Tried to make Thaumium Drill (EMT:ThaumiumDrill) with Infusion. That recipe need MV drill with 0 durability that can be obtained with cheating only.

And when i check Drill of the Rockbreaker (EMT:DrillRockbreaker) infusion recipe it need Thaumium Drill with 0 Eu and 1/27 durability. But you will get 0/27 thaumium drill after infusion. I thing that rockbreaker recipe should be changed to 1/27 or even better fully charged 26/27 instead of 0/27?

Check also:
Iron omnitool (EMT:Omnitool)
Diamond omnitool (EMT:Diamond Omnitool) (circuits also not oredicted)

#
#### What happend instead? (Attach screenshots if needed)
I cannot craft that drill - infusion cannot start.
![2018-03-12_19 29 37](https://user-images.githubusercontent.com/4716758/37295353-010e86e0-2629-11e8-9751-75b208014f55.png)

#
#### What do you suggest instead/what changes do you propose?
Allow oredict on this recipe or if it is not possible use MV drill with thaumium head and lithium battery (charged one i think).

**Comment by Dream-Master** [comment]
Will check

**Comment by DV666** [comment]
Sorry to up this topic but issue is still here.

![2019-06-28_03 36 39](https://user-images.githubusercontent.com/17729817/60311124-221bdf80-9956-11e9-8b9a-9f9a8b07d64c.png)
![2019-06-28_03 36 47](https://user-images.githubusercontent.com/17729817/60311125-22b47600-9956-11e9-9e19-2cd00924f557.png)
![2019-06-28_03 36 52](https://user-images.githubusercontent.com/17729817/60311127-234d0c80-9956-11e9-9242-626317ffd05c.png)
![2019-06-28_03 37 56](https://user-images.githubusercontent.com/17729817/60311130-247e3980-9956-11e9-8a3f-cf0af626a0e0.png)

**Comment by richardhendricks** [comment]
@bartimaeusnek
