### ISSUE TITLE
[Automagy] Recipes need nerfing

### ISSUE THREAD

**Issue by ershnsyn** [GTNewHorizons/GT-New-Horizons-Modpack#2712]
#### Which modpack version are you using?

2.0.3.0

#### What did you try to do, and what did you expect to happen?

The alchemical boiler recipe seems very cheap compared to the alchemical furnace: no arcane stone bricks, no thaumium plates, no boiler tank.

![screen shot 2018-03-14 at 15 49 41](https://user-images.githubusercontent.com/37359957/37387352-66486392-279f-11e8-8ea8-2660b05599c4.png)

In comparison here is the alchemical furnace recipe:

![screen shot 2018-03-14 at 15 54 09](https://user-images.githubusercontent.com/37359957/37387512-042be3d6-27a0-11e8-8861-9b1fd2e31c75.png)

#### What do you suggest instead/what changes do you propose?

Make the alchemical boiler recipe a bit harder ?

**Comment by Dream-Master** [comment]
One mod is nerfed the other not.

**Comment by mtesseracttech** [comment]
When I get some time, I can think of some good recipes

**Comment by ershnsyn** [comment]
Ok, that explains it.
I'm leaving it in your hands then.

**Comment by Dream-Master** [comment]
Sure. Some day  it will be nerfed.
