### ISSUE TITLE
Assembly Line recipe book

### ISSUE THREAD

**Issue by Prewf** [GTNewHorizons/GT-New-Horizons-Modpack#2717]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
I'm trying to see the LuV tier assembly line books for everything. I started with the LuV-tier sensor. I have attached screenshots. It looks like this for everything I've scanned so far (Emitter, Sensor, Pump).
#
#### What happend instead? (Attach screenshots if needed)
![messedbook](https://user-images.githubusercontent.com/35204071/37510483-6e2c2e62-28b8-11e8-9e37-f60709190617.png)
![messedstick](https://user-images.githubusercontent.com/35204071/37510485-6fa25ca8-28b8-11e8-9566-51c872852f6f.png)
![messedbook1](https://user-images.githubusercontent.com/35204071/37510488-711f410e-28b8-11e8-8df0-b25bbfd5efeb.png)
![messedbook2](https://user-images.githubusercontent.com/35204071/37510489-7136dc92-28b8-11e8-8f9e-ffb2f942fd22.png)

#
#### What do you suggest instead/what changes do you propose?
If I go into single player and try to reproduce this, it actually makes the proper book. So it only happens in multiplayer. See the following:
![workingbook](https://user-images.githubusercontent.com/35204071/37510325-f18445ca-28b7-11e8-881d-45561024a535.png)
![workingstick](https://user-images.githubusercontent.com/35204071/37510330-f31170ac-28b7-11e8-8765-0825407b0d08.png)
![workingbook1](https://user-images.githubusercontent.com/35204071/37510332-f681b7d8-28b7-11e8-85f2-be9a1a90f0be.png)
![workingbook2](https://user-images.githubusercontent.com/35204071/37510333-f698c4d2-28b7-11e8-8565-e0238ddaa150.png)
Why is this happening?/Please fix this.

**Comment by Dream-Master** [comment]
I thought this was fixed?
@technus @richardhendricks @mitchej123

**Comment by mtesseracttech** [comment]
Can confirm, this also happened to me with the fusion computer recipe book. It has a few unlocalized components in there.

**Comment by Prometheus0000** [comment]
This is fixed already, unless you mean for other languages or something.
