### ISSUE TITLE
Lootgames weird block behavior

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/GT-New-Horizons-Modpack#2723]
#### Which modpack version are you using?
Epsilon
#
#### If in multiplayer; On which server does this happen? 
Epsilon server
#
#### What did you try to do, and what did you expect to happen?
When i scan dungeon light block with thaumometr i see realy weird shit - just look at video. I think it hurt server performance alot.
https://youtu.be/h4L4ZxajE1o

**Comment by Dream-Master** [comment]
It would be better add some aspects to the Blocks.
