### ISSUE TITLE
There is no nuclear decay display on the panel NuclearControl.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/GT-New-Horizons-Modpack#2741]
#### Which modpack version are you using?
Latest.
#
Nuclear Control does not display the decay time of nuclear fuel.

https://i.imgur.com/Gp5QwNN.png

**Comment by Dream-Master** [comment]
@Pilad best way would to report it on the original repo.
If it is a bug i gues xbonny will fix it.
https://github.com/xbony2/Nuclear-Control/issues

**Comment by Pilad** [comment]
https://github.com/xbony2/Nuclear-Control/issues/137

**Comment by repo-alt** [comment]
There is apparently a PR fixing it https://github.com/xbony2/Nuclear-Control/pull/179 but it messes up whitespaces and the author went incommunicado (a bit weird after doing the main job)

**Comment by Dream-Master** [comment]
@repo-alt we can fork it.

**Comment by The1stRonin** [comment]
Was this never fixed? I'm still having this issue on 2.1.1.0

**Comment by Dream-Master** [comment]
or this one 
https://github.com/Thorfusion/Nuclear-Control/commits/pr/2

**Comment by The1stRonin** [comment]
Thanks, that would be appreciated. I use thorium reactors extensively. If you do fix it would you mind commenting back here so I know to upgrade my version? Thanks!

**Comment by Dream-Master** [comment]
@The1stRonin are there changes we need from Impact ?

**Comment by The1stRonin** [comment]
Changes from Impact?

Sorry, I don't understand.

**Comment by The1stRonin** [comment]
I don't know (I couldn't even find a java file to install for that one).

I'm not sure if the time is off (even though it's displaying now)...

It's showing 15:58:14 when I have 52% of the fuel rods left in the reactor. Does GT:NH make any changes to the length that fuel lasts that might be confusing the calculations?

**Comment by Dream-Master** [comment]
[IC2NuclearControl-2.4.6a-pr-2.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7359694/IC2NuclearControl-2.4.6a-pr-2.zip)
[IC2NuclearControl-2.4.6a-IMPACT.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7359695/IC2NuclearControl-2.4.6a-IMPACT.zip)
@The1stRonin can you test both ?

**Comment by The1stRonin** [comment]
Both seem to work without any issues that I saw.

Both fix the fuel time.

I couldn't see any differences between the 2 but I'm sure you would be able to understand what is different better being able to understand the code?

**Comment by Dream-Master** [comment]
code wise they very similar. Only some render stuff was added.

**Comment by The1stRonin** [comment]
I guess either would be fine to add then it seems?

The only quirk I noticed was on multi-displays that already exist in the world sometimes the left-most display would be the wrong color (slightly different shade of green to the rest). But breaking and replacing the block fixed this 100% of the time.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/Nuclear-Control/pulls

**Comment by The1stRonin** [comment]
Thanks Dream.
