### ISSUE TITLE
NewFairestOfThemAllSpawnChance too low.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/GT-New-Horizons-Modpack#2753]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Used the witchery Mirror,  a lot.  Including setting up use core golems to use it.

The fairest of them all to spawn.
#
#### What happend instead? (Attach screenshots if needed)
No spawn, even with six golems up and clicking.
#
#### What do you suggest instead/what changes do you propose?
I'd suggest increasing the fairestofthemall chance from 0.01 to something where it may actually have a semi chance of spawning, perhaps 1 or so if it's on a scale of x/100.    It may not seem that bad you could just setup an automated system like that-  except~~

Every time you use the mirror to try to spawn her, it posts to everyone in the current dim "Mirror, mirror, on the wall, who is the fairest one of all?"    So for a witch/wizard trying to get a heart of gold-  they could potentially annoy their peers quite a lot over the hours of all the Mirror, Mirror-  that percentage kinda seems like something more suited to single player only, or servers with TONS of witches using them like a pure witchery pack.

Again, not sure if it's 0.01/100 or 0.01/1  but I've used it well over 180 times by this point with no result.

**Comment by richardhendricks** [comment]
Is there no option to stop the message spam?  Pretty poor mod design IMO.

**Comment by Teirdalin** [comment]
I agree.  Doesn't look like there's a setting for "disable spam"  lol.

Anyways, from testing it seems to be on a 0.01/100 chance,  which is awful for that design.   I'd suggest 5% or 10% overall, the heart isn't even a powerful reagent.

**Comment by draknyte1** [comment]
The Messages are only sent client side.

`Line 1001:com.emoniph.witchery.blocks.BlockMirror.TileEntityMirror.Java`
```
if (!fairestFound) {
                  ChatUtil.sendTranslated(EnumChatFormatting.AQUA, player, "witchery.rite.mirrormirror.you", new Object[0]);
                }
```
`Line 16:com.emoniph.witchery.util.ChatUtil`
```
public static void sendTranslated(EnumChatFormatting color, ICommandSender player, String key, Object... params)
  {
    player.addChatMessage(new ChatComponentTranslation(key, params).setChatStyle(new ChatStyle().setColor(color)));
  }
```

**Comment by Teirdalin** [comment]
Although it may be client-side messages,  it does annoy everyone else in the dimension.  lol

**Comment by draknyte1** [comment]
It shouldn't send messages to anyone but the client doing the interaction, is moreso my point.

**Comment by Teirdalin** [comment]
Ah,  maybe it's a bug then.
They could even see the messages when I used use-core golems to do it.

**Comment by richardhendricks** [comment]
Does it have a world.isRemote check in there?

**Comment by Dream-Master** [comment]
Did i need to change a witery cfg settings or is this a coding problem ?
@Teirdalin @richardhendricks @draknyte1

**Comment by bartimaeusnek** [comment]
coding problem, as far as i know it wont be easy to fix this.
