### ISSUE TITLE
Server Crash - CME with an Enderzoo mob.

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/GT-New-Horizons-Modpack#2772]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#

https://github.com/SleepyTrousers/EnderZoo/issues/202

**Comment by bartimaeusnek** [comment]
i think this is a random issure, and since it doesn't happens often, i would only give it low prio...

**Comment by boubou19** [comment]
crashlog is no longer availiable, closing this
