### ISSUE TITLE
Thaumic Bases nerf

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/GT-New-Horizons-Modpack#2776]
#### Which modpack version are you using?
2.0.3.0
#

#### Why you're writing this issue?
I had some time, so I thought: 'Why not try to nerf Thaumic Bases?' and I think I did...
#

#### What did you change?
- Added recipes for thaumium and void wands and thauminite caps  
- Added recipes for all Bracelets (simmilar to GTNHs Wand recipes)
- Made both Anvils more expensive (Thaumium and Void)
- Node Manipulation now requires Titanium (EV)
- All Foci are know more expensive (Crystal Clusters, Lenses, ...)
- Added a recipe for concentrated Taint 
- Changed the recipe for the thaumic relocator (More like the elevator)
- Made Spikes more expensive (simmilar to ExtraUtillities spikes)
- The void seed (TB) now requires tons of essentia
- Added more Warp
#

#### Do you need some Core-Mod Items?
 - Thauminite Caps would be nice (I used elementium caps as placeholder) 
 - (I also thought about blank Foci stones, since I used Mnemonic Matricies[Is that the Plural of Matrix?])
#

#### Do we need to know anything else ?
- Im not sure weather Revolver upgrades are nerfable or not
- Seeds require code changes to prevent duplication
- (Don't add thauminite as GT Material, since it would break the explaination why it can't be turned into wand caps directly)
- TB Iron spikes should be renamed to steel spikes
#

#### Screenshots
![thaumium anvil](https://user-images.githubusercontent.com/32712367/38227523-e5a6b184-36fe-11e8-92ea-b8646b70c737.PNG)
![concentrated taint](https://user-images.githubusercontent.com/32712367/38227524-e5bca192-36fe-11e8-9459-f951386bd49a.PNG)
![gold bracelet](https://user-images.githubusercontent.com/32712367/38227525-e5d37cc8-36fe-11e8-8536-965c4d3de477.PNG)
![thauminite bossed void wand](https://user-images.githubusercontent.com/32712367/38227526-e5ea3e68-36fe-11e8-839d-3f459e9855a7.PNG)
# 
#### Files
[Thaumic-Bases-02-Wands.txt](https://github.com/GTNewHorizons/NewHorizons/files/1870089/Thaumic-Bases-02-Wands.txt)
[Thaumic-Bases-01-Main.txt](https://github.com/GTNewHorizons/NewHorizons/files/1870090/Thaumic-Bases-01-Main.txt)

**Comment by Dream-Master** [comment]
Thanks for you help. I will add some research changes maybe later but this is a good start :)

**Comment by Dream-Master** [comment]
Will add some new Wand caps in GTNH for Wand recipes.

**Comment by bartimaeusnek** [comment]
> Node Manipulation now requires Titanium (EV)

That thing is already expensive for what it does and blows up on a regular base... (~ every 500ticks, without Ichorium (late IV / early LuV) blocks on top, I ended up just getting nodes and use the Theological Recombiner instead)

Why do the IRON spikes require STEEL in their recipe? Maybe change this to ExUtil ones + some magic stuff...

And im not quite sure if the Void Spikes and the Void Plant Seed (which i use in Berries++) recipe may be a bit too expensive...

Other than that, good job. 👍 @Zoko061602

**Comment by Dream-Master** [comment]
Let me take a look first before we change stuff again.

**Comment by bartimaeusnek** [comment]
@Dream-Master sure, this are just my thoughts on these new recipes.

**Comment by Zoko061602** [comment]
@bartimaeusnek I guess the thing you meant is the node linking device and not the node manipulator. The node manipulator doens't blow anything up, it is completely secure. The node linking device only requires MV parts.

Since ExUtils Iron Spikes already use Iron, I don't wanted to use Iron for TBs Spikes, maybe that coudl be changed to an iron block, 3 iron ingots and 2 steel screws.

The void spikes might be a bit to expensive, maybe it should use regular salis mundus instead of blocks.

The void plant seed, should be that expensive, you can get tons of void seed pretty fast, and it's also duplicateable with a fortune pick.  The only real problem when making this seed is getting nebrisum essentia, anything else is doable at HV: 
- All the plants have crucible recipes
- Herba & Messis: crops
- Victus: flowers
- Praecantatio: magical wood
- Tenebrae : Obsidian
- Auram : Aurelia
- Desidea: Beds
Thats all just grindy and not realy hard to make.

**Comment by Dream-Master** [comment]
@Zoko061602 any way to contact you on my discord or elsewhere if I have a quick question?

**Comment by Zoko061602** [comment]
@Dream-Master I have no idea how to use discord

**Comment by Dream-Master** [comment]
@Zoko061602 download the app 
https://discordapp.com/
and join on
https://discord.gg/kTrF3nV

**Comment by richardhendricks** [comment]
BTW, you don't have to download any app to use discord, I never did.  I just use their web portal interface.  You get most of the functionality (even voice chat if that matters).

**Comment by Dream-Master** [comment]
sure that works too.

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/728

**Comment by richardhendricks** [comment]
Is this ticket done? Looks like changes were merged already?

**Comment by Dream-Master** [comment]
yes but the mod never nerfed completly. Same for Automagy
