### ISSUE TITLE
Crash on placing GS Hybrid Solar Panel or Solar Wind Panel

### ISSUE THREAD

**Issue by lexx1191** [GTNewHorizons/GT-New-Horizons-Modpack#2781]
#### Which modpack version are you using?

#2.0.3.0
#### If in multiplayer; On which server does this happen? 

#single
#### What did you try to do, and what did you expect to happen?
when you install solar wind generator, the game crashes

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 4/3/18 10:43 PM
Description: Ticking block entity

java.lang.NoSuchFieldError: ticks
	at galaxyspace.SolarSystem.planets.overworld.tile.TileEntitySolarWind.func_145845_h(TileEntitySolarWind.java:102)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:

[crash-2018-04-03_22.43.15-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/1872980/crash-2018-04-03_22.43.15-server.txt)

#### What do you suggest instead/what changes do you propose?
the question is solved updating to the latest version

**Comment by Dream-Master** [comment]
The problem updating gs again will cause multiple new problems because this mod guy change most of his blocks and items in every new version so I need to add blocks and items  in my core mod. Will see if I found the time in the future to do this a last time.

**Comment by lexx1191** [comment]
well, if you can't update, disable the blocks causing crash

**Comment by Dream-Master** [comment]
Can you named the blocks needs to be disabled here ?

**Comment by bartimaeusnek** [comment]
```
Name: GS Solar Wind Panel // galaxyspace.SolarSystem.planets.overworld.tile.TileEntitySolarWind
Block type: ID #2186 (tile.SolarWindPanel // galaxyspace.SolarSystem.planets.overworld.blocks.BlockSolarWindPanel)
Block data value: 3 / 0x3 / 0b0011
```

**Comment by Dream-Master** [comment]
Is this the only recipe i need to remove?

**Comment by lexx1191** [comment]
yes

**Comment by Dream-Master** [comment]
Sure if i have 50+h free time i will look into it.

**Comment by Dream-Master** [comment]
let it open and when i have time i look over it.

**Comment by richardhendricks** [comment]
Considering actions dev is now taking, I don't know if we want to continue updating GS.  Talk to Bart for details.

**Comment by glowredman** [comment]
Is fixed in https://github.com/GTNewHorizons/Galaxy-Space-GTNH/commit/23034cda20fb57642d59e65c6beafb42c525f61a. Some tests have happend and no further issues were found but we should keep an eye on this.
