### ISSUE TITLE
Bucket duplication bug in golem workbench

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#2798]
#### Which modpack version are you using?
2.0.2.7 (Windows Technic)
#

#### What did you try to do, and what did you expect to happen?
Place a golem workbench.
Set to craft salt from bucket of water and cooking pot.
Assign it a Empty container golem with order & entropy upgrades.
Tag golem to empty to a container and to carry salt.
Feed workbench buckets of water.

Expect: golem consumes water bucket, produced salt and places in container (THIS HAPPENS)
Expect: single empty bucket to be place back in workbench (THIS Goes Wrong)

#
#### What happend instead? (Attach screenshots if needed)
Two empty buckets are placed in workbench, essentially creating one free bucket per salt produced.
Believe specifically related to the behavior of one of the golem upgrades.

**Comment by Dream-Master** [comment]
A few recipes where changed so need to be tested in 2.0.3.1 again.

**Comment by richardhendricks** [comment]
BTW, in 2.0.3.1, this recipe will be crafting *edible salt*, not salt you can use in GT chemistry.
