### ISSUE TITLE
Mirrored Jars stop transferring essence

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#2803]
#### Which modpack version are you using?
2.0.2.7 (Technic Windows)
#

#### What did you try to do, and what did you expect to happen?
Place a thaumcraft Mirrored Jar (A), link and place Mirrored Jar (B).
As essentia is added to jar A it is shared between the 2 jar.
Allow both jars to completely fill.
Drain essence from jar B.

Expect: essence to be split between 2 jars

#
#### What happens instead? (Attach screenshots if needed)

Jar A remains full, jar B remains empty with no essence transfer occurring.

If you manually (with phial) remove some essence from jar A everything start working again until jar a completely refills again.

Makes any sort of system with mirrored jars rubbish as need to keep manually poking them to keep them working.

**Comment by drayath** [comment]
Just been checking, the item is from the Thaumacraft mod Gadomancy

I have added it to their issue tracker (https://github.com/makeoo/Gadomancy/issues/93) though it looks rather inactive there.

**Comment by Dream-Master** [comment]
Will ask HelfirePVP for an update
