### ISSUE TITLE
Thaumonomicon incorrect description

### ISSUE THREAD

**Issue by Rakdarian** [GTNewHorizons/GT-New-Horizons-Modpack#2816]
#### Which modpack version are you using?
2.2.7
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I opened my thaumonomicon and opened the butcher golem core tab i expected it to to describe the golem core
#
#### What happend instead? (Attach screenshots if needed)
It described something to do with filling and emptying tank inventories
#
#### What do you suggest instead/what changes do you propose?
Replace the page with the correct one.

**Comment by bartimaeusnek** [comment]
Also applies to the Thaumonomicon Pages for Wands.

**Comment by Prometheus0000** [comment]
Already fixed.
