### ISSUE TITLE
Why is radon derived from plutonium 239?

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/GT-New-Horizons-Modpack#2819]
At the moment we are receiving radon from plutonium 239, but in reality it is obtained from radium 226, which is obtained as a result of the decay of thorium 232.
But from the spent thorium rods, we obtain lutetium, which occurs in samaskite ((Y, Er) (Nb, Ta)2 О6), gadolinite (Y2FeBe2Si2О10), yttralite  ((Y, Th, U, Fe)2 Si2О7), xenotime (YPO4).
Is it possible to change the chain of reception of radon approximately to the real?

**Comment by CalterOK** [comment]
So to receive radium, it will also be necessary to burn thorium in nuclear reactors (now this is required for obtaining lutetium).

**Comment by bartimaeusnek** [comment]
But thorium is way easier to obtain than plutonium. IMO this should not be changed because of balance reasons > reality reasons.

**Comment by 0lafe** [comment]
I'm happy not needing multiple useless EV reactors setup just to make radium

**Comment by CalterOK** [comment]
How can this break the progression? Now the pluton can still be obtained without reactors in a centrifuge. It is necessary to wait here for a full cycle of thorium rods, and it will not be possible to bypass it, although it is available ahead of time for its processing, it takes much more. As for obtaining lutetium, it can be obtained from the above minerals, and they can be obtained from Rare Earth.

**Comment by 0lafe** [comment]
I still think it would make the radon process take too long, and require machines that become useless pretty fast

**Comment by CalterOK** [comment]
Before thermonuclear synthesis, radon can be obtained only through a chemical reactor or matter. This method is becoming obsolete, but not as soon as you think, and there are not so many additional mechanisms.

**Comment by draknyte1** [comment]
GT++ enables another way to obtain Radon as well.
Via Nuclear Decay of other elements.
