### ISSUE TITLE
Awakened Ichorium pick cannot mine Enceladus in square mode

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#2820]
#### Which modpack version are you using?
2.0.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Mine anything in 'square' mode
#
#### What happend instead? (Attach screenshots if needed)
Works as if in block mode.
See also https://github.com/GTNewHorizons/NewHorizons/issues/1014

**Comment by 0lafe** [comment]
Might be because some of the enceladus stuff is supposed to be mined with a shovel?

**Comment by repo-alt** [comment]
Enceladus ice is mined with a shovel, which is kind of strange but tolerable. Enceladus stone though?
Also hammer and, reportedly, draconium pick work ok.

**Comment by Dream-Master** [comment]
Will check if I can change the hardness of the stone ore the level of the pickaxe. Not sure if this will solve the problem.

**Comment by bartimaeusnek** [comment]
The harvestlevel is Stone, the hardness 0.5F, so it is not likely to be an issute with these valures.

**Comment by repo-alt** [comment]
Tau Ceti E stone also cannot be mined with bound or ichorium pick

**Comment by Dream-Master** [comment]
@repo-alt why ?

**Comment by bartimaeusnek** [comment]
T Ceti E stone needs shovel afaik

**Comment by repo-alt** [comment]
I have no  idea why, it is an addition to the Enceladus bug report. Perhaps there are other planets affected by this bug.

**Comment by richardhendricks** [comment]
Possibly related to GG oreplacement?  Has that dimension been respawned since this fix?

https://github.com/GTNewHorizons/GalacticGregGT5/pull/3

**Comment by bartimaeusnek** [comment]
i re-checked and TCetiE and Enceladus Ice need shovel. Enceladus blocks are made from the material `Material.ground` which should explain the issure. The Ichorium Pickaxe can only mine the Materials which are registered for pickaxes.

https://github.com/GTNewHorizons/ThaumicTinkerer/blob/9f79fc786df05c8ef0e7a674ee0d36e3afd3f1a5/src/main/java/thaumic/tinkerer/common/item/kami/tool/ItemIchorPickAdv.java#L100

**Comment by Prometheus0000** [comment]
We should be able to fix this now, right?
