### ISSUE TITLE
Dupe bug with dyes

### ISSUE THREAD

**Issue by Day0Dreamer** [GTNewHorizons/GT-New-Horizons-Modpack#2840]
#### Which modpack version are you using?
2027

#### If in multiplayer; On which server does this happen? 
SP with LAN + cheats enabled

#### What happend instead? (Attach screenshots if needed)
https://cdn.discordapp.com/attachments/234936569360809996/435230135373922334/2018-04-16_02-08-36.mp4
(or search discord with _in:#help Buuuuug :3_)

#### What do you suggest instead/what changes do you propose?
Fix it

**Comment by Dream-Master** [comment]
Guess project red won't fix things anymore but it is open source. Are other items ne duped too? @Day0Dreamer

**Comment by Day0Dreamer** [comment]
From the looks of it - ProjectRed makes no distinction between types of color. So it's kind of like Equivalent Exchange, when you can freely substitute red for yellow or blue.

Why it dupes, I've no idea :) 

Too tired to do more testing, because it's my main job as it is :(

**Comment by Dream-Master** [comment]
But only dyes or other stuff too?

**Comment by Dream-Master** [comment]
@Day0Dreamer are you able to dupe all kinds of items or only dyes?

**Comment by Day0Dreamer** [comment]
Apologies, workdays, I intended to do more testing on the weekend. As far as I've tested, it's been the case only with minecraft recipes concerning 16 minecraft vanilla dyes.

Haven't had any issues with GT autocrafting.
