### ISSUE TITLE
Storage Interface on Super/QuantumChechts does not work propperly

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#2851]
#### Which modpack version are you using?
2.0.3.1Dev

Storage Interface on Super/QuantumChechts does not work propperly

**Comment by repo-alt** [comment]
isn't that fixed already?

**Comment by GTNH-Colen** [comment]
It seems like any super/quantum chests that were placed before the update cannot support the AE storage bus but any new ones placed down can. Tested all the super/quantum chests in sp and all work perfectly well with the storage bus but all the old ones in my base do not.

**Comment by repo-alt** [comment]
This is weird, no NBT or anything were added to the digital chest. Perhaps it is a server issue? can you test a new chest at the server?

**Comment by GTNH-Colen** [comment]
Just crafted a new super chest and it works with AE on eta, also noticed that the old super chests contain less items than the new ones strangely. Eg for the super chest IV the new ones in NEI show 32,000,000 storage but the old super chest IV I have in game shows 21,870,000 storage. Not sure what's up here but given that new ones work anyways, it's not the end of the world.

**Comment by repo-alt** [comment]
It turned out that GT++ handles the old super chests, and our version does the new ones. They have different meta - ours is 138, Alk's is 949.

**Comment by repo-alt** [comment]
This may be closed I think?
