### ISSUE TITLE
Water Fluid Cell does not return Empty Cell when right-clicking on terrain

### ISSUE THREAD

**Issue by Snaggerr** [GTNewHorizons/GT-New-Horizons-Modpack#2868]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
I right clicked on the ground with a fluid cell filled with water in my hand, and I expected for a water block to be placed where I clicked, and the water cell to be replaced with an empty cell.
#
#### What happend instead? (Attach screenshots if needed)
The water does get placed on the ground, but an empty cell is not returned to your inventory.
#
#### What do you suggest instead/what changes do you propose?
Make placing cells in the world return an empty cell.  I don't know how this works with cells filled with other fluids; I've only tried it with water cells.

**Comment by draknyte1** [comment]
IC2 bug that won't ever get fixed by IC2.

Best bet would be to remove the ability to place water with them or freely add a cell when a water cell is right clicked.

**Comment by richardhendricks** [comment]
IC2 is closed-source right?

**Comment by draknyte1** [comment]
Correct. 
Hence my suggestions to fix externally in an event handler.

**Comment by Dream-Master** [comment]
Not sure if can ask aroma to fix it. need to chat with him

**Comment by draknyte1** [comment]
I don't think it's worth the time asking, especially for 1.7.10. Hence why I provided two alternative fixes to add straight into DreamCore. 

Hell, I'll add it into GT master branch if it proves to work fine via DreamCore/GT++ implementation. (Might test in GT++)

**Comment by eldritch-cookie** [comment]
hello it isn't clear to me what is the resolution? i can replicate this problem with water and lava on 2.7.4, if we can't modify IC2 code why not make a new exact replacement item in another open source mod we can modify? especially considering this specific one is slightly bugged?
