### ISSUE TITLE
[Suggestion] Better Boat mod for QOL

### ISSUE THREAD

**Issue by bertcardinaels** [GTNewHorizons/GT-New-Horizons-Modpack#2874]
We all know how annoying boats can be in 1.7.10
The mod Better Boat fixes a couple of things with boats:    
- Client-Server desync: Your boat won't randomly crash into things because the Client and Server disagrees about the boat's position!
- Boats won't drop planks and sticks anymore: If you crash, you get your boat back!
- Your boats won't crash when colliding with an animal/mob: If you collide with a squid or a swimming mob, it gets damaged, you bounce off and can move onward   

I've quickly tested all the other boats in creative too and didn't stumble upon any issues with them, these features only seem to apply to vanilla boats.  
As exploration is a part of the pack experience this would make water transport a bit easier.

Link to the mod:  https://minecraft.curseforge.com/projects/better-boat  
Link to the needed library: https://minecraft.curseforge.com/projects/bookshelf  
I've checked the config of the library and it is only adds a warning if duplicate potion ID's are used. Better Boat does not have a config.

**Comment by bartimaeusnek** [comment]
I've recoded a bit and removed the need of the library. 
https://github.com/bartimaeusnek/BetterBoat/releases/tag/1.1.0

So im in favor of this mod 😄

**Comment by Ugachaga** [comment]
A good idea for mod, but I'm against it in the pack since it only improves standard boats. There are so many different upgraded boats, so no sense to improve only the simplest one.

**Comment by verknaller** [comment]
I'll do some further testing regarding the breaking/damaging mobs with all the other boats. I'm fairly certain the desync issues should be fixed on other boats too.  
I'll fire up an instance of this pack with the mod, and one without and come back with some more testing results.

**Comment by draknyte1** [comment]
Adding the mod doesn't change load time at all. 

All boats probably inherit desync fixes. 

Rubber boat doesn't break, neither does the electric boat. So the boat drop is moot for those two and I can't think of any others. 

There's literally only benefits to adding this QoL mod with no downsides.

**Comment by Ugachaga** [comment]
I once watched the code of this mod, all that it does is replace the already created standard boats with their own. Inheritance will not work.

**Comment by Ugachaga** [comment]
@bartimaeusnek Yeah, would be great to add support at least for IC2 and Thaumic boats. In the current state the mod will encourage players to use only vanilla boats.

**Comment by KaneHart** [comment]
@Dream-Master This should make it in before next major version. I think this was forgotten.
https://github.com/bartimaeusnek/BetterBoat/releases/tag/1.1.0

Boats are prob one the worst ways to travel due to dsyncing, etc.

**Comment by draknyte1** [comment]
Boats are already fixed by ForgePatcher. 

https://github.com/alkcorp/ForgePatcher

**Comment by Prometheus0000** [comment]
So is this done then? Are we adding the other mod or not?

**Comment by Dream-Master** [comment]
I will check out the mod since I never seen any forge patcher mod to test it.
