### ISSUE TITLE
[Harvestcraft] Plum trees not spawning in worldgen

### ISSUE THREAD

**Issue by ls-r** [GTNewHorizons/GT-New-Horizons-Modpack#2876]
Version 2.0.3.0

**Pam's Harvestcraft plum trees are not being created during world generation.**

Plum trees should be spawning given that in `config/harvestcraft.cfg` plum tree generation is true:

![screen shot 2018-04-26 at 3 25 50 am](https://user-images.githubusercontent.com/16024676/39297748-90e2af3a-4901-11e8-9bc6-93321a031651.png)

In the mod's code itself, specifically in `mods/Pam's 
Harvestcraft 1.7.10m.jar/com/pam/harvestcraft/PamTreeGenerator.class` all of the Harvestcraft oak-based fruit trees are randomly generated in the overworld *except* for plums:

![screen shot 2018-04-26 at 3 29 40 am](https://user-images.githubusercontent.com/16024676/39298216-d394a436-4902-11e8-9419-7bbec725ba6d.png)

It would be a nice little change if you could just copy/paste a new case and enable plum tree spawning if you are allowed to edit the source code of other people's mods.

Thanks for the awesome pack!

**Comment by EddieEnder** [comment]
Okay, here's the modified .class file and the .jar file as well, so that's all updated and good to go! I loaded up a test world and flew around until I found a plum tree naturally spawned, so I can confirm that the changes worked :D

[harvestcraft with plums.zip](https://github.com/GTNewHorizons/NewHorizons/files/1957808/harvestcraft.with.plums.zip)

**Comment by Dream-Master** [comment]
ok cool will add when i be back home in a few Days.

**Comment by DannyParker0001** [comment]
This bug is back
![image](https://user-images.githubusercontent.com/24753108/184474205-ea8ce175-1b0d-47af-b35a-0b5f45f7aac2.png)
There in 2.0.5.1, not there in >2.0.9, regressed somewhere in-between

**Comment by McFrugal** [comment]
Is this still broken?  If so, perhaps we should just add a quest that requires a bunch of other fruit in exchange for a plum sapling.

**Comment by wlhlm** [comment]
Fixed in 1.0.16-GTNH
