### ISSUE TITLE
Crash while handling Draconic sword

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/GT-New-Horizons-Modpack#2910]
#### Which modpack version are you using?
V 2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Held Shift+Enter of an enchanted Draconic sword in the inventory while forgetting this is a 1.7 pack. As such, I expected nothing to happen.
#
#### What happend instead? (Attach screenshots if needed)
Crash, with the following report.
[crash-2018-05-07_14.24.34-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/1980002/crash-2018-05-07_14.24.34-client.txt)

**Comment by Prometheus0000** [comment]
This doesn't appear to happen anymore.
