### ISSUE TITLE
Thaumcraft golemancy bell

### ISSUE THREAD

**Issue by TheGodwar** [GTNewHorizons/GT-New-Horizons-Modpack#2914]
When try to craft golemancy bell on magic workbench-client has crash...how to be with golems?)

**Comment by bartimaeusnek** [comment]
attach log please.

**Comment by richardhendricks** [comment]
@TheGodwar Did you get it working?

**Comment by Prometheus0000** [comment]
Doesn't crash when I tested it on all 3 types, if it still occurs, reopen.
