### ISSUE TITLE
Alchemical furnace TPS drop

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/GT-New-Horizons-Modpack#2926]
#### Which modpack version are you using?
2.0.2.7

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
Alchemical furnaces cause a huge TPS drop when they fill up with essentia.

**Comment by bartimaeusnek** [comment]
I don't think we can do anything here.

**Comment by richardhendricks** [comment]
@AlexBucket Can you provide some data?

**Comment by richardhendricks** [comment]
Need to investigate, maybe we can try adding some information to the quest to tell people not to let it fill up.  Does the lag only occur when they are full?

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57199802-f594aa00-6f48-11e9-99e6-9fa9f5f15ebd.png)

**Comment by boubou19** [comment]
this is not fixed code wise: 
![image](https://user-images.githubusercontent.com/12850933/99392704-69ed2f00-28dc-11eb-9904-f7f2b2f02b3d.png)
![image](https://user-images.githubusercontent.com/12850933/99392929-d23c1080-28dc-11eb-8336-2452971f9d06.png)

**Comment by draknyte1** [comment]
Technically is fixed as of last week when I wrote some ASM for it. I’m looking to further optimise some internal TC code used by everything before I release it though. 

Prior to that, no.

**Comment by Prometheus0000** [comment]
And hopefully prevent the crash on finishing melting something?

**Comment by Dream-Master** [comment]
@draknyte1 where you write asm code? In gt++

**Comment by boubou19** [comment]
fixing the thaumcraft api will fix the alchemical boiler from automagy too it seems:
![image](https://user-images.githubusercontent.com/12850933/100154646-398e2d80-2ea6-11eb-9a7e-4f102d270e01.png)

**Comment by boubou19** [comment]
this one is actually fixed
