### ISSUE TITLE
Google Spreadsheet - TC Aspects

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#2927]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
TC Aspects on Google sheets: https://docs.google.com/spreadsheets/d/1Rsz0rH9tIVJxr18b1Z6-QxOSaEKssxF7u2naQTq2Mqg/edit#gid=324521832
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Not really an issue.

The existing TC Aspect spreadsheet was rather annoying to navigate and search; so I parsed the data and recreated the sheet (screenshot: http://213.48.63.6:5003/aspect-ss-new.png ).  Please find a copy of the sheet here: http://213.48.63.6:5003/aspects-ss-new.xlsx

Feel free to use this version if you prefer the layout.

I'm not sure if google sheets can keep the filter function which would be useful to see only the type you need.

I have spot checked the data to ensure it matches the original sheet, maybe someone may want to spot check it too.

Highbeam

**Comment by richardhendricks** [comment]
Highbeam, how's the progress on this?

What do think about picking some items and creating a quest line for scanning?

**Comment by Prometheus0000** [comment]
Neither link works, closing.

**Comment by tyrael93** [comment]
@Prometheus0000 
Uh, no. 
They both do actually. Here.
![Screenshot from 2021-05-21 14-31-20](https://user-images.githubusercontent.com/5557920/119137623-49479280-ba41-11eb-99b2-0b3039eff5d1.png)
