### ISSUE TITLE
Dragon egg duplication

### ISSUE THREAD

**Issue by SirFischi** [GTNewHorizons/GT-New-Horizons-Modpack#2928]
#### Which modpack version are you using?
GTNewHorizons-2.0.3.0-1.7.10
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I tried to get all of my items out of my ME system using a ME IO port and a formation plane set to output as item.
#
#### What happend instead? (Attach screenshots if needed)
When trying to output a Dragon egg it didnt get removed from disk and thus kept getting dropped as item.
![2018-05-13_20 26 47](https://user-images.githubusercontent.com/39245032/39970450-0249b72a-56ec-11e8-91a3-f4517c514d6f.png)

#
#### What do you suggest instead/what changes do you propose?
If it isnt intended as a way to farm dragon eggs i would try to fix it.

**Comment by Dream-Master** [comment]
Dragon egg rain :) Never seen before

**Comment by repo-alt** [comment]
Can't be reproduced with just AE2, probably HEE related

**Comment by repo-alt** [comment]
HEE bug, it spawns the egg and at the same time cancels the spawn event.

**Comment by Dream-Master** [comment]
maybe we need to fork HEE @repo-alt

**Comment by repo-alt** [comment]
It is ARR

**Comment by repo-alt** [comment]
Maybe I can do a PR to the original repository.

**Comment by Dream-Master** [comment]
@repo-alt 

``I want to create a modification:

The terms say that you cannot redistribute the mod or modifications of the mod. You can play around with the code if you fork the project, but if you want to distribute it, you need my explicit permission. I haven't been in this situation yet, so if you create a modification, let me know and we'll figure something out.``

**Comment by repo-alt** [comment]
Ok, in any case it should be fixed first, then we may talk to hylex if he will accept PR or allow the fork.
