### ISSUE TITLE
Fusions reactors overclocking

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/GT-New-Horizons-Modpack#2929]
#### Which modpack version are you using?
Epsion one
#
#### If in multiplayer; On which server does this happen? 
Epsi
#
#### What did you try to do, and what did you expect to happen?
I noticed that fusion reactors have no recipe overclocking like other gt machines - Please, add it if possible.
![2018-05-13_21 44 11](https://user-images.githubusercontent.com/25028786/39970678-509a5234-56f8-11e8-9e56-d6b3a9b09d58.png)

**Comment by Dream-Master** [comment]
@Technus  any idea on this ?

**Comment by 0lafe** [comment]
Was it removed? They sure used to

**Comment by Anarack** [comment]
they do, or did, and judging by past issues by bloody they are supposed to.

**Comment by noobyaran9** [comment]
What is the starting power requirement?

**Comment by Anarack** [comment]
Have you timed the reactors plasma output to see if the scanner is just wrong on plasma output? The process time looks like it halved correctly.

**Comment by noobyaran9** [comment]
Just tested and it shows that it does overclock. Its just the tooltip is wrong. And it overclock with the usual 4x power 2x speed.

Below is the setup:
![2018-05-19_11 50 35](https://user-images.githubusercontent.com/13598309/40264626-2b20e006-5b5b-11e8-9456-e7b3cf30a86d.png)

MK1
![2018-05-19_11 50 42](https://user-images.githubusercontent.com/13598309/40264627-2b5096de-5b5b-11e8-94f0-342c91f3c396.png)
MK2
![2018-05-19_11 50 47](https://user-images.githubusercontent.com/13598309/40264628-2b8096f4-5b5b-11e8-8716-b58b7450f3cc.png)
MK3
![2018-05-19_11 50 51](https://user-images.githubusercontent.com/13598309/40264629-2bba601e-5b5b-11e8-8f48-4025075745a9.png)

I only ran it for awhile and from the below results, its obvious that it overclocked.
MK1 output:
![2018-05-19_11 51 16](https://user-images.githubusercontent.com/13598309/40264630-2ca2e4c4-5b5b-11e8-9be7-5a76b23f127f.png)
MK2 output:
![2018-05-19_11 51 19](https://user-images.githubusercontent.com/13598309/40264631-2d7a0710-5b5b-11e8-9a83-99593ad85dad.png)
MK3 output:
![2018-05-19_11 51 23](https://user-images.githubusercontent.com/13598309/40264632-2da896e8-5b5b-11e8-8d6b-adba708f7ccd.png)


Might need a fix to the scanner plasma output as its very misleading.

**Comment by Dream-Master** [comment]
@bartimausnek @richardhendricks is this possible code wise?

**Comment by richardhendricks** [comment]
Yeah should be possible, will need to look at code.
