### ISSUE TITLE
[Suggestion] Advanced Nano Chest Plate Hover

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/GT-New-Horizons-Modpack#2942]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Multiplayer
#
#### What did you try to do, and what did you expect to happen?
Advanced Nano Chest Plate Hover mode ist "schlechter" als der Electric Jetpack. Electric Jetpack hat "creativ flight" auf der stelle schweben. Mit  der Advanced Nano Chest Plate sinkt man im Hover Modus immer 
#
#### What do you suggest instead/what changes do you propose?
Wenn möglich die Advanced Nano Chest Plate Hover anpassen so das gleich wertig zu Electric Jetpack Hover.

**Comment by Dream-Master** [comment]
Von Welchen mods ausser ic2 sprechen wir? Gravisuit ? @PapaTim68

**Comment by bartimaeusnek** [comment]
Electric Jetpack hat aber auch keinen Rüstungswert... 
Translation of the Issure:
The Advanced Nano Chest Plate Hover mode is worse than the Electric Jetpack ones, due to slowly falling.

**Comment by alphaNOVAircraft** [comment]
@Dream-Master von Gravity suite

**Comment by Dream-Master** [comment]
müssen wir Namikon mal ansprechen @Namikon

**Comment by Namikon** [comment]
So either IC2 has changed the behavior of their jetpack, or something else is wrong here.
The IC2 Jetpack *never* gave "Creative Flight" in Hover mode; It is one unique ability to fly that IC2 has 
Currently, I'm sort of against a change to make the "low-grade" Jetpack creative-like. It would impact the new upgrade system I'm working on.

**Comment by Methes** [comment]
Namikon is right, although the IC2 jetpack has had creative flight for about a year now, making me sad when upgrading to nano chest plate jetpack and having actually worse flight.
Switching those would make more sense although I have no idea what upgrade system is being developed.

**Comment by alphaNOVAircraft** [comment]
Then we need to nerf the ic2 jetpack, having a better jetpack with a worse hover mode doesnt make any sense.
