### ISSUE TITLE
Extruder Recipe Missing

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#2967]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Went to make the Ardite Crossbow Body in the MV Extruder. I expected to get an Ardite Crossbow Body Quest ID: 1153.
#
#### What happend instead? (Attach screenshots if needed)
Absolutely nothing lol. Tried up to 10 Ardite Ingots. It looks like it might not be oredict because it only shows Tinkers Construct Ardite Ingots in the recipe.
#
#### What do you suggest instead/what changes do you propose?
Allow it to use GregTech Ardite ingots as well?

**Comment by Dream-Master** [comment]
all original tinkers materials not in gt machines. need to add tones of recipes because other parts not work. @Vexatos is there a config option for enable tinkers materials in gt machines?

**Comment by Vexatos** [comment]
Tinkers' Gregworks does not touch other TCon materials, and I cannot think of an easy way to add recipes for them. You'll have to add them manually.

**Comment by Dream-Master** [comment]
ok thanks for info @Vexatos

**Comment by Dream-Master** [comment]
will do later probably.

**Comment by Prometheus0000** [comment]
This appears to be already done, as you can use either type of ingot in the extruder now.
