### ISSUE TITLE
Steamcells recipe addition

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#2986]
add new high tier recipes to get stemcells. No stupid egg farms anymore.

**Comment by draknyte1** [comment]
How about I add Giant Chickens and Giant Eggs? 🤣

**Comment by bartimaeusnek** [comment]
Stemcell Crop? 😸

**Comment by Prometheus0000** [comment]
We get stemcells a totally different way now.
