### ISSUE TITLE
Essentia Condenser (Gadomancy)

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/GT-New-Horizons-Modpack#2990]
#### Which modpack version are you using?
2.0.4
#
When filling this repository of essences with golems, there is no limit to the amount of stored essences.
![2018-05-23_11 33 36](https://user-images.githubusercontent.com/35035276/40464641-fe7420d6-5f24-11e8-8355-bbf83de6fc9d.png)
Without improvement, it stores up to 200 pieces of essence of each type, but as you can see in the screenshot there is much more.
When the structure itself draws in essence, everything works correctly.

**Comment by Dream-Master** [comment]
So is this a visual bug? @CalterOK

**Comment by CalterOK** [comment]
There is no visual, it really stores so much essence.

**Comment by Dream-Master** [comment]
ok but what this issue about? Is the condenser to cheap or to powerful? @CalterOK

**Comment by CalterOK** [comment]
The problem is that you can put more into it than it should store. in the end we get an unlimited storage of all essences.

**Comment by Ethryan** [comment]
According to the [source](https://github.com/makeoo/Gadomancy/blob/master/src/main/java/makeo/gadomancy/common/blocks/tiles/TileEssentiaCompressor.java), 
The Essentia Condenser has a limit of 3000 total essence. Can you test this @CalterOK?

**Comment by CalterOK** [comment]
Its initial volume is 200, to 3000, it is increased by Element of Darkness (on 350 for a piece)
![2018-05-25_14 40 35](https://user-images.githubusercontent.com/35035276/40542725-0c3c2fd2-602a-11e8-963d-4948cbd8329d.png)

**Comment by Ethryan** [comment]
Ah, i understand

**Comment by Dream-Master** [comment]
@CalterOK should we change the recipe to make it harder? I cant make much on source need some help.

**Comment by Ethryan** [comment]
found an open [issue](https://github.com/makeoo/Gadomancy/issues/71) about this.

**Comment by CalterOK** [comment]
Is it possible that a condenser could only pull in essences from nearby cans, and it would not be possible to serve it with golems (it also requires that the condenser be able to pump the essences even if they were not there before)? Since this error only occurs when the essence is loaded with golems. As for the error about free essences, I'm seeing this post

**Comment by CalterOK** [comment]
This is a very specific design that finds application only for infusion. If we raise the required aspects for activation of the design (250+), then it will transfer it to one level with the ME network and it will not be so attractive.

**Comment by yukieiji** [comment]
This bug has not been fixed yet.(v1.0.7.5)
This issue only occurs when carrying in  Essentia using Golem.

**Comment by yukieiji** [comment]
This bug also exists in GTNH ver2.0.8.0Pre(gadomancy-1.7.10-1.0.7.6)
![2019-12-27_17 57 04](https://user-images.githubusercontent.com/40425798/71510591-b568aa00-28d2-11ea-8490-57a7a63304bf.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek can you look at this issue. Thanks

**Comment by Cinobi** [comment]
Still preset at current live zeta server, but if it do not couse significant lags i think this can stay - as a nice alternative of thaum ae(which looks not magic atall!)
