### ISSUE TITLE
Void Putty not consuming Spellbinding Cloth

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/GT-New-Horizons-Modpack#3017]
#### Which modpack version are you using?
2.0.3.7
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Repair spellbinding Cloth with Void Putty
Cloth to get repaired without duping.
#
#### What happend instead? (Attach screenshots if needed)
Kept damaged cloth, as well as got repaired cloth.
#
#### What do you suggest instead/what changes do you propose?
Consumes cloth during repair.

**Comment by Dream-Master** [comment]
@Teirdalin Can you post a few pics to show me how it working?
Thanks

**Comment by Teirdalin** [comment]
https://i.imgur.com/IYguBAC.png
https://i.imgur.com/267tfLo.png
