### ISSUE TITLE
Infusion Claw causes crashes.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/GT-New-Horizons-Modpack#3027]
#### Which modpack version are you using?
2.0.2.7
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Set an Infusion Claw on a pulse timer for 5 seconds being relayed from a magic hourglass through mercurial redstone signals connected via magic mirrors.
It to activate and fail due to nothing being on the altar.
#
#### What happend instead? (Attach screenshots if needed)
Server crashes every five seconds.
#
#### What do you suggest instead/what changes do you propose?
Give the Infusion Claw the ability to not crash servers.

**Comment by Dream-Master** [comment]
a crashlog would be nice

**Comment by Teirdalin** [comment]
Hey Dream, guess the log would be here-  https://paste.fedoraproject.org/paste/u5J0N~v4uY0xDIM2Fgma6Q

**Comment by bartimaeusnek** [comment]
https://github.com/makeoo/Gadomancy/blob/8ce6944b33fc80f1d278234dafecf8257d3d93a3/src/main/java/makeo/gadomancy/common/blocks/tiles/TileInfusionClaw.java#L250
should be the issure.
So either
fakePlayer, world or wandStack is null and should not be null.

**Comment by Teirdalin** [comment]
Seems it's gotta be the fakePlayer, was in a protected area   We did a test outside of towny with the same exact setup with no crash.  So I suppose this really isn't an issue, just a plugin thing.  Thanks anyways Dream and Bartimaeusnek.

**Comment by bartimaeusnek** [comment]
@Teirdalin @Dream-Master 
https://github.com/bartimaeusnek/Gadomancy/releases/download/1.0.7.4/gadomancy-1.7.10-1.0.7.4.jar

**Comment by Dream-Master** [comment]
Will be in the next release and can be tested.

**Comment by PredVesTNiK2142** [comment]
2021 - the problem is not solved. and your current form does not allow you to send a new ticket :)

**Comment by Ethryan** [comment]
Reopened this since it doesn’t seem fixed.

**Comment by repo-alt** [comment]
The old bug was due to town protection, and this one looks exactly the same. Tbh I don't know what else may be checked in TileInfusionClaw.performClickBlock

**Comment by bombcar** [comment]
we don't have town protection but we DO have GriefPrevention - could it be that something similar needs to be applied? Does it use a fake player? If so that might explain it ...

**Comment by repo-alt** [comment]
Of course the claw uses fake player, who do you think uses the wand

**Comment by bombcar** [comment]
> Of course the claw uses fake player, who do you think uses the wand

RIP assuming Thaumcraft would just ... you know, work without it :D

**Comment by repo-alt** [comment]
Well, Bart's fix works around Thermos town protection (I mean the claw still doesn't work w/o fake player permission, but the server does not crash). Looks like your grief prevention plugin does some unspeakable evil in, idk, block change event handler?

**Comment by bombcar** [comment]
> Well, Bart's fix works around Thermos town protection (I mean the claw still doesn't work w/o fake player permission, but the server does not crash). Looks like your grief prevention plugin does some unspeakable evil in, idk, block change event handler?

Yeah, it is VERY aggressive - and that's almost certainly the cause. I propose a note in the associated quest maybe as a workaround? As it's likely not worth the coding to fix griefprevention

**Comment by PredVesTNiK2142** [comment]
I think it's better to take into account that not everyone uses Thermos and such ... Ahem ... There are no interesting protections on other cores.

Я думаю что лучше учесть что не все используют Thermos и таких... Кхм... Интересный защит на других ядрах нет.

**Comment by MrWye** [comment]
[crash-2022-10-24_17.41.21-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9853048/crash-2022-10-24_17.41.21-server.txt)
