### ISSUE TITLE
Filing Cabinet hiding the number of items

### ISSUE THREAD

**Issue by code32** [GTNewHorizons/GT-New-Horizons-Modpack#3045]
#### Which modpack version are you using?
2.0.4.2

#
#### If in multiplayer; On which server does this happen? 
private Multiplayer (localhost)

#
#### What did you try to do, and what did you expect to happen?
https://youtu.be/I1c37F9i3Ug

**Comment by Ugachaga** [comment]
Seems client not syncing propertly.
