### ISSUE TITLE
Forestry Fixes

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#3061]
Forrestry has a few Major bugs that need to be fixed:

- [x] alvearys can coprrupt world chunks with a shitton of NBT entries (solution: restrict items to be saved in NBT to a maximum valure)
- [ ] Butterflies flying in unloaded chunks 
- [ ] "crash if your head is stuck in a hive" bug
- [ ] improve performance for the whole pollination/leafs system
- [x] incompability with JAVA 9 due to a shitty java version check addon (solution: remove the addon)

**Comment by Dream-Master** [comment]
Forestry is open source so go ahead @bartimaeusnek
