### ISSUE TITLE
[Suggestion] New high tier plastic

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/GT-New-Horizons-Modpack#3063]
#### Which modpack version are you using?
2.0.4.2
#
#### What do you suggest instead/what changes do you propose?
I looked throuh some recipes and saw that high tier machine hulls only require PTFE, which looks quite cheap to me, since it only requires methane, chlorine and fluorine, so I thought that a bit of more advanced chemistry should be required.

I think Polybenzimidazole (PBI) would be quite nice.
If I got it right, that stuff is more resistant than PTFE and also more complex, just look at this:
![polybenzimidazole](https://user-images.githubusercontent.com/32712367/41124151-57c4a610-6aa1-11e8-86e4-5519622157e4.png)

Additional information:
https://en.wikipedia.org/wiki/Polybenzimidazole_fiber
https://www.professionalplastics.com/professionalplastics/PP-1410TechnicalCeramicsBrochure_04.pdf

**Comment by WarlordWossman** [comment]
Yeah IV is where PTFE starts for hulls. Could technically start at HV and use a higher one for IV+ but we have to do it in a way where you want to go for the assembler recipe. 
With PTFE for HV hulls people would probably be happy to pay the extra stainless and wrought iron instead.

**Comment by Kortako** [comment]
I'm not high tier enough yet, so take my opinion with a grain of salt, but I see two potential problems with this recipe:

1.  If this new plastic is used JUST for making higher machine tier hulls, who is going to want to do that?  We have something similarly complex that everyone keeps trying to get people to use, but no one wants to do it: High Octane Gasoline.  This looks even more complex than that, so maybe at some point people will just be like "screw that" and do the shaped crafting recipe instead.  Is there a different high tier plastic you could use that actually has uses for other things too?

2.  Is Pyrolusite easily obtainable?  If I'm not mistaken, you get it from the Manganese/Tantalite vein right?  I want to say those veins are fairly rare and small, so I'm not sure how viable that is.   But maybe at higher tiers that isn't a problem.

Also @WarlordWossman, hulls only start needing PTFE at ZPM I believe, not IV.  Kind of a big difference there.

**Comment by WarlordWossman** [comment]
You are right, the idea stands tho.
I think at some point we could just remove shapeless recipes, HV sounds a bit early for that tho.
Maybe for EV+ there is just no shapeless option anymore (thoughts?)

**Comment by bartimaeusnek** [comment]
I really like the idea of a new high tier plastic, but i would suggest cutting the steps to re-create it to 3-4 steps at most. Please dont overcomplicate this.

**Comment by richardhendricks** [comment]
Also, I think at this stage, there's not really a reason to make it a real-world plastic processing flow, right?  Maybe use desh or other tier 2/3/4 materials as part of the processing.

**Comment by Prewf** [comment]
I like the idea of the material itself, but not the recipe in the OP. It would be cool if this plastic was used in the space suit for Venus.

**Comment by 0lafe** [comment]
I love this, totally should play a roll in LuV+ parts in assembly lines too or something like that. If you want to keep it realistic I'd get it, but coal tar isn't something you should use for high tiers, nor copper, nor zinc, nor potassium, and definitely not pyrolusite. Gating it is great, but most of these aren't endgame materials, and further emphasize current endgame issues. Make it cost naquadria, neutronium, or something actually endgame. Right now it's dumb oil products and things you stop mining at those tiers. Zinc isn't in many places, pyrolusite really isn't, coal isn't, and potassium barely comes from anything, and nothing you mine late game. 

New plastic sounds cool, maybe also give it uses like how you can use normal plastic for 2 boards, or like ptfe for 4, maybe pbl gives 8 or something.

**Comment by noobyaran9** [comment]
>New plastic sounds cool, maybe also give it uses like how you can use normal plastic for 2 boards, or like ptfe for 4, maybe pbl gives 8 or something.

If its not a recipe that is easily sustainable at highier tier, there is no point making this plastic at all. I'd rather use the other plastic which are easier to sustain.

How many uses are this plastic going to get? Im going to be againsting this idea if it has really less usage or its sole existance is just to gate certain multiblock. Don't force it on people to get it just to get that certain multiblock to go through some stupid method of getting the plastic. Just like what happened before the assembly line uses the oredicted rubber recipe that only takes polydimethylsiloxane when I only have all the other type of rubber except polydimethylsiloxane.

**Comment by richardhendricks** [comment]
But that's kind of the purpose of the whole modpack??  And of course the number of uses are limited, it's still in the potential idea stage.  PPL complain about no endgame, then when endgame is developed, complain it is incomplete. Well duh.

**Comment by 0lafe** [comment]
My complaint is that copper, potassium, bezene, phenol, manganese and coal aren't endgame when I've never ran low on iridium, osmium, naquadria, neutronium, or sammarium as that somehow seems to be a high tier thing now

**Comment by richardhendricks** [comment]
That's fair.  But saying this proposed new material has no uses and should just be removed adds 0 to the discussion.   How about proposing places where it can be added?  Sheesh.  This whole modpack is about *stupid method of getting*.

**Comment by 0lafe** [comment]
Yea, the problem is that it could be something new, but it's not. We already have so many uses for a lot of the stuff in this recipe, while what is seemingly meant to be high tier items just stockpile up and are rarely used. I mean, endgame GT is struggling with copper and tin while having hundreds of thousands of all ores you get t2+ planets.

**Comment by richardhendricks** [comment]
Yeah that's a problem with trying to keep it "realistic", most common things on Earth use common elements!  :D

**Comment by 0lafe** [comment]
>ExU

>Ender IO

>thaum

>withcery


But yes, switching copper for a made up element is a step to far lol

**Comment by Krispion** [comment]
Change the metals to late tier materials as has been suggested. Shouldn't be too much of an issue, this plastic conveniently uses some metals in its real life chemistry. Good to take advantage of it.

**Comment by ScriptedPiky** [comment]
Although while the potential of the metal used in the Polybenzimidazole (PBI) is currently Copper, this plastic has been added in for a while and will close. Reopen if discussion for tweaks or adjustments is necessary.
