### ISSUE TITLE
UHV super conductors for higher tiers 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#3069]
#### Which modpack version are you using?
2.0.4.2
#
#### What do you suggest instead/what changes do you propose?

I think it would be nice to have UV and UHV crafts of the UHV super conductors. Right now you can only make them from LuV or ZPM pumps, but nothing higher. Considering you're not really making much from those tiers by UHV, I find it weird that an integral part of superconductors is a tiering system aimed at irrelevant tiers. 

Numbers of superconductors for UV-UHV pumps have to be pretty high. The UV pump alone costs a stack of super conductors and is harder to make than the zpm one. So UV pump should probably give something like 3 stacks of UHV super conductors, or 48 4x wires. UHV maybe 2x that? So 48 8x wires? 

You need thousands upon thousands of these wires, it'd be nice to be able to use higher tier items to make them faster, instead of dumping the same low tier materials we dump into everything. Why else would anyone really make a UHV pump right now?

**Comment by ScriptedPiky** [comment]
Closing this after realizing these superconductors have been in the game for quite a while now. See recipes below for curiosity of current recipes:
Material composition is **Nq*4(Ir3Os)3EuSm**
![image](https://user-images.githubusercontent.com/41557212/83111320-435ee180-a079-11ea-9f1a-ce62b508de63.png)
Material composition is **D6SpNt7Tn5Am6**
![image](https://user-images.githubusercontent.com/41557212/83111443-72755300-a079-11ea-982c-c674917eb41f.png)
