### ISSUE TITLE
seaweed weird behavior

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#3084]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to harvest seaweed with shears
#
#### What happend instead? (Attach screenshots if needed)
Seaweeds have weird behavior: if i harvest the first layer of the seaweed, i got only one seaweed.
And if I harvest at an higher layer, every parts of the seaweed higher than the harvested level will disappear and I will also get only one seaweed, but the layers below the harvested layers will remain.
#
#### What do you suggest instead/what changes do you propose?
i'll suggest to drop every layers higher than the harvested level to drop as well as the harvested layer which is droped.

**Comment by Dream-Master** [comment]
So far i know did we cant change Galaxy space code wise. Not sure if we can change the harvestlevel. @bartimaeusnek

**Comment by boubou19** [comment]
when i say "harvest level" i was reffering to the height sorry for the misleading

**Comment by bartimaeusnek** [comment]
@Dream-Master @boubou19 it uses the normal Grass behavior, im not so sure if i can change this

**Comment by glowredman** [comment]
Has been fixed in https://github.com/GTNewHorizons/Galaxy-Space-GTNH/commit/f7d24a2bb3b9b85c8265df892b36e9749437e6f5.
