### ISSUE TITLE
Manganese duplication

### ISSUE THREAD

**Issue by galyfray** [GTNewHorizons/GT-New-Horizons-Modpack#3094]
#### Which modpack version are you using?
2.0.4.4
# 
#### What did you try to do, and what did you expect to happen?
duplicate manganese nugget with Thaumcraft Metalurgic Perfection(witching gadgets) at a normal cost recipe cost expeted matalum permutatio other standard aspect ex: motus volatus lucrum recipe
#
#### What happend instead? (Attach screenshots if needed)
the recipe is too expancive for this metal cost nebrisum 
#
#### What do you suggest instead/what changes do you propose?
change in the duplication recipe nebrisum by motus

**Comment by bartimaeusnek** [comment]
these recipes are autogenerated from the gregtech materials, when the GT Materials have no Aspects or not enough aspects, there will be nebrisum as placeholder.

**Comment by galyfray** [comment]
is there a way to add aspect to GT material ?

**Comment by bartimaeusnek** [comment]
yes this needs code changes. Metalurgic Perfection is [WiP]

**Comment by Dream-Master** [comment]
@bartimaeusnek did you take care it ?

**Comment by galyfray** [comment]
\config\GregTech\MaterialProperties.cfg --> line 2614 chane "METALLUM" by any ather aspect will fix it :)

**Comment by draknyte1** [comment]
```
[19:33:11] [Client thread/ERROR] [FML/]: Caught exception from gregtech
java.lang.IllegalArgumentException: No enum constant gregtech.api.enums.TC_Aspects.
	at java.lang.Enum.valueOf(Unknown Source) ~[?:1.8.0_71]
	at gregtech.api.enums.TC_Aspects.valueOf(TC_Aspects.java:5) ~[TC_Aspects.class:?]
	at gregtech.api.enums.Materials.initMaterialProperties(Materials.java:1697) ~[Materials.class:?]
	at gregtech.api.enums.Materials.init(Materials.java:1550) ~[Materials.class:?]
	at gregtech.GT_Mod.onPreLoad(GT_Mod.java:392) ~[GT_Mod.class:?]
```

For future reference:
If you do change the aspect name, be sure to spell it properly and with the expect capitalization. Otherwise you will encounter these crashes.
