### ISSUE TITLE
Stone mug with rum can't go into fluid canning machine, incorrect item ID

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [GTNewHorizons/GT-New-Horizons-Modpack#3100]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I was trying to complete the quest 'rum'. To complete the quest I would need to put the rum from the previous quest into the fluid canning machine and rebottle the rum into glass bottles. 
# 
#### What happend instead? (Attach screenshots if needed)
However this does not work as the recipe in NEI uses item-ID 4284:2, but the rum you get from the previous quest 'non-industrial rum' has item-ID 4284:12918.
#
#### What do you suggest instead/what changes do you propose?
I suggest that either the recipe in the fluid canning machine be changed to accept the stone mug with rum, or maybe, if possible, the different kinds of rum (stone mug/glass bottle) be oredictioneried such that the quest and the fluid canning machine no longer care about what kind of fluid container my rum is in.

**Comment by Dream-Master** [comment]
@bartimausnek

**Comment by bartimaeusnek** [comment]
ye will fix

**Comment by Prometheus0000** [comment]
This is already fixed.
