### ISSUE TITLE
[recipe] Thaumic Bases Shards from Ores

### ISSUE THREAD

**Issue by galyfray** [GTNewHorizons/GT-New-Horizons-Modpack#3117]
#### Which modpack version are you using?
2.0.4.4
# 
#### What did you try to do, and what did you expect to happen?
process ordo infused stone with the ore destruction (thaumic bases) recipe
#
#### What happend instead? (Attach screenshots if needed)
not working with gt ore
#
#### What do you suggest instead/what changes do you propose?
change the thaumic recipe or make a recipe to create tc ore from gt ore

**Comment by bartimaeusnek** [comment]
@Dream-Master if its okay, ill change the recipe to use GT Ores instead of Thaumcraft Ores. Or better disable this recipe completely?

**Comment by Dream-Master** [comment]
use gt ores is ok for me. Why disable? @bartimaeusnek

**Comment by Ghengis88** [comment]
I agree with Dream, use GT ores, i noticed this last year but just thought it disaled, but if that was not intentionall then the recepie should be changed
