### ISSUE TITLE
Server crash due to unlocking the ghost amulet (impure) recipe in the ender compendium

### ISSUE THREAD

**Issue by mergendil** [GTNewHorizons/GT-New-Horizons-Modpack#3121]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
multiplayer, private server
#
#### What did you try to do, and what did you expect to happen?
unlock stuff in the compendium to have info on what does the ghost amulet do
#
#### What happend instead? (Attach screenshots if needed)
crash
#

**Comment by Dream-Master** [comment]
crashlog please @mergendil

**Comment by mergendil** [comment]
[crash-2018-06-14_16.10.07-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/2102757/crash-2018-06-14_16.10.07-server.txt)
