### ISSUE TITLE
Minor issue: HV Turbo Steam Turbine quest gives tier 3 bag, not 4

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#3126]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
HV Turbo Steam Turbine quest gives tier 3 lootbag, guess it should be tier 4.

**Comment by Dream-Master** [comment]
will change.

**Comment by Prometheus0000** [comment]
This seems to be fixed already.
