### ISSUE TITLE
Client crash.

### ISSUE THREAD

**Issue by PhoenixTV** [GTNewHorizons/GT-New-Horizons-Modpack#3127]
#### Which modpack version are you using?
2.0.4.3
#
#### If in multiplayer; On which server does this happen? 
Private 
#
#### What did you try to do, and what did you expect to happen?
Client crash. RMC by pollen on wood.
[Client Log] (https://pastebin.com/uQ3YmfrC)

[Server Log] (https://pastebin.com/r9PiTY6T)
#### What happend instead? (Attach screenshots if needed)

#

**Comment by bartimaeusnek** [comment]
Please explain exactly what you did, this issure seems to be somewhat deeper than normal ones.

**Comment by vampirebat74** [comment]
I have the same issue hosted on a LAN server. I noticed that killing butterflies, for some reason, dropped oak pollen. Using that pollen to right click a leaf would immediately crash the game.
