### ISSUE TITLE
request recipe to 'clean' sticky piston and make regular piston.

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/GT-New-Horizons-Modpack#3137]
#### Which modpack version are you using?
.27
#
#### If in multiplayer; On which server does this happen? 
n/a
#
#### What did you try to do, and what did you expect to happen?
request recipe to 'clean' sticky piston and make regular piston.
#
#### What happend instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
maybe chemical wash, or craft with bucket of water or ?

**Comment by alphaNOVAircraft** [comment]
Not sure if such a recipe is needed but shouldnt be to hard to implement either

**Comment by bartimaeusnek** [comment]
i would recommend to add both, chemical bath and water bucket.

**Comment by DoomSquirter** [comment]
I only ask for it cause mob farm is filling up with normal/sticky pistons but I have almost no use for sticky pistons.  would like to convert them.

**Comment by MotiasF33** [comment]
#6755
