### ISSUE TITLE
Vis relays randomly disconnecting

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#3139]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
Epsilon and single player
#
#### What did you try to do, and what did you expect to happen?
I tried to recharge my wand using vis relays I had previously set up and used.
#
#### What happend instead? (Attach screenshots if needed)
Relay beam appeared graphically broken and didn't transmit centivis to the wand.
No changes were made to the relays between them working and not working, they just disconnected after some time.
![image](https://user-images.githubusercontent.com/17787093/41502453-11591022-71b2-11e8-8d22-8dbec394b447.png)
#
#### What do you suggest instead/what changes do you propose?
Make the beam not randomly disconnect.

**Comment by alphaNOVAircraft** [comment]
are you sure that there are no chunck loading issues possible, could be related to chunk boarders

**Comment by KiloJoel** [comment]
The 2 that are disconnected there are in the same chunk, not sure how I would tell beyond that.
Even if it is a chunk issue, still seems like a problem to me if you have to manually fix your relays every time the chunkloader isn't on.
Would probably be useful to see if other people have had similar issues.

**Comment by galyfray** [comment]
i had the same isue on infitech try to tune your rellay and and place they nearer than the maximal distance it's not a fully fix but sligly decrease the random disconect

**Comment by Dream-Master** [comment]
So not a bug? @KiloJoel  @galyfray  @alphaNOVAircraft

**Comment by Methes** [comment]
It's Thaumcraft bug. Relays tend to eventually disconnect when crossing chunk borders and the chunks unload/reload.
The only fix is to replace the relay or chunkload all the chunks the path goes through. With them chunkloaded this doesn't happen.

**Comment by richardhendricks** [comment]
@KiloJoel Can you add chunkloaders and see if the issue continues?

**Comment by KiloJoel** [comment]
will do

**Comment by KiloJoel** [comment]
No disconnections happened with the chunks loaded

**Comment by DoomSquirter** [comment]
even with chunkloaders, in same chunk, you will still get random disconnects.
what usually works for me is place one vis relay, then try to get next one as far as you can.  then place it 1 block closer than extent.  maybe two.  do this for all connected relays.  I think maybe a rounding error or something?   
I had a persistent error like this on a BRC server for my infernal blast furnace and my everburn urns going to a dedicated ignis energized node all in same room/chunk.  Doing the above stopped the disconnects from happening entirely.

**Comment by Methes** [comment]
Interesting. My setup was probably close enough to each other then.

**Comment by DoomSquirter** [comment]
well my fix is incidental and one off.  I always do this when I use vis relays.  maybe I got lucky but my problem was persistent then it wasn't.  would be interesting to see if I was right tho about rounding errors in code lol

**Comment by GionaCantarutti** [comment]
This is still an issue and does not matter if chunk boarders are crossed. These two relays are in the same chunk and they reliably disconnect every single time i restart the game (on version 2.8.3)

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/eec8d527-66a2-4fcf-a54b-26e62ad8783e" />
