### ISSUE TITLE
Shard Recrystallization

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/GT-New-Horizons-Modpack#3141]
#### Which modpack version are you using?

2.0.4.0

#### What did you try to do, and what did you expect to happen?

I have shard recrystallization unlocked, and went to test it with amber dust in the alchemical construct.

#### What happened instead? (Attach screenshots if needed)

![amber](https://user-images.githubusercontent.com/36259908/41503630-45fb273e-719e-11e8-8292-34752e862a7d.png)

No recipe available. But the other dusts work.

**Comment by bartimaeusnek** [comment]
this might be a recipe issure.

**Comment by Prometheus0000** [comment]
Maybe I could take a look if you _said where it was, and what it was from_.

**Comment by leagris** [comment]
amber is not a shard, so no wonder it does not work with shard recrystallization.

**Comment by Prometheus0000** [comment]
I can see it on the research page, so it should work for amber, I just can't tell what mod it's from. And I tried looking.
![image](https://user-images.githubusercontent.com/8517039/99126150-926ee380-25d3-11eb-8113-0efda3262cb5.png)

**Comment by leagris** [comment]
Gregtech adds these researches because it introduced crushed and dusts of shards, so it hads means to recreate the shards from grinding ore of these.

**Comment by Prometheus0000** [comment]
That doesn't tell me the tab so I can find the zs file to see if it all looks ok. Or is it in the GT5U code?

**Comment by leagris** [comment]
It is even in GT5.07.07's code

**Comment by Prometheus0000** [comment]
Who puts something this long on one line?
```GregTech_API.sThaumcraftCompat.addResearch(tKey, "Shard Recrystallisation", "Fixing your precious crystals", new String[]{"ALCHEMICALMANUFACTURE"}, "ALCHEMY", GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedOrder, 1L), 3, 0, -11, -3, Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.VITREUS, 5L), new TC_Aspects.TC_AspectStack(TC_Aspects.PERMUTATIO, 3L), new TC_Aspects.TC_AspectStack(TC_Aspects.ORDO, 3L)), null, new Object[]{GT_MachineRecipeLoader.aTextTCGTPage + tKey, GregTech_API.sThaumcraftCompat.addCrucibleRecipe(tKey, OrePrefixes.dust.get(Materials.Amber), GT_OreDictUnificator.get(OrePrefixes.gem, Materials.Amber, 1L), Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.VITREUS, 4L))), GregTech_API.sThaumcraftCompat.addCrucibleRecipe(tKey, OrePrefixes.dust.get(Materials.InfusedOrder), GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedOrder, 1L), Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.VITREUS, 4L))), GregTech_API.sThaumcraftCompat.addCrucibleRecipe(tKey, OrePrefixes.dust.get(Materials.InfusedEntropy), GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedEntropy, 1L), Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.VITREUS, 4L))), GregTech_API.sThaumcraftCompat.addCrucibleRecipe(tKey, OrePrefixes.dust.get(Materials.InfusedAir), GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedAir, 1L), Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.VITREUS, 4L))), GregTech_API.sThaumcraftCompat.addCrucibleRecipe(tKey, OrePrefixes.dust.get(Materials.InfusedEarth), GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedEarth, 1L), Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.VITREUS, 4L))), GregTech_API.sThaumcraftCompat.addCrucibleRecipe(tKey, OrePrefixes.dust.get(Materials.InfusedFire), GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedFire, 1L), Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.VITREUS, 4L))), GregTech_API.sThaumcraftCompat.addCrucibleRecipe(tKey, OrePrefixes.dust.get(Materials.InfusedWater), GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedWater, 1L), Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.VITREUS, 4L)))});```

**Comment by leagris** [comment]
> Who puts something this long on one line?

This whole class is a bloated spaghetti mess.

**Comment by NoX-programer** [comment]
Right now I don't see amber in list of recipes of that research. And what will we do?
- say abmer is not shard, recrystallization not intended
- or add recrystallization of amber

I prefer the second one...

**Comment by Prometheus0000** [comment]
Feel free to try to get it to work
