### ISSUE TITLE
magical memory(creative) item from computronics is uncraftable

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#3165]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i tried to craft a magical memory(creative) item from computronics. I expected to see a recipe because others creative items from open computers are (teddiously) craftable
#
#### What happend instead? (Attach screenshots if needed)
the item has no recipe
#
#### What do you suggest instead/what changes do you propose?
pls add one

**Comment by Dream-Master** [comment]
What this item does to find a good recipes for it? @boubou19

**Comment by boubou19** [comment]
it gives infinite memory for opencomputers

**Comment by Dream-Master** [comment]
any recipe suggestion ?

**Comment by boubou19** [comment]
i'll look what i could do this night

**Comment by Bryfer** [comment]
Adding this item could create alot of lag on servers?
What kind of program do you want to use with the computer anyway?

**Comment by boubou19** [comment]
it will be an endgame recipe so not so much spam and i want to point out the fact that on reboot, at least it was the case on delta, the computers crash by them self with unrecoverable errors so you need to reboot them manually.

**Comment by boubou19** [comment]
and if you really want to stop players spamming this item just make the recipe over expensive like it's the case with stargates

**Comment by repo-alt** [comment]
tbh I never needed even 3.5 memory planks, and I use OC automation quite a lot.
The only place where it may be "usable" is to play with something like MineOS

**Comment by Teirdalin** [comment]
Can't the server rack handle more memory just fine?

**Comment by 0lafe** [comment]
>, at least it was the case on delta, the computers crash by them self with unrecoverable errors so you need to reboot them manually.

That makes a lot of sense, wondered why everything needed to be rebooted on restart. Any idea why it happens/how to stop it though?

**Comment by boubou19** [comment]
from what i read on internet, the computer usually crashes on reboot because the mod use a separated thread to handle the lua interpreter and if there are too much lags that thread isn't properly handled so it leads to an unrecoverable error. So i don't think we can do anything sadly.

**Comment by boubou19** [comment]
it's been age, but here is a proposal of a recipe (credit: Cinobi):
![image](https://user-images.githubusercontent.com/12850933/120682089-57170200-c49c-11eb-9044-2f47d064fa48.png)

This is very expensive for what it does, but it's a creative item, and a lot of creative items in the pack have a recipe, so why not this one? The price is justified by the fact that it can cause issues if spammed/used incorrectly, so putting an extremely high price for this will make the players think twice about their need of such item. It's also making file reading on massive files easier, such as music encoding for exemple. So imo it still has its niche use cases.

**Comment by Prometheus0000** [comment]
Cinobi should make a PR then, shouldn't they?

**Comment by boubou19** [comment]
well, none of us know where to put the recipe: in code? in a minetweaker script? tell me and i'll gladly make a PR

**Comment by GTNH-Afx237v7** [comment]
Those are easiest made in a Minetweaker script. iirc there is already a creative item recipe in the opencomputers script file.

**Comment by Prometheus0000** [comment]
In the Computronics.zs file, you can use Open-Computers.zs for examples.

null = no item
<ore:circuitMaster> =  oredict of that item, in this case a circuit tier
<OpenComputers:item:103> = an item from the OC mod (EXACT spelling), named 'item', with meta 103. Use this if specifying a specific item or there's no oredict. /mt hand ingame should help you out with this stuff.

**Comment by boubou19** [comment]
here is the corresponding PR: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/8010
