### ISSUE TITLE
weird behavior with superbuffers, typefilters and itemfilters

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#3166]
#### Which modpack version are you using?
2.0.4.4
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
wanted to set the output on a specific side with a wrench like with others normal gt machines.
#
#### What happend instead? (Attach screenshots if needed)
i need to click on the opposite side to place the output on the side i want:
for exemple let's say i want to move the output to the opposite side:
![weird](https://user-images.githubusercontent.com/12850933/41688667-568e80da-74ed-11e8-8f9c-66fc5a83bda3.png)
if i click with my wrench where there is the green arrow: nothing happen
if i click with my wrench where there is the red arrow: the output is placed where i want

#
#### What do you suggest instead/what changes do you propose?
pls make it consistant with others GT machine behaviors

**Comment by richardhendricks** [comment]
I think we just need to flip the texture PNG file.

Also though, we should make it screwdriver-enabled on all sides, not just the output.

**Comment by boubou19** [comment]
if you flip the texture, does it mean that only the skin will have the correct behavior but not the actual output?

**Comment by richardhendricks** [comment]
Curses! My evil plan is foiled again. :(

**Comment by Dream-Master** [comment]
@richardhendricks need it another fix or is it fixed or need it more tests?

**Comment by richardhendricks** [comment]
Haven't done anything with this yet.

**Comment by repo-alt** [comment]
It is kind of trivial to fix, but the existing buffers will turn around breaking a lot of setups. 
Alternatively I can mask the weirdness, changing only wrench behaviour for this block.

**Comment by Dream-Master** [comment]
this blocks are never change and maybe not very often used. I hope we can add some sorting buttons(or auto sorting) there as well or maybe we need to do it via inventory tweaks?. I ask because if using a buffer some tiny piles not sorted and so are many slots used up with the same tiny pile type.

**Comment by repo-alt** [comment]
Sorting is turned on/off with a soldering iron

**Comment by Dream-Master** [comment]
ah ok good to know. Maybe we can add a gui like we add for covers ?

**Comment by repo-alt** [comment]
All the buffers have different GUIs, and most used one (super buffer), has no GUI at all.

**Comment by boubou19** [comment]
changing how the wrench interacts with the buffers seems to be the good solution. But that just adds a hack on top of the issue just to avoid breaking setups.  I think it's okay if there is a disclamer to change the buffers behavior properly
