### ISSUE TITLE
Suggestion - Void Cover

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#3182]
#### Which modpack version are you using?
2.0.4.4

This is a suggestion/request only:

Is it possible to add a Fluid Void Cover/Item Void Cover for GT storage (mainly) and maybe machines.

Similar to Drawers - the fluid or item void cover will void anything above the maximum storage value.

This will make cleaner storage solutions and also add the ability for single machines to void excess fluids/items when storage is full (similar to how multiblock output hatches currently work).

**Comment by Dream-Master** [comment]
@richardhendricks  @bartimaeusnek  @codewarrior0 @mitchej123 @Technus
need help with it.

**Comment by richardhendricks** [comment]
How would you expect it to operate on machines?  Only void the output side?

**Comment by boubou19** [comment]
i'll say only void the input if the machine already have the maximum amount.

**Comment by tranceplanet** [comment]
On singular machines:  Void Cover on output side = void excess above maximum output (storage) amount

Voiding input would be a bad idea...
