### ISSUE TITLE
Cleanroom

### ISSUE THREAD

**Issue by Viktor-KN** [GTNewHorizons/GT-New-Horizons-Modpack#3188]
#### Which modpack version are you using?
2.0.4.2
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Cleanroom in my opinion should nullify pollution effects on player, but it not.

**Comment by Dream-Master** [comment]
@richardhendricks @bartimaeusnek @codewarrior0 any idea how to realize this ?
