### ISSUE TITLE
Rocket fuel

### ISSUE THREAD

**Issue by Bob558-51** [GTNewHorizons/GT-New-Horizons-Modpack#3190]
I propose to use as fuel for the missiles cetane-boost this diesel.
So it will be more technologically for flights into space

**Comment by Dream-Master** [comment]
yes i wish we can add it. Will ask GC devs for change code.

**Comment by Dream-Master** [comment]
https://github.com/micdoodle8/Galacticraft/issues/3452

**Comment by Zoko061602** [comment]
I thought you wanted to use EnderIO Rocket fuel

**Comment by Dream-Master** [comment]
no gt one but I guess they are the same now.

**Comment by Prometheus0000** [comment]
This already happened.
