### ISSUE TITLE
Stargate core crystals can be obtained ridiculously easily

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#3193]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
was breeding random villagers to make a villager population for delta. Expected to see cheap items in trades.
#
#### What happend instead? (Attach screenshots if needed)
![2018-06-26_12 51 02](https://user-images.githubusercontent.com/12850933/41907103-2d37c6cc-7940-11e8-93fc-e26030832484.png)

#
#### What do you suggest instead/what changes do you propose?
remove this trades or this villager lmao

**Comment by Wolozo7** [comment]
Does obtaining those cores make the recipe of a whole stargate significantly easier though?

**Comment by boubou19** [comment]
you need 64 of this:
![2018-06-26_13 17 31](https://user-images.githubusercontent.com/12850933/41908143-510ca6fa-7943-11e8-93c9-311813c853de.png)
1 seaweed extract is done with 64 tceti-E seaweeds
and silver plasma (so fusion reactor needed) and low gravity to make it at zpm voltage:
![2018-06-26_13 18 35](https://user-images.githubusercontent.com/12850933/41908193-711c77d6-7943-11e8-86af-ca4097583e40.png)
so, yeah this is a bit short cut if you can have some for a few diamonds and emeralds

**Comment by boubou19** [comment]
And i forgot to mention that seaweed is a pain to gather because they are underwater and you need to harvest them from top to bottom. if you do the maths you need a few thousands of them

**Comment by DV666** [comment]
To fix that, i remember you can remove Stargate villager on config file.

**Comment by Dream-Master** [comment]
will do

**Comment by richardhendricks** [comment]
IDK, I kinda like it.

**Comment by DV666** [comment]
Trade from Tokra Villager present on this file (code source from SGCraft java file) => SGCraft/src/mod/gcewing/sg/SGTradeHandler.java

`//      recipes.add(new MerchantRecipe(
//          new ItemStack(Item.emerald, 4),
//          new ItemStack(SGCraft.naquadahIngot, 3),
//          new ItemStack(SGCraft.sgRingBlock, 1, 0)));
//      recipes.add(new MerchantRecipe(
//          new ItemStack(Item.emerald, 4),
//          new ItemStack(Item.enderPearl),
//          new ItemStack(SGCraft.sgRingBlock, 1, 1)));
//      recipes.add(new MerchantRecipe(
//          new ItemStack(Item.emerald, 16),
//          new ItemStack(Item.eyeOfEnder),
//          new ItemStack(SGCraft.sgBaseBlock)));
//      recipes.add(new MerchantRecipe(
//          new ItemStack(Item.emerald, 16),
//          new ItemStack(Block.obsidian, 4),
//          new ItemStack(SGCraft.sgControllerBlock)));
            
        recipes.add(new MerchantRecipe(
            new ItemStack(Items.emerald, 8),
            new ItemStack(Items.diamond, 1),
            new ItemStack(SGCraft.sgCoreCrystal)));

        recipes.add(new MerchantRecipe(
            new ItemStack(Items.emerald, 16),
            new ItemStack(Items.diamond, 1),
            new ItemStack(SGCraft.sgControllerCrystal)));
}`

Maybe just replace theses trades by something else or remove it ? I didn't know if you can edit directly source file or need to create special code to replace it, i leave you that :p

**Comment by Vicus-N** [comment]
@boubou19 seaweed can be easily farmed with fish catchers.

**Comment by bartimaeusnek** [comment]
@Vicus-N T-Ceti-E seaweed.

**Comment by Vicus-N** [comment]
sorry, my bad

**Comment by Dream-Master** [comment]
Oh another fork uuug.

**Comment by Dream-Master** [comment]
fork done

**Comment by richardhendricks** [comment]
We should put in different trades, not just completely delete them.  @boubou19 Do you have some suggestions on what is reasonable?

**Comment by boubou19** [comment]
well based on the recipes i think Dream doesn't want players to spam them so if villagers aren't disabled, then at least replaces emerald and diamonds with eternal singularities and ridiculously large capacitors, or other higly expensive items so that way if you use villagers as a shortcut, you still need to craft a shitton of things first.

**Comment by richardhendricks** [comment]
I am OK with that.

**Comment by 0lafe** [comment]
Considering the cost of the rest of the stuff for stargats, the crystals are laughably cheap. Iirc you need 1 of these for the charm of dislocation, but crafting the rest of it costs 16k infinity, as well as millions upon millions of the materials that go into singularities. 

Villagers probably shouldn't give these out the way they do, but it's like getting a free iron dust, and being asked to make an entire HV macerator.

**Comment by richardhendricks** [comment]
Maybe we make 3 different Tokra villager classes with different trades for each.

http://jabelarminecraft.blogspot.com/p/minecraft-forge-modding-villagers.html
Seems pretty easy.

I also like the idea of maybe using villagers instead of coins quests for GT items.  villager trades though are pretty easy to cheese, would need some time to thing on it.

**Comment by boubou19** [comment]
this is not fixed in latest live version so far i know

**Comment by mitchej123** [comment]
If it's still an issue, feel free to reopen -- going through and cleaning up stuff that looks stale

**Comment by boubou19** [comment]
can't reopen it for some reason

**Comment by TataTawa** [comment]
I breed villagers in overworld and suprisingly got some villagers with yellow hair selling stargate crystal. is it intended?

btw I can also get some Thaumcraft red villagers in overworld i have never seen, selling strange wands (50vis each, bad than thaumwood ones).

**Comment by TataTawa** [comment]
these breeded Thaumcraft red villagers' wand is obtainable even in stone age. it makes a player be able to use HV-thaumcraft content even in stone age.
