### ISSUE TITLE
wrong name in UV batteries crafts

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#3194]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I wanted to craft a large naquadah battery (uv tier)
#
#### What happend instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/12850933/41924155-91bedb84-7969-11e8-8db1-82d363668ccf.png)

![image](https://user-images.githubusercontent.com/12850933/41924232-bcd68650-7969-11e8-8e87-9f08693667af.png)

#
#### What do you suggest instead/what changes do you propose?
rename the "large naquadria battery (empty)" to "large naquadah battery (empty)"

**Comment by boubou19** [comment]
It's the same for the medium naquadah battery also

**Comment by Dream-Master** [comment]
I guess you cant name in twice because when this bat full it called empty too.
