### ISSUE TITLE
Issue using paper as pipe cover

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#3195]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I right clicked a small wooden fluid pipe with a stack of paper, I expected it to add 1 paper as a cover to the pipe.
#
#### What happend instead? (Attach screenshots if needed)
The whole stack of paper got used up and no cover was added to the pipe.
The cover is added properly when only holding 1 paper.
#

**Comment by Dream-Master** [comment]
I didnt know paper can used as cover. @richardhendricks @bartimaeusnek any idea?
