### ISSUE TITLE
Magnum Torch not working

### ISSUE THREAD

**Issue by DeForce** [GTNewHorizons/GT-New-Horizons-Modpack#3204]
#### Which modpack version are you using?
2.0.4.5, 2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
This happens ONLY in multiplayer

#
#### What did you try to do, and what did you expect to happen?
I place magnum torch and mobs do not spawn.

#
#### What happend instead? (Attach screenshots if needed)
I place magnum torch and mobs still spawn 

#
#### What do you suggest instead/what changes do you propose?
This is happening because of AMDIForge mod that was added in 2.0.4.5 version of the modpack.
This mod "controls" spawn of the mobs and it overwrites the magnum torch effect.
https://github.com/GTNewHorizons/AMDIForge/blob/master/src/main/java/eu/usrv/amdiforge/events/LivingCheckSpawnEventHandler.java#L142

What I suggest? Either fix the mod or do not include that in server installations that is not for Delta or Epsilon.

**Comment by Bryfer** [comment]
The magnum torch has been broken a long time
Dupe of #1101 ?

Or was the torch actually fixed and is now broken again?

**Comment by devanchya** [comment]
Just confirmed on DigtoBuild.com that removing the AMDIForge mod, the Repulsors and Magna Torches work again.
This is the only change we made between "report of issue" and "resolution of issue" on our server.

**Comment by Dream-Master** [comment]
@Namikon any idea ?

**Comment by DeForce** [comment]
@Dream-Master I have created the pull request that fixes this issue, just merge it and it will start working...

**Comment by DoomSquirter** [comment]
late to game, but forge server, no plugins, can confirm chandeliers definately don't seem to be working, using 4.6 but they definately did work in 2.7 which is what we upgraded from.

**Comment by DoomSquirter** [comment]
also, what is the AMDIForge mod for?  It's purpose in the pack?

**Comment by DeForce** [comment]
#3205 I did question it myself, you can check it there.

**Comment by KaneHart** [comment]
@Dream-Master If this the case why this being added still?

**Comment by Dream-Master** [comment]
AMDI Forge can control the mob spawn so far i understand it. If you dont want it not add it. Its a server mod. @KaneHart

**Comment by draknyte1** [comment]
I still don't see why this mod that exists specifically for the official servers, is bundled with everyone's package.. it's server side only and it breaks shit, definitely no use for the other 99% of servers.

**Comment by Prometheus0000** [comment]
Was this ever fixed?

**Comment by boubou19** [comment]
it depends: is amdi forge still provided in the server pack?

**Comment by yukieiji** [comment]
It shouldn't have worked on some of the Thermos servers...

**Comment by Savallator** [comment]
This was fixed (in 2.1.1.2 the mod was included as disabled .jars file), then it reappeared. In 2.1.1.4QF2 it is currently broken.
