### ISSUE TITLE
EMT circuits bug

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/GT-New-Horizons-Modpack#3212]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
No Matter
#
#### What did you try to do, and what did you expect to happen?
EMT recipes have only mainframes in crafts
![unknown](https://user-images.githubusercontent.com/37113583/42091830-80c857c2-7baf-11e8-8832-89afb783803c.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek is the recipe codewise or minetweaker?

**Comment by Dream-Master** [comment]
ok mt recipes can't be ordicted in Thaumcraft need a codewise solution @barsikus007 @bartimaeusnek

**Comment by bartimaeusnek** [comment]
@Dream-Master ill pull the MT Recipes to code

**Comment by Dream-Master** [comment]
ok

**Comment by bartimaeusnek** [comment]
as a reminder for me:
use propper Metadata for IC2 components

**Comment by Prometheus0000** [comment]
They're auto oredicted, it just doesn't show in the recipe in nei.
