### ISSUE TITLE
Lapotron autocrafting stopped working in 2.0.4.5

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#3223]
#### Which modpack version are you using?
2.0.4.5
#
#### If in multiplayer; On which server does this happen? 
both server and SSP
#
#### What did you try to do, and what did you expect to happen?
Autocraft lapotron from "Raw Lapotron Crystal" and 2 "Nanoprocessor"
#
#### What happend instead? (Attach screenshots if needed)
AE order is just stuck
![image](https://user-images.githubusercontent.com/23512002/42119302-112a4be6-7c13-11e8-9911-5db79b018c2c.png)
To test the issue further I put the assembler in the test world
placed a conveyor on  top
set to import
put a chest above
placed ingredients in the chest
- as a result - only raw crystal was pulled in the assembler
![image](https://user-images.githubusercontent.com/23512002/42119350-53d946d6-7c13-11e8-8d2d-25a15500352f.png)
![image](https://user-images.githubusercontent.com/23512002/42119353-5c92e3fe-7c13-11e8-82db-5fc1aea00922.png)

**Comment by repo-alt** [comment]
IC2 Advanced Circuit does work in autocrafting.
Maybe related fact: when I look up Nanoprocessor recipe in NEI, in the first pages I see Advanced Circuit

**Comment by Dream-Master** [comment]
Maybe i need to add a copy past circuit into gt that can be made out of ic2 circuits to solve this probelm.

**Comment by repo-alt** [comment]
This issue is still actual: with circuit downgrade disabled https://github.com/GTNewHorizons/NewHorizons/issues/3289 I  (and anybody who wants to autocraft lapotrons) have to support outdated IC2 advanced circuits, which means supporting previous tiers of the said circuit along with their components. Needless to say that lapotron autocrafting is quite essential in late game.

**Comment by Dream-Master** [comment]
we can disable ic2 circuits? but will this fix the problen? And i am not aure if i can disable circuits so good that they not exist ingame anymore.

**Comment by DoomSquirter** [comment]
please do not $#%&ing disable the ic2 circuits.  find another way pls

**Comment by repo-alt** [comment]
As I understand, the idea is not to just throw them out, but to, kind of, transfer them to GT. This may still break things, but may also solve all the incompatibilities with these circuits.

**Comment by DoomSquirter** [comment]
I really don't care about the how.  but it has to be transparent.  I'm looking squarely at the bee conversion and how everything had to be thrown on the ground, etc.  

if they have the same recipe but create different circuits but the old circuits can live on in same world as the new ones, that's dandy.  ppl can use up what they have and nobody's affected.  

but just keep this in the back of the mind that this is a huge change and will affect more the ppl below IV than the ones above.

**Comment by draknyte1** [comment]
Too many things rely on the two IC2 circuits, I vote against touching them at all.

**Comment by repo-alt** [comment]
Perhaps you can suggest how to fix lapotron autocrafting @draknyte1 since you are here?

**Comment by draknyte1** [comment]
Remove existing lapotron recipe, add recipes with explicit circuits required.. my suggestion

**Comment by Dream-Master** [comment]
aren't they oredicted?
