### ISSUE TITLE
Tinkers Construct modifiers

### ISSUE THREAD

**Issue by Karl-Markkus** [GTNewHorizons/GT-New-Horizons-Modpack#3227]
#### Which modpack version are you using?
2.0.4.7
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I was fighting mobs with my rapier, which had necrotic on it, but once it broke, I excpected it to not steal life anymore.
#
#### What happend instead? (Attach screenshots if needed)
Instead, the broken rapier still stole life, even when not doing any damage, as it was broken.
#
#### What do you suggest instead/what changes do you propose?
This is a cheaty bug which can increase a players survivability a bunch, if one figures out this bug, though one should have 2 weapons to actually use the broken one to steal life, and the other weapon to kill mobs. But it is highly improbable that it would not happen to everyone, but I just happened to find it out a day ago.

**Comment by Dream-Master** [comment]
mh not sure if this is a real bad bug? @Karl-Markkus 
@bartimaeusnek any idea ?
