### ISSUE TITLE
Hunger overhaul overhaul

### ISSUE THREAD

**Issue by Waisse** [GTNewHorizons/GT-New-Horizons-Modpack#3239]
#### Which modpack version are you using?

#2.0.4.6
 
I think a review of all config option of Hunger Overhaul is needed. This mod conflict too much with other mods mechanics, namely Witchery vampirism and lycanthropy.

I'm not ranting about the hunger/farming nerf, but rather the health part. With HO, health regen lower, and even lower when your health is low, and EVEN LOWER if your max health is higher. You also get weakness/slowness effect when your health get very low. This in itself make combat frustrating as you can't defend yourself at all when you get injured too much. You get a bit injured, you get bad debuff, the enemy get the upper hand, and you get even worse debuff, ensuring your death. Low health debuff also only affect players, making combat against infernals or regular mobs even more unfair.

Now to the conflict part.
Werewolves have increased max health when they transform, but they keep their current health when they do. Then HO low health mechanic trigger because it's % based : 20/60hp is considered injured by the mod so you get debuffed. That make playing werewolf unfun because transforming give you instant low health debuff for a very long time until you naturally regen to a healthy state. Werewolves are supposed to transform only when they are fighting, they can't hold any items in wolf form, so HO make playing werewolf incredibly frustrating and not worth at all.

Vampires also have an issue with HO. Vampire have immortality, that means they can't be brought below 1hp with standards attacks. But with HO, 1hp vampires get extremely high debuff that make them unable to defend themselves and ultimately make vampirism not worth at all too.

My suggestions ? Entirely remove low health debuff. It's % based, make vampire immortality useless and werewolves sitting ducks until they regen enough to be considered healthy by the mod.
I'd also review how fast health regen, currently it's way too slow because of the following config options : 

    # The lower your health the longer it takes to regen [vanilla: false] [default: true]
    B:modifyRegenRateOnLowHealth=true

This setting make high max health players like werewolves even more useless since they have to wait forever to regen EVERYTIME they switch into wolf form.

Thanks for reading, I hope you understand my concerns about HO and Witchery interaction.

**Comment by Dream-Master** [comment]
Will check

**Comment by mitchej123** [comment]
If you find the source for the current version we're running, we can also modify it to play nicely with vampirism/lyncanthropy.

**Comment by Dream-Master** [comment]
@mitchej123 sure if you can tae care why not. Would be great.

**Comment by Dream-Master** [comment]
Waiting for license
https://github.com/progwml6/HungerOverhaul/issues/197

**Comment by beta-phenylethylamine** [comment]
Couldn't you unregister the HungerOverhaulEventHook, override onLivingUpdate, and basically cause it to short-circuit if the EntityLiving is both a player and a vampire or a werewolf, then call the super function?
