### ISSUE TITLE
Igniter + rainforest wood logs  Bag

### ISSUE THREAD

**Issue by Vernam** [GTNewHorizons/GT-New-Horizons-Modpack#3247]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
own
#
#### What did you try to do, and what did you expect to happen?
i'm try filled charcoal pile igniter with the rainforest wood logs from gt++
#
#### What happend instead? (Attach screenshots if needed)
charcoal pile igniter doesn's work
#
#### What do you suggest instead/what changes do you propose?
After testing, it was revealed that the logs should have one general arrangement (horizontal or vertical). ordinary oak logs work at any arrangement (interspersed horizontally and vertically). 
This tree is very useful, so I do not understand why it is so important for charcoal pile igniter..

**Comment by Dream-Master** [comment]
Works for me horizontal and vertical:

![image](https://user-images.githubusercontent.com/2970688/42260962-bc8a7208-7f66-11e8-8e60-782e0c2a56da.png)
![image](https://user-images.githubusercontent.com/2970688/42260968-c1cc4a0c-7f66-11e8-84f4-b6fbc14f6e61.png)
![image](https://user-images.githubusercontent.com/2970688/42260976-ccd4b83a-7f66-11e8-9308-369d27d002cd.png)
![image](https://user-images.githubusercontent.com/2970688/42260992-dc38ea58-7f66-11e8-81bb-71e8b3f838c3.png)
![image](https://user-images.githubusercontent.com/2970688/42261005-e2f0578c-7f66-11e8-950e-563f7e7d5366.png)
![image](https://user-images.githubusercontent.com/2970688/42261021-eeebfc08-7f66-11e8-9918-c4896317d79f.png)
![image](https://user-images.githubusercontent.com/2970688/42261032-fc39700c-7f66-11e8-91cd-ee859ec2df5c.png)

**Comment by Vernam** [comment]
U don't test bigger sizes... this is a problem

**Comment by Dream-Master** [comment]
I can test bigger size

**Comment by Vernam** [comment]
U will see the problem... if not, a little bit later i will post some screens

**Comment by Dream-Master** [comment]
ok which size you are using ? @Vernam

**Comment by Vernam** [comment]
maximum. But a bug appears when more than 1 log

**Comment by Vernam** [comment]
will work
![screenshot_7](https://user-images.githubusercontent.com/39298269/42268657-c0d70772-7f84-11e8-928d-1b63149cafbf.png)

will not work
![screenshot_9](https://user-images.githubusercontent.com/39298269/42268671-c8bdd4e8-7f84-11e8-8b92-75725399cadc.png)

**Comment by Dream-Master** [comment]
@Vernam please report issue on GT++ side 
https://github.com/draknyte1/GTplusplus/issues 

any idea on this issue @draknyte1 ?

**Comment by draknyte1** [comment]
It's not an issue in my side from previous testing. They do work, ask @codewarrior0

**Comment by Dream-Master** [comment]
I will run a few testes later when i be back from work.

**Comment by Dream-Master** [comment]
@draknyte1 @codewarrior0 it not work. Try 3x3 logs with mixed oriantation. Any idea?

**Comment by draknyte1** [comment]
No idea, when someone can raise an issue on the GT++ GitHub, I'll look into it further.

**Comment by Dream-Master** [comment]
@Vernam can you make an issue on gt++ side. thanks
