### ISSUE TITLE
Witchery++ baba yaga spawn rate 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#3249]
#### Which modpack version are you using?
2.0.4.6
#
#### What do you suggest instead/what changes do you propose?
Change the spawn rate of the bags yaga using the crystal ball. The times I tried, I must have put 8-9 hours into the dumb fortunes and got the spawn once. It's just dumb, it's not interesting to do the fortunes once. Let alone hundreds of times. Please

**Comment by Dream-Master** [comment]
If there is a config I could change it.

**Comment by Dream-Master** [comment]
There is no config for it @0lafe

**Comment by draknyte1** [comment]
I can look into changing the rates.
Post the suggestion here: https://github.com/draknyte1/WitcheryExtras/issues

**Comment by draknyte1** [comment]
Implemented in https://github.com/alkcorp/WitcheryExtras/commit/c0f4ba306c8f90c566c16025e2d92fd560b09c68.
