### ISSUE TITLE
Galacticraft tooltips wrong key

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#3254]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
View more info on galacticraft items.
Items with more info say press semicolon for more info (my sneak key)
![image](https://user-images.githubusercontent.com/17787093/42285509-bfc0457e-7fa7-11e8-8f4c-bbb563c50ed3.png)
#
#### What happend instead? (Attach screenshots if needed)
Semicolon doesn't work, shift is still the key needed to view the extra info.
#
#### What do you suggest instead/what changes do you propose?
Either change the tooltips to permanently say "Press LSHIFT for more info" or change it to use the sneak key to view more info.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/42409618-33e816fc-81dd-11e8-9a76-a8e1c695703d.png)
works for me in sp.
![image](https://user-images.githubusercontent.com/2970688/42409622-3e050078-81dd-11e8-9ac7-58d0af7b5542.png)

**Comment by Dream-Master** [comment]
If the sneak key is change it show the wrong key. @richardhendricks are we able to fix it code wise in GC code ?
