### ISSUE TITLE
Applied Energistics cant request items to get crafted

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#3255]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I tried to order one HV Machin Hull in my me system. I expected that it will craft me the machin hull and it will show up in the system.
#
#### What happend instead? (Attach screenshots if needed)
I cant even order the item to be crafted ( nnot a singel one at all ). When i click on an item to craft it, normally a dialog field should show up where you can select how many you want to craft, but i dont even get this dialog field, it kicks me instand out of the terminal.
#
#### What do you suggest instead/what changes do you propose?
Does anyone else encounters that bug / any ideas how to fix it

**Comment by boubou19** [comment]
maybe a lag issue. try to reboot your AE to see if it's fixed because on the official server Delta i'm not encoutering this issue

**Comment by alphaNOVAircraft** [comment]
i shut down my me serveral times, has enough energy and no channel problems

**Comment by alphaNOVAircraft** [comment]
in my case its not a hotbar slot, im not allowed to have an item in the second row the 6th slot
