### ISSUE TITLE
Bowl's in lunch-bag/lunchbox cause crashes.

### ISSUE THREAD

**Issue by illogicalproductions** [GTNewHorizons/GT-New-Horizons-Modpack#3263]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Private Multiplayer Server
#
#### What did you try to do, and what did you expect to happen?
I knowingly placed a mushroom stew (Natura) into my lunch-bag, knowing when i ate from my lunch bag, the bowl would remain in the lunch-bag and cause a unexpected error.
#
#### What happend instead? (Attach screenshots if needed)
Exactly what I thought would happen, a crash.
#
#### What do you suggest instead/what changes do you propose?
Disabling or modifying foods that return bowls from being craft-able, or placed in the lunch-bag/lunchbox.

**Comment by Dream-Master** [comment]
the berries in the bowl works fine. Never tried mushroom stew. And btw potato on a stick works also it gives it back to inventory. Are you inventory full? @illogicalproductions

**Comment by Dream-Master** [comment]
It did crash only if all slota re occupied. If there is a free solt it not crash. Not sure what i can do here.

**Comment by Dream-Master** [comment]
I test it in sp.
Oh and i see you @illogicalproductions use a empty bag too with only one slot occupies with the stew. Very strange. Maybe a multiplayer bug.

**Comment by valeriouslis** [comment]
i have crash in single playet without any multiplayer...

**Comment by Dream-Master** [comment]
Ok.
Not sure if we can fix it code wise?
Spice of Life is open source.
@mitchej123 @richardhendricks @bartimaeusnek @codewarrior0 @Zoko061602 @Technus 
any idea how or if we can fix it?

**Comment by valeriouslis** [comment]
i cant fix code, may be author fix it

**Comment by Dream-Master** [comment]
1.7.10 is not longer developed i guess.

**Comment by mitchej123** [comment]
Can you provide a stack trace/error log?

**Comment by Dream-Master** [comment]
@illogicalproductions

**Comment by grompe** [comment]
Alternatively, (and what I've been using), modified
`SpiceOfLife-mc1.7.10-1.3.11.jar:\squeek\spiceoflife\foodtracker\FoodModifier.class`
file.

After this change the player just eats the bowl infinitely to no effect, much better than a random crash.
