### ISSUE TITLE
RemoteIO - Remote Accessor crashes client linking to non-vanilla chest

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#3281]
#### Which modpack version are you using?
2.0.4.6

#
#### If in multiplayer; On which server does this happen? 
Epsilon

#
#### What did you try to do, and what did you expect to happen?
Linking RemoteIO Remote Accessor to vanilla chest appears to work fine at any range.

However, linking to any non-vanilla chest works only when close (tested with steel/obsidian/compressed chest), but as soon as you move away from your base and use the Remote Accessor, it crashes the client.

#
#### What do you suggest instead/what changes do you propose?
I know it's an old mod that's not updated and I'm not really expecting a fix here.  A fix would be great!  Weird that vanilla chests work but compressed doesn't...

Is it possible to add a recipe to dismantle the Remote Accessor (Pulveriser or something?); mainly want the Remote Interface Block and Location Chip back as these are very expensive (needs a lot of EV/IV circuits).

Is it possible to add this to the GT Disassembling Machine?

Another minor issue with the Remote Accessor: you have to look at any old block to open the linked chest.  Looking in the air does nothing.

**Comment by Highbeam** [comment]
Adding to this issue.  Linking the item in chat crashes other players.

When this item goes into a storage (advanced filing cabinet) it also crashes the player trying to look in to the storage directly or through an ender inventory panel.

I recommend this item be completely disabled.  It is useless.

**Comment by Dream-Master** [comment]
@Highbeam 
a crash log would be nice. And a log file.

**Comment by Bryfer** [comment]
Here is my crashlog
I crashed when looking at the item from the link in chat.
[crash-2018-07-11_17.29.07-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2185201/crash-2018-07-11_17.29.07-client.txt)
[techniclauncher_2018-07-11.log](https://github.com/GTNewHorizons/NewHorizons/files/2185212/techniclauncher_2018-07-11.log)

**Comment by Highbeam** [comment]
crash report hovering over item in chat:
[crash-2018-07-11_17.42.44-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2185266/crash-2018-07-11_17.42.44-client.txt)

crash report trying to access a remote chest:
[crash-2018-07-11_17.54.50-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2185255/crash-2018-07-11_17.54.50-client.txt)
[techniclauncher_2018-07-11.log](https://github.com/GTNewHorizons/NewHorizons/files/2185263/techniclauncher_2018-07-11.log)
