### ISSUE TITLE
[Balance] Energy Sub Station Redox cells

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#3287]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I made the energy sub station. I looked up the recipes for the Redox cells that determin the capacity of the Sub Station. I expected that they have a decent price, due to the fact that the EV one ( just some tantal, nothing else expensive) has already the quadruple energy storage per block like a Lapatronic Energy orb, that is compared to the redox cells, extrem expensive. Also upgrading the Redox cells just costs a few plates of a higher tier material and some gas (e.g. Oxygen, but the late ons also more compley like argon or radon. but still extrem cheap)

For Comparison. We are currently in IV and set up a Sub Station with a capacity of over 86 Billion EU, using the LuV Redox cells. The controller has a decent price considered that you shall be able to build it when you reach EV. If we would like to have the same energy storage we would need aroun 860!!!! Lapatronic energy orbs. And they dont just cost some plates and chap gases. 
#

#### What do you suggest instead/what changes do you propose?
I would definitly nerf the Redox Cells, im fine with the Sub Station controller, this one has a decent price.

For a small adjustment it would already help to make the upgrading of the redox cells const dens plates and not only a singel one. We could consider adding some more tier specific item to the uupgrade recipe. 
If im informed correctly the moder Redox energy storages use fluids for the energy storge, so i would suggest adding a pump of the tier you are upgrading the Redox cell

E.g. Recipe of the IV Redox Cell: Redox Cell EV, 4 stainless steel plates, 2000 mb Nitrogen
My Suggestion: Redox Cell EV, 4 Dense Tungstensteel plates, 1 electric pump IV,  4 small Niobium Titanium Fluid Pipes, 1152 mb Molten Platinum.

This should make it still more then worth upgrading the cells, but to get 300 Million EU storage for 4 stainless plates and 2 B nitrogen seems a bit to easy.

**Comment by Dream-Master** [comment]
@alphaNOVAircraft Gt++ issue i guess so please popst it on Alkalus side also.

**Comment by Dream-Master** [comment]
https://github.com/draknyte1/GTplusplus/issues

**Comment by alphaNOVAircraft** [comment]
Will post it on his git too, just wanted to mention it here too

**Comment by Dream-Master** [comment]
sure

**Comment by alphaNOVAircraft** [comment]
Issue is still the same, but there are plenty of newer issues that address it
