### ISSUE TITLE
Bees should be unnerfed.

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/GT-New-Horizons-Modpack#3302]
Recently (well I haven't really been active at the time) bees have been nerfed. Because of the nerf many bees are near useless and pointless. Because there are many bees, I want this issue to be a general issue for what should be done instead and change/remove/buff/nerf certain bees/recipes.

My proposals for now is to lower the process times of almost all of the combs to 128 ticks (default time to process) and change the voltage for processing if needed. 

Another is to remove all the "Space Stone" Combs and instead add multiple outputs to the bees to only make dusts and make it have 2-4 Main outputs with 50% chance and if wanted also have multiple Special Outputs.

We also don't need Infinity Bees because that's a joke :P.

**Comment by Dream-Master** [comment]
Not unerfed but improfed. Will do bees into gt code soon.

**Comment by mitchej123** [comment]
+1
