### ISSUE TITLE
adding some form of routing like type filter for siftable purified ores

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/GT-New-Horizons-Modpack#3303]
#### Which modpack version are you using?
2.7
#
#### If in multiplayer; On which server does this happen? 
n/a
#
#### What did you try to do, and what did you expect to happen?
n/a
#
#### What happend instead? (Attach screenshots if needed)
n/a
#
#### What do you suggest instead/what changes do you propose?
so, since I first used gregtech, whenever you make an ore processing line, and you find the type filter for the first time, it's a glorious thing that handles all of your routing for ores you haven't picked up yet, etc (i.e. future proof)

but there's one thing it doesn't do.  There's no way to associate what purified ores coming off your line can be sent to a sifter to process for gems.

Not a bug, but programmatic addition

while talking in discord, came up with some alternatives but no idea what is best way to implement.
1) ability to add an oredict entry manually to all the siftable purifieds and have type filter pick that up without mucking up other things.  don't even know if type filter will do this

2) add an oredict entry and not have type filter catch it.  can then I guess use some other form of oredict checking to deal with the rest.

3) if you were to put a bunch of sifters ahead of another chest, the sifters will only let siftable items into them.  obviously this method runs the risk of not working depending on how much stuff is in process, but the idea could be used to implement something else.

a cover could be made that acts as a camoflauge of another block like a sifter.  takes the properties of said item as far as what it allows/can process but translates that into "whatever cable or chest I'm attached only allows these items, as if it was a 'block X'"

was told to throw this up as an issue to get discussion or ideas

**Comment by alphaNOVAircraft** [comment]
I used the ender io existing item filter, so you make one sample chest with all the purified ores in it and just give that conduit a higher priority, so you will sort out everything you told your existing item filter to filter out. works perfectly fine for me so far

**Comment by DoomSquirter** [comment]
I should have mentioned that.

ofc I have a way around it and that's actually the way I use as well.  one chest to hold the samples to set the filters to.  this does however mean that you have to know that something you're throwing into your oreproc line is going to be a siftable item and stop things from processing past the orewash to enable you to catch each of those things that are going to end up being sifted.  doing this continually is really the problem I have.

in ssp I will cheat a single ore and let them run through the line, create my filter in one shot based on the list of siftables I get from nei and call it a day and that works great.  playing legit tho is a completely different matter.

another option is to use a drawer controller and a bunch of drawers, but same drawback, just changes the filter medium.

**Comment by WarlordWossman** [comment]
I like the idea of a type-filter for siftable ores, would def make it easier for newer players that don't know all recipes in there.

**Comment by Prewf** [comment]
>There's no way to associate what purified ores coming off your line can be sent to a sifter to process for gems.

Just curious, what's your method of determining which purified ores should be macerated/thermal centrifuged? Is it a similar method as sending it to the sifter (existing item filter on another sample chest)?

**Comment by DoomSquirter** [comment]
iirc I just thermal everything if it doesn't goto sifter. the idea is that the sifter is a different beast.  there is a large amt of things that benefit going that way and they get mostly wasted if they don't, whereas the same cannot be said about alternative methods for individual items once that pass has been made.

Basically, Ive setup some intercept rules very similar like but alot less complicated and alot less amt of items to deal with.
