### ISSUE TITLE
Charcoal Blocks useable as fuel in Adv. Coal Coke Oven

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/GT-New-Horizons-Modpack#3320]
#### Which modpack version are you using?
.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Tried putting compressed charcoal blocks into an advanced coal coke oven (the one that needs infernal bricks). I expected compressed charcoal blocks to be a valid fuel source
#
#### What happend instead? (Attach screenshots if needed)
Charcoal blocks apparently are not a valid fuel source, despite getting ten of them as a reward for completing the quest and also since regular charcoal is a valid fuel source
#
#### What do you suggest instead/what changes do you propose?
I would suggest adding it as a fuel source for the advanced coke oven

**Comment by MineAnPlay** [comment]
The reason is because it's just a renamed Blast Furnace. Not sure if it can be added with a config or a script. Should be possible with code though.
