### ISSUE TITLE
Cells emptying even if Liquid Fueled Boiler is full.

### ISSUE THREAD

**Issue by Ormusn2o** [GTNewHorizons/GT-New-Horizons-Modpack#3326]
#### Which modpack version are you using?

2.0.4.6
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

Put in fuel cell into LFB. I expected it to fill in as much fuel as possible then topping off as the fuel is used.

#
#### What happend instead? (Attach screenshots if needed)

What happened in this video. Mute the audio because i forgot to mute my mic.
https://streamable.com/mbnax

#
#### What do you suggest instead/what changes do you propose?

I have confirmed the fuel is being wasted with gregtech cells and industrial craft cells. I also confirmed that fuel is not being wasted if you are feeding it directly into the firebox with pipes. Seems to be problems with cells instead. Im almost sure this is a new problem and in earlier versions of the pack that did not happened. This seems to be problem with railcraft. 

I recommend disabling the ability to put cells into the boiler until this is fixed.

**Comment by alphaNOVAircraft** [comment]
Its not a bug, that behavior occures at many cases, like right licking a bc tank thats only missing 1mb still will empty the cell, in the moment a small amount of liquid is missing (just 1 mb is enough) it will fill it and delete the rest of the fluid in the cell

**Comment by Ormusn2o** [comment]
As you can see in the video, the internal tank is not missing any fluid. Its 16,000/16,000

**Comment by alphaNOVAircraft** [comment]
> As you can see in the video, the internal tank is not missing any fluid. Its 16,000/16,000

is is instandly refilled by the cells, thats why they are emptying, all the time a cell moves fro the top to the bottom slot one mb of the creosote got burned, the cells replace just 1mb in the internal tank of the boiler, rest of it (999mb) get voided

**Comment by boubou19** [comment]
this is a weird behavior. it should only be able to empty when there is enough space for 1 cell

**Comment by Ormusn2o** [comment]
@alphaNOVAircraft Nope, the boiler uses up one bucket at a time.

**Comment by Dream-Master** [comment]
@Ormusn2o why using cells? Input it via pipes (GT)

**Comment by Ormusn2o** [comment]
@Dream-Master yeah i did it, i just had creosote cells on hand. The only reason why i posted this bug is because fuel is wasted and a lot of people play on servers and can't cheat items back.

**Comment by Dream-Master** [comment]
rc tank have same issue
