### ISSUE TITLE
GT Brewing Liquid and Thaumcraft

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/GT-New-Horizons-Modpack#3328]
#### Which modpack version are you using?
2.0.4.6
#
#### What did you try to do, and what did you expect to happen?
I tryied to brew Instant Health Poitions using GT und break them down using Automagy Alchemical Boiler.
#
#### What happend instead? (Attach screenshots if needed)
Alchemical Boiler cant break down this liquid.
#
#### What do you suggest instead/what changes do you propose?
If possible adding the aspekts to the liquid so the Boilert can break it down might be nessecary for all Potions.

**Comment by Dream-Master** [comment]
@PapaTim68 Did they have aspects or they empty?
I can add it via Minetweaker.

**Comment by PapaTim68** [comment]
The potions in bottles do have aspects but not the liquid it seems I also noticed they don't fit in to g++ luv Tanks
