### ISSUE TITLE
ME Import Export Autocrafting

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/GT-New-Horizons-Modpack#3329]
#### Which modpack version are you using?
2.0.4.6
#
#### What did you try to do, and what did you expect to happen?
Adding ME Import/Export Busses to auto crafting.
#
#### What happend instead? (Attach screenshots if needed)
Noticed their are no Assembler recepies for them.
#
#### What do you suggest instead/what changes do you propose?
Adding recepies like they are their for pumps, convayers , robo arms and so on

**Comment by lexx1191** [comment]
use molecular assembler?
