### ISSUE TITLE
Talisman of remediation doesn't remove flux flu (possibly others)

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/GT-New-Horizons-Modpack#3343]
#### Which modpack version are you using?
4.6
#
#### If in multiplayer; On which server does this happen? 
private, smp
#
#### What did you try to do, and what did you expect to happen?
talisman of remediation did not remove flux flu
#
#### What happend instead? (Attach screenshots if needed)
talisman of remediation is supposed to remove flux flu.  it's one of the intended purposes of it and I was told it was changed code wise so it does not?  
#
#### What do you suggest instead/what changes do you propose?
the talisman is an item you make to specifically help with a bunch of warp related affects.  yes it also removes all negative potion effects, but every time I've made it it's to deal with the normal warp events.

are there any other surprises that were changed about it?

Considering that you've got this other mod that adds these permanent warp events already, nerfing this really seems a tad bit severe.  Please restore it to it's intended usefulness.

**Comment by Dream-Master** [comment]
For reduce warp you need the amulet from warp theory.

**Comment by DoomSquirter** [comment]
Let me be clear.  flux flu is from vanilla thaumcraft, not warp theory.  

the amulet you mention requires the tear itself iirc, which, if that's the case, comes way more towards the end of your warp adventures not the begining or middle.  by the time you have the tear, you don't have to worry about warp anymore.  I'm trying to figure out if you don't quite understand my concern or being flippant about it...  :P 

Secondly, text of the book states for the talisman of remediation "....  this talisman will dispel most harmful effects on the holder and keep them on itself, taking damage.  it will remove some effects stemming from warp, at an extreme durability cost."

you guys changed a core mechanic of a item from a mod from what I gather.  I just don't understand why considering how badly you're punishing ppl with warp theory in addition to that.    It seems extra punitive with the only recourse is to deal with the issue.

note: you would have been better served stating that the bath soaps, etc are what you would use to reduce some of those warp events (again, vanilla warp events).  but doing so while you're 1000m away from your base or in another dimension sorta precludes that.

Lastly, since you mentioned warp theory, there are a couple warp theory warp events that the talisman does remove and nullify.  So again, not sure why this modification was made.  Bart told me to look at the code but I'd have no clue where to look or what to look for to see who made the changes and why.  

Even if you don't feel it needs changing, I'd still like it clarified what you guys changed from the core behavior so at least ppl can know what to expect.
