### ISSUE TITLE
GT++ Experience Converter (2 issues) animation is laggy / recipe doesn't show

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#3352]
#### Which modpack version are you using?
2.0.4.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Issue #1 The animation of this block lags my client when it's placed.  I suggest disabling the animation.  (Will raise this on GT++)
Issue #2 In NEI: when you left click Experience Converter it doesn't show a recipe.  However, if you right click 'Bottle of Enchanting' you can see the recipe for Experience Converter and make it.

On a side note:  I have no idea if mob essence if needed yet since there's no MFR, I just thought it would be cool to get :)

**Comment by Dream-Master** [comment]
@Highbeam can you make a issue on gt++ side too ?
https://github.com/draknyte1/GTplusplus/issues
Thanks

**Comment by draknyte1** [comment]
It's been removed since then.

**Comment by draknyte1** [comment]
Fixed in Dev.
