### ISSUE TITLE
unknown liquid on barnada C deletes infinity ingots

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#3353]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i wanted to show to bartimaeusnek that infinity ingot is undestructible when looted in the world
so bartimaeusnek asked me to loot it in the unknown liquid on barnarda C. I expected the ingot to sink in the liquid
#
#### What happend instead? (Attach screenshots if needed)
it disappeared lol
#
#### What do you suggest instead/what changes do you propose?
i just post it here to let know that dropping an infinity ingot in this dim is dangerous

**Comment by alphaNOVAircraft** [comment]
Basic stuff bozz, who not accidential drops some infinity ingots xD but still a weird bug

**Comment by 0lafe** [comment]
I think this is the first time the idea of dropping an infinity ingot crossed my mind
