### ISSUE TITLE
troubles powering quarry

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#3354]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to boost the ender quarry with 3 speed III upgrades with energy provided by a UV batterie.
I expected the quarry to mine fast.
#
#### What happend instead? (Attach screenshots if needed)
The quarry start and stop very frenquently so it's quickier to use only one speed III upgrade
#
#### What do you suggest instead/what changes do you propose?
Apparently the quarry isn't able to retrieve energy quickly from the UV cable, as if it has a rf limitation in input. So please unlimit the rf you can input in the quarry or unblacklist the quarry from the World Accelerator

**Comment by Anarack** [comment]
There was a issue with configs for the transceivers transfer limit, I believe dream fixed that in the current dev branch.

**Comment by boubou19** [comment]
i don't use the transceivers to power the quarry i use UV amp with a gt cable to convert rf to eu so dunno if it's related

**Comment by boubou19** [comment]
thing is i will not bother if i can put only one speed III upgrade and use a world accelerator on it because with my UV one i'll speed it enough for my needs but i can uderstand that is kind of too OP. From my tests on Delta i don't reach 6 blocks per ticks with 3 speed III upgrades sadly.

**Comment by MineAnPlay** [comment]
The problem isn't it being OP but more so that it brings the server to it's knees.

**Comment by Dream-Master** [comment]
@MineAnPlay @boubou19 @Anarack is this happend because the tps is low or the same in SP Game?
What we can do here and i wont enable Quarry on Accelerators.
