### ISSUE TITLE
Effect: Water

### ISSUE THREAD

**Issue by Hakameda** [GTNewHorizons/GT-New-Horizons-Modpack#3359]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
GTNH: Roller Derby
#
#### What did you try to do, and what did you expect to happen?
Ocean bees and river bees have effect: water which should fill nearby water accepting things
#
#### What happend instead? (Attach screenshots if needed)
Nothing, doesn't work
#
#### What do you suggest instead/what changes do you propose?
Make it work, maybe a bucket every few seconds, could be an alternative water source

**Comment by damug** [comment]
Some quick research indicates the water effect may only work on buildcraft pipes and tanks. See https://www.reddit.com/r/feedthebeast/comments/28779o/bee_water_effect_any_affect/#ampf=undefined

**Comment by Hakameda** [comment]
Tried that, I too can use google. Doesn't work. Tried GT Machines, BC Tanks, Waterproof Pipes, GT Tanks, GT++ Tanks, GT Pipes. The only other post that mentioned it use to work at such a poor pace it wasn't worth it

On Wed, 25 Jul 2018 at 17:52, damug <notifications@github.com<mailto:notifications@github.com>> wrote:

Some quick research indicates the water effect may only work on buildcraft pipes and tanks. See https://www.reddit.com/r/feedthebeast/comments/28779o/bee_water_effect_any_affect/#ampf=undefined

**Comment by MineAnPlay** [comment]
No, it works. It filled my damn oil pipes and was confused why they were filling up, then I realised my water bees are just above my oil pipes underground. It's not much water though.

**Comment by draknyte1** [comment]
I like that you think GT & GT++ tanks are different things, They're 100% identical besides capacity.

**Comment by MineAnPlay** [comment]
So I did some testing, the Water effect "does" work BUT it's stupidly slow. Most likely it picks a random spot in it's territory every so often and if it fails it just resets. Every time it's successful at finding a valid tank it will spawn 100L of Water. Problem is it's so SLOW. I ran a test with around 50 tanks all around the apiary which was world accelerated with a UV accelerator and it only generated a total of about 3-4 buckets worth of water in around 20-30 mins. Also something else I saw was that it preferred certain positions over others so, it's either a pattern or just using a pseudo-random generator. It will work with anything using the IFuildHandler though so GT tanks, RC Tanks, BC tanks, Iron Tanks, GT Pipes will all work.

**Comment by Hakameda** [comment]
Hmm, So perhaps it picks even invalid spots that can't store water, I put it in a spot away from base with only a basic tank and after an hour, no water

**Comment by Hakameda** [comment]
Any chance of it being more usable? Maybe it could pick a block next to Apiary instead of randomly

**Comment by MineAnPlay** [comment]
I think we might have permission to edit Binne's Mods, if so yea we could change it. I can see 3 ways to do this: First one is to give it half or even quarter of it's territory and also increase the output to 1B everytime it's successful, Second one is to make it so it searches for all available tanks in range and give them water at about a bucket a second, Third one is to make it work like a reservoir where it will output to any of it's 6 sides and make it do around a bucket of water per side.

**Comment by draknyte1** [comment]
Sounds like OP free water from naturally generated bees (TF and other places spawn water hives) if they get changed up. /2cents

**Comment by damug** [comment]
Possibly let it generate water in nearby tanks at about the same rate as a rail craft tank in an average biome, i.e. 10 mb per 8 seconds?

**Comment by Hakameda** [comment]
Or remove it from world gen bees. You have to do minimal breeding to get
ocean bees anyway

**Comment by Hakameda** [comment]
Requires automation to be great, should be better then water tanks.

**Comment by draknyte1** [comment]
Doable on day one. 
Find village, steal an alveary, make some hoppers or other basic item movement setup. 
Get a pure drone and a princess, they'll breed forever. Not hard in any sense.

**Comment by Hakameda** [comment]
Which makes it worthless

**Comment by draknyte1** [comment]
Not when you can turn a single bee and drone into inifinite drones, which in turn can convert infinite other type princesses. 

Scaling here is the issue because it's so damn easy with bees.

**Comment by 0lafe** [comment]
Easy, reservoir bees. Needs eio reservoir block to breed, costs ocean and something else watery. Gives 1B/s per side. 

Maybe easier to scale than reservoir, but the first couple would take longer to make, as well as take more infrastructure to setup. Need to cycle bees, as well as pull water.

**Comment by Hakameda** [comment]
Well sort of pointless then, the ticket was to make it not useless

**Comment by Hakameda** [comment]
Balanced is not the same as worthless. It's in the pack already, doesn't do
much. It was an option to perhaps add. If the only ideas make it just as
useless. There isn't a point, better to not waste any further time on it. I
suggested it would just add to an adjacent tank. I picture it as better
then a water tank, worse then thirsty or eio. Needs slight automations,
only certain biomes because you don't have access to all traits yet. Only
daytime, since it's not nocturnal. Needs sky. Those things would improve
over time, but not that quickly

**Comment by richardhendricks** [comment]
See, those are valid arguments.  With those considerations, I can agree to output equal to a water tank in a normal biome only to adjacent tanks.  Would it be equal to all tanks, or in total though?

**Comment by Hakameda** [comment]
Total, probably easier if it searched for a tank. Found the first one then
outputted to that

**Comment by Hakameda** [comment]
Output should be higher though. They are limited. More so then a water
tank, 2-3x.  Not so OP that it's the only choice but good enough to be a
valid option if you got lucky and found alveraries or for people who would
rather use those

**Comment by Hakameda** [comment]
The effect could be removed from base water bees. Though you get handed ocean bees for free with quests. I believe just needs imperials which isn't hard to get too. Then you can buy ocean bees with coins. Using adjacent tanks would be the least search intensive

**Comment by richardhendricks** [comment]
I'm ok with leaving it on base water bees tbh. 1 water tanks worth from 1 bee house/alveary isn't much

**Comment by Hakameda** [comment]
It really should be 2-3x water tank

**Comment by richardhendricks** [comment]
OK, so proposal is 

Only output water to attached fluid inventory. (need to adjust search algorithm)
Base rate is 14 L/tick adjusted by production speed.
Base water bee is slowest, so .3 = 4L/t or 80L/s
Fastest production is 2x, so 24 L/tick or 480L/s

This is countered by starter bees not working underground or at night, and needing lily pads for flowers.

Also, compared to water tanks, they don't have a builtin tank so a tank would be necessary to provide water at night.  No boost in the rain.

**Comment by 0lafe** [comment]
Or you could move it to ocean bees and give it a useful amount of water. 80L/s is pretty much nothing. If you're trying to run anything meaningful off them you'd need so many that there's no reason not to use thirsty tanks or eio reservoirs

**Comment by Hakameda** [comment]
It's actually okay like that, because we can get fastest speed easily

**Comment by richardhendricks** [comment]
I don't think it's to replace the 2nd tier of water gen, but replace or supplant the first tier, the water siding tanks, and offer alternatives for players who want to survive in a desert climate.

**Comment by richardhendricks** [comment]
seriously, has anyone survived off of cactus farming?

**Comment by MineAnPlay** [comment]
Cacti farm IMO is the easiest farm to make, only problem is the speed of the recipe which discourages it too much.

**Comment by richardhendricks** [comment]
Well that's assuming you can keep an extractor full filled, and have one dedicated to making water.

**Comment by MineAnPlay** [comment]
Fluid Extractor isn't hard to craft and doesn't use much power and cactus farm just requires cactus, sand, cobble, string (or something that is similar), water and a hopper and it's infinitely expandable.

**Comment by richardhendricks** [comment]
String? A vanilla cactus farm "watering" a base might be funny.

**Comment by Hakameda** [comment]
It's a viable path if you breed bees, that should be an allowed thing.
Won't replace eio or extra bees in early stages, bees are slow going
intially

**Comment by richardhendricks** [comment]
We have our own fork of Forestry, so we can adjust bees as we want. 

OK, so proposal is

Only output water to attached fluid inventory. (need to adjust search algorithm). smallest range is 1 block effect, as range is increased effect range increases. Larger range could be disadvantage since it could miss a close by pipe.

Consdering output from stirling water generator, I think these numbers are ok.
Base rate is 10 L/tick adjusted by production speed.
Base water bee is slowest, so .3 = 3L/t or 60L/s
Fastest production is 1.7x, so 20 L/tick or 340L/s

This is countered by starter bees not working underground or at night, and needing lily pads for flowers.

Also, compared to water tanks, they don't have a builtin tank so a tank would be necessary to provide water at night. No boost in the rain.

**Comment by Methes** [comment]
Sounds balanced. Rain would also stop their function so they work pretty much like solar boilers.

**Comment by Hakameda** [comment]
I feel like rain should increase it though

On Dec. 29, 2019 8:01 a.m., Methes <notifications@github.com> wrote:

Sounds balanced. Rain would also stop their function so they work pretty much like solar boilers.
