### ISSUE TITLE
Harvest level of Railcraft block is not working

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#3360]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Client and my private server
#
#### What did you try to do, and what did you expect to happen?
I tried to harvest Railcraft block such as Coke Oven Brick and Water Tank Siding by hand.
#
#### What happend instead? (Attach screenshots if needed)
It harvested and never disappeared.

**Comment by Dream-Master** [comment]
nothing I can do here. Railcraft is not complete open source.

**Comment by shawnbyday** [comment]
Closing this issue. May I suggest bringing it up on the railcraft mod page on curseforge if you're still interested in getting it resolved. Thank you!
