### ISSUE TITLE
Add tooltip info to Ball of Moss

### ISSUE THREAD

**Issue by Wolozo7** [GTNewHorizons/GT-New-Horizons-Modpack#3362]
The question how to acquire moss for TC tools regularly comes up, especially now that we don't get random modifiers on tool levelups anymore. Therefore, it might be helpful to add a tooltip à la 'You need to research how to make this item' to the Ball (and potentially to the Silky Jewel as well).

**Comment by Dream-Master** [comment]
ok

**Comment by TwoTailedFox** [comment]
Why was this never implemented? This is a great suggestion for items lacking recipes initially.

**Comment by miozune** [comment]
@TwoTailedFox See #9747
