### ISSUE TITLE
Arcane Terminal turning crystallised essences to meto essentia type.

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/GT-New-Horizons-Modpack#3365]
#### Which modpack version are you using?
2.0.4.6

#
#### If in multiplayer; On which server does this happen? 
PropserCraft

#
#### What did you try to do, and what did you expect to happen?
Tried to shift click a crystallized essence of the Thaumic Energistics Arcane Crafting Terminal and expected it to be the same essence in my inventory

#
#### What happend instead? (Attach screenshots if needed)
The crystallized essences were turning to meto and that's all it would become in my inventory, regardless of what type they were originally in my system.

#
#### What do you suggest instead/what changes do you propose?
Fix it....please.

**Comment by AlexBucket** [comment]
Did this again, but it seems to have a mind of its own. Next time it was pulling all types out as victus.

**Comment by bartimaeusnek** [comment]
as far as i know shouldnt you even get crystalized essentia out of that termial...
