### ISSUE TITLE
Night vision, Suggestion

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/GT-New-Horizons-Modpack#3372]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Night vision Enchant from Thaumic Exploration
#
#### What happend instead? (Attach screenshots if needed)
I got the impression that it did not work as nothing happened after i applied it.
#
#### What do you suggest instead/what changes do you propose?
Only after finding a closeed post on github i lerned that the enchant is toggled on and off the same way as Dark Steen armor night vision. I suggest adding this  information in the Thaumonomicon for the benefit of future players so that they dont have to google this.

**Comment by Highbeam** [comment]
Which buttons activates the night vision?  I thought that enchant was a gimmick

**Comment by Ghengis88** [comment]
Think it was the same as ender  Io armor @Highbeam
