### ISSUE TITLE
A weirdly named by-product from sag-milling cobblestone.

### ISSUE THREAD

**Issue by Karl-Markkus** [GTNewHorizons/GT-New-Horizons-Modpack#3374]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I was using EnderIO sag mill, trying to get sand out of cobblestone
#
#### What happend instead? (Attach screenshots if needed)
![2018-07-30_20 55 08](https://user-images.githubusercontent.com/34920334/43414278-011e591e-943b-11e8-94c2-343c7ef16629.png)
As an additional by-product, you get a vanilla gravel which has a name given on the screenshot.
#
#### What do you suggest instead/what changes do you propose?
Re-name it into regular gravel? EnderIO or GregTech ore dictionary does not like vanilla gravel :p

**Comment by Dream-Master** [comment]
I try it but i fail allready. If you have any idea how to fix sure make a pull request.

**Comment by Dream-Master** [comment]
@Karl-Markkus
