### ISSUE TITLE
Wireless Redstone Must Go- Single player, and Server crashes.

### ISSUE THREAD

**Issue by ProsperCraft** [GTNewHorizons/GT-New-Horizons-Modpack#3375]
#### Which modpack version are you using?
All versions
#
#### If in multiplayer; On which server does this happen? 
Single player - https://gist.github.com/litjohn50/1b9d28f0b8bf81fab255211dca1ebf76
Multiplayer - ProsperCraft
I got sick of pasting these, there are 23 more where these came from.  
I wanted you to know the scope of the problem, it is big!

https://gist.github.com/ProsperCraft/4d121b81744096a72dbb11f8bf9318a5
https://gist.github.com/ProsperCraft/f2d891f9a0d40ce86dd686523d2d0adb
https://gist.github.com/ProsperCraft/afce1ebc854d622f69839173c51e77e7
https://gist.github.com/ProsperCraft/ac5c020cd8c7bc4ee4ffbeefaff9c10e
https://gist.github.com/ProsperCraft/65f5b6b2bd401d2f617caee80bc21aea
https://gist.github.com/ProsperCraft/21ed0fe4f63d6a20ed5ab38ddb1aa1f1
https://gist.github.com/ProsperCraft/f577b7ca89e4e210012adb2e9079736f
https://gist.github.com/ProsperCraft/1957368b4503dd38ed9d5fbd9a31ba13
https://gist.github.com/ProsperCraft/651a6d51315bfeeedaa0864d5755aede
https://gist.github.com/ProsperCraft/156bbf8780621e50ad3f1f6ed0e8888b
https://gist.github.com/ProsperCraft/77c4d9b03e315cf92e36a6c23e97f7b8
https://gist.github.com/ProsperCraft/16a3a010ee8a9b73e0c5db18e0ed7f5e
https://gist.github.com/ProsperCraft/c8a9aabc90020462c3952a251a881b32
https://gist.github.com/ProsperCraft/65509b3c3efe1d5d815698efc4e7027c
https://gist.github.com/ProsperCraft/3cf76cfa78ae2ada306a752b6eee0bf6
https://gist.github.com/ProsperCraft/512954051d86938116cb47ce1d7c49fe
https://gist.github.com/ProsperCraft/14eb41cf783233545d8ed9e95f3d74a3
https://gist.github.com/ProsperCraft/060b0b1f296464fc4cf5321d1d4516b8
https://gist.github.com/ProsperCraft/86eeea6cce7db0a85515fc8a0e77901d
https://gist.github.com/ProsperCraft/026b23cad07727c37f4abc481dc7bb9c
https://gist.github.com/ProsperCraft/bf2c7967798848df4aee072c4523201b
https://gist.github.com/ProsperCraft/66b78812241190f92ce6e833500cf9a8
https://gist.github.com/ProsperCraft/1a5acf81c52b46dc1fd188828a9bb3d5
https://gist.github.com/ProsperCraft/633a0a0900629bce74d5cb43db6ab92a
https://gist.github.com/ProsperCraft/d368c725174c42a71f43546dd0c7294d
https://gist.github.com/ProsperCraft/ddcaa29745fe4cae91d5fb8e6c81670f
https://gist.github.com/ProsperCraft/c7d937d21570792203207fef915405a1
https://gist.github.com/ProsperCraft/5088db94843b2ef3f1deeb5a1da04cf1
https://gist.github.com/ProsperCraft/fd0e595f13473c49fe107e7178596fc4
https://gist.github.com/ProsperCraft/1d361a1409c7adddd85385685676a117
https://gist.github.com/ProsperCraft/492ced1a5c831f194d67675046f57660
https://gist.github.com/ProsperCraft/a3ab79796a2d95a2152348fad213da8b
https://gist.github.com/ProsperCraft/35957489163ccc5799a33af906a73ba3
https://gist.github.com/ProsperCraft/a3f0229c079fe487a70379111f3aee75

#
#### What do you suggest instead/what changes do you propose?
Remove the wireless redstone mod.

**Comment by boubou19** [comment]
it crashes randomly but it's still a great mod. I use it a bit in my base

**Comment by richardhendricks** [comment]
WR-CBE is MIT license, we can look at fixing it.

http://chickenbones.net/Pages/links.html

**Comment by bartimaeusnek** [comment]
all server crashes refer to

```
@SubscribeEvent
    public void serverTick(ServerTickEvent event) {
        if(event.phase == Phase.START)
            RedstoneEtherAddons.server().processTrackers();
        else {
            RedstoneEtherAddons.server().tickTriangs(); <-This
            RedstoneEtherAddons.server().updateREPTimeouts();
        }
    }
```

so i guess adding 

```
if (RedstoneEtherAddons.server() == null)
		loadServerWorld();
```
should fix that.
Also we dont have this on the official servers as far as i know, maybe you have some aggressive unload mod or sth. like that installed? @ProsperCraft

**Comment by ProsperCraft** [comment]
Can't be only us, as someone had it in single player as well.

No we have the stock pack, and Thermos-1.7.10-1614-56-server.jar

Our plugins- 
Plugins (41): WitherStopper, WorldGenerator, WorldEdit, Questioner, OpenInv, Essentials, Payday2, SimpleVoteCommand, spark, WorldBorder, PetProtect, Votifier, BlockNuke, WorldGuard, ProtocolLib, ServerRestarter, AchieveThis, AutoPromotion, Morpheus, GTFixes, EssentialsGeoIP, PasteCrash, FakePlayerFix, PermissionsEx, SimpleVoteListener, Vault, EntityCheck, Prism, EssentialsSpawn, SendToSpawn, GoreaRestrict, AreaShop, Towny, PwnFilter, QuickShop, TownyChat, VanishNoPacket, DiscordSRV, Forge_Permittor, EnjinMinecraftPlugin, PlaceholderAPI

**Comment by boubou19** [comment]
it happened to me at least 4 times on delta

**Comment by richardhendricks** [comment]
@repo-alt Now that you are a chunkloading expert... :)

**Comment by repo-alt** [comment]
mhm. right, like Chickenbones and me
I agree that it would be nice to have this working though

**Comment by repo-alt** [comment]
I looked up WR-CBE source (https://github.com/TheCBProject/WirelessRedstone) and looks like those null checks are added later, the only problem is, as usual, 1.7.10 is not supported.

**Comment by bigbass1997** [comment]
I cannot find any github source for the 1.7.10 version that we use. http://chickenbones.net/maven/codechicken/WR-CBE/1.7.10-1.4.1.11/ indicates that the release was earlier this month, but TheCBProject/WirelessRedstone doesn't have a branch that reflects such a version, nor can I find the class `WRAddonEventHandler` in the repo.

However, the link I included has the [src jar available](http://chickenbones.net/maven/codechicken/WR-CBE/1.7.10-1.4.1.11/WR-CBE-1.7.10-1.4.1.11-src.jar); so we can use that to start a new repo to work off of.

**Comment by repo-alt** [comment]
WRAddonEventHandler is in src\main\java\codechicken\wirelessredstone\manager\ in 1.12
and in codechicken\wirelessredstone\addons\ in 1.7

**Comment by bigbass1997** [comment]
Yeah I get that. My point is that the latest release of the 1.7 version of the mod, from Dec 5/6th this year, doesn't seem to have any clear source on github. It's odd that there'd be a release, if no new commits have been made, not even to the new MC versions of the mod (since August). So I was just pointing to where the source could be found (for the version of the mod we are currently using), in order to easily add the patch ourselves.

**Comment by repo-alt** [comment]
I wonder who maintains that source from which the build was done. Perhaps he may be persuaded to accept a patch? It's not like this repository will much benefit from yet another mod fork

**Comment by Dream-Master** [comment]
@repo-alt @bigbass1997 should I fork wr-cbe to GTNH ?

**Comment by bigbass1997** [comment]
@Dream-Master Yes, go ahead and fork it. I've identified [which commit](https://github.com/TheCBProject/WirelessRedstone/tree/0c7fff755a3dc5a585f886b78cd3da72f9ff9f97) matches the source for [the version we currently use](http://chickenbones.net/maven/codechicken/WR-CBE/1.7.10-1.4.1.11/). Once forked, we can reset back to that commit and patch it as needed. Would have been easier if the person who continued working on the mod would have made separate branches; but oh well.

**Comment by Dream-Master** [comment]
@bigbass1997 https://github.com/Chicken-Bones/WirelessRedstone this one is not needed ?
The repo you show me is for 1.10 and 1.12 or you planing to downgrade it to 1.7.10 ?

**Comment by bigbass1997** [comment]
@Dream-Master I was simply going on what repo-alt first provided. Looks like the one you linked is essentially what I was going to reset to anyways. So go ahead and fork the Chicken-Bones/ one instead.

**Comment by repo-alt** [comment]
Yes, somehow I did not find the 1.7.10 repository

**Comment by bigbass1997** [comment]
Alright, implemented the patch as bart posted last year (which I agree with). Also changed the version of the mod. So it should be all ready; just `gradlew build` as usual.
