### ISSUE TITLE
Portable Tape Player Recipe Missing.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/GT-New-Horizons-Modpack#3379]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Singleplayer, and Prospercraft..
#
#### What did you try to do, and what did you expect to happen?
Craft a portable tape player.   Have a recipe for portable tape player.
#
#### What happend instead? (Attach screenshots if needed)
Found it impossible to make, contacted dream and was told to make an issue on here.
#
#### What do you suggest instead/what changes do you propose?
A recipe to exist for the portable tape player.

**Comment by shawnbyday** [comment]
@Teirdalin or anyone else have any recommendations on what the ingredients should be?
