### ISSUE TITLE
Manual pollination

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#3382]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I tried to manually pollinate silver birch tree with apple oak pollen collected by my bees
Edit: ive tried scanned and unscanned version of that apple oak pollen
#
#### What happend instead? (Attach screenshots if needed)
client froze then crashed, without any error message shown in client
#

**Comment by Dream-Master** [comment]
a fml log and a crash log would be nice. @Hyperic88

**Comment by Hyperic88** [comment]
[fml-client-latest.log](https://github.com/GTNewHorizons/NewHorizons/files/2252590/fml-client-latest.log)
[crash-2018-08-01_23.43.54-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/2252591/crash-2018-08-01_23.43.54-client.txt)


here they are, at least i hope that i post the good ones :))
