### ISSUE TITLE
LootGames 4th chest doesnt spawn

### ISSUE THREAD

**Issue by KayRahl** [GTNewHorizons/GT-New-Horizons-Modpack#3390]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Personal server
#
#### What did you try to do, and what did you expect to happen?
Completed LootGames minigame, expected 4 chests to spawn
#
#### What happend instead? (Attach screenshots if needed)
LootGames spawned only 3 chests

**Comment by richardhendricks** [comment]
Why do you think there should be 4?

**Comment by KayRahl** [comment]
Sorry for long reply, had to do some tests.

So, using modpack version 2.0.4.6 with LootGames version 1.0.16 i get this result:
![2046](https://user-images.githubusercontent.com/17408680/43648101-27cb23d0-9742-11e8-9a16-88bd8b5a310b.png)

the config file used for testing:
[2046.zip](https://github.com/GTNewHorizons/NewHorizons/files/2257660/2046.zip)
#
and when i test with modpack version 2.0.2.5 with LootGames version 1.0.13 i get this:
![2025](https://user-images.githubusercontent.com/17408680/43648267-93d58192-9742-11e8-951d-dd56b896211b.png)
and the config used for testing:
[2025.zip](https://github.com/GTNewHorizons/NewHorizons/files/2257669/2025.zip)

So after mod update its unable to get the achievement and loot

**Comment by Dream-Master** [comment]
I will ask @Namikon

**Comment by Dream-Master** [comment]
its a bug and Namikon will look into it soon.
