### ISSUE TITLE
Suggestion/Improvement: Fluid Solidifier - some molds take too long

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#3392]
#### Which modpack version are you using?
2.0.4.6
#

#### What do you suggest instead/what changes do you propose?
Some fluid solidifier recipes appear to take too long for what should be a simple process.  I believe some times could be shortened or fixed according to the amount required:

Rod takes 7.5 secs
Screw 2.5 secs
Round 2.5 secs
Bolt 2.5 secs
Long rod 15 secs
Rotor 5 secs
Ball 5 secs

In comparison:
Ingot takes 1.6 secs
Nugget 0.8 secs
Small gear 0.8 secs

Maybe this one has been discussed already or can be discussed?  I think it would be nice to see the Rod/Long Rod times reduced?

**Comment by Dream-Master** [comment]
will check

**Comment by shawnbyday** [comment]
@Highbeam what would you suggest the solidify time being for the rod?
