### ISSUE TITLE
Electric Goggles of Revealing Disappearing

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/GT-New-Horizons-Modpack#3410]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
I was fighting the yeti in the Twilight Forest and while getting hit from one of his attacks, my goggles just disappeared off of my head. They had like 50% charge on them, just like my boots at the time. Maybe they broke, despite having over half charge? Maybe they fell off?

**Comment by viljar290** [comment]
on delta. My nanohelmet did the same right after hitting 50% charge.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea?

**Comment by bartimaeusnek** [comment]
no sorry, no idea on this, might be an IC2 bug.

**Comment by boubou19** [comment]
i remember that that was also happening on the electric treetap from ic2 long time ago

**Comment by PapaTim68** [comment]
it might be a weird interaction between twilight/yeti and the googels hat a similar bug where I thought the yeti on our server and lost my nano stuff so travler boots asmd googels not sure if pants stayed or not but my adv nano stayed but that one was soul bound

**Comment by DoomSquirter** [comment]
we had this happen to someone on our server as well, lost goggles of revealing while fighting ur-ghast

forge server
