### ISSUE TITLE
Twilight Forest mini ghasts spawning in the last millennium 

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#3415]
#### Which modpack version are you using?
2.0.4.7

Twilight Forest mini ghasts are spawning in the last millennium, as they seem to ignore light levels this makes it very difficult to build anything mob proof. 

EDIT: or maybe the do obey light as I found one dark spot, but they still shouldn't spawn in there.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ?

**Comment by MineAnPlay** [comment]
I don't think it's Twilight Forest Carminite Ghasts, I think it might be Special Mobs Ghast (maybe the Faint Ghast?). I've rarely seen them in the overworld too so not sure how or why they spawn.

**Comment by bartimaeusnek** [comment]
@Dream-Master i think @MineAnPlay is right here, we had the same bug in the garden/mining/void dims, if you remember.

**Comment by Dream-Master** [comment]
Can we put this mob to the blacklist  for this dim?

**Comment by Prometheus0000** [comment]
Is this still happening or not?
