### ISSUE TITLE
Adding Runic Shielding to all Thaumcraft Armor

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/GT-New-Horizons-Modpack#3420]
#### Which modpack version are you using?
2.0.4.6
Runic Shielding should have the ability to be added to all Thaumcraft armor, not just vanilla Thaumcraft and Witching Gadgets armor (This includes Baubles items from Thaum and Witching Gadgets equipables as well)

**Comment by bartimaeusnek** [comment]
> Baubles items from Thaum 

thats due to thaum's license not possible
other stuff is possible
