### ISSUE TITLE
Thaumcraft mirror nerf in 2.0.4.7

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/GT-New-Horizons-Modpack#3424]
#### Which modpack version are you using?
on 4.6 now
#
#### If in multiplayer; On which server does this happen? 
n/a
#
#### What did you try to do, and what did you expect to happen?
n/a
#
#### What happend instead? (Attach screenshots if needed)
n/a
#
#### What do you suggest instead/what changes do you propose?

so I haven't seen the new recipe cept hear it's gated behind enderium for 4.7.

now if it's the regular mirror you are also now nerfing the magic hand mirror as well.  

if you are nerfing the mirrored glass recipe you are also nerfing all the other mirrors like essentia mirrors.

IMHO, this is a bad decision.  The magic mirrors are a simple item transport, UNIDIRECTIONAL, and speed is an issue tho can be rectified.  

In comparison to conduits/pipes, they lack the ability to tell when the destination is full, so their usefullness is limited w/o complex wireless redstone setups to turn off feed at source if destination is full or near full.

the fact that they show up well before anything else at least gives you a simple transport solution (that you have to work for via thaum).  

if the mirrors are now at the same level as transcievers, then I guarantee you NOBODY will make mirrors except the people wanting any of the downstream things that require it for crafting.  

If you feel MV is too early, then can I interest you in some HV recipe or something.  or better yet, make it a more expensive recipe but keep it at mv.

**Comment by Dream-Master** [comment]
mv is definitely to early. It to stuff interdimensional

**Comment by 0lafe** [comment]
The other wireless transfer system is gated to EV too, but costs much more to make, as well as power to run. The mirrors on the other hand do all the functionality of the dimensional transceivers except RF transfer, for a cheaper construction cost, but an increased infrastructure cost. That sounds fairly fair to me. You don't really need much wireless transfer pre moon anyway. 

>if the mirrors are now at the same level as transcievers, then I guarantee you NOBODY will make mirrors except the people wanting any of the downstream things that require it for crafting.

I'd still make them, considering they cost a lot less. Also no dumb soul binding of witches needed.

**Comment by 0lafe** [comment]
Maybe switch it to titanium? Slightly earlier, cheaper, but still gates it to the rocket. Imo, giving interdimensional item transport when you start being interdimensional, is a good fit.

**Comment by Dream-Master** [comment]
sure why not

**Comment by CalterOK** [comment]
The transfer of mirrors to the EV makes useless inventory (at the same level available AE). Although this was a great alternative to Ender IO and Project Red storage system.

**Comment by Dream-Master** [comment]
Yes but it was dirt cheap. Again i can change the recipes again but not back to what it was.

**Comment by CalterOK** [comment]
You can use hollow metal in the craft, which will require a warp that will somewhat reduce the number of those wishing to make a mirror early.

**Comment by Dream-Master** [comment]
No void metal is to easy to get.

**Comment by CalterOK** [comment]
Yes, a hollow metal is easy to obtain, but to open a recipe, ancient knowledge is required. And if you overdo it with the warp it will bring a bunch of problems.
Shadow metal in terms of industry requires more development in connection with cooling, but its production itself opens in magic before the hollow metal.
Here you can already choose how to limit availability. Required machines or the danger of warp effects.
![2018-08-09_16 24 43](https://user-images.githubusercontent.com/35035276/43901702-cca3e8f8-9bf0-11e8-9cf2-7c0c557de127.png)
![2018-08-09_16 24 49](https://user-images.githubusercontent.com/35035276/43901703-ccd291d0-9bf0-11e8-8edf-e419cc681632.png)

**Comment by Zoko061602** [comment]
I don't like the idea to gate regular TC stuff behind it's addons, I think the  addons should be as optional as possible. Energetic Alloy seems quite more fitting imo, it's relatively cheap, but it requires at least kanthal coils, so a vac freezer is required, gating it to mid/late HV.

**Comment by Dream-Master** [comment]
Ok i will do a mix of all this metals probably

**Comment by DoomSquirter** [comment]
I like the idea of titanium.  I don't think it's needed to complicate it even further by adding warpy research, etc.  again, I stick by my argument that mirrors are a much inferior means of transport in comparison to other methods.

**Comment by CalterOK** [comment]
The above materials do not require a flight and are available before titanium, although they stand roughly on the same level with it.

**Comment by Dream-Master** [comment]
no they don't. I like the titanium idea. you can get titanium  when processing alu gravel pre moon. not much but on or two ingots should be no problem.

**Comment by MineAnPlay** [comment]
Getting Titanium from Aluminium Gravel? No thank you. I'd prefer Shadow or Energetic Alloy (Both require better coils and the former also requires Vacuum Freezer and TC research). Like some have pointed out, making it require Titanium just means you have access to it when you reach the moon and when you do reach the moon you have access to better alternatives then the mirrors.

**Comment by CalterOK** [comment]
@Dream-Master And what about the mirrors for the essence? At what level will they be available?

**Comment by CalterOK** [comment]
Also, not all items are correctly transferred through mirrors, and without vacuum funnels the use of a mirror is fraught with loss of objects.

**Comment by Lainiel** [comment]
Honestly I couldn't care less about item transfer for mirrors, but essentia mirrors shouldn't be gated behind T1 rocket. Without them you can't provide essentia for your infusion without hauling the jars every time and you can't automate your thaumatorium. Titanium already unlocks AE2 storage and transfer for essentia which makes the essentia mirrors already obsolete when they unlock.

If you want to lock regular mirrors with titanium I have no problem with that, but don't lock essentia mirrors with it. Use shadow or energetic alloy for them.

**Comment by 0lafe** [comment]
To be fair, you get the infusion altar in HV, so waiting a tier to reasonably automate it isn't the worst. But if thaum AE is also EV, there doesn't seem to be a huge reason to use the mirrors. You can also just put your smelters near the altar, or use golems, or probably some other shenanigans. Idk, I don't mind one way or another, the item ones are really the OP part

**Comment by DoomSquirter** [comment]
I voiced my opposition to this at the time and I'll just reitterate it.  they can magically move items.  yes.  but are they OP?  absolutely not.  

1) they are slow.  you can speed them up but that adds to the problem below.  
2) they tend to clog and you have to either setup a vacuum hopper, hopper, or some sort of collection system on receiving end.  on sending end you have to setup a dropper or some sort.
3) using conduits works but it sort of exasperates the issue.  items come through at a fixed rate.  I've never done tests but I swear I was losing logs from my wood farm while using them.

where they were originally was an ideal place to have them.  they weren't on par with ender storage which is the next step up to item teleportation which is a few tiers above this, but it's also not as useful as ender storage.  moving it closer to enderstorage makes them absolutely useless since by the time you can make them, I'd rather hold off to make enderstorage.  

with that said, also losing out on being able to transfer essentia as well on top of it is insult to injury.

I saw it balanced before.  Not now.  Now there's an imbalance.

**Comment by 0lafe** [comment]
If you put an adv item collector on each end, and then push/pull from what ever inventory it's attached to, it seems like you have a cheaper ender storage. If they straight up delete items that seems like something that should probably be fixed. Looks as if it does that unless you give it ordo Cvis. 

>However, there is a chance that items will be destroyed. To remove this chance, the player needs to power one of the mirrors with Ordo CV.

I don't see how that's not as good as a DT or something, besides the rate. Can't find anything that gives a solid rate, but if it's 1stack/s or so, that's pretty good.

**Comment by DoomSquirter** [comment]
I actually did run into one issue but I don't recall exact losses

I have a setup that makes books

I had setup a mirror, using eio to pump books from barrel into mirror

other end was the 2 golems and barrels running the think tank.
they dropped into world and picked up by adv item collector.  it was powered by node so sped up.  (note I did this after I noticed how slow it was when I started so that was changed a couple minutes after I was noticed that books were leaving faster than they were showing up.

I had a non upgraded barrel full of books at sender end, empty on receiver

golems were running but the throughput on them is really slow

I started moving the barrel.  when it was done I checked the receiver and waited for them to catch up.  It was quite a few minutes till it did.  when it was done I had like 48 stacks or thereabouts.  so in my eyes I liked 20 something stacks of books doing this.

metering it became the thing I'd do, or better yet, never have it worry about bulk moves, just keeping the trickle going was fine.

but look at what we are talking about involving setup, doing things to fix issue or to work around it vs the ease of use enderstorage is.  I think I stated that I was fine moving it from mv to hv but to ev and enderium was too harsh especially considering the implication you were fucking the item mirrors right alongside the essentia ones.  weighing the advantages/disadvantages is called balancing the equation.  not just looking at one side of the equation.  

at the time that I started using this it was a godsend cause I had no way except long ass runs of item conduits/pipes from tree farm.  I never used it interdimensionally and I concede that's a major negative against it as far as gating goes, but I still feel if it's moved to ev, it'll NEVER be used.  then you might as well just state that you're nerfing the essentia mirrors and that's it.

**Comment by monroth** [comment]
Gating essentia mirrors beyond further than just infusion is absurd, it is HV already. The only alternatives to mirrors and their byproducts (such as mirrored jars) are golems (which are stupid running entities, that just randomly stops to look at surroundings and many other issues as well) and thaumcraft pipes, which are awful. Really awful, a lot worse than current options of item and even fluid transportation. It does not need to have enderium in it's recepie, it does not need to have titanium in it's recepie, infusion automation is impossible at that moment even with mirrors. Thaumcraft tube system was _designed_ with thought in mind that when you get infusion, you get essentia mirrors. And of course, it was almost never used to transfer essentia interdimensionally, so it makes no sence to compare gating essentia mirrors to other interdimensional transports. The only usable alternative to using mirror is to place everything inside your infusion room - thaumatorium, essentia storage, etc. Result is not harder, it is messier and uglier.

About item mirrors, their interdimensional transport ability is overrated - when i needed that interdimensional abilities, i have a lot of alternatives, without a lot of drawbacks that DoomSquirter mentioned. However, despite their limitations it was rather neat HV level of inside dimensional transportation, when direct piping would be awkward or messy or long (for example, from faraway tree farm to main base, or from outside of multiblocks to inside of multiblocks (am i the only one who build something inside their pyrolize oven?). May be there is an option to make some weak option of mirror without interdimensional abilities, that don't use advanced materials?
