### ISSUE TITLE
Native Stibnite Cluster On Alchemical construct

### ISSUE THREAD

**Issue by skynsun** [GTNewHorizons/GT-New-Horizons-Modpack#3454]
#### Which modpack version are you using?
2.0.4.8
#
#### If in multiplayer; On which server does this happen? 
I tried on private server and solo
#
#### What did you try to do, and what did you expect to happen?
i tried to craft Native Stibnite Cluster from witching gadgets in the alchemical construct and the craft doesn't start. However the craft work in the crucible.
#
#### What happend instead? (Attach screenshots if needed)
When you confirm the craft, it doesn't start and when you leave the alchemical construct interface and reopen you can see multiple instance of the native cluster.
#
#### What do you suggest instead/what changes do you propose?
i expect the alchemical construct to craft the Native Stibnite. I tried other ore and it worked.

**Comment by Dream-Master** [comment]
I guess you get this only via the pickaxe of the core during mining? @bartimaeusnek any idea?

**Comment by boubou19** [comment]
you can also clone them in a crucible iirc but it should also work in the alchemical construct

**Comment by skynsun** [comment]
the recipe is normal ore give you 2 Native cluster.
