### ISSUE TITLE
Make High Tier Machines findable

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#3461]
#### Which modpack version are you using?
2.0.4.8

While all the fancy names for machines are cool it makes it very difficult to search for the higher tier versions of most machines, or even tell if they exist. Suggestion get rid of the fancy names or at least leave the original name in its name so it can be found.

**Comment by Dream-Master** [comment]
I like fancy names. Check per id you will find it :)

**Comment by MineAnPlay** [comment]
Search for there descriptions, that's how I do it :D.

**Comment by richardhendricks** [comment]
It's annoying and confusing for new players.  We can at least keep the low-tier name in the higher tiers as part of the description.

**Comment by Dream-Master** [comment]
yes in description

**Comment by GTNH-Colen** [comment]
Yea honestly this is just a pain, meme names are fun and all but when it's actually stopping players from using NEI properly it should be stopped.

**Comment by Anarack** [comment]
See how gt++ shows in its description what functions each multi block has.
