### ISSUE TITLE
New lootbags and balanced the old ones

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#3469]
I need idea for Tier 7-9 Lootbagas.
I need ideas of balancing Steam to Tier 6 ones.

**Comment by richardhendricks** [comment]
Where is the loot tables now for the tiers?

**Comment by Dream-Master** [comment]
loot bag folder. lootbags.xml

**Comment by bartimaeusnek** [comment]
tier 7 = tier 6 without trash maybe?

**Comment by Dream-Master** [comment]
yes maybe no trash at tier 7 but we need more items and new items

**Comment by Dream-Master** [comment]
Add Enchantment recipes for missing Fortune 3 Lootbag types

**Comment by Cinobi** [comment]
1. remove chanse of crap in t1-t3 lootbags - they are too lowtier to waste fortune3 book for them anyway
2. reduse chanse of crap in legendary lootbags - draconic core is too high-tiered compare to time when u get legendary bags(u can get them at ev!)

**Comment by Dream-Master** [comment]
you mean you get a Draconium core before you make the legendary Quest ? @Cinobi

**Comment by richardhendricks** [comment]
Remove the OW berries from the lootbags. Add to Coins quests, 1 per berry type, 25 Explorer coins each.
Remove the Nether berries from lootbags. Add to Coins quests, 1 per berry type, 50 Explorer coins each.
Lower chances on saplings awards.

Useful loot for steam era
- half Stack of Coal Coke Blocks
- 2 Stacks of torches
- 2 LP coal boilers
- 1 HP coal boiler
- Steam macerator (LP or HP)
- 16 coke oven bricks (the block)
- 16 BBF bricks (the bricks)
- 4 hoppers
- mid-tier foods like jelly sandwiches, pies
- single-block ores needed for steam, like lapis, redstone, basaltic mineral sands, for orewand (one, not all at once)
- 8 spawn eggs for animals (8 cows, 8 chickens, etc)
- 128 Brownstone Road blocks (blocks that increase speed, craftable normally in smeltery + tin)
- 4 stone builder's wands

**Comment by richardhendricks** [comment]
LV era loot
- Stack of coal coke
- 32 oil cells
- 2 stacks of flat lamps
- 32 red alloy ingots
- basic gas turbine/combustion generator/steam turbine
- centrifuge
- macerator
- 64 mining pipes
- 32 empty cells
- 8  large steel fluid cells
- higher tier foods (not the top tier ones used for healing axe) - good pizzas, good burgers, etc.
- forestry farm blocks - maybe a mix of types?
- Steves carts parts
- Maybe some IC2 seedbags, nothing too crazy, stickreed, ferru, terrawart or coppon, 2 of each, 1/1/1
- weeding trowel
- 32 Rubber bars

MV loot
- Centrifuge
- Macerator
- 8 vanadium steel ingots
- 8 damascus steel ingots
- 8 manganese ingots
- 8 chrome ingots
- Supertank
- more forestry farm blocks
- ic2 seedbags - argentia, plumbilia, nickelback, or redwheat, 2 of each, 1/1/1
- crop matron
- 32 Polyethylene bars
- various circuit pieces

HV loot
- ic2 harvester
- ic2 seedbags - blazereed, aurelia, bauxia, or rape, 2 of each, 1/1/1
- rocket pieces
- half stack of iTNT
- 16 nitric acid
- 1 TNM
- 32 PTFE bars
- various circuit pieces

**Comment by Cinobi** [comment]
I mean when u get ur first lootbags u a AGES below draconic cores tier -> so most of the "legendary" lootbags yelds tree saplings. U just can't enchant them atall.

**Comment by Dream-Master** [comment]
@richardhendricks can you suggest more lootbags for EV and IV and LuV please.

**Comment by richardhendricks** [comment]
uh, I have no idea what would be good EV/IV/LuV rewards would be. Other than usual components, maybe batteries/lapotron crystals?

**Comment by Dream-Master** [comment]
@cinobi, @blubeine, @0Lafe any idea?

**Comment by Bluebine** [comment]
A list of things that can be added for every tier- I think some of these are already implemented, like the motors, at least for the lower tiers.
8 motors of the tier
4 pistons of the tier
4 pumps of the tier
4 circuits of the tier
a battery of the tier- lithium for LV-HV, sunnarium for EV-LuV
2 machine hulls of the tier
24 ingots of the tier's material
Perhaps a solar panel 3 tiers lower? i.e. LV solar panel at EV- these should be REALLY rare though. 
2-4 heavy duty alloy ingots for the rocket of the tier- tier 1 for HV, tier 2 for EV, etc.
16 wires of the superconductor of the tier previous (MV superconductors at HV, HV superconductors at EV, etc)
I think it would be interesting to have a rare chance to get a free lootbag of the tier ABOVE. You'd have to keep it pretty rare, but it'd be cool.
32 of the tier's cable (aluminium for EV, platinum for IV, etc.)
A prospector's scanner of the tier, made out of a tier-appropriate metal (steel for LV, vanadiumsteel for MV-HV, shadow for EV+). Should be pretty rare.
4 large fluid cells, of the appropriate size for the tier (steel for LV, aluminium for MV, etc.)

**Comment by boubou19** [comment]
it would be cool if you could add required components for gendustry stuff, like naquadah comb or a bucket of mutagen

**Comment by Dream-Master** [comment]
in which bag iv or LuV?

**Comment by Dream-Master** [comment]
in which bag iv or LuV?

**Comment by boubou19** [comment]
LuV since you can only start craftings things in LuV

**Comment by Dream-Master** [comment]
ok

**Comment by boubou19** [comment]
also there is some item only possible to craft in zpm so might be a valid suggestion for zpm lootbags too

**Comment by richardhendricks** [comment]
Oh yeah, some bee stuff would definitely be useful loot

LV
2 Bee houses
Scoop
wooden frame

MV
4 apiaries
1 apiarist chest
2 bee collector's jar
3 impregnated frames

HV
4 alveary block
2 alveary frame block
6 proven frames
Climate Acclimator (rare)

I don't know if we want to award bees?

**Comment by richardhendricks** [comment]
LV/MV/HV
Tin cans of food

**Comment by Sudoloo** [comment]
For later tiers, void metal pipes are ossly good, other options could be tier relavent metal machine casings (multiblocks) in quantities of 4 to six, medium handfulls of circuits of the earlier tiers, at tiers 5 and up a bag of preprogrammed circuits 1 through 24 would be funny. Tier 1 and steam should have weak thaumic bases crops like metalleat and rainbow ( gay ) cactus. Choochum schoochers and other niche tools no one makes would also be good.

**Comment by richardhendricks** [comment]
GT branch cutters and Sense would be nice.

**Comment by redmage17** [comment]
Remove the material requirements outside the enchantment books for Fortune 3 bags.

**Comment by ToastedEggplant** [comment]
Can we keep the unique Tinker's tools that appear in the lootbags as well? Those are a nice surprise to get.

**Comment by Dream-Master** [comment]
@ToastedEggplant feel free to design high tier tools and add it via mt commad here ?

**Comment by ChemEng227** [comment]
perhaps Tectech machine blocks and Genetics machines could be put in ZPM and UV lootbags.

**Comment by Ethryan** [comment]
Think we keep this open.

**Comment by johnch18** [comment]
Realizing that UV+ bags only give diamonds was a sobering moment for me

**Comment by Prometheus0000** [comment]
> Think we keep this open.

Why? The only instance of us giving out a higher than LuV lootbag is in a quest that uses it as a joke. And we should remove all the LuV rewards too, aside from for major stuff like the fusion quest.

Honestly, I think _specific, non-random_ rewards are better than lootbags anyways, since you can control what the player gets better, and they never get anything OP unless you let them, and they never get anything terrible, like happens almost every time with lootbags. I'd also say the enchanting them for luck thing should go, or be made _much_ easier. As far as I can remember it's either not worth it, or you're in the next tier by the time you can reasonably do it.

**Comment by Glease** [comment]
Reminder tag added for now. It looks like something that deserves it.

**Comment by bombcar** [comment]
A visual representation of some of the loot bags is now here: https://gtnh.miraheze.org/wiki/Lootbag

The *only* loot bags that everyone agrees are *entirely* worth it and worth enchanting are the AE2 loot bags.

The IV ones are also nice, but it's a tradeoff.
