### ISSUE TITLE
Soulbound on ElectroMagic armor

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/GT-New-Horizons-Modpack#3478]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Delta
#
Currently, there seems to be no way of adding soulbound/soultethered to stuff like nano wings or nano goggles. Can we make it possible to add soulbound to the armor?

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ?

**Comment by bartimaeusnek** [comment]
maybe will test something.

**Comment by draknyte1** [comment]
IC2 and it's addons generally make all armour non-enchantable on purpose.
I imagine EMT does the same as every other addon.
