### ISSUE TITLE
Suggestion to craft Pam's Pasta industrially

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/GT-New-Horizons-Modpack#3481]
So I'm kind of disappointed in the number of ways machines make crafting food easier and more efficient. I  would like to propose a few recipes to fix that.

I would like to propose an alternative way to make pasta (the hard noodles that aren't edible). Putting some dough through an extruder with a rod mould could make a large raw pasta noodle, cooking it into a cooked large pasta noodle could then allow you to use a cutting machine to chop it into some pastas. I'd love to hear what you guys think of this and I'm planning to make more food suggestions after this~

**Comment by Dream-Master** [comment]
Ok but this need two more items. raw pasta and cooked large pasta

**Comment by Dream-Master** [comment]
@LogicFalls need some texture for this please.

**Comment by richardhendricks** [comment]
we also have GT microwave oven, so normal smelting recipes work there too.

**Comment by ljjmrlion** [comment]
Curious on how this is going
