### ISSUE TITLE
Dimethylbenzene is not produced in Distillation Tower

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#3489]
v2.0.4.8

Dimethylbenzene can only be distilled from wood tar in a Distillery, but not is not produced in slot 5 in the Distillation Tower
![image](https://user-images.githubusercontent.com/30087707/44364578-a7796c80-a4c7-11e8-866d-63ff36d13544.png)
![image](https://user-images.githubusercontent.com/30087707/44364550-99c3e700-a4c7-11e8-8560-be58f50402a1.png)

**Comment by Dream-Master** [comment]
Will check

**Comment by DualBallers** [comment]
Added in 2.0.6.0 so this can be closed.

**Comment by mitchej123** [comment]
It's also not produced in the LCR, only the single block chemical reactor; unless I missed the commit that fixed that as well.

**Comment by DualBallers** [comment]
This issue only concerns the Distillation Tower. So maybe close this and leave issue 3620 open for the LCR recipe.

**Comment by mitchej123** [comment]
Could always edit the title and say it's not produced properly in multiblocks, then 2 for the price of one :-D
