### ISSUE TITLE
Ores are invisible while mining on some planets

### ISSUE THREAD

**Issue by litjohn50** [GTNewHorizons/GT-New-Horizons-Modpack#3490]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
I was trying to mine and I expected to see the ores when they were uncovered.
#
#### What happend instead? (Attach screenshots if needed)

https://gyazo.com/4f13a7f6d0e78900bc7f82fa3a734839

**Comment by bartimaeusnek** [comment]
relogging will fix this, its an issure caused by GaGreg creating the vein pretty late. will be changed once we have @richardhendricks ' OreGen for GaGreg.

**Comment by richardhendricks** [comment]
Will take a look after this release.
