### ISSUE TITLE
Vis Shard Foci Extremely Underpowered

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/GT-New-Horizons-Modpack#3500]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
*Use the Vis Shard Foci on a cow, with upgrades Potency IV, Persistant (with an a for some reason) and using a Primal Staff.
*The cow to maybe die as it would with,  any other upgraded attack foci.
#
#### What happend instead? (Attach screenshots if needed)
It did just two and a half hearts damage.
#
#### What do you suggest instead/what changes do you propose?
Increase damage of vis shard, and maybe vis cost to be a tiny bit higher than other foci as it is a bit more expensive to make;  if able to change this.    It's one of the cooler foci just more or less useless in it's current form.

**Comment by Dream-Master** [comment]
Vis Shard Foci is from which mod? @Teirdalin

**Comment by Teirdalin** [comment]
Tainted Magic
