### ISSUE TITLE
Augment: Vis Channels recipe unable to be done if Augment: Tainted Core is researched.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/GT-New-Horizons-Modpack#3501]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Singleplayer & Prospercraft
#
#### What did you try to do, and what did you expect to happen?
*Put Vis Channels augment, from Thaumic Machina onto my staff.
*The infusion to work.
#
#### What happend instead? (Attach screenshots if needed)
It begins the Tainted Core infusion, even though the recipes are almost completely different.
#
#### What do you suggest instead/what changes do you propose?
Allow the Vis Channels infusion recipe to work properly.

**Comment by Dream-Master** [comment]
@Teirdalin @DoomSquirter  which mod add it ?

**Comment by DoomSquirter** [comment]
thaumic machina

**Comment by Teirdalin** [comment]
Pretty sure Thaumic Machina.

**Comment by DoomSquirter** [comment]
from barokko in discord
If anyone broke Augment: Vis Channels of Charge Buffer after learning Augment: Tained Core (Thaumic Machina) - you can erase it with NBTExplorer - just backup and edit "saves<savename>\playerdata<username>.thaum" - you need to remove nodes WAND_AUGMENTATION_TAINTED_CORE and  WAND_AUGMENTATION_TAINT_CAPPING
