### ISSUE TITLE
Dagger of sacrefice

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/GT-New-Horizons-Modpack#3507]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
i have a powered spawner from ender IO spawning zombies near my blood altar and killing them with dager of sacrefice
#
#### What happend instead? (Attach screenshots if needed)
small zombies won't die, hitting them with the dager is like hitting with a empty hand
#
#### What do you suggest instead/what changes do you propose?
fix if fixable?

**Comment by Ghengis88** [comment]
mobs stand on same y level and up to 2 blocks away from altar

**Comment by Dream-Master** [comment]
witchery is closed source so no fix possible i guess.

**Comment by Ghengis88** [comment]
ok close the issue then

**Comment by Ghengis88** [comment]
oh i could close it xD

**Comment by DoomSquirter** [comment]
ummm he was talking about blood magic not witchery

**Comment by Ghengis88** [comment]
but blood magic is closed source also i think?

**Comment by DoomSquirter** [comment]
I have no clue but still, when a person calls out a fact that isn't correct, one has to correct them.  

tbh, zombies wouldn't be my first choice to spawn for blood magic tho.  are the mobs being spawned above or below your altar?  since they are half height, I wonder if you are exact one block more away from your altar than you should be and thus the baby zombies aren't considered close enough to oneshot

**Comment by DoomSquirter** [comment]
errr above comment assumes you are killing them below

**Comment by Dream-Master** [comment]
Oh sorry my bad. Blood magic is open source and we work the repo. If any one is able to fix it sure, @Ghengis88 @DoomSquirter

**Comment by Ghengis88** [comment]
the stand against the altar trying to get me, i use zombies becous i want some loot from them so i do 2 birds with one stone

**Comment by 0lafe** [comment]
I used zombies for mine and I don't think I ran into this problem. Are you actually using the dagger or are you using something else to kill? Also, normal dagger or the blood arsenal 2x one? I mostly used the 2nd one, so maybe the original is worse or buggy or something

**Comment by DoomSquirter** [comment]
I wouldn't suggest zombies cause of reinforcement mechanic (they call for help which teleport nearby)

normally, I would use skeletons for this.  drop them exactly one block above the altar onto a half slab where I can whack their toes

trying to get drops while you're doing this doesn't make much sense unless u can throw looting onto the dagger as well.  make a mob farm for that.

**Comment by 0lafe** [comment]
Looting or not, zombies drop a good amount of stuff from powered spawners, especially if those can be accelerated (idk). My setup of 4 spawners still got tons of iron/steel/gold from the drops, at least 20k of each in like a week. Diamonds too, and I turned the XP to copper. Decent loot from something I didn't really need. Doesn't really compare to quarrying, but it's a nice bonus of materials.

**Comment by DoomSquirter** [comment]
actually all mobs that have infernals do that.  

but that wasn't my point.  just how long are ppl doing manual sacrifice before they can upgrade their altar to support a WoS?  either way, you're better served worrying about the LP and not the drops while doing this.

fyi, my one wisp spawner has given me 10's of thousands of gold/iron/steel which I fluid solidify from their armors/weapons as well as heaps of diamonds/etc.  so yeah, I love me my mob farm, which sorta re-emphasizes why I said make a mob farm if you want loot.  not just while you're getting LP for the slabs, etc.

also, I've done this in the past, I'm not sure if it'll still work but I've used a dynamism tablet with dagger to do this w/o issue, so you may be able to automate this till you can get a WoS going.

**Comment by 0lafe** [comment]
> just how long are ppl doing manual sacrifice before they can upgrade their altar to support a WoS?

It's kind of a while. Those rune things are not cheap one bit, and BM isn't good enough to really warrant going too hard with it. World accelerators are pretty much a must when doing BM just with how many infusions you need to do

**Comment by Ghengis88** [comment]
![image](https://user-images.githubusercontent.com/25811344/44615464-01b55d00-a83b-11e8-9d99-d3a95e84af0f.png)

**Comment by Ghengis88** [comment]
![image](https://user-images.githubusercontent.com/25811344/44615476-2c9fb100-a83b-11e8-9adb-1ead81f18bbc.png)


![image](https://user-images.githubusercontent.com/25811344/44615480-4640f880-a83b-11e8-874d-09b0fb59a7ca.png)

**Comment by Ghengis88** [comment]
lots of little shits staying around :(

**Comment by DoomSquirter** [comment]
see if you can place a half slab over where they are and can / can not hit them where they are congregating

maybe you can't hit them cause they are half height and you are trying to attack them over a full block

**Comment by Ghengis88** [comment]
i can kill them with the dagger, just takes multiple hits and it wont generate LP

**Comment by Teirdalin** [comment]
I'd kinda suggest setting up a necromantic tablet and having some villagers spawned in, and thaumic relocatored onto your altar.  They'll give you so much blood.
