### ISSUE TITLE
Apprentice blood orb

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/GT-New-Horizons-Modpack#3508]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
charge my blood network wit the orb
#
#### What happend instead? (Attach screenshots if needed)
nothing
![image](https://user-images.githubusercontent.com/25811344/44615709-1ac10c80-a841-11e8-9940-309d9d5adb1d.png)
![image](https://user-images.githubusercontent.com/25811344/44615710-257ba180-a841-11e8-8216-ea28e82de038.png)
weak blood orb works fine
![image](https://user-images.githubusercontent.com/25811344/44615715-40e6ac80-a841-11e8-8191-94354329e3a6.png)

#

**Comment by Ghengis88** [comment]
it seems it requires a altar of the same tier ( possibly higer tiar altar works but cant tast :()

**Comment by Ghengis88** [comment]
is this intended btw?

**Comment by Dream-Master** [comment]
what you mean create a high tier orb in a low tier altar or refill it?

**Comment by DoomSquirter** [comment]
did you rclick the orb first?

you can put any orb in any altar

**Comment by Ghengis88** [comment]
when i put my apprentice in a tier 1 altal nothing happens, and no animation, but when i put it in a tier 2 altar it accepts LP.
and my weak blood orb wont accept LP on either my tier 1 altar or tier 2 altar

**Comment by Ghengis88** [comment]
and yes i have rightclicked the orbs

**Comment by Ghengis88** [comment]
i am new to bloodmagic but i dont think i am doin anything wrong, i can get LP into my network but only with the apprentice orb in a tier 2 altar and of you look at the top screenshot it says it is bound to me

**Comment by DoomSquirter** [comment]
any orb, any altar, but only up to altar's capacity.  so if you are trying to charge your LP beyond the capacity of the altar's capacity then your orb will not charge any more beyond that.

**Comment by DoomSquirter** [comment]
and just throwing this out there even tho it's obvious.  you are not charging your orbs.  your orbs are conduits to your LP pool.  one shared pool.  each orb is just a connection to that same LP pool.  they do not act as batteries.

**Comment by Ghengis88** [comment]
![image](https://user-images.githubusercontent.com/25811344/44616492-4946e380-a851-11e8-8ca1-0925299a5373.png)
now it is charging

**Comment by Ghengis88** [comment]
![image](https://user-images.githubusercontent.com/25811344/44616499-5f54a400-a851-11e8-9ed1-0f5d7900b093.png)
and goes beyond altar capacity

**Comment by DoomSquirter** [comment]
every orb has a capacity that is applied while charging to your LP network.  your LP network upper limit isn't really defined.  it's defined by the highest orb you've aquired and charged in an appropriate altar.

you can boost that however, like there are rune of the orbs which boost your LP pool while charged in that altar.  

never used the avaritia orb but I just assume it has literally no limit and will just charge till it hits whatever it's max limit is, some big ass number.

to see info on the altar, you'll need a divination sigil.  to find more info you can make a sigil of sight which shows different info on the altar.

**Comment by Ghengis88** [comment]
yea, but i dont understand why it wont charge my orb...

**Comment by DoomSquirter** [comment]
is your lp at 0?

again, you are not charging your orb

if your lp is 0 or < the capacity of your orb, it will charge, but after the capacity of the orb is passed your lp will not charge with that orb anymore

**Comment by Ghengis88** [comment]
look at the screenshot, my network has 7000 ish lp and it is not accepting

**Comment by Ghengis88** [comment]
but if i change from weak to apprentice it starts transfering to my soil network

**Comment by Ghengis88** [comment]
oh my bad weak has 5000 limit, but apprentice orb still dont charge in tier 1 altar

**Comment by Dream-Master** [comment]
@Ghengis88 is this still a bug or can this be closed?

**Comment by Ghengis88** [comment]
Still not working, same with every tier. You cant use a tier 2 orb in a tier 1 altar or a tier 3 orb in a tier  2 altar @Dream-Master
