### ISSUE TITLE
Suggestion: Add distillery recipe for liquid Fertiliser 6548:775

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#3540]
#### Which modpack version are you using?
6.0.4.5
#

#### What do you suggest instead/what changes do you propose?
Fertiliser has become fairly useless in my game but I am still producing insane quantities of it.  I noticed there is a liquid fertiliser recipe but it has no use.

I propose adding a Distillery recipe to break down fertiliser into useful gases.

Something similar to output of wood gas with higher methane output and no ethylene:

**Single Block Distillery**
Input - Liquid Fertiliser 6548:775 - 200L

Output -
Circuit 1: CO2 Gas - 10L
Circuit 2: Water - 52L
Circuit 3: Methane Gas - 98L
Circuit 4: Carbon Monoxide - 10L
Circuit 5: Hydrogen Gas - 30L
(adds up to 200L - replaced Ethylene with Water from wood gas)

**Tower Distillery**
Input - Liquid Fertiliser 6548:775 - 1000L

Output 1: CO2 Gas - 50L
Output 2: Water - 260L
Output 3: Methane Gas - 490L
Output 4: Carbon Monoxide - 50L
Output 5: Hydrogen Gas - 150L

**Comment by bartimaeusnek** [comment]
ID numbers are world unique, so it doesnt help posting them here, if you dont specify the world where they are used in...

**Comment by Highbeam** [comment]
That's the ID I see when I mouse over in the fertiliser fluid extractor recipe:
![2018-08-29_14 49 19](https://user-images.githubusercontent.com/32101225/44788593-bed8e980-ab9a-11e8-82b1-8e4cc2a765c9.png)

Overworld/Epsilon

**Comment by Bluebine** [comment]
The IDs don't matter though, you can just say fertiliser and people will be able to find it in NEI.
(just keep in mind that it' spelled fertiliser, NOT fertilizer. That might need fixed? is that a real word or a typo? IDK)
But either way, I like the idea. I'm not sure how powerful it would be, but with those numbers, I don't think it'll be overpowered.

**Comment by richardhendricks** [comment]
Those outputs just don't seem that useful to me.  What would you use them for that is not already being met?

**Comment by Highbeam** [comment]
Bluebine where did you see Fertilizer (with a Z) ?  Fertiliser is british english and Fertilizer is american.

@richardhendricks my proposal is more of a request for a use of fertiliser liquid since there isn't a use for it at the moment.  More methane will be useful for sure.

My storage has 70k ic2 fertiliser in and nothing much to do with it :)
