### ISSUE TITLE
Suggestion: Increase energy tier to melt Neutronium

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/GT-New-Horizons-Modpack#3545]
#### Which modpack version are you using?
2.0.4.6
#
#### What did you try to do, and what did you expect to happen?
Had to make a bunch of neutronium plates.

Noticed that it was like a tiny, tiny tiny fraction of energy to melt them and solidify instead of bending.   Kinda seems like a bug by just how energy cheap it is in contrast to bending.
#
#### What do you suggest instead/what changes do you propose?
Increase energy cost of melting neutronium to be closer to the cost of bending.

**Comment by Dream-Master** [comment]
Some recipes are autogened others are manual added.

**Comment by 0lafe** [comment]
The idea is you only do that, no one bends/lathes/extrudes or whatever else there is. Always extract then solidify. It's already 250s per ingot at ZPM, which is pretty slow compared to other ingots.
