### ISSUE TITLE
Crash/Kick when harvest infused seed from Thaumic Tinkerer

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/GT-New-Horizons-Modpack#3548]
#### Which modpack version are you using?
2.0.4.9
#
#### If in multiplayer; On which server does this happen? 
SP and private MP
#
#### What did you try to do, and what did you expect to happen?
Try to harvest mature infused seed from Thaumic Tinkerer to refresh soil and get loot
#
#### What happend instead? (Attach screenshots if needed)
Crash on SP.
Kick from MP, didn't get no seeds/loots

Crash report : [Here !](https://pastebin.com/2e6ZBL18)
#
#### What do you suggest instead/what changes do you propose?

Try to fix it (this issue make infused seed useless) => I will do more test tomorrow about that.

**Comment by bartimaeusnek** [comment]
Please re-test this, the crashlog appears to be a random crash. Does it apply to all Seeds or only special ones? Does it ever worked?

**Comment by DV666** [comment]
It's not random crash, that's appear every time when i try to broke this seed ^^.

> Does it apply to all Seeds or only special ones? 
The problem here i am stuck with primals seeds (aer, aqua, perditio, ordo, terra, ignis) because when i harvest them, they didn't drop residue on soil (forget to mention that, sorry).. seeds/loots either, as i said.
So i can't mutate seeds :(

> Does it ever worked?
Nope :( But i already use theses seeds on another modpack and hadn't no issues/crashs (with build ThaumicTinkerer-2.5-1.7.10-51)

**Comment by DV666** [comment]
Test with build 517 ([Available here](https://openeye.openmods.info/mod/thaumictinkerer/unspecified)) => Works perfectly.

**Comment by CalterOK** [comment]
This error does not occur if the seeds are collected as otherwise (water flow, golems, etc.).

**Comment by Barokko** [comment]
I investigated the problem. Cause of crash is the "race" between breakBlock() and getDrops() method in class thaumic.tinkerer.common.block.BlockInfusedGrain

breakBlock() method deletes related TileEntity from the world, but getDrops() method depends on the tile's fields. In case of manual harvesting breakBlock() called first.

Hotfix is saving the reference to TileEntity in block's private field. But block and entity interaction should be refactoried on the long term imo to prevent ambiguous behavior.
