### ISSUE TITLE
Thaumcraft Copper Nuggets not converyor-belt accepted into Macerator

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#3550]
#### Which modpack version are you using?
2.0.4.9
#
#### What did you try to do, and what did you expect to happen?
Use a conveyor belt (or a translocator) to transfer copper nuggets produced by alchemical duplication into the macerator. Since the macerator will work on thaumcraft copper nuggets as well as GT copper nuggets, this ought to work.
#
#### What happened instead? (Attach screenshots if needed)
It wouldn't transfer, so I had to move ~40k nuggets into my inventory to convert them to GT nuggets
#
#### What do you suggest instead/what changes do you propose?
Please fix this minor bug 😃

**Comment by Teirdalin** [comment]
Had this issue with my bee lab actually with magic bees nuggets, a workaround is to move them into a barrel or chest, then have then pulled out via a GT pipe and conveyor module.  Unless you already have them going into a GT pipe- in which case nevermind. lol
