### ISSUE TITLE
Beet to sugar in macerator

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/GT-New-Horizons-Modpack#3556]
So a pam's beet with a mortar makes a sugar but there seems to be no macerator version of this recipe. Could we add this?

**Comment by Dream-Master** [comment]
yes we can :)

**Comment by bartimaeusnek** [comment]
@Dream-Master we actually removed the macerator recipe in favor for the sugar beet...

**Comment by ljjmrlion** [comment]
Should it be removed from the mortar then? Also I feel like sugar beets should be more of a better method than beets but while keeping beets

**Comment by richardhendricks** [comment]
It should be removed from the mortar.  A normal beet does not produce any sugar whatsoever.  We can change it to be 4 sugar from 1 sugarbeet, or whatever 1/2 of the extractor recipe is for sugarbeets.
