### ISSUE TITLE
Ethereal Familiar improvement bug

### ISSUE THREAD

**Issue by Vernam** [GTNewHorizons/GT-New-Horizons-Modpack#3568]
#### Which modpack version are you using?
2.0.4.9
#
#### If in multiplayer; On which server does this happen? 
myself 
#
#### What did you try to do, and what did you expect to happen?
tried to improve the familiar with infusions
#
#### What happend instead? (Attach screenshots if needed)
Infusion does not start at all, everything is laid out according to a recipe from NEI
![screenshot_3](https://user-images.githubusercontent.com/39298269/45075849-1920ff80-b0f1-11e8-96f4-60519ba05369.png)
![screenshot_5](https://user-images.githubusercontent.com/39298269/45075858-1faf7700-b0f1-11e8-9a7c-cb62d5877c66.png)

#
#### What do you suggest instead/what changes do you propose?
I would like the infusions to be available (all infusions with an improvement in the familiar)

**Comment by Dream-Master** [comment]
It must be change in gadomancy code.
@bartimaeusnek any idea if and how ?

**Comment by Vernam** [comment]
when working with a recipe, I took into account that the essential essences in the recipe should be of the same aspect from which the familiar was created. But I tried also with ethereal essences, the infusion was not started either. So I do not quite understand what the problem is and why the infusion does not start

**Comment by DoomSquirter** [comment]
I wanted to make one of these.  I might give it a go and post results

which infusion did you try?

**Comment by DoomSquirter** [comment]
ah ok arc amplification I guess

**Comment by bartimaeusnek** [comment]
@Vernam @Dream-Master If the Infusion does not start at all, something is not right with the Items placed on the Altair. The Recipe has to match exactly the metadata/NBT data of the Items, especially the Item in the middle, havent looked that deep into Gadeomancy code to tell what could cause this... I think it might be some strange metadata/NBT data bug with the Ethereal Familiar.

**Comment by DoomSquirter** [comment]
I tried arc amplification and sensitivity boost.  neither started

**Comment by DoomSquirter** [comment]
couple other things.  looked at the gadomancy script.  you mainly just change the research stuff in there 

also, I am on 4.6

I just went through gadomancy's git and see nothing in there even remotely resembling this issue so I have to assume something in gtnh is causing this.  wierd yes, but likely, maybe.

**Comment by Vernam** [comment]
Yes, as expected) maybe a bug with the familiar at the center of the infusion? but I could not identify it visually, although I tried. so I wrote here only when I tried everything I could.

**Comment by Vernam** [comment]
I hope this can somehow be solved .. I would like to get such a familiar, because the mechanics are interesting and quite pleasant)

**Comment by fabiobuhr** [comment]
Problem persists, was there any solution to the this ticket?

**Comment by ianlavr** [comment]
Yep still persists
