### ISSUE TITLE
broken object from the infused seed which crashes game

### ISSUE THREAD

**Issue by Vernam** [GTNewHorizons/GT-New-Horizons-Modpack#3569]
#### Which modpack version are you using?
2.0.4.9
#
#### If in multiplayer; On which server does this happen? 
myself
#
#### What did you try to do, and what did you expect to happen?
I made a couple of infested seeds precantatsio. after a long growth they give a pair of shards. Together with shards, a broken object can fall from them, which closes the game, when trying to go to the server - similarly. While such an item in the inventory, go to play it is impossible. It also breaks the game even if you do not pick up the given object, but stand in a small radius near the seed at the time when the golem collects the ripe seed. If such an object falls into the world, in a small radius, everyone breaks the game (the item despawns after going back to the server). In this case, to enter the game is not a problem, since the broken item was not in inventory
![screenshot_13](https://user-images.githubusercontent.com/39298269/45076302-7a959e00-b0f2-11e8-93c7-9cdb83c7ec10.png)
![screenshot_14](https://user-images.githubusercontent.com/39298269/45076312-7d908e80-b0f2-11e8-9ea1-e8104013d08e.png)
![screenshot_18](https://user-images.githubusercontent.com/39298269/45076318-81241580-b0f2-11e8-8d8b-7af819db54bf.png)
![screenshot_17](https://user-images.githubusercontent.com/39298269/45076325-841f0600-b0f2-11e8-84cb-0b740185151d.png)
if you look at the drowers in which this item is located and you open the inventory - the work of several mods is disrupted (Nei disappears from the side, the inventory becomes clean), but all this is visual and only while you look at the drowers with the broken object inside.
I suffered 3 times from this item, I had to delete the inventory ..
it was extremely difficult to capture what is breaking the game, it took a lot of luck in the hope of catching the object in the drower
124/5000

#
#### What do you suggest instead/what changes do you propose?
if there is such an opportunity, I suggest removing this broken object from the game so that it does not exacerbate and worsen the game with such problems as closing the modpack

**Comment by Dream-Master** [comment]
I see Gt++ add some new aspects not sure if they have names or not.

**Comment by draknyte1** [comment]
>I see Gt++ add some new aspects not sure if they have names or not.

They're duplicates of the GT aspects, so should work fine.
The Meta on that shard looks like Short.MAX_VALUE, which is the wildcard meta..
What mod adds these seeds & shards? I can take a look at where the issue is stemming from..

**Comment by Vernam** [comment]
seed is added to the taum testerer. Essences from gt ++ added normally exist in the form of ethereal essences as well as all other types of taumkraft. 
![screenshot_7](https://user-images.githubusercontent.com/39298269/45109338-ebb37080-b147-11e8-9ef4-05b5c8ee7f1c.png)

By the way, this same precantacio seed sometimes gives a drop in the form of drained shard from gt++ that do not have an application. But with them everything is also normal, they simply do not have applications .. 
![screenshot_1](https://user-images.githubusercontent.com/39298269/45109351-f968f600-b147-11e8-8280-921a276a662a.png)

So the problem is definitely not in the essences of gt++

**Comment by Vernam** [comment]
I have no idea what mod adds this broken object on the first screenshots .. if I could pick up and look, but alas, as I wrote, I have to delete the inventory, it's only necessary to take such an item. Otherwise, it's impossible to play, the game breaks (

**Comment by draknyte1** [comment]
>  drained shard from gt++

Curious, because they don't exist if Thaumcraft is loaded..
They're used to make Elemental shards, to then macerate to Aer/Terra/Ignis/Water dust from GT.
They serve no other purpose whatsoever, as these 4 dusts are used to make a GT++ Alloy.

**Comment by Vernam** [comment]
An attempt to open a drawer inventory, where you can insert upgrades - has failed. I wanted to try to see from what fashion the subject, but the game immediately broke down

**Comment by Vernam** [comment]
Be that as it may, the problem is not in a drowned shard. The seed gives things with a shard oredict, and once in your mod there is such an object - the seed has a chance to give it as a drop. This I explain how I got them) But again, they are all right

**Comment by draknyte1** [comment]
It's just a side curiosity.
Can you provide a log file at all?

If it gives *Anything* that is a shard type, it's grabbing an invalid `WildCard` item from another mod.. Could be an easy fix.

**Comment by draknyte1** [comment]
Should be fixable. 
I'll add it to my to-do list for tomorrow, as I'm about to sleep. (3:30am here in Aus)

**Comment by Vernam** [comment]
good night)) Thanks for the sympathy and help! This problem caused a lot of trouble)

**Comment by draknyte1** [comment]
So yeah, some mod is definitely providing an instance of the Thaumcraft shard item with a Short.MAX_VALUE (Meta Wildcard Value) meta. This should never occur, for anything besides recipe checks..

I am not yet able to determine where it comes from though. But I'll keep this updated as I find out more.

**Comment by Kiwi233** [comment]
@draknyte1 
Can you add those crop added by GT in the file named gregtech.lang, so that I can translate them.

**Comment by thraskUlgo** [comment]
Experienced this bug today. 
A way to replicate it is to breed the praecantatio seed and then harvest it, if it spawns it ll crash the world instantly and crash again on further attempts to load the world.

[crash-2021-09-10_22.01.19-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7146107/crash-2021-09-10_22.01.19-client.txt)

**Comment by thraskUlgo** [comment]
tested all the seeds and the issue appears also on the arbor seed.

[crash-2021-09-11_01.40.38-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7147481/crash-2021-09-11_01.40.38-client.txt)

**Comment by ScriptedPiky** [comment]
Question. Which seeds are these from? GT++ or Thaumic Tinker?

**Comment by thraskUlgo** [comment]
they are from Thaumic Tinkerer

**Comment by ScriptedPiky** [comment]
Ah yeah, I remember that mod from InfiTech & it was both overpowered (some of the seeds), and some could crash/break the server with a null or broken item. I have a feeling that mod should be looked at more in-depth at some point to figure out how it works. One of the more obscure parts of any mod it seems.
