### ISSUE TITLE
Garnet bee

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#3573]
Need to add a Garnet bee, so players can source manganese and chrome.

**Comment by Dream-Master** [comment]
there is one so far i know. I will rework bees and put them into gt code next release.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/45225061-e414d880-b2bb-11e8-9ba2-57b9d7aa7f69.png)
![image](https://user-images.githubusercontent.com/2970688/45225067-eaa35000-b2bb-11e8-8842-90a30ec1f634.png)

@richardhendricks

**Comment by Prometheus0000** [comment]
These are in already, if they don't work or something, it can be reopened.
