### ISSUE TITLE
Talisman of Nourishment doesn't work properly

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/GT-New-Horizons-Modpack#3578]
#### Which modpack version are you using?
2.0.4.6 

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
Player wears talisman on nourishment and should automatically eat food on the hotbar to refill hunger

#
#### What happend instead? (Attach screenshots if needed)
Talisman won't eat food that gives well fed buff, due to the hunger mod thats basically all foods.

#
#### What do you suggest instead/what changes do you propose?
Fix it, please.

Apparently theres a fix posted here: https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/760

![image](https://user-images.githubusercontent.com/34566584/45143032-6c807400-b1fd-11e8-875d-8d9a3a05c1da.png)

**Comment by AlexBucket** [comment]
Apparently the issue comes from Hunger Overhaul providing all foods with a 'well fed' buff after eating them. This stops the amulet from working.

Theres an option in the Hunger Overhaul config to turn off the buff, but the buff is kinda important early game. From what I've come across, someone needs to come up with a fix that will ignore the well fed buff in the nourishment amulet code.

**Comment by Ghengis88** [comment]
any progress on this?

**Comment by Ghengis88** [comment]
or is there any food item that works?

**Comment by sthegreat** [comment]
It works for me on all foods from vanilla or Pam's, just not foods from GT. Beef wellingtons are good.

**Comment by Ghengis88** [comment]
Beef wellington dont work for me, what version are you playing?

**Comment by sthegreat** [comment]
2.0.5.1

**Comment by Ghengis88** [comment]
hm :/ why wont it work for me then :(

**Comment by Dream-Master** [comment]
did you both test it in smp or in singleplayer modus too? @Ghengis88 @sthegreat

**Comment by Ghengis88** [comment]
no i have only tested on Epsilon server

**Comment by Dream-Master** [comment]
Can you test it in sp too @Ghengis88 ?
