### ISSUE TITLE
Radon decay quest can't be claimed

### ISSUE THREAD

**Issue by Vernam** [GTNewHorizons/GT-New-Horizons-Modpack#3582]
#### Which modpack version are you using?
2.0.4.9
#
#### If in multiplayer; On which server does this happen? 
myself
#
#### What did you try to do, and what did you expect to happen?
wanted to close the radon quest
#
#### What happend instead? (Attach screenshots if needed)
it can not be closed
![screenshot_3](https://user-images.githubusercontent.com/39298269/45211519-2f6abf00-b29b-11e8-8a47-1ae654411fac.png)

#
#### What do you suggest instead/what changes do you propose?
Radium 226 dust collapses instantly when it hits the inventory, the questbook does not have time to detect this dust. Since the quest is considered the main, this is not a pleasant problem .. Perhaps there is an option to remove the requirement of a specific dust from the quest list

**Comment by Dream-Master** [comment]
@Vernam did you play sp or mp. I checked it in spand it works well.

**Comment by Dream-Master** [comment]
@draknyte1 any idea why Rasium 226 collapses and havent any decay time ?
