### ISSUE TITLE
Suggestion: Make OPPM (Package Manager) floppy disk craftable.

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/GT-New-Horizons-Modpack#3602]
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Get a OPPM (Package Manager) disk so that I can use some of the basic opencomputers devices like the 3D printer.

Find a way to get the floppy.
#
#### What happend instead? (Attach screenshots if needed)
Ended up making a suggestion on github, after exploring about 20 or so dungeons; checking all my old storage, and asking if anyone else found one; and after checking the NEI.  
Didn't actually find any opencomputers disks in general that weren't blank.
#
#### What do you suggest instead/what changes do you propose?
Increase dungeon chance of opencomputers floppies, or add a crafting recipe for the OPPM disk.

**Comment by 0lafe** [comment]
![2018-09-10_15 51 12](https://user-images.githubusercontent.com/21280852/45320718-706c0900-b511-11e8-9de2-7de64a7e6801.png)
This?

**Comment by Teirdalin** [comment]
Oh,  guess there's a recipe for it in the later version.  Thanks Olafe. :D

**Comment by bartimaeusnek** [comment]
@0lafe the first one should not exist lol
