### ISSUE TITLE
Wrong Undergroundfluid ID in BarnardaE C

### ISSUE THREAD

**Issue by FallDark** [GTNewHorizons/GT-New-Horizons-Modpack#3608]
#### Which modpack version are you using?
2.0.5.1
#
#### What happend instead? (Attach screenshots if needed)
![20180911223714](https://user-images.githubusercontent.com/25171639/45367198-4e5aaf80-b613-11e8-944b-90e35a87d1c8.png)
![20180911223612](https://user-images.githubusercontent.com/25171639/45367262-6e8a6e80-b613-11e8-80a8-98e1fb3e4146.png)
It should be BarnardaE C if you not sure you can check GalaxySpace dimensions.conf

One more Question
About #2854 
![20180911224204](https://user-images.githubusercontent.com/25171639/45367621-45b6a900-b614-11e8-89e1-d42b3bd68554.png)
Is that NqX isn't the Naquadria?

**Comment by Dream-Master** [comment]
ok will check and yes it should be naquadria @FallDark

**Comment by FallDark** [comment]
So VegaB and BarnardaC should be Molten Naquadria not the Enriched Naquadah
![306066295936dff9](https://user-images.githubusercontent.com/25171639/45421587-1493b280-b6c0-11e8-80bc-2a8762370d9b.png)

**Comment by Prometheus0000** [comment]
I assume this is obsolete considering naq was removed from pumping? See #5980
