### ISSUE TITLE
Bug recipe of Nano boots of the traveller

### ISSUE THREAD

**Issue by Vernam** [GTNewHorizons/GT-New-Horizons-Modpack#3609]
#### Which modpack version are you using?
2.0.4.9
#
#### What did you try to do, and what did you expect to happen?
frend tried to infuse boots to nano boots of traveller
#
#### What happend instead? (Attach screenshots if needed)
infusion doesn't start.
#
#### What do you suggest instead/what changes do you propose?
as i understood - problem with ID Electric boots of the traveller (in the center of infusion)
![screenshot_7](https://user-images.githubusercontent.com/39298269/45371070-4c342900-b5f2-11e8-8844-f8f4e109f2a0.png)

**Comment by bartimaeusnek** [comment]
you need to charge and discharge the energy crystal and the nano boots. will fix recipe asap

**Comment by Ghengis88** [comment]
crystal can be charged and it will start
