### ISSUE TITLE
[Suggestion] Changing the usage of PBI, and adding a properly high-tier plastic

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#3611]
Preface: 0lafe has made it known that he doesn't like current PBI as a high-tier plastic. 

PBI is made in GTNH similar to how it is made in real life, which is awesome. However, that means that it is made with low- and mid-tier ingredients and just has high eu/t costs, and it isn't a good fit for being a ZPM+ tier plastic.
For that reason, PBI should be a mid-tier plastic, same as PTFE, and usable as an alternative to PTFE. It's a lot more complicated to make (compared to PTFE), but because it doesn't need Fluorine, it has a niche. Think kindof like Styrene-Butadiene Rubber and Silicon Rubber.

At high tiers, stuff starts to resemble sci-fi. A plastic made with ingredients like molten naquadah, molten neutronium, and uum should make have a catchy name like Plasteel or Naqtec. Fictional ingredients in, fictional products out, and the processing can be as creative as possible.

**Comment by Zoko061602** [comment]
What about  adding a new fictional material like "Uridium" (Symbol Ud would be nice).
You could Fusion Reactor from 2xTritanium and 1xRadon and has therefore a atomic nuber of 168.
 (I choosed 168 so that it is part of the carbon group)
It can then be used to build some polymeres, similar to carbon.

**Comment by Krispion** [comment]
Perhaps use PBI for space suits and as an alternative material for hazmat suits?

**Comment by Dream-Master** [comment]
Now is PBI IV (7680 eu/t). If this is to high would EV ok ?

**Comment by 0lafe** [comment]
>What about adding a new fictional material like "Uridium" (Symbol Ud would be nice).
You could Fusion Reactor from 2xTritanium and 1xRadon and has therefore a atomic nuber of 168.

If that was chem reacted with stuff or cracked or something, gonna need a bunch of mid stage products for it though considering there's none for this yet
