### ISSUE TITLE
Molten Polybenzimidazole process (dimethylbenzene single machine problem)

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#3620]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Dimethylbenzene only has Single Machine recipes in the Distillery and Chemical Reactor.

Can the recipes be added to Distillation Tower / LCR?

![2018-09-13_16 51 41](https://user-images.githubusercontent.com/32101225/45496279-5a5e8280-b775-11e8-94f5-dbee14175092.png)

![2018-09-13_16 51 57](https://user-images.githubusercontent.com/32101225/45496292-621e2700-b775-11e8-8361-1112c7d8ba1a.png)

And for giggles, I did a representation of the new process in SFM:

![2018-09-13_16 39 50](https://user-images.githubusercontent.com/32101225/45495961-ae1c9c00-b774-11e8-90e8-651c564a748c.png)

**Comment by Highbeam** [comment]
Distillation Tower issue already here:
https://github.com/GTNewHorizons/NewHorizons/issues/3489

**Comment by Highbeam** [comment]
For the Large Chemical Reactor:

1000 Benzene + 1000 Methane (circuit 12) = 1000 Dimethylbenzene

**Comment by mitchej123** [comment]
Is this still an issue?
