### ISSUE TITLE
Multiverse-Core worlds have no ore veins? New GTU version problem?

### ISSUE THREAD

**Issue by plaguewolf** [GTNewHorizons/GT-New-Horizons-Modpack#3631]
not sure if this is the right place to ask questions of this nature, so sorry in advance for troubling you.

#### Which modpack version are you using?
GTNH 2.0.4.9
#
#### If in multiplayer; On which server does this happen? 
private server, localhost, latest thermos

#
#### What did you try to do, and what did you expect to happen?
#
#### What happened instead? (Attach screenshots if needed)

/mv create Mining NORMAL -t {RWG/BIOMESOP/etc} even left it at NORMAL by itself, world is created, biomes are correct as per world generator type, but no ore veins are spawned, just random ores from other mods, Railcraft dark diamond in abyssal, emeralds, draconium, etc. overworld that generated naturally on server start has veins though, so im thinking its a MV problem. GTNH and MV-Core worked prior to 2.0.4.2 (???) i think that's the last version i used as a server

#
#### What do you suggest instead/what changes do you propose?
just wondering if this is an isolated thing, ie: is it something specific to my setup, or if this is a known problem, something in the new version of gregtech-unofficial breaks support with multiverse.

**Comment by richardhendricks** [comment]
@bartimaeusnek ?
Which ores spawned before in 4.2?

**Comment by plaguewolf** [comment]
um, all the GT veins, i guess.
on the previous server creating a mining world was as easy as:
/mv create Mining NORMAL -t {worldgenerator}

ores spawned just like in the overworld and such. now i cut a swath of land with worldedit along ore chunks to check if veins spawned, no veins.

**Comment by bartimaeusnek** [comment]
@plaguewolf which GT, this one or the official?

@richardhendricks 
https://github.com/GTNewHorizons/GT5-Unofficial/blob/55abb429e5516587fe8946a1d1643e882e6f08c7/src/main/java/gregtech/api/world/GT_Worldgen.java#L63

this might be the problem?

**Comment by plaguewolf** [comment]
the gregtech that comes packaged with GTNH 2.0.4.9, so gregtech-5.09.32.34

**Comment by bartimaeusnek** [comment]
@plaguewolf yes, its implemented so GaGreg handles everything else and we dont have double code. I'd suggest writing a mini-mod that enables GaGreg for your specific dims aswell...

**Comment by draknyte1** [comment]
Not our job to support Bukkit Plugins when we write forge mods.

**Comment by plaguewolf** [comment]
well, i guess that's that then. feel free to close the issue. i'll try to bring it up with MV-Core people, but i suspect i already know the answer.

**Comment by bartimaeusnek** [comment]
@plaguewolf this will be changed soon anyways, when GaGreg is merged into GT5U

**Comment by mitchej123** [comment]
> @plaguewolf this will be changed soon anyways, when GaGreg is merged into GT5U

Working on that, should have a PR out in the next week.  Then all ore gen will go through GT5U :-D

**Comment by plaguewolf** [comment]
Neat, im sure many  server owners will like that, what with the resource consumption of a modpack like GTNH one of the primary ways to keep lag down is with an enforced worldborder. Doing that kind of requires access to a mining dim of some sort, maybe aroma1997 mining dim, if it needs to be forge based. In particular I've always liked multiverse for its ability to generate fresh worlds with whatever world generator you want to use, then simply set up a warp or make the spawn perms accessible.

I mean, I'm sure it wouldn't be too hard to add support for isGenerationAllowed() to something like MV, but frankly it's beyond my ability to do so. Freely admit I'm no programmer, just wanted to bring it to the attention of the pack devs.

While I'm thinking about it, when you refer to GaGreg, i've been assuming you mean the GalactiGreg addon, is that correct?

**Comment by bartimaeusnek** [comment]
GalactiGreg yes.

**Comment by mitchej123** [comment]
haha, still somewhere on the list, but haven't gotten to it
