### ISSUE TITLE
Make neutronium fusion viable

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#3648]
#### Which modpack version are you using?
2.0.5.1

#### What do you suggest instead/what changes do you propose?

Right now there's 2 ways to get neutronium. The ore, and fusion. The ore is avaliable in huge amounts and the only real bottleneck is the ebf time. 250s at ZPM takes a while, more than most things you'll have made, but it's manageable. Now fusion at about 1A ZPM in the mk3 reactor, takes 60s every L of molten neutronium. That's 144min per ingot, almost 35x slower than the ebf. However neutronium in the fusion reactor takes americium, which itself is a fusion recipe. If you wanted to match the speed of a single zpm ebf, you would need to run 36 fusion reactors, using 36A zpm, costing 4x the neutronium amount in americium and naquadria, with the americium cost being an ingot of plutonium 241. 

If the fusion recipe is made more reasonsable (72x the recipe currently for the same time?) then neutronium can be a fun lategame material that isn't just an ebf time sink. You'll need 2 reactors to make an ingot, but it will be using a more tier appropriate machine and not being a boring ore. Also, almost everything you do with neutronium is with it as a fluid then solidifying it into different parts. The fusion reactor makes fluid neutronium which just makes more sense for its uses. If the recipe is changed to be more manageable, I think the ore should be removed. It would force more fusion reactors for things other than just power, which they're almost never used for.

**Comment by NeroOneTrueKing** [comment]
I see that sneaky call to remove neutronium ore in there. 😄 
How about (in addition to your suggestions) replacing neutronium ore with an ore called "Neutronite", and it acts with respect to neutronium as rutile is to titanium (lots of extra steps). A player could mine out T5 planets for small neutronite ores (instead of small neutronium ores) and do some extra processing to obtain neutronium.
The fusion method is then a 'reward' for getting to a high tier and be able to more easily produce neutronium.

**Comment by 0lafe** [comment]
I mean, I don't really have anything against that. As long as it's some slow processing that takes longer than fusion. Other than the field gens for fusion, do you need neutronium pre mk3? I think I used a ton for DE but that's about it

**Comment by Cinobi** [comment]
Don't forget about americium itself. It need Lutetum, can be obtained with thorium rods burning in reactors  only. That sucks, and need to be changed.

**Comment by 0lafe** [comment]
>Don't forget about americium itself. It need Lutetum, can be obtained with thorium rods burning in reactors only. That sucks, and need to be changed.


Except americium plasma takes like 1 Pu241 and some H2

**Comment by Cinobi** [comment]
> > Don't forget about americium itself. It need Lutetum, can be obtained with thorium rods burning in reactors only. That sucks, and need to be changed.
> 
> Except americium plasma takes like 1 Pu241 and some H2

Doesn't this recipe need ZPM as well? =D add it to ur calcs than =)

**Comment by 0lafe** [comment]
I guess, but it's an ingot every 3.2s and neutronium would be like an ingot every min/2min from 16ingots of americium, so a single reactor doing americium could power 4-8 doing neutronium, for 0 energy cost as burning the americium plasma for molten americium makes more power than making the plasma. It does become 4 Pu-241 and 4 naquadria per neutronium, but that's not that bad
