### ISSUE TITLE
Request for public vote to Reboot server

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#3661]
We are unfortunately cursed with what I assume is Galacticraft causing bad TPS.  Often when one of decides to visit the planets, the server TPS slowly crawls to low figures...

Today, TPS was 17; I flew to IO to pickup the NASA schematic and I watched the TPS go down to 5.

I'm not sure what reboot system we are using but is it possible to enable public vote of restart?

https://forums.spongepowered.org/t/mmcreboot-a-server-restart-timer-and-voting-system/16503

**Comment by Namikon** [comment]
I'm not a fan of player-based votes for something like a restart. If TPS is low, there is a reason for it.
Like for the SpaceDims, it's sufficient to just enter the Dimension which has a high tick-time, and TPS stabilizes within seconds.
But on the other hand; I can't see anything problematic with just trying it. So have fun; We'll try this on Epsilon first. And if it really is what you want to have; I won't stop you from restarting without reason.

Get the command help with /vote.

I defined the ranks as follows:
Everyone can vote yes or no, dweller+ can start votes for kick/ban/restart, and elite+ can stop any vote with a veto.

**Comment by richardhendricks** [comment]
Dumb Q - if just having a player present in a dim is enough to prevent GC from crushing TPS, what about placing an admin anchor in each dimension along with a magnum torch (or equivalent, to prevent spawns)?

**Comment by Dream-Master** [comment]
Magnum torch not working on gc mobs so far I remember.

**Comment by Cinobi** [comment]
> t's sufficient to just enter the Dimension which has a high tick-time, and TPS stabilizes within seconds.

Players can't get this info, u know ;P

**Comment by Highbeam** [comment]
You could claim the area around the admin anchor with a town and mob spawn in turned off

**Comment by Namikon** [comment]
All this was tried already. When Drobac had built the Stargates; those areas had anchors and were loaded. Same problem.

**Comment by richardhendricks** [comment]
Hmmm... What about setting up a low-tier fluid drill?  That should use a fakePlayer right?  Maybe there is some difference with how anchors operate.

**Comment by Prometheus0000** [comment]
This is obsolete, right?

**Comment by boubou19** [comment]
yup
