### ISSUE TITLE
[EMT] Nano/Quantum Wings wrong protection value + mismatch name solar panel

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/GT-New-Horizons-Modpack#3663]
Yesterday, i tested some stuffs from EMT and i think they need some reworks because.... pretty weird imo.

- First, with Nano Boots of Traveller or Wings or both (and Quantum too i suppose), it's a pain to take Elevator from Openblock (already said by on this post [here](https://github.com/GTNewHorizons/NewHorizons/issues/2607#issuecomment-366873585) but issue still here). The only way to activate the elevator with theses boots is to jump a second time when you land on the block.

- I think Nano Boots of Traveller use too much energy to nullify fall damage. Maybe reduce by half, idk.

- About Wings (specially with Thaumium and Nano) : i don't know what the purpose about that. You can reach high heights but you take sooooo much damage when you landing. 
I know with Nano Boots of Traveller you can reduce damage but it's totally insane lol and as i said before, the consumption is way too high, even if you flap(s) just landing.
Moreover, you can slow your fall with wings with shift... but that's reduce fall damages : bug ?

- ~~I see someone wish enchantments must be added on EMT Tools (#3478) ! That's will be cool to add like Protection but we need to blacklist some of them like "Haste" on boots [otherwise](http://cdn.ebaumsworld.com/mediaFiles/picture/602759/81508430.png)...~~ Nevermind, you can use infusion enchantment and Haste on boots not OP as intended, cool !

- The sound flap from wings is annoying xD

So.... weird items or maybe i didn't understand something.

**Comment by DV666** [comment]
1. That's sad :( i will use Travel Anchor instead, np.
2. 75% ?! .... Oh, sometimes i lose like 600.000 EU when i landing xD (and i didn't fall from the moon)
3. But when you use the glide with wings to slow your speed, it's intended to lose 5 hearts or more ? Or a lot of energy from Nano Boots ? What the purpose to use this ? I didn't see the difference with glide or not ^^
4. I can reduce the sound but unfortunately, it's from "Hostile Mobs" sound.

**Comment by DV666** [comment]
I find another bug (@bartimaeusnek) with Nano Wings / Quantum Wings, protection provided by theses are false.

Nano/Quantum Wings said Protection : 8 but only give 5 (less than Thaumium xD)

![2018-09-26_19 31 54](https://user-images.githubusercontent.com/17729817/46097787-116deb80-c1c3-11e8-8654-82f9a832a390.png)
![2018-09-26_19 32 03](https://user-images.githubusercontent.com/17729817/46097789-129f1880-c1c3-11e8-995d-d9eb27ab3a03.png)
![2018-09-26_19 32 10](https://user-images.githubusercontent.com/17729817/46097792-13d04580-c1c3-11e8-88f3-d2df3a95f207.png)

**Comment by DV666** [comment]
Bump : Nano/Quantum Protection still bug (5 instead of 8), can we fix that for next update please ? :]

For previous statements i said for wing, the mantle of the raven from Witching Gadget is very usefull so... no need to balancing.

**Comment by DV666** [comment]
Sorry to bump this topic again but... bug still here ^^'

> Nano/Quantum Protection still bug (5 instead of 8)

Furthermore, i have some suggestions about new EMT solar panels.
I suggest to edit theirs names, to match with previous, for example we have : 

### Old
**Ignis** infused compressed solar panel
**Ignis** infused **double** compressed solar panel
**Ignis** infused **triple** compressed solar panel

### New 
**Quintuple** compressed **Ignis** solar
**Octuple** compressed **Ignis** solar

Just a little reversal and missing "panel" at the end. Not very convenient for NEI search. 
I suggest theses changes :
**Ignis** infused **Quintuple** compressed solar panel
**Ignis** infused **Octuple** compressed solar panel

That's would be perfect.
And another request : possible to get different texture for quadruple/quintuple/sextuple/septuple/octuple ?

Thanks in advance :}

**Comment by DV666** [comment]
It's possible to add this ticket for 2.0.7.6 Checklist ? @richardhendricks @bartimaeusnek @Dream-Master 

Here a to do list :
- Fix protection value from Nano/Quantum Wings
- Make EMT solar panel name match with all tiers (T1 to T8)
- Thaumium drill uncraftable -> #2694 
- Diamond Chainsaw and Iron omnitool uncraftable -> #4008
(- Different texture for quadruple/quintuple/sextuple/septuple/octuple solar panel)

Plz :}

**Comment by richardhendricks** [comment]
For 2.0.7.6 I want to focus on all the delinquent recipe changes.  This sounds like more work than that, so I would prefer 2.0.7.8 for it.

**Comment by DV666** [comment]
Yeah np ^^ I can wait ;)

**Comment by Dream-Master** [comment]
@richardhendricks @bartimaeusnek any news here?

**Comment by richardhendricks** [comment]
EMT is bart's baby. :)

**Comment by DV666** [comment]
For informations, we can't craft Quantum Wings and Quantum Boots but Quantum Googles can be crafted.

Furthermore, Thaumonumicon says about Quantum Wing : 
"Your fall will be completely stopped when spacebar and sneak are maintained". 
It's false, you still fall slowy.

**Comment by KiloJoel** [comment]
Wings wrong protection value is still an issue

**Comment by riking** [comment]
Boots use entirely too much energy and wings [use](https://github.com/GTNewHorizons/Electro-Magic-Tools/blob/master/src/main/java/emt/item/armor/wings/ItemFeatherWing.java#L91) entirely too little energy.

Climbing from sea level to 256 takes maybe 4k EU on the wings.

**Comment by a3626a** [comment]
I recently made nano wings, and found that nano boots of the traveller uses too much energy.
Energy usage feels totally unbalanced, even considering GTNH as an expert modpack.

I have read the source code of EMT, and also did some experiments, and found this significant issue.

## Fall damage reduction is not applied to boots energy consumption.

### 1) Experiment

case a) wearing boots and wings
case b) wearing boots only

Fall 20 meters and calculate the energy usage.

-> case a and b consumes same energy (of the boots)

### 2) Source code analysis

Fall damage reduction of wings is implemented here, using `onLivingHurt` :
https://github.com/GTNewHorizons/Electro-Magic-Tools/blob/547db6d7d0b75bed10f6b2602af8d7aca0d7336e/src/main/java/emt/util/EMTEventHandler.java#L31-L41

Energy consumption of boots is implemented here, using `onLivingFall`:
https://github.com/GTNewHorizons/Electro-Magic-Tools/blob/547db6d7d0b75bed10f6b2602af8d7aca0d7336e/src/main/java/emt/item/armor/boots/ItemElectricBootsTraveller.java#L177-L204

`onLivingFall` looks like called before `onLivingHurt` so, fall damage reduction of the wings do nothing for energy consumption.


By fixing this issue, energy usage of nano boots of the traveller with nanosuit wings will decrease 75%, which makes the lifetime of boots 4 times longer.


I think this fix is not that hard. The important point is this question.
"Should fall damage reduction reduce energy consumption?"

If the answer is YES, I can make PR for this.

**Comment by riking** [comment]
Please do not comment on closed issues; if you want to advocate for an issue to be reopened use Discord, or file a new issue resummarizing the content of the previous issue.
