### ISSUE TITLE
Thaumic shard bees

### ISSUE THREAD

**Issue by Ghengis88** [GTNewHorizons/GT-New-Horizons-Modpack#3671]
#### Which modpack version are you using?

#2.0.5.1
#### If in multiplayer; On which server does this happen? 
Epsilon and SP 
#
#### What did you try to do, and what did you expect to happen?
breed a thaumic shard bee
#
#### What happend instead? (Attach screenshots if needed)
nothing, tried multiple times with enough frames to make it not mutate impossible
#
#### What do you suggest instead/what changes do you propose?
check it there is i hidden requirement and add it to NEI

**Comment by Ghengis88** [comment]
tested some more, it says it has a 10% chance and i increased the chance by x15 with 3 mugatenic frames from GT++ (x5 each)so the chance should be above 100% but still no mutation,

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/95615842-def45b80-0a36-11eb-9106-0f580687ffac.png)
