### ISSUE TITLE
Fusewood Stairs recipe mistake.

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/GT-New-Horizons-Modpack#3674]
The recipe for fusewood stairs has a random darkwood plank required

![image](https://user-images.githubusercontent.com/9472512/46109146-bc73aa80-c1ad-11e8-9e4b-71bbccb4ed27.png)

**Comment by richardhendricks** [comment]
(makes note to have them explode when you walk on them)

**Comment by Dream-Master** [comment]
Funny never saw this recipe :)

**Comment by ljjmrlion** [comment]
Bumping this as it still exists
