### ISSUE TITLE
Sero Converter Crash

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/GT-New-Horizons-Modpack#3677]
Opening the gui of the seroconverter from thaumic horizons causes an immediate CTD if you have any gregtech aspects discovered
Crashlog https://pastebin.com/MhFfpPYu
![image](https://user-images.githubusercontent.com/9472512/46110427-96500980-c1b1-11e8-830b-d924d67dc869.png)

**Comment by draknyte1** [comment]
I don't know where you get the idea that it's explicitly GT aspects, because the crash log doesn't suggest as much.

TH is a horribly coded mod, it's closed source, so nothing can really be done to fix it's issues.

**Comment by ljjmrlion** [comment]
Opening the GUI with only base Thaumcraft aspects seems to work perfectly but when I created the GT aspects and opened it then it immediately crashed. Done in singleplayer. Maybe at the very least we could add a tooltip to let people know its broken.

**Comment by Dream-Master** [comment]
There is a repo but i am not sure if this code is exact copy of the original mod(code) and/or legal to use in a public pack.

https://github.com/Hoborific/ThaumicHorizons

**Comment by ljjmrlion** [comment]
![image](https://user-images.githubusercontent.com/9472512/46177258-3ffdcc00-c280-11e8-97d2-e4ffd33ec92b.png)
According to hoborific's description of the repository it is a decompiled version of thaumic horizons.

![image](https://user-images.githubusercontent.com/9472512/46177303-691e5c80-c280-11e8-9987-87735224737f.png)
Also, here is the only "licensing" relating to the mod that exists, this was written by the original creator Kentington. As long as you do not claim the mod as your own I don't see any legal issue with modifying it. Of course I'm not an expert and if anyone has any sort of missing information I'd gladly take it into account.
@Dream-Master

**Comment by ljjmrlion** [comment]
Sources: https://minecraft.curseforge.com/projects/thaumic-horizons , https://github.com/Hoborific
