### ISSUE TITLE
Hybrid solar helmet recipe broken

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/GT-New-Horizons-Modpack#3685]
#### Which modpack version are you using?
2.0.5.1
#
#### What did you try to do, and what did you expect to happen?
Craft hybrid solar helmet. Recipe doesn't work
#
#### What happend instead? (Attach screenshots if needed)
![](https://puu.sh/BCvsG/985e478fe2.png)

**Comment by Dream-Master** [comment]
did you test with a empty gravi helmet @Lainiel

**Comment by Lainiel** [comment]
I did not. Still it would make more sense for the recipe to work with a charged helmet than a discharged one.

**Comment by Dream-Master** [comment]
sure will change
