### ISSUE TITLE
Free redstone 

### ISSUE THREAD

**Issue by Erixonich** [GTNewHorizons/GT-New-Horizons-Modpack#3688]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
I'm expecting no free redstone.
Using mixer for red alloy dust and then centrifuging it outputs free redstone.
This was mentioned in #3491
#
#### What happend instead? (Attach screenshots if needed)
.
#
#### What do you suggest instead/what changes do you propose?
Change red alloy dust centrifuge and large centrifuge recipe to 1 copper dust and 3 redstone (instead of 1 and 4)

![2018-09-29_17 19 12](https://user-images.githubusercontent.com/12836717/46246858-68b2cc80-c40c-11e8-82b4-b3b5e1a4749b.png)
![2018-09-29_17 19 25](https://user-images.githubusercontent.com/12836717/46246859-68b2cc80-c40c-11e8-8fe8-e454f977c8e2.png)

**Comment by Dream-Master** [comment]
ok will override reverse recipe.
