### ISSUE TITLE
Opencomputers microchip recipes

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/GT-New-Horizons-Modpack#3690]
#### Which modpack version are you using?
2.0.5.1
#
#### What did you try to do, and what did you expect to happen?
Opencomputers microchip tier 3 accepts only one type of EV circuit, tier 1 accepts only one type of MV circuit. All of them do not accept SMD transistors.
#
#### What do you suggest instead/what changes do you propose?
Let the opencomputer microchip recipes accept different circuits of the same tier and accept SMD transistors as well.

![](https://puu.sh/BD3vY/a3f9894a8a.png)
![](https://puu.sh/BD3vi/a47655667d.png)

**Comment by Lainiel** [comment]
Also let opencomputer screens accept SMD Transistors

**Comment by Lainiel** [comment]
Tier 1 and Tier 3 CPU also do not accept different tiers of circuits

**Comment by Dream-Master** [comment]
Yes the old oredict bug with circuits.
