### ISSUE TITLE
Mining pipe silk touch

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/GT-New-Horizons-Modpack#3696]
collecting mining pipes with my silk tinker's pick drops the right thing until I break that last piece that is bigger. Could we add a recipe to craft it back into a normal mining pipe or prevent it from happening?

![image](https://user-images.githubusercontent.com/9472512/46320405-3d66e380-c5ac-11e8-94dc-350dec7fe7cf.png)

**Comment by ljjmrlion** [comment]
This issue is still here.

**Comment by Dream-Master** [comment]
Yes old issues are easy overseen
