### ISSUE TITLE
Suggestion: Chiseled Arcane Stone Blocks.

### ISSUE THREAD

**Issue by BlackFlameTNT** [GTNewHorizons/GT-New-Horizons-Modpack#3700]
here a simple suggestion, arcane stone for building is one of the bast blocks to use for making magical place and chiseled will be a good welcome.
[![2018-10-04_02.28.45.png](https://i.postimg.cc/0QHQY3V4/2018-10-04_02.28.45.png)](https://postimg.cc/9RZCVx5P)
or
[![2018-10-04_02.48.52.png](https://i.postimg.cc/L41Yk4MB/2018-10-04_02.48.52.png)](https://postimg.cc/RqvZ4BhN)
so there is no need to change recipes or getting  arcane stone bricks without precision laser.

**Comment by Prometheus0000** [comment]
I can't even find the other blocks, are they even in the game? Are they called something other than arcane X?

**Comment by BlackFlameTNT** [comment]
they are in game but you need to change chisel config folder with arcane stone from false to true.

**Comment by Prometheus0000** [comment]
See https://github.com/GTNewHorizons/Chisel/pull/5 and #6805
