### ISSUE TITLE
Suggestions: Late Tier Bee Overhaul, New Bee Lines and More!

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/GT-New-Horizons-Modpack#3706]
#### Which modpack version are you using?
2.0.5.1
#
#### W-what are you saying? What madness is all this?!

So while still progressing in the past, the concept of infinity catalyst and infinity dust bees seemed absolutely amazing to me,  but once you get two ingots of infinity and get to the deep dark infinity becomes nothing really more than just a mild chore to get; keeping the infinity bee and catalyst bees kinda-  useless in contrast to just making it yourself, and a huge waste of effort grinding through all the bee lines.   I also noticed that some bee lines seriously don't get the love and attention they deserve and one aspect of the pack was less touched on than most in bee-kind- so why not kill four birds in one stone and make a handful of new changes and even get a new draconium bee line~

So my suggestion is basically an overhauling of the later tier bees, keeping them apiary crafted of course but productions %, breed %, and items used changed to be a better incentive for end-game players to bother with bees.

::New Bees::

Neighsayer Drone + Catty Drone
____________________
*Beastly Drone

T: Normal
H: Normal
Flowers
Normal Life
Slow Worker
Diurnal Nocturnal

Beastly Production
*25% Furtive Comb
Spec: *25% Fish, 25% Leather 42% Apple
___________________________________

Beastly Drone + Smouldering Drone
____________________
*Horror Drone

T: Hell
H: Normal
Rocks or Flesh (giving use to the flesh found in nether) if able to add a new flower type.
Long Life
Slowest Worker
Diurnal Nocturnal
Rain Tolerant

**Horror Production
*15% Molten Comb 25% Furtive Comb
Spec: *20% Fish, 20% Leather 14% Apple 8% Blaze Rod 5% Blaze Powder
________________________________________________

Shadowmetal Drone + Horror Drone
___________________________________
*Shadowling Drone

T: Freezing
H: Arid
Flowers
Long Life
Slowest Worker
Diurnal Nocturnal
Rain Tolerant

**Shadowling Production
*5% Molten Comb 10% Shadowmetal Comb 15%  10% Glittering Comb
Spec: *10% Fish, 14% Leather 10% Apple 5% Blaze Rod 8% Blaze Powder
____________________________________________________

* The shadow dragon tree is an attempt to merge the draconic line, monster loot lines, and the shadow metal lines all together in order to cover the majority of the less used lines of bees.

Shadowling + Draconic
______Charged Draconium Block____________
*Shadow Dragon Drone

T: Freezing
H: Arid
End
Longest Life
Fast Worker
Diurnal Nocturnal
Rain Tolerant

**Shadow Dragon Production
10% Shadowmetal Comb  15% Draconic Dust (Magic bees) 5% Draconium Dust 
(It has aspects of both Draconic and Chaos bees in the creation)
Spec:  20% Leather  5% Blaze Rod 15% Blaze Powder 2% Draconic Chunk

_________________________________________________________

Shadow Dragon Drone + Black Plutonium
________Awakened Draconium Block________________
*Chaos Dragon Drone

T: Freezing
H: Arid
End
Longest Life
Fast Worker
Diurnal Nocturnal
Rain Tolerant

**Chaos Dragon Production
20% Draconic Dust (Magic bees) 10% Draconium Dust 5% Awakened Draconium Dust
Spec:  5% Draconic Chunk, 2.5% Draconic Core Fragment

:New Item: Draconic Core Fragment
Combine four Draconic Core Fragments in a ZPM assembly machine with 1,152 molten mithril to create a Draconic Core 

_________________________________________________________

::Breed Order Changes::
Barnarda F + T Ceti E
__________________________
Infinity Catalyst Bee

*This gives use to the T Ceti E bee as well as makes the breeder go through another side line of planets.

Neutronium + Infinity Catalyst
__________________________
Cosmic Neutronium Bee

*Cosmic Neutronium is more annoying to get once reaching the deep dark than infinity catalysts, so it stands to make sense for it to be higher in the breeding tree than catalysts.

Cosmic Neutronium + Chaos Dragon
__________________________
Infinity

**Infinity Bee
*Infinity Block as base block
-Once you have MEs and server rooms the infinity chest is honestly kind of a useless craft unless using specifically in this bee- and by this point there's no excuse to not have an ME.   Honestly I wouldn't mind a new compressed infinity block to be a thing specifically for this, but somewhat feel that'd be a bit unnecessary.
*Breed chance changed to 1.3%
-As we have a hard cap chance of 15x when mutating no matter what option is used, this gives it a reasonable 19.5% chance when using the absolute maximum possibility.

**Infinity Catalyst Bee:
*Deep Dark Portal as base block
-Once you reach the deep dark; you'll be getting thousands of infinity catalyst ores near effortlessly,  so it feels to make sense to use the deep dark portal as the base for this.
*Breed chance changed to 2%
-As we have a hard cap chance of 15x when mutating no matter what option is used, this gives it a reasonable 30% chance when using the absolute maximum possibility.

**Cosmic Neutronium Bee
*Deep Dark Portal as base block
-Honestly for this bee, Cosmic Neutronium block is a bit too cheap if the bee actually becomes useful.
*Breed Chance changed to 2.75%
-As we have a hard cap chance of 15x when mutating no matter what option is used, this gives it a reasonable 45% chance when using the absolute maximum possibility.

________________________________________________________________________________

**Infinity Comb
*5% chance of creation from the drone
centrifuge-
*266,168,000 EU processing cost (Cost of each other cost multiplied by number of mats in infin ingot recipe combined with costs of 1/9th of each of the crystal matrix costs)
*50%  Besswax
*5% Tiny Infinity Dust
*25% Tiny Infinity Catalyst Dust

**Infinity Catalyst Comb
*10% chance of creation from the drone
centrifuge-
*5,000,000 EU processing cost
*50%  Beeswax
*20% Tiny Pile of Infinity Catalyst Dust

**Cosmic Neutronium Comb
*5% chance of creation from the drone
*10% chance of Tiny Pile from Centrifuge
-At the energy cost, even if the fair cost is brought in;  it wouldn't be worth it at really anything less.
*8,775,000 EU processing cost.
-It takes roughly 90milion EU to make a cosmic neutronium ingot from scratch; so processing these combs at an already low chance this makes things reasonably balanced.  Also at this point there's not much excuse to not have automated itnt or dynamite production to take care of the other mats needed.

**Comment by AlexBucket** [comment]
> -Once you have MEs and server rooms the infinity chest is honestly kind of a useless craft unless using specifically in this bee- and by this point there's no excuse to not have an ME. Honestly I wouldn't mind a new compressed infinity block to be a thing specifically for this, but somewhat feel that'd be a bit unnecessary.

I would kind of disagree that the infinity chest is a 'useless craft'. The infinity chest has 243 slots, each holding 2,147,483,647 items and the chest holds its contents when broken (taken from google). Item storage wise, that's the same as having about 1,019,216 64k drives (based on 1 byte being 8 items). The chest is far from useless.

**Comment by Teirdalin** [comment]
> > -Once you have MEs and server rooms the infinity chest is honestly kind of a useless craft unless using specifically in this bee- and by this point there's no excuse to not have an ME. Honestly I wouldn't mind a new compressed infinity block to be a thing specifically for this, but somewhat feel that'd be a bit unnecessary.
> 
> I would kind of disagree that the infinity chest is a 'useless craft'. The infinity chest has 243 slots, each holding 2,147,483,647 items and the chest holds its contents when broken (taken from google). Item storage wise, that's the same as having about 1,019,216 64k drives (based on 1 byte being 8 items). The chest is far from useless.

In contrast; the drives it takes to make it can hold 640 different items.   And the modpack generally has you getting lots of different items instead of stacks going into the billions of the same items.  Far better to use a barrel upgraded to a couple thousand stacks for storing any item you may possibly need to go into the 30,000+s.   Or to just store them in a single slot on a large drive.

**Comment by 0lafe** [comment]
I always thought it needed the chest because of how expensive the chest is, which I liked. Also the infinity EU/% seems kind of high. Unless smelting the dust takes 20B EU, these values would make the bee about 4x better than anything automated right now. Which is dumb imo for a bee too do
