### ISSUE TITLE
Piston Plate (Plank Ore Dictionary)

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#3762]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Tried to craft Piston Plate in Basic Assembling Machine Using Spruce Plank and Oak Fence.
#
#### What happend instead? (Attach screenshots if needed)
Didn't create Piston Plate. Required Oak Plank specifically.
#
#### What do you suggest instead/what changes do you propose?
Ore Dictionary the planks so you can craft the piston plate from whatever wood you're farming?

**Comment by septemberWaves** [comment]
If I recall correctly, assemblers have issues with ore dictionary. Probably the simplest way of making wood-consuming assembler recipes work with any wood type would just be to use Gregtech's wood planks; otherwise I'm fairly sure the devs would have to add a unique recipe for each wood type.

**Comment by richardhendricks** [comment]
There is a Coins quest to provide at low cost access to vanilla tree types, including Oak.

**Comment by repo-alt** [comment]
Looks like the quest is gone, also I don't see why it is impossible to add an alternative recipe using "GT Wood Plank"

**Comment by Prometheus0000** [comment]
?
![image](https://user-images.githubusercontent.com/8517039/102662151-3bb57600-414c-11eb-8816-d6c659aa1d74.png)

**Comment by repo-alt** [comment]
Ah, I can't read. I thought it meant there is a quest for vanilla wood types. Anyway, I don't really want to keep specifically small oak farm forever, to be able to autocraft pistons

**Comment by Prometheus0000** [comment]
Certainly it would be nice to be able to use other wood types.

**Comment by repo-alt** [comment]
Other wood types may be impossible, due to oredict issues (although I remember Brat hacked some oredict support in the assembler), but at least add a recipe with planks made from compressed wood dust, made from just any wood

**Comment by draknyte1** [comment]
GT wooden plank/plate thing.. just don’t use actual planks anywhere and it’s gravy.
