### ISSUE TITLE
Shift+clicking saw with sacred oak wood deletes wood when it runs out.

### ISSUE THREAD

**Issue by mtjohnson47** [GTNewHorizons/GT-New-Horizons-Modpack#3772]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Personal server, default configs
#
#### What did you try to do, and what did you expect to happen?
Create planks to fuel boiler, i expected the extra logs to remain on the crafting table.
#
#### What happened instead? (Attach screenshots if needed)
When the saw broke, the extra logs did not remain on the crafting table, and i got less than 4 stacks planks
#
#### What do you suggest instead/what changes do you propose?
Fix the bug.

**Comment by Bryfer** [comment]
What crafting table see you using?

**Comment by mtjohnson47** [comment]
Tinker's

**Comment by Dream-Master** [comment]
@mtjohnson47 use the normal crafting table.

**Comment by mtjohnson47** [comment]
Just tested, the bug still occurs in the vanilla table.  Note that this report is specific to sacred oak logs, it does not occur with other wood varieties that i've tried.

**Comment by Dream-Master** [comment]
@mtjohnson47 any news here?

**Comment by mtjohnson47** [comment]
There's been no update, so yeah, but still exists.  How exactly does it need more info?

**Comment by Dream-Master** [comment]
ah sorry didnt see you do it in vanilla table. 
Sacred oak is from BoP right?
I guess it is a bug on Bop side. Not sure if anyone can fix it. @mtjohnson47

**Comment by mtjohnson47** [comment]
Steps to reproduce?
Place a saw on the crafting table with low durability.
Place a stack of planks on the table.
Shift click on the output.
You'll get less than 4 stacks planks.  If you get 4 stacks, repeat, durability was too high
