### ISSUE TITLE
Query/Request: How to standardise GT Machine Parts (hidden meta?)

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#3774]
#### Which modpack version are you using?
2.0.5.1
#
The GT machine parts all have an ID/meta data but they also have some hidden GT data:
Motor
Pump
Conveyor
Robot Arm
Sensor
Emitter

The hidden data appears to track the parts used to craft the item for disassembling.  I have noticed there is at least 2 versions of the part:

a) 1 that can be disassembled to it's original parts
b) a generic version that can't be disassembled (used to come from quest rewards).

I have found a way that you can convert (a) -> (b) by placing it on a GT hatch and removing it with a crowbar.  This generic version can now stack with other generic versions.  It can't be disassembled but this doesn't matter, you can always arc furnace it if necessary.  Example:

![version 1](https://user-images.githubusercontent.com/32101225/47431359-eebbfc00-d79b-11e8-8dda-704e6adbd4ee.png)

I place one of the (a) hv pumps on a hatch and removed it with crowbar, it became a (b) hv pump that cannot be disassembled.

![version 2](https://user-images.githubusercontent.com/32101225/47431367-f1b6ec80-d79b-11e8-9492-30e28abaf026.png)

This leads to many different types of parts being used to craft GT stuff and preventing parts and GT blocks from stacking which can be very annoying (especially when trying to figure out which blocks have covers already).  And when crafting machines for the Processing Arrays, you always have to start from scratch using all the same parts.

Is it possible to add a recipe for these parts to make them (a) -> (b) part.  Or maybe a simple GT Parts Normalising Unit - a machine to convert parts to a generic version?

If this is already possible via crafting/machine I'd like to know.

**Comment by Dream-Master** [comment]
<BuildCraft|Factory:tankBlock>
![image](https://user-images.githubusercontent.com/2970688/47609425-82145c00-da3e-11e8-8c21-a4b646989d4a.png)
Not sure if the Name remover can help here unifying stuff.
@Technus ?

**Comment by Dream-Master** [comment]
@Highbeam try to go in sp game and craft different items. Using /mt hand on all of them.
After you crowbar it or put it in the name remover do /mt hand again.
Report here. Thanks

**Comment by Highbeam** [comment]
Screenshot #1 = Player made LV Motor in crafting workbench:
![2018-10-27_23 36 53](https://user-images.githubusercontent.com/32101225/47609565-9ad24100-da41-11e8-98ad-4651a91f4007.png)

Screenshot #2 = Spawned LV Motor:
![2018-10-27_23 33 56](https://user-images.githubusercontent.com/32101225/47609569-a887c680-da41-11e8-83b1-be070ed5d18a.png)

**Comment by Highbeam** [comment]
I tried running the player made motor through the Name Remover but it didn't change the meta information.

So if the Name Remover can be updated to remove the tag from player made parts that would be perfect.

**Comment by Dream-Master** [comment]
@Technus @bartimaeusnek @mitchej123 @codewarrior0 @richardhendricks  i need help here.
The Name remover is in the core mod.

**Comment by Highbeam** [comment]
To update - removing a playermade conveyor with crowbar removes the tag.  A very long way to get items to stack.

Can the Name remover also strip tags from GT machines if they are run through it?
