### ISSUE TITLE
Auto smelt Tinker's modifier not working with GregTech Ores

### ISSUE THREAD

**Issue by mtjohnson47** [GTNewHorizons/GT-New-Horizons-Modpack#3781]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Personal Server, default configs
#
#### What did you try to do, and what did you expect to happen?
I tried mining coal and iron ore, which can both be smelted into coal/iron.  I expected it to drop coal/iron ingot, hopefully duplicated from fortune.
#
#### What happened instead? (Attach screenshots if needed)
It dropped the ore as normal.
#
#### What do you suggest instead/what changes do you propose?
Enable autosmelting GT ores

**Comment by mtjohnson47** [comment]
It also doesn't work with small ores

**Comment by Bryfer** [comment]
You really don't want autosmelt on your hammer.
Alot of the ores gives you precious byproducts, these byproducts can even be required to advance in progress

**Comment by mtjohnson47** [comment]
Then you can silk touch them, or use a pick without autosmelt.  Autosmelt is still useful when you don't want to wait on furnaces, even if you don't have it on your primary pickaxe.  The questbook gives you a lava crystal, it kindof makes since to use it for autosmelt.

**Comment by Dream-Master** [comment]
i am not sure if this can be disabled/enabled for each type of the tincer tool. After i removed random modifier i guess it is less an issue ? And btw so far i know it wont work for gt ores in general or i am wrong ?

**Comment by mtjohnson47** [comment]
Hasn't worked on any GT ore.  And why would it need to be disabled at all, it's an optional thing you can add, not a default thing.

**Comment by Dream-Master** [comment]
sure that's why I questioned if this is an issue at all. We forked tinkers source so if anyone will add gt ore support why not.

**Comment by mtjohnson47** [comment]
The issue is that it's not working, whether a bug or needing mod interaction, IDK.

**Comment by Dream-Master** [comment]
If you rember there was a big problem with the two mod devs in the past (2 or 3 years before)(mydio and greg) So they wont support each other. Guess thats the reason why it wont work.

**Comment by mtjohnson47** [comment]
Well, there's Tinker's Gregworks, so, that's probably the spot to add compatibility

**Comment by Dream-Master** [comment]
that is open source too. Go ahead.

**Comment by Highbeam** [comment]
just make sure you don't accidently enable autosmelt on ores that need EBF/vac freezer

**Comment by Dream-Master** [comment]
@mtjohnson47 i cant add code to Tico so what we need to do here @mtjohnson47  ?

**Comment by mtjohnson47** [comment]
If there's nothing you can do, there's nothing you can do.  I'm unfamiliar
with how the mods work, and assumed there was probably a white or blacklist
somewhere.

**Comment by Dream-Master** [comment]
@mtjohnson47 is there any in config just show it to me. If it is only code wise i cant do somethings here.

**Comment by mtjohnson47** [comment]
As I said, I don't know.

**Comment by Dream-Master** [comment]
ok.
