### ISSUE TITLE
There's a pretty bad dupe bug with TH.  ❗️

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/GT-New-Horizons-Modpack#3786]
#### Which modpack version are you using?
2.0.5.1
#
#### Well that's rather vague, what do you mean?
Messaged Dream about it, and he told me to post it vaguely on here.
Not,  entirely sure how he wanted me to go about the post aside from that.  
Kinda feel like it's not really something we want all random players visiting the github to figure out about; although most probably don't have the nonsense setup to do it to begin with in the short term.

**Comment by Teirdalin** [comment]
> Well this was vague! TH? 😅

Thhhhhhhhhhhhhhhh

**Comment by Gateswong** [comment]
> Well this was vague! TH? 😅

Guess is ThaumicHorizons

**Comment by Dream-Master** [comment]
@richardhendricks help wanted means i need help from you or another coder look into Thaumic horizons code.

**Comment by Dream-Master** [comment]
@Teirdalin what is your Discord Name. Cant find the TH bug.

**Comment by Teirdalin** [comment]
Hey @Dream-Master   Haven't been on minecraft in over a year now. xD   But I do remember the bug for the most part,   It's Teirdalin #6459
