### ISSUE TITLE
Construction Data for AssemblingLine(book) is broken in Server

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#3817]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
My private server × 2 and my friend server.
#
#### What happend instead? (Attach screenshots if needed)
Construction Data for AssemblingLine(book)  is different from NEI recipe in Server(It worked well in Single).

Screenshot is recipe for LuV pump
1.NEI Recipe(in server)
![2018-11-03_20 51 28](https://user-images.githubusercontent.com/40425798/47951930-3ff19a00-dfab-11e8-96ff-81e4ec193335.png)
2.Part of Construction Data for Assembling Line(It made in **server**)
![2018-11-03_20 22 58](https://user-images.githubusercontent.com/40425798/47951937-5c8dd200-dfab-11e8-9b41-e91cec82fe59.png)
3.Part of Construction Data for Assembling Line(It made in **single**)
![2018-11-03_19 32 31](https://user-images.githubusercontent.com/40425798/47951945-6ca5b180-dfab-11e8-833d-31fb13c60891.png)
#
#### What do you suggest instead/what changes do you propose?
fix it.
I found that it is different in LuV pump and ZPM pump.

**Comment by Dream-Master** [comment]
in newest version you can use more different rubber rings.

**Comment by Teirdalin** [comment]
At least your book isn't saying %Material like mine tend to.  lol

**Comment by bartimaeusnek** [comment]
@Teirdalin version? should be fixed

**Comment by Teirdalin** [comment]
> @Teirdalin version? should be fixed duct taped

2.0.5.1
Cannot recall if it was an old data disk,  I'll check later though.
