### ISSUE TITLE
Minor Suggestion:  Empty Blood Syringe

### ISSUE THREAD

**Issue by Teirdalin** [GTNewHorizons/GT-New-Horizons-Modpack#3818]
#### Which modpack version are you using?
2.0.5.1
#
#### Apples, Turnips, Pineapples.
So oddly enough when trying to take blood samples from animals sometimes it'll instead take a blood sample from yourself which,  is a waste of a syringe.  So my suggestion is a means of emptying the Thaumic Horizons Blood Syringe back into normal Warded Syringes.   Maybe just a crafting grid recipe with just the syringe alone.   Or perhaps in a machine of a sort instead if that's a bit unrealistic.

I got about a drawer just full of wasted blood syringes,  sure they're cheap but it'd be nice to use them.   The Seroconverter is still bugged to crash the client so their uses are incredibly limited.

**Comment by Dream-Master** [comment]
Will do when i am on Thaumic Base nerfs

**Comment by monroth** [comment]
bad idea, as whole idea by syringe mechanics is that it becomes nonsterile after first usage, and you can't use it after first use.

**Comment by Dream-Master** [comment]
so better close it I guess @monroth @Teirdalin ?

**Comment by Teirdalin** [comment]
How about requiring to sneak to take a self sample then, so as to not have accidental self samples of blood.

**Comment by Dream-Master** [comment]
@Teirdalin if you add this via code and this is balance i am ok with it.

**Comment by Teirdalin** [comment]
Another option I could see could be a way to sterilize a needle; looking online for "how to sterilize a needle" I saw that autoclaves with steam is what people do in real life; considering we have both ingame that seems an easier option than changing mechanics around to get rid of wasting needles due to bad hitboxes.
