### ISSUE TITLE
Strength of blocks from Mods Zstone

### ISSUE THREAD

**Issue by Bob558-51** [GTNewHorizons/GT-New-Horizons-Modpack#3819]
#### Which modpack version are you using?
Last actual

#### If in multiplayer; On which server does this happen? 
Epsilon

Building blocks from Mods Zstones are easily cut with a pick. Blocks are cut like butter - just a lot of, it is enough to accidentally hit them with a pick
Please increase the strength of these blocks at least to the level of stone bricks

**Comment by draknyte1** [comment]
Unless ztones offers a config option as such, there's little that can be done.
Just use a lower level pickaxe to mine them, problem solved.

**Comment by Bob558-51** [comment]
I don't need to mine them. They are from accidental contact with a pick scatter around the house

**Comment by richardhendricks** [comment]
The best solution I've found is to use a drying rack to hold a slower pick and swap my mining pick with it when I want to go mine.  (Also, remove your traveller's gloves if you made those, they add mining speed too!)

The better pick I've found for that is the Dark Steel pick.  Fairly easy to make, and slow enough to control deconstruction.

**Comment by Dream-Master** [comment]
how he changed it. Inside Tec Tech ?

**Comment by richardhendricks** [comment]
@Technus Any idea here?

**Comment by Technus** [comment]
I only set blocks to Stone hardeness not lower, could increase ztons hardness to stone.
