### ISSUE TITLE
[suggestion] early/easy way to get EBF ingots out of smeltery

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/GT-New-Horizons-Modpack#3828]
We are talking about a hand full of ingots here:
steel, alu, cobalt, ardite and manyullyn (hope that's all of them)

Currently you cannot get them out, the suggestion would be that you *can* get them out with the ingot cast but you get a "flawed ingot" which macerates back into the dust, possibly you could be able to arc furnace them (?).

Seems like an easy and clean way to get the metals back out instead of forcing the player to make parts or alloy them in the smeltery.

**Comment by sthegreat** [comment]
+1. We already have this for aluminium, and the resulting 'raw aluminium' can't be arcfurnaced or anything, only macerated or melted again. I think this would be good to add the same thing for all these early metals. This way people can get metals out but they can't smelt steel dust to ingot in the smeltery (which would allow a player to skip the blast furnace using chain armor from mobs).

**Comment by bartimaeusnek** [comment]
> allow a player to skip the blast furnace using chain armor from mobs
thats a neglictable ammount of steel you get compared to whats needed for a single steam turbine...

**Comment by Dream-Master** [comment]
ok but in which tier you stay when you have a good working mob farm ? @Hakameda

**Comment by CalterOK** [comment]
Do not pour more material into the oven than is required, and there will be no such problem.

**Comment by WarlordWossman** [comment]
>Do not pour more material into the oven than is required, and there will be no such problem.

Don't play the modpack and you will never run into issues.

**Comment by Dream-Master** [comment]
I add steel ingots maybe add the other one in such way.
