### ISSUE TITLE
Essentia transformation bug (OP)

### ISSUE THREAD

**Issue by R60D** [GTNewHorizons/GT-New-Horizons-Modpack#3848]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Dig-to-Build
#
#### What did you try to do, and what did you expect to happen?
Shift-leftclick essentia phials from my me-system. I expected them to appear in my inventory.
#
#### What happend instead? (Attach screenshots if needed)
The essentia phials stacked based on the first essentia phial shift-leftclicked into my inventory. I had three different essentia phials in my Me-system, and they all stacked into one. 
![1](https://user-images.githubusercontent.com/29761720/48782243-7555f180-ece6-11e8-9c59-2049a6c6bd1f.JPG)
![2](https://user-images.githubusercontent.com/29761720/48782258-7d159600-ece6-11e8-97fb-d352582ca460.JPG)

#
#### What do you suggest instead/what changes do you propose?
I have no idea how to fix it.

**Comment by Teirdalin** [comment]
Ah I think I saw this happen with my precantatio phials earlier; was wondering what was up with that;; figured it was just a visual bug.

Maybe the meta needs changing on the phials; although did you relog to see if they were still like that and that it definitely was not just a visual bug?

**Comment by R60D** [comment]
The bug is not visual. The phials stay after relog

**Comment by Dream-Master** [comment]
@R60D which mod have this bug ?

**Comment by R60D** [comment]
This bug only works with the (Tinkers Energetics) Arcane Crafting terminal.

**Comment by Dream-Master** [comment]
@R60D can you report the issue here ?
https://github.com/Nividica/ThaumicEnergistics/issues

**Comment by R60D** [comment]
Did send it to them, but I doubt they will fix it in the near future.

**Comment by R60D** [comment]
I did send it to them, but I doubt they will fix it anytime soon?

**Comment by Dream-Master** [comment]
will see

**Comment by Dream-Master** [comment]
the owner answering
