### ISSUE TITLE
Node Matrix Dupe Bug

### ISSUE THREAD

**Issue by gerb82** [GTNewHorizons/GT-New-Horizons-Modpack#3858]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Tested so far only in single-player in creative and survival
#
#### What did you try to do, and what did you expect to happen?
Attune a node matrix from nodal mechanics to a specific aspect.
#
#### What happend instead? (Attach screenshots if needed)
The amount you get per crafting batch is not only one, but the amount of matrices consumed is always one. Attached are two screenshots of before and after a crafting:
![2018-11-24_17 58 24](https://user-images.githubusercontent.com/13512001/48971401-c2f19780-f021-11e8-8b6c-d457ce8f0bc7.png)
![2018-11-24_17 58 27](https://user-images.githubusercontent.com/13512001/48971402-c4bb5b00-f021-11e8-9b08-039d22d890e0.png)
Works with any essentia. The amount crafted per batch is decided when you put the matrices in the middle. So if i put one, and then add 30 more, it will craft one on the first batch, and then it will see that it has 30 left in the middle (because it used one), and will allow to craft 30 now. But after this will be crafted, you will be left with 29 matrices in the middle, and you'll still get 30. You will also be prompted to craft 29 more.
#
#### What do you suggest instead/what changes do you propose?
Have it craft 1 matrix per 1 crafting, Which is what would make sense in this case.

**Comment by Dream-Master** [comment]
@gerb82 can you test it with  this version ?
https://github.com/KryptonCaptain/Nodal-Mechanics/releases

**Comment by gerb82** [comment]
Still doesn't work (already discussed with dream but figured it would be good to document here)

**Comment by Dream-Master** [comment]
additional pics
![image](https://user-images.githubusercontent.com/2970688/48977617-038ef680-f09e-11e8-8862-700c28826026.png)
![image](https://user-images.githubusercontent.com/2970688/48977621-199cb700-f09e-11e8-898c-e0a1af6a2ea7.png)
![image](https://user-images.githubusercontent.com/2970688/48977625-26210f80-f09e-11e8-9b2b-4716147a0104.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek can you help me with this here? Thanks
