### ISSUE TITLE
Quantum Computer scanner recipe bug

### ISSUE THREAD

**Issue by inganlegi** [GTNewHorizons/GT-New-Horizons-Modpack#3859]
#### Which modpack version are you using?
2.0.6.0b (but it happens 2.0.5.1 as well)
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I tried to scan data orb with data stick (tectech quantum computer recipe).
#
#### What happend instead? (Attach screenshots if needed)
Nothing happened (but research station recipe (elite scanner ii + data stick) worked).
![image](https://user-images.githubusercontent.com/12507307/48975761-883c3d80-f0bb-11e8-954b-c635f9187a49.png)
note: with tectech 3.6.2 + gt5u0931, this reipce worked.

**Comment by Dream-Master** [comment]
http://jenkins.usrv.eu:8080/job/Tec%20Tech/51/

**Comment by DualBallers** [comment]
It seems like this is still not working in 2.0.6.2, @Dream-Master 
![image](https://user-images.githubusercontent.com/30087707/50059454-3ef58000-0187-11e9-809f-0afdb0a1446c.png)

**Comment by richardhendricks** [comment]
@bartimaeusnek Is this a recipe bug or does it need code changes?
