### ISSUE TITLE
suggestion for AE

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#3876]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
At each reboot of Delta, I expect to be able to interact with my ae normally
#
#### What happend instead? (Attach screenshots if needed)
At each reboot my ME security terminal stop working and so do my wireless terminal. I need to manually
break it and replace it, then link again my wireless terminal. It's tedious.
Precision on the Security Station: it's directly next to a ME Controller and they are both in the same chunk. Also, i'm not recognized by the Security Station after the reboot so i must break it to regain access to AE 
#
#### What do you suggest instead/what changes do you propose?
I suggest to add a device which will be used only to link wireless terminals because anyways we already have claims to prevent players from interacting with AE.

**Comment by Dream-Master** [comment]
if some one programming it why not

**Comment by mitchej123** [comment]
There's a community effort to maintain AE2; if this is still an issue report upstream.

**Comment by Sphyix** [comment]
Security terminal can mess with various stuff, so if there's the possibility for a block to link the wireless without needing security, it'd be pretty cool, even if this is not a problem

**Comment by boubou19** [comment]
yeah if possible it would be cool to add

**Comment by repo-alt** [comment]
Well, quite a bit of hacking should be involved for that to work

**Comment by boubou19** [comment]
Should i reopen the ticket then?

**Comment by repo-alt** [comment]
This is honestly not quite trivial and may break stuff. What problems are there with a security terminal anyway?

**Comment by boubou19** [comment]
when the AE security loads faster than the rest of the chunks around it, it can interpret the connection of the cables at chunk boundaries as a block placement. So it breaks the cables and you end up with a base being fucked up.

**Comment by repo-alt** [comment]
That should be fixed I guess

**Comment by boubou19** [comment]
it's hard to reproduce, so i cannot try it, but i'll trust you and let you know if the issue happens again.

**Comment by repo-alt** [comment]
Perhaps easiest way would be something like a timeout before security terminal does any checking after loading. (Like what GT machines do)
