### ISSUE TITLE
Update automated on/off quest with better explanation

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#3894]
![image](https://user-images.githubusercontent.com/1214811/49817910-19a3e480-fd37-11e8-93ca-b1659ae75b40.png)

**Comment by Dream-Master** [comment]
@richardhendricks a bit more infos please. What need to be done here?

**Comment by richardhendricks** [comment]
I need to write up the quest better so it explains how this works properly.
