### ISSUE TITLE
The one ring op

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#3909]
#### Which modpack version are you using?
2.0.6.2
#
#### What do you suggest instead/what changes do you propose?

Probably just remove the ring. It's a fairly early loot drop and gives invincibility, feeds you, and makes mobs passive. Unless that's just warping stuff and you can do it other ways, the ring seems pretty OP. Apart from giving flight, that's better than infinity armor.

**Comment by bartimaeusnek** [comment]
how about i throw blindness, nausea and some other annoying potion effect on it, in addition to the warp? then you will only use it in rare situations...

**Comment by Dream-Master** [comment]
good idea

**Comment by richardhendricks** [comment]
Nah, just have it give you permanent warp each time you put it on, like 5 points, on top of 5 points of temporary warp.  That way the problem naturally resolves itself.

**Comment by Hakameda** [comment]
It gives blindness , nausea and poison already, and it doesn't make a difference. Can probably skip space suits too.

**Comment by Hakameda** [comment]
It was at like 160 warping, it actually sees to reduce the frequency of regular warp events. Though double withers in the base was meh

**Comment by 0lafe** [comment]
>Nah, just have it give you permanent warp each time you put it on, like 5 points, on top of 5 points of temporary warp.

Then just put it on once and never remove it, never gain warp? Also, the whole warp part is almost a non factor once the talismen comes into play, in EV/IV, still well before infinity. Use it for a little, take it off and wait a little until you have no warp.

**Comment by Anarack** [comment]
Make it give normal/sticky warp not perm, still removable just harder too and needs soap/arcane spa to do so, otherwise someone is going to brick their character with it.

**Comment by Hakameda** [comment]
The current warp isn't really punishing anyway

**Comment by richardhendricks** [comment]
It only gets removed by death @0lafe , and isn't bricking a character kinda the whole point?

**Comment by 0lafe** [comment]
Yeah it's comes off faster than a lubed up Winnie the Pooh stuck in a honey hole. If the warp goes away when the ring is gone, that's kind of an issue. I feel like to make an invincibility ring balanced at EVish, it would need to have so many downsides. Blindness is a good start, but how does that work with constant NV? Maybe don't give a ring that makes you invincible, or have it be a craft instead of a loot drop. Right now you pretty much get it for free, and end up making the talismen anyway, so it's almost free invincibility.

**Comment by richardhendricks** [comment]
After the discussion in discord, I agree this item needs removing.  It even protects against GalaxySpace trying to kill you on the planets with no oxygen.  

Cut it.

**Comment by Anarack** [comment]
As a side note, If I'm reading it right the invincibility should cut off after 23 minutes or so, but its still a screwy item.

**Comment by richardhendricks** [comment]
How about this?

no effects until it is worn the first time.

Inivisibility, but causes extreme hunger while worn, leading to damage quickly, along with slowly increasing warp

Item can be taken off, but as long as it is in inventory, will occasionally put itself in a ring slot, causing invisibility and warp increase etc as above.

Item cannot be taken out of player inventory.  Trying to remove it causes it to come back. putting it in a chest, etc.  Dropping it causes it to disappear after a short time and re-appear in the player's inventory, kicking out a random item if there is no room. Even swapping it with the traveller's belt should cause it to re-appear in inventory. (track separately in a file which players have worn the ring and just make it appear in their inventory)

Each time it is put on, including forced wearing, there is a chance that the red knights/clerics warp in and start immediately attacking the player.  Call them nazguls or something.

Player can only ever have 1 ring.  If they find another while in possession of one, it immediately disappears.

The only way to get rid of it is to drop it into lava.

**Comment by Dream-Master** [comment]
good idea if you coding it :) @richardhendricks

**Comment by richardhendricks** [comment]
EMT is Bart's turd...I mean baby. :D

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by bartimaeusnek** [comment]
>Inivisibility, but causes extreme hunger while worn, leading to damage quickly, along with slowly increasing warp
Item can be taken off, but as long as it is in inventory, will occasionally put itself in a ring slot, causing invisibility and warp increase etc as above.
Player can only ever have 1 ring. If they find another while in possession of one, it immediately disappears.
The only way to get rid of it is to drop it into lava.

possible

>Item cannot be taken out of player inventory. Trying to remove it causes it to come back. putting it in a chest, etc. Dropping it causes it to disappear after a short time and re-appear in the player's inventory, kicking out a random item if there is no room. Even swapping it with the traveller's belt should cause it to re-appear in inventory. (track separately in a file which players have worn the ring and just make it appear in their inventory)
Each time it is put on, including forced wearing, there is a chance that the red knights/clerics warp in and start immediately attacking the player. Call them nazguls or something.

harder to code, but theorethically possible...

**Comment by Lainiel** [comment]
Could you just remove it until it gets fixed?

**Comment by Prometheus0000** [comment]
Dream decided to make the ring be found in chests, but add warp to the player as well. See https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/14, #5168, #6661, #6665,  #6779.

**Comment by Dream-Master** [comment]
we have to lower the chance the ring appear in  chests . It was 15

**Comment by KiloJoel** [comment]
I really strongly disagree with this. If a new player finds the ring,, doesn't know what it does and wears it for 1h40m, they will amass enough permanent warp to permanently be spawning withers. With no way to stop it until they get mv machines, an implosion compressor and significant magic progress (for impure tears).

The only way they will be able to solve this is by choosing a different server. This is VERY new player unfriendly.

I have no problem with there being a significant downside to using it, but this feels more like a noob trap.

**Comment by Prometheus0000** [comment]
#6839

**Comment by Dream-Master** [comment]
@KiloJoel if you invincible in this pack you have to think that something is wrong. Wearing the ring and fighting the Dragon with 0 damage is so much power you have to deal with a malus as consequence.

**Comment by KiloJoel** [comment]
The problem is not that there is a consequence. The problem is that the consequence is unclear and you can stumble into it without knowing.

**Comment by Prometheus0000** [comment]
I already said we could add some text to the one ring quest though?

**Comment by leagris** [comment]
Can the ring simply refuse to fit in the ring slot if player has not unlocked it with some research or quest? In LOTR, the one ring is quite selective of its wearer and seems to have its very own will.

**Comment by Prometheus0000** [comment]
Maybe? I'm not sure if that's possible, but I'm not doing that though.

**Comment by Dream-Master** [comment]
@leagris nice idea but i am not sure how to programming it.
