### ISSUE TITLE
add wire cutter functionality to soldering iron

### ISSUE THREAD

**Issue by DoomSquirter** [GTNewHorizons/GT-New-Horizons-Modpack#3919]
#### Which modpack version are you using?
4.6
#
#### If in multiplayer; On which server does this happen? 
ssp
#
#### What did you try to do, and what did you expect to happen?
have a electric wire cutter
#
#### What happend instead? (Attach screenshots if needed)
realized we didn't have a electric wire cutter
divided by zero
#
#### What do you suggest instead/what changes do you propose?
soldering iron makes cables/wires teeny smol little buggers visually, and also disconnects/connects wires as well but does not remove wires/cables in world like a wire cutter does.
it'd be nice to get that functionality added to soldering iron to have an electric wire cutter

moron said he was awesome and to add a ticket so I did cause he is awesome (supposedly)
also moron wants a dremel but now I think he's just abusing his power (lv tier totally)

**Comment by Dream-Master** [comment]
@bartimaeusnek @richardhendricks are you able to add this ?

**Comment by richardhendricks** [comment]
I think so, it should be possible.  Will need to check code.  I assume we do not want it to use solder for wire attach/detach/cut.

**Comment by repo-alt** [comment]
It already does not use solder to attach/detach. Also, GT++ adds an electric wirecutter AFAIK.
