### ISSUE TITLE
[balance] multis and special requirements 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#3969]
#### Which modpack version are you using?
2.0.6.2

#### What do you suggest instead/what changes do you propose?

Multis don't care about special recipe requirements, like cleanroom/low grav. PAs/GT++ multis mean after IV ish you don't really need a cleanroom anymore, and you never need to worry about low grav. Personally I like the idea of the cleanroom. It gets really big too, it's not really a problem to fit stuff in it. I think it would be a good change to make even the multis require the special recipe stuff. If it's possible, I have no idea how to go about it. 

If it's an intended feature, then why even have the low grav stuff, or cleanroom reqs on stuff past IV.

**Comment by Dream-Master** [comment]
Thtas true. Like the idea but cant implement it myself.

**Comment by draknyte1** [comment]
I’ve said several times before I won’t ever change this 0lafe.

**Comment by 0lafe** [comment]
Eh, even just removing it from PAs would be enough, I can tier your multis past the point that you worry about this. I don't mind those skipping it

**Comment by Dream-Master** [comment]
maybe we need some crafting table placed in a clean room or low gravity to craft this part of Multiblocks. @0lafe
