### ISSUE TITLE
[2.0.5.1] NEI Recipes are incorrect for some assembly line items

### ISSUE THREAD

**Issue by finkledoodle** [GTNewHorizons/GT-New-Horizons-Modpack#3973]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Craft LuV Emitter (among other assembly line items with similar issues such as LuV/ZPM pump)
#
#### What happend instead? (Attach screenshots if needed)
The recipe did not craft, NEI displays both an incorrect circuit teir (LuV when it needs EV), and an incorrect number of circuits (4 when it needs 7). By making a printed book, I was able to ascertain the correct recipe. I confirmed with a second player on the server that the NEI recipe was not only wrong on my end, but theirs as well.
#
#### What do you suggest instead/what changes do you propose?
![2019-01-08_17 46 49](https://user-images.githubusercontent.com/12854704/50874104-8a124580-1377-11e9-8839-9f58536441de.png)

![2019-01-08_17 47 07](https://user-images.githubusercontent.com/12854704/50874119-9e564280-1377-11e9-89b0-17f47cbde55a.png)

**Comment by Anarack** [comment]
This at the moment from going over it in discord is looking like something is wrong on the Prospercraft server side. As nei which gets its recipes from the client is wrong, and techtech/the book which its data is assigned by the server is correct. 
This at a minimum suggest a client server mismatch. With in my option, the mistake being on the server side after looking at the 2.0.5.1 client recipes and testing to be sure they line up.
