### ISSUE TITLE
[Idea] High-Tier "Plastic" Type

### ISSUE THREAD

**Issue by Spluff5** [GTNewHorizons/GT-New-Horizons-Modpack#3976]
### The Goal
The problem with high-tier plastics is that no matter how complicated/accurate to irl you make the recipe, it's still just oil products in a chemical reactor like it is with virtually all plasitc in reality. My goal was to come up with an idea for at least a plastic-like material that wasn't just from oil and at the same time incorprated advanced technologies like Spaceflight. This "plastic" idea would be used in future UHV+ voltage tiers yet to be added. This is my idea: Kroton!

### The Inspiration
The Krotons are an alien species from Doctor Who. They, as well as the ships and equiptment they build are made of crystalline polymers based on Tellurium, unlike the Carbon-based life and plastics we are used to. They are also capable to changing back to a liquid state and reforming into different shapes. I thought this would be a perfect use for the new BioVat machine because a culture of living, liquid Kroton could be kept and used to convert tellurium-based nutrients into more liquid Kroton. This could then be pumped out and crystallised into useful shapes like plates and rods. I'm sorry I couldn't write proper recipe code, I might be able to later with a little help

### Getting Tellurium
_In real life, Tellurium occurs in Platinm-group ores, asociated with the platinum group metals. This is the most realistic production chain I can come up with but others could be better. Tellurium is a metal that already exists in GT++ but has no use and the ore doesn't generate._
**Sodium Carbonate**
Sodium Carbonate white, maybe slightly light blue dust
`Large Chemical Reactor: 2x Salt + 1x Hydrated Lime Dust + 2000L Water + 2000L Ammonia + 2000L CO2 Gas = 1x Sodium Carbonate + 2000L Water + 2000L Ammonia`
**Tellurium Extraction from Ore**
Sodium Tellurite is a dirty blue dust. This recipe is also a slightly more efficient way to get valuable metals out of Platinum Group Sludge.
`Large Chemical Reactor: 8x Platinum Group Sludge + 1000L Oxygen + Sodium Carbonate = Sodium Tellurite + Gold Dust + Platinum Dust + Palladium Dust + Iridium Dust + Osmium Dust`
Tellurium Dioxide is a pale brown dust
`Large Chemical Reactor: 1x Sodium Tellurite + 1x Sodium Hydroxide + 1000L Sulfuric Acid + 1000L Distilled Water = 1x Tellurium Dioxide dust + Sodium Bisulfate Dust`
`Electrolyzer: 2x Tellurium Dioxide dust = 1x Tellurium Dust + 2000L Oxygen (This recipe should either take an unusually long time or use an unusually high amount of power)`

**Potential Other uses for Tellurium**
- Used instead of Sulfur to make some kind of highly advanced, heat-resistant rubber
- Combined with Cadmium to make CdTe, used in solar panels
- Use in making advanced RAM chips
- Combined with Bismuth to make the thermocouples used in RTG Generators
- Used in making extremely pure crystalline foils. IRL these are used as semicinductors in advanced circuits

### Getting Kroton Seed Crystals
_In order for Kroton to start growing in the BioVat, you're going to need a sample of living Kroton alien to at least start the process. An alternative idea is for the seed crystal to be found in liquid form in underground lakes._
Kroton Seed Crystals only generate as single ores and look like silver versions of Emerald Ore
`Go to Barnarda F. Mine the very rare Kroton Seed Crystal Ore and put through the extractor to get Kroton Seed Crystals. An alternative idea is to have no ore but instead the crsytals must be centrifuged from Barnarda F Stone Dust at a very low chance of about 0.01% or lower, this isn't too bad since you'll probably only need a few cystals`
**Culturing**
The color of the culture is Metallic Grey
`BioLab: No Module, Sterilized petri Dish + Kroton Seed Crystals + 1000L Distilled Water= Petri Dish with a Culture (Kroton)`

### Growing Kroton
_Now that you have the seed crystals in a culture on a petri dish, they can be used to grow liquid Kroton. Tellurium Broth must be supplied to act as the raw materials for this as well as a high dosage of radiation. The BioVat must be reinforced with a special form of bulletproof glass so that the powerful alien juices don't escape._
**Bulletproof Glass**

**Sodium Tetrachlorotellurate**
Dark Blue-Green liquid
_Makes up the bulk of the broth, allowing a hospitable environment for the Kroton to grow in._
`Chemical Reactor: 1x Tellurium Dust + 1x Chlorine Cell + 2000L Salt Water = 1000L Sodium Tetrachlorotellurate`

**Teflic Acid**
Is a pale yellow liquid. This is the simplest irl recipe but there are much more complex options involving Barium and Distillation if this is too simple. 
_This is essentially the food for the growing Kroton organisms. Xenon Teflate would also be a really cool ingredient to add here instead for lore purposes but would involve getting Xenon, something I might talk about later._
`Chemical Reactor: 1x Tellurium Dust + 3x Fluorine Cell, + 1000L Water = 1x Teflic Acid Cell+ 1000L Hydrofluoric Acid`

**Zintl Dust**
Zintl is a dark blue-black powder
`Chemical Reactor: 1x Molten Tungsten Cell + 8x Tellurium Dust +3000L Chlorine = 1x Zintl Dust`

**Tellurium Broth**
Metallic-silver liquid
_The final, Kroton-nourishing liquid that's actually used in the BioVat. I put oriharkuron and mytryl here but it could be any decently rare space material. The idea is to make it spacey and add metals as a trace-elements to the broth._
`Mixer: 1x Zintl Dust + 1x Tiny Pile of Oriharkuron Dust + 1x Tiny Pile of Mytryl Dust + 1000L Teflic Acid + 4000L Sodium Tetrachlorotellurate = 1000L Tellurium Broth`

***BioVat Recipe***
Liquid Kroton is a silver liquid
_Not 100% sure yet but will involve. Not sure how much radiation will be used yet or the glass type. I think bulletproof glass sounds good but I haven't figured out exactly how to make it yet._
`BioVat (Petri Dish with a Culture (Kroton)): Tellurium Broth + Mysterious Crsytal Dust = Liquid Kroton`

### Shaping Liquid Kroton
_This process does involve forcing a liquid crystal alien to assume the shape you tell it to. This could just be done in the fluid solidifier with standard molds but also could be done using some kind of field-generating advanced-mold._

Wow! That took a while. Happy to answer any questions and discuss some of the recipes further, especially the ones for the Tellurium Broth components. ^_^

**Comment by bartimaeusnek** [comment]
Gold Dust doesnt fit in the platinum slugde thingy, i'd replace that with Ruthenium, Rhodium, or Nickel.

**Comment by draknyte1** [comment]
Tellerium is obtainable, like all base elements.

**Comment by DualBallers** [comment]
@Spluff5 I don't have a comment on the specifics or usability, but together with your Kevlar Material post I just wanna say I am pretty impressed with the detail level in your suggestions :-D
