### ISSUE TITLE
Fishing golem review/loot table update

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#3979]
Considering the ease of creating a large number of the simple fish traps, and the variety of useful items possible, a look at the fishing golem and its loot table is required.

1.  Is it too expensive?  Should the fishing core be made cheaper?

2. How fast is it?  How does it compare to the fish traps? Does it need fishing poles or do they last forever?

3.  What is the loot table for the fishing golem?  Can we change it?

**Comment by richardhendricks** [comment]
https://ftbwiki.org/Golem_Animation_Core_(Fishing)

**Comment by DoomSquirter** [comment]
fishing golems are slow.  very very slow and their output is very reliant on physical actions.

you actually see the bugger toss a line out, wait a bit, then pull something in.  a single item, which gets dropped on the ground and is  up to player to pick up in some way (can drop in random areas). 

needs to be near some deepish water and a decent amount of it.  no forcing them to work in a small area with a single block of water.  

does not use fishing poles or anything else over time.  they just endlessly toss their line into the water and wax softly on their meager existance.

**Comment by Anarack** [comment]
Keep in mind, gt++ single block catchers do not use the default fishing lists unlike the multi block

**Comment by Beyond-Veil** [comment]
@2: it is outfished by the single block GT++ trap about 2:1 (with upgraded core etc) roughly 4:1 if using "Standard" flesh golem with no upgrades
@3: it seems to use the player loot table. Which means that the best loot you can get is "enchanted book". For GTNH the GT++ loot table is actually much more attractive. It has diamonds emeralds, ink sacs, etc.

**Comment by draknyte1** [comment]
> loot pool that say the gt++ fisher has

Actually, It kinda does use the default loot table. (For Items not considered Junk/Loot). There's a 76% chance for that vs the 1% chance for some kind of resource. (Even then, it's a 1/1000 for a diamond)

https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/core/tileentities/general/TileEntityFishTrap.java#L138
