### ISSUE TITLE
SodiumPotassium can't be held in normal cells

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#3986]
2.0.6.2

SodiumPotassium liquid can not be held in normal cells - only in universal cells.
This liquid, in coolant cells, is now used for many types of hatches, so it would be nice if it could be handled easier.

**Comment by Dream-Master** [comment]
Maybe its a Core mod fluid need to check.

**Comment by Dream-Master** [comment]
It is a Core mod item. Have to look if i can add a new fluid in GT. Not sure about compatibility issues.
