### ISSUE TITLE
[minor]quest #759 molten polyethelyne numbers don't make sense

### ISSUE THREAD

**Issue by Beyond-Veil** [GTNewHorizons/GT-New-Horizons-Modpack#3987]
#### Which modpack version are you using?
2.0.6.x
#
#### What do you suggest instead/what changes do you propose?
The numbers of required ethylene and oxygen don't match up with current recipies and neither combination would result in the requested number of filled cells when complete.
1E+7O = 1.5 PE If the goal stays 32 PE, i would expect 24E + 168O, but that would be an outrageous number of cells.
If the goal was made 9PE, it would be 6E + 42O which would be more in line with the current goal.

none of this is gamebreaking, but all your other quests seem nicely aligned (very nice, thanks!).

**Comment by Dream-Master** [comment]
sure will check

**Comment by richardhendricks** [comment]
Don't forget, molten PE cells only hold 144, not 1000.  Also, PE can be made (lazy or stupid) by using compressed air directly for no bonus PE.

Anyways, 168 cells of O is not outrageous by any means.  Welcome to GT:NH!

**Comment by draknyte1** [comment]
> 168 cells of O

Lemme just use 3 Input slots...
