### ISSUE TITLE
Quest Description for #812 doesnt match the Retrieval task

### ISSUE THREAD

**Issue by Aggadahr** [GTNewHorizons/GT-New-Horizons-Modpack#3989]
#### Which modpack version are you using?

#GtNH
#### If in multiplayer; On which server does this happen? 

#Delta
#### What did you try to do, and what did you expect to happen?

# Quest description demands 36, Retrieval task demands 37
#### What happend instead? (Attach screenshots if needed)

# See above
#### What do you suggest instead/what changes do you propose?
Match the Description with the Task

**Comment by Dream-Master** [comment]
Name of the Quest and item/block you need to collect would be nice to not searching for it. @Aggadahr  thanks

**Comment by richardhendricks** [comment]
@Dream-Master You can type the number  in the BQ quest window and it will come up

**Comment by Dream-Master** [comment]
if i am not online idk which quest it is. Lazy to check everytime the quest file. I think if somone repot a issue is great but i want all infos in the issue. Hope that is not to much work :)

**Comment by Aggadahr** [comment]
Full Quest name is "Tier 1 Heavy Duty Plates #812"

**Comment by Dream-Master** [comment]
thanks
