### ISSUE TITLE
Can't see recipe that using AssemblingLine on NEI after taking achievement

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#3993]
#### Which modpack version are you using?
2.0.6.0 and 2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Private Server x2
#
#### What did you try to do, and what did you expect to happen?
I tried to see recipe that using AssemblingLine on NEI after taking achievement
#
#### What happend instead? (Attach screenshots if needed)
I could not see recipe that using AssemblingLine.
![2019-01-17_03 45 51](https://user-images.githubusercontent.com/40425798/51272192-c9423580-1a0c-11e9-9ba8-24bde2703998.png)
![2019-01-17_04 03 31](https://user-images.githubusercontent.com/40425798/51272214-de1ec900-1a0c-11e9-8b60-69e529d528a2.png)
#
#### What do you suggest instead/what changes do you propose?
Could you fix it?

**Comment by Spartak1997** [comment]
Omg. Scanning IV hatch and after that data stich push in Data Reader from TecTech
