### ISSUE TITLE
[Bartworks] Comments on windmill

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#3995]
- [x] Add durability info to primitive rotors.  Which one is best? Or possibly add info in quests for each type?
- [x] Add pointer in Circle Shapes to look for windmill in multiblock goals
- [x] Update windmill tooltip for "Dispenser is part of the wall"
- [x] In quest add info that items can be placed inside the structure, such as bed, crafting table, stairs, and torches etc.
- [x] Support different plank types
- [x] Maybe support different floor types?  Already lots of pressure on clay, stone bricks are pretty easy.

Ideas
- [x] Change the power curve so that it is useable at ground level up to max at 90ish. Dutch use windmills below sea level.  Add a flat number to ic2 wind value?

- [x] Add a new item, "windsock" that is a visual indicator of windspeeds.
SWT
S--
S--
S = stick, W = wool, T = string
Has different positions, 0, 30, 60, 90 degrees based on wind speeds.

- [ ] Future enhancement, add a primitive water pump version/water generator. Require 5x5 water blocks beneath bricks, controller outputs water.  Could be a smaller structure. I am ok with it being ~slower than the water siding tank in a medium environment.  This would give early game options for people who want to/have to live in a desert instead of a very slow/large cacti farm. So it would be better than the tanks in a desert, but worse than the tanks everywhere else.

- [ ] Add some to worldgen. I would not place only full setups, but ruins of various levels. So 1 in 5 has a full setup, most are missing the controller, some are missing controller + gearbox.

**Comment by bartimaeusnek** [comment]
> Change the power curve so that it is useable at ground level up to max at 90ish. Dutch use windmills below sea level. Add a flat number to ic2 wind value?

nope. its enough hackery as it is right now :P

**Comment by richardhendricks** [comment]
Add an obvious front to the controller, also make it obvious from the top. If it is not oriented the correct way, the structure does not form.

**Comment by bartimaeusnek** [comment]
No new NEI recipes for a simple Macerator and no crossing chunk boundaries support.
