### ISSUE TITLE
[Bartworks] Comments on circuit programmer

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4005]
- [x] The font is a little rough. Would prefer a cleaner font over the buttons.
- [x] I like that it needs power/charging.
- [ ] Would prefer an LV recipe.  I am ok with it needing the Mv-grade circuits. 
- [ ] I think using a sodium battery here would be more interesting.
- [ ] Change from aluminium plate to steel, and plastic to good circuit board. Add an LV robot arm to make it cost a little extra.
- [ ] Place a quest for it after Good Circuits in LV.

**Comment by draknyte1** [comment]
```
			//Circuit programmer			
			CORE.RA.addSixSlotAssemblingRecipe(
					new ItemStack[] {
						ItemUtils.getSimpleStack(CI.robotArm_LV, 4 * (GTNH ? 2 : 1)),						
						ItemList.Cover_Controller.get(1, CI.electricMotor_MV),
						CI.machineHull_MV,
						ItemUtils.getItemStackOfAmountFromOreDict(CI.getTieredCircuitOreDictName(2), 2),
						ItemUtils.getItemStackOfAmountFromOreDict(CI.getTieredCircuitOreDictName(3), 2)
					}, 
					ELEMENT.getInstance().IRON.getFluid(144 * 4), 
					ItemUtils.getSimpleStack(ModBlocks.blockCircuitProgrammer),
					60 * 10 * 1, 
					30);
```

Since Bart's is Portable, I don't see why his should be as cheap as a static block.
