### ISSUE TITLE
Wrong recipe causes EBF to lose circuit

### ISSUE THREAD

**Issue by huajijam** [GTNewHorizons/GT-New-Horizons-Modpack#4024]
#### Which modpack version are you using?
2.0.6.2
#

#### What did you try to do, and what did you expect to happen?
Make "clear glass"and"Clear glass pane"to minecraft's in EBF
#
#### What happend instead? (Attach screenshots if needed)
the intergarate circuit disappear

**Comment by Dream-Master** [comment]
Sure why not

**Comment by huajijam** [comment]
the recipe bug is in the "tinker's glass and glass pane to minecraft's one" not minecraft's to tinker's

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/95621995-a0639e80-0a40-11eb-9eee-7dacd575c162.png)
Or is checking in NEI not enough?
