### ISSUE TITLE
[rfc] Have multiblocks halt when output bus/hatch is full

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4041]
Discussion earlier in Discord was a request to stop voiding from multiblocks when their output location is full (hatch or bus).

This ticket is to discuss and vote on the change.

@draknyte1 has given permission to use his CanBufferOutputs function that will verify a recipe's outputs have valid destination locations before starting a recipe.

https://github.com/draknyte1/GTplusplus/blob/master/src/Java/gtPlusPlus/xmod/gregtech/api/metatileentity/implementations/base/GregtechMeta_MultiBlockBase.java#L368

Need to talk about potential issues with EBF output fluid hatch (flue gases) and distillation tower output bus (tiny carbon dusts etc) and missing hatches for unwanted outputs since those are optional.

Alk [++GT]Today at 9:56 AM
This function I just linked Moron must return true before it even processes a recipe.
This checks if there is enough room to output all possible outputs at once.
Unless >= 16 items.. then it just returns true and says good luck have fun.
Mostly for dumb things like DOB combs with 100 1% outputs.
JocroyToday at 9:58 AM
So a LCR with 1 output hatch would not process recipes with 2 results if this gets applied to normal GT?
moronwmachinegunToday at 9:58 AM
I don't think there are currently any  distillation tower outputs >16 is there?
Alk [++GT]Today at 9:58 AM
an LCR is not from GT++
moronwmachinegunToday at 9:59 AM
The one possible issue might be people with EBFs and no output fluid hatch.
It is technically optional right now
Alk [++GT]Today at 9:59 AM
Look how the EBF adds that optional outputs
or juts look at the Adv EBF..

Should they autorestart when space is free, or have to be turned back on manually via hammer/machine controller cover?

**Comment by draknyte1** [comment]
Just posting to confirm I gave permission.

**Comment by Jocroy** [comment]
In the past I did wish for this feature, but there are several setups where it is nice to rely on the auto voiding. For example automated setups, that don't need all the outputs all the time, but you want to buffer some of the other stuff as well (looking at distilling wood tar or biomass). If this gets implemented we need a void upgrade for GT tanks or output hatches, like the one for storage drawers.

**Comment by richardhendricks** [comment]
Trash cans and fluid trash cans exist, and we already have a request for a void cover.

**Comment by draknyte1** [comment]
> we already have a request for a void cover.

These ones?
![image](https://user-images.githubusercontent.com/3060479/51922422-eac5f880-23e0-11e9-8167-cf164ccc60b6.png)

**Comment by richardhendricks** [comment]
Does that also void items?

**Comment by draknyte1** [comment]
No, nor does it quite work properly.
Maybe you wanna take a look if I don't by the time we do this?

**Comment by Dream-Master** [comment]
@richardhendricks good idea that multis not have to void items.

**Comment by SunsfuryAlpha** [comment]
I'm pretty sure that the multiblocks that you do want to continue running when outputs are clogged are few and far between (distillation tower, maybe pyrolyse?). Considering the existence of fluid trash cans and you can buy ender pearls with coins, this change seems to be a net positive. The threat of items being voided doesn't really provide any meaningful challenge to circumvent - I'm in favour of removing pointless difficulties like this.

**Comment by 0lafe** [comment]
Probably gonna get added but personally I don't think we need it at all. I see it as kind of the same as things blowing up with the wrong voltages. Setup your multis to never have a full output and still run. There's more than enough ways to do it, and it punishes you if you don't. Adds some to the item logistics you gotta worry about

**Comment by Dream-Master** [comment]
maybe add a screwdriver option to set hatches to position void or not? @richardhendricks is this possible ?

**Comment by DualBallers** [comment]
I think the GT++ way of handling this plus overflow covers is best solution here. 
I really don't see any fun or learning experience in voiding materials unintentionally. 

However if this is added as a screwdriver setting please consider
- 'no voiding' as the default hatch setting, as this should be a QoL change.
- the multi should auto-start when the hatch space is available like GT++ does, again QoL.
- for multis with many different hatches, will it then be possible to use different settings on different hatches? I mean, the run function should then only ask for run permission on the hatches set to 'no void'.
- how will this conflict/work with fluid hatches set to a specific fluid output? (btw a really great functionality)
- on GT++ multis will enabling hatch voiding overrule or conflict with the GT++ function?

**Comment by mitchej123** [comment]
Any updates here?
