### ISSUE TITLE
[WG] transmutation is not configured yet

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#4059]
#### Which modpack version are you using?
2.0.6.6
#

#### What do you suggest instead/what changes do you propose?

Either disable this part of the mod, or remove a couple of the recipes. Mostly the ones for indium, iridium, naquadah, osmium, niobium, americium, uranium, thorium, deep iron, naquadria, Pu 241, europium, tungsten, black plutonium, cosmic neutronium, titanium, trinium, yttrium, platinum, draconium, oriharukon, and probably a few others, but these are the worst. 

Some of these are cheaty because they bypass smelting the ingot, which means this recipe is significantly easier than smelting the ingot in the ebf. As the transmutation uses nuggets it bypasses the smelting requirement. If you won't remove these, at least change them to tiny dust -> 3 tiny dusts. This goes for things like osmium, naquadria, naquadah, etc

Some of these are cheaty because its endgame stuff and you're getting it for free from a thaum crucible. Mostly the fusion products and the infinity stuff. No reason imo for this to exist, its incredibly easy to make these materials with transmutation, compared to the difficulty of making a cosmic neutronium ingot, or europium, etc. 

The rest are OP because they give very simple ways of making things that should be complex/large power sinks. Such as indium, titanium pre moon, plutonium, tungsten pre T2 rocket, etc... 

Seems like it autogens recipes for almost everything, so it's probably easier to just remove the transmutations from it all together. There's still the ones in the thaum tab, and I think we can add more there if we want them.

**Comment by DoomSquirter** [comment]
I want to express that this topic/whole conversation is held off till after 6.6 lands and is considered stable.  I really feel we need to try to get a 6.x stable version out and tested w/o adding every knee jerk reactionary modification w/o actual discussion about it.  I'll hold off on discussing the finer points of this whole thing till after stable 6.x.

**Comment by richardhendricks** [comment]
I agree, at this point we need to focus on getting 6.x out.  There have been some pretty major balance changes with this release compared to the stable 5.1, and we need to let the playerbase digest them for a while before changing anything else.

That being said, the transmutations do seem really OP.  IC2 Crops/bees take a major amount of time and investment, and unless these can equal that, their outputs need to be seriously reduced.

**Comment by Paolkageist** [comment]
I wouldn't think disabling them for 6.7 or whatever the next minor version is would be a big deal as far as modpack stability goes, but they are insanely OP.  The only limiting factor in some of the higher-end duplications is the Nebrisum aspect, but you can get that from platinum.  Once you make a single Osmium or Naquadah ingot, for example, you can duplicate it for the cost of 5 platinum dust, which you can easily get in large amounts from Ceres.  Nuggets like Indium, Europium, Iridium, Tungsten, P-241, Americium, and Oriharukon don't even have that restriction, and you can duplicate them for almost nothing once you have a single nugget.

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by 0lafe** [comment]
Can't you also get infinite Nebrisum from beans? Or do they not do GT stuff. 

Anyway, its a simple change, its in the config for WG

>"ore/crucible" {
    B:"Enable clusters"=true
    B:"Enable transmutations"=true


At least a lot needs to be added to the blacklist

**Comment by bartimaeusnek** [comment]
@0lafe you cant get "infinite Nebrisum from beans". only things that contain it are platinum and a few others similar to it. Also there is a config for blacklisting. If the material hasnt propper set aspects it will fallback to nebrisum. This arent "completely OP" recipes, they just oriante at the materials Aspects, if they arent balanced (too weak/too strong) the transmutation/cluster recipes reflext that issure.

**Comment by 0lafe** [comment]
There's a bunch that are still OP even coming from platinum. Indium, the fusions, avaritia stuff, etc. It's also way easier to smelt platinum than many of these materials. There's also the ones that don't use nebrisum. Also beans do work, even if they could be buggy or w/e. I've used them no problem, others too, they're not a death sentence

**Comment by 0lafe** [comment]
Huh, ok. Still think it should be black listed in case we get a nugget some time. No reason to keep it

**Comment by mitchej123** [comment]
This should be revisisted
