### ISSUE TITLE
typo in the recipe book of nano circuits

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#4064]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i scanned a wetware mainframe to see the new recipe of the nano circuits
#
#### What happend instead? (Attach screenshots if needed)
there is a typo for the 10th input item:
![image](https://user-images.githubusercontent.com/12850933/52180956-9493f380-27ec-11e9-93c2-24ac5c5f2653.png)
it doesn't exist

![image](https://user-images.githubusercontent.com/12850933/52180965-af666800-27ec-11e9-902c-96b9d2867d7b.png)
should be this name

it's only visual because if i put the right amount of thin silicone rubber sheet it works

**Comment by Dream-Master** [comment]
@boubou19 
lets thest this with 2.0.6.7
