### ISSUE TITLE
Fluid Terminal Refuses to use IC2 Normal Cells

### ISSUE THREAD

**Issue by Lithorn** [GTNewHorizons/GT-New-Horizons-Modpack#4065]
#### Which modpack version are you using?
2.0.6.7 DEV
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Insert Cell to extra fluid in 1000l amounts
#
#### What happend instead? (Attach screenshots if needed)
Terminal refuses to insert fluid.
#
#### What do you suggest instead/what changes do you propose?
Check recent changes and figure out what happened. Cells can still hold the liquids stored inside the terminal, just can't withdraw from the terminal any longer. Must use Universal, or Drums. Not tested Vials. I have Propene cells on hand, but can't get more propene from the terminal unless I use a Universal.

**Comment by Jocroy** [comment]
This has been an issue for a while. It sometimes works and sometimes it doesn't. Most of the time it works again after a server restart and randomly stops. So if you are in SP, it ptobably works to reload the safegame. I do have Optifine though, maybe this causes the randomness in my case.

**Comment by eigenraven** [comment]
Fixed in dev for a while
