### ISSUE TITLE
[Idea] Basis for Advanced Plastics

### ISSUE THREAD

**Issue by Spluff5** [GTNewHorizons/GT-New-Horizons-Modpack#4093]
### The Issue
As we get to thinking about the UHV+ tiers, we run into a problem that all the technology becomes this ultra-futuristic, cosmic tech while plastic remains basically just being oil products. I wanted to think of a way to have UHV+ plastic without just processing oil in a new way. I think the only way to do this is to stray away from plastics that actually exist irl, since real plastics are just made from oil.

### The Idea
I have posted about this before with my idea for Kroton as a "plastic" but that used not yet implemented machines to craft. My new idea is to make plastic from the alien plants found on Barnarda.

We already have metals that are "Space" versions of other metals (Eg. Black Plutonium, Meteoric Iron). So, why not have "space oil" as well? By putting the barnardian logs into the Pyrolyse oven, you could produce a variety of products with alien sounding names like "Xenoxene" or "Liquid Radox". These could then be used in the chemical reactor with other unusual materials from space like Mysterious Crystal to make alien plastics.

**Comment by bartimaeusnek** [comment]
To expand this idea:
Oil must be present in the BioVat with Bacteria gathered and processed, from Barnada F + TCetiE, to produce "Xenoxene" that then can be used in the Pyrolysis with "space logs" to create "Liquid Radox". The "Raw Radox" (1000) is then Distilled into:

1. "Super Light Radox" (1L)
2. "Light Radox" (10L)
3. "Heavy Radox" (10L)
4. "Super Heavy Radox" (100L)
5. "Deluted Xenoxene" (10L)
6. BioMass (10L)
7. Bacterial Sludge(9L)
8. Water (300L)
9. Creosote (250L)
10. Oil (100L)
11. Heavy Oil (150L)
12. Super Heavy Oil (50L)
13. Ash (1Pile)

Super Light Radox must then be cracked with a Plasma, to create Cracked Super Light Radox  that can be distilled into:

1. "Radox Gas" (1L)
2. "Light Radox" (999L)

Light Radox, Heavy Radox and Super Heavy Radox can provide different Elements for Fusion / Reactors, they are mainly used as fuel.
Deluted Xenoxene can be distilled into Water & Xenoxene.
Radox Gas must be polimerized with Oxygen and Titanium Plasma in a Large Chem to yield Radox Plasma, which then must be cooled down in a Vaccum Freezer to yield Polimerized Radox that can be used as Plastic.

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/tree/RadoxPlastic

**Comment by draknyte1** [comment]
> Radox 

https://en.wikipedia.org/wiki/Radox

**Comment by richardhendricks** [comment]
What tier do these quests need to be in?

**Comment by DietmarKracht** [comment]
UV as the recipes currently use uv to process
