### ISSUE TITLE
DE staff is glitched

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#4114]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i was mining with a fully upgraded DE staff of power with junk mode activated and enceladus subsurface rock set into the junk filter
#
#### What happend instead? (Attach screenshots if needed)
the staff keep placing it in inventory
#

**Comment by DietmarKracht** [comment]
You need to set at least mining size of 3x3. Otherwise the junkfilter doesnt work

**Comment by boubou19** [comment]
junk filter was working on 7x7 before
