### ISSUE TITLE
Projectile / Damage to player causes server Time Out / Crash

### ISSUE THREAD

**Issue by wiloxe** [GTNewHorizons/GT-New-Horizons-Modpack#4119]
#### Which modpack version are you using?
1.7.10 2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
Private server hosted with friends.
#
#### What did you try to do, and what did you expect to happen?
Was fighting a skeleton, I blocked a fire arrow with a leather shield and it's expected to function without issues.
#
#### What happend instead? (Attach screenshots if needed)
Instead, after fire arrow hit and lit me on fire the server froze and timed everyone out from the server and threw a bunch of errors into console then crashed.
#
#### What do you suggest instead/what changes do you propose?
What I suggest could be a hard answer but the optimal outcome would be to have this issue solved by the developers and then patched.

Suspected cause: mods.battlegear2.items.arrows.EntityFlameArrow

Crash log: https://pastebin.com/B6vktxya

**Comment by wiloxe** [comment]
Correction:

so it turns out that the cause is not specifically Mine & Blade Battlegear 2 but projectiles causing some form of damage to the player or so.
I don't know the exact cause myself yet.

https://pastebin.com/K4CpDuzS

**Comment by boubou19** [comment]
the stack trace is so huge...

**Comment by draknyte1** [comment]
```
java.lang.StackOverflowError: Ticking entity
    at java.security.AccessController.doPrivileged(Native Method)
    at java.lang.ClassLoader.checkPackageAccess(Unknown Source)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:146)
```
Related to https://github.com/GTNewHorizons/NewHorizons/issues/4110

It's uhh, some weird new issue we're probably gonna see a bit..
