### ISSUE TITLE
Rocket Engine Basic and Advanced no fuel

### ISSUE THREAD

**Issue by Dr4cos** [GTNewHorizons/GT-New-Horizons-Modpack#4122]
#### Which modpack version are you using?
2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
Getting Fuel into the Rocket engines

#
#### What happend instead? (Attach screenshots if needed)
Rocket Engine isn't taking in a fuels
Old Fuels:
![rocket 1](https://user-images.githubusercontent.com/33230359/53050571-eb125a80-3499-11e9-8483-ae87a3173d0d.png)
![rocket 2](https://user-images.githubusercontent.com/33230359/53050572-ec438780-3499-11e9-92e7-9bf462b6fd78.png)

Rocket Fuels:
![r1](https://user-images.githubusercontent.com/33230359/53051024-1cd7f100-349b-11e9-8fff-9f3f2de98517.png)
![r2](https://user-images.githubusercontent.com/33230359/53051025-1cd7f100-349b-11e9-86ec-f4bb1c1f8ad7.png)
![r3](https://user-images.githubusercontent.com/33230359/53051026-1d708780-349b-11e9-9fce-60c83c5c854c.png)
![r4](https://user-images.githubusercontent.com/33230359/53051027-1d708780-349b-11e9-8d14-c697ceb4b210.png)
![r5](https://user-images.githubusercontent.com/33230359/53051028-1d708780-349b-11e9-9a11-72dcac900a7e.png)
![r6](https://user-images.githubusercontent.com/33230359/53051029-1d708780-349b-11e9-828d-4c52a0661f45.png)

#
#### What do you suggest instead/what changes do you propose?
Fixxing pls xD

**Comment by Dream-Master** [comment]
@draknyte1 any idea ?

**Comment by Dream-Master** [comment]
@Dr4cos the fuel mixes not working yet but normal fuel should work. Did you test normal fuel/diesel ?

**Comment by Dr4cos** [comment]
Like seen in the 2 screen at the beginning, 
I tested:
fuel(heavy+light) 
cetant-boosted 
The octane gasoline

**Comment by Dream-Master** [comment]
but i dont see you using pure diesel or fuel

**Comment by Dr4cos** [comment]
@Dream-Master 

![2019-02-20_16 10 22](https://user-images.githubusercontent.com/33230359/53101673-87843d80-352a-11e9-87b8-258f602cc52f.png)

![2019-02-20_16 10 25](https://user-images.githubusercontent.com/33230359/53101687-8d7a1e80-352a-11e9-9e38-91c21db3e804.png)

![2019-02-20_16 12 29](https://user-images.githubusercontent.com/33230359/53101946-09746680-352b-11e9-9f7d-04d502bd5780.png)

**Comment by Dream-Master** [comment]
i rember i get a missing item and block message last update (Forestry oil capsule) Maybe related to this issue ?

**Comment by Anarack** [comment]
Dream you know alk talked about removing the cheapo/diesel/gasoline base fuels for his rocket engines right? In exchange for the fancy ones.

**Comment by draknyte1** [comment]
```
+ Added new Rocket Fuels and various chemical compounds to produce them.
% Reworked Rocket Engine generators, to now use new fuels and produce heavy pollution.
```
100% Intended.. While this change isn't currently applied to Galacticraft, it's still been changed for everything else.

https://github.com/draknyte1/GTplusplus/commit/cd4e9d4776bfbe26c7572d5bd8ba667c3c216449

**Comment by Ngar1** [comment]
Its a realy hard break and throw people two levels down from IV to HV -> this is intended? 
I have to build 100 x HV combustions now to come up again, because every machineries stands still.

**Comment by draknyte1** [comment]
They still produce the same amount of power.. They just use better fuels and produce pollution... 🤷‍♀️

**Comment by Dr4cos** [comment]
@draknyte1 the pollution is not the problem(that was really cheaty). But if you had the base only use the rocket engine you are kicking players back to stone age from IV happened to 3 players on our server here (4 with the afk player), had myself the problem with the naquadah off with the bug and no power from the rockets -.- (they were the backup units) + plus the new Core control Units thing = stone age

Maybe would be better to give more/longer power with the better fuels or damage the rocket engine in some way to get the players to use the new ones and the fuel are only usable in the Rocket engine.


But the engine don't take in the rocket fuel (Screens in the first post) or what fuels are for the engine???

**Comment by draknyte1** [comment]
```
//Rocket Fuel Mixs
H8N4C2O4 Rocket Fuel
Rp-1 Fuel Mixture
CN3H7O3 Rocket Fuel
Dense Hydrazine Fuel Mixture
```

Probably the 4 rocket fuels?

It was changed ages ago and it's not new knowledge.
Welcome to Beta updates, you find these things out and now you get to change them.
Such is life.

**Comment by Dream-Master** [comment]
@Dr4cos using Betas is very risky i chat with Dogboy and he said he will ask me the next time about beta or stable version before update.

**Comment by Dr4cos** [comment]
I know it's a beta update. I do not mean that in any way as a criticism. You can also absolutely nothing for when a beta update is used.
I just mean "people should read to read or just look in NEI ..." I and others have probably read the Nei, it just did not work ;).
I only tested the old fuels because the new ones did not work.

The rest was meant only as an idea of ​​how to prevent people from facing such problems.

I understand English quite well, but it's hard to express myself accurate. But since I did not see any of the problems that occurred to me here, I just reported what I noticed.

THIS is not meant as a complaint. But I, for example, have not found complete changelogs for 3-4 hours until now. I also do not know so well how Github works so I don't know if there is a function here.

I like GtnH as well as GT ++ very much as you might notice because my base is almost not running at all;). No ore processing or production. 

I will certainly continue to play the pack. Furthermore, I also hope for many newly added content.

**Comment by Dream-Master** [comment]
@Dr4cos reporting bugs isnt a bas thing. We can only fix reported bugs. I mean its risky using beta updates not criticism.

**Comment by Dr4cos** [comment]
I know that xD. I also use it really not voluntarily.
Will go and look for more broken things xD,wish me bad luck with it less work for Dream-Master ;).

**Comment by Dream-Master** [comment]
in my testworld rocket fuel and diesel work fine

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/4130
![image](https://user-images.githubusercontent.com/2970688/53728433-11110500-3e73-11e9-8b08-bcaaf15d1bf7.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/53728663-8977c600-3e73-11e9-84f6-6fdd50058d5b.png)
after landing

**Comment by Dream-Master** [comment]
rocket engines not accepting any rocketfuel anymore . I tested it too.
@Dr4cos make a issue on gt++ side please. Thanks
https://github.com/draknyte1/GTplusplus/issues

**Comment by draknyte1** [comment]
It’s not an issue? It’s intended..

**Comment by Bluebine** [comment]
They don't even take the rocket fuels.
They don't accept ANYTHING.
That's the problem.

**Comment by draknyte1** [comment]
> They don't accept ANYTHING.

And where is that stated at all? It's not. I'm reading Dream's message as him testing with Diesel or the other two fuels and not actually testing with mine..

**Comment by Bluebine** [comment]
The first post shows him trying to put in the 4 rocket fuels, too.
Has this been fixed, or do you want me to put it in your Github?

**Comment by draknyte1** [comment]
> Has this been fixed, or do you want me to put it in your Github?

Obviously not? Lol.

**Comment by Bluebine** [comment]
alright I added it to my existing rocket fuels ticket

**Comment by Dream-Master** [comment]
@draknyte1 i tested with all your fuels after i read the issue again. Non of your new rocket fuels (if in universal cells, gt cells or flasks) work. So the have NO fluid to burn right now.

**Comment by draknyte1** [comment]
Fixed in Dev.
