### ISSUE TITLE
highly ultimate transformer in step up mode is broken

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#4135]
#### Which modpack version are you using?
2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
wanted to make UEV power by using UHV transformer in inversed mode.
here is how i set up the UHV transformer:
![2019-02-21_18 57 11](https://user-images.githubusercontent.com/12850933/53191094-3dbf5400-360b-11e9-9228-e028f7ecd95d.png)

then i put directly next to it a battery buffer (16 slot version):
![2019-02-21_19 00 39](https://user-images.githubusercontent.com/12850933/53191135-5465ab00-360b-11e9-816b-d9abbca1bf33.png)
as you can see the battery buffer is getting energy in itself but the transformer has energy in it:
![2019-02-21_19 00 42](https://user-images.githubusercontent.com/12850933/53191192-7b23e180-360b-11e9-8ffb-d53978d9c38b.png)

same happens with a cable between them:
![2019-02-21_19 05 50](https://user-images.githubusercontent.com/12850933/53191282-b4f4e800-360b-11e9-85d1-fb7ed02ace9a.png)

I also tried to link the transformer to an UEV energy hatch and nothing happens(red arrow is my transformer)
![2019-02-21_19 07 20](https://user-images.githubusercontent.com/12850933/53191438-1cab3300-360c-11e9-84a7-543f9a057004.png)

**Comment by 0lafe** [comment]
Not a fix, but in the meantime the 4A and 16A ones work up transforming iirc. I think we had the same problem in 2.0.2.7

**Comment by Dream-Master** [comment]
@boubou19 @0lafe is this only broken in UEV and UHV ?

**Comment by 0lafe** [comment]
from what I was doing with them in 2.7 it seemed like all of them past UHV did this

**Comment by Dream-Master** [comment]
so a issue with the core mod I guess.

**Comment by boubou19** [comment]
still broken in 2.1.0.0

**Comment by Prometheus0000** [comment]
They're defined starting at line 3524 in GT_Loader_Machines of the coremod, and extends the GT_MetaTileEntity_Transformer class. There's probably something in there that needs changing to allow higher tiers.
