### ISSUE TITLE
IC2 Crops balancing

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4156]
Change these up a little bit to make them fun.

Blazereed will drop small piles of blaze dust.  If a block of blaze is beneath it, it will also drop blaze rods. Change so harvest only drops 1 tier.

Tearstalks will drop small piles of salt.  If a block of ghast tears is beneath it (or solid salt/salt ore), it will also drop ghast tears. Change so harvest only drops 1 tier.

**Comment by bartimaeusnek** [comment]
if you want to modify a highly abstract base class, good luck with that.

**Comment by richardhendricks** [comment]
I know nothing about Java, so CHALLENGE ACCEPTED

**Comment by bedrill64** [comment]
I'll just leave blazereeds with blaze powder, its painful enough to turn them into blazerods.

**Comment by draknyte1** [comment]
> I know nothing about Java, so CHALLENGE ACCEPTED

Back into your box!

**Comment by richardhendricks** [comment]
What do you mean?  Blazereeds only give powder?  Right now they give powder and occasional rods.

**Comment by bedrill64** [comment]
I mean, powder without block, rods with block.

**Comment by shawnbyday** [comment]
I like the powder without block and rods with block idea.

**Comment by richardhendricks** [comment]
There is a couple of different tweak options.  I like the idea of only getting the special drops when the crop hits max size, with the normal drop otherwise.  That would do what is needed and isn't a big change that should affect crops too badly.

For that change, we would need a harvest size for blazereed and tearstalks 1 less than maxsize, and add the block requirements.  Then adjust the code so that at < max size, you can't get the special drop.

ezpz

**Comment by richardhendricks** [comment]
This might cause issues with automated harvesting.  Need to confirm that automated harvesting always waits until final stage before harvesting occurs, otherwise you may not get the special drops.

**Comment by repo-alt** [comment]
Crop harvester waits for the last stage by default iirc. It needs cropnalyzer inside to _not_ wait for the last stage drop, like for potatoes it will by default harvest poisoned potatoes.

**Comment by richardhendricks** [comment]
There's the crop harvester, but also Forestry Farms too. I don't think Open Computers or golems support harvesting IC2 crops.

**Comment by richardhendricks** [comment]
Huh, didn't know about the potatoes bit. Is that the only crop that matters? I guess you could use it to force only sugarcane harvests with stickreeds? Not sure if we need to include that in the questbook, it is pretty esoteric.

**Comment by repo-alt** [comment]
OC robot may harvest crops, why not, I remember adding some adapter code for the robot to use. But the robot have access to the growth stage, so this issue is irrelevant.
No idea about the forestry farm though (pretty easy to check with potatoes and stickreeds).
