### ISSUE TITLE
Thaum crop nerf

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#4158]
#### Which modpack version are you using?
2.0.6.8
#

#### What do you suggest instead/what changes do you propose?

Thaum crops are too good. Metaleat/redlions/glieonia all give a ton of resources comparable to almost nothing in their respective tiers. Idea is to remove the ability to get more seeds with a fortune tool from fully grown crops, so you need to craft each seed instead of just 1. Then lower the yield. Maybe 1/10 current speed for the iron one, 1/20 for glowstone, and I never used redlions so idk a new speed that would be good. Maybe also 1/10 but I'll leave that to people who know how much they make. 

Lastly change the recipes for seeds a little to put them 1 tier past the tier that mainly uses their resources. By this I mean make metaleat use something MV (maybe 1 Al ingot/seed? Could be anything really), redlions use HV and glieonia use something EV. Should also probably make redlions/glieonia use infusion recipes. Redlions being 1 block Redstone + 4 ingots stainless + 4 void ingots + some essentias? Glieonia being 1 glowstone block + 4 titanium ingots + 4 shadow ingots? Maybe switch shadow/void if void is higher tier. Also don't have to be these recipes, suggest better ones if you got them.

**Comment by Bluebine** [comment]
One nerf at a time, man. Seriously.
The speed thing, I agree with. Let's start with that- reduce their speed a bunch.
Then once we've done that, WAIT, see how they are, and nerf more IF NEEDED.
You're going nuclear and your suggestions would bring them from OP to useless instantly.

**Comment by 0lafe** [comment]
At least also remove fortune. That ones just kinda dumb.

**Comment by shawnbyday** [comment]
I recommend:

- 2x as long to mature.
- Remove duping on seeds.

I don't like looking at nerfing as a tool to make 20% of people (abusers) more balanced while 80% of people (just trying to have fun) are so affected they don't even see the point in going after something.

Point is abuser will always be an abuser until you push them so far they quit but at that point all the people that make up the majority of our community are already gone because they don't have time to invest in such things.

Having an abundance of resources along with a way to make more (even if it can be scaled way up) will make servers more fun to play on because it won't take you a year to find redstone or iron or whatever.

I'd also suggest that along with bringing these down a bit that you bring bees and IC2 crops back up a bit. Giving people a tiny pile of dust (whether guaranteed or chance) or even giving them via specific combs being processed in my mind is a good balance between "forget this" and "if I put enough time and effort into this it will be worth it".

Most of the crops can gate themselves by requiring blocks of the material they grow under them. Bees gate themselves by having to get to certain tier planets to get specific ones.

**Comment by Bluebine** [comment]
> At least also remove fortune. That ones just kinda dumb.

as I say... do one thing at a time. You're already suggesting literally requiring 10x the amount of them for the same yield, don't ALSO make them far harder to obtain at the same time, without waiting to see how balanced they are.

**Comment by WarlordWossman** [comment]
It's funny that everybody always embraces the "GTNH is so hardcore" memes but then defends obviously OP things when somebody suggests to address them. Does that mean I 100% agree with 0lafe? No, but making them grow slower sounds like an idea, also what is the point of the seed recipe if you can dupe them with fortune after you got a single one?

**Comment by mitchej123** [comment]
I'm fine slowing them down, but he's taking slowing them down to uselessness.  5% speed really?  Let's start with 50% speed and go from there.  Hardcore != tedious.

**Comment by richardhendricks** [comment]
No duping at 50% is what every seems to agree with, dunno what you mean about "defending" it.

**Comment by WarlordWossman** [comment]
How are they useless when you can just make a bigger farm? Do you also plant a single wheat and complain that it takes ages to get enough wheat for bread? 50% is twice the plants for the old rates, seems like it hardly would have an impact, the 10% for redlons would actually encourage setups with world accelerators, if you think about it you get ruby (chrome, aluminium), pyrite (iron and sulfur), silicon and mercury from redstone, that is a lot of renewable ressources from a single source, doesn't match at all how weak renewable ressources are when you have to grind through IC2 crops etc.

**Comment by mitchej123** [comment]
> How are they useless when you can just make a bigger farm 

RIP TPS

**Comment by mitchej123** [comment]
I vote we fork GTNH and make 
1) GTNH - Hard, but not Tedius
2) GTNH - TEDIOUS AF (0lafe edition)

**Comment by WarlordWossman** [comment]
Random ticks from crops shouldn't destroy TPS nearly as much as other things in this pack, if you have a lot of mobs with tags to not despawn it's kind of funny to actually bring this up.

Also I wouldn't say it's tedius af, as I said the amount of renewable ressources you currently get for close to no effort is a bit strange when compared to IC2 crops, have not seen people use redwheat for example.

**Comment by mitchej123** [comment]
ic2 crops are tech based; redlon etc are magic based.  They're not directly comparable.  

I think redwheat needs a bit of a buff, and redlon a bit of a nerf, but not an 0lafe.

**Comment by Anarack** [comment]
Well for one redwheat is shit compared to glowflower even with the extra energy costs. and while crops don't do a ton, think about harvesting.

**Comment by DoomSquirter** [comment]
I've never used fortune to dupe the seeds.  I'm totally fine with removing that.
I have a simple 9x9 golem maintained farm.  gorgo just attends that farm with no special upgrades and has most of the plants in them.  yield isn't terrible but it's definately not OP.  what is OP tho is letting it run constantly w/o power needed to maintain gorgo and I just get free shit ad nauseum.

doing this on a server with chunk loading equals so much free resources it aint even funny.

I say nerf servers.  servers have to be kept alive by randomly intervalled votes to shutdown.  if a minimum vote is not reached, server is shut down, requiring attention.

Hey lookit me, I can be 0lafe for a day!

**Comment by finkledoodle** [comment]
Removing fortune makes a lot of sense. The only reason stuff like redlon seems OP though is because the other options just suck so much. If something gives more resources than anything else in that respective tier, how about we buff the other stuff in that tier to be more comparable instead? It solves the problem, and doesn't upset the players with another nerf.

**Comment by mitchej123** [comment]
I'd say meet in the middle.  Tone down redlon and gang a bit, and buff up the poor redwheats

**Comment by richardhendricks** [comment]
Yeah redwheats are garbage.  They are beaten by glowflowers, but GF require an MV centrifuge to get redstone. Honestly though you can just wait until MV before worrying about redstone in quantity.

**Comment by mitchej123** [comment]
Redwheats are such a pain to breed though - they should be buffed!  effort vs reward is way off.

**Comment by richardhendricks** [comment]
I agree, not sure how much control we have over them.  Could add a new crop that drops blocks of redstone.....

😜

**Comment by 0lafe** [comment]
> If something gives more resources than anything else in that respective tier, how about we buff the other stuff in that tier to be more comparable instead? It solves the problem, and doesn't upset the players with another nerf.

Ideally we wouldn't want to simply balance it around existing options, but balance the output for the tier it's used for. Need some numbers of current rates, but it would probably be useful to give a goal of x crops producing y resources, and make sure that lines up well with it's availability. You don't need much Redstone in MV/HV, more just that chrome is nice to have. Maybe balance it so you get as much in a day as you'd get from 1 mining trip? That seems kind or fair to me. Maybe a little less, because no one's really mining the same ore every day.

**Comment by Dream-Master** [comment]
I not nerfed thaumic bases completly so i can change recipe ofc.

**Comment by richardhendricks** [comment]
Todo List

- [ ] Remove fortune duplication on all Thaumic Bases seeds
- [ ] Slow crop speed down to 33% - compared to IC2 crops, still pretty fast and ezpz to make more.

I don't agree on tiering the seeds, nothing else does.

**Comment by 0lafe** [comment]
The tiering is more to give them a cost. It could be tiered different, but the seeds themselves are kind of cheap to make. So removing fortune is good, but they're still fairly easy to spam seeds

**Comment by mitchej123** [comment]
> The tiering is more to give them a cost. It could be tiered different, but the seeds themselves are kind of cheap to make. So removing fortune is good, but they're still fairly easy to spam seeds

One nerf at a time buddy!  Let's see how this one performs and then we can further adjust!

**Comment by DoomSquirter** [comment]
I'm very dissapointed that the consensus was 100% in favor of removing fortune but there was an enormous divide in changing the behavior of the actual plants themselves and yet I see that todo to do exactly that.

I think there was a limited consensus to change the recipes a bit (infusion I think) but that was more or less a concession to give instead of changing crops recipes.  but Again, I am fairly certain that the majority was against changing the behavior of the crops (speed, etc).

**Comment by Bluebine** [comment]
I think the crops should be adjusted individually- they're at very different levels of power.
To change moron's suggestion:
remove fortune duplication- perfectly fair change, should be implemented
glieonia to 1/5th speed, lazulia to 1/3rd speed, and redlons to 1/2 speed. Glieonia is the fastest by far, lazulia is a lot slower but still gets reasonably fast with lots of sprinklers, and redlons are already really slow.

**Comment by sthegreat** [comment]
So I just want to note that redlons are actually pretty slow, and sprinklers don't work on them. So they really don't need much of a nerf, only the ones you can sprinkler (glowstone, lapis, etc.) are even fast at all. For those ones I think a 1/2 or 1/3 speed as well as the removal of fortune is fine. Adding some high tier infusion is really unnecessary and an overnerf... consider that glowstone processing is limited by centrifuging anyways, and what op things is someone going to do with a lot of lapis or iron?

**Comment by DoomSquirter** [comment]
the one thing that ppl overlook is pretty simple...

none of the stuff you can get from these thaum bases crops allow you to skip tiers, enable ez mode, or anything else.  they are nice QOL adjustments and alternative.  FUCK COMPARING THESE TO BEES OR CROPS.  some ppl might avoid crops on religious grounds.  same with bees.  it gives those ppl alternatives.  better/worse than crops/bees?  adjust accordingly, but what I said first is the most important bit.  

it's not like any of these things give you pure titanium or tungsten.  it's all the vanilla bs that's mostly inconsequential.  get a grip on yourselves.

**Comment by richardhendricks** [comment]
Redlons give chrome, and glieonia give gold and redstone, so yeah, their speed does matter. I'm not for nerfing them out of existence, just for putting them in line with other methods.

**Comment by DoomSquirter** [comment]
chrome is meaningless, gold is absolutely meaningless as is redstone, lapis.   you seem to have your mind made up so whatever.  nothing I can do here.  u do u

said it before I'll say it again.  when you put things in #vote to be voted upon and pinging everyone to the vote's existance.   that was a good way to get consensus, not just asking the crowd of monkeys on crack in discord their opinion and watch good ideas get drowned out by poo flinging.

**Comment by richardhendricks** [comment]
You do realize #vote is literally on discord? 

Chrome is meaningless?  Then why the fuck are you doing these crops to being with?  Make up your mind, either they don't matter or they matter so much your pussy hurts.

**Comment by richardhendricks** [comment]
Voting on this change

- Remove fortune duplication on all Thaumic Bases seeds

- Slow crop speed down. Redlon 50%, Lazulia 33%, Glieonia 20%. Lazulia and Glieonia can be accelerated with sprinklers so they need more of a hit. Look at sweed and the string crop as well.

**Comment by DoomSquirter** [comment]
oh I'm sorry moron, did I attack you?  Are we attacking now?  I didn't get the memo.  always forget that ppl attack others when they run out of actual facts or arguments.

yes I realize vote is on discord.  wtf?  I don't understand ur concern there.

you know what else is on discord?  the original version where you said my pussy hurts.  my pussy's been dead for many years you clod.  

the point, if you even gave a fuck to actually read my statement, was to say that none of these resources will give you a super edge on things.  we aren't talking about world changing resources like getting instant titanium or tungsten or anything....

**Comment by Shattered2909** [comment]
Remove duping. Make the seeds a bit more expensive. Do not nerf speed/output.

**Comment by combusterf** [comment]
Redlon isn't farmable in the conventional sense; The seeds may look cheap in comparison but in addition to that I spent half a direcrafting table's worth of diamonds on block breakers to automate the farm itself. That is an investment of an order of magnitude larger than an IC2 harvester, and thus IMO  deserves to yield a return of an order of magnitude larger.


A sidenote about nerfs and hoes, you don't need fortune to multiply redlon; breaking full grown stems with bare hands drop 0-3 already (2.0.7.0).

**Comment by richardhendricks** [comment]
...you could have just made a steve's cart with a drill?

**Comment by combusterf** [comment]
I asked in the chat before I posted my thoughts; steves' requires maintenance by design, and repeated car replacement in practice.

**Comment by richardhendricks** [comment]
OK, after further bickering and knuckles to the jaw, we will

- [ ] remove duping seeds via fortune or normal drops.  Additional crops will require doing the recipe again.

Recipe and/or speed can be looked at again in the future if it is problematic.

**Comment by Scottishprog** [comment]
I am ok with the not-duping.  

I would keep the redlon nerf to a minimum.  No more than 1/3 reduction in speed. 

Keep in mind, in HV I am severely chrome starved. What _adequate_ sources of chrome are there besides crops/bees? My concern is not over redlon as such, but an adequate source of chrome, given a sufficient amount of infrastructure. Keep in mind, one chrome is 60 redstone, so even mining redstone is _not_ a sufficient source!

**Comment by 0lafe** [comment]
Mining redstone kind of is sufficient. If you get a whole vein, and turn the redstone to chrome too, you get a substantial amount. Especially for HV. Easy 2k+ stainless per vein without boosting the ore output, which would 4x that. 

Another option for speeds is to blacklist them for acceleration methods. No WA/sprinklers/lamps/etc. Would make their speeds kind of OK, but also keep them in their tier in a way.
