### ISSUE TITLE
issue regarding fired clay water buckets and cauldrons

### ISSUE THREAD

**Issue by Sudoloo** [GTNewHorizons/GT-New-Horizons-Modpack#4160]
#### Which modpack version are you using?
2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
n/a singleplayer
#
#### What did you try to do, and what did you expect to happen?
i was playing on the newest version of the pack, with hardcore darkness disabled because my poor eyes.

i was doing the 0.5 tier redstone quest  and i noticed i was unable to fill a cauldron from vanilla minecraft using a fired clay waterbucket, i asked in the help channel in the discord if it was intended behavior and i was told it was not, i tried using other cauldrons and other buckets and through no means was i able to fill a cauldron with a clay bucket. thaumcraft cauldrons work fine.
![image](https://user-images.githubusercontent.com/4110158/53471359-59bf5d00-3a32-11e9-8c99-1c3e2455926f.png) <i tried an extensive ammount of cheated in items to get this one feature working as noted by the ichorium tools>

#
#### What do you suggest instead/what changes do you propose?
put something in the quest description that implies its a feature or fix it, i dont mind either way.

**Comment by Dream-Master** [comment]
Known issue but dont have a workaround. Need to change this code wise.
A quest info i can add very quick. Which quest need this info ? @Sudoloo

**Comment by Sudoloo** [comment]
![image](https://user-images.githubusercontent.com/4110158/53475027-d9eac000-3a3c-11e9-98ba-3d81193c375d.png)
this quest, the part with"after this, fill a cauldron with water,", right after this point, you could say "but you will  need a new iron bucket as the fired clay bucket just isnt fit for the task".
you can insert the quote bit verbatim and it should line up pretty well, just switch the following "and" and with a period

**Comment by Dream-Master** [comment]
ah ok will add the hint

**Comment by richardhendricks** [comment]
Could also add an iron bucket quest reward

**Comment by Prometheus0000** [comment]
Apparently, this is still not fixed.

**Comment by draknyte1** [comment]
Gotta be fixed in vanilla code if memory serves me correctly. 🤔

**Comment by Dream-Master** [comment]
no not works in sp

**Comment by chavalitp** [comment]
I made the pull request, please help review code.

https://github.com/GTNewHorizons/IguanaTweaksTConstruct/pull/4/commits
