### ISSUE TITLE
Fluid lost when transporting fluid from GregTech pipe to EnderIO Conduit

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#4161]
#### Which modpack version are you using?
2.0.6.2 and 2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
Private Server and Single
#
#### What did you try to do, and what did you expect to happen?
Transport fluid using EnderIO conduit and GregTech pipe.
#
#### What happend instead? (Attach screenshots if needed)
Sometimes fluid lost when transporting fluid from GregTech pipe to EnderIO Conduit.
This issue occurs when transporting destination of Conduit and GregTech pipe is full

・Transporting destination of Conduit and GregTech pipe is full.
![2019-02-27_20 05 15](https://user-images.githubusercontent.com/40425798/53487566-3991ab80-3acf-11e9-84ab-325fb1101474.png)
![2019-02-27_20 05 10](https://user-images.githubusercontent.com/40425798/53487568-3b5b6f00-3acf-11e9-8569-dafd6cf1af20.png)
・Fluid lost
![2019-02-27_20 05 17](https://user-images.githubusercontent.com/40425798/53487590-49a98b00-3acf-11e9-97ec-1cda9bc7e064.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it please.
Due to this issue, tens of millions mb of chlorine has been lost....

**Comment by richardhendricks** [comment]
Why are you not putting the enderio conduit directly on the GT tank?

**Comment by 0lafe** [comment]
Eio conduits have really poor pull speeds, but transport infinitely. So it's better to push into them, and idk if pumps can do that. It's kind of weird with what they consider a pull or a push, but if you do it right you get the speed of the non eio push, and if you do it wrong/only pull with eio, you get like 500L/t? Something lower than many pumps/pipes/other pulling methods allow. You specifically notice it when they're on output hatches, you get faster speeds than simply pulling from another side of the hatch (which I don't think you can do anymore?)

**Comment by yukieiji** [comment]
Because we don't have much material, we use pipe and Conduit together.
Basically I use GT pipes, but we use Conduit when we want to make piping smart.

**Comment by Dream-Master** [comment]
@bartimaeusnek @richardhendricks  anything we can do against it?

**Comment by Polybomber** [comment]
I had a similar issue where I was extracting fluid from a Gregtech pipe into a pressurized conduit that didn't go anywhere. As a result, fluid would keep flowing into the conduit and be voided.

**Comment by repo-alt** [comment]
Why the f was that closed

**Comment by bombcar** [comment]
The “reason” for doing this shouldn’t exist anymore “the infinite transfer speed of ender io conduit” but this probably still happens. 

I suspect #6768 is related

**Comment by repo-alt** [comment]
EnderIO network does modify input fluid stack in it's IFluidHandler.fill implementation.
