### ISSUE TITLE
Multiblock garden/greenhouse

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4164]
It would be nice if we had a themed multiblock for accelerating ic2 crops, instead of generic world accelerators.

I'm thinking something like the cleanroom that supports multiple sizes, with input hatches for fertilizer and water, and a power hatch for internal "grow lights".

Would have to figure out if it is possible to directly manipulate the ic2 crops state etc etc too hard blah blah use a forestry farm nerf nerf

**Comment by shawnbyday** [comment]
Maybe the glass and structure are super cheap to make but the controller and hatches are the hard part. So if you have to build several of them it doesn't make you want to die. Controller that works sort of like the cleanroom one, liquid hatch for water, some filter types of things (not as many as a cleanroom) but like 2x2 on 2 sides or something. Not sure how to do power with them or if you need to.

**Comment by richardhendricks** [comment]
Another option could be a tier or two of crop sticks.  Like a better crop stick that ignores all negatives such a height, humdity, etc, and an advanced one that gives boosts to growth (say its crafting recipe includes lights/glowstone/fertilizer/whatever).

**Comment by shawnbyday** [comment]
It would be nice to have an end game viable option that lets the crops produce resources as well instead of just multiplying ores.

**Comment by 0lafe** [comment]
Could it also affect bees and black list crops/bees from WA? They're essentially the same thing so it kinda makes sense to put them together. For glass you could use Bart's glasses which would give it buffs for upgrading maybe similar to the ebf? Could also gate some crops/bees based on EU/t and glass tier if that's doable. Better crop sticks sound nice, we have better bee hives so it sort or lines up. Ways to eliminate requirements for daylight/sky/etc. 

>It would be nice to have an end game viable option that lets the crops produce resources as well instead of just multiplying ores.

We don't really *need* this, but they kind of already have that, you just need UU, which makes it pretty endgame. You can kind of make a bunch of it, and if you have the crops for UU it becomes a decent amount easier. Maybe lower it on the simplier materials and possibly buff it on later ones? Still below replication values, but more than like 9L per for things like osmium/iridium/naquadria/etc

**Comment by richardhendricks** [comment]
Bees already have plenty of ways to increase outputs without WAs:
houses -> apiaries + frames -> alvearies + frames -> industrial apiaries
Bees could do with a rate adjustment to make each tier more sensible, I agree.

**Comment by 0lafe** [comment]
Yea, but switching them to a blacklist on the WA and allowing them to use this multi seems cooler than a simple power dump for them

**Comment by richardhendricks** [comment]
Thematically, putting bees inside a greenhouse doesn't make sense to boost their output.  I'd rather we adjust the scaling for industrial apiaries and the boost from the frames for it instead, or make a multiblock GT beehive of some kind.

**Comment by mitchej123** [comment]
bump
