### ISSUE TITLE
HOG (high octane gasoline) buff [RFC]

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#4168]
#### Which modpack version are you using?
2.0.6.8
#

#### What do you suggest instead/what changes do you propose?

Looking at making HOG, relying on the product speeds of 1 EV distillation towers for oil and another for heavy oil, plus a TON more stuff to complete the recipe totaling close to 20k EU/t of processing, gives you close to 45k EU/t in a boosted LCE. If you instead take an amp of IV, and power an array of MV distilleries of oil to sulfuric LF, then turn it to LF, you're looking at about 12k EU/t running costs, and an output of 75k EU/t in a boosted LCE. Each MV distillery will make 1.1k EU/t from LF. 

Due to this, I suggest boosting the fuel value of HOG by a whopping 1.5x from 1152EU/L to 1728EU/L. This way you will get a similar EU output from the same distillery input, while giving more non power outputs with the HOG route, as it also takes many many more distillation setups, LCRs, crackers, farms, pyros, etc 

Considering you can do what I said above with LF, then use that power to run a distillation setup that gives the same outputs as HOG, for a little less infrastructure/power, this seems pretty fair. Also we might want to lower the acetone requirement of HOG. There's no real good way to make it at the moment, with most requiring almost more power than the entire HOG setup will give, or needing close to half the amount of multis just for acetone alone.

**Comment by 0lafe** [comment]
To compensate for acetone use, we could buff acetic acid output from fermented biomass of acetic acid, and lower the amount of water. Maybe -75 water, +75 acetic? Gives 100L/cycle of acetic acid, which essentially 4xs acetone production from distillation. Also could increase it from wood vinegar to maybe 150?

**Comment by richardhendricks** [comment]
https://en.wikipedia.org/wiki/Acetone#Production

**Comment by 0lafe** [comment]
Yeah read through that, it's mostly what we got. The cumene process does make a lot but uses phosphoric acid which isn't really a renewable resource unless you involve bees/crops. The tiny amount of phosphor pentoxide from ashes isn't really enough to keep it going. That's more the way you'd go for making phenol for epoxy. It does say you *could* use other Lewis acids in the cumene process, so maybe we can have a lower yield version that uses some renewable one? Or maybe some other dim pumping of phosphoric acid/cumene? Also said something about acetone on asteroids, so maybe add it as a pumpable fluid in the asteroid dim? Idk how that would work but could be something

**Comment by Dream-Master** [comment]
@0lafe if we boost HOG we need to bost the other gasolines fluids too?
