### ISSUE TITLE
Steam Cell

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#4203]
#### Which modpack version are you using?
2.0.6.7c
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Tried to fill an empty cell with steam stored in a super tank.
#
#### What happend instead? (Attach screenshots if needed)
Nothing.
#
#### What do you suggest instead/what changes do you propose?
Currently to get a steam cell you have to use a fluid canning machine or a bottler. Can we add a recipe that allows you to create a steam cell from steam stored in a super tank or something similar?

**Comment by Dream-Master** [comment]
Mods like railcraft and ic2 adds steam too so not sure how to add?

**Comment by shawnbyday** [comment]
Yea right now you can store steam in a super tank and it will show up as GregTech steam but if you put a cell into the tank it won't go into the cell. - Just adding to this to clarify.
