### ISSUE TITLE
CleanRoom unformed work

### ISSUE THREAD

**Issue by skynsun** [GTNewHorizons/GT-New-Horizons-Modpack#4206]
#### Which modpack version are you using?
v2.0.6.8
#
#### If in multiplayer; On which server does this happen? 
It happen on private server.
#
#### What did you try to do, and what did you expect to happen?
I build a cleanroom not fully formed but the mention not formed doesn't appear and works like complete structure, i tried to craft and you can.
#
#### What happend instead? (Attach screenshots if needed)
The clean room not fully formed should not work and the message would appear.

#### Screenshot
https://media.discordapp.net/attachments/181078474394566657/552675620644192257/Clean_room.png?width=784&height=441

**Comment by bartimaeusnek** [comment]
@skynsun do you build that over a chunk border? if yes its unpredictable what it will do.

**Comment by boubou19** [comment]
even if it's the case it can be used to run the clean room :/

**Comment by skynsun** [comment]
Nop all the clean room is within a same chunck

**Comment by richardhendricks** [comment]
![2019-03-07_23 20 29](https://user-images.githubusercontent.com/1214811/54009240-adffc680-412f-11e9-9f4e-0d6d4817de60.png)

**Comment by Prometheus0000** [comment]
Is this still happening or not?
