### ISSUE TITLE
[RFC] Adding pollution protection, nerfing night vision for Darksteel Armor

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4219]
It would be nice if Dark Steel armor could resist pollution.  Also, the NV in darksteel armor is way better than the night vision in the nanosuit.  I think a good compromise would be:

- Change current NV recipe to require the nanosuit helmet instead of nightvision potion. So now the darksteel is a bit of an upgrade.
- Increase power draw when NV is active, way too cheap now. Need to check numbers.
- Have recipes to add the rest of the nanosuit parts to grant pollution protection
- Do not grant lava protection like the hazmat suit
- Protect against radiation?

EnderIO is open source, but adding hazmat features might be hard with ic2.

**Comment by draknyte1** [comment]
Did we ever fix the Nano armour not behaving correctly as a Hazmat suit?

If not, I can happily register this and that in ++.

**Comment by Anarack** [comment]
We did not afaik.
