### ISSUE TITLE
More warp events

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4270]
gives multiblocks maintenance issues
randomly turns machines off/on
ties your shoes together, slow until you take off footgear
turns around your helmet, blind until you take off headgear
Makes hands slippery,  high chance to drop whatever you are holding until you take off gloves or chest piece
Makes you constantly jump, ants in the pants until you take off armor pants
Swaps L/R buttons on the  config file
Random trash blocks falls from the sky - where do you think those void drop filters lead? Like several stacks of cobble/sand/dirt/any other garbage items/etc. Not placed, but entities that clog up your inventory.
Very angry wisp summoned (maybe 1-3)

**Comment by dragagon** [comment]
oi, now wait just a minute. these will be added like... after 60 warp and just make the wither further out, right? cause otherwise wait until i get OsIr so i can clear my warp...

**Comment by bartimaeusnek** [comment]
+1 for the wisp, maybe even spawn BoP/Natura whasps? 
you feel out of your body -> lock in 3rd person for several minutes
you've become blue -> blue tint on everything
you have flashbacks from a prior life -> very slow stroboscope

**Comment by draknyte1** [comment]
> very slow stroboscope

Thanks for the seizures. 

Besides wisps, the rest are annoying aesthetically but don’t provide anything else. Purely annoying and non-consistent with the rest of the effects.

**Comment by bartimaeusnek** [comment]
you dont get seizures from a color change every few (5-7) seconds with a smooth transition.
>Purely annoying and non-consistent with the rest of the effects.

Acceleration warp, rain warp, blood warp, chest scramble, creeper friend, scortched....

**Comment by Methes** [comment]
I actually love all of them and think they fit the original warp theme Azanor had in mind. Playing with your mind more than your surroundings.

**Comment by richardhendricks** [comment]
These are just ideas. It might be better to tune warp events to be more personal instead of server wide, these gives some options that only pester the affected player and not the whole player base.

**Comment by richardhendricks** [comment]
I'd also like more poltergeist style effects to really mess with your head.

**Comment by richardhendricks** [comment]
...and encourage you to get rid of that warp!

**Comment by richardhendricks** [comment]
vampire effect - damage if you are out in sunlight
werewolf effect, you get turned into a doggo
zombie effect - you only get food restoration from eating rotten meat/zombie brains
strange attraction - passive mobs follow you, like you have the flower crown.. maybe even spawning and following you. Imagine a herd of animals in your way while you try to do base work.

**Comment by Namikon** [comment]
> > very slow stroboscope
> 
> Thanks for the seizures.
> 
> Besides wisps, the rest are annoying aesthetically but don’t provide anything else. Purely annoying and non-consistent with the rest of the effects.

So what about your weird Rainbow-Ingots and Dusts? That gave me eye-cancer

**Comment by richardhendricks** [comment]
@Namikon I was thinking on ways to reduce server damage from warp.  What about limiting it to a certain distance from a fixed point?  Like their bed, the player's research table, or infusion altar, or other likely-fixed structure of theirs. 

Or track where they last gained or removed warp, and only allow warp events near that location.  By "near" I'm thinking 320 blocks.

And if they try to flee the OW, the location where they enter a new dimension.  Go to the nether, warp effects start right at the portal. Or moon.  But that might be a bit mean if it traps them there from the wither blowing up their launch pad.  😄 

Warp events could individually limit themselves too, world-altering warp would be gated by distance from these locations while personal-affecting effects could be at any time.

And have it setup so that if a world-effect is denied due to distance, it adds more sticky or temp warp.

**Comment by Namikon** [comment]
There is a difference between solo and server play; On a solo world, it's a strategy to flee somewhere else and punch wood until your bad effects wear off (like going to exile)
On a Server, however, this is abused by waiting in public areas like spawn, or other player's homes, which caused severe damage in the past years.

Not sure if these effects can be limited enough so it works for both single and server play.
One thing that could help is to change Warptheory to use either a fake player to modify the world (Then any protection mod would be able to prevent it), or set the block(s) through the player instance. Not sure on the second idea; If I remember correctly, there is a range-check for altering blocks.
