### ISSUE TITLE
Suggestion: Reduce Automatable Data Hatch tier for Assembly Line

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/GT-New-Horizons-Modpack#4273]
2.0.6+

At LuV you get the 16x Data Access Hatch (2041:146).

But the Automatable Data Access Hatch (2041:147) isn't available until UV...

I suggest that this be reduced 1 tier to ZPM and all components reduced 1 tier accordingly:

2* ZPM Robot Arms
2* Data Orbs
1* ZPM Machine Hull
4* UV Circuits

This would still gate behind Fusion anyway.

Basically by the time you get to make this you would probably go with multiple assembly lines for more speed anyway...

**Comment by Dream-Master** [comment]
The auto data hatch is named uv_hatch s i guess it make sense add them at uv and not zpm. 
What the other think?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/54611282-ee781200-4a56-11e9-9dd5-5526f624cd9d.png)

**Comment by Kiwi233** [comment]
@Highbeam Can you tell me how to use this Automatable Data Hatch?
Looks the same as the advanced data access hatch.
