### ISSUE TITLE
GT Hand Drills Buff

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#4290]
The hand drills added by gregtech are rather shit compared to tinkers tools so from the discord discussion the following buffs were suggested.

- have a 3x3 mining mode or some or sort of larger area to allow competition with hammers
- change the drill tiers so they are not starting at hv and are more distributed across the tiers, ex lv drill in lv, mv drill in hv, hv drill in iv.
- look at hammer speed and see if any changes need or should be done to them.

**Comment by Dream-Master** [comment]
Help needed for it code wise.

**Comment by BlackFlameTNT** [comment]
I think you can limit how much red stone can TC tools have maybe this is something you can do.
Make the drill maybe more friendly you can have more then one mod like a single block mod,3x3 mod,2x1.
And why you have to build the whole drill if it broke why not only the drill tip is distributed and you need to replace the drill tip.

**Comment by damug** [comment]
If we do set a limit, 3 or 4 stacks could probably be a good number? Still lets picks get pretty speedy, but hammers would remain noticably slower. Might also consider disabling or adjusting some of the "speedy" tinker materials for picks, hammers, shovels, excavators, axes, and lumber axes.

**Comment by Anarack** [comment]
You were intended to disassemble them when they get close to breaking.

**Comment by Anarack** [comment]
or instead of down tiering them, make the use tier appropriate batteries and boost energy capacity.

**Comment by observeroftime02** [comment]
How about adding tools past HV? Would be nice to have an EV or LuV variant. Don't see why they should stop at HV, seeing how we have the appropriate materials already available. 

The material the drill is made from could be tiered to suit the appropriate material of the motor and battery used in it's construction. Making a LV Neutronium drill, for example, seems silly. 
Have, for example a titanium drill only be available for the EV variant of the tool, and so forth, and limit an LV drill to the materials available at the LV tier.

**Comment by Anarack** [comment]
Because a orihaukon hv drill is speed 288, higher tier ones aren't really needed and would just add item bloat for a tool very few people use.

**Comment by mitchej123** [comment]
I'd be happy with a way to increase the battery size. A 3x3 or higher area at higher tiers would also be a bonus. My HV one runs out before 1 vein is gone... kind of useless compared to a tcon hammer.

**Comment by observeroftime02** [comment]
Bigger battery size would be awesome. I run around with a charge pack, so I don't notice it as much, but many people might not have access to it.

**Comment by richardhendricks** [comment]
I like giving them 3x3, 5x5, and 7x7 active area-modes.  We can also reduce the EU cost for them so that they are more competitive against repairing TiCon tools.

@observeroftime02 Interesting.  I knew about the batpack and advanced batpack, but not the GT++ variants.  I'll add a ticket to add quests for them.
