### ISSUE TITLE
Chisel chest into trapped chest

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#4295]
#### Which modpack version are you using?
2.0.7.0 
#
#### If in multiplayer; On which server does this happen? 
Eta

You can chisel chest into trapped chest, I think it should be removed, since it has a recipe with tripwire hook.

**Comment by Dream-Master** [comment]
yes need to be removed

**Comment by Impos913** [comment]
This is not fixed and closed because of being an old issue.
