### ISSUE TITLE
GT Semi-fluid generators not accepting semifluids

### ISSUE THREAD

**Issue by robpo4** [GTNewHorizons/GT-New-Horizons-Modpack#4306]
#### Which modpack version are you using?
GT New Horizons 2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
ETA Server
#
#### What did you try to do, and what did you expect to happen?
Tried to put semi fluids (mainly heavy oil and Creosote) into a semifluid generator in cell form and piped in, and I expected it to just take the liquid and burn it as per the NEI recipe.
#
#### What happened instead? (Attach screenshots if needed)
Advanced semi fluid generator refused to take in the semi fluids.
#
#### What do you suggest instead/what changes do you propose?
Using Diesel generators and extra processing steps instead. Change the block to actually accept the fluids as currently the NEI recipes are luring people into using a lot of resources.

**Comment by EldrinnElantey** [comment]
Why does NEI have information that the semi-fluid generator will accept creosote if it is not?

**Comment by robpo4** [comment]
> Why does NEI have information that the semi-fluid generator will accept creosote if it is not?

I didn't realise this ticket was still even open. Its 16 months old at this point It appears to have been fixed in a different ticket.

**Comment by EldrinnElantey** [comment]
> > Why does NEI have information that the semi-fluid generator will accept creosote if it is not?
> 
> I didn't realise this ticket was still even open. Its 16 months old at this point It appears to have been fixed in a different ticket.

Did you find out why the information in NEI is wrong?

**Comment by robpo4** [comment]
it just looked like a liquid ID was wrong somewhere as it was fixed in the next version

**Comment by EldrinnElantey** [comment]
> it just looked like a liquid ID was wrong somewhere as it was fixed in the next version

You noticed this on the version of GT New Horizons 2.0.7.0 and I see it on the version of GT New Horizons 2.0.9.0

**Comment by robpo4** [comment]
Its still an active problem? I havent really played much of the new version to notice it

**Comment by robpo4** [comment]
Huh yeah it still doesn't work yet the NEI recipe is still there

**Comment by draknyte1** [comment]
> Huh yeah it still doesn't work yet the NEI recipe is still there

NEI handling and fuel handling by a generator are two entirely separate aspects of the game.

**Comment by robpo4** [comment]
thats fair enough, I kinda guessed that but I'm not a coding guy so I never bothered looking too far into it, i just knew it didn't work. Its just strange to me personally it was there after over a year, would be nice if it could be fixed though.

**Comment by draknyte1** [comment]
I fixed it, then broke it again at a later date. 😌

**Comment by robpo4** [comment]
Oh, I'll leave you to it then. Was it broken after they got nerfed?

**Comment by draknyte1** [comment]
It was rebroken in 9.0 due to something unrelated to them.
