### ISSUE TITLE
IV Mainframe Circuit recipe needs change

### ISSUE THREAD

**Issue by LogicFalls** [GTNewHorizons/GT-New-Horizons-Modpack#4308]
The quest prompts for two EV Workstations to craft one IV mainframe. The recipe only calls for a single workstation.

**Comment by 0lafe** [comment]
What version? There's a bug with mainframes only taking 1 circuit in 6.x, but was supposedly fixed in 7.0+

**Comment by LogicFalls** [comment]
This is V2.0.7.0. I guess it wasn't fixed.

**Comment by Dream-Master** [comment]
are the quest reloade ?

**Comment by LogicFalls** [comment]
Yes, quests are definitely up to date. Not only was it the first thing I did on updating, I've also had to reload to get rid of the "New Quest" glitch.

**Comment by 0lafe** [comment]
I don't think the quest is wrong, the mainframe should be 2 EV circuits.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57345299-ee6bc880-710f-11e9-8579-864a5d00a2bb.png)
Recipe needs adjusting.

**Comment by Prometheus0000** [comment]
Both the recipe and the quest require two now, so this should be closed.
