### ISSUE TITLE
ResearchStation,ObjectHolder and QuantumComputer recipes can only use CrystalProcessorMainframe

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#4361]
#### Which modpack version are you using?
2.0.6.8 and 2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Single and PrivateServer
#
#### What did you try to do, and what did you expect to happen?
I tried to make ResearchStation,ObjectHolder and QuantumComputer using WetwareSuperComputer.
#
#### What happend instead? (Attach screenshots if needed)
This recipe only use CrystalProcessorMainframe.
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by 0lafe** [comment]
If those are assline things, assline ore dict is struggling for some reason 
https://github.com/GTNewHorizons/NewHorizons/issues/4279

**Comment by Dream-Master** [comment]
@yukieiji  @0lafe 
are the bug visual or real. Did you try to use other uv circuits ?

**Comment by DietmarKracht** [comment]
I will try tomorrow as the uv parts were only visual too

**Comment by yukieiji** [comment]
This bug is not visual. I could not execute recipe on other uv circuit such as wetwaferprocessor than CrystalprocessorMainframe.

**Comment by DietmarKracht** [comment]
by looking into @Technus github code i can tell that this is no bug. The recipes only take the mainframe version of the circuits. Maybe @Technus can change this to accept all types of the circuit tier.

**Comment by Dream-Master** [comment]
dont worry I can change that myself. But as far I can say all assline recipes shows no oredicted circuits.

**Comment by DietmarKracht** [comment]
But for other recipes than the tectech ones this is only a visual bug

**Comment by Dream-Master** [comment]
so it work with all uv or zpm circuits?

**Comment by DietmarKracht** [comment]
yes, the normal assembly line recipes work with all type of circuits. only tectech uses mainframes and no ordicted circuits. see #4279
