### ISSUE TITLE
Tesseract Generator is way too expensive

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/GT-New-Horizons-Modpack#4369]
For something that is meant to be used around EV, the Tesseract Gen is way too expensive, needing a GT computer cube (therefore a ZPM circuit) for something that is objectively worse than Ender Tanks (IV). LUV circuits are also kinda silly.

**Comment by Dream-Master** [comment]
teleportation is expensive in GTNH just for items. I think it isnt realy expensive its to cheap :)

**Comment by Anarack** [comment]
It significantly more expensive than the dim transceiver which beats it in basically every possibly way except possible power usage.

**Comment by draknyte1** [comment]
Last I checked, nothing else supports xDim GTEU besides the microwave transmitter and it’s lossy as hell. 

So it has that going for it.

**Comment by 0lafe** [comment]
IV for interdim eu is kinda early if anything

**Comment by draknyte1** [comment]
They only accept one voltage. 
They consume a full amp for every amp transferred xDim. 
They consume a full amp of the tier below for same dim. 
They have an idle run cost when doing nothing. 

Very limited.

**Comment by repo-alt** [comment]
Interdim microwave transmitter was borked in the previous update btw. (didn't check in the last one)
