### ISSUE TITLE
Suggested cherry pick pull request

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4370]
Alk suggested merging this PR from upstream

https://github.com/Blood-Asp/GT5-Unofficial/pull/1527

Need to test it.

**Comment by draknyte1** [comment]
Already has been for like half hour.
Merged it into my local fork before I approved it.

**Comment by boubou19** [comment]
will this PR replace the behavior added there: https://github.com/GTNewHorizons/NewHorizons/issues/3222 ?

**Comment by draknyte1** [comment]
Would explain why I thought this was already done. 
Adds a new function to the utils class vs the current internal handling. Which is nicer.

**Comment by Dream-Master** [comment]
Can someone do a pull for us fork @draknyte1 @richardhendricks @bartimaeusnek
thanks
