### ISSUE TITLE
AE Inscriber

### ISSUE THREAD

**Issue by DarkShadow44** [GTNewHorizons/GT-New-Horizons-Modpack#4376]
#### Which modpack version are you using?
2.0.7.0

#
#### If in multiplayer; On which server does this happen? 
SP

#
#### What did you try to do, and what did you expect to happen?
What's the point of the AE Inscriber? It's super expensive and everything it does can be done by assembler & forming press.

#
#### What do you suggest instead/what changes do you propose?
Probably best to remove the recipes from the forming press and the assembler. Is there a particular reason for them being there?

**Comment by bartimaeusnek** [comment]
Yes. We are a GT modpack that tries to avoid non GT machinery. The Inscriber was a user request and thats the only reason it has a crafting recipe.

**Comment by DietmarKracht** [comment]
I want to keep the inscriber as it can be used to rename items with the new recipes for Quarz knifes and therefore inscriber name presses. There is no GT way to solve this

**Comment by DarkShadow44** [comment]
Okay, I understand. Would it make sense to make the AE recipes require the same level of GT machinery? Like, not only use 16EU/t, but need the Forming press the AE inscriber is made off?

**Comment by Anarack** [comment]
Well with the 10x power wouldn't that be 160 eu/t?

**Comment by DarkShadow44** [comment]
Why 10x power?

**Comment by Anarack** [comment]
Because all power usage on AE devices has a x10 multiplier on it?

**Comment by DarkShadow44** [comment]
The GT Forming Press uses 10 times the power when it makes an AE recipe? That doesn't sounds sane.
