### ISSUE TITLE
Tungstate from endstone

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#4379]
#### Which modpack version are you using?
2.0.7
#

Endstone tungsten got changed to tungstate, but tungstate is 7x less tungsten than tungsten is. So tungsten from endstone got nerfed by 7x and is kinda useless now. Chaning the % chance for tungstate to 15% or something would fix it.

**Comment by chochem** [comment]
Just played through that part on 2.0.7.0.

Endstone is actually very useful to get your first tungsten needed for the T2 rocket. Only alternative is lava. Three stacks of endstone is enough for T2 rocket. This is multiple magnitudes better then the moon stone the quests are pointing towards.

And once you have the T2 rocket, you have much better sources of tungstate. It really seems fine as is.

**Comment by draknyte1** [comment]
End stone was changed to tungstate years ago in master. 
> it’s not even a nerf

**Comment by boubou19** [comment]
yeah it was like that so far i can remember in gtnh( at least 2 years ago)

**Comment by 0lafe** [comment]
>Endstone is actually very useful to get your first tungsten needed for the T2 rocket. Only alternative is lava. Three stacks of endstone is enough for T2 rocket. This is multiple magnitudes better then the moon stone the quests are pointing towards.

If the rocket is to stay at IV, a tungsten cost of 2 is extremely too low. At least 1 ingot/plate, even that's still kinda low. Maybe increase 7x? lava can keep up, and increasing endstone to 7x current to reflect pre tungstate recipe. 

>End stone was changed to tungstate years ago in master.

I feel like it was mad long ago, but changelog says it was in 2.0.4.3? 

>- Tungsten from Endstone -> Tungstate

I think there was a different pure tungsten that got changed to tungstate a long time ago. Maybe lava? idk

**Comment by chochem** [comment]
> 
> If the rocket is to stay at IV, a tungsten cost of 2 is extremely too low. At least 1 ingot/plate, even that's still kinda low. Maybe increase 7x? lava can keep up, and increasing endstone to 7x current to reflect pre tungstate recipe.
>

not fully sure what you are saying here, but T2 rocket is EV not IV and the tungsten cost is only a single tungsten dust for the entire T2 rocket, not 2 (as you get a lot of tungstensteel back from the implosion compressor). As I said I think everything is fine as is, except maybe for the quest book which should point you to endstone instead of moonstone.

**Comment by ScriptedPiky** [comment]
I'd also recommend changing the Moonstone centrifuging recipe to be buffed (I'll go more in-depth about changing/buffing the planet stones in the future), such as: changing the tiny pile of tungstate to pure tiny pile of tungsten. Change the current chance of 1.50% to 3.75% as well.

For instance: If you decided to run your LV centrifuge to process Moonstone for exactly 1-hour for every 20 seconds on the current game patch (in-game time, so this can take longer with TPS issues), you'd get exactly .5 whole dusts worth of tungstate. Or rather, 4.5 tiny piles of tungstate over 1-hour in-game time roughly. This is without overclocking to HV or EV. Overclocking to HV would simply put it at 5 seconds and 2.5 seconds at EV.

Math by the way from my friend that explained this to me: (0.025) * (3600/20) / 9 = 0.5
In order: % of the tungstate (2.5%), 1-hour in seconds, recipe time in seconds, into whole pile of tungstate

**Comment by 0lafe** [comment]
1.75h per pure W dust at EV, 2x that at HV overclocked (3.5h), 2x less than that at max efficiency HV (53min). 3.75% lowers times to ~1.1h EV, 2.3hHV single, and 35min LV singles. Changing it to pure W 1/7s all those times, putting the lowest to 5min/dust. At a rate like that, 1 dust being used in a rocket is absurdly low, for endstone or lava usage aswell. 

Changing to pure W and 2.5% is 15min/30min/7.5min which is fairly low too. Tungstate at 5% is 1/2 current values, being 50min/100min/25min per dust, which makes a usage of ~4 (8 tungstensteel) reasonable. Pure W 3.75% would be closer to a usage of like 40 tungstensteel being viable, which also seems fine I guess. 

For comparison, lava is 9.3m/9.3m/18.6m for 4 MV singles/single EV/single HV for pure W not tungstate.

**Comment by ScriptedPiky** [comment]
> 1.75h per pure W dust at EV, 2x that at HV overclocked (3.5h), 2x less than that at max efficiency HV (53min). 3.75% lowers times to ~1.1h EV, 2.3hHV single, and 35min LV singles. Changing it to pure W 1/7s all those times, putting the lowest to 5min/dust. At a rate like that, 1 dust being used in a rocket is absurdly low, for endstone or lava usage aswell.
> 
> Changing to pure W and 2.5% is 15min/30min/7.5min which is fairly low too. Tungstate at 5% is 1/2 current values, being 50min/100min/25min per dust, which makes a usage of ~4 (8 tungstensteel) reasonable. Pure W 3.75% would be closer to a usage of like 40 tungstensteel being viable, which also seems fine I guess.
> 
> For comparison, lava is 9.3m/9.3m/18.6m for 4 MV singles/single EV/single HV for pure W not tungstate.

Please elaborate, as we're having a difficult time trying to understand; expand on what you said and describe details

**Comment by Hakameda** [comment]
Which part didn't you understand?

**Comment by ScriptedPiky** [comment]
> Which part didn't you understand?

Most of what was said were hard to understand. Yes, there were numbers, but it felt scattered. 0lafe later explained it in DM's
