### ISSUE TITLE
[Suggestion] Large Cooling Cells

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4383]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#

Now that energy hatches and dynamo hatches have been nerfed we need a better automation option for the higher tier hatches as they will be needed very frequently. I therefore suggest adding a 720k coolant cell and a respective 1440k cooling cell.
By adding that the UV and UHV hatches can be crafted using 9 or less components and they all can be done in one assembly line without having  to separate the different recipes. 
An alternative would be making the coolant cells stack in inventory or machines but the nuclear reactor.

**Comment by Dream-Master** [comment]
yea can add it but not sure if that works in reactors

**Comment by Spartak1997** [comment]
@Dream-Master https://github.com/Spartak1997/GregTech5.09UnofficialBuild/commit/0a71c802e8d956cf6d2396a936d6283dd29aa6c6

**Comment by 0lafe** [comment]
Recipes with >9 components can still be done in 1 assembly line though? There's already a bunch of 10+, including circuits right?

**Comment by DietmarKracht** [comment]
I am talking about the fact that you would need at least 3 assembly lines for all the dynamo and hatches because otherwise the input can be mixed up when you request multiple of them
