### ISSUE TITLE
Titanium Dust Smelting bug

### ISSUE THREAD

**Issue by GoldBlockIngot** [GTNewHorizons/GT-New-Horizons-Modpack#4386]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Smelting Titanium Dust with nitrogen in an EBF
#
#### What happend instead? (Attach screenshots if needed)
There is no speed/efficiency buff over smelting the dust with no gas, unless you are using small/tiny dusts. NEI backs this up.
#
#### What do you suggest instead/what changes do you propose?
Chaning the overall EU cost and speed of the one titanium dust+1k nitrogen recipe to match the small and tiny dust recipes.

**Comment by Dream-Master** [comment]
fixed in dev so far ik
