### ISSUE TITLE
Unfired Coke Oven Brick recipe issue

### ISSUE THREAD

**Issue by MrVenik** [GTNewHorizons/GT-New-Horizons-Modpack#4387]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Craft Unfired Coke Oven Brick
#
#### What happend instead? (Attach screenshots if needed)
There is no alternative to craft unfired coke oven brick with Red Sand
#
#### What do you suggest instead/what changes do you propose?
Add OreDictionary Sand for this recipe

**Comment by shawnbyday** [comment]
If there aren't any oppositions to this I can update the recipe to use ore dictionary.
