### ISSUE TITLE
[RFC] Underground fluid suggestions 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#4388]
#### Which modpack version are you using?
2.0.7
#

Fluid pumping got a bit of a suggestion thread but it kinda died and was more about removing Nq. So uh, I'ma post "current" ideas for pumpable fluids on planets. Complain about the ones you don't like, and suggest ones that aren't there. Also, order is based on rocket tier, as that's unlock tier, and the numbers after planets are max sizes. If you feel like a found is only okay in certain quantities/rates, mention that, I'll try to put accurate deposit sizes in the list. 

Nether
H2S 100
Lava 50

T1
Salt water (moon) 50
He-3 (moon) 425
T2
Nitrogen (Mars+) 200
Salt water (Mars+) 400
T3
Salt water (Europa+) 800
Infinite heavy oil (Europa+) 800
Very heavy oil (Europa+) 200
CO2 (Callisto+) 500
Infinite oil (Callisto+) 800
Infinite nat gas (Ganymede) 800
Helium (Ganymede) 100
T4
Argon (Venus) 50
Metals? (Venus) 1 
He-3 (Mercury) 800
T5
Methane (Titan) 800
Ethane (Titan) 200
Sulfuric light fuel (Miranda) 500
Sulfuric heavy fuel (Oberon) 500
Sulfuric naphtha (Oberon) 500 
T6
Liquid air (Triton) 100
Toluene (Proteus) 300
T7
Ethylene (Pluto) 800
Chlorine (Pluto) 300
T8
Fluorine (BC) 100
Radon (BE) 100
H2 (Tceti) 400

Uh the + on dimension names are because apparently we need 1 fluid per planet, so either need a lot more fluids, or some will be changed to be on multiple planets. The infinites are just fluids that can be pumped with no rate decrease.

**Comment by richardhendricks** [comment]
For the Nether, I'd like H2S changed to Sulfuric Acid.  H2S wouldn't be that compelling to go get, but H2SO4 would be worth getting once you are heavy into needing indium or Platinum Group Sludge, since it would save a lot of steps.  IF H2SO4 is too easy, it could be dilute H2SO4 instead.

Salt water on the moon I put as a stopgap to get people sufficient chlorine, but I think we can lower it to 50. I'd prefer the moon for He3 mining, and Mars/Europa for volume extraction of salt water.

Would replacing nitrogen for CO2 on Mars make sense? Neither really is a difficult gas needed in quantity, but CO2 would be slightly more realistic. I dunno.

Radon on one of the T3 dimensions would be convenient.  Maybe on Callisto to give it a unique purpose? All the way out on T8 seems like it wouldn't be relevant by the time you can get there. T3 would be two tiers beyond where you need it for EV sensors.

**Comment by Anarack** [comment]
Keep in mind, these are max values, the average value is around 1/5 to 1/6 of the max with how it weights it per bart.

**Comment by bartimaeusnek** [comment]
Im personally not a fan of infinite fluid fields, espically stuff like oil on callisto isnt realistic enough imo. id prefer a more realistic approach to fluid diversity, i.e. Salt Water should be on the mars, europa and callisto. Argon on Venus also makes just little sense logic wise, its a very light element that shouldnt be on a planet with such a high atmospheric pressure as Venus has, would prefer Radon or a liquid metal (iron, lead, copper, etc.) instead. Fuels on the planets also seem to be... wrong simply due to the fact that a fuel is a humanoid seperation of oil, therefore it shouldnt exist naturally, imo. Toluene on Proteus seems fitting, even tho id also add cyanides there. T7 & T8 Materials arent useful in my opinion, due to the fact, that at that stage, youll most likely have an infinite supply of these materials anyways. Other than that it seems fitting.

**Comment by botn365** [comment]
H2 seem usless after you get infinite nat gas at t3 wich can be easly convertet in H2

**Comment by 0lafe** [comment]
>H2 seem usless after you get infinite nat gas at t3 wich can be easly convertet in H2

It's like a 60% conversion and takes a decent amount of power to try to convert the whole output of the drill. It's a good H2 gen, but not really as good as pure H2. 

Mostly I tried to go with the ethylene/ethane products on higher planet idea of eliminating early processes of stuff in later tiers. Why argon is on Venus, and sulfurics on other planets. Just elimination of a step in processing as you tier up. 

>For the Nether, I'd like H2S changed to Sulfuric Acid. H2S wouldn't be that compelling to go get, but H2SO4 would be worth getting once you are heavy into needing indium or Platinum Group Sludge

Maybe on IO? H2S is 1:1 sulfuric acid, it just needs an O2 input, and considering nether fluid pumping is technically MV, pure sulfuric seems kinda good. Same for CO2 being just a good O2 gen, but just O2. I tried to do that for as many as possible early ones, but stuff like N2 and Ar didn't seem to have any good options that contained them and could be processed to them, besides liquid air. 

>T7-8

Infinite fast H2 on that small of a scale is kinda nice even lategame, especially if it's better than electrolyzation/distillation. Fluorine doesn't really have a good source before that isn't based on bees/crops, or heavy mining. Radon is kinda easy to make, but it's not really used all to much until after T6, so idk about earlier. It's still easier to pump than craft.

**Comment by 0lafe** [comment]
Metals kinda worry me just because how much you can get. A 1L/cycle max value would be over an ingot/s if it would make the whole field 1. If it kinda randomizes between 1 and 0, favoring 0, it could still reach ingot/2s. Essentially anything you pump as a metal is now free to produce. Iron sorta fits, lead too maybe? Copper would probably be too good, and most things post Stone age.

**Comment by richardhendricks** [comment]
@bartimaeusnek The problem is there are two competing needs, realism and balance/usefulness to the player at that tier. I prefer a mix of both. 

What rocket tier is Io?  I didn't see it on the list.  It would be a good to have sulfur and lava there.

**Comment by Anarack** [comment]
Tier 4. It would be nice thematically for hot fluids considering how active it is.

**Comment by richardhendricks** [comment]
When is large quantity of PGS needed? For building the T1 fusion right?

**Comment by Anarack** [comment]
Its mainly needed to unlock T3/T4 rockets if you skip looking for it in the end or asteroids for the plat veins. Once you hit T4 that gives you IO and then you don't really need it once you have IO.
Possible a few gt++ alloys before asteroids.
Some circuit stuff for plat, but you can get it outside of plat group sludge

**Comment by richardhendricks** [comment]
Maybe I'm thinking of Indium, is that used for the T1 fusion?  That needs sphalerite and galena.

**Comment by Anarack** [comment]
Some circuit/solar stuff, its big sink is the IV energy hatches, not fully sure what set of circuits start using em.

**Comment by ScriptedPiky** [comment]
Yes, Indium is used for T1 fusion and LuV Superconductor in particular. Indium can also be obtained from Bart's new T3 Ross128b planet as well (should be in 7.0 update now)

**Comment by voidlogic** [comment]
Hard disagree on organic molecules being available on planets with no biological ecosystems.

    Infinite heavy oil (Europa+) 800
    Very heavy oil (Europa+) 200
    Infinite oil (Callisto+) 800
    Infinite nat gas (Ganymede) 800
    Sulfuric light fuel (Miranda) 500
    Sulfuric heavy fuel (Oberon) 500
    Sulfuric naphtha (Oberon) 500
    Toluene (Proteus) 300

All of these: NO. Maybe make them available on fantasy Barnard C and T Ceti E

I think molten metals are okay where tier appropriate and plausibly realistic--however energy and multiblock structure demands of pumping a molten metal need to be considerably higher than pumping other liquids.

You've put forward a good start though, hopefully we can get someone in here who has studied astronomy for awhile to make some fancy suggestions.

**Comment by damug** [comment]
Oil on Europa isn't to far out of the realm of Scieance Fantasy as there have been several fictional works depicting sea life under the ice sheets that cover the planet. 

I agree that fossil fuels and fossil fuel derivatives should probably not be available on the rest though.

**Comment by voidlogic** [comment]
Ehhh even if there were life there. the 100-200km deep ocean makes whatever dead material that might land at the bottom exceptionally hard to access.

A more interesting idea might be harvesting raw Tholins https://en.wikipedia.org/wiki/Tholin#Occurrence and making a distillation tower recipe for that which gives a charitable amount of 10L oil for every 1000L Tholins

**Comment by 0lafe** [comment]
Indium in Bart's dim is essentially not really a source iirc. He said it's like 23 dust/vein, and the veins rarely generate. Like 1/500 veins will be the indium containing one. Plat sludge is never really needed. Pd is basically never used, and Ir/Os have alternate methods of creation less reliant on super high chalco amounts. You also don't need much until LuV, but by then you can make the T4 with a fairly low Os/Ir input and end up with pure Ir ores which give tons of Os as well. 

Not really sure why realism is so vital to fluid pumping when the current pumping uses fictional materials, as well as the planets themselves. Much of the tiers involving space have many reality breaks, such as Nq, ore gen, fake materials, etc.

That said, we also spawn organic matter on these planets already (creepers, zombies, bosses, etc), and they even function on a pre build dungeon mechanic. Some have plants and stuff too

**Comment by richardhendricks** [comment]
Raw Tholins on some of the dims would be interesting, but I would use it as a completely alternative material, not as a lame oil source - what would be the purpose?

"natural gas" is just a fancy representation of Methane, and having it on outer moons is plausible.  From Wiki

```
The average density of Ganymede, 1.936 g/cm3, suggests a composition of about equal parts rocky material and mostly water-ices.[4]  Some additional volatile ices such as ammonia may also be present.[39][40]
```

So Natural Gas could be plausible. Or maybe even ammonia.

Europa's ocean is potentially <10km below the surface.  And there is not really a reason to assume anything dying would sink.  Plenty of fish and other dead animals float during decay. Any "oils" from decomposing bodies would float to the surface of the ocean. and could be there between the ice and the water surface - this is what normally happens in Earth oil deposits with natural gas on top, then oil, then water.

Sulfuric fuels and toluene are definitely in the realm of science fiction, but there simply aren't that many plausible and useful liquids to begin with. I think the most likely use for those fluids would be to power large mining operations on-site.  So a fluid pump pulls naphtha that's burned to power one or a few high tier mining rigs placed across the planet's surface, for example..

**Comment by Bluebine** [comment]
Like most of these ideas, except for a couple.
 H2 on T8 seems WAY too late, maybe move that to T3 or T4. 
Nether should be H2S, being able to pump tons of sulfuric acid the instant you get the drilling rig would be OP. 
What's the point of CO2? It's kinda useless. Would remove that one. 
I think that drilling for oil could use some changes overall- oil drills get a RIDICULOUS amount of oil, which just kinda makes them insane for power gen. A drilling speed decrease for oil would be nice, or something to prevent people from just pumping 100,000 EU/t of raw oil or nat gas. What exactly needs changed is up to someone smarter than me, but I think drilling for oil needs a nerf in general. With that, you'd need to adjust the other fluids so they're not useless.

**Comment by 0lafe** [comment]
pump speeds are getting nerfed hevily past T1, and you cant really pump 100k without heavy refinement. Nat gas probably should be removed just because its too good tbh. Its the only oil product you can pump directly, and has a really high burn rate. 

CO2 is just an O2 source that would be better than most other alternatives. Also C gen which could be useful I guess? but we kinda got a lot of those.

**Comment by combusterf** [comment]
For the moons, particularly the small ones like Phobos and Deimos, is it an idea to have some (useful) trace gases (pick from things like helium, chlorine, fluorine, ...), but in "ridiculously" low quantities so that it only makes sense for single projects before having to pack up your rig and move over.

That particularly solves the "needs at least one fluid" problem when there's no good alternative.
