### ISSUE TITLE
Last Stand enchantment does not prevent death

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#4390]
#### Which modpack version are you using?
Zeta 7.1-Dev and previously Zeta 7.0-Dev (presumed to happen on 7.0 servers as well)

#### If in multiplayer; On which server does this happen? 
Zeta

#### What did you try to do, and what did you expect to happen?
Upon fighting a regular zombie with 30+ levels of XP, I should've lived and still brought back to 1/2 hearts worth/preventing death

#### What happend instead? (Attach screenshots if needed)
Died immediately despite having 30+ levels of XP where Last Stand **should've** prevented my death

#### What do you suggest instead/what changes do you propose?
Searching as to why Last Stand does not prevent death anymore and attempting a fix for it

**Comment by bartimaeusnek** [comment]
since its an ExU enchantment, and many mods may interfere with that, it will be rather hard to fix, would most likely need an ASM patch.

**Comment by richardhendricks** [comment]
Probably due to Special Mobs directly setting player health.  Will be fixed in 81

**Comment by Prometheus0000** [comment]
Was it fixed?
