### ISSUE TITLE
Broken dragon egg recipe + tcon enderium

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/GT-New-Horizons-Modpack#4410]
The dragon egg recipe (dragon heart + draconium egg in EV chemical reactor) is asking for 1000 molten enderium from tcon (should be GT) and players can get that by smelting an enderium gear in a smeltery (should not be possible either as that enderium fluid is disabled)

**Comment by Dream-Master** [comment]
yea will change it to gt fluid

**Comment by Hyperic88** [comment]
@Dream-Master Still an issue in 2.0.9.0
![2020-07-24_21 00 35](https://user-images.githubusercontent.com/14223368/88426671-e28e2400-cdf1-11ea-9c55-fd280906f74a.png)
![2020-07-24_21 00 45](https://user-images.githubusercontent.com/14223368/88426675-e3bf5100-cdf1-11ea-8c33-87079974137c.png)

**Comment by Dream-Master** [comment]
will check

**Comment by repo-alt** [comment]
The recipe is fixed, but the quest still requires TiCon enderium.
