### ISSUE TITLE
Bow Fletching Cast

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#4415]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Used tinkers smeltery and leaf fletching to cast a bow fletching cast. Expected leaf fletching to get consumed.
#
#### What happend instead? (Attach screenshots if needed)
Cast was made successfully but the leaf fletching was not consumed so I got the cast and the fletching back.
#
#### What do you suggest instead/what changes do you propose?
Have the casting process consume the leaf fletching. (Should probably check other recipes to make sure the item gets consumed as well at least from the smeltery).

**Comment by Dream-Master** [comment]
will check
