### ISSUE TITLE
Twilight Forest Ore distributions

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4416]
Per https://user-images.githubusercontent.com/1214811/35085337-d4ecd13a-fbed-11e7-8c69-61026b726396.png finding lead in the TF can be pretty difficult because of its height restrictions. As you can see, Diamond ore is 2x as common as lead.

Suggestion 
- change Lead from 5-45 to 5-35. This should increase percentages it can place in the TF.
- Change Lead and aspects weight.  Lead from 40-60 and aspects from 16-32.

**Comment by Prometheus0000** [comment]
Presumably the TF specific Galena vein was added since this, but it was never closed. Since both can spawn, it should be fixed, right?

**Comment by Dream-Master** [comment]
I changed the ore high a long time ago.

**Comment by Dream-Master** [comment]
but i will recheck
