### ISSUE TITLE
Finish rest of GT++ multiblock machine quests

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4424]
7.0 has quests for ABS, PSS, Macerator, Washer, Large Sifter, and Thermal Centrifuge.

Other raw material processing multis are:
- [x] Industrial Centrifuge
- [x] Industrial Electrolyzer
- [x] High Current Industrial Arc Furnace
- [x] Industrial Mixing Machine
- [x] Large Processing Factory (9 in 1)
- [x] Cutting Factory Controller
- [x] Industrial Extrusion Machine
- [x] Industrial Material Press
- [x] Wire Factory Controller

Advanced multis:
- [x] Volcanus Advanced EBF
- [x] Cryogenic Freezer

Other multis:
- [ ] multi tank - Currently no recipe
- [x] Large Scale Autoassembler
- [ ] Density² (Implosion Compressor)
- [ ] Mass Fab CPU
- [ ] Cyclotron
- [x] FusionTech Mk IV
- [ ] Helium Prime (wait for recipe discussion)
- [x] Industrial Coke Oven
- [ ] Tree Farmer - DISABLED, DEFER FOR NOW
- [x] Fishing Port
- [x] Amazon Warehouse Packager
- [x] Thermal Boiler

Other items
- [x] Rocket Engines, fuels (already in game?)
- [ ] super bus (I) and (O) - currently no recipes - Right clicking them list contents in chat. No gui. Have to place chest or other thing for player interaction, good for automation or high velocity outputs.
- [x] energy buffer
- [x] GT++ pipes? Potin, others?
- [x] various circuit programmers
- [ ] giant chickens (these are disabled in GTNH now)
- [x] Add to Processing factory/multi machine quest:
The entire machine can have 3 general modes that can be cycled by using a screwdriver on the controller. Each of the modes can support 2 or 3 different machines, that can be selected by putting a circuit into the same input bus as the items you want to process. If you have a look at the description of the controller in NEI, you will see a list of the supported machines for each mode. These are in order and can be used with circuit numbers 20, 21 and 22. This also means, that you can use multiple input busses with different circuits to use the full potential of the machine. You can also use more busses to use different non-consumable items in the recipes.
- [x] Add to Extruding Factory quest:
And in case you didn't read the description in NEI: You can use multiple input busses with a different extruder shape in each and then throw the items to extrude into the bus with the appropriate shape.

@draknyte1 Anything missing here?

**Comment by DietmarKracht** [comment]
We also have Helium Prime ("single block" fusion). Maybe a quest for a cheaper but slower fusion? Also takes very less space

**Comment by Bluebine** [comment]
@richardhendricks 
Info on the Thermal Boiler:
Quest should be unlocked after Tier 6. Should require the Thermal Boiler Controller and 12 Thermal Containment Casings (only needs 10, but they're made in batches of 4)
Text:
The Thermal Boiler is a boiler that produces steam from liquid fuels. More usefully, it can be used to filter lava for the same byproducts that centrifuging it grants, while generating power! The thermal boiler process 1,666L of lava per second, which is roughly 20 copper a minute or one tungsten every minute and 30 seconds. To grant these byproducts, it must be supplied with consumable lava filters.
The thermal boiler also produces 800L of steam per tick, whether or not you are filtering the lava.

**Comment by richardhendricks** [comment]
The single block fusion is under discussion for a tier/recipe change once that's done we can add it.

Need to add GT++ energy buffers for high capacity storage, and look at Power Station quest

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57576464-d5bc2500-7425-11e9-8d1b-1f7625a91be0.png)
![image](https://user-images.githubusercontent.com/1214811/57576466-d9e84280-7425-11e9-98cd-c2640f97215e.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57576646-92b08080-742a-11e9-8674-65d761f834bb.png)
![image](https://user-images.githubusercontent.com/1214811/57576658-e327de00-742a-11e9-811c-360056bf2355.png)
![image](https://user-images.githubusercontent.com/1214811/57576672-6a755180-742b-11e9-8c58-c7b97ff7983f.png)
![image](https://user-images.githubusercontent.com/1214811/57576708-3e0e0500-742c-11e9-8057-e95b94200923.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57576732-cc828680-742c-11e9-9e53-a7b5564fbceb.png)
![image](https://user-images.githubusercontent.com/1214811/57576760-837f0200-742d-11e9-8466-2aa35e4c7e64.png)
![image](https://user-images.githubusercontent.com/1214811/57576792-ea9cb680-742d-11e9-9c7f-7a7ededab9b8.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57576828-1e2c1080-742f-11e9-8468-337c274ea3cf.png)
![image](https://user-images.githubusercontent.com/1214811/57576853-9e527600-742f-11e9-8a9f-95fdb74faa68.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57578878-a32c1f80-7459-11e9-8346-6c76ac82331c.png)
![image](https://user-images.githubusercontent.com/1214811/57578879-a6271000-7459-11e9-9bb2-77b206653d74.png)
![image](https://user-images.githubusercontent.com/1214811/57578883-b50dc280-7459-11e9-8d5b-fc6620e66819.png)
![image](https://user-images.githubusercontent.com/1214811/57578884-b939e000-7459-11e9-9b21-36666d14ab30.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57578930-69a7e400-745a-11e9-96d2-4b2de0559cff.png)
![image](https://user-images.githubusercontent.com/1214811/57578969-e5099580-745a-11e9-8d1a-aea8fc8abc50.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57579167-db356180-745d-11e9-8968-49b58090b43b.png)
![image](https://user-images.githubusercontent.com/1214811/57579196-5c8cf400-745e-11e9-8374-3ce3c058a005.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57579355-5ef04d80-7460-11e9-8e7d-c185c8a07c12.png)

**Comment by Jocroy** [comment]
There has been some uncertainty about some of the multies in the past, but all the important information is in the NEI description. If you we still want to put more information into the quests, here are some writeups for 2 of them, where I feel the info could be needed:

Add to Processing factory/multi machine quest:
The entire machine can have 3 general modes that can be cycled by using a screwdriver on the controller. Each of the modes can support 2 or 3 different machines, that can be selected by putting a circuit into the same input bus as the items you want to process. If you have a look at the description of the controller in NEI, you will see a list of the supported machines for each mode. These are in order and can be used with circuit numbers 20, 21 and 22. This also means, that you can use multiple input busses with different circuits to use the full potential of the machine. You can also use more busses to use different non-consumable items in the recipes.

Add to Extruding Factory quest:
And in case you didn't read the description in NEI: You can use multiple input busses with a different extruder shape in each and then throw the items to extrude into the bus with the appropriate shape.

**Comment by richardhendricks** [comment]
well shit, I guess it will make the next PR

**Comment by draknyte1** [comment]
Just quick fix and reward the guide book for the quest.

**Comment by richardhendricks** [comment]
I have a separate quest for all the guidebooks :man_shrugging:

**Comment by richardhendricks** [comment]
Jocroy's comments are now added.

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/57587479-eb375a80-74ca-11e9-9094-b0b4232961e4.png)
![image](https://user-images.githubusercontent.com/1214811/57587482-eecae180-74ca-11e9-9a9f-8bee94335cd8.png)
