### ISSUE TITLE
Hand Pump trade token I

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#4425]
#### Which modpack version are you using?
2.0.7.2a.dev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Ive tried to make Hand Pump trade token I - LV - in MV assembler, ive put all the stuff in including circuits
#
#### What happend instead? (Attach screenshots if needed)
It took i suppose first viable recipe - LV fluid regulator instead
![2019-05-08_19 48 34](https://user-images.githubusercontent.com/14223368/57396437-b4133180-71ca-11e9-84d2-a96a1f3727d7.png)

#
#### What do you suggest instead/what changes do you propose?
change the recipe - add circuit with proper number for this current process

**Comment by Prometheus0000** [comment]
Already fixed, the regulator uses both an LV and a logic circuit now.
