### ISSUE TITLE
SFM Cable Cost

### ISSUE THREAD

**Issue by NoriSilverrage** [GTNewHorizons/GT-New-Horizons-Modpack#4436]
SFM cables have some odd costs associated with them.
The basic inventory cable is required to craft all other cables. 
Costs for a few cables follows:

- Inventory cable (2x output)
4x stainless steel plates, 3x fluix cables and 2x bundled cables (from PR).

- Cable Cluster
1x inventory cable, 1x IV circuit, 288L molten redstone

- Adv Cable Cluster
8x inventory cables

Every other cable is similar to the cable cluster. They require 1x cable and 1x item specific to what they do. 

The two clusters however stand out as being pretty expensive for what they are.

But first lets look at what they are, how they differ and why they are useful.

The basic cable cluster lets you condense other blocks down to one. So you could have a redstone receiver and emitter in the same block. 
One of the more useful things the cluster can do is combine a camo block with another block in order to hide a cable. This is merely a aesthetic thing, but many people would want to do this.

While useful, this functionality is rarely critical, it'd be pretty simple to just have two blocks place in most cases. Thus the cost of 1x IV circuits is quite high and hard to justify. 

**Suggestion:**
I would suggest either removing the circuit cost altogether, or making it a HV one instead. You do still have to fill the cable cluster with other blocks before it has functionality, so all you are doing is condensing 2+ blocks down to one.

Now on to the Adv Cable cluster. It is basically the same as a cable cluster, except it acts like a Inventory Cable. 8x cables to craft this is insane. That is 16 stainless steel, 12 fluix cables and 8 bundles cables for one block, which is really just a combined inventory cable/cable cluster.

**Suggestion:**
In this case I would suggest that it requires 1x cable cluster and 1x inventory cable.

**Comment by richardhendricks** [comment]
I think these are acceptable @Dream-Master
