### ISSUE TITLE
Essentia Generator Book info cutoff in EMT Potentia Generator entry

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4438]
@bartimaeusnek the bottom of the entry is cut off.  Can you adjust it?

![image](https://user-images.githubusercontent.com/1214811/57506301-12bad700-72c1-11e9-83df-f3d7190bf8ae.png)

**Comment by bartimaeusnek** [comment]
this is just a MT Script thing...

**Comment by Dream-Master** [comment]
will add another side or you planing put the recipe in code @bartimaeusnek  ?
