### ISSUE TITLE
[RFC][Suggestion] Fluid Hatches and Input Busses

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#4446]
Right now, Fluid Hatches and Input Busses are way to expensive, so that ULV hatches are the way to go. Thats why i suggest changing the busses this way (tier slots):

ULV 1 | LV 3 | MV 5 | HV 7 | EV 9 | IV 12 | LuV 14 | ZPM 16 | UV 18

ULV:
Machine + mini chest + 144L Glue / 72L Poly / 18L PTFE / 2L PBI
LV:
Machine + chest +  432L Glue / 144L Poly  / 36L PTFE / 4L PBI
MV:
Machine + copper chest + 288L Poly / 72L PTFE / 9L PBI
HV:
machine + iron chest + 432L Poly / 144L PTFE / 18L PBI
ev:
machine + gold chest + 288L PTFE / 36L PBI
IV:
machine + diamond chest + 432L PTFE / 72L PBI
LuV:
machine + Obsidian chest + 576L PTFE / 144L PBI
ZPM:
machine + Compressed Chest + 288L PBI
UV:
machine + 2 Compressed Chest + 432L PBI
all recipes would go into the assembler at their respective voltage
(8, 30, 90, 480, 1920 ...)

Fluid Hatches would stay unchanged regarding their capacity, but their recipes would be changed to incoperate only the Cells their have right now, but dont require any pumps or other specific crafting parts.

This change should be applied since right now hatches and busses are so expensive, most advanced players simply automate the lowest possible hatch/bus instead of building a higher tiered hatch. The costs of automating any hatch is a hopper and a chest, which gives way more storage space than any hatch could give. These rather cheap recipes might encurage the use of better hatches instead of a chest/hopper set up which will increase sever load on places where its simply not nessecary. All what these blocks do, is simply storing materials, therefore they should not be expensive at all.

**Comment by draknyte1** [comment]
But super buses exist ranging from 16-160 slots. 
Anything above > EV gets to be used purely for crafting and I’d prefer not to change my ASM just for these mediocre changes.

**Comment by Bluebine** [comment]
Fine with this, personally, as long as you check every single recipe that uses an input bus and makes sure you don't cause any issues with recipes. Have fun with that!
Make sure to check with Alk and make sure it wouldn't break the alloy blast smelter as well, I know some of its recipes use a lot of item input.

Also, the ZPM hatch could use a crystal chest (It's an upgraded obsidian chest that you can see through), and the UV can use 1 compressed chest. Just using 2 compressed chests feels kinda weird.

I support the fluid hatch change. Would make them a bit less annoying, I think

**Comment by Anarack** [comment]
GT++ requirements should be ok as they seem to max out around ev/9slots for stuff like the ABS.

I'm more concerned about what will happen to things in slots that no longer exist, but that is more a implementation thing vs concept thing.

**Comment by draknyte1** [comment]
> what will happen to things in slots that no longer exist

They’d vanish.

**Comment by AlexBucket** [comment]
So basically back to how they were pre change? And the whole change came about because they’re piece of piss to make in 5.1

I remember seeing the recipes and thinking they’re not too bad. In my head conveyors on buses and pumps on fluid hatches sounds reasonable seeing as how the outputs at least push automatically. 

The proposed change makes them too easy again.

**Comment by sthegreat** [comment]
Tiered hatches were rarely used in .5.1 and are even more rarely used now due to their high cost (which, for item buses above hv, come with literally no benefit of any kind. All hv+ buses are the same). This change would require people to make some different hatches, but would not excessively add to the costs of multis (like the way LV hatches add to the ebf price for no good reason now).

**Comment by bartimaeusnek** [comment]
@AlexBucket the problem with using conveyors on buses and pumps on fluid hatches is, that its litterally cheaper to just automate a ULV/LV hatch instead of building a MV+ hatch. Two simple hopper are enough for the EBF, the Distillation Tower and the Vac Freezer to fully automate their in and output, because they have rather long processing times. The consequence of this is that newer and less expirienced players will maybe build these hatches, while everyone else just makes laggy hopper setups with minimal Hatch costs. This creats two problems, 1. tps issues on server and 2. an unfair advantage for people that tend to automate a lot in lower tiers.
