### ISSUE TITLE
talisman nourishment

### ISSUE THREAD

**Issue by atreidesL** [GTNewHorizons/GT-New-Horizons-Modpack#4458]
On server eta does not work talisman of nourishment. He not consume food.

#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Eta server.
# 
#### What did you try to do, and what did you expect to happen?
I came into the solo game and tested this talisman and he works well.
#

**Comment by barsikus007** [comment]
![92956c86-2525-4a32-bed8-7ad83ad03344](https://user-images.githubusercontent.com/37113583/63467516-526f8e00-c46e-11e9-9e08-066460e4db9f.gif)

**Comment by barsikus007** [comment]
![7036f06a-f160-4caf-a519-a8fcd0ed7dd0](https://user-images.githubusercontent.com/37113583/63467604-834fc300-c46e-11e9-82c3-cb4c29746a8b.gif)
Eta server

**Comment by barsikus007** [comment]
Still exist on 2.0.7.5
