### ISSUE TITLE
Check on drops from various mobs, maybe document?

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4460]
Alk has graciously added support for custom drops to class specific mobs.  Need to setup grinders and evaluate what they drop now, and how often.

- [ ] zombies
- [ ] skeletons
- [ ] creepers
- [ ] endermen
- [ ] witches
- [ ] wolves
- [ ] creeperfish
- [ ] villagers?
- [ ] pigmen
- [ ] hellhounds
- [ ] ghasts
- [ ] blaze
- [ ] wither skeletons
- [ ] magma cubes
- [ ] imps
- [ ] wisps
- [ ] pech
- [ ] BoP pixies?
- [ ] Thaumcraft special mobs (brutish/mighty/etc)
- [ ] Galacticraft mobs?
- [ ] Twilight Forest mobs? Hobgoblin, books, minotaurs, etc?

**Comment by DoomSquirter** [comment]
you also have player killed, pseudo player killed, and non player killed.

there is a distinction between the first two.  diamond spikes drop player killed drops.  so blaze rods from blazes, for example.  but treasure bags from thaumcraft for example, they only drop from REAL player kills not fake players.  ironically, if you use the thaumic tinkerer dynamism tablet and put a tinkers sword in there you can get actual player killed drops from champ mobs like the treasure bags.

**Comment by Dream-Master** [comment]
we have a mod that do exactly add mob drops to mobs. Not sure if i can choose different mob classes from special mobs but i add the Bone to the lich as an example.

**Comment by richardhendricks** [comment]
where is the config file for that? We were thinking up new ideas for potential drops last night.

**Comment by Dream-Master** [comment]
wicll check when i be home. Guess in the GT horizons cfg folder

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/GTNewHorizons/CustomDrops.xml

**Comment by richardhendricks** [comment]
Witches
![image](https://user-images.githubusercontent.com/1214811/57745735-e83b9600-7693-11e9-8150-4dc6391eb878.png)
