### ISSUE TITLE
EBF Coil recycling

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#4462]
With the Inclusion of the mega blast furnace heating coils need to have recycling recipes or else each upgrade of the blast furnace will lock up very large amounts of material that can not be regained unlike most other gt machines.

**Comment by 0lafe** [comment]
can just give them a disassembler recipe, for some reason they dont disassemble

**Comment by draknyte1** [comment]
> only things crafted in a crafting grid get the correct NBT iirc

I wanted to add in something simple which will put the correct NBT on certain parts for disassembly.
So I can happily include all the coils.

**Comment by Dream-Master** [comment]
Isnt this a code issue on gt side. Why some parts are recycle able ond some not. I see crafting recipe have a dissasembler tag why blocks and items in machines doesent have a tag ?

**Comment by draknyte1** [comment]
It’s not a code issue at all. 
The recipes just don’t get disassembly data when handled that way iirc. 

There’s many things that need to have disassembly data added to it post-creation, so my new machine is going to exist regardless.

**Comment by Bluebine** [comment]
my suggestion for coils:
there should be 2 recipes: 
The current (or removed? idk) assembler recipe. that recipe will give you back the wires used in the coils.
The second recipe would be a macerator recipe, which would return the ingredients used in the mica sheets instead (so mica, asbestos, and rubber). 
You'd have to choose between the two recipes, can't get both, but this would provide an option for people to choose which one they want.

**Comment by Houstonruss** [comment]
Just an arc furnace recipe would make sense

**Comment by quedral** [comment]
you should at least recover some of the wires you've spent to craft the coils imo. its just a waste to throw them to trashcan.

**Comment by Dream-Master** [comment]
kk

**Comment by Prometheus0000** [comment]
Already in https://github.com/GTNewHorizons/GT5-Unofficial/pull/308
