### ISSUE TITLE
Quantum Helmet inconsistent recipe

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4469]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
The recipe for the Quantum helmet is inconsistent compared to the other parts.
#
#### What happend instead? (Attach screenshots if needed)
Quantum Chestplate:
![2019-05-14_12 32 30](https://user-images.githubusercontent.com/11991148/57691503-a6cfca00-7644-11e9-8c65-ff5d4ebdcc6c.png)

Quantum Boots:
![2019-05-14_12 32 21](https://user-images.githubusercontent.com/11991148/57691527-bbac5d80-7644-11e9-9651-2f4b8b00bb14.png)

#
#### What do you suggest instead/what changes do you propose?
Swap the field gen and the sensor in the quantum boots recipe

**Comment by Dream-Master** [comment]
sure shifting only 2 lines in code.
