### ISSUE TITLE
Borosilicate glass fiber

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4472]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Borosilicate glass fiber has a wiremill recipe at a much lower output. actually eithe rthe extruder recipe should be the one with the lower output or make both output equally. 
The wiremill is the machines that should be used for wires. not the extruder.

also take a look at #4402

**Comment by richardhendricks** [comment]
A wiremill is a fancy extruder. I vote for keeping the same outputs between the two but make the wiremill faster. 2x plz. :)
