### ISSUE TITLE
Quest on key conflicts

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4476]
Add quest that talks about most frequently used keys and how to avoid conflicts

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/58148677-4b45a380-7c25-11e9-9462-c2891b57d834.png)

**Comment by Dream-Master** [comment]
why not make a new file and define a default key file ?

**Comment by richardhendricks** [comment]
Everyone has their personal preference, and I don't want to override something someone is already used to using. This quest tells them "Hey, pay attention to these keys, they're important. The rest you can wait until later"

**Comment by stk2008** [comment]
How about shipping GTNH with a pre configured setup in a Zip folder.
So if people want to use yours they unzip it and overwrite theres.
Could even supply it with a key legend.

Even if people have a preferred layout it could help them get started with a setup that has no conflicts then they can tweak as needed.

**Comment by Dream-Master** [comment]
yes it's a default config only but with less or no conflicts.

**Comment by richardhendricks** [comment]
Okay, but no whining about my key setup. :D
