### ISSUE TITLE
Buff frames in Thaumcraft table, add Assembler recipes for most of them

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4495]
Buff Thaumcraft research bee frames so they are cheaper to make (aspect wise) and produce more output. 2x frames for example. Change them to needing 2nd tier bee waxes like refractory wax, magic, soulful, amnesic.

Right now proven frame recipe is this
![image](https://user-images.githubusercontent.com/1214811/57901306-1eab1980-782a-11e9-9946-150e23e3ded4.png)

Suggest changing it to 
3 of every aspect
Remove royal jelly, replace with pollen
Remove silky propolis, replace with normal propolis

**Comment by Dream-Master** [comment]
Proven frames hasnt befor a recipe and was only obtainable from villagers. Lower aspects i am ok with but make the recipe trival is not my plan. Use royal jelly is used to tier the frame. Ok i could change the two different kind of propolis and make them both work in any combination.

**Comment by Hakameda** [comment]
Crafting them is meh, 1 emerald for 4 frames from a villager

**Comment by Dream-Master** [comment]
@Hakameda but is there a limit of proven frames get from villagers or can they be automated ?

**Comment by Hakameda** [comment]
Sort of, but finding them and keeping them alive is annoying

**Comment by Hakameda** [comment]
Trades can be automated, but thats not be an issue with any other trades. Of which some can be abused. Just not a common thing people try

**Comment by richardhendricks** [comment]
Look at rest of TC frame recipes, and also propose lower yield Assembler based recipes.  TC recipes would be an upgrade/cheaper version.

**Comment by Ngar1** [comment]
on older Worlds, there are no void frames any more.
It would be great to make an easier receipt for them
