### ISSUE TITLE
Thaumcraft Recipes are broken due to the Energy Hatch Nerf

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#4497]
Right now, many recipes are broken due to the hatch nerf. For example the Aura Pylon uses Osmiridium Screws. It was meant as a beacon replacement with running costs in form of essentia. Right now that Pylon is LuV due to the energy hatch nerf, and there are many more Thaumcraft Recipes that arent appropritaly tiered for their usefullness, mostly because they were made so early that the hatch nerf wasnt even in sight, and choosen to be a challegening recipe for their appropriate tier. Back then, it was possible to smelt OsIr in HV/EV, simply due to upvolting and the reltively cheap costs of a LuV hatch and many Thaumcraft Recipes are still using this sheme, while the current costs of the LuV and IV hatches makes it impossible to craft them before lategame. This is a hughe issue, that impacts lots of Thaumcraft recipes.

**Comment by richardhendricks** [comment]
Is there an easy way to find affected objects?
