### ISSUE TITLE
Centauri A Surface Dust not oredicted

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4504]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
Add 'dustSpace' oredict tag to centauri a surface dust

**Comment by richardhendricks** [comment]
Aren't there issues with oredicting stuff like this?  oredicts should be for functionally identical things.

**Comment by Prometheus0000** [comment]
Is there a Centauri A? There's only a Centauri Bb, right? And the two dusts also come from Centauri Bb materials, so shouldn't they be renamed Centauri Bb Surface Dust and Centauri Bb Stone Dust? Though looking at the oredict tags, they say A not Bb on the other three items. Maybe change them all to be Bb, or change the planet name?

**Comment by draknyte1** [comment]
If it’s from GalaxySpace, isn’t a whole lot that can be done. 🙃

**Comment by Prometheus0000** [comment]
That's too bad I guess.

**Comment by Dream-Master** [comment]
will do via core mod

**Comment by boubou19** [comment]
This is fixed in 2.1.0.0:
![image](https://user-images.githubusercontent.com/12850933/103162386-50e77000-47f0-11eb-87e8-754fa8b4968d.png)

![image](https://user-images.githubusercontent.com/12850933/103162387-5f358c00-47f0-11eb-914e-e2c8e6a9215a.png)
