### ISSUE TITLE
Create new comb+leaf recipes

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4505]
For players who do both bees & crops, add in recipes that produce extra outputs when mixing both items.
Right now
9 leaves or combs + 1 crushed + water = 4 purified.
9 leaves or combs + uum = 4 purified.

Add in LCR recipe 
9 leaves and 9 combs + 1 crushed + distilled water = 16 purified
9 leaves and 9 combs + uum + distilled water = 16 purified

**Comment by DietmarKracht** [comment]
9 combs + uum = 4 purified right now

**Comment by richardhendricks** [comment]
kk, I wasn't sure, updating ticket.

**Comment by richardhendricks** [comment]
I added distilled water to make it a little more work, but not much if you have infrastructure.

**Comment by 0lafe** [comment]
16 out is kind of a lot. Why not use 8? It still doubles your output from ores if you do crops/bees, but an additional 4x is sort of a lot

**Comment by Ngar1** [comment]
With two  you have only a litte advantage to GT Machine. As compromize 3x ?

**Comment by richardhendricks** [comment]
yeah I think 2x is probably not worth the effort, but 3 or 4 makes it more worthwhile.  it doesn't have to stay a LV recipe, we can make these MV or HV.  Will probably need a circuit so the leftovers don't accidentally fall through as the lower yield recipe. Time shouldn't be too long though.

**Comment by richardhendricks** [comment]
could also change it from distilled water into a higher tier fluid. Not sure what would be good/interesting here. Lava perhaps? sulfuric/hydrochloric acid?  HCl sounds interesting to me, but lava could work.

**Comment by 0lafe** [comment]
Isn't 2x, totalling 8x still 8x better than GT? At 3x would be 12x better?

**Comment by richardhendricks** [comment]
When you do a full chain, you get 4x as much output from an ore.  Now if a player does the whole 2nd chain, his output should be what?  Doubled or quadrupled? The first time, it was 4x.  Now doing it all again, it is only 2x more.  That's why it should be 2 or 3x in my opinion.  As I said, we can also uptier the necessary fluid & recipe.

**Comment by 0lafe** [comment]
Because 2x is kind of a lot, and a well worth upgrade. It's really more of an 8x through the usage of the 2 options that give 4x, and as they can't be used together at the moment, that's kind of a fairly large upgrade.

Really what I'm saying is it should be addative not multiplicative, as the inputs you're doing are addative and not multiplicative. +1 dupe option for the rewards of that dupe option.
