### ISSUE TITLE
SAG Mill sand recipe is broken

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4511]
Currently the SAG mill recipe for Sand is just a 50% sand output.  Change it to 50% quartz dust instead and the SAG mill would be great for making quartz dust.

**Comment by Hakameda** [comment]
Macerator already makes quartz sand

**Comment by Bluebine** [comment]
SAG mill does a lot of macerator stuff. it's an alternative to macerator
