### ISSUE TITLE
Tree Tap Suggestion

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#4525]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Make IC2 tree taps less annoying or have more durability? Maybe add some iron ones with better durability? I generally skip trees and go straight for stickreed because of the taps.

**Comment by NoriSilverrage** [comment]
Agreed. Once you get the electric its fine, but the basic version breaks far to quickly and it's annoying to craft.

**Comment by Impos913** [comment]
I just prepare materials to craft 32 or 64 and leaving them in the crafting station, when I need resin I am crafting a couple then tapping trees.

**Comment by NoriSilverrage** [comment]
That's what I ended up doing, but then since they don't stack, you end up clogging storage. I'd be for a more expensive recipe if needs be, just to make the durability higher. Though really it should just be higher, or have a alternative.

**Comment by Impos913** [comment]
lol I found the clue: add tree tap as a tinkers tool. :D lol

**Comment by NoriSilverrage** [comment]
That'd certainly work, but eh, not really needed as you only tap for so long before you end up automating.

**Comment by Impos913** [comment]
Cant you automate tapping with forestry farms, wasnt there a electron tube that does this?

**Comment by NoriSilverrage** [comment]
There is indeed. Also there is the stickreed crop. Doesn't make the tree tap any better however.

**Comment by richardhendricks** [comment]
There's a couple of different ways to get sticky resin.
Treetap
IC2 stickreed
Bees
Chopping down the tree gives you some, and then processing the logs can give you some.

I agree, the treetap is kinda annoying, but not sure we have much control over it.  It would be nice if the recipe didn't need so many different types of wooden pipes.  Having it only use 1 type would be much better IMO.

**Comment by NoriSilverrage** [comment]
True, it'd be acceptable if the recipe was simpler (it's not the cost of the recipe).

**Comment by shawnbyday** [comment]
Yea I usually just skip rubber trees all together. I go straight for Stickreed. Bees isn't really an early game option. Just easier to craft and maybe make them stackable...god stackable taps would be a huge QOL too.

**Comment by NoriSilverrage** [comment]
Or make the electric more accessible early.

**Comment by richardhendricks** [comment]
Where are they tiered now?  LV or MV?  I would be OK with moving the IC2 tools (treetap, windmeter, electric hoe) to LV.

**Comment by Impos913** [comment]
They require stainless steel..

**Comment by NoriSilverrage** [comment]
Yeah, that. It's later MV since it needs SS, and honestly by that point, you quite possibly don't need it anymore..

**Comment by shawnbyday** [comment]
I'd say even changing it to use steel is good. By the time aluminium is accessible you can do something else or your rubber production is so efficient it is less of an issue. I think if you do aluminium and make the tree taps easier to craft and stackable things would "feel better".

**Comment by NoriSilverrage** [comment]
Steel would be good too. Just wasn't sure if the team would be up for a almost 2 tier change vs 1 tier.

**Comment by richardhendricks** [comment]
Steel would be fine with me. You have to get batteries before you can make them, which is quite some time.

**Comment by Houstonruss** [comment]
Steel and a sulfuric acid battery would be cool to see. It makes sense to have an "old style" battery in a low tier.

**Comment by Impos913** [comment]
Sulfuric acid battery is single use. Recipe should have a rechargeable battery.

**Comment by richardhendricks** [comment]
Sodium could work. Easy to get quantities in LV.

**Comment by Houstonruss** [comment]
![treetapsuggestion](https://user-images.githubusercontent.com/50430417/101431900-d5bc2980-38d5-11eb-8932-df1ced968986.png)

A nice LV recipe for the treetap. Thoughts?

**Comment by Houstonruss** [comment]
Treetap changed in script.
[IC2.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5663083/IC2.zip)

**Comment by Prometheus0000** [comment]
If you're going to make a pr, you should change the quest too.

**Comment by botn365** [comment]
dont bother makign a PR il do it in code

**Comment by Houstonruss** [comment]
ya okay

**Comment by Dream-Master** [comment]
Add two screws to the recipe and I am fine. How the old recipe looks like?
