### ISSUE TITLE
Certus/Fluix bee has no GT equivalent

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#4527]
#### Which modpack version are you using?
2.0.7
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Converting Gendustry bees to GT bees
#
#### What happend instead? (Attach screenshots if needed)
I found out that Fluix Dust bee and Certus Quartz bee have no GT equivalent
#
#### What do you suggest instead/what changes do you propose?
Add equivalent GT bees (if that is not intentional).

**Comment by repo-alt** [comment]
Looks like "Fluix Dust" bee has an equivalent called just "Fluix" bee.

**Comment by repo-alt** [comment]
Same with Certus Quartz - in GT it is called just "Certus".
Conversion still fails for them.

**Comment by repo-alt** [comment]
@bartimaeusnek :
As far as I understand bee conversion is done in GT_Proxy.onPlayerTickEventServer and gendustry bee is replaced with GT bee if there is "gregtech.bee.species" + bee name in AlleleManager.alleleRegistry

GT bees are registered in allele registry in GT_AlleleBeeSpecies, but perhaps AlleleManager.alleleRegistry.registerDeprecatedAlleleReplacement may help?

**Comment by Dream-Master** [comment]
will add this two bees.
