### ISSUE TITLE
Iron duplication using water tank siding

### ISSUE THREAD

**Issue by LargeJoj** [GTNewHorizons/GT-New-Horizons-Modpack#4553]
#### Which modpack version are you using?

2.0.7.0

#### What did you try to do, and what did you expect to happen?
1 iron rod along with some glue and wooden boxes can be used to create 1 water tank siding in an assembler. The siding can then be used in a arc furnace to be broken down into 1 Wrought Iron Ingot, which obviously can be reprocessed to make 1 iron rod and 2 small iron dust. 

#### What happened instead? (Attach screenshots if needed)
Here are the recipes:
![Screenshot_1](https://user-images.githubusercontent.com/50957859/58263058-fdbe5900-7d40-11e9-9e27-5280f742055a.png)
![Screenshot_2](https://user-images.githubusercontent.com/50957859/58263066-0151e000-7d41-11e9-83a6-1f77fe997d89.png)

I think this may have been around for a while, it looks like the assembler recipe could've been added during 2.0.3.0, and I assume the arc furnace recipe just wasn't changed. #2808 seems to be when it was suggested. 

#### What do you suggest instead/what changes do you propose?
Change the arc furnace recipe to give 2 small wrought iron dust or 4 nuggets. I believe the plasma arc furnace also has a recipe like this, which should also be changed.

**Comment by Dream-Master** [comment]
i can disable the arc furnace recipe or change it.
