### ISSUE TITLE
Thaumcraft Golem causing crash

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4554]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Crashlog here: [Crashlog](https://pastebin.com/dxuq12TF)

Steps to reproduce: 

1. Make a thaumcraft Straw golem.
2. Place it on the ground.
3. Attach golem core empty
4. Leftclick with golemancers bell to pickup
5. Put the golem into hotbar
6. Crash when selecting it in hotbar
#

**Comment by Dream-Master** [comment]
[B#402]  java.lang.ClassCastException: crazypants.enderio.machine.painter.TileEntityPaintedBlock cannot be cast to flaxbeard.thaumicexploration.tile.TileEntityAutoSorter

both mods are open source.
