### ISSUE TITLE
Coal jetpacks GUI disconnect you

### ISSUE THREAD

**Issue by steijn1** [GTNewHorizons/GT-New-Horizons-Modpack#4559]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
my own
#
#### What did you try to do, and what did you expect to happen?
Opening the GUI with the adventure backpack jetpack should open the GUI
#
#### What happend instead? (Attach screenshots if needed)
it disconnects you from the servers
#
#### What do you suggest instead/what changes do you propose?
get it in working order

**Comment by richardhendricks** [comment]
Has been confirmed by another user.  Some users also say jetpacks work fine for them.  Need to investigate.

**Comment by steijn1** [comment]
Apparently this is mainly caused when you spawn it in, regular craft works.

**Comment by shawnbyday** [comment]
Can confirm in 2.0.7.2 if you craft it GUI doesn't disconnect you. If you spawn it in GUI disconnects you.

**Comment by Dream-Master** [comment]
log ?
