### ISSUE TITLE
possible issues with GT bees

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4565]
Vibrant alloy uses setHasEffect but it is empty.  Also has Lifespan set twice.
    VIBRANTALLOY(GT_BranchDefinition.GTALLOY, "VibrantAlloy", false, 0x86A12D, 0xC4F2AE) {
        @Override
        protected void setSpeciesProperties(GT_AlleleBeeSpecies beeSpecies) {
            beeSpecies.addProduct(GT_ModHandler.getModItem(GT_Values.MOD_ID_FR, "beeCombs", 1, 7), 0.30f);
            beeSpecies.addSpecialty(GT_Bees.combs.getStackForType(CombType.VIBRANTALLOY), 0.15f);
            beeSpecies.setHumidity(EnumHumidity.DAMP);
            beeSpecies.setTemperature(EnumTemperature.NORMAL);
            beeSpecies.setHasEffect();
        }

        @Override
        protected void setAlleles(IAllele[] template) {
            AlleleHelper.instance.set(template, EnumBeeChromosome.SPEED, EnumAllele.Speed.SLOWER);
            AlleleHelper.instance.set(template, EnumBeeChromosome.LIFESPAN, EnumAllele.Lifespan.SHORTEST);
            AlleleHelper.instance.set(template, EnumBeeChromosome.FLOWERING, EnumAllele.Flowering.FAST);
            AlleleHelper.instance.set(template, EnumBeeChromosome.LIFESPAN, EnumAllele.Lifespan.SHORTEST);
        }

**Comment by Dream-Master** [comment]
beeSpecies.setHasEffect();
this means the bee is glowing so far i understand not need any addition

**Comment by Dream-Master** [comment]
ok lifespawn need to be fixed

**Comment by richardhendricks** [comment]
Many bees are also missing and effects and probably need them.  IE, lead and arsenic bees should probably poison.

**Comment by Dream-Master** [comment]
feel free to add some effects or create new ones @richardhendricks

**Comment by Prometheus0000** [comment]
This looks done? Effects of bees should be a separate item if anyone cares about that.
