### ISSUE TITLE
Torture Device (HV Quest - Slice n' Splice) Wrong Loot Bag?

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#4572]
#### Which modpack version are you using?
2.0.7.2
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Completing this quest offers a MV loot bag instead of an HV loot bag.

**Comment by shawnbyday** [comment]
It also gives T1 Technician coins.

**Comment by Bubunator** [comment]
Issue seems to be back...found out playing on epsilon

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/93179291-76e67a00-f703-11ea-9942-7238ec1c5202.png)
? This is already fixed in 2.0.9.0 QF4, maybe the server didn't update the quests correctly. I even check to see if it was an MV bag labelled as HV.
