### ISSUE TITLE
Minecraft flowers not working correct with IC2 crop sticks

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4574]
All tulips
Orchid
Sunflower
oxeye daisy
allium
azure bluet

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ?

**Comment by Prometheus0000** [comment]
These all work aside from sunflower, maybe you didn't hold enough at a time? But I don't think that's really worth fixing to begin with considering they all create the same rose crop. And tulip doesn't create tulip flowers, but does create rose.
