### ISSUE TITLE
Aluminum Brass missing smelting

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4586]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Aluminum Brass dust has no smelting recipe. It can only be smelted by the smeltery.

**Comment by Dream-Master** [comment]
@DietmarKracht from tico or gt ?
