### ISSUE TITLE
Redo DE Core pre-quests

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4591]
Current DE core pre-quests discuss automating thauminite, which is no longer part of the DE core recipe.  The prequests need to be updated to giving information on how to get sufficient ichorium, neutronium, etc. instead.

mobfarm quests 
Cursed earth? Not needed with EIO powered spawners, or endermen spawners from Roguelikes? Or endermen spawners from End towers?
corporeal attractor? (work on different types?)
Void spikes for killing - Should drop the correct shards?
advanced item collector for picking up items, ignores webs?
one for endermen, one for nether zombiepigman to give proper shards

method to deal with webs - lava or water?
Dropper, planes, I think there's a fluid AE thing
pistons pushing the floor/ceiling and then releasing lava or water
Spatial AE

gadomancy Infusion claw quest

automatic infusion quest, including placing items on pedestals and starting the infusion

WA infuser as Tile Entity

**Comment by BlackFlameTNT** [comment]
So I would say you need a quest line tell you about making 2 spawner one at the end and one at the nether it ask the player to get 8 of both shard. 

Another quest will ask the player to make 4 normal ichor and 8 DE ingot it will be a test for making the DE core and will end up will a fail and ask next to try ichor ingot for making to core.

It need only the last 4 step to be change and I would like to see to ask for UV or UHV part instead of ZPM part the player will be at early UHV that time.

**Comment by Folanlron** [comment]
> , I think there's a fluid AE thing

Bad idea too use Fluid Formation/Annihilation planes this way, massive TPS and graphical lag issues from doing it.

**Comment by 0lafe** [comment]
I'm down for the part change, it used to be a zpm quest which made sense, but uptiering it is probably a good idea. Maybe make the solar zpm too? 

I think a quest explaining the automation options you'd use in a general sense is enough, in combination with maybe some text in the quest line for DE telling you it's possible to automate/will help. 

If we want to have difficulty here, I really suggest staying away from the handholding for UV+ setups using early game mechanics. If you can't make a spawner or an auto infuser, I think it should hinder your progression. There's guides for it if you really need them, but the process itself is incredibly reasonable to be expected to be figured out.

**Comment by BlackFlameTNT** [comment]
changing it to ZPM solar mean it need UEV circuit and drag the quest line too long and after the solar nerf all solar after IV need 2 solar to be upgraded it and you can do the game 100% without solar and why you asking for solar now?

**Comment by 0lafe** [comment]
But it already asks for a solar?...

**Comment by AlexBucket** [comment]
I agree with 0lafe. It's an endgame quest, it shouldn't need hand-holding for 'how to make a mobfarm'. If anything, update the quest text in the thaum tab for thaum stating where to get the shards as a hint if it's not already there.

 Changing the ichor from 16 -> 8 is dumb. It's endgame armor, it shouldn't be a walk in the park and you should have to work hard for it.

**Comment by Dream-Master** [comment]
@richardhendricks what is the the last change in the quest file ?

**Comment by richardhendricks** [comment]
16 Nt, 16 Soc, 4 Ichor, receive 16 cores.

**Comment by Dream-Master** [comment]
why not  16 16 16 DE Cores are endgame ?

**Comment by richardhendricks** [comment]
We've already had several extensive arguments about it.  We will try 4 for now, once we have quests in place we can increase.

**Comment by 0lafe** [comment]
Why not 64 Nt? Didn't see agree on not changing that?

**Comment by richardhendricks** [comment]
I changed it back to rewarding only 16 cores, so it is 1:1 on Nt and SoC.  For ichor it is 1:4

**Comment by 0lafe** [comment]
Uhh, it should be 64Nt for 16 cores, 4:1 Nt, ichorium can be 1/4 that, of 1/16 if you really for some unknown reason think it's too much

**Comment by richardhendricks** [comment]
I'm sorry, I was mis-remembering.  It is 64 Nt, 16 SoC and 4 Ichorium, and rewards 16 cores.

**Comment by richardhendricks** [comment]
We can talk about setting up mobfarms in earlier parts of the questbook, and just mention which mobs are needed and the dims.  I'm gathering the thaumcraft nether/ender trees doesn't work for this, it has to actually be in the dims for the shards to drop. 

I think I agree a player should have *some* experience with automation by this point - Any of SFM, OC, AE2, PR could probably do the pedestal setup?  

And maybe a golem or whatever with the claw for the activation? I don't know about that part. How do you make it start the ritual but not stop it?

And then world accelerators of appropriate tiers.

Keeping the essentia jars filled might be a whole questline in itself.

**Comment by richardhendricks** [comment]
Please keep the recipe discussion in https://github.com/GTNewHorizons/NewHorizons/issues/4584

**Comment by 0lafe** [comment]
Sure. I'm not really sure mobfarms need a quest, they're farily self explanatory. We give quests for killing methods, and a spawner mover. The real bad parts of mobfarms, like webs, are related to higher tier things that are mostly past the quest book.

**Comment by Folanlron** [comment]
AE2 is tricky, as it's a combination of AE2 + EnderIO(it could be pure AE2, sub-network item placement but either way your stuck at a limit of 9 separate items(I know there is way to get AE2 too go beyond this limit I have never done it though, and it seems really weird as your basically tricking AE's auto-craft system))

I'm not sure on activation use(I'm not that far into TC yet) but in the past I would use a Autonomous Activator, it would need TT's Research Share book + a wand(wand needs to be recharged also occasionally), set a Item detector from PR and have it only "pulse" once too activate the ritual.

And what Essentia Jars ? Thaumic Energestics takes care of storage problems, just have too check essentia counts before every auto-craft(which 99.9999% people do anyway, it's the crazy ones who don't haha)

**Comment by richardhendricks** [comment]
We don't have autonomous activators in the pack, so we need alternative methods. Need options here @0lafe

**Comment by 0lafe** [comment]
Gotta check with WAs, theyll kill everything real fast if you can fuel it lol. 

doing >9 items isn't too difficult, and it's not that strange. It just nests recipes. Its not that hard to use, but is a little weird to think of. 

The claw is iirc the only thing we have to start infusions. The tablet didn't work when I tried it, something about it needing research too. Claw works amazing tho. Put a wand in, and it'll do your recipes on a redstone signal. How I made all my ichorium.

**Comment by richardhendricks** [comment]
Ah, looks like the Infusion Claw is simpler than I thought. 

https://ftbwiki.org/Infusion_Claw

More of a special block you insert a wand into. Should be pretty doable then.

**Comment by richardhendricks** [comment]
So you could basically put hoppers to pedestals and a pipe to the altar and then use the Claw to initiate recipes?

**Comment by 0lafe** [comment]
Uh, well, maybe. Id never use GT item pipes at this point, but a conduit network, sfm cables, or AE if it was OC. Could do like rationing pipes somehow maybe too? I'm not sure.

**Comment by richardhendricks** [comment]
I was saying that mostly as a joke. :dagger:

**Comment by Dream-Master** [comment]
why not mentioned mob farms in the quest book. Like the idea

**Comment by AlexBucket** [comment]
Do you really have to explain mob farms to someone who’s already done most of thaumcraft, BM and at LuV stage? They’re pre-reqs to unlocking the quest tab. Not to mention the whole tab relies on figuring out what item triggers the next quest to appear. Do you really need to explain mob farms?

If you really need to mention it, just add a “HINT: ender shards from ender men in the end and nether shards from pigmen in the nether” to the quest that requires you to make your first ichorium.

**Comment by Dream-Master** [comment]
I mean in general not at this tier.

**Comment by richardhendricks** [comment]
OK, so the only action left is a quest discussing mobfarms?

**Comment by Prometheus0000** [comment]
Was already handled in the issue mentioned above.
