### ISSUE TITLE
Mod Suggestion

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#4592]
https://minecraft.curseforge.com/projects/technomancy

![Screenshot_2019-05-28-22-11-40](https://user-images.githubusercontent.com/36479271/58505725-412c2380-8196-11e9-93c6-9dfd8052a43b.png)

**Comment by 0lafe** [comment]
Other than the things that sound super OP, we already have wireless essentia transport with thaum ae

**Comment by Impos913** [comment]
Why would it be super OP just transferring shit. I hate thaumcraft pipes and necer gonna use them. I didnt know there is a wireless essentia transport way in thaumic energistics

**Comment by repo-alt** [comment]
Not wireless essential transport per se, but as you can store essentia in AE disks and there are several ways to transport AE channels...

**Comment by DoomSquirter** [comment]
there's this thing in the base mod called essentia mirrors.  you should try them sometime.

**Comment by Impos913** [comment]
They are not what I wanted. What I want is fill jars with essentia directly from alembics without a connrction between them. And pull from jars to something else.

**Comment by DoomSquirter** [comment]
there is a thing but I can't rem it's name.  essentia something.  you attach it to back of a alembic.  🤷‍♂

**Comment by Impos913** [comment]
Wiki doesnt say essentia funnel is used like that.

**Comment by Anarack** [comment]
The funnel only draws like a infusion altar, I don't think it will do anything unless you can provide suction of some kind to it.

**Comment by Impos913** [comment]
https://ftb.gamepedia.com/Essentia_Funnel
What are you talkin' about??

**Comment by 0lafe** [comment]
Not op to transfer, I meant the rest of the mod has op stuff. The transfer itself is just a redundant feature as we have ways to do that already. 

> I hate thaumcraft pipes and necer gonna use them

Lmao ok

**Comment by Impos913** [comment]
Idk the mod just seen that on curse.

**Comment by Anarack** [comment]
Wring funnel thing for one. I don't fully remember its name but I have used the thing.

**Comment by Anarack** [comment]
ah https://ftbwiki.org/Essentia_Pump is what it was called, from witching gadgets.

**Comment by bartimaeusnek** [comment]
I've taken a deeper look into that mod, and it would give us some nice additions. But we would need to Tier it propperly and completely nerf it, rework recipes and code. So im currently against until wer are done with nerfing/repairing all other mods (Witchery, Thaumic Horizons, some final touches on Witching Gadgets).
