### ISSUE TITLE
Mica in the Mega EBF

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#4594]
This multi block eats 1-2 veins of mica per upgrade meaning over its lifetime each player that builds one will consume 8 veins of mica assuming you only upgrade the coils 4 times from IV ish onward which covers a large area of the overworld.

Suggestion add mica to one of the t2-t3 planets around when you should make it. Possibly ross128b as thats the main boron source for it in IV.

**Comment by DietmarKracht** [comment]
Kepp in midn that also the advanced ebf exists. Players might use the mega ebf when they need it at ZPM or UV which is when you might have access to the deep dark

**Comment by Dream-Master** [comment]
sure but add mica to another planet is ok.
@bartimaeusnek  what about replace bismut with mica on mars ? (bismut will be on ross)

**Comment by Bluebine** [comment]
copied from another issue.
my suggestion for coils:
there should be 2 recipes:
The current (or removed? idk) assembler recipe. that recipe will give you back the wires used in the coils.
The second recipe would be a macerator recipe, which would return the ingredients used in the mica sheets instead (so mica, asbestos, and rubber).
You'd have to choose between the two recipes, can't get both, but this would provide an option for people to choose which one they want

**Comment by Houstonruss** [comment]
Talked with bart and he likes the idea of replacing bismuth on mars with mica. Having an arc furnace recipe to recycle coils seems like a good idea.

**Comment by DoomSquirter** [comment]
hold up.  bismuth.  is this the stuff you need to make disenchanter?  or do I have the wrong gem?

is bismuth on moon?  if someone's trying to make that they need a decent amt of it (18 gems to make 2 blocks).  only place this spawns is TF in overworld in small ores.  as long as there's another source for the bismuth that's not too far away it should be fine (if it's what I think it is)

**Comment by Anarack** [comment]
Bismuth is a metal doom.
It still spawns on phobos as long as that vein is left alone red steel is ok for anything that needs it.

**Comment by Houstonruss** [comment]
IIRC you get it in tinies from the nether too.

**Comment by boubou19** [comment]
Bismuth was added on mars to help players getting it in quantities. AFAIK it's the only mix that gives regular bismuth ore.

**Comment by Houstonruss** [comment]
@boubou19 Now with ross128 you can find bismutite vein.

**Comment by boubou19** [comment]
also starting LuV finding mica is not much of a problem anymore with the Electric ore prospector scanner

**Comment by bartimaeusnek** [comment]
@DoomSquirter @boubou19 pure Bismuth ore isnt nessecary if you can get a vein complete persisting out of bismuth compounds... its also just T3 instead of T2 therefore not really a tier up, since you dont need Bismuth in large quantities and still can obtain it from small ores...

**Comment by richardhendricks** [comment]
See no code changes needed in this issue, just config/recipe changes.
