### ISSUE TITLE
Ardite missing compressor recipe

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4602]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to compress ardite.
#
#### What happend instead? (Attach screenshots if needed)
nothing happened as it doesnt have a compressor recipe.
#
#### What do you suggest instead/what changes do you propose?
Add the compressor recipe to all tinkers construct materials.

**Comment by leagris** [comment]
Can we re-open, as the compressor recipe only accepts Tinkers Ardite Ingots and not the GT ingots you get from the EBF?

**Comment by Prometheus0000** [comment]
Dream, why did you close a bunch of bug reports? It's not like this is the only one.

**Comment by Dream-Master** [comment]
I close this because its from 2019 and no one repost it or add a comment.

**Comment by Prometheus0000** [comment]
That doesn't mean it's fixed though. Just that there's a lack of people fixing things.

**Comment by Dream-Master** [comment]
we are drown in issues so old issues need to be fixed or closed or we have 2k issues soon :)

**Comment by Prometheus0000** [comment]
I thought it was agreed that we wouldn't close old bug reports, only balancing/suggestions type stuff? https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6669

**Comment by Ethryan** [comment]
This should be fixed in dev now
