### ISSUE TITLE
ExU Pipes

### ISSUE THREAD

**Issue by Hakameda** [GTNewHorizons/GT-New-Horizons-Modpack#4605]
#### Which modpack version are you using?
Latest
#
#### If in multiplayer; On which server does this happen? 
420blazeit's server
#
#### What did you try to do, and what did you expect to happen?
Craft some ExU cables
#
#### What happend instead? (Attach screenshots if needed)
I cried
#
#### What do you suggest instead/what changes do you propose?
The cables are a bit more expensive then they should be, Hyper rationing pipes, rationing pipes.

1 EV circuit per ration pipe is a bit much, it should have a buffed output, 1 to 8 or a lower tier requirement or both

**Comment by Hakameda** [comment]
Some of the other pipes are also weirdly tiered as well, you unlock basic cables in LV

**Comment by Hakameda** [comment]
192 hyper ration pipes cost, 192 LV Circuits, 192 MV Circuits, 192 HV Circuits, 192 EV Circuits

I think recipe is fine, If it was 8x out, opposed to 1x
Probably 8x on each step, the other pipes are sometimes useful. But mostly unused

**Comment by 0lafe** [comment]
I'm quite unsure as to the reason they cost so much in the first place, but this seems like a good change for it. 

420blazeit is the best server
