### ISSUE TITLE
Add Radon Recipe to the BioVat

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#4606]
Add Radon Recipe to the BioVat

**Comment by richardhendricks** [comment]
update?

**Comment by Prometheus0000** [comment]
Are you ever doing this, or should this be closed @bartimaeusnek ?

**Comment by Dream-Master** [comment]
i can add such recipe if you want. So far i remember i add all Circuit recipes(stem cells bio cells) in the core mod
I need some recipe suggestion.

**Comment by Prometheus0000** [comment]
Do we need another way to get radon though?

**Comment by Dream-Master** [comment]
why not. If ou have two or more ways is better

**Comment by Prometheus0000** [comment]
We have seven though?

**Comment by Dream-Master** [comment]
to get radon ? i know only one but maybe gt++ add some ?

**Comment by Prometheus0000** [comment]
There's the CR/LCR normal one using plutonium, the sift radioactive ores (uranium, pitchblende, uranite?) to get radium-226 which decays to decayed radium-226 which you electrolyze to get radon, centrifuging proteus planet dust, replicating with UUM, making it via fusion and cooling it (this seems unrealistic for gaining it honestly), and the two dehydrator recipes (they're probably not a real source).

**Comment by 0lafe** [comment]
The vat is kinda low tier right? Can we use this to finally have good radon recipes for EV+ as well?

**Comment by ScriptedPiky** [comment]
The Vat can be made in HV~, but the glass, recipes, radiation treatment, and many other various things can be adjusted to be considerably complex and high tier. Would be quite interesting to see, but I'm not sure how well or 'realistic' bacteria can somehow generate or allow for Radon production to exist. Still quite fun to think about.

**Comment by 0lafe** [comment]
I'm sure we can utilize it for something like the radiation aspect and some U/Pu base? Seems better than what we have atm with the LCR and Pu nuggets

**Comment by Pxx500** [comment]
Is this still relevant? Radon is now crafrable in LCRs though uranium

**Comment by Dream-Master** [comment]
idk how radon get in rl. Put all in the lcr is boaring

**Comment by Pxx500** [comment]
You don't get it irl, it doesn't really have sources, it is just created everywhere in the ground and rocks in very small quantities from other radiactive elements and just goes to the atmosphere where it's diluted.

**Comment by Dream-Master** [comment]
Are we add Radium to gt materials already ?

**Comment by Pxx500** [comment]
It's impossible to obtain outside of everglades right now

**Comment by GTNH-Colen** [comment]
I don't think this is necessary tbh, radon is used in huge quantities and making it a PITA with some biovat stuff is rather pointless.

**Comment by Dream-Master** [comment]
> I don't think this is necessary tbh, radon is used in huge quantities and making it a PITA with some biovat stuff is rather pointless.

Who spoke about bio vat. Guess this make less sense. I mean maybe new ways to get Radon out of Rhadium or out of the air in a space staion aerth etc.

**Comment by Dream-Master** [comment]
> It's impossible to obtain outside of everglades right now (The default radium dust)

This dimension from gt++ make no sense for me maybe we have to put stuff elsewhere.

**Comment by Pxx500** [comment]
Radon is very heavy so technically the most should be around bedrock, maybe a new multiblock that can take radon dusts and output constant amount of radon/s for some time

**Comment by Pxx500** [comment]
> > It's impossible to obtain outside of everglades right now (The default radium dust)
> 
> This dimension from gt++ make no sense for me maybe we have to put stuff elsewhere.

I made a mistake and looked at the wrong dust, it was GT++ dust that's why I deleted this comment

**Comment by GlodBlock** [comment]
the naq fuel line also can give a lot radon, from the delay of heavy nuclear element

**Comment by glowredman** [comment]
> @glowredman so we need to add radon to the earth space staion

If you mean the Planetary Gas Siphon multi, the no. It is only intended for space stations surrounding gas planets and the earth isn't one.

**Comment by Pxx500** [comment]
Maybe a new multiblock that needs to be placed on bedrock and extracts radon? Not like a fluid mining drill, it should be much slower and should never deplete (but maybe make it weak and not scalable so it's only early game [EV-IV]?)
