### ISSUE TITLE
Molten Redstone cells from IC2 battery quest not working

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4609]
Cannot empty into ULV tank

**Comment by richardhendricks** [comment]
Can empty with a fluid canner but can't seem to extract.  Needs more testing.

**Comment by richardhendricks** [comment]
Fluid canner can auto-output to portable iron tank OK

**Comment by richardhendricks** [comment]
Can move from portable <-> ULV but cannot fill empty cans from ulv

**Comment by draknyte1** [comment]
It’s like Steam. 
There’s several fluids GT refuses to handle properly, so it’s not a GT++ issue. 
(They’re no different to super/quantum tanks beside capacity, confirm they also don’t work)

**Comment by richardhendricks** [comment]
Ye I don't think it is a GT++ issue, just curious as to why it is this way. Is this something that can't be fixed?

**Comment by draknyte1** [comment]
It exists in the base code somewhere. 
Of course we can! (If we look why and apply glue)

**Comment by richardhendricks** [comment]
Quests rewarding molten redstone cells fixed to just reward redstone. Still need to fix code to find out why.
