### ISSUE TITLE
[ProjectRed] Overflow chip does not work

### ISSUE THREAD

**Issue by rontav** [GTNewHorizons/GT-New-Horizons-Modpack#4615]
#### Which modpack version are you using?
2.0.6.2
#
#### If in multiplayer; On which server does this happen? 
Offline server
#
#### What did you try to do, and what did you expect to happen?
The issue I have has been described [here](https://github.com/MrTJP/ProjectRed/issues/1162).
#
#### What do you suggest instead/what changes do you propose?
Can the overflow chip be fixed?

**Comment by Dream-Master** [comment]
@rontav if somone can code in scala why not.
