### ISSUE TITLE
More bee breeding lines

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4616]
- [x] Dyes (better pollination options, fastest worker, tolerances)
- [x] ghastly/smouldering line - require special skills to breed.  use drones, genetics, gendustry, alveary in nether with humidity mods, 
- [x] oily/refined
- [x] miry/swampy/elastic - has specific biome requirements
- [x] Sandwich
- [x] Ash/Apatite/Fertilizer
- [ ] Coolant
- [ ] Energy
- [ ] Pyrotheum
- [ ] Cryotheum
- [ ] Twilight Forest
- [ ] Enderium bee for blinding speed

**Comment by richardhendricks** [comment]
Dye bees offer a lot of great stats useful for breeding. better pollination stat for one, look also at rest of the bees.

**Comment by richardhendricks** [comment]
oily and elastic bees?

**Comment by richardhendricks** [comment]
Look at registries, maybe remove the item specific ones?  Give out uber-registry as quest reward for breeding industrious/imperial with a large requirement?  Or maybe a questline in the same tab as the healing axe, requiring a lot of different combs.

**Comment by richardhendricks** [comment]
Ghastly and smouldering bees

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/59492149-f4ab3e00-8e4d-11e9-8b54-b8ac3c86f807.png)
![image](https://user-images.githubusercontent.com/1214811/59492155-f83ec500-8e4d-11e9-85c4-f6e5b085a9b6.png)
![image](https://user-images.githubusercontent.com/1214811/59492163-fbd24c00-8e4d-11e9-93e9-213be5fad8a2.png)

**Comment by chochem** [comment]
If this is still the correct place on github for bee breeding quests, I would suggest adding 4 more: Manganese/Tungsten/Iridium/Naquadah

Then the quests go all the way to Naquadah combs which are needed for gendustry recipes like the Mutatron, which sounds like a nice end goal for the bee breeding quest tab.
