### ISSUE TITLE
Blooming Bee not working

### ISSUE THREAD

**Issue by shinkuri** [GTNewHorizons/GT-New-Horizons-Modpack#4618]
7.0, private server

This bee should bonemeal nearby saplings. However it doesn't show the usual "bee has some effect" swirly particles above the apiary, and it doesn't appear to bonemeal saplings at all. 
Also the only valid flower is a vanilla oak sapling. Ironically no forestry saplings work.

![image](https://user-images.githubusercontent.com/31353359/58699428-bb7ac480-839d-11e9-8340-7492a9600478.png)

**Comment by Ngar1** [comment]
would be covered by backporting fof fix at forestry 1.12 
https://github.com/ForestryMC/Binnie/commit/1f5fb237df83accfc571ac1c764f5d24d8c200f9

**Comment by Dream-Master** [comment]
Sure why not . If somone have more knowledge then me maybe we can backport a lot of stuff

**Comment by AiramProvoker** [comment]
Any updates regarding the backporting?
