### ISSUE TITLE
Remove universal cells from quest requirements/rewards

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4628]
Universal cells are notoriously buggy. Need to remove from any quest rewards or requirements.

**Comment by richardhendricks** [comment]
A lot of these are icons, need to check those as well

- [ ] reference to universal cells in 1792
- [ ] universal fluid cell for mutagen in 1656,
- [ ] 1657 dragon egg
- [ ] 1658 dragon egg
- [ ] 1659 dragon egg
- [ ] 1743 chlorobenzene
- [ ] 551 sulfuric heavy fuel
- [ ] 552 heavy fuel
- [ ] 555 hydrogen
- [ ] 616 mercury

(more)

**Comment by boubou19** [comment]
got a report saying it's still happening on quest N°1659 in 2.1.1.0 for molten enderium fluid cell. Dunno about the others

**Comment by Prometheus0000** [comment]
@D-Cysteine There's more things that don't go into normal cells if you want to look at it. There's more if you look up bacteria too.

**Comment by bombcar** [comment]
The quest entitled "Synthetic Rubber" has Universal Fluid Cells and bugged - empty ones counted for me - it's in HV off of Performing Chemical.

**Comment by D-Cysteine** [comment]
The quests still need to be updated, but this PR added cell support for the rest of the fluids:
 * https://github.com/GTNewHorizons/GT5-Unofficial/pull/698
