### ISSUE TITLE
Mirrored glass

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4645]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to craft mirrored glass. First i canned a bucket with liquid ender -> gt++ resonating ender bucket (that doesn't work in the recipe)
Second i tried with the clay bucket ->contains the correct liquid but the bucket needs to be an iron bucket...
![2019-06-04_09 05 55](https://user-images.githubusercontent.com/11991148/58858597-2717a700-86a8-11e9-895b-858cab7894f0.png)

![2019-06-04_09 07 05](https://user-images.githubusercontent.com/11991148/58858604-2d0d8800-86a8-11e9-8029-b79a575a6b7c.png)

**Comment by Anikilulala** [comment]
You can use tic table to fill the bucket.It works for me

**Comment by DietmarKracht** [comment]
It's a workaround but not the way it should be

**Comment by NoriSilverrage** [comment]
I ran into this as well. Frankly the recipe is crazy annoying and getting the ender buckets requires some annoying effort.

Each bucket is 4 pearls. I don't see anything that costs that much.. Maybe use 4 enderpearl lenes? Trade cost for processing difficulty? Or could make it output two and have it use 4x enderpearl blocks.

**Comment by DietmarKracht** [comment]
Or oredict the liquid ender buckets

**Comment by Scottishprog** [comment]
Second the ordicting of buckets. OR change the recipe to the easier type.

**Comment by NoriSilverrage** [comment]
I mean that'd help, but having to use unstackable buckets in the first place is really annoying. I'm using a lot of magic mirrors and said screw it. I voided all the ingredients and gave myself the mirrors because of how terrible that recipe is.

**Comment by Ethryan** [comment]
How about replacing the buckets with cells instead?
