### ISSUE TITLE
Arcane Assembler and Knowledge Inscriber issues

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4646]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to automate some recipes with the arnace assembler. Therefore i need to inscribe the recipe into a knowledge core. The problem is that soem recipes use damage value items like screwdriver or saw. The arcane assembler doesnt recognize these correctly and gets stuck if one requests multiple items. Even a single item request will result in a stuck.

The request: (notice that the screwdriver and saw are recognized correctly and the crafting network doesn't try to craft multiple of these)
![2019-06-04_11 41 03](https://user-images.githubusercontent.com/11991148/58868988-acf21d00-86bd-11e9-9014-29f3cdc632ee.png)

Here is got stuck cuz the screwdriver and saw don't reenter the network:
![2019-06-04_11 41 10](https://user-images.githubusercontent.com/11991148/58869002-b24f6780-86bd-11e9-8f02-eb06c77018a8.png)

**Comment by Houstonruss** [comment]
Suggestion to add assembler recipes or something similar to anything requiring tools
