### ISSUE TITLE
Void Spikes causing massive server lagg

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4654]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
I setup a small enderman farm in the end for end shards and used void spikes to kill the endermen. Void spikes get covered in blood after they killed the first enemy. so all my void spikes are covered in blood. Thats where the lagg begins. Also i am wearing infinity armor and get a damage animation when i walk over the void spikes. standing on them causes the server to kick everyone. Maybe an admin can investigate this issue @Namikon @Dream-Master 

This issue refers to #4584 because there is currently no other way of getting shards then using void spikes

**Comment by Dream-Master** [comment]
Which mods involved ?

**Comment by DietmarKracht** [comment]
Draconic evolution spawner, extra utilities cursed earth and ender collector, thaumic bases void spikes, avaritiaaddons compressed chest

**Comment by Dream-Master** [comment]
extra utilities is closed source the others are open source.
