### ISSUE TITLE
Essentia import bus

### ISSUE THREAD

**Issue by DietmarKracht** [GTNewHorizons/GT-New-Horizons-Modpack#4655]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
It seems like the essentia import bus isnt working as expected. This might be due to @bartimaeusnek code changings. The essentia doesnt get imported into the system. I experienced that sometimes the essentia is stored as a fluid inside the system. 
![2019-05-26_14 12 52](https://user-images.githubusercontent.com/11991148/58935760-61e41280-876e-11e9-869f-7b3ce9877a5e.png)

#
#### What happend instead? (Attach screenshots if needed)

![2019-06-05_08 44 26](https://user-images.githubusercontent.com/11991148/58935682-3c570900-876e-11e9-84df-3fcf8d89b3c2.png)

**Comment by bartimaeusnek** [comment]
I haven't touched the ThaumicEnergistics version we use.

**Comment by DietmarKracht** [comment]
replacing the construct is a workaround. the issue didnt happen to me again, yet

**Comment by DoomSquirter** [comment]
this is a very well known issue if you had checked TE's github.
