### ISSUE TITLE
Crossimentional item links

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/GT-New-Horizons-Modpack#4660]
#### Which modpack version are you using?
Eta live
#
#### If in multiplayer; On which server does this happen? 
Multiplayer
#
#### What did you try to do, and what did you expect to happen?
I trying to use item-linking system with ctrl+rightclick
#
#### What happend instead? (Attach screenshots if needed)
If i linked item from dim A and the other guy at dim A - he can see the link
If i linked item from dim B but other guy in dim A - he does not see the link

pls fix =D

![2019-06-05_22 25 44](https://user-images.githubusercontent.com/25028786/58984290-5ed63a00-87e1-11e9-8cf8-5c61b2ad2645.png)
![2019-06-05_22 26 12](https://user-images.githubusercontent.com/25028786/58984291-5f6ed080-87e1-11e9-88f3-94dac7cf9dde.png)

**Comment by boubou19** [comment]
If i remember correctly this functionality is provided by TravelersGear and should happen in every gtnh server and maybe on lan world

**Comment by repo-alt** [comment]
iirc this ability appeared in the pack after Witching Gadgets were added

**Comment by boubou19** [comment]
i just checked and it is from TravellersGear: 
https://github.com/BluSunrize/TravellersGear
