### ISSUE TITLE
Location chip craft circuit issues

### ISSUE THREAD

**Issue by DeForce** [GTNewHorizons/GT-New-Horizons-Modpack#4664]
#### Which modpack version are you using?
2.0.7.0

#
#### What did you try to do, and what did you expect to happen?
Try to craft Location chip with IV and EV circuits.
![image](https://user-images.githubusercontent.com/7394420/59150074-70f4ea00-8a26-11e9-8228-c9227326f781.png)
Takes 1 EV and 1 IV circuit.

![image](https://user-images.githubusercontent.com/7394420/59150078-85d17d80-8a26-11e9-83c0-9968aac59a84.png)
Takes 1 EV and 2 IV circuits

#
#### What do you suggest instead/what changes do you propose?
Fix all of the circuits recipes to be consistent

**Comment by bartimaeusnek** [comment]
please check with 7.3DEV should be fixed...
