### ISSUE TITLE
GT: Super buffer inconsistent wrench behaviour

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#4667]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
As part of an upgrade, I tried wrenching my super buffers to aim the output at a different machine
#
#### What happend instead? (Attach screenshots if needed)
After clicking the bottom segment with the wrench, the output was sent upwards as if the top square was clicked. The output face texture also appeared at the top side. WAILA however did report the block as facing down.
#
#### What do you suggest instead/what changes do you propose?
All GT machines should have the same wrenching behaviour to avoid surprises. The super buffer should have its orientation logic corrected.

I haven't checked the chest buffers or threaded buffers if they have the same issue.

**Comment by richardhendricks** [comment]
I think it's an issue with the texture, not the wrenching logic.

**Comment by combusterf** [comment]
If you hit your average machine on a side's center with a wrench that side becomes the output side.
If you hit the super buffer on a side's center with a wrench, the _opposite_ side becomes the output side.

The texture actually matches the actual output side, but since it's not necessarily visible where the machine is placed like in my case, you rely on the typical wrenching behaviour to point it the right way, and then spend the next 10 minutes wondering why it stopped working.

**Comment by boubou19** [comment]
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3166
