### ISSUE TITLE
bee mutations without foundations

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/GT-New-Horizons-Modpack#4668]
#### Which modpack version are you using?
2.0.7.0
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
I have gotten mutations for tin bees and zinc bees without having the proper blocks underneath. Nothing is really broken by those but might be an issue if this affects higher tier bees too.

**Comment by Hakameda** [comment]
Starts in 2.0.7.0 , I noticed it awhile back about getting  a lapis bee when using a redstone block though i didn't think to check the scope of that

**Comment by Dream-Master** [comment]
gt bees or gendustry bees ?

**Comment by sthegreat** [comment]
gt

**Comment by richardhendricks** [comment]
Unable to reproduce in 7.3dev. Output from apiaries over tin blocks on the left, over dirt blocks on the right.  Using mutagenic frames

![image](https://user-images.githubusercontent.com/1214811/59327018-f1794c00-8cad-11e9-9db8-bbe075cbfdd1.png)

![image](https://user-images.githubusercontent.com/1214811/59327030-f6d69680-8cad-11e9-98f0-e5abba5bec2c.png)

**Comment by richardhendricks** [comment]
Did 2 cycles, still no tin bees

**Comment by richardhendricks** [comment]
For Lapis, it looks like there are 3 separate Lapis bees.

Right Lapis bee is from GT, requires Lapis block, bred from Imperial and Resilient

Middle Lapis bee is from Gendustry, has no breeding

Left Lapis bee is from Extra Bees, requires No blocks, also breeds from Imperial and Resilient.

I guess we need to remove the duplicate bees from Extra bees that we have now in GT to fix.

**Comment by richardhendricks** [comment]
@Dream-Master We need Extra Bees compared against GT bees, remove duplicates.  Not sure for easy way to do that.

Ones I found we definitely have breedable Extra bees for 
- [ ] Lapis
- [ ] Diamond
- [ ] Ruby
- [ ] Emerald
- [ ] Aluminium
- [ ] Sapphire

**Comment by xtake** [comment]
I can confirm I also got metal bees without the right foundation.
Bee's I gotten without: Clay, Copper, Lead, Coal, Gold. Those are all the ones I needed didn't do any testing tbh.

**Comment by richardhendricks** [comment]
Yeah, it's possible this was before the old recipes were removed.

**Comment by richardhendricks** [comment]
Check on titanium bees too

**Comment by richardhendricks** [comment]
titanium shows only 1 breeding tree, should be ok.

**Comment by Ngar1** [comment]
Functionality of GT Bee combs are covered with crops. I see no reason for redundance because - on higher levels - crops are just energy (uumatter) to material. This remembers be at EMC production in old tekkit days.
