### ISSUE TITLE
missing hydrogen peroxide recipy

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#4682]
#### Which modpack version are you using?
2.0.7.4dev
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
the recipy using 2-ethlanthrahydroquinone to make hydrogen peroxide is missing
tis makes making hydrogen peroxide imposible
#
#### What do you suggest instead/what changes do you propose?
recipy should be added

**Comment by Bluebine** [comment]
this is a GT++ issue. please put this ticket on the GT++ github
https://github.com/alkcorp/GTplusplus/issues
