### ISSUE TITLE
Jade Moon Dial too hard to get

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4684]
Right now Small Jade Ores in the TF are set to 5-250, which is obviously crazy for the TF.  Recommend changing to 5-40.

Needing 4 Jade in the recipe for the Jade moon dial also makes it really hard.  Recommend changing to 1 jade and 2 stainless.

**Comment by richardhendricks** [comment]
eh, changing the range to 5-40 might be enough to fix jade.  Need to add Autoclave and Implosion Compressor recipes though to turn dusts back into gemstones.

**Comment by ScriptedPiky** [comment]
Can that change also apply to the other gems in the Twilight Forest? Most of them are nearly impossible to obtain (looking at you, Amythsts) due to the huge height variable

**Comment by richardhendricks** [comment]
Pretty much all GT small gemstone ores are broke. 5-250, amount 2?

![image](https://user-images.githubusercontent.com/1214811/60051805-70508a80-9699-11e9-80c1-3ccff2b6673b.png)

**Comment by richardhendricks** [comment]
Change all to 5-40

**Comment by Prometheus0000** [comment]
As of 2.0.8.5dev, the TF gem small ores are all 5-35 with amount 2, except for Jade, which is 5-250 amount 8.

**Comment by Dream-Master** [comment]
Will check
