### ISSUE TITLE
UHV wafer is way cheaper compared to the UV one

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#4688]
#### Which modpack version are you using?
2.0.7.4dev
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
recipy wafer for UV energy hatch
![afbeelding](https://user-images.githubusercontent.com/42187820/59534811-a3538b00-8eef-11e9-8df7-eb21fc3afab9.png)

recipy wafer for UHV energy hatch
![afbeelding](https://user-images.githubusercontent.com/42187820/59534861-be25ff80-8eef-11e9-8ef3-f5076512f0c0.png)
#
#### What do you suggest instead/what changes do you propose?
make the UV one cheaper or the UHV on more expansif

**Comment by 0lafe** [comment]
To follow the trend of crafting it should be the UV one used in the UHV recipe right?

**Comment by DualBallers** [comment]
This is still the case in 2.0.9.0 and it also recently surprised me that it is waaay faster (at UV tier) crafting UHV wafers than UV wafers due to the indium cost.
It would make more sense if QPIC are made by e.g. Americium wafer + 64 Naq alloy dust + x fluid Neutronium.

**Comment by 0lafe** [comment]
Isn't my previous comment still applicable? I thought the PICs were recursive?

**Comment by DualBallers** [comment]
Europium doped wafer -> NPIC -> PPIC
Americium doped wafer -> QPIC
So I guess it follows that the IC wafer tier can be extended from QPIC at a later point.
