### ISSUE TITLE
Using Prospectors scanner with too large of a radius disconnects the player

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/GT-New-Horizons-Modpack#4689]
#### Which modpack version are you using?
2.0.7.0

#### If in multiplayer; On which server does this happen? 
My own server

#### What did you try to do, and what did you expect to happen?
I used a prospectors scanner (UHV Trinium 23x23 chunks) in the Deep Dark dimension, and expected to get prospecting results

#### What happened instead? (Attach screenshots if needed)
I got disconnected, every time I try this.

#### What do you suggest instead/what changes do you propose?
Compress the results or send the results in multiple packets so it doesn't go over the max payload for a single packet. The Deep Dark is jam-packed with ores, so this is likely the reason, because the scanner works fine with 23x23 radius in every other dimension.

Using a scanner with a smaller chunk radius (13x13 works, unless i set it to show small ores too)

Here's a [log from the event](https://pastebin.com/cD1q9Ay2), IMHO the results contain too much data for the network dispatcher to handle, and it forcibly disconnects the player.

**Comment by Dream-Master** [comment]
Server show up 6 chunck radius or 8 maybe that is the problem. Use a smaller scanner.

**Comment by richardhendricks** [comment]
Need to update code to set maximum scan size, maybe 11x11 chunks.  Or limit max tier of scanner.

**Comment by Dream-Master** [comment]
No wait if you play sp i want big scanner. Not limit it or maybe with a config file @richardhendricks

**Comment by boubou19** [comment]
it happened to me with an uv prospector scanner made of awakened draconium (21 x 21 chunks) in deepdark on delta. It was set on "Ore (with small), Any Rock Block" mode. Setting it back on "Ore, Any Rock Block" mode fixed the issue.
