### ISSUE TITLE
Infusion Altar Stabilizers

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#4694]
2.0.7.0

So I tried making Ancient Cobblestone Slab as Infusion Altar Stabilizer. Many people in chat told me that it doesn't work and they've checked it before.

I'm unable to check this, but seems like they are right. Could we fix this or at least remove from the description that this is a stabilizer?

**Comment by NoriSilverrage** [comment]
Agreed. I made a bunch of, I think it was thaumic bases, blocks that claimed infusion stabilization, but they didn't do anything.

**Comment by chochem** [comment]
to add to that. there are also some other slabs with the same problem: ancient bricks, ancient mossy cobblestone, gold, iron, ... Not tested them, but I guess its the same

**Comment by mitchej123** [comment]
I'm fairly certain this is working as intended.  -- What description are they included in? Thauminomicon? Quest?

**Comment by chochem** [comment]
I agree it is working as intended but the tooltip is wrong. This line identifies all the infusion stabilizers:

![2020-02-16_16 31 43](https://user-images.githubusercontent.com/40274384/74608588-48a3ac00-50da-11ea-981b-e4593be780d8.png)

**Comment by Prometheus0000** [comment]
Unless someone feels like changing the tooltips on all these (with ASM I guess?) this is done.

**Comment by bombcar** [comment]
These are wrong and we can probably fix them and we have the source. Here we go!

**Comment by bombcar** [comment]
Bases just inherits from thaumcraft "old" blocks so this is done somewhere else.

Perhaps intentionally?

**Comment by bombcar** [comment]
<img width="394" alt="image" src="https://user-images.githubusercontent.com/533931/147846597-e48818c7-da2b-4b42-a458-2825645aea86.png">

also doesn't look much like a slab ....

**Comment by bombcar** [comment]
This is added by Bases somehow need to find where
