### ISSUE TITLE
Fluid Input Hatch Recipe Suggestion 

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#4702]
Just recently in 2.0.7.? - 7.5, the hatches were hot-fixed to be less tedious & frustrating to create. While they originally made sense on paper with their materials and components used, they were incredibly frustrating and nearly pointless to obtain, as a ULV or even LV fluid I/O hatch & I/O bus could accomplish the task of an HV or higher hatch/bus with extremely simple costs. The recipes were not enjoyable to craft as stated by several members within the community.

Now that they are fixed, I've come up with a proposed ideal concept & solution to a difficult, yet enjoyable experience. After listening to a few members in the GTNH Discord server and their overall positivity towards this concept & proposal, I present to you this logical and fairly balanced thread.

-Hatches use a pump or conveyor 2 tiers below the current tier. The energy tier is 1 tier below the current tier. They will also use 1 fluid pipe (3 ingots worth) based on the current tier; I.E. Stainless Steel fluid pipe for an HV fluid hatch.
-Hatches will use a large fluid cell, however, based on how large that fluid cell is, it will also increase the capacity of the fluid input/output to meet the exact specific amount that the fluid cell holds within that fluid hatch. In this case, an HV fluid hatch current has 48 buckets worth of fluid storage. The large stainless steel fluid cell holds 64 buckets. Now the fluid hatch holds 64 buckets to meet that requirement with this change
-Reduce all the hatch recipes down to 10 seconds instead of 24 seconds

Now that we have this concept in mind, let's put it to use.
Note: I do not wish to touch the general mechanics to force higher tier crafting, merely this is a recipe change that I want to make more enjoyable based on what the **community** thinks and believes in. This change will not happen immediately until a stable & desired vision occurs that most can agree on.

ULV Fluid I/O Hatch:
-1 ULV Machine Hull, 1 Copper Fluid Pipe, 1 Empty Cell
-144L Refined Glue or 72L Polyethylene or 36L Polytetrafluorethylene or 4L PBI
-ULV EU/t / Voltage Level

LV Fluid I/O Hatch:
-1 LV Machine Hull, 1 Bronze Fluid Pipe, 1 BC Factory Tank 
-720L Refined Glue or 144L Polyethylene or 72L Polytetrafluorethylene or 9L PBI
-ULV EU/t / Voltage Level

MV Fluid I/O Hatch:
-1 MV Machine Hull, 1 Steel Fluid Pipe, 1 Large Aluminium Fluid Cell
-288L Polyethylene or 144L Polytetrafluorethylene or 18L PBI
-LV EU/t / Voltage Level

HV Fluid I/O Hatch:
-1 HV Machine Hull, 1 Stainless Steel Fluid Pipe, 1 Large Stainless Steel Fluid Cell, 1 LV Pump
-432L Polyethylene or 288L Polytetrafluorethylene or 36L PBI
-MV EU/t / Voltage Level
-Increase the fluid capacity of hatch size from 56 buckets to 64 buckets

EV Fluid I/O Hatch:
-1 EV Machine Hull, 1 Titanium Fluid Pipe, 1 Large Titanium Fluid Cell, 1 MV Pump
-576L Polytetrafluorethylene or 72L PBI
-HV EU/t / Voltage Level
-Increase the fluid capacity of hatch size from 88 buckets to 128 buckets

IV Fluid I/O Hatch:
-1 IV Machine Hull, 1 Tungsten Steel Fluid Pipe, 1 Large Tungsten Steel Fluid Cell, 1 HV Pump
-1152L Polytetrafluorethylene or 144L PBI
-EV EU/t / Voltage Level
-Increase the fluid capacity of hatch size from 128 buckets to 512 buckets

LuV Fluid I/O Hatch:
-1 LuV Machine Hull, 1 Niobium-Titanium Fluid Pipe, 1 Large Chrome Fluid Cell, 1 EV Pump
-2304L Polytetrafluorethylene or 288L PBI
-IV EU/t / Voltage Level
-Increase the fluid capacity of hatch size from 176 buckets to 2048 buckets

ZPM Fluid I/O Hatch:
-1 ZPM Machine Hull, 1 Naquadah Fluid Pipe, 1 Large Iridium Fluid Cell, 1 IV Pump
-576L PBI
-LuV EU/t / Voltage Level
-Increase the fluid capacity of hatch size from 232 buckets to 8192 buckets

UV Fluid I/O Hatch:
-1 UV Machine Hull, 1 Neutronium Fluid Pipe, 1 Large Osmium Fluid Cell, 1 LuV Pump
-1152L PBI
-ZPM EU/t / Voltage Level
-Increase the fluid capacity of hatch size from 296 buckets to 32768 buckets

UHV Fluid I/O Hatch:
-1 UHV Machine Hull, 1 Awakened Draconium Fluid Pipe, 1 Large Neutronium Fluid Cell, 1 ZPM Pump
-2304L PBI
-UV EU/t / Voltage Level
-Increase the fluid capacity of hatch size from 368 buckets to 131072 buckets

Are these within fair ranges for a player? Is something too difficult or absurd in this change? Thoughts? Would love to hear your thoughts and ideas if you have them. Please note that it **SHOULD NOT** be any harder or difficult than the currently proposed recipes

**Comment by observeroftime02** [comment]
I like the bigger capacity hatches, and the part where it takes an actual fluid cell and pipes from the tier to craft it. It's well thought out. Better than the current recipe where you need fluid tanks, and then the size of the hatch doesn't even match the capacity. At least this proposal makes sense.

**Comment by AlexBucket** [comment]
I support these changes. @Dream-Master

**Comment by Dream-Master** [comment]
will do a deeper look at it when i finished Quest progress on BQ3 Mod
