### ISSUE TITLE
Nerf duplicate Lutetium and Cosmic neutronium nugget

### ISSUE THREAD

**Issue by bi9lamer** [GTNewHorizons/GT-New-Horizons-Modpack#4706]
#### Which modpack version are you using?
Version 2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Multiply Lutetium and Cosmic neutronium nugget using Metallurgic Perfection: Transmutation (Thaumcraft addon "Witching Gadgets")
#
#### What happened instead? (Attach screenshots if needed)
Easy way to get the resources that must be obtained through complicated manipulation. 

![Cosmic neutronium nugget recipe](https://user-images.githubusercontent.com/51369732/59637516-a4d6ba80-915e-11e9-8bab-c76f049ccb6b.png)
![Lutetium  nugget recipe](https://user-images.githubusercontent.com/51369732/59637517-a4d6ba80-915e-11e9-8baa-f0e16540a16e.png)

Nebrisum and Radio aspects easy to farm from uranium/plutonium (Radio) and platinum/mithril (Nebrisum).
#
#### What do you suggest instead/what changes do you propose?
Delete Lutetium and Cosmic neutronium nugget recipes from Thaumcraft addon "Witching Gadgets"

**Comment by boubou19** [comment]
cosmic neutronium nugget is not possible to get iirc

**Comment by Anarack** [comment]
You can, just take a saw to a ingot.

**Comment by bi9lamer** [comment]
@boubou19 
![Proof](https://user-images.githubusercontent.com/51369732/59641043-bf159600-9168-11e9-9888-b023f80a8db3.png)
