### ISSUE TITLE
Meteoric Iron and Compressed Meteoric Steel

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#4712]
It is very easy to make Meteoric Steel Ingots and think they are used in the Compressed Meteoric Steel instead of the Meteoric Iron ingots.

Right now the Meteoric Steel is only used for tinkers and tools.

Intended or something that needs to change?

GTNH: 2.0.7.5
Kudos to Kharax82 for pointing this out.

**Comment by Dream-Master** [comment]
@Ethryan so you suggest change the duty heavy plates t2 to meteoric steel plates ?

**Comment by Ethryan** [comment]
Either that or change the name to compressed meteoric iron.
