### ISSUE TITLE
block of certus quartz missing recipe

### ISSUE THREAD

**Issue by skynsun** [GTNewHorizons/GT-New-Horizons-Modpack#4728]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
in a private server
#
#### What did you try to do, and what did you expect to happen?
craft block of certus (gregtech)
#
#### What happened instead? (Attach screenshots if needed)
there is no recipe
#
#### What do you suggest instead/what changes do you propose?
the block is needed to certus bee

**Comment by yukieiji** [comment]
This problem prevents us from advancing the bees...
It needs to be made with Chisel etc.
