### ISSUE TITLE
Advanced Muffler not working

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/GT-New-Horizons-Modpack#4732]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Use EV Advanced Muffler
#
#### What happened instead? (Attach screenshots if needed)
Didn't work anymore since last update. Machine is stucked.
I see we need an air filter now for that purpose (T1 for EV) but when i insert the filter T1, it dissapear and machine still not working.

Another statement, machine can work with advanced muffler without air filter. After some operation, machine will stuck.

(Or maybe i am dumb and missing someting)
#
#### What do you suggest instead/what changes do you propose?
Fix ^^

**Comment by richardhendricks** [comment]
Machines will buffer a little polllution and then stop when they can't get rid of it with a muffler, that's probably why you see it behaving the way you do. As far as the advanced muffler not working, dunno.

File a ticket at Alk's repo I guess, but she'll be a while since she needs a new laptop.

**Comment by DV666** [comment]
Okay, i will open a ticket on GT++ and share the ticket here.

Thanks @richardhendricks

**Comment by DV666** [comment]
Ticket open : https://github.com/alkcorp/GTplusplus/issues/496

**Comment by draknyte1** [comment]
Fixed in Dev.
