### ISSUE TITLE
Miner filter thing

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#4740]
#### Which modpack version are you using?
2.0.7.newest
#

#### What do you suggest instead/what changes do you propose?

Add a filtering mechanic to the multi miners to avoid mining useless ores for you. Set them in an in bus, doing so removes the desired ore/small ore from the blocks the miner can mine. With larger areas and self loading, you'll end up with more useless ores.

**Comment by DoomSquirter** [comment]
as much as this is a fine idea and would make it similar to one of my favorite blocks, the mek digitial miner, it would completely change the idea of the tool from a sledge hammer to a precision hammer.  Using the miners (all of them) all share the drawback that you're getting the whole thing and you have to deal with that.  being able to bypass that and filter or blacklist stuff you don't want just seems to me it'd be .....  ugh... I can't believe I'm saying this....  cheaty.....

is this what being an 0lafe feels like?  I don't feel good mister stark.........

**Comment by mitchej123** [comment]
alternative is to just auto output and void stuff you don't want.  Less block updates... I'm in favor of a filter!

**Comment by 0lafe** [comment]
It's less about handling outputs as that's very easy, and more about maximizing speed through skipping unnecessary mining. It's achieveable without a filter to essentially do this, however it looses some viability when the drill area is larger than a single vein.

**Comment by mitchej123** [comment]
Uh, the cost of comparing a block and skipping it, vs mining it, is approximately the same.  Except mining it is going to incur a block update and hit tps more

**Comment by repo-alt** [comment]
When adding chunkloading support I also added ability to turn it off exactly to support vein "filtering", where you put an anchor on top of the veins you want to mine.
