### ISSUE TITLE
Polycaprolactam quests

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4742]
Need quest for finding electrotine ore

Quest for turning electrotine into electrum

Quest for creating the polycaprolactam bars from saltpeter and naphtha, and turning it into string with the wiremill

**Comment by Prometheus0000** [comment]
Isn't string from polycaprolactam bars completely worthless compared to cotton or string crops? Maybe they could be made into a new type of string that's needed for something in the future instead?
