### ISSUE TITLE
Hand Pump Trade Tokens are not craftable

### ISSUE THREAD

**Issue by SampsaxD** [GTNewHorizons/GT-New-Horizons-Modpack#4744]
Trying to craft any of the hand pump tokens will always create a fluid regulator of the tier of the pump.

Suggest just removing the pump and circuits from the recipe and replacing them with a fluid regulator instead.

**Comment by draknyte1** [comment]
Please report it here.
https://github.com/alkcorp/GTplusplus/issues/new
