### ISSUE TITLE
2075 Thaumic Base void spikes secondary recept to easy

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/GT-New-Horizons-Modpack#4745]
#### What did you try to do, and what did you expect to happen?
![](https://i.imgur.com/px7IIjD.png)
 this recept use in nei (invisible in thaumonomicon)

![](https://i.imgur.com/OZAokcR.png)
recept in thaumonomicon

#### What do you suggest instead/what changes do you propose?
remove shaped recept

**Comment by Dream-Master** [comment]
never nerfed o guess
