### ISSUE TITLE
digital themometer can only use 1 type of mv circuit

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#4746]
#### Which modpack version are you using?
2.0.7.4
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
make digital thermometer
#
#### What happened instead? (Attach screenshots if needed)
it would not craft
![afbeelding](https://user-images.githubusercontent.com/42187820/59952673-58042400-947d-11e9-95f1-bc8b038f22fe.png)
it wil only work with the low tier mv circuit
![afbeelding](https://user-images.githubusercontent.com/42187820/59952717-8255e180-947d-11e9-8a9e-a9ffb572b504.png)
#
#### What do you suggest instead/what changes do you propose?
it shoud be crafteble using al mv circuits

**Comment by thecodingchicken** [comment]
This does not appear to be fixed in version 2.3.0-rc2.  Unaware if it has been fixed in newer pre-releases, but I would presume not
