### ISSUE TITLE
tritium mechanics

### ISSUE THREAD

**Issue by willis936** [GTNewHorizons/GT-New-Horizons-Modpack#4747]
I don't think tritium should come from centrifuging deuterium.  ic2 has a means of generating tritium in fission reactors:

https://wiki.industrial-craft.net/index.php?title=Fuel_Rod_(Tritium)

https://en.wikipedia.org/wiki/Tritium#Lithium

The fusion reactor could also have a mechanic where if lithium is present in an input bus it converts it to tritium (and maybe helium) during a reaction.  So fission would be necessary to boot strap the tritium supply (like in real life).

**Comment by Anarack** [comment]
Does the tritium breeding correctly work with our ic2? In the past it just instantly converted.

**Comment by willis936** [comment]
I’m not sure.  I haven’t played around with it yet.  If that doesn’t work it could be added in through the same way thorium cells are added, though that is a lot more work.

I also propose that the platonic ideal of infinite energy still be in the game but pushed to a later tier.  The stellar fusion takes a much better confinement than D+T but only requires hydrogen.  So I propose a very high energy requirement (maybe something like 1A LuV or ZPM?  idk what the state of late game balance is like) but the only reaction input is 2 hydrogen and the output is 1 helium plasma.  Seeing as helium plasma is a relatively low power output fuel I propose a few different solutions:
 * the output ratio could be increased to something like 10 helium per 2 hydrogen
 * a new fluid of very hot helium plasma is added as a high energy fluid (my favorite)

https://en.wikipedia.org/wiki/Stellar_nucleosynthesis#Hydrogen_fusion

**Comment by 0lafe** [comment]
>have a high energy kickstart requirement but have the ongoing energy consumption be very low, implying plasma ignition (a cool concept but not exactly in line with current fusion gameplay balance)

But that's how fusion works now?...

>the output ratio could be increased to something like 10 helium per 2 hydrogen

Atm it's 125L He plasma per 125L D 125L T, which if processed from H2 is 2500L to make 1/20 of that in fuel. A 5:1 H2 to He plasma with more energy density seems like a poor idea, especially if it's also entirely removing the D/T processing chain. It makes fusion like a larger gas turbine lmao. 

>I also propose that infinite fusion energy still be in the game but pushed to a later tier

Much of fusion recipes are infinite one way or another, He is just the simplier one in some ways. It could do with a little change somehow, as it stays semi dominant fuel source across all of fusion. Maybe 3/4 overclocks? 

>So I propose a very high energy requirement (maybe something like 1A LuV or ZPM? idk what the state of late game balance is like)

Mostly fusion running costs are kind of low, but the energy cost comes more from the fuel production. I'd suggest balancing the output more around the fuel value of the output. Current mk1 He output is .64Meu/t, which is around 1M with eff bonuses, scaling 2x/tier, stopping at 8M in the MK4. The running costs are primarily just the creation of the inputs, as running the reactor itself is kind of cheap. You could switch that cost to the reactor itself I guess, but uh 1ZPM for even mk1 He production seems a little low for eliminating infrastructure cost. If you want it higher tiered, then you'd really want a much higher running cost, but the whole idea of making fusion setup easier would need to be different imo. Would need to loose like 1/2 energy to running costs or something like that.

**Comment by MineAnPlay** [comment]
Making Tritium from Lithium would be interesting but unless it's refined I would rather want it as an alternative. Also about fusion, like 0lafe said it's already roughly how you suggested. I too disagree that the output/ratio of Helium Plasma be changed. Right now Helium Plasma is not only the easiest to setup but because of its low starting EU (compared to other fusion plasma recipes) it allows it to be overclocked multiple times, so it can potentially be the most efficient and also produce the most EU/t worth of plasma compared to the other plasmas.

**Comment by Anarack** [comment]
You could also just drill He-3 on the moon and skip tritium completely.

**Comment by willis936** [comment]
> But that's how fusion works now?...

I mean requiring the startup to be high enough that it requires something 16 UHV+ casings to start the reaction.

> A 5:1 H2 to He plasma with more energy density seems like a poor idea, especially if it's also entirely removing the D/T processing chain

I agree changing the ratio isn't a good idea, but it was one of three suggestions (I was not suggesting implementing all three).  I think implementing the second suggestion (new fluid with the same 2:1 input/output ratio) is the best choice.  Also this wouldn't be removing the D processing chain, just the recipe to convert D to T without some sort of neutron injection.  Fuel production easier for the higher tier stellar fusion recipe since it would only require hydrogen.


What I think the stellar fusion recipe should look like:

2 Hydrogen in
1 High Energy Helium Plasma out
.5MEU/t running cost
200 MEU kickstart cost

Equivalent output of 2 MEU/t

The actual EU numbers/tiering I don't feel strongly about.  They can be placed wherever makes sense for the sake of balance.  I'm sure there are things about these suggested numbers that don't perfectly add up.  I think making it a relatively early stop after reaching D+T fusion is nice since it would afford the player not having to burn lithium.

**Comment by Anarack** [comment]
You are aware that none of those numbers even remotely follow fusion hatch scaling right?
Max power in a t4 reactor is the following. (Which I'm honestly not sure anyway has built yet)
Ignoring the strange eu/t to kick start cost.

Numbers for the t4 reactor iirr
262,144 EU/t input 16,384 eu/t a hatch
1,280 MEU or 80MEU a hatch

**Comment by willis936** [comment]
> You are aware that none of those numbers even remotely follow fusion hatch scaling right?

I am.  Hence:

> I'm sure there are things about these suggested numbers that don't perfectly add up.

I am making a mechanic suggestion, not a balance one.

**Comment by 0lafe** [comment]
The idea is to circumvent D/T production through lossier production. Imo it's just not that needed, and I'd rather see another fusion option have some more viability, at least comparatively

**Comment by willis936** [comment]
The idea is to not have a radioactive material treated as an inert material that can be found in nature.

**Comment by 0lafe** [comment]
Not talking about tritium, I mean hydrogen input He plasma

**Comment by willis936** [comment]
The largest reason to add a hydrogen recipe is to allow for a renewable fusion recipe.  If tritium requires lithium then there wouldn't be a truly infinite fusion energy option.

**Comment by 0lafe** [comment]
Lithium is renewable though. There's also other current infinite recipes

**Comment by botn365** [comment]
lithium is prety hard to get renewble and even hard to get in large quateties when using ore drills. 
tis wil only reduce the reason to use tritium/deutrium when al you have to do to get helium-3 is a pump on the moon

**Comment by Anarack** [comment]
Not so much, you get a ton out of tungstate, which is fairly renewable from several pure tech sources.

**Comment by 0lafe** [comment]
Depending on how much Li is used, and how much tritium is made, there's also even just uu

**Comment by richardhendricks** [comment]
Clay bees -> clay dust -> lithium
