### ISSUE TITLE
plasma temperature

### ISSUE THREAD

**Issue by willis936** [GTNewHorizons/GT-New-Horizons-Modpack#4749]
I noticed all plasma temperatures are 10000K yet higher tier pipes have maximum temperatures well beyond this.  I think it would make sense to gate the transport of higher tier plasmas to higher tier pipes by increasing the temperature of higher tier plasmas.

**Comment by 0lafe** [comment]
I mean, maybe? But for the most part you wouldn't really use GT pipes at that point
