### ISSUE TITLE
Pam's food de-syncing

### ISSUE THREAD

**Issue by Teteros** [GTNewHorizons/GT-New-Horizons-Modpack#475]
Small pam's food cannot be eaten as it appears to de-synchronize with client-to-server.
Reports of either the food not being able to be eaten entirely to food taking too long to consume were given.
Due to this, other foods (such as natura) have to be eaten first to survive in the early days of the pack.

Please post your findings below, maybe we'll find out what's causing this

**Comment by deeplyarnab** [comment]
I suspect ping ~100ms or more can be one of the cause, as mostly i do get it, ,but AFAIK @WarlordWossman also has the problem.

**Comment by Methes** [comment]
Wild guess - maybe setting modifyFoodEatingSpeed=true to false in HungerOverhaul could solve this.

**Comment by deeplyarnab** [comment]
You may be on the right track @Methes as they make the large foods take a very long time to eat (try edzels marshmallows from de). It can basically be doing the opposite for the food with less value, but other concern is that vanilla food of the same sort is not affected by it.

**Comment by Dream-Master** [comment]
Any news here. Can we do there some things or should this be closed?

**Comment by deeplyarnab** [comment]
Maybe, we should check if the issue still occurs in single player or not. If only multiplayer then we have to check if its only for the people with high ping. If it does not occur in single player and only on multiplayer with high ping then nothing can be done.

**Comment by UltraPeeks** [comment]
For anyone experiencing this: you should look at the sky or at distant objects while eating as a workaround for now.

**Comment by Technus** [comment]
May it be low event priority?

**Comment by Dream-Master** [comment]
Maybe.

**Comment by Prometheus0000** [comment]
If anyone feels like fixing this, we have a private fork now, so you can try.

**Comment by TimeConqueror** [comment]
After some testing I can tell, that this bug only occurs on Thermos server, not on pure forge.

**Comment by NoX-programer** [comment]
Forge too.

**Comment by Sovereignty89** [comment]
I seem to have a somewhat similar issue as #7410, however I have it in single player. Version is 2.1.0.7a. As stated by someone else in the previous issue, eating from a lunchbox seems to work. A short [video](https://youtu.be/q2Z0KUNczX8) depicting the issue. I have eaten a fair bit and it has only happened with Pam's cheese as of yet.
