### ISSUE TITLE
[Suggestion]Add Rocket Parts recycle recipes

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#4752]
#### Which modpack version are you using?
2.0.6.8 and 2.0.7.5

#
#### What do you suggest instead/what changes do you propose?
We consume a lot of material and make Rocket parts such as Heavy Duty Plate and Compressed plate to making Rocket.But There is no recycling recipe for Rocket parts, so extra Rocket parts are wasted.

I suggest that Rocket Parts recycling recipe should be added (In version 2.0.7.5, Compressed Plate can be recycled, but Dual Compressed Plate can't be recycled)

**Comment by Prometheus0000** [comment]
You can already recycle rockets. If you mean the parts of the rocket, don't make extras?

**Comment by yukieiji** [comment]
@Prometheus0000 The current version of the rocket parts that can be recycled(such as Compressed Copper Plate) and parts that cannot be recycled(such as Compressed Black Plutonium Plate). So shouldn't they be able to be recycled uniformly?
If you make extra, you'll be wasting materials and
