### ISSUE TITLE
Recipe of gregtech semi-fluid generators poofed in 2.0.7.5

### ISSUE THREAD

**Issue by Smeany** [GTNewHorizons/GT-New-Horizons-Modpack#4755]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
eta server official gtnh
#
#### What did you try to do, and what did you expect to happen?
crafting the gretech semi-fluid generators
#
#### What happened instead? (Attach screenshots if needed)
theres no recipy for them anymore
in addition to that, the machine when dismantled with a wrench disappeared, didnt drop as an item
#
#### What do you suggest instead/what changes do you propose?
the recipies of the semi-fluids were nearly the same as the combustion generators,
at the place where the cable is, was the ic2 semifluid generator block
(so beneath the hull) i made an example picture:
![semifluid2](https://user-images.githubusercontent.com/23564498/59968334-7e3aca00-9538-11e9-8b7d-0e0aaecacaab.png)

id of the ic2 semifluid generator is 195:7

**Comment by draknyte1** [comment]
Please report it here.
https://github.com/alkcorp/GTplusplus/issues/new

**Comment by draknyte1** [comment]
Fixed in Dev.
