### ISSUE TITLE
Extra Bees: incubator/handpump dupe

### ISSUE THREAD

**Issue by parttimealcoholic** [GTNewHorizons/GT-New-Horizons-Modpack#4762]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Own server 
#
#### What did you try to do, and what did you expect to happen?
Tried pumping a liquid out of an incubator from extra bees/genetics by shift-rightclicking on it with a GT++ handpump.
#
#### What happened instead? (Attach screenshots if needed)
Fluid did not get removed from the incubator but it was still added to the handpump. Works with every fluid which is accepted by the incubator. (nearly anything, including molten metals etc.)
#

**Comment by richardhendricks** [comment]
Please also file ticket at GT++ github.

https://github.com/alkcorp/GTplusplus/issues

**Comment by parttimealcoholic** [comment]
Done. [https://github.com/alkcorp/GTplusplus/issues/498](url)

**Comment by Prometheus0000** [comment]
This was listed as fixed recently, I'm not sure which version though, is QF4 using a GT++ jar more recent than Apr 11?

**Comment by draknyte1** [comment]
Yes it is. .68 was built the same day as the last RC.
