### ISSUE TITLE
buff styreen butadien rubber

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#4773]
#### Which modpack version are you using?
2.0.7.5
#
#### What do you suggest instead/what changes do you propose?
styreen butadien rubber is a lot more work to make the silicone rubber the only ting that makes it better is that it does not use chlorine.
so it should be at least equal to silicone rubber.
only neets 1/2 to make ad rubber to cabels instead of 3/4
it should be able to ad rubber to iv cables without ading the vinlychloreide pulp and be able to use the raw styreen butatien pulp instead of the vinlychloride
shoud be able to be used in the smd capasitor recipy of 1 styreen budatien foil + 1 aluminium foil + 72L PE =8 smd capasitors
tis way both rubbers are equal with both having cons and pros instead of silicone rubber being superior

**Comment by Dream-Master** [comment]
@botn365 exact recipe suggestion please what i need to change

**Comment by richardhendricks** [comment]
I thought SBR was already superior to Silicone Rubber?  Doesn't it go to higher tiers?

**Comment by botn365** [comment]
for ev and below cables change
1x/2x wire from 108L per cable to 72L per cable
4x from 216L to 144L
8x from 324L to 216L
12x from 432L to 288L
16x from 540L to 360L

for IV+ cables add recipys
1x/2x wire 1 foil + 72L
4x 2 foil + 144L
8x 3 foil + 216L
12x 4 foil + 288L
16x 5 foil + 360L

for the recipy wire + 36L styreen/silicon rubber + smal pile of polyvinly chloride/polydimethysiloxane
make smal pile of styreen butatien rubber also a option instead of polyvinly chloride/polydimethysiloxane

1 styreen butatien foil + 1 aluminium foil + 72L polyethylene = 8 smd capasitors

you can use silicone rubber for al the cables

**Comment by 0lafe** [comment]
Not really higher tiers moron, they're essentially the "same thing". From what I can tell they're meant to be used interchangeably, and as rubber replacements. I wouldn't say SB is worse than silicone though, it seems to just use more oil based products. Silicone using methane, chlorine, and non oiley stuff, with SB being benzene/ethylene/butandiene which are all distill options. More usages for SB where silicone is sounds good, generally using *SyntheticRubberAny seems like the move. Idk if I'd reduce amounts of SB in stuff though, I've found both silicone and SB to be plentiful enough in production to satisfy all your cabling needs.
