### ISSUE TITLE
Add Neon and maybe Germanium if it doesn't exist already

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4776]
Add Ne and Ge so it can be used for recipes.

liquid Ne for coolant sourcing

Ge for high end nanowires/semiconductors/fiber optics/etc

**Comment by botn365** [comment]
germanium can be gotten fron sphalerite

**Comment by Dream-Master** [comment]
guess its from gt++. Need to check

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/60126306-fea63880-978d-11e9-88ba-6bbae633bd04.png)
@botn365 explain me how to get germanium out of sphalerite ?

**Comment by Dream-Master** [comment]
@botn365 nevermind found it
![image](https://user-images.githubusercontent.com/2970688/60126662-c4896680-978e-11e9-8b74-3fb4d913b962.png)

**Comment by botn365** [comment]
![afbeelding](https://user-images.githubusercontent.com/42187820/60126665-c6532a00-978e-11e9-8e41-148a2a31f2c3.png)

**Comment by Dream-Master** [comment]
haha first :P @botn365

**Comment by DietmarKracht** [comment]
There is also a gt++ ore that contains germanium if you centrifuge it
