### ISSUE TITLE
Vanadium from heavy oil

### ISSUE THREAD

**Issue by EmeraldsEmerald** [GTNewHorizons/GT-New-Horizons-Modpack#4781]
I think that a way to renewably produce vanadium from Heavy Oil would be a nice option for vanadium production. Perhaps Centrifuge Heavy Oil into Vanadium and Light Oil? Since Vanadium itself is actually found in oil IRL this even has an actual basis

**Comment by 0lafe** [comment]
Could it be the item you get from distillation in towers?

**Comment by richardhendricks** [comment]
That could work

**Comment by EmeraldsEmerald** [comment]
yeah distillation could totally work too
