### ISSUE TITLE
Suggestion: Changes to volumetric flasks to hold more liquid

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/GT-New-Horizons-Modpack#4783]
It would be great if the volumetric flasks could hold more than 1000 mb of liquid. Perhaps add some bigger versions of it. The Idea of it is awesome, but right now, the size of it limits the possibility.

They make autocrafting with liquids a breeze, but right now a recipe is limited by the small amount they can each hold. 

For example, to craft an LV energy buffer. The recipe has six inputs and requires 4608 mb of liquid. One would need to add 5 volumetric flasks to it, which needlessly complicates the crafting. 

I have done some tests with volumes > 1000 mb and haven't noticed any ill effects, but perhaps splitting it up into small, medium and large volumetric flasks would be a good idea also.

**Comment by 0lafe** [comment]
You could also use 4 cells and then 1 volumetric flask with 608L

**Comment by observeroftime02** [comment]
A cell holds 1000 mb. A recipe in an assembler with 6 inputs and 4 volumetric flasks is not going to be automatable easily. Never mind the recipes that call for 20 buckets of something, like the LuV+ Energy buffers.

**Comment by richardhendricks** [comment]
4608/144=32
Throw 32 ingots into fluid extractor attached to your assembler. Boom, done.
