### ISSUE TITLE
Crossbow bolts quest change. 

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#4786]
The bolt quest in steam tab wants a iron tipped wooden bolt with feather fletching. You can make an alumite tipped alumite bolt with leaf fletching in that age and this one is even better than that magnalium bolt the quest tells you in LV. So change the quest in steam tab to alumite tipped alumite bolts with leaf fletching and remove the magnalium one or change it if there is any better one you can make in that age.

**Comment by Prometheus0000** [comment]
Not everyone has easy access to the materials for Alumite, so forcing them to make it out of that is suboptimal. Changing the rod does nothing, so you'd be forcing people to repair with Alumite all the time.
