### ISSUE TITLE
Move T4 rocket quests from IV to LuV 

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#4790]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried working on the T4 rocket quest, since it was labeled as a mainline quest and might thus be needed to unlock the LuV tab.
#
#### What happened instead? (Attach screenshots if needed)
Tier 4 heavy duty plates were uncraftable at this stage, it requires an LuV assembler for both the T4 ingot and the compressed ice.
The LuV tab itself is rendered inaccessible by the T4 block requirements in the LuV hull quest.
#
#### What do you suggest instead/what changes do you propose?
Remove the first half of the LuV hull quest
Move the T4 rocket quest to the LuV tab (after the appropriate machines)

**Comment by Ngar1** [comment]
some ores from Tier 4 planets are important for IV production. Tier 4 should be IV (before the assembly line!)

**Comment by 0lafe** [comment]
T4 is LuV rn though, but which ores?

**Comment by Ngar1** [comment]
ok, T4 ist helpfull for beginning LuV, but not needed.

**Comment by npo6ka** [comment]
To make a T4 rocket need a 32k assembler...

**Comment by BlackFlameTNT** [comment]
Can you make Zpm mainframes at T4?if not I would take an a 2nd look at all rocket because as far I know T8 is uncraftable and if T4 uncraftable well that mean we have to redo the power and make few test b4 the next up

**Comment by Anarack** [comment]
Yes, otherwise the assline is uncraftable, quantum mainframe are zpm circuits.

**Comment by combusterf** [comment]
As an addendum, I noticed that the LuV hull quest also requires T4 surface blocks, effectively locking the player out of the entire LuV page until after the rocket.

**Comment by Prometheus0000** [comment]
Is this still valid? The Compressed Ice Plates only require an IV assembler in 2.0.9.0dev2, and you can add a second IV hatch to the Assline.

**Comment by Dream-Master** [comment]
So no change needed ? @Prometheus0000 @combusterf @Anarack @0lafe

**Comment by combusterf** [comment]
That would indeed void the need to move the rocket quest.

I'd still recommend uncoupling the LuV hull from the T4 blocks though, mercury is only needed at the very end for the trinium that will complete fusion
