### ISSUE TITLE
Industrial Apiary Adjustments

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT-New-Horizons-Modpack#4791]
Look into the following:

1) Blacklist Industrial apiaries from the WA
2) Add a new upgrade that modifies usage of `public static final int ticksPerBeeWorkCycle = 550;` so the`doWork()` function does work in fewer ticks and doesn't require acceleration.  Ie: `if ticks > (ticksPerBeeWorkCycle - adjustment) then do stuff`
3) Balance it so the end production/power usage is similar to WA, but with less TPS impact.

**Comment by DietmarKracht** [comment]
+1
