### ISSUE TITLE
Oil bee after throw on ground produce useless combs

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#4798]
#### Which modpack version are you using?

7.5
#### If in multiplayer; On which server does this happen? 

myFTB
#### What did you try to do, and what did you expect to happen?
throw bees on ground, but than they are useless
#
#### What happened instead? (Attach screenshots if needed)
Combs receipt say crushed Oilsan, bus they are no crushed because of sand (sand is crushed)
#
![Oil_Bee_4928_Comb](https://user-images.githubusercontent.com/7759876/60382452-8082b400-9a63-11e9-9f43-721341e39095.JPG)
![Oil_Bee_4928_no_crushed_Oilsand](https://user-images.githubusercontent.com/7759876/60382453-84163b00-9a63-11e9-8fb0-6480f48a7dd2.JPG)

#### What do you suggest instead/what changes do you propose?
Combs they produce oil by centrifuge or multiplying Oilsand (not crushed oilsand) in RC

**Comment by richardhendricks** [comment]
Oil combs can be directly centrifuged. Also, can create purified oilsands ore via UU mater. Don't think a change is needed here.
