### ISSUE TITLE
suggestion for new Gallium comb (zinc bee)

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#4799]
#### Which modpack version are you using?
7.5
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
Gallium combs of new GT bees (zinc bee) could only use für Tier 6 planet ores, but Gallium is important before.
#
#### sugesstion
Chemical Reactor receipt with this comb for multiplying Sphalerite Ore
#

**Comment by richardhendricks** [comment]
I dunno, sphalerite is already used with Zinc combs, which you will have more from Zinc bees. Also, Gallium combs + UU at HV makes 4 gallium ore, so I think it's ok as is? Dream, what do you think?

**Comment by Dream-Master** [comment]
in which tier gallium comp is ?
