### ISSUE TITLE
Delta planetary system

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/GT-New-Horizons-Modpack#4804]
#### Which modpack version are you using?
Live delta
#
#### If in multiplayer; On which server does this happen? 
Live delta
#
#### What did you try to do, and what did you expect to happen?

Planetary system at delta is broken completly. U can't use rocket at all, delta PC is dead most of time and half of stargate destinations is not accesable. Helpers and @bartimaeusnek tping ppl when asked, but this is little not normal, and single-way trip(due to no ./homes at planets).

##### Suggestion:
Do something about it. Fix Mercuty teleport atleast - ppl can't get trinium for T5.

Some ideas:
Make a bloodmagic teleposer setups, activated by thrown rocket to hopper. Can be even better with multiple little towns and perms adjasted via commandblocks

+ easy to fix if wipe happend
+ easy to make
- easy to bypass

Allow ./homes at planets at delta 

+ even more easy to make
- still need someone to tp at first time

Rewive drobac and he will fix everyghin =D

+ Everyone happy!
-  just a joke, not possible
![2019-06-29_21 09 18](https://user-images.githubusercontent.com/25028786/60387929-f6fad280-9ab2-11e9-99f6-fc0b2e62eab3.png)
![2019-06-29_21 09 51](https://user-images.githubusercontent.com/25028786/60387931-f6fad280-9ab2-11e9-9382-03f447e92015.png)
![2019-06-29_21 10 48](https://user-images.githubusercontent.com/25028786/60387932-f7936900-9ab2-11e9-9515-9ba46462898e.png)

**Comment by DietmarKracht** [comment]
Or add draconic charm teleport action with pedestals locked by arcane doors. Trade rocket for key for the door
