### ISSUE TITLE
Change the sunnarium piece in Irradiant Reinforced Aluminium Plates to Energetic Alloy

### ISSUE THREAD

**Issue by EmeraldsEmerald** [GTNewHorizons/GT-New-Horizons-Modpack#4809]
Currently, Irradiant Reinforced Aluminium Plates are far too expensive to justify their output, with 20 million EU input required just to produce one LV solar panel, and 10 million EU input for one PLATE.. This is a lot to obtain, especially considering the fact these panels are craftable at HV. This is due to the Sunnarium Piece requirement. 

I propose changing the Sunnarium Piece in the Irradiant Reinforced Aluminium Plate to an Energetic Alloy Plate for several reasons:
- Energetic Alloy still uses glowstone
- Energetic Alloy is a HV-tier material
- Energetic Alloy is already used in EIO's Photovoltaic Cells - why not GregTech's solars too?

Also, it's a plate because an ingot would be odd

Quick edit: Another option would be 8x or 16x Energetic Alloy Foil for a single Plate. thanks, kekzdealer

**Comment by botn365** [comment]
i would make it dens energetic plates foil feels to cheap

**Comment by kekzdealer** [comment]
The energy input isn't even as much problem as the fact that you need the Matter Transformer, which is supposed to be EV gated. This technically even breaks the T+2 rule for Solars. I do support this rule in general, but the step from 8V to 32V solars is just too massive right now. 

@botn365 You can always just have it cost more foil. Dense plates for a thin solar panel feel wrong.

**Comment by 0lafe** [comment]
It's T+1 for solars rn, but not really in creation tier as much as having a single lock on some to a handful at most of T+1 singles. Sunnarium in LV doesn't seem like the worst thing, considering solars aren't really meant to be tier power gen, and substitutions for lower tier gens aren't as needed pre EV.

**Comment by SampsaxD** [comment]
It's not "T+1 for solar rn", unless you classify yourself as HV when you can make IV circuits and tungsten, and MV when you can make EV circuits and Titanium.

The tiering is:
1V - MV
8V - MV
LV - EV (+3) / Titanium
MV - EV (+2) / Titanium + EV Circuits
HV - IV (+2) / Tungsten + IV Circuits
EV - LuV (+2) / Naquadah + LuV Circuits
IV - LuV (+1) / LuV Assembler + ZPM Circuits <- This is a weird one

**Comment by 0lafe** [comment]
HV/EV are T+1. T+2 overall seems good, probably. LuV+ are also t+1 ish and could change. T+4 circuits, T+2 eu/ts, maybe more T+2 mats in them. 

HV could be naq, EV duranium, IV naq alloy, LuV SpNt, zpm infinity, UV something UEV ish. Could also retier the reflector components, and increase those.

**Comment by botn365** [comment]
duranium wich neets fuision for ev while iv neets naqally wich is needit to get fusion defenetly makes sense
so it should be ev naq alloy, iv duranium
