### ISSUE TITLE
GT Electric Wrench has all harvesting tools

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#4814]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
I use GT Electric Wrench with Oriharukon
#
#### What happened instead? (Attach screenshots if needed)
It have harvesting tools.
For example,it harvest  Iszm and Iron Chests.

・These screenshots are from Waila's harvest tools
![2019-07-02_22 04 10](https://user-images.githubusercontent.com/40425798/60515551-c9ae5e80-9d16-11e9-9b2f-6ef937834158.png)
![2019-07-02_22 04 12](https://user-images.githubusercontent.com/40425798/60515558-cfa43f80-9d16-11e9-8e0a-4f17f91a1750.png)
![2019-07-02_22 13 46](https://user-images.githubusercontent.com/40425798/60515564-d16e0300-9d16-11e9-8b2b-5b7d1ef573e6.png)
![2019-07-02_22 14 10](https://user-images.githubusercontent.com/40425798/60515566-d337c680-9d16-11e9-8b40-df49e437dd9d.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by noobyaran9** [comment]
Afaik, it’s not fixable. At least not on the WAILA side. 
About the chest, did u right click or left click?

**Comment by yukieiji** [comment]
All blocks except GT cable were harvested with left click

**Comment by boubou19** [comment]
you can also harvest cable with gt wrench but you need a traveller gear
