### ISSUE TITLE
Needs maintenance cover block update broken

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/GT-New-Horizons-Modpack#4815]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private server
#

I put needs maintenance cover on controller block. It detects problems and emit redstone signal. But when I fix all problems it not stop emit signal. It stop only when block updates. 

Twitch clip here:
[https://clips.twitch.tv/FancyPlayfulShieldFloof](https://clips.twitch.tv/FancyPlayfulShieldFloof)

**Comment by finkledoodle** [comment]
I continue to have the same issue. Most of the time these need maintenance hatches don't seem to work at all (even when properly configured with the soldering iron and such). When they do occasionally work, as Usernm0 says they continue emitting that redstone signal until they are updated, which results in even more work than it would be if I just checked each control block's GUI every time instead.

**Comment by Bubunator** [comment]
the issue still exist in current version on official servers

**Comment by moller21** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/310 ;)
