### ISSUE TITLE
Stockroom catalog is broken

### ISSUE THREAD

**Issue by NIKENIT** [GTNewHorizons/GT-New-Horizons-Modpack#4828]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What happened instead? (Attach screenshots if needed)
Stockroom Catalog item (4666) is broken and shows %material instead of name for the majority of gregtech ores and items.
![изображение](https://user-images.githubusercontent.com/8414371/60770561-78331480-a106-11e9-861c-83cfac3f35c4.png)
![изображение](https://user-images.githubusercontent.com/8414371/60770568-884af400-a106-11e9-900f-97253e8cdea5.png)

**Comment by repo-alt** [comment]
Bibliocraft is closed source but the author does not seem to be much of a dick, so you may report it to him https://github.com/Nuchaz/BiblioCraft/issues. Obviously the issue better be reproduced in a minimized modpack, like Bibliocraft + GT5u
