### ISSUE TITLE
Ferrofluid

### ISSUE THREAD

**Issue by Spluff5** [GTNewHorizons/GT-New-Horizons-Modpack#4837]
## Introduction
![Ferrofluid](https://icdn3.digitaltrends.com/image/ferrofluid-375x375.jpg)
Useless Accessory and I have been developing the idea of a production chain for ferrofluid as a relatively high-tier fluid for use in the assembly machine. Ferrofluid is a black, oily liquid that responds to magnetic fields by forming fluid spikes and can be moves around with a magnet. The fluid itself is made up of magnetite particles that exist on a nano-scale, small enough that they don't settle out of the solution. They are further stabilized by a surfactant chemical that helps them interact with the kerosene liquid part of the fluid.
### Applications
In real life, the main application of ferrofluid is in fluid seals for mechanical machinery, especially those containing magnets such as motors and hard drives, and also as a vibration dampener in aerospace technology. For this reason we propose is as a replacement for Lubricant in high-tier components like the Piston, Pump, and Robot arm and also possibly in rocketry and maybe circuits.
## Production
As usual, the times, power requirements and exact amounts of reagents can be used as long as the ratios stay the same.
**Credit goes to NileRed for figuring out how to do this in real life.**
### Surfactant
**Triolein**
Distillery: 1000L Seed Oil → 200L Triolein
Triolein is the name for the triglyceride Oleic acid is stored as in plants. it would be a pale yellow or maybe slightly green fluid. The 200L amount is variable and could be as low as 30L

**Oleic Acid**
Chemical Reactor: 1000L Triolein + Tiny Pile of Sodium Hydroxide Dust → 3000L Oleic Acid + 1000L Glycerol
This is very similar chemically to the bio-diesel recipe. Oleic Acid is a nice olive-oil yellow colored fluid

**Surfactant**
Chemical Reactor: 1000L Oleic Acid + 1000L Ammonia + 2000L Water → 1000L Surfactant
Chemically, the surfactant is Ammonium Oleate, "surfatant" is the name of this clas of chemical because I thought it sounded cooler. Irl, the surfactant is a thick white paste so could really be a fluid or an item.

### Magnetic Nanoparticles
**Iron(II) Chloride**
Chemical Reactor: 288L Iron(III) Chloride + Iron Dust → 432L Iron(II) Chloride
Iron(II) Chloride would be a lighter green liquid, maybe #79db63

**Magnetic Nanoparticle Mixture**
Mixer: 8000L Ammonia + 8000L Water + 2000L Iron(III) Chloride + 1000L Iron(II) Chloride → 1000L Magnetic Nanoparticle Mixture
Magnetic Nanoparticle Mixture would be a black fluid, maybe with a slight blue or brown tinge.

**Magnetic Nanoparticle Suspension**
Mixer: nL Surfactant + nL Dilute Hydrochloric Acid + 1000L Magnetic Nanoparticle Mixture → 1000L Magnetic Nanoparticle Suspension
The amount of Surfactant and DHA can be anything really to balance the recipe as long as the amounts are the same since these ingredients aren't really reacting chemically. Because this is the first proper nanoparticle suspension in the game, it could have a totally unique fluid texture which I would be happy to make.

**Magnetic Nanoparticle Dust**
Electromagnetic Seperator:  Magnetic Nanoparticle Suspension Cell → Magnetic Nanoparticle Dust + Water Cell
**A Chemical Dehydrator step could also be added here**
Because nanoparticles are so small, the dust could have the less chunky apperance of sugar rather than glowstone-like dust. It should be the same color as Stabilised Magnetic Nanoparticle fluid. This recipe could produce small piles of Magnetic Nanoparticle Dust for balance reasons. It's nice to give the EMS some love. 

### Ferrofluid
Mixer: 1000L Kerosene + 12x Tiny Pile of Magnetic Nanoparticle Dust →  1000L Ferrofluid
I imagine Ferrofluid as a black liquid but with shiny white parts. I guess I could make a texture for this if needed.

**Comment by EmeraldsEmerald** [comment]
Hey it's me! Useless Accessory! I envision the mixer recipes would most likely have to be mixed via cells, but generally I support adding this to the game. Lube gets boring after some time
