### ISSUE TITLE
LootGames always give level 1 rewards

### ISSUE THREAD

**Issue by NIKENIT** [GTNewHorizons/GT-New-Horizons-Modpack#4842]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#### What happened instead? (Attach screenshots if needed)
The LootGames colors minigame always gives Level 1 rewards if you fail. Happend to me several times already, got to the last level, failed, got there again, failed, failed early on the third climb - got level 1 rewards on level 2 or 3.
![изображение](https://user-images.githubusercontent.com/8414371/61143166-aac08100-a4fb-11e9-9fb6-2d7a99fd3412.png)

You can even see it writing "Current level 2. Best attempt: 1"
#

**Comment by Dream-Master** [comment]
@Namikon

**Comment by Impos913** [comment]
This issue still exists in 2.1.0.3a. Happened to me on a local server.
