### ISSUE TITLE
Pyrolyze Oven incompatible with higher tier coils

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/GT-New-Horizons-Modpack#4848]
I know this seems silly, but I'm reporting it anyways because it seems like an oversight. 

The Pyrolyse oven currently does not work with the last two tiers of coils, the Electrum Flux Coil Block, and the Awakened Draconium Coil Block. 

Maybe support for the last two coils could be added for the Pyrolyse Oven.

**Comment by Prometheus0000** [comment]
Seems to be added already. Why can't people ever reference issues when the fix/add things?
