### ISSUE TITLE
Arc Lamp prevents some multiblocks from being assembled fully

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/GT-New-Horizons-Modpack#4856]
2.0.7.5

So this is a completely strange bug, but I need to post this here so it's documented. 

Any type of multi block that has transparent elements to it (Bio Vat as one notable example) will not assemble correctly in the presence of GC Arc Lamps. 

See an example here:
With the arc lamp illuminating the area: 
Block does not assemble.

![2019-07-13_21 51 00](https://user-images.githubusercontent.com/43228249/61402806-ba87ee80-a888-11e9-863e-e06adf00c3fc.png)

Without the arc lamp:
Block does assemble.
![2019-07-13_21 51 09](https://user-images.githubusercontent.com/43228249/61402853-d1c6dc00-a888-11e9-82f4-641ad48d8c4e.png)

I believe this has got something to do with the fact that the arc lamp spawns invisible light emitting TEs everywhere (something like that) that end up in the hollow section of the multi and interfere with the structure of the block. This drove me up the walls trying to get together the Bio Vat, as initially I had no idea why the multi-block would assemble outside of my base, but not inside it. After looking at the interior of my base with McEdit, I found these invisible air light tiles everywhere where the GC Arc Lamps were present. This could potentially turn into a bigger issue, depending on how multi blocks are being assembled, and how lights are placed throughout the base. Blocks with dark interior should be fine (the majority of it), but still.

An idea: Find the precise entity that causes the issue (spawned by GC arc lamps) and black-list it from any structure validation checks.

**Comment by mitchej123** [comment]
Similar to https://github.com/GTNewHorizons/GT5-Unofficial/commit/6b0312f7bbd31c5fa84fed2a48e8feef47ac6a68  Use .getAir() or check block isinstance Block.AIR  don't check for ==  Blocks.air

**Comment by bartimaeusnek** [comment]
should be fixed with BartWorks 0.4.19_pre2 (not public yet)

**Comment by observeroftime02** [comment]
Great news. I'm mostly posting this here so there's a documented instance of the problem for posterity sake. It really is a rather strange and uncommon problem.

**Comment by yukieiji** [comment]
This problem also occurs with TC's Arcane lamp light source
Does the problem with that this light also occur with BartWorks 0.4.19_pre2?

**Comment by yukieiji** [comment]
This problem recurred in Mega Vacuum Freezer with GTNH ver2.0.8.1(BartWorks-0.5.6), please reopen.

**Comment by richardhendricks** [comment]
Need to add info to multiblock info quest to be careful of light sources near hollow multis.

**Comment by mitchej123** [comment]
Or... We can properly check isair instead of == block.air

**Comment by draknyte1** [comment]
Not a problem if they’re coded properly. Don’t bother. 

Just poke Bart to fix his shit. @bartimaeusnek

**Comment by mitchej123** [comment]
https://github.com/bartimaeusnek/bartworks/blob/master/src/main/java/com/github/bartimaeusnek/bartworks/util/BW_Util.java#L436-L477

This should be adjusted to call `block.isAir()` if `Block.Air` is passed in as the `inside` block.

**Comment by Prometheus0000** [comment]
@bartimaeusnek @mitchej123 Is this ever going to be fixed or should I add a note to a quest?
Also the location of the code in question seems to have moved since Jan.
https://github.com/bartimaeusnek/bartworks/blob/8c91821b0be00d8004ba03326430b42c77cb73e9/src/main/java/com/github/bartimaeusnek/bartworks/util/BW_Util.java#L541

**Comment by leagris** [comment]
@bartimaeusnek reminder to fix with isAir() https://github.com/bartimaeusnek/bartworks/blob/master/src/main/java/com/github/bartimaeusnek/bartworks/util/BW_Util.java#L204-L212

**Comment by Glease** [comment]
Is this still a problem in current version? I can see bart made a few changes to BW_Util but I'm not sure if it's sufficient.

**Comment by Prometheus0000** [comment]
Surprisingly, it seems that he _has_ fixed it. Silently. Without telling anyone. At the very least, the 3 multis work fine with arcane lamp lights inside.

Also, it's ironic that he moved the GT multis to BW to make them use the TT structure check (somehow), but his don't use it.

**Comment by botn365** [comment]
the gr multies that got replaced with TT stil very much use the TT air check

**Comment by Glease** [comment]
which should be fixed by GTNewHorizons/TecTech#3

**Comment by Prometheus0000** [comment]
The ticket for them is https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7566
