### ISSUE TITLE
Placing a GalaxySpace Hybrid Solar Panel corrupts the world

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/GT-New-Horizons-Modpack#4858]
2.0.7.5

Placing of a hybrid solar panel from galaxy space in the overworld kicks the player and corrupts the world.

Here's a crash report: https://pastebin.com/5UvuC6hT

Try this at your own risk.

**Comment by Josh5minus1** [comment]
The hybrid solar panel at galaxy space 1.1.9 STABLE works fine, but it would require massive recipe/quest changes.

**Comment by Dream-Master** [comment]
@Josh5minus1 that is impossible because many tiers of planets are missing. So a tiering is not possible sadly. Maybe some asm fix would work. IDK

**Comment by Josh5minus1** [comment]
The last version of GS that has planets is 1.1.9 and they removed in 1.2.0, the rocket crafting in GS got changed, which may not fit the tiering system.

**Comment by Dream-Master** [comment]
@Josh5minus1 did they have 8 Tiers ?

**Comment by Dream-Master** [comment]
didnt find 1.1.9
1.20 is the lastest on curse and btw we add micro patches to the main file so its not the original one ynymore.
I just start the game with lastest GS version and get a nasty crash which leads to a ton of other mods.
Better disable the panel or write a own planet mod.

**Comment by richardhendricks** [comment]
Does the HS provide any benefits?  I think we should just disable it, we've got enough other types of solars.

**Comment by Josh5minus1** [comment]
@Dream-Master 1.1.9 somehow got deleted, I have a copy somehow, but yeah, just disable the hybrid panel.
