### ISSUE TITLE
Some New Crop & Bee Types

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#4870]
These crops and bees are mainly focused around on allowing certain materials to be renewable in some way that they previously never had a renewable source. Or for some others, it allows for a renewable source that's reliably consistent, yet, not as overpowered.

-Mica Crops & Bees
Mica Splundous: T9, 4 stages, 1200 growth points each stage (4800 total points to mature), 0-1 drops upon full harvest; 16 Mica leaves equals to 1 purified Mica ore or rather, boosts Mica related ores as well (Kyanite, Mica, Cassiterite, and Pollucite), requires Mica Ore present under the soil.
EU/t and time for Autoclave: Roughly 100-300 second Autoclave recipe; HV. LV Chemical Reactor recipe using the same schematic recipes of normal leaves (9 leaves + 1 crushed ore + water = 4 purified ores).

Mica Bees: Bred from Aluminium & Industrious at an 8% chance. Normal Temperature, Normal Climate. Yields 1 Mica comb at a 25% chance; comb is processed at an MV centrifuge to produce 2 tiny piles of Mica dust at 10 seconds.

-Earthila or Raretato or Raredish Crop
Earth's Rarety: T10, 4 stages, 1600 growth points each stage (6400 total points to mature), 0-1 drops upon full harvest; 8 Earth's Rarety Leaves when inputted into an Extractor will yield 1 tiny pile of Rare Earth, or when inputted into a Chemical Reactor and any Neodymium byproduct (Bastnasite, Monazite, Neodymium, Redstone, Samarium, and Rubracium) with the same schematic recipe type will yield 4x more ore product as per usual, requires Neodymium Ore or a block of Neodymium present under the soil.

-Stonelila & Space Drops
Addition to the Stonelila crop, **if** a planet stone of a particular type is placed underneath the soil of a Stonelila crop, the Stonelila crop will instead produce space dust based on the particular planet stone. Drops range from 0-1. However, these planet stones will take much longer to fully mature and require a slightly heavier nutrient count to compensate.

Otherwise, if the Stonelila crop isn't all that suitable for crop breeding in terms of balance, then resort to creating additions of new crops based on the planets and of which that they require the dedicated blocks to fully mature.

I may be missing some crop and bee-related products, if I am missing any of them, please do let me know and or add some of your ideas as well! I'm open to discussion on balancing these if they are either too strong or too underpowered.

**Comment by SampsaxD** [comment]
For the Rare Earth crop requiring either a Neodymium related ore or a neodymium block would be pretty crucial to not totally break Neodymium gating. Also suggest Earthlia as a name-

**Comment by ScriptedPiky** [comment]
> For the Rare Earth crop requiring either a Neodymium related ore or a neodymium block would be pretty crucial to not totally break Neodymium gating. Also suggest Earthlia as a name-

You got it, added in the Neodymium ore or Neodymium block requirement and changed the name. As well as added in the Plant Stone mechanic for Stonelila's

**Comment by richardhendricks** [comment]
I propose the name Raretato :D

**Comment by ScriptedPiky** [comment]
> I propose the name Raretato :D

Added that as a possibility for the Rare Earth crop 🎉

**Comment by EmeraldsEmerald** [comment]
How about  Raredish? (radish)
