### ISSUE TITLE
buff sphalerite on T4+ planets

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#4871]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What do you suggest instead/what changes do you propose?
you neet a lot of indium when you get to LuV+ 
and insane amounts in UV so sulfer veins on T4+ planets should get sphallerite as secondery ore so that the methode methode using ores can compete with the replicater methode

**Comment by bartimaeusnek** [comment]
There is a low-processing ore on Ross128b, Quadruple-able ores in the Nether, and UUM dont see why you would need another source of Indium at that point.

**Comment by botn365** [comment]
tis isent an other source of indium but makes sphalerite easyer to obtain on higher planets

**Comment by Dream-Master** [comment]
@botn365 @bartimaeusnek so what i should do ? buff it or let it like it is ?

**Comment by bartimaeusnek** [comment]
i dont think there is a need for an indium buff at all, maybe ask others aswell

**Comment by sthegreat** [comment]
I think it's fine as is. I like that indium actually makes sense to replicate right now.

**Comment by observeroftime02** [comment]
Seeing how Barts T3 planet has got Roquesite that processes into Indium i think that's a good source for it. Perhaps the ore itself could be a bit more common, as even a T4 mining rig only yields very small amounts of it. On average I get less than 200 ores per rig. Either increasing the size of the vein, increasing the density, or increasing it's weight could be sensible buffs to this.

**Comment by Ngar1** [comment]
@ Barti Ross128b isnt reachable on FTB, because of stability problems they switched them off

**Comment by bartimaeusnek** [comment]
@Ngar1 aint my problem. stability problems should be fixed in the next release anyways

**Comment by Dream-Master** [comment]
ok so i close this issue the next release and we tested with the Ross ores.
