### ISSUE TITLE
minor correction: text at HP steam turbine

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#4876]
#### Which modpack version are you using?
2075
#
#### If in multiplayer; On which server does this happen? 
myftb
#
#### What did you try to do, and what did you expect to happen?
1) Text of XL HP Steam turbine say 2 times maintance hatch -> one times enought?
![HP_Turbine](https://user-images.githubusercontent.com/7759876/61990953-fe79b100-b049-11e9-837f-57d82fcf2f9d.JPG)

2) Text of both  HP Steam turbine say "superheated input .." -> it is not a
 special? If, it should mean `"input hatch for superheated.."
#

**Comment by observeroftime02** [comment]
I don't think those work at all at the moment for what it's worth

**Comment by Dream-Master** [comment]
Yes and they dont have a recipe.
@Ngar1 feel free make an issue on Gt++ side.

**Comment by Dream-Master** [comment]
https://github.com/alkcorp/GTplusplus/issues

**Comment by Ngar1** [comment]
I placed it at GT++

**Comment by richardhendricks** [comment]
Still in 8.0
