### ISSUE TITLE
Fluid terminal search bar always in focus

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/GT-New-Horizons-Modpack#4881]
![image](https://user-images.githubusercontent.com/43228249/62030521-17917780-b19a-11e9-9582-bb1371d61a48.png)

Basically, having a fluid terminal open, stationary or portable, the search bar always has the focus of the keyboard input. That means looking at recipes and other things while the terminal is open is  impossible. Also, the terminal does not close with the E key or whatever else key is assigned, necessitating the use of ESC to close the terminal. This behavior is not consistent with any other minecraft GUI. 

Maybe there is an easy fix for it, maybe there isn't, either way I'm posting this here.

Example:
https://gfycat.com/powerlesswidefish

**Comment by DeForce** [comment]
that would be me
