### ISSUE TITLE
remote io blank plate has wierd restone use

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#4884]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What do you suggest instead/what changes do you propose?
the blank plate uses 100L molten redstone but is you fluid extract redstone you get 144L
![afbeelding](https://user-images.githubusercontent.com/42187820/62076691-98a74800-b248-11e9-8d5a-a39886adc511.png)
it should use 144L molten redstone so that it needs 1 redstone instead of 0.6944444 redstone

**Comment by repo-alt** [comment]
@botn365 I think if you make a PR fixing that, Dream will have no problem accepting it.

**Comment by Dream-Master** [comment]
very old recipe need a change
