### ISSUE TITLE
Gadomancy's Golem Core changing when removing Golem.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#4891]
#### Which modpack version are you using?
2.0.7.5(gadomancy-1.7.10-1.0.7.5)
#
#### If in multiplayer; On which server does this happen? 
Singe
#
#### What did you try to do, and what did you expect to happen?
Right-click removed Golem with Gadomancy's Golem Core, such as Golem Core:Break and Golem Core:Bodyguard.
#
#### What happened instead? (Attach screenshots if needed)
Gadomancy's Golem Core changed.
Golem Core:Break changed to Golem Core:Empty.
Golem Core:Bodyguard changed to Golem Core:Guard.
When Shift+Right-click removed Golem with Gadomancy's Golem Core, it not changing.

・Golem Core:Break setting
![2019-07-31_14 32 41](https://user-images.githubusercontent.com/40425798/62186836-7b868c80-b3a2-11e9-8d6d-02162d53c5c5.png)
・Right-click removed Golem.
![2019-07-31_14 32 45](https://user-images.githubusercontent.com/40425798/62186839-7d505000-b3a2-11e9-81ed-b6bdb5fbbb36.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it

**Comment by thenextelement** [comment]
Just switched out for the latest version of Gado that's in 2.7 and this is still happening, does it require something other than just the base fork?
