### ISSUE TITLE
Rebalance Cadmium in batteries

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#4893]
#### Which modpack version are you using?
2.0.7.5 (technic launcher)

#
#### If in multiplayer; On which server does this happen? 
Private Server

#
#### What did you try to do, and what did you expect to happen?
Follow quest 'A big Meteorite' #623
Follow first few steps: Get skystone, crush, centrifuge to get rare earth.
Next step of quest is to centrifuge rare earth for cadmium

#
#### What happened instead? (Attach screenshots if needed)
There is no longer a centrifuge recipe for rare earth (now HV sifter recipe) but quest is an LV one.

#
#### What do you suggest instead/what changes do you propose?
A) Either rework quest completely: with a way to produce cadmium and/or a use for sky-stone dust
B) or re-add centrifuge recipe (if removed by accident) 
C) or add in a basic LV centrifuge recipe (if deliberately removed) for processing rare earth (E.g. restricted to just some lower tier outputs)

**Comment by Dream-Master** [comment]
@drayath idk who removed recipe ?

**Comment by draknyte1** [comment]
I did, guess nobody thought to update the quest. (Community was asked and were made aware months ago when this was done, they were happy with the change)

**Comment by Dream-Master** [comment]
@draknyte1 Ok and how i can make my cadmium batteries? There are more quest that are affected.

**Comment by draknyte1** [comment]
Cadmium as an LV battery material never made sense and it was the majority opinion by the 10-20 involved in the discussion that the lack of availability now present is better. Who makes cadmium batteries over sodium or lithium? Nobody. Being a Rare Earth material, it shouldn’t have even been a thing for that tier.

**Comment by Dream-Master** [comment]
@draknyte1 ok but we have more than 10-20 players and we dont have such decission under the radar. I want that recipe back.

**Comment by draknyte1** [comment]
I’ll re-add it, but I’m not removing the sifting recipe. It’s REQUIRED for obtaining further rare earth elements.

**Comment by Dream-Master** [comment]
sure let the sifting recipe

**Comment by 0lafe** [comment]
I'm not against only having the sifting recipe. That said, a more indepth rare earth proc thing could be fun instead of all the outputs at once. Could gate some based on eu/t too and start at LV for cadmium, then tier the higher tier materials with higher tier voltages

**Comment by Scottishprog** [comment]
Keep in mind: 

Cadmium Batteries are needed for the EIO Capacitor banks. No Cd, no banks, and tier.

**Comment by Dream-Master** [comment]
sure we can add two or three recipes with more and more outputs and reduce the lv one but not remove it completely with zero message that the recipe is vanish and I get notice of this via this issue

**Comment by Xauronx** [comment]
I wanna add to this cause i ran in another cadmium related problem...

Cadmium is the main material for MV superconductors. And Veins of it are only aviable on T8 planets and DD.

MV superconductors are requiered in LV solars

**Comment by draknyte1** [comment]
Still makes more sense to replace cadmium with a tier appropriate material..
As opposed to making rare earth processing LV. Which serves no purpose beyond obtaining mistiered cadmium.

**Comment by richardhendricks** [comment]
It is odd that we just have "cadmium batteries" with no need for nickel. Would make more sense to add a "nickel-cadmium mix" material that we can adjust the cadmium used at the mixer, ie 1 tiny cad + 1 nickel. That way the tiny amounts available early on make sense.

The really weird this is why the heck is lithium an output from clay processing? That's what's odd and drives everyone to use lithium batteries.

**Comment by repo-alt** [comment]
A bit later lithium in insane quantities comes from salt water being electrolyzed for chlorine, but it is usually done at HV+, so probably not an issue.

**Comment by Ethryan** [comment]
Perhaps something like this could be used:
Mixer with Ni3Cd, that way 1 cadmium dust = 2/3 of a lv battery.

This makes cadmium still hard to use early but not so prohibitly expensive as it is right now.

**Comment by leagris** [comment]
If you go that route, don't stop at the electrolyte. Because battery casing made of lead and tin is a non-sense for all kind of battery. Then fix Lead-Acid batteries to use lead and zinc plates additionally to acid filling.

Ten you end-up with specific casing, specific anode cathode combination...

Then the whole game mechanic with batteries is turned into boring realism rather than incentive reward driven game fantasy mechanic.

Do you get it? Gregtech batteries are fantasy. Trying to add realism to it is just a waste of time, making the game worse and wasting precious developers maintainers resources.
