### ISSUE TITLE
Centrifuging wood for methane supports only a couple of wood types.

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#4895]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
Private 

#
#### What did you try to do, and what did you expect to happen?

Quest 1869 text describes centrifuging wood to produce methane

However in practice the wood that you can use is incredible restricted (just Oak/spruce/birch/jungle)

Is this intended behavior as it seems odd that i can use these wood types but not use my hoarded stores of twilight/dark oak/redwood etc.

#
#### What do you suggest instead/what changes do you propose?

Would expect that any woods that don't have a specialty centrifuge recipe (e.g. rubber wood) would be centrifugal to methane.

**Comment by draknyte1** [comment]
The updated build of GT++ isn't within GTNH-dev yet.
But afaik, it's tested and working, so expect it..
