### ISSUE TITLE
Re-enable BC water springs

### ISSUE THREAD

**Issue by SpwnX** [GTNewHorizons/GT-New-Horizons-Modpack#4899]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
GTNH - Epsilon (reports from discord says it does happen on SSP aswell)
#
#### What did you try to do, and what did you expect to happen?
Obtain water from a spring
#
#### What happened instead? (Attach screenshots if needed)
It did not spawn water
![javaw_2019-08-02_16-21-32](https://user-images.githubusercontent.com/2791175/62397985-6138e400-b545-11e9-9fba-1b5914953db6.png)
#
#### What do you suggest instead/what changes do you propose?
Re-enable said water springs. 
It is a very rare spawn and combined with the fact that it does not have any surface flow or protusion (unlike oil wells) it is hard to miss. Thus, i propose that if someone happen to find it, they should be rewarded with infinite water.

**Comment by richardhendricks** [comment]
Are these the things that make a pillar of water above them? How do you get infinite water from them? We removed the water spouts because they are pretty useless overall.

**Comment by SpwnX** [comment]
the last block (the one i'm pointing) spawns one water block above them, or that is how it should be.

**Comment by richardhendricks** [comment]
What's the use/restrictions on it? Can it be moved? What's the mining tier? Non-renewable water is such a big part of the pack I don't like the idea of a trivial water source early on without significant danger/annoyance.

**Comment by observeroftime02** [comment]
It can't be moved, it's like a bedrock block.

**Comment by CalterOK** [comment]
These water sources were turned off quite a while ago, after my caspose about how they can be automated on distributors

**Comment by SpwnX** [comment]
they can be automated via many setups, but it alongside being an unmovable object, it becomes obsolete after the everful urn or reservoir.

**Comment by CalterOK** [comment]
Disabled since they can be automated at the very beginning of the game. The fact that they are not tolerated is not such a problem. You can start development next to him, after moving.

**Comment by Methes** [comment]
I like them turned off because dealing with them when mining an area is pita.
BUT. Going out of your way and creating a contraption to farm the bedrock block which gives you replenisable water should be rewared accordingly. Building water tanks or stirling pump is way easier than finding suitable base location with this water spring present and then building your water source around it.
I wouldn't be opposed to reenabling them.

**Comment by Ethryan** [comment]
Leave disabled since they sometimes can have wierd interactions with oilwells. 1 Time before it was disabled i got an oilwell that spawned, then a waterspring spawned inside the oilwell and ****ed up my oil pump.

**Comment by SpwnX** [comment]
> Leave disabled since they sometimes can have wierd interactions with oilwells. 1 Time before it was disabled i got an oilwell that spawned, then a waterspring spawned inside the oilwell and ****ed up my oil pump.

I just wonder whats the chance of that happening.

**Comment by DoomSquirter** [comment]
I vote keep disabled

I have a bedrock basement.  if I had gotten down there and found water springs I would have been pissed.

on a side note, it would be nice if we had flat bedrock enabled.  but that's just me.

**Comment by Anarack** [comment]
Anyone know if these things are even fast enough to have a point? I know the oil ones are extremely slow.

**Comment by SpwnX** [comment]
They are very fast, spawning water every tick, making it worth 20 buckets a second.
Or 20 reservoirs.
