### ISSUE TITLE
Plantball+honey brewing recipe uses weird honey type.

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#4902]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
Private

#
#### What did you try to do, and what did you expect to happen?

Use a basic brewing machine to run the recipe: Honey + plantball -> biomass

Recipe only seems to work (according to nei) with honey that comes out of void/magic honey capsules.
You can't use honey extracted from honey drops and there seems to be no way (according to nei) to convert between the honey types.

#
#### What do you suggest instead/what changes do you propose?

Ideally unify honey types, otherwise either add recipes using both types or a simple conversion recipe.

**Comment by Dream-Master** [comment]
There is a conversion recipe from forestry to bop honey and the way around.

**Comment by drayath** [comment]
Would you know how.

Can find three types of honey; there is a centrifuge recipe to convert **from** the honey needed in the brewing recipe (to different honey type or sugar), but can't find a way to convert **too** the type of honey required

**Comment by Dream-Master** [comment]
make a few pics for me please @drayath

**Comment by drayath** [comment]
Brewing recipe
![2019-08-04_16 18 13](https://user-images.githubusercontent.com/6987850/62425664-7b083180-b6d3-11e9-9179-e7ad6c9bc87f.png)

--
These are the only 2 recipes types NEI show to make that honey (6857:26):
![2019-08-04_16 11 36](https://user-images.githubusercontent.com/6987850/62425529-ac343200-b6d2-11e9-9a59-63ea04077a80.png)
![2019-08-04_16 11 39](https://user-images.githubusercontent.com/6987850/62425535-adfdf580-b6d2-11e9-9ae2-36d9119a1145.png)

-----

There is a centrifuge recipe to convert from (6857:26) to (6857:31) but not the other way round
![2019-08-04_16 19 08](https://user-images.githubusercontent.com/6987850/62425679-a4c15880-b6d3-11e9-9978-96112cd461d9.png)


--

There is also a fermenter recipe but that converts from (6857:31) to (6857:31) for some reason
![2019-08-04_16 14 56](https://user-images.githubusercontent.com/6987850/62425575-16e56d80-b6d3-11e9-8ae9-2c809e66f8ef.png)
--
In my game
gregtech honey cell (created from extracting honey drop) goes to fluid:  (6857:31)

**Comment by Dream-Master** [comment]
Who add that honey to biomass recipe in the first place. Using 3 eu/t is a very unique recipe.
So there is beside forestry and bob honey a gt honey?
