### ISSUE TITLE
Allow the EBF to do alloy smelter recipes

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/GT-New-Horizons-Modpack#4904]
talking about things like electrum or bronze. those can only be made in the normal alloy smelter right now and at higher tiers, it gets a bit slow. if the EBF can do tungstensteel, why not things like electrum? could be a better, more efficient way at later tiers, probably requires a circuit (no. 4?) or whatever to not mix with other EBF recipes.

**Comment by draknyte1** [comment]
ABS already does them all.

**Comment by richardhendricks** [comment]
@Dream-Master Implement or not? Up to you

**Comment by Dream-Master** [comment]
Ebf shouldn't  have ingots alloying in gtnh. Dust alloying ok

**Comment by Prometheus0000** [comment]
The Zyngen (alloy smelter multi) has a recipe now, so this is pointless.
