### ISSUE TITLE
Mega Blast Furnace

### ISSUE THREAD

**Issue by CalterOK** [GTNewHorizons/GT-New-Horizons-Modpack#4905]
#### Which modpack version are you using?
2.0.7.5
Mega Blast Furnace does not use nitrogen for melting (all recipes with it are carried out as if it were not). 
The panel also does not show the temperature of the heating rings.
![image](https://user-images.githubusercontent.com/35035276/62464810-3db8a800-b796-11e9-805b-4b5dba3f90da.png)
I did not notice that the acceleration would work.
![image](https://user-images.githubusercontent.com/35035276/62464952-7ce6f900-b796-11e9-9f38-0f7c14eba09d.png)

**Comment by Prometheus0000** [comment]
@bartimaeusnek Did you ever fix this?

**Comment by bartimaeusnek** [comment]
Idk, needs to be retested, I'll retest once I pushed my changes I made during the last weeks

**Comment by Prometheus0000** [comment]
It shows even less info now
![image](https://user-images.githubusercontent.com/8517039/98843714-54c65b00-2419-11eb-9862-06883e441938.png)

**Comment by Prometheus0000** [comment]
According to bart this is intended? I'm not sure which part he meant though. It does appear to do the upgraded overclock, and use nitrogen correctly now though.
@bartimaeusnek Why does it not show the heat capacity anymore?
