### ISSUE TITLE
some small additions to the official servers 

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/GT-New-Horizons-Modpack#4907]
So basically, server lacks some stuff in my opinion, I'll try to list some stuff, might add more later
So first, server [broadcast] (that thing console says in chat every hour or so )should have more info to say, I recommend something along the lines of the following:

"Server donations have been reset, besure to donate for command permission"  just to make sure everyone knows about it <3

Every new player needs to be told by other players to do the following, while it's nice for players to help eachother, I think basic information should be broadcasted, here are some:
"To protect yourself  and your stuff /mytown and create your own town"
"To get money, you need a job, do /jobs browse and select the 3 you like the most"
" /Rankup and get more homes and better chunkloader coins"
"/Jobs shop offers chunkloader coins for your chunkloading needs"

And most important one
"Remember to clean your browsing history regularly"

**Comment by glowredman** [comment]
At least at rank Dweller you get a reminder that there are now T2 Chunkloader Coins available in /jobs shop. I don't know about the lower ranks though.
