### ISSUE TITLE
Can't mine BartWorks ores with DE Staff of Power on Safe Mode

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/GT-New-Horizons-Modpack#4915]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
Tried to mine BartWorks ores on Ross128B

#
#### What happened instead? (Attach screenshots if needed)
Get an error that there are tile entities in the area and nothing gets mined.

![image](https://user-images.githubusercontent.com/34566584/62763269-79bd7700-bace-11e9-9faf-0f0bc2bae4ef.png)

#
#### What do you suggest instead/what changes do you propose?
Fix BartWork ores to work correctly.

**Comment by bartimaeusnek** [comment]
the issue here lies within the whitelist of the draconic stuff not my ores.

**Comment by AlexBucket** [comment]
GT++ ores work correctly with the staff, maybe ask Alk for help.

**Comment by bartimaeusnek** [comment]
GT++ ores are not tile entites.

**Comment by mitchej123** [comment]
@bartimaeusnek Can you add your ore classes to this check? https://github.com/GTNewHorizons/Draconic-Evolution/commit/21981128ac70677a463a227a9a8d17705c180608
