### ISSUE TITLE
Railcraft's solid fuel boiler produces infinite steam without fuel usage

### ISSUE THREAD

**Issue by SomeCatIDK** [GTNewHorizons/GT-New-Horizons-Modpack#4920]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
This is happening on my personal server I setup to play with a bunch of friends.

I can provide the IP if needed, but I'm not sure how long this problem will persist.
#
#### What did you try to do, and what did you expect to happen?
We had a solid fuel boiler firebox running with a single low pressure boiler tank. We wanted to upgrade it, and just decided to hot swap boiler tanks while the machine was running. (amazing idea)

Instead of the firebox beginning to heat the new tank and continue on as expected (or explode), it began to work with just one piece of charcoal infinitely. 
#
#### What happened instead? (Attach screenshots if needed)
It created a loop where it can infinity burn a single piece of charcoal.

![image](https://user-images.githubusercontent.com/29684429/62823327-f3507600-bb5d-11e9-9807-ceee62f2c124.png)

![image](https://user-images.githubusercontent.com/29684429/62823332-03685580-bb5e-11e9-85f6-6b524ab47ac3.png)

```
100% valid code:

for (int i = -1, i != 0, i--){
    burn();
}
```
#
#### What do you suggest instead/what changes do you propose?
Possibly upgrading to a newer version of Railcraft, if one is not available, then maybe a custom fork of Railcraft can be created to fix this bug.

I'm unsure how long this will go on; it obviously won't be infinite as the number will overflow, but I will continue until it does and comment the results.

**Comment by Dream-Master** [comment]
@SomeCatIDK i chat with CovertJaguar some times before about a custom fork of Railcraft but that isnt possible. Some of his data he hold private so we cant make a fully new build. Not sure what can do here.

**Comment by draknyte1** [comment]
> I'm unsure how long this will go on; it obviously won't be infinite as the number will overflow, but I will continue until it does and comment the results.

Integer.MAX_VALUE is a big number.

> Not sure what can do here.

Make me a ticket, I'll add it to the Railcraft ASM I already do.

**Comment by SomeCatIDK** [comment]
> > I'm unsure how long this will go on; it obviously won't be infinite as the number will overflow, but I will continue until it does and comment the results.
> 
> Integer.MAX_VALUE is a big number.

I assumed Minecraft would use a smaller data structure for a value that doesn't go above 64 in vanilla play, thanks for the info.

> > Not sure what can do here.

> Make me a ticket, I'll add it to the Railcraft ASM I already do.

What do you mean by that? I can re-upload the issue to the Railcraft's GitHub issue page if that would be better. Once it's fixed and the changes are published I will update the issue here.

**Comment by draknyte1** [comment]
> I assumed Minecraft

First mistake, don’t assume. MC uses the wrong data types everywhere, lol. Java itself is limited to bytes (128 max) shorts (32k max) ints and longs. Every number is assumed to be an integer unless specified otherwise, so they’re used as a standard even when values never exceed 100.

> What do you mean by that?

That was aimed at Dream, if either of you reports this to my GitHub (GT++) I’ll fix it. I don’t see RC releasing a new version in 2019, so like all closed source mods, fixing falls back to us devs using java byte code to hot replace the code in question with fixed code.

**Comment by draknyte1** [comment]
```
public static ItemStack depleteItem(ItemStack stack) {
		if (stack.stackSize == 1) {
			return stack.getItem().getContainerItem(stack);
		} else {
			stack.splitStack(1);
			return stack;
		}
	}
```
Ok Railcraft.

**Comment by MrKorpiklaani** [comment]
Same. Version 2.0.8.9 dev, 
issue still here. 

![image](https://user-images.githubusercontent.com/20806770/79504521-4fe02b00-8033-11ea-90aa-f25d0a0b04e5.png)

**Comment by draknyte1** [comment]
@MrKorpiklaani could you make a ticket on the GT++ tracker with your full FML-client-latest.log? Server log also if you’re hosting your own server (or playing on a server)

**Comment by MrKorpiklaani** [comment]
Done. 👍

**Comment by bombcar** [comment]
This is fixed in stable and can be closed
