### ISSUE TITLE
Floodlights occasionally cause server to crash

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/GT-New-Horizons-Modpack#4921]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
ProsperCraft

#
#### What did you try to do, and what did you expect to happen?
Loaded an area with floodlights

#
#### What happened instead? (Attach screenshots if needed)
Server crashed

#
#### What do you suggest instead/what changes do you propose?
Fix floodlights

https://paste.fedoraproject.org/paste/xt~xtw9ZeULFJxeNWk0xdw

**Comment by richardhendricks** [comment]
@AlexBucket Any details on the crash?

1. Consistent?  Every time those chunks are loaded?

2. Anything in particular about the floodlights setup that might trigger a crash? Light-beams crossing, etc? 

3. How are the floodlights configured? Cone or straight?

Floodlights mod is open source. https://github.com/Keridos/FloodLights/tree/1.7.10

https://www.baeldung.com/java-concurrentmodificationexception

    public void updateAllSources() {
        for (int[] source : sources) {
            TileEntity te = worldObj.getTileEntity(source[0], source[1], source[2]);
            if (te != null && te instanceof TileEntityMetaFloodlight) {
                ((TileEntityMetaFloodlight) te).toggleUpdateRun();
            } else {
                this.removeSource(source[0], source[1], source[2]);    <-- Looks like the problem!
            }
        }
    }

**Comment by richardhendricks** [comment]
uh.... that code is some "weird shit"

**Comment by draknyte1** [comment]
You shouldn’t update something while iterating. 
Just gotta use a concurrent data type. (Concurrent hashset of int[][][])

**Comment by finkledoodle** [comment]
This is my base where the crash was happening.
1. No it doesn't seem to be consistent, sometimes it crashes when I first load the area, other times I could be returning to that chunk an hour later (still loaded with chunkloader), and then it would crash.
2. Yes, I have a series of floodlights on the ceiling, as well as a set right above the fluid level to light the surface.
3. The lights on the ceiling are cone, those on the surface are straight
Row of lights at surface level, and then in the ceiling above
![2019-08-14_13 55 58](https://user-images.githubusercontent.com/12854704/63055692-52cebe80-be9b-11e9-8ed8-d70b975f6e6e.png)

That Ztyl block was one of the PhantomLight issue blocks, the other was in the same configuration.
![2019-08-14_13 56 40](https://user-images.githubusercontent.com/12854704/63055725-6712bb80-be9b-11e9-9d64-e629718e94b0.png)

**Comment by finkledoodle** [comment]
As a slight update to this, I learned that there is at least 1 arcane lamp near these phantom light blocks, so it may be some sort of relationship between floodlights creating light sources and the arcane doing the same. As I mentioned above, loading the area above does not cause crashes every instance, so maybe it has to do with the order in which the floodlight and arcane lamp happen to create their light sources.
