### ISSUE TITLE
Gold Etched Obsidian recipe incorrect.

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#4926]
#### Which modpack version are you using?
2.0.7.5

#
#### If in multiplayer; On which server does this happen? 
Private

#
#### What did you try to do, and what did you expect to happen?
Trying to make Gold Etched Obsidian, issues with recipe.

![2019-08-11_13 13 13](https://user-images.githubusercontent.com/6987850/62833622-d25d5300-bc39-11e9-9c38-9aabca7d9425.png)

#
#### What do you suggest instead/what changes do you propose?
Assume this should be an oredict for variants of obsidian blocks.

**Comment by Rika-TH** [comment]
this seems to be occuring again as of 2.4.0 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/38961580/ccbdcbe3-8b87-4b9f-a4a8-c1daf81d1c27)
