### ISSUE TITLE
Genetics fails to add sequenced traits to the database

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/GT-New-Horizons-Modpack#4930]
2.0.7.5

Many of the sequenced traits are not added to the database. 

Things like: Temperature Tolerance, Tolerant Flyer, Cave dwelling, Flower type etc.

The only things successfully added are Species. The rest seems random, with the vast majority simply not working at all.

Take this for example: 
![image](https://user-images.githubusercontent.com/43228249/62840925-3c83f100-bc56-11e9-802a-bb421d65a82d.png)

I go ahead and sequence it

![image](https://user-images.githubusercontent.com/43228249/62840930-54f40b80-bc56-11e9-8e43-fdd8c25de322.png)

It fails to show up

![image](https://user-images.githubusercontent.com/43228249/62840937-6fc68000-bc56-11e9-8232-4f4ed85d5406.png)

What gives? This makes Genetics basically unusable outside of the species trait if most sequenced traits simply don't show up. These traits _do_ exist in the master gene database, so it's not like it's some custom trait from another mod issue. What can I do here?

I've read [here](https://github.com/GTNewHorizons/NewHorizons/issues/4421) that some people were having similar issues a while back and that it _might be_ fixed, but to date this issue remains.

**Comment by yukieiji** [comment]
The same issue has already been reported #3913

**Comment by Hyperic88** [comment]
Issue still persists in 7.6bdev

**Comment by Dream-Master** [comment]
@bartimaeusnek is this somethings we can fixed or need this changed in binnies mod source ?

**Comment by Dream-Master** [comment]
or a gt issue ?

**Comment by bartimaeusnek** [comment]
should be fixed with: https://github.com/GTNewHorizons/GT5-Unofficial/pull/205

**Comment by Hyperic88** [comment]
Wooo :) great, cant wait to test :))

**Comment by Dream-Master** [comment]
soon will update zeta on weekend hopfully

**Comment by yukieiji** [comment]
This issue recurred in GTNH ver2.0.8.1, please reopen.
I still testing, but I couldn't add to the database when I analyzed Certus, Ruby(GregTech) and Diamond(GregTech) bees.

**Comment by Dream-Master** [comment]
@yukieiji did you using binnies mod version 24 ?

**Comment by yukieiji** [comment]
The version I am using is binnie-mods-1.7.10-2.0.24
