### ISSUE TITLE
Crops tooltip leaks information

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#4934]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I was collecting new crop breeds to analyse and noticed a (new?) ctrl-option
#
#### What happened instead? (Attach screenshots if needed)
The extra info gives clues to the exact species/other information I probably shouldn't have pre-scanning.
![image](https://user-images.githubusercontent.com/8459776/63001598-3cf9d300-be74-11e9-91d7-b1dd8e052285.png)
![image](https://user-images.githubusercontent.com/8459776/63001615-4420e100-be74-11e9-8618-6dd5e634f8d6.png)

Extra information is particularly identifying for all metal-like crops I've tested (including TF and Thaumcraft ones), and a few non-metal ones like oak bonsai.
#
#### What do you suggest instead/what changes do you propose?
The tooltip should not show the ctrl-hint / extra information on unidentified crops

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by bartimaeusnek** [comment]
@Dream-Master Speiger, not me on this. Its the NEI Plugin that adds this.

**Comment by Dream-Master** [comment]
@Speiger any idea. Is this fixable?

**Comment by Speiger** [comment]
o.O Oh yeah  that is fixable. But to get the seed you already know what you got technically.
But this will be patched soon.

**Comment by Dream-Master** [comment]
ok Thanks

**Comment by Prometheus0000** [comment]
Was this ever fixed?

**Comment by Speiger** [comment]
This actually got lost under another much more demainded "Fix" request that was so vocal that i said, you got that don't ask for anything else. (I didn't want to add the fix because it was providing false information)

**Comment by Prometheus0000** [comment]
Well, I don't really care if it's fixed or not anyway, it's not like they're hard to scan, and past a certain point you just use the portable one to check the stats anyway, so it's already scanned by the time you pull it out.
