### ISSUE TITLE
Wrong values for vacuum freezing If* ingots

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/GT-New-Horizons-Modpack#4938]
It takes 2 mil eu/t to smelt Infinity dust, but takes 20 mil eu/t to cool it. Because I'm unsure if this is intended or a mistake, I'm posting this here

![image](https://user-images.githubusercontent.com/43228249/63078582-cfd85300-bef0-11e9-96ee-25a90e96115d.png)

It's the GTNH Core Mod that adds these values, can @Dream-Master look at this?

**Comment by Dream-Master** [comment]
yes it intended and in the core mod. What is wrong with the recipe ? @observeroftime02

**Comment by observeroftime02** [comment]
You need 10x as much power to cool the ingot than you need smelting it, meaning one would need at least an UIV energy hatch on a freezer. This seems completely out of proportion to me. It's quite unusual, that's why I thought I'd check.

**Comment by Dream-Master** [comment]
will check the code. Maybe its autogenerated recipe.

**Comment by observeroftime02** [comment]
I had a look and it's a recipe that gets added via GT_MachineRecipeLoader.java, I know an extra zero is an easy thing to miss when typing that many zeroes in a row

**Comment by Dream-Master** [comment]
sure a misstype is possible.

**Comment by DietmarKracht** [comment]
i dont think its a mistake. Infinity is supposed to be UEV which is 8m eu/t. and that is close to 10m.
