### ISSUE TITLE
Rainforest oak in cutting machine

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [GTNewHorizons/GT-New-Horizons-Modpack#4943]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Put rainforest oak into cutting machine, would expect it to make 6 oak planks and 1 wood pulp just as for oak and twilight oak
#
#### What happened instead? (Attach screenshots if needed)
Didn't give me any planks :(
#
#### What do you suggest instead/what changes do you propose?
As you can already make oak planks from oak, twilight oak, and rainforest oak by hand (in the crafting table), I would suggest that the same 3 types of oak would all also have a recipe in the cutting machine.

**Comment by Dream-Master** [comment]
From which mod Rainforest oak is? @AndrewAmmerlaan

**Comment by AndrewAmmerlaan** [comment]
GT++

**Comment by Dream-Master** [comment]
@draknyte1 any idea ?

**Comment by johnch18** [comment]
I'm on 2.0.8.6, this is still an issue. Would be nice if this were to be fixed.
