### ISSUE TITLE
GT++ Large Sifter Control Block tooltip is wrong

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/GT-New-Horizons-Modpack#4951]
#### Which modpack version are you using?
2.0.7.5-1.7.10
![image](https://user-images.githubusercontent.com/30208401/63552907-fd338b00-c506-11e9-8259-28b363d970aa.png)
There is no bonus outputs.

**Comment by KorGgenT** [comment]
posted issue on GT++ repo

**Comment by Dream-Master** [comment]
https://github.com/alkcorp/GTplusplus/issues/533

**Comment by boubou19** [comment]
looks like it was fixed at some point
