### ISSUE TITLE
Railcraft liquid fuel boiler deleting but not accepting fuels.

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/GT-New-Horizons-Modpack#4953]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Cells of liquid fuels that empty into the boiler firebox should add liquid to the firebox and burn into heat. Fuels that are accepted but just get voided include; Light fuel, heavy fuel, sulfuric light fuel, sulfuric heavy fuel, seed oil, 
#
#### What happened instead? (Attach screenshots if needed)
Liquid fuel is emptied from cells but does not enter the boiler fuel tank.

#
#### What do you suggest instead/what changes do you propose?
Disable these fuels from being just voided in the boiler if they aren't meant to work or allow them to actually enter the boiler tank and produce heat.

**Comment by stacra** [comment]
Still an issue on version 2.1.1.0, at least with seed oil and biodiesel. Playing on official server (Epsilon). It won't allow to pump it through pipes, but will void the fuel from liquid cells. Annoying part is that the quest for liquid-fuelled firebox says biodiesel is supposed to work well (which would be very nice if it did).

**Comment by bombcar** [comment]
Can you try actual iron buckets of fuel?

**Comment by stacra** [comment]
I don't think I can put biodiesel into bucket

**Comment by bombcar** [comment]
It might be possible using ender IO fluid tanks, let me experiment. Seed oil may work.

If the fuels that WORK can be bucketed and the ones that don't cannot, it's probably the underlying issue.

**Comment by stacra** [comment]
I'm also thinking the same thing. Also all of the fuels that work have fluid entries in NEI too.

**Comment by stacra** [comment]
Ok it seems railcraft boiler does it with all of the cells. So it might be an issue with biodiesel simply not being added as a boiler fuel.
In which case it should be either added or remove it from the quest description (and add a warning that the boiler will void any liquids from cells).

**Comment by ToastedEggplant** [comment]
Was this issue closed just because no one ever commented on it? I wonder how many other issues still exist that weren't fixed but were just closed.

**Comment by mitchej123** [comment]
> Was this issue closed just because no one ever commented on it? I wonder how many other issues still exist that weren't fixed but were just closed.

If they are important someone will reopen them or comment on them.

**Comment by stacra** [comment]
https://github.com/Railcraft/Railcraft-API/blob/f86190ff95d5dc69b3b24fcc4752404528874b48/mods/railcraft/api/fuel/FuelManager.java
Should be helpful if anyone wants to do it
