### ISSUE TITLE
Wooden fluid pipe crafting in Assembler give crafting table

### ISSUE THREAD

**Issue by Moogrok** [GTNewHorizons/GT-New-Horizons-Modpack#4956]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Own private server
#
#### What did you try to do, and what did you expect to happen?
I tried to craft wooden fluid pipes in the Assembler; 3 wooden planks, refined glue and Programmed Circuit 4. I was expecting 4 wooden fluid pipes.
#
#### What happened instead? (Attach screenshots if needed)
I got 1 crafting table for 4 wooden planks (no refiend glue used)
#
#### What do you suggest instead/what changes do you propose?
Please fix the recipe. :)

**Comment by observeroftime02** [comment]
![image](https://user-images.githubusercontent.com/43228249/63658059-77a91880-c75c-11e9-9789-d0160e5c83ce.png)
It crafts correctly? Were you using the right type of planks?

**Comment by Moogrok** [comment]
I'm still in LV, don't have those fancy planks. And the recipe shows the planks i used. I also couldn't find a recipe for craftingtables using planks (But that might be my mistake).

**Comment by Dream-Master** [comment]
@richardhendricks wooden plates would be better because the similar to iron plates. 
recipe need this plates and a control circuit.

**Comment by Moogrok** [comment]
I'm using planks made from wood pulp (made in the compressor) with the correct circuit. 
Do i need to add screenshots to clarify?

**Comment by Dream-Master** [comment]
please

**Comment by Moogrok** [comment]
Ofc I will help! The pack is amazing! Im just happy to be able to give something back.

Below are two pictures. The first one shows what happen when i put in 4 planks (I did put in a full stack the first time, thats how i noticed the problem). The chip is Config 4, it does not use any refined glue.
Picture two is what happens when i put in 3 planks in, its taken straight after the first picture. No operation.
It's and LV assembler. The Refined Glue is from centrifuged Sticky Resin. The planks is macerated oak, into pulp, and then compressed into Wood planks.

My NEI shows the "Correct" recipes, ie. the ones in @observeroftime02 post.

![Assembler_Planks](https://user-images.githubusercontent.com/2915078/63807828-d1f1d700-c91e-11e9-9572-e9ab4df69280.png)
![Assembler_Planks2](https://user-images.githubusercontent.com/2915078/63808254-cfdc4800-c91f-11e9-90cc-8b9a7b95dca9.png)
