### ISSUE TITLE
Stemcells recipe does not work in single block chem reactor

### ISSUE THREAD

**Issue by observeroftime02** [GTNewHorizons/GT-New-Horizons-Modpack#4959]
I'm on 7.5

Trying to make Stemcells from Raw growth medium does not work in the single block chem reactor, despite a recipe existing for it.

The recipe:
![image](https://user-images.githubusercontent.com/43228249/63748218-cbe7f180-c85d-11e9-8ed0-9358ff68d8ab.png)

My results in a LuV Chem reactor:
![image](https://user-images.githubusercontent.com/43228249/63748256-dd30fe00-c85d-11e9-9e29-53d378108f21.png)

Nothing. Yes it's powered. No, there aren't any invisible items like Air in any of the inputs. The recipe works in the LCR, but not in the single block. I suggest either removing the single block recipe, or making it work properly. Not sure what the issue could be here.

**Comment by Josh5minus1** [comment]
Try to use the raw growth medium cell instead of fluid itself

**Comment by observeroftime02** [comment]
That did not work
