### ISSUE TITLE
New unofficial GT NH server

### ISSUE THREAD

**Issue by Lardyking** [GTNewHorizons/GT-New-Horizons-Modpack#4960]
#### Which modpack version are you using?
Official GT NH latest version (only ekstra mods are serverside - backup and sethome addon)

Server IP: gtnh.ajes.dk:25566
Whitelist: yes
Contact for whitelist: Lardy#2889 or Ajes#7852 on discord - also on the official discord.
Server started 18/08 2019.

**Comment by Lardyking** [comment]
Dreammaster told me to put this here. I obey hos command and guidance at all times. We have a history. Sorry if I offended you in anyway.

**Comment by Dream-Master** [comment]
@bigbass1997 I ask for an issue so I think in this case it is ok @Lardyking

**Comment by Lardyking** [comment]
Location is DK/EU - language on server is English (main) but talk in Danish/German/Swedish is allowed

**Comment by Dream-Master** [comment]
@Lardyking are the server removed or ip is changed ?
Cant add it server offline.

**Comment by Dream-Master** [comment]
I spoke wit Ajes and Lardy and we add the server later.

**Comment by Prometheus0000** [comment]
I assume this was either added or not added already, I can't tell, since there's no server name?

**Comment by Dream-Master** [comment]
Guess the server have anothe rip or just closed

**Comment by boubou19** [comment]
can't reach the server inside of the multiplayer screen.

**Comment by Dream-Master** [comment]
@Lardyking feel free to reopen the ticket if the server still exists and sorry we dont add it earlier.
