### ISSUE TITLE
Sigil of Compression can skip Machine Compression

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#4961]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private Sever
#
#### What did you try to do, and what did you expect to happen?
Added Sigil of Compression to inventory
#
#### What happened instead? (Attach screenshots if needed)
Item is compressed such as Cobblestone, Gold, Iron.
#
#### What do you suggest instead/what changes do you propose?
Fix it.
This issue makes it easy to make BedRockium without TNT.

**Comment by Methes** [comment]
So the Sigil worked as intended and that's a bad thing somehow?

**Comment by Methes** [comment]
Never played with BM. How difficult is it to get the Sigil?
It requires player interaction and can't be automated.

**Comment by yukieiji** [comment]
@richardhendricks This sigil doesn't use Life Essence.

**Comment by boubou19** [comment]
the issue could be if it works with injections through player interfaces. If yes then you can hook up a cobble gen on the player interface and jackpot you have easy bedrockium.

**Comment by Dream-Master** [comment]
nerf incomming :P

**Comment by Dream-Master** [comment]
better Infinity

**Comment by mitchej123** [comment]
Please vote:
:+1: - Leave as is
:-1: - Some form of nerf

Personally I'm a fan of magic options/alternatives.

**Comment by AlexBucket** [comment]
Is it possible to modify the amount of LP it takes per compress?

**Comment by noobyaran9** [comment]
> Is it possible to modify the amount of LP it takes per compress?

`I:"Sigil` of Compression"=250

Its possible

**Comment by Dream-Master** [comment]
use more blood is a good idea and make the sigil a bit more expensive too. Not to bad i mean
