### ISSUE TITLE
Remove rotor disassembling from disassembler

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/GT-New-Horizons-Modpack#4970]
#### What did you try to do, and what did you expect to happen?
Currently, you can disassemble rotor that is close to broken and effectively getting 100% of the material back. If thats the case, whats the point of having durability on the rotors?

#### What do you suggest instead/what changes do you propose?
Remove disassembling rotor from disassembler. (Yay for more disassembler recipe removal.)
Proposed method of disassembling rotor:
Arc furnacing a so called broken rotor (basically what rotor turns into when they break or gets to 0 durability), will return you around 40%~60% (I don't know the specific number so please discuss on it) of the material cost for the rotor in ingot / nugget form.

**Comment by observeroftime02** [comment]
100% agree. The disassembling and reassembling of rotors completely negates any running cost turbines have. This seems like a loophole that should be fixed. What's the point of having a durability on the rotor otherwise?

**Comment by Canhos** [comment]
the energy cost to disassemble was a bit more then actually crafting one from scratch.. all you safe is the mats. you still have to monitor to ensure it doesnt totally break, and then wait the time to fix it. when i was doing this, many version ago, I too felt is was wrong, until i calculated the energy use.. this is the balance you seek. Because of this, i had fun messing with rarer turbines, as they were repairable.. much like they do in real life.

**Comment by noobyaran9** [comment]
> the energy cost to disassemble was a bit more then actually crafting one from scratch

Energy is not the problem, the problem here is the material used.

> i calculated the energy use

The energy use is just minor compared to what a rotor could possibly generate. 

> they were repairable

It's not suppose to use itself to repair itself. More material should be used to repair a rotor (If that were possible).

**Comment by observeroftime02** [comment]
It's not about the energy cost, but the cost of the material. I could make an infinity turbine, and use it forever without ever having to use new materials for it. That's clearly not right.

**Comment by sthegreat** [comment]
I think items with durability should remain disassemblable but their lost durability should impose a penalty on the disassembly returns. For example, there could be a multiplier of 1 - ((%used/100) / 5). In such a system a nearly broken rotor would return 80% as many materials as it normally would in a certain disassembler tier, a 50% rotor would return 90% as many materials as normal, a 75% rotor would return 95% as much, and only a pristine new rotor would return 100% as many materials as before.

**Comment by Dream-Master** [comment]
@sthegreat if you code that I am fine with it. I can only disable it.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/67752645-9ca75980-fa33-11e9-824e-ebd0236dfa62.png)
not working for me

**Comment by observeroftime02** [comment]
You have to use the rotor in a turbine first, for it to loose some durability. Then, and only then, can you disassemble it.

**Comment by Dream-Master** [comment]
ok i need someone with cosing knowledge to disable reverse recipes for turbines.

**Comment by observeroftime02** [comment]
Might have an idea how and where to do that. Not sure if it will mess anything up. I'll look into it when I get a free moment over the weekend.

**Comment by Dream-Master** [comment]
sure

**Comment by observeroftime01** [comment]
Done deal.

**Comment by Dream-Master** [comment]
@observeroftime02 did you test it?

**Comment by Dream-Master** [comment]
ok you did. sorry not read the text first

**Comment by richardhendricks** [comment]
We really need to do a turbine rebalance end to end. :D
