### ISSUE TITLE
Osmium and Ruthenium changes

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/GT-New-Horizons-Modpack#4974]
With Osmium and Ruthenium being the more rare materials at/for LUV, while removing Osmium from simple machine parts, these 2 materials still need to be used for crafting.

My current idea is to have Crystalprocessors eat Fine Osmium Wire in their recipes while using Ruthenium for Data parts and the Fusion Reactor.

**Comment by Dream-Master** [comment]
@Shattered2909 did you mean this recipe ?
![image](https://user-images.githubusercontent.com/2970688/67750079-c4e08980-fa2e-11e9-9445-2fe857ffa9b3.png)

i need more infos here. Thanks
