### ISSUE TITLE
[RFC] Platinum Group Slude Overhaul

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#4976]
As seen in the #vote channel on the Discord here the Suggestion Thread for it:

Preamble:
Platinum Group Slude = PGSD
related issue: #4885 
Graphs are CC-BY-SA taken from here and modified: https://en.wikipedia.org/wiki/Platinum_group#/media/File:PtMetalExtraction_II.jpg

Recipies Currently:
HNO3 + Chalcopyrite/Penlandite -> 1 Tiny Pile of PGSD
1 Pile of PGSD -> 1SiO2,1Au, 1Pt, 95% 3 Tiny Pile of Pd, 90% 3 Tiny Pile of Ir, 85% 3 Tiny Pile of Os

this basically boils down to either use a metric ton of HNO3 or pure ores, which is not an interesting mechanic, therefore i suggest changing this to a more reality based approach that is also interesting gameplay wise.

General Idea:
![new PGSD](https://user-images.githubusercontent.com/33183715/64070173-b4dd4100-cc5b-11e9-97fa-9afe9bd18d40.jpg)

This graph might look very complicated on the first look, but in reality is just a few recipe chains put together. Therefore i have split them into seperate chains, for easier understanding.

Every PGSD-Material can be made from any PGSD containg Ore. I.e. a Copper and Sulfur Compound or Iridium Ore. (where the CuS* compund would be worse production wise and the Iridium Ore would be compareable way better).

Platinum:
![Platin](https://user-images.githubusercontent.com/33183715/64070197-1f8e7c80-cc5c-11e9-8903-4f73fa9beb57.jpg)

Platinum Ores and Platinum Rich Compounds would not give out the "pure" Material anymore, but the "Pt Metalic Powder" which would be processed in a similar way like the TitaniumOxid in EV, but without the EBF.

Palladium:
![Palladium](https://user-images.githubusercontent.com/33183715/64070233-6b412600-cc5c-11e9-8ae3-fdbed78a4cd3.jpg)

Palladium would have the same approach as Platinum.

Ruthenium, Osmium and Iridium
![RuOsIr](https://user-images.githubusercontent.com/33183715/64070265-ca9f3600-cc5c-11e9-9827-36712902918a.jpg)

These Chains are relatively simple, and with increasing Tier, would require increasing demands, i.e. Iridium and Ruthenium would only require the EBF while Os would require a Distillation Tower aswell.

Rhodium
![Rhodium](https://user-images.githubusercontent.com/33183715/64070278-0d610e00-cc5d-11e9-8773-1edaed3a5b54.jpg)
Rhodium would be one of the most complex, but also one of the shortest, time wise, chains.

**Comment by observeroftime02** [comment]
I'd be interested in how demanding this is for input chemicals, and their potential recycling / restoration. If this could work on a somewhat lossy closed circuit, then this would indeed make it more interesting.

**Comment by EmeraldsEmerald** [comment]
What @observeroftime02 said, pretty much. All for it, perhaps with minor adjustments

**Comment by 0lafe** [comment]
My only complaints would really come from input:output ratios

**Comment by Ngar1** [comment]
interesting, but if something is added, it shoud also come out, may be in a dirty form (no easy treatment).
example: rh receipt : rhutenium sulfat -> + Zn = Crude Rhutenium 
and were is the Zn? should give as output also Zinc sulfide

**Comment by botn365** [comment]
it does give zinc sulfate

**Comment by observeroftime02** [comment]
![image](https://user-images.githubusercontent.com/43228249/66681347-6b531f00-ec27-11e9-8517-33d170788fac.png)

Zinc + Rhodium Sulfate Solution -> Zinc Sulfate + Crude Rhodium Metal Dust

**Comment by richardhendricks** [comment]
@bartimaeusnek I assume there will be some LCR recipes as well that do multiple steps?

**Comment by 0lafe** [comment]
In a single recipe? Seems kind of cheaty. Like having a multi that takes ore blocks and outputs dusts. You can put all the LCR recipes in a single LCR anyway

**Comment by mitchej123** [comment]
> In a single recipe? Seems kind of cheaty. Like having a multi that takes ore blocks and outputs dusts. You can put all the LCR recipes in a single LCR anyway

Circuit 24, kthx.  Higher tier, less annoyance.

**Comment by redmage17** [comment]
Output probably needs tweaked/increased before full release

**Comment by 0lafe** [comment]
>Circuit 24, kthx. Higher tier, less annoyance.

Wym higher tier?

**Comment by 0lafe** [comment]
>Output probably needs tweaked/increased before full release

Is there a general ore:dust ratio that exists? Or one that's being aimed for? Seemed like if anything it was pretty high already, like 2Ir/ore and half as Os or something?

**Comment by botn365** [comment]
most of the elements give enough if not too much i would say Ir,Rh and platinum are good
for palladium and ruthenium(if you go the steam cracker rout) it gives too much IMO the amount of osmium you get from PMP is good but you get too litle form osmium ore

**Comment by ScriptedPiky** [comment]
As far as I'm aware of for Iridium and Osmium (not sure about the others), Iridium Metal Residue dust that is obtained from Iridium byproducts and ore is a 1:1 ratio after processing. And Rarest Metal Residue from Osmium byproducts and ore is a ~1:10 ratio after fully processing.

**Comment by richardhendricks** [comment]
This is already in 2.0.8.0.  Any tweaks will be in 2.0.8.1.
