### ISSUE TITLE
Storage drawer script loading takes years

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/GT-New-Horizons-Modpack#4983]
#### Which modpack version are you using?
2.0.7.5

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/13598309/64469482-84b70600-d165-11e9-88d5-425f8cd5b434.png)

Storage drawer scripts takes more than a full minute to load from the server.
#
#### What do you suggest instead/what changes do you propose?

Move the recipe to core mod or remove all variant of drawers to keep it at a low amount because there is a shit ton of foreach loop in the script which makes it very slow.

**Comment by boubou19** [comment]
there is exactly 30 foreach loops

**Comment by ljjmrlion** [comment]
Is the loop slower than if we manually added each recipe? If someone wants to test I mean we could try that. I don't think we should remove the drawer variants but if there's a way to optimize the script that'd be alright.

**Comment by boubou19** [comment]
i reduced the number of 30 loops to only 5 loops: https://pastebin.com/Ts6P8bBe

**Comment by Dream-Master** [comment]
Guess when @bartimaeusnek put all redipes into code it loads much quicker. 
Sure the scripts loads so long because check all recipes.

**Comment by Dream-Master** [comment]
will be in code soon.

**Comment by richardhendricks** [comment]
@leagris is working on directly putting the recipes into the Drawers mod, and making all assembler recipes produce the vanilla drawer version. Players that want custom versions can then Chisel them. This reduces the load time and keeps the recipe map small. :+1:

**Comment by Prometheus0000** [comment]
The recipes were already put in code, just that the scroll bar doesn't work, so you can't make them all
