### ISSUE TITLE
Energy Module Ore Dict issue

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/GT-New-Horizons-Modpack#5002]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
ETA
#
#### What did you try to do, and what did you expect to happen?
I tried to make zpm lapotronic and I used previous tier of circuits
![image](https://user-images.githubusercontent.com/37113583/64780114-3d1aea80-d568-11e9-8b05-b86a009c9170.png)

![image](https://user-images.githubusercontent.com/37113583/64780096-342a1900-d568-11e9-9e7a-cc1ce1a97d22.png)

#
#### What happened instead? (Attach screenshots if needed)
It won't craft

#
#### What do you suggest instead/what changes do you propose?
add oredict to recipe

**Comment by barsikus007** [comment]
same issue with gravi chest plate

**Comment by barsikus007** [comment]
@Dream-Master 
I checked zpm lapotronic, and bug still exist

**Comment by repo-alt** [comment]
Probably the same circuit oredicting issue as  https://github.com/GTNewHorizons/NewHorizons/issues/5154
