### ISSUE TITLE
Teleportation bug

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5004]
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Attempted to use /back and /tpa in other dimensions and expected it to well teleport me.
#### What happened instead? (Attach screenshots if needed)
Nothing, didn't move or yield any errors the command just runs and then nothing happens after.
<img width="650" alt="Screenshot 2019-09-12 at 21 04 37" src="https://user-images.githubusercontent.com/54497873/64817091-f85f7580-d5a0-11e9-85e7-689970b2011d.png">

#### What do you suggest instead/what changes do you propose?
That it be fixed.

**Comment by Proficus** [comment]
I have this problem too. 3 or 4 times
Fix this problem please
![tp problem](https://user-images.githubusercontent.com/31763068/64895930-b0b31980-d686-11e9-978f-840cd8acd85d.png)

**Comment by barsikus007** [comment]
> This is a pretty serious bug as it can easily leave players stranded on other planets with no oxygen, seems to happen after I go to ceres primarily. However I used a waystone to teleport from ceres to ross and the same bug persisted so unsure what is the actual cause of this issue.

but shouldn't you fly home on a rocket?

**Comment by Proficus** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/31763068/65908245-b4f16d80-e3ce-11e9-88b7-d2b4e73601fd.jpg)
Teleport again not work!!!

**Comment by Proficus** [comment]
![1](https://user-images.githubusercontent.com/31763068/66248127-a935dc00-e72b-11e9-83e7-6e9ca0be30a5.jpg)
The problem again suddenly emerged and I cannot teleport

**Comment by Proficus** [comment]
https://clips.twitch.tv/OutstandingHelplessStingrayBrokeBack
Again not working-on stream

**Comment by Proficus** [comment]
![Not](https://user-images.githubusercontent.com/31763068/66315179-e8c41a00-e91d-11e9-92c2-e20214122934.jpg)
Today's game day started again with problems with the teleport

**Comment by Relvl** [comment]
I don’t understand English very well, but as far as I understand, miner operations interfere with teleporting? Maybe in this case, it’s better to fix the teleportation plugin? As my experience tells me, this is a better decision than banning or making a miner unworkable.

**Comment by Prometheus0000** [comment]
Same as  #4670 presumably

**Comment by boubou19** [comment]
Fixed as a side effect of having the perk to teleport instantly. To get this perk, grind to the Elite rank.

**Comment by Proficus** [comment]
> Fixed as a side effect of having the perk to teleport instantly. To get this perk, grind to the Elite rank.

Welcome to 2021

**Comment by boubou19** [comment]
Elite rank is easier to grind than you were used to before, as the money limit is now daily.

**Comment by GTNH-Colen** [comment]
An alternative solution I will mention here for archival sake and anyone looking at this in the future - you can use a block placer to place the machine controller then it will be assigned to a fake player and you can teleport freely with no issues.
