### ISSUE TITLE
Bandaid fixing Growth Medium and Bio Medium

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#5005]
What are these recipes and why are they such a problem? First, here are the three main recipes that cause the direst of issues when it comes towards balances and some reasonings as to why they're troubling. See https://github.com/GTNewHorizons/NewHorizons/issues/3852 for more information.

**Raw Growth Medium 1-3#**
Black Plutonium dust and Americium dust (ZPM+ tier materials), 500L of Radon. Outcome: 500L of Growth Medium.
![image](https://user-images.githubusercontent.com/41557212/64828588-fe902a80-d57d-11e9-8aab-941e4ffcbf32.png)
4 Nuggets of Ichorium, 1 Inert Pearl Fragment (IV~ level materials. Please note the Pearl Fragment can be made from Magic Essence or rather, Salis Mundus as an alternative), 16000L of Radon. Outcome: 16000L of Raw Growth Medium.
![image](https://user-images.githubusercontent.com/41557212/64828745-9beb5e80-d57e-11e9-8d04-3443a9e9acd5.png)
1 tiny pile of Cosmic Neutronium dust and Infinity Catalyst dust (UV-UHV+ materials), 32000L of Radon. Outcome: 32000L of Raw Growth Medium.
![image](https://user-images.githubusercontent.com/41557212/64828908-16b47980-d57f-11e9-9003-ba0258775bb3.png)

**Raw Bio Medium & Bio Stemcells**
16 Mysterious Crystal dust, Oriharukon dust, 4 Cosmic Neutronium dust, 1 tiny Infinity dust, 16 TCetiE-Seaweed Extract (this one is renewable), 4000L of Raw Growth Medium. Outcome: 4000L of Raw Bio Medium.
![image](https://user-images.githubusercontent.com/41557212/64829035-84f93c00-d57f-11e9-9a23-5ce2714206e0.png)
4 Stemcells (250 Raw Growth Medium total), 1 Mysterious Crystal Dust, 1000L of Raw Bio Medium. Outcome: 1 Biocells (32 are needed to make one CPU), 250L Mutagen. 

All of these recipes are widely criticized to be over the top ridiculous and makes very little sense in terms of balance & logic; overusing the high tiered materials such as Radon and tiny Infinity, these recipes are by far one of the most obnoxious, least enjoyable and most tedious recipes in the game. In addition, it was also found out that it took roughly around 117~ **Infinity ingots/dusts** just to get one UEV circuit. with the extra Bio Medium required even further for the Bio CPU's and circuit boards, it goes beyond the expected Infinity amount for a **single UEV circuit**. So, how do we fix this?

First off, revert Raw Growth Medium back to its original recipe.
**New Recipe:** Next, change the materials used in the Raw Bio Medium to as such: 16 Tceti E Seaweed Extract, 16 Europium dust, 8 Tartarite dust (note: this dust can be obtained through ores on Centarui A and Barnard), 6 Fluxed Electrum dust, 6 Cosmic Neutronium dust, 1 tiny Infinity dust, 20 cells of Growth Medium (20000L). Output: 20 cells of Bio Medium (20000L).
![image](https://user-images.githubusercontent.com/41557212/64915602-ba3c9000-d71f-11e9-989a-ad225a2a8345.png)

**Old recipe:** ~~Next, change the materials used in the Raw Bio Medium to as such: 8 TcetiE-Seaweed Extract, Mysterious Crystal dust, 4 CNaquadria dust, 2 Trinium dust, 1 Cosmic Neutronium dust, 1 Infinity Catalyst, 16000L of Raw Growth Medium. Output: 1 returned Infinity Catalyst at a 90% chance, 16000L of Raw Bio Medium.~~
![image](https://user-images.githubusercontent.com/41557212/64829840-d22add00-d582-11e9-9e2b-a1792e811ac2.png)

Change the Biocell recipe to as such: 64 Stemcells, 16 Unknown Crystal Shard or Mysterious Crystal dust, 4000L of Raw Bio Medium. Output: 32 Biocells, 4000L Mutagen.
![image](https://user-images.githubusercontent.com/41557212/64830160-0357dd00-d584-11e9-973c-57ba9085018f.png)

What this does is HEAVILY reduces the overall tedious and dumb aspect of the entire Seaweed problems that many people have had and complained about. These are some very simple recipes that can be changed quite easily, only requires a few lines to be adjusted/changed, simple & makes the majority of the community happy.

**Potential arguments**
-"Doesn't the new renewable seaweed fix this issue?"
Yes and no. While it fixes renewable problems, it does not address the on-going issue of making the Bio Medium and Bio circuits themselves with their absurdly high running costs.

-"Shouldn't we make a new reworked recipe instead of a bandaid fix?"
That is true and is perfect for the long run. However, the current recipes are practically on the verge of being broken & insane. People have long complained in the Discord and on GitHub to fix these recipes. We all are requesting a bandaid fix at the very least to help fix this dumb issue.

**Comment by ScriptedPiky** [comment]
Adjusted the overall costs of the Bio Medium recipe a tiny bit along with some math and numbers.
Left side:
**Bio Medium**: 16 Tceti E Seaweed Extract, 16 Europium dust, 8 Tartarite dust (note: this dust can be obtained through ores on Centarui A and Barnard), 6 Fluxed Electrum dust, 6 Cosmic Neutronium dust, 1 tiny Infinity dust, 20 cells of Growth Medium. Output: 20 cells of Bio Medium (20000L).
Biocell recipe is unchanged.

Right side:
Recipes and place holders for me at the given time.
![image](https://user-images.githubusercontent.com/41557212/64915192-c07a3e80-d716-11e9-93c1-e6f3052362c7.png)

Please note: It takes around 1 tiny infinity per 4 Bio ZPM circuits. It will also take almost ~3 tiny infinity per UEV circuit. In total, you require 45740L of Bio Medium for one UEV circuit roughly.

In total, this requires a total of 3 processes; 60000L of bio medium, 48 seaweed, 48 europium, 24 tartarite, 18 fluxed electrum, 18 cosmic neutronium, 3 tiny infinity on average to get one UEV circuit with leftover Bio Medium of course.

**Comment by Dream-Master** [comment]
Add the recipes to Bartworks is maybe a idea too. Bio vat fits better than gt devices. Or maybe a combination of both.

**Comment by Dream-Master** [comment]
Add the recipes to Bartworks is maybe a idea too. Bio vat fits better than gt devices. Or maybe a combination of both.

**Comment by Prometheus0000** [comment]
These have already been changed, so this should be closed.
