### ISSUE TITLE
map crafting throwing null ref exception & can't zoom map out

### ISSUE THREAD

**Issue by RossSoft** [GTNewHorizons/GT-New-Horizons-Modpack#5008]
#### Which modpack version are you using?
2.0.7.5
#

#### If in multiplayer; On which server does this happen? 
We host our own server
#

#### What did you try to do, and what did you expect to happen?
Issue 1:
Placing 8 paper and one compass in the AE2 ME system to craft a blank 'map'.

Issue 2:
Placing 8 paper around a map that has already had map data written to it in a crafting grid in order to zoom the map out (i.e. increase grid size) 

#
#### What happened instead? (Attach screenshots if needed)

Issue 1: (Map crafting)
No map is crafted and the following message is displayed:
Error: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: java.lang.NullPointerException

NOTE: The map can be crafted if you place the items manually in the grid, but the compass is transferred out of the ME system and into the players inventory when you grab the map out of the output window.

Issue 2: 
The zoomed out map cannot be crafted. (I need a zoomed out map for a recipe for an opencomputers 'navigation upgrade' for crafting robots)
#

#### What do you suggest instead/what changes do you propose?

As issue 1 is causing an exception, I thought you should know about it.

Resolving issue 2 would allow robots to be used in the areas needed by the player.  At present I would need 4 separate robots doing the same task as the map borders cross through our base.

Other than this, I gotta say this is one fantastically brilliant modpack. Well done all, we are around 6 months in and loving it so far!

**Comment by speckbrot** [comment]
https://ibb.co/tLy83qX
https://ibb.co/f0BCWsT
https://ibb.co/Y7VBT2F

**Comment by speckbrot** [comment]
There is no way to increse the map size for the navigation upgrade for drones or robots, and autocrafting the map with the me system results in a error message.

**Comment by Dream-Master** [comment]
@DeForce any idea if this can be fixed ?

**Comment by repo-alt** [comment]
The crash seems to be gone, but the zoomed out map is still not craftable
