### ISSUE TITLE
Change Zeron-100 to Nitinol 60 in wiremill multiblock (LuV -> IV)

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5012]
Currently Zeron-100 requires an LuV voltage to process in the alloy blast furnace (As well as solidify), this causes the wiremill multiblock to become LuV which doesn't really fall in line with the rest of the multiblocks. In addition everything else in the recipe including the wire factory casing only require IV so requiring it for 4 plates seems a bit odd.

<img width="348" alt="Screenshot 2019-09-14 at 23 26 23" src="https://user-images.githubusercontent.com/54497873/64914423-22ec3280-d749-11e9-899e-26807af01750.png">

<img width="346" alt="Screenshot 2019-09-14 at 23 26 16" src="https://user-images.githubusercontent.com/54497873/64914424-22ec3280-d749-11e9-9d4f-55d98f4e66c0.png">

EDITED: I was being dumb and have subsequently opted to push for a change in the material instead of a change of the voltage requirements for Zeron-100.

**Comment by observeroftime02** [comment]
The GT++ Wiremill is essentially gated behind the assembly line, and I think that was a decision made on purpose. 

Also, why would you change the entire alloy (a LuV tiered material) to IV, instead of simply changing the alloy the wiremill is made from to the GT++ IV tier alloy (Nitinol)? Moving that material down a tier would break the tiering of a few recipes (namely energy buffers). That seems far more bothersome than changing the material used to make the wiremill.

**Comment by botn365** [comment]
here is the right place to complain about it
https://github.com/alkcorp/GTplusplus/issues

**Comment by observeroftime02** [comment]
Well, as far as changing the material the wiremill is constructed from, this can be done in the core mod no problem, though I don't really see the reason for it since it seems okay at LuV.

**Comment by GTNH-Colen** [comment]
> The GT++ Wiremill is essentially gated behind the assembly line, and I think that was a decision made on purpose.
> 
> Also, why would you change the entire alloy (a LuV tiered material) to IV, instead of simply changing the alloy the wiremill is made from to the GT++ IV tier alloy (Nitinol)? Moving that material down a tier would break the tiering of a few recipes (namely energy buffers). That seems far more bothersome than changing the material used to make the wiremill.

Good point, I honestly just overlooked that possibility of changing the material itself instead (I'm dumb). In regards to the requiring of an assembly line that doesn't seem accurate from the recipe? Unless you're referring to something else?

<img width="348" alt="Screenshot 2019-09-14 at 23 26 23" src="https://user-images.githubusercontent.com/54497873/64914330-1535ad80-d747-11e9-8d1b-5bf175dcd530.png">

<img width="346" alt="Screenshot 2019-09-14 at 23 26 16" src="https://user-images.githubusercontent.com/54497873/64914331-1535ad80-d747-11e9-8b5d-e4620929fb42.png">

I don't understand the logic behind gating this one multiblock behind LuV though when many other highly convenient ones become available here such as the industrial material press, cutting factory, mixing machine etc. Just seems to stand out weirdly, especially since the actual recipe of the wiremill only needs IV components bar 4 plates.

**Comment by observeroftime02** [comment]
You do need the assline to make the LuV energy hatch, which is needed for the ABS to make that Alloy (I'm actually not sure if you can just mix the dust in a blender and then EBF it though, if you can then that's a moot point).

**Comment by botn365** [comment]
there is no mixer recipy

**Comment by GTNH-Colen** [comment]
> You do need the assline to make the LuV energy hatch, which is needed for the ABS to make that Alloy (I'm actually not sure if you can just mix the dust in a blender and then EBF it though, if you can then that's a moot point).

Ah I see what you were referring to now, that makes more sense. I was mostly referring to the actual recipes itself, with this change it would obviously no longer require the assline but in all honesty I don't see that as a problem. It's my opinion that this multiblock is on the same level  as the industrial material press so why it's locked behind so much seems odd.

Honestly the main reason I made this entire thread was because of the fact that it seemed like an oversight that the zeron-100 actually needed LuV to process as I can't really get why this has to be so heavily gated.

**Comment by Dream-Master** [comment]
@GTNH-Colen make a gt++ issue please. 
https://github.com/alkcorp/GTplusplus/issues
Thanks
