### ISSUE TITLE
Charm of Keeping 1 crashing server

### ISSUE THREAD

**Issue by ETx13** [GTNewHorizons/GT-New-Horizons-Modpack#5018]
Whenever I die with a Charm of Keeping 1 the server crashed and the grave doesn't spawn and I lose all my stuff. Someone else had a Charm of Keeping 2 and it worked fine. So there's a big problem with 1.

**Comment by draknyte1** [comment]
Got a log file or something?
We literally can’t do anything with this report otherwise..

**Comment by Dream-Master** [comment]
@ETx13 we need more infos and log files.
If i get no infos i close this issue.

**Comment by richardhendricks** [comment]
@ETx13 Update?

**Comment by dvdmandt** [comment]
So this was almost certainly the same issue as #5619 which was fixed by this commit to the TF repo: https://github.com/GTNewHorizons/twilightforest/commit/34d2a106d7108c1f89bb157800dfe835d18524ba

**Comment by Dream-Master** [comment]
@jss2a98aj can you check this too?

**Comment by jss2a98aj** [comment]
This is a duplicate of issue #5619 which I fixed.
