### ISSUE TITLE
Bonsai Tree Crops for Thaumcraft and maybe wichery trees

### ISSUE THREAD

**Issue by speckbrot** [GTNewHorizons/GT-New-Horizons-Modpack#5024]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Privat
#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Would be cool to have more bonsai tree crops from the magic mods

**Comment by richardhendricks** [comment]
Since we can purchase the thaumcraft trees with coins, I am OK with this, but we should tier them up a bit more than the vanilla trees.

**Comment by Prometheus0000** [comment]
Is there a reason to need bonsais of these trees? You don't need more than a stack or so of wood from any of these trees. More useless crops means less probability to get useful ones, and they're hard enough to get. I'd rather have an obsidian plant than 5 more useless types of wood.
