### ISSUE TITLE
Arcane Infusion crafting of Wand Augmentation Vis Channel impossible

### ISSUE THREAD

**Issue by speckbrot** [GTNewHorizons/GT-New-Horizons-Modpack#5028]
#### Which modpack version are you using?
2.0.7.5

#### If in multiplayer; On which server does this happen? 
Private Server

#### What did you try to do, and what did you expect to happen?
Arcane Infusion crafting of Wand Augmentation Vis Channel impossible allways starts Wand Aumentation Tainted Core and keeps ignoring the 2nd quick silver and thaumium bar and keeps draining essentia out of the me system until you either run out of the essentia or replace them with Tainted Tendril and Tainted Goo.  Tried the recipe several Times and it always defaults to the Tainted Core Augment 

#### What happened instead? (Attach screenshots if needed)
https://ibb.co/r0NWGvS
https://ibb.co/Hhy7qSV

#### What do you suggest instead/what changes do you propose?
Change the reciepe for both recipes that the recipes are more different or fix the problem with the script

**Comment by drayath** [comment]
As a quick note, if you do not have (or unlearn with a command) the 'Wand Augmentation Tainted Core' research the Vis Channel infusion works.

**Comment by Dream-Master** [comment]
@speckbrot the recipes are never changed because so far i know not possible via script. To many wand combination are needed. I can look what i can change in code.

**Comment by Dream-Master** [comment]
@speckbrot sorry no source found. If no one decompile the mod and change it we cant change anything.

**Comment by Dream-Master** [comment]
@speckbrot 
we could change the aspect using in the recipes. Did this help ?

**Comment by KiloJoel** [comment]
Suggestion: Disable that research or recipe completely. If either is possible, this will fix the problem. I'm not sure exactly what the augmentation does but I suspect essentially nobody wants it anyway.

**Comment by GTNH-Afx237v7** [comment]
I can have a look tomorrow, see if I can be of any help.

**Comment by Prometheus0000** [comment]
Does anyone have any idea how to clear a research a player has already learned though the MT script? Because removing the research prevents the problem in a new world, but not an existing one. I thought the refresh might work, but it does not. And since the result is variable, I can't just remove the recipe by the result either.
```
// --- Tainted recipe conflict stuff
mods.thaumcraft.Research.orphanResearch("@WAND_AUGMENTATION_TAINTED_CORE");
mods.thaumcraft.Research.removeResearch("@WAND_AUGMENTATION_TAINTED_CORE");
// -
mods.thaumcraft.Research.orphanResearch("@WAND_AUGMENTATION_TAINT_CAPPING");
mods.thaumcraft.Research.removeResearch("@WAND_AUGMENTATION_TAINT_CAPPING");
// -
mods.thaumcraft.Research.refreshResearchRecipe("@WAND_AUGMENTATION_TAINTED_CORE");
mods.thaumcraft.Research.refreshResearchRecipe("@WAND_AUGMENTATION_TAINT_CAPPING");
```
