### ISSUE TITLE
Garden Portal from Utility words - internal server error

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/GT-New-Horizons-Modpack#5033]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Epsilon, have not tested on others
#
#### What did you try to do, and what did you expect to happen?
Attempted to forcibly change OW garden dim location (as OP), by placing a fresh unlinked portal
and Shift+RMB where i should get a GUI to link it to the desired Garden dim
#
#### What happened instead? (Attach screenshots if needed)
Instant disconnect with Internal Server Error, every time
#
#### What do you suggest instead/what changes do you propose?
Fix if possible.
 
note: Players change bases, it would be nice to simply relocate their portals when needed.

**Comment by mitchej123** [comment]
Any logs or stack traces you can provide?

**Comment by MrWye** [comment]
This is all i get in the log when client disconnects, there is no crash so no crash log is generated
https://prnt.sc/pdautk

**Comment by mitchej123** [comment]
Anything of note server side?

**Comment by MrWye** [comment]
bart posted this, he tested on single player
bartimaeusnekToday at 5:56 AM
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
   at zarkov.utilityworlds.UW_PortalBlock.func_149727_a(UW_PortalBlock.java:112)

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea on this issue
@mitchej123
