### ISSUE TITLE
Add new recipes for storage cell from AE2/EC

### ISSUE THREAD

**Issue by Spartak1997** [GTNewHorizons/GT-New-Horizons-Modpack#5041]
Hello, guys! So, I have an idea about change and add recipes for storage cells.
The higher tier of a machine, the cheaper recipes of cells.
![image](https://user-images.githubusercontent.com/29407630/66158515-b620d580-e62e-11e9-832f-ade18cbf4d6a.png)
![image](https://user-images.githubusercontent.com/29407630/66158589-da7cb200-e62e-11e9-8b42-5dab8f5e4fcb.png)
![image](https://user-images.githubusercontent.com/29407630/66158636-f84a1700-e62e-11e9-964a-553acefae807.png)

Pull Request: https://github.com/GTNewHorizons/NewHorizons/pull/5040

**Comment by Cinobi** [comment]
One more assembler with unique circuit, aww. Sounds pretty well though.

**Comment by barsikus007** [comment]
Maybe this is 1 or 2 or 3 or 8 or 9 circuit?

**Comment by barsikus007** [comment]
anyway we need 12 slots now
