### ISSUE TITLE
HSLA Steel Proposal & more additional content for this alloy

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#5057]
What is HSLA Steel and what does it do? What is its purpose? HSLA Steel is an alloy that and I quote, "type of alloy steel that provides better mechanical properties or greater resistance to corrosion than carbon steel." Quoted via [Wikipedia](https://en.wikipedia.org/wiki/High-strength_low-alloy_steel). With this in mind, we can conjure up a few ideas. One is a better fluid piping alternative that allows for a potential fluid pipe at EV level (due to the Titanium requirements inside) and can possibly be used in EV machines or multiblocks or other recipes to increase difficulty and creativity.

HSLA Steel does indeed have a recipe as shown below. However, it has no uses whatsoever, yet the potential of this alloy can serve greatly for creatively difficult recipes if done correctly.
![image](https://user-images.githubusercontent.com/41557212/67154787-c683b200-f2b6-11e9-8f3a-3f1ee2d5365a.png)

Here is what I propose. First off, touch upon the EBF recipe itself (see below for current recipe) by increasing the voltage input from 120 EU/t (MV) to 480 EU/t (HV) and increase the coil requirement from 1000K (Cupronickel) to 3600K (Nichrome). Leave the time as it is currently (100 seconds). Have a freezer requirement, with the freezing time being 7.35 seconds at 480 EU/t (HV). See below for the unused freezer recipe as well.
![image](https://user-images.githubusercontent.com/41557212/67154812-0cd91100-f2b7-11e9-98a5-a98a9ec85c5e.png)
![image](https://user-images.githubusercontent.com/41557212/67154852-97ba0b80-f2b7-11e9-8a49-f0dbf235792e.png)

Now, what are the possible applications? There are some thoughts that this could replace certain wand/scepter recipes. For example, imagine the Thaumium Wand Cap and that it requires Titanium Screws. However, replace the Titanium with the HSLA Steel alloy and we get a recipe that concludes an interesting recipe that still retains the same main requirements, that being Titanium, while still creating a somewhat challenging and quite fun recipe. This can also possibly serve as replacing the Stainless Steel in some of the EV recipes like the pump for example.
![image](https://user-images.githubusercontent.com/41557212/67154932-0c417a00-f2b9-11e9-8a67-5d146cd3add5.png)

Take it for example that Molybdenum and Niobium are rather difficult to obtain in large quantities at first. The same goes for Gallium in some sense, where Gallium comes in scarce resources, Molybdenum and Niobium are rare to find. What ends up happening is one of two things: The player already has both rare resources before progressing 🎉 Or the player will need to find one or both of the resources in order to progress. Not only does this passively tell them to get the resource, but it will also serve as a sign that you will need these resources for future progression (GT++ alloys, Niobium-Titanium, and so on).

**Comment by AiramProvoker** [comment]
I can't say "no" to a useless alloy being less useless. Your propositions seem thought out. 
I also like "alternative" recipes like with the pump. It'd be interesting if every tier had such an "alternative" main metal/alloy (stainless-ultimet, titanium-HSLA), but I suppose it's too much work and hard to balance.
When it comes to TiCo, vanadiumsteel, which the player can get as early as MV, has extremely high stats. HSLA or maybe some other complicated alloys are more worthy of the godlike stats VS has.
