### ISSUE TITLE
assembling line does not want to consum eitems

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5060]
#### Which modpack version are you using?
7.6d
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What do you suggest instead/what changes do you propose?
whent rieng to make items with the assembling line it will make the item but will not consume the items needit to make it so it will infinitly make it.
this does not happen with evry item that needs to be made with the assembling line from al the recipys that i tested the
ZPM energy hatch,ZPM dynamo hach and lapotronic energy orb cluster
things like ZPM pump or LuV energy hatch dont seem to have this problem
the difrents i see between these item is that the ones whre it does not get consumed are ZPM voltage while the other are LuV and below

**Comment by Dream-Master** [comment]
@bartimaeusnek did you lastest fix a recipe will not start if the tier not match cause this issue ?

**Comment by botn365** [comment]
i dit some testing
if your using 2 energy hatches to upvolt the assembling line and you make a recipy that needs the the upvoldet recipy it wil not consume the items

if you have 2 IV energy hatches a Luv motor wich need IV wil consum the items on crafting
but a ZPM motor wich needs LuV voltage wil not consume items on crafting

**Comment by Dream-Master** [comment]
@botn365 can I send you a file with and without a small fix to test out if this happens again ?

**Comment by botn365** [comment]
sure

**Comment by Dream-Master** [comment]
[GT-test.zip](https://github.com/GTNewHorizons/NewHorizons/files/3782144/GT-test.zip)
@botn365 

333 is without the fix and 336 the newest GT Version. Please test both version and repot it here. 
Thanks

**Comment by botn365** [comment]
the problem is not there on 333
the problem is there on 336

**Comment by richardhendricks** [comment]
@Dream-Master @botn365 Any progress?

**Comment by Dream-Master** [comment]
@botn365 did you test thus in-game ? I am  very busy with rl stuff rn.

**Comment by Prometheus0000** [comment]
Does this still happen?
