### ISSUE TITLE
AE2 Fluid interfaces malfunction after upgrade.

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#5069]
#### Which modpack version are you using?
GTNH-1.7.10-2.0.7.6e-dev.zip

#
#### If in multiplayer; On which server does this happen? 
Private

#
#### What did you try to do, and what did you expect to happen?
Upgraded from 2.0.7.5 to GTNH-1.7.10-2.0.7.6e-dev.zip

All existing AE2 fluid interfaces with a fluid output set have the fluid output type replaced with some sort of bad fluid type (different color than the original fluid, tooltip shows no name, no fluid outputted)

You then need to go round you base working out all the correct fluid output type and resetting the output filter.

In addition previously when in the fluid interface ui the tooltip (on each column) showed which face of the interface the fluid would output to (north, up, west etc) this is no longer shown.

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Upgrade should not break existing setting if at all possible.
Return the UI output face tooltip as it is extremely useful.

**Comment by Dream-Master** [comment]
So far ik Fluids have no fix id thats why it happend most of the time when a updates come. Idk if somone can help me code a fix if it is fixable.

**Comment by richardhendricks** [comment]
I think for GT devices @mitchej123 added a method to save/restore fluids using strings instead of fluid IDs. Guess AE2 doesn't do it that way.

**Comment by Dream-Master** [comment]
Maybe @DeForce can help us here?

**Comment by observeroftime01** [comment]
Mitch did fix SFM so that the fluid is stored as a string rather than by ID that prevents this very problem from messing up your SFM setups. Works great by the way. Not sure if the same fix can be applied to EC2 stuff, would be nice for sure.

**Comment by DeForce** [comment]
I'll investigate, but there should be no "fluid mixup" things between the versions, only if moved from old version that broke liquids

**Comment by drayath** [comment]
Just done a search on my base, all ae2 'fluid export buses' and 'fluid storage buses' seem to be fine (they have correctly retained their fluid filter type)

It seems to be just the 'fluid interfaces' that have issues.

**Comment by DeForce** [comment]
@drayath thank you, I'll check why that could be happening

**Comment by drayath** [comment]
Likely a similar issues but the Gregtech Fluid Filter covers also appear to lose there fluid filter type on game upgrade.

**Comment by mitchej123** [comment]
The cover issue has already been resolved

**Comment by richardhendricks** [comment]
Still need help on the ExtraCells 2 issue

**Comment by Dream-Master** [comment]
@DeForce can you help us here please. thanks
