### ISSUE TITLE
Cannot reliably place IC2 crop sticks on farmland or garden soil

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5070]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Trying to place the crops, cannot place them.
#
#### What happened instead? (Attach screenshots if needed)
First cropstick places, but then any additional will show as placed, then disappear and come back into inventory.
![2019-10-30_21 22 27](https://user-images.githubusercontent.com/1214811/67913580-8c8a9980-fb5b-11e9-9553-ed595b4115ff.png)
![2019-10-30_21 22 28](https://user-images.githubusercontent.com/1214811/67913581-8c8a9980-fb5b-11e9-9c61-d71fa062fe29.png)

#
#### What do you suggest instead/what changes do you propose?
Please fix. Not sure why it's happening.

**Comment by Soulstealer86** [comment]
I'm noticing the same problem at my base. Anytime I try to place a crop, it reappears in my inventory, and I don't know how to correct it.

**Comment by boubou19** [comment]
it's a known bug on the live servers: sometimes even a reboot can't fix this. A workaround is to plant the crops in another dim such as the twilight forest.

**Comment by richardhendricks** [comment]
Really?  I didn't see anything when I searched for it.

**Comment by boubou19** [comment]
it was first reported in #3841 iirc. It's totally random, appears for a couple of restarts then it's gone. My guess is that somehow mytown is messing with the crops.

**Comment by richardhendricks** [comment]
Well, it shouldn't have been closed if it wasn't resolved. 😒

**Comment by Waisse** [comment]
This issue still exist btw, it's happening on Epsilon. Can't plant anything in our town unless we hold r click for a minute and even that doesn't guarantee it'll place it down.

**Comment by MrWye** [comment]
Crop sticks can be placed every 15-20 seconds. Outside of a town issue still persist, so its doubtful mytown is messing with it. Almost feels like there is some sort of config that was set on a timed cooldown for placement.

**Comment by boubou19** [comment]
mytownadmin can set flags for the wilderness so this why i say that mytown can be related to this. It reminds me not able to use a tc wand with wand focus time to set the day in a wild chunk because i first used it in a town where i could not use it.

**Comment by Prometheus0000** [comment]
So, thermos again?

**Comment by boubou19** [comment]
it definitely did not happened since couple of monthes, so i think we can close this. I will reopen it if it happens again, but there is not much we can do as no one was ever able to reproduce it on purpose.

**Comment by NeroOneTrueKing** [comment]
Currently having this issue on a non-official server, not using MyTown or anything of the like. Restarting the server once has not resolved the issue. Placing the cropsticks in the twilight forest works. No idea what caused it to start happening.

**Comment by boubou19** [comment]
does it run on a non forge minecraft server?

**Comment by NeroOneTrueKing** [comment]
It's running on a forge server, I'm told.

**Comment by NeroOneTrueKing** [comment]
Update: cropsticks are now placeable again, with seemingly no reason; approx 1 day of realtime after the issue first started happening.

**Comment by NeroOneTrueKing** [comment]
Update: issue continues to occur when opening the world in singleplayer.

Is there anything I can do to help test this / narrow down the cause?
