### ISSUE TITLE
[Official servers] Hunter /jobs doesn't register evolved blazes

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#5094]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Roaming Mercury, shooting mobs for fun and profit
#
#### What happened instead? (Attach screenshots if needed)
The collected XP for the hunter jobs increased for all naturally spawning mobs on Mercury, except evolved blazes.
#
#### What do you suggest instead/what changes do you propose?
Evolved blazes should be added to the jobs index

**Comment by boubou19** [comment]
closing this, as only vanilla mobs are supported by the jobs plugin
