### ISSUE TITLE
1.12 Concrete Back Port (Mod Recommendation)

### ISSUE THREAD

**Issue by itsmekasta** [GTNewHorizons/GT-New-Horizons-Modpack#5095]
Hey guys, 

I'm playing with 1.12 Concrete Back Port mod for about 700 hours on SP.

I think we all love aesthetics and the 1.12 concrete blocks, in all the colors, are adorable and I heard from so many people, that they really like the blocks.

If we add this mod, we could import into a ZS with a machine like an Assembler or something.

On 1.7 we only have the blocks, powder/final blocks, so no stairs, slabs, fences, fence gates, **but** we could import it to Microblocks like I did in the config.

So if you guys need the config file, I would like to help you if you want. :)

https://www.curseforge.com/minecraft/mc-mods/concrete-mod

Best wishes
Kasta

**Comment by bartimaeusnek** [comment]
It's ARR (all rights reserved) therefore we can not fix it easily if it makes problems. Im against it.

**Comment by itsmekasta** [comment]
EDIT: here the git.
https://github.com/D-prog-55/ConcreteMod/tree/MC1.7.10

**Comment by draknyte1** [comment]
> I think we all love aesthetics and the 1.12 concrete blocks
Assuming anyone playing GTNH has used or even cares for 1.12? Bahahaha,
Your suggestion is 100% redudant as it doesn't provide anything useful.

My memory seems to recall you'd even asked how to copy the GT concrete speed boost code to this mod, because the 1.7.10 fork of it doesn't add anything beyond useless aesthetics.

We have Concrete, we don't need infinitely more variations for the sake of colours. 
/2cents

**Comment by itsmekasta** [comment]
Totally understandable.

Thanks for the replies.

**Comment by richardhendricks** [comment]
Couldt we take the textures and just add new GT concrete blocks using those textures?

**Comment by bigbass1997** [comment]
@richardhendricks I don't even think we could add the mod to the pack, let alone steal the textures. Mod is listed under "All Rights Reserved" license; and no license (or readme) on the github repo. You'd have to get permission from the developer first to redistribute the mod or to take the textures. The former sounds a lot more doable.

**Comment by itsmekasta** [comment]
@bigbass1997 , he's using the official concrete texture for 1.7.

There are no extra blocks other than vanilla powder and concrete.

https://minecraft.gamepedia.com/Concrete

**Comment by richardhendricks** [comment]
That's what I mean, the texture are part of Forge for 1.12 right? I don't know the legalities of using them in our GT5u branch though, so it probably would be a no no.

**Comment by bigbass1997** [comment]
Well based on the source repo, he does have textures being [compiled into his mod](https://github.com/D-prog-55/ConcreteMod/tree/MC1.7.10/src/main/resources/assets/one_point_twelve_concrete/textures/blocks). So it's not quite like he's just applying textures already found in game to blocks he created.

If the textures are just copies from Minecraft, then we could use those the same way he did. However, any of the code he wrote, is still his. Just keep that in mind if you decide to copy the functionality into one of our own mods.

**Comment by richardhendricks** [comment]
I would just use available GT meta Ids and make them behave like GT concrete. I'd want an independant source for the textures, definitely.

**Comment by bartimaeusnek** [comment]
Best thing to do would be to just use the white conctrete texture from GT and make color shifts based on ID or NBT. [I do that with my glass in bartworks here.](https://github.com/bartimaeusnek/bartworks/blob/9f9fa04b609f02e779d8648022ce8bede48b5467/src/main/java/com/github/bartimaeusnek/bartworks/client/renderer/RendererGlasBlock.java#L82)
