### ISSUE TITLE
Lootgames lack of grave bug

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5100]
#### Which modpack version are you using?
2.0.7.5
#
#### What did you try to do, and what did you expect to happen?
Play the Lootgames game, not die, or have a grave spawn at least.
#
#### What happened instead? (Attach screenshots if needed)
It killed me, saying I was a cheater, presumably because there was oil flowing into the room, and it said the room needed to be clear or something. 
The main part is that a grave didn't spawn, and there was no associated grave or death file, so I couldn't restore my inventory with the command, so I had to roll back the whole world.
#
#### What do you suggest instead/what changes do you propose?
Talk to the mod author and get them to allow graves to spawn after killing you? Maybe put a warning in a quest?

**Comment by Dream-Master** [comment]
The Game warns 3 times. Not us fault you restart the game so often.

**Comment by Prometheus0000** [comment]
I didn't get a warning, it killed me when I was putting in the sequence the first time.

**Comment by Prometheus0000** [comment]
I just checked again, and it did give a warning after starting the game, my bad. It wasn't very obvious though (in the bottom left). The lack of a grave still sounds like a bug though.

**Comment by Dream-Master** [comment]
maybe a cfg option will be made to switch it off. No promise
