### ISSUE TITLE
Add craftable or quest-reward end portal blocks.

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#5104]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Make it possible to craft an end portal block? Obviously after you get to the end. Purely a quality of life thing so you can put the new portal wherever you want. Won't be butthurt if people say no to this but if anyone would like to give feedback on what such a recipe might look like I may just add it to my customization script for my own server.

**Comment by Dream-Master** [comment]
@shawnbyday are you able to harvest this blocks? If not its the same i add bedrock Block recipes.

**Comment by shawnbyday** [comment]
@Dream-Master I haven't tried to harvest it. I will check when I get home to see if that is possible.

**Comment by Dream-Master** [comment]
kk

**Comment by shawnbyday** [comment]
They have a hardness of -1.0 so I'm assuming they can't be broken? At least not with obsidian level tool I know that much.

**Comment by ScriptedPiky** [comment]
Correct, they cannot be mined by any means (unless you got an Infinity Pickaxe I think). Although, there are ways to technically delete the portal frames or portals themselves despite being unbreakable, and you can create end-portals by using a bee with the Resurrection effect on an ender egg being thrown on the ground and promptly killing the dragon with it, thus creating end-portals as if it were slain in the End.

**Comment by shawnbyday** [comment]
@ScriptedPiky that seems like something that would work pretty well in the middle of a base lol! :D

**Comment by basdxz** [comment]
There are multiple methods of interdimentional transportation, getting end portal frames sounds rather redundant.
