### ISSUE TITLE
Lootbags Tier 8, 9, 10 give shit

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#5107]
#### Which modpack version are you using?
2.0.7.5
#
#
#### What did you try to do, and what did you expect to happen?
expected tier 8, 9, 10 loot
#
#### What happened instead? (Attach screenshots if needed)
Unenchented lootbags only gives really basic stuff with no gregtech stuff and enchented version only gives 1 diamond. It is frustrating to open this kind of lootbags
#

**Comment by Dream-Master** [comment]
Need to be added. This bag are not ready for use.
@Alexdoru make some suggestions
