### ISSUE TITLE
T8 rocket plating imposible to make

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5124]
#### Which modpack version are you using?
2.0.8.0a
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
make T8 rocket plating
#
#### What happened instead? (Attach screenshots if needed)
i cant make them becues they need UEV voltage assembling line to get a UHV energy hatches you need awaken draconium wich needs T8 planet to get and UHV SC wich need draconium and infinity cathelist
#
#### What do you suggest instead/what changes do you propose?
make the plate UHV or
allow UHV energy hatches to be made without getting a T8 rocket

**Comment by Anarack** [comment]
UEV Energy hatches/dynamos are cheaply craftable currently. You can use a power substation to provide the buffer for the t8 rocket assline.

However this is not a real solution as it will break as soon as the UEV energy dynamo/hatches get a real recipe but will work in your case.

**Comment by Anarack** [comment]
Or you could just keep moving up the cheapo energy high tier energy hatches I guess. but lets try to fix this early for once?

**Comment by Bluebine** [comment]
IMHO these really shouldn't be an assline recipe. Assline should be for super complicated stuff with lots of intricate parts, which plates really aren't. They're just a few different materials stuck together. Should go back to being an assembler recipe, the plates aren't nearly complex enough to justify an assline and making them need it is kinda dumb.

**Comment by Prometheus0000** [comment]
This is fixed now.
