### ISSUE TITLE
UEV transformer not working

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5125]
#### Which modpack version are you using?
2.0.8.0a
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
tried to upvolt UHV to UEV
#
#### What happened instead? (Attach screenshots if needed)
it does not output the uev 
#
#### What do you suggest instead/what changes do you propose?
fix so it can output UEV

**Comment by Dream-Master** [comment]
The GT one ? @botn365 can you add a picture here ?

**Comment by boubou19** [comment]
possible duplicate of #4135
