### ISSUE TITLE
mining osiridium casing has difrent assembler recipy

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5126]
#### Which modpack version are you using?
2.0.8.0a
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What do you suggest instead/what changes do you propose?
if you want to make mining osmiridium casing in the workbench you need 1 osmiridium frame and 6 osmiridium plates
but in the assembler it is 1 osmiridium frame and 6 ruridite plate
change the assembler recipy to use osmiridium instead of ruruidite

**Comment by bartimaeusnek** [comment]
@Dream-Master pleas up the voltage above LuV for it, that should fix the casing

**Comment by Prometheus0000** [comment]
@bartimaeusnek  Why would that fix it?
```GT_Values.RA.addAssemblerRecipe(GT_OreDictUnificator.get(OrePrefixes.plate, Materials.Osmiridium, 6L), GT_OreDictUnificator.get(OrePrefixes.frameGt, Materials.Osmiridium, 1L), ItemList.Casing_MiningOsmiridium.get(1L), 50, 16);```

It says osmiridium in it already? Why doesn't it work?

**Comment by bartimaeusnek** [comment]
Pre LuV Voltage triggers a hook to replace osmiridium with ruridite

**Comment by Prometheus0000** [comment]
What possible reason would you have for designing something this way? Why not just specify ruridit when you want it? And why does it seem to be different from every other material?
