### ISSUE TITLE
Miranda worldgen disappointing (suggestion for worldgen changes)

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/GT-New-Horizons-Modpack#5128]
#### Which modpack version are you using?
2.0.7.5
#
I'm disappointed by the world generation for Miranda. In reality, that moon is known for having the tallest cliffs in the solar system by far, as well as having wide canyons. In the game, it has neither of these features, which is unfortunate; I know some players will just ignore this moon, but I doubt I'm the only one who would appreciate a change to the worldgen to make it a bit more interesting.
# 
I don't know whether it's possible for you to edit the terrain generation of a Galacticraft dimension, but if it is, I would suggest altering the terrain of Miranda to include immense plateaus similar to the Alps biome from BOP (at least, I am fairly sure it's the Alps biome I'm thinking of; it's the one with huge snowy mountains with sheer cliff faces at the edges), and with deep chasms in between where the terrain is at a lower, more normal level.

**Comment by bartimaeusnek** [comment]
It is theorethically possible. BUT if you don't do it yourself, no one will invest the time, to write an ASM Patch just to make things "nicer". If it aint broke, no one is going to fix it, basically, simply due to the high time investment needed to change ARR mods.

**Comment by richardhendricks** [comment]
Could we disable the ARR Galacticraft dimension and add our own "miranda" dimension? It would mess up the living requirements, but then we have more flexibility on the worldgen.

**Comment by septemberWaves** [comment]
I'd been hoping it'd be a fairly simple change. If it's a big task to do something like this then of course there's not much point just for aesthetics.

**Comment by Dream-Master** [comment]
If somone wrote a new Galactic space mod why not. The mod is buggy as hell and closed source and outdated.
