### ISSUE TITLE
RFC: Should we add Thaumcraft quests for scanning items?

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5130]
One of the annoying bits of TC is trying to figure out how and which items to scan to learn the various aspects.  Should we add quests to guide players through this? Basically take information from threads like https://forum.feed-the-beast.com/threads/thaumcraft-4-a-quick-way-to-discover-all-aspects-updated-for-4-2.33605/

How should it be handled? 
* Should the blocks be prereqs to the quests? 
* Should there be rewards (imo, no)?
* Should the quests all open at once (like how I did the tree and bee breeding quests) or one at a time in order?

**Comment by richardhendricks** [comment]
(getting ready to start TC on Epsilon, hence the Q)

**Comment by Methes** [comment]
I'd like to see it as purely informative quest with checkbox like many other info quests.
With just tips for problematic aspects to push the player forward.

I usually combine aqua+terra straight away as victus gates a lot of things and is problematic to get. Same as mortuus, motus, auram and sano. Then use the usual  easy soulsand, paper, flint, zombie flesh etc.

**Comment by shawnbyday** [comment]
I think having informational quest would be good.
