### ISSUE TITLE
Forestry Yield trait doesn't seem to work properly.

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5131]
After breeding plums (high yield) and mixing them with my butternuts (average yield)  I expected a 50% increase.  Average yield is supposed to be ~20% chance of fruit, with high yield at 30%.  However, after testing, I see essentially no yield difference between the average and high yield trees.
![2019-12-02_20 28 11](https://user-images.githubusercontent.com/1214811/70015286-83b62a80-1542-11ea-915a-e80a0798f162.png)
![2019-12-02_20 29 10](https://user-images.githubusercontent.com/1214811/70015287-844ec100-1542-11ea-901e-9a7c45ac0c4e.png)

**Comment by richardhendricks** [comment]
Could be an issue with ExtraTrees?  Not sure where Butternuts come from.

**Comment by richardhendricks** [comment]
Yeah, looks like ExtraTrees does a 5x yield increase (!). This probably needs to be changed.

https://github.com/ForestryMC/Binnie/blob/master-MC1.7.10/src/main/java/binnie/extratrees/genetics/ExtraTreeFruitGene.java#L378

**Comment by Dream-Master** [comment]
I can fork it

**Comment by Dream-Master** [comment]
@richardhendricks 
https://github.com/GTNewHorizons/Binnie

**Comment by richardhendricks** [comment]
Thanks @Dream-Master

**Comment by richardhendricks** [comment]
@mitchej123 What are your thoughts here?  I think the High yield trait should return what we get now, with the Average about 65% of that.  So if there is a setup with average or below yield, it will get a hit.  I don't think it's a big deal since getting Plum isn't that hard, and/or adding a few more trees isn't a big deal.
