### ISSUE TITLE
Issue with Advanced Seismic Prospector LV/HV

### ISSUE THREAD

**Issue by diregarath** [GTNewHorizons/GT-New-Horizons-Modpack#5133]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
I scanned areas looking for fluids.  I printed the book and looked at the book.
Expected to find the fluids where the book suggested they were.
#
#### What happened instead? (Attach screenshots if needed)
It only listed one kind of fluid.  But as I checked it out with the Fluid Drill every time the book was wrong on the kind of fluid, but correct on the amount.
#
#### What do you suggest instead/what changes do you propose?
Bug fix or config change on Prospercraft

Here are some photos of the books - one on the earth planet and one on the moon.
![](https://cdn.discordapp.com/attachments/104694078595182592/649973795385507841/Capture.JPG)

![](https://cdn.discordapp.com/attachments/104694078595182592/649973760006553600/Annotation_2019-11-29_070216.png)

I found heavy oil instead of light oil and helium instead of salt water.

**Comment by richardhendricks** [comment]
Do you know if someone else has prospected those chunks? This is the first time I've seen this issue. Also, what was the XYZ of the prospector? Maybe there is some issue with negative numbers or something. Any additional information you could provide would be great.

**Comment by diregarath** [comment]
I will get the XYZ when I have time tonight.  I should have thought to include those things.  For the moon no one else has been in the area at all.  It was pristine when I landed.  Prospercraft resets most of the planets every 6 months.  There was other people near where I was at in the overworld - but from what I have seen from his base it seems like he never used oil.  I can give you a XZ estimate for the overworld -4000, -4000 if I remember correctly.  I will get exact screenshots from the books I have.  Thanks for the quick response.

**Comment by bartimaeusnek** [comment]
MP issue for sure @richardhendricks

**Comment by diregarath** [comment]
<img width="474" alt="Screen Shot 2019-12-04 at 10 52 14 PM" src="https://user-images.githubusercontent.com/32985190/70207721-cf0a3d80-16e8-11ea-9689-8292d84ca009.png">
<img width="485" alt="Screen Shot 2019-12-04 at 10 52 04 PM" src="https://user-images.githubusercontent.com/32985190/70207724-d0d40100-16e8-11ea-854d-d3d8d498bbd0.png">

**Comment by diregarath** [comment]
@richardhendricks Hopefully this helps.

**Comment by richardhendricks** [comment]
I am baffled as to why it is reporting incorrectly.  @bartimaeusnek there is nothing to do with MP, the book is generated server side, there is no packets back to the player.

**Comment by richardhendricks** [comment]
Need to check on chunkload requirements for oilfield prospecting. I don't think there is one though.

**Comment by diregarath** [comment]
> Need to check on chunkload requirements for oilfield prospecting. I don't think there is one though.

Good idea - although I was in the area when I did it.  I am willing to try again on Prospercraft - in other parts of dimensions if you like.

**Comment by richardhendricks** [comment]
Thanks.  I don't have time before the holidays, but afterwards we can try some debug.

**Comment by Devtron3D** [comment]
Any news on this problem?

**Comment by Dream-Master** [comment]
@richardhendricks

**Comment by Devtron3D** [comment]
I am starting to cry that this does not work :(

**Comment by richardhendricks** [comment]
I am leaving on vacation tomorrow until Sunday, but will take another look at it when I return.

**Comment by richardhendricks** [comment]
Is Prospercraft still on 2.0.7.5?

**Comment by diregarath** [comment]
No - 2.0.8.3 last I checked.

**Comment by Prometheus0000** [comment]
Is this still happening?

**Comment by repo-alt** [comment]
I cannot reproduce that in 2.1.1
