### ISSUE TITLE
Add step assist to Infinity Armor

### ISSUE THREAD

**Issue by barsikus007** [GTNewHorizons/GT-New-Horizons-Modpack#5137]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Any
#
#### What did you try to do, and what did you expect to happen?
We need Step Assest thing for infinity armor bcs this just unfair to not have utility thing on best armor
#
#### What happened instead? (Attach screenshots if needed)
Or we can add step assist baubles
#

**Comment by richardhendricks** [comment]
https://github.com/GTNewHorizons/Avaritia/blob/master/src/main/java/fox/spiteful/avaritia/items/ItemArmorInfinity.java

**Comment by GTNH-Colen** [comment]
An option to turn it off would be nice if you do add it, not everyone likes step assist after all.
