### ISSUE TITLE
Diamond equipment gives four times what it should when pulverized

### ISSUE THREAD

**Issue by Schist-** [GTNewHorizons/GT-New-Horizons-Modpack#5139]
#### Which modpack version are you using?

#2.0.7.5-1.7.10
#### If in multiplayer; On which server does this happen? 

# 
#### What did you try to do, and what did you expect to happen?

# Pulverize diamond armour 
#### What happened instead? (Attach screenshots if needed)

# Gives 32 diamond dust, four times the amount it should. As do boots, leggings, helmets, swords, hoes, pickaxes, shovels, hoes, axes and chisels.
#### What do you suggest instead/what changes do you propose?
Reduce the output to a normal level.

**Comment by Prometheus0000** [comment]
Already fixed
