### ISSUE TITLE
Add a costum recipe for draconic cores

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#5144]
#### Which modpack version are you using?
2.0.7.5
#

#### What do you suggest instead/what changes do you propose?
I sugget adding a costum assembler recipe that does 64 neutronium ingot + 4 ichorium ingot + 16 AsoC + [Costum item that does not get consumed] ----> 16 draconic cores.

And the item that does not gets consumed is unlocked as a reward at the end of the legendary quests. This way it is possible to automate draconic evolution crafting without having to manually get the cores.

**Comment by Dream-Master** [comment]
Add a recipe was suggested before but why would anyone doing the quests anymore ?

**Comment by draknyte1** [comment]
I think the recipe involves an end game quest to get the reusable item.

**Comment by Alexdoru** [comment]
"And the item that does not gets consumed is unlocked as a reward at the end of the legendary quests. This way it is possible to automate draconic evolution crafting without having to manually get the cores."

To make this assembler recipe you need a special item that is unlocked at the end of the legendary quests. This way draconic evolution is still gated behind the legendary quests and you can now automate draconic cores crafting.

**Comment by Dream-Master** [comment]
Yea maybe a good idea. Get a key item via the Quests.

**Comment by Anarack** [comment]
You could always make the quest give the tablet, and then you scan that. Just add a recipe for the tablet using a core.

**Comment by Spartak1997** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/203
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/86

**Comment by Dream-Master** [comment]
@Spartak1997 please read the comment in pull request. If you realy a dd a new interresting machine i will add it.
