### ISSUE TITLE
OpenComputer-Components in the Assembler

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/GT-New-Horizons-Modpack#5154]
#### Which modpack version are you using?
7.5
# 
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
crafting oc compenents with an iv /luv assembler
# 
#### What happened instead? (Attach screenshots if needed)
didnt start the recipe
# 
#### What do you suggest instead/what changes do you propose?
assuming that there´s some nbt shenanigans going on, looking at those. i also was told that circuits may be an issue

**Comment by GeicowithaBango** [comment]
Also worth to mention is that some recipe allow only one type of a circuit

**Comment by Dream-Master** [comment]
@GeicowithaBango 
some recipe? can you write down which recipes ?

**Comment by GeicowithaBango** [comment]
The microchip (t1) and the arithmetic logic unit, for instance, wont craft in the circuit assembler. i cant tell for other recipes since i have to craft those first. the arithmitec one just doesnt want to start, and after some testing i found out that microchips only allow GOOD ELECTRONIC CIRCUITS, and not int. processor´s. (which shouldnt be the case?)

**Comment by GeicowithaBango** [comment]
but there are most defently more of those cases. thats why i made i ticket

**Comment by Dream-Master** [comment]
The recipe is an oredicted one. Why the hell it not working idk.
Having much issues in the past. In GT code oredict circuits worked well now not in the core mod.
HELP WANTED.

**Comment by Dream-Master** [comment]
``//Circuit 1
                    GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Board_Plastic_Advanced.get(1L), GT_OreDictUnificator.get(OrePrefixes.circuit, Materials.Good, 1), ItemList.Circuit_Parts_Transistor.get(4L), GT_OreDictUnificator.get(OrePrefixes.foil, Materials.Electrum, 4L), GT_Utility.getIntegratedCircuit(1)}, tMat.getMolten(144L * tMultiplier / 2L), GT_ModHandler.getModItem("OpenComputers", "item", 1L, 24), 300, 120);
                    GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Board_Plastic_Advanced.get(1L), GT_OreDictUnificator.get(OrePrefixes.circuit, Materials.Good, 1), ItemList.Circuit_Parts_TransistorSMD.get(4L), GT_OreDictUnificator.get(OrePrefixes.foil, Materials.Electrum, 4L), GT_Utility.getIntegratedCircuit(1)}, tMat.getMolten(144L * tMultiplier / 2L), GT_ModHandler.getModItem("OpenComputers", "item", 1L, 24), 300, 120);
                    ``

**Comment by repo-alt** [comment]
I think GT_OreDictUnificator.get(OrePrefixes.circuit, Materials.Good, 1) will just return the first element of the dictionary

**Comment by repo-alt** [comment]
So the real fix would be to register the recipe in a loop. Perhaps there is another way, idk.

**Comment by Dream-Master** [comment]
in gt the same code works. Should it be 1L ?

**Comment by repo-alt** [comment]
Where does it work?
I look for the GT_Values.RA.addCircuitAssemblerRecipe and the first occurrence I find look like this:
`                GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Board_Coated_Basic.get(1L), GT_OreDictUnificator.get(OrePrefixes.circuit, Materials.Primitive, 2), GT_OreDictUnificator.get(OrePrefixes.foil, Materials.Tin, 2), GT_OreDictUnificator.get(OrePrefixes.screw, Materials.Tin, 4), GT_OreDictUnificator.get(OrePrefixes.wireFine, Materials.Tin, 1),GT_Utility.getIntegratedCircuit(1)}, tMat.getMolten(1152L * tMultiplier / 2L), GT_ModHandler.getModItem("Forestry", "chipsets", 1L, 0), 200, 30);
                GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Board_Coated_Basic.get(1L), GT_OreDictUnificator.get(OrePrefixes.circuit, Materials.Basic, 2), GT_OreDictUnificator.get(OrePrefixes.foil, Materials.Bronze, 2), GT_OreDictUnificator.get(OrePrefixes.screw, Materials.Bronze, 4), GT_OreDictUnificator.get(OrePrefixes.wireFine, Materials.Bronze, 1),GT_Utility.getIntegratedCircuit(1)}, tMat.getMolten(1152L * tMultiplier / 2L), GT_ModHandler.getModItem("Forestry", "chipsets", 1L, 1), 200, 30);
                GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Board_Phenolic_Good.get(1L), GT_OreDictUnificator.get(OrePrefixes.circuit, Materials.Good, 2), GT_OreDictUnificator.get(OrePrefixes.foil, Materials.Steel, 2), GT_OreDictUnificator.get(OrePrefixes.screw, Materials.Steel, 4), GT_OreDictUnificator.get(OrePrefixes.wireFine, Materials.Steel, 1),GT_Utility.getIntegratedCircuit(1)}, tMat.getMolten(1152L * tMultiplier / 2L), GT_ModHandler.getModItem("Forestry", "chipsets", 1L, 2), 200, 30);
                GT_Values.RA.addCircuitAssemblerRecipe(new ItemStack[]{ItemList.Circuit_Board_Phenolic_Good.get(1L), GT_OreDictUnificator.get(OrePrefixes.circuit, Materials.Advanced, 2), GT_OreDictUnificator.get(OrePrefixes.foil, Materials.Electrum, 2), GT_OreDictUnificator.get(OrePrefixes.screw, Materials.Electrum, 4), GT_OreDictUnificator.get(OrePrefixes.wireFine, Materials.Electrum, 1),GT_Utility.getIntegratedCircuit(1)}, tMat.getMolten(1152L * tMultiplier / 2L), GT_ModHandler.getModItem("Forestry", "chipsets", 1L, 3), 200, 30);
`

**Comment by Dream-Master** [comment]
yes that is the recipe i checked too. Any mistake i doing in the core mod ? @repo-alt

**Comment by draknyte1** [comment]
If memory serves me right, Circuit OreDict is a hack directly on Assembler code and we don’t have such support in master at all.

**Comment by repo-alt** [comment]
Indeed it works in GT, interesting.

**Comment by repo-alt** [comment]
Looks like indeed the problem is loading order, so, one solution is indeed queue the recipes in (custom) addCircuitAssemblerRecipe() and process the queue in GT postLoad, hoping that it would be late enough.

**Comment by Prometheus0000** [comment]
Dupicate of #4714
