### ISSUE TITLE
[RFC] Add new concept for DE mod

### ISSUE THREAD

**Issue by Spartak1997** [GTNewHorizons/GT-New-Horizons-Modpack#5157]
#### Which modpack version are you using?
2.0.8.X
#
#### What do you suggest instead/what changes do you propose?
Many people told about change "recipes" of Draconic Evolution Cores. So, I suggest add Fusion Crafting Machine for construct all components from this mod.

First, about structure:
![structure1](https://user-images.githubusercontent.com/29407630/70391105-bad18380-19fb-11ea-97f6-4164a4af38e1.png)
![structure2](https://user-images.githubusercontent.com/29407630/70391109-c4f38200-19fb-11ea-8379-fe0686724dad.png)
This machine using different casings for different recipes.

Tooltip:
![tooltip](https://user-images.githubusercontent.com/29407630/70391134-113ec200-19fc-11ea-8020-a2f38b33bfbe.png)

Casings:
![casing1](https://user-images.githubusercontent.com/29407630/70391146-303d5400-19fc-11ea-9d40-e992a3b27210.png)
![casing2](https://user-images.githubusercontent.com/29407630/70391150-359a9e80-19fc-11ea-9f13-f0d843b7454b.png)
![casing3](https://user-images.githubusercontent.com/29407630/70391152-3b907f80-19fc-11ea-8122-16b6da3055b5.png)
![casing4](https://user-images.githubusercontent.com/29407630/70391153-40553380-19fc-11ea-91a8-85deb6f92685.png)
![casing5](https://user-images.githubusercontent.com/29407630/70391160-45b27e00-19fc-11ea-856b-616d5380167e.png)

Each tier of casing reduces time by 50%. These blocks need for crafting different components. For example cores:
![core1](https://user-images.githubusercontent.com/29407630/70391181-890cec80-19fc-11ea-993a-a85657df88fb.png)
![core2](https://user-images.githubusercontent.com/29407630/70391188-8f9b6400-19fc-11ea-8a57-78fdbe2ef1c1.png)
![core3](https://user-images.githubusercontent.com/29407630/70391190-95914500-19fc-11ea-9ac1-64cca48a24a9.png)
![core4](https://user-images.githubusercontent.com/29407630/70391193-9b872600-19fc-11ea-9a35-bf0b95938ca0.png)
![ecore1](https://user-images.githubusercontent.com/29407630/70391195-a0e47080-19fc-11ea-9c05-7c50498f5144.png)
![ecore2](https://user-images.githubusercontent.com/29407630/70391198-a6da5180-19fc-11ea-95dc-661e76147ebb.png)

I think you observed new items - schematics. These things you can get from Legendary Quest Line.

So, guys, I hope you like it suggestion. Of course I can change recipes, structure and another things.
 
Thank you for comments =) 
 
Pull Requests:
https://github.com/GTNewHorizons/GT5-Unofficial/pull/203
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/86

**Comment by Anarack** [comment]
This is interesting, do the schematics go in the input bus, or will you need to build multiple of the things to handle multiple recipes?

**Comment by Spartak1997** [comment]
@Anarack input bus

**Comment by GTNH-Colen** [comment]
This is really nice and clearly has had a lot of time and effort put into considering it. The current method of obtaining cores via the quest reward is kinda strange and out of place so this would be a really nice addition to the game even if it ends up costing us more in the long run.

**Comment by barsikus007** [comment]
Pls add dislocator recipes

**Comment by Dream-Master** [comment]
yes more recipes will follow

**Comment by EmeraldsEmerald** [comment]
oh hey those schematics are my textures, yes sure why not

**Comment by EmeraldsEmerald** [comment]
oh hey those schematics are my textures, yes sure why not

**Comment by GTNH-Colen** [comment]
> Pls add dislocator recipes

This could be a good chance to rebalance the enhanced dislocation recipe while we're at it given the current one is absurdly overpriced as it stands.

**Comment by GTNH-Colen** [comment]
> Pls add dislocator recipes

This could be a good chance to rebalance the enhanced dislocation recipe while we're at it given the current one is absurdly overpriced as it stands.

**Comment by combusterf** [comment]
> These things you can get from Legendary Quest Line.
I would be very wary of getting permanently stuck when you lose the schematic for any reason, be it through losing the item, or already having done the legendary quests in question.

Considering what the legendary quests tend to be, why not drop the schematics directly from the boss mobs instead?

**Comment by 0lafe** [comment]
Bosses are only a part of the quest line, the HEE part is probably worse than any boss fight in the game. Could change it so the repeatable quest gives the schematics instead of the cores. Technically infinite, and you can't really loose it without loosing quest progress. Also nice to be able to get multiple for parallelization options

**Comment by Dream-Master** [comment]
after you finish quest line I can add a schematic buy quest.

**Comment by DoomSquirter** [comment]
is the bat part of the multiblock?

**Comment by BlackFlameTNT** [comment]
i like but ..... the old way to make core take 4 ichorium for 16 core .... the new way 4 ichorium for 1 core is this going to change?

**Comment by DietmarKracht** [comment]
4 Stacks Ichorium for a single chaotic core :D

**Comment by 0lafe** [comment]
Ichorium is fairly inexpensive to craft by the point of chaotic cores. You barely use the chaotics for DE, needing a couple hundred ichorium is very achievable for zpm+.

**Comment by KaneHart** [comment]
Really love the concept. I can't give you ideas for Balance as I don't have the experience that high. But it looks like awesome thing to craft. I'm all for more Multiblocks :)

**Comment by SpwnX** [comment]
more multiblocks means more fun imo

**Comment by Prometheus0000** [comment]
@mitchej123 I @'d spartak/sportacus and he said

>  Hi! About DE Machine, I will never work with another mods/addons. If you like it, you can copy/change this thing

So could you or someone else implement this?

**Comment by Dream-Master** [comment]
I ask @Spartak1997 to pack all in core mode because it was split in gt and core but never get it done. That's why I closed it.

**Comment by Prometheus0000** [comment]
See the quote above. He's done with MC modding, so someone else needs to do it if we want it done.

**Comment by GTNH-Colen** [comment]
This was extremely popular (>90% voting for it) so would be nice to see it implemented, the current system of only being able to buy cores from the quest is kinda wacky.

**Comment by Dream-Master** [comment]
If someone recode it it why not.

**Comment by glowredman** [comment]
Maybe we can look into this again once StructureLib is ready?
