### ISSUE TITLE
Make Pollution a visual feature in the game.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#5160]
Not even sure if this can be done with the current state of the engine, etc. I don't want some silly block based living pollution, etc. What I like to see some way to look down a mountain and see a factory running and be able to just visually know there is a lot of pollution in the area without actually having to use a tool while standing near it or on it or being hit by the character effects.

I think it be a lot of fun to visually see a factory causing pollution in the area.

The only other way and sadly I think the map API, etc does not really exist in this version and probably can't be done without too much lag is something that visually shows on your minimap/map and shows like red area you can turn on and off. 

Sadly this might be slightly out of the abilities like I said of the engine and such but I thought I give it a shot ask at least.

**Comment by Dream-Master** [comment]
@Technus can you make it visual maybe like you did in Tec Tech ?

**Comment by draknyte1** [comment]
![66E90ED0-D181-48ED-A3FC-AE9B1AE553DC](https://user-images.githubusercontent.com/3060479/70395681-2cf49900-19f9-11ea-852f-0f7349085316.png)
![57087B45-D911-4DC1-A40A-73E788C9D038](https://user-images.githubusercontent.com/3060479/70395682-2cf49900-19f9-11ea-9893-14307d0e1470.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/70397322-e2fabb80-19d6-11ea-963a-a849a748a131.png)

We could modify the current implementation so it shows effect of the current chunk you are in, but modifying the look of a chunk far away might be hard to do.

**Comment by shawnbyday** [comment]
I still want to see an HVAC like system added so you can control the pollution. Either by sending it to a far off chunk or being required to build air filtration systems to "handle" your pollution output.

**Comment by richardhendricks** [comment]
I wonder if we could control the rain effect?  We could then use that to show pollution on chunks further away.

**Comment by KaneHart** [comment]
Is that possible? I don't think I seen localized rain before outside of rain shield that would remove said rain. That be cool though a toxic looking rain effect

**Comment by richardhendricks** [comment]
Twilight Forest does different effects in different biomes, so it should be possible. 

Also, it doesn't rain in a desert, so there's something there.

**Comment by KaneHart** [comment]
That is a good point but keep in mind stopping an effect and having an effect outside biome might be diff. Hopefully not as I think it be an awesome solution period. 

It can be an effect from the center of the pollution and depending how bad it is grows in size to the point where you can be 500 blocks away and be effected (that being like really really shitty base that you die instantly in almost) lol.

If it was something the server admin could adjust for more fun omg that be awesome effect :)

**Comment by Ethryan** [comment]
If it's possible: 
How about gradually changing the tint of water in affected chunks, that would be a neat way to show gradually worsening pollution conditions.

**Comment by richardhendricks** [comment]
#3460 also discusses same issue.

**Comment by draknyte1** [comment]
Pollution is DEFINITELY synced to the client... because why else would we have pollution packets? 🤔 

On top of that, the renderer is in the Client Proxy.. which would require.. you guessed it.. synchronization..

The ability to make the changes gradual are easily doable also.
