### ISSUE TITLE
Add quests for batpack and GT++ power backpacks

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5161]
Check on quests for the batpack /advanced batpack/GT++ Charge Packs

Keeps armor and tools charged.  Good for adding to support electro mining tools.

**Comment by richardhendricks** [comment]
Add batpack/advanced batpack quests after stainless? Not really any tools that can use it before that point.  Need to check against real GT tools as well such as drill and etc.

**Comment by Prometheus0000** [comment]
Dream said no more GT++ quests. Also, there's already a quest about the charge thing.
