### ISSUE TITLE
[Suggestion] Deep earth drilling platform

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#5166]
If I understand this correctly the deep earth drilling platform is a void miner that is disabled right now because the ore output isn't balanced for GTNH yet. So here is my suggestion on how it should work.

My proposition is to make the drilling platform generate only ores and small ores that spawn in the dimension where you place the miner.
This way the player can only generate ressources from dimensions he has access to (although at the time he can craft this the player should have access to all dimensions). 
Moreover the player can somewhat choose what ores he wants to target as the oregen is specific to every dimension. 
And considering there is so many ores in GTNH having this multiblock generate all the ores from the game wouldn't be a good idea since you would get a lot of ore in total but not much of every single ore.

The drilling platform should behave similarly to the previous drilling plants : it should give crushed ores + side product + stone dust when it "mines" a regular ore and crushed ore + impure dust + stone dust when it "mines" a small ore. And it should have a fortune bonus as well with a level consistent with the previous drilling plants. Might want to consider to make it need drilling fluid as well ?

Now how does the multiblock calculate the chances of having this or this output for every operation ?
To generate the file with the %chances the miner has to give an output or another depending on the dimension you should consider all the parameters taken into account during gregtech ore generation. And this way attribute to every ore and small ore a chance to be generated by the multiblock for every dimension.
If I understand it correctly those parameters are the following  : vein weight, veins size, veins density, chance of spawn of primary/secondary/between/sporadic ore and number or small ore per chunk.

In the end this behavior makes it the ultimate endgame mining solution while remaning not OP because it is operating similarely to a regular drilling plant execpt you don't need to move it and it only require one chunk loaded.

**Comment by draknyte1** [comment]
No. 

Ore outputs are to be defined by GTNH staff manually. Until that’s done, the multi will remain disabled.

**Comment by 0lafe** [comment]
should probably work on what that list would include at some point

**Comment by Alexdoru** [comment]
I never said that it was GT++'s job to do, I would have posted this on your github Alk

**Comment by botn365** [comment]
https://pastebin.com/M8dZ1p2C

this is a the ore veins but without the dimension correct
im asking if these weigths values are good 
righ now they follow 
pimary/secondary 45% of weight
inbetween 20% of weight
sporadic around 15% of weight

**Comment by draknyte1** [comment]
The problem I see so far is this:

```
VoidMiner_API.registerOreForVoidMiner(0,"oreChrome",2);
VoidMiner_API.registerOreForVoidMiner(0,"oreTungsten",2);
VoidMiner_API.registerOreForVoidMiner(0,"oreMolybdenum",1);
VoidMiner_API.registerOreForVoidMiner(0,"oreManganese",1);
```
There's a total weight of 6.. 
```
VoidMiner_API.registerOreForVoidMiner(0,"oreChrome",50);
VoidMiner_API.registerOreForVoidMiner(0,"oreTungsten",50);
VoidMiner_API.registerOreForVoidMiner(0,"oreMolybdenum",30);
VoidMiner_API.registerOreForVoidMiner(0,"oreManganese",15);```
Kinda gives more rarirty to Manganese (Just as a random example) as opposed to what it has in the first block.

**Comment by Prometheus0000** [comment]
The VM has been in for a while, closing.
