### ISSUE TITLE
The One Ring invincibility

### ISSUE THREAD

**Issue by sthegreat** [GTNewHorizons/GT-New-Horizons-Modpack#5168]
#### Which modpack version are you using?
.7.5

The One Ring is a earlygame loot item giving invisibility and invincibility. Obviously quite op as this enables you to walk past infernal mobs and swim in lava, and trivializes the pseudo-inversion sigil, dragon fight, roguelike dungeons, and probably a lot more. It is slightly nerfed by a "mind corruption" system giving some potion effects as well as the fact that item warp gets added to the ring over time, but it's still super op when used situationally. A while back I was looking in the code for it and saw something interesting:

Here in gtnh we have:
https://github.com/GTNewHorizons/Electro-Magic-Tools/blob/master/src/main/java/emt/item/ItemOneRing.java

while EMT main is:
https://github.com/fewizz/Electro-Magic-Tools/blob/master/src/main/java/emt/item/ItemOneRing.java

We have various nerfs, such as adding item warp, as well as changes to make things work properly. But theirs only gives invisibility, while ours gives (nearly) complete invincibility... I suggest we also comment out the line disabling damage on onWornTick, so it will only give invisibility, which to me seems a lot more appropriate for a stone age item.

**Comment by richardhendricks** [comment]
It still feels a little OP to me. It should do more IMO, like giving you hunger or damage.

**Comment by Anarack** [comment]
https://github.com/GTNewHorizons/NewHorizons/issues/3909 relevant reading

**Comment by sthegreat** [comment]
I think invisibility for "mind corruption" negative potion effects (includes poison, eventually wither) and item warp is a fair trade. Maybe make the effects occur more often and/or throw in some hunger too, though, I'm not really sure how much is needed.

**Comment by Dream-Master** [comment]
@sthegreat feel free to make a pull request with code changes.

**Comment by KaneHart** [comment]
I just wanted to comment I felt it was quite a cheap item as well and plan on removing it, but that being said I be willing to see it nerfed.

I honestly rather see random bad things happen that can mean life or death not just random effects that maybe people can keep up to with Milk due to the nature of how powerful the ring is to begin with.

**Comment by richardhendricks** [comment]
I like the idea of it summoning mobs the more you use it. 
"You feel the ring calling out into the void"
"Monsters seem strangely attracted to you"
"The ring is screaming in your mind that its master is coming"
etc
