### ISSUE TITLE
Prospecting Book Localization

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#5178]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Scanned data stick printed book. Expected text to fit on page and be legible.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/33701188/70845442-7f2c2480-1e14-11ea-8508-b080555f757b.png)
Localization looks off.
#
#### What do you suggest instead/what changes do you propose?
Can we fix the localization?

**Comment by richardhendricks** [comment]
Which language are you set to?

**Comment by shawnbyday** [comment]
> 
> 
> Which language are you set to?

Well...English...I think?

**Comment by Prometheus0000** [comment]
Looks fine in english
