### ISSUE TITLE
Wolrd breaker pickaxe on Spawners

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#5179]
#### Which modpack version are you using?
GTNH 2.0.7.5
#

#### What did you try to do, and what did you expect to happen?
Break a mod spawner with the world breaker pickaxe from Avaritia mod and it dropped 4 broken spawners instead of one. I don't know if it is intended or if it is a bug.
#

**Comment by Dream-Master** [comment]
idk

**Comment by Prometheus0000** [comment]
Sounds good, given how late you get that.

**Comment by boubou19** [comment]
that's because it has fortune X
