### ISSUE TITLE
Negative number displayed on super tanks

### ISSUE THREAD

**Issue by firendlyGhost** [GTNewHorizons/GT-New-Horizons-Modpack#5181]
#### Which modpack version are you using?
i think its on version 2.0.7.5 but im not 100% sure I didnt discover this bug im just reporting it
#
#### If in multiplayer; On which server does this happen? 
Dont know
#
#### What did you try to do, and what did you expect to happen?
They filled a tank with Gt++ rocket fuel, expected the tank to display the correct value of fuel
#
#### What happened instead? (Attach screenshots if needed)
the number displays negative screenshot attached
#
#### What do you suggest instead/what changes do you propose?
![bug](https://user-images.githubusercontent.com/53128966/70862689-48026400-1f37-11ea-8baa-6863a7b303f5.PNG)

I suggest it gets fixed to show the correct value and not a negative number

**Comment by Dream-Master** [comment]
@draknyte1 any idea ?

**Comment by Methes** [comment]
Also Temperature -300 K looks not functioning correctly.

**Comment by draknyte1** [comment]
> Super and quantum tanks aren’t mine, although they’re identical code wise to my tanks beyond portability. Bug either is in the base GT tank if mine does it, or it’s a NH specific super/quantum tank issue.  

No idea, just know it's not my bug. Probably a long getting passed as an int and overflowing.

> And only two things treat fluids as K, Gregtech and Minecraft. Every mod uses C.  

@Methes You won't be able to change that, lol. Vanilla oddly uses K, but nothing else does.

**Comment by Methes** [comment]
I don't care about the unit. Would honestly like to see Celcius and mB/tick or mB/sec just cause it's how MC has standardized over they years instead of articifical and 'realistic' litres and Kelvins.
Either way your quotes are missing context and authors so they are confusing and difficult to read.
Also - even -300C is bullshit so it's faulty either way.

**Comment by draknyte1** [comment]
The context was me quoting myself from discord. 

![4FB5AB37-D5E9-432D-88AF-1BFF06C1C073](https://user-images.githubusercontent.com/3060479/70865233-fff13a80-1f52-11ea-9857-a1260a361396.png)

It’s a made up game, there is no limit to -C.. look at cryotheum 🤷🏻‍♀️

While I agree on consistency, converting between ticks and seconds isn’t hard. And L and Mb are interchangeable.

**Comment by Prometheus0000** [comment]
Should be the fluid and not the tank that has the bug?
