### ISSUE TITLE
Magic metal berry oddness

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5182]
#### Which modpack version are you using?
2.0.7.5
#
#### What did you try to do, and what did you expect to happen?
Harvest the magic metal berry crop (with Void metal Block 1509 under it) with a forestry mutifarm.
#
#### What happened instead? (Attach screenshots if needed)
When the farm harvests it, you get Void Nugget 6854:9970, but when you do it by hand, you get Void metal Nugget 4432:7. If you put the first into your inventory it changes into the second, and they're oredicted together, so it isn't a huge deal, but you probably should only be getting the second type. The same thing also happens with the Thaumium nuggets as well.

Secondly the rate of collection is abysmally low (like, 1 per 30+ crop harvests) if you use the multifarm. If you try to harvest the crop (with any of the 3 types of compatible blocks under it) shortly after turning it off, it stays low, but after a minute or two, I'm getting a nugget per crop doing it by hand, which is definitely weird. I tried another of the oreberry crops, and it seemed normal, so it sounds like it's just this crop?
#
#### What do you suggest instead/what changes do you propose?
Have it drop Void metal Nugget 4432:7 (and Thaumium Nugget 4432:6) from the beginning, fix whatever's wrong with the drop rate when using a multifarm.

**Comment by Dream-Master** [comment]
From which mod the nuggets drop? @Prometheus0000

**Comment by Prometheus0000** [comment]
The ones they change into are Thaumcraft (manual collection), and the ones they change from are from Gregtech (multifarm harvested).
