### ISSUE TITLE
Circuit assembling line balance

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#5183]
#### Which modpack version are you using?
GTNH 2.0.8.0.b
#
I have multiple suggestions for the circuit assembling line. 

This multiblock is a circuit assembling machine that is 16x faster than the single block version therefore cutting by 16 the energy cost of circuits. 
Let's take a look at the material cost and compare apples and apples, that is the multiblock and 16 circuit assembling machines doing the same work in the same time.
So one circuit assembling line vs 16 circuit assembling machines:

![Material cost](https://user-images.githubusercontent.com/57050655/70872014-2213a880-1fa5-11ea-988e-8c011515c50b.PNG)

As we can see as the multiblock variant is way much cheaper than 16 machines even though it is going at the same speed. This is why I think we need recipe changes alongside with speed nerf. @botn365
suggested adding circuit assembling line casing with tiers : LuV, ZPM and UV to reestablish balance between the multiblock and the equivalent circuit assembling machines. The recipes for those casing should be such as the whole multi is more expensive than the machines it is emulating BUT the whole point is that the multi has the advantage of having a (great) speed boost and therefore en energy cost reduction.

![Circuit assembling line casing](https://user-images.githubusercontent.com/57050655/70872015-23dd6c00-1fa5-11ea-8ba3-03cdfb56fd59.PNG)

Moreover I suggets these changes :
- Change the 16xspeed boost make it 4x or 8x
- Remove the nerf on normal circuit assembling machine recipes. This way players aren't bothered by the changes but if they want to craft circuits with increased speed they have to make this more expensive multiblock.
- Allow the circuit assline to make different circuits, it is annoying to have multiblocks sitting around and not use them all at once in parrallel,
for instance with regular asslines it would be a bit idiotic to use one assline per recipe and I think it is the same for this multi.

**Comment by 0lafe** [comment]
What about parallel processes that scale with length? Assuming it caps at 16, a 16 parallel count is pretty decent for something that works on multiple tiers. Significantly better than using singles, as it'll change tier based on the recipe, but still the same power cost. 

Imo speed bonuses are a bad idea for this. Even if the multi costs more, you have a fairly significant power decrease. 4x is a full tier down of what you would need for the same speed. 16x is 2T and is wayyy too much. 

Doesn't this thing also allow you to make a 2nd line of circuits that's purposefully easier than many of the main line? That alone is worth a cost greater than what it seems to be, giving it the functionality of a better CA as well seems fine but within some bounds. Reducing the power cost of the CA by 16x seems like a poor way to do that. Parallel count will keep it with a better suited power cost, but still benefit over singles in a tangeble way.  Casing tier could control input v tier, which would give it a good cost for tiering up. Just a hatch is about the cheapest cost you can give something
