### ISSUE TITLE
[Suggestion] Unveiling enchantment should work on invisible Infernals

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/GT-New-Horizons-Modpack#5190]
There's Unveiling enchantment in Witching Gadgets allowing you to enchant your helmet so that you can see mobs and players with invisibility effect.
For some reason it doesn't work against Infernals with the invisibility ability.
Would be nice if it did.
Low priority, really.

**Comment by wlhlm** [comment]
I've looked at the Infernals code and all the cloaking modifier does is apply the vanilla invisibility potion to the mob. So if unveiling doesn't work on those, then this should be fixed in Witching Gadgets.

**Comment by wlhlm** [comment]
Doing some more investigating: The unveiling enchantment seems to be buggy outside of infernals. Here is a vanilla Zombie Pigman that I've thrown an invisibility splash potion towards:
![2020-03-01_10 46 14](https://user-images.githubusercontent.com/1928113/75623463-8577a480-5baa-11ea-96ab-45d8dcb6a8f2.png)
![2020-03-01_10 46 20](https://user-images.githubusercontent.com/1928113/75623465-890b2b80-5baa-11ea-8e57-3821919b2536.png)

It doesn't unveil whatsoever.
