### ISSUE TITLE
Wax Capsule Lava

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#5194]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Trying to get lava into the Acclimatizer, trying different things since buckets disappear. So I tried a waxed cell. It didn't go into the Acclimatizer (which is fine) but I didn't expect it to hold lava to begin with since it is wax and I especially didn't expect to get the capsule back after I emptied the lava.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/33701188/71146404-bf135300-21ea-11ea-9ec3-f0439c63233a.png)

#
#### What do you suggest instead/what changes do you propose?
Wax capsules shouldn't hold lava. If they do they should burn up when emptied like a clay bucket.

**Comment by repo-alt** [comment]
Vanilla forestry does not allow lava in usual wax capsules, there is refractory wax for that.
