### ISSUE TITLE
infinity bolts are way to weak

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5197]
#### Which modpack version are you using?
2.0.8.0a
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
make infinty bolts and get OP bolts
#
#### What do you suggest instead/what changes do you propose?
infinty bolts damage
![afbeelding](https://user-images.githubusercontent.com/42187820/71216262-61e6d280-22ba-11ea-83d4-8125fe28b711.png)
palldium bott damage wit energetic rod
![afbeelding](https://user-images.githubusercontent.com/42187820/71216330-817dfb00-22ba-11ea-9324-fbdd0f926879.png)
this is realy low for the most expansif metal in the game needing T8 rocket while palladium can be gotten in HV

**Comment by Dream-Master** [comment]
Not sure how ticon or Tinkers Gregworks add effects to tools. Need to check code and need help.
