### ISSUE TITLE
Superconductors and You: Quality of Life, Adjustments, and a New Superconductor

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#5200]
What is the current situation with superconductors? Are they 'bad' or 'good' or perhaps in between? All your answers explained and a cookie near you! Superconductors are considered 'lossless' wires and high amperage means of transporting huge currents of EU packets with no downsides compared to the regular amperage loss per cable length of regular cables. Their lossless EU and large packet transfer can be highly sought out for, but it is not without its varying problems of different wires and is thus widely criticized and questioned if it is worth it or not. Though these problems are or have been adjusted and accounted for, such notable ones as the Gate to Fusion has been recognized in its part with the superconductor controversy.

I'll also illiterate the current superconductor EBF and Freezer times on the current beta (and soon official) 2.0.8.0 of GTNH for the sake of information:
**MV Superconductor**: 480 EU/t, 110~ seconds no gas, 100 seconds Nitrogen gas to EBF. 480 EU/t, 37.50 seconds freezing.
**HV Superconductor**: 480 EU/t, 130~ seconds no gas, 115 seconds Nitrogen gas to EBF. 480 EU/t, 37.50 seconds freezing.
**EV Superconductor**: 1920 EU/t, 145~ seconds no gas, 128.80 seconds Argon gas to EBF. 1920 EU/t, 100 seconds freezing.
**IV Superconductor**: 1920 EU/t, 175~ seconds no gas, 156.40 seconds Argon gas to EBF. 1920 EU/t, 100 seconds freezing. 
**LuV Superconductor**: 7680 EU/t, 275~ seconds no gas, 220 seconds Argon gas to EBF. 7680 EU/t, 150 seconds freezing.
**ZPM Superconductor**: 7680 EU/t, 315~ seconds no gas, 250 seconds Argon gas to EBF. 7680 EU/t, 150 seconds freezing.
**UV Superconductor**: 30720 EU/t, 660~ seconds no gas, 300 seconds Radon gas to EBF. 30720 EU/t, 150 seconds freezing.
**UHV Superconductor**: 122880 EU/t, 820~ seconds no gas, 375 seconds Radon gas to EBF. 122880 EU/t, 150 seconds freezing.

### Quality of Life Buffs and Adjustments

Specifically, we're going to look at the MV & HV superconductor, and superconductor amperage overall. Currently, the MV superconductor is in a weird place, requiring the Vacuum Freezer in order to even obtain the ingots, which is gated far into HV where you'd already have HV machines and cables instead of this rather exaggeratedly gated material. Instead, change the following to its recipe:
**MV Superconductor**: 480 EU/t, 120~ seconds no gas, 95 seconds Nitrogen gas to EBF. No freezing needed.
In addition, the HV superconductor also has a weirdly placed recipe, requiring titanium in its mixer recipe when titanium cannot be *realistically* obtained before the Moon. Instead of `TiBar9Cu10O20`, it should be `LaBar9Cu10O20`, where La is Lanthanum and this is a rather uncommonly obtained & unused resource that could use some love.

For adjustments, we'll be taking a look into the UHV superconductor and its weirdly and seemingly rushed material list. The UHV superconductor uses 6 Awakened Draconium dust, 7 Cosmic Neutronium dust, 5 Infinity Catalyst dust, and 6 Americium dust. This dust, however, arrives with a critical problem, it is unobtainable by any means because of two of the following dusts, Awakened Draconium and Infinity Catalyst are obtained on a **UEV** or T8 planet, and is thus impossible to obtain. Here is a suggested recipe that fixes this problem with a more balanced, fun, and thought-out approach:
7 Tritanium dust, 3 Americium dust, 2 Unstable dust, 2 Ichorium dust, 3 Cosmic Neutronium dust, 8 Xenon gas. Or otherwise known as `Tn7Am3?2IcMa2SpNtXe8`. Xenon gas is an incredibly rare resource that is mainly obtained from centrifuging air in the distillation tower with an incredibly large input hatch (from Bartworks). It is one of the three only ways of obtaining it. The other two being through the incredibly slow route of Tiberium fuel cells and UUM. This puts a huge price on the UHV superconductor alone and addresses the overall core problems of this conductor being impossible to obtain.

### A New UEV Superconductor

So far, we do not have a UEV superconductor, and probably for good reasons. But there also isn't a lot of wires & cables beyond this point either, so a good time to possibly have one then for large amounts of amperage! Introducing the following two possible combinations of resources:
**UEV SC 1#** Also known as the switched UHV superconductor: 6 Awakened Draconium dust, 7 Cosmic Neutronium dust, 5 Infinity Catalyst dust, and 6 Americium dust.
**UEV SC 2#** 4 Fluxed Electrum dust, 5 Californium dust, 1 Infinity dust, 14 Awakened Draconium dust, 3 Flerovium, and 10 Oganesson gas. The color of the superconductor should be blue, perhaps the color of #3467ba.

One important note here. If UEV SC 2# is chosen, Flerovium MUST BE LOOKED AT AND CHANGED. Currently, it is most likely impossible to obtain Flerovium due to it requiring a massive amount of EU startup; most likely needs to be moved to the T3 fusion reactor. On the other note of Oganesson gas, it was recently added by Bartworks and is considered one of the rarest and most difficult gases to obtain and requires hefty amounts of resources, both creating it at first and using UUM. This can fit the overall difficulty and rarity of UEV superconductor quite well for an expensive superconductor.

Thoughts or questions?

Before you also ask, 'but Piky, you can use multiple gases with Bartworks, why not use Radon?' While yes, I could technically balance around Radon, it is a rather more expensive gas to use in comparison to Argon, which is infinitely obtainable, and this is mainly based around the average gas of average players that is likely to be used for these purposes. You can certainly use Radon or whatever gas you'd like for most recipes though.

**Comment by botn365** [comment]
for the UHV SC i dont think  ichrium should be used
ichorium is a magic item needs a lot of progresion in thaumcraft and i think it should not be used that is a pure tech related item

for xenon i dont like it becous at the current moment its most cost efective way of making is UUM i think that UUM should never beat the intendet process in terms of energy cost
onagasson has the same problem but these are more bartworks problems

one other problem with the MV SC is that it needs helium wich can not be easly obtained in MV

**Comment by BlackFlameTNT** [comment]
i would say the same about ichrium for UHV but i do like seeing new SC more powerful then UHV.

**Comment by basdxz** [comment]
Here's a question, do we really even need superconductors pre LuV?

**Comment by mitchej123** [comment]
> Here's a question, do we really even need superconductors pre LuV?

yes

**Comment by basdxz** [comment]
But why? Power loss has been a long standing mechanic since industrial craft and before a change that had redone super conductors to have real 0 EU/block loss along with adding the lower tier variants things were fine.

**Comment by Anarack** [comment]
Power loss is only sometimes relevant at hv and lower voltages, above that loss is trivial so no one uses them for the 0 eu/t loss. There main usage unless you are making very loss sensitive setups is the high amp limit of the cables or as crafting components.

**Comment by ScriptedPiky** [comment]
Yup, that is correct ^
Assuming if EU loss is changed in the future, then superconductors could become more relevant. But other than that, they are really only used for their amperage (if you're doing massive power generation setups) and for recipes. Also, I changed up the UHV & UEV SC, does this look fine so far?
UHV: 7 Tritanium dust, 3 Americium dust, 2 Unstable dust, 9 Indium dust, 2 Cosmic Neutronium dust, 8 Argon gas. Or otherwise known as `Tn7Am3?2In9InSpNt2Ar8`. It could also have no gas if desired.
UEV: 4 Fluxed Electrum dust, 5 Californium dust, 1 Infinity dust, 14 Awakened Draconium dust, and 3 Flerovium.

And about MV superconductor, should it take Nitrogen instead of Helium?

**Comment by AiramProvoker** [comment]
Just bumping it, because SCs really need to be more viable/interesting.
