### ISSUE TITLE
Simple Hand Pump + Diamond Tank Bug?

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#5203]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Tried to use the Simple Hand pump to grab 2000L of Lubricant from my Diamond Tank with ~60,000L of Lubricant. I expected to get 2000L in my Simple Hand Pump and have ~58,000L of Lubricant in my Diamond Tank.
#
#### What happened instead? (Attach screenshots if needed)
I got 2000L in my Simple Hand Pump and my Diamond Tank was set to have exactly 2000L of Lubricant left in it.
#
#### What do you suggest instead/what changes do you propose?
Can we just fix that?

**Comment by mitchej123** [comment]
Post on GT++'s github.

**Comment by draknyte1** [comment]
Fixed in Dev.
