### ISSUE TITLE
Remove Quest ID 2069 - Hot hot hot!

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#5207]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Supreme Pizza Gloves have no recipe.
Spawned a pair in to test if there was a reason no recipe was implemented.
Work but give permanent Fire Protection and you can stand in lava.
Need to remove the quest until the item is ready.

**Comment by richardhendricks** [comment]
We can hide it instead of removing it.

**Comment by draknyte1** [comment]
They have a recipe, it just doesn’t work in NH for some reason. I added it specifically because *someone* added the quest and thought there already was a recipe, We just never implemented it then heh. 

I’ve got an open ticket about it, so don’t need to make a new one.

**Comment by richardhendricks** [comment]
Quest is now hidden, must unhide once supreme pizza gloves recipe works again.

**Comment by DualBallers** [comment]
@richardhendricks A minor issue by hiding the quest. Now you will not get a green checkmark on the Tier 4 tab even when all visible quests in the tab are completed.

![image](https://user-images.githubusercontent.com/30087707/81222386-7f57d700-8fe4-11ea-84a6-cc81636e0e20.png)

**Comment by yukieiji** [comment]
This quest is currently only available via search. so I can't see it within the Quest tab.
