### ISSUE TITLE
Stellite rotor has no extruder recipe

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5208]
#### Which modpack version are you using?
2.0.7.5
#

Currently the stellite rotor has no extruder recipe, just a crafting one. Kinda odd given basically all other rotors have them, seems like an easy fix.

**Comment by Dream-Master** [comment]
From wich mod is that material @GTNH-Colen ?

**Comment by Spartak1997** [comment]
@Dream-Master all GT++ materials don't have recipe with your shapes.

**Comment by Dream-Master** [comment]
@GTNH-Colen ask alk to add it if you want.
