### ISSUE TITLE
problems with platinum quest line

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5221]
#### Which modpack version are you using?
2.0.8.0a
#
#### If in multiplayer; On which server does this happen? 
SSP
#
palladium quest line should be EV 

the hatch should be at the bottem should also be mentioned in the "back to step 1" quest

the "first seperation quest" needs 36 sodium sulfate cells or 5184L sodium sulfate and then you need 36 rhodium sulfate cells wich is 36KL

on the "rhodium" quest it sais that thodium is one of the most commen metals but thats a lie its the second most rare one

**Comment by bartimaeusnek** [comment]
@botn365 why do you think Palladium should be EV?

**Comment by botn365** [comment]
palladium hase some use in EV mostly tinkers tools and the mettal feels like the same tier as platinum

**Comment by richardhendricks** [comment]
added comment on bottom layer output hatch to "back to step 1" quest
changed from 36 potassium disulfate to 250 to align with 36,000L of rhodium sulfate
Changed from "most common" to "most useful"

Bart do you think we need to migrate the questline to EV?

**Comment by richardhendricks** [comment]
(quests listed are fixed for 2.0.8.0, migrate to EV, if necessary, will do in 81)

**Comment by Prometheus0000** [comment]
I really don't think it should be moved to EV, as it's primary use is IV+. TC tools are not enough in my opinion.
