### ISSUE TITLE
Can't put Molten Redstone into Empty Cells in Fluid Tank

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5225]
#### Which modpack version are you using?
2.0.7.5
#
#### What did you try to do, and what did you expect to happen?
I have Molten Redstone in one of the X Voltage Fluid Tanks that I got from a fluid extractor, but it won't fill the cell to become a Molten Redstone Cell. Other molten fluids work, so I'm not sure why this one doesn't? A Molten Redstone Cell won't empty into an empty tank either, but if it already has the fluid it just goes from input to output without doing anything. It works in the Fluid Canner though.
#
#### What do you suggest instead/what changes do you propose?
Fix it somehow, or explain why it shouldn't work?

**Comment by Dream-Master** [comment]
you need the other fluid cells @Prometheus0000 
![image](https://user-images.githubusercontent.com/2970688/71927138-1d51a700-3195-11ea-9d9f-c1141c4615be.png)
![image](https://user-images.githubusercontent.com/2970688/71927142-204c9780-3195-11ea-894a-e7f9ff4e0b71.png)
![image](https://user-images.githubusercontent.com/2970688/71927155-26427880-3195-11ea-92b9-3d7076a42e70.png)

**Comment by Dream-Master** [comment]
this cell not work
not ask me why
![image](https://user-images.githubusercontent.com/2970688/71927178-35c1c180-3195-11ea-9c79-15cc0760e730.png)

**Comment by Dream-Master** [comment]
Not sure if molten redstone is special

**Comment by Dream-Master** [comment]
Funny
this cell works in tanks
![image](https://user-images.githubusercontent.com/2970688/71927326-86391f00-3195-11ea-9f5c-dbc67f537528.png)

**Comment by Prometheus0000** [comment]
I used Empty Cells, the problem is that it doesn't work in the X Voltage Fluid Tanks (X=Ultra Low, Low, Medium, High), when everything else I used does.

**Comment by Dream-Master** [comment]
seems to be the one cell store 1000 mb and the other just 144 mb
![image](https://user-images.githubusercontent.com/2970688/71927452-cc8e7e00-3195-11ea-9997-66e6623ca4ba.png)

**Comment by Dream-Master** [comment]
some inconsitence idk why

**Comment by Dream-Master** [comment]
get a part filled cell 
![image](https://user-images.githubusercontent.com/2970688/71927481-e039e480-3195-11ea-9204-08cc56140178.png)

**Comment by draknyte1** [comment]
> X Voltage Fluid Tanks (X=Ultra Low, Low, Medium, High)

They inherit base GT Tank logic. Steam also won’t work. 

I feel it’s intentional tbh, but don’t quote me on that. Please refer to the discussion myself and other developers have had regarding this already. (Not sure what ticket # it is)

**Comment by Prometheus0000** [comment]
#4609 I believe? Didn't you just inherit the GT5U codebase or something? If you get time (and figure out if it's supposed to be intentional or not), maybe you can fix it, otherwise probably low priority (as in, off the must fix list). If you do fix it, don't forget the X-cracked stuff only working with Universal Fluid Cells too.
