### ISSUE TITLE
Neutronium fusion is a noob trap

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#5228]
2.0.8.0
there is no reason why this recipe should ever be used. even in its buffed form.

**Comment by GTNH-Colen** [comment]
I think we need to ask ourselves if we want fusion to be a primary source of neutronium later on and if so at what point/tier of fusion should that be gated behind.

I would personally like to see it in a tier 4 fusion reactor as currently there seems to be very little incentive for players to try and go for that particular beast (I think in the new update it's at least possible but need to check). The vast majority of other recipes it unlocks seems to be for god-tier materials that have virtually no use currently (Ie hypogen).

**Comment by BlackFlameTNT** [comment]
Neutroium for T4 fusion is impassable because T4 is UHV and the main matel for UHV is neutroium and for now fuison T4 is uncraftable due to assembly line recipes overlook that need fixing in GT++ side.

**Comment by draknyte1** [comment]
It *is* fixed, just not in the dev releases of GT++ being used. 

https://github.com/alkcorp/GTplusplus/pull/493

Current dev releases are based on DevTop branch, which doesn’t have this PR in it.
