### ISSUE TITLE
Reactor Enclosure options

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#5229]
Reactors due to the boosted max explosion limit of 100 are very difficult/expensive to safly block when not using blast proof methods.

To put it into perspective, 20 layers of reinforced stone is what it would take to stop a full power blast.

Our options are,

-  buff gt and possibly open modular turrets reinforced/hardened walls
- nerf the reactor explosion 
More things to discuss, how many blocks should be a ok amount of defense when compared to the many blast proof options. I would like to make this a viable options for players and not a massive resource hole.

**Comment by richardhendricks** [comment]
I think we could target 1 or 2 layers of reinforced materials. Right now the meta of fused quartz or warded glass is kinda weird for a tech focused modpack.

**Comment by Anarack** [comment]
gt++ wither proof blocks are other cheap ish option as well 3k blast resistance for tungsten steel and a nether star.

**Comment by Prometheus0000** [comment]
We have several X Plated Reinforced Stone. Presumably they were added to deal with this?
