### ISSUE TITLE
Friendly creeper can be infernal and attack you

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5232]
#### Which modpack version are you using?
2.0.7.5
#
The friendly creeper warp effect causes a non-hostile creeper to spawn near you that is not supposed to attack you, but just scare you. However, with berserk(I think this caused it?) it will. It might also need Alchemist/Ghastly to to do so. I had a Ghastly Berserk spawn in my base and start shooting fireballs at me, which is against the idea of the friendly creeper warp effect. I'm not sure if if would blow up normally with just berserk though.
#
#### What do you suggest instead/what changes do you propose?
I'm not sure there's anything you can really do, especially with how infernals are right now, but if you get more control over them, consider blacklisting this specific mob from being infernal, or whatever makes it attack you.

**Comment by wlhlm** [comment]
Infernal mods attacking friendly/neutral players should be fixed in  GTNewHorizons/atomicstrykers-minecraft-mods#1.
