### ISSUE TITLE
Minor issue filling cells from water tanks

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5235]
#### Which modpack version are you using?
2.0.7.5
#
#### What did you try to do, and what did you expect to happen?
Put a aluminium or stainless steel cell into a water tank (Railcraft) and get a bunch of water.
#
#### What happened instead? (Attach screenshots if needed)
They only fill to 16000L, doing it again empties them, same thing with higher tier cells.
#
#### What do you suggest instead/what changes do you propose?
Fix it or mention in a quest it doesn't work.

**Comment by richardhendricks** [comment]
AFAIK, it's a limitation on the Railcraft side, that we can't change.

**Comment by Prometheus0000** [comment]
I didn't really think you could fix it anyway (or that it would be worth it). For whatever quest it's mentioned in, maybe mention using a X Voltage tank (or higher) to fill them? Probably the quests that you make each of the cells in would be appropriate.
