### ISSUE TITLE
Obsidian stick/rod can't be crafted without smeltery

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5236]
#### Which modpack version are you using?
2.0.7.5
#
#### What did you try to do, and what did you expect to happen?
Make an obsidian stick/rod/tool rod without the smeltery.
#
#### What happened instead? (Attach screenshots if needed)
It needs to be made as an obsidian tool rod in the smeltery, not any other way, such as the extruder or lathe.
#
#### What do you suggest instead/what changes do you propose?
Add an extruder recipe for the obsidian ingots to get the tool rod, maybe a lathe recipe too. It just seems weird to have to keep the smeltery around for this one thing.

**Comment by Methes** [comment]
Obsidian is one of the few materials you can use directly in Part Builder without any Smeltery or Extruder involvement, like wood, stone, magical wood and thaumium.

**Comment by Prometheus0000** [comment]
Ah, I forgot about that, thanks. But you can't automate that though, and is even more "low-tech" than the smeltery, yeah? I still think lathe/extruder recipes should be added.

**Comment by richardhendricks** [comment]
I agree, since it is used for the obsidian drawer upgrades. Lathe recipe plz.

**Comment by GTNH-Afx237v7** [comment]
Don't know when this was added, but there is an extruder recipe for the obsidian tool rods (tested with 2.1.0.4.dev), so you are able to mass-produce the obsidian tool rods.
![grafik](https://user-images.githubusercontent.com/64365566/112047668-e3788080-8b4d-11eb-85a2-15abf1939123.png)
Guess this can be closed then.

**Comment by Prometheus0000** [comment]
Little annoying it's MV, but you don need an alu plate for the SD upgrade anyway.
