### ISSUE TITLE
Buff Chromite Veins on Moon

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#5241]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Consider increasing the chromite vein weight on the moon. It feels painfully low. Also worth considering lowering galena vein weight on the moon. The chalcopyrite veins seem to appear way too much as well but it seems people actually go to the moon to mine that?

**Comment by richardhendricks** [comment]
Ill try to get some numbers for a ore generation %.

**Comment by Dream-Master** [comment]
if you lower or increase a number the whole planet will change . Balancing it could be different. But @richardhendricks you are the oregen expert :)
