### ISSUE TITLE
Advanced solar solar panels do not output energy sometimes.

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#5242]
2.0.8.0 pre
They will only output power to gt cables when you connect them to a cable, they will not output power if the connection already exists.
If placed on this no output
![image](https://user-images.githubusercontent.com/20565115/71535421-a3cfd400-28cb-11ea-989e-3788f49ffe3e.png)
you have to manually connect the panel after placing.

**Comment by mitchej123** [comment]
Is this still an issue?
