### ISSUE TITLE
Galacticraft stones don't go into backpack

### ISSUE THREAD

**Issue by TimDiekmann** [GTNewHorizons/GT-New-Horizons-Modpack#5249]
#### Which modpack version are you using?
2.0.8.0pre

#
#### If in multiplayer; On which server does this happen? 
Private server

#
#### What did you try to do, and what did you expect to happen?
Tried to put Phobos stone, moon stone etc. in the forestry diggers backpack.
#
#### What happened instead? (Attach screenshots if needed)
It doesn't work.
#
#### What do you suggest instead/what changes do you propose?
Add blocks to forestry config.

**Comment by Dream-Master** [comment]
not close this now. After we make a new release. Thanks

**Comment by combusterf** [comment]
This is no longer working in 2.0.9.0 (it was known to work in 2.0.8.3, the previous version of Delta).

**Comment by Prometheus0000** [comment]
Add it yourself if you want it that bad.

**Comment by bombcar** [comment]
This would be nice tbh, the miner's works but digger's doesn't.

**Comment by Skiftcha** [comment]
> the miner's works

it would be nice miner's not filling with stones. only ores.
