### ISSUE TITLE
Twilight Performance Issues Talk.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#5250]
So we had a talk today about Twilight Forest. It was me talking about wanting to ban the use of Gliders in Twilight due to the performance issues. Twilight not just heavy on first time Generation but even exploring pre-generated worlds. This performance hit is easily noticed on the world's ms that increases when people are visiting the world.

@richardhendricks recommended us to post it on here.

Now Phosphor Mod in 1.12 did massive improvements to TF and a few other areas. I wanted to share that picture here now:
![am2h638nf5p21](https://user-images.githubusercontent.com/425853/71561426-457a3100-2a44-11ea-96e0-340db17827d9.png)

Now keep in mind it's not about just world Generation but load time of pre-gen worlds. I'm sure you admins out there seen it when users are in TF.

What is strange the mod was for 1.12 as well but I can't find the source just the 1.14 stuff:
https://github.com/jellysquid3/Phosphor

Might not been open source yet...

The Mode that includes 1.12:
https://www.curseforge.com/minecraft/mc-mods/phosphor

I asked Tama for tips and was told:

> you cant really improve TF 1.7 without ripping the codebase apart
> it has a LOT of issues
> lighting is the least of the issues
>

**Comment by Dream-Master** [comment]
Twilight Forest is open source for 1.7.10 and the guy make the mod "Benimatic" is online some time on my discord.
@KaneHart

**Comment by richardhendricks** [comment]
Yes, we talked about it on Discord. I want to take a look at this in 8.4 or 8.5. If rhey did something in phosphor maybe we can put it directly into Twilight Forest.

**Comment by richardhendricks** [comment]
https://github.com/jss2a98aj/twilightforest
Looks like someone is working on Twilight Forest in 1.7.10
Other things to look at
- [ ] Create custom damage sources so that other mods, ie Special Mobs, can behave appropriately with damage from frost, etc.
