### ISSUE TITLE
fitting cabinet stuff disapear when inventory full

### ISSUE THREAD

**Issue by ponenerve** [GTNewHorizons/GT-New-Horizons-Modpack#5252]
#### Which modpack version are you using?
1.0.8

#### If in multiplayer; On which server does this happen? 
solo
#### What did you try to do, and what did you expect to happen?
i just wanted to take some PVC cells out of my fitting cabinet but i didnt noticed my inv was full
#### What happened instead? (Attach screenshots if needed)
the 96 cells retracted to 64 without been given i tried it on useless stuff it did the same
#### What do you suggest instead/what changes do you propose?
fixing it x)

**Comment by richardhendricks** [comment]
So the filing cabinet had 96 cells, you tried to retrieve them, and instead of giving you any cells, it reduced to 64 in the filing cabinet?

**Comment by combusterf** [comment]
I managed to reproduce the bug as follows:
- Load a filing cabinet with identical but unstackable items (you can reuse one with looted bows or armours). In the GUI you do see a stack counter appear. Find an entry with 5+ items for visibility.
- Occupy your inventory with different items. Leave exactly one slot free
- Shift-click from the 5+ stack. The item moves to your inventory and the counter decreases as expected. Your inventory is now full
- Shift-click from the same stack.
- Observe that the requested stack is instantly reduced to 1 item.

Server is Delta, modpack version 2.0.9.0

**Comment by Aragnir** [comment]
it's still there 2.1.1.0 version on eta.

**Comment by repo-alt** [comment]
ExU is ARR (and closed source for 1.7.10)
