### ISSUE TITLE
Coin shop broken timer

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5253]
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Eta
#
For some reason when switching dimensions occasionally the timer on the coin shop will reset, I can't seem to reproduce it on a consistent basis but have managed to get it to occur a couple of times in a row so it is definitely happening. This is not just a visual bug as I have been able to purchase items multiple times just by going in and out of a dimension.

In addition to this when switching dimensions the timer will sometimes default to an insanely high number such as 300000 minutes.

**Comment by boubou19** [comment]
let's wait and see if it still occurs in Better Questing 3 in the next release i guess

**Comment by Prometheus0000** [comment]
Is this fixed?

**Comment by Dream-Master** [comment]
I wait for feedback on zeta. @GTNH-Colen is this fixed ?

**Comment by PredVesTNiK2142** [comment]
2.0.9.0 QF4 Duplicate quests still do not work
