### ISSUE TITLE
[Suggestion] Long Distance Transfer System

### ISSUE THREAD

**Issue by Methes** [GTNewHorizons/GT-New-Horizons-Modpack#5257]
When dealing with large distances as 500 blocks or more, you don't have many choices regarding transportation of energy/items/redstone signal.
You _can_ run a 500 blocks long pipe but you'd also have to chunkload the whole line which is a big nono.
You can also use carts but those have limited throughput, are buggy and require chunkloading cart as well.
Then there's teleportation via various means but those are gated pretty far and not as cool.
That's why I've come up with LDTS - Large Distance Transfer System.

**Function:**
Whole line has just two active blocks - transceiver and receiver (interchangeable freely on the fly)
All other blocks are simply passive and visual placeholders adding no load to the server.
Energy/Item/Fluid/Redstone signal transport happens only between the first and last blocks which of course need to be loaded.
It's essentially a teleporter with a cable.

I'd like to see it tiered at HV+
Energy loss should be not large and decrease with tier - reaching almost 0% with higher tiers (why run LDTS with 5% loss when running 1000 blocks with LuV voltage has 3% loss).
Controllers can be moderately expensive, Relays should be cheap to be spammable.

**Mechanism:**
**Placing the Transportation Controller Block**
 - generate a unique database ID upon placing, set invalid boolean state and disconnected boolean state
- Controller Block is active only when valid and connected.
- scan surrounding connected blocks for a Relay.
  - if one valid and with ID, inherit its ID, checks database for the same ID and if no problems, set itself to valid and connected - network ready
  - if one invalid with ID, remove it from problematic list, inherit its ID, checks database for the same ID and if no problems, set itself to valid and connected - network ready
  - if two Relays are found, do nothing (can't connect to multiple relays)
 - Controller Connection check - check connected Relays and if valid with same ID, set itself to connected

**Placing the Transportation Relay Block**
 - set invalid state and no database ID
 - scan surrounding connected blocks for a Controller or Relay.
  - if an invalid disconnected Controller is found, inherit its database ID and set itself to "valid" boolean. Set Controller to connected boolean.
   - if an invalid connected Controller is found, set Controller to disconnected. (can't connect multiple relays to a Controller)
  - if a valid Controller is found, set the Controller to disconnected (can't connect multiple relays to a Controller)
  - if an invalid Relay with no ID is found, do nothing
  - if one invalid Relay with ID is found, inherit its ID, set it to valid and set itself to valid and remove the found one from problematic list (continuing broken line)
  - if two Relays with same ID are found, either valid or invalid, inherit their ID, set all 3 to valid and remove invalid ones from problematic list (reconnecting broken line - see breaking a Relay)
  - if one valid Relay is found, inherit its ID and set itself to valid (continuing the line)
  - if two valid Relays are found, do nothing (either two different lines or one line going close together for some reason - player's issue)

**Breaking Relay**
 - if valid, check connected Controllers and set them to invalid and disconnected, check connected Relays and set them to invalid, add those invalid Relays' coordinates and ID to problematic list (breaking a line either at the end or in the middle)
 - if invalid with no ID, check connected Controllers and run Controller connection check
 - if invalid with ID, remove itself from problematic list, check connected Relays and set them to invalid, add those invalid Relays' coordinates and ID to problematic list (further breaking a line either at the end or in the middle) 

**Breaking Controller**
 - if connected, check connected Relay and set it to invalid, add the invalid Relay's coordinates and ID to problematic list
 - if valid, invalidate the second Controller with same ID
 - if no other controller with same ID exists, delete whole problematic list
	
I probably ommited some scenario but it should handle building a line, breaking a line from an end, breaking and rebuilding a line even with different path in the middle, trying to connect different lines or same line multiple times, trying to connect multiple lines to a controller.
All that with very little CPU overhead, only saving IDs and problematic blocks that get deleted when breaking them so even if you remove 1000 blocks from the middle of a line the list should have only 2 entries unless you break every other Relay.

**Comment by Scottishprog** [comment]
I can second something like this.... Allows remote installations without the need for inter-dimensional teleportation.

However, I will make a suggestion: Don't require the cable between the endpoints - have some other means of linking the two. In short, single dimension teleportation.

That said,  a solution like this, with or without the cable, will be appreciated.

**Comment by draknyte1** [comment]
GT++ has tesseracts for interdim

**Comment by Scottishprog** [comment]
Gated at LUV - I think the demand is for intr**a**-dimensional transfer at a much lower tier.

**Comment by bigbass1997** [comment]
There is RemoteIO in the pack, which allows inter-dimensional transfer of pretty much everything you'd ever need.

**Comment by repo-alt** [comment]
Currently for energy we have microwave transmitters (early EV) , and for the items/fluids there is EIO transceivers which (late EV), (There are also TC mirrors, which are HV, but are not reliable w/o CV, which is EV too I think). GT++ tesseracts are late IV, looking at the recipe? Do they works like GT6 tesseracts? Did anyone tested them? There are also ender chests/tanks and Jabba b-space upgrade. 

Railcraft long distance lines need not be chunkloaded, anchor carts work just fine, but it cannot be very reliable system due to cart duplication/disappearing bug. Disappearance can be circumvented with timer checks for missing cart and launching a replacement automatically. I general this is a fun system, for someone who did not do that before. Train routing has OC integration.

**Comment by Methes** [comment]
I understand you all post alternatives to the system, offering true wireless methods.

I thought having actual powerlines and oilducts running across the world with no server overhead would appeal to people, apparently every

**Comment by repo-alt** [comment]
Not really. Alternatives are necessary to balance the idea against.

**Comment by bigbass1997** [comment]
I can't state whether or not _everyone_ wants one thing or another. However, in response to 
> When dealing with large distances as 500 blocks or more, you don't have many choices regarding transportation of energy/items/redstone signal.

we actually do have many choices, with their own pros and cons, and their own tier/material restrictions. I also think the common thought is that these teleportation solutions, should be rather high tier or otherwise expensive due to the power such a solution has.

**Comment by Scottishprog** [comment]
If that is the case, the single dimension options are tiered too high.

The can be expensive at tier, but I think these types of solutions need to be available sooner.  Low tier traveling is time consuming. And I would like to spend that time on other things.

That said, this becomes a design/balancing decision, I have just stated my (mild) dissatisfaction with the current balance.

**Comment by bigbass1997** [comment]
What exactly do you need to be transporting long distances before such options are available?

**Comment by Scottishprog** [comment]
Multi-block oil wells are the main need.   But I would like to have the option of sub-bases, powered by the central base.... I just find the lack of automatic long range transportation a bit confining.

However, I can work with the current state... I am stating a preference - _not_ a game-breaking situation.

**Comment by richardhendricks** [comment]
Arent RemoteIO and Wireless Redstone slated for removal due to bugginess?

**Comment by bigbass1997** [comment]
@richardhendricks Idk where you heard that. Wireless Redstone has been fixed in #3375. I haven't heard about any bugs from RemoteIO, and I've used it myself without issues.

**Comment by bigbass1997** [comment]
I see #3487 which doesn't include any crash logs. And the mod arguably has a lot more functionality than what is explained in that issue thread. Plus we haven't had any new reports about the mod for over a year now.

**Comment by yukieiji** [comment]
I agree with this suggestion, but I think its mechanism is complex.
There are machines with similar functions in GT6, it is simple and easy to use. So I think that the mechanism suggestion should be simpler.

・GT6 Long Distance pip and transformer
[Long Distance Transformer](https://git.gregtech.overminddl1.com/GregTech-6/GT6/src/branch/master/src/main/java/gregtech/tileentity/energy/transformers/MultiTileEntityLongDistanceTransformer.javal)
[Long Distance ItemPipe](https://git.gregtech.overminddl1.com/GregTech-6/GT6/src/branch/master/src/main/java/gregtech/tileentity/inventories/MultiTileEntityLongDistancePipelineItem.java)
[Long Distance FluidPipe](https://git.gregtech.overminddl1.com/GregTech-6/GT6/src/branch/master/src/main/java/gregtech/tileentity/tanks/MultiTileEntityLongDistancePipelineFluid.java)

**Comment by koiNoCirculation** [comment]
Use EIO Dimensional Transreviever at EV level.
