### ISSUE TITLE
Add recycle recipes for unwanted Hatches of all kind?

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/GT-New-Horizons-Modpack#5263]
# 
#### What happened instead? (Attach screenshots if needed)
you cant put an input bus, for instance, in a disassembler nor in an arc furnace.
#
#### What do you suggest instead/what changes do you propose?
add a recipe to recycle unwanted buses, fluid-/ energy hatches..etc.

**Comment by Prometheus0000** [comment]
@redmage17 Weren't you going to do this too?

**Comment by repo-alt** [comment]
Looks like HV energy hatch for some reason does not have disassembler recipe too

**Comment by redmage17** [comment]
Yes it's on my list let me bring up a discussion before I code

**Comment by Prometheus0000** [comment]
Is this needed anymore? You can disassemble the hatches/busses now. And the coils, too.
