### ISSUE TITLE
[ExtraCells2] Bug with Crafting Storage Unit

### ISSUE THREAD

**Issue by 4gname** [GTNewHorizons/GT-New-Horizons-Modpack#5264]
#### Which modpack version are you using?
2.0.8.0
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
I was expecting the crafting storage unit to connect to the ME system.  This did not happen
#
#### What happened instead? (Attach screenshots if needed)
ME can't see the crafting storage unit

![image](https://user-images.githubusercontent.com/50260829/71644417-9024d300-2cfa-11ea-9d40-3e1ef413e51b.png)

![image](https://user-images.githubusercontent.com/50260829/71644438-f3166a00-2cfa-11ea-8352-e98222f2f9b7.png)

#
#### What do you suggest instead/what changes do you propose?
Fix bug pls. I think the problem is in one of the class with "return" to 1k AE crafting storage unit

**Comment by Prometheus0000** [comment]
From Retster in the other issue
> Got same issue at 8.8 when connect 2*256 Crafting units, but when connect to them another unit with 16K then all storage is used properly.

So you can use them if you add in a normal one until/unless they get fixed

**Comment by repo-alt** [comment]
That should be fixed I think
