### ISSUE TITLE
GT++, possibly others, Strange efficiency tool tip

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#5272]
![image](https://user-images.githubusercontent.com/20565115/71690440-5ab7ce00-2d6a-11ea-818d-20fa760b6b0b.png)
It does not to the best of my knowledge affect how the multi runs.

**Comment by Anarack** [comment]
![image](https://user-images.githubusercontent.com/20565115/71690646-e6315f00-2d6a-11ea-9163-f3557e59538b.png)

**Comment by draknyte1** [comment]
No fucking idea. The default value on all multis should be 10000 and I don’t think the code on any multi ever adjusts that. It’s a value I never use anywhere myself, so unless GT does internally, no idea. Efficiency on my multis holds no value and it would be better if WAILA didn’t show it at all.

**Comment by richardhendricks** [comment]
https://github.com/alkcorp/GTplusplus/blob/470d876b83e1ccb28c135203b93ed3cb500d711d/src/Java/gtPlusPlus/xmod/gregtech/common/tileentities/machines/multi/production/GregtechMetaTileEntity_IndustrialFishingPond.java#L543
Doesn't repair status effect recipe voiding or EU usage, like other multis?
I don't see anything weird in there, looks fine to me.  I'll need to see it in-game to try and understand why it is doing what it is doing.

**Comment by mitchej123** [comment]
If someone wants to provide a list of machines to whitelist effeciency status on I can do that instead.  (or a blacklist)  Right now it just pulls it off the multiblock.   GT does do some wonky stuff with it.
