### ISSUE TITLE
2 Types of Dirt

### ISSUE THREAD

**Issue by r2go-beep** [GTNewHorizons/GT-New-Horizons-Modpack#5273]
#### Which modpack version are you using?
1.7.10 - 2.0.8.0  24-Dec-2019 10:38 from ClientPacks
#
#### If in multiplayer; On which server does this happen? 
N/A 
#
#### What did you try to do, and what did you expect to happen?
Harvest Smoldering Grass Block 759:1 to get dirt, expecting to drop Dirt 3
#
#### What happened instead? (Attach screenshots if needed)
Drops "Dirt 3:1", which is unusable in crafting recipes and doesn't stack with Dirt 3
#
#### What do you suggest instead/what changes do you propose?
Smoldering Grass Block drops Dirt 3 instead of Dirt 3:1

**Comment by Dream-Master** [comment]
need to add an recipe to convert it.

**Comment by Dream-Master** [comment]
which mod add smoldering grass @r2go-beep  ?

**Comment by r2go-beep** [comment]
Biomes O' Plenty

**Comment by Bluebine** [comment]
Dirt 3:1 is actually a thing in vanilla- it's regular dirt, but it can't grow grass. IMHO should stay as a separate block, but  be usable in recipes that dirt is.

**Comment by Dream-Master** [comment]
thats to complicated. Will make a recipe wich can exchange this block. Its just dirt

**Comment by Prometheus0000** [comment]
This is so incredibly pointless.
