### ISSUE TITLE
Cleanroom Hull amount increase

### ISSUE THREAD

**Issue by MineAnPlay** [GTNewHorizons/GT-New-Horizons-Modpack#5277]
Increasing the max machine hull count would make the Cleanroom automation a little bit easier and we wouldn't be required to use wireless AE within the Cleanroom to automate everything. Would make automation before AE also easier, and actually make it possible.

I don't know a direct amount but maybe 10% of the Plascretes could be converted to Machine Hulls. People can discuss the amount to be determined here.

**Comment by richardhendricks** [comment]
For numbers, a 3x3x3 interior space cleanroom needs 
5x5x5(outer layer) - 3x3x3(inner core) - 3x3(top layer) - (1+1) (maintenance + power) = 87 plascrete.

7x7x7 interior space cleanroom needs
9x9x9 - 7x7x7 - 7x7 - 2 = 335 plascrete

**Comment by richardhendricks** [comment]
Also need to make sure we account for tall skinny cleanrooms for cheapasses who don't want to make filter casings.

**Comment by drayath** [comment]
What about 1 machine hull allowed per filter casing. Easy for the user to calculate, slight discouragement for cheapskates, and almost realistic (more filters allows more holes in the wall)

**Comment by bartimaeusnek** [comment]
I dont see a reason for this, since we have diodes. At least not for power.

**Comment by richardhendricks** [comment]
This is not about power etc.  The point is that as-is the cleanroom can take 10 pass through hulls, including fluids and items.  If you want to automate the cleanroom at higher tiers, more pass through hulls would be useful, esp. if based on the size of the cleanroom.  We can use similar logic to the reinforced glass option to support this.

**Comment by draknyte1** [comment]
Just allow (aFilterCount \ 2). Scales decently imo.

**Comment by Prometheus0000** [comment]
Not that I'm opposed to this or anything, but did no-one think to use Transvector Interfaces? It's ludicrously simple to use them, and the main cost is the 4x HV circuits.
