### ISSUE TITLE
Evaluate multiblock ore drill speed/rebalance fluid use

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5278]
Multiblock ore drill speed is not very fast. Players would like to speed it up. Should it compare to Ender Quarry?

Also, would be interesting to have more fluid options.

So, suggestion:

~~- [ ] Reduce fluid use at the drill by 10x. Increase the lube/stone dust use in the mixer by 10x to compensate. This way players can use 256B drums to provide drilling fluid instead of needing bedrockium drums.~~ Players seem ok with this as-is.

- [ ] Increase drill base speed. For tier 2, base speed is 2s, adjust up/down appropriately for other tiers. Base speed - need to determine how this applies per tier. Should it all be respect to LV? Or LV = tier 1, MV = tier 2, etc?

- [ ] Add API to add custom advanced fluids, and how much faster they are compared to default. IE, fluid.advlube or whatever. Could be 4x faster, maybe add higher tier options.

- [ ] Let overclocking dictate base speed adjustments. Let advanced fluid speeds dictate how many blocks are picked per operation. Basic drilling fluid = 1x. Advanced = 4x. Maybe faster ones?
- [ ] Add a second fluid hatch for concrete? Let the machine place concrete in the drill holes. Dunno if that matters.

**Comment by bartimaeusnek** [comment]
>  Reduce fluid use at the drill by 10x. Increase the lube/stone dust use in the mixer by 10x to compensate. This way players can use 256B drums to provide drilling fluid instead of needing bedrockium drums.

I'd like to veto on that. This would make it too easy to place down miners. The easiest thing to do this is currently with IntraDim Fluid transfer and im quite happy about that.

**Comment by draknyte1** [comment]
Void miner is pending SOMEONE wrote up ore lists for it.. we could have that for 2.0.8.

Already a concrete backfiller. 

API is useless, I won’t use it, why I suggested you just look up the fluid by name.. no hard dependencies.

**Comment by richardhendricks** [comment]
Need to propose recipe for decamethylcyclopentasiloxane https://github.com/alkcorp/GTplusplus/issues/550
And also need to come up advanced drilling fluid recipe based on it

**Comment by richardhendricks** [comment]
The API isn't for you, it's for us to add a fluid to the miner.

**Comment by draknyte1** [comment]
That’s just redundant code though.. you can be explicit in NH code because you can expect things to exist.. 🙃 

Even if they don’t, no harm done polling for fluids if they don’t exist.

**Comment by richardhendricks** [comment]
@bartimaeusnek I don't get why you think intradim fluid transfer should be required? Players get drums/bedrockium drums right at the moon, so it makes sense to use those to transfer large fluid amounts like this.

**Comment by bartimaeusnek** [comment]
bedrockium drums or intradim transfer is both fine for me. I just dont want it to be that easy to slap down a single drum and be done with it.

**Comment by repo-alt** [comment]
I seriously doubt anyone will supply concrete, but this part is very easy to implement. (couple of lines change)

**Comment by richardhendricks** [comment]
Well, stone dust is part of the recipe for drilling fluid, we could just have it place down a stone block. Just thought it would be a good idea for servers if some poor noob comes along to your depleted chunks and tries to setup there LOL.

**Comment by repo-alt** [comment]
Placing stone instead of air? what about other planets/dimensions? But I like that idea, Ender Quarry places dirt after itself for a reason. I wonder why it was not done from the start

**Comment by richardhendricks** [comment]
well, the GT miners don't do a block update (that's why the area is unlit until a player does something), to prevent lighting change lag I guess.

yeah other planets/dims would be an issue, or we could have another list of dim/rock to replace. :D

**Comment by repo-alt** [comment]
Actually the only harm of the random holes in the world is additional spawn places, which may not matter much for miners because they are used mostly in deserted places, and if you use a miner right next to the base - use concrete backfiller. On the other hand I cannot think of any reasonable _objections_ to place stone instead of air, even on planets.

**Comment by richardhendricks** [comment]
Changing fluid usage is off the table for now.
