### ISSUE TITLE
insufficient Ae2 waila overlay

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/GT-New-Horizons-Modpack#5286]
#### Which modpack version are you using?
 pre8.0

# 
#### What did you try to do, and what did you expect to happen?
looking at an interface/ input bus/ p2p etc.
# 
#### What happened instead? (Attach screenshots if needed)
![2020-01-05_23 10 14](https://user-images.githubusercontent.com/58643870/71786863-f9fdef00-3010-11ea-9f28-0168df0c7b7d.png)
#
#### What do you suggest instead/what changes do you propose?
changing "Ae2 cable and/or Bus" so you can identify the item without clicking it. since it can cause some trouble wit p2p´s.

**Comment by mitchej123** [comment]
Is this behavior different in 1.12?

**Comment by GeicowithaBango** [comment]
i dont know. the "bug" come with the update from 7.5 to pre8.0

**Comment by mitchej123** [comment]
Please provide a screenshot of the expected behavior if it changed.

**Comment by repo-alt** [comment]
I remember someone doing p2p channel display backporting...
In 7.5 p2p looked like this:
![image](https://user-images.githubusercontent.com/23512002/71787279-e6f61980-3026-11ea-880b-6a20229ac99c.png)

**Comment by GeicowithaBango** [comment]
![2020-01-05_23 53 30](https://user-images.githubusercontent.com/58643870/71787467-62040380-3018-11ea-9679-aab0840428f8.png)
![2020-01-05_23 53 57](https://user-images.githubusercontent.com/58643870/71787468-64665d80-3018-11ea-91dc-2c71c7c30122.png)

yes. this is it how it looked in 7.5

**Comment by mitchej123** [comment]
What version of ae2 do you have in your 2.8 folder and 2.7.5 folder?

**Comment by GeicowithaBango** [comment]
ae2stuff-rv3-0.5.1.9-mc1.7.10 for pre8.0

appliedenergistics2-rv3-beta-17.bps for 7.5

**Comment by repo-alt** [comment]
pre4 apparently includes appliedenergistics2-rv3-beta-20.jar

**Comment by Dream-Master** [comment]
no 19 it was wrongly nemed as 20 @repo-alt 
Version 20 crash the Server
