### ISSUE TITLE
Obsidian Totem recipe suggestion

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5288]
#### Which modpack version are you using?
2.0.8.0pre4
#
They're used in a couple of recipes like the Osmotic Enchanter (and you need several nearby) or Master Ritual Stones, but the only way to get them is worldgen. IE: The totems with a sinister node in them, the wisp spawner+chest in high places. This might limit the number of BM rituals you can have if they're picked over in multiplayer.
#
#### What do you suggest instead/what changes do you propose?
A recipe for them similar to the Obsidian Tile one, 4xTile=4xTotem.

**Comment by richardhendricks** [comment]
Should need something greggy I think. Maybe an infusion with something included?

**Comment by Prometheus0000** [comment]
Well, keep in mind you can get them from worldgen, this is just for people who can't find any, I dunno if it needs to be hard. Also, if you make this harder, you should (maybe) make the tiles harder too. How about just changing them both to infusion recipes of the same thing? 3+1 = higher tier obsidian. Essentia should maybe include Tenebrae and/or Perditio + Terra. Hmm, but I just checked, and tiles are used in ritual stones, which you would need, like, dozens or hundreds of if you get serious. Maybe put Tiles in the Arcane Worktable instead? Totems being an infusion recipe wouldn't affect things much though.

**Comment by richardhendricks** [comment]
Sounds fine to me.
