### ISSUE TITLE
Enhanced Charm recipe is a joke

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5304]
#### Which modpack version are you using?
2.0.7.5
#

The current enhanced charm recipe is an absolute joke and I think any player that has reached the endgame knows this. The issue has been brought up time and time again with no resolution in sight so i'm proposing the current change. 

<img width="455" alt="Screenshot 2020-01-08 at 17 33 28" src="https://user-images.githubusercontent.com/54497873/72001494-80971400-323d-11ea-9389-2ca90d7c4604.png">

This is a much more reasonable recipe, for those who are unaware the current recipe requires over **14,000 Infinity Ingots** which for a device that simply saves a few minutes of flying is absurd.

https://github.com/GTNewHorizons/NewHorizons/compare/master...GTNH-Colen:patch-1

**Comment by Cinobi** [comment]
Sounds reasonable, but it might look better to replace draconium with Adraconium, and 4 blocks of cosmic neutronium maybe.

**Comment by GTNH-Colen** [comment]
Yea can do that if people want, did think the use of normal draconium was a bit too low.

**Comment by KaneHart** [comment]
Great suggestion.

**Comment by Dream-Master** [comment]
@GTNH-Colen i think we need to balance all teleporter not just this recipe.
I cant say for sure if this is balanced after the change when i not seen the other teleporter.

**Comment by Dream-Master** [comment]
is this now located in zpm tier ?

**Comment by GTNH-Colen** [comment]
This would tier it at UV+ given that it requires draconic cores. I do agree that most teleportation devices need to be rebalanced really because currently a lot of them are so expensive that they may as well not be craftable currently.
