### ISSUE TITLE
Issue with loot games load on client (phase 2)

### ISSUE THREAD

**Issue by quedral** [GTNewHorizons/GT-New-Horizons-Modpack#5309]
#### Which modpack version are you using?
2.0.7.5 & 2.0.8.0pre4
#
#### If in multiplayer; On which server does this happen? 
SP MP doesn't matter in this case
#
#### What did you try to do, and what did you expect to happen?
While loading the client Loot games stalls like 5 minute if it fails to connect to pastebin (which is blocked via firewall):
https://pastebin.com/raw/x1K80mwb
#
#### What happened instead? (Attach screenshots if needed)
this is 4 lines of fml-client log regarding the issue:

> [14:38:05] [Client thread/INFO] [LOOTGAMES/lootgames]: Worldgen enabled in DimensionID 0 with Rhombus Size 12
> [14:43:11] [Client thread/WARN] [YAMCL/lootgames]: Unable to connect to https://pastebin.com/raw/x1K80mwb. DonorController will not do anything!
> [14:43:11] [Client thread/TRACE] [lootgames/lootgames]: Sent event FMLPreInitializationEvent to mod lootgames
> [14:43:11] [Client thread/DEBUG] [FML/]: Bar Step: PreInitialization - LootGames took 305.853s
> 

#
#### What do you suggest instead/what changes do you propose?
mod should check if it can connect to pastebin or not and give up after 5 seconds if cannot.

**Comment by Dream-Master** [comment]
we can move this to us server @Namikon ?

**Comment by draknyte1** [comment]
Not an issue of hosting. 

Shit code is the problem, it should time out in a timeframe shorter than several minutes.

**Comment by bigbass1997** [comment]
Here's the source points of interest:
LootGames: https://bitbucket.org/Namikon/gameoflights/src/e93c4afd321bf2ba1fd65ef26293fe16e7fd806a/src/main/java/eu/usrv/lootgames/LootGames.java#lines-77

YAMCore: https://github.com/GTNewHorizons/Yamcl/blob/master/src/main/java/eu/usrv/yamcore/auxiliary/DonorController.java#L29-L50

So this is actually something that should be changed in YAMCore (Yamcl), not LootGames.

**Comment by richardhendricks** [comment]
What's the point of the donor list in *lootgames* of all places?

**Comment by bigbass1997** [comment]
Best guess those are people who have donated directly to Namikon. But idk what exactly his intentions were with that mechanic.

**Comment by bigbass1997** [comment]
The 4 UUID's from the pastebin come back to (respectively):
```
Namikon
DreamMasterXXL
_Technus_
hhheeexxx
```

**Comment by TimeConqueror** [comment]
Fixed in LootGames 1.0.19: https://www.curseforge.com/minecraft/mc-mods/loot-games/files/3159655

**Comment by Dream-Master** [comment]
We need this repo in the GTNH project and link it to the existing jenkins project.
