### ISSUE TITLE
Creeper fish rebalance

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5315]
Creeper fish are annoying as well.  This ticket is to discuss rebalancing.

- Reduce the amount that spawns globally
- "groups" can be same size
- Change their attack profile so they cannot leap out of the water
- Lower their damage...
- ..but make them faster. Not quite fast enough to catch a boat, but enough to make you worry
- drops fish if killed

Also, add a new "baby creeper fish" that will populate lakes/rivers
- very small groups
- much lower damage
- drops fish if killed

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/72174538-9ae90300-339f-11ea-8a2a-dce5bc2c531c.png)

**Comment by richardhendricks** [comment]
![image](https://user-images.githubusercontent.com/1214811/72174558-a3d9d480-339f-11ea-93f3-23606f56a4ab.png)

**Comment by KaneHart** [comment]
Okay keep them in oceans lmao. RWG players are safe till Twilight haha. Water creepers though and their spawns are totally broken and I'm speaking about performance not difficulty here. Our first encounter in Twilight ocean was really painful performance wise in an already laggy world.

**Comment by Prometheus0000** [comment]
Was this the removed aqua creepers?
