### ISSUE TITLE
Move Quest: Playing with the Big Boys (2397)

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#5318]
#### Which modpack version are you using?
2.0.8.1
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What is the problem?
the controller needs stainless steel, so LV tab is _a bit_ unrealistic. Should go to late MV or better HV. It also need an MV assembler.

Edit: Btw, is the **SIZE** of the quest intended?

**Comment by Bluebine** [comment]
Should be in multiblock goals tab... it's a multiblock, after all. Needs MV assembler and stainless steel, so unlock after those two.

**Comment by chochem** [comment]
maybe better gt++ tab then

**Comment by richardhendricks** [comment]
well, it's a BIG chemical plant, it deserves a BIG icon. :)

**Comment by richardhendricks** [comment]
Looks like the recipe is HV since it needs a stainless steel frame box. Placed after HV Chemical Reactor for now.
Added info from screenshot on valid solid casings and pipe casing

![image](https://user-images.githubusercontent.com/1214811/72228676-81e27c80-356e-11ea-8a1f-19ae0959f44a.png)

**Comment by richardhendricks** [comment]
GT++ has retiered the chemical plant, need to look at latest GT++ build and place in appropriate tier.
