### ISSUE TITLE
Additional quest information on trees

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5330]
From leagris

Best traits:
Mature: Faster → Apple Oak (fruit ripening and sapling growgth speed)
Yield: Hier → Chilli Pepper (drop chance for fruits and generating fruit pods)
Saplings: High → Balsa (saplings drop chance)
Hight: Gigantic → Giant Sequoia (Villager deal only, no crossbreeding)
Girth: 4×4 → Giant Sequoia (see above)
Sappiness: High → Blue Mahoe (best fermentation multiplier)

Fruit for maxiumum fruit juice per fruit:
Papaya or Grapefruit

Fruit for maximum mulch per fruit:
Plum

Fruit for maximum seedoil:
SweetChestnut

Tree for best regular shape amount of leaf blocks and wood that can also bears fruits:
SweetChestnut
So for best fruit juice at highest density:
Balsa tree, holding papaya pods, with gigantic trait from Giant Sequoia, hich yield from Chilli Pepper, Faster mature from Apple Oak
For balanced Fruit Juice and Mulch and simplest tree farm ever:
Chestnut tree with Apple fruit, Mature Faster, Higher Yeild from Chilli Pepper, and Sappiness High from Blue Mahoe...
Apple fruit has the perfect balance between amount of juice and amount of mulch for the Forestry fermenter.

Apple fruit also drop with harvesting the tree so does not need a Forestry Farm in orchard mode.
It also aloow you use the wood
Drawback is you have to provide farm with dirt supply as soil decay into sand
Or use any other kind of automated farm, and it will drop you apples without costing you dirt

But if better production if you don't mind a bit less wood, opt for a girth 1x1 Chestnut tree
Yes gigantic heigh also helps
Forgot the Fireproof trait from Gig Sequoia and some other specie

For balsa tree holding papaya fruit pods in a Forestry Multifarm Orchard
Layout like: (T: tree, L light source or spacer)
TLLTLLTLL…
LTLLTLLTL…
LLTLLTLLT…
…

This allow each trunk to have its own fruit pods without blocking pods from neighbor tree.
Each balsa trunk is surrounded by 4 light sources at its base and can have its own pods at all sides.

Yous all you want, (nobody should be attributed for knowledge other than thank you)One other info about growing forestry trees
when using fertilizer/bonemeal on sapling
When girth is 2×2
Bonemeal the North-West saplng
X.
..
When girth is 3×3
Bonemeal the center sapling
...
.X.
...
When girth ix 4×4
Bonemeal the center NW sapling
....
.X..
....
....
Do not bonemeal/fertilize other saplings, it is useless and waste your fertilizer.
Forestry only test the sapling X for fertilization

**Comment by richardhendricks** [comment]
Need to update original quest description, should say yield is higher with orchard apple, and mention faster maturity, with fastest maturity golden raspberry.

Or maybe remove the specific tree info? dunno.

**Comment by leagris** [comment]
The balsa with papaya fruilt pods layout to waste no space is:
```
TLLLLTLLLL…
LLTLLLLTLL…
LLLLTLLLLT…
LTLLLLTLLL…
LLLTLLLLTL…
```
Each L can host a fruit pod attached to trunk T.

**Comment by leagris** [comment]
Also there is a really high limit for forestry orchard multifarm to collect fruits.
You can plant a first set of balsa papaya trees say at y=120, then remove the dirt and plant other trees just below first ones at y=105, then continue down repeating the process.
Connect all trunks so they are continuous without leaf or air block in-between, making really tall balsa trees with fruit pods all sides.
Be sure to add multiple gearboxes to the farm so it can sustain such a large fruits production rate.

**Comment by Prometheus0000** [comment]
The info at the top (or better has already been added). I also don't think we need to tell people min-max setups in the QB. Plus, no pictures make it hard.
