### ISSUE TITLE
OpenBlocks book crash game

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/GT-New-Horizons-Modpack#5332]
#### Which modpack version are you using?
2.0.8.1
#
#### If in multiplayer; On which server does this happen? 
No
#
#### What did you try to do, and what did you expect to happen?
Open the guide book of OpenBlocks
#
#### What happened instead? (Attach screenshots if needed)
Game Crash
[crash-2020-01-12_17.41.09-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4051712/crash-2020-01-12_17.41.09-client.txt)
#
#### What do you suggest instead/what changes do you propose?
Fix it

**Comment by Dream-Master** [comment]
@mitchej123 any idea ?

**Comment by Prometheus0000** [comment]
Is this still happening? It didn't crash for me.

**Comment by Dream-Master** [comment]
i close this now. Feel free to reopen if necessary.
