### ISSUE TITLE
Discuss; new general plasma rework (overhaul)

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/GT-New-Horizons-Modpack#5335]
#### Which modpack version are you using?

# /
#### If in multiplayer; On which server does this happen? 

# /
#### What did you try to do, and what did you expect to happen?
 
# After taking a look into fusion recipes and calculating the potential performence, i was shocked to see that tin plasma,  very easy to run permanently, is by far the best one. 
#### What happened instead? (Attach screenshots if needed)

# /
#### What do you suggest instead/what changes do you propose?
 after comparing all recipes i came to the conclusion that it would be necesarry to create a new system for fusion recipes, since the current design is a joke.

**Comment by Dream-Master** [comment]
@GeicowithaBango can you create a list with new suggested recipes ? Thanks

**Comment by GeicowithaBango** [comment]
its not that simple imo. a little bit more context is needed, more like an norm behind the system.
1.) can recipes have more then 1 output, code-wise?
2.) shall higher tier metals have fusion states (decent cost) etc.
3.) should someone be able to run a t3, for instance, the hole time?
there are a lot of options, but im unsure whats possible to realise.

**Comment by repo-alt** [comment]
GT_RecipeAdder.addFusionReactorRecipe allows only one output, while technically in fusion reactor there are no built-in limit on recipes (or number of output hatches)

**Comment by draknyte1** [comment]
> no built-in limit

You may wanna double check the recipe map, as it could be limited on its outputs. ;)

Fusion as a whole in NH is kinda odd, but tries to follow realism in the fact of what can be fused. (Vanilla GT has far more fusion content, NH removed most stuff > Iron iirc)

**Comment by repo-alt** [comment]
Fusion uses generic recipe map (GT_Recipe_Map) w/o any upper limits

**Comment by 0lafe** [comment]
It would be nice to use inputs that aren't basic tier materials. Put some proc chains into creating isotopes or something, idk. Most fusions are really simple 1-2 stage setups, that make what comes before fusion look complex. Plasma -> power gen also low-key sucks. 

Imo, some fission integration could be fun. We can also use naq or something and run it through a whole bunch of machines before it ends up in the reactor. Also using a better/bigger LHE, combined with a larger steam turbine with better rotor management, we could do plasma->SH steam, and run that through turbines instead. Rn the plasma turbines essentially do both of those, and have singleblock versions, both of which don't really fit late LuV+ power gen. 

With more control over how reactors work, we could bring back Li rod H-3 production for He plasma, giving the intro to fusion power a more interesting proc, and utilizing fission in a slightly more interesting way than normal.
