### ISSUE TITLE
Add ForgePatcher to next release

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5344]
Make sure to pull release version of Forgepatcher from @draknyte1's CircleCI.

**Comment by Dream-Master** [comment]
is this a mod that patch forge ?

**Comment by richardhendricks** [comment]
Yes it will, and other ASM fixes too.

**Comment by Dream-Master** [comment]
https://github.com/alkcorp/ForgePatcher

**Comment by richardhendricks** [comment]
Need to update build gradle to latest forge, and needs more testing before a recommended release

**Comment by richardhendricks** [comment]
@hakameda said they can test the entity fix once it is in ForgePatcher. They run a huge world with a lot of minecart entities.

**Comment by Prometheus0000** [comment]
I don't see it on the mod list so I guess this wasn't added? Unless it's called something else

**Comment by Prometheus0000** [comment]
@mitchej123 Did you ever borrow code from this for the existing forge-patching mods we have? Can this be closed?

**Comment by boubou19** [comment]
https://github.com/alkcorp/ForgePatcher is a 3commits outdated fork from https://github.com/williewillus/BugfixMod. Asie forked it and made foamfix1.7 with it: https://github.com/asiekierka/FoamFix17.

**Comment by Prometheus0000** [comment]
I thought we were using FF (recently), but it's not in the mods folder? Was it just under consideration or something?

**Comment by boubou19** [comment]
FoamFix1.7 is on the officials, works like a charm, so i guess it can now be a part of the pack. (the license is a gnu general public license according to curseforge)

**Comment by mitchej123** [comment]
FoamFix works, we can close this one.
