### ISSUE TITLE
Kill all the things quests, Minoshroom&Hydra not completing (900, 901)

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#5346]
#### Which modpack version are you using?
2.0.8.1
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
killed Minoshroom&Hydra.
#
#### What happened instead? (Attach screenshots if needed)
quest did not complete. The TF achievement however did complete.

These are the only two boss quests in the tab I have tried, so it is likely some of the others have a problem too.

**Comment by richardhendricks** [comment]
naga - works
lich - works
minoshroom

Did you try the Detect button in the quest? I noticed I had to press it to complete the quest, but it definitely gave me credit for killing these three

![2020-01-15_20 17 47](https://user-images.githubusercontent.com/1214811/72487583-21ed0f80-37d4-11ea-90f2-949685c7bb8f.png)
![2020-01-15_20 18 20](https://user-images.githubusercontent.com/1214811/72487594-2d403b00-37d4-11ea-95b6-efd0c1116bf7.png)

**Comment by chochem** [comment]
hmm, not sure if I tried detecting. thanks for testing, Will try again and make sure to detect.

**Comment by chochem** [comment]
just tried hydra again: nothing. detect also does nothing. Can some of the others again tomorrow. Anything else I should try?

**Comment by Bluebine** [comment]
From my experience the quests only work properly if you melee the boss to death. Not sure if that's fixable.

**Comment by chochem** [comment]
will try that. I used a xbow of course.

**Comment by dragagon** [comment]
I xbow'd the hydra on 7.5 and it worked fine. did your achievements reset that you need to melee a bird or squirrel and start the line over?

**Comment by chochem** [comment]
the achievements (and thus TF progression) are fine its just about the quests.

**Comment by richardhendricks** [comment]
Can someone else test on 8.1 with BQ3? It worked fine for me. I did use a sword though.

**Comment by chochem** [comment]
Just to update on this: It really seems to affect all the quests in the tab. As Bluebine says, if you dont melee them, BQ3 does not count it.

So xbows never count and neither does killing the mars boss creeper with his own TNT.

I dont know why there are so few complaints about this. Maybe it actually works for some people? or is everybody using melee?

**Comment by dragagon** [comment]
8.3 did not recognize the mars creeper boss when reflecting it's TNT. that's the only way i know to kill it... i never wanted to get close enough to try to melee.

**Comment by Methes** [comment]
It's a long known issue that xbow does not trigger BQ kill quests, only meele does. It's annoying for sure.
To be honest xbow has more issues as for instance the first TF achievement (killing a raven or any passive mob) does not trigger with xbow either and that's MC achievement not BQ quest so maybe there's issue in how xbow handles kills?

**Comment by Dream-Master** [comment]
we need to report this on better questing github or pm funwayguy he is on GTNH Discord

**Comment by chochem** [comment]
update from discord:

> Funwayguy: So just a heads up but I need to update the 1.7.10 version yet again. Kill tasks don't work with ranged weapons because I used the wrong entity reference last time I backported

**Comment by Dream-Master** [comment]
thanks for info @chochem

**Comment by Prometheus0000** [comment]
Was this fixed since then? It wasn't by mar 22, and I didn't see anything in the commits since then, but they're not always specific.

**Comment by Prometheus0000** [comment]
Seems to work now using a crossbow at range
