### ISSUE TITLE
Arcane Crafting Terminal‘s bug

### ISSUE THREAD

**Issue by hanlie2nd** [GTNewHorizons/GT-New-Horizons-Modpack#5371]
#### Which modpack version are you using?
 2.0.8.3
# 
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
 Open Arcane Crafting Terminal to take out stackable things by pressing shift ,and inventory also have another one(same ID)(such as Ethereal Essence,Drum with different liquid).
#

#### What happened instead? (Attach screenshots if needed)
 It(in AE) will become another one(in inventory).
# 
#### What do you suggest instead/what changes do you propose?
fix the buy.

**Comment by BloCamLimb** [comment]
There's a [GIF](https://i.imgur.com/y1rnoMo.gif) to show that

**Comment by repo-alt** [comment]
Well, I can't reproduce that with essentia phials

**Comment by repo-alt** [comment]
And I have no idea where to get Extra Utilities 1.7.10 dev version to try the drums. What "Ethereal Essence" did you mean?

**Comment by Dream-Master** [comment]
i can check if i have a extra utilities dev version

**Comment by repo-alt** [comment]
Looks like it was fixed
