### ISSUE TITLE
Underwhelming liquid air distillation recipe

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#5383]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I was checking the updated EBF recipes with inert gases and ways to get them
#
#### What happened instead? (Attach screenshots if needed)
~I found that the minor noble gases (neon, krypton, xenon) appear unobtainable through earthly means. There is one recipe available which involves the direct distillation of 100.000 buckets (100.000.000L) of liquid air - the MAX input hatch accepts 968 buckets - a factor 1000 short.~

In addition, I ran the numbers and noticed that helium production through this chain is also off by a factor ~1000 from the double centrifuging cells method, needing 200¼ cells for one helium compared to 190000 to the distillation method. 
#
#### What do you suggest instead/what changes do you propose?
While the latter number appears more world-realistic, the numbers for the cell method is actually a useful production mechanism for helium despite being a tad slow. Therefore I'd suggest dropping the input to 100 buckets worth (that is within an IV-tier hatch range), and readjusting the bulk gases to the appropriate proportions

| Output | Current | Proposed |
|---|---|---|
| ²H | - | 18 |
| Xe | 9 | 3 |
| ¹H | 55 | - |
| Kr | 114 | 38 |
| CH4 | 180 | 60 |
| He | 524 | 175 |
| Ne | 1818 | 606 |
| CO2 | 40 700 | 1000 |
| Ar | 934 000 | 2100 |
| O | 20 946 000 | 19 000 |
| N | 78 084 000 | 77 000 |
| total | 100 000 000 | 100 000 |

Reasoning: 2700 worth of noble gases exist in the original listing. The centrifuge does roughly 2 cells of nobles output per 100 input, so I've normalised that to /3 noble gases +1 bucket CO2 to roughly preserve that trace/bulk ratio, then filled up the remaining 96 buckets with the usual N2/O2 ratios. The centrifuge route also produces deuterium over hydrogen, so I substituted that back as well.

**Comment by Anarack** [comment]
Bart added a extra large output hatch. so it is possible.

**Comment by combusterf** [comment]
Do you happen to have a name, assuming there is an input version as well? I don't see anything relevant when typing "input hatch" in NEI

**Comment by ScriptedPiky** [comment]
It is under 'fluid hatch,' where you will see an odd "ULV" textured hatch under the name of 'Liquid Air Fluid Hatch.'
![2020-01-18_10 39 54](https://user-images.githubusercontent.com/41557212/72668758-ebcfab80-39de-11ea-935e-e7cd7275939f.png)
