### ISSUE TITLE
Maple tree not dropping extractable wood

### ISSUE THREAD

**Issue by MaxsimalPD** [GTNewHorizons/GT-New-Horizons-Modpack#5385]
#### Which modpack version are you using?
2.0.8.1

#
#### If in multiplayer; On which server does this happen? 
In SP

#
#### What did you try to do, and what did you expect to happen?
I bought maple syrup from the coin tab.  I then added maple syrup to a spruce sapling to get a maple sapling.  I planted the sapling and grew it with bone meal.  I then chopped it down using a TiCon mattock.

I expected to be able to put this wood in an extractor this wood to get more maple syrup.

#
#### What happened instead? (Attach screenshots if needed)
The wood I got from the maple tree had item ID 1265:1, which you cannot extract to get more maple wood.  The Maple wood you can extract w/the extractor is item ID 1265.

#
#### What do you suggest instead/what changes do you propose?
Maple trees should drop wood you can extract maple syrup from.

**Comment by richardhendricks** [comment]
Btw like all pams trees you can just use bonemeal on the log to get more.

**Comment by Dream-Master** [comment]
We could add a recipe .

**Comment by NoX-programer** [comment]
Some times I get even \<harvestcraft:pamMaple:3\>. So
`recipes.addShaped(<harvestcraft:pamMaple>, [[<harvestcraft:pamMaple:*>]]);`
does solves the problem (but hit U on \<harvestcraft:pamMaple:1\> is not showing you can re-craft it so we also need to add item description to it).

**Comment by NoX-programer** [comment]
Same problem with cinnamon wood. And it is solved in the same way:
`recipes.addShaped(<harvestcraft:pamCinnamon>, [[<harvestcraft:pamCinnamon:*>]]);`
Also, there is no recipe for cinnamon item? Is it missed?

Is anyone remembers anymore problematic wood in Pam?

**Comment by Prometheus0000** [comment]
Now completely broken, probably as a result of the 'fix', see  #7812.

**Comment by Dream-Master** [comment]
@jss2a98aj any idea ?

**Comment by Prometheus0000** [comment]
Looks like it's assuming every tree is WorldGenPamFruitTree, which messes up the ones that are WorldGenPamFruitLogTree.

**Comment by Prometheus0000** [comment]
jss2a98aj seems to have fixed this
