### ISSUE TITLE
Forestry Quests and LV motors

### ISSUE THREAD

**Issue by Scottishprog** [GTNewHorizons/GT-New-Horizons-Modpack#5386]
#### Which modpack version are you using?
GTNH
#
#### If in multiplayer; On which server does this happen? 
This is an SSP world
#
#### What did you try to do, and what did you expect to happen?
I was trying to complete quests: "The Centrifuge" and "The carpenter" (The current configuration doesn't allow me to see the quests #
#
#### What happened instead? (Attach screenshots if needed)
I attempted to make motors with both steel and iron rods - they did not work.
I attempted to make motors in the assembler with steel rods - the assembler did not recognize the recipe as valid.
The assembler DID work with iron rods.
Only the iron rod recipe motors out of the assembler worked in the quest book.

#
#### What do you suggest instead/what changes do you propose?
Fix NBT for motors in the Forestry and Multi-farms tab.
Check assembler recipe for the steel rod based LV motor

**Comment by Scottishprog** [comment]
Has the same issues with the robot arms as well.

**Comment by Dream-Master** [comment]
nbt issues i guess
