### ISSUE TITLE
Quest #100 "Press all the things" Not accepting the Basic Forming Press as Valid input

### ISSUE THREAD

**Issue by Scottishprog** [GTNewHorizons/GT-New-Horizons-Modpack#5388]
#### Which modpack version are you using?
GTNH
#
#### If in multiplayer; On which server does this happen? 
SSP World
#
#### What did you try to do, and what did you expect to happen?
Made the Basic Forming Press, expecting the quest #100 "Press all the things" to complete
#
#### What happened instead? (Attach screenshots if needed)
Quest did not complete
#
#### What do you suggest instead/what changes do you propose?
I am guessing that this is another NBT issue....

**Comment by Prometheus0000** [comment]
I tried crafting it using motors, pistons, and machine hull I crafted myself and it completed properly. ignoreNBT is already set to true too.
