### ISSUE TITLE
Hungar recovery with Syntskin sometimes differs from the display

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#5390]
#### Which modpack version are you using?
2.0.7.5～2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
My server
#
#### What did you try to do, and what did you expect to happen?
Performed photosynthesis with Syntskin with ThaumicHorizons and recover Hangar
#
#### What happened instead? (Attach screenshots if needed)
Sometimes hunger indicator appears to have improved, but not.
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Dream-Master** [comment]
i never worked much with Thaumic horizons. Can you make a video or/and pics and explain what you did? @yukieiji  thanks

**Comment by yukieiji** [comment]
Syntskin is Self-Infusion added by the ThaumicHorizons.
Its ability gradually recover Hungar by being exposed to the sunshine.

・First Hungar
![2020-01-21_21 37 32](https://user-images.githubusercontent.com/40425798/72805730-e2706880-3c96-11ea-9ab5-37d20980a3c6.png)
・Hungar recovery with Syntskin(The display of HungerOverhaul in the upper right disappears and looks like it has recovered)
![2020-01-21_21 39 53](https://user-images.githubusercontent.com/40425798/72805802-1186da00-3c97-11ea-8ce0-07e2ed63ede4.png)
・But different display of Hungar when taking damage etc.
![2020-01-21_21 40 02](https://user-images.githubusercontent.com/40425798/72805922-56ab0c00-3c97-11ea-8c96-3d0d9e1ac554.png)
