### ISSUE TITLE
NEI crash with bartworks ores

### ISSUE THREAD

**Issue by BloCamLimb** [GTNewHorizons/GT-New-Horizons-Modpack#5392]
#### Which modpack version are you using?
2083
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/14106648/72680654-70155200-3af7-11ea-990a-cced6b430cf6.png)
then crash
[Crash-Report](https://paste.ubuntu.com/p/ppwkQ9b8Qz/)
#

**Comment by BloCamLimb** [comment]
@bartimaeusnek

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by Dream-Master** [comment]
@mitchej123

**Comment by bartimaeusnek** [comment]
@Dream-Master its a problem with GaGreg, will fix soon

**Comment by Dream-Master** [comment]
ok thanks

**Comment by chochem** [comment]
looks like this is fixed in 2.0.8.8 (or before)
