### ISSUE TITLE
Missing names for some of Potassium Disulfate items

### ISSUE THREAD

**Issue by urso90** [GTNewHorizons/GT-New-Horizons-Modpack#5393]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Name of Molten Potassium Disulfate cell and Block have fallowing names:
gt.bwMetaGeneratedCell.59.name 10567:59
bw.werkstoffblocks.01.59.name 3211:59

**Comment by chochem** [comment]
to clarify that a bit:
gt.bwMetaGeneratedCell.59.name 10014:59
and
Molten Potassium Disulfate Cell 10016:59

both exist. You get the first by clicking a cell on a BC tank and the second if you put a cell into a GT tank or fluid canner. Of course, only the second one is accepted by the quest.

**Comment by combusterf** [comment]
I ran into the same problem from a quest perspective on 2.8.0.4/Delta; I would suggest removing the first item variant altogether. Other GT plastics taken from BC tanks yield the hot cell flavour, so that would make it more consistent.

**Comment by Prometheus0000** [comment]
This doesn't appear to happen anymore, instead an empty cell **destroys** the fluid, and a universal cell grabs it correctly.
