### ISSUE TITLE
Walking really fast

### ISSUE THREAD

**Issue by Immortal-Redshirt** [GTNewHorizons/GT-New-Horizons-Modpack#5400]
#### Which modpack version are you using?
2.0.8.3
#

#### What did you try to do, and what did you expect to happen?
I tried walking and expected to walk at the normal speed.
#
#### What happened instead? (Attach screenshots if needed)
I walk at about the same speed as a sprinting player(and yes, if I try to sprint, I go even faster).
#

**Comment by boubou19** [comment]
what items do you wear in the inventory?

**Comment by Immortal-Redshirt** [comment]
> what items do you wear in the inventory?

As I am currently in the early steam age, I likely do not have any technological of magical items that would boost my speed.

**Comment by PoptartOverlord-Xabedo** [comment]
hm, perhaps there's some sort of paranormal entity thats pushing you, check if your pc is haunted.

**Comment by richardhendricks** [comment]
What does your game report for the tps?
/xu_tps
Perhaps your PC is not able to keep up?

**Comment by Immortal-Redshirt** [comment]
> What does your game report for the tps?
> /xu_tps
> Perhaps your PC is not able to keep up?

I'm getting:
9(20), 9(20), and 25(20)

**Comment by Methes** [comment]
Do you by chance have boots with Haste effect on them? Enchanted items drop from infernals so it's very possible you have these even in steam age.

**Comment by Immortal-Redshirt** [comment]
> Do you by chance have boots with Haste effect on them? Enchanted items drop from infernals so it's very possible you have these even in steam age.

All armor has been crafted by me.

**Comment by richardhendricks** [comment]
Are you running on any special surfaces?  GT concrete, TiCon brownstone, Ztones boosters, etc? All of those accelerate walking speed.

Otherwise, no real explanation what's going on.

**Comment by Immortal-Redshirt** [comment]
> Are you running on any special surfaces? GT concrete, TiCon brownstone, Ztones boosters, etc? All of those accelerate walking speed.
> 
> Otherwise, no real explanation what's going on.

It's happening everywhere.
