### ISSUE TITLE
Repairing Hazmat suit does not consume bucket of glue

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [GTNewHorizons/GT-New-Horizons-Modpack#5405]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to repair my Hazmet suit (scuba helmet, rubber boots etc)
#
#### What happened instead? (Attach screenshots if needed)
It worked, I got a repaired suit, and an empty bucket, but it did not consume the Sticky Glue bucket
#
#### What do you suggest instead/what changes do you propose?
In addition to giving an empty bucket it should also consume the Sticky Glue bucket, otherwise I end up with more buckets then I began with.

Also in that same quest ("Repairing your Hazmat Suit") I've been having some trouble with the quest detecting my soft mallet. I have crafted several, but it's not detecting them, leaving me unable to complete the quest

**Comment by Dream-Master** [comment]
maybe the reuse command not worked. Will change it.

**Comment by richardhendricks** [comment]
Need to fix ignore nbt

**Comment by Prometheus0000** [comment]
There's currently no mallet required in the quest, so I quess that part was fixed?
