### ISSUE TITLE
Add this Backported Patch that fixes entities tracking to prevent duping/vanishing Minecarts and other entities. 

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#5406]
**The Actual code fix in 1.12.2:**
https://github.com/MinecraftForge/MinecraftForge/pull/5160

**The Backport:**
https://github.com/Itaros/minecraft-backport5160

**The Compiled Jar:**
https://github.com/Itaros/minecraft-backport5160/releases

This helps fix the tracking of entities and helps if not fully prevents the whole duping and vanishing of entities. The biggest complaint that I have seen that it would fix is Steve Carts, Railcraft Stuff vanishing and or even duping.

It can be server side as well from my understanding so you can throw this onto one the test servers without a Client Patch to test first. 

I tested it for quite a while but it should be tested in a more active live development like people with tech, minecarts, etc. That being said I saw no vanishing or duping of entities that being said it's a rarer bug to begin with but not rare as in you never see it but rare enough you can't easily repeat it.

**Comment by richardhendricks** [comment]
@Hakameda
Have you tested this with RailWorld?

**Comment by KaneHart** [comment]
I don't suggest this patch at this time due to a shuttering issue I found on the client side:
https://github.com/Itaros/minecraft-backport5160/issues/1

**Comment by RupticMC** [comment]
Hello, the backport seems to crash my 1.7.10 Thermos/Uranium server. The log that I get is https://paste.helpch.at/ehekehinof.md

Am I installing this incorrectly? 

I am trying to use this since I switched to Uranium from Thermos, some blocks are disappearing that players have placed down.

**Comment by draknyte1** [comment]
Non-forge environments are not supported. They’re “Use at your own risk”.

**Comment by Itaros** [comment]
Does it happen if installed server-side only?

**Comment by Prometheus0000** [comment]
Can be reopened if someone wants to.
