### ISSUE TITLE
Unable to reach UHV tier

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#5412]
#### Which modpack version are you using?
2.0.8.3
#
#### What happened instead? (Attach screenshots if needed)
UHV SuperConductor is required to make UHV Machine Hull, but UHV assembler is needed to make UHV SuperConductor.
Also, T6 rocket Tier of UV Tier don't have access to materials that make Infinity Catalyst such as Black Plutonium.
#
#### What do you suggest instead/what changes do you propose?
Fix it

**Comment by Anarack** [comment]
Use multiple hatches in the gt++ assembler multi block for now.

**Comment by yukieiji** [comment]
Even if this solves the assembler problem, it is impossible to craft a UHV SuperConductor Base because the Infinity Catalyst isn't available with UV Tier.

**Comment by Dream-Master** [comment]
yes we add a way to make it gt++ independent.

**Comment by 0lafe** [comment]
We could add an assembler multi, remove the ++ one, and force overclocking of the new one 🤔

**Comment by repo-alt** [comment]
(why isn't there a trollface in available reactions)

**Comment by ScriptedPiky** [comment]
I even made a thread that would address this superconductor issue (mainly the infinity catalyst and awakened draconium): https://github.com/GTNewHorizons/NewHorizons/issues/5200

Or, a more simple way of solving it would be change the UHV superconductor wires to either ichorium or bedrockium wires instead. That way, the UHV machine hull is actually craftable.

**Comment by yukieiji** [comment]
I found another problem caused by the inability to make UHV machine hulls.
When smelting a UHV SuperConductor Base, will need an Awakened Draconium coil that can be created with a UHV assembler.
But we can't make a UHV machine hull that makes UHV assembler.....

**Comment by ScriptedPiky** [comment]
Awakened Draconium and Infinity Catalyst are unobtainable by the tier you are in as well. However, it is possible to obtain the UHV hull by using the GT++ Large Scale Auto-Assembler to upvolt from UV to UHV, but of course, the materials are impossible to obtain. Already explained in-depth in #5200 or in my comment above.

**Comment by yukieiji** [comment]
Also, the cost of the UHV circuit remains high because a TCeitE-SeeWeed Extract can't be made and Bioprocessor-based circuit can't be made.

What about the following suggestions?
1. Change the current UHV SuperConductorBase material to UEV SuperConductorBase material and set a new UHV SuperConductorBase material.
2. Rename the current BioProcessingUnit and to use it for UV circuits that can be made in one step.
3. Change the recipe for the BioProcessor series so that it can be created with the materials available on the T7 rocket.
