### ISSUE TITLE
questbook not detecting quest #546

### ISSUE THREAD

**Issue by PoptartOverlord-Xabedo** [GTNewHorizons/GT-New-Horizons-Modpack#5413]
#### If in multiplayer; On which server does this happen? 
epsilon
#### What did you try to do, and what did you expect to happen?
do the quest.
#### What happened instead? (Attach screenshots if needed)

![image](https://user-images.githubusercontent.com/40670872/72911352-93800d00-3d42-11ea-93d7-4c9c112685aa.png)
the pump is clearly in my hotbar, i've spam clicked detect, finished other quests and relogged, is it perhaps from using the pumps i won from a lootbag

**Comment by richardhendricks** [comment]
Missing ignoreNBT on pump requirement

      "tasks:9": {
        "0:10": {
          "partialMatch:1": 1,
          "autoConsume:1": 0,
          "groupDetect:1": 0,
          "ignoreNBT:1": 0,
          "index:3": 0,
          "consume:1": 0,
          "requiredItems:9": {
            "0:10": {
              "id:8": "gregtech:gt.blockmachines",
              "Count:3": 1,
              "Damage:2": 1140,
              "OreDict:8": ""
            }
          },
          "taskID:8": "bq_standard:retrieval"
        },

**Comment by ben0sharples** [comment]
Quest #1090 has the same issue with the Pump if you didn't catch that one yet.

**Comment by chochem** [comment]
just wanted to add: the name remover does not fix this quest, contrary to all the other NBT issues in the quests.

**Comment by draknyte1** [comment]
Because the name remover only removes the name tag and the gt.ingredients tag. It won’t strip all the NBT, because that could break other things.
