### ISSUE TITLE
Exposing machine's internal fluid tank capacity metadata

### ISSUE THREAD

**Issue by fourk** [GTNewHorizons/GT-New-Horizons-Modpack#5415]
#### Which modpack version are you using?
2.0.8.3
#

#### What did you try to do, and what did you expect to happen?
Goal: determine size of internal fluid tanks for machines, specifically Basic Assembly Machine. Tried using Personal Scanner to get this info.
#
#### What happened instead? (Attach screenshots if needed)
Scanning front face of Basic Assembling Machine does not provide any information about fluids. Scanning left or right face of that machine reports 'Tank 0: 0L / 16,000 L' on a machine that currently has 3096L of fluid internally. I'm guessing the scanner may only work for output tanks and not input tanks? This is in contrast to a Basic Centrifuge that just produced some glue, which provides on both the Waila tooltip and by using Personal Scanner on non-front face a 200/64000 Glue message.

#
#### What do you suggest instead/what changes do you propose?

Most preferable would be be to make internal fluid tank sizes part of the tooltip on machines before placing them, at least for machines that don't show tank sizes via Waila (i.e, Assembly Machine, not Centrifuge). Second most preferable would be to make Personal Tricorder scan all of the fluid tanks in a machine, not just the output tank.

**Comment by richardhendricks** [comment]
Should be doable.  Can remove some redundant lines as well.

**Comment by Prometheus0000** [comment]
Can be done if someone cares.

**Comment by Glease** [comment]
Actually, this is somewhat addressed in GTNewHorizons/GT5-Unofficial#468. I'm not sure what tricorder will say, but waila should properly display all fluid contained now.
