### ISSUE TITLE
Division sigil Unstable Ingot crafting isn't working

### ISSUE THREAD

**Issue by MadeofGold** [GTNewHorizons/GT-New-Horizons-Modpack#5416]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Official Delta
#
#### What did you try to do, and what did you expect to happen?
I was trying to craft some unstable ingots in a vanilla crafting table using diamonds , a division sigil (activated) and an iron ingot and it doesnt work. The semi-stable nugget works .
#
#### What happened instead? (Attach screenshots if needed)
It doesn't craft:
![unknown](https://user-images.githubusercontent.com/38396468/72926336-f1215300-3d5c-11ea-8019-ce5a5b34bb11.png)

#

**Comment by richardhendricks** [comment]
@Dream-Master Can you look at this? Don't know what would have changed this

**Comment by Dream-Master** [comment]
it's a vanilla recipe I don't touche it. Will check

**Comment by Rongmario** [comment]
If you leave the recipe in there f or 10 seconds, do you explode? Do try clicking on the output slot in case it's a graphical glitch.

**Comment by Dream-Master** [comment]
No it not give you any ingot or show some

**Comment by MadeofGold** [comment]
While loading i found this in the console log , is it any help in solving the bug?
![gtnh-divsig](https://user-images.githubusercontent.com/38396468/73667453-f8295900-46ac-11ea-9625-8833f79809e1.png)

**Comment by boubou19** [comment]
A valid workaround is to make the pseudo-inversion sigil, then make mobius stable/unstable ingots, then convert them into unstable ingots

**Comment by KaneHart** [comment]
@Dream-Master forgot this one I think.

The plan was to create a new MT recipe for now to override the current one till it could be fixed later on if anyone cares even. It would mean it would not blow up anymore and I doubt anyone would object.

The chance is that when Moron did the performance tweaks to the crafting bench this broke.

**Comment by Dream-Master** [comment]
@KaneHart I don't forget it but mt script not worked here. You can place in got in Tinkers table and it won't explode after 10 secs. It  was to changed code wise. I am not  a coder. Need help here.

**Comment by KaneHart** [comment]
Would this work?
![GwYsaYV](https://user-images.githubusercontent.com/425853/74608052-fd72a480-50ab-11ea-8b7f-bedf2a073a23.png)

It's own file:
https://github.com/Kashdeya/miscscripts/blob/master/Kash/Random%20Scripts/Crafting.zs

Tested it and worked. 

![j4UpXH1](https://user-images.githubusercontent.com/425853/74608072-2135ea80-50ac-11ea-8fa4-87f38f899230.png)

**Comment by Dream-Master** [comment]
yes it works but it break logic @KaneHart

**Comment by Prometheus0000** [comment]
@KaneHart What was the script that worked, your file doesn't have a related recipe?

@Dream-Master What do you mean by 'break logic'?

**Comment by Dream-Master** [comment]
It not worked. If you add a recipe vie minetweaker it wont explode and make the mechanic of instability obsolete.

**Comment by Miruzuki** [comment]
Hi. I managed to fix it with a little minetweaker script:
`recipes.removeShaped(<ExtraUtilities:unstableingot>.withTag({Bug: 1 as byte}),[
    [<minecraft:iron_ingot>],
    [<ExtraUtilities:divisionSigil>.withTag({damage: 256})],
    [<minecraft:diamond>]
]);

recipes.addShaped(<ExtraUtilities:unstableingot>,[
    [<minecraft:iron_ingot>],
    [<ExtraUtilities:divisionSigil>.withTag({damage: 256})],
    [<minecraft:diamond>]
]);`

Instability mechanic is kept (it will explode after 10 sec).
![image](https://user-images.githubusercontent.com/57010903/161882253-7bc8213b-e114-4d19-a67b-99dde1704c98.png)

**Comment by Dream-Master** [comment]
ok will add this to Extra Utilities script

**Comment by Miruzuki** [comment]
> ok will add this to Extra Utilities script

Update: instability only working if you craft this ingon one at a time. In case of bulk crafting (e.g. 10 ingots) it won't explode.
Sorry for the inaccurate information.
