### ISSUE TITLE
Transformer not change visually when mode changes to step up

### ISSUE THREAD

**Issue by Usernm0** [GTNewHorizons/GT-New-Horizons-Modpack#5420]
#### Which modpack version are you using?
GTNH 2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Any
#
#### What did you try to do, and what did you expect to happen?
I Whack my transformer with soft mallet.
#
#### What happened instead? (Attach screenshots if needed)

It should have dots like on left blocks, but it not changed visually.
![](https://i.imgur.com/OExni7r.png)

#
#### What do you suggest instead/what changes do you propose?
Make it works like it works long ago.

**Comment by richardhendricks** [comment]
Which transformer is that? and did it work before?

**Comment by Usernm0** [comment]
Any transformers not work now. Power IV transformer on screen. I just take one, which looks better on screenshot. 

And this mechanics works long ago on gt 5.0.9 unofficial. I don't know when exactly it broken.

**Comment by Dream-Master** [comment]
can confirm no visual change. How it looks like before ? @Usernm0 @richardhendricks

**Comment by Usernm0** [comment]
I put blocks with right colored dots on the left part of the screenshot.

**Comment by Dream-Master** [comment]
@Usernm0 did it work in 2.0.7.5 ?

**Comment by Usernm0** [comment]
Yes.
![](https://i.imgur.com/N9SmHw2.png)
