### ISSUE TITLE
IC2 crop missing from spreadsheet

### ISSUE THREAD

**Issue by MaxsimalPD** [GTNewHorizons/GT-New-Horizons-Modpack#5421]
#### Which modpack version are you using?

2.0.8.3

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I found a garnydia seedback and went to the very useful gtnh spreadsheet to see what it was.  Didn't find it there.  Seems some of the newly added crops are not exported there?

#
#### What do you suggest instead/what changes do you propose?

Updating the spreadsheet.  Bluebine told me I should file a ticket since that's a thing that should be done :P

**Comment by richardhendricks** [comment]
@bartimaeusnek Any other crops that need adding to the wiki?

**Comment by Prometheus0000** [comment]
They're talking about the spreadsheet, not the wiki, yeah? I already updated the wiki some time ago, and the Garnydinia is on it.
