### ISSUE TITLE
Update Better Questing readme file for new BQ3 process

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5430]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by Dream-Master** [comment]
@richardhendricks  where? Wiki page? in the Quest file? Github?

**Comment by Prometheus0000** [comment]
Under \.minecraft\config\betterquesting in any instance of GTNH right?

**Comment by Prometheus0000** [comment]
I think he already did this?
