### ISSUE TITLE
Make all recipemap-bloating recipes use the chisel instead

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5432]
Instead of 9,999 scripts and 1+ minute to do the various log types etc, turn them all into Chisel groups and just delete the normal recipes. Make the default "oak" one use any log/plank type, then players can chisel to whatever damn color they want.

All the drawer sizes and types.
All bibliocraft item types.

**Comment by Dream-Master** [comment]
how ? @richardhendricks

**Comment by Prometheus0000** [comment]
See #5537
