### ISSUE TITLE
Quest complete detection

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#5445]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Some quests do not finish, although all the stages are detected as complete
E.g.:
![image](https://user-images.githubusercontent.com/23512002/73144090-b39d2c80-40b2-11ea-9a9e-778fe172b71b.png)
![image](https://user-images.githubusercontent.com/23512002/73144095-c4e63900-40b2-11ea-83af-0cc720252b22.png)

**Comment by Dream-Master** [comment]
@repo-alt can you make a list with quests (name and/or id) make it easier to fix. Thanks.

**Comment by repo-alt** [comment]
The problem is that I can only detect these issues as I play, which is not very fast (warning: _understatement_). Also I'm not sure this issue is NBT related unlike others, because BQ3 does detect all the items in the quest stages here, but the whole quest is not marked as complete for some reason.

**Comment by Prometheus0000** [comment]
I've had this happen too, it might be caused by going into and out of edit mode. It sometimes decides it's complete after changing dims, and has always worked after logging out and back in.
