### ISSUE TITLE
Better Quests, multiblock assembling line 4/4 not completing

### ISSUE THREAD

**Issue by Parsalin** [GTNewHorizons/GT-New-Horizons-Modpack#5451]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
prospercraft.com
#
#### What did you try to do, and what did you expect to happen?
complete the assembling line multiblock quest 4/4
#
#### What happened instead? (Attach screenshots if needed)
it didnt complete even tho i held one i had then crafted a second just in case.
#
#### What do you suggest instead/what changes do you propose?
make sure its detecting the right block and tell me what blcok it is looking for so i can complete it.

I attempted: 
Craft a new one,
Detect button many times, 
Relogging, 
Wait for server reset to try again.

![2020-01-27_05 49 11](https://user-images.githubusercontent.com/4047592/73216558-0efb0900-410b-11ea-8668-db0199d44030.png)
![2020-01-27_05 49 38](https://user-images.githubusercontent.com/4047592/73216560-0efb0900-410b-11ea-91b9-97985b29dd1b.png)

**Comment by richardhendricks** [comment]
try using a Name Remover machine, should let you finish the quest.
