### ISSUE TITLE
Everfull Urn violently breaks Gregtech tools and metaitems

### ISSUE THREAD

**Issue by Ethelana** [GTNewHorizons/GT-New-Horizons-Modpack#5453]
#### Which modpack version are you using?
2.0.8.3

If in multiplayer; On which server does this happen? 
N/A

What did you try to do, and what did you expect to happen?
Tried to break an everfull urn with a gregtech tool, I just thought it would break

What happened instead? (Attach screenshots if needed)
Turns gregtech tools into NULL broadswords and testing showed that it turns all other metaitems from gregtech into gt.metaitem.01.0.name. 

What do you suggest instead/what changes do you propose?
make it so it actually breaks the urn instead of breaking the tool on a cosmic scale.

(I was told to make a new one, i know its been reported twice, don't get angry)

**Comment by boubou19** [comment]
maybe related with #1442

**Comment by richardhendricks** [comment]
Seems like we can add some detection on the GT side to not interact with these items.

**Comment by GTNH-Afx237v7** [comment]
Just tested this with 2.1.0.0, did not encounter any issues.
Using a GT Pickaxe properly mines the everfull urn. 
Trying to break it with a GT wrench/soft mallet/electric wrench,screwdriver does nothing
Trying to break it with a GT item (here: electric pump cover) breaks the urn, leaving nothing
Trying to break it with a GT dust breaks the urn, leaving nothing. 
Suggest to close this issue.
