### ISSUE TITLE
Speed effect problem/bug

### ISSUE THREAD

**Issue by deNaDE** [GTNewHorizons/GT-New-Horizons-Modpack#5458]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
drinking a speed potion, expecting it to increase my movement speed
#
#### What happened instead? (Attach screenshots if needed)
it only showed the tab that i am under the speed effect, yet it didnt speed me up at all
#
#### What do you suggest instead/what changes do you propose?
i dont think i know how the potion stuff work, sorry

**Comment by PoptartOverlord-Xabedo** [comment]
i drank a speed potion and tested it, it didnt work, i have no clue

**Comment by deNaDE** [comment]
PS: it doesnt do that only for potions. vampires dont get any speed either

**Comment by Mr-Jeany** [comment]
2.3.4 - Still wasn't fixed.

I really want to have it fixed, because speed is almost the best benefit of vampires. It worked for me a bit earlier (may be before 2.3.3???) but now - it doesn't.
