### ISSUE TITLE
Fun stuff to do with Special Mobs

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5459]
- [ ] Add effect from garlic so that player can make vampire pigmen run away, or not attack players at least.
- [ ] Add Witchery vampirism notes to vampire pigman drops.
- [ ] More preferred damage sources
- [ ] More unpreferred damage sources for mobs
- [ ] Setup some kind of config file for damage sources
- [ ] Standardize on method to do that

**Comment by Prometheus0000** [comment]
Can be reopened if anyone has the time for this.
