### ISSUE TITLE
difference mining osmiridium casing

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/GT-New-Horizons-Modpack#5460]
#### Which modpack version are you using?
2083
#

#### What happened instead? (Attach screenshots if needed)
![image](https://i.imgur.com/TKGGA5q.png) osmiridium plate on shaped
![image](https://i.imgur.com/s9OnPnZ.png) ruridit in assm

**Comment by Dream-Master** [comment]
funny. Need a change

**Comment by Prometheus0000** [comment]
Duplicate of #5126
