### ISSUE TITLE
Expensive Avaritia

### ISSUE THREAD

**Issue by SKYCATV587** [GTNewHorizons/GT-New-Horizons-Modpack#5465]
Is Avaritia things too cheap for now? Can you make it more expensive?

**Comment by Dream-Master** [comment]
@SKYCATV587 what you mean. Give me examples ?

**Comment by SKYCATV587** [comment]
Such as add WitchingGadgets‘s Primordial Helm ，Blood magic's four Omega Helmet into Infinity Helmet's craft like this

**Comment by GTNH-Colen** [comment]
Omega armour can't actually be removed from the player without it converting back to bound armour. Thus using it in this recipe would be near impossible unless we added an alternative recipe for it, not sure if that would handle well though. In any case we already use the Sanguine helmet and Life imbued helmet so it's not like blood magic hasn't been taken into account.

Infinity armour is fine where it currently is, really don't see the need to be screwing with its recipes?
