### ISSUE TITLE
Ore Drilling Plant cant process gt++ ores

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#5468]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by repo-alt** [comment]
Please report it here: https://github.com/AlkCorp/gtplusplus/issues
Our miner is no different from vanilla GT5 in that respect

**Comment by Pnc6lx** [comment]
in 2080pre4, it also cant mine Djurleite, but when i update to 2083, it works. maybe this is the same?

**Comment by Pnc6lx** [comment]
addition,  single block miner can mine those gt++ ores well,  only multiblock ore miner have this problem

**Comment by repo-alt** [comment]
How exactly it does not mine the ores - does it leave empty spaces or just ignores the ores?

**Comment by Pnc6lx** [comment]
> How exactly it does not mine the ores - does it leave empty spaces or just ignores the ores?

ignore the gt++ ores

**Comment by repo-alt** [comment]
No idea then, need to be debugged with GT++, and Alk makes that intentionally difficult, perhaps @botn365 may help.

**Comment by draknyte1** [comment]
Not my job to fix core GT problems from GT++ 95% of the time.

**Comment by repo-alt** [comment]
Any reason it is core GT problem?

**Comment by draknyte1** [comment]
Ore drilling rig isn’t mine, so not my problem if it doesn’t work as intended. 

Simple. What do you want me to do beyond ASM the ODR? 🤷🏻‍♀️

**Comment by richardhendricks** [comment]
GT++ ores don't subclass GT ores?

**Comment by draknyte1** [comment]
Why would they?

**Comment by richardhendricks** [comment]
And isn't it technically yours now that you own GT5U? :P

**Comment by repo-alt** [comment]
It looks like you made the ores that don't work with the rig.

**Comment by draknyte1** [comment]
Considering I’m working 60hr a week & Bloods busy, that handover may take months. Neither of us are in any rush to deal with that right now. 

Fix it here, merge upstream. Same thing we’ve done the past year...

**Comment by richardhendricks** [comment]
Will do
