### ISSUE TITLE
Unable to add a player to /mytown

### ISSUE THREAD

**Issue by lmao420blazeit** [GTNewHorizons/GT-New-Horizons-Modpack#5469]
#### Which modpack version are you using?
GT New Horizons-2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta Server
#
#### What did you try to do, and what did you expect to happen?
I created a town and tried to add 2 friends. 1 of them accepted the invitation without problems. The other wouldnt get the invitation even though it said the invitation was sent.

#### What do you suggest instead/what changes do you propose?
I just want to be able to add my friend to my town so he can be able to access my stuff.

**Comment by boubou19** [comment]
to join a town you must be at least nomad. Sometimes the server doesn't show that the invitation was sent, but either typing "/town accept" or disconnecting/reconnecting then try it again can solve the issue. If none of that works, wait for a restart of the server then try it again.

**Comment by PoptartOverlord-Xabedo** [comment]
watch out though, its case sensitive too

**Comment by richardhendricks** [comment]
@lmao420blazeit Did your friend meet the requirements?  You can use /pay to give them some server credits to rankup.
