### ISSUE TITLE
Crash with 512V Creative Energy Buffer

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5470]
#### Which modpack version are you using?
2.0.8.3
#
#### What did you try to do, and what did you expect to happen?
Change the output of the Buffer with a screwdriver, to cycle back to ULV from MAX.
#
#### What happened instead? (Attach screenshots if needed)
It crashed.
#
#### What do you suggest instead/what changes do you propose?
Fix the crash. Do you need a log? It seems easy to reproduce so I'm not sure you needed one.

**Comment by mitchej123** [comment]
Please provide a log with a stacktrace.

**Comment by Prometheus0000** [comment]
Is that included in the normal crashlog from MultiMC?
I noticed you can go past UHV with the buffer now, so it's probably related to that?
[crash-2020-01-29_10.21.08-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/4129159/crash-2020-01-29_10.21.08-server.txt)

**Comment by mitchej123** [comment]
Looks like a gt++ issue, please report there.
