### ISSUE TITLE
Miners (single and multi) do not pick up Aluminum ore (TC) in Bedrock dim

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5477]
#### Which modpack version are you using?
2.0.8.3
#
#### What did you try to do, and what did you expect to happen?
Use a miner in the bedrock dim, collect all ores.
#
#### What happened instead? (Attach screenshots if needed)
Does not collect all ores, Aluminum ore (TC) is not collected.

There might be other ores it misses, but I'm not going to look for them if there's no easy way to do so.
#
#### What do you suggest instead/what changes do you propose?
Fix it?

**Comment by Dream-Master** [comment]
Why there ores from Tico ?  This is a mistake. Normaly only GT ores in this dim

**Comment by Prometheus0000** [comment]
Please look at the links in #5476, it also has ic2 ore, and probably gc and thaum as well. I didn't really look around much though.

**Comment by Dream-Master** [comment]
ok will check

**Comment by repo-alt** [comment]
Bedrock dim is kinda natural reserve for non-GT ore generation. Theoretically miner (both variants) should work with every block oredicted  as "ore*". Perhaps they do not get oredictionary unification because they are "kind of" disabled.

**Comment by Prometheus0000** [comment]
I checked before, and the ore had the oreAluminum tag on it, but I wouldn't think it would get avoided because of a spelling difference for example.

**Comment by repo-alt** [comment]
I think TiCo aluminium ore is not unified intentionally, so that it would be separate from GT aluminium  ore, allowing smelting it in the smeltery and at the same time being not usable as GT aluminum.

**Comment by Prometheus0000** [comment]
Is there a point to that? By the time you get there, I would think you have tons of it. And the Aluminium ore for GT spawns in other much earlier dims, so maybe take off the oreAluminum tag and add the oreAluminium one? But would that really affect the Miner?

**Comment by repo-alt** [comment]
Not sure if unificating TiCo would not break Aluminium gravel processing. Anyway, this issue does not seem to be of any importance, because when you have access to bedrock dim you are probably already up to voiding aluminium to not overflow AE

**Comment by Prometheus0000** [comment]
Well true, but I didn't go very far to check for other ores that might have a similar problem, and I couldn't get the /fill command to work to delete the bedrock to look either. I'll leave it up to the staff to decide if it's worth it or not.

**Comment by Dream-Master** [comment]
nah maybe I am wrong. Bedrock dim have no gt ores only the other mods ores. Mixing that with Deep Dark

**Comment by Prometheus0000** [comment]
Looks like the miner fix recently fixed this.
