### ISSUE TITLE
Text addition suggestion to Chemical Plant quest

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5483]
#### Which modpack version are you using?
2.0.8.3
#
There's no indication of what the Chemical Plant Tier does in the tooltip for the CP controller, so it should probably be mentioned in the quest.  Specifically, you can't craft an item if the CP tier is insufficient for the recipe. Currently the highest one is 3, making T4 pointless, but I'm sure the number of items/recipes is being worked on. You can see the required tier on the NEI recipe page (you can check nitrobenzene for example).
#
#### What do you suggest instead/what changes do you propose?
"Recipes can only be made after meeting the required Chemical Plant tier" something like that added to 'Playing with the big Boys, chemically' on the HV tab.

**Comment by richardhendricks** [comment]
It's still very much in flux. I was going to wait for it to settle down before doing a full quest chain for it.

**Comment by Prometheus0000** [comment]
I agree with that, but this is definitely something easy to miss, since it's not GT standard, and wouldn't require a new quest or something. Though currently all the recipes do seem kinda pointless right now after all.

**Comment by richardhendricks** [comment]
I guess we can add a minor comment to the current quest while we wait

**Comment by richardhendricks** [comment]
note: Change to 2.0.10 after adding note above

**Comment by Dream-Master** [comment]
@Prometheus0000 this is fixed right ?

**Comment by Prometheus0000** [comment]
I did add the appropriate text in my PR. I don't think you added of the appropriate tag (fixedindev) to any of the issues linked to my PR though. @richardhendricks seems to want to use this issue to remind him to make a chemical plant quest chain later or something though.
