### ISSUE TITLE
Killer Joe requires 75% nutrient distillation to work

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5498]
https://www.reddit.com/r/feedthebeast/comments/39ig8y/killer_joe_stopped_working/

**Comment by Dream-Master** [comment]
we have the source so we can change it.

**Comment by richardhendricks** [comment]
I know, just wanted to mark it so we can either fix or mention in the quest.

**Comment by Dream-Master** [comment]
@zoko061602 you the ender io guy now

**Comment by Prometheus0000** [comment]
Added note to quest, but it's still not fixed.
