### ISSUE TITLE
The sleeping issue

### ISSUE THREAD

**Issue by Waisse** [GTNewHorizons/GT-New-Horizons-Modpack#5500]
An issue that only apply to the official GTNH server

Can something be done to make skipping night easier ? Right now it is set to 25% of players sleeping to skip, but I don't think it's taking into account if someone is afk or not in the otherworld. Sometimes I feel like I'm the only one playing even tho the server has ~10 players online. Literally no one chat for hours and the only message I see is players AFK.

I know there's a command to skip night but doing so instead of sleeping can trigger rain and that's something I don't want because bees.

**Comment by leagris** [comment]
> something I don't want because bees

Breed the Tolerant Flyer trait for bees that also work with rain.

**Comment by GTNH-Colen** [comment]
It definitely takes into account which dimension people are in, if I leave the OW it can sometimes tip the balance and make it day. However it doesn't take into account AFK people not voting, maybe this should change? I honestly think a lot of players just like to keep to themselves and can't be bothered to sleep/vote.

**Comment by DietmarKracht** [comment]
maybe add a vote for rain/no rain?

**Comment by boubou19** [comment]
we do have a vote to skip day/night, and i just implemented a vote to toggle the rain.
