### ISSUE TITLE
[Crash] Twilight Forest - When loading some chunks rare with Chunk-Pregenerator World.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#5504]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Local Lan Dedicated Test Instance
#
#### What did you try to do, and what did you expect to happen?
So I Chunk-Pregenerator Twilight and the reason I used Twilight vs Admin Toolbox is because Chunk-Pregenerator prevents crashes and it just skips the chunks. Not sure if these are related error wise but it's how I created a 32k x 32k world... That being said it's still laggy as hell when I fly through it I'm guessing all the lighting is broken...

#
#### What happened instead? (Attach screenshots if needed)
So when I fly around the world very rare I get the following crash:
https://pastebin.com/egeTcWZ4
It's a full out crash nothing else I can do about it. It seems that it's not been the first time it's happen with a mod that does special world generation I guess it's also happen to GT6 and Chunk-Pregenerator and sadly Greg and @Speiger I don't think have ever solved it I could be wrong...

#
#### What do you suggest instead/what changes do you propose?
Some way to prevent the crash. As I see it Speiger mod can do that or interrupt it I think it's called. Not sure if it's something we can do maybe that is too stupid...

My honest Wish is to Generate a full 32k x 32k Twilight World without having such a performance hit.. Even using Speiger Mod I can't seem to fix the performance once a Player runs through it.. The 2nd time it's way way better.. So clearly the world not fully generating correctly.. Even though I did a mapping of it and the tree's etc were showing up... My only guess is that the lighting itself not being handled till the player runs through.

@jss2a98aj With you now working on TF might be some ideas as well but I thought I cry haha. Even if I can find a better method of generating the world.

**Comment by Speiger** [comment]
Oh thats because of mcs dungeon spawner logic, that could be fixed if @Chocohead would finally patch this issue that is left in CarefulCastCorrector (i am trying to get him to fix this issue since months)
(its an asm patch)

**Comment by KaneHart** [comment]
Will be generating a new world in the next couple of days 8k out and will report back if anything changed. Speiger done massive changes and even GTNH and such has had many changes that might help solved this issue.

**Comment by Speiger** [comment]
@KaneHart i got another dev to fix the chocohead patcher to include that specific case too so that should be fixed
