### ISSUE TITLE
Twilight Forest Magic Map Performance Issues in Overworld.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#5505]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Multiplayer Lan Dedicated
#
#### What did you try to do, and what did you expect to happen?
When using the Magic Map on the Overworld it should either not work or at least not cause performance issues.
#
#### What happened instead? (Attach screenshots if needed)
It causes performance issues and server hangs. Please Refer to #2171 for more info.
#
#### What do you suggest instead/what changes do you propose?
I suggest that the mighty @jss2a98aj take a look and see if it's something that can be fixed

**Comment by jss2a98aj** [comment]
I took a look and making blank magic and maze maps only work while in the Twilight Forest was easy.

**Comment by KaneHart** [comment]
Awesome thanks :)

**Comment by KaneHart** [comment]
> I took a look and making blank magic and maze maps only work while in the Twilight Forest was easy.

Wondering what happen to this. Kind of old but wondering if there was a fix or a per world option ever added?

**Comment by Dream-Master** [comment]
maybe we need to add this map to the itemlist you can use ouside tf
