### ISSUE TITLE
ConcurrentModificationExceptions in server log (no crashes)

### ISSUE THREAD

**Issue by ken-long** [GTNewHorizons/GT-New-Horizons-Modpack#5506]
#### Which modpack version are you using?
2.0.8.3 
(very slightly modified for personal use --
special mobs disabled
infernal mobs disabled
GT++ updated to build 478)

#
#### If in multiplayer; On which server does this happen? 
locally hosted server for single-player (all running from SSD, 16GB system RAM, -Xms2G -Xmx6G in startserver.bat, 6GB selected in technic launcher)

#
#### What did you try to do, and what did you expect to happen?
Occasionally see ConcurrentModificationExceptions in the server log, seemingly for no reason and seemingly causing no problems

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/6040204/73678069-8b4e9880-4685-11ea-9080-dec6f8513b47.png)

My world is very young and not much is going on in it at all.  I do have several railcraft admin anchors placed.

#
#### What do you suggest instead/what changes do you propose?
I have no idea if this is a significant issue or not.

**Comment by boubou19** [comment]
i'm gonna close this as it's an old modpack version. Feel free to reopen it if it still happens on the 2.1.0.0 version.
