### ISSUE TITLE
[Suggestion] Add more EnderIO Grinding Balls

### ISSUE THREAD

**Issue by Zokonius** [GTNewHorizons/GT-New-Horizons-Modpack#5510]
#### Which modpack version are you using?
2.0.8.3
#
#### What do you suggest instead/what changes do you propose?
Add EnderIO GrindingBalls from newer versions.

**Comment by Dream-Master** [comment]
@Zoko061602 if you can code it feel free to add it.

**Comment by Zoko061602** [comment]
GTNewHorizons/EnderIO/pull/6

**Comment by Zoko061602** [comment]
[Ender-IO.txt](https://github.com/GTNewHorizons/NewHorizons/files/4150709/Ender-IO.txt)

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/95656517-ebcb8a80-0adc-11eb-8c11-d267891bd68b.png)
