### ISSUE TITLE
Conflicting recipes for leather and gold dust

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#5517]
#### Which modpack version are you using?
2.0.8.3
#

gold dust and leather have the same xp bucket recipe. It produces gold dust in practice. plz fix, I want leather.

**Comment by leagris** [comment]
Turn your monitor upside-down to produce leather :stuck_out_tongue_winking_eye:

**Comment by chochem** [comment]
no idea what you mean with the upside-down. The current recipe is not what you have drawn here (that one is gallium), but
╔═══╤═══╤═══╗
║   B   │   B  │   B   ║
╟───┼───┼───╢
║   B   │   B  │   B   ║
╟───┼───┼───╢
║   B   │       │   B   ║
╚═══╧═══╧═══╝
same as gold dust.

**Comment by leagris** [comment]
I was just joking about gold and leather recipes having the same shape and orientation.. See the PR patch if you want to know what alternate non-conflicting recipe replacement is proposed.

**Comment by Dream-Master** [comment]
I close this after release
