### ISSUE TITLE
Add a ice modifier to tinkers construct for blaze killing specifically 

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#5519]
Have it added via ice in the tool station

![image](https://user-images.githubusercontent.com/20565115/73852750-595c4400-47f5-11ea-861a-b154022074c8.png)
![image](https://user-images.githubusercontent.com/20565115/73852777-6416d900-47f5-11ea-8e2f-28bcf38c8257.png)

**Comment by richardhendricks** [comment]
Also look into adding a M&B icy arrow type

**Comment by Prometheus0000** [comment]
Sounds _cool_. Reopen if someone want to do it.
