### ISSUE TITLE
Suggestion: Add a recipe for making nitric acid with saltpeter

### ISSUE THREAD

**Issue by shitstainlord** [GTNewHorizons/GT-New-Horizons-Modpack#5521]
Saltpeter, as it currently stands, is trash and only useful in making ruthenium but you end up getting thousands of it in every mining operation. With a simple chemical reactor recipe it can be quite useful all the way from early to late game:

KNO3 + H2SO4 → KHSO4 + HNO3
Saltpeter + Sulfuric acid = Potassium bisulfate + Nitric acid

Potassium bisulfate can be electrolyzed to get elements back or if you want to go a step further:

2 KHSO4 → K2S2O7 + H2O is the thermal decomposition process of potassium bisulfate that forms potassium pyrosulfate. It can be done in EBF since we have those type of recipes in platinum chain.

And to tie it all together heating up potassium pyrosulfate once again forms potassium sulfate and sulfur trioxide:

K2S2O7 → K2SO4 + SO3

Sulfur trioxide can be used to make sulfuric acid (a recipe that already exists) and potassium sulfate can either be used to make fertilizer or just electrolyzed into its basic elements.

**Comment by NG-ChE** [comment]
An alternative reaction that requires no need for adding an additional compound into GTNH:

2KNO3 + 2HCl + H2O → 2KCl + HNO3 + NO2 + H2O

KCl is rock salt.

**Comment by quedral** [comment]
Thats a good use of Saltpeter imo

**Comment by richardhendricks** [comment]
If we add these, I think they need to be either MV or HV recipes.

**Comment by shitstainlord** [comment]
Since making ammonia requires HV chemical reactor, I think it would be fair for this recipe to require the same

**Comment by botn365** [comment]
for the second recipy the amount of rock salt you get and hydrochloric acid should be changed so you cant dupe the potasium or consume chlorine if it needs chlorine it will never be used becous chlorine is already used for evrything

**Comment by richardhendricks** [comment]
It's 2:2, I don't see a dupe issue there?

**Comment by botn365** [comment]
there is the 1 potassium -> 3 potassium hydroxide 
3 potasisium hydroxide + 5 nitric acid = 5 saltpeter

**Comment by shitstainlord** [comment]
Yeah that recipe is bonkers, it should be:

potassium + 1000mb water → Potassium hydroxide + 1000mb hydrogen

**Comment by botn365** [comment]
that recipe is fine as it needs lots of nitric acid its just that the saltpeter to nitric acid recipe should be balanced around this recipe

**Comment by repo-alt** [comment]
Isn't balancing around broken recipe a bit weird?

**Comment by Prometheus0000** [comment]
Does anyone care about this any more?

**Comment by Rakdarian** [comment]
I like the idea, but the specifics are beyond me

**Comment by Dream-Master** [comment]
i could add such recipe change. Not sure if i can do it today maybe till next week
