### ISSUE TITLE
Entity issues causing TPS problems

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#5522]
Vanilla rules are that mobs that spawn holding something can despawn, but they cannot despawn if they pick up an item.  Make sure Special Mobs giving pain swords isn't causing this trigger to happen, ie Brutish.

Maybe allow despawning if the item picked up is a common drop, like rotten meat/bones/etc. Or block picking up those items

Also check infernal mobs, especially ultras - maybe something there is preventing despawning?

Another thing to check - make sure SMs are only doing pathfinding if they are in and next to fully loaded chunks - see https://github.com/GTNewHorizons/NewHorizons/issues/5532

Check roguelike spawners - are they properly limited? Seems like they might be spawning entities even though they shouldn't be due to limits on how many are nearby. Pretty sure they ignore player distance when spawning in mobs - perhaps they shouldn't

Check on AMDI or whatever mod it is that limits the number of entities in a single block - maybe that is causing drops that then can be picked up? Give it a special DamageType so that we can track it. Also, when killed by overpopulation, do not donthe dumb explosions. When killed by overpop, do not drop any new drops. Find out how minecraft marks mobs with carried items

Look at adding some commands to display locations of all entities/certain entities/certain dimensions, and display all currently active chunk tickets, and originating spot.

Next release SM will replace all vanilla mobs with "SM" vanilla types. This will let us control their behavior. Need to confirm this does not block TC furious zombies since players will still need their brains.

Look at adding "SM" style breeding animals to prevent players from jamming a huge number in one spot. Only allow breeding if number of animals within 5 blocks is less than 10. Check on if it is collisions or just existing that is lagging out. Do pathing checks so that pathing doesnt occur if player is too far or there are not 3x3 loaded chunks.

Soul brazier in Thaumic Explorations is acting as a permanent world anchor chunkloader.  This violates server policy since it cannot be controlled by server owners.  Add an option to disable the chunkloader ability and require a server-approved chunkloader.

**Comment by richardhendricks** [comment]
https://gaming.stackexchange.com/questions/125577/what-are-all-possible-ways-to-stop-a-zombie-from-despawning

**Comment by richardhendricks** [comment]
Setup the despawn timer in special mobs to force delete mobs that have lived too long?

That might not be great for smeltery ender pearl farms.

**Comment by repo-alt** [comment]
It would be seriously inconvenient if the mob might despawn holding your weapon

**Comment by richardhendricks** [comment]
Yes I agree we need to be super careful on which we despawn. We can have a list of items that do not stop despawning, items like bones/rotten meat/etc should not force a despawn.

I wonder if our entity limits is causing areas with high densities to kill entities, and then they pick up trash items off the ground.

**Comment by repo-alt** [comment]
I believe that is exactly what happens

**Comment by richardhendricks** [comment]
@MrWye noticed problems in Epsilon with unknown entites spawning in the void in the End, something to do with a shaft dug all the way down.

**Comment by richardhendricks** [comment]
@ScriptedPiky Hmm I don't have op privs on Zetatest, I'll have to ask to be added.  Can you provide an XZ location for that cave? Is it a dungeon spawner or roguelike?  I suspect roguelikes don't properly limit their spawn numbers, I recall seeing a room jammed with Endermen in a roguelike once.

**Comment by repo-alt** [comment]
"Unknown entities in the void" now that sounds scary

**Comment by richardhendricks** [comment]
MrWye found this as the source of lag on Eta

https://prnt.sc/r1cul3

https://prnt.sc/r1cuy5

**Comment by richardhendricks** [comment]
Gregtech, of all things, limits the number of entities in a block. Our current default is 6.
`
                            if (tEntityCount > this.mMaxEqualEntitiesAtOneSpot) {
                                tEntity.attackEntityFrom(DamageSource.inWall, tEntityCount - this.mMaxEqualEntitiesAtOneSpot);
                            }
`

**Comment by richardhendricks** [comment]
OK, looks like EntityLivingBase doesn't really care what caused the death, you get drops no matter what. If an entity has been hit recently by the player, that does give you the rare drops, but that's it.

Instead of damaging the entity when there are too many, perhaps we should just outright delete them.

**Comment by BlackAce21** [comment]
@richardhendricks there is a config option in the spigot.yml file as well labeled "max-entity-collisions" if its not already, this should be set to 1 as the default is 8 and its per tick. Can be helpful for situations like the one in that screenshot, although it doesn't negate the problem completely.

**Comment by richardhendricks** [comment]
Thanks, I pointed Mr Wye and Rizzok at your suggestion!

**Comment by ScriptedPiky** [comment]
To further discuss on this matter as of version 2.0.8.0. I may of figured some further evidence and assumptions towards this massive problem. All of the hostile mobs shown in these pictures are **Infernal** mobs holding an item. For some reason, Infernal Mobs, regardless if placed with the Regen prefix, will continue to stay alive for a majority of the time. It is likely that they spawn and potentially ignore being killed or deleted by the server, and as a result, will continue to live until they eventually fill the mob cap. I killed 60+ entities and am now down to a solid 90 entities around my base (at least for one area cleared of mobs). Quite literally there are hundreds of mobs around my base in caves that do not despawn, are infernals, and fill the mob cap & lag the server.
![2020-04-03_17 25 30](https://user-images.githubusercontent.com/41557212/78420384-8c5b6200-7603-11ea-95e4-575fa2b2bbba.png)
![2020-04-03_17 30 56](https://user-images.githubusercontent.com/41557212/78420385-8cf3f880-7603-11ea-8b8c-64a27ef49362.png)
![2020-04-03_23 18 54](https://user-images.githubusercontent.com/41557212/78420386-8d8c8f00-7603-11ea-92f1-1fb81d2620fa.png)
![2020-04-03_23 28 54](https://user-images.githubusercontent.com/41557212/78420387-8e252580-7603-11ea-80bb-a7978b815bc9.png)

**Comment by wlhlm** [comment]
Is this still a problem with the latest 2.0.8.8 release? Infernal Mobs has gotten an update halfway through the 2.0.8.x cycle (in 2.0.8.6).
