### ISSUE TITLE
Quest 2025 not detecting items

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#5525]
Playing GTNH 2.0.8.3.

GT++ knowledge, id 2025, does not detect any of the four books.

Using the name remover does NOT help.

**Comment by Prometheus0000** [comment]
The thermal boiler book was detected anyways, maybe you made the 5th, useless book by mistake? I fixed it so it detects the crafted versions of the other 3.
