### ISSUE TITLE
Dragon egg availability issue

### ISSUE THREAD

**Issue by Waisse** [GTNewHorizons/GT-New-Horizons-Modpack#5530]
GTNH 2.0.8.3 on the official Epsilon server.

The oblivion branch for bees all require the end flower which is the dragon egg. This branch is the only source of amnesic wax, used for magic frames.

In a singleplayer world or small server it would be easy to get the first egg, but on the official server it is too late, and getting another egg after the first dragon on the main island has been defeated is way way harder than the first one, and probably impossible at MV. 

> 
Yes you can get rid of the flower trait via breeding, it would require a lot of breeding cycle and RNG. This would be fine if I had access to frames better than chocolate which unfortunately oblivion bee is gatekeeping. There is also the issue of oblivion hive availability which are only found under the main island.

**Comment by Prometheus0000** [comment]
I think you can buy hives. Maybe the hee flower could be added as an additional end flower type? I think it changes after enough time (maybe not in a pot, but would it still count as a flower then?) or something, but you could still use the natural ones.

Or have admins place a dragon egg and surround it with bedrock or something.

**Comment by chochem** [comment]
> ...which unfortunately oblivion bee is gatekeeping. There is also the issue of oblivion hive availability which are only found under the main island.

Seriously? Why did I spend my time on discord to explain to you step by step how to unlock and get oblivion hives with coins?

**Comment by Waisse** [comment]
You can buy the hive with coins, I know, but this isn't the main issue of this thread. 
Even then, the quest to trade the hive is locked behind kill endermen quest, and we all know how cancerous combat is in this pack. TPS constantly fluctuating, combined with the threat of infernals ... it was easier to take a blood bucket and waterfall behind the island than trying to engage monsters.

**Comment by quedral** [comment]
You should be able to kill few endermans even if they are infernals.

**Comment by chochem** [comment]
Also keep in mind that the end is balanced around HV+ (eye of ender recipe). So complaining that it is hard to get a dragon egg in MV doesn't make much sense.

Having said all that, there should of course be a reasonable option to get a dragon egg on large servers. Bees should work, but its not for everyone. I don't know how that is usually managed by server admins.  Prometheus0000 already made a suggestion. another could be to make the dragon heart craftable or otherwise available, so that players can use the chem reactor quest chain for their first heart.

**Comment by Waisse** [comment]
My issue concerns mostly the official server in which there is access to The End at spawn, so it's not gated behind HV. Forestry stuff is available at LV/MV.

**Comment by richardhendricks** [comment]
The real issue is which frames require the amnesiac wax.  Is it just the best frames?

**Comment by Prometheus0000** [comment]
You can also get it from the Lapotron bees, though that would be much harder, and the end bees breed into other useful ones too.
The wax is used to make magic frames, which are used in gentle, resilient, necrotic, metabolic, temporal, and oblivion frames.
So all the magic bees frames, and not forestry, extra bees,  or GT++ bee frames.

**Comment by Waisse** [comment]
The end flower trait is recessive, so it's actually not an issue to replace it to a dominant one like simple flowers
