### ISSUE TITLE
Chunks unloading and reloading en mass

### ISSUE THREAD

**Issue by Entih** [GTNewHorizons/GT-New-Horizons-Modpack#5532]
#### Which modpack version are you using?
GTNH 2.0.8.3 with a few additional diagnostic tools (Sampler, TickProfiler, and OPIS)
#
#### If in multiplayer; On which server does this happen? 
Private server with up to 6-8 people at a time.
#
#### What is the issue
Over the past few weeks, my small group of friends have been playing.  Originally hosted on a personal server box by another, this issue arose.  Thinking it was hardware based, we transitioned the save to a paid hosting service; it persisted on the new machine.

Having spent the time since the transition attempting to diagnose the issue, here is what I found:

On this server, with entirely base-pack mods outside of diagnostic tools, an inordinate number of chunks are loading (Up to 4x what would be expected from server render distance), being pruned by Minecraft, and instantly loading back into place, causing massive, frequent, recurring lag spikes.  This occurs even if the server is placed into Peaceful mode, so hostile mobs may not be to blame.

While I have been able to observe the chunks churning in OPIS, and even output a trimmed log file showing the cause for every chunk load for 12 seconds of a churn (the number of chunk loads renders the file ~200 kb), nothing I can find in these traces means much to me, and appear to even be generic Minecraft functions to my eye.

I will attach the mentioned chunk load log, in hopes it helps with diagnostics, and can provide other information as needed.

Additionally, I will note that portions of the overworld, nether, and twilight (No other dimensions yet accessed) were generated using a chunk pre-generator prior to my taking over, though the pre-generator was removed as part of my suspicion early on.

[chunkloads.log](https://github.com/GTNewHorizons/NewHorizons/files/4168551/chunkloads.log)

**Comment by richardhendricks** [comment]
Interesting.  We can adjust the pathfinding issue in SpecialMobs. Right now it is just using the default zombie pathfinding, but we can override it so it doesn't attempt pathfinding into a chunk that isn't loaded. Or maybe require the 8 chunks around it to be loaded before it attempts to pathfind. I thought that is what vanilla does, but with 1.7.10, who knows.

**Comment by richardhendricks** [comment]
It's odd that it is always the zombie causing the chunkload. Something special about zombies vs skeletons or spiders or witches or endermen?

Also, the spawn animals is interesting. Perhaps they were being placed on a border with a chunk and that caused it to load the neighboring chunk? I wonder what could be causing that. I haven't looked at that function in Forge before.

**Comment by richardhendricks** [comment]
While I did put this in 2.0.11, we'll probably be looking at performance issues throughout.

**Comment by richardhendricks** [comment]
Can you provide your tools and instructions on how you set them up? 

This would save me time hunting them all down/getting them working.  We could also write it up as a wiki page to help others.

**Comment by Entih** [comment]
[diagnosticmods.zip](https://github.com/GTNewHorizons/NewHorizons/files/4168618/diagnosticmods.zip)

The exact diagnostic mods used are in the zip file provided here.  All of them go in the server's mod folder, but OPIS needs to be included into the client mod folder as well, as it provides an external tool window to see server information.

Use /opis to open the tool window, with various capabilities.  This tool allowed me to notice the massive chunk numbers and how their change corresponded to lag spikes.

Sampler is the second most important tool provided.  Of use in getting chunk load data as provided, use /sampler loads show (or hide to stop), which logs chunk load traces to server console.

TickProfiler is tertiary, and was used before the issue was traced to chunks.

Web pages for each tool:
https://www.curseforge.com/minecraft/mc-mods/sampler
https://www.curseforge.com/minecraft/mc-mods/tickprofiler
https://www.curseforge.com/minecraft/mc-mods/opis (zipped OPIS mod is a more recent community version W/O map function)

Also, I do not suspect infernal mobs are particularly to blame (perhaps partially), as the issue exists even on Peaceful mode, after purging all hostile mobs from the server.

**Comment by richardhendricks** [comment]
In this world, do you have a lot of chunkloaders by chance? 

I wonder if the chunkloaders are making a small 3x3 chunk area valid, but spawns happening on the edges cause the nearby chunks to load. 

We can try looking into how Minecraft does its pathfinding/spawning for more details.

**Comment by Entih** [comment]
Theres no active chunk loaders, just ~ 4 players at a time (though the players are spread out).

**Comment by MrWye** [comment]
On official servers, attempting /cofh killall followed by /lagg unloadchunks does not alleviate the issue at all. I am not sure if this in fact can properly unload the chunks but nothing seems to work so far. It does improve the tps, but spikes are just persistent. At some point i thought that server is simply low on memory, but not really, forcing garbage collection doesn't seem to help either since this is apparently not the problem. Spikes on Epsilon specifically did start after latest update, and i have been trying to find the reason since.

**Comment by Entih** [comment]
I was able to mitigate a lot of the symptoms of the lag spikes by introducing fastcraft into the server, but as for the cause of the chunks unloading and reloading that cause the lag, I am still bewildered.

Wasn't fastcraft in the pack by default at some point?

**Comment by richardhendricks** [comment]
https://www.minecraftforge.net/forum/topic/26474-1710check-if-chunk-is-loaded/

**Comment by richardhendricks** [comment]
https://www.reddit.com/r/feedthebeast/comments/85gu4l/how_do_modded_tile_entities_interact_with_lazily/?utm_source=amp&utm_medium=&utm_content=post_body

**Comment by richardhendricks** [comment]
@Entih I dont remember if we already discussed this, but do your chunks have any spreading plants? Im thinking glow flower or glint weed.

**Comment by Entih** [comment]
Considering the chunks loaded increases to over 2000 at times I can assure you there are pams gardens in a large subsection of the chunks.

**Comment by richardhendricks** [comment]
I can't really explain the zombie pathing.  I've seen it a few times too, and it *looks* like a zombie is walking in an area that isn't chunkloaded.  So I don't know if it is somehow chunkloading itself? I only see 1 chunk load event from it, but maybe Sampler is suppressing them, idk.  Opis doesn't find a whole lot of load from them in general though. 

https://pastebin.com/88hqKGMe

I told mitch about the grass chunk churn, maybe we can patch it.  Looks like newer Minecraft does check to make sure the block exists (aka chunk is loaded) before trying to spread grass onto it.

**Comment by richardhendricks** [comment]
You can try messing with the Force chunkloading config files.  Maybe try setting up a dormant ChunkCache?

I would definitely back up first, since it doesn't seem to be widely used.  

It might help with keeping your grass tick chunks in memory.  They will still get saved off to disk when unloaded, but reloading them should come from RAM.

The setting is in config\forgeChunkLoading.cfg

**Comment by BlackAce21** [comment]
Just chiming in as I was browsing issues section. I run ProsperCraft's server and we've been using the dormant chunk cache for years without issues. It does give a slight performance boost but its a pretty big memory hog, as you might expect. Without attacking the baseline problem though of chunks being loaded without cause, I doubt it'll do much more than band aid the problem for a longer time period between restarts.

This issue feels similar to a problem we had with a world generation script from world border. Running it would latch onto chunks and since everything was processed by one scheduled task, the loaded chunk objects would be kept alive so long as that scheduled task was still running in the background. Eventually the amount of mobs/chunks being kept alive by the process would reach a critical mass and everything would lock up. Not sure if you are doing anything like that but the problem could be a similar situation? Just my input. I haven't checked on the chunk loads for the PC server but I will give a check up and if I find we are having the same problem, I'll do my own investigation and report back if I find something.

**Comment by richardhendricks** [comment]
Mitch is working on a fix under his hodgepodge repo now. https://github.com/mitchej123/Hodgepodge There is a version pinned in #mod-dev, but it has a lot of print messages right now.

**Comment by richardhendricks** [comment]
@BlackAce21 How large do you set the dormant chunk cache?

**Comment by Dream-Master** [comment]
@mitchej123 @richardhendricks is this a client or sever mod or both ?

**Comment by mitchej123** [comment]
Both, currently only needed on the server but I could use it to patch some client side issues as well.

**Comment by mitchej123** [comment]
I'll have a version that addresses the grass chunk loads tonight.

**Comment by mitchej123** [comment]
This should fix the grass tick chunk loads - 
https://github.com/mitchej123/Hodgepodge/releases/tag/v1.1.0

**Comment by BlackAce21** [comment]
@richardhendricks we set ours at 4000 and the server with 2 hour uptime, 7 players online and ~1k chunks loaded is taking up ~7gb currently if that data is any indication for you. I am not noticing that we are experiencing any problems related to chunks not unloading on our server either but I will admit I am not watching it like a hawk.

My advice would be to assume a gig of memory per 2k chunks cached which is the rule of thumb I've been using over the years with varied results. When we've needed it I have pushed the chunk cache to as high as 10k but thats when we had more memory allocated to the server and that has its own list of optimization problems related to the java GC mostly but it can be worked around if you know how. Its also dependent on how many chunks get loaded on average. 4k seems to provide a solid boost for our player count and I haven't had to modify it in a while.

**Comment by mitchej123** [comment]
@Entih Any better with hodgepodge 1.1.0? Are there any other things causing massive chunk loads?

**Comment by Entih** [comment]
Alright, clonked the hodgepodge in the server for a quick test.  While it seems to have resolved grass chunk loads, mob movement and "spawneranimals" are still loading chunks by the hundred.  Usually the mob movement loads aren't as big an issue, but I was the only one on the server to test, and that means less actively loaded chunks.  The zombie meandering can be mitigated with a killall, at least!

I'm uploading a current log of chunk load traces as an example.  Mind the server is still on 2.0.8.3 as of now, so I am not sure if these are addressed in the new version, have been waiting for a changelog.

[chunkloads2.log](https://github.com/GTNewHorizons/NewHorizons/files/4239529/chunkloads2.log)
