### ISSUE TITLE
OpenComputers microchips crafting issues

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#5535]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
1) Tried to make T1 OC microchips, when put those materials inside circuit assembler (i am using multiblock Processing array with 1 IV in) it works ok, but when they are about to be sent via ME it doesnt work
2) Tried to make T2 microchips, using 1HV Nanoprocessor, Adv. circuit board, electrum foils,SMD transistors and programmed circuit n.2, but it but it crafted Control unit as it would if n.1 was used
#
#### What do you suggest instead/what changes do you propose?
Check those recipes for microchips please, also MV circuits needed for T1 which works are only Good Electronic Circs (the first craftable MVs)

**Comment by Dream-Master** [comment]
This is a known bug with circuit assembler picking out first circuit at mv.
@bartimaeusnek any idea how we can fix that? Maybe like the assembler fix ?

**Comment by Prometheus0000** [comment]
Dupicate of #4714
