### ISSUE TITLE
Infinite Fuel

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#5547]
#### Which modpack version are you using?

# 2.8.3.0
 If you hold shift and right click to extract fuel from the Fuel Loader of GalactiCraft with the hand pump,you will get a filled hand pump and the fuel in Fuel Loader wont decrease.
You can fill a Quantum Tank easily in this way.

**Comment by Dream-Master** [comment]
@draknyte1 is it possible to block GC devices using the pump ?

**Comment by Ethryan** [comment]
There exist a dupe bug of liquids with buildcraft tanks and the hand pump also. Suggest blacklisting the tanks if possible.
