### ISSUE TITLE
Suggestion: Radon as "END-Gate" of Ev-Tier

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/GT-New-Horizons-Modpack#5557]
#### Which modpack version are you using?

#  8.3
#### If in multiplayer; On which server does this happen? 

# //
#### What did you try to do, and what did you expect to happen?
 
# //
#### What happened instead? (Attach screenshots if needed)
//
# Radon, which is essential material, for progressing more freely at this tier, is capped (so) far behind Pu239. Its important for Quantum Eyes/Stars and for further more. 
My concern is that, without the ++ way, its gated behind nuclear reactors.

#### What do you suggest instead/what changes do you propose?
Create a new porcessing chain line that gives radon (even in small bases). Imho radon just does fill odd to use  .Its quiet off-meta and still important at the same time. I have some funny ideas about the design of the chain but i want to wait on how ppl want a change in general (not just me). Ofc with higher tiers Pu gets obtainable as an Ore, which kinda skips the nuclear breeding. So  
I see the use for this suggestion on adding things in ev and making it more accessable.

**Comment by 0lafe** [comment]
But it comes from EV planet stone too? 

If we change the ++ way to be worse, increase Rn in stars/eyes, or do something to make it less useful in EV, I'm all for a new chain. Could still use Pu tho lol

**Comment by GeicowithaBango** [comment]
which planet stone should that be?

**Comment by sthegreat** [comment]
rl radon for any inspiration:

Radon is obtained as a by-product of uraniferous ores processing after transferring into 1% solutions of hydrochloric or hydrobromic acids. The gas mixture extracted from the solutions contains H2, O2, He, Rn, CO2, H2O and hydrocarbons. The mixture is purified by passing it over copper at 993 K (720°C; 1,328 °F) to remove the H2 and the O2, and then KOH and P2O5 are used to remove the acids and moisture by sorption. Radon is condensed by liquid nitrogen and purified from residue gases by sublimation.

Would be nice to do a cool new realistic uranium processing chain and have a radon byproduct as an option of that chain.

**Comment by Ethryan** [comment]
Wikipedia: High concentrations of radon can be found in some spring waters and hot springs.

Maybe some sort of reaction chain with BoP Hot Spring water might extract trace amounts of radon.

**Comment by GeicowithaBango** [comment]
thank you for your comment. an industrial approach seems like the best solution. it also   *allows* rn to be an well-placed iv gas. idk about the complexity of this chain, however, with barts implementation of noble gases for the ebf, it must be viewed critically since the discount at smelting ingots will be, with an industrial chain, out of control, imo

**Comment by Prometheus0000** [comment]
What even is the purpose of this issue? You don't like the way something is acquired so you want another way? What's wrong with nuclear reactors or GT++? And you only need a tiny amount of it? Plus as mentioned in #4606 there's several ways to get it. You can suggest another recipe over there.

**Comment by GeicowithaBango** [comment]
@Prometheus0000 the amounts you obtain by sifting are too low. radon is used in circuits, so it’s definitely something you have to have in mind. the other alternative(for ev) is breeding plutonium which takes ever and is not really enjoyable

**Comment by Prometheus0000** [comment]
I didn't have a problem with it, but I also didn't mass produce circuits that needed it. Either way, use the other issue to suggest another recipe even if it's not for the vat (there can be multiple tiers to vat recipes too), I want to keep the number of issues down.

**Comment by GeicowithaBango** [comment]
sure, lets keep this issue closed then
