### ISSUE TITLE
[OC] Cannot craft tier 3 microchips with higher tier EV circuits

### ISSUE THREAD

**Issue by Mogball** [GTNewHorizons/GT-New-Horizons-Modpack#5564]
#### Which modpack version are you using?
2.0.8.3

#
#### What did you try to do, and what did you expect to happen?
Craft opencomputers' tier 3 microchips with quantum processors.
#
#### What happened instead? (Attach screenshots if needed)
Doesn't craft.
#
#### What do you suggest instead/what changes do you propose?
Enabling ore dictionary on the microchip tier 3 recipe so that it accepts EV-tier circuits other than the workstation, which would make it consistent with the tier 1 and tier 2 microchip recipes which allow any HV or MV circuit.

**Comment by repo-alt** [comment]
Probably the same as https://github.com/GTNewHorizons/NewHorizons/issues/5154 and like 4 other similar bug reports

**Comment by Prometheus0000** [comment]
Dupicate of #4714
