### ISSUE TITLE
[Suggest]Fine tune the number of singularities for automation

### ISSUE THREAD

**Issue by Kiwi233** [GTNewHorizons/GT-New-Horizons-Modpack#5567]
#### Which modpack version are you using?
2.0.8.3

https://cdn.discordapp.com/attachments/487824795216379914/635472445003792424/Singularity.xlsx

Plz change like this:
911 ---> 912
1821 ---> 3 x 608 = 1824
3642 ---> 6 x 608 = 3648
7283 ---> 12 x 608 = 7296

**Comment by Prometheus0000** [comment]
I can't open that file, and I see commits, so I'm going to assume this is done
