### ISSUE TITLE
Quest #1814 requested chemical crafts is not enough to make 30 bars

### ISSUE THREAD

**Issue by daddy77gaming** [GTNewHorizons/GT-New-Horizons-Modpack#5568]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
toasted
#
#### What did you try to do, and what did you expect to happen?
follow quest #1814 expect advised amounts to be enough to make final craft.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/31905330/74446959-e730d280-4e78-11ea-865f-148778aedd99.png)
![image](https://user-images.githubusercontent.com/31905330/74447070-0def0900-4e79-11ea-92d0-b6be22d2eb46.png)

#
#### What happened instead? (Attach screenshots if needed)
30 bars needs 4320mb
#
#### What do you suggest instead/what changes do you propose?
ask for 20 bars which is just under 3000mb the rest of the quest gives

**Comment by Prometheus0000** [comment]
You get 4500 if you use oxygen instead of air, which you should have a decent amount of at this point. Not to mention the quest literally says to use oxygen. You get 31 that way.
