### ISSUE TITLE
Bricked blast furnace does not resume on blocking/unblocking top opening

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#5572]
#### Which modpack version are you using?
dev

The Bricked or the Bronze Blast Furnace will not resume processing, even after removing the blocking of the open top block during operation.

See: https://github.com/GTNewHorizons/GT5-Unofficial/issues/240

**Comment by Prometheus0000** [comment]
Link is bad, but can confirm
