### ISSUE TITLE
Suggestion: Greatly reduce the amount of warp gained from Blood Magic research

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5574]
#### Which modpack version are you using?
2.0.8.3
#
Mentioned in #4843, the amount of warp in these researches is insane. Given that BM doesn't even naturally have such a mechanic, plus the fact that it's just too much (3 times the amount to get withers!) I suggest reducing it quite a lot. I know it (maybe) fits the theme somewhat, but it greatly discourages people from using it. Given that it's available from MV, but that people avoid it until they have pure tears (LuV), that seems to go against the tiering of the mod. If it's necessary to have lots of warp, maybe it could be concentrated on specific items? Like the ones to summon the demon invasion for example.
#
#### What do you suggest instead/what changes do you propose?
Reduce the amount of warp on these researches.

**Comment by boubou19** [comment]
closing this as it's in the pack since a year now

**Comment by Prometheus0000** [comment]
You mean rejected since a year ago.
