### ISSUE TITLE
Stretched night vision potion not craftable in GT brewery

### ISSUE THREAD

**Issue by daddy77gaming** [GTNewHorizons/GT-New-Horizons-Modpack#5587]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
toasted
#
#### What did you try to do, and what did you expect to happen?
brew this recipe.
![image](https://user-images.githubusercontent.com/31905330/74597004-b955b480-5057-11ea-9989-0a10fc7e2a2b.png)

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/31905330/74597016-cf637500-5057-11ea-960c-a49eaea0e1fb.png)
did it 2x to make sure it wasnt me skipping a step..
#
#### What do you suggest instead/what changes do you propose?
fix, xD

**Comment by daddy77gaming** [comment]
Adding to this.. also 

![image](https://user-images.githubusercontent.com/31905330/74597042-7516e400-5058-11ea-9f3d-7f5f12db1d27.png)

doesnt make the stretched

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/75594214-510bc780-5a88-11ea-8442-b9107df46c36.png)
?

**Comment by Dream-Master** [comment]
@daddy77gaming need more infos
