### ISSUE TITLE
seismic prospector works incorectly with negetif cordinates

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5588]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
MP
#
#### What did you try to do, and what did you expect to happen?
i tried lookign for a salt water field with the seimsic prosspector and when i placed the oil drill i got nothing instead of saltwater
after cheating in a electric prospector al the veins where shiftet to the left
![afbeelding](https://user-images.githubusercontent.com/42187820/74597920-b19e0c00-5067-11ea-88a5-41950b59b5d3.png)
the cordinates where ~ x=  -5K and y =  8K

**Comment by richardhendricks** [comment]
Probably due to Javas asinine rounding. Ill look into it.

**Comment by qthree** [comment]
Can confirm that there is off-by-one-oilfield error if coordinate is negative. Tested with negative/positive Y. When Y is negative it behaves as if prospector was not in [5] but in [8] oilfield (in Prospection Data schematic).
It's probably related to the fact that there is "positive zero" chunk, and  Z: 1 chunk has coordinates from 16 to 31, but Z: -1 chunk has coordinates from -0 to -15.

**Comment by repo-alt** [comment]
Since moron is mia, perhaps I'll fix it

**Comment by toadjaune** [comment]
Funny part is, it seems there is an off-by-one-oilfield error, but only on X coordinate. Z seems unaffected.
