### ISSUE TITLE
Bucket Duping

### ISSUE THREAD

**Issue by Zystus** [GTNewHorizons/GT-New-Horizons-Modpack#5591]
so when I was playing GT:NH I decided to craft the mud armor just for the quest I had a bucket from a reward bag so I did the dirt+Water Bucket recipe when I crafted mud something strange happened the water bucket I had stayed and I had +1 empty bucket I had ONLY 1 bucket before I did this craft because of the crafts I now have 14 buckets I am playing in a Single Player world 

![image](https://user-images.githubusercontent.com/31573458/74605064-628ec000-50d5-11ea-9c9d-d7cbaf557e16.png)
![image](https://user-images.githubusercontent.com/31573458/74605069-6a4e6480-50d5-11ea-9d99-dd09b52b1b09.png)
![image](https://user-images.githubusercontent.com/31573458/74605071-6e7a8200-50d5-11ea-8c4e-d0f2b2f0f80c.png)
![image](https://user-images.githubusercontent.com/31573458/74605073-73d7cc80-50d5-11ea-8e4b-31adf8720278.png)

**Comment by MadeofGold** [comment]
Tested , it works even in official servers (Delta)

**Comment by Dream-Master** [comment]
need to test all other reuse recipes

**Comment by EldrinnElantey** [comment]
The fix for this bug has already been added to the recipe script here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/47ca6245d5cdcaed51cfa6cd8373d3fdf61c1efe. Maybe it's time to close this issue?
