### ISSUE TITLE
NullPointerException on connect

### ISSUE THREAD

**Issue by FQLT** [GTNewHorizons/GT-New-Horizons-Modpack#5593]
#### Which modpack version are you using?
GT New Horizons-2.0.8.3-1.7.10
#
#### If in multiplayer; On which server does this happen? 
In local multiplayer server (Open to LAN button)
#
#### What did you try to do, and what did you expect to happen?
I tried to connect. I expect that I will be able to play the game
#
#### What happened instead? (Attach screenshots if needed)
NullPointerException
Crash log: https://pastebin.com/WnPfKz3m
It's happening all the time, no matter who is hosting the world and nothing changes with different accounts that are connecting
#
#### What do you suggest instead/what changes do you propose?
???

**Comment by Dream-Master** [comment]
Ticking scrren is normaly a random error.
@FQLT Try to update server to 2.0.8.4 or 2.0.8.5dev and report if this happend again.

**Comment by Dream-Master** [comment]
http://downloads.gtnewhorizons.com/ClientPacks/

**Comment by FQLT** [comment]
@Dream-Master Updated version to 2.0.8.4 - nothing has changed

**Comment by Dream-Master** [comment]
2.0.8.5 too ? @FQLT  Did you use a forge server? Did you add or change mods ?

**Comment by FQLT** [comment]
@Dream-Master Only 2.0.8.4 tested, fully redownloaded modpack, i'm using local multiplayer server through Open to LAN

**Comment by richardhendricks** [comment]
So, you are starting a single player game, selecting Open to LAN, and a second player cannot join?

**Comment by richardhendricks** [comment]
No Hamachi or other network bridges?

**Comment by FQLT** [comment]
Yes, when other players try to join my LAN game they got a NullPointerException in minecraft, we are using Hamachi to connect

**Comment by quedral** [comment]
I know things get broken when you try to set up LAN game. This may be one of these cases. You gotta try with proper server and see if you are getting same errors.

**Comment by mitchej123** [comment]
Open to Lan is super buggy; I'd advocate for using an actual dedicated server process
