### ISSUE TITLE
wax capsule filled with water give ice capsule

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#5610]
#### Which modpack version are you using?
283
#
#### If in multiplayer; On which server does this happen? 
myftb
#
#### What did you try to do, and what did you expect to happen?
fill wax capsule with water for acclimatiser 
#
#### What happened instead? (Attach screenshots if needed)
-> ice capsule (bart works) instead water capsule -> they don't work in acclimatiser
#
#### What do you suggest instead/what changes do you propose?
because of no special use of ice capsule from bart works in NEI -> correction to get water capsule

**Comment by dragagon** [comment]
As a follow up, you can use the fluid canner with water, but it gives you bart's water capsule, which also doesn't work in the acclimitizer.

**Comment by Ngar1** [comment]
Please correct this failure! 

The forestry wax capsule should usable for forestry (addon)! This change brake compatibility with the mod forestry(and Addon) of its own.

If other mods want specific solution, they should use there parts if not be able to let it compatible..
