### ISSUE TITLE
Integral Encasement I - molten steel issue

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#5617]
#### Which modpack version are you using?
.8.5
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
In crafting Algae Farm, you need to craft 4x Integral Encasement I which need among others molten steel for the recipe. It can be hardly intended but there is no amount of steel "needed" for each run.
![2020-02-19_01 19 23](https://user-images.githubusercontent.com/14223368/74789811-19e22d00-52b6-11ea-880e-946301690fbc.png) so it works with i guess any amount rn.

**Comment by Dream-Master** [comment]
https://github.com/alkcorp/GTplusplus/issues/644

**Comment by draknyte1** [comment]
Fixed in Dev.
