### ISSUE TITLE
Suggestion: New, Assembly line like GT machine that can accept TC Aspects and does faster Infusion.

### ISSUE THREAD

**Issue by quedral** [GTNewHorizons/GT-New-Horizons-Modpack#5630]
Even though TC infusion can be automated someway (SFM/OC/WA's and AE2 addon) its bit tedious and done maybe 20 times before.

We've been brain-farting on discord github channel and i've came up an idea like this one. Why not add an ass line that can accept aspects and do faster infusion.

I do not know if this is possible or viable or even favourable since there are people like to stick with the original way of crafting TC infusion items.

**Comment by 0lafe** [comment]
Isn't the assline more tedious to craft with than infusion? Like idk if I'm even mad at the idea, but they're almost the same concept but the assline needs specific items in specific spots. More specific item logistics compared to the simple distribution of infusion mats. 

Also how would things like essentia work? The infusion provider is nice and easy, could GT pull from that? It could be a lil weird with fluid hatches for it, but if essentia is a fluid it could work. High-key seems like this makes infusions more difficult tho

**Comment by quedral** [comment]
well some kind of essence accepting block must be coded for sure if its going to be a multiblock. single block assembler that can accept essentia is also a viable idea. i don't necessarily insist on ass line multiblock.

**Comment by leagris** [comment]
From having dealt with essentia absorption when Improved the Magical Energy Absorber, I can tell you that essentia absorption is a pain to deal with the Thaumcraft API.
First it can only absorb essentia from containers at a given range. Accessing essentia fluids directly requires hacking inside non-api Thaumcraft classes, with the numerous possibilities of stuffs going wrong (see the number of bugs in ThaumicEnergistics. I even tried allowing connection of essentia tubes to the Absorber, and the suction system is equally a nightmare.

**Comment by Prometheus0000** [comment]
Personally I'd like to ask, what does this do that the normal infusion currently doesn't? Are you just trying to 'tech' a magic mod? You'd still have to automate input, and you'd still have to automate output (without a filter I guess). Is it necessary to be faster? Which recipes? Maybe the recipes should be altered instead. If it's the multiple compressed solars, do we really need more solars to begin with?

**Comment by quedral** [comment]
Automating current infusion takes combination of many mod items including placing hoppers on pedestals and world acceleration block placed near matrix and thaumic energestics shenanigans. You can go with steves factory manager or open computers as well. My suggestion will grant this process to be accomplish with a single mod and provided with gt power tiers we have it will be completed faster than infusion altar. Late tc stuff takes alot of mats and gets really complicated to automate. Thats why i came with this suggestion.

**Comment by sthegreat** [comment]
I'm fine with this if and only if it's at least as complicated as normal infusion and it maintains a magical or magi-tech (like EMT) theming. Infusion is an actually interesting mechanic (well kind of interesting, it's basically a simpler/easier assline) and it would be bad to have it killed in favor of some boring assembler.

**Comment by Prometheus0000** [comment]
Why does it need to be faster? Why does it need tiers? How would this reduce the number of mods involved? Is multiple mod usage supposed to be bad? Which things specifically do you have a problem with. I can't really give an opinion if I don't know which ones. If it's like the assline, you'd still need OC of SFM, wouldn't you? And TE for storing+supplying the essentia. This seems like a solution in search of a problem to me.

**Comment by 0lafe** [comment]
>make it like the assline
That makes infusion harder 
>Make it a singleblock 
Bruh why easier? 

This thread confuses me to no end

**Comment by mitchej123** [comment]
Any sufficiently advanced technology is indistinguishable from magic.  The more advanced you get, the more obvious it's tech.

**Comment by sthegreat** [comment]
mitch im like 99% sure that those sentences directly contradict each other

**Comment by botn365** [comment]
the only reason why this should exist is to make infusion faster without the use of WA

**Comment by chochem** [comment]
We have an actually interesting multiblock from a non-gt mod. Please keep it! It can be automated, has natural speed tiers through WA, nice animations and sound, an AE interface for essentia, ...

to keep it short, I am heavily against this.

**Comment by Dream-Master** [comment]
Magic is magic and tech is tech. Not mixing it to much.

**Comment by Prometheus0000** [comment]
If the only problem is speed, 1.12 had the 'ancient stone' version that was supposed to be better but didn't work (at least in FTB:I), and blocks you placed under the pillars to increase speed/stability. Backporting those or creating something similar would probably be significantly less work. Adding multiple tiers of stone (arcane/ancient/eldritch/spacey?/supertechy?) would fit the tiering thing too.

Whatever you do, you'll have to convince someone capable of coding to spend their time on it.
