### ISSUE TITLE
GT ore in BM meteor not picked up by miners

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5642]
#### Which modpack version are you using?
2.0.8.4
#### What did you try to do, and what did you expect to happen?
Mine meteor with single/multi miner, get ore.
#
#### What happened instead? (Attach screenshots if needed)
Does not get ore

#
To setup to test:
Get ritual stone, master ritual stone, ritual diviner (dusk), awakened activation crystal, blood orb of armok (infinite lp), divination sigil.
Use the crystal, divination sigil, and orb to tie them to you. Check with the sigil to see a big number, if not try using the orb again.
Shift right click the diviner until it says the falling tower ritual.
Place the master ritual stone in the air, and use the diviner on it. Try not to block any of the spots it places things.
Place a block in the air 20-30 blocks directly above the master ritual stone.
Use the crystal on the master ritual stone, it should have particles. If not, try using the orb or waiting a bit.
Throw down iron block/diamond/nether star to get a meteor (stone has almost no ore).
If using Github version, they all have GT ore, if not use the one that has certus quartz in it.
Set up a miner and try to get ore. It's all ignored.

moronwmachinegun: Ah, I bet you are setting up the tile entity but not the meta tile entity

This might not be fixable without forking BM, I dunno.

#
#### What do you suggest instead/what changes do you propose?
See how annoying it would be to fix. Consider fixing it if it's not too hard.

**Comment by Dream-Master** [comment]
BM is forked and we changed things allready so far ik

**Comment by eigenraven** [comment]
Was later duplicated: <https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10176>
Fixed by <https://github.com/GTNewHorizons/BloodMagic/pull/23>
