### ISSUE TITLE
[GT++] Advanced boiler [lv] is not capped at 32 buckets of steam

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#5644]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
delta
#

see https://github.com/alkcorp/GTplusplus/issues/645

**Comment by draknyte1** [comment]
WAILA issue. 
Won’t fix.

**Comment by boubou19** [comment]
look the tricorder it says also the same thing plus i can recover that steam so not a waila issue

**Comment by draknyte1** [comment]
It’s supposed to have that capacity. 

Whatever says otherwise is wrong, it’s a visual issue. I tried fixing it years ago and don’t care enough to try again. 

All boilers had this same issue last I checked, making it not *my* issue. It’s either Core GT or WAILA.

**Comment by boubou19** [comment]
Then how do you explain this behavior: when i have 55 bucket stored in an advanced boiler [lv]
then i allow the steam output i get 55 buckets not 32 it's not a visual bug...

**Comment by draknyte1** [comment]
It’s capacity is not 32k and like Bronze Age boilers, vents half its tank when at capacity. 

Don’t see what you don’t understand here.. the fact you think it’s 32k shows it’s a visual issue. 🤔

**Comment by boubou19** [comment]
ok so the supposedly visualbug with 44 -ish buckets boiler, when i discharge the steam in a bedrockium tank directly next to it (no other source of steam input in the drum i checked)
it gets the 44-ish buckets in it. ![2020-02-24_12 38 57](https://user-images.githubusercontent.com/12850933/75149576-a64f7e00-5702-11ea-8f33-7f1a417bb386.png)

 the boiler behaves exactly as if it was a 64k limit. So I DO AGREE that the steam 32k limit is a visual bug. But AS YOU SAID, it should be a 32k limit that's the issue here.

**Comment by boubou19** [comment]
anyways you don't want to fix it, at least put its actual capacity in the tooltip or that there is a x2 coefficient between what waila and tricorder said, and the actual capacity.

**Comment by draknyte1** [comment]
> AS YOU SAID, it should be a 32k limit that's the issue here.

I’ve said that the capacity isn’t 32k..

**Comment by boubou19** [comment]
you did not say it was 64k for the lv version: there is no wiki page for the boilers nor in game way to detect the correct size of the buffer afaik. It would have been easier if you had said that "the capacity is 64k" instead of "the capacity isn’t 32k".

How am i supposed to know that the correct size is 64k if there is a visual bug on it and not another tank size?  We are not in your head so we cannot know it's the correct size if you don't write it somewhere...

**Comment by richardhendricks** [comment]
I think there's a similar issue with the HP solar boilers, we need to check the WAILA code to see how it is getting the tank capacity.
