### ISSUE TITLE
BW fluids don't work in sfm

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5646]
#### Which modpack version are you using?
2.0.8.3.smth

#### What do you suggest instead/what changes do you propose?

When you try to specify a few BW fluids, the filter changes to something else. Trying filter acidic iridium solution will switch to biogass for example. Acidic osmium becomes pahoehoe and CaCl2 is uu as well. Could be related to sfm string thing? Idk

**Comment by GTNH-Colen** [comment]
Yep just encountered this issue myself while testing in SP, very strange behaviour. SeaweedBroth changes to Ethanol for some reason.

**Comment by Prometheus0000** [comment]
Couldn't this be used to cheese particular fluids if you figured out the pattern of the changing? That sounds real bad.

**Comment by KoljaStrohm** [comment]
I have the same issue:
Osmium Solution -> sap
Rhodium Sulfate -> molten glass
Aqua Regia -> Poison

could this be the problem: https://github.com/GTNewHorizons/Steve-s-Factory-Manager/blob/14973c2db4df31f415815dd54bf18b381c23b9c0/src/main/java/vswe/stevesfactory/network/DataBitHelper.java#L35

**Comment by KoljaStrohm** [comment]
I tested it locally and changed the 10 to a 32. this fixed the issue for me

**Comment by Prometheus0000** [comment]
Would it break everyone else's fluid SFM moving that isn't doing BW stuff? Still probably worth it even if it does

**Comment by Dream-Master** [comment]
@KoljaStrohm can you do a pull request with your fix ? Thanks

**Comment by Dream-Master** [comment]
sure if it not breaks other stuff.

**Comment by KoljaStrohm** [comment]
I changed it in a way now such that it only breaks something if someone uses the fluid with the id 0 (don't know witch one it is or if it even exists). I will create a pull request soon.

**Comment by Dream-Master** [comment]
@KoljaStrohm glease ask for some changes maybe its possible to add it. Thanks

**Comment by Prometheus0000** [comment]
So, did this fix it? @0lafe You use SFM all the time, do you have an answer?

**Comment by 0lafe** [comment]
Seems to be fixed

**Comment by Prometheus0000** [comment]
Great.
