### ISSUE TITLE
Ore Finder Wand - No tooltip

### ISSUE THREAD

**Issue by shinkuri** [GTNewHorizons/GT-New-Horizons-Modpack#5654]
This issue seems to affect multiple versions. The below documented error happened in 8.1.

Working tooltip:
![image](https://user-images.githubusercontent.com/31353359/75374985-8a4c0800-58cd-11ea-8a7e-bd1219392685.png)

Broken tooltip:
![image](https://user-images.githubusercontent.com/31353359/75375037-9df76e80-58cd-11ea-8533-9e48df94e9d0.png)

**Comment by YannickMG** [comment]
Seems to work just fine in 2.1.2.0
<img width="408" alt="image" src="https://user-images.githubusercontent.com/5321549/177838409-9f06f7a9-6e62-480a-97e6-280da7e7cdac.png">
