### ISSUE TITLE
Interaction of Large Sifter Bonus and Platinum Line

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#5656]
#### Which modpack version are you using?
2.0.8.5dev
#
#### If in multiplayer; On which server does this happen? 
sp
#

The problem: The Large Sifter (GT++) gives a bonus output of 12%. At the moment this applies to the sifting in the platinum processing line (bartworks).

My test: I started with 720 platinum metallic powder. This gives you 640 platinum salt which you then sift (normally at 95%). through that I got 717 platinum metallic powder back. That means I only needed 3 platinum metallic powder to create 80 platinum dust as well as the other byproducts.

Conclusion: The details in this test depend on rng, but it should be clear that this needs to be fixed as platinum metallic powder is pretty much infinite for zero effort otherwise.

Background as I understand it: In past versions, there was an ASM by bart to overwrite the bonus. This was removed because of opposition by Alk. Alk has implemented an alternative path to suppress the bonus using a circuit (I dont know how it works exactly), but this has not made it to GTNH. Bart says he does not want to make any further adjustments on his side.

Reminder: Please stay civil if there is any discussion, this is a hot topic for both alk and bart already. They both have done amazing contributions to this modpack, so be nice!

**Comment by quedral** [comment]
there can be no fix if not both parties come to an agreement at this point. commendable attempt on your side but it is futile in my opinion.

**Comment by draknyte1** [comment]
If Bart won’t adjust it, it won’t ever change. Pointless discussion.

**Comment by 0lafe** [comment]
Can't bart use the items to limit bonus outputs?

**Comment by draknyte1** [comment]
> Can't bart use the items to limit bonus outputs?

> Bart says he does not want to make any further adjustments on his side

@0lafe

**Comment by chochem** [comment]
@draknyte1 hmm, any chance there could be a blacklist for bonus outputs in the configs? This seems like something many pack authors might want to have to be able to fix stuff themselves. I think we are using something like that for the enderio sagmill for example.

**Comment by draknyte1** [comment]
I don’t give a fuck what pack authors *may* want. It’s my mod and how it functions isn’t up for debate, nor is every aspect of every machine/etc going to be configurable. 

Bart was offered several solutions, didn’t take any, doesn’t care. Pester him, not me.

**Comment by chochem** [comment]
this was really not meant as an attack, order or anything like that. sorry. really. And yes, I have talked to Bart already (on discord).

But overall I fear @quedral got it right. :( I will just focus on the much simpler task on how I work around it in my playthrough. :P

**Comment by ScriptedPiky** [comment]
For further information for those about the specific circuit: Alk implemented an LV "bio-circuit" that is functional and prevents the associated bonus chances on multi-blocks from occurring, should a recipe require that bio-circuit. In fact, you could technically use this circuit for most of the other recipes in the Sifter as well to accomplish the desired output. The circuit is on the latest GTNH official update and can be implemented at any time, literally adding one item and one line of code to change, or multiple if you are adding a check if GT++ is loaded or not.

**Comment by Prometheus0000** [comment]
The Programmed Bio Circuit is shapelessly crafted from one of the 3 ULV circuits not LV. So it's easier to make than the normal one. It works with the block circuit programmer, but not the handheld one. Where is the config to allow it to change stuff? I didn't see it in the Gtplusplus config.

**Comment by GeicowithaBango** [comment]
Is there any way to warn players about thats issue?

**Comment by ScriptedPiky** [comment]
Ohh ah okay, was off by one-tier. There is no config, rather if a user (Bart in this case) wanted their recipe to not have the bonus, they could require the bio-circuit in their recipe if GT++ is loaded.

A way to warn about it is to notify them about it in the quests that feature the multiblock in the multiblocks tab, HV tab(?), and GT++ tab.

**Comment by draknyte1** [comment]
Block one is mine, handheld one is Barts. I don’t think he cares enough to add support, lul.

**Comment by ScriptedPiky** [comment]
> Hell, developers can adjust the parallelism, speed, EU & output bonuses on all multis by registering an item via my API. It will then effect any recipe it’s in on any multi.

Wait wait wait, that's possible to achieve? Well, you learn something new every day! Was this not previously known for the other developers? If so, then there are some very interesting possibilities at hand.

**Comment by draknyte1** [comment]
I added the capability explicitly for Bart.

**Comment by Prometheus0000** [comment]
If bart isn't going to do anything, maybe lower the percentage chance to get platinum metallic powder back in the recipe to account for the bonus? That would punish people not using the large sifter, but I don't know how many people that would be.

**Comment by 0lafe** [comment]
Punishing people for not using the unchangable OP method seems like a poor choice. Why not just add it to the recipe outside of BW with MT or coremod shits?

**Comment by Prometheus0000** [comment]
Isn't that what I said? I'm not familiar with the platinum processing stuff so I assume that the sifting of platinum salt could be changed from 95% to ~85% to account for the bonus.

By unchangeable OP method, do you mean the platinum stuff is BW instead of added to GT so it can't be changed directly? I thought it was only part of GTNH. But changing it with MT sounds good too. Better than forking BW just for this at least.

**Comment by draknyte1** [comment]
> account for the bonus

That was my first suggestion. Bart didn’t do it. 

0lafe considers ++ multis OP and refuses to use them.

**Comment by 0lafe** [comment]
^ if we wanna balance the *whole* recipe for the sifter I'd be more onboard, but that probably means time/v or both in some way. Running single PA limit vs multi sifter, accounting for optimal speeds on the PA, you get some noticeable differences in power/speed. 

HV: sifter is ~280% faster, uses ~53% the eu/t, resulting in ~18% power/item compared to 17 LV sifters
EV: sifter drops to 200% speed, 75% power draw, and ~38% energy consumption overall, compared to 64 LV sifters
IV: it's back up to ~245% speed, down to 94% power draw, and ~38% energy consumption compared to 64 MV sifters
LuV drops it to 150% speed, 28% power draw, and 19% overall power/item, compared to 64 HV sifters
The values of LuV are somewhat repeated, with the speed slowly increasing as the PA is simply OCing while the sifter is adding a few parallels each time 

Not only is the sifting multi 1.5-2x faster for LuV+ but it's also using ~1/5 the total power. If we wanna increase the recipe to maybe 4x the current time, it would leave the OCing logic the same, make running it at EV-IV a little bit worse (1.5x power), and make HV/LuV+ take a little less power than the current recipe in GT machines. Then just change % to give the current % with  the bonus, it's pretty close to the same thing. Seems somewhat worse than just adding an item to a recipe, but :shrug:

**Comment by Prometheus0000** [comment]
...In any case, when I opened my 2.0.8.x instance to look, I saw that at least one other step in the platinum processing has a similar step, so probably multiple recipes (one for each platinum chain metal?) would need to be changed if that's what's going to happen, whether by MT or whatever.

**Comment by GeicowithaBango** [comment]
its getting absurd if you use gt++ multis with in higher tiers. the bonus you will get (discount) cant be verified within the coast of a multi block. this issue can be

**Comment by chochem** [comment]
@GeicowithaBango seriously no idea what you wanted to say (was that google translate?), but it surely doesn't sound related to this thread.

@Prometheus0000 yeah, this should apply to the rest of the platinum group. Platinum, Palladium, and Rhodium come to mind for sieving. Though there is no cycle-structure to Rhodium I think, which only leaves Platinum and Palladium.

@0lafe If you dont want to use gt++ machines, that is very strange, but up to you. Please dont expect stuff to be balanced around that though. For everyone else they are an integral part of the modpack. Progressing from singles to more efficient multiblocks is quite interesting and rewarding gameplay, while PAs for everything sound incredibly boring.

**Comment by GeicowithaBango** [comment]
@chochem the efficiency of ++multis is not justified in higher tiers. im positive that this fact is related to this very issue. pls think befor talking.

**Comment by GeicowithaBango** [comment]
maybe for some grass-eating iv player. but 20% discount in any UV recipe is not justified.

**Comment by GTNH-Colen** [comment]
> @chochem the efficiency of ++multis is not justified in higher tiers. im positive that this fact is related to this very issue. pls think befor talking.

Let's be careful to keep this related to the platinum line and not devolve into another "GT++ bad" flame war...

**Comment by 0lafe** [comment]
If you're arguing for the prioritization of using ++ multis that's fine, but make them balanced for the recipe theyre needed for. Sifting % is one thing, but I'm not arguing that you need to be able to use singles as well, I'm fine forcing ++ multis for things if you actually take the time to make the recipes balanced for ++. 4xing the time, in addition to an output decrease does just that.

**Comment by GeicowithaBango** [comment]
balancing around ++ is against dreams will. so close this issue finally.

**Comment by 0lafe** [comment]
Yes let's leave something that increases Pt proc yields by 30x+.....

**Comment by richardhendricks** [comment]
Overall GT++ balance issues is outside the scope of this ticket. 

Fixing the excess output for platinum group processing is the only focus of this ticket moving forwards.

**Comment by Glease** [comment]
Fixed by GTNewHorizons/GTPP#5
