### ISSUE TITLE
DeepDark ores need adjusting

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5665]
#### Which modpack version are you using?
2.0.8.3
#
Some of the ore choices in the DD make no sense, why do we have materials with no use and are lacking some which are actually useful?

I propose we add the following:

Barium
Coal
Europium (??)
Redstone

Europium ore was removed from lower tier planets and now spawns nowhere, perhaps it would be better suited in the DD?

And thus remove the following:

Ceruclase
Vulcanite
Vyroxeres
Ilmenite (Unsure on this one, feel free to tell me your thoughts)
Rubracium

There is honestly probably quite a few others that could go, like limonite veins but I would like to hear other peoples thoughts on this issue. Currently a lot of this stuff just serves to clog up AE systems and dilute down useful ores.

**Comment by 0lafe** [comment]
Eu was removed because fusion products shouldn't be ores, but the rest seem fine. I think the metallurgy shit is eventually gonna get some implementation, but it doesn't really have to be there until that happens

**Comment by GTNH-Colen** [comment]
Compared to real life no but europium is a ZPM material, I don't think it'd hurt that much to possibly include it in a place gated by infinity.. We could even talk about maybe adding indium ore, it's not like you can't get abundant indium by that point via fusion anyways.

**Comment by Prometheus0000** [comment]
Personally I say it should have only pure ores, tungsten instead of tungstate, titanium instead of ilmenite, but aren't some used for funky stuff like the chalcopyrite/pentlandite with nitric acid to make the platinum stuff or sphalerite+galena to make indium? Those should also just have the pure ores available, but is there anything that doesn't have an ore? Like, there's no fluorine ore, but there are things that contain it like the GT++ ores (but at this level you probably get tons from black stonelilies or something else I don't know about), but I don't know about adding those. Though is there a reason not to? Removing ores that serve no purpose sounds good to me, they can be readded if they get some use later.

**Comment by GTNH-Colen** [comment]
> Personally I say it should have only pure ores, tungsten instead of tungstate, titanium instead of ilmenite, but aren't some used for funky stuff like the chalcopyrite/pentlandite with nitric acid to make the platinum stuff or sphalerite+galena to make indium? Those should also just have the pure ores available, but is there anything that doesn't have an ore? Like, there's no fluorine ore, but there are things that contain it like the GT++ ores (but at this level you probably get tons from black stonelilies or something else I don't know about), but I don't know about adding those. Though is there a reason not to? Removing ores that serve no purpose sounds good to me, they can be readded if they get some use later.

There are other ways to make the platinum concentrate, the most common just being platinum metallic powder + aqua regia which doesn't require those ores. Additionally you can easily make vast quantities of indium much easier through MK3 fusion so I wouldn't worry about those too much. I do completely agree though that crap like tungstate and ilmenite just really serve no purpose at that tier and shouldn't be included in DD ore lists. I would submit a PR myself but i'm unsure on where exactly this data is stored internally or how to edit it in a friendly way.

**Comment by Prometheus0000** [comment]
Try looking at https://github.com/GTNewHorizons/NewHorizons/commit/3842a7ad97c8e0847956b1d6adcc95dc0bba9bc9
It looks like 'ore mixes' are veins, and lower down it sets whether it spawns in a dim by the number. 
Looks complicated though, and I don't know where the mixes are determined either.

**Comment by bartimaeusnek** [comment]
@Prometheus0000 we dont use that approach anymore. Check here: https://github.com/GTNewHorizons/GT5-Unofficial/blob/3bca4b84a8a3c146c658cb238b85658c2e3ca4f0/src/main/java/gregtech/loaders/postload/GT_Worldgenloader.java#L170

**Comment by Prometheus0000** [comment]
This is now obselete, see #6560
