### ISSUE TITLE
Ender IO Attraction Obelisk not working

### ISSUE THREAD

**Issue by noobnoobnub** [GTNewHorizons/GT-New-Horizons-Modpack#5673]
#### Which modpack version are you using?

#5637 
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#place the obelisk with power supply and redstone mode always active and soul vial with corresponding mob
#### What happened instead? (Attach screenshots if needed)

#mob ignore the obelisk

**Comment by Dream-Master** [comment]
@Zoko061602 any idea? You just add new stuff to ender io maybe you know more.

**Comment by mitchej123** [comment]
My guess: It's probably checking .class == SKELETON instead of isinstance Skeleton

**Comment by Dream-Master** [comment]
@mitchej123 can you fix that and i will add a testversion?

**Comment by mitchej123** [comment]
I was planning on looking at it after work; that's why I requested he submit a ticket.  If it's an easy fix I'll push it out

**Comment by Dream-Master** [comment]
ok thanks

**Comment by wlhlm** [comment]
It does exactly match the Id of the mobs for which Soul Vials have been provided:

```java
  private boolean isMobInFilter(String entityId) {
    for (int i = slotDefinition.minInputSlot; i <= slotDefinition.maxInputSlot; i++) {
      if(inventory[i] != null) {
        String mob = EnderIO.itemSoulVessel.getMobTypeFromStack(inventory[i]);
        if(mob != null && mob.equals(entityId)) {
          return true;
        }
      }
    }
    return false;
  }
```
[Source link](https://github.com/GTNewHorizons/EnderIO/blob/a833d3394836940c1d6b82e96f39afcc65cc1778/src/main/java/crazypants/enderio/machine/obelisk/attractor/TileAttractor.java#L248-L258)

The player has to put in a Soul Vial for every type of special Enderman. I don't think that it needs to be fixed to match all types of Endermen. This gives the player more fine grained control over which type of mob can be attracted. The Obelisk should have inventory space for enough Enderman types.

**Comment by mitchej123** [comment]
What usecase would people have for picking a specific type of enderman? I'd want all enderman.. or all skeletons, regardless of their special mobs type personally.

**Comment by Dream-Master** [comment]
why not collect all first.

**Comment by leagris** [comment]
Because the number of soul vial slots in the obelisk is limited, same for the opposite machine to repel mobs. An enderman soul vial should match any kind of enderman

**Comment by wlhlm** [comment]
If there is exact matching, you can sort your Enderman by type, maybe players want to put earch in their own grinder, or have other fun contraptions.

If I remember correctly, creating Ender IO Spawners using Soul Vial, it spawns the exact mob from the vial, not a random selection with the same parent class. So the obelisk mirrors that in a way.

But regardless of any (admittedly far fetched) reason for having specific matching that I could come up with, I've just checked Special Mobs and even though exact matching would maybe work for Endermen, there are simply too many Creeper types for this to work.

**Comment by mitchej123** [comment]
I'd advocate for attracting any of the same parent class. I can't come up with a realistic usecase for wanting to be so specific within subtypes of endermen or creepers.

**Comment by Dream-Master** [comment]
ok go ahead with one type off all enderman etc

**Comment by richardhendricks** [comment]
To give us more flexibility with mob control/options, I enabled the Special Mobs config option that replaces all vanilla mobs with "special mobs" variants - not the "SPECIAL" mobs, but just sm "vanilla" mobs that allow us to change behavior in the future. If you have a soul vial with the old vanilla, try changing to a SM vanilla mob and see if that works.

**Comment by Prometheus0000** [comment]
Is this fixed now?
