### ISSUE TITLE
GT5U, Crafted Firebricks holds useless NBT payload that is lost when harvesting

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#5686]
`/mt hand` on freshly crafted Firebricks:
```zenscript
<gregtech:gt.blockcasings4:15>.withTag(
{
  "GT.CraftingComponents": {
    "Ingredient.5": {
      id: 6916 as short,
      Count: 1 as byte,
      Damage: 32111 as short
    },
    "Ingredient.6": {
      id: 6916 as short,
      Count: 1 as byte,
      Damage: 32111 as short
    },
    "Ingredient.7": {
      id: 6916 as short,
      Count: 1 as byte,
      Damage: 2934 as short
    },
    "Ingredient.8": {
      id: 6916 as short,
      Count: 1 as byte,
      Damage: 32111 as short
    },
    "Ingredient.0": {
      id: 6916 as short,
      Count: 1 as byte,
      Damage: 32111 as short
    },
    "Ingredient.1": {
      id: 6916 as short,
      Count: 1 as byte,
      Damage: 2934 as short
    },
    "Ingredient.2": {
      id: 6916 as short,
      Count: 1 as byte,
      Damage: 32111 as short
    },
    "Ingredient.3": {
      id: 6916 as short,
      Count: 1 as byte,
      Damage: 32111 as short
    }
  }
})
```

`/mt hand` on wrenched-out Firebricks (harvested):
```zenscript
<gregtech:gt.blockcasings4:15>
```

Please fix by removing ingredient NBT from crafted Firebricks. It is not like they are of any use, except space filler on inventory data and network payload. And it prevents stacking wrenched-out casings with freshly crafted casings.

**Comment by richardhendricks** [comment]
AFAIK we don't have a way to prevent the GT disassembly data from being generated on any GT parts. The Name Remover block handles removing NBT Crafting Components data.

**Comment by leagris** [comment]
We have since the disassembly data existed with Solar Panels and was later removed from it due to obvious exponential growth when crafting upper tier Solar Panels and the player crash it caused.

**Comment by richardhendricks** [comment]
I bow before your superior knowledge. 🙇

**Comment by Prometheus0000** [comment]
No longer a problem with the removal of disassembly data.
