### ISSUE TITLE
Potin Rotors can't be made in the Fluid Solidifier or Extruder

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5698]
#### Which modpack version are you using?
2.0.8.5dev
#
They only have an assembler recipe
#
#### What do you suggest instead/what changes do you propose?
Add recipes for the Fluid Solidifier and Extruder.

**Comment by Dream-Master** [comment]
it's Gt++ material. Ask Alkalus

**Comment by Prometheus0000** [comment]
That's why I also made an issue there, same for the others since I was told to make one here as well just in case before.

**Comment by Dream-Master** [comment]
seen it after I post it 😀
