### ISSUE TITLE
Crop Gene Extractor Data Sticks to free Data Orbs

### ISSUE THREAD

**Issue by Ldmf** [GTNewHorizons/GT-New-Horizons-Modpack#5706]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Privet SMP/SSP
#
#### What did you try to do, and what did you expect to happen?
Use the Basic Crop Gene Extractor with a data srick and get a Data Orb instat a data stick back
#
#### What happened instead? (Attach screenshots if needed)
![2020-03-07_17 46 49](https://user-images.githubusercontent.com/15316448/76147353-bd478600-609b-11ea-9afe-5cb42c7d87b4.png)
![2020-03-07_17 46 41](https://user-images.githubusercontent.com/15316448/76147354-bf114980-609b-11ea-8c9a-08190787e919.png)
![2020-03-07_17 51 54](https://user-images.githubusercontent.com/15316448/76147424-5d051400-609c-11ea-97d5-0e11a95db855.png)

#
#### What do you suggest instead/what changes do you propose?
get data stick with Specimen Gr or GA or Re instat of a data orb

**Comment by Dream-Master** [comment]
can you check this @bartimaeusnek?  thanks
