### ISSUE TITLE
Dupe EC2 Fluids

### ISSUE THREAD

**Issue by 4gname** [GTNewHorizons/GT-New-Horizons-Modpack#5709]
#### Which modpack version are you using?
2.0.8.5dev
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
When ordering through a liquid interface, a duplicate of liquids takes place, prescription liquid is poured into each adjacent buffer
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/50260829/76153356-70949700-60fd-11ea-8cd7-09c78b6a76ab.png)

#
#### What do you suggest instead/what changes do you propose?
-

**Comment by repo-alt** [comment]
Can you post the pattern itself too?

**Comment by Dream-Master** [comment]
@DeForce can you help us here or is this a bug @repo-alt you can fix?

**Comment by 4gname** [comment]
[fixed](https://github.com/GTNewHorizons/ExtraCells2/commit/3a7bc94bb5b059d38a9df4a21a2dd2f007dc3103)

**Comment by Dream-Master** [comment]
I close this after release
