### ISSUE TITLE
Packager Processing Array + Super Bus sort mode off didn't work

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/GT-New-Horizons-Modpack#5711]
#### Which modpack version are you using?
2.0.8.4QF   
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
I have a lot of small/tiny dust and i need to process very fast : i can't craft GT++ packager for the moment so i use processing array (IV with 16 Packagers HV)

![2020-03-08_13 38 37](https://user-images.githubusercontent.com/17729817/76163056-4c5ba900-6143-11ea-8f6b-3961cf86deb3.png)

I use 2 filters to send dust in quantities of 4 or 9 + sort mode disabled on input bus (HV) : that's works but not optimally. 
However, there are 2 minor issues :  
- Processing Array can process only 1 kind of dust : for example, if input bus have 900 tiny silicon dust but 9 naquadah dust on the last input, machine will process only naquadah (because other slot contain an another dust...)
So, with 16 Packager, only 1 Packager will be used... it will process silicon dust when the last slot contain silicon too.
So my question here : possible to improve Processing Array to use ALL packagers inside ?

- About this previous issue, i test with a super bus : more slot so possibility to process more dust !
But when i disable sort mode on the super bus, that's didn't work very well... after few seconds, processing array stuck because some dust remain on bus (have never this problem with classic input bus)

#
#### What do you suggest instead/what changes do you propose?
Need to fix mode sort off for super bus and possible to improve processing array ?

I hope to be clear on the problem, you can reproduce the machine's configuration in SP if needed.

Thanks in advanced !

**Comment by Dream-Master** [comment]
@DV666 please report it here too.
https://github.com/alkcorp/GTplusplus/issues
Thanks

**Comment by DV666** [comment]
Issue open on GT++ github for Super Bus sort mode => https://github.com/alkcorp/GTplusplus/issues/653

**Comment by Prometheus0000** [comment]
I don't really understand your problem? Can't you just use separate input bus mode?
