### ISSUE TITLE
Concurrentmodifiaction Crash findCachedMatchingRecipe

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#5717]
#### Which modpack version are you using?
dev

Just IDLE at menu after loading world:

ConcurrentModificationException at bartimaeusnek.ASM.BWCoreStaticReplacementMethodes.findCachedMatchingRecipe

https://gist.github.com/leagris/2e41d5c1e4adcb71e81e261f4a594241

**Comment by Dream-Master** [comment]
@leagris try with Bartworks 0.5.12

**Comment by tworf** [comment]
I had the same crash with findCachedMatchingRecipe on **modpack version: 2.0.8.3** whenever I loaded my single player world.

FYI Upgrading to Bartworks 0.5.12 resolved the issue. Thanks.
