### ISSUE TITLE
The battery buffer does not work with the machine controller cover

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5719]
#### Which modpack version are you using?
2.0.8.5dev
#
#### What did you try to do, and what did you expect to happen?
Use the machine controller to turn off a battery buffer so the supplied machines stop receiving power, instead of having a machine controller on each machine.
#
#### What happened instead? (Attach screenshots if needed)
Nothing happens, regardless of cover or redstone state. It just keeps sending power from the battery.
#
#### What do you suggest instead/what changes do you propose?
I'm not sure if this is a bug, or if it never worked with them. I did find out they work with transformers, so I can use that, but It would be nice if I could use it with a batbuff too.

**Comment by richardhendricks** [comment]
Should be easy enough to implement I think.

**Comment by richardhendricks** [comment]
A shutter cover on the wire would be cheaper though wouldn't it?

**Comment by Prometheus0000** [comment]
Does it say you can do that anywhere? I don't think there's a quest for the shutter covers to explain you can do that. Probably because they were integrated into pipes? And you would need two covers instead of one.

**Comment by richardhendricks** [comment]
I don't think we ever had a shutter quest.  Why would you need two covers? You can disconnect the wires with just one. We'll still look at adding support for the machine controller cover to the battery buffer. Kinda weird it doesn't work.

**Comment by Prometheus0000** [comment]
The Shutter Module Cover says to use with a Machine Controller? Does it interact with redstone without it then?

**Comment by richardhendricks** [comment]
Ah yeah, I didn't see that detail. :)

**Comment by Prometheus0000** [comment]
Are you sure that works? It didn't work when I tried with the shutter or shutter+machine controller? Or with pipes? Or when I put it between them? I can't tell if I'm doing it right because the shutters appear to do nothing.

**Comment by Anarack** [comment]
I've done it with pipes in the past, never tried with wires.

**Comment by sthegreat** [comment]
I've used a shutter with a machine controller on cables in the past and it works properly, even visually disconnects the wires for you. Put the shutter on the face you want to turn on/off and put the controller on the same wire block and on the face you want to send the redstone signal.

**Comment by Prometheus0000** [comment]
Is one of these three the right way? None of them work though?
![2020-03-10_18 11 26](https://user-images.githubusercontent.com/8517039/76364064-b5395180-62fa-11ea-901f-b79300f3131f.png)

**Comment by sthegreat** [comment]
The middle one with the electrum pipe should be right. Try screwdrivering the shutter and/or controller covers to try to configure them properly. If it still doesn't work, try moving the controller to the side instead of the top because I'm 100% sure it worked for me in that configuration.

**Comment by Prometheus0000** [comment]
No-go. I'm gonna say they're broken. Can anyone else try?

**Comment by sthegreat** [comment]
![](https://i.imgur.com/mPgtvoB.png)

Just doesn't seem to display the on/off visually anymore for some reason. Energy flow is properly turned on and off.

**Comment by mitchej123** [comment]
Pipes/wires do not visibly disconnect anymore; however the shutters do work.

**Comment by Prometheus0000** [comment]
Can confirm, but that's very confusing.

**Comment by mitchej123** [comment]
It's unavoidable without either a visual hack, or forcing the wire to disconnect.  But once it's disconnected it doesn't automatically reconnect.  If someone wants to submit a PR to add a texture overlay when it's disabled feel free.

**Comment by richardhendricks** [comment]
Let's do a separate issue for adding a visual indicator. Should be easy to change to an X or something else on the shutter cover.

**Comment by YannickMG** [comment]
Shutters do work now, so I believe this no longer needs fixing.
