### ISSUE TITLE
Missing recipe on MP : Casting Form (Coinage Mold)

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#5723]
#### Which modpack version are you using?
.8.5dev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
ive tried to make coinage mold for Doge coins , Everglades...
#
#### What happened instead? (Attach screenshots if needed)
No recipe for casting form coinage mold
#
#### What do you suggest instead/what changes do you propose?
Add that recipe please

**Comment by Prometheus0000** [comment]
The recipe's there for me? SP and same ver. Can you see the recipe for both/either of the 'Casting Form (Coinage Mold)' that you make the 'Mold (Coinage)' out of? Did you try in SP? Maybe the server's script is outdated.

**Comment by Dream-Master** [comment]
This is a very old bug but it should be fixed. need to check

**Comment by ScriptedPiky** [comment]
It doesn't work on MP for some reason. Apparently, it works on SP, but NEVER on MP. Is there some kind of bug involved with MP scripts or another mod confliction? Possibly we could just move the script from MineTweaker (presumably) to the GTNH core.

**Comment by Dream-Master** [comment]
maybe it's blacklisted to avoid you to make Chunckloader coins idk

**Comment by ScriptedPiky** [comment]
Chunkloader coin recipes are actually disabled on Zeta, so maybe but I wouldn't know unless these recipes are enabled or if some can confirm this on 8.5.dev at least.

**Comment by Prometheus0000** [comment]
Uh, I already said it works on 2.0.8.5.dev SP? How do you even chunkload on Zeta then?

**Comment by Dream-Master** [comment]
you can buy coins form points you collect in jobs as woodcutter miner or other jobs @Prometheus0000

**Comment by Dream-Master** [comment]
@ScriptedPiky
