### ISSUE TITLE
Alveary temperature + adjusting isnt working properly

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#5725]
#### Which modpack version are you using?
.8.5dev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Ive tried to set temperature to Icy in Alveary, so ive added 4, later even 6 alveary fans
![2020-03-09_18 46 12](https://user-images.githubusercontent.com/14223368/76242062-53afaf00-6236-11ea-8d71-47ba03c7ee6e.png) 
 and powered them, but they doesnt work.
#
#### What happened instead? (Attach screenshots if needed)
Temperature dropped to max 2% 
![2020-03-09_18 44 56](https://user-images.githubusercontent.com/14223368/76242109-6924d900-6236-11ea-8fe9-45399f7d6a07.png)
 so ive changed biome to Biome Taiga M, which has -50°F but that Alveary keeps saying 2%(which should be already in Icy range - 0-5%) and Cold. It worked for a moment and dunno why it stayed for only a while at -53%, so my bees were able to produce 1 comb of cryotheum

**Comment by Dream-Master** [comment]
Icy bees from which mod ? @Hyperic88

**Comment by Hyperic88** [comment]
@Dream-Master As far as i know there is only updated version of bees in .8.5dev, but the problem itself isnt in bees, its in alveary. That structure has issues with temperature... nevertheless those Cryotheum bees are labeled "Forestry for minecraft"
![2020-03-10_13 33 40](https://user-images.githubusercontent.com/14223368/76312689-dd618a00-62d3-11ea-858c-e112336c6d12.png)

**Comment by Dream-Master** [comment]
i dont know but have gt++ bees ?

**Comment by Dream-Master** [comment]
All bees are labeld like this

**Comment by Hyperic88** [comment]
Think so, bcs ive connected to Delta while back, and lots of bees were missing /changed... so i guess all of them are now gt++

**Comment by Dream-Master** [comment]
@Hyperic88 ask Alkalus for help if this bees are now gt++ bees

**Comment by Hyperic88** [comment]
@Dream-Master but... its not problem of bees :))

**Comment by Dream-Master** [comment]
Ok so we need to check Forstry code for it?

**Comment by Dream-Master** [comment]
@GTNewHorizons/core @GTNewHorizons/developers 
Need help here

**Comment by Hyperic88** [comment]
> Ok so we need to check Forstry code for it?

looks like it

**Comment by leagris** [comment]
Please analyze this bee, because with unknown genome we can not what other traits it has. Can you please use `/mt hand` on bee and paste it here.
Also some bees have specific biome requirement for breeding that can not be emulated by an alveary. Only an industrial Apiary with proper biome emulation module ca, if required biome is a vanilla. Not sure if the biome requirement also affect product.

Finally, make sure your alveary is not crossing chunk boundaries.

**Comment by Hyperic88** [comment]
> Please analyze this bee, because with unknown genome we can not know what other traits it has or what are the active traits.
> 
> Can you please use `/mt hand` on bee and paste it here.
> 
> Also some bees have specific biome requirement for breeding that can not be emulated by an alveary. Only an industrial Apiary with proper biome emulation module ca, if required biome is a vanilla. Not sure if the biome requirement also affect product.
> 
> Finally, make sure your alveary is not crossing chunk boundaries.

![2020-03-10_18 43 49](https://user-images.githubusercontent.com/14223368/76342670-401c4b00-62ff-11ea-86f8-de825cc5a343.png)
![2020-03-10_18 43 54](https://user-images.githubusercontent.com/14223368/76342680-427ea500-62ff-11ea-92fe-401e3b3f957a.png)
![2020-03-10_18 43 59](https://user-images.githubusercontent.com/14223368/76342682-427ea500-62ff-11ea-9b4c-d53eaca3b905.png)
![2020-03-10_18 44 40](https://user-images.githubusercontent.com/14223368/76342684-43173b80-62ff-11ea-9ccd-3bfd9459187e.png)

@leagris problem itselft isnt with bees, but with alveary structure... as you can see on screenshot its placed within cold taiga M biome with -50°F temperature, but still has only 2% cold

**Comment by draknyte1** [comment]
I don’t add bees, wot. 😂

**Comment by Zeruel13** [comment]
I'm having the same issue. Trying to get void bees to produce their spec. item but the temperature on the alveary maxes out at 7% using 3 fans. Adding more fans doesn't change the temperature making it impossible to get void metal nuggets. 

![image](https://user-images.githubusercontent.com/63512252/130476354-26169072-5a3b-4d6d-a7d1-d8766e3100f8.png)

![image](https://user-images.githubusercontent.com/63512252/130476388-15bd834f-4b96-48ee-9ccf-2186b69a69f8.png)

**Comment by Prometheus0000** [comment]
@D-Cysteine should have fixed this already, try again on the latest version.

**Comment by Prometheus0000** [comment]
Unless this wasn't part of it?

**Comment by Zeruel13** [comment]
I'm on the latest dev version 2.1.1.2. What was fixed was breeding bees by changing climate in the alveary but I still can't seem to make the alveary icy in a normal temperature biome. 

I also can't make the temperature hellish. Seems to cap at 242%

![image](https://user-images.githubusercontent.com/63512252/130478457-254b1ede-82b0-4cee-b5c7-9e3ebb1bb9d5.png)

**Comment by Glease** [comment]
Vanilla forestry limitation. Not sure about the icy condition, but you definitely cannot emulate a hellish biome with alveary. This is by design. Go to nether or use Gendustry indurstrial alveary with hell upgrade.

**Comment by Prometheus0000** [comment]
Is it a limitation by a hard cap, or because you can't fit enough fans in? Because if it's the latter, that's not our problem, but we could change the first if we wanted I guess?

Personally, I'd say just go to a close biome and change that, or, y'know, follow the biome changing quests I made and change the biome in a small area. That's exactly why those quests are there.

**Comment by Glease** [comment]
For hellish it's a hard cap, and I strongly oppose anyone to remove it. All bees with hellish biome req has an unusually high mutation rate just for this reason. All base forestry bees are pretty well balanced and I don't see why would we ever need to change that.

**Comment by Prometheus0000** [comment]
Fine with me. I guess this can be closed then?

**Comment by Zeruel13** [comment]
Is the intention for Icy as well to be only obtainable in a biome with icy temperature? The original issue was using fans in biome that was already very cold. Just want to make sure.

**Comment by D-Cysteine** [comment]
I haven't actually done much with the alveary myself, but looking at the wiki, it sounds like the icy limitation comes from vanilla Forestry: https://ftbwiki.org/Alveary_Fan (see section "Limitations"). It also sounds like the limitations are per-dimension, and icy is achievable in the nether, for some reason.

**Comment by Waisse** [comment]
I'm having the same issue with the alveary. The apiary I placed on top to check shows icy/arid, whereas the alveary only shows cold/arid, which is leaving me quite perplexed and frustrated. The biome is called rwg_snowForest and is covering the entirety of the 3x3 multiblock and  is also located on the same chunk etc.

**Comment by Waisse** [comment]
![image](https://user-images.githubusercontent.com/9310630/174794889-080005c4-4e33-463a-a310-9181616c9d8d.png)
![image](https://user-images.githubusercontent.com/9310630/174794943-b1c46d31-b1f8-4049-8f4f-1d2eb0f013ed.png)

**Comment by MrWye** [comment]
If i am not mistaken, alveary was not designed to simulate Icy temperature/biomes, fan only reduces the temperature to various amounts of cold depending on the amount of fans.  On the other hand, hellish (Nether) is actually suppose to be simulated by using Alveary Stimulator with proper circuit and blazing tube embedded. Unfortunately it needs fixing, because nether is not being simulated and i have opened an issue already. Having same kind of mechanic usable with Electrical Stimulator would probably be a nice addition to simulate Icy Biome. But then again, i believe Industrial Apiaries are capable of those simulations and various modification, so perhaps it is intentionally gated
