### ISSUE TITLE
Diodes do not work with Machine Controllers

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5726]
#### Which modpack version are you using?
2.0.8.5dev
#
Same as #5719, but with Diodes, see https://github.com/bartimaeusnek/bartworks/issues/54 for main issue.

**Comment by Dream-Master** [comment]
@Prometheus0000 did you try with BArtworks 5.0.12 ? from 2.0.8.6dev

**Comment by Prometheus0000** [comment]
I'll try it later

**Comment by Prometheus0000** [comment]
Both still don't work.

**Comment by Dream-Master** [comment]
Need to tested first and fixed in a later version
