### ISSUE TITLE
Bug in quest "crop automatic"

### ISSUE THREAD

**Issue by skushnarev** [GTNewHorizons/GT-New-Horizons-Modpack#5730]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
No
#
#### What did you try to do, and what did you expect to happen?
It is not possible to complete the quest "crop automatic".
#
#### What happened instead? (Attach screenshots if needed)
The book does not see the electric motor
#
#### What do you suggest instead/what changes do you propose?
Helped getting an electric motor out of creative mode

**Comment by Prometheus0000** [comment]
The quest crop automation (use the correct name next time) already has NBT ignore on. Try again with a newer version, it worked when I tested it. Also try using a name remover in the future.
