### ISSUE TITLE
Shutter Module Cover requested changes

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5733]
#### Which modpack version are you using?
2.0.8.5dev
#
As mentioned in #5719, there's currently no visual indicator of whether fluid/item pipes or cables/wires are connected or disconnected when using a shutter cover. It would be nice (and less confusing) if there was.

Additionally:
1) It would be nice if it said on the tooltip that it works on pipes/cables
2) A quest to explain how to use them, probably right next to the overflow cover one in LV
3) ~~Quests for the other covers if there aren't ones (or a combined one)~~ Done
#

**Comment by richardhendricks** [comment]
@mitchej123 Is it possible to integrate this into WAILA as well? Or would that not work since it is a cover?

**Comment by mitchej123** [comment]
The cover sets block.can_work -- same for cables as it is for machines.  Covers are a bit of a pain; but just looking at the state could be added on WAILA (it might already be since I think I include Enabled/Disabled, but not sure)
