### ISSUE TITLE
Simple hand pump shift-right click fill voids fluid

### ISSUE THREAD

**Issue by tungstensteelwrench** [GTNewHorizons/GT-New-Horizons-Modpack#5758]
#### Which modpack version are you using?

# 2.0.8.7
#### If in multiplayer; On which server does this happen? 

# Single player
#### What did you try to do, and what did you expect to happen?

# There was 10 buckets of Nitrogen gas in a BC Tank, I shift-right click the tank with an empty first tier simple hand pump. So there should be 2 buckets of N in the hand pump, and 8 buckets of N in the tank.
#### What happened instead? (Attach screenshots if needed)

# First tier simple hand pump(2000mB) filled itself 2 buckets, but voided 1 bucket of gas from the tank.

**Comment by Dream-Master** [comment]
@tungstensteelwrench please report here
https://github.com/alkcorp/GTplusplus
Thanks

**Comment by draknyte1** [comment]
Fixed in Dev.
