### ISSUE TITLE
A more realistic way to get aluminum

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#5763]
#### Which modpack version are you using?
2.8.0.6

#### What do you suggest instead/what changes do you propose?
Using electric blast furnace to smelt aluminum whose melting point is only 933K is quite ridiculous.Even if you say aluminum can avoid being oxidized in electric blast furnace with shielding gas,it still takes too much time and energy to smelt.
The most time and energy consuming procedure should be the electrolysis of alumina.
## My suggestions are:
Disable the directly electrolyze of aluminous compound to get aluminum dust.
Alumina can be gained from aluminous compound.
Use Na or K to reduce Alumina to get aluminum dust in LV tier.(make sure it will consume more energy than the regular way)
Alumina electrolysis will available in MV tire,use cryolite to save energy.
Cryolite can be made in HV Chemical Reactor.
Aluminum dust shuold be smelted in electric blast furnace with shielding gas,and the time of smelting shouldn't over 5s

**Comment by 0lafe** [comment]
This sounds fun

**Comment by Anarack** [comment]
Personally, I don't like this as the ebf alone is enough imo.

Can salt be broken down to Na/K in lv?
How is cryolite made other than HV chemical reactor. its a mineral normally I thought so not sure how you would make it.
what is the energy consumption going to be like as it will be very very slow to match current values of power for aluminium with just lv machines. aka 220 seconds per ingot slow to match gas smelting.

Other changes that would be needed off the top of my head.
-  tinkers casts/alloys/gravel ore changes
- washing/thermal/maceration recipes for a large number of ores needed to be looked at for pure aluminum dust
- gem cooking
- magnalium becomes annoying in lv, not sure if intended.

**Comment by GlodBlock** [comment]
@Anarack 
- Salt can  be broken down to Na and Cl in lv
- Cryolite(Na3AlF6) is kind of mineral,but the biggest vein of cryolite has been used up in 1987.So the most common way to get cryolite is artificial synthesize.
6HF+Al(OH)3===H3AlF6+3H2O
2H3AlF6+3Na2CO3===2Na3AlF6+3CO2+3H2O
- Pre Al ingot cost 144000 eu with N2 in current recipe.Pre Na/K dust cost 9600 eu by electrolyzing salt.So we can use 4 Block of Na/K and 5*Al2O3 to make two aluminum ingots(288000eu) in Alloy Smelter(30eu/t,40s),the total energy is 369600eu.
In fact,before Alumina electrolysis came into existence,the only way to get pure aluminum is to use Na to reduce AlCl3.
- In terms of TiC,just ban the generation of aluminum gravel ore ,aluminum oreberry can be ground into alumina dust or be smelt in tic smelter(to make aluminium brass).

**Comment by GeicowithaBango** [comment]
I think the amount needed for the MV-tier is already enough. this idea seems like overkill to me.

**Comment by draknyte1** [comment]
As it is, I add in an alternative route for process aluminium which yields more.. if you’re unhappy with the yields of the standard way, try that. (Look at Aluminium Pellets)

**Comment by Anarack** [comment]
We can't use ore berries like that, we need far too much. every mold/extruder shape needs it and you need a lot of them in steam/lv. Alumite needs it for the tool forge. ore gravel already exists in large amounts of the servers and wont be removed, so it will only hurt new players. Best would be to change what the ore gives and adjust smeltery recipes/alumite dust recipe.

**Comment by 0lafe** [comment]
Would be nice to take a look at Al gravel with this and possibly change it to give better MV stuff, but it doesn't need to be required. With many Al containing ores existing, we got options for Al isolation, but this would probably just make the process of getting pure Al more intricate while reducing the smelt time to compensate. Seems fun imo

**Comment by Dream-Master** [comment]
@GlodBlock why you close this issue ?

**Comment by Prometheus0000** [comment]
> As it is, I add in an alternative route for process aluminium which yields more.. if you’re unhappy with the yields of the standard way, try that. (Look at Aluminium Pellets)

Maybe they were satisfied with that?
