### ISSUE TITLE
Manual Trafo not forming

### ISSUE THREAD

**Issue by noobnoobnub** [GTNewHorizons/GT-New-Horizons-Modpack#5766]
#### Which modpack version are you using?
2.0.8.6
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Follow the quest
![image](https://user-images.githubusercontent.com/50437615/76935185-9d318580-692b-11ea-9733-e6f96efb312f.png)
9 iv dynamo on top layer
8 transformer winding block on middle while 1 nickel zinc ferrate block in centre
1 controller block on front bottom center + 1 maintainance on the bottom corner 
Rest of the bottom are ev energy hatch
#
#### What happened instead? (Attach screenshots if needed)
![1](https://user-images.githubusercontent.com/50437615/76935155-8e4ad300-692b-11ea-9232-311d80080fd7.png)

#

**Comment by noobnoobnub** [comment]
It need muffler hatch where the quest doesnt mention it need one

**Comment by wlhlm** [comment]
I think this should be put in the quest, thus reopening.

**Comment by ahmetsad** [comment]
What does muffler do at a trafo. Does electrons transform into gases?

**Comment by Dream-Master** [comment]
All Multiblocks need a muffler so far ik. Maybe make no sense and we need to make a code change

**Comment by ahmetsad** [comment]
Vacuum freezer doesn't need muffler

**Comment by Dream-Master** [comment]
ok so a code change needed

**Comment by Dream-Master** [comment]
Is this traffo a gt code block or another mods block labels as gt

**Comment by boubou19** [comment]
iirc it's from bartworks

**Comment by DerMilchkarton** [comment]
![grafik](https://user-images.githubusercontent.com/36045340/79151333-87986a00-7dca-11ea-8828-758b372f6f70.png)

![grafik](https://user-images.githubusercontent.com/36045340/79151388-9da62a80-7dca-11ea-99bb-ecfc3f1e7d9b.png)

Maybe this does help.
Personally i would simply add the requirement to craft 13 ULV Machine Casings to the quest.
