### ISSUE TITLE
ae interface can delete patterns without card

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5768]
#### Which modpack version are you using?
8.7
#
#### If in multiplayer; On which server does this happen? 
mp
#
#### What do you suggest instead/what changes do you propose?
i tried putting a pattern in a pattern slot that gets unlocked with the expansion cards when there where no cards 
when i did the pattern got deleted

**Comment by Houstonruss** [comment]
Removing a pattern capacity card voids extra patterns.

**Comment by repo-alt** [comment]
Just hides them, until you put the card back.

**Comment by leagris** [comment]
Possible options:

- Drop or return the extraneous patterns to the ME network when removing the pattern slots upgrade.
- Prevent removal of the pattern slots upgrade until the extra pattern slots are empty.
