### ISSUE TITLE
Default World Generator doesn't allow changing superflat world preset

### ISSUE THREAD

**Issue by wlhlm** [GTNewHorizons/GT-New-Horizons-Modpack#5770]
#### Which modpack version are you using?

2.0.8.7

#### If in multiplayer; On which server does this happen? 

Singeplayer

#### What did you try to do, and what did you expect to happen?

Create a superflat creative world for testing various things for survival play. I prefer to use the the "Desert" preset instead of the default "Classic Flat". Normally, GTNH includes which locks woldgen options to RWG currently. To be able change world preset, I have to set `B:"Lock World Generator"` to `false` in `defaultworldgenerator.cfg`.

#### What happened instead? (Attach screenshots if needed)

When changing superflat preset, the worldgen is reset to RWG. You can use superflat as as worldgen as long as you don't change the preset. Changing the preset opens up another menu and I suspect when going back to "Create New World" screen the mod just resets worldgen to the configured default option.

#### What do you suggest instead/what changes do you propose?

Make Default World Generator check from which menu the player came before setting the default worldgen.

**Comment by Dream-Master** [comment]
I disable this because to many player load vanilla terrain and have big mushroom terrains and complain about it. If there is an option to allow only flat and rwg I am ok with

**Comment by wlhlm** [comment]
I understand. But even when manually changing the config option to not lock the worldgen, you still can't change superflat preset.

I'm not advocating lifting the lock. Rather this is a bug in Default World Generator. The only workaround is to remove the mod (which sucks when updating the pack).

**Comment by Dream-Master** [comment]
never test it. Maybe we need to fork it

**Comment by boubou19** [comment]
another workaround is to create a map, then change the world gen type in the level.dat, delete all the region files, then launch the map again

**Comment by GTNH-Colen** [comment]
If you need a superflat testing world just spawn in a garden portal and use that, it's not ideal but works in the meantime.
