### ISSUE TITLE
Nanosuit wrong tooltip.

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#5772]
#### Which modpack version are you using?
2.0.8.7

Nanosuit tooltip says 'Provides full hazmat protection' but it doesn't.
Doesn't protect from radiation or doesn't protect from hot/cold pipes.

![2020-03-19_20 11 40](https://user-images.githubusercontent.com/36479271/77101409-eebb3c80-6a1f-11ea-9903-a72f89dc0f51.png)

Either change the tooltip or add full hazmat protection.

**Comment by draknyte1** [comment]
Please report here. 
https://github.com/alkcorp/GTplusplus/issues

**Comment by Impos913** [comment]
https://github.com/alkcorp/GTplusplus/issues/657

**Comment by Prometheus0000** [comment]
This appears to work now+alk's repo says so.
