### ISSUE TITLE
UU and lategame issues

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5775]
#### Which modpack version are you using?
2.0.8.7

#### What do you suggest instead/what changes do you propose?

Seems like uu for the most part is a system build upon power gen stopping around IV. Many LuV+ things become easy enough to uu, that it's simpler, easier, and or cheaper to just uu instead of using another production route. 

A big impact here is on fusion based production of materials. Eu, Am, Tn, Rn, and Fl are all faster to be made by uu than fusion, by a fairly wide margin. It varies between them, but all are better, with some being 12x+ faster from uu when using just He plasma. 

This is a problem for a few reasons. It means that most fusion recipes are primarily useful for a 1 time recipe, then using that dust for replication. Now even if the uu was a little worse, it would still probably beat the reactor setup, as reactors aren't cheap. Being able to use uu instead of a reactor for even a 2x slower rate can often be beneficial, as you usually won't need to run these reactors 24/7 for material production, so a power reactor can cover the rates needed through uu, and still give a net output of power. 

For this reason, I'd suggest removing fusion based production uu, and instead push it into tech tech. UU in general is meant more as an option for dumping power in, and getting worse yield than any other option. These become quite good, as uu scaling is based on that power input being lower than we allow it to be. We could simply up the power/time on the replication, or increase uu cost. This would move the uu mentality into a spot that fits needing to use fusion first, then being able to use uu once you're a bit past that reactor tier, and the power input is less of a concern. It would still be less efficient, but it would mean you need less reactors, which does win out at a certain point of power production. However, this seems like a lazy way of accomplishing this goal. While it would push the power req into later tiers, it doesn't do much about the rest of uu being based mostly on lower tier machines, and being overall a fairly simplistic pre LuV process. Moving the uu type production of circumventing the reactor with extreme power into the tiers of being able to produce that power. Using some type of particle shits in TT seems to fit post fusion production better than something that's technically open to you from LV, and sees some heavy use cases pre fusion. 

This might apply to Cf as well as some ++ things, but idek if those have uses so I didn't focus on those too much. If we do wish to keep uu for these, I'd recommend a 256x power increase applied to these recipes replication process. Putting uu ~20x worse than using a reactor. This would probably make Eu uu have some use late UV, while the rest we don't really have enough power gen to reach the levels of uu surpassing fusion. 

![image](https://user-images.githubusercontent.com/21280852/77131598-7b6ef600-6a32-11ea-80ea-041d49e3cc87.png)
These are rate comparisons from using the same tier of reactor for mat gen compared to He plasma power into uu. This takes into account the uu production being fit into a single PA, so thing's will be overclocked. Some values are higher, such as the case of Tn, in which I only compared it to a single Mk2 doing uu, while Tn needs 2 reactors. Also doesn't account for the power of production of the inputs for the fusion materials, which would also boost UU to being even better in comparison.

**Comment by chochem** [comment]
I am pretty sure that the entire process of -only making one dust the hard way and then having uum- is intentional design and not something that needs fixing.
Sounds like something you should implement in the -often discussed but still not existing- 0lafecraft.

**Comment by Dream-Master** [comment]
Yea uu need a change.

**Comment by quedral** [comment]
maybe disabling/increasing power usage of UUM on fusion materials like Europium Americium..ect is not bad however if you start to nerf other rare dusts like Indium/Yttrium then you WILL hinder the progression of lower tier greatly so for the sake of the general population(which are not even close ton UV tier) i strongly disagree with the changes.

**Comment by GTNH-Colen** [comment]
Discouraging UUM creation of americium and europium seems alright but no one seems to actually bother with this method (Although you can get europium fairly cheap energy wise by just macerating vega B stone so take that as you will). But I agree that other materials such as indium should be left alone as they are annoying enough to obtain in large quantities.

Another thing to consider is time, you need a lot of americium/europium for higher tiers and to replicate that amount takes a very long time compared to the fusion reactor. The numbers shown below is with an LV replicator so you can obviously overclock it multiple times to decrease the time needed but it illustrates the point.

3865s/Europium dust via UUM
14.4s/Europium via Fusion

6272s/Americium dust via UUM
43.2s/Americium via Fusion

**Comment by 0lafe** [comment]
>maybe disabling/increasing power usage of UUM on fusion materials like Europium Americium..ect is not bad however if you start to nerf other rare dusts like Indium/Yttrium then you WILL hinder the progression of lower tier greatly so for the sake of the general population(which are not even close to UV tier) i strongly disagree with the changes.

Literally only talking about the 5 elements I brought up 

Another thing to consider is time, you need a lot of americium/europium for higher tiers and to replicate that amount takes a very long time compared to the fusion reactor. The numbers shown below is with an LV replicator so you can obviously overclock it multiple times to decrease the time needed but it illustrates the point.

3865s/Europium dust via UUM
14.4s/Europium via Fusion

6272s/Americium dust via UUM
43.2s/Americium via Fusion

Did you read the thread? The point is it doesn't take a long time compared to fusion, it's actually significantly faster if you use fusion for power instead. Vega b Eu doesn't matter too much if it's better. That's like T+2 iirc if Eu is zpm

**Comment by 0lafe** [comment]
Aight so putting some values down. Gonna separate Rn/Os/W from the fusion gated materials, as these have fusion changes in addition to uu. These are materials used pre fusion, and for Rn/W fusion needs to compete with a lot more than uu. 

W is the worst fusion for the most part. While only loosing to uu by around 8x, it's a lot worse than other W gen. I recommend leaving uu as it is, and reducing fusion power cost. Lowering starting power from 200M to 100M makes the recipe mk1. Changing time to 1s and increasing inputs to 144L brings the recipe to 1s Mk1. This is about 2x as power eff as W UU. 

Rn is a bit higher tier than W, and exists as a semi expensive plasma. Currently the plasma is useless for power gen, and the Rn output is not just significantly worse than UU, but much much worse than LCRing. Post quarry U becomes less of a bottleneck, and with LCR OCing Rn outputs get very high. Rn uu is currently cheaper than U238 uuing, making LCR uu production completely useless. For these reasons I recommend changing Rn replication to 480v from 30v, and increasing the uu to 1000L. On the reactor side, i recommend lowering Rn starting power to 300M, changing the running voltage to 60000v, lowering the time to 20 ticks. This makes Rn plasma semi power viable, despite not being incredibly reliable with inputs being F and Ir. The plasma from 1 reactor would beat He by about 1.5x but I think looses to tin. Would also make Rn plasma better than Rn uu, while being worse than U238 uu LCRing. 

Os is pretty useless in fusion atm, but the uu is quite fast. Os isn't a big element until ZPM+, but uu gives it in quite large quantities. I recommend changing the Os replicator recipe to 1920v and increasing the UU to 1900L. Then change the Os reactor recipe to 40000v, the inputs and outputs being 144L, and lowering the time to 10s. This makes fusion quite a bit better than uu, while gating Os to an mk2, and making Os generation pre zpm more ore based. 


Now for the fusion elements of Eu, Am, Tn and Fl, I still support removal of uu for. However, if they need to stay, a recipe that gives value to them, but gates it to tiers past initial creation, I have these values for new replicator recipes. As these are fusion only elements for the most part, I'm leaving their fusion output as is. 

Eu: 4000L 7680v current time
Am: 18000L, 7680v, 4x current time
Tn: 40000L, 7680v, current time
Fl: 36000L, 7680v, current time

This makes all worse than fusion, encouraging Fusion gen for tiers near initial generation.
