### ISSUE TITLE
Os UU and bees

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5776]
#### Which modpack version are you using?
2.,0.8.7

#### What do you suggest instead/what changes do you propose?

UUing osmium is cheaper than using bee combs to make Os due to BW ore change on Os ore. Comb production used to make 4x Os dust, but now it makes .2. Id recommend changing the ore output on the comb by 20x to 80 pure Os ore if possible, or something to that extent. Os now gives 20x less Os per ore do to BW proc.

**Comment by chochem** [comment]
this is a bit more tricky. If you just multiply the pure ore by 20 this becomes insanely good for iridium.

**Comment by 0lafe** [comment]
We could have it make 4 Osmium solution from combs instead?
