### ISSUE TITLE
Spice of Life Carrot Edition: Balancing

### ISSUE THREAD

**Issue by wlhlm** [GTNewHorizons/GT-New-Horizons-Modpack#5778]
#### Which modpack version are you using?

2.0.8.7
SOL - Carrot Edition 2.0.0

- - -

Development versions of GTNH feature a backported Spice of Life - Carrot Edition thanks to @mitchej123. The big change this adds is the ability for the player to permanently gain extra hearts the more unique food items they consume. As it is currently implemented, this gives players one heart for every 10 unique food items they consume. This is rather unbalanced compared to, for example Tinker's Construct, which also has a way for the player to gain hearts, but it's significantly harder to gain hearts going this route.

According to Discord chat, there are ~600 food items currently in GTNH.

Suggestions on my part:
- require more food items per heart (for example 20 instead of 10)
- logarithmically scale the number of foods required (similar to how mc levels work)

**Comment by mitchej123** [comment]
I'm open to this discussion, but a few ground rules:

1) I'm not interested in heart comparisons between other mods.  Tinker's hearts are balanced around vanilla and will get re-evaluated in the future once I'm done with SoL

2) I'm also not interested in "that's too many hearts!"

What I am interested in: How much does each heart add to the survivability.  At early game levels, and number of hearts, how much more survivable are the infernal mobs.  Too survivable? Still not survivable enough?  

Ex: A mob does 50% max health damage on each hit -- 10 max hearts, or 60 doesn't make a difference.  General musings on discord seemed that another 5-6 hearts let someone survive one more hit and run away from an Infernal.  

How much (as objectively as possible) more survivable is it with each heart, or row of hearts.  What ages does it matter?  When does it stop mattering?  I'd wager a guess somewhere between IV and LuV the hearts stop mattering completely.  Maybe earlier.

**Comment by GTNH-Colen** [comment]
I don't have much of an opinion on this topic, only thing I will add is that no matter how many hearts you're adding make sure it rounds to a multiple of 10 so people aren't left with ugly health bars if they max it out with every food...

**Comment by 0lafe** [comment]
Hearts in general don't matter too much. We're working on fusion rn and still have red hearts. Most armors cover you well enough it's pretty easy to survive. With pain/agony being changed as well, that makes mobs much easier to survive. I most see this as something helpful around steam/LV. Pre healing axe you could get a lot of hearts by accident, which with shitty armor would have a much larger impact. 

Looking at ability to survive, when you have iron armor equivalent, and you actually take damage, if you have 2 more rows of hearts you can survive quite a bit longer than normal. Most things won't be 1 hitting besides stuff like black widdows/pigment. You'll probably be able to survive about 3x longer if you have 3 heart rows. Armor/enchants/mob type change how many hits you'll endure, but it should be relative to how many you can survive without extra hearts 

Imo you might wanna cap the hearts to 1-2 row additions. Gives a fairly big impact, but isn't as insane as the amount you can get with all the foods. That's still 100-200 foods consumed iirc, so it gives the player something to work for, that will help for a while, and takes a bit of setup.

**Comment by mitchej123** [comment]
I'm fine leaving it uncapped for people who want to min/max.  Most players will probably get 1-2 rows.... a few will get more.

**Comment by mitchej123** [comment]
Rather than capping at 1-2.. I'd probably just scale up the number needed.   something like 10 10 10 20 20 20 30 30 30

**Comment by Houstonruss** [comment]
Easy way to nerf the crap out of this its to make it affect foods over 1/2 shank.

**Comment by mitchej123** [comment]
> Easy way to nerf the crap out of this its to make it affect foods over 1/2 shank.

Clearly that's what we're looking for, instead of you know; thoughtfully considering the balance implications and finding the right trade-offs.

**Comment by EvgenijM86** [comment]
If I were balancing this I would probably leave heart gain as is, but make them a temporary buff instead. Like for 5-10 minutes. And then it clears the food list that you have eaten for that specific heart, and you can eat those foods again to regain that heart for another 5-10 minutes. That limits the amount of extra hearts you can get, and it also adds a desirability to cook a lot of different food in large amounts, instead of only cooking it once for perma heart.

**Comment by Glease** [comment]
That means 1) use high tier food so you don't get hungery soon but never get heart 2) eat morsel and get at best 2 heart for 10 minute at the cost of eating every now and then and the hassle of eating 20 different food every time.

**Comment by EvgenijM86** [comment]
Yes, maybe high tier food should give more points to a temporary heart buff than morsels. And maybe change the buff to 15-20 minutes. Just remember that you can artificially starve yourself, by using a bucket of glue. But the core of that idea is still interesting, as it gives the desirability to cook exotic food more than once.

**Comment by EvgenijM86** [comment]
Or maybe you can achieve the same effect by removing a portion of extra hearts upon death.

**Comment by mitchej123** [comment]
Please address the questions I've asked before we dive into _how_ to adjust it.

> How much does each heart add to the survivability. At early game levels, and number of hearts, how much more survivable are the infernal mobs. Too survivable? Still not survivable enough?

> How much (as objectively as possible) more survivable is it with each heart, or row of hearts. What ages does it matter? When does it stop mattering? I'd wager a guess somewhere between IV and LuV the hearts stop mattering completely. Maybe earlier.

**Comment by EvgenijM86** [comment]
It adds a lot of survivability against early game threats, especially against mobs that poison you. 5 extra hearts can easily be a difference between almost always getting low health debuf after battle with poison monster and rarely getting low health debuf, which is huge, considering how it cripples you. Assuming that you engage in melee. If you just ranged weapon + flying you can cheese almost anything.

**Comment by chochem** [comment]
after playing with this for a bit (though not the early game), I thought I share two more observation:
- the actual number of food is more like 800-900, not 600, I already have 690.
- the large number of hearts is a big buff to early blood magic. self-sacrificial blood magic is much much better now. I consider that a clear positive. Eventually most players want to do a well of suffering automation anyway, but making early blood magic (MV-EV) less grindy and giving it more options (self-sacrifice vs mob farm vs villagers) is a big plus in my opinion.

**Comment by bartimaeusnek** [comment]
Dream requested a config option for:
1. Max hearts
2. How many foods you need to eat per heart

**Comment by Prunebane** [comment]
A couple observations of this change coming into a hoarder's world in Steam age.

- The first row of hearts can be obtained fairly easily by just traveling across a couple different biomes, and getting their respective gardens. (I'm still going through my ingredient chest for not-eaten ingredients)
- food processing = more "uneaten" foods (**Pam's cooking** is more rewarding, and **quest rewards** in the form of small amounts of food also)
- More hearts = higher recovery time. I've noticed that my "hurt-injured-wounded" etc. statuses, including their effects, are spread over a larger margin. Combat is thus a little slower, if fighting poisonous enemies, but that is balanced out with more tankiness.
- Self-observation, I'm not walking around in armor at night when I'm actively hunting mobs in SP. No (or considerably less) lag means I can actually combat mobs in an area around my base. 
- Infernal powerhouses like Lightning and Ghastly are more bearable (lightning doesn't get me to 5 hearts off of two ticks of lightning damage; Ghastly doesn't set me on fire to end up with ~2 hearts). 
  Granted, retribution, alchemist, and regen still mean I retreat to my little bunker to cheese, but over time, I'm getting braver to go out and actually fight them.

Personal feeling, I like the buff, extra hearts from food are definitely nice, but Pam's ingredients in particular seem quite powerful in this regard, for how available they are.

One personal proposition would be, having the actual food value matter in the points gained (say, any 1/2 shank gained = 1 point towards a new heart, and you get a new heart at 50 points). This could work out in favor of nerfing easy, low-tier foods, and promoting the more complicated, high-tier foods.

**Comment by mitchej123** [comment]
Thanks for the recent feedback, this is what I was looking for.

**Comment by KiloJoel** [comment]
I don't know if this is known, but the amount of food required per heart isn't 10 as stated here, it is 50 total hunger points (25 shanks). So it would take 50 morsels for 1 heart, or 2 and a half foods that restore a full bar.

**Comment by mitchej123** [comment]
It was changed after this ticket, it's quite stale.

**Comment by DrParadox7** [comment]
This is covered in https://github.com/GTNewHorizons/SpiceOfLife/pull/32

**Comment by chochem** [comment]
this ticket is very old and not relevant anymore as far as I can tell. It was resolved here https://github.com/GTNewHorizons/SpiceOfLife/pull/12
