### ISSUE TITLE
assline gets stuck at 0 seconds until server restart due to advanced data hatch

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5779]
#### Which modpack version are you using?
8.7
#
#### If in multiplayer; On which server does this happen? 
mp
#
#### What did you try to do, and what did you expect to happen?
make luv conveyor
#
#### What happened instead? (Attach screenshots if needed)
assline is stuck at 0 seconds progresion until the server gets restarted
it also does not consume power 
#

**Comment by botn365** [comment]
when it is stuck at 0 seconds the data hatch is still inective but when the assline works like normal it is active

**Comment by Dream-Master** [comment]
@bartimaeusnek @mitchej123 @richardhendricks @Technus any idea ?

**Comment by chochem** [comment]
I have had the same issue (2.0.9.0 beta2). From my experience it seems to be a problem with the advanced data hatch (the 16 slot hatch). I cant use the assembly line at all with the advanced data hatch, it just gets stuck at 0 progress. But everything works fine if I use the normal (4slot) data access hatch.

**Comment by botn365** [comment]
![afbeelding](https://user-images.githubusercontent.com/42187820/82386246-38320300-9a34-11ea-8949-2f997bb89f0c.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek @mitchej123  @repo-alt @Technus  any idea?
