### ISSUE TITLE
Renamed items came out from the auto miner

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#5783]
#### Which modpack version are you using?
delta
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I use auto miner and i want ores
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/77219509-79f81780-6b71-11ea-91c5-a6d0fc53308a.png)
![image](https://user-images.githubusercontent.com/59776356/77219512-7e243500-6b71-11ea-82ee-64239870859b.png)

#

**Comment by mitchej123** [comment]
throw it into a name remover

**Comment by leagris** [comment]
@mitchej123 This is a serious bug if the Miner can't produce correct output. It probably needs a bit more love and consideration than suggesting player work-around with the name remover.

**Comment by Dream-Master** [comment]
@richardhendricks

**Comment by mitchej123** [comment]
> @mitchej123 This is a serious bug if the Miner can't produce correct output. It probably needs a bit more love and consideration than suggesting player work-around with the name remover.

As soon as someone provides a bug report with exactly how to reproduce the bug I'll get on it.  Until then the name remover works around the bug.  Fairly certain tec and others have looked at this before with no luck.

Happy for anyone else to take a look and find the cause.

**Comment by repo-alt** [comment]
It may be not even a miner but a worldgen e.g.

**Comment by mitchej123** [comment]
It doesn't cause a crash, it's able to be recovered from.  Not a high priority to track down imho.

**Comment by leagris** [comment]
@ Eason134HK can you paste here in a code block, the output of `/mt hand` when holding one of these badly named crushed ores?

I'd also suggest you archive or delete the `gregtech.lang` file, so it can be re-generated at startup.

**Comment by boubou19** [comment]
we don't have access to mt commands on live servers

**Comment by Prometheus0000** [comment]
Is this still happening?
