### ISSUE TITLE
oil drill retreats pipes whent there is plenty of oil left

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5788]
#### Which modpack version are you using?
8.7
#
#### If in multiplayer; On which server does this happen? 
mp
#
#### What do you suggest instead/what changes do you propose?
i got a T2 drill stil driling around 2000L oil/sycle but when it reaches bedrock it pulls back the pipes

**Comment by Dream-Master** [comment]
@richardhendricks @mitchej123 @Technus @bartimaeusnek any idea?

**Comment by Prometheus0000** [comment]
Was this fixed?
