### ISSUE TITLE
New tiers of Ore Drilling plant

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#5799]
Now in game is existing only 3 tiers of ore drilling plant. Why not more?

I suggest adding 3 more. For LuV, ZPM and UV levels.
Reasons:
1) Small ore on planets
2) sometimes we are need for a large ammount of resources right now, and it’s easier to put a miner on the planet than to wait until they are mined in deep dark.
3) gameplay expansion

Recepie:
LuV Ore drilling plant:
controller: 2 ZPM circuit, 3 Electrical motor ZPM, 3 Trinium Naquadah alloy frame box
Frames: Naquadah Frame box
Solid casings: Naquadah Machine casings (Simmiliar as Tungsteel)

ZPM Ore drilling plant:
controller: 2 UV circuit, 3 Electrical motor UV, 3 Black Plutonium frame box
Frames: Iridium Frame box
Solid casings: Iridium Machine casings (Simmiliar as Tungsteel)

UV Ore drilling plant:
controller: 2 UHV circuit, 3 Electrical motor UHV, 3 Neutronium frame box
Frames: Osmium Frame box
Solid casings: Osmium Machine casings (Simmiliar as Tungsteel)

**Comment by Dream-Master** [comment]
If the recipe follow the logic way you need uv circuits in LUV uhv in zpm and so on.

**Comment by Dream-Master** [comment]
Trinium Naq is a gt++ material which i dont use in GT.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/113dc732b2d25c3ed302bf6ee4c673a49405fc6b

Materials need a change maybe and not sure if thi is blanced. Need more input here

**Comment by Retster** [comment]
> If the recipe follow the logic way you need uv circuits in LUV uhv in zpm and so on.

Sure you right, my mistake. it's need luv circuits. Instead of ZPM, also for for frames material in LuV Ore drilling plant may be more reasonable to use plutonium 241 or so. 
I myself am not sure how much this is balanced, since I myself play only on the ZMP tier/
Need more feedback. Cheers.

**Comment by Dream-Master** [comment]
No UV circuits in LUV.

**Comment by 0lafe** [comment]
We have 4 drill tiers, T2 is LuV and T3 is zpm though?

**Comment by Dream-Master** [comment]
we have 4 yes mv to iv so far i see

**Comment by Dream-Master** [comment]
i add luv and zpm but bart mean better do it from Bartworks side

**Comment by botn365** [comment]
the curren ore drills are from EV to ZPM so the next tiers should be UV and UHV

**Comment by 0lafe** [comment]
if the void miner is UV it seems like that's kind of the end of normal drilling

**Comment by Dream-Master** [comment]
if the void miner close this gap we not have to expand ore drilles sure

**Comment by Dream-Master** [comment]
we have 3 void miner tiers now.
