### ISSUE TITLE
replicator bug in 8.8

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#5802]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
sp
#
####

my (EV) replicator got completely messed up in 8.8. (I just updated from 8.6QF)
1. it does not accept uu-matter input from any side or any method
2. if the attempted input is done with a translocator, the uum is still not put in, but even worse, it is duped in the source tank even beyond the limits of the tank and quite quickly (the speed of the translocator)
3. it also keeps its uum-inventory when broken.

running it through a name remover cleared the inventory, after which it accepts uum up to only 403L, but behaves normally otherwise (so no duping anymore). however 403 would not be sufficient for all recipes.

**Comment by Dream-Master** [comment]
We dont change anythings on replicators for years so far ik. Why that never was repoted or was this broken allready before 2.0.8.6 ?

**Comment by chochem** [comment]
was fine in 8.6.  hmm, maybe something just went randomly wrong in the update process. I did a clean install though. I guess the question is if anybody else has the same issues.

**Comment by chochem** [comment]
cheated in a new replicator: no duping, accepts input, but is still stuck at a maximum of 403L uum.

**Comment by chochem** [comment]
sampsa has had at least some if these issues as well (see discord), so its not just me. Though his IV replicator is stuck at 768L.

**Comment by Dream-Master** [comment]
@bartimaeusnek i remeber you change some recipe map size. Have this to do with this bug ?
Or any other idea?
@mitchej123 @richardhendricks @Technus

**Comment by chochem** [comment]
further testing update. tried all the different replicators from lv to luv: all stuck at 403L. started a new world: still stuck at 403L.

**Comment by chochem** [comment]
further update from discord discussions: checking in on my replicator later on revealed it is now stuck at 768L, too (like Sampsa's). Furthermore three other people have now tried to replicate the issue and were not able too. None of them had a replicator when updating though, maybe that made the difference. No idea whats going on.

**Comment by mitchej123** [comment]
Try this version: 
http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/lastBuild/artifact/build/libs/gregtech-5.09.33.34.jar

**Comment by chochem** [comment]
seems to be working correctly. :)
