### ISSUE TITLE
InGameInfo XML Integrations

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT-New-Horizons-Modpack#5803]
```
> Configure project :
Building without BloodMagic...
Building without SimplyJetpacks...
Building without TerraFirmaCraft...
Building without Thaumcraft...
```

BloodMagic & Thaumcraft dev files should be added to the build script to be pulled in at compile time.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/77360439-a5375e00-6d4d-11ea-84e5-fa3dd2745a0d.png)
i build it with this mods

**Comment by Dream-Master** [comment]
@seitenca you build it without. I update your jars and put the libs in folder

**Comment by mitchej123** [comment]
We should update the build.gradle to automatically pull those in -- are they available on the standard lib urls you use dream?  If they are I can update later today.

**Comment by Dream-Master** [comment]
feel free to do so @mitchej123
