### ISSUE TITLE
AE Blocking mode on GT singles 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5806]
#### Which modpack version are you using?
2.0.8.7

#### What do you suggest instead/what changes do you propose?

Blocking mode on AE interfaces doesn't work on GT singleblocks. Ontop of that, interfaces will attempt to push recipes into inventories they can't fit in. For example my compressor will end up with 64 sunnarium despite the recipe being 9 at a time. This caused my last recipe to always fail, as it thinks it put a whole recipe in, when it put 1 sunnarium in. 

Blocking mode doesn't work, so things like mixers can end up with many recipes in them. 

Avoidable with a chest and item logistics, so it doesn't really break much, but it can kind of be annoying earlier on into AE progression.

**Comment by repo-alt** [comment]
Actually after the fix the blocking mode would still be useless, because it will not work if these is a selector circuit in the machine.

**Comment by Dream-Master** [comment]
can you do a new fix @repo-alt ?

**Comment by repo-alt** [comment]
The fix is correct - interface in blocking mode should not push anything in the inventory containing stuff. It is more a GT machine logic problem that some items are considered "special"

**Comment by Dream-Master** [comment]
so any idea how we  an fix that on gt side @repo-alt ?

**Comment by repo-alt** [comment]
Theoretically, there may be some specific inventory wrapper for machine inventories that would say that inventory is empty if there is only selection circuit in it.

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/12
