### ISSUE TITLE
task 237 item ID is incorrect

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/GT-New-Horizons-Modpack#5808]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
Can't make task 237 item , item ID is incorrect thuamcraft:wandcasting
#
#### What do you suggest instead/what changes do you propose?
next version fix

**Comment by Dream-Master** [comment]
Is this a quest issue @AdminXiaoMai ?

**Comment by chochem** [comment]
looks like the wands were changed in one of the last patches. In the past the crafted greatwood wand was id X:9, which is what the quest wants, but now the crafting gives X:30, so its not recognized.

Proposed fix: Change the 'damage' value in the quest from 9 to 30.

I don't know who made this change to the wands or why, but would this also affect other quests?

**Comment by AdminXiaoMai** [comment]
@chochem That's the problem

**Comment by AdminXiaoMai** [comment]
To be precise, the synthetic item ID found by NEI does not match the item ID required by the mission
 this and task ID 798 same.or know how to make the right item please tell me

**Comment by AdminXiaoMai** [comment]
@Dream-Master

**Comment by Dream-Master** [comment]
@timeconquer

**Comment by Dream-Master** [comment]
@timeconqueror
