### ISSUE TITLE
Void miner running at 0eu/T

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#5809]
#### Which modpack version are you using?
GTNH 2.0.8.8
#
#
#### What did you try to do, and what did you expect to happen?
 build the void miner start it, it is running fine BUT it is using 0eu/t, and the scanner says the machine is consumming -524288eu/t
#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ?

**Comment by bartimaeusnek** [comment]
its still in WiP state, will investigate

**Comment by bartimaeusnek** [comment]
it did actually created power bcs of a missing "-"

**Comment by Dream-Master** [comment]
did you push the code allready? @bartimaeusnek
