### ISSUE TITLE
Crash servers & client in the Twilight forest.

### ISSUE THREAD

**Issue by bamik69** [GTNewHorizons/GT-New-Horizons-Modpack#5810]
#### Which modpack version are you using?
2.0.8.7
#
#### If in multiplayer; On which server does this happen? 
On server.
#
#### What did you try to do, and what did you expect to happen?
Crash the server in Twilight forest if the player flies into the territory of the last castle before getting a lamp that burns thorns.

[message.txt](https://github.com/GTNewHorizons/NewHorizons/files/4372842/message.txt)

#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by wlhlm** [comment]
https://github.com/GTNewHorizons/twilightforest/blob/ef2f5c7f655317d3be0588c8bc10c2e4ffcba5ac/src/main/java/twilightforest/structures/lichtower/ComponentTFTowerWing.java#L2184

**Comment by Dream-Master** [comment]
@bamik69 did you play GTNH vanilla or you add more mods to the pack ?

**Comment by DIMONHA** [comment]
I have the same problem, I deleted the infernal mob and added world edit, b aromabackup

**Comment by seitenca** [comment]
https://pastebin.com/7Ts5yae3

**Comment by jss2a98aj** [comment]
Can someone provide a seed and location with an instance of the final dungeon that is causing that crash?

**Comment by Dream-Master** [comment]
@bamik69 @DIMONHA

**Comment by DIMONHA** [comment]
![image](https://user-images.githubusercontent.com/62596299/77639191-084d0e80-6f61-11ea-8827-148b4c78fa04.png)
the seed in the picture, the coordinates of the last castle (x1250 z1550)
![image](https://user-images.githubusercontent.com/62596299/77639393-64b02e00-6f61-11ea-8ddf-514548a2769b.png)

**Comment by jss2a98aj** [comment]
I was not able to replicate the crash on my end, but I think I found and fixed the root cause of it.

**Comment by DIMONHA** [comment]
@jss2a98aj 
and what was the reason?

**Comment by Dream-Master** [comment]
@DIMONHA I build asap a version  for you. Can you test it ?

**Comment by DIMONHA** [comment]
@Dream-Master 
Oh sure

**Comment by Dream-Master** [comment]
@DIMONHA 


[twilightforest-1.7.10-2.3.8.2-dev.zip](https://github.com/GTNewHorizons/NewHorizons/files/4392413/twilightforest-1.7.10-2.3.8.2-dev.zip)

**Comment by jss2a98aj** [comment]
Some of the involved dungeon segments were not using the correct parent constructor. Having looked at later versions of the mod for MC 1.12 it appears to have been fixed there too. The fix resolves some dungeon segments not having a componentType set. I am not certain what the full impact of the bug was, but NBT data for all affected segments was never properly setup.

**Comment by Dream-Master** [comment]
@DIMONHA let me know if it works

**Comment by DIMONHA** [comment]
@Dream-Master did not help
[crash-2020-03-27_11.21.43-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/4392541/crash-2020-03-27_11.21.43-server.txt)

**Comment by DIMONHA** [comment]
![image](https://user-images.githubusercontent.com/62596299/77742455-27aa7100-701f-11ea-9683-3acfa7bc302f.png)

**Comment by Dream-Master** [comment]
@jss2a98aj 
Any idea on this ?

**Comment by bamik69** [comment]
We framed the pure world of Twilight Forest with the same seed. And I left the zone safely. We also use a couple of mods related to GT, but not related to Twilight Forest. Items from these mods were not with you.

**Comment by Larsien973** [comment]
Had a similar crash, with subsequent crashes on reload.
Entered the "Thornlands" without "Lamp of Cinders".
Grabbed the dev build which fixed it for my part.

Logs for completeness:
[Original crash](https://pastebin.com/BNCywtZKl)
[On reload](https://pastebin.com/b1qcJ5w2) (Close to identical)

**Comment by Dream-Master** [comment]
@jss2a98aj any idea here?
