### ISSUE TITLE
Radiation Server Kick

### ISSUE THREAD

**Issue by Houstonruss** [GTNewHorizons/GT-New-Horizons-Modpack#5812]
#### Which modpack version are you using?
2.0.8.7
#
#### If in multiplayer; On which server does this happen? 
ChadNH
#
Radiation from Radium and Naqadria can kick you from multiplayer.
You can't remove the radiation effect with terrawart or milk. The current solution is to kms!

Side note to add hazmat protection to any nano or quantum from EMT

**Comment by draknyte1** [comment]
Hazmat protection requests go to GT++ tracker.

**Comment by GeicowithaBango** [comment]
what does nq+ had to do with gt++?

**Comment by draknyte1** [comment]
I am responsible for making things radiationproof/hazmat. 

> add hazmat protection to any nano or quantum from EMT

Nobody else can do this...
