### ISSUE TITLE
Titanium, Chrome, and Platinum Bee not breedable

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#5816]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
I tried to breed a titanium bee by using redstone and aluminium bees on top of a block of titanium. 

All the bees involved were just freshly obtained along the questline.

#
#### What happened instead? (Attach screenshots if needed)
No success to get even a single gene over more than 300 attempts even though the rate of 5% is not too bad. So rng is not the problem.

Should be easy enough to reproduce.

#
#### What do you suggest instead/what changes do you propose?
fix it. Not sure what the problem is though, maybe the foundational block?

**Comment by chochem** [comment]
Update: The same is true for the Chrome Bee

**Comment by chochem** [comment]
update 2: also the Uranium Bee

**Comment by Dream-Master** [comment]
@bartimaeusnek hope its not the newest change we did to Forestry

**Comment by Dream-Master** [comment]
@chochem 
can you test with foretry https://github.com/GTNewHorizons/ForestryMC/releases/tag/4.2.24.0 and report here?

**Comment by Dream-Master** [comment]
@ElNounch you touche the code first before Bart complete it. Did you have any idea on this ?

**Comment by chochem** [comment]
> 
> @chochem
> can you test with foretry https://github.com/GTNewHorizons/ForestryMC/releases/tag/4.2.24.0 and report here?

@Dream-Master 4.2.24.0 already is the version I am using in GTNH 2.0.8.8.

**Comment by Dream-Master** [comment]
Ok thanks for clarification so the bug is older. @chochem  thanks

**Comment by Dream-Master** [comment]
@chochem can you check with version https://github.com/GTNewHorizons/ForestryMC/releases/tag/4.2.23.0

**Comment by chochem** [comment]
yep, just successfully got titanium on 4.2.23.0

**Comment by Dream-Master** [comment]
@chochem thanks for testing

**Comment by Dream-Master** [comment]
@bartimaeusnek this commit cause it
https://github.com/GTNewHorizons/ForestryMC/commit/d1c17a13b16b4a12bb3c8d0cd3b2fd620e968d15

**Comment by bartimaeusnek** [comment]
fixed with https://github.com/GTNewHorizons/ForestryMC/commit/5db5b712ceb842acf7f6b575092a1bfd1c7c2a34

**Comment by Ngar1** [comment]
Not shure if related to this issue
![Ash_bee_hellish01](https://user-images.githubusercontent.com/7759876/81095967-0c782e80-8f06-11ea-8075-b89e8721eaf1.JPG)
![Ash_bee_hellish02](https://user-images.githubusercontent.com/7759876/81095975-0eda8880-8f06-11ea-8983-54b9eec0be2a.JPG)


I tried to breed (>50 times, forced by accelerator) an ash bee, and no block underneath should be necessary, just nether biome (I made with thaumcraft in OW).
Version 2.0.8.3, MP, myFTB.de

**Comment by chochem** [comment]
if you are on 2.0.8.3, then this is 100% unrelated. the bug in this issue does not exist on 2.0.8.3

**Comment by Ngar1** [comment]
so I should do a separate issue? I didn't find any related.

**Comment by Dream-Master** [comment]
@Ngar1 if there is no issue yes reopen one. Thanks

**Comment by Retster** [comment]
> Not shure if related to this issue
> ![Ash_bee_hellish01](https://user-images.githubusercontent.com/7759876/81095967-0c782e80-8f06-11ea-8075-b89e8721eaf1.JPG)
> ![Ash_bee_hellish02](https://user-images.githubusercontent.com/7759876/81095975-0eda8880-8f06-11ea-8983-54b9eec0be2a.JPG)
> 
> I tried to breed (>50 times, forced by accelerator) an ash bee, and no block underneath should be necessary, just nether biome (I made with thaumcraft in OW).
> Version 2.0.8.3, MP, myFTB.de
Got that bug yesturday in 8.8 even with this fix: https://github.com/GTNewHorizons/ForestryMC/releases/tag/4.2.23.0
Same with all bees that reqire specific climate to mutate (space bee also cannot be breed) i go through this bug with mutatron.
