### ISSUE TITLE
Quantum tank V integer overflow issue

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#5817]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I had a quantum tank V full of oxygen, i opened the gui, shift-clicked on an oxygen cell, the oxygen cell went into the input slot of the tank. I expected that nothing happens because the tank is full.
#
#### What happened instead? (Attach screenshots if needed)
It accepted to empty the cell in the tank, resulting in a fluid amount reset

**Comment by boubou19** [comment]
it behaves normally if you use fluid pipe input tho.

**Comment by Dream-Master** [comment]
@GTNewHorizons/core @GTNewHorizons/developers

**Comment by Alexdoru** [comment]
yeah happened to me right now

**Comment by Prometheus0000** [comment]
Can confirm this happens. It goes to -a lot, then 0.

**Comment by repo-alt** [comment]
Integer overflow. Quantum tank V has capacity of 2^31-8. When you add another 1000, it gets negative. Weird how it was never fixed
