### ISSUE TITLE
LV chemistry quests not marked as main quests

### ISSUE THREAD

**Issue by gordominossi** [GTNewHorizons/GT-New-Horizons-Modpack#5818]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Tried to get to the IV quests 
#
#### What happened instead? (Attach screenshots if needed)
Not all EV quest were open due to LV oil chemistry requirements
![Screenshot from 2020-03-25 11-25-45](https://user-images.githubusercontent.com/18463025/77547029-6b6c7180-6e8b-11ea-9da3-e093a40b93a1.png)

#
#### What do you suggest instead/what changes do you propose?
Mark the oil chemistry quests in LV as main quests
![Screenshot from 2020-03-25 11-24-28](https://user-images.githubusercontent.com/18463025/77546938-4d9f0c80-6e8b-11ea-9de5-19f88c902ead.png)

**Comment by Dream-Master** [comment]
@gordominossi named the quest that need a dependencies. I cant find any.

**Comment by gordominossi** [comment]
@Dream-Master, the Phenol quest on the EV tab depends on the Heavy fuel quest on the LV tab
