### ISSUE TITLE
Malachite block cutting machine recipes have no output

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#5819]
#### Which modpack version are you using?
dev

##### Cutting Machine Recipes have no output:
![image](https://user-images.githubusercontent.com/1111474/77552292-a4b8d780-6eb3-11ea-83e4-f0d522ec4b7c.png)

The possible reason is that, there is no Malachite Plate.

##### Possible fixes:
- Not registering cutting machine recipes (requires GT5U fix)
- Enabling Malachite Plates (requires GT5U config changes)

**Comment by Dream-Master** [comment]
will add.

**Comment by leagris** [comment]
Probably need fix as well. Workbench recipe, malachite block turns to 9 dusts.

A good fix would be to GT5U Cutting Machine, not registering plate cutting if plate does not exist.
