### ISSUE TITLE
Voltages of LuV+ part assline recipes seems off

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5822]
#### Which modpack version are you using?
2.0.8.7

#### What do you suggest instead/what changes do you propose?

Currently recipes for LuV+ parts are at T-1 voltage, which seems off. LuV parts take 6kv, zpm use 24k, and so on. Imo being LuV, they should take LuV, and so on.

**Comment by Anarack** [comment]
Question, can the assline even use more than one energy hatch right now?

**Comment by chochem** [comment]
yes, of course it can take two energy hatches. no way to get going at the beginning otherwise.

**Comment by Dream-Master** [comment]
@0lafe explain a bit what you mean.

**Comment by GTNH-Colen** [comment]
Really don't see the need to change this, there is nothing wrong with the current system other than "0lafe wants to make it harder". I'd be fine with upping the voltage if you also correspondingly lowered the time as the components are in a decent spot time wise atm.

Really don't see how upping the voltage and thus making things take more time is in anyway going to actually improve the gameplay.

**Comment by 0lafe** [comment]
Nah times gotta stay the same. Iirc they used to be 30s T voltage, but got lowered some time recently. Been making a bunch of LuV parts recently. Getting into LuV we ran an IV assline powered off a single HV combustion and it worked perfectly. Kinda made me sad. Had to uptier for T4 plates, but besides those and hatches/dynamos, it's all overclocked IV recipes. Gives us motors and such really fast. Imo needing to run the assline at the tier you want to make parts in, is a good idea. You won't have hatches to start, and will need to overclock. Also it brings the times on the parts closer to being a bit more of something you need to address. 

Most recipes in the assline are pretty fast pre circuits anyway. Doing LuV parts, our assline is almost never running during crafts.

**Comment by 0lafe** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/257
