### ISSUE TITLE
Tesla's Last Testament casings name displayed wrong

### ISSUE THREAD

**Issue by Shuan97** [GTNewHorizons/GT-New-Horizons-Modpack#5824]
#### Which modpack version are you using?
2.0.8.3

#
#### What happened?
Casings name in the tooltip are displayed improperly

![image](https://user-images.githubusercontent.com/35654946/77680104-c7222200-6f93-11ea-90b8-b89709f07a2e.png)
#
#### What do you suggest instead/what changes do you propose?
Fix naming in mod files to be displayed properly

**Comment by draknyte1** [comment]
Already fixed, consider updating.

**Comment by Shuan97** [comment]
Alright, I didn't find related issue, I'm playing on server, we will wait for official recommended version release
