### ISSUE TITLE
Make the clean Room shape more flexable

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#5825]
I would like to be able to make a rectangular one, giant squares or really tall and skinny ones are awkward to build around and makes you just hide the thing.

**Comment by GTNH-Colen** [comment]
I don't think anyone would object to this? Just not totally sure how technically feasible it is, gotta wait on what some devs say I guess.

**Comment by draknyte1** [comment]
You'd still realistically be limited to the size of a single chunk, for the same reasons other multis are.

**Comment by quedral** [comment]
still you are confined in a chunk it doesn't really matter much of the shape imho.
That being said it would be nice to see that generators not working inside of cleanroom though which is more important issue and clearly off topic in this case :D
