### ISSUE TITLE
BW ore small tiering issue

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5827]
#### Which modpack version are you using?
2.0.8.7

#### What do you suggest instead/what changes do you propose?

There seem to be a vein of rarest metal, leach residue, and maybe more I'm unsure of. There also seems to be one of crude rhodium, Arsenopyrite, and other ores I'm unsure of. There's also a third of iridium residue, and possible more i cant see. All these veins start on T3/4 planets, such as ganymede, ceres, callisto, IO and mercury for the Rh mix. As well as Ganymede, IO and mercury for the Rarest metal mix. Then Ganymede, ceres, callisto, IO, and mercury for the Ir mix. 

I suggest removing all the T3/4 planets these spawn on. These are all Pt proc products, primarily aimed at LuV+. With the T5 rocket being LuV, this gives Pt ore skipping potential in early IV. These ores seem like a good option once you need a lot of the materials, however that is much later than they appear.

**Comment by chochem** [comment]
There is so much to unpack here.
1. your tiering is incorrect. they already start before T3/T4.
2. osmium and iridium are both needed in IV. These are not LuV+ materials.
3. as all these components are byproducts of the platinum chain, there is absolutely no point in pushing the small ore to later tiers. Seriously, this makes no sense whatsover. The player already has access to all these raw materials pretty much since LV (but at least HV).
4. Iridium is even available as normal ore in T4, how is the small ore a problem?

**Comment by GeicowithaBango** [comment]
osmium and iridium and needed for hss-s.

**Comment by 0lafe** [comment]
>your tiering is incorrect. they already start before T3/T4.
osmium and iridium are both needed in IV. These are not LuV+ materials.
as all these components are byproducts of the platinum chain, there is absolutely no point in pushing the small ore to later tiers. Seriously, this makes no sense whatsover. The player already has access to all these raw materials pretty much since LV (but at least HV).
Iridium is even available as normal ore in T4, how is the small ore a problem?


1. Aren't those small ores pre T3? I'd put those here too, but I can't check small ore spawns 
2. In small quantities yes, however not in amounts that need a vein of anything more than Pt, which it has
3. I don't mean small ores here. Pushing full veins to T5 gives them very real uses, especially being around the equarry. It'll be much easier to produce these materials. You have access sure, but these reduce power, and increase quantity by a fair bit, before you really start using most of them heavily. 
4. Once again full ore, but that one is more on there because I'm unsure of the full vein. Nei isn't very helpful in showing what spawns with what for the BW veins. 

>osmium and iridium and needed for hss-s.

true, but amounts that fit Pt ore, not ores of the byproducts

**Comment by GeicowithaBango** [comment]
i wouldnt agree to that. rarest metal residue is truly a live safer here.

**Comment by 0lafe** [comment]
You can get more than enough Os for fusion from Pt ore, so I'm unsure what you would need a pure ore for

**Comment by GeicowithaBango** [comment]
do you mean rarest metal residue as pure ore?

**Comment by chochem** [comment]
thanks for clearing up my confusion. I only the words small, ore, and BW in the title, lol.

I still don't see the point. The main restriction for the player is production line, not the raw ore. you seem to be assuming that people would be setting up automations for the osmium/ iridium refinement without also automating the separation process leading there.

Platinum has to be available in large quantities but that automatically also means the others are available too.

**Comment by ScriptedPiky** [comment]
Remember, pure ores **no longer give their pure dusts**. Also, Rarest Metal Residue into Osmium is a 20:1 ratio, in that you would need roughly 20 crushed ore to get a single Osmium dust (excluding the washing, thermal, and crushing products). Removing these ores from pre-T3-4 would be silly, as now the player has to find Rarest Metal Residue from other smaller sources; byproducts of other ores not pertaining to Rarest Metal Residue. You also don't get a lot of RMR from the Platinum ores at all due to the rarity and 20:1 ratio.

**Comment by 0lafe** [comment]
>Remember, pure ores no longer give their pure dusts. Also, Rarest Metal Residue into Osmium is a 20:1 ratio, in that you would need roughly 20 crushed ore to get a single Osmium dust (excluding the washing, thermal, and crushing products). Removing these ores from pre-T3-4 would be silly, as now the player has to find Rarest Metal Residue from other smaller sources; byproducts of other ores not pertaining to Rarest Metal Residue. You also don't get a lot of RMR from the Platinum ores at all due to the rarity and 20:1 ratio.

Yes thats the point lol. You get more than enough from plat ore to cover pre T5 rocket Os usage though so I'm unsure what you mean. 

>I still don't see the point. The main restriction for the player is the production line, not the raw ore. you seem to be assuming that people would be setting up automations for the osmium/ iridium refinement without also automating the separation process leading there.

You would still probably have both, but it would quite drastically decrease the power needed to get the final products, as well as lower the amount of ores needed. Imo both being too low too early, as Rh/Os usage doesn't go up much until post LuV.

**Comment by Prometheus0000** [comment]
Just to be clear, you start getting the small ores of the platinum process from the moon at least. I think I got around 1/2 stack to a stack (combining crushed and impure, and you can't use combs or crops to multiply the crushed) of each from a single HV miner. This seems like too much, considering I don't even use anything other than a little bit of platinum right now.

**Comment by 0lafe** [comment]
Small ores could also do with a change, but this is about non small ores

**Comment by quedral** [comment]
Again unnecessary nerf suggestion by 0lafe  which can hinder the progression of IV or lower tiers. why would it matter to you if someone get few extra plat residue from tier t2/t3 planets?

**Comment by 0lafe** [comment]
Doesn't give Pt residue, and I'm a little unsure what you mean here? Its quite more than a few, and these aren't things that do much to IV- progression.  It means your IV-early LuV Os/Rh will come from PT primarily, which is seemingly the point of the Pt change. You don't really use either of those pre LuV, but you can still get them easily from Pt ores.

**Comment by botn365** [comment]
there wasent iridium ore veins before T4 and no osmium veins before T5 so i dont see why it should now be a thing also with the platinum process you get lots of irirdium and osmium even before the viens

**Comment by Dream-Master** [comment]
BW small and normal ores need to recode/changed in Galagtic greg mod
@bartimaeusnek any idea how long this take to add?

**Comment by Prometheus0000** [comment]
Bart stopped his ores from spawning anywhere other than the two rosses, so this is obselete too
