### ISSUE TITLE
suggest for some awesome cell

### ISSUE THREAD

**Issue by Sakura-sama** [GTNewHorizons/GT-New-Horizons-Modpack#5829]
#### Which modpack version are you using?

#2.0.8.4
now thanks to platinum ores，we need tons of chemical raw materials,like ammonia ,hydrochloric acid,and so on.But we know,the shortest time to get any chemical raw materials by larger chemical reaction kettel is two tick,0.1s.Easy to find it is to slow for these higher tier players,so these player find a new way,using processing array,then we find the difficult comes from the speed of the cell getting full of liquid in the tank,one tick,0.05s.
the plan we are putting into game is getting more tanks to fill empty cells into cells contains liquid.
this plan is awful,but we don't have better plan.
I think we can make a new kinds of cells,like the chips in the circuit assembly machine,we can gain 64 empty cells in assembly machine to make a package cell,it will get 64 bucket of liquid in tank like a stainless steel cell.The coolest thing of this cell is it can disassembly into 64 cells with the liquid in it.I think this item will help us a lot.

**Comment by richardhendricks** [comment]
There already are various large fluid cells available.  I am not sure what you are requesting?

**Comment by 0lafe** [comment]
He's looking for something that can be used as a cell in recipes, that you can fill faster than 1/t from a tank. Empty cells will only fill at 1/t in a tank, and many fluids you will be dealing with in the 10kL/t+ range, which equates to many many tanks simply for filling cells. Large fluid cells can't be used in PAs and split into smaller cells as far as i know

**Comment by Sakura-sama** [comment]
yes，that's what we need,as for drilling oil,we can only use simple a cell,that's to slow for a UV ore miner.

**Comment by 0lafe** [comment]
You can use drums and non item based fluid transfer for drills though. AE/EIO/RIO will all work for supplying a UV miner

**Comment by Anarack** [comment]
...why are you not using stuff like the dim transiver or ender tanks which are close to unlimited throughput.

**Comment by Sakura-sama** [comment]
well.the question is not how to transform drilling oil but only two tank to gain water cell are not enough for a UV miner.

**Comment by Sakura-sama** [comment]
even for platinum ores,like Ru and Rh,get one metal dust needs almost 7 buckets hydrochloric acid,even two large chemical kettels are not enough

**Comment by Dream-Master** [comment]
we have large cells i wont add more cells
