### ISSUE TITLE
Staffs/Staves uncraftable, with 2 recipes for staffters instead

### ISSUE THREAD

**Issue by noobnoobnub** [GTNewHorizons/GT-New-Horizons-Modpack#5830]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/50437615/77781843-37629d80-7091-11ea-92ab-9845ce7cad63.png)
![image](https://user-images.githubusercontent.com/50437615/77781880-45182300-7091-11ea-9ec9-bdf1bbc46e29.png)
![image](https://user-images.githubusercontent.com/50437615/77781886-4a756d80-7091-11ea-90a9-43a5111d6cc1.png)
![image](https://user-images.githubusercontent.com/50437615/77781902-506b4e80-7091-11ea-9a7c-e0cfb82a8801.png)

#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by Prometheus0000** [comment]
It looks like the normal staff recipes have become staffter recipes, with you being unable to craft normal ones anymore, not just for greatwood. This bug also exists in 2.0.8.5dev at least.

**Comment by Impos913** [comment]
Same in 2.0.8.8

**Comment by noobnoobnub** [comment]
so I suppose to get 150 vis wand before tungstensteel screw?
Also I don't know how do i get to higher tier wand after iron capped silverwood scepter because the next wand available is iron capped silverwood staff, or staffter? Which can't be used for crafting.

**Comment by Prometheus0000** [comment]
I think this might be caused by the changes in #5218, by @Zoko061602 or @TimeConqueror. And probably caused the metadata on all the wands to change, borking the quests too.
