### ISSUE TITLE
Rendering GT Machines with BC Tank

### ISSUE THREAD

**Issue by meneken17** [GTNewHorizons/GT-New-Horizons-Modpack#5831]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
Place a BC Tank adjacent to a GT machine fill with any fluid from Tinkers' Construct.
#
#### What happened instead? (Attach screenshots if needed)
The side of the GT machine becomes transparent.
![2020-03-27_19 27 19](https://user-images.githubusercontent.com/8579800/77790452-2e5bd700-7065-11ea-824d-1acea13897cb.png)

#

**Comment by Prometheus0000** [comment]
@leagris Do you care? Can we close this if not?

**Comment by YannickMG** [comment]
I can't  seem to reproduce this now on 2.1.2.0

![image](https://user-images.githubusercontent.com/5321549/147797455-5ea0e4ae-0252-48a9-9b5b-129996191f2e.png)
![image](https://user-images.githubusercontent.com/5321549/147797556-b90d832c-afab-4c23-b2a6-e48420e300f1.png)
