### ISSUE TITLE
well,might a bug for extreme auto craftingtable

### ISSUE THREAD

**Issue by Sakura-sama** [GTNewHorizons/GT-New-Horizons-Modpack#5832]
#### Which modpack version are you using?
2.0.8.4
I,again.
The crafting table will let your product disappear if you make some and in it but don't pick up your product and has no materials for the next one,then if you teleport to other world (might be),then back and put the other materials into the table,the later product will disappear.
Might hard to imagine,if I can share one video here,it would be better to understand what I say.

**Comment by Dream-Master** [comment]
@Sakura-sama better make a video or add pictures here because idk what you mean.
