### ISSUE TITLE
suggestion: change ratio of the electric air filter multiblock

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/GT-New-Horizons-Modpack#5833]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by GeicowithaBango** [comment]
excuse me, I already pressed on „done“ before written anything. however, i think its self explanatory what this issue is about. the ratio of the multi needs imo an significant adjustment (mega buff).

**Comment by Dream-Master** [comment]
if you mean the Air Filter mutliblock this was changed by Tec.
