### ISSUE TITLE
Ore Drilling Plant dig radius is 5x5 chunks

### ISSUE THREAD

**Issue by VasyaOrk** [GTNewHorizons/GT-New-Horizons-Modpack#5836]
#### Which modpack version are you using?
2.0.8.8

#### If in multiplayer; On which server does this happen? 
I run server on same machine, and connect via 127.0.0.1

#### What did you try to do, and what did you expect to happen?
Use Ore Drilling Plant.
Mode : only structure is chunkloaded.
Radius : 48 Blocks
Build in corner of the chink
Before 2.0.8.8 it dig 6x6 chunks.

![structure](https://user-images.githubusercontent.com/11337638/77833531-2aa47f00-714f-11ea-8958-3e09f5fa34bf.png)
#### What happened instead? (Attach screenshots if needed)
Now i see 5x5 chunks, on all miners
![ore map](https://user-images.githubusercontent.com/11337638/77833563-65a6b280-714f-11ea-975f-8270169f30d4.png)
![ore map 2](https://user-images.githubusercontent.com/11337638/77833565-67707600-714f-11ea-8ac7-a26b42ac0b3e.png)

#### What do you suggest instead/what changes do you propose?
It correct ?

**Comment by repo-alt** [comment]
It was indeed 6x6, centered on the miner controller. You can see the old behaviour by turning off chunkloading with a soldering iron. But with chunkloading it makes little sense to track exact miner controller position, especially wit bigger radius. Miner just digs whole chunks.

**Comment by noobnoobnub** [comment]
i have the same issue
is it not able to mine half a chunk when chunkloading is on?
it fits a perfect 5x5 chunk when it is done

**Comment by repo-alt** [comment]
It may be done, but I don't see the point. Maximum size vein is exactly 5x5 chunks.

**Comment by Dream-Master** [comment]
@repo-alt @noobnoobnub what we can do here? Change values or close this issue ?

**Comment by repo-alt** [comment]
I would say close it unless there would be more than 2 players demanding that.
Or we may buff ore drills and make them mine 7x7 at tier one instead. (so that T3 ore drill will be a bit more viable alternative to an ender quarry, given that the void miners are UV+ now)

**Comment by Dream-Master** [comment]
up to you fell free to change or close the issue @repo-alt

**Comment by repo-alt** [comment]
T3 single block miner digs 3x3 chunks, so T1 multiblock being 5x5 is kind of logical. On the other hand I know users do limit higher tiers digging radius with a screwdriver to dig less junk mines, so increasing  T1 drilling area to 7x7 is not much of a buff.  I'll ask in #gihub-discussion for more opinions.

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/81568814-fa373e00-93a6-11ea-91ca-e6952fb43d49.png)
Changed tooltip to be more clear.

**Comment by botn365** [comment]
the avrage vein is 3x3 so with a radius of 6x6 it would mine 4 veins wich is a upgrade to the 1 vein of the HV miner

**Comment by repo-alt** [comment]
May just make it 7x7 then. Tracking half the chunk is a minor pain
