### ISSUE TITLE
melodic capacitor bug 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5838]
#### Which modpack version are you using?
2.0.8.7

#### What do you suggest instead/what changes do you propose?

New EIO capacitor, melodic, does weird things to power input. It seems to be meant to 2x or 4x the input rate of the octadic capacitor, but instead sets all input rates to 180rf/t

**Comment by Dream-Master** [comment]
@Zoko061602 can you check this please? Thanks

**Comment by Dream-Master** [comment]
``
BASIC_CAPACITOR(
      new BasicCapacitor(80, 100000, 20),
      "basicCapacitor"),

  ACTIVATED_CAPACITOR(
      new BasicCapacitor(240, 200000, 60),
      "activatedCapacitor"),

  ENDER_CAPACITOR(
      new BasicCapacitor(400, 500000, 100),
      "enderCapacitor"),
  MELODIC_CAPACITOR(
      new BasicCapacitor(640, 1000000, 180),
      "melodicCapacitor");
``

**Comment by Dream-Master** [comment]
Max energy in, second max energy stored last max energy out.

**Comment by Dream-Master** [comment]
@0lafe can you ckeck?

**Comment by 0lafe** [comment]
The values seem ok, but I'm not sure if that addresses the issue. Melodic here says 180 as one value, which was my issue. Some machines have values of 4k+ with the ender capacitor, but using the melodic reduces it to 180. I'm not sure enough how eio works, but it seems fine in the sag mill, while broken in the sould binder/spawners.

**Comment by Dream-Master** [comment]
what are the values 640 and 1000000?

**Comment by Dream-Master** [comment]
Zoko said it was fixed in newer version.
@0lafe please test with 2.0.9.0. Thanks
