### ISSUE TITLE
#252 Adept Thaumaturgy. Wand not detected

### ISSUE THREAD

**Issue by Ultimoos** [GTNewHorizons/GT-New-Horizons-Modpack#5839]
#### Which modpack version are you using?
2.0.8.6
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
It's wand retrieval quest. I have exact copy of the wand required
#
#### What happened instead? (Attach screenshots if needed)
Nothing happens
#

**Comment by Dream-Master** [comment]
@Ultimoos please try version 2.0.8.8
I fixing a lot of quests.

**Comment by Ultimoos** [comment]
Thanks, we'll update as soon as possible.

**Comment by noobnoobnub** [comment]
tried it in 2.0.8.8
still not detecting even with name remover

**Comment by Dream-Master** [comment]
are Quest reloaded? @noobnoobnub 
/bq_admin default load

**Comment by Prometheus0000** [comment]
252 is not a wand retrieval quest. Use names, numbers, and the tab name.

**Comment by Prometheus0000** [comment]
@Ultimoos Whatever quest you had problems with, are you still having that problem?
