### ISSUE TITLE
BC tanks dupe liquids

### ISSUE THREAD

**Issue by LooseEthics** [GTNewHorizons/GT-New-Horizons-Modpack#5840]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Put a stack of redstone into a fluid extractor and piped it into a bc tank (9216 mb).  Tried to pull it out with the 8k hand pump.
#
#### What happened instead? (Attach screenshots if needed)
Hand pump filled up to 8k mb. The tank, instead of falling to 1216 mb, dropped to 8k, leaving me with 16k mb redstone total. The remaining 8k could be extracted without problem.
#

**Comment by Dream-Master** [comment]
@draknyte1 any idea on this?

**Comment by draknyte1** [comment]
Already fixed in dev.
