### ISSUE TITLE
Found a bug with transformers

### ISSUE THREAD

**Issue by lectorr** [GTNewHorizons/GT-New-Horizons-Modpack#5841]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Found a bug with transformers (all tiers). Repeats in singleplayer and multiplayer. When energy is transferred downward, a large loss of energy occurs. For example. You need to lower 1 amp 32k to 4 amp 8k. With losses in a simple scheme (close to each other), the losses should be no more than 5 EU per tick. However, the real loss is 6554 EU per tick (which is 20%). I observe the problem from 32k to 32 (lv) and on all types of transformers.
#
#### What happened instead? (Attach screenshots if needed)
![unknown](https://user-images.githubusercontent.com/62926823/77993294-88dc8800-7330-11ea-817b-91156aa5e15f.png)
![unknown (1)](https://user-images.githubusercontent.com/62926823/77993306-8da13c00-7330-11ea-928d-ee934eb13627.png)
![unknown (2)](https://user-images.githubusercontent.com/62926823/77993316-91cd5980-7330-11ea-94b0-575ab58779af.png)
![unknown (3)](https://user-images.githubusercontent.com/62926823/77993320-942fb380-7330-11ea-8e7b-76446927eca2.png)
#

**Comment by chochem** [comment]
I tested it. no such bug found. seems to work fine.

regarding your report:
1. 5eu/t is NOT the expected loss. energy outputting machines have a loss of 2^Tier x Amps eu/t (2^5x4= 128eu/t for 4A IV). Of course that is still quite low, more like 1%, not 20%

2. all three parts of your test setup have sizeable internal buffers. you probably forgot to account for that.

**Comment by lectorr** [comment]
Conducted additional tests both on the server and in the singleplayer. A bug is observed if the transformer transfers energy to the north side or up. The video showed the stand and its results.
https://www.youtube.com/watch?v=jZxt0Wd1Zds

**Comment by chochem** [comment]
tested again. still not able to produce any kind of bug. Keep in mind though that the portable scanner is incredible unreliable for transfer rates of any kind! You should really check the actual energy in the batteries + internally stored energy (for this you can use the scanner. its fine for static values just not rates). The same setup you have (ev to hv, including direction) gives me a measured 3.0% loss compared to a theoretical 2.3% or so (not quite sure how to calculate that correctly)

**Comment by Dream-Master** [comment]
@lectorr need more infos on this. Why someone have this is issue and another player not.

**Comment by PredVesTNiK2142** [comment]
I confirm on 2.0.8.8. On our server, players also complain.

**Comment by Dream-Master** [comment]
@PredVesTNiK2142 we need a crash log

**Comment by repo-alt** [comment]
The battery buffers themselves have loss. Also, bat.buffer internal buffer size is Voltage*64*(battery count)

**Comment by repo-alt** [comment]
Feel free to reopen that if you have some real evidence.
