### ISSUE TITLE
Battle Gear 2

### ISSUE THREAD

**Issue by lectorr** [GTNewHorizons/GT-New-Horizons-Modpack#5842]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
mod Battle Gear 2
when trying to enter the world - the client crashes
#
#### What happened instead? (Attach screenshots if needed)
[message.txt](https://github.com/GTNewHorizons/NewHorizons/files/4407114/message.txt)

#

**Comment by seitenca** [comment]
@lectorr A lot of mods break when switching to Smooth. This is not something we can fix. Either use default, or remove Optifine entirely.
