### ISSUE TITLE
Temple caller resets extra hearts

### ISSUE THREAD

**Issue by ahmetsad** [GTNewHorizons/GT-New-Horizons-Modpack#5843]
#### Which modpack version are you using?
2.0.8.7
#
#### If in multiplayer; On which server does this happen? 
Sp
#
#### What did you try to do, and what did you expect to happen?
Using temple caller
#
#### What happened instead? (Attach screenshots if needed)
extra hearts from spice of life carrot edition reseted to 0. Foods were eaten wasn't deleted.

**Comment by chochem** [comment]
@mitchej123

Myself, I haven't used temple caller, but also had all the hearts vanish a couple of times. No idea why, havent been able to reproduce it reliably. Restarting fixed the issue. (playing 2.0.8.8)

**Comment by Prometheus0000** [comment]
Temple caller isn't usable without changing the config, unsupported
