### ISSUE TITLE
[RFC] Add additional bonsais. 

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#5844]
I suggest adding pine trees as ic2 bonsai crops since we are going to need pine oil for new gt++ ore processing chain. 

Also requesting for comment if you think we need more bonsai crops.

**Comment by Impos913** [comment]
Natura nether trees might be useful. Ghostwood for bonemeal, darkwood for fertilizer, bloodwood for redstone, fusewood for gunpowder. At least darkwood and fusewood as there are better sources for redstone and bonemeal.

**Comment by quedral** [comment]
what to discuss? more bonzai's the merrier.

**Comment by Impos913** [comment]
We shouldn't add every tree as a bonsai because they are all going to effect ic2 breeding chances. They will make harder to get some crops.

**Comment by mitchej123** [comment]
> We shouldn't add every tree as a bonsai because they are all going to effect ic2 breeding chances. They will make harder to get some crops.

I think that's the wrong approach and is a separate issue.  We could make the ic2 crop breeding more deterministic if we wanted to avoid this problem.

**Comment by glowredman** [comment]
I'm about to implement the Natura Nether trees as bonsais but before I can do so there are a few things that should be discussed further:
At the moment the bonsais share the same properties as the vanilla bonsais, with some exceptions:

|name|tier|attributes|drop (amount, probability)*|
|:---|:---:|:---:|:---:|
|Ghostwood|4|Tree, Bonsai, Leavy, Nether, Undead|Ghostwood (10, 80%), Ghostwood Sapling (2, 40%), Bonemeal (2, 20%)|
|Bloodwood|4|Tree, Bonsai, Leavy, Nether, Redstone|Bloodwood (10, 80%), Blood Sapling (2, 40%), Redstone (1, 20%)|
|Darkwood|4|Tree, Bonsai, Leavy, Growth|Darkwood (10, 80%), Darkwood Sapling (2, 40%), IC2 Fertilizer (1, 40), Potash Apple (1, 10%)|
|Fusewood|4|Tree, Bonsai, Leavy, Explosive|Fusewood (10, 80%), Fusewood Sapling (2, 40%), Gunpowder (2, 20%)|

*stack size is amount ±4
 - growth duration is tier * 200 * 3, so in this case 2400
 - max size is 3
 - seed is the corresponding Natura sapling

What to discuss:
 - if the above stats are balanced and appropriate
 - if the new bonsais should require Netherrack or another block below
 - the Bloodwood tree grows upside-down in the nether. Is it okay to have it grow normal (game design)?
 - if the humidity/nutrients/air requirements should be changed becuase the tree grew in the nether

**Comment by Prometheus0000** [comment]
Has the thing suggested by mitch been added? No? Any other solution? No? Then maybe wait, or contribute to those solutions yourself, so you don't make it even harder to get far more useful crops.

**Comment by Prometheus0000** [comment]
Also, the potash apple is super rare normally, so it should probably be more like 1% (I think?). And did it even drop fertilizer?

**Comment by SampsaxD** [comment]
We also already have crops for bonemeal (Corpseplant), fertilizer (Fertilia), redstone (Redwheat), and gunpowder (Creeperweed)
I don't think we need more bonsais to replace the existing crops.

**Comment by mitchej123** [comment]
I'm a fan of variety, I'd say add them.  We can evaluate making them more deterministic separately.

**Comment by Prometheus0000** [comment]
I'm fine with adding them once we have that deterministicness, but we don't yet, right? We can just hold off until then, since there's nothing unique here.

**Comment by glowredman** [comment]
> And did it even drop fertilizer?

Not directly. The Fertilizer can be extracted from Darkwood (2->1), Darkwood Leaves (8 -> 1), Potash Apples (1 -> 4) and Darkwood Saplings (2 -> 1).

The drop numbers are based of the original bonsais because, but if they are far too bad/good I'm happy to change them.

What I don't really get is what is meant with "deterministic". That the crossbreeding relies more on the attributes?

**Comment by Prometheus0000** [comment]
Probably. It's not decided yet. But basically, you could 'determine' what you get from breeding something instead of total RNG. So it'd be far easier to get what you want, and also not have the % reduced from all the other crops.

**Comment by SampsaxD** [comment]
Maybe I am biased, but I don't see anything wrong with crop breeding. It's already quite predictable what you can get from most crops, save for a few like stickreed, and making it easier would most likely trivialize crops, making everyone do them, when they are already very common.

**Comment by Prometheus0000** [comment]
You also do no-rocket runs, so maybe you're used to excessive grind. Having to babysit them for hours to get the right crops is extremely annoying, and it's not like it's only these ones, it's also the witchery trees someone wanted to add. And if it was less random we could add more of the useful types of crops, like obsidan, sulfur, other minerals, planet dusts, etc.

**Comment by SampsaxD** [comment]
I think crops are in a good place right now materialwise, they shouldn't be able to do literally everything, otherwise they would completely obsolete bees.

What does randomess have to do with adding new types of crops, anyways?

**Comment by Prometheus0000** [comment]
So you can actually get the crops you want. And I think you should be able to get the same stuff with crops as bees. Why shouldn't you be able to? So imagine how many crops that would be an increase of. And with bees, once you get to the appropriate point, you can just gendustry them. Or the binnie stuff it that works.

**Comment by SampsaxD** [comment]
You shouldn't be able to get everything from both, because then there would be no incentive at all to do bees alongside crops. I've also looked at it as crops = early-midgame, bees = mid-endgame, and I don't think it should be early-endgame for both.

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4505

But if it's the intention to have it like you say, I'd like it expressed. And then stuff like transformium, space plant, quantaria, stargatium, etc should be removed.

**Comment by glowredman** [comment]
> it's also the witchery trees someone wanted to add

I didn't find any issue detailing this problem, but I can see why one would want that. At the moment the only option to get the Witchery saplings is via a tree farm. This means that the same logic that applies for vanilla bonsais would also apply for theoretical Witchery bonsais, except vanilla saplings can be substituted nearly every time. For this reason I'd like to add that topic to this issue/thread.

On the topic of buffing/not buffing crops: I think the fact that, especially in the earlygame, you have to babysit the crops a lot (as opposed to bees, where you put them in the Apiary an just do something else) which is very tedious. How long it took me just to get Stickreed... But then the highest tier I achived is late-MV, so I am probably not the best person to ask. I think there are good arguments for either side, so I think it is probably best to have a vote on this.

Finally, although I am very much pro-variaty, I also don't think it should be possible to acquire every material in the game via crops.

**Comment by Prometheus0000** [comment]
#5024 The thing is, you only need a few stacks of saplings, and then you're done for basically the rest of the game. Unless you really love witchery and want to make witchery stuff all the time I guess. At the cost of making it harder for everyone to get the crops that actually matter. Same for thaumcraft trees, you only need one tree of each if you get the sapling (you use that for a quest, right?).

If people want separate stuff for crops and bees then that's fine I guess, but there's a bunch of recipes that are very weird when comparing them, like the purified nether star ore one.

**Comment by mitchej123** [comment]
@Prometheus0000 Please treat the issue of obtaining what you want because of RNG vs making it deterministic as a **separate issue** and stop conflating the two.  

Make another issue, with how we should address it, and I'm happy to do the mixin patching.

**Comment by Prometheus0000** [comment]
I don't really know how to do that either, it's just that I don't want it to get harder to get specific crops until that's done. Wouldn't I have to understand the code to even suggest something? Which I don't. I figured that someone like you or moron was thinking about it since the last time this came up. Personally, I'd be happy if we completely ripped off agricraft, but that was shot down because it's too easy, which I also understand. Should I just make an RFC to ask for suggestions then?

Wait, you're saying I'm conflating RNG and deterministicness? Isn't RNG non-deterministicness? Maybe you could explain what I'm 'conflating' here? That means confusing them for each other, doesn't it?

**Comment by chochem** [comment]
> 
> 
>  it's also the witchery trees someone wanted to add

not gonna comment on the rest, just wanted to add the witchery trees should not be made into bonsais. They have specific mechanics like spawning mobs, that would probably be difficult to implement for bonsais.
