### ISSUE TITLE
Bartworks causing server crashes?

### ISSUE THREAD

**Issue by Jakersd404** [GTNewHorizons/GT-New-Horizons-Modpack#5845]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Personal Server
#
#### What did you try to do, and what did you expect to happen?
Tried to launch my server and have it run
#
#### What happened instead? (Attach screenshots if needed)
Crashes and says that bartworks is causing errors
#
#### What do you suggest instead/what changes do you propose?
Something to fix the issue?

Pastebin Crash Log: https://pastebin.com/8EFEMWeL

It says at the bottom that it has something to do with AE2 but looking at the rest of the crash log and thew console log of my server only bartworks errors seem to be popping up. I would really appreciate some help with this! (This works when hosting a lan world but on my actual server it just won't work)

**Comment by Dream-Master** [comment]
@Jakersd404 you dont use the 2.0.8.3
You update gt++ to a not recommenend version (42)
use gt++ 25 or older.
Your bartworks is to old use bartworks 0.5.12
https://github.com/bartimaeusnek/bartworks/releases/tag/untagged-d87f67fa9bff7f5d1374

**Comment by draknyte1** [comment]
Bart has already released a fix for my latest build. (Both made yesterday)

His issue is probably with the crafting speed up.

**Comment by bartimaeusnek** [comment]
This was an issue caused by a pre version of GT++ adding additional OrePrefixes and my hook running before that addition, please make sure to write these things in the ticket.  If you modify the shipped version.
"(GT-PlusPlus-1.7.05.42 (1).jar) "

Was fixed yesterday as @draknyte1 said.

**Comment by Jakersd404** [comment]
This is where a problem occurs. My server host says "Old versions of Gt-PlusPlus are broken" and switches me to version 42. Is there a version of bartworks that can work with GtPlusPlus 42?

**Comment by Dream-Master** [comment]
@Jakersd404 Ask @draknyte1 
I run the game with version 25.

**Comment by Jakersd404** [comment]
Apparently the older versions send an "update check" and the server finds it suspicious. Is there anyway to turn this off that anyone knows of? Or again is there a way to use version 42 with bartworks?

**Comment by Dream-Master** [comment]
@Jakersd404 again ask draknyte for an patch.

**Comment by draknyte1** [comment]
Tell your host they’re a fucking idiot. 
Wait for official releases of both BW and GT++.

You could also just *disable* the update check. 🤦🏻‍♀️🤦🏻‍♀️🤦🏻‍♀️🤦🏻‍♀️🤦🏻‍♀️

**Comment by Jakersd404** [comment]
Yeah I don't doubt they are and that was the first thing I did but they're apparently still saying it's checking for updates.
Any idea on when the next official release is?

**Comment by draknyte1** [comment]
Soon™

**Comment by Dream-Master** [comment]
yes soon
