### ISSUE TITLE
Difference between MultiMC download on the downloads website and server pack (which is compatible with Technic)

### ISSUE THREAD

**Issue by john01dav** [GTNewHorizons/GT-New-Horizons-Modpack#5846]
The MultiMC download for 2.0.8.8 on downloads.gtnewhorizons.com is incompatible with the same version's server pack there, but the Technic client is compatible with the server pack there. Applied Energitsics, Advanced Backpacks, and Forestry have conflicting versions. Some players on my server report that this MultiMc pack works fine for them, but, when I copy/paste the below URL into MultiMc I can't join my server (gtnh.moddedminecraft.club), which is built from the linked server pack. 

MultiMc download in question: http://downloads.gtnewhorizons.com/Multi_mc_downloads/GTNewHorizonsClient-1.7.10-2.0.8.8-MMC.zip
Server pack in question: http://downloads.gtnewhorizons.com/ServerPacks/GTNewHorizonsServer-1.7.10-2.0.8.8.zip

**Comment by john01dav** [comment]
To fix this I *strongly* recommend changing the MultiMc zip instead of all the others, to prevent further issues for those using this pack and needing it to stay how it is (or, if you must change the rest, fix MultiMc for this version, and make a 2.0.8.9 where it's different) so players can easily join.

**Comment by Dream-Master** [comment]
will ckeck

**Comment by Prometheus0000** [comment]
Old version
