### ISSUE TITLE
Get ready for Tier 3 Description Text Number

### ISSUE THREAD

**Issue by meneken17** [GTNewHorizons/GT-New-Horizons-Modpack#5850]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
Quest description says 'eight is enough for this quest' but requieres 9 aluminium ingots. 
#

**Comment by Dream-Master** [comment]
i close this after i make a new release.
