### ISSUE TITLE
Molten Vibrant Alloy solidifies to EnderIO variant and doesn't unify to GregTech variant

### ISSUE THREAD

**Issue by Sovereignty89** [GTNewHorizons/GT-New-Horizons-Modpack#5852]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Tried creating Vibrant Alloy Ingots using the Alloy Blast Smelter. The Molten Vibrant Alloy turning into a Vibrant Alloy Ingot from GregTech.
#
#### What happened instead? (Attach screenshots if needed)
Tried creating Vibrant Alloy Ingots using the Alloy Blast Smelter. The Molten Vibrant Alloy turns in to the Vibrant Alloy from EnderIO when solidified to an ingot. It then doesn't unify to a GregTech one like some other materials do. Not in inventory or on the ground. (Turning it in to plates and smelting is a workaround).
#
#### What do you suggest instead/what changes do you propose?
Have it either solidify or unify to a GregTech ingot.

**Comment by Prometheus0000** [comment]
@shawnbyday Why would this be GT++?

**Comment by draknyte1** [comment]
The fluid returned is actually specially handled for Energetic/Vibrant within GT itself and then solidification is also handled by GT. Not an ABS issue.
