### ISSUE TITLE
EIO Advanced Item Filter broken

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#5853]
2.0.8.8

The second row of filtered items in the EIO advanced item filter is broken, and items cannot be saved into these slots. 
All second row filter-items on existing conduits have also sadly been removed after updating the pack.

**Comment by Retster** [comment]
Can confirm, my automated Vacuum-nuce setup was broken because of that bug and i go back on 2.0.8.3 from backup

**Comment by Ethryan** [comment]
Why is this disabled?
[Link](https://github.com/GTNewHorizons/EnderIO/blob/9a5bdf55ca0dc9818bb61f5a5fdf60226c5a7916/src/main/java/crazypants/enderio/EnderIO.java#L447)

**Comment by chochem** [comment]
I think @Zoko061602 worked on this.
