### ISSUE TITLE
World crash when breaking or placing gregtech pipes/cables/machines.

### ISSUE THREAD

**Issue by royalarmor** [GTNewHorizons/GT-New-Horizons-Modpack#5856]
2.0.8.3

There a chance to my world crash every time I place/break a gregtech machine/wire/pipe. I was having ramdom  crashes before but crashes were so rare that I just ignored them (I can't confirm if these crashes are the same I'm having right now) . Now with the constrution on my oil ryfinery/power plant , more machines added to the world, the game crashes very very frequently. very other mod seens fine only when I mess with gregtech I have this issue.

This issue is extremely similar to the issue #2510 

i3 9100f
16 Gb ram (5Gb dedicated to minecraft)
Minecraft runing on a SSD
Java build 1.8.0_241
 
Crash logs:

https://pastebin.com/1fe1CDVe
https://pastebin.com/3BupGm37
https://pastebin.com/Ehn9mN7W

The last two crashes seems to disappear when  I remove fastcraft
All of them is related to removal/placing of gregtech things
Sorry for any english errors, my english is pretty basic.

I would  appreciate any suggestions

**Comment by Dream-Master** [comment]
@GTNewHorizons/core @GTNewHorizons/developers any idea on this ?

**Comment by Prometheus0000** [comment]
Does it still happen on newer versions? Also try reinstalling the pack (and not from twitch if you're using that).

**Comment by Dream-Master** [comment]
i never heared or have such bug

**Comment by royalarmor** [comment]
No update didn't help =/ I try restore the world moving/delete chuck but nothing helped
I started a new world by now, Amost at Iv again 
Anyway guys thx for the time and attention, it seens somehow my world get corrupted...  I dont know...
