### ISSUE TITLE
Osmiridium ore from quest useless

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5857]
#### Which modpack version are you using?
2.0.8.5dev
#
#### What did you try to do, and what did you expect to happen?
Completed metals from the sky on the farming tab, got ore and thought it might be useful.
#
#### What happened instead? (Attach screenshots if needed)
No uses, can't be used with quantaria either.
#
#### What do you suggest instead/what changes do you propose?
Change with iridium ore? This would allow you to grow the plant though, and you can get the quantaria seed from the quest. Is that what's intended? Or is this item a joke item? If you change it to 2 iridium ore and 2 osmium, keep in mind you can only use the iridium for the crop if that's intended.

**Comment by Impos913** [comment]
You can get iridium ore from end. Though that vein is really rare.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizons/commit/e41b43fe9bd26fe8d06b987e1cf9f79c91e3b9a4
