### ISSUE TITLE
Hostile mobs spawning in perfectly lit area

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#5864]
#### Which modpack version are you using?
dev

#### What do you suggest instead/what changes do you propose?
Remove the mob mod that is causing this bug, because it is a devastating issue that no fancy mob mod can justify.

**Comment by Anarack** [comment]
well, step 1 is what mob you are talking about?

**Comment by draknyte1** [comment]
I’ve had various shit spawn in perfectly lit areas over the years. 

It’s either Special mobs or Infernal Mobs. Think the former.

**Comment by ScriptedPiky** [comment]
Special Mobs mod. Infernal Mobs shouldn't be touching spawning conditions (at least I hope), rather the special mobs that are being spawned from Special Mobs mod have some horrible coding that causes them to ignore certain conditions perhaps. Also, speaking of Infernal Mobs mod, the enemies that have the Ghastly prefix are what causes your machines and other things to constantly explode. Base go boom after a zombie walks up to you and sets off your IV machinery.

Special Mobs has caused so many issues that I wonder if we should keep modifying it further and fix all the problems or start a brand new mob mod.

**Comment by leagris** [comment]
I have had brutal zombies spawn in shallow water covered with lillypads, despite perfectly lit area and no yellow or red cross show by NEI
I have had infernal wisps spawns at similar places, daytime, no shadow, torched everywhere. Possibly related to this mob mods. I cannot get any butterfly to lay caterpillars into forestry leaf block. They seem to fail to despawn as they should when doing so.

I now removed all these three mods and will test again if I can now get caterpillars.

Removed:
- InfernalMobs
- SpecialMobs
- AngerMod (I don't like Butterflies explosions)

**Comment by ScriptedPiky** [comment]
Wisps are from the Thaumcraft mob and have unique spawning conditions. The best way to potentially stop them from spawning completely is by using slabs in all areas. Unsure as to why they're spawning near or in shallow waters.

Butterfly stuff was recently changed, I think Moron or Mitch changed/modified them in some way to prevent mass amounts of butterflies populating the area and going everywhere.

**Comment by leagris** [comment]
You cannot breed butterflies without collecting caterpillars and making serum with the caterpillar

So if they removed the ability to lay caterpillars in leaf blocks, then they broke the mechanism of butterflies

**Comment by Dream-Master** [comment]
@richardhendricks @wlhlm can you check the mods special mobs and infernal mobs if the ignore light levels when spawning?

**Comment by wlhlm** [comment]
Infernal Mobs are not special entities in their own and thus have no special spawn code. Modifiers are applied after a mob is spawned. Wisps and Brutal Zombies are TC mobs. I suggest you just disable one mod (I'd say start with Infernal Mobs) and see if the problem still occurs.

**Comment by Prometheus0000** [comment]
Is it still happening?
