### ISSUE TITLE
T5 rocket allows Europium pre T1 fusion

### ISSUE THREAD

**Issue by Anarack** [GTNewHorizons/GT-New-Horizons-Modpack#5870]
2.0.8.8
It seems europium's main source should be fusion initially at least.

Suggestion to prevent t5 rocket allowing europium

Add europium bolts to rocket plate. (simplest change)
Bump the t5 plate up 1 tier in the assline. (may need to rework rocket eu costs again)

**Comment by chochem** [comment]
slightly longer explanation: 
1. T5 rocket does not need europium at the moment
2. T5 rocket reaches ross 128ba
3. there you can get bartimaeusnek veins which give europium.
