### ISSUE TITLE
[RFC] Increase the fuel capacity of Copter Pack. 

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#5873]
#### Which modpack version are you using?
2.0.8.8

#### What do you suggest instead/what changes do you propose?
I suggest to increase the fuel capacity of copter pack from 6 buckets to 32 buckets, so it will last longer and we will be able to fill it with large fluid cells.

**Comment by Dream-Master** [comment]
copter pack is a low tier flying device. I am against to make the tank much bigger.

**Comment by Impos913** [comment]
There is no better way of flight until very late tiers though.

**Comment by AiramProvoker** [comment]
The harness is superior; there's also the bat form from Witchery, which has a fun trade-off.

**Comment by Impos913** [comment]
Harness is not even close to being superior. It is slower, wastes the chestplate slot.

**Comment by AiramProvoker** [comment]
Just tested it. The harness is superior in many ways:
- Fuel consumption rate and fuel availability.
- Synergy with other baubles
- **WAY** better vertical speed
- Slightly better speed overall with haste, cloak, girdle.
- No annoying sound
- No item dislocation
- Doesn't waste the backpack slot, which could provide  with irreplaceable permanent buffs (like fire resist or regeneration)
- Extra interactions with related mechanisms, like the pylons.

Combat situations from MV and above are solved with a crossbow; the protection aspect is **easily** compensated with enchantments. 
**Conclusion: Harness is far superior to the copter pack.**

**Comment by Impos913** [comment]
So you say I should take off my shadow fortress and wear the harness... It is using the chestplate slot and that makes it a piece of trash.

**Comment by AiramProvoker** [comment]
Maybe in some extreme cases of PVE, the copter pack is better. Overall, it's clearly obvious that harness blows the pack out of the water.

**Comment by Dream-Master** [comment]
@Impos913 @AiramProvoker ok lets open up this issue as RFC one.

**Comment by Impos913** [comment]
I would like to use at least steel large fluid cells to fill the copter pack. So at least the capacity can be increased to 8 buckets.

**Comment by Dream-Master** [comment]
about 8 buckets we can discuss.

**Comment by Extremity4** [comment]
If there's a plan to allow large steel cells in copter jetpacks then the capacity should be a little over 8 buckets imo, like probably 9. If it's exactly 8 buckets then you won't be able to fill it in midair since you won't be able to put the cells in until it's completely empty. I don't really see the need for this change though as a stack of cells of a good fuel (such as cetane) lasts quite a while unless you're using hover mode constantly.

**Comment by Dream-Master** [comment]
@Extremity4 Did you test the new version instead of complaining here ?

**Comment by richardhendricks** [comment]
I think it's fine with 6, but would be all right with an increase to 9 buckets so steel fluid cells can fill it.  It would also make it viable with lower quality fuels like ethanol or diesel, until your cetane setup is fully online.

**Comment by Dream-Master** [comment]
large fluid cells not working here. I test it and cant fill the choper pack with it

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/78577237-11c25a80-782e-11ea-920f-c6c85c2cbf78.png)

**Comment by Dream-Master** [comment]
i update it to 16 so it can hold 16 buckets/cells and additional 16 more (32 in total)

**Comment by Dream-Master** [comment]
http://jenkins.usrv.eu:8080/job/Advanced-Backpacks/3/
