### ISSUE TITLE
Crash when exiting world to main menu

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5874]
#### Which modpack version are you using?
2.0.8.5dev
#
[crash-2020-04-05_08.40.04-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4433607/crash-2020-04-05_08.40.04-client.txt)

It mentions BW, so it's probably a BW issue?
#
#### What do you suggest instead/what changes do you propose?
Fix it or tell me to post it to BW if it's bart's problem.

**Comment by Dream-Master** [comment]
post it on barts side

**Comment by bartimaeusnek** [comment]
should be already fixed
