### ISSUE TITLE
Outdated Fluid Overview  - Quest 1743

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#5875]
#### Which modpack version are you using?
2.0.8.8
#
####

Quest 1743 (Saltwater and Chlorobenzene on Mars, Space Race Tab) gives an important overview of the fluids on planets for the player. However it is outdated/incorrect.

The exact overview is here: https://github.com/GTNewHorizons/NewHorizons/blob/master/config/GregTech/GregTech.cfg#L118

I did not go through everything, but clearly Molten Naquadria and Molten Naquadah are no longer available anywhere.

Please update the quest description. (also, there is a typo. 'If yu...' should be 'If you...')

**Comment by Dream-Master** [comment]
I fixed typo and remove Naquada/naquadria

**Comment by Pnc6lx** [comment]
> I fixed typo and remove Naquada/naquadria

it was existed, and in 2.0.8.8 @0lafe  removed it without any discord. I think it should after a discuss

**Comment by draknyte1** [comment]
Fluid Naq shouldn’t have ever been added. (Someone did it without thinking)

They unbalance power generation now and in the future with the LNR.

**Comment by Dream-Master** [comment]
@Pnc6lx I removed it not 0lafe. I am the Pack Dev.
