### ISSUE TITLE
MBF does not behaves correctly

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#5876]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
was baking SpPu dusts inside the MBF
#
#### What happened instead? (Attach screenshots if needed)
According to config file, max number of processed items per batch for all mega multis is 256, but
it processed 360 ingots: 

My setup:
all the output hatches are zpm, osmium glass, awakened draconium coils, 8 UV hatches (UEV tier), 3input hatches with argon, nitrogen and helium inside, input bus hv with circuit 11 & 1, mbf set to prioritize circuit 11, and an output bus hv with uv conveyor set to export mode linked to a huge bedrockium item pipe.

Here is the recipe:
![image](https://user-images.githubusercontent.com/12850933/78508873-67ddc200-778a-11ea-815a-5cf7d768f51c.png)

So what i do is:
 - I put 360 SpPu dusts in the input bus
 - I start the MBF with a soft mallet
 - 300 hot SpPu are instant processed and output in the bedrockium pipe
 - I wait 300s for the recipe to be done
 - The other 60 hot SpPu ingots are output

**Comment by boubou19** [comment]
Also if i spam the tricorder on the mbf controller, the line "Pollution reduced to: xxx %" will change its value every time

**Comment by Dream-Master** [comment]
@boubou19 try with 2.0.8.8

**Comment by boubou19** [comment]
will do but the class related to the mbf in bartworks was updated 4monthes ago so I doubt it will change something
