### ISSUE TITLE
gt++ fuel rod centrifuging gives non-unified pu239

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#5879]
#### Which modpack version are you using?
2.0.8.8
#
####

I thought the gt++ fuel rod recipes were just a work in progress or something like that. But alk tells people to use them, so here we go:

~~1. centrifuging is only possible for single depleted rods which practically no one uses.~~
2. centrifuging depleted MOX or uranium gives a gt++ pu239 variant which is not unified with the already existing (and actually useful) pu239.

Edit: alk just wrote me somewhere else that 1 is intended.

**Comment by draknyte1** [comment]
Did you not read? It’s intended. 
https://github.com/GTNewHorizons/NewHorizons/issues/4826

**Comment by chochem** [comment]
> 
> 
> Did you not read? It’s intended.
> #4826

I wrote the issue before seeing your reply obviously. I cut it down to point 2 then.

**Comment by chochem** [comment]
@Dream-Master why did you close this? Do you disagree that pu239 should be unified?

**Comment by Dream-Master** [comment]
is the recipe a gt++ recipe or a gt one @chochem

**Comment by chochem** [comment]
the recipe is gt++ obviously.

I checked the oredicts btw. From the little I understand, this should be the easiest place to fix this. They are:
dustPlutonium for the regular plutonium 239 dust
dustPlutonium239 for the gt++ plutonium 239 dust

**Comment by Dream-Master** [comment]
are the standard gt plutonium dust are the plutonium 239 or add alk a new isotope?

**Comment by chochem** [comment]
I assume the non-gt++ one is just from gt but I am just guessing there.

Here, I made you screenshots of the two:

![2020-04-19_07 39 01](https://user-images.githubusercontent.com/40274384/79681286-03eadd00-8211-11ea-8003-490b4f8ea244.png)
![2020-04-19_07 38 56](https://user-images.githubusercontent.com/40274384/79681293-15cc8000-8211-11ea-8778-0a48740a5e56.png)

**Comment by leagris** [comment]
They are both plutonium239. I think both GT and GT++ plutonium shall have both `Plutonium239` and `AnyPlutonium` material name and ore suffix. `AnyPlutonium` for all plutonium variants like isotope 241, the same way as `AnyCopper` or `AnyIron`?

**Comment by Dream-Master** [comment]
if this is an unification issue on gt side I'll try to fix

**Comment by draknyte1** [comment]
Do *NOT* add anyX tags to stuff. 
I’ll fix this from my side, someone just needs to make me a ticket.

**Comment by Dream-Master** [comment]
@draknyte1 ok

**Comment by Prometheus0000** [comment]
@draknyte1 is this fixed in a version we have? It doesn't appear so ingame

**Comment by draknyte1** [comment]
Converted in chem plant. Fixed in 9.0 afaik.

**Comment by Prometheus0000** [comment]
OK thanks
