### ISSUE TITLE
IV electrolyzer for GT++ multi seems like it might be using a mistiered material

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5883]
#### Which modpack version are you using?
2.0.8.8
#
#### What did you try to do, and what did you expect to happen?
Make the IV electrolyzer.
#
#### What happened instead? (Attach screenshots if needed)
I can't because smelting the osmium ingots requires LuV-tier power.

It seems odd that I can't make it until I can make IV energy hatches, is it supposed to be like this? Maybe the cable could be replaced with something else, like tungsten for example? Or maybe use 2x platinum cables?
#
#### What do you suggest instead/what changes do you propose?
See above. Unless you're not supposed to be able to make it until mid-late IV.

**Comment by chochem** [comment]
I assume you mean the wires, not cables. This is certainly intended. Electrolyzers always take a more difficult wire. E.g., platinum is already needed in EV. Furthermore, you need only like 2 IV machines to make the energy hatch.

If your goal is the LPF, you need the IV energy hatch anyway to get arcanite.

**Comment by Prometheus0000** [comment]
Yeah, I meant wires. I wanted to build the Industrial Electrolyzer, the LPF is a bit further off for me. Yeah, they use higher tier cables in each machine tier, but I was wondering if it's supposed to block off the multi like this, especially since the next one also uses osmium, just 2x. Like, maybe it was possible before the platinum change? Personally I'd like to see more consistency across the machines that use wires in their recipes like the polarizer and thermal centrifuge. Like, it's HV wire for 3 tiers, then straight up to an EV one for 3 tiers, then twice more with LuV wires. And I can't think of any other single block machine that you have to use a material of the tier after the one you're on, power-wise to make. Unless there's more of that later on I don't know about?

**Comment by Dream-Master** [comment]
@Prometheus0000 should we change it ti tungstensteel wires ? iv wires as well. Luv use osmium as well too.

**Comment by Prometheus0000** [comment]
Since the EV uses Platinum (IV voltage) and the LuV uses 2x Osmium (also IV voltage) I think Tungstensteel, Tungsten or Graphene would be appropriate. Any of them would be fine to me.

**Comment by Dream-Master** [comment]
wait if ev use platinum maybe we use a 32k material which are obtainable in iv

**Comment by Dream-Master** [comment]
Maybe HSSG Wires possible too
4,2k heat (tungstensteel Coils)

**Comment by 0lafe** [comment]
You can do LuV voltage ebf recipes in IV, but considering how useless the electro is on its own, this really is mostly about the ++ electro. With the benefits it brings, locking it behind IV hatches/Pt proc for Os, isn't the worst thing. It's still much earlier than you'd ever "need" it

**Comment by Dream-Master** [comment]
@0lafe so you suggest let the old recipe in ?
Using two tiers osmium wires looks not really interresting.

**Comment by 0lafe** [comment]
We could do HSS-S? It'll still need Os, but less, and has an IV smelting voltage. You'll need a LOT for LuV, just like how you need a LOT of Pt in IV, and it's the wire in EV electros. 

This would need roughly the same setup as pure Os, it just uses significantly less Os, and smelts at IV instead of LuV. Imo that makes it a little less interesting, but it could work

**Comment by Extremity4** [comment]
I agree that Os wires are fine. You never actually need an IV tier electrolyzer for anything except the GT++ multi and that gives it an additional cost that I think is okay. It doesn't really matter what the upper tier electrolyzers have as wires because they're very inefficient and no recipes need voltages that high... anybody sane would either use the multiblock or processing arrays for large electrolyzer tasks at that tier.

**Comment by Dream-Master** [comment]
ok so we let the recipe like it is and close the issue ?
@Prometheus0000 @chochem @0lafe @Extremity4

**Comment by Prometheus0000** [comment]
We could have the IV one use platinum and change the EV one to an EV cable, like Black Steel (is this wire even used anywhere?) And getting the IV energy hatch is pretty far into IV, compared to when you can get the other machines/multis from them.

I'd be fine with HSS-S wires (I guess they'd need to be added?). It's not getting the osmium I have a problem with, it's the smelting.

**Comment by Dream-Master** [comment]
No the ev stay like it is. Why we need to change that. The issue said IV version of the Electrolyzer.

**Comment by Prometheus0000** [comment]
Well, I guess the question is, do you think we should need to make the IV energy hatch before making the electrolyzer or not.

**Comment by 0lafe** [comment]
Personally for what the multi of the IV does, id recommend a UHV+ energy hatch being required, but IV seems more than ok.

**Comment by Dream-Master** [comment]
Ok so we change it to HSSS and all fine with IV Electrolyzer ?
@Prometheus0000 @0lafe

**Comment by Prometheus0000** [comment]
So you suggest that the IV electrolyzer require a UHV material, like Infinity or something? Not that I really know those materials. And I can't even imagine what material you would suggest the osmium in the LuV version and above be replaced with. If you think the multi should be harder to make, then that's a separate issue. I may have wanted to use the electrolyzer to make the multi, but that doesn't invalidate the fact that it's harder to make than all the other 'regular' machines at its tier, and the tiers before this. Aside from the circuit assembler which specifically requires higher tier circuits. Why doesn't the IV centrifuge or IV ore washer require IV energy hatches to make then for example? Do you think that the electrolyzer (of just this tier) is so much more powerful that it needs to be harder to make? I just want it to be equivalently difficult compared to the other machines.

**Comment by Prometheus0000** [comment]
I'm fine with HSS-S.

**Comment by Extremity4** [comment]
HSS-S is fine.

**Comment by Dream-Master** [comment]
Hss-s iv oslium luv

**Comment by Dream-Master** [comment]
ok good
