### ISSUE TITLE
[RFC] Railcraft tank gauges recipe output ×2

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#5890]
Railcraft tank looks better with gauge block at sides, rather than whole wall blocks.
![Railcraft tank using gauge block at sides](https://i.imgur.com/hxNoVX9.png)

Unfortunately, tank gauge recipes outputs a single block versus two blocks for the tank wall block recipes. This also makes the steel tank gauge excessively costly since it uses two iron tank gauges as ingredients.

I propose to change the tank gauge recipes for both steel and iron Railcraft tank gauges to output two blocks instead of one.

**Comment by Dream-Master** [comment]
Same for the Window. 
Will check the recipes.

**Comment by leagris** [comment]
Will require adjustments to workbench and machine recipes as well as amount of validation ingredients in corresponding multi-blocks quests.
