### ISSUE TITLE
Plasma Turbine does not turn on automatically once it has fuel

### ISSUE THREAD

**Issue by kilianloftis** [GTNewHorizons/GT-New-Horizons-Modpack#5891]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Pumping helium plasma in to the LV Input Hatch of a plasma turbine, I would expect the turbine to start running, as the steam and HP steam turbines do.
#
#### What happened instead? (Attach screenshots if needed)
Nothing. The hatch can fill up completely, but the turbine doesn't start until I hit it with a soft hammer. 
When there is no fuel remaining in the hatch, the turbine stops. If I add fuel again, I still have to use the soft mallet before it will start again.
#
#### What do you suggest instead/what changes do you propose?
Have the turbine start automatically when it has fuel.

**Comment by Prometheus0000** [comment]
Sounds like normal behavior to me? If they were _already on_. Use a machine controller cover.
