### ISSUE TITLE
Pollution/Hazmat crash 2.0.8.9

### ISSUE THREAD

**Issue by Zodiack256b** [GTNewHorizons/GT-New-Horizons-Modpack#5893]
#### Which modpack version are you using?
2.0.8.9 dev
#
#### If in multiplayer; On which server does this happen? 
Single Player
#
#### What did you try to do, and what did you expect to happen?
Crash occurred while outside at night with a rainstorm occurring in game

[crash-2020-04-09_01.01.15-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/4454310/crash-2020-04-09_01.01.15-server.txt)

**Comment by chochem** [comment]
details would help. but probably this one https://github.com/alkcorp/GTplusplus/issues/673
