### ISSUE TITLE
bartworks crushed ore dont put for AE2 ore dictionary bus

### ISSUE THREAD

**Issue by lectorr** [GTNewHorizons/GT-New-Horizons-Modpack#5894]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
bartworks crushed ore dont put for AE2 ore dictionary bus
#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by bartimaeusnek** [comment]
i dont even, what does this mean?

**Comment by Dream-Master** [comment]
I think he means that you ores not detected by ore dict ae2 filter

**Comment by Dream-Master** [comment]
@lectorr please give us more infos when you wrote issues . Thanks

**Comment by lectorr** [comment]
All the ores in the screenshot are from the Bartworsk mod. ME ore dictionary export bus does not see this ore and does not send it to the input bus for processing
![unknown](https://user-images.githubusercontent.com/62926823/78891146-9d76f980-7a6f-11ea-95c1-8238cb429a73.png)
![unknown (1)](https://user-images.githubusercontent.com/62926823/78891153-a071ea00-7a6f-11ea-89da-701c7372edc2.png)

**Comment by Dream-Master** [comment]
@repo-alt any idea on this ?

**Comment by repo-alt** [comment]
Eh, not even looking at the bus code, if it works for everything but Bart's ores, it should be clear who is to blame.

**Comment by repo-alt** [comment]
Relevant piece of code looks like this:
`		int[] ids = OreDictionary.getOreIDs(s.getItemStack());
		for (int id : ids) {
			String name = OreDictionary.getOreName(id);
`
where name is later checked against wildcard
@bartimaeusnek

**Comment by bartimaeusnek** [comment]
@repo-alt my ores are properly added to the oreDict during startup, they wouldnt even be obtainable without it.

**Comment by Dream-Master** [comment]
@repo-alt any news here. Can we fix that ?

**Comment by repo-alt** [comment]
Oredictionary export bus is EC2

**Comment by Dream-Master** [comment]
@deforce any idea on this issue ?

**Comment by DeForce** [comment]
I would first look at @bartimaeusnek work to check if it's actually correctly oredicted. Even if GregTech understands it, doesn't mean other mods are handling it's the same.

**Comment by Dream-Master** [comment]
@DeForce 
https://github.com/bartimaeusnek/bartworks/tree/refactor

**Comment by repo-alt** [comment]
I suspect that Ore Drill doesn't mine Bartworks ores for the same reason

**Comment by bartimaeusnek** [comment]
@repo-alt Ore Drill mines BartWorks ores. That was fixes ages ago.

**Comment by chochem** [comment]
Just to add more info: this does not just affect the bartworks crushed ore, but, e.g., also the bartworks impure dusts. (using dustImpure* in the ore dictionary bus)


The oredict names in the game look fine from what I can tell. Comparison:

![2020-05-04_12 22 27](https://user-images.githubusercontent.com/40274384/80961217-61cb1780-8e02-11ea-8861-fed9b1f09cb0.png)
![2020-05-04_12 22 44](https://user-images.githubusercontent.com/40274384/80961221-642d7180-8e02-11ea-8e97-0f02b88cbef8.png)

**Comment by repo-alt** [comment]
Ok, tested that in 2.0.8.9.dev4 and it is working
