### ISSUE TITLE
Suggestion: Mega Chemical Reactor

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#5895]
I suggest to add mega-chemical reactor with logics simmiliar to other mega-stuff. Even if they will work only with one circuit in them. 

Because in high tiers if you want to sped up chem proces you should make complicated setups to paralelize and speed up all the chem proceses. Of course it`s posible jist to duplicate ALL the CHEM RECEPIES for every chem reactor(with ME interfaces), but for my opinion it's a bit dumb and tps decreasing things.
Making that request when i ending building of x4 LCR 32k setups for every circuit and i see that its not enoug and need to make it even more paralelize..

BTW, maybe make it not like usual 15 * 15 * 15, but wisualy smaller and not just a big box, like 7 * 5 * 5, or so. With new multi-amp energy hatches we are dont ned that much space. Material cost may be stay same like in 15 * 15 * 15 structure.

**Comment by 0lafe** [comment]
LCRs losslessly overclock making them the same speed as a mega for 4 tiers above the tier of the recipe. After that the LCR beats the the mega logic. Do you just want more hatches to be able to fit more recipes in a single LCR? A mega LCR would be worse than normal LCRs so I'm kind of lost on why you want this

**Comment by Retster** [comment]
> LCRs losslessly overclock making them the same speed as a mega for 4 tiers above the tier of the recipe. After that the LCR beats the the mega logic. Do you just want more hatches to be able to fit more recipes in a single LCR? A mega LCR would be worse than normal LCRs so I'm kind of lost on why you want this

Mega LCR is should  support multi-amp energy hatches(or usual energy hatches but in any quantity), and accordingly make more recepies in paralel, like other Mega-stuff. Here is no point in energy savings, but about make one big reactor instead 2/4/16 etc usual LCR at same voltage.

**Comment by 0lafe** [comment]
You don't need to make 2/4/etc LCRs though? If the sole point is to be able to overclock this way beyond your tier, I'm still lost. Most LCR recipes are so fast you don't need to get them even close to tier. 

What's causing you to make 2/4/16+ LCRs?

**Comment by Retster** [comment]
> You don't need to make 2/4/etc LCRs though? If the sole point is to be able to overclock this way beyond your tier, I'm still lost. Most LCR recipes are so fast you don't need to get them even close to tier.
> 
> What's causing you to make 2/4/16+ LCRs?
I making all chemicals on demand, but not precraft. And use not separate LCRS for all recepise, but all recepies in one pull of LCR with same circuit. (x4 LCR for #0 circuit, x4LCR for #1 circuit etc). 90% of time that setup is idle, but i i will order something heawy then all chain of chemical reactions will consistently be maked in that setup. And then everything depends on the speed of the reactors.
Maybe that's not often usecase, but that's only suggestion. And more options and choices for players.

**Comment by 0lafe** [comment]
why dont you overclock the CR's instead of making 4 of them?

**Comment by botn365** [comment]
other megas dont do multiple recipes in aprallel they just have high parrallel counts 
the onlu use i see in the mega CR is for the few recipes with low recipe times

**Comment by Retster** [comment]
> why dont you overclock the CR's instead of making 4 of them?

nice idea, wil make x4 overclocked LCR. thanks, It will x4 speed up it. But still prefere single machines with multi-amp energy hatches. 

Thank you for your attention to my suggestion.

**Comment by 0lafe** [comment]
I'm still so confused on this, why do you have 4 LCRs? They dont benefit from being run in parallel

**Comment by Retster** [comment]
> 4 LCRs? They dont bene

The spped is the benefit, in long-chain of chem reactions, it's important. (platinum line is also here) :man_shrugging: 
https://i.imgur.com/J3WbHjM.png

**Comment by Dream-Master** [comment]
@bartimaeusnek any thoughts on this?

**Comment by Prometheus0000** [comment]
@bartimaeusnek Should we just close this then?
