### ISSUE TITLE
Over-Generous LV Conveyor maceration recipe

### ISSUE THREAD

**Issue by MatthewCOwen** [GTNewHorizons/GT-New-Horizons-Modpack#5896]
#### Which modpack version are you using?
2.0.8.8
#
#### 
You can craft these with normal rubber, macerate them, and get silicone rubber back

#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/16054364/78939160-75d06300-7a68-11ea-92a4-9f0173e44b66.png)

#
#### What do you suggest instead/what changes do you propose?
change the recipe to give 6 rubber pulp and no silicon pulp and keep the other outputs the same

**Comment by GTNH-Colen** [comment]
Why do we even have these recipes cluttering NEI? I honestly cannot imagine a situation where I feel I need to macerate my LV conveyor down to get a measly 6 rubber back...

**Comment by Dream-Master** [comment]
@MatthewCOwen add allrecipes by hand is much work. We need to do it for mv and hv and th other tiers too. Really necessary?

**Comment by Prometheus0000** [comment]
Only the LV conveyors give silicone in the first slot. And by HV you can make silicone yourself anyway. So you would only need to swap the output of the first two items.

**Comment by Dream-Master** [comment]
thats true will redoing 1 recipe

**Comment by Dream-Master** [comment]
Need a fix because fix not working.

**Comment by Prometheus0000** [comment]
Did the fix work before?

**Comment by Dream-Master** [comment]
fixed

**Comment by Dream-Master** [comment]
idk it was 6 Silicon rubber
