### ISSUE TITLE
Infinity Armour is too fast

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5897]
So as it currently stands infinity armour is just way too fast imo, it's really hard to move around in precisely without flying off in a random direction.

It would be nice if we could modify it to work similarly to the quantum/gravisuit where you only move at an increased speed when holding shift. Non shift flight should be the standard creative vanilla flight speed. This is rather minor change I know but when you've worked on infinity armour for so long it's only fair to make it more user friendly.

The relevant code seems to be contained [here](https://github.com/GTNewHorizons/Avaritia/blob/master/src/main/java/fox/spiteful/avaritia/items/ItemArmorInfinity.java), reducing the relevant speed seems easy enough but I wouldn't know how to add a keybinding for it and definitely don't want to just outright remove the increased flight speed.

**Comment by Dream-Master** [comment]
Its Infinity i would say. Nothing is too fast

**Comment by Prometheus0000** [comment]
Roleplay as Sonic.
