### ISSUE TITLE
JVM memory leak ?

### ISSUE THREAD

**Issue by albus12138** [GTNewHorizons/GT-New-Horizons-Modpack#5899]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
After update to 2088 from 2083, JVM heap memory continuously increase. It used up 8G heap memory after about 6 hours.

root@ea1fce410a80:/gtnh# tail -f logs/gc.log 
      [Choose CSet: 0.0 ms]
      [Ref Proc: 0.3 ms]
      [Ref Enq: 0.0 ms]
      [Redirty Cards: 0.1 ms]
      [Humongous Register: 0.1 ms]
      [Humongous Reclaim: 0.1 ms]
      [Free CSet: 0.0 ms]
   [Eden: 0.0B(408.0M)->0.0B(408.0M) Survivors: 0.0B->0.0B Heap: 8174.4M(8192.0M)->8174.4M(8192.0M)]
 [Times: user=0.17 sys=0.00, real=0.02 secs] 
2020-04-10T14:22:04.147+0000: 28979.396: [Full GC (Allocation Failure) 

#
#### What do you suggest instead/what changes do you propose?
Please check new code added to 2088.

**Comment by Prometheus0000** [comment]
Is this still an issue?

**Comment by albus12138** [comment]
I'm not sure. I have stopped host the server for a few month.

**Comment by eigenraven** [comment]
Some server memory leaks were fixed recently, and this issue doesn't have enough details (like a heap dump) to confirm. If this still happens, re-open with more details.
