### ISSUE TITLE
UHV Pump data stick has incorrect name

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5900]
#### Which modpack version are you using?
2.0.8.3
#

UHV Pump has the incorrect name on the data stick, see below:

<img width="530" alt="Screenshot 2020-04-07 at 05 29 48" src="https://user-images.githubusercontent.com/54497873/79031266-85999580-7b95-11ea-9124-0ddd439c1045.png">

**Comment by Dream-Master** [comment]
@Technus any idea on this
@basdxz

**Comment by Technus** [comment]
Cannot reproduce

**Comment by GeicowithaBango** [comment]
We made a lot of Uhv components 2 days ago, with no problem whatsoever. Pre 2

**Comment by chochem** [comment]
yeah my UHV pump on 9.0 QF2 works fine too (probably scanned when I was on RC1)

**Comment by Dream-Master** [comment]
might be fixed.

**Comment by GeicowithaBango** [comment]
maybe colen put accidentally a HV pump into the scanner lol. 
Is the recipe at lest the right one, @GTNH-Colen

**Comment by GTNH-Colen** [comment]
> maybe colen put accidentally a HV pump into the scanner lol.
> Is the recipe at lest the right one, @GTNH-Colen

The recipe is correct, it just has this weird name for some reason. I scanned it a while ago just didn't make a ticket for a bit so perhaps it was fixed at some point, no idea.
