### ISSUE TITLE
CTD during combat with modified Shadows Witch

### ISSUE THREAD

**Issue by Prunebane** [GTNewHorizons/GT-New-Horizons-Modpack#5902]
#### Which modpack version are you using?
2.0.8.8

#### If in multiplayer; On which server does this happen? 
Singleplayer

#### What happened? 
**In short: [arrow fired from enchanted vanilla bow → bow breaks → arrow hits infernal mob → freeze → CTD]**

Longer version: I was battling a "rare" (5 modifiers - Regen, Poisonous, Fiery, Cloaking, and Quicksand) ShadowsWitch from the safety of my little bunker.
She was fiery and poisonous, so I resorted to using a bow (_Vanilla bow, 5 durability, Flame I enchantment, vanilla arrows_)
She never set on fire, which is fine, and I shot her with 4 arrows as per usual.

The fifth arrow that I shot was when my bow broke.
The witch was in close proximity.
The last thing I remember was me firing my bow, it breaking, and the arrow landing on the witch, upon which my game froze and Crashed To Desktop moments later.
I may have right-clicked her before or after the freeze.

World is fine, re-loading back in works OK.

Crashlog:
[crash-2020-04-11_09.58.09-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4464282/crash-2020-04-11_09.58.09-server.txt)

EDIT: small clean-up of text

**Comment by Dream-Master** [comment]
http://jenkins.usrv.eu:8080/job/TwilightForest/11/
