### ISSUE TITLE
Suggestion: a MT recipe for graphene 

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/GT-New-Horizons-Modpack#5903]
#### Which modpack version are you using?

# /
#### If in multiplayer; On which server does this happen? 

# / 
#### What did you try to do, and what did you expect to happen?

# /
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
I suggest an easy access to graphene via the Molecular Transformer. the MT can -as the name implies- transform the molecular structure of carbon dust to for graphene (both molecules are from the same element just with a diffrent mol. structure). Imo, its a appropriate recipe for a MT. I suggest a cost of around 0.5 eu in total to form one carbon dust into graphene. In general, its seems like a handy method to obtain graphene without being the most efficient one.

**Comment by Prometheus0000** [comment]
0.5EU? Are you missing an M or something? And there's already an easy method to make the Graphite that Graphene is made of? Is this really necessary?

**Comment by GeicowithaBango** [comment]
ah yes, 0,5 M eu of course. i think that it is a nice feature to have, especially if you want quick access and dont have the time to setup an dedicated blast furnace to smelt graphite (/graphene). and btw, its a ++ material so yea....

**Comment by GeicowithaBango** [comment]
no front, just saying

**Comment by chochem** [comment]
that cost is still way too low in comparison. the existing route take 1.4M eu + the setup + nitrogen and silicon.
but generally I also don't really see the point of doing this.

**Comment by GeicowithaBango** [comment]
I explained the advantage of using that method :/ i calculated ~0.5M eu so that 5 amps of EV energy would need 2,5 seconds for one graphene

**Comment by Dream-Master** [comment]
if the other ecipe is 1.4m 0.5 is to cheap

**Comment by GeicowithaBango** [comment]
sure

**Comment by Impos913** [comment]
Making graphene shouldn't be that hard imo as it is just an allotrope of carbon. Should have an easier way to obtain than EBFing at IV tier.

**Comment by chochem** [comment]
I mean diamond is just an allotrope of carbon, too. :)
just saying. I don't mind balance changes.

**Comment by GeicowithaBango** [comment]
yes, imo, a MT is supposed to do that, and not change elements D:

**Comment by Dream-Master** [comment]
we can add it with 2 or 2.5 mio eu

**Comment by Impos913** [comment]
@chochem yes diamond is an allotrope of carbon too. But diamond can be VERY easily obtained infinitely with crops, but graphite doesn't have a crop way or any easy way to automate. Only way is EBFing SiC with IV energy and Wsteel coils.
