### ISSUE TITLE
GlassFiber recipe is different.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#5904]
#### Which modpack version are you using?
2.0.7.5～2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
My Server
#
#### What happened instead? (Attach screenshots if needed)
The number of GlassFiber made is different for Wiremill and Extruder.
![2020-04-12_01 35 30](https://user-images.githubusercontent.com/40425798/79049330-f6a48000-7c5d-11ea-8857-8fe815df5f7a.png)
![2020-04-12_01 35 32](https://user-images.githubusercontent.com/40425798/79049336-fa380700-7c5d-11ea-8761-26f36ef08ebc.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Dream-Master** [comment]
we have to lower the voltage for wire mill but that this two recipes give out different amounts is normal.

**Comment by bartimaeusnek** [comment]
this is intended.
