### ISSUE TITLE
No recipe for small steel turbine

### ISSUE THREAD

**Issue by Zeruel13** [GTNewHorizons/GT-New-Horizons-Modpack#5905]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Try to craft a small steel turbine. 
#
#### What happened instead? (Attach screenshots if needed)
there's no recipe for a small steel turbine
![image](https://user-images.githubusercontent.com/63512252/79049978-f3c17500-7bf4-11ea-87d7-3dd5158271df.png)
![image](https://user-images.githubusercontent.com/63512252/79049994-09cf3580-7bf5-11ea-9445-e8304eda240f.png)

#
#### What do you suggest instead/what changes do you propose?
Quest #1417 recommends crafting a small steel turbine however there is no recipe to make one. 

Add a recipe to make a small steel turbine or change to text in the quest to recommend another type of small turbine.

**Comment by draknyte1** [comment]
Turbines with horrible durability aren’t given recipes. You sure you’re trying to make the right one?

**Comment by Zeruel13** [comment]
The quest says to make a small steel turbine. if there's no recipe then the text on the quest should be changed.

**Comment by Dream-Master** [comment]
yea will check

**Comment by patrick-hill** [comment]
I hit this in 2.0.8.3 as well

**Comment by Dream-Master** [comment]
@draknyte1 is gt++ cut off the bad valued steam turbine blades or is it gt ?

**Comment by draknyte1** [comment]
I do. 
We had an RFC probably a year+ ago and the community decided on a minimum value. You’re welcome to change it in the config file, but it’s probably better to change the quest. 

There is 0 point having shitty turbines with low durability existing.

**Comment by Dream-Master** [comment]
@draknyte1 i only want to know which mod change it thats all (because i cant find it in gt code) and i am with you that low tier turbine blades not have a real use.
I will look for a better turbine material for the quest.

**Comment by Dream-Master** [comment]
Use Blacksteel instead
