### ISSUE TITLE
Massive Lag Spike when building GT Multiblocks

### ISSUE THREAD

**Issue by Mogball** [GTNewHorizons/GT-New-Horizons-Modpack#5906]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Place any GT machine casing (clean stainless steel, inert PTFE casing, etc.). Note, this does not happen with hatches/busses or the main controller block, just the casings.
#
#### What happened instead? (Attach screenshots if needed)
Big lag spike. On my computer (hosting the server), CPU usage jumps to 100%. The client FPS drops to less than 1 or, if I increased the process priority of the server, my whole computer seizes.

**Comment by Mogball** [comment]
I tried commenting out `GregTech_API.causeMachineUpdate` inside `GT_Block_Casings_Abtract::onBlockAdded` and the lag spike was gone. We do have a really large number of multiblock machines (~80 ish?) in the chunks that comprise our base, but this issue only started happening recently. Maybe we hit some critical number of machines, but I also noticed that this happens occasionally when I placed GT cables or pipes.

As far as I can tell, multiblock machines were still forming and functioning correctly.

**Comment by Mogball** [comment]
Okay I poked around the code more. I don't understand the GT codebase much but I think `stepToUpdateMachine` in `GT_Runnable_MachineBlockUpdate` crawls through all machine blocks triggering an update. Our base has rows of distillation towers/chemical reactors/etc. all next to each other, so `aList.contains(pos)` is a potential culprit.

**Comment by Dream-Master** [comment]
feel free to do a pull request if you performance update work so we can review it. @Mogball

**Comment by repo-alt** [comment]
The update will indeed propagate through all connected GT tile entities, including cables, which, for the large base is a bit ridiculous. Not sure what exactly will be broken if update will just be disabled. To be fair it runs in a separate thread, so, not sure why would it cause much lag. The update does nothing for the cables & pipes, so perhaps update propagation through cables may be stopped, this looks like a safest workaround.

**Comment by mitchej123** [comment]
Also seems a hashed set might work better than a list.

**Comment by repo-alt** [comment]
tbh, this function should find & update usually 1 and at maximum 4 joined multiblocks, so even spinning a thread should be unnecessary (cost more than the structure check). But hashset certainly wouldn't hurt too

**Comment by Mogball** [comment]
> The update will indeed propagate through all connected GT tile entities, including cables, which, for the large base is a bit ridiculous. Not sure what exactly will be broken if update will just be disabled. To be fair it runs in a separate thread, so, not sure why would it cause much lag. The update does nothing for the cables & pipes, so perhaps update propagation through cables may be stopped, this looks like a safest workaround.

Oof. Then it's not unlikely that every update is propagating through our whole base... I'll try messing around and submit a PR at some point.

**Comment by Mogball** [comment]
Solved by

https://github.com/GTNewHorizons/GT5-Unofficial/pull/266
