### ISSUE TITLE
Quest for Thaumcraft Cheat Sheet

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5907]
Thaumcraft research is boring, I think most of us can agree on this fact by now. The vast majority of the player base in GTNH are experienced modded minecraft players, we've all done thaumcraft a hundred times by now and quite frankly the research system is boring and tedious.

I propose that we add a quest for the thaumcraft cheat sheet so that once you finish say all of the thaumcraft quests (Which takes you up to the purification talisman essentially) you may use it and unlock the rest of the book. This saves the player potentially dozens of hours of mind numbing dragging of aspects. I have seen numerous players opt to simply cheat in the cheat sheet from NEI or buy the research from a fellow server player just because of this sheer tedium.

This really doesn't change the balance of the pack at all, you still need the items to craft the stuff all it is doing is removing the boring step once you've gotten far enough. Only thing it could affect is the balance of warp, since you can purge it all at once however once you get the pure tear you can do this anyways.

I really think this is a much needed addition, there are quite literally hundreds of researches because of the myriad of addons we use in this pack. Not to mention all the special ones that are specific to GTNH which are added on top.

**Comment by 0lafe** [comment]
Can't you bypass research with thaumic horizons or something? Iirc some book you feed essentia that researches for you

**Comment by Dream-Master** [comment]
No I am against this. I don't spend days and month of making recipe that you unlock in  the book after 1/3 of finishing thaumcraft.

**Comment by Dream-Master** [comment]
If you don't like  thaumcraft make only the stuff you like @GTNH-Colen

**Comment by Extremity4** [comment]
I think most players dislike the tedious research though... Having all of the fun content from TC gated behind hours and hours of repetitive research often either just makes people not play TC, cheat/buy all the research in, or grind their teeth and put up with the 10th unfun hour of aspect dragging,... Your months of recipe making are more going to waste this way than with the alternative IMO

**Comment by GTNH-Colen** [comment]
> No I am against this. I don't spend days and month of making recipe that you unlock in the book after 1/3 of finishing thaumcraft.

None of the recipes are changed by this, it just means you have more freedom after completing the core thaumcraft mod. You would need to be IV to even do this as it is beyond the pure tear quest.

This is not an issue of balance, it's about not making people sit staring at a research game for hours on end for no purpose.

> If you don't like thaumcraft make only the stuff you like @GTNH-Colen

It's not that simple, lots of research is gated behind other research meaning you have to do things you don't care about to get to the items you do, again wasting the users time for no reason.

None of the hard work the dev team has put into creating custom recipes is affected by this, you still have to craft the items yourself. As Extremity says by actually forcing all this research a lot of the work you guys put into the pack is wasted as people simply don't bother to craft the items.

**Comment by Dream-Master** [comment]
Ok we find a way but the sheet will be stay disabled. Its a dev item for me to test stuff not for survival games.

**Comment by psuemno** [comment]
Instead of unlocking all research, an alternative might be looking for ways to improve automating research. [The Book of Knowledge](https://ftbwiki.org/Book_of_Knowledge) can serve as a way to skip the tedium of research, but some people were testing it on the Discord in response to this post and found it to be prohibitively slow. 

One issue was that the block couldn't be World Accelerated. Finding some way to enable that would give one  way to greatly speed up the process.

Another thing that might be done would be to improve the built-in way to speed it up. Putting enchantment boosters around the item speeds it up, but people found that the cap was 200, and with a full 200 it is still only a ~1% chance at progressing research per tick. Since there are many items that serve as more potent enchantment boosters than bookshelves (e.g. enchanted wood), raising the cap would also serve as a way to speed up research speeds a lot.

**Comment by Dream-Master** [comment]
Gadomamcy code can be changed so we can make the book better or add an advanced book.
About the second solution is this pure thaumcraft or another mod?
@psuemno

**Comment by psuemno** [comment]
The Book of Knowledge is a thaumcraft addon, Gadomancy. 

The Book itself gets a small speed boost from having enchantment boosters around it, just like how an enchanting table gets a boost if you put bookshelves around it. The people who were testing looked through the code and it seemed like it caps at 200 boosters (so I assume that's 200 bookshelves but not certain).  However, several mods have enchantment boosters that are more potent, like [Enchanting Bookshelves](https://ftbwiki.org/Enchanting_Bookshelf) or [Magical Wood(https://ftbwiki.org/Magical_Wood) which behave like more potent versions of vanilla bookshelves, so I'd assume would be more potent for the Book of Knowledge as well. If that's the case, raising the cap should let people take advantage of those more potent boosters for faster research, if that's what we want.

**Comment by repo-alt** [comment]
The Book is obviously unfinished, there is an unused interface for alternative boosters, and some unused (and deprecated!) cache for some other (?) boosters . Only author knows what he intended to do with that.

**Comment by Dream-Master** [comment]
If this is Gadomancy i will ask @HelfirePVP

**Comment by Houstonruss** [comment]
I still think warp and research is a bad feature from any thaumcraft version. Getting rid of both should be fine, considering thaum is gated behind tech. Everyone has done TC research. Nobody likes it.

**Comment by repo-alt** [comment]
I think the first time it's ok. And delegating it to the book is a good solution. Of course it would be nice to also have a technomagical alternative, like TecTech research station but for magic.
