### ISSUE TITLE
2.0.8.9.dev4 Crashes when loading an existing world

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#5908]
#### Which modpack version are you using?
2.0.8.9.dev4
#
It loaded up a new world fine, but crashed when I was alt-tabbed out the first time, and shortly after unpausing to enter my existing world the second time.

[crash-2020-04-12_05.30.03-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4466113/crash-2020-04-12_05.30.03-server.txt)

[crash-2020-04-12_05.42.56-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4466114/crash-2020-04-12_05.42.56-server.txt)

It seems to be a problem with SFM?

**Comment by Prometheus0000** [comment]
And I got another, different crash creating another new world.
[crash-2020-04-12_05.59.22-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4466135/crash-2020-04-12_05.59.22-server.txt)

**Comment by Dream-Master** [comment]
@mitchej123 any idea ?

**Comment by Dream-Master** [comment]
@Prometheus0000 test with this version please
http://downloads.gtnewhorizons.com/Dev-Pack/Pack/GTNH-1.7.10-2.0.9.0-pre2-dev.zip

**Comment by Prometheus0000** [comment]
Crash on attempting to load my test world: 
[crash-2020-04-21_15.19.20-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4512200/crash-2020-04-21_15.19.20-server.txt)

After trying to create a new world, it just kicks back to the main menu (it takes the time to create it though, this isn't instant). Closing minecraft doesn't work properly either. MMC thinks it's still running too. Closing that and reopening shows MMC using the same resources javaw.exe (minecraft) should be when running the game. This happened even after killing it, closing MMC and trying again.
MMC log (couldn't figure out which specific file it was, and there was no crash log)
[MMC Log.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4512267/MMC.Log.txt)
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4512272/fml-client-latest.log)

PS, you forgot to remove aromabackup+aromacore
PPS, it feels like it took longer to start up? Is the new loading screen really faster?

**Comment by Dream-Master** [comment]
@mitchej123 any idea on this ?

**Comment by Prometheus0000** [comment]
This appears to work properly now for both loading my existing world and creating new ones.

**Comment by Dream-Master** [comment]
ok
