### ISSUE TITLE
Quest #1511 and #504 in Bee Chapter cannot complete

### ISSUE THREAD

**Issue by albus12138** [GTNewHorizons/GT-New-Horizons-Modpack#5909]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
mp
#
#### What did you try to do, and what did you expect to happen?
try to complete quest 1511
#
#### What happened instead? (Attach screenshots if needed)
cannot complete it
#
#### What do you suggest instead/what changes do you propose?
I set ignoreNBT to true, then I complete it.

**Comment by albus12138** [comment]
quest 504 have the same problem.

**Comment by Dream-Master** [comment]
if nbt is ignored on bees you not need a special bee just any bee which destroy the whole quest

**Comment by chochem** [comment]
they werent very helpful in their description :P
its the *how to bee* tab and the quests are for the habitat locator and the beealyzer.
I have done them both in 8.x, so this is probably a new bug.

**Comment by albus12138** [comment]
Not bees. #1511 is Forestry habitat locator, #504 is Forestry bee analyzer.

**Comment by Dream-Master** [comment]
ok this a total different thing. Sure we can ignore nbt there
