### ISSUE TITLE
An odd request.

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/GT-New-Horizons-Modpack#5910]
Hello, this may be a bit personal but a friend of mine passed away yesterday. I've had a lot of very fond memories with him on this modpack and he's logged thousands of hours play time easily. His name was Eden and his ign was Cerulean627. I was wondering if in his memory you could possibly add a small part of him into the pack somehow maybe in a tooltip or something. I know this is an odd request and I apologize if this is not appropriate to post here. He was very fond of oil ingame. I'm really frazzled and can't come up with a specific idea and would very much appreciate anyone's input. Thank you.

**Comment by Dream-Master** [comment]
@ToastedEggplant Sad to hear this but yes we find something we can add,

**Comment by Dream-Master** [comment]
@ToastedEggplant ok go ahead with something we can do here. I need suggestions.

**Comment by bennydupuy** [comment]
"May you have all the black gold you want" RIP Cerulean

**Comment by ToastedEggplant** [comment]
Sorry this took a while, maybe we can add ("May you have all the black gold you want" RIP Cerulean) as a part of the tooltip on the oil drilling rig.
