### ISSUE TITLE
liquid dna from gendustry only obtainable from sapplings

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#5911]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
wanted to recycle my thousands unused bee drones into liquid dna
#
#### What happened instead? (Attach screenshots if needed)
liquid dna is only obtainable from sapplings, which is weird because it can then be used to make both sapplings and bees
#
#### What do you suggest instead/what changes do you propose?
add liquid dna recipes for drones and princess.

**Comment by Ngar1** [comment]
just for information: 
genepool from binnies generate DNA from bee

**Comment by Dream-Master** [comment]
@boubou19 will this break balance if we add bees to give us gendustry dna ?

**Comment by boubou19** [comment]
IMO this will break nothing because in order to generate something from DNA with gendustry machine, you need to already get a genetic template with 13/13 genes. This only allows to create bees from "nothing" instead of breading them in an apiary. But to get the 13/13 genes, you need to already have the bees you want and extract the genes, which with the current config, will always consume the labware. So you'll need a ton of drones and a ton of labwares and some time (gendustry machines are blacklisted from WA). In addition of that, gendustry machines are somewhere between LuV and ZPM, and it requires end game combs such as plutonium combs, iridium combs, osmium combs. So concerning gendustry, it will not break balance of the mod.

If DNA is used somewhere else, then using bees to farm DNA is a poor solution (iirc you can get like 4 drones per bee life cycle at maximum) because currently, many sapplings (maybe all) can be used to produce DNA so it would be better to make a woodfarm and use the excess amount of sapplings to get DNA.

To conclude, this will not break the current balance of bees.

**Comment by Dream-Master** [comment]
ok

**Comment by boubou19** [comment]
I would recommend to make bees give something like 100mb DNA (average output recipe with sapplings) so that way you need 50 bees to make 1 in the gendustry replicator(a created bee costs 5000 mb DNA)

**Comment by Dream-Master** [comment]
will check the other ingredients
