### ISSUE TITLE
ae2 autocrafting is not working

### ISSUE THREAD

**Issue by BurakOM** [GTNewHorizons/GT-New-Horizons-Modpack#5912]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
single
#
#### What did you try to do, and what did you expect to happen?
ae2 autocrafting is not working
#
#### What happened instead? (Attach screenshots if needed)
terminal closes and when i click crafting status game crashes
#
#### What do you suggest instead/what changes do you propose?
i want ae2 autocrafting
![2020-04-13_20 30 21](https://user-images.githubusercontent.com/63606695/79143379-d0015900-7dc5-11ea-976b-3b9c738b5912.png)
![2020-04-13_20 32 19](https://user-images.githubusercontent.com/63606695/79143438-ea3b3700-7dc5-11ea-9ae0-5588a64bd60c.png)

**Comment by repo-alt** [comment]
seriously? this is a bug report?
