### ISSUE TITLE
Small Collagen adjustment

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/GT-New-Horizons-Modpack#5913]
![2020-04-13_23 43 41](https://user-images.githubusercontent.com/58643870/79165554-a820ee00-7de3-11ea-9719-26c4b66f818b.png)

#### What do you suggest instead/what changes do you propose?
a suggest two things to make this recipe more satisfiable (without huge mob farms) 
1.) lower the amount of needed bones
2.) additionally, allow the use also of bone meal

**Comment by Dream-Master** [comment]
its a 480 eu recipe i dont lower the bones per item
i add a second recipes with 4 bonemeal to it.
