### ISSUE TITLE
buff infinity wire

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#5916]
now 1×infinity wire has 16A and loss 1eu/t/m at max volat. As a kind of endgame materials, I think infinity wire should be superconductor, and it can be buff to 24 or 32 a/wire (uhv superconductor is 16a/wire.

**Comment by GTNH-Colen** [comment]
A lot of wires have strange values, this would need to be part of a general rework of endgame cables imo. Why quantium gives UMV wires I will never know.

**Comment by Dream-Master** [comment]
Yes wires need a rework.
