### ISSUE TITLE
incorrect oredictionary 

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#5917]
I play this pack in zh_CN, and find the space stone dust have incorrect oredictionary like this. 
![-110d305caa09cbf7](https://user-images.githubusercontent.com/49830847/79232624-5ab38800-7e9a-11ea-9aaa-fb5315948629.png)
It is caused by this https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/master/src/main/java/com/dreammaster/oredict/OreDictHandler.java#L161

**Comment by Dream-Master** [comment]
@Pnc6lx what is wrong here ?

**Comment by Pnc6lx** [comment]
> @Pnc6lx what is wrong here ?

Chinese character is illegal character in oredictionary, so it will cause incorrect recipe. for example all the space stone dust have the same centrifuge recipe like dustMoon

**Comment by Dream-Master** [comment]
@Pnc6lx any idea how to fix it ?

**Comment by Pnc6lx** [comment]
> @Pnc6lx any idea how to fix it ?

dont use getdisplayname

**Comment by Dream-Master** [comment]
@Pnc6lx can you make a pull request ?

**Comment by Dream-Master** [comment]
@bartimaeusnek 
You added the code. Any idea whyt we can do here?
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/51e13e368ce317cabdb75c89c66b54d097ee8ff6#diff-63a6df1946ca41b20b2eee99bf950b90

**Comment by Dream-Master** [comment]
fixed with https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/107
