### ISSUE TITLE
Glue Balls

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5921]
Not sure why this isn't a thing but I noticed that "glue" is crafted with two "ball of glue" from tinkers construct however the "ball of glue" can only be created with a tinkers smeltery. There should be a fluid solidification recipe here as well using glue.

That said strangely glue is made by melting down rubber, perhaps this should be removed and the primary method would thus be using refined glue in a distillery (This recipe already exists). Glue can still be made early game by smelting horses I believe, we could always just keep all the recipes but currently it just seems a bit odd that you melt rubber and then form it back into glue?

Thanks.

**Comment by Houstonruss** [comment]
I say just let us ball mold any glue in solidifier for it. Just a cancer way to get the shite EMT wings.

**Comment by GTNH-Colen** [comment]
> I say just let us ball mold any glue in solidifier for it. Just a cancer way to get the shite EMT wings.

Yea honestly this is the easiest option, it doesn't make any sense to force people to use the tinkers smeltery when they stopped using it potentially weeks/months ago.
