### ISSUE TITLE
2.0.8.4-2.0.8.9 can not use ForgeEssentials

### ISSUE THREAD

**Issue by JackMeds** [GTNewHorizons/GT-New-Horizons-Modpack#5922]
#### Which modpack version are you using?
2.0.8.9
#
#### If in multiplayer; On which server does this happen? 
add the ForgeEssentials, nothing happned
It seems to be banned by some mods
#
#### What did you try to do, and what did you expect to happen?
By comparing “only had ForgeEssentials”  and “ForgeEssentials with GTNH”
#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by TimeConqueror** [comment]
Please provide a crash report

**Comment by Dream-Master** [comment]
@JackMeds

**Comment by JackMeds** [comment]
mod:    https://www.curseforge.com/minecraft/mc-mods/forge-essentials-74735
There's no crash report. It just doesn't work.
log：

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4500900/fml-server-latest.log)
After the test failed, I stopped it manually

**Comment by JackMeds** [comment]
I've tried every command about ForgeEssentials, 
only show Unknown command. Try /help for a list of commands

**Comment by TimeConqueror** [comment]
As log says you use forgeessentials-1.7.10-1.4.6.1362-server.jar. This version doesn't exist on curseforge. The last is 1.4.6.1357.
@JackMeds

**Comment by JackMeds** [comment]
This is 1.4.6.1357
[fml-server-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4509225/fml-server-3.log)

**Comment by masterqgj** [comment]
I have the same issue, already asked in the discord, before i found this issue. It's a bit sad since FE offers some nice and easy teleportfeatures and such and was quite easy to integrate until now. 
I Used some 1.7.x build for GTNH the last time and in that build it still worked.

I too have no crash nor an error message in the logs, only the commands do not get recognized at all :(

**Comment by qvazzar** [comment]
Me too. Recently updated my server from 2.0.8.3 to 2.0.8.8 and commands from Forge Essentials suddenly stopped working, as if this mod just doesn't load at startup. It's sad because FE offers good authorization system that doesn't break fake players from other mods..

**Comment by kaziu687** [comment]
There is problem with mixin loader. ForgeEssentials cannot load them cuz they are loaded already. Try to move sponge mixins classes (without manifest) to essentials then remove mixins jar. Works like a charm at 2.0.9.0QF4 version.
[forgeessentials-1.7.10-1.4.6.1362-server-mixins-updated.jar.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4886923/forgeessentials-1.7.10-1.4.6.1362-server-mixins-updated.jar.zip)

**Comment by Prometheus0000** [comment]
Is this fixed? What even is it? A MP thing?

**Comment by boubou19** [comment]
ForgeEssentials is the forge port of the famous bukkit plugin called Essentials. And it looks like Forge Essentials is broken by mixins. But yeah it's essentially allowing for many commands used in multiplayer: homes, warp, tpa...

**Comment by mitchej123** [comment]
FE should gracefully fall back if another mixin of >= version is loaded.  I _believe_ I addressed this with the latest spogemixins.  Comment to reopen if it's still an issue.

**Comment by Curtion** [comment]
> FE should gracefully fall back if another mixin of >= version is loaded. I _believe_ I addressed this with the latest spogemixins. Comment to reopen if it's still an issue.

I use https://media.forgecdn.net/files/2659/141/forgeessentials-1.7.10-1.4.6.1357-server.jar ，FE still not working，My GTNH version is 2.1.0.4

**Comment by mitchej123** [comment]
Please provide a log.

**Comment by Curtion** [comment]
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6279873/fml-server-latest.log)

I have the same phenomenon as JackMeds，It didn't crash, it just didn't work，input command: show Unknown command

**Comment by KaneHart** [comment]
I'm also having this issue I tried deleting the spongemixins jar haha bad idea. I also attempted to prune it from the fe jar itself without any luck yet. I'm playing around with it, but I fear I might run into issues here. 

Using the 2..1.0.7a

**Comment by KaneHart** [comment]
So I tried a couple versions including their latest build from jenkins. 

https://ci.forgeessentials.com/job/FE-1.7.10/1366/artifact/build/libs/forgeessentials-1.7.10-1.4.6.1366-server.jar

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6519927/fml-server-latest.log)
