### ISSUE TITLE
Repeatable quest dnt work 

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#5923]
#### Which modpack version are you using?
2.0.8.3

#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com

Repeatable quest dnt work 
![изображение](https://user-images.githubusercontent.com/47714084/79324319-1bc41780-7f18-11ea-8a0a-0c15ffeb7607.png)

**Comment by Dream-Master** [comment]
wait until we upate. I think this is fixed hopfully soon

**Comment by MotDT** [comment]
Ok, Thanks!

**Comment by Dream-Master** [comment]
Let test lastest version on zeta and we will see if this works. After it i will update the servers
