### ISSUE TITLE
Clay bee cannot be bred

### ISSUE THREAD

**Issue by dragagon** [GTNewHorizons/GT-New-Horizons-Modpack#5924]
#### Which modpack version are you using?
2.0.8.8

#
#### What did you try to do, and what did you expect to happen?
Tried to breed the clay bee. 

#
#### What happened instead? (Attach screenshots if needed)
I have a vanilla clay block under the apiary. I tried a hardened clay, a white painted clay and even bricks. 142 generations with 2 soul frames and I cannot get this bee to breed.

#
#### What do you suggest instead/what changes do you propose?
Need someone to take a look if its the block it expects. Minecraft:clay does not seem to work when the tooltip says it should.

**Comment by Prometheus0000** [comment]
Should be a dupe of #5816, which is fixed.

**Comment by dragagon** [comment]
Ah, i didn't see clay bees referenced at all, only titanium and a ton of others. Just need a release then.
