### ISSUE TITLE
[Railcraft] Steam Boiler uncorrectly structure

### ISSUE THREAD

**Issue by MotDT** [GTNewHorizons/GT-New-Horizons-Modpack#5926]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
#
[Steam Boiler](https://ftbwiki.org/Steam_Boiler_(Railcraft)) can not formed 2x2x2, 3x2x3 structure:
![изображение](https://user-images.githubusercontent.com/47714084/79388685-6c6a5d80-7f76-11ea-94ec-172517951f0c.png)
![изображение](https://user-images.githubusercontent.com/47714084/79389963-8bb5ba80-7f77-11ea-8e1b-615d1ee21612.png)
#
Need to change a description and quest or configuration RC.

**Comment by Anarack** [comment]
If you notice, the tool tip refers specifically to the boiler tank, not including the fireboxes, the quest most likely follows railcrafts descriptions.
