### ISSUE TITLE
[GregTech] Depleted thorium rod recipes are inconsistent

### ISSUE THREAD

**Issue by Mogball** [GTNewHorizons/GT-New-Horizons-Modpack#5927]
#### Which modpack version are you using?
2.0.8.3
#
#### Description of the issue
Depleted thorium fuel rods of any kind can be put into thermal centrifuges to get some thorium back plus 0.5 Lutetium per rod. However, only single depleted thorium rods can be put into a regular centrifuge to obtain additional byproducts (Th-232, Po, Tl, etc.).

Moreover, the rate of Lutetium becomes 0.125 per 8 rods, 32 times lower!
#
#### What do you suggest instead/what changes do you propose?
 Dual and quad depleted thorium rods should also have centrifuge recipes and the lutetium gain should be consistent.

**Comment by chochem** [comment]
dual and quad rods not having recipes has been declared an _intended mechanic_ by the mod author even though it is pretty weird.  see #5879,  #4826

**Comment by Mogball** [comment]
Gotcha. Thanks.
