### ISSUE TITLE
More Polybenzimidazole (PBI) Uses in Higher Tier Recipes 

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#5928]
+What is this tongue twister of a plastic? What are its uses? How can we implement further recipes in slightly logical ways? Do you get a cookie afterward? All the more answered, perhaps!

Polybenzimidazole, or often referred to as PBI, in real life it has "exceptional thermal and chemical stability and does not readily ignite." (-[Wikipedia](https://en.wikipedia.org/wiki/Polybenzimidazole_fiber) yes yes I know it's that site). With some imagination & magic, you can already begin formulating ideas as to what this can potentially accomplish.

In the case of GTNH and its uses inside of here, it is only used for a minuscule amount of **required** (no other poly substitution may be used) recipes; ZPM+ Machine Hulls, ZPM+ Input/Output Buses/Hatches, LuV+ Batteries (excluding Lapotronic Orbs, NeuroCPU's(?), Bio CPU, EV+ GT Solar Panels, and some other various recipes. As a result, the usage of it is barely negligible outside of the usage for GT Solar Panels and is only required as a few stacks worth to progress throughout most of IV+. For recipes that opt in to use PBI as an optional usage, then any Input/Output Bus/Hatch of IV or lower-tier may use this poly as a substitution for a large decrease in the amount required.

What can we do to help this almost neglected recipe?
A great way is to obviously find which recipes we should currently adjust, and if we should add **new** recipes that take on the usage of PBI to further increase the difficulty and or challenge of the game.

1. One excellent recipe to take on is the Thermal Cloth Tier 2. This recipe uses the following: 4 Titanium Foil (1 Titanium Ingot), 4 Tungsten Wires (1 Tungsten Worth), and 1 Thermal Cloth. Obviously, we could replace the foil with PBI foil instead, forcing a subtle usage, but a hard requirement of PBI before making the T2 suit.
![pufferfish58](https://user-images.githubusercontent.com/41557212/79425276-4d6bcb80-7f76-11ea-891b-bf2248feaae1.PNG)

2. Boots of the Voidwalker, Void Fortress and Shadow Fortress armor are generally considered one of the more extraordinarily powerful armor sets in the entire game, boasting powerful damage reduction, superior resistance to magic (potions) & fire damage, auto-repair (Void Fortress and Void Walker), and vis discount. Shadow Fortress is relatively the same, but its stats are increased to the extreme, yet it does not have the auto-repair mechanic. Voidwalker boots are of a similar nature to the Void Fortress, in that it provides similar resistance, durability, extreme speed(!), and auto-repair. With all of this in mind, the thought of rushing towards this armor as quickly as possible, even at the beginning of or late EV, is an amazing addition to survivability and traversing the environment as quickly as possible. As such, we could perhaps add PBI plates or double or even triple plates to the recipe to give it a sense of high value and tiered progression, while still somewhat being in the realm of possibility in obtaining it at mid to late EV (earliest possible).

3. Advanced SMD Parts, although while perhaps not logical in the manner that PBI being used for SMD parts, it could serve as a new potential for difficulty & challenge later on, as well as new materials instead of the regular SMD components; Copper, Electrum, Gallium, Platinum, and copious amounts of Polyethylene that we all know and love. These advanced parts may be used for higher tier recipes that require higher-tech to progress. There may be potential for this to be used for lower-tier circuits, but large batch crafting processes. Obviously, the amount can be adjusted to fit the desired requirements.
Advanced SMD Resistor: 4 Carbon Dust or 4 Graphene Dust, 32 Fine Platinum Wire, 288L of PBI = 64 A-SMD Resistors
Advanced SMD Diode: 16 Fine Niobium-Titanium Wires, 1 Indium Gallium Phosphide Dust, 288L of PBI = 64 A-SMD Diodes
Advanced SMD Transistor: 4 Vanadium Gallium Foils, 32 Fine HSS-G Wires, 288L of PBI = 64 A-SMD Diodes
Advanced SMD Capacitor: 4 PBI Foils, 8 HSS-S Foils, 144L of PBI = 64 A-SMD Capacitors

These are perhaps some rough general ideas, a gear to help shift a movement towards a transition of new high tiered recipes, a new difficulty, and new challenges. If you have any general thoughts or ideas, please do paste them.

**Comment by AiramProvoker** [comment]
Piky with thought-out suggestions. Never change.

**Comment by 0lafe** [comment]
LuV hulls should use PBI
