### ISSUE TITLE
Ore and Oil rigs missing recipes.

### ISSUE THREAD

**Issue by Houstonruss** [GTNewHorizons/GT-New-Horizons-Modpack#5929]
#### Which modpack version are you using?
 2.0.8.9dev

All Ore and Oil Drilling rigs have no recipies.

**Comment by Dream-Master** [comment]
they have assembler recipes

**Comment by Houstonruss** [comment]
Even the MK1s don't have recipies. I can only see scanner recipies for the void miners.

**Comment by Dream-Master** [comment]
The recipwe are in code but not visible idk why.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/0846d776777342fcfdc84cbea7dcb9ef980da896
https://github.com/GTNewHorizons/GT5-Unofficial/commit/fcc29fa66ffd1ce2880c6896730f8cc3fff37a9f
