### ISSUE TITLE
placing dimensional tranciver crashes client

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5930]
#### Which modpack version are you using?
8.9 dev4
#
#### If in multiplayer; On which server does this happen? 
mp
#
#### What did you try to do, and what did you expect to happen?
place down dimensionel tranciever
#
#### What happened instead? (Attach screenshots if needed)
client crashed
[crash-2020-04-16_20.51.41-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4489337/crash-2020-04-16_20.51.41-client.txt)

#

**Comment by Dream-Master** [comment]
@Zoko061602 we need help here

**Comment by Dream-Master** [comment]
fixed
