### ISSUE TITLE
Dimensional transceiver recipe

### ISSUE THREAD

**Issue by Houstonruss** [GTNewHorizons/GT-New-Horizons-Modpack#5931]
#### Which modpack version are you using?
2.0.8.9
 Dimensional transceiver recipe has been turbo nerfed from EV to ZPM. Stellar capacitors require gravistars, which require neutronium.

Endertanks and chests are still IV.

Suggestion to revert the recipe, make the capacitors EV, or use lower tier capacitors.

![image](https://user-images.githubusercontent.com/50430417/79499173-8b113880-7ff8-11ea-9410-d64e23a051a2.png)
![image](https://user-images.githubusercontent.com/50430417/79499200-949aa080-7ff8-11ea-90b0-cd07197552c0.png)

**Comment by GeicowithaBango** [comment]
additionally to that the stellar alloy armor (a very important ingredient for this recipe) is also in a state of need D:

**Comment by Dream-Master** [comment]
Same as for the other teleporting devices (Telepad Charm)we need to discaussed which item have to be in which tier.

**Comment by repo-alt** [comment]
It is not a player teleporting device, it is a kind of intelligent EnderChest. IV maybe, but ZPM?

**Comment by Prometheus0000** [comment]
You can send/receive items+fluids+RF. You can't change the RF back to EU though. It's basically the same as the Thermal Expansion Tesseract.

**Comment by Dream-Master** [comment]
iv is a good tier. Will  change it

**Comment by Houstonruss** [comment]
Should leave it EV because it is worse than enderchests and tanks.

**Comment by repo-alt** [comment]
Worse? Why?

**Comment by Houstonruss** [comment]
Functionally works more like a pipe / duct than a chest/tank. Requires energy to work, ender stuff doesnt.

**Comment by repo-alt** [comment]
IV lootbags I think. Requires energy yes, but combines energy/item/fluid transfer in one block. I would not say it is worse, it is just different.

**Comment by Houstonruss** [comment]
Also it was EV before the recipie got changed.

**Comment by Dream-Master** [comment]
IV now

**Comment by botn365** [comment]
thats still ZPM melodic capacitors need melodic alloy
melodic alloy needs mystrius crystal wich is T5 rocket

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/6b4489fd736fd2ded206ef043caa09d720e2f67d
