### ISSUE TITLE
Quest bugs on 2.0.8.8

### ISSUE THREAD

**Issue by FilizFiliz** [GTNewHorizons/GT-New-Horizons-Modpack#5933]
#### Which modpack version are you using?

2.0.8.8
#### If in multiplayer; On which server does this happen? 
Private

**The following quests aren't detecting**
_Quest ID - Quest Name (Quest Item) [Quest Tab]_

- [ ] Quest ID 5 - Tools (Shovel) [Tier 0 - It Begins]
- [ ] Quest ID 497 - Lit way to get charred (Charcoal Pile Ignitor) [Tier 1 - Steam]
- [ ] Quest ID 501 - Go find some bees (Princess, Drone) [How to be(e)]
- [ ] Quest ID  562 - High pressure boiler tank (High pressure boiler tank) [Multiblock Goals]
- [ ] Quest ID 649 - Coal steam jetpack (Solid Fueled Boiler Firebox, Electric Motor (MV)) [Armors and Jetpacks]
- [ ] Quest ID 784 - It's time to get more steam (Large Bronze Boiler) [Multiblock Goals]
- [ ] Quest ID 1560 - Witchery Seeds (Garlic) [Fishing Farming Cooking]
- [ ] Quest ID 1888 - Repairing your Hazmat Suit (Soft Mallet) [Tier 1 - Steam]

**Comment by wlhlm** [comment]
Can you be more specific about what do you mean by bugs?

NBT issues?

Which subtask is broken?

For example, quest 562 (High Pressure Boiler Tank) has recently been fixed, I've tested it. See #5652.

**Comment by FilizFiliz** [comment]
**wlhlm**, quests aren't detecting specified items. Btw another version here.

**Comment by FilizFiliz** [comment]
**Dream-Master** Im just playing on server with other players, who have the same problems with quests.

**Comment by Dream-Master** [comment]
@FilizFiliz i fix a few quests not ignore nbt now all quests does.

**Comment by Dream-Master** [comment]
@FilizFiliz try with 2.0.9.0 when it is out.

**Comment by Dream-Master** [comment]
or use this version and remove rf expansion.

**Comment by Dream-Master** [comment]
http://jenkins.usrv.eu:8080/job/BetterQuesting/18/
http://jenkins.usrv.eu:8080/job/StandartExpansion/11/
