### ISSUE TITLE
EIO Basic Item filters

### ISSUE THREAD

**Issue by Houstonruss** [GTNewHorizons/GT-New-Horizons-Modpack#5934]
#### Which modpack version are you using?

2.0.8.9dev

Basic item filters from EIO that have been configured, will be cleared after updating. This will break bases and cause headache. At this point I would reccomend going through the whole of EIO to balance new recipies and prevent issues.

**Comment by quedral** [comment]
this caused vac nuke explosion. just fyi.

**Comment by Houstonruss** [comment]
> this caused vac nuke explosion. just fyi.

If I wasn't using advanced item filters i would have the same problem. FYI, you should always use thermal monitors on your reactors to disable them if they get hot. That's the only thing you need to save a base and sop many people just want a crater instead!

**Comment by mitchej123** [comment]
What items were you filtering?

**Comment by Houstonruss** [comment]
Coolant cells most likely.

**Comment by GeicowithaBango** [comment]
in general, all the item filter we had were resetted after updating to .9 dev :/

**Comment by mitchej123** [comment]
If you want help, I need specifics.

**Comment by GeicowithaBango** [comment]
judging by the chat history of #github issues this is already fixed, isnt it?

**Comment by Dream-Master** [comment]
should be fixed in last dev version

**Comment by Prometheus0000** [comment]
Are the advanced ones fixed as well? #5853

**Comment by quedral** [comment]
> > this caused vac nuke explosion. just fyi.
> 
> If I wasn't using advanced item filters i would have the same problem on 16 reactors. FYI, you should always use thermal monitors on your reactors to disable them if they get hot. That's the only thing you need to save a base and sop many people just want a crater instead!

You are absolutely right however one doesn't expect the filters getting cleared "magically"

**Comment by mitchej123** [comment]
Bugs happen as new features are introduced and old bugs are fixed.

![image](https://user-images.githubusercontent.com/1894689/79602994-5f498d80-80a0-11ea-88b8-2ba0bef850af.png)

**Comment by GeicowithaBango** [comment]
ah yes, refreshing old men humor :p
