### ISSUE TITLE
Arcane Assembler Uncraftable

### ISSUE THREAD

**Issue by Houstonruss** [GTNewHorizons/GT-New-Horizons-Modpack#5937]
#### Which modpack version are you using?

2.0.8.7

Arcane assembler uncraftable because wand ID in recipie is wrong.
![image](https://user-images.githubusercontent.com/50430417/79614599-d8f87000-80ce-11ea-8d6d-daf74fe7e227.png)
This is what you can actually craft ingame.
![image](https://user-images.githubusercontent.com/50430417/79614575-cbdb8100-80ce-11ea-8659-f24a5c5cb8ea.png)

**Comment by Dream-Master** [comment]
@TimeConqueror maybe another id missmatch

**Comment by Houstonruss** [comment]
[Thaumic-Energistics.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4495265/Thaumic-Energistics.zip)
