### ISSUE TITLE
OC power convertor does not want to craft

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5938]
#### Which modpack version are you using?
8.7
#
#### If in multiplayer; On which server does this happen? 
mp
#
#### What did you try to do, and what did you expect to happen?
tried making the OC power convertor
#
#### What happened instead? (Attach screenshots if needed)
assemler dint want to make it
#
#### What do you suggest instead/what changes do you propose?
![afbeelding](https://user-images.githubusercontent.com/42187820/79617596-2513d680-8108-11ea-91e0-e90be4983551.png)
![afbeelding](https://user-images.githubusercontent.com/42187820/79617619-34931f80-8108-11ea-9fe5-848d98297f51.png)

**Comment by repo-alt** [comment]
Tested in 2.0.8.9.dev4, works fine. Are you sure there is polyethylene in the fluid input slot?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/79643188-1548d080-81a2-11ea-9d52-8ce085c917b2.png)
works fine

**Comment by botn365** [comment]
tried it agian in SP and the sever and now it works
