### ISSUE TITLE
Twilight Forest WorldGen Ticking Chunk Crash

### ISSUE THREAD

**Issue by Tuxprogrammer** [GTNewHorizons/GT-New-Horizons-Modpack#5939]
#### Which modpack version are you using?
GTNH (v2.0.8.3)
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Went to twilight forest, tried to explore swamp after defeating hydra.
#
#### What happened instead? (Attach screenshots if needed)
Full crash to desktop, world state isn't saved to disk.
#
#### What do you suggest instead/what changes do you propose?
Fix bug in twilight forest worldgen

#### What additional mods do you have loaded?
- Iron Chest Backpacks
- WorldEdit Forge
- WorldEdit Forge CUI

Logs:
https://gist.github.com/Dream-Master/c1ef16fc9021fad0f3801a0991ae1da2

**Comment by Tuxprogrammer** [comment]
Possibly related to #5504 and #5810

**Comment by Dream-Master** [comment]
@Tuxprogrammer please use gist or pastebin for logs. Thanks

**Comment by Dream-Master** [comment]
@jss2a98aj is this fixed allready?
