### ISSUE TITLE
missing Carpeter receipt

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#5940]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
ftb
#
#### What did you try to do, and what did you expect to happen?
used NEI for searching receipt of some carpeter blocks
#
#### What happened instead? (Attach screenshots if needed)
-> no receipt shown
![missing_Carpeter_receipe](https://user-images.githubusercontent.com/7759876/79628988-f7e61900-8145-11ea-9831-ba171d03cdb9.JPG)

#
#### What do you suggest instead/what changes do you propose?
working receipt

**Comment by Houstonruss** [comment]
You get all of those by placing the carpenter block wedges in certain orientation. Also try holding a wedge and shift+m3 to change.

**Comment by Ngar1** [comment]
thanks!
