### ISSUE TITLE
wish for carpeter or architect receipt/block

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#5941]
#### Which modpack version are you using?
2073
#
#### If in multiplayer; On which server does this happen? 
ftb
#
following blocks, prefered in carpeter mod, but also architect mod ok
very liked:
- halve slope
- 3/4 slope
- dual halve slope
- dual 3/4 slope

nice:
- round with 3 blocks (like arch block of architect - but outside rounded)
- round with 4 blocks (like arch block of architect - but outside rounded)

**Comment by Ngar1** [comment]
is there a chance, that this could realized?
Who I should ask for this?

**Comment by repo-alt** [comment]
Can't say I really understand what do you ask.

**Comment by Ngar1** [comment]
Gibt es jemanden im Team, der diese Erweiterung umsetzen kann und wenn, wen müsste ich ansprechen?
Thats in german, what i mean..

**Comment by repo-alt** [comment]
Eh, I don't understand not your last comment (which is clear enough) but the ticket contents.

**Comment by Ngar1** [comment]
As example I would like to get halfe high and 3/4 slopes in Carpeter mod or Architect mod which are a part of the modpack.

**Comment by Prometheus0000** [comment]
So you're saying you want new mods added? Post links to them first, then we'll consider if it's worth it

**Comment by Prometheus0000** [comment]
If you want it reopened get someone else to say what it is you want, minimum. I can't understand what it is you're asking for.
