### ISSUE TITLE
wish for disass/pulverisator receipt for catwalk receipt

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#5942]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
ftb
#
![catwalk_disass](https://user-images.githubusercontent.com/7759876/79629246-43012b80-8148-11ea-8ede-52ed4052b119.JPG)
1= 6x small steel dust
2= 3x steel dust
3 and 4= 2x steel dust (or 10 small steel dust)
5= 2x steel dust
6= 2x small steel dust

(alle rezepte abgerundet)

**Comment by Dream-Master** [comment]
Your material counting is wrong but i add recipes now.

**Comment by Ngar1** [comment]
Danke :-)
