### ISSUE TITLE
Quest 1197 - NBT issue

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#5944]
#### Which modpack version are you using?
2.0.8.8
#
####

Quest 1197 (Fusion reactor MK2 - bigger, better, fusor) does not recognize the Fusion Coil Blocks (2nd task) due to NBT problems.

**Comment by Dream-Master** [comment]
will check

**Comment by chochem** [comment]
that was fixed at some point
