### ISSUE TITLE
Cannot mine diamonds with bronze pickaxe

### ISSUE THREAD

**Issue by seanparko** [GTNewHorizons/GT-New-Horizons-Modpack#5945]
#### Which modpack version are you using?
Current Version on twitch
#### If in multiplayer; On which server does this happen? 
A small server for me and my friends which I set up.
#### What did you try to do, and what did you expect to happen?
To complete the macerator quest, you need diamonds. In my save file, diamonds are a tier 4 ore, yet every time I make a bronze pickaxe it has a mining tier of 3, meaning I can't aquire diamonds. I can't get steel to get around this problem, as a blast furnace requires stone dust which requires a macerator
#### What happened instead? (Attach screenshots if needed)
I can't get steel to get around this problem, as a blast furnace requires stone dust which requires a macerator. I can no longer continue the questline.
![Fully Assembled Pickaxe](https://user-images.githubusercontent.com/29669307/79678522-c81b3c00-823f-11ea-800c-fc44655501a6.PNG)
![Bronze Pickaxe Head in NEI](https://user-images.githubusercontent.com/29669307/79678523-ca7d9600-823f-11ea-9a8a-b189bda90f99.PNG)
![Bronze Pickaxe in NEI](https://user-images.githubusercontent.com/29669307/79678525-cbaec300-823f-11ea-9ecc-2a6d50148a2a.PNG)

#### What do you suggest instead/what changes do you propose?
I've seen in youtube videos and in the tinkers construct book that a bronze pickaxe has a mining tier of 4. Could you please explain how to fix it?

**Comment by chochem** [comment]
the mining level gets boosted by +1 after using the pickaxe a bit (press shift for details). alternatively some mob heads let you skip that and get the boost directly.

by the way: the discord might be better for simple questions like that.

**Comment by Dream-Master** [comment]
upgrade your pick with head or levels and you can mine diamond
