### ISSUE TITLE
EBF - Silicon Ingot Recipe Misconfigured

### ISSUE THREAD

**Issue by vorvac** [GTNewHorizons/GT-New-Horizons-Modpack#5946]
#### Which modpack version are you using?
2.0.8.8 - MMC
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Alternate EBF recipe for Silicon Ingot shows an output of 2000L of Carbon Monoxide, however the EBF is only outputting 100L per ingot.

![Screenshot from 2020-04-18 23-09-25](https://user-images.githubusercontent.com/17916889/79679230-a2684580-81f3-11ea-8788-687c9834d0f3.png)

#
#### What do you suggest instead/what changes do you propose?

It seems 2000L of CO would make sense, given SiO2 + 2C -> Si + 2CO

**Comment by Dream-Master** [comment]
each hatch tier it gives out more fluid. This is intended and not a bug.

**Comment by vorvac** [comment]
Any way it can show in the recipe? How to figure out how much per tier?

**Comment by chochem** [comment]
check the muffler hatch tooltip

**Comment by Dream-Master** [comment]
guess uv = 100%

**Comment by vorvac** [comment]
Muffler hatch..got it

**Comment by vorvac** [comment]
Thanks for the info. My mistake
