### ISSUE TITLE
Replicator Nerf 

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5948]
So in order to prevent a stealth nerf here I think it's important to discuss this in the primary github page most people look at. Everyone ready for some maths? Good uwu.

There has been a change in a recent commit to how the UUM cost of each replication recipe is calculated, it currently costs x UUM to replicate an element and under the new scheme it will cost x^(a) where a is the value we need to decide. To give you an example of why this value needs to be so carefully selected I show you the following table...

| Resource  | Base UUM cost  (L) | a = 1.1 | a = 1.125 | a = 1.333 | a = 1.5 | a=2 |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| Indium  | 114  | 183 | 206 | 552 |1217 | 12996 |
| Osmium  | 190  | 321 | 366 | 1092 | 2619 | 36100 |
| Iridium  | 192 |324 | 370 | 1107 | 2660 | 36864 |
| Ruthenium  | 101 | 160 | 180 | 470 | 1015 | 10201 |
| Lutetium  | 174 | 291 | 331 | 969 | 2295 | 30276 |
| Europium  | 151 | 267 | 304 | 874 | 2043 | 25921 |
| Americium  | 245 | 425 | 487 | 1530 | 3835 | 60025 |
| Flerovium  | 289 | 509 | 586 | 1907 | 4913 | 83521 |
| Boron  | 10 | 13 | 13 | 22 | 32 | 100 |

Any input on what exactly a should be set to would be extremely helpful, thanks for attending my TED talk.

**Comment by Houstonruss** [comment]
This only slows the game down more. Why don't we buff the problematic processes to incentivize people to use them over UUM bad?  Give a better indium yield from galena? Make Thorium breeding for reactors faster/more efficient? Adjust the yield of osmium from plat processing so you're not left with AYYLMAO amounts of iridium?

**Comment by SampsaxD** [comment]
Here's some of the exponents graphed out. The vertical lines are some common replicated materials:
https://i.imgur.com/ZKqWDqB.png

**Comment by 0lafe** [comment]
Is a static between all materials or specifically set per element?

**Comment by GTNH-Colen** [comment]
> Is 'a' static between all materials or specifically set per element? If a is the same for all elements, unless we can also change the base value raised to a, this isn't that useful.

"a" is static across all UUM recipes, it's just a limit of GT for some reason I don't quite understand why.

**Comment by sthegreat** [comment]
looks like there is a spot where you can override the value a exponentiates (which is just the material atomic mass number); not sure if that's also new or if I was just blind when I read thru this stuff earlier.

**Comment by SKYCATV587** [comment]
UU arent a cheap thing , Dont for difficult to change to difficult,its very sutpid,Its not as good as delete uu.if you want to Adjust game balance ,or you can change how much energe to make uu rather than let it cost more uu. the cost is follow Atomic number

**Comment by SKYCATV587** [comment]
If this thing is really installed，im afraid of i will add a Underground Oil in my server,Otherwise, i can't play at all
![image](https://user-images.githubusercontent.com/41377439/79770810-7c13e880-8360-11ea-84b5-95aa13d1b1f7.png)

**Comment by Glease** [comment]
Take it easy. Bart's PR included a config for tuning this. If you (and probably myself as well) don't like the nerf, you can just set that value to 1 and this change will not affect your server.

And yet, unless you make UUA something stupidly hard to acquire and make UUA mandatory, this will only change *afk for 1 hour* into *afk for 2 hour*. I sincerely don't see why this change would be necessary, unless someone wants UUM to be the next stargate.

**Comment by GTNH-Colen** [comment]
Mostly concerned about this impacting lower tier players honestly, as a fairly developed player I can fairly easily afford to just quadruple my UUM generation and basically ignore this nerf but for new players clawing their way up this will hit really hard.

**Comment by Prometheus0000** [comment]
Wouldn't you be fairly far when you start producing UUM anyway? The first thing you would want to UUM would be indium, right? And you only start using that in IV. You should have a bunch of good power options by that point if you really need to go the UUM route, I would think.

**Comment by bartimaeusnek** [comment]
UUM was never a smarter or faster option compared to the alternative routes, this makes it even more unlikely to be used, in comparison with automated setups.

**Comment by Glease** [comment]
FYI GTNewHorizons/GT5-Unofficial#269 is the corresponding pull for this issue. There you can check how the proposed change works exactly.

**Comment by quedral** [comment]
> UUM was never a smarter or faster option compared to the alternative routes, this makes it even more unlikely to be used, in comparison with automated setups.

some resources are too scarce or takes tremendous amount of time to gather other ways. Make them more available if you are going to nerf uum to the ground.

**Comment by chochem** [comment]
@Prometheus0000 Indium pre T3 fusion is definitely pretty bad outside of uum. Making it 5-6x more expensive is rough. Buffing the alternative processes would not be a bad idea.

**Comment by combusterf** [comment]
> UUM was never a smarter or faster option compared to the alternative routes, this makes it even more unlikely to be used, in comparison with automated setups.

I think this whole discussion shows that replication is very much a viable strategy: Nobody likes to keep roaming the nether and TF for the base ores, and you need like a vein of each per stack of indium, and you get denied the other byproducts. One team on Delta mined every rare vein on Ross in a kilometer radius to get their fusion reactor done - so much for the next person who has to go through that.

I've also done the platinum group metals - it needed 3 chunks full of machines.

And then the replicator is just one block. It's extremely predictable and care free. And the question of it being slow is rather: is it faster than spending all this labour on these "how it was meant to be" processes?
In my case, letting the replicator chug along on spare power for one full week to get that one stack of indium was preferable over mining for hours on end. Is that bad design? Your choice.



But I think it's good that the underlying problem is now exposed: we can turn the 1 tiny indium from sphalerite into 3-5, we can give the Ross vein in question some extra indium as the byproduct, give osmium ratios and lutetium some love too, then the reasons why everybody is using the replicator as a stopgap measure against design excesses should be covered.

**Comment by Prometheus0000** [comment]
This already happened, did this still need adjusting?

**Comment by GTNH-Colen** [comment]
No, a decision was reached and implemented.

**Comment by Dream-Master** [comment]
no it was in a test run to see it it need more nerf or not.

**Comment by Prometheus0000** [comment]
Think it was good, right?
