### ISSUE TITLE
Search for a solution: Solar wiring burns at chunk borders

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#5949]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do?
Solar on roof -> wiring burns afer some days. 
I use up to 32A wiring to a 16A input transformer 
I tried superconductor and standard wires.

![Solar_Chunkgrenzen](https://user-images.githubusercontent.com/7759876/79692470-a5038300-8265-11ea-8e5c-13a050ce0060.JPG)

#
#### What do you suggest instead/what changes do you propose?
wiring should only transport maximum amperage of  the sink, in every case.

**Comment by boubou19** [comment]
is the server running Thermos? because if yes then you'll have no choice but use machine hulls/battery buffers/diodes/energy distributors at chunk boundaries. This occurs because thermos runs chunks at different speeds and it happens on Delta, Epsilon and Eta as well.

**Comment by richardhendricks** [comment]
Are you chunkloading both chunks? Otherwise, as Bou said, the problem is uneven # of ticks per chunk

gen  --->  >--- machine

At gen, it scans out to machine, and sees it has space to receive amps. It sends the max amps it can each tick. But if the wire on the >--- cannot accept that many amps, it will catch fire when it ticks.

gen ---> >BB----machine

If you put a batbuff on the receiving border with matching batteries for the BB---machine link, it will accept 2x the amps from the generator, and put out 1x the amps for the machine without issues.

**Comment by bartimaeusnek** [comment]
I made the diodes especially for this usecase.

**Comment by Dream-Master** [comment]
@bartimaeusnek use my new asmd items for high tier diodes

**Comment by Ngar1** [comment]
burned also in a chunk: 
the marked cable (HSS-G 4x) was burned today in a chunk (see green grid)
![Solar_ohne_Chunkgrenzen](https://user-images.githubusercontent.com/7759876/80720069-adc54600-8afc-11ea-8f2a-b9482db375d0.JPG)

**Comment by KaneHart** [comment]
I know this is a bit old. Have you tried setting skip-tileentity-ticks: false instead of true in the tileentities.yml file? This sounds like more of what would cause this if enabled.

Description: If enabled, turns on tileentity tick skip feature when no players are near.

**Comment by Prometheus0000** [comment]
Is there anything to fix here? You just have to deal with thermos being thermos, right?

**Comment by Prometheus0000** [comment]
I looked at the picture, so let's try this again. Does this still happen? In SP? Only MP? Non-thermos servers?

**Comment by boubou19** [comment]
this is a thermos issue, happens from time to time on the officials when players incorrectly chunkload their base. Disabling the skip tileentity ticks does help, but does not totally fix the issue. So unless the GT cables are reworked, this will always happen on thermos server.
