### ISSUE TITLE
Harvestcraft machines do not work as intended

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/GT-New-Horizons-Modpack#5950]
#### Which modpack version are you using?
2.0.8.3

#
#### If in multiplayer; On which server does this happen? 
Singleplayer

#
#### What did you try to do, and what did you expect to happen?
Put salt and fresh milk in churn (obtainable through quest 1836), expected to turn into butter

#
#### What happened instead? (Attach screenshots if needed)
It did not. Churn only uses harvestcraft's salt, and this salt automatically convertes to gregtech's salt.

#
#### What do you suggest instead/what changes do you propose?

Make it so churn will use gregtech's salt and\or eadible salt.

Also, optional suggestions about machines from quest 1836: 
a) It would be nice to have harvestcraft cheese recepie added to churn alongside with butter
b) Quern use pressure plates to press some food into "dusts". It make sence in context of vanilla, as pressure plates are just two pieces of stone. However, in context of GTNH, they are somewhat complex machines, that are crafted with springs and screws, that are not needed to press wheat into flour. Would be nice if quern could work just by using stone and\or stone slabs.
c) Is there a reason for them to be not craftable?

**Comment by Dream-Master** [comment]
wait until we edit harvestcraft source and we can change it.
