### ISSUE TITLE
OSS from BetterQuesting is unable to submit items or fluids

### ISSUE THREAD

**Issue by TheOnlyRupert** [GTNewHorizons/GT-New-Horizons-Modpack#5952]
#### Which modpack version are you using?
2.0.8.9.dev4
#
#### If in multiplayer; On which server does this happen? 
My own
#
#### What did you try to do, and what did you expect to happen?
Items/liquids should be able to be submitted via the OSS from the "better questing" mod when a retrieval task (that consumes) is selected.
#
#### What happened instead? (Attach screenshots if needed)
No items/liquids are able to be submitted via the OSS. Whether that's through the GUI, with pipes, tanks, hoppers, etc. This is a problem in another modpack I play also.
In singleplayer, the GUI does save its state of the quest that was selected, in multiplayer, the quest gets reset to the default quest when first opening the GUI.

BetterQuesting-3.0.322.jar
StandardExpansion-3.0.174.jar
also tried:
BetterQuesting-3.0.325-GTNH.jar
StandardExpansion-3.0.176-GTNH.jar
#
#### What do you suggest instead/what changes do you propose?
Make the OSS able to submit items and liquids.

**Comment by Dream-Master** [comment]
@TheOnlyRupert we have new versions try out the lastest
http://jenkins.usrv.eu:8080/job/BetterQuesting/
http://jenkins.usrv.eu:8080/job/StandartExpansion/

**Comment by TheOnlyRupert** [comment]
Issue still persists using the new versions. 
NOTE: I changed the first quest (when you acquire dirt) to consume 800 dirt. This quest worked and allowed me to use a hopper to turn in the dirt blocks. I created another quest to turn in gravel and this did not work.
However, even with the GUI showing gravel, when I put dirt in the hopper, it submitted to the first quest. So it seems to be "stuck" only at the default quest that the GUI shows.

BetterQuesting-3.0.330-GTNH.jar
StandardExpansion-3.0.179-GTNH.jar

Also RFExpansion-3.0.29.jar crashes during startup with the new versions.
[crash-2020-04-19_17.05.14-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4500402/crash-2020-04-19_17.05.14-client.txt)

**Comment by Dream-Master** [comment]
@TheOnlyRupert rf expansion need an update first.
@funwayguy any idea on this issue. Are you need a ticket on your side ?

**Comment by Dream-Master** [comment]
@TheOnlyRupert 
try with this versions and report if it works
http://jenkins.usrv.eu:8080/job/BetterQuesting/21/
http://jenkins.usrv.eu:8080/job/StandartExpansion/14/

**Comment by Dream-Master** [comment]
@TheOnlyRupert any news here?
