### ISSUE TITLE
Add Polution to non-GT-TileEntitys via Mixins

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#5953]
- [ ] Make pollution affect garden soil
- [ ] Anything else that burns stuff (very low prio)
- [x] Railcraft Boiler

- [x] Thaumcraft Coal Burning Devices (low prio)
- [x] Rockets (low prio)

- [x] Coal Engine (very low prio)
- [x] Furnaceses (very low prio)

**Comment by GTNH-Colen** [comment]
I'd rather see pollution be more challenging than just forcing it into more machines, you can essentially totally ignore it by the time you get a hazmat suit/nano (HV).

**Comment by mitchej123** [comment]
> I'd rather see pollution be more challenging

Please propose some ideas.  If they're not too annoying to implement we're open to considering them.

**Comment by Houstonruss** [comment]
biters when

**Comment by Prometheus0000** [comment]
Here are some ideas, some are not really realistic, or likely to be accepted admittedly.

Fog that increases with pollution (always active), eventually effectively being the blindness effect.
Reducing max hearts (temporary, but really long effect), also keeps reducing up to 1 heart left
Increasing amounts of hunger, or something similar
Directly taking damage
Adding warp
Chance of mob spawning, even in light (probably a new mob, like a pollution cloud, or dirty slime or something)
Some kind of 'nature lover' mob spawns, and tries to kill you (boss)
Placing some kind of 'sludge' block or fluid randomly
Killing bees
Making machines really loud
Adding 'dirtiness' textures to everything around randomly on top of existing ones
Sending chat messages to shame you
Changing light level required for mobs to spawn
Biome changes
Reduced machine speed, reducing more as it gets worse
Increased machine EU cost, increasing more as it gets worse
A chance for cables/pipes to randomly disconnect (this would cause explosions, so probably not)
Low chance of voiding at high levels of pollution
A chance for machines to 'break' and revert to casings at really high levels
Make coils effectively tier-1
Make DTs only output some of the normal outputs
Have programmed circuits revert to 0
Have cleanroom void 100% if any pollution
Interfering in wireless redstone signals
Make OC computers not work (they're complex computers after all)
Similar to above, but SFM, tectec, other stuff maybe
Add chance for hungry node to spawn (they don't eat tile entities, right?)

**Comment by leagris** [comment]
Here are my options:

- Randomly replace air blocks with unbreathable invisible suffocating gas fluid blocks that very very slowly (as slow as oil but upward like ThermalExpansion molten Glowstone flow up). Would not affect you with a space suit.
- Alternatively to the above, just randomly suffocate for a few seconds any living entity (including animals)
- Spread biome change to the next dryer hotter biome
- Cancel all plant growtgh ticks including crops
- Rain/Storms causes all living entities to take damage and armor pieces to get damaged if entity receives rain (open sky). Supposedly acid rain. Trees looses leafs, plants/crops dyes.
- Radioactive Cockroaches can spawn when you break/wrench out any block/
- Random blocks turns to falling block and fall if unsupported

**Comment by bartimaeusnek** [comment]
can we PLEASE move that to another ticket?

**Comment by Anarack** [comment]
#5954

**Comment by draknyte1** [comment]
RC logic is janky to tad pollution to from memory.

**Comment by Prometheus0000** [comment]
Can be discussed after pollution change is decided.
