### ISSUE TITLE
[Sense] uncorrectly working

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#5956]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
#
it continues  #4761 issue
#
- Sense excavating 5x5x5 i.g. dirt, gravel, stone ..
- Using right click harvest not IC2 crops, destroys blocks under it i.g. mods Natura, Pam's
#
https://youtu.be/pc89m3ovEgo

**Comment by GTNH-Colen** [comment]
At least it doesn't break bedrock anymore? lmao

**Comment by MotDT** [comment]
> 
> 
> At least it doesn't break bedrock anymore? lmao

Yes, only basic block i.g. dirt, gravel, stone, wood..

**Comment by Cleista** [comment]
Still occurs on 2.0.9.0QF4

- [Try to harvest crops](https://cdn.discordapp.com/attachments/181078474394566657/728317113197920417/unknown.png)
- [Accidentally dismantle base instead](https://cdn.discordapp.com/attachments/181078474394566657/728317188267835401/unknown.png)

**Comment by bombcar** [comment]
How can I get this to occur? It doesn't seem to be triggering in 2.1.1.5pre - does it need particular blocks?

**Comment by bombcar** [comment]
I think https://github.com/GTNewHorizons/GT5-Unofficial/commit/42543040b0533d2cd714412efa29a51b75321bb6 fixed Most of this - it harvests bushes like the berry bushes instead of just picking the berries, but eh, that's not too bad.
