### ISSUE TITLE
++ Rocketfuel RFC

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5957]
#### Which modpack version are you using?
2.0.8.9

#### What do you suggest instead/what changes do you propose?

Rocketfuels got a fairly heavy change with 8.9, not all of it good imo. Some things that were already very good god buffed too much, while some underpowered fuels are still not great. I'll add all of them eventually, but first I'm going to talk about CH8NO3, or purple fuel. 

The primary changes here were two things. On one side, 3 of the steps in fuel gen got moved to the chem plant. However, in this move all ratios got improved to provide more fuel. Imo, the values for these should be as follows. 

2000L Hydrogen Peroxide + 2000L Ammonia -> 2000L Hydrazine (30v 320t)
2000L Hydrazine + 2000L Hydrogen + 2 C -> 3000L Monomethylhdrazine (240v 600t)
1000L Monomethylhydrazine + 1000L Nitric acid -> 2000L Purple Fuel (480v 400t)

This essentially reduces ratios to the previous values, while reducing the recent CP recipes times by a little. Puts purple in almost the same spot as before, but you loose a tiny bit more power to the CP steps than the previous centrifuge/CR/CD. As power lost isnt the main concern with rocket fuel though, this essentially makes the change to purple fuel simply one of requiring more CP usage. 

I'll update this with values for RP1/Green/Dense once I take a look at them, but any discussion about any fuel is appreciated. It would be nice to have a proper tiering without one being quite dominant. 

Also, this is posted in the ++ repo as well, however i think I'll get more responses here, so I've made this the main discussion.

**Comment by AiramProvoker** [comment]
You really should provide the values that are now and not just the ones you're suggesting. 
Also might as well show the values that were before the buff.

**Comment by 0lafe** [comment]
I was primarily targeting this to people who have used the fuels,  either currently or pre update, but I guess. Calling it pre change, pre pre change, current, and proposed change is gonna get a little confusing, so Ima give some names to these. 

R1 are recipes as they originally were, this means the stage that still consumed Li and had no CP. 

R2 would be values pre nh8.9, which is post first CP integration, but still has the final 3 steps in machines other than the CP

R3 is what values are in 8.9 currently, which are the ones I'm aiming to change

R4 will be for the values I'm proposing here, as possible future recipes

We can somewhat ignore R1 for now, but I think it's important to leave in for context about which values are which. 

R2's values for the recipes I'm aiming to change are this 

2000L Hydrogen Peroxide + 2000L Ammonia -> 2000L Hydrazine (30v 320t) Singleblock CR
1000L Hydrazine + 1000L Hydrogen + 1 C -> 1500L Monomethylhdrazine (240v 480t) Chemical Dehydrator
1000L Monomethylhydrazine + 1000L Nitric acid -> 2000L Purple Fuel (30v 640t) Centrifuge

R3 values are such

2000L hydrogen peroxide + 2000L ammonia = 4000L Hydrazine (120v, 30s, T1)
2000L H2 + 2000L hydrazine + 2 C dust = 4000L monomethylhydrazine (240v, 48s, T2)
1000L nitric acid + 1000L monomethylhydrazine in chem plant = 3000L purple rocket fuel (480v, 45s, T3)

R4 are the values in the top of the ticket

Energy gained isn't a super useful metric of how rocket fuel works, but if you don't want to do the math on it, this shows most of the setup 
https://docs.google.com/spreadsheets/d/16l_RXMlQ7k4PnjTp-EbMWdCird8gddAmBQgamFBtSdo/edit?usp=sharing
It has things unrelated to purple fuel alone, such as cryothium for the liquid H2, but it should demonstrate what you want to know about power. If you want to test it for different values, id recommend copying the sheet. Adjusting the quantity of Pyros on the first page ("Display") will adjust the production rate of fuel. All other processes will adjust themselves based on the pyro quantity.

**Comment by noobnoobnub** [comment]
BTW why there is duplicated recipe for dinitrogen tetraoxide (one from chem reactor, useless; and one from dehydration by copper). Speaking of which there is also duplicated recipe for potassium nitrate. Not sure is it is intended to use the dehydration recipe for dinitrogen tetraoxide for rocket fuel.
