### ISSUE TITLE
Suggestion: Steam Multis

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#5958]
Hey, since steam age is kinda only "rush to the LV" rn and bcs steam is fun, steam is life... :D Ok, just wanna said that steam was used for longer period and achieved a great success and allow multiple advancements. I thought about Steam Multis.

Not All of them ofc, but for example macerator, centrifuge, or mixer is just big spinning thingy and therefore it should be viable to get that in steam age. Yes it would be expensive for lower tiers but i present this as a merely suggestion to add some flavour or possibility to early parts of the game.

Lets say that most of materials would be bronze, brass, iron,steel, wood... an my idea is to make them bigger bcs they need to have own "boiler", start like MB steam turbines do and do more parallel processes. Downside would be need of fuel - solid/liquid and water. Dangers of live steam are obvious - kaboom. So for example if IV+centrifuge is 3x3x3 let say that steam version would be something like 5x5x3. Speed should be as fast as LP/HP steam stuff but let say 2x parallel if use bronze/brass, 4x steel... etc so speed cant be changed only parallel to the cap 8x. Sadly i cant programm that, but those machines sorta exists in IV+ form, so i hope it wont be as big issue to add them.

They should be optional and not mandatory , what do you think?

**Comment by leagris** [comment]
I fail to see this fit in any kind of practicality in GTNH. There is no point in making low tech Steam machine faster or process more stuffs because automation options, products and by-products choices are very limited. Fueling greedy large steam machines at this stage is also wholly impractical.

**Comment by Hyperic88** [comment]
I can hardly agree, since you can make multis at IV+ those would be useful up then, even at lower efficiency etc. and it would be good to batch processing stuff at HV (after upgraded basic steam version) to help you advance...

**Comment by quedral** [comment]
Diversity is good however it wouldn't be very practical. I am not sure if anyone would like to design/texture and code that unless you do that yourself which you are very welcome.

**Comment by Hyperic88** [comment]
Well, design and texture would be possible i think, but i can't code it unfortunately, simply bcs i do not know how :/

**Comment by repo-alt** [comment]
We even have stone age multiblock macerator, aka Bart's windmill, so it may easily fit the theme, but really, such things require some work to implement. You may try to sell the idea to Bart (or Kekz), especially if you will design & texture it yourself.
