### ISSUE TITLE
Jägermeiter tooltip umlauts

### ISSUE THREAD

**Issue by glowredman** [GTNewHorizons/GT-New-Horizons-Modpack#5959]
#### Which modpack version are you using?
2.0.8.8
####What happened?
The tooltip of the two Jägermeister items (Crops++) contain common umlaut-substitutions (ä -> ae, ö -> oe, ü -> ue).
#
#### What do you suggest instead/what changes do you propose?
Changing it in the code is not difficult (I did it on my own [fork](https://github.com/glowredman/crops-plus-plus/blob/master/src/main/java/com/github/bartimaeusnek/cropspp/items/CppPotions.java)) and would increase authenticity.

**Comment by Dream-Master** [comment]
@glowredman Jaegermister sound realy wrong for me. Only real with ä sorry.
JÄGERMEISTER

**Comment by glowredman** [comment]
Update: changing it to 'ä', 'ö', 'ü' in code did work for me in dev, but not as a build. With `\u` it worked for me though.

**Comment by bartimaeusnek** [comment]
@glowredman that mod was written when i had basically no idea what tf i was doing, so expect more unnessecary broken and redundant or extremly complicated stuff in there lol
