### ISSUE TITLE
2.0.9.0 Dev hazmat suit crash

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5960]
#### Which modpack version are you using?
2.0.9.0 dev with gt++ 1.7.05.53
#
Game crashes on launch due to hazmat issue, see log below:

[Log File.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4512494/Log.File.txt)

**Comment by Glease** [comment]
Is this still relevant?

**Comment by Glease** [comment]
Should no longer be relevant now as hazmat functionality has been removed from GTPP.
