### ISSUE TITLE
2 small adjustments for the platinum line processing 

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/GT-New-Horizons-Modpack#5961]
#### What do you suggest instead/what changes do you propose?
1.) lower the consumption of HCl for the acid iridium solution
2.)lower the recipe time of platinum/ palladium sifting 
those are two things I personally found that have to be optimized.

**Comment by GTNH-Colen** [comment]
Highly concur on point 1 at least, that process absolutely devours chlorine. In regards to point 2 i'm unsure, I use the GT++ sifter which greatly increases the sifting time so perhaps I just don't notice.

**Comment by 0lafe** [comment]
1. Maybe I havent made enough Ir yet, but HCl has never been an issue. What's your Cl gen rate? 

2. Im not sure I agree here either. It's probably the most energy consuming step. Imo its fine though. I was running a fairly under powered Pt chain for a while, and even then the outputs were pretty good. This would seemingly lower overall output powers by a decent bit depending how much it's lowered.

**Comment by GeicowithaBango** [comment]
we refined roughly 150k of iridium in the last few days. the hcl gen uses up to one amp of LuV for salt water electrolyzing.
the platinum sifting is an huge bottleneck for our general platinum processing/ consumption.

**Comment by 0lafe** [comment]
It'll be a bottleneck as it's the highest energy consumer. I'm not sure how that's bad though. You were able to make 150k Ir, that seems like it's fine? Also, 1A LuV for Cl? If youre running out of Cl or H2, you can make so much more than that if needed. No way you don't have a spare amp of zpm with mk2. 

Are you using 150k Ir in the time it took you to make it from Pt?

**Comment by GeicowithaBango** [comment]
Im guessing that most iridium comes from the rarest metal dust and its „pure“ Iridium equivalent. 
my concern is that due to the big aspect of platinum being very recursive to progress (sifting /recycling)-any given setup- will never be able to keep up with a proper miner, unless, as mentioned, without additional amps of zmp. 
i think that shouldnt be the case. 
sifting should never be that energy consuming

**Comment by 0lafe** [comment]
Does it need to keep up with a miner if you're getting more Pt/Ru/Rh/Pd/Os/Ir than you're using though? And what's wrong with sifting being the main power sink?

**Comment by GeicowithaBango** [comment]
if our platinum consumption would be low I wouldnt call it a bottleneck >:(

**Comment by Dream-Master** [comment]
> #### What do you suggest instead/what changes do you propose?
> 1.) lower the consumption of HCl for the acid iridium solution
> 2.)lower the recipe time of platinum/ palladium sifting
> those are two things I personally found that have to be optimized.

What values you suggest? @GeicowithaBango

**Comment by GeicowithaBango** [comment]
Hard to tell, 500L of HCl would be nice,is my first thought. (700L might be more appropiate)
The sifting time should definitely be decreased by half, if not more.
