### ISSUE TITLE
Unknown water as an underground fluid

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5963]
#### Which modpack version are you using?
2.0.9.0 DEV
#

Unknown water should have an underground fluid added, that or a recipe of some kind to produce it renewably. Being forced to pump real liquid blocks from the surface in mass quantities is both laggy for servers and frustrating for players, we haven't needed to do that since essentially LV for oil wells.

Also side note, can we rename "Unknowwater" to "Unknown Water" not sure if this is intentional or just because someone made a typo?

**Comment by Dream-Master** [comment]
if the liquid is from gs we can't because the mod is closed source. But we can add a new fluid with this name and make it as underground fluid on this planets.

**Comment by Prometheus0000** [comment]
Bucket of Unknown Liquid is from GalaxySpace, so I'd say it's from it.

**Comment by Dream-Master** [comment]
same for Seaweed extract i guess to avoid more lag ? @GTNH-Colen @Prometheus0000

**Comment by Dream-Master** [comment]
or this recipe better ?
![image](https://user-images.githubusercontent.com/2970688/80129067-dbf3d480-8596-11ea-9e8a-888854fdd741.png)
