### ISSUE TITLE
UnknownNutrientAgar takes too long (Biowares)

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5964]
#### Which modpack version are you using?
2.0.9.0 DEV
#

This recipe should either be cut to 20s or reduced to ZPM for the same effect (Or more), taking 80s at UV for a recipe you need in bulk is far too long and a disproportionate energy sink for the bioware line.

<img width="346" alt="Screenshot 2020-04-22 at 10 25 23" src="https://user-images.githubusercontent.com/54497873/79965178-9c889380-8483-11ea-864b-7091f2187abe.png">

For the full multiplier you need 1,600,000L of this stuff which seriously slows down the entire chain.

**Comment by botn365** [comment]
the bacterial vat recipe should be fixed to only use 50L instead of the 1600

**Comment by Dream-Master** [comment]
1600 where you see this level ? @botn365

**Comment by GTNH-Colen** [comment]
> the bacterial vat recipe should be fixed to only use 50L instead of the 1600

<img width="376" alt="Screenshot 2020-04-22 at 16 40 20" src="https://user-images.githubusercontent.com/54497873/80002787-015de100-84b8-11ea-85d3-763342eae876.png">

Looks like 1600L to me as of the latest dev version?

**Comment by Dream-Master** [comment]
change to 60 sec

**Comment by Dream-Master** [comment]
after i spoke with bart we let the other recipes like it is. When we find out balance is not good we can reopen this ticket.

**Comment by GTNH-Colen** [comment]
@Dream-Master This is still 3.3H at UV energy, that means you can only do 7.2 cycles per day or (7.2 * 50000/500)*32 = 23,040 seaweed per day. You need 33760L of growth stuff to get 1 UEV which is 54 seaweed extract roughly or 3456 seaweed (625mb per seaweed extract).


This means that you can only make 6.6 UEV circuits per day and keep in mind that there are a lot of high energy recipes in this line, not just this one UV recipe. This is clearly too low and becomes a major bottleneck for the entire recipe, we need to reduce it further. 


This is also assuming you are actually running the game 24/7, a lot of players play single player so balancing around a server is unfair. You'd potentially only make 1-2 UEV circuits per day if you were to play around 6 hours.


We don't need to wait, I can run the numbers and tell you this isn't fairly balanced right now.

**Comment by Dream-Master** [comment]
ok amount lowering to 50

**Comment by Dream-Master** [comment]
i close thus after release
