### ISSUE TITLE
[Fruits. Pam's Harvest The Nether] flying fruits

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#5965]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
#
 Cut down tree, fruits remain in air
![Screenshot_2](https://user-images.githubusercontent.com/47714084/79970701-feed8e00-849b-11ea-9e03-4cfbc7bcfff0.png)

**Comment by Dream-Master** [comment]
we not forked pams nether mod yet. Have to check if there is a repo.

**Comment by Ethryan** [comment]
ARR for Pam's harvest the nether: [Link](https://www.curseforge.com/minecraft/mc-mods/pams-harvest-the-nether)
No source available.

**Comment by leagris** [comment]
Anyway, the issue might not even bi in Harvest The Nether mod itself. I have seen flying fruits over-world at some occasions. Pam's hanging fruits are tile-entities while the leaf block are dumb leaf blocks. Some world-gen rules might override erase leaf blocks but leave tile blocks in-place. This might not even be pam's mod fault either. Might be Natura or Biomes'o'plenty or even vanilla world-gen issue.

**Comment by repo-alt** [comment]
"I would appreciate that any modpack creators and/or server administrators that greatly benefit from having my mod in their pack/on their server donate to my Patreon, but I am not requiring this"

**Comment by draknyte1** [comment]
Fairly sure the source is available to the GTNH team. @Ethryan 

Iirc, Moron asked Pam for it, then just gave her some $$ to obtain the ability to decompile and use said sources since she didn’t have it herself.
