### ISSUE TITLE
[Diamond Sawblade] offer change recipe

### ISSUE THREAD

**Issue by MotDT** [GTNewHorizons/GT-New-Horizons-Modpack#5966]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
#
I suggest change Assembler recipe to:
`(<Diamond Saw Blade>, <Cobalt Brass Gear> * 1, <Diamond Small Dust> * 1, 800, 120)`
_(using 1 Diamond small dust instead of Diamond dust and MV voltage)_
#
![Diamond Sawblade](https://user-images.githubusercontent.com/47714084/79971691-593b1e80-849d-11ea-8e06-f2ee611ac1a6.png)
![Diamond Sawblade2](https://user-images.githubusercontent.com/47714084/79971832-97384280-849d-11ea-9bbf-c268729c2d8c.png)

**Comment by Prometheus0000** [comment]
What problem does this solve? And what are you supposed to do with the other 3 small dusts then?

**Comment by MotDT** [comment]
> 
> 
> What problem does this solve? And what are you supposed to do with the other 3 small dusts then?

3 small dusts for other recipe..
Assembler recipe not balanced
Why i will using assembler if can craft: quick, without cost energy?

**Comment by Prometheus0000** [comment]
What other recipe? The only thing that uses small diamond dust is this, and you don't need a lot of them at all. How would it not be balanced? Your recipe restricts using the assembler recipe until MV, but why? There's lots of recipes that have assembler recipes that aren't as good as hand crafting. Are you going to go through all of them? Why bother? People will still hand craft them. If you think it's unbalanced it terms of time, just suggest reducing it to 5 secs or something.

**Comment by Dream-Master** [comment]
@MotDT we not change the recipes like you mentioned. Come up with a beter one and reopen it if you like.
