### ISSUE TITLE
Merge Saltpeter and Potassium Nitrate

### ISSUE THREAD

**Issue by Glease** [GTNewHorizons/GT-New-Horizons-Modpack#5967]
#### Which modpack version are you using?
2086fix2
#
#### If in multiplayer; On which server does this happen? 
private mp
#
#### What did you try to do, and what did you expect to happen?
KNO3 is KNO3
#
#### What happened instead? (Attach screenshots if needed)
KNO3 is not KNO3
#
#### What do you suggest instead/what changes do you propose?
Merge two into one. If Potassium Nitrade is intended to be the purified version, add a recipe to refine saltpeter into potassium nitrate (e.g. centrifuge). ~~Plus, fix the typo as the correct spelling is potassium nitra**t**e.~~ This is addressed in another issue.

**Comment by chochem** [comment]
If we do any merging, the recipes should also be looked at, as they are very inconsistent. namely from K to KNO3 (which many players use for leach residue processing), we currently have

1. 1 Potassium Dust + 1000L Nitric Acid -> 1 Potassium Nitrade
2. 1 Potassium Dust + 3000L Oxygen + 1000L Nitrogen -> 1 Saltpeter
3. 1 Potassium Dust + 3000L Water -> 3 Potassium Hydroxide Dust + 1000L Hydrogen, 3 Potassium Hydroxide Dust + 5000L Nitric Acid ->5 Saltpeter + 16000L Steam

Btw, there also is Gregtech Niter Dust (which is just another word for Saltpeter) but I dont think that can be obtained in any way.

**Comment by Glease** [comment]
Niter is probably just a legacy ore that isn't generated any more. The potassium dust + nitric acid recipe and potassium dust + oxygen + nitrogen recipe are hilarious in every sense and we'd better just get rid of them. The last one makes *some sense* and is reasonably complex. I'd prefer this route.

It should also be noticed that saltpeter is obtainable via other options:
* Centrifuge unstable comb
* Crush sandstone in a SAG mill
* Saltpeter vein in nether. Primary, Weight 40.

**Comment by Dream-Master** [comment]
I rember i add something in the core mod before it was added to gt. Mybe old one is obsolete idk.

**Comment by noobnoobnub** [comment]
Speaking of which, there is two dinitrogen tetraoxide. Only one (from dehydration with copper) has usage for rocket fuel. Maybe it is a good idea to remove the other one (from chemical reactor with nitrogen and oxygen).

**Comment by Prometheus0000** [comment]
Also see #5521

**Comment by Glease** [comment]
Partially addressed by  GTNewHorizons/GT5-Unofficial#423
