### ISSUE TITLE
Buff infinity turbines

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5970]
#### Which modpack version are you using?
2.0.8.9
#
I get not many people make this but it seems a bit silly that infinity has the same efficiency as cosmic and awakened. If you are going to put the effort into making infinity turbines you should get a higher efficiency on your energy generation.

Perhaps buff them as follows? Open to suggestions.

Small - 220
Normal - 245
Large - 270
Huge - 250

**Comment by 0lafe** [comment]
The point of initially adding If turbines was to just bridge the gap between a high efficiency turbine and a high durability one, not to add anything with extra efficiency

**Comment by GTNH-Colen** [comment]
> The point of initially adding If turbines was to just bridge the gap between a high efficiency turbine and a high durability one, not to add anything with extra efficiency

It's pretty much the most endgame material in the pack, why shouldn't it have a greater efficiency than cosmic neutronium? This is an expensive material, I can't see many people putting the 200 odd infinity required into actually making these increased efficiency turbines but if they do then they deserve the energy boost.

**Comment by 0lafe** [comment]
SpNt wasn't meant to have a turbine iirc. The best were Nt/D*, but each had a benefit over the other. If was the truly endgame option to get the best of both turbines. You really don't need the efficiency boost. The idea with them was more if you have spare If, you can replace turbines less frequently. Idk the length of them, but if it's more than 4x D* at eff L/t rates, that's kind of useful still. 

If SpNt is the same as If I'm not sure I like it, but as long as it's low durability, isn't that similar to D*?

**Comment by GTNH-Colen** [comment]
> SpNt wasn't meant to have a turbine iirc. 

Well it does and has the same stats as inf pre buff efficiency wise.

>The best were Nt/D*, but each had a benefit over the other. If was the truly endgame option to get the best of both turbines. You really don't need the efficiency boost. The idea with them was more if you have spare If, you can replace turbines less frequently. Idk the length of them, but if it's more than 4x D* at eff L/t rates, that's kind of useful still.

Nt currently has about 10x the durability but slightly less efficiency. I mean that may have been what was intended then but this works now and based off the chat we had earlier people seemed up for a buff on this material, it makes sense given the cost. Maybe in the future if we get materials even beyond infinity we can have better turbines.

Also in regards to "You really don't need the efficiency boost." says who exactly, not sure who your authority is on that one?

> Isn't the If eff much past D* anyway? Iirc it ended up being buffed anyway

Nope, no efficiencies went > 180 before this buff.

**Comment by Dream-Master** [comment]
we can disable cosmic notronium turbine

**Comment by GTNH-Colen** [comment]
> we can disable cosmic notronium turbine

I don't see why we need to disable it, 0lafes only argument is that he thinks it should be disabled not really any actual logic?

**Comment by 0lafe** [comment]
Ah Fuck I forgot the 3rd turbine value. If was also meant as a merge of Ke, with it's throughput. It's definitely more than D* for throughput, which is really the only issue with turbines. 

>Also in regards to "You really don't need the efficiency boost." says who exactly, not sure who your authority is on that one?

180% on He alone is more than you'll need, 180% on Sn plasma is more than fine. Eff reduced infra on plasma gen side, which is really not the problem. 

If you want to talk throughput I'd be more onboard, but even then, iirc If is in a good spot. It *should* be similar if not more than Ke, which was the best at the time. Iirc it's somewhere around 1.7x the throughput of D* being ~730kv instead of ~450kv. 

Ignoring ++ which is a big help here, the issue is the turbine quantities for scaling, which was the last part of the If turbine addition. 

Unless SpNt/Ic have the same throughput/efficiency as If, which durability close to D* or above, then they can probably stay the same. D* is gated post SpNt, so I'd rather not see it being worse. It's a very good turbine pre If, which without an efficiency bonus still provides a very useful throughput increase. 

Is there a fusion based reason for needing more efficiency? It seems very much ok where it is, if anything the efficiencies are one of the things that make fusion OP atm

**Comment by GTNH-Colen** [comment]
> 180% on He alone is more than you'll need, 180% on Sn plasma is more than fine. Eff reduced infra on plasma gen side, which is really not the problem.
> 
This isn't actually about what you "need" just balancing an endgame material. As I previously stated very few people will bother given the cost of these rotors. I was only prompted to do this because someone in chat last night crafted a huge infinity turbine and yet it was actually pretty bad in terms of efficiency. Prior the best was essentially cosmic neutronium iirc, this at least gives endgame players an even better rotor to work towards. 

> Is there a fusion based reason for needing more efficiency? It seems very much ok where it is, if anything the efficiencies are one of the things that make fusion OP atm

OP in your *opinion* 0lafe, but that isn't really a new phenomenon. Again as I said if people are willing to spend 144-216 infinity ingots per reactor for an extra energy boost than that is on them. This is a very endgame material and an efficiency buff was needed to distinguish it. You may personally think that is not a lot of infinity but I can tell you from personal experience and talking to many other players that it is a very significant amount.

If you want to completely butcher power generation from fusion as a whole then please take that to another thread.

**Comment by GeicowithaBango** [comment]
I hope you will reconsider a diffrent efficiency value @Dream-Master The current suggestion gives 90% more efficiency, which is extremely high, imho

**Comment by GTNH-Colen** [comment]
> I hope you will reconsider a diffrent efficiency value @Dream-Master The current suggestion gives 90% more efficiency, which is extremely high, imho

> Open to suggestions.

**Comment by Dream-Master** [comment]
if this is to high we can nerf it. Suggestion splease @GeicowithaBango

**Comment by GeicowithaBango** [comment]
I heard that you buffed other turbines too, is that true? If so, mind showing the numbers, so that we can find a solution?

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/c87de46629d25c549a46e5b3499b98ee2b009790

**Comment by Dream-Master** [comment]
1 level means 10 point efficency at small turbine and +25 each. Only huge is max value - 20

**Comment by 0lafe** [comment]
Did you nerf some? D* was 180% iirc at large, which would be 130 at small, with an efficiency value of 13? 

Anyway, any value above 180% at a large turbine is pretty OP. Even things above 150% are reaching OP territory. If you want to make the If turbine better, I'd suggest increasing the throughput. It still makes the turbine better, but adjusts the weaker side of production.

Efficiency increases power from fusion, throughput increases the throughput of the turbines. Fusion fuel gen is amazingly easy atm, giving efficiency buffs this incredibly unbalanced process even more. Throughput increases leave fusion alone, and require less turbines from you, which is much more fair. 

Id suggest lowering some of the efficiencies to produce 150% at a large turbine for SpNt/Ic, with throughputs around ~400kv. Then put D* at 160% eff with ~450kv, and If at 180% with ~800kv

**Comment by GTNH-Colen** [comment]
> Id suggest lowering some of the efficiencies to produce 150% at a large turbine for SpNt/Ic, with throughputs around ~400kv. Then put D* at 160% eff with ~450kv, and If at 180% with ~800kv

This is literally just a nerf to before the original values? The entire point of this thread was to buff infinity turbines which has been achieved, a lesser buff is okay if you can justify it. As I said if you want to nerf fusion then **open a new ticket** discussing that instead. Infinity is not a super abundant resource, please stop balancing around your own play style and consider others.

I also see absolutely no point in spending the amount of resources to make infinity rotors just so I can build a few less turbines? It costs far more to run them and the turbine multiblocks themselves are not expensive. The only good way is to up the efficiency gains.

**Comment by quedral** [comment]
> Id suggest lowering some of the efficiencies to produce 150% at a large turbine for SpNt/Ic, with > throughputs around ~400kv. Then put D* at 160% eff with ~450kv, and If at 180% with ~800kv

Firstly the values you propose is lower than the current values if i am not wrong so this defeats entire purpose of the ticket itself.

Secondly what the hell is kv? kilo-volt? no offense but are we taking suggestions from a person who cannot differentiate real world Volt with imaginary EU?

**Comment by Anarack** [comment]
EU has a voltage... kv is just short hand for NUMBERx1000.

**Comment by botn365** [comment]
0lafe just wants to use whats used in irl but is stil mis using it sine it should be KW

**Comment by GTNH-Colen** [comment]
> EU has a voltage... kv is just short hand for NUMBERx1000.

He could just write kEU, 0lafe is deliberately being obscure for no purpose other than to confuse people.

**Comment by 0lafe** [comment]
If kv confuses you then I got nothing lol. I tried kw for a while but people reallly didnt like that one. 

The values i proposed also aren't detrimental to If, they do buff it a little. 800kv output is slightly more than they are now iirc, and the eff is the same. Also, adjusting the other values, does put a 180% efficiency of If above anything else. 

If you want to really buff efficiencies of turbines, it would be nice if you could somehow justify the values with current fusion values. It very much seems like all plasmas, with tin being even worse, give more power than you need. This adjusts the OP parts pre If a bit, and places If above all in efficiency and throughput. 

Throughput is also a large concern with fusion. Especially with Sn plasma, but He as well, turbines become a large portion of your setup. Lowering turbine count allows better scaling, which is quite useful.

**Comment by botn365** [comment]
i dont think eff should be realy buffed maby up to like 200 or 210% but more the trough put of them
right now infinity has 3.55x more trough put then cosmic neutronium but cost +24x the amiunt to make so its just easyer to spam turbines

**Comment by GTNH-Colen** [comment]
> If kv confuses you then I got nothing lol. I tried kw for a while but people reallly didnt like that one.

Unfortunately not all of us smol brained people are able to keep up with your massive intellect, please use shorter words in future );

**Comment by iouter** [comment]
why not think about raw materials or products in chemical industry

**Comment by Dream-Master** [comment]
@GTNH-Colen @0lafe @botn365 @Anarack @GeicowithaBango ok then let's write down now the new values here so I can change it.
