### ISSUE TITLE
More underground Fluids

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#5974]
I add now To barnadeE the unkown fluid as underground fluid and i found out nothing work on this planet so i fixed it too.

I like to see more usefull but not to op materials as fluids on planets and moons.
Any suggestions?

**Comment by Prometheus0000** [comment]
I believe people were complaining about a lack of hydrogen, and pumping methane and cracking it or something, maybe add Hydrogen directly? Maybe add Sulfuric Acid or Hydrogen Sulfide to Io (it's volcanic right?). Also, maybe Carbon Monoxide and/or Carbon Dioxide as they would probably be realistic to find on planets. Maybe other molten metals? Possibly Distilled Water to Europa (it's full of water, isn't it?) .

**Comment by feliser** [comment]
Milk

**Comment by 0lafe** [comment]
Methane would be nice, but H2 pre T7 or so seems kind of OP. H2 makes up a fair bit of the cost of many fuels.

**Comment by botn365** [comment]
methane can alredy be found on titan

**Comment by Prometheus0000** [comment]
Is H2 so OP? It's just easier than water electrolyzing it, right? Which is already infinite. This would just be faster.

Although what I really want is gas giant gas siphoning of various stuff, kind of like in Advanced Rocketry. You could have all kinds of stuff if that was possible. Maybe a new dim like the asteroids one that's supposed to be Jupiter's upper atmosphere or something?

**Comment by botn365** [comment]
water electrolisis does come with a big energy cost and infrastructure so you cant realy compare it to water

**Comment by feliser** [comment]
I agree with 0lfate

**Comment by GTNH-Colen** [comment]
> Maybe other molten metals? Possibly Distilled Water to Europa (it's full of water, isn't it?) .

Perhaps molten iron is an option useful but not gamebreaking? Also would like to see hydrogen later on, perhaps a T7 or T8 planet as it can be quite useful.

**Comment by quedral** [comment]
molten iron/ copper/tin?

**Comment by iouter** [comment]
why not think about raw materials or products in chemical industry

**Comment by SKYCATV587** [comment]
why not add a uua/uum in world ,it can just chance1,maxamount10(or5?),minamount0,even you find it ,it also can't change anything。Just as a symbol of luck

**Comment by botn365** [comment]
uum would be realy OP maby even uua

**Comment by Extremity4** [comment]
What about fluorine or HF? The current meta for infinite fluorine is crops but it might be nice to have an alternative option for people who dislike crops.... IDK what tier if any would be good for it though

**Comment by ScriptedPiky** [comment]
Fluorine or Hydrofluoric would definitely be a nice addition. Fluorine is only ever used in large amounts for PTFE, then there are exactly three fusion recipes, and finally, there is the GT++ usage of Fluorine for Industrial Strength Hydrofluoric Acid, which doesn't have a lot of uses in itself either. Perhaps Fluorine would be very nice and not as game-breaking in this case.

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/5980

**Comment by chochem** [comment]
got one more suggestion, maybe you already had that on your radar: once the the new fluids are fixed, can they be added to the overview quest as well?
that is 'Saltwater and Chlorobenzene on Mars', Space Race Tab, ID 1743

**Comment by Dream-Master** [comment]
sure

**Comment by noobnoobnub** [comment]
sulfur dioxide and hydrogen sulfide?
maybe carbon monoxide if you want to set a small scale power generation
ammonia for very late tier? not sure will it be useful for late game

**Comment by 0lafe** [comment]
CO seems kinda OP. Maybe we can put it somewhere as an O2 source instead of pure O2? If you can pump a pure fuel that gets out of hand very fast with pumps. Id suggest gating CO post fusion if anything

**Comment by Prometheus0000** [comment]
The idea behind CO and CO2 is to get carbon though. To me at least. And somewhat realistic I think?

**Comment by Anarack** [comment]
People run out of carbon? I agree with olafe about recreating the refinery gas problem.

**Comment by chochem** [comment]
> 
> 
>  Id suggest gating CO post fusion if anything

@0lafe check again. Oberon is T5, so that is already the case. Nobody would use it as a fuel at that stage.

**Comment by Prometheus0000** [comment]
I didn't even know you could even burn those two things (are they even flammable? maybe they should be changed?) before. I don't have an automatic process for getting carbon so it's entirely possible that people wouldn't need it by the time they got the the point they could pump it.

**Comment by Prometheus0000** [comment]
This is already done, if someone wants to suggest a change, they can open a new issue.
