### ISSUE TITLE
Lava change made the HV quest "Separating molecule" useless

### ISSUE THREAD

**Issue by PoroCoco** [GTNewHorizons/GT-New-Horizons-Modpack#5979]
#### Which modpack version are you using?
I'm using the version 2.0.8.8
#
#### What did you try to do, and what did you expect to happen?
I wanted to do the "Separating molecule" quest in HV (quest id 1921) that tell the player that he can centrifuge lava in a HV centrifuge to get tungstate so I expected to get tungstate.
#
#### What happened instead? (Attach screenshots if needed)
With the changes made to lava, processing lava into a centrifuge doesn't give tungstate, only pahoehoe lava processed into a centrifuge gives tungstate. 
![Screenshot_200](https://user-images.githubusercontent.com/48033370/80286827-f6ac8180-872d-11ea-8161-ba7f5f82e117.png)
Also, the recipe doesn't require HV voltage but MV.
It doesn't stop the player from doing the quest as the only requirement is to craft a HV centrifuge but the information is wrong.
#
#### What do you suggest instead/what changes do you propose?
I think that the information in the quest need to be uptated and maybe to remove the fact that this quest is marked as a "main quest" (star form and thick line)

**Comment by Dream-Master** [comment]
will change the quest
