### ISSUE TITLE
Nether portal going to random dimension

### ISSUE THREAD

**Issue by Glease** [GTNewHorizons/GT-New-Horizons-Modpack#5981]
#### Which modpack version are you using?
2.0.8.6 fix2
#
#### If in multiplayer; On which server does this happen? 
private. vanilla forge server.
#
#### What did you try to do, and what did you expect to happen?
Go to nether via nether portal. Go back to base via the portal created.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/4586901/80287157-77857080-8762-11ea-8b9b-58f8fb3b74cb.png)
Go to nether via nether portal. Land on moon when I go back.

After server restart the nether portal no longer links to moon but some other random location, thankfully still in overworld not moon.
#
#### What do you suggest instead/what changes do you propose?
Fix this bug.

WARNING: Cannot reproduce. Cannot determine the cause. Server log contains nothing useful. This is more or less a note that this *can* happen.

**Comment by Dream-Master** [comment]
since i set the dims to positive numbers this is fixed. Was an old bug fixed ages ago by GC itself.

**Comment by Glease** [comment]
The important thing about this bug is **Go to nether, then travel through the same portal, I landed on moon**. I can skip the rocket to go to moon.

**Comment by Dream-Master** [comment]
@Glease are you have any idea how or if this can be fixed? Blacklisted GC/GS dims from portals ?

**Comment by Glease** [comment]
Absolutely no idea as I can not reproduce it. My guess is that there is something wrong with vanilla nether portal code. Perhaps the blacklist (i.e. an explicit check) can be ASMed/mixin-ed inside so it cannot happen again.
