### ISSUE TITLE
Pattern Capacity Cards need to be cheapened 

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#5982]
Currently as 2.8.9 the pattern capacity cards are so expensive as to be useless unless you are really strapped for space or at a really high tier. 

I am at UV and I'd rather just make another ME Interface and a Machine since that is far cheaper. They is also the added benefit that this would help servers as it would add incentive for more compact set-ups.

I think it it should cost 1 advanced me card, 2 1k drives(or hv circuits)  and 1 capacity card.

The other option is 1 advanced me card 2 4k drives, an advanced me card and an me interface. 

Also it should not increase power usage by 4x.  

I love that these were added but not worth it atm

**Comment by Dream-Master** [comment]
the new one @redmage17 ?

**Comment by redmage17** [comment]
Yes the ones that add expansion slots to me interfaces

**Comment by Prometheus0000** [comment]
It should be 4x per card when in use. repo-alt's comments on how much power it uses is confusing though. Like, do I add those, or multiply them? https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5707#issuecomment-596255678

I'm at IV and don't think the recipe is _too_ bad, but kicking the 16k down to 4k or 1k would significantly reduce the cost.

**Comment by Dream-Master** [comment]
we allready changed from 64 to 16 not another buff.

**Comment by redmage17** [comment]
You were nuts to start with 64k in the first place

**Comment by 0lafe** [comment]
It's not 64k? Bruh...

You should make it 64k again, a 1-3x increase in pattern storage is incredibly useful. You get 4x total storage per logistics setup. One interface compared to 2/3/4/etc is a very different setup. It'll always be cheaper to spam more, but there's also a reason you aren't using LV machines forever. We put a few of the 64k recipe storage extenders in, and it's super fine. 64k storage is free by like IV if you have a very small amount of diamonds. If anything id recommend raising it to 256x to push the first possible usage of them a little farther

**Comment by Anarack** [comment]
I'd disagree on the usefulness of this tbh, yes it uses less channels but thats not a big deal. More blocking mode recipes in one interface is the main draw for me, but even that is not a big issue as  a assembler + diamond buffer chest and 5 interfaces almost never manages to jam itself. wouldn't even bother with it at 256 and 64 is on the edge of it being cheaper to spam machines, even high tier ones.

**Comment by botn365** [comment]
16k is fien makes it not to cheap for a prety powrful upgrade

**Comment by repo-alt** [comment]
> on how much power it uses is confusing though. Like, do I add those, or multiply them?

Seriously how one can misinterpret "Each upgrade increases energy usage 4 times." Yes it is multiplicative.

**Comment by Prometheus0000** [comment]
Well first, the amount of AE used per item is not specified, and I'm not sure where it is. Or rather, I never even knew the power draw from an interface increased when in use to begin with until I saw you comment. You didn't specify whether it was multiplicative or additive, so how would I know? I would assume additive, or the power usage would spike tremendously, right? Also, could you tell me how much AE it uses per item?

**Comment by repo-alt** [comment]
Energy per craft, not sure if it documented anywhere. AE crafting CPU extracts the (sum of amounts of items in the pattern) * config multiplier, and now that is also multiplied by 4^(number of upgrades)
Also 1 EU = 2 AE internal energy units.
E.g. recipe (wood log -> planks) in the interface w/o upgrades would draw: 1*10 AE units, that is 5 EU
9 charcoal -> charcoal block compressor recipe in the interface with 3 upgrades will draw 9*10*4^3*0.5 = 2070 EU

**Comment by chochem** [comment]
I am at ZPM and still haven't used these. Contrary to what some people are saying here, they are not very powerful. They are only a qol improvement and a way to make your setups slightly more compact. Its pretty straightforward to use multiple interfaces on a single machine without them.

Compared to that, the power draw and crafting cost are still a bit excessive. Of course I could use them at this point and I might - the cost are not big if you are zpm - but they certainly are pretty bad in EV/IV.

**Comment by repo-alt** [comment]
Energy usage has been somewhat reduce, and as recipe is not going to change I close this
