### ISSUE TITLE
[RFC] remove Nat gas spawns in the OW 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5983]
#### Which modpack version are you using?
2.0.new

Nat gas veins in the OW are OP. Nat gas comes from oil in good enough ways. 

"Realism" but no, it's pretty broken 

Movement to other planets/reduction in rates is an option, but for how shitty of a power system it is, I recommend removal.

**Comment by mitchej123** [comment]
I see no math, no support other than "0lafe says it's broken"

**Comment by Bluebine** [comment]
here is math: 8 LV electrolyzers to make 1 hydrogen every 4 seconds, and 1 chemical reactor, makes 16kEU/t in refinery gas from natural gas
which is kind of absurd for a very simple two-step processing chain powered by a drilling rig
nat gas processing is stupid easy and shouldn't be that rewarding

**Comment by mitchej123** [comment]
Thanks for the math!

**Comment by Ldmf** [comment]
If you dont like it remove it fome you game and dont force others to go you way

nerfing it is ok but removing i think not
increase the time and reduce the burn value of nat gas and refinde gas
maybe lower the amount fund in ow
oil and gas belong together you cant finde one with out the other

**Comment by 0lafe** [comment]
Oil provides gas at an elongated time/power, and in the OW

**Comment by Dream-Master** [comment]
So what is the essence of the whole discussion ? Remove Gas and put it to another planet/moon or reduce the amount the chance? @0lafe @Bluebine @Ldmf @mitchej123

**Comment by Glease** [comment]
Make the nature gas -> refinery gas process takes 4x as long would satisfy your balancing point. Nature gas is easier than oil only because the distillery is too slow. 

I mean, why remove it? There should be different ways to power your base.

**Comment by Ldmf** [comment]
for natural gas reduce the fuel value from 20000 to 10000
reduce the chanc of finding it by 25% and the yeld by 25% to 30%
for refined gas move to HV so you need at last a HV Chemical reactor and incres the ti,me to 20s 
increas the totel eu cost respectivlie
lower the fule value from 160000 to 80000

**Comment by Dream-Master** [comment]
what is with the idea replace it with sulfuricgas?

**Comment by Ldmf** [comment]
i think the problem is if you nerf one power source you must check all other so they are all in line with each other

**Comment by quedral** [comment]
didn't we have this exact ticket yesterday? There is no math behind it, its just 1 person saying its OP. Put this on Discord Vote. it is very major change and will effect everyone.

**Comment by chochem** [comment]
@quedral this RFC is in response to that PR. The maths is in Bluebine's post above. If you think that maths is incorrect, please provide an explanation.

**Comment by Dream-Master** [comment]
natural gas is now changed to 350 at ow

**Comment by Prometheus0000** [comment]
I'd be fine with weakening it or moving it.

**Comment by 0lafe** [comment]
https://docs.google.com/spreadsheets/d/1WJl8DdvOgoSoCErVIt3GEz7O3O5IEJ3-SR9KEkhKTCQ/edit?usp=sharing If you wish to see more math, this gives some useful values. I highlighted the categories you input values for with green, and useful output values in orange. 

Even at 350 you can do some insane things with it due to the scaling. In EV you can throw down a T3 pump and with a PA of ~37 electros, one MV LCR and one separate LV electro, you can get almost 100keu/t worth of RG. If the PA is too expensive, even using singleblock EV electros gets you >80keu/t off a single pump.

The main issue is how pumps scale. You have a 16x boost at T2 and 64x at T3, independent from overclocking. Compared to an MV machine at EV normally having a 4x speed bonus, the pumps would have a 256x.

Of course you can't simply use the raw fuel, you need turbines. However, with this incredibly small setup, you can power something close to 16 turbines. While it's not infinite free fuel, it gets very close to the cost of power simply being your turbines construction/maint/setup costs. This very much eclipses pretty much every fuel option we have, despite most being much more complex and require much more infrastructure for similar fuel gen levels. 

Oil is much more balanced in this sense, as the initial distillation of oil is a fairly limiting factor. The main way around it is to do use single distilleries, which will increase your oil consumption by a lot. This fits the rates pumped a lot better, and provides a bottleneck that results in much more reasonable infrastructure for a given fuel rate. 

I do strongly recommend simply removing nat gas as a spawn. You produce it with oil, it provides power positive rates that make refining it and burning it useful. 

Nerfing the pumping effects things that are perfectly reasonable as they are, when the only noticeable issue is natural gas. Yes, pumps are good, but theyre often limited in other ways once you have the raw fluid. Nat gas doesnt limit you in those ways at all, and that's what brings us such an OP fuel. We certainly could extend nat gas processing, but that's essentially what oil already is.

**Comment by Prometheus0000** [comment]
I don't really disagree to nerfing or maybe removing from OW, but still STALE.
