### ISSUE TITLE
Extra utilities and Enderchest potentially don't call markDirty when changing settings

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#5985]
#### Which modpack version are you using?
2.0.8.4
#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What happened?
Items randomly seem to dupe or void en masse in my garden dimension - this only happens through routes that would normally pull the same items, but they don't show up the other end (mostly for ores) or duplicate. Furthermore, it seems that tile entities - or possibly the world itself - sometimes seem to exists in multiples:
- Moving an ender chest away from its connected location and putting it somewhere not connected still sees its inventory pulled. The contents usually doesn't show up elsewhere.
- Extra utilities retrieval nodes sometimes transfer items at higher than expected rates.
- Updating filters for XU nodes sometimes doesn't have any effect - it will still transfer as per the original configuration.
- It's not limited to XU networks - cells readily duplicate from the electrolyser processing ores, which is connected entirely with stock GT cables and pipes except for one transvector interface.
- Once they have started, relogging (with the expectation to unload the entire dimension) does not reset the symptoms.

#
#### What do you suggest instead/what changes do you propose?
I thus suspect that due to some bug the tile entities in the garden dimension stay in memory when the dimension is left, and upon return a new copy and the old copy together run for each tile entity. This could be another symptom to what's causing #5033, but might be something different entirely.

Of course I'd like to see this fixed, but I'm not oblivious to the rumour mill and surgical removal could well be on the table.

**Comment by Dream-Master** [comment]
@bartimaeusnek can you re check this mod ?

**Comment by boubou19** [comment]
the enderchest bug happened to me on my void dim as well

**Comment by Prometheus0000** [comment]
Was this due to thermos? I remember that a bunch of stuff was mp-only, does it happen in SP?

**Comment by eigenraven** [comment]
Most of these were already fixed, they are usually missing markDirty calls when TE contents change. UW was also replaced by PS which fixes some of the world time issues. However enderchest and XU not saving might still be something that needs looking into.
