### ISSUE TITLE
[Suggestion] [Bartworks] Extra platinum recipes

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#5986]
#### Which modpack version are you using?
2.0.8.4
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I've been implementing the platinum chain. I've been mostly doing it in IV singleblocks to avoid the voiding and pollution risks associated with multis.

#
#### What happened instead? (Attach screenshots if needed)
The chain is long, and there are various places where it could be a bit more convenient - particularly to save up on fluid canners.

#
#### What do you suggest instead/what changes do you propose?
I've compiled a list of mostly "missing" recipes - chemical reactors where inputs and outputs could be formulated in more than one way like the game allows you to create hydrochloric acid with either H, Cl or both as the cell input, and the option to pick cell or fluid output.

I mainly hope you find this list useful:

**Chemical reactor: CO + NaOH -> NaCOOH (Sodium Formate)**
- 1x NaOH (dust) + circuit + CO (1000L) -> NaCOOH (1000L)
- 1x NaOH (dust) + empty cell + CO (1000L) -> NaCOOH (cell)

**Chemical reactor: C + CO2 -> 2xCO (Carbon monoxide)**
- 1x C (dust) + 1x CO2 (cell) -> empty cell + CO (2000L)

**Chemical reactor: 2x NaCOOH + H2SO4 -> HCOOH + Na2SO4**
- NaCOOH (2 cell) + H2SO4 (1000L) + circuit -> HCOOH (2000L) + 2x empty cell + 7x Na2SO4 dust
- NaCOOH (2 cell) + H2SO4 (1 cell) -> HCOOH (2000L) + 3x empty cell + 7x Na2SO4 dust

**Chemical reactor: Platinum metallic power + Aqua Regia**
- 1x PMP dust + 1x Aqua Regia (cell) -> 1x Platinum concentrate (cell) + 1x tiny platinum residue dust

**Chemical reactor: HCl + NH3 -> NH4Cl (Ammonium chloride)**
- 1x NH3 (cell) + circuit + HCl (1000L) -> NH4Cl (1000L)
- 1x HCl (cell) + circuit + NH3 (1000L) -> NH4Cl (cell)

**Chemical reactor: Na2RuO3 + Cl -> Ruthenium Tetroxide solution**
- 2x Na2RuO3 + circuit + Cl (1000L) -> RuO4 solution (3000L)

**Chemical reactor: RuO4 + HCl -> Ruthenium**
- RuO4 (dust) + 2x empty cell + HCl (6000L) -> Ru (dust) + water (2 cells) + Cl (6000L)
- RuO4 (dust) + circuit + HCl (6000L) -> Ru (dust) + Cl (6000L) - water voided

**Chemical reactor: Acidic iridium solution + Ammonium Chloride -> Ammonia + Iridium(III)Chloride**
- Acidic iridium (cell) + circuit 1 + NH4Cl (3000L) -> Empty cell + IrCl3 (dust) + NH3 (3000L) 
- NH4Cl (3x cell) + circuit 1 + Acidic iridium (1000L) -> 3x Empty cell + IrCl3 (dust) + NH3 (3000L)
- NH4Cl (3x cell) + circuit 2 + Acidic iridium (1000L) -> NH3 (3x cell) + IrCl3 (dust)

**Chemical reactor: Iridium oxide + HCl -> Acidic iridium solution**
- IrO2 + circuit 1 + HCl (1000L) -> Acidic iridium solution (1000L)
- IrO2 + empty cell + HCl (1000L) -> Acidic iridium solution (1x cell)

**Mixer: H2SO4 + H2O -> Diluted sulfuric acid**
- 1x H20 (cell) + 3x H2SO4 (cell) + circuit 1 -> Diluted H2SO4 (4x cell)
- 1x H20 (cell) + 3x H2SO4 (cell) + circuit 11 -> Diluted H2SO4 (4000L) + 4x empty cell

**Centrifuge: Platinum concentrate + Ammonium chloride -> products**
- 1x NH4Cl (cell) + 10x Platinum concentrate (cell) -> 1x Pd-enriched (cell) + 5x NO2 (cell) + 5x Diluted sulfuric (cell) + 10x tiny PtCl dust + 64+16 tiny platinum salt dust

**Fluid solidifier**
- Potassium (144L) + circuit -> Potassium dust

**Distillery: Hot RuO4 solution -> salt/water/RuO4**
- RuO4 solution (500L) + circuit 1 -> salt (3x tiny dust) + water (100L)
- RuO4 solution (500L) + circuit 2 -> salt (3x tiny dust) + RuO4 (400L)

**Comment by GeicowithaBango** [comment]
I have several questions about your setup.
It seems messed up. If you are really afraid of voiding while using Large Chemical Reactors, for instance, I suggest watching a tutorial about all the useful covers gt adds (very very helpful whatsoever).
your suggested version of „compact recipes“ is a nice idea, but probably too op. 

p.s I wouldnt use single block chemical reactors, and you dont have to use fluid canners, a tank that can interact with cells works perfectly.

**Comment by combusterf** [comment]
> I have several questions about your setup.
Yet you didn't ask any, just assumed. :eyes: 

> all the useful covers
By the time you have checked all outputs *and* the power source for safety, you end up with about as much additional space needed as the original multiblock you're trying to protect - whereas you get all of this for free in the singleblock version

> probably too op.
So you're saying that saving 10% space (read: server load) and materials on machines that would not be there, as well as a <0.1% power reduction is "too overpowered"?

> a tank
Still an extra block

**Comment by GeicowithaBango** [comment]
i really dont want to offend you but from what I just read I must assume that your judging is bad and that you lack in creative to make a decent and sufficient design for the processing.

**Comment by Prometheus0000** [comment]
Given that the second step _requires_ either an LCR or GT++ Centrifuge, plus how good they are, I believe you're expected to use the LCRs, and non-LCR recipes are just backups.

Though getting potassium dust back instead of potassium ingots is interesting. Given there's one for calcium chloride and ruthenium tetroxide, maybe we should also for that to be standardized for all molten materials? It would definitely be useful, unlike most of the rest of this stuff looks.

**Comment by GeicowithaBango** [comment]
hmm, I really thought about this issue for quiet a bit now. combusternerf might be right on about the compacted recipes. although, im still thinking that he didn’t give any bigger thought about setting his stuff up. 
Imo, there are processing steps that may could be summed up, the rhodium mixing, for instance. I understand that the recipe are as close as possible when it comes to realism, however, i think a processing chain that would require a certain machine (besides LCR) for multi steps is annoying and more important not following gt logic

**Comment by GeicowithaBango** [comment]
the overall energy consumption and output is well thought. its just about the single steps. i hope you consider this @bartimaeusnek

**Comment by 0lafe** [comment]
>think a processing chain that would require a certain machine (besides LCR) for multi steps is annoying and more important not following gt logic

What do you mean by this?

**Comment by GeicowithaBango** [comment]
an imaginary example, assuming a certain processing chain has 10 recipes to get the main product. if 3 of those 10 recipes are mixing recipes its getting absurd,imo. the gt way would be to find a proper way to make one compact recipe

**Comment by 0lafe** [comment]
Why? Imo that's what makes some of the more interesting GT mechanics, when you try to bundle recipes. We have absurd amounts in the LCR, which prompts fun LCR combinations. You have like 6 ebf steps in Pt proc, which also prompts the same thing. It's by no means an absurd amount of recipes, I'm not sure what the issue is

**Comment by chochem** [comment]
adding recipes to get out a fluid instead of a cell and vice-versa by changing the circuit makes a lot of sense. This is how I understood the main point of the post. I support that, even though I set up the platinum process with mostly singleblock machines myself without having any problems.

adding recipes to simply the processing chain again however, kind of defeats the entire point of the platinum process. Its supposed to be complex.

**Comment by combusterf** [comment]
> i really dont want to offend you

> combusternerf

That was unnecessarily childish of you. Please don't.

**Comment by GeicowithaBango** [comment]
@combusterf sorry was not intended

**Comment by Dream-Master** [comment]
Use Multiblocks.

**Comment by combusterf** [comment]
Welp, that got quitely vetoed.

**Comment by Dream-Master** [comment]
@combusterf ask @bartimaeusnek about it. Thanks

**Comment by combusterf** [comment]
Bart wrote:
> and combuster, feel free to add the recipes as a PR
> im just too lazy to implement them
