### ISSUE TITLE
wrong orevine spawen in plants 

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#5987]
#### Which modpack version are you using?
2088
#
#### If in multiplayer; On which server does this happen? 
my own server with some friends 
#
#### What did you try to do, and what did you expect to happen?
mine ore in the  palnts, expect it is 9 layers and like ow or tf or dd with some small ore in the spawn chucks.  
#
#### What happened instead? (Attach screenshots if needed)
these orevine are 7 layers rather than 9, and dont spawn small ore around chucks. Also, they dont spawn in every  coordinate it should spawn like ow. 
#
#### What do you suggest instead/what changes do you propose?
fix it

**Comment by Dream-Master** [comment]
why it is wrong ?
Its the new oregen
@richardhendricks  right ?

**Comment by Pnc6lx** [comment]
> why it is wrong ?
> Its the new oregen
> @richardhendricks right ?

i mean in these plants, orevine use the old oregen, not the new one

**Comment by Dream-Master** [comment]
@Pnc6lx did you mean the samll ores from bartworks ?

**Comment by Pnc6lx** [comment]
i mean, in ow, oremix wil genrerate small ores around the chucks in spawn. For example, i can find small oilsand ore around oresand oremix.  but in space, oremix dont generate these small ores. 
And in overworld, twilight forest, nether, end and dd( it was removed in 2089 ) , oremixs are 9 layers( new oregen) ,in gc and gs plants, they are 7( old oregen

**Comment by repo-alt** [comment]
On planets oregen is managed by GalaxySpace.

**Comment by repo-alt** [comment]
cf https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4417

**Comment by Pnc6lx** [comment]
so this problem has been existed for a long time?

**Comment by richardhendricks** [comment]
Yes, the problem is that GalaxySpace/GC planets outside of the moon use a different oregen scheme that isn't compatible with Gregtech.  A separate mod, GalacticGreg, is used. That mod has not been updated with the new oregen code.

**Comment by Dream-Master** [comment]
@richardhendricks are you able to make a code change there to make it looke same?

**Comment by richardhendricks** [comment]
It's too large a time investment for me right now, and there are more critical bugs that need fixing. By the time you are at those planets you shouldn't be using small ores to find veins anyways.

**Comment by Dream-Master** [comment]
@richardhendricks but you did it for the ow dims too. Any quicker duct tape solution here ?

**Comment by Prometheus0000** [comment]
Is this still happening?

**Comment by Pnc6lx** [comment]
its still 7layers

**Comment by repo-alt** [comment]
I see GC oregen is not even chunkified

**Comment by Pnc6lx** [comment]
and plant oregen is managed by galasticgreg

**Comment by Pnc6lx** [comment]
i receive this mail, say its fixed, but i dont see any code change.

**Comment by glowredman** [comment]
The bot went riot today and added "FixedInDev" labels to a lot of issues which should be stale

**Comment by Pnc6lx** [comment]
it is fixed now
