### ISSUE TITLE
Dirt recipe

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5988]
#### Which modpack version are you using?
2.0.8.3
#
Add a recipe for dirt, it seems rather silly that you can obtain gravel, cobble and sand in mass quantities easy enough but dirt is always kinda annoying in any modpack. Not saying it isn't renewable but a fairly easy recipe for it would be nice.

1 stone dust + 1 wood pulp + 100L of water = 1 dirt block in a mixer should suffice.

**Comment by Bluebine** [comment]
I would love a good dirt recipe. Always annoyed me how there was no easy way to make it.

**Comment by Prometheus0000** [comment]
Can't you macerate chaff or something?

**Comment by ScriptedPiky** [comment]
Yes, you can macerate bio chaff to get exactly 1 dirt block (8 saplings required).

**Comment by GTNH-Colen** [comment]
> Can't you macerate chaff or something?



> Yes, you can macerate bio chaff to get exactly 1 dirt block (8 saplings required roughly).

Sure you can, it's just a bit of a pain in the ass. Would rather see a more simple recipe for dirt than the whole centrifuging, macerating, macerating again and compressing recipe. It's just dirt, it's nice to have a lot around for building and such.

**Comment by shawnbyday** [comment]
@GTNH-Colen use gravel to get to dirt somehow? Recommendation everyone can agree on? I can make change.

**Comment by Prometheus0000** [comment]
Personally I'm not sure what's wrong with the other recipe. Or using an excavator to get more if you aren't at autoing it and want to terraform.

**Comment by DualBallers** [comment]
The pack is about automating, not terraforming by hand.
I've tried writing the recipe below using a bit more stone dust. Could someone try to add it in GT_MachineRecipeLoader around line 1577 and see if it compiles.

`GT_Values.RA.addMixerRecipe(GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Stone, 4), GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Wood, 1), GT_Values.NI, GT_Values.NI, GT_Values.NI, GT_Utility.getIntegratedCircuit(4), Materials.Water.getFluid(100L), GT_Values.NF, new ItemStack(Blocks.dirt, 1, 0), 50, 8);`
