### ISSUE TITLE
[Honey] incorrect Fermenter recipe

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#5989]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
#
Incorrect Fermenter recipe
![изображение](https://user-images.githubusercontent.com/47714084/80324612-509a6d80-883a-11ea-94de-b404a08e51dc.png)

#
Probably recipe should have been like this:
Centrifuge recipe: Honey[7094:26] to Honey[7094:31]
![изображение](https://user-images.githubusercontent.com/47714084/80324586-33659f00-883a-11ea-88aa-5424568af441.png)

**Comment by Dream-Master** [comment]
it's an exchange recipes in both directions. I picked the fermenter but centrifuge can used also.

**Comment by MotDT** [comment]
> 
> 
> it's an exchange recipes in both directions. I picked the fermenter but centrifuge can used also.

I understand, but recipe Fermenter ferment from one to the same, unlike a centrifuge.

**Comment by Dream-Master** [comment]
ok will change it.

**Comment by Prometheus0000** [comment]
Removed in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/158
