### ISSUE TITLE
Enhanced charm rebalancing V42

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#5991]
#### Which modpack version are you using?
2.0.8.3
#
Please can we finally address this issue, it's been around for two years now and all it needs is one simple recipe changes. I even made the PR myself a while ago to resolve this exact issue. 

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/5317
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5304
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5186
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3083

I think the primary issues currently are the fact that this uses the "ridiculously large capacitor" item following:

<img width="532" alt="Screenshot 2020-04-27 at 04 27 20" src="https://user-images.githubusercontent.com/54497873/80331271-89891100-883f-11ea-9d0b-383119bd919e.png">

This can be replaced with 

<img width="256" alt="Screenshot 2020-04-27 at 04 30 54" src="https://user-images.githubusercontent.com/54497873/80331406-e5ec3080-883f-11ea-863c-0256d5ff089f.png">

I made this suggestion a while ago, I still feel as if it is an appropriate recipe now. This is a teleport, it does not break the game or radically altar the balance. I have seen countless people complain about this and have done so myself on many occasions but by god I will get this recipe changed if it is the last thing I ever do.

Some maths:

Each "Stargate-Radiation-Containment-Plate" plate uses 16 infinity blocks
Each "Ridiculously large capacitor" uses 12 "Stargate-Radiation-Containment-Plate"
1 Enhanced charm of dislocation uses 8 "Ridiculously large capacitor"

This means 1 Enhanced charm of dislocation would use 13,824 infinity ingots. Do I even need to say anything more?

**Comment by feliser** [comment]
Collen this is a good suggestion, I think removing the capacitors is definately the right idea. But i still think maybe it would be better if we kept the SG core crystal in the center as it fits with the theme of the item but is nowhere near as insane as the capacitors

**Comment by quedral** [comment]
I don't understand why this is hanging for **2 years**

I know teleportation must be _adressed_ in whole but the current recipe is beyond ridiculous.
