### ISSUE TITLE
about 0lafe's issues

### ISSUE THREAD

**Issue by Del0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#5992]
i see 0lafe nerf a lot thing,and let game difficult a lot.you play this game?What stage have you reached?HV?EV?Have you really played gtnh seriously?If you did not play the game,Please don't make stupid speech.if can repair 0lafe can write issues in github ,GTNH will become beautiful and successful

**Comment by truecyt** [comment]
del 0lafe to MAKE GTNH GREAT AGAIN😂

**Comment by feliser** [comment]
0lfate always leaves the best suggestions and has the greatest ideas that make the game the best! yay for 0lfate! His helium fusion changes sound incredible and i am so excited for them to make it into the game!

**Comment by bigbass1997** [comment]
Do not use Github as a platform to push your negative opinions of other individuals. If you have a problem with someone, talk with them directly; don't come here to voice your dislike of someone.
