### ISSUE TITLE
SpecialDepLoader points to non existant URL

### ISSUE THREAD

**Issue by spannerman79** [GTNewHorizons/GT-New-Horizons-Modpack#5993]
#### Which modpack version are you using?
2.0.8.3e via https://www.curseforge.com/minecraft/modpacks/gt-new-horizons/files/2863127
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Click run/launch - SpecialDepLoader issues.
#
#### What happened instead? (Attach screenshots if needed)
```
SpecialDepLoader was unable to download required library GalacticraftCore-1.7-3.0.12.504.jar Check your internet connection and try restarting or download it manually from https://ci.micdoodle8.com/job/Galacticraft-1.7/504/artifact/Forge/build/libs//GalacticraftCore-1.7-3.0.12.504.jar and put it in your mods folder
```
URL doesn't exist - 404.
#
#### What do you suggest instead/what changes do you propose?
Update correct URL to `GalacticraftCore-1.7-3.0.12.504.jar` - and possible others.

**Comment by Dream-Master** [comment]
since I can't ship the mod files on curse we have this mess. Will check how I can host the files on another place.

**Comment by spannerman79** [comment]
https://authors.curseforge.com/knowledge-base/game-specific-support/3279-non-curseforge-mods

GalacticraftCore **is** listed in that spreadsheet.  Personally I know how much of a pain it is to deal with Curse/Twitch on the best of days.

**Comment by Dream-Master** [comment]
@spannerman79 use technic / multi mc or my download page make things more easy.
http://downloads.gtnewhorizons.com/ClientPacks/
or dev test pack
http://downloads.gtnewhorizons.com/Dev-Pack/Pack/

**Comment by spannerman79** [comment]
> use technic

No.

> multi mc 

Thats what I initially did, download the zip from https://www.curseforge.com/minecraft/modpacks/gt-new-horizons/files/2863127 create a new instance, import from zip like I have **always** done.  I've used MultiMC for quite some time.

This has nothing to do with "curse being sucky" but whatever config you have set to pull `GalacticraftCore-1.7-3.0.12.504.jar` from which doesn't exist/404'ed.  Which happens to be micdoodle8 CI server for which has changed.

> or my download page

They can be added as Additional Files - https://authors.curseforge.com/knowledge-base/projects/103-files-types-definitions-and-management

Also it will use the CurseCDN instead too.

**Comment by mitchej123** [comment]
> > use technic
> No.

Then stop complaining.  


It's not hard to download via Technic and import into multimc.

**Comment by spannerman79** [comment]
> Then stop complaining.

If creating an issue for an **actual** issue is complaing to you then I'll ensure to avoid you like the plague as your comment is unwarranted and just adds noise.

**Comment by mitchej123** [comment]
You were given alternatives, and refuse to listen to them.

**Comment by Dream-Master** [comment]
@spannerman79 I'll take care when I update the pack to 2.0.9.0 soon.

**Comment by Dream-Master** [comment]
I reopen it as reminder for an curse/twitch update

**Comment by TOLoneWolf** [comment]
https://github.com/micdoodle8/Galacticraft/blob/master/LICENSE.txt
```
For the avoidance of doubt, the distribution or copying of Galacticraft

on mod download or re-distribution websites is PROHIBITED.  (But bona fide

modpacks comprising multiple mods, distributed through CurseForge or FTB or

Technic platform or similar sites, are permitted in accordance with the modpack

permission in section 37 below.)
```

**Comment by Dream-Master** [comment]
@TOLoneWolf we hav persmission to use a own version of GC. Will be in GTNH 2.0.9.0

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/Galacticraft/blob/MC1.7/LICENSE-GTNH.txt

 
Permission to modify, build, and distributed a modified version provided to the GTNH team by
Radfast (Galacticraft Dev)  - https://github.com/micdoodle8/Galacticraft/issues/3452

```
Radfast: Yes, permission granted to fork the source and build a modified version of Galacticraft 1.7.10 for this purpose. 
But you must make sure all support requests and issue reports for the modified version come to you, not here ...
```

**Comment by spannerman79** [comment]
Resolved with https://www.curseforge.com/minecraft/modpacks/gt-new-horizons/files/3018390
