### ISSUE TITLE
use new form of ore in palnts

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#5994]
I find gt5 has gc stone form like this. 
![-66a0e0d358dc94d1](https://user-images.githubusercontent.com/49830847/80338351-b31d5900-888e-11ea-89fe-e1cbae1b90de.png)
maybe we can change ore form from stone to the around style? 
i suggest its output will be plant stone where it spawn like it is in ow or nether

**Comment by Prometheus0000** [comment]
Please get someone else who understands english better to translate your suggestion
