### ISSUE TITLE
Storage drawer upgrade recipes are disabled in NEI

### ISSUE THREAD

**Issue by thibaut-fagart** [GTNewHorizons/GT-New-Horizons-Modpack#5995]
#### Which modpack version are you using?
2.0.8.8, using technic launcher
#
#### If in multiplayer; On which server does this happen? 
single  player
#
#### What did you try to do, and what did you expect to happen?
storage drawer upgrades recips appear in NEI but aren't craftable.
According to discord, they should be craftable
![image](https://user-images.githubusercontent.com/1150232/80365275-9a5d7500-8887-11ea-97bd-29ccbbcf38d2.png)

#
#### What happened instead? (Attach screenshots if needed)
when clicking the recipe in NEI list, its details don't appear
#
#### What do you suggest instead/what changes do you propose?

PS : i tried to reinstall the modpack using technic launcher, result did not change

**Comment by chochem** [comment]
have seen this before. this is an installation issue. A script file isnt removed properly.

Known solution: delete the storage-drawer.zs file and reinstall the pack 

Though just deleting it and restarting might even be enough.

**Comment by boubou19** [comment]
if you play solo only deleting the storage-drawer.zs will not fix anything as the MT scripts are only syncing with server when joining. So yeah make a backup of your world and reinstall the pack. If it still persists then let us know.

**Comment by Dream-Master** [comment]
@thibaut-fagart yes remove storyge drawer script then it must be working fine.
Let me know if this is fixed after you tried it or close the issue. Thanks

**Comment by mitchej123** [comment]
Didn't we remove the recipes for everything except the oak drawer, and add the rest in via Chisel?

**Comment by chochem** [comment]
> 
> 
> Didn't we remove the recipes for everything except the oak drawer, and add the rest in via Chisel?

thats completely unrelated. this is about the upgrades. which were bugged in several 8.x version but are all fixed in 8.8. Only the script file from the previous versions which is sometimes not being deleted causes issues.

**Comment by Dream-Master** [comment]
so far ik all recipes in code now

**Comment by mitchej123** [comment]
> thats completely unrelated. this is about the upgrades. 

Ah, makes sense.  Title wasn't correct and I missed the "upgrade" in the body.

**Comment by thibaut-fagart** [comment]
i'll try that shortly.
might be noteworthy that indeed, the only file in the script folder that wasn't updated when i reinstalled the pack this morning is the storage-drawer.zs  file

**Comment by Dream-Master** [comment]
storage-drawer.zs isnt anymore in use

**Comment by thibaut-fagart** [comment]
i confirm this fixed my issue, thanks for the quick reply
