### ISSUE TITLE
[Block of Calcium] Cutting machine

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#5999]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
#
Empty recipe:
![изображение](https://user-images.githubusercontent.com/47714084/80414617-fbae3400-88d9-11ea-8628-4a379e5ea6c7.png)

**Comment by Dream-Master** [comment]
@MotiasF33 was this fixed ? Why you close this ?
