### ISSUE TITLE
Sheldonite ore quadrupling recipe gives molten palladium

### ISSUE THREAD

**Issue by Glease** [GTNewHorizons/GT-New-Horizons-Modpack#6000]
#### Which modpack version are you using?
2.0.8.6 fix2
#
#### If in multiplayer; On which server does this happen? 
mp private
#
#### What did you try to do, and what did you expect to happen?
Getting palladium dust/ingot/plate only by that bartwork process
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/4586901/80422470-ca9d2600-8910-11ea-83e1-94a231d49087.png)
#
#### What do you suggest instead/what changes do you propose?
This process should be changed to give 2 palladium metallic powder and 4 purified sheldonite.

**Comment by Prometheus0000** [comment]
Why would you change the sheldonite to pmp? And halve it? Shouldn't it just be the removal of the liquid? Also, you should probably post an issue to bart's github too and link it.

**Comment by Glease** [comment]
Well I mean change the liquid to pmp, not change the solid to pmp and keep the liquid.

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by Prometheus0000** [comment]
@bartimaeusnek Did you fix this?

**Comment by Glease** [comment]
He certainly didn't. Maybe let's just call it a feature then.
