### ISSUE TITLE
White Metal Dust grants extra platinum

### ISSUE THREAD

**Issue by feliser** [GTNewHorizons/GT-New-Horizons-Modpack#6002]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Not get extra platinum
#
#### What happened instead? (Attach screenshots if needed)
![whitemetalmixer](https://user-images.githubusercontent.com/37637640/80436019-1da0ba00-88cc-11ea-813a-b3176d615423.png)
![whitemetalcentrifuge](https://user-images.githubusercontent.com/37637640/80436027-21344100-88cc-11ea-9fa6-88cda7bda28b.png)
The platinum metallic powder can turn into more than 2 pure plat dust, especially when the plat line is processed using gt++ sifter for extra return.
#
#### What do you suggest instead/what changes do you propose?
Either make centrifuging white metal give you the 2 pure plat back or just 2 plat metallic powder

**Comment by draknyte1** [comment]
@bartimaeusnek 🤦🏻‍♀️
