### ISSUE TITLE
Serious Galactic Craft Oxygen Bug (2.0.9-Dev)

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#6004]
This occurred on the latest 2.0.9 Dev instance on the Zeta server. I went to a couple of planets and something felt off; my oxygen depleting much faster than usual and taking damage from the "no oxygen" mechanic much more quickly. As it turns out, this occurred over numerous planets. The bug appears to _"increase the tick speed"_ of the oxygen depletion by a factor of around **2-5x times** the amount. With this in mind, you will rapidly lose oxygen and die VERY quickly if you are not swift in switching out your oxygen canisters. I am unsure as to what, who, or why this bug is occurring, but this should be investigated thoroughly (ain't GC a fun little bug-free mod?).

**Comment by Dream-Master** [comment]
not changing anything in gc or gs

**Comment by ScriptedPiky** [comment]
Has anything been changed in Thermos or something to cause a major tick increase? Will check this in single-player if it's a multi-player issue.

**Comment by ScriptedPiky** [comment]
Can confirm that this occurs in single-player as well.

**Comment by Glease** [comment]
The only way for this to happen is some mod increasing `EntityPlayerMP.ticksExisted` on its own, or simply deliviering extra update to the player entity. Could you please get a decayable and see how fast it decay?

**Comment by Glease** [comment]
This is fixed by GTNewHorizons/BetterQuesting@4f5a37babdfcbbc2e55f900d83efbe8
