### ISSUE TITLE
2.0.8.9 Thaumic Restorer crash

### ISSUE THREAD

**Issue by JackMeds** [GTNewHorizons/GT-New-Horizons-Modpack#6005]
#### Which modpack version are you using?
2.0.8.9
#
#### What did you try to do, and what did you expect to happen?
Place Thaumic Restorer
#
#### What happened instead? (Attach screenshots if needed)
The client will crash, but the server will not

client crash report：   https://paste.ubuntu.com/p/XhphNRQbWr/

server log ：    https://paste.ubuntu.com/p/h59ZgyqqFs/    ----From 18:52:30

**Comment by draknyte1** [comment]
Already fixed.

**Comment by JackMeds** [comment]
> Already fixed.

2.0.9.0?

**Comment by draknyte1** [comment]
No clue. I just know I’ve already fixed it. 🤷🏻‍♀️

**Comment by JackMeds** [comment]
🤷🏻‍♀️fine

**Comment by GeicowithaBango** [comment]
iirc your fix is causing that problem. we had the issue too.

**Comment by draknyte1** [comment]
Which is why I removed it the version after it was added. 🤦🏻‍♀️

**Comment by GeicowithaBango** [comment]
doesnt 8.9 has your newer fix already?

**Comment by JackMeds** [comment]
> Which is why I removed it the version after it was added. Hence why it’s fixed. 🤦🏻‍♀️

Wait a second, i use 2.0.8.9.dev4.  So what version should I use now?

**Comment by GeicowithaBango** [comment]
gg

**Comment by Dream-Master** [comment]
Test with 2.0.9.0-pre4-dev

**Comment by Dream-Master** [comment]
link 8 will add later

**Comment by Dream-Master** [comment]
link I will add later

**Comment by Dream-Master** [comment]
@JackMeds 
http://downloads.gtnewhorizons.com/Dev-Pack/Pack/GTNH-1.7.10-2.0.9.0-pre4-dev.zip
try this version and report here. Thanks

**Comment by JackMeds** [comment]
@Dream-Master  No more crash 👍
