### ISSUE TITLE
GTNH block based solar panels dont produce power at night, unlike their cover counterparts

### ISSUE THREAD

**Issue by SpwnX** [GTNewHorizons/GT-New-Horizons-Modpack#6009]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon official gtnh server
#
#### What did you try to do, and what did you expect to happen?
expect 1/8 'lunar' panel production from GTNH block solar panels
#
#### What happened instead? (Attach screenshots if needed)
0 EU/t
#
#### What do you suggest instead/what changes do you propose?
Make all GTNH block solar panels (that are based on GT solar covers) produce 1/8 of their day production during night, because GT solar cover panels do.

**Comment by AiramProvoker** [comment]
I assume you're talking about the solars from Advanced Solar Panels? Yeah, it's a bit of a weird tweak, considering that by the time you get meaningfully powerful panels from here, you have access to Garden/Void dim, which provides you with constant day time.
I think it could even be buffed to 1/4, so that:
Advanced Solar Panel is 8eu/t at night;
Hybrid is 32 eu/t at night;
Ultimate Hybrid is 128 eu/t at night etc.

**Comment by Dream-Master** [comment]
@SpwnX that solarpanels works in night make no sense . Gt not output eu and advanced solar panels also. I set it to 0 in the cfg a long time ago.

**Comment by Dream-Master** [comment]
general {
    I:AdvancedSPGenDay=32
    I:AdvancedSPGenNight=0
    I:AdvancedSPOutput=32
    I:AdvancedSPStorage=320000
    I:HybrydSPGenDay=128
    I:HybrydSPGenNight=0
    I:HybrydSPOutput=128
    I:HybrydSPStorage=1280000
    I:QuantumSPGenDay=2048
    I:QuantumSPGenNight=0
    I:QuantumSPOutput=2048
    I:QuantumSPStorage=20480000
    I:UltimateHSPGenDay=512
    I:UltimateHSPGenNight=0
    I:UltimateHSPOutput=512
    I:UltimateHSPStorage=5120000

**Comment by Glease** [comment]
> Gt not output eu and advanced solar panels also. I set it to 0 in the cfg a long time ago.

Yes but OP was specifically talking about [solar panel covers](https://github.com/GTNewHorizons/GT5-Unofficial/blob/b86cbc9abb4a0d79fabc604fe4ebf044feb608f6/src/main/java/gregtech/common/covers/GT_Cover_SolarPanel.java#L47), which has no config option to tweak their output.

As my tests on 2.0.8.6 goes, the covers do output power during night.

**Comment by Dream-Master** [comment]
oh gt ones does it? I am wondering and want to test it now

**Comment by Dream-Master** [comment]
That need to be fixed.

**Comment by AiramProvoker** [comment]
Well, Dream, if want to talk about realism, solar panels producing energy during night DOES make sense, but only if it's full moon. Moon light is nothing but a reflected sunlight. However, they would only produce a fraction of their nominal output.

**Comment by Dream-Master** [comment]
no i mean if the advanced not producing energy at night the gt not doing it either.
