### ISSUE TITLE
Iron Tanks is uncraftable

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#6010]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
SinglePlayer
#
#### What did you try to do, and what did you expect to happen?
Tanks(Copper, Iron, Silver, Gold, Diamond, Obsidian) for fluid hatches above LV isn't have recepies, so input/output hatches MV-ZPM is uncraftable.

**Comment by chochem** [comment]
They all work in 2.0.8.8. Both Shaped Crafting and Assembler. Might be something with your installation. The mod is *iron tanks* by the way.

I would try making a backup and then doing a clean reinstall of the pack.

**Comment by Retster** [comment]
Will try to check after reload server, maybe recipes was not loaded properly.

**Comment by MLellmann** [comment]
Neither did it work for me. I did get error messages while starting up single player telling me that irontanks.zs did have script errors because it did not find emeraltank - which does not show up in NEI either. 

For me it looks like the iron tanks mod in the newest version is not the correct one, but an older one that is missing it and thus resulting in this error. 

A quick solution for me was to remove the 3 or 4 lines from the irontanks.zs script file referencing emerald tank (or the upgrades).

**Comment by chochem** [comment]
@MLellmann hmm, emerald tanks were only added in 8.9 I think. Did you maybe mix the two versions somehow?

**Comment by MLellmann** [comment]
No, the version is the 2.0.8.8 for Multi-MC download

**Comment by MLellmann** [comment]
Did re-download both versions and only the Multi-MC version has the emerald tank in the irontanks script file.

**Comment by chochem** [comment]
thanks for checking! which files exactly have the problem? I also have 8.8 multimc (client, from the dropbox linked in discord announcements) and even just redownloaded to confirm they dont have that problem.

**Comment by Prometheus0000** [comment]
Do you mean GTNewHorizonsClient-1.7.10-2.0.8.8-MMC.zip?
Or GTNewHorizonsClient-1.7.10-2.0.8.8.zip?
I have the latter, and don't have the emerald tank (I think, I'm not ingame)

**Comment by MLellmann** [comment]
It is the file downloaded from 

http://downloads.gtnewhorizons.com/Multi_mc_downloads/

**Comment by Prometheus0000** [comment]
That's the first file. Try the second one and see if it works.

**Comment by chochem** [comment]
@Prometheus0000 the other one is 8.3

I am not sure who is packing these mmc downloads sadly.

**Comment by Prometheus0000** [comment]
The second one mentioned in my previous post, which is under http://downloads.gtnewhorizons.com/ClientPacks/ instead of http://downloads.gtnewhorizons.com/Multi_mc_downloads/

I also don't see the point of them? What's even different? Is it an installer? Are people incapable of deleting folders and replacing files?

**Comment by chochem** [comment]
whats different: you can press the import button.
is there a point to that? not really.

**Comment by Retster** [comment]
"A quick solution for me was to remove the 3 or 4 lines from the irontanks.zs script file referencing emerald tank (or the upgrades)."
Same, i download the 2.0.8.8 pack from http://downloads.gtnewhorizons.com/Multi_mc_downloads/
GTNewHorizonsClient-1.7.10-2.0.8.8-MMC
Not notised that before your post, but then find in chat that message:
https://i.imgur.com/j1LocTc.png
than i comented that strings and after reload the game not assembler craft for iron tanks is appear, but in chat was new related errors:
https://i.imgur.com/dXJMQFr.png
today i remowed also this lines and related stuff and now irontanks recipes is working in assembler too, but still have the single error message in game chat:
https://imgur.com/a/T1C2CfS

**Comment by chochem** [comment]
@Dream-Master can you remove or fix the 2.0.8.8-MMC from the downloads? or have you fixed that file already?

**Comment by Dream-Master** [comment]
nope

**Comment by chochem** [comment]
lets try this differently then: do you know how to best contact malianx or whoever it is that packs&uploads these?

**Comment by Dream-Master** [comment]
I check the file when I be back home. In 2.0.9.0 dev the recipes worked

**Comment by chochem** [comment]
everything works in 8.8 as well with every other download. it just seems to be the specific file, GTNewHorizonsClient-1.7.10-2.0.8.8-MMC in the Multimc downloads, that likely has a 8.9dev file mixed in by mistake or something like that.

**Comment by Dream-Master** [comment]
could be. Need to check later
