### ISSUE TITLE
NEI crash - Refined Iron

### ISSUE THREAD

**Issue by Prunebane** [GTNewHorizons/GT-New-Horizons-Modpack#6011]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Was looking at Refined Iron's uses (recipes it's used in) - clicked through different crafting tabs, I think I was going into "Compressor" (never saw the tab, judging by crashlog)
#
#### What happened instead? (Attach screenshots if needed)
CTD - crash reports "/ by zero"
[crash-2020-04-30_18.55.09-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4559902/crash-2020-04-30_18.55.09-client.txt)

**Comment by mitchej123** [comment]
Ugh.  Another GC issue.  I'll look into handling their error, had a similar one with fluids

**Comment by Dream-Master** [comment]
i try to reproduce the issue but not get any crash

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/80911153-e7809180-8d34-11ea-8535-a29181f42dde.png)
![image](https://user-images.githubusercontent.com/2970688/80911163-ec454580-8d34-11ea-9ba0-ab5ac7f36632.png)

**Comment by mitchej123** [comment]
The entire handler has been removed as of 2.0.9+
