### ISSUE TITLE
[Bug] Infinite Haste + Invincibility Glitch

### ISSUE THREAD

**Issue by Regian24** [GTNewHorizons/GT-New-Horizons-Modpack#6012]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
I had accidentally drank the Real Bottled Jagermeister from Crops++, and it gave me 1 hour of nausea, water breathing, strength, regeneration, resistance, fire resistance, and water breathing.
I was trying to kill myself so I could get rid of the annoying 1 hour nausea effect. So I used a splash potion of damage (I was in the TwilightForest, because that's where we keep our potions, but it shouldn't matter). 
#
#### What happened instead? (Attach screenshots if needed)
Instead of getting damaged, I didn't get damaged (Because I had regeneration effect), but it put all of my effects to **:** duration. Then I used terra wart to get rid of the nausea, and now I basically have infinite haste and invincibility effect. It has been an hour and a half and they haven't gone away.
#

**Comment by boubou19** [comment]
where tps at 20?

**Comment by Regian24** [comment]
I logged in after two hours, now the effects are at 17:32 and are ticking at normal speed (not affected by TPS). This is so weird

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea on this?

**Comment by MotDT** [comment]
It looks like an old bug 1.4.7, when after using the potion of invisibility and death, it was saved until relog

**Comment by Prometheus0000** [comment]
@bartimaeusnek Crops++ is yours.

**Comment by rem821** [comment]
This is still present in version 2.6.1. Had to kill myself using /kill.
