### ISSUE TITLE
Bee: no specific comb production with Naqadria bee

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6013]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
mxftb
#
#### What did you try to do, and what did you expect to happen?
apiary with naquadria bee on naquadria block in end biome (sky) 
I expect: 15% naq combs, 20% naquadria combs
#
#### What happened instead? (Attach screenshots if needed)
![no_naq_Comb_01](https://user-images.githubusercontent.com/7759876/80778698-8a84b000-8b69-11ea-808c-6ec8ac780a08.JPG)

#
#### What do you suggest instead/what changes do you propose?
it seems, new dependency to original biome, as (in game itselfe) undocumented feature doesen't work.

**Comment by Ngar1** [comment]
same as plutonium bee:
![no_naq_Comb_02](https://user-images.githubusercontent.com/7759876/80779067-d421ca80-8b6a-11ea-8570-3013015add7e.JPG)
![no_naq_Comb_03](https://user-images.githubusercontent.com/7759876/80779075-d84de800-8b6a-11ea-82e0-f285476d35eb.JPG)




What bee types are also changed?
How I can get right combs? (Nether/End/ are weekly resettet, in this case not usable)

**Comment by sthegreat** [comment]
The biome itself is not what allows bees to work properly, but rather it is having the bees' preferred temperature and humidity values, i.e. the ones the bees could work in without any tolerance stats. Check that the temp and humidity shown by the alvearies are the ones the bees prefer, if not, fix it by changing biomes or using the alveary upgrades to change the temp and humidity.

**Comment by Ngar1** [comment]
I changed the temp and hum of the bee to 5/5, that means, it should work

**Comment by chochem** [comment]
no. tolerance is not sufficient for specialty output. follow what sthegreat said.

**Comment by Ngar1** [comment]
1. biome dependence or not?
2. were is the decription in the game, that the biome specific temp/hum hast to bee fulfilled for comb production?

**Comment by chochem** [comment]
1. not
2. its just how forestry works. check any wiki. Dont know if that info is anywhere ingame, probably not.

**Comment by Ngar1** [comment]
2. is not true at my experence. If tolarance and flower is right or changed to the inviorment, the bee produce the combs. Independently, where the bee comes originaly from.

**Comment by chochem** [comment]
only the normal ones. not specialty.

**Comment by chochem** [comment]
the only ingame documentation I found one the fly is the Smouldering Bee Quest. There might not be anything from Forestry and its addons, I dont know.

**Comment by Ngar1** [comment]
It is possible to change the biome with thaumcraft, what I had done in this case.
If you change to desert or nether, the temperature and humidity change, but if you change it to sky it does't work. This seems to be the problem?
![Thaumcraft_biome_change01](https://user-images.githubusercontent.com/7759876/80785067-6c29af00-8b7f-11ea-90f6-c58a37d1ed0f.JPG)

**Comment by Ngar1** [comment]
please add documentation for specific combs in bee info in this modpack. (that change of tolerance of bee it selfe does not work for specific combs)

Problem of this case was failing of witched gadget biome change to sky, because hum/temp was not changed. -> new issue

**Comment by chochem** [comment]
actually, looks like the mechanic is already clearly explained in the basic bee guide in the quest book (basic bee stats). So I guess that should satisfy you?

**Comment by Ngar1** [comment]
I found this information just at smoulding bee and at no other bee (tested: plutonium, stickyresin, refined,...) with speciality comb. The relation "speciality combs needing orign biome or changed enviroment by alveary" as general statement would easier to prevent questions in future.

**Comment by Glease** [comment]
End biome's humidity and temperature is changed by HEE to normal/normal. It's not a specific problem with witching gadgets.

**Comment by leagris** [comment]
Thing to know about bees temperature computation: It is also altitude dependent. At Y=64, temperature is biome nominal, it decreases upward and increase downward

**Comment by Prometheus0000** [comment]
Is that mentioned anywhere else on the internet? I did check and see it's true though.

**Comment by chochem** [comment]
> 
> 
> I found this information just at smoulding bee and at no other bee (tested: plutonium, stickyresin, refined,...) with speciality comb. The relation "speciality combs needing orign biome or changed enviroment by alveary" as general statement would easier to prevent questions in future.

@Ngar1 I guess I need to repeat myself because you didnt actually read what I wrote:
The speciality mechanic is clearly explained in the basic bee guide in the quest book. quest: basic bee stats

I am pretty sure this issue can be closed.

**Comment by Prometheus0000** [comment]
Ngar, if you want more information, look up jubilant for bees. Otherwise, someone needs to fix what HEE messed up, but that belongs in #6015
