### ISSUE TITLE
Crystal processor receipt missmatch

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6014]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
myftb
#
#### What did you try to do, and what did you expect to happen?
have to change receipt of crystal processor (its IV!)
- original
![crystal_CPU_receipt_03](https://user-images.githubusercontent.com/7759876/80782549-ed307880-8b76-11ea-8676-4fbed01b6854.JPG)
- with standard assembler: = nerfed 6 times!
![crystal_CPU_receipt_01](https://user-images.githubusercontent.com/7759876/80782576-0e916480-8b77-11ea-9e72-460150a44081.JPG)
 
- with the new (and hopefully working circuit assembly line)
![crystal_CPU_receipt_02](https://user-images.githubusercontent.com/7759876/80782623-3b457c00-8b77-11ea-918c-512a35139e8f.JPG)
same ratio as old one

This change is to extrem.  May be factor 2, to improve the value of the cir ass line. is ok.

In large and old Fabs/Worlds it is not nice to change every time every thing.
I don´t build just cobble blocks or caves, so every huge change should have a value for the game (new ways, new solutions, new uses, new views, nicer builds, new intraworks), not just to make it more complicate.

eg Ass Line: 
More important is a good solution for a working interface between assembly lines and ME. Actual you have  to configure filter or programming receipt wise - it is a useless double work for nothing.

**Comment by Glease** [comment]
FYI you can change the config option `Tier to nerf circuits` in `bartworks.cfg` to -1 to disable this change completely

**Comment by Ngar1** [comment]
not on a server (I am on myFTB)

**Comment by Dream-Master** [comment]
myFTB is a mp Server right?

**Comment by Ngar1** [comment]
yes

**Comment by Prometheus0000** [comment]
It is intended behavior for circuits that use LuV tier voltage+ to use more components to make you use the circuit assembling line.

**Comment by Ngar1** [comment]
If the use of circuit line assem is pressed, a solution for a direct ME Interface would be nice as "Entschädigung" ;-)

**Comment by Prometheus0000** [comment]
I have no idea what you mean. If you want it changed on your server talk to your server owner. They can change the tier it occurs in addition to turning it off.

**Comment by 0lafe** [comment]
>More important is a good solution for a working interface between assembly lines and ME. Actual you have to configure filter or programming receipt wise - it is a useless double work for nothing.

You're missing something if you mean AE input translation to Circuit assembly line. The item inputs aren't the hard part, you can do that easily. Each circuit assembly line controller is bound to a single Circuit, and can only produce that circuit. If you wish to combine inputs you'll need to swap controllers which is a lot worse than item input. 

The idea is to make you make 1+ per circuit

**Comment by Ngar1** [comment]
perfect for server load: one machine per receipt...

@Prometheus0000 I did it in parallel, but they are so busy, they couldn't activate Barts planets to get new ores. myFTB.de is the 2. large GTNH EU-Server -> alternativless.
