### ISSUE TITLE
Bees that require for mutation a block under the hive cannot be breed

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#6016]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Single player
#
#### What did you try to do, and what did you expect to happen?
Trying to make new thorium bee, setup is same like in 8.3: alveary, mutagenic frames block of thorium under. But after ~ 15 attempt its behavior is look exactly like required block is missing. 
After that for testing i trying to make the bees that i already maked in 8.3, Chrome bee. And here is appear is same issue. it's imposible to make it even with chrome block that i already use before.
updated the pack recently and continue my bee breeding.
#
#### What do you suggest instead/what changes do you propose?
Fix pls. My progress is stuck.

**Comment by Prometheus0000** [comment]
Duplicate of #5816

**Comment by Retster** [comment]
> Duplicate of #5816

Thank you, with wersion of forestry menitoned in this link mutations goes right. 
Issue can be closed.
