### ISSUE TITLE
save broke

### ISSUE THREAD

**Issue by ponenerve** [GTNewHorizons/GT-New-Horizons-Modpack#6018]
#### Which modpack version are you using?
2.8.8.0
#### If in multiplayer; On which server does this happen? 
solo
#### What did you try to do, and what did you expect to happen?
i just missclicked the cross to excape the window
#### What happened instead? (Attach screenshots if needed)
save wasnt present anymore on the saves list
#### What do you suggest instead/what changes do you propose?
getting back my save would be a good start but if you have an ideo on where it could have gone and if i can get it back in some way

**Comment by Prometheus0000** [comment]
Restore from backup. If you don't have one, search for similar issues on the discord server. And use a backup mod next time.

**Comment by GTNH-Afx237v7** [comment]
Is the save file there in the Minecraft folder? If yes, but it cannot be selected, create a new world and replace the files with your previous save.

**Comment by Dream-Master** [comment]
there is a save folder
![image](https://user-images.githubusercontent.com/2970688/80910908-08e07e00-8d33-11ea-8e43-08e96dca878f.png)

Use Aroma Backup next time
[Aroma-Bachup.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4569914/Aroma-Bachup.zip)
