### ISSUE TITLE
GraviChestPlate recipe should work with all zpm circuits

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6020]
#### Which modpack version are you using?
2.0.8.8
#
#### 
The GraviChestPlate requires 2 ZPM circuits. However, currently only the Ultimate Crystalcomputer is allowed.

In pretty much ever other recipe in the pack circuits of the same tier are interchangeable.

Suggested change: Also allow other ZPM circuits like the Quantum Processor Mainframe.

**Comment by Dream-Master** [comment]
@chochem so far ik they work with all circuits but shows only one circuit

**Comment by chochem** [comment]
I tried it with the mainframes. It did not work. The moment I switched the zpm circuits to Ultimate Crystalcomputers the recipe started.
