### ISSUE TITLE
CO/CO2/SO can’t be recovered by EBF.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6022]
#### Which modpack version are you using?
2.0.8.3～2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Privet Server and Single
#
#### What did you try to do, and what did you expect to happen?
I installed an output hatch on the top of the EBF and tried to recover the CO/CO2/SO.
#
#### What happened instead? (Attach screenshots if needed)
I couldn't recover them.
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by draknyte1** [comment]
You realise this only applies to like a handful of recipes right?

**Comment by Glease** [comment]
If you are using a LV muffler then nothing can be recovered. Please attach a screenshot of your EBF setup. It is working fine on my end.

**Comment by yukieiji** [comment]
It's my EBF.
![2020-05-03_01 56 26](https://user-images.githubusercontent.com/40425798/80870451-7663be80-8ce1-11ea-862b-3aa7b69b1c93.png)
![2020-05-03_01 56 17](https://user-images.githubusercontent.com/40425798/80870447-719f0a80-8ce1-11ea-93a0-1061d4160270.png)
![2020-05-03_01 56 29](https://user-images.githubusercontent.com/40425798/80870452-76fc5500-8ce1-11ea-888c-de74c1a64d6e.png)

**Comment by yukieiji** [comment]
@draknyte1 Is this true? For example, what kind of recipes does this apply to?

**Comment by Prometheus0000** [comment]
The ones that say they have them as output? Maybe silicon dioxide to silicon ingot for example?

**Comment by Dream-Master** [comment]
you not got the full amount of fluids back but with higher tier mufflers you get more and more back.
I am not sure if the hatch have to be on top.

**Comment by draknyte1** [comment]
> hatch have to be on top.

It does.

**Comment by Prometheus0000** [comment]
Did you figure it out? Can this be closed now?
