### ISSUE TITLE
The Erebus

### ISSUE THREAD

**Issue by Zoko061602** [GTNewHorizons/GT-New-Horizons-Modpack#6024]
## What do you suggest instead/what changes do you propose?
It was already proposed to add the Erebus to GTNH, however due to some conficting biomes ids it was not possible to add this mod, since the author did not accept my pull-request. So created a small core mod to change the biome ids in Erebus.

I think it would be a great addition to the magic and adventure questline, since it adds many new and dangerous creatures.

The coremod can be found here: https://github.com/Zoko061602/ErebusPatcher

**Comment by draknyte1** [comment]
Why have a main mod class that doesn’t do anything? Pre/Post/Init are all empty, so it’s kinda redundant.

**Comment by Zoko061602** [comment]
I could have also made a DummyModContainer, doesn't really make a differnce

**Comment by Prometheus0000** [comment]
Rather than adding new content, shouldn't we balance/fix the existing content first? Like bio-stuff, teleportation, etc.

**Comment by noobnoobnub** [comment]
Ewww bugs!

**Comment by bartimaeusnek** [comment]
We already has this suggestion a while ago and it was said to be NOT ADDED due to the license.
