### ISSUE TITLE
Recipe conflict

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#6025]
#### Which modpack version are you using?
2.0.9.0 dev
#
Fluid regulators should have a programmed circuit added to the recipe as to prevent a recipe conflict from occuring. We had this happen to us while trying to use the new recipe for the fluid drilling multiblock.

<img width="344" alt="Screenshot 2020-05-02 at 21 44 26" src="https://user-images.githubusercontent.com/54497873/80891761-232c4480-8cbe-11ea-8d5c-28486fb70f8a.png">

<img width="350" alt="Screenshot 2020-05-02 at 21 44 39" src="https://user-images.githubusercontent.com/54497873/80891762-24f60800-8cbe-11ea-95a9-bc94b4844cc9.png">

**Comment by Dream-Master** [comment]
yes fluid regulator need a ontrol circuit too.
