### ISSUE TITLE
Bee: light gray bee or larve change in hand to silver bee

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6026]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
myFTB.de
#
#### What did you try to do, and what did you expect to happen?
light gray bee or larvae change in hand to silver bee

 
![Bee_Light2Silver](https://user-images.githubusercontent.com/7759876/80907353-cdd05180-8d16-11ea-90b8-c05f81ed5814.JPG)

![Bee_Light2Silver2](https://user-images.githubusercontent.com/7759876/80907356-d3c63280-8d16-11ea-9b15-221b0783ea6a.JPG)

**Comment by Dream-Master** [comment]
maybe the converting code from gendustry to Gt bees work here.
@bartimaeusnek did you have any idea on this ?

**Comment by Ngar1** [comment]
testet with GTNH-1.7.10-2.0.9.0-pre7-dev.zip same world, SP -> solved

No more change to Silver bee at light gray bee or lavae

**Comment by Ngar1** [comment]
Sorry, failure is unsolved at Multiplayer

**Comment by Ngar1** [comment]
in single player (same world!) grey bee doesn't change to silver....

**Comment by Ngar1** [comment]
Any plan to solve?

**Comment by Dream-Master** [comment]
Not sure who can help us with this issue. Not sure who is familiar with binnies mods code.

**Comment by Ngar1** [comment]
Not solved in 2.1.1.0
grey bee change in silver if it is in inventar

**Comment by Ngar1** [comment]
Not solved 
tested in SP with 2.1.1.3

**Comment by DianeXD** [comment]
I guess it's here? Why convert the bees
https://github.com/GTNewHorizons/GT5-Unofficial/blob/dbd0e98223f34787e557b7d4357d3480955db4d9/src/main/java/gregtech/common/GT_Proxy.java#L1596-L1694

**Comment by DianeXD** [comment]
> why it convert light grey bees to silver bees. It should only convert old gendustry silver bees to new gt silver bees?

Because the bees have the same species name, but now still need to convert the bees? Have all custom gendustry bees been moved to GT or am I wrong?

**Comment by Dream-Master** [comment]
We using long time ago a config file from gendustry with a bunch of custom bees. This bees goes into gt code done day. So we add the convert code to keep peoples progress . Maybe we need to remove the convert code because it’s no longer needed? @boubou19 what are you concerns ?
