### ISSUE TITLE
Change the mechanics of chest buffers

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#6027]
I propose to change the mechanics of all chest buffer. At the moment, they fill all available slots with the amount that we indicate with a screwdriver. However, this does not work with input bus. Since he compresses all the objects in one slot (and continues to do this until his place in it ends). This is not convenient when working with multi-block mechanisms - when you need to lay down a fixed number of items without overflow. Alternatively, change the mechanics of the chest buffers so that they fit in only one slot. Or they did a check "is there a current item in the input bus" and if there is an amount that is indicated by a screwdriver - do not put anything down (so I think this option is preferable).

**Comment by chochem** [comment]
Just switch to 'transfer size mode'.

no mechanics need changing.

**Comment by PredVesTNiK2142** [comment]
In "transfer size mode" the problem is exactly the same. He continues to score until the place runs out.

**Comment by Glease** [comment]
Or simpler, *Shift + right click with screwdriver to turn Sort mode off*.

**Comment by chochem** [comment]
if this is not what you are looking for, can you please describe your actual specific problem in more detail?

**Comment by PredVesTNiK2142** [comment]
Hmm ... And this is more interesting. This way it works. Thank.

**Comment by Glease** [comment]
Seem like you are withdrawing your proposal. Closing now. Feel free to reopen if you feel a change is necessary.
