### ISSUE TITLE
Magnalium Crossbow bolts #1154, 4/5 quest never counted

### ISSUE THREAD

**Issue by Zaharu** [GTNewHorizons/GT-New-Horizons-Modpack#6028]
#### 2.0.8.8

#
#### I tried to submit the quest with 2 different types of magnalium bolts(gold and magnalium tips) 

#
#### unfortunately it had been counted only when i got the bolt from creative mode

#
####

**Comment by Zaharu** [comment]
![magnal1](https://user-images.githubusercontent.com/64740016/80917563-69d67900-8d68-11ea-923c-419ac1824e00.png)
![magnal2](https://user-images.githubusercontent.com/64740016/80917565-6ba03c80-8d68-11ea-93e8-f987647538f3.png)

**Comment by Prometheus0000** [comment]
Doesn't it need an iron tip?

**Comment by Prometheus0000** [comment]
The last step says iron bolts, and even mentions about molten iron in the text (in the 2.0.9.0beta1 version). And it detects properly.
