### ISSUE TITLE
Massive lag when player looks directly to storage drawer with combs.

### ISSUE THREAD

**Issue by ZorbaHerbalist** [GTNewHorizons/GT-New-Horizons-Modpack#6029]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Storage drawers causes massive lags when store different combs, another items (ex. dusts, ingots) don't cause lags. Lags happened when player looks directly to storage drawer which contains combs.

**Comment by Prometheus0000** [comment]
Try the concealment key for now.

**Comment by ZorbaHerbalist** [comment]
Already tried, doesn't help.

**Comment by StopZone** [comment]
After some testing, I found that this bug only occurs with bee combs added by gregtech. basic forestry combs work as normal in storage drawers.

**Comment by KiloJoel** [comment]
Just encountered this. Profiled it and it seems to be writing to a file constantly. The framerate drop is massive for me
![image](https://user-images.githubusercontent.com/17787093/154864381-e5ba475c-ac29-41d7-9b4c-3f8c12341fb4.png)

**Comment by bombcar** [comment]
> Just encountered this. Profiled it and it seems to be writing to a file constantly. The framerate drop is massive for me
> ![image](https://user-images.githubusercontent.com/17787093/154864381-e5ba475c-ac29-41d7-9b4c-3f8c12341fb4.png)

Can you save the roast as web page comolete and load it into this ticket? @mitchej123 loves roasts

**Comment by KiloJoel** [comment]
that's from visualvm, i could share the snapshot file maybe

**Comment by Glease** [comment]
This is also why I'd like a reword of GT localization system. The only people like it would be English speaking developers. Non English speakers got frustrated that they must *somehow* acquire a community translation from nobody. Translators would need to work on a non faimiliar .lang format, and the generated .lang is always incomplete.

However since I *am* an English speaking developer, there is very little incentive for me to actually work on this issue...

**Comment by NoX-programer** [comment]
The issue is still exists and annoying. Is it anythyng can I help with? Profile something or else? (however, please describe in more detail what exactly to run and how to profile, since I have no experience in this)
