### ISSUE TITLE
Duping Buckets with RC tanks

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#6031]
With the newest GTNH version it is possible to duping Buckets in RC Tanks.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/80919181-fd0fae80-8d68-11ea-880d-1402e439988a.png)
![image](https://user-images.githubusercontent.com/2970688/80919185-04cf5300-8d69-11ea-96ca-a77fa6d4da52.png)

**Comment by botn365** [comment]
i have tried the dupe with and without gt++ in the pack
with gt++ it duped the bucket
without gt++ it is not duping the bucket

**Comment by Hyperic88** [comment]
I just tried that. RMB with empty bucket on RC tank with GT++ installed does nothing bad, just filling bucket. Placing that bucket in slot just fills the bucket too... no dupe at my place

**Comment by draknyte1** [comment]
Probably related to my fix on boiler item usage. Make me a ticket and I’ll take a look.

**Comment by Prometheus0000** [comment]
Which fix? Does it fix BM lava crystals getting eaten?

**Comment by draknyte1** [comment]
No, it just fixes a function used by RC to handle item consumption. Worked as far as I could test and it’s been around for a while.. so it shouldn’t be a *new* bug.

**Comment by Prometheus0000** [comment]
Ah, I forgot you were talking about the RC boiler. I didn't check that one, but the BM LC does nothing  in the GT normal and high pressure boilers, while your LV/MV/HV ones eat it. Should the GT ones work at all, or is the problem only yours eating it?

**Comment by draknyte1** [comment]
GT boilers have hard coded fuel lists. Mine accept anything that a furnace does. It’s intended.

**Comment by Prometheus0000** [comment]
So your boilers are supposed to eat the BM lava crystals? That's not how the crystals are supposed to work, you know?

**Comment by draknyte1** [comment]
If they have burn value, they can be used. 🤷🏻‍♀️

All I do is ask the furnace for the fuel list and use that, lol.

**Comment by draknyte1** [comment]
Fixed in Dev. (1.7.05.68)
