### ISSUE TITLE
Frugal bees unobtainable

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#6032]
#### Which modpack version are you using?
9.0.
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Trying to breed Frugal bees for Uranium later on. Combined Modest princess + sinister drone, placed them in alveary with some fans in desert to achieve hot&arid and use it 10 times. Ive used also mutator with soul sand to increase chance which is 16% base... no success, not even inactive allele
#
#### What happened instead? (Attach screenshots if needed)
Nothing, just constantly switching princess and drones to Modest-sinister and Sinister-modest
#
#### What do you suggest instead/what changes do you propose?
Check that probability or so

**Comment by Prometheus0000** [comment]
Which 9.0? And is it the same bug as #5816? Did you try in sp? Does it work if you revert the forestry version?

**Comment by Hyperic88** [comment]
Its 9.0-pr4-dev

Just tested in SP and no luck, 5 runs with mutagenic frames and still switching from modest to sinister and vice versa. Not the same ive managed to get titanium ones with this version. 

Sadly cant revert to older version, dont have that...

**Comment by Prometheus0000** [comment]
Is this a bee that requires a specific block under it? Because that's what isn't working in #5816. There should be a link to the older version in the other issue. You can change the version back after testing in sp so you can still connect to the server.

**Comment by Hyperic88** [comment]
No it just requires specific temperature humidity - hot and arid , both requirements were met
![2020-05-03_20 07 17](https://user-images.githubusercontent.com/14223368/80922979-e83f1500-8d80-11ea-8d86-ffd85604f4a6.png)

**Comment by Prometheus0000** [comment]
I dunno, try asking on discord if anyone managed to breed them, and what version they were on when they did so? At the very least, gendustry allows you to skip all requirements when you get there. Maybe no-one noticed it was broken because they all did it that way?

**Comment by chochem** [comment]
I definitely bred them somewhere between 8.3-8.8, not sure exactly when. there was nothing special about it.

**Comment by Hyperic88** [comment]
> I dunno, try asking on discord if anyone managed to breed them, and what version they were on when they did so? At the very least, gendustry allows you to skip all requirements when you get there. Maybe no-one noticed it was broken because they all did it that way?

problem with gendustry is that you need uranium/naquadah combs hence those bees, and those youll get via those frugal :)))

**Comment by Prometheus0000** [comment]
Maybe something broke in 9.0, there's apparently a bunch of stuff broken.

**Comment by Glease** [comment]
Can't seem to reproduce this on pre5. However I didn't find a native Hot/Arid world so I was breeding **fiendish**+modest in nether. Please check if this works for you.

**Comment by Ngar1** [comment]
At 2.0.8.3, I have the same problem, instead of Frugal, Friendish is breeded:
![instead_Frugal_Friendish_0](https://user-images.githubusercontent.com/7759876/81282614-b0bfb980-905b-11ea-9e3e-3ac4a9771010.JPG)
![instead_Frugal_Friendish_3](https://user-images.githubusercontent.com/7759876/81282626-b5846d80-905b-11ea-88fd-3c3fd5ca4249.JPG)
![instead_Frugal_Friendish_2](https://user-images.githubusercontent.com/7759876/81282636-bae1b800-905b-11ea-91c1-ffa7ab84cdc3.JPG)
![instead_Frugal_Friendish_1](https://user-images.githubusercontent.com/7759876/81282641-bcab7b80-905b-11ea-84ed-3c3822d58dbf.JPG)

**Comment by chochem** [comment]
@Ngar1 that is unrelated to the issue and, more importantly, not a bug.

**Comment by Ngar1** [comment]
Please explain: Receipt say: Friendish=Sinister&Cultivated; Fugal= Modest&Sinister
Why shouldn´t be that Friendish is bread from Sinister&Modest not be a bug? I am realy irritated.

I tried also, that Cultivated&Sinister and breed also Friendish:
![instead_Frugal_Friendish_4](https://user-images.githubusercontent.com/7759876/81284751-d00c1600-905e-11ea-9d43-2154f78f0748.JPG)

**Comment by chochem** [comment]
100% not a bug.

If you have questions about bee mechanics please just ask in the discord instead of here.

but since we are at it already: there are more recipes then what you are listing, and yes they are in NEI (but not the tree) and crucially some combos of bees can mutate into mutable possible outcomes (this already happens with some of the basic ones).

**Comment by chochem** [comment]
@Hyperic88 back to the actual issue: I just tested it and was able to breed Frugal from modest and sinister without problems. this was done in a outback with properties hot (126%) and arid (5%) and on version 2.0.9.0 pre7-dev.

So if there actually is an issue here, it must be about the alveary. but please try a bit more first, with alveary or in the wild.

**Comment by Ngar1** [comment]
so I changed to Sinister&Modest with only one (!) breading result (in parallel NEI view): "Frugal", bread them with mutating frames more than 100 times wit accelarator. Nether biome in OW by TC.
Never got a Frugal:
![instead_Frugal_Friendish_7](https://user-images.githubusercontent.com/7759876/81287849-c638e180-9063-11ea-99fb-87b48b345bc2.JPG)
![instead_Frugal_Friendish_6](https://user-images.githubusercontent.com/7759876/81287853-c802a500-9063-11ea-8c5d-dab98e71e219.JPG)

**Comment by chochem** [comment]
> 
> so I changed to Sinister&Modest with only one (!) breading result

nope thats still not true. maybe you mean fiendish?

anyway glease already tested that combo on 9.0 and it works as posted above. if it works or not on an older version of the pack is kind of irrelevant.

**Comment by Ngar1** [comment]
This means, failures should only issued, if the server is at the newest dev version?
Since dayes I try to breed the rest of my open bees and I got more than 20% times problems.

**Comment by chochem** [comment]
> 
> 
> This means, failures should only issued, if the server is at the newest dev version?

no one ever said that. now you are just making stuff up.

let me ask you this: if something doesnt work on an old version but does work on a newer version, what kind of fix exactly do you expect to happen?

**Comment by Ngar1** [comment]
1. as I reported, the failure was not solved
2. Than you say, this is not a bug, I didn’t understand how it works
3. Than I show that this is a bug with a receipt with only one result
4. Now you say it is solved, nothing more to do...

I feel like an idiot

**Comment by chochem** [comment]
what is this pointless discussion?
ad 1/3/4: see again glease's and my post on it working in 9.0. We specifically took the time and tested it for you guys.
And ad 2: you were claiming getting fiendish is a bug which is not the case.

**Comment by Prometheus0000** [comment]
Does this help? The nether is good for either mutation, try not being in a Nether biome?
![Untitled](https://user-images.githubusercontent.com/8517039/81338409-96e19f00-907a-11ea-86cb-8779a5bd3fc1.png)

**Comment by Hyperic88** [comment]
@chochem 
maybe it was some tweaking done, bcs i had tested that in slight different version than you do ;) but will test for sure :)

**Comment by Ngar1** [comment]
testet with GTNH-1.7.10-2.0.9.0-pre7-dev.zip same world, SP 

with Mutator and nether biome (200%/0%) receipt Modest&Fiendish=Frugal work

with Apiary and nether biome (200%/0%)  and Mutagenic frames it doesn't work

**Comment by Dream-Master** [comment]
Mutagenic frame is from gt++ ?

**Comment by Ngar1** [comment]
I tried Mutagenic (GT++), Soul and Metabolic Frames, more than 50 times (mixed)

Same situation with ash bee = Coal&Clay: Mutator work, but Apiary doesn't at same biome

**Comment by chochem** [comment]
sounds like a bug with one of the frames then. Apiary is fine, and so is soul frame. Thats what I used for ash bee (see other thread). I would focus on the others.

**Comment by Dream-Master** [comment]
not sure if the mutator works in any  case and ignore bee breeding requirements

**Comment by draknyte1** [comment]
The only difference frames have code wise is a float to specify mutation rate. Rest is handled by forestry. Having a rate too high breaks stuff iirc.

**Comment by Ngar1** [comment]
At Apiary I work with wold accelerator and Oblivion frames, to get fast results

**Comment by Hyperic88** [comment]
Just bred them yesterday along with subsequent austere, hermitic, secluded and just fine ;) version 2.0.9.0-beta3 +

**Comment by Darkstar1712** [comment]
I'm having an issue with this on the latest version on zeta. Did 50+ attempts with both Modest + Sinister and Modest + Fiendish in Outback and Nether biomes(the biomes were changed with witchery but that worked fine for other bees). I tried using Mutagenic frames and Oblivion + Soul frames, haven't had a single Frugal bee.

**Comment by Benimatic** [comment]
Just as a datapoint, I tried about 100 times in a witchery changed biome (vanilla Desert) with no luck breeding. Then I moved to a naturally occurring Brushland biome, and was successful on literally the first try.

Something must be wrong with the temperature checking logic. Either it's pulling the natural biome of the area somehow, or it's not checking the exact location of the apiary.

**Comment by Dream-Master** [comment]
interesting maybe we have to review the code a bit.

**Comment by DianeXD** [comment]
Can't be reproduced in 2.1.2.4 (whether witchery alters biome or normal), I think it's fixed
