### ISSUE TITLE
ganymede stone dust mising textuer

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#6034]
#### Which modpack version are you using?
9.0beta6
#### If in multiplayer; On which server does this happen? 
SP
#### What do you suggest instead/what changes do you propose?
![Screenshot from 2020-05-04 02-31-47](https://user-images.githubusercontent.com/42187820/80929855-a5e0fc80-8daf-11ea-8442-6d8ba79bf5d6.png)

**Comment by Dream-Master** [comment]
guess because of the renaming thing

**Comment by Prometheus0000** [comment]
Already fixed
