### ISSUE TITLE
Crash while editing quests

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6035]
#### Which modpack version are you using?
GTNH-1.7.10-2.0.9.0-pre2-dev
#
#### What did you try to do, and what did you expect to happen?
Click on item in inventory (wand) to change quest req (was also alt-tabbed out (I think?) and came back, it may have been that instead)
#
#### What happened instead? (Attach screenshots if needed)
Crash
[crash-2020-05-03_21.12.17-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4572447/crash-2020-05-03_21.12.17-client.txt)
#
#### What do you suggest instead/what changes do you propose?
For the BQ3 mod author to fix it

**Comment by Dream-Master** [comment]
@SKProCH is this something we cause in the GTNH fork or is the in vanilla BQ too?

**Comment by SKProCH** [comment]
I think the problem is not on the side of my changes to the GTNH fork. But I'm not sure, maybe indirectly.

**Comment by Dream-Master** [comment]
@funwayguy can you look into this issue? Or should i copy it to your repo/issues?

**Comment by Prometheus0000** [comment]
It happened again when I was closing the tab for selecting an icon (I think).
[crash-2020-05-04_21.51.37-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4578604/crash-2020-05-04_21.51.37-client.txt)

BTW, why does dev2 use BetterQuesting-3.0.331-GTNH, while dev4 and dev6 use BetterQuesting-3.0.330-GTNH?

**Comment by Dream-Master** [comment]
@Prometheus0000 did it crash with  both versions?

**Comment by Prometheus0000** [comment]
I was only using dev2, I just noticed when I looked to see if there was a large difference in case it was something already fixed.

**Comment by Dream-Master** [comment]
I will push 2.0.9.0pre7dev today @Prometheus0000  can you test later ?

**Comment by Prometheus0000** [comment]
It's very intermittent, so I don't know if it'll happen again soon.

**Comment by Funwayguy** [comment]
I don't think I can actually fix it from my side. This crash is occurring inside vanilla tooltip code and the report wont give me the particular line in code that tripped it.

If I had to take a guess, I'd say someone's mod setup their creative tab entries wrong with null item subtype references. I can probably give you a debug build with extra logging to figure out which item caused it.

**Comment by Prometheus0000** [comment]
That's fine with me, but doesn't GTNH use a special build or something?

**Comment by Funwayguy** [comment]
It doesn't have anything special compared to what will be released publicly later. GTNH just get to test it for any notable issues early.

Just checked but there may in fact be some logged errors just before the crash occurs. Can you send a copy of the normal console log file?

**Comment by Dream-Master** [comment]
will send a full fml log next time i got a crash @Funwayguy

**Comment by Dream-Master** [comment]
https://gist.github.com/Dream-Master/fcd2621b6266b619178e0eea1d19a18e
