### ISSUE TITLE
The Big Item Filter from EIO has two recipes, one of which probably shouldn't be there

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6036]
#### Which modpack version are you using?
2.0.9.0dev2
#
The hand crafting recipe is probably the default one, the assembler recipe is probably the one for GTNH.
#
#### What do you suggest instead/what changes do you propose?
Remove hand crafting recipe, unless it should have both.

**Comment by ScriptedPiky** [comment]
There are actually multiple recipes with this similar issue. However, they would need to be properly adjusted (i.e. Melodic Alloy requiring Mysterious Crystal, a ZPM tier material).
