### ISSUE TITLE
Some adjustements

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6039]
As discussed on Discord: here are the new materials to add in the "Not Trippling Cluster List" in WitchingGadgets.cfg (not sure about the spelling as it does not seems to be oredict names):
Lutetium
Mysterious Crystal

Also: tinker's aluminum nugget must have the oredict "nuggetAluminium" removed.

**Comment by Prometheus0000** [comment]
The alu thing belongs in a separate ticket
