### ISSUE TITLE
Wrong recipes for item distributors

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#6041]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Wanted to craft some item distributors and the craft involve conveyer module and circuits.
So those should be in relation with the item distributor tier
#
#### What happened instead? (Attach screenshots if needed)
The conveyer module are adapted to the machine tier but the circuits are not
Indeed the circuits to craft the item distributors for all tiers are MV circuits
#
#### What do you suggest instead/what changes do you propose?
Put the right circuits for each tiers

**Comment by noobnoobnub** [comment]
I think it is intended, as item filter take hv circuit regardless of its tier.

**Comment by Nicouuuuu** [comment]
Well maybe, actually I just want to know if it's intended or not as you said

**Comment by Prometheus0000** [comment]
Is it intended?

**Comment by Prometheus0000** [comment]
Since all of them only take 1 EU, I'm going to assume it's intended.
