### ISSUE TITLE
How to get sodium/Lithium #622

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#6042]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Was searching for a vein of Lepidolite/Salt/Rock Salt/Spodumene, found a vein of marble ores/granite ores and I thought without a sec that they should be okay for the quest
#
#### What happened instead? (Attach screenshots if needed)
The others types of ores like marble ores/granit ores are not detected by the quest, only the stone ones work at the moment
This is annoying to found another vein just because of that
#
#### What do you suggest instead/what changes do you propose?
Making the quest recognizing the different ore variants (marble, granit etc)

**Comment by Prometheus0000** [comment]
This is not possible without exponentially expanding the size of the quest to cover all possible variations and combinations, since they all have different oredict tags, and all the GT items use the same item Id but different meta so you can't use meta either.

**Comment by Nicouuuuu** [comment]
Meh 
So this will not be possible ?

**Comment by Prometheus0000** [comment]
No. I tried, it's not possible unless a general 'material' oredict tag is added to the ores. Such as adding oreSulfur to all the stone variants. And it's not really worth it, it's not hard to find more ore usually.

**Comment by Nicouuuuu** [comment]
Okay I see,
I reported that when I was early game, I assume that new players will have to dig lmao !
thanks for trying though,
