### ISSUE TITLE
Massive lag with pyrolayse oven.

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#6043]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Setup row of 3 pryolayse ovens (all mv modules)
Setup for wood tar production with no nitrogen) circuit 9
load input bus with wood (stacks of redwood) 
Everything works fine.

Mix the wood in the input buses (add a couple of stacks of twilight oak wood to each)
Server now give messages about skipping ~150 ticks every 15 seconds, with compaints about lag from pryolase oven tile block.

stop the machines lag stops, start them and it is back.

remove the twilight oak (so just redwood). Stopps skipping ticks.

add some twilight oak back, ticks start skipping again.

If just twilight oak in the input bus also no issue, so it seems related to having stacks of different items (???that match by oredict the recipe???)

#
#### What do you suggest instead/what changes do you propose?
Resolve the matter (does it impact other machines/recipies?)

Let me know if there are specific logs that would help resolve this.

**Comment by noobnoobnub** [comment]
Have been using 2pyrolyse oven, but not experience any lag related at 2.0.8.8
I did put nitrogen into it

**Comment by drayath** [comment]
Lag was only when mixed wood was in the input bus (could add remove to enable/disable lag)

**Comment by Glease** [comment]
Do you use extracells' fluid export bus to move fluid around? They are known to be lag intensive. Try replace them with fluid interface and fluid storage bus instead

**Comment by drayath** [comment]
No. This is a new game, just as the start of the hv age. Ovens have no connection to any anything else (local power from benzene distillery/generator, wood loaded from single drawer/conveyer attached to side of oven.
-
The weirdness was that with:
a single wood type there was no lag, 
mixed wood massive lag, 
mixed wood machines disabled no lag
enable, lag
remove mixed wood (so only a single type in input bus), no lag
add mixed wood types back, lag

**Comment by leagris** [comment]
This pack has lots of Oredictionary entries for `logWood`, if the Pyrolyse Oven is re-checking recipes each time it changes wood log item, it is expected that extra lagg appears when you mix different log types in the input. Also multiple logs in the input, means unstacking logs need to check for item stack-ability each time you insert logs in the hatch. Maybe you could save on this one source of lagg by disabling the auto sorting inside the hatch.

**Comment by drayath** [comment]
From my pov of view will ensure does not happen with a mix free setup (because 150 tick server delay every time a machine starts it processing actions makes it pain to even manually stop the machines to fix it).
