### ISSUE TITLE
Disable Blast resistant ME Drive

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6045]
#### Which modpack version are you using?
2.0.8.8
#
#### 

Pretty simple proposal: disable the Blast resistant ME drive from extra cells, as well as remove its quest. Two reasons:

1) There is absolutely no reason to make it. it only holds three drives, which is horrible. And, we have plenty of other blast resistant blocks in the pack to protect your drives.

2) They are very buggy. namely, we get people posting about this bug https://github.com/ExtraCells/ExtraCells2/issues/232 regularly. The bug is not even limited to the person making the drive but affects other people around too who might not even know about the drive. Basically, that item was never finished in minecraft 1.7.

**Comment by Prometheus0000** [comment]
While you're removing stuff, could you also remove the certus quartz and nether quartz cutting knives, as they're not used to make anchors (or anything) anymore. And since there's no grindstone, removing the TE gear boxes would also make sense.

PS: I'm working on AE2 quests, so I can remove the quest myself if you decide to remove it.

**Comment by noobnoobnub** [comment]
![image](https://user-images.githubusercontent.com/50437615/81036078-44647f00-8ed0-11ea-9d4e-bee47269e733.png)
yeah very buggy

**Comment by Retster** [comment]
please leave alone certus quartz and nether quartz cutting knives, what is wrong with them? i use it to make template for inscribers to my complicated setups.

**Comment by Prometheus0000** [comment]
They can't be used for anything? What template item?

**Comment by chochem** [comment]
@Prometheus0000 I assume this: https://ae-mod.info/Inscriber-Name-Press/
works even if its not in NEI. never tried it, as I prefer the gt naming mold.

**Comment by Prometheus0000** [comment]
Well, as long as there's a use, it's fine.

**Comment by Houstonruss** [comment]
You can name AE items in an anvil so its kinda useless

**Comment by chochem** [comment]
still not disabled in 9.0. Is this more difficult than I thought it would be?

another *beautiful* picture in discord today:
![image](https://user-images.githubusercontent.com/40274384/84188485-95493380-aa8b-11ea-83a1-f6c92b79a357.png)
