### ISSUE TITLE
Write a Instructions to let player know how to play Tectech

### ISSUE THREAD

**Issue by SKYCATV587** [GTNewHorizons/GT-New-Horizons-Modpack#6046]
Tectech is a very interesting mod in GTNH, but can not find some useful information for this.There is not much information in his wiki, so please write a Instructions for tectech

**Comment by redmage17** [comment]
Needs a quest line honestly I couldn't find much info either

**Comment by GeicowithaBango** [comment]
Isnt there a quest line already? It might need an upgrade tho

**Comment by Dream-Master** [comment]
@redmage17 there is a quest line but I guess not for many devices

**Comment by Prometheus0000** [comment]
The problem is that the people who make quests don't know how to use tectech, so we can't write one. If you can convince someone who understands how it works (or even just how to build something that works), to write some quests it can be easily added. Of course Technus would be the best for that.

**Comment by ScriptedPiky** [comment]
I actually wrote a questline for TecTech, but only including the Quantum Computer and Research Station quests. Along with the Blueprint and maybe some other bits, though there is a lack of information for all the other multiblocks (most of which may or may not be usable).

**Comment by Prometheus0000** [comment]
@ScriptedPiky Do you any comment on #4707?

**Comment by ScriptedPiky** [comment]
For #4707, I'd suggest a minor rework over the text I wrote. As much of it was done a long while ago and the information & mechanics have changed recently. Although, I am entirely unsure of the rest of the multiblocks.

**Comment by Prometheus0000** [comment]
@ScriptedPiky Could you check and see if the text I wrote is good? I'm finished with the Tectech stuff with the latest PR #6268.
