### ISSUE TITLE
achivement bug

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6047]
#### Which modpack version are you using?
delta
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
https://cdn.discordapp.com/attachments/657592172899467285/707144394913874012/unknown.png   you can never craft a coil so you can never get this achivement 
#
#### What happened instead? (Attach screenshots if needed)
can't get this  achivement 
#
#### What do you suggest instead/what changes do you propose?
fix it

**Comment by boubou19** [comment]
have you tried to pick it up from the ground? Also due to mod changes in GTNH, a lot of achievements aren't possible to make.

**Comment by Eason134HK** [comment]
> have you tried to pick it up from the ground? Also due to mod changes in GTNH, a lot of achievements aren't possible to make.

yep i did and according to my observation only produce achivement can be done by pick it up from the ground method

**Comment by Prometheus0000** [comment]
We should just remove achievements. The quests effectively supersede them anyway for the most part.

**Comment by Dream-Master** [comment]
or we can change the archivement to pop up if get the coil via assembler.
