### ISSUE TITLE
some ender io bees don't produce their special comb

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6050]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
wanted to setup theses bees:
conductive iron bee
energetic alloy bee
vibrant alloy bee
electrical steel bee
pulsating iron bee
dark steel bee

#
#### What happened instead? (Attach screenshots if needed)
they only produce the parched comb instead of producing their specialty too:
(I am sure of that because i UV WA-ed them in an industrial apiary with 8 production upgrades)
![image](https://user-images.githubusercontent.com/12850933/81059217-547c5e80-8ed0-11ea-8ea7-d20889f4990d.png)

![image](https://user-images.githubusercontent.com/12850933/81059277-71b12d00-8ed0-11ea-90ce-1a8064a6ae4a.png)

![image](https://user-images.githubusercontent.com/12850933/81059358-94dbdc80-8ed0-11ea-96c0-fd0c09183c85.png)

![image](https://user-images.githubusercontent.com/12850933/81059440-b76df580-8ed0-11ea-951b-fbc3176a5e12.png)

![image](https://user-images.githubusercontent.com/12850933/81059482-c81e6b80-8ed0-11ea-94f8-9ae2caaebffd.png)

![image](https://user-images.githubusercontent.com/12850933/81059534-dc626880-8ed0-11ea-8256-4a07e8954b6e.png)

Is there any additionnal thing i need to do to get their specialty? Because i can get the specialty from redstone alloy bee without extra steps.

**Comment by chochem** [comment]
its called a specialty for a reason. they need to be in jubilant state. google or read the quest book (quest *basic bee stats*) for more. Or in short, they need correct humidity and temp, not just tolerances.

**Comment by boubou19** [comment]
Ah true, totally forgotten that, thx for the reminder
