### ISSUE TITLE
AE2 does not save blank pattern

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#6051]
#### Which modpack version are you using?
2.0.8.8
#

Found an interesting bug. If you put a blank pattern through the interface terminal and after that for some reason the server crashes (bsod. Power outage. Server error) - blank patterns disappear from the world. If you put blank patterns with your hands in interfaces - in the same situations they are saved.

**Comment by repo-alt** [comment]
I didn't even know you _can_ put blank pattern in the interface. Why would you do that?

**Comment by PredVesTNiK2142** [comment]
I apologize. Misspelled. Recorded Patterns

**Comment by repo-alt** [comment]
Looks like for that to happen the chunk with the interface was not yet saved to the disk, while the player data is already saved. If you can reproduce the issue with the interface and the terminal in one chunk then my hypothesis must be wrong, but if I'm right, there is nothing I can do.

**Comment by PredVesTNiK2142** [comment]
The interfaces in which the patterns lay were in different chunks. All the patterns that were done in about 7 hours of the game were gone. Play succeeded.

**Comment by repo-alt** [comment]
It is a bit strange that the server didn't save the chunk with the interface for 7 hours. Or perhaps it did, but it crashed while saving and did automatic rollback.
