### ISSUE TITLE
GT Schematic 3x3 for the packager eats the tiny dusts and outputs nothing

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/GT-New-Horizons-Modpack#6052]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon

Needs a fix

**Comment by repo-alt** [comment]
I agree that it should be fixed, but why don't you use 'dust' schematics?

**Comment by repo-alt** [comment]
Broken by Tec 4 years ago, looks like 3x3 pattern is not really popular

**Comment by MrWye** [comment]
> 
> 
> I agree that it should be fixed, but why don't you use 'dust' schematics?

Simply noticed its broken, and reported :)
