### ISSUE TITLE
GT transformer cannot receive more than 2A of energy from ic energy source

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/GT-New-Horizons-Modpack#6053]
#### Which modpack version are you using?
2088
#
#### If in multiplayer; On which server does this happen? 
multiplayer ，privateserver
#
#### What did you try to do, and what did you expect to happen?
put a ev transformer on a nuclear reactor generating 8160eu / t of power；
and set mode to step down ，8192 to 2048 x4。
use the eu meter to determine how much power it transformed，expecting a 4a ev or 8k+ of output
#### What happened instead? (Attach screenshots if needed)
resulting in 4k-5keu output
#
#
#### What do you suggest instead/what changes do you propose?
fix it，let transformer drain at most 4A of energy from ic power source

**Comment by koiNoCirculation** [comment]
![2020-05-06_02 27 29](https://user-images.githubusercontent.com/57739338/81106543-6568b680-8f48-11ea-8690-503c9d9bcdf8.png)
![2020-05-06_02 27 42](https://user-images.githubusercontent.com/57739338/81106599-76b1c300-8f48-11ea-9943-c5263044805b.png)
![2020-05-06_02 27 45](https://user-images.githubusercontent.com/57739338/81106613-7c0f0d80-8f48-11ea-9026-722dac54f642.png)
![2020-05-06_02 27 52](https://user-images.githubusercontent.com/57739338/81106637-86c9a280-8f48-11ea-80c4-f0867bec6b41.png)

**Comment by repo-alt** [comment]
EU meter is not really the most precise instrument. Better use some battery buffer with lapotrons and measure time to fill them (given the tps is stable enough). Make sure to wait for the internal buffer to fill first.

**Comment by koiNoCirculation** [comment]
notice the ebf，it is attached to a 4A ev battery case，and it is processing materials at IV voltage(6837eu/t)，if the transformer outputs 4a ev of power，the power indicator of crystals shouldn't drop.
But I see it dropped, which means input of buffer is less than the output(3a+ ev).

**Comment by koiNoCirculation** [comment]
I tried direct connecting the output of transformer to ebf, and it stopped immediately after starting to work, which means input of power is not enough to process the recipe, but the nuclear reactor outputs 8160eu/t, so it must be the problem of transformer.

**Comment by repo-alt** [comment]
@Technus , iirc you did ic2 e-net integration for transformers?

**Comment by mitchej123** [comment]
@repo-alt I did the ic2 e-net integration for cables; I think I might have also done it for transformers at the same time.

**Comment by repo-alt** [comment]
Ah, ok

**Comment by mitchej123** [comment]
I'll take a look at the code, but my assumption is ic2 isn't sending it every tick.  You should have it output into a buffer and use the buffer, instead of directly running it off of the transformer.

**Comment by repo-alt** [comment]
Doesn't transformer have big enough internal buffer?

**Comment by mitchej123** [comment]
My assumption is ic2 isn't sending it as frequently as it's expected, or the loss is taking it lower.

For reference, here's the enet commit: https://github.com/GTNewHorizons/GT5-Unofficial/commit/1b7d5e176ec01d7b8fec464371b3e79144fffa8a

**Comment by mitchej123** [comment]
The enet compat doesn't do much except say "I want this much EU, at most". Ic2 enet finds all the sources, and sinks, and figures out how to distribute them itself.  If more than one thing is hooked up to the source (reactor), it'll get split between the sinks (outputs).  Cables are annoying and always ask for the max amount, even if they have nowhere to send it -- transformers are smarter because they have an internal buffer.

**Comment by koiNoCirculation** [comment]
@mitchej123 transformer in the image is attached directly to afsu，which outputs 8192eu/t(IV)，and afsu drain energy from reactor.

**Comment by mitchej123** [comment]
AFSU isn't a GT item afaik and would be using the ic2 enet; use a GT battery buffer and see if the behavior changes.

**Comment by koiNoCirculation** [comment]
@mitchej123 no, things wouldn't change my friend, cause GT_MetaTileEntity_BasicBatteryBuffer did not override shouldJoinIc2Enet(); In fact afsu is a stable IV level IC2 energy buffer, the transformer cannot even take 4A ev from it.

**Comment by mitchej123** [comment]
I'm saying... go nuke --> transformer --> bat buf --> EBF

**Comment by koiNoCirculation** [comment]
@mitchej123 If that works I won't open this issue my friend. I tried that but doesn't work, then I took an afsu from cheat mode but still broken. I tried using Eu meter on afsu, which said the afsu was absorbing energy from reactor with power of 8.16kEU/t.

**Comment by mitchej123** [comment]
What does the output from the GT scanner say when you smack the transformer?

The transformer & IC2 sink code is quite simple... 

Relevant lines from the transformer - https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Transformer.java#L111-L138

Relevant lines from the sink:
Demanded Energy (for simulation) - https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/TileIC2EnergySink.java#L55

Inject Energy: https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/TileIC2EnergySink.java#L97

**Comment by mitchej123** [comment]
1) What are you sending the energy into?  Is that another transformer?  
2) Is anything else hooked up to the nuclear reactor and consuming power?  It has 8k eu to distribute between _all_ connections.  [It was a bug before that every GT connection got the full 8k; hence the enet connection]

**Comment by mitchej123** [comment]
Also... if you're on discord, hit me up -- easier to discuss there.

**Comment by koiNoCirculation** [comment]
@mitchej123 GT scanner says 4k-5keu, and power indicator of batteries drop while ebf is processing recipes.
There was an open computers power transformer attached to the reactor.

**Comment by mitchej123** [comment]
Then you're splitting 8.2k between two sources and ~4-5k is what you'd expect to be getting.  Remove the other connections and you should see the full 8k

**Comment by koiNoCirculation** [comment]
![2020-05-07_21 59 55](https://user-images.githubusercontent.com/57739338/81303528-64519980-90ae-11ea-9752-a50fff1618f2.png)
left: reactor + ev transformer + ev battery case, 
middle afsu + ev transformer + ev battery case,
right mfsu + hv transformer + hv battery case

MFSU：everything works fine.

![2020-05-07_22 00 01](https://user-images.githubusercontent.com/57739338/81303689-9b27af80-90ae-11ea-8982-08d062eb23b5.png)

AFSU:  5keu /t output 
![2020-05-07_22 00 12](https://user-images.githubusercontent.com/57739338/81303884-e17d0e80-90ae-11ea-9783-775ca1ef917c.png)


8160 reactor：still 5keu
![2020-05-07_22 00 30](https://user-images.githubusercontent.com/57739338/81303889-e477ff00-90ae-11ea-9448-d2647685bbe6.png)

There must be problem in the transformer, it's not related to how many devices connected to reactor.

**Comment by mitchej123** [comment]
What happens if you skip the transformer and just use a gt cable directly on the reactor?

**Comment by koiNoCirculation** [comment]
![2020-05-07_22 35 44](https://user-images.githubusercontent.com/57739338/81307382-2dca4d80-90b3-11ea-8dc9-6581a902e614.png)
works
