### ISSUE TITLE
Witchery Shade of Leonard server crash

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#6054]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
High end witchery, summon The Shade of Leonard, and iniate combat.
#
#### What happened instead? (Attach screenshots if needed)
Fight start, a short way in a server crash happens.
Every time the player logs in the server crashes.

I believe (unconfirmed) it is the mortal coil (de)buff that leonard applies to the player.
#
#### What do you suggest instead/what changes do you propose?
Not Crash

#### Extra Info
Tried 3 logon afterwards, all crashed the server.
I reverted to a server snapshot before making a copy of the logs so have no further details.

As a note, leonards drop (Leonards Urn) is the capstone item of the witchery mod (use mystic branch to cast witchery custom potions as spells) as well as the leonard boss fight (with mostly witchery items) being intresting; it would be sad to just remove leonard to resolve the issue.

**Comment by repo-alt** [comment]
Well, it would be nice to see the logs at least.
