### ISSUE TITLE
Post spirit world witchery quests reset

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#6055]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
A number of the post spirit world witchery quests auto-reset (for example the one that stage on is visit the spirt world, stage 2 is have xx Exhalation of the Horned one, but here are a could of other with the visit spirit world as the first stage).

#
#### What happened instead? (Attach screenshots if needed)
In spirit world, complete quest, wait a couple of seconds, can complete quest again (rewards clay jars and coins), repeat, repeat etc.

#
#### What do you suggest instead/what changes do you propose?
Either the quest should be once only (or on a long timer) or if intended to be repeatable shoujld should consume the 2nd stage items.

**Comment by Prometheus0000** [comment]
List the quest names and the numbers so we don't have to search through 30 quests.

**Comment by Prometheus0000** [comment]
@drayath ^
