### ISSUE TITLE
Clean room need machine hull and diode block does not count.

### ISSUE THREAD

**Issue by drayath** [GTNewHorizons/GT-New-Horizons-Modpack#6056]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Build clean room following the quest line, structure won't complete.
#
#### What happened instead? (Attach screenshots if needed)
After spending some time adding and removing different blocks, turns out i had immediately followed the next quest (use diodes to provide power though clean room walls) and had a diode to pass power but no machine hulls, and you need at least one machine hull in the clean room for the structure to be complete.
#
#### What do you suggest instead/what changes do you propose?
a) Don't require machine hull for clean room to be valid.
b) Mention in the diodes for the clean room quest that you still need a machine hull

#### Extra Notes
Probably not so much of an issue later but the first time you are making the cleanroom, it is extremely expensive, and you may well be carrying stuff in by hand to make a few circuits at a time prior to automating things.

As a general things, is there any way of reporting at least the first structure error to the player when a structure is not valid (e.g. missing block type xxx) as it can be a bit mystifying when you build something and it just say's structure invalid without any way to diagnose what the actual issue is.

**Comment by Devtron3D** [comment]
I am on 2.0.8.3 and my clean room does not have a machine hull, but just a diode.

**Comment by Dream-Master** [comment]
@moller21
i remeber you changed the cleanroom (a fe days before) is this a thing that is fixed too or need a fix ?

**Comment by moller21** [comment]
From what i can see the cleanroom runs fine without diode and hull.
