### ISSUE TITLE
Large Steel Controller quest validation issues

### ISSUE THREAD

**Issue by Kafouille** [GTNewHorizons/GT-New-Horizons-Modpack#6057]
#### Which modpack version are you using?
 2.0.8.3-1.7.10
#
#### If in multiplayer; On which server does this happen? 
Official, Epsilon
#
#### What did you try to do, and what did you expect to happen?
Crafted the Large Steel Boiler controller block, expected it to validate that step in the Steam is Never Enough quest
#
#### What happened instead? (Attach screenshots if needed)
The questbook did not recognize the block until I ran it trough a Name Remover, at witch point the quest validated
#

**Comment by Dream-Master** [comment]
I guess this is fixed but need to be tested.

**Comment by Prometheus0000** [comment]
Just checked, it's fixed.
