### ISSUE TITLE
BQ3 Feature Request

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6059]
#### Which modpack version are you using?
GTNH-1.7.10-2.0.9.0-pre7-dev
BetterQuesting-3.0.332-GTNH
#
When editing quests, I frequently go to the designer to move things around. However, doing this is a multi-step process, making it more annoying than it has to be. I would like to ask for a button above the edit (gear) button in the bottom left, that will open the designer directly for that tab.

**Comment by Dream-Master** [comment]
@Funwayguy is this possible to add?

**Comment by Prometheus0000** [comment]
Added in BetterQuesting-3.0.333-GTNH
