### ISSUE TITLE
achivement bug 2.0

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6060]
#### Which modpack version are you using?
delta
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/59776356/81136218-89022000-8f8d-11ea-8c10-11410550f540.png)
![image](https://user-images.githubusercontent.com/59776356/81136229-915a5b00-8f8d-11ea-9284-305747bc2995.png)
![image](https://user-images.githubusercontent.com/59776356/81136345-e302e580-8f8d-11ea-915f-561a754efdc5.png)
![image](https://user-images.githubusercontent.com/59776356/81136379-fe6df080-8f8d-11ea-891e-f693fc8bec7b.png)

#
#### What happened instead? (Attach screenshots if needed)
the workbench is not craft by four planks
the furnace is not make by eight stone 
#
#### What do you suggest instead/what changes do you propose?
fix it

**Comment by Dream-Master** [comment]
GTNH change recipes and of course the recipe text not match. This is vanilla stuff and can't be changed.

**Comment by Dream-Master** [comment]
Any idea @GTNewHorizons/core @GTNewHorizons/developers if banilla text can be changed?
