### ISSUE TITLE
ash bee not breedable

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6062]
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
myFTB.de
#
#### What did you try to do, and what did you expect to happen?
![Ash_bee_hellish01](https://user-images.githubusercontent.com/7759876/81095967-0c782e80-8f06-11ea-8075-b89e8721eaf1.JPG)
![Ash_bee_hellish02](https://user-images.githubusercontent.com/7759876/81095975-0eda8880-8f06-11ea-8983-54b9eec0be2a.JPG)

I tried to breed (>50 times, forced by accelerator) an ash bee, and no block underneath should be necessary, just nether biome (I made nether biome with thaumcraft in OW).
Version 2.0.8.3, MP, myFTB.de

**Comment by Retster** [comment]
copypate my expirience about same thigs in 8.8+

Got that bug few days ago in 8.8 even with this fix from [issue](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5816) dont work as inded: https://github.com/GTNewHorizons/ForestryMC/releases/tag/4.2.23.0
Same with all bees that reqire specific climate to mutate (space bee also cannot be breed) i go through this bug with mutatron.

**Comment by Dream-Master** [comment]
use newer forestry version or wait for 2.0.9.0 rlease.

**Comment by bartimaeusnek** [comment]
The fix i wrote was **ONLY** for blocks below the apiary **NOT** for anything else.

**Comment by Dream-Master** [comment]
@bartimaeusnek what cause the bug and are there more bees affected?

**Comment by chochem** [comment]
Just tested in 2.0.9.0 pre7-dev: Breeding Ash bee works fine. no problems.
So if there was a bug in some prior version, then its fixed already.
