### ISSUE TITLE
Add server please

### ISSUE THREAD

**Issue by FeiYuab** [GTNewHorizons/GT-New-Horizons-Modpack#6064]
website: https://www.dovemc.com/
mc server: gtnh.dovemc.com    (No need to add port)
name: 一世长安(DoveMc) [CN]
whitelist/graylist: whitelist

**Comment by FeiYuab** [comment]
6.1-6.7 server shutdown maintenance

**Comment by Dream-Master** [comment]
ah sorry need to add the server. Is on my list

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/83557483-09c32600-a512-11ea-886e-b20b676716d9.png)

**Comment by Dream-Master** [comment]
@FeiYuab are yu server reopen. I cant see it ?
