### ISSUE TITLE
Multiblock oil/gas rig nerf [RFC]

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#6065]
#### Which modpack version are you using?
2.0.9.0

#### What do you suggest instead/what changes do you propose?

**Idea:**

Imo, preserving current functionality while adding a speed slowdown of 1/16 speed at T2 and 1/64 speed at T3, is a good idea. You will benefit with higher tiers through what is essentially a 16x then 64x increase to total fluid quantity you can pump without movement. That alone does give higher tiers a fairly useful place in power gen. The speed slowdown would be 1:1 with the range increase, essentially just being there to keep a constant rate. This would mean a T1 and a T3 pump would only differ in how long one would be able to run for. 

**Reasoning:**

Multiblock oil/gas rigs are kind of absurd at the moment. T1 is super ok, but T2 gives what is essentially a 16x output boost. T3's 4x that value once again to a 64x boost. With such an ability to produce the pumpable fluid, some issues arise, surrounding power gen in particular. 

Nat gas current allows for very large power gen starting as soon as MV, and being not just viable, but very powerful pre fusion. Diesel, and even light fuel to an extent, when obtained through pumped oil, can outclass most else withing the combustible fuel category. Both of these options allow for very small scale setup for what can equate to move than 100keu/t. 

Nat gas simply has such a short processing chain, it only functions as a balanced fuel in an environment with limited nat gas. Diesel isn't very oil efficient, and light fuel is pretty awful, but once again with large fluid production they become dominant power sources. 

More complex fuels, such as HOG, cetane, or even something like benzene, get extremely outclassed here. They seem to be built upon the idea of limited pumpable fluid, and would function very well in that environment. However with incredibly fast oil gen, it's useless to go for oil efficiency for the cost. 

Imo, the issue is the way the area "bonus" works on the T2/3. Giving it a larger range can be a good idea, however being able to pull from all at once simply functions as a speed multiplier. 16x and 64x faster can be quite a lot. I suggest something that will make crafting higher pump tiers still very valuable, however attempt to tier pump quantities/tiers reasonably with their fluid usages. 

**Comparative Values**

Currently you can use a single T3 HV multi pump on a decent ~500L oil field to make ~100keu/t average worth of oil through diesel. This change would reduce it to around ~1200eu/t with single HV gens. You can still use the proposed values to reach >EV ranges, and can do some reasonable <30keu/t LCE options, but overall youll need a lot more multiblock pumps, and theyll need to be tiered higher up. 

You can get ~50keu/t HOG with ~12.5L/t oil, which is a very reasonable value to produce with the suggested change. A single EV pump with a ~500L field will do 12.5L/t, essentially requiring one pump per ~50keu/t generated with HOG. This isn't high in any way, which imo should be a goal of higher tier fuels. 

Plastic gen from oil is essentially untouched. Oil quantity in veins isn't changed, and plastic usage is absolutely nowhere near current pumping rates. 

Im not sure 16x or 64x pumps were ever really meant to be in GT. Their effect on power gen seems to be somewhat unintentional

https://docs.google.com/spreadsheets/d/1WJl8DdvOgoSoCErVIt3GEz7O3O5IEJ3-SR9KEkhKTCQ/edit?usp=sharing
https://docs.google.com/spreadsheets/d/1zZQCOzAxlOUUIX31K9HI686ndjSx4njoHM2GIV9LGgM/edit?usp=sharing

These show some values for Nat gas and diesel based on current and nerfed pumping values. 

**Other Fluids**

This would indirectly also slow down pumping of salt water and other fluids. Personally I'd say that the nerfed values would be substantial, but if they become too slow we could simply increase vein sizes for them. Most seem still in dev, but salt water would be somewhat impacted.

**Comment by Glease** [comment]
The rate of production is not 16x/64x. Work cycle length is linear to the chunks you would drill. After that every higher pump tier really just half the progress cycle beyond the usual overclock bonus.

All in all, it's 1 EV T3 = 2 EV T2 = 4 EV T1. I'm using tungsten steel/titanium (several tier above steel!), so I think I rightfully deserve this bonus.

**Comment by mitchej123** [comment]
joy... more tedium/grindfest/spam more stuff being proposed... again

**Comment by 0lafe** [comment]
I fucked up, ratios are much more even than 1:16:64
