### ISSUE TITLE
Purified Platinum Ore

### ISSUE THREAD

**Issue by CrazyMasterT** [GTNewHorizons/GT-New-Horizons-Modpack#6066]
#### Which modpack version are you using?
2.0.8.7
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Tried to forge hammer purified platinum ore into purified platinum dust. 

#
#### What happened instead? (Attach screenshots if needed)
It turned into Platinum Metallic Powder Dust, backing up my centrifuges. **I found that the purified platinum powder can be obtained through crafting table with normal hammer.** Dont know which one is the issue.
#
#### What do you suggest instead/what changes do you propose?
Find out if Forge hammered platinum ore was supposed to be purified platinum dust or Platinum Metallic Powder Dust.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea on this or just fixed in newer version?

**Comment by bartimaeusnek** [comment]
purified is no issue iirc.
