### ISSUE TITLE
Void miner mining only one ore in the Overworld

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6068]
#### Which modpack version are you using?
GTNH-1.7.10-2.0.9.0-pre7-dev
#
#
#### What did you try to do, and what did you expect to happen?
Void miner III is mining only one ore in the Overworld (tellurium ore) however I made another one on Mars and it mined different types of ores as intended.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea on this ?

**Comment by Alexdoru** [comment]
I also tried one in the Nether and after the mining pipe reached bercock, it mined nothing. Although it seems to work fine in the galactic dims.

**Comment by bartimaeusnek** [comment]
That seems like an outdated version.

**Comment by yukieiji** [comment]
This issue also occurred in GTNH ver2.0.9.0beta2(bartworks[1.7.10]-0.5.13_pre15).
![2020-05-15_15 05 41](https://user-images.githubusercontent.com/40425798/82017280-c2d5d380-96bd-11ea-8076-9cc1ce2cb153.png)

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ?

**Comment by bartimaeusnek** [comment]
@Dream-Master ill look into it today, need to patch a bit of stuff anyways
