### ISSUE TITLE
AE2 p2p eu tunnels continuously drain power

### ISSUE THREAD

**Issue by darkpouetman** [GTNewHorizons/GT-New-Horizons-Modpack#6069]
#### Which modpack version are you using?

2.0.8.8

#
#### If in multiplayer; On which server does this happen? 

In singleplayer

#
#### What did you try to do, and what did you expect to happen?

I wanted to transport power around my base with p2p EU tunnels. Two nuclear reactors producing together 6120eu/t feed into a battery buffer with lapotron crystals, which outpouts 4 amps of EV at 1920 eu/t. I connected a eu p2p tunnel to the output of the battery buffer and connected it to three different p2p tunnels.
I was expecting the eu p2p tunnel to be able to transmit 4 amp of EV power minus the 5% tax indicated on the wiki, so 1824 eu/t.

#
#### What happened instead? (Attach screenshots if needed)

After running out of power multiple times it seems like the each p2p tunnel voids 1amp of power even with nothing consuming power on the output side, which means I can't keep up their power consumption.

#
#### What do you suggest instead/what changes do you propose?

Fix the drain of the p2p tunnels so that they don't drain passively 1 amp.

**Comment by Dream-Master** [comment]
@repo-alt is this intended behavior or a bug ?

**Comment by repo-alt** [comment]
mm, no idea, I think @mitchej123 added EU p2p

**Comment by mitchej123** [comment]
I'll check.  Someone else added them, I just updated them to send more than one amp.

**Comment by Pnc6lx** [comment]
it increase power cost of ae2 system rather than the transport power

**Comment by repo-alt** [comment]
So, I implemented somewhat better GT EU p2p tunnel in AE2 (half of the code borrowed from Ultramine core). Now the question is - what loss should the tunnel have? (Looks like IC2 EU p2p tunnel did not have any loss regardless of what the wiki said)
I can set it to be 5% now, to support the supposed default

**Comment by 0lafe** [comment]
Does the "better" one still constant fill the outputs?

**Comment by repo-alt** [comment]
I did not debug the ic2 one, so no idea where it was broken.
I hope new implementation will be tested on zeta. Locally it works.

**Comment by Devtron3D** [comment]
I thought the power cost was 10%, so send 100 EU, only get 90 EU on the other side

**Comment by repo-alt** [comment]
Actually IC2 p2p was using generic energy tunnel tax, which was 5% and extracted from AE grid, not from passed energy
