### ISSUE TITLE
Basic Brewery crafting auto-fill crashes client

### ISSUE THREAD

**Issue by meneken17** [GTNewHorizons/GT-New-Horizons-Modpack#6070]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
singleplayer and multiplayer

#
#### What did you try to do, and what did you expect to happen?
Using the NEI Recipy auto-fill (the questionmark-button) for the Basic Brewery with all ingredients in the inventory.

#
#### What happened instead? (Attach screenshots if needed)
[crash-2020-05-06_22.17.54-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4589299/crash-2020-05-06_22.17.54-client.txt)

**Comment by Dream-Master** [comment]
@mitchej123 any idea or is this fixed in a newer version ?

**Comment by mitchej123** [comment]
Haven't seen this error before, will investigate later.

**Comment by Dream-Master** [comment]
@mitchej123 any news here?

**Comment by mitchej123** [comment]
Is this still an issue?

**Comment by GTNH-Afx237v7** [comment]
Yes it is. Just tested it with 2.1.0.0.
With all ingredients in the inventory and using a vanilla crafting table, using the question mark to put the recipe in the crafting table resulted in the following crash:
[crash-2021-02-14_12.41.15-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5977640/crash-2021-02-14_12.41.15-client.txt)

**Comment by mitchej123** [comment]
@GTNH-Afx237v7 @meneken17 Can you provide a screenshot of a recipe that crashes when hitting the question mark?

**Comment by meneken17** [comment]
![2021-02-15_00 21 03](https://user-images.githubusercontent.com/8579800/107892210-ed420f00-6f23-11eb-8114-b9fad5313b15.png)

**Comment by mitchej123** [comment]
hahaha thanks.  I thought you meant "crafting with a basic brewery" not crafting the brewery itself, my bad.  Will investigate

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/NotEnoughItems/pull/41
