### ISSUE TITLE
Infinity pants uncraftable

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#6072]
#### Which modpack version are you using?
2.0.9.0 dev 7 & 2.0.8.3
#
Recipe as shown in NEI:
<img width="447" alt="Screenshot 2020-05-07 at 15 07 21" src="https://user-images.githubusercontent.com/54497873/81304165-9940fa80-9074-11ea-9862-8828331348cb.png">

Attempted recipe but no luck, tried IC2 pants charged fully and empty along with all variations of the draconic leggings and life imbued leggings. Probably related to #6063.

<img width="450" alt="Screenshot 2020-05-07 at 15 07 34" src="https://user-images.githubusercontent.com/54497873/81304312-ce4d4d00-9074-11ea-9619-02c4a0a646a2.png">

<img width="449" alt="Screenshot 2020-05-07 at 15 02 03" src="https://user-images.githubusercontent.com/54497873/81304319-d1483d80-9074-11ea-88c4-41bfd2c938e5.png">

**Comment by Josh5minus1** [comment]
It also happened while I'm testing till I found out that the QuantumSuit Leggings had differnet metadata in recipe than the creative spawned one, I tried the correct meta one in recipe by using give command, it works just fine.

**Comment by GTNH-Colen** [comment]
> It also happened while I'm testing till I found out that the QuantumSuit Leggings had differnet metadata in recipe than the creative spawned one, I tried the correct meta one in recipe by using give command, it works just fine.

This test was done in a creative world with spawned items, however I tried it on eta with my actual quantum leggings and could not get it to work which was what prompted me to create this ticket.

**Comment by Dream-Master** [comment]
Will check if it use wildcard values
