### ISSUE TITLE
Crash on entering nether

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6073]
#### Which modpack version are you using?
GTNH-1.7.10-2.0.9.0-pre2-dev
#
#### What did you try to do, and what did you expect to happen?
Enter Nether Portal, go to Nether
#
#### What happened instead? (Attach screenshots if needed)
Enter Nether Portal, crash
[crash-2020-05-07_15.34.05-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4595302/crash-2020-05-07_15.34.05-client.txt)

It seems to be referencing the ME quantum bridge, of which I did have two for testing with singularities inside, but they were disconnected and unpowered.
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Dream-Master** [comment]
@repoalt
any idea?

**Comment by repo-alt** [comment]
Will be away till 11th

**Comment by repo-alt** [comment]
at the first glance it looks like onUnload event was sent twice to the same object

**Comment by Dream-Master** [comment]
@repo-alt are you able to fix this issue ?

**Comment by repo-alt** [comment]
@Prometheus0000 Is that happening on the server or in SSP? If server then Thermos or Forge?
I'll put the reentrance check, just interesting who is to blame for it.

**Comment by Prometheus0000** [comment]
My SP test world.

**Comment by repo-alt** [comment]
Very interesting, who may send the duplicate message then. It should probably affect other blocks too. The message in the call stack is valid, and is sent by minecraft core, but it looks like there was another before it.
