### ISSUE TITLE
Modifying Impure Tear Recipe and Thaumonomicon entry

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#6074]
I feel that the impure Tear recipe doesn't quite fit and should be made slightly more expensive.  I think the recipe should swap the quicksilver blocks with ordo crystals, the biomes o'plenty hard ice with a ghast tear,also remove the darn tomotoes, and the life essence cells with sanctus(from blood magic.) Also for the essentia requirements remove veneum, gelum, and fames. 

I'd rewrite the entry as:

You have dealt the warping effects of the darker side of thaumomancy to the point it has become irksome. Maybe it is time to delve into forces to purify the corruption.

Your solution was a small drop that provides some cleansing power. It's potency waxes and wanes corresponding to the corruption(You need 50 warp for a 1% chance for this to work, at 150 warp it has a 100% chance of removing warp this scales) Better regents may be required to fully purge yourself of warp.

**Comment by Prometheus0000** [comment]
You need to reference the previous issues you know? #5978 #5671 #5643
Also, why do you think it needs to be harder? The previous issue was about making it easier you know? And why didn't you just comment there?

**Comment by redmage17** [comment]
#1 not everyone is going to instantly know GitHub etiqute.
#2 learn soft skills

**Comment by Dream-Master** [comment]
@Prometheus0000 but tomatoes maybe not a good solution. Using crops is ok but maybe another magical crop
