### ISSUE TITLE
Add modded log support to the crafting table recipe in the Assembling Machine

### ISSUE THREAD

**Issue by jacobrham** [GTNewHorizons/GT-New-Horizons-Modpack#6077]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
SMP hosted single player world
#
#### What did you try to do, and what did you expect to happen?
Placed Greatwood logs in a LV assembler with flint to make a crafting table
#
#### What happened instead? (Attach screenshots if needed)
No crafting recipe was initiated. Looking at the recipe in NEI reveals that only vanilla logs are accepted in that crafting recipe
#
#### What do you suggest instead/what changes do you propose?
add support for modded logs to the crafting table recipe in the assembling machine.

**Comment by jacobrham** [comment]
#6082 
made the necessary minetweaker script changes in this PR

**Comment by Dream-Master** [comment]
i merge the pr please test

**Comment by jacobrham** [comment]
Tested in 2.0.8.8 and 0.9-dev-pre7 by placing greatwood logs in an LV assember with Flint. Everything worked perfectly.
