### ISSUE TITLE
The core conflict recipes

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#6078]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Make The core in assembler.
#
#### What happened instead? (Attach screenshots if needed)
Time to time instead of making The core it makes regular x4 Naqudah fuel rods
#
#### What do you suggest instead/what changes do you propose?
making The core from regular x4 Naqudah fuel rods
https://imgur.com/LahsU16

**Comment by Dream-Master** [comment]
yea they need control circuits
