### ISSUE TITLE
Change Programmed-Circuit number for certain recipe

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/GT-New-Horizons-Modpack#6079]
![2020-05-08_18 01 47](https://user-images.githubusercontent.com/58643870/81424390-2a3bd280-9156-11ea-8a8f-27ccde988a9a.png)
![2020-05-08_18 03 14](https://user-images.githubusercontent.com/58643870/81424411-34f66780-9156-11ea-9bf9-ddb0b493bd88.png)

Having those two recipes needing a prog.-circutit of 1 makes it impossible to automate in one LCR.
Therefore I suggest to change one of them to 24.

**Comment by Prometheus0000** [comment]
...You need to state what recipes they are first?

**Comment by GeicowithaBango** [comment]
right, both of this recipe are using potassium as ingredient. One craft the potassium nitrate and the other potassium hydroxide. 
Potassium hydroxide needs also a programmed circuit of 1 and nitric acid to be crafted into saltpeter. those recipe crashes.

**Comment by 0lafe** [comment]
Doesn't changing it to a 24 really ensure they can't be done in the same LCR? Also I'm kind of confused, what's preventing them from being in the same LCR? It seems like if you put potassium and the right fluid in, it'll make each of them?

**Comment by GeicowithaBango** [comment]
you need nitric acid and water to make saltpeter, both need a circuit of 1. The issue is that if you put nitric acid in the LCR it might react with potassium instantly to potassium nitrate, rather then to potassium hydroxide

**Comment by 0lafe** [comment]
Ah

**Comment by 0lafe** [comment]
Ye but the nitric reacts with the hydroxide, not the pure K, so the only time you'd have potassium in besides nitrate would be when crafting potassium with water. I think I'm still missing the crossover?

**Comment by GeicowithaBango** [comment]
therefore you cant automate it in one LCR. just change the programmed circuit for potassium nitrate to 24

**Comment by Glease** [comment]
> Ye but the nitric reacts with the hydroxide

@0lafe There is another recipe for potassium nitriate that use pure K and HNO3. See [this comment](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5967#issuecomment-618034720) for more info.

**Comment by botn365** [comment]
why are there 2 difrent potasium nitrades?

**Comment by GeicowithaBango** [comment]
???

**Comment by Glease** [comment]
Nobody including greg noticed there is nitor. Greg then added saltpeter. Then everybody forget both of them as well. Alk added one for his chem line, then someone else added another when adding PBI.

**Comment by draknyte1** [comment]
If they don’t exist in base GT they get added. If they require a check for pre-existence, make a ticket.

**Comment by Glease** [comment]
Both niter and saltpeter exists in the first commit in GT5-Unofficial repository. I guess they are indeed in base GT.

**Comment by 0lafe** [comment]
From what it looks like, you can handle that in a single LCR in a handful of ways. Simply locking nitric input on hydroxide need works with a small overflow of nitrate. More discreet options of inputs also exist and can help here. This isn't the only recipe conflict you can run into, depending how you split your fluids, and how many you combine. Why not reward slightly more complex setups. LCR costs as a whole are very low, you can always build another or make a singleblock instead of combining recipes as well. Even the low effort solution of using another LCR is pretty viable here.

**Comment by Dream-Master** [comment]
@GeicowithaBango what are these two recipes.
input/output ?

**Comment by GeicowithaBango** [comment]
1.) Potassium + Nitric Acid —> Potassium nitrate (this should change to a circuit of 24) 
2.) Potassium + Water—> Potassium Hydroxide
so that:
Potassium Hydroxide + Nitric acid —> Saltpeter

**Comment by botn365** [comment]
to make potasium nitrade should be changed to 2 not 24 
24 is for recipes that combines steps the potaium nitrade is not such step

**Comment by Dream-Master** [comment]
ok
