### ISSUE TITLE
Crash after a minute on Ross 128ab

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6083]
#### Which modpack version are you using?
2.0.9.0 pre7-dev
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### 
Crash after exploring Ross 128ab (the moon) for a minute. Maybe I just explored to fast, but others have also had crashes there on 9.0 (melkutus on discord).
I was there on 8.8 and everything was fine. (I deleted the some dimensions including this one when updating, so this one now on 9.0 was a freshly generated dimension.)

Crash report: [crash-2020-05-09_05.41.52-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4602683/crash-2020-05-09_05.41.52-server.txt)

My log is also full of warnings: [log.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4602698/log.log)

**Comment by chochem** [comment]
I also get the same type of warning spam about attempted chunk loading in dim 64 whenever I launch a rocket. I think that should be Ross itself, but I haven't even been there in 9.0 and I am certainly not loading any chunks there.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ?

**Comment by Melkutus** [comment]
I have also had this issue exploring there. I've noticed there are unimplemented meta small ores generating too. When I mined one, it caused me to CTD. This crashlog is from exploring:

https://pastebin.com/gZy6zV0H

**Comment by yukieiji** [comment]
This issue also occurred in GTNH ver2.0.9.0beta1.

**Comment by Dream-Master** [comment]
@bartimaeusnek

**Comment by bartimaeusnek** [comment]
@Dream-Master https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6008#issuecomment-626613896

**Comment by Prometheus0000** [comment]
Also crashed on beta2. Was checking electric prospector's scanner after getting close to a suspicious empty square (ore-wise).
[crash-2020-05-24_07.03.06-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4673342/crash-2020-05-24_07.03.06-server.txt)

**Comment by Prometheus0000** [comment]
The next time I started up it crashed again on me, but the time after it didn't. It also didn't generate a crash log in the crash-reports folder.
[MMC log.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4674501/MMC.log.txt)
[hs_err_pid14108.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4674503/hs_err_pid14108.log)

**Comment by chochem** [comment]
I got another one of those crashes.  This one happened during the countdown of the rocket. This was on enceladus, I have not been to either ross in a long time (since I made the post), but the crash report still mentions them.

[crash-2020-06-01_22.06.55-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4713453/crash-2020-06-01_22.06.55-server.txt)

@bartimaeusnek it would really be great if you could have a look at these crashes. They really dont look like a gc issue, but more like a bartworks one. Why is ross even *decorating* when I try to fly from enceladus to the overworld?

**Comment by Dream-Master** [comment]
@chochem wich Version do you using?

**Comment by chochem** [comment]
beta3. has there been an attempted fix? will update to RC1 anyway.

**Comment by ScriptedPiky** [comment]
I believe these should be fixed on RC1, as it did fix a very laggy ocean problem on Ross128b. If they are not, then more bugs to squash!

**Comment by chochem** [comment]
cool, thanks! currently installing RC1. did not know anything had been changed. as there was no update of any kind.

**Comment by Dream-Master** [comment]
@chochem report if it works with RC1. Thanks

**Comment by Prometheus0000** [comment]
Has anyone crashed on Ross 128ba since RC4, or can this be closed?

**Comment by Dream-Master** [comment]
i guess this is fixed?  @bartimaeusnek
