### ISSUE TITLE
Fix or clear out Genetic Growth Medium recipes

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6088]
#### Which modpack version are you using?
2.0.9.0 pre7-dev (but I think this has been broken for a while)
#
####

Currently there are five recipes for Growth Medium in the mixer (the dust thing from the Genetics mod)
1. sugar+ bone + mulch + wood ash +1B water for 1 Growth Medium
2. sugar+ bone + mulch + wood ash +0.8 B water for 1 Growth Medium
3. 4 small piles of sugar+ 4 small piles of bone meal + 4 mulch powder + wood ash +1B water for 1 Growth Medium
4. 4 small piles of sugar+ 4 small piles of bone meal + 4 mulch powder + wood ash +0.8 B water  for 1 Growth Medium
5. 9 tiny piles of sugar+ 9 tiny piles of sugar + 4 mulch powder + wood ash +0.8 B water  for 1 Growth Medium

So first of all no.5 is clearly a bug. its sugar twice and no bones/bone meal. Second of all there is big descrepancy between one bone in 1/2 but one bonemeal in 3/4. And lastly, who really wants these small/tiny recipes (except for the fact that they are currently better).

Proposal: remove 3, 4, and 5.

**Comment by Glease** [comment]
There are some recipe conflicts involved here. If you put in a full pile of bone meal then it will make water mixed white dye instead. This is why those stupid tiny/small pile of dusts are used.

**Comment by chochem** [comment]
hmm, that explains where this comes from of course. (there are also some circuits in those recipes that I didnt mention of course.)

I mean as a start: is the recipe supposed to be bone meal or bones? I think bones are completely fine (of course a bit harder/more expensive). and those recipes work fine.

either way 5. is literally just a copy-paste coding error and should be fixed or removed for sure.

**Comment by Glease** [comment]
Probably bonemeal. Mixer isn't supposed to break bone down into dusts like a macerator, is it?

**Comment by chochem** [comment]
that is more intuitive, yes. that makes it harder to come up with a nicer solution for 1-4 though. :P
the water+ bonemeal recipe without circuit is inconvenient for sure.

Well, if we cant come up with anything nicer, just removing/fixing recipe 5 might be enough here.
But maybe someone has an idea. :)
