### ISSUE TITLE
Bucket/Clay bucket bag/dupe

### ISSUE THREAD

**Issue by f0Re3t** [GTNewHorizons/GT-New-Horizons-Modpack#6089]
#### Which modpack version are you using?
v2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
This happens both in a single player game and on the server
#
#### What did you try to do, and what did you expect to happen?
I tried to craft a Mud Ball from a block of dirt and a bucket of water
#
#### What happened instead? (Attach screenshots if needed)
The item is being crafted, but a bucket of water remains in the crafting grid, as well as giving an empty bucket to the inventory
#
#### What do you suggest instead/what changes do you propose?
Change the reuse function to giveBack or transformReplace

**Comment by Dream-Master** [comment]
can you test with a newer version. I rember i fix some things. @f0Re3t

**Comment by f0Re3t** [comment]
Yes, I checked the script files on v2.0.8.8 and you really fixed it, in the game it also works without bugs
@Dream-Master
