### ISSUE TITLE
ae 2 and large fluid cell dupe fluid

### ISSUE THREAD

**Issue by AlastarDArk** [GTNewHorizons/GT-New-Horizons-Modpack#6090]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Just wanted to drain the liquid into the terminal
#
#### What happened instead? (Attach screenshots if needed)
Fluid volume tripled
Here is a link to the video, I immediately apologize for the quality.
https://drive.google.com/open?id=1xavoP3jjyJyWgGwO51I3X1_nmAQZqGKA
#
#### What do you suggest instead/what changes do you propose?
I don’t know how to fix errors, but I would like knowledgeable people to fix it

**Comment by GTNH-Colen** [comment]
Another EC2 fluid bug? Damn it's almost like we should disable the recipes to these components until/if anyone ever gets around to fixing them... Just a wild thought.

**Comment by Dream-Master** [comment]
No fix is better. @GTNH-Colen 
@DeForce maby you can check the issues. We all label it with EC2

**Comment by boubou19** [comment]
I noticed that it happens when a cell does have free space but not enough to store the entire amount of fluid. One way to reduce the amount of fluid to clean is to partition each cell/fluid storage bus. (Not sure if it still happens if you do have multiple partitionned cells with the same fluid and one is almost full)

**Comment by Nick5131** [comment]
Bug is reproducible on my server with what @boubou19 said.  I'm on 2.0.8.8

**Comment by eigenraven** [comment]
Fixed in dev for a while.
