### ISSUE TITLE
Void Essence recipe and other crucible recipes do not show up in NEI if searched by recipe

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6092]
#### Which modpack version are you using?
2.0.9.0 pre7-dev
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### 

The Void Essence (added by gt new horizons and needed e.g. for the shard of creation) does not have a recipe in NEI. And yes, I have the research unlocked and the recipe I found in the research does indeed work, see below.

I was just very confused on how to make the essence before I found that recipe in the book and judging by discord search history I was not the first to be confused.

Edit: as explained below, the recipe can actually be found if one searches for uses of the void metal ingot, instead of looking for recipes for the Void Essence. Of course that is useless in practice.

![2020-05-11_23 20 26](https://user-images.githubusercontent.com/40274384/81617908-36d25c00-93de-11ea-8842-5f48227769fb.png)

**Comment by Prometheus0000** [comment]
My understanding is that some/all crucible recipes don't show up sometimes/all the time in NEI.

**Comment by chochem** [comment]
I guess I am not using the crucible enough then. Didnt really have any problems so far. :)

But if anything that makes the problem bigger not smaller. unless the devs have already locked at it and decided its not easily fixable. I could not find a general issue on this.

I searched a bit more around on discord according to your suggestion and it seems the typical problem is then you cant look it up via 'recipe' but it does exist via 'uses'. Indeed the same is true here apparently. If I search for uses of the void metal ingot, then I can find the recipe in NEI. Of course thats pretty useless compared to searching by 'recipe'.

**Comment by Prometheus0000** [comment]
There's also a bunch of infusion recipes that don't show up on the giant list of infusions, of which 95% or so is ethereal familiar variations.

**Comment by querns** [comment]
Related to this -- it looks like there is an issue with the NEI handler for crucible recipes. If you make a stack of the item you're looking for, in your inventory, that's the exact size of the output from one crucible recipe, you can see the recipe just fine. For example, make a stack of 9 redcrystal in your inventory, then hit `R`, and it'll work fine. The corresponding entry in the NEI panel on the right, however, does not. The redcrystal recipe (in 2.1.0.7a) returns 9 items from a single crucible recipe.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/TCNEIAdditions/pull/5
