### ISSUE TITLE
hot Quantium ingot exist two times

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6095]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
Hot ingot No 7271 exist without receipt

![Quantium_hot_01](https://user-images.githubusercontent.com/7759876/81664355-afb5d000-943f-11ea-9801-a1e93eb7f5ad.JPG)
![Quantium_hot_02](https://user-images.githubusercontent.com/7759876/81664367-b17f9380-943f-11ea-8484-ab0a1211a3b1.JPG)

Q: how can I lable issues, in this case low prio?

**Comment by Dream-Master** [comment]
you can't.
Will check the recipe.

**Comment by bartimaeusnek** [comment]
can be removed from the core mod.

**Comment by Dream-Master** [comment]
Are they added via core mod and gt or via core mod and bartworks ? @bartimaeusnek

**Comment by GTNH-Afx237v7** [comment]
It is found here in the coremod:

**Ore dictionary registration:**
https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/d93943ecd8acb8ea09348657f4ee08cdc54be7bc/src/main/java/com/dreammaster/gthandler/GT_Loader_OreDictionary.java#L56-L60

**GT_Machine_Recipeloader:**

_Blast furnace recipes:_
https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/d93943ecd8acb8ea09348657f4ee08cdc54be7bc/src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java#L632-L633

_Vaccum freezer recipes:_
https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/d93943ecd8acb8ea09348657f4ee08cdc54be7bc/src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java#L1944
