### ISSUE TITLE
AE2 WCT Bugs

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6097]
#### Which modpack version are you using?
GTNH-1.7.10-2.0.9.0-pre2-dev
#
Also see #6080

AE2 Wireless Crafting Terminal:
- [ ] There's some lag when opening the terminal
- [ ] What should be check marks or Xs or something in the magnet card interface is some kind of weird characters instead. Visual bug only probably.
- [ ] (From GTNH-Colen+boubou19) If you use the wireless crafting terminal and hold shift while dragging your mouse it seems to kick the infinite range card out for some reason making it useless until you get home again. (in range of an access point? or the controller?)
- [ ] Also the magnet card/infinite range cards have a tendency to just delete themselves sometimes. May also just be dropped on the ground instead.
#
#### What do you suggest instead/what changes do you propose?
Be fixed

**Comment by repo-alt** [comment]
Does WCT lags every time you open it? If it is  just first time then it is unavoidable - AE essentially sends the network contents to the client. Same lag happens in the usual terminal.

**Comment by Prometheus0000** [comment]
Every time I used it. I was only testing it for the quests, so I haven't used it a lot.

**Comment by repo-alt** [comment]
I seriously suspect that mouse weirdness comes from Inventory Tweaks. Would be nice if someone would be able to reproduce the bug with just AE2+WCT
