### ISSUE TITLE
AE2 TE Bugs/Suggestions

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6098]
#### Which modpack version are you using?
GTNH-1.7.10-2.0.9.0-pre2-dev
#
Also see #6080

Thaumic Energistics:
- [x] Essentia storage/conversion monitor power drain not consistent with same type (other storage/conversion monitors). I believe it's 0.006 instead of 0.5
- [ ] There isn't a way to have the system craft essentia on demand for a craft, it would be nice if the essentia provider (and infusion provider) would send a request to any me interfaces that have a pattern for that aspect (you can make those patterns with the Distillation Pattern Encoder). This would be incredibly useful.
- [x] Alternatively (or as well) allow essentia export busses to accept the crafting card (and work with it of course), so you can use the essentia level emitter to activate them and keep a certain stock level.

#
#### What do you suggest instead/what changes do you propose?
Have the power drain be the same as the other storage/conversion monitors (0.5 AE? I forget). Add one or both of the suggestions.

**Comment by repo-alt** [comment]
Monitors idle drain is indeed set to 0.0625 instead of 0.5 like in core AE. No idea why it was made so., probably the author did not find out the related code in AE sources.

**Comment by repo-alt** [comment]
On demand crafting for essentia providers I find to be strange. Crafting card support for the export bus I can look into, although that is potentially not very server friendly, if not done in batches, and what will regulate batch size -  config value?
Currently you may trigger essential production with level emitters, but I agree that it may be clumsy.
I personally use OC to monitor certain essentia levels, and order production as necessary.

**Comment by GTNH-Afx237v7** [comment]
In Divine Journey I made a setup to keep essentia stocked using essentia level emitters. When a certain type of essentia was low, the essentia level emitter would toggle item extraction from a drawer and the item would be thrown into an advanced alchemical furnace.
![image](https://user-images.githubusercontent.com/64365566/86226502-0d3ae300-bb8c-11ea-9fc5-d750b37a84ed.png)
Really helpful was a list I found online with the aspects of the different items. If I remember correctly there is a command in GTNH (/dumpaspects ?), however the only reply from the game is that a list is being created but never actually written to disk.

**Comment by repo-alt** [comment]
List of aspects of many items was on GTNH datasheet on Google Docs, but looks like it was removed

**Comment by GTNH-Afx237v7** [comment]
The command is /dumpaspects, alternatively
/DA
/da
/dumptc
/DumpAspects
It creates a file called AspectInfo.txt in the GT++ config folder, however the file remains empty.

**Comment by Prometheus0000** [comment]
There's a link to an aspect list on the misc page. I removed the other one, but you should be able to look at the old sheets at https://docs.google.com/spreadsheets/d/1PzuHY2ZyJiha2fpOlbWz1v2fdpP41c6kHwSV6qX9bVI/edit?usp=sharing.
Both unfortunately are not completely accurate.
