### ISSUE TITLE
AE2 EC2 Bugs/Suggestions

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6099]
#### Which modpack version are you using?
GTNH-1.7.10-2.0.9.0-pre2-dev
#
Also see #6080

EC2:
- [x] EC2 higher item cells don't consume AE (256k+)
- [x] EC2 fluid cells don't consume AE
- [x] The ME Portable Fluid Storage only contains 128 buckets, why would you ever use it?
    MEPFS should have a larger size, it's only equivalent to 1 titanium cell, but way harder to make. Buff it to iridium cell level? Maybe increase power storage as well, if it just doesn't run out because you can barely put anything in. It might be kinda useless no matter what since you have to put the fluids in manually, and if you have the cells for that, you'd probably keep them in them?
- [x] Fluid storage and conversion monitors locking with network tool doesn't work (but does with certus/NQ wrench
- [x] Fluid storage and conversion monitors won't display fluid amount (So they're useless. did work once somehow, but I couldn't get it to happen again)
- [x] When placing filled cells into a fluid terminal with a bucket in the output, it just voids the cells. Probably does this with anything different between I/O since it expects only buckets?
- [x] When changing modes of the ME Block Container when it hasn't been locked to an item, it gives you a free Advanced Storage Housing, probably because the command conflicts with the one for separating components and housings. You can see a component for a millisecond before it goes back to being the BC. You can repeat this.
- [ ] Wireless Universal Terminal with essentia terminal added doesn't add functionality properly
- [ ] Wireless Universal Terminal won't allow adding crafting terminal to add crafting mode (apparently you can get it by using the WCT as the base, but I believe this should be an option as well)
- [ ] The ME Energy Cell Fixture both requires a channel (unlike other energy cells) and doesn't store any energy. This means it doesn't do anything
- [ ] ME Fluid Pattern [WIP]s don't work (are they disabled because we have cells?)
- [x] (suggested by GTNH-Afx237v7) As discussed on Discord, would be a quality of life feature if the EC2 Ore Dictionary Export Bus can accept multiple expressions (e.g. dustImpure* & beeComb* to go in a centrifuge). Currently it only allows one expression.
#
#### What do you suggest instead/what changes do you propose?
Be fixed/added

**Comment by repo-alt** [comment]
1.12 code with Oredictionary Export bus improvements:
https://github.com/ExtraCells/ExtraCells2/commit/4f4d41b23f0dbe77860bdca58a6c1ee4a383324e?diff=split

**Comment by DualBallers** [comment]
The ME Fluid Storage Bus emits light when it's connected to an ME system.

**Comment by DualBallers** [comment]
The Crafting Terminal cannot be added/installed to the Universal Wireless Terminal (like it is possible to add e.g. the Fluid Terminal).
![image](https://user-images.githubusercontent.com/30087707/85016339-d6b3a000-b169-11ea-8864-c78cd19f2325.png)

**Comment by repo-alt** [comment]
I think it is deliberate. There is Wireless Crafting Terminal.

**Comment by DualBallers** [comment]
- After a certain number of fluids in the AE system it is not possible to mouse-select the lower ones in the Fluid Terminal (both handheld and terminal screen), even though it is possible to scroll down in the fluid list. 
E.i. the selection is not updated when scrolling far down. All fluids can still be selected by searching, so I suppose the same list update should be applied after a scrolling event.

- It would be really nice if the Fluid Interface could be sorted by fluid name and/or by fluid volume.
