### ISSUE TITLE
Iron tank gauge

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#6104]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Craft iron tank gauges for a railcraft multiblock tank
#
#### What happened instead? (Attach screenshots if needed)
I am disapointed to see that the iron tank gauge can't be crafted in an assembler, while the steel tank gauge can
#
#### What do you suggest instead/what changes do you propose?
Add a recipie in the assembler for this iron tank gauge

**Comment by TimDiekmann** [comment]
It's possible as of now: 1 Iron Plate + 1 Glass Pane. However, pulverizing it gives two iron dusts. It isn't worth the effort for duplicating iron however it has to be fixed. Can't find the recipe in the scripts, otherwise I would have made a PR.

**Comment by Prometheus0000** [comment]
@TimDiekmann That's a different issue, you can open up another ticket if you like.
