### ISSUE TITLE
IC2 quest Unknown seeds no more validation issues

### ISSUE THREAD

**Issue by Kafouille** [GTNewHorizons/GT-New-Horizons-Modpack#6106]
#### Which modpack version are you using?
 2.0.8.3-1.7.10
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Unknown seeds no more quest should validate 2nd step when the player has 32 unscanned seeds in inventory.
#
#### What happened instead? (Attach screenshots if needed)
Quest does not validate when the player has 32 unknown seeds in his inventory.
#
#### What do you suggest instead/what changes do you propose?
Requiring most of the player inventory to be filled with unstackable items is a bit awkward.

**Comment by boubou19** [comment]
Duplicated of #5647, which is fixed in dev.
