### ISSUE TITLE
Tier 4 Heavy Duty Plates Recipe and Quest

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6107]
#### Which modpack version are you using?
2.0.9.0 pre7-dev
#
####

The recipe for the Tier 4 Heavy-Duty Plates has been changed (back) to Osmiridium bolts. The quest (1532) asks for ruridit bolts instead.

The recipe change back to the old recipe was a bit surprising. But if this was intended, please also change the quest to ask for osmiridium bolts, 4 per plate, so 52 in total.

Edit: Still the case in 2.0.9.0 beta2
Edit2: Still the case in 2.0.9.0RC1
Edit3: Still the case in 2.0.9.2b dev. Bart, are you ever going to fix this?

**Comment by Prometheus0000** [comment]
You should probably check the GTNH-1.7.10-2.0.9.0-beta1 version too.

**Comment by chochem** [comment]
ok, its a 10 hours outdated version. have patience and I will get there.

**Comment by Prometheus0000** [comment]
Can confirm it's now Osmiridium in beta1 for some reason.

**Comment by Dream-Master** [comment]
i dont change it so how it changed themself

**Comment by Prometheus0000** [comment]
No idea, I couldn't even find where the recipe is defined when I looked. Though I found the ingot -> plate implosion compressor one which says it still gives ruridit dust.

**Comment by Dream-Master** [comment]
I remember we change same plate need europium for get fusion first to progress in planet tiers.

**Comment by Prometheus0000** [comment]
According to #6076, the Europium bolts are for the T5 ingots -> plates.

**Comment by chochem** [comment]
thanks for checking the beta.

following the T5 changes it was easy to find that the recipes are defined here: https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/11e8829f1286333746ec46a1b8219c1ae2221dca/src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java  (line 271)

However, I dont see anything about ruridit in the history. It has always been osmiridium as far as I can see, so I guess it was overwritten from somewhere else?

**Comment by Dream-Master** [comment]
@bartimaeusnek is this overridden from Bartworks ?

**Comment by bartimaeusnek** [comment]
It was, no idea why it suddenly changed tho, ill investigate.

**Comment by bartimaeusnek** [comment]
It was some kind of Reference/Value issue, it's fixed.

**Comment by chochem** [comment]
this is not fixed in 9.0 RC1

**Comment by ScriptedPiky** [comment]
Can confirm it still isn't fixed on QF4.

**Comment by Prometheus0000** [comment]
Changed the quest until Bart fixes it so players don't make stuff they can't use.
