### ISSUE TITLE
LSC Issues

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#6108]
#### Which modpack version are you using?
2.0.9.0 Beta 1
#
Below are a few issues that seem to have cropped up while playing with this in sp:

- [x] Really ultimate capacitor has a missing item in the recipe.

- [x] Really ultimate capacitor is UEV, should it be UMV?

- [x] IDs seem confused, when spawning casings/capacitors in they stack as if one item?

- [x] Structure check allows hatches in glass spots but hatches do not function.

- [ ] Info panel passive loss count does not seem to increase beyond 598 eu/t (Not updating maybe?)

- [ ] LSC Seems to sometimes make energy from nothing? (See: https://imgur.com/a/V2NQbkN) Unsure on the exact cause here, perhaps someone can chime in?

**Comment by kekzdealer** [comment]
I can't replicate either of the last two points.

Info Panels update fine for me and I have no clue how the last one is supposed to happen.

**Comment by GTNH-Colen** [comment]
> I can't replicate either of the last two points.
> 
> Info Panels update fine for me and I have no clue how the last one is supposed to happen.

For the last point neither, I couldn't get it to repeat for me but was definitely occuring as you can see from the gif. The panel wouldn't update for me whether I had a trillion EU in it or 0, unsure why I'll try take another look later if I have time.
