### ISSUE TITLE
Cheap assembly recipe for machine hulls?

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#6110]
2.0.8.8

Is this intended? 
The assembly recipe for ALL machine hulls does not include the tier specific plate from the shaped crafting, e.g.:

![image](https://user-images.githubusercontent.com/30087707/81917990-36041a80-95d6-11ea-85a1-e6ebf00f457a.png) ![image](https://user-images.githubusercontent.com/30087707/81918023-41574600-95d6-11ea-987e-6ba9e50c718d.png)

I would suggest either that 
- the plate is added to the assembly recipes, or 
- if its not added, that the assembly voltage is one tier above the respective machine casing tier.

**Comment by botn365** [comment]
yes that intended

**Comment by DualBallers** [comment]
OK, to me it just seemed too big a discount when it can be assembled at LV.

**Comment by botn365** [comment]
its to push people to use the assembler to make the casings

**Comment by Houstonruss** [comment]
There is still a plastic requirement in the fluids slot.
