### ISSUE TITLE
After UV transformers recipes is wrong

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6111]
#### Which modpack version are you using?
2.0.9.0beta1
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What happened instead? (Attach screenshots if needed)
UHV transformer use Nano Power IC and UEV transformer  use Pico Power IC
![2020-05-14_20 00 03](https://user-images.githubusercontent.com/40425798/81937138-2d3f3300-962e-11ea-9863-037d7ac3ad43.png)
![2020-05-14_20 00 31](https://user-images.githubusercontent.com/40425798/81937151-329c7d80-962e-11ea-8151-331b05e3d225.png)
#
#### What do you suggest instead/what changes do you propose?
UHV transformer should use Pico Power IC and the UEV transformer should use Quantum Power IC.

**Comment by GeicowithaBango** [comment]
In general, more  and new recipes for UEV components would be nice to have.

**Comment by yukieiji** [comment]
Fixed in v2.1.0.0 now

**Comment by yukieiji** [comment]
It was not fixed at all.
Currently, it is possible to make a UEV transformer with UHV, so you can charge with UIV and get high amperage UHV by stepping down (but the voltage to charge the UIV battery is UHV, so I don't think it will be a problem).

**Comment by yukieiji** [comment]
LV (MV to LV) to ZPM (UV to ZPM) transformers can only be craft in that tier. However, UV (UHV to UV) transformers can only be craft at UHV, and transformers up to UMV can craft at UHV tier.
Shouldn't this be changed so that UV transformers can be craft in UV and only UHV transformer can be craft in the UHV tier?

**Comment by Prometheus0000** [comment]
¯\_(ツ)_/¯
What you asked for is done, now you've changed what you asked for. I dunno when you can make them. I'll investigate another time.

**Comment by Prometheus0000** [comment]
@yukieiji I'm having trouble understanding why you can't make the UV transformers in UV, aside from the UHV superconductor. See #7611. But you're talking about the power ICs, which seem to be craftable at that tier?
![image](https://user-images.githubusercontent.com/8517039/117556756-3a70e100-b03a-11eb-878c-6f2804f5b547.png)
![image](https://user-images.githubusercontent.com/8517039/117556688-9ab35300-b039-11eb-9200-e239c835daa3.png)
![image](https://user-images.githubusercontent.com/8517039/117556689-9f780700-b039-11eb-958d-2f0b0a2fd049.png)
![image](https://user-images.githubusercontent.com/8517039/117556692-a30b8e00-b039-11eb-91a0-3e7f21e7e5bb.png)
![image](https://user-images.githubusercontent.com/8517039/117556702-b7e82180-b039-11eb-8418-93c9f2404e2a.png)

Also, the piko ones are harder, not easier?

**Comment by yukieiji** [comment]
UHV Superconducter isn't craftable in UV...

**Comment by yukieiji** [comment]
私は多くのことを見落としていましたが、現在は正しいレシピになっているようです。
UVトランスのレシピについては、新しいチケットが発行されているので、このチケットは閉じます。
