### ISSUE TITLE
Game crash when place the Botany flower

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6112]
#### Which modpack version are you using?
2.0.9.0beta1
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
I placed a flower in order to open the portal of twilight.
#
#### What happened instead? (Attach screenshots if needed)
Game Crash

Clash reports:
[crash-2020-05-14_22.00.14-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4628521/crash-2020-05-14_22.00.14-server.txt)
[crash-2020-05-14_22.00.31-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4628522/crash-2020-05-14_22.00.31-client.txt)
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by mitchej123** [comment]
What flower did you try to place

**Comment by yukieiji** [comment]
Minecraft Vanilla Dandelion.
It's from the NEI cheat in creative mode.

**Comment by yukieiji** [comment]
After the crash, Dandelion that placed left behind had turned into a Poppy.

**Comment by mitchej123** [comment]
Odd, it's crashing in binnie's botany code

**Comment by mitchej123** [comment]
The itemstack that's getting passed around is null...

**Comment by mitchej123** [comment]
Can you reproduce this?

1) From cheating in another flower from NEI
2) From a flower obtained in survival mode

**Comment by yukieiji** [comment]
Sorry @mitchej123 , I misunderstood a bit.
I placed Botany's Flower (taken out of NEI).
The other Botany flowers and vanilla flowers didn't cause any problems.

Botany flower causing a crash:
![2020-05-15_13 37 34](https://user-images.githubusercontent.com/40425798/82012048-b6e41480-96b1-11ea-926d-ae9388c2c71a.png)
