### ISSUE TITLE
Minor change in NEI interface for the combustion generator

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#6113]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Was looking in NEI for the burn times of different fuels in the combustion generator 
#
#### What happened instead? (Attach screenshots if needed)
In NEI interface, the combustion generator is named "diesel generator" 
#
#### What do you suggest instead/what changes do you propose?
Switch the name diesel generator by combustion generator in NEI interface

**Comment by Prometheus0000** [comment]
I forgot to note I did this.
