### ISSUE TITLE
Dislocation Wand focus keeps NBT of the block it picked up last saved until another block is picked up

### ISSUE THREAD

**Issue by kekzdealer** [GTNewHorizons/GT-New-Horizons-Modpack#6116]
Version: Private install of 2.0.9.0 beta2

This issue doesn't really impact gameplay in any way, but in some edge cases a rather extreme amount of NBT data can be duplicated. For example when picking up huge chest filled with GT machines.

In that case the entire NBT of all the GT machines in the chest sticks with your actual player data. Which probably isn't that healthy.

**Comment by Prometheus0000** [comment]
I don't think there's anything that can be done about this. It will be fixed naturally whenever the NBT Dissassembly Data is removed.
