### ISSUE TITLE
[Better Questing] Bugged quest rewards (quest list inside with solution)

### ISSUE THREAD

**Issue by nrodriguesdev** [GTNewHorizons/GT-New-Horizons-Modpack#6117]
#### Which modpack version are you using?
2.0.8.8

**Description**
Players are unable to claim rewards for certain quests. Those quests remain highlighted and unclaimed. I've encountered this problem shortly after starting GTNH. 

![image](https://user-images.githubusercontent.com/25905465/82049771-ed576a80-9684-11ea-9740-a056710781e7.png)
(screenshot taken while debugging issue in creative mode)

**Investigation**
I cloned GTNH's custom Better Questing repository and inspected the code. I concluded that the problem came from the quests added by the modpack, although the mod could be improved to handle this gracefully. 

Better Questing shows only the first reward listed for the quest. The mod checks the player's ability to claim each item (even hidden rewards). If a Choice Reward is added after an Item Reward in the rewards list, then the `canClaim()` method of the QuestInstance class will always return false. 
![image](https://user-images.githubusercontent.com/25905465/82049905-30194280-9685-11ea-88cf-adf99900f765.png)
(Modified Better Questing mod v3.0.322 to show the status of the carrot quest below)

**Example: Quest 484 - Can you hear the carrots grow?**
![image](https://user-images.githubusercontent.com/25905465/82050278-da916580-9685-11ea-9998-d7af4c2b675b.png)

**Solution**
- Ensure that Choice Rewards are the first reward in the list, so they show up in the book and don't bug the quest. 
- Remove Choice Rewards from quests that shouldn't have them in the first place.

**Affected Quests**
I wrote a script to identify the quests affected. I've tested several and each have the same problem.

[ID: 1540] 	§5§lMagnalium Source
[ID: 56] 	§3§lUpgrade: Forge hammer
[ID: 1888] 	§4§3§lRepairing your Hazmat Suit
[ID: 1832] 	§6§lGrinding with Wind
[ID: 699] 	§6§lWhy one coke oven when you can have ten?
[ID: 697] 	§6§l2x steel
[ID: 2268] 	Who needs friends?
[ID: 1157] 	§3§lRubber Soft Mallet
[ID: 1820] 	§6§lLapotronic Energy Storage Unit
[ID: 1354] 	Rechargeable Scribing Tools
[ID: 479] 	§3§m§l§m§4§3§lTHE NETHER
[ID: 58] 	§3§lUpgrade: Better macerator
[ID: 488] 	§2§lYou need them all!
[ID: 867] 	§3§lLapis, Lazurite, Sodalite, Calcite
[ID: 1613] 	§5§lSource of Nickel
[ID: 52] 	§3§4§3§lA clear view
[ID: 1155] 	§5§lBasic Fluid Solidifier
[ID: 1791] 	§5§lOilsand or how you get heavy Oil
[ID: 65] 	§3§lBlastoff!
[ID: 76] 	§6§lTime to get some steel
[ID: 1107] 	§4§3§lThe Iron Guy
[ID: 1642] 	Reward for desulfuring automation
[ID: 238] 	Fuuuuuu...(sion)!
[ID: 496] 	§3§lHow to make rubber
[ID: 66] 	§3§lTime for some logic
[ID: 561] 	§6§lLiquid fuelled firebox
[ID: 868] 	§1§2§3§lGypsum
[ID: 484] 	§1§lCan you hear the carrots grow?
[ID: 1147] 	§3§2§4§3§lGT 6 styled Wires and Cables
[ID: 2426] 	§6§lTantalum Nether
[ID: 625] 	§3§lPacking your tanks chests and barrels
[ID: 716] 	§5§lFind some Certus Quartz
[ID: 57] 	§3§lUpgrade: Extractor
[ID: 1351] 	Quantum Goggles
[ID: 577] 	Forestry core block
[ID: 579] 	§5§lMolten redstone?
[ID: 1641] 	Small reward
[ID: 55] 	§4§3§lUpgrade: A better compressor
[ID: 21] 	§2§lClay: The Gathering
[ID: 64] 	§3§lUpgrade: Better furnace
[ID: 1285] 	§5§lDiamond Spikes
[ID: 766] 	§6§lLet's get crackin!
[ID: 536] 	§3§lLow tier wires
[ID: 163] 	§9§lI see everything
[ID: 698] 	§6§l4x steel
[ID: 1108] 	§3§lThe Cool Guy
[ID: 558] 	§3§lWhat can I put all these items in?
[ID: 942] 	§3§lIt's a dirty job, and you're going to do it
[ID: 1345] 	Secret-Angel-Assasin
[ID: 1835] 	§6§lTantalum Overworld
[ID: 478] 	§3§lFlint and steel
[ID: 497] 	§4§3§lLit way to get charred
[ID: 1754] 	Computer Case
[ID: 472] 	§2§lYour first tool
[ID: 562] 	§6§lHigh pressure boiler tank
[ID: 470] 	§1§lBerry medley
[ID: 597] 	§5§lTetrahedrite, stibnite and copper
[ID: 69] 	§3§lWire-Wrap
[ID: 875] 	§3§lSlime Island Journey
[ID: 703] 	Powerful shards
[ID: 705] 	§3§lAccelerated plant growth
[ID: 2267] 	A travel companion
[ID: 495] 	§3§lOh, shiny! (Not platinum!)
[ID: 474] 	§2§k§l§l§r§2§lUpgrade 2.0
[ID: 834] 	§3§lCircuit Boards
[ID: 1166] 	§5§lQuartz and Quartzite Veins
[ID: 49] 	§3§lThe hell is that?
[ID: 1818] 	Large Essentia Generator

If you have any questions I'd be happy to answer them. 😄

**Comment by Dream-Master** [comment]
@nrodriguesdev 
can you check with 2.0.9.0-beta2 and report if this happend again or fixed?

**Comment by Dream-Master** [comment]
http://downloads.gtnewhorizons.com/Dev-Pack/Pack/Client/

**Comment by nrodriguesdev** [comment]
I can confirm that the latest version does indeed fix the issue! The UI improvements are fantastic.
