### ISSUE TITLE
Scanner consumes schematic even if voltage level too low

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [GTNewHorizons/GT-New-Horizons-Modpack#6118]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried to scan the Tier 2 rocket schematic, in an LV Scanner. I had not noticed that the required voltage level is HV. As this machine's voltage level is too low, the scanning process should not have started.
#
#### What happened instead? (Attach screenshots if needed)
Instead, the scanning process did start, and now the machine is complaining that it is not receiving enough power. It is in fact impossible to supply this machine with the correct amount of power for this process as it is only a LV Scanner.
#
#### What do you suggest instead/what changes do you propose?
All other gregtech process do not start if the required voltage level is higher then the machines maximum voltage level. The Scanner should adhere to the same principle, and not start if the process cannot be completed with the machines current voltage tier.

**Comment by Prometheus0000** [comment]
I believe this is fixed in a newer version.

**Comment by botn365** [comment]
you can feed the machine 16A of LV to finish the scan

**Comment by AndrewAmmerlaan** [comment]
> you can feed the machine 16A of LV to finish the scan

Thanks! That worked. I'm still confused as to why this recipe seems to behave differently then the others. Trying to do a process that requires voltage X in machine of tier X-1 usually results in the process not starting, or am I mistaken?

> I believe this is fixed in a newer version.

Awesome, i don't have the dev version installed on my computer at the moment, but I might check it out later to see if this works in the new version.
