### ISSUE TITLE
[Bosses:Evolved] offer change task quests

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6119]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
### I'm offer change task quest line "Bosses: Evolved"

Because killing Creeper Evolved boss can't was detected - and to save uniformity, I suggest to change all Quest Line
#
From `Mob Hunt Task: Boss Evolved`
![изображение](https://user-images.githubusercontent.com/47714084/82067190-0f7ad800-96d9-11ea-9aa7-08727a5cdb84.png)
#
To `Retrieval or Interact Task: Tier Dungeon Key`
![изображение](https://user-images.githubusercontent.com/47714084/82067606-9f208680-96d9-11ea-9429-e9ac32a363a3.png)

**Comment by Prometheus0000** [comment]
Wasn't this fixed on a newer version of BQ3? Try killing them with melee or reflecting the TNT at them.

**Comment by MotDT** [comment]
> 
> 
> Wasn't this fixed on a newer version of BQ3? Try killing them with melee or reflecting the TNT at them.

I'm trying, but this dn't work(
https://youtu.be/hCjDOp9NSuw

**Comment by Dream-Master** [comment]
@MotDT did you test with 2.0.9.0 beta 2
2.0.8.3 is ancient.
