### ISSUE TITLE
Naquadria combs give naquadah ore

### ISSUE THREAD

**Issue by Retster** [GTNewHorizons/GT-New-Horizons-Modpack#6120]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Spingle Player
#
#### What did you try to do, and what did you expect to happen?
Make purified naquadria ore from naquadria combs
#
#### What happened instead? (Attach screenshots if needed)
Making regular purified naquah ore
https://i.imgur.com/KDaLRt0.png
#
#### What do you suggest instead/what changes do you propose?
fix recipe.

**Comment by Dream-Master** [comment]
Autoclave cant use circuits.Maybe i need to add a map se circuits
