### ISSUE TITLE
Mod suggestion Bug Torch

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#6122]
https://github.com/jss2a98aj/BugTorch

made by jss2a98aj who maintained us version of Twilight Forest

**Comment by Ethryan** [comment]
Hmm, that list of features look mighty interesting. I approve.

**Comment by kekzdealer** [comment]
I like this one 
> Speed up initial world loading by not waiting for as many chunks to load

**Comment by GTNH-Colen** [comment]
> Speed up initial world loading by not waiting for as many chunks to load

Just playing devils advocate here but couldn't this cause issues if i'm understanding it correctly? Thinking primarily of cable networks half loading in and burning up?

**Comment by boubou19** [comment]
> Just playing devils advocate here but couldn't this cause issues if i'm understanding it correctly? Thinking primarily of cable networks half loading in and burning up?

i think we should at least give it a try and if it add more issues than it resolves we simply take it back.

**Comment by Prometheus0000** [comment]
This is in already
