### ISSUE TITLE
dimensional trencivers break on restart/breakign the block

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#6124]
#### Which modpack version are you using?
9.0 pre7
#
#### If in multiplayer; On which server does this happen? 
mp/sp
#### What do you suggest instead/what changes do you propose?
when you break a dimensional transiver or on restart it will stop accepting power and stop working
only when you reset the dimensional transiver by puting it in a craftingbench will it start working again
but the moment you break it it stops working again

**Comment by botn365** [comment]
also the capacity that waila shows gose from 500K when it works to 100K when it doesent work

**Comment by Dream-Master** [comment]
@botn365 with beta 2 ?

**Comment by botn365** [comment]
yep

**Comment by Dream-Master** [comment]
@Zoko061602 we need your help here

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/EnderIO/pull/17
