### ISSUE TITLE
Quest that appears nowhere can be completed (Low priority)

### ISSUE THREAD

**Issue by interestingusernam3** [GTNewHorizons/GT-New-Horizons-Modpack#6126]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
I picked up some project red pipes and circuits, I expected nothing to happen.
#
#### What happened instead? (Attach screenshots if needed)
A "quest completed" notification about the quest "Ghetto ME system" appeared. I searched hard for the quest, but it seems to not be present within any of the quest book tabs avaible to me. Same thing later happened with a quest called "Ghetto ME system: Default storage chest"(or something like that".
#
#### What do you suggest instead/what changes do you propose?
Delete the quests or make them impossible to complete in some way

**Comment by Prometheus0000** [comment]
Did you check the projectred tab? Maybe you completed the quest requirement before opening the tab (if that's possible). You can use /bq_admin edit in a cheat-enable sp world to see all the quests.

**Comment by interestingusernam3** [comment]
I checked it. Those quests aren't there. I have the all the circuit/pipe quests done.

**Comment by Prometheus0000** [comment]
I found the problem, they're quests that do look like they're for the PR page, but have been removed from it for some reason. There's at least 5 of them.
![image](https://user-images.githubusercontent.com/8517039/84571271-2eb06800-ad60-11ea-8565-3f31542f13b7.png)
@Dream-Master Should I delete these or make them uncompletable? I think (but I'm not sure) that the text is explained more fully by the existing quests, but I don't know anything about PR. Also, could someone who knows about it read the quests and comment if they're obsolete or not? If they're not, we could also add them back in.

The quests are: Project red beginning, Can u eat those?, Routed pipes, Ghetto ME system, and Input chest for Ghetto ME system. You can find them by going into edit mode, clicking the gear, going to add/remove, and search the name

**Comment by Dream-Master** [comment]
Not remove them just fix or modifying them @Prometheus0000

**Comment by interestingusernam3** [comment]
This probably doesn't need to be open anymore now that the issue is fixed

**Comment by Prometheus0000** [comment]
It's not really 'fixed', I just unhid them. The text made me sleepy, so I ignored it. For all I know it's completely obsolete stuff handled by the already existing questline.

If someone tells me I can get rid of them, that'd be great. Or how to integrate them properly. I'm not learning PR for this.

Also, we don't close until the next release.
