### ISSUE TITLE
Add zpm/uv/uhv/uev quest and add tier 6/7/8 rocket quest

### ISSUE THREAD

**Issue by SKYCATV587** [GTNewHorizons/GT-New-Horizons-Modpack#6130]
now, quest is just luv and tire 5 rocket, it should be perfected

**Comment by chochem** [comment]
That would be great. Of course, these new quests dont have to be as plentiful or as detailed as before. After all, the player knows how to build a rocket by now. The only quest lines with more detail should be the ones about new mechanics like bartworks lab/vat (see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6115).

**Comment by Regian24** [comment]
That would be great, but the quests don't have to be as detailed as the LV/MV/HV ones, because you already played a lot at LuV. It would just be the machines you need to craft
