### ISSUE TITLE
[GT++, RFConvertor] crash report

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6132]
#### Which modpack version are you using?
2.0.8.3
### Crash server after try toggle RFConvertor from MAX to next mode.
[Crash-Report](https://pastebin.com/KZ4aGXYz)

**Comment by Prometheus0000** [comment]
Try a newer version or report on the GT++ github.

**Comment by chochem** [comment]
The RF converter actually is disabled in newer versions, as its wasn't supposed to be a thing in this pack anyway.

**Comment by mitchej123** [comment]
This block should be disabled.
