### ISSUE TITLE
Wrench rotates part of beds on rightclick

### ISSUE THREAD

**Issue by meneken17** [GTNewHorizons/GT-New-Horizons-Modpack#6133]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Right click on a bed with a wrench in the hand.
#
#### What happened instead? (Attach screenshots if needed)
The part of the bed rotates and the side without texture (between both bed blocks) becomes visible.
#
#### What do you suggest instead/what changes do you propose?
Don't rotate bed-blocks.

**Comment by boubou19** [comment]
![image](https://user-images.githubusercontent.com/12850933/82207823-bdb99400-990a-11ea-960e-339a843a5b68.png)

**Comment by mitchej123** [comment]
lol

**Comment by leagris** [comment]
Does it smell feet cheese when you sleep in it?
