### ISSUE TITLE
making bacterial petri dish does not work with mysterious crystal or infinty catalyst

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#6134]
#### Which modpack version are you using?
9.0pre7
#
#### If in multiplayer; On which server does this happen? 
MP
#
#### What did you try to do, and what did you expect to happen?
trie to make petri dish using mesterious crystal
#
#### What happened instead? (Attach screenshots if needed)
it dint craft
#
#### What do you suggest instead/what changes do you propose?
making it with biochaff works but making it with mysterios crystal or infinty cathelist does not want to work

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/84778661-4cc0d700-afb1-11ea-967b-f6abc6f74a92.png)
Both worked in QF4 for me. It was probably because the 'needs cleanroom' part wasn't working before.

**Comment by Dream-Master** [comment]
Yes this was fixed
