### ISSUE TITLE
unused materials in gregtech code

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6136]
GT code contains a lot of materials that were used to maintain compatibility with mods that are not present in GTNH. So i though it could be cool to clean it up (and maybe it will make the modpack load faster). Here are the materials that i wasn't able to determine if they are in use:

https://docs.google.com/spreadsheets/d/1r32Vcv69OuXlaIM8eGwv9pS58zIaq40xW8vRB-mmTvk/edit?usp=sharing

if you know that a listed material is in use, or will be in use, let me know and i'll update the list.

**Comment by Regian24** [comment]
"Antimatter"

🤔

**Comment by Prometheus0000** [comment]
We can just directly edit it though? I added some notes on stuff I remembered.

**Comment by boubou19** [comment]
my biggest fear about editing this file is it might cause some id shifting. If it does not then all good.

**Comment by Prometheus0000** [comment]
Since meta IDs are reserved, I don't think that's a problem, or else that wouldn't even be a thing. I could be wrong though, best way to know is to just try it.
