### ISSUE TITLE
Infinite radiation in radio hatch with radioactive ingots and dusts

### ISSUE THREAD

**Issue by Josh5minus1** [GTNewHorizons/GT-New-Horizons-Modpack#6137]
#### Which modpack version are you using?
2.0.9.0 beta 1
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Only rods can be accepted to radio hatch, until I put a radioactive ingot, (e.g. Einsteinium ingot)...
#
#### What happened instead? (Attach screenshots if needed)
It does get accepted and produced infinite radiation, the scanner says it sievert amount, despite of 0 amount. Destroying the hatch resets the hatch, or putting another material in it.
#
#### What do you suggest instead/what changes do you propose?
Remove the ingots compat with radio hatch

**Comment by yukieiji** [comment]
This issue occurs not only with ingots, but also with dust.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ?

**Comment by bartimaeusnek** [comment]
Even tho this didnt happended to me indev, i wrote some checks to prevent this.

**Comment by Josh5minus1** [comment]
Is the fix in QF4? Seems that it's still happening. (GT++ radioactive items are causing it)

**Comment by Josh5minus1** [comment]
#6530
