### ISSUE TITLE
Valentines Block Ore Dictionary

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#6140]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Tried crafting Valentines Blocks with GregTech pink dye.
#
#### What happened instead? (Attach screenshots if needed)
Recipe doesn't appear to use ore dictionary for pink dye. Requires Minecraft pink dye.
#
#### What do you suggest instead/what changes do you propose?
Ore dictionary pink dye in this recipe??

**Comment by Dream-Master** [comment]
yes we have chisel code and we can change this.
