### ISSUE TITLE
A simple new vein for higher tiers (LuV+) for solving Niobium shortage at these higher tiers

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#6142]
After previously hearing many members complain about Niobium shortages at LuV and above, most notably used for the Crystal & Wetware circuits; I arrived at a potential idea that would solve these problems without actually introducing an extremely powerful pure ore source. Introducing, the "Niobium-Tantalum Mineral Rich Vein."

Primary: Pyrochlore
Secondary: Pyrosite
Between: Tantalite
Sporadic: Tantalite
This occurs on T4+ (LuV+) planets. Has moderately good size, has a weight of 20 to spawn, and spawns on Y level 20 to 30.

This can serve as a moderately great, but lesser overpowered source for Niobium, as most of the Niobium you obtain from these ores are from byproducts, with the exception being Pyrochlore having Niobium after electrolyzing it.

**Comment by chochem** [comment]
interesting, never had a problem with those materials.

Niobium Ore is on T6 so in time for wetware. And not such big problem before either in my experience. 

I never had a tantalum shortage in these tiers either. are you using it for smds? If so maybe just use aluminum, or even better use your new ASMDs, they dont use tantalum :)

**Comment by ScriptedPiky** [comment]
I always remembered having trouble with Niobium when requiring large amounts of Crystal and Wetware. Ice and Bot and Houston on their private server had trouble with it as their main bottleneck that ended up resorting to UUM (pre-replicator nerf) for large quantities.

The Tantalite in this vein is mainly a byproduct to obtain Niobium while the Tantalum is a nice side-product. And while yeah, you can use ASMD's to get around Tantalum, it is again, a side-product of the main product that people are searching for in this vein.

**Comment by chochem** [comment]
the main bottleneck at the moment is indium. its in a very bad spot since the uum nerf. I guess that one is universal for all players.

Outside of that I guess it can vary a bit. I am noy denying it happened for you. ¯\\\_(ツ)_/¯

**Comment by botn365** [comment]
in my 2 playtrough had problems with niobium in both of them

**Comment by chochem** [comment]
I am not sure what to say, except: put a multiblock miner on a apatite vein and make sure your ore processing is set to wash/thermal/macerate all three ores to maximize tertiary. but you should know all that I am sure. and for wetwares you have niobium ore so at that points its trivial.

anyway, feel free to add the vein, I am just curious.

**Comment by ScriptedPiky** [comment]
Ah, yeah that is definitely true. An Apatite vein (primary source) or a Tantalite vein (secondary) with a T2 or T3 miner at that tier can definitely yield an instrumental amount of potential Niobium. Although, I am particularly uncertain how true this reflects on the live servers, though I assume it wouldn't be too harsh or awful in finding these veins. Do correct me if the older servers have or don't have this problem, though.

Overall, yeah, your point is definitely true & valid. I do believe the cause & trouble of why people struggle with Niobium might be due to a huge supply & demand of them for specific purposes (stacks of IV superconductor for some reason, though they don't really take all that much), or utilizing crystal and wetware circuits as their primary source for various tiers (e.g. using Crystalprocessor - IV or Crystalprocessor Assembly - LuV for main circuitry usage instead of the cheaper, Quantumprocessor's). That's roughly one main idea of why, though there obviously are other factors that I am entirely unsure of as well.

**Comment by ScriptedPiky** [comment]
Also, I probably should've added this prior, but these are the numbers (I think? At least from how I was viewing such numbers in the config) for the ore vein:

Weight of 20 - Height of 20-30 - Size 26
Primary: 550
Secondary: 475
Between: 425
Sporadic: 375

Thoughts on the numbers? I presume these are the averages of the ores? Though someone please do correct me.

**Comment by Prometheus0000** [comment]
NEI says this isn't generated in any dim.

**Comment by chochem** [comment]
hmm, it was supposed to be io and miranda, last I heard.

**Comment by Prometheus0000** [comment]
NEI says it generates now, @ScriptedPiky is this good enough and can this be closed/marked as fixed now?

**Comment by ScriptedPiky** [comment]
If it generates, then yes, we can close the ticket. Got a screenshot, though? Just to ensure, but will mark this as tested and will close it soon.

**Comment by Prometheus0000** [comment]
Making me do your work for you, huh? Was there anything else in GQ2 that needed checking while I have it open?

**Comment by Prometheus0000** [comment]
![2020-06-10_06 43 47](https://user-images.githubusercontent.com/8517039/84259009-d5d59b00-aae5-11ea-83a7-561d7f2fa7b0.png)
![2020-06-10_06 43 53](https://user-images.githubusercontent.com/8517039/84259019-d9692200-aae5-11ea-8701-84cc2ae0e28b.png)

On Io. Though I thought that chunks not having ores was fixed? So it would rerun it until something spawned? There's certainly enough depth for it here.

**Comment by ScriptedPiky** [comment]
Heh, I was on Zeta at the time and couldn't check NEI, but I could check the planets with the ores. Just needed to verify NEI displays ores are in these two dimensions.
But for the planet ores, those ones are different from the Overworld or Nether ores generations and there may or may not be enough high probability ores (especially something like Magnetite or another vein with 100% probability).

**Comment by Prometheus0000** [comment]
It's also on Miranda.
