### ISSUE TITLE
Circuits for Recipes keep changing on restart

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6143]
#### Which modpack version are you using?
2.0.9.0 beta2
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
make polyethylene/acetic acid in a LCR from oxygen and ethylene.
#
#### What happened instead? (Attach screenshots if needed)
The circuits in those recipes keep flipping between 1 and 2 for either when I restart the game.
I thought at first that I am just messing things up when all my ethylene got voided. Then I took screenshots just in case and saw what was going on:

First Polyethylene is on 1 and acetic acid on 2:
![2020-05-21_15 50 21](https://user-images.githubusercontent.com/40274384/82668111-fcb05800-9c30-11ea-9e3b-562fe0116d57.png)
![2020-05-21_15 50 40](https://user-images.githubusercontent.com/40274384/82668157-13ef4580-9c31-11ea-901f-5bb9f73bc176.png)

After restart, its the other way around, polyethylene is on 2 and acetic acid is on 1
![2020-05-22_13 37 59](https://user-images.githubusercontent.com/40274384/82668391-8e1fca00-9c31-11ea-8f2f-c1be7b5de73b.png)
:
![2020-05-22_13 27 49](https://user-images.githubusercontent.com/40274384/82668247-4436e400-9c31-11ea-9ebc-c66cd81c87bf.png)

#
#### What do you suggest instead/what changes do you propose?
fix it.
And more generally: Circuits should not be determined on game start. that seems like a bad idea. They should stay fixed not just between restarts but even over multiple versions as much as possible.

**Comment by chochem** [comment]
just to be clear: the pictures above are just one example! half the chemistry in my base is broken or voiding stuff.

**Comment by GeicowithaBango** [comment]
the ratio of the second recipe seems odd too. It was never 2:1

**Comment by bartimaeusnek** [comment]
fixed with Beta3
