### ISSUE TITLE
Add Just Enough Calculation to the pack [Feature Suggestion]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#6145]
#### What do you suggest instead/what changes do you propose?
I recently played an unrelated pack which included Just Enough Calculation. It was a really nice QoL addition and I think it could fit well into GT:NH. I tried installing it manually, but I was unable to auto-fill in machine recipes, which kind of hampers its usefullness. Overall I just think it would be nice to have, but clearly there are some compatiblity issues at the moment.
https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation

**Comment by Dream-Master** [comment]
if they only support crafting recipes it's not really enough
for this pack. But I not tested the mod to be honest.

**Comment by johnch18** [comment]
I think it supports any recipe which uses the question mark function in NEI, at least that's what I gathered from the mod page, so if that NEI feature can be configured to work for machines it might be useful.

**Comment by mitchej123** [comment]
This has been requested, and rejected in the past.  I believe it's client side, so feel free to add to your client.
