### ISSUE TITLE
Unify gt and gt++ phtalic acid

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6146]
#### Which modpack version are you using?
2.0.9.0 beta2
#
####

At the moment there is a phtalic acid from gt (green) and from gt++ (white, spelled phthalic for the cells. I think that's the correct spelling actually).

The green is used for PBI and UnknownNutrientAgar, while the white one is used for the gt++ rocket fuels. With the rocket changes proposed by bot, the later one will likely be mandatory as well in the future (in small amounts).

At the moment, green and white versions have different recipes and are incompatible. However there is a distillery recipe to convert the white to the green, just not the other way around. 

It would be great if only one were needed, or at least if one could also convert from green to white.

Let me know if I should cross-post this over at the gt++ github.

**Comment by Dream-Master** [comment]
@draknyte1

**Comment by draknyte1** [comment]
Post it to my GitHub.

**Comment by draknyte1** [comment]
Fixed in Dev.
