### ISSUE TITLE
Nether Ore Gen: No Pattern and InGameInfo is wrong

### ISSUE THREAD

**Issue by M0rtim3r** [GTNewHorizons/GT-New-Horizons-Modpack#6148]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Multiplayer; Official Server Delta
#
#### What did you try to do, and what did you expect to happen?
Tried to find ores in the nether. I searched in the chunks where InGameInfo said on the screen: 'This is an ore chunk'. I expected it to follow the same pattern as in the overworld: every 3rd chunk is an ore chunk. In one spot InGameInfo said 'This is an ore chunk' where it was only the second chunk from the last ore chunk. So i asked the server helper for help (thx boubs:))
#
#### What happened instead? (Attach screenshots if needed)
Turns out: There is no pattern for ore gen in the nether and InGameInfo chooses randomly what to say about ore chunks.
#
#### What do you suggest instead/what changes do you propose?
Make ore gen in the nether follow the same pattern as in the overworld: A vein every 3rd chunk. Make InGameInfo a realiable tool. Thanks for all your effort!

**Comment by mitchej123** [comment]
IGI is just a hint.  Not all ore chunks spawn ores.

**Comment by boubou19** [comment]
Checked it in the nether and some veins have their center chunk deleted by the worldgen (in addition of the empty ore chunks) but i guess there is nothing that can be done here.
