### ISSUE TITLE
ProjectRed Block Breaker unable to break Obsidian

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#6150]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Use ProjectRed Block Breaker to break Obsidian
#
#### What happened instead? (Attach screenshots if needed)
Block Breaker cannot break Obsidian due to increased block hardness level. In the original RedPower 2 mod, the block breaker was able to do so
#
#### What do you suggest instead/what changes do you propose?
Enable the block breaker to break Obsidian (after all, the recipe requires a diamond drill tip).
Disclaimer: I am in no way a programmer, but the respective line may be found here:
https://github.com/GTNewHorizons/ProjectRed/blob/2001af649bc0c844593c405822a3249d21e00c74/src/mrtjp/projectred/expansion/TileBlockBreaker.scala#L43

**Comment by repo-alt** [comment]
The quoted repository is for 1.12, there is no 1.7.10 branch.

**Comment by draknyte1** [comment]
There used to be a repo for 1.7.10.

**Comment by repo-alt** [comment]
You mean there - somewhere, or there, at this address?

**Comment by GTNH-Afx237v7** [comment]
The link takes me to the ProjectRed repo within GTNH though? (See top left).
![A07F90FF-8BF3-4965-A68B-15BF3083B65A](https://user-images.githubusercontent.com/64365566/87252297-17a18a80-c472-11ea-980d-80e93e6747a5.png)

**Comment by repo-alt** [comment]
Exactly. And there is no 1.7.10 branch there.

**Comment by Dream-Master** [comment]
but we can make a branch for 1.7.10in us fork

**Comment by Dream-Master** [comment]
@repo-alt are you able to change the code?

**Comment by repo-alt** [comment]
I have no idea what would it take to find the revision compilable at 1.7.10

**Comment by Dream-Master** [comment]
i forked it now and i see a diamond block breaker in code. This should solve the problem hopfully.

**Comment by GTNH-Afx237v7** [comment]
Stumbled upon this as well... no longer needed from my point of view. Feel free to close.
