### ISSUE TITLE
[GregTech] Processing array does work with mass fabricators

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#6152]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I was upgrading my mass fabricator array, and wanted to save some space by putting them in a processing array.
The array has a LuV tier energy hatch (8A x LV x 64 = 0.5A LuV), EV output hatch and 56 LV fabricators
#
#### What happened instead? (Attach screenshots if needed)
The array doesn't start. Upon further inspection with a tricorder erroneously gives me that it has tier 0 machines in it, whereas the other processing array with LVs returns tier 1.

I've tried both 56 machines and a single machine with no difference
I've tried removing the input hatch in case it was expecting UUA, which also didn't change anything.

#
#### What do you suggest instead/what changes do you propose?
The processing array states that it runs machines "as if placed in the world", and should therefore be made to work with mass fabricators.

**Comment by Prometheus0000** [comment]
I believe it was specifically set to not work with them. You could try the multi, but I hear that's worse.

**Comment by combusterf** [comment]
I can of course still place them individually and see them work. I'm not sure if that's beneficial to the server though.

**Comment by Prometheus0000** [comment]
From GT++'s recent changelog (1.05.62) (a few hours too late for beta3)
+ Added support for Custom Machines being registered to the PA. (If GT is up-to date)(Try a Simple Washer!)

So maybe you'll be able to use it in beta4? But I think it would have to be added to a config list or done in code, rather than anything goes automatically (I could be wrong though).

**Comment by draknyte1** [comment]
They don’t use recipes maps. They have hard coded processing logic. They intentionally wont ever be supported.
