### ISSUE TITLE
Potential Player Data Deletion or Reverting & Server Crash by SpecialMobs

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#6153]
Occurred on Zeta, at Pacific Time 8:17 PM, as well as some time previously; I was fighting & farming Wither Skeletons when I had happened to immediately die in a single hit, from thirty hearts down to zero in full Awakened Ichorium Armor, by a Mighty Champion prefixed Sniper Skeleton. Followed by an instant server crash. In addition, I apparently had died twice and had caused no grave to spawn. But when I logged back in, I had lost ALL my tinker hearts (should NEVER disappear on death), along with the introduction guide to Tinker's Construct, a book that is ONLY given to you if you happen to log in as a "new" player to a world/server. Thus, there is a potential that SpecialMobs is causing some extremely dangerous corruption shenanigans to player data and should be investigated.

Do note, that this occurs on nearly all versions of SpecialMobs as a whole. I've only had one previous instance where this occurred on Zeta and was caused directly by a SpecialMob's mob; deleting my player data and corrupting it.
Server crash provided by Dream: [message (4).txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4673268/message.4.txt)
Alternatively, a Paste Bin link: https://pastebin.com/3BYxbTM1

**Comment by Dream-Master** [comment]
@bartimaeusnek  @richardhendricks @wlhlm any idea about it?

**Comment by nrodriguesdev** [comment]
This is a problem within Minecraft itself. 

All AI actions are stored in a List called executingTaskEntries in the EntityAITasks class. The ConcurrentModificationException error is thrown by the List iterator when it detects that some piece of code is interacting with the list incorrectly. 

There are three instances of the minecraft devs incorrectly accessing the list in the EntityAITasks class: line 50 (removeTask), 81(onUpdateTasks), 87(onUpdateTasks).

This has to be fixed using ASM to replace the methods with ones that safely access the executingTaskEntries list.
