### ISSUE TITLE
GalacticraftCore not downloading with SpecialDepLoader

### ISSUE THREAD

**Issue by DuwidG** [GTNewHorizons/GT-New-Horizons-Modpack#6154]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
It's on Pack startup (twitch launcher)
#
#### What did you try to do, and what did you expect to happen?
The first time I loaded up the modpack in twitch launcher, it uses SpecialDepLoader to download a few other mods. Galacticraft is one of them.
#
#### What happened instead? (Attach screenshots if needed)
It says a download error has occured: "SpecialDepLoader was unable to download required library GalacticraftCore-1.7-3.0.12.504.jar Check your internet connection and try restarting or
download it manually from
https://ci.micdoodle8.com/job/Galacticraft-1.7/504/artifact/Forge/build/libs//GalacticraftCore-1.7-3.0.12.504.jar "
This link is non-existant. I will be downloading the mod from somewhere else, but I just wanted to mention this.
#
#### What do you suggest instead/what changes do you propose?
Adding in a link that works

**Comment by bartimaeusnek** [comment]
Thats known, will be changed for 2.0.9.0.

**Comment by Prometheus0000** [comment]
See #5993

**Comment by Prometheus0000** [comment]
I assume this is fixed now?

**Comment by Dream-Master** [comment]
yes
