### ISSUE TITLE
SmoohFont mod

### ISSUE THREAD

**Issue by EngineerXL** [GTNewHorizons/GT-New-Horizons-Modpack#6157]
#### What do you suggest instead/what changes do you propose?
How about this SmoothFont? Playing not english language makes some things unreadable so as the font is too small. It does not need lots of RAM, if you will not set max resolution and smoothing. The only thing it is not compatible is FastCraft, but it can be fixed by simply turning off FastCraft font tweaks in cfg

**Comment by leagris** [comment]
:+1: [`SmoothFont-1.7.10-1.15.3.jar`](https://www.curseforge.com/minecraft/mc-mods/smooth-font/files/2614474)

**Comment by Prometheus0000** [comment]
You can add it to the optional mods page on the wiki.
