### ISSUE TITLE
Arrange some HV early quests

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#6159]
#### Which modpack version are you using?
2.0.8.3

I'm just talking about some possible improvements

When you craft your first HV machine Hull, the quest 1237 Glowstone doped monocrystalline silicon boule is unlocked and this is clearly leading you (in the description of the quest) to build a cleanroom and a vaccum freezer to craft this item.

The vacumm freezer needs EV circuits (workstations) and this means that you need Processors assembly; integrated processors and a MV circuit assembler (crafted in a cleanroom), which are quests unlocked after 3 other quests from the Hv machine Hull one (They are : 1231, 1232, 1018).
So I was a bit dissapointed by this "later showing" as I build the cleanroom and the vacuum freezer before doing those quests

So I suggest to unlock the quest 1237 after crafting the vacuum freezer AND the kanthal coils, so she will not be linked to the Machine hull quest anymore (160) 
Then it would be more apropriate to unlock the cleanroom quest in multiblock goals when the quest 1018 is unlocked

Another one is the vibrant alloy quest (989) which is unlocked before the energetic alloy one (990) and this is not making sense in my opinion because vibrant alloy needs nichrome coils in the EBF which are clearly not reachable after crafting your first HV machine Hull
So maybe the energetic alloy quest should be unlocked after crafting the kanthal coils as like as the quest 1237 I mentioned before, and the vibrant one should be unlocked when the nichrome coils are crafted

To finish I noticed that for the quest 1137, you need titanium gears, which are of course items not craftable before you reach the moon, so I suggest to unlock this quest after you land on the moon.
And talking about the moon, While the dire crafting table needs a IV mainframe circuit, the quest 809 shouldn't be unlocked untill you craft the IV circuit mainframe (quest 1225)

If a similar issue is already posted let me know which one it is and I will close mine. 
( I didn't found any but I probably didn't search correctly )

**Comment by Regian24** [comment]
Also, the HV cutting machine quest says you need a HV cutting machine to cut the glowstone doped wafers, but it's actually a 120EU recipe

**Comment by johnch18** [comment]
In a similar vein, I would separate the SMD Diode from the other SMD components questwise. You can make the 3 simpler SMD components starting once you get the MV assembler, and I think moving that earlier in the progression would make a lot more sense.

**Comment by Prometheus0000** [comment]
#5305?

**Comment by Nicouuuuu** [comment]
> In a similar vein, I would separate the SMD Diode from the other SMD components questwise. You can make the 3 simpler SMD components starting once you get the MV assembler, and I think moving that earlier in the progression would make a lot more sense.

Yeah actually I started to craft SMD resistors mostly and a bit of capacitors and transistors at MV (even if it's not very easy for the PVC sheets and the gallium foils, it is doable)

Soo #5305 is a good option I think

**Comment by Prometheus0000** [comment]
BTW when you use # before a number it links to other issues (or PRs) on the repo, so you shouldn't do that when listing quest numbers.

**Comment by Nicouuuuu** [comment]
> BTW when you use # before a number it links to other issues (or PRs) on the repo, so you shouldn't do that when listing quest numbers.

No problem I'll be more carefull :)

**Comment by Nicouuuuu** [comment]
I can also notice that the obelisk quest (167) isn't linked to the vibrant alloy quest (989) which should be more logical than linking the obelisk to the HV machine Hull quest

**Comment by Prometheus0000** [comment]
> Energetic alloy one (990)

Already requires coils. 

> I can also notice that the obelisk quest (167) isn't linked to the vibrant alloy quest (989) which should be more logical than linking the obelisk to the HV machine Hull quest

It actually uses the energetic alloy, so I linked it from that.
