### ISSUE TITLE
Suggestion: Change how the Portable Scanner displays scanned info

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6162]
#### Which modpack version are you using?
beta3
#
Basically, if the info you need is not in the last few lines, you need to hit T to see the rest of the scanned info in the chat log, if you do this a lot, it's pretty annoying.
#
#### What do you suggest instead/what changes do you propose?
Show as much as possible of the scanned info/text. Assuming this is possible.

**Comment by chochem** [comment]
you can use nano/quantum armor to display the entire thing, but I dont like it personally.

**Comment by YannickMG** [comment]
Alternatively, make it so you don't need to rely exclusively on the scanner for critical information.
