### ISSUE TITLE
Botany Ceramic Tile

### ISSUE THREAD

**Issue by smerk84** [GTNewHorizons/GT-New-Horizons-Modpack#6163]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
no
#
#### What did you try to do, and what did you expect to happen?
When i want to craft the ceramic tile for the botany quest, i cant craft yellow ones. When i put 3 yellow ceramic and a mortar, how the quest want, then there comes red brown ones.
#
#### What happened instead? (Attach screenshots if needed)

![](https://cdn.discordapp.com/attachments/234936569360809996/714592193330937876/unknown.png)

#
#### What do you suggest instead/what changes do you propose?
Yellow Ceramic Tiles

**Comment by smerk84** [comment]
I tried the normal version from binniesmods, than everything is working. I dont know what changes you did in the "binnie-mods-1.7.10-gtnh-2.0.28"

**Comment by Dream-Master** [comment]
So far i know we never changed recipes for ceramic
