### ISSUE TITLE
enderio farming station bugged in beta3

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6165]
#### Which modpack version are you using?
2.0.9.0 beta3
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### 

My enderio farming stations worked fine before. now they were stuck at 40/250000 RF doing absolutely nothing.

A bit of testing showed a very peculiar and clearly bugged behavior:

the farming station now has two -lets call them- 'modes':

mode A) using a LOT of power but displaying 40RF/t base use. If the power runs out I get the behaviour orginally observed where it does nothing due to too large idle power

mode B) using barely any power but displaying 1600RF/t base use.

before updating it had the low power usage of B) with the display of A), which made sense.

But thats not all, you can consistently (!) switch between the two modes by breaking and replacing the machine.

Other enderio machines also might be affected, I have not tested that yet.

**Comment by bartimaeusnek** [comment]
*heh* that might be a side effect of the transdimensional reciver fix.

**Comment by Darkstar1712** [comment]
This issue still seems to be happening on the latest version, been experiencing it on Zeta.

**Comment by Dream-Master** [comment]
@bartimaeusnek so not fixed i guess ?

**Comment by Prometheus0000** [comment]
Bart said:
It’s fixed. Old ones must be reset tho.
Place in crafting grid and take out again

Does that fix it?

**Comment by Darkstar1712** [comment]
Yeah, it works fine after doing that.
