### ISSUE TITLE
Thaumic Horizons Mod nerf

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#6167]
Thaumic Horizons Mod nerf

**Comment by GTNH-Colen** [comment]
Specifically?

**Comment by Dream-Master** [comment]
in general the mod was never touched and havent gt materials like plates instead of ingots. (only one example)

**Comment by bartimaeusnek** [comment]
Buff Infusion stuff, keep costs for the rest the same. (Already expensive enough)

**Comment by Dream-Master** [comment]
i will gregifying a bit more like ingots becomes plates etc.

**Comment by Prometheus0000** [comment]
Did you finish this?

**Comment by Dream-Master** [comment]
Nope. Need to continue like Automage as well.

**Comment by SteamDoge9000** [comment]
sorry to bug you all, but the Gollemancers bell seems to be breaking another mod that I added called Magic Cookies with its own bell that uses the original Golmancers bell, I was wondering if there could be something done to fix this so the NH bell can be used for MC mod

**Comment by SteamDoge9000** [comment]
on another note, a small bug with the modified Thaumic Horizons, the syringe that is launched does not move properly while the actual projectile hits somehwere else 
![image](https://user-images.githubusercontent.com/38770780/118404696-f4230f80-b641-11eb-9de1-e8dc35aa78b2.png)
The red X is where the projectile acutaly is while the syringe is not where it is
like something with it not syncing with the pojectiles movement properly or something
