### ISSUE TITLE
Suggestion: Dont release with the new pollution visuals until they get some major overhauls and fixes

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6170]
#### Which modpack version are you using?
2.0.9.0 beta4
#
#### If in multiplayer; On which server does this happen? 
sp
#
####

Edit: The original suggestion was to drop the new visuals all together, but dream made it clear that is not gonna happen. So I hope they will at least be held back until some major overhauls. More precisely all the visual bugs and glitches as well as the overall scaling and starting point of the mechanic. But this should also include giving the player better/earlier tools to fight pollution an the fps impact these mechanics have.
#
####

The new pollution visuals just make the game look terrible. but if you think that is too subjective, here are some more objective points about it:
- it glitches the horizon by just being a few chunks in range of pollution
- it FLICKERS back and forth between different modes (far away from pollution, pollution in a closeby chunk, in pollution chunk)
- its way over the top even at low pollution levels

But even with those points fixed, there is no way I would want to play with this.

Please just remove it. It was an interesting idea, but is just terrible in practice. The game is just unplayable in this state.

glitched horizon, not sure if that is clear to see in the picture. its a lot worse when it flickers of course.
![image](https://user-images.githubusercontent.com/40274384/83174950-13641c80-a113-11ea-9a83-5a53476f1552.png)

there are some much better pics/gifs on the discord

**Comment by bartimaeusnek** [comment]
> it glitches the horizon by just being a few chunks in range of pollution

Side effect of the renderer itself, not fixable.

> it FLICKERS back and forth between different modes (far away from pollution, pollution in a closeby chunk, in pollution chunk)

well thats a problem with the per block distribution, the logic behind that is relativly simple, so it might look weird if you are on a border. Sampsa is going to rework that logic.

> its way over the top even at low pollution levels

thats not objective, but a subjective view.

**Comment by draknyte1** [comment]
Base GT also only has it as a mild fog which barely works. As you’d said yourself. Just make it a config option so as not to utterly ruin the game for anyone running shaders or who think it’s look shit. 💁🏻‍♀️

**Comment by chochem** [comment]
@bartimaeusnek sorry for my stronger language. this is nothing personal. with the last version being called beta4final or something like that, I am just worried dream is about to push a release that includes this very questionable last minute addition.

Also to be clear: I have nothing in general against visual changes. I really like the hardcore darkness for example. But hardcore darkness actually looks really good.

**Comment by GeicowithaBango** [comment]
„this is nothing personal“ PogClap

**Comment by chochem** [comment]
> 
> 
> „this is nothing personal“ PogClap

it isnt.

**Comment by Bluebine** [comment]
If this is gonna stay, it needs toned down. It's absurd as is.
![2020-05-28_13 58 35](https://user-images.githubusercontent.com/29802757/83183054-40093b80-a0f5-11ea-9eb2-7a32b03d3dd6.png)
This is my base at 476k pollution. I can't see shit, and this is a rather low level of pollution, before even the minor status effects.

**Comment by leagris** [comment]
The effect is nice but it surely needs some tone-down

**Comment by leagris** [comment]
FYI, I noticed a big drop in FPS. From 50-60 before and now 15-20 FPS with 2.0.9.0-beta2

**Comment by Dream-Master** [comment]
I see the problem here that no one realy care pollution before. So now its time to look for pollution reducing devices.

**Comment by Dream-Master** [comment]
Maybe we have to change the values how much fog is there for how much pollution but remove is not an option. And maybe we have to check for cleaning devices early LV if we not have some allready.

**Comment by mitchej123** [comment]
inb4 alk releases a client side only mod that disables it

**Comment by draknyte1** [comment]
Scrubbers exist already from ULV+.

**Comment by Dream-Master** [comment]
so why not use them or they to weak ?

**Comment by leagris** [comment]
Scrubbers for the BBF?
WTF If pollution bugs me enough, Ill just turn it off. Because I don't want to deal with that early game.

**Comment by Dream-Master** [comment]
Are you sure BFF pull out enough pollution to make it really foggy ?

**Comment by chochem** [comment]
> 
> 
> Are you sure BFF pull out enough pollution to make it really foggy ?

yes. BBF is easily enough for this.

**Comment by moller21** [comment]
I had a look in the pollution code trying to figure out how it calculates. Looks like it reduces it faster the fewer chunks are loaded? So servers get more pollution. Could anyone confirm?

**Comment by GTNH-Colen** [comment]
> If this is gonna stay, it needs toned down. It's absurd as is.
> ![2020-05-28_13 58 35](https://user-images.githubusercontent.com/29802757/83183054-40093b80-a0f5-11ea-9eb2-7a32b03d3dd6.png)
> This is my base at 476k pollution. I can't see shit, and this is a rather low level of pollution, before even the minor status effects.

This is ridiculous imo, players in extreme early game should not have these kinds of effects. I would be okay with this level of fog on a mid to endgame base since then you have the ability to scrub it away.



> > it glitches the horizon by just being a few chunks in range of pollution
> 
> Side effect of the renderer itself, not fixable.
> 
> > it FLICKERS back and forth between different modes (far away from pollution, pollution in a closeby chunk, in pollution chunk)
> 
> well thats a problem with the per block distribution, the logic behind that is relativly simple, so it might look weird if you are on a border. Sampsa is going to rework that logic.
> 

If the rendering issues can't be fixed then we have to find other ways of handling pollution as this flicking is just too much of a pain to be tolerated. See below for an example courtesy of Sampsa.


![ezgif-6-8ae1cff45790](https://user-images.githubusercontent.com/54497873/83198810-e24a1300-a137-11ea-93de-c19a729b562b.gif)

**Comment by Prometheus0000** [comment]
Shouldn't it only show up when you get the first pollution effects? And get worse once you get to the higher ones?

And I'm not sure you can make the turbine for the scrubber right away.

**Comment by chochem** [comment]
> 
> 
>...but remove is not an option.

that's a shame. I can easily see this driving away players from the pack in significant numbers.

But if that is really set in stone, then at least it should be restricted to very high pollution levels. This is clearly the most drastic of all the pollution effects. It just being thin smog on low levels does not help. The visual difference between no smog and some smog is much bigger than the difference between some and a lot.

**Comment by chochem** [comment]
Sampsa helped with a new versions. which I got to test a bit. Some parts are much smoother, but

- ender tanks glitch out, so do OC screens and armor
- when crossing a chunk boudary slowly, the visual effects turn off completely for a moment
- I still get the weird double horizon at very low pollution levels. (this is very non smooth and leads to screen flickering when moving about)
- projectred lamps through fog look way to gorgeous to be aloud
- overall this whole thing still makes me want to die and will inevitably drive away new players that dont have access to scrubbers yet. Those are gated by the MV assembler for rotors or am I missing something there?

The easiest solution could be to restrict the effects to 1M+ pollution or so. (the higher, the better)

And certainly, this should not be in any release until it is much improved and fixed.

**Comment by SampsaxD** [comment]
The fog rendering in itself absolutely wrecks any integrated graphics, making the pack even more unplayable with a low-end computer.

Not adding a config option with the reasoning of "making the pack harder" does indeed accomplish it, by making it so hard to run (on some computers) that they cannot even play it.

Some other things to make the smog actually a fun addition instead of a total buzzkill:
1. Make the smog only start after some threshold (200k? maybe 300k?) so you can run a few polluting machines without getting the effect. (1 or 2 EBFs)
2. Make the range of the fog to go from 300k-3000k instead of the current 0-2000k. This would smooth out the curve, and make the super smog only appear with like 4+ pyrolyses, instead of getting it already in your early game base with BBFs.

**Comment by Folanlron** [comment]
As a person who is colour blind ... I love playing games were I can only see 10m in front of me.

Just give users a off switch.

**Comment by Regian24** [comment]
wait, can't you guys put it in settings? kinda like the minecraft clouds that you can switch off

**Comment by Larsien973** [comment]
I like the idea, but the implementation in 2.0.9.0 RC2 drops my fps from ~60 down to 10-12, making the pack unplayable. This is on a i5-3350P @ 3.10GHz with a GTX 760

**Comment by Prometheus0000** [comment]
It's already been decided to remove it from the next version until the FPS problem is fixed. Though it might come back in some version for testing whether it IS fixed. And it doesn't have any problems on some people's computers (the ones behind making the pollution code).

**Comment by AndreasBoegh** [comment]
The scrubber machine is available in LV or ULV. But it requires a rotor which is first available with and MV assembler

**Comment by chochem** [comment]
@AndreasBoegh Alk has already added new low tier rotors, though they might not work yet https://github.com/alkcorp/GTplusplus/issues/711

**Comment by Prometheus0000** [comment]
Visual pollution is coming back in the next version, you may want to check it out. My understanding is that it doesn't impact FPS, but I haven't really tried it.
![2020-10-10_08 49 47](https://user-images.githubusercontent.com/8517039/95655485-b53e4180-0ad5-11eb-9274-ab09cea28faa.png)
#5954 #5160

**Comment by boubou19** [comment]
it is now live in 2.1.0.0

**Comment by Dream-Master** [comment]
> @AndreasBoegh Alk has already added new low tier rotors, though they might not work yet [alkcorp/GTplusplus#711](https://github.com/alkcorp/GTplusplus/issues/711)

And they wont be work so long i not get a fixed version. version 68 is ancient
