### ISSUE TITLE
Bee species gene cant be added via sequencer

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#6171]
#### Which modpack version are you using?
Zeta 2.0.9.0-beta3, not tested on beta4fix yet, bcs obtaining those isolated genes is kinda tricky...

Edit : Did some testing in SP with beta4fix
#
#### What did you try to do, and what did you expect to happen?
Trying to add those species (currently certus and lapis) to Genetics  Gene database and even they run through the sequencer they arent in the list. 

So in SP ive tested a couple of bee species whose genes cant be added to the gene database, bcs you need to do that manually ive did only the uranium vein or so yet. 
#
#### What happened instead? (Attach screenshots if needed)
It consume the item, dont add that allele to the list. Although ive managed to obtain and succesfully added severaly other bee species that day, namely Austere, Secluded, Hermitic, Frugal 
#
SP not functioning (will added when find more): 
Certus
Lapis
Diamond
Platinum
Nickel
Emerald
Sapphire
Ruby

SP functioning (will be adding more later):
Plutonium
Uranium
Naquadah
Naquadria
MakeMake
Chrome
Titanium
Redstone
Aluminium
Tin
Iron
Copper
Zinc
Clay
Diligent
Olivine
Unweary
Industrious
Imperial
Hermitic
Coal
Manyullyn
Stickyresin
Oil
Apatite
Ash
Coolant
Energy
Lapotron
Cryotheum
Pyrotheum
Red Alloy
Redstone Alloy
Conductive Iron
Vibrant Alloy
Energetic Alloy
Electrical Steel
Pulsating Iron
Stainless Steel
Enderium

**Comment by Prometheus0000** [comment]
Could you try and determine if they're similar by mod, ie all extra bees or magic bees or whatnot. Also, a complete list of what _does_ work (that you've checked). Looking at that list I wonder if it's the replaced bees, from when you had to drop them on the ground to exchange them. Maybe something about them wasn't set properly?

**Comment by Dream-Master** [comment]
@Prometheus0000 i guess its a gt bee problem maybe some alelle on gem bees not working or wrong

**Comment by Hyperic88** [comment]
Edit

**Comment by Hyperic88** [comment]
@Dream-Master is there some list of gt bees that were"updated" so i can primary test those?

**Comment by Dream-Master** [comment]
Imperial and industrious bees are pure foresty

**Comment by Dream-Master** [comment]
check for gt combs all have one bee for it

**Comment by Hyperic88** [comment]
Ok, so not all gt bees are affected so its not "gt bees are bad" in general... they have to have something else in common

**Comment by Hyperic88** [comment]
Added few other species to both lists

**Comment by Dream-Master** [comment]
@Hyperic88 can you point out wich alelle is not working ?

**Comment by Hyperic88** [comment]
> @Hyperic88 can you point out wich alelle is not working ?

Species one

**Comment by Dream-Master** [comment]
i mean like territory, or woking speed, or flowering etc

**Comment by Hyperic88** [comment]
i know what you meant, and its what i said "Species", thats one the traits

**Comment by Dream-Master** [comment]
mh ok will check what that mean
