### ISSUE TITLE
Endgame Goals Tab

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#6172]
So currently we don't really have a tab like this, some stuff is spread about and other things have no tab at all. I was thinking we could make a tab that unlocks say after the legendary tab that would have quests for super endgame goals. Current list of ideas I have is as follows.

- Infinity Armour
- Stargate (This is more a meme but would be funny nonetheless)
- Infinity Chest
- UV Solar
- MK4 Fusion
- Eternal Singularity?

I'm sure there is more stuff around if any of you can think of it. The page wouldn't really need any structure to it, just some quests scattered around.

**Comment by Prometheus0000** [comment]
UEV Motors? Didn't you make a shrine for it lol?
And MK4 and ES aren't required?
The materials for a max sized LESU? Or do the quests for it require that already?
Maybe the draconic reactor? Given how kinda useless RF is, I'm not sure how many people would make it.
Orb of Armok (there's a quest in the BM tab)
Creative Energy Cell (there's a quest in the AE tab)
The unlimited range booster for the wireless terminal (there's a quest in the AE tab)
The unlimited air tank
The OC dire table crafts (was there more than one?)
The other, similar items made in the dire table

BTW AoE had packing taped drawers full of X as crafting components for endgame stuff, maybe we could do that for Infinity Blocks or so? <- Not a serious suggestion

**Comment by GTNH-Colen** [comment]
> UEV Motors? Didn't you make a shrine for it lol?

Lmao, UEV parts quest could be fun. If we ever develop to a proper UEV tab we can just remove them and merge it in there, they use like 16 infinity per motor iirc.
> And MK4 and ES aren't required?

Not sure what you mean by required, most of this stuff isn't required it's just a fun list of goals to work towards if you've essentially finished the pack. MK4 Fusion is absurdly expensive (100k+ neutronium ingots and 500+ UEV circuits along with a myriad of other resources). ES is arguably craft-able in like UV I suppose, its only good use is the infinity chest though so I was thinking maybe having a quest for that and then connecting it to the inf chest quest.
> The materials for a max sized LESU? Or do the quests for it require that already?

Does the LESU even have a max size? I thought you could just add them indefinitely.
> Draconic reactor
> Orb of Armok (there's a quest in the BM tab)
> Creative Energy Cell (there's a quest in the AE tab)
> The unlimited air tank

These seem good, I don't think they have quests currently
> The unlimited range booster for the wireless terminal (there's a quest in the AE tab)

I thought someone was adding a quest for this in the AE tab somewhere? Could be mistaken
> The OC dire table crafts (was there more than one?)

The OC item only uses up to UV or maybe UHV circuits, no infinity at all so not really endgame enough to be included imo.

**Comment by Prometheus0000** [comment]
The ones that have quests already are ones I added quests for myself. You can download one of the betas or grab the quest file directly if you want to look at them.

Also, up until a few months ago I thought you needed to make the ES for the first 2 infinity catalysts for the deep dark portal. But there's the dust on Vega B or something, so it doesn't really have much use like you say. Maybe we should change out the catalysts for ES's? Or if that's unreasonable, one of the void miner upgrades?

**Comment by GTNH-Colen** [comment]
> The ones that have quests already are ones I added quests for myself. You can download one of the betas or grab the quest file directly if you want to look at them.
> 
> Also, up until a few months ago I thought you needed to make the ES for the first 2 infinity catalysts for the deep dark portal. But there's the dust on Vega B or something, so it doesn't really have much use like you say. Maybe we should change out the catalysts for ES's? Or if that's unreasonable, one of the void miner upgrades?

You've never needed eternal singularities to make the DD portal, they've been exclusively used in the stargate/infinity chest as far back as I can remember at least. Given the power of the void miner I wouldn't be opposed to nerfing the DD recipe to require eternal singularities but perhaps that should take another thread (We could then add a DD portal quest to this tab though which would be nice).

**Comment by Regian24** [comment]
A quest to fully complete a Really Ultimate Battery (9 QUINTILLION EU)

that could be fun.

**Comment by Prometheus0000** [comment]
No no no, you need enough to fill a battery buffer, so 16 filled ones.

**Comment by chochem** [comment]
dont you just put it in an ultimate capacitor? or does that just take the ultimate one? I dont know the recipe. In that case the really ultimate would be a bit useless.

**Comment by Regian24** [comment]
> No no no, you need enough to fill a battery buffer, so 16 filled ones.

so, if you are UEV (8388608EU/t), it would take 54975581500 seconds to fill up one battery, and that is 1743 years, so no.

**Comment by chochem** [comment]
also regarding LESU: that thing should not get any new quests. its a pure nostalgia thing from bart with no purpose in the game. If anything the existing ones should be removed and replaced with LSC quests.

**Comment by Prometheus0000** [comment]
I don't think dream would approve of removing the existing quests, since it's still there, it's just outclassed (like it has been for a long time). Maybe you could suggest a way for bart to make it useful?

That said, I do think it should have some quests, explaining what it is and how to make/use it. Maybe someone who's made it could make a new issue? I haven't even touched it. Same for the TFFT. And kekz's jars, now that I think about it. Or was the TFFT buggy? I remember kekz saying something about that in discord.

**Comment by chochem** [comment]
It has come up before and bart does not seem to care about its usefulness. it really is just meant to be a nostalgia item. but best ask him yourself if you dont believe me.

Its also not just outclassed. It would still be useless if PSS and LSC were removed tomorrow due to the low voltage levels. The old school LESU was designed around LV-HV and had a maximum of 1,999 blocks, so not even 1A EV. In GTNH it is available in EV. while the cap is removed (I think), this works out roughly as bad as one would imagine.

Either way, my point is that the *focus* should certainly be on PSS/LSC/.. not on the LESU, even if no quests are being removed.

**Comment by botn365** [comment]
@Regian24 a realy ult battery is UMV and you can fill it with 2A of UMV so if your making 32A of UMV it would only take 54,477007813 years to fill it

**Comment by Regian24** [comment]
> it would only take 54,477007813 years

its still 54 years LOL

**Comment by GTNH-Colen** [comment]
<img width="844" alt="Screenshot 2020-05-30 at 01 32 55" src="https://user-images.githubusercontent.com/54497873/83352139-79ce8200-a341-11ea-86a4-0bad9ae97764.png">
Finished tab for those curious, will perhaps update it in future if anyone has any additional ideas or new endgame content gets added.

**Comment by Prometheus0000** [comment]
Was the deep dark portal one you made or did you remember to copy the existing one for that one too? And how long does it take to make the NAN? Would you definitely be able to make it before the others, or was that quest just an informative checkbox one (I remember someone suggesting that).

**Comment by GTNH-Colen** [comment]
> Was the deep dark portal one you made or did you remember to copy the existing one for that one too? And how long does it take to make the NAN? Would you definitely be able to make it before the others, or was that quest just an informative checkbox one (I remember someone suggesting that).

Not done DD yet, want to nerf it before adding it here but not sure if we will get that in for the next version as ppl will probs want a RFC on that one. NaN takes 128 neutronium blocks at UV voltage for ~700k seconds? Can't recall the exact number but it's pretty brutal (GT++ multi helps here). Most of this stuff is post infinity which is UV+ territory (Murky ground here as tiers this high up get screwy).

**Comment by Prometheus0000** [comment]
I guess that's the eternal singularity on the left then, they look similar with the textures bugged out.

So does the NAN icon using quest require making it then? If not, we should have one for it, how else will we prove our non-noobness? But I don't think it should be required to make the all the others. And I meant realistically how long does it take? But I guess I was remembering wrong, I thought it was LV with a time of like, a year or two.

**Comment by GTNH-Colen** [comment]
> I guess that's the eternal singularity on the left then, they look similar with the textures bugged out.
> 
> So does the NAN icon using quest require making it then? If not, we should have one for it, how else will we prove our non-noobness? But I don't think it should be required to complete the others. And I meant realistically how long does it take? But I guess I was remembering wrong, I thought it was LV with a time of like, a year or two.

Eternal needs the neutronium compressor so UHV wetwares iirc? UV at a minimum though due to parts, I based some of the ordering on how Kharax did things in his lets play as he had some of these as final goals on his clipboard. Creating 1 NaN certificate will unlock all the other quests here yes

**Comment by Prometheus0000** [comment]
Well, it's not like I've made any of these things or anything. Was the DHD craftable? I thought it wasn't?

**Comment by GTNH-Colen** [comment]
> Well, it's not like I've made any of these things or anything. Was the DHD craftable? I thought it wasn't?

It isn't, I just used it as an icon. The actual quest requires the power unit and OC stargate interface.

**Comment by Prometheus0000** [comment]
I remember the power unit might not have been craftable too, did that get fixed? There was some kind of SG block at least that had no recipe.

**Comment by chochem** [comment]
@Prometheus0000 RF power unit looks craftable. nanos+Stargate ring block +Rid.Large Capacitors+SC Coils + Naq Alloy. all doable in principle

@GTNH-Colen 
nice work!

If you are interested in some feedback:
while the symmetry looks good, wouldnt it be better to include more dependencies? namely the ridiculously large capacitor is needed for the power unit which is in turn need for the teleporter (if that is the thing on the bottom right?), or the eternal singularity is needed for the infinity chest.

of course I already mentioned that I dont see a place for the LESU in here. On the other hand, I think the new ultimate capacitor (for the lapotronic supercapacitor) should totally be included! Its currently based of the ultimate battery, but kekz is thinking about basing it of the really ultimate instead, as it has very high I/O.

some more interesting quests could be: a quest for either or all of Chaos guardian/chaotic shard/chaotic core. This then leads to a) chaotic capacitor bank (creative RF energy) and b) a quest for the draconic staff of power which is pretty good in its own right (leading to the sword of the cosmos).

the draconic armor/tools are pretty nice too and maybe deserving of their own quest, though the recipes are pretty boring, so I dont know about these. most DE recipes really need changing.

other interesting endgame items that are craftable are: energy bazooka III, enhanced charm of dislocation

**Comment by Prometheus0000** [comment]
Isn't there a quest for the chaos guardian already on the grind page? It says to kill the dragon again, but it's the chaos one I think.

**Comment by chochem** [comment]
ah sorry. not the chaos guardian in that case.

**Comment by Prometheus0000** [comment]
We can have quests on both tabs. Or move it. The grinding and legendary infinity tabs both seems kinda half-assed, maybe we should try to move some of them to here or other tabs.

**Comment by Regian24** [comment]
i think we should move the legendary infinity, tier x quests etc. to endgame goals.

**Comment by chochem** [comment]
For legendary infinity, it might be better to just move them to the witchery tab.

legendary quests& tier X are different. Well, they are very different from anything else we have. I dont think they would fit well into the endgame goals. Basically, colens plan was that the endgame goals tab unlocks after finishing the tier X questline and maybe after finishing a UV/UHV tab, once/if we have one.

At some point they should probably get a rework, as they were kind of a place holder for ZPM/UV/UHV tabs . But such a rework is a pretty big separate task. And imo, the draconic cores should not just be available with a simple crafting recipe. All the additional gates on bloodmagic/thaumcraft/rocket tier/etc are very fitting.

**Comment by Regian24** [comment]
what if we merge the tier x and legendary questlines into one quest line

**Comment by feliser** [comment]
Maybe a Radox Polymer quest would be cool and maybe a stargate core crystal quest but this looks really nice good work

**Comment by Prometheus0000** [comment]
It's the IC2 Stargate Power Unit that has no recipe. The Stargate Command quest requires the RF one, but the Anywhere, Anytime quest requires the Teleporter (GT) which uses this in the recipe, so is _not completable_. Maybe a recipe could be added until #6007 is done?

**Comment by Dream-Master** [comment]
rf and ic2 one are exchangeable

**Comment by Prometheus0000** [comment]
Not for crafting the teleporter
![image](https://user-images.githubusercontent.com/8517039/83602465-98e73280-a540-11ea-910a-43175cd3a2f6.png)
![image](https://user-images.githubusercontent.com/8517039/83602486-a13f6d80-a540-11ea-86d4-3f4cc1f26216.png)

**Comment by Dream-Master** [comment]
ah ok no you need to exchange block first but add it as a second recipe is a nice idea

**Comment by GTNH-Colen** [comment]
> Not for crafting the teleporter
> ![image](https://user-images.githubusercontent.com/8517039/83602465-98e73280-a540-11ea-910a-43175cd3a2f6.png)
> ![image](https://user-images.githubusercontent.com/8517039/83602486-a13f6d80-a540-11ea-86d4-3f4cc1f26216.png)
> Instead of adding a recipe for the IC2 power unit, you could also just allow either in the teleporter recipe.

Thanks for pointing this out Prometheus0000, it was in the back of my mind so that's why I made the other quest use the RF one but didn't realise that the teleporter used it as well.



> while the symmetry looks good, wouldnt it be better to include more dependencies? namely the ridiculously large capacitor is needed for the power unit which is in turn need for the teleporter (if that is the thing on the bottom right?), or the eternal singularity is needed for the infinity chest.
> 
> of course I already mentioned that I dont see a place for the LESU in here. On the other hand, I think the new ultimate capacitor (for the lapotronic supercapacitor) should totally be included! Its currently based of the ultimate battery, but kekz is thinking about basing it of the really ultimate instead, as it has very high I/O.
> 

More dependencies could be good, I wanted to make it quite open so people could feel free to tackle it and get an overview of endgame items as a whole. LSC I was conflicted on, didn't really want to add it along with the LSC (Perhaps the LSC UHV block could take its place as a quest?).

> some more interesting quests could be: a quest for ~either or all of Chaos guardian/chaotic shard/~ a chaotic core. This then leads to a) chaotic capacitor bank (creative RF energy) and b) a quest for the draconic staff of power which is pretty good in its own right (leading to the sword of the cosmos).
> 
> the draconic armor/tools are pretty nice too and maybe deserving of their own quest, though the recipes are pretty boring, so I dont know about these. most DE recipes really need changing.
> 

Chaotic capacitor for RF is a good one, didn't want to include draconic as I felt it was too low level for this tab. Recipes could probably use a rework they're not challenging at all just held back by users being unable to obtain cores after that atrocious quest line.

> other interesting endgame items that are craftable are: energy bazooka III, enhanced charm of dislocation
Unsure on the recipe of the energy bazooka III personally will need to load up my game and take a look sometime, enhanced charm I deliberately left off as I am still hoping to rework it so it will be a much more feasible goal under #6007

**Comment by Prometheus0000** [comment]
BTW I'm working on quests now, so don't change anything until I'm done. Also, the LSC probably should have quests next to the LESU.

**Comment by chochem** [comment]
regarding LSC ultimate capacitor: kekz was still reworking this over the last days. It now takes the components of the really ultimate battery (instead of just ultimate) because it can do very high I/O and he also wanted to add a recipe to upgrade the really ultimate battery directly into the ultimate capacitor. See discord github-discussions. In that case the quest should probably just be behind the really ultimate battery.

**Comment by Prometheus0000** [comment]
We should add a quest for a Radox Polymer Ingot.

**Comment by Regian24** [comment]
i wonder if that'll ever be useful
