### ISSUE TITLE
Throwing Knife Crashes Game when Striking Enemy

### ISSUE THREAD

**Issue by MadManMax213** [GTNewHorizons/GT-New-Horizons-Modpack#6173]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Not playing in Multiplayer
#
#### What did you try to do, and what did you expect to happen?
Throw a Flint Throwing Knife from my Left-Hand slots and hit a skeleton from about 15 blocks away. The knife should have hit the skeleton.
#
#### What happened instead? (Attach screenshots if needed)
My game froze momentarily and then closed. This has happened three times previously while striking different mobs (from what I can recall) but does not always happen.
![image](https://user-images.githubusercontent.com/66109697/83231137-023dfe80-a159-11ea-9cff-43a090fb5270.png)
This was the mob I was trying to hit when the game crashed. It's labeled as a normal Minecraft Skeleton when I look at it with Waila.
![image](https://user-images.githubusercontent.com/66109697/83231543-a162f600-a159-11ea-8e9f-11b2533a03d5.png)
This is the throwing knife I was using. Tinker's Construct Flint Throwing Knife. I've used it on other enemies with and without this problem occurring.
Upon re-opening the world, the skeleton had taken damage from the throwing knife.
#
#### What do you suggest instead/what changes do you propose?
I'm not exactly sure what would cause this aside from the mobs not having a correct reaction to getting hit by the ranged projectile and the game closing itself to prevent other problems. I have not yet tested using modded ranged weapons aside from the flint throwing knife to see if they have similar problems for me.

**Comment by Dream-Master** [comment]
@MadManMax213 
crash log ?
fml log?
