### ISSUE TITLE
Cataclytic Converters to improve dealing with pollution

### ISSUE THREAD

**Issue by SampsaxD** [GTNewHorizons/GT-New-Horizons-Modpack#6174]
With the smog change, pollution will become a bigger part of the game, but we currently lack adequate tools to combat generating pollution.

One idea I had was cataclytic converters as an "addon" for muffler hatches, which could work as follows:
A cataclytic converter (CC) can be placed directly adjacent to a muffler hatch, and counts as a casing for multiblocks.
A CC has two inventory slots, one for input, and one for output.
The input slot would accept catalyst metal foils, which get consumed after set amount of pollution negated. After it has used a foil, it has a small chance to give a tiny pile of Platinum Group Sludge dust. (The catalyst getting dirty and turning into a mush)
The different tier CCs would accept increasingly better foils and give increasingly better pollution reduction with these foils. Some rough numbers:

![image](https://user-images.githubusercontent.com/42840657/83270108-b038bf80-a1d0-11ea-99da-248c16b6efac.png)

The materials that are lower tier than the CC can be used, but do not provide any bonuses compared to using them in a appropriate-tier CC.

The converters shouldn't be too expensive to craft, but maybe have the tier specific Large Cell as a component, to represent the converter itself where the foils (catalyst mesh) is placed.

This adds a way to reduce pollution significantly, while being automatable but incurring a small, but noticeable resource use to combat it.

This would also only work for multiblocks, to encourage players to switch to multiblock generators to avoid pollution.

**Comment by Dream-Master** [comment]
The scrubbers are not useable before MV (turbine Blades use 100 eu/t) and it's costy because the low tiere turbine blades cut off so you need black steel or better.

**Comment by draknyte1** [comment]
This has already been discussed and changes to accommodate will be implemented. So, they’re still viable.

**Comment by Regian24** [comment]
platinum at hv?

**Comment by botn365** [comment]
platinum is doable in HV

**Comment by Regian24** [comment]
yup, I'm doing it right now. its just very very hard

**Comment by leagris** [comment]
Instead of adding the catalytic converter as another block tile and the nightmare to make structures work with it. Why not have that as a right-click installable upgrade to the muffler block? Or even use the existing muffler upgrade.

**Comment by draknyte1** [comment]
You need the tier of conveyor the scrubber is to enable automation, there's two low tier turbines for LV as well.

Scrubbers are now viable early game.

![image](https://user-images.githubusercontent.com/3060479/83303632-4c74bd80-a1f5-11ea-8954-f596938da5aa.png)
![image](https://user-images.githubusercontent.com/3060479/83303637-526a9e80-a1f5-11ea-8f33-b0a219a95fad.png)

As suggested by Sampsa here: https://github.com/alkcorp/GTplusplus/issues/701 I'll just adjust my Advanced Mufflers to be Catalytic Converters.

Pollution now made even more negligible by AlkGang.

**Comment by Dream-Master** [comment]
we need also a filter between T1 and T2. T1 is used up so quickly.

**Comment by draknyte1** [comment]
T1 is just carbon.. you can just make more of them from literally wood 😂

**Comment by Dream-Master** [comment]
@draknyte1 the turbines still not working and i guess the wont forever?
