### ISSUE TITLE
Server crash on latest Final Beta

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#6175]
#### Which modpack version are you using?
GTNH-Server-1.7.10-2.0.9.0-beta4-final-fix
#
#### If in multiplayer; On which server does this happen? 
My private instance
#
#### What did you try to do, and what did you expect to happen?
Start the server
#
#### What happened instead? (Attach screenshots if needed)
The server crashes on startup
[crash-2020-05-29_18.38.06-server](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4703051/crash-2020-05-29_18.38.06-server.txt)

#
#### What do you suggest instead/what changes do you propose?
Fix it so that the server can be launched.

**Comment by Ethryan** [comment]
[fml-server-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4703201/fml-server-3.log) <-- With Thermos

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4703204/fml-server-latest.log) <-- With Forge
[crash-2020-05-29_19.08.30-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4703205/crash-2020-05-29_19.08.30-server.txt) <-- Error for Forge

**Comment by Ethryan** [comment]
Server works, with a lot of effort.

**Comment by JackMeds** [comment]
What did you do to fix the server?
I have the same problem in 2.0.9.0QF2.

**Comment by Dream-Master** [comment]
@Ethryan

**Comment by Ethryan** [comment]
Try extracting the .tar file in the server config directory. that might fix this problem.
