### ISSUE TITLE
[IO] spam client console

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6176]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
### IO spam client console
https://pastebin.com/fNc4Dv2Z

**Comment by Dream-Master** [comment]
@Zoko061602 is this fixed with the newest version?

**Comment by MotiasF33** [comment]
> 
> 
> @Zoko061602 is this fixed with the newest version?

looks like this issue
https://github.com/SleepyTrousers/EnderIO/issues/1412

**Comment by boubou19** [comment]
Does not seem to happen anymore in 2.1.0.0. Feel free to reopen it if it is still an issue.
