### ISSUE TITLE
Make ender singularity use a different block

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#6177]
#### Which modpack version are you using?
2.0.9.0 Beta 4
#
This should be changed really, the current block needed can only be made in a smeltery which imo is really dumb.

<img width="350" alt="Screenshot 2020-05-29 at 21 33 23" src="https://user-images.githubusercontent.com/54497873/83302909-0bc87480-a1f4-11ea-91c9-ca1d07bf04a3.png">

<img width="348" alt="Screenshot 2020-05-29 at 21 33 51" src="https://user-images.githubusercontent.com/54497873/83302943-18e56380-a1f4-11ea-9244-0d294406ca28.png">
Change it to use the "Block of Enderpearl"

**Comment by Regian24** [comment]
Colen, it's a throwback to the stone age when you needed to use a casting basin to make the blocks. Imho it's kinda a fitting end to the pack /s

**Comment by Dream-Master** [comment]
Why not add an recipe in the fluid solidified ?

**Comment by GTNH-Colen** [comment]
> Why not add an recipe in the fluid solidified ?

That also works but I feel like using the other block makes more sense, nearly every other block is just compressed normally. Either way is good though tbh and an improvement nonetheless.

**Comment by Alexdoru** [comment]
I would love to see it changed, fluid solidifier recipe or compressor. Compressor would make more sense since the block of enderpearls from gregtech already exists.

**Comment by Dream-Master** [comment]
yea will change that asap

**Comment by MotiasF33** [comment]
@Prometheus0000 , can add to 2.0.9.1 tasks? 😽

**Comment by Prometheus0000** [comment]
It looks like the line https://github.com/GTNewHorizons/Universal-Singularities/blob/94164d518936eee32499118ecd3b48f729b8576f/src/main/java/wealthyturtle/uiesingularities/proxy/CommonProxy.java#L176
Would need to be changed and moved to about https://github.com/GTNewHorizons/Universal-Singularities/blob/94164d518936eee32499118ecd3b48f729b8576f/src/main/java/wealthyturtle/uiesingularities/proxy/CommonProxy.java#L87

You'd probably have to change the 'blockEnder' to whatever the oredict tag of the other one is. And then build it. Don't make a PR without testing it.
