### ISSUE TITLE
Data Bank recipe should work with all LuV circuits

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6178]
#### Which modpack version are you using?
2.0.9.0 beta3
#
#### 

The Data Bank (from tectech) assembly line recipe requires 2 LuV circuits. However, currently only the Nanoprocessor Mainframe is allowed. It does not work with Master Quantumcomputers. (literally just swapping out the circuits makes the recipe start)

In pretty much ever other recipe in the pack circuits of the same tier are interchangeable.

Suggested change: Also allow other LuV circuits like the Master Quantumcomputer.

**Comment by boubou19** [comment]
still in 2.0.9.0 QF4
