### ISSUE TITLE
NEI - Some circuit recipes are wrong

### ISSUE THREAD

**Issue by urso90** [GTNewHorizons/GT-New-Horizons-Modpack#6182]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Craft CrystalProcessor, CrystalProcessor Assembly, Ultimate Crystal Computer
#
#### What happened instead? (Attach screenshots if needed)
I see recipes with incorrect number of items
Crystal Processor:
http://prntscr.com/sqzkzw
Should be:
https://prnt.sc/sqzisz

CrystalProcessor Assembly:
http://prntscr.com/sqzlal
Should be:
https://prnt.sc/sqziqi

Ultimate CrystalCopmuter:
http://prntscr.com/sqzlg5
Should be:
https://prnt.sc/sqziiv

I see the same problem is with crystal processor Mainframe.
Problem exists **ONLY IN NEI** - actual crafting takes correct number of items.
#
#### What do you suggest instead/what changes do you propose?
There was already a ticket for that: #5209 
But it was closed. In above ticket numbers were even higher, even if in code numbers are ok. Maybe this is some local file corruption?

**Comment by 0lafe** [comment]
The singleblock assembler values are intended to make you use the circuit assembler

**Comment by Prometheus0000** [comment]
Did you even read the other ticket? Any circuits that use LuV+ voltage use 6x components (excluding circuits used in crafting it) up to max stack size.

For the reason Olafe said.

**Comment by urso90** [comment]
But there is another recipe in NEI specificly for circuit assdembly line, which im not talking about. Im just saying NEI says it need more then it actually uses in circuit assembling machine. So either NEI is wrong or circuig assembling machine uses wrong number of items

**Comment by Prometheus0000** [comment]
I'll check with the beta4 when I get it set up, it might be fixed already.

**Comment by GeicowithaBango** [comment]
Thats an old bug, nei showing more material then actually needed. It occurred with the circuit assembling change that old recipe were still used because they were buffered. If epsilon updates the issue will be gone.

**Comment by Prometheus0000** [comment]
This is what the recipe for crystalprocessor in the singleblock is now, and it uses the correct amount of materials:
![Untitled](https://user-images.githubusercontent.com/8517039/83347496-5e3c8a80-a2f3-11ea-88a9-e83d5950b3cf.png)

**Comment by GeicowithaBango** [comment]
urso is not referrring to the overall higher cost in the single block. Its about nei showing the recipe with 6x circuit board cost, however, the machine consuming just the old recipe cost.

**Comment by Prometheus0000** [comment]
The machine shows and consumes 6 circuit boards though?
![image](https://user-images.githubusercontent.com/8517039/83347675-85e02280-a2f4-11ea-8a5f-f4a95eaa737d.png)

**Comment by GeicowithaBango** [comment]
thats ofc the intended behavior. don’t forget that epsilon is probably on a very old version

**Comment by Prometheus0000** [comment]
I really wish we had a 'that was fixed ages ago, update your sh*t' label. Though that wouldn't help the people on the servers I guess.

Dream will update the servers once the cell bug is fixed, so you'll just have to suffer until then.
