### ISSUE TITLE
Replicator times wrong in NEI

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6184]
#### Which modpack version are you using?
2.0.9.0 beta3
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### 

Example: Indium dust.
NEI: 2918.40 secs
scanner/actual: 7500 sec or more precisely 150016 ticks

Pictures from 9.0 beta3:

This is probably due to the recent changes to uum and replicators though I do not know the old times.
![2020-05-31_18 09 42](https://user-images.githubusercontent.com/40274384/83358331-b498e000-a36a-11ea-9c3e-7817255700b8.png)
![2020-05-31_18 07 59](https://user-images.githubusercontent.com/40274384/83358334-b793d080-a36a-11ea-93a5-a3ce0d277d33.png)

I found some help on discord to find the old recipe pre-nerf, and it looked like this:
https://cdn.discordapp.com/attachments/181078474394566657/716701090422194318/unknown.png

meaning NEI still shows the old recipe that no longer applies

Edit: This might be completely obvious, but here was alks first analysis on discord:
![image](https://user-images.githubusercontent.com/40274384/83358651-d85d2580-a36c-11ea-8abf-69930bc41664.png)

**Comment by boubou19** [comment]
is it still an issue in 2.1.0.0?

**Comment by Glease** [comment]
Already fixed via GTNewHorizons/GT5-Unofficial@3a59a69ff4e4161b1040859420eea414d48b78e4.
