### ISSUE TITLE
Suggestion: More lootbags

### ISSUE THREAD

**Issue by Regian24** [GTNewHorizons/GT-New-Horizons-Modpack#6185]
Now that LuV/ZPM/UV and Endgame quests are gonna be added, I think we should post our ideas for the new lootbags.
Currently the Tier 8 ZPM, Tier 9 UV and Tier 10 UHV lootbags are just vanilla stuff. I don't think it's a good idea to get stuff like apples and cobblestone in the higher tier lootbags.
I don't think endgame quests should have the lootbags, I think they should get special rewards (Like a medal for completing the stargate? Idk)

**Comment by Dream-Master** [comment]
@Regian24 feel free to add some loot tables

**Comment by Regian24** [comment]
dream i haven't got to zpm yet

**Comment by 0lafe** [comment]
We probably wouldn't want to use lootbags for that. If they're just cool items to own from completing lategame tasks, maybe we just give them as items? Something like the DE core quest maybe?

**Comment by Regian24** [comment]
I meant for the tier 8 and tier 9 tabs. Not the endgame goals.

**Comment by 0lafe** [comment]
LuV+ so doesn't need anything like a loot bag or craftable item rewards tho. Most of these quests aren't even for player info, and giving more rewards just weirdly makes the initial time you craft some of these items give you a bonus. Lootbags and quest rewards just don't really fit into lategame very well. 

I'd suggest either not giving these quests rewards at all, or doing something cosmetic like the unique legendary x items. The player really doesn't need free quest items translated to zpm+ lol

**Comment by Prometheus0000** [comment]
As a somewhat related issue, could we stop giving people coins at some point? They're annoying to set, and I doubt people use them past HV for most things.

**Comment by Dream-Master** [comment]
maybe it's time to put more inside to sell. A second coins coins tab is needed for hv+ items

**Comment by Prometheus0000** [comment]
Should we really be encouraging people to use coins instead of making things themselves? Although it depends on what it is of course. Basic items like blood runes or T1 slates are probably fine for BM for example, but buying the sacrificial runes or T5 slates would be weird. And can't we just expand the current tab if we have to add more stuff to it? Doesn't it have lots of space? Personally I'd say to move the lootbag trading up quests to this tab instead of making more tabs. Or is there a limit to quest numbers or size?

**Comment by Dream-Master** [comment]
as you know from the past I won't sell op items more ingredients and part for items. Yes we can stay on one page. No limitation I know of

**Comment by Prometheus0000** [comment]
It should probably be it's own issue in any case.
