### ISSUE TITLE
Handpump quest is available before EBF

### ISSUE THREAD

**Issue by Nvidiot** [GTNewHorizons/GT-New-Horizons-Modpack#6188]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
I tried completing the handpump quest (Plunger 2.0 The Hand Pump) in the LV tab.
#
#### What happened instead? (Attach screenshots if needed)
This quest (and item) requires 8 Aluminium Bolt. That is something which is not attainable without having the EBF. However, this quest unlocks way before you unlock the EBF quest. When watching a playthrough of an older version of GT:NH, it seems like the recipe has changed to now include Aluminium bolts.
#
#### What do you suggest instead/what changes do you propose?
Either lock this quest behind the EBF quest, or change the recipe to allow you to create this hand pump before the EBF. It'd be nice to not have to void all that glue from your assembler every time, but be able to store it in the ULV tank instead, without messing around with pipes, pumps etc.

**Comment by Prometheus0000** [comment]
I didn't make the EBF a requirement, simply mentioned it, because you can easily get Aluminium from chests.
