### ISSUE TITLE
Fix Scanner Info for Plasma Turbine

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6190]
#### Which modpack version are you using?
9.0 beta3 (but this bug has been around a long time)
#
####

when scanning a plasma turbine it shows an optimal flow, like
![image](https://user-images.githubusercontent.com/40274384/83428208-e2912980-a429-11ea-9aa8-a1c6245e10d1.png)
for americium plasma with a small trinium rotor.

This info is wrong and always has been from what I can tell. It has to be seconds, not ticks. I have seen quite a few people confused by this.

Its easy to fix: replace L/t by L/s.

**Comment by Elisis** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/541
