### ISSUE TITLE
gt drilling rig breaks commands.

### ISSUE THREAD

**Issue by AlastarDArk** [GTNewHorizons/GT-New-Horizons-Modpack#6192]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?

#I wanted to teleport or teleport the player to me.
#### What happened instead? (Attach screenshots if needed)
Instead, a null error appeared in the chat
My friend and I recorded a video
Video from my face
https://drive.google.com/file/d/1K5WEISjWxxnOK4NwmTv-nSKJQCTboIRU/view?usp=sharing
Video on behalf of a friend
https://drive.google.com/drive/folders/1IQU8hVKsZI9fq1jRL3j4QY5v9NtsZ34P?usp=sharing
This is due to all the commands aimed at the owner of the rig, but sometimes commands work if you spam them in the chat.
In the video on my behalf, it can be seen that command worked, but after the estimated time, I did not teleport.
Teleportation commands do not work well with the rig owner
#

**Comment by boubou19** [comment]
yeah known bug: every chunkloading GT machine will do the same

**Comment by GTNH-Colen** [comment]
Yea sadly as boubou says this is known and has been reported a myriad of times. Unfortunately no fix seems to be on the horizon. (See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5004)
