### ISSUE TITLE
liquid duplication bug with railcraft multiblock tanks

### ISSUE THREAD

**Issue by telugu-boy** [GTNewHorizons/GT-New-Horizons-Modpack#6196]
#### Which modpack version are you using?
2.0.8.9 dev 4

process:
get 2 or more of a universal cell filled with liquid
right click railcraft multiblock tank with cells
no change will happen to cells, but the tank will fill

**Comment by Prometheus0000** [comment]
Are you in creative? That happens in creative. Also, a duping bug with the RC tanks was fixed earlier today, you need the GT-PlusPlus-1.7.05.68.jar to get the fix, but I'm not sure I can just hand it out. Also, I'm not experiencing this with the updated jar, so it's almost certainly the same thing, and fixed.

**Comment by telugu-boy** [comment]
this happens in survival.

**Comment by Prometheus0000** [comment]
Then you'll need to wait for a newer version to test.

**Comment by draknyte1** [comment]
If you have a link handy @Prometheus0000 feel free.

**Comment by Prometheus0000** [comment]
[GT-PlusPlus-1.7.05.68.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4722094/GT-PlusPlus-1.7.05.68.zip)

**Comment by tripulse** [comment]
'-'
