### ISSUE TITLE
Letter Recipe only accepts Forestry Wood Pulp

### ISSUE THREAD

**Issue by wspk** [GTNewHorizons/GT-New-Horizons-Modpack#6197]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Private server.
#
#### What did you try to do, and what did you expect to happen?
Tried to use 6 Wood Pulp + Water -> Letter Recipe in a Forestry Carpenter using Gregtech Wood Pulp. I checked that the Carpenter has power, and was able to use other recipes using the carpenter.
#
#### What happened instead? (Attach screenshots if needed)
The recipe does not seem to accept Gregtech wood pulp, and this seems to be confirmed by NEI.
#
#### What do you suggest instead/what changes do you propose?
Allow the recipe to use the ore dictionary to accept either wood pulp.

**Comment by Dream-Master** [comment]
need to be oredict. will check

**Comment by shawnbyday** [comment]
Can assign to me and I will look at.
