### ISSUE TITLE
extreme lag induced by conveyors

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6198]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I was putting an UV conveyor on a Huge bedrockium pipe, without doing anything else (pipe not linked to anything). The compressed chest on the side of the conveyor is full. I expected it to not spam the cpu-load
#
#### What happened instead? (Attach screenshots if needed)
here is the cpu load recorded:
when the conveyor is in export mode:
![2020-06-03_14 05 31](https://user-images.githubusercontent.com/12850933/83634896-9e299900-a5a3-11ea-9e8c-8a5b8cdfddd9.png)

when the conveyor is in import mode:
![2020-06-03_14 05 04](https://user-images.githubusercontent.com/12850933/83634939-ad104b80-a5a3-11ea-9b90-70ec4ed10993.png)

when the conveyor is in export mode on a free side:
![2020-06-03_14 13 37](https://user-images.githubusercontent.com/12850933/83635429-7f77d200-a5a4-11ea-9e3d-020fc619aeca.png)

when the conveyor is in import mode on a free side:
![2020-06-03_14 13 48](https://user-images.githubusercontent.com/12850933/83635483-98808300-a5a4-11ea-8317-1ee5ca1a4b14.png)

the conveyors from IV to UV induce the same lags, but the lag decrease when using lower conveyors:
ev conveyor in export mode:
![2020-06-03_14 16 14](https://user-images.githubusercontent.com/12850933/83635608-d2518980-a5a4-11ea-90da-278e96d5228f.png)
ev conveyor in import mode:
![2020-06-03_14 16 22](https://user-images.githubusercontent.com/12850933/83635628-daa9c480-a5a4-11ea-9fa0-2a4a9d6fee5e.png)
hv conveyor in export mode:
![2020-06-03_14 17 24](https://user-images.githubusercontent.com/12850933/83635728-02009180-a5a5-11ea-9a82-c1fc0808465a.png)
hv conveyor in import mode:
![2020-06-03_14 17 37](https://user-images.githubusercontent.com/12850933/83635747-075ddc00-a5a5-11ea-8e9b-44083e4195c8.png)

Also there is only this pipe, no other pipes attached to it.
why is it generating so much cpu-load?

**Comment by moller21** [comment]
Think the higher tier pipes run every tick.

The bedrockium pipe has like 500 slots, the chest 250? So every tick it checks if it can move an item like 125000 times. Not great. That's why at least.

**Comment by interestingusernam3** [comment]
>The bedrockium pipe has like 500 slots, the chest 250? So every tick it checks if it can move an item like 125000 times. Not great. That's partly why at least.

If pipe code really works like that, someone should make a mod that changes it because this is absolutely horrible.

**Comment by boubou19** [comment]
![2020-09-22_20 37 29](https://user-images.githubusercontent.com/12850933/93923429-a739a400-fd13-11ea-8131-8591d61f37e9.png)
it's fixed in the 2.0.9.1 dev pack
