### ISSUE TITLE
SSP Block Lag ?

### ISSUE THREAD

**Issue by mightydanp** [GTNewHorizons/GT-New-Horizons-Modpack#6201]
#### Which modpack version are you using?
Latest
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
mine block and sometimes the game will freeze and the block will return.
#
#### What happened instead? (Attach screenshots if needed)
block gets mined then re-appears
#
#### What do you suggest instead/what changes do you propose?
If theres a fix for this tell me how to fix it :) I have a high end computer and get over 200 fps. not even using shaders

**Comment by Dream-Master** [comment]
lastest = rc1 ?

**Comment by mightydanp** [comment]
Latest = 2.0.8.3 also hello dream-master

**Comment by Dream-Master** [comment]
retest with 2.0.9.0 when it is out.

**Comment by mightydanp** [comment]
Is there a beta build of thos version ?

**Comment by Prometheus0000** [comment]
You could grab the RC1 from the announcements channel in discord. And 2.0.8.3 isn't even close to being the latest.

**Comment by mightydanp** [comment]
I just updated same issue

**Comment by Dream-Master** [comment]
to rc1 ? @mightydanp

**Comment by mightydanp** [comment]
Yes even on rc1 its very irritating

**Comment by Dream-Master** [comment]
@mightydanp i need your full mod list fml log.
Are you use additional mods that not in the pack ?
How much ram you gave mc ?
Java version ?

**Comment by GTNH-Afx237v7** [comment]
In my experience this happens when there are too many entities, regardless of high end computer. As Dream said, more info will be helpful.

**Comment by Prometheus0000** [comment]
It also sounds like what happens when a mp server and client desyncs (like the stars changing position back to what they were a second before). And I assume your TPS is good as well as your FPS?

**Comment by mightydanp** [comment]
My fps and tps are good ill upload my logs folder asap

**Comment by mightydanp** [comment]
i am giving it 9 gb

**Comment by Prometheus0000** [comment]
Is this still happening?

**Comment by mightydanp** [comment]
It happens unless when i dont have my jmv saying to add more cores to my jmv to use. But then that would mean that a person who has a lesser pc wouldnt be able to handle the pack and would have to deal with the block lag
