### ISSUE TITLE
RC2 actually unplayable

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6203]
#### Which modpack version are you using?
2.0.9.0 RC2
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### 

Already discussed on discord but I figured it is better to have a thread here to make it easier to find/see.

RC2 is actually unplayable for may people.

After 30 seconds in the game I had all of 5 rendered chunks, many missing textures, and like 10 fps. After a minute or so it finally found the textures and got up to 9 (3x3) rendered chunks and 15 fps. Even after 3-5 minutes my game was not able to render more than 9 chunks, only the fps went up a bit.

These problems instantly disappear if one switches to gamemode 1.

several people reported the same or very similar behaviour on discord. Video by Lucy: https://cdn.discordapp.com/attachments/603348502637969419/718101977958973501/E3YeYr4CA2.mp4

Edit: I should add, this also happens at low or 0 pollution.

Edit2: specs are not too great (3 year old laptop) but I never had any problems before.
i7-6700HQ, 2.6GHz
GTX 970M

**Comment by shitstainlord** [comment]
Balanced

**Comment by Dream-Master** [comment]
@chochem fog will be removed untill we get a full sollution for srubbing it away or have some mufflers T2.
