### ISSUE TITLE
Ore drill getting stuck inside the Twilight Forest

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#6204]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I set up a drill in the Twilight Forest to dig up graphite and TC shards
#
#### What happened instead? (Attach screenshots if needed)
The drill stopped progress after two chunks. It did keep running, using fluid and power but did not produce any output. Rebuilding did not resume progress, using the screwdriver also did not convince it to continue closer by.

On second observation I noticed that it intersected an old Hydra lair and that it stopped partway in.

#
#### What do you suggest instead/what changes do you propose?
The ore drill should not get stuck and progress past technical obstacles if those arise.

**Comment by repo-alt** [comment]
Looks like it met a block that it couldn't break

**Comment by Prometheus0000** [comment]
Did you ever figure this out?

**Comment by repo-alt** [comment]
It is probably Thermos doing unnatural things with the fake player again. May test in SSP in the hydra layer with radius 1 w/o Thermos
