### ISSUE TITLE
Endgame ultimate battery quest is wrong

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6205]
#### Which modpack version are you using?
2.0.9.0 RC1
#
In the Endgame quest tab both quests for ultimate battery and really ultimate battery require a really ultimate battery

**Comment by GTNH-Colen** [comment]
This is intentional, one is full and the other is empty. There is no quest for a normal ultimate battery, only the ultimate one.

**Comment by botn365** [comment]
does the quest state that with microwave transmitors you can by pass the amps limit

**Comment by Prometheus0000** [comment]
Shouldn't quests be actually completable? Maybe it should be replaced with the Ultimate Capacitor (UHV) like someone suggested be added.

And no, it just says to fill it. How long would it take doing that with the microwave transmitors? If it's still more than a year, we should change it.

**Comment by botn365** [comment]
sinse microwave transmitors can by pass the amp limit they can teoreticly do it in 1 tick

**Comment by chochem** [comment]
> 
> 
> does the quest state that with microwave transmitors you can by pass the amps limit

that sounds more like a bug that should be fixed.



> 
> 
> sinse microwave transmitors can by pass the amp limit they can teoreticly do it in 1 tick

that energy still needs to come from somewhere.
