### ISSUE TITLE
Kinetic Generators only output one full amp, no matter what

### ISSUE THREAD

**Issue by SampsaxD** [GTNewHorizons/GT-New-Horizons-Modpack#6206]
All Kinetic Generators (HV to ZPM) should output a full amp from every connected side, but after the reactor fix, they only ever output (1 / Connected Sides) voltage amps from each side:

1 Side:
![image](https://user-images.githubusercontent.com/42840657/83828190-bf47d200-a6e8-11ea-8657-5d4a2a0e49f0.png)
2 Sides:
![image](https://user-images.githubusercontent.com/42840657/83828245-ddadcd80-a6e8-11ea-8a2c-741abf67c982.png)
3 Sides:
![image](https://user-images.githubusercontent.com/42840657/83828277-f0c09d80-a6e8-11ea-8c4e-d0ee0d7f0f6a.png)
4 Sides:
![image](https://user-images.githubusercontent.com/42840657/83828311-003fe680-a6e9-11ea-873c-83617118f5c6.png)
5 Sides:
![image](https://user-images.githubusercontent.com/42840657/83828343-10f05c80-a6e9-11ea-9a37-40097922672e.png)

**Comment by dvdmandt** [comment]
Just discovered this one myself ingame. The logic seems very weird here. If a generator can generate (fill its internal buffer) at 2A+, it should be able to output 2A+ IMHO. I have a wind turbine setup, medium wind kinetic -> medium kinetic (like Sampsa in the pictures). At the moment, it uses strong winds to build up its rather big energy buffer, and then constantly output exactly 1A IV, even when there's no wind at all. I think it would make more sense to remove/shrink its internal buffer and have it output as much as can be accepted instead, forcing the user to deal with the energy buffering/smoothing instead.

**Comment by Prometheus0000** [comment]
Presumably generating more than 1A is also a bug, or to make sure it can always output 1A, right from startup? Or to account in height variances if these do that?

**Comment by dvdmandt** [comment]
I'm pretty sure it was intentional at the time, but we may have better rotors making it a more obvious issue and possibly a balance issue. I think it was always intended to generate variable amounts, forcing the issue smoothing/buffering upon the user to have stable power, but several issues have stacked up and made them a bit ridiculous.

If nothing else, the GUI and quests should be fixed, because this is confusing when the actual output is 8192.

![image](https://user-images.githubusercontent.com/11985732/92527509-69268580-f227-11ea-82a3-fa165d140e33.png)

**Comment by Prometheus0000** [comment]
Personally, I don't think a X tier singleblock gen should put out multiple amps. And I don't think we have permission to edit the code, so it needs to ASM'd, but Alk isn't doing any dev work recently, and they're the person who knows the most about ASM.

**Comment by dvdmandt** [comment]
What I want is to make it average 1A, but with high fluctuations. Like the lightning rods (which can output 512A), but not as extreme.

**Comment by dvdmandt** [comment]
The lack of explicit license for the mod is indeed an issue though. Is that the case with IC2 as well?

**Comment by Prometheus0000** [comment]
ER, I dunno? I think we have to ASM IC2. I thought we didn't even have a fork of this one, until I looked just now. I wonder why we have it if we can't edit it? Just to have a copy of the code? Regardless, nothing's likely to happen for a while at least.

**Comment by dvdmandt** [comment]
Note that I'm potentially willing to make the code changes, but the permissions are a bit of a problem. Currently trying to figure out where the change that caused the current behavior was implemented and see if I can figure out what's going on.

**Comment by Cleista** [comment]
The tiered EMT solars already output multiple amps so I don't think it's much of a consistency issue to change how kinetic gens work? Might burn some cables if people weren't careful but shouldn't cause any explosions as long as the max EU/t doesn't change.

**Comment by draknyte1** [comment]
IC2 has no concept of Amps. 
IC2 is closed source ARR. Distributing any unofficial builds would have the devs take legal action. (Player literally obfuscates FastCraft and takes his IP very seriously)

**Comment by Cleista** [comment]
Aren't the higher tier kinetic gens from an addon? If addons are subject to the same licensing issues, GTNH shouldn't have been able to modify EMT solars to output multiple A of GT power, and yet here we are.

**Comment by draknyte1** [comment]
EMT has an open license. 
IC2 and the kinetics mod do not. 

Bart just jammed GT Compat into EMT solars and iirc has/had issues.

**Comment by Cleista** [comment]
Well, that's unfortunate. @PinkaLulan hadn't been active for months now so probably not likely we'd be able to get a license added to the the kinetics mod's repo.

**Comment by Dream-Master** [comment]
i dont get any answer since month.
