### ISSUE TITLE
Industrial coke oven not working properly.

### ISSUE THREAD

**Issue by Alsarus** [GTNewHorizons/GT-New-Horizons-Modpack#6207]
#### Which modpack version are you using?
GTNH 2090 RC2
#
#### If in multiplayer; On which server does this happen? 
mp (my local server)
#
#### What did you try to do, and what did you expect to happen?
Coke oven after a few cycles of work (tested on wood tar and coal tar) is crushed and dont work. Output hatch and bus is empty.
#
#### What happened instead? (Attach screenshots if needed)
Here video: https://yadi.sk/i/ZLte9mQinyZaZQ
#
#### What do you suggest instead/what changes do you propose?
fix this bug.

**Comment by botn365** [comment]
that looks like a polution problem

**Comment by Prometheus0000** [comment]
Specifically, is there a muffler? Also, that's a GT++ machine.

**Comment by Alsarus** [comment]
http://puu.sh/FT2JF/73e75c07e9.jpg muffler does not work in structure

**Comment by botn365** [comment]
trie puting the muffler somwhere else like yhe bottem layer

**Comment by Prometheus0000** [comment]
The Industrial Coke Oven tooltip says you need one

**Comment by Alsarus** [comment]
yep. muffler work in bottom layer. I think it need change description in industrial coke oven(1x muffler hatch(bottom layer))

**Comment by Prometheus0000** [comment]
Go to https://github.com/alkcorp/GTplusplus/issues and make an issue there.

**Comment by Prometheus0000** [comment]
https://github.com/alkcorp/GTplusplus/issues/715
