### ISSUE TITLE
T8 rocket uncraftable (again)

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6208]
#### Which modpack version are you using?
2.0.9.0 RC1
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
- Heavy duty plates T8 needs 8M eu/t in the assembly line
- using more than 2 energy hatches is buggy and unreliable, 8 should not work (according to bot, test in edit below)
- that means the player needs 2 UHV energy hatches
- those need UHV superconducting cables
- those need you to smelt UHV SC Base ingots in the EBF (or equivalent) at 10800 heat.
- fluxed electrum coils give only 9900K plus 700K bonus at UHV= 10600 so insufficient
- that means the player needs awakened draconium coils
- awakened draconium is only available as ore (needs T8 rocket) or with draconic cores in the DE ritual (needs T8 rocket)
- hence the player needs a T8 rocket.

#
#### Possible Solutions:
Any of:
- reduce heat requirement of UHV SC Base ingots
- reduce the Heavy duty plates T8 voltage requirement to 2M eu/t
- add a small amount of awakened draconium small ore to a T7 planet
- change the recipe of the UHV energy hatch (might also need a change to the transformer recipe which also needs a UHV superconducting wire)

#
#### Edit1 - Test:
Tested the assembly line with 8 uv hatches. The multiblock forms and the scanner says:
![image](https://user-images.githubusercontent.com/40274384/83927338-80fff080-a784-11ea-83be-4c6d1f9b4181.png)
But the recipe fails instantly. My power supply is not the problem, as switching to two UHV energy hatches and a UHV high voltage transformer lets the recipe run. (all three cheated in) 

#
#### Edit2 - Temporary Workaround
Found by bot. The mark III fusion reactor has UHV Superconductor Wire as a choice reward. Obviously this is not a proper solution.

**Comment by chochem** [comment]
updated with test and temporary workaround.

**Comment by Regian24** [comment]
> add a small amount of awakened draconium small ore to a T7 planet
I like this one.

**Comment by 0lafe** [comment]
we could make coils rely on a better item than a pure ore, or finally give D* any level of interesting proc chain as well and their that better. Besides being T8 locked it's not a very interesting material

**Comment by chochem** [comment]
this issue should just get a quick and easy fix. A proper material rework is for some other time.

**Comment by Prometheus0000** [comment]
A quick fix is preferable in the short term, so people can progress without quest rewards, which should not be necessary. 

BTW did you want me to add them to another quest? Or just add a note to take them if they don't want to get stuck?

**Comment by chochem** [comment]
you mean the temporary workaround? no, dont do anything there, a fix of the actual issue shouldn't be too hard. this is just info for anybody having this issue and trying to find a possible solution (outside of cheating in sp or asking an admin in mp).

**Comment by 0lafe** [comment]
Could swap coils to Nt for 10800k

**Comment by 0lafe** [comment]
UHC SC in mk3 fusion reward also seems wrong. Seems like old SC that never changed with additions of UV-. We should probably change that to UV

**Comment by Prometheus0000** [comment]
I'll change it making the UHV ones gets fixed.

**Comment by Prometheus0000** [comment]
Confirmed you can make the base ingots with the fluxed coils and uv hatch.

**Comment by Dream-Master** [comment]
so the change are useless ?

**Comment by Prometheus0000** [comment]
I mean I confirmed the fix works
