### ISSUE TITLE
Forestry tileworker patterns messed up

### ISSUE THREAD

**Issue by Josh5minus1** [GTNewHorizons/GT-New-Horizons-Modpack#6210]
#### Which modpack version are you using?
2.0.9.0 RC1
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
![Tileworker_2 1](https://user-images.githubusercontent.com/54713920/83935998-9c551500-a7f1-11ea-8762-bb37b1b8574c.png)
(Old versions of binnie mods and forestry)
#
#### What happened instead? (Attach screenshots if needed)
![Tileworker 1](https://user-images.githubusercontent.com/54713920/83936005-a414b980-a7f1-11ea-9836-fd7e1dd5a326.png)
(Newer versions of those mods)
#
#### What do you suggest instead/what changes do you propose?
Fix the tileworker bug

**Comment by Dream-Master** [comment]
@Josh5minus1 (Old versions of binnie mods and forestry) ?can you list wich version works and which not.
Thanks

**Comment by Josh5minus1** [comment]
@Dream-Master 
Fine versions:
Binnie mods 1.7.10-2.0.23
Forestry 4.2.20.0

Bugged versions:
Binnie mods gtnh 2.0.29.4
Forestry 4 2.27.12
