### ISSUE TITLE
Internal Server Error, Blocking damage over time.

### ISSUE THREAD

**Issue by wspk** [GTNewHorizons/GT-New-Horizons-Modpack#6211]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Private server.
#
#### What did you try to do, and what did you expect to happen?
Unexpected crash "Internal Server Error". Has happened 5 or so times, perhaps when I block (heater shield + cutlass) while poisoned? 
#
#### What happened instead? (Attach screenshots if needed)
I get kicked from the server. Server console is attached 
[console.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4739733/console.txt)

#

**Comment by wspk** [comment]
Specifically: Get poisoned, kill infernal mob that poisoned me, block in case there are other mobs around, crash.

**Comment by DSLM** [comment]
Same thing happened at 2.0.9.0QF4.
I get the poison from mob, block with cutlass(Tinker's Construct) and the iron shield(Mine & Blade), then the game crashes.
[crash-2020-10-28_21.31.17-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5455627/crash-2020-10-28_21.31.17-server.txt)

**Comment by DSLM** [comment]
Fixed in 2.1.0.0.
