### ISSUE TITLE
Ore Finding Wand Detect Ardite Ore in Weird Way

### ISSUE THREAD

**Issue by noobnoobnub** [GTNewHorizons/GT-New-Horizons-Modpack#6214]
#### Which modpack version are you using?
2.0.8.9
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Expect it beep
![image](https://user-images.githubusercontent.com/50437615/83973159-221eb080-a917-11ea-876b-5d04df7b521a.png)

#
#### What happened instead? (Attach screenshots if needed)
It doesn't beep for this ore

For a random 5x5 block i walk in and detected
no ardite ore in vincinity
b beep x not beep

layer 1
xbxxx
xbxxx
xbxxx
xbxxx
bbxxx

layer 2
xbxxx
bbbbb
bbbbb
bbxxx
bbbbb

#

**Comment by Prometheus0000** [comment]
There probably isn't enough of it for that. And there won't be, since they're found 1-3 at a time at most.

**Comment by Dream-Master** [comment]
so far ik the wand is desinged for GT ores
