### ISSUE TITLE
LUV OreScanner shown small ores displaced

### ISSUE THREAD

**Issue by flockenobsidian** [GTNewHorizons/GT-New-Horizons-Modpack#6218]
#### Which modpack version are you using
2090RC2
#
#### If in multiplayer; On which server does this happen? 
zeta
#
#### What did you try to do, and what did you expect to happen?
searching for small ore amethyst in twighlight
#
#### What happened instead? (Attach screenshots if needed)
![2020-06-08_14 51 44](https://user-images.githubusercontent.com/41200844/84038234-fb588c80-a99f-11ea-927f-4140af1797ea.png)
![2020-06-08_14 51 46](https://user-images.githubusercontent.com/41200844/84038244-fe537d00-a99f-11ea-9c8b-67ebfbe2d349.png)
ore appeared to the wrong the position:  on block above(north) and one to the left(west)

**Comment by Prometheus0000** [comment]
Does this only apply to TF? Only small ore?

**Comment by Prometheus0000** [comment]
@mitchej123 Did you fix this when you modified the scanner? If not, could you?

**Comment by repo-alt** [comment]
someone used division instead of bit shift to get chunk coordinates (again)?

**Comment by mitchej123** [comment]
I didn't see any issue with the code when I modified it.  I also didn't look very hard.

**Comment by Skiftcha** [comment]
https://github.com/GTNewHorizons/DetravScannerMod/blob/master/src/main/java/com/detrav/gui/textures/DetravMapTexture.java#L37-L38
?

**Comment by Skiftcha** [comment]
https://github.com/GTNewHorizons/DetravScannerMod/commit/5182c1cb77fe3d7c26a7ddbbc9b9e0de5115d9d2#diff-cbdabf486fd265ec6f90fc9685e6b9c7ade5d6f9be2d9311792b830a1383646fR131
> fixed offset

**Comment by Prometheus0000** [comment]
> looks like intentional change

So does that mean it's bugged on purpose, or...?
