### ISSUE TITLE
Thaumcraft Wand is not detected in BQ on 2.0.9.0

### ISSUE THREAD

**Issue by noobnoobnub** [GTNewHorizons/GT-New-Horizons-Modpack#6219]
#### Which modpack version are you using?
2.0.9.0 QF2
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/50437615/84056336-ab51e800-a9e8-11ea-896d-c345adb58a24.png)
![image](https://user-images.githubusercontent.com/50437615/84056343-af7e0580-a9e8-11ea-9ada-a14c61d422bd.png)

#

**Comment by Prometheus0000** [comment]
Tested in RC2, it works fine, even without running it through the name remover. I don't think thaumcraft was changed inbetween, but go back to RC2 and see if there's a difference.

**Comment by chochem** [comment]
From past experience: This should be a damage value issue, not NBT. Because that value is used to distinguish wands here. His wand is :30. what does the quest want?

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/84057329-824c3b80-a985-11ea-8009-5d594cee0f71.png)

**Comment by noobnoobnub** [comment]
I just crafted one from the recipe on RC2. Not using cheat mode to get a wand.
So maybe the recipe is screwed up like other wands? I don't know

**Comment by Prometheus0000** [comment]
recipe
![image](https://user-images.githubusercontent.com/8517039/84569955-2a804c80-ad58-11ea-9e9e-dca1d7d98dff.png)
/mt hand
![image](https://user-images.githubusercontent.com/8517039/84569943-1b010380-ad58-11ea-9498-93806b7973fd.png)
Works for me on QF4. Are you in mp? did you try sp?

**Comment by Mondfaust** [comment]
Hey Devs, Mond here
Did this Quest on the testserver today "20.6.2020" patch 2.0.9.0QF4

The quest did not update with the craftet wand
![wandcrafted](https://user-images.githubusercontent.com/67201828/85208050-ad437180-b32d-11ea-8c1d-a7cb4dec34ae.png)
![wandforquest](https://user-images.githubusercontent.com/67201828/85208062-b9c7ca00-b32d-11ea-819e-e2031a21f36c.png)

what i see is the ending number is different from the quest wands number.

its /30 on the crafteted and /9 on the requirered wand 

Greetings Mond

**Comment by Dream-Master** [comment]
The Quest was made before we put all recipes in code. Guess thats why

**Comment by Prometheus0000** [comment]
If you look back at https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6219#issuecomment-640742840, you'll see that it requests metadata 30, not 9 when I checked. And it didn't require aspects either. Did someone change it since then?

**Comment by chochem** [comment]
@Prometheus0000 yes, this has changed in the past as I pointed out. I assume that :9 wand was crafted in 8.3 or so. compare https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5808#issuecomment-609426441

**Comment by Prometheus0000** [comment]
@Mondfaust in what version did you craft your wand? And why does your quest have aspects on it? It's not set like that, did you reload the quest database properly after updating? By testeserver do you mean Zeta? Maybe Zeta's quest database wasn't reloaded properly? I have no idea how one does that in MP though.

@chochem I meant changed what the recipe output since I checked 13 days ago.

I checked _again_ in QF4, NEI recipe :30, in the table, :30, actual output :30, quest requirement :30. And it doesn't require any aspects in the wand. There's a possibility it changes in MP or for other people, but I would think there would be more people complaining if that was the case? Maybe some other people could comment as to what the metadata is for their recipe through NEI?

**Comment by Mondfaust** [comment]
@Prometheus0000  yes by Testserver i meant zeta, sorry for that
and it was on the actual version so QF4

to be more clear there are 2 Quests one is 
![wand1](https://user-images.githubusercontent.com/67201828/85267295-5fd21c00-b475-11ea-84a4-aa69f856e5ec.png) 
this one is Novice Thaumaturge and worked fine
then there is this quest in adept thaumaturgy
![wand2](https://user-images.githubusercontent.com/67201828/85267506-a58ee480-b475-11ea-95cb-83988c82e918.png)
which is here
![wand2-1](https://user-images.githubusercontent.com/67201828/85267529-ad4e8900-b475-11ea-8687-faec7a98ddc4.png)
and that quest did not accept the wand

**Comment by Prometheus0000** [comment]
This is why people need to be more specific about names of quests and the numbers too. I thought there was only 1 GBGW quest, I didn't even look at that one. Now that I know that I can probably fix it, I'll see if I can take a look soon.

**Comment by Mondfaust** [comment]
im sorry, next time i do better !

**Comment by Cleista** [comment]
Still broken on 2.0.9.0QF4. 

Furthermore "Magical "Staffter"" (Quest No. 1191) ingredient detection also broken. 

[Crafting result](https://cdn.discordapp.com/attachments/234936569360809996/730497797320867970/unknown.png), [quest requirement](https://cdn.discordapp.com/attachments/234936569360809996/730497836382158919/unknown.png)

**Comment by PedroG98** [comment]
Having the same problem in server epsilon with "Adept Thaumaturgy" quest. Crafting a new wand doesn't solve the issue either.

Considering that wand quests tend to be buggy, that there's already a quest asking to craft a gold banded wand and that what's needed to unlock Adept Thaumaturgy is a simple checkbox quest, wouldn't it make sense to simply remove this quest/replace it with a checkbox?

**Comment by Prometheus0000** [comment]
It's also there to detect the condition to unlock the tab, otherwise it would be available before the first TC tab (I think). We can have duplicate quests across tabs (maybe we couldn't way back when it was created), so making it a duplicate would be an option, but I can't remember if there's unique text in it. Plus it's not that hard to fix, I just haven't been able to get to it.

**Comment by PedroG98** [comment]
It broke again D:

Quest 877 "Scepter with 75 vis capacity" doesn't recognize item being held or crafted.
Playing on official server epsilon.

**Comment by Prometheus0000** [comment]
That's a different quest, isn't it? First, check if the repo quest file fixes it in SP (it's got more fixes in it, but I don't think I fixed this one), and if not, make a new ticket.
