### ISSUE TITLE
Recipe Question/Change?

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#6223]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
For the EnderIO Photovoltaic Cell recipes the Tier 1 cell requires energetic alloy plates and vibrant alloy plates. The Tier 2 cell requires vibrant alloy plates and pulsating iron plates.

It seems like the Tier 1 cell should be energetic alloy plates and pulsating iron plates?

**Comment by shawnbyday** [comment]
![image](https://user-images.githubusercontent.com/33701188/84067377-f5a57b80-a98c-11ea-9f2c-35bc672ebfa1.png)

![image](https://user-images.githubusercontent.com/33701188/84067393-fb9b5c80-a98c-11ea-9dbf-fb3eab6a6eb9.png)

**Comment by Dream-Master** [comment]
i think i did it because of the color but i check the recipe

**Comment by Dream-Master** [comment]
both have vibrant alloy so i choose it for the color
