### ISSUE TITLE
BW Circuit Programmer can delete circuits

### ISSUE THREAD

**Issue by Larsien973** [GTNewHorizons/GT-New-Horizons-Modpack#6226]
#### Which modpack version are you using?
2.0.9.0. RC1
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Move circuits into the circuit programmer via the numbered hotkeys, expected a single circuit to be moved.
#
#### What happened instead? (Attach screenshots if needed)
Instead the whole stack dissapeares , and only one moves to the programmers GUI.

Repro step:
1. Charged Circuit Porgrammer in hotbar slot 1, a stack of programmed circuits in slot 2
2. Open Programmer, move mouse over circuit slot, hit "2"
3. Stack moves, deleting all except one
#
#### What do you suggest instead/what changes do you propose?
Should propably be the same as "shift" clicking or dropping circuits in; only one gets deposited leaving the rest.

**Comment by Prometheus0000** [comment]
According to bart: anti-dupe-mechanic.
