### ISSUE TITLE
2.0.9.0 MAJOR space travel changes with ZERO DOCUMENTATION? WTF?!

### ISSUE THREAD

**Issue by dieselfuelonly** [GTNewHorizons/GT-New-Horizons-Modpack#6227]
What on God's green earth would possess ya'll to release 2.0.9.0 with all of these major changes to space travel with NOT ONE mention of what all has changed?

I go to fuel up my T2 rocket and can't even put diesel inside.

Okay, off to Discord:

Just to go to Mars now I need RP-1 rocket fuel.

Which needs a chem plant.

Which is a multiblock that requires other blocks which aren't mentioned in the tooltip on the multiblock itself.

No mention of what manual is required to make just to figure out.

Finally get help finding out what manual I need to make, oh great that's not just a small change, that's one expensive multiblock to make now just to go to Mars.

That's fine if it's supposed to be difficult to hard.  Not documenting any of this changes and just throwing the RELEASE out there to everyone with the attitude of GOOD LUCK EVERYONE ELSE is unacceptable.  Not even a quest book update... lmao.  Pathetic.

**Comment by chochem** [comment]
If want to know about changes pre-update, you should wait until the changelog comes out. that is literally the documentation.

A few of us, mostly Prometheus, (not the nominal devs) are working on that quest book update but it wasn't finished for 9.0, sorry. you still got lots of new quests btw.

**Comment by draknyte1** [comment]
The manual is literally called “Chemical Plant Manual” 🤦🏻‍♀️

**Comment by Prometheus0000** [comment]
It should list on each rocket quest  (aside from the first, which mentions it on the rocket fuel quest) which fuel you need. I'm not sure if that made it in 9.0 or not, but I don't think so.

And I haven't updated the CP quest yet.

**Comment by dieselfuelonly** [comment]
> 
> 
> If want to know about changes pre-update, you should wait until the changelog comes out. that is literally the documentation.
> 
> A few of us, mostly Prometheus, (not the nominal devs) are working on that quest book update but it wasn't finished for 9.0, sorry. you still got lots of new quests btw.

So what is the new player supposed to do downloading this pack, start by reading the changelog?  Obviously I'm not new to this but imagine my confusion when suddenly the rocket won't take the fuel that I've always used.  Galacticraft is buggy and the documentation is shoddy to begin with, let alone a heavily modified version like this pack uses.  The questbook is pretty much necessary to guide the player through, why on earth would a release be put out without it updated?

**Comment by Prometheus0000** [comment]
Listen, I understand your complaints, but people have been wanting this update for quite some time, so it was maybe a little rushed, and some things didn't make it in. If you look at https://github.com/GTNewHorizons/Galacticraft/pull/4#issuecomment-633132159 you'll see that I had the same concerns, and I'm even going out of my way to update the questbook not just for myself, but for everyone else as well. And if I hadn't caught it, you would've had to use RP-1 for T1, but that originally required _Tungstensteel Casings_. Before the moon. Be thankful we avoided _that_ mess.

**Comment by mitchej123** [comment]
@dieselfuelonly Please keep things constructive.

**Comment by Regian24** [comment]
username checks out xD
