### ISSUE TITLE
2.0.9.0 Quest issue list

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6228]
A generalized post for a list of quest issue that occur in the latest 2.0.9 QF2.

- [x] Chickens my boy. the future is in chickens quest reward is wrong(Fixed in New-Quest branch)

- Work in Progress

- [x] Outline for future LuV-UV quests #6161

- [x] Text addition suggestion to Chemical Plant quest #5483

If you have similar quest issue on the 2.0.9.0QF2, please put them down below.

###########################
Added by the admins:
###########################
- Use the experimental quests on the New-Quests branch before complaining.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/tree/New-Quests/config/betterquesting (grab the DefaultQuests.json and replace the one on your computer and use the default load command)

- If there's still a problem you can report it. If it's _about_ the new quests, report in #6161.

- Large Chickens and their eggs have been removed in favor of using Sterilized Growth Medium to make them, as Dream deemed them far too easy. If you still have some, you might or might not be able to still use them. Cheater.

- Rocket Fuels changes are already noted in the updated version on the 'craft the rocket' and rocket fuel quests.

- The CP quest needs to be updated, but I need permission from Dream first, since I was told not to update quests since it seemed for a while that we might have to go back to an older version of GT++.

- The CP has a book, use it.

- 2 of the CP casings have no recipe, known oversight.

- The 2 low tier turbines for scrubbers don't work, also known.

- Pollution Fog is not in until it's fixed.

- GT++ multis are getting nerfed **HARD**, soon. Look forward to it, with less breaking of stuff.

**Comment by Prometheus0000** [comment]
> Even the default quests have edit mode enabled.

? Do you mean edit mode was left enabled? Turn it off for now, I guess. I try to remember to turn it off, maybe I forgot?

>  Chickens my boy. the future is in chickens quest reward is wrong.

The eggs are now uncraftable, so I removed the quest.

Also, please wait to complain about quests until I'm actually done doing them if you don't want to grab the updated ones from the branch.

**Comment by yukieiji** [comment]
> ? Do you mean edit mode was left enabled? Turn it off for now, I guess. I try to remember to turn it off, maybe I forgot?

I was mistaken, as the edit mode was still active when I reloaded the quests.

**Comment by Prometheus0000** [comment]
If you want to grab the latest version of the questfile from the branch, you can comment about it in the issue specifically for it #6161

**Comment by yukieiji** [comment]
Why does it need to be closed?
I think it would be easier to understand if you reported the 2.0.9.0QF quest bug here.

**Comment by Prometheus0000** [comment]
Because I'm actively working on the quests (though I'm going to sleep for the day soon), and I don't want to keep track of two separate issues. And the chicken thing and CP thing are already things I know about. And I'm the only one who's been doing quest stuff since RC2 and now, so it'd be about my quests anyway (probably).

**Comment by draknyte1** [comment]
Diesel cannot be used at all. 
It’s now cetane for T1.

**Comment by Prometheus0000** [comment]
I know that? Why are you mentioning it here?

**Comment by yukieiji** [comment]
There may be quest bug that have not been discovered by RC2, 2.0.9.0QF2 It's only been released for a day and it would be premature to close it.

**Comment by Prometheus0000** [comment]
Fine, whatever, I'll add some text telling people to use the experimental quest version first.

**Comment by Regian24** [comment]
> New-Quest Brunch
I'm hungry
