### ISSUE TITLE
The Big Egg's recipe for dragon eggs doesn't exist.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6229]
#### Which modpack version are you using?
2.0.9.0QF2
#
#### What happened instead? (Attach screenshots if needed)
The Big Egg's recipe for dragon eggs doesn't exist.
#
#### What do you suggest instead/what changes do you propose?
I think Dream made the mistake of removing the recipe for Giant Chicken Eggs when he deleted that recipe.
If it was deliberately removed, then you need to remove the quest related to making a dragon egg.

**Comment by Prometheus0000** [comment]
Also in RC2. He probably just made a mistake.
![image](https://user-images.githubusercontent.com/8517039/84130042-c0db0800-aa10-11ea-90cb-1a1a5db58717.png)
This is the egg missing a recipe.

![image](https://user-images.githubusercontent.com/8517039/84130104-d3edd800-aa10-11ea-8c72-ebd11d12d75c.png)
This is the GT++ one you disabled.

**Comment by Dream-Master** [comment]
Yes disabled it by mistake
