### ISSUE TITLE
Nitric Acid name wrong as a fluid

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6231]
#### Which modpack version are you using?
RC2
#
When it's a fluid, and not in a cell, it's called NitricAcid, not Nitric Acid.
#
#### What do you suggest instead/what changes do you propose?
Add the space to the name.

**Comment by Dream-Master** [comment]
Not sure how to change it

**Comment by Dream-Master** [comment]
seems to be have a material and a fluid

**Comment by shawnbyday** [comment]
@Dream-Master fixed in dev?

**Comment by Dream-Master** [comment]
Yes should be.
