### ISSUE TITLE
Quests are not giving the correct sound on completion again

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6234]
#### Which modpack version are you using?
2.0.9.0 RC2
#
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6161#issuecomment-640856835
 https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6161#issuecomment-640890196
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6161#issuecomment-640903749
 #5078
 #5342

#
#### What do you suggest instead/what changes do you propose?
This is apparently wrong on all the quests I did recently (The LuV+ changes/additions), so there's a good chance some kind of default setting is wrong somewhere in BQ3.

**Comment by Prometheus0000** [comment]
Funwayguy ain't gonna fix it, so if someone feels like it go ahead.

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/BetterQuesting/pull/6 doesn't seem to be working completely, as quest 2815-2818 still uses the wrong sound, while 2814 and 2819 use the right one, even though I made them all in the same session, and not that long ago.

**Comment by Dream-Master** [comment]
so we need to observe this when doing new quests
