### ISSUE TITLE
ME Interface voids the items that were pushed inside by Item Conduit

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#6235]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
I have an ME Interface with LCR recipe patterns. When LCR produces a recipe result, item conduit takes the result from output hatch/bus, and moves into ME Interface top slot.
![image](https://user-images.githubusercontent.com/4941736/84315778-d5371600-ab72-11ea-8afa-bf7e5e93eee7.png)
In the beginning when I started the game, everything works fine and the item that was pushed to ME Interface goes to the ME Network and Network completes the recipe.
But at certain point of time, that ME Interface starts to Void the items. Items just disappear, they don't appear in ME Network and recipe Hangs forever with green "crafting", waiting for the output which was voided.
For example like this
![image](https://user-images.githubusercontent.com/4941736/84315993-116a7680-ab73-11ea-9948-8fde7402cad2.png)

When the recipe was stuck, I had requested the recipe once again, and I have watched LCR. I saw LCR giving the output, then output would be moved by Item Conduit to the ME Interface and disappear forever.
When I restart the game and repeat the same recipe, it works 100% correct.

This voiding thing has eaten about 600 of my 800 volumetric flasks.

**Comment by repo-alt** [comment]
And everything is safely chunkloaded I assume?

**Comment by repo-alt** [comment]
Are you still using 8.3? maybe you can try to reproduce that in the newer version?
