### ISSUE TITLE
Cannot breed Clay bees

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#6237]
GTNH 2.0.8.9 SP

After around 90 attempts of cross breeding industrious and diligent bees in an alveary, with clay blocks beneath, with 6 soul frames and ender eyes in the mutator not a single mutation. Am I doing something wrong or is the mutation rate so abysmal that bees may as well be removed?

**Comment by chochem** [comment]
can you check your forestry mod version, to see if it is the same issue as here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5816

**Comment by redmage17** [comment]
> 
> 
> can you check your forestry mod version, to see if it is the same issue as here: #5816

It is the same version let me see if the roll back fixes it

**Comment by redmage17** [comment]
Rolling back to the prior version of forestry fixed it
