### ISSUE TITLE
Multiblock controllers do not run structure check after initial placement

### ISSUE THREAD

**Issue by SampsaxD** [GTNewHorizons/GT-New-Horizons-Modpack#6241]
2.0.9.0 QF3

All GT Multiblocks fail to do structure checks after initial placement.
![image](https://user-images.githubusercontent.com/42840657/84387067-16730880-abfb-11ea-9102-8519b7a92923.png)

Caused by [this commit](https://github.com/GTNewHorizons/GT5-Unofficial/commit/8b93a2909d7285f6506a56889929039c41882845).

**Comment by Prometheus0000** [comment]
At least you can make them look different now.

**Comment by Prometheus0000** [comment]
If I recall this is due to bart borking some stuff in the oddest way, and is no longer applicable
