### ISSUE TITLE
The server crashed at startup - 2.0.9.0QF3

### ISSUE THREAD

**Issue by JackMeds** [GTNewHorizons/GT-New-Horizons-Modpack#6243]
#### Which modpack version are you using?
2.0.9.0QF3
#
#### If in multiplayer; On which server does this happen? 
At startup
#
#### What did you try to do, and what did you expect to happen?
start new server file
#
#### What happened instead? (Attach screenshots if needed)
crashed   
#
crash report
 https://paste.ubuntu.com/p/53TKzyqqzx/
#
The log when the crash occurred 
https://paste.ubuntu.com/p/cDY5YY9rQH/
#
#### What do you suggest instead/what changes do you propose?
I try to delete Gambiarras_BQThermosFix.jar, the server starts successfully

At the same time, I found that the version of WailaHarvestability-mc1.7.10-1.1.6 is old when comparing the files（client is WailaHarvestability-mc1.7.10-1.1.7-GTNH）

**Comment by JackMeds** [comment]
Wait a second，When the bake is done，crashed  
https://paste.ubuntu.com/p/hvrKKsWbfj/

**Comment by JackMeds** [comment]
> Wait a second，When the bake is done，crashed
> https://paste.ubuntu.com/p/hvrKKsWbfj/

Repair method：config\MyPermissions\MyPermissions.cfg
Change "S:permissionSystem=$Bukkit" to "S:permissionSystem=$ForgeEssentials"

**Comment by JackMeds** [comment]
> > Wait a second，When the bake is done，crashed
> > https://paste.ubuntu.com/p/hvrKKsWbfj/
> 
> Repair method：config\MyPermissions\MyPermissions.cfg
> Change "S:permissionSystem=$Bukkit" to "S:permissionSystem=$ForgeEssentials"

I don’t know the purpose of your setting, I can be sure that such changes will affect the server using bukkit

**Comment by Dream-Master** [comment]
If you dont know how setup a Thermos server plaese setup a forge server.

**Comment by JackMeds** [comment]
> If you dont know how setup a Thermos server plaese setup a forge server.

I’m not sure if Thermos is stable, and your server files seem to be neither start on Thermos nor on forge

**Comment by JackMeds** [comment]
> If you dont know how setup a Thermos server plaese setup a forge server.

Can you tell me that your server files are good for Thermos?
Can you write this in readme or wiki?

**Comment by JackMeds** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6175#issuecomment-642558206

fixed, thx
