### ISSUE TITLE
2.0.9.0 QF3 breaks existing AE2 autocrafting patterns involving motors

### ISSUE THREAD

**Issue by SampsaxD** [GTNewHorizons/GT-New-Horizons-Modpack#6246]
https://i.imgur.com/iU3lXBg.gifv

Only seems to affect motors, maybe their NBT data changed, causing it to break?

**Comment by Dream-Master** [comment]
are you sure it is a ae2 bug ?

**Comment by Prometheus0000** [comment]
No, it sound like it's an nbt thing.

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/84427313-ba0beb00-abf2-11ea-888d-451d81ce9f66.png)
New motor crafted in QF3 with copper and only iron rods /mag rod

**Comment by bartimaeusnek** [comment]
thats the registry name fix i made

**Comment by SampsaxD** [comment]
well thanks :c

**Comment by GTNH-Colen** [comment]
What do we actually gain from "fixing" this, all I can see is that 100s if not 1000s of peoples AE recipes will be completely broken after the update. From the user perspective this seems like a massive hit for no real gain? It could be really important, I'm just kinda curious why this had to be done now?

**Comment by Prometheus0000** [comment]
The quests for imprints/sliced circuits work correctly on other worlds/computers. And yeah, that isn't really worth it.

**Comment by draknyte1** [comment]
> I'm just kinda curious why this had to be done now?

It was easier to patch vanilla than for Bart to fix his own code and avoid the issue.

**Comment by nom457** [comment]
2.0.9.0QF4 All recipes of motors, pistons etc broke. Re-encode patterns?

**Comment by chochem** [comment]
Thats a lot of recipes to re-encode for a lot of players. There must be a better solution to this.
