### ISSUE TITLE
 Server Crashing

### ISSUE THREAD

**Issue by JasonArgo6** [GTNewHorizons/GT-New-Horizons-Modpack#6247]
#### Which modpack version are you using?
Latest Version of the modpack

I am trying to run the GTNewHorizons server for my friend and I, and I am getting this error:

Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION
.Loading cannot continue 

[ERROR] [FML]:
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
[ERROR]Caught exception from ResourceLoader
[ERROR]Caught exception from CustomMainMenu
[ERROR]Caught exception from defaultworldgenerator
[ERROR]Caught exception from reauth
[ERROR]Encountered an unexpected exception

**Comment by mitchej123** [comment]
we need the actual stacktrace and/or log.

**Comment by JasonArgo6** [comment]
you mean the saved server crash information, or the console info?

**Comment by JasonArgo6** [comment]
[crash-2020-06-11_12.54.43-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4767026/crash-2020-06-11_12.54.43-server.txt)
