### ISSUE TITLE
Everfull Urn replaces pump/gt tools when rightclicked

### ISSUE THREAD

**Issue by liripoop** [GTNewHorizons/GT-New-Horizons-Modpack#6249]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
I rightclicked an everfull urn with a pump. As this is not a gregtech block nothing should happen.
#
#### What happened instead? (Attach screenshots if needed)
The pump got replaced with gt.metaitem.01.0.name .If you rightclick the jar with a tool like a crowbar or wrench they get replaced by a sword.
#
#### What do you suggest instead/what changes do you propose?
Remove the unintuitive/buggy behaviour.
![sword](https://user-images.githubusercontent.com/43907060/84491420-cea8bb80-aca4-11ea-81b2-fc404e662f75.jpg)
![metaitem](https://user-images.githubusercontent.com/43907060/84491422-cf415200-aca4-11ea-9cd4-b244672d8c28.jpg)

**Comment by boubou19** [comment]
known issue: #5453, #1442
