### ISSUE TITLE
Changes&Additions to the Endgame Tab

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6250]
A first draft of the endgame tab is now in the game. Thanks to Colen for designing it, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6172! So Prometheus asked me to make an issue to collect any proposed changes and additions. This goes from typos to major changes and new quests. I'll start with my own observations below.

Keep in mind that in the end its up to Colen, Prometheus, & the devs.

- Remove the UEV circuit from the circuit quest 'these exist?' as that one has its own quest in the UHV tab now.

- The quest for a filled really ultimate battery is just silly and should be removed. I am confident Colen did not do the maths. Just in terms of energy production, even if you have 10 mk3 fusion reactors running permanently just for filling the battery, giving you 150M eu/t with infinity turbines which would be a more powerful setup than anybody has ever done to my knowledge, then it would still take about 100 actual real life years to fill. (also discussed in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6205)

- Adding a quest for just the ultimate battery would be a good stepping stone to the really ultimate one

- The ultimate capacitor (kekztech) is now just a simple assembler recipe away from the really ultimate battery, so maybe not quite worth its own quest, but at least it should be mentioned in the quest for the really ultimate battery (extra quest is also fine of course)

- Also add a quest for the chaotic capacitor bank (infinite RF power). It would be a requirement for the Ridiculously Large Capacitor ('You'll Probably Need Quite a Few of These').

- The Stargate Radiation Containment Plate ('Building Block of the Stargate') should be another requirement for the Ridiculously Large Capacitor

- Eternal Singularity should be a requirement for the infinity chest.

- The Ridiculously Large Capacitor should be a requirement for the Stargate Command

- ~~Stargate Command should be a requirement for the Teleporter ('Anywhere, Anytime').*maybe check first that the recipe is fixed*~~ Remove Teleporter ('Anywhere, Anytime'). the recipe is broken&hopefully there will be larger teleportation rebalance soon.

- Add Xenoxene/radox quest. #5049 Needs an explanation once I actually do it as the culture recipe doesn't show in NEI. And then radox, and radox polymer. Probably the same quest, maybe not. (by Prometheus0000)

- Add Longbow of the Heavens (by Prometheus0000)

Possible New Quests for other Tabs that are creative-like or have a dire crafting table recipe:
- many DE items (tools, armor, weapons, charms, pedestal, portal, dislocator,...)
- steve carts: Upgrade: Integrated Infinity Reactor
- steve carts: Infinity Engine
- Six different creative OC parts
- Creative mode IC chip (would need an IC workbench quest with some explanations first, maybe postpone this one)
- Skullfire sword (also see #5732), recipe is HV

**Comment by Prometheus0000** [comment]
> Stargate Command should be a requirement for the Teleporter ('Anywhere, Anytime'). maybe check first that the recipe is fixed

It's definitely not. And about the requirement, for this and the Ridiculously Large Capacitor, he said before that he expects the teleportation stuff to change 'soon' so it will hopefully not rely on that for non-SG stuff.

- Xenoxene/radox quest. #5049 Needs an explanation once I actually do it as the culture recipe doesn't show in NEI. And then radox, and radox polymer. Probably the same quest, maybe not.

**Comment by GTNH-Colen** [comment]
> > Stargate Command should be a requirement for the Teleporter ('Anywhere, Anytime'). maybe check first that the recipe is fixed
> 
> It's definitely not. And about the requirement, for this and the Ridiculously Large Capacitor, he said before that he expects the teleportation stuff to change 'soon' so it will hopefully not rely on that for non-SG stuff.
> 
> * Xenoxene/radox quest. #5049 Needs an explanation once I actually do it as the culture recipe doesn't show in NEI. And then radox, and radox polymer. Probably the same quest, maybe not.

I won't be changing stargate recipes at all with teleporation rebalancing, just trying to pry the parts out of other recipes (Primarily thinking of the enhanced charm of dislocation here as that was something that I would've included otherwise).

I deliberately designed the tab to be over decentralised so people could get an overview of everything without being forced down a specific path first but I can understand the arguments here for wanting to gate things given that they're used in some of the other items recipes.

>The quest for a filled really ultimate battery is just silly and should be removed. I am confident Colen did not do the maths. Just in terms of energy production, even if you have 10 mk3 fusion reactors running permanently just for filling the battery, giving you 150M eu/t with infinity turbines which would be a more powerful setup than anybody has ever done to my knowledge, then it would still take about 100 actual real life years to fill. (also discussed in #6205)

This is a fair point, I am aware it would take obscene amounts of time to fill it but more made it as a "good luck" goal and gated nothing behind it for that reason. It's caused quite a lot of controversy so I am happy to remove it (Would only need 14,600,000,000 eu/t for a year to fill it guys, trivial... /s).

I don't really expect 99.999999% of the population to ever complete the stargate quests for example, it's why I added a quest for a single stargate radiation plate so there is a more realistic goal for most players. I kinda see the stargate quests as similar in that regard but guess the stargate would "only" take like a year to make.

Maybe in the far future when we develop higher tiers filling the ultimate battery will be possible but for now it can go. Most of the other points you mention seem fine, radox I didn't add as it just didn't come to mind when making them tbh but would be a nice addition.

**Comment by chochem** [comment]
Obviously a stargate is extremely hard to make too. I think the differences is, that I think it is quite possible that a dedicated group with a server running for a good while will complete the stargate quest eventually now that we have the void miners. The filled battery just seems out of reach mathematically.

For the dependencies: I only wrote down the ones that are actual recipe dependencies, so the player is not artificially restricted.

**Comment by Prometheus0000** [comment]
On that note, maybe a quest for the charm? Or maybe we need a draconic evolution tab or section somewhere? In LTX?

Hopefully we'll see more traction on the teleportation rebalance once things are less broken. But I think specific recipes might need to be suggested for each one for that to happen, and that's kind of a lot of work, and only high-level players really know what is and isn't difficult to make/achieve, and there isn't (I think?) a lot of them.

**Comment by Regian24** [comment]
Maybe a quest for the Ultimate Stew?

**Comment by Prometheus0000** [comment]
So, looking through the DCT list, there's:
Longbow of the heavens
Infinite oxygen supply
Upgrade: Integrated Infinity Reactor
Infinity Engine
Six different OC parts, probably more appropriate on the OC page
Creative mode IC chip (uses UHV circuits, but I don't know what it is)
Skullfire sword (should have a quest elsewhere for sure, also see #5732)

Maybe a quest for collecting the components of the hard recipe for the Infinity Catalyst? Though Colen also suggested maybe adjusting the recipe and making players use it for a bit.

**Comment by Regian24** [comment]
i could help make the rewards maybe?

**Comment by GTNH-Colen** [comment]
> Skullfire sword (should have a quest elsewhere for sure, also see #5732)

Why would this have a quest in the endgame tab? It's can be made in like IV if you wanted to?

**Comment by chochem** [comment]
I think it can be made in HV. and no it wont go on the endgame tab, I discussed Prometheus' list with him already and ordered it into my text on top.

**Comment by Prometheus0000** [comment]
> Skullfire sword (should have a quest elsewhere for sure, also see #5732)

I only wanted to mention it because it's a DCT item, I wasn't suggesting that it should have a quest on this tab.

**Comment by Josh5minus1** [comment]
Just an idea: For the If catalyst recipe, maybe tge adjusted xtreme recipe could be done for one time (getting the first If catalyst), removing its neutronium compressor recipe, then adding a recipe in a machine that basically, like: 64 If catalyst dust + 1 If catalyst (does not get consumed) = 1If catalyst. When you don't have at least an If catalyst, you have to do the xtreme recipe again.
