### ISSUE TITLE
Improving Legendary Quests and Tier X quest lines

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6251]
#### Which modpack version are you using?
9.0QF2
#
#### 

My goal here is not completely change the way these quest lines work, but just to propose some fixes and improvements to make it a bit smoother and consistent without changing the overall theme or balance. 

**Legendary Quests**

the main problem here is imo that some of the triggers are hard/impossible to figure out without peeking in creative or asking someone. So I would propose:

- *A Problem that matters*: the hole talk of stars/sun is pretty misleading. Also the picture is very misleading. I would put the main hint in here and make it a matter condenser. And then the description a bit shorter:
> I need to open a wormhole. But for that, I need an immense gravitational field. Somehow I need to compress matter to extreme density. But how?

- *It needs a power plug*
again the picture is very misleading here. I think a demon blood shard could work well. Then the text can stay the same.

- *A casing*:
the text is very clear this time. Still the picture is very unfitting. I would propose an Enceladus dungeon brick.

- *A few more things*: Ask for 2 Tier VI field gens instead of just Tier III.

**Legendar Tier X**

- *Successful.. Or not?*:
the player should be pointed towards Pluto, but that is absolutely not the case. keep in mind that you need a T8 rocket to get here, so Pluto is not the edge of space. I would propose to change the text too:
> (...) a small success.
You traveled to many planets and moons. Maybe you can find some new material. Some place dark, in the distant parts of our solar system.

- *Forcefield, second try*:
needs to be a bit more specific. I would suggest to change the end to:
> (...) There must be a way. This should be pretty similar to controlling dangerous nodes...

- *Weird creatures*:
this quest should be removed. the player already needed ectoplasma to get here.

- *thauminite trigger*:
this one makes no sense as the quest line wants ichorium. should be changed to ichorium trigger, triggered by one ingot of ichorium.

- If https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5157 gets implemented then it should be integrated into the end of the quest line. Namely, the player would get the schematics from the quests instead of a repeatable quest for cores.

disclaimer: I should mention that I dont know how made these quest lines orginally, so I hope this is fine with whoever did.

**Comment by Prometheus0000** [comment]
Do you not thing the field generator should be a higher tier?
![image](https://user-images.githubusercontent.com/8517039/84571593-29ecb380-ad62-11ea-8158-a0d169cff160.png)
2nd last LQ Q

**Comment by chochem** [comment]
yeah those are strangely low. should probably be Tier VI.

**Comment by Prometheus0000** [comment]
> Weird creatures:
this quest should be removed. the player already needed ectoplasma to get here.

![image](https://user-images.githubusercontent.com/8517039/84571959-daf44d80-ad64-11ea-88ab-e2980c7ca355.png)
I moved it around little instead. I space things out a little more while I was at it.

**Comment by Prometheus0000** [comment]
See also #4591. if there's nothing else, I think both can be considered done? The idea of mob farms should be discussed way earlier than this after all.
