### ISSUE TITLE
Server Error, compatibility with mods.

### ISSUE THREAD

**Issue by JasonArgo6** [GTNewHorizons/GT-New-Horizons-Modpack#6252]
#### Which modpack version are you using?
Newest Version
#
#### If in multiplayer; On which server does this happen? 
I am using Server.pro as a hosting service
#
#### What did you try to do, and what did you expect to happen?
Tried to load the server with all the mods and all the correct config files onto the server and start like we have in the past.

#
#### What happened instead? (Attach screenshots if needed)
it instead crashed, we asked our server provider if they knew what the issue was, and they said its a issue with these mods: 
- GalacticraftCore
- GalacticraftMars
- galacticgreg
- GalaxySpace
- ToxicEverglades
- Australia
- reauth
- ResourceLoader
- OpenBlocks
- miscutils
#
#### What do you suggest instead/what changes do you propose?
I am not sure if there are mods missing? Like dependencies or, missing files, wrong java version?
[crash-2020-06-12_08.59.00-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4771856/crash-2020-06-12_08.59.00-server.txt)

**Comment by mitchej123** [comment]
Do you have any non-standard mods included?

Are you running Thermos/kcauldron/bukkit?

**Comment by JasonArgo6** [comment]
No

**Comment by mitchej123** [comment]
Do you have openjdk 8 available?  I'm not sure OpenJ9 is supported.  I recall there being an issue with GT++ and OpenJ9...

```
Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Linux amd64-64-Bit Compressed References 20190417_286 (JIT enabled, AOT enabled)
```

**Comment by JasonArgo6** [comment]
Yea we dont have a openjdk 8 available it seems, only java 8 hotspot and openJ9
I wonder if I could somehow manually install a openjdk 8...

**Comment by mitchej123** [comment]
Try java8 hotspot instead of openj9

**Comment by JasonArgo6** [comment]
Still crashing

**Comment by JasonArgo6** [comment]
Should I paste the crash errors or txt file?

**Comment by mitchej123** [comment]
Is it the same error?

Check in discord #github-discussion and see if @Alkalus#9378 has a newer build of gt++ you could try.  I recall they might have been working on a fix for OpenJ9.  Otherwise search around in the discord for openj9 and see if anyone else had a workaround.

**Comment by JasonArgo6** [comment]
ok heading there now

**Comment by draknyte1** [comment]
It’s fixed In any RC release or 9.0 release.

**Comment by JasonArgo6** [comment]
sure ill try that

**Comment by Prometheus0000** [comment]
Don't use QF3 though, it's completely borked.

**Comment by JasonArgo6** [comment]
but wait im using a 9.0 version do you guys know exactly what versions i should try?

**Comment by JasonArgo6** [comment]
Also what is a RC release?

**Comment by chochem** [comment]
RC= release candidate. but more to the point, what version exactly are you running? *Newest Version* is not very specific.

**Comment by JasonArgo6** [comment]
we were running a quick fix now that I know so which one should we try downloading?

**Comment by Prometheus0000** [comment]
Honestly there were QF versions for a reason. I'd just wait for QF4 or whatever the next version is, or use RC2 and ask someone which file to change to not use the pollution stuff  (serious FPS problems).

**Comment by Dream-Master** [comment]
@JasonArgo6 newest version ? 2.0.9.0QF3 is newest version

**Comment by JasonArgo6** [comment]
thanks
