### ISSUE TITLE
Crash after leaving game open for a while

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6253]
#### Which modpack version are you using?
2.0.9.0 QF3
#
[crash-2020-06-12_12.11.39-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4772167/crash-2020-06-12_12.11.39-client.txt)

I went out for a bit, and came back to it having crashed.

**Comment by draknyte1** [comment]
You ran out of memory. 
In future, if it continues to occur, try use visualvm and see what’s eating all your memory.

**Comment by Prometheus0000** [comment]
It might be the Tectech stuff, since I've been testing that recently. I also noticed a couple times (on other days) long delays (2-5s) between doing something and it happening, like opening my inventory.
