### ISSUE TITLE
Wetware board crafting loop (pre-CAL) results in a net loss

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#6254]
2.0.8.8

Before having the CAL, using wetware processors to craft wetware processors results in a net loss!
24 wetware boards -> 4 wetware circuits -> 1 LuV sensor -> 16 wetware boards = **net loss 8 boards** per loop

Basically this recipe chain/loop gives less boards back than what you start with which is really bad.
The 6x board nerf put the crafting loop in the negative, so now it is literally just a resource sink if you use wetware circuits to craft themselves.

This really should be fixed to result in at least a small net gain, e.g.
12 wetware boards -> 4 wetware circuits -> 1 LuV sensor -> 16 wetware boards = **net gain 4** boards

(comparatively the CAL has a net gain of 12 boards per loop, so the CAL is still much better)

**Comment by chochem** [comment]
that sounds completely fine. you have two options:
- use a different LuV circuit,
- make a CAL,
preferably both.

**Comment by botn365** [comment]
non CAL recipe is only to make the first circuit so you can imprint the CAL not for there to production of luv+ voltage circuits

**Comment by DualBallers** [comment]
@botn365 Please reread the issue and don't close the issue early.

I have no problem with the nerf on the circuit assembler, but if you do not realise that the loop gives a net loss this way you are basically voiding resources!

**Comment by DualBallers** [comment]
Would you say it is good to have a recipe that takes 24 boards and outputs 16 boards?
Of course either you would change the recipe or remove it, because it makes no sense to have it.

**Comment by Prometheus0000** [comment]
Then you're stupid? Just make the CAL?

**Comment by draknyte1** [comment]
What Bot is saying is that the recipe is shit and isn't intended to be used for > 1 circuit.
Make a CAL or make different circuits. It's only purpose is to imprint and use for a CAL.

**Comment by DualBallers** [comment]
That is not the point. I know that you should "just" make the CAL. But the recipe loop is simply voiding resources.
On all other levels of circuit progression it is better/cheaper to use the most advanced circuit, but here it you have a loop that voids your resources.

How is is "not a bug" that recources are voided.

**Comment by DualBallers** [comment]
Now you're just throwing around labels - I understand you have had similar discussions on this nerf, but my point still stands:
Why it is good to have a net loss crafting loop? It really makes no sense.

**Comment by botn365** [comment]
it is not a bug becous the non CAL recipe only exists to imprint the CAL and stop circuit tier skipping
not to mass produce circuits and becous of that this is not a problem

**Comment by Prometheus0000** [comment]
They aren't 'voided' if you're using the intended recipe, or another LuV circuit.

**Comment by DualBallers** [comment]
@Prometheus0000 if you start with 24 boards and end with less, 16 boards, then you might as well have voided 8 boards. 
And if you don't realise that you need to use e.g. crystralprocessor assemblies (because you are conditioned to use the latest tech i.e. wetware processors) then you basically cannot progress because of the net loss.

**Comment by repo-alt** [comment]
You are aware that you need a template to use in a Circuit Assembly Line, right?

**Comment by Prometheus0000** [comment]
If you remove the recipe for the circuit, how would you make the imprint?

**Comment by Prometheus0000** [comment]
Also, what's counter-intuitive is not using the CAL at every turn.

**Comment by DualBallers** [comment]
OK, that's a fair point, of course the imprint is needed.

However, I still would like to hear your thoughts on the net loss issue.

@Prometheus0000 To get to the CAL you need a lot of LuV-tier circuits, and "of course" you want to make them the cheapest way - but what seems to be the best way (use latest tech/tier) actually voids your resources. How would you expect players to know this.

**Comment by draknyte1** [comment]
> However, I still would like to hear your thoughts on the net loss issue.

It’s intentional.

**Comment by DualBallers** [comment]
So far I have not encountered a net loss loop in this excellent pack, so to me this specific crafting loop jumps out as unintentionally bad design, as players are continually conditioned to use the latest available tech and circuit tiers.

**Comment by Prometheus0000** [comment]
It's not a net loss if you craft them using the imprints the second time.

The sheer idea that someone in ZPM/UV is so stupid that they can't figure it out (even after crafting some boards!) is mind-boggling. They shouldn't be playing GTNH, and should go back to vanilla with their 'sane' and 'normal' recipes.

**Comment by DualBallers** [comment]
This is issue is specifically minded at the pre-CAL stage, and how to get to the CAL.

The second paragraph is really uncalled for - if the pack teaches you to progress in a certain way up to LuV, then players should not be called stupid for expecting this to continue.

**Comment by Prometheus0000** [comment]
CAL is LuV, wetware is ZPM or UV if you actually want the new circuit.

Have you looked at the new quests? The handholding is gone ZPM+, you're expected to use NEI. Which wetwares are, minimum. Plus, this is just like the first aluminium dust voiding thing, expect to lose some if you don't pay attention.

**Comment by DualBallers** [comment]
Wetware processor is an LuV-tier circuit. 
I don't recall the 'first aluminium' stuff, as I haven't restarted in years, but maybe it's the same trickiness.
Using Technic so I can only look forward to the 2.0.9.0 update and your work on the quests.

I agree that the hand-holding should be progressively lessened as the tiers increase, however this specific net loss loop is just so out of place, that it could warrant a recipe change or mention in the quest book somewhere. 

Anyway, I'll not drag this more out as it's clearly not getting traction :-)

**Comment by GTNH-Colen** [comment]
This is indeed intended, the recipes are designed in this way on purpose. You are supposed to only make wetwares if you need a UHV circuit essentially, using them in place of crystal processors is a waste due to the net loss you mention. UEVs are the exact same, you only make them to get the UEV circuit, not to use the bioprocessors in the place of lower circuits. As it stands crystals are the cheaper tier, anything beyond that requires these "special" circuits.

I get this can be a bit unintuitive compared to past tiers where the preceeding tiers become obsolete, perhaps in the future when more tiers are fleshed out this will change but this is definitely intended currently. Hope that clears this up.

**Comment by DualBallers** [comment]
@GTNH-Colen thank you for expanding on the thoughts behind this decision and the "paradigm shift" for the circuit progression at this stage :-P
