### ISSUE TITLE
Quests for Chem Plant Machine Casings need adjustment

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6255]
#### Which modpack version are you using?
2.0.9.0 QF2 with the QF3 version of the quest branch
#
#### 

space race tab, *serious upgrades* and *beyond the limit*: Minimum Casing Limit is 80. The tasks, as well as the text at the bottom of *serious upgrades* need to be adjusted accordingly.

The minimum count of 80 is stated in the manual, It only wasn't the case up to now due to a bug in the structure check, but that bug is getting fixed by bot while I am writing this.

**Comment by Prometheus0000** [comment]
Guess I skimmed over that part. I figured 64 would be enough, since you'd probably be able to add a bunch of extra in/outs for other recipes. I wonder how many people will set up dedicated CPs for rocket fuel vs batch crafting considering how many you need?

**Comment by draknyte1** [comment]
You can still use at least 15 hatches or more iirc. (Inclusive of maint, power, catalyst)

**Comment by chochem** [comment]
64 actually worked sofar, that's why I didn't correct it before (+I hadnt fully tested it yet).

I only do batch crafting in mine. easily sufficient. Of course some people will want to automate everything or even go for rocket fuel as a power source, so I am sure we will some dedicated CPs, or some people with a *smart* CP that can do multiple recipes.

**Comment by Prometheus0000** [comment]
And didn't you say something about adding more inputs too? Like 8 solid and liquid or something?

**Comment by chochem** [comment]
49 (top)+20 (sides)+24 (bottom)=93
93-80=13
1 cat, 1 power, 1 maint, 1 controller: leaves 9
of those, 6 have to be for fluids and 2 for solids if you want to do all recipes.
which leaves exactly one. So maybe a second for energy. sounds fine.

**Comment by draknyte1** [comment]
Only 8 solid, NEI spacing is a tad minimal to do extra fluids too.  I’d forgotten if said that, You should drop me a ticket. 😅
