### ISSUE TITLE
Bucket Dupe

### ISSUE THREAD

**Issue by mightydanp** [GTNewHorizons/GT-New-Horizons-Modpack#6256]
#### Which modpack version are you using?
2.0.9.0QF3
#
#### If in multiplayer; On which server does this happen? 
no
#
#### What did you try to do, and what did you expect to happen?
craft mud, give one bucket back
#
#### What happened instead? (Attach screenshots if needed)
gave 2 buckets back
#
#### What do you suggest instead/what changes do you propose?
fix it duping is bad

**Comment by draknyte1** [comment]
Known issue.. did you look at the several existing tickets?

**Comment by Prometheus0000** [comment]
#6230 #6089 #5727 #5591
