### ISSUE TITLE
Calcium chloride electrolysis

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#6257]
2.0.8.8

3 Calcium Chloride dust (CaCl2) outputs only 1 Ca and 2 Cl in the electrolyzer.

Change to 1 CaCl2 -> 1 Ca + 2 Cl

![image](https://user-images.githubusercontent.com/30087707/84550381-be2b2c00-ad0a-11ea-9fab-27b6c84ed5a4.png)

**Comment by GeicowithaBango** [comment]
are you stupid or something?

**Comment by chochem** [comment]
no need for the Ice. 
but to the point: I am pretty certain this is intended, representing that the process is not lossless. You actually get out some extra chlorine elsewhere in the platinum chain, too.

**Comment by DualBallers** [comment]
Jeez, why the need for the hostility??
Most electrolysis recipes gives a 1:1 input to output based on the element ratios, so this struck me as an odd exception.

**Comment by GeicowithaBango** [comment]
So 2(H2O)shouldn’t give 2H2 and O2?

**Comment by DualBallers** [comment]
I'm sure that you are more proficient in redox reactions and what not than me, but that is really not what I was trying to show.

**Comment by chochem** [comment]
well it looks like geico is the idiot :D 

its simple, you put 1 calcium in to get 1 calcium chloride in the previous step, so its very natural to assume there is a full calcium in each calciumchloride.
However, here specifically the process is supposed to have some loss in calcium and some transference of the chloride to somewhere else.

**Comment by GeicowithaBango** [comment]
Im always the idiot D: 

> its simple, you put 1 calcium in to get 1 calcium chloride in the previous step, so its very natural to assume there is a full calcium in each calciumchloride.
> However, here specifically the process is supposed to have some loss in calcium and some transference of the chloride to somewhere else.
 This clearly not intended since its not supposed to be a catalyst.

**Comment by chochem** [comment]
btw here is full calculation from my excel (without gt++ sifter)
![image](https://user-images.githubusercontent.com/40274384/84551725-5541b500-ad06-11ea-906c-079fb04d98cb.png)


notice thats its chlorine positive :)
thats because bart made a maths error. It was supposed to be chlorine neutral I think. anyway its not much so I don't care.

**Comment by DualBallers** [comment]
Wow OK, I am definitely a bit stupid here. 3 in gives 3 out... so there is nothing wrong with the recipe.
I guess I was confused by the large calcium expense for the process.

**Comment by Regian24** [comment]
huh? 3 calcium chloride gives 1 calcium and 2 chlorine, because if it was 1 : 3 you could infintly replicate calcium and chlorine

**Comment by chochem** [comment]
> 
> 
> huh? 3 calcium chloride gives 1 calcium and 2 chlorine, because if it was 1 : 3 you could infintly replicate calcium and chlorine

this false in pretty much every aspect. 1) this would just be neutral in calcium 2) the process is chlorine positive regardless.

did you even read my posts above?
