### ISSUE TITLE
Galacticraft stones don't go into digger backpack

### ISSUE THREAD

**Issue by nom457** [GTNewHorizons/GT-New-Horizons-Modpack#6258]
#### Which modpack version are you using?
2.0.9.0QF4
#### If in multiplayer; On which server does this happen? 
Singleplayer

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5249
 Same problem

**Comment by Prometheus0000** [comment]
Go back to the original issue and say it didn't work. Also check if the items have the rockSpace oredict.

**Comment by combusterf** [comment]
Can't say "it didn't work" when it did. oreDict checks out, and the referenced "fix" was working in a previous release, so we're talking about a regression here.

@Prometheus0000 Could you reopen the referenced ticket or drop the duplicate tag, whichever you feel more appropriate?
