### ISSUE TITLE
Nether to Cobble! WHY?

### ISSUE THREAD

**Issue by Emorgaly** [GTNewHorizons/GT-New-Horizons-Modpack#6259]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen? /What happened instead? (Attach screenshots if needed)

man kann aus Netherrack Cobblestone Craften in dem man sie einfach um crafted
9 Nether -> 9 Cobblestone
![Unbenannt](https://user-images.githubusercontent.com/58056709/84551996-a6a27200-ad0f-11ea-8e9c-1782df2e467a.png)

#### translation:
you can craft from Netherrack Cobblestone by simply crafting them around
9 Nether -> 9 Cobblestone

#
#### What do you suggest instead/what changes do you propose?
Rezept entfernen da es keine Sin macht und man zu leicht an Cobblestone kommt

#### translation:

remove the recipe because it doesn't make sin and it is easy to get cobblestone

**Comment by GTNH-Colen** [comment]
Not really sure it's a rule but I think tickets are supposed to be in english.

Your argument for this is really that it makes it too easy to get cobblestone? I honestly can't tell if this is a troll post lmao

**Comment by Dream-Master** [comment]
@GTNH-Colen i said it is ok.  Better a German ticket than none at all.I translate for you :)

**Comment by Emorgaly** [comment]
GTNH-Colen aren't a Troll Post, my english is only not good enaf.

**Comment by GTNH-Colen** [comment]
Okay but still in any case I see no problem with this recipe, if it was the other way round I could understand your point but cobblestone is free anyways so why not keep this?

**Comment by Emorgaly** [comment]
we was in the Stone Age until yesterday.

Cobbleston was one of the big problems for us. Because with the first tools, it felt like it would take forever to mine cobblestone; And in my opinion, it was what gave the certain Reitz to the age.

after we find out that you can easily carft it  of Netherrack, and that it can be broken down almost 10 times as fast, we build and a Protal and from then on the stone age was just boring.

with us mean 2 people no group.

the text ist translated form Germany whit Google

**Comment by Prometheus0000** [comment]
By the time you get a nether portal normally (in GTNH), you're probably overflowing with cobblestone. Not to mention, it's a material only slightly above wood. Plus the Nether is super dangerous. If you went to all the trouble to get netherrack to convert it, why not let you continue? It's far easier to get with the Extra Utilities thing anyway.

**Comment by Regian24** [comment]
> By the time you get a nether portal normally (in GTNH), you're probably overflowing with cobblestone.

Yeah, even in vanilla lol

**Comment by boubou19** [comment]
imo, just because the resources used in this recipe are trivial doesn't mean this recipe should be kept: there is no use case that justifies this recipe.

**Comment by GTNH-Colen** [comment]
> imo, just because the resources used in this recipe are trivial doesn't mean this recipe should be kept: there is no use case that justifies this recipe.

There is also very little reason to remove it though, it's literally cobblestone lmfao. I've no clue where this recipe came from but I really see no harm in it, it's just a random QoL thing I guess. You can maybe make a furnace if you're in the nether perhaps? (In vanilla anyways)
