### ISSUE TITLE
DD portal nerf

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#6260]
#### Which modpack version are you using?
2.0.9.0 (QF4)
#
So I've thought about this for a bit now and given the power of the void miner in the DD dimension I really think the portal needs to be gated higher.

My current thoughts would be to replace the infinity ingots with infinity blocks and cobblestone with eternal singularities. Any further input would be appreciated though as I've yet to come to a good conclusion on what to do here, but a nerf is definitely in order.

**Comment by chochem** [comment]
I agree, even though I have to craft it soon. Currently you can craft it very quickly after making the T8 rocket, making things like the neutron collector a bit obsolete, as you can get cosmic neutronium ore in the DD.

I am definitely ok with infinity blocks. But I dont quite have a grasp yet on how difficult 2 eternal singularities are. So people who have actually made those have to chime in. If that is too rough, then some lesser singularites could be a middle-ground.

**Comment by GTNH-Colen** [comment]
> I am definitely ok with infinity blocks. But I dont quite have a grasp yet on how difficult 2 eternal singularities are. So people who have actually made those have to chime in. If that is too rough, then some lesser singularites could be a middle-ground.

Eternals aren't really hard, just require some of most materials in the game so makes sense given the DD will give basically every material.  Usage of UEVs may also be warranted in this recipe if we wanted to gate it behind a higher tier so people use neutron collectors for a while (Neutron collectors take UHV wetwares, this would take UEVs so makes some kind of progression).

**Comment by boubou19** [comment]
Unless it was added post 2.0.8.3, there is no cosmic neutronium ore in DD, only infinity catalyst ores. And 64 infinity catalyst dusts are needed to make 1 infinity catalyst.

**Comment by chochem** [comment]
yeah that was added post 8.3

**Comment by GTNH-Colen** [comment]
> Unless it was added post 2.0.8.3, there is no cosmic neutronium ore in DD, only infinity catalyst ores. And 64 infinity catalyst dusts are needed to make 1 infinity catalyst.

Every ore in the game can now be obtained from the DD, except pure infinity ore which is why this needs to be gated much more now.

**Comment by Dream-Master** [comment]
we can put more ore in the blacklist i would say

**Comment by chochem** [comment]
Imo a more difficult portal is a lot more interesting than removing ores.

**Comment by botn365** [comment]
i do think a few ores can be added to the blacklist like 
europium,americium,duranium and tritanium

**Comment by chochem** [comment]
duranium&tritanium dont have an ore. Your are multiple tiers past T1 fusion, so europium ore should be fine. You do have a point with americium though, maybe that should stay with fusion only.

**Comment by botn365** [comment]
i would like all the only fusion ores to stay only fusion

**Comment by chochem** [comment]
well europium is not fusion only, so that fits with what I said.

**Comment by botn365** [comment]
the only non fusion source os europium is a meme ore the meme ore should stil be gotten in dd but europium ore it self no

**Comment by chochem** [comment]
I guess we disagree on one ore then. Anyway you should be able to craft the DD portal yourself right about now, so what do you think of the recipe, the actual issue here?

**Comment by botn365** [comment]
i do agree recipe should be more expansif and lol we have almost no thaumcrap infra so dd is some time away

**Comment by Prometheus0000** [comment]
BTW should I add a copy of the DD quest to UHV? Or just a note? You have to go through the TC stuff anyway.

**Comment by chochem** [comment]
I would wait how this issue turns out. It might be more fitting to the endgame tab, with eternal singularity, etc.

**Comment by GTNH-Colen** [comment]
I really see no issue with adding lower tier fusion materials to the DD, americium is a joke anyways with MK3 fusion as you can make crap tons of it extremely easily and get energy back in the process.

Nerfing the portal and making it much more difficult to craft should be the objective here. As others have said the DD essentially should act as a T9 rocket and as such should be appropriately priced.

**Comment by GTNH-Colen** [comment]
![Capture](https://user-images.githubusercontent.com/54497873/85042063-a9272080-b182-11ea-8e64-5860a75dad8f.png)
Current proposal, cells are in order: Oganesson, Molten Infinity and Molten Cheese

This would move it to the assembly line which I would prefer personally as I really think this should be treated as a "Tier 9" rocket of sorts so this keeps it tech based. Perhaps scanning a T8 plate in the research station could unlock it?

**Comment by Dream-Master** [comment]
![Screenshot 2020-07-23 21 17 48](https://user-images.githubusercontent.com/2970688/88329528-654bac00-cd2a-11ea-88e2-d966b90bec1d.png)
![Screenshot 2020-07-23 21 17 38](https://user-images.githubusercontent.com/2970688/88329533-667cd900-cd2a-11ea-94ff-d40e7d2a14df.png)
![Screenshot 2020-07-23 21 17 30](https://user-images.githubusercontent.com/2970688/88329534-667cd900-cd2a-11ea-962e-3b2ed1c233e9.png)

**Comment by botn365** [comment]
got exited about the recipe but 
i think the field gens and ethernal silgularitys should be reduced 2 of each 
scaning should be research station 
should be the nano circuit not piko
ps: sad to see the thoumcrap

**Comment by GTNH-Colen** [comment]
> Scanning should be in the research station
This is a good point that totally slipped my mind honestly, completely agree.

**Comment by Dream-Master** [comment]
research station recipe added.

**Comment by Dream-Master** [comment]
make TH recipe cheaper
