### ISSUE TITLE
ore-berry und XP-berry growing at lightlevel 12? Why

### ISSUE THREAD

**Issue by Emorgaly** [GTNewHorizons/GT-New-Horizons-Modpack#6261]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Wir haben zum ausbau unsere Erzfarm, Fackeln gesetzt und diese dann vergessen abzubauen. Später bemerkten wir das sowohl ore-berry als auch XP-berry auch bei einem Lichtlevel von 12 Problemlos wachsen.

#### translation:
We used our ore farm to set torches and then forgot to mine them. Later we noticed that both ore-berry and XP-berry grow easily even at a light level of 12
#
#### What happened instead? (Attach screenshots if needed)
eigentlich (so kennen ich den Mod) wachsen beide berrys nur bei fast vollkomender Dunkelheit

#### translation:
actually (as I know the mod) both berry's only grow in almost perfect darkness

#
#### What do you suggest instead/what changes do you propose?

ich empfinde es als zu leicht wenn man diese einfach an der Oberfläsche wachsen lassen kann

#### translation:
I think it is too easy if you can just let it grow on the surface

**Comment by glowredman** [comment]
Wenn du in Zukunft deine Tickets auf Englisch verfasst, können dir auch mehr Leute helfen ;)

Zum Thema: Das ist so gedacht. Essenceberry Büsche sind eben keine _Ore_-berry Büsche.

**Comment by Dream-Master** [comment]
Ich hab gesagt auf deutsch wäre ok.

**Comment by glowredman** [comment]
Wenn Chef sagt, ist okay, ist das natürlich was anderes ^^

**Comment by Prometheus0000** [comment]
Oreberries should be 10 or less, while the XP ones can grow at any light level. It should be the same for the non-IC2 crop original versions.
