### ISSUE TITLE
Dedicated server 2.0.9.0QF4 CRASH!

### ISSUE THREAD

**Issue by I3lackI3rains** [GTNewHorizons/GT-New-Horizons-Modpack#6262]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Dedicated server GTNH 2.0.9.0QF4
#
#### What did you try to do, and what did you expect to happen?
I just download it from your website and try to start it
#
#### What happened instead? (Attach screenshots if needed)
It crashed while while it was being launched
#
#### What do you suggest instead/what changes do you propose?
fix it plz :)

[crash-log.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4774017/crash-log.zip)

**Comment by noobnoobnub** [comment]
Did you follow the procedure in the pinned message in discord?

How to switch from Thermos to Forge server
1. Get the server from here. http://downloads.gtnewhorizons.com/ServerPacks/
2. After extraction delete libraries folder, Thermos-1.7.10-1614-server.jar and minecraft_server.1.7.10.jar.
3. Grab latest forge installer for 1.7.10 http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html
4. Run a server installer on an empty folder. And after that merge forge server folder and GTNH server folder.
5. Delete these mods from the mods folder: 
BanHammerJ-0.0.2.jar
Gambiarras_BQThermosFix-1.0.1.jar
MyEssentials-Core-1.7.10-1.19GTNH-universal.jar
MyPermissions-1.7.10-67GTNH.jar
MyTown2-1.7.10-0.5.2GTNH.jar
MyTownWebAuth-1.7.10-1.0.0.jar
AMDIForge-1.7.10-1.0.1.jar
6. Make sure startserver.bat looks like this "java -Xms2G -Xmx6G -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui"
7. Run startserver.bat

**Comment by Dream-Master** [comment]
Maybe i need to make this mods optinal that people use Forge as default

**Comment by I3lackI3rains** [comment]
http://downloads.gtnewhorizons.com/ServerPacks/GTNewHorizonsServer-1.7.10-2.0.9.0QF4.zip

How I got it right is the non-working version, yes?

**Comment by draknyte1** [comment]
Literally every time people use thermos. 
![BA8A5C11-B8EC-4AD3-AC37-50D6BF65DF74](https://user-images.githubusercontent.com/3060479/84564398-3e787e00-ad59-11ea-8694-e8bfaedccbaa.png)

Don’t make it the default. 🤦🏻‍♀️

**Comment by Dream-Master** [comment]
@I3lackI3rains not close it when it isn't fixed. Thanks

**Comment by Prometheus0000** [comment]
We're on a new version now, that hopefully works, whatever your problem was?
