### ISSUE TITLE
Hardcore Ender Expansion Instability Orbs can be used to get lategame materials

### ISSUE THREAD

**Issue by SampsaxD** [GTNewHorizons/GT-New-Horizons-Modpack#6263]
These orbs can turn into, for example:
Mysterious Crystal
Infinity
Callisto Ice

And a lot more stuff, by just throwing them on the ground, and they are available in HV.

Should make a blacklist/whitelist for the drops they can give.

**Comment by chochem** [comment]
A whitelist would be better as the item list here is very big and includes broken items that can cause a crash and probably anything new that gets added.

**Comment by ScriptedPiky** [comment]
It can practically give you almost any item. However, it sometimes likes to choose very specific ones repeatedly for some odd reason. Additionally, you can get some very wacky items (including Dense Infinity Plates) or spawn eggs or spawning mobs (uncertain if this can spawn bosses). You can also crash your game or server by spawning in a bad or null item.

**Comment by Prometheus0000** [comment]
They can also seem to spawn any non boss mob as well. So you can spawn the Golems from the Everglades put them into a soul vial, make that into a spawner, and get free staballoy you can centrifuge for uranium.

However it isn't easy to get the large amounts of the orbs you would need to get anything decent.

**Comment by GTNH-Colen** [comment]
This has been known for a while, I saw someone get a quantum plate before I think which needs UEV? We probably should just outright remove the ore tbh, not only does it break the progression it also causes server crashes because it spawns invalid items as Piky says.

**Comment by Dream-Master** [comment]
Fix not remove

**Comment by GTNH-Colen** [comment]
> Fix not remove

Are we allowed to modify HEE?

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/Hardcore-Ender-Expansion

And they were here commenting on a previous issue.

**Comment by lor1113** [comment]
Best not to remove the orbs because they do have legitimate uses aside from making into random items. At worst I'd say remove the dropping feature entirely.

**Comment by bartimaeusnek** [comment]
Intended. No need for a fix or removal.

**Comment by Prometheus0000** [comment]
> You can also crash your game or server by spawning in a bad or null item.

This is intended? I didn't report it before (balance reasons, not crashing) because you need a large amount of them to have a probability of getting anything good, but if it can crash worlds/servers, shouldn't that be handled?

**Comment by Dream-Master** [comment]
intended or not but if the game crash or if you get some very late game items i am not ok with it.

**Comment by CatsLeftEar** [comment]
![orb](https://user-images.githubusercontent.com/67397297/109416626-b78b3480-79bf-11eb-8a6b-ee5c19b21cc1.png)

**Comment by CatsLeftEar** [comment]
Instability orbs also often explode, this is part of spawn. They backdoor any protection
![изображение](https://user-images.githubusercontent.com/67397297/112134007-9091de00-8bcc-11eb-8561-363dddd7cc7b.png)
