### ISSUE TITLE
Remove or Change Quest 'Technology: Evolved'

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6264]
#### Which modpack version are you using?
9.0QF2
#
#### 

It says *You beat the game. literally. There is nothing left to do....* and that after getting through the TF and getting a T7 rocket.

A simple removal is easy, as the quest is replaced by all the new high tier quests and in particular the new endgame quest tab. This was already shortly discussed on discord a few days ago.

Even worse: Sofia just pointed out to me on discord that the quest allows you to get an OP wand without ever doing any thaumcraft.

The only part that might be worth a thought, is to maybe reuse some of the quest rewards in the new high tier/endgame quests.

![image](https://user-images.githubusercontent.com/40274384/84563410-4a614180-ad53-11ea-9e29-9c6c15be94e7.png)

**Comment by Prometheus0000** [comment]
I'd say just change it to some kind of ' welcome to the end game' quest or something and make the rewards much worse. After all there's a bunch of quests that lead up to it on the tab.

**Comment by chochem** [comment]
thats sounds perfectly fine to me :)

**Comment by Prometheus0000** [comment]
Suggestions would be welcome. Keep in mind that this will also be added to the opening req for the endgame tab. Though that would mean that people would have to defeat the twilight bosses. Are there people that skip those at neutronium-having level?
