### ISSUE TITLE
Bricked Blast Furnace recipe using charcoal blocks doesnt work

### ISSUE THREAD

**Issue by Xela10001** [GTNewHorizons/GT-New-Horizons-Modpack#6265]
#### Which modpack version are you using?
2.0.9.0QF3
#
#### What did you try to do, and what did you expect to happen?
I tried to cook my first steel in the Bricked Blast Furnace using 5 steel and 2 charcoal blocks, and I even tried changing the slots of the blocks and of the ingots.
#
#### What happened instead? (Attach screenshots if needed)
Nothing happened, instead of the furnace beggining to cook the iron into steel.
![image](https://user-images.githubusercontent.com/47480171/84567080-31b25500-ad6e-11ea-8cc4-1b3f62333d1d.png)

#
#### What do you suggest instead/what changes do you propose?
Fix the recipe or disable it in NEI
![image](https://user-images.githubusercontent.com/47480171/84567084-3a0a9000-ad6e-11ea-9eff-33cea03adf31.png)

**Comment by Prometheus0000** [comment]
Did you form it correctly? There was someone with basically the exact same problem on discord yesterday.

**Comment by Xela10001** [comment]
It was placed correctly and within chunk borders, and I even broke and replaced it and it still didnt work. And after breaking it and placing it back for the 2nd time, it worked for some reason. Sorry to bother
