### ISSUE TITLE
Make it easier for people to get dragon essence/egg/heart if you're in MP

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6267]
#### Which modpack version are you using?
2.0.9.0 QF3
#
As mentioned by Colen, you can't really make the dragon egg using the heart, or use the quest to get essence if you didn't kill the dragon. And you can't summon it again without the egg either.

If you're on MP, you need to do serious bee shenanigans (to breed up to the egg-producing bee), since they require the egg as their flower. So you need to breed into other bees and hope that end flower is not the active trait. And if it is even once, you gotta start that bee type over. You have to go through 4 bees like this.

Also, I somehow didn't get the heart even in SP, so it's possible to not get it. You also need an egg to respawn the dragon to get more hearts, or get the essence the normal way, or do the essence quest.
#
#### What do you suggest instead/what changes do you propose?
Add an alternative recipe for the dragon egg LCR recipe that is much harder, or a way to craft the heart. I'm thinking UUM+multiple enriched draconium eggs, and maybe blocks of something?

**Comment by chochem** [comment]
as I already pointed out to Colen, dream added new HEE bees that make that a lot easier

**Comment by chochem** [comment]
> If you're on MP, you need to do serious bee shenanigans (to breed up to the egg-producing bee), since they require the egg as their flower. So you need to breed into other bees and hope that end flower is not the active trait

also, this part is a lot easier then it sounds. not only can you use template princesses to circumvent bad traits like that, its actually even easier here as the dragon egg flower trait is recessive.

Having made all these points, there might still be uses for a recipe like the one you propose.

there is also an older open issue on the matter https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5530

**Comment by Prometheus0000** [comment]
I thought forestry didn't use the idea of dominant and recessive traits, only active and inactive ones? Is our fork different?

**Comment by chochem** [comment]
thats just normal forestry

**Comment by Prometheus0000** [comment]
OK, so you breed the bees to get the egg so you can summon the dragon and get the heart and essence (although there's also a bee for the essence directly too now). When doing so, it shouldn't be that hard to keep end flower as an inactive trait (because of recessive traits), so is there a need for a recipe change or addition any more? Or maybe a mention of how to do this?

PS: Dominant and Recessive-ness has been added to the bee guide.

**Comment by GTNH-Colen** [comment]
I would still like to see a recipe here if possible, forcing users to breed specific bee chains is irritating and adding a recipe would level the playing field for those not into bees.

**Comment by Prometheus0000** [comment]
I added a quest to get a heart if you need one, so I think this is done?
