### ISSUE TITLE
Spelling error in quest #69 "Wire-Wrap

### ISSUE THREAD

**Issue by Oblivo** [GTNewHorizons/GT-New-Horizons-Modpack#6269]
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Singleplayer

Error is in Quest #69 "Wire-Wrap"

Sulfur is written as "sulphur" in the description, should be "sulfur" instead

![spelling_sulfur](https://user-images.githubusercontent.com/66883943/84576804-b83f5480-adb7-11ea-89e2-7f3f0f625bd0.png)

**Comment by draknyte1** [comment]
Sulphur is technically correct. 
https://grammarist.com/spelling/sulfur-sulphur/

**Comment by Prometheus0000** [comment]
True, but very very little in GTNH uses the ph version

**Comment by Oblivo** [comment]
Technically yes, but it seems odd to use 2 different spelling variants on the same quest, and as Prometheus mentioned there are almost no items with the ph :)
