### ISSUE TITLE
General Purpose Fermenting Bacteria Culture can't be made

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6270]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### What did you try to do, and what did you expect to happen?
Check the recipe to see how it's made.
#
#### What happened instead? (Attach screenshots if needed)
It's made with the fluid you use it to make, a catch-22. I suspect that the ones I see are the 'you can make it easier now that you have the culture' recipes, since the others seem to all have that.
#
#### What do you suggest instead/what changes do you propose?
Add the appropriate recipes, or fix them if they're broken. they would probably be the same, but water/distilled water.

**Comment by bartimaeusnek** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5049#issuecomment-540540587

Same procedure like this, but with yeast plasmid injected into Escherichia cadaver

**Comment by Prometheus0000** [comment]
Ugh, I'd rather tell people to use the cadaver one for xenoxene.

**Comment by bartimaeusnek** [comment]
you can create fluid from the Escherichia cadaver and create seperate copies of it 😄

**Comment by Prometheus0000** [comment]
Added a quest for it.
