### ISSUE TITLE
Calcium smelting recipe bugged in 9.0

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6274]
#### Which modpack version are you using?
2.0.9.0 QF2
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
I tried to get from calcium dust to molten calcium. Context: This is needed for Oganesson.
#
#### What happened instead? (Attach screenshots if needed)
Calcium dust can not be smelted or fluid extracted. (except with the infernal blast furnace according to NEI, but I dont have one of those, so not tested)
Only calcium ingots can be fluid extracted but I cannot get them.

#
#### What do you suggest instead/what changes do you propose?
It looks like this is a bug on 9.0.

A helpful soul on discord provided me with a screenshot from 8.8 where calcium dust can be turned into ingots with nitrogen in the EBF: 
![image](https://user-images.githubusercontent.com/40274384/84584409-e8a8e200-adfb-11ea-9e9f-7bd5a9010cf8.png)

This recipe does not work in 9.0 and does not exist in NEI either.

**Comment by yukieiji** [comment]
This issue also occurs in QF4.
This problem has prevented me from making an Oganesson...

**Comment by chochem** [comment]
> 
> 
> This issue also occurs in QF4.
> This problem has prevented me from making an Oganesson...

@yukieiji Until it is fixed the workaround is: Make calcium plasma and cool it down with a plasma gen. Use to make your first Oganesson. Then get more by replicating.

**Comment by Prometheus0000** [comment]
@bartimaeusnek Are you ever going to fix this? Is it BW, GT, or something else causing the bug?
