### ISSUE TITLE
Bartworks materials have two replicator recipes in NEI in 9.0

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#6275]
#### Which modpack version are you using?
2.0.9.0 QF2
#
####

This does not affect all materials, which is why I did not notice it earlier. The recipes are obviously the old one and the new one in terms of uum with the times bugged for the new one (the time might be fixed in QF3/4, see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6184)

It affects Tiberium, Oganesson, Californium, Rhodium, Ruthenium, Zirconium, Krypton, so the bartworks materials really.

I have not tested yet which one is actually used. I will post an update once I have.

Update: tested for oganesson. It uses the more expensive (so the correct) recipe. But I don't know if that is just random or reliable.

![image](https://user-images.githubusercontent.com/40274384/84584582-155df900-adfe-11ea-9b7d-1e2760fa4702.png) 
![image](https://user-images.githubusercontent.com/40274384/84584584-1d1d9d80-adfe-11ea-8b5d-480e843b0c2f.png)

**Comment by GTNH-Colen** [comment]
This has been known for a while now I think, thought it was fixed though. Bart said it is purely visual to me a while ago iirc, have you tried with QF4?

**Comment by chochem** [comment]
I did not see any report. will try again once I am on QF4+.

**Comment by GTNH-Colen** [comment]
> I did not see any report. will check again once I am on QF4+.

Yea sorry, I meant as in it's been known to people for a while but there is no active ticket afaik so this is still good.

**Comment by Prometheus0000** [comment]
This appears fixed
