### ISSUE TITLE
Make some blocks/items recyclable

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#6277]
#### Which modpack version are you using?

# 2.0.9.0 qf4
#### If in multiplayer; On which server does this happen? 

# sp
#### What do you suggest instead/what changes do you propose?
Could you add a recycle recipe for the IO hatch and bus,and the compressed plates of GC?

**Comment by Prometheus0000** [comment]
Similar to #5263
