### ISSUE TITLE
Problem with FancyBlockParticles in the Twiligt Forest

### ISSUE THREAD

**Issue by soufhehe** [GTNewHorizons/GT-New-Horizons-Modpack#6280]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen?
Singleplayer
# 
#### What did you try to do
I went to the twilight forest
# 
#### What happened
It crashed. Here is the logs.
https://pastebin.com/LkN8hTLw
I added some additionnals mods from here https://gtnh.miraheze.org/wiki/Additional_Mods and I figured out that it was FancyBlockParticles that was causing that.
Also I have updated FastCraft to 1.25 so I can add Optifine, I don't know if it matters 
# 
#### What do you suggest instead/what changes do you propose?
fix it pls

**Comment by Prometheus0000** [comment]
My understanding is that TF uses a lot of CPU power to do worldgen and may crash the first time you enter no matter what depending on your computer.

**Comment by Dream-Master** [comment]
@jss2a98aj any idea to change the way Tf load up the first time you entered the TF ?
i see BogdanG fork had some terrain gen changes but i am not sure if this is helpful

**Comment by jss2a98aj** [comment]
The BogdanG fork does very little to speed up TF world gen. My own changes also do very little. Significant improvements will likely require rewriting most TF world gen code.

**Comment by Prometheus0000** [comment]
Additional mods that add lag are unsupported. Try using more ram or getting a better computer. Or rent a server to offload calculations to it
