### ISSUE TITLE
Electric scribing tools not charging

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#6281]
#### Which modpack version are you using?
2.0.8.3

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
As per the questbook instructions, I made electric scribing tools and put them in an LV battery buffer for charging

#
#### What happened instead? (Attach screenshots if needed)
The electric scribing tools remained at 0 EU.

I was also unable to start research, the thaumonomicon would tell me I need scribing tools and paper. I also could not charge the item in an MV through IV battery buffer, and as a sanity check, the LV battery buffer in question was able to charge other items.

![image](https://user-images.githubusercontent.com/8459776/84604088-d4b0bf00-ae93-11ea-8dd7-7f03de62b13a.png)

Edit: LV machines did not work, HV machines do work

#
#### What do you suggest instead/what changes do you propose?
- Update the quest to list the tier as HV
- Address charging issues related to the battery buffer.

**Comment by Prometheus0000** [comment]
Try an LV machine.

**Comment by combusterf** [comment]
Nope:
![image](https://user-images.githubusercontent.com/8459776/84629328-6c40fc80-aeea-11ea-812a-1824cf8671d9.png)

**Comment by ElNounch** [comment]
Please double check charging in a **HV** machine's energy slot.
It is not a LV tier tool anymore, due to #2752.

**Comment by combusterf** [comment]
I had seen that issue, which is one of the reasons why I had tried the HV battery buffer already. The machine however did work. That basically leaves two issues:
1) Battery buffers don't actually charge, which sounds like an undesired feature to me.
2) The questbook lists the wrong machine tier.

**Comment by viljar290** [comment]
the electric scribing tools do not get charged properly by wireless charger either (the ev tier one) it shows full charge but durability slowly goes to 0 as you use it and then it only charges in HV machine battery slot or battery charger. EV wireless charges everything on you EV or below.

**Comment by CatsLeftEar** [comment]
I want to bump this because quest still tells to use LV
![изображение](https://user-images.githubusercontent.com/67397297/108287026-735f8f00-718a-11eb-8f79-ebbf441a9d1c.png)

**Comment by Prometheus0000** [comment]
I checked and it works charging it in an HV batbuff.

**Comment by CatsLeftEar** [comment]
Yes, but text in quests says LV only. Mistake in text quest

**Comment by Prometheus0000** [comment]
I already updated the quest text.
