### ISSUE TITLE
Distillery Will Not Eject Into Gas Turbine (MV)

### ISSUE THREAD

**Issue by chadtheturtle** [GTNewHorizons/GT-New-Horizons-Modpack#6282]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Set a Distillery facing a Gas turbine (both MV) to auto-eject. Both machines were facing different ways, expected benzene to flow from distillery toward turbine to generate power.
#
#### What happened instead? (Attach screenshots if needed)
The benzene would not flow into the turbine but would flow into diamond tank, and can be piped from the tank to the turbine.
![2020-06-15_01 28 14](https://user-images.githubusercontent.com/66935665/84621536-cf11a400-aea8-11ea-97d5-9d918325da83.png)
![2020-06-15_01 41 08](https://user-images.githubusercontent.com/66935665/84621736-54955400-aea9-11ea-8d84-07662ad9c844.png)

#
#### What do you suggest instead/what changes do you propose?
allow MV distillery to auto-output to gas turbine/ allow turbine to accept the fluid without pipes.

**Comment by GTNH-Afx237v7** [comment]
Did the turbine front perhaps face the distillery? Front faces don’t interact.

**Comment by noobnoobnub** [comment]
why would you want that? I would suggest to autooutput to a pipe then to the turbine as you dont want all the fuel go to one turbine that powering itself only

**Comment by shawnbyday** [comment]
@chadtheturtle pretty sure you're trying to do what GTNH-afx said. I'm closing this as I think this is more of a configuration issue than a bug. If you're still trying to work on this please pop in our help channel on discord and you'll get plenty of people able to help you out.
