### ISSUE TITLE
Server crash (0.9QF4)

### ISSUE THREAD

**Issue by lor1113** [GTNewHorizons/GT-New-Horizons-Modpack#6285]
#### Which modpack version are you using?
2.0.9.0QF4

#### If in multiplayer; On which server does this happen? 
My personal server

#### What did you try to do, and what did you expect to happen?
I updated the server to 2.0.9.0 from 2.0.8.8 by downloading the appropriate server file from (http://downloads.gtnewhorizons.com/ServerPacks/) and unzipping it in the main world folder, allowing it to replace all previous files. I expected the server to, well, work

#### What happened instead? (Attach screenshots if needed)
The server crashes on boot. This seems unrelated to the previous thermos issue because (A) apparently that issue has been resolved with the QF4 download if I understand dream's discord message correctly and secondly because the erorr is different
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4782819/fml-server-latest.1.log)

#### What do you suggest instead/what changes do you propose?
That it works

**Comment by bartimaeusnek** [comment]
This is a ASM clash. Bugtorch and micdoodle core are clashing here, I'd recommend to turn off the server start patch from bugtorch for now.

**Comment by Dream-Master** [comment]
just disable the cobfig option "chunck loading on startup disabled" in the mixin config file

**Comment by lor1113** [comment]
Thanks I'll try that

**Comment by lor1113** [comment]
Same crash despite config change

[crashlog](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4783008/fml-server-latest.2.log)


[mixins.cfg](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4783014/mixins.txt)

**Comment by lor1113** [comment]
Crash fixed. Nothing that needs to change on your end, I made a silly mistake with setup.
