### ISSUE TITLE
Suggestion: Make the Extruder Shape (cell) give different outputs depending on material

### ISSUE THREAD

**Issue by AndreasBoegh** [GTNewHorizons/GT-New-Horizons-Modpack#6289]
#### Which modpack version are you using?
2.0.8.3

#### Extruder shape cell ####
Currently the Extruder allows you to make Industrialcraft 2 Empty Cells. This can be done with 2 of different ingots: 
* Steel ingots
* Magnetic steel ingots
* Polytetrafluoroethylene bar
* tin ingot

All of these recipes give a single cell
I propose that 
* 2 tin ingots gives 1 cell
* 1 steel ingot gives 1 cell
* Polytetrafluoroethylene bar gives 2 cells

This would give one an incentive to use either steel or PTFE.

**Comment by shawnbyday** [comment]
See lots of thumbs up on this. Can assign to me. Anyone have any different ideas opposed to what @AndreasBoegh suggested?
