### ISSUE TITLE
Industrial material press does not display missing muffler hatch

### ISSUE THREAD

**Issue by liripoop** [GTNewHorizons/GT-New-Horizons-Modpack#6291]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
I built an industrial material press and forgot to include a muffler hatch. Since the structure was incomplete it should not have worked and displayed the incomplete structure warning on the controller.
#
#### What happened instead? (Attach screenshots if needed)
The press worked for a couple recipes and then stopped working without displaying the inclomplete structure warning. I have not tested any other multiblocks except the blast furnace which was behaving as expected.
#
#### What do you suggest instead/what changes do you propose?
Display the incomplete stucture warning on the controller when the muffler hatch is missing and stop the machine from working in a limited capacity without the hatch.

**Comment by Prometheus0000** [comment]
Report at the gt++ repo.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/36
