### ISSUE TITLE
Server Disconnect when breaking 2x2 Draw

### ISSUE THREAD

**Issue by Okka676767** [GTNewHorizons/GT-New-Horizons-Modpack#6292]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
 Official Server Eta
#
#### What did you try to do, and what did you expect to happen?
Broke 2x2 Draw and hoped to get drawer + items
#
#### What happened instead? (Attach screenshots if needed)
Game crashed
#
#### What do you suggest instead/what changes do you propose?
fix?

**Comment by Regian24** [comment]
how many items did the drawer have? maybe it was too much, and 3k cobblestone going on the floor lagged your client and crashed you

**Comment by Okka676767** [comment]
No, it was no more than 200 items and the error message said a "fatal error has occurred".

**Comment by Regian24** [comment]
Huh, that's weird.

**Comment by boubou19** [comment]
what was the items in it? is your base overpopulated with stuff containing high nbt? because the game has a limit of data which can be sent to the client. My guess is that you were close to that limit, and breaking the barrel added enough data to reach this limit, causing you to disconnect. But i may be wrong tho as the "internal server error" is a generic error.

**Comment by Prometheus0000** [comment]
Does this still happen on newer versions?

**Comment by Dream-Master** [comment]
nope this is fixed with the gamberia fix

**Comment by Okka676767** [comment]
Poggers Sent from Mail for Windows 10 From: Martin RobertzSent: 07 October 2020 17:45To: GTNewHorizons/GT-New-Horizons-ModpackCc: Okka676767; AuthorSubject: Re: [GTNewHorizons/GT-New-Horizons-Modpack] Server Disconnect when breaking 2x2 Draw (#6292) Closed #6292.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Dream-Master** [comment]
@Okka676767 ?
