### ISSUE TITLE
Wireless crafting terminal crash game when placed inside own crafting grid

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#6296]
2.0.9.0

How to replicate crash:
- Have a linked (universal) wireless crafting terminal in the hot bar, and use it.
- Move the mouse cursor inside the opened crafting grid onto a crafting square.
- If the placement of the terminal is e.g. in the third hot bar slot then press the 3 key on the keyboard.
- The terminal item will move inside its own crafting grid and (I guess) the recursion of this state will crash the game.

When the game is reloaded the terminal item is deleted. 

Other items from the hot bar can also be moved into the crafting grid in the same manner (for me often by accident). This does not cause a crash, and though it is not very useful IMO I expect this is intended.

Solution?
When the terminal is open it is not possible to move the terminal item with the mouse, so the same restriction should somehow be applied to the 1-9 shortcut function.

**Comment by repo-alt** [comment]
Afaik universal crafting terminal from EC2 is just disabled, is it not? (If not, it should be, WCT is also buggy, but way less buggy)

**Comment by boubou19** [comment]
This issue is very frustrating: just crashed delta right now. 
[crash-2021-01-01_14.07.13-server (1).txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5758963/crash-2021-01-01_14.07.13-server.1.txt)
