### ISSUE TITLE
Floodlights Sometimes Causing Server Crash on Chunkload

### ISSUE THREAD

**Issue by finkledoodle** [GTNewHorizons/GT-New-Horizons-Modpack#6298]
#### Which modpack version are you using?
2.0.8.3

#
#### If in multiplayer; On which server does this happen? 
Prospercraft

#
#### What did you try to do, and what did you expect to happen?
Use Floodlights to light a room. 

#
#### What happened instead? (Attach screenshots if needed)
They seem to work fine for days or weeks until they cause server crashes upon loading the chunk they are in. After the crash I'm able to rejoin and load the chunk as normal though. As I'm not very good with the details, I'll just quote those that assisted me on the discord. BigBass said that it "Looks like an issue with multi-threading in that mod. Something is manipulating a collection while it's being iterated through somewhere else"

Here are the crashlogs from server crashes caused by different sets of floodlights
https://paste.centos.org/view/c888e265
https://paste.centos.org/view/239e9e51

#
#### What do you suggest instead/what changes do you propose?
According to BigBass, "the 1.7.10 version of the mod has highly problematic code for updating the floodlights. They rewrote how the class works in the 1.12 version, likely to avoid that concurrency issue"

Mitchej123 suggested that backporting the fixes from the 1.12 version may not be very difficult, and would solve these issues without requiring the removal of the mod from the pack.

**Comment by ProsperCraft** [comment]
Dedicated server crash - https://gist.github.com/ProsperCraft/47814a4ba31555975fcdc7db987b34c3
