### ISSUE TITLE
existing dimensional transceivers are broken after update

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6299]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
wanted to fix my dimensional transcievers because the chanels have disappeared (it happens sometimes without the server being updated as well so i am used to it). I expected it to work again after i have set new chanels up

#
#### What happened instead? (Attach screenshots if needed)
The dimensional transcievers do not accept any energy, either by new energy channel, or linking it to gt cables/ vibrant capacitors. 
#
#### What do you suggest instead/what changes do you propose?
As it's fixed by cleaning the dimensional transceiver configuration, i believe the nbt of existing dimensional transceivers are somehow broken.

**Comment by Prometheus0000** [comment]
Run it through the crafting grid.

**Comment by boubou19** [comment]
i did it but that's not a proper fix.

**Comment by Prometheus0000** [comment]
Then too bad? My understanding is that it was necessary to fix them not working. Complain to the person who fixed them (I forget who).

**Comment by repo-alt** [comment]
@Zoko061602
