### ISSUE TITLE
Suggestion: Buff Large Gas Turbine

### ISSUE THREAD

**Issue by GeicowithaBango** [GTNewHorizons/GT-New-Horizons-Modpack#6301]
I mentioned recently in a diffrent ticket that I am clueless about the current situation of LGTs.
I suggest that certain Turbine blades should get buffed. It seems like there are no good choices to create one amp of IV with one multi-block. 
There are a couple end game materials which can perform more then an amp of IV but until then, one has already better power sources.
The solid-oxide fuel cell mk2 is worth mentioning here, since it also consumes gases. It has a diffrently mechanic tho and its quiet expensive but doesnt uses any Turbines, therefore, its indeed diffrent then the LGT. 

In addition to that I also suggest to raise up the energy density of Liquid Petroleum Gas

**Comment by chochem** [comment]
Large Oriharukon is fairly straightforward and produces an amp of IV. Having some choices besides trinium to go beyond that in late IV/early LuV would be great though.

**Comment by Prometheus0000** [comment]
Already changed: #5970
