### ISSUE TITLE
Output hatch ignores EIO fluid conduit redstone mode

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#6303]
2.0.9.0

A multiblock output hatch connected to an EIO fluid conduit will ignore the auto extract redstone mode of the conduit and push fluid into the conduit regardless.

The four redstone modes, with the example of no applied redstone signal to the conduit:

- Always active / Active without signal = no issue, the generated fluid is auto pushed to conduit without showing in the output interface

- Active with signal / Never active = issue, the generated fluid is shown as flickering in the output interface and is then auto pushed into the conduit

However, as I find it, an output bus connected to an EIO item conduit will respect the conduit redstone mode and redstone signal, and only push according to this.

**Comment by leagris** [comment]
Not a bug and normal behaviour for both Gregtech output Hatch and EnderIO fluid conduits:

- Gregtech Fluid hatch will push fluid to adjacent container/pipes if it has free space to receive fluid.
 - EnderIO Fluid conduit's Redstone control only turns the active pumping o or off. It does not determines if fluid is allowed to be pushed flow-in from another tile.

**Comment by DualBallers** [comment]
Alright, I will take your word for it, though I would find it favorable if the flow could be controlled directly from the output hatch using EIO.

However it strikes me as strange that there is, as mentioned, a clear visual difference between the redstone modes. It seems like there is already a difference in the code for the fluid handling here.

**Comment by Prometheus0000** [comment]
Try using the shutter cover.

**Comment by DualBallers** [comment]
Tried the shutter cover in all settings but could unfortunately not control the output this way.

**Comment by Prometheus0000** [comment]
Did you use the shutter cover along with the machine cover? I use this combination to cut off fuel to my LGT, so I can get maximum efficiency pretty much right away, so I know the cover works. You need to put the shutter between the pipes, if you didn't know that.

**Comment by DualBallers** [comment]
Haven't tried the machine and shutter combo, but I found that EIO fluid conduits can extract from all sides of an output bus. 
So as long as it's not connected to the normal output side, it is possible to use the all the redstone modes.

**Comment by Technus** [comment]
Hard hammer should toggle force output on hatch/machine iirc

**Comment by DualBallers** [comment]
@Technus great, I suppose that was the option I was looking for :-)

No point keeping the issue open.
