### ISSUE TITLE
[Witchery] Koboldite tiny dust

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6305]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
Hobgoblin's no drop koboldite tiny dust.
I think it's happened after 2.0.8.3 to 2.0.9.0QF4 update.
I'm try regular and koboldite Pickaxe
![изображение](https://user-images.githubusercontent.com/47714084/85210362-e2f55400-b347-11ea-8dfd-cee14b78f723.png)

**Comment by repo-alt** [comment]
I tested in single and I had koboldite drop (I used a diamond pick and vanilla iron ore). It required a stack of ore to get one dust, so, maybe you are just unlucky.

**Comment by yukieiji** [comment]
As previously reported(#3792), I think it's a bug in Thermos Server.
How about add some kind of relief recipe(very expensive)?

**Comment by repo-alt** [comment]
When the previous bug was reported I had Koboldite farm on Epsilon working (albeit much slower than in SP). Set one Hobgoblin to work on Eta yesterday, will see if he will bring something.

**Comment by repo-alt** [comment]
Turned out to be working on Eta too
