### ISSUE TITLE
Basic Combustion Generator Bug

### ISSUE THREAD

**Issue by ReflVec** [GTNewHorizons/GT-New-Horizons-Modpack#6306]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I put cells with **Light Fuel** in **Basic Combustion Generator** while there **Cetane-Boosted Diesel**, expect returning empty cells from combustion generator at least.
#
#### What happened instead? (Attach screenshots if needed)
Cells with Light fuel disappear and generator works on light fuel while boosted diesel in generator, so emty cells not return in this process.
#
#### What do you suggest instead/what changes do you propose?
Check all generators with GUI for this bug (Basic gas turbine with different gases - not noticed)

**Comment by Prometheus0000** [comment]
Same as #5689?

**Comment by ReflVec** [comment]
probably the same thing
