### ISSUE TITLE
Chem. Plant catalyst usage

### ISSUE THREAD

**Issue by paroxod** [GTNewHorizons/GT-New-Horizons-Modpack#6308]
#### Which modpack version are you using?
2.0.9.0QF4

#
#### If in multiplayer; On which server does this happen? 
Server Eta

#
#### What did you try to do, and what did you expect to happen?
 I wanted to make purple rocket fuel in one chemical plant with 8 parallels, but the following problems arose.
 1. The orange metal catalyst breaks during any other recipe in which it should not be used.
 2. When the strength of the catalyst reaches 1/50, it remains in this state and does not collapse
completely. But at the same time, empty catalysts appear in the ME. In the morning I threw 8 orange catalysts, and now I have 500 empty catalysts.
 3. And everything would not be so bad, but when the strength of the catalyst is in the 1/50 state, the chemical plant stops working in 8 parallels, but only in 1, which is VERY bad.

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/67229669/85227927-e1dd2900-b412-11ea-8d9d-c0af8e332383.png)
![image](https://user-images.githubusercontent.com/67229669/85227940-f7eae980-b412-11ea-841d-8f83fc47db5a.png)
![image](https://user-images.githubusercontent.com/67229669/85227541-bbb68980-b410-11ea-8029-7b89ce6161cc.png)

#
#### What do you suggest instead/what changes do you propose? 
 Make sure that the catalyst does not lose strength when a recipe occurs in which it is not used.
Destroy the catalyst completely in a 1/50 strength state so that the new catalyst replaces it. This will immediately fix the problem with 1 active parallel instead of 8.

**Comment by Prometheus0000** [comment]
See https://github.com/alkcorp/GTplusplus/issues/710. You'll have to wait for Alk to fix it.

**Comment by paroxod** [comment]
I hope the fix will be very soon, because now the production of rocket fuel is becoming very slow, and it was my only source of energy. At least then there was version 2.0.8.3.And now I do not know how to get a large amount of energy on IV tier, except for Rocketdyne ((

**Comment by chochem** [comment]
@paroxod if you have additional problems then what I wrote in my issue, please go to gt++ github (e.g. my issue that prometheus linked) and write it there.

**Comment by bombcar** [comment]
GTNewHorizons/GTplusplus#46 fixes 1 and 2 - but 3 is a different thing. It would be easy enough to remove the catalyst durability check and just run at maximum parallel if a catalyst is available.
