### ISSUE TITLE
Noncompletion bug on Quest #1431

### ISSUE THREAD

**Issue by Sirheavens** [GTNewHorizons/GT-New-Horizons-Modpack#6309]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I obtained the items (the two Filled Fuel Canister items) required for the retrieval quest, and it should mark them as completed.
#
#### What happened instead? (Attach screenshots if needed)
The quest entry remains incomplete, thus disallowing completion.
![Screenshot_7](https://user-images.githubusercontent.com/42445273/85227957-6f247b80-b41b-11ea-90ea-b1a3ceffdbd6.png)
![Screenshot_9](https://user-images.githubusercontent.com/42445273/85227958-70ee3f00-b41b-11ea-95b6-231d662a26e8.png)

Edit: After the initial attempt, the fuel canisters were run through the Name Remover. This did not solve the issue.
#
#### What do you suggest instead/what changes do you propose?
Please fix the noncompletion issue.

**Comment by Prometheus0000** [comment]
If you look at the GT++ book quests you can see that it doesn't show the metadata. I still replaced it, but it seems that not ignoring nbt was the problem somehow, since it detected filled canisters as different things.
