### ISSUE TITLE
Void miner II not working in the deep dark

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6310]
#### Which modpack version are you using?
2.0.9.0QF4
#

#### What did you try to do, and what did you expect to happen?
I placed my void miner II in the deep dark and it is running fine, it is comsuming the ogannesson gas but it is not outputting any ore. Whereas right before I had a void miner III set up in the deep dark to test it and it was mining ores.

**Comment by Prometheus0000** [comment]
Does the VM II work in other dims?

**Comment by Alexdoru** [comment]
The VM II works in other dims, before moving it to the deep dark I had one on Vega on on Pluto and one on a third planet. The three VM work as intented on those planets.

**Comment by Prometheus0000** [comment]
@bartimaeusnek I believe they're yours.

**Comment by bartimaeusnek** [comment]
yupp, but the T2 void miner is the same code as the T3, so this doesnt make any sense.. 🤔

**Comment by boubou19** [comment]
i got my T2 void miner working as intended on delta's DD with Oganesson.

**Comment by Prometheus0000** [comment]
Works perfectly fine for me as well, maybe you forgot the mining pipes?
