### ISSUE TITLE
Instability orb, binnie core crash-entity

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6312]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Open Instability Orb.
#
#### What happened instead? (Attach screenshots if needed)
Spawn entity and crash client every time.
### [client-crash](https://pastebin.com/H061KDZB)

**Comment by Prometheus0000** [comment]
See #6263
