### ISSUE TITLE
Semifluid generators not working in 2.0.9.0QF4

### ISSUE THREAD

**Issue by donoya** [GTNewHorizons/GT-New-Horizons-Modpack#6313]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### What did you try to do, and what did you expect to happen?
I tried piping creosote oil into the single block semifluid generators and even tried inserting the cell of creosote.
#
#### What happened instead? (Attach screenshots if needed)
No creosote went into the internal buffer. Also, the cell of creosote did not get consumed when put into the item slot.
#
#### What do you suggest instead/what changes do you propose?
Get the single block semifluid generators working.

**Comment by Prometheus0000** [comment]
Go bother Alk about it on the GT++ repo.
