### ISSUE TITLE
[EnderIO] Totemic Capacitor

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6314]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### Totemic Capacitor cannot be enchanted Efficiency and Unbreaking
![изображение](https://user-images.githubusercontent.com/47714084/85269174-34a0fa00-b480-11ea-973e-60fdf0efe006.png)
_I can enchant only Soulbound_
![изображение](https://user-images.githubusercontent.com/47714084/85270077-78483380-b481-11ea-8a54-a65a2dd6a83a.png)

**Comment by Petsox** [comment]
Is this behavior intended? I feel like this should be doable
