### ISSUE TITLE
no Lithium Block available for lithium bee breeding

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6315]
#### Which modpack version are you using?
2090
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
breeding Lithium bee out of salt and alu bee
#
#### What happened instead? (Attach screenshots if needed)
no lithium Block available (NEI), tested: compress dust & ingot, Block melt with fluid lithium
#
#### What do you suggest instead/what changes do you propose?
introduction of lithium block or bee breeding without block. Lithium is an early available product, why a block shouldn't that importend to block the lithium bee breeding
![Lithium_Bee_Block](https://user-images.githubusercontent.com/7759876/85273067-5fd61a00-b47d-11ea-97cc-938a77a79df3.JPG)

**Comment by Prometheus0000** [comment]
Did you try the lithium ore block?

**Comment by Ngar1** [comment]
I tried 50 times breeding with metabolic frame  -> no lithium bee

**Comment by Prometheus0000** [comment]
With the ore block or not, like I asked?

**Comment by Ngar1** [comment]
sorry, i missed the importand info

**Comment by Ngar1** [comment]
Alternativly add/change Lithium ore

**Comment by Dream-Master** [comment]
will check the recipe or add some.
