### ISSUE TITLE
GT Ruby Bee not recogniced by Gene Bank if Forestry Ruby is stored

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6319]
#### Which modpack version are you using?
2090
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
breeded ruby by redstone/diamond bee at ruby-block and analysed that genome by sequencer
#
#### What happened instead? (Attach screenshots if needed)
GT Ruby Bee was'nt recogniced
#
#### What do you suggest instead/what changes do you propose?
- recogniced ruby
- I wish, that GT Ruby has a different name, than the ruby bee from binnie/forestry

**Comment by Prometheus0000** [comment]
It's possible that the non-GT one was supposed to have been removed, but wasn't. Do they produce the same thing? I know there's 2 certus bees, but they produce different things

**Comment by Ngar1** [comment]
![ruby_bee_binnies_products](https://user-images.githubusercontent.com/7759876/85338473-a447d100-b4e2-11ea-9fbb-a43cc7d26391.JPG)

they are orign binnies bees

**Comment by Prometheus0000** [comment]
A bunch of the non-GT bees were replaced with GT bee equivalents a while ago for some reason. I'm just wondering if a bee that was supposed to be replaced wasn't by accident, and is causing this.

**Comment by Ngar1** [comment]
with Certus bee seems to have the same situation, only one type is stored.

GT Bees are not equivalent to Forestry bees, functional they are equvalent to crop. 
The best solution against overlapping would be useing different names, as in beginning of GT was done (ferrous and iron - as example)

I like Forestry/Binnies bee more, but modpack need to breed GT bees. 
GT Bees are only technical: just an material equivalent, normaly you need to breed as block under and combs do multiply crushed or.. No surprice, no special products, not realy different to crob. Binnies are more interesting.

**Comment by Ngar1** [comment]
may be related to issue: #6171

**Comment by Ngar1** [comment]
Emerald bee have also that problem, Issue #6171  isn't solved

**Comment by Ngar1** [comment]
GT Platinium bee have that problem too.

**Comment by Ngar1** [comment]
Fluix Bee the same. I will be happy, if this could be solved!

**Comment by Dream-Master** [comment]
Next updated called bee update. So we can do more about bees mechanics and by products etc.

**Comment by Ngar1** [comment]
Is not solved in version 2.1.1.0
Only one ruby bee will be recognized by Genebank.
