### ISSUE TITLE
Gooseberry Yogurt not have recipe and wrong recipe of Pineapple Yogurt

### ISSUE THREAD

**Issue by code32** [GTNewHorizons/GT-New-Horizons-Modpack#6320]
#### Which modpack version are you using?
2.0.8.6
#
#### If in multiplayer; On which server does this happen? 
private server

#
#### What did you try to do, and what did you expect to happen?
I wanted to craft Gooseberry Yogurt

#
#### What happened instead? (Attach screenshots if needed)
Gooseberry Yogurt not have recipe in NEI
Plain Yogurt + Gooseberry = Pineapple Yogurt

#
#### What do you suggest instead/what changes do you propose?
Change recipe to:
Gooseberry Yogurt = Plain Yogurt + Gooseberry
Pineapple Yogurt = Plain Yogurt + Pineapple

**Comment by GTNH-Colen** [comment]
The deception and lies of GTNH truly know no bound, this false advertising of pineapple yogurt must be stopped.

**Comment by Impos913** [comment]
Still no recipe for gooseberry yogurt in 2.0.9.0
