### ISSUE TITLE
Add a recipe for mysterious crystal (For no-rocket runs)

### ISSUE THREAD

**Issue by SampsaxD** [GTNewHorizons/GT-New-Horizons-Modpack#6321]
2.0.9.0QF4

Currently it is impossible to reach UV voltage without using a rocket, due to Neutronium, which could be acquired in ZPM using bees if Gendustry machines were available. However, these require Mutagen, of which the only component that cannot be acquired without rockets is Mysterious Crystals.

I propose adding a (expensive) LCR recipe to create Mysterious Crystals from Crystal Matrix Ingots, UUM and Space Flowers, requiring ZPM energy hatches. Something like this:
![image](https://user-images.githubusercontent.com/42840657/85400583-4efed480-b561-11ea-9bf9-efe8ad2c5c84.png)

It should be hideously energy expensive, so that the "intended" way of mining it from planets is still the preferred option.

**Comment by 0lafe** [comment]
Why are we not forcing rocket crafting again?

**Comment by SampsaxD** [comment]
Why should we?
Rocket crafting is still the easier and faster way.

This is just for extra challenge and variety.

**Comment by 0lafe** [comment]
Where's the challenge or variety though? This is the epitome of an easy/boring recipe. Crop + power = avoiding space travel lol. At 1000L that's not very much power, considering this is a zpm mat, which raises another issue. Isn't this recipe a tier before the MC rocket? T5 being fusion locked, while this is early LuV. 

Circumventing space travel, rocket fuel proc, and rocket creation for a recipe that creates the rocket unique resource from crops and power seems to neither hit the challenge aspect, nor the variety aspect. 

Maybe add some variety or challenge to the recipe if that's the goal, but crops + power isn't really a good LuV/ZPM creation option.

**Comment by SampsaxD** [comment]
Well, recipes like this https://i.imgur.com/HFT7JJn.png already exist, so it would be in line with these. Sure the voltage could be bumped up to require ZPM hatches, wouldn't matter much for the intended purpose.

You can already get to ZPM without a rocket, but it is in no way easier, faster or more optimal to do it instead of using rockets. The variety comes not from this recipe, but from enabling progression without rockets in general, while keeping these "special" recipes so expensive they are not feasible if you can choose to just use a rocket.

**Comment by Cleista** [comment]
**Suggestion:** Rework cargo rockets (because who uses them anyway?) so that they become items that you can launch from the OW and get back some amount of resources found on the target celestial body. 

This works them into the rocket fuel tiering and they can be balanced in a variety of other ways too: 
- Fuel consumption per operation (assuming rocket fuel is nontrivial to make)
- Possible delay between launch and getting back the materials (to simulate mining time)
- Resources mined per trip (so that you have to launch multiple times to get enough materials to tier up)
- Limit # of simultaneous launched rockets so that it won't compete with actually mining the celestial bodies

In addition to letting no space travel runs continue, this also makes cargo rockets a compelling option for normal players to grab a small amount of unique resources from X celestial body when they need to without having to physically go there.

**Comment by SampsaxD** [comment]
That would trivialize the "no space travel" runs, and besides, the run is a "no rocket run" where you only use materials in the four dimension available without rockets. (Atleast that is how I am doing the challenge)

**Comment by Prometheus0000** [comment]
Perhaps you mean the astro miner instead?

I don't think it's really a problem to add a recipe so long as it's much easier to do it the normal way, and you can't just use one of the recipes because you want to cop out on making a rocket temporarily. Though you still can't get draconic cores, and infinity catalyst bees are a joke (Assuming you can even get them).

**Comment by 0lafe** [comment]
What is the progression for non rocket besides you gen uu and have crops? That doesn't seem like a very interesting or challenging option in any way. 

I'd suggest giving much more to it to actually give it a real challenge, as opposed to being semi slow but simple to produce continuously. Seems like a dumb recipe imo. Rockets compared to crops and uu is just a bad set of options. It's not an interesting mechanic, it just avoids a lot of mechanics/chains. 

It seems more like you're trying to get a feature added specifically to fit your personal playthrough, with little on why this should exist in the first place. 

If you're want to avoid rockets, at least give it a decent recipe. Put some ichorium in there maybe, witchery brews maybe, or anything that isn't a crop and uu lol.

**Comment by mitchej123** [comment]
> That doesn't seem like a very interesting or challenging option in any way
That's *very* subjective, and the same could be said of your play style... "not interesting"

>It seems more like you're trying to get a feature added specifically to fit your personal playthrough, with little on why this should exist in the first place.

lolololol. pot meet kettle.

**Comment by 0lafe** [comment]
Can't quite define interest of a recipe. However this uses nothing unique, and adds almost nothing upon similar recipes. Maybe interest isn't the right word, but the simplicity of it is retarded

**Comment by mitchej123** [comment]
Same could be said of most of your suggestions.  

How about you 1) stop being rude 2) stop trying to force your playstyle on everyone else 3) If you're going to continue to respond to this thread - be productive.  

If Sampsa wants to do a no-rocket run, and we add appropriately challenging recipes to support that, how does this in any way diminish anyone else's enjoyment of the pack?

**Comment by 0lafe** [comment]
If a challenging recipe was suggested then I wouldn't be complaining. Crops and uu tho isn't challenging

**Comment by mitchej123** [comment]
So instead of insulting his play style, why not suggest a more appropriate recipe?

**Comment by SampsaxD** [comment]
Sure the Crystal Matrix could be Ichorium for all I care, as long as it's _possible_ in some form.

Crystal Matrix was just the first thing that came to mind that is related to "Mysterious Crystals"

**Comment by quedral** [comment]
I agree, more variery better. In my opinion even current grindyness of getting a crop that you want is challenging in its own way. People have kids / wife / life and have very little time to grind all that stuff. Challenge is really a subjective topic.

**Comment by Prometheus0000** [comment]
The BM blue and red crystals? Or the crystal block you make with them?

**Comment by Prometheus0000** [comment]
The recipe would go here https://github.com/GTNewHorizons/Crops-plus-plus/blob/b49117b7a7c1270b23742bc363ea3a6f5a90d93c/src/main/java/com/github/bartimaeusnek/cropspp/GTHandler/GTNHMachineRecipeLoader.java#L165
