### ISSUE TITLE
Recipe for HV circuits using luv circuit assembler is incorrect

### ISSUE THREAD

**Issue by darkpouetman** [GTNewHorizons/GT-New-Horizons-Modpack#6323]
#### Which modpack version are you using?
2.0.9.0QF4
#
#
#### What did you try to do, and what did you expect to happen?
I wanted to craft HV circuits with the luv circuit assembler recipe
#
#### What happened instead? (Attach screenshots if needed)
The recipe asks for 6 times the ressources (6 circuit boards, 6 Asoc, etc) and gives just one HV circuit.
#
#### What do you suggest instead/what changes do you propose?
Fix the recipe for the HV circuits using the luv circuit assembler

**Comment by Prometheus0000** [comment]
Intended, read the quests properly or do a search.
