### ISSUE TITLE
[Elecrticity] Recipes have negative eu/t values

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6327]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
### Some recipes began to have negative eu/t values
For example:
![изображение](https://user-images.githubusercontent.com/47714084/85594208-65378e00-b650-11ea-8f9d-17baed615f17.png)
![изображение](https://user-images.githubusercontent.com/47714084/85594334-839d8980-b650-11ea-8e73-4128bc75fda2.png)

**Comment by GTNH-Colen** [comment]
Well that's interesting, looks like an Alk problem though from the machines so might wanna report it to the GT++ repo.

**Comment by bartimaeusnek** [comment]
go bother alk on his git with this please https://github.com/alkcorp/GTplusplus/issues

**Comment by Prometheus0000** [comment]
Already reported: https://github.com/alkcorp/GTplusplus/issues/714
Alk said it was visual only.

**Comment by interestingusernam3** [comment]
Finally, GT+++

**Comment by Dream-Master** [comment]
Not fixed

**Comment by YannickMG** [comment]
These appear to have been fixed by now on 2.1.2.0.
![image](https://user-images.githubusercontent.com/5321549/147797725-8de71c31-9c7a-491a-96a8-ffd2fbfcc628.png)
![image](https://user-images.githubusercontent.com/5321549/147797666-326650db-bfbe-4718-899a-73ad0925a8f4.png)
