### ISSUE TITLE
Endless Iron duplication Glitch/Bug finding 

### ISSUE THREAD

**Issue by Emorgaly** [GTNewHorizons/GT-New-Horizons-Modpack#6328]
#### Which modpack version are you using?
2.0.8.3

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
I found it while completing the quests.
Quest
![image](https://user-images.githubusercontent.com/58056709/85624752-a9d02300-b66a-11ea-8c54-6423d1ae424b.png)
#
#### What happened instead? (Attach screenshots if needed)
initial situation
![image](https://user-images.githubusercontent.com/58056709/85624897-e69c1a00-b66a-11ea-8761-00bf8608e913.png)

Crafting 
![image](https://user-images.githubusercontent.com/58056709/85624950-fca9da80-b66a-11ea-9817-6094d25d1943.png)

Result 
![image](https://user-images.githubusercontent.com/58056709/85625026-164b2200-b66b-11ea-9e3e-ddea87877618.png)
as one Bucked (ID:326) came 2 Bucket (ID:325)

result in 12 Sec => 16 Bucket (ID:325) => 48 Iron Ingot => BUG/GLITCH 
![image](https://user-images.githubusercontent.com/58056709/85625441-c02aae80-b66b-11ea-870d-ab6745eb670c.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it, place.

**Comment by Anarack** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5727 or
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6256
Known issue seems no one has had much luck fixing it

**Comment by Emorgaly** [comment]
i have updatet the madpack the last days.

**Comment by Emorgaly** [comment]
![image](https://user-images.githubusercontent.com/58056709/85630065-4dbdcc80-b673-11ea-9826-589d34dc5dba.png)

**Comment by Prometheus0000** [comment]
Don't make new issues, comment on existing ones. And always search to see if there is an existing one first.
