### ISSUE TITLE
Ganymed bee

### ISSUE THREAD

**Issue by nom457** [GTNewHorizons/GT-New-Horizons-Modpack#6334]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
Singleplayer

Is it ok that ganymed and jupiter bees make a boat? Shouldn't be Ganymede stone Dust?
![1e](https://user-images.githubusercontent.com/60323607/85905276-a75cfd00-b813-11ea-95fd-df1a8116133e.png)
![2e](https://user-images.githubusercontent.com/60323607/85905286-af1ca180-b813-11ea-8f90-e669df945728.png)

**Comment by Dream-Master** [comment]
Yea this dust item was changed and maybe now it display a wrong item. Will fix it.

**Comment by interestingusernam3** [comment]
Boat bee
