### ISSUE TITLE
Using a void jar on an essentia storage bus displays voided essentia in the terminal.

### ISSUE THREAD

**Issue by Darkstar1712** [GTNewHorizons/GT-New-Horizons-Modpack#6335]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
When a void jar is placed on an essentia storage bus, it seems to be displaying the voided essentia in the essentia terminal.

![Storage](https://user-images.githubusercontent.com/34458535/85929237-1cc7dc80-b8ab-11ea-81ed-101d2a83d0c5.png)
![terminal](https://user-images.githubusercontent.com/34458535/85929236-1a658280-b8ab-11ea-802c-b641e33b1fce.png)

As you see there's 8192 essentia in the cell and theres also another 64 in the jar but the terminal is showing more than that, it keeps going up as more essentia is distilled. 

It's only visual, it isn't actually storing extra essentia, replacing the jar makes it show the correct amount.

**Comment by berta24** [comment]
![image](https://user-images.githubusercontent.com/25983005/147714503-2cc42975-d757-42b5-8d48-d250c4f9b8e6.png)

![image](https://user-images.githubusercontent.com/25983005/147714515-e2068a1d-970a-4f99-902e-63b6a53b518e.png)

Bug still there in 2.1.2.0
