### ISSUE TITLE
Illuminated Scribing Tools cannot be refilled

### ISSUE THREAD

**Issue by Cleista** [GTNewHorizons/GT-New-Horizons-Modpack#6340]
#### Which modpack version are you using?
2.0.9.0QF4

#
#### If in multiplayer; On which server does this happen? 
Personal server

#
#### What did you try to do, and what did you expect to happen?
Attempt to refill Illuminated Scribing Tools

#
#### What happened instead? (Attach screenshots if needed)
[Recipe does not register](https://cdn.discordapp.com/attachments/181078474394566657/726968318858362910/unknown.png)

Common problem [reported](https://discordapp.com/channels/181078474394566657/234936569360809996/710500253551296585) [multiple](https://discordapp.com/channels/181078474394566657/181078474394566657/711618487310745680) [times](https://discordapp.com/channels/181078474394566657/234936569360809996/582791829175533578) by people in GTNH Discord

#
#### What do you suggest instead/what changes do you propose?
Fix arcane worktable refilling recipe or if not possible, let us do it with molten glowstone and small pile of gold in an assembler.

**Comment by repo-alt** [comment]
I don't see where the crafting recipe for the tools is changed. It can hardly be an original recipe, since it uses TF Magic Map Focus.
Probably refilling recipe is deleted there.

**Comment by repo-alt** [comment]
@bartimaeusnek You are probably the person who may fix that with the least efforts.

**Comment by Prometheus0000** [comment]
@bartimaeusnek

**Comment by Gateswong** [comment]
This is still not being fixed as of ver 2.1.2.1

![image](https://user-images.githubusercontent.com/2586057/150615128-4fa23597-7b49-4559-a87a-d3c37a306e9f.png)
