### ISSUE TITLE
Banana Milkshake name spelt wrong

### ISSUE THREAD

**Issue by Regian24** [GTNewHorizons/GT-New-Horizons-Modpack#6342]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
SinglePlayer
#
#### What did you try to do, and what did you expect to happen?
I got a Banana Milkshake from a Lootbag, expecting it to be named Banana Milkshake 
#
#### What happened instead? (Attach screenshots if needed)
It's named Banana Milkeshake
#
#### What do you suggest instead/what changes do you propose?
Change the name

**Comment by interestingusernam3** [comment]
Wh're is the problem? t's madeth from milke

**Comment by Prometheus0000** [comment]
https://www.merriam-webster.com/dictionary/milkshake There's no e in milk.
