### ISSUE TITLE
Ichorium research prerequisites broken

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#6343]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Ichorium research is not accessible, although /iskamiunlocked returns "yes"
I also have all vanilla Thaumcraft and TT researched

**Comment by repo-alt** [comment]
Apparently now in addition to Vanilla & TT you need "Node Catalyzation" & "Thaumium Reinforced Jars"

**Comment by chochem** [comment]
compare some of the discussion in here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6008
not that it solved anything, this new ticket is certainly warranted.

**Comment by viljar290** [comment]
can add to it that for me I also needed all the metal transmutations researched. ontop of ichor jar

**Comment by Dream-Master** [comment]
it's broken because script recipes not checking this command.

**Comment by chochem** [comment]
dream, if you mean the iskamiunlocked command. From what I can tell that has nothing to do with the issue even though repo mentioned it. kami is not the problem, kami unlocks just fine giving you access to ichor. However Ichorium (the ingot) has all kinds of extra requirements in 9.0 and nobody seems to know what they are exactly or why that has changed.

**Comment by Aggadahr** [comment]
the command /iskamiunlocked is still useless in the latest official version (Im playing on epsi)
![javaw_2021-07-20_16-10-27](https://user-images.githubusercontent.com/46688121/126357011-26ff9cc0-8896-4d3b-95e0-1cced60f6f3e.png)
![javaw_2021-07-20_15-22-08](https://user-images.githubusercontent.com/46688121/126357027-e064dcdc-bc17-44ee-a71a-c09abaac1eec.png)
i even copied the thaumonomicon from a player who got ichor unlocked, but to no avail

**Comment by joshaup1999** [comment]
This is still an ongoing issue. From what i've seen all Base thaum and TT research is required (Including elemental fire, the seeds and potions) People get getting confused on what the pre req is for Ichorium. I had all research done and still didnt have it. It took researching Ichor Cloth to unlock Ichorium for some unknown reason even when they should be unlocked together. Either a message needs to be noted in the questbook stating ALL research from base thaum plus TT is required even if the /iskamiunlocked command says otherwise

**Comment by PolkageistHS** [comment]
So I figured out why it's doing this:  TT only lists researches that have have parents and aren't triggered by scanning certain aspects, items, or mobs.  

https://github.com/GTNewHorizons/ThaumicTinkerer/blob/1.7-final/src/main/java/thaumic/tinkerer/common/research/KamiResearchItem.java#L52-L55

This means that some researches weren't showing up, such as Thaumostatic Girdle (scan anything with Volatus) or Brain in a Jar (scan an Angry Zombie), in the /iskamiunlocked command.  I'll fix this along with the Ichorium research dependency when I convert all the recipes over from scripts to the mod itself.

**Comment by Dream-Master** [comment]
sure recipe lay in Minetweaker script not detected. If they in code make things more easy.
