### ISSUE TITLE
Storage drawers crash

### ISSUE THREAD

**Issue by I3lackI3rains** [GTNewHorizons/GT-New-Horizons-Modpack#6344]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
single
#
#### What did you try to do, and what did you expect to happen?
I was using storage drawers and game crashed
#
#### What happened instead? (Attach screenshots if needed)
-
#
#### What do you suggest instead/what changes do you propose?
If it is possible fix it in future updates

**Comment by boubou19** [comment]
looks like it's related to inventory tweak only.

**Comment by leagris** [comment]
Disable the auto-refill from inventory tweak. It is very broken.
