### ISSUE TITLE
new thaumium and ichorium jars(kekztech)

### ISSUE THREAD

**Issue by faqza** [GTNewHorizons/GT-New-Horizons-Modpack#6346]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
I've tried to move essentia to/from these jars using essentia export, import and storage buses.
#
#### What happened instead? (Attach screenshots if needed)
All these buses couldn't see these jars and interract with them. Also, attaching essentia storage/export/import bus to these kekztech void jars causes a crash.
[crash-2020-06-30_12.36.45-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4850137/crash-2020-06-30_12.36.45-server.txt)

#
#### What do you suggest instead/what changes do you propose?
Fix these jars

**Comment by aka13-404** [comment]
Ichor Jars still can not be interacted with via storage, import or export busses in 2.7.4
Really wanted to use those for passive essentia storage without having to worry about overflow.
<img width="1740" height="1191" alt="Image" src="https://github.com/user-attachments/assets/8fed62ea-c6c7-4d73-b29a-e842a4a5de29" />

**Comment by chochem** [comment]
bad bot. that is unrelated to the ticket.
