### ISSUE TITLE
[GT++] Tantalloy-61

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6347]
#### Which modpack version are you using?
2.0.9.4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### 2 identical recipes with different consumption
![изображение](https://user-images.githubusercontent.com/47714084/86168363-cc59b480-bb20-11ea-9b64-951839108f14.png)
![изображение](https://user-images.githubusercontent.com/47714084/86168392-d5e31c80-bb20-11ea-94de-5d745a582903.png)

**Comment by Dream-Master** [comment]
@draknyte1 any idea ?
