### ISSUE TITLE
[GT++] Mixing Machine

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6348]
#### Which modpack version are you using?
2.0.9.4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### Tips says: 16 Multi-Use casing at least
![изображение](https://user-images.githubusercontent.com/47714084/86173302-738e1a00-bb28-11ea-87a2-e085d24bed65.png)
### But it working, if use ONLY input buses.
![изображение](https://user-images.githubusercontent.com/47714084/86173548-d089d000-bb28-11ea-8f45-ed813d407a52.png)

**Comment by Prometheus0000** [comment]
Already reported https://github.com/alkcorp/GTplusplus/issues/664

**Comment by Dream-Master** [comment]
Not fixed
