### ISSUE TITLE
Betterquesting, Thaumcraft and Baubles

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#6351]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
Private MP (Forge)
#
#### What did you try to do, and what did you expect to happen?
After updating the assembly, each cycle of recording information (about 30 seconds?) to the disk from the mods indicated in the title to not decent values. It also draws TPS from 6 to 18 during operations. Please fix it.
[https://cdn.discordapp.com/attachments/506377144520146953/727492869543297124/unknown.png](url)
[https://cdn.discordapp.com/attachments/716493760879394816/727537127243382976/unknown.png](url)
[https://cdn.discordapp.com/attachments/716493760879394816/727530284383338516/unknown.png](url)
#

**Comment by PredVesTNiK2142** [comment]
I checked on Thermos - the problem is exactly the same. Only the load is 2 times higher than this.

**Comment by PredVesTNiK2142** [comment]
Checked all the mods from the update. Failed to test only mods:
-Bartworks 0.5.13.1 (breaks server and client)
-CoreMod 1.6.46 (do not work because of Bartworks)
-Gregtech 5.09.33.52 (do not work because of Bartworks)
-Kekztech 0.4.6 (do not work because of Bartworks)
-TecTech 3.8.3 (do not work because of Bartworks)

The rest of the mods do not affect the problem. She still shows up. It seems that you need to dig towards these 5 mods. @Dream-Master Can someone still tackle the problem?
We want to play at 9.0 but this is not possible due to this problem. Now they are forced to return to 8.8 as the last stable one.

**Comment by Methes** [comment]
Judging by the screens posted you have additional mods installed, Opis at the least. You also opened a bunch of other issues suggesting there's something wrong with your server setup.
Have you tried the obvious thing - make a fresh installation of barebones forge 2.0.9.0QF4 without your additional stuff, with a brand new world, connect a player and use /xu_tps clientside to see if that issue still persist?
Cause noone's going to bother with your assumed modified setup without concrete details.

**Comment by PredVesTNiK2142** [comment]
I repeat the same as in previous tickets - I conduct all tests on a clean build with the addition of Opis and / or Tickprofiler. Now for a week I conducted tests on 3 different server cores. Everywhere the same thing. Version 8.8 is stable everywhere. Version 9.0 ... I no longer have normal words on it.

**Comment by Methes** [comment]
Alright. Then zip your entire clean (but still faulty) 2.0.9.0 server folder somewhere (preferably google drive), I'll download it and try it. If it's ok on my end (as 2.0.9.0 is for me and for almost everybody), you probably have issues not related to the game but to your hosting PC (CPU/HDD bottleneck perhaps?).

**Comment by PredVesTNiK2142** [comment]
I have checked the possibility of bottlenecks in the server configuration for a long time. Including not on one host. The problem is not in the server 100%
Regarding a clean build, you don’t know the link to UltraMine. Everything else is with [http://downloads.gtnewhorizons.com/ServerPacks/](url). Unzipped and launched. What could be unclean here?

**Comment by Prometheus0000** [comment]
I don't know how to setup a server, but assuming it works the same, you delete the old folders that are going to be replaced first so there's no conflicts. Did you remember to do that?

**Comment by PredVesTNiK2142** [comment]
For tests, I set the original 9.0 without any changes and additions. Just unzipped and launched.

Для тестов ставил оригинальную 9.0 без каких либо изменений и дополнений. Просто разархивировал и запустил.
