### ISSUE TITLE
Forestry worktable

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#6352]
#### Which modpack version are you using?
2.0.8.8 and 2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
Private MP(Forge)
#
#### What did you try to do, and what did you expect to happen?
When trying to craft in the worktable, some of the players crashed on completely different recipes. And it happens that on the same recipes and does not crash. It is impossible to track and reproduce stably. The problem is observed both on the Technic launcher and on the MMC.
[https://pastebin.com/Y32Le62K](url)
#

**Comment by boubou19** [comment]
an attempt to fix that was made in #5486, but looks like adventure backpacks has the same issue

**Comment by sema1011** [comment]
The same problem occured. When using a workbench from forestry. When crafting tin rings

https://pastebin.com/fcNdGbiK

**Comment by Prometheus0000** [comment]
Still happening?
