### ISSUE TITLE
Crafting mud balls duplicates buckets 

### ISSUE THREAD

**Issue by 909-xdd** [GTNewHorizons/GT-New-Horizons-Modpack#6354]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
single player world
#
#### What did you try to do, and what did you expect to happen?
I tried to craft mud balls with water bucket and dirt.
#
#### What happened instead? (Attach screenshots if needed)
The mud balls got crafted but I got an extra bucket after.
#

**Comment by chochem** [comment]
Duplicate.
Please use the search function next time. there is like 5 tickets already for this. For example https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6256.
