### ISSUE TITLE
GregTech machines energy slot

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6357]
#### Which modpack version are you using?
2.0.9.0

#
#### If in multiplayer; On which server does this happen? 
Prospercraft

#
#### What did you try to do, and what did you expect to happen?
Using batteries in gregtech machines like assembly machines should just act as backup power
Also been using the energy slot to store spare circuits for later use

#
#### What happened instead? (Attach screenshots if needed)

Placing a spare circuit in the slot for use later causes the tick rate increase shown on the included image.

![image](https://user-images.githubusercontent.com/3405825/86501682-6af14a00-bd9b-11ea-8134-9037ad854e77.png)

The top one of the list "BaseMetaTitleEntity 20359.63.-16089:0" was an IV assembly machine in my base that had a spare circuit stored in the energy slot, after removal there was no issue. 

I had two HV assembly machines that had similar issues and showed up on the lag board, they both had a hv energy crystal in them, after removal, they disappeared off the lag board.

Just wondering why even storing a circuit in that slot causes high tick rate time in "tick profiler"

#
#### What do you suggest instead/what changes do you propose?
Check if there is a bug with checking if anything is in the slot or what is in the slot. as it causes tick rate issues

**Comment by Cleista** [comment]
Can confirm this also occurs on my server. 2.0.9.0QF4, forge server, using official server zip with no modifications except for adding AromaBackup (which was not included for some reason).

**Comment by draknyte1** [comment]
> AromaBackup (which was not included for some reason)

Not our job to provide Aroma it a backup solution. That’s on the user. 

As for the tick time, the slot is constantly checked for the presence of batteries to charge/discharge. Probably doesn’t need to be as frequent, but also kinda does.
