### ISSUE TITLE
typesetting table, goes into the negative.

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6358]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft and single player
#
#### What did you try to do, and what did you expect to happen?
Was using the typesetting table to make copys of enchanted books (soulbound and fortune III)

#
#### What happened instead? (Attach screenshots if needed)
When using the typesetting table, and it runs out of print press chase (9379), it will remove the chase from display of the typesetter and keep making new finished enchanted plates and using the holo glasses the typesetting table will show a negative amount of print press chase's as shown in the included image.
![image](https://user-images.githubusercontent.com/3405825/86511078-e97ad580-bdf5-11ea-8b5b-0b28a45d6a55.png)
Image is a single player test, where test was preformed with /gamemode 0
#
#### What do you suggest instead/what changes do you propose?
Make the typesetting table stop producing enchanted plates when it runs out of chases

**Comment by chochem** [comment]
this bug is many years old and is not GTNH specific. Afaik we dont have access to bibliocraft, so I would guess probably no way to fix it.

**Comment by repo-alt** [comment]
Bibliocraft is closed source, and the author was not heard from for a year already.

**Comment by Dream-Master** [comment]
fix via reflection possible @repo-alt ?

**Comment by repo-alt** [comment]
Everything is possible, but, seriously, is it worth the trouble?

**Comment by Dream-Master** [comment]
maybe not we have other issues more important.
