### ISSUE TITLE
Refined platinum salt dust not responsed by Type Filter

### ISSUE THREAD

**Issue by VasyaOrk** [GTNewHorizons/GT-New-Horizons-Modpack#6359]
#### Which modpack version are you using?
9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Singleplayer, separate client and server on same machine
#
#### What did you try to do, and what did you expect to happen?
Try filter Refined Platinum Salt Dust with LV Type Filter (like any another dusts)
#
#### What happened instead? (Attach screenshots if needed)
Type Filter not accepted Refined Platinum Salt Dust (but accepted copper dust)
#

**Comment by Cleista** [comment]
BartWorks dust uses the `dustRefined` prefix.

**Comment by Prometheus0000** [comment]
So, not a bug then?
