### ISSUE TITLE
BetterQuesting

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#6360]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
Private server (Forge)
#
#### What did you try to do, and what did you expect to happen?
In the Revards tab, bags are counted only 1 time. After which the quest is not reset.

Also, they still have not fixed the bug with timers in quests. As before, there is a countdown in the opposite direction with a negative value.
#

**Comment by Prometheus0000** [comment]
Which ones?
