### ISSUE TITLE
Terrawart won't be recognized by Spice of Life's extra hearts system

### ISSUE THREAD

**Issue by glowredman** [GTNewHorizons/GT-New-Horizons-Modpack#6362]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
The Terrawart's tooltip states that it can be used to gain extra hearts ("_Not yet eaten! What does it taste like?_"). After eating it it should state "_Eaten: Assisted in adding hearts_" instead.
#
#### What happened instead? (Attach screenshots if needed)
It still states "_Not yet eaten! What does it taste like?_". I can't tell if it counted towards the next heart and if so, if it counts towards the next heart every time.

**Comment by boubou19** [comment]
it's deeper than that, you can eat infinite amount of terra wart so looks like spice of life fails to detect this item. Also, ic² filled tin can aren't detected by spice of life at all.

**Comment by BritishCynic** [comment]
This issue is still outstanding and I think it's worthy of still being looked into.

**Comment by BritishCynic** [comment]
In addition, Terra Wart does not restore hunger at all.

**Comment by cubic-chariot** [comment]
I thought that this was intentional, because Terra Wart cures debuffs, so this allows us to keep continuously eating Terra Warts (e.g. when fighting the Wither). Another food item that could benefit from such explicit exclusion would be Pam's Ignis Fruit, which essentially is a short-duration steam-age fire resistance potion.

**Comment by Alastors** [comment]
I don't think this is ever gonna get fixed @mitchej123 should we move to reclose?
