### ISSUE TITLE
GT++

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#6363]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
Private server (Forge)
#
#### What did you try to do, and what did you expect to happen?
GT ++ multiblocks(freezer and volcanus) when auto maintence hatch is installed in the on state can instantly consume all resources for fixing. They also consume resources for fixing in the off state.
#

**Comment by Prometheus0000** [comment]
You should report at the GT++ and/or Tectech repo.
