### ISSUE TITLE
Space

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#6364]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
Private server (Forge)
#
#### What did you try to do, and what did you expect to happen?
After the upgrade, all planets are not available except overworld for rocket flights. Teleporting through the admin panel is easy (except for the team of the mod itself, it also shows that all the planets are inaccessible)

P.S. I am only interested in how the pre-alpha version of the update with a huge bunch of critical bugs was in the release ???
#

**Comment by chochem** [comment]
everybody else is able to go to all the planets. this is just you. so it would be helpful if you could describe your concrete issue in more detail.

**Comment by boubou19** [comment]
try to clean the config folder and make a fresh install, it may help you.

**Comment by PredVesTNiK2142** [comment]
> everybody else is able to go to all the planets. this is just you. so it would be helpful if you could describe your exact issue in more detail.

I'm not alone, but the whole server cannot.




> try to clean the config folder and make a fresh install, it may help you.

For several hours now I’ve been fighting this ... resetting the configs did not help.

**Comment by PredVesTNiK2142** [comment]
For details - updated from 8.8 to 9.0 and hello a bunch of crits - errors - TPS loss.

**Comment by chochem** [comment]
yeah that sounds like your server installation is messed up somehow.

**Comment by PredVesTNiK2142** [comment]
> yeah that sounds like your server installation is messed up somehow.

There would be a problem only in the server or map. Problems all manifest themselves on different nuclei and on pure worlds. And even in the single (only here the space in the single works fine)

**Comment by chochem** [comment]
well it doesn't help that you are not providing any details. your are the only one who has mentioned anything about 'critical' bugs sofar, nobody else but you and your group had any serious problems. If you want help you need to post the errors in question, crash logs, recent logs, any info you got really.

**Comment by PredVesTNiK2142** [comment]
> well it doesn't help that you are not providing any details. your are the only one who has mentioned anything about 'critical' bugs sofar, nobody else but you and your group had any serious problems. If you want help you need to post the errors in question, crash logs, recent logs, any info you got really.

What details do you expect? If in space - there are no logs and errors other than the red launch button. If the rest of the tickets - there is provided all the available information. If according to actions - I just described as detailed as possible. We play on a clean build. Only admin plugins and sethome are added. What else is needed ?!

**Comment by chochem** [comment]
> What details do you expect? 

about the 'bunch of crit errors' you mentioned obviously. or was that just a misunderstanding?


On the space part, just to be sure: what fuel are you using? the fuels got a major overhaul. Though if that was the problem you would get the 'too low quality' message and you would have mentioned that. I just want to make sure its not something easy like that. :P

**Comment by boubou19** [comment]
> (only here the space in the single works fine)

single player is just a multiplayer instance launched in local, so it's definitely the server fault. what you can do is upload a map that works fine in SP on the server and see if it solves the issue.

**Comment by PredVesTNiK2142** [comment]
> > What details do you expect?
> 
> about the 'bunch of crit errors' you mentioned obviously. or was that just a misunderstanding?
> 
> On the space part, just to be sure: what fuel are you using? the fuels got a major overhaul. Though if that was the problem you would get the 'too low quality' message and you would have mentioned that. I just want to make sure its not something easy like that. :P

All that is important and cannot be tolerated is already written in tickets.
Across space - creative rocket and admin team eat fuel too? Checked already in all available ways. And on all 8 shooting ranges of missiles.

**Comment by chochem** [comment]
> All that is important and cannot be tolerated is already written in tickets.

so no critical errors then like you mentioned earlier?

> Across space - creative rocket and admin team eat fuel too? Checked already in all available ways. And on all 8 shooting ranges of missiles.

If you are not able to answer a simple question like 'what fuel?' then I dont think me or anybody can help you really ¯\_(ツ)_/¯

**Comment by repo-alt** [comment]
(He probably means the other issues filed by him earlier (look up, they are at the top). I see a bit of language barrier issue here, @chochem)

**Comment by PredVesTNiK2142** [comment]
> (He probably means the other issues filed by him earlier (look up, they are at the top). I see a bit of language barrier issue here, @chochem)

Really. Google translates poorly most often

**Comment by chochem** [comment]
yeah the language barrier is obvious ;). I had better success with deepl than google. But improving English skills is the optimal long term solution in many ways 📦 

Looks like the other issues are minor or not 9.0 related (still good to make issues). I guess this one https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6351 sounds more serious but I dont really understand it either.

I still want to know what fuels you tried to use. Its just the most obvious thing to check if this is a new problem for you on 9.0: diesel? cetane boosted? rp1? ...

**Comment by PredVesTNiK2142** [comment]
Of course, on the rocket ranges. Otherwise, they are not flooded. Also creative rockets and / dimensiontp

**Comment by chochem** [comment]
again not an answer to the question. but at least some more info, so a dimensional tp is not working either? the dimensions just straight-up dont generate/exist or what exactly happens? then this has nothing to do with rockets but is a much more fundamental problem. are only GC dimensions affected or also other dimensions? Either way that sounds like you should do a complete reinstall.

**Comment by chochem** [comment]
btw, when you say dimensional tp, do you mean /cofh tpx (which is the one I would use/recommend) or something else?

**Comment by boubou19** [comment]
you could try to spawn in a GT teleporter, that works too.

**Comment by PredVesTNiK2142** [comment]
I repeat the same thing over and over again... All the fuel - all the rocket - dimensiontp - don't work. The launch button is inactive and lights up red. You can only move to overworld. A new world has been created. Tried 3 server cores. I tried the single. It's where the space works.

The teleport is working through the admin commands. Worlds exist and work.

**Comment by boubou19** [comment]
did you uploaded a map generated in singleplayer on the server?

**Comment by PredVesTNiK2142** [comment]
> did you uploaded a map generated in singleplayer on the server?

I can't yet. We've lost the Internet on our host. If it doesn't show up soon, I'll pick it up at my place and check it out.

**Comment by chochem** [comment]
we at least we narrowed down the issue a bit despite translation barrier. Not sure how to fix it though if a reinstall didn't help. Keep in mind your server is the only one affected, so try to think about the stuff that you might be doing differently.

**Comment by PredVesTNiK2142** [comment]
All that was done was remove the mods config scripts folders from 8.8 and copy everything from 9.0. BugTorch was also removed due to the breakage of Opis mods.

**Comment by Viktor-KN** [comment]
U mentioned that use some admin plugins... you running Thermos? What plugins is installed?

**Comment by PredVesTNiK2142** [comment]
Actually, we have a server on our UM. Thermos and Forge test without plug-ins.

**Comment by PredVesTNiK2142** [comment]
> did you uploaded a map generated in singleplayer on the server?

work

**Comment by PredVesTNiK2142** [comment]
I discovered that if you do not specify additional rules for loading or creating worlds, then all the planets are available. And this only appears in 9.0. In 8.8, everything works fine.

**Comment by chochem** [comment]
So to summarize: its was not just a 'clean build' as you repeat everywhere, but you messed with stuff and that caused problems. correct?

**Comment by repo-alt** [comment]
Abrasive comments aside, what rules these were? So that no one else would step on that in the future

**Comment by PredVesTNiK2142** [comment]
> So to summarize: its was not just a 'clean build' as you repeat everywhere, but you messed with stuff and that caused problems. correct?

On the contrary. After installing the configs with 8.8 (accidentally threw the wrong ones during the tests), everything worked. But with configs 9.0 no.

**Comment by PredVesTNiK2142** [comment]
> Abrasive comments aside, what rules these were? So that no one else would step on that in the future

I already have no idea what is in this version and what is wrong. We just left on 8.8 and stopped spoiling our nerves. I especially like that they stubbornly pretend that there are no problems. You put everything under the net - and here he is a heap of everything.

**Comment by Prometheus0000** [comment]
That's probably because it works for other people, so it suggests that your setup is wrong/messed up/etc somehow.

**Comment by boubou19** [comment]
Do you still confirm that uploading a map from single player to your server works? or did it worked because you used accidentally 2.0.8.8

**Comment by PredVesTNiK2142** [comment]
> Do you still confirm that uploading a map from single player to your server works? or did it worked because you used accidentally used 2.0.8.8 config?

Yes, the single worked. And with the replacement of configs, it also worked

**Comment by PredVesTNiK2142** [comment]
> That's probably because it works for other people, so it suggests that your setup is wrong/messed up/etc somehow.

What can be done without unpacking the official archive and running without any changes?

**Comment by repo-alt** [comment]
Google translate obviously failed with the last comment. Can you perhaps post both translated and original replies? (about half of the ppl here can understand russian I think) (Реально нифига не понятно)

**Comment by PredVesTNiK2142** [comment]
Я уж думал наших нет в команде. По последним комментам:
1. И сингл мир работает на сервере. И конфиги от 8.8.
2. Как можно что то поломать при просто распаковывании офф архива и запуск что форджа что термоса без изменений? (да и УМ так же)
@repo-alt можно как то через тебя информацию передавать? А то меня этот цирк с переводчиком уже конкретно достал.

**Comment by repo-alt** [comment]
Ну, чудес не бывает, тех симптомов что ты описываешь, никто больше не описвает. Может с железом что.
Т.е., итого: когда 
1. ставится последняя версия в чистый каталог на сервере, 
2. настраивается как описано https://www.gtnewhorizons.com/wiki/m/41469370/page/Server_Setup
3. создаётся новый мир
4. ракеты не работают, (тут уточнение - даже T1 c нитродизелем не летит на луну?)  (скрины не помешают)

**Comment by PredVesTNiK2142** [comment]
Железо исключено точно. Проверено на нескольких хостах и на простых компах.

Ракеты и командой мода спокойно выводится в режим выбора планеты. Только вот все планеты кроме овера заблокированы (кнопка лаунча горит красным). 
Через тп админкой спокойно на все планеты перемещаешься. Они нормально работают.
Если закинуть сингл мир - все работает. Если откатить конфиги на 8.8 - все работает. В случае с УМ если дополнительно прописать настройки на миры - с ванильными работает а с измененными нет.

**Comment by repo-alt** [comment]
Ну смотри, если ты говоришь что "Если откатить конфиги на 8.8 - все работает.", то банально делением пополам можно найти виноватый конфиг, и уже его внимательно рассмотреть. (Понятно что прежде чем делить пополам можно попробовать откатить только GalacticCraft config)

**Comment by Viktor-KN** [comment]
Все галактикрафтовские миры должны быть постоянно загружены на сервере (cauldron.yml для термоса keep-world-loaded: true) . Если используете multiverse или что-то подобное, ни в коем случае эти миры туда не добавлять.

**Comment by PredVesTNiK2142** [comment]
> Все галактикрафтовские миры должны быть постоянно загружены на сервере (cauldron.yml для термоса keep-world-loaded: true) . Если используете multiverse или что-то подобное, ни в коем случае эти миры туда не добавлять.

Кстати действительно видел в логах упоминание что миры не были загружены при запуске сервера на термосе(если использовать вариант с офф архива). На фордже такого не видел. На УМ все миры загружаются и держаться в подгрузке.
По идее если на термосе этот баг зависит от того загружен мир или нет - то тоже наврятли. Мир все равно оставался недоступен если кто то находился в нем.

**Comment by PredVesTNiK2142** [comment]
> Ну смотри, если ты говоришь что "Если откатить конфиги на 8.8 - все работает.", то банально делением пополам можно найти виноватый конфиг, и уже его внимательно рассмотреть. (Понятно что прежде чем делить пополам можно попробовать откатить только GalacticCraft config)

Есть подозрение что не совсем конфиг виноват а слияние кора с модом

**Comment by Prometheus0000** [comment]
Old, reopen if it still happens.
