### ISSUE TITLE
Suggestion: full hazmat protection to bound armor and awakened ichorium armor

### ISSUE THREAD

**Issue by faqza** [GTNewHorizons/GT-New-Horizons-Modpack#6366]
#### Which modpack version are you using?
2.0.9.0
#
As for awakened ichorium armor, it is luv tier armor like shadow fortress and primordial armor.  I suggest adding full hazmat protection property awakened ichorium armor.
#
As for bound armor, I suggest adding full hazmat protection property to each piece of armor with demon blood shard or archmage blood orb in it.

**Comment by draknyte1** [comment]
Suggest here. 
https://github.com/alkcorp/GTplusplus/issues/590

Awakened Ichorium was buggy with hazmat protection, so it’s currently disabled.
