### ISSUE TITLE
Cleanroom randomly loses all efficiency

### ISSUE THREAD

**Issue by TimNagle0** [GTNewHorizons/GT-New-Horizons-Modpack#6367]
#### Which modpack version are you using?
2.0.8.8
#

#### What did you try to do, and what did you expect to happen?
I just set up my cleanroom for the first time, completed one recipe in my circuit assembler (at 100%) and then the efficiency dropped to zero and wasn't recharging. 
#
#### What happened instead? (Attach screenshots if needed)
I tried to hit it with a soft mallet and it gets going again until about 4% and then drops to zero again and turns off. The cleanroom is correctly formed and working properly according to the tooltip and I'm powering it with a dedicated mv combustion engine so I don't think power is the problem either.
#

**Comment by boubou19** [comment]
try putting 2A on the energy hatch, maybe that's the issue.

**Comment by repo-alt** [comment]
Cleanroom eats more that 1A LV while gaining effficiency. When at 100% efficiency it eats 4 eu/t. In general it is safer/easier to use MV energy hatch.

**Comment by chochem** [comment]
it says MV in the post folks, not LV.

Does it have maintenance issues maybe? also definitely double check the power and make sure to close (or not use) the door.

Generally I would say such a topic is much better suited for the discord help channel than github as a hint for next time.

**Comment by boubou19** [comment]
also make sur to build it in a single chunk

**Comment by TimNagle0** [comment]
Hey all, thanks for the advice, I figured it out, it was functioning properly on 1A MV but when I used the circuit assembler (which draws power from the same generator) it didn't get enough power anymore or something and switching to 2A fixed it.
