### ISSUE TITLE
Talisman of Nourishment doesn't work

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6368]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
I crafted a Talisman of Nourishment and put it in a hotbar with food
#
#### What happened instead? (Attach screenshots if needed)
Talisman of Nourishment eats the food in hotbar and fills the food(Apple etc..) counter, but don't eat.
#
#### What do you suggest instead/what changes do you propose?
Fix it.
According to the following original issue(https://github.com/Flaxbeard/Thaumic_Exploration/issues/22) there isn't much food to work with when HungerOverhaul is installed.

**Comment by Dream-Master** [comment]
we have the source so we need to found someone who can fix it.
