### ISSUE TITLE
[Better Quest] Witchery Quest Quartz Sphere

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6369]
#### Which modpack version are you using?
2.0.9.4
#
#### If in multiplayer; On which server does this happen? 
Eta
### For Quest Detect need the Exquisite Glass Crystal
![изображение](https://user-images.githubusercontent.com/47714084/87049221-60a0d700-c205-11ea-95ed-05b5a4713cc8.png)
### But for recipe neded the Glass Lens
![изображение](https://user-images.githubusercontent.com/47714084/87049706-fb99b100-c205-11ea-9a1c-2451e4aafb20.png)

**Comment by Dream-Master** [comment]
yea recipe was changed but quest not.
