### ISSUE TITLE
[Witchery] The Spirit will not spawn

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6371]
#### Which modpack version are you using?
2.0.9.4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### The Spirit in the World of Dreams will not spawn.
I can not find a spirit in world of dreams.
![изображение](https://user-images.githubusercontent.com/47714084/87153073-88ed0c00-c2bf-11ea-8181-653887a0b6c0.png)
Only vanilla mobs.
![изображение](https://user-images.githubusercontent.com/47714084/87153232-cf426b00-c2bf-11ea-989e-91acbb806ade.png)
Nowhere.
![изображение](https://user-images.githubusercontent.com/47714084/87153513-48da5900-c2c0-11ea-9b43-fdef403456e5.png)
_It Spirits needed for to be continued Withery mod_
![изображение](https://user-images.githubusercontent.com/47714084/87153687-8939d700-c2c0-11ea-8c69-82ea43b7b90b.png)

**Comment by MotiasF33** [comment]
I think this conflict the Spirit[Random Things] and Spirit[Witchery]
Because after killing mobs Spirit[RT] too will not spawn.

**Comment by Dream-Master** [comment]
@MotiasF33 why you think so ?

**Comment by Dream-Master** [comment]
maybe we disable spirits (RT)

**Comment by MotiasF33** [comment]
> 
> 
> maybe we disable spirits (RT)

it have same names :3 idk..this it suppose

**Comment by boubou19** [comment]
by disabling the spirits from random things, you won't be able to get ectoplasm anymore, which is needed in the crafting of the spectre glass. The spectre glass is a cool block that is only solid for players, and can be used in mob farms design. So if the spirits from random things is disabled, you should add a way to obtain the ectoplasm (thaumcraft ?)

**Comment by MotiasF33** [comment]
> 
> 
> by disabling the spirits from random things, you won't be able to get ectoplasm anymore, which is needed in the crafting of the spectre glass. The spectre glass is a cool block that is only solid for players, and can be used in mob farms design. So if the spirits from random things is disabled, you should add a way to obtain the ectoplasm (thaumcraft ?)

This only applies World of Dreams

**Comment by Dream-Master** [comment]
maybe we need to disablen Spirits RT only in that dim. Not sure if there is some blacklist
