### ISSUE TITLE
[Witchery] Wormwood Seeds

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6372]
#### Which modpack version are you using?
2.0.9.4QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
### Wormwood Seeds can be crafting with only fresh Mutating Sprigs
![изображение](https://user-images.githubusercontent.com/47714084/87189421-4811e900-c2f9-11ea-9fcc-6be19cccfde7.png)
### After crafting, recipe becomes not working, because Sprigs have a durability
![изображение](https://user-images.githubusercontent.com/47714084/87189789-ef8f1b80-c2f9-11ea-87b7-7bdd7b5d23bc.png)

**Comment by MotiasF33** [comment]
After writing, I thought "That maybe the author was thinking so .."

**Comment by repo-alt** [comment]
I don't think this is intentional. Btw, can you repair the twigs in the Thaumic Restorer?

**Comment by MotiasF33** [comment]
> 
> 
> I don't think this is intentional. Btw, can you repair the twigs in the Thaumic Restorer?

Yea, Thanks
![изображение](https://user-images.githubusercontent.com/47714084/87192096-64645480-c2fe-11ea-8484-9bf0b6b38c45.png)
