### ISSUE TITLE
Updating to version 90 on non forgesever will cause all instructions to fail, and will not fail without replacing the config

### ISSUE THREAD

**Issue by maozelai** [GTNewHorizons/GT-New-Horizons-Modpack#6373]
The server uses thermos core

**Comment by yukieiji** [comment]
Removing the BugTorch  or setting `B:skipInitialWorldChunkLoad` to `false` in `mixins.cfg` would probably work
If that doesn't fix it, we'll need more detailed logs, thermos version, plugins, etc to help you understand the issue.

**Comment by Dream-Master** [comment]
@yukieiji can you write this in us wiki maybe ?
https://gtnh.miraheze.org/wiki/Main_Page
