### ISSUE TITLE
GT Forming Press Single and Multiblocks do not accept items not specified in recipes, making naming plate automation impossible. 

### ISSUE THREAD

**Issue by DuskNite** [GTNewHorizons/GT-New-Horizons-Modpack#6374]
#### Which modpack version are you using?
2.0.9.0QF4
#

#### If in multiplayer; On which server does this happen? 
Private
#

#### What did you try to do, and what did you expect to happen?
Tried to input items into Forming Press, Industrial Machine Press and Processing Array (with Forming Presses) for renaming purposes. Naming Plate is already in the Forming Press/Input bus. I expected the item to be pushed into the Forming Press/Input bus and be renamed. 
# 

#### What happened instead? (Attach screenshots if needed)
Items that were not specified in another forming press array cannot be pushed into the machine/input bus. Tested with Conveyor Belt, Robot Arm, Interface, Item Conduits and Transfer Nodes. 

Items can still be placed in the forming press and input bus by the player directly, If done like that, the machine works as intended. 
# 

#### What do you suggest instead/what changes do you propose?
Since forming press has a naming plate function that should be able to apply to everything. Forming press and its multi blocks should not have a restriction on the items that can be put in.

**Comment by Prometheus0000** [comment]
Are you saying it works with the SB and not multis? Or that you can't move the plates around with pipes? Your wording is very confusing.

**Comment by GTNH-Afx237v7** [comment]
Had the same issue today: 
A processing array with Forming Press as single block machine inside. Tried to autocraft the renaming of an item via AE interface pointed at the input bus of this processing array. The name mold was inside of the input bus, however the item to be renamed would not be pushed into the input bus by AE (blocking mode of the Interface disabled). 

Solution (don’t know if this was already implemented in 2.0.9.0): Use a screwdriver on the input bus to select „input filter off“ (tested fine with 2.1.0.0).
