### ISSUE TITLE
Advanced Inscriber does not accept Inscriber Name Press

### ISSUE THREAD

**Issue by Cleista** [GTNewHorizons/GT-New-Horizons-Modpack#6375]
#### Which modpack version are you using?
2.0.9.0QF4

#
#### If in multiplayer; On which server does this happen? 
Private server

#
#### What did you try to do, and what did you expect to happen?
Attempt to insert Inscriber Name Press into AE2 Stuff Advanced Inscriber

#
#### What happened instead? (Attach screenshots if needed)
Advanced Inscriber will not accept Inscriber Name Press

#
#### What do you suggest instead/what changes do you propose?
Allow Advanced Inscriber to take the Inscriber Name Press and use it to rename items

**Comment by MotiasF33** [comment]
> 
> #### Which modpack version are you using?
> 
> 2.0.9.0QF4
> #### If in multiplayer; On which server does this happen?
> 
> Private server
> #### What did you try to do, and what did you expect to happen?
> 
> Attempt to insert Inscriber Name Press into AE2 Stuff Advanced Inscriber
> #### What happened instead? (Attach screenshots if needed)
> 
> Advanced Inscriber will not accept Inscriber Name Press
> #### What do you suggest instead/what changes do you propose?
> 
> Allow Advanced Inscriber to take the Inscriber Name Press and use it to rename items

U can use a regular Inscriber and SFM for automatizon this process

**Comment by repo-alt** [comment]
That may  be (or may be not) fixed by adding a recipe via minetweaker. (There is a similar bug reported at the original repository and the only solution proposed was adding and removing the recipe with a CraftTweaker)

**Comment by Prometheus0000** [comment]
@Cleista Please find this recipe repo mentioned, because I don't even know how to use a name press in the first place.
