### ISSUE TITLE
[Thaumcraft] Node Transduser recipe 

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6376]
#### Which modpack version are you using?
2.0.9.4
#
#### If in multiplayer; On which server does this happen? 
Eta
### Now like that
![изображение](https://user-images.githubusercontent.com/47714084/87237829-754abe00-c403-11ea-8535-ec9f786291ed.png)
### I think it should be like that
![изображение](https://user-images.githubusercontent.com/47714084/87237832-7b409f00-c403-11ea-9e0f-bb6a7c4710e2.png)

**Comment by repo-alt** [comment]
That recipe always stroke as a bit weird

**Comment by Dream-Master** [comment]
will check

**Comment by GTNH-Afx237v7** [comment]
Afaik it is the same in 2.0.8.8 (1st image). Not too bad to make either.

**Comment by Dream-Master** [comment]
maybe remove the top left redstone block and add the plate make it look better.
