### ISSUE TITLE
Cutting factory -> Carpeter Block

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6377]
#### Which modpack version are you using?
2.0.9.
#
#### If in multiplayer; On which server does this happen? 
Please extend cutting receips from single block cutting mashine to factory cutting machine, like carpeters block to wedge slope and so on.

**Comment by boubou19** [comment]
it seems like this is caused by minetweaker itself: I suspect every item added by a minetweaker script will not be added to gt++ multiblock recipe map. So you may want to report it at gt++ repo: https://github.com/alkcorp/GTplusplus/issues

**Comment by draknyte1** [comment]
Both use the same recipe map, should work fine.

**Comment by Ngar1** [comment]
my failure - it takes longer than I liked to wait :-)
