### ISSUE TITLE
Tinker Copper Block change in inventar to GC Copper Block

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6378]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
I used for decoration chisseld Tinkers copper block (1169:3) -> they change in inventrar to (ugly;-)  galacticraft copper block (1708:9).
#
#### What do you suggest instead/what changes do you propose?
please stopp autochangeing of this blocks, Thank You!

**Comment by Ngar1** [comment]
is there a trick do prevent this autochangeing general?

**Comment by Dream-Master** [comment]
@Ngar1 its uniffication from GT but we can change it to another copper block.

**Comment by Ngar1** [comment]
thanks, but if i change only one stack of many the uniffication do not strike.
