### ISSUE TITLE
IC2 coolant cells voiding on use

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#6379]
#### Which modpack version are you using?
2.0.9.0

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
I was moving a specific amount of IC2 coolant in cells for a crafting recipe, and tried loading it into a non-gt tank
#
#### What happened instead? (Attach screenshots if needed)
The cells did not return.

This happens both when using the EIO user interface or clicking the tank, and it also happens with other inventories like barrels. It also appears to be exclusive to IC2 coolant as any other fluid I've passed through portable containers do return the cell (So far I've seen lox, argon, and everything from the tritanium quest work fine)
![image](https://user-images.githubusercontent.com/8459776/87245191-bf539400-c443-11ea-9ce0-0fc0c7c9cbf2.png)
![image](https://user-images.githubusercontent.com/8459776/87245194-c37fb180-c443-11ea-82dd-d7378ae0fc39.png)
![image](https://user-images.githubusercontent.com/8459776/87245198-ca0e2900-c443-11ea-8d5c-536d4227ef67.png)

#
#### What do you suggest instead/what changes do you propose?
Please patch it so I don't have to keep crafting cells for no apparent reason. A possible cause of action might be to add a GT replacement fluid.

**Comment by MotiasF33** [comment]
> 

Use Universal Cell?

**Comment by Prometheus0000** [comment]
My understanding is that this is the normal behavior for ic2 cells (yes it's stupid). Try using a different cell type or tank. Or find a coder that can ASM IC2 for you. You can also use a GT tank+pump as an intermediary too.

**Comment by Prometheus0000** [comment]
Don't do that then.
