### ISSUE TITLE
Uncraftable storage drawer variants

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#6380]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried crafting jungle drawers
#
#### What happened instead? (Attach screenshots if needed)
It seems that the recipe has changed to use the chisel, but whereas the recipe shows in NEI, it is not actually available.

When placing the 2x1 drawer into the chisel UI, it showed all cells occupied but there was no scrollbar visible to navigate to other variants. Notably, all vanilla wood flavours are dropped and are thus uncraftable this way.
#
#### What do you suggest instead/what changes do you propose?
This might be a bug in Chisel (fix the scrollbar), or an incomplete implementation of #5537 (which could probably be corrected or reverted)

**Comment by leagris** [comment]
See: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5537#issuecomment-657235215
