### ISSUE TITLE
[HEE] Instability Orbs drop

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6381]
#### Which modpack version are you using?
2.0.9.4QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
### From Instability Orbs drops a null BartWorks things
![изображение](https://user-images.githubusercontent.com/47714084/87250355-dfe41400-c46c-11ea-8d7d-caffb744d460.png)

**Comment by Prometheus0000** [comment]
Duplicate of #6263
