### ISSUE TITLE
[Suggestion] Change recipe for the Ender Tank

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6383]
#### Which modpack version are you using?
2.0.9.4QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
### Now recipe the Ender Tank
![изображение](https://user-images.githubusercontent.com/47714084/87254093-cc46a680-c488-11ea-85de-36d360fccb4a.png)
i think that it’s not fair, because the Ender Chest has more expensive craft
![изображение](https://user-images.githubusercontent.com/47714084/87254131-fe580880-c488-11ea-81bc-8f840a70be2e.png)
### I want suppose change recipe the Ender Tank
_like that_
![изображение](https://user-images.githubusercontent.com/47714084/87254234-c3a2a000-c489-11ea-8e28-7cb0245bda06.png)
_or mb like that_
![изображение](https://user-images.githubusercontent.com/47714084/87254289-4592c900-c48a-11ea-8bd7-19f0d0798626.png)

**Comment by Dream-Master** [comment]
nope a tank not fit in the chest recipe. I guess the bc tank is not fair maybe I chose a obsidian one.
