### ISSUE TITLE
Cleanroom Color Glitch

### ISSUE THREAD

**Issue by SBAngel810** [GTNewHorizons/GT-New-Horizons-Modpack#6384]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
I built a cleanroom
#
#### What happened instead? (Attach screenshots if needed)
The maintenance hatch block and energy hatch block's color looks pretty weird,
but the cleanroom works fine.
![1D6_}TR%GP O@ EEP4059NM](https://user-images.githubusercontent.com/66779899/87292261-21d78d80-c533-11ea-8927-a11d79a29091.png)
![GVE2R} AQV)3T}}D5MU(Z9G](https://user-images.githubusercontent.com/66779899/87292265-2308ba80-c533-11ea-9e1e-c46ea10d2d79.png)

#
#### What do you suggest instead/what changes do you propose?
fix this color glitch

**Comment by boubou19** [comment]
duplicated of #3059 and #2813. Next time please look for existing/closed issues before posting a new one.

**Comment by SBAngel810** [comment]
sorry
