### ISSUE TITLE
GT5 Underground Oil Calculations not respecting config when MinAmount > 0

### ISSUE THREAD

**Issue by Cleista** [GTNewHorizons/GT-New-Horizons-Modpack#6387]
#### Which modpack version are you using?
2.0.9.0QF4

#
#### If in multiplayer; On which server does this happen? 
Any server

#
#### What did you try to do, and what did you expect to happen?
Discussed with @0lafe about [liquid air on Callisto](https://discordapp.com/channels/181078474394566657/234936569360809996/732648469226848419) and found out it's [generating way more than the config value of 20 max](https://discordapp.com/channels/181078474394566657/234936569360809996/732651031720099931). 

#
#### What happened instead? (Attach screenshots if needed)
The issue lies with [GT_UO_Fluid.java#getRandomAmount()](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/objects/GT_UO_Fluid.java#L55). 

It incorrectly adds `min` to `amount` before raising it to the 5th power, causing any fluid with config values of `MinAmount` greater than zero to generate significantly more fluid than they should. 

Impacted fluids: 

* Callisto Liquid Air: 
    * Config: 2 to 20L
    * Actual: 1 to 180L
* Pluto Liquid Air: 
    * Config: 4 to 40L
    * Actual: 3 to 411L
* Pluto Fluorine
    * Config: 4 to 800L
    * Actual: 3 to 3361L

Slightly less importantly, the rounding here also causes fluids to never be able to reach the max value. For example: 

* Ross Lava:  
    * Config: 0 to 32767L
    * Actual: 0 to 32210L
* Mars Chlorobenzene
    * Config: 0 to 400L
    * Actual: 0 to 369L

You may see values above the config max in-game, but that's because of the per-chunk 25% variation. The highest possible average amount is always slightly below the config max.

#
#### What do you suggest instead/what changes do you propose?
Fix the source to this: 

```java
	public int getRandomAmount(Random aRandom){//generates some random ass number that correlates to extraction speeds
		int div = (int)Math.floor(Math.pow((MaxAmount-MinAmount)*100.d*DIVIDER, 0.2d));
                double amount = aRandom.nextInt(div)+aRandom.nextDouble();
                return MinAmount*DIVIDER + (int) (Math.pow(amount, 5) / 100);//reverses the computation above
	}
```

so that it properly respects MinAmount, or if not possible change all MinAmount in config to 0. Then set Liquid Air/Fluorine config amounts to the current actual generated quantities (due to this bug) so it doesn't break old worldgen.

**Comment by chochem** [comment]
Just to add, what I already wrote on discord. this is not a bug in the code but some weird maths.

for the maths literate: it uses a Lp 'quasinorm' with p=0.2 which is pretty messed up and does not behave intuitively. in particular, to take the '2 to 20L' example, the sum of 2 and 18 in this norm is actually not 20 or at most 20 as usual, but is about 216. this behavior does not happen if min is zero as then there is no adding and the fomula is much simpler.

**Comment by 0lafe** [comment]
Might be related, but I've noticed weird behavior on the reduction value in the config. It's supposed to just dictate the amount of cycles that results in a decrease in the deposit. However when testing values of 0, I was noticing increases to the deposit size in a weird way. 500 Max's would show up in deposits larger than 1000

**Comment by chochem** [comment]
just to take what I said earlier to the logical conclusion: A proper fix would be to use a completely different formula, a quick hack fix would be to only ever user MinAmount=0. Without either, the values in the game will not respect the min/max configs.

**Comment by Dream-Master** [comment]
@Cleista can you write a fix and push it ?
