### ISSUE TITLE
infinity card quits its slot when you use your mousewheel while hoverring items in AE

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6388]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
Delta
#
####
I was finally able to make a reproductible "infinity card quits its slot" bug:
![annoying](https://user-images.githubusercontent.com/12850933/87464393-56bb1180-c613-11ea-9c02-009df25610db.gif)

from what i have understood, the infinity card slot is somehow linked to the scroll when you hover items in the AE system, but this stops as soon as you stop hoverring the items in the AE.

**Comment by Prometheus0000** [comment]
Same/similar to 3/4 in #6097. Did you try disabling the inventory/mouse tweaks stuff? I think one of them might interfere with scrolling, but I'm not sure.

**Comment by Prometheus0000** [comment]
Also, I tried to reproduce this, but was unable to.

**Comment by boubou19** [comment]
tried without inventory tweaks, same behavior

**Comment by Alexdoru** [comment]
To me it happens when I hold shift + click and drag the mouse in the terminal

**Comment by Prometheus0000** [comment]
> To me it happens when I hold shift + click and drag the mouse in the terminal

This I was able to reproduce, but not in a minimal session with only NEI+AE2+WCT+IT.

**Comment by Dream-Master** [comment]
@repo-alt any idea on this ?

**Comment by repo-alt** [comment]
I have no idea how is that possible.
Would be nice if somebody took the effort to actually localize the culprit by binary division of the pack.

**Comment by Prometheus0000** [comment]
I did try reducing the number of mods, but every single one (it felt like) told me it needed to be added back (or else crash), so I just gave up.

**Comment by repo-alt** [comment]
Many mods do have dependencies, that's true. I'd start with removing Gregtech and all that requires it, as it will immediately reduce launch time a lot.

**Comment by repo-alt** [comment]
Documenting the process would also help in future similar cases

**Comment by Prometheus0000** [comment]
Is there some kind of dependencies list?

**Comment by repo-alt** [comment]
I'm afraid not. Perhaps there is a tool to extract "hard" dependencies from the jar like what Forge does on launch, but I'm not aware of that

**Comment by bartimaeusnek** [comment]
> 
> 
> I'm afraid not. Perhaps there is a tool to extract "hard" dependencies from the jar like what Forge does on launch, but I'm not aware of that

you litterally write them in the mod container as "required-after" or "required-before"

**Comment by repo-alt** [comment]
That I'm aware of, and that helps Prometheus how?

**Comment by DianeXD** [comment]
WCT+MouseTweaks can reproduce 
related issue
https://github.com/p455w0rd/WirelessCraftingTerminal/issues/70
