### ISSUE TITLE
[Trash] a detailed quests.

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6390]
#
**Be careful reading it, because i'm writting it a very hard emotionally.**
### The little pre-story
![изображение](https://user-images.githubusercontent.com/47714084/87518678-3ded4300-c689-11ea-886d-e177fb6af0bc.png)
\- "Fine. I'm crafting wires. Now need complete quest:"

### - "Detect, detect, detect..Oh-Oxygen!"
![изображение](https://user-images.githubusercontent.com/47714084/87518936-96244500-c689-11ea-84a5-55a935c6504b.png)
\- "just put it in a cell"
![изображение](https://user-images.githubusercontent.com/47714084/87521767-7b53cf80-c68d-11ea-8245-8d97da5dbd1c.png)
### - "dck! Maybe can be using a universal cells?"
![изображение](https://user-images.githubusercontent.com/47714084/87522032-cd94f080-c68d-11ea-8e25-41da7f58e2f2.png)
### - "Good! Next required item..$%@[sound fast clicks]"
![изображение](https://user-images.githubusercontent.com/47714084/87519584-7f322280-c68a-11ea-9465-8b8f448074df.png)
\- Why it cannot be a detecting!? Ducking Oxygen!%$
### - "You my last hope!"
![изображение](https://user-images.githubusercontent.com/47714084/87519732-b0125780-c68a-11ea-92ed-cc8c83811723.png)
### - "Finally! I do it! Wait!"
![изображение](https://user-images.githubusercontent.com/47714084/87519828-cae4cc00-c68a-11ea-8eec-f6fc11f1ce1d.png)
### - "Oh..NO pLs no more!"
![изображение](https://user-images.githubusercontent.com/47714084/87523196-4a749a00-c68f-11ea-9f9a-1352844504d8.png)
Now then .
I don't understand for what a needed a detalied quests after IV-tier, then u have ME, autocrafting and rest for it.
Do you already have a crafring items, but you can't move on, because you need to show from which you mined the tin, and which enderman you killed, to make the pipe enderium and more, more, more..Aaa I don't like it.

**Comment by Prometheus0000** [comment]
LuV+quests generally don't go into this much detail, take a look at them yourself.

Also, I've never had a problem filling empty cells with oxygen, but I did so from a regular tank, not EC2.

**Comment by MotiasF33** [comment]
> 
> 
> LuV+quests generally don't go into this much detail, take a look at them yourself.
> 
> Also, I've never had a problem filling empty cells with oxygen, but I did so from a regular tank, not EC2.
My problem is not that it’s hard to fill the cells
I'm about sometimes too much details, where it is not needed.

**Comment by Prometheus0000** [comment]
> LuV+quests generally don't go into this much detail, take a look at them yourself.

Go look.

**Comment by repo-alt** [comment]
EC2 - just don't.

**Comment by MotiasF33** [comment]
> 
> 
> > LuV+quests generally don't go into this much detail, take a look at them yourself.
> 
> Go look.

It relaxing. Thanks

**Comment by 0lafe** [comment]
I wouldn't mind if the quest just asked for wires. Asking for steps like this when you should know how to read nei is just annoying, not helpful.
