### ISSUE TITLE
[Quests] T4 HDP

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6391]
#### Which modpack version are you using?
2.9.0.4QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
### For quest need a different from osmiridium bolts 
![изображение](https://user-images.githubusercontent.com/47714084/87542523-bbc24600-c6ab-11ea-892f-ff824f755ad6.png)
![изображение](https://user-images.githubusercontent.com/47714084/87542603-e2807c80-c6ab-11ea-8725-c3afe3685397.png)

**Comment by Prometheus0000** [comment]
Rurudit is correct #6107. Bother Bart to fix it.
