### ISSUE TITLE
Submission Station Crashing Game

### ISSUE THREAD

**Issue by Clowcadia** [GTNewHorizons/GT-New-Horizons-Modpack#6393]
#### Which modpack version are you using?
Current 2.08.3e
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Use Submission station
#
#### What happened instead? (Attach screenshots if needed)
Crashed
#
#### What do you suggest instead/what changes do you propose?
No idea, kind of wondering if its anything to do with my setup. need help

****
[crash-2020-07-15_14.08.12-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4927164/crash-2020-07-15_14.08.12-client.txt)

**Comment by Dream-Master** [comment]
@Clowcadia try with version 2.0.9.0. Multi mc is also in the stactrace. Can you try with any other launcher like technic ?

**Comment by Prometheus0000** [comment]
May be related to 
![image](https://user-images.githubusercontent.com/8517039/93551507-09715e00-f93c-11ea-9332-92379c062808.png)
I dunno. Try an older version than that.
