### ISSUE TITLE
Transformers stepup-stepdown textures switch

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/GT-New-Horizons-Modpack#6394]
#### Which modpack version are you using?
Current official server one
#
#### If in multiplayer; On which server does this happen? 
mp, eta
#
#### What did you try to do, and what did you expect to happen?
Using soft malled on transformer do not change the texture on it
#
![2020-07-15_22 28 09](https://user-images.githubusercontent.com/25028786/87587241-84bf5500-c6ea-11ea-89a6-cb2db6356332.png)
![2020-07-15_22 28 05](https://user-images.githubusercontent.com/25028786/87587256-8a1c9f80-c6ea-11ea-8e9d-9422e6ac3b09.png)
#### What do you suggest instead/what changes do you propose?
Fix it xD

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5420

**Comment by Cinobi** [comment]
Wew, jan issue, lol... don't look so close xD
