### ISSUE TITLE
New Cactus Fuel Quest

### ISSUE THREAD

**Issue by Krispion** [GTNewHorizons/GT-New-Horizons-Modpack#6395]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happened instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?

New quest for Cactus Coke (or Sugar Coke), an alternative fuel source during the Stone Age tier. The fuel itself isn't particularly good, burning half as long as Coal/Charcoal. That said, it's completely renewable and can be entirely automated at this tier, which I found noteworthy. I actually don't know how strong it is - I only discovered it yesterday after I reached LV. My impression is it's not too OP, but who knows. Might just depend how big you make your cactus farm, or perhaps I'm underestimating its growth rate to begin with.

**Tab:** Steam (or Stone Age; or Multiblock Goals)
**Requirements:** Hoppers (or Important Tools)

**Name:** Green Gold (or Renewable Energy v1; or Biofuel?; or Cacto-Cola)
**Description:**
With a Coke Oven, Cactus Charcoal processing becomes available. This fuel is an upgrade to regular Cacti, burning for a little longer than wood and being totally renewable.

Don't celebrate just yet though - to get the most out of your Cactus you'll want a second Coke Oven to process Cactus Charcoal into Cactus Coke. It burns half as long as regular Charcoal, with the benefit of being completely renewable.

Set up an automatic Cactus farm with water and a Hopper. The Hopper should feed into a Coke Oven. The Coke Oven in turn should dump its contents into another hopper, connected to the second Coke Oven. Its produce should then be carried into a chest by a third hopper. This will provide you with a steady and passive source of solid fuel, with a bit of Creosote as well.
(Might be too descriptive)

Instead of Cactus, you can also use Sugar Cane to produce Sugar Coke. It uses the same setup and process, and has equivalent burn time.

**Tasks:** 
Retrieval - 52x Coke Oven Brick, 3x Hopper, 128x Cactus Coke

**Rewards:** 
32x Cactus Coke
Lootbag (Stone Age)

**Notes:**
I've set the task as retrieval to leave the player the choice to either use their previously made Coke Oven for (half of) this quest, or create 2 brand new Coke Ovens.

The entire quest could also be replaced with a quest for Sugar Coke, which is processed the same way but with Sugar Cane instead. Choose whichever you'd like; I'd give mention of the alternative choice at the end of the description.

I'd keep the rewards moderate because some players will already have 2 Coke Ovens and could complete the quest trivially.

**Comment by Dream-Master** [comment]
@Prometheus000
