### ISSUE TITLE
Prospector's Scanner Output Formatting QoL Change

### ISSUE THREAD

**Issue by Cleista** [GTNewHorizons/GT-New-Horizons-Modpack#6396]
The non-electric Prospector's Scanners are widely unpopular because of the spammy, unsorted nature of its unformatted text output that's difficult to read and parse. It's bad enough that it causes people to cheat in the LuV scanner in single player. 

If we format the output so it's sorted by distance then ore name in alphabetical order, the device should become much more usable. Since it's the same amount of information that the scanner currently gives you (just much easier to read), it doesn't really affect game balance. 

Current: 
![image](https://user-images.githubusercontent.com/67157844/87607643-cc82b400-c6cb-11ea-9a16-3a7e1ff121ad.png)

Proposed result: 
![image](https://user-images.githubusercontent.com/67157844/87607653-d60c1c00-c6cb-11ea-9e46-3c874583e880.png)

**Comment by Dream-Master** [comment]
How you did this second screenshot? Are you able to make a pull request? @Cleista

**Comment by Cleista** [comment]
@Dream-Master Unfortunately that is just printed /tellraw text to check if it would look good in-game. However should be fairly straightforward change for anyone that has a working build environment and can build the scanner mod. 

Color coding/underlining can be done trivially by editing strings in [this file](https://github.com/GTNewHorizons/DetravScannerMod/blob/master/src/main/java/com/detrav/items/behaviours/BehaviourDetravToolProPick.java). 

Sorting by distance then ore name will require caching the found messages in new data structure that has the ore name, distance, and the colorized string - then sort that before sending it to players.
