### ISSUE TITLE
Tier 4/5 Heavy duty plates quests are incorrect

### ISSUE THREAD

**Issue by Cleista** [GTNewHorizons/GT-New-Horizons-Modpack#6397]
#### Which modpack version are you using?
2.0.9.0QF4

#
#### If in multiplayer; On which server does this happen? 
Private server

#
#### What did you try to do, and what did you expect to happen?
Tier 5 Heavy Duty Plate quest (ID 1724) asks for Europium Screws
![image](https://user-images.githubusercontent.com/67157844/87628236-7c711500-c6fe-11ea-91bf-981961dba787.png)

However actual recipe uses Europium Bolts
![image](https://user-images.githubusercontent.com/67157844/87629963-02428f80-c702-11ea-90d6-dd479adff4c1.png)

Screws are worth less than bolts, so this resulted in a bunch of my Europium getting lost
![image](https://user-images.githubusercontent.com/67157844/87630080-4d5ca280-c702-11ea-80ff-9601732e0289.png)

Same issue affects Tier 4 Heavy Duty Plate quest (ID 1532)
![image](https://user-images.githubusercontent.com/67157844/87629983-1090ab80-c702-11ea-937f-04aab54bacd1.png)

Asks for Ruridit bolt, actually Osmiridium bolt
![image](https://user-images.githubusercontent.com/67157844/87630043-3918a580-c702-11ea-905a-09700885ffeb.png)

#
#### What do you suggest instead/what changes do you propose?
Need @Prometheus0000 to update the quests to take the correct items. Maybe double check other space race quests too.

**Comment by Cleista** [comment]
Addendum: Implosion Compressor still gives back Ruridit dust (yes it actually gives ruridit dust, not just NEI bug), despite the recipe change. 

![image](https://user-images.githubusercontent.com/67157844/87631907-4d5ea180-c706-11ea-8db3-22a16e9b3b3b.png)

**Comment by Dream-Master** [comment]
it's bartsworks that change it so far I know. Osmium and Iridium changed by this mod.

**Comment by Prometheus0000** [comment]
See #6107 and #6391 about the T4.

**Comment by yukieiji** [comment]
Teir 5 heavy duty plates's quest  is the latest quest and has been fixed.
