### ISSUE TITLE
LuV tier lootbag rebalancing

### ISSUE THREAD

**Issue by Cleista** [GTNewHorizons/GT-New-Horizons-Modpack#6398]
#### Which modpack version are you using?
2.0.9.0QF4

#
#### What did you try to do, and what did you expect to happen?
Opened a bunch of LuV lootbags, got 4 Europium ingots, which lets me skip T1 Fusion and can get T5 rocket without ever building the reactor. 

Also got 32 Neutronium Ore somehow. 
![image](https://user-images.githubusercontent.com/67157844/87630254-b17f6680-c702-11ea-84a4-0816b34a934a.png)

#
#### What do you suggest instead/what changes do you propose?
The LuV lootbag is incredibly shit when unenchanted except for some progression-breaking drops, and the loot is basically worthless once you can actually enchant it (because you'll have fusion by then). 

This is very different from lootbags of all previous tiers which had a good chance of giving you something you could use immediately. Hell I don't even want to convert IV lootbags to LuV because I can at least get Ender Chests out of the IV lootbags. 

Suggest removing the Europium (so people can't skip tiers by getting lucky) and adding more immediately useful drops. 

Could be Super/Quantum Tanks/Chests, maybe some rare earth metals or Nq+ ore, or Quantum Stars. Stuff that people would actually want to use in early/mid LuV.

**Comment by Dream-Master** [comment]
Luv zpm and uv bags are not done yet. Feel free to add more items to the xml list. Can be done in-game.

**Comment by chochem** [comment]
I guess I am taking this as the ticket LuV, ZPM, and UV. These are really ages where the player doesn't need anybody to hold there hand and help them out anymore. But if dream wants lootbags anyway, we better come up with something. One of the main differences is that pumps/sensors/etc are getting a lot more expensive here, and so are circuits, so they are not suitable for lootbags imo. Well, others might disagree, but this is my take:

what NOT to put in:
- motors/pistons/pumps/conveyors/robot arms/sensors/emitters or anything else that directly needs the assembly line
- any crystal/wetware/bioware circuits or wetware/bioware circuit boards.
- duranium, tritanium or other stuff that directly needs a fusion reactor.

what could be good:

LuV:
- cables/pipes
- heavy duty plates
- ender tanks/chests
- industrial apiary (rare)
- interface capacity cards
- a single SC coil block (the one used in mk1 fusion, you need 33 for the reactor, but you shouldnt be able to get more than a few even if you go all-in on LuV lootbags)
- a bit of trinium dust


ZPM:
- a stack of some gt++ ores.
- cultures for the vat that are not part of the main progression, so for stuff like beer brewing etc.
- a single cell of Krypton (rare)
- a single cell of Neon (common)
- industrial apiary (rare)
- single upgrades for the industrial apiary 
- interface capacity cards
- cables/pipes
- heavy duty plates
- a bit more trinium dust
- a single piece of salt

UV:
- tectech casings
- tectech cables
- a scrench
- a few multiblock machine blueprints
- a small set of items with various colors for painting tectech stuff
- cables/pipes
- heavy duty plates
- a single piece of salt

**Comment by combusterf** [comment]
So assuming lootbag item use that do not actually complete quests or achievements directly:
ZPM
- Q-bit wafers
- Quantum PCB and Ev-Iv-Luv-Zpm circuits
- Roquesite ore x 64 (T3 sporadic)
- Trinium ore x 32 (not normally obtainable)
- Naquadria ore (16 in crate due to radioactivity) (not normally obtainable) 
- LuV field generator x 1
- Superconducting coil block x 2
- Quantum star x 8
- UHPIC wafer x 4
- Reinforced glass tube x64

UV
- neutronium ingot x64 (takes un-fun amounts of time to cook)
- mysterious crystal ingot x64 (idem. You'll be cooking these around the clock all week for the T7 rocket)
- Fusion coil block x 2
- PPIC wafer x 4
- ZPM energy hatches
- LuV sensor x8 (i.e. feedstock for wetware)
- Neuro board wrap x 1 (i.e. only usable if you made wetware the hard way already)
- Naquadria ore (32 in crate)
- Samarium ore 
- Raw crystal chips and crystalprocessor items 
- Quantum star x 16
- Gravi star x 4
- Tectech High-power casing x 8
- Tectech computer casing x 4

I'd personally add all the gonna-hate-this 1-4 items to their corresponding tier rather than to go Tier±1 on them. It is universally the first quest and you're not reasonably going to get all four of them from lootbags before you complete it.

**Comment by Cleista** [comment]
Here's the first draft of EV-ZPM lootbags testing the idea of keeping the loot tables relatively consistent across tiers. I didn't touch loot below EV because their tables are considerably different, though it would probably be simple enough to carry over this template to lower voltages if desired. 

# EV
-----
![image](https://user-images.githubusercontent.com/67157844/88605809-08f9cc80-d049-11ea-94f6-92c8e630aca0.png)

# IV
-----
![image](https://user-images.githubusercontent.com/67157844/88605842-19aa4280-d049-11ea-8fa1-1d71ec046993.png)

# LuV
-----
![image](https://user-images.githubusercontent.com/67157844/88605855-23cc4100-d049-11ea-95ff-741c45a2761f.png)

# ZPM
-----
![image](https://user-images.githubusercontent.com/67157844/88605864-2b8be580-d049-11ea-8799-a01109d43d1e.png)

# How much difference does enchanting make? 
-----
**One stack of unenchanted IV lootbags:** 
![image](https://user-images.githubusercontent.com/67157844/88606345-6b070180-d04a-11ea-9c12-bf7730130803.png)

**One stack of enchanted IV lootbags:** 
![image](https://user-images.githubusercontent.com/67157844/88606588-0ac48f80-d04b-11ea-8ba0-0e8cff717341.png)

The ratio of trash to treasure is increased by about 2x at LuV/ZPM tiers to encourage enchanting the lootbag.

**Comment by Cleista** [comment]
Lootbag XML if you want to load it in your own world to test. 
[LootBags.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4985402/LootBags.zip)

# Main points of discussion: 
1. Should Assembling Line parts be given in LuV+ bags at all? If not, what is a substitute? 
2. Should Crystalprocessors be given in ZPM, if you can technically enter the tier without making Crystalprocessors?
3. Since Wetware/Bio processors are extremely expensive, what should stand in for them at UV+?
3. What should lootbag enchantment actually cost? Currently the item required is inconsistent across tiers, some being available at start of tier and some being available at end of tier.

**Comment by Prometheus0000** [comment]
Didn't you already have a branch about this made and get merged? Though I don't see the PR? Is this done? @Cleista

**Comment by Dream-Master** [comment]
LuV and zpm merged so far ik uv not done yet

**Comment by Dream-Master** [comment]
Need to check if this can be closed.

**Comment by Prometheus0000** [comment]
BTW @Cleista if you ever get back to this, you should know that ZPM and higher lootbags are not given out.

**Comment by alphaNOVAircraft** [comment]
> BTW @Cleista if you ever get back to this, you should know that ZPM and higher lootbags are not given out.

They are

**Comment by Dream-Master** [comment]
This issue need to be open.
