### ISSUE TITLE
GT super buffer start to lag again

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6400]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### 
I know that this old bug was supposed to be fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/124 but here is what i get: 
![2020-07-16_18 35 15](https://user-images.githubusercontent.com/12850933/87698341-9e68a700-c793-11ea-810f-f5913130d5c7.png)

this GT UV super chest buffer is set in Transfer size mode, with an stack output of 9 items.

**Comment by boubou19** [comment]
lags occur only when there is item I/O, otherwise it's totally fine

**Comment by repo-alt** [comment]
There a "threaded" version, that is supposedly better, but I never tested it

**Comment by Prometheus0000** [comment]
Wasn't the threaded version made to fix the problem, but the original was improved so it became useless?

No idea why this problem (which I never personally got far enough to experience) has started happening though. Maybe ask other people if it's happening to them? Maybe it's something you're doing?

**Comment by chochem** [comment]
If I recall correctly:
The threaded super buffer is a legacy thing. that was just a first improvement by alk of the old super buffer. the super buffer then got fixed proper though by moron, alk, and mitch combined and should (in theory) be performing pretty well and better than the threaded one.

Not sure whats going on here specifically. I did not notice any performance issues. You should probably switch the output to 63 instead of 9 if you are in late game, that should help a good bit.

**Comment by boubou19** [comment]
i tried with both 9 and 63, still lags a lot

**Comment by Devtron3D** [comment]
I am playing on prospercraft server and have spent HOURS trying to remove these things from its lagboard
Atm even a superbuffer that i cut off its input of dust still takes up tik time
![image](https://user-images.githubusercontent.com/3405825/87949509-65d41080-caa6-11ea-97ce-05fc1042a283.png)

this second one is running, set to output 63 stack size of tiny dust
![image](https://user-images.githubusercontent.com/3405825/87949587-81d7b200-caa6-11ea-9bf4-8d5634c95c42.png)
both showing little or high numbers on the lag board, depending on time, dont know why the one not getting dust show up

**Comment by boubou19** [comment]
![2020-09-22_21 36 41](https://user-images.githubusercontent.com/12850933/93929424-1f0bcc80-fd1c-11ea-8512-9009460def5c.png)

tested in the 2.0.9.1 dev pack. still a bit laggy, but way better. (2 infinite item chests outputting constantly tiny piles of tin and copper, outputting by 63, transfert mode)

**Comment by Devtron3D** [comment]
Could you try adding as many different types of tiny you could to it, so it has like 100 types in it.
just so it needs to iterate over a lot to see what needs outputting, while it is outputting one type.

**Comment by Prometheus0000** [comment]
Is this the same as in #6414?

**Comment by repo-alt** [comment]
I recently proposed 2 solutions for this problem (making "better" superbuffer, not plagued by MetaTileEntity inheritance, or, improving oredictionary export bus, to allow rationing). Didn't get much reaction.

**Comment by repo-alt** [comment]
Actually 3 solutions: another one is to get rid of the tiny piles, or at least generate alternative centrifuge recipes w/o them (with a selector circuit)

**Comment by Prometheus0000** [comment]
Well, I don't think I'm code-savvy enough to say what would be a good idea. And I'm not far enough to use super busses or ore dict exporters, so I don't know what people would use more.

I do think option 3 sounds like it would break way too much stuff though.

**Comment by repo-alt** [comment]
It would break nothing if you don't remove existing recipes, but add new ones, like: 9 impure dusts + circuit#1 = 9 pure dusts + 1 byproduct dust

**Comment by GTNH-Afx237v7** [comment]
In case of number 3, there will still be tiny dusts from macerating / arc furnacing items/blocks (cables, screws etc) I assume?
Personally I think a „better“ buffer and improved oredict bus seem equal (not code savvy enough either), though I think I would go for the oredict bus.

**Comment by repo-alt** [comment]
"there will still be tiny dusts from macerating / arc furnacing items/blocks (cables, screws etc)" - sure, but this is a negligible source of them

**Comment by Devtron3D** [comment]
I find tiny dust to be a real drag on server performance with big bases, and I would welcome an option to make recipes with hole dust instead.

**Comment by Prometheus0000** [comment]
What about GT++ materials that give tiny dust? I doubt you can change them as well? (I grabbed a random one)
![image](https://user-images.githubusercontent.com/8517039/96020626-4f76f000-0e1c-11eb-894c-b2780c8f731c.png)

**Comment by Prometheus0000** [comment]
There's also bee stuff, but that could probably have the % lowered
![image](https://user-images.githubusercontent.com/8517039/96020733-7a614400-0e1c-11eb-9381-944cc8f8d6ae.png)

**Comment by Devtron3D** [comment]
Why not add an option to do 9 at once, it will take longer of course, but you skip the tiny ones while getting a hole one

**Comment by Glease** [comment]
1.11% is going to look very frustrating, while it offers essentially the same thing over the long run. 9 in 1 run sounds more appealing. BTW gt++ recipes are mirrored from the vanilla gt centrifuge/macerator/etc recipes. If you add a 9 in 1 recipe or a probabilitistic full dust recipe early enough then gt++ will (hopefully) copy it over.

**Comment by Prometheus0000** [comment]
We could just do 9 combs at once too. I agree it seems like a good option.

**Comment by Devtron3D** [comment]
could we add a chip to these machines so they would only do 9 at once?
Or whatever is required to avoid tiny dust
