### ISSUE TITLE
Yttrium barium cuprate recipe is wrong

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6401]
#### Which modpack version are you using?
GTNH 2.0.9.0 QF4

it is missing the oxygen in the input hatch

![image](https://user-images.githubusercontent.com/57050655/87699466-30bd7a80-c795-11ea-8c6b-4602c24fa60f.png)

**Comment by Dream-Master** [comment]
Will add
