### ISSUE TITLE
Crafting with fluids some fluids dont work and ask for missing fluid pattern

### ISSUE THREAD

**Issue by viljar290** [GTNewHorizons/GT-New-Horizons-Modpack#6402]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
eta
#
#### What did you try to do, and what did you expect to happen?
used fluid cell in pattern and put it in a fluid interface. recepie fails and keeps asking for missing fluid pattern
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/41335390/87712322-69168600-c7a0-11ea-8234-4080588d18fd.png)

only happens with some fluids this far I have found this for molten hss-g and for molten polybenzimidazole
#
#### What do you suggest instead/what changes do you propose?
fix so it works consistently with all fluids not just some.

**Comment by viljar290** [comment]
i have tried with normal cell with the fluid and volumetric cell in the pattern.

**Comment by boubou19** [comment]
are those old pattern or did you made them in 2.0.9.0 QF4? Also what fluid is not working?

**Comment by viljar290** [comment]
just made them. fluids i have found this far that don't work are molten hss-g and molten polybenzisomething (the more advanced plastic) also if you actually make the fluid pattern its asking for and try to tell it to craft it crashes the server (just tested sorry to evreyone on the server expected it to maybe not do anything not crash server...)

**Comment by viljar290** [comment]
Figured out whats the issue and how to work around it. 
It breaks with every fluid if there's no actual items in the recepie.
it works if I add a stick for it to feed into a box next to the interface. Same issue happens for every fluid if there's no items besides the cells in the pattern.

**Comment by boubou19** [comment]
if you want to only craft fluids, you may want to look at the ME Fluid Assembler from extra cells 2, but i don't know if it's as bugged as the rest of the mod

**Comment by viljar290** [comment]
the workaround with the stick works so I can have it just put a stick into a box next to the machine and the fluid into the fluid solidified. so end result I was trying to get is achieved with just a random stick cycling along

**Comment by Dream-Master** [comment]
@repo-alt any idea on this ?
