### ISSUE TITLE
crystal

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6405]
#### Which modpack version are you using?
latest
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
100%
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/87866641-d439a580-c9b6-11ea-91c8-0e7bff973062.png)
![image](https://user-images.githubusercontent.com/59776356/87866646-e0256780-c9b6-11ea-8f6f-07222c46d190.png)
Since this is not 100%  Why only ask me to make 32 powders 
I put in 64 powders and only got 40 crystal

#
#### What do you suggest instead/what changes do you propose?
make it 100%

**Comment by Prometheus0000** [comment]
Use the LCR recipe.

**Comment by Dream-Master** [comment]
Autoclave never give 100% with water.

**Comment by Cleista** [comment]
![image](https://user-images.githubusercontent.com/67157844/87871094-b3079380-c97b-11ea-8398-c626d7655c85.png)

![image](https://user-images.githubusercontent.com/67157844/87871088-aaaf5880-c97b-11ea-8e2f-913087394431.png)

**Comment by Dream-Master** [comment]
Ok maybe the need be less than 100% with water and 100 with another fluid.

**Comment by Prometheus0000** [comment]
Are those two water or distilled water? And adding a third, better fluid sounds fun, if we ever finish some of the other stuff.

**Comment by Dream-Master** [comment]
first i add to water 80% and distilled water 90%
Any idea what fluids gives 100%

**Comment by Dream-Master** [comment]
@Prometheus0000 @Eason134HK @Cleista any idea for 3rd better autoclave meaterial ?

**Comment by Prometheus0000** [comment]
FTB:I used a magical material for their third fluid, and I think doing the same to encourage doing magical stuff would be nice. Though it depends on whether it's for specific recipes, or all/many of the water/distilled water ones.

For magical stuff, void metal fits thematically (it's a self-repairing metal), and is difficult to get a lot of, and takes quite a while to get to in TC. Life essence (blood) is much easier to get (and super easy once you get a WoS) but doesn't fit as well thematically, but is available immediately in BM.

For non-magic stuff, maybe that polycapron (or whatever it's called) that's only used to make string? Maybe one of the rubbers, like PBI?

If it's just for crystals though, then I think Mineral Water sounds good. It already has minerals in it (to form crystals), and is a GT fluid to begin with, and is only currently used to make food items.

**Comment by damug** [comment]
Eh, from a realistic standpoint you don't use tap water in an autoclave because it has minerals in it.  You use RO or distilled water to get the purest crystals forming from your solution.  I like the void metal idea though, because ~magic~.

**Comment by Dream-Master** [comment]
yes why not molten void. If you dont like magic you dont get 100%.Or alternative we can have 100% with Mineralwater and if that work 120 or 130 % with void

**Comment by Dream-Master** [comment]
never tested more than 100%

**Comment by damug** [comment]
I think you misread me, mineral water has all the same failings for use in an autoclave as regular water, because of the minerals in it.  distilled water, realistically, would still be inherently better... but yeah, all about that void metal.

**Comment by Dream-Master** [comment]
@Prometheus0000 PBI or polycapron  not match really it sound for me that it is to thick for make crystals grow but maybe we find another gt fluid.
Ok mineral water idea is out

**Comment by damug** [comment]
Is there a way to use essentia in the autoclave?  Aqua essentia could be a good candidate, even though I'm not seeing a liquid version of it, it's about as pure as water could come.

**Comment by yukieiji** [comment]
Since both are space mod materials, what about molten meteoric iron?
I think 5 dust → 6 crystal(100％) would solve 120% crystal recipe(need programming circuit to avoid conflicts).

**Comment by Dream-Master** [comment]
now we have 2 slots and can use circuits :)
