### ISSUE TITLE
quest 1686 "Crystalprocessors" does not complete

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6408]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
Tried to comple the quest 1686 "Crystalprocessors"
#
#### What happened instead? (Attach screenshots if needed)
I cannot the two last steps of the quest.
![image](https://user-images.githubusercontent.com/12850933/87881574-7c249280-c9fa-11ea-81fc-95630ffe449a.png)

![image](https://user-images.githubusercontent.com/12850933/87881581-88105480-c9fa-11ea-923d-b978813d49ef.png)

![image](https://user-images.githubusercontent.com/12850933/87881597-a37b5f80-c9fa-11ea-96d8-52bec0f69f0f.png)

![image](https://user-images.githubusercontent.com/12850933/87881610-b5f59900-c9fa-11ea-9ee9-492461cbcd3c.png)

I made the sliced circuit in both an IV slicer and a ZPM slicer and both gave me the same item that does not trigger the step 3 to complete, and making the circuit imprint from the sliced circuit i have does not trigger the step 4 to complete. I tried spamming manual detect, it changed nothing.

here is the output of the /mt hand on the sliced circuit:

<bartworks:gt.bwMetaGeneratedItem0:1>.withTag({id: 5878 as short, Count: 1 as byte, registryName: "gregtech:gt.metaitem.03", Damage: 32089 as short})

here is the output of the /mt hand on the circuit imprint:

<bartworks:gt.bwMetaGeneratedItem0>.withTag({id: 5878 as short, Count: 1 as byte, registryName: "gregtech:gt.metaitem.03", Damage: 32089 as short})

**Comment by Prometheus0000** [comment]
This requires the updated hodgepodge to work to fix the sliced item ID shifting. Maybe the server wasn't updated correctly? Does it work for other people on the same/other servers? Or in SP?

Did you try using a cutting factory in slicing mode to make it? It should work from either machine though.

**Comment by boubou19** [comment]
Combuster confirmed the id shifting on delta. The cutting factory gave me the same sliced circuit. Unfortunally my potato computer can't stand SP. here is the /mt hand of the sliced circuit of the crystalprocessor on epsilon: 

<bartworks:gt.bwMetaGeneratedItem0:1>.withTag({id: 6546 as short, Count: 1 as byte, registryName: "gregtech:gt.metaitem.03", Damage: 32089 as short})

which is still not the same as in the quest file.

**Comment by Prometheus0000** [comment]
The ID number will change because it's a different world than the one I made the quest in, the problem before was having things like a 'sliced gooseberry' imprint since it determines what it's sliced by item ID, which shifts per world. Can you find people who _can_ get it to work? Like I said, it could be the servers not being setup correctly.

Also, do the other imprint quests work/not work?  I had to replace all the sliced and imprinted stuff (after the HP fix was implemented) and might have missed just this quest or something.

**Comment by boubou19** [comment]
looks like delta and epsilon do not run the latest hodepodge because i could not get all the crystalprocessor family to have their sliced circuits & circuit imprints despite their tooltip indicating correct circuits.

**Comment by Prometheus0000** [comment]
But it works on the other servers/sp?

**Comment by DualBallers** [comment]
I had the same issue for the circuit imprint for these quests in the ZPM tab. This was in single player (had to use bq_admin edit).
![image](https://user-images.githubusercontent.com/30087707/87885737-f8799e80-ca17-11ea-86b3-7bbc4ca0ef54.png)

**Comment by Prometheus0000** [comment]
Can you find someone who _can_ complete them then? Otherwise, you'll probably have to wait for Bart to come back to fix it, and he'll probably have to break all the AE recipes when he tries to fix it _again_.

I don't think there's anything I can do myself if no one else can complete it other than not requiring the sliced and imprinted items in quests. And of course, you're all using the latest version, right?

**Comment by boubou19** [comment]
i borrowed another computer, so i could try it in sp with 2.0.9.0QF4, and it does not work too. official servers are on 2.0.9.0 QF4 as well.

**Comment by Cleista** [comment]
@Prometheus0000 if you remove the ID nbt here, the imprint seems to still complete the quest in my testing. 

![image](https://user-images.githubusercontent.com/67157844/88485692-bedbf280-cf45-11ea-822d-36d32843812d.png)

**Comment by Dream-Master** [comment]
ignore nbt is better

**Comment by Cleista** [comment]
> ignore nbt is better

If you ignore NBT then one sliced circuit will complete every tier of sliced circuit quests. 

You should keep the registryName and Damage fields because those check for which circuit got sliced and don't have the ID problem.

**Comment by Anarack** [comment]
If it already requires the circuit you need to slice I don't see a major problem.

**Comment by Cleista** [comment]
Leaving the sliced circuit out of the quest may confuse people.

The fix I suggested above should let you keep the sliced circuits in the quest and not have the ID issue. Just need some external testing to confirm it works for everyone.

**Comment by Dream-Master** [comment]
@Cleista  Nope i am against  let it out The quest book is a kind of wiki

**Comment by Prometheus0000** [comment]
I got it to work by removing the id and registryname fields after going though 2 raw nbt data option screens (the ...). Just removing the id was not sufficient for me. It worked in both worlds I tested it in (different IDs) so let's hope it works for others.
![image](https://user-images.githubusercontent.com/8517039/93725720-44af9f00-fb7f-11ea-96ef-e194c4258550.png)
