### ISSUE TITLE
Circuit programmer requires specific circuits

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#6412]
#### Which modpack version are you using?
2.0.9.0
#
#### What did you try to do, and what did you expect to happen?
Craft circuit programmer with hiighest tier circuits
#
#### What happened instead? (Attach screenshots if needed)
Now you cant craft it with microprocessors and integrated processors. Ore dict only supported with worst mv tier circuits
![image](https://user-images.githubusercontent.com/29033773/87923403-1aaa0580-ca86-11ea-90cf-66e6815e5007.png)
![image](https://user-images.githubusercontent.com/29033773/87923581-66f54580-ca86-11ea-8316-79dcf2cce403.png)
#
#### What do you suggest instead/what changes do you propose?
Add full list of circuits to circuit programmer craft

**Comment by Dream-Master** [comment]
@draknyte should we put this issue on your repo ?
