### ISSUE TITLE
Extraordinary lag being created from GT

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#6414]
#### Which modpack version are you using?
2.0.9.0 QF4
#
As of 2.0.9.0 or possibly before there are multiple GT tile entities causing extreme amounts of lag. I'm going to try fold @boubou19's ticket #6198 from last month into a new ticket here covering multiple issues that I believe are related.

<details>
<summary><s>Output bus lag</s> Fixed</summary>
<br>

Firstly output buses on multiblocks if connected to large inventories cause extreme amounts of lag. See below for screenshots:

We show here the output bus with no attached inventory, taking very little processing power.  (0.000426ms)

![unknown](https://user-images.githubusercontent.com/54497873/87961004-07f6f700-caad-11ea-85df-6a3a73a50060.png)

Now we see it with a quantium pipe attached, this inventory handles 512 stacks a second and causes ~300x more lag.  (0.14ms)

![unknown (2)](https://user-images.githubusercontent.com/54497873/87961010-09c0ba80-caad-11ea-8d0c-d4377263432b.png)

Now we see the output bus with a UV conveyor attached causing even more lag totalling ~400x more processing power. (0.21ms)

![unknown (1)](https://user-images.githubusercontent.com/54497873/87961015-0b8a7e00-caad-11ea-9794-953e51528216.png)

While on its own this may only constitute around 0.4% of server load when you have 100+ of these scattered around a developed base this can quickly consume huge amounts of server resources.

One oddity I also noticed here is that the output bus causes the same amount of lag even if the pipe will not accept the items, this is something that rarely comes up but should be kept in mind nonetheless.

![unknown (7)](https://user-images.githubusercontent.com/54497873/87971703-a8551780-cabd-11ea-930f-235c5a30dc2f.png)

Finally I thought I would mention super buses, these are just quite frankly too laggy to be useful in their current state. These are taking on average 4ms with a worst of 37 ms! That is 74% of server capacity for one bus. This is only an EV tier with 80 slots as well, the 160 slot MAX one has the potential to stall the entire server if used.

![unknown (3)](https://user-images.githubusercontent.com/54497873/87969992-02a0a900-cabb-11ea-8200-8be80c1657e9.png)
</details>

<details>
<summary><s>Conveyor lag</s> Fixed</summary>
<br>

The second issue is conveyors, this seems to be caused by the conveyor searching the entire inventory of the chest and then attempting to pull it out but someone with more experience probably knows better here.

![unknown (4)](https://user-images.githubusercontent.com/54497873/87970402-96727500-cabb-11ea-83b3-1adf3c54505b.png)

Here we can see a UV conveyor extracting from a compressed chest causing 0.5ms of lag.

An interesting thing I spotted is that if you use it on the input bus directly then it causes ~25x less lag as you can see below. See #6198 for a few more examples of this.

![unknown (5)](https://user-images.githubusercontent.com/54497873/87970531-c9b50400-cabb-11ea-99da-a7ace1b62e3b.png)

</details>

<details>
<summary>Super buffer lag</summary>
<br>

I'm not sure what is causing this one but it is definitely happening and causing a lot of unnecessary lag.

![unknown (6)](https://user-images.githubusercontent.com/54497873/87971198-da19ae80-cabc-11ea-972e-941332aec6a5.png)

Some people seem to get a lot more lag with these than I could with my testing, unsure why currently but these are pretty alarming given how prevalent their use is. 

![unknown](https://user-images.githubusercontent.com/54497873/87972043-2fa28b00-cabe-11ea-809c-aa2fb80f046b.png)

The picture above is causing 7.5ms of lag or 15% of server capacity.

</details>

**Key take aways for users**

- Do not use output super buses, the input ones do cause lag but only when they are working otherwise they are relatively tame.

- Do not use high tier conveyors on large inventories.

- Do not put large inventories on output buses, this includes GT pipes and things like compressed chests. ME interfaces are very quick and should be sufficient for most purposes here.

- Minimise use of super buffers, these are very laggy in their current state and should be avoided if possible but I recognise for some purposes they just can't be replaced (Tiny dust sorting for example).

**Comment by boubou19** [comment]
i would add to this list the issue related to #6357 and #6399

**Comment by boubou19** [comment]
super buffers may be fixed in dev with this one: https://github.com/GTNewHorizons/GT5-Unofficial/pull/309

#6198 may be fixed in dev with this one: https://github.com/GTNewHorizons/GT5-Unofficial/pull/306

#6416 may be fixed in dev with this one: https://github.com/GTNewHorizons/GT5-Unofficial/pull/315

#6515 (schematic dust in packager) and  #6662 (forcepushing fluids in EIO fluid pipe network) still need to be adressed
