### ISSUE TITLE
Quest 1417 "Cough cough - something needs to be done about that smell" bugged objective

### ISSUE THREAD

**Issue by TNaud** [GTNewHorizons/GT-New-Horizons-Modpack#6415]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Tried to do Quest #1417 (Pollution Scrubbing)
#
#### What happened instead? (Attach screenshots if needed)
The quest has two objectives to obtain the item .name which is unobtainable.
![quest](https://user-images.githubusercontent.com/35411589/87993530-bf453b00-cab8-11ea-9a66-95414a0dd2eb.png)
#
#### What do you suggest instead/what changes do you propose?
Air filters got changed in 2.0.9.0, quest should be changed to reflect that.

**Comment by draknyte1** [comment]
> Air filters got changed in 2.0.9.0, quest should be changed to reflect that.

No they didn’t.

**Comment by Prometheus0000** [comment]
I think they mean the scrubber.

**Comment by Prometheus0000** [comment]
There's nothing to fix?
![image](https://user-images.githubusercontent.com/8517039/91646263-54721280-ea1b-11ea-9fbe-be6d0a53360c.png)
Were you using qf4? Try reinstalling the pack or reloading the quests.

**Comment by boubou19** [comment]
For those who run into this issue: turn back your `    B:EnablePollution=true` in your config/GregTech/GregTech.cfg
