### ISSUE TITLE
Really ultimate battery construction data (data stick) is wrong

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6420]
#### Which modpack version are you using?
GTNH 2.0.9.0 QF4

The recipe in the data stick shows no fluids whereas the recipe in NEI shows fluids.
I have not tested yet if you can craft the battery in the assembly line with this data stick that does not have fluids.

Edit : the craft in the assembly line (with the stick that doesn't have fluids) does not use the fluids.

![image](https://user-images.githubusercontent.com/57050655/88112191-9bb0ec00-cbaf-11ea-83da-b3d892e6e183.png)
![image](https://user-images.githubusercontent.com/57050655/88112195-a1a6cd00-cbaf-11ea-87a2-085310d45da9.png)

**Comment by Dream-Master** [comment]
@Alexdoru cn you let me know if it works without the fluids ?

**Comment by Dream-Master** [comment]
Not sure it is a Tec Tech problem but this recipe was made in a TT reasearch station.

**Comment by Dream-Master** [comment]
@Technus any idea ?

**Comment by Alexdoru** [comment]
Now that you fixed the recipe of the really ultimate battery by adding the superconductors, you might also want to change the recipe of the Ultimate capacitor (UHV) from kekz

as a reminder : the new and fixed recipe 
![image](https://user-images.githubusercontent.com/57050655/89105615-d7a34700-d422-11ea-9bd1-ceda809fbbea.png)

and the recipe that would need to be changed : 
![image](https://user-images.githubusercontent.com/57050655/89105619-e4c03600-d422-11ea-9db5-291ee43dce46.png)

**Comment by Dream-Master** [comment]
@kekzdealer

**Comment by Prometheus0000** [comment]
@Alexdoru Is this fixed or isn't it? Are you talking about two different things? And what needs to be changed for the second thing? And why isn't it in its own ticket?
