### ISSUE TITLE
Game freezes

### ISSUE THREAD

**Issue by helhel1** [GTNewHorizons/GT-New-Horizons-Modpack#6421]
Hello, as soon as I try to view the recipe for an item and press R, the game freezes for about half a second. I noticed that when viewing recipes from the tinker construct mod, the game does not freeze.

####Which modpack version are you using?
2.0.8.7

#### If in multiplayer; On which server does this happen? 
I play in single player mode

#### What did you try to do, and what did you expect to happen?
I tried reinstalling the assembly, playing from different launchers, playing different versions. None of this worked.

#### What do you suggest instead/what changes do you propose?
I do not know what to do.

**Comment by boubou19** [comment]
the first lookup in nei is always laggy because it caches many things.

**Comment by helhel1** [comment]
But this happens not only at the first opening of the recipe, but also at subsequent ones.

**Comment by boubou19** [comment]
do you use regular gtnh pack? or do you added some mods? also 2.0.8.7 is not supported anymore so consider updating your game

**Comment by Dream-Master** [comment]
@helhel1 Yes  update to 2.0.9.0. Nei is now much faster

**Comment by helhel1** [comment]
I didn't add new mods, the new version didn't help

**Comment by Dream-Master** [comment]
we update nei so it becomes faster in 2.0.9.0

**Comment by helhel1** [comment]
It didn't help me (

**Comment by GTNH-Afx237v7** [comment]
How did you update? Copy and paste over? Deleted old files? Are you using any JVM arguments? Double/conflicting keybindings for R (iirc it’s also connected to sort inventory)?

**Comment by chochem** [comment]
all the NEI speed up was before 8.7 afaik, so I dont think its about the update. One should also be clear that while NEI is much faster than it used to be, that does not mean its absolutely instant. On weaker machines you still get a very noticeable lag as described here, I dont know if there is much that can be done about it though.

You can try hiding a few more big item categories in NEI, but thats not a great solution either.

**Comment by helhel1** [comment]
I completely removed the old build version from the computer and installed the new one. I play without java arguments, but I also tried to put these (-XX: + UseG1GC -XX: + AggressiveOpts -XX: + UseBiasedLocking). It did not help. I also tried to remove keybindings for R. It didn't help.

I think I have a fairly powerful computer. i7 960 3.8 GHz / 10 GB I allocated for assembly / r9 270

**Comment by GTNH-Afx237v7** [comment]
You could try allocate less RAM to the game (more isn’t always better), or split up server/client into two threads on the same PC. 
Here are the arguments I use:
-d64 -XX:+UseG1GC -Xmx4G -Xms4G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:ParallelGCThreads=4
Make sure to set the last one to the number of cores your CPU has.

**Comment by draknyte1** [comment]
> i7 960

Your cpu is like ten years old. 😂

**Comment by leagris** [comment]
I have an i7 920, and it runs GTNH good enough. Stop blaming CPU age for poor coding practices.

**Comment by helhel1** [comment]
Unfortunately, nothing helped (

**Comment by Dream-Master** [comment]
@helhel1 idk what i can do more. If you try all launchers update to 2.0.9.0 update your java it must be working
