### ISSUE TITLE
[RFC] remove endgame bees 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#6422]
#### Which modpack version are you using?
2.0.9
#

#### What do you suggest instead/what changes do you propose?

Should remove the avaritia and fusion bees. They're essentially useless, however they shouldn't be made better. Bee gen is pretty bad for endgame stuff, and these materials already struggle to have any complexity.

**Comment by chochem** [comment]
do you got a specific list of bees you want removed? Nobody uses infinity and infinity catalyst bees for example and they shouldn't really be buffed to be viable imo, so removal there is obviously a positive to remove some bloat. but what other bees do you have in mind?

**Comment by GTNH-Colen** [comment]
I kinda agree that inf bees should be removed at least, they are utterly useless bloat. We should really look into making infinity hard to get but that is another issue.

**Comment by 0lafe** [comment]
List would be infinity, infinity catalyst, cosmic Nt, GT neutronium, americium, trinium, SpPu and mysterious crystal. 

I'd also suggest removing the bees that still produce nuggets of stuff like copper/nickel, but I'm unsure of all that exist.

**Comment by Anarack** [comment]
Nugget bees do exist, but comb bees beat them out in output once you can throw enough power at it.
I am iffy on removing mysterious crystal and SpPu as those are not fusion bees.

**Comment by Ngar1** [comment]
> 
> 
> List would be infinity, infinity catalyst, cosmic Nt, GT neutronium, americium, trinium, SpPu and mysterious crystal.
> 
> I'd also suggest removing the bees that still produce nuggets of stuff like copper/nickel, but I'm unsure of all that exist.

Bee, they produce nuggets,: 
Why removing binnies/forestry/magic(?) bees? In my opinion, the GT bee (combs for Ore multiplying oder UUxComb=dust) are less interesting, because the similar function is available by crop - so they are redundant. I prefere bees, they collect things (usefull and less usefull).

**Comment by chochem** [comment]
> 
> 
> List would be infinity, infinity catalyst, cosmic Nt, GT neutronium, americium, trinium, SpPu and mysterious crystal.

thats a no from me, unless its embedded in a much larger change. the main problem here is that you didnt consider the secondary consequences:
- removing the neutronium bee would make the advanced mutatron uncraftable.
- removing these bees make at least the following ones also unobtainable: uranus. neptune, oberon, miranda, oriharukon, pluto, proteus, triton, aCentauri, barnadaF, barnadaC. I might be missing some.

**Comment by 0lafe** [comment]
We can make the comb literally anything other than Nt. If we can remove the products from the Nt comb I guess that works too. 

If that's just breeding we can make them not require that bee

**Comment by chochem** [comment]
If you dont just remove them like proposed, but change all things around them too, then the situation is different obviously. It just looked like you hadn't even looked at that ;)

**Comment by Zeruel13** [comment]
As someone who knows nothing about balance but likes collecting different types of bees, I say nerf if you need to but don't remove them. I like to collect all bees and even if they're worthless I still like the idea of having an infinity or neutronium bee as a trophy item just for the challenge.
