### ISSUE TITLE
2.1.1.0 Update List

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#6423]
Here we put all stuff in that need to be changed till the next update.

**Comment by GTNH-Colen** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6007 - Teleport rebalance
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6414, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6416, #6399, #6357 - Lag issues (Requires code changes)
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6260 - DD Portal nerf

**Comment by Dream-Master** [comment]
Botania addition #6446

**Comment by Prometheus0000** [comment]
The botania thing isn't going to happen any time soon, if ever. It doesn't belong on this list.
