### ISSUE TITLE
Crafting Mud Balls causes buckets to duplicate

### ISSUE THREAD

**Issue by Qawler** [GTNewHorizons/GT-New-Horizons-Modpack#6424]
#### Which modpack version are you using?
2.0.9.0

#### What did you try to do, and what did you expect to happen?
While crafting mudballs with a water bucket and dirt I expected to get the two mudballs and one bucket

#### What happened instead? (Attach screenshots if needed)
Instead, I got 2 mudballs and 2 buckets back

**Comment by chochem** [comment]
please use the search function. this is ticket no. 6 or 7 I think. see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6354 for example.

**Comment by Qawler** [comment]
Oh, I'm sorry

**Comment by Dream-Master** [comment]
@Qawler if you find any new bugs feel free to open up issues. Thanks
