### ISSUE TITLE
assembling line controller turned into a .name

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6425]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
delta
#
####
i made the data bank multiblock from TecTech. It worked great, recipe worked, then the assembling line went into idling mode.
Sometime after that, i got a .name instead of the controller. It's not visual because another player confirmed seeing it. Wrenching it gives back the controller, but did not wanted to right click on it to see if it crashes the game.

![2020-07-22_23 21 18](https://user-images.githubusercontent.com/12850933/88230785-4fc77b00-cc73-11ea-878e-89edb9ad97c9.png)

it reminds me of the random corruption of GT disassemblers (#3864 and #4132)

**Comment by Dream-Master** [comment]
@Technus any idea ?

**Comment by Technus** [comment]
Try replicating and send gt logs. Most likely nbt is corrupt. If you could send nbt it would be great too.
