### ISSUE TITLE
Thaumcraft script text and localizer messed up

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#6426]
Thaumcraft script text and localizer messed up
NH, Blood Magic and Witchery pages are messed up
@seitenca any idea? You was the one changing the scripts to add minetweaker legacy support.
![image](https://user-images.githubusercontent.com/2970688/88258984-af4c7780-ccc1-11ea-9a5d-11999a1fd87f.png)
![image](https://user-images.githubusercontent.com/2970688/88259085-e3279d00-ccc1-11ea-85ee-e474d004b443.png)

**Comment by Anarack** [comment]
This can be fixed by leaving and entering the game and seems to just happen ever once in a while.

**Comment by Dream-Master** [comment]
i fixing it allready @Anarack
