### ISSUE TITLE
Brownstone doesn't speed you up anymore

### ISSUE THREAD

**Issue by makamys** [GTNewHorizons/GT-New-Horizons-Modpack#6427]
#### Which modpack version are you using?
2.0.9.0
#
#### What did you try to do, and what did you expect to happen?
Run on Rough Brownstone and expect to be sped up.
#
#### What happened instead? (Attach screenshots if needed)
I ran at normal speed.
#
#### What do you suggest instead/what changes do you propose?
It worked correctly before I upgraded from 2.0.8.3. I didn't find anything relevant in the changelogs, so I assume it wasn't an intentional change.

**Comment by Prometheus0000** [comment]
I was testing with Brownstone the other day and one of the alternate versions (I think it was Road) worked.

**Comment by makamys** [comment]
Just checked with all the variants (rough, smelted, and all the chiseled versions) and none of them worked, as opposed to GT concrete and catwalks, which still work.

**Comment by makamys** [comment]
Er, it happened on singleplayer with just the base GTNH mods. I don't play GTNH these days so I can't confirm if this is still an issue.

**Comment by YannickMG** [comment]
It definitely lets you run fast right now, though the implementation results in jerky movement compared to what Catwalks do.
