### ISSUE TITLE
Super buffer threaded can't count

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6428]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
Ultimated Superbuffer (Threaded) filled with tiny dust via ME
Output programmed to 9 (or to 63 tried both)
Output goes into input Hatch of Amazon Warehouse with Dust Schematics
![tiny_Superbuffer_01](https://user-images.githubusercontent.com/7759876/88282581-20a02080-ccea-11ea-9e0b-f9fab2c19fcd.JPG)
#
#### What happened instead? (Attach screenshots if needed)
=> input hatched doesen't filled up in modulo 9, some stacks filled higher (x64 but summ is not a part of 9)
![tiny_Superbuffer_02](https://user-images.githubusercontent.com/7759876/88282591-2564d480-ccea-11ea-994f-3eac7f66fd81.JPG)
#
#### What do you suggest instead/what changes do you propose?
programmed superbuffer shall learn to count :-)

**Comment by chochem** [comment]
as far as I know the threaded superbuffers are legacy and shouldn't really be used anymore ever since the (normal) superbuffers got reworked. If somebody can confirm that (alk/moron/mitch?), then they should probably be disabled.

**Comment by draknyte1** [comment]
Yeah don’t use them lul. 
I thought I removed their recipes ages ago.

**Comment by chochem** [comment]
Also, looking at your picture again, it actually looks like you just used the wrong mode. this will also be the same with the normal superbuffer. you want to use 'transfer size mode' otherwise you get a problem with slot merging inventories. alternatively you can turn sort mode off for the input bus, either works.

**Comment by Ngar1** [comment]
Same situation with super buffer. Programmed to: don't fill up. See picture
![tiny_Superbuffer_03](https://user-images.githubusercontent.com/7759876/88284550-e33d9200-cced-11ea-8b6e-7fdc483c1a72.JPG)
![tiny_Superbuffer_04](https://user-images.githubusercontent.com/7759876/88284559-e769af80-cced-11ea-9b3f-aee2b53ccb4c.JPG)

**Comment by Ngar1** [comment]
on Threaded Version, it is not possible to change the mode.

**Comment by chochem** [comment]
I have used transfer size mode for a long time, it never ever counted wrong. did you clear out the bus after changing the mode and setting it to 63?

**Comment by Ngar1** [comment]
Yes, but it seems to occure, If the amozon warehouse isn't fast enought to empty the hatch down to zero.

**Comment by chochem** [comment]
that does not matter in transfer size mode. I dont know if anybody else can replicate this, because I cant. 

Have you tried the alternative I mentioned? changing the mode of the bus with a screwdriver?

**Comment by Ngar1** [comment]
I leveld up the warehouse to higher voltage, and now the fill up by buffer ist all times slower. So the problem seems solved, by this.
The buffer was cleaned  and unused before.
The problem was easily replicable again, by stopping output hatch voiding -> input hatch filled up without modulo 63.

**Comment by Ngar1** [comment]
I builded it compleet ne and now it worked also if i let the input hatch overflowing. It seems, that the output mode of the buffer where changed without any info in chat.

Thanks all for suporting me such fast and competent!!!
