### ISSUE TITLE
[Quests] Underground Fluids

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6429]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### Description misprint
![изображение](https://user-images.githubusercontent.com/47714084/88283989-4252d500-ccf5-11ea-8aae-c6b00eb02252.png)

![изображение](https://user-images.githubusercontent.com/47714084/88283976-3830d680-ccf5-11ea-90dd-b1025b9ce73f.png)

**Comment by chochem** [comment]
you could really write at least one sentence. do you mean this https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6387?
or just that its min-max instead of max when min>0?

**Comment by MotiasF33** [comment]
> 
> 
> you could really write at least one sentence. do you mean this #6387?
> or just that its min-max instead of max when min>0?

- I mean "-"
Example:
```
Pluto:
Fluorine min 80 - max 4800
```
- And i think need add `-` as
```
Tier 7:
- Makemake
Hydrofluoric Acid 80 - 300
```

**Comment by chochem** [comment]
no thats not what it means. its weight: 80 min:4 max:800, but min is dropped whenever it is 0.
Thanks for the clarification though. Just a questbook fix then. The whole quest might deserve a better format tbh.

**Comment by MotiasF33** [comment]
> 
> 
> no thats not what it means. its weight: 80 min:4 max:800, but min is dropped whenever it is 0.
> Thanks for the clarification though. Just a questbook fix then. The whole quest might deserve a better format tbh.

It would be great to have an understanding of what these numbers are :3

**Comment by chochem** [comment]
![image](https://user-images.githubusercontent.com/40274384/88287402-24cc3e00-ccea-11ea-8b3b-98cb4eb659dd.png)
but yeah, it doesnt mention min and the format is a bit inconsistent, I agree.

**Comment by Prometheus0000** [comment]
I didn't want to type a bunch of useless zeros. I'll adjust it next time I edit quests.
