### ISSUE TITLE
[Cutting Machine] Obsidian Plate (not profitable)

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6430]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### Cutting recipe give 1 obsidian plate from 1 obsidian
![изображение](https://user-images.githubusercontent.com/47714084/88286903-2b62b180-ccfa-11ea-9358-cf9a6f52ad28.png)
### Whereas Bending 1 obsidian ingot=obsidian plate
![изображение](https://user-images.githubusercontent.com/47714084/88286941-3d445480-ccfa-11ea-95af-7b7ca369285d.png)
### Obsidian ingot have from Alloy smelter recipe
![изображение](https://user-images.githubusercontent.com/47714084/88286985-55b46f00-ccfa-11ea-984e-edaca5fe2a1d.png)

**Comment by boubou19** [comment]
obsidian always had balancing issues (#3707 for exemple) and the plate bending recipe was added to adress issue #3092

**Comment by Dream-Master** [comment]
i remove all recipes that are not profitable.
