### ISSUE TITLE
[Twitch Launcher] ic2 and ae2 was not found when I finish the download in the lunching mc software.

### ISSUE THREAD

**Issue by Yecgaa1** [GTNewHorizons/GT-New-Horizons-Modpack#6431]
#### Which modpack version are you using?
2.0.9.0

#
#### What did you try to do, and what did you expect to happen?
lunch the game
#
#### What happened instead? (Attach screenshots if needed)
1.Baubles-1.7.10-1.0.1.10 is failed to download(dropbox told me 404)
2.ic2 and ae2 was not found when I finish the download in the lunching mc software.

In addition,I use hmcl to be lunching,instead of twitch

**Comment by chochem** [comment]
multimc and technic are the two recommended launchers. Any other option is not really supported currently.

technic is very straightforward. multimc has instructions here: https://gtnh.miraheze.org/wiki/Installing_and_Migrating

have a nice lunch ;)

**Comment by Yecgaa1** [comment]
However the dropbox seems didnt have the baubles-1.7.10-1.0.1.10.jar

**Comment by Yecgaa1** [comment]
And I use mmc,but the problem is same,ic2 ae2 was not found

**Comment by chochem** [comment]
download the pack here http://downloads.gtnewhorizons.com/ClientPacks/ as the instructions say and also follow the other steps.

**Comment by Yecgaa1** [comment]
Not from the curseforge?

**Comment by chochem** [comment]
no.

**Comment by Yecgaa1** [comment]
ok,please let me have a try

**Comment by boubou19** [comment]
curseforge source is often causing troubles

**Comment by Dream-Master** [comment]
We need to programm a mod first to make it working.

**Comment by Yecgaa1** [comment]
> We need to programm a mod first to make it working.

I download the zip from curseforge,import to mmc,but the wrong is same

**Comment by Yecgaa1** [comment]
Now I use it following [](https://gtnh.miraheze.org/wiki/Installing_and_Migrating),may be it is the best choice

**Comment by Dream-Master** [comment]
the problem is not solved so I let this open so long I have a solution

**Comment by Yecgaa1** [comment]
> the problem is not solved so I let this open so long I have a solution

Ok，you are right ,thanks

**Comment by Prometheus0000** [comment]
Is it fixed now?

**Comment by Dream-Master** [comment]
fixed
