### ISSUE TITLE
[Computronics] Drone Docking Station and Upgrade not Craftable

### ISSUE THREAD

**Issue by PapaTim68** [GTNewHorizons/GT-New-Horizons-Modpack#6432]
#### Which modpack version are you using?
2.0.8.3
#
Wanted to craft the Drone Docking Station and Drone Docking Upgrade. Both have a Recipe, but parts of it are not craft able.
Especially the ComputerrCraft Transistors and the Quart Covered Pip form BC are not craft able.

![grafik](https://user-images.githubusercontent.com/29522870/88336614-99789a00-cd35-11ea-96bb-0ede5196f56e.png)
![grafik](https://user-images.githubusercontent.com/29522870/88336636-a4332f00-cd35-11ea-8e2e-270f0a11b82a.png)

**Comment by boubou19** [comment]
still applies to 2.0.9.0 QF4 , the quartz-covered pipe and the OC transistors are uncraftables

**Comment by Dream-Master** [comment]
i looking for recipes and i cant find any. Maybe i need to go into code and check them.
