### ISSUE TITLE
Quest 1403 "HV Steam Turbine" does not complete

### ISSUE THREAD

**Issue by GamerTriStuS** [GTNewHorizons/GT-New-Horizons-Modpack#6433]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### What did you try to do, and what did you expect to happen?
I made a turbine, but the quest does not count it.
The turbine that is required by the task and located in nei has a different description with the turbine that is crafted in the workbench
#
#### What happened instead? (Attach screenshots if needed)
#
![1](https://user-images.githubusercontent.com/52796465/88353783-7b2b9200-cd67-11ea-9d2f-0bc24bae5d58.jpg)

**Comment by Dream-Master** [comment]
@Prometheus0000 cyn you check this? Thanks
