### ISSUE TITLE
[IC2] Iridium reinforced alloy ingot recipe correction

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#6436]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
SP (but valid for MP as well)
#
#### What did you try to do, and what did you expect to happen?
IC2 iridium reinforced alloy ingot is crafted with iridium plates, reinforced alloy and either industrial diamond, exquisite cubic zirconia or exquisite industrial diamond from GT++.
#
#### What happened instead? (Attach screenshots if needed)

The exquisite industrial diamond from GT++ is not obtainable due to it not having a recipe (confirmed by Alk, see https://discordapp.com/channels/181078474394566657/401118216228831252/736205571962699797).

#
#### What do you suggest instead/what changes do you propose?
Remove exquisite industrial diamond from GT++ from 
recipe. Possibly replace it with regular exquisite diamond that can be obtained by either sifting or laser engraving.

**Comment by Dream-Master** [comment]
you can use all that items so why i would change it ? Gt++ isnt open source so nothing i can do here.
