### ISSUE TITLE
Allow for Cactus/sugar coke/coal to be used as fuel in coal boilers.

### ISSUE THREAD

**Issue by Cyhidraethe** [GTNewHorizons/GT-New-Horizons-Modpack#6438]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
-
#
#### What did you try to do, and what did you expect to happen?
Burn Cactus Coke in a small coal boiler as fuel.
#
#### What happened instead? (Attach screenshots if needed)
Nothing.
#
#### What do you suggest instead/what changes do you propose?
Allow to burn Cactus Coke, Cactus Coal, Sugar Coke and Sugar Coal in small coal boiler (and other boilers and coal ran machines) please.

**Comment by Dream-Master** [comment]
Yea will check what I can do.

**Comment by Dream-Master** [comment]
I added fuel for single block boilers of GT.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/88456629-59bdc980-ce7f-11ea-92bc-448a073cba08.png)
![image](https://user-images.githubusercontent.com/2970688/88456632-604c4100-ce7f-11ea-8dc7-c2ae238ae434.png)
