### ISSUE TITLE
uncrafting Ultimate capacitor (UHV) recipe wrong

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6440]
#### Which modpack version are you using?
GTNH 2.0.9.0QF4
#
the uncrafting recipe for the ultimate capacitor gives an UV ultimate battery instead of the UMV really ultimate battery 
![image](https://user-images.githubusercontent.com/57050655/88463799-ce135f80-ceb5-11ea-81ab-45329c5625f9.png)

@kekzdealer

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/88464303-e1282e80-ceb9-11ea-80b5-ace2044ed203.png)
![image](https://user-images.githubusercontent.com/2970688/88464313-e84f3c80-ceb9-11ea-82bf-4cc5ceb6c10b.png)
why it gives that item back ?

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/88464330-07e66500-ceba-11ea-8fba-4348413b1e37.png)
![image](https://user-images.githubusercontent.com/2970688/88464335-0ddc4600-ceba-11ea-93a5-d7a6b59833c4.png)
same here

**Comment by Prometheus0000** [comment]
Probably because you can make the LSC ultimate capacitor with either battery. You don't want people making it with the ultimate and uncrafting it to get the really ultimate one, do you?

Though if it stores which battery it was made from, then yeah, it's a bug.

**Comment by Dream-Master** [comment]
other recipes follow maybe a logic but first one not.

**Comment by Alexdoru** [comment]
all the assembly line recipes follow the same logic: it's a copy of the battery + framebox and screws : for example : 
![image](https://user-images.githubusercontent.com/57050655/89106019-a167c680-d426-11ea-8352-01f1501c9d8d.png)
and 
![image](https://user-images.githubusercontent.com/57050655/89106026-b5abc380-d426-11ea-9904-75a0d4cbceff.png)
![image](https://user-images.githubusercontent.com/57050655/89106044-d411bf00-d426-11ea-8f8f-62589e8de516.png)

So it makes it normal than the uncrafting recipe gives you the battery back, however the for the UHV capacitor it gives you the wrong battery. 

![image](https://user-images.githubusercontent.com/57050655/89106060-fc012280-d426-11ea-8825-cab98a99ef9f.png)
![image](https://user-images.githubusercontent.com/57050655/89106068-09b6a800-d427-11ea-8c04-c26a5fc86ecf.png)
