### ISSUE TITLE
Electric Air Filter will not form!

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#6441]
GTHN 2.0.8.9

Multiblock Air filter will not form no idea if bugged or if the tooltip is missing something. Played around in creative and for the life of me would not form. (If someone can explain this to me we need to make a quest or wiki article)
![2020-07-25_21 19 24](https://user-images.githubusercontent.com/15355637/88469496-146dbc00-cec0-11ea-8fec-024264f4a414.png)

**Comment by Dream-Master** [comment]
@redmage17 using 2.0.9.0 and test again. Thanks

**Comment by SBAngel810** [comment]
![20200726135944](https://user-images.githubusercontent.com/66779899/88472700-4e82a080-cf48-11ea-9d81-e7277c696b70.png)


![20200726135944](https://user-images.githubusercontent.com/66779899/88472743-bcc76300-cf48-11ea-8add-b2f750722e26.png)

tested two exactly same setup.
seems like the multiblock needs more air block around it to make sure it's working.

**Comment by ScriptedPiky** [comment]
If I remember correctly, there was a bug that I encountered a year or so ago that would cause the multiblock to not form if it was above a certain Y level. If it was below said Y level threshold, then it'll form normally, regardless of how many air blocks there were. I feel as if the multiblock deserves a rework or at least an investigation as to the silly behavior.

**Comment by Dream-Master** [comment]
@redmage17 did you test it with more air blocks around ?

**Comment by redmage17** [comment]
It needs 3 blocks of air specifically to form. Gonna make a a wiki article.
