### ISSUE TITLE
Binnie Mods 2.0-29.4-gtnh is named differently than other mods

### ISSUE THREAD

**Issue by sarperen** [GTNewHorizons/GT-New-Horizons-Modpack#6442]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
I looked at the modlist on Curse and saw Binnie Mods 2.0-29.4-gtnh not ending in -GTNH like other mods
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/43860774/88480726-4df60400-cf60-11ea-8060-427c526ecad9.png)

#
#### What do you suggest instead/what changes do you propose?
Rename Binnie Mods 2.0-29.4-gtnh to Binnie Mods 2.0-29.4-GTNH

**Comment by Prometheus0000** [comment]
@Dream-Master
