### ISSUE TITLE
UEV Electric Piston has 2 pixels miscoloured

### ISSUE THREAD

**Issue by sarperen** [GTNewHorizons/GT-New-Horizons-Modpack#6443]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Look at the UEV pistons sprite, and expect the 2 pixels on the bottom left be the same colour as the piston, like other pistons.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/43860774/88488856-faec7300-cf98-11ea-9b9b-5c8706660cd0.png)
(The blue piston has the 2 pixels on the bottom left be white)
#
#### What do you suggest instead/what changes do you propose?
The 2 pixels on the bottom left of the piston should be blue.

**Comment by sarperen** [comment]
Huh, this seems to be a design decision for all UEV parts. Still weird, but it seems intentional so I'm closing the issue.

**Comment by sarperen** [comment]
Image of other UEV parts for comparios
![image](https://user-images.githubusercontent.com/43860774/88488985-fbd1d480-cf99-11ea-8bc2-4a8366e70af3.png)

**Comment by leagris** [comment]
Also notes that these items don't use the meta-generated texture icons with colouring overlay but a distinct icon file for each tier. This is not in-line with Gregtech functional design.

**Comment by Dream-Master** [comment]
anyways i changed it
