### ISSUE TITLE
maxed quantum computer size is not recognized by the controller

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6445]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I wanted to build the maximum size of the quantum computer, so i used a stack of blueprints to be sure that it will display me the maximum size. Then i followed all the hints to build it.
#
#### What happened instead? (Attach screenshots if needed)
It does not form. But if i reduce it of 1 slice, it works correctly

**Comment by Prometheus0000** [comment]
Did you report it at his repo?
