### ISSUE TITLE
[T.F.F.T] with ME fluid storage bus

### ISSUE THREAD

**Issue by longyup** [GTNewHorizons/GT-New-Horizons-Modpack#6447]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### What did you try to do, and what did you expect to happen?
I set TFFT auto void true and put the ME fluid storage bus on TFFT mutli-fluid I/O hatch. if the TFFT was full,The fluid did not enter the TFFT but entered the ME fluid storage
#
#### What happened instead? (Attach screenshots if needed)
The fluid enter TFFT and be voided
#

**Comment by Dream-Master** [comment]
@kekzdealer any idea ?

**Comment by Prometheus0000** [comment]
@botn365 Did https://github.com/GTNewHorizons/KekzTech/pull/3 fix this?

**Comment by Prometheus0000** [comment]
Does the TFFT not work with multi hatches at all or just the ME one? As in, can you use a conduit to access the multi hatch properly?

**Comment by botn365** [comment]
im gone need to test this

**Comment by Prometheus0000** [comment]
Should be fixed by https://github.com/GTNewHorizons/KekzTech/pull/6.
