### ISSUE TITLE
[Disscussion] Rocket T5 Quest

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6448]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Eta
### Sure?Now i put it into the dire..
For what need this quest ?
We have the same previous quests, which are already boring, because contain crafting components
![изображение](https://user-images.githubusercontent.com/47714084/88707405-db7d5380-d11a-11ea-8b9f-383d1137b385.png)
![изображение](https://user-images.githubusercontent.com/47714084/88708073-c523c780-d11b-11ea-93ba-6edeb611b68f.png)

### I think it's worth leaving only this quest
![изображение](https://user-images.githubusercontent.com/47714084/88707911-94439280-d11b-11ea-9ebc-464453510e21.png)

**Comment by Cleista** [comment]
I created a Tier 5 rocket by following this quest about a week ago and didn't see any issues with it.

**Comment by Dream-Master** [comment]
@MotiasF33 if you boared not doning quests

**Comment by GTNH-Colen** [comment]
I think the point he is trying to make is that it's a bit annoying having quests with all the sub components in them, people often just end up crafting the item by accident without throwing it all in their inventory first (I've done this a few times, luckily not for something as expensive as a rocket though). 

For the first few sets of quests I can understand this but later on it's probably better to just check for the final product. A lot of the new later game quests do this, it makes life easier and you're less likely to screw stuff up. Plus it saves development time, no need to fill in for every single ingredient.

**Comment by chochem** [comment]
We actually had the very direct and short rocket quests initially. That was on purpose, I also preferred that. you have to take it up with yukieiji who decided that they need all this detail, and of course dream and prometheus who accepted the PR. This one: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6271

**Comment by Dream-Master** [comment]
sorry I like quests. It's not necessary to do quest to progress.

**Comment by GTNH-Colen** [comment]
> sorry I like quests. It's not necessary to do quest to progress.

It's not about removing quests, just making them more simple for the user. Say for example making this quest only require the T5 rocket to complete and not all the other sub parts. The cost is the same but it's less hassle for everyone.

**Comment by Cleista** [comment]
How about main quest requiring just T5 rocket with optional side quests to get/craft all the parts? This won't block people from completing it with just the rocket and keeps the other quests in there.

**Comment by Dream-Master** [comment]
fair enough we can change that. Or we doing it as or quest so if one is done you can progress further

**Comment by Prometheus0000** [comment]
The T5 Rocket quests were already there. Yukieiji added quests for the _new_ crafting components for the T6-T8 quests.

Dream, do you want me to make _all_ the TX rocket quests all just the rocket, or from a certain point on, or what?

**Comment by Dream-Master** [comment]
@Prometheus0000 nope let it like it is I take care

**Comment by Prometheus0000** [comment]
Are you ever going to fix this?
