### ISSUE TITLE
Item Detector Cover Shift Right Click Interface Issues

### ISSUE THREAD

**Issue by Godelboard** [GTNewHorizons/GT-New-Horizons-Modpack#6449]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Shift right click on block with item detector cover to configure via gui to change redstone mode. Also to set the detector to read all slots via the GUI.
#
#### What happened instead? (Attach screenshots if needed)
- The button to change redstone mode only allows you to go from Inverted --> Normal. Right now this has to be done with a screwdriver.
  - Normal --> Inverted toggle does not work.
- The redstone mode text also does not accurately reflect the current state of the block.
  - It instead seems to change when I change the slot number.
- The slot number can be changed from all but it can't be put back to all without a screwdriver.
#
#### What do you suggest instead/what changes do you propose?
- Make the button correctly swap modes and the label accurately reflect the current mode the cover is in.
- Add a button for reverting the slot examined to All? Maybe also add a confirm button since it's odd you have to press 0 to commit your option.
- Not part of the bug but suggestion: Have some helper text or tooltips that explain what the different controls in the GUI do?

**Comment by Dream-Master** [comment]
@moller21 any idea on this ?

**Comment by moller21** [comment]
Should be fixed https://github.com/GTNewHorizons/GT5-Unofficial/commit/884a268666ef8223b1b3fc6ccb4808700813c8e7, but don't think its included in the latest release of the pack. Basically the GUI didn't work at all before the patch.

You can save it by pressing tab, inventory key(e) or enter, so clear all text and press any of those keys. But i agree its odd it resets to slot 0 when right-clicked, not All slots. 

Any suggestions for tooltips/text?

**Comment by Dream-Master** [comment]
@Godelboard 
Any suggestions for tooltips/text?
