### ISSUE TITLE
Land claim coordinate

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6450]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i am crafting at my base and suddenly 
![image](https://user-images.githubusercontent.com/59776356/88773625-eedcfd00-d1b4-11ea-96e9-2fe4daac8562.png)

#
#### What happened instead? (Attach screenshots if needed)
i don't know where this happened
#
#### What do you suggest instead/what changes do you propose?
It's better to give a coordinate to let me know what exploded

**Comment by boubou19** [comment]
looks like there will be extra work to get the location of the explosion: mytown only search for the chunk coords https://github.com/GTNewHorizons/MyTown2/blob/09084210db9216739d0fd89d41873a54c76695a4/src/main/java/mytown/protection/eventhandlers/ExtraEventsHandler.java#L36

**Comment by boubou19** [comment]
implemented since december i believe.
