### ISSUE TITLE
Error - Tell Alkalus Ingot for vacuum freezing hydrogen

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/GT-New-Horizons-Modpack#6451]
#### Which modpack version are you using?
Latest
#
![image](https://user-images.githubusercontent.com/9472512/88803045-e61b0580-d179-11ea-92d6-8b120f96e5e2.png)

Putting a hydrogen cell in a vacuum freezer creates an "Error - Tell Alkalus Ingot" If you check the recipe for the ingot using NEI you can also see a bunch of other odd recipes that make the same ingot. This probably isn't a huge issue but I'm adding it to the list regardless.

**Comment by chochem** [comment]
wrong place to report and already reported: https://github.com/alkcorp/GTplusplus/issues/678

Can be closed.
