### ISSUE TITLE
[Suggestion] Containment Box

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6452]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### I want suggest add radioactives materials to storage in Containment Box
like as enriched naquadah, naquadria and others
![изображение](https://user-images.githubusercontent.com/47714084/88866289-eb785e80-d212-11ea-8bc7-77a561c2a141.png)
And using Containment Box like as a Forestry backpack
### Example use:
Using RCM hand Containment Box with Naquadah bolt, upload content to Naquadah Reactor 
#_It will give new life the Box_

**Comment by draknyte1** [comment]
IC2 is closed source and it probably can’t be changed.

**Comment by Cleista** [comment]
We have a lead-lined box for radium decay already, why not an item version?

**Comment by 4gname** [comment]
I have the source code for ic2, if someone wants to do, leave feedback.

**Comment by draknyte1** [comment]
So do I and many people.. we can’t use it for a custom build. Unlike you Russians, that’s definitely not allowed anywhere else. (Unless you’re Chinese)

**Comment by 4gname** [comment]
Dude, what's the problem with using api IC2, and codding in GTNHcore.

**Comment by hohounk** [comment]
Does IC2 api have the functionality for modifying the behaviour of the containment box?

**Comment by Dream-Master** [comment]
@4gname if you have the source just share it with me thanks
dream-master@gmx.net

**Comment by repo-alt** [comment]
Don't see how source will help, you can just as well decompile the jar. It is the license that is a problem.

**Comment by 4gname** [comment]
@Dream-Master added you to a private repository.

https://github.com/4gname/IC2
