### ISSUE TITLE
Make Oxygen Tanks last more time. {Suggestion}

### ISSUE THREAD

**Issue by Regian24** [GTNewHorizons/GT-New-Horizons-Modpack#6453]
Having to refill your oxygen tanks every 10 minutes when you're in space is very annoying, so maybe you could make them bigger? Like 1 oxygen tank can be filled with 1 full cell of liquid oxygen and last an hour instead of filling with just a bit of liquid oxygen and last 10 minutes.

**Comment by Dream-Master** [comment]
maybe we can add bigger tanks

**Comment by Cleista** [comment]
Right now there's very little time difference between small tanks and large tanks, but nothing between large and infinity (which is where you spend most of your gameplay time in).  

Maybe a Trinium tank that lasts 1h can be added? It'll fit into LuV nicely and makes sense as a tank material considering what Trinium is.

**Comment by Regian24** [comment]
Yeah that sounds like a cool idea. In Original Galacticraft they had better oxygen tanks every tier of rocket,maybe we could do the same here.

**Comment by Dream-Master** [comment]
@Regian24 in 1.12 Version ?

**Comment by Regian24** [comment]
No in 1.7 too. They have small tanks for tier 1 rocket, medium tanks after unlocking moon, and large tanks after unlocking mars

**Comment by Dream-Master** [comment]
we have 3 tanks in the pack

**Comment by Regian24** [comment]
yeah we could make the level 4 tank unlocked with Trinium.

**Comment by Pnc6lx** [comment]
in fact, infinity tank cant be equipmented. so if you get that, you still have to refill your tanks.
