### ISSUE TITLE
Nerf Thaumium Reinforced Jars

### ISSUE THREAD

**Issue by WizardSleve280** [GTNewHorizons/GT-New-Horizons-Modpack#6454]
In vanilla Thaumcraft, the only upgrade you can make to a warded jar is a warded reservoir, which needs void metal to make and is around 2/3 of the way into Thaumcraft. However, thaumium reinforced jars are able to be obtained right after you unlock regular warded jars, which are both less expensive and obtained much earlier than the warded reservoir. Both of these reasons make warded reservoirs essentially useless in comparison. I personally feel that the amount of space in the thaumium reinforced jars should be reduced to 192 essentia instead of 256 in order to both give warded reservoirs a use and not give you so much storage so early on. (ichor reinforced jars are fine because they are much more expensive than thaumium reinforced jars and are obtained at end game Thaumcraft)

**Comment by Ethryan** [comment]
Why not lock the Reinforced Jars behind the Warded Reservoir. That way you will have to reach deeper into thaumcraft for them.

**Comment by Alastors** [comment]
> In vanilla Thaumcraft, the only upgrade you can make to a warded jar is a warded reservoir, which needs void metal to make and is around 2/3 of the way into Thaumcraft. However, thaumium reinforced jars are able to be obtained right after you unlock regular warded jars, which are both less expensive and obtained much earlier than the warded reservoir. Both of these reasons make warded reservoirs essentially useless in comparison. I personally feel that the amount of space in the thaumium reinforced jars should be reduced to 192 essentia instead of 256 in order to both give warded reservoirs a use and not give you so much storage so early on. (ichor reinforced jars are fine because they are much more expensive than thaumium reinforced jars and are obtained at end game Thaumcraft)

this is a stupid statement and not true, the reservoir is still usable as a multi essentia jar, and you are missing the idea that the reservoir is doable in lv, while the jar is only doable in HV+. 

I dont care if you think this is not the normal thaumic route, this has become more and more common since I've come to the scene
