### ISSUE TITLE
Nano circuit requieres weird soldering alloy amount

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6456]
#### Which modpack version are you using?
GTNH 2.0.9.0QF4
#

It requiers 3670L of soldering alloy wich is 26,1111 ingots, that's weird. Make it 26 or 27 or 32 ingots, an integer amount of ingots please.

![image](https://user-images.githubusercontent.com/57050655/89053350-5c289380-d357-11ea-8ce6-060112856fe4.png)

**Comment by leagris** [comment]
26 ingots and 1 nugget

**Comment by Dream-Master** [comment]
yea i can change it to 26 ingots if that help

**Comment by Prometheus0000** [comment]
See #6649
