### ISSUE TITLE
[Suggestion] Remove Backpack aspects 

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6458]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### I want suggest remove Backpack aspects because it don't have a profit but only harm
Example  :
You accidentally dropped bag into the thaum-oven
![изображение](https://user-images.githubusercontent.com/47714084/89075078-0d462280-d386-11ea-9c23-c93d3c8a5a8d.png)

**Comment by Dream-Master** [comment]
then dont drop it by accident

**Comment by Regian24** [comment]
the thaum-oven says om nom noom

**Comment by Prometheus0000** [comment]
Delicious
