### ISSUE TITLE
Multiblock Electrolyzer won't do the recipe if there is any other dust inside

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#6468]
So I'm not sure if this behavior specific to Multiblock Electrolyzer or to all GT machines.

For example there is 6 garnet dust recipe and 6 ruby dust recipe. If there is 5 garnet dust inside the Input Bus, and 7 ruby dust, then even though there is enough Ruby to start the recipe, it will not start anyway.

Why this is a problem? Imagine someone has for example 10 types of dusts, in quantity of thousands and he needs to electrolyze all of that. The simpliest solution for him would be to set up ME Interface, put 9 types inside and just pull everything into the Electrolyzer. But because of this limitation and user not knowing if the amount is divisible by the amount required by recipe he can not do that.

So what, he should go the other way? But any other way is rather stupid. He would have to use a dedicated electrolyzer for each type of dust, or make AE recipe patterns with the exact amount and make for example Export Bus request the crafting of those items. All of this put pretty useless extra work for automation of something that should be pretty straightforward "I put enough dust for recipes and please electrolyzer use that if this is enough". So something that would probably work out of the box in any other place, here has received some limitations...

**Comment by Dream-Master** [comment]
@nikitinalexx is this a gt++ machine ?

**Comment by nikitinalexx** [comment]
No, it says GregTech

**Comment by boubou19** [comment]
the industrial electrolyzer is GT++. If you wan to have the correct amount of dusts, use super buffers, set the output stack size like you want, then use the transfer mode.

**Comment by nikitinalexx** [comment]
But the variety of size is between 2 and ~60. This means you will need 60 super buffers, 1 for each stack size.

**Comment by nikitinalexx** [comment]
Yes, you can use multiplied stack sizes to cover 2 smaller sizes, but it still brings you to build a solid amount of buffers.

**Comment by boubou19** [comment]
here is the result of a little python script i made:

```
{	
'64': [1, 2, 4, 8, 16, 32, 64],
'63': [3, 7, 9, 21, 63],
'62': [31, 62],
'61': [61],
'60': [5, 6, 10, 12, 15, 20, 30, 60],
'59': [59],
'58': [29, 58],
'57': [19, 57],
'56': [14, 28, 56],
'55': [11, 55],
'54': [18, 27, 54],
'53': [53],
'52': [13, 26, 52],
'51': [17, 51],
'50': [25, 50],
'49': [49],
'48': [24, 48],
'47': [47],
'46': [23, 46],
'45': [45],
'44': [22, 44],
'43': [43],
'42': [42],
'41': [41],
'40': [40],
'39': [39],
'38': [38],
'37': [37],
'36': [36],
'35': [35],
'34': [34],
'33': [33]
}
```
As you can see, you need 32 superchests to cover them all, but a lot of them are rarely used. The rarely used ones are often used by gt++ dusts. to route the items efficiently, you can use SFM.

**Comment by nikitinalexx** [comment]
So such Electrolyzer behavior is intended?

**Comment by boubou19** [comment]
yes

**Comment by Prometheus0000** [comment]
Already reported to the GT++ repo https://github.com/alkcorp/GTplusplus/issues/689

**Comment by boubou19** [comment]
iirc it happens in the centrifuge as well
