### ISSUE TITLE
[RFC] Galaxy Space Rewrite

### ISSUE THREAD

**Issue by glowredman** [GTNewHorizons/GT-New-Horizons-Modpack#6469]
Galaxy Space being closed-sources has been a fairly big problem in the past and contnues to be. The reason is, that it is not easily possible to alter any of the mods mechanics which makes balancing or fixing bugs very difficult. DreamMasterXXL repeatedly stated that replacing an other mod like Extra Planets is not an option, instead [someone has to rewrite Galaxy Space](https://discordapp.com/channels/181078474394566657/673270669802340379/736950373151014972). This would allow for heavy changes/additions. In my opinion, it's important to first clear up some points before someone* can rewrite it:

- Which features have to be carried over and which features can be left out becuase they are obsolete in GTNH?
- Can/want we use the original assets? If we want to, we would have to ask for permission though.
- The meta-values of certain blocks/items might not be reasonable anymore. Do we keep them as they are anyway or do we change them to better fit our needs? If we change them, should there be a transition-phase where players can convert their existing items to the new ones (If so, how long would such phase be?)? 
- Can/want we keep "Galaxy Space" as the name?

Furthermore, I think it is important that we first carry over existing features before adding completely new ones.

*I could give it a try, but there are certainly people with more experience than me, but they obviously need to want to do it and have the time for it.

**Comment by Regian24** [comment]
> Can/want we keep "Galaxy Space" as the name?
Space: New Horizons

**Comment by glowredman** [comment]
> 
> 
> > Can/want we keep "Galaxy Space" as the name?
> > Space: New Horizons

We would need to keep "galaxyspace" (iirc) as the modid though to ensure backwards compat

**Comment by boubou19** [comment]
exchanging a mod with another one needs intensive testing to be sure that the existing worlds aren't corrupted. You can change the modid as long as you provide a tool to convert the existing world, but that would increase significantly the workload.

**Comment by Regian24** [comment]
> We would need to keep "galaxyspace" (iirc) as the modid though to ensure backwards compat

yeah that's fine , it was just an idea.

**Comment by glowredman** [comment]
> yeah that's fine , it was just an idea.

modid =/= modname (in case I confused you)

**Comment by Regian24** [comment]
i know, the mod id is like dreamcraft:something and the mod name is "GT: New Horizons"

**Comment by Dream-Master** [comment]
that's because it has the name dreamcraft first. It was changed to GTNH after we start with the core mod.

**Comment by Ethryan** [comment]
Link to Galaxyspace [License](https://github.com/BlesseNtumble/GalaxySpace/blob/master/LICENSE)

**Comment by boubou19** [comment]
since there is no source code on the GalaxySpace repo, i don't know if it applies to the source code too.

**Comment by draknyte1** [comment]
What actually needs to be changed?
![84E329F4-E8BC-4EC1-A8A3-F810DFA6C804](https://user-images.githubusercontent.com/3060479/89162139-8488db80-d56b-11ea-8d40-826de18d440f.png)

**Comment by Dream-Master** [comment]
Plansts are boring so we need much more different content on planets

**Comment by Regian24** [comment]
I have some idea for the dungeons.

**Comment by Dream-Master** [comment]
we need new epic boss fights

**Comment by Regian24** [comment]
seriously tho, the pluto boss is a wolf, and that isn't very epic cuz it's literally the final boss of space

**Comment by Josh5minus1** [comment]
Tier 9 and 10 planets

**Comment by Regian24** [comment]
other galaxy exploration in galaxy space , that sounds fun

**Comment by Josh5minus1** [comment]
I made a Galacticraft addon to add some crazy planets and stuff... It's only for purpose of learning Java, and for myself, most of code is just copy pasted.. 😭

**Comment by Josh5minus1** [comment]
If only there's one who can rewrite the code

**Comment by glowredman** [comment]
> 
> 
> If only there's one who can rewrite the code

I could at least give it a try

**Comment by glowredman** [comment]
I made a spreadsheet containg all(TM) current features of GS.
Please add your ideas there (and mark them as new ideas). Please do not remove entries just because you think they are not fitting, but rather discuss them (and already existing features) here or in #galaxy-space-discussion.

-> https://docs.google.com/spreadsheets/d/1AKo92mPeUYGcndSMs5QpvunHR9LQzjNKFNEh48Gp7gg/ <-

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/New-Horizons-Space

**Comment by Ethryan** [comment]
https://github.com/GTNewHorizons/New-Horizons-Space = source set to private according to agreement with author on discord.

**Comment by Dream-Master** [comment]
if somone want to help please pm me on Discord.
