### ISSUE TITLE
advanced nitinol can't be created (gt++)

### ISSUE THREAD

**Issue by zgggz** [GTNewHorizons/GT-New-Horizons-Modpack#6470]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
prospercraft
#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
need to add recept for dust or for alloy blast smelter.

**Comment by chochem** [comment]
I dont understand. What is wrong with the current recipe? I assume you have a quantum anomaly, where exactly is the problem?

**Comment by chochem** [comment]
Well I assume this was just a combination of not reading the questbook, not looking sufficiently in NEI, and not searching in discord all at once. Can be closed.

**Comment by zgggz** [comment]
Thank you man. Can be closed.

**Comment by chochem** [comment]
you can close it yourself. I just wrote that because I cant :P
