### ISSUE TITLE
Arcane Worktable and Infusion Altar do not accept the same tier circuit

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#6474]
#### Which modpack version are you using?

# 2090
#### What did you try to do, and what did you expect to happen?

The Arcane Worktable and Infusion Altar dont accept the same trie circuit,only the one showed in nei is workable.
#### What do you suggest instead/what changes do you propose?
Could you make all the same trie circuit acceptable.

**Comment by Dream-Master** [comment]
ore dict us not possible with minetweaker. So I need to add 3 more recipe each recipe have circuits.

**Comment by GlodBlock** [comment]
@Dream-Master 
i think you can just add recipe for every circuit to make the mainframe circuit of the same tire

**Comment by Dream-Master** [comment]
Sure that is possible but make the script and loading time longer

**Comment by Prometheus0000** [comment]
Have you decide we should do that, or not do that then? Also WTF is a trie circuit?

**Comment by GTNH-Afx237v7** [comment]
Same tier, aka oredict for the circuit. Should not be too difficult to change in the MT script?

**Comment by Prometheus0000** [comment]
We have to decide whether the extra loading time is worth it. And there's probably other recipes that would need the same thing. So it could add up.

I wish people would make use of the spellcheck at least.

**Comment by GTNH-Afx237v7** [comment]
I wish it was stated whether this affects a certain recipe, or all, or a certain addon to TC...
For sure you can use oredict when doing arcane crafting terminal (see #6562 ). 
@GlodBlock Any more details?

**Comment by GlodBlock** [comment]
All of recipes of TC worktable and infusion altar have the same PROBLEM.
Oredict doesn't work for them

**Comment by Glease** [comment]
Dream's impression seems to be based on ancient versions we don't use any more. We can indeed use oredict in both of the recipes. 

Arcane workbench recipes using oredict: https://github.com/CyricV/TelluraPack/blob/79c946bef68bd90222d594fd6132682556afa842/scripts/ender_io.zs#L386-L388

All ingredients of Infusion recipes are implicitly oredict aware and will try to use oredict wherever possible. Just pass in any item with desired oredict name will work.

**Comment by GlodBlock** [comment]
Well,it's good news for us.

**Comment by Prometheus0000** [comment]
The electric goggles of revealing even has this done already. I'll go through them.

**Comment by Prometheus0000** [comment]
Were there ones not in EMT or TE? I replaced all of those, but I want to do it all at once.

**Comment by Prometheus0000** [comment]
I found where the arcane abacus recipe is, but I can't fix it, as I don't understand the format: https://github.com/GTNewHorizons/WitchingGadgets/blob/07ac5c3602021124a8b812aa644c0d0c68b09e0f/src/main/java/witchinggadgets/common/recipes/WG_arcane_recipes.java#L62.

The magic energy absorber/converters are at: https://github.com/GTNewHorizons/GT5-Unofficial/tree/experimental/src/main/java/gregtech/common/tileentities/generators, but I can't even tell where the recipes are determined.

**Comment by Prometheus0000** [comment]
@Glease oredict for infusion recipes did not work. Is there something special I'm supposed to do other than changing an HV circuit from <gregtech:gt.metaitem.01:32706> to <ore:circuitMaster>? Or will giving it the first cause it to accept anything with the same oredict and it just doesn't look like it? It doesn't switch between them like for arcane table recipes.

**Comment by Prometheus0000** [comment]
Ok, I tested it and it does accept different circuits in the infusion recipes already, so the problem is telling players this. This includes the magic machines. The exception is the arcane abacus, which is a table recipe. So my previous commit was both broken _and_ pointless.

**Comment by Glease** [comment]
Magic generators' recipes are located here: https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L2860-L3062

But they are all infusion recipes. You don't really need to change it.
