### ISSUE TITLE
LUV plasma generator quest chain is an accidental trap

### ISSUE THREAD

**Issue by viljar290** [GTNewHorizons/GT-New-Horizons-Modpack#6475]
#### Which modpack version are you using?
2.0.0.9
#
#### If in multiplayer; On which server does this happen? 
eta
#
#### What did you try to do, and what did you expect to happen?
Questchain in LUV tier shows you how to make plasma into power with large plasma generator. 
its on LUV tier and tells you to make a luv buffered dynamo hatch, followup quest has you make a large draconium turbine.
That combination will instantly explode if actually made as it produces too much power.
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Change the quest to suggest making a normal draconium turbine ideally hinting that a large one will be better once you can make ZPM tier buffered dynamo hatches.

**Comment by Regian24** [comment]
bruh, a quest that insta-kills you

**Comment by chochem** [comment]
well Prometheus asked me for recommendations when he made the quest and I said normal draconium. Indeed I also recommended the large draconium one as one of the options in ZPM. Not sure why he deviated from that if what you say is true. see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6161#issuecomment-638075031
I hope it has at least the disclaimer to check yourself.
