### ISSUE TITLE
[TecTech] Only mainframe ciruits for TT recipes

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6477]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### For craftiing TecTech things can be using only Mainframe circuits
![изображение](https://user-images.githubusercontent.com/47714084/89211597-c8f79400-d5ca-11ea-8b9d-ed8c1cb0d251.png)
![изображение](https://user-images.githubusercontent.com/47714084/89211670-d44abf80-d5ca-11ea-983d-adac67d6bdab.png)
![изображение](https://user-images.githubusercontent.com/47714084/89211734-ddd42780-d5ca-11ea-920c-06cc485fe5fc.png)
![изображение](https://user-images.githubusercontent.com/47714084/89211778-f5131500-d5ca-11ea-9626-6074b474e449.png)

**Comment by Dream-Master** [comment]
@MotiasF33 can you try another circuit ? Maybe it shows only the first one.

**Comment by MotiasF33** [comment]
> 
> 
> @MotiasF33 can you try another circuit ? Maybe it shows only the first one.

![изображение](https://user-images.githubusercontent.com/47714084/89227753-e89cb580-d5e6-11ea-8319-5f20a7505ec8.png)

![изображение](https://user-images.githubusercontent.com/47714084/89227679-c5720600-d5e6-11ea-9c9d-0dde00c3cee4.png)
![изображение](https://user-images.githubusercontent.com/47714084/89227792-feaa7600-d5e6-11ea-812a-d2f5bbe51177.png)
![изображение](https://user-images.githubusercontent.com/47714084/89227803-036f2a00-d5e7-11ea-8f79-1e5c57902da9.png)

**Comment by Dream-Master** [comment]
@Technus

**Comment by Spartak1997** [comment]
A lot of recipes from TT don't use oredict.
