### ISSUE TITLE
Arcane crafting terminal pulls garbage items into the crafting slots

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#6479]
#### Which modpack version are you using?
2.0.9.0
(this was working fine in 2.0.8.3)
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Using the arcane terminal to craft recipes that have oredictionaried items
#
#### What happened instead? (Attach screenshots if needed)
1: If your AE system runs out of stock after a craft, it will fill the crafting grid with stone (or whatever happens to be the lowest block id in your AE)
2: If you shift-click the question mark on a recipe to autofill, it will only pull in the exact items shown when clicked, and stone for anything oredictionaried even if the appropriate item is available. For instance if you shiftclick for a machine with two circuits, it will most likely prefill one or both of with stone unless you wait for NEI's RNG to give you the preview that exactly matches the (nano/quantum/magneto/crystal/...) flavour that you have in stock.

![image](https://user-images.githubusercontent.com/8459776/89307522-7a510500-d671-11ea-802b-4f025d6805f5.png)

#
#### What do you suggest instead/what changes do you propose?
Please make sure I don't have to keep removing unrelated items every time I try crafting something.

**Comment by Cleista** [comment]
Fixing the oredict would be great, though even just removing the pulling stone thing would be a big help.

**Comment by Dream-Master** [comment]
@repo-alt any idea on this?
