### ISSUE TITLE
Golden apples only drop from golden oak leaves when breaking with shears

### ISSUE THREAD

**Issue by interestingusernam3** [GTNewHorizons/GT-New-Horizons-Modpack#6480]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
n/a
#
#### What did you try to do, and what did you expect to happen?
Broke lots of golden oak leaves, expected them to drop golden apples regardless of the tool used
#
#### What happened instead? (Attach screenshots if needed)
Golden apples were only dropped when shears (TC, Vanilla and BM bound ones work, didn't test other) were used to break the block
#
#### What do you suggest instead/what changes do you propose?
Either mention this behavior in the thaumonomicon entry or make golden apples drop with all tools.

**Comment by Prometheus0000** [comment]
Maybe mention what mod the tree is from?

**Comment by boubou19** [comment]
![image](https://user-images.githubusercontent.com/12850933/89351836-194a2100-d6b3-11ea-8852-34e49922516f.png)

**Comment by Dream-Master** [comment]
Original recipe i guess. No nerf yet

**Comment by MotiasF33** [comment]
Good source of golden apple !
_ran away_ plant :deciduous_tree:

**Comment by Prometheus0000** [comment]
Try doing it with just thaumcraft and thaumic bases to see if it's another mod interfering.

**Comment by interestingusernam3** [comment]
With only tc, tb and their dependencies, golden apples drop regardless of item used to break leaves

**Comment by Prometheus0000** [comment]
Then you need to either add or remove mods (try many at once) until you find which one messes with it. I know fastcraft causes leaf blocks to decay instantly for example (though I doubt that would be the problem).

**Comment by interestingusernam3** [comment]
Sorry but I don't care about this enough to spend that much time on it.

**Comment by Prometheus0000** [comment]
Then neither do we

**Comment by interestingusernam3** [comment]
This is a suprising response but an understandable one.

**Comment by interestingusernam3** [comment]
Context for people here from discord: Golden oak is absolutely useless even when working properly due to the gains*rates in gold being lower than the amounts used to create the sampling, and saplings drop only once every few trees grown on average. The above apply even with fortune IV. Basically, it's a meme item noone will ever use. 

I don't want to spend a dozen hours booting up Minecraft and doing the annoyingly long test requiered to find out if the rare drop works just to make something like this work properly and I understand that nobody else wants to do it. As for the suprising, I meant the close. Now stop saying mean things about me :(((((((((

**Comment by shawnbyday** [comment]
I'm re-opening this to recommend the following (for items that are bugged and no intention to fix):

- Disable the Item
- Delete any Quest Associated with Item
- Create an Info Quest to List Disabled Items

**Comment by interestingusernam3** [comment]
https://cdn.discordapp.com/attachments/326843254639165441/838511654114426910/fishy_on_me.mp4
