### ISSUE TITLE
[BartWorks] Mining Osmiridium Casing 

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6481]
#### Which modpack version are you using?
2.0.9.0.qf4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### Platinum group problem
![изображение](https://user-images.githubusercontent.com/47714084/89339535-016ca000-d6a7-11ea-886c-f9d418d91f2f.png)
![изображение](https://user-images.githubusercontent.com/47714084/89339548-06315400-d6a7-11ea-9a9d-3c731a384d64.png)

**Comment by Prometheus0000** [comment]
#5126
