### ISSUE TITLE
[Essential] TP commands

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6482]
#### Which modpack version are you using?
2.0.9.0.qf4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
### :red_circle:Teleportation commands like us /back, /warp /tpa e.t.c. dn't work while Ore Drlling Plant active..
When you try to teleport, a timer appears before teleportation, but after it ends nothing happens.
I cannot figure out how this could b related to miner.
https://youtu.be/lKDFE_I9BHk
#
_This problem occurs not only for me, but also for many other players_

**Comment by Prometheus0000** [comment]
Duplicate, do a search.
