### ISSUE TITLE
[Shadow Iron Dust] no proifitable recipe

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6483]
#### Which modpack version are you using?
2.0.9.0 qf4
### No profitable centrifuge recipe
Centrifuge recipe:
![изображение](https://user-images.githubusercontent.com/47714084/89556701-74e2ee80-d81a-11ea-8c9b-f826256da3d0.png)
![изображение](https://user-images.githubusercontent.com/47714084/89556943-c25f5b80-d81a-11ea-8445-4886cca11dfb.png)

Electrolyzer recipe:
![изображение](https://user-images.githubusercontent.com/47714084/89556871-abb90480-d81a-11ea-97e3-3ea7e424f957.png)
![изображение](https://user-images.githubusercontent.com/47714084/89556954-c7bca600-d81a-11ea-8ee3-6ef5b08f6ba0.png)

**Comment by Prometheus0000** [comment]
BTW profitable doesn't mean anything in this context. From the pictures, I'm guessing you think that it should be 2 instead of 3? It would be nice if you specified what all 3 materials are and the recipe to make the one being disassembled.

**Comment by Prometheus0000** [comment]
Explain better or I'm going to close it, since I can't tell what you want.

**Comment by Prometheus0000** [comment]
So you're saying that you think the EU cost (and time) should be the same for the centrifuge and electrolyzer recipe? Rather, one of them should probably be removed. Probably the centrifuge one. Unless that's what you mean, in which case I agree.
