### ISSUE TITLE
Where is the fast leaf decay function in GTNH?

### ISSUE THREAD

**Issue by TataTawa** [GTNewHorizons/GT-New-Horizons-Modpack#6486]
#### Which modpack version are you using?
2088

there is performance issue in leaf decay fast when chopping down a tree but i cannot find where the code of this function is in.

**Comment by moller21** [comment]
Randomthings does it with trough ASM:

`  private byte[] patchLeaveClass(byte[] basicClass) {
    ClassNode classNode = new ClassNode();
    ClassReader classReader = new ClassReader(basicClass);
    classReader.accept((ClassVisitor)classNode, 0);
    this.coreLogger.log(Level.INFO, "Found Leave Class: " + classNode.name);
    ClassWriter writer = new ClassWriter(3);
    classNode.accept(writer);
    String methodName = MCPNames.method("func_149695_a");
    String worldClass = "net/minecraft/world/World";
    String leaveClass = "net/minecraft/block/BlockLeavesBase";
    String blockClass = "net/minecraft/block/Block";
    MethodVisitor mv = writer.visitMethod(1, methodName, "(L" + worldClass + ";IIIL" + blockClass + ";)V", null, null);
    mv.visitCode();
    Label l0 = new Label();
    mv.visitLabel(l0);
    mv.visitLineNumber(81, l0);
    mv.visitVarInsn(25, 1);
    mv.visitVarInsn(21, 2);
    mv.visitVarInsn(21, 3);
    mv.visitVarInsn(21, 4);
    mv.visitVarInsn(25, 0);
    mv.visitMethodInsn(184, "lumien/randomthings/Handler/CoreHandler", "handleLeaveDecay", "(L" + worldClass + ";IIIL" + blockClass + ";)V", false);
    Label l1 = new Label();
    mv.visitLabel(l1);
    mv.visitLineNumber(82, l1);
    mv.visitInsn(177);
    Label l2 = new Label();
    mv.visitLabel(l2);
    mv.visitLocalVariable("this", "Llumien/randomthings/Transformer/RTClassTransformer;", null, l0, l2, 0);
    mv.visitLocalVariable("p_149695_1_", "L" + worldClass + ";", null, l0, l2, 1);
    mv.visitLocalVariable("p_149695_2_", "I", null, l0, l2, 2);
    mv.visitLocalVariable("p_149695_3_", "I", null, l0, l2, 3);
    mv.visitLocalVariable("p_149695_4_", "I", null, l0, l2, 4);
    mv.visitLocalVariable("p_149695_5_", "L" + blockClass + ";", null, l0, l2, 5);
    mv.visitMaxs(5, 6);
    mv.visitEnd();
    return writer.toByteArray();
  }`

**Comment by moller21** [comment]
And this: 

```
  public static void handleLeaveDecay(World worldObj, int posX, int posY, int posZ, Block block) {
    if (VanillaChanges.FASTER_LEAVEDECAY) {
      worldObj.func_147464_a(posX, posY, posZ, block, Settings.DECAY_SPEED + ((Settings.DECAY_FUZZ > 0) ? rng.nextInt(Settings.DECAY_FUZZ) : 0));
      return;
    } 
  }
```

Don't think we have the source, but if you wanna improve it I guess we could disable it here, and add it to the hodgepodge mod.

**Comment by Dream-Master** [comment]
@moller21 good idea. Thaumcraft trees not working.

**Comment by draknyte1** [comment]
TC trees are not meant to work. That’s intentional.

**Comment by TataTawa** [comment]
@moller21  thank you and i will try mod configuration first and see if it could solve the problem

**Comment by shawnbyday** [comment]
@TataTawa are we ok to close this issue? Do you need further help with the configuration? Will close after while if we don't hear back.
