### ISSUE TITLE
[Suggestion]  Quest #925 Tehnology: Evolved

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6487]
#### Which modpack version are you using?
2.0.9.0qf4
### Suggest change requires amount of coins for consume quest, from 10 "1000" to 10 "10k"
But when quest available, we have a much more.
![изображение](https://user-images.githubusercontent.com/47714084/89719178-44dc4c80-d9ce-11ea-9169-293df60c258b.png)
### I think retrieval should look like this:

- 10 Coin "The Dark Wizard 10k"

- 10 Coin "The Explorer 10k"

- 10 Coin "The Survivor 10k"

- 10 Coin "The Technican 10k"

- 1 Coin "The Space Invaders 10" (1 because you can't farm this coins)

_Will the players have enough coins?
For example, now I have so many_
![изображение](https://user-images.githubusercontent.com/47714084/89719317-b23cad00-d9cf-11ea-8dc9-9e89a8c544ae.png)

**Comment by Prometheus0000** [comment]
There's already a ticket for changing this quest. Post over there.
