### ISSUE TITLE
[Draconic Evolution] Upgrade Modifier over cap slots

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6488]
#### Which modpack version are you using?
2.0.9.0qf4
### More fast clicking to  before reaching a limit, allows over modifier cap.
![изображение](https://user-images.githubusercontent.com/47714084/89719613-cafa9200-d9d2-11ea-9379-ff98af58fb33.png)
![изображение](https://user-images.githubusercontent.com/47714084/89719642-17de6880-d9d3-11ea-91cd-51eade8aafe1.png)

**Comment by MotiasF33** [comment]
"-7" because i don't have more cores :3

**Comment by GTNH-Colen** [comment]
Is this visual or do the stats keep stacking?

**Comment by MotiasF33** [comment]
> 
> 
> Is this visual or do the stats keep stacking?

stats keep stacking.
