### ISSUE TITLE
Angel ring

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6491]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i want angel ring
#
#### What happened instead? (Attach screenshots if needed)
no angel ring
#
#### What do you suggest instead/what changes do you propose?
add angel ring
![image](https://user-images.githubusercontent.com/59776356/89748106-2d977f00-daf4-11ea-871d-fc0db5129fe8.png)

**Comment by Glease** [comment]
For those who are not familiar with item:

1. Angel Ring is an item from ExU2 (whereas we have exu1)
2. Angel Ring provides creative flight and some cosmetic decoration
3. Angel Ring uses a new energy type in ExU2 which is quite easy to set up (by GTNH standard)
4. **ExU is not open source**.

**Comment by Dream-Master** [comment]
Angel Ring is disabled. We have enough jetpacks and flight abilities
