### ISSUE TITLE
lag spikes causes items to be moved chunks away in all directions.

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6492]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
 Ok i am asking this here, as i would like some more information if others have experiences this
 I have found that when a lagspike hits (might be the server save, i am not sure) the 5-20 second spikes
 And i am breaking something, when the server tick start up again, and it did break those blocks
they will be scattered everywhere, they will get blown chunks away even.
I was breaking some ender io solar pannels, and I am still finding them 3 chunks away
 and no my copter pack was not on,
 Anyone else seen this issue,
 I am asking here as i have seen a few people lose stuff when they break it doing a lag spike
My experience is on the prospercraft server and i dont know how to replicate this in single player

#
#### What do you suggest instead/what changes do you propose?
unknown

**Comment by Dream-Master** [comment]
Possible Thermos related or plugin related.
We have a newer Thermos version but never tested.

**Comment by Dream-Master** [comment]
@Devtron3D 
https://github.com/GTNewHorizons/Thermos/releases/tag/GTNH-UNOFFICIAL

**Comment by Devtron3D** [comment]
@Dream-Master 
when installing the latest thermos from that link.
it is missing a library file for joptsimple and idk where it is expecting it
