### ISSUE TITLE
UEV and (ZPM?) field generator recipe is wrong

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6493]
#### Which modpack version are you using?
GTNH 2.0.9.0QF4
#
the recipe should have gravi stars and UEV emitters to have the same logic as the others field generator recipes

![image](https://user-images.githubusercontent.com/57050655/89808600-ae796980-db3a-11ea-8ea1-3357e9c23d29.png)

this recipe only have 1 quantum star whereas the Luv field generator has 2, is this intended ? 
![image](https://user-images.githubusercontent.com/57050655/89808752-e4b6e900-db3a-11ea-995e-f7adaaae4955.png)

**Comment by GeicowithaBango** [comment]
Pls spare us the 4 UEV emitters, oh Lord Almighty

**Comment by Prometheus0000** [comment]
Both T9 and T10 don't use stars, probably because there isn't a high enough one? We could just add more to compensate though.

**Comment by Prometheus0000** [comment]
PS: FG VII = ZPM FG = LuV FG in code for some reason.

**Comment by Prometheus0000** [comment]
@Dream-Master I haven't made a PR about the emitters yet since I can't get TT to build, so this isn't done yet. I also made the FG X need nanos for consistency. Maybe the DD recipe should be made slightly easier as a result?
https://github.com/Prometheus0000/TecTech/commits/fgchange

**Comment by botn365** [comment]
this is the same for UHV field not having emittors
also UEV field should be 4 nanos instead of 8 UEV

**Comment by Prometheus0000** [comment]
I thought it was left out by accident so I added them to both.

> also UEV field should be 4 nanos instead of 8 UEV

I did this too

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/97125951-e2146a80-170b-11eb-84e5-05ebef742c88.png)
![image](https://user-images.githubusercontent.com/8517039/97125956-e6d91e80-170b-11eb-9719-9de0e0c4d0b5.png)
Can I go PR this now @botn365? Or do you disagree?

**Comment by botn365** [comment]
looks good to me
