### ISSUE TITLE
[RFC] Should Input Busses allow pulling 

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#6498]
#### Which modpack version are you using?
2.0.9.0
#

At the moment input busses do not allow logistics to pull from them in conventional ways. Seemingly not super significant, this allows for a lot more options in consolidation of infrastructure. I'm not sure if it's disabled intentionally, or just happens to be that way. 

Curious what other people think. Granted the circumventing methods have a lot of charm to them, and I don't know if I'd want to obsolete that.

**Comment by draknyte1** [comment]
Super busses already do. 
Standard ones should not be allowed to be pulled from.

**Comment by Prometheus0000** [comment]
I don't really understand why you would need to? If it's about circuits, you can just use more than one bus, right? Or another machine.

**Comment by 0lafe** [comment]
The idea was to make single machine consolidation more accessible, as I assume most people aren't using reforming logic on their machines. I wouldn't mind the super bus being the only one, but I think I saw someone mention that it has its own lag based issues. Not sure this mechanic needs to be gated in that way, due to how it's gated through complexity of construction.

**Comment by GTNH-Colen** [comment]
Could we not just add a single 16 slot special input bus that allows this behaviour?

Also yes the super buses do this but are absurdly laggy and should under no circumstances be used.

**Comment by 0lafe** [comment]
We could, but I'm not sure it really needs to be relegated to a specific bus. It mostly just allows you to do more without resorting to chunk reloading and block manipulation, which seems fine to give as a base point. I don't think gating would really play a huge roll, as you don't really need to touch this mechanic ever, or at least until very late game.  

It's also kind of nice to be able to automatically flush busses on multis if you fuck up your logistics too, and I'm not sure we need to disallow that

**Comment by draknyte1** [comment]
> Also yes the super buses do this but are absurdly laggy 

All busses are laggy, super buses just emphasise this. Beyond their slots and lack of GUI, they’re identical to normal buses. So if the code for them were to be optimised, then we’d have no issue.
