### ISSUE TITLE
4a and 16a energy hatches are too cheap

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#6501]
Let's take a look at IV energy hatch, it gives 1 A and is pretty difficult to craft, whereas upgrading it to IV 4A Dynamo Hatch costs just 4 tungsten, 2 tungstensteel and 1 silver. In IV tier this price is literally nothing.
If you want to get 4x amperage compaired to 1 A it should be at least comparable to what you spent for 1 A.
Even crafting the cables through your base at IV level is 100x more difficult, than making the Hatch that actually can output all those amperes.
And the same for 16a version, I think it should be more expensive. I mean we are already in IV, things should be extremely expensive by now!

**Comment by 0lafe** [comment]
We probably want harder recipes for 4A+ energy/dynamo hatches 

>I mean we are already in IV, things should be extremely expensive by now!

🙏🙏🙏

**Comment by Devtron3D** [comment]
To my knowledge say an EBF or LCR, will not work with those energy hatches, the only place i know they work are the mega EBF and the Power sub station for inputting power.  I atm only use 1x 16 amp hatch to put power into my substation, and I am about to hit LuV,

If they could be used in ANY machine, I would agree that a high cost is a must, would be nice to be able to overclock an IV EBF to turbo smelt with a 64Amp energy hatch, and then cry when you are out of power 5min later and have to wait 12-24 hours to recharge the full size substation :)

**Comment by Prometheus0000** [comment]
I believe they also work in kekz's power thing (lcs?). They're probably still a little too cheap right now though.

They don't work on other machines on purpose (or at least I assume so) so that you can't tier skip.

**Comment by 0lafe** [comment]
4A

ATM: 1A hatch, 2 4x w wire, 2 tungstensteel plate, 144L silver
5s EV

I propose: 1A hatch, 4 4x IV SC, 2 dense Ir plate, 64x ASMD, 4 180k Nak/HE coolant cells, 1296L silver
5s IV

~~~

16A

ATM: LuV-IV xformer, 4A hatch, 2 8x W wire, 4 WS plates, 144L electrum
10s EV

Proposal: LuV HI amp xformer, 4A hatch, 4 8x IV SC, 8 dense Ir plates, 16 wraps of ASMD's, 3 360k NaK/He coolant, 1 UHPIC wafer
20s IV

~~~

64A

ATM: 64A LuV xformer, 16A hatch, 2 12x W wire, 6 WS plates, 144L W
20s EV

Proposal: 64A LuV xformer, 16A hatch, 4 16x IV SC, 4 stacks of 8 dense Ir plates, 2 stacks of ASMD wraps, 5 360 NaK/He coolant, 4 UHPIC, 1152L solder, 1296L W, 8000L Radon
80s IV assline

~~~

Dynamos and xformers are another story, but i like this idea for hatches personally

**Comment by Devtron3D** [comment]
So with the Iridium plates you want to move the 16amp IV hatches to more or less end of IV and start of LuV ???

**Comment by Cleista** [comment]
I mean, look at the recipe for advanced SMD components too. Hardly a cost that makes sense. 

Build an expensive lapotronic supercapacitor and you aren't even allowed to input EU into it or extract it faster than a singleblock battery buffer (which can request 32A and output 16A) without costing an arm and a leg? This seems like an entirely unnecessary nerf.

**Comment by Prometheus0000** [comment]
Don't forget that you're not even starting to use ASMDs until LuV circuits.

Not sure when UHPICs are available though. If they're from the next tier, and that's when you're supposed to make the 16x+, then that's fine I guess?

**Comment by 0lafe** [comment]
Base energy hatches already use Ir, this gives a scaling Ir cost meant to emulate the Ir in multiple 1A hatches. UHPICs are doable with IV hatches, and are even pre assline iirc. This puts the 4A more into IV, needing more components, and infra, the 16A being more towards the later stages of lots of automation and power, and the 64A post assline pre LuV.

**Comment by alphaNOVAircraft** [comment]
Same issue applies to the Bufferd Dynamo Hatchs. Maybe even worse there because you can use those for turbines.

**Comment by Devtron3D** [comment]
The 4AMP hatches are VERY useful even for steam turbine multiblock and gas generator multi blocks, if they get gated, later on, it will be hard locating good turbine blades that will stay under 1 amp and be useful.
It will just force people to spam more single blocks generators.

**Comment by alphaNOVAircraft** [comment]
> The 4AMP hatches are VERY useful even for steam turbine multiblock and gas generator multi blocks, if they get gated, later on, it will be hard locating good turbine blades that will stay under 1 amp and be useful.
> It will just force people to spam more single blocks generators.

They are definitly VERY useful, and noone wants to make them unaviable, but they are a bit cheap, a bit too cheap, you would still be able to make them. And i dont think ppl would start spamming single block gens. Even with low eff low power turbines you still will get way more energy with it then with single blocks. I used a steam fluid reactor before the existance of the bufferd hatches, and its very much still viable using them.
