### ISSUE TITLE
add EV/IV singleblock diesel generator

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#6502]
#### Which modpack version are you using?

# 2.0.9
#### If in multiplayer; On which server does this happen? 

# sp
#### What do you suggest instead/what changes do you propose?
The large combustion engine is too expensive and bulky.I think a singleblock one would be better.

**Comment by 0lafe** [comment]
God no lol. Costly multiblock gen is a good thing for EV+

**Comment by GlodBlock** [comment]
> 
> 
> God no lol. Costly multiblock gen is a good thing for EV+

The multiblock one is much more costly than 4 HV gens and needs lubricant to keep it running.
If possble,I would choose to use 4 HV gens to power my EV machines,but too many gens cause lag.

**Comment by Cleista** [comment]
The multi is equivalent to 12 HV gens. 

The problem is there's only one tier of the multi which makes it a shitty complex solution that doesn't tier up with your own tech.

**Comment by GlodBlock** [comment]
> The multi is equivalent to 12 HV gens.
> 
> The problem is there's only one tier of the multi which makes it a shitty complex solution that doesn't tier up with your own tech.

It equals to 12 hv when provided with oxygen,making it more complex to work.
The voltage tire is also a problem as u say.

**Comment by draknyte1** [comment]
> making it more complex to work

That’s the whole idea. 🤦🏻‍♀️

**Comment by 0lafe** [comment]
It's also not quite equatable to singles due to the 150% eff vs the 85- of the singles. Which can be quite large of a bonus to net output in larger less efficient setups

**Comment by 0lafe** [comment]
Personally I'd like to see integration with boilers and turbines as an IV option for combustable fuels, but there should probably be some fixes to pump first lol

**Comment by Prometheus0000** [comment]
This is a terrible idea, they should be _bigger_ and _more_ complicated as you progress, not less.

**Comment by Shattered2909** [comment]
Bad idea. It should be expensive, it is really powerful and I agree that it's not great at scaling up but at EV it's nuts.

How on earth is it expensive? It's a few hundred Titanium and nothing else. How is Lubricant an issue for you? Just distill Creosote from making Charcoal. More complex, yes. As it should be at EV.
