### ISSUE TITLE
Adventure backpack working with ender collector can duplicat anything bug

### ISSUE THREAD

**Issue by XenonDB** [GTNewHorizons/GT-New-Horizons-Modpack#6503]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
breaking an adventure backpack placed on ground nearby an ender collector should be collect by ender collector.
#
#### What happened instead? (Attach screenshots if needed)
ender collector collect it but remain a backpack on ground. It mean you can duplicate anything with this.
![未命名](https://user-images.githubusercontent.com/58476103/90117299-4d93a080-dd89-11ea-88cd-ced5fd46a7be.png)
#
#### What do you suggest instead/what changes do you propose?
fix this bug or ban either ender collector or adventure backpack

**Comment by interestingusernam3** [comment]
Isn't the resulting copy backpack just a second access point to the same inventory tho?

**Comment by GTNH-Colen** [comment]
@XenonDB Please remove this, dupes should be reported directly to staff on discord.
