### ISSUE TITLE
Heavy Fuel unusable in Combustion Generator

### ISSUE THREAD

**Issue by schliip** [GTNewHorizons/GT-New-Horizons-Modpack#6505]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Burn Heavy Fuel in Combustion Generator
#
#### What happened instead? (Attach screenshots if needed)
Combustion Generator does not accept Heavy Fuel (fluid or cell), and there is no recipe to burn it in NEI.
#
#### What do you suggest instead/what changes do you propose?
Heavy Fuel should be usable as a Combustion Generator fuel for 240EU/mB
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/Materials.java#L504

**Comment by draknyte1** [comment]
It’s used in semifluid generators.

**Comment by Dream-Master** [comment]
and this is good. As the name said "heavy" fuel.
