### ISSUE TITLE
questID:3 (Your First Night) Needs to be freshened up since the removal of the quest book.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#6506]
#### Which modpack version are you using?
2.0.9.0
#
#### What do you suggest instead/what changes do you propose?
It's just the old version when we use to have a Quest Book in our Inventory. I'm not great at making anything up so I thought I throw it on here instead of trying to submit something silly haha.

**Comment by Dream-Master** [comment]
Fixed in 2.0.9.1
