### ISSUE TITLE
LV Semi-Fluid Generator is not available at LV

### ISSUE THREAD

**Issue by schliip** [GTNewHorizons/GT-New-Horizons-Modpack#6507]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Expected semi-fluid generators to be available at the tier of power they produce
#
#### What happened instead? (Attach screenshots if needed)
LV semi-fluid generator requires Molten Bronze (GregTech), which needs an MV fluid extractor to produce.
![image](https://user-images.githubusercontent.com/34576051/90209191-ae869d00-ddb8-11ea-9927-c5ccc371d361.png)

#
#### What do you suggest instead/what changes do you propose?
Change the Molten Bronze to another material, or add another recipe with Tinkers' Molten Bronze

**Comment by draknyte1** [comment]
Intended. 
Unless bronze is changed to be fluid extracted at LV, this won’t be changed.

**Comment by leagris** [comment]
>  Unless bronze is changed to be fluid extracted at LV, this won’t be changed.

This look like the saner option, since bronze melting and smelting was achieved with dirt smelters and casters burning raw wood. Something that shall not require high-tech.

I did not check, but would it be possible to produce the molten bronze with a Tinker's Construct Smeltery?
Then this recipe would be a non-issue.

**Comment by draknyte1** [comment]
Tinkers molten bronze is not usable.

**Comment by EldrinnElantey** [comment]
> Tinkers molten bronze is not usable.

Since they have different temperatures

**Comment by draknyte1** [comment]
> > Tinkers molten bronze is not usable.
> 
> Since they have different temperatures

They’re two totally different fluids as far as MC cares.

**Comment by leagris** [comment]
It can not stop at the technical explanation.

Having two incompatible, different characteristics, different tier molten bronze fluids is highly illogical.

Can this be fixed, so if both fluids continue to coexist, they share the very same characteristics and be allowed to be unified at some point?

**Comment by draknyte1** [comment]
Fluids cannot be unified. 
TiCon fluids are purposely not compatible with GT fluids. 

Working as intended.

**Comment by draknyte1** [comment]
You do understand it’s broken right and will someday be fixed? 🤦🏻‍♀️
You also understand that this isn’t the correct ticket for your “complaint” either.
