### ISSUE TITLE
CustomLoadingScreen Breaks ResourceLoader Textures from Loading in Game. 

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#6508]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
yes
#
#### What did you try to do, and what did you expect to happen?
add resource textures & then also checked yours out and found none were loading in game for items that existed.
#
#### What happened instead? (Attach screenshots if needed)
showed original textures. 
#
#### What do you suggest instead/what changes do you propose?
Might be able to compile a fix based on the error reported here:
https://github.com/AlexIIL/CustomLoadingScreen/issues/44

Sadly no one narrowed the location of the bug.

**Comment by Prometheus0000** [comment]
Which textures? I use texturepacks fine?
