### ISSUE TITLE
Quest #131 is a bit weird

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#6509]
Anarack said that this quest is wrong so i'm filing a ticket, i'm not really sure what is so i'm sorry for anything.
here's what it's says.
# Quest.131 - §6§lSimple RF power: Solid
By simply burning coal as fuel, this machine produces RF power.
Enough for a basic machine setup.This machine will also accept compressed and multiple-compressed blocks.
Want to burn for 250+ days?Also, with double or octadic capacitors the output will increase and efficiency will improve.
GT wiring can convert EU to RF, but EnderIO machines can be left safely out in the rain. 
%n%nMight be useful for Genetics machines since they consume excessive power when attached to GT wiring 
Forestry and EnderIO machines work fine.

**Comment by Anarack** [comment]
The wording mainly,

 "but EnderIO machines can be left safely out in the rain." unsure why this is here at all
The part about forestry machine not using excess power is mostly right, but the thermionic fabricator is the exception.
