### ISSUE TITLE
Game crashes when i try to connect server

### ISSUE THREAD

**Issue by Erenoit** [GTNewHorizons/GT-New-Horizons-Modpack#6510]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
personal server
#
#### What did you try to do, and what did you expect to happen?
i tried to connect server
#
#### What happened instead? (Attach screenshots if needed)
game freezes and crashes
[crash-2020-08-15_15.27.27-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5078655/crash-2020-08-15_15.27.27-client.txt)

#
#### What do you suggest instead/what changes do you propose?
bugfix

**Comment by boubou19** [comment]
does another player can join the map sucessfully? are you hosting the server on the same computer as the client or remotely? Did you joined the server previously? If yes did you tried to rollback the server to a previously known working state? Is the server running forge or thermos?

**Comment by Erenoit** [comment]
My friend hosts the server. yes i join the server previously. yes i tried to rollback but didn't work. my friend opens derfer from "open to lan"

**Comment by boubou19** [comment]
try to get it running from a true remote server/check both your and his network configuration, because the report looks like internet troubles
