### ISSUE TITLE
FPS issues with eating food

### ISSUE THREAD

**Issue by MyrstaL** [GTNewHorizons/GT-New-Horizons-Modpack#6511]
#### Which modpack version are you using?
GT:NH Version 2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
My own private hosted server
#
#### What did you try to do, and what did you expect to happen?
While the hunger bar is full, I had my lunchbox filled with food in my hand (this happens with any food except ones you can eat while your bar is full, I just happened to be holding lunchbox at the time I decided to write an issue), and I held down RMB (right mouse button), I expected nothing to happen as my hunger bar was already full.
#
#### What happened instead? (Attach screenshots if needed)
When holding down RMB with a full hunger bar and with food out, my FPS dropped drastically, one time going from 105 to 39
#
#### What do you suggest instead/what changes do you propose?
I am not too sure, I just wanting to report on what was happening

**Comment by Dream-Master** [comment]
I need more infos. Logs? did you check with warmroast or opis ?

**Comment by Dream-Master** [comment]
@MyrstaL

**Comment by MyrstaL** [comment]
I couldn't find anything in the logs, I'm not sure what warmroast or opis is

**Comment by Dream-Master** [comment]
Google it and try to run it on the server. You can use the mod sampler too. Run it before eat food and stop it after. The file can analyst then and show you the mod or class what cause the lag.

**Comment by Dream-Master** [comment]
And if you run a server you must know this programmes.
