### ISSUE TITLE
Circuit assembly line not working

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6512]
#### Which modpack version are you using?
GTNH 2.0.9.0QF4
#
I build a circuit assembly line for LV circuits just like the other 12 CAL I have for other circuits, and this CAL just won't work.

When I did a /mt hand on the controller it says 

`<gregtech:gt.blockmachines:12735>.withTag({mPollution: 0, mRuntime: 0, mWrench: 1 as byte, mEUt: 0, mEfficiency: 0, mHardHammer: 1 as byte, mScrewdriver: 1 as byte, mProgresstime: 0, mSoftHammer: 1 as byte, Type: {id: 4156 as short, Count: 1 as byte, registryName: "IC2:itemPartCircuit", Damage: 0 as short}, mCrowbar: 1 as byte, mSolderingTool: 1 as byte, mEfficiencyIncrease: 0, mMaxProgresstime: 0})`

"IC2:itemPartCircuit" is the ic2 circuit maybe that's the problem

**Comment by GTNH-Colen** [comment]
I had a similar issue with nanoprocessors, the CAL would take it in but then it would only make "advanced circuit" not nanoprocessors and thus was useless. Using a spawned in nanoprocessor fixed the issue, never had it happen for the LV one though.

**Comment by Alexdoru** [comment]
So I cheated a new CAL controller using this command 

`/give Alexdoru 2041 1 12735 {mPollution: 0, mRuntime: 0, mWrench: 1, mEUt: 0, mEfficiency: 0, mHardHammer: 1, mScrewdriver: 1, mProgresstime: 0, mSoftHammer: 1, Type: {id: 7095, Count: 1, registryName: "gregtech:gt.metaitem.03", Damage: 32078}, mCrowbar: 1, mSolderingTool: 1, mEfficiencyIncrease: 0, mMaxProgresstime: 0}`

This new controller has the tag for the microprocessor and now my CAL is working and can perform this recipe : 
![image](https://user-images.githubusercontent.com/57050655/90340266-38bc4480-dff7-11ea-94f4-7b2793fdddfb.png)

To fix this issue I suggest changing the NBT tag of the Sliced circuit you get when you slice a microprocessor, because right now the sliced circuit has this tag wich is the IC2 circuit and not the microprocessor : 

`<bartworks:gt.bwMetaGeneratedItem0:1>.withTag({id: 4156 as short, Count: 1 as byte, registryName: "IC2:itemPartCircuit", Damage: 0 as short})`

**Comment by Prometheus0000** [comment]
There are two recipes for the LV and HV sliced circuits, only the non-oredict one works properly, and I think you have to use the slicing machine instead of the multi, but I can't remember. This should be mentioned in the latest version of the quest book, you might have to grab it from the repo if the qf4 doesn't say so in the cheaper HV circuits quest. Additionally, this CANNOT be fixed according to Alk.

**Comment by draknyte1** [comment]
Imagine if Bart did it properly as suggested by everyone else. It would’ve never had issues.

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/91645034-b3318f00-ea0f-11ea-9e43-3379a749b41c.png)
The quest tells you already.
![image](https://user-images.githubusercontent.com/8517039/91645056-e5db8780-ea0f-11ea-8a90-4db5b60b39be.png)
Right. Only works in the slicing machine.
![image](https://user-images.githubusercontent.com/8517039/91645065-f68bfd80-ea0f-11ea-9dea-3f3dd7593a95.png)
Wrong. Also include the other LV circuits.

Unless you sliced the right circuit with the slicing machine and it still doesn't work? Though I agree that this is a stupid way to make the slices/imprints.
