### ISSUE TITLE
Dupe Bug with crafting Mud Balls in all crafting inventories giving x2 Buckets

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#6514]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Yes
#
#### What did you try to do, and what did you expect to happen?
Crafting Mud Balls with 1 Dirt 1 Bucket of Water in my crafting, normal crafting table even tinkers crafting table. I should get 1 bucket back but I get 2 Buckets Back instead of 1
#
#### What happened instead? (Attach screenshots if needed)
I dupe the buckets. 
#
#### What do you suggest instead/what changes do you propose?
I assume either there is a recipe / mechanic that does this already and it's duping or a typo somewhere.

![image](https://user-images.githubusercontent.com/425853/90359669-8781d280-e027-11ea-9e4e-ecd57f4b35c7.png)

**Comment by GTNH-Colen** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6424
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6354
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6256
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6230
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5727
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5591
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6089

I think it's safe to say this is a known issue at this point 😆

**Comment by Dream-Master** [comment]
@KaneHart You Mud Ball duper :P

**Comment by KaneHart** [comment]
Opps haha :)

**Comment by KaneHart** [comment]
Can I please have the link to the actual open ticket for this bug and the fixed commit.

**Comment by Prometheus0000** [comment]
Reopened #5591 as that appears to be the original issue.
