### ISSUE TITLE
(1x1) Schematic causes extreme lag

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#6515]
#### Which modpack version are you using?
2.0.9.0 QF4
#

Using this schematic in a packager sometimes causes absolutely insane levels of lag, like 1.4m ns per single block. Happened with uranium 238 dust and copper but not polyethylene dust, unsure why this is the case. Packagers generally seem to eat a lot more performance than they should, sometimes 20-40k which when on its own is tolerable but once you start using the GT++ packager it goes absolutely haywire. This seems related to core GT since from what I've heard the GT++ packager uses regular packager logic, just goes a lot faster.

**Comment by Glease** [comment]
Packager actually invokes the normal craft handler to determine recipe outputs, so it's not going be fast in a huge pack like GTNH. We might add a few special cases here to prevent going through all the crafting recipes since the most common use case is combining tiny/small dust.

GT++ multi have a huge loop. For however many parallel you have you will get X times more time consumed. It could probably use some caching here but I don't have a say there..

**Comment by GTNH-Colen** [comment]
Given that 99% of the time the (1x1) schematic is simply being used to craft from 1 dust to 9 tiny dust cacheing would seem wise, you aren't ever changing what dust goes in. The GT++ multi is more complicated and ultimately on Alk to take a proper stab at but it is causing big lag spikes when on.

**Comment by draknyte1** [comment]
Isn’t there a dust schematic?
Iirc the shaped ones are far laggier than the dust one if so. (I know one is far nicer on tps than the others, as I spoke to Greg about this a year or two back)

**Comment by GTNH-Colen** [comment]
> Isn’t there a dust schematic?
> Iirc the shaped ones are far laggier than the dust one if so. (I know one is far nicer on tps than the others, as I spoke to Greg about this a year or two back)

Doesn't the dust one just do tiny -> regular piles not the reverse?

**Comment by MotiasF33** [comment]
not only 1x1 schematic has lag
![изображение](https://user-images.githubusercontent.com/47714084/91582775-f250d900-e958-11ea-8eec-db5c39d4a39f.png)
and "dusts" too

**Comment by boubou19** [comment]
![2020-09-22_21 48 13](https://user-images.githubusercontent.com/12850933/93930367-8b3b0000-fd1d-11ea-94a7-28636db94594.png)
still a lag source in 2.0.9.1 dev (zpm packager packing tiny piles of copper)

**Comment by Glease** [comment]
Can you check if this is still a problem? Bot made some optimization to this machine in GTNewHorizons/GT5-Unofficial#357, but I'm not sure if it still need any more improvements. The optimization will fail if you keep alternating the input but I'm not sure how many people would do that.
