### ISSUE TITLE
[UHV stuffs Recipes] recipe have only one type items

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6516]
#### Which modpack version are you using?
2.0.9.0qf4

### For craft UHV energy\dynamo only helium coolant cells 
![изображение](https://user-images.githubusercontent.com/47714084/90411777-ec373e80-e0b4-11ea-821d-0d4490876001.png)
_I suppose change it on supercoolant cells :}_

### For craft UHV pump only silicone rubber rings
![изображение](https://user-images.githubusercontent.com/47714084/90412184-767fa280-e0b5-11ea-8396-419171ec4339.png)

**Comment by MotiasF33** [comment]
or is this a feature?
🤔

**Comment by GTNH-Colen** [comment]
Pretty sure this is intentional to force you to use the higher tier rubber ie silicone. Helium not sure, might be meant to allow NAK as well?

**Comment by MotiasF33** [comment]
> 
> 
> Pretty sure this is intentional to force you to use the higher tier rubber ie silicone. Helium not sure, might be meant to allow NAK as well?

need testing but, it do not flicking as circuits

**Comment by Dream-Master** [comment]
Nope circuits are oredicted and this isnt fixed
