### ISSUE TITLE
Strange terrain generation far from spawn

### ISSUE THREAD

**Issue by dieselfuelonly** [GTNewHorizons/GT-New-Horizons-Modpack#6518]
2.0.9.0 on SSP.  I was looking for some mystic grove biomes using the Nature's Compass and started noticing this weird terrain generation far from spawn.  Someone else from Discord mentioned seeing the strange generation around 10k away.  Any idea what causes this and how to stop it?

https://imgur.com/a/xHCOFJ6

**Comment by interestingusernam3** [comment]
RWG farlands?

**Comment by dieselfuelonly** [comment]
> RWG farlands?

Seems something like that, although it didn't generate in all biomes which was odd.

**Comment by Devtron3D** [comment]
ok ALLLL servers i have been on have this. Even the officials ones,   go out 20-40k and you will see it lots of places.

**Comment by boubou19** [comment]
does not happens on delta

**Comment by Devtron3D** [comment]
I am 100% sure it is on ETA

**Comment by Viktor-KN** [comment]
If I remember correctly, all our servers have 12k world border... so @Devtron3D, you couldn't see it on 20-40k.

**Comment by Devtron3D** [comment]
ok let me be a bit more detailed
The further you go out, the more often you will see.
it is more rare for sub 10k from what i have seen

Delta ill be honest i cant remember 100% been a few years

On ETA I am 100% sure i saw it, cause I asked about it in chat back then, and was told it happens, unfortunately i dont remember where, I found it when I was stargate hunting :) (and yes i have a claimed chunk with a stargate even though i am only ev :) they were generated by mistake when the server was created )
It was not a big area but it is there.

Prospercraft server has it (that is an old world) but i live 16k out.

MMC No TP (Eu+Asia2)   also has it, found it when hunting for a base location, and that server was created this year. This had the largest area i had ever seen, and i was very far out.

**Comment by boubou19** [comment]
Is it happening on a fresh map with the latest GT:NH version?

**Comment by Prometheus0000** [comment]
Don't go that far out then.
