### ISSUE TITLE
Order-Infused Compressed solar bugged and reverting on pick-up

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/GT-New-Horizons-Modpack#6521]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Currently I'm redesigning some stuff, and was moving my solar panels, and noticed that my order-infused triple compressed solar was not doing anything (buffer was tiny, no sunlight coming in, etc.)
I right-click wrenched the block and I expected this to just be picked up as normal.
#
#### What happened instead? (Attach screenshots if needed)
When it got dropped on the floor as an item, it looked like it got reveted to a normal compressed solar panel. When I picked it up and placed it again, it became clear that this was true indeed.
Before (from a far screenshot from 2 months ago):
![image](https://user-images.githubusercontent.com/11915663/90626771-a6e15100-e21b-11ea-99b1-383c87a197e1.png)
After (from just earlier):
![image](https://user-images.githubusercontent.com/11915663/90626797-aba60500-e21b-11ea-8d46-9e45b81ea6aa.png)

#
#### What do you suggest instead/what changes do you propose?
Hopefully this is a rare occurrence because of it being an old block, but if it's a thing 
I suspect this is because this panel was from years ago, before electro-magic tools were reworked to include the higher tiers.
Consequently, my panel may have not been a valid block anymore and therefore reverted when broken.

It would be nice if I could get it refunded though as it seems to be unintended behaviour.

Potentially another relevant thing to mention:
When I looked at the GUI of the solar itself before picking it up, it showed it was not generating anything and that it had no internal buffer, so it really seemed bugged out.

**Comment by Prometheus0000** [comment]
Consider it a punishment for using solars.
