### ISSUE TITLE
Railcraft reinforced (switch) track crafting issues

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#6526]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried making the reinforced switch track from railcraft according to the NEI recipe:

![image](https://user-images.githubusercontent.com/8459776/90682533-627aa300-e265-11ea-9c4d-b43d35c3dfdd.png)
![image](https://user-images.githubusercontent.com/8459776/90682564-6c9ca180-e265-11ea-94f6-46ef29bd33b2.png)

ingredients used:

![image](https://user-images.githubusercontent.com/8459776/90682435-3a8b3f80-e265-11ea-8ef6-23722d5ee2d4.png)
![image](https://user-images.githubusercontent.com/8459776/90682478-4bd44c00-e265-11ea-9dd2-318fa012cccb.png)
#
#### What happened instead? (Attach screenshots if needed)
The IDs don't match up, and the assembling machine doesn't start with assembler-created rail.
There is a more expensive crafting table recipe for reinforced track that does trigger the recipe, but it does not show when clicking reinforced track in NEI, only when clicking through from the switch track can it be found

Placing and breaking the crafting table version converts it into the assembler version, rendering it useless for switchtrack crafts.
#
#### What do you suggest instead/what changes do you propose?
All recipes involved should agree on one ID flavour. The most appropriate candidate is the one returned from breaking rail in the world. That would mean that both the table craft for reinforced rail and the recipe for switchtrack should be made to use the other version. 

The associated search issues with NEI will probably solve themselves with that change.

**Comment by Prometheus0000** [comment]
I can't see the problem, could you try again on the latest version? There's only 1 version of the 'Reinforced Switch Track' that I can find, and there's no crafting table recipe. Maybe someone already fixed it?
