### ISSUE TITLE
Cannot get computronics  Scummy Bee

### ISSUE THREAD

**Issue by TataTawa** [GTNewHorizons/GT-New-Horizons-Modpack#6527]
#### Which modpack version are you using?
2088

Scummy Bee needs a block of salt water to mutate, if there is a liquid called "saltwater". if there is not a liquid "saltwater", it will need a block of water.  There is  "saltwater" liquid in GTNH but there is no block of saltwater. so the mutation is impossible.

i don't think add a liquid block is a good choice, so i think it is OK to change the mutation condition to water block.

https://github.com/Vexatos/Computronics/issues/165

**Comment by Prometheus0000** [comment]
Did you look at #3791? If you're trying to get grog/nanomachines there's apparently another recipe or something.

**Comment by TataTawa** [comment]
if computronics is hard to compile, it is ok to adding follwing reflection code to some where postinitialize to solve.

try {
                Class clazz = Class.forName("pl.asie.computronics.integration.forestry.FlowerProviderSea");
                Field waterTypes = clazz.getDeclaredField("waterTypes");
                Field hasCheckedSaltwater = clazz.getDeclaredField("hasCheckedSaltwater");
                waterTypes.setAccessible(true);
                hasCheckedSaltwater.setAccessible(true);
                waterTypes.set(null, Arrays.asList("water"));
                hasCheckedSaltwater.set(null, true);
            } catch (Exception e) {
                e.printStackTrace();
            }

**Comment by TataTawa** [comment]
@Prometheus0000 yes ,the recipe is a work-around
