### ISSUE TITLE
allow player to see what inside the graves by holo glass

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6528]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
allow player to see what inside the graves by holo glass
#
#### What happened instead? (Attach screenshots if needed)
i can't see
#
#### What do you suggest instead/what changes do you propose?
allow player to see what inside the graves by holo glass

**Comment by Prometheus0000** [comment]
I'm not sure if they actually 'contain' the items or if they spawn them when broken. Probably the latter, thus making this (probably) impossible.

Also, what's wrong with breaking all the graves? You don't want to leave them lying around, do you?

**Comment by Eason134HK** [comment]
> I'm not sure if they actually 'contain' the items or if they spawn them when broken. Probably the latter, thus making this (probably) impossible.
> 
> Also, what's wrong with breaking all the graves? You don't want to leave them lying around, do you?

I don't think it is the latter, Quantum Entangled Singularity is in pair. According to this, I did a test
![image](https://user-images.githubusercontent.com/59776356/93587122-f615cf80-f9db-11ea-816e-eb23be1670f7.png)
i made a pair of Quantum Entangled Singularity one keep it in chest and one hold on my hand and i kill myself
The end result is that they can overlap
If it spawn item when broken Quantum Entangled Singularity should not work

**Comment by Prometheus0000** [comment]
I don't mean spawn a new version, I mean spawn the items listed in the file created when you die.

**Comment by Prometheus0000** [comment]
The dead deserve their privacy.
