### ISSUE TITLE
Adding my server to the server list

### ISSUE THREAD

**Issue by VeyezX** [GTNewHorizons/GT-New-Horizons-Modpack#6529]
IP: modded.vex-mc.com
<s>Discord: https://discord.gg/cx8H8Pa</s>
Location: The Netherlands (EU Server)
Whitelisted

**Comment by Prometheus0000** [comment]
@Dream-Master Is this done?

**Comment by Dream-Master** [comment]
IrgendwerToday at 4:05 PM
https://discord.gg/CnrKQ2uM4B

**Comment by Dream-Master** [comment]
@VeyezX can you update the Discord link so i can add your server?
I need anerver expiring link. Thanks
