### ISSUE TITLE
[Bartworks] Radio Hatch

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6530]
#### Which modpack version are you using?
2.0.9.0qf4
### IV+ Radio hatches no consuming a ☢️ material for work.

![изображение](https://user-images.githubusercontent.com/47714084/90942192-60f3db00-e41d-11ea-96c3-771ce3c5496b.png)
![изображение](https://user-images.githubusercontent.com/47714084/90942219-7cf77c80-e41d-11ea-9958-6d41d602d89d.png)
just always works 🆓

**Comment by Josh5minus1** [comment]
Is it only specific for IV radio hatch?

**Comment by Prometheus0000** [comment]
They work fine for me, are you on a server with thermos? Try it in SP

**Comment by Prometheus0000** [comment]
Apparently this happens to other people as well, and may be a MP only problem. Also happens on Zeta, with the latest version.

**Comment by yukieiji** [comment]
In ver 2.1.0.0, it also occurs with the HV radio hatch.
Also, when I used Name Remover to delete an object inside, it was even more buggy....
![2021-03-12_15 59 43](https://user-images.githubusercontent.com/40425798/110904212-fa4bf580-834b-11eb-9ea6-264fe47ae506.png)

**Comment by Prometheus0000** [comment]
@bartimaeusnek
