### ISSUE TITLE
rework wetware and bio circuit boards

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#6531]
#### Which modpack version are you using?
9.0 qf4
#### What do you suggest instead/what changes do you propose?
the curent cost for wetware and bio circuits make the only viable for UHV and UEV circuits
change the LuV sensors to 2-4 IV sensors this way you dont need 4 luV circuits to make 16 of them 

the bio boards need UV sensors so if you want to make 16 zpm circuits you need 4UV or 8 ZPM
but if you want to make UV circuits with it then you need 12 UV circuits to make 16 of a total of 4 UV circuits 
this makes the UV circuits the bio way basicly 4 times more expansif 
for a 1 tier in circuit increase you need UV components for it witch is 2T higher then the LuV for wetware

change it to ZPM components and change the sensor to 2x LuV

**Comment by RaitGamerGR** [comment]
Wetware circuits much cheaper than crystal circuits

**Comment by Florexiz** [comment]
Can we somehow promote this to voting? Current recipes extremely out of concept. I think iv components for luv circuits and luv for zpm looks more fitting?

**Comment by LewisSaber** [comment]
new circuit lines supposed to make circuit production of its tier cheaper, atm all what wetware and bioware do is just giving acces to UHV and UEV circuits

**Comment by Prometheus0000** [comment]
I believe bot already did this but didn't link it https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/131
