### ISSUE TITLE
Rocket Fuel from EnderIO mentions in Questbook

### ISSUE THREAD

**Issue by Dunnoer** [GTNewHorizons/GT-New-Horizons-Modpack#6533]
#### Which modpack version are you using?
2.0.9.0
#
#### Issue
Questbook in the quest number 827 mentions to use Rocket Fuel from EnderIO for the t1 rocket but the recipe for that doesn't even exist.
#
![Zbp9g4J3JP](https://user-images.githubusercontent.com/13352471/90965472-90135680-e4c8-11ea-9181-07ae7ce5ad1d.png)

**Comment by Prometheus0000** [comment]
Checked, it's your fault. Be on qf4 and reload quests.
