### ISSUE TITLE
Lafinum receipt in alloy furnace multiblock don´t work 

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6536]
#### Which modpack version are you using?
2.0.9.
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
Receipt with based dusts say argon, cirquit 8 and some dusts i.e. hastelloy-N
#
#### What happened instead? (Attach screenshots if needed)
hastelloy-N directly smelted and ignore cirquit 8
#
#### What do you suggest instead/what changes do you propose?
hastalloy-N shall respect circuit 8 and work only without circuit or with may be cirquit 1

**Comment by Ngar1** [comment]
ABS

**Comment by Ngar1** [comment]
I found the reason: the multi Alloy Smelter respect not the circuit in the used input bus. It used circuit no from other input busses at the same multi block. As a hook: build a smelter per circuit!

**Comment by Prometheus0000** [comment]
If you want you can make an issue at the GT++ tracker to ask for optional separated bus treatment like the PA via screwdriver.
