### ISSUE TITLE
[bug++] Dangote Distullus as Distilation Tower does not work

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6540]
#### Which modpack version are you using?
2.0.9.0.qf4
### Dangote Distullus as  a Distilation Tower does not work..
Structure complete, DT mode, have a energy, have a source.. but is does not work.
![изображение](https://user-images.githubusercontent.com/47714084/90994993-393e7780-e5c3-11ea-8c9d-0b98cabe7484.png)
![изображение](https://user-images.githubusercontent.com/47714084/90995007-40658580-e5c3-11ea-9b88-a89e89883201.png)
![изображение](https://user-images.githubusercontent.com/47714084/90995108-9afee180-e5c3-11ea-997c-127bfd56c5c7.png)
_No idea_

**Comment by Prometheus0000** [comment]
Report at the GT++ repo.

**Comment by MotiasF33** [comment]
> 
> 
> Report at the GT++ repo.

Alc, say me what is not working.
mb add tips  ?
_DIstillation mode DISABLED?_

**Comment by Prometheus0000** [comment]
Ask at the GT++ repo? Or search there or the discord to see if someone already complained and had this answered?

**Comment by MotiasF33** [comment]
> 
> 
> Ask at the GT++ repo? Or search there or the discord to see if someone already complained and had this answered?

Alkalus answer me
![изображение](https://user-images.githubusercontent.com/47714084/91513587-65bd0100-e8ed-11ea-9cf5-5869938d12d1.png)

**Comment by MotiasF33** [comment]
DT mode is off.
