### ISSUE TITLE
Add a recipe for the Perpetuum Locomotive train

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#6541]
#### Which modpack version are you using?
2.0.9.0
#

I propose we add a recipe for this, it's usually a creative item but I see no reason why it couldn't have a recipe. It's just a train that takes no fuel or energy and will keep running, probably doesn't need to be very highly gated honestly.

🚂 🚂 🚂

**Comment by Dream-Master** [comment]
ok why not.

**Comment by Prometheus0000** [comment]
Maybe suggest a recipe?

**Comment by Prometheus0000** [comment]
@GTNH-Colen

**Comment by Prometheus0000** [comment]
I guess you don't care after all @GTNH-Colen
