### ISSUE TITLE
MalisisBookFactory

### ISSUE THREAD

**Issue by crazydarkmind** [GTNewHorizons/GT-New-Horizons-Modpack#6543]
#### Which modpack version are you using?
GTNH latets modpack
MalisisCore14.3
#
#### If in multiplayer; On which server does this happen? 
Minecraft.ru
#
#### What did you try to do, and what did you expect to happen?
Tried to use block to craft doors and had an error message
#
#### What happened instead? (Attach screenshots if needed)
![unknown](https://user-images.githubusercontent.com/70168726/91082917-13ac7f00-e652-11ea-8563-ea8b43370e92.png)

#
#### What do you suggest instead/what changes do you propose?
using google I found that this version of MalisisCore 14.3 gets this error. Would be better to use 14.1 this must solve the issue

**Comment by Dream-Master** [comment]
@crazydarkmind you suggest use a older version ?

**Comment by crazydarkmind** [comment]
Yes, because it works

**Comment by Dream-Master** [comment]
any downsides? missing fixes or changes ?

**Comment by crazydarkmind** [comment]
installed every update till latest version. Didn't found no other way to fix this

**Comment by Dream-Master** [comment]
is this error message only visual or are the thing not working ?

**Comment by crazydarkmind** [comment]
not only visual. DoorFactory interface don't open, instead this message apeears in chat

**Comment by Dream-Master** [comment]
maybe we can check if a fix is possible instead of downgrading

**Comment by crazydarkmind** [comment]
Of course, fixing is better than downgrading.
