### ISSUE TITLE
ingameinfo showing Z-coordinate as elevation

### ISSUE THREAD

**Issue by MyrstaL** [GTNewHorizons/GT-New-Horizons-Modpack#6544]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
All I suppose?
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/69368253/91123344-9fcaa080-e66a-11ea-8b87-903253bfe95f.png) (Standing on the ground)
![image](https://user-images.githubusercontent.com/69368253/91123633-5af33980-e66b-11ea-9d9a-af6547529e13.png) (Jumped)
The ingameinfo writes "Z" instead of "Y" as my elevation coordinate
#
#### What do you suggest instead/what changes do you propose?
Whatever needs to be done to edit the ingameinfo to show that element as the Y coordinate

**Comment by GTNH-Afx237v7** [comment]
InGameInfo.xml in the config-Folder of your Minecraft Instance

<str> Z: $6{yfeeti}$f facing $6{finedirection}$f</str>

Change Z to Y

**Comment by Dream-Master** [comment]
@GTNH-Afx237v7 make a pull request please. Thanks

**Comment by GTNH-Afx237v7** [comment]
I have Zero clue on Pull request functionality and what is required to do so. Suggest someone who knows how this works makes a pull request.
Sorry.
