### ISSUE TITLE
[BartWorks] Steam age windmill can't get more efficiency than 0 %

### ISSUE THREAD

**Issue by TheStoneWolf** [GTNewHorizons/GT-New-Horizons-Modpack#6547]
#### Which modpack version are you using?
2.0.9.0
#
#### What did you try to do, and what did you expect to happen?
Bult a BartWorks windmill according to its specifications and with the block structure not crossing any chunk boundaries. The Windmill controller says that it is "running fine" and the rotor spins very fast when it is placed in the shaftbox. When I put in the wheat into the controller, I expected the wheat to begin to be turned into flour.
#
#### What happened instead? (Attach screenshots if needed)
Bult a BartWorks windmill according to its specifications and with the block structure not crossing any chunk boundaries. The Windmill controller says that it is "running fine" and the rotor spins very fast when it is placed in the shaftbox. Still, even the most efficient rotor, the  combined primitive rotor, (only checking rotors available in the steam age or earlier) can't make the windmill as an entirety get more efficiency than 0.0 as displayed below, with no progress on grinding the wheat done whatsoever.

![2020-08-25_13 38 20](https://user-images.githubusercontent.com/15616024/91170025-91b36900-e6d8-11ea-9426-adc016a4a1e5.png)

In the case of this windmill the wind is common around it (measured by the simple wind meter) but I have tried in both strong and low winds as well using all of the different rotors available in the early game (paper, wool, leather and combined). Despite all that the efficiency never rises above zero.

![2020-08-25_13 38 29](https://user-images.githubusercontent.com/15616024/91170044-9710b380-e6d8-11ea-928a-ba7778fd6831.png)

#
#### What do you suggest instead/what changes do you propose?
The efficiency should only be zero when the windmill is faulty, because you have a too heavy rotor for the wind for example. Outside of that it should be **above zero** because right now the windmill is not only completely useless but also a giant trap for new players like me who pour tons of resources into it for it to just not work.

**Comment by Prometheus0000** [comment]
If it doesn't work it makes sense it's at 0, if it does work, but stays at 0, that's a bug. Did you check if anyone else on discord can get it to work?

**Comment by Josh5minus1** [comment]
I got it to work, but with IC2 rotors instead.
