### ISSUE TITLE
Changes/Removal Spacesuit

### ISSUE THREAD

**Issue by mtesseracttech** [GTNewHorizons/GT-New-Horizons-Modpack#6550]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Gather some surface dust.
#
#### What happened instead? (Attach screenshots if needed)
Went to venus, took all precautions, but just got 1-hit by a skeleton, despite the spacesuit being maximally enchanted and me having 63hearts of health.

Also, after death my spacesuit jetpack was gone as well as my red heart containers, it seems.
#
#### What do you suggest instead/what changes do you propose?
The spacesuit seems entirely unsuitable for the pack because:
1: It is not made to handle the extreme darkness the pack causes
2: It's in no way a suitable protection against the mob mechanics of the pack
3: It looks very bad, obscures 50% of your sight for no reason and just is not fully enchantable to allow you to have night vision.
4: despite all above points, you need it for all of the most hostile planets.

There is no way to go mining with it and expect that you will make it back alive.

Proposed: Either taking out the spacesuit entirely, since it's not a very fun mechanic or considerably changing its mechanics. It's quite clearly not suitable and any other player who had to go to planets that require it also all seem to hate this mechanic and think it's unfair.

Taking out the spacesuit could be an option, and if you want to sort of keep its spirit in, you could make it so that there is a list of armor that counts as space suits. For example: Stellar, Quantum, etc.

It could be replaced by another set of thermal undies or something along those lines, but as it stands now: you are way too vulnerable on something as high stakes as space exploration in this pack.
If I didn't have access to the portal, I'd basically have lost everything because a single mob managing to land a single arrow: all my gear, inventory items, rocket, etc. This is way too random and not at all something you can prepare for.

**Comment by Prometheus0000** [comment]
1) ? Do you mean the vision obscuring?
2) We can change it to diamond level most likely, I dunno what it's at now. But something one-shotting you at 63 hearts is probably a problem with the mob, not the armor, unless I don't understand how armor works?
3) I think they look cool? Never looked at the character model though. Agree with the second, dunno about enchanting it. You can always use a potion?
4) Ok?

I'd say have it replace the thermal gear (and also give thermal gear effect), so it's always on.

And again, it sounds like most of the problem is with the mob. I thought the pain enchant and such was nerfed?

**Comment by mtesseracttech** [comment]
1. No, I mean that you cannot enchant it to have night vision, which is an issue in a pack that has complete 100% darkness, but to be honest, the obscured vision is rather obnoxious as well.
2. Still seems kind of ridiculous. The mobs on the planet really should be tweaked to at least make it possible to protect yourself against them.
3. That's fair enough, personally I find the whole mod to look inconsistent, but to each their own.
To me this remains kind of obnoxious that you kinda have to half-ass it, not to mention that on most normal playthroughs (where inter-dimensional teleporting is not there and will have to wait for a few more irl years), by the time you discover this, it's probably already way too late.
4: guess there's not too much to say to it, but that point mostly was made to drive home that it was just very awkwardly balanced and seemingly not thought out too well.

**Comment by Prometheus0000** [comment]
Is it just the GC mobs that are crazy? Have you tried spawning them elsewhere (in a creative world obviously) and seeing if they do crazy damage even with decent armor? I would think it's them being infernal or TC champions or both causing the massive damage.

**Comment by Cleista** [comment]
It sounds like a bug because I haven't been instakilled on Venus yet, but the spacesuit mechanic is silly. If we can't remove it, I at least think making quantum armor count as a spacesuit is a good compromise.

Quantum Armor is lava proof and clearly airtight because it lets you breathe underwater, and has enough structural integrity to nullify all kinds of damage to zero. Surely that's more than enough, specs-wise, for a suit that lets you survive on Venus?

**Comment by Anarack** [comment]
You could just use the one ring and ignore the entire space suit mechanic, its already skipable so I don't see the point in having the space suit restriction.

**Comment by mtesseracttech** [comment]
> You could just use the one ring and ignore the entire space suit mechanic, its already skipable so I don't see the point in having the space suit restriction.

Usage of sort of obscure, unintended side effects of seemingly unrelated items seems like a bit of a bad solution to this problem.
Especially going there without a spacesuit instakills you in any other situation.

**Comment by Anarack** [comment]
I wouldn't call it untended when that is what it is supposed to do.

**Comment by mtesseracttech** [comment]
> I wouldn't call it untended when that is what it is supposed to do.

Maybe, but you can easily go an entire playthrough without finding even one. 
Also: the things are effectively banned on the official servers (to prevent tier skipping)

**Comment by boubou19** [comment]
Not "banned" properly speaking, but strictly ruled on: we already cases of players skipping rockets with the one ring, or players summoning wither bosses without dealing with them.

**Comment by Prometheus0000** [comment]
Is there a reason they're not disabled? Or have a crazy endgame recipe to make only? Because that's what I'd do.

#5168 Looks like it's waiting on someone with the will to change it or something. I agree with them about disabling it until it's nerfed, but that's a different discussion.

**Comment by ScriptedPiky** [comment]
So the Space Suit is actually required for only **two** planets, Venus and Cent. Bb. Those are the only two that are required. Now dying instantly from 63 hearts from a mob is likely a bug in itself, maybe one of the mobs is using `setHealth` mechanics or the bows/swords have Pain/Agony?

**Comment by glowredman** [comment]
I've changed the SpaceSuit to have 25 armor points (1.25 full armor bars) when wearing the full set. I did not change the overlay when wearing the SpaceSuit Sensor Helmet becuase the class inherits this property from the GC class for the Sensor Goggles and tbh it's not *that* annoying.
