### ISSUE TITLE
[Suggestion] add a Polymers Bees

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6551]
### Suppose add a Polymers Bees as silicone, epoxid i.c. on hight hier 
What do you think about this?
🐝

**Comment by Glease** [comment]
If you plan to skip the production line designing by having bees that produce polymer products directly then it's a hard NO, because you are converting one of the main selling points into a dull afk game. However if you can come up with some more interesting mechanism like bees boosting production (like what pure oxygen or TiCl4 does now), simplifying steps but require more precious resources, etc, I think we would happily accept it into the game.

**Comment by boubou19** [comment]
also there is already at least 1 silicon bee that gives raw silicon from gc or gs. you can get silicon in some compound dust availiable with bees such as lapis bees for exemple.

**Comment by MotiasF33** [comment]
just i don't like LCR..
It takes up a lot of space or requires thoughtful action
I agree if infinity honeycombs will give tiny dust of polymers :3

**Comment by boubou19** [comment]
then use the single block version? 🤷

**Comment by MotiasF33** [comment]
@boubou19 
Mb would be an interesting simplified combination?
EpoxyComb +Epichlorohydrin+ sodium hydroxide = Epoxy?

**Comment by Anarack** [comment]
...then you might as well do the chem in the first place? your halfway there.

**Comment by GTNH-Colen** [comment]
> @boubou19
> Mb would be an interesting simplified combination?
> EpoxyComb +Epichlorohydrin+ sodium hydroxide = Epoxy?

Was kinda against this thread until you suggested this, a type of comb to boost the output would be quite cool for all the polymers imo.

**Comment by Prometheus0000** [comment]
Like replacing the titanium tetrachloride (or whatever it's called) or mercury in some recipes?

**Comment by 0lafe** [comment]
Bro this shit is retarded lol

**Comment by MotiasF33** [comment]
> 
> 
> Like replacing the titanium tetrachloride (or whatever it's called) or mercury in some recipes?

I meant to replace part of the component with bee honey 🍯

**Comment by Prometheus0000** [comment]
Dream said no to polymer bees on discord, so no. If you have a different bee suggestion, post another ticket.
