### ISSUE TITLE
[Wrong Recipe] Crystal Cosmic Wand

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6553]
#### Which modpack version are you using?
2.0.9.0qf4
### Crystal Cosmic Wand
For recipe need _4396\150_ Scepter (from OP),
and u have _4396\540_ Scepter
![изображение](https://user-images.githubusercontent.com/47714084/91614015-5c817200-e989-11ea-8199-aae769b67df1.png)
![изображение](https://user-images.githubusercontent.com/47714084/91614106-93578800-e989-11ea-8b61-8188e4ad56eb.png)
![изображение](https://user-images.githubusercontent.com/47714084/91614159-ac603900-e989-11ea-859d-5348b0bcf46c.png)

**Comment by MotiasF33** [comment]
_pss..anyone can crafting this for me?_ 👀

**Comment by Dream-Master** [comment]
Guess the meta id change happend after we put the wand recipe in code. Need to change mine tweaker recipes.
