### ISSUE TITLE
[Visual] Invisible fluourine in Prospector's Scanner

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6554]
#### Which modpack version are you using?
2.0.9.0qf4
### Fluorine has the same color as gui grid
![изображение](https://user-images.githubusercontent.com/47714084/91627174-3924ea00-e9be-11ea-8fd2-d47b78b11685.png)

**Comment by Dream-Master** [comment]
Yea ik this issue but guess the gt++ fluids are Gray by default. @draknyte1 any idea ?
