### ISSUE TITLE
Unlisted EBF Temperature bonus

### ISSUE THREAD

**Issue by DuskNite** [GTNewHorizons/GT-New-Horizons-Modpack#6555]
#### Which modpack version are you using?
2.0.9.0 

#
#### If in multiplayer; On which server does this happen? 
Private 

#
#### What did you try to do, and what did you expect to happen?
Tried making UHV superconductor. Expected it to be craftable at UV/UHV tier. 

#
#### What happened instead? (Attach screenshots if needed)
UHV superconductor base needs 10500K to smelt
This needs awakened draconium coils. 
Awakened draconium can only be obtained at Tier 8 Planets (and supposedly bees)
Tier 8 rocket plates needs UHV superconductor
UHV superconductor base needs awakened draconium coils to smelt. 

After asking around, apparently EBF has a +100K bonus per voltage tier from MV, so it is actually craftable with UV voltage and EBF. However, this is not documented anywhere ingame, or if it is, it is documented in an old LV/MV-tier quest that users will likely forget by the time they reach UHV. 

Furthermore, this bonus only applies to the regular EBF, not Volcanus or Mega EBF, which most UHV players would be using.

#
#### What do you suggest instead/what changes do you propose?
List the EBF heat bonus on the EBF controller's tooltip. 
Optionally: Implement the heat bonus in the Volcanus and Mega EBF, and if so, list the heat bonus on these machines too.

**Comment by Prometheus0000** [comment]
You'd have to bother bart+alk at the bartworks+alkcorp/gt++ repos to have them implement it.

**Comment by draknyte1** [comment]
Volcanus uses vanilla GT5 logic and won’t support this, I assume the MEBF does the same.
