### ISSUE TITLE
[Suggestion] Add processing recipe a Rare Earth to MB Centrifuge

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6556]
#### Which modpack version are you using?
2.0.9.0qf4
### Add processing recipe a Rare Earth to MB Centrifuge 🤔 
![изображение](https://user-images.githubusercontent.com/47714084/91628700-1e0ca700-e9cb-11ea-96d0-75358d564874.png)

**Comment by Prometheus0000** [comment]
Post on the GT++ repo. Also, they're likely to say no, since there's already a RE chain available that they made which you're supposed to do.

**Comment by draknyte1** [comment]
No. The centrifuge recipe shouldn’t even exist.

**Comment by MotiasF33** [comment]
recipe shouldn’t even exist

**Comment by Dream-Master** [comment]
wait it exist otherwise you can't made cadmium for batteries. This recipe is the original recipe and was removed from gt++ without my notice. I add it back because I think this recipe is useful.

**Comment by draknyte1** [comment]
Cadmium can be obtained other ways, recipe is redundant.

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/91632063-43d68380-e9ac-11ea-88c6-111a32e4062a.png)
You can get it from Centrifuging Purified Piles of Sphalerite Dust.

![image](https://user-images.githubusercontent.com/8517039/91632115-9fa10c80-e9ac-11ea-9f1c-542afd201907.png)
Or Thermal Centrifuging Purified Sphalerite Ore.

Or from Chalcopyrite in HV.

You get Sphalerite Ore from the Nether, which is a whole tier before the LV battery quest anyway.
