### ISSUE TITLE
Add the mod "Vending block" from kamildanak

### ISSUE THREAD

**Issue by VeyezX** [GTNewHorizons/GT-New-Horizons-Modpack#6558]
For multiplayer servers it can be a great mod for trading/shops. As there is no other decent way to make a shopping area.

It also looks great as an item display or something for decoration.

https://www.curseforge.com/minecraft/mc-mods/vending-block

**Comment by leagris** [comment]
How about using that already available Forestry's [Trade Station](https://forestryforminecraft.info/mail:tradestation)?

**Comment by Cleista** [comment]
Don't there exist Bukkit shop plugins? If you wanted one you can look into those and run a Thermos server.

**Comment by Dream-Master** [comment]
Adding Multiplayer mods to the pack is not the best idea because it is useless for singleplayers and will make the loading phase much longer. Feel free as a server owner to add what you nee to your sever. @VeyezX

**Comment by boubou19** [comment]
we do also have trade-o-matics, which work fine for this kind of things too.
