### ISSUE TITLE
[Void Miner] DD mining ore list

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6560]
#### Which modpack version are you using?
2.0.9.0qf4
### Void miner digs about 50 unused ores, which one direction in the trash can
![изображение](https://user-images.githubusercontent.com/47714084/91687239-ed15a900-eb67-11ea-8de5-30403c687e2c.png)
### Also we have both lutetium ore and americium
![изображение](https://user-images.githubusercontent.com/47714084/91687506-8e046400-eb68-11ea-8b1f-b6364b31604f.png)
i think getting americium ore introduces a slight imbalance
### What do you think?

**Comment by 0lafe** [comment]
They fucked up bad, there's lots of other issues too. Should restore old ore list

**Comment by ScriptedPiky** [comment]
I wonder if the ore list applies to all Void Miners, and if this is the case, you can obtain large quantities of Americium way before ever making the T3 fusion reactor. In this case, you might even be able to skip the T2 fusion reactor and build a straight-up T3 (assuming you have the materials) after some time.

**Comment by Prometheus0000** [comment]
Isn't this just for the DD? You need to be post-infinity or something, yeah? Or more, if the recipe has been changed, I can't remember if that actually happened yet.

And which VM did you use? If this was a problem, I would've thought other people would've mentioned it by now?

**Comment by GTNH-Colen** [comment]
The void miner works usually by digging up the ores in the dimension it's in, only special case is that in the OW/nether/end you get tellurium ore on top of usual generation lists. The DD is special however, when a void miner is placed there it will be able to mine every available ore in the game, all 279 of them. This is why people are getting ores that have 0 uses or cannot usually be mined like ichorium ore or indium ore.

Still these useless ores should really be removed, they just clutter the ore table.

**Comment by Alexdoru** [comment]
> I wonder if the ore list applies to all Void Miners, and if this is the case, you can obtain large quantities of Americium way before ever making the T2 fusion reactor. In this case, you might even be able to skip the T2 fusion reactor and build a straight-up T3 (assuming you have the materials) after some time.

To access to the DD you need to craft the Portal and the recipe has been changed to be UEV so you can't skip fusion reactors.

**Comment by 0lafe** [comment]
I'm not sure if "ive already made a bunch of this, so it should be easier" works on all, or even most of the ores introduced with the VM

**Comment by GTNH-Colen** [comment]
> I'm not sure if "ive already made a bunch of this, so it should be easier" works on all, or even most of the ores introduced with the VM

It does need refining, just isn't at the top of anyones priority list atm

**Comment by Prometheus0000** [comment]
If you can figure out where the list is, feel free to PR it. Note that we also now have a BW fork, presumably to fix things until Bart comes back, so if the problem's there we should be able to change it.

**Comment by LewisSaber** [comment]
Leave only clean ores,maybe remove fusion ores but leave luthetium,this will make new DD cost worth grinding

**Comment by Prometheus0000** [comment]
WTF is a clean ore? Also, list. Again, this would remove ALL INSTANCES OF THE ORE if we change the materials file. So if you mean remove chalcopyrite (unclean? not the right word, maybe you mean impure?), it would remove it from the OW too.

**Comment by GTNH-Colen** [comment]
> Leave only clean ores,maybe remove fusion ores but leave luthetium,this will make new DD cost worth grinding

As Prometheus says, defining what is and what is not a "clean" ore is very hard. For example most would probably consider Rutile a non clean ore given you can get titanium ore however it may be useful to some players since you can use it for titaniumtetrachloride in chemical reactor recipes.

**Comment by LewisSaber** [comment]
I mean ores that need electrolys and cant be smelted directly to clean resource/like chalcopyrite  can be smelted into copper but something like grossular need electrolysing? 
If removing ore from DD requires removing it from game,we need to ask bart to rewrite code in such way that it wont be removed

**Comment by LewisSaber** [comment]
Clean is something that you dont need to process anymore,no need for electrolysing, rutile is exeption

**Comment by Prometheus0000** [comment]
What about apatite? Or lapis? Or galena and sphalerite? There's a number of useful non-pure materials. For example there's no calcium ore, so calcite is the best you get. There's a also no rare earth ore or potassium ore either. Determining this is hard, so I'm not going to do it.

**Comment by alphaNOVAircraft** [comment]
Having nearly all ores aviable seems fine to me, you can still void the compounts you consider not worth processing 

Americium and Europium ore shouldnt be a thing even tho i dont think its gamebreaking.

**Comment by Prometheus0000** [comment]
Also, the ores for materials that _aren't used at all_.

**Comment by alphaNOVAircraft** [comment]
Sure, didnt think i have to add that noone needs ores that have no use......... thought thats kinda self explaining

**Comment by 0lafe** [comment]
Lots of pure ores don't belong there imo. If we're actually making the ore list good, things like ichorium, fusion mats, and a few others are really out of place. Maybe for like Ti or W, but imo pure ores that aren't T-3 from DD shouldn't be included. Making ore gen better is one thing, but removing proc chains seems off for things that are still relevant.

**Comment by alphaNOVAircraft** [comment]
> Lots of pure ores don't belong there imo. If we're actually making the ore list good, things like ichorium, fusion mats, and a few others are really out of place. Maybe for like Ti or W, but imo pure ores that aren't T-3 from DD shouldn't be included. Making ore gen better is one thing, but removing proc chains seems off for things that are still relevant.

There arent lots of compound ores later on anyways, so if you let W and Ti in there (which definitly should be the case) there is no other processing chain you can currently skip (plat line gives you metallic powder etc in any ore form).

**Comment by D-Cysteine** [comment]
I have no idea which ores should be removed, but I added a config option to remove ores from the Deep Dark void miner, so that should make it easier to make changes here. There's also an option to log a complete list of all ores that are getting added.
 * https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/196
 * https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/8288

With a bit more effort, it should also be possible to add a config option to adjust the weights for each ore individually (right now they all have equal weight).

**Comment by D-Cysteine** [comment]
Here's a complete list of the ores, from GTNH 2.1.1.0: https://pastebin.com/cXE9k0Yq

**Comment by Prometheus0000** [comment]
Dream, this also wasn't fixed, all that was done was adding the _option_ for BLing stuff from the VM.

**Comment by Dream-Master** [comment]
ah ok didnt know
