### ISSUE TITLE
Drawer size upgrade recipes missing

### ISSUE THREAD

**Issue by T0mmen** [GTNewHorizons/GT-New-Horizons-Modpack#6563]
I am using GT New horizons version 2.0.9.0

I was attempting to craft drawer size upgrades. The recipes do not show in NEI either with R or leftclick.

I found out the recipes through discord but they did not work .

I hope this bug will be fixed.

![GTNH iron drawer upgrade not working](https://user-images.githubusercontent.com/70544861/91766968-14aa5700-ebe4-11ea-9288-8ccd96a2eaf2.PNG)
![GTNH gold drawer upgrade not working](https://user-images.githubusercontent.com/70544861/91767128-55a26b80-ebe4-11ea-900b-e4aebe1363c1.PNG)

**Comment by Prometheus0000** [comment]
Try reinstalling your pack, this has happened before.

**Comment by T0mmen** [comment]
> Try reinstalling your pack, this has happened before.

I will see if that fixes it.

**Comment by MotiasF33** [comment]
> 
> 
> > Try reinstalling your pack, this has happened before.
> 
> I will see if that fixes it.

![изображение](https://user-images.githubusercontent.com/47714084/91768569-7966b100-ebe6-11ea-98f3-9054ece5620b.png)
![изображение](https://user-images.githubusercontent.com/47714084/91768598-82578280-ebe6-11ea-962f-45a67da3f76e.png)

**Comment by DualBallers** [comment]
See #5995 
Easiest fix is to delete the storage-drawer.zs file in the scripts folder.

**Comment by T0mmen** [comment]
> See #5995
> Easiest fix is to delete the storage-drawer.zs file in the scripts folder.

I will try this, thank you for the tip. I'll say if it worked. Gonna try just restarting first, then resinstalling.

**Comment by T0mmen** [comment]
> See #5995
> Easiest fix is to delete the storage-drawer.zs file in the scripts folder.

Yep, that fixed it, thank you :D
