### ISSUE TITLE
Wand Liquifaction Focus causes smelting machines to void future outputs

### ISSUE THREAD

**Issue by General-Ike** [GTNewHorizons/GT-New-Horizons-Modpack#6564]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Personal server hosted by Server Miner
#
#### What did you try to do, and what did you expect to happen?
I place Tumbaga into my LV Electric Furnace, HV Electric Oven, and my EV Multi-Smelter (I verified that it was receiving sufficient power) and I expected the machines to output Tumbaga Ingots.
#
#### What happened instead? (Attach screenshots if needed)
In the single block furnaces, the very 1st ingot would output and smelt as per normal; however, all subsequent smelting operations did not output any ingots, though they still consumed the dusts. Additionally, the use of a hopper beneath the machines would result in not ingots being output at all. Further experimentation interestingly revealed that the very first Tumbaga ingot could not be shift clicked out of the machine.

The multi-smelter simply did not output ingots in any situation, regardless of stack size, or if there was an output chest directly attached or not.

I was not able to replicate it, but I'm quite sure that this issue occurred with Eglin Steel in the past. I've been smelting my GT++ alloys with a wand ever since.
#
#### What do you suggest instead/what changes do you propose?
I'd like to not spend energy to void my alloy dusts please :P

**Comment by Dream-Master** [comment]
@General-Ike Please post this on alkalus gt++ repo also. 
@draknyte1 any idea?

**Comment by draknyte1** [comment]
Not a clue, they’re standard furnace recipes. 🤷🏻‍♀️

If they work in a normal furnace, it’s a GT issue.

**Comment by General-Ike** [comment]
Further testing has yielded me an answer. Use of the item smelting wand focus from TC will make it so that trying to smelt that item in any furnace type block causes the issues as stated. I believe restarting the server might clear the bugged items until they are smelted with the wand focus again.

**Comment by General-Ike** [comment]
Whoops, my bad. I closed the wrong issue. This is not a problem with GT++ dusts, this is a problem with the liquifaction wand focus. See my comment above.
