### ISSUE TITLE
ic2 solar panels cannot transfer EU through redstone alloy (LV) wire.

### ISSUE THREAD

**Issue by xTwi** [GTNewHorizons/GT-New-Horizons-Modpack#6565]
#### Which modpack version are you using?
2.0.9.0
--Reporting someone elses issue recently posted in #help --
#
#### What did you try to do, and what did you expect to happen?
use redstone alloy cable (LV) to transfer EU from ic2 solar panels
these are superconductors, so no EU loss is possible.
#
#### What happened instead? (Attach screenshots if needed)
does not transfer. red alloy cables (ULV) work, however
https://cdn.discordapp.com/attachments/234936569360809996/750474777365446737/2020-09-01_23.58.43.png
#
#### What do you suggest instead/what changes do you propose?
take a look at ic2 solar panel code, redstone alloy wire may be incompatible with other ic2 machines due to this.

**Comment by Dream-Master** [comment]
Its gt++ wire so far ik. Maybe @draknyte1 knows more
