### ISSUE TITLE
Block of Infinity Recipe Change Suggestion

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6566]
#### Which modpack version are you using?
2.0.9.0qf4
### Need remove recipe from Implosion Compressor or Compressor, solidifier i.c.
![изображение](https://user-images.githubusercontent.com/47714084/91936264-3268e080-ecf8-11ea-91d2-c245dc79fd6f.png)
![изображение](https://user-images.githubusercontent.com/47714084/91936273-3563d100-ecf8-11ea-90dd-141f1eadddae.png)
![изображение](https://user-images.githubusercontent.com/47714084/91936280-37c62b00-ecf8-11ea-81d7-5d4b7ccba341.png)
![изображение](https://user-images.githubusercontent.com/47714084/91936287-3bf24880-ecf8-11ea-972d-76ff9422f29f.png)
![изображение](https://user-images.githubusercontent.com/47714084/91936300-3eed3900-ecf8-11ea-9fa1-d2c00e17ea68.png)

**Comment by Prometheus0000** [comment]
Why exactly do they need to be removed?

**Comment by MotiasF33** [comment]
> 
> 
> Why exactly do they need to be removed?

For what need Imposion Compressor recipe if i can make it in Alloy smelter?

**Comment by MotiasF33** [comment]
I think need keep only Implosion Compressor recipe
It would be nice
Because on the high tier this mechanism is almost never used

**Comment by boubou19** [comment]
16 industrial tnt are neglectable in comparison to the infinity ingot cost. At that point in the game, spending 16 itnt for a craft is a joke for the player, so it does not really matter. But i do agree that it is not coherent. To me, because of the name of the ingots, they should be densier than cosmic neutronium, so they should be implosion compressior only.

**Comment by Prometheus0000** [comment]
Maybe we should remove them all and have it require the Neutronium Compressor or something? Or is that easier than ICing it? I also forget if it needs Inf ingots to make, but something a little more interesting for infinity does sound like a good idea.

**Comment by MotiasF33** [comment]
> 
> 
> Maybe we should remove them all and have it require the Neutronium Compressor or something? Or is that easier than ICing it? I also forget if it needs Inf ingots to make, but something a little more interesting for infinity does sound like a good idea.

neutronium compressor make it at 1 tick and no consuming of energy (
may be 64 ITNT in Implosion compressor for infinity?
and let's 48 ITNI for Cosmiq Neutronium?

**Comment by botn365** [comment]
by the time you have infinity you have the electric imlosion comresser wich is prety fast

**Comment by MotiasF33** [comment]
> 
> 
> by the time you have infinity you have the electric imlosion comresser wich is prety fast

Unfortunately, it can broken it out after restarting the server

**Comment by botn365** [comment]
in one of the bartworks brenches that is fixed also it stoping from working evry few ticks
