### ISSUE TITLE
[Suggestion] LCR Magic metalls recipes

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6567]
#### Which modpack version are you using?
2.0.9.0qf4
### The first few recipes are still normal in proportion:
![изображение](https://user-images.githubusercontent.com/47714084/91946320-e6259c80-ed07-11ea-8d16-12f103d2f12b.png)
![изображение](https://user-images.githubusercontent.com/47714084/91946346-e9b92380-ed07-11ea-82a5-1fea42fd6c42.png)
![изображение](https://user-images.githubusercontent.com/47714084/91946446-f0479b00-ed07-11ea-8020-7ddfe6b3debb.png)
### Mytryl dust has almost no uses:
![изображение](https://user-images.githubusercontent.com/47714084/91946824-0d7c6980-ed08-11ea-9a18-88492fd31eb7.png)
### Ichorium ingot from _190b_ matter:
![изображение](https://user-images.githubusercontent.com/47714084/91948968-aa3f0700-ed08-11ea-8be2-14c67b32a9db.png)
### Are these recipes necessary, if so, why? 🤔 
Lower tier, just can't get ingredients, and on the higher tier it is not needed

**Comment by Prometheus0000** [comment]
These are alternative methods to get stuff, they're supposed to be hard/absurd. They're mostly for no-rocket runs. I guess the ichorium one is for people who really really hate TC?

**Comment by MotiasF33** [comment]
> 
> 
> These are alternative methods to get stuff, they're supposed to be hard/absurd. They're mostly for no-rocket runs. I guess the ichorium one is for people who really really hate TC?

After this recipe, they will have to study TС
