### ISSUE TITLE
[AE2Stuff] Advanced Inscribered not accepting energy from network

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6568]
#### Which modpack version are you using?
2.0.9.0qf4
###  Advanced Inscribered not accepting energy from network
if u have Neutronium Cell as one energy generator
![изображение](https://user-images.githubusercontent.com/47714084/91966826-0dd23000-ed1b-11ea-9006-50819787726b.png)
### But it can energy acccept only directly from the Neutronium cell
![изображение](https://user-images.githubusercontent.com/47714084/91966898-27737780-ed1b-11ea-80f0-e4c20b4c5a53.png)

**Comment by Devtron3D** [comment]
could you do this
Power source -> small smart cable -> inscriber
Mine works that way.

**Comment by Prometheus0000** [comment]
Perhaps this is caused by thermos? Try in SP
