### ISSUE TITLE
[Suggestion] Add possibility hide the Grandma Suit

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6571]
#### Which modpack version are you using?
2.0.9.0.qf4
### Add possibility hide the Thermal Padding Galacticraft
It cannot be hidden by any means
![изображение](https://user-images.githubusercontent.com/47714084/92143422-efa12880-ee1d-11ea-95fb-3817bb75227e.png)

**Comment by Dream-Master** [comment]
What is this ? @MotiasF33

**Comment by MotiasF33** [comment]
> 
> 
> What is this ? @MotiasF33

Thermal padding
![изображение](https://user-images.githubusercontent.com/47714084/92153760-701b5580-ee2d-11ea-9faa-aa5cb51cd282.png)

**Comment by Prometheus0000** [comment]
You also can't hide the stuff like the glass helmet or whatnot from GC.

**Comment by MotiasF33** [comment]
> 
> 
> You also can't hide the stuff like the glass helmet or whatnot from GC.
Yes, but they are not as visible as this suit...

**Comment by MotiasF33** [comment]
I do it 🐙 as resourcepack..but who cares
![изображение](https://user-images.githubusercontent.com/47714084/92228323-60912080-eeb0-11ea-8c85-d2e5e47a4943.png)
![изображение](https://user-images.githubusercontent.com/47714084/92228369-743c8700-eeb0-11ea-8d6d-6137917e9b4c.png)
