### ISSUE TITLE
Quest #260 not completing

### ISSUE THREAD

**Issue by Dekuscrubb** [GTNewHorizons/GT-New-Horizons-Modpack#6572]
#### Which modpack version are you using?
GTNH
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
attempted to complete the quest "Adept Thaumaturgy"
#
#### What happened instead? (Attach screenshots if needed)
Quest fails to detect the requested item, a gold capped greatwood wand
![2020-09-03_18 24 09](https://user-images.githubusercontent.com/70727521/92179652-19088700-ee13-11ea-96f1-cd9bcdea3a3d.png)
![2020-09-03_18 24 34](https://user-images.githubusercontent.com/70727521/92179663-1d34a480-ee13-11ea-8a50-2c70e0d810c4.png)

#

**Comment by Prometheus0000** [comment]
Already Fixed. Update the quest file from the repo or complete it with commands.
