### ISSUE TITLE
Crystalline and Melodic slower than Octadic capacitor

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#6573]
2.0.9.0

I wanted to increase the spawn rate of my Powered Spawner from an Octadic capacitor, but it seems that both the Crystalline and Melodic (edit: and Totemic) capacitor are both significantly slower than the Octadic.

Octadic ~10 sec
Crystalline ~20 sec
Melodic ~30 sec

**Comment by Dream-Master** [comment]
@Zoko061602 any idea? You ported the stuff or did i doing the tiering wrong

**Comment by Zoko061602** [comment]
Probably this incomplete switch:
https://github.com/GTNewHorizons/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/spawner/TilePoweredSpawner.java#L85

**Comment by MotiasF33** [comment]
it works differently in different mechanisms
For example:
- SAG 
Octadic 100 RF/t
Crystalyne 260 RF/t
- Soul Binder
Octadic 2000 RF/t
Crystalyne 260 RF/t

**Comment by DualBallers** [comment]
Ya, it looks like theres a switch in the [Soul Binder](https://github.com/GTNewHorizons/EnderIO/blob/8807be588733f8a6a18e872c6bbd577935cb4a7f/src/main/java/crazypants/enderio/machine/soul/TileSoulBinder.java#L161) for all types


but the same type of switch is missing in the [Slice & Splice](https://github.com/GTNewHorizons/EnderIO/blob/8807be588733f8a6a18e872c6bbd577935cb4a7f/src/main/java/crazypants/enderio/machine/slicensplice/TileSliceAndSplice.java#L62), [Attractor](https://github.com/GTNewHorizons/EnderIO/blob/8807be588733f8a6a18e872c6bbd577935cb4a7f/src/main/java/crazypants/enderio/machine/obelisk/attractor/TileAttractor.java#L94), [Aversion Obelisk](https://github.com/GTNewHorizons/EnderIO/blob/8807be588733f8a6a18e872c6bbd577935cb4a7f/src/main/java/crazypants/enderio/machine/obelisk/aversion/TileAversionObelisk.java#L72), [Farming station](https://github.com/GTNewHorizons/EnderIO/blob/8807be588733f8a6a18e872c6bbd577935cb4a7f/src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java#L709)

Couldn't find a switch for the SAG mill, so maybe I've overlooked some other places.

**Comment by Zoko061602** [comment]
Most regular EnderIO machines extend some abstract machine, I think I only changed it in there.

**Comment by DualBallers** [comment]
By the way @Zoko061602, do you think it would be possible to have some information in the item data on the capacitor stats?
![image](https://user-images.githubusercontent.com/30087707/92332860-ff6c7700-f080-11ea-8af0-33a8b4074586.png)

Looking into the code it seems like, Silver = Basic, Endergetic = Double, Endergised = Octadic, but it is not possible (?) to find this information in-game.

**Comment by MotiasF33** [comment]
> 
> 
> Most regular EnderIO machines extend some abstract machine, I think I only changed it in there.

We can create a separate issue about this addon?
for example this capacitor(Eff5) cannot be enchanting..
![изображение](https://user-images.githubusercontent.com/47714084/92571929-690ca100-f28c-11ea-8fdf-2fbd9a309b8d.png)

**Comment by D-Cysteine** [comment]
Here's a list of places that probably should be updated to handle more capacitor types (most already mentioned above, but just to put them all in one place):
 * [Crafter](https://github.com/GTNewHorizons/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/crafter/TileCrafter.java#L124-L132)
 * [Farming Station](https://github.com/GTNewHorizons/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/farm/TileFarmStation.java#L708-L725)
 * [Attractor Obelisk](https://github.com/GTNewHorizons/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/obelisk/attractor/TileAttractor.java#L93-L116)
 * [Aversion Obelisk](https://github.com/GTNewHorizons/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/obelisk/aversion/TileAversionObelisk.java#L71-L92)
 * [Slice'N'Splice](https://github.com/GTNewHorizons/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/slicensplice/TileSliceAndSplice.java#L60-L75)
 * [Soul Binder](https://github.com/GTNewHorizons/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/soul/TileSoulBinder.java#L160-L189)
 * [Powered Spawner](https://github.com/GTNewHorizons/EnderIO/blob/master/src/main/java/crazypants/enderio/machine/spawner/TilePoweredSpawner.java#L84-L107)

From this tangentially related PR:
 * https://github.com/GTNewHorizons/EnderIO/pull/31#issue-1025961495
