### ISSUE TITLE
Quest not updating

### ISSUE THREAD

**Issue by reesycup** [GTNewHorizons/GT-New-Horizons-Modpack#6575]
#### Which modpack version are you using?
2.090
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Tried to complete quest, will not recognize MV motor. (NBT issue?)
Quest is "Coal Steam Jetpack" under "Armors and Jetpacks"

**Comment by Dream-Master** [comment]
try to use command /bq_admin default load
or/and use a newer file
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/betterquesting/DefaultQuests.json

**Comment by reesycup** [comment]
thank you the command worked.
