### ISSUE TITLE
Drawers

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#6578]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
forge
#
#### What did you try to do, and what did you expect to happen?
[Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
[Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel StorageDrawers
java.lang.NullPointerException

**Comment by MotiasF33** [comment]
> 
> #### Which modpack version are you using?
> 
> 2.0.9.0
> #### If in multiplayer; On which server does this happen?
> 
> forge
> #### What did you try to do, and what did you expect to happen?
> 
> [Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
> java.lang.NullPointerException
> [Client thread/ERROR] [FML]: There was a critical exception handling a packet on channel StorageDrawers
> java.lang.NullPointerException

attach full crash-log

**Comment by PredVesTNiK2142** [comment]
this is full crash log

**Comment by PredVesTNiK2142** [comment]
![image](https://user-images.githubusercontent.com/63409840/92327599-f67da480-f084-11ea-88ba-c52b0ec5c3f7.png)

**Comment by PredVesTNiK2142** [comment]
from another player https://pastebin.com/nqZ5MPB5

**Comment by Prometheus0000** [comment]
Under what circumstances did the crash happen though?

**Comment by Glease** [comment]
@Dream-Master shouldn't this be closed? This was merged before 2.1.1.0 release.

**Comment by Dream-Master** [comment]
Close it
