### ISSUE TITLE
[Suggestion] Extreme Kinetic Generator

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6579]
#### Which modpack version are you using?
2.0.9.0qf4
### I suppose remove the 131072 eu / t limit for Extreme kinetic generator
Extreme kinetic generators are the **latest** version of kinetic source
If we could remove limitation, water and wind kinetics would be a alt source of energy, even at high tiers.

![изображение](https://user-images.githubusercontent.com/47714084/92321762-3e74db00-f035-11ea-828d-9532e9e3563b.png)
_generation energy at 67.2 MCW (no rain, no storm)_
# What do you think? 💨

**Comment by Dream-Master** [comment]
The mod is closed source and the mod dev not response on my question about change the license or even add some.

**Comment by 0lafe** [comment]
What if instead of adding stuff past zpm, we remove all of them until we can have decent EV/IV kinetic gens. Then we can think about *if* we even want those in LuV

**Comment by Prometheus0000** [comment]
What's the problem with them you have at EV/IV? Is it #6206?

**Comment by 0lafe** [comment]
Lmao no. They're awful power producing mechanics for EV+. Don't fit the multi age in any way, they're basically singleblocks. The rotor mec is pretty broken, and they have 0 other upkeep. The costs are also pretty dumb imo. I don't think lots of ebf makes it fair to have something that reduces power productions to such a low level on input

**Comment by Prometheus0000** [comment]
Was there and issue for multiblock kinetics? I remember it coming up before. I'd be cool with that, but we _have_ this, we'd need someone to code new multis to change it, so maybe not disable them until we do?

**Comment by 0lafe** [comment]
I personally don't agree that these pieces of ic2 shit deserve to be in NH

**Comment by Prometheus0000** [comment]
Well, I'd be fine removing all solars and kinetics, but that's not going to happen, yeah? So, either learn to code or find someone who wants to make the multi-kinetics if you want to progress that. Or make a ticket if there isn't one.

**Comment by 0lafe** [comment]
>Well, I'd be fine removing all solars and kinetics

Let's go ahead and do it then 🤷‍♂️

**Comment by GTNH-Colen** [comment]
> > Well, I'd be fine removing all solars and kinetics
> 
> Let's go ahead and do it then 🤷‍♂️

I really don't get why some people have such a deep-seated hate of solar panels lol.

**Comment by Prometheus0000** [comment]
I just don't like passive power gen, but I don't hate it or anything.

**Comment by 0lafe** [comment]
I like when the complexity for achieving lots of infinite power scales with progress in the game. Unlike solars/kinetics that aren't doing anything better than what solar boilers did in steam :/

**Comment by MotiasF33** [comment]
> 
> 
>  So, either learn to code or find someone who wants to make the multi-kinetics if you want to progress that.
It seems Alkalus tried to create something like this, but I don't think it will ever work.
![изображение](https://user-images.githubusercontent.com/47714084/92401840-31d8ab80-f137-11ea-98d7-690c0983c1c3.png)

**Comment by MotiasF33** [comment]
and Bartworks have a base for kinetic generators
![изображение](https://user-images.githubusercontent.com/47714084/92402070-a01d6e00-f137-11ea-9313-b6a4bf25606e.png)

**Comment by repo-alt** [comment]
lol
