### ISSUE TITLE
inconsistency between questbook and the game when a wall share is done

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6581]
#### Which modpack version are you using?
2.0.9.0 QF4

I had several reports from players saying that the energy hatches can be shared. However, the quests say that a player should only share input/output hatches/buses when he does a wall share. So i was wondering if there was a reason code wise to avoid that (extra checks in code that is cpu intensive or whatever), or if the quests are simply outdated (quest 1494 for exemple).

**Comment by GTNH-Colen** [comment]
You can only share an energy hatch when the power consumed is low enough to allow for it, for example if you had a UV energy hatch being shared between two multiblocks both of which are using say 200,000 eu/t then it should work fine. This isn't that common though so people often say just not to share the energy hatch but on some occasions it works out well.

I guess the person who wrote the quest book never consider this though, there are some things which simply cannot be shared such as the maintenance hatch (Though the auto maintenance hatch can be wall shared interestingly). Additionally mufflers can also be shared between multiblocks.

**Comment by boubou19** [comment]
interesting, i might reconsider my opinion on wall sharing thanks to that.

**Comment by Prometheus0000** [comment]
Did you want something in the QB changed? You'd need to tell me which quest(s).

**Comment by boubou19** [comment]
will try to see if there is more than the 1494
