### ISSUE TITLE
Replicator II internal tank glitched

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#6583]
GTNH 2.0.8.8

UU - replicator II not accepting UUM after chunk load. I am in SP, I have broken the machine, placed it in a different chunk, reloaded my client, and reloaded the entire pack. It gets stuck at a certain amount for the tank and stays there. Once it was at 88L and now it's at 273L

**Comment by boubou19** [comment]
did you tried it on the latest version? maybe it was fixed since.

**Comment by redmage17** [comment]
> 
> 
> did you tried it on the latest version? maybe it was fixed since.

New GT requires dreamcraft and not dealing with the chem plant bullshit

**Comment by boubou19** [comment]
It's fixed according to #5802, so consider updating your pack to get the proper fix.

**Comment by Prometheus0000** [comment]
What bs do you not want to update for?

**Comment by redmage17** [comment]
Chemplant/rocket fuels
