### ISSUE TITLE
White Metal Dust Centrifuges to Platinum Metallic Powder Dust

### ISSUE THREAD

**Issue by General-Ike** [GTNewHorizons/GT-New-Horizons-Modpack#6584]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Private server hosted by Server Miner
#
#### What did you try to do, and what did you expect to happen?
I tried to centrifuge White Metal Dust and expected to get back the materials that I put into the alloy.
#
#### What happened instead? (Attach screenshots if needed)
the alloy yielded back all the dusts, but replaced the 2x Platinum with 4x Platinum Metallic Powder. This is the recipe listed in NEI.
#
#### What do you suggest instead/what changes do you propose?
The alloy dust should centrifuge back into pure Pt. With use of the GT++ sifter in a plat line, this duplicates Pt Metallic Powder Dust, albeit, in a very expensive way.

**Comment by Dream-Master** [comment]
well maybe gt++ and bartsworks not working good together ?

**Comment by draknyte1** [comment]
Welcome to BartWorks breaking *every* recipe that returns platinum. 

Go bitch at Bart to fix it, nothing I can do.

**Comment by Prometheus0000** [comment]
Bart says GT++ isn't supported, so he won't change it.

**Comment by Prometheus0000** [comment]
Duplicate, too.
