### ISSUE TITLE
LGT stops running if the calculated Optimal Flow [L/t] is less than 1

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6586]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### What did you try to do, and what did you expect to happen?
Run a LGT with Nitrobenzene and an Adamantium Small Turbine
#
#### What happened instead? (Attach screenshots if needed)
Doesn't run.

I noticed when I was added some columns to the turbine page on the main spreadsheet that many turbines end up calculating to 0 EU when using Nitrobenzene. I figured this was just a math problem when rounding down, but they actually don't run ingame.

You can look at the main spreadsheet, or the updated turbine calculator to see the math it uses. I couldn't understand the math in GT_MetaTileEntity_LargeTurbine_Gas.java myself of course.
https://docs.google.com/spreadsheets/d/15dn8iBJJlNYCi_sKnpL0SJ-c3TaBvOSYpGZRI-TjowA/edit?usp=sharing
#
#### What do you suggest instead/what changes do you propose?
Run? Probably at lowered efficiency? Or have a warning or error message? Or tell me to put a message in a quest.

**Comment by Glease** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/blob/9c7f9fa6e4ab8d1ad45f43c59ee27ebade3011b8/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeTurbine_Gas.java#L91

Possible solution 
1. consume X mb every Y tick so the average is on par with calculated values. Fluid regulators however cannot handle this without some more setup, or we need to make a more advanced fluid regulator.
2. Round up no matter what. Wastes fuel and you are better off burning something less complex and easier to manufacture.

Both are possible code wise, but we need to make the decision first.

**Comment by Prometheus0000** [comment]
If you look at the turbine sheet https://docs.google.com/spreadsheets/d/1Rsz0rH9tIVJxr18b1Z6-QxOSaEKssxF7u2naQTq2Mqg/edit?usp=sharing
You can see it mostly affects small turbines, which people probably won't use, I dunno whether it really matters. I'd say the second option, since that seems like a lot less work. It can affect other fuels, but not as much, since they generally need a higher L/t. Also, by the time you can mass-produce NB, I think you would be capable of making a turbine out of the non-zero large turbine materials.
