### ISSUE TITLE
Tinker's Construct quest requires crafting even though the stations in question are very often found in the world.

### ISSUE THREAD

**Issue by rabitibike112** [GTNewHorizons/GT-New-Horizons-Modpack#6588]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Not multiplayer
#
#### What did you try to do, and what did you expect to happen?
I tried quickly running through the tier 0.5 quests.
#
#### What happened instead? (Attach screenshots if needed)
When i got to the quest that requires the crafting of **Tinker's Construct** tool benches i already had the full set needed for the quest but had to craft them anyways because it's a "crafting" quest instead of "retrieval" quest. Thus i had to waste a bit of time, and a few resources. Most painful being the 16 paper that i could've otherwise used for tool molds.
#
#### What do you suggest instead/what changes do you propose?
I propose the change from crafting quest to retrieval quest.

I understand that this has not been done mainly because of multiplayer, where with one set of blocks a whole party could finish the quest. But i'd like to counter that by saying that if they are a party, then they don't need more than one set of these blocks anyways. Thus they would also be wasting resources needlessly.
When it comes to chests and crafting tables it makes sense to be crafting because more than 1 will be needed in each run/world.
The biggest problem, with this specific quest is that these blocks are often found in villages, which are also often found very easily and early in _Singleplayer_ worlds. In multiplayer it might not be the case, which is why the quest could still fullfil it's goal of teaching people how to craft these stations.

One last thing and I will stop wasting your time, sir reader. I happen to be an idiot who plays the modpack on **_Hardcore_**, which obviously results in me playing the early-game rather often. At least give this change a real though while keeping in mind that people like me exist.

Thank you for taking the time to read this. Hope you have a great life!

**Comment by ben0sharples** [comment]
I think the key point in this is that you will likely only want **one** of most of the Tinkers blocks per playthrough. Maybe a second Tool Station to carry around for repairs/second Pattern chest for casts or whatever, but duplicates of the others are almost entirely unnecessary.

I actually really like Dream's ideology on Crafting tasks for things you're going to repeat a lot. I think it's vital that people craft their first machine hulls/motors etc. by hand so they know what that recipe looks like, and can see the analogous higher tier ones. You're going to be making them over and over, so forcing people to learn them is a great idea.

But where I think that falls down is these cases where you just need the one. Why would you need to learn that? Tinkers blocks are a really obvious case of it and would be worth changing in my view.

**Comment by Prometheus0000** [comment]
The thing is, you still craft a machine hull or motor by hand, retrieval just means that it applies if you have it in your inventory so you could theoretically hand it to someone else and have them complete it. But if you're doing that for someone I would think you're in a team already, and it would complete for everyone. And I don't think team reward abuse is something to really care about.

**Comment by ben0sharples** [comment]
Is it not possible to get a motor/hull through like, a LootGames dungeon or whatever beforehand? I don't think you get any lootbags that'll have them by then but there might be other tier skippy ways of getting them I'm not aware of.

**Comment by Prometheus0000** [comment]
Ah, I forgot, that might be true. Any, I agree for the one-offs.
