### ISSUE TITLE
[Suggestion] Tungsten Nerf

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/GT-New-Horizons-Modpack#6589]
Heya :D
feels good to be back!

Here is my idea:
![tungstenchain](https://user-images.githubusercontent.com/35029480/92690424-48eae980-f341-11ea-9e89-e2326018d129.png)

**Comment by Prometheus0000** [comment]
Wasn't the whole problem with tungsten that it takes a ridiculously long time to smelt? I don't see a solution for that in this? Not to mention that it already has to be gotten from an impure source at not great rates. Now you're adding platinum chain level complexity to it? Why? Now it'll be even longer, and more complicated, and use more power for no reason? Maybe apply this to something post-platinum that's too easy like black plutonium or something.

Why do you even want to nerf tungsten in the first place?

**Comment by Dream-Master** [comment]
I am always for a more complicated process so long its not get annoying.

**Comment by Shattered2909** [comment]
It is not Platinum Chain level of complexity and I think we can reduce the time it takes to smelt Tungsten by 1 or 2 minutes, that is fine.

This is to make it actually more complicated than Titanium, the current Electrolyzing recipe is too simple for IV.

**Comment by Prometheus0000** [comment]
Not the entire chain of course, but part of it. I think it should be <# of titanium steps> + 1/2. Was Rutile -> Titanium dust 2 steps? I forget. Plus keep in mind you're suggesting 3 recipes with 3 inputs AND 2 outputs, that's a decent jump in complexity comparatively.

**Comment by Shattered2909** [comment]
Yes, it is a decent jump. We are talking about IV tier GTNH!

**Comment by Prometheus0000** [comment]
Isn't it EV? You make it to build the IV machines. And you have the whole platinum chain to think about too if it's IV, or just the platinum stuff if it's EV.

I'd like comments from other people as well though when it's not 4AM.

**Comment by Shattered2909** [comment]
Well mid to late EV.

**Comment by redmage17** [comment]
Don't need another Chlorine sink, need to make tungsten smelting shorter if you are doing this

**Comment by Shattered2909** [comment]
I already mentioned in an earlier comment that I think smelting it takes too long, but we definitely need another Clorine Sink :D

**Comment by johnch18** [comment]
How about we fucking not.

**Comment by Dream-Master** [comment]
@johnch18 can you write down it less vulgar?

**Comment by Shattered2909** [comment]
So much weakness in this thread :D

**Comment by Shattered2909** [comment]
Okay how about this:

Change Tungstencarbide to not just be a Tungsten + Carbon mix.

1 Tungsten Dust + 6000mb Chlorine = 1 Tungsten Hexachloride Dust (WCl6)
480 EU/t in a Chemical Reactor for 30 seconds

1 Tungsten Hexachloride Dust (WCl6) + 6000mb Hydrogen + 1000mb Methane = 1 Tungstencarbide Dust + 8000mb Diluted Hydrochloric Acid
480 EU/t in a Chemical Reactor for 30 seconds

**Comment by Prometheus0000** [comment]
That's a different material, so it belongs in another ticket. And why do you want to use chlorine so much? There are other materials to use. And what even is the use of Tungstencarbide?

**Comment by Shattered2909** [comment]
I don't want to use more Chlorine, these are just the recipes that were implemented in Gregicality (1.12 GT) and they make sense. It's just dissolving metals in acid to do chemical reactions.

In my opinion there should be some more Chlorine sources. I don't exactly remember the purpose of Tungsten Carbide outside of Neutron Reflectors...

**Comment by Prometheus0000** [comment]
We have other acids then? What about the GT++ ones for RE I/II/III?

**Comment by Shattered2909** [comment]
Other acids might be okay too, but please do not use GT++

**Comment by Prometheus0000** [comment]
? If Alk changes them to be ridiculous, we can change them then? Or are they too ridiculous already? I believe you're supposed to mass-produce them for RE processing so they shouldn't be too bad?

**Comment by Shattered2909** [comment]
How about just going with Hydrofluoric Acid?

**Comment by Prometheus0000** [comment]
That's fine too. Wasn't fluorine basically just used for LCRs, even if it's annoying to get? Was there another use for HFA?

**Comment by Shattered2909** [comment]
Well yeah, mostly PTFE at the moment.

**Comment by botn365** [comment]
the step of WO3 + H2 = W + H2O shoudl be difrent 
it should be 2 WO3 + 3 C = 2  hot tungsten ingots + 3 CO2 60 seconds EV
this way the last step is a EBF and we dont have to reduce the curent smelting time 
this wil also discourage people to use the pure tungsten ores

**Comment by GTNH-Colen** [comment]
> the step of WO3 + H2 = W + H2O shoudl be difrent
> it should be 2 WO3 + 3 C = 2 hot tungsten ingots + 3 CO2 60 seconds EV
> this way the last step is a EBF and we dont have to reduce the curent smelting time
> this wil also discourage people to use the pure tungsten ores

So basically make tungsten take even longer and also punish people later in the game for unlocking a pure variant? Doesn't seem very wise.

**Comment by botn365** [comment]
im not saying it should take longer just not reduced and you unlock the pure varian t way to fast in like T3 rocket 
and the chemical chain should be superior to pure ore sinse it is more complex actualy pure tungsten should be removed

**Comment by GTNH-Colen** [comment]
> im not saying it should take longer just not reduced and you unlock the pure varian t way to fast in like T3 rocket
> and the chemical chain should be superior to pure ore sinse it is more complex actualy pure tungsten should be removed

I would agree that the pure variant is unlocked too quickly but greatly disagree that there should not be one. Things should be hard in lower tiers then get easier as you unlock higher tier more complex chains later on. Your focus should shift to newer things, just as it does with everything else. The extruder makes parts easier, pure Ti makes it easier than the rutile method etc.

People have been complaining about tungsten smelting times for as long as I can remember, it needs to be reduced.

**Comment by botn365** [comment]
but the chain is going to reduce the smelting times
sure maby later a pure tungsten ore but then just like titanium it should be changed to IV voltage and  same time
if people want to do the easyer rout then they have to pay with more energy

**Comment by botn365** [comment]
also on the titanium example the chemical process takes 40 seconds @ HV while the pure smelting is 90 seconds(nitrogen) @ EV

**Comment by johnch18** [comment]
> @johnch18 can you write down it less vulgar?

No.

**Comment by boubou19** [comment]
@johnch18 this place is friendly so please keep it like that. We are not here to insult each other

**Comment by Shattered2909** [comment]
How about you guys just take my solution?

**Comment by Prometheus0000** [comment]
Bot already did something.
