### ISSUE TITLE
[AE2 terminal] cause spike lag

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6591]
#### Which modpack version are you using?
2.9.0.4qf4
#
#### If in multiplayer; On which server does this happen? 
Eta
### Open wireless terminal causes сlag.
![изображение](https://user-images.githubusercontent.com/47714084/92720288-10610500-f36d-11ea-8e19-0869ae43e0d8.png)
_before_

![изображение](https://user-images.githubusercontent.com/47714084/92720328-1c4cc700-f36d-11ea-8692-b2c038f9d6b0.png)
_after_

![изображение](https://user-images.githubusercontent.com/47714084/92720369-2b337980-f36d-11ea-88c1-fa58d18b4994.png)
_closed_

**Comment by MotiasF33** [comment]
upd
this also happens when you open the standard terminal
![изображение](https://user-images.githubusercontent.com/47714084/92720921-fc69d300-f36d-11ea-8b47-aaa22c74a0d0.png)
![изображение](https://user-images.githubusercontent.com/47714084/92720952-04c20e00-f36e-11ea-9d84-1d71987a61f4.png)
![изображение](https://user-images.githubusercontent.com/47714084/92721000-10add000-f36e-11ea-964f-77f3945805d3.png)

**Comment by repo-alt** [comment]
Maybe it is just UI update packet that takes time, idk

**Comment by MotiasF33** [comment]
> 
> 
> Maybe it is just UI update packet that takes time, idk

Can you do something about it? :o

**Comment by repo-alt** [comment]
Can you test if the lag is smaller if the terminal size is smaller?

**Comment by MotiasF33** [comment]
> 
> 
> Can you test if the lag is smaller if the terminal size is smaller?

small - slightly less lag

**Comment by MotiasF33** [comment]
@repo-alt , network have a less items - no lag 🧑‍⚖️ 
![изображение](https://user-images.githubusercontent.com/47714084/92725480-e3b0eb80-f374-11ea-970e-52e5ca1cc6cc.png)

**Comment by MotiasF33** [comment]
This no lag if i use Arcane terminal
![изображение](https://user-images.githubusercontent.com/47714084/92855319-d0e0fa00-f3fa-11ea-8d69-9538d38dffee.png)

**Comment by repo-alt** [comment]
Well, this is weird, they use the same code to get item list from the server

**Comment by MotiasF33** [comment]
@repo-alt , it seems that they differ only in Inventory Tweaks

**Comment by XenonDB** [comment]
Same problem happend on me. 
Also I found if I stop my hydrochloric acid automation, no lag on both AE terminal or wireless terminal
as well as I continue the automation, lag happen again.

![未命名](https://user-images.githubusercontent.com/58476103/93013900-ea429b80-f5de-11ea-8132-0798fc083722.png)

chlorine, hydrogen and hydrochloric acid are stored in same network, accessed via storage bus.
This network can also be access by main network via storage bus.

**Comment by repo-alt** [comment]
So, you are saying, effectively, that ec2 is to blame

**Comment by repo-alt** [comment]
Although I dont see how, crafting terminal does not collect any fluid information while updating gui

**Comment by XenonDB** [comment]
Yes, but even searching thing that doesn't exist in system doesn't make it better.
Also, quickly outputing fluid via fluid export bus causes lag too.

**Comment by Glease** [comment]
fluid export bus lag is a well known issue and there seems to be no trivial fix. Just avoid using them and use fluid interface instead for the time being.

**Comment by MotiasF33** [comment]
The problem was found *maybe*
`возможно у тебя в ме много вещей с обширной метадатой
гт машинки, зачарованный шмот` 
I remove few staff aka gt machines from network, and lag less
![изображение](https://user-images.githubusercontent.com/47714084/93315529-d0d66500-f813-11ea-8dcc-de9ad5e193fc.png)

**Comment by Prometheus0000** [comment]
So putting gt machines in your network causes lag? Wonderful. Maybe it's caused by disassemly nbt data? Were they handcrafted or made by ae2 autocrafting (no disassembly data)?

**Comment by boubou19** [comment]
while GT machines maybe the most impacting stuff, the issue will rise again if you put heavy nbt tagged items (if it's really that). I did not noticed such lag when opening my gigantic AE, maybe caused by tps or your internet connection, but i maybe wrong. So just in case, try reproducing this in SP to be sure tps/connection are not the cause of it.

**Comment by repo-alt** [comment]
Well, there is unavoidable _client_ lag because client receives a large packet, but some tps hit also takes place, because server has to pack and send that data

**Comment by bartimaeusnek** [comment]
@repo-alt would it be possible for you to outsource the packing and sending of that data to a seperate thread or make it non-blocking in any other manner?

**Comment by repo-alt** [comment]
That may be possible. AE was not designed with parallel execution in mind (like all minecraft), but this is (or at least should be) read only operation.

**Comment by repo-alt** [comment]
(should make a debug command "FillNearestAEWithRandomStuff")

**Comment by MotiasF33** [comment]
"So putting gt machines in your network causes lag? Wonderful"
No..

**Comment by GTNH-Colen** [comment]
> while GT machines maybe the most impacting stuff, the issue will rise again if you put heavy nbt tagged items (if it's really that). I did not noticed such lag when opening my gigantic AE, maybe caused by tps or your internet connection, but i maybe wrong. So just in case, try reproducing this in SP to be sure tps/connection are not the cause of it.

My AE takes a good 2-3 minutes to open for me and I have dozens of GT machines with disassembly data along with compressed chests of items in my AE so wouldn't surprise me if this is the cause.

**Comment by mitchej123** [comment]
There is the "name remover" which you can run them through to remove the disassembly data.

**Comment by Prometheus0000** [comment]
@MotiasF33 That was sarcasm, I don't think it's good at all.

@GTNH-Colen Maybe try removing those and see if there's a difference?

**Comment by boubou19** [comment]
@GTNH-Colen do you talk about the initial opening, or each opening after the initial one?

**Comment by MotiasF33** [comment]
got worse..
![изображение](https://user-images.githubusercontent.com/47714084/94101618-e44b8680-fe38-11ea-9274-2b9810b3e667.png)
while craft terminal open 20 >6 tps
I cleared me of items I didn't use at all, but it doesn't help..

**Comment by alphaNOVAircraft** [comment]
Having the same issue, doubles my ticktime from 25 ms to 50 ms
