### ISSUE TITLE
Hot ingot stack size when output from AE system to compressed chest

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6592]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
prospercraft
#
#### What did you try to do, and what did you expect to happen?
I am using the AE system to grab hot ingots out of the EBF or Volcanus.
The AE then deposits these hot ingots into a compressed chest for further processing.
The ingots the AE deposit in the chest stack as 64 items, but should only be 16 (as far as i know)
![image](https://user-images.githubusercontent.com/3405825/92772501-14f0e200-f39c-11ea-88f6-811f47e3bfd8.png)
As can be seen in this image most ingots are stacked in 64, if i remove a stack, they will stack in 16 in 4 stacks in my inventory, 
if i move them back, they only stack to 16 in the chest as seen in the image.

#### What do you suggest instead/what changes do you propose?
minor bug, so not top priority
Might be good to make sure the AE system (if that is the cause, ebf only outputs with convayer to 16 stack size) stacks the ingots to only 16 if this is intended.

**Comment by MotiasF33** [comment]
@Devtron3D , u use oreDict export bus for transfer it to compressed chest?
Because this is the bus - ignores item limits for all..

**Comment by Prometheus0000** [comment]
Is this an AE bug, AE addon bug, or Avaritia (the chest)?

**Comment by MotiasF33** [comment]
> 
> 
> Is this an AE bug, AE addon bug, or Avaritia (the chest)?

if Devtron3d use a oreDict bus this EC2 bug

**Comment by Prometheus0000** [comment]
Which is why I need them to respond, otherwise we can only guess.

**Comment by GTNH-Afx237v7** [comment]
Can confirm, it’s the ore dictionary export bus thus EC2.

**Comment by Prometheus0000** [comment]
At least it's not duplicating things this time, *sigh*.

**Comment by Devtron3D** [comment]
It is the ore dictionary export bus, changing to a vanilla chest still caused this issue.

**Comment by GTNH-Afx237v7** [comment]
Since the recipe of the ore dictionary export bus will be deactivated next release and succeeded by the oredictionnary filter card, I assume this can be considered fixedindev?

**Comment by Prometheus0000** [comment]
I guess so.
