### ISSUE TITLE
Make endgame ore processing simpler [RFC]

### ISSUE THREAD

**Issue by GreyWolf4389** [GTNewHorizons/GT-New-Horizons-Modpack#6593]
#### Which modpack version are you using?
2.0.9.0

Basically, if you want to process ore for singularities efficiently, you need to macerate --> forge hammer --> wash --> smelt --> compress, which requires five machines. We should add a new multi-block, available only ZPM+ that cuts out the first three to four machines, greatly simplifying many late game ore setups.

Essentially, we should add a multiblock that turns one ore into two dust/ingots, but doesn't yield byproducts.

**Comment by yukieiji** [comment]
Why not use the OreDrill and the ChemicalReactor? By doing so, you can easily get 8 or more ingots from 1 ore.
I don't think it's necessary because there are other means of obtaining ingots besides ore.

**Comment by Houstonruss** [comment]
If you're that far in the game, it's worth just hammering and smelting. Any extra steps are your doing.
