### ISSUE TITLE
[Suggestion] A few mod additions

### ISSUE THREAD

**Issue by mxnmnm** [GTNewHorizons/GT-New-Horizons-Modpack#6596]
You should add these because they're fun/cool and they don't add anything that would require too much work to edit/fit into progression

https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1294960-tomahawks-1-5-4-0-throwing-axes-updated-2015-07-13

https://www.curseforge.com/minecraft/mc-mods/colorful-mobs

**Comment by MotiasF33** [comment]
@mxnmnm ,Would you at least explain.. why this should be added?

**Comment by mxnmnm** [comment]
Tomahawks adds another use for axes/frying pans and makes for a very nice early game alternative to a bow. Also who doesn't wanna throw their axes/frying pans around?

Colorful mobs is fun to use on players (randomly dying your friends and waiting for them to notice is very entertaining lol) and randomly dying your pets adds a bit more personality to them. Just generally small and fun.

**Comment by NoX-programer** [comment]
The modpack is huge enough already, starting long enounh, and, IMHO, suggested mods is not that useful and interesting. BTW, axes, frying pans and other tools are added already by Tinker's Construct.
