### ISSUE TITLE
[Recipe] Block of Solid Ender only way for craft

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6597]
#### Which modpack version are you using?
2.0.9.0qf4

### Block of solid Ender have at one recipe for craft - Tinkers Casting Basin
![изображение](https://user-images.githubusercontent.com/47714084/92837604-7473df80-f3e6-11ea-9e58-05187d7baea6.png)

### This pain to create the Singularity
![изображение](https://user-images.githubusercontent.com/47714084/92837673-8d7c9080-f3e6-11ea-9a9d-269ea1e3e33c.png)
_Add recipe to fluid solidifier_  🥺

**Comment by Prometheus0000** [comment]
Duplicate, see #6177.
