### ISSUE TITLE
[Malisis' Door] You can walk though big doors like they aren't even there.

### ISSUE THREAD

**Issue by wllp** [GTNewHorizons/GT-New-Horizons-Modpack#6598]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Single Player
#
#### What did you try to do, and what did you expect to happen?
Tired to open a "carriage door" but the hit box seems to be way off.
#
#### What happened instead? (Attach screenshots if needed)
I eventually figure it out by clicking on the corner of the door but as I was doing that I found I could just walk though a "closed" door.
#
#### What do you suggest instead/what changes do you propose?
I would like it if these doors worked again. :) I have gone into peacful mode since with the way things are now a creeper can just waltz into my previously (mostly) secure fort.

**Comment by Prometheus0000** [comment]
Did they work in a previous version? If not, consider using another type of door.

**Comment by Prometheus0000** [comment]
Related: #6543? Try a different version.

**Comment by wllp** [comment]
I bet they are it did work in the 2.0.8.8 version of the pack.

**Comment by Dream-Master** [comment]
We dont change anything on the mod Malis Doors. The version not updated for ages.

**Comment by wllp** [comment]
True, witch leads me to suspect it is same issue from #6543 or related some how. That would make sense as the doors "work" its just their hit boxes that are screwed up now witch might be a part of the MalisisCore14.3 mod issues.

**Comment by wllp** [comment]
This still was a bug as of a month ago.

**Comment by chochem** [comment]
already discussed on github but for clarity here as well: we dont have a dev working on that mod so this is just permanently stale. Feel free to try to fix it yourself though, but otherwise this is probably gonna stay closed. :)

**Comment by YannickMG** [comment]
Don't we have a repository with a fork? Why couldn't we fix this?

**Comment by mitchej123** [comment]
> Don't we have a repository with a fork? Why couldn't we fix this?

It's a matter of finding someone who is willing and able to fix it.  Yes we have a fork.  There's also a ray tracing lag issue that might be good to tackle together with this, as I believe the ray tracing is specifically for the larger doors.
