### ISSUE TITLE
VoidMiner setting up in DeepDark mines Null ore

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6601]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
VoidMiner setting up in DeepDark 
#
#### What happened instead? (Attach screenshots if needed)
It mines Null ore.
![2020-09-12_14 40 05](https://user-images.githubusercontent.com/40425798/92988521-30c4c700-f507-11ea-8de2-c02103a17206.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it

**Comment by Prometheus0000** [comment]
I couldn't find another ticket for it, but bart already knew about this awhile ago, so it's unknown whether he'll try to fix it.

**Comment by Prometheus0000** [comment]
Realated: #6560.
