### ISSUE TITLE
No mentions of alpha centuri needing spacesuit .

### ISSUE THREAD

**Issue by DuskNite** [GTNewHorizons/GT-New-Horizons-Modpack#6603]
#### Which modpack version are you using?
2.0.9.0

#
#### What did you try to do, and what did you expect to happen?
Go to alpha centuri, mine copper, solar for days.

#
#### What happened instead? (Attach screenshots if needed)
Died. 

#
#### What do you suggest instead/what changes do you propose?
![image](https://user-images.githubusercontent.com/19917651/92995934-561ef880-f53a-11ea-9775-e24e7c5b2f9e.png)
Add a mention here. Preferably bolded. And with large letters. 

Edit: 
![unknown](https://user-images.githubusercontent.com/19917651/93008353-489f5800-f5a6-11ea-86f5-17753d17575c.png)
![unknown (1)](https://user-images.githubusercontent.com/19917651/93008355-4ccb7580-f5a6-11ea-82e2-35edb559e43e.png)
Also add this quest to tips & hints tab

**Comment by Prometheus0000** [comment]
There's another quest that lists all the planets and what you need for them (thermal/thermal2/spacesuit).

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/93010405-241d8e80-f55a-11ea-8097-f1df29ba6dba.png)
