### ISSUE TITLE
Unfired Coke Oven Bricks Won't Accept Red Sand in Recipe

### ISSUE THREAD

**Issue by KingSt4o** [GTNewHorizons/GT-New-Horizons-Modpack#6623]
#### The Recommended (Newest Update) on the Technic Launcher

#
#### Single Player 

#
#### The Stone Age quest that has you collect sand two stacks of sand before making the coke oven. It allows you to collect red sand as well as regular sand. But unfired coke oven bricks can't be crafted with red sand.

#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by Prometheus0000** [comment]
It's not the quest preventing it, it's that the unfired bricks recipe isn't oredicted for both types of sand. The other quest that has you collecting sand _is_ oredicted, but this can be removed. I dunno how to oredict the bricks recipe though, but that would be the better solution. I found the recipe here: https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/699017734bcd471a4017a21a3825d509dd68f8aa/src/main/java/com/dreammaster/gthandler/GT_CraftingRecipeLoader.java#L217, but good luck figuring that out.

**Comment by Dream-Master** [comment]
We could oredict it.

**Comment by shawnbyday** [comment]
Is it hard coded or is it just a zs script change?

**Comment by Prometheus0000** [comment]
See my comment.
