### ISSUE TITLE
Kekztech reinforced void jars bug

### ISSUE THREAD

**Issue by Rakdarian** [GTNewHorizons/GT-New-Horizons-Modpack#6624]
#### Which modpack version are you using?
release
#
#### If in multiplayer; On which server does this happen? 
Boys gregified
#
#### What did you try to do, and what did you expect to happen?
store large amounts of essentia in these jars and label them. I expected them to hold 256 essentia and remain labled
#
#### What happened instead? (Attach screenshots if needed)
After a random amount of time the jars reset, losing their label and all essentia inside
#
#### What do you suggest instead/what changes do you propose?
fix the bug that causes them to lose the label and the essentia

**Comment by Dream-Master** [comment]
After Kekz repo went private we need to fix things on us own I guess.
