### ISSUE TITLE
Storage Drawers size upgrades have no recipe

### ISSUE THREAD

**Issue by AbrasiveElk** [GTNewHorizons/GT-New-Horizons-Modpack#6625]
#### Which modpack version are you using?
2.0.9
#
#### What did you try to do, and what did you expect to happen?
tried crafting the Storage Drawers size upgrades
#
#### What happened instead? (Attach screenshots if needed)
clicking on the size upgrades of Storage Drawers in NEI shows no recipe
#
#### What do you suggest instead/what changes do you propose?
make them craftable

**Comment by yukieiji** [comment]
There are recipes for all the upgrades(Storage UpgradeⅡ~Ⅵ) in ver2.0.9.0QF4.
Have you updated to QF4?

**Comment by AbrasiveElk** [comment]
> There are recipes for all the upgrades(Storage UpgradeⅡ~Ⅵ) in ver2.0.9.0QF4.
> Have you updated to QF4?

I just did and still can't see them in NEI

**Comment by boubou19** [comment]
make sure to correctly update you minetweaker scripts
