### ISSUE TITLE
PBI is too high tier plastic for Voidmetal fortress/Voidwalker boots

### ISSUE THREAD

**Issue by Rakdarian** [GTNewHorizons/GT-New-Horizons-Modpack#6628]
Voidmetal fortress armor Voidwalker boots is a malefica fortress armor gated behind quite a bit of warp(eldritch revelation), MV metals, Shadowmetal, Polybenzimidopole, and infusion. The costs to benefits for this are significantly too high to justify the Late EV early IV plastic, especially in comparison to similar on tier or even later tier armor. 

Shadow fortress armor deserves the plastic requirement, it already requires infused gold(a tier 4 planet metal) and it makes you effectively immortal. There's not much to argue there. 

Defensively there are a few sets of armor that outperform in a bunch of scenarios voidmetal fortress. Dreammaster armor is trivial to repair(Dragon essence, Thaumic Restorer, Repair enchant, Void putty) and offers superior protection. Voidmetal offers a vis discount, but Dreammaster gear is HV tier rather then the IV tier that PBI requires. Another set of gear that outperforms it defensively is Nano gear, which even offers hazmat protection, and is also only gated at HV. A set of armor that is supposedly on the same tier as it, Quantum armor, is effectively strictly better and even offers the ability to upgrade into a fly suit a trait that is shared with its nano cousin. 

Boots of the voidwalker are hilariously overcosted. IV tier set of boots for what amounts to Dreammaster boots with haste 6. The mobility on these, even with accompanying belt offers slower mobility then the boots of the meteor, something that is only gated by villager trading and firestone. A recipe that can trivially be done at LV. There is literally no reason for it to be as expensive as it is for what it provides.  One caveat, assuming the GTNH spreadsheet is correct theres an invisible 5% vis discount on the boots. Which is something that is only beaten by infinity boots, Horizontal Shield boots, and primodial boots. And is matched by quantum boots of the traveler and ichorcloth boots. But after testing it it doesnt appear to be there.

**Comment by Prometheus0000** [comment]
Are you sure the discount isn't there? I went and checked previously and it was?

Also, keep in mind it can be enchanted unlike nano/quantum.

**Comment by Rakdarian** [comment]
Its not on the tooltip, and wearing it and not wearing them doesnt change the visible vis discount. Either its not there or it doesnt exist. 

Nano and Quantum cant be enchanted, but generally speaking enchantments dont do anything. By the time you get any of the above the defensive enchantments are redundant, They dont help against bosses that actually matter since those bosses hit hard enough that ProtV or VI doesnt do anything. And against regular mobs they cant hurt you anyways. Dreammaster armour can also be enchanted, the overchanting table even allows you to do it without removing the existing enchants and upgrade them

**Comment by MotiasF33** [comment]
mm
Suppose change PBI to Epoxid.
It also requires advanced chemistry, but reduces required tier

**Comment by Rakdarian** [comment]
It used to be ptfe. It didn't deserve the nerf in the first place

**Comment by bedrill64** [comment]
Reminder, please buff the void fortress for the next patch.

**Comment by Prometheus0000** [comment]
@ScriptedPiky You're the one that wanted PBI in this stuff in #5928. You explain.

**Comment by Rakdarian** [comment]
Replace the PBI plates with PTFE plates on the Boots of the voidwalker, Void fortress helm/chest/boots, and voidwalker sash if they have them
