### ISSUE TITLE
Server crash, with a few internal error on client, and item duplication.

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6631]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Automating my Assembly line with open computers
I was putting an adapter block form open computers under my assembly line when i found this bug

![image](https://user-images.githubusercontent.com/3405825/93258701-03924600-f79f-11ea-889c-179381d661fe.png)

As seen on this image, to reproduce it do as following
Active adapter block on the bottom powered on, 
Middle add an AE smart cable that is active connection to an me controller block
Top add a hatch with the input port pointing down (this was an UV input hatch)

Here comes the fun part, on the top of the ME cable add a storage bus on the input side of the input hatch.
This should immediately cause an internal error and the server will kick you. (or server crash)

When reconnecting, if you place an item on the ground near or around the area (I think the chunk gets corrupted), it will cause another internal error or a server crash (managed to crash prospercraft a few times identifying this bug)

Now removing it is the fun part, you can break all the blocks around it (not the storage bus), and they will for the most part pop back and you can rebreak them.

If when the bug is in effect, and you reloged after placing the storage bus, try breaking a block next to the power adapter and placing down say a vanilla chest, that will cause kick or server crash also

Now, this might require a relog, but when breaking the storage bus with all items, they should stop popping back, place an item like a vanilla chest on the ground and items spawn that you broke, including duplicated for each time you broke an item that did not appear. 
I managed to stop the items from popping back (few times, and did a relog the final time before i placed an item the final time to fix the area and make the broken items reappear.

I do not know if other ME items like an interface or import/export bus will cause the same issue, had to restart my client a few time locating this bug as it seamed to cause issues with it.

**Comment by repo-alt** [comment]
Crash log?

**Comment by Devtron3D** [comment]
[c941dce2.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5228121/c941dce2.txt)
[851514e0.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5228122/851514e0.txt)

**Comment by repo-alt** [comment]
Ah, f*kn EC2 bug, it crashes your system even if you don't use it

**Comment by repo-alt** [comment]
Already saw that

**Comment by Devtron3D** [comment]
@repo-alt 
Strange enough, if you add the storage bus direct on the adapter block, nothing happens, it had to be this setup, as shown in the image.

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/ExtraCells2/commit/44cddc17124f90daf7cbf81f89d41783f4b01ef3

**Comment by repo-alt** [comment]
Some guy in the russian channel reported that a month ago
