### ISSUE TITLE
Fine cosmic neutronium wire recipe seems wrong

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6633]
#### Which modpack version are you using?
GTNH2.0.9.0QF4
#

one ingot should be 8 fine wires and not 4

![image](https://user-images.githubusercontent.com/57050655/93273505-4a406a00-f7b8-11ea-9b18-ca5b4ef5f095.png)

**Comment by Prometheus0000** [comment]
Borosilicate is the same isn't it?

**Comment by GeicowithaBango** [comment]
Not every ingot returns 8fine wires. I always thought this was intentional

**Comment by Prometheus0000** [comment]
#4472

**Comment by Dream-Master** [comment]
Not every material give the same output and this isnt a bug.

**Comment by botn365** [comment]
it should be giving 8 like all other fine wires for motors
there is no reason why materials that dont have a wire will only give 4 fine wire per ingot while materials that do have a wire give 8 fine wire

**Comment by Prometheus0000** [comment]
@botn365 I can't find anything other than the ProcessingFineWire class that might create SpNt fine wires, but I don't care enough to try to figure it out. If you want to go at it fine, otherwise this should be closed.
