### ISSUE TITLE
[Suggestion] Naquadah Rework/Nerf

### ISSUE THREAD

**Issue by Shattered2909** [GTNewHorizons/GT-New-Horizons-Modpack#6635]
What about this?

![Naquadah_process_3](https://user-images.githubusercontent.com/35029480/93374379-e9b43a00-f856-11ea-8bcc-e6ae636ecbea.png)

**Comment by yukieiji** [comment]
I can understand if you want to rework Naquadria, which is used for parts(after UV), singularity, batteries, and power generation, but is it worth reworking Naquadah, which is mainly only used for cables and alloys, to increase the load on the server?

**Comment by leagris** [comment]
Adding the Nerf keyword is not a free pass for changes acceptance and I am absolutely sick of the nerf fest in GTNH to the point I have not played since 6 months.

**Comment by Shattered2909** [comment]
Hmm there is one thing I forgot. This change would also include new Naquadah Fuels that are much better, let me get the recipes/stats!

**Comment by Prometheus0000** [comment]
Could you please keep in mind that Nq is _required_ for progression (wafers), and that you are once again suggesting a huge nerf before platinum.

**Comment by Shattered2909** [comment]
This not before Platinum.

**Comment by Shattered2909** [comment]
![naquadah](https://user-images.githubusercontent.com/35029480/93380627-c2159f80-f85f-11ea-9ef2-f3ae4f5a446c.png)

Okay so here is the processing line for turning the Dusts into Resources.

**Comment by Prometheus0000** [comment]
I'm not 100% sure when you actually _need_ the Nq wafers admittedly. I definitely made them before setting up the platinum series (the whole thing) though.

**Comment by Shattered2909** [comment]
in Gas Turbine:
1mb Naquadah Gas: 768000 EU
1mb Light Naquadah Fuel: 320000 EU
1mb Light Enriched Naquadah Fuel: 800000

in Naq Reactor:
1mb Medium Naquadah Fuel: 640000
Enriched: 1280000
1m Heavy Naquadah Fuel: 1280000
Enriched: 1920000

Hyper Fuel 1: 3276800 EU
200mb Naquadria Solution + 300mb Light Enriched Naq Fuel + 500mb Light Naq Fuel + 144mb plutonium244 = 2000mb Hyper Fuel 1

Hyper Fuel 2: 4915200 EU
250mb Naquadria Solution + 350mb Medium Enriched Naq Fuel + 400mb Medium Naq Fuel + 144mb curium250 = 2000mb Hyper Fuel 2

Hyper Fuel 3: 6553600 EU
300mb Naquadria Solution + 400mb Heavy Enriched Naq Fuel + 300mb Heavy Naq Fuel + 144mb californium256 = 2000mb Hyper Fuel 3

**Comment by Shattered2909** [comment]
This rework will make Naquadah as complicated as it should be, also non-enriched Naquadah is actually useful instead of Clutter.
This makes Naquadah Reactors powerful and adds a little bit of help to Gas Turbines as well.

**Comment by yukieiji** [comment]
Which tiers are these treatments targeting? IV tiers are too fuel efficient, but we'll need a nacquada in IV(on quest).
@Prometheus0000  Nq wafer is required in the IV tier on the quest. But it's not required, although cost reduction.

**Comment by Shattered2909** [comment]
Well processing itself is possible at late IV, the Hyper Fuels require materials from Fusion.

**Comment by GTNH-Colen** [comment]
This has clearly had a lot of work put into it, I believe impact uses this right?

**Comment by Prometheus0000** [comment]
BTW, your charts are opposite each other, unless you suggest people go through _both_. The first ends with dusts, and the second practically starts with them.

**Comment by Shattered2909** [comment]
Yeah it is from Impact, also used in Gregicality.

And yes, the first is for processing Ore, the second is for turning Dust into the Fuels. So you only have to do the first for Naquadah Wafers.

**Comment by Prometheus0000** [comment]
BTW you didn't explain how to get all the stuff, like Naquadric compound. And you need to use all 3 at once? IF not, you should use different boxes for the machines. Like when it goes to the ebf in the upper right, do you put all 3 difluorides in at once? Because that's what your chart says.

**Comment by Shattered2909** [comment]
Naquadric Compound replaces Naquadah Ore.

**Comment by Prometheus0000** [comment]
So it's just a rename? Well what about _all the other ones_, like fluoroantimonic acid? What do we do with indium trifluoride? And all the other ones that are used or are byproducts. How much materials do they use? Or produce? What machine? How long? How much power? Are you even sure this is power positive? Is there really a realistic way to get a bunch of xenon that is not replicating it? And what's a heavy metal cyclone? Etc.

**Comment by yukieiji** [comment]
Large Naquada Reactor will be added in GT++, and given the fuel value of Hyper Fuel, I think if we agree this fuel, we need to rethink the entire generator after LuV....

**Comment by Shattered2909** [comment]
Fluoroantimonic Acid is made from Fluorine and Antimony (there are a few steps)
Indium Trifluoride can be turned back into Indium. Mostly EBF/Chemical Reactor recipes with IV voltage requirements.

It is extremely power positive, the fuel values are for 1mb. No idea about Xenon right now, this might need some changes.
Heavy Metal Cyclone is just a large Centrifuge.

Fuck GT++

**Comment by Prometheus0000** [comment]
When I say all of them, I mean please list the complete details for _every single one_. How would it be implemented if we don't know? We could decide to make them al 0.001 seconds, or 3hrs. Or ULV voltage or UHV. And of course the materials. You're the one suggesting it, so you need to go through the effort. If it's already in impact, you just need to copy it out, right?

**Comment by Shattered2909** [comment]
Okay fine, I will do that tomorrow.

**Comment by Houstonruss** [comment]
So long as this gets you naq faster and cheaper long run this is good, but yall can't forget how changing something like this causes dramatic effects later in the game with the exponential amount of resources needed every time you tier up.

**Comment by Shattered2909** [comment]
Faster and cheaper? Absolutely not. But definitely way more rewarding.

**Comment by GeicowithaBango** [comment]
how do the hyper fuels work?

**Comment by Shattered2909** [comment]
Liquid Fuel in Naquadah Reactors.

**Comment by GeicowithaBango** [comment]
And what about the enriched naquadah/ naquadria

**Comment by Shattered2909** [comment]
Liquid Enriched Naquadah should not be a valid Fuel anymore, the Fuel products made  from it replace it.

**Comment by leagris** [comment]
I am sure those having setup Naquadah reactors and having to redo the fuel processing so many times because fuelling and working has been redone so many times. Will be happy to once again entirely redo their Naquadah fuelling.

For the story:
- It started as canned Nq+ dust
- then it was changed to give Nq dust by-product
- then it was changed to molten Nq+
- then it was changed to molten Naquadria
- ...
- And you want to change it once more.

Yeah! Really! Those having spent time to layout the process and have their base setup and forget with Nq reactors, all te logistic setup and forget and busy with other stuffs… You believe that, they will accept it without protest or consequence?

**Comment by leagris** [comment]
My purpose is:
If you make new fuels, keep the old Nq reactors as-is. Then add your new special reactors/generators to use the new improved fuel, or keep the old fuel and working as-is alongside the new fuel in existing reactors. So players are free to upgrade to the new fuel or keep with their legacy Nq fuel processing still working as planned.

**Comment by Shattered2909** [comment]
Yes, I want to change it once more because this idea is actually good.
Reactors that just run off Molten Metal are bad design, especially for something at IV and higher tiers this is ridiculously simple, also not even that good, I don't know anyone that even uses Naquadah Power. We don't necessarily need new Reactors, the Singleblocks are fine although I would definitely like to see a Multiblock. We just need to change what Liquid the Reactors take.

**Comment by botn365** [comment]
this line is way to big for just naquadah
its almost the samme size as the entire platline wich gives platinum,palladium,osmium,iridium,ruthenium and rhodium
while here its just naquadah and also
radontrioxode what?! a nobel gas with oxygen

**Comment by leagris** [comment]
I have used these within another GT5 mod-pack and it took quite some significant effort into breeding Nq bees, setting-up EV centrifuges packages and return path to feed Nq reactor Mk3. I would have been really pissed if on a pack update, all of a sudden, my energy source collapsed and I had to rework all the Nq fuel processing and recycling.

Please keep the current Nq fuels unchanged but add your improved fuels and chemistry as an incremental upgrade, to get more fuel, more mower from same quantity of base Nq.

As for the molten metal thingy, I see nothing wrong with it. Nq is a fantasy material. It does not have to obey real-world chemistry, it can be whatever since it has no real existence.

**Comment by Shattered2909** [comment]
Look, I just took this from Gregicality which also took things from Bartworks, we can always debate/change specifics, that is not the problem. I don't think it is too big, considering how powerful reworked Naquadah is, this is similar to Fusion in power.

Current Naq Fuel is only the Enriched Naquadah in Naquadah Reactor which is pretty terrible, even more so if you have to centrifuge the Dust first. I don't mind if it stays, would just be more consistent to replace.

What I absolutely do mind though, is that Naquadah is just found as a pure Ore, it was a problem with Iridium/Osmium before. Later resources should not be less complex than something like Titanium, but more so.

**Comment by 4gname** [comment]
> ![naquadah](https://user-images.githubusercontent.com/35029480/93380627-c2159f80-f85f-11ea-9ef2-f3ae4f5a446c.png)
> 
> Okay so here is the processing line for turning the Dusts into Resources.

Its my work with @Spartak1997 

1) Liquid Naquadah Generator
2) Liquid Enriched Naquadah Generator
3) Hyper Generator
![](https://cdn.discordapp.com/attachments/660746905692930091/746798815654314014/unknown.png)
![](https://cdn.discordapp.com/attachments/660184245695676416/746816006449528882/unknown.png)
![](https://cdn.discordapp.com/attachments/660746905692930091/734702133374615562/unknown.png)
4) Heavy Metal Cyclone
![](https://cdn.discordapp.com/attachments/660746905692930091/741726831006187520/unknown.png)
![](https://cdn.discordapp.com/attachments/660184245695676416/747001422180253756/unknown.png)

**Comment by Shattered2909** [comment]
Pretty epic, I just took the ideas from Gregicality which are based on yours.

**Comment by Dream-Master** [comment]
@GlodBlock maybe not doing a copy paste but maybe with the new mod good geerator we can just a bit an the Nqaudah Line

**Comment by Glease** [comment]
Chemical reactor everything. 10 out of 14 total processing step is chemical reactor. So instead of blue cube spam now we want grey cube spam?

The original proposal is honestly not very interesting to say the least. What about something actually interesting with a distinct mechanism, like bio vat?

**Comment by Dream-Master** [comment]
sure we should use a different way then Impact. We are not a Impact Clone :)
