### ISSUE TITLE
Fix Enderio's capacitor efficiency

### ISSUE THREAD

**Issue by truecyt** [GTNewHorizons/GT-New-Horizons-Modpack#6641]
#### Which modpack version are you using?
2.0.9.0qf4
#### What did you try to do, and what did you expect to happen?
Enderio's capacitor cannot get right efficiency
#### What happened instead? (Attach screenshots if needed)
**octadic capacitor:**
![P$4YUC6T}%K2LP6G4NTSWS8](https://user-images.githubusercontent.com/58604873/93423645-09943e00-f8e9-11ea-9590-dfff95494729.png)
**stellar capacitor:**
![{XGUJI6MYP~` 6D1$)0$}N](https://user-images.githubusercontent.com/58604873/93423758-46603500-f8e9-11ea-9e41-d5ace0173e43.png)
**totemic capacitor with enchanted efficiency V:**
![SN81DH8{$G{I78T(MUHKCKA](https://user-images.githubusercontent.com/58604873/93423849-760f3d00-f8e9-11ea-8050-7f36db1b0ec9.png)
#### What do you suggest instead/what changes do you propose?
Fix Enderio's capacitor efficiency in next stable version

**Comment by Prometheus0000** [comment]
Duplicate: #6573.
