### ISSUE TITLE
Pam's Gardens not suppressing item behavior when right-clicking them

### ISSUE THREAD

**Issue by PaulVisschers** [GTNewHorizons/GT-New-Horizons-Modpack#6642]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
-
#
#### What did you try to do, and what did you expect to happen?
Right-click a Pam's Harvestcraft garden to harvest it, with a placeable block or some other item that has functionality on right-click. You'd expect the garden to be harvested and that being the only thing that happens.
#
#### What happened instead? (Attach screenshots if needed)
Instead it harvest the garden but then also does whatever right-click behavior your item has. So for blocks it places it down, plants will be planted, swords will block etc.
#
#### What do you suggest instead/what changes do you propose?
Have it be like right-clicking any other plant, in that it harvests the garden and suppresses the default right-click behavior of whatever you're holding.

**Comment by rabitibike112** [comment]
This issue is indeed rather annoying. It would be great if fixed
