### ISSUE TITLE
Add confirmation window to 'Claim All' button in quest window

### ISSUE THREAD

**Issue by PaulVisschers** [GTNewHorizons/GT-New-Horizons-Modpack#6643]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
-
#
#### What did you try to do, and what did you expect to happen?
I tried to go to another tab in the quest book but I accidentally clicked the 'claim all' button instead. I would've liked to have not clicked that, but in lieu of that a confirmation window would've been nice so I could cancel out of it.
#
#### What happened instead? (Attach screenshots if needed)
I got a bunch of items in my inventory when I wasn't ready for them.
#
#### What do you suggest instead/what changes do you propose?
Add a confirmation window that asks if you really want to claim all those rewards.

**Comment by SKProCH** [comment]
Done
