### ISSUE TITLE
Gadomancy Aura Pylon can cause CTD

### ISSUE THREAD

**Issue by Hiranus** [GTNewHorizons/GT-New-Horizons-Modpack#6644]
#### Which modpack version are you using?
2.0.9.0

#### What did you try to do, and what did you expect to happen?
Use multiple Aura Pylons in the same area to boost plant growth.
#
#### What happened instead? (Attach screenshots if needed)
Crash to desktop.
https://pastebin.com/s468yR6P

#
#### What do you suggest instead/what changes do you propose?
Since this modpack has forked Gadomancy you can change this linked list to something thread safe. 
And while you are at it, please add inventory slot to that machine so that it would be impossible to accidentally pick up crystallized essentia.

**Comment by shawnbyday** [comment]
@Hiranus do you have a copy of the full crash log or can you reproduce crash so you can post one? Just want to make sure we have enough information available for someone that can fix this issue.

**Comment by Hiranus** [comment]
@shawnbyday Its super easy to reproduce, just place few aura pylons in close proximity, turn all of them on, supply essentia, look at them and go make yourself a tea. When you will be back your game will be crashed. There is nothing more related in the log. Fixing this one means just changing list to something that is thread safe.

**Comment by yukieiji** [comment]
I'm using a plant farm with aura pylon and it causes tremendous TPS lag....
Could this crash be due to TPS lag?

**Comment by Hiranus** [comment]
@yukieiji You have 1 aura pylon right? Then its just issue of aura pylon like mad checking every possible plant location very often. This is separate issue and can be fixed by queuing those checks and doing only 1/few every tick. This will force machine to "discover" plants slower, but after discovering it should work exactly the same.

This crash however is strictly client-side and caused by code responsible for pretty particles being not thread-friendly. It will happen if you place >=2 aura pylons close together, so that game will have to render them at the same time. While 2 aura pylons are somewhat unlikely to cause it, with 5 aura pylons you will crash in less than 2 min.
