### ISSUE TITLE
GT advanced miner can cause lags when mining

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6645]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### 
Was trying to understand the lags from Eta, found this:
![image](https://user-images.githubusercontent.com/12850933/93516998-1e91c100-f92b-11ea-8b5a-5ff5d649e518.png)

The tricorder record is from a GT advanced miner

**Comment by repo-alt** [comment]
Single block miner code is a bit stupid. In worst case it may test 2500 blocks per tick. Ore drill at least does not check one block more than once.

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/344
