### ISSUE TITLE
Broken Rocket Progression

### ISSUE THREAD

**Issue by Houstonruss** [GTNewHorizons/GT-New-Horizons-Modpack#6646]
#### Which modpack version are you using?
**2.0.9.1dev**
#
#### If in multiplayer; On which server does this happen? 
ssp
#
#### What did you try to do, and what did you expect to happen?
Schematic recipes require over-tiered printers which can't be crafted in the same tier (and you can't get uev stuff before t8 rocket)

#
#### What do you suggest instead/what changes do you propose?
Just use any printer for every schematic. Having voltage tiers and yet another single-use machine to progress is getting old.
While we're at it, don't require the schematic to be "printed" on a giant chunk of metal instead of a piece of paper. A laser engrave would make more sense.

If this is a ++ problem, then kill ++.

**Comment by Prometheus0000** [comment]
Very Important: **2.0.9.1dev**

So there's a new mechanic related to the rocket schematics that is broken? I dunno what they're being printed on or what it is exactly, maybe you could add some pictures to show your point so I don't have to DL and run the very WIP new build?

**Comment by glowredman** [comment]
Previously I did the voltages of the machines according to the previous recipes. These voltages seemed odd to me, so I made the tiering according to the [GTNH spreadsheet](https://docs.google.com/spreadsheets/d/1Rsz0rH9tIVJxr18b1Z6-QxOSaEKssxF7u2naQTq2Mqg/edit#gid=1677292418).
I've never made it to the rockets myself, so feedback on the tiering is crucial for me (either here or on Discord).

The schematics can be found in the boss dungeons (like before). Previously you needed to scan these schematics to get the Data Sticks, thus the schematics were consumed. You need the schematics to unlock the recipes in the NASA workbench though. For this reason I made the printer recipes, so older players don't need to fight the boss a second time.
I understand, that you shouldn't have to make a better printer for each tier though and that paper as the input is sufficient and will change that accordingly.

**Comment by Prometheus0000** [comment]
If you mean 
![image](https://user-images.githubusercontent.com/8517039/93640718-096b6f80-f9c9-11ea-97df-999036fc03ae.png)
that isn't necessarily 100% accurate.

**Comment by glowredman** [comment]
At which voltagetiers re the rockets typically available then?

**Comment by Prometheus0000** [comment]
I only got the T3 one, you'll need to ask someone else.

**Comment by Houstonruss** [comment]
What's stopping us from just unlocking the nasa workbench tabs with the current circuits?

**Comment by glowredman** [comment]
You'd need the schematics anyway and all players who know GalactiCraft/GalaxySpace expect it to need the schematic. It would be complicated at some point however I make it.
