### ISSUE TITLE
Void miner does not produce ore, after wipe DD

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6647]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
Eta
### Void miner does not produce ore after wipe DD
![изображение](https://user-images.githubusercontent.com/47714084/93529375-7a1c7880-f944-11ea-80bd-cdd2d76f1629.png)

**Comment by Prometheus0000** [comment]
@bartimaeusnek

**Comment by MotiasF33** [comment]
Relax. excuse me
It mininig but u need to lower mining pipes to 0 height
![изображение](https://user-images.githubusercontent.com/47714084/93530263-f4013180-f945-11ea-914a-28cd7b00eb50.png)
