### ISSUE TITLE
[Suggestion] nano circuit have a incorrect amount of liquid in the recipe

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6649]
#### Which modpack version are you using?
2.0.9.0qf4
#
### nano circuit have a incorrect amount of soldering = 3760mb
All previous recipes were divided either by 250 or by 144
![изображение](https://user-images.githubusercontent.com/47714084/93557733-6abd1f80-f984-11ea-8f9c-82dc21e98d95.png)
### Change to 3744mb or 5760mb

**Comment by Dream-Master** [comment]
sure

**Comment by Prometheus0000** [comment]
https://github.com/Technus/TecTech/commit/474c28ca31043f9b1861e149e79bb540b81f08f5 Please make a note here (or there) when you fix something @MotiasF33 , otherwise we won't know it's fixed.
