### ISSUE TITLE
Bugtorch isnt compatible with Essential

### ISSUE THREAD

**Issue by wohaopa** [GTNewHorizons/GT-New-Horizons-Modpack#6650]
#### Which modpack version are you using?
2.0.9.0 server core is thermos
#
#### If in multiplayer; On which server does this happen? 
my server
#
#### What did you try to do, and what did you expect to happen?
ender command as /list /ess /tps
#
#### What happened instead? (Attach screenshots if needed)
it doesnt show what I expected
enter /list it isnt esss
enter /ess no such command
but removed bugtorch it is ok
i dont want to remove it
#
#### What do you suggest instead/what changes do you propose?
tall me the solution update it or change config

**Comment by boubou19** [comment]
simply disable the server patches one by one in the cfg until it works, then post the working cfg here pls

**Comment by wohaopa** [comment]
just after the test, only BugTorch and Essential are OK.so I suspect it is the other mods problem

**Comment by yukieiji** [comment]
Does this issue occur if you set `B:skipInitialWorldChunkLoad` to `false` in `mixins.cfg` to False?

**Comment by wohaopa** [comment]
> Does this issue occur if you set `B:skipInitialWorldChunkLoad` to `false` in `mixins.cfg` to False?
this method is effective and practical..thanks
