### ISSUE TITLE
Compressed air -> liquid air -> distillation by products ( the small cell issue)

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6652]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
prospercraft
#
#### What did you try to do, and what did you expect to happen?
I have been generating a lot of argon, using a compressor->freeser->distilation, all in the big multi blocks

The problem is, i can only get the recipe to work with 144 cells, and considering i am making a lot of those when powering the Machines with LuV power, this moving cells around creates a lot of lag.

#
#### What do you suggest instead/what changes do you propose?
What I would suggest is adding the ability to use the larger cells also to process this, like the steel, chrome, iridium, and so on cells.
This would mean that people can now get 8000 compressed air, with a steel cell, instead of 144 with the small ones.
To combat the speed these could be run trough, I suggest adding a calculation like this and 8k cell would take 8000/144 =55 times the time to fill with compressed air, and also take 55 times longer to process with the vacuum freezer. 
The same would then go for larger cells,  alu, chrome, and so on.

If needed to make people switch, give a 10% speed boost for each cell. this would mean a larger amount in a shorter time the higher cell level you go.
So say 10% of an iridium cell would be a lot more free air compression time than 10% of a steel cell. 

Think of it this way, If, on a multiplayer server, someone on gave an iridium cell to an MV player, how long would it take that person to fill that one cell in an MV compressor :D

**Comment by Prometheus0000** [comment]
The cryo freezer doesn't need the cells.

**Comment by Devtron3D** [comment]
I know that is a possibility, I myself have not built it yet.

I was looking for an option that also works at lower-tier players, that have not yet reached the cyro.
Just adding the air intake hatch seems to simple.
Using the cells would also make them more useful

**Comment by Devtron3D** [comment]
The possibility for using this with the electrolyzer and other machines would also help
Like making aqua regal atm requires the small cells.
There are a lot of recipes that could benefit from the larger cells, as it would help move fewer cells around and create less CPU time.

If the time to make it is still the same pr volume of the product, it would not matter if they got a bigger batch, creating it with 55x 144cells or 1x 8k cell should still be the same crafting time, so the main benefit would be the fewer cells to work with and store.

**Comment by Prometheus0000** [comment]
I'm not sure what the size of the input buffer is for all the machines, or how easy this is to do. If someone has to manually make new recipes for them all, it might not happen since you can just advance and use the GT++ multis to avoid cells.

**Comment by Prometheus0000** [comment]
And for some recipes that need a cell and fluid, it might not have a large enough input tank for that. Especially for cells > 64K L.

**Comment by Devtron3D** [comment]
well atm 8k is the smallest of the larger cells
My problem is there are some useful recipes that you can't get around even at late stages to use the small cells.
Aqua Regal being one of them, there are a few more I can't remember atm, that there are no other ways to craft.
Aqua regal i atm craft by the drum, that's over 1.777 pr craft, in the large mixer. At LuV this crafts in seconds, and if you make a few drums at a time, this shows up on lag monitoring tools.
Atm, I have around 20k of 144 cells in stock for things that I cant avoid the small cells on.

**Comment by Devtron3D** [comment]
Also if i remember correct an HV hatch is 56k, there is more than enough room there.
I don't know how it would work in a single block with two cells to craft something.

**Comment by Prometheus0000** [comment]
I was thinking about the SB chemical reactor.

**Comment by Devtron3D** [comment]
IF i remember right, they hold different amounts of fluid, depending on tier. but I seem to recall that mv or hv has 16k storage

**Comment by GeicowithaBango** [comment]
1.) Isnt a compressed air cell 1000mb of air? 
2.) Theres a dedicated liquid air hatch it holds the needed amount

**Comment by Devtron3D** [comment]
1, yes it is, I was thinking of other recipes when thinking of that too :/, so I wrote down the wrong number.

2. the liquid air hatch holds a lot more, it does not work on the vacuum freezer, only the cryo.

**Comment by Prometheus0000** [comment]
PS: It doesn't work on the MVF either.

**Comment by Devtron3D** [comment]
That would save one machine, energy-wise, but it would still have the cells running to more than one of those air hatches, as one cannot keep up with an LuV freezer with 2 energy hatches.
And again with 1000+ cells, I have in my setup atm, it does show on OPIS.

**Comment by GeicowithaBango** [comment]
@Devtron3D ours works fine in the DT, and its supposed to work for the DT. Could you attach  screenshots so we know how your setup looks like?

**Comment by Devtron3D** [comment]
@GeicowithaBango you mean air intake hatch on distillation tower?

**Comment by GeicowithaBango** [comment]
yes.

**Comment by Prometheus0000** [comment]
If the air intake hatch works on the DT, what's the point of the liquid air hatch? Or is it a different recipe?

**Comment by GeicowithaBango** [comment]
excuse me, i was talking about the liquid air input hatch.

**Comment by GeicowithaBango** [comment]
btw, a compressor might be handy here.

**Comment by Prometheus0000** [comment]
Do you not understand what the air intake hatch does? It makes 'Air' which is what you get if you uncan a compressed air cell, so you can just recan it in a ULV tank (hot the hatch) to skip compressing. _That's the whole point._

**Comment by Devtron3D** [comment]
Well unless there is another recipe i am missing, atm I am making argon this way
small cells ->compressor->vacuum freeser->distilation tower->argon->  send empty cells back to start

I know I can use the air intake direct to skip the compressor, but last I checked the compressor (multiblock) was faster than a few air intakes.

**Comment by Prometheus0000** [comment]
It doesn't cost power, plus you can use it directly in the cryo freezer to get liquid air. I haven't checked which is faster though.

**Comment by Prometheus0000** [comment]
Also, wasn't the liquid air DT recipe bad for anything other than the ones you need it for? Like xenon? Aren't you supposed to get argon and the others (first 6 or so?) by centrifuging it?

**Comment by Devtron3D** [comment]
![image](https://user-images.githubusercontent.com/3405825/93662439-6108ea00-fa60-11ea-8bb3-acc0daf5f488.png)
Multiblock Centrifuge
------------------
![image](https://user-images.githubusercontent.com/3405825/93662443-6f570600-fa60-11ea-8cc4-5a8dbb9d9327.png)
Distillation Tower

Which one would you chose :D

**Comment by Prometheus0000** [comment]
#5383 Is the second actually better then? My understanding is that it isn't?

**Comment by Devtron3D** [comment]
![image](https://user-images.githubusercontent.com/3405825/93662710-8991e380-fa62-11ea-9eb2-d450555ce5ce.png)
current setup,  I have removed 1 freezer as the chunk created to much lag, so I have run only 1 for a few days.
If i did the math right I am going through a 1000 cell batch every 50 seconds.

But as i said it is not just this recipe where you are kind of forced into the small cells, even in the late game, either we need a recipe change for some of these, or as i suggest, allow these few recipes that add high tick time to the server to user larger cells

**Comment by Prometheus0000** [comment]
So the cryo freezer+air intake hatch -> DT (all liquids) is slower than PA compressor -> freezer -> DT (uses cells)?

**Comment by Devtron3D** [comment]
No, I don't think so, have not used the cryo yet, also as a side note, the cyro requires LuV to make.
I have been using a setup like this since IV i think

This got a bit sidetracked, this was just meant as a comparison to why bigger cell sizes would help decrease lag while giving people more ways to build setups.

Aqua regal / Drilling fluids are the only two i can remember atm that take a ton of small cells to make what is needed late game.
The more cells you use and the faster you use them, the more lag is introduced on a server.

**Comment by 0lafe** [comment]
I like this idea. I had a similar issue when setting up rocket power. Not entirely sure how you're managing to lag that much with that little throughput, but I don't know how much that matters. Definitely should keep 1:1 timing/power, but less items/time being moved around seems good

**Comment by johnch18** [comment]
I'd just generally like to not have to use single-cells in recipes, but I imagine it could be a challenge.
