### ISSUE TITLE
Quest requirement is in the wrong order

### ISSUE THREAD

**Issue by tyrannus00** [GTNewHorizons/GT-New-Horizons-Modpack#6653]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Internal Server, probably irrelevant.
#
#### Problem:
To unlock the Quest "You're gonna hate this #2" (#93) you are required to complete "You're gonna hate this #3" (#95) first, what doesn't make sense.
# 
![2020-09-19_00 04 40](https://user-images.githubusercontent.com/60930117/93651618-6e978300-fa12-11ea-90a7-4c89b109cbfe.png)

**Comment by Prometheus0000** [comment]
I checked, and this is already fixed, though I'm not sure which PR it was.
