### ISSUE TITLE
Neutronium ingot quest in Legendary Tier X needs Neutronium ore

### ISSUE THREAD

**Issue by DuskNite** [GTNewHorizons/GT-New-Horizons-Modpack#6658]
#### Which modpack version are you using?
2.0.9.0

#
#### What did you try to do, and what did you expect to happen?
Hidden quest asks for neutronium. Checking in creative, quest literally needs neutronium ingots.
Expected quest to trigger on collecting neutronium ingots (like all the previous hidden quests)

#
#### What happened instead? (Attach screenshots if needed)
Quest triggers on collecting neutronium ore. The black plutonium quest also has the same issue (I'm glad I sat around at pluto),
https://media.discordapp.net/attachments/234936569360809996/756746341140660244/unknown.png?width=823&height=463

Edit: 
![image](https://user-images.githubusercontent.com/19917651/93665654-bec22400-faaa-11ea-8035-716119f68d0c.png)
Quest asks for ichorium. Triggers on thauminite nugget??

#
#### What do you suggest instead/what changes do you propose?
Change to neutronium ingot. It's unlikely anyone has the ore lying around (because it's UHV and who the fuck doesn't have an ore processing setup) unless they have a void miner (because normal miner produces crushed ores). Same for the black plutonium one.
If it is possible to do a 'or' on the trigger, have it check for ore/dust/ingot. That should give ideal coverage. Otherwise, the next best fix is to check for the ingot, not the ore.

**Comment by Prometheus0000** [comment]
I found a way to make tasks OR based by looking at another pack's quest. You need to set multiple tasks and then go to Edit -> Advanced -> Object -> Object and then set taskLogic to OR instead of AND.

BTW if you want other changes to the tab, you can open another ticket for that. Like the void capsule mentioned on discord.
