### ISSUE TITLE
lag induced by the output hatches trying to output in an EIO fluid conduit

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6662]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### 
Was tracking down the lag sources on Eta, and i found out that if an output hatch tries to output in an EIO fluid conduit, it produces more lags:
fluid conduit facing the output hatch's output:
![with fluid conduit](https://user-images.githubusercontent.com/12850933/93713863-fdb1b180-fb5e-11ea-8abd-65974ae2aea8.png)

no fluid conduit:
![without fluid conduit](https://user-images.githubusercontent.com/12850933/93713873-0b673700-fb5f-11ea-9d04-a3eab6cd7c97.png)

While the diffenrence can look neglictible, i encountered a case on eta where it makes 1ms lag.

output facing the gigantic eio fluid conduit network:
![laggy](https://user-images.githubusercontent.com/12850933/93713960-b24bd300-fb5f-11ea-9942-3795365521d2.png)

output not facing the gigantic eio fluid conduit network:
![not laggy](https://user-images.githubusercontent.com/12850933/93713981-ce4f7480-fb5f-11ea-9840-70dbb6dcac0a.png)

To be sure it was not random lag, i did spam the tricorder for a minute in each configuration shown on the pictures.

**Comment by MotiasF33** [comment]
more
![изображение](https://user-images.githubusercontent.com/47714084/93714831-d44c5200-fb6d-11ea-897e-64153739b15b.png)

**Comment by mitchej123** [comment]
Can you get a warm roast, opis, tickprofiler, or VisualVM profile of it?   Knowing what functions are the hot spot is very helpful.

**Comment by MotiasF33** [comment]
> 
> 
> Can you get a warm roast, opis, tickprofiler, or VisualVM profile of it? Knowing what functions are the hot spot is very helpful.

i can't (i don't have permission), but maybe @boubou19 can?

**Comment by MotiasF33** [comment]
Have ideas how to extract them immediately?
Because for chemicals such as sulfuric acid - auto-export is too slow

**Comment by boubou19** [comment]
Opis is currently broken on eta, and i don't have access to WarmRoast, so only @Dream-Master can check this.

**Comment by MotiasF33** [comment]
I'm try use O hatch > Tank and export fluids with pump but ih have LAG too
![изображение](https://user-images.githubusercontent.com/47714084/93715290-162ac780-fb71-11ea-8f58-9a7045ecfc74.png)

**Comment by boubou19** [comment]
@MotiasF33 said that even if the EIO max auto extracting rate is set to 200mb/t in the EIO config, if you push the fluid through the pipe network with another way, the speed is unlimited, maybe it's the reason of the lag source, as it has to check the whole network to find room for the fluid, instead of sending it 200mb by 200mb.

**Comment by MotiasF33** [comment]
![изображение](https://user-images.githubusercontent.com/47714084/93716569-3068a380-fb79-11ea-8c92-3d75846382e1.png)
Elsewhere it creates less lags
![изображение](https://user-images.githubusercontent.com/47714084/93716596-6c036d80-fb79-11ea-85bd-1049e99db6f0.png)

Because it also has an entrance where liquid can enter

**Comment by boubou19** [comment]
should be fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/730
