### ISSUE TITLE
Quest "Project red beginning" (#127) is invisible

### ISSUE THREAD

**Issue by Glordir** [GTNewHorizons/GT-New-Horizons-Modpack#6664]
#### Which modpack version are you using?
1.0.9.0
#
#### What did you try to do, and what did you expect to happen?
I got the quest-completed notification for the quest "Project red beginning" (ID:127). I opened the questbook and expected to find this completed quest.
#
#### What happened instead? (Attach screenshots if needed)
But there is no (visible) icon in the questbook where I could read the Quest description / see the quest requirements / collect the rewards.

Further information:
The quest can be found in the document _config/betterquesting/DefaultQuests.json_ by using the search term <"questID:3": 127,> (without <>). However, there is no entry on which questline / position the quest should be displayed at.
For example, the questline and position of the quest with the id 126 and 128 can be found by searching for the term <"id:3": 126,> and <"id:3": 128,> respectively. But nothing can be found when searching for the term <"id:3": 127,>
#
#### What do you suggest instead/what changes do you propose?

- Remove the quest with the ID 127 entirely.
or
- Make the quest visible / add the position and quest line information to this quest.
#
Edit: The same is the case for the quest "Can u eat those? " (ID 737).

**Comment by Prometheus0000** [comment]
See #6126
