### ISSUE TITLE
One Ring recipe

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6665]
#### Which modpack version are you using?
2.0.9.1 dev
#

So now we need a recipe for the one ring. It needs to be far along enough you can't abuse it to cheese all the bosses (and infernals), but not as far as infinity armor, since that apparently also makes you invincible. So here's my proposed recipe:

![image](https://user-images.githubusercontent.com/8517039/93722286-9f3b0200-fb63-11ea-9e8b-50a85890a300.png)

This is UV and uses items from Witchery (easy, couldn't find a harder item easily), BM (T6, hard to get there, but not so hard to make), and TC (Moderately difficult). It gets it's UV-ness from the SpNt and SpPu.

See #6092 to see how to make the void essence for the shards.
#
It uses SpNt plates,  SpPu blocks, Wand Focus: Mending/Shield, Attuned Stone (charged), Crystal Cluster, Eldritch Blood Orb, Extremely Primordial Pearl, Shard of Creation, Inventory/Armor Charging Ring, and Ring of Runic Shielding +5.

You can make this is time for the Pluto boss if you really want to.

**Comment by Rakdarian** [comment]
Remove the warping effect entirely. Also, last stand makes you immortal as well, are we going to remove that? It makes you more immortal then one ring because one ring doesnt protect you from chaos dragon

**Comment by boubou19** [comment]
Last Stand consume XP, and the more armor pieces with Last Stand are damaged, the more it costs you to survive (see https://ftb.gamepedia.com/Last_Stand)

**Comment by Rakdarian** [comment]
Xp is free and its actually less.

**Comment by Dream-Master** [comment]
the ring is evil so got warp during usage is ok

**Comment by Rakdarian** [comment]
Sticking it behind UV and having the warping effect as is is pretty unreasonable

**Comment by quedral** [comment]
by the time you reach UV you would have almost all armour in game that can make you invulnerable so the ring itself would be obsolete. I don't think this is a good change. Either remove it completely or add reasonable recipe.

**Comment by leagris** [comment]
Can there be only one of it per server and implement an IA so the ring has its very own will. Choose its owner, but may decide to drop itself from inventory and bury hidden until it find a new owner who pleases its master's will ^^. Like the ring could vanish if its owner dies. Even if ring is in any other inventory. It will vanish to be looted again by someone-else. I can conceptualize implementations that would make it possible with NBT Serial # and owner encoded, so the ring item cancels itself if taken in player inventory of a demised owner.

Chat message:
> You lost the one ring, likely it deemed you unworthy to it.

**Comment by Rakdarian** [comment]
UV is too high, especially with the considerable drawbacks

**Comment by jackowski626** [comment]
Making it available a bit before first invulnerability-granting armors would be pretty reasonable. Finding it in chests is completely meh. Making a recipe for it is kinda meh lorewise tho, if someone wants to code a ring ai, that would be dope.

**Comment by Prometheus0000** [comment]
Leagris, I choose you! (throws pokeball)

**Comment by Rakdarian** [comment]
Good invulnerablility granting armor are accessible at HV. If thats where were putting it at i dont actually have an issue

**Comment by Prometheus0000** [comment]
If there's armor that make you invincible at HV, then that needs nerfing too.

**Comment by KiloJoel** [comment]
The one ring doesn't make you immune to creeper fish -> Worthless

**Comment by KiloJoel** [comment]
On a more serious note though, I like where the ring is. Maybe instead of moving where it is, nerf the damage immunity.

**Comment by Rakdarian** [comment]
Ring doesnt make you wholly invincible. Last stand does, and HV gets you access to high durability armor like Dreammasters/fortress gear. Technically it also works on earlier tier armors but the durability is lower.

**Comment by MotiasF33** [comment]
**Stop it**, @Prometheus0000,  for what needed The One Ring on UV-tier?
You just remove item this recipe.
If the ring has a craft
It should be available at the end of the HV-Tier after crafting Dire Table.

**Comment by Rakdarian** [comment]
Yeah that sounds fine.

**Comment by Houstonruss** [comment]
Why isn't this an infusion recipe? Every item in that craft is beyond the usefulness of the ring too.

**Comment by Rakdarian** [comment]
Infusion is reliably craftable in lv. Making it an avartia table gates it better.

**Comment by Houstonruss** [comment]
> Infusion is reliably craftable in lv. Making it an avartia table gates it better.

I thought the black plutonium and the armor charging rings were the gates here?

**Comment by botn365** [comment]
even if the infusion can be made in LV and avaritia table is HV it makes more sense thematicly for it to be infusion becous its a magic item

**Comment by MotiasF33** [comment]
Our offer recipe the One Ring:
_the recipe becomes available at the HV tier_
### Concept:
The One Ring - A One ring that contains the power/affects of multiple rings

### Recipe:
![изображение](https://user-images.githubusercontent.com/47714084/94055293-6b6f0f00-fde5-11ea-9639-8c15df9e7701.png)

Components: 

- Rose Gold Plates x16
- Rose Gold Screw x4
- Rose Gold Foil x4
- Ring of Aer (3%)
- Talisman of Remedium
- Ring of Ignis (3%)
- Ring of Terra (3%)
- Primal Charm x2
- Wither protection Ring
- Ring of Perdito (3%)
- Talisman of Nourishement
- Ring of Ordo (3%)
- Taitantacle Ring
- Ring of Aqua (3%)

**Comment by Houstonruss** [comment]
This is better, but maybe it shouldn't require other rings to make, just the talismans and charms.

**Comment by MotiasF33** [comment]
> 
> 
> This is better, but maybe it shouldn't require other rings to make, just the talismans and charms.
Rings represent the effects of The One ring

Elements ring says: that ring contains the strength of the elements.
![изображение](https://user-images.githubusercontent.com/47714084/94061526-2dc2b400-fdee-11ea-8e11-be089dd9658c.png)
Tanitacle ring says: this ring have a warp
![изображение](https://user-images.githubusercontent.com/47714084/94061591-4337de00-fdee-11ea-99b0-8d0185da9d85.png)
Wither protection - Protect from wither 
![изображение](https://user-images.githubusercontent.com/47714084/94061695-64003380-fdee-11ea-8e91-4e3c170b550b.png)

**Comment by Rakdarian** [comment]
The vis discount rings are a little weird. If I was making it I would swap them out for each of the runic shielding rings. Everything else seems kino.

**Comment by MotiasF33** [comment]
> 
> 
> The vis discount rings are a little weird. If I was making it I would swap them out for each of the runic shielding rings. Everything else seems kino.

You can always suggest your own version
