### ISSUE TITLE
Betterquesting tag weirdness

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6666]
#### Which modpack version are you using?
2.0.9.1 dev
#
#### What did you try to do, and what did you expect to happen?
Edit quests
#
#### What happened instead? (Attach screenshots if needed)
Tag appears/disappears from all item entries causing huge diffs.
![image](https://user-images.githubusercontent.com/8517039/93724133-7bcb8380-fb72-11ea-88bc-64bd0816db9d.png)
![image](https://user-images.githubusercontent.com/8517039/93724139-88e87280-fb72-11ea-9860-b45801d2a558.png)
You can see the line "registryName:8": "minecraft:wheat", has disappeared, even though all I did was load and save. And I was the last person to edit quests too. Maybe it's caused by being it being 2.0.9.1 dev? I reverted the BQ3 version to the 2.0.9.0 QF4 version before this (see https://github.com/GTNewHorizons/BetterQuesting/pull/14#issuecomment-695844214), so it should be the same.
#
#### What do you suggest instead/what changes do you propose?
I dunno what's causing it.

**Comment by MotiasF33** [comment]
So what about the registryname?
While we have different versions of file, editing is not very convenient(

**Comment by MotiasF33** [comment]
@Prometheus0000, @Dream-Master ?

**Comment by Prometheus0000** [comment]
I already said I don't know what's causing it, what do you want me to do?

**Comment by MotiasF33** [comment]
> 
> 
> I already said I don't know what's causing it, what do you want me to do?
may be merge last version?
as you said: default load>save and paste it
I'm not sure if this is correct

**Comment by Prometheus0000** [comment]
I'm not editing quests right now though? I always use the latest version when I do. And that's so that the weird change is in a separate commit, not so it stops happening. I also asked @dvdmandt to look at it before since they were also editing the zoom code, but I guess they're busy.

**Comment by MotiasF33** [comment]
> 
> 
> I'm not editing quests right now though? I always use the latest version when I do. And that's so that the weird change is in a separate commit, not so it stops happening. I also asked @dvdmandt to look at it before since they were also editing the zoom code, but I guess they're busy.

It is sad.
Will wait for someone to free himself and help 🥺

**Comment by dvdmandt** [comment]
I've tried looking into this, but I can't figure it out. I'm not convinced this is even a BQ or SQP problem to be honest. It seems BQ uses NBT structures for everything internally and just sets various properties. As far as I can tell, BQ/SQP does not touch the property "registryName" anywhere in the code. It basically just gets this data from Minecraft/Forge/something and stores it and loads it as it is. The icons are item stacks, so I think the problem is how Minecraft/Forge stores items. Like, what data is stored about an item when you just /give it to a player or whatever.

**Comment by dvdmandt** [comment]
In other words, I think this might very well affect how items are stored in all files, like chunk files, player inventories and what not.

**Comment by Prometheus0000** [comment]
I'm wondering if it's related to the hodgepodge (or whatever) fix for the circuit imprints/sliced circuits from a while ago. But I think that was in before 2.0.9.1.

**Comment by dvdmandt** [comment]
Wasn't there some experimental crafting optimizations? That could be it, but that should have been in QF4, right?

**Comment by Prometheus0000** [comment]
Isn't that just recipe caching?

**Comment by dvdmandt** [comment]
No idea. It seems to be something that deals with how items (or possibly icons, but I think items) are stored. Reasons to change these things would likely be some form of lookup optimization and/or debug help for something like MineTweaker.
