### ISSUE TITLE
Can't lunch GTNH ver2.0.9.1-dev(Game crush)

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6668]
#### Which modpack version are you using?
ver2.0.9.1-dev
#
#### If in multiplayer; On which server does this happen? 
single
#
#### What did you try to do, and what did you expect to happen?
install and boot
#
#### What happened instead? (Attach screenshots if needed)
Game crush and I can't lunch GTNH ver2.0.9.1-dev

・Crush reports
[crash-2020-09-22_10.16.30-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5258834/crash-2020-09-22_10.16.30-client.txt)
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Prometheus0000** [comment]
If you looked at the discord, you would've seen this is a known issue that's being worked on.

**Comment by bartimaeusnek** [comment]
retry with new version (which is bugged again in some other manner, but hey)
