### ISSUE TITLE
[EIO] EIO facade the Planar Boundary cause voiding items. 

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6671]
#### Which modpack version are you using?
2.0.9.0qf4
#
### EIO conduits voiding items
Item extrating from the chest but does not appear in another chest
![изображение](https://user-images.githubusercontent.com/47714084/93886924-b2c6a400-fcee-11ea-8907-b64e6e4649c7.png)
_On the left line items voiding. On the right, everything is fine_

**Comment by MotiasF33** [comment]
I think the problem is caused by facades at the connection point
![изображение](https://user-images.githubusercontent.com/47714084/93887459-6891f280-fcef-11ea-8bc7-f110439afe4d.png)
_I used the facades masked as a Planar Boundary block_
