### ISSUE TITLE
Nerf Last Stand

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6672]
#### Which modpack version are you using?
2.0.9.0 QF4
#

Since according to @Rakdarian #6665 Last Stand is OP, I propose nerfing it so it can fail. The exact percentages are certainly up for debate, but I've already prepared a PR.

**Comment by Rakdarian** [comment]
You said it was op not me.

**Comment by mitchej123** [comment]
Last stand isn't OP; you need to enchant it, and then grind a bunch of levels.  I vote no.

**Comment by Houstonruss** [comment]
Everything is op in this pack if it isn't shit.-0lafe probably.

**Comment by quedral** [comment]
another senseless nerf proposition. please do something productive / creative instead.

**Comment by Dream-Master** [comment]
we just discussed here so if we decide we won't change it then we close this thread. relax

**Comment by Prometheus0000** [comment]
Closing because unnecessary/unwanted.
