### ISSUE TITLE
Portable scanner upgrade suggestion to trace lag

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6673]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
prospercraft
#
I like trying to get off the larboard on the server, but in some ways, it's hard to pin down what in the chunk is causing issues.
Now look at this nice picture 👍 
![image](https://user-images.githubusercontent.com/3405825/94034557-749ab480-fdc2-11ea-894d-1aad855967b0.png)
This is a setup I use, I use the. puts fluids into a machine and extracts items (in this case a fluid solidifier), but what machine it is irrelevant (i hope)

The problem is the portable scanner, I can scan gregtech machines like this machine on the image, and gets an average CPU load of ****** of it. This works with most gregtech related machines I can scan.

Would it be possible to add more items to this list so i can get CPU load, in this case on the image, i have 3 scans, the top is the machine block, the next two are the AE fluid and item bus on the sides.  They do not show the CPU load.
Ender IO items don't show CPU load, as well as chests and such, vacuum hoppers, and more.

Is it possible to add these CPU load information to more items?

**Comment by MotiasF33** [comment]
It would be great, but I think it's impossible

**Comment by Devtron3D** [comment]
Would it be possible to create another device that can do this?

**Comment by mitchej123** [comment]
GT does it's own time tracking, that's why it can be reported.  This can only be done with other mods by 1) editing their code 2) sampling activity from the JVM.

**Comment by dvdmandt** [comment]
Wouldn't it in theory be possible to add timing to Forge itself? Looking at the sources and licenses, it should be possible to create our own Forge build, even though it's not technically open source? Or is there some huge issue with that?

**Comment by mitchej123** [comment]
That'd add a non trivial amount of overhead, plus distributing a custom forge would be annoying.  We've thought about it in the past.

**Comment by dvdmandt** [comment]
So I'm not actually proposing we'd do it, but I'm a bit curious anyway as performance and lag-tracking are common issues for server operators. I assume Forge does some form of loop updating TileEntities in a chunk or similar? If so, sampling once before the loop, and at the end of each iteration you'd sample again and subtract last readout and assign it to the block. Are timestamp sampling really that expensive? Other than that, it's like 5-10 instructions per TileEntity, can't imagine that would be too bad of an impact..?

**Comment by repo-alt** [comment]
Added GT compatible timing for interfaces & buses. AE tiles don't really tick, so this timing will make some sense only for continuously working parts.

**Comment by repo-alt** [comment]
Just a note: later investigation shown that this won't work well even for interfaces (for buses it doesn't work at all). Theoretically it is possible to have such timing spliced in the AE, but it would require extensive changes, that I'm not really ready to undertake.

**Comment by GTNH-Colen** [comment]
> Just a note: later investigation shown that this won't work well even for interfaces (for buses it doesn't work at all). Theoretically it is possible to have such timing spliced in the AE, but it would require extensive changes, that I'm not really ready to undertake.

Thanks for looking into it anyways, ultimately staff have other tools to track down lag (OPIS and warmroast) so this isn't the end of the universe.

**Comment by Devtron3D** [comment]
My suggestion for this was to take the stress of the server owners and their staff and make people police their own bases and their neighbors. 
I would be great if there was a way for the average user to figure out what is causing stress on their world, be it single player or multiplayer
