### ISSUE TITLE
Sky stone is unable to obtain on servers disabled the AE2 meteor generation.

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/GT-New-Horizons-Modpack#6677]
#### Which modpack version are you using?

2.0.9.0QF4

#
#### If in multiplayer; On which server does this happen? 

Stonelegion

#
#### What did you try to do, and what did you expect to happen?

The server had disabled the generation of AE2 meteors according to several reasons. Now there is no way to obtain sky stones. The only recipe is the bee but to breed the bee it will need one sky stone to get that species.

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?

Add a coin quest or gives some free sky stone in AE2 quest line.

**Comment by Prometheus0000** [comment]
Untrue. Summon a BM meteor.
