### ISSUE TITLE
[Suggestion]Change NASA Workbench's recipe

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6678]
#### Which modpack version are you using?
2.0.9.1a-dev
#
#### If in multiplayer; On which server does this happen? 
single
#
#### What happened instead? (Attach screenshots if needed)
In HV tier(Before space), we can't get Uranium 235 without stacking the odds against it.
Also this recipe far more expensive to craft than the DireCraftingtable that needed to craft a rocket before.
![2020-09-24_19 44 22](https://user-images.githubusercontent.com/40425798/94135402-60c48080-fe9e-11ea-8a94-1e8e800336bd.png)
#
#### What do you suggest instead/what changes do you propose?
Change Material.
How about Nether Star plate or Advanced Wafer?

**Comment by Rakdarian** [comment]
Thorium has uranium byproducts which centrifuge into 235 iirc

**Comment by yukieiji** [comment]
I think it's difficult that two uranium-235 dust (lay the odds on the probability) from Thorium, which is available in low quantities in HV....

**Comment by Rakdarian** [comment]
You only need one nugget and then you can use the metallurgic perfection recipe to make more nuggets out of thorium

**Comment by yukieiji** [comment]
If we are going to need TC(until that WC's research) at this point, we are going to need to change a large number of quests to include this process, and who's going to do that?

**Comment by interestingusernam3** [comment]
Macerate red granite cobblestone with HV macerator.

**Comment by yukieiji** [comment]
It's available in larger quantities than Thorium, but on the other hand, the probability and size of Uranium-238 dust is reduced, so I don't think it makes much difference.

**Comment by Rakdarian** [comment]
You dont need to use metallurgical perfection. It is wholly doable with red granite/ thorium. If you're complaining that its grindy then you might be in the wrong pack

**Comment by draknyte1** [comment]
Pointless tedium like that isn’t favourable for things that gate progression. 

TC also shouldn’t be required for space. Changes to remove TC as a requirement have been made in the last few updates already.

**Comment by interestingusernam3** [comment]
>TC also shouldn’t be required for space

It isn't?

**Comment by glowredman** [comment]
In a previous version of GSit was a different recipe. (https://discord.com/channels/181078474394566657/739455313924587591/753673012519108709). Multiple users including Dream found this too easy, so we changed it to this. In general I'm open for suggestions, but I want to keep the layout about the same

**Comment by Rakdarian** [comment]
You mean like grinding the 288 wither skulls to get dire table in the previous iteration? It's not thaumcraft gated. Thaumcraft makes it easier, not stops it. Just do red granite/thorium it really isn't that hard

**Comment by Rakdarian** [comment]
Err oops 54. For some reason I thought dire table required 96 nether stars

**Comment by botn365** [comment]
so you mine 280 thorium ore or you macerate 36K red granite(ReaLy nOt thAt HarD)
also its 18 nether starts 1 block -> 9 ingots   1 ingot -> 2 nether starts -> 9*2 = 18
also the thorium ore is sporadic so there is like a best a stack of ore there so you would have to go trough the rng again to find 5 veins for your thorium
both of this is retardet noting hard about it just tedium and only tedium nothing fun
if it was u238 fine that 1 thorium vein and ~200 red granite but this 2 u235
and you still need 9 nether stars and the difrents between 9 and 18 is very small becous at that point you already have a skeleton spawner in the nether or some other farm with a deacently leveld cleaver

**Comment by Houstonruss** [comment]
Skullfire sword buffed!
nASA WoRKbENcH:

**Comment by Rakdarian** [comment]
Well red granite is fairly common, and thorium might be sporadic but the vein itself is fairly common. Have you considered not being a bitch?

**Comment by repo-alt** [comment]
Thorium vein is not fairly common

**Comment by botn365** [comment]
but what gamplay gets added by having to mine 5 thorium veins instead of 1 exept that  it consumes a lot more time
and sure redgranite may be fairly but there is no tool to propect for it so you jsut have to dig evrywhere to find that 36K! red granite
and the you have to macerate it for 2 days with a HV macerator to get it sure you need more but that is 8-16 HV macerators do do it in a reasenble time frame (6-3 hours) 
is it doable sure but it adds nothing of value to the gamplay and is just pure tedium and nothing more
and a thorium vein is not fairly common it has a weight of 30 while mica is 20 and diamond being 40
have you considerd calculating thiss stuff

**Comment by Dream-Master** [comment]
feel free to suggest recipe here. We can add NASA work bench recipe in absentia table but make it less annoying and more fancy looking @botn365

**Comment by botn365** [comment]
same recipe but replace the U235 plates with 4x gold cable

**Comment by Bluebine** [comment]
I just tested it and one thorium vein (at least, the specific vein I mined) gives enough uranium for 3 ingots and 3 nuggets of U-235. That's exclusively from the ore blocks, so a hammer would get you those results.

my math: I got 144 ore blocks from the vein I mined.
macerate for 576 crushed and, on average, 28.8 U238.
macerate again for 576 impure dust and, on average, 57.6 U238.
centrifuge for 576 thorium and 64 U238.
overall that's 150.4 U238. 
divide that by 9 and multiply by 0.2 and you get 3.34 U235 on average. 

This is with the least efficient mining method (no drilling rigs and no small ores) and pretty simple oreproc (you should be able to macerate and centrifuge ore by HV). You're welcome to do the math yourself if you disagree.

**Comment by yukieiji** [comment]
The HV tier consumes over an hour to process 150 Uranium...
Doesn't it make the game more boring to have to wait for an hour or more when you can't necessarily get it(There's an 80% chance you won't get it)?

**Comment by Bluebine** [comment]
you're likely to only need ~100 U238 to get your needed U235. (statistically 90 of it will be enough 50% of the time) which requires just over an hour to process. That seems reasonable enough to me- killing 18 withers to get enough nether stars would almost always take over an hour of active work versus an hour of AFKing near a machine.

**Comment by yukieiji** [comment]
With the HV tier equipment, the 18 withers should be faster to take down by themselves. there are also other ways to get NetherStar, such as defeating it with a machine or using a witchery
So, I think that collecting 18 Netherstars is much faster than Uranium process.

**Comment by Dream-Master** [comment]
ok we drop uranium . I try to look for a nice recipe maybe in absentia table so we can drop netherstar block  too.

**Comment by Bluebine** [comment]
I don't think it needs to be done away with, the recipe is fine IMO. 
Although if you make it a dire table recipe, the NASA workbecnh should also be made cheaper, since the dire table itself is very expensive.

**Comment by Dream-Master** [comment]
that's what I mean.

**Comment by interestingusernam3** [comment]
>The HV tier consumes over an hour to process 150 Uranium...
Doesn't it make the game more boring to have to wait for an hour or more when you can't necessarily get it(There's an 80% chance you won't get it)?

Did you like dupe/ProjectE your way through the pack or something? This isn't even an impressive amount of time compared to some earlier things

**Comment by Rakdarian** [comment]
Yeah this guy just seems like hes upset that theres a bit of a grind. Thats the pack buddy.  And if you dont want to process an entire vein worth of thorium, options are availible to you. You brought up that there are alternative ways to make nether stars, well there are alternative ways to get the plutonium. 


As for my suggestion i think the nasa workbench is too easy. Dense U235 plates should do.

**Comment by yukieiji** [comment]
@Rakdarian Do you realize that Uranium is only available on a probability basis(in HV Tier), which means that you may not be able to get it even if you process tens of thousands of them?
With the exception of TC, there are ｍassive ways to defeat a wither(to get NetherStar), but there's only one way to get the Uranium-235, right(only centrifugation of Uranium-238)?

**Comment by Rakdarian** [comment]
Not really. You have to grind for skulls every time. Unless you're in luv(?) And straight up can miss e the ore. As to the remark about probability. Sure that could happen, you could also kill 100k wither skellies and not get a skull. It really isn't that difficult

**Comment by Houstonruss** [comment]
![wbrecipie](https://user-images.githubusercontent.com/50430417/94291755-01ac4d80-ff2a-11ea-9b48-d95eb80e43c4.png)
Hard Wall T8, Nether Star Plates in "Extended Robot Arm"
Im trying to keep things more tech and matching the theme of the workbench.

The Uranium and block of stars felt lazy.

**Comment by glowredman** [comment]
What is the top right item?

**Comment by Dream-Master** [comment]
@glowredman  lense from GC

**Comment by GeicowithaBango** [comment]
Afaik, nobody appreciate nether stars in the dire table, so im glad this is finally gone.

**Comment by Rakdarian** [comment]
A. I did. B. You still need 9
