### ISSUE TITLE
Gregtech output bus, with chest with many slots, causes high CPU load

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6680]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
prospercraft
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/3405825/94154983-bee16b80-fe7e-11ea-9e06-fe55603fc1f4.png)

In this example, i have an Gregtech output bus, with a chest to output to.
the CPU time goes up, the bigger the number of slots in an inventory.

Jabba barrel
![image](https://user-images.githubusercontent.com/3405825/94155380-2e575b00-fe7f-11ea-8bbb-6ff73e1cfada.png)
------------------------------------
Vanilla chest
![image](https://user-images.githubusercontent.com/3405825/94155521-521aa100-fe7f-11ea-912d-ed4da525b228.png)
-------------------------------
Diamond chest cpu time
![image](https://user-images.githubusercontent.com/3405825/94155234-036d0700-fe7f-11ea-8841-7ac8b53d7254.png)
------------------------------
Compressed chest
![image](https://user-images.githubusercontent.com/3405825/94155591-66f73480-fe7f-11ea-94f9-559ce4f5b8d3.png)
------------------------------

As can be seen, as the number of slots in a chest increases the output CPU time increases a lot

**Comment by Prometheus0000** [comment]
Is this the same as mentioned at the top of #6414? As in fixed?

**Comment by Devtron3D** [comment]
I don't know if it is the same.
I know super buffers are still a LAG monster on 2.0.9.0

I know this one causes a lot of lag, and i have been helping people change to other designs in their bases to reduce lag on prospercraft, so we can stay at 20tps

**Comment by GTNH-Afx237v7** [comment]
I believe this can be considered fixedindev with this optimization: https://github.com/GTNewHorizons/GT5-Unofficial/pull/306  (also shown to reduce cpu usage here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6198) 

Also, the new ME output bus provides an alternative to save tps

**Comment by boubou19** [comment]
i'm closing this as it's already in 2.1.0.0
