### ISSUE TITLE
AE power from gregtech dynamo, high cpu time

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6681]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
prospercraft
#
#### What did you try to do, and what did you expect to happen?
When trying to trace down lag, it was observed that every base had energy dynamos that were reporting high CPU time

It was traced down to AE power draw from the dynamo. 
We tested getting energy with an energy acceptor, or direct into the AE controller block, the same result.
I have a ZPM level base attacked to other dynamos, and they have normal CPU time.

![image](https://user-images.githubusercontent.com/3405825/94158579-d884b200-fe82-11ea-8f8b-52ede998340e.png)

This problem was discussed a few days ago in the github discussion on discord.

**Comment by repo-alt** [comment]
Does it happen when dynamo directly outputs to the energy acceptor, or is there a cable?

**Comment by Devtron3D** [comment]
![image](https://user-images.githubusercontent.com/3405825/94180222-f8759f00-fe9d-11ea-84ea-767d3a0fd1dc.png)


Here I put the energy acceptor direct on the dynamo, other times was tested with cable.

**Comment by Devtron3D** [comment]
![image](https://user-images.githubusercontent.com/3405825/94283701-a2623380-ff51-11ea-924d-314e2b40d9bc.png)
still only the AE system on this block
AE is currently feeding redstone ore to the ore washer, then the thermal centri and then macerator,

**Comment by mitchej123** [comment]
@repo-alt I started looking into this a bit, devtron sent the following from black ace:  It looks like getDemandedEnergy(), which is called in a while loop, is running a scan on (up to) the entire ae2 network to get energy demanded every time the cables try to insert energy, which is roughly once a tick.  

The ae controller stops scanning once it hits 8k in demand, whereas the energy acceptor will scan the entire network.

I had thought to adjust the insertEnergy to cache the getEnergyDemanded(), and insert up to that much, but that would mean energy starvation if inserted into a controller.  I had some half baked thoughts on caching the energy required, but have not gotten around to investigating further yet.


![ae2_cables](https://user-images.githubusercontent.com/1894689/94286939-84bdab80-ff0a-11ea-9163-ce6ba0caef7e.png)

**Comment by repo-alt** [comment]
I'm on vacation rn, so can't look myself. I think energy handling was refactored a bit in 1.12. Scanning the grid every time sounds bad
