### ISSUE TITLE
Iron golem can't be healed with iron ingots. It should

### ISSUE THREAD

**Issue by rabitibike112** [GTNewHorizons/GT-New-Horizons-Modpack#6682]
#### Which modpack version are you using?
Latest  2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Not MP
#
#### What did you try to do, and what did you expect to happen?
I tried healing my damaged iron golem with iron ingots and nothing happened. I expected it to heal the golem
#
#### What happened instead? (Attach screenshots if needed)
Well, nothing.
#
#### What do you suggest instead/what changes do you propose?
Allow the right clicking of a golem with an iron ingot in hand to heal said iron golem. If i'm not wrong, this is a standard feature of vanilla minecraft. It would be great having this feature (back?) because it might make golems more usable in early game. Right now they are kinda expensive since they die quite easily in this modpack.

Thank you for reading, i hope you have a great day.

**Comment by interestingusernam3** [comment]
>If i'm not wrong, this is a standard feature of vanilla minecraft.


You're wrong

**Comment by Bluebine** [comment]
At least, it's not a feature in 1.7.10. Might be a thing in later versions.

**Comment by Anarack** [comment]
1.15 or so.
