### ISSUE TITLE
High Octane Gasoline Buff [Suggestion]

### ISSUE THREAD

**Issue by General-Ike** [GTNewHorizons/GT-New-Horizons-Modpack#6683]
As it stands, High Octane Gasoline is a bit of a meme. It takes a ton of processing to make, and is simply not worth the investment. Objectively, you get much more energy per bucket of oil input, but oil is honestly not hard to come by. A T2 drilling rig with an EV hatch processed to Diesel as I understand it, will provide fuel at a much higher rate than you would even be able to realistically consume it for power in the tiers where oil energy is relevant.

To buff HOG, it should give the option to "overclock" the LCE. Either by default, or with a configured circuit in the controller block, it should output 4x the qty of energy and consume 4x the amount of fuel. Resulting in 8192 eu/t unboosted, and 24,576 eu/t boosted.

Since I find the problem using oil based fuels in IV/LuV is physically creating the generators to burn them, this change would fundamentally maintain the value of an oil bucket in producing an amount of eu/b, but would encourage setting up an HOG line to maintain relevance of oil, without just spamming diesel. As for balance, since this is a multi that requires dedicated infrastructure, this still doesn't step on the toes of the nutty good Naquadah Reactors, and while I haven't yet made it to fusion, as I understand it, it will still be vastly outclassed by what fusion can do, but if heavily invested in, could even extend the relevance of oil as a fuel for at least a short while into fusion tier.

Additionally, I think HOG should have it's EU value raised again, to 2.25 million EU/b, because it is still a pain to process, and also not a necessary fuel, so there should be proper incentive to make it, especially if players are expected to be burning it at a much higher rate.

**Comment by Houstonruss** [comment]
What if HOG processing gave plenty of useful byproducts used in other parts of the game?
