### ISSUE TITLE
data bank achievement displays wrong

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6684]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
prospercraft
#
#### 
incorrect achievement display

![image](https://user-images.githubusercontent.com/3405825/94185434-8d2fcb00-fea5-11ea-9a82-9536b2e4be96.png)

![image](https://user-images.githubusercontent.com/3405825/94185453-94ef6f80-fea5-11ea-8f4e-4ce5950050b8.png)

**Comment by Dream-Master** [comment]
@Technus any idea. Guess it's your block

**Comment by Technus** [comment]
@basdxz some awry locale?
