### ISSUE TITLE
Remove WG nugget transmutations

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#6685]
#### Which modpack version are you using?
2.0.9.1
#

#### What do you suggest instead/what changes do you propose?

There's a whole lot of these that are terribly OP. While I think some have been removed, a LOT are still left. I'd suggest removing pretty much all of them, considering it seems like the black list doesn't work. Shits dumb

**Comment by Dream-Master** [comment]
the blacklist work but there are only a few entries

**Comment by 0lafe** [comment]
Where is the black list? We put a bunch of stuff in the one in the WG config, but many of those materials are still dupable 
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/WitchingGadgets.cfg

**Comment by Rakdarian** [comment]
I suggest we leave it as is.

**Comment by Prometheus0000** [comment]
Already discussed in github-discussions a few days ago. The blacklist only sorta works, with some entries working and some not for an unknown reason. For example plutonium and plutonium 241, one of which works and one which doesn't. You can tell it works for the ones that it does work by removing them from the blacklist checking ingame. You can turn them off by changing true to false though

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea why some meaterials works and some not ?

**Comment by Rakdarian** [comment]
I think is because of bad oredict tags

**Comment by Prometheus0000** [comment]
@0lafe The BL is fixed, so you can open another ticket about adding items if you want instead of disabling it entirely.
