### ISSUE TITLE
opis - Orphan TileEnts

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6687]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
prospercraft
#
I dont know opis very well, I am new to it.
But i was trying to figure out what all these debug messages are, googling is not helping much
I managed to remove most by breaking some silverwood trees nodes
and tearing down a reactor as seen on these images

The reactor spam stopped after the ic2 nukes were removed
the nodes stoped after breaking silver wood tree nodes
there is a warding stone i cant remove. i removed the stone it but the server still spams messages for it in opis debug

the Silverwood trees at a players base and the warding stone had not had any players near the for months 
the reactor someone was online with reactor 

![image](https://user-images.githubusercontent.com/3405825/94193270-6fb42e80-feb0-11ea-9110-4c012f73dc80.png)
![image](https://user-images.githubusercontent.com/3405825/94193298-79d62d00-feb0-11ea-93b8-2b9695b3b407.png)
![image](https://user-images.githubusercontent.com/3405825/94193337-865a8580-feb0-11ea-8e9c-795ba66efc54.png)
![image](https://user-images.githubusercontent.com/3405825/94193355-8b1f3980-feb0-11ea-9352-c806be699404.png)
![image](https://user-images.githubusercontent.com/3405825/94193376-91adb100-feb0-11ea-93aa-e2a9852e9c0f.png)
![image](https://user-images.githubusercontent.com/3405825/94193388-96726500-feb0-11ea-8322-095a7179838a.png)

**Comment by boubou19** [comment]
did you killed the tile entities with opis or are they just some leftovers?

**Comment by Devtron3D** [comment]
No, i had to manually remove the nodes in the trees and a few wandering stone, as well as remove the reactor
