### ISSUE TITLE
[Suggestion] Chunkloaders

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6688]
#### Which modpack version are you using?
2.0.9.0qf4
#
On a high tier, the problem of loading base arises (if it is located in more than one chunk), because we need to install and loading many anchors
I think it would be great to have 1 device capable of loading сhunks as Chunkloader GT++
![изображение](https://user-images.githubusercontent.com/47714084/94206126-62596d00-fecd-11ea-806d-58f2d07bb284.png)
Because world anchors are disabled on official servers, then this one does not work either.
Perhaps it is worth introducing an analog of an electric loader in the passive anchor mode

**Comment by MotiasF33** [comment]
Maybe we could add [ccchunk](https://github.com/TheCBProject/ChickenChunks)
and configuration it:
- As a passive anchor (Loading chunks if Player was online after start server)
- Limit on the number of loaded chunks (depends on the rank)
What do u think about it?

**Comment by Prometheus0000** [comment]
If you're adding things you can already just add FTButil.

**Comment by MotiasF33** [comment]
> 
> 
> If you're adding things you can already just add FTButil.

I suppose it for Eta :*

**Comment by boubou19** [comment]
Officials already have everything needed to chunkload. World anchors were disabled because endgame base were reloaded without being visited at each reboot, killing the tps instantly.

**Comment by MotiasF33** [comment]
> 
> 
> Officials already have everything needed to chunkload. World anchors were disabled because endgame bases were reloaded without being visited at each reboot, killing the tps instantly.

"As a passive anchor (Loading chunks if Player was online after start server)"

single anchor shit loading large areas

**Comment by boubou19** [comment]
just map them correctly, you can change the shape with the anchor sentinel. There is really no need to add such a thing because we already have them. Also trying to add mods according to a limitation from Officials is a bad idea.

**Comment by MotiasF33** [comment]
> just map them correctly, you can change the shape with the anchor sentinel. There is really no need to add such a thing because we already have them. Also trying to add mods according to a limitation from Officials is a bad idea.

anchor sentinel can only in one direction but not areas.((

**Comment by boubou19** [comment]
yeah, and they are supposed to cover 9 chunks max. I don't see the issue with setting a field of them, the T4 chunkloader coins are basically free on the officials when you reached elite rank. i did that on delta and i cover my ~150+ chunks base fine.

**Comment by repo-alt** [comment]
The problem is not with maintaining chunkloaders, coins are not expensive indeed, but sometimes the loading sequence is important

**Comment by MotiasF33** [comment]
> 
> 
> yeah, and they are supposed to cover 9 chunks max. I don't see the issue with setting a field of them, the T4 chunkloader coins are basically free on the officials when you reached elite rank. i did that on delta and i cover my ~150+ chunks base fine.

for example:
If i load here
![изображение](https://user-images.githubusercontent.com/47714084/94346595-5a690c80-0036-11eb-969c-db33d09efc1a.png)
my base lost energy and access to AE2, because the battery and controllers are located in the center
And accordingly, everything that comes in my way will die as I walk to center

**Comment by boubou19** [comment]
then use some anchors/anchor sentinels with overlapping chunks so you can load them from far.

**Comment by MotiasF33** [comment]
> 
> 
> then use some anchors/anchor sentinels with overlapping chunks so you can load them from far.

it amazing
need set anchor + sentiel on all long base every fcng chunk
![изображение](https://user-images.githubusercontent.com/47714084/94346829-0828eb00-0038-11eb-97f1-3852afdc87b9.png)

**Comment by MotiasF33** [comment]
Why can't you just change the GT ++ chunkloader and make it passive??

**Comment by boubou19** [comment]
if you want to suggest a passive GT++ chunkloader, go ask in https://github.com/alkcorp/GTplusplus/issues. Also by default, a player loads the chunks in a radius of 10 around him (may have been reduced a bit on the officials i don't know). But that means you can optimize the placements to a normal chunk loader grid, + chunk loaders with anchor sentinels crossing the grid network to make them propagate when you load the base from a corner. What you describe would be overkill.

**Comment by MotiasF33** [comment]
https://github.com/alkcorp/GTplusplus/issues/742
