### ISSUE TITLE
Quest Sodium Sulfide (#1652)

### ISSUE THREAD

**Issue by PanSzelescik** [GTNewHorizons/GT-New-Horizons-Modpack#6690]
#### Which modpack version are you using?
2.0.9.0
#### If in multiplayer; On which server does this happen? 
Singleplayer and Multiplayer
#### What did you try to do, and what did you expect to happen?
1 Sodium Sulfide Dust requires in Chemical Reactor 2 Sodium Dust and 1 Sulfur
In quest we must do 12 Sodium Sulfide Dust, which requires 24 Sodium Dust and 12 Sulfur, not 12 Sodium Dust and 24 Sulfur
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/26679785/94277687-30d2b700-ff4a-11ea-8db7-8f484069bf12.png)
![image](https://user-images.githubusercontent.com/26679785/94277706-37612e80-ff4a-11ea-85ec-87c9b130b712.png)
#### What do you suggest instead/what changes do you propose?
Change amounts

**Comment by Prometheus0000** [comment]
This was _already_ fixed in #6417, #6557. And now it looks like you messed it up again, by not using the latest version of the qb, the latest version of the pack, or checking for similar issues.

@PanSzelescik @Dream-Master
