### ISSUE TITLE
Thaumium and void scoop recipes are making GT scoop

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6692]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Craft a thaumium scoop and a void scoop from Magic Bees, as shown in their research pages. Expected those items to be crafted.
![image](https://user-images.githubusercontent.com/17787093/94287338-113d8d80-ff4e-11ea-815b-9d6de6ab74b1.png)
![image](https://user-images.githubusercontent.com/17787093/94288472-57dfb780-ff4f-11ea-8891-ac7c8c522fd5.png)

#
#### What happened instead? (Attach screenshots if needed)
A Gregtech scoop was crafted made of that material in both cases. This is an issue because repairing cannot be applied to Gregtech tools, and the void repair property is also lost. 
![image](https://user-images.githubusercontent.com/17787093/94288094-f28bc680-ff4e-11ea-834b-38fb5021bdd7.png)

These materials give a low durability to the Gregtech tool, so anyone that did the forbidden research in order to get a repairing void scoop would be short-changed.

This is also inconsistent with grafters, where a Magic Bees thaumium grafter and void grafter can be crafted as normal and enchanted with repair.
#
#### What do you suggest instead/what changes do you propose?
The Magic Bees scoops should be craftable out of those materials rather than the Gregtech scoop.

OR Alternatively - If it is necessary - Remove the research for both items to avoid misleading people.

**Comment by Rakdarian** [comment]
Suggestion, enchanted fabric I. The centre of each

**Comment by Prometheus0000** [comment]
The gt scoop is way better anyway, isn't it?

**Comment by GTNH-Afx237v7** [comment]
It’s modified via Minetweaker, don’t see any immediate cause why it reverts to a GT scoop? Could someone point me at the original recipe, didn’t have any luck finding it.

**Comment by KiloJoel** [comment]
> 
> 
> The gt scoop is way better anyway, isn't it?

Auto-repairing is a nice QOL thing over just lasting a really long time

**Comment by leagris** [comment]
> The gt scoop is way better anyway, isn't it?

No, the GT scoop is incapable of harvesting caterpillars from serum seeded leaf blocks.

**Comment by repo-alt** [comment]
That is probably a bug of GTA scoop, not being able to harvest caterpillars, but really butterflies are almost disabled anyway

**Comment by GTNH-Afx237v7** [comment]
Here is the script in question:

`mods.thaumcraft.Arcane.addShaped("MB_Scoop", <MagicBees:item.thaumiumScoop>, "ordo 10, terra 10, aer 10", [
[<gregtech:gt.metaitem.01:23330>, <minecraft:wool:*>, <gregtech:gt.metaitem.01:23330>],
[<gregtech:gt.metaitem.01:23330>, <gregtech:gt.metaitem.01:23330>, <gregtech:gt.metaitem.01:23330>],
[<ore:craftingToolWireCutter>, <gregtech:gt.metaitem.01:23330>, <ore:craftingToolHardHammer>]]); `

`mods.thaumcraft.Arcane.addShaped("MB_ScoopVoid", <MagicBees:item.voidScoop>, "ordo 20, terra 20, aer 20", [
[<gregtech:gt.metaitem.01:23970>, <minecraft:wool:*>, <gregtech:gt.metaitem.01:23970>],
[<gregtech:gt.metaitem.01:23970>, <gregtech:gt.metaitem.01:23970>, <gregtech:gt.metaitem.01:23970>],
[<ore:craftingToolWireCutter>, <gregtech:gt.metaitem.01:23970>, <ore:craftingToolHardHammer>]]); `

Regardless of what is the better scoop, the recipe is defined, yet yields a vanilla GT scoop.
Hence I believe the suggestion by @Rakdarian should work but needs testing.
