### ISSUE TITLE
Reflectors kill AE2 lategame

### ISSUE THREAD

**Issue by Houstonruss** [GTNewHorizons/GT-New-Horizons-Modpack#6693]
2.0.9.x
Neutron reflectors use wrenches to craft, and cause massive problems lategame for crafting fusion coils. (AE permanently stuck on simulating)
I suggest changing to assembler recipes with short times for the reflector parts.

**Comment by repo-alt** [comment]
As a short term solution the recipe may be changed, or, better, an assembler recipe added, but the underlying bug should be investigated as well.

**Comment by Houstonruss** [comment]
> As a short term solution the recipe may be changed, or, better, an assembler recipe added, but the underlying bug should be investigated as well.

It's a recursive crafting issue using the same wrench. Gt6 had special items for crafting called robot arms. They were unbreakable.

**Comment by GeicowithaBango** [comment]
neutron reflectors shouldn’t be craftable by hand, although, thats what a chad would do

**Comment by Prometheus0000** [comment]
Doesn't seem possible, putting them in a recipe causes it to just run after one is in there. You can also look at the advanced IC2 charging things for the same thing.

Maybe if someone made a 1:1 exchange for a stacking equivalent for the 2 neutron reflector parts.

**Comment by GTNH-Afx237v7** [comment]
Guess this was solved here?
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6719
As of 2.1.0.0 you can craft the reflectors in an assembler flawlessly
