### ISSUE TITLE
Wetware: Big chickens can't be automated for stemcells

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#6694]
#### Which modpack version are you using?
2.0.9.0

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
I was rebuilding parts of my Wetware line since the update broke most of it, and tried automating the big chickens I had available for stemcells.

#
#### What happened instead? (Attach screenshots if needed)
The disassembler only accepts big chicken eggs that have been held in one's inventory once, not the freshly harvested ones that have no stats yet.

![image](https://user-images.githubusercontent.com/8459776/94308881-7ce82080-ff77-11ea-9777-4708c7a0c9c5.png)

In addition, I get a broken texture.

#
#### What do you suggest instead/what changes do you propose?
Since the eggs don't stack anyway, we might just as well put in the stats straight away.

**Comment by botn365** [comment]
iirc this way of geting stem cells has been replaced with a other recipe

**Comment by MotiasF33** [comment]
@combusterf , new recipe stemcells
![изображение](https://user-images.githubusercontent.com/47714084/94332178-74293600-ffdb-11ea-97f3-dbf1bcf32a7c.png)
