### ISSUE TITLE
Recipe Removal: Unrealistic use of carbon in gunpowder recipe

### ISSUE THREAD

**Issue by Farlandercd** [GTNewHorizons/GT-New-Horizons-Modpack#6695]
The gunpowder recipe on page 2, 5 and 8 of NEI (mixer) needs to be removed. (Pure) Carbon is very inert and does not work well for gunpowder IRL. Primary Source: Cody's Lab + inherited chemistry knowledge

![](https://cdn.discordapp.com/attachments/181078474394566657/759147595385012244/unknown.png)

While I appreciate that this would break the automation of players setups I feel that those could very easily be remedied as there are two other alternatives already in the game; charcoal and coal.

I also want to address the concerns regarding my interest in this pack as being realistic. Others have notified me that there are lots of unrealistic features in this pack and that this should therefore not matter. I strongly disagree. From my understanding, this pack strives to give players a realistic experience. Why else do we have finite water for example? I also would like to point out that it is a poor argument to say that we shouldn't improve something just because a lot of other things are bad.

**Comment by leagris** [comment]
Realism in Minecraft is an oxymoron. Every other guy like you want to push its tiny bit of realism. Realism is impossible in Minecraft. You'd have to rewrite the whole game engine. Physics is fantasy, chemistry is fantasy. Player character can go swimming with open buckets and leave water with all buckets dry. Player character can go swimming with 2000 of anvils made of solid iron/steel. There is a dragon, improbable villagers of same undetermined sex and happy to pay you for wheat you stole from their own garden... Improbable Nether dimension with inconsistent thermodynamic. Everything is fantasy in this game. What kind of realism are you talking about.  This pack is about a fantasy to play chemistry that look like real world but is certainly not.

**Comment by interestingusernam3** [comment]
The carbon is a budget substitute for shungite meant to stop the mixture from prematurely detonating due to 5G influence.

**Comment by Rakdarian** [comment]
support

**Comment by MotiasF33** [comment]
The standard components for black powder are 75% potassium nitrate , 15% Carbon, and 10% sulfur

**Comment by MotiasF33** [comment]
![изображение](https://user-images.githubusercontent.com/47714084/94336643-52d14580-ffed-11ea-9521-5e87ef98c35c.png)

**Comment by MotiasF33** [comment]
or 
![изображение](https://user-images.githubusercontent.com/47714084/94336672-857b3e00-ffed-11ea-957f-a810670da8a3.png)

**Comment by boubou19** [comment]
what about just grinding it from creepers?

**Comment by Dream-Master** [comment]
mob farms more laggy

**Comment by Farlandercd** [comment]
> The standard components for black powder are 75% potassium nitrate , 15% Carbon, and 10% sulfur

That is incorrect. Carbon in itself is very inert. The 15% carbon you are referring to is in the form of coal or charcoal that actually has a fuel value.

**Comment by Farlandercd** [comment]
> Realism in Minecraft is an oxymoron. Every other guy like you want to push its tiny bit of realism. Realism is impossible in Minecraft. You'd have to rewrite the whole game engine. Physics is fantasy, chemistry is fantasy. Player character can go swimming with open buckets and leave water with all buckets dry. Player character can go swimming with 2000 of anvils made of solid iron/steel. There is a dragon, improbable villagers of same undetermined sex and happy to pay you for wheat you stole from their own garden... Improbable Nether dimension with inconsistent thermodynamic. Everything is fantasy in this game. What kind of realism are you talking about. This pack is about a fantasy to play chemistry that look like real world but is certainly not.
> 
> And I forget the cutest unrealistic Gregtech mechanic, where you can not place piles of the same dust material but different size, where rain will make machines explode but soaking same machine in deep water will not.
> 
> And so many unrealistic mechanic.
> 
> Recipes, mechanics of the game are here to balance, challenge, sink resources. It is all a patience puzzle, not a simulation of reality of any kind, or a very coarse one that games are made off.

Thank you for your well-written arguments. I do not agree that just because other things are not realistic we should not strive to be better.
