### ISSUE TITLE
[Iron Tanks Mod] Emerald Tank too fast to craft - Emerald processing nerf

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/GT-New-Horizons-Modpack#6696]
Modpack ver 2.0.9.0

Emerald tank - tank with highest capacity of 96B is easier to craft than diamond tank (64B) and faster to craft (using machines for materials) than gold one (48B), emerald lathe and cutting machine times should be nerfed, because there is no point in crafting diamond one, when you can get emerald, better one faster and for less energy.

For comparison:

Diamond rod in lathe time: 192 sec
Diamond bolts in cutting machine (lube recipe) time: 76.8 sec
Diamond screws in lathe time: 4.8 sec
Diamond Block to plate in cutting machine time: 384 sec

Emerald rod in lathe time: 4.5 sec
Emerald bolts in cutting machine (lube recipe) time: 1.8 sec
Emerald screws in lathe time: 0.1 sec
Emerald Block to plate in cutting machine (lube recipe) time: 9 sec

It will also affect upgrades for barrels and drawers.

If we cannot increase processing times, due to the fact that emeralds are softer than diamonds or something like that, we should revamp emerald tank recipe.

**Comment by Dream-Master** [comment]
Sorry i dont see the issues. why you crafting the tank by hand it use much more items. Sure diamond are more harder material. Maybe we can change emerald to titan or anything else idk

**Comment by Dream-Master** [comment]
The machine recipes using only tank from bc and a plate

**Comment by bedrill64** [comment]
As we discussed, good gating material will be aluminum, so it unlocks at EBF stage along with MV and HV GT Tanks.

I suggest we replace emerald screws with aluminum ones, so emerald plates are still required.

**Comment by bedrill64** [comment]
And about machine recipe, just put it at MV voltage.

**Comment by Regian24** [comment]
128B tank with Stainless Steel?

**Comment by Dream-Master** [comment]
https://discordapp.com/channels/181078474394566657/295669878222880769/759859700396982273
