### ISSUE TITLE
 torohealth-1.0.0 in GTNH server pack(Default)

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6698]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
single(Twitch) and private sever(default 2.0.9.0)
#
#### What did you try to do, and what did you expect to happen?
I tried to join the private server with the Twitch profile GTNH.
#
#### What happened instead? (Attach screenshots if needed)
I couldn't get a connection.
#
#### What do you suggest instead/what changes do you propose?
I checked and found that torohealth-1.0.0 was missing from the twitch profile. Please add it.

Edit: please remove  torohealth-1.0.0 from GTNH server pack(Default)

**Comment by boubou19** [comment]
torohealth is a clientside mod only, you can remove it from the server. There was a mistake in a previous server pack release with it inside

**Comment by yukieiji** [comment]
@boubou19 ok, Thank you

**Comment by ProsperCraft** [comment]
The real problem here, is that the Twitch/Curseforge/Overwolf version of the pack is missing Torohealth in the client.

The client version needs to be updated to include torohealth-1.7.10-1.0.0

**Comment by Dream-Master** [comment]
will upload a new version

**Comment by Prometheus0000** [comment]
No longer relevant
