### ISSUE TITLE
[f.request] quest search

### ISSUE THREAD

**Issue by NoX-programer** [GTNewHorizons/GT-New-Horizons-Modpack#6699]
#### Which modpack version are you using?
2.0.9.0
Better Questing v3.0.334-GTNH
#
#### What do you suggest instead/what changes do you propose?
Sometimes I need to find the quest by it's name, and it will be useful to make a search for it in quest window. For example, I hit "/" (slash) there (aka "linux commonly search button") and getting to search field where typing part of quest name (any) and result is updating while I typing. It's even better if that search will consider relevance: matches in the currently selected quest tab will be in top lines of result.

**Comment by Prometheus0000** [comment]
If you go into edit mode and then select edit and then add/remove quests, there's a search menu. Same thing if you go into a quest and select edit and requirements.

**Comment by NoX-programer** [comment]
That search looks fine, but it's also remains to:
* allow to use it without edit_mode and long click series - bring it up by a key on quests screen
* not only open the quest itself, but also select it's tab and zoom to it (maybe even glow effect, etc.)

**Comment by dvdmandt** [comment]
I have been thinking about this as well and have been looking at the code for it. I don't think it'd be too hard to achieve something useful.

**Comment by bedrill64** [comment]
You can't go into edit mode in servers, so this option would be nice addition.

**Comment by SKProCH** [comment]
Done

**Comment by bartimaeusnek** [comment]
@SKProCH we keep the issues open and tag them with fixedindev so dream can write a changelog for the next version
