### ISSUE TITLE
[Suggestion] Make boots of the comet and meteor more safe

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6702]
#### Which modpack version are you using?
2.0.9.0
#### What do you suggest instead/what changes do you propose?

Boots of the comet and boots of the meteor provide a fun alternative route to Electro-Magic Tools traveller's boots - less defence and vis discount but more mobility. The problem is that they both have very destructive abilities.

----

Boots of the comet freeze water, this destroys crops. I propose this part of their ability is disabled to allow people that have crops to safely use them.

Boots of the meteor make an explosion when they land, this explosion damages entities, which includes items on the ground and rockets. Making them very unsafe to use. I propose that the explosion part of this ability is disabled.

The abilities of the boots of the meteor are quite strong, so if the explosion is removed, they may be better suited as a more expensive HV item rather than being available as soon as infusion is.

----

Changes required:

Boots of the comet have a config option to disable the creation of ice.

The explosion for boots of the meteor can be disabled by removing line 378 in TXBootsEventHandler.java

**Comment by Rakdarian** [comment]
So infusion is "hv" first off, secondly comet boots are ridiculously fast as is.compare voidwalkers to them and voidwalkers pale. So they should be IV+. But if were not nerfing them they should definitely not lose the explosions since that's a big reason why we get them.

**Comment by GTNH-Afx237v7** [comment]
If the creation of ice is a config then feel free to disable it. The creation of explosions is not a config, however if you deem this to be too volatile maybe not use them near your rockets?

**Comment by KiloJoel** [comment]
Well you can get infusion in mv by trading for an ender eye with a villager, but I meant more like late hv, for example requiring an EV circuit.

In terms of wanting the explosion, that hadn't occurred to me, I just find it annoying and dangerous. My opinion of the role of the boots is to be able to fall quicker and jump further, but obviously that is only my opinion.

**Comment by Dream-Master** [comment]
Ok i don't want to change that. If you want to use this boots you have to handle the malus. 
When you work with crops use other boots or when jump around in your base.
Its the same with Hazmat suit. Dont use it when you not working on your reactor or with hazardous things or it will break very quickly.
