### ISSUE TITLE
[RailCraft] Anchor Sentiel

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6705]
#### Which modpack version are you using?
2.0.9.0qf4
#
### Sential can be pairing up to 25 chunks in one direction
Wiki says:  `It is possible to load up to a total of 9 chunks in a straight line in this way.`
But can be connect the passive anchor and the anchor centiel at a distance of 25 chunks with the same consumption of coins as for nine chunks.

**Comment by boubou19** [comment]
are you sure the 25 chunks are loaded tho?

**Comment by MotiasF33** [comment]
> 
> 
> are you sure the 25 chunks are loaded tho?

i think..yes :3

**Comment by MotiasF33** [comment]
Have ideas?

**Comment by MotiasF33** [comment]
https://github.com/MotiasF33/Railcraft/blob/mc-1.7.10/src/main/java/mods/railcraft/common/blocks/machine/beta/TileSentinel.java
Looks like the Sentinel has no limit?

**Comment by repo-alt** [comment]
25 is indeed the limit, and consumption depends on the amount of chunks loaded. Look at https://github.com/Railcraft/Railcraft/blob/b8d388c8988301282c3d8ea2dadcb24697ff2eac/src/main/java/mods/railcraft/common/blocks/machine/alpha/TileAnchorWorld.java#L178

**Comment by repo-alt** [comment]
What is the issue anyway?

**Comment by MotiasF33** [comment]
> 
> 
> What is the issue anyway?

It looks like it consumes 3x3

**Comment by Prometheus0000** [comment]
See https://railcraft.info/wiki/device:world_anchor

**Comment by repo-alt** [comment]
Look how it consumes fuel here: https://github.com/Railcraft/Railcraft/blob/b8d388c8988301282c3d8ea2dadcb24697ff2eac/src/main/java/mods/railcraft/common/blocks/machine/alpha/TileAnchorWorld.java#L268

**Comment by repo-alt** [comment]
Chunks are calculated here: https://github.com/Railcraft/Railcraft/blob/b8d388c8988301282c3d8ea2dadcb24697ff2eac/src/main/java/mods/railcraft/common/blocks/machine/alpha/TileAnchorWorld.java#L402

**Comment by MotiasF33** [comment]
everything is as it should be
