### ISSUE TITLE
[Client-crash] java.lang.NullPointerException: Rendering item

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6706]
#### Which modpack version are you using?
2.0.9.0qf4
#
### I pressed the arrow > of the duralumin recipe in the ABS and crash.
[crash-2020-09-27_15.28.01-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5288266/crash-2020-09-27_15.28.01-client.txt)

**Comment by Dream-Master** [comment]
@bartimaeusnek can you check what it is ?
or another gt++ issue ?

**Comment by bartimaeusnek** [comment]
No support for GT++ Machines. If this occurs in a regular machine, ill fix it, but not in the ABS.

**Comment by Dream-Master** [comment]
@MotiasF33 can you report this to GT++ repo ?

**Comment by boubou19** [comment]
got it happening right now by looking the Cerium cell recipe.
[crash-2020-09-27_15.35.23-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5288351/crash-2020-09-27_15.35.23-client.txt)

**Comment by MotiasF33** [comment]
> 
> 
> @MotiasF33 can you report this to GT++ repo ?

done
