### ISSUE TITLE
[Suggestion] Fix the fluid types in Magic Bees so you can use the capsules with more liquids.

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#6715]
How about fixing this?

Right now you can only use the specified liquids in magic capsules.
https://github.com/GTNewHorizons/MagicBees/blob/1.7.10-krypt/src/main/java/magicbees/item/types/FluidType.java

**Comment by Prometheus0000** [comment]
That would probably be a huge pain, and in my opinion not worth it since it looks like you have to add every liquid individually. Is there a reason to use them over cells?

**Comment by Ethryan** [comment]
They store 2 buckets and 8 buckets in each cell.

And i thought it would be possible to change it to import the forge fluid registry.

**Comment by Prometheus0000** [comment]
We have steel cells too. If it's not hard it's not like I mind though.
