### ISSUE TITLE
[Suggestion] Buff impure tears

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6716]
#### Which modpack version are you using?
2.0.9.0
#
#### What do you suggest instead/what changes do you propose?
Currently impure tears are not very useful, because the highest warp effect is at 80, and the tears struggle to get warp even below that level.

I propose that the percent chance of reduction from impure tears is kept, but that chance instead scales from 0% at 0 warp up to 100% at 100 warp.

This would mean, from 100 warp, it would take about 23 tears to get below 80, 71 tears to get below 50 and 194 to get below 15.

**Comment by yukieiji** [comment]
Impure tears is a temporary rescue item until pure tear or another warp removing item, not the main way to get rid of the warp hence the setup that.
In the case of your suggestion, it would take away the value of the other warp removing items...

**Comment by repo-alt** [comment]
It is quite useless now though

**Comment by bartimaeusnek** [comment]
The new tear is just a symptom of improper hard gating.

**Comment by KiloJoel** [comment]
> 
> 
> Impure tears is a temporary rescue item until pure tear or another warp removing item, not the main way to get rid of the warp hence the setup that.
> In the case of your suggestion, it would take away the value of the other warp removing items...

The pure tear is late IV right? I'd guess that the vast majority of people never get there, so the impure tear is the only method available during their time playing.

**Comment by KiloJoel** [comment]
Another thing I just thought about, the soul brazier can stop warp effects in an area while active, which could be a nice step to protect your base before pure tears. But the problem is that it is also gated by ichorium.

**Comment by repo-alt** [comment]
(and when you have ichorium, you almost at the same time get pure tear)

**Comment by yukieiji** [comment]
The GTNH also has numerous other items that have the effect of removing or protecting warp
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5643#issuecomment-590108550.
With those and the current Impure tear, though, I don't think it's difficult to unlock ichorium(The fastest release of the ichorium will accumulate 80 warp).

**Comment by Prometheus0000** [comment]
Your issue is irrelevant as they've already been changed. Try the new version to see. https://github.com/GTNewHorizons/WarpTheory/pull/7

**Comment by KiloJoel** [comment]
Sorry for creating this then, didn't see changes were already being made.

Though I am looking at what you've linked and I am struggling to see what the changes are, maybe I'm just being blind but could you help me out?

**Comment by KiloJoel** [comment]
Sorry, ignore me, I see it now
