### ISSUE TITLE
Impure tears are better with warping armour

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6717]
#### Which modpack version are you using?
2.0.9.0
#
#### What happened instead? (Attach screenshots if needed)
When eating an impure tear, the warp number that it calculates your percent chance of reduction from includes the warp from armour. This means that you have a better chance to reduce your warp when wearing it.

Having said this, the tears felt closer to a point of balance as a result, so I have created a sister issue proposing a buff for the tears.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6716#issue-710985944 
#
#### What do you suggest instead/what changes do you propose?
Calculate percent of reduction based only on your personal warp.

**Comment by Prometheus0000** [comment]
Irrelevant because of reason I stated in your other issue.

**Comment by KiloJoel** [comment]
Still an issue in the new version. Pull request https://github.com/GTNewHorizons/WarpTheory/pull/9

**Comment by Prometheus0000** [comment]
@KiloJoel This is fixed now, right?

**Comment by KiloJoel** [comment]
yes
