### ISSUE TITLE
Fps drop from jar binding seal

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6720]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Place a jar binding seal on a warded jar, to turn it into a bound jar.
#
#### What happened instead? (Attach screenshots if needed)
My fps dropped from more than 60 to about 15 as soon as I added the seal.

**Comment by bedrill64** [comment]
Tested and recreated, drop from 180 to 120 fps, was testing on the Eta server.
