### ISSUE TITLE
[Crash] Attempting growth grass between chunks causes a crash server

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6725]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
Eta

### Attempting growth grass at the border between loaded and unloaded chunk causes a server crash
![изображение](https://user-images.githubusercontent.com/47714084/94750956-fb85f900-038f-11eb-98d5-de7473f9fbde.png)

**Comment by bartimaeusnek** [comment]
Might have something to do with the Mixins for this... @mitchej123 @richardhendricks

**Comment by mitchej123** [comment]
Need a stacktrace @Dream-Master

**Comment by repo-alt** [comment]
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
	at net.minecraft.world.World.func_147439_a(World.java:703)
	at net.minecraft.block.BlockGrass.func_149674_a(BlockGrass.java:77)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:568)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:287)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:963)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mitchej123** [comment]
Did you do something to cause this, or was it grass ticking?  

func_147439_a = getBlock() if I recall.

Might be thermos interacting badly with hodgepodge which patches getBlock() to return if `!worldIn.blockExists()` https://github.com/GTNewHorizons/Hodgepodge/blob/master/src/main/java/com/mitchej123/hodgepodge/mixins/fixgrasschunkloads/block/MixinBlockGrass.java

If it happens again the fix can be disabled in the config on the server.

**Comment by Dream-Master** [comment]
Guess i need to have a Server and a Sp branch

**Comment by juanmuscaria** [comment]
Thermos adds a new local variable ["numGrowth"](https://github.com/CyberdyneCC/Thermos/blob/bae97f16f0fac984a56083769ef75cb8a8eb1812/patches/net/minecraft/block/BlockGrass.java.patch#L38) before the for loop, maybe the patch is capturing the wrong local variables because of that. That NPE in specific is caused when you try to get a block but the chunk is null/non existent.

**Comment by mitchej123** [comment]
*sigh*.  Thermos strikes again.  I'll look at a workaround for thermos, or just disable it if thermos is loaded.
