### ISSUE TITLE
Spacesuit Jetpack charging. 

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6729]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
prospercraft
#
#### What did you try to do, and what did you expect to happen?
Well i want to go to venus AGAIN, and i missed my quantum suit jetpack, so i put one on the spacesuit
Well turns out i cant charge it with HV-EV-IV-LUV battery buffers of ender io capacitor banks, wireless EU or RF.
Was told to craft the Energy Storage Module 1723,  but it is bugged too (bug report will be made in a min for that)
#

#
#### What do you suggest instead/what changes do you propose?
Allow the spacesuit to charge with EU from the wireless, or the ender io capacitor bank please, or gregtech battery buffers.

**Comment by Dream-Master** [comment]
@Devtron3D is this a galaxy space item? If yes we can change stuff in code.

**Comment by Prometheus0000** [comment]
I believe the 2 planets it's used on are GS so it should be as well.

**Comment by Devtron3D** [comment]
It is yes GC,
Atm, there is only one way to charge it, and I find that kinda silly.
Also ill be honest, it is strange that the quantum suit can not be upgraded to handle those two planets.
I am so rare on venus (about to build t6 rocket) but when I need something there I forget to put on the spacesuit, would be nice is there was something on, only venus that could upgrade the quantum suit to handle the environment.
