### ISSUE TITLE
Energy Storage Module 1723

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6730]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
prospercraft
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/3405825/94843917-b14b5900-041d-11eb-977a-5917815896c3.png)
I am trying to craft this, but the battery newly created in ME can not be used, and a full one just the same
I have been unable to craft it

#

#### What do you suggest instead/what changes do you propose?
add so an empty can be used
or since many have wireless energy at their base at later stages, allow a full one to be used

**Comment by GTNH-Afx237v7** [comment]
See Galacticraft Minetweaker file line 704 and 706:  <IC2:itemBatChargeRE:26>
Could work with :32767 as wildcard instead to allow any sort of charge. Will give it a try tomorrow.
