### ISSUE TITLE
Volumetric Flask 144mb 

### ISSUE THREAD

**Issue by Houstonruss** [GTNewHorizons/GT-New-Horizons-Modpack#6733]
I suggest either a recipie to make 1000mb flasks into 144mb ones, or one to create 144mb flasks directly.

**Comment by Prometheus0000** [comment]
You can use the device?

**Comment by Houstonruss** [comment]
Its frustratingly slow, and its heresy++!
I need 30k of these bad bois.

**Comment by Prometheus0000** [comment]
I thought they were supposed to be fast? Ask alk to make them faster? Or do other things while you wait? Or make them before you need them?

**Comment by Rakdarian** [comment]
If you need that many just use 1000 liter ones. You only need 4320 of those

**Comment by MotiasF33** [comment]
i make it like this
![изображение](https://user-images.githubusercontent.com/47714084/94867497-0309d880-044a-11eb-95b0-97416246de72.png)
and took it with my hands

**Comment by Houstonruss** [comment]
Yeah, Im not usinge++. If the thing worked right and you didn't still have to do it manually it would be fine.

Asking all to fix it is a joke.
Saying I need any 1000mb ones is like saying you can use iron for UV motors.

Why the discussion against qol? 
You guys are the reason nh2 started.

**Comment by MotiasF33** [comment]
kek

**Comment by MotiasF33** [comment]
Almost all molten metals can be placed to ic2 cell (with a capacity of 144mb)

**Comment by 0lafe** [comment]
An option for producing specific flasks would be great, but having some recipes would be ok. Probably a lot of recipes to cover all the sizes, but it would work. 

Maybe one for 
144
250
500
576

Maybe some for the ++ flasks too? 8k 16k 24k and 27k are pretty useful.

**Comment by Prometheus0000** [comment]
The optimal solution would be for it to work correctly (I thought you could pipe in and out), though I understand that alk isn't really working on gt++ right now. I also don't understand the need for so many, maybe try doing batch crafts? If you're using 30,000 at a time you can certainly afford it. Or make greater use of filling hatches automatically without using cells.

**Comment by Houstonruss** [comment]
@Prometheus0000 A batch craft is millions of items in UEV These little bottlenecks waste DAYS of game time!

**Comment by GeicowithaBango** [comment]
@Prometheus0000 you gonna tell us how to play the game?

**Comment by Prometheus0000** [comment]
? I have no idea what you're making, so 30k flasks sounds kinda excessive. And when I say batch, I mean more like 64, not 10000+x that. And if you batch craft things, generally there's some number that divides into 1000 so you can use the regular cells. Or the larger ones even. Also #6652 indicates that there may significant lag from using that many flasks/cells constantly. Also, how would batch crafting bottleneck things? It's one thing if you wait until you can make a giant amount, but 64 is hardly a lot at later tiers. And if it's a difficult to get fluid, you wouldn't need so many flasks.

**Comment by GeicowithaBango** [comment]
im afraid that you dont see the issue of this problem. For instance: batch crafting a few fusion coils will need a couple thousand flasks already -not just a stack of flasks  as you might have thought. crafting necessary components, needed in our example, will always be crafted one for one and not batch-wise because of the otherwise upcoming complexity managing all those recipe steps.... 
In general, I would highly suggest adding a shaped crafting recipe for flasks, the effort is minimal for such a quality of life change. every higher tier player will agree on that

**Comment by Prometheus0000** [comment]
I have no problem with recipes being added, I was just trying to suggest alternatives to using flasks. Personally, I'd probably either auto add fluids to a hatch or use big cells manually with large hatches.

**Comment by DuskNite** [comment]
That only really works if you have enough asslines lying around to have them run extremely dedicated recipes. I'm saying asslines coz that's likely where the volumetric flasks are being used at.

**Comment by Prometheus0000** [comment]
If you're doing UEV recipes, you can afford some dedicated asslines.

**Comment by 0lafe** [comment]
Lmao this is comedy

**Comment by botn365** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/321
