### ISSUE TITLE
Adding Zephyrus Server to ingame list

### ISSUE THREAD

**Issue by Irgendwer01** [GTNewHorizons/GT-New-Horizons-Modpack#6734]
Can u guys add Zephyrus to the ingame server list? its hosted in the netherlands, 20 player slots IP is gtnh.zephyrus-mc.com

**Comment by Houstonruss** [comment]
Has it been around a while? How long will this be up? How many players do you have?

**Comment by Dream-Master** [comment]
IrgendwerToday at 4:05 PM
https://discord.gg/CnrKQ2uM4B

**Comment by Dream-Master** [comment]
Open
