### ISSUE TITLE
[crash-client] java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6737]
#### Which modpack version are you using?
2.0.9.0qf4

**java.lang.IllegalArgumentException:** Could not get provider type for dimension 202, does not exist

[crash-2020-10-02_18.51.26-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5319048/crash-2020-10-02_18.51.26-client.txt)

**Comment by boubou19** [comment]
you used a gt teleporter?

**Comment by MotiasF33** [comment]
> 
> 
> you used a gt teleporter?

no i relog for setup a SmothFont, and when i'm join it crash me

**Comment by MotiasF33** [comment]
on the third attempt, launch is successful

**Comment by MotiasF33** [comment]
first crash-report
[crash-2020-10-02_18.43.15-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5319125/crash-2020-10-02_18.43.15-client.txt)

**Comment by Dream-Master** [comment]
liteloader ?

**Comment by MotiasF33** [comment]
> 
> 
> liteloader ?

Have it
Implementation-Version: 1.7.10_04

**Comment by glowredman** [comment]
Liteloader is very fragile in combination with Forge. I don't know a good way to tell why a collextion of Forge/Liteloader mods does not work, it's pretty much trial and error. Sometimes it's also random if the game crashes or not. I use Liteloader within GTNH, I don't use Smooth-Font though.

**Comment by MotiasF33** [comment]
> 
> 
> Liteloader is very fragile in combination with Forge. I don't know a good way to tell why a collextion of Forge/Liteloader mods does not work, it's pretty much trial and error. Sometimes it's also random if the game crashes or not. I use Liteloader within GTNH, I don't use Smooth-Font though.

after remove Smooth-Font all is everhything good..
it strange..

**Comment by boubou19** [comment]
liteloader is not supported anyways.

**Comment by MotiasF33** [comment]
Removing the liteloader solved crashes.
