### ISSUE TITLE
Industrial Material Press, high tik rate when running at high speed

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6739]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
prospercraft
#
#### What did you try to do, and what did you expect to happen?
Industrial Material Press gets a high tick rate when running at zpm power (maybe less power also, have not tested)
insertion for this was copper plates to foil. 
Remember when we get higher tiers like zpm, people craft 100k plates or more and other stuff all the time to create BIG recipes. 
![image](https://user-images.githubusercontent.com/3405825/94960525-571cc780-04f3-11eb-89f8-ada2debeee88.png)
Changed input and output bus to see if that made a difference in tests with the super ones with many slots, that did not help

**Comment by MotiasF33** [comment]
did not notice this, the material press is running on uhv

**Comment by zgggz** [comment]
![image](https://user-images.githubusercontent.com/64369015/108772163-b6947600-756d-11eb-86a7-294acee82732.png)
![image](https://user-images.githubusercontent.com/64369015/108772421-0a06c400-756e-11eb-84c2-20dd33aa9333.png)

The same problem with bender and assembler gt++ with high load.
UIV powered.

**Comment by Prometheus0000** [comment]
Ok, so? Go tell alk

**Comment by zgggz** [comment]
Yes, we must
