### ISSUE TITLE
GT power generation tick time.

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6741]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
![image](https://user-images.githubusercontent.com/3405825/94988086-faf58a00-056a-11eb-91c9-ffa2c991fc88.png)
I have started to notice in bases where people use a lot of single block generators that the chunk CPU time is relatively high.
After scanning several machines, I saw that power generators can be anywhere from 10k-100k ns.
This is even though the machines they are connected to are not running.

**Comment by GeicowithaBango** [comment]
this hurts my eyes.

**Comment by mitchej123** [comment]
Even if the machines aren't running, they're going to try and send power to all connected cables.  And if nothing is running, it's going to hit. every. single. cable.  which is awesome for CPU usage.

**Comment by Prometheus0000** [comment]
Is there anything to about this? Or just tell people not to do that?

**Comment by Devtron3D** [comment]
So many bases where people are HV/EV has a TON of single block generators
I myself had 20-30.
So telling people not to do that is not an option.

**Comment by Prometheus0000** [comment]
Really? I only had 4-5. Going to a multi is way more efficient after all.

**Comment by Methes** [comment]
Is this an issue only for singleblock generators or for other energy sources too?
Trying to think of how to prevent future lag in a large base - use battery buffers? Or diodes?

**Comment by repo-alt** [comment]
Any complex eu network, not divided by transformers, diodes or buffers will lag a bit in 1.7.10, so ideally, the less cable splitting there is, the better

**Comment by S4mpsa** [comment]
Battery Buffers are very nasty for TPS, probably due to how they have to scan their inventory all the time
Diodes work the best from what I have found.

**Comment by Methes** [comment]
I've seen people using wireless EU in the endgame. That works too?

**Comment by repo-alt** [comment]
If you don't have to care about losses, wireless is probably the best
