### ISSUE TITLE
Rocket quest change reminder

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6742]
When the changes are finished (unless they are?)

DCT -> nasa workbench (where should dct quest go then?)
Extended robot arm for NW can be part of that
Computer cubes (or whatever they're called) added to make the rocket quests (are these finished?)
Note about how using the schematics has changed
Note about rocket pollution (or will that be dialed back to something reasonable?)
Did anything else change?

**Comment by glowredman** [comment]
The rockets are done. The only thing that is still on my list are the voltage levels in the assembler, I didn't get any feedback that they are not doable though, so I assume tgey fit.

**Comment by Prometheus0000** [comment]
Are the computer cubes made in the assembler? Just reuse the same voltage for the plates/raw ingots, you should be fine with that.

**Comment by Dream-Master** [comment]
Nei Texture need a change for recipe but beside this all fine i guess.

**Comment by Prometheus0000** [comment]
I'm looking over this stuff, and you need to change at least some of it. Infinity rods in UEV emitters, means you can't make the T8 CC for T8 rocket without getting infinity, which requires T8 rocket.

**Comment by Prometheus0000** [comment]
I believe the problem is that both T3 and T4 are IV, so all the CCs T4+ need to have the parts and voltage tier reduced by one.

For example, the T4 CC currently requires LuV parts, so Assline, but the quest is in IV, pre-assline (and pre-LuV circuit assembler too). That said, I've never made one past T3.

BTW @Dream-Master is the pollution being scaled back or should I warn people to put their rockets 10+ chunks away from their base? The pictures on discord are crazy. https://discordapp.com/channels/181078474394566657/401118216228831252/759104734102683648

**Comment by glowredman** [comment]
> I'm looking over this stuff, and you need to change at least some of it. Infinity rods in UEV emitters, means you can't make the T8 CC for T8 rocket without getting infinity, which requires T8 rocket.

Okay, I'll change it

**Comment by glowredman** [comment]
Done: https://github.com/GTNewHorizons/Galaxy-Space-GTNH/commit/aacd623b4df1e86ef8f23194e940c1e2c39780c9

**Comment by Dream-Master** [comment]
but now we have 2 tiers at iv level and 2 of uv level ?

**Comment by glowredman** [comment]
Like it was before, the spreadsheet is wrong though (ore we redo the rocket tiering...)

**Comment by Prometheus0000** [comment]
In IV, also see the discussion on the GS channel
![image](https://user-images.githubusercontent.com/8517039/95249516-cb52b600-07e6-11eb-9aa5-c67838dea0a7.png)
![image](https://user-images.githubusercontent.com/8517039/95249546-d60d4b00-07e6-11eb-851e-8dd1dcea5b48.png)

**Comment by Dream-Master** [comment]
ok ill check in detail later.

**Comment by Dream-Master** [comment]
@Prometheus0000 but this can labled as fixed indev ?

**Comment by Prometheus0000** [comment]
Almost done, I need to change the heavy plate count _again_. _*cry*_

**Comment by glowredman** [comment]
Is there a quest for the Astro Miner? if yes, does it mention, that [you can only find the schematic for it after visiting the asteroids](https://wiki.micdoodle8.com/wiki/Astro_Miner)?

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/95251683-e5da5e80-07e9-11eb-9b2d-8f7fe84c0622.png)
You craft it from the T3 schematic though?

**Comment by Dream-Master** [comment]
i thought you can find all schematics in Dungeons. I add only conversion recipes if you found another one first.

**Comment by Prometheus0000** [comment]
@glowredman You only changed the voltages, did you read my other comment? You only changed the voltages, so lots of rockets (maybe all T4+?) are uncraftable when you're supposed to be able to.

> I believe the problem is that both T3 and T4 are IV, so all the CCs T4+ need to have the **parts** and voltage tier reduced by one.
For example, the T4 CC currently requires LuV parts, so Assline, but the quest is in IV, pre-assline (and pre-LuV circuit assembler too). That said, I've never made one past T3.

**Comment by glowredman** [comment]
@Prometheus0000 oh, I missed that. But changing the voltage levels of the CCs is also neccessary, because you have to be able to craft the Circuit Assembler at that tier, or am I wrong?

**Comment by glowredman** [comment]
@Dream-Master You can find all schematics in dungeons. Though te Astro Miner schematic is scpecial, because you can only find it on Mars after visiting the Asteroids

**Comment by Prometheus0000** [comment]
Yes, but I'm not sure why the last one needs to go down by two. Sledius' comment was not the clearest.

**Comment by glowredman** [comment]
I don't know either, but iirc the schematic circuits reflect that pattern.

**Comment by Dream-Master** [comment]
i can change this you get astro mine if you find a tier 4 schematic if that is a problem.

**Comment by Prometheus0000** [comment]
The items for CCs have been changed now. It seems changes to a private repo don't show up on the auto discord thing.
