### ISSUE TITLE
Bucket dublication on craft

### ISSUE THREAD

**Issue by rizemun** [GTNewHorizons/GT-New-Horizons-Modpack#6746]
#### Which modpack version are you using?
2.0.9.0 twitch 
#
#### What did you try to do, and what did you expect to happen?
crafting piece of mud via bucket of water + dirt for dirt armor. Expected 2x pieces of mud + returned bucket
#
#### What happened instead? (Attach screenshots if needed)
bucket duplicates. after craft i got 2 buckets (clay or iron, no matters) instead of 1 and expected 2 pieces of mud. These both are normal buckets, i can drop and use them, they are saved if i restart game. 
#
#### What do you suggest instead/what changes do you propose?
fix dupe behavior, to not clone buckets

**Comment by Prometheus0000** [comment]
Super duper duplicate, use search.
