### ISSUE TITLE
Manual processing of berries is more efficient than machine

### ISSUE THREAD

**Issue by EldrinnElantey** [GTNewHorizons/GT-New-Horizons-Modpack#6747]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Changing recipes or at least an explanation of why they are
#
#### What happened instead? (Attach screenshots if needed)
Berry juice such as raspberry juice can be created in two ways. Manual with soft mallet and automatic in the extractor. Why, when manually, one raspberry is enough to get juice, and through an extractor you need 4?
![image](https://user-images.githubusercontent.com/46845681/94993238-92c19b00-05a0-11eb-8187-51e6b25b901d.png)
![image](https://user-images.githubusercontent.com/46845681/94993254-b7b60e00-05a0-11eb-9826-6dec1c84a7ee.png)

#
#### What do you suggest instead/what changes do you propose?
Manual processing should be less efficient than machine processing. Through the extractor, one juice should be obtained from 1 berry, and with manual juice from 2 or 4.

**Comment by Dream-Master** [comment]
mh funny this make no sense. Will change recipes
