### ISSUE TITLE
add recipe for Forestry stamps

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#6751]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
MP/SP / Stone Legion
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happened instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?

By default there should be stamp recipes. I respect some servers might have their own features, etc. But that is their job to deal with that. By default there should be stamp recipes. In fact did we not talk about this years ago lol?

**Comment by Dream-Master** [comment]
There are recipes but in the client file

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/94999202-26529600-05b8-11eb-975c-1f5cae88c3ab.png)

just use zzclient on server

**Comment by Dream-Master** [comment]
@KaneHart
