### ISSUE TITLE
Forestry Bag Additions

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#6756]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
MP/SP / Stone Legion
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happened instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?

Some items to add to bags:

hunter
- random things
    - ectoplasm
- gt++
    - raw human meat
- tinker's
    - blue slime
- thaumcraft
    zombie brain
    essences
- ender zoo
    ender fragment
- forbidden magic
    shards
- minecraft
    skeleton skull
    zombie skull ...
- witchery
    hellhound head
    wool of bat
trackman
- gregtech
    block of charcoal

**Comment by Prometheus0000** [comment]
You can make a PR for it yourself you know? Just add the correct items to the config file in a forked repository and PR the changed file after testing it.
