### ISSUE TITLE
/foodlist

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6757]
#### Which modpack version are you using?
delta
#
#### If in multiplayer; On which server does this happen? 
2.0.9.0
#
#### What did you try to do, and what did you expect to happen?
tpye /foodlist 
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/95006682-5beb9380-0639-11eb-88a1-1c6881b36c74.png)

#
#### What do you suggest instead/what changes do you propose?
Can this command (/foodlist ) be allowed on delta?

**Comment by boubou19** [comment]
just as a workaround, just type `extra hearts` in nei. /foodlist has an option to clear your amount of unique food eaten, and i'm not a huge fan of letting ppl clear them by accident.

**Comment by MotiasF33** [comment]
> 
> 
> just as a workaround, just type `extra hearts` in nei. /foodlist has an option to clear your amount of unique food eaten, and i'm not a huge fan of letting ppl clear them by accident.

can add only `/foodlist size` to player permission
