### ISSUE TITLE
[KekzTech] LSC Wrong maintence multiplier 

### ISSUE THREAD

**Issue by Motias-git** [GTNewHorizons/GT-New-Horizons-Modpack#6758]
#### Which modpack version are you using?
2.0.9.0qf4

### Wrong maintence multiplier 
If has problems 2564eu/t
![изображение](https://user-images.githubusercontent.com/47714084/95016995-4c7f4100-065f-11eb-9fad-aecbd95ff123.png)
if all perfectly 5640 eu/t

**Comment by MotiasF33** [comment]
https://github.com/GTNewHorizons/KekzTech/blob/master/src/main/java/common/tileentities/GTMTE_LapotronicSuperCapacitor.java#L472

**Comment by Dream-Master** [comment]
feel free to change code @MotiasF33

**Comment by Prometheus0000** [comment]
What exactly is the problem?

**Comment by MotiasF33** [comment]
> 
> 
> What exactly is the problem?

having a problems consumes energy less than not having

but now all is good..
w8t next problems for test it

**Comment by Prometheus0000** [comment]
![2020-10-25_03 02 42](https://user-images.githubusercontent.com/8517039/97100879-a24b7580-166e-11eb-9e09-becd06ab133c.png)
The one on the left has 1 problem, the right, 3. The one on the right should have a higher passive loss due to more maintenance problems.
