### ISSUE TITLE
Wand focus: Nine hells, incorrect tooltip when using bat bombs

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6761]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
The base nine hells focus states (correctly) that it costs 2 ignis and 1 perditio vis. 
![image](https://user-images.githubusercontent.com/17787093/95025069-1487f600-067f-11eb-8a52-f25ad108b48e.png)

When it is upgraded in the focal manipulator with the bat bombs upgrade, the tooltip changes to say 1 ignis and 2 perditio. However the cost of the focus is still the same as the original.
![image](https://user-images.githubusercontent.com/17787093/95025096-3f724a00-067f-11eb-9782-6a1f7f2c76ec.png)

Wand after a cast with the focus:
![image](https://user-images.githubusercontent.com/17787093/95025117-66308080-067f-11eb-9794-c6690a607bf5.png)
#
#### What do you suggest instead/what changes do you propose?
Change the tooltip to reflect the actual cost of the nine hells focus with bat bombs.

**Comment by Nikolay-Sitnikov** [comment]
Fixed in Salis Arcana: https://github.com/rndmorris/Salis-Arcana/pull/276
