### ISSUE TITLE
splash brew of shifting seasons from witchery without making rituals corrupts chunks

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6764]
#### Which modpack version are you using?
2090QF4
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
A player wanted to use the quest reward from quest 2418 "The easy way of changing biomes" without performing any ritual. 
It corrupted the chunk as soon as the potion was thrown.

here is one of the crash reports made by the player loading the corrupted chunk
[crash-2020-10-05_18.59.39-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5329571/crash-2020-10-05_18.59.39-server.txt)

**Comment by Prometheus0000** [comment]
Never happened to me when I tested it. Maybe it's Thermos again?

**Comment by boubou19** [comment]
dunno if it's the potion who is somehow corrupted or if it's plain witchery issue, or thermos doing random stuff behind the scene.

**Comment by Prometheus0000** [comment]
Should I just change the quest reward then? It's not like it's critical or anything, and crashing is bad.

**Comment by Prometheus0000** [comment]
I changed the quest reward just in case, but it would be nice to know what's actually causing the problem.

**Comment by Dream-Master** [comment]
i guess hard to find out in a closed source mod (Witchery)

**Comment by draknyte1** [comment]
Please report it here: https://github.com/alkcorp/WitcheryExtras

See if it’s reproducible and see if thermos is involved. If I’m given the details, I can investigate further / fix it.
