### ISSUE TITLE
Arcanite Ingot in Fluid Extractor UV takes half time than receipt showes for MV

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#6767]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what did you expect to happen?
make fluid Arcanite out of ingots -> expect per tier stage x.5 time of receipt info (MV=300sec)
#
#### What happened instead? (Attach screenshots if needed)
with UV an operating time of 9 sec (=300*0.5^5)
#
#### What do you suggest instead/what changes do you propose?
9 sec operating time per ingot 
(comparing: dust to fluid with IV takes in Alloy Blast Smelter just 30 sec.)

![Fluid_Arcanite_02](https://user-images.githubusercontent.com/7759876/95222633-fc3be680-07f8-11eb-8451-4337af463074.PNG)

![Fluid_Arcanite_01](https://user-images.githubusercontent.com/7759876/95222595-f219e800-07f8-11eb-9f45-d13957f8e5fc.PNG)

**Comment by Prometheus0000** [comment]
Are you sure you're running it at UV? UV is several times the amount in the picture.

**Comment by Ngar1** [comment]
sorry, I was wrong - > machine is HV -> than every thing is ok...
