### ISSUE TITLE
Ender IO ender fluid conduites act weird

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#6768]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
private
#
#### What did you try to do, and what did you expect to happen?
i tried to connect single ender io ender fluid conduit to gregtech fluid pipe(plastic and titanium, tried both), expected it to connect to pipe
#
#### What happened instead? (Attach screenshots if needed)
it didnt connect
#
#### What do you suggest instead/what changes do you propose?
After some time investigating in this issueш i found out that in order for ender io pipe to connect to Gt pipes u need it to have 2 possible connections on the left of the screen you can see that pipe cant connect because it can have only 1 connection< while right pipe can have 2 so it connects
![image](https://user-images.githubusercontent.com/39595617/95254243-47b9b900-0828-11eb-8c62-c87f8cc7bbfe.png)

**Comment by Prometheus0000** [comment]
So what exactly is the problem, you can't use it if it's not connected to two things anyway?

**Comment by mitchej123** [comment]
GT pipes can "connect" to air, there's no reason they shouldn't be able to pre-connect to an EIO conduit.

I'll look into this and see if there's an easy fix without any unintended side effects.

**Comment by draknyte1** [comment]
Why not fix it in EIO vs a special case in GT?

**Comment by mitchej123** [comment]
Because the bug is on GT's side.  Notice how the EIO conduits connect, but not the GT pipes?

**Comment by bombcar** [comment]
I think this is because GT sees the conduit as "a block" but not one that can carry fluid. I can't get a pipe to connect to the side facing stone.

It works fine with "fluid conduit" (the gravity flow ones)
