### ISSUE TITLE
Gregtech "Sense" tool incorrect right click behaviour

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6769]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Right clicked a cotton plant using a gregtech sense. Expected it to harvest them in a 5x5 area.
#
#### What happened instead? (Attach screenshots if needed)
It harvested the plant that was right clicked, but broke all the plants around it in a 5x5 area as well as 2 layers of blocks below
![image](https://user-images.githubusercontent.com/17787093/95269018-6fad1a80-0830-11eb-82d9-eee5671f5940.png)

**Comment by KiloJoel** [comment]
I've just realised this is a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5956#issue-603645363. Should I close this?

**Comment by Dream-Master** [comment]
i doing this for you :)
