### ISSUE TITLE
HoloInventory

### ISSUE THREAD

**Issue by Aleks233** [GTNewHorizons/GT-New-Horizons-Modpack#6774]
#### Which modpack version are you using?

2.0.9.0
#### If in multiplayer; On which server does this happen? 
One.
#
#### What did you try to do, and what did you expect to happen?
Look at the items in the box.
#
#### What happened instead? (Attach screenshots if needed)
HoloInventory doesn't display the contents in the container. The button doesn't respond. Is it the wrong way I use it.
#
#### What do you suggest instead/what changes do you propose?
Did I use it wrong?

**Comment by Prometheus0000** [comment]
Did you put on the glasses?

**Comment by Aleks233** [comment]
What glasses?
Do I have to wear glasses to see it?

**Comment by Aleks233** [comment]
I thought the game has this function. I think wrong    -.-
thanks

**Comment by Prometheus0000** [comment]
Yes, there will be a quest to get them in the first 2 tiers or so.

**Comment by Aleks233** [comment]
OK

**Comment by Aleks233** [comment]
I now
