### ISSUE TITLE
Shadowmetal tools are not craftable, meaning mage's mace focus also isn't

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6775]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I tried to craft a shadowmetal sword using the gregtech shadowmetal ingots. This is an ingredient for wand focus: mage's mace.
#
#### What happened instead? (Attach screenshots if needed)
The crafting recipe shown by nei doesn't work with the gt ingots, only the tainted magic ones, which are not obtainable.
Nei:
![image](https://user-images.githubusercontent.com/17787093/95371449-20b7c180-08d2-11eb-8aa5-70636881227c.png)

![image](https://user-images.githubusercontent.com/17787093/95371373-0847a700-08d2-11eb-8ec0-ed5fab1e0b9f.png)

This is the case with all of the shadowmetal tools from Tainted Magic

Creatively spawned shadowmetal ingots are also automatically converted to gregtech ones.

#

**Comment by Dream-Master** [comment]
Ingots to craft a sword. We need to gregifying it.

**Comment by repo-alt** [comment]
Mages mace is also potentially useful to get blood for crimson cloth (with Bloodlust focus upgrade). Looks like nobody ever bothered with it (Which tells something about the size of the pack and the efforts of some people to _add more mods_)

**Comment by narwhalfire** [comment]
I just bothered with it and encountered this. We may be few but we exist.

**Comment by KiloJoel** [comment]
> 
> 
> Mages mace is also potentially useful to get blood for crimson cloth (with Bloodlust focus upgrade). Looks like nobody ever bothered with it (Which tells something about the size of the pack and the efforts of some people to _add more mods_)

I would say it's probably more to do with the fact that forbidden research drives ~95% of people away until they can get pure tear, at which point there are much better weapons available.

**Comment by KiloJoel** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7472
