### ISSUE TITLE
[RFC] Allow maintenance hatch to go on top of EBF

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#6776]
2.0.9.0

I would like to suggest that the maintenance hatch could also be placed on the top layer of the EBF.

When the controller, energy hatch, and maintenance hatch all must (should) be dedicated to one EBF, the design possibilities for wall sharing, overclocking, dedicated fluid hatches, and additional input busses are getting really limited. 
Also when comparing to most other multis where the maintenance placement is mostly unrestrained.

This is obviously a suggestion based on my personal progression (currently trying to design a flexible 2x2 or 2x3 EBF setup), but I see this as a nice QoL change that would give some more design freedom for this essential multi.

**Comment by shawnbyday** [comment]
The other thing to keep in mind with this is recipes that require the output hatch to be on the bottom of the EBF to get the return product (Platinum Processing) makes this even more of a requirement.
