### ISSUE TITLE
Enhance cleanroom speed/operation to be dependent on internal size

### ISSUE THREAD

**Issue by AtomicGrog** [GTNewHorizons/GT-New-Horizons-Modpack#6778]
#### Which modpack version are you using?
# 2.0.9.0

Presently the cycle time for a cleanroom is fixed at say 1% every 5 mins regardless of the internal size

#### What do you suggest instead/what changes do you propose?

Change the recycle time to be calculated base on internal volume, making 3x3x3 maybe faster than at present and larger say 13x10x13 significantly longer and maybe needing higher tier operation to speed up in line with other machine tiers.

**Comment by LewisSaber** [comment]
Its better to make speed depend on height of at as if you make it wider you also add mire filter casing so speed of it dont decrease, a nice addition would be making it speed up recipes if provided with argon

**Comment by Glease** [comment]
Cleanroom usually don't involve an argon atomsphere. Plus, there will be Steves visiting with oxygen gears off.

**Comment by MotiasF33** [comment]
The need for air supply can be added in input hatch? 😄 
e.g. 2l each 5s

**Comment by Glease** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/344b00012aca59c4b0372185e41f529baffa5da3

Somehow I commited directly onto the master branch without a proper PR, so I will say what I have done and see what you guys think. If you think my commit is horrible please just say that and I'll revert it.

1. Cleanroom can now be overclocked. It will overclock as if it is a machine that will nominally use 40EU/t, so e.g. given 1 MV hatch it will not overclock, even when it will only consume 4 EU/t at 100% efficiency. It overclocks once if given 2 MV hatch or 1 HV hatch. It refuse to work if given only one LV hatch.
2. It will take 225 seconds per block height to reach full efficiency. so e.g. Standard 3x4x3 cleanroom take 450 seconds to reach 100% (down from 500seconds), 5x5x5 cleanroom take 675 seconds, 5x4x5 take 450 seconds.

I have think about the possibility of driving up the EU/t cost if the x/z dimension is too big, but I'm not sure about the numbers so I didn't include it in that commit.

**Comment by Prometheus0000** [comment]
So OCing will make it go up to 100% faster? And still only consume 4EU/t at 100%? Won't this make having a door open cause it to go down to 99% and right back up though? So you can leave it open all the time? Is there a similar problem with maint issues, or does that just cap it?

Only height, not width?

**Comment by Glease** [comment]
The base EU consumption will go up as well, e.g. overclock twice (require the use of an EV hatch or 2 HV hatch) it becomes 64EU/t at 100%.
The door problem is indeed there, but I think if you feed it a higher voltage, well the fan would be working so hard that a hole practically doesn't matter. Afterall, the base EU consumption does go up. This can be considered somewhat a compensation for that.
A low height makes logisitics hard so an 15x4x15 box isn't that appealing, but we can factor that width in if you think the otherwise.

**Comment by Prometheus0000** [comment]
I'll let other people comment, I switched over to multis ASAP.

**Comment by Glease** [comment]
Seems like there is no objection/discussion whatsoever. Let's tag this as fixed.
