### ISSUE TITLE
Enchantment 'Dispersed Strikes' from thaumic tinkerer has no benefit

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6784]
#### Which modpack version are you using?
2.0.9.0
#
#### What happened instead? (Attach screenshots if needed)
The dispersed strikes thaumonomicon entry states "the damage to a mob on the first hit will be multiplied, but the damage on successive strikes to the same mob will be decreased." But what it actually does is normal damage on the first hit then less on subsequent hits.

This is a snippet from the code in ModEnchantmentHandler.java.
![image](https://user-images.githubusercontent.com/17787093/95525009-d23a1e00-09ca-11eb-921b-626e98da45e5.png)
 The best case is successiveStrikes being 0, which results in the damage being multiplied by 1, then divided by 1.

This calculation also doesn't use the level of the enchantment at all.
#
#### What do you suggest instead/what changes do you propose?
Change the calculation to something like:

event.ammount *= 1 + ((successiveStrikes + dispersedStrikes * 0.4) / 5);
event.ammount /= (1 + (successiveStrikes * 2));

That would mean 1.48x damage on the first hit, 0.56x damage on the second, though I'm not sure about the numbers for a good balance, just giving an example.

**Comment by Glease** [comment]
See GTNewHorizons/ThaumicTinkerer#10
