### ISSUE TITLE
about GT disassembly NBT data removal

### ISSUE THREAD

**Issue by NoX-programer** [GTNewHorizons/GT-New-Horizons-Modpack#6786]
#### Which modpack version are you using?
1.7.10-2.0.9
#
#### What do you suggest instead/what changes do you propose?
If it will be decided to cut DNBT via vote https://discordapp.com/channels/181078474394566657/465207956745486336/764106712176394260 I suggest not to delete parts of well working code, but add a config options to disable DNBT separately for:
* Components (piston, robot arm, etc.)
* Machines (bender, multi controllers, etc)
* Tools (electric screwdriver, electric wrench, etc.)
* Others (covers, multi blocks, etc)

**Comment by Prometheus0000** [comment]
Put your comment in #4782
