### ISSUE TITLE
Void miner VS small ore

### ISSUE THREAD

**Issue by zgggz** [GTNewHorizons/GT-New-Horizons-Modpack#6787]
Void miner dig only ore blocks and he skip small ores. So we need to dig infiniti catalist, bedrockium, awakened draconic by simple miner. At UHV we need to move it every couple hours. It is really annoing.

**Comment by GeicowithaBango** [comment]
void miners dont mine ore blocks afaik

**Comment by botn365** [comment]
they dont they but smal ores to get calculated in what ores it will produce

**Comment by Prometheus0000** [comment]
So it does produce the things they said it doesn't?

**Comment by Prometheus0000** [comment]
I can confirm that small ores don't seem to be picked up. The thing is, there's no recipes for what to do with small ores, even if they were picked up. You'd have to place them back down and break them.

So we need 1) small ores to be collected as well 2) add maceration+forge hammer recipes for small ore

Or grab the normal ore when it would grab a small ore, this would probably be easier, and a better solution.

**Comment by GeicowithaBango** [comment]
@Prometheus0000 hold up, what did you test exactly?

**Comment by Prometheus0000** [comment]
Does it already do this?
![image](https://user-images.githubusercontent.com/8517039/95877006-aeb40200-0d41-11eb-82b7-173d2421bdc2.png)
Maybe I didn't wait long enough+no sorting in infinity chest

**Comment by Prometheus0000** [comment]
I mean, I have 17k Yttrium and 192 AwDr from a T3 VM UMV using oganesson for testing, that seems kinda off?

**Comment by GeicowithaBango** [comment]
we never experienced that problem

**Comment by Prometheus0000** [comment]
I also have...3 titanium

**Comment by Prometheus0000** [comment]
So after restarting and running a VM I got this
![image](https://user-images.githubusercontent.com/8517039/95894318-ea0cfb80-0d56-11eb-8326-318644560994.png)
So it's clearly not even, but it does give you ores instead of small ores.

After running a normal miner, it seems to give a similar ratio too, so I don't think there's a problem.
