### ISSUE TITLE
New feature request: Vehicles, Weapons and more

### ISSUE THREAD

**Issue by NikitaGamer64** [GTNewHorizons/GT-New-Horizons-Modpack#6789]
I wonder if GregTech: New Horizons would become even better if it got expanded. But in case even less players will be able to play due to their weak computers, these features would be optional for them.
First of all, it's the vehicles. Maybe add something like Mr. Crayfish's Vehicle Mod, but to prevent the perpetuum mobile, vehicles in there should need energy: gasoline, electricity, kerosene and etc. Have their own speed, and they can't be had as an item, only as an entity. And they would have their own HP which depletes when you crash. And roads & traffic are needed.
Weapons: turrets, explosives, guns, melee weapons of all ages and times. And I mean, more various!
Building: maybe it's compatibility between Forge Microblocks, Carpenter's Blocks, Chisel, various building blocks, Architecture Craft and Forge Multipart! Carpenter's Blocks' various shapes can be combined together like the puzzles! That means you can place several materials on the one part! Also, Architecture Craft shapes will be added to Carpenter's Blocks!
Also maybe some ways to control the gravity and even control/scan more things with new programs... blocks, entities...

**Comment by Prometheus0000** [comment]
You can't make features optional and still have them in the pack, not to mention the huge effort to add recipes and fix things. Plus lag from adding tons of stuff

**Comment by glowredman** [comment]
The AT Launcher has optional mods but that launcher is not supported as far as I know

**Comment by Prometheus0000** [comment]
You can't distribute optional mods in a zip file without editing the filename or putting them in a different directory. And this would break compatibility with all servers if you had them but the server didn't. There's a list of optional mods on the wiki already I think too.

**Comment by NikitaGamer64** [comment]
Now I understand that optional mods are not possible as you said. But what about vehicles and weapons at least?

**Comment by Prometheus0000** [comment]
If people want it it can be added, it just can't be optional as part of the distributed pack. It depends on the amount of lag, effort, and Open Source-ness though. Given how many open issues there are, especially about changing existing things/balance, I don't think anyone has any time for it.

Not to mention that I don't think there's a need for vehicles or weapons. The weapons would either be weaker than crossbows or super-OP, and we have options for getting around already that don't require flat areas that vehicles likely do.

**Comment by NikitaGamer64** [comment]
In New Horizons, it is possible to build any town or even city you like, but the town is not a town without vehicles
