### ISSUE TITLE
Magic mirror (Thaumcraft) cannot transfer raw firestone (Railcraft).

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/GT-New-Horizons-Modpack#6793]
#### Which modpack version are you using?
2.0.9.0QF4

#
#### If in multiplayer; On which server does this happen? 
Stonelegion

#
#### What did you try to do, and what did you expect to happen?
I'm using magic mirror to transfer mined ores with ore drilling rig. In nether there are Railcraft firestone ores. The drilling rig harvested them into "raw firestone" and while it was piped into magic mirror, it just keep jumping at both side but not actually transfered.

#
#### What happened instead? (Attach screenshots if needed)

https://youtu.be/SCjE9n7A1vo

If I break the magic mirror at the sender side, I can pick up the firestone to my inventory. But I cannot pick it up if I don't break the mirror and it will keep jumping at there.

**Comment by yukieiji** [comment]
I think ThaumCraft's MagicMiror item sending was Intradim, so I think the fact that items can be sent is a bug in itself.,,
Isn't MeldingMirror(can be sent by Interdim) the one sending the item in the Nether, not MagicMirror?
