### ISSUE TITLE
Inserting music discs into GT++ "Sir Mixalot" via hopper causes server crash

### ISSUE THREAD

**Issue by Beetrootmonkey** [GTNewHorizons/GT-New-Horizons-Modpack#6799]
## Description
Using a hopper (and propably other similar means) to insert music discs into GT++'s "Sir Mixalot" (called "SuperJukebox" in code) causes a server crash. Easily reproducable in both SP and MP. [Also reported this issue at GT++'s repo.](https://github.com/alkcorp/GTplusplus/issues/747)

## Current Behavior
The moment the hopper tries to insert the disc, the server crashes with an IndexOutOfBoundsException.

## Steps to Reproduce (for bugs)
 1. Place Jukebox
 2. Place a hopper on top
 3. Put a random vanilla/modded music disc into the hopper

## Context
[Crash report (SP)](https://pastebin.com/HvwfuNp7)

## Game Environment
Modpack used: GT:NH 2.0.9.0

Also include:
 * GT-PlusPlus: 1.7.05.68
 * Gregtech version: 5.09.33.52
 * IC2 version: 2-2.2.828a-experimental
 * Java version: 1.8.0_261
 * Operating System: Win 10 Pro

### Misc Info
 - [x]    Single Player?
 - [x]    Multi Player?

**Comment by Prometheus0000** [comment]
Report at the GT++ repo

**Comment by boubou19** [comment]
https://github.com/alkcorp/GTplusplus/issues/747

**Comment by Beetrootmonkey** [comment]
I did report it at the GT++ repo, but since that wasn't exactly clear from what I wrote, I updated my description to include that piece of information (and also a link to the issue).

**Comment by shawnbyday** [comment]
"Baby got back-up?"

**Comment by draknyte1** [comment]
Fixed in https://github.com/GTNewHorizons/GTplusplus/pull/50.
