### ISSUE TITLE
TFFT should be able to use other glass types

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6801]
#### Which modpack version are you using?
2.0.9.1a dev
#
It would look fancier if we could use other glass types. We could also restrict the upgrades by glass tier if we wanted (though I probably couldn't do that part). Would anyone care if it was just any glass? Or just glass tier EV+?

**Comment by GTNH-Afx237v7** [comment]
Upgrading glass tier to allow higher storage field blocks sounds good to me.
What seems odd though is the tiering of the circuits for the storage field blocks:
Tier 1 and 2: HV circuits
Tier 3: EV circuits
Tier 4: IV circuits
Tier 5: ZPM circuits
If someone were to make the change to the glass tiering maybe the circuit tiering can be adjusted as well?
My suggestion for glass-tiering:

Tier 1 and 2 storage: IC2 reinforced or Nickel reinforced borosilicate 
Tier 3 and 4 storage: Tungsten reinforced borosilicate or thorium-yttrium
Tier 5 storage: chrome reinforced borosilicate
