### ISSUE TITLE
Quest ID 1462 Thermal Cloth

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#6802]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Quest still calling for 24 Enchanted Fabric. Doesn't use Enchanted Fabric to craft thermal jump suit. Would LOVE to see it require Enchanted Fabric (: but would settle for the quest being updated to remove the Enchanted Fabric if you don't need it anymore.

**Comment by Prometheus0000** [comment]
Already fixed, update your version

**Comment by Prometheus0000** [comment]
Well, when the next version comes out for real.
