### ISSUE TITLE
[Possible Bug] Hoe of Growth too high durability loss.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/GT-New-Horizons-Modpack#6809]
Ver: 2.0.9.0, Server: Eta

Using a Hoe of Growth to till dirt uses 5 durability per dirt tilled, which reduces its effective durability from 1500 to 300. Using it as bonemeal on crops uses only 1 durability. Thaumonomicon description says that using it as bonemeal should take more durability than normal use. The values are possibly switched around.

See Thaumonomicon entry:
![image](https://user-images.githubusercontent.com/9555787/95710957-0ed37700-0c62-11eb-806a-bd804b25b65c.png)

**Comment by MotiasF33** [comment]
But we don't have a thaumcraft source(

**Comment by bedrill64** [comment]
Still an important bug, not resolved.
