### ISSUE TITLE
switch fluid canner 617 with mercury 616 quest

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#6815]
#### Which modpack version are you using?
2.0.9.0

#### What happened instead? (Attach screenshots if needed)

Quest 616 Mercury is before quest 617 Fluid Canner
![image](https://user-images.githubusercontent.com/1111474/95885423-83e79f00-0d7d-11eb-8627-26bdbe6a1924.png)

#### What do you suggest instead/what changes do you propose?

The Fluid Canner quest should be before the Mercury quest because it needs the fluid canner anyway

**Comment by Prometheus0000** [comment]
It doesn't though? You can use a ULV tank.

**Comment by Prometheus0000** [comment]
@leagris ^
