### ISSUE TITLE
Replace WAing bees with EQUIVALENT industrial apiary upgrade

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6817]
See title, should save some TPS.

Should have tiers between LV (x2) to UV (x256).
Probably will override existing production upgrades, and not stack, but maybe not, can you WA something more with 2?

'if someone did the math on the energy and output, I'd look into adding an upgrade to make them equivalent to what was there before with the WA' <- Mitch

**Comment by botn365** [comment]
yes if you have 2 WA next to a hive it wil produce 2x the amount

**Comment by botn365** [comment]
at best should stack to 5x becous thats the most you can place next to it and stil have access to the inventory

**Comment by Prometheus0000** [comment]
Transvector interface

**Comment by Prometheus0000** [comment]
37.5 EU for basic IA

normal prod upgrade
+20% prod, +40% EU per prod upgrade
~4.3 prod, 553.5 EU for 8. This is multiplied by the chance of the item (like a comb) and the speed of the bee and apiary type
#
WAs use 3A in block mode, 6A in TE mode. IA are TEs, so 6A. Can use 6 sides if min-maxing with transvector interfaces.
LV=2x, MV=4x, HV=8x, etc speed multiplier

32EUx6A=192EU, 192EUx6(sides)=1,152EU (or are we going to have individual ones that stack?)
128EUx6A=768EU, 192EUx6(sides)=4,608EU
512EUx6A=3,072EU, 192EUx6(sides)=18,432EU
2048EUx6A=12,288EU, 192EUx6(sides)=7,3728EU
8,192EUx6A=49,152EU, 192EUx6(sides)=29,4912EU
32,768EUx6A=196,608EU, 192EUx6(sides)=117,9648EU
131,072EUx6A=786,432EU, 192EUx6(sides)=4,718,592EU
524,288EUx6A=3,145,728EU, 192EUx6(sides)=18,874,368EU


speed 1x2(multiplier for LV)x6(WAs)=12xspeed (If it's individual ones, it's +(multiplier) per tier for each upgrade)
speed 1x4(multiplier for MV)x6(WAs)=24xspeed
speed 1x8(multiplier for HV)x6(WAs)=48xspeed
speed 1x16(multiplier for EV)x6(WAs)=96xspeed
speed 1x32(multiplier for IV)x6(WAs)=192xspeed
speed 1x64(multiplier for LUV)x6(WAs)=384xspeed
speed 1x128(multiplier for ZPM)x6(WAs)=768xspeed
speed 1xx256(multiplier for UV)x6(WAs)=1,536xspeed

**Comment by Prometheus0000** [comment]
I'll let mitch decide.

**Comment by Houstonruss** [comment]
Buffing apiaries is a slippery slope to bees being viable...idk guys.

**Comment by Prometheus0000** [comment]
@mitchej123 When you get around to it, after NEI and CFB I guess?
