### ISSUE TITLE
Fused Quartz is way too blast resistant for how inexpensive it is

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6819]
It also makes the fancy reinforced stone blocks useless.

This is the code, it looks like 2000->20? would be better, though I'm not sure what the else does.
![image](https://user-images.githubusercontent.com/8517039/96022964-b1852480-0e1f-11eb-8289-71a0b2600cd0.png)

The fancy reinforced stone blocks also seem like they might need to scale better, since apparently even bronze stops a nuke
There are several
![image](https://user-images.githubusercontent.com/8517039/96023184-088af980-0e20-11eb-8ad6-b4a5432e864d.png)
Also see #5229

**Comment by GTNH-Colen** [comment]
This is a great way to break lots of peoples setups for no real reason.

**Comment by Prometheus0000** [comment]
Why would it? Do they explode things on purpose?

**Comment by GTNH-Colen** [comment]
> Why would it? Do they explode things on purpose?

If people build setups relying on these being blast proof (Which is standard in modded MC) then it sets them up for a bad time. Thinking wither farms, nuclear reactor contains etc.

**Comment by mitchej123** [comment]
We've changed plenty of other stupid shit that breaks people setup for less reason.  It's way too blast resistant for how early/easy it is to make, and completely renders the other reinforced blocks useless.  That's an invalid reason for not properly balancing it with what's available in ic2 and GT.

**Comment by GTNH-Colen** [comment]
> We've changed plenty of other stupid shit that breaks people setup for less reason. It's way too blast resistant for how early/easy it is to make, and completely renders the other reinforced blocks useless. That's an invalid reason for not properly balancing it with what's available in ic2 and GT.

Then you should change the recipe, not the blast resistance if it's too easy. I don't even see why this is a semi-important issue tbh.

**Comment by mitchej123** [comment]
It's used in other recipes, those aren't OP.  The OP part is the blast resistance.

**Comment by Prometheus0000** [comment]
It's a super easy change, especially if we don't change anything else.

**Comment by ScriptedPiky** [comment]
We can also inform users with an announcement or something to tell them that this *very* important change to them, is being affected and some setups will need to be addressed. This can make other forms of the reinforced blocks finally useful. Although, I do believe that, beyond a certain point, the reinforced stones become relatively pointless due to no real block exceeding beyond a nuke (200 blast resistance might protect you), up until someone blows up a Draconic reactor where the highest possible reinforced stone is viable for such an occurrence.

**Comment by Prometheus0000** [comment]
We can also add it to the join/start game message as seen in https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/774069cf4fbe2e17a074f43d11960d93b7cde7bc

Honestly, maybe we should add major changes to that more often?

**Comment by Prometheus0000** [comment]
Currently:
Block					=Hardness, Blast Resistance
Reinforced Glass		=?, ? (normal block, waila says 5, 108)
Obsidian(altered by IC2)=50, 60 (waila says 50, 12)
Reinforced Stone		=80, 180 (waila says 80, 108)			Can contain 1 chamber reactor with 1x thorium fuel rods explosion with 2 layers, 3 for quad
Bronze PRS				=75, 250								Can contain 1 chamber reactor with 1x uranium fuel rods explosion with 1 layer, 3 for quad, 3 for 6 chamber quad
Steel PRS				=100, 350								Can contain all nuke explosions with 2 layers
Titanium PRS			=150, 400
Tungstensteel PRS		=200, 500								Can contain all nuke explosions with 1 layer
Naquadah PRS			=300, 700
Fused Quartz			=?, 2000 (waila says 0.5, 3)
Neutronium PRS			=500, 100000 (waila says 750, 2500)

Suggested changes:
Reinforced Stone		=80, 150 (if we can change it)
Bronze PRS				=75, 200
Steel PRS				=100, 225
Titanium PRS			=150, 300
Tungstensteel PRS		=200, 375
Naquadah PRS			=300, 500
Fused Quartz			=?, 20
Neutronium PRS			=500, 1000

Maybe even reduced more, since you don't exactly fill reactors entirely with rods, but the explosions also don't seem to increase beyond a certain point, either

We can also change tooltips and add it to the fused quartz+reinforced stone. See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/GTNewHorizons/CustomToolTips.xml

**Comment by Prometheus0000** [comment]
If no one else disagrees I'll make a PR?

**Comment by Prometheus0000** [comment]
Dream, why did you change the resistance https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/738b5097e65579db6f516ef04afa588e24f7a485 without changing the tooltip, they're all different now. And why not round them instead of weird numbers like 666.7? Is this a float number thing?

Though I based my tests on what actually occurred ingame, I just need to redo the numbers.

**Comment by Prometheus0000** [comment]
New numbers:
					=H, BR(actual BR, changed BR)
Bronze PRS 			=75, 250(250->200)
Steel PRS 			=100, 350(333.4->325)
Titanium PRS 		=150, 400(500->450)
Tungstensteel PRS 	=200(666.7->575)
Naquadah PRS 		=300, 700(1666.7->700)
Fused Quartz 		=?, 2000(2000->20)
Neutronium PRS 		=500, 100000(4166.7->2000)

**Comment by Prometheus0000** [comment]
See https://github.com/GTNewHorizons/EnderIO/pull/22, https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/123, https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/124, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6840.

**Comment by Prometheus0000** [comment]
Also #6846.

**Comment by Anarack** [comment]
What about the modular turrets hard walls? there blast resistance isn't high enough to do anything right now either.

**Comment by Prometheus0000** [comment]
If you mean the turret bases, that can be changed in the config. The hard walls are at https://github.com/OpenModularTurretsTeam/OpenModularTurrets/tree/1.7.10/src/main/java/openmodularturrets/blocks/misc , and go from ```this.setResistance(10.0F);
        this.setHardness(10.0F);``` to ```this.setResistance(80.0F);
        this.setHardness(80.0F);``` which is sufficient to deal with mobs most likely? Try it ingame?
