### ISSUE TITLE
Displaced inventory hologram

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#6822]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Privat Server
#
#### What did you try to do, and what did you expect to happen?
Displaced inventory hologram
#
#### What happened instead? (Attach screenshots if needed)
Suddenly, the inventory hologram has shifted north of the chest
![image](https://user-images.githubusercontent.com/46845681/96352753-e1aa1d00-10d6-11eb-914d-c4b43aa6534a.png)

#
#### What do you suggest instead/what changes do you propose?
How to fix it?

**Comment by EldrinnElantey** [comment]
Found the reason for this
![image](https://user-images.githubusercontent.com/46845681/96352822-8dec0380-10d7-11eb-88d1-c72fdd26c20e.png)

**Comment by Prometheus0000** [comment]
And the reason is? And does this mean you have no problem anymore?

**Comment by EldrinnElantey** [comment]
The same reaction to a armor stand from biblio craft

**Comment by EldrinnElantey** [comment]
> And the reason is? And does this mean you have no problem anymore?

I am wearing the glasses for holographic inventory and the numbers have shifted back. This happens if there is an armor rack from biblio craft or Traveler's Gear nearby.
