### ISSUE TITLE
Crash when creating a pocket plane (Thaumic horizons)

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6824]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
-Created a node containing 192 ordo (using node catalyzation)
-Created a planar vortex using the node
-Threw a primordial pearl into it to create a pocket plane
#
#### What happened instead? (Attach screenshots if needed)
The game crashed as the pocket plane was created. Relaunching and opening the world again resulted in it crashing again instantly.

Crash log
https://pastebin.com/CB6aUBEF

When creating a pocket plane with a smaller ordo node, it didn't crash but the pocket plane had snow (the non-full block) that was one block above the ground level, this meant giving a block update to any of the snow caused a chain-reaction of a large amount of the snow disappearing due to not having a block underneath it.

**Comment by Prometheus0000** [comment]
[crash-2020-10-21_23.32.14-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5419875/crash-2020-10-21_23.32.14-client.txt)
This is likely related, though I was nowhere near the planar vortex or doing anything related to it. And I don't have a pocket plane set up. BTW it's from Thaumic Horizons.

**Comment by bartimaeusnek** [comment]
@KiloJoel try starting the instance with ```-Xss 1G``` removing the node in creative and restarting the game without that flag.

**Comment by KiloJoel** [comment]
Is that just to help me with accessing the world or for testing? It was a creative world I was testing in so I just deleted the pocket plane dimension

**Comment by KiloJoel** [comment]
https://github.com/GTNewHorizons/ThaumicHorizons/pull/11
