### ISSUE TITLE
[Thaumcraft] [Thaumic Tinkering] Osmotic Enchanter infusion doesn't consume Spellbinding Cloth.

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/GT-New-Horizons-Modpack#6831]
Ver.: 2.0.9.0, Server: Eta

As in the title, Spellbinding Cloths that are placed on pedestals are not used during infusion, it 'sucks' them but they are left on pedestals after the infusion process. They are not consumed and can be reused later.

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/96631264-17702100-12e4-11eb-809b-3bbf9910d02e.png)
Not a bug, surprise feature. We can change the recipe if it's that big a deal, but I don't really know if it's worth it.

**Comment by Methes** [comment]
Or the thaumonomicon entry could be changed to mention this feature (not a bug).
