### ISSUE TITLE
After world join, a Thaumcraft client background thread scanning IC2 items accounts for substantial GC pressure.

### ISSUE THREAD

**Issue by Uristqwerty** [GTNewHorizons/GT-New-Horizons-Modpack#6833]
In a memory profile, thaumcraft.client.gui.MappingThread scanned 40,000,000 combined IC2 Item and Block instances, generating multiple temporary String and char[] objects for each. Once it finished, F3's Used Memory is climbing an order of magnitude slower.

I don't know if there's an easy way to alleviate some of the workload, but I expect it could greatly improve lag spikes in the first 5? 10? 30? minutes after opening a save.

I've attached a few memory profiler snapshots. I started the profile shortly after the game's output log said I joined the world, though apparently the game wasn't finished as the loading screen stayed up a while after, so the difference between the first and last snapshot (shortly after actually getting in to the world, and shortly after MappingThread stopped performing work) is more relevant here than the absolute numbers; and I didn't have it logging char[] allocations so the true cost isn't directly apparent. I used VisualVM 2.0.4 (now a standalone project, rather than bundled with the JDK), if other software/versions have trouble with the snapshots. Also, I let the game run unpaused for most of the profiling, rather than sitting on the pause menu where *only* the background thread would be doing substantial work.

[GTNH-profile-snapshots.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5403298/GTNH-profile-snapshots.zip)

or, if a screenshot is good enough,

![image](https://user-images.githubusercontent.com/569596/96478713-03ee8880-1206-11eb-9fa2-063fe42ab96f.png)

(there's a near-duplicate subtree for java.lang.String.substring (int) lower down, plus all the types not counted in the profile)

**Comment by GTNH-Afx237v7** [comment]
This could very well be the collection of the Thaumcraft aspect information for all blocks and items.
Wonder if this could be handled differently, like start with a blank file and add to this file once the block/item has been scanned? But then again every block/item is assigned a certain combination of aspects based on a particular logic... that’d be a puzzle for someone who can code...

**Comment by Uristqwerty** [comment]
Small followup, the thread in question seems to be indirectly @SideOnly(Side.CLIENT), and its results only used by Thaumcraft itself to show which items you've scanned for a given aspect. It's also used by a NEI plugin, though, and I haven't bothered to check other mods.

So I'd expect that it's actually causing NEI results to be missing for the first in-game-day-or-so of play after launching the pack, and if the algorithms themselves cannot be optimized (there might be an O(n²) lurking about, relating to the number of times it fetches item ids?), at least prioritizing scanned items would be a gameplay enhancement (and skipping unscanned items outright, lazily inserting them on first scan, would be a performance optimization but take substantially more work)

**Comment by Glease** [comment]
`generateItemHash` problem has been fixed with the addition of my TC4Tweaks mod. It's currently included by default only in dev branch, however you could just go to curseforge and grab one if you want to stick to stable branch.
