### ISSUE TITLE
Electric implosion compressor problem with neutronium blocks.

### ISSUE THREAD

**Issue by zgggz** [GTNewHorizons/GT-New-Horizons-Modpack#6835]
#### Which modpack version are you using?
gtnh
#
#### If in multiplayer; On which server does this happen? 
Prospector craft
#
#### What did you try to do, and what did you expect to happen?
I turn on my compressor and he remove 5 neutronium blocks at middle. He work until server restart. Then he write uncomplete structure.
## What do you suggest instead/what changes do you propose?
![image](https://user-images.githubusercontent.com/64369015/96495759-ef83ad80-1250-11eb-8477-3fc68ea960e2.png)

**Comment by GTNH-Colen** [comment]
I think this is fixed? I recall bot saying they managed to get a working version at least @bartimaeusnek

**Comment by bartimaeusnek** [comment]
Should be fixed in next version.
