### ISSUE TITLE
programmed circuit not work

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6837]
#### Which modpack version are you using?
delta
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?

https://drive.google.com/file/d/1SG2hiDR3tO3TbrcRGufgFJz-hYPSEm6W/view?usp=sharing
#
#### What happened instead? (Attach screenshots if needed)
the programmed circuit not work and the centrifuge don't give me Sticky Resin
#
#### What do you suggest instead/what changes do you propose?
fix it

**Comment by Glease** [comment]
See #5243

**Comment by AtomicGrog** [comment]
Seems to work reliably (tested 6 times in a row...) if machine placed fresh, circuit added and a few seconds wood added. suspect machine remembers last used recipe and wont swap to circuit equivalent as it will always see the wood first after (supposition).

**Comment by Prometheus0000** [comment]
? I grabbed the items out of creative and it immediately didn't work. Regardless of the order of the items.

**Comment by AtomicGrog** [comment]
https://www.dropbox.com/s/am80atu786404lq/rubberextract.mov?dl=0

Pretty crappy movie but it demonstrates that my steps work.

This is on a public 2.0.9.0 server and if you follow standard process ie. wood left, circuit right etc. it fails every time. if you process 1 piece of wood badly it fails every time thereafter.

**Comment by Prometheus0000** [comment]
After ekzoi's comment in the non-closed issue I was able to get it to work by changing the order of the circuit, though it's still bad.
