### ISSUE TITLE
LootBag (AE Good) dupe bug

### ISSUE THREAD

**Issue by kaziu687** [GTNewHorizons/GT-New-Horizons-Modpack#6838]
#### Which modpack version are you using?
2.0.9.0QF4

#
#### If in multiplayer; On which server does this happen? 
My own public server

#
#### What did you try to do, and what did you expect to happen?
When you open LootBag (AE Good), for example with 100% luck you have a chance to receive stacked ME Storage Cells. When you put it in AE and insert items into that you can simply unstack cells. Contents will remain on every cell.

#
#### What do you suggest instead/what changes do you propose?
Do not give stacked cells.

**Comment by kaziu687** [comment]
It occurs on appliedenergistics2:item.ItemBasicStorageCell.16k

**Comment by Ethryan** [comment]
Maybe change it to the storage component instead.

**Comment by Glease** [comment]
With above patch the lootbag will no longer give a stack of 4 cells. It will give 4 stack, each with one cell instead.

**Comment by Prometheus0000** [comment]
We don't close until a release with the fix.
