### ISSUE TITLE
Opis broken on eta (And epsilon?)

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6848]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
Opis doesn't work on eta and I believe also epsilon. This means that lag sources can't be found easily, leading to very low tps the majority of the time.
#
#### What do you suggest instead/what changes do you propose?
I know that this is a known problem, but I saw there was no issue about it, and it has been a problem for a long time.

I believe this should be treated as high priority because it has a significant impact on gameplay on the majority of the official servers. It is a source of great frustration and personally would be by far the best quality of life increase if addressed.

This info may help
![image](https://user-images.githubusercontent.com/17787093/97056105-165b2000-1580-11eb-8a3c-8cc97f950444.png)

**Comment by boubou19** [comment]
all the officials are set up identically. Dream looked into it twice already without finding why only Delta has a working opis.

**Comment by KiloJoel** [comment]
The issue was found! It was a conflict with bugtorch. Thanks @boubou19 and @GTNH-Colen
