### ISSUE TITLE
[2.0.9.0] Chisel gui broken

### ISSUE THREAD

**Issue by RaidhoSketch** [GTNewHorizons/GT-New-Horizons-Modpack#6850]
![image_2020-10-24_162412](https://user-images.githubusercontent.com/73392166/97082856-5ae4cb00-1615-11eb-8905-aa05b07c9406.png)

Broken gui when trying to use chisel (unable to place blocks, misplaced boxes etc.) - verified in creative to be an issue with diamond and obsidian chisels too. Auto-chisel works, but it needs the final product first...

Any suggestions for what is causing this and how to fix it?

**Comment by leagris** [comment]
Bug with your texture pack overriding with an obsolete texture.

Open your resource-pack zip file and delete `assets/chisel/textures/chisel2GuiScroll.png`
