### ISSUE TITLE
UHV tier, rocket, raw bio medium, and many other things are still impossible

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#6854]
There are currently two bugs preventing players from legitimately going to UHV and above, those two bugs being Raw Bio Medium/UEV Bio Mainframes are impossible to make pre-TCetiE/UEV, and the Legendary X quests still requires Pluto to be found, but that cannot be done because the UHV rocket requires a UHV circuit assembler, that also requires UEV/Bio Medium.

What can be done to address this? First off, the Legendary X trigger should be moved from Pluto (T7) to Triton (T6), a planet where Small SpPu ore can be naturally found. Second, the TCetiEis Fucus Serratus Petri Dish (see photo down below) and unknownwater need to be renewable in some fashion. As it currently stands, it is theoretically possible to get TCetiE seaweed before going to the T8 planet if only **TCetiEis Fucus Serratus Petri Dish** and **unknownwater** and **Tcetieisfucusserratusfluid** were possible to obtain. Thirdly, Mysterious Crystal should have a small ore recipe found on Enceladus. While this isn't gating or stopping players, Mysterious Crystal is a rather annoying material to obtain without the usage of bees. However, this small ore could be within the intentions of being picked up via Void Miners, and as such, you could have 32 possible ores, but it can go from 40-100 Y levels, as to make it a sudo-random occurrence.

**Compiled list:**
- Change Legendary X quest Pluto planet trigger to Triton planet trigger
- Make TCetiEis Fucus Serratus Petri Dish, Tcetieisfucusserratusfluid, and unknownwater possible to create and renewable in some fashion
- Make small Mysterious Crystal ore generate in Enceladus

**Comment by Prometheus0000** [comment]
Why is lqx needed for uhv again?

**Comment by 0lafe** [comment]
Doesn't enceladus have MC through planet stone?

**Comment by Prometheus0000** [comment]
I think piky wants it from ore _as well_. Is the ender quarry not fast enough? Maybe add it to a later planet instead?

Were you referring to this about needing UEV circuits?
![image](https://user-images.githubusercontent.com/8517039/97117098-fcccec00-16d7-11eb-836c-a9d62f448061.png)
![image](https://user-images.githubusercontent.com/8517039/97117165-53d2c100-16d8-11eb-936f-1bfd28848e1e.png)
![image](https://user-images.githubusercontent.com/8517039/97117176-5e8d5600-16d8-11eb-9aab-22221de25a0f.png)
They've already been dialed down, it's just not in 2.0.9.1a dev, like changing from uranium plates. You can't see it or the log because it's private. @ScriptedPiky

**Comment by ScriptedPiky** [comment]
> Why is lqx needed for uhv again?

UHV Superconducter needs Awakened Draconium/D*, but that can only be obtained via completing the questline.

> Doesn't enceladus have MC through planet stone?

Yeah, Enceladus actually has a 50% chance to give a whole dust from one snow layer. However, there is only **one** snow layer that generates. The planet also naturally generates meteors, but then again, who is going to spend hours farming meteors on the surface for a marginal amount.

Oh, they have been dialed down? Well, that would solve quite a couple of problems, however, I still would appreciate if Bio Medium was made to be possible pre-T8/UEV in some way, shape, or form.

**Comment by botn365** [comment]
uhv SC got changed to use D instead of D* unless somone changed it back to D*

**Comment by Prometheus0000** [comment]
> UHV Superconducter needs Awakened Draconium/D*, but that can only be obtained via completing the questline by getting Draconic Cores.

What? It doesn't use it as far as I can see?
![image](https://user-images.githubusercontent.com/8517039/97121990-d10e2e00-16f8-11eb-9db2-515592b6d944.png)
![image](https://user-images.githubusercontent.com/8517039/97121991-d9666900-16f8-11eb-991b-a237059b6b52.png)
Which part uses it? It's an ore found on T8 planets?
![image](https://user-images.githubusercontent.com/8517039/97122004-f602a100-16f8-11eb-9682-b379838594a6.png)

> Yeah, Enceladus actually has a 50% chance to give a whole dust from one snow layer. However, there is only one snow layer that generates. The planet also naturally generates meteors, but then again, who is going to spend hours farming meteors on the surface for a marginal amount.

Maybe it could be added to another planet's dust? Or the stone dust from enceladus? It'd probably have to replace something though.

> Oh, they have been dialed down? Well, that would solve quite a couple of problems, however, I still would appreciate if Bio Medium was made to be possible pre-T8/UEV in some way, shape, or form.

I'm going to guess that this isn't going to be changed. Why is it needed before you need to make UEV circuits? And why would you need to pre-uhv?

**Comment by ScriptedPiky** [comment]
Wait, it isn't required anymore? Huh, I must be thinking entirely of a different version, since I am now realizing that the current Zeta dev version has this particular thing changed. The only thing I can now think of that may require D* is the D* coils themselves, but they aren't necessarily mandatory for UHV+ or Neutronium cooking (though they can provide a coil overclock). Well, that solves that problem then.

> Maybe it could be added to another planet's dust? Or the stone dust from enceladus? It'd probably have to replace something though.
Yeah, that or a small ore. Small ores would technically allow it to be picked up by Void Miners, thus allowing it to be reasonably renewable.
>I'm going to guess that this isn't going to be changed. Why is it needed before you need to make UEV circuits? And why would you need to pre-uhv?
You need Bio Medium to get to UEV in the *first place*. However, pre-UHV, I'd imagine that you can get a lot of stuff done (excluding UHV circuit assembler) in that tier. But if the T8 rocket requires, say, a UHV circuit assembler, then UEV is *still* impossible.

**Comment by Prometheus0000** [comment]
> The only thing I can now think of that may require D* is the D* coils themselves

On the UHV SC quest:
![image](https://user-images.githubusercontent.com/8517039/97122358-aec9df80-16fb-11eb-84a0-2f9ff081c0fd.png)
Unless this is what you mean by 'aren't necessarily mandatory'.

> You need Bio Medium to get to UEV in the first place. However, pre- or even standard UHV, I'd imagine that you can get a lot of stuff done (excluding UHV circuit assembler) in that tier. But if the T8 rocket requires, say, a UHV circuit assembler, then UEV is still impossible.

The tier of the rocket T8 voltage and items went down by 2 instead of 1 for the rest. Look closer at the numbers.

**Comment by botn365** [comment]
this was changed for a long time and is in the main version

**Comment by ScriptedPiky** [comment]
I wasn't entirely sure about the UHV base superconductor at the time, but that is quite neat to know now.

>The tier of the rocket T8 voltage and items went down by 2 instead of 1 for the rest. Look closer at the numbers.
this was changed for a long time and is in the main version

That's not what's shown on the official Zeta Dev version that Zeta server is on. Unless it's in a future version.

Speaking of the future version, I was shown by Prometheus about https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6742 that I didn't previously know about, whoops. Until then, I await for the Zeta server to be updated.

**Comment by glowredman** [comment]
> That's not what's shown on the official Zeta Dev version that Zeta server is on. Unless it's in a future version.

I changed that temporarily to be in line with the (at that time wrong) spreadsheet. This is changed back in newer versions of GS.

Also, Unknown Crystals are obtainable from a T8 planet. I don't know, if they are also obtainable from its dust.

**Comment by ScriptedPiky** [comment]
> Also, Unknown Crystals are obtainable from a T8 planet. I don't know, if they are also obtainable from its dust.

Unknown Crystals are also obtained from Enceladus (T5) from fallen crystal meteors, but I didn't think they would be obtainable on a T8 planet (presumably Barnarda C), and the dust is obtainable from a one-sheet layer of snow on Enceladus via centrifuging the dust. But yes, you can make Unknown Crystals in an autoclave from the dust.

**Comment by glowredman** [comment]
I'll look into it, maybe I can make it thicker

**Comment by ScriptedPiky** [comment]
There are also two other alternatives if we wish to explore them in addition to the snow layers, the first being adding in small ores within the range amount of 2-6? And or replacing one of the dusts in the Enceladus Stone Dust recipe with Mysterious Crystal Dust.

**Comment by glowredman** [comment]
Before (Enceladus Ice, Packed Ice, Enceladus Subsurface Block):
![grafik](https://user-images.githubusercontent.com/35727266/98025100-90559980-1e09-11eb-8400-5029f258a371.png)

After (Enceladus Snow, Enceladus Ice, Enceladus Subsurface Block):
![grafik](https://user-images.githubusercontent.com/35727266/98024856-35bc3d80-1e09-11eb-98e9-3b5ad6a8d1c4.png)

Yes, the former Enceladus Ice is the same block as Enceladus Snow. I just changed the name to make it more fitting. The new Enceladus Ice will have the same usages as the Enceladus Snow (PR incomming). I can't easily just change the thickness of the top layer, but I think this is a good solution.

**Comment by ScriptedPiky** [comment]
That seems like a reasonable solution for solving Mysterious Crystal problems for now. Should we tinker with the Enceladus Ice and Stone recipe outputs a little further or leave it as is? Otherwise, this is a great change.

**Comment by Prometheus0000** [comment]
This is all done now, right? You confirmed the other stuff @ScriptedPiky ? I think adding small ores to a later planet would be good, but that can go into another ticket, as I don't know how to do that.

**Comment by ScriptedPiky** [comment]
Yeah, it should be about done. The other stuff like rocket tiers & unable to get bio medium are fixed, though Bot's changes to growth and bio medium still remain somewhat uncertain as physically tested, but that shouldn't matter as much. And yes, the small ores could be in a different ticket, and the extra ice layers will help greatly mitigate the mysterious crystal problem for now.
