### ISSUE TITLE
Bug with BC Builder/FMB/Frames

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#6856]
#### Which modpack version are you using?
2.0.9

Putting forge or PR parts down seem to break the BC builder in different ways. 

FMB stuff like covers/strips/nodes/etc seem to have some mapping issues when placed on the sides of the block as seen here in the before/after shot
![2020-10-25_19 17 39](https://user-images.githubusercontent.com/21280852/97121739-d4a0b580-16f6-11eb-80eb-f06d1530cc3f.png)

Frames from MCFrames seem to be broken in some ways as well. They're built fine, however if there are FMB blocks within them, it will only place the FMB blocks, and not the frame. The FMB rotational effect will also be present
![2020-10-25_19 31 05](https://user-images.githubusercontent.com/21280852/97121971-a7550700-16f8-11eb-98f6-a4eba955c30a.png)

**Comment by boubou19** [comment]
Can you replicate it on an untouched GT:NH 2.1.0.0 version? because afaik, we don't have MCFrames on the pack, and microblock list got changed.

**Comment by GTNH-Afx237v7** [comment]
It is part of ForgeRelocation-0.0.1.4-universal.jar
![grafik](https://user-images.githubusercontent.com/64365566/110586358-68d55b80-8172-11eb-9305-b865f18cc8f0.png)

**Comment by boubou19** [comment]
the more you know

**Comment by 0lafe** [comment]
i do believe this is still an issue in the current release

**Comment by mitchej123** [comment]
BC's closed source and isn't wildly used; this is unlikely to be fixed.

**Comment by glowredman** [comment]
> 
> 
> BC's closed source and isn't wildly used; this is unlikely to be fixed.

BuildCraft is not closed source: https://github.com/BuildCraft/BuildCraft/tree/7.1.x

**Comment by mitchej123** [comment]
> > BC's closed source and isn't wildly used; this is unlikely to be fixed.
> 
> BuildCraft is not closed source: https://github.com/BuildCraft/BuildCraft/tree/7.1.x

My recollection is that it's visible source, but we can't redistribute modified versions.

**Comment by leagris** [comment]
> My recollection is that it's visible source, but we can't redistribute modified versions.

Custom license https://github.com/BuildCraft/BuildCraft/blob/7.1.x/LICENSE

**Comment by mitchej123** [comment]
Ok, looks like I misremembered.  Anyway, unlikely anyone's going to pick this up.   If someone does plan on working on it feel free to re-open.  Otherwise leaving it "wont fix"
