### ISSUE TITLE
Planar gateway doesnt work on moon dim

### ISSUE THREAD

**Issue by anoldshoe** [GTNewHorizons/GT-New-Horizons-Modpack#6857]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
MMCC's GTNH Ironman
#
#### What did you try to do, and what did you expect to happen?
Placed a gateway in moon and linked portals. portal from moon to pocket dim works correctly. portal from pocket dim to moon sends to overworld dimention, 4 chunks to the north, 3 to the east of the planar vortex. also noted that the coords are the same(moon gate and the spawn from pocket to moon). Tried: server restart, re-linking portals, and re-placing gateway blocks.
#
#### What happened instead? (Attach screenshots if needed)
sends from pocket dimention to overworld.
#
#### What do you suggest instead/what changes do you propose?
in my opinion, it might be set to default to send to overworld. maybe there is not variable set for specific dimentions? Reasoning is, the coords for the portal at the moon, and where it mistakenly sends me in the overworld are the same X Y Z.. just different dim

**Comment by KiloJoel** [comment]
https://github.com/GTNewHorizons/ThaumicHorizons/pull/17
