### ISSUE TITLE
HardcoreEnderExpansion Void Chest BUG !!!

### ISSUE THREAD

**Issue by ENNISHIBUYA** [GTNewHorizons/GT-New-Horizons-Modpack#6861]
#### Which modpack version are you using?

#First Version ~ 2.0.9
#### If in multiplayer; On which server does this happen? 

#Server & Single Game
#### What did you try to do, and what did you expect to happen?

#I tried to use it and found this bug. I hope to fix it!
#### What happened instead? (Attach screenshots if needed)

#Not a good time. In this case, a movie is a good choice.

https://www.nicovideo.jp/watch/sm37730708
(My youtube channel banned ! so I upload on other sites.)
#### What do you suggest instead/what changes do you propose?

#Fix it !  Fix it !  Fix it !
This bug has existed since Void Chest.
This issue was not posted by me.

**Comment by Dream-Master** [comment]
we are allowed to edit the code and fix it possibly.

**Comment by bartimaeusnek** [comment]
okay, the chechst isnt checking Metadata, most likely it doesn't check NBT-data aswell.

**Comment by Prometheus0000** [comment]
So this is fixed then?

**Comment by Prometheus0000** [comment]
@bartimaeusnek
