### ISSUE TITLE
Add Baubles functionality to AR Glasses

### ISSUE THREAD

**Issue by S4mpsa** [GTNewHorizons/GT-New-Horizons-Modpack#6862]
#### Which modpack version are you using?
2.0.9.1a
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Equipping the AR glasses into a Baubles slot.
#
#### What happened instead? (Attach screenshots if needed)
The glasses can only be equipped in the helmet slot.
(OpenGlasses 2 has this functionality as default, implementation [here.](https://github.com/Starchasers/OCGlasses/blob/OG2-MC1.12.2/src/main/java/com/bymarcin/openglasses/item/OpenGlassesItem.java)
#
#### What do you suggest instead/what changes do you propose?
Add/backport the Baubles functionality to our version of OpenGlasses, OG1
1.7.10 repository here https://github.com/Starchasers/OCGlasses/tree/master, the license permits modification.

**Comment by Ethryan** [comment]
You can equip them in the Tinker Mask slot.

**Comment by S4mpsa** [comment]
The... OpenGlasses AR Glasses? I am not able to equip them in any slot but the helmet slot: https://i.imgur.com/gMoolSk.gif

Maybe you mixed them up with the Holo Glasses?

**Comment by dvdmandt** [comment]
Note that you are not actually looking for Baubles but Tinkers or Travellers gear. Baubles only has slots for two rings, one amulet and one belt slot.

I started looking into this when you requested it a few weeks back. It shouldn't be too hard, but it wasn't as simple as I had hoped for IIRC.

**Comment by S4mpsa** [comment]
That's good to know
Is the implementation in OG2 of any help? I assume we would need to fork the repo for GTNH to add it.

**Comment by dvdmandt** [comment]
Well, "need" is relative, but we probably should. I think there are like two tasks. The first is to make the item equipable in that slot, which probably requires additional dependencies etc, but other than that is fairly easy. I think it needs to implement an interface and return an ID for which slot it should be in or something. The other part is to make the overlay detect that they are equipped, probably here https://github.com/Starchasers/OCGlasses/blob/98d4e3bc417e85886bb6e8869f883085c4e1294b/src/main/java/com/bymarcin/openglasses/surface/ClientSurface.java#L65 and/or here https://github.com/Starchasers/OCGlasses/blob/98d4e3bc417e85886bb6e8869f883085c4e1294b/src/main/java/com/bymarcin/openglasses/event/ClientEventHandler.java#L22

**Comment by dvdmandt** [comment]
(just realized we already have OCGlasses cloned by the way)

**Comment by repo-alt** [comment]
I added the baubles support, but 1.7.10 branch is of course horribly outdated

**Comment by repo-alt** [comment]
I was unable to make the glasses render on the player model when in the bauble slot. Maybe someone with more knowledge will fix that

**Comment by Prometheus0000** [comment]
There's also the 'getting killed in one hit bug with them on' if you see that anywhere in the code. Does that actually have a ticket?

**Comment by S4mpsa** [comment]
That does not, mostly because I could not find any reason for that to happen when going through all of OG source code so I just deemed it unfixable

**Comment by repo-alt** [comment]
There is no reason. The bug does not reproduce with just OC, OpenGlasses & Baubles
