### ISSUE TITLE
Expose block coordinate data on GregTech machines for OpenComputers

### ISSUE THREAD

**Issue by S4mpsa** [GTNewHorizons/GT-New-Horizons-Modpack#6863]
#### Which modpack version are you using?
2.0.9.1a
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Get block coordinate data, like the handheld scanner shows, using the integration with OC adapters.
#
#### What happened instead? (Attach screenshots if needed)
getSensorInformation() is missing the field that shows X/Y/Z coordinates (Topmost row in scanner data)
![image](https://user-images.githubusercontent.com/69092953/97300556-4b58c280-185f-11eb-967f-678543d293f4.png)

#
#### What do you suggest instead/what changes do you propose?
Expose the world location in getSensorInformation() / add a separate call for location data to the GT TE integration.

**Comment by Glease** [comment]
Is this still relevant? I remember someone adding some functionality to GT adaptor, but can't quite recall the details.

**Comment by repo-alt** [comment]
Mod author is against the real coordinates in OC, but since it is in sensor information, idk, maybe it's ok.

**Comment by repo-alt** [comment]
I guess we can add it under config switch for the purists.
