### ISSUE TITLE
Server adding 

### ISSUE THREAD

**Issue by Captianrex255** [GTNewHorizons/GT-New-Horizons-Modpack#6864]
ip- 51.81.112.112:25565
Current name subject to change the enteral war 
Currently don’t have whitelist on  don’t know if I will turn it on 
Fresh world, rules have not been implemented yet but I will state that no greifing or raiding is allowed untial the rules are implemented that about it

**Comment by Dream-Master** [comment]
Server location ? Name of your Server?

**Comment by Captianrex255** [comment]
NAme alredy there in the seocond secnetse (Current name subject to change the enteral war) 
and its in the us

**Comment by GTNH-Afx237v7** [comment]
Guess he means to say: The Eternal War
