### ISSUE TITLE
Recipe Problem: Recipe for use Glow Flower in NEI is not displayed

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#6866]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Privat Server
#
#### What did you try to do, and what did you expect to happen?
Found in the nether world Glow Flower decided to look at the recipes for using this item. 
#
#### What happened instead? (Attach screenshots if needed)
I only saw getting the seeds. Put it in the chest
![image](https://user-images.githubusercontent.com/46845681/97423999-87585a00-1929-11eb-8eb0-ec47e882ba8a.png)
#
#### What do you suggest instead/what changes do you propose?
Then I was looking for a way to get Glowstone Dust and found a recipe with two Glow Flowers in an extractor
![image](https://user-images.githubusercontent.com/46845681/97424142-bc64ac80-1929-11eb-9923-6b1e286d027a.png)
Why is the recipe not showing when viewing recipes for using the "U" Glow Flower? It can be fixed?
#### Notes:
It seems a similar question was raised here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/1822
#

**Comment by ReflVec** [comment]
I`m found this is related with number of items you have when press "U" key (shows recipe only for extractor from IC2, not from GT).
With more or equal number show recipe:
![with more or equal number](https://user-images.githubusercontent.com/36041167/104807970-e70d2580-57f3-11eb-9bf8-308913f6a937.png)
With one item not show recipe for extractor from IC2:
![with one not show](https://user-images.githubusercontent.com/36041167/104807971-ed030680-57f3-11eb-848a-93b02f93d824.png)

For Beeswax same thing, it shows recipe only from IC2 compressor.

**Comment by fleefie** [comment]
Persists in 2.1.2.4-18-pre

Seems like the issue is a bit random. Leaving the server, joining a SP world, and going back into MP seems to make the recipe appear again. It, however, appears and disappears randomly based on joining and rejoining, no idea what the consistent trigger is.
It consistently doesn't show up when only joining an MP server after launch however.
