### ISSUE TITLE
duplicate mobs

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6867]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I just used 21 empty soul vial and ONE enderman and got 21 soul vial with enderman
#
#### What happened instead? (Attach screenshots if needed)
i got 21 soul vial with enderman 
![image](https://user-images.githubusercontent.com/59776356/97434514-12e9df00-195a-11eb-8916-4e560a0c1c95.png)

#
#### What do you suggest instead/what changes do you propose?
don't fix it. it is useful I report this only because of obligation

**Comment by Ethryan** [comment]
Mob duplication at its finest ^^.

**Comment by Eason134HK** [comment]
https://drive.google.com/file/d/14mf7QOU6_cORFebu88VMKMgmoZKGaSG1/view?usp=sharing
video about it

**Comment by Gateswong** [comment]
This happens with every type of mobs, but will only happens with little chance and probably only while server lag/slow.

**Comment by Glease** [comment]
Seems like a vanilla bug. C02PacketUseEntity got processed (thus all the relevant code got called) even if the concerned entity is already dead. 

@repo-alt are you sure we shouldn't fix this and instead treat this as a feature? fixing it would be as trivial as `if (!entity.isEntityAlive()) return;`

**Comment by repo-alt** [comment]
It's not like I care much, but also I don't see how it can be abused, after all, boss mobs don't fit in vials. Balance decisions are for Martin to decide

**Comment by Dream-Master** [comment]
if a fix is possible i would prefer a fix.

**Comment by Dream-Master** [comment]
@Glease

**Comment by Prometheus0000** [comment]
@Glease Is this fixed then?
