### ISSUE TITLE
Nice and comfortable in space Quest

### ISSUE THREAD

**Issue by daddy77gaming** [GTNewHorizons/GT-New-Horizons-Modpack#6873]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
ToAsgaard patreon server
#
#### What did you try to do, and what did you expect to happen?
craft thermal cloth with requested recourses.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/31905330/97573357-eb425780-19e9-11eb-95c6-355e620d9ab1.png)
![image](https://user-images.githubusercontent.com/31905330/97573390-fa290a00-19e9-11eb-9ba2-551cc19a6c08.png)
![image](https://user-images.githubusercontent.com/31905330/97573412-04e39f00-19ea-11eb-844a-e6137f1a240c.png)

#
#### What do you suggest instead/what changes do you propose?
The requested material for these crafts are still based on the old crafting table recipe for the thermal cloth. Make the quest require an additional 120 tungsten`string and 96 titanium foil, as thats what you need to craft all pieces 192 foil 192 string for the cloth and 24 more string for the armor pieces themself.

**Comment by Prometheus0000** [comment]
Duplicate, already fixed, use search next time.
