### ISSUE TITLE
AE wireless access energy usage and display are different

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6874]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I try to increase the wireless access distance
#
#### What happened instead? (Attach screenshots if needed)
here is how much 36 wireless booster
![image](https://user-images.githubusercontent.com/59776356/97575062-21ea9300-1a27-11eb-8dc0-e04696a889e6.png)
![image](https://user-images.githubusercontent.com/59776356/97575160-48a8c980-1a27-11eb-9a76-9b106e17e66e.png)
and here is no wireless booster
![image](https://user-images.githubusercontent.com/59776356/97575210-5bbb9980-1a27-11eb-89dd-f0953447bc89.png)

You can see that the energy usage is 3570 EU/t when wireless booster is not installed
but after installed 36 wireless booster the energy usage becomes 4960 EU/t 
4960-3570 = 1390 but the energy usage of 36 wireless booster should be 143.11 EU/t only

#
#### What do you suggest instead/what changes do you propose?
fix it

**Comment by Eason134HK** [comment]
![image](https://user-images.githubusercontent.com/59776356/97576031-9d990f80-1a28-11eb-958c-5824e00487c1.png)
This is my test in the single player world
You can see that the energy usage is only 2050 EU/t
But the total energy usage is as high as 20KEU/t

**Comment by S4mpsa** [comment]
The bug here is AE2 tooltips not accounting for the global usage modifer set in config.
