### ISSUE TITLE
Lightning Sigil does not use Water Sigil

### ISSUE THREAD

**Issue by wolfpup08** [GTNewHorizons/GT-New-Horizons-Modpack#6875]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Official ETA server
#
#### What did you try to do, and what did you expect to happen?
I tried to make a lightning sigil and all the items had to be used.
#
#### What happened instead? (Attach screenshots if needed)
Water Sigil not use. Stayed on Pedestal. 
#
#### What do you suggest instead/what changes do you propose?
Fix it!

**Comment by GTNH-Afx237v7** [comment]
Does it consume the air sigil? A solution could be to move the water sigil to the center pedestal, but I am surprised that seemingly only one of the two sigils is consumed, the other one isn’t...

**Comment by Prometheus0000** [comment]
I don't think this bug can be resolved without diving deep into BM code. Both sigils are defined the same way in the script, and I tried playing with the ownership too. Just enjoy the free sigil.
