### ISSUE TITLE
Wand focus: Dislocation turns advanced filing cabinet into regular

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6876]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
I used Wand focus: dislocation to pick up a filing cabinet (advanced) and place it is a different location.
#
#### What happened instead? (Attach screenshots if needed)
The filing cabinet (advanced) became a regular filing cabinet, but it did keep all the items despite the normal cabinet not normally allowing you to store items of different types.
![image](https://user-images.githubusercontent.com/17787093/97620979-2b213300-1a1a-11eb-8afd-26d38f2c3573.png)
#
#### What do you suggest instead/what changes do you propose?
Either make the focus keep the full data or blacklist the block from it.

Also if possible, could I get a replacement

**Comment by Prometheus0000** [comment]
Is the difference metadata? Could you check and see how it works on other metadata blocks if so?

**Comment by KiloJoel** [comment]
Yes, filing cabinet is 1119 and advanced is 1119:1, I will see if i can find another block to test now

**Comment by KiloJoel** [comment]
Smooth marble (2051:7) retains its metadata value when dislocated

**Comment by KiloJoel** [comment]
Cherry drawer 2908:1 also retains its value

**Comment by Glease** [comment]
Are you really sure it's not the reverse? I had normal cabinets turning into advanced ones in the past..

**Comment by KiloJoel** [comment]
> 
> 
> Are you really sure it's not the reverse? I had normal cabinets turning into advanced ones in the past..

I am certain, the cabinet in the screenshot has items with various IDs, which can only be done with an advanced filing cabinet

**Comment by LewisSaber** [comment]
Can you still insert other items in it, maybe its just sort of visual bug

**Comment by KiloJoel** [comment]
> Can you still insert other items in it, maybe its just sort of visual bug
No, I can't, and any items taken out also can't be reinserted.
