### ISSUE TITLE
Recipe Problem: Recipe for use Exquisite Diamond

### ISSUE THREAD

**Issue by EldrinnElantey** [GTNewHorizons/GT-New-Horizons-Modpack#6877]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Privat Server
#
#### What did you try to do, and what did you expect to happen?
Have a question about one recipe
#
#### What happened instead? (Attach screenshots if needed)
Exquisite Diamond is 4 regular diamonds, why do you need 9 to get a block?
![image](https://user-images.githubusercontent.com/46845681/97627581-00989f80-1a45-11eb-8850-55566a8074d8.png)
#
#### What do you suggest instead/what changes do you propose?
Is there a mistake here?

**Comment by Prometheus0000** [comment]
Isn't it just ordicting it as diamonds? Use regular ones for that

**Comment by EldrinnElantey** [comment]
> Isn't it just ordicting it as diamonds? Use regular ones for that

![image](https://user-images.githubusercontent.com/46845681/97631071-df867d80-1a49-11eb-8b28-928e4b94dc96.png)
This large diamond is crushed into 4 regular ones from vanilla minecraft

**Comment by GTNH-Afx237v7** [comment]
One could remove the compressor recipe for exquisite gems into blocks, possibly also for flawless gems into blocks (if the latter exists and the former is possible).

**Comment by Prometheus0000** [comment]
So? You lose some when implosion compressing too. It's not a lossless process. Just make the blocks out of regular diamonds like I said.

Presumably it's oredicted to diamond so you can use industrial diamonds, since you originally made them from carbon (in IC2 at least).

**Comment by GTNH-Afx237v7** [comment]
Yeah right, forgot about the oredict for exquisite diamonds there...

**Comment by EldrinnElantey** [comment]
> So? You lose some when implosion compressing too. It's not a lossless process. Just make the blocks out of regular diamonds like I said.
> 
> Presumably it's oredicted to diamond so you can use industrial diamonds, since you originally made them from carbon (in IC2 at least).

Crafting a block of different types of diamonds in one case is 9 in another 36. This is not the same as an implusive compressor. These recipes contradict each other! Need to remove the crafting block from exquisite diamonds!

**Comment by Prometheus0000** [comment]
You could try doing yourself? I don't think it's worth the effort

**Comment by EldrinnElantey** [comment]
So what about this question?

**Comment by Prometheus0000** [comment]
What question? There was a _suggestion_, which was 99% pointless, and no one wanted to touch.

**Comment by EldrinnElantey** [comment]
Ok
