### ISSUE TITLE
Proposal to improve the font for Cyrillic

### ISSUE THREAD

**Issue by EldrinnElantey** [GTNewHorizons/GT-New-Horizons-Modpack#6881]
Along with the modpack comes a resource pack of excellent sky and fonts. In Russian in Thaumcraft and not only, this font does not look very good.

Therefore, I propose to add the [clientfixer ](https://github.com/gamerforEA/Minecraft-ClientFixer) mod and its [font](https://mods2.ru/engine/download.php?id=1076) to the modpack, which will adjust to the size of the game interface and fix the incorrect display of the font in thaumcraft interfaces and other mods.

This will eliminate the need to play with a large interface size for normal use of Thaumcraft.

**Comment by Prometheus0000** [comment]
Why would we add a mod for everyone, when it looks fine for everyone not playing in russian? You can just add it to your own pack/server.

Not to mention there's no explanation of what it does for people who can't read russian.

**Comment by Prometheus0000** [comment]
Also, there's no 1.7 version, so no for sure unless you can find one.

**Comment by EldrinnElantey** [comment]
> Also, there's no 1.7 version, so no for sure unless you can find one.

The mod started with 1.7.10 so it is for this version. It can be found on the [second release page](https://github.com/gamerforEA/Minecraft-ClientFixer/releases?after=1.1).

I also checked the work of this mod before offering it here.

**Comment by EldrinnElantey** [comment]
The font is suitable not only for Cyrillic but also for Latin

**Comment by Prometheus0000** [comment]
Well I don't know why they wouldn't maintain that version in their repo, and means that bugs might not be able to be fixed. But that just means we go back to my initial comment. Why add it to the pack when it's just useless bloat for probably 95% of players (no idea how many play in russian honestly). Does it require being on the server to use it? Why can't you just add it to https://gtnh.miraheze.org/wiki/Additional_Mods?

**Comment by EldrinnElantey** [comment]
> Well I don't know why they wouldn't maintain that version in their repo, and means that bugs might not be able to be fixed. But that just means we go back to my initial comment. Why add it to the pack when it's just useless bloat for probably 95% of players (no idea how many play in russian honestly). Does it require being on the server to use it? Why can't you just add it to https://gtnh.miraheze.org/wiki/Additional_Mods?

I expected an approximate result like this. How can I add it to the Additional Mods list?

**Comment by Prometheus0000** [comment]
Create an account, then edit the page to add it.

**Comment by EldrinnElantey** [comment]
Added it to the list
