### ISSUE TITLE
Cannot create architecturecraft blocks with chiseled stained glass

### ISSUE THREAD

**Issue by jonathan-ng** [GTNewHorizons/GT-New-Horizons-Modpack#6882]
### Which modpack version are you using?
2.0.9.0 QF4

#
#### If in multiplayer; On which server does this happen? 
Singleplayer

#
#### What did you try to do, and what did you expect to happen?
Create shaped blocks at the architect's table

#
#### What happened instead? (Attach screenshots if needed)
It didn't work, although it worked for chiseled plain glass.

#
#### What do you suggest instead/what changes do you propose?
This issue has come up before in #3761 but the fix doesn't seem to work with stained glass. 

Using a config with all the colored names of stain glass seems to fix the issue.

```
materials {
    S:UnlocalizedNames <
        tile.chisel.stained_glass
        tile.chisel.glass
        tile.chisel.stained_glass_black
        tile.chisel.stained_glass_red
        tile.chisel.stained_glass_green
        tile.chisel.stained_glass_brown
        tile.chisel.stained_glass_blue
        tile.chisel.stained_glass_purple
        tile.chisel.stained_glass_cyan
        tile.chisel.stained_glass_lightgray
        tile.chisel.stained_glass_gray
        tile.chisel.stained_glass_pink
        tile.chisel.stained_glass_lime
        tile.chisel.stained_glass_yellow
        tile.chisel.stained_glass_lightblue
        tile.chisel.stained_glass_magenta
        tile.chisel.stained_glass_orange
        tile.chisel.stained_glass_white
    >
}
```

Unfortunately internal faces are visible when using archiecturecraft with stained glass, unlike carpenter's blocks, so I doubt this will see any use.

**Comment by Dream-Master** [comment]
@jonathan-ng can you make a pull request so I can merge it and put it into the next update. thanks
