### ISSUE TITLE
[Suggestion]Add giant gas planet 

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#6886]
There are so many gas planets in the galaxy and it would be awesome if we can use them as a gas resource.
The elements of giant gas planet include H,He,O,Ne etc and can be obtained by spacedrill(a new machine after T4?).
Unlike the regular underground fluid,these giant gas planets are almost inexhaustible.
Just a tentative idea.

**Comment by DualBallers** [comment]
It would be really cool if the planet's gas had to be siphoned from orbit, e.i. the gas pump had to be placed on an orbiting space station.
As far as I know the space stations have no use except for crafting the first low-gravity chip.

**Comment by repo-alt** [comment]
Space station are also very buggy...

**Comment by glowredman** [comment]
What bugs are there? Maybe we can fix them. I think this concept is a nice idea and I'd like to implement somehing like this

**Comment by repo-alt** [comment]
Movement is weird, block placement is weird. Just build one in creative it is hard to miss

**Comment by GlodBlock** [comment]
Well,it isn't an issue about space station.

**Comment by GlodBlock** [comment]
More details:
The spacedrill should be placed on space station to pump the planet's gas.
The drill can be modified to pump different gas of different depths of the planet.
![20201103_093246](https://user-images.githubusercontent.com/60341015/97936893-fa455300-1db7-11eb-8b09-f23fc6dbf8fc.jpg)

**Comment by glowredman** [comment]
Just out of cuoriosity: are these gases based on the actual planets or did you choose them because you thought they would fit balance-wise?

**Comment by botn365** [comment]
8B/s ammonia and 18B/s H2 is the opesite of balance

**Comment by GlodBlock** [comment]
> Just out of cuoriosity: are these gases based on the actual planets or did you choose them because you thought they would fit balance-wise?

H2,He,NH3,CH4,N,O are actual on these planets,and the rest are not.

**Comment by GlodBlock** [comment]
> 8B/s ammonia and 18B/s H2 is the opesite of balance

How about 4B/s NH3?
As to hydrogen,I don't think it is imbalance because hydrogen is so easy to mass production at that tier.

**Comment by glowredman** [comment]
I tinkered around a bit with adding new SpaceStaions, turn out Galacticraft needs the dimensionID of the planet the SS surrounds. These planets don't have a dimension attached to them because, well, they are gasplanets. So I tried to change the GC code a bit to accept the planet object, which nearly worked.
I really like this idea and want to implement it, but I don't know (yet) how to properly do this, so this won't be a feature for the forseeable future :(

**Comment by LewisSaber** [comment]
Create planet from layer of cobble and somehow make it unnacesible

**Comment by GlodBlock** [comment]
@glowredman 
Maybe you can just use the spacestations of these planets' moon(except Eris).
But it looks a bit weird.
If you are able toregister new planets, could you make the SS as a "planet" surrounding these gasplanets.

**Comment by glowredman** [comment]
> Create planet from layer of cobble and somehow make it unaccecible

Something like this is my plan, not sure if it'll work.

> If you are able toregister new planets, could you make the SS as a "planet" surrounding these gasplanets.

This would work for SSP, but 1) the creation costs will fall flat and 2) there would be only one SS per dimension, so this wouldn't work on servers (yes I know I could create a SS for each player and space them 1000 blocks apart, but I'd also have to make sure that the player will actually land there when entering the dimension, which is *very* difficult)

**Comment by Glease** [comment]
@glowredman I think you don't want this closed, no?

**Comment by glowredman** [comment]
No, maybe I'll get back to this when I'm done with my own pack.

**Comment by Dream-Master** [comment]
ok lets reopen this 2030.

**Comment by johnch18** [comment]
You could make the bottom layer of Jupiter out of "solid hydrogen" blocks and just make the planet instakill everything. That's pretty true to life.

**Comment by glowredman** [comment]
Good idea. Something like this has to be done becuase GC is not able to make space stations around dimension-less planets sadly.

**Comment by johnch18** [comment]
We could add pressure suits gated behind T8 planet stuff and make the gas giants almost act like a T8.5 planet

**Comment by glowredman** [comment]
I'm currently working on this (again) and I noticed that Eris is not a gas planet: *Infrared light from the object revealed the presence of methane ice, indicating that the surface may be similar to that of Pluto, which at the time was the only TNO known to have surface methane, and of Neptune's moon Triton, which also has methane on its surface.* (https://en.wikipedia.org/wiki/Eris_(dwarf_planet)#Surface_and_atmosphere)

In my opinion there are different options we have now (in order of increasing work):
1. Remove Eris from the list posted above
2. Don't take realism to serious and implement Eris anyway
3. Find another planet/moon, possibly in another system and use it instead
4. Create a new planet/moon, possibly with its own system and use it instead

Thoughts?

**Comment by bombcar** [comment]
> close-up imagery from the *New Horizons* mission more accurately determined Pluto's volume to be slightly larger than Eris's, rather than slightly smaller as previously thought.

(from the article) - well now we kinda have to include it I guess ...

**Comment by GlodBlock** [comment]
yeah, i mistaken Eris as the gas planet so removing it from the list should be reasonable. but could you directly make Eris reachable via rockets, and we can add these fluids as it's underground fluids.

**Comment by glowredman** [comment]
Sure that could be done, though it requires a bit more work than space stations (biggest problem for me is the rendering of the skybox)

**Comment by glowredman** [comment]
This feature has now been implemented and will be part of the pack once https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/22 is merged. You can test the multi already by downloading the newest GalaxySpace build from [Jenkins](http://jenkins.usrv.eu:8080/job/Galaxy-Space/148/artifact/build/libs/GalaxySpace-1.7.10-1.1.12-GTNH-5-g2b58dc9.jar).
