### ISSUE TITLE
Things that need fixing in the 2.0.9.2b dev version

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6887]
- Add a circuit assembler recipe for the uranium tube
 - Add a note on startup about the change to crop multifarms
 - Fix the AE2 voiding power thing

Anything else?

**Comment by ScriptedPiky** [comment]
Galactic Craft & Galaxy Space bosses may still crash servers if they're loaded. Although, I am uncertain if this change was included and I don't want to be soft-locked out on Zeta for trying to test it.

**Comment by Prometheus0000** [comment]
Their health and their class name is different? There's no commit that says it's fixed though. @glowredman 

Is there even a ticket for that? I couldn't find one.

**Comment by Prometheus0000** [comment]
NVM, I didn't look back far enough.

**Comment by bartimaeusnek** [comment]
> Add a note on startup about the change to crop multifarms

Thats a change. I'll not add every change to startup.

**Comment by Prometheus0000** [comment]
If it destroys people's entire crop farms, we should.

**Comment by Prometheus0000** [comment]
Note #6714 for previous stuff.

**Comment by leagris** [comment]
> If it destroys people's entire crop farms, we should.

If it destroys people's entire crop farm we should roll-back or warn people before they even upgrade. Because If I had crop farm and I had to redo them entirely, I'd be really pissed.

What was the incentive for this change again?

**Comment by Prometheus0000** [comment]
TPS gain. Admittedly it'll only destroy the crops (after a certain amount of time) if you're relying on the fertilizer+water from a multifarm to keep them alive.

**Comment by S4mpsa** [comment]
And fixing it takes 10 seconds with the soldering iron, 5 minutes if you count making the electron tubes. It's nothing huge, but something that people need to know so they can replace the farm circuit in time.

**Comment by Prometheus0000** [comment]
Assuming you have the uranium. Also completely breaks all stacked multifarms, so everyone doing that is screwed though.

**Comment by ScriptedPiky** [comment]
https://cdn.discordapp.com/attachments/521008249844269061/772985348186701844/unknown.png This was found out in the Zeta server. Seems to be only LuV motors, for some reason. I wonder if it's a Bartworks material problem itself or the assline recipe having trouble working with the Bartworks materials.

**Comment by Darkstar1712** [comment]
T6 field gens too.
![image](https://user-images.githubusercontent.com/34458535/97935712-47520680-1d71-11eb-8b2b-54d89ec20e84.png)

**Comment by repo-alt** [comment]
Fixed AE energy drain.
