### ISSUE TITLE
FPS drop due to installation in the world of Upgraded Pollution Scrubber

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#6891]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Privet Server
#
#### What did you try to do, and what did you expect to happen?
I wanted to use the Upgraded Pollution Scrubber for its intended purpose, but when I put it in the world, the fps dropped by an average of 30 units and every time I looked in its direction, the fps dropped.
#
#### What happened instead? (Attach screenshots if needed)
Before
![image](https://user-images.githubusercontent.com/46845681/97999458-c5abb880-1e04-11eb-8460-c85b8dfd5759.png)
After
![image](https://user-images.githubusercontent.com/46845681/97999414-b4fb4280-1e04-11eb-8460-050be376795e.png)
#
#### What do you suggest instead/what changes do you propose?
How can I fix this?

**Comment by Prometheus0000** [comment]
Report on the GT++ repo

**Comment by EldrinnElantey** [comment]
> Report on the GT++ repo

Do I have to duplicate issues in the repo GT ++?

**Comment by Prometheus0000** [comment]
If it's a GT++ issue, yes. Also, link back to this one.

**Comment by EldrinnElantey** [comment]
> If it's a GT++ issue, yes. Also, link back to this one.

done

https://github.com/alkcorp/GTplusplus/issues/763
