### ISSUE TITLE
Recipe Problem: Wrong Vibrant Alloy Recipe

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#6894]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Privat Server
#
#### What did you try to do, and what did you expect to happen?
I wanted to get a vibrating alloy using this recipe at NEI.
![image](https://user-images.githubusercontent.com/46845681/98033304-c0636380-1e2e-11eb-9459-8a5cdc304bd2.png)
#
#### What happened instead? (Attach screenshots if needed)
It turned out that this is not the same vibrating alloy but from GT ++. To smelt the required temperature, a lower temperature is required.
#
#### What do you suggest instead/what changes do you propose?
Remove dead-end recipe. Since dust from GT ++ cannot be created

**Comment by Glease** [comment]
I'd like to revisit this at some point.

**Comment by Eldrinn-Elantey** [comment]
@Glease 
![image](https://user-images.githubusercontent.com/46845681/193692216-eeed08b0-2342-432e-8cd6-303ed02b5415.png)
![image](https://user-images.githubusercontent.com/46845681/193692219-17754d5b-4810-42bb-915d-f4ad8de993eb.png)

**Comment by BritishCynic** [comment]
The dust now smelts to a GregTech Hot Vibrant Alloy, so this issue can be closed.

**Comment by Eldrinn-Elantey** [comment]
> The dust now smelts to a GregTech Hot Vibrant Alloy, so this issue can be closed.

I agree
