### ISSUE TITLE
Cobweb/string double drop

### ISSUE THREAD

**Issue by chadandersen1** [GTNewHorizons/GT-New-Horizons-Modpack#6897]
Upon breaking cobweb with any shears except precision shears in version 2.0.9.0, it drops you both a string and the cobweb back so you may acquire infinite string. I do not know which one you would rather have drop but I was trying to acquire only the string, a player can use a boline from witchery to get the web if they need it. Precision shears drop nothing but can still break cobwebs quickly, this may be a function of ExUtil or a separate bug. An activated bound sheers also drops both items.

**Comment by repo-alt** [comment]
Any weapon drops the string, so shears should drop the cobweb. I doubt many players know about boline

**Comment by chadandersen1** [comment]
> Any weapon drops the string, so shears should drop the cobweb. I doubt many players know about boline

I agree with this, if anything sheers should probably drop the whole web.

**Comment by yukieiji** [comment]
I have confirmed that this issue exists in v2.1.1.0
Also, this issue doesn't occur with multi-servers.
Instead, only Cobweb dupe when I collected it with Dark shear.
