### ISSUE TITLE
Unattuned/attuned node matrix dupe bug

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6898]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### What happened instead? (Attach screenshots if needed)
Unattuned node matrix/Attuned node matrix can be duplicated by placing more than one in the arcane workbench when crafting them with phials of essentia. When crafting, one is used, but many are created.

The process is exponential, many stacks of them can be created from just 2 with very few crafts.
![image](https://user-images.githubusercontent.com/17787093/98269813-1e568f00-1f86-11eb-8435-a27fd37a11b2.png)
![image](https://user-images.githubusercontent.com/17787093/98270149-7a211800-1f86-11eb-958c-c36e856082df.png)

An old issue about the same thing: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3858

**Comment by repo-alt** [comment]
How about just making matrices unstackable

**Comment by KiloJoel** [comment]
That seems like a reasonable solution, I can't think of any downsides from that.
