### ISSUE TITLE
Hemp Seed tooltip broken L.java.lang.String

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#6899]
#### Which modpack version are you using?
2.0.9.0

#### What happened instead? (Attach screenshots if needed)
Hemp Seed extra Info:
Hemp Seed: `L.java.lang.String:@41dc2da8`

![Help Seed ToolTip](https://i.imgur.com/ad7tQ49.png)

**Comment by Dream-Master** [comment]
is this a crops++ seed @bartimaeusnek  ?

**Comment by bartimaeusnek** [comment]
nope GT++, this is a String[].toString() call issue. @alkalus

**Comment by draknyte1** [comment]
I copied the code for crops from crops++. 🤷🏻‍♀️
