### ISSUE TITLE
project red

### ISSUE THREAD

**Issue by abitaredomdepo** [GTNewHorizons/GT-New-Horizons-Modpack#6900]
Hello everyone, there was a problem. there is a bug in the "project red" mod due to which it is not possible to use all cells outside the inventory.
cells in which it is impossible to put anything are marked in black.
cells are marked in green, which can be placed, provided that it is placed in the red selection area. help to solve the problem.
![Безымяыыыыыыыыынный](https://user-images.githubusercontent.com/51705777/98306581-2d186280-1fd5-11eb-8530-979041c8b03b.png)

**Comment by Prometheus0000** [comment]
Duplicate #6019
