### ISSUE TITLE
EIO Farming station and Forestry sapplings

### ISSUE THREAD

**Issue by AiramProvoker** [GTNewHorizons/GT-New-Horizons-Modpack#6904]
Forestry saplings are incompatible with the EIO farming station. 
Boubou mentioned the issue ~2.5 years ago, so I'm bringing it up again. 
Farming stations are still a somewhat TPS-hungry solution in comparison to bart's bonsais, but I think it would be a worthy fix regardless.
 
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/2582

**Comment by mitchej123** [comment]
Implemented in https://github.com/GTNewHorizons/EnderIO/pull/25

**Comment by boubou19** [comment]
Finally! Thanks Mitch :D

**Comment by boubou19** [comment]
don't close it, it will be closed when a release will happen, that helps to make the changelog

**Comment by AiramProvoker** [comment]
Got it, will remember it in the future
