### ISSUE TITLE
Colorful upgrade recipe

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#6905]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Craft Colorful upgrade from Computronics
#

#### What happened instead? (Attach screenshots if needed)
Recipe uses transistor from OC which are disabled by OC config and doesnt have any recipe
![image](https://user-images.githubusercontent.com/29033773/98451398-3977f900-2156-11eb-8875-29eb0d80cc9e.png)

**Comment by Dream-Master** [comment]
wasnt this fixed in 2.0.9.1 oer 2.0.9.2 ?

**Comment by Prometheus0000** [comment]
It appears to use a completely different recipe now, which doesn't use a transistor.
