### ISSUE TITLE
Question: Using the system of in-demand materials

### ISSUE THREAD

**Issue by EldrinnElantey** [GTNewHorizons/GT-New-Horizons-Modpack#6906]
In one of the versions of GregTech 5, Unofficial added a system for loading only those materials that are used in GregTech recipes or in minetweaker scripts, which is a good optimization of client loading.

I want to know if it is fully used in the modpack? Since I see a lot of materials that are not used anywhere, for example, an electrum rotor

**Comment by Prometheus0000** [comment]
Materials are different from the items made from those materials aren't they? https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/Materials.java for list
It would be great if we could get rid of the clutter, but would made it nearly impossible to decide to use them later since I have no idea how we would then find the meta #.

**Comment by EldrinnElantey** [comment]
> Materials are different from the items made from those materials aren't they? https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/Materials.java for list
> It would be great if we could get rid of the clutter, but would made it nearly impossible to decide to use them later since I have no idea how we would then find the meta #.

That is, if you remove / disable materials now, it will complicate their use in the future, if necessary?

Did I understand correctly?

**Comment by Prometheus0000** [comment]
If you disable a material, all things made of it are disabled, like disabling electrum would disable any electrum parts. Or at least, that's my reading of it, I'm certainly not any kind of expert. If there's a way to know what the meta #s are and still disable unused parts (parts, not materials), that would be useful though. Do you happen to know where this code is, or what version uses it?

**Comment by EldrinnElantey** [comment]
> If you disable a material, all things made of it are disabled, like disabling electrum would disable any electrum parts. Or at least, that's my reading of it, I'm certainly not any kind of expert. If there's a way to know what the meta #s are and still disable unused parts (parts, not materials), that would be useful though. Do you happen to know where this code is, or what version uses it?

I once saw a video in which this system was mentioned. They said that there are ingots and plates made of bismuth, but there is no foil from it. And he said that this is because of the new system for loading materials and that this foil needs to be at least mentioned in the minetweaker scripts.

He said that when loading, GregTech looks at both its recipes and minetweaker scripts, and what I did not find anywhere does not load at all and, accordingly, NEI does not.

**Comment by EldrinnElantey** [comment]
So what about this question? Are there any problems using this system? Why are items that don't have recipes being loaded?

**Comment by GTNH-Afx237v7** [comment]
Is this still significant/relevant given the optimizations, especially with regards to Minetweaker scripts, that have been implemented recently? When I started with 2.0.7.5, load times was a good 15-20 minutes, now (2.1.0.0) I am down to 8 minutes (on exactly the same computer, which is not a beefy one).

**Comment by boubou19** [comment]
Can we close this?

**Comment by EldrinnElantey** [comment]
> Can we close this?

So will this system be used to optimize client downloads? What's the point of loading electrum foil if there are no craft items with it?

**Comment by boubou19** [comment]
If you can provide a link to a piece of code or a config, we could be able to use it. Currently, the pack is using the material system Prometheus described. However, i suggest you to download the latest dev version availiable in #announcements on our discord, and launch it. You should see the difference (the gregtech material loading is very fast now)

**Comment by EldrinnElantey** [comment]
> If you can provide a link to a piece of code or a config, we could be able to use it. Currently, the pack is using the material system Prometheus described. However, i suggest you to download the latest dev version availiable in #announcements on our discord, and launch it. You should see the difference (the gregtech material loading is very fast now)

Since the work on optimizing the pack is already being carried out according to a certain principle, then let it go. Since at the moment I cannot tell you more about the shutdown system for items not involved in recipes. If I have information about this system, I will immediately inform you.
