### ISSUE TITLE
cauldrons can't be filled with water via clay buckets

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6907]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
eta
#
#### What did you try to do, and what did you expect to happen?
you cannot fill a cauldron with water via clay buckets from iguana tinker tweaks.
This has already been reported in the past, (#4160) but it's still not fixed.

**Comment by Prometheus0000** [comment]
Then why didn't you reopen that one instead of opening a new one?

**Comment by boubou19** [comment]
i don't have perms to reopen it :/
