### ISSUE TITLE
IC2 Crops ignoring growth rate set from Hunger Overhaul

### ISSUE THREAD

**Issue by DrParadox7** [GTNewHorizons/GT-New-Horizons-Modpack#6909]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
/
#
#### What did you try to do, and what did you expect to happen?
Planted 2 vanilla seeds, one on a hydrated farmland and another on hydrated farmland AND cropsticks.
Expected both to grow at the same rate.
#
#### What happened instead? (Attach screenshots if needed)
The one on cropsticks was mature by the time the one on just farmland reached stage one growth rate.
![2020-11-09_20 15 19](https://user-images.githubusercontent.com/47131096/98591557-4fa5c680-22c8-11eb-8e2f-ef26cb6594a5.png)
#
#### What do you suggest instead/what changes do you propose?
Add a way to slowdown Ic2 crop growth since it ignores Hunger Overhaul's `I:cropRegrowthMultiplier=2`

**Comment by Prometheus0000** [comment]
I hope you mean only for edible stuff? It's hard enough. Also, it takes a while to get to ic2 crops anyway I think?

**Comment by DrParadox7** [comment]
I would say only all vanilla crops instead and maybe the sticky reed since it is basically just reeds with an extra maturity stage.
It seems berries++ already has a feature to slowdown crop growth but only for primordial seed. Maybe extend that to those seeds too? 

`#  Primordial Berry's growth time is divided by 4, in IC2 groth points. F.e. 10 = 40GP per groth-period
#  IC2 groth points are calculated by 3 + random 0-7 + statGrowth per 256ticks
I:"Primordial Berry growth time"=125000`

**Comment by DrParadox7** [comment]
Basically:
Potatoes
Carrots
Wheat
Reeds (Sticky Reeds?)
Netherwart (Terrawart?)
Pumpkin
Melon
Cocoa

**Comment by Prometheus0000** [comment]
It would be a huge pain to add a config for every crop. And you have to to ASM/mixin vanilla crops too, since they're all IC2. And there's no reason to nerf stickreed? Plus it's the best crop for advancing, so would nerf crops as a whole.

Does HO modify crops like netherwart? Why? You can't eat them? If it does, it sounds like they were lazy and just applied it to anything that grows.

**Comment by DrParadox7** [comment]
I'm not suggesting  to add a config to every crop, only those that have a vanilla crops variant.
My problem is the very strong mismatch in growth between crops that can be planted with cropsticks compared to their non-cropsticks counterpart. 
As for the sticky reed balance, I am not arguing on whether is balanced or not but slowing it down by 50% instead of 100% (like HO does to all crops), in my opinion, would be negligible at worst.

Hunger Overhaul has a setting specifically for Nether wart and GT:NH has it set at:
`I:netherWartRegrowthMultiplier=2`

**Comment by DrParadox7** [comment]
Maybe I'm being overly picky. I'll just lower down HO Multipliers to 1.5 instead. 

I forget that I am playing a game where trees float when punched and it strays from real life.

**Comment by repo-alt** [comment]
Note that non-ic2 crops can be bonemealed, sprinkled, lamp of growth affected, etc. Nothing short of World Accelerator works on crop sticks.

**Comment by DrParadox7** [comment]
I didn’t know. That is a worthy trade off, thank you for mentioning.
