### ISSUE TITLE
add infinity coils

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#6911]
#### Which modpack version are you using?
9.0
#
#### If in multiplayer; On which server does this happen? 
MP
#### What do you suggest instead/what changes do you propose?
add infinity coils with a value of  12600K this allows for 1 extra free OC
thats is al it should be usfull fore

**Comment by Prometheus0000** [comment]
I'd still rather there be more than 1 coil tier more post AwDr, but I don't know how difficult it is to get inf. And if we flesh out more tiers later, skipping temp values will be annoying to adjust later.

**Comment by ScriptedPiky** [comment]
From what I can tell, Infinity is more or less a time gate once you place down Void Miners on Vega B and maybe some other planets for Black Plutonium? However, for the average player at this tier (presumably if they don't have multiple VM's), obtaining Infinity in large quantities might be difficult. Although, more coil tiers beyond D*/AwDr would be nice before we get If* coil tiers but what materials could we use that isn't Infinity Catalyst or Cosmic Neutronium? Or do we use one of those for the next coil?

**Comment by Prometheus0000** [comment]
Discussion: https://discordapp.com/channels/181078474394566657/224191655375273985/775542435215966239

**Comment by boubou19** [comment]
don't forget to add the coils in the pyrolyse oven if some new ebf coils get added.

**Comment by Prometheus0000** [comment]
I also heard the volcanus doesn't support the last 2 tiers even now? Or maybe it was the utupu? Or zyngen. Anyway, GT++ multi support is likely to be lacking.

**Comment by GTNH-Colen** [comment]
> I also heard the volcanus doesn't support the last 2 tiers even now? Or maybe it was the utupu? Or zyngen. Anyway, GT++ multi support is likely to be lacking.

Not sure about in the past but GT++ volcanus supports the highest tier coils at least, unsure about the other multis you mentioned.

**Comment by Prometheus0000** [comment]
Awakened Draconium Coil reduce energy consumption Zyngen to 0: https://github.com/alkcorp/GTplusplus/issues/733
This is the only bug with coils I found, maybe I was thinking of an old version.

**Comment by Hikari1nVoid** [comment]
The only threshold that decides whether infinity is expensive or cheap is the void miner,which is doable in T6.And from my perspectives in smelting uhv superconductors and bedrockium I will be very happy if I have a infinite/Spnt Coil which allows me for lossless overclocking.
