### ISSUE TITLE
[Bartworks] Tooltip mistakes/suggestions for Mega Blast Furnace

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#6912]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Affects both SP and MP
#
#### What did you try to do, and what did you expect to happen?
Read the tooltip of the mega blast furnace
#
#### What happened instead? (Attach screenshots if needed)

Small mistakes:
_Controller: 3nd Layer Middle Center_ - should read: **3rd Layer Middle Center**
_Outer 15x18x15 Boronsilicate Glass_ - should read: **Borosilicate Glass Blocks**

Suggestions:
_The glass limits the Energy Input Tier_ - suggestion: **The glass tier determines the energy input tier**
_Heat Proof Machine Casings for Base_ - suggestion to combine it with the info on heat proof machine casings for layer 20:
**Heat proof machine casings for the base and top layers**

#
#### What do you suggest instead/what changes do you propose?
see above

**Comment by Prometheus0000** [comment]
You know you're supposed to open them on bart's tracker as well, right?

**Comment by GTNH-Afx237v7** [comment]
Done.
