### ISSUE TITLE
GT bypasses EIO conduit limitations

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6914]
#### Which modpack version are you using?
2090QF4
#
#### If in multiplayer; On which server does this happen? 
eta

was hunting lag on eta, found out that the conveyors bypass the intended speed of EIO item conduits, like the pump does for the fluid conduits (see #6662).

that makes the eio conduits better for setups than GT item/fluid pipes, and they are basically cheap HV+.

**Comment by Prometheus0000** [comment]
Does this cause lag though?

**Comment by repo-alt** [comment]
The "intended" speed is for extraction only, so this is totally not a bug.

**Comment by boubou19** [comment]
welp, it makes all the connected inventories to be seen as a single big one, or something like that, from the conveyors' point of view. And because we don't have the conveyors fix yet, it generates significant amount of lags. Don't know if it still lags on 2092d.

Lag aside, it looks like the balance for the GT pipes is a bit useless if you can tp instantly items with a single conveyor/pump: why would you want to craft Bedrockium/Quantium item pipes, or Naquadah/Neutronium fluid pipes in that case?

**Comment by repo-alt** [comment]
1.7.10 GT pipes are horrible lag-wise anyway. I'd not encourage their usage. Using conveyors on large conduit network is bad, but it would be even worse with high tier GT pipes.

**Comment by bartimaeusnek** [comment]
@repo-alt i see it completly different. GT pipes usually lagg less than conduits 🤔

**Comment by repo-alt** [comment]
GT pipes basically don't do any routing, at any point pipe block determines where it may pass its contents. Item pipes are a bit intelligent remembering where from they did get the stuff, but anyway, every pipe block does some decisions every tick (every working tick, that depends on tier). Conduits behave like a network, so at least they may cache routes.

**Comment by Prometheus0000** [comment]
Maybe we should just copy the conduits and make the pipes teleport items instantly past a certain tier if it reduces lag? Or add a version that does this but uses power?
