### ISSUE TITLE
Suggestion for AE

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#6915]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What do you suggest instead/what changes do you propose?
Add new mode for Ae terminal, where it saves searchbar value when leaving terminal

**Comment by S4mpsa** [comment]
Doesn't that already exist? Atleast my terminal saves the search result when reopened

**Comment by LewisSaber** [comment]
maybe that was added in dev version?

**Comment by boubou19** [comment]
I know that if you leave the terminal after checking your current crafting tasks, it's remembered, at least for the wireless crafting terminal.

**Comment by LewisSaber** [comment]
ye found that few days ago, but function of being able to save what u need may be preatty handy

**Comment by LewisSaber** [comment]
open this i closed by missclick sorry

**Comment by GTNH-Afx237v7** [comment]
As of 2.1.0.0 this works fine with the Arcane Crafting Terminal from Thaumic Energistics, but not with the Terminals of AE2 (tried Crafting, Pattern, Interface and Processing Pattern). Maybe what was done with Thaumic Energistics can be added to AE2?
