### ISSUE TITLE
Industrial grafter has a ludicrous recipe

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6916]
#### Which modpack version are you using?
2.0.9.2d dev
#
![image](https://user-images.githubusercontent.com/8517039/98888200-86651380-2465-11eb-9b24-bb9a0db5d10a.png)
![image](https://user-images.githubusercontent.com/8517039/98888210-8cf38b00-2465-11eb-8f66-1ac07b6cf970.png)
That's a Nq comb and LuV circuit, not to mention the other stuff. It's a chargable grafter, it works the same as the dirt cheap branch cutter, you just charge it instead of making a new one. And those ones have crazy durability too.

**Comment by Dream-Master** [comment]
Gendustry  is a high tier mod and balanced above all other bee stuff. Not start to make GTNH stuff to easy.

**Comment by GTNH-Colen** [comment]
> #### Which modpack version are you using?
> 2.0.9.2d dev
> 
> ![image](https://user-images.githubusercontent.com/8517039/98888200-86651380-2465-11eb-9b24-bb9a0db5d10a.png)
> ![image](https://user-images.githubusercontent.com/8517039/98888210-8cf38b00-2465-11eb-8f66-1ac07b6cf970.png)
> That's a Nq comb and LuV circuit, not to mention the other stuff. It's a chargable grafter, it works the same as the dirt cheap branch cutter, you just charge it instead of making a new one. And those ones have crazy durability too.

Agreed, this is a silly overpriced recipe for no real reason other than for the sake of it. You can make a regular grafter and spam them, why would this need to cost so much more?

**Comment by repo-alt** [comment]
Kinda poor man's meme item.

**Comment by Dream-Master** [comment]
Maybe the grafter but the thing in the middle used in other devices too so we need to remove this item

**Comment by Ethryan** [comment]
Why not replace the Power Module with a appropriate tiered GT Motor instead. That should suffice.

**Comment by Dream-Master** [comment]
Sure why not.

**Comment by LewisSaber** [comment]
I dont think knife is moving so he dont need motor, why not to make it use field gen of unlocked tier or tier -1 so it will be like he generates energy field around blade to cut thigs

**Comment by Ethryan** [comment]
That's actually a better idea, i retract my suggestion.

**Comment by LewisSaber** [comment]
You may also leave option between field generator and power module, as power module is cheaper but requires naquadah comb

**Comment by Prometheus0000** [comment]
The power module should definitely go, the main gendustry stuff does need that to be hard. Also, grafter = 5 uses, Iron branch cutter = 380, this = 100. They do the same thing. There's absolutely no reason to make this outside of completing the quest.

> I dont think knife is moving so he dont need motor, why not to make it use field gen of unlocked tier or tier -1 so it will be like he generates energy field around blade to cut things, and replace battery to lapotronic crystal

It's unlocked after making bronze, before any FGs. Or electricity. Not only that, but although it has an AoE effect, it doesn't even work properly and make every block drop a sapling, more like 1 every 4 or 5. Is this thing even working? The *branch cutter* is still way better than this.

Let's just copy the other worthless IC2 tools that use RE-Batteries and change palladium -> SSteel, osmium -> SSteel, PM -> something? A Plate? Same changes to the scoop version. Though that one's probably decent, you can still make the GT version as well.

**Comment by Dream-Master** [comment]
@Prometheus0000 are we need to change a quest ?

**Comment by Prometheus0000** [comment]
No
