### ISSUE TITLE
Advanced alchemical furnace output bug

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6918]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Use the advanced alchemical furnace to melt and output essentia (The thaumcraft multiblock, not the thaumic bases one)
#
#### What happened instead? (Attach screenshots if needed)
Quite rarely, with no obvious trigger, the output of essentia gets stuck, no more essentia can be output. When an output block is right clicked with an essentia resonator, it reports "0 cognitio essentia" which is normally not possible, since it only reports essentia types which are in amounts of at least 1.
![image](https://user-images.githubusercontent.com/17787093/98992931-ad831a00-2525-11eb-99d9-ede5c45989cc.png)
![image](https://user-images.githubusercontent.com/17787093/98993012-cbe91580-2525-11eb-95f7-14d4b7c80720.png)
This has happened to me 3 times, and it is always cognitio essentia that is reported.

It can be fixed when it happens by using a gregtech plunger, or breaking and reforming the multiblock.

**Comment by KiloJoel** [comment]
I believe this is the cause: Books and enchanted books appear to contain cognitio with an amount of 0, changing this value or removing the aspect should fix this bug.
![image](https://user-images.githubusercontent.com/17787093/99065576-7fdab700-259f-11eb-9729-8b9658649ff2.png)

**Comment by Prometheus0000** [comment]
Unfortunately, I don't know where this is set, it's not in the .zs file at least.

**Comment by KiloJoel** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6948

**Comment by Prometheus0000** [comment]
Did you check to see this actually prevents the bug? Oh, also, you can run a /dumpaspects command to dump a file to see if there's any more with zero, alk gave me a fixed version of gt++ for that that actually works if you want to look through it. There's quite a few x0 ones.
[AspectInfo.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5555422/AspectInfo.zip)

**Comment by KiloJoel** [comment]
Yes, does prevent the bug. Also wow that's a lot of x0, is that the full list that you've put there?

**Comment by Prometheus0000** [comment]
It still doesn't say it's finished, but does stop collecting stuff in the file. It seems to be randomly ordered, so I can' tell if it's missing stuff.

**Comment by KiloJoel** [comment]
> alk gave me a fixed version of gt++ for that that actually works

I'm a little confused by what you mean by this, what works?

**Comment by Prometheus0000** [comment]
The /dumpaspects command.

**Comment by KiloJoel** [comment]
Ok, I'll have a go at fixing all of these

**Comment by KiloJoel** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6950
