### ISSUE TITLE
Official Server Config Differences

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6919]
Galacticraft:
B:LoadOnLogin in chunkloading.conf, B:"Enable Sealed edge checks" in core.conf, and B:launchControllerChunkLoad in planets.conf to false

**Comment by Prometheus0000** [comment]
@Dream-Master You seem to have forgotten to do this.

**Comment by boubou19** [comment]
i'll do it, as well as disabling the chunkloading ability from the puppet shelves.

**Comment by boubou19** [comment]
done.
