### ISSUE TITLE
Ender Tanks and Chests Lag

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6925]
We have a fork now, so anyone wanting to not have lag in high-end bases who can code, feel free to unlagify it.
https://github.com/GTNewHorizons/EnderStorage

The 1.8+ version (for backporting stuff) is at 
https://github.com/TheCBProject/EnderStorage

**Comment by GTNH-Colen** [comment]
https://github.com/GTNewHorizons/EnderStorage/blob/master/src/codechicken/enderstorage/storage/item/EnderChestRenderer.java

Code seems to be here, not sure what would happen if we just yanked it out. Ideally we can just replace it with a black square, seems much more lag friendly and doubt most players would even notice tbh.

**Comment by Prometheus0000** [comment]
Someone should probably test if doing so actually affects the lag first.

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/99160156-11d2e480-26b2-11eb-96cf-ef0ddd1f1b8d.png)
If someone can get something out of that. I had a chest and tank in a new world.

**Comment by Glease** [comment]
You can't just remove the renderer, otherwise you won't be able to get the color of button, also the whole thing willl otherwise be invisible. 

The profiler result basically says the raytracing is slow. The CB raytracer is really weird. It runs a loop. Each loop generate one piece of data, but only the last non null value is used and the preceding one will all get discarded no matter what. I guess we can try run the loop in reverse order and use the first nonnull value instead. This will prevent a lot of unnecessary computations, but this indeed require us to either fork or ASM the CCL.

**Comment by Prometheus0000** [comment]
Well, something is causing the lag. Someone suggested it was the fancy effect on the inside bottom? Removing that is what Colen means.

**Comment by Glease** [comment]
I just realized you were looking at server thread. If you see a fps drop but no tps drop, then you should look at client thread.

If you say the FX then just remove [these lines](https://github.com/GTNewHorizons/EnderStorage/blob/15b06718eb31fc715cfd924a17259f0a6b858f46/src/codechicken/enderstorage/storage/item/EnderChestRenderer.java#L26-L27) and see if it can have an improvement

**Comment by Prometheus0000** [comment]
I've never experienced the lag from them myself, so I dunno which type it is. @GTNH-Colen ?

**Comment by GTNH-Colen** [comment]
It is FPS lag, this same issue occurs if you place down too many end portals in one spot. It was just never optimised to have too many of these textures in the same spot given in vanilla you can have like 9 tiles max. That's why I think we should just outright remove it, really adds no benefit given it's not even visible when the chest is closed.

**Comment by repo-alt** [comment]
This is holoinventory lag

**Comment by Prometheus0000** [comment]
It uses codechicken code?

**Comment by repo-alt** [comment]
Holoinventory uses ray tracing, which is, kind of, rendering on a server. I don't say tanks rendering is generally good, but usually it should cause only client lags

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/99199621-6cca1180-276e-11eb-8e9d-bd03ea340f9c.png)
![image](https://user-images.githubusercontent.com/8517039/99199674-c9c5c780-276e-11eb-8060-170c6c9e2ddc.png)

**Comment by Prometheus0000** [comment]
60 EChests
![image](https://user-images.githubusercontent.com/8517039/99211436-4fa93900-2796-11eb-9765-d95ed49ef310.png)
![image](https://user-images.githubusercontent.com/8517039/99211460-5a63ce00-2796-11eb-9100-4ddbec7b036f.png)
![image](https://user-images.githubusercontent.com/8517039/99211510-710a2500-2796-11eb-927a-71a7deaa9e06.png)
![image](https://user-images.githubusercontent.com/8517039/99211537-7d8e7d80-2796-11eb-9184-ecdb72eb2614.png)

**Comment by Prometheus0000** [comment]
60 ender tanks
![image](https://user-images.githubusercontent.com/8517039/99211970-baa73f80-2797-11eb-9ad6-e22d6550efc4.png)
![image](https://user-images.githubusercontent.com/8517039/99211980-c1ce4d80-2797-11eb-8cb0-b0c794f95eba.png)
![image](https://user-images.githubusercontent.com/8517039/99211992-ca268880-2797-11eb-850f-5f9308217310.png)

**Comment by Prometheus0000** [comment]
I made a build of ender storage with the end portal render as a config option, does anyone want to try it out? Assuming you have FPS problems and could actually see if there's a difference.


[EnderStorage-1.7.10-1.4.7.null-universal.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5742684/EnderStorage-1.7.10-1.4.7.null-universal.zip)

**Comment by Prometheus0000** [comment]
Testing has proven that having the FX render set to off improves FPS. I don't know if they still lag _some_ or not, but I guess someone can open a new ticket on it if they intend to investigate.
