### ISSUE TITLE
Transfer Node (Items) and Retrieval node (Items) are too expensive

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6927]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### What happened instead? (Attach screenshots if needed)
The item transfer node from extra utilities has a much higher resource cost than other similar items.

So primarily, I almost never see them being used, which is a pretty good indication that their cost-usefulness balance is off.

To make 16 of them, it costs:
208 steel, 32 lv motors, 48 brass, 16 lv circuits, 96 rubber and more.

To make 16 Item conduits, it costs:
16 electrum, 16 pulsating iron, 16 PE

They are not particularly better than item conduits, they just function in a different manner. They also don't work as well for larger setups because transfer speed reduces when the pipe lengths are greater.

Translocators are also a lot cheaper than them, so buffing the transfer nodes would provide an alternative cheap way of moving items short distances quickly by using a stack upgrade (with less TPS impact too).

In terms of retrieval nodes, they cost 4 hv circuits and 3 transfer nodes each, among other things. They are potentially more useful, so a greater cost does make sense, but even then, I think 4 hv circuits is a bit too much.
#
#### What do you suggest instead/what changes do you propose?
I suggest that:
Transfer node recipe should make 4 rather than 1.
Retrieval node recipe should make 2 rather than 1.

**Comment by yukieiji** [comment]
> The item transfer node from extra utilities has a much higher resource cost than other similar items.

ProjectRed and GregTech, Thaumcraft's transport item are cheaper than transfer node, even if it's long distance or short.

> They are not particularly better than item conduits, they just function in a different manner. They also don't work as well for larger setups because transfer speed reduces when the pipe lengths are greater.

Transfer Nodes (Items) and Retrieval Nodes (Items) are better(TPS, simple, etc...) than other modes of transport items one-to-many or many-to-one. And the feature is even better with upgrades.

> Translocators are also a lot cheaper than them, so buffing the transfer nodes would provide an alternative cheap way of moving items short distances quickly by using a stack upgrade (with less TPS impact too).

Translocators can only transport one block, and it would be foolish to transport more than that with Translocators.

**Comment by KiloJoel** [comment]
> ProjectRed and GregTech, Thaumcraft's transport item are cheaper than transfer node, even if it's long distance or short.

I don't understand what you mean by this. What is thaumcraft's transport item? Is this in support of my point?

> Transfer Nodes (Items) and Retrieval Nodes (Items) are better(TPS, simple, etc...) than other modes of transport items one-to-many or many-to-one. And the feature is even better with upgrades.

Being better on TPS should be incentivised, so if anything, I think that's an point in favour of them being cheaper. And Ender IO conduits can also be upgraded, and can also do one to many, many to one, as well as the coloured networks making pipe sharing possible for much more compact and less costly setups.

> Translocators can only transport one block, and it would be foolish to transport more than that with Translocators.

Transfer nodes become 1/2 the speed when using a 2 block long connection compared to 1, so if you want things to move the fastest, you are also only looking at moving things one block.

**Comment by yukieiji** [comment]
>I don't understand what you mean by this. What is thaumcraft's transport item? Is this in support of my point?

Aren't golems, magic mirrors, transvector interfaces, etc. a means of transporting items?
Thaumcraft's transport of golems is possible with 9 wheat and a small amount of Essentia.

> Being better on TPS should be incentivised, so if anything, I think that's an point in favour of them being cheaper. And Ender IO conduits can also be upgraded, and can also do one to many, many to one, as well as the coloured networks making pipe sharing possible for much more compact and less costly setups.

Transfer node can perform many-to-one and one-to-many transports(one network) in a simpler setup and lower TPS than other transport methods. and these can be achieved without any disadvantages. Other modes of transport have disadvantages (complexity of setup(EnderIO, ProjectRed), slow transport speed(EnderIO, ThaumCraft), etc.).
Isn't that the advantage of Transfer node and the reason for its expensive?

> Transfer nodes become 1/2 the speed when using a 2 block long connection compared to 1, so if you want things to move the fastest, you are also only looking at moving things one block.

I don't think there is any advantage to using TPS other than TPS because other modes of transportation are better in terms of speed and transportation stability in one-to-one transportation (although the advantage of TPS may not exist because Transfer node also requires a search).
