### ISSUE TITLE
[Pam's harvestcraft] (MISSING RECIPES: Mochi, Jam roll, Paneer, Paneer tikka masala) (MISSING TEXTURE: Chocolate roll) (TYPO: Grapfruit juice -> Grapefruit juice)

### ISSUE THREAD

**Issue by omegablasterzeta** [GTNewHorizons/GT-New-Horizons-Modpack#6928]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
@bombtrack's unofficial.
#
#### What did you try to do, and what did you expect to happen?
I tried to see the recipes for Mochi, Jam roll, Paneer, and Paneer tikka masala. I expected the recipe to show up.
Chocolate roll doesn't show a texture.
Grapefruit juice has a typo.
#
#### What happened instead? (Attach screenshots if needed)
There are no recipes.
Chocolate roll doesn't have a texture.
Grapefruit juice has a typo.
#
#### What do you suggest instead/what changes do you propose?
Adding the recipes.
Adding the texture.
Fixing the typo.

**Comment by Prometheus0000** [comment]
Wiki: (for reference)
![image](https://user-images.githubusercontent.com/8517039/99129862-c0a4f100-25dc-11eb-8763-39ea3b07a86f.png)
It might not've had one in 1.7.10 though

**Comment by Dream-Master** [comment]
we have pams source so easy to add

**Comment by omegablasterzeta** [comment]
This issue can be closed if the correspondent branch with the fixes in the harvestcraft repo is merged to the main branch.

**Comment by Dream-Master** [comment]
@omegablasterzeta i will close this after 2.0.9.3 release
