### ISSUE TITLE
Multi Descriptions

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6930]
I've been looking at the Kekztech stuff for the info vs structure stuff, and it seems pretty cool.
![image](https://user-images.githubusercontent.com/8517039/99141040-de8e4800-2614-11eb-9205-6bf42ec5791a.png)
![image](https://user-images.githubusercontent.com/8517039/99141044-e51cbf80-2614-11eb-9e6a-6c84ce9657b6.png)
It doesn't seem particularly hard to do, so I was wondering what other people think of changing to the same format?
The MultiBlockTooltipBuilder file seems easy enough to move over to GT5U, assuming we don't want to make Kekztech a dependency.

**Comment by Dream-Master** [comment]
Yea why not good idea.
