### ISSUE TITLE
Tier 2 rocket recipe issue

### ISSUE THREAD

**Issue by secirpac** [GTNewHorizons/GT-New-Horizons-Modpack#6931]
#### Which modpack version are you using?
2.0.9.2d-dev
#
I need Radon to craft Tier 2 rocket (EV emmiter&sensor for Rocket Control Computer T2), but I can't get Radon before I have the rocket.

**Comment by alphaNOVAircraft** [comment]
I think you can get it but it for sure is extremly time intensive and not intended

**Comment by glowredman** [comment]
I'm currently working on it
