### ISSUE TITLE
[RFC] increase the money you can get on the official servers

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6932]
I see a lot of lag related with mobs spawning underground around players' bases (or under). So to reduce the lags from the mobs, I want the players to be incentivized to claim their base, and the surrounding chunks (server view distance is set to 6 chunks). But it's a lot of money. 

However, i don't want the players to get 1M$/day, because there would have no point anymore to have the ranking system.

So what i have in mind is to rework the incomes you can get from the jobs (apart from Miner, Digger, Hunter, WoodCutter, the others jobs are useless currently), and increase the hourly money limit.

The current meta to get money is to chop down Sacred trees with a lumber axe, but obviously it will be changed to something else less laggy, as it loots a lot of items on the ground.

What are your thought? what do you suggest to make the other jobs viable? Do you think we should add jobs?

**Comment by S4mpsa** [comment]
Change the ramping up of the claim cost from 50/chunk to 10/chunk so people can claim more instead?

**Comment by Dream-Master** [comment]
be careful with balancing. Not that people claming the whole map in a very short time.

**Comment by Cinobi** [comment]
With rank-cost increase only i think.
<3 @fluid @falsecolor

**Comment by boubou19** [comment]
The town cost for the creation is 1000 (to create the town) + 200 (to claim the first chunk of the town)
A town can have 625 chunks claimed. There is an additional cost of 50 for each next chunk to claim.
This mean that you need 1000+625*200 + 50 * (624*625/2) = 9876000$ for each town.

A player can be in 16 towns, so he can own 16 maxed towns for 158M, for a total of 10000 chunks.

The map of the officials is 24k*24k blocks, so 1500*1500 chunks= 2,25M chunks. So it would take 225players to claim the map, at a cost of 158M$ per player (impossible)

Now: if we reduce the additional cost for the next claims from 50 to 10, the price of a fully claimed town is 1000+625*200 + 10 * (624*625/2) = 2076000$ (a bit more than the elite rank currently), so 16 towns would cost 33216000$ per player (still unrealistic to think we will have 225 players grinding 33M$).

So, that would be indeed a good buff.

But choping down huge trees to reach the hourly money limit very fast is a bit dumb (also i already had to clean a lot of unfinished sacred trees because some player were to lazy to finish them).

What do you think about that?

**Comment by LewisSaber** [comment]
make limit daily?

**Comment by boubou19** [comment]
making the limit daily will ease the things, as it will conserve the same total limit, but will make it easier to earn money, as we can't physically reach the daily limit each hour. That's a good suggestion.

Any feedback about the current job tasks?

**Comment by combusterf** [comment]
I have never got a notification on hitting the maximum for explorer, despite having walked the full 6km between player's bases, or even the 14km from Stargate to an old rocket landing site. I'm not sure how it counts exactly, but it would be nice to recalculate the rate so the maximum corresponds to a certain fraction of exercise, say 10 or 15 minutes of unbuffed walking per hour.

**Comment by boubou19** [comment]
iirc you get explorer points when you see chunks not seen by the other players (likely to be on the borders of the map in ow on delta)

**Comment by z3r0b0t** [comment]
Azuna from Delta here!

Here's my 2 cents about the current job and tasks system.

I believe the current job tasks are... "Ok", I can easily think of ways to balance them, not that they are a perfect solutions. E.g for woodcutter, and this could be applied to other jobs as well I think, easy to farm trees such as sacred oak, spruce and any 2x2 should really not allow to reach the daily/hourly IMO; unless you're farming it for the full hour.

This way, I'm thinking lazy people and people and general won't just do this, but if they really need to, they can but they have to spend the time for it. While on the other hand, I would make rare trees return more money. In this system, high ranks would have easier ways to reach the limits with rare trees, but I believe that is already an issue.

What I also want to point out is with the current system there are only 2-3 jobs viable, and we can take ... 3 jobs. So the current system could simply be replaced with an hourly rate depending on your rank and I'm sure there would be no difference 🤷‍♂️

Another point about the current system, it's a system that doesn't promote interactions, I would LOVE a system where you rely on interacting with others, through shops and whatnot. A much more realistic economic system (I believe we already have a system for this but no one uses it on delta), plus it would enhance the community. Let's be crazy, this system could allow players from different servers to interact, that might be less realistic tho 😅

**Comment by boubou19** [comment]
Balancing around ranks seems a bit weird: ranks aren't related to GT tiers at all (you can spam redstone on a TiCo hammer to get it insta break cobble, then mine cobble for like 15min and poof! easy reach of the hourly limit).

A part from Miner, Digger, Hunter and WoodCutter, all the other jobs seems to be balanced around vanilla.
- brewer/enchanter can't be done until some thaumcraft if were not lucky to find a brewing stand/enchanting table in a roguelike dungeon, or if you did not bothered finding a HEE Tower in the End.
- fisherman is super boring as it needs the player to fish, not very well fitted for GT:NH.
- crafter is possible to level until you reach something to automate your crafts, but the items are all balanced around vanilla(you won't craft a lot of anvils to get money from this job, even if it's 18$/anvil)
- WeaponSmith can be done, gives a good xp and money per craft, and you can endlessly spam the job once you have MV fluid extractor/solidifer, but this is very borring.
- Explorer job is harder to level in overworld as the map is getting older, so a boost is required for it, but don't know how much we should boost it (and we need to check if exploring a random dim works too or just the overworld)
- Farmer is balanced around vanilla, but it would fit perfectly the early game, given we have pam's harvest craft and the incentive to craft food to get extra hearts
- Builder could be interesting to buff and add more building materials than it currently has
- Miner is perfectly balanced IMO, no need to touch stuff there, except maybe adding some ores you can encounter in the bedrock dim for exemple.
- Digger should be a bit buffed, in comparison of the Miner job, you gain way less to mine common blocks such as dirt for the Digger(0,22$) than cobble for the Miner (2,06$)
- Hunter fits perfectly with the pack because grinding mobs is a good source of a lot of stuff, especially for early game, but we cannot add other mobs, only vanilla mobs
- WoodCutter is the easiest way to gain money, can lead to some lag spikes if you grind the Sacred oaks, and most of the players chop only the trunk without cleaning the rest of the tree, so it pollute the server. I suggest a nerf of it to avoid that.

the equation behind the money limit is: 500+1000*(totallevel/10). Because you can have 3 jobs at the same time with level 200 each, it makes the max money limit to be 60,5k$.

With the limit changing from hourly to daily, it would need 412 levels for a player to get a 1M$ daily limit, but only 4 players (me included :P) have more than 412 jobs level, all the servers cumulated. So it seems reasonable, and maybe it will make the Nolife rank actually doable.

**Comment by z3r0b0t** [comment]
I would 100% agree with a nerf for woodcutter, trees that grows too much wood or too fast should reduce the money they give and maybe even experience, I would imagine there are some qoods that are harder to find but would yield similar results such as bamboo, silverwood, etc. Rarer trees that can still be found by any players, I would buff those.

**Comment by SaloEater** [comment]
- Hunter fits perfectly with the pack because grinding mobs is a good source of a lot of stuff, especially for early game, but we cannot add other mobs, only vanilla mobs

If we are unable to add, shall we make our own "jobs" mod then? I mean, like, why do we restricted to this vanilla(?) plugin on this very modded server.
I am ready to learn some java in order to.

**Comment by GTNH-Colen** [comment]
> 
> Another point about the current system, it's a system that doesn't promote interactions, I would LOVE a system where you rely on interacting with others, through shops and whatnot. A much more realistic economic system (I believe we already have a system for this but no one uses it on delta), plus it would enhance the community. Let's be crazy, this system could allow players from different servers to interact, that might be less realistic tho 😅

This is something I've brought up before but is very tricky in modded minecraft due to the fact you can usually massively overproduce a resource later on (Not to mention tier skipping). Players could sell millions of copper for pennies given the cheap cost of it at endgame and severely disrupt the balance of other players, the only way I could see maybe getting around this is to have shops that are restricted to that tier and below. Something like you hand in an item from said tier and then it adds to your permissions the ability to enter the zone of this shop, similar to how delta does portal restrictions with a rocket. I'd be up for trying to set up something akin to this if people were interested.

**Comment by combusterf** [comment]
I went ahead and ran some numbers on explorer. Basically, I ran from the Mars stargate to 10000,10000 on a freshly reset map.

It took me 58 minutes, I earned $6939, and gained 6696 XP in explorer (went from level 34 to 35), and 524 XP in hunter (stayed at level 35, I got cobwebbed a few times despite trying to be evasive)

If I compare that to chopping down my patch of redwoods, I'd give explorer a 5x income boost to make it competitive

**Comment by GTNH-Colen** [comment]
> I went ahead and ran some numbers on explorer. Basically, I ran from the Mars stargate to 10000,10000 on a freshly reset map.
> 
> It took me 58 minutes, I earned $6939, and gained 6696 XP in explorer (went from level 34 to 35), and 524 XP in hunter (stayed at level 35, I got cobwebbed a few times despite trying to be evasive)
> 
> If I compare that to chopping down my patch of redwoods, I'd give explorer a 5x income boost to make it competitive

While this would make it more competitive I'm unsure we should be encouraging players to fly around the map for hours in order to get cash (especially since they can just hold down W in a dim with no world borders and make millions). Not to mention the lag implications.

**Comment by Eason134HK** [comment]
![image](https://user-images.githubusercontent.com/59776356/106414165-ebd60880-6486-11eb-8bf7-3c51b0e2c7e8.png)

add rainforest oak to the woodcutter jobs it is a less laggy tree and also have lots of wood per tree

**Comment by boubou19** [comment]
after thinking a little about jobs, this is what i came up with:

- disable the points earning when you reach your money limit. 
This is ridiculous: players are never short on jobs points because they always earn them, so they can buy stupid amount of chunkloader coins (someone on delta has more than 40 years worth of chunkloader coins)

- change the money limit.
Right now everyone is grinding money like crazy, and it makes the elite rank lose its meaning. To avoid that, here are some options i came up with to mitigate this issue:
  1.  make the jobs xp harder to get
  2.  make the jobs xp impossible to get when you have reached money limit (unpaid overtime work is meh)
  3.  add twice more levels but divide the money limit by two
  4.  reduce the max level of jobs
 
  I would prefer enforcing the 2nd solution, as it seems to be the best solution:
   - it will reduce the known (and unknown) laggy setup usages for leveling, while not impacting the money limit when the jobs are maxed.
   - it will make the ranks harder again to get
  But i'm open for discussion on that.

- balancing stuff:
  - woodcutter job
    - removing sacred oak wood and redwood (laggy)
    - adding rainforest wood
    - change how the money per log is calculated:
       -  defining a fixed amount of money per tree
       -  dividing it by the average amount of logs so it makes the money per log
  - brewer/enchanter
    buff those jobs as i don't see a way to abuse it as much as woodcutter or builder and they are availiable past mv if you don't try to find brewing stand/ enchanting table in the world gen
  - fisherman
    i don't know what to do for this job, and i feel like we should remove it because afaik, fishing is not very developped in GT:NH
  - Crafter
    will be the most painful to configure, but would be worth to set up, provided it can accept non vanilla items. (i have no idea of the xp/$ values, nor what kind of items to add in this job)
  - WeaponSmith
    should remain untouched (you can make a loop from crafted metal armors with the combo fluid extractor/fluid solidifier)
  - Explorer
    xp and money boost because in the overworld the map is already almost totally explored, and in the other dims, this will reduce the amount of map generated to level this job. (the boost will be determined after all the other jobs has been balanced, otherwise this could become an issue if it becomes one of the best jobs)
  - Farmer
    add pams food crafting and pams harvesting (i have no idea of the xp/$ values)
  - Builder
    add more building materials
  - Miner
    change the gt ores giving money when placed (this is totally stupid)
  - Digger
    buff the common blocks (dirt/sand/gravel) to match common blocks of miner job
  - Hunter
    nothing to change, as you can abuse it with mob spawners and only vanilla mobs can be added/modified

What do you think about it?

**Comment by KiloJoel** [comment]
>
>         change the gt ores giving money when placed (this is totally stupid)
>  

It doesn't give money for this, it subtracts

**Comment by Connor-Colenso** [comment]
>   * Crafter
>     will be the most painful to configure, but would be worth to set up, provided it can accept non vanilla items. (i have no idea of the xp/$ values, nor what kind of items to add in this job)

This is a tricky one just because of how modded minecraft tends to exponentially snowball in terms of resources. If say an LV macerator made $500 that could be cool and rewarding for someone in LV but if you're in ZPM you can just craft hundreds if not thousands for virtually nothing.
