### ISSUE TITLE
Long Superconductor Base UV/UHV Rods are missing a forge hammer recipe.

### ISSUE THREAD

**Issue by Darkstar1712** [GTNewHorizons/GT-New-Horizons-Modpack#6933]
#### Which modpack version are you using?
2.0.9.2d
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
I tried to make some Long Superconductor Base UV Rods for the UV dynamo hatches and noticed that there is no forge hammer recipe. It's not a huge problem as there are other recipes but all the other Superconductor Base ingots have forge hammer recipes so it feels like there should be one.

**Comment by Prometheus0000** [comment]
Seems to be added by the coremod.
