### ISSUE TITLE
Increase the require amount in quest "You are not prepared!!!"

### ISSUE THREAD

**Issue by SaloEater** [GTNewHorizons/GT-New-Horizons-Modpack#6934]
#### Which modpack version are you using?
GTNH 2.0.9.0

#
#### If in multiplayer; On which server does this happen? 
Official server ETA

#
#### What did you try to do, and what did you expect to happen?
I tried: create the "Smeltery" multiblock from mod "Tinker's Construct"
I expect: create multiblock with all necessary structures

#
#### What happened instead? (Attach screenshots if needed)
I crafted not enough item "Unfired Seared Brick" by following the quest tasks.

#
#### What do you suggest instead/what changes do you propose?
Increase the required amount of these items:
Sand: 123 -> 126
Gravel: 123 -> 126
Clay Dust: 82 -> 84

**Comment by SaloEater** [comment]
Quest is fine, probably i made a mistake while crafting.

**Comment by SaloEater** [comment]
@Prometheus0000 i prolly miscalculated ingame, can you revert this suggestion?

**Comment by Prometheus0000** [comment]
I already did it, then reverted it.

**Comment by Dream-Master** [comment]
@SaloEater @Prometheus0000 is the fix now included or not ?

**Comment by Prometheus0000** [comment]
They said they were wrong, so I undid it.

**Comment by Dream-Master** [comment]
can you undo it again ? @Prometheus0000

**Comment by Prometheus0000** [comment]
You mean redo it? But he said he was wrong? So you want me to make it wrong on purpose?

**Comment by Dream-Master** [comment]
no if it is now fixed all good
