### ISSUE TITLE
Vortex attenuators hardness is 0

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6940]
# Which modpack version are you using?
2.0.9.0QF4
#
#### What happened instead? (Attach screenshots if needed)
When creating a planar vortex, it will destroy one block before being stabilised, and since vortex attenuators can be destroyed by the vortex (hardness is below 10), this can occasionally cause the whole thing to collapse through bad luck.

They will also be destroyed by punching them, but not return the item, because they need a pickaxe to harvest them. (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3037#issue-328803877)
#
#### What do you suggest instead/what changes do you propose?
Merge pull request to change vortex attenuators to 10 hardness

#https://github.com/GTNewHorizons/ThaumicHorizons/pull/10

side note: first time making a pull request, did I do this right?

**Comment by KiloJoel** [comment]
https://github.com/GTNewHorizons/ThaumicHorizons/pull/10

**Comment by yukieiji** [comment]
The Vortex Attenuator has a range of 10 blocks, and I don't think the Vortex Attenuator is going to be destroyed with creating planar vortex.
Therefore, the issue here is that you can accidentally destroy it with a punch, and wouldn't it be over-specified to set it to the same hardness as the OMT hardwall (T1)?

**Comment by KiloJoel** [comment]
> Vortex Attenuator has a range of 10 blocks, and I don't think the Vortex Attenuator is going to be destroyed with Vortex Attenuator setup around 7 blocks and creating planar vortex.

I have tested this, it can destroy them even at max range.

> Therefore, the issue here is that you can accidentally destroy it with a punch, and wouldn't it be over-specified to set it to the same hardness as the OMT hardwall (T1)?

The vortex attenuator is significantly more expensive than T1 hard wall. Also it's only hardness, its blast resistance is still 3, compared to the 10 of the wall. I don't really see the issue.

**Comment by KiloJoel** [comment]
> I have tested this, it can destroy them even at max range.

To give more specific info, it uses a raycast with random direction and 16 block range to destroy blocks.

**Comment by yukieiji** [comment]
I think destroyed block that at the proper distance(Vortex Attenuator will be installed) and a split second when the planar vortex is created is soft block with a hardness of less than 1.
Does the Vortex Attenuator at that proper distance need to have the same hardness as the OMT hardwall (T1)?

**Comment by yukieiji** [comment]
I'm still testing, but so far the Vortex attenuator is not broken when creating planar vortexes....

**Comment by KiloJoel** [comment]
It destroys any block with a hardness 0 <= h < 10

**Comment by yukieiji** [comment]
Have you tested that a block with high hardness breaks(over 1.0) in a split second before the Vortex Attenuator's beam hits the planar vortex?
As far as I tested, only once did a block with 1.5 Hardness break, and no Vortex attenuator with 0 Hardness was ever broken.

**Comment by yukieiji** [comment]
Currently, planar vortexes take the advantage of preventing the destruction of the Vortex Attenuator by bearing the disadvantage of taking the proper distance and size, but this change eliminates the disadvantage altogether.

**Comment by KiloJoel** [comment]
there is only one check for hardness, and it is the one i described above

there is no big advantage to making the attenuators further away currently, they can be destroyed either way

this is a simple QOL change, i don't understand why you are so against this

**Comment by yukieiji** [comment]
You may be carrying around a Vortex Attenuator because you can temporarily disable HungryNode, but this change doesn't take that into account.

**Comment by yukieiji** [comment]
Stabilizing the planar vortex provides enormous benefits, but it has the disadvantage of potentially destroying the Vortex Attenuator and causing it to run out of control. If the Vortex attenuator is destroyed and you lose control, you can still stabilize it by reinstalling a new Vortex attenuator. The extra Vortex attenuator also helps to make the HungryNode temporarily ineffective.
Isn't this change, which eliminates that disadvantage, lazy?

**Comment by yukieiji** [comment]
> there is no big advantage to making the attenuators further away currently, they can be destroyed either way
As far as I can tell from the Code, the determination of the coordinates of the block to be destroyed is normally distributed with the mean being the coordinates of the planar vortex, so the possibility of the Vortex Attenuator not being destroyed increases by moving away from the planar vortex.
