### ISSUE TITLE
Thaumcraft offensive foci buff

### ISSUE THREAD

**Issue by AiramProvoker** [GTNewHorizons/GT-New-Horizons-Modpack#6941]
Offensive foci should be buffed.
Why? Let's make a comparison:

Tier-wise, all foci can be made starting HV. At HV, the average GTNH player already has a crossbow, ~~ a very balanced weapon~~, with at least 40-100 hearts of damage and 0.25-1s  reload time, which makes 95% of enemies a breeze. 

What does the player have if he decides to invest into offensive magic?
Well, he has the standard issue thaumaturge fire focus... which deals... roughly 5 damage (2.5 hearts) per second? Okay, but what if we upgrade it? Potency 3 + beam upgrade puts it at slightly more respectable ~4-5 hearts per second. That is still miles below an average crossbow.
The situation is pretty much equal with the other vanilla TC offensive foci. Another underpowered contender for buffing is the Dark Matter focus from the Tainted Magic addon. Fully upgraded, it deals 13 (6.5 hearts) of damage + Wither Debuff for 7 seconds, all the cost of a *whooping primordial pearl*, and with the drawback of applying Temporary Warp to the player, and this is not counting all the research and exploration.

The actual problem stems from TiCo weapons (especially crossbows), but rather than nerfing those, I would consider buffing other options.
I know very few players even consider PVE in GTNH and even less use offensive foci, but it would be interesting to hear everyone's opinion on the matter.

**Comment by glowredman** [comment]
I agree, TiCon weapons in general and the crossbow in particular are way to strong. But I think we shouldn't buff all other options to their niveau, but rather nerf TiCon. We can still buff the foci if they are not viable afterwards.

**Comment by yukieiji** [comment]
I agree, I think we should review TC attack magic as a whole, not just foci.

**Comment by Prometheus0000** [comment]
Feel free to ASM it in if you can, but changing the crossbows sounds way easier. I already made a proposal about it awhile ago.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5494

**Comment by draknyte1** [comment]
If you want TC ASM’d, just say what and how. I’ll add it to AlkCore along with the rest of the TC changes/fixes.
