### ISSUE TITLE
Forge Microblocks causes crashes if you try to destroy them.

### ISSUE THREAD

**Issue by Saika-Takehiko** [GTNewHorizons/GT-New-Horizons-Modpack#6942]
#### Which modpack version are you using?
Latest
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
I tried to remove an inverted white lamp slab using my pickaxe and then other tools.
#
#### What happened instead? (Attach screenshots if needed)
It crashed me, so far I've tried with pickaxe and wrench. The first couple of times it crashed me to menu and then it crashed the game as well.
![2020-11-16_04 21 38](https://user-images.githubusercontent.com/58763784/99209442-792c8980-27c3-11eb-895c-717b06e0605a.png)
![2020-11-16_04 21 49](https://user-images.githubusercontent.com/58763784/99209447-79c52000-27c3-11eb-91a3-b492965dc8b5.png)

#
#### What do you suggest instead/what changes do you propose?
So far what I've looked up is that Forge Microblocks has issue with Forge versions higher than 1180 but I might be wrong here so don't take my word for it. The mod still works without issues when crafting other things using microblocks but placing a microblock and then trying to remove it seems to cause the crashes

**Comment by leagris** [comment]
> #### Which modpack version are you using?
> 
> Latest

Unfortunately `Latest` is not a version of the pack.
The pack version you use can be seen on the game menu.

> #### If in multiplayer; On which server does this happen?
> 
> Epsilon
> #### What did you try to do, and what did you expect to happen?
> 
> I tried to remove an inverted white lamp slab using my pickaxe and then other tools.
> #### What happened instead? (Attach screenshots if needed)
> 
> It crashed me, so far I've tried with pickaxe and wrench. The first couple of times it crashed me to menu and then it crashed the game as well.

Crash logs would be absolutely welcome here, because screen shots will not tell why it crashed while removing the block.

If you use Optifine, try without it.

**Comment by Saika-Takehiko** [comment]
> > #### Which modpack version are you using?
> > Latest
> 
> Unfortunately `Latest` is not a version of the pack.
> The pack version you use can be seen on the game menu.
> 
> > #### If in multiplayer; On which server does this happen?
> > Epsilon
> > #### What did you try to do, and what did you expect to happen?
> > I tried to remove an inverted white lamp slab using my pickaxe and then other tools.
> > #### What happened instead? (Attach screenshots if needed)
> > It crashed me, so far I've tried with pickaxe and wrench. The first couple of times it crashed me to menu and then it crashed the game as well.
> 
> Crash logs would be absolutely welcome here, because screen shots will not tell why it crashed while removing the block.
> 
> If you use Optifine, try without it.

@leagris  The modpack version is: 1.2.0.347

[crash-2020-11-16_03.51.41-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5544520/crash-2020-11-16_03.51.41-client.txt)

**Comment by Prometheus0000** [comment]
That's not a real version. It should be 2.0.something

**Comment by Saika-Takehiko** [comment]
> That's not a real version. It should be 2.0.something

Ah, you mean the "GTNH" Modpack itself...  It's 2.0.9.0

**Comment by boubou19** [comment]
epsilon runs 2090qf4. It's a known and already reported bug (don't have time to check other issues rn) Don't cut the project red lamps with forge microblocks

**Comment by Dream-Master** [comment]
@boubou19 linke the duplication issue and we close it after. Thanks

**Comment by boubou19** [comment]
#359 and #6419
