### ISSUE TITLE
GT5 Small miner bug?

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#6943]
#### Which modpack version are you using?
2.0.9.3dev
#
#### If in multiplayer; On which server does this happen? 
My own
#
#### What did you try to do, and what did you expect to happen?
I placed down a small lv single block miner and it mines every ore ecxept GT based ones. That makes it a bit more useful than a stick.
#
#### What happened instead? (Attach screenshots if needed)
It doesn't mine GT ores, only other modded ones.
#
#### What do you suggest instead/what changes do you propose?
Fix it, might have something to do with a GT5U ore overflow error, but I am not sure.
Anyone up for testing this on Eta to make sure i havn't derped something up in my server install.

**Comment by repo-alt** [comment]
@Ethryan I may drop you a (probably) fixed version to test. Ping me in discord if interested.

**Comment by Dream-Master** [comment]
@repo-alt can you link the fix ? thanks.

**Comment by Ethryan** [comment]
This one i think: [Link](https://github.com/GTNewHorizons/GT5-Unofficial/pull/348)

**Comment by Ethryan** [comment]
The fix works on my server, nice job
