### ISSUE TITLE
Aqua creepers are laggy

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6945]
#### Which modpack version are you using?
2090QF4
#
#### If in multiplayer; On which server does this happen? 
eta
#
#### What did you try to do, and what did you expect to happen?
Was profiling eta to spot some lag, found out that aqua creepers do generate some non neglictible amount of lag.
![image](https://user-images.githubusercontent.com/12850933/99272864-96e00a00-2828-11eb-893b-7d416e7bc1ac.png)

![image](https://user-images.githubusercontent.com/12850933/99273896-e541d880-2829-11eb-9644-9f2d02e231c9.png)

**Comment by Dream-Master** [comment]
and another mod we need to fork :)

**Comment by KiloJoel** [comment]
Genuine question, can we just remove aqua creepers? 
They make an entire biome uninhabitable.
They make it impossible to use boats on multiplayer. 
Taking full damage from their explosion is mostly unavoidable since they move much faster than you in water.
They can jump up onto land before exploding for some reason.
Practically every new player dies at least once to them after using the random tp, which I imagine is not very encouraging.

**Comment by Dream-Master** [comment]
before we disable this mod we can check the config option and see what we can do here first.

**Comment by boubou19** [comment]
The mod is ARR, and here is the whole config of the mod:

"aqua creeper settings" {
    I:"Spawn Chance Probability"=5
    I:"Spawn Group Maximum Size"=1
    I:"Spawn Group Minimum Size"=1
}

So I guess we can't really do something.

**Comment by GTNH-Colen** [comment]
> Genuine question, can we just remove aqua creepers?
> -They make an entire biome uninhabitable.
> -They make it impossible to use boats on multiplayer.
> -Taking full damage from their explosion is mostly unavoidable since they move much faster than you in water.
> -They can jump up onto land before exploding for some reason.
> -Practically every new player dies at least once to them after using the random tp, which I imagine is not very encouraging.

Completely agree, I see absolutely no reason to sacrifice TPS for a useless mod that only causes frustration among the user base.

**Comment by GTNH-Colen** [comment]
@Dream-Master Can we remove this from next release? It adds nothing of substance, is very laggy and is quite unpopular as you can see from KiloJoels comments reactions. The config is useless to resolve this issue as you can see above.

**Comment by Prometheus0000** [comment]
Removed
