### ISSUE TITLE
Improve the getItemsInNetwork() call of OpenComputers AE2 integration

### ISSUE THREAD

**Issue by S4mpsa** [GTNewHorizons/GT-New-Horizons-Modpack#6946]
Currently very large AE2 networks (>5000 unique items) fill up all the possible memory of even the highest tier RAM, due to it returing a massive table of every value.

It could be made to return an iterator instead, which would allow picking the data you need on a per-item basis instead of having to hold it all in memory at once.

@repo-alt

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/99320197-219e2480-287c-11eb-9788-8c00cdf39ba8.png)

**Comment by repo-alt** [comment]
Suggestions for a less ugly name are welcome.

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/OpenComputers/pull/21

**Comment by repo-alt** [comment]
called it 'allItems'

**Comment by draknyte1** [comment]
allItems is kinda a bad name, Cause l and I look the same.

**Comment by repo-alt** [comment]
Well, I got no suggestions.
