### ISSUE TITLE
How do you use the Manual Trafo?

### ISSUE THREAD

**Issue by dieselfuelonly** [GTNewHorizons/GT-New-Horizons-Modpack#6947]
On current stable release version of pack.  How do you using the manual trafo?  I got the structure to form using what seem to be any machine casings.  IV energy hatch on bottom, EV dynamo on top, windings in between.  Structure forms fine, machine turns on, tried using circuits 0 and 1 and no circuits, doesn't seem to do anything.  Any more documentation on this?  Seems like a useful multiblock for transforming one power input into multiple outputs without the need for singleblock transformer chaining, a nice step in between the substation maybe.

https://i.imgur.com/ElHHIaQ.jpg

**Comment by Prometheus0000** [comment]
This is not the place for that. Also, try using search.
