### ISSUE TITLE
Telum spelled tellum in essentia value config

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6951]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Fixed in https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6950

**Comment by Prometheus0000** [comment]
*sigh*
