### ISSUE TITLE
Replicators in PA

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#6952]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Really wanted to use replicators in PA(procassing array)
#
#### What happened instead? (Attach screenshots if needed)
It dont work
#
#### What do you suggest instead/what changes do you propose?
Add replicator support to Processing arrays, you can make it require data orbs equal to amounth of replicators inside.Its nott mass fabricators they have regular 4energy/2speed overclock, also putting mass fabricators in PA would also be good

**Comment by draknyte1** [comment]
These things don’t use recipe maps, the have hard coded recipes. Hence why they, along with the printer and a few other things *cannot* be simply supported.

**Comment by LewisSaber** [comment]
Can we add special recipe for replicator that would use orb + uu + dust = 2 dust + orb

**Comment by Prometheus0000** [comment]
? How would it use power then?

**Comment by Florexiz** [comment]
So, well, maybe we should reopen this? "cannot be simply supported" isnt a reason to ignore unnecessary lag sources as I think

**Comment by Florexiz** [comment]
We need somebody to add custom logic for such machines. PA code even have old TODO commented code with function for such things

**Comment by mitchej123** [comment]
The PA is already a giant hack, and nobody who's capable of doing the work wants to.  I'd say the reason still stands.

**Comment by Florexiz** [comment]
Im all in for mass fab and replicator multi (gt++ is useless), but I think add handler to PA is easier>

**Comment by mitchej123** [comment]
I don't think anyone who is capable of making the changes is willing.  Please discuss in `#github-discussion` on discord, but I'm not expecting anything to change from the last time this was brought up and shot down.
