### ISSUE TITLE
MV Macerator is uncraftable in MV tier

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/GT-New-Horizons-Modpack#6953]
#### Which modpack version are you using?
2.0.9.0

#### If in multiplayer; On which server does this happen? 
private server

#### What did you try to do, and what did you expect to happen?
MV macerators require an industrial diamond, ~~which are not craftable in MV tier, since they require an implosion compressor (among other things that are standard mid-to-late HV progression)~~
even though you can get a precious few in quests, the actual recipe needs to be possible.

ok so they're technically possible if you go out of your way to do it in MV. but seriously, noone makes an implosion compressor in MV, that's not the normal progression. calling that multiblock+dynamite requirement for a medium voltage machine is just why it's one of the worst machines that exist in the game from a balance standpoint

#### What do you suggest instead/what changes do you propose?
change the industrial diamond to something else. regular diamond. diamond grinding head. whichever is more balanced.

**Comment by Prometheus0000** [comment]
Again, IC is MV? Did you even check? You need a valid reason, so rewrite it or I'll close it.

**Comment by LewisSaber** [comment]
Implosion compressor can be made at MV

**Comment by KiloJoel** [comment]
While the implosion compressor can be made in MV, I would agree that the cost (compared to HV lootbag enchanting) is quite high

**Comment by KorGgenT** [comment]
it's not in the normal progression at MV, and it even takes HV circuits. 
literally everyone makes the implosion compressor when they're in HV proper, so calling it actually MV is disingenuous

**Comment by greesyB** [comment]
I think it is reasonable to change the MV macerator recipe since gating it with implosion compressor and thus HV circuits means it is barely any harder to make the HV one.

**Comment by KiloJoel** [comment]
> 
> 
> While the implosion compressor can be made in MV, I would agree that the cost (compared to HV lootbag enchanting) is quite high

Oh whoops, I missed that this is about macerator, not lootbags.

**Comment by LewisSaber** [comment]
> literally everyone makes the implosion compressor when they're in HV proper, so calling it actually MV is disingenuous
I can say same for MegaDIstillation tower, you can make it HV but all make it at Luv+
But still it can be made,and implosion compresson dont cost that much, as for me industrial diamond have to stay

**Comment by KorGgenT** [comment]
> as for me industrial diamond have to stay

why? the MV macerator is yet another one of those things that everyone tells everyone else to never make, and the industrial diamond requirement even forces the issue further. if you can make HV circuits, you're just going to make an HV macerator anyway. might as well remove the MV macerator recipe then.

**Comment by LewisSaber** [comment]
why is MV macerator better then LV one? even with changing diamond , it would be still better to make 2 Lv macerators at MV , as its cheaper by resources and power and saves you more power in future, some machines are ingame just to be,like rotors for every material or screw even if its not used

**Comment by KorGgenT** [comment]
you're proving my point

**Comment by wllp** [comment]
I liked the idea of it taking a exquisite diamond or a cutting head of some sort.

**Comment by wllp** [comment]
Is and industrial diamond really that much more effective as a cutting head tool? I favor realism over making things hard "just 'cause".

**Comment by wllp** [comment]
> ... some machines are ingame just to be,like rotors for every material or screw even if its not used

Saying something should remain useless because there are other useless things already is a logical fallacie. Besides the issue here is not wether or not the MV Mac is useful. But wether or not the recipe to make the machine is too restrictive. Also side point wouldn't it be better server resource wise for there to be a single MV mac rather then your alternative of many lv ones?

**Comment by boubou19** [comment]
macerators aren't really impacting the tps. speaking of useless gt single blocks: there are two gt furnaces: the electric oven et the electric furnace.

**Comment by Prometheus0000** [comment]
Do you mean the microwave?

**Comment by boubou19** [comment]
i forgot about this one: so we have 3 gt single block furnaces

**Comment by KiloJoel** [comment]
I remember reading microwave blows up if you put anything metal in it. Not sure if that is true or not, but sounds like a pretty undesirable machine to ever make.

**Comment by KiloJoel** [comment]
It does indeed blow up
![image](https://user-images.githubusercontent.com/17787093/99461980-b3646b00-292a-11eb-8652-b6bad556e9ea.png)

**Comment by leagris** [comment]
About useless machines:
- Food Slicer, unless your wet dream is to recreate a fast-food chain with automated onions, tomatoes and cucumber slicing.
- Fluid canner (no comment!)
- Packager (Having multiple dust stacks sizes not stacking is already very retarded, and needing a machine to combine stacks is the pinnacle of degenerate stupidity)
- Boxinator (who turns scrap to boxes? Look mom! I just won a free wooden pickaxe from lootbox by burning 262144 EU and 640 pieces of scrap.)

**Comment by KiloJoel** [comment]
Fluid canner is needed for a few things. NaK coolant cell for HV energy hatches comes to mind

**Comment by Prometheus0000** [comment]
- We slice circuits. 
- And some stuff doesn't work for normal cell filling. Like redstone, steam, and cracked stuff. If only it worked right.
- Wasn't someone removing them in favor of lower chances? Is that still ongoing?
- Agree.

**Comment by leagris** [comment]
> * We slice circuits.
Hopefully not in the food slicer which only slices vegetables and has exactly two configure item a Slicer cut and a potatoes stick cut for french fries.

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/99465678-e85fc600-2908-11eb-823e-08e54eef5797.png)
![image](https://user-images.githubusercontent.com/8517039/99465691-edbd1080-2908-11eb-80f5-34c4cdf3c67a.png)
![image](https://user-images.githubusercontent.com/8517039/99465802-1ba25500-2909-11eb-95d2-89525228eb6c.png)
![image](https://user-images.githubusercontent.com/8517039/99465742-01687700-2909-11eb-853b-afbae9d7f7f1.png)
There's more to it than that. Slightly.

**Comment by mitchej123** [comment]
TIL there is a slicing machine.

**Comment by Prometheus0000** [comment]
How did you guys _think_ bart's sliced circuits were being made?

**Comment by draknyte1** [comment]
Packager is important. 
Tiny/Small dust changes are dumb and won’t propagate to addons, making shit ungodly inconsistent. 

Funnily enough, boxinator is the internal name of the packager. 🙃

**Comment by Houstonruss** [comment]
Maybe we can make the compressed coal chunk craftable in an MV compressor, instead of solely implosion compressor.
