### ISSUE TITLE
[Suggestion] Add paintable Immersive Engineering-like crate

### ISSUE THREAD

**Issue by DerMilchkarton** [GTNewHorizons/GT-New-Horizons-Modpack#6955]
The Immersive Engineering Mod adds a Wooden Storage Crate that fits nicely into machinery. It is essentially a simple chest that is always openable (like the slightly larger chest from extra utilites), but keeps its inventory when broken.

It would be a nice addition the bring a similar crate to GTNH. Would be even better if it is paintable like the other GT Machines.

More Info: https://ftb.gamepedia.com/Wooden_Storage_Crate

Really appreciate your work on this modpack, thanks!

![grafik](https://user-images.githubusercontent.com/36045340/99571175-3c36e180-29d3-11eb-8f9b-6d28fc3f3bec.png)

**Comment by Prometheus0000** [comment]
We have compressed chests already.

**Comment by DerMilchkarton** [comment]
Yes, but it doesn't look crate-like, it isn't paintable and it is pretty overkill for a lot of instances where you just need a bit of storage.

**Comment by Prometheus0000** [comment]
I'm not sure why you want the other stuff, but it does keep it's contents. BTW, did you check the license of IE, and/or try to port the item yourself if possible?
