### ISSUE TITLE
[Servers] I was told to put here if I wanted my server to get added to the list

### ISSUE THREAD

**Issue by genericusername1547** [GTNewHorizons/GT-New-Horizons-Modpack#6956]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
My server
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happened instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
I was told that to get my server added, I should make an issue request:
 
Title: Generic's GTNH Server (USE) 
IP: 173.68.69.230:25566

**Comment by Dream-Master** [comment]
@genericusername1547 has the server a whitelist or just open ?
Where is the server located to let other know how good or bad is the ping time.

**Comment by genericusername1547** [comment]
No whitelist, open, in US East

**Comment by Dream-Master** [comment]
ok
