### ISSUE TITLE
Wooden bolts quest 1156

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#6959]
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Craft a wooden bolt 
I used bronze to do that as it's not mentioned and to see if the quest will be checked
#
#### What happened instead? (Attach screenshots if needed)
The quest apparently requires a wooden bolt with iron only
#
#### What do you suggest instead/what changes do you propose?
As it's not mentionned clearly, I heard MaitreCarl beiing tricked by that so maybe you can just mentioned in the quest to craft a wooden bolt with iron like that :
wooden bolt (iron)

**Comment by Prometheus0000** [comment]
It says iron already
![image](https://user-images.githubusercontent.com/8517039/99853846-bdb47e00-2b51-11eb-9ef9-3cabe67f965d.png)

**Comment by Nicouuuuu** [comment]
Indeed I'm sorry I didn't saw that
