### ISSUE TITLE
Holo inventory toggle keybind is activated while chat is open

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6960]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/17787093/99730212-f9006f80-2ab3-11eb-8f33-c96129921d50.png)
My keybinding is as above

I typed c in chat
![image](https://user-images.githubusercontent.com/17787093/99730316-25b48700-2ab4-11eb-84c9-b626c0ad5885.png)
#
#### What happened instead? (Attach screenshots if needed)
My holo inventory view was toggled off
#
#### What do you suggest instead/what changes do you propose?
Not allow the key to be activated while chat is open

**Comment by Dream-Master** [comment]
Use another key. I use Numpad 1. Works well

**Comment by KiloJoel** [comment]
https://github.com/GTNewHorizons/HoloInventory/pull/10
