### ISSUE TITLE
Clay ball recipe dupe

### ISSUE THREAD

**Issue by D-Cysteine** [GTNewHorizons/GT-New-Horizons-Modpack#6961]
I found this in GT:NH 2.0.9.0 (2020-07-29).

The following recipe chain allows duplication of clay balls:

Input | Machine | Output
--- | --- | ---
Clay | Extruder (MV) | 2x Tiny clay pipe
2x Tiny clay pipe | Pulverizer (LV) | 4x Small clay dust
4x Small clay dust + Water | Mixer (LV) | 2x Clay

This also works for the other sizes of clay pipe, but requires an additional crafting step to convert the full-size clay dust from pulverization into small clay dust for the mixer.

I'd guess that this is an unintended consequence of clay balls being equal to 2x small dust rather than 1x dust like other ingots. The easiest way to fix this might be to change the extruder recipe to take clay dust rather than clay balls?

**Comment by xcube16** [comment]
A clay block can also be turned into 9 clay plates in a cutting machine.
Clay Block -*cutting_machine*-> 9 Clay Plates -*macerate*-> 9 Clay Dust -*crafting*-> 36 Small Clay Dust -*mixer*-> 18 Clay -*compressor*-> 4.5 Clay Blocks!
