### ISSUE TITLE
Multifarm configuration mismatch

### ISSUE THREAD

**Issue by DrParadox7** [GTNewHorizons/GT-New-Horizons-Modpack#6963]
#### Which modpack version are you using?
2.0.9.0-1.7.10
#
#### If in multiplayer; On which server does this happen? 
/
#
#### What did you try to do, and what did you expect to happen?
Tried to learn the difference between a Manual Multifarm and a Managed Multifarm by comparing 2 Multifarms, a Manual Crop Farm and a Managed Crop Farm.

Expected:
Managed Crop Farm to set the soil, plant any plants that matched the configurations etc. (Works as intended)
Manual Crop Farm to not set the soil, to not plant the initial crop and to only replace crops with the same type of crop it just harvested. (This didn't quite work).

#
#### What happened instead? (Attach screenshots if needed)
Manual Crop Farm sets the soil, plants the initial crop and when a crop matures it replants any available crop instead of the same type of crop previously harvested.
This is not the expected behavior.

Video showing the same things as above but with vegetable farms instead:
https://www.dropbox.com/s/g8c11rpjt3726uv/Crops.mp4?dl=0
#
#### What do you suggest instead/what changes do you propose?
I have tested all Managed Multifarms and they all work as intended. Manual farms, according to the available documentation, are not supposed to do the above.
It does not seem to be a problem with all Manual Farms as I tested the Manual Vegetable Farm and it works exactly as intended.
EDIT: Never mind, Manual Vegetable Farms exhibits the same behavior (it was just lacking hydrated farmland).

**Comment by DrParadox7** [comment]
I Tested all other Manual farms:
**Orchard Farm:** Works great for everything.
**Peat Bog:** Replaces existing blocks in it. (Expected behaviour?)
**Rubber Farm:** works as intented
**Reed Farm:** Diamantine Electron Tubes cannot be used to configure farms:
![image](https://user-images.githubusercontent.com/47131096/99752365-1e08d880-2adc-11eb-952f-a3006a5c18a3.png)
**Gourd Farm:** Works as intented
**Succulent farm:** works as intented.

**Comment by bookerthegeek** [comment]
So the with the automatic and manual crop farms, the Manual/Automatic part is solely about dirt/water/farmland placement.
- The Manual farm requires you to place dirt/water
- The Automatic farm places dirt/water for you.
The harvesting of pants, and replanting of whatever seed is next in the gui inventory of the farm, is exactly the same between the two and is expected behavior.

The orchard farm is the one you want as long as whatever you are harvesting is harvestable with a right click. The orchard will not plant anything it only right click harvests.

This behavior was documented in the Forestry changelogs back when Agricraft first came out and the orchard option was added.

**Comment by DrParadox7** [comment]
@bookerthegeek Manual farm will replace any block placed within the Multifarm's range with dirt. Is this intented?

**Comment by bookerthegeek** [comment]
@DrParadox7 Which manual farm are you referring to?

**Comment by DrParadox7** [comment]
@bookerthegeek  Manual Veg, Peat & Crop Farm. (See video above).
It will replace **any block**, till the dirt and plant the seeds on watered soil. That is not very manual imo.

**Comment by DrParadox7** [comment]
Even tested it with bedrock, nothing stops the Manual machine.

**Comment by DrParadox7** [comment]
[From the wiki:](https://forestryforminecraft.info/farms:configuration)
Manual Farms, unlike Managed Farms, will not set the soil for the crops to grow or place the initial seeds or saplings, but it will replant and harvest the crops/trees in its operation radius.

**Comment by Prometheus0000** [comment]
So aside from removing bedrock, is it working as intended? Can this be closed then?

**Comment by DrParadox7** [comment]
I will later test the most up to date version of Forestry and attempt to replicate the same behaviour.
If the same occurs I will personally close this issue and chuck it up to it being intentional.

**Comment by DrParadox7** [comment]
Most up-to-date version of Forestry exhibits the same behavior (minus the bedrock collection). Either intentional or a long forgotten oversight by the devs.
