### ISSUE TITLE
[Quest] MK3 Fusion (#1198): coil blocks not detected

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#6967]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I completed the bulk of the T3 fusion blocks and expected to unlock the quests below it
#
#### What happened instead? (Attach screenshots if needed)
The fusion coil blocks were not detected
![image](https://user-images.githubusercontent.com/8459776/99835329-bea2db00-2b64-11eb-82ca-96e9a63a0b49.png)
The appropriate stack is visible in the hotbar.

#
#### What do you suggest instead/what changes do you propose?
Update the quest (probably by disabling the metadata)

**Comment by botn365** [comment]
defnetly a nbt missmatch

**Comment by LewisSaber** [comment]
Why not just remove coils, you made it for t2 fusion,just add note for it in quest with red font,it will make people no need to dissasemble old reactor coils
