### ISSUE TITLE
[Quest][Suggestion] QPIC quest 2633: split quest or remove unnecessary UHV item

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#6968]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I had completed most infrastructure, and was working the remaining dependencies of MK3 fusion
#
#### What happened instead? (Attach screenshots if needed)
Part 2 of the QPIC quest wants you to cut the wafers. This either needs a detour into UHV, or a GT++ machine. Currently there are no visible uses of the cut wafers until UIV (+3 tiers from UV), but the uncut wafers are part of the MK3 fusion recipe in UV which is the player's likely goal at that point.
#
#### What do you suggest instead/what changes do you propose?
Splitting out part 2 of the quest (into a non-mainline one) would save the annotations for future look-up and is IMO the better solution. Simply dropping the latter part of the quest is also an option.

**Comment by Prometheus0000** [comment]
Duplicate, already done, check latest #6697.

**Comment by combusterf** [comment]
I apparently borked the duplicate search. My apologies.
