### ISSUE TITLE
Find item in inventory hotkey can't be typed into AE2 search box if mouse is hovering an item

### ISSUE THREAD

**Issue by dvdmandt** [GTNewHorizons/GT-New-Horizons-Modpack#6970]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
My own
#
#### What did you try to do, and what did you expect to happen?
Try to type T (default hotkey for Find Item in Nearby Inventories from Extra Utilities) when search box in AE2 terminal is active. I expected a T to appear in the textbox.
#
#### What happened instead? (Attach screenshots if needed)
Nothing. If the hovered item was present in a nearby inventory, I'd expect the inventory to be marked with particles.
#
#### What do you suggest instead/what changes do you propose?
Rework keybind resolution order or something so that textboxes have higher priority than the Find Item In Nearby Inventory feature.

**Comment by Eason134HK** [comment]
you can type "T'" in the AE terminal search box you just need to click the search box by your mouse and you can type whatever you want
