### ISSUE TITLE
Golden head mostly uncraftable

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6971]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Create a golden head using a player head.
#
#### What happened instead? (Attach screenshots if needed)
It doesn't work. The golden head (different to creative tool modifier) can only be crafted using a player head that is blank. The only way to obtain one of these is from a tricky bee which can only be obtained around halloween.
![image](https://user-images.githubusercontent.com/17787093/99814670-33fcb480-2b41-11eb-9384-e4ff259d6268.png)

![image](https://user-images.githubusercontent.com/17787093/99814540-03b51600-2b41-11eb-95cd-22d3bbe9c126.png)

#
#### What do you suggest instead/what changes do you propose?
Make the recipe accept a player head with any player data.

**Comment by Prometheus0000** [comment]
I'm pretty sure gendustry overrides all requirements. Use that? It's a frigging creative modifier after all.

**Comment by KiloJoel** [comment]
It's not a creative modifier, it's an edible item that gives regen I think. Different item

**Comment by Dream-Master** [comment]
can the name remover remove the nbt data ? @KiloJoel  can you test that first?

**Comment by Prometheus0000** [comment]
Still stays as my head when I try it

**Comment by GTNH-Colen** [comment]
I believe the name remover only removes NBT data from GT items to prevent people abusing it, could be wrong though.

**Comment by Dream-Master** [comment]
Add a recipe like <head:with.nbt> = <head:without.nbt>

**Comment by Prometheus0000** [comment]
Where? I couldn't find the recipe for the golden head in the smeltery? That's why I re-enabled the normal recipe.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/111837986-f8a8a180-88f8-11eb-98db-7f9aadec6c37.png)

**Comment by Prometheus0000** [comment]
Ok, where's the code?

**Comment by Prometheus0000** [comment]
val SteveHead = <minecraft:skull:3>;

// --- Gold Head
recipes.remove(<TConstruct:goldHead>);

// --- Gold Head (casting table recipe)
mods.tconstruct.Casting.removeTableRecipe(<TConstruct:goldHead>);

mods.tconstruct.Casting.addTableRecipe(<TConstruct:goldHead>, <liquid:gold.molten> * 1152, SteveHead, true, 200);

You can remove the casting table recipe and try another with this, but I can't find any tag that says to ignore NBT, only to specify it, and "head:with.nbt = head:without.nbt" does not parse.
