### ISSUE TITLE
Need ore dict on Fusion machine casing MKIII assline recipe

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#6975]
#### Which modpack version are you using?
GTNH 2.0.9.0QF4
#

#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/57050655/99885874-49083f00-2c38-11eb-82a1-57429a72ff22.png)

This recipe doesn't have the oredict enable for the circuits, you need excaclty the circuits in the pic and not any circuits. Could you change the recipe so it accepts all type of circuits ?

**Comment by Prometheus0000** [comment]
This _again_? Are there even any TT recipes that _are_ oredicted?

**Comment by LewisSaber** [comment]
this is GT++ tho

**Comment by Prometheus0000** [comment]
I still wonder whether QC+RS recipes can be oredicted.

**Comment by Prometheus0000** [comment]
Or is the problem with the assembly line?

**Comment by draknyte1** [comment]
OreDict is handled by GT, not GT++. 

Not my issue. 🤦🏻‍♀️

**Comment by Prometheus0000** [comment]
I don't suppose you happen to know how to fix it?

**Comment by draknyte1** [comment]
GT shit only supports OD through partially hacky code. Not my issue, care or problem. Dunno, don’t care.

**Comment by Prometheus0000** [comment]
That makes me sad. But is also expected. I mean, we have the OC microcontroller OD that doesn't work either.

**Comment by draknyte1** [comment]
Essentially, GT stuff doesn’t natively support OD and anything that does uses kinda hacky code. Fix that, which then fixes everything else. 🤷🏻‍♀️

**Comment by Prometheus0000** [comment]
I know.
