### ISSUE TITLE
Memory "leak" issue when chunks are loaded/unloaded in otherwise inactive dimensions

### ISSUE THREAD

**Issue by dvdmandt** [GTNewHorizons/GT-New-Horizons-Modpack#6976]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
My own
#
#### What did you try to do, and what did you expect to happen?
Leave server online for more than a day without memory adding up to a point where GC is constantly running causing performance to degrade completely.
#
#### What happened instead? (Attach screenshots if needed)
Memory "leaks"/builds up over time. This is similar to the more severe #6964, but a different issue that is slightly more rare. If chunks with TileEntities (including GT ores) are loaded and unloaded in dimensions without players or chunk loaders, the TileEntities will be added to a list (field_147483_b aka tileEntitiesToBeRemoved in net.minecraft.world.World) which is not cleared until a player visits that dimension. In my case, I had just over 13M objects using something like 3GB memory in that list after ~40 hours. Such chunk loading can be triggered by things like Thaumcraft mirrors and probably chests and tanks for EnderStorage, and similar, where one end is in a loaded dimension and the other in an unloaded one.

The code that causes the skip is

```
    public void updateEntities() {
        if (this.playerEntities.isEmpty() && this.getPersistentChunks().isEmpty()) {
            if (this.updateEntityTick++ >= 1200) {
                return;
            }
        } else {
            this.resetUpdateEntityTick();
        }

        super.updateEntities();
    }
```
in WorldServer, though I'm not sure where it comes from.

#
#### What do you suggest instead/what changes do you propose?
I'm thinking the cleanup should be forced to run once if a chunk has been unloaded or something.

**Comment by dvdmandt** [comment]
So as I wrote in Discord, I'm seeing this issue again on 2.1.2.1, but this time with a much more likely trigger. Just placing a HV miner with a passive anchor in the nether seems to trigger a buildup that continues long after the miner completes and the anchor is removed. The buildup consists of GT_TileEntity_Ores objects that are located 1-2 chunks away from the mined/loaded area. The buildup is reset when a player visits the dimension, so it's probably not an issue on the officials, but it's evidently pretty easy to trigger on a private server.

So there are two parts to this issue. One is to track down what triggers the ghost loading of these chunks, and I'm currently looking into that, but I also think we should consider force clearing the buildup if it reaches a certain level, like say a million objects or something, and output some console message about it.

**Comment by Rubix2048** [comment]
This actually might have been why Eta had some ridiculous tens of thousands of TEs in the nether despite having no loaded chunks maybe.

**Comment by boubou19** [comment]
Officials are suffering from this since ages, most recurring dims are nether and space dims. But with the tps meter i set up at spawns, players can at least visit themselves the dimension to mitigate the issue. I'd be happy to see this fixed.

**Comment by fluffle** [comment]
Not sure if you're interested in anecdata of this working, but I can confirm it's stopped the leaks I was observing on my local server. Thank you!
