### ISSUE TITLE
Infernal pigzombies/vampires applying debuffs through walls

### ISSUE THREAD

**Issue by omegablasterzeta** [GTNewHorizons/GT-New-Horizons-Modpack#6979]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Bombtrack's server.
#
#### What did you try to do, and what did you expect to happen?
Mine in the nether without being set on fire through walls every minute.
#
#### What happened instead? (Attach screenshots if needed)
I got set on fire through walls.
#
#### What do you suggest instead/what changes do you propose?
Make all pigzombies/vampires stop applying debuffs like fire, poison, wither, blindness, slowness, etc (basically every debuf an infernal mob can have) THROUGH the walls, as i imagine this behaviour is not intended (at least i surely hope it isn't) and likely the result of the aggro mechanic from breaking ores, since these mobs specifically apply their debuffs on the player once for each ore they break inside their aggro range.

The ideal solution would be some kind of check to see if the mob has line of sight, but in case this isn't possible/pratical/would cause lag, removing the aggro mechanic (shouldn't be that much of a problem since most infernal pigzombies i meet are aggressive by default anyway), or simply blacklisting the problematic infernal modifiers that go through walls from being applied to pigzombie/vampire variants.

**Comment by Dream-Master** [comment]
Not make GTNH to easy. i like they can watch you through walls so you cant steel them the ores

**Comment by Dream-Master** [comment]
@omegablasterzeta nah not give up to convinced me :)
