### ISSUE TITLE
Mudball recipe gives two buckets back

### ISSUE THREAD

**Issue by Rokkitz** [GTNewHorizons/GT-New-Horizons-Modpack#6980]
#### Which modpack version are you using?
2090
#
#### If in multiplayer; On which server does this happen? 
no
#
#### What did you try to do, and what did you expect to happen?
Tried to make two mudball with one dirt and one bucket of water. Expected to get two mudball and one empty bucket back.
#
#### What happened instead? (Attach screenshots if needed)
Recipe returns two mudball and two empty buckets.
#
#### What do you suggest instead/what changes do you propose?
Only one empty bucket should be returned instead of two

**Comment by Dream-Master** [comment]
fixed so far i remeber

**Comment by Prometheus0000** [comment]
Go check the latest version. Also, duplicate.
