### ISSUE TITLE
Thaumic sauna stove large freeze (Witching gadgets)

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6983]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Place water inside a thaumic sauna stove
or
Move into render range of a sauna stove that already has water in
#
#### What happened instead? (Attach screenshots if needed)
A large freeze occurs.
![image](https://user-images.githubusercontent.com/17787093/100029419-236e6780-2de9-11eb-9dc4-1ec384b03c8e.png)

Previous issues https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3361 https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4120
#

**Comment by dvdmandt** [comment]
Took a very quick look at the source code and my guess is that it's the area checking code that is inefficient (the screenshot doesn't reveal it). It seems to do some form of flood fill style checking of the sauna steam volume, and my guess is that if it isn't contained in a rather small area, that code is not super efficient. I didn't look too closely at it though.

**Comment by KiloJoel** [comment]
It's a clientside freeze that i'm getting, not sure about any server impact.

It's in the range of a personal anchor, so it's not being loaded when I move into render range, but still causes a freeze.

**Comment by KiloJoel** [comment]
Freeze only occurs when the stove is in a large open space.

**Comment by dvdmandt** [comment]
Again, I only took a quick look, but it seems to me like it tries to fill up to a 32x32x32 volume. We could probably shrink that to like 8x8x8 or so, if not for performance then perhaps for balance?

**Comment by Prometheus0000** [comment]
Why would the size affect balance anyway?

**Comment by dvdmandt** [comment]
Isn't it reducing or even preventing warp effects in its area?

**Comment by Prometheus0000** [comment]
Are you just going to hang out in there? AFKing?

**Comment by dvdmandt** [comment]
Well, if it's 2x2 chunks, you can do quite a lot in its area?

**Comment by Prometheus0000** [comment]
I suppose. I'd just make it a 2x2x2 or 4x4x4, as real saunas are small, right?

**Comment by KiloJoel** [comment]
It's mainly useful for holding off effects while doing a lot of warpy activity, which could include doing infusions, that's the main case I can't think of where a large areas would be useful.

**Comment by dvdmandt** [comment]
As a swede who used to date a finn, the biggest sauna I've been in was like 5x3x2 meters I think. But I think something like 8x8x4 (WxDxH) would make more sense in MC.

**Comment by KiloJoel** [comment]
> 
> 
> I suppose. I'd just make it a 2x2x2 or 4x4x4, as real saunas are small, right?

For symmetry's sake, can we make it an odd number :P

**Comment by dvdmandt** [comment]
9x9x5? That would still be fairly large, but would probably be a significant performance improvement in worst case.

**Comment by KiloJoel** [comment]
That seems reasonable to me
