### ISSUE TITLE
Quest #1724 Tier 5 Heavy Duty Plates

### ISSUE THREAD

**Issue by bombtrack** [GTNewHorizons/GT-New-Horizons-Modpack#6984]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Bombtrack's GTNH Server
#
#### What did you try to do, and what did you expect to happen?
Complete quest 1724
#
#### What happened instead? (Attach screenshots if needed)
Quest asks for incorrect items
#
#### What do you suggest instead/what changes do you propose?
Update quest to ask for europium bolts instead of europium screws

![image](https://user-images.githubusercontent.com/47153072/100036919-1c3a6000-2dcf-11eb-9d3e-7bdbccf3dbd6.png)
![image](https://user-images.githubusercontent.com/47153072/100036997-468c1d80-2dcf-11eb-939a-05d511c41320.png)

**Comment by yukieiji** [comment]
The latest quests have been fixed.

**Comment by Prometheus0000** [comment]
Already fixed.
