### ISSUE TITLE
Add textures for each programmable circuit

### ISSUE THREAD

**Issue by aLegoz** [GTNewHorizons/GT-New-Horizons-Modpack#6993]
I wanted to add textures for Programmable circuit, but i don\`t know where search source code GT that\`s why i propose to add textures for each programmable circuit. It will be help to identify which circuit need for recipe. Of course if you can.
![](https://i.imgur.com/Lp30fiN.png)
![](https://i.imgur.com/jSVO0u6.png)

**Comment by draknyte1** [comment]
The item uses the same texture for every meta, so you’d have to adjust that code and have 20+ textures vs just one. Feel the way it is now is fine tbh.

**Comment by aLegoz** [comment]
> The item uses the same texture for every meta, so you’d have to adjust that code and have 20+ textures vs just one. Feel the way it is now is fine tbh.

Copy this 20 textures pls. I will draw myself.

**Comment by Dream-Master** [comment]
Why not its a nice addition to have different textures.

**Comment by leagris** [comment]
Integrated Circuit:

- As an LCD 7-segments 2-digits: ![image](https://user-images.githubusercontent.com/1111474/100275137-c8ab4c00-2f5f-11eb-979e-2527fa69800e.png)  
  Could be 2 decimals or 2 hex for up to 256 settings.

**Comment by Usernm0** [comment]
Nice idea with 7-segments LCD. I draw update for my texture pack when we get technical possibility.

**Comment by Dream-Master** [comment]
Are this need code changes and btw where is the exsting texture located ?

**Comment by leagris** [comment]
Original asset here: `src/main/resources/assets/gregtech/textures/items/gt.integrated_circuit.png`

![.](https://raw.githubusercontent.com/GTNewHorizons/GT5-Unofficial/85c804fa112fd1f19c91e45d150a787cfbf0f7a8/src/main/resources/assets/gregtech/textures/items/gt.integrated_circuit.png)

Could be replaced with
```none
src/main/resources/assets/gregtech/textures/items/gt.integrated_circuit/
├── 0.png
├── 1.png
├── 2.png
├── 3.png
├── 4.png
…
└── 24.png
```

**Comment by Dream-Master** [comment]
ah ok

**Comment by GTNH-Afx237v7** [comment]
DIP switch has it’s visual appeal, however practically not really useful unless you have an indication on the circuit setting in the tooltip. 
The digit indicator makes it easy to understand for everyone. Personally I‘d have this added to a texture pack as I think the current texture is fine.

**Comment by Usernm0** [comment]
Bigger is better IMHO.
![](https://i.imgur.com/UZqZRhY.png)
Feel free to use if you like.
Already split images here:
[google drive](https://drive.google.com/file/d/1dhOC7Ck1BOPT7tz4xHfMmer3sMmh83sU/view?usp=sharing)

**Comment by leagris** [comment]
Here are both versions as shown in a Gregtech Assembler GUI
![image](https://user-images.githubusercontent.com/1111474/100302743-46407d80-2f9b-11eb-8d69-ca25c897b366.png)

Note how odd size icons cannot be centered.

**Comment by aLegoz** [comment]
I made my variants for circuit. You can use this in your mod, if you need. I added psd file and made circuits for GT++ (Green and Red).
Link: [Google drive](https://drive.google.com/file/d/1u69MWKe9el8TtUdOHzngcBsGMlqa6DqO/view?usp=sharing)
![](https://i.imgur.com/dSdU64b.png)
![](https://i.imgur.com/hcYsDH9.png)
![](https://i.imgur.com/OfeuGTR.png)

**Comment by DualBallers** [comment]
@leagris @Dream-Master 
It seems like there are several different opinions on the graphics for the numbered circuits. 
Though it does not count for anything, personally I am not in favour of the option that has just been merged (too spiky).

This is a very central item to the pack, so I would suggest to put the options of which graphics to use to a vote on discord.

**Comment by Dream-Master** [comment]
They grey one is the neutral one and should be ok. Sure if somone want to change it better put thus in a resource texture pack

**Comment by leagris** [comment]
The one merged has same pins spikes as the old non-visual IC. I just rotated it horizontally to better fit digits.

Spiky pins or shorty pins is really a matter of integrated-circuit package type:

Component packages from https://learn.sparkfun.com/tutorials/integrated-circuits/all
![](https://cdn.sparkfun.com/assets/c/7/a/1/9/51e0633cce395f867b000000.jpg)

The last proposed has off liquid crystal segments brighter than background and this is not how reflective (old-style) Liquid Crystal Displays renders. Crystal polarization is same as screen polarization when off, but they are still slightly darker because scattered light from surroundings cannot pass through it unless of same polarization.

**Comment by leagris** [comment]
Sample design: ![](https://cdn-reichelt.de/bilder/web/xxl_ws/A500/LCD_2_0-13.png)
