### ISSUE TITLE
Bucket Duplication Glitch with Modballs

### ISSUE THREAD

**Issue by AndyDobrowolski** [GTNewHorizons/GT-New-Horizons-Modpack#6994]
#### Which modpack version are you using?
Latest Version: 2.0.9.0-1.7.10
#
#### If in multiplayer; On which server does this happen? 
Single player 
#
#### What did you try to do, and what did you expect to happen?
I used a piece of dirt and a bucket of water in my 2x2 crafting grid, and expected to get 2 mud balls. 
#
#### What happened instead? (Attach screenshots if needed)
I got the mud balls, but I also got 2 bucket in return per craft. 
#
#### What do you suggest instead/what changes do you propose?
Adjust the recipe to not duplicate buckets when crafted.

**Comment by Prometheus0000** [comment]
Use search, duplicate
