### ISSUE TITLE
Very bad TPS lag from code relating to arcane enervation emitter (gadomancy)

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6996]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/17787093/100301957-33c14680-2f91-11eb-9e29-5d3068196d78.png)
This method is used to create an area that disables mobGriefing for entities near any arcane enervation emitter.

The problem is it's incredibly slow and is called every tick by every zombie, and some others, adding up to an unreasonably large tick time.

It also doesn't work properly, I've tested all the things affected by mobGriefing and the only one it actually prevents is creeper explosions destroying blocks (The enervation emitter only prevents non-special creepers from exploding).
#
#### What do you suggest instead/what changes do you propose?
As far as I can tell, there's no way to change this to maintain functionality and remove the getStackTrace() call, so unless anyone else has any ideas, I propose the method be removed. This would mean it would no longer prevent creeper explosions from destroying blocks, but regular creepers would still not explode, and endermen would still not teleport.

**Comment by KiloJoel** [comment]
Whoops, I forgot to say, that code is in EventHandlerWorld.java in Gadomancy

**Comment by repo-alt** [comment]
Actually, I don't understand why it overrides "mob griefing" only for "EntityLivingBase.onUpdate" method

**Comment by KiloJoel** [comment]
> 
> 
> Actually, I don't understand why it overrides "mob griefing" only for "EntityLivingBase.onUpdate" method

Yeah, that is weird since as far as I could tell, that's the only place mobgriefing checks come from

**Comment by repo-alt** [comment]
So, maybe it makes sense to just remove the callstack walking?

**Comment by KiloJoel** [comment]
Possibly, though I wouldn't be able to say whether that would cause any side effects or not. There may be some mod getting the mobgriefing that we don't know about.

**Comment by repo-alt** [comment]
I would think this is actually good. So in the area of effect of the emitter, mobgriefing is false to everybody

**Comment by KiloJoel** [comment]
Another issue currently is it's using the stacktrace to verify whether lastupdated is the object that called to check mobgriefing.

If the tracktrace checking was removed, a situation could happen such as:
-Zombie is updated, lastupdated set to zombie
-Wither skull is updated
-Wither skull checks mobgriefing
-Lastupdated is still zombie, so it checks whether zombie is within enervation emitter range to determine whether the skull can break blocks

**Comment by boubou19** [comment]
might be easier to totally disable the enervation emitter as we can use the corporeal attractor to prevent mobs from escaping (including endermen) and use blocks with enough blast resistance to prevent explosion grieffing from vanilla creepers.

**Comment by KiloJoel** [comment]
> 
> 
> might be easier to totally disable the enervation emitter as we can use the corporeal attractor to prevent mobs from escaping (including endermen) and use blocks with enough blast resistance to prevent explosion grieffing from vanilla creepers.

I have no objection to this, but I also don't see the need to disable more than is necessary. I can imagine someone might want to use it to more easily farm music discs for example. Also, are you sure corporeal attractors prevent endermen from teleporting? I can't find any info suggesting that is the case.

**Comment by Uristqwerty** [comment]
Instead of walking a stack trace, what about something like setting a thread-local variable while in either of the two functions it's scanning for? I'm not familiar with the difficulty of patching vanilla(?) functions, but it might be a decently-straightforward way to preserve current functionality.

**Comment by draknyte1** [comment]
> I'm not familiar with the difficulty of patching vanilla(?) functions

Difficult. Using ASM or Mixins to fix something should always be a last resort and there’s < 5 people in the GTNH capable of actually doing so. 

Any other solution is preferential. Walking stacktraces is also horribly slow and inefficient.
