### ISSUE TITLE
formation planes can corrupt chunks

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6997]
#### Which modpack version are you using?
2090QF4
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
i was playing around with the formation planes on delta, and i somehow managed to corrupt a chunk.

[crash-2020-11-27_02.05.06-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5605454/crash-2020-11-27_02.05.06-server.txt)

**Comment by repo-alt** [comment]
What were you placing/forming?

**Comment by repo-alt** [comment]
Looks like it tried to place some AE part

**Comment by repo-alt** [comment]
Ok, looks like placing AE parts was broken quite a while ago.

**Comment by boubou19** [comment]
I wanted to measure the impact of the constant usage of formation planes on the tps (using them to place barnarda c log) made a 11x11 wall of formation planes, a storage bus on a compressed chest. I configured like 10 formation planes to place the barnarda c logs, but when i put a stack in the AE terminal, only like 6 of the logs were placed by the formation planes, and the stack was returned in my inventory instead of being stored in the compressed chest. So i wanted to use an import bus on a player interface to import the logs, and lookslike that it did not liked the fact i placed the import bus.

**Comment by repo-alt** [comment]
Well, the crash was in the formation plane, and it tried to export/place some AE part. I may test what happens if I use _a lot_ of planes
