### ISSUE TITLE
Important Tools (Saw)

### ISSUE THREAD

**Issue by mhar02** [GTNewHorizons/GT-New-Horizons-Modpack#6999]
#### Which modpack version are you using? Latest

#
#### If in multiplayer; On which server does this happen? N/A

#
#### What did you try to do, and what did you expect to happen? I crafted an iron saw in a crafting bench and expected for the crafting task to complete for quest "Important tools".

#
#### What happened instead? (Attach screenshots if needed) Did not complete the quest

#

**Comment by Prometheus0000** [comment]
Real version

**Comment by mhar02** [comment]
We figured it. I was offline at the time. This was explained to me why it was an issue in the GTNH discord.
