### ISSUE TITLE
TF Loot chests have mostly useless stuff inside

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#7000]
I want to add custom loot to TF chests so i need some code implementation to add other mods loot.

**Comment by Dream-Master** [comment]
@jss2a98aj hope you can help me with it

**Comment by jss2a98aj** [comment]
This https://github.com/GTNewHorizons/twilightforest/commit/7c3fa1c03b22aada2616c814c05d711283730c9d will make it possible to add itemstacks to TF loot tables without risking a NPE.

**Comment by Ethryan** [comment]
Nice, so now we might add items to find like Thaumium, Nitor, Alumentum, and maybe Thaumcraft Wax Candles in the chests.

Thaumcraft Wax Candles sounds like a good idea for the tower_library chest. (Just my 5 cents)

**Comment by Prometheus0000** [comment]
See #7890
