### ISSUE TITLE
Rouge Like Dungeon Loot chests need to have other mods loot too

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#7001]
I want to add custom loot to Rouge Like Dungeon chests so i need some code implementation to add other mods loot.

**Comment by Glease** [comment]
This mod has a configuration system for custom dungeons. Documents here:

https://github.com/Greymerk/minecraft-roguelike/wiki/Loot-Customisation/bc372e9188540193093bd0d0d61ec470ce44a3f3
https://github.com/Greymerk/minecraft-roguelike/wiki/Dungeon-Settings/bc372e9188540193093bd0d0d61ec470ce44a3f3

The author also included a demo in Loot-Customisation page. I'll put the link here as well in case you missed it https://github.com/Greymerk/minecraft-roguelike/files/60656/loot-settings-demo.zip

**Comment by dimondmine2** [comment]
Is loot not determined in a config file for this mod. I found someone describing a quick way to get this done. https://www.reddit.com/r/feedthebeast/comments/cu92s3/for_those_interested_in_adding_loot_to_roguelike/

**Comment by Glease** [comment]
@dimondmine2 unforunately that's for a newer version of the mod (1.8+), and this newer version is 1.12.2 exclusive.

**Comment by Ethryan** [comment]
Soo, anyone thinking of seeing if that can be backported easily?

**Comment by mitchej123** [comment]
If someone wants to track down the custom loot code (probably in this repo): https://github.com/srwaggon/minecraft-roguelike. I'll take a stab at backporting into our repo - https://github.com/GTNewHorizons/Roguelike-Dungeons

**Comment by Ethryan** [comment]
https://github.com/srwaggon/minecraft-roguelike/tree/master/src/main/java/greymerk/roguelike/dungeon/settings
Seems to be set in this whole damn directory have a look
