### ISSUE TITLE
Nanos suit

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7002]
#### Which modpack version are you using?
delta
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/59776356/100433210-b521f180-30d5-11eb-92bf-401ba7b69c29.png)
![image](https://user-images.githubusercontent.com/59776356/100433216-b7844b80-30d5-11eb-96f5-2f216d54bd5f.png)
i can't soulbound my nano suit
#
#### What happened instead? (Attach screenshots if needed)
i can't soulbound my nano suit
#
#### What do you suggest instead/what changes do you propose?
Allow players to enchant nano suit

**Comment by Dream-Master** [comment]
How? ic2 is closed source. Maybe it can add from outside

**Comment by Prometheus0000** [comment]
My understanding is that you can't enchant nano or quantum at all

**Comment by Prometheus0000** [comment]
Do we even want to allow enchanting it though?

**Comment by Eason134HK** [comment]
> Do we even want to allow enchanting it though?

sure why not if it is possible

**Comment by bombcar** [comment]
Can't enchant the magic nano boots either. :(
