### ISSUE TITLE
[Suggestion] - Modifier for Soulbound support to tinkers tools

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#7003]
We can get soulbound enchantment on almost anything important,

But if i remember correctly you can't enchant tinkers tools with it.

Why not code in an expensive tinkers modifier that enchants the tool with soulbound when added.

**Comment by bamik69** [comment]
There are several soulbound enchantments in the game. What are we talking about?

**Comment by Ethryan** [comment]
Adding code for an item or that uses a modifier slot on a tinkers tool, and then adds the soulbound enchantment to the tool.

**Comment by bedrill64** [comment]
They for sure can be enchanted with soulbound, I have my hammer soulbound enchanted and I've seen ppl with soulbound enchanted crossbow.

**Comment by repo-alt** [comment]
There is a (vanilla?) bug where anvil incorrectly shows required level for some items

**Comment by boubou19** [comment]
there is an anvil from thaumcraft that let's you enchant your stuff for less xp

**Comment by Ethryan** [comment]
K, i thought they couldn't be enchanted with it.
Shows what i know....
