### ISSUE TITLE
The NanoSuit is a lie

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7004]
#### Which modpack version are you using?
delta
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I am wearing a full set of nanosuits standing next to a reactor with a temperature of over 70%
and then I was taking damage
![image](https://user-images.githubusercontent.com/59776356/100459176-f8915580-30ff-11eb-935c-1bf7ea089e9d.png)
If the nano suit can provide a full hazmat protection, i will not be damaged by the heat of the reactor
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/100459248-1e1e5f00-3100-11eb-906c-5727875d3bca.png)

#
#### What do you suggest instead/what changes do you propose?
NanoSuit is a lie
delete NanoSuit (jk)
i want to say fix it
but i know you have no way to fix it cuz ic2 is closed source
 ╮(╯_╰)╭

**Comment by draknyte1** [comment]
There may be parts of IC2 with hazmat integration I missed. Issue should be reported here: https://github.com/alkcorp/GTplusplus/issues
