### ISSUE TITLE
Changing the circuit number in the mixer

### ISSUE THREAD

**Issue by bamik69** [GTNewHorizons/GT-New-Horizons-Modpack#7008]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Your own version of the server without significant changes to the original.
#
#### What did you try to do, and what did you expect to happen?
I suggest changing the number of the scheme in crafting changeable dust in the mixer from 4 to 2. This will simplify the creation of Autocraft. There are no intersections with other recipes.
![2020-11-28_00 28 50](https://user-images.githubusercontent.com/22926983/100485691-1962a680-3112-11eb-8710-d2caabc63151.png)

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Similar to it
![2020-11-28_00 29 01](https://user-images.githubusercontent.com/22926983/100485728-4020dd00-3112-11eb-91e1-29e0409c4f17.png)

**Comment by LewisSaber** [comment]
any problems putting 2 circuits together? More splitting to diffrent programmed circuits _. less conflicts,there is always conflicts if u really , like here if you put recipe for 4 fluix + recipe of rose gold(1 copper + 4 gold) of that all would be circuit 2 it will make red alloy from it

**Comment by Prometheus0000** [comment]
There's still no explanation of what's wrong with the way it is?

And why do you want to make it even more complicated?

**Comment by Dream-Master** [comment]
if there is no recipe interaction with existing once we can change it. The circuit nr represent the output of items so far i rember.

**Comment by bamik69** [comment]
I looked through the materials of the intersection of recipes. There are none. It is completely painless to change the number of scheme 4 to the number of scheme 2.there will be no Conflicts. This will only remove the need to install an additional mixer to perform just this recipe.

**Comment by Prometheus0000** [comment]
Again, _why_ would we want to change it?

**Comment by bamik69** [comment]
For a good cause. I just suggested it. You know better what is best. If you think there should be more mechs on the bases, then so be it.

**Comment by Prometheus0000** [comment]
What good cause? You mentioned 'This will simplify the creation of Autocraft', but there is no 'Autocraft' item? Nor explain what specific recipe you're talking about? Or do you mean more than one? Is it the one in the picture only? Why make us search for it?

If you're talking about simplifying _autocrafting_, then it still doesn't make any sense because you didn't say why this would be the case. What's wrong with the way it is now that requires a change in order to simplify it? And what's a 'changeable dust'? As far as I know there's no such item? I suggest getting someone to help you with the translation on the discord. For example 'more mechs on the bases' makes literally no sense.

**Comment by KiloJoel** [comment]
From what I understand of mixer recipes, they always require a config 2 circuit unless there is a conflict, so it would make sense for this to use 2 given there is no conflict.

**Comment by Prometheus0000** [comment]
Which specific recipe(s) then? Also keep in mind _whatever_ #6534 is about?

**Comment by bamik69** [comment]
Ok. I realized that the problem is a misunderstanding due to the translation from Russian. I will restore the English language in the client to be closer to you.
By Autocraft, I mean the AE2 system. You can't change the schemas using it. Therefore, we have to put a separate mechanism under each scheme.
I conducted a more detailed analysis of the use of scheme #4 in the mixer. An interesting picture is obtained. There are 5 recipes. And in only two it is possible to explain the presence of this scheme.
In order.
Recipes 1 and 2.
![2020-11-28_09 14 38](https://user-images.githubusercontent.com/22926983/100495390-64a1a700-315c-11eb-8d12-042fb15eb346.png)
![2020-11-28_09 15 02](https://user-images.githubusercontent.com/22926983/100495391-6cf9e200-315c-11eb-8f9c-f6964b345c3f.png)

Agrees with the statement that the circuit number corresponds to the output quantity.
Recipes 3 and 4 differ in the water used.
![2020-11-28_09 12 18](https://user-images.githubusercontent.com/22926983/100495396-7aaf6780-315c-11eb-84ef-3593d5d07b7c.png)

Recipe 5.
![2020-11-28_09 15 13](https://user-images.githubusercontent.com/22926983/100495401-88fd8380-315c-11eb-9d1e-16408972ca5c.png)

Rather, it should be in a chemical reactor.
It may be worth it to completely eliminate the scheme number 4 of the recipes of the mixer? If there are no contradictions.

**Comment by bamik69** [comment]
I suggest changing recipes 3 and 4. the Rest do not affect the convenience of your presence. 1 recipe of the costs of the Assembly in a molecular assembler. 2 the recipe is hardly used. And if it will be used, then only in mini factories. 5 the recipe is similar. You don't need to automate them using AE2.

**Comment by repo-alt** [comment]
I support that. The less selectors used, the better.

**Comment by repo-alt** [comment]
Why it was set to 4 in the first place I wonder.

**Comment by bamik69** [comment]
Thanks!
