### ISSUE TITLE
NEI bookmarking prospector generated books results in crash upon opening inventory

### ISSUE THREAD

**Issue by LordTet** [GTNewHorizons/GT-New-Horizons-Modpack#7010]
#### Which modpack version are you using?
2.0.9.0
#
#### Description
Bookmarking a written book generated by the prospector can result in corruption of the file which saves said data in config/NEI/bookmarks.ini.
#
#### Reproduction
Use the prospector as intended, generating a written book via the printer, scanner, and assembler. Bookmark the new written book with 'A' in NEI, then restart.
You should now crash in any world upon opening your inventory, so long as the game was started with your generated bookmarks file in config.
#
#### Cause
Not exactly sure why this happens, but some culprits I suspect are:
- Contents of the book, some pages overflow and have instances of patterns that also appear in the savedata format (such as "#:")
- Metadata of the book, also unrealistically long for a vanilla written book, similar issues to the contents.
#
#### Resources
- [Crashlog](https://pastebin.com/JCEvN2JZ)
- [Example corrupted bookmarks.ini](https://pastebin.com/xFeSGyyc)

**Comment by LordTet** [comment]
If anything else is needed, feel free to ask me here or on the discord, I'm glad to help out.

**Comment by repo-alt** [comment]
wow, it dumps nbt in the bookmarks

**Comment by mitchej123** [comment]
> wow, it dumps nbt in the bookmarks

Aren't some items are defined by NBT?  Would I break anything if I stripped the NBT?

The underlying issue though: It's not properly quoting the resulting JSON.

**Comment by mitchej123** [comment]
The proper fix would be to escape all NBT tags... but that'd be a lot of work, and require ASM/mixins.  I think I might just block written books from being bookmarked, since most other places don't allow freeform text (and by association, the possibility of unescaped `"`\s).

**Comment by mitchej123** [comment]
I've got a fix that I'm finishing up.  It won't read the old corrupted bookmarks.ini; but it will properly quote and load any bookmarks made once NEI 2.0.10 is released:

![NEI Book Compat](https://user-images.githubusercontent.com/1894689/107861589-a527cd00-6dfb-11eb-9a27-f2acde49d2a8.gif)
