### ISSUE TITLE
BQ3 crafting Task issue

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#7011]
Crafting task count wrong. If i am doing (for example) 10 items in the vanilla or TiCon Table (as batch craft) it count more than 10 items. Maybe some sync error. So it happend that task are shown as done but the number of items not in the inventory.

**Comment by Dream-Master** [comment]
@SKProCH maybe you can have a look? Thanks

**Comment by SKProCH** [comment]
The problem is confirmed and reproduced. A little later I will look at the reasons
