### ISSUE TITLE
UEV, UIV & UMV chest buffer not working

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7014]
#### Which modpack version are you using?
2.0.9.3.a.dev
#

I have UEV chest buffers in my base that used to work before the update and now they don't.

I tried all tiers of chest buffers and it seems that UEV, UIV & UMV chest buffers do not work.

**Comment by Prometheus0000** [comment]
Seems to be a result of https://github.com/GTNewHorizons/GT5-Unofficial/commit/3a07aac9a56e9f340954e9092aecf85ba648c405#diff-17da04a7057aeaf98a0f5ccb80fcd3db7102dc448034539320dec869dd7bb86cR22 which doesn't account for the 3 defined in the coremod.

**Comment by Dream-Master** [comment]
@Prometheus0000 are you able to fix this ?

**Comment by Prometheus0000** [comment]
That's what the PR was for?

**Comment by Dream-Master** [comment]
ah ok
