### ISSUE TITLE
Super chest holding more than max amount

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7018]
#### Which modpack version are you using?
GTNH 2.0.9.3..a.dev
#

I turned on the void if full on a super chest V capable of holding 64m items at max. And the chest if currently at 67m...

![image](https://user-images.githubusercontent.com/57050655/100544814-b0d21180-3258-11eb-8615-e66e57508c8a.png)
![image](https://user-images.githubusercontent.com/57050655/100544821-b62f5c00-3258-11eb-828c-495929ce9958.png)

**Comment by Prometheus0000** [comment]
@botn365

**Comment by botn365** [comment]
how are you inserting the items in the chest ae or a pipe?

**Comment by Alexdoru** [comment]
I have the chest right next to the output bus of my pyro oven

**Comment by Alexdoru** [comment]
![image](https://user-images.githubusercontent.com/57050655/101284165-ed64b680-37de-11eb-95f1-c6a745904bcc.png)


looks fixed in newest version GTNH 2.0.9.4.a.dev
