### ISSUE TITLE
Some repos not tracked by the discord bot

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7019]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Made a pull request in MyTown2, expected it to show up on the github-issues channel.
#
#### What happened instead? (Attach screenshots if needed)
Nothing was shown.
MyTown2, MyEssentials-Core, and presumably also MyPermissions are not tracked. Maybe others that I don't know about.
#
#### What do you suggest instead/what changes do you propose?
Set the discord bot to track them

**Comment by Dream-Master** [comment]
i dont link it but i could

**Comment by Dream-Master** [comment]
added
