### ISSUE TITLE
AE2 Caching and Optimization 

### ISSUE THREAD

**Issue by Houstonruss** [GTNewHorizons/GT-New-Horizons-Modpack#7020]
I was wondering if it possible to cache AE information for a next pack load? It takes a long time to open terminals lategame (30+ seconds, and you're frozen the whole time) This only the first time you open it per pack launch, and server restarts and client reconnects aren't bad, because updating that is lighter load i suppose.

**Comment by repo-alt** [comment]
Ok, I investigated the question, and looks like it is not quite trivial. The cache in question is in https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/blob/53d3eafdbf9e3b29e1aefb86fae368781bba883f/src/main/java/appeng/client/me/ItemRepo.java#L47 if somebody will have the time/energy to pick up that task. Feel free to reopen the bug if that would be the case.
