### ISSUE TITLE
witchery oven make some lag

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7021]
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
epsilon
#
#### 
I saw on opis that a witchery oven could make some lag, so here is a report of what i found:
![image](https://user-images.githubusercontent.com/12850933/100622753-81d3a280-3321-11eb-8936-506c7d5ee72f.png)

![image](https://user-images.githubusercontent.com/12850933/100622792-931caf00-3321-11eb-9e45-5aa4487d64f0.png)

![2020-11-30_15 35 02](https://user-images.githubusercontent.com/12850933/100622905-b6dff500-3321-11eb-99b6-9fbcf5925a99.png)

**Comment by draknyte1** [comment]
Repost issue on my WitcheryExtras repo please.
