### ISSUE TITLE
[Suggestion] Add non-vanilla mob drops to Hunter's backpack

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#7022]
#### Which modpack version are you using?

2.0.9.0

#
#### If in multiplayer; On which server does this happen? 

Delta

#
#### What did you try to do, and what did you expect to happen?

I made a hunter's backpack to avoid inventory clutter while navigating planets and dealing with hostiles

#
#### What happened instead? (Attach screenshots if needed)

Pretty much all non-vanilla drops were not picked up by the pack.

#
#### What do you suggest instead/what changes do you propose?

Add the following items to the config:
- Mob heads (itemSkull: skeleton, creeper, zombie, wither, enderman; but also wolf heads and hellhound heads which are not currently oredicted)
- Withering dust
- Confusing powder
- Flamestring
- Tongue of dog
- Blizz rod
- Ectoplasm
- Wolf Hide
- Ender fragment
- Wool of Bat
- Zombie brain

Meats have already been added via another ticket (#5865), and some of these appear to have regressed (#930)

**Comment by Prometheus0000** [comment]
Try adding them yourself and making a PR, it's not hard.

**Comment by Dream-Master** [comment]
@combusterf its a config options so feel free to make a pr.

**Comment by Dream-Master** [comment]
syntax

    miner {
        # Add itemStacks for the miner's backpack here in the format 'modid:name:meta'. For wildcard metadata the format is 'modid:name'.
        S:item.stacks <
            BiomesOPlenty:ashStone
            BiomesOPlenty:ashStone:0
            BiomesOPlenty:cragRock
            BiomesOPlenty:cragRock:0
            BiomesOPlenty:driedDirt
            BiomesOPlenty:driedDirt:0
            BiomesOPlenty:gemOre:0
            BiomesOPlenty:gemOre:10
            BiomesOPlenty:gemOre:12
            BiomesOPlenty:gemOre:14
            BiomesOPlenty:gemOre:2
            BiomesOPlenty:gemOre:4
            BiomesOPlenty:gemOre:6
            BiomesOPlenty:gemOre:8
            BiomesOPlenty:gems

**Comment by Dream-Master** [comment]
@combusterf use /mt hand ingame and copy paste items below the bag  you want to put items in. Thanks

**Comment by Prometheus0000** [comment]
Or use NEI's dump inventory command in the options menu and look in the dump file (there's like 3 different versions per item though)

**Comment by bombcar** [comment]
I've found some are still not picked up in my current playthrough, so I'll store some notes here before adding them in one commit hopefully.

BloodArsenal:wolf_hide
witchery:ingredient:25 (tongue of dog)

Strangely enough it takes nuggetGold ...

**Comment by Dream-Master** [comment]
sure this list need a rework. Feel free to make a new PR.

**Comment by ghostflyby** [comment]
> I've found some are still not picked up in my current playthrough, so I'll store some notes here before adding them in one commit hopefully.
> 
> BloodArsenal:wolf_hide witchery:ingredient:25 (tongue of dog)
> 
> Strangely enough it takes nuggetGold ...

A Zombie Pigman drops nuggetGold.

**Comment by bombcar** [comment]
> A Zombie Pigman drops nuggetGold.

Which raises a philosophical question - should it be _anything_ a mob can drop, or should it be only the things that (me? you? the ever-amorphous _they_?) think of as "mob drops"? Because with infernal mobs you get lots of things dropped that I  wouldn't think to first look in the "hunter" backpack, like pistons, nuggets, etc.

**Comment by bombcar** [comment]
EnderZoo:confusingDust
EnderZoo:witheringDust
RandomThings:ingredient:3 (this is Ectoplasm, which I'm conflicted on if it's a "mob drop")
minecraft:fire_charge
