### ISSUE TITLE
.name gt tileentity crashes game after starting world save from 2.0.9.0

### ISSUE THREAD

**Issue by donoya** [GTNewHorizons/GT-New-Horizons-Modpack#7023]
#### Which modpack version are you using?
2.0.9.3a with scripts jar
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
I tried loading my world save from the 2.0.9.0 version on the 2.0.9.3a version. I expected it would load and play without crashing.
#
#### What happened instead? (Attach screenshots if needed)
My game crashes a few seconds after loading. All my gregtech tileentities in the world that I can see upon loading the world say either '.name' or 'name.' in the waila tooltip and show in the world as the black and purple checkers broken texture.
#
#### What do you suggest instead/what changes do you propose?
Either make it so that worlds can be loaded with the newest test version or provide a workaround for players experiencing this issue.
[crash-2020-12-01_00.32.52-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5624888/crash-2020-12-01_00.32.52-server.txt)

**Comment by GTNH-Afx237v7** [comment]
I have experiend this once or twice, however I am not sure if this is related to the dev version or the script replacement to a .jar file. I could load my world just fine in 2.0.9.3 dev. Do you maybe have another log available (fml-client-latest)?
I assume you are playing SSP?
Some info I could find: https://forum.mechaenetia.com/t/java-lang-nullpointerexception-ticking-memory-connection-at-cpw-mods-fml-common-network-internal-fmlproxypacket/415/4 
Maybe try again or try splitting up server/client on the same computer (that is again assuming you are playing SSP).
