### ISSUE TITLE
Using a chisel with a full inventory crashes the game

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/GT-New-Horizons-Modpack#7024]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
private
#
#### What did you try to do, and what did you expect to happen?
i had a full inventory and tried to shift click from the chisel interface
#
#### What happened instead? (Attach screenshots if needed)
the game crashed
[crash-2020-12-02_00.59.06-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5627277/crash-2020-12-02_00.59.06-client.txt)

**Comment by Dream-Master** [comment]
@KorGgenT 2.0.7.0 is very old. Try version 2.0.9.0

**Comment by KorGgenT** [comment]
sorry my mistake. it's the most recent one on technic right now, and i had to name it from memory
