### ISSUE TITLE
Quest 877 : Scepter with 75 vis

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#7027]
#### Which modpack version are you using?
2.0.9.0qf4

Scepter isn't detected

![image](https://user-images.githubusercontent.com/62377720/100907346-7ec7e600-34ca-11eb-8909-54de7ec4349d.png)

**Comment by Prometheus0000** [comment]
Duplicate, also fixed on latest
