### ISSUE TITLE
ME Arcane terminal crash

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7028]
#### Which modpack version are you using?
2.0.9.3.a.dev
#
Game crashed when I shift clicked a recipe from NEI in the ME Arcane terminal. I don't have the crash log, it didn't generate a crash log

**Comment by boubou19** [comment]
is it reproducible? or was it a random crash?

**Comment by repo-alt** [comment]
What recipe at least

**Comment by Alexdoru** [comment]
Enchanted fabric, I just tried it again and the game crashes and goes back to title screen

![image](https://user-images.githubusercontent.com/57050655/101070676-f74aa780-359b-11eb-8fdd-c5e5dc0f91d4.png)

**Comment by repo-alt** [comment]
Is that dedicated server?

**Comment by Alexdoru** [comment]
No I am playing in singleplayer

**Comment by Alexdoru** [comment]
Error seems to be at [19:14:59] 


https://paste.ee/p/FAHXr

**Comment by repo-alt** [comment]
Thaumcraft is f-n _special_ ...

**Comment by repo-alt** [comment]
Do yo want to test the fix?

**Comment by Alexdoru** [comment]
yeah I can test the fix

**Comment by repo-alt** [comment]
[Uploading thaumicenergistics-1.1.3.7.jar.zip…]()

**Comment by repo-alt** [comment]
if it fails to upload here ping me in discord

**Comment by Alexdoru** [comment]
Not fixed :/

https://paste.ee/p/V2tJe


![image](https://user-images.githubusercontent.com/57050655/101078166-0e8e9280-35a6-11eb-8914-8d1df092f5aa.png)

**Comment by repo-alt** [comment]
ok, quickfix didn't work, will have to reproduce and test locally

**Comment by Alexdoru** [comment]
I clicked once and it worked, then I clicked a second time and it crashed want log ?

**Comment by Dream-Master** [comment]
@Alexdoru we need always a log :)

**Comment by repo-alt** [comment]
we communicated in private, new version is already in testing

**Comment by repo-alt** [comment]
(For the record: topic starter tested the fix, and it worked)
