### ISSUE TITLE
[Suggestion] New mod  Agriculture

### ISSUE THREAD

**Issue by bookerthegeek** [GTNewHorizons/GT-New-Horizons-Modpack#7029]
# Heyo!

Not using the template, please don't kill me. ;) I would like to suggest a mod to the pack, other then [Cooking For Blockheads](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads) which was suggested [HERE](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/810). This mod would be [Agriculture](https://www.curseforge.com/minecraft/mc-mods/tmagriculture) by Team Metallurgy. Ok, on to reasons why & maybe why not this should be added to the pack:

### Reasons Why
- The blocks in the mod are aesthetically pleasing. 
- Adds many new foods for players to make
- Ability to move recipes to those blocks so they are required for more involved food.
- Not well known so it would be a new experience for most players

### Reasons Why Not
- Mod would need to be fixed as it currently is slightly broken with later forge updates.
  - I've been told (No idea if it is true or not) that this is an easy fix? I don't know java so have no idea. 
- Not as well loved as Cooking4Blockheads

~edit, forgot to say what mod! Add to the post.

**Comment by KiloJoel** [comment]
what mod do you mean?

**Comment by Dream-Master** [comment]
@mitchej123 is allready backporting features and fix stuff to add this mode some day.

**Comment by Prometheus0000** [comment]
He's talking about agriculture, not cfb

**Comment by repo-alt** [comment]
I honestly don't see much value in that mod, because it is completely superseded by Harvescraft+CfB combination

**Comment by boubou19** [comment]
Also, early game is very populated in term of content, so i don't think it needs additionnal alternatives.
