### ISSUE TITLE
Quest 887 isn't checking

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#7030]
#### Which modpack version are you using?

2.0.9.0qf4

![image](https://user-images.githubusercontent.com/62377720/101026615-6bbf1f80-3577-11eb-9654-1da37f384eb7.png)

In addition, the materials required are not the same in the quest and in the recipe

![image](https://user-images.githubusercontent.com/62377720/101026837-ac1e9d80-3577-11eb-86ba-99d4b7b2570d.png)

**Comment by Prometheus0000** [comment]
Duplicate, staves are broken, see #5830.
