### ISSUE TITLE
Smeltery tooltip for seared stone is inaccurate

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7037]
#### Which modpack version are you using?
2.0.9.0
#
#### What did you try to do, and what did you expect to happen?
I tried to make a seared stone block when the fluid level said it had more than one block in the smeltery, and expected to get a block out.
#
#### What happened instead? (Attach screenshots if needed)
The basin filled partially, emptying the smeltery of seared stone.

#
#### What do you suggest instead/what changes do you propose?
It looks like the amount of molten seared stone required for a block was changed in the recipe, but the unit of measurement that tcon uses for the block in the smeltery GUI fluid tooltip remained the same.  Seems like it thinks 144mb is a block?  You could just set the seared stone block recipe to 144mb, if the tooltip can't be changed.
As it is now, it takes 45 cobble per seared stone if you melt 8-cobble parts to speed things up, and 20 cobble per seared stone if you don't (but that takes over 3x the lava)

**Comment by Dream-Master** [comment]
you can make a hammer head out of 8 cobble wich make the ratio and the lava usage better.

**Comment by McFrugal** [comment]
I already edited the post and made a note of that on the bottom.  It only saves lava though?
