### ISSUE TITLE
it's a reasonable reward advanced energy hatch can undercook 

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#7038]
in 2090, LCR can under-clock after the LCR overclock to 1t, in 2094 this has been fixed. i think this mechanic is a reasonable reward for you to make more advanced energy hatch. it's better to change the uev uiv umv energy hatch recipe than the mechanism.

**Comment by Prometheus0000** [comment]
Please explain better. Also state how it used to work, what changed, and why you don't like this change.
