### ISSUE TITLE
Tinker's Smeltery Issue

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#7039]
#### Which modpack version are you using?
2.0.9.3dev
#
#### If in multiplayer; On which server does this happen? 
My own
#
#### What did you try to do, and what did you expect to happen?
I broke the wall of a tinkers smeltery containing molten metal and expected it to unform the multiblock and stop harming mobs.
#
#### What happened instead? (Attach screenshots if needed)
I died by falling out of the world. And continued to die in the spot until i removed the smeltery controller.
#
#### What do you suggest instead/what changes do you propose?
Make the smeltery have to be formed to damage entities, otherwise you could easily bug this, and trick other players into entering its range.

**Comment by Ethryan** [comment]
Maybe add some kind of is the smeltery formed check at the damage code: [Here i Think].(https://github.com/GTNewHorizons/TinkersConstruct/blob/5d055ec8dc5577b3ebd8405418cf3cf3865eb2ad/src/main/java/tconstruct/smeltery/logic/SmelteryLogic.java#L341)

**Comment by repo-alt** [comment]
I experienced that on zeta once, but couldn't reproduce later (didn't break the controller)

**Comment by Ethryan** [comment]
Well, i died 7 times to this, and lost a lot of my tinker tools.

**Comment by Prometheus0000** [comment]
Should also be fixed due to https://github.com/GTNewHorizons/TinkersConstruct/pull/22?

Could you test if it still happens?

**Comment by Ethryan** [comment]
Think this is fixed, i will close this for now but let's reopen the issue if anyone reports something different.
