### ISSUE TITLE
evolved blaze can generate a lot of lag

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7040]
#### Which modpack version are you using?
2090QF4
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### 
Epsilon was running slower, so i profiled the server with Opis. I found that evolved blaze lagging epsilon. (it was falling when i tp-ed on it if that matters)
![image](https://user-images.githubusercontent.com/12850933/101176095-5238d900-3646-11eb-94a8-443a3f5ba73f.png)
![image](https://user-images.githubusercontent.com/12850933/101176164-6977c680-3646-11eb-81eb-1e498db21ae5.png)

**Comment by repo-alt** [comment]
It is a real bad luck that it was loaded. Was some miner nearby or what is the reason?

**Comment by boubou19** [comment]
it was in a chunk having an ore drill iirc (corrupted my instance while using opis, currently rebooting the instance  right now). Maybe it was detecting the fake player?
