### ISSUE TITLE
Gt transformer tooltip

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#7041]
#### Which modpack version are you using?
2,0,9,0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I placed gt transformer and turned it to step up mode, expected to get higher voltage
#
#### What happened instead? (Attach screenshots if needed)
Explosion
#
#### What do you suggest instead/what changes do you propose?
Add tooltip to transformer "Input for step-down transformer is output for step-up mode" and make it be a huge red colored tooltip

**Comment by Prometheus0000** [comment]
Is this really necessary? It already says you can use the soft mallet to invert it, you can't help stupidity or forgetfulness.

**Comment by Ethryan** [comment]
Maybe add the text to the LV transformer quest instead.

**Comment by Prometheus0000** [comment]
It already gives a warning.

**Comment by repo-alt** [comment]
No amount of red text will help

**Comment by GTNH-Afx237v7** [comment]
Check the Waila tooltip, it says which mode it is in and where input/output side is.
