### ISSUE TITLE
Steam age quest "Pumping Water" (2446) returns T1 lootbag

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7043]
#### Which modpack version are you using?
2.0.9.4-dev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What do you suggest instead/what changes do you propose?
Change to Steam

**Comment by bartimaeusnek** [comment]
If that is the Water Pump, then thats intended, bcs. you basically need to be at the border to LV to do that thing.

**Comment by repo-alt** [comment]
It is still somewhat weird because there is 3 steam -> 1 T2 bag conversion. Is that tier used for any other quest?

**Comment by Prometheus0000** [comment]
Tier 1 != lv. The bag only has a cookie in it. I don't know why this bag seems to be unused.

**Comment by Dream-Master** [comment]
Tier2 is lv @Prometheus0000

**Comment by Dream-Master** [comment]
Tier1 is unused. The cooki is a placeholder

**Comment by Prometheus0000** [comment]
That's what I said though? That 1 is not lv?
