### ISSUE TITLE
Cleanroom quest is gated behind a wafer that requires a cleanroom to be produced

### ISSUE THREAD

**Issue by Xela10001** [GTNewHorizons/GT-New-Horizons-Modpack#7044]
#### Which modpack version are you using?
2.0.9.4 dev
#
The cleanroom is gated behind the Central Processing Unit quest, but to make that kind of wafer, a cleanroom is required.
Just change the dependency of the cleanroom quest to not need that wafer's quest.
![image](https://user-images.githubusercontent.com/47480171/101205963-4eb54a00-3666-11eb-8e86-6cd1ac1a8b14.png)

**Comment by Xela10001** [comment]
Central Processing Unit quest's number is #1018 btw

**Comment by Prometheus0000** [comment]
I was trying to make it clearer as to the order of which you make the VF, cleanroom, and EV circuits, but I must've messed up this part.
