### ISSUE TITLE
Electrotine in washer issue

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7046]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Tried to make impure pile of electrotine dust into electrotine in a simple ore washer
#
#### What happened instead? (Attach screenshots if needed)
The recipe stalls after washing 1 dust, seems like it doesn't recognise the output as the same item it produces. Will produce another 1 dust each time that dust is removed.
![image](https://user-images.githubusercontent.com/17787093/101232146-ae801500-36a7-11eb-9bab-9e83519654ba.png)

#

**Comment by draknyte1** [comment]
Issue doesn’t really belong here. 
https://github.com/alkcorp/GTplusplus/issues 

Thing is, the recipes are generated in a simple manner. Iterate all OD entries for impure dust and crushed, if clean version exists, make recipe. 

Machine uses same logic as every other standard GT machine, so can’t really say why this occurs at all.

**Comment by KiloJoel** [comment]
> 
> 
> Issue doesn’t really belong here.
> https://github.com/alkcorp/GTplusplus/issues
> 
> Thing is, the recipes are generated in a simple manner. Iterate all OD entries for impure dust and crushed, if clean version exists, make recipe.
> 
> Machine uses same logic as every other standard GT machine, so can’t really say why this occurs at all.

The clean electrotine is the projectred item
![image](https://user-images.githubusercontent.com/17787093/101232689-f5bbd500-36aa-11eb-9c61-a0c6c17cd13a.png)

**Comment by draknyte1** [comment]
Output wouldn’t matter. 
It’s going to return the first value registered to dustX in the OD.

**Comment by Glease** [comment]
In GTNH electrotine is forced to unify towards PR's electrotine
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/3a6e59e0e949e2086b3e2d49ae82dc462174978e/config/GregTech/Unification.cfg#L13294
Since it's not default I guess it's not the first value registered to dustX in the OD.

**Comment by KiloJoel** [comment]
Tested a different electrotine recipe, this one works fine
![image](https://user-images.githubusercontent.com/17787093/101234759-f019bb80-36b9-11eb-98bd-59b0e5438389.png)
