### ISSUE TITLE
GC Fuel loader GregTech Wrench Interactions

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#7047]
#### Which modpack version are you using?
2.0.9.0-QF4
#
#### If in multiplayer; On which server does this happen? 
Stonehuts
#
#### What did you try to do, and what did you expect to happen?
Wrench a Galacticraft Fuel loader and it changes directions for the energy and fuel ports, 
#
#### What happened instead? (Attach screenshots if needed)
The fuel loader would change directions for a few ticks then change back immediately, no matter with a connected launch pad or not.
#
#### What do you suggest instead/what changes do you propose?
GC fuel loader should respect GregTech wrenchs and change directions

**Comment by Prometheus0000** [comment]
@glowredman I recall this used to work? Did you change anything related or am I remembering wrong?

**Comment by glowredman** [comment]
I didn't change anything. Iirc, GC has support for the IC2 wrench, but I'm not sure
