### ISSUE TITLE
Nano suit is a lie 2.0

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7048]
#### Which modpack version are you using?
delta
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/59776356/101234240-7f45c400-36f8-11eb-8964-8eedb37e4e7e.png)
![image](https://user-images.githubusercontent.com/59776356/101234298-ef544a00-36f8-11eb-9112-5719f89c0662.png)
Holding a lava bucket while wearing a nano suit 
Jump into the lava with  nanosuit

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/101234261-a43a3700-36f8-11eb-82ec-aa8d47f54155.png)
![image](https://user-images.githubusercontent.com/59776356/101234291-d8adf300-36f8-11eb-9d0e-e101afec3c1a.png)
If wearing a hazmat suit will provide fire resistance
But the nanosuit does not provide fire resistance

#
#### What do you suggest instead/what changes do you propose?
add fire resistance to nano suits
and provides full hazmat protection
![image](https://user-images.githubusercontent.com/59776356/101234317-1c086180-36f9-11eb-9164-129030dc2b90.png)

**Comment by Eason134HK** [comment]
It also provides fire resistance when struck by lightning or burned by flames

**Comment by Prometheus0000** [comment]
Why would we do that, it's not supposed to have fire res? Also, nano does have hazmat protection.

**Comment by Dream-Master** [comment]
@Eason134HK so far ik you can put enchantments on them

**Comment by draknyte1** [comment]
You cannot enchant Nano and Quantum. 

Lava buckets doing fire damage probably doesn’t check for hazmat properly. Check core mod or anger mod (whichever adds it), if it checks for the hazmat directly instead of the isWearingHazmat(), it won’t work for anything.

**Comment by Eason134HK** [comment]
> Why would we do that, it's not supposed to have fire res? Also, nano does have hazmat protection.

Yes  nano does have hazmat protection. but it **DON'T** have _full hazmat protection_
![image](https://user-images.githubusercontent.com/59776356/101315496-9c63c980-3895-11eb-829d-40fe869dd6a1.png)

**Comment by Prometheus0000** [comment]
Hazmat protection is not fire resistance, it's protection against pollution and radiation. The hazmat suit in particular just happens to have fire res. If anything, we should remove it from that instead.

**Comment by Eason134HK** [comment]
> Hazmat protection is not fire resistance, it's protection against pollution and radiation. The hazmat suit in particular just happens to have fire res. If anything, we should remove it from that instead.

So you don't think lava bucket is hazmat?

**Comment by draknyte1** [comment]
> Hazmat protection is not fire resistance, it's protection against pollution and radiation. The hazmat suit in particular just happens to have fire res. If anything, we should remove it from that instead.

Hazmat is protection from:
Heat damage
First damage
Electric damage
Radiation damage
Pollution damage
And one other type (Bio)

This is a bug, but probably on the mod adding damage to lava buckets. As you can literally swim in lava wearing hazmat. Changing the default hazmat won’t happen, trust me.

**Comment by Prometheus0000** [comment]
Well, are you going to add fire res so we should reopen it? That's probably the important part.

And I never said that we _would_ change the default hazmat. I still think it's weird, but it's balanced by being terrible armor.

**Comment by draknyte1** [comment]
The issue probably lies is whatever mod adds fire damage for lava buckets, etc. Less so my problem.
