### ISSUE TITLE
Railcraft shunting wire has no recipe

### ISSUE THREAD

**Issue by truenachtara** [GTNewHorizons/GT-New-Horizons-Modpack#7049]
#### Which modpack version are you using?
2.0.9.0

#
#### What did you try to do, and what did you expect to happen?
Expected a recipe to craft it, but there was none

#
#### What do you suggest instead/what changes do you propose?
Given that wire support frame DOES have a recipe, and the electric locomotive is MV, it seems the wire should be MV as well. The original recipe is a block of copper, 4 paper, and 4 lead ingots in a rolling machine to make 8.

Recommendation: 
Crafting Recipe: 2x lead wire on corners, rubber sheets on top/left/right edge, wire cutters on bottom, 8x copper (or annealed copper) cable in the center to craft 4
Assember: 10s, 120eu/t (MV), 2 2x lead wires, 288mb rubber, 8x copper (or annealed copper) cable, circuit 23 to craft 8

**Comment by Prometheus0000** [comment]
Already fixed, see #6356

**Comment by Dream-Master** [comment]
@truenachtara will be in the next official version.
