### ISSUE TITLE
AE essentia storage

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#7050]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
private
#

#### What do you suggest instead/what changes do you propose?
Add tooltip or into notofication in quest that in order to open ae essentia storage you need to research warded doors(Warded arcana research, artifice tab)

**Comment by Prometheus0000** [comment]
That seems like it would lead to a lot of notes about how to research stuff, which I really don't want to investigate.
