### ISSUE TITLE
Quantum Chest AE2 sometimes voids Items on server restart

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#7051]
#### Which modpack version are you using?
2.0.8.3 but issue is also present in newer version (according to bot) 
#
#### If in multiplayer; On which server does this happen? 
Playing on myFTB 
#
#### What did you try to do / what happend? 
I have muliple Quantum Chests for storing all dusts etc, those are connected to my me system via storage bus. I realised that after some restarts (not every time) the stock of  some materials that are stored in quantum chests goes down (without any of them being used). E.g. having 53k diamonds after restart, ore processing running producing roughly 40k diamonds in the next 6 hours till server restart. Stock before restart approx 90k, but after the restart its down to 53k again. The rest of the world did not get resettet or anything, only happens to stuff stored in quantum chests. 
#

#### What do you suggest instead/what changes do you propose?
If possible fix it :) dont really know what causes it tho / appears randomly

**Comment by repo-alt** [comment]
I'm not sure how AE is to blame, AE is a tool to access the chest, it does not store the stuff. If the chest is in the void/garden world, perhaps it is the old intermittent bug with tileentity (not) saving

**Comment by alphaNOVAircraft** [comment]
It is in the Void dim, should have added it, sry. 
Didnt want to blame AE, just wanted to mention it occures in combination with AE. 
Iirc bot encountered that behavior as well and he is not in a garden / void dim iirc

**Comment by boubou19** [comment]
it happens without AE, and it seems that @combusterf knows how to avoid the triggering of the bug.

**Comment by combusterf** [comment]
The TE bug manifests differently for me, but from what I observed, it seems to require the dimension to unload and reload without a server restart. So as a workaround, you can have a chunkloader active in your dim whenever you go out for mining and other stuff.

**Comment by Alexdoru** [comment]
Yeah it happened to me also and I am in the overworld. I noticed that after a restart sometimes it seems to load in the chest the quantity of item from the previous restart, as if it didn't save properly the number of item in the chest when the server closed.

**Comment by repo-alt** [comment]
Also maybe it is Thermos again? It may _optimize_ region saving somehow

**Comment by Alexdoru** [comment]
I don't have thermos on singleplayer ? Thermos is a multiplayer thing right ?

**Comment by boubou19** [comment]
Themos is a server type yes. Because you play SP, your game use normal forge.

**Comment by botn365** [comment]
have the same problem but this is in overworld and chuncks where loaded with a adim anchore
i have seen other wierd non saving bugs 
i had a chunck loaded by a admin anchore wich conatined 1 MEBF and on server restart the input bus would always void the circuits in the input bus and the ebf would always be off after restart as well
i have had covers not get saved on a other MEBF auto maintence hatch
this seems to be a problem all over GT

**Comment by repo-alt** [comment]
AE cells avoid that problem just by writing to NBT immediately after change. That may seem like overprotective and not TPS-friendly, but probably comes from a bitter experience.

**Comment by greesyB** [comment]
I've started to notice this issue on almost every server restart. Chests are in the overworld, admin loaded and only interacted with through storage buses. Private server, no thermos.

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1001
