### ISSUE TITLE
Scanned items and aspects arent kept through upgrading versions

### ISSUE THREAD

**Issue by Xela10001** [GTNewHorizons/GT-New-Horizons-Modpack#7052]
#### Which modpack version are you using?
2.0.9.4 dev
#
Upgrading versions destroyed all my scanned items and stored aspects.
All my aspects in the research table have been brought back to 0 and all the items I scanned are now as if i had'nt scanned them.
I upgraded versions exactly as listed in the gtnh wiki, by deleting the mods, config, resources and scripts folders and replacing with the new ones.

**Comment by repo-alt** [comment]
iirc all that stuff is bound to user id

**Comment by Xela10001** [comment]
what folder is it in?

**Comment by repo-alt** [comment]
"playerdata" in the save folder

**Comment by repo-alt** [comment]
*.thaum , etc.

**Comment by boubou19** [comment]
should not happen if [this guide](https://gtnh.miraheze.org/wiki/Installing_and_Migrating#Files_to_backup) is followed right?

**Comment by Xela10001** [comment]
I never altered my saves folder, and the research and aspects only disappeared after i upgraded. Are you sure there arent other places where the data is kept? Or if the new dev version's version of thaumcraft deletes this data?

**Comment by repo-alt** [comment]
We don't modify TC, it is closed source

**Comment by Xela10001** [comment]
> should not happen if [this guide](https://gtnh.miraheze.org/wiki/Installing_and_Migrating#Files_to_backup) is followed right?

Thats migrating launchers tho

**Comment by repo-alt** [comment]
Look in that folder, and compare username.thaum with the version from backup

**Comment by repo-alt** [comment]
(I hope you do backup)

**Comment by Xela10001** [comment]
Nope, i dont lol

**Comment by Alexdoru** [comment]
![image](https://user-images.githubusercontent.com/57050655/101246492-ff2d5780-3713-11eb-8429-96399d4c66ac.png)

I am having the same problem, I looked at the player data folder and it seems that it is using username and not uuid. Alexdoru, Al3xdoru and ComeradeDuckyDuck are my usernames and it is three separates files even thought it'a all me.

Also that doesn't explain the fact that in game when I open the creative thaumonomicon in addition to running the " /thaumcraft research Alexdoru all " command, I can't see everything. I  can't see everything in the thaumonomicon and I can't see some recipes in NEI

**Comment by boubou19** [comment]
Do you have 3 accounts, or do you play with cracked launcher?

**Comment by Alexdoru** [comment]
you can change your username on mojang every 30 days

**Comment by Alexdoru** [comment]
that's why it is better to use uuid and not usernames

**Comment by boubou19** [comment]
It's weird that no one reported it before.

**Comment by repo-alt** [comment]
You may rename the *.thaum after changing your name. I agree that using user name instead of GUID is a bad practice, but changing it now is not trivial (TC is closed source), and would break stuff

**Comment by boubou19** [comment]
Should be written somewhere in quests/wiki at least.

**Comment by Alexdoru** [comment]
Still that wouldn't explain that rn whith the creative thaumonomicon I can't see everything : 
![image](https://user-images.githubusercontent.com/57050655/101246742-8202e200-3715-11eb-9644-86101a683438.png)

**Comment by GTNH-Afx237v7** [comment]
I just ran into this as well, and I have not changed my username. In previous versions (2.0.8.8 and 2.0.9.0) the username remained and it kept the scanned entries when updating.
