### ISSUE TITLE
Twilight Forest - client crashes on load

### ISSUE THREAD

**Issue by TheElan** [GTNewHorizons/GT-New-Horizons-Modpack#7054]
#### Which modpack version are you using?
2.0.9.0
# 
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I've tried to travel to twilight forest. I was expecting to load in and go exploring for the first time.
#
#### What happened instead? (Attach screenshots if needed)
Instead after world started rendering client suddenly crashed. Client keeps crashing after world has rendered for ~10sec. 
#
#### What do you suggest instead/what changes do you propose?
Fix casting issue in `NetworkEventFiringHandler`, jugging from log line:
```
ClassCastException: com.TominoCZ.FBP.renderer.FBPWeatherRenderer cannot be cast to twilightforest.client.renderer.TFWeatherRenderer
```

#### Additional mods installed
I've had some additional modes installed initially (recommended once, like matmos, optifine + shaders pack), however I've removed them later on as performance got worse, so client should be clean.

### Error Logs
[log.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5647720/log.txt)

**Comment by Dream-Master** [comment]
@jss2a98aj any idea ?

**Comment by Ethryan** [comment]
Seems to be an error with the client mod [Fancy Block Particles](https://www.curseforge.com/minecraft/mc-mods/fancy-block-particles) and TF, Nothing to do with standard GTNH.

**Comment by TheElan** [comment]
Ok, it works after full re-install, I suspect that fancy block particles left something after de-install

**Comment by TheElan** [comment]
Thanks for reacting so fast :) Sorry for bothering.
