### ISSUE TITLE
Silver nuggets can't be directly processed in early game

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7055]
#### Which modpack version are you using?
2.0.9.0

#
#### What did you try to do, and what did you expect to happen?
I smelted some crushed silver ore and got nuggets in steam age, then found I could not turn them into ingots directly.  The only way is to macerate them first.

#
#### What do you suggest instead/what changes do you propose?
Add a Compressor recipe and a Smeltery melting recipe for silver nuggets to bring them in line with other basic materials.
Iron, Tin and Copper nuggets lack a Compressor recipe as well to turn them into ingots, but you can melt those so it's less clear if that's intended or not.  I feel like wrought iron shouldn't be so special in that case.

**Comment by repo-alt** [comment]
Alloy smelter + ingot mold

**Comment by McFrugal** [comment]
I don't really want to spend 4 steel just to skip macerating nuggets.

**Comment by Prometheus0000** [comment]
You're not supposed to use the compressor.

**Comment by McFrugal** [comment]
Ok, what about the smeltery though?

**Comment by Prometheus0000** [comment]
Read the TT on the casting basin.

**Comment by McFrugal** [comment]
The tooltip says "Some metals processed in the smeltery do not meet purity requirement for GregTech processing", which implies that you can process metals in the smeltery to get ingots which can't be used in other recipes, not that you can't process certain metals in the smeltery.  Like, if you could make silver tcon tools it wouldn't contradict the tooltip at all.

**Comment by Prometheus0000** [comment]
Make a PR to change the tooltip then, instead of accepting dream's germanglish.
