### ISSUE TITLE
Cannot craft Cooked rabbit

### ISSUE THREAD

**Issue by ecr99** [GTNewHorizons/GT-New-Horizons-Modpack#7056]
#### Which modpack version are you using?
GT New Horizons-2.0.9.0-1.7.10
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I tried to craft Cooked rabbit from Pam's harvestcraft using a furnace.
#
#### What happened instead? (Attach screenshots if needed)
I couldn't because there's no recipe for cooked rabbit. The only way to get cooked rabbit is using a Pam's harvestcraft oven , that oven cannot be crafted.
#
#### What do you suggest instead/what changes do you propose?
Add a recipe to get cooked rabbit by using a furnace , like the other meats.

**Comment by KiloJoel** [comment]
If you want a quick fix, the Kitchenware 2.0 quest has a pam's oven as a choice reward

**Comment by KiloJoel** [comment]
ah, it was already fixed

**Comment by Dream-Master** [comment]
you get raw rabbit from twilight rabbit in 2.0.9.4
