### ISSUE TITLE
Multifarm can  obtain bedrock

### ISSUE THREAD

**Issue by DrParadox7** [GTNewHorizons/GT-New-Horizons-Modpack#7057]
####Which modpack version are you using?
2.0.9.0-1.7.10

####If in multiplayer; On which server does this happen?
/
#### What did you try to do, and what did you expect to happen?

I tried taking the previous Issue #6963 regarding how manual farms do not behave as they should to the limit. I discovered you can obtain bedrock fairly easy at the roof of the Nether with it.

It can be replicated by:
-Creating a multifarm at the ceiling of the nether
![2020-12-06_02 59 26](https://user-images.githubusercontent.com/47131096/101270371-4b0dea00-3770-11eb-9a33-adb174f55092.png)
 
-Run one of the three broken **Manual Farms**. 
In this case I used a crop farm but a Vegetable farm or Peat farm will do just as well.
![2020-12-06_02 59 38](https://user-images.githubusercontent.com/47131096/101270375-611baa80-3770-11eb-85c8-1f6657721ff2.png)

-Provide Dirt, Power, Water and Fertilizer

-Profit $$$

#
#### What happened instead? (Attach screenshots if needed)
![2020-12-06_03 00 03](https://user-images.githubusercontent.com/47131096/101270390-7e507900-3770-11eb-9898-13781bc11c9b.png)

#
#### What do you suggest instead/what changes do you propose?
Blacklist dirt from the Manual farms gui and add hardness checks.

**Comment by KiloJoel** [comment]
Probably better to not allow it to do anything with hardness < 0

**Comment by Houstonruss** [comment]
bruh

**Comment by DrParadox7** [comment]
![2020-12-06_04 11 14](https://user-images.githubusercontent.com/47131096/101271271-50236700-3779-11eb-9f66-dd9b285e3c20.png)
![2020-12-06_04 12 11](https://user-images.githubusercontent.com/47131096/101271276-587ba200-3779-11eb-989a-4dfad98a2838.png)

Anything is possible at this point

**Comment by mitchej123** [comment]
hahahahahahaha; hilarious
