### ISSUE TITLE
zpm single block pump kicks you from server and stops you from rejoining 

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#7058]
#### Which modpack version are you using?
9.0
#
#### If in multiplayer; On which server does this happen? 
MP
#### What do you suggest instead/what changes do you propose?
when you place it and power it it creates a huge lag spike wich basicly kicks you from the server

**Comment by repo-alt** [comment]
Has a huge area to calculate

**Comment by Prometheus0000** [comment]
Is this even fixable? The only reason to use them past HV versions is for unknowwater on the T8 planet, right? Is UG pumping not enough? Do we need these pumps to begin with?

**Comment by Dream-Master** [comment]
The uv pump was removed because the pump region was so huge and it lags forever. Maybe the zpm pump need to be removed as well.
