### ISSUE TITLE
Bronze Chisel Head + Stick, character tries to eat it

### ISSUE THREAD

**Issue by Crimmies** [GTNewHorizons/GT-New-Horizons-Modpack#7060]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Single Player
#
#### What did you try to do, and what did you expect to happen?
Tried to Chisel some stuff, just expected to chisel.
#
#### What happened instead? (Attach screenshots if needed)
My character tried to eat the tool. Tried to change tool rod to bronze, happened the same thing https://clips.twitch.tv/FrozenNimbleFerretRuleFive
#
#### What do you suggest instead/what changes do you propose?
I want to use Tinkers Chisel, i like it! Just propose to fix it :P

**Comment by Crimmies** [comment]
Just realize the issue is with every chisel tinkers. Doesn't matter the head/rod.

**Comment by Ethryan** [comment]
The Tinkers chisel works like that, you "Eat" the durability to change blocks.

**Comment by Prometheus0000** [comment]
https://tinkers-construct.fandom.com/wiki/Chisel

> Note: the animation will show whenever you hold right-click, not just when chiseling a block

So basically, it never tells you the block doesn't have a chiseling form. Also, some (like infinity) can't be 'eaten'. Probably the addon part ones.
