### ISSUE TITLE
Two items named Hermetic casing VII

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7062]
#### Which modpack version are you using?
GTNH 2.0.9.4.a.dev
#

there are two items in the game named "hermetic casing VII" and they have a different recipe.

![image](https://user-images.githubusercontent.com/57050655/101291387-a68bb680-3808-11eb-870d-bd193facc4a9.png)
![image](https://user-images.githubusercontent.com/57050655/101291389-ae4b5b00-3808-11eb-8469-23ee2381da60.png)

The quantum tank II uses the 2047/7 to craft and the quantum tank III uses the 2047/8 to craft.
![image](https://user-images.githubusercontent.com/57050655/101291405-c8853900-3808-11eb-876f-17cc64e1d76a.png)
![image](https://user-images.githubusercontent.com/57050655/101291411-cfac4700-3808-11eb-9c45-baa65b8e5d5c.png)

Suggestion : 

Rename the 2047/8 Hermetic casing VIII

**Comment by Prometheus0000** [comment]
What's the situation with VIII, IX and X? Is VIII just missing?

**Comment by Alexdoru** [comment]
It's only the VIII missing yes. I think it's just a misspelling issue cause the Hermetic casing VII 2047/8 has the correct texture that is different from the 2047/7
