### ISSUE TITLE
Time to make some steel quest should be streamlined

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7063]
#### Which modpack version are you using?
2.0.9.0
#
#### What did you try to do, and what did you expect to happen?
I looked at the quest for the bricked blast furnace and noticed it has a lot of requirements.  Most of them are unnecessary, in fact the clay brick ones directly get in the way since you can get brick dust by macerating bricks harvested from worldgen structures.

#
#### What do you suggest instead/what changes do you propose?
Remove most of the basic material steps.  The only parts that need to stay are the firebricks and the bricked blast furnace block, since those are the end result of your crafting steps.

I saw someone complain about this quest in a different way: that you have to gather all the materials before you start combining them, which is a little silly.  It should be possible, for instance, to start macerating the clay before you gather all of it.  I expect there are more quests like this in the quest book.

**Comment by Prometheus0000** [comment]
Complain to dream

**Comment by Dream-Master** [comment]
No why i would to change this. It explain what eaterials you need. If you go and loot Villages its you way to play the game. Some mp worlds have villages disabled.
The quests are optinal so if you dont like it skip it.

**Comment by McFrugal** [comment]
You do understand that people like to complete quests, right?  It's a bad quest.  You should change it.

**Comment by alphaNOVAircraft** [comment]
The Bricks from a village are a workaround. You get a reward for making the quest the way it is intended. Getting the clay isnt that bad. 
Yes a lot of quests are done that way. 

> The quests are optinal so if you dont like it skip it.
Not all of them, iirc there is still not a way to obtain draconic cores without quests?!

**Comment by Prometheus0000** [comment]
This isn't an optional quest, nor can you find the parts, the problem is that you need a huge number of them and if you start on the next step before you finish the previous, you end up without enough at once to complete it.

The solution would be to require 1 of each and then say in the text how many you need.

**Comment by 0lafe** [comment]
Maybe we should stop using the thing that helps people, as a method of rewarding people as well. Really dumb you need to intentionally play worse to receive better rewards

**Comment by Uristqwerty** [comment]
Is it possible to make specific quest steps optional, or automatically complete if a specified later step is completed first? Or even have a checkbox next to specific crafting steps deemed non-critical for "I've already done that", including the ability to de-check it if they later decide they *want* the reminder to craft that bit.

As an anecdote, I had to pull stuff out of furnaces after realizing that the quest needed the full stacks of raw components at once to count, and had to craft a few extra bricks to make up the difference.

**Comment by 0lafe** [comment]
Probably not ideal, but you could definitely pull out all the preliminary components into a separate checkbox task quest that would come before the final product.

**Comment by McFrugal** [comment]
Oh, you can get clay dust from macerating hardened clay, which can be mined from various biomes, so it's quite possible to make a bbf without 1008 clay even if villages aren't spawning.
Plus, roguelike dungeons can spawn with brick blocks.

**Comment by Dream-Master** [comment]
ok i will revisit this quest and look what I can do.

**Comment by Prometheus0000** [comment]
@Dream-Master Is it ok if I change it to my previous suggestion 'The solution would be to require 1 of each and then say in the text how many you need.'

**Comment by Prometheus0000** [comment]
Are you going to do this or should I, like I said a month ago?
