### ISSUE TITLE
Brick block takes 1 second to macerate, individual bricks take 20

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7065]
#### Which modpack version are you using?
2.0.9.0

#
#### What did you try to do, and what did you expect to happen?
Someone on discord noted that brick blocks take 1 second to macerate, while individual bricks take 20.  I took a look, and I also noticed that brick stairs take 20 seconds to macerate.

#
#### What do you suggest instead/what changes do you propose?
I think the recipes are mixed up and brick blocks should take 20s while individual bricks should take 1s.  Anywhere from 1 to 5 seconds seems appropriate.  If you want to get granular, brick stairs could take 15s.  Also the bricks slab has no maceration recipe, that should be added.

**Comment by GTNH-Colen** [comment]
I would agree this makes little sense in its current state but seriously against making normal bricks take 20s, it's just silly. Item bricks should take 1s and the block should take 3-4s possibly.

**Comment by alphaNOVAircraft** [comment]
Or make both recipes equal time, so you can decide if you want to spend some time crafting the blocks or just shred them directly, or make bricks blocks double the time of the single bricks. 
1 s seems a bit low, but 2 and 5 or smth like that should be enough, no reason to be 20 sec

**Comment by Prometheus0000** [comment]
Does anyone even bother though? When you're done with the ovens, there's nothing to use the brick dust on is there? Or can you reuse it for the the advanced coke oven? Before pyros obsolete it too of course.

**Comment by Prometheus0000** [comment]
Wait, which brick dust are you talking about, there's multiple?

**Comment by alphaNOVAircraft** [comment]
Atm i always craft the blocks, cz the massive decrease in processing time. Past bbf brick dust is useless, but those numbers are still wierd, not a gamebraking bug but just dont seem right. 
Talking about the dust you get by macerating the vanilla bricks
