### ISSUE TITLE
Aluminum Brass Alloy Smelter Recipe

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#7066]
#### Which modpack version are you using?
Newest dev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Looking up Aluminum Brass recipe. Expected the alloy smelter recipe to be as / more efficient then the smeltery recipe
#
#### What happened instead? (Attach screenshots if needed)
In a smeltery you get 1 aluminum brass with 3/4 ingot of aluminum and 1/4 ingot of copper. But if you do it in the alloy smelter you need 3 copper and 1 aluminum to get 1 aluminum brass. 
![2020-12-07_02 30 10](https://user-images.githubusercontent.com/29660362/101300115-cb961e80-3834-11eb-9489-6bdb0bf74815.png)

#
#### What do you suggest instead/what changes do you propose?
Changing the alloy smelter recipe to yield 4 aluminum brass ingots

**Comment by Ethryan** [comment]
This is in GTNH Core, 
Line [Link](https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/189c0f350e45a25875e7c5581023437d18f082a4/src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java#L52), nothing i did, but i suggest you change this to 4.
