### ISSUE TITLE
Add textures for each programmable circuit (GT++) [FOR DRAKNYTE1]

### ISSUE THREAD

**Issue by aLegoz** [GTNewHorizons/GT-New-Horizons-Modpack#7068]
Hello, @draknyte1! Perhaps you didn`t see that issue: [Add textures for each programmable circuit #6993](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6993) 
It would be very nice if you implement this idea in your GT++ mod. You can use my textures which i load in that issue! (I never use them.)
Ty!

**Comment by Ethryan** [comment]
Why don't you open the issue on the [GT++](https://github.com/alkcorp/GTplusplus/issues) github instead of here?

**Comment by Dream-Master** [comment]
@aLegoz yes open up an issue on gt++ side.

**Comment by draknyte1** [comment]
I guess I could. 
It wouldn’t make any sense outside of GTNH though.

**Comment by aLegoz** [comment]
Oh, sry. I asked my friend, they said the repository gt++ is closed
