### ISSUE TITLE
Zeta

### ISSUE THREAD

**Issue by dimondmine2** [GTNewHorizons/GT-New-Horizons-Modpack#7069]
#### Which modpack version are you using?
# GTNewHorizons-1.7.10-2.0.9.4-dev

#### If in multiplayer; On which server does this happen? 
# Zeta

#### What did you try to do, and what did you expect to happen?
# Break maple tree (Pam's) to obtain logs (ID: 1251) to make maple syrup. Expected to be able to use logs to create maple syrup in extractor.

#### What happened instead? (Attach screenshots if needed)
# Maple tree logs, whether generated in wild or from crafted and manually planted tree, when broken are ID: 1252:2. Logs with this ID show no recipes when pressing r. 

#### What do you suggest instead/what changes do you propose?
# Either allow ID 1252:2 to create Pam's Maple Syrup (ID: 6041) or solve for why the logs have a damage value and fix.

**Comment by Prometheus0000** [comment]
Duplicate

**Comment by Dream-Master** [comment]
@dimondmine2 if you report things don't do this in bolt letters. Thanks
