### ISSUE TITLE
Changing crafting quests that can be done out of order to use locked progress flag

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7070]
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6620#issuecomment-692327599

Have we decided to implement this or not?

This won't help with stuff you can pick up from villages or #7063, but should help somewhat.

**Comment by Dream-Master** [comment]
@Prometheus0000 go ahead.

**Comment by Prometheus0000** [comment]
Ok
