### ISSUE TITLE
BQ3 Colored text cursor off

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7072]
#### Which modpack version are you using?
2.0.9.4a dev
#
When editing colored text in titles (and sometimes in the body?), the cursor is off to the right by a couple characters. This makes it hard to edit.
#
#### What do you suggest instead/what changes do you propose?
It work properly. Also, a way to edit the color of titles in a sane way would be nice.

**Comment by chochem** [comment]
still an issue
