### ISSUE TITLE
Missing recipe for Electric implosion compressor

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#7076]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
private
#

#### What do you suggest instead/what changes do you propose?
Add Raw hardener -> Refined hardener(steve carts 2) recipe for electric implosion compressor

**Comment by Dream-Master** [comment]
So far I understand recipes are picked from the implosion compressor recipe map. It is not possible to add recipes ? @bartimaeusnek

**Comment by botn365** [comment]
recipe needs to be moved to code from scripts to fix this

**Comment by Dream-Master** [comment]
Ah ok . Make sense

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7081

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/101616502-b9240c80-3a0f-11eb-8b9a-5dfbffc1a2b6.png)
