### ISSUE TITLE
Impossible to get a Dessert lootbag

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7077]
#### Which modpack version are you using?
2.0.9.0

#
#### What did you try to do, and what did you expect to happen?
I looked at the cooking tab of the questbook and found that there are not enough lootbags to get 6 haute cuisine lootbags to turn in and get a dessert lootbag.  I think you can get 4 or 5 via direct rewards and conversions.

#
#### What do you suggest instead/what changes do you propose?
Either lower the number of haute cuisine lootbags required, or enable some renewable way of getting food lootbags.

**Comment by Prometheus0000** [comment]
Make suggestions for repeating quests. Like donating food items or something.

**Comment by McFrugal** [comment]
Uh, stacks of bread?  Hamburgers?
I'm not a member of the dev team or anything.

**Comment by Prometheus0000** [comment]
I can easily make a quest, but I've got no ideas other than sacrificing a bunch of food items. People would probably be ok with that, but it's a little boring.

**Comment by Dream-Master** [comment]
Not sure if the Dessert Loo bag have items allready.

**Comment by dimondmine2** [comment]
I propose a Let Them Eat Cake quest that requires giving 16 cakes (1x16 or 4x4 in terms of cake types) in return for a food based lootbag.
