### ISSUE TITLE
HV Quest "Synthetic Rubber" is impossible to complete as it requires lightly steam cracked naphtha fluid cells, which can't be created

### ISSUE THREAD

**Issue by SteelGiant87** [GTNewHorizons/GT-New-Horizons-Modpack#7084]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
single player
#
#### What did you try to do, and what did you expect to happen?
Tried to put lightly steam cracked naphtha into a fluid cell using any of a GT output hatch, a GT ULV fluid tank and a LV fluid canner. None worked. JEI contains no recipes for creating cells for any cracked fluids.
#
#### What happened instead? (Attach screenshots if needed)
Cracked fluid stays in block inventory and is not moved to cell, Cracked fluids seem to only be movable via pipes or the hand pump, not via fluid cells. Additionally, hand pump seems to be unable to extract the cracked fluid from the LV fluid canner.
#
#### What do you suggest instead/what changes do you propose?
Change the HV Quest "Synthetic Rubber" to not require fluid cells that are impossible to create

**Comment by Prometheus0000** [comment]
Use a 'Universal Fluid Cell', some fluids require these cells, like steam, cracked stuff, molten redstone, etc. And no, we can't fix it.

**Comment by SteelGiant87** [comment]
Thanks for the quick reply, I had just found the alternate fluid cells as I received some steam ones from a quest, which worked for some reason.

For anyone else who finds this reply while searching for a solution:

The normal empty IC2 "Empty Cell" 4198 can be crafted into the IC2 "Universal Fluid Cell" 4098 (and you can craft them back as well).

The "Universal Fluid Cell" 4098 can contain the cracked fluids and be used to complete the quest.

JEI doesn't help as while it shows a way to make the "Universal Fluid Cell", this item appears useless as it doesn't have any recipes that fill it. I was able to make steam fluid cells without converting to "Universal fluid cell" 4098 by using a fluid canner, so I had assumed that certain fluids could not be put in cells to force using pipes.

Perhaps this information could be added to the "Synthetic Rubber" quest (or some other quest)? Otherwise there is nowhere else in the quest book up to this point that has provided or required this information that I can see.
