### ISSUE TITLE
Planar vortex spawned wisps despawn (Thaumic horizons)

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7085]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
Unlike other automatable spawning methods, wisps spawned by a planar vortex will despawn when a player is not nearby.
#
#### What do you suggest instead/what changes do you propose?
Port over the functionality from ender IO powered spawners that gives the mobs a time where they are protected from despawning

**Comment by Prometheus0000** [comment]
Are they...supposed to spawn wisps? Even if they should, shouldn't we just remove that instead?

**Comment by greesyB** [comment]
Spawning wisps with planar vortex is a "recipe" that you can research and use by tossing in salis mundus

**Comment by Prometheus0000** [comment]
Sounds useful for rare aspects, after reading the TC page. Assuming you can get a node of the right type? Can you make non-primal ones? I assume that's the goal?

**Comment by KiloJoel** [comment]
yeah, similar to how wisps spawned using a powered spawner (or vanilla spawner) will be a random aspect type

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/ThaumicHorizons/blob/46fdf7f730d34c6207fcddce2d13f5c68e239468/src/main/java/com/kentington/thaumichorizons/common/tiles/TileVortex.java#L223

Looks like the code to spawn them.

**Comment by Prometheus0000** [comment]
It looks like https://github.com/GTNewHorizons/EnderIO/blob/27a0a443a216b0a383ca538e6f672d410b247f7d/src/main/java/crazypants/enderio/machine/spawner/TilePoweredSpawner.java#L239 May be what you need? Try it out.
