### ISSUE TITLE
Apiaries can't be autocrafted, Carpenter not accepting items

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#7088]
#### Which modpack version are you using?
2.0.9.0

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
I wanted to set up autocrafting for the forestry apiary, one of the ingredients for the industrial ones

#
#### What happened instead? (Attach screenshots if needed)
The carpenter refuses to accept the impregnated frames in its main inventory:
![image](https://user-images.githubusercontent.com/8459776/101939236-fee5fe00-3be4-11eb-8522-81145d46e1cc.png)
![image](https://user-images.githubusercontent.com/8459776/101940751-3e154e80-3be7-11eb-87cd-c4193daa8f06.png)
![image](https://user-images.githubusercontent.com/8459776/101940689-250c9d80-3be7-11eb-863f-8071c8eb8a8f.png)

After some testing, the carpenter acts as if it lacks sidedness, and only ever allows impregnated frames in the top slot. regardless of input face.

#
#### What do you suggest instead/what changes do you propose?
- Make the recipe automatable, e.g. by switching the bee house and frame, or by adding a copy of the recipe to the LV assembler. If the carpenter itself can be fixed that would be even better.

**Comment by Prometheus0000** [comment]
I don't fully understand what you mean, but did you try adding a stack of the other ingredients first? So it will work properly with those slots until it gets to the frames?

**Comment by combusterf** [comment]
The bee house is not the problem, its the impregnated frame that refuses to be accepted in the correct space - probably because there are many other recipes where the frame does go in the top slot.
