### ISSUE TITLE
Forestry Worktable + Traveller's Backpack crashing game

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/GT-New-Horizons-Modpack#7091]
Eta, 2.0.9.0

Crafting recipes in the forestry worktable crashes my game while I have Traveller's Backpack on, issue is weird because it only happens when I'm playing on laptop, crash isn't happening while I'm playing on PC. Taking off travellers's backpack resolves problem. 

Crashlog and full log included below.

[2020-12-12-1.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5682835/2020-12-12-1.log)
[crash-2020-12-12_10.26.14-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5682836/crash-2020-12-12_10.26.14-client.txt)

**Comment by repo-alt** [comment]
may drop you a fixed version to test, since it is unlikely to be easy to reproduce otherwise
