### ISSUE TITLE
Warped tumor preventing player from gaining warp

### ISSUE THREAD

**Issue by NG-ChE** [GTNewHorizons/GT-New-Horizons-Modpack#7093]
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I did the self infusion: warped tumor from thaumic horizons, which is supposed to remove 50 total warp and give it back upon death.
#
#### What happened instead? (Attach screenshots if needed)
The warped tumor removed 55 permanent warp, and I can no longer gain any warp. I tried doing some warpy research and noticed I didn't gain any warp. I restarted the client, then I tried taking tainted fragments to get temp/sticky warp and also tried using warped clothing. Nothing allowed me to get warp. I have also tried killing my player and did not gain back any warp.
#
#### What do you suggest instead/what changes do you propose?
Make it so the cap on warp removed is working, and the player gets warp back upon death.

**Comment by Prometheus0000** [comment]
Duplicate. Go post on the issue I linked you, and I'll reopen it.

**Comment by Prometheus0000** [comment]
#5404 Old issue where it was decided to half-assedly nerf it (but not enough) instead of fixing it.

**Comment by NG-ChE** [comment]
After researching a few forbidden knowledge items, I finally started gaining warp after completing the research and the tainted fragments are working again. However, arcane litmus paper isn't getting consumed now, even though I have warp.

**Comment by KiloJoel** [comment]
That's intended, litmus paper has a chance to be used based on how high your warp is.

**Comment by bombcar** [comment]
I can't get this to happen anymore but perhaps the tumor sets warp "negative" somehow if you use it without having warp? Will experiment a bit more.

**Comment by draknyte1** [comment]
> I can't get this to happen anymore but perhaps the tumor sets warp "negative" somehow if you use it without having warp? Will experiment a bit more.

Nope. 

It gets the players warp level and removes it either in the same line of code or the line after. Don’t even think TC would allow that regardless.

**Comment by bombcar** [comment]
No, something definitely triggers twice, I saw it drop 50 and then drop 40+ more (via ingameinfo warp modling).

I am suspicious of https://github.com/GTNewHorizons/ThaumicHorizons/blob/4bf23df25b8edc57a8d11526bd843cd5f101e831/src/main/java/com/kentington/thaumichorizons/common/lib/EventHandlerEntity.java#L126 and https://github.com/GTNewHorizons/ThaumicHorizons/blob/4bf23df25b8edc57a8d11526bd843cd5f101e831/src/main/java/com/kentington/thaumichorizons/common/lib/EventHandlerEntity.java#L208 because perhaps both are triggering.

**Comment by bombcar** [comment]
ok I added some really stupid debug lines, got to 200 warp (100 perm, 50, 50) and than used a tumor and got: 

![image](https://user-images.githubusercontent.com/533931/143084470-dc26ec6d-6097-4507-8186-ad2e3645996b.png)

so both the first and second "sections" triggered.

```java
if (warpPermanent > capacity) {
    Thaumcraft.proxy.getPlayerKnowledge().addWarpPerm(entity.getCommandSenderName(), -capacity);
    final EntityInfusionProperties entityInfusionProperties = (EntityInfusionProperties)entity.getExtendedProperties("CreatureInfusion");
    entityInfusionProperties.tumorWarpPermanent += capacity;
    capacity = 0;
    entity.addChatMessage(new ChatComponentText(EnumChatFormatting.ITALIC + "" + EnumChatFormatting.GRAY  + " ate warp in first group"));
}
else {
    capacity -= warpPermanent;
    Thaumcraft.proxy.getPlayerKnowledge().addWarpPerm(entity.getCommandSenderName(), -warpPermanent);
    final EntityInfusionProperties entityInfusionProperties2 = (EntityInfusionProperties)entity.getExtendedProperties("CreatureInfusion");
    entityInfusionProperties2.tumorWarpPermanent += warpPermanent;
    if (warp > capacity) {
        Thaumcraft.proxy.getPlayerKnowledge().addWarpSticky(entity.getCommandSenderName(), -capacity);
        final EntityInfusionProperties entityInfusionProperties3 = (EntityInfusionProperties)entity.getExtendedProperties("CreatureInfusion");
        entityInfusionProperties3.tumorWarp += capacity;
        capacity = 0;
        entity.addChatMessage(new ChatComponentText(EnumChatFormatting.ITALIC + "" + EnumChatFormatting.GRAY  + " ate warp in second group"));
    }
    else {
        capacity -= warp;
        Thaumcraft.proxy.getPlayerKnowledge().addWarpSticky(entity.getCommandSenderName(), -warp);
        final EntityInfusionProperties entityInfusionProperties4 = (EntityInfusionProperties)entity.getExtendedProperties("CreatureInfusion");
        entityInfusionProperties4.tumorWarp += warp;
        if (tempWarp > capacity) {
            Thaumcraft.proxy.getPlayerKnowledge().addWarpTemp(entity.getCommandSenderName(), -capacity);
            final EntityInfusionProperties entityInfusionProperties5 = (EntityInfusionProperties)entity.getExtendedProperties("CreatureInfusion");
            entityInfusionProperties5.tumorWarpTemp += capacity;
            capacity = 0;
            entity.addChatMessage(new ChatComponentText(EnumChatFormatting.ITALIC + "" + EnumChatFormatting.GRAY  + " ate warp in third group"));
        }
        else {
            capacity -= tempWarp;
            Thaumcraft.proxy.getPlayerKnowledge().addWarpTemp(entity.getCommandSenderName(), -tempWarp);
            final EntityInfusionProperties entityInfusionProperties6 = (EntityInfusionProperties)entity.getExtendedProperties("CreatureInfusion");
            entityInfusionProperties6.tumorWarpTemp += tempWarp;
            entity.addChatMessage(new ChatComponentText(EnumChatFormatting.ITALIC + "" + EnumChatFormatting.GRAY  + " ate warp in fourth group"));
        }
    }
}
```
Upon logout and log back in I get "ate warp in third group" and 50 sticky warp disappears.

And do that again and it ate the last 50 temp warp and starts looping until death:

![image](https://user-images.githubusercontent.com/533931/143085049-420d144f-7846-45fa-9076-d4bd876b54c1.png)

**Comment by bombcar** [comment]
Something must be calling `applyInfusions` continually; doesn't seem to be once a tic though, maybe once a second.
