### ISSUE TITLE
wierd voiding/dupe PA/ender conduit

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#7094]
#### Which modpack version are you using?
9.0
#
#### If in multiplayer; On which server does this happen? 
MP (not thermos)
#### What do you suggest instead/what changes do you propose?

![afbeelding](https://user-images.githubusercontent.com/42187820/101993154-ada73e80-3cb8-11eb-9925-09e6bf3eb6f8.png)
this is the setup
input bus filtert to bartworks glass
3 zpm fluid extractor with as input item filter any non bartworks glass
zpm fluid extractor pushes fluids in to ender conduits
5 input hatches with filtert ender consuits 1 for each metal

ae is curently carfting 72 nickle glass
1 iridium glass
and 15 osmium glass

total fluids in system
exactly enough nickle for 72 glass
512L osmium so 18 928L osmium gone or 131.44 ingots worth
75 520 L irdium or  71 632L iridium to much or 497.44 ingots to much
this system was crafting 8K osmium glass over night and made 5K before it stoped working

this is chunck loaded with admin anchores in the overworld and not using thermos
no server restarts should have happend during this time

**Comment by yukieiji** [comment]
Fluid voiding seems to be the same issue as this. #4161

**Comment by boubou19** [comment]
is it still happening in latest version?
