### ISSUE TITLE
Electric implosion compressor duping neutronium blocks

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7096]
#### Which modpack version are you using?
GTNH 2.0.9.4.a.dev
#
#
#### What did you try to do, and what did you expect to happen?
I placed the electric implosion compressor controller and it spawned out of thin air 5 neutronium blocks above it.
#
#### What happened instead? (Attach screenshots if needed)

https://youtu.be/SiAkU-Q_HHM

I did /mt hand on the controller

![image](https://user-images.githubusercontent.com/57050655/102009904-e25bda00-3d3a-11eb-8593-bb183a5251fd.png)

**Comment by boubou19** [comment]
how is this even possible?
