### ISSUE TITLE
Drowning in the air... maybe only after being on ice?

### ISSUE THREAD

**Issue by Mummelpuffin** [GTNewHorizons/GT-New-Horizons-Modpack#7098]
#### Which modpack version are you using?

2.9.4 Nightly

#
#### If in multiplayer; On which server does this happen? 

Not in multiplayer

#### What did you try to do, and what did you expect to happen?

I expected not to drown while standing in the air in the overworld.

#
#### What happened instead? (Attach screenshots if needed)

I was walking over a bunch of ice. For some reason a lot of the water under it was actually flowing. At some point as I was walking across it, I started drowning! In the air! Even after I stepped off of the ice the game was still convinced that I was underwater, at least as far as drowning's concerned.

I'm sorry I don't have more info on what happened here. I had only just started the world. The only other thing I can say about it is that I heard some ice break for some reason.

**Comment by Dream-Master** [comment]
Guess you was hit by an infernal mob which let you drown or somethings.

**Comment by Prometheus0000** [comment]
Infernals with choke can do this
