### ISSUE TITLE
Ore drilling plant don't mine ores

### ISSUE THREAD

**Issue by Oueio** [GTNewHorizons/GT-New-Horizons-Modpack#7100]
#### Which modpack version are you using?
2.0.9.4a
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
Set the ore drilling plant, add energy,mining pipes, drilling fluid, chest for ores
#
#### What happened instead? (Attach screenshots if needed)
Ore drilling plant set pipes to bedrock and then mined only **small emerald ores** (vein was coal/graphite/diamond). Radius - 64 blocks. Also soldering iron change chunk loading, but tooltip say about chunk mode.
#

**Comment by Prometheus0000** [comment]
Are you _sure_ it's 2.0.9.4a? It's supposed to be fixed.

**Comment by repo-alt** [comment]
it was broken just before 9.4a and the fixed version was not packed in

**Comment by repo-alt** [comment]
http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/

**Comment by Prometheus0000** [comment]
I would think something this important would deserve a b version.

**Comment by Oueio** [comment]
So, what i need to do to fix it?

**Comment by Oueio** [comment]
Version exactly 2.0.9.4a

**Comment by repo-alt** [comment]
Just use GT from Jenkins I posted, until the new version will be out

**Comment by Dream-Master** [comment]
i will push a last version before release asap
