### ISSUE TITLE
Bennie - Gene Database not registering

### ISSUE THREAD

**Issue by fabiobuhr** [GTNewHorizons/GT-New-Horizons-Modpack#7102]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Scanning certain >Apiarist DNA Sequence (5158:5)< in Sequencer gives the species genes in Gene Database. However, some of them are not registering. I noticed the bug while scanning bees: Lapis and Certus genes. 
#
#### What happened instead? (Attach screenshots if needed)
After scanning, input in gene database does not occur.
#
#### What do you suggest instead/what changes do you propose?
Fixing the non-registry. The error could be caused by the fact that there are duplicate bees for lapis, certus and most others.

**Comment by Prometheus0000** [comment]
Try again on latest

**Comment by ZorbaHerbalist** [comment]
Issue still exists in 2.1.1.3
