### ISSUE TITLE
Change #297/#1992 quests requirements - wand augements quest unnecessary gate

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/GT-New-Horizons-Modpack#7103]
2.0.9.0 Eta

Quest #1992- for wand augments - is blocked by essentia mirror quest, and requires full essentia mirror to be crafted(enderium, so tungstensteel coils), while augments themselves requires only mirrored glass (energetic alloy, so kanthal coils), so basically after reaching research and being able to craft mirrored glass, you are able to craft wand augments.

I propose to change #297 quest to require mirrored glass to be completed and make the separate quest for essentia mirror, so there is a logical flow between quests, since both essentia mirror and wand augments require mirrored glass, and augments don't require essentia mirrors.

**Comment by Prometheus0000** [comment]
Try not to use # in the issue when listing quest #s as that links to other issues.
