### ISSUE TITLE
Edit Assembly line quest

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#7104]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
private
#

#### What do you suggest instead/what changes do you propose?
Assembly line quest requires you to craft iv busses,iv busses have no sence at all, its just resource waste. they dont have more capacity, What i suggers is changing busses needed to ULV(used for automation) or HV busses

**Comment by Houstonruss** [comment]
Get rid of the bus requirement altogether!
