### ISSUE TITLE
[Suggestion] Add a recipe for the debug maintenance hatch

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7105]
I am tired of placing hundreds of auto-maintenance hatches and place for every one of them some ender io conduits to feed them lubricant cells, steel screws, nano processors and duct tape.

I am willing to pay more for the craft and have a creative/debug maintenance hatch.

**Comment by Prometheus0000** [comment]
Suggest a recipe and tier. Also, when does the auto become viable for comparison?

**Comment by alphaNOVAircraft** [comment]
You can craft the auto maintanance hatch starting LuV, For some things its already viable in Luv (like ass line, cleanroom, megaebf / freezer etc), I startet using it on basically every multiblock in zpm. 
Having nearly the same recipe but maybe with uv / uhv (if you want to maybe even uev) components should be fine. The current one isnt really an issue, it would be only a small qol change and reducing some unnecessary ender chests / conduits etc. 
Imo UV components should be fine

**Comment by Alexdoru** [comment]
I was about to propose a ZPM craft lol, could make it UV also.
![image](https://user-images.githubusercontent.com/57050655/102123144-d4937b00-3e46-11eb-9599-6c5f0da44fdb.png)

The main problem I have with the current auto-maintenance hatch is not the cost of the craft but the time it takes to place them up and wire them with conduits to feed them cheap items.

**Comment by GeicowithaBango** [comment]
very nice suggestion imo. i think everyone would appreciate that

**Comment by Prometheus0000** [comment]
I was thinking 2-3 tiers after you use the auto one, so it isn't obsolete too fast. Assuming other people approve of course.

**Comment by Dream-Master** [comment]
use the advanced variant of the maintenance hatch in the recipe

**Comment by GeicowithaBango** [comment]
i think we can lower the needed materials for the automated maintenance hatch then. those hatches are practically speaking not used at all and no one gonna bother crafting them -besides to make the debug one- so respecting that those should gets used by players I pledge to make them cheaper

**Comment by Dream-Master** [comment]
No the recipe is fine.

**Comment by Prometheus0000** [comment]
BTW, did anyone test if they work on non-TT multis?

**Comment by Alexdoru** [comment]
They do work on any multi

**Comment by 0lafe** [comment]
>The main problem I have with the current auto-maintenance hatch is not the cost of the craft but the time it takes to place them up and wire them with conduits to feed them cheap items

Smdh, it's 3 clicks with conduits and a probe

**Comment by Alexdoru** [comment]
> > The main problem I have with the current auto-maintenance hatch is not the cost of the craft but the time it takes to place them up and wire them with conduits to feed them cheap items
> 
> Smdh, it's 3 clicks with conduits and a probe

I use conduits and probe, and you still have to open it and manually put one lubricant cell, one nano, one duct tape and one steel screw, otherwise you end up with shit like this : 

![image](https://user-images.githubusercontent.com/57050655/102143627-80978f00-3e64-11eb-9fa6-c66e7b91b7f7.png)

**Comment by Ethryan** [comment]
I would love to have the Ender IO match amount function from 1.12.2, just so i don't have to fill all the slots with 64 of each item.

**Comment by 0lafe** [comment]
In all fairness, you could use sfm and add them to a variable, and dupe managers. You could use AE, I think you can copy paste interfaces? You could use ExU rationing pipes. You could automate your multi construction and have an oc bot or something do the item placement for you. 

But I guess a recipe 1 tier up is fine instead :(

**Comment by GTNH-Colen** [comment]
I've really wanted this added as a recipe for a long time, totally agree that after a point you just don't want to be dealing with it anymore. Some endgame users have 100s of multiblocks and this would be a serious QoL improvement given the actual running cost for them is negligible anyways just a method of irritating users.

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/103149423-52089680-4737-11eb-9c79-8710d9ccbe73.png)
![image](https://user-images.githubusercontent.com/8517039/103150408-e11aac00-4741-11eb-95f2-3412a468c272.png)
Thoughts? Also, I think the auto should maybe go down 1 tier if we add a recipe for this. I'm not sure if there's a way to change what materials it uses just for GTNH though.

**Comment by alphaNOVAircraft** [comment]
The computation required seems quite high for me. 
And i would pref that it doesnt need 256 B of Lubricant. I think most ppl build their ass lines not wit UV Input Hatches. 
600 s might be a bit high, you need a looooot of hatches, and if you dont get 10 or more ass lines working on UEV+ level that recipe is kinda slow (you also need to take into account the components that take ass line time as well)

**Comment by Prometheus0000** [comment]
> The computation required seems quite high for me.

The idea is that the computation is high (and long), but the A is low. And remember you only need to do it once.

> And i would pref that it doesnt need 256 B of Lubricant. I think most ppl build their ass lines not wit UV Input Hatches.

But where will the lubricant to repair the multi come from? Or at least that's the idea.

> 600 s might be a bit high, you need a looooot of hatches, and if you dont get 10 or more ass lines working on UEV+ level that recipe is kinda slow (you also need to take into account the components that take ass line time as well)

I'll see what other people say, but it means _no more maintenance for that multi ever_. I think it's worth 10m. Honestly, I think it'd be worth a couple hours, or a day even. And it's not like you can't speed it up.

**Comment by GeicowithaBango** [comment]
i think the UV energy orb might be too expansive for a maintenance hatch.

**Comment by alphaNOVAircraft** [comment]
> > The computation required seems quite high for me.
> 
> The idea is that the computation is high (and long), but the A is low. And remember you only need to do it once.
> 
Ture, but requiring 512 c/s is the part that uses most of the energy in that recipe. And you would have to upgade most ppls quantum pcs (thing 4 racks is the usuals UVish build. That would be fine if you want to make it harder to get. 

> > And i would pref that it doesnt need 256 B of Lubricant. I think most ppl build their ass lines not wit UV Input Hatches.
> 
> But where will the lubricant to repair the multi come from? Or at least that's the idea.
> 
Use a stack of lubricant cells in the recipe?! Can stay that way, upgrading fluid hathes isnt not possible, just wanted to point it out. 

> > 600 s might be a bit high, you need a looooot of hatches, and if you dont get 10 or more ass lines working on UEV+ level that recipe is kinda slow (you also need to take into account the components that take ass line time as well)
> 
> I'll see what other people say, but it means _no more maintenance for that multi ever_. I think it's worth 10m. Honestly, I think it'd be worth a couple hours, or a day even. And it's not like you can't speed it up.

You can speed it up (thats why i mentioned UEV+ ass lines. I dont think its worth a couple of hours, It takes me less then 20 sec to set up a auto maint with a conveyer and a ender chest. Its just unecessary and laggy. There is no expense at all in doing so, but that recipe is quite expensive for basically just cancel out that time and being better on performance. The rep materials are free anyways. 

> i think the UV energy orb might be too expansive for a maintenance hatch.

If it is one of those it definitly is. For a normal UHV - UEV base you need more energy clusters then to build a really ultimate battery. I dont think those should be part of anything you craft a lot. That nested crafting in those is terrible, and it shouldnt be required to spam production for them.

**Comment by Alexdoru** [comment]
Only thing that bothers me in this recipe is the UV energy cluster, keep in mind that to craft a really ultimate battery you need 64 of those and high end players will probably craft hundreds of those maintenance hatches. I think the cluster makes it really expensive.

The lubricant is not a problem, can always have a larger input hatch and use larger flasks to automate it

**Comment by GTNH-Colen** [comment]
I would agree, take out the UV energy orb. 256kL of lubricant is a lot but manageable, just will be a bit of a pain for those with SFM I'd imagine (Having to switch out input buses).

**Comment by GeicowithaBango** [comment]
Perhaps the time has come to make a T2 lubricant lmao D:

**Comment by alphaNOVAircraft** [comment]
Tbh i dont really see a point why it should be that expensive. Its mainly a qol change with a bit of a performance gain. Nothing gamebrakingly op. 

Just researching that thing is around 3 times as expensive as a void miner 3. 
With 512 c/s requirement it takes you 12 hours (assuming 20 tps).  Seems kinda overkill for me. 

Im would still use it with the current recipe, but i though we wanted a recipe to be 2 tiers above the auto, that would put it early / mid UV. 
And thats not the case with that recipe, noone who just reached UV will consider this thing. Im in UHV / start of UEV but still couldnt afford switching all my multis to them, with the auto maint beeing free. 

Really depends if it is supposed to be that late. Id presonally pref if it would be aviable in uv at a reasonable price for uv players.

**Comment by Prometheus0000** [comment]
BTW, you guys seem to be down on research costs, but personally, I think they should go way, way, up. Why? Because you never even have to use a full quantum computer, much less chain them, even to research the farthest stuff. I think you should be required to do it at some point. Though maybe not at the start of UV/for this one, haha.

**Comment by alphaNOVAircraft** [comment]
I would like to see recipes using massive quantum computers, but that one just doesnt seem to be the right one to start with imo. Computation wise that is 100x lower then stargate stuff xD

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/103160955-3dfd7d00-47a9-11eb-94e5-82dddca0b717.png)
![image](https://user-images.githubusercontent.com/8517039/103160959-45248b00-47a9-11eb-8720-ed8cf526b92c.png)
That's the LuV lapo

Also, keep in mind that this is _optional_.

**Comment by alphaNOVAircraft** [comment]
Im really sorry to be picky about the fluids again, but i think having the same fluid in three slots is worse for automation sometimes (cause you need to split up the same item). But otherwise it looks good. (Some automatisation approches need you to rename the cells / flasks before inserting, which is kinda painful to do)

**Comment by Alexdoru** [comment]
Yes please do not put the same fluid in three different slots, it's harder for automation. And I assume most people have HV input hatches so now they would need to replace 3 hatches per assline whereas with the previous recipe it was 1 input hatch per assline.

**Comment by Prometheus0000** [comment]
So you're saying we shouldn't encourage players to make hatches past HV? That seems weirder to me. The reason the other recipes don't have as much is because they're almost all molten, so 144/1000. Otherwise the 256000L one would only be 36864L.

**Comment by Alexdoru** [comment]
I am saying that with recipe one you need to have one UV input hatch, whereas wich recipe 2 you need 3 EV input hatch and it's harder to automate the fact that you need the same fluid in three different hatches. 

With recipe one you actually craft a higher tier hatch.

**Comment by Prometheus0000** [comment]
If I change it back to 1x256 you're going to complain again is what I'm saying. Yet apparently you need hundreds of the item, but can't be bothered to make a higher tier hatch? What's up with that?

**Comment by Prometheus0000** [comment]
Actually maybe I'm combining different people's comments in my head.

**Comment by botn365** [comment]
computation seems stil to high imo its not a void miner your making here make it should be 1 to 2M
i dont see why it needs so mutch tape make it like 
1 stack tape and add a stack of neutronium screws
i dont like the pump and conveyors we arent transfering milions of liters and items were maintining macjhines the arms are enough

**Comment by LewisSaber** [comment]
The recipe atm looks very stupid, machines break not that often and i dont see any point on spending so much resources, why not to make it just 1 auto maintenance hatch + 128b lubricant + 128 hv circuit +128 tape + 2 zpm robo arms or 1 Uv
