### ISSUE TITLE
 [Suggestion] Add a Pipeline-Pipe for long distance fluid transportation

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#7106]
Add a Pipeline-Pipe for long distance fluid transportation which not need to chanckloaded and have less lag

**Comment by richardhendricks** [comment]
Heya old friends. Just saw this and had some thoughts.

Is this a big issue?

For implementation, it seems like an "input pipe" and an "output pipe" would work, with the bottom side requiring bedrock.  This way the "pipeline" can be in the bedrock 'invisible' to players.

Then you assign the output pipe a channel number (based on dim, and XYZ location, and a little bit random/unique based on the player).
 
Then you put that number in the input pipe, and it calculates how far it has to go, and then requests drilling pipe + pipe tier pipe to make the connection (these resources would be "lost" underground if the player decides to move, imo.). It could be 1 pipe == 1 block, or it could be discounted if you want people to use it.

During the input pipe tick, it checks to see if the destination location is chunk-loaded. If not, it does nothing. If it is, it tries to push fluid into the output pipe.

Power would be required, with tier-appropriate values. 

Tiering of the intakes/exit pipes allows for setting distances the pipe will work. 5 chunks/tier sounds pretty reasonable, starting at HV.

Very high tier pipes could even be cross-dim, with appropriate build requirements.

Would this only be for fluid pipes, or would item pipes also be allowed?

Happy to see GTNH is still evolving!

**Comment by ChemEng227** [comment]
so why not use Ender Tanks?

**Comment by GTNH-Afx237v7** [comment]
The implementation that mitch is working on is meant to be early tier, whereas ender tanks are IV level.

**Comment by mitchej123** [comment]
Also it's being implemented for items, fluids, and power.   No need to iterate over every pipe/wire over long distances Every. Single. Tick.   This will optimize long distance transmission without resorting to teleportation.
