### ISSUE TITLE
Impact merge

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#7107]
#### Which modpack version are you using?
2.0.9.5

At the moment, impact the modpack has a lot of cool features we could benefit from. All their multis seem like they'd have a home here. The singleblock replacements seen much better than GT++ in every way, and even let us customize them iirc. Their parallel mechanism seems awesome if we can also take their GC Integration for it. 

They have LP, so if we wanted to add that, we could probably use those recipes. Their naq proc seems much much better than anything we have. Their nq based machines also seem sick. 

Lots of new multis for things like molten alloys, and cooling them. Seems like the abs but better. The pyro oven is much cooler, but their recipes in it might be weird for us. The sawmill seems dope too. 

Some of their lategame stuff also seems cool, but I don't have enough experience to really comment on it.

**Comment by 4gname** [comment]
I do not allow my code to be used while GT++ is installed on GTNH. Sorry

**Comment by 0lafe** [comment]
Then step one is to remove GT++, step two, add all these cool features. Maybe bundle them into a mod called GT+++ or something lol

**Comment by Spartak1997** [comment]
But all stuff can realise in GTNHCore or some MultiblockModule

**Comment by Dream-Master** [comment]
@4gname who said we have Gt++ in the pack ?

**Comment by 4gname** [comment]
> @4gname who said we have Gt++ in the pack ?

hehe

**Comment by Dream-Master** [comment]
I am 2 clicks away ^^

**Comment by GlodBlock** [comment]
I suggest to remove 0lafe😅

**Comment by Ethryan** [comment]
You don't remove 0lafe, if you try he will nerf you into oblivion ^^.

**Comment by Dream-Master** [comment]
0lafe++   or 0lafe-- ?

**Comment by GlodBlock** [comment]
Add impact is a good idea, while remove gtpp is a terrible idea.
If you remove gtpp, my current save will be destroyed because my gtpp machine will disappear. You shouldn't do that unless the solution is found.

**Comment by dimondmine2** [comment]
I agree with removing GT++ in favor of Impact. Though GlodBlock has a point in that users should receive ample notice before GT++ is removed so they can adjust their setups accordingly. Not saying that wouldn't have been done, but emphasizing it's importance.

**Comment by quedral** [comment]
I am pretty sure that removing gt++ from pack will cause world corruption for older saves. You have to start from the scratch. It is a big decision since it would mean it will be the last version for a lot of people before removal of the mod.

**Comment by 4gname** [comment]
> I am pretty sure that removing gt++ from pack will cause world corruption for older saves. You have to start from the scratch. It is a big decision since it would mean it will be the last version for a lot of people before removal of the mod.

What evidence will there be?

**Comment by GlodBlock** [comment]
> > I am pretty sure that removing gt++ from pack will cause world corruption for older saves. You have to start from the scratch. It is a big decision since it would mean it will be the last version for a lot of people before removal of the mod.
> 
> What evidence will there be?

The save won't corrupt without gtpp, but the blocks and items of gtpp will disappear (no effect for those don't use gtpp). The best solution i can come up with is to release a transition version of impact for us to replace our gtpp machines into impact ones.
I don't know why everyone have prejudices on alk and his mod, but could you

**Comment by GTNH-Colen** [comment]
A transition period is absolutely essential, peoples saves will be thrown into chaos without one as half their bases will simply vanish overnight leaving them with no way to recover or rebuild. It will be painful but getting away from GT++ in the long run is worth it, it's a huge part of the pack we have no control over and that's just simply unacceptable. From a pack creation standpoint we have to have the ability to curate content in the way we need it and Alk has proven they are completely unwilling to allow us to do this.

**Comment by 4gname** [comment]
of course there will be a transfer version, this is not even discussed

**Comment by iouter** [comment]
you can add other mods, but gt++ should not be deleted, at most castration it

**Comment by ChemEng227** [comment]
Is there any replacement for Vulcan and MB assembly machine in impact?

**Comment by icha-senpai** [comment]
soo after reading this post about impact being merged...should I start a playthrough or wait?

**Comment by Dream-Master** [comment]
this will happend not yet. It's planed for a version after the next release. So do your playthrough 😀
