### ISSUE TITLE
Gallium Arsenide quest Describes Incorrect Sphalerite Height.

### ISSUE THREAD

**Issue by dimondmine2** [GTNewHorizons/GT-New-Horizons-Modpack#7108]
#### Which modpack version are you using?
1.7.10-2.0.9.4a-dev
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Expected sphalerite height to be described properly in questbook.
#
#### What happened instead? (Attach screenshots if needed)
Sphalerite height is incorrect in questbook.
#
![image](https://user-images.githubusercontent.com/75643342/102158811-458b6080-3e50-11eb-8472-2f2c0bf5937d.png)

#### What do you suggest instead/what changes do you propose?
Change questbook text to describe sphalerite height as it currently exists. Also, please state sphalerite as the name of the zinc ore and state that it is found in sulfur veins.

**Comment by Prometheus0000** [comment]
Both zinc and sphalerite exist, and both can be used to get gallium.
