### ISSUE TITLE
questbook recommends you centrifuge stibnite dust, but it's better to smelt it

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7109]
#### Which modpack version are you using?
2.0.9.0

#
#### What do you suggest instead/what changes do you propose?
Just change the Antimony quest to say that the most efficient way to get antimony is to smelt stibnite dust.

**Comment by dimondmine2** [comment]
The quest calls for 32 animony dust, so the quest requirement should either change to antimony bars or suggest that the player smelt stibnite into antimony bars and macerate those
