### ISSUE TITLE
[Question/Suggestion] About Tec Tec's Active transformer

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7111]
Considering you can't bend optic cables the only way to distribute the power with optical power grids is to use power transformer. 
Question is : does the power transformer loose power when transfering power of the same voltage from input to output ?

Suggestion : 
- make the power transformer apply the x% loss only when it is transforming
- make it without loss when it is just transferring power of the same voltage.

Bonus suggestion :
- when transforming let the loss be x^n % with n being the difference of voltage on the input and output

**Comment by Prometheus0000** [comment]
> Considering you can't bend optic cables the only way to distribute the power with optical power grids is to use power transformer.

Untrue, you can transform laser to normal and back to turn at (possibly?) horrendous cost. Also, I assume you mean the **active** transformer? Also, you can probably I/O any TT machine with power pass too, since that's what it's doing.

> Question is : does the power transformer loose power when transfering power of the same voltage from input to output ?

Does it? Why did you make a ticket to ask a question?

> make the power transformer apply the x% loss only when it is transforming

I'm not sure this is possible codewise. Maybe if you compared the hatches and confirmed they were the same tier?

**Comment by Alexdoru** [comment]
The Active transformer of course.

Bot told me they do loose power when they are just passing power.

**Comment by alphaNOVAircraft** [comment]
Yeah sadly they do, which is really sad considering that 0.7% is quite high when you use it for your main power lines (and thats definitly the most use case for them). 
Chaning it to only applie on transforming power would be epic (maybe just calcualte it on normal hatches not on laser hatches?!)

**Comment by Prometheus0000** [comment]
I think it would be best to ask @basdxz how reasonable this would be.

**Comment by botn365** [comment]
https://github.com/Technus/TecTech/commit/6c9ec7b46509a7142edb94c15f9beac5a6153d82
it got changed to 0.004% loss wich is way way better

**Comment by Prometheus0000** [comment]
Is that all of them or just the lasers? It looks like all TT hatches/dynamos, and not the normal ones. I'm not sure if it counts laser ones.

**Comment by botn365** [comment]
i think all of them

**Comment by Alexdoru** [comment]
> Untrue, you can transform laser to normal and back to turn at (possibly?) horrendous cost. Also, I assume you mean the **active** transformer? Also, you can probably I/O any TT machine with power pass too, since that's what it's doing.


If you are talking about the laser power converter from bratworks it's EV to ZPm voltage lol, it's not good enough for 2 million amps UEV transfer

**Comment by Prometheus0000** [comment]
Are you...using 2M A?

**Comment by Alexdoru** [comment]
That's not the point, the point is : if you want to transfer a lot of power you have to use optic cables & the active transformer and it souldn't have loss if it is just acting as a power relay and not transforming it. Most likely you will have a lot of active transformer connected in series and the loss adds up and ends up being a lot.

To fi the issue the last update changed the power loss from 0.79% ? to 0.004%, wich is basically nothing now.
In my mind the idea of having power loss was good but it should take place only when it is transforming power and not just transferring it.

**Comment by Prometheus0000** [comment]
Maybe you should talk to bass or make an issue on the TT repo then? The loss seems pretty negligible now. Or are you saying this can be closed?

**Comment by basdxz** [comment]
I don't see an issue with it, the power loss was reduced since the main use of it was as you had found, distributing power through optical power grids.
