### ISSUE TITLE
quests on bees in "coins coins" does not update

### ISSUE THREAD

**Issue by Alsarus** [GTNewHorizons/GT-New-Horizons-Modpack#7114]
#### Which modpack version are you using?
2090 qf4
#
#### If in multiplayer; On which server does this happen? 
local server
#
#### What did you try to do, and what did you expect to happen?
try buy some bees in "coins coins". Fistly i buy, but next time quest's does not updates
#
#### What happened instead? (Attach screenshots if needed)
http://puu.sh/GY2gT/8c626da162.png
#
#### What do you suggest instead/what changes do you propose?
fix quests

**Comment by Prometheus0000** [comment]
@SKProCH Are you sure this is a problem with BQ3? If it's just the quest, it should have the quest change label instead.

Also, if this is the existing problem, it's a duplicate, did you investigate?

**Comment by SKProCH** [comment]
All this happened due to the fact that Edit mode was enabled.
