### ISSUE TITLE
[RFC] Gendustry

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#7117]
#### Which modpack version are you using?
2/0/9/0
#
#### If in multiplayer; On which server does this happen? 
private
#
#### What did you try to do, and what did you expect to happen?
Used pristine lutetium bee in imprinter
#
#### What happened instead? (Attach screenshots if needed)
It died
#
#### What do you suggest instead/what changes do you propose?
Remove dying of pristine bees completly from gendustry genetic imprinter
Also Remove/decrease degrade chance of gendustry mutatron

**Comment by boubou19** [comment]
The mutatron basically make the breeding instantly. by reaching gendustry, you should have a lot of pristine rocky bees/princesses. Imo this is a non issue, as gendustry is basically trivializing bees. 

What is the chance of dying for a bee anyways?

**Comment by LewisSaber** [comment]
Idk exact but i am sure its not so small, i lost a lot of bees in imprinter already

**Comment by Dream-Master** [comment]
No I  am against to change it. It's not a lossless copy past bee process. Some times it fails as always in rl.

**Comment by mitchej123** [comment]
Gendustry is gated pretty late.  Seems kinda stupid it fails that much at LuV+.

**Comment by Ethryan** [comment]
Here are the chances of death for the different machines:

Mutatron:
Degrade: 30 %
Death of Ignoble: 80 %

Advanced Mutatron:
Degrade: 10 %
Death of Ignoble: 50 %

Imprinter:
Death of Pristine: 20 %
Death of Ignoble: 40 %

Theese numbers look reasonable to me.

**Comment by boubou19** [comment]
i thought you could pristine bees as well?anyways that is totally reasonable to me

**Comment by Ethryan** [comment]
That feature is disabled i think: [Link](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/gendustry/overrides/tuning.cfg#L129)

**Comment by LewisSaber** [comment]
Can we change imprinter pristine bee chance death to 10%

**Comment by bedrill64** [comment]
According to all of the wiki's I check, imprinter kills only ignoble bees (see below), is this config option we've got in GTNH that pristine are also killed?

> The Genetic Imprinter is a machine added by Gendustry which replaces traits of a species using a Genetic Template. It requires 80,000 MJ per operation in addition to a Genetics Labware. The Genetic Template will not be consumed. It will replace all of the traits that are present in the template at once. Ignoble Stock have a chance of not surviving the process.

**Comment by boubou19** [comment]
well it makes more sense to kill both pristine and ignoble bees, as it still add a bit of a challenge to get imprinted pristine bees.

**Comment by basdxz** [comment]
Isn't this standard behavior as-is? Gendustry adds options for easing your work of getting top-tier bees and is already the easiest way to go about it, why should it be further see further buffs?
