### ISSUE TITLE
Add assembler recipes for: Bed, Saddle, Clock

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/GT-New-Horizons-Modpack#7119]
Eta, 2.0.9.0

As in the title, add assembler recipes for Bed, Saddle and Clock. Only way to obtain essentia aspects of Desidia, Luxuria and Tempus are these items (not counting shards and boss trophies). Change will make it less tedious  to grind, especially desidia aspect, since it is needed for impure tears crafting, at this moment you have to craft these manually which is simply annoying.

Proposed recipes:

Bed: 3 carpets, 3 wood planks
Saddle: 1 tanned leather, 4 leather, 2 iron rings
Clock: Redstone Comparator, gold plate and 2 gold rings.

Voltage LV, crafting time 10 seconds.

**Comment by bedrill64** [comment]
Actually, as I'm checking aspect list in the GTNH spreadsheet, there are more ways for these, but still, we could use assembler recipes for these items just as QoL.

**Comment by Prometheus0000** [comment]
I don't understand, why can't you just craft them with the normal recipe in a molecular assembler? The saddle doesn't even have a tool in the recipe if it's that.
