### ISSUE TITLE
Honeycomb Chocolate Bar is uncraftable

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7120]
#### Which modpack version are you using?
2.1,0,0-pre

Honeycomb Chocolate Bar uses Pams's Honeycombs, which are inaccessible

(Also they use oredictionary "materialHoneyComb", while Forestry bees use "beeComb", but that is probably irrelevant since they are disabled)

**Comment by bedrill64** [comment]
It is craftable, these honeycombs can be obtained from nether hives, from destroying filled honeycomb blocks. See the image below, already eaten one in 2.0.9.0

![image](https://user-images.githubusercontent.com/9555787/102488712-c9219900-406c-11eb-9240-a5d28649d3f4.png)

**Comment by Prometheus0000** [comment]
Is there a reason the beehive generation is turned off, but you can still get apiaries?
