### ISSUE TITLE
Only getting trash drops from Tier 5 lootbags created with the 3 Tier 4 > Tier 5 quest in reward area

### ISSUE THREAD

**Issue by SteelGiant87** [GTNewHorizons/GT-New-Horizons-Modpack#7121]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Single player
#
#### What did you try to do, and what did you expect to happen?
Opened 5 Tier 5 lootbags created using the Reward Area quest, combining 15 Tier 4 lootbags, Expected to recieve useful Tier 5 items.
#
#### What happened instead? (Attach screenshots if needed)
Only received trash rewards (bowls, string, bonemeal etc) from all Tier 5 lootbags. 

Tried reloading world from a backup and trying again: only received trash items, although a different set of trash items. Essentially impossible for this to be a statistical fluke.

This doesn't happen with Tier 5 lootbags obtained from Tier 5 quests, 

This has probably happened to me before (although wasn't paying particular attention) with lower tier lootbags from the Reward Area, so this problem may not be exclusive to Tier 5 lootbags from the reward area.
#
#### What do you suggest instead/what changes do you propose?
Bags obtained from reward area should drop non-trash items from their respective tier.

**Comment by alphaNOVAircraft** [comment]
That sounds pretty awkward to me. Tbh i think you got unlucky. Afaik there is only one type of t5 lootbag so cant really see how that would work

**Comment by Prometheus0000** [comment]
You should Fortune them if you want decent stuff. There's no difference how you get the loot bag.
