### ISSUE TITLE
Got a crashbug (1.1.0.0-pre)

### ISSUE THREAD

**Issue by Ethryan** [GTNewHorizons/GT-New-Horizons-Modpack#7122]
#### Which modpack version are you using?
1.1.0.0-pre
#
#### If in multiplayer; On which server does this happen? 
My own
#
#### What did you try to do, and what did you expect to happen?
I tried to look up the recipe for the fluid Polyvinylchloride
#
#### What happened instead? (Attach screenshots if needed)
Crashing so hard it quit the game.

[crash-2020-12-17_18.50.53-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5711245/crash-2020-12-17_18.50.53-client.txt)
#
#### What do you suggest instead/what changes do you propose?
Bart should maybe fix it.

**Comment by Dream-Master** [comment]
we dont update bartworks so must be an old issue ?

**Comment by Prometheus0000** [comment]
It's GT not BW

**Comment by repo-alt** [comment]
Looks like BW to me, wdym?

**Comment by bartimaeusnek** [comment]
i pushed a quickfix. this will now dispay an error item instead of crashing... hopefully.
