### ISSUE TITLE
Shutter graphics on pipes are backwards on the bottom face

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7124]
#### Which modpack version are you using?
2.0.9.0

#
#### What did you try to do, and what did you expect to happen?
I was looking at some pipes from underneath and saw it looked like a shutter was pointed the wrong way, then eventually figured out it was just a graphical glitch.
#
#### What happened instead? (Attach screenshots if needed)
![2020-12-17_19 56 00](https://user-images.githubusercontent.com/3614140/102561190-0ce2c580-40a2-11eb-8716-b393e8da88ce.png)
Here, the shutter is activated on the left side of the pipe, but shows up on the right side on the bottom face.
#
#### What do you suggest instead/what changes do you propose?
It's just graphical but a correction would be nice anyway.

**Comment by Prometheus0000** [comment]
Did you fix this already @leagris ?

**Comment by leagris** [comment]
> Did you fix this already @leagris ?

This is exactly part of the fixes in this commit:
https://github.com/GTNewHorizons/GT5-Unofficial/commit/b3789aebb681711a91ec51cdd390a47dc36282dd
