### ISSUE TITLE
Shutters are invisible on potin fluid pipes

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7125]
#### Which modpack version are you using?
2.0.9.0

#
#### What do you suggest instead/what changes do you propose?
Please make them visible like on other pipe materials.

**Comment by draknyte1** [comment]
Known. 
visual issue, won’t fix.

**Comment by Prometheus0000** [comment]
Use search

**Comment by McFrugal** [comment]
I did use search.  I searched for "potin" and for "shutter", and got no relevant results in issues.

**Comment by Prometheus0000** [comment]
Discord

**Comment by leagris** [comment]
> Discord

This is not really appropriate to rely on Discord history search to search about issues mentions. Hopefully now this issue now can be tracked down here for ppl facing the same invisible shutter on potin fluid pipes issue.

**Comment by Prometheus0000** [comment]
It's because the thing about alk retaining backward compat has been discussed a bajillion times and I didn't want to type it out again or know where to link about it. As in, it's not just this pipe.

**Comment by draknyte1** [comment]
As stated 2yr ago (I can’t for the life of me find anything more recent), won’t be fixed. 

https://github.com/alkcorp/GTplusplus/issues/396
