### ISSUE TITLE
Crashed while mining small ores

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7126]
#### Which modpack version are you using?
2.0.9.0
#
#### What did you try to do, and what did you expect to happen?
I mined a small silver and small yellow limonite one after the other (they were adjacent) and the game crashed.  Upon relaunching the game, I had a crushed silver ore in my miner's backpack but no yellow limonite.  I restored from a backup and went to mine the ores again to try to reproduce it, but didn't crash.  Here's the crash log:
[crash-2020-12-17_23.39.25-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5713930/crash-2020-12-17_23.39.25-server.txt)

**Comment by McFrugal** [comment]
I've crashed two more times:
[crash-2021-01-11_00.47.39-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5799798/crash-2021-01-11_00.47.39-server.txt)
[crash-2021-01-11_23.27.57-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5799799/crash-2021-01-11_23.27.57-server.txt)
The small ore types were Chalcopyrite for the first one, and... coal for the second one I think?
Possibly relevant information is that my pickaxe has lapis on it, and a green slime rod.  I feel like this is most likely due to the tinkers construct lapis mod, maybe the Lucky part of it instead of the Fortune part?

**Comment by Prometheus0000** [comment]
Or maybe some kind of attempt at slime creation interaction?

**Comment by Prunebane** [comment]
Can confirm, had it happen with two different small ores. Don't remember the first one, but the second one was definitely Small Chalcopyrite.
The first I accounted to me having the world running for too long, but the second happened not too long after starting.
I vaguely remember that both times happened during mining the main ore vein, and finding a small ore inside; I'll have to double-check that, see how it works. Might play around in creative.

Happened in Technic installation, 2.1.0.0, using a basic wood-wood-flint pickaxe, so I wanna say the pickaxe doesn't have an effect

[crash-2021-01-23_17.25.01-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5862435/crash-2021-01-23_17.25.01-server.txt)
[crash-2021-01-24_10.09.49-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5862436/crash-2021-01-24_10.09.49-server.txt)

**Comment by YannickMG** [comment]
I reproduced this crash today with with what I think was a Small Cassiterite Ore (can't guarantee) as well as the regular flint pickaxe as well.

[crash-2021-03-22_23.59.09-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6186844/crash-2021-03-22_23.59.09-server.txt)

**Comment by Prometheus0000** [comment]
On what version though? And I thought this was fixed some time ago? As the linked ticket says

**Comment by YannickMG** [comment]
Version  2.1.0.0QF1-1.7.10. I mistakenly assumed the version 2.0.11 mentioned in the other post referred to the modpack rather than the individual mod, so I'll update NEI to that version as recommended. Apologies for the misunderstanding.
