### ISSUE TITLE
Smeltery instakills everything

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7127]
#### Which modpack version are you using?
2.1.0.0-pre
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
This change has made it so entities die instantly from smeltery damage: https://github.com/GTNewHorizons/TinkersConstruct/pull/21
This breaks the ability to have a supply of ender pearls using a regen enderman, which is branded as intentional by the quest book.

Not had anyone test yet, but I suspect that this also means the smeltery will instakill players.

Code which does this:
https://github.com/GTNewHorizons/TinkersConstruct/blob/5d055ec8dc5577b3ebd8405418cf3cf3865eb2ad/src/main/java/tconstruct/smeltery/logic/SmelteryLogic.java#L406
#
#### What do you suggest instead/what changes do you propose?
Revert this behaviour.

**Comment by Ethryan** [comment]
Ooh, it instakills, i can certify that one.

**Comment by KiloJoel** [comment]
> 
> 
> Ooh, it instakills, i can certify that one.

Instakills players?

**Comment by repo-alt** [comment]
everything

**Comment by repo-alt** [comment]
It is also the reason of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7039

**Comment by Dream-Master** [comment]
Anyways the enderman in smelter was cheaty

**Comment by draknyte1** [comment]
> Anyways the enderman in smelter was cheaty

That’s why you put it in the quest book then? Advocation for what’s good until you nerf it for no reason, not like infinite Enderpearls have much use.. nether roof is about it early game.

**Comment by dvdmandt** [comment]
Well, it instakills almost anything, including players, and the quest book etc recommend doing it as a feature. It's not that cheaty, you still need to catch a regen enderman and get it into the smeltery. I propose we revert the instakill behavior for this release and figure out a better way to rebalance it, if a rebalance is even needed (I think it was fine personally).

**Comment by alphaNOVAircraft** [comment]
> Anyways the enderman in smelter was cheaty

Well now the only thing that is different is that you force players to use an ender man spawner (which isnt that hard to get either, but probably way more laggy. Not really nerfing anything just making it more laggy seems terible to me

**Comment by Dream-Master** [comment]
I just said that it is cheaty not that we not fix it ;-)  What commit broke it ?

**Comment by dvdmandt** [comment]
One with lots of other things as well, so it's easier to make a fix instead of reverting. I'll get on it in an hour or so.

**Comment by KiloJoel** [comment]
> 
> 
> I just said that it is cheaty not that we not fix it ;-) What commit broke it ?

was this
https://github.com/GTNewHorizons/TinkersConstruct/commit/6bd68f13b1eafa4d6ea656b495ce5c440ada1138

**Comment by interestingusernam3** [comment]
>Anyways the enderman in smelter was cheaty

So what are we supposed to do on the officials? Build super laggy enderman mob farms?

**Comment by leagris** [comment]
> > Anyways the enderman in smelter was cheaty
> 
> So what are we supposed to do on the officials? Build super laggy enderman mob farms and bribe the mods to not get banned for it?

Until this is fixed, IC2 crop Enderbloom is a good alternative to laggy endermen farms.

**Comment by dvdmandt** [comment]
PR: https://github.com/GTNewHorizons/TinkersConstruct/pull/22/commits/7198b6fc5f31ab6d7b62f4fa0317ca25c04f6b19
