### ISSUE TITLE
BQ checkmarks on questlines

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7128]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
After completing entire questline small checkmark appears near questline icon
![image](https://user-images.githubusercontent.com/29033773/102646762-acbd5380-4175-11eb-83fd-310f12cb1796.png)
But some questlines have repeatable quests or quests with excluding requirements such as 
![image](https://user-images.githubusercontent.com/29033773/102646879-db3b2e80-4175-11eb-9b9d-ff6fff12a015.png)
and this preventing questline from completion
#
#### What do you suggest instead/what changes do you propose?
Change logic for checkmark to ignore repeatable, hidden (such as pizza gloves in HV) and excluding quests

**Comment by SKProCH** [comment]
Done
