### ISSUE TITLE
Conveyor pulling from wrong interface

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7129]
#### Which modpack version are you using?
GTNH 2.0.9.5.dev
#

I have this setup with an interface on the top facing the conveyor that is set on importing and an interface on the side. The conveyor is pulling stuff that is in the interface on the side and it shouldn't 

![image](https://user-images.githubusercontent.com/57050655/102654851-9614fd80-4171-11eb-8031-092fe130dc76.png)

**Comment by alphaNOVAircraft** [comment]
Did someone have that issue before in older versions or is it only in the newest dev?

**Comment by Alexdoru** [comment]
I am pretty sure I did this kind of setup before and never had this kind of issue

**Comment by alphaNOVAircraft** [comment]
didnt bot change something in the way conveyer etc interact with stuff? not sure if its in the dev already but maybe its related to it

**Comment by Alexdoru** [comment]
yeah I thought about it as well @botn365

**Comment by alphaNOVAircraft** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/347#issue-521280677

Thats the comit, maybe related cant really tell

**Comment by Dream-Master** [comment]
@botn365 i want to do a release this weekend and i hope this can be fixed before . Thanks

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/376
