### ISSUE TITLE
RFC: MV Advanced boilers overpriced

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7132]
#### Which modpack version are you using?
2.1.0.0-pre
#
#### If in multiplayer; On which server does this happen? 
Zeta

GT++ MV Advanced boiler is grossly overpriced
One large vanilla GT steel boiler produces 24000 L/s of steam
To match it you would need 16 MV advanced boilers, which would cost you ~800 stainless steel (not counting 16 MV circuits, etc)
Steel boiler is dirt cheap in comparison.

**Comment by repo-alt** [comment]
I don't even speak about HV boilers, they are just ridiculous

**Comment by alphaNOVAircraft** [comment]
Single block boiers should have a downside, but thats a bit to bad to be even remotly cosidered for usage

**Comment by Dream-Master** [comment]
REcipe suggestion? change double plates to single plates ? make 2 boilers casis as output

**Comment by repo-alt** [comment]
idk, but really, just look at the numbers, either they have to be a lot cheaper or produce a lot more. I would not even build LV ones if I compared them to the big bronze boiler. The only downside of a big boiler at LV is awkward automation. At MV, when you have Project Red gates, automation becomes trivial, and the _smartness_ of the advanced boilers becomes not that required

**Comment by botn365** [comment]
these boilers produce a whole 56.25eu/t @ 100% eff you would need like a mv recipe to consider them woth it 
sisne we are planing to remove gt++ i would say do nothing about it

**Comment by repo-alt** [comment]
1500 L/s is 75 EU/t at 100%, but where would you get 100% anyway

**Comment by botn365** [comment]
its 2L steam per eu

**Comment by Prometheus0000** [comment]
They should use their tier material for MV and HV, aluminium and stainless. Not stainless and titanium. By the time you get those, you're in the next tier already.

**Comment by Dream-Master** [comment]
If we remove gt++ we need to keep this boilers and move them into gt code or so.

**Comment by draknyte1** [comment]
> If we remove gt++ we need to keep this boilers and move them into gt code or so.

Technically isn’t allowed because copying them requires breaking my license. Also, You *can’t* remove my mod without breaking existing worlds and the user experience of 50%+ of your community (a majority), so have fun there lol. 

If I ever finish my discussions with @mitchej123, there wouldn’t even be a reason to remove the mod. I want to leave MC & modding, so I would like to leave things in his hands for the most part. 

*taps watch*

Time is short in life for us all rn, so why rush?

**Comment by 4gname** [comment]
> > If we remove gt++ we need to keep this boilers and move them into gt code or so.
> 
> Technically isn’t allowed because copying them requires breaking my license. Also, You _can’t_ remove my mod without breaking existing worlds and the user experience of 50%+ of your community (a majority), so have fun there lol.
> 
> If I ever finish my discussions with @mitchej123, there wouldn’t even be a reason to remove the mod. I want to leave MC & modding, so I would like to leave things in his hands for the most part.
> 
> _taps watch_
> 
> Time is short in life for us all rn, so why rush?

Сan always write your own from scratch, an idea cannot be licensed. 🙂

**Comment by draknyte1** [comment]
> > > If we remove gt++ we need to keep this boilers and move them into gt code or so.
> > 
> > 
> > Technically isn’t allowed because copying them requires breaking my license. Also, You _can’t_ remove my mod without breaking existing worlds and the user experience of 50%+ of your community (a majority), so have fun there lol.
> > If I ever finish my discussions with @mitchej123, there wouldn’t even be a reason to remove the mod. I want to leave MC & modding, so I would like to leave things in his hands for the most part.
> > _taps watch_
> > Time is short in life for us all rn, so why rush?
> 
> Сan always write your own from scratch, an idea cannot be licensed. 🙂

No but using identical strings to Properly replace the existing ones violates the license as they’d be identical.
