### ISSUE TITLE
Pam's foods health bonus gone after killing dragon

### ISSUE THREAD

**Issue by fabiobuhr** [GTNewHorizons/GT-New-Horizons-Modpack#7133]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Killing the dragon resulted in disappearance of Pam's Foods heart bonuses
#
#### What happened instead? (Attach screenshots if needed)
I returned to standard 10 hearts, had 27
#
#### What do you suggest instead/what changes do you propose?
Maintaining or completely reseting food consumption, so if needed can be eaten again for hearts. All hearts are gone and all food shows as already eaten.

**Comment by Prometheus0000** [comment]
This is a thing that happens with TC hearts after coming back from the end. Or maybe just changing dims. Try logging out and in again. It should just be visual anyway.

**Comment by fabiobuhr** [comment]
That fixed it, thank you
