### ISSUE TITLE
Biome o plenty license

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#7135]
I revert to the old version in the 2.1.0.0. update because we cant use an own fork of BoP.
It would be very nice if we can add the fixes (we allready add) move in the core mod .

**Comment by repo-alt** [comment]
You mean apply fixes as mixins at runtime?

**Comment by Dream-Master** [comment]
yea whatever works. Since we cant run a own fork we need the changes made allready and all changes in the future add from extern.
