### ISSUE TITLE
Let us craft the TecTech Debug Power Generator!

### ISSUE THREAD

**Issue by basdxz** [GTNewHorizons/GT-New-Horizons-Modpack#7136]
Hello, I have made a list of why we need it.

1. I am biased.
2. More power gen == less tps
3. less tps == slower mobs
4. slower mobs == slower mob farms
5. slower mob farms == fewer enderpearls

thank you for coming to my ted talk

i expect it to be a quest right before healing axe

**Comment by GeicowithaBango** [comment]
what about the debug pollution generator?

**Comment by basdxz** [comment]
Yes that too, however it must be slightly nerfed.

You see, we must lock it into only producing elemental pollution.

That way IC2 crops don't die but players get cancer like they always wanted to

**Comment by Prometheus0000** [comment]
Stargate -> debug gen.

Seriously, what's the point of this ticket?

**Comment by basdxz** [comment]
How is my suggestion silly? This is is a valid request for something that will

1. Improve player retention by reducing the grind
2. Minimize tick-time on official servers allowing more time for mobs
3. gaming
4. basically the best thing since toast sandwiches

**Comment by Prometheus0000** [comment]
This produces unlimited amounts of power for free right? It would never be balanced unless it was at the end, like in AoE, when you craft similar stuff.

**Comment by basdxz** [comment]
Whatever do you mean 'for free'? Nothing is free! Not your time not mine! It takes an entire t-w-e-l-v-e seconds to open the gui to even punch in a value! Do you know how much clay I can gather in that time? Three! Sometimes four! And that's if I have to look for it. Now stop telling me about how it's "free" when you dare include things like "solar" "panels" that allow for fusion energy harvesting at such low tiers

**Comment by 0lafe** [comment]
I'm a concerned citizen who couldn't bare to play this game if you don't make this gen craftible. maybe the quest is locked behind the solar and the kinetic quests. This way only us good players will have access to it 😜

**Comment by basdxz** [comment]
If the almighty Nerf gnome 0lafe agrees then it must be balanced!

**Comment by Ethryan** [comment]
Octuple Compressed Infinity Blocks sounds lika a perfect crafting material for this.

**Comment by interestingusernam3** [comment]
This good suggestion is URGENT, and despite that the incompetent do-nothing DEV TEAM still hasn't added a recipe for the TecTech Debug POWER generator and updated the OFFICIAL SERVERS to include the new update. SHAME!

**Comment by Dream-Master** [comment]
> This good suggestion is URGENT, and despite that the incompetent do-nothing DEV TEAM still hasn't added a recipe for the TecTech Debug POWER generator and updated the OFFICIAL SERVERS to include the new update. SHAME!

feel free to make a pr instead of bulling us. Its x-mas

**Comment by Prometheus0000** [comment]
We could make a recipe to craft the debug power and pollution gens into each other, but that would be pointless, as is this ticket.
