### ISSUE TITLE
[Suggestion] Add parrallel processing to the LCR

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7139]
As we all know with the perfect overclock on the LCR it is really easy to reach the one tick limit, and then if you want to produce more you need to spam more LCR's, it's annoying, doesn't add much to gameplay and destroys server TPS.

We should add parrallelisation to the LCR.
For instance we could make it so that it depends on the tier of the coil. With default cupronickel coil it has no parrallel, with the next coil tier it does 4x parrallel and then x8, x12, x16 and so on.

The parrallel doesn't break balance on the side of power consumption considering it already has perfect overclock, however it requires you to craft less LCR, we could discuss the cost of the block to enable the parrallel e.g use something else than coil blocks.

**Comment by alphaNOVAircraft** [comment]
If added it would be nice to adujust maximum parallel with screwdrivers e.g. to save setups from voiding huge amounts of stuff bcz of smaller hatches

**Comment by LewisSaber** [comment]
> If added it would be nice to adujust maximum parallel with screwdrivers e.g. to save setups from voiding huge amounts of stuff bcz of smaller hatches

Just use lower tier coil?

**Comment by basdxz** [comment]
As of right now the LCR scaling is very off-putting for me, you have a multi-block that scales up entire tiers depending on just the hatch. And then on top of that doesn't make you pay extra in power? If anything it should be changed so the hatch determines nothing but the voltage input tier and the coils determine the true 'tier' of processing/parallels

**Comment by 0lafe** [comment]
Just coil tiering? Imo it should scale max input voltage to the coils and parallels with increasing its size. Make them pay a reasonable associated cost for the benefits. No HV coils? No HV+ hatches. Want more parallel because you're hitting tick limits? Build more.

**Comment by Alexdoru** [comment]
Building more of the same machine is destroying the TPS, could add a special coil to enable the parrallel and make it expensive. Or have a special middle block instead of the coil so you can't actually share it.

 I don't really like the idea of making it biger cause it takes space and imma nuke my base if all my LCR aren't aligned and same size.

**Comment by leagris** [comment]
Is there other alternatives? like:

- Process bigger amount per cycle.
- Process time compute by real time rather than ticking rate

**Comment by Alexdoru** [comment]
Process bigger amount per cycle is extacly what parrallel processing is...

**Comment by ChemEng227** [comment]
Actually I dont think just simply adding parrallel to LCR is a good idea - the balance would be difficult to make.
but maybe we can add something like a MEGA Chemical Reactor?

**Comment by Alexdoru** [comment]
It's not "simply" adding parrallel to the LCR, it's crafting an expensive block to enable the parrallel on one LCR and make it work like N LCR. 
Regarding the balance it's the same cost for energy and we can discuss the cost of the block to enable parrallel and make it more expensive than N LCR.

**Comment by Alexdoru** [comment]
new idea : make it so that once you hit the one tick limit, the new overclock will unlock 4 parrallel processing, the overclock after that will do 16 parrallel processint etc up to 64x parrallel. It will add more "overclocks" to the LCR and reduce the number of LCR needed for certain setups like radon

**Comment by 0lafe** [comment]
What if we try to incentivize other production methods? we have a Rn plasma, we could just adjust the throughput of it to make it a viable alternative to 1t limit LCRs

**Comment by Alexdoru** [comment]
> What if we try to incentivize other production methods? we have a Rn plasma, we could just adjust the throughput of it to make it a viable alternative to 1t limit LCRs

I took the example of Radon but the 1tick limit with LCR applies to a LOT of recipes. circuit boards, platinum processing, basic chemistry like hydrochloric acid, charged certus quartz dust, radon 

I think the TPS would benefit from implementing the parrallel to LCR instead id spaming more multis

**Comment by Glease** [comment]
Apparently there is still an interest in advancing this topic.

**Comment by Sphyix** [comment]
This topic is still really interesting, making a block that costs as much as a 2nd LCR and make it work as a parallel can be a really nice addition.
To make it easy (please don't hate), just make a recursive recipe?
It will be something like 1st block 2x parallel, 2nd block 4x and 3rd block 8x?
I don't think there's really a need to go over 8x parallels on 1tick recipes, that would already reduce a LOT the number of LCRs needed in a base

**Comment by Alexdoru** [comment]
Place N LCR controllers (as an item) in the LCR controller to enable (N+1) parallel processing

**Comment by alphaNOVAircraft** [comment]
I would prefer maybe separate controller tiers that feature different caps of parallels. Just placing a second controller in the gui would make the parallel way cheaper cz you don’t need the Test of the Multi again.

**Comment by bombcar** [comment]
Even if we don't parallel it - I still think allowing higher level coils (and giving a discount similar to the cracker) would be nice.

**Comment by tommmmmmmmm** [comment]
remove perfect oc (i know you guys love nerfs) and make oc work kinda like ebf?

tier up energy tier makes it go 2x speed and 4x power
tier up coil gives space for a 2x parallel for each power tier

i think the perfect oc isn't needed and doesn't fit that well whith the other machines, feels like a2 OP stuff

also you could add coil requirement for some recipes

**Comment by Sphyix** [comment]
> remove perfect oc (i know you guys love nerfs) and make oc work kinda like ebf?
> 
> tier up energy tier makes it go 2x speed and 4x power tier up coil gives space for a 2x parallel for each power tier
> 
> aslo, is now the lcr the only multi that only takes cuni coils?
> 
> and i think the perfect oc isn't needed and doesn't fit that well whith the other machines, feels like a2 OP stuff
> 
> also you could add coil requirement for some recipes

remove perfect oc? no?
if i want shitty overclock but more speed i can already use a PA with a stack of single blocks
no need to make the LCR work like single blocks but worse

gt++ doesn't have perfect overclocking, at high tiers it matches PAs with stacks of machines

**Comment by tommmmmmmmm** [comment]
> remove perfect oc? no? if i want shitty overclock but more speed i can already use a PA with a stack of single blocks no need to make the LCR work like single blocks but worse

it still has no cell requirement...........

**Comment by Glease** [comment]
Probably resolved in the form of Mega LCR in bartworks.
