### ISSUE TITLE
my save file doesn't work

### ISSUE THREAD

**Issue by lughnasadhs2** [GTNewHorizons/GT-New-Horizons-Modpack#7140]
#### Which modpack version are you using?

# 2.0.9.0
#### If in multiplayer; On which server does this happen? 

# solo
#### What did you try to do, and what did you expect to happen?

#just exit game and reboot
#### What happened instead? (Attach screenshots if needed)

#
![image](https://user-images.githubusercontent.com/76432904/102772724-58131600-43cb-11eb-8165-7760071b6989.png)

My world still exists, but it is invisible

**Comment by boubou19** [comment]
make a backup, create a new map, then replace all the content by the content of the backup.

**Comment by Prometheus0000** [comment]
I just restore from backup when that happens. Also, this is not the discord help channel.
