### ISSUE TITLE
RFC Increasing Storage Capacity of Ender Tank

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#7144]
#### What do you suggest instead/what changes do you propose?
In later stages of the game it is required to move huge amounts of fluid.
Currently i use a lot of ender tanks, they are quite fast (you can transfer their capacity each tick, so currently 16000 mb/t) but not fast enough. The only option faster i currently know of are the ME Fluid P2P Tunnels, but those have the downside of only allowing a 1:n Network to be formed, not a n:n like the ender tank. (Edit: They allow n-1:n so no a real downside, my mistake)

Id like to increase the storage volume of the ender tank to be able to transfere liquids at higher rates with it. Its a "quite expensive" tank so i think that wouldnt be unbalanced to increase it to 4 096 000 mb which would allow the usage of even a UEV pump in combination with it, noone should need more than that (not even for a stargate).  

Edit: Since a lot of ppl seem to think 4kB is way to much, how about making it 128 / 256 / 512 Buckets. 

I can submit a pull request to ender storage if noone doesnt want such a change.

**Comment by basdxz** [comment]
what the actual fuck

**Comment by basdxz** [comment]
why would anyone need this

**Comment by basdxz** [comment]
https://github.com/Technus/TecTech/wiki/Ender-Fluid-Link-Cover

when this exists

**Comment by basdxz** [comment]
Hayo

**Comment by alphaNOVAircraft** [comment]
First of all i didnt know that existed / cant find it ingame, and looking at when you added it it seems pretty new as well. 
It also states max extraction rate is 8kmb/t, thats even slower then the current transfer of ender tanks. 
I reached the limit of the ender tank pretty easie (for hydrogen) with just a platinum line running. 

I dont see any downside making the ender fluid tank able to store more fluid, its more expensive then an equivilent super tank.

**Comment by botn365** [comment]
fluid p2p allows for n:n networks sinse outout p2ps can also accept fluids

**Comment by basdxz** [comment]
Oh it's fine. It's something new I've been working on since bot requested it.

For the speed, 8000 mb/t is just the hard-coded non-beta tested rate.

And the storage is mimicking that of existing ender tanks 4

Look at countless other high tier bases and how far they have gotten with conventional ender tanks, upgrading them to such an absurd degree is irresponsible at best and down right moronic at worst.

**Comment by alphaNOVAircraft** [comment]
I didnt say there is no alternative to it, ae seems to be one if you can input on the output side (i thought it didnt work last time i tried it, guess i fcked something else up then).
The storage doesnt need to be that high, i just suggested a value, if you would like it lower im fine with it as well. 
I didnt know bot asked you too do that cover, saw it for the first time. 

Having an alternative to ae p2p still doesnt seem harmful to me. 
Not quite sure why it would be irresponsible / moronic. If its bcz of the pricetag: you still need high lvl pumps to use the max possible transfere, so i think its still balanced.

**Comment by alphaNOVAircraft** [comment]
Found the issue why i thought its not n:n. You can input in output side of p2p and it will send to all other output sides (tried it only if the input side will recive, which it doesnt)

**Comment by 0lafe** [comment]
Use an e chest with large cells 🤷‍♂️

**Comment by alphaNOVAircraft** [comment]
@0lafe sure, i didnt say there are no other options. Using a chest in combination can be faster (by a lot). For me its more like a qol improvement. I like ender tanks and think it would be neat if you could use them with higher pumps as well. Having ender chests as a replacement or having a few more ae2 covers around seems boring to me, i like the look (and everyone can still decide for himselfe if he wants to deal with fps impact of them or use an alternative). Dont see a point why it SHOULDNT be in the game.

**Comment by Prometheus0000** [comment]
We could also add another tier of them.

**Comment by alphaNOVAircraft** [comment]
Yeah, dont know how to do that, thats why i simply changed the capacity
