### ISSUE TITLE
Make Crop Harvester accesible earlier

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/GT-New-Horizons-Modpack#7148]
So, the topic of discussion gonna be the buff of the Crop Harvester. 

With the upcoming change to forestry multifarm, in order to farm crops on the multifarm player has to obtain U238, which isn't a big deal, with the thorium ore in the nether, and the endereye plate. The latter one is a tricky part, without finding villager trade for the eye of ender or breeding enderbloom, the player can't farm crops on the multifarm until HV. We can all agree that multifarm with its ability to fertilize and hydrate crops, along with the enormous size is way superior compared to the harvester, and yet accessible at the same level in an upcoming patch.

My suggestion is to move crop harvester to LV level, so players do not have to bother with exploring half of the overworld in order to find an eye of ender trade villager, and still can farm crops on a slightly smaller scale at LV age.

**Comment by Azemari** [comment]
I agree HV is a steep gate to make a crop harvester. It does also make it confusing that it uses a HV hull but can only pull 32EU/t.  
By combining this with KiloJoel's steam pump in the next update could provide players' with an introduction to simple automated steam power. I don't know how this would affect how the game should be balanced.
However, my opinion would be to have LV components (as it's an LV input machine) but with an MV circuit (as it is quite useful). Which through my eyes, would make the recipe reflect the block itself more accurately.

**Comment by Dream-Master** [comment]
To be honest i play the pack myself an i am at mid mv and never had the time to setup a farm. Now i want to make Biodiesel and a farm will be very helpful. Let's change the recipe to early mv with lv components.

**Comment by Prometheus0000** [comment]
Old
![image](https://user-images.githubusercontent.com/8517039/102929719-1afd6100-4469-11eb-9e27-e037ca20d7a1.png)
New
![image](https://user-images.githubusercontent.com/8517039/102929727-205aab80-4469-11eb-897e-7628b39ef9e5.png)
alu sense blades, mv circuit and machine hull

Look good?

**Comment by Dream-Master** [comment]
yes @Prometheus0000

**Comment by Yarntheory** [comment]
I would cut back the material cost even more. that is a pretty massive aluminium investment early on in MV.

Maybe cut back down the LV parts, make the top center a LV scanner, and the 2 middle sides MV circuits? total cost being 3 LV circuits, 2 MV circuits, and the rest is just steel.

**Comment by Prometheus0000** [comment]
Do you happen to know where the recipe is defined? The one in the IC2 script file is commented out.

**Comment by Dream-Master** [comment]
@Prometheus0000 the recipe you suggest is fine. I went into mv and have tons of alu.

**Comment by leagris** [comment]
I'd make it entirely LV, except for sense blades because tin blades does makes much sense. I'd choose steel blades instead. And a Good Electronic circuit.

**Comment by Prometheus0000** [comment]
Well, I could change it if I could _find the recipe_. It doesn't appear to be in the IC2 script file, coremod script file, the coremod, or GT5U.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/2ff7f253b3471a5d48d7f430df07a15c643f6354
The parent commit of which is https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/00c66c98745a22c127e25968dcfc219ad1fd7894 which suggests it was all moved to code...somewhere.

**Comment by bedrill64** [comment]
> I would cut back the material cost even more. that is a pretty massive aluminium investment early on in MV.
> 
> Maybe cut back down *to LV parts, make the top center a LV scanner, and the 2 middle sides MV circuits? total cost being 3 LV circuits, 2 MV circuits, and the rest is just steel.

I agree with this recipe, making it early MV/Late LV lines it up perfectly with the step you obtain cropnalyzer. Fits well in progression curve in my opinion.

**Comment by Azemari** [comment]
> 
> 
> Do you happen to know where the recipe is defined? The one in the IC2 script file is commented out.

I was having a dig, line 106914 of config\Gregtech\Recipes.cfg says:
`
harderrecipes{
...
    B:cropharvester_true=true
`
Makes me think it might be in the actual GregTech mod? I've no experience with this code base so could be wrong

**Comment by Azemari** [comment]
My suspicions were correct. The recipe is in 
GT5-Unofficial-experimental\GT5-Unofficial-experimental\src\main\java\gregtech\loaders\postload\GT_CraftingRecipeLoader.java
Line 739

**Comment by Prometheus0000** [comment]
Ok thanks.
