### ISSUE TITLE
mods different

### ISSUE THREAD

**Issue by bjin2000** [GTNewHorizons/GT-New-Horizons-Modpack#7150]
#### Which modpack version are you using?
2.1.0.0 from http://downloads.gtnewhorizons.com/
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
The several mods between client and server are different.
#
#### What happened instead? (Attach screenshots if needed)
client:  draconic evolution 1.0.2r, hodgepodge 1.4.3, thaumcraft 4.2.3.5a
server: draconic evolution 1.0.2q, hodgepodge 1.4.2, thaumcraft 4.2.3.5
Also, technic lack CraftPresence
I didn't check curse and multimc.
#
#### What do you suggest instead/what changes do you propose?
Please check and confirm

**Comment by Dream-Master** [comment]
yea i fix that and we need an update very soon with a few versions that i not updated.

**Comment by Prometheus0000** [comment]
Same problems as #7149
