### ISSUE TITLE
Natura retrogen issues

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7151]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
It seems like the natura retrogen is taking a really high amount of milliseconds whenever someone explores chunks. TPS dropped to less than 5 when I started flying around. 

The clouds are also all still there.
#
#### What do you suggest instead/what changes do you propose?
Disable it until resolved

**Comment by Prometheus0000** [comment]
Your own fault though.

**Comment by KiloJoel** [comment]
![image](https://user-images.githubusercontent.com/17787093/103039464-e1138400-4568-11eb-9e9c-823f86e462c6.png)

**Comment by Prometheus0000** [comment]
I guess it was jackowski626 that made the PR. Why is mitch telling you to make the PR then?

**Comment by boubou19** [comment]
this is fixed in dev and on the official servers.
