### ISSUE TITLE
Extra MOX recipe with double results

### ISSUE THREAD

**Issue by Sirheavens** [GTNewHorizons/GT-New-Horizons-Modpack#7156]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Making MOX rods, I came across this recipe. It does seem to work, and gives a quad rod for 2 singles.
![image](https://user-images.githubusercontent.com/42445273/103112664-3ef3b900-469a-11eb-96be-6d4ce5634aba.png)

#
#### What happened instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
Seems like a leftover dev recipe, seems a bit OP.

**Comment by Prometheus0000** [comment]
I made a mistake when moving the recipes from scripts to code.
