### ISSUE TITLE
Traveller's Gloves Upgrades quest not completing

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7158]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/23512002/103129027-589bfd00-46a8-11eb-9d6b-92b078df244d.png)
![image](https://user-images.githubusercontent.com/23512002/103129037-605ba180-46a8-11eb-925b-b9ffdf555f00.png)
Quest id 1785

**Comment by Prometheus0000** [comment]
Current version
![2020-12-25_05 06 13](https://user-images.githubusercontent.com/8517039/103131588-5a959a00-466f-11eb-95b1-a0e20eddeef2.png)
After I try replacing it
![2020-12-25_05 08 51](https://user-images.githubusercontent.com/8517039/103131605-697c4c80-466f-11eb-8752-6a12e8729b8d.png)

I could make it ignore nbt, but it would just complete immediately, assuming we care. I do wonder why it breaks...whatever it is there though.

**Comment by Dream-Master** [comment]
yea ignore nbt not helps here.
@repo-alt can you post what mt hand command shows you so we can compare the nbt tag.

**Comment by repo-alt** [comment]
Well, can't do "/mt hand" on the server

**Comment by repo-alt** [comment]
In SSP mt hand returns the same

**Comment by Prometheus0000** [comment]
The problem isn't the specific NBT tags, but the fact that is has this
![image](https://user-images.githubusercontent.com/8517039/103204999-8c546e00-48c6-11eb-99e9-52c3493806e2.png)
there, so I don't know what would happen if I tried to keep it like that.

**Comment by Dream-Master** [comment]
Maybe we can add in in the GTNH fork
