### ISSUE TITLE
Crash when loading world related to AE2 and TFFT?

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7159]
#### Which modpack version are you using?
2.1.0.0
#
#### What did you try to do, and what did you expect to happen?
Start test world
#
#### What happened instead? (Attach screenshots if needed)
Crash
[crash-2020-12-25_04.32.14-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5741672/crash-2020-12-25_04.32.14-server.txt)
#
#### What do you suggest instead/what changes do you propose?
A fix. @botn365 is this the same as #7153? If so, where's the fix?

**Comment by botn365** [comment]
no this one is difrent
