### ISSUE TITLE
Zero Point Module only partially full when found

### ISSUE THREAD

**Issue by Smeany** [GTNewHorizons/GT-New-Horizons-Modpack#7161]
#### Which modpack version are you using?
2.0.9.0

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Found a Zero Point Module 6546:32598 in Lootchest on RossB. It was only filled to 2.147.483.647 aka 2^31-1 
when it actually should have been on full capacity 2trillion eu.

#
#### What happened instead? (Attach screenshots if needed)
Happened to have way less energy stored than it should have.

#
#### What do you suggest instead/what changes do you propose?
Store it in a variable type thats used for other batterys of that size maybe.

**Comment by basdxz** [comment]
Lore-wise this makes sense, ZPMs should always be found part drained energy remaining in them so this seems like an unintended feature.
But yeah, seems like @bartimaeusnek is using an int where a long is required

**Comment by GTNH-Colen** [comment]
> Lore-wise this makes sense, ZPMs should always be found part drained energy remaining in them so this seems like an unintended feature.
> But yeah, seems like @bartimaeusnek is using an int where a long is required

I believe this also happens in regular jungle temples implying that the issue is with something else not necessarily bart afaik.

**Comment by dvdmandt** [comment]
I always assumed it was intentional as they were always nearly depleted when found in the series.

**Comment by draknyte1** [comment]
It’s intentional.

**Comment by basdxz** [comment]
If the value is exactly the max of an int then it seems rather odd

**Comment by alphaNOVAircraft** [comment]
You shouldnt be able to find a full ZPM imo, to much energy for when you can find it, i dont want ppl to run around on ross for an hour and get enough energy to make their fusion reactor........... why not gift fusions and ass lines as well ....

**Comment by Devtron3D** [comment]
Rember to use it you need a ZPM battery buffer, plus transformers from ZPM all the way down to what tier you are.
When you reach LuV / ZPM it is not THAT much energy anymore.
Finding a full one would blow my mind, and would make me waste time trying to find out how to use it. 
So finding full ones I would not mind,

**Comment by Dream-Master** [comment]
I am not against it be always full.

**Comment by bartimaeusnek** [comment]
It's using the same table as the Pyramid ones, so this is a GT issue.
