### ISSUE TITLE
Add debug information for pollution

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/GT-New-Horizons-Modpack#7162]
#### Which modpack version are you using?
2.9

#
#### Summary
@mitchej123 
This suggestion is to add a line in waila and/or the debug scanner to tell you if the machine is not running because it is full of pollution. it will help out with knowing if your machine is missing a muffler hatch.

**Comment by repo-alt** [comment]
Should not structure check check for muffler presence right after assembling the multiblock?

**Comment by draknyte1** [comment]
Mine don’t. 
User should read the tooltip.

**Comment by repo-alt** [comment]
I don't see that as a benefit tbh
