### ISSUE TITLE
ElectroMagic Tools - Boots config is client-side

### ISSUE THREAD

**Issue by Lughbaloo** [GTNewHorizons/GT-New-Horizons-Modpack#7164]
In short, **Electromagic Tools** Nano boots and Quantum boots of the traveler pull their speed/stats from the Client configuration file, not the server. 
Players can manually change their own files to affect the speeds of these boots on multiplayer servers.

From my testing, you can manually set fall damage resistance, speeds, and jump height.

Probably can't be easily fixed without someone rewriting the code, just thought I'd let you know.

**Comment by Ethryan** [comment]
This should really be fixed, since it seems it is pulling all config values locally.
