### ISSUE TITLE
double and quadruple fuel rods from ic² now have a crafting grid recipe

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7167]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
looks like the old ic² recipes for double and quadruple fuel rods of thorium, uranium and mox somehow came back into the game. for example, this is the double fuel rod of uranium: 
![image](https://user-images.githubusercontent.com/12850933/103158981-35667000-47c4-11eb-8e2a-ac5cad880dcc.png)

Might happens because of the assembler recipes were moved in code by @Prometheus0000.

**Comment by Prometheus0000** [comment]
So these weren't supposed to exist?

**Comment by boubou19** [comment]
nope, i asked to some delta players to confirm my old memories, and they aren't supposed to be here. it's also incoherent with tiberium cells or naquadah cells, which are added by bartworks and GT.

**Comment by Dream-Master** [comment]
@Prometheus0000 the remove code maybe not worked

**Comment by Prometheus0000** [comment]
I'll take a look

**Comment by Prometheus0000** [comment]
I'd guess that they were removed by the script instead of removed or commented out, and now that script is gone, so they came back.

**Comment by Eason134HK** [comment]
> nope, i asked to some delta players to confirm my old memories, and they aren't supposed to be here. it's also incoherent with tiberium cells or naquadah cells, which are added by bartworks and GT.

Isn't it new recipe in 2.1.0.0?

**Comment by Prometheus0000** [comment]
Why would it need to be tested, I did that before submitting the PR?

**Comment by Dream-Master** [comment]
@Prometheus0000 if you tested all fine.
