### ISSUE TITLE
RFC Always show Assembly Line Recipes

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#7170]
#### What do you suggest instead/what changes do you propose?
Why do we hide recipes in NEI before you unlock the achievment, its annoying and if ppl want to know it they just check in singleplayer. 
You need to scan the item to be able to make it anyways. So it would be a small qol change with no progression change at all.

**Comment by ChemEng227** [comment]
that will make printers and data reader a meaningless machine.

**Comment by GTNH-Colen** [comment]
> that will make printers and data reader a meaningless machine.

The horror.

**Comment by boubou19** [comment]
not necessarily for the printer: old data sticks could use this as well, but ngl, the tectech's machine to read the datasticks is so convenient that i don't use the printer (forgot its actual name)

**Comment by Dream-Master** [comment]
no i am against it show the recipe before you reserahced it.

**Comment by GTNH-Colen** [comment]
> no i am against it show the recipe before you reserahced it.

Why?

**Comment by alphaNOVAircraft** [comment]
> that will make printers and data reader a meaningless machine.

let be honest, everyone looks the recipes up in nei in singelpayer before, its just annoying to hide them, you have to walk back and check the recipe in the data reader again. 
Setting up patterns / automating the ass line is more then annoying enough if you have to do it the 50th time over and over again. 
And who the fck even considers using printers, and they still have a use for prospectors data.

**Comment by alphaNOVAircraft** [comment]
We are not changing the balance of anything nor making anything easier. It would only change that ppl dont have to go to sp to check the recipe (and if you were on a server before going into sp your game might crash and you have to restart it for 10 minutes, at least happens nearl 50% of the time i go to sp test worlds, and i know a few other ppl experiencing that issue)

**Comment by Anarack** [comment]
Doesn't tec tech add a data stick viewer anyway? people only use the printer is if they don't know that exists.
Or they just check our wiki which has all of the assline recipes posted.

**Comment by Prometheus0000** [comment]
Maybe change the unlock to reading the printed book instead of picking up the item?

**Comment by GTNH-Colen** [comment]
There is no real reason not to do this if it's possible, it will have absolutely 0 impact on balance and just stops needless pissing about. Everyone either checks in SP or opens the [wiki page](https://gtnh.miraheze.org/wiki/Assembly_Line_Recipes) completely nullifying this mechanic anyways.

People will still have to research the recipe, this is a purely visual change.

**Comment by alphaNOVAircraft** [comment]
Still annoying, you dont see recipes, and sometimes you need to know if its worth the effort to research it / what you need to focus on to progress. 
Everyone just checks in sp. 
E.g. if you see a item in NEI you were intrested in, but its locked behind the research station and you just reached UV. Now it would be grate to know if its worth the effort setting up the research station or if you can wait a bit longer cz you cant get the item you wanted anyways. Noone is gonna take such a step without checkin in sp. 

All we are doing here is making ppl not going to a creative sp world. Its not making anything easier, its just removing annoying swaps to sp that might crash your game. 

Maybe ppl who barley saw LuV think its a funny mechanic, but it really is not if you have to do it every time. Its a nice idea and the data sticks will still be necessary, but overall its just annoying with no point of all.
