### ISSUE TITLE
How to install optifine?

### ISSUE THREAD

**Issue by Aleks233** [GTNewHorizons/GT-New-Horizons-Modpack#7172]
#### Which modpack version are you using?
2.0.9.0
#
#### What did you try to do, and what did you expect to happen?
I want to install optifine, but it will report an error,
Is my installation method wrong?
So how to install optifine.
Can you tell me,thank.

**Comment by boubou19** [comment]
install either optifine D6 if you wants to stay with fastcraft 1.23, or update fastcraft to 1.25 and use optifine E7 to get shaders. Next time ask in our discord server, in #help. This place is to discuss the balance of the pack and to report bugs.

**Comment by Aleks233** [comment]
Ok.
But,i can't jion yours discord server.
Prompt invitation invalid.

**Comment by Aleks233** [comment]
What shall I do?

**Comment by Dream-Master** [comment]
https://discord.gg/CUF92w7CHz

**Comment by Dream-Master** [comment]
@Aleks233

**Comment by Dream-Master** [comment]
I copy the link in case you never used Google before 😜
