### ISSUE TITLE
MEGA EBF tooltip needs correction

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7173]
#### Which modpack version are you using?
GTNH 2.1.0.0
#
![image](https://user-images.githubusercontent.com/57050655/103163321-fc96bd00-47fc-11eb-80b8-a50c44326715.png)

This line is wrong, it's not what the mega EBF is doing, it is behaving like the normal EBF (eu/t reduction and not recipe duration reduction) wich is the following : 

![image](https://user-images.githubusercontent.com/57050655/103163339-28b23e00-47fd-11eb-8b3f-dd7e03841f05.png)

I suggest changing both of the tooltips ( EBF and mega EBF) to make them clearer : 

- Each 900K over the min. Heat Capacity reduces power consumption by 5% (multiplicatively)
- Each 1800K over the min. Heat Capacity grants one perfect overclock
- For each perfect overclock the EBF will consume 4 times more power while running 4 times faster

**Comment by boubou19** [comment]
is the "Additionally gives +100K for every tier past MV" applied to the Mega Blast Furnace too?

**Comment by Prometheus0000** [comment]
Pretty sure not.

**Comment by boubou19** [comment]
i just checked and the mbf just checks for the coil temperature. But given the parallele processing of the mbf, it's fair to not have the +100°K for each tier past MV.
