### ISSUE TITLE
Quest "Making Better Tools" quest in wrong place?

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#7174]
#### Which modpack version are you using?
2.0.1.0QF1

The quest "Making Better Tools" in the Stone Age, talks about Aluminium Brass, but what we are making here is bronze.

![image](https://user-images.githubusercontent.com/3405825/103169199-eeb35d00-4839-11eb-94d1-3321dd440231.png)

All quest items are bronze,  why is this locked behind aluminium?

**Comment by Prometheus0000** [comment]
To make the cast. The text should mention both though.

**Comment by Devtron3D** [comment]
Might I suggest a quest be made for making the cast. 
It might also be advantageous to lock steam behind these tools, When you get to the macerator quest, you need diamonds, and in my current test beginning playthrough, I got stuck at the macerator, I was unable to mine diamond, and I had to go looking for what quest gave better tools to mine diamond.
For a new player, It might prevent them from getting stuck, if these tool upgrades are a must for steam age.
