### ISSUE TITLE
Oil/gas fluid drilling rig weird pumping behavior

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#7175]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#

I'm currently pumping saltwater in mars and it seems that the pumping rate is decreasing as long as the salt water in the chunk decrease
For exemple, with a T1 Drilling rig with an MV, then an HV hatch (just to test), and I'm approximattely with a 400mb/s pumping rate. After a few hours it decrease to like 50 mb/s.
Is that an intened behavior ?  
I want to underline that in the Overworld, I also have a T1 drilling rig with MV Hatch to pump oil and it doesn't behave like that, the pumping rate isn't decreasing as long as the chunk gets pump.

**Comment by Devtron3D** [comment]
As far as I know, depending on how much is left it decreases over time
I have also seen from using t3 that pumps more chunks, that it will empty one chunk at a time, and while one is draining its output wil decrease, then when it switches to a new one, the output will be high again.
This is from playing on 2.0.9.0

**Comment by Nicouuuuu** [comment]
I agree with you because I observed that in 2.0.9.0 too for the first time
So okay, this is apparently intened

**Comment by Prometheus0000** [comment]
> I have also seen from using t3 that pumps more chunks, that it will empty one chunk at a time, and while one is draining its output wil decrease, then when it switches to a new one, the output will be high again.

Shouldn't it be pumping from the entire range at once? Did you change the mode with a screwdriver?

**Comment by Nicouuuuu** [comment]
Little update on this issue, as I said at the beginning, this behavior wasn't happening in the OW, now it seems that it is the case.
Maybe I didn't check correctly before because I'm still in 2.1.0.0.
So the drill pumps less and consume the same amout of power.
This is both time consumming and power wasting for nothing in my opinion.

**Comment by boubou19** [comment]
It's the intended behavior, as you are supposed to put some circuits inside the pump to tell it which fluid level it needs to ignore, when you make it run in "ignore near exhausted fluid chunks" mode.

**Comment by Prometheus0000** [comment]
BTW, I tested that before and it doesn't work https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6962
