### ISSUE TITLE
Void miner does not extract resources on Proteus

### ISSUE THREAD

**Issue by Alsarus** [GTNewHorizons/GT-New-Horizons-Modpack#7176]
#### Which modpack version are you using?
2090 qf4
#
#### If in multiplayer; On which server does this happen? 
local server
#
#### What did you try to do, and what did you expect to happen?
Install void miner 1. Tirn on and waiting resources in output bus. But they didn't comming. Void miner working. Drill tube on bedrokium. On another planet (titan) this miner working.
#
#### What happened instead? (Attach screenshots if needed)
http://puu.sh/H1ktf/898e0ada5b.jpg
http://puu.sh/H1ktl/5e087076f5.jpg
http://puu.sh/H1ktp/256681b4df.jpg
#
#### What do you suggest instead/what changes do you propose?
fix

**Comment by Prometheus0000** [comment]
Try again on latest

**Comment by Alsarus** [comment]
@Prometheus0000 same situation on 2100. Reinstall void miner. They does not extract(

**Comment by boubou19** [comment]
Still don't work if you reset your dim files?

**Comment by Alsarus** [comment]
@boubou19 i can check this. Whats Proteus dim number?

**Comment by boubou19** [comment]
according to the galaxyspace conf, it is 47.

**Comment by GTNH-Afx237v7** [comment]
Reset dim file = delete dim folder, or is there another way to do it?

**Comment by Alsarus** [comment]
@boubou19 i delete folder DIM47 and nothing changed. They does not extract

**Comment by Alsarus** [comment]
After reinstall they works good. I think it has something to do with machine cover. When i install void miner fistly, main block was be with machine cover. And when i install they didnt work. Then i disconnect cover and reinstall all component and tirn on they work greatly. 
And yeah, when i install void miner with cover and thed remove cover, void drill does not work again. I remove drill tube under drill and tirn on, but tube didnt exit from miner, but drill working.

**Comment by boubou19** [comment]
have you tried to use a screwdriver on the machine controller cover? might be inverted with your setup

**Comment by Alsarus** [comment]
yeah. I use screwdriver on cover. I use "disable with Redstone" mod on cover.

**Comment by boubou19** [comment]
can you retry in 2.1.0.0 please?

**Comment by GTNH-Afx237v7** [comment]
related ticket: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7738
Though I have been using the VM with and without cover, I did not see a relation between it working or not working. I think it started to work again for Alsarus because he broke and replaced it - though I did that several times as well, without any ores being output.

**Comment by Aggadahr** [comment]
i had a wonky time setting up the VM 3 today on 2.1.1.0 (epsilon)
it drained oganesson and the mining pipe was on bedrock, but no ores appeared in the output

removing all covers, replacing the controller block and putting the covers back on fixed it for me. Dimension is VegaB

**Comment by GTNH-Afx237v7** [comment]
Did you put the controller in the exact same spot as before? What covers did you use?

**Comment by Aggadahr** [comment]
i used machine controller cover (below the controller) and item detector cover on the output bus, as well as a energy detector cover on the energy source (not the energy hatch, so not part of the multiblock)

repositioning the drill didnt fix it, placing it in the exact same spot did - so i guess position is not the issue

**Comment by GTNH-Afx237v7** [comment]
I tried with cover, without cover, break and replace in the same spot, move to completely new location, delete dim folder and place again-all without luck...
Can you tell me the X and Z position of the controller? Would like to see if any positive/negative placement may have an effect.

**Comment by Aggadahr** [comment]
![javaw_2021-06-23_20-15-13](https://user-images.githubusercontent.com/46688121/123147812-c78fbe00-d45f-11eb-9dd7-0d91bcb8d33d.png)
![javaw_2021-06-23_20-14-42](https://user-images.githubusercontent.com/46688121/123147827-cb234500-d45f-11eb-8d90-45fa71141359.png)
![2021-06-23_20-14-06](https://user-images.githubusercontent.com/46688121/123147833-cd859f00-d45f-11eb-9bbd-4a22c10e857a.png)

**Comment by Alsarus** [comment]
General sequence is:
1) Install void miner without covers. If you have covers - install, delete covers, and reinstall again.
2) Start void miner and waiting resourses in output
3) Stop void miner
4) Install covers

Only in this case, I get resources at the output.

**Comment by Aggadahr** [comment]
i skipped step 3, but yeah
