### ISSUE TITLE
Arcane assembler with GT tools

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7178]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Craft encoded recipe in arcane assembler with GT tools
#
#### What happened instead? (Attach screenshots if needed)
Gt tools correctly recognized as multi-use (requesting only 1 despite used multiple times), but after 1 usage crafting tools arent returned until crafting task cancelled, preventing next recipes from executing
![image](https://user-images.githubusercontent.com/29033773/103175999-6f487c80-487f-11eb-877a-bb039808d6ab.png)

**Comment by Prometheus0000** [comment]
Use the oredict tag. Also, this is for bugs, not help. If you can get it to work with a normal assembler but not the arcane one, state that.

**Comment by Florexiz** [comment]
You cant specify ore dict while encoding recipes for arcane assembler, but it looks like its enabled by default. IF not - it will mass craft tools, but they are recognized as multi use, so this isnt the case. No such  issues with molecular assemblers.
![image](https://user-images.githubusercontent.com/29033773/103194855-ed456b80-48f1-11eb-849f-af3136301fef.png)

**Comment by Prometheus0000** [comment]
I don't understand, now it works?

> looks like its enabled by default. IF not

Then how would you disable it to know? Did you change a config setting or something?

If it's got oredict on by default, then there shouldn't be a problem, right?

**Comment by Florexiz** [comment]
Im saying that you cant disable ore dict there and issue not about it. Not at planning phase of recipe at least

**Comment by Prometheus0000** [comment]
BTW, you didn't fill in a section about what you want done, I assume you want the same functionality as the normal MA, where it reuses the tool? Maybe @repo-alt can do something.

**Comment by Florexiz** [comment]
> BTW, you didn't fill in a section about what you want done, I assume you want the same functionality as the normal MA, where it reuses the tool? 

Just thought it was obvious that blocking recipes is not how it was planned :p

**Comment by GTNH-Afx237v7** [comment]
There is no button on a knowledge inscriber to enable oredict, like on a regular ME pattern terminal when you define a recipe. 
The recipe never completes and thus never returns the screwdriver.
What it should do is simply complete the crafting process and return all tools back to inventory.

**Comment by Prometheus0000** [comment]
> There is no button on a knowledge inscriber to enable oredict, like on a regular ME pattern terminal when you define a recipe.

He said it's default on.

> The recipe never completes and thus never returns the screwdriver.

It never completes, even if it's for 1 item? Presumably only when using a tool with durability?

**Comment by GTNH-Afx237v7** [comment]
He assumed it is on by default 😉

**Comment by Florexiz** [comment]
> It never completes, even if it's for 1 item? Presumably only when using a tool with durability?

Yeah, even when used for 1 craft they arent returned
Noticed only with gt tools, nor sure about buckets with fluid or similar (if we even have such recipes)

**Comment by boubou19** [comment]
don't close the issue if it's labelled a fixed in dev, it helps Dream to make the changelog.
