### ISSUE TITLE
Suggestion- make the backpack warning on tooltip shorter

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7182]
#### Which modpack version are you using?
2.10.0

#
#### What do you suggest instead/what changes do you propose?
Perhaps "WARNING: Upgrading deletes contents" in red would be enough?  Right now the tooltip blocks view of my entire inventory whenever I mouse over my backpack...

**Comment by Prometheus0000** [comment]
Ask dream about it, it's his tooltip.

**Comment by McFrugal** [comment]
I am well aware of that.  I am also well aware that he uses this github.

**Comment by Ethryan** [comment]
We might be able to completely remove the tooltip soon, if #7137 last comment is implemented.

**Comment by Dream-Master** [comment]
Oh no my nice tooltip 🙄. If the script realy fix it sure.

**Comment by Yakameen** [comment]
I'll take a look into it today. It should be an easy copy-paste to implement with the other backpacks, I just got lazy after troubleshooting the adventure backpacks.

**Comment by Yakameen** [comment]
See  #7292 for the fix. I also added ore directories so backpacks can be dyed multiple times.
