### ISSUE TITLE
server crush when Witches Oven is crafting.

### ISSUE THREAD

**Issue by Alsarus** [GTNewHorizons/GT-New-Horizons-Modpack#7183]
#### Which modpack version are you using?
2100
#
#### If in multiplayer; On which server does this happen? 
local server
#
#### What did you try to do, and what did you expect to happen?
Try chaft receipt in witches oven(see screenshot). I put oak spring in oven and then server crush and save corrupt. Logs here
[crash-2020-12-28_18.41.57-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5747495/crash-2020-12-28_18.41.57-server.txt)
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5747498/fml-server-latest.log)
[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5747499/GregTech.log)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5747500/latest.log)

#
#### What happened instead? (Attach screenshots if needed)
http://puu.sh/H1CGa/f0d7dcefe0.png
#
#### What do you suggest instead/what changes do you propose?
fix

**Comment by Dream-Master** [comment]
Known issue. Fix in the next version
