### ISSUE TITLE
Items not routed to ProjectRed extension pipes

### ISSUE THREAD

**Issue by q009** [GTNewHorizons/GT-New-Horizons-Modpack#7184]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
Local

#
#### What did you try to do, and what did you expect to happen?
I've set up autocrafting of GT cables: routing wires to an assembler and rubber sheets (via an extension chip) to a fluid extractor.
When requesting the crafting of cables using this setup, wires should be put in the assembler and rubber sheets in the extractor.
This setup was working in modpack version 2.0.9.0 therefore I can say that this is probably a regression.

I attempted to re-assign the extension chips, removing the pipes, giving them new UUIDs, did not help.

#
#### What happened instead? (Attach screenshots if needed)
All the items were routed to the block connected via the crafting pipe (crafting chip), completely ignoring the extension.
Both the wire and the rubber sheet were put in the assembling machine.
Same behavior is observed in other setups using extension chips.

#
#### What do you suggest instead/what changes do you propose?
Items should be routed in accordance with extension chips.

**Comment by q009** [comment]
I downgraded ProjectRed to version 4.7.0pre12.95, I can confirm that the issue no longer appears.

**Comment by Dream-Master** [comment]
@makamys it was your pr any idea what went wrong ?

**Comment by makamys** [comment]
I'll have a look at it.

**Comment by makamys** [comment]
Can you post some screenshots of your setup? I can't seem to be able to recreate it.
