### ISSUE TITLE
Chest Buffer does not combine stacks

### ISSUE THREAD

**Issue by Skiftcha** [GTNewHorizons/GT-New-Horizons-Modpack#7185]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
local ultramine
#
#### What did you try to do, and what did you expect to happen?
using EV Chest Buffer set to output 36 items
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/2212585/103233873-41cb0400-494f-11eb-8f7f-607ad3105d7b.png)
![image](https://user-images.githubusercontent.com/2212585/103233919-59a28800-494f-11eb-89ab-d3b680786424.png)
#
#### What do you suggest instead/what changes do you propose?
uncomment this? https://github.com/GTNewHorizons/GT5-Unofficial/blame/3a07aac9a56e9f340954e9092aecf85ba648c405/src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_ChestBuffer.java#L74

because according to these lines
https://github.com/GTNewHorizons/GT5-Unofficial/blame/3a07aac9a56e9f340954e9092aecf85ba648c405/src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_ChestBuffer.java#L62-L66
it can move items to first slots only when inventory changed at the same tick machine can work

alternatively, move check of hasInventoryBeenModified before tick check and return

**Comment by boubou19** [comment]
Could it be a lead to reduce the lag of chest buffer / super buffer?

**Comment by boubou19** [comment]
it does happen for the super chest buffer too (output stack size set up on 63): 
![image](https://user-images.githubusercontent.com/12850933/103461597-e1a5da80-4d1f-11eb-8c6a-322c37acfebe.png)

**Comment by johnch18** [comment]
On the topic of buffers, I've had my buffers get "stuck", and I have to empty/refill them using conveyors to get them to function again.

**Comment by boubou19** [comment]
it is still annoying to make some maintenance on that. We could imagine something like in the input hatches were the stacks are automatically merging.

**Comment by yukieiji** [comment]
I also had this bug, before the update it was sorted but after the update it is not sorted...
I changed to the Crucibe server when I updated, so it may be incompatible with [um_bukkit](https://gitlab.ultramine.ru/ultramine/um_bukkitl), considering that it is also happening on Ultramine.

**Comment by Prometheus0000** [comment]
Try on latest
