### ISSUE TITLE
Prohibit long term weather control in OW

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7187]
Right now Eta (not sure about other servers) have warp for toggling permanent day and disabling weather, and before that some players wanted to build similar stuff on their own
Im proposing to disable this warp and add rule to prohibit any long term manipulation with day cycle and weather. 
Here is the reasons why:
1) Breaking early experience of modpack to new players. When everybody can toggle night off you can just forgot about any danger in OW completely (not talking about towns itself)
2) Messing with other players needs. Every time you must teleport to warp, press button, wait for tp cooldown and wait for day/night (if you dont have foci) and praying no one will toggle Celestus again
3) No sense in garden/void dims when all their benefits enabled in OW almost 24/7 (kinda OP btw)
4) There are no more dims with regular weather and day cycle (except space maybe) that some (me at least) liked

You can think about more issues caused by such warps and mechanisms, but thats what came to me first

**Comment by GTNH-Colen** [comment]
Players were already manipulating the time long before celestus, celestus enables it to be centrally controlled so that anyone can have the power to switch it off when needed (Such as for rituals). In addition you seem to be the only person I've seen who has had a big issue with this, take it up with the staff on discord.

Also players deliberately abusing celestus and not allowing others to do simple things such as turn it off to do something for a little bit (Again, primarily thinking things like rituals or bees here) when requested will be punished just as someone abusing /vote veto would be.

**Comment by repo-alt** [comment]
I wonder what the vampires think

**Comment by boubou19** [comment]
if players are actively fighting for the weather control while being selfish, just fill a report to staff, as Colen said. This falls under the 2nd rule of the official servers: "Be nice to the others"

**Comment by repo-alt** [comment]
Tbh, I find it very weird, and not in spirit of the pack to have such control in the early game, but I don't play on Eta anymore (and even if I did, I already have weather control focus there)

**Comment by Prometheus0000** [comment]
> warp for toggling permanent day and disabling weather

Does warp do this? I thought it was negative effects to the player?

> teleport to warp

What?

> Celestus

Is this some kind of server only item?


Also, making it perma-day kinda gets rid of mobs, making it even easier than the TF, which has tons of caves for mobs to come out of.

**Comment by Florexiz** [comment]
> What?

You never played servers? xD
Warp is a point to which you can teleport
![image](https://user-images.githubusercontent.com/29033773/103246576-05120380-4975-11eb-967b-83dc2c794bce.png)

**Comment by Prometheus0000** [comment]
Probably should be called Warp Points instead.
