### ISSUE TITLE
Warded Glass recipe consuming Warding Focus

### ISSUE THREAD

**Issue by Yarntheory** [GTNewHorizons/GT-New-Horizons-Modpack#7188]
#### Which modpack version are you using?

2.1.0

#
#### If in multiplayer; On which server does this happen? 

Eta

#
#### What did you try to do, and what did you expect to happen?

Craft 4 warded glass, expected the warding focus to not be consumed

#
#### What happened instead? (Attach screenshots if needed)

Warding focus gets consumed

#
#### What do you suggest instead/what changes do you propose?

Per Prometheus on the discord server, the focus is not intended to be consumed (there is a config option).

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6846
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/126

**Comment by Shyrff** [comment]
how will this hack with giving focus back will work with ae2 autocraft?

**Comment by repo-alt** [comment]
That is broken even in Arcane terminal, not just in autocrafting.

**Comment by Prometheus0000** [comment]
@Glease

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/152 should fix it.
