### ISSUE TITLE
Shutters on bottom of fluid pipes look wrong

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7189]
#### Which modpack version are you using?
2.1.0.0
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/17787093/103293627-26f89e00-49e8-11eb-9ed4-347ba2a1285c.png)

I guess probably to do with this https://github.com/GTNewHorizons/GT5-Unofficial/pull/363

**Comment by KiloJoel** [comment]
Those are tiny plastic fluid pipes

**Comment by boubou19** [comment]
are they from the core mod or from GT? in 2.1.0.0 pipes from the core mod still have this issue. Iirc @leagris fixed it in dev by recompiling the core mod with newer GT api

**Comment by Prometheus0000** [comment]
@leagris ?

**Comment by YannickMG** [comment]
Looks fine in-game now. 
<img width="292" alt="image" src="https://user-images.githubusercontent.com/5321549/177855635-458f01f9-d73e-4a66-ba4b-603035e88205.png">
