### ISSUE TITLE
Cooking for Blockheads cabinet and counter delete stored items

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#7190]
#### Which modpack version are you using?
GTNH version 2.1.0.0, CFBH version 1.2.0-GTNH

#### If in multiplayer; On which server does this happen? 
Single player, N/A

#### What did you try to do, and what did you expect to happen?
I placed items inside of the storage of the Counter and Cabinet blocks that are a part of Cooking for Blockheads. I then saved the game and closed Minecraft. I expected the items to stay stored within.

#### What happened instead? (Attach screenshots if needed)
After opening GTNH and loading my single-player save, the items were gone. 

#### What do you suggest instead/what changes do you propose?
The items should not be deleted. I did not try the Fridge or Cooking Oven blocks to see if they properly store items.

**Comment by mitchej123** [comment]
Pushed out a fix, and put a new test version in #mod-dev
