### ISSUE TITLE
Remove ULV from power info in NEI

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#7191]
#### Which modpack version are you using?
2.1.0.0
#
I see many questions about this on the discord server in help, it's very confusing for new players and honestly adds nothing of value for more experienced players as far as I can tell. People assume that ULV -> LV is an overclock and well GT logic would suggest that to be true except it just isn't and really has 0 purpose.

![unknown](https://user-images.githubusercontent.com/54497873/103300643-3af7cc00-49f7-11eb-8df1-d1ee7d88528a.png)

Not sure how baked this is into the core GT but given @bartimaeusnek is currently changing some layouts with this stuff anyways (Adding colours) maybe he would know if this is feasible? 

Note I'm not saying we should purge all ULV related items out of the game, given a lot (all?) seems to exist in GT++ for some reason we can't do that anyways but what I am suggesting is that we change the NEI interface so that it'd just recognise this as LV.

**Comment by sintken** [comment]
agree, but ulv is technically its own voltage tier (see: simple washer I, for example). maybe add a line to the first quest mentioning overclocks?
