### ISSUE TITLE
Binnies genetics splicer recipe is way too expensive

### ISSUE THREAD

**Issue by MatthewCOwen** [GTNewHorizons/GT-New-Horizons-Modpack#7192]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
zeta
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/16054364/103304565-d0766a00-49bd-11eb-8f4d-d7adeaaa6c8b.png)
![image](https://user-images.githubusercontent.com/16054364/103304588-dcfac280-49bd-11eb-8c91-1fa13a5058c4.png)

#
#### What do you suggest instead/what changes do you propose?
balance this back into mv. The rest of the binnies machines cost 4 hv circuits per machine, which is reasonable I guess
No reasonable person is going to use 48 advanced circuits on this machine

**Comment by Prometheus0000** [comment]
@MatthewCOwen It's been balanced to be properly HV, since it's an upgraded version of the inoculator. I had it use less, but higher tier circuits though.
