### ISSUE TITLE
nasa workbench, can't craft tier 2 rocket

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#7196]
#### Which modpack version are you using?
2.1.0.0QF

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
Crafting tier 2 rocket in nasa workbench

#
#### What happened instead? (Attach screenshots if needed)
rocket doesn't appear after placing all the items
![javaw_u705Xuugn9](https://user-images.githubusercontent.com/17811922/103314293-eff3ae00-4a22-11eb-96fe-88975a33d9db.png)

#

**Comment by glowredman** [comment]
Fixed with GalaxySpace version 1.1.7b (http://jenkins.usrv.eu:8080/job/Galaxy-Space/62/)
