### ISSUE TITLE
Pollution at the beginning, with extra steps. 

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#7197]
#### Which modpack version are you using?
2.1.0.0qf1

I spent some hours on the new update looking at what stumps beginners, and pollution looks to be one of them, as player's bases now get polluted faster than they get the hazmat suit.

I propose an extra item or two to solve the pre player damage pollution at the start of the game.

As we are in this COVID time, how about adding masks to the start of the steam age, before the BBF, and after the coke oven.
The use of a mask would remove the de-buffs and allow the player to keep doing what they do to build their base. Later on, when pollution gets higher hazmat would be needed.

Now to add to the GTNH part where things are done with extra steps, there should be several mask types.

Single-use masks, 
    -These last 20-30 min.
    -These could be crafted with wool/silk, and once used, they don't get destroyed, but just fill the inventory/chest, so we get 
    -the real-world effect of used masks everywhere.
     
Reusable masks with filter change.
    -These are a mask with changeable filters, and the player would be able to make filters that have different quality.
    -The quality of the filters affects the time until they need to be changed, say 30-60-90min filters.
    

All this could be pre-rubber, to help the player have several coke ovens and smelter running, as well as the few starting steam boilers.

**Comment by Dream-Master** [comment]
yea why not. @Devtron3D  feel free to add it.
