### ISSUE TITLE
Suggestion- mud block to clay block extractor recipe

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7199]
#### Which modpack version are you using?
2.10.0
#
#### What do you suggest instead/what changes do you propose?
There's a mud ball to clay ball extractor recipe but nothing that uses mud blocks.  Might as well have one so players can store mud balls as mud blocks without having to manually break the blocks afterwards to make use of them (for instance, when settling in a swamp)

**Comment by Prometheus0000** [comment]
I don't see the point of this when you can already extract the balls? There's no reason to craft them into blocks, that's what barrels or drawers are for.

**Comment by Ethryan** [comment]
Seems like you can’t use the mud blocks for anything and it’s a pain to manually break them into balls in order to get clay out of them.

**Comment by Prometheus0000** [comment]
Yes, but why would you make them into blocks to begin with?

**Comment by Ethryan** [comment]
No clue

**Comment by McFrugal** [comment]
You can store mud more easily if it's in block form.
But hey, a recipe to turn blocks into mud balls would work just as well.
