### ISSUE TITLE
Crop Harvester recipe 

### ISSUE THREAD

**Issue by Azemari** [GTNewHorizons/GT-New-Horizons-Modpack#7200]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Crop harvester has reverted to HV recipe for me and Colen, but not KiloJoel. Don't know about other people
#
#### What happened instead? (Attach screenshots if needed)
Image is same server (Eta), 1 minute apart
![image](https://user-images.githubusercontent.com/55991839/103411927-b201a180-4b6a-11eb-9bba-24a168f5a55a.png)

#
#### What do you suggest instead/what changes do you propose?
Figure out what's happening. This started happening as of 2.1.0.0 as a part of [issue](url) #7148

**Comment by TimDiekmann** [comment]
It appears that the server is using another recipe than the client. The same also occures on my private server with the latest serverpack download (2.1.0.0). Uploading the gregtech.jar from the client crashes the server.

**Comment by Skiftcha** [comment]
my friends with technic launcher have lv recipe.
multimc and server packs use hv parts

**Comment by Dream-Master** [comment]
yes will correct that asap

**Comment by Prometheus0000** [comment]
@Dream-Master  is this fixed on newer versions?

**Comment by Dream-Master** [comment]
Need to check

**Comment by boubou19** [comment]
see #8035
