### ISSUE TITLE
BetterQuesting should save the state of its bar after client restarts

### ISSUE THREAD

**Issue by mkrutov** [GTNewHorizons/GT-New-Horizons-Modpack#7201]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
not applicable
#
#### What did you try to do, and what did you expect to happen?
BetterQuesting auto hides sidebar every time client is reloaded.
#
#### What happened instead? (Attach screenshots if needed)
It should remember configuration between restarts.
#
#### What do you suggest instead/what changes do you propose?
Read previous point.

**Comment by r2go-beep** [comment]
This has already been merged in the BetterQuesting repository, https://github.com/GTNewHorizons/BetterQuesting/pull/25
