### ISSUE TITLE
Geolyzer as prospector scanner for oils

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7203]
Proposing to add method in geolyzer component for getting oil/fluid under bedrock in current chunk.
Right now we dont have any reliable option to scout chunks in search for fluids. This can add sense into drone usage and make both geolyzer and drones correspond their initial concept as scanning tools.

**Comment by boubou19** [comment]
This is a very good idea.
