### ISSUE TITLE
[RFC][feature request]: GT Pump go streight to bottom then pump

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#7205]
Expanding on https://github.com/GTNewHorizons/GT5-Unofficial/pull/388

Pumping oil spouts surround by water or other fluid can be an issue, especially when water is infinite (not the GTNH default, but an issue anyway) and water sources regenerates immediately before the pipe has time to go down to continue pumping or flowing water invade the space left by the removed oil blocks.. It can cause the pump to suddenly pump water instead of oil.

I propose the following changes to the pumping mechanic:

Mechanic would be 3-phases only:
1. Pipe deployment identifies fluid top-most and bottom-most layers, deploy pipes down to bottom most layer and pump only replaced fluid blocks on its way down.
2. Pumping phase, pumps only identified fluid layers from top to bottom.
3. Once no more of identified fluid layers, retracts the pipes.

Detailed mechanic:
- Pump memorize the first fluid it encounters while deploying the pipes.
- Pipes would deploy down until reaching a solid block **or a fluid of a different type**, pumping only the single fluid block it replaces on its way.
- Once at the down-most layer, it shall now only start pumping the top-most fluid blocks layer that is of the memorised type and that is in contact with the pipes column; and continue until there is no more fluid blocks in contact with the pipes.
- Then only retracts the pipes.

How to define what fluid to pump if multiple fluids are in contact with the pipe, and how to define a fluid contact with the pipes:

1. **Fluid contact:**  
  Either a source or a flowing fluid block is directly adjacent to a pipe. If hitting flowing fluid, it scans connected blocks to find a source fluid block of that type. (Basically what a BC pump does)
2. **Multi-fuild decision:**  
  When scanning the bottom to top for fluid blocks to pipe contact, it stops scanning higher if the fluid is no more what has been memorized during deployment. Example:  
    - Lets say, bottom 1 to 7 layers is oil, and layer 8 to 15 is water, it stops scanning at layer 7 and start pumping oil at layer 7, then go down.  
    - When it has pumped the last bottom layer of oil, chances are that water sources or flowing water has filled down, replaced the emptied oil blocks. Pump shall detect no more oil in contact with the pipes and start the pipe retraction process. The pipe retraction also means forgetting the fluid type, or the pump need to be wrenched out to forget/reset itself to the pipe deployment phase.
    - Air gaps are to be ignored skipped. 

What issues would be fixed with this new mechanic:

1. Pumping wrong fluid when multiple fluids are in contact and flows changes during pumping.
2. Pumping stop because falling gravel/sand erased source blocks and only left air gaps and flowing fluid.
3. Pipe descent delay interrupt pumping.

**Comment by Prometheus0000** [comment]
It would need to ignore flowing fluids for which the source block is not in it's range though.

Also, how would it work if a fluid is in it's range but not flowing to the pipe?

**Comment by leagris** [comment]
> It would need to ignore flowing fluids for which the source block is not in it's range though.

Yes

> Also, how would it work if a fluid is in it's range but not flowing to the pipe?

Ignore it. A pump cannot work if its pipe is not in contact with the fluid, even in real-life, or you need a vacuum with a very high flow to attract a remote fluid with a venturi effect. But that would be quite abusive.

**Comment by Prometheus0000** [comment]
Might make it harder to get oil if you use the LV pump on it first in certain circumstances. Though maybe you could place down a bucket of oil inbetween to connect it?
