### ISSUE TITLE
UEV field generator has a different texture than the other field generators

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7206]
#### Which modpack version are you using?
2.1.0.0

There is a small white dot on the UEV field generator texture:
![image](https://user-images.githubusercontent.com/12850933/103437797-23edef80-4c2c-11eb-94dc-2c0386ae77ce.png)

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/commit/a34efc6ade3fb0f05017bf697564aba79fb5d7d2
