### ISSUE TITLE
Forestry worktable crash with crafting GT component

### ISSUE THREAD

**Issue by Ulatirso02** [GTNewHorizons/GT-New-Horizons-Modpack#7209]
#### Which modpack version are you using?
"2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
in a my hosted server with a my second PC
#
#### What did you try to do, and what did you expect to happen?
I tried a craft a LV motor 

#
#### What happened instead? (Attach screenshots if needed)
Crash
[crash-2021-01-01_15.58.41-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5759090/crash-2021-01-01_15.58.41-client.txt)

#

**Comment by mitchej123** [comment]
```
java.lang.NullPointerException: Updating screen events
	at thaumcraft.common.lib.events.EventHandlerWorld.onCrafting(EventHandlerWorld.java:149)
```

Hard to track down exactly what is null in `onCrafting` but these are used without any null check:
1) event.crafting
2) event.player
3) event.player.worldObj
4) event.craftingMatrix
5) A few other random obfuscated calls that I'm too lazy to look up

**Comment by Ulatirso02** [comment]
Hi, i remembered that when I updated the pack it gave me the same problem and I tried to craft a component in a vanilla crafting and then try again in the forestry worktable and that time it didn't crash I tried again today and it didn't crash(sorry for my bad english)
