### ISSUE TITLE
OpenComputers integer overflow with AE

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#7211]
#### Which modpack version are you using?
2.0.1.0
#
If you use the me_interface.getItemsInNetwork() function and an item has > 2^31 items it will loop around so appears some overflow is occuring.

<img width="350" alt="Screenshot 2021-01-01 at 17 18 35" src="https://user-images.githubusercontent.com/54497873/103443289-637d0180-4c55-11eb-9ac9-bb8e283cb935.png">

Negative 630 items being shown since 1,352,914,697,610 / (2^31-1) = 630.

<img width="374" alt="Screenshot 2021-01-01 at 17 18 07" src="https://user-images.githubusercontent.com/54497873/103443276-53652200-4c55-11eb-9779-0bb191758e6b.png">

If this is too much hassle to change then leave it as be but going over 2 billion isn't that hard these days so might be a good shout to fix it if is as easy as changing some value from a regular int to a long.

**Comment by repo-alt** [comment]
Well, I fixed the AE stack conversion, but did not actually test with stacks > 2^23 (not sure how to make one really quick)

**Comment by GTNH-Colen** [comment]
> Well, I fixed the AE stack conversion, but did not actually test with stacks > 2^23 (not sure how to make one really quick)

Do you mean 2^32? And this is how it can be tested easily:

<img width="715" alt="Screenshot 2021-01-01 at 19 09 41" src="https://user-images.githubusercontent.com/54497873/103444853-e8bbe280-4c64-11eb-906b-0fb47aeb70d3.png">

<img width="256" alt="Screenshot 2021-01-01 at 19 10 46" src="https://user-images.githubusercontent.com/54497873/103444865-0e48ec00-4c65-11eb-9a37-f16ef18f4043.png">

<img width="371" alt="Screenshot 2021-01-01 at 19 10 53" src="https://user-images.githubusercontent.com/54497873/103444868-130da000-4c65-11eb-859b-7e73a7f3b6c7.png">

Each item in a creative cell accounts for 2^31 so 2^31 * 63 * 10 = 1,352,914,698,240 as seen.

**Comment by repo-alt** [comment]
ah, ok

**Comment by repo-alt** [comment]
it works
