### ISSUE TITLE
weird lag from fusion reactor

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7213]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta

The fusion was running since days, and suddently it started to lag a lot (55ms of lag)
breaking and replacing the controller fixed it, but here is the warmroast report:
![image](https://user-images.githubusercontent.com/12850933/103444637-7c43e200-4c6a-11eb-8e2e-cedada33b6d9.png)

according to @ScriptedPiky, it happened a couple of times on Zeta too.

**Comment by boubou19** [comment]
Ok so Eta ran into it today with @GTNH-Colen's fusion MKIII. Same warmroast report, but it seems it's lagging very high when only an input hatch is filled (~2E8ns of lag in worse peak) and around ~200000ns when the input hatches are empty.

**Comment by GTNH-Colen** [comment]
The lag seems to increase linearly by a few thousand ns per second, regardless of whether or not the hatch is full or empty. I really have no clue what causes this as the machine is off but the lag just keeps increasing endlessly.
