### ISSUE TITLE
T2 Thermal Cloth Quest has wrong materials

### ISSUE THREAD

**Issue by Teykn** [GTNewHorizons/GT-New-Horizons-Modpack#7214]
#### Which modpack version are you using?
2.0.9.0

#### What did you try to do, and what did you expect to happen?
Was working on the T2 thermal cloth, and thought that i'd only need the 96 titanium foil and tungsten string listed.

#### What happened instead? (Attach screenshots if needed)
The recipe was changed, yet the QB didn't reflect on it. 192 titanium foil and tungsten string are now needed, alongside 96 PBI sheets

#### What do you suggest instead/what changes do you propose?
Change the Quest in order to reflect on the updated recipe in NEI, with it requiring 192 Ti foil, 192 W string, and 96 PBI sheets.

**Comment by glowredman** [comment]
Have you tried updating the pack? Maybe this is fixed by now.

**Comment by Prometheus0000** [comment]
It is
