### ISSUE TITLE
Suggestion: add fluid solidifier recipes for mold plates and extruder plates

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/GT-New-Horizons-Modpack#7216]
#### Which modpack version are you using?
2.1
#
#### What did you try to do, and what did you expect to happen?
i tried to make a mold plate, but realized i had to use a smeltery. and i'm in IV.
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
add a series of recipes that create the molds and extruder plates. 576 L molten steel and the appropriate casting form. prob MV like all the other steel solidification recipes. maybe about 3 seconds ish or about the same as the smeltery at MV imo

**Comment by leagris** [comment]
IMHO it would be a waste of Item ID, recipe map slot and overall game resources because mold plates are not consumables and there is a known finite number of it you will ever need for the whole duration of the game.

**Comment by Prometheus0000** [comment]
It's just a matter of adding alternate recipes for the existing items though?

**Comment by leagris** [comment]
> It's just a matter of adding alternate recipes for the existing items though?

Requires adding a new mold shape for the mold plate.

Maybe we could have a solidifier duplicator that take any single material item as model, input of molten material and duplicate the item using the molten material in matching amount without using a shape but the item itself as a model.

It would be able to duplicate bolts, screws, bars… mold plates whatever is made of a single material that has a molten state and a solid state.

**Comment by boubou19** [comment]
why not add a recipe for the blank cast in the fluid solidifier? then you would solidify the steel on the cast form. That way at Late tiers, you don't need to keep the smeltery in that purpose. But i agree that someone could batch craft all molds/shapes once and then forget about it.

**Comment by GTNH-Afx237v7** [comment]
So it would be necessary to allow fluid extractor to process Tinkers aluminum brass (can currently only be turned into fluid in the smeltery) and fluid solidifier to make the blank cast from Tinkers (probably via configured circuit #1). You can already make aluminum brass ingots in the GT alloy smelter. (All checked with 2.1.0.0).

**Comment by mkrutov** [comment]
>Requires adding a new mold shape for the mold plate.

Can't items which are used for tinker's way of creating molds be reused here?

**Comment by GTNH-Afx237v7** [comment]
Sure, but much easier (since only one recipe) is adding a fluid solidifier recipe to turn molten aluminum brass into a blank cast. From there on, you can continue.

**Comment by Prometheus0000** [comment]
Can you do that with nothing in the machine is the question. If you can't, you need a cast to make the blank cast for it, which need the smeltery anyway.

**Comment by GTNH-Afx237v7** [comment]
Well it is possible to turn liquids into dusts with circuits (e.g. molten ruthenium tetroxide into ruthenium tetroxide dust). Isn’t it just a matter of adding a recipe to the GT fluid solidifier: take molten x + circuit + energy = item y ?

**Comment by GTNH-Afx237v7** [comment]
So I tried adding the following recipes to GT5u:

Fluid extractor turning 1 ingot of Aluminum brass into 144L of molten Aluminum brass
Fluid solidifier turning 144L of molten Aluminum brass into a Tinkers Construct blank cast using a Circuit #1
Below the code, however I cannot get it to work, the GT jar compiles via `gradlew build` but the recipes don't show up (tested with 2.1.04dev).

According to fml-latest.log:
`The fluid TConstruct:aluminumbrass.molten has been selected as the default fluid for aluminumbrass.molten`


```
// Check Tinkers Construct mod is loaded
if (Loader.isModLoaded("TConstruct")) {
  FluidStack moltenAluminumBrass1L = FluidRegistry.getFluidStack("aluminumbrass.molten", 1);
  if (moltenAluminumBrass1L != null) {
     GT_Values.RA.addFluidExtractionRecipe(GT_ModHandler.getModItem("TConstruct", "materials", 1L, 14), GT_Values.NI, FluidRegistry.getFluidStack("TConstruct:aluminumbrass.molten", 144), 10000, 32, 2);
     GT_Values.RA.addFluidSolidifierRecipe(GT_Utility.getIntegratedCircuit(1), FluidRegistry.getFluidStack("TConstruct:aluminumbrass.molten", 144), GT_ModHandler.getModItem("TConstruct", "blankPattern", 1L, 1), 200, 24);	
  }
}
```
Maybe someone else knows how to solve this.

**Comment by GTNH-Afx237v7** [comment]
Heureka! I did it!

![2021-03-03_20 43 52](https://user-images.githubusercontent.com/64365566/109865200-12dd5100-7c64-11eb-8a9f-1ff361aacf3e.png)
![2021-03-03_20 43 41](https://user-images.githubusercontent.com/64365566/109865203-140e7e00-7c64-11eb-87d4-762c80a49192.png)

Fluid extraction will be MV
Fluid solidifying - maybe HV?

**Comment by KorGgenT** [comment]
Imo mv should be good. It doesn't maker sense to me to force using the tc
smelter all the way to hv

**Comment by Prometheus0000** [comment]
@GTNH-Afx237v7 Did you finish this, or...?

**Comment by GTNH-Afx237v7** [comment]
Not yet, but will do so in the next days.

**Comment by GTNH-Afx237v7** [comment]
Coming to a release near you (soon(TM)).

![grafik](https://user-images.githubusercontent.com/64365566/111982771-a7bbc780-8b09-11eb-9c4e-07f59e1407a5.png)

**Comment by GTNH-Afx237v7** [comment]
see https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/164
