### ISSUE TITLE
New transduction amplifier recipe too expensive

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7222]
#### Which modpack version are you using?
2.1.0.0
#
First of all, sorry I missed this in my original review of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6991
#
#### Background
The transduction amplifier is a tool which increases the effective vis of an energised node by 10. So for example, a normal 30 terra node energised makes 5 terra centivis/tick (sqrt30), with a transduction amplifier, it will produce 6cv (sqrt40). 2 more amplifiers can be used on the same node, but will cause it to damage nearby entities and create flux.
This has less of an effect the larger the node is, for example, a 256 vis node will make 16cv, even with 3 transduction amplifiers, it will still only make 16.
So transduction amplifiers are useful in the stages where you are able to jar and energise nodes, but not useful once you have the ability to create large nodes.
Additionally, 4 of them (among other things) are consumed in the creation of a planar vortex.
#
#### Current recipe, as of 2.1.0.0
![image](https://user-images.githubusercontent.com/17787093/103461452-64299c80-4d16-11eb-8840-9c5db6b6c6bb.png)
Thaumium screws
Planar conduit -> Shadowmetal -> Vacuum freezer
Exquisite amber
Node transducer
Redstone alloy plate
Nitor
150 of each vis -> Silverwood+ wand -> Titanium screws
#
#### What do you suggest instead/what changes do you propose?
New recipe
![image](https://user-images.githubusercontent.com/17787093/103461567-3002ab80-4d17-11eb-8bef-ed3e75f348e3.png)
Thaumium screws
Void plate
Flawless amber
Transduction amplifier
Redstone alloy plate
Nitor
50 of each vis

Remove warp from research (It's already behind planar theory and voidmetal, with 1 perm warp each)

**Comment by KiloJoel** [comment]
After discussion:
Instead of changing planar conduit to void plate in this recipe.

Change the recipe of planar conduit to
4x void plate, 4x ender eye plate, 1 primal charm

**Comment by Azemari** [comment]
![image](https://user-images.githubusercontent.com/55991839/103466821-686aaf80-4d40-11eb-8a86-34ba3e29f888.png)
![image](https://user-images.githubusercontent.com/55991839/103466822-77e9f880-4d40-11eb-97aa-b008a9437584.png)

Is this correct?

**Comment by KiloJoel** [comment]
Ah, the planar conduit vis cost also needs to come down. Probably to 50

**Comment by Azemari** [comment]
![image](https://user-images.githubusercontent.com/55991839/103466989-293d5e00-4d42-11eb-89d1-76b24bf9ab00.png)

**Comment by Azemari** [comment]
Here's a link to the pull request: [https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7232#issue-547802710](url)
