### ISSUE TITLE
TecTech Dynamo Hatches not Working with GT Multiblock Generators

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7223]
#### Which modpack version are you using?
2.1.0.0

#
#### What did you try to do, and what did you expect to happen?
I put a 64A LuV Dynamo Hatch onto my Plasma Turbine and I expected it to form

#
#### What happened instead? (Attach screenshots if needed)
It didn't form

#
#### What do you suggest instead/what changes do you propose?
Allow the dynamo hatches to work with generators. If it's a question of balance, I think that would be best addressed through recipe changes rather than outright gating.

**Comment by alphaNOVAircraft** [comment]
That isnt really a bug atm. But it will be fixed soon. Bart is implementing the TecTech structure checks for the gt multis atm. That will allow the hatches to be used. 
But they really need some new recipes then, otherwise the balance will be really broken for some parts. 
Balance for them was already discussed in this issue as well : #6501

**Comment by johnch18** [comment]
I'm annoyed because I spent the last few hours crafting a hatch only to find that I need to craft a 4A ZPM hatch and all that goes with it instead.

**Comment by Prometheus0000** [comment]
> That isnt really a bug atm. But it will be fixed soon. Bart is implementing the TecTech structure checks for the gt multis atm. That will allow the hatches to be used.

I'm not so sure it does? The LSC supports them but doesn't use the TT structure check. Bart might or might not do it at the same time though? Eventually.

**Comment by alphaNOVAircraft** [comment]
Im pretty sure they will be supported, Bart showed it yesterday. 
They still need to be balaneced then again. Bcz otherwise they will be extremly op if they are useable on all the tubines etc. 
(You could run an infinity turbine on LuV 64 Amp hatches......... )

**Comment by Prometheus0000** [comment]
Then he should only add support for the 4A or something. I didn't think it would really be a problem.

**Comment by johnch18** [comment]
> Then he should only add support for the 4A or something. I didn't think it would really be a problem.
Buffered hatches already exist, this would be redundant. I'd rather have expensive 16A/64A recipes than a lack of functionality.

**Comment by mitchej123** [comment]
> > Then he should only add support for the 4A or something. I didn't think it would really be a problem.
> 
> Buffered hatches already exist, this would be redundant. I'd rather have expensive 16A/64A recipes than a lack of functionality.

Or... we let them be used on a higher tier of the generator, instead of upgrading old multi blocks with just one item.  :drevil:

**Comment by Prometheus0000** [comment]
Do they work now with structurelib?

**Comment by Glease** [comment]
No. As the name suggests, it's just a structure definition API, not a full tectech stack.
