### ISSUE TITLE
Random Game Crash

### ISSUE THREAD

**Issue by JackOE3** [GTNewHorizons/GT-New-Horizons-Modpack#7224]
#### Which modpack version are you using? 2.1.0.0

#
#### If in multiplayer; On which server does this happen? Playing single player

#
#### What did you try to do, and what did you expect to happen? I was casually mining ores and my game suddenly closed (was playing in windowed mode if that helps)

Crash log: https://pastebin.com/M1fDpk2H

**Comment by GTNH-Afx237v7** [comment]
Care to explain some more? Were you mining, or looking up sth in NEI? Was the game just about to start, or did it happen after some time?

**Comment by ThePixelbrain** [comment]
The same issue happend to me as well multiple times during mining. When I mine an ore my game crashes occasionally. I'm pretty sure it only happens with small ores, however I'm not fully certain on that one.

I'm also playing on 2.1.0.0 and in singleplayer.

My crashlogs:
https://pastebin.com/uhPXaL26
https://pastebin.com/bZCWSJ2u
https://pastebin.com/VrbPeAtZ
