### ISSUE TITLE
Remove Hiding of Assembly Line Recipes [Feature Suggestion]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7225]
#### What do you suggest instead/what changes do you propose?
Disable the hiding of Assembly Line Recipes in NEI. They're available on the wiki already, and the recipe itself still requires the scan, so it's not going to break progression at all. Allowing people to view recipes will enable them to make more measured decisions as to what they do or do not want to craft.

**Comment by mitchej123** [comment]
Duplicate #7170
