### ISSUE TITLE
RFC: gt output bus/interface combination

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#7226]
add a output bus that connects to ae and when a multi outputs items in it will try to push those items directly in ae
this would be way more tps eff then a output bus + high tier conveyore  + interface

**Comment by repo-alt** [comment]
Well, the logic for the block is not difficult to do, it is kinda (simplified) interface and output bus combined, but there are lots of boring details to mind, depending on which side to implement it. On GT side it would require importing quite a bit of AE internals, on AE side it would affect item and block registration (which is just crazy). In general I think implementing that stuff on GT side looks easier. In any case it would need textures (and id range).

**Comment by repo-alt** [comment]
Bus is implemented (not tested), now it needs a recipe.

**Comment by alphaNOVAircraft** [comment]
![image](https://user-images.githubusercontent.com/29660362/105049940-81c46900-5a6d-11eb-8a34-59cc1b8dbb9c.png)

Rather cheap Recipe Suggestion: 4 EV circuits, 1 IV Output Bus, 2 Acceleration Cards, 2 Interfaces

I think they shouldnt be to expensive, so ppl use them which should posivitly affect tps.

**Comment by Prometheus0000** [comment]
> I think they shouldnt be to expensive, so ppl use them which should posivitly affect tps.

Why an _IV_ output bus then? No one makes above HV for anything other than fusion.

**Comment by Alexdoru** [comment]
Considering this will replace setups of output bus + conveyor (up to UV) + interface, what should be the cost of the block ? Should it have a conveyor in its recipe ? Because if you can use this instead of a UV conveyor it's going to be cheap

**Comment by Prometheus0000** [comment]
Think about when you first make it though. If it's an IV bus (or is too expensive overall), and you're at EV/early IV, that'd be painful to make, yeah? So you might decide not to, and then not do so for a long-ass time, and thus not get the lag savings. I do think having a conveyor in the recipe would be fine though.

**Comment by alphaNOVAircraft** [comment]
> > I think they shouldnt be to expensive, so ppl use them which should posivitly affect tps.
> 
> Why an _IV_ output bus then? No one makes above HV for anything other than fusion.

Maybe you dont have them laying around, but i think they are still not really expensive to make, and i wish there would be use for more of the higher tier hatches / bus. But its a suggestion, so feel free to change that. 

> Considering this will replace setups of output bus + conveyor (up to UV) + interface, what should be the cost of the block ? Should it have a conveyor in its recipe ? Because if you can use this instead of a UV conveyor it's going to be cheap

Compared to a UV Converyer it will have to be cheap or we have to add multiple tiers (which might be a good idea). 
Sure maybe replace the acceleration cards with EV / IV conveyer. I went with Acceleration cards cz some players tend to use import bus before requiring the high speeds, so it felt fair to me.

**Comment by leagris** [comment]
Why limit to UV if you can have the same recipe balanced with matching tier components?

It is not just a player QoL.

It is also a good way to reduce ticking tiles and processing lag on servers.

**Comment by Alexdoru** [comment]
Is this block aimed to replace output bus + interface or output + conveyor + interface or both ? because if it is aimed to replace the output + conveyor + interface considering you actually don't need this kind of setup until late game when you have really fast PA/MEGA EBF we could make it require a high tier conveyor.

**Comment by Prometheus0000** [comment]
I figured it was supposed to be used instead of an output bus as soon as you have AE autocrafting? @repo-alt ?

**Comment by repo-alt** [comment]
A note about the functionality: this bus takes precedence before any conventional bus, so you may also add a usual bus with an item detector on it, and if ever there will be any items in it, then stop the multiblock, because that means ME overflow or energy fault.

**Comment by repo-alt** [comment]
@Prometheus0000 I think it was supposed to be a less laggy superbus replacement, but really, I have no idea about tiering, hence RFC

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/416

**Comment by Glease** [comment]
High tier output bus are not needed because there is no point using it. Arbitrary recipes requiring them doesn't make them anyway more useful. I deem such kind of recipe as worthless towards a smooth and interesting gameplay. I'd rather just simply have it be an assembler recipe with a EV machine hull and a ME interface plus some molten plastic.

**Comment by Alexdoru** [comment]
iirc when you have an output bus and an interface it doesn't cause a lot of CPU load so you can always use that. However at some point when your machine gets faster you are forced to use a high end conveyor on the output bus because the output bus on its own can't output fast enough into the interface and it is the conveyor that is causing a lot of lag. Bot requested this block as a replacement to the output bus + conveyor + interface combo, this way you avoid the lag from the conveyor.

 So to my eyes the recipe of this block should be gated behind a LuV or ZPM conveyor because that's what this block is going to replace.

**Comment by Prometheus0000** [comment]
BTW, should we remove the super bus recipes to _encourage_ people to use it?

**Comment by Alexdoru** [comment]
> BTW, should we remove the super bus recipes to _encourage_ people to use it?

don't remove stuff please, super bus and this have different utility, what if I am doing an automation in a close system without using AE ?

**Comment by repo-alt** [comment]
> > BTW, should we remove the super bus recipes to _encourage_ people to use it?
> 
> don't remove stuff please, super bus and this have different utility, what if I am doing an automation in a close system without using AE ?

Actually, super bus is almost always bad, so idk

**Comment by GTNH-Afx237v7** [comment]
Where do think the break even is, i.e. the consumption of CPU time from bus+conveyor+interface is larger than the new interface? That could be the tiering for the new output bus.

**Comment by repo-alt** [comment]
Always, that much is obvious.

**Comment by GTNH-Afx237v7** [comment]
Not to me, but thanks for clarification. Then it should be low tier based, aka EV/IV.

**Comment by leagris** [comment]
It should not be higher tier or more complicated than crafting all components separately (bus + conveyor + interface).

**Comment by draknyte1** [comment]
> > > BTW, should we remove the super bus recipes to _encourage_ people to use it?
> > 
> > 
> > don't remove stuff please, super bus and this have different utility, what if I am doing an automation in a close system without using AE ?
> 
> Actually, super bus is almost always bad, so idk

Because the code in original buses is bad, Lol. Only difference is slot count and lack of GUI. They’d be less shit inherently if the base code was less shit.

**Comment by repo-alt** [comment]
> > > > BTW, should we remove the super bus recipes to _encourage_ people to use it?
> > > 
> > > 
> > > don't remove stuff please, super bus and this have different utility, what if I am doing an automation in a close system without using AE ?
> > 
> > 
> > Actually, super bus is almost always bad, so idk
> 
> Because the code in original buses is bad, Lol. Only difference is slot count and lack of GUI. They’d be less shit inherently if the base code was less shit.

Yes of course, a lot of GT code is just not scalable.

**Comment by GTNH-Afx237v7** [comment]
> It should not be higher tier or more complicated than crafting all components separately (bus + conveyor + interface).
> 
> I mean the recipe to craft it should be just that ((bus + conveyor OR hatch + pump) + circuit) all three of same tier of the desired (interface bus/hatch) + AE interface

So maybe HV output bus + EV conveyor + AE interface in an EV assembler and soldering alloy to glue it all together. Possibly add a EV/IV tier circuit.

**Comment by botn365** [comment]
i would say HV output bus + ae interface + PE this shoulnd be realy expansif to make

**Comment by Dream-Master** [comment]
Not mixing to uch tier items. I give it a recipe ev with ev components and maybe iv circuit.
