### ISSUE TITLE
Severe issues with earlygame pollution

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7227]
#### Which modpack version are you using?
2.1.0.0
#
#### The problem
So by far the biggest offender here is the railcraft boiler. The tooltip on the firebox says 40 pollution per second, but after testing, it is actually 200 per second per firebox. So for a 3x3 boiler, that's 1800 pollution per second! Clearly this isn't intended, but I think that even 40/s that is intended is too high.

A max size LP boiler produces 7200 steam/s, which equals 153eu/t in lv steam turbines, or 135eu/t in MV ones.
The equivalent pollution for that amount of power generation from gas/combustion (assuming they run constantly) is ~4.5 lv gens = 90/180 pollution/s. So to make the boiler equivalent (not counting coke ovens), it would be 10/20 per firebox.
#
Now taking coke ovens into account. You need around 12 coke ovens to keep up with a max size LP boiler, so currently that's another 240 pollution/s.
In terms of realism, the wood here isn't being burnt, just dehydrated. So a large amount of pollution doesn't really make sense.
#
#### My proposed new pollution numbers (per second)
Coke oven - 3
Solid fueled boiler firebox - 15
Liquid fueled boiler firebox - 10 (Currently no reason to use this, so a nice incentive)
#
This makes 12 coke ovens and a 3x3 boiler 171 pollution per second. Placing it slightly below the 180 from lv combustion gens for the equivalent power. Though in practice, it will generate more because it runs constantly.
It is also in line with the GT boilers:
RC boiler - 7200 steam/135 pollution = 53.3 steam/pollution
Large bronze boiler - 32000 steam/240 pollution = 133.3 steam/pollution
#
#### Side note
I have heard that furnaces are producing too much pollution too, but I don't know enough right now, so I'll leave that for another issue.

**Comment by johnch18** [comment]
Wait, RC multis produce pollution?

**Comment by boubou19** [comment]
in the 2.1.0.0, the fireboxes produce 40 pollution per second, according to the tooltip. I don't know if it's per firebox or per boiler tho.

**Comment by KiloJoel** [comment]
> 
> 
> in the 2.1.0.0, the fireboxes produce 40 pollution per second, according to the tooltip. I don't know if it's per firebox or per boiler tho.
> A complete coke oven produces 20 pollution per second, and a complete advanced coke oven produces 80 pollution per second.

I have tested it, and the tooltip is wrong. They make 200 pollution per firebox per second. Presumably this is a bug.

**Comment by leagris** [comment]
Pollution handling has clearly been out of control for a very clear reason.

Nobody took care of defining pollution, what its intended role was and now every contributor add code for what they feel like ok about their own gauge and definition of pollution.

Pollution cannot be fixed by changing gauges here and there, because of the above reason.

I’ll prepare a spec sheet RFC for pollution rework so we are able to all agree on stable definition, what we expect from it with arguments and only then we can expect implementations to matche definitions and expectations.

**Comment by johnch18** [comment]
I only ever craft LV mufflers because it's super easy to ignore pollution entirely, the entire mechanic is kind of meh.

**Comment by Teykn** [comment]
There definitely SHOULD be consequences for pollution. I think the motivation for making pollution something players should worry about more is misplaced.

I agree that the pollution in those should be dropped. The fact that you produce more pollution in the steam age than you do in the early electrical ages is highly non-realistic.

As for mufflers, I feel that pollution should **cause maintenance issues**, with better mufflers reducing maintenance issue chance from pollution. That should promote peeps to upgrade their mufflers and reduce their pollution.

**Comment by Anarack** [comment]
In almost every case GT boilers beat out railcraft boilers in terms of efficiency and output rate, so not sure why they should have even worse pollution as well when you are already encouraged not to use them from a power perspective.

**Comment by KiloJoel** [comment]
Pull request ready: https://github.com/GTNewHorizons/ModMixins/pull/5

**Comment by KiloJoel** [comment]
After some discussion and compromise with dream. The new values are currently going to be
20/s per firebox
10/s per coke oven

We now have config for these values, so they are easy to change in the future if more discussion arises.
