### ISSUE TITLE
bisphenol A recipe does not have water as output in LCR

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7228]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
was looking inside the Bisphenol A recipe, expected to have the same outputs in the chemical reactor and the LCR
#
#### What happened instead? (Attach screenshots if needed)
The LCR does not ouput water:
![image](https://user-images.githubusercontent.com/12850933/103464734-4704c600-4d36-11eb-9c32-1f2060100a3f.png)

single block recipe:
![image](https://user-images.githubusercontent.com/12850933/103464739-584dd280-4d36-11eb-8ca8-65f2a640c3e4.png)

#
#### What do you suggest instead/what changes do you propose?
Add water as output for the LCR

**Comment by johnch18** [comment]
Ah yes more excess water please yes.

**Comment by boubou19** [comment]
it's more for consistency's sake, it's really easy to void anyways.
