### ISSUE TITLE
Something is wrong about 2.1.0.0 MMC Download.

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#7233]
#### Which modpack version are you using?
2.1.0.0

I realized that 2.1.0.0 MMC download includes IV loot at ross128b in bartworks config. I did check it from technic launcher and it looks fine. Bartworks config may not be the only wrong thing in MMC download.
Also my double layer forestry multifarm works in 2.1.0.0 which shouldn't work. But I am not sure if it is also an issue of the MMC download.

**Comment by Prometheus0000** [comment]
Remove when next release is ready.

**Comment by Prometheus0000** [comment]
It doesn't seem like anyone's going to fix this, so...
