### ISSUE TITLE
Missing one of the Nitric Acid recipe in single block chemical reactor

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#7237]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Searching in NEI for Nitric acid recipe
#
#### What happened instead? (Attach screenshots if needed)
I found this recipe : 
![image](https://user-images.githubusercontent.com/62377720/103490554-f025ec00-4e1c-11eb-8801-04ef0691bdd2.png)
And it appears that this recipe is not available in a normal chemical reactor, to make either a cell or the fluid.
#
#### What do you suggest instead/what changes do you propose?
This seems to not beeing gated by a specific tier because as I can see it's LV, so I don't understand why this is not available in the single block chemical reactor and I just suggest to add the recipe

**Comment by alphaNOVAircraft** [comment]
Did you ask if other ppl on the server dont see the recipe as well? Not being able to make nitric acide pre lrc would be a serious issue.

**Comment by boubou19** [comment]
The nitric acid is possible, it's just that the route Nicouuuuu is displaying isn't in the singleblock version. (looked for the cell recipes and for the fluid recipes).

**Comment by Glease** [comment]
LCR got a few "shortcut" recipes that is the combination of multiple reaction steps. AFAIK this is the intended behavior.

**Comment by mitchej123** [comment]
Anything with circuit 24 doesn't have an equivalent single block recipe.

**Comment by Nicouuuuu** [comment]
> LCR got a few "shortcut" recipes that is the combination of multiple reaction steps. AFAIK this is the intended behavior.

Okay I didn't know that thanks for the information
