### ISSUE TITLE
Digger & Miner's Backpack recipe not showing item in crafting table

### ISSUE THREAD

**Issue by JoHgamer** [GTNewHorizons/GT-New-Horizons-Modpack#7239]
#### Which modpack version are you using?
2.1.0.0-MMC
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
When trying to craft the Digger or Miner's Backpack for the "Need more space" quest in the crafting table, the finished item doesn't show up. The recipe shows only two recipes were the first one you need 2 woven cotton, 2 stone blocks, and 5 leather, and the second recipe is the Digger/Miner backpack itself. Is their a workaround?
#

**Comment by bedrill64** [comment]
Take a note that recipe is not 5 leathers, but 4 leathers and 1 tanned leather, check this bit and report.

**Comment by JoHgamer** [comment]
Sorry for very late response. You were right it was 4 leather and 1 tanned leather.
