### ISSUE TITLE
Mutton and calamari inconsistent drop rates

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7240]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Eta, another forge server
#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
Multiple reports of very low drop rates (<10% with looting 3) on mutton and calamari, but also normal drop rates in singleplayer. Needs more investigation.
The main issue is quest 482 requires 100 mutton
#
#### What do you suggest instead/what changes do you propose?
Either investigate and fix drop rates or remove mutton requirement from the quest.

**Comment by Prometheus0000** [comment]
Edited quest, but issue not resolved.
