### ISSUE TITLE
Slice'n'Splice IO incorrectly auto-fills slots

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7242]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Put a chest next to Slice'n'Splice machine, put ingredients in the chest, set up machine IO to input/output to/from the chest
Machine correctly placed soularium plates and zombie head, but misplaced silicon plates and ignored red alloy plates
![image](https://user-images.githubusercontent.com/23512002/103539758-a7684480-4ea9-11eb-9fae-efd8e06461eb.png)

Since there is no recipe with silicon plates in 4 and 5 slots simultaneously, I think this is a bug, and I remember this working correctly some (considerable) time ago.

**Comment by repo-alt** [comment]
Note that if the red alloy plates are placed in the ingredients chest earlier than silicon then it work correctly

**Comment by q009** [comment]
I saw it happen as well.

**Comment by DualBallers** [comment]
It is also still possible to have an interface connected directly to the Splice'n'Slice, as long as the components are listed in a specific order in the crafting pattern.

**Comment by OrderedSet86** [comment]
Can confirm still an issue in 2.1.2.1

**Comment by AnrDaemon** [comment]
It seems to become worse in the latest EnderIO releases.
Interface does not push items at all to the machine. No matter the interface or machine side configuration.

Will update with a/b testing in a day.
