### ISSUE TITLE
Can't craft Electric Hoe - missing Steel hoe head recipe

### ISSUE THREAD

**Issue by ko5h** [GTNewHorizons/GT-New-Horizons-Modpack#7244]
#### Which modpack version are you using?
2100
![img](https://i.imgur.com/bOGRGGg.png)
#
#### What do you suggest instead/what changes do you propose?
mb replace GT head to vanilla hoe (diamond or gold etc)?

**Comment by Dream-Master** [comment]
fixed in dev version.

**Comment by lobiita24** [comment]
pero cual es el crafteo ?

**Comment by Prometheus0000** [comment]
Use english.
