### ISSUE TITLE
Recipe for Cherry Wood Fence doesn't work

### ISSUE THREAD

**Issue by ryankhart** [GTNewHorizons/GT-New-Horizons-Modpack#7250]
#### Which modpack version are you using?
2.1.0
#
#### If in multiplayer; On which server does this happen? 
Locally hosted server
#
#### What did you try to do, and what did you expect to happen?
I tried to do as NEI told me I could do and make a fence using cherry wood planks
#
#### What happened instead? (Attach screenshots if needed)
It doesn't do anything. See screenshot here:
![image](https://user-images.githubusercontent.com/3673962/103660567-97d91200-4f22-11eb-885d-57bbff673419.png)
#
#### What do you suggest instead/what changes do you propose?
I would suggest to match the actual recipe with what NEI says the recipe is.

**Comment by boubou19** [comment]
might be related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7307
