### ISSUE TITLE
Ardite Dust(Tinkers Version) - replace with GT version

### ISSUE THREAD

**Issue by braeven** [GTNewHorizons/GT-New-Horizons-Modpack#7251]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
Epsilon

#
#### What did you try to do, and what did you expect to happen?
Ore Drilling Plant 2(Probably other drills will do this too) now finally break Tinkers Ores, but it produces Tinkers Ardite Dust instead of GT-Ardite Dust. Not really a problem, but you need to convert(make small dusts and back into normal Dust) the Dust to use it. Tinkers Dust can not be used in a lot of machine recipes. Strangely it does not happen with cobalt ore from Tinkers.

Also happens with Macerators, they produce Tinkers Dust.
#
#### What do you suggest instead/what changes do you propose?
Auto-Replace Tinkers Ardite Dust with GT one
Most Dusts get auto-converted in Inventory, but this also does not happen with Ardite.

**Comment by GTNH-Afx237v7** [comment]
As of 2.1.0.5 you also get two variants of cobalt from a multiblock miner.
![grafik](https://user-images.githubusercontent.com/64365566/114280342-1620e500-9a39-11eb-85e5-3a81cf80e8b5.png)
Left is GT Cobalt (Shared ItemStack between bartworks and Gregtech), right is Tinkers cobalt (Shared ItemStack between Bartworks and Tinkers Construct).
So an automatic unification of both dusts would be much appreciated.
