### ISSUE TITLE
Uranium 238 Vein/Plutonium 341

### ISSUE THREAD

**Issue by braeven** [GTNewHorizons/GT-New-Horizons-Modpack#7252]
#### Which modpack version are you using?
2.1.0.0
#

#### What did you try to do, and what did you expect to happen?
I would like to propose to change something on the Ore Generation:
Currently the Uranium 238 Vein is the only source for people to get Plutonium 241(out of the Plutonium 239) if they are not using Reactors, but it's really rare to find on T3 Planets:
it only has a weight of 5 and generates above 65(height 65-120)
it currently spawns on Callisto, Ceres, Ganymede and Io(T4).

I just searched on Epsilon for 2 veins on Callisto, I prospected around 1100 Veins to find 2 partly not generated veins.
it should be around a 1% chance for a Vein to be generated on Callisto(80 Chalco + 120 Limo + 160 Magni + 10 Scheelite + 16 Ilmenite + 30 Bastnasite + 10 Platinum + 40 Callisto Ice + 5 Uranium -> 471, Uranium itself has a weight 5 -> (5/471)*100 ->  1.06%), so mathematically I should have found  around10 Veins(I know GT-Generation works a little different).

The T3 planets tend to have a rough Terain, with some high Mountains, deep Holes and a "sealevel" around 60 and not much area for this vein to be generated.

#
#### What do you suggest instead/what changes do you propose?
I would like to propose to lower the minimum height from 65 to 55. This might not be much, but I think it will be enough to let the vein generate a little more often and give the players more access to plutonium related stuff, that are not using Reactors

**Comment by johnch18** [comment]
In my playthrough I very quickly had more 241 than 239, so I don't think this is the biggest problem

**Comment by Glease** [comment]
Voiding half the vein is quite frustrating though.

**Comment by repo-alt** [comment]
I think it is just an oversight in the first place.

**Comment by repo-alt** [comment]
Where are those veins defined?

**Comment by Glease** [comment]
Both in [source code](https://github.com/GTNewHorizons/GT5-Unofficial/blob/c99a6e14495c82f6022e8676b412a37775af85f6/src/main/java/gregtech/loaders/postload/GT_Worldgenloader.java#L202) and [config](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/422b5b7762d68c20e3a9afacb8c3143c946786e7/config/GregTech/WorldGeneration.cfg#L773-L778). Probably we could just add a line in the config to override the height.

**Comment by johnch18** [comment]
Pu-239 and U-238 is still useful for radon production, and Pu-241 is useful for T3 fusion stuff.

**Comment by repo-alt** [comment]
This should really be fixed, if not already
