### ISSUE TITLE
SFM replace Ammonium chloride into Blood

### ISSUE THREAD

**Issue by Vernam** [GTNewHorizons/GT-New-Horizons-Modpack#7253]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Mp, local 
#
#### What did you try to do, and what did you expect to happen?
tried to automate Platinum processing with SFM
#
#### What happened instead? (Attach screenshots if needed)
When i want to add Ammonium Chloride into liquid input or output - SFM changes Ammonium Chloride into Blood
#
#### What do you suggest instead/what changes do you propose?
I hope to see some fix somehow, it's not very funny to automate platinum without SFM

**Comment by boubou19** [comment]
is what happens as described in #5646 ?

**Comment by Prometheus0000** [comment]
Also, duplicate

**Comment by Vernam** [comment]
lol, "duplicate",  but the date of the previous one is a year ago...

**Comment by Prometheus0000** [comment]
So? There's already a possible fix, go test it

**Comment by Vernam** [comment]
Yes, sorry, just looked.
