### ISSUE TITLE
Error spam in logs

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7254]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
I looked at my latest.log and found this error spammed in it. Doesn't result in a crash, but I assume it's causing a lot of client lag handling them.
![image](https://user-images.githubusercontent.com/17787093/103711672-d49f1a80-4faf-11eb-9096-fb575e2b715b.png)
Same thing as text: https://pastebin.com/LXYY7G26
#
#### What do you suggest instead/what changes do you propose?
See if it's possible to fix it

**Comment by Prometheus0000** [comment]
MiscUtils is GT++ right?

**Comment by KiloJoel** [comment]
Just remove the overchanter and checked again and another thing is spamming the same error, so it doesn't seem to be related to the overchanter specifically, nor MiscUtils by the looks of it
![image](https://user-images.githubusercontent.com/17787093/103733689-38423b80-4fe2-11eb-8668-994e0d7c7399.png)

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/103734167-67908280-4fb9-11eb-82bd-f1eafca8b5c2.png)
Might be an EMT essentia generator

**Comment by KiloJoel** [comment]
Ah it's actually the same error that was crashing me in singleplayer: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7204

**Comment by KiloJoel** [comment]
This issue is triggered by calling SimpleNetworkWrapper::sendToAllAround or similar methods from the clientside. The essentia generator instance is fixed by https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/19 but other instances still exist.
Ideally this would be patched in forge itself, but I am not sure how to do that.
