### ISSUE TITLE
Chest buffer doesn't require energy to work

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7257]
#### Which modpack version are you using?
GTNH 2.1.0.1
#

So now chest buffers don't require energy to work and they also sort their inventory without energy. Is it a normal considering the tooltip says it requires energy to work ? Either way there is something to change, either the tooltip or the behavior.

**Comment by Prometheus0000** [comment]
This might've been removed along with covers not needing EU anymore, but the TT didn't change? Or is it just the later tiers not working right again?

**Comment by Alexdoru** [comment]
All tiers are working without energy and the tooltip is unchanged. And the tooltip says the machine requiers energy to work whereas in reality it doesn't.
 Is it collateral damage from the update on covers or is it intended ?

**Comment by KiloJoel** [comment]
I believe the reason chest buffers ever required EU is because all machines cost a small amount of EU to output items. So when this was removed, it removed the cost here too.

**Comment by GTNH-Afx237v7** [comment]
Assume this is the same then for superbuffers?

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/406
