### ISSUE TITLE
Items need to be inserted into item pipes after long distance pipe transportation 

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#7259]
The output end of the LDP does not allow item pipes to connect, and currently be inserted into a buffer chest before inserting into item pipes.

![image](https://user-images.githubusercontent.com/1894689/103922269-5e420b80-50c8-11eb-98bf-ab12157abc11.png)

**Comment by Prometheus0000** [comment]
@mitchej123 Was this fixed?

**Comment by Prometheus0000** [comment]
Insert pipe will not connect unless there's an inventory on the other side (pipe/chest)
![image](https://user-images.githubusercontent.com/8517039/118408609-597ffc00-b654-11eb-8fec-352562f39c35.png)
Output pipe will not visibly connect no matter what, you also need another conveyor to get the item out of the pipe
![image](https://user-images.githubusercontent.com/8517039/118408750-de6b1580-b654-11eb-94b1-82908e032b3f.png)
This will not send items
![image](https://user-images.githubusercontent.com/8517039/118408817-268a3800-b655-11eb-8c1b-2b7d03f3ac24.png)
But this will
![image](https://user-images.githubusercontent.com/8517039/118408830-31dd6380-b655-11eb-8b2f-9943562b500c.png)

They don't work with item conduits at all.
Fluid ones work fine with pipes and conduits.

@mitchej123

**Comment by Glease** [comment]
Let's push this back to next milestone, since mitch seems to be busy working on something else right now.

**Comment by ahmetsad** [comment]
also they don't output to input buses even though they have inventory.
