### ISSUE TITLE
Slime trees grow to eat blocks

### ISSUE THREAD

**Issue by Shadowsoftime99** [GTNewHorizons/GT-New-Horizons-Modpack#7260]
#### Which modpack version are you using?

2.1.0.0 (latest)

#### If in multiplayer; On which server does this happen? 

A private server

#### What did you try to do, and what did you expect to happen?

I let a Slime Tree grow, and expected it to either not grow or have its leaves not appear in spaces where other blocks were

#### What happened instead? (Attach screenshots if needed)

A nearby chest is gone, just got eaten by the Slime Leaves. Contents voided too (rip my saplings)

#### What do you suggest instead/what changes do you propose?

The book mentions this effect for Canopy Trees, but doesn't seem to for Slime Trees. At the very least some mention of it would be nice, though it seems like this shouldn't happen at all for Slime Trees.

**Comment by Devtron3D** [comment]
Yeah that happens in tree farms too, leaves will eat the ground, stone, obsidian, or bedrock

**Comment by boubou19** [comment]
yes, not sure what we can do here, as it happens even with vanilla trees sometimes.
