### ISSUE TITLE
GT++ Backpack Dupe Bug

### ISSUE THREAD

**Issue by Karpouzas12** [GTNewHorizons/GT-New-Horizons-Modpack#7262]
#### Which modpack version are you using?
v2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
gt.craftersland.net
#
#### What did you try to do, and what did you expect to happen?
I placed something in the backpack, closed it and then pressed right click and Q simultaneously.
I expected for the backpack to drop on the ground.
#
#### What happened instead? (Attach screenshots if needed)
The backpack dropped but it's inventory stayed open so I took the item inside the backpack and then picked the backpack from the floor, but the item was still in it so I got 2 copies of the same item.
#
#### What do you suggest instead/what changes do you propose?
Remove the backpack from the modpack or fix the issue somehow.

https://user-images.githubusercontent.com/77125399/103943263-718dbf00-513a-11eb-8a80-91132d8833f0.mp4

**Comment by Ethryan** [comment]
I thought the GT++ backpacks was disabled in this modpack, i can't find any crafting recipe for them.

**Comment by Dream-Master** [comment]
@Karpouzas12 why closed ?

**Comment by Karpouzas12** [comment]
@Dream-Master Because they are disabled anyway and you can only get them in creative
