### ISSUE TITLE
EBF-Time Quest text clarification on Heat Capacity Levels

### ISSUE THREAD

**Issue by r2go-beep** [GTNewHorizons/GT-New-Horizons-Modpack#7263]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
I went through the quest trying to make an MV energy hatch which required Monocrystalline Silicon Boules which to craft require a heat capacity of 1784K. I assumed the EBF with Coup Coils and 2 LV energy hatches are capped at 1701K as the quest EBF-Time states that energy hatches in LV are -100k. 

I expected my EBF to be 1700k. Cheating in a portable scanner to see if EBF progression was broken (as there would be no way to create kantal coils as they also required 1800k).
#
#### What happened instead? (Attach screenshots if needed)
I noticed my EBF is indeed 1800k as it has 2 LV energy hatches equaling 64eu/t(*2A) which is MV level. Removing 1 LV energy Hatch resulted in LV power levels (aka -100k).
https://cdn.discordapp.com/attachments/234936569360809996/796837160519073812/unknown.png
#
#### What do you suggest instead/what changes do you propose?
Add to the EBF-Time Quest Text to state "Having only 1(ONE) LV energy hatch means there is a maximum input of 32EU/t(*2A), which is LV energy tier and reduced by 100k making the heat capacity 1701K. You should make 2 LV energy hatches which is a maximum input of 64EU/t(*2A), which is MV energy tier making the heat capacity of 1800K! Aka no penalty for you.

**Comment by GTNH-Afx237v7** [comment]
Here is the original issue: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6555.

I believe what the questbook is telling you is that the coils will have an added bonus, but not that the minimum coil temp as indicated in the tooltip can only be reached with a certain voltage.
So the coil temp in the tooltip is the lowest temp the coils will reach, with the „hidden bonus“ of +100K above MV.

**Comment by Prometheus0000** [comment]
I can't understand the problem you have with the text. It's completely accurate as far as I can tell?

The boules require both the 1801K _and_ the MV power level. You can get this with 2 hatches of LV, or 1 of MV with the initial coils.

**Comment by r2go-beep** [comment]
I understood the quest text as using LV energy hatch's = no bonus, however using two hatches makes it an MV power level(which wasn't implied). Its not a big issue, I was interpreting the quest book text differently. Feel free to close.
