### ISSUE TITLE
Feature request - Here we go questing again.  

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#7264]
I would like a way to start from scratch on the same server, that would require a quest book reset.
The problem is at some point I want to go back to my high-tier base and progress there, and if I reset my quests I cant follow the quest book anymore.

I have talked to a few that play this pack, and they do the same thing I do from time to time. We server hop, as to play some parts of the pack again, either see how fast we can get to say LV or HV, kinda speed run the pack.

My problem is, once you find a good server and have a large base, I don't want to leave. But I also do not want to reset my quest progression to speed run the start again, so I start on another server to speed run to MV in a weekend.

Is it possible to implement a way for players to have one or more quest book progressions, so they have one main book they follow and say a secondary book, that they can reset at will?

**Comment by Prometheus0000** [comment]
You'd have to have an entirely separate file for redoing the quests, assuming it was coded in. And it would have to disable rewards for quests to prevent cheating (or save every single one you previously got), but this would screw you over later for d cores, garden/void choice, maybe others. I really don't think it would be worth the annoyance of coding it personally.

**Comment by KiloJoel** [comment]
I think the logistics of having multiple quest progressions going at once, while doable, would be a bit messy. Personally what I would be happy with is essentially the equivalent of asking an admin to delete your player files, except without the admin.

**Comment by Prometheus0000** [comment]
That would just be be bq_admin reset all <player>, but not allowing you to get the quest rewards again. Or do, if it's deemed ok.

**Comment by Devtron3D** [comment]
Why not get the quest rewards again.
The coins I could kinda understand, but I am ZPM atm, and I have not used coins since LV / HV if I remember correctly, so from that point of view It would not matter if I got them again.

Item wise, just off the top of my head, the only quest reward I can think of that might cause issues, is the void / garden / specter key items, as well as thaumcraft research.

If this was meant for a speed run kinda situation or even just going through the start of the game again. Why not make the coins and items only appear if the main quest progression had reached say IV, so when you unlock IV you gain access to the progression from beginning again part. 

I mean If you look at it from a cheating perspective and you already have an IV base on the same server, the coins to get some rubber, steel, circuit boards, should not matter in the grand scheme of things, as you could run to your main base to get that if you wanted to "cheat" the progression faster. Getting those extra coins from steam/lv/mv/hv would not matter.

**Comment by Prometheus0000** [comment]
Depends on how much coding someone is willing to do.

I'd just allow players to use the command on themself and call it a day, but I don't know if you can specify it that way. If not, putting it in the menu is possible too.
