### ISSUE TITLE
Adventure backpack 'bat'

### ISSUE THREAD

**Issue by anoldshoe** [GTNewHorizons/GT-New-Horizons-Modpack#7266]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
gtnh.moddedminecraft.club
#
#### What did you try to do, and what did you expect to happen?
Craft adventure backpack: bat (4345:2)
#
#### What happened instead? (Attach screenshots if needed)
crashes client
#

**Comment by alphaNOVAircraft** [comment]
Can you post a Crashlog?

**Comment by Yakameen** [comment]
@anoldshoe Yes, please post the crash log, I just crafted one and could not replicate the crash...

**Comment by Florexiz** [comment]
Same happens on eta with squid backpack (most likely with every backpack)
[crash-2021-01-11_13.25.01-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5795146/crash-2021-01-11_13.25.01-client.txt)

**Comment by Yakameen** [comment]
What was in the backpack when the crash happened?

**Comment by Yakameen** [comment]
Fixed with https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7299
Recommend Closing. Thank you @Florexiz for providing that crash report.
