### ISSUE TITLE
Missing capactitors in quest 1225 : IV Circuit Mainframe

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#7269]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta
# 

Here is one of the craft of the IV Circuit Mainframe : 
![image](https://user-images.githubusercontent.com/62377720/104000449-8a2fc080-519e-11eb-80be-bb518594b91d.png)
Here is now the quest requirements : 
![image](https://user-images.githubusercontent.com/62377720/104000497-9fa4ea80-519e-11eb-949f-dec7bc44cc89.png)

#### What do you suggest instead/what changes do you propose?
As you can see the capacitors are missing in the requirements, I suggest to add them either on the SMD or the normal version 
maybe the SMD would be better regarding to the recipe not that much difficult in HV

**Comment by bedrill64** [comment]
![image](https://user-images.githubusercontent.com/9555787/104001211-9d8f5b80-519f-11eb-961d-cd74c7403cdb.png)

Read the quests ppl. Quest already mentions that.

**Comment by Nicouuuuu** [comment]
Why not putting that into the requirements direclty ? it splits stuff for nothing imo

**Comment by GTNH-Afx237v7** [comment]
There are various ways to make capacitors, so it’s better to not put them into the actual requirements.

**Comment by Prometheus0000** [comment]
There was already an issue about removing them, I'm not putting them back in. Learn to read.

**Comment by Nicouuuuu** [comment]
Okay  I understand, I didn't know it was already an issue, you don't need to be arrogant though Prometheus 😄

**Comment by Prometheus0000** [comment]
It's just there's a lot of people who ask questions that are answered by the quests, so I get kinda frustrated. Like asking about rocket fuels.

**Comment by Nicouuuuu** [comment]
Ye I can imagine ... 
I wish you to be brave with all of that and sorry to bother
