### ISSUE TITLE
Quests requiring specific tiers of machines should work with any tier of machine.

### ISSUE THREAD

**Issue by PPKFS** [GTNewHorizons/GT-New-Horizons-Modpack#7271]
#### Which modpack version are you using?
2.1.0.0
#

#### What did you try to do, and what did you expect to happen?
Some quests require certain tiers of machine, but often those machines are unnecessary. This means the player may have to craft unnecessary, lower tier machines to ensure they aren't missing off quests.

Due to the hidden nature of the questbook, it's often confusing if these quests are necessary. For example, I had to build an LV extruder (which the questbook explicitly says is fairly useless) to unlock the crossbow quest progression, despite having an MV extruder.
Examples include:
Passive Chunkloading, Spade, Super Chest - MV Bending Machine
Glowstone centrifuging - MV centrifuge
Concrete - MV fluid solidifier
Magnalium, crossbows - LV extruder
#

#### What do you suggest instead/what changes do you propose?
Change quest prerequisites for quests that are not essential, but locked behind specific tier machines to be unlocked by having any tier or above of the machine quest. e.g. the crossbow quest line having prereqs of OR: LV extruder, MV extruder, HV extruder.

**Comment by Prometheus0000** [comment]
This would require an OR of every tier. And not allow any components in the quest. There's no easy way to do this, so no.
