### ISSUE TITLE
Active Transformers (Possibly other controllers) fail to receive energy from input hatches

### ISSUE THREAD

**Issue by S4mpsa** [GTNewHorizons/GT-New-Horizons-Modpack#7274]
#### Which modpack version are you using?
2.1.0.2a
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/69092953/104067361-b2093d80-520b-11eb-8ff6-3f16e5e9b2bb.png)
![image](https://user-images.githubusercontent.com/69092953/104067374-bafa0f00-520b-11eb-977d-12e7a4ca513d.png)

The controller doesn't fill the internal buffer from the input hatches, which causes the transformer to stop working.
This setup worked fine before the newest update. Happens with all Active Transformers, doesn't seem to happen with the Data Bank as a reference (Not 100% sure, didn't have energy to check for sure due to this bug)
@bartimaeusnek 
@Technus 
@basdxz 
![image](https://user-images.githubusercontent.com/69092953/104067593-17f5c500-520c-11eb-98c2-8c280a96df5a.png)

**Comment by Dream-Master** [comment]
http://jenkins.usrv.eu:8080/job/Tec%20Tech/612/ not fixing it @Technus

**Comment by S4mpsa** [comment]
From toying around, it seems laser hatches are the problem.
Laser target hatches cannot be extracted from, and laser source hatches are not filled by the controller. Normal multi-amp hatches work as expected.

**Comment by Technus** [comment]
Well spotted. That is the case, using amp of hatch for computation while lasers use 0 amps (cause they are not really enet things)

Changed laser hatch logic, they report amps now but are not enet IO
