### ISSUE TITLE
[Suggestion] Remove Passive Anchors smelting Recipe

### ISSUE THREAD

**Issue by Azemari** [GTNewHorizons/GT-New-Horizons-Modpack#7275]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Break Passive anchor with a pickaxe with Auto-smelt. Expected to receive a passive anchor. Received 2 obsidian.
#
#### What happened instead? (Attach screenshots if needed)
The pickaxe smelted down the passive anchor 
![image](https://user-images.githubusercontent.com/55991839/104075276-2f33b300-520a-11eb-95ea-fe978d253be6.png)

#
#### What do you suggest instead/what changes do you propose?
Remove the recipe so that when you break it with a pickaxe you don't get 2 obsidian.

**Comment by Prometheus0000** [comment]
This would require ASMing RC, and is probably not worth it.
