### ISSUE TITLE
Add Ore Dictionary tags to ore byproducts corresponding to what machines can process them [Feature Suggestion]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7277]
Adding ore dictionary entries such as "siftable", "electrolyzable", "centrifugable", etc., to ore byproducts and dusts would allow significant streamlining of many automations for players and would improve the overall experience.

**Comment by leagris** [comment]
It could also ease selection for recipe maps.
I propose to choose a dedicated prefix to better distinguish with other oredict entries
- procSift
- procElectrolze
- procCentrigue
- procThermalCentrifuge
- procMagneticSepar
- procCrush
- procSmelt
- procBlastSmelt
- procChemicalReact

Another alternative would be to add a new filter machine that filters items based on the processing/machine type. The processing filter would be tuned to a given machine, so it checks if item exist as an ingredient for the corresponding machine's recipe map.

**Comment by boubou19** [comment]
how hard it is to add new oredict entries to the items based on machine's recipemap? Will it slow down the pack loading significantly? Because i feel like iterating on the smelting recipe map will be the slowest one.

**Comment by leagris** [comment]
> Because i feel like iterating on the smelting recipe map will be the slowest one.

This is implementations details, but I see no reason why it should necessarily be slower than searching corresponding ore dictionary entries.

Also consider that adding a procProcessName for every process/machine, is going to clobber tooltips significantly for some items. An iron ingot would have:
- procSmelt
- procArcFurnace
- procAlloy
- procBlastFurance
- procMelt
- procRoll
- procHammer
- procGrind
- procExtrude
- procLath

I am worried about hard to read tooltip spanning more then screen height.

**Comment by boubou19** [comment]
what about restricting it to some machines like the ones restricted in the ore treatment (thermal centrifuge/centrifuge/electrolyzer/sifter) ? because those are the ones which are painful to filter manually. IMO, the others don't need such filters as the pack has various ways to deal with them.

**Comment by leagris** [comment]
I am not very found of using the Ore Dictionary at all for this purpose. Newer versions of forge it seems have a tagging system instead that sound more appropriate, but here in 1.7.10 there is not.

So you are asking for ways to route items based on their process, but only for ores and ores by-products.

This would be so cool if there was a dedicated RecipeFilter block with a very similar working as the TypeFilter.

How it could work:

User select the machine/recipe in the GUI (same kind of cycling button as the TypeFilter)

The RecipeFilter switches to a fast lookup hashSet (or whatever data structure has the cheapest lookup) of the ingredients for the selected recipe.

Only items which are known ingredients fore the recipe would pass through the RecipeFilter.

**Comment by johnch18** [comment]
I specified ore processing because I can understand the issue with the tooltip.

**Comment by leagris** [comment]
@johnch18 would you agree to list the process that need a selector switch?

I mean I can see oilsands needing an extraction rather than grinding. But what other ore or ore by-product would be candidate for such oreDictionary processing tags? (that could not be sorted-out by other mean or criteria)?

**Comment by johnch18** [comment]
> @johnch18 would you agree to list the processes, ores and by-products that need a selector switch?
> 
> I mean I can see oilsands needing an extraction rather than grinding. But what other ore or ore by-product would be candidate for such oreDictionary processing tags? (that could not be sorted-out by other mean or criteria)?

The most pressing thing for me personally is sifting, as it's difficult to filter siftables from other purified ore.

**Comment by leagris** [comment]
So the most meaningful oredictionary tagging would be the material type.

Could be one of the dictionary tag with `mat` prefixing the material type:
- matDiamond
- matDull
- matEmerald
- matFiery
- matFine
- matFlint
- matFluid
- matGem_horizontal
- matGem_vertical
- matGlass
- matLapis
- matLeaf
- matLignite
- matMagnetic
- matMetallic
- matNetherstar
- matNone
- matOpal
- matPaper
- matPowder
- matQuartz
- matRough
- matRuby
- matSand
- matShards
- matShiny
- matWood

These tags would tell quite precisely what kind of process is to be used at each stage of ore and by-products processing.

It also means a Material Type Filter machine could be added to Gregtech to provide a logistic sorting mechanism for Gregtech without depending on inefficient regex match on oreDictionary name from EC2.

**Comment by Prometheus0000** [comment]
Can't you tell the material from the ore though? Isn't it just the ```mat``` instead of ```ore``` prefix? What's the point?

**Comment by leagris** [comment]
> Can't you tell the material from the ore though? Isn't it just the `mat` instead of `ore` prefix? What's the point?

It is the material type.

The main idea is to allow filtering items (*and possibly fluids*), based on their material's properties, preferably without having to make guesses from main ore dictionary name.

Once you get an item/fluid's material, it is a matter of querying the material's properties and filter on these.

Some possibilities (not exhaustive, not implementation specific):
- Filtering items based on the [material's SubTags](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/enums/SubTag.java)
- Filtering items based on the material's properties getters:
  - `isRadioactive()`
  - `getSolid(1) != null`
  - `getFluid(1) != null`
  - `getGas(1) != null`
  - `getPlasma(1) != null`
  - `getMolten(1) != null`
  - `hasCorrespondingFluid()`
  - `hasCorrespondingGas()`
  - `canBeCracked()`
  - ...

**Comment by bartimaeusnek** [comment]
I'll add a Specalised Filter Multiblock. That should do it.

**Comment by SteamDoge9000** [comment]
This would be hell useful for what I am putting together, I cant separate the usable sift able purified ores and make a buffer for the centerfuge wtihout putting the unusable ones in there and I cant automatically take them out without taking the usable crystals as well

**Comment by johnch18** [comment]
I'm out of the loop with gt5 source code, so I apologize if this is a poor suggestion, but maybe we could create a GT subclass of Item that includes flags for what "processes" it participates in. So implicitly, naquadah is a centrifugable material and we could scan for that rather than checking recipe maps. This would offset the computation from runtime to loadtime, which I think would be maybe worth it. Just spitballing though.

**Comment by SteamDoge9000** [comment]
would it be a good idea to have this suggestion on the front page if its going to be considered so it dosent go stale?

idk how yall work tbh

**Comment by Prometheus0000** [comment]
Just how big do you think the front page is? There's tons of stuff that could go on there.

**Comment by SteamDoge9000** [comment]
hmm, maybe if you want some things to stay open, a role tag could be added that prevents the bot from marking the issue as stale and closing it? IDK

**Comment by Glease** [comment]
There are such tags. Just no one bothered enough before.
