### ISSUE TITLE
Vacuum Freezer not using power when processing

### ISSUE THREAD

**Issue by Zodiack256b** [GTNewHorizons/GT-New-Horizons-Modpack#7279]
#### Which modpack version are you using?
2.1.0.2b
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
I set up a vacuum freezer with two HV hatches one had gas power feeding into a battery bank and the second was just linked to a battery bank with 4 HV batteries.  When i processed hot TungstenSteel ingots no power was drawn from either battery/power system.

Expected power to be drawn but none was used.

**Comment by Zodiack256b** [comment]
This issue looks to also affect the EBF. I ran some stainless steel through it since it is also affected by TecTec. It also did not consume any power from the system while processing.

Multiblocks not affected by TecTec look to be fine. (Distillation tower, Pyrolyse Oven tested).

**Comment by Dream-Master** [comment]
can you check http://jenkins.usrv.eu:8080/job/Tec Tech/613/

**Comment by Dream-Master** [comment]
@Zodiack256b and report if it works ?

**Comment by Zodiack256b** [comment]
Swapped to the TecTec file you linked. Tried running 5 stainless steel through the EBF again to test and it still did not pull power from the attached power systems.

**Comment by Dream-Master** [comment]
Can you post a few pictures here. So that we can rebuild and test it ? @Zodiack256b

**Comment by Dream-Master** [comment]
Nope ebf runs fine burning 4 ingots allready

**Comment by Dream-Master** [comment]
Vac Freezer runs fine too

**Comment by Dream-Master** [comment]
http://downloads.gtnewhorizons.com/Dev-Pack/Pack/Client/GTNewHorizonsClient-1.7.10-2.1.0.2c.zip
last dev pack

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/104088034-3091c980-5264-11eb-9243-6e1343022f9f.png)
![image](https://user-images.githubusercontent.com/2970688/104088038-3687aa80-5264-11eb-8ba6-c6b1619cf614.png)
![image](https://user-images.githubusercontent.com/2970688/104088041-3c7d8b80-5264-11eb-9ede-d61be07e13b0.png)

**Comment by GTNH-Afx237v7** [comment]
Runs fine but does it consume power?

**Comment by Dream-Master** [comment]
yes
![image](https://user-images.githubusercontent.com/2970688/104088128-d34a4800-5264-11eb-93f7-97012bbfe9e6.png)
![image](https://user-images.githubusercontent.com/2970688/104088131-d6ddcf00-5264-11eb-8ea4-2cbb73757753.png)

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/104088134-de9d7380-5264-11eb-8e3e-613d21cfc86f.png)
![image](https://user-images.githubusercontent.com/2970688/104088136-e230fa80-5264-11eb-8e3e-351e849e3820.png)

**Comment by Zodiack256b** [comment]
I updated to 2.1.0.2c and there was no issue on an SSP world but the issue persisted in my server world.  Currently making a fresh server to make sure it isn't something going on with an unexpected mod interaction from my addons. Will update shortly.

**Comment by Zodiack256b** [comment]
Fresh server environment worked correctly. Issue will be from an addon/mod of mine. Ok to close. Issue is not within the pack files.

**Comment by Zodiack256b** [comment]
Quick follow up to this issue. I replaced the controllers for both the EBF and the Vacuum freezer and the multiblock began using power again. As far as i can tell from the Waila readout they have the same id's so not sure what is different about them (unless its metadata).

It seems like the original controllers were bugged up somehow after updating. I can actually build a multiblock using those two controllers and not connect any power to them and they will run. As others update their production worlds might have them check to see if older multiblocks exhibit the same behavior.

I was even able to import the world to single player and had the same behavior. Old controllers were bugged and new ones worked correctly.

The world this occurred on has been going since 2019 so it has had alot of updates over the years.

**Comment by Zodiack256b** [comment]
![2021-01-09_06 20 39](https://user-images.githubusercontent.com/16424443/104091413-eba96b00-5242-11eb-894c-306f02ccd3ed.png)
![2021-01-09_06 20 42](https://user-images.githubusercontent.com/16424443/104091417-ecda9800-5242-11eb-9e2e-c3d2527885cb.png)
![2021-01-09_06 20 44](https://user-images.githubusercontent.com/16424443/104091419-ed732e80-5242-11eb-89bf-f09d3149bdf8.png)
![2021-01-09_06 20 48](https://user-images.githubusercontent.com/16424443/104091420-ee0bc500-5242-11eb-808e-9072b1c997fd.png)
![2021-01-09_06 20 54](https://user-images.githubusercontent.com/16424443/104091421-eea45b80-5242-11eb-9e26-4051cc332c27.png)
![2021-01-09_06 20 56](https://user-images.githubusercontent.com/16424443/104091423-eea45b80-5242-11eb-92e5-ed1144f3e7b0.png)

A set of pictures showing the original EBF controller being used. Multiblock was freshly put together and a piece of pulverized titanium was put in to process. Pics from all angles showing no power connected and the EBF is in production into a 98 second recipe.

**Comment by Dream-Master** [comment]
cant reproduce but i will ask @Technus

**Comment by Zodiack256b** [comment]
Sounds good. As you can see in the photos i do have extra mods added to the pack. Logistics pipes, Compact Machines, and a number of mob mods and a few performance mods not in the normal pack so I cannot guarantee it was not simply be an unexpected mod interaction.

Quick synopsis for Technus. After updating the pack my EBF, Vacuum Freezer, and likely my implosion compressor (not tested) would process recipes and not use power at all in the process. I cheated in new controllers and replaced the old ones and the ones cheated in worked as expected. The original controllers can be re-used like in the picture and will continue to not use power. As pictured even without attaching power the multiblock will still process like it has full power.

Testing in single player and a fresh multiplayer server environment worked as expected but those instances were cheated in blocks so are likely not carrying the meta data that an old controller would have from when it was crafted a very long time ago.
If it is reproduceable it will be from a world that has been around for at least the 2.0.9.x days likely.

**Comment by Dream-Master** [comment]
@bartimaeusnek any idea ?

**Comment by Technus** [comment]
There needs to be default 1A on on Nbt load adding that

**Comment by Technus** [comment]
This fix does not retrofit already broken machines!

**Comment by Technus** [comment]
If that is required ask bart to set amps explicitly for ex:
disabling eRating save/load (by overwriting the value with 1) idk
