### ISSUE TITLE
Suggestion: let turbines face up and down

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7280]
#### Which modpack version are you using?
2.10.0
#
#### What did you try to do, and what did you expect to happen?
I tried to point a steam turbine down.
#
#### What happened instead? (Attach screenshots if needed)
Doesn't work.
#
#### What do you suggest instead/what changes do you propose?
Please allow this.  Every other kind of single block machine can point up and down, why not turbines?

**Comment by leagris** [comment]
Should have been fixed already by StructureLib integration

**Comment by Prometheus0000** [comment]
I see no reason to not allow this and other generators from facing up/down.

**Comment by bombcar** [comment]
Any idea where this is in the code?

**Comment by Ethryan** [comment]
Think it has something to do with [Link](https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_BasicGenerator.java#L119), but not sure otherwise.
