### ISSUE TITLE
Fresh server crash from Lootgames

### ISSUE THREAD

**Issue by Zodiack256b** [GTNewHorizons/GT-New-Horizons-Modpack#7281]
#### Which modpack version are you using?
2.0.1.2c

#### If in multiplayer; On which server does this happen? 
Fresh server install to test another issue.

#### What did you try to do, and what did you expect to happen?
setup and started a fresh server with files from 2.0.1.2c zip. Got the attached crash during startup.

Reverting to LootGames-1.7.10-1.0.18.jar  Resolves the issue.

Was found while setting up a test server for issue #7279.

**Comment by Zodiack256b** [comment]
[crash-2021-01-09_04.04.31-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5790465/crash-2021-01-09_04.04.31-server.txt)

**Comment by TimeConqueror** [comment]
How did you setup your server? Seems that you don't have httpcomponent library in /libraries folder.

**Comment by Zodiack256b** [comment]
I used the libraries folder i have from my other 1.7.10 servers. Guess I am missing that component. Any means to get my hands on it so I can get it added to my libraries folder?

**Comment by TimeConqueror** [comment]
regenerate it with forge, or if you use Thermos, they provide their own libraries folder. Try to use fresh one.

**Comment by Zodiack256b** [comment]
Regenerated the server libraries from the forge 1614 installer and moved them to my server instance. I got the same crash. 
[crash-2021-01-09_07.38.37-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5791183/crash-2021-01-09_07.38.37-server.txt)

**Comment by Zodiack256b** [comment]
Looks like it is from Thermos. I pulled the library from their libraries.zip and it looks to be working now.

**Comment by Zodiack256b** [comment]
I added the thermos libraries from their github download and that also did not fix the issue. Any other idea where that file referenced might be from?

**Comment by TimeConqueror** [comment]
that's weird. I just tested it with fresh forge, but also didn't find these libraries. Ok, will fix it

**Comment by bartimaeusnek** [comment]
https://artfiles.org/apache.org//httpcomponents/httpclient/binary/httpcomponents-client-4.5.13-bin.zip

this _might_ fix it, for now
