### ISSUE TITLE
[Better Questing] Crash in edit mode

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#7282]
Just made a new quest and be in edit mode. After i add some new item to choice reward i got a crash.

Crash:
https://gist.github.com/Dream-Master/0efde3d071746095504b1c33e259b709

**Comment by Glease** [comment]
Is it still crashing on latest jenkins build? What exactly did you add anyway? The GUI codebase is quite solid afaik, and I highly doubt if it's some weird item being the culprit than BQ3.

**Comment by Dream-Master** [comment]
@Glease it still crash so we need to check what happend

**Comment by Dream-Master** [comment]
https://gist.github.com/Dream-Master/d8d417792e8213a628a3e4d9cc0785ef

**Comment by Dream-Master** [comment]
https://gist.github.com/Dream-Master/99446faa06c145513609f6e53679af9b
