### ISSUE TITLE
Dimensional goal: Moon  - Space race confusion

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#7285]
#### Which modpack version are you using?
2.1
#

I just got to HV tier (for the x'ed time), and ran into something that confused me, and since i have reached this point 3-4 times by now, a new player might find this even more confusing.

When entering HV tier, the quest "Dimensional goal: Moon" unlocked, and tells you to check out space race, but space race is grayed out. now I have done this before and was wondering why it was this time, The NASA workbench requires IV circuits, now that is easy enough to make when the cleanroom is up and running, but for a first time player this could be confusing and it could look broken to them.

I suggest we change the Space Race to open with "Dimensional goal: Moon" and add a pre-request quest that tells players something like this
/*
Well well well, you need to build a rocket, how do you do that you might be asking???
Well, first you need to build some advanced circuits in "Tier 4 HV" so you need to build a clean room and fill it with nice new machines to build the IV circuits you will need to get to the moon.
You might now be asking WHY do I need to do this, that is overly complicated, well......., if you think that is complicated then please hold my beer... while I laugh at your pain  :D/*

![image](https://user-images.githubusercontent.com/3405825/104107298-5ac2a600-52bb-11eb-8dab-9afff9c63c85.png)

![image](https://user-images.githubusercontent.com/3405825/104107293-55fdf200-52bb-11eb-865a-66070f86be51.png)

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/104107444-3e2f6980-52cd-11eb-85c9-6350bb7a72ca.png)
Isn't that blue text enough?

**Comment by Devtron3D** [comment]
might also add a clean room.
But I must be honest, having you need circuits of this type quest to unlock the space tab or everything else in the space tab, will make it more clear to new players. 

Missing an extra comment in a quest can be easy and forgotten when you spent 10 hours or two weeks, getting the cleanroom working

**Comment by Prometheus0000** [comment]
It already says what you need in the quest, so there's no need to change it. Having this quest unlock earlier just gives you some direction, rather than putting it behind IV circuits.
