### ISSUE TITLE
Tinkers Construct tools get harder to repair over time - please remove this

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7286]
#### Which modpack version are you using?
2.10.0
#
#### What did you try to do, and what did you expect to happen?
Repaired my excavator, expected similar repair costs as other tools
#
#### What happened instead? (Attach screenshots if needed)
It gets like half the durability per ingot.  Turns out this is because I've been using it a lot, and thus repaired it a lot.  In the code, each time you repair a tool it gets 1% less durability from future repairs, up to 50%.
#
#### What do you suggest instead/what changes do you propose?
Just remove this.  Tinkers Construct's original purpose was to enable you to keep using tools forever instead of them being broken when you run out of durability.  Having any permanent penalty at all for repairing them(or "breaking" them) flies in the face of that, and too strongly incentivizes auto-repair mods or making tools unbreakable.  It's also not stated anywhere in the documentation as far as I can tell.

**Comment by Dream-Master** [comment]
use more obsidian plates to update tools and make them unbreakable over time

**Comment by McFrugal** [comment]
That's not a reasonable option on the heavy tools such as Excavators and Hammers which use more durability and require more ingots for repairs.  You just can't rank them up enough to reach unbreakable before hitting the 50% reduction.  For example, my excavator is at 50% reduction and has 2 mods on it.
It's also not addressing the problem at all, merely working around it by rendering durability moot.  If there were some means of refreshing the tool to remove the penalty that would be a real solution.
I reiterate: this is not stated anywhere in the tinkers construct books.  It is an UNDOCUMENTED PENALTY for simply using the tool, in a mod that encourages using the same tool forever instead of making disposable ones.  It should not be like this.

**Comment by Skiftcha** [comment]
use better materials with more durability then. or cheaper materials. x2 resources on repairing is not that much even if you want to terraform large are.

**Comment by boubou19** [comment]
Tinker tools are better than any other tools. I think it's reasonable to make them harder to fix over time. That makes a reason to improve the tool.

But this should be documented somewhere as it can be confusing for players.

**Comment by Prometheus0000** [comment]
Isn't this only if it breaks first before you repair it?
