### ISSUE TITLE
Quest: Tier 1 Heavy duty plates needs updating

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7287]
#### Which modpack version are you using?
 2.1.0.2c
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?

Quest in subject (n. 812) requires stainless steel bolts, but the Heavy duty alloy ingots recipe has changed to use molten stainless steel in assembler instead. I propose to just remove the bolts requirement.

**Comment by Prometheus0000** [comment]
I noticed that all 3 pre-assline ones have changed, are the assline ones going to be changed too?
