### ISSUE TITLE
AE2 Interface's "blocking mode" are broken

### ISSUE THREAD

**Issue by htol** [GTNewHorizons/GT-New-Horizons-Modpack#7288]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
AE interface in "blocking mode" must ignore circuits in input hatches of multiblock and battery in single block machines.

#
#### What happened instead? (Attach screenshots if needed)
AE interface in "blocking mode" doesn't transfer items to input hatches with circuit or single block with battery.

#
#### What do you suggest instead/what changes do you propose?
Restore proper behavior.

**Comment by repo-alt** [comment]
I'll fix input buses, but not batteries. Battery slot is just one of the slots exposed by the machine, there may be anything. Checking for too many exceptions is expensive.

**Comment by GTNH-Afx237v7** [comment]
Won’t this block the interface from inputting at all? I.e. render blocking mode useless for input busses with circuits?

**Comment by repo-alt** [comment]
It is currently useless for blocking mode, not sure what do you mean.

**Comment by GTNH-Afx237v7** [comment]
Blocking mode will prevent the interface from inputting into an inventory if the inventory already contains an item. If there is a circuit in the input bus, how are you going to get your items in at all? The interface will see „item in there“ and not input anything until the circuit is removed.

**Comment by repo-alt** [comment]
There is exception for circuit for a few versions already, it just doesn't work for input buses.

**Comment by GTNH-Afx237v7** [comment]
Ok forget what I said, I misread the original statement... been a tough, long day...
