### ISSUE TITLE
The language file GregTech.lang does not work as it expected

### ISSUE THREAD

**Issue by SarixWired** [GTNewHorizons/GT-New-Horizons-Modpack#7294]
#### Which modpack version are you using?
2.1.0.0+
#
#### What did you try to do, and what did you expect to happen?
if I use the file "GregTech.lang" as the language file, which means changing the option in "GregTech.lang" "UseThisFileAsLanguageFile" from false to true  , almost any multi-machines' tooltips cannot change when press key "LSHIFT". However I expect it to be change or be transformed.
#
#### What do you suggest instead/what changes do you propose?
As I have red and thought the source code of  the mod "gregtech", I found that the function "getDiscription()"  return different String Array when press the key "LSHIFT", it's a dynamic String array,but if "UseThisFileAsLanguageFile" is true, the info display does not change anymore(it's static).
Suggestions:
   move the tooltips of multi including "iline" and "sline" to localization such as "en_us.lang" "zh_cn.lang" and so on for evey multi-block machine
  or rollback the discription methods(not suggested)

the issue is proxy for "Kiwi233"

**Comment by Kiwi233** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/410
Thanks @albus12138 fix this error
