### ISSUE TITLE
EBF TecTech structure

### ISSUE THREAD

**Issue by Oueio** [GTNewHorizons/GT-New-Horizons-Modpack#7295]
#### Which modpack version are you using?
2.1.0.2c
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Smelting Rarest metal residue dust to get Acidic osmium solution
#
#### What happened instead? (Attach screenshots if needed)
Iridium metal residue dust is appearing in output bus, but Acidic osmium solution is just dissappearing
Replaced output hathes, deleted filter, tryed again, and i didn't get osmium solution
#

**Comment by bartimaeusnek** [comment]
fixed with https://github.com/bartimaeusnek/bartworks/commit/d1ffbd200edb4ec1841cf6f697f334b5c92d9998

**Comment by Oueio** [comment]
Also, to my mind, with update, steel in EBF with LuV tier and 5801k, is smelting slower than before

**Comment by Oueio** [comment]
1 in sec or half

**Comment by bartimaeusnek** [comment]
Might be coil update. The Nq and NqKe coils got nerfed one tier down.

**Comment by Oueio** [comment]
Have hss-g coils

**Comment by Oueio** [comment]
Just before it was smelting 64 of wrought iron dust with oxygen in almos 10 or less

**Comment by Oueio** [comment]
Maybe it can't go lower than 1 sec of time

**Comment by Oueio** [comment]
If i'm not wrong, with luv tier(reducing time half 4 times) and 2 overclocks( steel has 1000k, i have 5800), time have to be 5*2^(-6) sec = 0.07

**Comment by Oueio** [comment]
Also now because of multismelter have tectech structure, oredictionary export bus with dust*, export all dust in input bus, but before it was pulling there only smeltable dusts

**Comment by GTNH-Afx237v7** [comment]
That maybe because of recipe input filter disabled, try adjusting with screwdriver (?)/ soldering alloy (?), not sure. Should say „input filter enabled“ then.

**Comment by Oueio** [comment]
> That maybe because of recipe input filter disabled, try adjusting with screwdriver (?)/ soldering alloy (?), not sure. Should say „input filter enabled“ then.

Input enabled, but don't work

**Comment by Glease** [comment]
Multismelter input bus is a different issue. Please open a new issue instead.
