### ISSUE TITLE
Multismelter input bus

### ISSUE THREAD

**Issue by Oueio** [GTNewHorizons/GT-New-Horizons-Modpack#7296]
#### Which modpack version are you using?
2.1.0.2c
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Input bus with filter input on have to get only smeltable dusts
#
#### What happened instead? (Attach screenshots if needed)
All dusts with oredictionary export bus are going into input bus
#

**Comment by bartimaeusnek** [comment]
fixed with: https://github.com/bartimaeusnek/bartworks/commit/305cc469dc6078566dd745fb4618a2cde380d18a
