### ISSUE TITLE
Monster Repellator doesn't block slime spawns

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#7298]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
Placed an EV repellator. It blocked all the mob spawns except slimes.

![2021-01-11_23 55 21](https://user-images.githubusercontent.com/36479271/104237823-af0b8880-5469-11eb-94ef-ba86de7b9d2c.png)

**Comment by bartimaeusnek** [comment]
Slimes are not considered hostile mods codewise, so yeah that might have to do with it

**Comment by draknyte1** [comment]
Should be fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/896
