### ISSUE TITLE
Gregtech cheese turns to harvestcraft cheese when picked up

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7300]
#### Which modpack version are you using?
2.10.0
#
#### What did you try to do, and what did you expect to happen?
I made some gregtech cheese with the fluid solidifier to get credit for eating it.
#
#### What happened instead? (Attach screenshots if needed)
It instantly turns into harvestcraft cheese when it reaches my inventory, preventing me from eating it.
#
#### What do you suggest instead/what changes do you propose?
Can this be changed?  I can't imagine a reason for it to be like this...  I'd like to eventually get credit for eating every single food.

**Comment by Prometheus0000** [comment]
The cheese ore also changes, messing up the no-rocket run apparently.
