### ISSUE TITLE
Chloramine quest is obsolete

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7305]
#### Which modpack version are you using?
2.1.0.2c
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?

subj
(chloramine was used for rocket fuel iirc, it has no use now)
maybe we should remove it's recipe, but the quest should definitely go

**Comment by Dream-Master** [comment]
lets see maybe we can found a new use

**Comment by Prometheus0000** [comment]
So what do you want me to do here? There's been no use for a year or two, are you (or someone) going to come up with one soon? It sure doesn't look like it. Otherwise we should remove the quest.
