### ISSUE TITLE
PTFE quest math is off

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7306]
#### Which modpack version are you using?
2.1.0.2c
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/23512002/104442179-c0f24600-55a5-11eb-888f-965ba1076d95.png)
When doing that quest you don't have access to LCR, and in single blocks you get 124 plates and some leftover TFE and PTFE

**Comment by KiloJoel** [comment]
It seems to be designed around this recipe, which does work out. (12*1500)/144=125
![image](https://user-images.githubusercontent.com/17787093/104442694-533a2000-558d-11eb-81bb-887fcad1425c.png)

**Comment by Vernam** [comment]
in this quest all is correctly, i don't understand how do u get 124 plates instead of 125... LCR recipe doesn't boost recipe without titanium tetrachloride.. With oxygen recipe in LCR matches with single block chem. try to look where do u could have a mistake please

**Comment by repo-alt** [comment]
probably I used oxygen in cells and TFE as fluid

**Comment by Prometheus0000** [comment]
So there's no need to change it after all?

**Comment by repo-alt** [comment]
idk, it is kinda trap, but avoidable

**Comment by Prometheus0000** [comment]
Which part is a trap? I don't remember if the other 3 recipes give a different amount, but if they do, you can just make a little more? And if they got an amount different than they expected, maybe they'll look in NEI and see the more efficient recipe?

**Comment by Prometheus0000** [comment]
> probably I used oxygen in cells and TFE as fluid

If this version of the recipe gives a different amount of fluid using the same amount of cells, maybe we should change it?

**Comment by repo-alt** [comment]
They give the same amount but divided differently, so you are left with like half a capsule of PTFE and some TFE if you use oxygen cells

**Comment by repo-alt** [comment]
And yes I had to make one more chloroform & 2 HF to complete the quest. Not a real problem.
