### ISSUE TITLE
OutOfBounds while mining

### ISSUE THREAD

**Issue by xhek** [GTNewHorizons/GT-New-Horizons-Modpack#7308]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Singeplayer
#
#### What did you try to do, and what did you expect to happen?
I was mining chalcopyrite ore with tinkers hammer nothing expected
#
#### What happened instead? (Attach screenshots if needed)
Mineraft crashed
#
#### What do you suggest instead/what changes do you propose?
OutOfBounds, Array Issue maybe?

Crashlog:
https://pastebin.com/GuBw8HSa

**Comment by Prometheus0000** [comment]
Duplicate of #7289
