### ISSUE TITLE
[Suggestion] Add possibilty to use excess fertilizer

### ISSUE THREAD

**Issue by DerMilchkarton** [GTNewHorizons/GT-New-Horizons-Modpack#7310]
Maybe create a electrolyzer recipe for fertiziler to get something semi-useful like sulfur, nitrogen and calcium out of fertiziler.
When creating a biofuel setup, there is a lot of fertilizer piling up due to the distillation which has little use. I think it shouldn't be only excess "waste". Sulfur, nitrogen and calcium have more use than fertiziler but aren't as op as chlorine or phosphorus from fertilizer.

**Comment by Prometheus0000** [comment]
Use a farm?

**Comment by leagris** [comment]
fertilizer nitrates and nitrites can be recycled for soap or explosives or get back the nitrogen, calcium, potassium if it helps, or farm.

**Comment by interestingusernam3** [comment]
Based no farm player.
