### ISSUE TITLE
Wire factory controller GT++ gated in LuV quest

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#7311]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta
Here is my GT++ quest tab (I'm currently IV tier)
![image](https://user-images.githubusercontent.com/62377720/104522000-54effc00-55fe-11eb-992e-11ceb08b77d6.png)
As you can see the quest for the wire factory controller isn't there and as the following image shows, the quest is gated behind LuV tier (Tier 7)
![image](https://user-images.githubusercontent.com/62377720/104521983-4acdfd80-55fe-11eb-94ef-1b0947657c58.png)
It should be gated behind Tier 6 (IV) because the recipe of that multi is IV

**Comment by alphaNOVAircraft** [comment]
Relict when it still required Zeron-100 plates that were Luv.

**Comment by johnch18** [comment]
You need an LuV fluid solidifier for the Zeron

**Comment by alphaNOVAircraft** [comment]
> You need an LuV fluid solidifier for the Zeron

yeah but you dont need zeron plates anymore
