### ISSUE TITLE
Pyrolyse Oven structure is not completing

### ISSUE THREAD

**Issue by sillygoosesofia** [GTNewHorizons/GT-New-Horizons-Modpack#7312]
#### Which modpack version are you using?
2.1.0.2c
#
#### If in multiplayer; On which server does this happen? 
Zeta. This issue does NOT occur in single player.
#
#### What did you try to do, and what did you expect to happen?
Built the Pyrolyse Oven as usual, expected it to form
#
#### What happened instead? (Attach screenshots if needed)
It displays as an incomplete structure. Also, checked Darkstar/Sampsa's base and their previously built Pyrolyse is showing as incomplete as well.
#
#### What do you suggest instead/what changes do you propose?
Not sure what is going on here; was thinking it is possibly related to TecTech multiblock update but the Blueprint does not do anything on the Pyrolyse.

**Comment by Prometheus0000** [comment]
Might be related to the coil change instead @bartimaeusnek

**Comment by dimondmine2** [comment]
Bumping for exposure. The Pyrolyse oven is an essential machine and progression in hindered without it.

**Comment by Prometheus0000** [comment]
@bartimaeusnek You fixed this already, right? It was a thermos bug relating to a lib/lang file or something yeah?

**Comment by bartimaeusnek** [comment]
Thermos only issue.
