### ISSUE TITLE
The clean room and what is locked behind it......   Confusing quest items.

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#7315]
#### Which modpack version are you using?
2.1
#

Found some stuff that might need a bit more explaining, or at least be hidden until the cleanroom is unlocked, that unlocks the vacuum freezer that is needed to make the following.

Cant make HV dynamos or HV energy hatches that are required for these quests.
Large steam turbine.
Oil Cracking Unit

The Energetic Alloy cant be made without kanthal coils, which requires the vacuum freezer that requires the cleanroom

I know for new players the EBF and the heat of the coils can be a confusing thing, and why it won't smelt energetic alloy can be confusing.

**Comment by Prometheus0000** [comment]
Energetic Alloy already requires the coil quest.

**Comment by Devtron3D** [comment]
Ok.
The large steam turbine and Oil cracking did not and they require that hatch/dynamo
