### ISSUE TITLE
Pink GT tools re-add

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#7318]
#### Which modpack version are you using?
2.1.0.0

Alumite GT tools were added in version 2.0.7.0 but it caused there to be 2 types of alumite for tinkers tools as mentioned in issue #4231 then they got removed.

I suggest to add pink GT tools back :)

**Comment by Prometheus0000** [comment]
Why do you want something so pointless?

**Comment by Impos913** [comment]
#4149 because moron added them and they got removed unintendedly.

**Comment by Impos913** [comment]
Also dream told me to make a ticket

**Comment by Prometheus0000** [comment]
Why in the world would you need 2 types of it though?

**Comment by Impos913** [comment]
GT alumite tools got removed while removing the duplicate tinkers tools. I suggest adding GT alumite tools (file, hammer, wrench etc.) back not the duplicate tinkers tools.

**Comment by Prometheus0000** [comment]
Given the nature of the bug I'm not sure that's possible

**Comment by Impos913** [comment]
Alumite is still a gt material as there are rods and plates and all the other stuff. ¯\_(ツ)_/¯

**Comment by Dream-Master** [comment]
relax i try to re add it

**Comment by Impos913** [comment]
![screenshot](https://user-images.githubusercontent.com/36479271/104791320-70e4d080-57ab-11eb-9ea6-f9f02a29a7f8.PNG)
They still exist, but you can't craft them. I remembered I had alumite GT tools in eta and joined there to see what happened to them.

**Comment by Dream-Master** [comment]
Did you tryed it with 2.1.0.2c?

**Comment by Impos913** [comment]
No, I don't have 2.1.0.2c installed. But nothing have changed about alumite probably.

**Comment by Dream-Master** [comment]
@Impos913 Not guessing test it. I make changes to gt tools. So it is possible that it work now.

**Comment by Impos913** [comment]
![2021-01-16_12 05 40](https://user-images.githubusercontent.com/36479271/104807869-3b63d580-57f3-11eb-959d-44064385d3d5.png)
This is 2.1.0.2c. GT++ alumite tools still exist too and they are crafted by using GT alumite tools. So when I check usage for plates I can see these. No recipes with alumite for regular GT tools though.

**Comment by Dream-Master** [comment]
ok will check

**Comment by Dream-Master** [comment]
If i re add it we have two parts of tinker's tools again. And i am against it to add those recipes manual. Any other suggestion ?

**Comment by Dream-Master** [comment]
@Impos913 what are the benefit of Alumite tools ?

**Comment by Dream-Master** [comment]
i work on a solution guess i found some

**Comment by Impos913** [comment]
Better durability than steel and P I N K

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/104811359-2ab75d80-57fb-11eb-9f14-dad3bfb7e43e.png)
here you are no tico tool and gt tools
![image](https://user-images.githubusercontent.com/2970688/104811368-39057980-57fb-11eb-9e3a-5c037d5a6964.png)
