### ISSUE TITLE
Login Crashes Modpack

### ISSUE THREAD

**Issue by DerVillager** [GTNewHorizons/GT-New-Horizons-Modpack#7319]
#### Which modpack version are you using?
2.075
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Login
#

#### What happened instead? (Attach screenshots if needed)
Crash

#
#### What do you suggest instead/what changes do you propose?

Attached Crashlog
[crash-2021-01-15_18.15.50-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5822131/crash-2021-01-15_18.15.50-server.txt)

**Comment by boubou19** [comment]
the version 2.0.7.5 is very outdated, update your pack and see what happens.

**Comment by boubou19** [comment]
i'm closing this. Feel free to reopen it if it still happen in 2.1.0.0 or later.
