### ISSUE TITLE
Add recipe to convert circuits to their lowest tier equivalent

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7320]
As the title says. The purpose of this is to mitigate the impact of current and future oredict problems until they can be fixed.

The recipe could be, for example, shapeless GT file + circuit

**Comment by johnch18** [comment]
i would create a specific set of "generic" item circuits for this purpose. This will also be mitigated by the removal of disassembly data

**Comment by Prometheus0000** [comment]
We don't need _another_ set of circuits
