### ISSUE TITLE
Assembling lines don't allow oredict in recipes

### ISSUE THREAD

**Issue by Teykn** [GTNewHorizons/GT-New-Horizons-Modpack#7321]
A few important Assembly Line recipes utilize molten rubbers, like the conveyors for example. However, they're limited to only 1 of the 2 rubbers (Recipe that utilizes molten SB rubber can't use molten Silicone, and vice versa). I propose changing recipes that utilize molten rubbers to instead utilize rubber sheets, since they can utilize oreDict substitution so that both SB and silicone work. It would also make sense to do so (in the case of conveyors) due to the fact that LV-IV conveyors utilize rubber sheets, and LuV+ pump recipes can use both SB and silicone.

Thoughts?

**Comment by johnch18** [comment]
Use SFM bruh

**Comment by Teykn** [comment]
> Use SFM bruh

My problem isn’t with fluid management. My problem is with the fact that due to the usage of rubber fluids it’s impossible to substitute them for the other variant. What does SFM have to do with it???

**Comment by Prometheus0000** [comment]
I don't think the assline allows any oredicting. This is a bug, not on purpose, BTW.

**Comment by Teykn** [comment]
> I don't think the assline allows any oredicting. This is a bug, not on purpose, BTW.

Huh, Thought that some recipes allowed oreDicting. Probably gonna check it out in game just to confirm.

I also presume that it’s not possible for there to be multiple assline recipes in a data stick?

**Comment by Prometheus0000** [comment]
I'm gonna say no?

**Comment by boubou19** [comment]
> I also presume that it’s not possible for there to be multiple assline recipes in a data stick?

No it's not possible, but you can allow multiple data sticks inside an assembling line by using data access hatches (one is even automatable). If you want to centralize your your datasticks and share them with multiple assembling lines, use a databank from TecTech
