### ISSUE TITLE
Suggestion : Multi-smelter Coils 

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#7322]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
With the multismelter, you can smelt baches of items as you know.
The maximum amout of smeltable items at once is 2 stacks which leads to HSS-G coil tier at the moment
I tried with some Naquadah coil blocks and it didn't change anything obviously because we reached the max
I think this is a shame because a few coil tier are useless for the multi smelter

#### What do you suggest instead/what changes do you propose?
I suggest 2 options : 

1) Increasing the amout of ingots smelted at once so we will have : 
- Cupronickel : 8
- Kanthal : 16 
- Nichrome : 32
- Tungstensteel : 64
- HSS-G : 128
- Naquadah : 256
- Naquadah alloy : 512
- Electrum fluxed :  1024
- Awakened draconium : increasing speed (because as the input bus can be 16 slots max this is not suitable to have 32 stacks in one hatch)

2) Reducing the amouts of smelted ingots for example like that :
- Cupronickel : 8
- Kanthal : 16 
- Nichrome : 24
- Tungstensteel : 32
- HSS-G : 48
- Naquadah : 64
- Naquadah alloy : 128
- Electrum fluxed : 256
- Awakened draconium : 512

I actually don't know if superconducting coil blocks can be used so I didn't integrated them in my thoughts
Let me know what you think of that

**Comment by Prometheus0000** [comment]
Isn't there an energy efficiency thing too?

**Comment by Nicouuuuu** [comment]
Indeed you're right, it seems that the energy consumed is divided by 2 after HSS-G coils

Yeah That's what I thought I am not aware of all high tier coils for multiblocks

**Comment by alphaNOVAircraft** [comment]
I like the idea of reducing the current ones and adding a multiplier benefit on a few higher ones. Energy is no issue with a multi smelter anyways.

**Comment by Prometheus0000** [comment]
Bart added them really recently, they go inbetween, not after AwDr.

**Comment by Nicouuuuu** [comment]
Oh yeah that's right there are new ones now ! 
So if we keeping the idea of reducing the amout of smelted items it would be something like that for the numbers : 

8/16/24/32/48/64/128/196/256/512/1024
