### ISSUE TITLE
Game failing to load

### ISSUE THREAD

**Issue by paleofry** [GTNewHorizons/GT-New-Horizons-Modpack#7323]
#### Which modpack version are you using?
Currently using the up to date version of 2.1.0.0QF1-1.7.10
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
I am trying to access my save file today but everytime I try the game crashes and I get and Exit code of -1. Game was functioning correctly yesterday. Updated Java to current verison. I am able to start a new world while crash logs mentions something about Ender IO being an possible issue. Not sure what to do. I have reinstalled the modpack already and tried repair feature in curseforge. The pack won't run/tries to reinstall Ender IO and subsequence mods when i remove them. Any help would be greatly appreciated. Log attached below.

[crash-2021-01-15_23.39.56-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5823867/crash-2021-01-15_23.39.56-server.txt)

#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by mitchej123** [comment]
Looks like a corrupt chunk

**Comment by paleofry** [comment]
Any suggestions on what to do then?

**Comment by paleofry** [comment]
Just decided to restart world.
