### ISSUE TITLE
Add Advanced Coils to pair with Advanced SMD Components

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7325]
Add an advanced coil in the spirit of the advanced smd components.

**Comment by alphaNOVAircraft** [comment]
Hmm, coils seem to be fine for me. Not sure if we really need a advacned version of them

**Comment by Prometheus0000** [comment]
Which coil? There's a bunch of coils

**Comment by alphaNOVAircraft** [comment]
Probaly the small coils (the yellow ones) that you use for circuits (i think mainframe tier circuits)

**Comment by johnch18** [comment]
Yes, I mistyped in saying capacitor

**Comment by johnch18** [comment]
Bumping my own suggestion because I'd prefer this.

**Comment by alphaNOVAircraft** [comment]
Would maybe help if you rename the issue so you dont have to check the comments on what you want to add, cz it still says capacitor instead of coil
