### ISSUE TITLE
Molten redstone cells cannot be used

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7327]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/59776356/104819140-810db600-5866-11eb-8de6-99c9c5b1f433.png)
![image](https://user-images.githubusercontent.com/59776356/104819141-83701000-5866-11eb-8390-fa808f8ff0df.png)
![image](https://user-images.githubusercontent.com/59776356/104819146-8a971e00-5866-11eb-848f-cd9410addb49.png)
![image](https://user-images.githubusercontent.com/59776356/104819159-98e53a00-5866-11eb-9ac9-064a44f0d7e4.png)
![image](https://user-images.githubusercontent.com/59776356/104819163-a3073880-5866-11eb-8cf3-ebdc0c355fb6.png)

#
#### What happened instead? (Attach screenshots if needed)
You can't set Molten redstone cells in the fluid interface or fluid export bus
You can't even get redstone cells from gt tank and you can’t put redstone in the gt tank
Can't be put in rc tank
Molten redstone can go through the pipeline 
But because Molten redstone cells cannot be correctly identified by AE, there is no way to use AE for transfer
#
#### What do you suggest instead/what changes do you propose?
fix it make molten redstone can be transported through ae like other fluids

**Comment by Prometheus0000** [comment]
Use the fluid canner or universal cells.

**Comment by Glease** [comment]
That's a good workaround, but I guess someone still need to go investigate it and devise a proper fix.

**Comment by Prometheus0000** [comment]
Is this not the same thing as some fluids needing a fluid canner/universal cell that's been around for ages though? If it is, this is a duplicate issue. I dunno about fluid AE though.

**Comment by Glease** [comment]
I haven't got to know any fluid that can't be pulled out of a cell by a gt tank (as shown in one of the screenshots), so it's probably not the same thing, but it might be my ignorant.

**Comment by Prometheus0000** [comment]
Steam, cracked stuff
