### ISSUE TITLE
Cleanroom and diode

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7328]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/59776356/104818864-1c9e2700-5865-11eb-83fc-e1b1b8b83853.png)
![image](https://user-images.githubusercontent.com/59776356/104818867-21fb7180-5865-11eb-8004-87fde9e4f6ea.png)
#
#### What happened instead? (Attach screenshots if needed)
The diode is actually within the 10 machine Hulls limit
Means that when you have ten Machine Hulls, you will not be able to use diodes
#
#### What do you suggest instead/what changes do you propose?
Remove the diode limit

**Comment by mitchej123** [comment]
I'm fairly certain this is intended, 10 machine hulls/diodes.

**Comment by Eason134HK** [comment]
> I'm fairly certain this is intended, 10 machine hulls/diodes.
Then this should be mentioned on the wiki or mentioned on the questbook
When I added diodes to my cleanroom, it was because of this problem that I didn’t know why my cleanroom could not work for a while.

**Comment by Prometheus0000** [comment]
We're not removing the limit.

**Comment by Prometheus0000** [comment]
If you want to edit the wiki, feel free

**Comment by Glease** [comment]
It will be in the controller tooltip next release
