### ISSUE TITLE
GT multiple blocks will destroy fluid or items

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7329]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
GT multiple blocks will destroy liquids or items
#
#### What happened instead? (Attach screenshots if needed)
GT multiple blocks will destroy liquids or items
#
#### What do you suggest instead/what changes do you propose?
GT++ multis don't void stuff so it should be fixable

**Comment by Impos913** [comment]
#6636

**Comment by GTNH-Afx237v7** [comment]
Yeah this has been the behavior of GT multiblocks since... always?

**Comment by Dream-Master** [comment]
So a gt issue ? @mitchej123 @bartimaeusnek  any idea ?

**Comment by Glease** [comment]
Basically a duplicate of #6636. That thread has attracted plenty of attention, is still open, and has an ongoing discussion, so I'm closing this issue in favor of that one.
