### ISSUE TITLE
wrenching reactor could loss item inside reactor

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7330]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta 
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/59776356/104818990-c8477700-5865-11eb-8080-250fa3ec971c.png)
When I tried to move my reactor from the old location to the new location, I wrenched them and some item inside the reactor disappeared
#
#### What happened instead? (Attach screenshots if needed)
wrenching reactor could loss item inside reactor
When it happened for the first time, I thought it was because I didn’t pay attention and then forgot to pick up the items on the ground but it happened to me three times
I can't recreate this bug successfully in my creative mode world but it happened on delta
#
#### What do you suggest instead/what changes do you propose?
fix it if you can

**Comment by Dream-Master** [comment]
ic2 code is closed source so not sure what we can do against it?
