### ISSUE TITLE
Add dire autocrafting table OC integration

### ISSUE THREAD

**Issue by bamik69** [GTNewHorizons/GT-New-Horizons-Modpack#7331]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Other
#
#### What did you try to do, and what did you expect to happen?
I wanted to put the recipe in the Dire Crafting table using Transposer. 
#
#### What happened instead? (Attach screenshots if needed)
Materials do not fit into the crafting grid. Is it possible to make this possible? Items are not taken from the workbench. Although the survey reports the presence of items in the cells, the maximum number in the cell is 64.
#
#### What do you suggest instead/what changes do you propose?
I suggest changing the capabilities of Transposer to work with workbenches that have slots in the crafting field.

**Comment by GTNH-Afx237v7** [comment]
You can use the Dire Autocrafting table to set a recipe pattern and insert items via automation (e.g. via AE2 interface).

**Comment by bamik69** [comment]
I would like to be able to automate crafting with OC. I know about the Dire Autocrafting Table. But for each recipe, you will need your own workbench. 20-30 Dire Autocrafting Table will need to be placed in the house. This is very inconvenient.

**Comment by Prometheus0000** [comment]
So? I don't see the problem. And transposers is ARR, so it would be a giant pain to do, do. Just suck it up and make the blocks, it's not like you don't need to make tons of other stuff in this pack. And your issue says nothing about OC.

**Comment by Prometheus0000** [comment]
Is the transposer not the translocator, or is this another item? Also, I was wrong, and the translocator mod is not ARR.

**Comment by bamik69** [comment]
Transposer allows you to move items and liquids between storages.

**Comment by Prometheus0000** [comment]
Is it this item https://discord.com/channels/181078474394566657/603348502637969419/800077847683137566 ?

**Comment by bamik69** [comment]
> So? I don't see the problem. And transposers is ARR, so it would be a giant pain to do. Just suck it up and make the blocks, it's not like you don't need to make tons of other stuff in this pack. And your issue says nothing about OC. Transposers != OC.

Autocraft using the Dire Autocrafting Table + AE2 is a problem on the upper Solar Panel. There are also missiles that are periodically lost. Etc.

**Comment by Prometheus0000** [comment]
What? There's no missiles in this pack I can think of?

**Comment by bamik69** [comment]
> Is it this item https://discord.com/channels/181078474394566657/603348502637969419/800077847683137566 ?

Yes

**Comment by Prometheus0000** [comment]
> Autocraft using the Dire Autocrafting Table + AE2 is a problem on the upper Solar Panel.

How/why? Isn't it just a matter of putting the items into it's inventory? Does it not work? Or do you just want to craft all the items with one DAT?

**Comment by Glease** [comment]
> missiles

I guess he means rockets. 

Anyway, in current version of the pack rockets are once again made in NASA workbench not direcrafting table. That stupidly large crafting table is no longer mandatory

**Comment by bamik69** [comment]
> > Autocraft using the Dire Autocrafting Table + AE2 is a problem on the upper Solar Panel.
> 
> How/why? Isn't it just a matter of putting the items into it's inventory? Does it not work? Or do you just want to craft all the items with one DAT/DCT?

Yes, I wanted to use one workbench for all the recipes. Or, if possible, one.

**Comment by bamik69** [comment]
> > missiles
> 
> I guess he means rockets.
> 
> Anyway, in current version of the pack rockets are once again made in NASA workbench not direcrafting table. That stupidly large crafting table is no longer mandatory

There are many other recipes that are performed in this large workbench.

**Comment by bamik69** [comment]
Unfortunately, the robot is also unable to interact with such workbenches. There is no way to test the drones yet.

**Comment by bamik69** [comment]
I apologize for my Yandex English.

**Comment by repo-alt** [comment]
Usual avaritia table is intentionally not automatable, use dire autocrafting table as suggested. (May use it with robot if you like)

**Comment by 0lafe** [comment]
Could you use OC to edit which fake items are stored in the auto dire table? I know theres some weird things we can do with setting ghost items in filters

**Comment by repo-alt** [comment]
Not sure you can set ghost items via OC, they are probably read-only. May add integration.

**Comment by GTNH-Colen** [comment]
This seems like a waste of dev time, while possible you can literally just make 10 or so autocrafting tables and be done with it. There are not that many recipes which need to be repeated in that table, most I can think of is related to draconic evolution cores.

**Comment by bamik69** [comment]
> This seems like a waste of dev time, while possible you can literally just make 10 or so autocrafting tables and be done with it. There are not that many recipes which need to be repeated in that table, most I can think of is related to draconic evolution cores.

Most of the recipes for autocraft are solar panels. The problem is that in the older shooting ranges, it will not be possible to solve autocraft beautifully with the help of AE2, it requires more materials than AE2 is able to provide.
In addition, there are many who want to use this opportunity.
Maybe an OC adapter is suitable for this purpose? If you insert something like Crafting Upgrade into it. And create a driver that allows you to fill the crafting grid in DAT.

**Comment by boubou19** [comment]
are you aware of the new processing pattern terminal that let you put 16 itemstacks in input for 4 itemstack in output?

**Comment by bamik69** [comment]
> are you aware of the new processing pattern terminal that let you put 16 itemstacks in input for 4 itemstack in output?

Yes.

**Comment by repo-alt** [comment]
Do we actually have recipes with more than 16 ingredients?

**Comment by bamik69** [comment]
> Do we actually have recipes with more than 16 ingredients?

Maybe not. But putting 20 DAT is not very nice at least. There is an idea of a full-fledged autokraft under the control of OC, but without the ability to control DCT, this is not feasible.

**Comment by GTNH-Colen** [comment]
Isn't it possible to encode patterns with > 16 items using OC now anyways?

**Comment by Prometheus0000** [comment]
It is. Somehow. Maybe ask sampsa/bot to make some instructions and post in the OC channel? I can't make quest instructions for it, cuz I don't understand OC, much less this.

**Comment by GTNH-Afx237v7** [comment]
It is possible to encode patterns via OC to hold more than 16x64=1,024 items (as bot did for the recipes to make singularities). But as Prometheus said, better ask bot/Sampsa/repolainen if more than 16 item stacks are possible.

**Comment by bamik69** [comment]
> Isn't it possible to encode patterns with > 16 items using OC now anyways?

At the moment, OC is able to craft in a 3*3 matrix through the work inventory.
The problem with DFC/DCT is that the OC is not able to move anything to or from the container of these tables. Although the characteristics are read by both tables and stacks via the Adapter or Transposer interfaces.

**Comment by repo-alt** [comment]
First 81 slots of the dire crafting table are writable, did you even try that? Ghost items are read only, that is true.

**Comment by bamik69** [comment]
I tried it. It's not very interesting. The usual supply of resources can be carried out using AE2. I am interested in making a recipe.

**Comment by repo-alt** [comment]
![image](https://user-images.githubusercontent.com/23512002/105636813-10c0ef00-5e7b-11eb-8c1d-3dbe2b49db55.png)

**Comment by bamik69** [comment]
Wow! Can this be used for tests?

**Comment by repo-alt** [comment]
> Wow! Can this be used for tests?

Yes, "need to be tested" label tells exactly that.

**Comment by Dream-Master** [comment]
I will make an dev update when bartworks is patched to use new Tec tech overlay multies. Will included oc too

**Comment by bamik69** [comment]
That's great!

**Comment by bamik69** [comment]
You have no idea what a breakthrough this is. The whole game world dreamed of automating this. I've read quite a few forums. And once you've done this.
