### ISSUE TITLE
Ae2 Cables break with Forge multipart covers

### ISSUE THREAD

**Issue by Ydrec** [GTNewHorizons/GT-New-Horizons-Modpack#7332]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
Zvezdolet
#
#### What did you try to do, and what did you expect to happen?
When using forge multipart covers to hide cables they apply hardness of the matterial they are made from (or just generally make some distinction) to the block they are placed on. Even so when just placing them on ae cables they work normally, and should not mess with ae cables work.
#
#### What happened instead? (Attach screenshots if needed)
But after server restart on places where two cables with covers of different hardness meet they disconnect. 
#
#### What do you suggest instead/what changes do you propose?
Either make covers all have same hardness or make them use hardness of block they are placed on. 
This maybe at all not the reason why they disconnect but at least this can easily be tested.
And yes im fully aware ae2 have its own covers, but they lack the forms and different sides making them unsuitable for designing some factories.

**Comment by repo-alt** [comment]
Multipart support is a gross hack in ae2, and is dropped in the later versions because it is extremely hard to implement properly. I don't think I'll have time to seriously dig into that. What kind of forms do you mean btw?
