### ISSUE TITLE
[Suggestion] Chest buffer sorting

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7333]
#### Which modpack version are you using?
GTNH 2.1.0.2.c

The chest buffer is a nice gregtech container on wich you can use covers. Before the update that removed energy costs on covers, the chest buffer would sort its own inventory only when powered but now it does it all the time. For certain automations you don’t want to have the sorting enable.

I suggest adding a way to toggle the sorting via screwdriving the block (other side than output face) or adding a button in the internal GUI or something else.

**Comment by alphaNOVAircraft** [comment]
Yeah would be really good to have such a feature, disabling the whole block is sometimes not suitable either. 
I dont know why but it seems to mess up the way how AE Interfaces insert items into the chestbuffer, they dont stay in the right order (at least last time i tried it)

**Comment by Prometheus0000** [comment]
Is #7185 related?
