### ISSUE TITLE
GUI Scale crash

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#7334]
#### Which modpack version are you using?
2.1.0.2c

Changing GUI scale crashed game.
https://pastebin.pl/view/5ebf528a

**Comment by mitchej123** [comment]
It's almost certainly an Optifine issue.  Happens fairly often if you have multi core chunk loading enabled.

remove optionsof.txt and try again.

**Comment by Impos913** [comment]
I don't have multi core chunk loading enabled

**Comment by TimeConqueror** [comment]
@Impos913 Optifine changes Chunk Loading to Smooth or MultiCore when you change your gui scale

**Comment by Impos913** [comment]
I see, lol
