### ISSUE TITLE
Similar recipes for IC2 coolant

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#7335]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What did you try to do, and what did you expect to happen?
crafting IC2 coolant with a mixer (lapis dust + water)
found 2 similar recipes, one uses 125L of water and gives 125L of IC2 coolant using 1 dust, the 2nd recipe still uses 1 lapis dust, but uses 1000L of water and gives 1000L of IC2 coolant
![javaw_GNQ5JxTgpE](https://user-images.githubusercontent.com/17811922/104827354-faa0a680-585c-11eb-93ea-462d28ba5227.png)
![javaw_RWu0LvFwJ6](https://user-images.githubusercontent.com/17811922/104827355-feccc400-585c-11eb-80ee-730a3fac6789.png)
In my case, the one with 125L was used. Idk which one is correct

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Remove one of the 2 recipes, possibly the one with 125L :P

**Comment by Prometheus0000** [comment]
The 125 should be distilled water, is it not?

**Comment by Impos913** [comment]
1000 one is distilled

**Comment by Prometheus0000** [comment]
Ah, I wasn't looking a the output. Yeah, it's using less lapis, like the IC2 recipe. So it's all good.

**Comment by Sphyix** [comment]
Ye, just noticed, 1000L one is distilled, sry.
