### ISSUE TITLE
New Hing Current UMV Wire

### ISSUE THREAD

**Issue by SKYCATV587** [GTNewHorizons/GT-New-Horizons-Modpack#7337]
What do you suggest instead/what changes do you propose?
i saw that umv have no high current wire and Nether Star can be use to make uiv wire , so why not use Crystal Matrix Ingot to make umv wire and let it have 128a

**Comment by 0lafe** [comment]
Why not use TT lasers? They seem like a more unique high throughput option

**Comment by SKYCATV587** [comment]
> Why not use TT lasers? They seem like a more unique high throughput option

gtpp's multi block can't use lasers

**Comment by 0lafe** [comment]
good
