### ISSUE TITLE
Suggestion: Add Fluid Interfaces to Interface Terminal

### ISSUE THREAD

**Issue by KorGgenT** [GTNewHorizons/GT-New-Horizons-Modpack#7340]
#### Which modpack version are you using?
2.1
#
#### If in multiplayer; On which server does this happen? 
-
#
#### What did you try to do, and what did you expect to happen?
access the interface terminal, see the fluid interface buses
#
#### What happened instead? (Attach screenshots if needed)
no interface buses
#
#### What do you suggest instead/what changes do you propose?
I would like for the following to happen:
1 - be able to rename fluid interface buses with certus quartz knife (important for this)
2 - have fluid interfaces show up in the interface terminal for easy usage of patterns.

**Comment by GTNH-Afx237v7** [comment]
Just as an addendum: you could have a look at this https://gtnh.miraheze.org/wiki/Fluid_P2P_tunnels
Not fully what you described but may be helpful

**Comment by PolkageistHS** [comment]
Any chance this one could be reopened?  I use these quite a bit for autocrafting because I'm too cheap to make a separate machine for each liquid and it's annoying not being able to see them in the interface terminal.

**Comment by boubou19** [comment]
you should really move away from EC2's fluid management, it's buggy as hell. Just use a regular interface with flasks filled with fluid and the rest of your craft, then make the interface export pattern result inside a chest, then route flasks in an input hatch/tank while the other items go inside the correct bus/machine. All crafts with fluids have a multiple of one of the few flask values craftable in an assembler.
