### ISSUE TITLE
TecTech EBF is so broken

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#7342]
#### Which modpack version are you using?
2.1.0.2c
#
#### If in multiplayer; On which server does this happen? 
sp

![ss1](https://user-images.githubusercontent.com/36479271/104955163-ceab2f80-59da-11eb-90f6-a986ff7ecdeb.PNG)
![ss](https://user-images.githubusercontent.com/36479271/104955164-cf43c600-59da-11eb-801a-548e5a235130.PNG)

2 IV energy hatches and hss-g coils and using 2 carbon dust + 1 silicon dioxide recipe.
It is working a lot slower than it should. Recipe should take 3 ticks but it smelts like 3 items every 2 secs or slower (tps is fine).
Switched to 1 IV energy hatch and it should have smelted in 7 ticks but it worked at the speed.

Also it doesn't consume power.

**Comment by basdxz** [comment]
@bartimaeusnek

**Comment by Dream-Master** [comment]
@Impos913 thanks for bug report but 2.1.0.2c is a dev version. Bugs are normal and we try to working on this asap.

**Comment by Impos913** [comment]
@Dream-Master is the fix included in 2.1.0.3a ?

**Comment by Impos913** [comment]
Ok it includes but EBFs that were used in 2.1.0.2 wasn't consuming power. I had to break and re-place the controller to fix.

**Comment by Dream-Master** [comment]
will be fixed in 2.1.0.4 when it is out.
