### ISSUE TITLE
Item detector covers aren't working anymore

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7343]
#### Which modpack version are you using?
GTNH 2.1.0.2.c

So I have item detector covers with default setting on a chest buffer/input bus/output bus and none of them are working

![image](https://user-images.githubusercontent.com/57050655/104957046-aec13f00-59cd-11eb-8bc1-18299952e26c.png)

**Comment by GeicowithaBango** [comment]
the cover are going to need energy if you place them on the buffer/filter.
i dont remember that you can insert items from anywhere besides the front of the input bus 
mind checking if it works with my suggestions?

**Comment by Alexdoru** [comment]
Look, the item detector cover never needed energy to work, it used to work before and now it's not --> it's a bug.

And how am I supposed to give energy to an input/output bus ?

**Comment by GeicowithaBango** [comment]
> Look, the item detector cover never needed energy to work, it used to work before and now it's not --> it's a bug.

No, that was never the case, Im afraid you are remembering not correctly 


> And how am I supposed to give energy to an input/output bus ?
an input bus ofc doesnt need power, but afaik gt covers can only insert stuff through the front of the input bus

**Comment by Alexdoru** [comment]
> No, that was never the case, Im afraid you are remembering not correctly
I have item detector covers on chest buffers that are unpowered and they used to work before updating.

> an input bus ofc doesnt need power, but afaik gt covers can only insert stuff through the front of the input bus
why are you talking about inserting stuff in input bus, that's not the subject here.

**Comment by GeicowithaBango** [comment]
you are absolutely right, i mistook the conveyor belts to be the subject here lmao, sorry

well, item detection covers should have been untouched, idk
