### ISSUE TITLE
[RFC] Make Item Dislocator (Draconic Magnet) Available Earlier

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#7344]
![2021-01-18_23 19 48](https://user-images.githubusercontent.com/36479271/104959886-3a45ca80-59e4-11eb-9ad0-6dc734f4660a.png)
![2021-01-18_23 20 10](https://user-images.githubusercontent.com/36479271/104959891-3ca82480-59e4-11eb-860b-4bb78c9b0869.png)
Other magnet options aren't good. EnderIO magnet makes items orbit around and launch them. Another option is Magic Bees Mysterious Magnet and I don't even know how to unlock them. I researched most of the thaumonomicon (including all of apimancy tab) and I don't even see where it is. Also it makes teleport annoying noises while working. 
Item Dislocator is the best magnet option in the pack and it is ridiculously gated and expensive.
I suggest to make it available earlier. EnderIO magnet is available in late HV so make the draconic magnet available a bit later than that? Or make it replace EnderIO magnet?

**Comment by Yarntheory** [comment]
The draconium ingots in the recipe already gate the item dislocator at naquadah coils, so early/mid LuV at least. I think swapping the Charm of Dislocation with an enderIO magnet would be a reasonable change.

The item dislocator isn't something that really _needs_ to be gated. It's mostly useful when manually mining, which I am kind of assuming is going to be less common at the point when draconic cores are available anyways. There is also a server tps advantage as well, as players won't be leaving random items on the ground when mining.

**Comment by Impos913** [comment]
> The draconium ingots in the recipe already gate the item dislocator at naquadah coils, so early/mid LuV at least. I think swapping the Charm of Dislocation with an enderIO magnet would be a reasonable change.
> 
> The item dislocator isn't something that really _needs_ to be gated. It's mostly useful when manually mining, which I am kind of assuming is going to be less common at the point when draconic cores are available anyways.

So you are saying people do mine manually in LuV.

**Comment by Prometheus0000** [comment]
Or we can buff both magnets

**Comment by Impos913** [comment]
If it is possible to make EnderIO magnet teleport items to your inventory instead of making them orbit around you. It is ok too.

**Comment by Prometheus0000** [comment]
Wasn't that fixed though?

**Comment by Impos913** [comment]
no

**Comment by Prometheus0000** [comment]
Guess it was the 3rd of at least 4 magnets (BM has the 4th) #6978
