### ISSUE TITLE
Incorrect recipe of lv c

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#7345]
#### Which modpack version are you using?
MC1710
#
#### If in multiplayer; On which server does this happen? 
GTNH official server
#
#### What did you try to do, and what did you expect to happen?
macerating the lv, mv, hv, ev, iv conveyour, expecting to get dusts of their components
#
#### What happened instead? (Attach screenshots if needed)
Got both rubber pulp and extra 6 silicone rubber pulps (which is pretty hard to get, so you can use this bug to get silicone rubber without actually making chemical line to craft it)
![gtnh bug](https://user-images.githubusercontent.com/67397297/104964346-8a209380-59dc-11eb-8898-5b05638652c7.png)

#
#### What do you suggest instead/what changes do you propose?
fixing the recipe

**Comment by Prometheus0000** [comment]
Should be fixed for LV (#5896), we don't really care about the rest, since you need to be HV anyway

**Comment by Dream-Master** [comment]
No

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/104964830-8c372200-59dd-11eb-84dc-7a7fee3a9738.png)
still in 2.1.0.3-dev

**Comment by Dream-Master** [comment]
please check issues first before close @Prometheus0000 . Thanks

**Comment by Prometheus0000** [comment]
Then shouldn't we close this as duplicate and re-open the old one?

**Comment by Dream-Master** [comment]
sure
