### ISSUE TITLE
Suggestion- tie pollution to recipes, or abandon realism and tie it to blocks' CPU usage

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7346]
#
#### Which modpack version are you using?
2.10.0

#
#### What do you suggest instead/what changes do you propose?
Right now pollution happens from EBFs even if the recipe involves no carbon or raw ore at all.  For instance, the aluminum recipe accepts pure aluminum dust and gives aluminum ingots, but the EBF produces pollution from this somehow despite running on pure electricity.
Similarly, other recipes which have no or little carbon or volatile gas should not produce so much pollution.  Other machines should be investigated as well-- why does the Pyrolyse Oven pollute so much compared to coke ovens?  Optimally pollution would be tied directly to waste products emitted into the air, and the biggest culprits there would be solid fuel boilers/generators.  Burning coal(or charcoal) for power, in other words.  Burning most types of oil to produce energy would be bad as well, and methane (that's what "natural gas" is... would other gases pollute less than liquid fuels too?) would be relatively clean by comparison.  Once a base transitions to nuclear power, pollution shouldn't be a problem anymore.  Tying pollution to recipes would also make voltage/time requirements stop scaling up pollution of the EBF so much, which is a huge problem with mega blast furnaces.

An alternate suggestion is to abandon realism and aim straight for the problem you're trying to fix.  Associate pollution with CPU usage, naming it something else, like ambient entropy.  Should be easy to assign appropriate values to problematic blocks.
Or someone could go around on the servers and punish players for having laggy setups by removing the offending blocks?  I've seen server admins do that with other modpacks.  Then SSP players would not be affected at all.

On a side note, why is there an iron to steel recipe for the EBF that requires no carbon?  Steel production always involves carbon in real life, and I wouldn't expect the EBF to extract it from ambient air.

edit: oops, I should've posted this in the related RFC issue instead.

**Comment by Prometheus0000** [comment]
> edit: oops, I should've posted this in the related RFC issue instead.

Indeed
