### ISSUE TITLE
Thaumcraft research GT multiblock proposal

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7347]
#### Purpose
Provide an interesting tech-based way of automating thaumcraft research. As an alternative to the minigame, for players that are tired of it.
#
#### Function
Requires EU and Thaumcraft nodes to operate.
While the machine is processing, it will drain the max capacity of the nodes in its structure until they are diminished to 0 and destroyed.
Base recipe - 120eu/t, 60 seconds
If all nodes run out, the recipe will fail, in the same way it would if it ran out of EU.
#
#### New blocks
Magical machine casing - 6 Thaumium Plates, Thaumium Frame Box, 2 Salis Mundus
Controller - 4 MV Circuits, Magical Machine Casing, 3 Warded Glass, Wand Recharge Pedestal
#
#### Structure
Dimensions: 3x3x[3-13] (WxHxL)

Bottom layer outside - Magical machine casing
Middle layer outside - Warded glass, Controller front center
Middle layer inside - Air or Thaumcraft node
Top layer outside - Magical machine casing

Unchecked space under the nodes allows for optional node stabilisers, and space above allows for access to replace depleted nodes.

Minimum
![image](https://user-images.githubusercontent.com/17787093/104966911-f64dc800-59d9-11eb-9cbf-33edb9a3caa8.png)

Maximum
![image](https://user-images.githubusercontent.com/17787093/104966974-18dfe100-59da-11eb-8196-9a7b983c3b88.png)

Exploded
![image](https://user-images.githubusercontent.com/17787093/104967003-301ece80-59da-11eb-8d90-54cb170ef8cd.png)

**Comment by bedrill64** [comment]
Holy that's fun thing.

Few questions  tho:
- How would EU/vis cost would be determined? Will it be hardcoded for each mod and recipe or do you have some idea in mind? Maybe based on complexity and some other parameters in the code?

- Does this need all primals or just random nodes and random vis?

- How are you going to choose research to be done? By inserting research paper into input bus -> receiving researched thing in output bus? If so, how is it different from Book of Knowledge from Gadomancy mod.

- You say it would be research automation, then what is the main principle of machine working process researchwise in your mind?

**Comment by KiloJoel** [comment]
>
>     * How would EU/vis cost would be determined? Will it be hardcoded for each mod and recipe or do you have some idea in mind? Maybe based on complexity and some other parameters in the code?

I was thinking a flat EU cost per research, and a variable vis cost based on the existing aspect cost of the research. (if you're in easy mode, minor researches just cost research points rather than needing the minigame, all researches have these aspects defined)

> 
>     * Does this need all primals or just random nodes and random vis?

My thought was that it could use any vis type, maybe compound aspects could be worth double compared to primal.

> 
>     * How are you going to choose research to be done? By inserting research paper into input bus -> receiving researched thing in output bus? If so, how is it different from Book of Knowledge from Gadomancy mod.

I was thinking research paper in, research note out. I can't think of any other way this could work, but I'm open to suggestions.

I think the thing that this brings compared to the book of knowledge is not being an absolute pain. The book takes ages. If you walk near the book while it's researching, you'll pick up the page and it'll reset its progress. Actually unlocking the research and making the book requires messing around with aura cores, which are weird and hard to get right, which pushes away most people. Also while the book of knowledge can be automated, it requires quite a specific setup which is not easily scaleable, it also can't be world accelerated. So the slowness persists no matter what tier you're at.

If it is possible to get the book into a position where it's good enough that this isn't needed, I'd be happy with that as an alternative. Less development work overall maybe.

> 
>     * You say it would be research automation, then what is the main principle of machine working process researchwise in your mind?

I don't understand what you mean by this.

**Comment by hohounk** [comment]
The idea sounds fun but I wonder how can warp be handled by this.

**Comment by KiloJoel** [comment]
> The idea sounds fun but I wonder how can warp be handled by this.

The output of the machine would be a completed research note, so you would gain warp when you right click with it, same as if you had done the research manually

**Comment by hohounk** [comment]
oh, right. Duh. Somehow I had the dumb idea that you gain warp as you complete the research. Silly me :)

If I understand it correctly, the thing consumes nodes and pumps out research, right? As it probably requires a whole lot of those nodes to get anywhere it might sense to feed it nodes in a jar instead of building it around "free" nodes, especially due to nodes close by stealing from each other. That way people could easily make nodes from attuned matrixes and feed them to the machine instead of having to destroy and rebuild the thing any time a node runs out to place a new one. Ideally the machine would also somehow show what aspects it contains without you having to break a hole into it and scanning manually but I'm not sure how easy it'd be to add such rather unique UI.

**Comment by KiloJoel** [comment]
> If I understand it correctly, the thing consumes nodes and pumps out research, right? As it probably requires a whole lot of those nodes to get anywhere it might sense to feed it nodes in a jar instead of building it around "free" nodes, especially due to nodes close by stealing from each other. That way people could easily make nodes from attuned matrixes and feed them to the machine instead of having to destroy and rebuild the thing any time a node runs out to place a new one. 

Yep. Rebuilding the machine for every node would be very fiddly, so I'd consider it soft gated by the ability to jar nodes. Node matrices are quite expensive in GTNH so I would say that is probably only preferable to jarring once HV circuits are cheap to you. Another option would be to grow a big node using a hungry node or bees to get lots of research done with a single node.

> Ideally the machine would also somehow show what aspects it contains without you having to break a hole into it and scanning manually but I'm not sure how easy it'd be to add such rather unique UI.

I guess this is possible, but usually multiblocks don't have much of a UI. My idea was that by having the top of the structure open by design, you have access to see the nodes even when the multiblock is formed. Plus you can get a general idea of how the nodes are doing by looking at them through the warded glass since they will dim and disappear as they are drained.

**Comment by hohounk** [comment]
> Node matrices are quite expensive in GTNH so I would say that is probably only preferable to jarring once HV circuits are cheap to you

yea, it probably isn't the cheapest way to go but hunting down nodes can also take quite a while. In the end it will boil down to how much aspects the thing will take from the nodes.
Say, I have this research:
![image](https://user-images.githubusercontent.com/4471281/136022505-ee01ca66-6d81-40c7-ae7b-64b688076479.png)
What kind of aspects would the nodes have to have to research it and how much of them it'd consume?

> My idea was that by having the top of the structure open by design, you have access to see the nodes even when the multiblock is formed

duh, another oversight on my part. I've not used to having multiblocks be simple closed boxes.

**Comment by KiloJoel** [comment]
Each research has its own list of aspects defined. They vary by quite a lot and use all different aspects. 
Example:
![image](https://user-images.githubusercontent.com/17787093/136048293-67e007f0-3609-435a-a2d9-1221f1578b59.png)
Because nodes mostly just have primal aspects, I think it wouldn't make sense to try and make the aspects match. So for this research example you'd just consider the cost to be 16.
The ratio between aspects in the list to the aspects in the nodes can be decided on later, initially I'd just make it 1:1.

**Comment by bombcar** [comment]
I fully support this and would work toward it instead of just using solvers.

**Comment by KiloJoel** [comment]
> 
> 
> I fully support this and would work toward it instead of just using solvers. What "tier" is it expected to be? Anything later than HV/EV may be moderately redundant.

I suppose it's not entirely my call, but I would expect mostly thaumcraft gating. Besides minimum MV power to run, you'd need node jarring, alchemy, ability to make enough thaumium, and possibly infusion.
