### ISSUE TITLE
Iron Tank redundant recipes in assembler

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7348]
#### Which modpack version are you using?
2.10.0
#
#### What did you try to do, and what did you expect to happen?
I looked at NEI recipes for the various Iron Tank tanks.
#
#### What happened instead? (Attach screenshots if needed)
I saw that there are two assembler recipes for most of them- the same materials except the circuit is 1 or 4.
#
#### What do you suggest instead/what changes do you propose?
Use circuit 4 for all of them, I guess.  Looks like the extra recipes stop at titanium and above... but the aluminum tank has a circuit 1 recipe that uses an emerald plate for some reason.

**Comment by Prometheus0000** [comment]
Looks like it's already fixed. Try again on latest.

**Comment by McFrugal** [comment]
Latest is 2.1.0.0, which is the one I am playing.

**Comment by boubou19** [comment]
He meant the 2.0.1.4 version, the dev pack

**Comment by McFrugal** [comment]
Shouldn't this have the "fixed in dev" tag instead of "invalid", then?

**Comment by Prometheus0000** [comment]
It was fixed in an already released version (2.1.0.4), so no.
