### ISSUE TITLE
The craftpresence mod defaults to `/~, messing up the QB shortcut

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7351]
#### Which modpack version are you using?
2.1.02c
#
#### What did you try to do, and what did you expect to happen?
Use the QB
#
#### What happened instead? (Attach screenshots if needed)
Get the stupid CP thing
#
#### What do you suggest instead/what changes do you propose?
Remove CP. But seriously, make the default _some other key_. Or no key. And also add the ability to config it _from the key config menu_ if possible.
@jackowski626

**Comment by MatthewCOwen** [comment]
You can config the CP hotkey from within the accessibility settings in the craft presence menu.

**Comment by Prometheus0000** [comment]
> You can config the CP hotkey from within the accessibility settings in the craft presence menu.

> But seriously, make the default some other key.

I know how to change it, I just don't want to have to change it _every time I download a new version of the pack_ .

**Comment by GTNH-Afx237v7** [comment]
I tried changing it via the accessibility settings, it showed the newly assigned key, however upon pressing the new key nothing happened. Opening the accessiblity settings again showed that the original key was still assigned, as if I never changed it. Have since disabled the mod.

**Comment by Prometheus0000** [comment]
There's a save button at the bottom

**Comment by Prometheus0000** [comment]
@jackowski626 You still haven't fixed this in 2.1.03a.
