### ISSUE TITLE
Shard cast requires a brass plate instead of blank cast

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7357]
#### Which modpack version are you using?
2.10.0
#
#### What did you try to do, and what did you expect to happen?
I looked at the shard cast recipe and expected it to involve a blank cast
#
#### What happened instead? (Attach screenshots if needed)
There's a brass cast instead
#
#### What do you suggest instead/what changes do you propose?
Change the recipe to use a blank cast for consistency.  The fletching and bow string casts also have a second recipe using a brass cast that could be removed.

**Comment by GTNH-Afx237v7** [comment]
I think this is defined here:
https://github.com/GTNewHorizons/TinkersGregworks/blob/f2c7b0210f05183c4a57c7bde1e8e07069e66370/src/main/java/vexatos/tgregworks/integration/TGregRecipeRegistry.java#L180-L209

The config file for Tinkers Gregworks has the following entries:
```
# Enable the GregTech style Shard Cast recipe [default: true]
B:gregtechcastrecipe=true
B:ingotToShardRecipe=true
B:reverseSmelting=true
B:shardToIngotSmelting=true
B:shardToToolPartRecipe=true
B:solidifierRecipes=true

# Enable the Shard Cast recipe using Tinkers' Construct shards [default: true]
B:tinkersconstructcastrecipe=true
B:useNonGTFluidsForBolts=true
B:useNonGTToolRodsForBolts=true
```
I find it confusing that both GT styl shard casts and Tinkers' Construct shards are enabled?

**Comment by Dream-Master** [comment]
I am not sure but maybe they enabled because tinkers gregworks needs it ?

**Comment by GTNH-Afx237v7** [comment]
For better explanation:

There is a shaped recipe using a gregtech brass plate, a gt hammer, gt knife and gt file to make the tinkers gregworks shard cast.

Also there are 3 extruder recipes (each 30eu/t for 40 secs (800ticks)) to make said cast.

Recipe 1 and 2 are identical, both using a tinkers construct blank cast and tinkers construct obsidian shard.
Recipe 3 uses the gt brass plate and the above mentioned obsidian shard.

**Comment by GTNH-Afx237v7** [comment]
`B:gregtechcastrecipe=true` enables the above mentioned shaped recipe.
There are two distinct blankpatterns, one with meta:1 (made from aluminum brass) and one with meta:2 (made from gold)

So in order to use a tinkers blank cast in the shaped recipe, it maybe works with:

```
GameRegistry.addRecipe(new ShapedOreRecipe(
				new ItemStack(TGregworks.shardCast, 1, 0),
				" CH",
				" PF",
				"   ",
				'C', ToolDictNames.craftingToolHardHammer.name(), 'H', ToolDictNames.craftingToolKnife.name(), 'F', ToolDictNames.craftingToolFile.name(), 'P', "ItemStack(TinkerTools.blankPattern, 1, 1)"
			));
```
though I have no idea how to allow the second blank cast made from gold. Maybe copy / past with different meta below?

As for the extruder recipes:
Recipe 1 and 2 exist because, as stated above, you can make a blank cast from either aluminum brass or gold
Recipe 3 should not be in there, as it's actually disabled in the config?

**Comment by GTNH-Afx237v7** [comment]
If someone is willing and could give this a try (to replace this section here: https://github.com/GTNewHorizons/TinkersGregworks/blob/f2c7b0210f05183c4a57c7bde1e8e07069e66370/src/main/java/vexatos/tgregworks/integration/TGregRecipeRegistry.java#L203-L208)
```
GameRegistry.addRecipe(new ShapedOreRecipe(
				new ItemStack(TGregworks.shardCast, 1, 0),
				" CH",
				" PF",
				"   ",
				'C', ToolDictNames.craftingToolHardHammer.name(), 'H', ToolDictNames.craftingToolKnife.name(), 'F', ToolDictNames.craftingToolFile.name(), 'P', "TinkerTools.blankPattern, 1, 1"
			)
GameRegistry.addRecipe(new ShapedOreRecipe(
				new ItemStack(TGregworks.shardCast, 1, 0),
				" CH",
				" PF",
				"   ",
				'C', ToolDictNames.craftingToolHardHammer.name(), 'H', ToolDictNames.craftingToolKnife.name(), 'F', ToolDictNames.craftingToolFile.name(), 'P', "TinkerTools.blankPattern, 1, 2"
			)
```

**Comment by GTNH-Afx237v7** [comment]
So having discussed this today on Discord with Vexatos and for future reference:
The reason for being able to independently active/deactivate both the Tinkers style and GT style shard recipes is being able to use the Tinkers Gregworks without the smeltery module of tinkers (think making all tool parts solely in GT machines). It just happens that in GTNH both ways are enabled. 

One could add a smeltery recipe (obsidian shard (that is left over when obsidian is used in a part builder) and aluminum brass in casting table —> shard cast). Or disable the GT style recipe (Hammer, file and saw + brass plate —>shard cast) entirely.

The latter would make more sense as using a shard cast in GTNH is restricted to using it in an extruder.

**Comment by Prometheus0000** [comment]
@GTNH-Afx237v7 Did you forget about this?

**Comment by GTNH-Afx237v7** [comment]
This needs a decision on what to do, keeping in mind it is rather early-game which has been quite some time for me.

**Comment by Dream-Master** [comment]
blank cast match better i think.
