### ISSUE TITLE
Polybenzimidazole carbon fibre recipe is pointless

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7358]
#### Which modpack version are you using?
2.10.0

#
#### What do you suggest instead/what changes do you propose?
It takes 8 carbon and outputs 8 fibre.  The other carbon fibre recipes input 4 carbon, which means the molten epoxid-using recipe is just as efficient and takes less EU, as well as slightly less time per fibre.
The PBI-using recipe should input 4 carbon to make 8 fibre.

**Comment by GTNH-Afx237v7** [comment]
PBI is a later-tier chemical than Epoxid, so you will want to perform larger crafts and thus having 8 input to 8 output seems suitable. Carbon is abundant once you can (or need to) make PBI, therefore I don't see a 4 input to 8 outpus as necessary.

**Comment by McFrugal** [comment]
Huh?  Epoxid outputs 8 though.  There's no reason to use the PBI one.

**Comment by Glease** [comment]
PBI recipe should at least have its recipe time reduced. Currently it takes something more expensive, spend longer and use a higher voltage while producing basically the same stuff.

**Comment by Ethryan** [comment]
[Link](https://github.com/GTNewHorizons/GT5-Unofficial/blob/bc7ce8e5a6a9a2146fa61f0c0a09b83ecec4cf66/src/main/java/gregtech/loaders/postload/GT_MachineRecipeLoader.java#L472), seems someone missed that the stack limit is 64...
