### ISSUE TITLE
Platinum line rebalance

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7360]
So I am making a flowchart for the platinum line processing and I realised that the process for the platinum dust is chlorine positive, you litterally create chlorine out of nowhere, this should be changed.

To fix this and make the process renewable for chlorine I suggest changing the values for those two recipes : 

![image](https://user-images.githubusercontent.com/57050655/105204408-6a0be400-5b44-11eb-89a3-8ce15b4bb370.png)

change this to give 75L of chlorine instead if 87L

![image](https://user-images.githubusercontent.com/57050655/105204581-9fb0cd00-5b44-11eb-8ead-d89b4b4af4b1.png)
change this to give 1980 L of chlorine instead of 2000

now the process is perfeclty balanced.

![image](https://user-images.githubusercontent.com/57050655/105204669-ba834180-5b44-11eb-9680-220ec483c6ac.png)

find my flowchart here, correct me if I made mistakes : https://docs.google.com/spreadsheets/d/1zcxyhI1AcR90d1mpmI77elxmXtcGXtgS0G-H5KCiIo0/edit?usp=sharing

**Comment by Alexdoru** [comment]
> ![image](https://user-images.githubusercontent.com/57050655/105204581-9fb0cd00-5b44-11eb-8ead-d89b4b4af4b1.png)

Should we also change the amount of calcium of this recipe to 3 ? Because right now because of this recipe it is just voiding calcium for no reason

**Comment by alphaNOVAircraft** [comment]
The Calcium usage of the plat line is quite high atm

**Comment by feliser** [comment]
i like it how it is lets not buff it

**Comment by botn365** [comment]
> change this to give 1980 L of chlorine instead of 2000
that is illegal i prefer to have a small loss of chlorine then have it at 1980

**Comment by Alexdoru** [comment]
>  that is illegal i prefer to have a small loss of chlorine then have it at 1980

it's not a loss of chlorine, it's a gain of chlorine, otherwise we can only change the EBF recipe to 75L and not touch the electrolyzer recipe, it will result in an overall smaller chlorine gain

**Comment by botn365** [comment]
then it should be less then 75L so it would be a small loss

**Comment by Alexdoru** [comment]
make it 74L then, and how about the calcium loss ?

**Comment by Eason134HK** [comment]
does rebalance mean i have to rebuild my platinum line?

**Comment by boubou19** [comment]
@Eason134HK It just means that some values will be modified, not the actual items used in the recipe. So your platinum line will be fine.

**Comment by Florexiz** [comment]
2000->1980 is just *wrong*
Please, dont do this

**Comment by Prometheus0000** [comment]
@bartimaeusnek Are you going to do anything here, or can we close this?
