### ISSUE TITLE
Large Steam Turbine and its quest + fluid regulator

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#7361]
#### Which modpack version are you using?
2,1
#
I found myself in a pickle with the Large Steam Turbine (LST). 

This will be a long one sorry.

Agenda
Energy output analysis of suggested materials.
New player introduction to turbines and all that.....
Suggestions for changes. 

--------------------------------------------------------------------------------

First here is a list of the quest descriptions materials suggested to be used to create small turbines

If you look here at the suggested materials for usage for turbine blades.
![image](https://user-images.githubusercontent.com/3405825/105260603-5d13e280-5b8e-11eb-8c30-db12a431ff07.png)

The turbine unlocks with Tier-4 (HV).
My problem is with the suggested materials, now you cant make anything other than small turbines until you have been on the moon and acquired titanium. And this was just unlocked with HV, so it will be a long time before they have a rocket and space suit ready.

So players are stuck with choosing a small turbine made out of the 5 suggested materials.

If you look at the power output of the small turbine blades material suggested, as well as what is required to make it.

Blue Steel - 168 eu/t
Damascus Steel- 160 eu/t
Ultimet - 160 eu/t - Kanthal coils + Vacuum freezer       
Ardite - 405 eu/t - Kanthal coils + Vacuum freezer
Vibrant Alloy - 405 eu/t - Kanthal coils + Vacuum freezer

At HV when all this unlocks, blue steel and Damascus steel are the only two that can be made, until the player unlocks Kanthal coils and the vacuum freezer. 

From my point of view, getting about 160eu/t is not worth it for the resources required to build the LST.
So if new players CAN figure out all the complicated things with steam usage, energy, and efficiency, they would wait till they can use Ardite or Vibrant Alloy. 

Now with regards to Ardite, I have never found more than a few blocks of that, even in HV. I have found it hard to locate more than a single block here and there in the Nether, so let's remove Ardite as an option for turbine blades for now.

Ultimet when the player can make it, the small turbine can only produce 160eu/t, the normal turbine one after moon access produces 517eu/t.

This leaves only Vibrant Alloy along with a buffered HV dynamo, that pre moon with small turbine blade produces 405eu/t and after moon with normal turbine blade 1035eu/t

From this small analysis, it looks like vibrant alloy is the only option that is worth it, with a 1amp dynamo and a small turbine blade. Even after the moon with a normal turbine blade, I find that I personally stay with it for a while.

--------------------------------------------------------------------------------

Now I remember the first time I had to figure out turbines and efficiency, as well as optimal flow,  tick vs seconds flow rate......

If you look at the recipes ( for a new player NEVER having done turbines before, figuring out the stats can be daunting.)
All this is complicated for new players (I have helped a few over the years figuring this out, and was helped when I started)

I would suggest a new quest series be added to learn multiblock turbines. (be it the steam one or gas (benzene))

An introduction quest, that tells the player to construct the components for the turbine, like it is now.

After that a quest that shows how to build a turbine and how to figure out the blade calculations. Now this quest could be a link to an online wiki and or the GTNH spreadsheet. If possible we could just add the descriptions of the basic with a picture or two to the quest description (I don't know if better quests support images in the description) otherwise a wiki link would be best.

After this, the fluid regulator is needed. pre mood to give the LST enough steam at the correct rate for Vibrant or Ardite 18.000 L/sec is needed, but the HV fluid regulator stops at 10.240L/sec. The Regulator quest also links to the plasma turbine, but all GregTech fluid regulators cant be used with the plasma turbine and Helium-3 as even the LV regulator cant be turned down to the low level of fluid required for optimal fule usage of the plasma turbine.
It works on the IC2 Fluid regulator, both for the 18.000L/sec steam and the low and slow rate of Helium-3 that is needed for plasma turbines. 

The Turbine as it is now unlocked at HV but the HV dynamo requires energetic alloy to make, and that requires a vacuum freezer and kanthal coils, so maybe unlock the quest after that?

--------------------------------------------------------------------------------

PS.
The quest description, says what was removed ( why does a new user need to know what is not there if they are removed? ), can we not remove this unneeded information?

**Comment by Prometheus0000** [comment]
You can't make shadow?

**Comment by Devtron3D** [comment]
I had shadow on my list, but as of my current level ( about to kill the wither) I have yet to start Thaumcraft so i don't have access to its metal that is needed for the shadow steel. 
A

**Comment by Prometheus0000** [comment]
Shadow, shadowiron, and shadow steel are all different things. Shadow is researched on the malefica/forbidden magic page I think, and you make the ore itself. I'm pretty sure it's HV or even MV.
