### ISSUE TITLE
(Bug) (Thaumcraft) Certain recipes can't be completed due to undefined aspects.

### ISSUE THREAD

**Issue by MRJones3206** [GTNewHorizons/GT-New-Horizons-Modpack#7362]
#### Which modpack version are you using?
2.1.0.0
#

#### If in multiplayer; On which server does this happen? 
Bug occurs on both MP and SP. 
#

#### What did you try to do, and what did you expect to happen?
Followed normal Thaumcraft research progression. Attempted to research Crafting Focus (Automagy) and Planar Theory (Thaumic Horizons). Normally Thaumcraft research will either show all the aspects you need to connect to complete the research, or a '?' symbol if you have not discovered an aspect. Rarely research will have no aspects to connect, in which case the research can be completed by placing any aspect on the page.
#

#### What happened instead? (Attach screenshots if needed)
The previously mentioned recipes were created with an undefined aspect (upper right of attached image). The aspect could not be connected to by any other aspect - including child or parent aspects of the aspect that should have been present - making the research impossible. Screenshot of issue and reference to the related recipe changing scripts are provided below.

![UnknownAspect](https://user-images.githubusercontent.com/77698421/105433022-a9523780-5c0d-11eb-9aee-05284452ddfb.PNG)

Crafting Focus (Automagy)  - https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/scripts/Automagy.zs
Line 247 - 253

Planar Theory (Thaumic Horizons) https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/scripts/Thaumic-Horizons.zs
Line 29 - 32

Bug can be most easily seen/reproduced by completing the 'Wand Foci' research prerequisite in the Thaumaturgy tab and then creating a research note for 'Wand Focus: Crafting' under the Automagy tab. Aspects can be either researched normally or unlocked with the dev command '/tc aspect "playername" all 100'.

#
#### What do you suggest instead/what changes do you propose?

One firm application of Bug Busting (tm).

**Comment by Prometheus0000** [comment]
I don't see any typos, so I'm not sure what we would change to fix it? Did you try changing the script to fix it locally?

**Comment by MRJones3206** [comment]
Looks like my version of the scripts were downloaded before this was fixed.

Automagy.zs and Thaumic-Horizons.zs had typos that were fixed by [2794c3c](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/2794c3c894e9e852a5b15b49521e6af05cfc3da1#diff-44b42d4841362cf17d7c98d34604264a2904a3fd306dd924df040821ff434e4b) and [74618b4](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/74618b465faf2319d5212350b16ed7c67f63d8d9#diff-8b18ee6534d15f8684dcdb3050cde176fbabe75b21ba6f3d35b5cca94538162b) respectively. After applying those locally everything worked like a charm.

Sorry for the false alarm!

**Comment by Ethryan** [comment]
Close this when next version is public
