### ISSUE TITLE
Show multiblock construction details of the opaque block in Multiblock Machine Blueprint

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#7364]
![q1](https://user-images.githubusercontent.com/62897714/105470835-0533c380-5cd5-11eb-8370-a0ab41834058.jpg)
It can help new players to correct the construction problems of multiblock.

**Comment by Dream-Master** [comment]
@Technus @basdxz is this possible ?

**Comment by Prometheus0000** [comment]
Only if it uses the tectech structure check (as far as I know), as what bart did for a couple. I still want to know why he put the code in BW though.
