### ISSUE TITLE
Items crafted in Forestry worktable does not count towards crafting quests

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#7366]
#### Which modpack version are you using?
2100
#
#### If in multiplayer; On which server does this happen? 
my server
#
#### What did you try to do, and what did you expect to happen?
--
#
#### What happened instead? (Attach screenshots if needed)
There is a bug in Crafting Task, cannot finish the task on the Forestry Worktable. 
#
#### What do you suggest instead/what changes do you propose?
Change all the task to retrieval task.

**Comment by Dream-Master** [comment]
No you need to craft those items in a vanilla crafting table or in a tinkers one.

**Comment by iouter** [comment]
> 不，您不需要在香草制作桌或修补匠中制作这些物品。
But if I accidentally use the forestry worktable to craft some items, I have to use the edit mode or command to force the task to complete. this is annoying.

**Comment by iouter** [comment]
> No you need to craft those items in a vanilla crafting table or in a tinkers one.

But if I accidentally use the forestry worktable to craft some items, I have to use the edit mode or command to force the task to complete. this is annoying.

**Comment by Glease** [comment]
Fixed by GTNewHorizons/ForestryMC#7

**Comment by Prometheus0000** [comment]
So does this mean that all crafting tasks can be done in the forestry worktable now?
