### ISSUE TITLE
Use same level circuit in data bank and research station's recipe.

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#7367]
#### Which modpack version are you using?
2100
#
#### If in multiplayer; On which server does this happen? 
my server
#
#### What did you try to do, and what did you expect to happen?
--
#
#### What happened instead? (Attach screenshots if needed)
only nanoprocessor mainframe used in the recipe  of data bank, only crystalprocessor mainframe used in recipe of Research Station.
#
#### What do you suggest instead/what changes do you propose?
use same level circuit in data bank and research station's recipe.

**Comment by Prometheus0000** [comment]
Is this an assline recipe? Are you asking for ordict in it? More info needed.

**Comment by GTNH-Afx237v7** [comment]
Sounds like a request for ore dictionary to me...

**Comment by Prometheus0000** [comment]
Which doesn't work for the assline, which is why I want to know.
