### ISSUE TITLE
[Suggestion] Add a quest explaining the modpack's chunkloading meta

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7371]
Newer players are confused with the chunkloading options and they should be informed right from the start that they can use as much chunkloading as they want to make the farm/processing less painfull. Right now this is said in the questbook but it's only a single sentence in a side quest in LV.

We should add an information quest named "Chunkloading in GTNH"  in the tips and tricks tab that is unlocked as soon as stone age (that's when you get the bricked blast furnace) that states : 

"The chunkloading options in this modpack are balanced around the official servers to not put too much stress on the servers.
However if you are playing in singleplayer or on your own server feel free to use as much chunkloading as you want and do it for free. You can do that by cheating admin anchors from railcraft or add to the game a chunkloading mod like FTButilities or chicken chunks. Both of those mods work well with GTNH."

**Comment by Prometheus0000** [comment]
Do they though? I heard some mods' chunkloading doesn't always work right. And does FTButil's backup conflict with aroma, with it now being in the pack by default? You don't need it backing up twice in a row, so I'd like to mention it if it's a problem. Also, if we add this, I'd like to remove the other chunkloading quests, and just mention the anchors here.

**Comment by Alexdoru** [comment]
MY bad, I never used FTB utils, but I have been using chicken chunks for two years now and it works perfectly.

**Comment by icha-senpai** [comment]
you can disable the backup feature in ftb utilites config (/local/ftbu/config.json)

**Comment by Prometheus0000** [comment]
The question is whether I need to tell people that in the quest or not.

**Comment by icha-senpai** [comment]
i think adding to the "back up your stuff" tip or adding a chuck loading tip could be a good idea in the tips and tricks quest line also at the same time mentioning that your able to disable the ftb utilities back ups in the tip in case you prefer to use aromas backups and ftb's chunkloading
