### ISSUE TITLE
A quite different storage #119 Issue with filing cabinets 

### ISSUE THREAD

**Issue by Obeliske1** [GTNewHorizons/GT-New-Horizons-Modpack#7372]
#### Which modpack version are you using?
1.7.1 The most up to date one

#### If in multiplayer; On which server does this happen? 
I would assume all of them? Though I am currently running a server for a small group of friends

#### What did you try to do, and what did you expect to happen?
Built a filing cabinet to use to store bees and bee related items, as per the quest itself it can be used to store bees

#### What happened instead? (Attach screenshots if needed)
The cabinet will not accept any bee related item nor bees with the exception of combs

#### What do you suggest instead/what changes do you propose?
Either change the quest text to give a better idea of what will go in it or fix it so that anything can go in it.

**Comment by Obeliske1** [comment]
Just tested, it will take the Forestry for Minecraft backpacks but no armor or weapons from vanilla Minecraft either (which again are specifically called out in the quest text as a thing that can be stored in it).

**Comment by Prometheus0000** [comment]
> 1.17 The most up to date one

This is not a version that GTNH runs on, much less a version of GTNH BTW

**Comment by Obeliske1** [comment]
This is the one I'm running it says in the top corner 1.7.10 Beyond that I'm unsure. 

https://www.curseforge.com/minecraft/modpacks/gt-new-horizons

I played online for a month on the crafterslands servers and enjoyed it enough I got some friends to want to play and so rented a server and muddled through the installation. Haven't actually played MC in 5-6 years beyond that, So if I got the version wrong I'm sorry.

It is however still the newest version of the modpack released late December.

**Comment by Prometheus0000** [comment]
Don't use curseforge, it's endlessly causing problems for this pack. Though it's probably not responsible for this.

**Comment by Obeliske1** [comment]
Whelp I don't know what to say, server runs a little choppy sometimes but it's definitely server side lag which is likely the host. Otherwise we got people all over the place with no issues, this is the first bug I have seen and my 6 other friends haven't told me about coming across any issues. Where would you suggest I do it from next time?

**Comment by Prometheus0000** [comment]
Use a different launcher like technic or multimc. CF has problems, like: not having the same files so you can't connect to a server, not downloading dependencies (mods) so you can't launch, being out of date but saying a different version just to confuse you more, being a giant pain to update, and so on. For the actual download, go to the discord and check the announcements channel or use the !downloads command, though I think technic doesn't need that.

**Comment by Glease** [comment]
I don't think the filing cabinet issue can somehow relate to launcher, unless it is a issue that has been fixed in one of our coremods and a broken launcher doesn't want to download that mod.

**Comment by Obeliske1** [comment]
As of yesterday these started working inexplicably and I don't seem to be able to reproduce what they were doing before so I've closed this.
