### ISSUE TITLE
Weird Sunnarium recipe

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#7373]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta 
#

There is this recipe
![image](https://user-images.githubusercontent.com/62377720/105551434-00860400-5d03-11eb-935a-cb281fc605f7.png)
And then this one 
![image](https://user-images.githubusercontent.com/62377720/105551591-21e6f000-5d03-11eb-94d5-64fe4e44a9e3.png)

Is that intended ?

**Comment by Ethryan** [comment]
Found it: [Link](https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/b4b06004ca5124658b24d4fa9c1d183aabae0ba6/src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java#L1086)

**Comment by GTNH-Afx237v7** [comment]
So I guess

`(OrePrefixes.dust, Materials.Sunnarium, 4L)`

needs to be 

`OrePrefixes.dust, Materials.Sunnarium, 1L)`

?

**Comment by Prometheus0000** [comment]
That would indeed change it from 4 to 1

**Comment by GTNH-Afx237v7** [comment]
Think you have a working dev environment to test it just to be sure? Then it would be an easy and quick fix.

**Comment by GTNH-Afx237v7** [comment]
:D now people can happily macerate and compress sunnarium back and forth

**Comment by bartimaeusnek** [comment]
@Ethryan have you checked what happens if you macerate piles of sunnarium?

**Comment by Ethryan** [comment]
no, i didn't know you could macerate a dust
