### ISSUE TITLE
Wrong required quest in Blood Magic quest book page

### ISSUE THREAD

**Issue by OriginalBacer** [GTNewHorizons/GT-New-Horizons-Modpack#7376]
#### Which modpack version are you using?
2.1.0.0
#### If in multiplayer; On which server does this happen? 
Private server / Same in Single
#### What did you try to do, and what did you expect to happen?
Quest on craft Magician orb need Titanium bees to open quest.
#### What happened instead? (Attach screenshots if needed)
<img width="882" alt="1" src="https://user-images.githubusercontent.com/2857859/105609658-6d58d700-5db3-11eb-9d6b-e0a8bbefa089.png">
<img width="838" alt="2" src="https://user-images.githubusercontent.com/2857859/105609661-7053c780-5db3-11eb-81fc-fd032519e149.png">

#### What do you suggest instead/what changes do you propose?
Change required quest on "Titanium Finally" like on thaumcraft quest book page.

**Comment by Prometheus0000** [comment]
Whoops. Those quests are pretty unclearly named though.

**Comment by Ethryan** [comment]
Maybe add something like “Bee: Metal” to make it easier to separate from ordinary quests.
