### ISSUE TITLE
Sulfuric acid quest STILL gives incorrect instructions

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7378]
#### Which modpack version are you using?
2.10.0

#
#### What did you try to do, and what did you expect to happen?
It says "you can always make sulfuric acid with sulfur and water in the chemical reactor" when that is not possible.  There's two ways to make sulfuric acid:
1, via the sulfur dioxide -> trioxide process
2, by distilling diluted sulfuric acid, which you can get in the chemical reactor from hydrogen sulfide + water.

The quest text doesn't flow very well before that either, to be honest.  It starts out properly explaining the main way to get sulfuric acid, via sulfur trioxide, then mentions hydrogen sulfide, which should not be used to make sulfur dioxide IMO since it's more efficient to use sulfur dust for that step.

#
#### What do you suggest instead/what changes do you propose?
Rewrite it to state both methods of getting the acid, and also that both hydrogen sulfide and sulfur dust can be used to make sulfur dioxide but hydrogen sulfide can more easily make diluted acid.

**Comment by McFrugal** [comment]
I'm guessing the rewards are old too.  It gives sulfur dust and water.  Change it to sulfur dust and oxygen perhaps?

**Comment by Prometheus0000** [comment]
I guess dream didn't fix it properly #5174?
