### ISSUE TITLE
Radioisotope Thermoelectric Gen 16eu/t only

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7380]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
i try to use the Radioisotope Thermoelectric Gen 
![image](https://user-images.githubusercontent.com/59776356/105623691-81094980-5e56-11eb-9f15-3876bbec7be4.png)
the quest say it can give up to 32EU/t 

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/105623675-63d47b00-5e56-11eb-853a-3eb92a5c2724.png)
![image](https://user-images.githubusercontent.com/59776356/105623680-6931c580-5e56-11eb-8db4-a7f6aa22d4cb.png)
not sure if it is waila error or quest book error or the Radioisotope Thermoelectric Gen unable to provide enough power due to unknown reasons.
#

**Comment by Prometheus0000** [comment]
How weird, I swear it was 32 when I tested it.

**Comment by GTNH-Afx237v7** [comment]
Did you check with tricorder, maybe attach a cable and see how much is coming out? Just as a means of verification.

**Comment by Eason134HK** [comment]
> How weird, I swear it was 32 when I tested it.
maybe waila is wrong

**Comment by Eason134HK** [comment]
> > How weird, I swear it was 32 when I tested it.

maybe waila is wrong

**Comment by Eason134HK** [comment]
> How weird, I swear it was 32 when I tested it.

![image](https://user-images.githubusercontent.com/59776356/105648582-3552b080-5ee7-11eb-964d-88da1ac43e5c.png)
the it do say Power output : 1-32 EU/t Max

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/107684219-834e0f00-6c70-11eb-89bd-03bc61f11f0a.png)
Waila lies to you here.
