### ISSUE TITLE
Thaumic Tinker Ichorium Ingot research has unnecessary & unspecified research tied to it

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#7382]
Simple. You type `/iskamiunlocked`, receive a 'Yes' message, and complete the Ichor research, but you do not unlock Ichorium Ingots despite the obvious & noticeable unlock. The problem likely stems from recent mods being added that likely and somehow made 'Ichorium' require more research and or a script problem. I am unsure how to find out what is required for Ichorium unlock or how to fix it, but it is a very noticeable and obnoxious problem that requires players to go on a wild guessing goose-hunt to find out what is required for Ichorium.

**Comment by Dream-Master** [comment]
that is because some script look it and the command not work on it. Maybe we need to put those research in code that look ichorium.

**Comment by Yarntheory** [comment]
I was able to successfully narrow down the researches. Ichorium does require the Gregtech nugget duplications researches, but Ichor/Ichorcloth does not. 

This might be solvable with quest notes too.

**Comment by KiloJoel** [comment]
> 
> 
> I was able to successfully narrow down the researches. Ichorium does require the Gregtech nugget duplications researches, but Ichor/Ichorcloth does not.
> 
> This might be solvable with quest notes too.

That can't be the only difference. I have the nugget duplication and ichorcloth, but not ichorium

**Comment by prosbloom225** [comment]
The void metal crowbar from Eldritch is required for Ichorium Ingots, but the Thaumium Crowbar from Artifice is not required for Ichorium.

**Comment by bombcar** [comment]
aluminum transmutation also needed
