### ISSUE TITLE
GT Miner does not mine stardust ore in End

### ISSUE THREAD

**Issue by dimondmine2** [GTNewHorizons/GT-New-Horizons-Modpack#7383]
#### Which modpack version are you using?
GTNH 2.1.0.2c
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Placed miner on igneous island in End, expected miner to mine Stardust ore
#
#### What happened instead? (Attach screenshots if needed)
HV minder does not mine stardust ore. Stardust ore ID is 846
#
#### What do you suggest instead/what changes do you propose?
Add block ID 846 to list of blocks GT miners dig up.

**Comment by Prometheus0000** [comment]
That's not how it works. It _might_ not work because of not having an oredict? I'm not sure.

**Comment by dimondmine2** [comment]
I'm not sure either, I'm mainly just trying to flag the issue

**Comment by Dream-Master** [comment]
Block id's differ so in your game it is 846 in another game it's totally different. We fork hee source so maybe somone is able to add compability.

**Comment by repo-alt** [comment]
If it is oredicted as "oreSomething" then it should just work.

**Comment by GTNH-Afx237v7** [comment]
Seems to be registered as oreDict:
https://github.com/GTNewHorizons/Hardcore-Ender-Expansion/blob/f3c0aa881cb81900a844d6b476a087ba7656566a/src/main/java/chylex/hee/init/BlockList.java#L246

**Comment by repo-alt** [comment]
Well, yes it is, but it is registered with meta 0, and in the world it is with meta 11 for some reason.

**Comment by bartimaeusnek** [comment]
just register all 16 metas and we are fine...

**Comment by repo-alt** [comment]
Do we have HEE maintainer?

**Comment by Dream-Master** [comment]
yes

**Comment by repo-alt** [comment]
In that case it would be better if he looks at it himself

**Comment by repo-alt** [comment]
Like, register all 16 meta indeed, or something..

**Comment by dimondmine2** [comment]
Issue still open
