### ISSUE TITLE
Igneous Ore Block required by questbook. Why?

### ISSUE THREAD

**Issue by dimondmine2** [GTNewHorizons/GT-New-Horizons-Modpack#7384]
#### Which modpack version are you using?
2.1.0.2c
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Complete quest Visit the Fiery Island in the HEE quest tab reasonably.
#
#### What happened instead? (Attach screenshots if needed)
Quest tab asks you to get igneous rock ore blocks, which can only be gotten through silk touch and has no use except to macerate into igneous rock.
#
#### What do you suggest instead/what changes do you propose?
Remove requirement to get igneous rock ore blocks to complete the quest.

**Comment by Prometheus0000** [comment]
Dream added a bunch of silly requirements to the HEE quests like this.

**Comment by Dream-Master** [comment]
Why silly? make it better

**Comment by Prometheus0000** [comment]
Like impossible to get items, requiring people to get large amounts of utterly useless items, especially ones you need to use silk touch pickaxes or shears to get, requiring people to find 64 towers, for the 1 block you need from them (might have been only 16), stuff like that.

**Comment by dimondmine2** [comment]
I don't understand what is better about a out-of-the-way requirement? Why make three rights when I can make a left?

**Comment by Dream-Master** [comment]
i reduce the amount but the rock is still in. I will add more useful recipes to use Hee materials like ender goo etc.
