### ISSUE TITLE
Burn time tool tip disappeared

### ISSUE THREAD

**Issue by Ydrec** [GTNewHorizons/GT-New-Horizons-Modpack#7385]
#### Which modpack version are you using?
2100
#
#### If in multiplayer; On which server does this happen? 
Single or any server
#
#### What did you try to do, and what did you expect to happen?
NEI should show burn time on items which can burn 
![2-for-minecraft-11](https://user-images.githubusercontent.com/53411693/105642587-a40a1c80-5e9b-11eb-9a57-ae314ac74fb0.jpg)
#
#### What happened instead? (Attach screenshots if needed)
NEi dont show burn times on items which should burn
![2021-01-24_23 27 52](https://user-images.githubusercontent.com/53411693/105642614-d156ca80-5e9b-11eb-8db2-55ed1877f99a.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it, plz.

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/EnderIO/pull/28
