### ISSUE TITLE
Potin Fluid Pipe Input Visual Bug

### ISSUE THREAD

**Issue by r2go-beep** [GTNewHorizons/GT-New-Horizons-Modpack#7387]
#### Which modpack version are you using?
2.1.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Potin Fluid Pipes do not show the visual grey ring to demonstrate they are blocking input from a certain direction.
#
#### What happened instead? (Attach screenshots if needed)
No visual "Grey Ring" appears on any of the faces of the Potin Pipes
https://cdn.discordapp.com/attachments/234936569360809996/803137101008732160/2021-01-24_23.34.30.png
#
#### What do you suggest instead/what changes do you propose?
Add the visual grey ring

**Comment by mitchej123** [comment]
Gt++ issue.  I believe there is no intention of fixing it
