### ISSUE TITLE
Biomass redundancy

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7388]
#### Which modpack version are you using?
2.10.0

#
#### What did you try to do, and what did you expect to happen?
Tried to figure out how to make ethanol from biomass
#
#### What happened instead? (Attach screenshots if needed)
It's extremely confusing because there are two fluids with slightly different colors sharing the same name, but there are different recipes involving them.
#
#### What do you suggest instead/what changes do you propose?
Either change the name of one of them or unify them so that they use the same recipes.

**Comment by ToastedEggplant** [comment]
One of them requires biochaff (IC2 Biomass) and needs to be fermented before making ethanol and the other one requires one of 150 different crops and does not require fermentation and goes to from biomass ethanol directly in a distillery(Forestry Biomass). I think the names should be changed to avoid confusion if the separate recipes were intended. Is there anyone who knows if this was intended or not?

**Comment by 0lafe** [comment]
i'd personally suggest keeping both. the ethanol one is great for HoG, and the other is good for lots of early game stuff imo
