### ISSUE TITLE
[RFC] Better hotfix and release policy

### ISSUE THREAD

**Issue by Skiftcha** [GTNewHorizons/GT-New-Horizons-Modpack#7389]
#### Which modpack version are you using?
2.1.0.0
#
#### What did you try to do, and what did you expect to happen?
i (and not only me) want fixes and improvements from 2.1.0.2c and maybe some more not yet included
i expect that some time after new release i can update to hotfix version and get most new bugs fixed.
#
#### What happened instead? (Attach screenshots if needed)
instead 2.1.0.2c includes a bunch of reworks and game breaking changes/rebalancing. it is more that 2 weeks on zeta and is not ready to be on "production" servers including official servers and private instances
we have a lot of bug reports that are already "fixed in dev" but cannot be delivered to users.
#
#### What do you suggest instead/what changes do you propose?
hard question.
because this may require extra work from dream to create mod pack archive.

i think if pack include some reworks it need to be at least 2.1.1.0 or something like this.
2.1.0.2c should include only hot fixes
maybe we need code freeze after release for new reworks and rebalancing so we have time for release stabilising.
maybe we need to create stable branches/labels so fixes can be cherry-picked and released asap

**Comment by repo-alt** [comment]
omg, what next, scrum meetings?

**Comment by Dream-Master** [comment]
The idea have a hotfix branch and a dev branch are nice but sadly  I don't have the time and the mean power to make this happend. If 2.1.0.2c is to buggy please use 2.1.0.0. If you willing to take care of a hotfix branch go ahead and help me with it.

**Comment by Dream-Master** [comment]
@Skiftcha
