### ISSUE TITLE
Volcanus overclocking

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7390]
#### Which modpack version are you using?
GTNH 2.1.0.0
#

When the volcanus reachs the one tick limit it continues to overclock the power input even thought it's not making the recipes go faster considering it already takes one tick. Thus it is voiding a lot of energy for nothing. This isn't the same behavior as other GT machines/multi.

here at UEV
![image](https://user-images.githubusercontent.com/57050655/105727139-0f4eff80-5f2b-11eb-8fc7-05d04ad41ae0.png)

here the same recipe at ZPM
![image](https://user-images.githubusercontent.com/57050655/105727181-1b3ac180-5f2b-11eb-896f-07947b8c0b29.png)

**Comment by GTNH-Afx237v7** [comment]
The volcanus is GT++, think you should report it at Alk‘s GitHub https://github.com/alkcorp/GTplusplus

**Comment by Alexdoru** [comment]
I know of the gt++ github but I think that Alk isn’t updating the mod anymore and that a dev from GTNH is now handling the mod

**Comment by Prometheus0000** [comment]
This isn't true at all. It might become true in the future, or might not. Depends on stuff, and is unlikely to happen any time soon.
