### ISSUE TITLE
Quest book still reference To Grind, or Not to Grind

### ISSUE THREAD

**Issue by Isoarcree** [GTNewHorizons/GT-New-Horizons-Modpack#7391]
#### Which modpack version are you using?
2.1.0.0
#

#### What did you try to do, and what did you expect to happen?
The quest "Breed some imperial bees" (#1121) still references getting the Master Registry in the To Grind, or Not to Grind quest tab.

**Comment by Prometheus0000** [comment]
BTW, the quest itself was moved to the bee page if you didn't know.
