### ISSUE TITLE
some minor but painful issues I found

### ISSUE THREAD

**Issue by wakasagisan** [GTNewHorizons/GT-New-Horizons-Modpack#7395]
#### Which modpack version are you using?
2.10.0.0
#
#### If in multiplayer; On which server does this happen? 
It's singleplayer
#
#### What did you try to do, and what did you expect to happen?
1st, I accidentally placed my endertank into an input hatch and expect nothing to happen
2nd, I placed a personal anchor on GC planets with pearls to load my ore drill to keep it loaded
#
#### What happened instead? (Attach screenshots if needed)
for the first issue, the endertank was consumed as a cell that only has mB of liquids, which made me reloaded my backup since it's really expensive;
for the second issue, the personal anchor seems to fail after a prolong period of time. I have to go back to the dimension then it starts working again for some reason. It's really painful to do this due to this rocket pollution nerf and the fuel nerf.
#
#### What do you suggest instead/what changes do you propose?
for the first issue, I hope some adjustment can be made to the property of the endertank to make it not consumable by the hatches; for the chunkloading issue in SP, I wish either better alternative can be provided or have the coding adjusted to keep the dimension loaded without using an admin anchor

**Comment by repo-alt** [comment]
1. Don't do that?
2. There is nothing wrong in giving yourself some admin anchors in SP

**Comment by GTNH-Afx237v7** [comment]
The personal anchor will load its area after the owner has visited, so after server restart you need to go there and visit it. A world anchor, that you can craft, will keep the area loaded. 
From my experience, the world anchor is just fine, make sure to put enough chunkloader coins in.

**Comment by dvdmandt** [comment]
You can't get chunkloader coins in SP though (except like one from quest rewards)..?

**Comment by wakasagisan** [comment]
> 1. Don't do th
> 2. There is nothing wrong in giving yourself some admin anchors in SP



> You can't get chunkloader coins in SP though (except like one from quest rewards)..?

you can make them with chemical reactor I think.

**Comment by Dream-Master** [comment]
> You can't get chunkloader coins in SP though (except like one from quest rewards)..?

You can make them in sp but not on the server.
