### ISSUE TITLE
Pest Control crashes server

### ISSUE THREAD

**Issue by fabiobuhr** [GTNewHorizons/GT-New-Horizons-Modpack#7396]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Pest Killer 3209 crashes the server as soon as it ticks the first time, it was filled with Formaldehyde
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Fix issue

**Comment by Prometheus0000** [comment]
Make an issue at the GT++ tracker
