### ISSUE TITLE
Electrolyser/Centrifuge : Suggestion

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#7400]
#### Which modpack version are you using?
2.1.0.0
Now as you know you can process dusts in the centrifuge and the electrolyser
Tell me if I'm wrong but :
Centrifuge is supposed to be used for separating molecules 
Electrolyser is supposed to be used for separating elements

So if this is true,I don't understand some recipes
Here are some examples : 
- 2 Realgar dusts gives 1 Sulfur and 1 Arsenic
![Realgar](https://user-images.githubusercontent.com/62377720/106156513-e96f6800-6181-11eb-8032-39e12f440aae.PNG)
It separates the dust and gives the elements so it should be in the electrolyser and not in the centrifuge
this is the same for yellow and brown limonite as you can see : 
![Yellow lim Centri](https://user-images.githubusercontent.com/62377720/106156828-4ec35900-6182-11eb-8b33-c9f0b518924f.PNG)
![Brown Lim centri](https://user-images.githubusercontent.com/62377720/106157000-83371500-6182-11eb-8685-a8c75b9f7036.PNG)

For another example, there is the Red granite
- 6 dusts gives 2 Aluminium, 3 Oxygen and 1 Potassium feldspar as you can see 
![Red granite Elec](https://user-images.githubusercontent.com/62377720/106157209-bf6a7580-6182-11eb-9ae7-5f85fc81a569.PNG)
So as the recipe separates elements and molecules, it should be in a centrifuge

They are other examples but I will not obviously show them all here.
Well Maybe something I can't understand is behind this, like balancing the game or some oher explication, but I just want to understand why it is like that, and, if it's not inteed, consider a possible change.

I've searched for an issue like that but I wasn't able to found one, so if it's a duplicate I'm sorry.

**Comment by dvdmandt** [comment]
So I'm not saying what we have makes sense, nor do I really know this chemistry (especially in English). Centrifuging is to my understanding basically about taking mixes of small particles/grains/fluids and separating them into different layers (piles). Electrolysis is more about splitting molecules that are bound together in certain ways into smaller molecules and/or atoms. To split other stuff, you'd need acids or other chemical reactions to break apart molecules.

So whether or not it makes sense to electrolyse, centrifuge or use chemical reactions to split dust into separate components depends entirely on the chemical structure of said dust. Also, a lot of things are overly simplified for technical and/or gameplay reasons. For example, the chemical formulas or whatever don't differentiate between mixes and molecular structures. 

I'm also pretty sure you would need two types of dusts for alloys, one pre-smelt that can be centrifuged into its components and one post-smelt that can't, but I don't think anyone actually cares that much.

If you know more about the specific structures of specific materials/minerals/whatever and processes used in real life for those, feel free to propose changes to those. Note however that realism is not really the main focus, but rather to be somewhat believable while also being somewhat varied in terms of processes etc for gameplay reasons.

**Comment by Nicouuuuu** [comment]
Well I don't try to fit real life as much as possible, it is obviously not the main point of the game as you said and I agree with that.
Indeed Electrolysing IRL is absoutely not valuable in the game like it's just for some applications to make H2 or Chlorine for example.
I can provide some informations about material structure for iron and steels for example but as you said I'm also not sure if anyone want to bother with different types of Steels/Irons depending on the cooling rate the pression and the temperature haha...
I was talking mainly about the gameplay to clearly separate the utilisation of those 2 machines. Because at the moment I'm feeling like those 2 machines are doing the same things but with recipes randomly splitted.
So I was just thinking of using electrolyser to separates atoms
and centrifuge to separate molecules mainly

**Comment by Nicouuuuu** [comment]
:boubs_glasses:
