### ISSUE TITLE
Rape seed name change - requested by Dream

### ISSUE THREAD

**Issue by Nyagi** [GTNewHorizons/GT-New-Horizons-Modpack#7401]
#### Which modpack version are you using?
Latest 2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta

#### What do you suggest instead/what changes do you propose?
Change the Rape seed name to Canola or "Brassica napus" if you want the scientific name

**Comment by Prometheus0000** [comment]
Personally, I'd think changing crop to cropstick would be a better change. Plus I brought this up before but no one seemed interested in changing it.

**Comment by KiloJoel** [comment]
> 
> 
> Personally, I'd think changing crop to cropstick would be a better change. Plus I brought this up before but no one seemed interested in changing it.

why not both

**Comment by Nyagi** [comment]
> Personally, I'd think changing crop to cropstick would be a better change. Plus I brought this up before but no one seemed interested in changing it.

Changing both sounds good too. And I posted this at the request of Dream, I personally agree with it being changed but thats not for me to decide lol

**Comment by Prometheus0000** [comment]
Both is good too. It's probably easier to asm than actual code changes too.

**Comment by Ethryan** [comment]
Don’t we just have to add a lang file to the resources folder to change the ic 2 name?

No need for asm methinks

**Comment by Ethryan** [comment]
[Link](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/tree/master/resources), you create a folder here with a lang folder and the edited .lang file inside, that loads the new text over the .jar added lang file, works with textures too.

**Comment by bartimaeusnek** [comment]
This is just not justified nor nessecary, since "rape seed" is a proper name for it. Hard no from me, for legacy sake.

**Comment by leagris** [comment]
> This is just not justified nor nessecary, since "rape seed" is a proper name for it. Hard no from me, for legacy sake.

Maybe just write it as one word `Rapeseed` as in the [Wikipedia article](https://en.wikipedia.org/wiki/Rapeseed) because two words probably sound too much like a seed of sexual assault.

**Comment by jackowski626** [comment]
I agree 100% with Léa. Don't strip "le funny" from the pack please

**Comment by dimondmine2** [comment]
If changing "rape seed" to "rapeseed" fails to solve the reference to sexual assault, or what Jack refers to as the "le funny" aspect of it, then changing the name to "rapeseed" is a half measure that addresses the problem without fixing it.

**Comment by Dream-Master** [comment]
ok so we let it like it is to be "le funny"? It was a low priority issue anyways.

**Comment by KiloJoel** [comment]
> 
> 
> If changing "rape seed" to "rapeseed" fails to solve the reference to sexual assault, or what Jack refers to as the "le funny" aspect of it, then changing the name to "rapeseed" is a half measure that addresses the problem without fixing it.

Rapeseed is a thing, so that makes sense. Rape seed is not a thing, so the association is made with the literal meaning of the words

**Comment by basdxz** [comment]
The big funny, just make it drag the player in to if they step on it. Kinda like the crop++ fish plant screams at you when you step on it

**Comment by Prometheus0000** [comment]
Closing since it's apparently impossible to do without breaking things or excessive changes.

**Comment by benjamin-kirkbride** [comment]
Could we at least get the tooltip changed? And the questbook references? Saying "it's the name of a plant, we aren't going to rename a plant in the name of PoLiTiCaL wOkEnEsS", but then turning around and making a bunch of innuendos is pretty disingenuous.

**Comment by MrWisski** [comment]
> This is just not justified nor nessecary, since "rape seed" is a proper name for it. Hard no from me, for legacy sake.

Rapeseed IS the proper name for it, and disapproving of violent sexual assault (and having empathy for another human being) is not, and has never been "PoLiTiCaL wOkEnEsS" - IT IS THE BASIS OF HUMAN SOCIETY.  Just say "We can't change it cause IC2 codebase is a bloody nightmare, End of story."
