### ISSUE TITLE
Conservation of mass in chemical reactions

### ISSUE THREAD

**Issue by Ydrec** [GTNewHorizons/GT-New-Horizons-Modpack#7403]
#### Which modpack version are you using?
2100
#
#### If in multiplayer; On which server does this happen? 
Any
#
#### What did you try to do, and what did you expect to happen?
So most of decomposition reactions in gtnh try to abide to rough mass conservation where each dust is decomposed into its chemical parts each being only a 1/nth of starting mass, like for example decomposition of Sodium hydroxide NaOH
![изображение](https://user-images.githubusercontent.com/53411693/106206334-ecde1000-61d0-11eb-966a-64493cf59022.png)

#
#### What happened instead? (Attach screenshots if needed)
But almost none of chemical reactor composition recipes abide by this, this makes no sense and kill any and all catalysis reaction chains where catalysis shouldn't be used up. 
For example a few
Sodium Na into Sodium hydroxide NaOH, based on NaOH< Sodium is only 1/3 of the mass of Hydroxide, and as such 1 Na should be able to create 3NaOH dusts, from 3000L of water, with byproduct of 1000L hydrogen, making it an actual catalysis reaction of getting hydrogen from water.
![изображение](https://user-images.githubusercontent.com/53411693/106208498-8b1fa500-61d4-11eb-91c1-ec13c67397a5.png)
Hydrogen sulfide uses 1 sodium and 2 hydrogen buckets only giving 1 cell
![изображение](https://user-images.githubusercontent.com/53411693/106209313-d9817380-61d5-11eb-8ca0-937a9503342e.png)
Ammonia NH3 uses 1N and 3H cells but only produces 1Cell
![изображение](https://user-images.githubusercontent.com/53411693/106209607-5f9dba00-61d6-11eb-8e84-552c9d4f51fc.png)

Most noticeably is ofc chlorine in titanium processing, but its understandable as dissipation in oven and balance as titanium is major progression step.

#
#### What do you suggest instead/what changes do you propose?
This basically turns any fun of chemistry into just more ore processing cause everything just lost into void. This may be addressed as "losses" due to imperfect machines etc, but no, not with losses like 66% of actual starting product. And this can not be negated in more advanced machines as same recipes are reused in chem reactor multi and still same void losses. To drastically improve chemistry in pack as well as lower the amount of constant ore processing this needs refactoring to reaction to either have no mass loss or addition of percentage output to negate such massive losses over nothing while keeping to machines imperfections.

**Comment by Dream-Master** [comment]
Guess we need to rewrite the whole backward recipes in GT code.
