### ISSUE TITLE
Molten Potassium Disulfate cell name is broken

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#7404]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What did you try to do, and what did you expect to happen?
I filled an empty cell with Molten Potassium Disulfate from a drum, expected to get a cell named Molten Potassium Disulfate

#
#### What happened instead? (Attach screenshots if needed)
![javaw_nAnyVxuz0Y](https://user-images.githubusercontent.com/17811922/106257224-8848a280-621c-11eb-8c06-183619e31c93.png)

#

**Comment by bartimaeusnek** [comment]
Known for a rather long time, im not quite sure whats causing this, and since its only visual, its low prio to me.

**Comment by Prometheus0000** [comment]
Duplicate of  #5393, #6386

**Comment by GeicowithaBango** [comment]
if this issue gets reported so frequently, i would say this shouldnt be low-prio, now should it?

**Comment by mitchej123** [comment]
> if this issue gets reported so frequently, i would say this shouldnt be low-prio, now should it?
> best regards

Feel free to submit a fix to this volunteer effort

**Comment by Sphyix** [comment]
@GeicowithaBango ppl like me report it cause I clearly don't know how to use the search function, it is still just a visual issue

**Comment by GeicowithaBango** [comment]
i think theres a misunderstanding happening here. All my effort aims to present BW in its glorious light it deserves.
And having a minor bug like this damaging the outer facade of BW is in my opinion troublesome -think about marketing a product idk.


anyways:


> > if this issue gets reported so frequently, i would say this shouldnt be low-prio, now should it?
> > best regards
> 
> Feel free to submit a fix to this volunteer effort

how about you think about a diffrent way to express yourself. the shit-show at bears Discord was embarrassing

**Comment by mitchej123** [comment]
> how about you think about a diffrent way to express yourself. the shit-show at bears Discord was embarrassing

Please follow your own advice.

**Comment by Prometheus0000** [comment]
Bart clearly thinks it's low priority, and no one else cares that much about it, so I don't know what you expect here? More people helping out means things get done faster, or at all even.

Also, it's low priority because it doesn't actually affect anything. People just automate the platline (it was used in that, right?) anyway, so there's little opportunity to be bothered by it

**Comment by GeicowithaBango** [comment]
> Bart clearly thinks it's low priority, and no one else cares that much about it, so I don't know what you expect here? More people helping out means things get done faster, or at all even.
> 
> Also, it's low priority because it doesn't actually affect anything. People just automate the platline (it was used in that, right?) anyway, so there's little opportunity to be bothered by it


good to know, so the low prio description seems right
