### ISSUE TITLE
Twilight Forest: Crash upon generating stuff

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#7407]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Private one.
#

Just found that my server had been crashed.
CrashRep: https://pastebin.com/cpTt9h5a

**Comment by Dream-Master** [comment]
@jss2a98aj any idea on this bug/crash?

**Comment by jss2a98aj** [comment]
I don't know why that happened. It might be a multi-threading issue.

**Comment by TimeConqueror** [comment]
Seems like the issue is with the whole Twilight generation, got one more crash, which is not the same:
https://pastebin.com/P8GsX4XQ

**Comment by KaneHart** [comment]
Sadly getting too and happen like not even 10min into generating a new world there. I want to pregen it but this is going to be painful. No way to ignore it I guess and skip it?

https://gist.github.com/KaneHart/656d520521506d941b68c7e92e086356

What you think @jss2a98aj Not sure if you are tinkering with TF anymore.
