### ISSUE TITLE
Tier 2 rocket recipe

### ISSUE THREAD

**Issue by OriginalBacer** [GTNewHorizons/GT-New-Horizons-Modpack#7408]
#### Which modpack version are you using?
2.1.0.0
#### If in multiplayer; On which server does this happen? 
Privat server / singl too
#### What did you try to do, and what did you expect to happen?
Craft tier 2 rocket
#### What happened instead? (Attach screenshots if needed)
Tier 2 rocket recipe incorrect. Using one tier 1 booster instead two.
![unknown (1)](https://user-images.githubusercontent.com/2857859/106316022-c5408380-6274-11eb-8664-f48cacd4b57b.png)
![unknown (2)](https://user-images.githubusercontent.com/2857859/106316030-c70a4700-6274-11eb-8fe0-78d9f123c114.png)
![unknown (3)](https://user-images.githubusercontent.com/2857859/106316033-c8d40a80-6274-11eb-8fb3-c66d211f9627.png)
#### What do you suggest instead/what changes do you propose?
Change recipe

**Comment by boubou19** [comment]
duplicated of #7196, which is fixed in dev
