### ISSUE TITLE
client-server eat animation desync

### ISSUE THREAD

**Issue by NoX-programer** [GTNewHorizons/GT-New-Horizons-Modpack#7410]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
private
#
#### What did you try to do, and what did you expect to happen?
Player eats the cheese (Pam's HarvestCraft) when hungry, expecting refill hunger and change cheese status "not yet eaten" -> "eaten: assisted..."
#
#### What happened instead? (Attach screenshots if needed)
Status of cheese isn't changed ("not yet eaten") and after some time hunger level resets to amount before cheese eat, also cheese_item gets back in slot (after slot click/update)
#
#### What do you suggest instead/what changes do you propose?
Looks like HarvestCraft bug, introduced only with it's update to version 1.0.2-GTNH (before there was no problems with cheese). I suggest to roll back invalid changes in Pam's Harvestcraft to fix this :bug:

**Comment by Dream-Master** [comment]
@Mitchj123 @leagris any idea ?

**Comment by TimeConqueror** [comment]
Temporary solution: eat it using lunch box

**Comment by NoX-programer** [comment]
Re-checked: actually, the cheese is normally consuming, restoring hunger and changes status to "eaten: ..." **if** you holding mouse button longer; i.e. client too early thinks that cheese is consumed / or server is too late. **So we have client-server eat animation desync.** When I have complete understanding of the bug, it's not big problem any more (for me). Let issue hang open until some skilled desync-exterminator finally come.

**Comment by NoX-programer** [comment]
That's problem lives long, I see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/475
So if this issue is a dupe than maybe close this?
