### ISSUE TITLE
[Twilight Forest] Dark Forest Dungeon Generation Bug

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7411]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
kill boss in Dark Forest Dungeon
#
#### What happened instead? (Attach screenshots if needed)
Part of the dungeon is under the Ur-Ghast tower make player unable to attack the mobs in the dungeon resulting death
After the player died cannot break the grave to get the item back
#
#### What do you suggest instead/what changes do you propose?
don't know just report it
maybe disable the region protection in twilight forest?

**Comment by Dream-Master** [comment]
they acidently generated together like this I  guess. But so far ik there are more than one urgast tower so look for another
