### ISSUE TITLE
Centrifuging glowstone inneficient recipe

### ISSUE THREAD

**Issue by dimondmine2** [GTNewHorizons/GT-New-Horizons-Modpack#7413]
#### Which modpack version are you using?
2.1.0.3
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
![image](https://user-images.githubusercontent.com/75643342/106369185-33d91c00-631d-11eb-8548-e1b9b5714427.png)

#### What do you suggest instead/what changes do you propose?
Recipe should require 2 glowstone and export 2 full dusts. No need for the recipe to inconvenience the player by forcing them to manually put the dusts together.

**Comment by Nicouuuuu** [comment]
This is the same for the recipe of magnesium chloride imo : 
![image](https://user-images.githubusercontent.com/62377720/106827280-d92b2180-6688-11eb-930d-30a83dd0dbf0.png)
It should be outputing 2 whole dusts

**Comment by KiloJoel** [comment]
> 
> 
> This is the same for the recipe of magnesium chloride imo :
> ![image](https://user-images.githubusercontent.com/62377720/106827280-d92b2180-6688-11eb-930d-30a83dd0dbf0.png)
> It should be outputing 2 whole dusts

Already done: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7303

**Comment by Nicouuuuu** [comment]
Just saw that yeah so I deleted my comment
