### ISSUE TITLE
Worktable doesn't craft items

### ISSUE THREAD

**Issue by Nuroyun** [GTNewHorizons/GT-New-Horizons-Modpack#7414]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
ETA official server
#
#### What did you try to do, and what did you expect to happen?
I tried to craft something on a forestry wortktable expected to actually get the item
#
#### What happened instead? (Attach screenshots if needed)
Game crashed, crashlog and logs below
[crash-2021-01-31_01.25.46-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5898944/crash-2021-01-31_01.25.46-client.txt)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5898945/latest.log)
#

**Comment by Glease** [comment]
Wait this isn't me. My changes wasn't even in 2.1.0.0 yet. No idea why would it crash.

**Comment by Waraslt** [comment]
I have got exactly same error, I tried to craft crafting table in a worktable and got client crash, twice, probably will not try again unless fixed
[crash-2021-03-18_21.13.20-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6166817/crash-2021-03-18_21.13.20-client.txt)

**Comment by Nuroyun** [comment]
> I have got exactly same error, I tried to craft crafting table in a worktable and got client crash, twice, probably will not try again unless fixed
> [crash-2021-03-18_21.13.20-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6166817/crash-2021-03-18_21.13.20-client.txt)
> 
> EDIT: ok did some digging in the crash reports, figured theres a side mod that is causing crashes, mine is optifine(specifically items NEEDS to be animated), Noroyun's is unknown ae2 api installed.

i cant say anything about an unknown mod i am playing without changes

**Comment by Waraslt** [comment]
[crash-2021-03-25_20.21.17-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6207259/crash-2021-03-25_20.21.17-client.txt)
ok this time it was a random crash for no reason, I tried to craft LV machine casing, next time I loaded it crafted it.
this is definitely a real issue.

**Comment by Prometheus0000** [comment]
This is about the forestry worktable, not the TC one, right?

**Comment by Nuroyun** [comment]
> This is about the forestry worktable, not the TC one, right?

yep
