### ISSUE TITLE
Aluminum gravel cant be pulverized

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7415]
#### Which modpack version are you using?
2.1.0.3a
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Pulverize aluminum gravel for double output
#
#### What happened instead? (Attach screenshots if needed)
Aluminum gravel ore unlike other gravel ores cant pulverized in GT macerator
![image](https://user-images.githubusercontent.com/29033773/106378016-38034900-63b2-11eb-808d-cb3c98cf7b09.png)
#
#### What do you suggest instead/what changes do you propose?
Return aluminum doubling for gravel

**Comment by Florexiz** [comment]
Right now only option to get alumium from gravel :
1. Smelt gravel in smeltery
2. Cast it in raw aluminum
3. Macerate
Also SAG mill recipe still present unlike gt one

**Comment by repo-alt** [comment]
wow, if that is so, then no rocket run is broken

**Comment by Dream-Master** [comment]
Ok it was the same with cobalt. Will add the recipes in code.
