### ISSUE TITLE
Ruthenium recipes

### ISSUE THREAD

**Issue by Oueio** [GTNewHorizons/GT-New-Horizons-Modpack#7419]
#### Which modpack version are you using?
2.1.0.3a
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/75951914/106396179-62d3b880-6417-11eb-8145-22f080f1d88a.png)
![image](https://user-images.githubusercontent.com/75951914/106396191-6f581100-6417-11eb-82d8-de949979d851.png)
![image](https://user-images.githubusercontent.com/75951914/106396205-8434a480-6417-11eb-9502-1816407cb33e.png)
With recipe 2 ruthenium ingots for 1 ruthenium gear
And recipe 1 ruthenium gear for 4 dust in pulverizer it's dupe of ruthenium
![image](https://user-images.githubusercontent.com/75951914/106396223-adedcb80-6417-11eb-8b69-429c3e4b6468.png)

**Comment by Oueio** [comment]
Also compressor recipe - 2 ruthenium ingots equal 1 block (In NEI)
Extruder - Gear, block, plates recipes

**Comment by miozune** [comment]
I think we can close this
