### ISSUE TITLE
Hazmat tooltip not showing on server

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7420]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Locally hosted server and Eta
#
#### What happened instead? (Attach screenshots if needed)
The hazmat tooltip doesn't load until you have logged into a singleplayer world. After logging into a singleplayer world it will then also show while on a server in the same game session.

On singleplayer
![image](https://user-images.githubusercontent.com/17787093/106398309-06b66780-640a-11eb-91a6-a014bfb4bb75.png)

On locally hosted server without logging into singleplayer first
![image](https://user-images.githubusercontent.com/17787093/106398969-e5f01100-640d-11eb-8464-72c50aab8521.png)

This is the same for all items that provide hazmat.
I have asked others on Eta and they also can't see the tooltip.

**Comment by boubou19** [comment]
looks like a minetweaker script mismatch.

**Comment by Dream-Master** [comment]
minetweaker ? this is gt++ stuff

**Comment by boubou19** [comment]
i thought it was another tooltip added by a script, my bad. Could have explained why if the officials had slightly different minetweaker scripts.

**Comment by Dream-Master** [comment]
idk but the ic2 script not match. Maybe I add changes so close on the update that I forgot to push.

**Comment by Eason134HK** [comment]
Nano suit actually don't provides full hazmat protection

**Comment by KiloJoel** [comment]
> 
> 
> Nano suit actually don't provides full hazmat protection
> #7004
> #7048

Ok but that's not relevant here
