### ISSUE TITLE
Removal of Warded Glass placed by Unbreakable Wand

### ISSUE THREAD

**Issue by Tatarigami** [GTNewHorizons/GT-New-Horizons-Modpack#7422]
#### Which modpack version are you using?
2.0.9.0

#### If in multiplayer; On which server does this happen? 
Private Server

#### What did you try to do, and what did you expect to happen?
Placing Warded Glass with Unbreakable Wand

#### What happened instead? (Attach screenshots if needed)
Can't remove Warded Glass with any Wand

#### What do you suggest instead/what changes do you propose?
I suppose placing with Unbreakable Wand somehow miss "placed by" flag and we just need to channel this flag through Unbreakable Wand to Warded Glass

**Comment by Prometheus0000** [comment]
Duplicate of #2416
