### ISSUE TITLE
Red alloy wire can't connect to dense redcrystal

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7423]
#### Which modpack version are you using?
GTNH 2.1.0.0
#

When the dense redcrystal is placed on a wall, the red alloy wire can't connect to the top or bottom.

![image](https://user-images.githubusercontent.com/57050655/106433658-cb9b4f00-6470-11eb-83b1-f052e39c7c52.png)

**Comment by Leerdix** [comment]
This also happens to every redcrysal, not just the dense one
