### ISSUE TITLE
AE2 Energy Accepter behavior is different between 2.0.7.5 and 2.1.0.0

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7424]
#### Which modpack version are you using?
2.1.0.0 and 2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Single and multi
#
#### What happened instead? (Attach screenshots if needed)
This network is not online in 2.1.0.0. but It was online in 2.0.7.5.
![2021-02-01_03 24 32](https://user-images.githubusercontent.com/40425798/106436261-3a9b9680-64b7-11eb-9a6a-068cd9eabcaf.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it?

**Comment by repo-alt** [comment]
What is that blue box? Doesn't it point up?

**Comment by Alexdoru** [comment]
> What is that blue box? Doesn't it point up?
> (It is a bit hard to believe that all energy acceptors suddenly stopped accepting energy in 2.1.0.0 and I learn about it only now)

Blue box is a debug power generator, it outputs power to all sides

**Comment by yukieiji** [comment]
> What is that blue box? Doesn't it point up?
(It is a bit hard to believe that all energy acceptors suddenly stopped accepting energy in 2.1.0.0 and I learn about it only now)

It's a debug power generator that outputs EU over UV.
If you have additional energy cells or other storage devices, you can get it working.
![2021-02-01_19 00 04](https://user-images.githubusercontent.com/40425798/106443417-cca79d00-64bf-11eb-95f8-fc8166e6289a.png)

**Comment by repo-alt** [comment]
I think it does not have enough buffer to accept one ampere/packet in this case

**Comment by yukieiji** [comment]
This is shedding a huge EU as a typical example, but  it isn't online even if low EU.

**Comment by yukieiji** [comment]
In fact, the ad-hoc network that was online in 2.0.7.5 couldn't be online after updated 2.1.0.0...

**Comment by repo-alt** [comment]
Ok, this is not intended. Previously acceptor handled GT cable as an IC2 source that could provide partial ampere. Now it has real GT power interface, and GT works only with full packets. Almost no AE entities have an internal energy buffer, so adhoc networks w/o energy cells cannot be directly powered by GT cables. I'll add energy acceptor internal buffer.
