### ISSUE TITLE
Arthana duplication bug

### ISSUE THREAD

**Issue by DocWhoSonicDrive** [GTNewHorizons/GT-New-Horizons-Modpack#7429]
The modpack version is 2.0.9.0
I am playing on multiplayer, on the prospercraft server. The issue is the same as the one in [https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/1458](this) one, and I was told to make a new report. So basically, I placed an arthana from witchery on the altar with Shift+RC, like normally, but it causes an duplicate to form in my inventory that is invisible. When interacting with the object, it appears and I can place it like normal. I relog and find that it's not just a ghost item, but a true duplicate. I can break the arthana on the table to get a second one, and I find that this is repeatable. I don't know how this would be fixed, but I see that I should bring this to attention, as the previous report is 4 years old.

**Comment by combusterf** [comment]
I accidentally ran into this and can confirm it still exist, though I did not manage to dupe any other items with this procedure. Since there's no recipe involving the arthana you can only really get free durability with this.
