### ISSUE TITLE
Game crash when looking nei recipe of chem plant

### ISSUE THREAD

**Issue by lkj0604** [GTNewHorizons/GT-New-Horizons-Modpack#7432]
#### Which modpack version are you using?

#2.1.0.3a
#### If in multiplayer; On which server does this happen? 

#sp
#### What did you try to do, and what did you expect to happen?

#
[crash-2021-02-04_17.57.43-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5924968/crash-2021-02-04_17.57.43-client.txt)

**Comment by mitchej123** [comment]
Please update to NEI 2.0.9 and report back if it's still an issue.

**Comment by Dream-Master** [comment]
@lkj0604

**Comment by lkj0604** [comment]
update to NEI 2.0.9 but still crash 


[crash-2021-02-05_11.24.42-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5929883/crash-2021-02-05_11.24.42-client.txt)

**Comment by lkj0604** [comment]
https://user-images.githubusercontent.com/53849240/107107683-abeb9880-686d-11eb-8794-0a517e088e2a.mp4

This is how the game crashes

**Comment by mitchej123** [comment]
@lkj0604 Please update your witchery extras.  Did you grab that version from the version I posted on discord, or from a dev download?   I've attached a version that should work (Rename zip --> jar)

[WitcheryExtras-1.1.0.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5937384/WitcheryExtras-1.1.0.zip)

**Comment by mitchej123** [comment]
Thanks for the video, I was able to reproduce it that way.  I'll identify and push a fix.

**Comment by mitchej123** [comment]
It was a bug with incompatible NEI versions when compiling WitcheryExtras.  Swap this version (rename zip -> jar)
[WitcheryExtras-1.1.1.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5937417/WitcheryExtras-1.1.1.zip)

**Comment by Dream-Master** [comment]
or use this instead :P http://jenkins.usrv.eu:8080/job/Witchery-Extras/24/

**Comment by lkj0604** [comment]
Perfectly solved this problem, thanks

**Comment by mitchej123** [comment]
Will close when released
