### ISSUE TITLE
Heart Canisters destroyed

### ISSUE THREAD

**Issue by tuckermand** [GTNewHorizons/GT-New-Horizons-Modpack#7433]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
I tried to go AFK for a couple hours without dying. I suspect I starved to death due to warp. Before I returned to keyboard and respawned, the server restarted.
#
#### What happened instead? (Attach screenshots if needed)
 I respawned without any heart canisters and there were none in the grave.
#
#### What do you suggest instead/what changes do you propose?
My suspicion is a server restart while you're dead prevents heart canisters from being soulbound properly, but I have little information to work with here. Naturally, it would be better if this effect did not occur.

**Comment by NoX-programer** [comment]
Workaround (not solution!): AFK only with Healing Axe in hands

**Comment by tuckermand** [comment]
I typically do, but sometimes forget D:

**Comment by boubou19** [comment]
can you try reproducing it on 2.1.0.0?
