### ISSUE TITLE
Crash from wand focus: illumination orbs

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7434]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Eta->singleplayer
#
#### What did you try to do, and what did you expect to happen?
Switched world from server to singleplayer while in range of orbs placed using wand focus: illumination (Thaumic Horizons)
#
#### What happened instead? (Attach screenshots if needed)
The game crashed: [crash-2021-02-04_22.47.11-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5929074/crash-2021-02-04_22.47.11-client.txt)

The crash happens every time with these conditions, with the same error message

**Comment by Prometheus0000** [comment]
Could you list what mod it is too?

**Comment by Prometheus0000** [comment]
NVM, the crashlog does it

**Comment by KiloJoel** [comment]
Maybe also worth noting that I don't have anything from remoteIO in singleplayer, I tried it with a freshly generated superflat world and it still crashed with the same thing.

**Comment by Prometheus0000** [comment]
Sounds like RIO is upset it can't understand the TE, even though you don't have any RIO items?
