### ISSUE TITLE
Welcome to the Church of Benzene quest description is wrong

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7435]
#### Which modpack version are you using?
2.10.0
#
#### What did you try to do, and what did you expect to happen?
Read the Benzene quest to see how I can make it.
#
#### What happened instead? (Attach screenshots if needed)
It says Coke Ovens and Advanced Coke Ovens do not pollute, but they do.
#
#### What do you suggest instead/what changes do you propose?
Update the quest text to say that coke ovens make pollution now.  Benzene cannot be produced without pollution.

**Comment by Prometheus0000** [comment]
If the pollution discussion ever goes anywhere, it might be removed again though.

**Comment by Dream-Master** [comment]
not removed reworked!
