### ISSUE TITLE
Peat Fired Engine quest does not complete

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7436]
#### Which modpack version are you using?
2.10.0
#
#### What did you try to do, and what did you expect to happen?
I tried to do the peat fired engine quest.
#
#### What happened instead? (Attach screenshots if needed)
It doesn't complete.  I tried in both a crafting station and a vanilla crafting table.
#
#### What do you suggest instead/what changes do you propose?
Just change it to a detection task IMO.  The last attempted fix didn't work anyway.

**Comment by Prometheus0000** [comment]
Duplicate of #6738. In the case of an old issue coming back, you comment on the old issue and we re-open it. Don't make a new one, or the info is all over the place and it makes it harder to solve.
