### ISSUE TITLE
Useless air-to-air electrolyzer recipe

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7437]
#### Which modpack version are you using?
2.10.0
#
#### What did you try to do, and what did you expect to happen?
I was looking up stuff in NEI and wanted to see how to make Air gas, and noticed the electrolyzer recipe for it.
#
#### What happened instead? (Attach screenshots if needed)
It's pointless.  It takes air as an input (as pure gas in the multiblock recipe, or as compressed air in the single block recipe) and outputs the same amount of air, doing nothing but waste energy.
#
#### What do you suggest instead/what changes do you propose?
Remove it.

**Comment by Glease** [comment]
The recipe in question is a recipe for GT++ multiblock electrolyzer, which is copied from singleblock electrolyzer. The singleblock version of recipe takes one compressed air cell and output 2000L air. It's kindof pointless as it's more of a fluid canner recipe than electrolyzer.
