### ISSUE TITLE
Old IC2 Recipes for uranium fuel rod combination re-enabled

### ISSUE THREAD

**Issue by Mrminesheeps** [GTNewHorizons/GT-New-Horizons-Modpack#7439]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
In multiplayer, but it's not a server-added recipe. (Unofficial GT server)
#
#### What did you try to do, and what did you expect to happen?
Nothing special, just checked NEI uses for single uranium fuel rods (Was checking what circuit was added to the recipe)
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/15947037/107092374-543f2580-67b8-11eb-9a00-c37756190e05.png)
(That should be a raw screenshot of my game showing the recipes)
#
#### What do you suggest instead/what changes do you propose?
Removing the recipes as I suppose they're not intended.

**Comment by Prometheus0000** [comment]
Already fixed in #7167
