### ISSUE TITLE
Trash can from extra utils stops working

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7440]
#### Which modpack version are you using?
GTNH 2.1.0.0
#

I have 10 void miners III running and I put in the trash can around half of the ores, on server restart sometimes the trash can gets stuck with a stack of ores in its inventory and doesn't destroy it thus blocking my whole system.

**Comment by Alexdoru** [comment]
Here a pic showing the trash can with a stack of ore that is blocked in the trash can and that won't get void, I have to break and replace the trash can


![2021-02-08_17 32 32](https://user-images.githubusercontent.com/57050655/107250072-15b59f00-6a34-11eb-9073-11cf341ca665.png)

**Comment by NoX-programer** [comment]
We need Extra Utilities source to fix this. I don't see any available. [That one](https://github.com/sameer/ExtraUtilities) looks like we can use, but the final decision will be announced @Dream-Master.

**Comment by mitchej123** [comment]
> We need Extra Utilities source to fix this. I don't see any available. [That one](https://github.com/sameer/ExtraUtilities) looks like we can use, but the final decision will announce @Dream-Master.

I don't see anything on the repo you linked that gives any indication rwtema gave permission to distribute it.  We'd need to get official permission from them, or use ASM/Mixins to patch the bug

**Comment by Dream-Master** [comment]
I ask him twice but never get an answer back. I can try it again.

**Comment by NoX-programer** [comment]
@Alexdoru thank you for report, some day it may be solved, but for now I have a workaround: to unstuck the trash you may to try place, for example, any recycler with importing conveyor-cover closely to the trash.
