### ISSUE TITLE
Steam Grinder multiblock crafting inconsistency

### ISSUE THREAD

**Issue by Rubix2048** [GTNewHorizons/GT-New-Horizons-Modpack#7441]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Official Eta
#
#### What did you try to do, and what did you expect to happen?
Craft a Tumbaga Rod with a file and tumbaga ingot
#
#### What happened instead? (Attach screenshots if needed)
No such recipe (need an LV lathe)
#
#### What do you suggest instead/what changes do you propose?
If the Steam Grinder is supposed to be steam tier, as suggested by the 2.1.0.0 changelog about how there's a recipe for it pre-LV Assembler, add a recipe for Tumbaga Rod with a file in a workbench, and change the quest-lock on the quest for the Steam Grinder to be in the Steam age. Alternately, change the quest-lock to require the LV lathe. Else, remove the hand-crafting recipe for Tumbaga Frame and leave the quests as they are.

**Comment by Prometheus0000** [comment]
It's a GT++ MB, and I had to add the recipe for tumbaga frames manually, otherwise it requires the LV assembler, by which time it's probably useless, but I guess I missed the rod.

**Comment by Rubix2048** [comment]
I haven't used it, but I have heard it is a good solution all the way up to HV, so obsolescence is probably not an issue (specifically, "better than an MV macerator"--i suppose it is much bigger though), but my only complaint is the inconsistent "can you craft it and when" thing :)

**Comment by Impos913** [comment]
Also steam grinder quest is still gated behind lv assembler quest. In 2.1.0.3a

**Comment by septemberWaves** [comment]
The tumbaga gears are also impossible to craft in the steam age, for similar reasons. They are machine craftable only.

**Comment by Prometheus0000** [comment]
Christ, it's one thing after another with this.
