### ISSUE TITLE
[Galacticraft] Unable to auto-craft frequency module / arc lamp

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#7442]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Tried to autocraft the frequency module via AE autocrafting, set up a pattern incl. `allow substitutions = yes`
#
#### What happened instead? (Attach screenshots if needed)
Craft does not complete, Crafting terminal shows the frequency module as scheduled, but nothing happens
#
#### What do you suggest instead/what changes do you propose?
In the Galacticraft.zs script file, there is a duplicate entry for the frequency module:

```
// --- Frequencey Module
recipes.addShaped(<GalacticraftCore:item.basicItem:19>, [
[CompressedAl, <gregtech:gt.metaitem.01:32692>, CompressedAl],
[BWafer, <gregtech:gt.metaitem.01:32740>, BWafer],
[CompressedTin, <GalacticraftCore:item.battery>, CompressedTin]]);
// -
recipes.addShaped(<GalacticraftCore:item.basicItem:19>, [
[CompressedAl, <gregtech:gt.metaitem.01:32692>, CompressedAl],
[BWafer, <gregtech:gt.metaitem.01:32740>, BWafer],
[CompressedTin, <GalacticraftCore:item.battery:*>, CompressedTin]]);
```
I'll try a change in the script file and report back.

**Comment by GTNH-Afx237v7** [comment]
So I deleted the lower entry and changed `GalacticraftCore:item.battery` with `GalacticraftCore:item.battery:32767` but it still doesn't work...
Will test more tomorrow.

**Comment by Skiftcha** [comment]
maybe just replace GC battery with small battery hull in recipe?
this step looks strange and useless
![image](https://user-images.githubusercontent.com/2212585/107214844-91572200-6a1b-11eb-95b2-6ec1f64ccef5.png)

**Comment by GTNH-Afx237v7** [comment]
It is most likely the culprit. Replacing the `*` in the script file with `32767` for both the battery recipe and the frequency module recipe doesn’t work...

**Comment by GTNH-Afx237v7** [comment]
I have not been able to solve this, also it is not possible to auto-craft the Arc lamps via AE autocrafting. They show the same behaviour, despite all items being available the craft remains as "scheduled" indefinitely.

Before I make a PR I'd like to seek further input on this. If anyone knows what to try I am open for suggestions.

The Galacticraft battery is used in the following recipes:

Galacticraft:
Frequency module
Arc Lamp

Galaxy Space:
Plasma Tools

It is also required in quest #1464 "Arc Lamps"

**Comment by GTNH-Afx237v7** [comment]
See PR here:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7461
