### ISSUE TITLE
[suggestion] make the EIO item filters and fluid filters possible to configure with NEI Ghost Items

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7443]
#### Which modpack version are you using?
2.1.0.0
#

Could it be possible to configure EIO item and fluid filters with ghost items from NEI? AE allows it for pattern encoding, so it could be a QoL change to be able to drop fluid cells from NEI instead of filling actual cells with the fluid you want to filter, or go pick the item in your storage because you forgot to take it.

**Comment by Glease** [comment]
It'd take some effort, but it's a worthwhile feature.

**Comment by boubou19** [comment]
For reference: here is how it's done for AE: https://github.com/GTNewHorizons/neiaddons/blob/mc1710/src/net/bdew/neiaddons/appeng/AppEngGuiHandler.java

**Comment by repo-alt** [comment]
Well, since I just added such a handler to AE terminal search string, perhaps I'll take a look at EIO filters

**Comment by repo-alt** [comment]
Looks like that is a conscious decision made in EnderCore, they actually handle drag and drop there and do nothing.
It's not like we can't change that anyway.

**Comment by Glease** [comment]
Seems implemented by https://github.com/GTNewHorizons/EnderCore/pull/2 now.
