### ISSUE TITLE
cutting factory 

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7444]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
build cutting factory  
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/107155758-283cc380-69b5-11eb-8b73-4fbe99928eee.png)
incomplete structure
#
#### What do you suggest instead/what changes do you propose?
![image](https://user-images.githubusercontent.com/59776356/107155765-32f75880-69b5-11eb-8906-cfca48e50eec.png)
Description say requires 26 casings But it actually requires 28 to function normally

**Comment by GTNH-Afx237v7** [comment]
Cutting factory is GT++. Best to report it at https://github.com/alkcorp/GTplusplus/issues
