### ISSUE TITLE
Add "Quantum/Super Controller" block [Feature Request]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7445]
It would be nice if there was an equivalent to drawer controllers for super tanks and chests. I would suggest it be gated behind LuV/ZPM for the sake of balance. Storage drawers hold at most about 700K items and I can see many instances where larger storage options would be useful, and minimizing AE2 channels is always a plus.

**Comment by repo-alt** [comment]
I don't see how it may be done server friendly. For items just use storage cells, they are efficient and there are big ones available. For fluids just use quantum tanks and p2p, what's the point in controller. Storing stuff in chests is _bad_, and becomes worse with bigger chests.

**Comment by GTNH-Colen** [comment]
> I don't see how it may be done server friendly. For items just use storage cells, they are efficient and there are big ones available. For fluids just use quantum tanks and p2p, what's the point in controller. Storing stuff in chests is _bad_, and becomes worse with bigger chests.

Could perhaps a limited setup be alright? I appreciate we don't want to encourage massive cubes of super chests but say if a controller had a limit of 8 superchests per that would that still be laggy? 8 AE storage buses would be doing the same checks anyways right?

**Comment by repo-alt** [comment]
> 8 AE storage buses would be doing the same checks anyways right?
right, so, what's the point?

**Comment by repo-alt** [comment]
Just to be clear: storage buses on super chests is a bad, not server friendly solution.

**Comment by GTNH-Afx237v7** [comment]
Storage cells are just somewhat expensive compared to drawers/super chests.
A 256K storage will hold 2 Million items and is ~ 1,300 Gold, 2,000 Redstone,  120 Diamonds, 550 Copper. A super chest 1 is 5 LV circuits, a bit of iron and rubber and holds 4 Million items. 
I am not saying GTNH is too hard. However I would understand if someone were to prefer storage buffers/chests over storage disks.

**Comment by Prometheus0000** [comment]
Is the only non-bad storage solution ae cells then? Maybe you could add an option to auto-void when full if that's the only thing we should be using?

**Comment by johnch18** [comment]
Even an option limited to say 8 tanks/chests would be appreciable.

**Comment by GTNH-Colen** [comment]
> Just to be clear: storage buses on super chests is a bad, not server friendly solution.

I'm not sure on the feasibility of such an idea but couldn't we have special AE cells that uses say a 64m super chest in the recipe and creates a cell that holds up to 64m of 1 item? In addition a special drive housing that only accepts these cells could be created that holds say 50 cells instead. NBT overflow shouldn't be an issue given how much data regular drive housings already hold, all seems like an extension of what already exists in AE but I appreciate it'd be a fair bit of work.

**Comment by repo-alt** [comment]
Tbh I would have preferred to make storage cells way cheaper. But it is not impossible to make integration for quantum chests to work with AE more closely, and require less grid updates.

**Comment by GTNH-Colen** [comment]
> Tbh I would have preferred to make storage cells way cheaper. But it is not impossible to make integration for quantum chests to work with AE more closely, and require less grid updates.

There were proposed recipes to do exactly this a while ago using high tier fluids like molten europium to significantly reduce the cost. Currently the top tier extra cells stuff is prohibitively expensive for regular use, even in endgame. I think the best cell takes something like 64k ULV circuits? Now we don't even have perfect OC on the circuit assline that's even more annoying.

**Comment by repo-alt** [comment]
Dedicated storage cells make little sense. A usual partitioned cell plays the same role. NBT overflow is not an issue if the cell still limits item types to like 64

**Comment by boubou19** [comment]
>I'm not sure on the feasibility of such an idea but couldn't we have special AE cells that uses say a 64m super chest in the recipe and creates a cell that holds up to 64m of 1 item? 

We have something similar from extracells, holding 65.5k items, it's called the ME block container. So a tier II ME block container could achieve that i guess.

**Comment by GTNH-Colen** [comment]
> Dedicated storage cells make little sense. A usual partitioned cell plays the same role. NBT overflow is not an issue if the cell still limits item types to like 64

A partition would yes but you still have the issue of expense, making cheaper variants that only hold 1 type of item would sidestep this.

**Comment by repo-alt** [comment]
Lobby Martin to make cells cheaper, there is not much sense for them to be that expensive

**Comment by GTNH-Colen** [comment]
> Lobby Martin to make cells cheaper, there is not much sense for them to be that expensive

In the long run this is probably the best solution which requires the least effort/dev work and reduces random bloat.

**Comment by repo-alt** [comment]
I'll look at the quantum chests, it sounds like a good idea to use them as a bulk storage, and not lose in efficiency. It is now more possible, since GT already have AE dependency and we control both sides.
