### ISSUE TITLE
Industrial Mixing Machine

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7446]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/59776356/107221183-40acec80-6a4e-11eb-88d9-42b91e90f28f.png)

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/107221219-4c98ae80-6a4e-11eb-96fd-147c2e013375.png)
I'm pretty sure this is not the centre
and there is no centre for 3x4
#
#### What do you suggest instead/what changes do you propose?
fix the text

**Comment by Prometheus0000** [comment]
Bother alk with that

**Comment by johnch18** [comment]
That seems pretty front-centered to me

**Comment by Eason134HK** [comment]
> That seems pretty front-centered to me
What about I put the controller one block higher
That seems pretty front-centered to me too but it just not work
must place the controller on the second layer

**Comment by Prometheus0000** [comment]
Again, go bother alk about it

**Comment by Dream-Master** [comment]
I hope the Day comes we can edit Gt++ or remove/replace it. Nothing is more bad then a not longer developed closed source mod.

**Comment by GTNH-Afx237v7** [comment]
_Cough_ Thaumcraft _cough_
