### ISSUE TITLE
Un-nerf the Iridium Alloy Ingot recipe.

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7447]
Change it back to using industrial diamonds and at least halve the crafting time in the assembler. Nonupling the diamond cost and making it take literal hours just to craft the raw ingots is fucking ridiculous.

**Comment by johnch18** [comment]
That, or at least make a way to make diamond dust https://en.wikipedia.org/wiki/Synthetic_diamond

**Comment by boubou19** [comment]
9 diamonds per ingot (laser engraving) at worse if you don't have a sifter giving out exquisite diamonds from time to time, given this is processed at IV tier, is not that much expensive. You don't need that much of the iridium alloy plates anyways.

**Comment by johnch18** [comment]
The ZPM tier PSS cells take **16** reinforced iridium plates per.

**Comment by Prometheus0000** [comment]
So? The PSS is still cheap compared to the LSC, isn't it?

**Comment by johnch18** [comment]
Not anymore it's not. I think the nerf to the ingots was short-sighted and overkill. It should be reigned back in.

**Comment by Prometheus0000** [comment]
Why don't you link the pr/commit so we know why it was changed then?

**Comment by boubou19** [comment]
Also, you complain for a bunch of diamonds for a zpm tier stuff? Diamonds are cheap

**Comment by johnch18** [comment]
This isn't high school debate club, I don't need to cite my reasons for finding something obnoxious.

**Comment by Prometheus0000** [comment]
Then we don't need to state our reasons for _not_ finding it obnoxious, now do we?

**Comment by GTNH-Afx237v7** [comment]
The previous recipe was a shaped crafting recipe, however you could either do it with exquisite diamonds from GT++ which had no way to obtain, or via exquisite cubic zirconia which had an EBF —> laser engraver „upgrading“ cycle.

**Comment by Dream-Master** [comment]
> Change it back to using industrial diamonds and at least halve the crafting time in the assembler. Nonupling the diamond cost and making it take literal hours just to craft the raw ingots is fucking ridiculous.

If you think something is unbalanced open an Github issue like other people do. If you don't like GTNH Pack play another more easy one. And we dont want to hear the "F" word here.

**Comment by Prometheus0000** [comment]
The PSS cells take LuV voltage, so this is an LuV recipe. If you can't figure out how to get sufficient diamonds or parallelize by then, it's not our problem.
