### ISSUE TITLE
Implement custom non-ticking MEMonitorHandler for quantum chests.

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7448]
Related to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7445

**Comment by GTNH-Afx237v7** [comment]
So for my understanding (and others as well), this is an implementation that, when I use a storage bus on a quantum chest (I assume any variant works), performance is improved? E.g. not check inventory count every tick, but only upon change?

**Comment by repo-alt** [comment]
Yes, it triggers cache update on _external_ change. If you don't use it directly but only through AE (which is usually the case) then it behaves essentially like partitioned cell now.
