### ISSUE TITLE
Cryogenic Freezer GT++ (tooltip don't say about muffler hatch)

### ISSUE THREAD

**Issue by Oueio** [GTNewHorizons/GT-New-Horizons-Modpack#7451]
#### Which modpack version are you using?
2.1.0.3a
#
#### If in multiplayer; On which server does this happen? 
single
#
#### What did you try to do, and what did you expect to happen?
Cryogenic Freezer works normally.
#
#### What happened instead? (Attach screenshots if needed)
After small number of recipes done, it turns off and don't work. Replacing controller helps for another small number of recipes.
There are 2 videos for demonstrating the problem.
**https://dropmefiles.com/6tG6r Password: nLHh4v Link for 7 days**

**Comment by GTNH-Afx237v7** [comment]
You forgot the muffler hatch, didn’t you? It may not be in the tooltip but based on this behavior it needs a muffler hatch.

**Comment by Oueio** [comment]
Yes, i didn't place muffler
if it's this, so thanks

**Comment by Dream-Master** [comment]
This file is 1 GB large and seems to looad very slow 6-7h download.

**Comment by Oueio** [comment]
eh, i will check if it's muffleer
sorry for videos, don't know how to load them normally

**Comment by Oueio** [comment]
Yeah, was muffler. Please write it on the tooltip

**Comment by Prometheus0000** [comment]
We can't change the tooltip, go bother alk at the GT++ repo for that

**Comment by Oueio** [comment]
okay

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GTplusplus/pull/36
