### ISSUE TITLE
Fertile Manure Slurry recipe has an error ingot

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7453]
#### Which modpack version are you using?
2.10.0

#
#### What did you try to do
I was looking for uses for human meat, and found it, the glitched recipe.
The ingot's name is "Errors - Tell Alkalus Ingot"
#
#### What do you suggest instead/what changes do you propose?
I'm not sure what's supposed to be there.

**Comment by Prometheus0000** [comment]
Go tell alkalus at the gt++ repo then
