### ISSUE TITLE
NPE in GT_MetaTileEntity_MultiBlockBase.java:314 until the muffler has a valid tile

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#7454]
#### Which modpack version are you using?
dev

Running with Latest GT5-NH Patch 8d2b13f7e466165b5aeaed2198a8573ef67131c3

gregtech-5.09.34.11.jar

#### What did you try to do, and what did you expect to happen?

Run GT5 Alone
Built an Electric Blast Furnace

When just placed, the Muffler is triggering repeated NPEs spam into `logs/Gregtech.log` until it can get a working tileEntity assigned.

Repeatedly logged at each ticking of the EBF into `logs/GregTech.log`:
```none
java.lang.NullPointerException
        at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_MultiBlockBase.onPostTick(GT_MetaTileEntity_MultiBlockBase.java:314)
        at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:556)
        at net.minecraft.world.World.func_72939_s(World.java:1939)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

#### TODO

- Check why the controller tries ticking poking the Muffler hatch before it gets a working TileEntity.
- Add a Null check before poking the tile.
- Include checking for valid operational TileEntity into the `checkMachine()` method.

**Comment by bartimaeusnek** [comment]
> aMuffler.getBaseMetaTileEntity().setActive(active);

Seems to me like you got a broken Muffler there..

**Comment by bartimaeusnek** [comment]
> Decouple or remove slept-in rogue dependency with TechTech or Barthwork.
Always document and discuss the reasons if a new dependency is to be introduced.

Sorry Lea, but there is no added dependancy. The Change of the multis are completely done on my side and do not interact from the gregtech-side. There is no code or logic or any dependancies in GT5U, the TecTech-Structure Check Multis are **replacements**.

> Always publish dependencies the legit way into the mcmod.info and loader class.

mcmod.info is a document that is used for fallback purposes and user information, it has little to no reason to list its dependancies there.

> Check that the EBF and any other multi-block affected by the coil changes still works as before.

Well ye. Thas what needed to be done with every Refactor, even tho this crash seems to be unrelated.

**Comment by leagris** [comment]
> > aMuffler.getBaseMetaTileEntity().setActive(active);
> 
> Seems to me like you got a broken Muffler there..

What is a broken Muffler I just placed?

**Comment by leagris** [comment]
So, turns out the NPe spam occurs until the machine structure has been validated.

It can be reliably reproduced by removing and replacing the muffler, or first time the muffler is placed.

**Comment by Prometheus0000** [comment]
Is this fixed?
