### ISSUE TITLE
Broken quicksilver recipe (Thaumic bases)

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#7455]
#### Which modpack version are you using?
MC1710
#
#### If in multiplayer; On which server does this happen? 
GTNH official ETA
#
#### What did you try to do, and what did you expect to happen?
I tried to use "making quicksilver" from Thaumic bases, there is a recipe to transmute silverwood to quicksilver.
#
#### What happened instead? (Attach screenshots if needed)
No such recipe in NEI and recipe doesnt work either with crucible or alchemical construct.
#
#### What do you suggest instead/what changes do you propose?
Remove this recipe from thaumonomicon (bad idea) or add recipe as it should be (good idea)
![изображение](https://user-images.githubusercontent.com/67397297/107508716-baa1ba80-6ba1-11eb-901e-699e4e94c9e5.png)
![изображение](https://user-images.githubusercontent.com/67397297/107508746-c3928c00-6ba1-11eb-9e38-f7f8a69634c8.png)

**Comment by GTNH-Afx237v7** [comment]
Tested with 2.1.0.0, and it is indeed not working. You can't select this recipe in an alchemical construct.

There is obviously a Thaumonomicon page added

https://github.com/GTNewHorizons/ThaumicBases/blob/98230988b35fff69fff34a39861de5c7fe04361e/src/main/java/tb/init/TBThaumonomicon.java#L550

but I don't see an actual recipe in the code?

https://github.com/GTNewHorizons/ThaumicBases/blob/master/src/main/java/tb/init/TBRecipes.java 

Additionaly, there is no recipe in the ThaumicBases.zs script file.

Maybe this was forgotten at some point?

**Comment by GTNH-Afx237v7** [comment]
Add this to Thaumic-Bases-01-Main.zs
I tested it and it works fine.

```
// --- Quicksilver
Crucible.addRecipe("TB.Quicksilver", <Thaumcraft:ItemResource:3>, <Thaumcraft:blockMagicalLog:1>, "ordo 1, venenum 1");
```

**Comment by Dream-Master** [comment]
why not pack it into the code ?

**Comment by Prometheus0000** [comment]
Not everyone knows how.

**Comment by GTNH-Afx237v7** [comment]
as i just learned my way of doing things on Github is not the best so for now i'll let it sit here...

**Comment by Prometheus0000** [comment]
Recipe is at https://github.com/GTNewHorizons/ThaumicBases/blob/98230988b35fff69fff34a39861de5c7fe04361e/src/main/java/tb/init/TBThaumonomicon.java#L102
I'd guess it's a conflict with another mod that adds a log to charcoal crucible recipe somewhere.

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/107708372-60802280-6c91-11eb-9dd6-374a40f4a5ae.png)
```String tKey = "GT_WOOD_TO_CHARCOAL";
                GT_LanguageManager.addStringLocalization(GT_MachineRecipeLoader.aTextTCGTPage + tKey, "You have discovered a way of making charcoal magically instead of using regular ovens for this purpose.<BR><BR>To create charcoal from wood you first need an air-free environment, some vacuus essentia is needed for that, then you need to incinerate the wood using ignis essentia and wait until all the water inside the wood is burned away.<BR><BR>This method however doesn't create creosote oil as byproduct.");

                GregTech_API.sThaumcraftCompat.addResearch(tKey, "Charcoal Transmutation", "Turning wood into charcoal", new String[]{"ALUMENTUM"}, "ALCHEMY", GT_OreDictUnificator.get(OrePrefixes.gem, Materials.Charcoal, 1L), 2, 0, 13, 5, Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.ARBOR, 10L), new TC_Aspects.TC_AspectStack(TC_Aspects.VACUOS, 8L), new TC_Aspects.TC_AspectStack(TC_Aspects.IGNIS, 8L)), null, new Object[]{GT_MachineRecipeLoader.aTextTCGTPage + tKey, 
                		GregTech_API.sThaumcraftCompat.addCrucibleRecipe(tKey, OrePrefixes.log.get(Materials.Wood), GT_OreDictUnificator.get(OrePrefixes.gem, Materials.Charcoal, 1L), Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.VACUOS, 2L), new TC_Aspects.TC_AspectStack(TC_Aspects.IGNIS, 1L)))});```
There's a GT recipe added, but it seems to allow both in the stripped pack I tested.

**Comment by Prometheus0000** [comment]
I thought commenting out
```// --- Quicksilver
recipes.remove(<Thaumcraft:ItemResource:3>);
// -
recipes.remove(<Thaumcraft:ItemNugget:5>);
```
 in the script files might help, but nope.

Unless someone can track down why the recipe is mysteriously removed, adding the script seems to be the only option for now.

**Comment by GTNH-Afx237v7** [comment]
maybe because here it uses different aspects - tree and order instead of poison and order?

https://github.com/GTNewHorizons/ThaumicBases/blob/98230988b35fff69fff34a39861de5c7fe04361e/src/main/java/tb/init/TBThaumonomicon.java#L550 

(How tf did I miss this line anyway? :confused: )

**Comment by Dream-Master** [comment]
the recipe is there but I guess gt recipe wood to charcoal use all wood types so it got overridden.

**Comment by GTNH-Afx237v7** [comment]
Can't they exist in parallel? One uses some aspects to turn wood into charcoal, the other uses some aspects to turn it into quicksilver...

**Comment by Prometheus0000** [comment]
_Like I said_ both recipes exist in the stripped pack (basically just GT and TB) I tested. And the script to remove QS recipes isn't removing it either, so it's some other kind of interaction.
