### ISSUE TITLE
Basic Arc Furnace quest# 662 LV Era missing prereqs

### ISSUE THREAD

**Issue by Obeliske1** [GTNewHorizons/GT-New-Horizons-Modpack#7458]
#### Which modpack version are you using?
1.7.10
#
#### If in multiplayer; On which server does this happen? 
Private server, confirmed in single player
#
#### What did you try to do, and what did you expect to happen?
The quest requires a Graphite Cell item# 6954/30865 only craftable in the canning machine. We at this point have not been informed of nor instructed how to make this machine yet. Also have done every other quest so far in the tree.

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Add in a quest to make the canning machine somewhere prior to this quest.

**Comment by Prometheus0000** [comment]
Are you sure the canning machine is required? It's not a crafting recipe or doable in a ULV tank?

Also, do you mean canning machine or fluid canning machine?

**Comment by Obeliske1** [comment]
There is a request for a fluid canning machine, no issues there. Specifically though there is no quest for the "Basic Canning Machine" ID# 1754/291 and the recipe for the Arc Furnace (quest ID#662) requires a graphite cell ID# 6954/30865 The only recipe for which is in a canning machine (not the fluid one).

I didn't have a canning machine made as I hadn't been instructed to by a quest and sure was confused for a bit. Not sure if this is intended or not so made the post. I have finished the LV quest tree almost entirely https://imgur.com/a/sYNqBu3

**Comment by Prometheus0000** [comment]
Ok, thanks. I'll rejigger it next time I edit the QB.

**Comment by Prometheus0000** [comment]
The only way you can skip the canner quest is if you only made the single use acid batteries, which are terrible. I still adjusted it, just in case.

**Comment by Obeliske1** [comment]
> The only way you can skip the canner quest is if you only made the single use acid batteries, which are terrible. I still adjusted it, just in case.

No idea I just followed the quests, I did make the single use batteries as those are a quest :P I appreciate it though thank you.
