### ISSUE TITLE
screwdriver, file texture

### ISSUE THREAD

**Issue by jesuseduardo90** [GTNewHorizons/GT-New-Horizons-Modpack#7460]
#### Which modpack version are you using?
2.1.0.0
#
#### What do you suggest instead/what changes do you propose?
how about mirror the texture of  (screwdriver or file) like the (hammer and softhammer) to stop bending my back to see better the letters to know the difference or see quicker the crafting on :v

**Comment by Dream-Master** [comment]
yes good idea

**Comment by boubou19** [comment]
![image](https://user-images.githubusercontent.com/12850933/107564447-b6e25800-6be2-11eb-92a0-adb5b02f5dd1.png)
it can be quite confusing if you are new to GT

**Comment by jesuseduardo90** [comment]
oh nice that was quick:v better then my school supportXD

**Comment by leagris** [comment]
You know, in real life as well, novices have difficulties to identify the right tool. Telling a wood chisel from a screwdriver, telling a wood grate from a file, a hammer from a mallet, kitchen knives from screwdrivers, a hot air gun from a hair dryer…

**Comment by Prometheus0000** [comment]
Duplicate of #6602. Also, I think they look fine, and are not hard to confuse, but I don't care if you flip one or something.

**Comment by jesuseduardo90** [comment]
:o welp srry

**Comment by jesuseduardo90** [comment]
Actually it was easy:v
[Inverted screwdriver.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5967800/Inverted.screwdriver.zip)

**Comment by Dream-Master** [comment]
you cant rotate only the texture you need to check the shadow as well

**Comment by leagris** [comment]
And update the item in-hand rendering orientation wit own class and then hope all texturepacks will update accordingly....

**Comment by jesuseduardo90** [comment]
yeah idunno what you mean about "shadow" i see everything good i guess optifine or is a server thing cause i dont see anything wrong(i disable mobs shadow with optifine but items? i never hear that) JEI also looks good so idunno.
or if you mean for other texture packs also reverse, cause if thats the case i dunno how to do that:v

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/107719781-fc685900-6ca6-11eb-9ad4-525432093796.png)
I think this is what dream means? Though it could be just the thing in the BG of the right one.

**Comment by jesuseduardo90** [comment]
oh ok i see well, i cant see that, what is that? i cant see that i mean for real i dont have that. optifine maybe idunno

**Comment by Prometheus0000** [comment]
I just zoomed in on boubou's picture. Dream might also mean the shadow in the middle
![image](https://user-images.githubusercontent.com/8517039/107721274-44d54600-6caa-11eb-872c-5a9f1adc6a45.png)

**Comment by Prometheus0000** [comment]
Ah, I closed it by accident before.

**Comment by jesuseduardo90** [comment]
i dont think he means that, i mirror the handel and each material head of gh and gh++
both parts are different textures

**Comment by jesuseduardo90** [comment]
I SEE because the update, delete extra stuff, aparently that cause the texture works just for me, so here for anyone who read this:v
[screwdriver inverted.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6797917/screwdriver.inverted.zip)
