### ISSUE TITLE
A suggested input for a quest for Forestry and Multifarms

### ISSUE THREAD

**Issue by Obeliske1** [GTNewHorizons/GT-New-Horizons-Modpack#7464]
#### Which modpack version are you using?
2.1.0.0 (see I can learn!)
#
#### If in multiplayer; On which server does this happen? 
Private Server /NA
#
#### What did you try to do, and what did you expect to happen?
Tried to connect GT wires to Forestry machines
#
#### What happened instead? (Attach screenshots if needed)
Nada, after several hours of googlefu I learned about the BC transport fluid pipes but these seem to not be implemented in the current version, this leads to every single forestry machine required a generator of some sort directly beside it. 

Today I had a friend over who knows more about GT and he suggested trying the EnderIO conduit and those transmitted a signal allowing generators to not go directly beside Forestry machines
#
#### What do you suggest instead/what changes do you propose?

I would suggest adding a quest to the forestry tree to teach people that these conduits can transmit the proper signal and allow these machines to work while not being directly attached to generators. I have no doubt that these quests exist elsewhere already that I haven't gotten to yet (having only unlocked MV) but the first place that they will be needed has been Forestry so far unless there is another source that I'm as of yet unaware of. The issue with that being of course that Forestry is expected to be started somewhere in the LV quest lines I think. As forestry is the only way I am aware of to get large amounts of resin and charcoal for processing. 

Further I would suggest putting it between carpentry and Forestry Core Block as (much as wires for the GT items) it will be needed for all generators and you don't unlock this portion of the quest chains until LV where you are also capable of crafting several of the EnderIO conduits.

**Comment by dvdmandt** [comment]
To clarify, the problem is that there are various quests making RF generators, but no comment on how to transfer RF from generator to consuming machine, ie with EnderIO energy conduits, possibly kinetic pipes or Extra Utilities?

**Comment by Obeliske1** [comment]
We did attempt kinetic pipes, either we did them wrong or they didn't work but essentially yes this is the gist of the issue.

**Comment by MartinEggerstedt** [comment]
Hi, i think because Buildcraft is not so popular to actual modded Minecraft Player.
You need a "Wooden Kinesis Pipe(Extration Pipe)" first at the Forestry/Railcraft Engine than the normal Kinesis Pipe towards the Forestry  Machine.  With this method you can power the machines with more than one engine :)

**Comment by MartinEggerstedt** [comment]
![2021-02-17_17 54 03](https://user-images.githubusercontent.com/36814129/108238596-640c2180-7149-11eb-99c2-ad758bf234b9.png)
