### ISSUE TITLE
Wrong recipes with molten potassium disulfate in fluid extractor 

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#7466]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta

![C1](https://user-images.githubusercontent.com/62377720/107745462-a500d200-6d14-11eb-8e20-676cafd3d96b.PNG)
![C2](https://user-images.githubusercontent.com/62377720/107745468-a7632c00-6d14-11eb-99c2-3de1996faa71.PNG)
![C3](https://user-images.githubusercontent.com/62377720/107745475-a8945900-6d14-11eb-9d6b-754261f38d29.PNG)
 
As you can see for the dust, the small pile and the tiny pile, the processing time and the power used is the same
 
#### What do you suggest instead/what changes do you propose?
 It should be 4 times quicker for the small pile and 9 times quicker for the small pile with the right amout of power consummed for each recipe

Sorry if it's a duplicate I searched and didn't see any issue about that

**Comment by Prometheus0000** [comment]
This is a BW material, right?

**Comment by Nicouuuuu** [comment]
yes it is 
![image](https://user-images.githubusercontent.com/62377720/107746000-71727780-6d15-11eb-93d2-a7f5476aba39.png)

**Comment by bartimaeusnek** [comment]
https://github.com/bartimaeusnek/bartworks/commit/58c1bf1bd33b714cb69a460a2a72105e0c61b06a
