### ISSUE TITLE
chisels and bits & flat colored blocks

### ISSUE THREAD

**Issue by firstdorsal** [GTNewHorizons/GT-New-Horizons-Modpack#7467]
have you considered adding chisels and bits as well as flat colored blocks?
or is there a reason why not?
great pack, thank you <3

**Comment by Prometheus0000** [comment]
There's no 1.7.10 version. If you want to backport it, it might be considered. I don't really know what it does differently from the existing stuff though, which seems capable of creating any shape you want.

**Comment by GTNH-Afx237v7** [comment]
Main devs said no Backport from them. Oldest branch is MC 1.8 under LGPLv3. So unless someone is really wanting to invest time and effort, most likely not happening.

**Comment by firstdorsal** [comment]
i would love to do it myself but as i have no experience in java/forge etc. it would take a lot more time to get into it than for someone that has these skills.
is there some realistic ammount for a donation i could make that would help to implement both mods?

**Comment by mitchej123** [comment]
Let's not go bothering other authors to backport something.
