### ISSUE TITLE
suggestion: "Unknown seeds no more" quest add a second possible prequisite

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7473]
#### Which modpack version are you using?
2.10.0

#
#### What do you suggest instead/what changes do you propose?
So, the unknown seeds quest in the fishing farming cooking tab requires the LV Scanner quest to unlock, but like it says you can use a Portable Scanner instead of a scanner machine block.
I suggest the portable scanner quest be added as an "OR" requirement, so you can skip the basic scanner quest if you want.  This would also mean the basic scanner block should not be in the unknown seeds quest (not sure why it is in the first place)

**Comment by Prometheus0000** [comment]
This is an LV tier quest, whereas the portable scanner is MV, so unless you put it off, you can't get it at that point.

> the basic scanner block should not be in the unknown seeds quest (not sure why it is in the first place)

Because you use it to scan the crops?

We can't account for every possibility of what the player can do.

**Comment by McFrugal** [comment]
The quest requires you to make a basic scanner to reach it, which is completed by having it in your inventory.  That immediately satisfies the condition in the unknown seeds quest, so what's the point of it being in there?

The quest isn't in the LV page, so I'd argue it's not in any particular tier.

**Comment by Prometheus0000** [comment]
Because LV is when you get the scanner? And the LV scanner is in the quest?

> so what's the point of it being in there

To show you what to make.

Technically, we should have scanned seeds, but there's such a huge variance in what you can get that would be a terrible idea.

**Comment by McFrugal** [comment]
You can't see what's in the unknown seeds quest until you complete the basic scanner quest.  Again, the unknown seeds quest is *unlocked* by completing the Basic Scanner quest.  So it doesn't show you what to make.

**Comment by Prometheus0000** [comment]
I'll adjust it then.

**Comment by McFrugal** [comment]
Oh, after advancing further and getting a portable scanner I realized you can't use it to scan seeds that you've pulled out of the crop sticks, so you need a scanner machine anyway and there's no reason to skip it.

**Comment by KiloJoel** [comment]
A cropnalyzer works as an alternative, so the scanner isn't required

**Comment by Prometheus0000** [comment]
Scanner is LV, cropnalyzer is MV.

**Comment by KiloJoel** [comment]
Both scanner and cropnalyzer require MV circuits, so they become available at the same time

**Comment by Prometheus0000** [comment]
Well, it's still easier to use the scanner. You only have to run it through once, and you can automate it.

**Comment by KiloJoel** [comment]
my point is just that neither is totally required, i never used scanner for crops

**Comment by Prometheus0000** [comment]
Ok, so? You don't need to make a PA either, but there's a quest for it. There's no reason to change the quest further, unless it's to remove the cropnalyzer quest and/or the portable scanner quest, but that would shove several paragraphs (each) into other quests, so I'm not going to.

**Comment by KiloJoel** [comment]
I thought the point of this is that a quest shouldn't gate another quest if it's not actually required for it?
This is why I was making it clear that the scanner is not required for crops progress.

**Comment by Prometheus0000** [comment]
Technically, you don't need to go to the moon to get titanium either, but you're still required to to complete the quest for it.

Like, do you want a single quest that has several pages of text in it? And making the cropnalyzer is still a good idea if you don't use the crops program (or can figure out how to start bart's), so you can see the breeding %s.

**Comment by McFrugal** [comment]
Oh, I should've read the text for the cropnalyzer quest.  Seems like you don't need a scanner machine at all for crops unless you want to automate mass seed identification...

**Comment by Prometheus0000** [comment]
KiloJoel, maybe you could be clear about what kind of change you want, because it's not really clear?

**Comment by McFrugal** [comment]
Nobody's suggesting that the cropnalyzer and portable scanner quests be removed.
I just think the basic scanner quest shouldn't gate the unknown seeds quest.

**Comment by KiloJoel** [comment]
> 
> 
> Nobody's suggesting that the cropnalyzer and portable scanner quests be removed.
> I just think the basic scanner quest shouldn't gate the unknown seeds quest.

^Essentially, this is what change I think would be good

As an alternative, unknown seeds no more could require the scanner quest OR the cropnalyzer quest. Right now the cropnalyzer quest comes after the unknown seeds no more quest, which makes very little sense, so the order of these should probably be swapped,
So 
[First breeding 719] -> [Analyze your crops 1541]
([Analyze your crops 1541] OR [Scanner quest 531]) AND [First breeding 719] -> [Unknown seeds no more 721]

**Comment by KiloJoel** [comment]
The first solution is probably better though, because of there being a third way of scanning plants (tricorder) meaning that both the scanner and cropnalyzer are not required
