### ISSUE TITLE
OC Charger recipe is ridiculous

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7476]
#### Which modpack version are you using?
2.1.0.1
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
![image](https://user-images.githubusercontent.com/23512002/107871243-d6aea000-6eb0-11eb-8a8b-b8a510af282d.png)

Player is supposed to be able to make a first robot at MV, but this recipe is not trivial even at late HV
Maybe make it cost T2 circuit and 1 MFE charger (or even CESU charge pad)?
(also, why 2 charge pads, they are not even stackable)

**Comment by Varkaus** [comment]
3 microchips level 3 is not so difficult to make)

**Comment by boubou19** [comment]
thing is this recipe adds unecessary tedium and discourage players from toying with OC early game. I'll be in favor of buffing the recipes.

**Comment by botn365** [comment]
i think lots of OC recipes should be redone they are not realy expansif but just a massif pain to make

**Comment by Prometheus0000** [comment]
You could suggest recipe changes? Or make a PR with them?
