### ISSUE TITLE
2.1.0.0QF1 Wrong Glass pane for quest "Dimond tanks... Oh Shiny"

### ISSUE THREAD

**Issue by Lithorn** [GTNewHorizons/GT-New-Horizons-Modpack#7477]
#### Which modpack version are you using?
2.1.0.0QF1 GTNH
#
#### If in multiplayer; On which server does this happen? 
Personal Server
#
#### What did you try to do, and what did you expect to happen?
Complete quest - Diamond Tanks... Oh Shiny. Expected to use glass panes requested by quest to make diamond tank.
#
#### What happened instead? (Attach screenshots if needed)
Quest calls for normal glass pane, but crafting calls for clear glass pane and are not interchangable
#
#### What do you suggest instead/what changes do you propose?
Have quest call for Clear Panes

**Comment by Prometheus0000** [comment]
I checked and it uses regular and dyed regular glass panes in 2.1.0.3a. Try again in that version.

**Comment by Lithorn** [comment]
The quest or the actual craft? If quest, then we can close this.

**Comment by Prometheus0000** [comment]
Both.
