### ISSUE TITLE
World anchor, forestry farms

### ISSUE THREAD

**Issue by Varkaus** [GTNewHorizons/GT-New-Horizons-Modpack#7478]
2.1.0.0

Server is not official

World anchor after exiting the game does not work on the forestry farm

**Comment by GTNH-Afx237v7** [comment]
What exactly does not work? No crop growth? No harvesting? No consumption of water/power/fertilizer?

**Comment by Skiftcha** [comment]
on my server it does not plant saplings
and this is hard to reproduce for me, it breaks randomly after restart. so you can disconnect normally a few times but after a long uptime it breaks till restart.
i think this is somehow related to fakeplayer used to plant saplings

**Comment by Varkaus** [comment]
> на моем сервере он не сажает саженцы,
> и мне это трудно воспроизвести, он случайно ломается после перезапуска. поэтому вы можете нормально отключиться несколько раз, но после долгого времени безотказной работы он прерывается до перезапуска.
> Я думаю, это как-то связано с fakeplayer, который сажает саженцы, когда игрок не в сети.
> потому что у нас было 2 фермы от разных игроков, и только у одного из нас была остановка фарма,
> возможно, сломалась после посещения других измерений

yes

**Comment by boubou19** [comment]
What kind of server this is? plain forge? thermos? ultramine? crucible?

**Comment by Skiftcha** [comment]
ultramine

**Comment by Varkaus** [comment]
thermos

**Comment by boubou19** [comment]
would be cool if we could get it to happen on a plain forge server.

**Comment by Skiftcha** [comment]
this is actual and annoying but i have no idea how to fix

**Comment by boubou19** [comment]
did you changed the log level of your server logs to debug? maybe you'll get some useful information on how to track it down.
