### ISSUE TITLE
Buff Robes of the Stratoshpere

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#7483]
Considering that it is locked at IV tier with osmiridium, it would be nice if it can provide hazmat protection.
Idk if I missed something but that's the first armor that gives creative-like flight, and right now it's kinda a tradeoff to use it, as pollution is an issue, and it needs to be swapped everytime radioactive materials need to be handled.
I guess the rest of the armor would need to have the same effect applied aswell

**Comment by alphaNOVAircraft** [comment]
Seems to be fine to me. It has its tradeoff - early creative-like flight vs pollution. The hazmat creative like flight is locked behind zpm.

**Comment by Glease** [comment]
Duplicate of #6366

**Comment by yukieiji** [comment]
Isn't Thaumostatic Harness the first armor that gives you creative-like flight?(need fuel)
