### ISSUE TITLE
ProjectRed not seeing all items in drawers when interfaced with a controller

### ISSUE THREAD

**Issue by q009** [GTNewHorizons/GT-New-Horizons-Modpack#7484]
#### Which modpack version are you using?
2.1.0.0
ProjectRed version 4.7.0pre13.11

#
#### If in multiplayer; On which server does this happen? 
Local server

#
#### What did you try to do, and what did you expect to happen?
ProjectRed Transportation pipe network interfaced with a drawer controller.
The pipe network should be able to see all items stored in the drawers as well as be able to correctly determine whether they're full.

#
#### What happened instead? (Attach screenshots if needed)
ProjectRed Transportation pipe network only sees up to one stack of items in drawers, when interfaced with a drawer controller.
Additionally, when routing items into network, the items don't always land in the drawers (particularly, when sending more than one stack at a time.) It appears as if the network is unable to determine whether the drawer system can hold more items.
**As of latest available ProjectRed version from modpack 2.1.0.3a - ProjectRed-4.7.0pre13.11 the problem no longer occurs when interfaced with drawers directly. However, drawer controller compat seems still broken.**

**Comment by Prometheus0000** [comment]
Duplicate of #3393. It's closed source, so it would need ASMing to fix.

> As of latest available ProjectRed version from modpack 2.1.0.3a - ProjectRed-4.7.0pre13.11 the problem no longer occurs when interfaced with drawers directly. However, drawer controller compat seems still broken.

Is it broken or not? If you say it's not broken, why did you make the ticket?

**Comment by q009** [comment]
@Prometheus0000 the very last sentence of the ticker says explicitly that the controller compat is broken.
Sorry if I didn't make a clear enough distinction between **direct** and controller interface. By direct I meant connecting interfaces to drawers themselves. That part works fine. It's when you try to connect it to controllers it fails.

**Comment by Prometheus0000** [comment]
Ok, I don't know the mod at all. Maybe try the LP stuff in the latest version?
