### ISSUE TITLE
suggestion: disable gregtech arrows on skeletons

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7485]
#### Which modpack version are you using?
2.1.0.0
#
#### What do you suggest instead/what changes do you propose?
The chance for gregtech arrows (set at 16 right now) is mostly pointless.  It doesn't really do much unless the skeleton gets really lucky and fires something intensely radioactive at you, in which case you just die unless you have some way of removing it (I'm not sure you can?  I seem to remember milk doesn't remove the debuff from a high dose of radiation).
A good alternative would be to change the radioactive arrows' effect to poison instead of radiation.

**Comment by basdxz** [comment]
What the fuck

**Comment by mtesseracttech** [comment]
> The chance for gregtech arrows (set at 16 right now) is mostly pointless. It doesn't really do much unless the skeleton gets really lucky and fires something intensely radioactive at you, in which case you just die unless you have some way of removing it (I'm not sure you can? I seem to remember milk doesn't remove the debuff from a high dose of radiation).

Milk worked fine, last time I tried.

**Comment by redmage17** [comment]
But seeing people die of plutonium arrows is funny. Not like 90% of the mobs in this pack are mean spirited with diabolic mobs factored in.

**Comment by Dream-Master** [comment]
yes milk works fine. Not a issue. If you @redmage17 complain more i will add more dangerous arrows to gt code :P
instant death and lost your grave :P
