### ISSUE TITLE
Hard dependency on AE2 introduced into Gregtech

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#7486]
#### Which modpack version are you using?
dev

Better quantum chest integration introduced a hard dependency to AppliedEnergistics2 into Gregtech, causing a crash if AE2 is not present:

https://github.com/GTNewHorizons/GT5-Unofficial/commit/d3e4deddbae28129fe3300af21dbff6cfb3b1b01#diff-940478cd2e1eac043c677d19ef4031648d9cec64e3fb63b821379e77d24eab5aR24

[crash-2021-02-16_18.14.44-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5990441/crash-2021-02-16_18.14.44-client.txt)

**Comment by repo-alt** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/438
