### ISSUE TITLE
Water tank siding are generating a bit of lag

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7487]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
eta and delta
#
![image](https://user-images.githubusercontent.com/12850933/108101979-4460f480-7088-11eb-8d08-bd37f0056f5f.png)
as you can see, for ~32 water tank sidings, I get 0.8ms taken by them, while the coke oven multis are taking 65µs for 24 of them.

after digging a bit with warmroast, the lag comes when the tanks are outputting the water:
![image](https://user-images.githubusercontent.com/12850933/108102356-bc2f1f00-7088-11eb-89a3-3574d0c5d7d1.png)

**Comment by Prometheus0000** [comment]
Does it happen no matter what method to output water you use? Like using a pump instead of just a pipe? Or putting a tank next to it (if that works).

**Comment by boubou19** [comment]
Sadly, i can't isolate the top laggy ones, as opis consider them as not laggy enough blocks to be listed in the report for single TileEntities. But i can imagine most of the players using GT pipes on them without putting a pump on the pipes, as it's a relatively cheap option.

**Comment by KiloJoel** [comment]
> 
> 
> Does it happen no matter what method to output water you use? Like using a pump instead of just a pipe? Or putting a tank next to it (if that works).

Given that the highest cost is checking if a block exists, I guess it happens no matter what. Probably just a case of 20+ tanks doing 54 checks each every tick
