### ISSUE TITLE
Trying to craft acacia fence (and any other fence with fall back to plain wood presumably)

### ISSUE THREAD

**Issue by Heliarco** [GTNewHorizons/GT-New-Horizons-Modpack#7488]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Occurs on both single player and private multiplayer server.
#
#### What did you try to do, and what did you expect to happen?
Timeline of events.
1. Created a world ~6 months ago played a bit. then stopped (World 1)
2. Return after v 2.1.0.0 released
3. Update pack via technic launcher
4. Continue playing World 1
5. Craft acacia fence with no issue
6. Time passes
7. Try to craft fence, but fails, get oak fence instead <---- not good

Meanwhile:
I can create a new world, and craft the things just fine

#
#### What happened instead? (Attach screenshots if needed)
Plain old boring fence got crafted from pristine acacia planks

#
#### What do you suggest instead/what changes do you propose?
Fix it, or provide instructions how to repair an old world

#
#### Diagram because visuals help
![image](https://user-images.githubusercontent.com/72616574/108138195-b99aec80-70bd-11eb-9db5-caf2ea10da23.png)

**Comment by Heliarco** [comment]
forgot to mention /mt reload had no effect

**Comment by Dream-Master** [comment]
can you chisel it?

**Comment by Dream-Master** [comment]
i mean is chisel on fence possible ?

**Comment by bartimaeusnek** [comment]
This is  a side effect of the recipe speedup. Since the Acacia Fence and regular Fence recipes are basically the same, the Fence recipe will take priority over it, since its crafted more often.

**Comment by leagris** [comment]
> This is a side effect of the recipe speedup. Since the Acacia Fence and regular Fence recipes are basically the same, the Fence recipe will take priority over it, since its crafted more often.

Not exactly. All wooden fence recipes have been merged into a single ore-dictionary recipe for the oak fence. All other wooden fences are obtained from the oak fence using a chisel.

**Comment by Heliarco** [comment]
@Dream-Master No it cannot be chiseled, neither in world via right click or using the chisel gui. Also no NEI entry indicating so.
@bartimaeusnek  ´why is this not a bug? There is no way for me to craft the items? AT ALL
@leagris I would need an illustration how to do this, im currently checking in a new world and a world created before 2.1.0.0 and a chisel doesn't seem to be involved here. 


Again important to note, the fence can be crafted just fine in a NEW world, just not in an OLD world. I have lnked an old world for your testing convenience.

https://1drv.ms/u/s!AoWjHlYUP1a4gv9FttCFykLuDg_quA?e=bgqTin

**Comment by bartimaeusnek** [comment]
@Heliarco It's a recipe issue, not a code bug.

**Comment by Heliarco** [comment]
Aha, i misunderstood the tag then. Is there a way i can "reset" the recipies to what they would be in a new world then? Or do i have to abandon the world?

**Comment by botn365** [comment]
the abilety to chisle fences should be add then

**Comment by Heliarco** [comment]
Update since i did more testing: 
Turns out that the test world i made AFTER updating, that is in a NEW World, also has the broken recipe after entering and exiting a couple of times.

Probably means the problem is unrelated to the whole "upgrading the gtnh version" process then.

I am literally losing recipes by playing the game 😆

also for extra hilarious shenanigans, tried crafting other wood types -> fences:

alder wood (extra trees) -> Hawthorn fence
maclura wood  (extra trees)  -> Hawthorn fence
cherry wood (forestry) -> cherry wood fence (SUCCESS :D )
