### ISSUE TITLE
Limestone to fluorite ore recipe

### ISSUE THREAD

**Issue by Leche-Caliente** [GTNewHorizons/GT-New-Horizons-Modpack#7491]
#### Which modpack version are you using?
2.1.0.0

The current recipe for fluorite ore involves using an assembly machine to make limestone out of stone and calcite, placing that limestone in the world, and mining it for a 1/32 chance for fluorite ore. This recipe doesn't make sense, isn't in line with any of the other recipe's in GTNH, and is un-automatable and tedious. 

The above recipe should be removed, and a chemical reactor recipe should be added in its place which simply turns calcite into fluorite dust.

Edit* This issue is specific to the context of HV, I know that there are post-moon ways of automating fluorine.

**Comment by KiloJoel** [comment]
I'd possibly be in favour of a different/more involved process, but support the general idea.

**Comment by GTNH-Afx237v7** [comment]
Is fluorite ore from GT++? If so, then it is intentionally not automatable, i.e. player only drop.
Give crops a chance (black stonelillies). :)

**Comment by KiloJoel** [comment]
I would love to see some viable alternatives to some things you are mostly forced to use crops for

**Comment by Prometheus0000** [comment]
> Is fluorite ore from GT++? If so, then it is intentionally not automatable, i.e. player only drop.
Give crops a chance (black stonelillies). :)

Go read the very long, very circular discussion in #general. That was already discussed. https://discord.com/channels/181078474394566657/181078474394566657/811501064565686313

**Comment by Leche-Caliente** [comment]
I'm well aware of black stonelillies, and plan on using them myself. That doesn't excuse the fact that the recipe described above is comedic. I wasn't aware of any design philosophy of GT++ that demanded things not be automatable, and if one exists, I would have to wonder how it fits this pack.

GT: New Horizons is not supposed to be tedious. If it's tedious, you are doing it wrong. The idea that people should be expected to basically perform the vanilla flint recipe, and that said recipe is the 'correct' path outside of crops, for a key resource in HV is absurd.

**Comment by Glease** [comment]
For reference alk made it to be not automatable and fixed numerous stuff that allow automated creation of fluorite, e.g. TT fake player.

**Comment by Leche-Caliente** [comment]
> For reference alk made it to be not automatable and fixed numerous stuff that allow automated creation of fluorite, e.g. TT fake player.

Note my previous comment:
"GT: New Horizons is not supposed to be tedious. If it's tedious, you are doing it wrong. The idea that people should be expected to basically perform the vanilla flint recipe, and that said recipe is the 'correct' path outside of crops, for a key resource in HV, is absurd."

Instead of hiding behind "it's like this because so-and-so said so," why don't you provide an actual reason to justify the recipe against what I've said.

**Comment by Glease** [comment]
>> **for reference**

I know this **fact**. You seems to not know it, so I remind you of it. That's all. I don't have a particular **opinion** towards this issue.

**Comment by Leche-Caliente** [comment]
> > > **for reference** alk ......
> 
> I know this **fact**. You seems to not know it, so I remind you of it. That's all. I don't have a particular **opinion** towards this issue.

This: "e.g. TT fake player." statement lead me to believe otherwise.

**Comment by GTNH-Afx237v7** [comment]
Eventually, there is nothing we can do about the mechanic of limestone to fluorite ore.
GT++ is ARR, Alk has not released any builds in quite some time, it remains doubtful if she touches it again.

It remains another topic to add a chemical reactor recipe to make fluorite dust out of ingredients.
Given that you can use black granite dust (from macerating black granite in the overworld), or from lepdidolite, or from crops (black stonelillies) or other sources I currently can't remember...there is already a variety of ways to get fluorine.

**Comment by Leche-Caliente** [comment]
> Eventually, there is nothing we can do about the mechanic of limestone to fluorite ore.
> GT++ is ARR, Alk has not released any builds in quite some time, it remains doubtful if she touches it again.
> 
> It remains another topic to add a chemical reactor recipe to make fluorite dust out of ingredients.
> Given that you can use black granite dust (from macerating black granite in the overworld), or from lepdidolite, or from crops (black stonelillies) or other sources I currently can't remember...there is already a variety of ways to get fluorine.

Am I mistaken about the capabilities of the development team? Don't they disable, edit, and add new recipes to various mods in the pack all the time?

Surely it is possible to disable the current limestone recipe, and give calcite a machine recipe that does the same thing, albeit without necessary player interaction. Even if disabling the current recipe is impossible, adding the new one surely is, which would be enough on its own.

The fact of the matter is, outside of crops, the only optimal method of getting fluorine pre-moon is this process. You list black granite as an alternative for instance, 1x black granite provides 18L of fluorine. This is not a viable method considering that black granite is not in-and-of-itself all that easy to gather large amounts of.

The current calcite recipe exists, we are clearly implicitly accepting the narrative that there is fluorine in calcite. Why exactly shouldn't you be able to get fluorine out of calcite in one of the same ways you can get any of the other byproducts out of resources in the mod?

**Comment by boubou19** [comment]
> Am I mistaken about the capabilities of the development team? Don't they disable, edit, and add new recipes to various mods in the pack all the time?

You are right, the dev team do that often. However, gt++ has been so much of a pain in the pack, that no one wants to tweak it, even by editing the recipes externally. You are given alternatives, if you don't accept it, then feel free to make a pull request reflecting your recipe changes, because we accept external help too.

**Comment by Skiftcha** [comment]
imo removing mining chance to manually get fluorite is useless nerf.
if you want automation you can use chem plant recipe for fluorite ore

**Comment by Leche-Caliente** [comment]
> imo removing mining chance to manually get fluorite is useless nerf.
> if you want automation and do not want to do crops you can use chem plant recipe for fluorite ore

Chem plant is not HV tier, which is the context of this discussion. I realize this was not clear in the original issue, and will edit accordingly.

**Comment by 0lafe** [comment]
You can avoid the crop req by using stone -> black granite. Slight power increase, but considering how little F/PTFE is used, it more than holds up. 
There's also the many F containing ores that are more than viable even without using mining machines. Especially once you hit the moon and can get Nd veins, which doesn't take much PTFE to do. 

Not everything really needs to be infinitely generatable imo, especially considering this is HV and the product isn't used much itself

**Comment by Leche-Caliente** [comment]
> You can avoid the crop req by using stone -> black granite. Slight power increase, but considering how little F/PTFE is used, it more than holds up.
> There's also the many F containing ores that are more than viable even without using mining machines. Especially once you hit the moon and can get Nd veins, which doesn't take much PTFE to do.
> 
> Not everything really needs to be infinitely generatable imo, especially considering this is HV and the product isn't used much itself

My problem was more that the limestone recipe doesn't make sense, and so I wanted it replaced with something else or removed. The consensus seems to be that GT++ is just a stupid mod, and there's no reason to change this because it isn't game breaking.
