### ISSUE TITLE
Sticky Jars can't craft with Arcane Crafting Terminal

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7492]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Try to craft Sticky Jars
#
#### What happened instead? (Attach screenshots if needed)
Can't craft with Arcane Crafting Terminal

・Arcane Crafting Terminal
![2021-02-17_20 20 30](https://user-images.githubusercontent.com/40425798/108212607-6f734300-7171-11eb-8f48-09dc16289909.png)
・Arcane Crafting Table
![2021-02-17_20 20 44](https://user-images.githubusercontent.com/40425798/108212625-7306ca00-7171-11eb-9a84-e2c3b451fabf.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it

**Comment by Prometheus0000** [comment]
Try one that doesn't have any nbt attached, like that network thing I see there.

**Comment by Prometheus0000** [comment]
Also, I don't know anything about mirrored jars, maybe it doesn't work with them?

**Comment by yukieiji** [comment]
Same with normal Jar
![2021-02-17_22 51 40](https://user-images.githubusercontent.com/40425798/108213771-bdd51180-7172-11eb-8d61-6b77c7dccc30.png)
![2021-02-17_22 51 23](https://user-images.githubusercontent.com/40425798/108213781-bf9ed500-7172-11eb-8cb0-abf2001a168f.png)

**Comment by yukieiji** [comment]
> Also, I don't know anything about mirrored jars, maybe it doesn't work with them?

It works well with Sticky Mirrored Jar crafted with the Arcane Crafting Table.
![2021-02-17_22 54 06](https://user-images.githubusercontent.com/40425798/108214468-8fa40180-7173-11eb-8830-4c2459f1eadb.png)

**Comment by repo-alt** [comment]
What mod adds this recipe?

**Comment by yukieiji** [comment]
Gadomancy
![2021-02-18_00 09 44](https://user-images.githubusercontent.com/40425798/108223856-9cc5ee00-717d-11eb-89a0-3961557c2c3d.png)
![2021-02-18_00 08 50](https://user-images.githubusercontent.com/40425798/108223802-87e95a80-717d-11eb-806f-dce418c13fd0.png)

**Comment by Ethryan** [comment]
Recipe Location: [Link](https://github.com/GTNewHorizons/Gadomancy/blob/master/src/main/java/makeo/gadomancy/common/crafting/RecipeStickyJar.java)

For those troubleshooting

**Comment by repo-alt** [comment]
Yea, it returns null aspect list from the inventory check.

**Comment by repo-alt** [comment]
I guess I'll just check both signatures, like crafting table does. Gadomancy maybe not the only mod with such behaviour.
