### ISSUE TITLE
some weird issue lv combustion generators seem to have with HOG

### ISSUE THREAD

**Issue by wakasagisan** [GTNewHorizons/GT-New-Horizons-Modpack#7493]
#### Which modpack version are you using?
2.0.10
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
I try to supply lv combustion generators with HOG through pipes and expect it to work like the other generators
#
#### What happened instead? (Attach screenshots if needed)
apparently they only use HOG supplied through cells, and ignore the HOG supplied by piping
#

**Comment by GeicowithaBango** [comment]
the combustion engine didn’t explode?

**Comment by botn365** [comment]
are you sure you test this corectly for me cell or piping it in wont work witch makes way more sense then only 1 of them working

**Comment by wakasagisan** [comment]
> the combustion engine didn’t explode?

it didn't

**Comment by wakasagisan** [comment]
> are you sure you test this corectly for me cell or piping it in wont work witch makes way more sense then only 1 of them working

for me only the cell worked.

**Comment by botn365** [comment]
but that doesent make any sense 
fluid cell will put fluid in to the tank of the generator the pipe does the same thing
and even then the engin shoulnd work becous its internal buffer is to small to work corect and stops working
how are you testing this becous i feel like the problem is there

**Comment by wakasagisan** [comment]
I'm doing this in my survival mode gameplay. About how I test it,  I did what I described and only the cell input method allows the generator to work. This problem only happens with LV generator, while the piping method works fine with the other tier comb gen.

**Comment by botn365** [comment]
i need more details then that 
did you break the generator and place it back between test did you check if it actual can fill a battery

**Comment by wakasagisan** [comment]
I didn't break it, but it's connected to cables with machines requiring energy. The generator doesn't even consume the HOG as if it's a gt tank, there is no fire sprite representing it's generating energy when I empty it up. But when I put the cell in, there is fire sprite remains even if I empty it, and it has the generator running animation playing on top of the block too

**Comment by botn365** [comment]
place the genrator and pipe in hog and see if the machine can run
then break it and place it again then do the same but with a cell

**Comment by wakasagisan** [comment]
Like i said that's what I did and only cell can run

**Comment by dvdmandt** [comment]
I noticed something on 2.0.9.0, some combustion engine "recipes" in NEI show that you get a certain amount of energy and an empty cell back, others (like boosted diesel and HOG) only give energy. When I tried using cells of boosted diesel, the cells disappeared as energy was being generated, while using regular diesel gave me energy and empty cells back. It was very strange though, first it filled up the internal tank and gave me those 16 cells back, so I refilled those to leave 64 full cells in the generator, but after that it started eating them.

**Comment by Prometheus0000** [comment]
I thought it couldn't use HOG because the amount/t it produces is more than the generator buffer size, but I guess that's not true?

**Comment by greesyB** [comment]
> I thought it couldn't use HOG because the amount/t it produces is more than the generator buffer size, but I guess that's not true?

This is true in 2.0.9.0 at least. I'm not sure if it was changed in 2.1, but didn't see any related issues with a quick search.
