### ISSUE TITLE
Unable to craft greatwood slabs

### ISSUE THREAD

**Issue by MatthewCOwen** [GTNewHorizons/GT-New-Horizons-Modpack#7496]
#### Which modpack version are you using?
2.1.0.3a
#

I wanted to craft the arcane bellows
![image](https://user-images.githubusercontent.com/16054364/108309835-2f0ec780-7167-11eb-8795-e294be9e0467.png)
but there's no recipe for the greatwood slabs
![image](https://user-images.githubusercontent.com/16054364/108309895-4948a580-7167-11eb-9f30-53481e9888ca.png)
![image](https://user-images.githubusercontent.com/16054364/108309926-56659480-7167-11eb-9f32-59cfd1eed4e9.png)

#### What do you suggest instead/what changes do you propose?
Fix the recipe so it gives greatwood slabs

**Comment by Prometheus0000** [comment]
You don't appear to be able to chisel it either.

**Comment by GTNH-Afx237v7** [comment]
Cutting Greatwood Logs and Silverwood logs into their respective planks as well as both types of planks into their respective slabs works fine in 2.1.0.0.
As pointed out by Glease on discord 

https://github.com/GTNewHorizons/GT5-Unofficial/blob/92d0fb5b6657fe673b60c426dcfadee7cf1a683f/src/main/java/gregtech/loaders/oreprocessing/ProcessingPlank.java#L36-L54

is where plank recipes are auto-generated.

Only change in this code between release of 2.1.0.0. and 2.1.03a was made by mitchej123:

https://github.com/GTNewHorizons/GT5-Unofficial/commit/3b6bc659ee5a38644ce0c3e55dbc3363e3a7100e#diff-79bb17f82a9ce4982bd5e3bdacf829d7f83fc895039e48e02ecf49b5a5128969

(not pointing my finger at you mitchej123, this is just the only change present)

**Comment by mitchej123** [comment]
Added an unholy hack as a workaround.  If this type of issue pops up again I'll fix the underlying cause.
