### ISSUE TITLE
Witchery NEI lookups broken in 2.1.0.0

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7498]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Both eta and single
#
#### What did you try to do, and what did you expect to happen?
Looked up the recipe for odour of purity, it only shows this page
![image](https://user-images.githubusercontent.com/17787093/108351877-f9f18c00-71dd-11eb-9c97-4fdb606a13b1.png)

#
#### What happened instead? (Attach screenshots if needed)
But when looking up the uses for a hawthorn sapling, this recipe can be seen which makes odour of purity
![image](https://user-images.githubusercontent.com/17787093/108351960-18578780-71de-11eb-8c1e-99d090bf9258.png)

This was not broken in 2.0.9.0, looking up the recipe for odour of purity correctly showed the witches oven recipe.

I believe this is the case with other items too, but can't confirm since I don't know what the recipes are meant to be,
For example Exhale of the horned one shows no recipe at all

**Comment by KiloJoel** [comment]
Tested and still broken with latest versions of NEI and witchery extras (2.0.10 and 1.1.1)

**Comment by Prometheus0000** [comment]
It crashed for me in 2.1.0.3a when looking at one of the witchery sapling recipes. 
[crash-2021-02-18_22.53.59-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6007623/crash-2021-02-18_22.53.59-client.txt)
