### ISSUE TITLE
Checking NEI recipes too soon after loading up the game causes it to hang

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7500]
#### Which modpack version are you using?
2.1.0.3a
NotEnoughItems-1.7.10-2.0.7-GTNH-universal.jar
#
#### What did you try to do, and what did you expect to happen?
Check a recipe
#
#### What happened instead? (Attach screenshots if needed)
Hangs
#
#### What do you suggest instead/what changes do you propose?
Was checking alu gravel. Also happened before. Didn't generate a crashlog.
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6007800/fml-client-latest.log)

**Comment by mitchej123** [comment]
Try again with 2.0.9

**Comment by Prometheus0000** [comment]
It's intermittent unfortunately. When I loaded up the game again NEI was more responsive and there was no crash. Previously it was super slow, like it was building a database or something?

**Comment by mitchej123** [comment]
Repost if it happens with 2.0.9.  You are using an outdated version
