### ISSUE TITLE
Brew of shifting seasons kicked people from server

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7502]
#### Which modpack version are you using?
2.1.0.0 with updated witchery extras
#
#### If in multiplayer; On which server does this happen? 
eta
#
#### What did you try to do, and what did you expect to happen?
Threw a brew of the shifting seasons to change the biome
#
#### What happened instead? (Attach screenshots if needed)
Game kicked me and 3 others (different locations, not everyone) with this message:
![image](https://user-images.githubusercontent.com/17787093/108507776-b9177700-72b2-11eb-81ce-f70ee4359f6f.png)

From fml-client-latest.log:
https://pastebin.com/arYXSm7R

**Comment by Prometheus0000** [comment]
Is it the one from the quest? I removed it in case it was that. Also see #6764, though that has a different error.

**Comment by KiloJoel** [comment]
The brew was thrown at a TileEntity, apparently that is known to cause problems. I've not tried one not throwing at a TileEntity yet

**Comment by KiloJoel** [comment]
It's not from the quest

> 
> 
> Is it the one from the quest? I removed it in case it was that. Also see #6764, though that has a different error.

It's not from the quest

**Comment by KiloJoel** [comment]
> 
> 
> The brew was thrown at a TileEntity, apparently that is known to cause problems. I've not tried one not throwing at a TileEntity yet

I tried throwing it at a normal block and same result

**Comment by Prometheus0000** [comment]
Try doing it in SP (and crafting it the same way), maybe it's thermos? It may also be a result of the witchery extras changes somehow.

**Comment by KiloJoel** [comment]
Tested in singleplayer and a locally hosted server, didn't happen in both instances, but it didn't kick everyone when done on eta (didn't kick me the second time), so I guess it's hard to rule out too much.

It seems to me like this would have been found earlier if it happened before witchery extras was added, so my best guess is an interaction between WE and Thermos.
