### ISSUE TITLE
crash due to an interaction between tfft hatch and AE

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7505]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
eta
#
Might be caused by the NPE issue in the old version of kekztech in the 2.1.0.0, but i prefer to open an issue just in case it is not. Here is the crashlog:
[crash-2021-02-19_16.25.29-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6015498/crash-2021-02-19_16.25.29-server.txt)

**Comment by Prometheus0000** [comment]
See #7159, which has the same error and should be fixed. You can probably dl a version of kekztech off the jenkins to fix it, though not for the server I guess.
