### ISSUE TITLE
The 2nd part of the task in quests # 877 # 887 # 1191 is not counted.

### ISSUE THREAD

**Issue by GamerTriStuS** [GTNewHorizons/GT-New-Horizons-Modpack#7506]
#### Which modpack version are you using?

2.1.0.0
#### If in multiplayer; On which server does this happen? 

sp
#### What did you try to do, and what did you expect to happen?
The problem was previously discussed #6219. There is a suspicion that this occurs in a small number of players, no fixes have been made and are not planned.
#### What happened instead? (Attach screenshots if needed)
The situation is similar in 3 quests, let's look at # 877. The drawing shows that the required element for the task and the element created on the workbench (or obtained from the creative) have differences.

![2021-02-20_20 35 56](https://user-images.githubusercontent.com/52796465/108607788-9e88ef00-73d3-11eb-8c98-223ccf2eb9bc.png)

Еxperimentally, I made changes to the DefaultQuests.json file, wrote 40 instead of 4.
After this change, the quest was completed successfully.

![bandicam 2021-02-20 20-41-41-453](https://user-images.githubusercontent.com/52796465/108608134-0a6c5700-73d6-11eb-8db6-aebe5055d956.jpg)
![2021-02-20_20 45 44](https://user-images.githubusercontent.com/52796465/108608239-c168d280-73d6-11eb-962d-9ab2ba1ee44d.png)

#### What do you suggest instead/what changes do you propose?
Will there be any corrections? After editing the DefaultQuests file.json may be a problem?

**Comment by Prometheus0000** [comment]
I hand made the items instead of getting them out of NEI to fix this, but I'll check again, I don't remember if the other ones were about a scepter.

> After editing the DefaultQuests file.json may be a problem?

There's no problem with this. You can also force complete the quest.

**Comment by Prometheus0000** [comment]
887 cannot be fixed, as crafting staffs is broken. I fixed the other 2 though.
