### ISSUE TITLE
Turbine texture change causes FPS stutter

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7508]
#### Which modpack version are you using?
2.1.0.0

#
#### What did you try to do, and what did you expect to happen?
I noticed a FPS drop and spent some time figuring out what the cause was.  Initially I thought it was from steam in the pipes because the FPS drop went away when my solar boilers turned off at like 4 AM, but then I figured out the FPS drop also stopped when my batteries filled up.  Also before you ask, yes, I have my pipes set to one-way flow via the built in muffler hatches.
Turns out the turbines switch texture from the animated one to a still texture when they are empty of fuel, in this case steam.  My steam production doesn't keep up so they do this frequently, and I get microstutter every time it happens, resulting in my average FPS dropping.  I have six turbines doing this so the FPS drop was noticeable, going from a smooth 60 fps to... usually 51 but sometimes dropping to 45 or so.  The microstutter was the main issue, and that doesn't impact the average FPS as much as you'd think.

#
#### What do you suggest instead/what changes do you propose?
There might be a way to fix it without disabling texture switching via more optimized code, but you could just set the blocks to only use one texture and players would barely notice.  It's useful for diagnosing power problems but you can also just go up close and use WAILA's fluid display to tell if a turbine has fuel or not.

**Comment by Prometheus0000** [comment]
Use a fluid regulator? Like you're told to?

**Comment by McFrugal** [comment]
Okay, I looked it up and apparently it replaces the texture, so sure.  That works.  That won't solve it for anyone that doesn't know about that, though, which brings me to...
I don't know what you mean by "like you're told to".  I can't find anything in the questbook that says that.

**Comment by Prometheus0000** [comment]
? You're supposed to use them with every turbine to have a steady flow of fluid so the power output and fluid input doesn't vary up and down. It should talk about it in the FR quest, or one of the 3 turbine quests. Or all of them. Or the tooltips on the MBs.

> Also this adds extra expense to every turbine if you're not keeping up with demand.

You might as well say the turbine is an extra expense. If you don't want to use something they're designed to be used with, that's up to you.

> Okay, I looked it up and apparently it replaces the texture

This makes no sense. It doesn't replace anything, it just prevents the turbine from choking if it doesn't have enough fuel.

**Comment by McFrugal** [comment]
Choking?  No, I'm not using large turbines.  These are single block turbines.  I have some solar boilers feeding some Basic and Advanced Steam Turbines.  They consume more steam than I can produce, so they run out and the texture changes rapidly causing stutter.

**Comment by Prometheus0000** [comment]
Then what you do is take one away one at a time until they stop turning on/off. Or add more boilers. This kind of flickering FPS drop stuff is present on _all_ machines AFAIK.

**Comment by McFrugal** [comment]
If I did as you said and removed turbines, I would not be able to use my steam storage as a battery.  Steam storage only works that way if you can consume it faster than it's being filled, like actual EU batteries work.  It'd result in shorter EBF runs, which is bad.  It's not a reasonable solution.  If I added enough boilers to keep up with consumption then that's... a lot more boilers, and I'm not rushing so I don't actually need the extra EBF uptime.
The order of events is this: I have full batteries and a large amount of steam, so I start put something in my EBF, and my batteries start draining.  My turbines turn on to compensate, and start draining my steam.  At some point my steam runs out and my turbines start stuttering.  They keep doing that until my EBF is done, the batteries charge to full, and my steam tanks start filling.

What I *could* do that would actually work somewhat without ruining everything or requiring a massive boiler expansion is replace my basic turbines with another Advanced turbine.  Less turbines means less texture flickering which means less FPS issues.  It wouldn't totally fix things but it'd be better.  I'd just lose some efficiency.
What I'm actually going to do is switch to diesel for my EBF's power generation and leave my solar setup in place exclusively for smaller machines, which means I would very rarely run out of steam even if I let my boilers calcify.

This issue will still exist though, and would mostly be encountered in early to mid MV when some players would still be using solar boilers and some LV turbines, with no obvious reason to make an MV turbine.  The efficiency loss disincentivizes it, even.  I never considered making a large turbine because I thought it'd be too expensive and annoying to keep fed with rotors, though I guess I never actually looked at the details...

**Comment by McFrugal** [comment]
What other machines are likely to flicker like this?

**Comment by Prometheus0000** [comment]
All of them

**Comment by Prometheus0000** [comment]
Try going to the gtplusplus config file and set B:enableAnimatedTurbines to false.

**Comment by McFrugal** [comment]
EU-consuming machines have a several seconds long cooldown period after failing a recipe, and during that cooldown period they're regaining a buffer of EU, so they won't flicker.
I don't think other types of turbines are likely to flicker either, because they have much higher energy density fuels.

**Comment by leagris** [comment]
What is more likely to cause client lagg is the needed network packet transmission between server and client to notify the client each time the machine rendering has to be updated. It has exactly the same cost as a block update + cost of updating the client-side tileentity's `ITexture[][]` array.
1. 1.7.10 Forge using inefficient Netty network library sends packet to 1.7.10 Forge client
2. Client receive packet of machine changed state
3. Client update the ITexture[][] array for the machine's tile instance with:
  - Reinstantiating an IIcon from a ResourceLocation into the ITexture array

All of these steps have a significant cost for the client.

**Comment by Glease** [comment]
GT definitely doesn't reload an IIcon from disk upon every state change. IIRC all active and inactive icons are registered on meta tile entity registeration, and loaded into memory later using a callhook in some GT block's `registerBlockIcons`

**Comment by McFrugal** [comment]
Changing the GT++ turbine texture config option to false didn't work.  Maybe it only works for the multiblock turbines?  I did a search in the configs and the only other thing I could do is turn off all animated textures.
Also I don't see anything in the tooltips regarding regulators or whatever.

**Comment by GTNH-Afx237v7** [comment]
Regulators are usually used in combination with multiblock turbines; I believe I have not seen them being used for singleblock steam turbines.

**Comment by Prometheus0000** [comment]
Regulators are for MBs generally. I thought you were using MBs before.

They're talked about in these quests:
![image](https://user-images.githubusercontent.com/8517039/108665891-0149bb80-74a4-11eb-8b2e-a4b16483d9c2.png)

Also, this is the animated turbine tooltip, you need to hit shift:
![image](https://user-images.githubusercontent.com/8517039/108665837-d6f7fe00-74a3-11eb-802a-69ad49d4034e.png)

**Comment by McFrugal** [comment]
That's not present in my game.

**Comment by Prometheus0000** [comment]
I dunno what to tell you, it show up for me. Also, you said it doesn't work, so...
