### ISSUE TITLE
suggestions for things to be displayed on a computer screen at spawn

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7510]
I thought it could be great to have an open computer screen to display various informations about the server at spawn. Here are the ideas i have in mind:
- list of the richiest players on the server (already implemented on delta)
- list of the players the most online on the server
- time left until the next planned reboot
- current TPS (I still need to find a better way than what is used on eta)

If you have other ideas let me know, and i'll see if i can implement them.

**Comment by Nicouuuuu** [comment]
Why do you want to display the current TPS ? The xu_tps command is not enough ? or maybe not well known ? 
Also I can suggest to add maybe like a "dim tracer" to see which dims are loaded and who is in the dim ? (player/chunk loader)
Don't know if it's very usefull but why not ?

**Comment by boubou19** [comment]
well /xu_tps is accurate most of the time, unless you have issues with your ISP. Having the TPS displayed somewhere on the server can help you to know if you are having issues with your ISP or if it's the server. About the dims, IIRC all the dims have a forceloaded chunk (the one containing the origin of the coordinate grid). What i *could* with some black magic, is to display the top 5 heavy dims every X minutes.

**Comment by Nicouuuuu** [comment]
Oh yeah okay I see now,
Yeah why not, It could be easier to monitorate the servers for the operators

**Comment by boubou19** [comment]
well, we that little amount of data, can't really know what's going on, but you can tell at least what void dim is laggy for endgame players.
