### ISSUE TITLE
Multiblock Goals quest "Time To Get Some Steel" has wrong number of Firebricks needed

### ISSUE THREAD

**Issue by Hillgrove** [GTNewHorizons/GT-New-Horizons-Modpack#7511]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
Eta

#
#### What do you suggest instead/what changes do you propose?
change quest to indicate you to make 37 firebricks as is needed to make the BBF.

**Comment by Prometheus0000** [comment]
It's already been changed, but I'll change the text if it's wrong.

**Comment by Hillgrove** [comment]
Closed issue.. The number is correct. I thought the multiblock needed to be enclosed and not have a hole in the "roof".
