### ISSUE TITLE
can we get crop seedbag at 100% ?

### ISSUE THREAD

**Issue by NoX-programer** [GTNewHorizons/GT-New-Horizons-Modpack#7512]
#### Which modpack version are you using?
2.1.0.0
#
#### What did you try to do, and what did you expect to happen?
While crossbreeding seeds on IC2 crops, I got another new crop with seed of new type or better stats. And now I want to get guaranteed seedbag from it.
#
#### What happened instead? (Attach screenshots if needed)
But we don't have any tool that provide guaranteed seedbag drop (don't we?). So I do left click crop with anything or spade (from cropsPP) and have some chance to get seedbag or get nothing. The chance of losing [my precious] seedbag is very upsetting!
#
#### What do you suggest instead/what changes do you propose?
1. come to an understanding and agreement that we really need an opportunity and a tool to get a 100% chance of seedbag drop [only when seed is mature, maybe]
2. we can decide to fix CropsPP spade to make it drop seedbag at 100% (Also, it have "Has a higher chance of yielding seedbags!" in tooltip, but it's a lie!), maybe also make it's recipe little more expensive
3. or leave CropsPP spade as is and invent new tool which will guarantee seedbag drop (I suggesting materials: polycaprolactam, nether star, void metal)

**Comment by repo-alt** [comment]
Just don't break that new crop. Cross breed it with something and with almost 50% probability you will get another one, that you may try to pick.

**Comment by NoX-programer** [comment]
I spent a long enough of time to get some useful crop from world random. And you insist that I have spent not enough time - I need to spend more to get a chance to get some useful crop... I disagree! I want to craft a tool (expensive enough), that will solve this problem of chance.

**Comment by Glease** [comment]
If you really want to stop seedbags from voiding, go craft TT's focus of dislocation. It can transport crops around without converting it to seedbags first. Granted it's expensive, hard to get, take quite a bit of vis and can only transport one plant per focus, it's much better than nothing. It does skip the growth phase as well.

**Comment by boubou19** [comment]
can't the dolly do that as well?

**Comment by Glease** [comment]
maybe it can. never tried it, but tt's focus definitely works and don't give you slow

**Comment by NoX-programer** [comment]
@Glease I do already use TT's focus of dislocation. There is still pain-in-the-\#\#\# while regular improving stats and trying to get new types. It's just uncomfortable without the right tool.

**Comment by Viktor-KN** [comment]
Why we discussing "need or don't need"? Just add such tool and make it require star gates components in craft.

**Comment by McFrugal** [comment]
IC2 crops are annoying enough without being unable to move them around.
Just give us something.  ANYTHING.

**Comment by repo-alt** [comment]
Focus is not single use, you just move plants one by one. I suppose any tool would work like that.

**Comment by GTNH-Afx237v7** [comment]
Please bear in mind that crops, while tedious to get the right type and good stats, require pretty much 0 effort and resources to maintain and give infinite yield. Personally I don’t think that a tool to guarantee  100% drop chance is needed.

**Comment by McFrugal** [comment]
Bees are free resources too, and you don't need anything special to preserve new breeds once you get them.  You can move bees and housings freely, there's no weeds to worry about, and currently they are FAR more hands off to progress through.
There's two things that crops are better for:
1, things you can't get from bees
2, randomly getting a useful high tier crop early

**Comment by repo-alt** [comment]
You can also automate crop breeding. Bees are much worse in that respect.

**Comment by Prometheus0000** [comment]
> 1, things you can't get from bees

Like? Was there stuff?

> 2, randomly getting a useful high tier crop early

Which you can't use because of under block reqs.

> These advantages do not outweigh the annoyance IMO. Crops should be similar in annoyance level.

They're already super duper annoying. And bees are too.

> A tool that guaranteed a seed drop would mean you could move seeds in mass quantity instead of one by one, and allow storing of seeds without loss. It's an important QOL increase.

You can already move crops. And you can make multiple wands if you want. Ad you can probably move them with teleposers or spatial AE stuff en mass. And what reason would you have for needing to move tons of them or storing tons of them? There's no reason to allow 100% chance to get seeds. You can also get more than 1 when breaking it you know?

**Comment by McFrugal** [comment]
You can automate bee breeding with apiarist's pipes.  I know of no way to automate crop breeding-- if you leave crop sticks unattended weeds will eat your seeds.

**Comment by Prometheus0000** [comment]
I think repo meant the completely absurd OC program someone made recently. Though I see no reason you can't do something like that with bees.

**Comment by repo-alt** [comment]
You technically can do that with bees but that would be _really_ absurd, complexity-wise

**Comment by Prometheus0000** [comment]
> Black granite.

Both slag and stone comb give black granite dust.

> because I have to stand there and watch them to crossbreed

You don't. Go do something else for a bit and come back. Or read/watch something at the same time.

> A blood magic Teleposer seems like it might be a bit more reasonable for moving crops around, but the biggest area is 7x7 and also you have to get deep into blood magic which has few other benefits.

The ability to TP to other planets easily doesn't appeal to you? OK, then.

> I've never gotten more than 1 seed from a crop except for oreberries

You need a high resistance to to gain a higher chance at it. You have a lower mutation chance though.

> The spade tooltip says it has higher drop rates for seed bags but the questbook says it has worse drop rates-- which is true?

The tooltip is lying.

> Speaking of poor documentation and seed drop chances, apparently the more stats and higher tier your plant is the harder it is to get a seed bag. Why?! Why is this a thing?

To make it harder I guess? You can just make them with the crop machines, you know? If you're tiered up enough for the crop. And if you're really serious about crops, you should, to get maximized crops.

**Comment by McFrugal** [comment]
Walking away from an empty crop is not a good idea, weeds can spawn within like 30 seconds and then spread within 5 minutes.  IIRC even a crop matron with weed-ex won't fully prevent weeds.  Bees, on the other hand, can be set to perform automated crossbreeding for hours.  Or you can make powerful frames to make crossbreeding nearly instant and at a much higher chance.  Or just brute force it with Gendustry.

What machines make crop seeds?  Do you have any automated way of crossbreeding except with OpenComputers and I presume drones?  Is there any machine that allows bruteforcing crop crossbreeding?

We should at least have a specialized harvesting tool.  One that works as well as a Spade on low growth stages, and as well as punching the crop at high growth stages.  Or, heck, an upgraded Spade that's never worse than punching the crop.

**Comment by bedrill64** [comment]
Holy you are going nuts on this thread, I see no problem with implementing LuV tiered electric spade for 100% drop chance so people stop crying about not having a tool that they won't use anyway because it is going to be tiered high. 

You can move crops with dislocation focus and some block idk what's it's called. if you want you can spread crop to 4 adjacent slots and gamble for seeds, it's not like given crop is going anywhere. And there is literally no point in having crops in seed forms besides seed duping, which again require mad machine tier and no one uses that.

This is not the topic about crops vs bees balance. This topic appears at least daily in discord chat, no new ideas gonna be said here, so stop the balance issue and just decide if you want another useless overtired mechanic that can't be balanced and never gonna be used.

**Comment by Prometheus0000** [comment]
> weeds can spawn within like 30 seconds and then spread within 5 minutes

Are you WAing them or something? You can leave for 10+m and have no problems in my experience.

> IIRC even a crop matron with weed-ex won't fully prevent weeds

Completely untrue if you set it up properly.

> What machines make crop seeds?

Read the questbook

> We should at least have a specialized harvesting tool. One that works as well as a Spade on low growth stages, and as well as punching the crop at high growth stages. Or, heck, an upgraded Spade that's never worse than punching the crop.

Ask bart to implement one then. Or, do it yourself.

**Comment by bcmpinc** [comment]
I don't think this is going to change in the pack, especially now that IC2 is planned for removal. However, for current players who do not want to deal with IC2's punitive RNG and constantly babysit their crops, I made a mod that removes most of that stuff: https://github.com/bcmpinc/IC2CropsQoL. One change is that crops are guaranteed to drop a single seed (don't use the CropsPP spade though). I mostly made it for myself so I can do IC2 crops *and* have fun, but thought other people might find some use in it as well.
