### ISSUE TITLE
ME interface terminal cause serious lag

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7513]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
A player was afk inside the gui of the interface terminal, and his chunk was taking 11ms by its own. the lag went away as soon as the gui was closed
![image](https://user-images.githubusercontent.com/12850933/108715051-9f786880-751a-11eb-99e1-6e89df161adc.png)
![image](https://user-images.githubusercontent.com/12850933/108715085-aacb9400-751a-11eb-8ad0-13e259a6f9d4.png)

**Comment by combusterf** [comment]
ME size/stats:
![image](https://user-images.githubusercontent.com/8459776/108715377-16adfc80-751b-11eb-972a-c0e296f8fbc8.png)
![image](https://user-images.githubusercontent.com/8459776/108715416-23325500-751b-11eb-824c-e6e55eec0fe4.png)

**Comment by repo-alt** [comment]
well, detectAndSendChanges() is a generic client/server synchronization mechanism, it is not something I can easily change. I guess I can close the GUI after like 10 minutes, but the whole scenario is a bit unusual

**Comment by Glease** [comment]
It is not that unusual. Sometimes I do idle at terminal GUI when waiting for some long crafting job to finish.

**Comment by repo-alt** [comment]
It is interface terminal, kinda strange to idle before it. It compares sever and client inventory to track moving patterns between interfaces. Granted, the whole system may be optimized, but it is not exactly trivial, and prone to dupes/desyncs if done inaccurately.

**Comment by Glease** [comment]
Oh sorry, I mistaken the title and thought it's the normal interface that contains the ME network content.
