### ISSUE TITLE
circuit assembly line config not working corectly

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#7514]
2.0.9.0
SP

Unless there is a bug somewhere nanocircuits cost 4-6x what they used to in base components. I know people had issues with them having a slight edge previously over other circuits but this is overkill. At least reduce the cost of the base tier nano circuits or do some more thoughtful balancing. 6x just on the board is nuts

**Comment by Glease** [comment]
Use circuit assembly line.

**Comment by redmage17** [comment]
I disabled the CAL adjustment in the config should not be doing that then

**Comment by Glease** [comment]
What is your current configuration? I didn't code this part but my first guess would be bart's negative number wreck havoc again. Try something like 14 instead of -1.

**Comment by redmage17** [comment]
Will do was at -1

**Comment by redmage17** [comment]
14,16, didn't work. 9 does not sure why

**Comment by redmage17** [comment]
Bartworks 0.5.13.1 is the version in the pack in case it comes up
