### ISSUE TITLE
Strange dependencies when trying to run a stripped down instance

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7515]
#### Which modpack version are you using?
Latest from jenkins
#
#### What did you try to do, and what did you expect to happen?
When trying to get a stripped instance with the minimum to run the coremod, I run into odd error messages. I have found (after a number of hours) what mods are necessary, but it seems strange that they are. I made sure to use the latest versions too.
![image](https://user-images.githubusercontent.com/8517039/108775600-4c5ce080-752f-11eb-8577-df9889199e5b.png)
If I remove forgelin or modmixins I get 
[crash-2021-02-22_17.00.03-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6025423/crash-2021-02-22_17.00.03-client.txt)
If I remove spongemixins, I get
[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6025450/fml-client-latest.log)
Any combination of removal of the 3 mods has the spongemixins error take priority.
#
#### What do you suggest instead/what changes do you propose?
I remember 2 of the mixin/asm mods had a dependency, maybe it isn't fixed properly? Assuming it wasn't different mods. Also, I don't see why the coremod would bug out if any/all of them were removed. Please find what's causing it and fix it, as I couldn't figure it out.

**Comment by Glease** [comment]
Modmixin is written in kotlin, so it requires forgelin to be present. It also depends on functionalities from SpongeMixins to do anything, so it require said jar to be present as well. 

All of these are kind of coremods, so it happens before normal mods loading, thus doesn't have the nice friendly forge interface telling you what's missing and what not.

From the stacktrace it seems someone messed up classloading order again. no idea where it comes from though.

**Comment by Prometheus0000** [comment]
My main point is that the 3 don't seem to have anything to do with the gtnhcoremod, but it throws an error without all 3.
