### ISSUE TITLE
Super Tanks should retain fluids (at least with a dolly or something)

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7519]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Mine
#
#### What did you try to do, and what did you expect to happen?
Idk
#
#### What happened instead? (Attach screenshots if needed)
Super tank dropped fluid
#
#### What do you suggest instead/what changes do you propose?
Just making them retain fluids either with a dolly or just by mining them? It is kind of annoying to lose that much fluid and not being able to move it at all really.

**Comment by 0lafe** [comment]
use pipes, or cells, or any other fluid movement lol 

orrrrr get creative and use PR frames or BM teleposers 

imo it's nice when the player isn't able to do much on their own, at least quickly. it incentivizes more intricate setups

**Comment by alphaNOVAircraft** [comment]
Yeah just make Ender Tanks steam age and all the problems are fixed LMAO 

Super tanks store insane amounts of fluid (and you get them early on and they are way to cheap imo). So its just fair that they have some sort of drawback.

**Comment by alphaNOVAircraft** [comment]
But i wouldnt mind a Super Tank Mover Dolly that is crafted with one complete stargate, so its kinda teleporting the super tank to its new destination. Guess stargate in recipe would make it balanced

**Comment by mitchej123** [comment]
As a point of reference: The super tank not saving its fluid is a legacy bug where NBT wasn't properly persisted when broken.   If this is considered a "feature" in GTNH, so be it.

Also please let's not encourage moving more tile entities with teleposers or PR frames... great way to corrupt worlds @0lafe

**Comment by 0lafe** [comment]
literally my bad for suggesting fun and engaging gameplay mechanics lol 

i also feel as though i should have ran into this "corruption" given my extensive use of frames, teleposers, and spatial AE. somehow i guess i'm just lucky that my worlds have lived through me moving sfm networks, AE networks, GT multis, and blocks that error out of existence 🤷‍♂️

**Comment by boubou19** [comment]
I can assure that teleposing a SFM inventory controller can corrupt it, because i witnessed such a case on Eta, where it was kicking every player loading the corrupted inventory controller.

**Comment by 0lafe** [comment]
with frames or teleposers? frames can do kicking things, but that's not exactly an sfm issue from my experience but just a frame issue from too much data

bm maybe but do you have the config enabled to remove erroring entities? i've seen some sfm errors but i always kept that config on so i would just loose my controller when i fucked up

**Comment by GTNH-Afx237v7** [comment]
GT fluid tanks are cheap, offer rapid emptying/filling of various fluid containers and interaction with machines and provide decent storage. So in my eyes they should be left as is. There are portable tanks/Performance friendly long distance fluid pipes and the aforementioned fluid containers if you need your fluids moved from A to B.

**Comment by GTNH-Afx237v7** [comment]
So it was mentioned briefly on discord that there could be an upgrade to make a tank keep its content. I have to say it sounds like a decent idea, especially when upgrade cost scales with tank cost.

**Comment by leagris** [comment]
Random simple solution:
Add cover to tank over its output side as a seal lead. Tank is no longer capable of output fluid but can be moved with fluid in it. When setting the tank back at destination, use crowbar to remove the cover lid, so it can output again.

**Comment by miozune** [comment]
For reference: fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/738
