### ISSUE TITLE
Lapotronic Capacitors and "Orb" Batteries 

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#7520]
#### Which modpack version are you using?
Version from Officeal server Eta
#
#### If in multiplayer; On which server does this happen? 
Official server: Eta
#
#### What did you try to do, and what did you expect to happen?
I tried to craft Lapotronic Capacitor (UV) on Assembling Line
![image](https://user-images.githubusercontent.com/70205464/108889697-bbb0fe00-761d-11eb-8e7f-e4ec62ccb60b.png)

#
#### What happened instead? (Attach screenshots if needed)
Assembling Line craft Energy Cluster
![image](https://user-images.githubusercontent.com/70205464/108889826-de431700-761d-11eb-9bb1-fc43cc8c916f.png)

#
#### What do you suggest instead/what changes do you propose?
Reposition items in recipes for all Lapotronic Capacitors
![image](https://user-images.githubusercontent.com/70205464/108890545-c5873100-761e-11eb-8d4d-e7847db04ca0.png)
![image](https://user-images.githubusercontent.com/70205464/108890586-d172f300-761e-11eb-9891-32e4e21bfb0d.png)
![image](https://user-images.githubusercontent.com/70205464/108890672-e9e30d80-761e-11eb-9fac-fd829ca66e2c.png)
![image](https://user-images.githubusercontent.com/70205464/108890701-f23b4880-761e-11eb-92fc-df1651a21e7e.png)

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/KekzTech/pull/10
