### ISSUE TITLE
Turn off the vengeance mechanic, it is the worst mechanic.

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7521]
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Mine
#
#### What did you try to do, and what did you expect to happen?
Not have a shitty mechanic
#
#### What happened instead? (Attach screenshots if needed)
had a shitty mechanic
#
#### What do you suggest instead/what changes do you propose?
The vengeance mechanic from infernal mobs is universally hated and turned off by many players in this pack. I propose we turn it off on the official config since it is literally the worst mechanic in infernal mobs by all means by all players who have run into it.

**Comment by boubou19** [comment]
The whole point of the infernal mobs is to piss you off by having a little challenge very early game. If you find one, just go back, like any other infernal mobs with difficult traits. If i follow your logic, then we should disable many traits from config, because they are a massive pain to deal with, to the point where mobs are close to vanilla again.

**Comment by Alastors** [comment]
no my point is that it isnt just annoying, infernal mobs is fine my point is it isnt a challenge at all, its just straight up a bad mechanic, I mean dying everytime you hit a mob with your weapon? Dungeon crawling and you run into a mob with vengeance that you didnt realize had vengeance and now you insta-killed yourself because of the mechanic. My point is if so many players turn off *this* mechanic in particular, it must be for a reason. and that reason is because it is a terrible feature that deserves to be turned off above all others. The others are just annoying and challenging vengeance is just full on malicious and idiotic.

**Comment by Impos913** [comment]
I never died because of vengeance, you need good protection and high hp. (my crossbow one shots wither and still never died to vengeance)

**Comment by alphaNOVAircraft** [comment]
Are you trying to make GTNH a FTB modpack or what are your intentions, im getting kinda confused

**Comment by Alastors** [comment]
god no, i have no idea why you would even think that, my point is, it is the most turned off mechanic in the game besides pollution in 2.1 and I cant have been the only person to notice that.

**Comment by boubou19** [comment]
Players are responsible for what they do to modpack config: we know that the hardcore darkess and the pollution have a lot of haters (and i'm one of them for the pollution). But i did not know about the Vengence trait being disabled.

**Comment by Alastors** [comment]
I have certainly noticed a lot of people complain on that mechanic in particular in the couple months I have been on the discord and that actually where I got the idea from to turn it off in the first place from other people turning it off, I genuinely would not have even thought about the config file if others hadn't mentioned it first. Ive actually never seen anyone complain on hardcore darkness though lmao.

**Comment by Elisis** [comment]
I wouldn't say it's that shitty. It's pretty easy to avoid mobs in most instances, and there's absolutely nothing stopping you from turning it off yourself.

**Comment by Alastors** [comment]
lol I already did tbf

**Comment by 0lafe** [comment]
i hope all this negativity doesn't dissuade you from posting more of your thoughts. i find them interesting

**Comment by Yarntheory** [comment]
It's not a great mechanic, and I personally disabled it in SP. However, rather than just turning it off maybe have a Tips and Tricks quest telling people where and how to adjust the configs?

Vengeance is particularly bad because crossbow damage especially scales up very quickly. If you are use to sniping with your crossbow, you tend to frequently snipe at a vengeance mob without being able to see the actual infernal modifiers, resulting in killing yourself. While i would say adding a more obvious visual effect to the vengeance modifier would be ideal, I expect that is not easy, and i know i'm not coding it.

**Comment by Alastors** [comment]
It doesn't really I didn't really think of these conversations as negativity tbh. Why do ya think my thoughts are interesting though? Im curious.

**Comment by Alastors** [comment]
or is that sarcasm?

**Comment by 0lafe** [comment]
usually i'm the one getting shat upon for my ideas, so i like seeing someone else straying from the norm

people like to stay in their mentalities so having some new ideas is always nice to see. personally i'm not super opposed to this idea. most recently i was playing a pack with no mobs at all, and i found it to be a more enjoyable experience in some ways. i think difficulty is a complex idea, and simply making mobs more powerful doesn't exactly make the game harder most of the time

**Comment by Alastors** [comment]
tbfff the super tank thing was based off a different thing where I didn't understand why the drum (not the bedrockium one obvi) cost meteoric iron tbh and that got into a little discussion on the discord. and yeah I get that tbh, when you can easily kill the hydra in a couple shots more powerful mobs can't really compete with that.

**Comment by dvdmandt** [comment]
I personally feel like there should be a better counter against it (like an amulet or something), or that it's damage was limited to like 80% of max health or similar. I've instakilled myself too many times from shooting things before even seeing that it's an infernal, like on asteroids for example. I'm not for turning it off completely, but I would really like to see a nerf or counter.

**Comment by Prometheus0000** [comment]
What if instead of reflecting the damage back at you it did a set amount of damage, or a %? Like 5 hearts or 25%? So you don't get killed immediately. BTW, what is the strategy to kill them? Soul vial+kill zone? Or is there any?

**Comment by KiloJoel** [comment]
How about 2 things to lessen the stupidity without completely removing it
-Nerf crossbows (I guess everyone agrees here, they get out of hand very quickly)
-Modify vengeance so its damage is dealt after armour and ignores overkill damage (I'm not 100% sure this is accurate, but is what I remember from when I looked at the code last)

**Comment by Impos913** [comment]
> What if instead of reflecting the damage back at you it did a set amount of damage, or a %? Like 5 hearts or 25%? So you don't get killed immediately. BTW, what is the strategy to kill them? Soul vial+kill zone? Or is there any?

Having runic shielding or high enough hp makes them no problem.

**Comment by ScriptedPiky** [comment]
> What if instead of reflecting the damage back at you it did a set amount of damage, or a %? Like 5 hearts or 25%? So you don't get killed immediately. BTW, what is the strategy to kill them? Soul vial+kill zone? Or is there any?

Basically that, yeah. For lower tiers, it's either stabbing them repeatedly with a Tinker's Rapier with Life Steal, having them wander on spikes of sorts, or killing them with lava (assuming it's not certain Nether variant mobs)

**Comment by KiloJoel** [comment]
> > What if instead of reflecting the damage back at you it did a set amount of damage, or a %? Like 5 hearts or 25%? So you don't get killed immediately. BTW, what is the strategy to kill them? Soul vial+kill zone? Or is there any?
> 
> Having runic shielding or high enough hp makes them no problem.

Yeah, they 1-shot you right up until the point where you get some gear and then they do nothing at all from then on. Not a great mechanic

**Comment by Impos913** [comment]
You can have high hp early on ¯\_(ツ)_/¯. Food crafting is stone age. It is more of a player fault to insta die to vengeance imo.

**Comment by KiloJoel** [comment]
I have been 1-shot with 55 damage from vengeance from shooting a 50 health mob. Having more health doesn't guarantee survival, you're just hoping the mob you're shooting has less health than you

**Comment by McFrugal** [comment]
Vengeance dealing flat retaliatory damage would be great.

**Comment by bombcar** [comment]
Modify vengeance to never deal more damage than the mob had health AND make it so that you can’t actually die to a vengeance hit (leaves you at one half heart). 

Then if you react quickly you can live, but you’re in a very vulnerable state.

**Comment by bombcar** [comment]
Vengeance has been nerfed to never do more damage than the mob had health.
