### ISSUE TITLE
Nei glitch with bees

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7524]
#### Which modpack version are you using?
2.1.0.3
#
#### If in multiplayer; On which server does this happen? 
mine
#
#### What did you try to do, and what did you expect to happen?
Bookmark bees
#
#### What happened instead? (Attach screenshots if needed)
Only can bookmark one Queen, one Princess, and one Drone
#
#### What do you suggest instead/what changes do you propose?
a change to the system so that we can bookmark any number of bees no matter the type

**Comment by Prometheus0000** [comment]
This is because they're the same thing with different NBT I believe.

**Comment by Alastors** [comment]
Is there a way to fix it?

**Comment by Prometheus0000** [comment]
You'd have to ask mitch. BTW, this also applies to turbines for example.

**Comment by slprime** [comment]
https://github.com/GTNewHorizons/NotEnoughItems/issues/30 it some issue?
