### ISSUE TITLE
Change the Sigil of Holding's Thaumonomicon entry

### ISSUE THREAD

**Issue by Lonzo34** [GTNewHorizons/GT-New-Horizons-Modpack#7525]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Shift-right-clicked the sigil of holding, expected sigil on hotbar to get shlurped. (As per the thaumonomicon)

![Thaumonomicon page](https://user-images.githubusercontent.com/79593572/109035912-f21e6580-767d-11eb-9171-9ee73073cc80.png)
#
#### What happened instead? (Attach screenshots if needed)
Gui opened where I can place/remove sigils

![Actual GUI](https://user-images.githubusercontent.com/79593572/109035911-f21e6580-767d-11eb-9794-7643c39fe234.png)

#
#### What do you suggest instead/what changes do you propose?
Changing the text on the page to accurately reflect how this sigil functions.

- Shift-right-click opens gui to place/remove sigils
- Shift-scrollwheel cycles through sigil slots (Including empty ones)
- Right-click activates/deactivates selected sigil

I get that the text was copy-pasted from the wiki, but for some reason the wiki is wrong.

**Comment by GTNH-Afx237v7** [comment]
On mobile now, text is found here:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/27dfbdc74dddffd0c71b9f97f65e84dc400fd331/scripts/Blood-Magic-Thaumcraft.zs#L657

**Comment by Lonzo34** [comment]
Here's some replacement text, to make it easy.

"The Sigil of Holding is a tool added by Blood Magic. The Sigil of Holding is used to save inventory space by combining several sigils into a single one. When used, the Sigil of Holding will open a gui on sneak-right click, where sigils may be placed into and removed from the Sigil of Holding. Sneaking and using the scrollwheel will cycle between the stored sigils, while right clicking will activate the displayed sigil."

**Comment by Lonzo34** [comment]
Didn't think to check before, but the Sigil of Augmented Holding is in the same boat. Works identically to the Sigil of Holding, has the same wrong description of operation.

Text is here

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/27dfbdc74dddffd0c71b9f97f65e84dc400fd331/scripts/Blood-Magic-Thaumcraft.zs#L672
