### ISSUE TITLE
The pump thing still

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7527]
#### Which modpack version are you using?
2.1.0.3
#
#### If in multiplayer; On which server does this happen? 
Mine
#
#### What did you try to do, and what did you expect to happen?
NOPE NOPE NOPE YOU ARENT GETTING IT, it autoretracts for no reason when it runs out of pipes!
#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by boubou19** [comment]
uh? can you be a bit more specific? also, can you link to any previous issues showing that we don't get it?

**Comment by Prometheus0000** [comment]
Don't make a new issue for the same thing you just made an issue for (#7526) if you don't like the response.
