### ISSUE TITLE
Nerf the long distance pipeline input/output block recipes

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7528]
#### Which modpack version are you using?
2.1.0.3
#
#### If in multiplayer; On which server does this happen? 
Mine
#
#### What do you suggest instead/what changes do you propose?

The recipes for the pipes themselves shouldnt be upped, its long distance for a reason so it should be relatively cheap for what it does but, the sending/receiving block is def too cheap for what it does. I'd suggest upping it to MV with aluminium or even stainless steel since you don't need much for it. (Aluminium would prob be a better fit for it tbh), It is kind of an op block for steam/lv tbh

**Comment by Glease** [comment]
It's meant to be used to transport oil at LV tier. Push it up the tier is most likely not going to be accepted. It's eventually up to dream to decide, but he is busy now so this might need to wait.

**Comment by mitchej123** [comment]
Like glease said, it's meant to be LV long distance transport, specifically for oil.

**Comment by Alastors** [comment]
yeah that was kind of why I suggested pushing it up just like a tier to requiring at least a lil aluminium but I get the sentiment. the recipe does seem a little inexpensive for what it does though

**Comment by mitchej123** [comment]
It saves significant server resources by only requiring the two end chunks to be loaded.

**Comment by Dream-Master** [comment]
@Alastors what recipe you suggest. Make a more specific suggestion.

**Comment by Alastors** [comment]
Aluminium gears or plates instead of the gears/plates respectively so it would push the tier back just ever so slightly without making it mid mv before you can really get your hands on enough to make it. It would fit around the area where you are most likely going to be able to drop enough steel on the pipeline but also make it a most useful improvement on earlier stages early oil set ups about like the mv electrolyzer and mv extruder are for mv, or like how the ebf and wiremill are for lv, or etc.

so Im proposing 4 aluminium gears, 2 steel plates, and 2 huge steel pipes with a wrench or 4 steel gears, 2 aluminium plates, and 2 huge steel pipe for the first craftable one and 1 steel/aluminum gear, 3 steel/aluminium plate, and the 1 huge steel pipe in the assembler, I also dont understand the tin in the assembler recipe? Is it for soldering? Idk @Dream-Master

**Comment by Dream-Master** [comment]
I am against aluminium. I need the oil in lv.

**Comment by Glease** [comment]
So basically this wouldn't happen?

**Comment by Dream-Master** [comment]
About the amount we can discuss but it stay at steel level.
