### ISSUE TITLE
Change the long distance pipe textures to something more aesthetic than blue blocks with the gt texture

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7529]
#### Which modpack version are you using?
2.1.0.3
#
#### What happened instead? (Attach screenshots if needed)
<img width="1155" alt="Screen Shot 2021-02-24 at 5 38 58 PM" src="https://user-images.githubusercontent.com/78517796/109081757-61b94280-76c8-11eb-90bf-1727af2ea2a5.png">
<img width="1240" alt="Screen Shot 2021-02-24 at 5 35 52 PM" src="https://user-images.githubusercontent.com/78517796/109081768-65e56000-76c8-11eb-84d2-165f76ae20d2.png">

#
#### What do you suggest instead/what changes do you propose?
I suggest maybe taking ie's texture for pipes for this one so it looks a little bit nicer, the blue blocks are thought as pretty ugly tbh, not just by myself but many others on the discord.

I looked at the IE license and it seems like it would be fine as long as yall ask first

What you can do:
- Look at the code, draw inspiration, copy bits of it to use in your own projects
- Fork this repository and modify its code
- Submit Pull Requests to this repository
- Write other projects that base on this project and its API (if present) (This means Addons are totally cool)

What you can not do:
- Claim any of this code to be your property
- Redistribute this project (source or compiled) without explicit permission of the license holder, BluSunrize
- Copy large sections of this code (classes, complex methods) without giving credit
- Monetize any of this project. This means selling the code, compiled projects and also forbids the use of paywalls or "donations" to restrict access to any part of the project's content. I specifically exempt CurseForge's "Points"-system from this statement.
On the topic of resources:
- Always give credit to original artists/creators
- Always ask for permission before copying assets
- Addon mods are allowed to use and remix art & model assets for the sole purpose of being addons. When in doubt, better ask.
For any questions on this license, go poke me on twitter, @BluSunrize

obvi it doesnt have to be ie but the texture is drop dead ugly for the item

**Comment by BluSunrize** [comment]
Modpacks aren't addons.
But thanks for the ping =P

**Comment by Elisis** [comment]
> Modpacks aren't addons.
> But thanks for the ping =P

Well, this one may as well be given the number of forks 😛

**Comment by KiloJoel** [comment]
If it's at all doable, I'd love for them to also have a smaller than full block hitbox/model. It would make compact setups using them look like less of a mess and be easier to access.

**Comment by Dream-Master** [comment]
@Alastors feel free to add some texture. I just add some texture and 2.1.0.3 is dev so hope before the next release we have a final texture.

**Comment by BluSunrize** [comment]
> 
> 
> > Modpacks aren't addons.
> > But thanks for the ping =P
> 
> Well, this one may as well be given the number of forks going on 😛

As far as I can tell, IE isn't even in this pack, so no, you can't use the texture =P

**Comment by Alastors** [comment]
@Dream-Master I can try tbh I have a four day weekend that starts tonight but we will see
@BluSunrize sorry didnt mean to ping you but thank you for the response anyway! <3

**Comment by Elisis** [comment]
> If it's at all doable, I'd love for them to also have a smaller than full block hitbox/model. It would make compact setups using them look like less of a mess and be easier to access.

Afaik, this would necessitate making the pipeline blocks tile entities, which kinda defeats the purpose of having them

**Comment by KiloJoel** [comment]
> 
> Afaik, this would necessitate making the pipeline blocks tile entities, which kinda defeats the purpose of having them

Would it? My understanding is that as long as it's not a ticking tile entity, then it wouldn't make much difference.

Alternatively maybe the hitbox could be a centred cube which is too wide to fit between 2 adjacent ones.

**Comment by leagris** [comment]
You don't need a tile to have a model adapt its shape or texture based on connections. See the working of fences, glass panes for dumb blocks (no tile) changing shape and texture based on surrounding blocks.

**Comment by Ydrec** [comment]
> You don't need a tile to have a model adapt its shape or texture based on connections. See the working of fences, glass panes for dumb blocks (no tile) changing shape and texture based on surrounding blocks.

Making a custom model for a dumb block is possible, but the logic of connecting youre referring to is inapplicable to long distance pipes, as its based on changing metadata, which gt completly uses up. 

That said, there is already a known way to solve the textures not rotating/connecting problem. Its to use the connected textures chisel based on. Devs are busy doing other things, so just waiting until somebody makes a pull with itegrates CTM into these pipes.

**Comment by leagris** [comment]
> Making a custom model for a dumb block is possible, but the logic of connecting youre referring to is inapplicable to long distance pipes, as its based on changing metadata, which gt completly uses up.

No need for metadata as the connected model does not need a world persistent state but only check client-side neighbour blocks.

> That said, there is already a known way to solve the textures not rotating/connecting problem. Its to use the connected textures chisel based on. Devs are busy doing other things, so just waiting until somebody makes a pull with itegrates CTM into these pipes.

No need for CTM, although CTM effectively helps writing the connected texture logic into a JSON ctm file and everything is handled into a library.
