### ISSUE TITLE
Unable to input power to advanced Inscriber

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7532]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
multi
#
#### What did you try to do, and what did you expect to happen?
Connectted advanced Inscriber
#
#### What happened instead? (Attach screenshots if needed)
Unable to input power to advanced Inscriber
#
#### What do you suggest instead/what changes do you propose?
Fix it.
I found out that this bug has existed for a long time.(https://www.reddit.com/r/projectozone2/comments/5hs62y/how_do_i_connect_power_to_the_advanced_inscriber/)

**Comment by Prometheus0000** [comment]
Just power it through the network? Like the link says?

**Comment by yukieiji** [comment]
Both

**Comment by Prometheus0000** [comment]
What? Just do what the post you linked says?

**Comment by repo-alt** [comment]
Not all AE blocks accept any power, and it is kinda intentional.

**Comment by yukieiji** [comment]
> What? Just do what the post you linked says?

Sorry, I read that wrong.
Even if you connect to the network normally, there are times when it doesn't accept energy.

>Not all AE blocks accept any power, and it is kinda intentional.

Even when I reconnect from the network, it doesn't accept any energy...

**Comment by repo-alt** [comment]
Can it be easily reproduced? Have you enough dense energy cells to handle power fluctuations? (power reserve for like 1 second)

**Comment by Prometheus0000** [comment]
Also, does your server use thermos?

**Comment by yukieiji** [comment]
It's not easy to reproduce, but a similar issue occurred in a single I did before
The Network is powered by a creative energy cell, but it's not accepted.
![2021-02-25_23 23 07](https://user-images.githubusercontent.com/40425798/109166864-809b0000-77c0-11eb-8bf0-a7715dddfd70.png)

**Comment by yukieiji** [comment]
@repo-alt  I've succeeded in reproducing it.
You can reproduce it by setting up as shown in the screenshot.
In this setup, the AE2 Inscriber works, but the advanced Inscriber does not.
![2021-02-25_23 32 55](https://user-images.githubusercontent.com/40425798/109168356-12efd380-77c2-11eb-8e90-9e12ac5242eb.png)

**Comment by repo-alt** [comment]
Advanced inscriber does not accept energy while sleeping.
When you put ingredients in, then it requests energy.

**Comment by yukieiji** [comment]
![Uploading 2021-02-26_01.18.26.png…]()

**Comment by yukieiji** [comment]
![2021-02-26_01 18 26](https://user-images.githubusercontent.com/40425798/109182886-be078980-77d0-11eb-9a25-0668d7a11e59.png)

**Comment by repo-alt** [comment]
Yes, there is a bug in ae2stuff

**Comment by repo-alt** [comment]
I fixed the bug but now we need to fork the mod, fix gradle, add to jenkins, etc.
