### ISSUE TITLE
Faucet pouring liquids causing FPS drop.

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#7535]
#### Which modpack version are you using?
2.1.0.3a
#
#### If in multiplayer; On which server does this happen? 
local

Tried pouring liquids from smeltery to casting table/basin and from tank to tank. Faucet is causing FPS drop. Even while not looking at it.

**Comment by boubou19** [comment]
can you install opis and run a client profiling while pooring the fluid? it will tell more accurately what eats your fps

**Comment by Impos913** [comment]
Is opis client-side?

**Comment by Impos913** [comment]
Also where can I get opis?

**Comment by boubou19** [comment]
Opis is needed server side and client side for each player wanting to profile the things. You need a slightly modified version of opis if you run on thermos. The default version of Opis can be found on curse (you need mobius core as well)
