### ISSUE TITLE
Compressed solar panel tooltip is wrong

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7536]
#### Which modpack version are you using?
2.1.0.0

#
#### What did you try to do, and what did you expect to happen?
I connected a compressed solar panel to a battery buffer via 1x redstone alloy cables.
#
#### What happened instead? (Attach screenshots if needed)
The cables burned.  2x cables work.
#
#### What do you suggest instead/what changes do you propose?
I think the solar panel outputs multiple amps once it's full.  Please correct the tooltip.  And any other solar panel tooltips that might be wrong.

**Comment by KiloJoel** [comment]
Is it this issue? Already fixed if so
https://github.com/GTNewHorizons/Electro-Magic-Tools/pull/20

**Comment by McFrugal** [comment]
It's not an essentia generator, but... maybe?  It has a pipe directly above it, which might count.

**Comment by KiloJoel** [comment]
Yeah, that will count. I fixed the solars and essentia gens in the same thing

**Comment by KiloJoel** [comment]
I actually never made an issue relating to it, so I guess technically it's not a duplicate
