### ISSUE TITLE
Wrong recipe for power pass upgrade cover

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7538]
#### Which modpack version are you using?
GTNH 2.1.0.4
#

I think the recipe of the power pass upgrade cover got swaped with the ender fluid link cover

![image](https://user-images.githubusercontent.com/57050655/109335734-bc86a180-7862-11eb-800f-1afb80b06ffc.png)

**Comment by Prometheus0000** [comment]
@bartimaeusnek

**Comment by Technus** [comment]
@basdxz it also has no can recipe

**Comment by johnch18** [comment]
Kinda unrelated, but what exactly is power pass?
