### ISSUE TITLE
advanced alchemical furnace multiblock crush client

### ISSUE THREAD

**Issue by zgggz** [GTNewHorizons/GT-New-Horizons-Modpack#7539]
#### Which modpack version are you using?
GTNH 2.0.9
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
i go 4 chunks away from alchemical furnace and then go back
#
#### What happened instead? (Attach screenshots if needed)
client crushes
#
#### What do you suggest instead/what changes do you propose?
fix it pls
[crash-2021-02-25_23.21.46-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6051898/crash-2021-02-25_23.21.46-client.txt)
[crash-2021-02-25_22.19.48-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6051899/crash-2021-02-25_22.19.48-client.txt)
[crash-2021-01-24_08.59.07-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6051900/crash-2021-01-24_08.59.07-client.txt)

**Comment by boubou19** [comment]
Can you remove fastcraft and see if it happens?

**Comment by zgggz** [comment]
> Can you remove fastcraft and see if it happens?
I can't understand you.
I never heard about fastcraft.
How to do it?

**Comment by GTNH-Afx237v7** [comment]
Go into your Minecraft folder, there is a folder called `mods`, in it is a file called `fastcraft.jar`. Change the file ending from` .jar` to` .off`. Then launch the pack again and see if the crash happens again.
