### ISSUE TITLE
crafting Squid Backpack crashes game to desktop

### ISSUE THREAD

**Issue by ToastedEggplant** [GTNewHorizons/GT-New-Horizons-Modpack#7541]
#### Which modpack version are you using?

Latest

#
#### What did you try to do, and what did you expect to happen?

Crafting the squid backpack crashed the game to the desktop.

Crash report here: https://pastebin.com/vCnVkfWK

**Comment by boubou19** [comment]
define latest: 2.1.0.0 or 2.1.0.4?

**Comment by ToastedEggplant** [comment]
Touche. 2.1.0.0

**Comment by Prometheus0000** [comment]
Should be fixed with #7299, try actual latest.
