### ISSUE TITLE
Mirrored glass recipe requires too many clicks

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7544]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/17787093/109397239-af82b480-792d-11eb-870c-263ab76f0cba.png)
This is the recipe. Each bucket has to be clicked into the grid manually, they don't stack, and significant amounts of mirrored glass is required in some cases. It's a thaumcraft recipe, so autocrafting is not available besides thaumic energistics.

This is very poor accessibility, and an alternative should be provided.
#
#### What do you suggest instead/what changes do you propose?
new/alternative recipe which uses 2 blocks of enderpearl instead of the 4 buckets (costs 18 vs 16, but I couldn't think of a better way)

**Comment by Prometheus0000** [comment]
Why would you need so much mirrored glass?

**Comment by KiloJoel** [comment]
Mirrored jars, mercurial redcrystals, magic mirrors etc.

**Comment by Prometheus0000** [comment]
Why not cells instead?

**Comment by KiloJoel** [comment]
If it's possible to return an empty cell, sure

**Comment by KiloJoel** [comment]
There's no molten ender pearl cell, so it's a question of whether it's possible to do with universal fluid cells

**Comment by Prometheus0000** [comment]
Well, I don't care that much either way, if it's too hard. Being a liquid makes more sense (coating the glass) than blocks to me, that's all.

**Comment by repo-alt** [comment]
I agree that handling the buckets is horrible

**Comment by ScriptedPiky** [comment]
Changing them to Ic2 universal fluid cells would be the best and less horrific to handle in the magical crafting table. However, can those cells be filled in the same instance of the Tinker's Smeltery as you would with the buckets? I'd imagine filling them is the same outcome & case.

**Comment by Prometheus0000** [comment]
So it's a TC fluid? We can change that too, can't we?

**Comment by KiloJoel** [comment]
As far as I can tell, there's 2 fluids, both called "liquid ender". One from gregtech, one from tinkers'
