### ISSUE TITLE
Equipping and trying to use chisel in weapon swap slot crashes the server

### ISSUE THREAD

**Issue by Warlander** [GTNewHorizons/GT-New-Horizons-Modpack#7546]
#### Which modpack version are you using?
2.1.0.0 (newest available)
#
#### If in multiplayer; On which server does this happen? 
Privately hosted server.
#
#### What did you try to do, and what did you expect to happen?
Equipped chisel (ID 5531, craftable and not Tinkers one) in weapons swap slots and tried to use it as a chisel.
#
#### What happened instead? (Attach screenshots if needed)
Server crashed.
#
#### What do you suggest instead/what changes do you propose?
Either default chisel behavior or default chisel behavior should be blocked.

**Comment by boubou19** [comment]
can we have the crashlog so we can trackdown the crash easier please?

**Comment by Warlander** [comment]
Attaching crashlog on the bottom. Exception from server log:

> [23:28:22] [Server thread/ERROR]: Encountered an unexpected exception
> java.lang.ArrayIndexOutOfBoundsException: 150
> 	at team.chisel.inventory.ContainerChisel.onChiselSlotChanged(ContainerChisel.java:144) ~[ContainerChisel.class:?]
> 	at team.chisel.inventory.InventoryChiselSelection.updateItems(InventoryChiselSelection.java:129) ~[InventoryChiselSelection.class:?]
> 	at team.chisel.inventory.ContainerChisel.<init>(ContainerChisel.java:60) ~[ContainerChisel.class:?]
> 	at team.chisel.network.ChiselGuiHandler.getServerGuiElement(ChiselGuiHandler.java:23) ~[ChiselGuiHandler.class:?]
> 	at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243) ~[NetworkRegistry.class:?]
> 	at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75) ~[FMLNetworkHandler.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.openGui(Unknown Source) ~[yz.class:?]
> 	at team.chisel.item.chisel.ChiselController$GuiOpen.run(ChiselController.java:48) ~[ChiselController$GuiOpen.class:?]
> 	at team.chisel.item.chisel.ChiselController.openQueuedGui(ChiselController.java:168) ~[ChiselController.class:?]
> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_373_ChiselController_openQueuedGui_ServerTickEvent.invoke(.dynamic) ~[?:?]
> 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
> 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
> 	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
> 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
> 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

[crash-2021-02-27_23.28.22-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6079886/crash-2021-02-27_23.28.22-server.txt)

**Comment by bombitmanbomb** [comment]
We're also getting this in our private server. Crash error is near identical. Player did the same action as listed above.

[crash-2024-01-09_17.58.20-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13881430/crash-2024-01-09_17.58.20-server.txt)

**Comment by chochem** [comment]
not working on it myself but this seems pretty bad, so reopen.
