### ISSUE TITLE
[Suggestion]Make Fool's Ruby useful in some way or remove it

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7551]
#### Which modpack version are you using?
2.1.0.0

#
#### What do you suggest instead/what changes do you propose?
Currently, there are no useful recipes for FoolsRuby other than lenses, and the large amount of it left over makes useless!
So I propose to make FoolsRuby electrolyzable or removed.
What about the following recipe that requires a larger amount of EU and Dusts to differentiate it from the normal ruby electrolyzing recipe?
・240EU/t 14.4sec 18× FoolsRuby Dust => 1× Chrome Dust + 2× Aluminium Dust + 3000L Oxygen

**Comment by Alastors** [comment]
there are no recipes for it for a reason. it used to be able to be turned into ruby but that got cut so just gonna tell ya man its most likely gonna be a hard pass @yukieiji

**Comment by Prometheus0000** [comment]
The whole point is that it isn't ruby. Do you want iron pyrite to contain gold, too?

**Comment by yukieiji** [comment]
Pyrite is FeS2 with no gold in it, and FoolRuby is CrAl2O3 with aluminum, chromium and oxygen in it. So isn't it wrong to compare them?
If it is not near ruby and is just a item that is nothing, then it is useless and should be deleted to reduce the data, shouldn't it?

**Comment by Prometheus0000** [comment]
You might as well say coal has diamond in it because it's all carbon. If you want to open another ticket about removing it instead that's fine, though that probably belongs in the ticket about removing useless materials in general.

**Comment by yukieiji** [comment]
Since it is a issue of whether to remove FoolsRuby or make it electrolyzable, wouldn't it be clearer to reopen it and change the name and content of this issue slightly?

**Comment by repo-alt** [comment]
As far as I know Fool's Ruby is Spinel, so

**Comment by Prometheus0000** [comment]
https://en.wikipedia.org/wiki/Spinel
Sounds fine changing is so it electrolyzes to that to me. So long as it's not chrome.
