### ISSUE TITLE
Let the Operators have a look up in any protected AE system without having to break the Security Terminal

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7555]
This feature was already discussed in https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/523. It was shot down because it was originally designed to be like that: an Operator must break the security terminal to make an audit. This was done like that in cases some opped players would want to steal from some users.

I personally think it's a poor design, as if you just want to make a random audit, there is no point in breaking the security terminal, because the audited players will be pissed by that.

So my suggestion is to add a way for the admins to be whitelisted in every protected AE system.

**Comment by leagris** [comment]
This is a duplicate of: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/523
I really recommend reading all the comments and the reason it was closed without any implementation.

Now here is my own stance on this although it is really not needed with all the extensive discussion from the AE2 issue above.

You are basically asking for a back-door.
A security system with a back-door is not a security system any-more.
This is the very same issue as state agencies, police asking for back-doors into encrypted systems.

When as a server admin, you cannot trust your server users :
**You have a trust issue** that no amount of backdoors or racing on police-like surveillance can fix.

A backdoor and you as an admin, sneaking into users inventory:
- Will lower your users trust on you as an admin. 
- Will redirect malicious users to the next low hanging abuse target.

**Comment by boubou19** [comment]
as stated in the original issue, there are already ways for the operator to bypass the security station without breaking it: either by disconnecting the security terminal with a focus of dislocation, or if you don't know where it's located, just plug another me security terminal with the focus of dislocation.

For your two points, i would say that:
-  with my change, players actually know that we can access the protected AE systems at anytime. Right now, we abuse the trust of the players because they don't know that.
-  I would not qualify AE to be a low hanging abuse target in GT:NH.

**Comment by 0lafe** [comment]
Anecdotally, we had an admin who would steal from me quite often. He would break my sec terminal though which would break my AE system for me. I would rather he just stole it straight out of the terminals to be honest. I was aware of it either way, but one was kind of annoying to fix so often

**Comment by repo-alt** [comment]
If you don't trust the server admin wtf you are doing on that server. It's not like playing on a server is mandatory and to emigrate you need a dispensation...

**Comment by repo-alt** [comment]
ok, since it happen to be working on the server I'm closing this.
