### ISSUE TITLE
Suggestion: more complex bauxite processing

### ISSUE THREAD

**Issue by septemberWaves** [GTNewHorizons/GT-New-Horizons-Modpack#7556]
Bauxite processing is something which could probably benefit from a more complex processing chain, like how rare earths and platinum-group metals have been expanded upon over the past few updates.

My suggestion is to add a complex bauxite process that involves arc furnaces, cryolite (including artificial production before the ore can be obtained), and sodium hydroxide. The reason I think the added complexity is worthwhile is because aluminium is one of the major resources required in the modpack, and also because I think that requiring the arc furnace for an ore processing chain would be unique and interesting.

As an incentive to undergo the more complex process, increased outputs of aluminium and titanium could be promised, along with extra outputs of byproducts like gallium and zirconium (getting any significant amounts of these could perhaps be gated behind stages of the process). Trace amounts of hafnium and possibly some other trace byproducts of bauxite could also provide some incentive for the more complex process. It could also provide a good reason to build the multiblock arc furnace in the late-game, if large-scale bauxite processing is desired - particularly if the arc furnace recipe is slow.

The outline of how I think such a process _could_ be implemented (without ratios) is as follows:

1: Bauxite ore ==> crushed bauxite (existing pulverizing recipe)
2: Crushed bauxite + sodium hydroxide ==> alkaline bauxite solution (new fluid) - done in a chemical reactor
3: Alkaline bauxite solution ==> magnetite dust + ilmenite dust + impure bauxite dust + silicon dioxide dust + quicklime dust + gallium dust + red mud - done in a centrifuge
4: Impure bauxite dust ==> bauxite dust + tiny grossular dust (existing centrifuge recipe)
5: Bauxite dust + molten cryolite (new fluid) ==> bauxite-cryolite mixture (new item) - done in an electric  blast furnace; bauxite-cryolite mixture will have to be solid to go in the arc furnace, even though it would realistically be molten
6: Bauxite-cryolite mixture ==> aluminium ingot + zirconium dust + processed bauxite residues (new dust) - done in an arc furnace
7: Processed bauxite residues + hydrogen ==> aluminium dust + small zirconium dust + tiny hafnium dust + hydrofluoric acid - done in a centrifuge; should probably take a while due to zirconium-hafnium separation

**Comment by Prometheus0000** [comment]
Why would you want to make the early game even harder? Please make a suggestion for luv+ instead.

**Comment by septemberWaves** [comment]
I think you may misunderstand the purpose of this suggestion. I was not suggesting to remove existing bauxite processing options (besides a possible nerf to their gallium/zirconium output); perhaps the comparison to the rare earth and platinum-group chains wasn't quite accurate to my meaning. The idea is to allow players the option to use more in-depth processing at higher tiers than HV/EV, in order to boost the main output of bauxite and provide some additional secondary products. I don't think it's that much different in principle than the planned milling/flotation recipes for certain ores.

**Comment by Prometheus0000** [comment]
Milling/flotation is GT++, and is not going to happen. Even if alk starts coding again, we'll disable the MBs recipes.

I'm not sure that bauxite produces anything valuable enough to warrant an optional chain anyway. Zirconium is easily acquired from zircon on ross (T3 rocket), and I dunno if hafnium is even used.

**Comment by Ydrec** [comment]
Both alluminium and gallium are plentiful after ev, and that chain doesn't cover the actual main bp of bauxite which is rutile. There is already a 4-5 machine processing to get the most out of bauxite. No need to complexify lower tiers which has an abundance of things to do.
