### ISSUE TITLE
Pyrolyse Oven

### ISSUE THREAD

**Issue by Ritoshisan** [GTNewHorizons/GT-New-Horizons-Modpack#7557]
#### Which modpack version are you using?
2.1.0.4 dev
#
#### If in multiplayer; On which server does this happen? 
sp
#
#### What did you try to do, and what did you expect to happen?
The structure of the furnace does not count the top layer three by three
#
#### What happened instead? (Attach screenshots if needed)

https://user-images.githubusercontent.com/79956710/109819943-5cbf3a80-7c56-11eb-918c-c8621bbef274.mp4

#
#### What do you suggest instead/what changes do you propose?

At the same time, if you put outlets on liquid and objects in the bottom row, then the structure is not assembled. and the top remains empty, as if he does not calculate it, if it is filled as expected with a maffler and he does not consider them a structure as inputs.

**Comment by GeicowithaBango** [comment]
the structure shown is wrong to begin with. thy pyrolyse oven need a roof top that contains a muffler, an input hatch and input bus.

**Comment by Ritoshisan** [comment]
> the structure shown is wrong to begin with. the pyrolyse oven need a top that contains a muffler, an input hatch and input bus.

He does not perceive the top of the structure at all. but as soon as you put the 4th block in the bottom row, then the structure breaks.

https://user-images.githubusercontent.com/79956710/109823373-b117e980-7c59-11eb-8f4d-8379128cdf20.mp4

**Comment by GeicowithaBango** [comment]
ok, thats a major bug then

**Comment by Ritoshisan** [comment]
everything works!

**Comment by vivec55** [comment]
> everything works!

How did you fix it? I am having the same problem.
