### ISSUE TITLE
does not recognize Electric motor (HV) in inventory

### ISSUE THREAD

**Issue by TA0MACHINE** [GTNewHorizons/GT-New-Horizons-Modpack#7559]
#### Which modpack version are you using?
Version 2.1.0.0 23.12.2020
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Drop and take it in inventory again
#
#### What happened instead? (Attach screenshots if needed)
![gdTcnI](https://user-images.githubusercontent.com/42874669/109929581-4d300800-7ccf-11eb-8501-584c145314e4.png)
![YSxsIa](https://user-images.githubusercontent.com/42874669/109929599-53be7f80-7ccf-11eb-9d4c-7c2a5d2edd02.png)

#

**Comment by boubou19** [comment]
try to put the motor in a name remover to remove all the disassembling NBT

**Comment by TA0MACHINE** [comment]
It's works. Thank you

**Comment by boubou19** [comment]
because the disassembling NBT are removed in future version, i'll close this as it will work correctly.
