### ISSUE TITLE
Tesla Tower at LuV and ZPM

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#7561]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
single player

#
#### What did you try to do, and what did you expect to happen?
Tried building an LuV tesla tower, noticed I couldn't extract energy from it cause LuV transceiver is missing
![javaw_8gGT4kefZ3](https://user-images.githubusercontent.com/17811922/109959509-e66b1880-7ce7-11eb-9afe-92822d3424fb.png)

#
#### What do you suggest instead/what changes do you propose?
Add the tesla transceivers for LuV and ZPM power

**Comment by Prometheus0000** [comment]
@basdxz @Technus

**Comment by basdxz** [comment]
Just use Tesla covers (Rich Edition)

**Comment by Sphyix** [comment]
Isn't the cover with half the range compared to the transceiver?

**Comment by basdxz** [comment]
I might add it anyway, would need to re-look into the tiering.

But the range should be non-issue if you use plasma boosting
