### ISSUE TITLE
Tungsten Bee can't breed

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7562]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
multi
#
#### What did you try to do, and what did you expect to happen?
I tried breed dozens of times with three Mutagenic Frames.
#
#### What happened instead? (Attach screenshots if needed)
Didn't mutate.
#
#### What do you suggest instead/what changes do you propose?
Fix it

**Comment by Prometheus0000** [comment]
Can confirm that it doesn't seem to work.

**Comment by luzinsk** [comment]
![image](https://user-images.githubusercontent.com/63211169/123534922-8bbe5800-d6ee-11eb-93ba-a86435a2f8d0.png)
Can be bred in latest release (2.1.1.0)
