### ISSUE TITLE
Covers don't take on the colour of machine they're placed on

### ISSUE THREAD

**Issue by Jimbno** [GTNewHorizons/GT-New-Horizons-Modpack#7563]
#### Which modpack version are you using?
2.1.0.3
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Placed a cover on a machine and expected it to be the same colour as the machine 
#
#### What happened instead? (Attach screenshots if needed)
Cover defaults to gregtech base machine colour
https://imgur.com/a/JfW1Upo
#
#### What do you suggest instead/what changes do you propose?
Covers match the colour of the machine placed on

**Comment by Prometheus0000** [comment]
I don't think it's supposed to? Also, maybe try to highlight the covers, or use an example with covers that are more obvious.

**Comment by Jimbno** [comment]
This happens with every cover I'm just using the computer screen as an example.
https://imgur.com/a/kHY2849

**Comment by leagris** [comment]
1. If you place a cover on a painted stuff, how would the cover get the paint?
2. If you paint a machine blue and place a wood cover that turns blue, that would really look bad and kill the now fixed rendering of soft lighting on GT Tiles to blend your cover with surrounding wood textures.

There would be mean to change the rendering code, so tint does not apply to copied textures but only rendered textures of covers. I'd then wishes that the cover tinting be a client-side only option within Gregtech.cfg in the root directory.

I personally think this would look ugly in most circumstances and can't find a case where this would help or be needed.

If I feel motivated enough to code this option and rendering change, ill look at it, but I place this as very low priority if any priority at all.

**Comment by Prometheus0000** [comment]
BTW, you can't paint a cover, I checked. Maybe add doing that instead?
