### ISSUE TITLE
Remove or Change quest 82 An unexpected Bonus

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#7564]
# Quest 82 An unexpected Bonus
The quest is requiring extremely time consuming under-rewarded uninteresting, unusable at its stage 5x Compressed Charcoal Blocks.

Here is a table of what its requirement actually represent:

| Amount | Designation                                     | Fuel Value per unit | Bonus | Compression Cost EU per unit |
|-------:|:------------------------------------------------|-----------:|-----:|-------------------:|
|      1 | Block of Quintuple Compressed Charcoal          |  944784000 |     0 | 60000000 |
|      9 | Blocks of Quadruple Compressed Charcoal         |  104976000 |     0 |  6000000 |
|     81 | Blocks of Triple Compressed Charcoal         |   11664000 |     0 |   600000 |
|    729 | Blocks of Double Compressed Charcoal            |    1296000 |     0 |    60000 |
|   6561 | Blocks of Compressed Charcoal                   |     144000 |     0 |     6000 |
|  59049 | Blocks of Charcoal                              |      16000 |  1600 |      600 |
| 531441 | Gems of Charcoal                                |       1600 |     0 |        0 |

1 Charcoal of 1600 Burn Value is worth 4000 EU on a 100% efficient power generation.

The Block of Compressed Charcoal already costs more to compress than the bonus gained by forming a block of charcoal \( 6000 EU of compression cost, versus 4000 EU gained from compressing 9 charcoal gems into a Block of Charcoal\).

As-is, this unexpected bonus pitched quest is a lie and a silly time sink farce !

## Proposed changes

- Add worthy rewards
- Add 10% burn-time bonus at each compression level
- Reduce quest requirement to triple compressed

or

- **Remove the quest entirely !**

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/110031882-77042180-7d05-11eb-9987-7c6290168fdc.png)
You wouldn't happen to know how you use charcoal blocks to make steel? You can only use coal blocks in the BBF, and the only other use for C. blocks seems to be boilers or furnaces?

**Comment by leagris** [comment]
The BBF takes only Charcoal Block, not the compressed ones.
The compressed charcoal are only useable into the large boilers and offer not benefit. They even cause a loss due to compression EU cost (not even overclocked compression),  so you will need arrays of LV compressors to keep the burn rate of large boilers. Compressed charcoal blocks as-is are a joke.

**Comment by Prometheus0000** [comment]
...There's two charcoal blocks.
Useless:
![image](https://user-images.githubusercontent.com/8517039/110033183-0fe76c80-7d07-11eb-800e-40a7118c0210.png)
The usable one:
![image](https://user-images.githubusercontent.com/8517039/110033209-170e7a80-7d07-11eb-9b6e-a8773fd3d50d.png)

**Comment by Prometheus0000** [comment]
Also, this is hilarious:
![image](https://user-images.githubusercontent.com/8517039/110033313-3dccb100-7d07-11eb-8b80-032e10d8407b.png)
This is a fusion metal.
