### ISSUE TITLE
suggestion: add a voiding mode for Super/Quantum tanks

### ISSUE THREAD

**Issue by Tedtricks** [GTNewHorizons/GT-New-Horizons-Modpack#7565]
Since Super/Quantum chests can void items on overflow using a screwdriver, why not the tanks as well? This would remove the need of GT++ overflow valves

**Comment by GTNH-Afx237v7** [comment]
Highly appreciated. @Tedtricks suggest you update the issue title as this is not a fix but an additional feature for GT tanks.

**Comment by alphaNOVAircraft** [comment]
Maybe just add it to quantum tanks. There are plenty of ways (that dont require gt++) to have such a voiding. Making everything aviable by default is to simple imo

**Comment by NeroOneTrueKing** [comment]
One -- I'd rather if there was a tierless basic "voiding overflow" cover that was one-size-fits-all: if the tank were to receive more fluid in than it can hold, it voids the excess, and the tank always appears like it can get more fluid added (like a voiding storage drawer).

Two -- I'd like a tiered fluid overflow cover that would do what the original request for the overflow covers would do: https://github.com/alkcorp/GTplusplus/issues/362#issuecomment-417967627. Preferably, it would have a GUI like fluid regulators do.

**Comment by johnch18** [comment]
I really wish there was a simple cover that just voids the excess of whatever it's attached to like how multis do natively. The GT++ overflow valves are really cumbersome to use and IMHO poorly implemented.

**Comment by GTNH-Afx237v7** [comment]
Maybe it just needs its own little quest if it doesn’t already have one.

**Comment by Prometheus0000** [comment]
The OF cover has one, next to the LV assembler.

**Comment by Glease** [comment]
> One -- I'd rather if there was a tierless basic "voiding overflow" cover that was one-size-fits-all: if the tank were to receive more fluid in than it can hold, it voids the excess, and the tank always appears like it can get more fluid added (like a voiding storage drawer).

It's near possible codewise without modifying every addons' machine out there. They need to be aware of this cover and continue to operate despite output tank being full. Some simpler addon machine wouldn't need modifying, but I'd guess lots of them do.

> Two -- I'd like a tiered fluid overflow cover that would do what the original request for the overflow covers would do: [alkcorp/GTplusplus#362 (comment)](https://github.com/alkcorp/GTplusplus/issues/362#issuecomment-417967627). Preferably, it would have a GUI like fluid regulators do.

Basically you want a safety valve. That can be trivially achieved with a dense red crystal, a machine controller, a fluid detector and a pump cover, though admittedly it's quite bulky and sometimes you run out of faces to place the covers. If you, or anyone else interested, can somehow come up with a good texture (item icon and block texture) I can do the coding.

**Comment by Prometheus0000** [comment]
BTW, what would this mean for the TFFT? Completely useless? I'd much rather have a cool multi for this.

**Comment by johnch18** [comment]
Isn't the TFFT notoriously buggy?

**Comment by Prometheus0000** [comment]
Which bot keeps fixing. I'm not sure it has any right now?

**Comment by bombcar** [comment]
https://github.com/GTNewHorizons/GTplusplus/pull/40 May improve the GUI enough for overflow as to make this not necessary.

**Comment by combusterf** [comment]
If we want to stick with GT++, then higher tier overflow valves would be needed as well. The current maximum is IV tier, which has about the same capacity as a Quantum tank 2, so it doesn't make sense to craft higher tier tanks after that if you intend to void excesses.
