### ISSUE TITLE
Arcane lamps break multiblocks 

### ISSUE THREAD

**Issue by Phineasor** [GTNewHorizons/GT-New-Horizons-Modpack#7566]
I am using dev 2.1.0.4

#
I play on a privately hosted server bit does not matter due to the nature of the issue.

#
I logged on expecting my EBF to work.

#
when I logged on to the server, an arcane lamp had added a fake light source to the inside of my EBF causing the structure to be incompleate.

#
I suggest making multiblocks ignore the arcane lamp fake light block, or make it count as air, or make them be a suitable replacement to the air blocks in the multiblock structure like how hatches can be moved arround.

**Comment by GTNH-Afx237v7** [comment]
See also #4856, where this is mentioned (not a duplicate though)
