### ISSUE TITLE
Suggestion: adding Decocraft

### ISSUE THREAD

**Issue by barbarian49** [GTNewHorizons/GT-New-Horizons-Modpack#7567]
I would like to suggest adding the decocraft mod to the pack. This pack contains many different items/props that can be used for making a base look nicer and could be a good complement to the Chisel and Architecturecraft mods. As far as I know, the mod doesn't interact with any other mods so there's less chance for compability issues. It is probably best to have it LV or MV-gated. Lag shouldn't be a problem as long as there are no excessive amounts of items placed around a base.

**Comment by Prometheus0000** [comment]
Duplicatex5. No, for the reasons stated previously.
