### ISSUE TITLE
[AE2] Suggestion: Allow P2P Memory Card to handle multiple entries

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#7568]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Affects both SP and MP
#
#### What did you try to do, and what did you expect to happen?
The AE2 P2P memory card can save an „input“ with shift right click and determine an „output“ with right click. However it can only hold one „input“.
With the recent changes such as fluid P2P
or better handling of GT EU, the P2P tunnels have become more versatile and attractive to use.
#
#### What happened instead? (Attach screenshots if needed)
Either you run around connecting inputs and outputs and clear the memory card every time or you craft a bunch of cards for each input and carry those around. 
#
#### What do you suggest instead/what changes do you propose?
Would it be possible to have a selection option (maybe drop down list) to save multiple „inputs“ in a single card?

**Comment by alphaNOVAircraft** [comment]
Having a Card for one type of liquid seems fine to me. They arent to expensive.

**Comment by repo-alt** [comment]
Just make a bunch of them, seriously

**Comment by GTNH-Afx237v7** [comment]
I will close this, as meanwhile I have made the necessary amount of memory cards.
