### ISSUE TITLE
Naquadah Bee don't produce Naquadah Comb

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7569]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
Single and multi

#
#### What did you try to do, and what did you expect to happen?
I have done dozens of apicultural runs with the following Naquadah Bees.
![2021-03-06_05 43 45](https://user-images.githubusercontent.com/40425798/110171647-61931280-7e3f-11eb-9032-7e7dd7c6576a.png)

#
#### What happened instead? (Attach screenshots if needed)
Naquadah Comb was never produced, even with the Mutagenic Frame.
I have confirmed producing Plutnium Comb(Same probability) with a neater Plutnium bee than that one

#
#### What do you suggest instead/what changes do you propose?
Fix it.
This issue doesn't occur in Gendustry's Industrial Apiary, but in Apiary and Alveary.

**Comment by yukieiji** [comment]
I think it may be failing to check the block, just like the issue I posted before(#7562 ).

**Comment by Prometheus0000** [comment]
1) Kilojoel determined that is seems to have something to do with temp/humidity for the other issue
2) Read the QB/Read the internet/Ask people in discord first
3) It doesn't require a block as far as I know
4) Get it into jubilant state to get the specialty, by getting it to exact temp/humidity req
5) Other people have gotten it

**Comment by yukieiji** [comment]
I'm sorry.
There was a similar problem I posted before (#4736 ).
So I'm closing it.
