### ISSUE TITLE
[RFC] Ceramic Heating Elements 

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#7571]
So i came up with this:

Ceramic Heating Elements (a few tiers, from ULV to IV maybe)

Upsides? -> 
gives perfect OC to LCR, regular heating coils will only allow the recipe to be used, but with *regular* OC instead of *perfect*
EBF, MEBF, MultiSmelter will get 25% Energy Discount & 25% pollution reduction if ceramics are used
Cracker will be 25% faster
Pyrolyse will get 50% pollution reduction

Downsides? ->
LCR won't be perfect OC-able at higher tiers anymore
EBF, MEBF, MultiSmelter will be 12.5% slower with ceramic coils installed
Cracker, Pyrolyse - none

**Comment by alphaNOVAircraft** [comment]
so we wont be able to perfect oc recipes beyon IV in the LCR? 

Energy discount and speed increase seems like a cool mechanic, would reward passive running systems which is always nice imo. 

Do you have any idea already on how to create such coils / how expensive / time consuming they will be compared to normal ones?

**Comment by Yarntheory** [comment]
I do like the idea that you can upgrade your multiblocks besides just replacing the energy hatch (coils do kinda/sorta do that). However this would really depend on cost and difficulty of creating these new blocks. 

I don't think these should be capped out at IV. It almost incentivizes running multiple IV LCRs with the perfect OC, which would increase the server load. I do get that the free OC on LCRs is an issue, but these new heating elements should also scale up to higher tiers as well. The higher tier elements could be restricted somehow, or require a tier or two above to craft (akin to solar panels).

**Comment by Cinobi** [comment]
Half of mod team: Shit, we need to do something to reduce lags at endgame due to shittons of machines needed

bart: loloololol, let's forse ppl place more LCRS!!11

**Comment by Prometheus0000** [comment]
To be fair, there was also mention of a replacement for the LCR you would use/get at ZPM? or so in discord, but _was not mentioned at all in the issue_.

Bart, maybe talk about that? And have that exist before you nerf people's bases for lulz. If people could switch to something else, I think they'd be more ok with it.

That said, optional upgrades to multis sounds like a neat idea. Personally, I'd prefer bonuses rather than tradeoffs though.

**Comment by KiloJoel** [comment]
For the EBF, MEBF and multi smelter, the power and pollution change should probably be more significant, because accounting for the fact that the recipes will take longer, it would only actually be a 15.6% reduction in overall power/pollution for a given recipe

**Comment by redmage17** [comment]
> So i came up with this:
> 
> Ceramic Heating Elements (a few tiers, from ULV to IV maybe)
> 
> Upsides? ->
> gives perfect OC to LCR, regular heating coils will only allow the recipe to be used, but with _regular_ OC instead of _perfect_
> EBF, MEBF, MultiSmelter will get 25% Energy Discount & 25% pollution reduction if ceramics are used
> Cracker will be 25% faster
> Pyrolyse will get 50% pollution reduction
> 
> Downsides? ->
> LCR won't be perfect OC-able at higher tiers anymore
> EBF, MEBF, MultiSmelter will be 12.5% slower with ceramic coils installed
> Cracker, Pyrolyse - none

This I like the idea since it will all for existing lcrs to work, but instead creating a bunch of new recipes for coils and more bloat why not use existing coils?

**Comment by Prometheus0000** [comment]
See #5123

**Comment by johnch18** [comment]
I think LCR overclocking being slightly gated wouldn't be the worst thing in the world. It is pretty broken right now, only having to place a new energy hatch.
