### ISSUE TITLE
[Suggestion] Add a multiblock naquadah reactor

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#7572]
Currently, the only generator for naquadah is the singleblock naquadah reactor, so it would be interesting if a multiblock naquadah reactor is added.

The MAR(short for multiblock naquadah reactor) consumes molten naquadria/enriched naquadah.

Basic output:
1mb molten enriched naquadah can generate 32768eu/t for 60s.
1mb molten naquadria can generate 524288eu/t for 15s.

MAR consumes liquid air 120mb/t when working. If the liquid air is used up, it will keep consuming the fuel without generating energy.

Boost:
1. Supplied with molten caesium 288mb per second, doubled the output voltage.
2. Supplied with molten uranium-238 288mb or uranium-235 72mb per second, tripled the output voltage.
3. Supplied with molten naquadah 18mb per second, quadruple the output voltage.
5. Supplied with coolant 50mb per tick, improve fuel efficiency to 105%.
6. Supplied with super coolant 50mb per tick, improve fuel efficiency to 150%.
7. Supplied with cryotheum 50mb per tick, improve fuel efficiency to 275%.

And the singleblock naquadah reactor should be nerfed slightly(?)

**Comment by alphaNOVAircraft** [comment]
Singleblock naquadah gens are fine imo. They are comparably quite expensive and are need if you need a compact energy source in a tier below your current one. 

Having a multiblock naq reqactor would be cool and maybe a nice alternative for powergen in luv / zpm instead of helium plasma.

**Comment by GlodBlock** [comment]
well, I have made a multiblock naquadah reactor by myself
[https://github.com/GlodBlock/GoodGenerator](url)

**Comment by GlodBlock** [comment]
the running multiblock naquadah reactor
![2021-04-14_23 29 10](https://user-images.githubusercontent.com/60341015/114738239-5f936c00-9d7a-11eb-8056-8e75d760fbb5.png)
(the display looks a little weird)

**Comment by mitchej123** [comment]
Mind adding a license?

**Comment by GTNH-Colen** [comment]
This would be quite a large nerf to naquadria, currently an ingot is 2.5B EU iirc. At base this would give it 157,286,400 EU, with the best efficiency upgrade that's 432,537,600 EU or a ~5.8x nerf.

**Comment by GlodBlock** [comment]
> This would be quite a large nerf to naquadria, currently an ingot is 2.5B EU iirc. At base this would give it 157,286,400 EU, with the best efficiency upgrade that's 432,537,600 EU or a ~5.8x nerf.

yeah,but it can generate energy much more quickly than the normal single block generator.

and i want to add a ture "naquadah fuel" to replace the molten one, which has more energy than the molten naquadah.

**Comment by GlodBlock** [comment]
> Mind adding a license?

i will do it later

**Comment by Glease** [comment]
Regarding naquadah based fuel, there were some prior discussion in #6635. I thought @0lafe should have worked on this subject before as well.

**Comment by GTNH-Colen** [comment]
> (it is every 1mb naquadria generates 157,286,400eu)

Oh my bad, then this is a huge buff? 157,286,400*144 = 22B EU, with best efficiency that's 62B EU?

**Comment by GlodBlock** [comment]
> Regarding naquadah based fuel, there were some prior discussion in #6635. I thought @0lafe should have worked on this subject before as well.

he just wants to make the naquadah more difficult to get.

**Comment by GlodBlock** [comment]
> Oh my bad, then this is a huge buff? 157,286,400*144 = 22B EU, with best efficiency that's 62B EU?

s*it,maybe i made a mistake in calculation.i am not mean to do it

**Comment by 0lafe** [comment]
what type of power outputs does this do?

**Comment by GlodBlock** [comment]
> what type of power outputs does this do?

eu.

**Comment by 0lafe** [comment]
lol i more meant like how much power, like 1A LuV? 12A zpm?

**Comment by GlodBlock** [comment]
> lol i more meant like how much power, like 1A LuV? 12A zpm?

2.75A uhv with the highest efficiency.
it only accept one dynamo hatch

**Comment by GTNH-Colen** [comment]
> > lol i more meant like how much power, like 1A LuV? 12A zpm?
> 
> 2.75A uhv with the highest efficiency.
> it only accept one dynamo hatch

Based on the way the original post was put shouldn't it be 1A UV, with cryo it has a higher fuel efficiency so that it lasts longer. Or did you mean for that to imply that it gives out 2.75A UV in the same time instead? Unsure where you got 2.75UHV from as that's 5.7m eu/t? Probably just language barriers 😜

**Comment by GeicowithaBango** [comment]
1mb molten enriched naquadria can generate 524288eu/t for 15s

are you positive that you mean enriched naquadria? very nice if so

im glad for a new naq multi generator, but theres something that seems spanish to me. 
i think it would be more characteristic if the energy output would come from a defined point, like the single blocks that emit only to sideways (relatively from the face). No but thingy overall nice work 🙌 PogPogPog

**Comment by GlodBlock** [comment]
yeah, the 2.75a uhv is unbalanced, but it is the highest output currently.
maybe i should nerf it to uv.

**Comment by GlodBlock** [comment]
> 1mb molten enriched naquadria can generate 524288eu/t for 15s
> 
> are you positive that you mean enriched naquadria? very nice if so

sorry, that's a typo.i mean naquadria in fact.

>i think it would be more characteristic if the energy output would come from a defined point.

i think it maybe a nice idea

**Comment by GeicowithaBango** [comment]
1mb molten enriched naquadria can generate 524288eu/t for 15s

are you positive that you mean enriched naquadria? very nice if so
sorry, that's a typo.i mean naquadria in fact.

Enriched Naquadria would also be a very nice fuel to use, it has quite some chemistry chain. iirc its in the gtnh core mod

**Comment by johnch18** [comment]
We need a semi decent way to get naquadria beyond processing enriched naquadah ore and the deep dark though

**Comment by GlodBlock** [comment]
the license has been added.
i also balanced it and fixed some bugs.

**Comment by Dream-Master** [comment]
we will add good generator next zeta update. Same for hydro energy.
