### ISSUE TITLE
[2.1.0.4] Fluid regulators are broken

### ISSUE THREAD

**Issue by Auge103** [GTNewHorizons/GT-New-Horizons-Modpack#7576]
#### Which modpack version are you using?
GT:NH 2.1.0.4
#
#### If in multiplayer; On which server does this happen? 
Singleplayer & self-hosted multiplayer
#
#### What did you try to do, and what did you expect to happen?
I just upgraded my version from 2.1.0.0 to 2.1.0.4.
Had a few fluid regulators attached to output hatches on my large heat exchanger.
The fluid regulators should regulate the fluid [doh!].
#
#### What happened instead? (Attach screenshots if needed)
The fluid regulators did NOT regulate the fluid. Instead, there was no fluid flow at all as long as one was attached.
Also, the fluid regulators LV -> IV don't have an inventory icon anymore.
#
#### What do you suggest instead/what changes do you propose?
Make the fluid regulators flow again

**Comment by Prometheus0000** [comment]
Probably the same as #7523

**Comment by Auge103** [comment]
Fixed in dev https://github.com/GTNewHorizons/GT5-Unofficial/pull/447
