### ISSUE TITLE
[Suggestion] Renaming GT's Growth Medium

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7577]
#### Which modpack version are you using?
2.1.0.0

#
#### What do you suggest instead/what changes do you propose?
GTNH's Growth Medium is very confusing, as there is one from Binnes Mod and one from GregTech. In addition, the Bacteria required for GregTech's Growth Medium requires Binne's Growth Medium, further adding to the confusion.
So I suggest that rename GregTech's Growth Medium.

**Comment by Glease** [comment]
But rename to what?

**Comment by johnch18** [comment]
Forced Evolution Virus. Everybody likes a good fallout reference.

**Comment by yukieiji** [comment]
How about this?(For clarity, Bio Medium has been renamed in the same way)
Raw Growth Medium -> Growth Catalyst Medium(Inactive)
Sterilized Growth Medium -> Growth Catalyst Medium
Raw Bio Medium -> Bio Catalyst Medium(Inactive)
Sterilized Bio Medium -> Bio Catalyst Medium
