### ISSUE TITLE
Slab/Panel/Cover made by light source block causes terrible lag

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7578]
#### Which modpack version are you using?
2.0.9.0 - 2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
multi
#
#### What did you try to do, and what did you expect to happen?
Built a base using  GlowStone and Inverted White Lamp Slab/Panel/Cover.
#
#### What happened instead? (Attach screenshots if needed)
TPS has dropped significantly.
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Prometheus0000** [comment]
Is that from railcraft or project red or what?

**Comment by mitchej123** [comment]
Can you run visualvm and produce a sampling report that shows the lag in your base?

**Comment by yukieiji** [comment]
@mitchej123 The TPS dropped to 11 on a server that was always 20, and upon investigation, I found that before the TPS dropped, I had placed a light source carver such as the Inverted White Lamp.

・Normal
![VM1 Normal](https://user-images.githubusercontent.com/40425798/110256033-05b0c100-7fda-11eb-83c4-8829ca58306b.PNG)
・Base
![VM1 base](https://user-images.githubusercontent.com/40425798/110256056-24af5300-7fda-11eb-84fd-f2894b9e9002.PNG)

**Comment by yukieiji** [comment]
@Prometheus0000 ProjectRed

**Comment by KiloJoel** [comment]
Are you able to post the full file?

**Comment by boubou19** [comment]
what does crucible that justifies its 110ms of tick time? Can you try it on a plain forge server and see if it happens too? Could be a crucible issue.

**Comment by Glease** [comment]
[Poke crucible developers over this](https://github.com/CrucibleMC/Crucible/issues/new/choose) if this is the only source of unusual lag.

**Comment by yukieiji** [comment]
This issue also occurred with the Thermos server, so it is unlikely to be specific to Crucible.

**Comment by boubou19** [comment]
then provide the full dump made by visualvm, and try to load your map with base forge server, just to be sure it's not specific to some custom server types.

**Comment by yukieiji** [comment]
Is this okay?
[ForgeNormal.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6098147/ForgeNormal.zip)

**Comment by Glease** [comment]
Top lagger is GC arclamp. it takes 13% of tick time even when it only activates once per 5 second. I'm not quite sure what's the role of PR here. It could be pure coincidence. Maybe check if your new blocks somehow create a redstone circuit and it's now fliping your arclamp on and off in rapid succession.

**Comment by yukieiji** [comment]
There is places where there are a lot of GC ArcLamps placed, so that's probably the cause (but there should be no change in TPS after placement)
