### ISSUE TITLE
Recipe Grouping In NEI

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#7579]
👏🏻ＢΛ - ЯＴ👏🏻|борода|bartworks™heute um 19:07 Uhr
can you do a NEI patch
that makes recipes
which are the same
except for the fluid
cycle though like OreDicted stuff?
mitchej123heute um 19:08 Uhr
got an example of one?
👏🏻ＢΛ - ЯＴ👏🏻|борода|bartworks™heute um 19:09 Uhr
Like, the Soldering Alloy, Lead, Tin recipes in the Circuit Assembler
mitchej123heute um 19:09 Uhr
don't they use different amounts?
👏🏻ＢΛ - ЯＴ👏🏻|борода|bartworks™heute um 19:09 Uhr
yes, but its basically the same recipe
mitchej123heute um 19:10 Uhr
I'd have to look, not familiar with that part of it.  That might be in the NEI handler in GT...
if we gave it some hinting, it'd probably be easier
are all 3 of the recipes made at the same time?
👏🏻ＢΛ - ЯＴ👏🏻|борода|bartworks™heute um 19:10 Uhr
basically:
recipe1.input == recipe2.input
recipe1.output == recipe2.output
recipe1.voltage == recipe2.voltage
add to list of "oredicted"
👏🏻ＢΛ - ЯＴ👏🏻|борода|bartworks™heute um 19:10 Uhr
yes
different length tho
mitchej123heute um 19:11 Uhr
I think it'd be easier to flag them at the time of creation, than to run heuristics later on
or just make a fake nei recipe in place of those 3
:thinking:
👏🏻ＢΛ - ЯＴ👏🏻|борода|bartworks™heute um 19:12 Uhr
same for Helium/Neon/Argon/Kryton/Xeon/Radon
EBF recipes
mitchej123heute um 19:13 Uhr
make a ticket, I think it'd be possible in the GT handler
about to head out hiking
@👏🏻ＢΛ - ЯＴ👏🏻|борода|bartworks™ while you're here though, ignoring the merits of said multi, if Iwanted to make a dust multi using TT multiblock code, which mod would be best to throw that in; or do I follow the pattern of other devs and make MitchMightWorks

**Comment by boubou19** [comment]
How would you know the amount of fluid if you group assembler/ebf recipes? you hover on the fluid input and you see the list of accepted fluids and the amount you need to make the recipe?
