### ISSUE TITLE
Updating This message will only display once.

### ISSUE THREAD

**Issue by deriv** [GTNewHorizons/GT-New-Horizons-Modpack#7581]
I'm using 2.1.0.0 and I'm getting the following one-time notification:
![gtnh_2100_biomesop](https://user-images.githubusercontent.com/19568048/110276936-e5cecc80-7fdc-11eb-8742-4f76a00d30cb.png)
Afaik, by default in server.properties and in wiki, level-type is advised to set it to rwg. If this issue has been already corrected, cool.

**Comment by GTNH-Afx237v7** [comment]
Where is the bug? This is just the notification that the BoP World type can be used, however when you make a new world it defaults to RWG

**Comment by boubou19** [comment]
the world type is enforced to be RWG with the default world generator mod. So you can't change it clientside.
