### ISSUE TITLE
Broken reinforced rails in assembler

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7583]
#### Which modpack version are you using?
2.1.0.4
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Craft reinforced tracks in assembler and then upgrade them into launcher tracks
#
#### What happened instead? (Attach screenshots if needed)
Making reinforced tracks via crafting grid return valid rails that can be used in further crafts, while assembler make unusable tracks.
![image](https://user-images.githubusercontent.com/29033773/110294922-8931d880-8001-11eb-81dc-2eb2a4b8f755.png)
![image](https://user-images.githubusercontent.com/29033773/110294995-a1095c80-8001-11eb-9ac5-32b88c401871.png)

#
#### What do you suggest instead/what changes do you propose?
Fix assembler recipe

**Comment by Prometheus0000** [comment]
Also see #6526. This explains the issue better, assuming it's actually the same thing? @combusterf
