### ISSUE TITLE
Add recycling or downgrading recipes for OpenBlock's "rotating elevator" -> "elevator"

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#7589]
#### Which modpack version are you using?
2.1.0.0 
#
#### What did you try to do, and what did you expect to happen?
Downgrade my rotating elevators into standard elevators. Or recycle them into the aluminum and steel it took to make them.
#
#### What happened instead? (Attach screenshots if needed)
The only thing you can do with a rotating elevator is chembath it to bleach its color.
![image](https://user-images.githubusercontent.com/28197216/110384326-15082c80-8023-11eb-8eda-d94379eb1ae2.png)
#
#### What do you suggest instead/what changes do you propose?
Add a downgrading recipe, and/or a recycling recipe.

Possible downgrade recipe:
Just itself in a crafting table.

Possible recycling recipes:
Elevator: 7 steel 2 aluminum in arc furnace, equivalent quantities in fluid extractor
Rotating elevator: 10 steel 2 aluminum in arc furnace, equivalent quantities in fluid extractor

**Comment by Prometheus0000** [comment]
Completely unnecessary.
