### ISSUE TITLE
Twilight Forest Crash When Near The Naga Courtyard

### ISSUE THREAD

**Issue by NekoLemon** [GTNewHorizons/GT-New-Horizons-Modpack#7591]
#### Which modpack version are you using?
v2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
After killed by Naga, I restore my save by unzip them from backups into saves folder. After that whenever I get close to the naga courtyard, the game crashed.
#
#### What happened instead? (Attach screenshots if needed)
Crash to desktop with a report about ArrayIndexOutOfBoundsException at net.minecraft.block.BlockDoublePlant.func_149888_a.
#
#### What do you suggest instead/what changes do you propose?
Help me fix this problem.
#
#### Logs
https://gist.github.com/NekoLemon/293ed610f3bb0aaa0e2d467be175ca0a

**Comment by GTNH-Afx237v7** [comment]
Did you overwrite the existing files, or delete the folder and unzip ? I suggest you delete the save folder first and then unzip your backup.
Do you have another backup that you can try to see if the same error happens as well?

**Comment by NekoLemon** [comment]
I've thought this situation and have tried it.
I delete my saves and unzip it.
I tried different saves backups but each will crash when get close to naga courtyard.

**Comment by NekoLemon** [comment]
I suspect there is some files changed outside the save directory but I can't find it...

**Comment by GTNH-Afx237v7** [comment]
If  you haven't done much progress in the Twilight Forest yet, you could delete the Dimension Folder (Dimension ID 7, unless you changed it in the config) and try again

**Comment by NekoLemon** [comment]
Alright, I'll try it later
