### ISSUE TITLE
QB not detecting crushed uranium

### ISSUE THREAD

**Issue by Jimbno** [GTNewHorizons/GT-New-Horizons-Modpack#7594]
#### Which modpack version are you using?
Grog toch New Horizons 2.1.0.3
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Complete the pure uranium ores quest in EV after phobos
#
#### What happened instead? (Attach screenshots if needed)
https://imgur.com/a/tPgxjhb
I had crushed uranium 238 in hotbar QB doesn't detect it
#
#### What do you suggest instead/what changes do you propose?
¯\_(ツ)_/¯

**Comment by Prometheus0000** [comment]
User error. You forgot to close this.
