### ISSUE TITLE
You can get space invader coins from space combs

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7595]
#### Which modpack version are you using?
2.1.0.4
#
![image](https://user-images.githubusercontent.com/8517039/110491645-7b428d00-80bf-11eb-941f-a5fc35d0bd6b.png)
Is this intended? @Dream-Master If not, what's supposed to be there?

**Comment by Dream-Master** [comment]
it is intended to got this coins from bees but yes we need to add rocket components for coins.
I just had no time to think about it yet.

**Comment by Prometheus0000** [comment]
I really don't think you should be able to buy rocket components for coins. Making the rocket is supposed to be hard. Though that discussion belongs in the other ticket.

**Comment by Dream-Master** [comment]
if the price is high i see no reson for get components. Maybe one tier below. Sure a new issue need to be open for that.
