### ISSUE TITLE
There's no use for space invader coins

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7596]
#### Which modpack version are you using?
2.1.0.4
#
Please suggest some. Also keep in mind #7595. You can get unlimited coins from bees.

**Comment by NeroOneTrueKing** [comment]
Oxygen tank refill: Consumes an empty oxygen tank and some coins, and gives a full oxygen tank.

**Comment by Prometheus0000** [comment]
BTW, it seems you can buy dragon essence with blue SI coins.

**Comment by dimondmine2** [comment]
If the original space invader coins quest doesn't mention the ability to purchase dragon essence with blue coins, I think it should.
