### ISSUE TITLE
PA for mass fabricators and replicators

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7597]
Right now mass fabricators and replicators cant be placed inside processing array. This leads to large amount of low tier machines (price per block scales up drastically due to field gens) and unnecessary server load. I suggest adding custom logic into PA for handling replicators and mass fabricators.
PA even have 5 yo TODO in its code for machines that arent using recipe maps

**Comment by mitchej123** [comment]
Dupe https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6952
