### ISSUE TITLE
Incomplete structure of EBF MutiSmelter and P-ofen

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#7598]
#### Which modpack version are you using?
2.1.0.4 
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
I used the Tectech tools in the new quest, it showed the strcuture. But after i rebuilt
the EBF and muti-smelter.They still show "incomplete structure"
#
#### What happened instead? (Attach screenshots if needed)
EBF and MutiSmelter still not working.
I think P-ofen the same.
The Vacuum freezer seems ok .distillation tower seems ok and GT++ mutiblock seems ok.
LCR is ok
#
#### What do you suggest instead/what changes do you propose?
Please check the problem

**Comment by Prometheus0000** [comment]
WTF is a P-ofen?

**Comment by KamenriderZO** [comment]
Pyroly ofen

**Comment by interestingusernam3** [comment]
Ofen your entire family for your terrible use od abbreviations.

**Comment by Glease** [comment]
Is this still a problem with 2.1.0.5?
