### ISSUE TITLE
Crash with BQ3

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7599]
#### Which modpack version are you using?
2.1.0.4
#
Occurred when trying to remove a standard item quest reward on the edit rewards screen. It had saved the change when I reloaded the pack/world. It was just a coin, nothing special.
[crash-2021-03-09_11.09.41-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6109842/crash-2021-03-09_11.09.41-client.txt)

**Comment by Prometheus0000** [comment]
BTW, this has happened 2 more times since then. It'd be nice if this was fixed soon. 
[crash-2021-03-10_13.50.05-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6120154/crash-2021-03-10_13.50.05-client.txt)
[crash-2021-03-10_22.03.46-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6120155/crash-2021-03-10_22.03.46-client.txt)

**Comment by Skiftcha** [comment]
you can review & merge/comment
https://github.com/GTNewHorizons/BetterQuesting/pull/28

**Comment by Prometheus0000** [comment]
I saw that, but I'm not good enough at coding to review it, and I don't know how to use git to try it out either.

**Comment by Prometheus0000** [comment]
The PR fixes this, but introduces an even worse problem in that you can't add quests to tabs.

**Comment by Glease** [comment]
> The PR fixes this, but introduces an even worse problem in that you can't add quests to tabs.

Is this still here on latest jenkins build?

**Comment by Prometheus0000** [comment]
Pretty sure, though I stopped using those since I had to choose between crashing or creating quests.

I'll go check.

**Comment by Glease** [comment]
I vaguely remember GTNewHorizons/BetterQuesting#28 was meant to fix this.

**Comment by Prometheus0000** [comment]
Still doesn't allow you to put quests on tabs.

They're created in the database, but you can't put them onto a tab with the designer, or by adding them through the edit page.

**Comment by Dream-Master** [comment]
@SKProCH any idea ?
