### ISSUE TITLE
Tiny dusts in chemical reactor recipes

### ISSUE THREAD

**Issue by Leche-Caliente** [GTNewHorizons/GT-New-Horizons-Modpack#7602]
#### Which modpack version are you using?
2.1.0.3
#
Regarding the current talk about changes to tiny dusts, there are a few chemical reactor recipes that require tiny dusts, and which have no alternative recipe which uses a normal dust.

The two that I know of are 3,3-dichlorobenzidine (a precursor to polybenzimidazole), which requires a tiny copper dust, and biodiesel, which requires a tiny pile of sodium hydroxide.

Clearly it doesn't make sense that an LCR would differentiate between a normal dust and a stack of nine tiny dusts. My suggestion is that alternate recipes should be added for these cases, which take one normal dust instead of a tiny dust as input, and have their time/eu and other input requirements multiplied by nine, in exchange for nine times the current output.

For instance, the 3,3 recipe currently requires 1000L of 2-nitrochlorobenzene and one tiny copper dust for 10 seconds with usage of 1920eu/t and total cost of 384,000eu, and outputs 1000L of 3,3. The new additional recipe would instead require 9000L of 2-nitrochlorobenzene and one normal copper dust for 90 seconds with usage of 1920eu/t and total cost of 3,456,000eu, and would output 9000L of 3,3.

If interested in further reasoning for this change, please see discussion following this comment: https://discordapp.com/channels/181078474394566657/401118216228831252/819126662666125332

Also, it's in the interest of the developers to clean up all instances of this issue at the same time, so if anyone knows of a recipe which requires a tiny dust and has no normal dust alternative, please add it as a comment.
#
#### What is your GTNH Discord username?
Leche Caliente

**Comment by Prometheus0000** [comment]
That's CO2, there's similar CO ones
![image](https://user-images.githubusercontent.com/8517039/110644624-4b5cbd80-8183-11eb-8893-2303c5114da8.png)
That's U-238 and Pu-239
![image](https://user-images.githubusercontent.com/8517039/110644729-64656e80-8183-11eb-9c5f-5a93f0478744.png)
I dunno why this even exists, there's already a full sulfur one
![image](https://user-images.githubusercontent.com/8517039/110644955-95de3a00-8183-11eb-8345-579be9b24fff.png)
I don't think anyone is going to mass-produce these
![image](https://user-images.githubusercontent.com/8517039/110645114-b27a7200-8183-11eb-8c29-fba8cd0f5244.png)
I don't think we're encouraging use of platinum group sludge. Is there a reason for it to still exist?
![image](https://user-images.githubusercontent.com/8517039/110645178-c0c88e00-8183-11eb-83f4-57c74424f063.png)
Part of the platline, platinum residue dust
![image](https://user-images.githubusercontent.com/8517039/110645424-f2d9f000-8183-11eb-8166-00bc8c3d4680.png)
Part of the platline, palladium salt and reprecipitated palladium dust
![image](https://user-images.githubusercontent.com/8517039/110645492-01c0a280-8184-11eb-81b4-8f88d99cd76c.png)
Part of the platline, leach residue dust
![image](https://user-images.githubusercontent.com/8517039/110645808-4ba98880-8184-11eb-98c2-2ae4f4f7dbe8.png)
GT++ recipe, lithium 7
![image](https://user-images.githubusercontent.com/8517039/110645874-5c59fe80-8184-11eb-87df-4c3702618d16.png)
That's sulfur, and the main output is sulfuric apatite. Probably GT++, given it makes the acids which I think are GT++
![image](https://user-images.githubusercontent.com/8517039/110645969-7267bf00-8184-11eb-8707-c84f039fedcd.png)
Ghast tears to saltwater recipe
![image](https://user-images.githubusercontent.com/8517039/110646142-9a572280-8184-11eb-9ca3-95fb156f0360.png)
Bio diesel recipes
![image](https://user-images.githubusercontent.com/8517039/110646209-b0fd7980-8184-11eb-9b87-4f96b73e456e.png)
Polycaprolactam recipe
![image](https://user-images.githubusercontent.com/8517039/110646252-b9ee4b00-8184-11eb-8d6c-a59cc6dc7f21.png)
Part of the platline, platinum salt and reprecipitated platinum dust
![image](https://user-images.githubusercontent.com/8517039/110646978-71835d00-8185-11eb-8919-414ee85552e0.png)
Recipe for raw styrene-butadiene rubber dust. There's another that uses O2 that doesn't leave any partial dusts
![image](https://user-images.githubusercontent.com/8517039/110647195-9e377480-8185-11eb-9462-86aad5777e8a.png)
Indium recipe
![image](https://user-images.githubusercontent.com/8517039/110647415-cf17a980-8185-11eb-9861-60d985e977a5.png)
Phtalic acid recipe
![image](https://user-images.githubusercontent.com/8517039/110647478-dc349880-8185-11eb-8c0f-185f3023b3ce.png)
The already mentioned 3,3-dichlorobenzidine
![image](https://user-images.githubusercontent.com/8517039/110647602-f4a4b300-8185-11eb-8a24-8c9392e611b2.png)
Pico wafer recipe
![image](https://user-images.githubusercontent.com/8517039/110647660-038b6580-8186-11eb-9adb-f301c695a2dc.png)

**Comment by Leche-Caliente** [comment]
Regarding what you said about the rubber de-sulfurization recipe, I don't think that the tiny dust recipes should be removed, just that alternatives should be added. It's easy to imagine for a lot of these that people may not want to use the big recipe when making something by hand.

**Comment by Prometheus0000** [comment]
Eh, I just scrolled through the whole list, it didn't take more than 5-10 minutes.

**Comment by dimondmine2** [comment]
For the first image linked I propose the alternative is using a charcoal block instead of nine charcoal. Happy to receive feedback and let this die if folks make an argument against it.

**Comment by Leche-Caliente** [comment]
There is also the cables recipe with PVC pulp. I'm not in game right now so the details are fuzzy for me at the moment, but it's the recipe that makes cables out of wire, rubber, and small PVC pulp in an assembler --the addition of PVC pulp reduces the amount of rubber required per cable. This isn't a chemical reactor recipe, but I think an updated recipe using one normal pile of PVC pulp should be considered here as well.

**Comment by Prometheus0000** [comment]
There's also a ton of mixer and EBF recipes. Does anyone actually use these?
![image](https://user-images.githubusercontent.com/8517039/111351371-7f3f5380-8659-11eb-9411-315dae0853f3.png)
![image](https://user-images.githubusercontent.com/8517039/111351428-8bc3ac00-8659-11eb-85e7-b1061e828e28.png)

**Comment by Skiftcha** [comment]
for ebf i saw only one possible usage
put 1 and 19 or 14 in single ebf so dust size decides use fluid or no to smelt it
but i do not think somebody really use it

**Comment by Prometheus0000** [comment]
BTW, I was also thinking about removing the recipes that use wrought iron as well as normal iron. In code I believe this is material.anyiron->material.iron, so it includes the magnetized stuff too. In script it's just listed twice, with the second one for WI.

I just can't imagine someone saying, 'hey, I can use normal iron for this, but I'm going to make it into wrought/magnetized iron first, just cuz.' Of course, tools are excluded from this, as they have different stats. This would also make it easier to see recipes where you actually need it, as few as there are.

**Comment by Sunrobbie** [comment]
I've used the wrought iron recipes before, the biggest case has been iron armor/tools from a mob farm. Sometimes in order to use it in recipes it has to be fluid extracted and solidified into normal iron again. This can be avoided by fluid extracting and solidifying the armor/tools instead of arcing it, but I figured I mention it, as it does have a tiny bit of utility early game.

**Comment by Sunrobbie** [comment]
Sorry that was a bit unclear, if you choose to arc furnace the tools and armor as a reprocessing method then it returns wrought iron. If you need normal iron, you would have to convert it using a fluid extractor+solidifier. Obviously, you could just not arc furnace it and process the armor a different way, but it is faster than macerating.

**Comment by Prometheus0000** [comment]
I see. I don't think mob farms are supposed to be the primary way of getting iron, but I'll see what other people say before removing these.
