### ISSUE TITLE
balance void miner weight

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#7603]
in void miner, the between ore in mix have same weight with sporatic ore (1/8), but in worldgen between ore is much larger than 1/8.
in worlldgen, primmary ore and secondary ore have 4 layers and 1 chance, between ore have 5 layers and 0.5 chance, sporatic ore have 9 layers and 1/7 chance. so their weight should be 4:4:2.5:9/7

**Comment by Florexiz** [comment]
No, it have code for doing 1/8 for sporadic and between

**Comment by Florexiz** [comment]
[Here](https://github.com/GTNewHorizons/bartworks/blob/d15a07ea14bce243a9dead8a4511be059749280a/src/main/java/com/github/bartimaeusnek/crossmod/galacticgreg/GT_TileEntity_VoidMiner_Base.java#L231) and few more

**Comment by alphaNOVAircraft** [comment]
Void miners arent balanced by any means. All you basiclly need from the planets when you have a void miner are the small ores. If you change it ppl will just build more miners and void / process more ore they dont need. 

Void miners overall should take a huge nerf imo, but changing that will do nothing good but just more unecessary spam

**Comment by boubou19** [comment]
is it ok if i make a PR with proposed weight changes? Or does it need more discussion?

**Comment by alphaNOVAircraft** [comment]
Like I said. All you are going to change with that is more spam / lag. I propose balancing the miners themselves instead of forcing ppl to spam even more

**Comment by boubou19** [comment]
And what would be your proposal? Because the proposed ratios are closer to the actual worldgen than it is currently. It's a buff for primary and secondary, and it's a nerf for the others. So spam wise, it depends what you are looking for.

**Comment by alphaNOVAircraft** [comment]
I would let it as it is. 
Nearly every time what you are looking for are the rare ores, I don’t think the primary and secondary ore is really an issue on any planets. 
I would prefer the void miner taking a nerf (maybe base speed / higher eu/t usage / requiring field gens that have to be replaced or more or less a nerf of any kind). 
Imo with the current price and running cost of voidminers ppl will tent to just build more of them to get all the rare resources they require (I don’t think anyone runs our of any of the primary ores). And then we just got more spam with even less useful yield

**Comment by Prometheus0000** [comment]
This ticket is about balancing the weight, not balancing the VM. Make another ticket or post on an existing one for that.

**Comment by alphaNOVAircraft** [comment]
> This ticket is about balancing the weight, not balancing the VM. Make another ticket or post on an existing one for that.

I know but I argued for not changing the described behaviour of this issue so I don’t quite get your reaction. 
So do I now need to make a new ticket to argue about changes proposed in a other ticket?!

**Comment by Prometheus0000** [comment]
Perhaps I wasn't phrasing it right, this is a fix to how the VM grabs ores, not a balance change.

In addition, any discussion about VM balancing is likely to not go anywhere, so I'd rather you not halt this from proceeding by bringing up something not related. Discussing field gens or w/e has _nothing to do with ore weight_.

**Comment by alphaNOVAircraft** [comment]
How the hell has it nothing to do with weight changes. 
I already said that changing this will most likely produce more spam

if I think a change would have negative impact i WILL try to halt it. 
Boubs asked what my proposal would be after I argued for not changing the weights, so I did. 

So I am really questioning why I should move into a different ticket so your shit goes through when I explicitly said I disagree with it being a suitable change. 

And I really cannot follow how a vodiminer change is not related to voidminer balance.

**Comment by boubou19** [comment]
I think prometheus wanted to say that the ore weight distribution is another topic than discussing how the void miners should be fundamentally changed to be less OP.

**Comment by alphaNOVAircraft** [comment]
Yes but he also told me not to halt this change even tho I clearly stated that it is my intention to do so. 
And even with more balanced voidminers I would still like to halt it cuz i only see more spam with no improved gameplay by implementing the proposed change.

**Comment by botn365** [comment]
changing weigt distrubution will change almost nothing and think changing it would be wasted efford untill a actual balance patch is done around the void miner
