### ISSUE TITLE
HSS-G ingots quest requires unnecessary IV Mixer

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#7606]
#### Which modpack version are you using?
2.1.0.3

#### If in multiplayer; On which server does this happen? 
n/a

#### What did you try to do, and what did you expect to happen?
In the quest book, in the IV section, the quest for HSS-G ingots has a prerequisite for the IV mixer.

![IV questbook screenshot](https://i.imgur.com/nJRitLX.png)

However, you can mix HSS-G dust by hand.

![HSS-G dust hand mixing recipe](https://i.imgur.com/gAH7cfc.png)

This allows you to create HSS-G coils without ever making an IV mixer. (You still need an IV assembling machine.)

![Completed HSS-G coils quest](https://i.imgur.com/PXvl6bl.png)

This "breaks" quest book progression. A few quests require the ingot quest, rather than the coil quest, so  having the progression broken can cause unnecessary backtracking.

HSS-S dust can also be hand mixed, but the quest book doesn't require the IV mixer as a prerequisite for the HSS-S ingot quest.

#### What do you suggest instead/what changes do you propose?
There's three ways I could see fixing this.

1. Remove the HSS-G dust hand mixing recipe (and probably the HSS-S hand mixing recipe, though it doesn't have a specific progression breaking effect.)
2. Eliminate the HSS-G ingot quest, and in its place, use the HSS-G coil quest as a prerequisite.
3. Eliminate the IV Mixer quest, and put a note in the HSS-G ingot quest that you can hand mix HSS-G dust, or use an IV mixer for a better yield.

#### What is your GTNH Discord username?
querns

**Comment by Prometheus0000** [comment]
I'm not going to account for people using a hand crafting recipe that shouldn't even exist in the first place. You should have to use the mixer to make alloys as soon as you can make it, or at least by MV/HV.

**Comment by querns** [comment]
Yeah, I figured as much. That's why I put "remove the hand mixing recipe" as the first fix option. 😀

**Comment by Dream-Master** [comment]
Guess we need to remove a lot more hand crafting recipe. Everything behind mv
