### ISSUE TITLE
Calcified solar boilers still consume water at the same rate

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7608]
#### Which modpack version are you using?
2.1.0.0

#
#### What did you try to do, and what did you expect to happen?
I waited for my solar boilers to calcify then added fresh ones to compensate, expecting the water usage to be roughly the same.
Why did I do this, you ask?  I want to eventually let my boilers fully calcify so that I don't have to check on them, while still producing enough steam.
#
#### What happened instead? (Attach screenshots if needed)
After the new boilers filled with water, the water tank started losing water over time.  This should have been impossible, as it was slightly overproducing water with the non-calcified boilers, and the new total steam production was slightly less than before.
#
#### What do you suggest instead/what changes do you propose?
Match rate of water use to the steam production rate.  It should always be 150 steam per 1 water; it doesn't make any sense for it to change.
#
#### What is your GTNH Discord username?
McFrugal

**Comment by Pnc6lx** [comment]
in fact, steam: water, is 160:1, not 150: 1, this cause a problem in large boiler and steam turbe

**Comment by McFrugal** [comment]
Are you sure it's 160?  That contradicts every source of information I can find on that.

**Comment by McFrugal** [comment]
Well, I just tested it.  I gave a high pressure solar boiler 100mb of water via a volumetric flask, then stuck a tank next to it and monitored it.  Every burst of steam was 150, and the final amount was 15300.  It looks like there's some bug where it produces extra cycles but it certainly tries to do 150:1.

**Comment by Pnc6lx** [comment]
> Are you sure it's 160? That contradicts every source of information I can find on that.

large heat exchange and steam turbe is 160, large boiler is150

**Comment by Glease** [comment]
The whole boiler code is a mess. I'd like to have a thorough cleanup while fixing this issue. @Dream-Master

**Comment by Dream-Master** [comment]
Sure feel free to make it better @Glease

**Comment by Glease** [comment]
GTNewHorizons/GT5-Unofficial#487

**Comment by ben0sharples** [comment]
This may have been intentional, but I don't think calcification was considered when the production cycle duration was halved. Since calcification occurs every 100 cycles, it's now happening much faster than it used to, and I think possibly by even more than double. 

https://ftb.fandom.com/wiki/Simple_Solar_Boiler says that the calcification process should take 3 and a half hours, but I counted the gap between reductions and it's only 14 seconds. 240 procs of that and you only reach 56 minutes, so unless there were already changes in place to nerf them, it's more than three times faster than it should be.

**Comment by Glease** [comment]
Open a new ticket for it. And before you do so, make sure you are on 2.1.0.7a. There has been several different rounds of changes to it throughout the 2.1.0.x dev releases.

**Comment by ben0sharples** [comment]
Yeah I'm on 7a, will open one.
