### ISSUE TITLE
Fix Fusion Reactor getting stuck when its hatches aren't empty [Feature Request]/[Bug Fix]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7609]
#### Which modpack version are you using?
2.1.0.0

#

#### What did you try to do, and what did you expect to happen?
I tried to automate the production of helium plasma alongside tin plasma depending on demand. I had molten silver going into one hatch, helium-3 into another, and deuterium going into a third.

#
#### What happened instead? (Attach screenshots if needed)
When switching between running the two recipes, if there was any residual deuterium, the tin plasma recipe wouldn't kick off. Likewise, if there was any residual molten silver, the helium plasma recipe wouldn't start.

#
#### What do you suggest instead/what changes do you propose?
Make the fusion reactor able to ignore partial fluid amounts.

**Comment by 0lafe** [comment]
what if you segregate your inputs and don't allow conflicting recipes in at the same time? that seems more reasonable for a lategame+ multi imo

**Comment by johnch18** [comment]
> what if you segregate your inputs and don't allow conflicting recipes in at the same time? that seems more reasonable for a lategame+ multi imo

I already segregate my inputs, the issue is that there is usually always a few liters of residual fluid in the hatches.

**Comment by GeicowithaBango** [comment]
Im afraid thats your problem then.

**Comment by johnch18** [comment]
Such as?

**Comment by 0lafe** [comment]
actually segregating your inputs such that none exist at the same time as each other would work. using inputs that toggle based on fill level of the other fluid using fluid detectors, or other fluid reading items such as OC/SFM. then you can send quantized inputs through OC/SFM/fluid regulators/flasks/cells to get exact recipe quantities ensuring that no left over fluid will exist in the inputs.

**Comment by johnch18** [comment]
That actually sounds kind of fun, I shall try it.
