### ISSUE TITLE
Another BQ3 crash

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7610]
#### Which modpack version are you using?
2.1.0.4
#
[crash-2021-03-11_20.12.11-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6126864/crash-2021-03-11_20.12.11-server.txt)
It crashed when I clicked the done button to finish editing a quest. I'm not sure if it's the same as #7599, but the error looks different.

**Comment by GTNH-Afx237v7** [comment]
Just tested 2.1.0.5
When clicking the small "update" button in the top right corner of the questbook, it resulted in the attached crash.
[crash-2021-04-08_15.16.48-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6278948/crash-2021-04-08_15.16.48-server.txt)
Crashlog is almost identical to the one Prometheus posted.

**Comment by Glease** [comment]
Should be fixed by GTNewHorizons/BetterQuesting#31
