### ISSUE TITLE
UV Transformers Too Expensive [Un-nerf Request]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7611]
#### What do you suggest instead/what changes do you propose?
UV transformers require UHV supes, which in turn require TecTech infrastructure and a UHV Assembler. I think compared to all of the previous tiers, this is a huge jump in complexity. I would suggest changing the recipe to use UHV base supes instead, or adding more UHV cables/wires and using one of those.
If this is intentional gating then I would understand.

**Comment by alphaNOVAircraft** [comment]
They are fine Imo, you should make the TecTech stuff in UV and thats smth forcing you to do so

**Comment by Prometheus0000** [comment]
So what you're saying is, we need to make it require SCs even earlier.

**Comment by alphaNOVAircraft** [comment]
> So what you're saying is, we need to make it require SCs even earlier.

Yes, at least i think that would be a welcome change, a tier x transformer is always tier x+1 to tier x, and if you want to deal with tier + 1 voltage you should be able to provide the SC required

**Comment by johnch18** [comment]
This thread has devolved very quickly IMO. I think X tier transformers being available at tier X is a very good feature. It enables people to use X+1 cables for long distance power transfer. For example, if you were to change the transformers to require superconductors, it would put a large burden on players in the first couple tiers, as lower tier turbines/generators are more efficient and it's better to transform them up.

Making things arbitrarily more difficult is not making things more interesting for players. This seems to be a common misconception among the devs for this pack.

**Comment by Prometheus0000** [comment]
Given that you need to be at the tier to make it (I forgot this) putting SCs of a higher tier in probably isn't a great idea after all. We could put them in on the right side, but that would make it unnecessarily expensive. Making it a base wire until the upper tier wires are redone is probably the best idea, so that you can still upvolt.

> They are fine Imo, you should make the TecTech stuff in UV and thats smth forcing you to do so
It uses UHC SCs, in a UV machine (uses UV hull) but you absolutely can't make UHV SCs until UHV. Well, quest-wise at least, I'm not sure what you can skip.

**Comment by johnch18** [comment]
I would be totally accepting of base wires being used in transformers, it would make sense given that transformers have a small loss.
