### ISSUE TITLE
Remove Boys Gregified from the server list

### ISSUE THREAD

**Issue by jackowski626** [GTNewHorizons/GT-New-Horizons-Modpack#7612]
Sadly the server did not gain in popularity and it was simply not worth to maintain it online.

**Comment by Dream-Master** [comment]
ok

**Comment by boubou19** [comment]
looks like jack's server is not the only one dead: 
![image](https://user-images.githubusercontent.com/12850933/111041782-437a7300-843a-11eb-9636-e2d1be014327.png)

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/117168677-610eed80-ad96-11eb-952b-e9242621d35f.png)
Is the first one here just inaccurate? Otherwise it should be removed too.
Does 'can't connect' also mean it should be removed?

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/commit/2589659720ac938dfeb83f1c481d3a624a90a66c

**Comment by KaneHart** [comment]
We would like to make our new server on the list but we might not have it up exactly the moment when the update comes out. Really depends exactly when it comes out and when we get our world gen done. Should we post the information here or would you rather us wait till the next big update? @Dream-Master

**Comment by Dream-Master** [comment]
@KaneHart make a new ticket please.
