### ISSUE TITLE
Allowing singleblock generators to have top and bottom output sides

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#7614]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
I tried to turn singleblock turbine/combustion generator to output energy out of top or bottom sides
#
#### What happened instead? (Attach screenshots if needed)
Weird, that we can do anything with the wrench and turn any mechanism, but not generators. Sometimes it can be helpful and i got such sutiation several times.
#
#### What do you suggest instead/what changes do you propose?
Every mechanism can have output on every side possible, so why not generators also? Minecraft is sandbox and such restriction does nothing
#
#### What is your GTNH Discord username?
CatsLeftEar

**Comment by CatsLeftEar** [comment]
This would be a great feature, why dont you like it?

**Comment by Autowinto** [comment]
I think it's a good idea as well. I wonder if it's a design choice or if the implementation of generators is so different from regular machines that it's too cumbersome to do.

**Comment by YannickMG** [comment]
I understand that this change would have balance implications in terms of superconductor cable design or cable loss.

Beyond that there's not a clear logical reason this couldn't happen.
