### ISSUE TITLE
TT Oil Cracker

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7616]
#### Which modpack version are you using?
2.1.0.4
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Build Oil Cracker
#
#### What happened instead? (Attach screenshots if needed)
TT Replacement of Oil Cracker have very strict build requirements  that aren't present in regular GT cracker
1) Input hatch can be placed at left side, while output on the right. You can turn cracker upside down, but esthetics... Ugh
2) Side hatches can be only be placed in center block of the side. Prev version example:
![image](https://user-images.githubusercontent.com/29033773/110942440-de941f80-834a-11eb-8448-8e906dc8ac19.png)
Now fluid hatch can be placed only on central block
#
#### What do you suggest instead/what changes do you propose?
Change oil cracker structure so it match GT one
#
#### What is your GTNH Discord username?
FalseColor

**Comment by Florexiz** [comment]
@Ethryan I think its more related to bartworks? Multi replacement to TT code located there

**Comment by bartimaeusnek** [comment]
The multi itself can be rotated/flipped to accommodate for io on left/right side. the 90° angle of the controller to hydrogen/steam input was introduced to limit Wallsharing to 4x instead of endless Wallsharing.

**Comment by Ethryan** [comment]
Will close this then since an answer has been made available.

**Comment by KiloJoel** [comment]
This is even more restrictive than i thought, this seriously needs looking at because it breaks a LOT of current setups, including ones that don't wallshare at all

**Comment by Prometheus0000** [comment]
Bart just doesn't want to merge https://github.com/GTNewHorizons/bartworks/pull/4

I mean, just merge it for now, and then work on preventing wallsharing for all the multis and add the double casing thing discussed before.

Or just merge it for our fork, but not the original repo.

Why should this multi be special?

**Comment by Dream-Master** [comment]
i reopen the issue. So feel free to discuss here.

**Comment by Florexiz** [comment]
Imo there are no reason to remove wall sharing. It was always been here and nobody complain about it afaik. It doesn't change too much in terms of saving resources, when you need more than 1 multi of that type few casings doesn't really matter. I cant remember using wall sharing for saving resources, only for sharing inputs or aesthetics

**Comment by mitchej123** [comment]
I vote we address the wall sharing independent of the Oil Cracker move to TT.  Enable the new oil cracker code with the existing behavior, and start an RFC to discuss potential limitations on wall sharing [of which I'm in favor of].

**Comment by Prometheus0000** [comment]
By 'new oil cracker code with the existing behavior' do you mean bot's PR? Or anything else needed to fix it so it works the same as before the TT change regarding structure check?

**Comment by mitchej123** [comment]
Bots PR + anything else needed to continue with the legacy behavior until we've decided how to address wall sharing.  Not trying to put off the wall sharing discussion, but it should be addressed globally, not on a one off basis.

**Comment by bartimaeusnek** [comment]
If you want legacy behavior, remove the class entirely. But don't just buff another part of the game with no downsides. You're eroding balance, again and i don't like it at all.

**Comment by mitchej123** [comment]
> If you want legacy behavior, remove the class entirely. But don't just buff another part of the game with no downsides. You're eroding balance, again and i don't like it at all.

Or, we merge Bot's PR, and address wall sharing as a separate concern globally instead of with a one off bespoke implementation with a hacky implementation.

**Comment by Prometheus0000** [comment]
The downside is that you have to make higher tiers of coils to get the bonus? That _is_ what you're talking about, right?

**Comment by Florexiz** [comment]
> But don't just buff another part of the game with no downsides.
Leaving things as they are isn't a buff

**Comment by Leche-Caliente** [comment]
When I discovered the oil cracker change, I was also puzzled. When I learned it was done in an effort to curb wall sharing, I was annoyed.

People choosing to make caterpillar oil crackers in their own bases is not my problem. It isn't anyone's problem. Quite frankly, the cult of anti-wall sharing needs to lay off. It was fine when they were just trying to remove it from the game, but now failing that, they've decided to reduce functionality in other areas just to compensate. Now suddenly it is my problem.

The new overly-strict structure requirement for the oil cracker is simply goofy. The phrase "cutting off one's nose to spite one's face" comes to mind.

**Comment by bartimaeusnek** [comment]
> > But don't just buff another part of the game with no downsides.
> 
> Leaving things as they are isn't a buff
> 

Ye that's what I suggested. Remove the buff that's currently active in the zeta release, and remove the harder structure check or keep both. But I won't accept both active at the same time just because mitchej will eventually fix them somewhen in the future, maybe.

**Comment by mitchej123** [comment]
> Ye that's what I suggested. Remove the buff that's currently active in the zeta release, and remove the harder structure check or keep both. But I won't accept both active at the same time just because mitchej will eventually fix them somewhen in the future, maybe.

You are picking a very strange battle here Bart.  Why is the oil cracker, of all things, so out of balance?  Remove the 90 degree requirement and leave it as a TT multi. 


You won't accept both active?  Didn't you say dream has say over this?  Stop trying to force your view on everyone to such an extreme.  I don't even want wall sharing and think this absurd requirement and your unwillingness to budge is ridiculous.


Also stop with the attacks on me.  The wall sharing adjustment should 💯 be addressed separately, regardless of who may or may not do it.

**Comment by basdxz** [comment]
Just fix your setups and move on. The cracker has been buffed and appropriately nerfed, and wall sharing itself is a mechanic that hardly needs addressing. It is the QoL you love so much is it not? 3 multis for the cost of 2 sounds rather convenient to me,

**Comment by mitchej123** [comment]
> Just fix your setups and move on. The cracker has been buffed and appropriately nerfed, and wall sharing itself is a mechanic that hardly needs addressing. It is the QoL you love so much is it not? 3 multis for the cost of 2 sounds rather convenient to me,

My non wall sharing setup has been broken because of this inane fight against wall sharing.  Remove the unnecessary 90 degree requirement and move on.

**Comment by basdxz** [comment]
Changes require setup adjustment all the time, it's hardly a game changing thing for people to have to move a few machines around. Regardless like Bart said, undo the buff to the coils along with the slight structure adjustment.

**Comment by mitchej123** [comment]
How about we update the structure to TT, and move the wall sharing adjustments to a DIFFERENT RFC like was suggested?

**Comment by basdxz** [comment]
@bartimaeusnek Hey can we undo the TT structure all together? I don't see why we really need it here.

**Comment by mitchej123** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7633

**Comment by basdxz** [comment]
sqrt(-1)

**Comment by mitchej123** [comment]
> Changes require setup adjustment all the time, 

Changes for no valid reason other than you and bart want to.  Stop trying to shove stuff through without Dream and others agreeing with them.  "omg so cheap" at a point it doesn't really matter much.

**Comment by Leche-Caliente** [comment]
> > Changes require setup adjustment all the time,
> 
> Changes for no valid reason other than you and bart want to. Stop trying to shove stuff through without Dream and others agreeing with them. "omg so cheap" at a point it doesn't really matter much.

Aye. It's pretty clear at this point that bart and basdxz have a personal vendetta against wall sharing, and they don't care what else they break, so long as they can get their white whale.

And it isn't just about breaking current  setups --although that should be reason enough not to push through this inane change. Oil crackers are just silly now. The inputs have to go from left to right, unless you turn the entire machine upside down? It's like I've been transported back to a time where we didn't know how to make modular multiblocks, and it is a stark comparison to every other multiblock in my base.

**Comment by mitchej123** [comment]
> Aye. It's pretty clear at this point that bart and basdxz have a personal vendetta against wall sharing, and they don't care what else they break, so long as they can get their white whale.
> 
> And it isn't just about breaking current setups --although that should be reason enough not to push through this inane change. Oil crackers are just silly now. The inputs have to go from left to right, unless you turn the entire machine upside down? It's like I've been transported back to a time where we didn't know how to make modular multiblocks, and it is a stark comparison to every other multiblock in my base.

To be 100% clear I'm in favor of removing wall sharing, but not by forcing it in as a dumb requirement to a structure check like you mention.  They should be two separate issues.

**Comment by Leche-Caliente** [comment]
> To be 100% clear I'm in favor of removing wall sharing, but not by forcing it in as a dumb requirement to a structure check like you mention. They should be two separate issues.

Same, I have no issue with wallsharing getting cut, but not these kinds of hacky changes.
