### ISSUE TITLE
Oreberry maceration broken in 2.1.0.4

### ISSUE THREAD

**Issue by rv-jgentile** [GTNewHorizons/GT-New-Horizons-Modpack#7618]
#### Which modpack version are you using?
2.1.0.4
#
#### If in multiplayer; On which server does this happen? 
n/a
#
#### What did you try to do, and what did you expect to happen?
Macerate oreberries, expected the macerator to operate and crush them into tiny piles.
#
#### What happened instead? (Attach screenshots if needed)
The macerator's inventory accepts them but doesn't actually do anything.
![image](https://user-images.githubusercontent.com/5657339/110978405-f490e880-8328-11eb-9379-45198085553d.png)

#
#### What do you suggest instead/what changes do you propose?
Fix oreberry maceration or document the change.
#
#### What is your GTNH Discord username?
aburger

**Comment by Dream-Master** [comment]
ah yes another one i need to fix :)

**Comment by Prometheus0000** [comment]
BTW I looked in the tinkers script file and the coremod and couldn't find the recipe, or it's removal. I wonder if someone changed something in GT related to finding materials?

**Comment by Dream-Master** [comment]
it was a change by mitch or was it bart cant remeber. Make the gt code loads faster and remove some unused compat stuff.
Now we see some compat is gone and i need to readd it manual like ardite and cobalt crushed recipes. Nothing to worry ill take care.

**Comment by rv-jgentile** [comment]
@Dream-Master I dug into this because I was bored and curious about ZenScript, hope you don't mind. PR up @ [PR 7630](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7630). Feel free to reject it - I was just curious if I could get it to work and figured I might as well put up a PR with what I ended up with on local.
