### ISSUE TITLE
Manyullyn gated different two separate tiers (Lv for parts) (Hv for ingots) (you can alloy in a TiC multiblock

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7619]
#### Which modpack version are you using?
2.1.0.4
#
#### If in multiplayer; On which server does this happen? 
Mine I guess
#

#### What do you suggest instead/what changes do you propose?
Below are the six pictures for the references 
<img width="516" alt="Screen Shot 2021-03-12 at 2 04 44 PM" src="https://user-images.githubusercontent.com/78517796/110993077-72aaba80-833c-11eb-9830-aca1105a9738.png">
<img width="527" alt="Screen Shot 2021-03-12 at 2 04 47 PM" src="https://user-images.githubusercontent.com/78517796/110993080-73435100-833c-11eb-8ebc-6ddc8664e297.png">
<img width="511" alt="Screen Shot 2021-03-12 at 1 59 36 PM" src="https://user-images.githubusercontent.com/78517796/110993083-73435100-833c-11eb-8810-34d61fa5e421.png">
<img width="641" alt="Screen Shot 2021-03-12 at 1 59 39 PM" src="https://user-images.githubusercontent.com/78517796/110993084-73dbe780-833c-11eb-9d8a-ec7673edee29.png">
<img width="527" alt="Screen Shot 2021-03-12 at 2 06 01 PM" src="https://user-images.githubusercontent.com/78517796/110993085-73dbe780-833c-11eb-84dd-378d1b585247.png">
<img width="520" alt="Screen Shot 2021-03-12 at 2 06 10 PM" src="https://user-images.githubusercontent.com/78517796/110993086-73dbe780-833c-11eb-94e8-e2c096b581d8.png">

So basically, manyullyn needs either a buff to tier or nerf to tier (Id personally say a buff since it is worse than most materials that are craftable before it (Vanadiumsteel, Damascus steel, even cobalt is a better pickaxe head than manyullyn) and not really useful for much of anything to be honest) Since you can craft manyullyn at two separate points in GTNH, the issue is, you can craft the TiC parts at lv as soon as you get ardite and cobalt right but, you cant make the ingots until you get the vacuum freezer post-cleanroom.
I will attached pictures below of the two different crafting ways but you can still pour manyullyn alloy crafted in the TiC smeltery into molds to make things such as pickaxe heads

So I propose instead switching the manyullyn ingot recipe to not require the vacuum freezer by instead having it be smeltable in the mv energy hatch ebf at latest, such as the hot ingots are now. It would still be worse than most materials at mv tier but at least we could repair any manyullyn tools we made in lv before we make a cleanroom.

I currently have a manyullyn pickaxe head that was made in lv in the TiC multi which was where the issue originally started since ya know, cant repair or swap out until I fix it completely.

#
#### What is your GTNH Discord username?
take a wild guess lmao

**Comment by KiloJoel** [comment]
Heat capacity requirement would also need to be reduced
