### ISSUE TITLE
suggestion- copper foil for PCBs should be in only one of the crafting steps

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7621]
#### Which modpack version are you using?
2.1.0.0

#
#### What did you try to do, and what did you expect to happen?
Making some PCBs
#
#### What happened instead? (Attach screenshots if needed)
It takes more copper than seems reasonable since both types of "plastic circuit board" use it-- both the naked and the wired one.
#
#### What do you suggest instead/what changes do you propose?
Copper foil should only be required for the wired one.  Making a naked board should not require foil.
#
#### What is your GTNH Discord username?
McFrugal

**Comment by Leche-Caliente** [comment]
Seems to me that there are two slightly separate issues here. Do you just have a problem with the quantity of copper required? Or do you also specifically dislike the fact that it is required in two different steps?

**Comment by Prometheus0000** [comment]
I'm gonna say: Too Bad?

**Comment by McFrugal** [comment]
It just seems to me that the recipe for the naked board was made by someone looking up info on how pcbs were made and noticing that they had a copper coating.  So that's reasonable.  Then, someone put in foils for the second step.  Why?  PCBs aren't made that way.  You etch them to remove conductor, you don't put MORE conductor on them.
It's not realistic whatsoever, and the redundancy just looks like the two recipes were made independently, without knowing that the foil had been added already or would be added in the next step.

Oh well, I guess the circuit board recipes just reject realism after a while anyway.  Petri dishes?  Really?
