### ISSUE TITLE
HV Tanks can't be made with other ULV Circuits

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7622]
#### Which modpack version are you using?
2.1.0.0

#
#### What did you try to do, and what did you expect to happen?
I wanted to make an HV tank with NAND chips.

#
#### What happened instead? (Attach screenshots if needed)
The recipe only accepts vacuum tubes

#
#### What do you suggest instead/what changes do you propose?
Change the recipe to use any ULV circuit.

**Comment by Dream-Master** [comment]
HV Tank ? its a GT++ device

**Comment by botn365** [comment]
yes

**Comment by Prometheus0000** [comment]
Wasn't this fixed awhile ago?

**Comment by johnch18** [comment]
Maybe, in 2.1.0.0 at least it's still the case.
