### ISSUE TITLE
Phosphoric acid from apatite chemical reactor recipe has no LCR equivalent

### ISSUE THREAD

**Issue by Leche-Caliente** [GTNewHorizons/GT-New-Horizons-Modpack#7623]
#### Which modpack version are you using?
2.1.0.3
#
![Capture](https://user-images.githubusercontent.com/64061913/111025104-0a3cf700-8397-11eb-91e6-870f11d379dc.PNG)

The pictured recipe (apatite, sulfuric acid, water ---> HCl, Phosphoric acid) has no equivalent in the LCR. I can't imagine that this is intended, and so it should be fixed.

#
#### What is your GTNH Discord username?
Leche Caliente

**Comment by Glease** [comment]
GTNewHorizons/GT5-Unofficial#423

**Comment by Glease** [comment]
Actually, 2.1.0.4 should already have my changes.

**Comment by Leche-Caliente** [comment]
danke
