### ISSUE TITLE
GT battboxes with ME controller could cause Free GTeus

### ISSUE THREAD

**Issue by Hikari1nVoid** [GTNewHorizons/GT-New-Horizons-Modpack#7624]
#### Which modpack version are you using?
2.1.0.3
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Connect the battery output side to ME contoller while provides extra ic2 powersource to the ME controller
#
#### What happened instead? (Attach screenshots if needed)
The batterybox get charged @1meu/t regardless the power provided by that extra power source.EU meter indicates that there is a "negative output" current in the battbox causing this batterybox a infinite power source. 
#
#### What do you suggest instead/what changes do you propose?
Fix this bug ASAP since it breaks the GT EU network(Free energy)
![QQ图片20210314155958](https://user-images.githubusercontent.com/24840795/111061465-7fffaa80-84de-11eb-9a27-bf33f64c5c28.png)

#
#### What is your GTNH Discord username?
Hikari1nVoid

**Comment by Hikari1nVoid** [comment]
Edit:Not only ME controller but any blocks in AE2 that could output energy could trigger this bug.

**Comment by repo-alt** [comment]
I was not able to reproduce that with a battery buffer. Do you mean GT++ energy buffers perhaps?

**Comment by GlodBlock** [comment]
@repo-alt 
you need to put a non-empty battery in the battery buffer to trigger the bug.

**Comment by repo-alt** [comment]
@boubou19 please also transfer that
