### ISSUE TITLE
Alumite recipe oversight

### ISSUE THREAD

**Issue by SirFell** [GTNewHorizons/GT-New-Horizons-Modpack#7628]
#### Which modpack version are you using?
Any upto 2.1.0.4

#
#### If in multiplayer; On which server does this happen? 
Same for both SSP and SMP

#
#### What did you try to do, and what did you expect to happen?
Alumite crafting related oversight. In the smeltery 2 parts of alumite are made by combining 5 parts aluminium to 2 parts steel to 2 parts obsidian.
![image](https://user-images.githubusercontent.com/5310658/111072193-226d5d00-84e2-11eb-8353-747df3f4a2c7.png)

#
#### What happened instead? (Attach screenshots if needed)
When crafted by hand you make 9 parts of alumite (4.5 times more than in the smeltery) with same amount of materials.
![image](https://user-images.githubusercontent.com/5310658/111072230-4f217480-84e2-11eb-89d6-297b0e04306a.png)

#
#### What do you suggest instead/what changes do you propose?
Merge [(CoreMod) #161](https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/161) to equalize both recipes to 5:2:2 makes 2

#
#### What is your GTNH Discord username?
SirFell#1024

**Comment by KiloJoel** [comment]
As far as I'm aware, the dust recipe is intended to be more efficient, which is consistent with other alloy recipes being less efficient in the smeltery. There is also a quest which tell you to use the dust recipe because it's more efficient.

**Comment by KiloJoel** [comment]
This is a major slowdown so I don't think it should be changed lightly. When aluminium gravel is not available, this means 405 aluminium oreberries need to be grown just to make the tool forge. That's a VERY long time spent waiting and I'm not sure we want that.

**Comment by SirFell** [comment]
quest backing up likely unintended feature is not a good proof of intention since quests get rewritten a lot. Previously tool forge took MV to get due to 3 alum screws so i still dont see the point, we made tool forge just fine back then by either waiting or foraging for aluminium ingots

**Comment by SirFell** [comment]
i wouldnt mind if it would be an alloy recipe (read as: require some actual progress rather than a piece of flint and some stone) but its shapeless recipe that can then be just smelted in the furnace

**Comment by SirFell** [comment]
even in alloy furnace it would be way too op, 4.5x more efficient than smeltery recipe is dumb. next PR i will likely look at other recipes so they dont give such insane boosts in efficiency (im looking at you obsidian ingot)

**Comment by KiloJoel** [comment]
So I'm not saying let's not change this at all, but this needs some discussion before making a change, since this has a large impact on current early progression

**Comment by SirFell** [comment]
i believe shaped recipe should stay as in PR. maybe we should add slightly more efficient alloy recipe, say 3 ingots instead of 2 (50% efficiency boost)

**Comment by SirFell** [comment]
and reform other alloy recipes that are replacement for smeltery recipes that give too big of a boos to that amount too.

**Comment by KiloJoel** [comment]
I think that the smeltery recipe is too inefficient for how alumite used in GTNH, and probably shouldn't be used as a baseline for balance in its current state. It's currently a noob trap which wastes aluminium rather than a viable recipe.

I think that the dust mixing recipe should make 6 alumite, and the smeltery recipe should make 4, vs the 9 and 2 currently.

**Comment by Prometheus0000** [comment]
I agree with kilojoel here. Also, the comparison to the tool forge being MV is ludicrous. Why would you prevent people from having hammers for that long? They'd probably just use auto-miners instead, and the hammers wouldn't see use.

> quest backing up likely unintended feature is not a good proof of intention since quests get rewritten a lot
The first half of your sentence is a garbled mess. We aren't talking about backups?

Since I didn't realize the dust recipe existed when I played (which you have now made the same) I never even used alumite tools (aside from maybe my pickaxe, to get the next mining level, which I believe I changed after I repaired it the first time), since they were too expensive. And I had the gravel, too. This indicates that with a recipe that only gives two parts, it's too expensive.

**Comment by SirFell** [comment]
> The first half of your sentence is a garbled mess. We aren't talking about backups?
@Prometheus0000 if you dont know english well enough then at least use google and/or common sense:
![image](https://user-images.githubusercontent.com/5310658/111078870-40e25100-8500-11eb-8e90-e5dc3b618ad6.png)
in my original sentence "backing up" is clearly used as "supporting"

**Comment by Prometheus0000** [comment]
I'm a native english speaker. And I say it doesn't make sense.

> **The** quest**book** backing up **a** likely unintended feature

^ Would make sense.

**Comment by boubou19** [comment]
Guys, either open a new issue for the balancing, or unmerge the https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/161. This issue can't be labeled as RFC if changes are already pushed in code.

**Comment by SirFell** [comment]
**whole questbook backs up a single thing** vs **actual quest inside that questbook that mentions this particular recipe** sure. either way, return fixed in dev tag, commit is merged. I deem this issue closed as its linked PR is merged. Balancing by adding separate recipe should be its own ticket with its own linked PR.

**Comment by boubou19** [comment]
Dream will close it after the release.

**Comment by GTNH-Afx237v7** [comment]
Maybe add an LV mixer recipe that yields 9 dusts if it doesn’t exist already. That would incentivize a tech progression.

**Comment by SirFell** [comment]
continue discussion in #7629 @boubou19 lock this please
