### ISSUE TITLE
Alumite recipe unbalanced

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7629]
As a result of #7628 and https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/161, making alumite is now imbalanced and the PR should either be reverted or the recipe changed in some way that is easier to make alumite. And/or the smeltery recipe too.

**Comment by Prometheus0000** [comment]
@GTNH-Afx237v7 The mixer is too late, you're supposed to get the tool forge before then, in steam. Not that there shouldn't be a third, even more efficient recipe, but I dunno if people would even use it at that point.

**Comment by SirFell** [comment]
making alumite now is more balanced than ever as its 1:1 with the alternatives so title is arguably invalid. To summarize:

@KiloJoel :
> I think that the smeltery recipe is too inefficient for how alumite is used in GTNH, and probably shouldn't be used as a baseline for balance in its current state. It's currently a noob trap which wastes aluminium rather than a viable recipe.
>
>I think that the dust mixing recipe should make 6 alumite, and the smeltery recipe should make 4, vs the 9 and 2 currently.

**Comment by SirFell** [comment]
i personally think manual mixing should stay 1:1 with smeltery while we would add a alloy smelter recipe that makes 3 instead of 2, and maybe LV mixer that makes 4

**Comment by Prometheus0000** [comment]
I didn't specify which recipe, I was trying to be inclusive to both. I'd honestly like the opinion of someone at that stage though.

**Comment by SirFell** [comment]
maybe even make smeltery make 3, alloy make 4 and mixer make 6

**Comment by SirFell** [comment]
suggestion of explanation:

manual mixing only makes 2 since you cant really mix something well enough to be uniform, thus you have to discard nuggets of original materials that formed because of it

smeltery is somewhat better (3-4) since it melts materials one by one from lowest melting point to highest allowing for better mixing since materials are now liquid

alloy smelter is even better (4-6) because smaller batches and higher temperatures allow for better passive mixing

mixer is the best (6-9) because it allows to mix materials into uniform dust which (almost [in case of 6-8]) doesnt form nuggets of original materials

**Comment by GTNH-Afx237v7** [comment]
There is no steam-mixer though, is there?

**Comment by SirFell** [comment]
there isnt indeed, earliest you can get it is early LV

**Comment by Prometheus0000** [comment]
I don't disagree with your order of how much a recipe should give, but you don't have a mixer at this point, and by the time you do, I'm not sure you'd be using alumite any more. So I think that you should get more, since aluminum can be hard to get, and you need a bunch for the tool forge.

You use the alumite to mine ardite, then use that to get cobalt (both of which you can use in the smeltery). So you only use alumite for a tiny window of time (a few hours?), and to make the tool forge. Well, you might have trouble repairing it, but I believe I got to the point I could make cobalt ingots before needing to repair.

**Comment by KiloJoel** [comment]
For now, can we undo https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/161? It's not an agreed-on change and will probably be reverted in the process of any other potential change anyway.

Ninja-ing changes shouldn't be a thing and a balance change should not be merged within 1 hour of making an issue regarding it.

**Comment by yukieiji** [comment]
> The mixer is too late, you're supposed to get the tool forge before then, in steam. Not that there shouldn't be a third, even more efficient recipe, but I dunno if people would even use it at that point.

I think it's a good idea because we'll need a lot of Alumite to craft Alumite Singularity.

**Comment by mitchej123** [comment]
> Ninja-ing changes shouldn't be a thing and a balance change should not be merged within 1 hour of making an issue regarding it.

💯

**Comment by alphaNOVAircraft** [comment]
Alumite is a strong material. You are still able to obtain the required alumite for the tool forge quite easy, the pr doesnt change when you unlock it, just changes the ratio to stay the same. 

It makes simply no sence that one recipe is way superior for no reason, and the smeltery recipe is more then balanced imo. You dont need to give out alumite for tools for free. 

And talking about singularities as a balancing factor for alumite is a bit weird

**Comment by SirFell** [comment]
as i already mentioned in original recipe looks like an oversight, undoing changes just because there is no current "buffed" replacement imo is plain stupid, we dont run modpack as "bleeding edge", by the time it gets into stable there will be more than enough time

**Comment by SirFell** [comment]
if i wanted to ninja it in it would be directly commited alongside some other change without opening PR period.

**Comment by SirFell** [comment]
> Not that there shouldn't be a third, even more efficient recipe, but I dunno if people would even use it at that point current recipe is 100% efficient. 9 dusts go in 9 dusts go out. easily automatable. make smeltery recipe basically useless. This recipe isnt that old either, i remember it not existing in ~2017

**Comment by Prometheus0000** [comment]
It seems there's already a mixing recipe at 100% efficiency. The other recipes should indeed be less efficient than that. It has 3 ingredients, so unfortunately we can't use the alloy smelter for this either. And, I mean, that's what the mixer is for, it's just not available yet.

kilojoel said
> I think that the dust mixing recipe should make 6 alumite, and the smeltery recipe should make 4, vs the 9 and 2 currently.

I think this, or the reverse would be fair. The thing is that it takes more effort to do the hand craft recipe than the smelter one (though only a little I admit), since you have to macerate the obsidian and aluminium, though if you're smart you macerated the gravel for the smeltery recipe too. Assuming you have gravel. On the other hand you have to wait for things to smelt and such in the smeltery.

Or we could settle on a number for the smeltery recipe and remove the hand craft recipe altogether.

**Comment by SirFell** [comment]
so hand crafting is harder. lets think about it.

Hand crafting you can craft 9 STACKS OF MATERIALS into whatever amount alumite dust

if we consider classic smeltery (3x3 inside) you would need 64 block tall smeltery. yes smeltery can be automated but in what world is momentary craft of 9 stacks of material harder than using (quite a bit of) lava and waiting for some time PLUS building giant ass smeltery

**Comment by SirFell** [comment]
i believe most fair would be to leave hand at my PR rate (5:2:2 -> 2) and buffing smeltery A LITTLE and then adding more efficient recipes finishing off at 100% efficient by volume recipe in a mixer. there shouldnt be a drastic change in efficiency IMO, even if it means gating 100% efficient recipe too far to be used in earlygame

**Comment by Prometheus0000** [comment]
I don't understand why you're talking about making an entire stack? Or rather, 9 stacks. Who would even do that? Are you making your base out of it? I'm talking about the inconvenience of macerating obsidian and maybe aluminium. And I also mentioned some of the problems with the smeltery. Why would you care about automating making alumite in the smeltery?

Also, did you miss the part where I said the mixer recipe already exists?
![image](https://user-images.githubusercontent.com/8517039/111087430-fe1c7b00-84f7-11eb-9bb8-a8f394417772.png)

**Comment by SirFell** [comment]
i know that it exists. we were talking ONLY about manual and smeltery and thats it. You said EASIER/HARDER so i pushed easier one to 
### **THEORETICAL MAXIMUM PER OPERATION** 

and then shown with alternative you said is "easier" that it would require MUCH more work to achieve same result

**Comment by SirFell** [comment]
if you want to talk about mixer recipe so much: manual crafting of same 9 stacks of alumite would take a bit over TEN AND A HALF MINUTES and 89600 EU

**Comment by Prometheus0000** [comment]
'THEORETICAL MAXIMUM PER OPERATION' isn't what we're talking about at all though. I's about the minimum level instead. And if the smeltery is harder, then I say smeltery 6, hand 4, rather than smeltery 4, hand 6.

**Comment by KiloJoel** [comment]
By nerfing the hand crafting recipe so much, all you're doing is making new players wait for 405 aluminium oreberries to grow. Given you start with only 10 of them, this results in a wait which is comparable if not longer than the wait for steel from BBFs. Just to make a tool forge.
That's not balance, that's tedium

For tools, as already explained, alumite tools are only slightly better than steel, so this nerf makes them not at all worth making.

So can you please explain @SirFell what aspect of the game did you think needed changing to justify this nerf? Besides just changing one recipe to match another.
It's clearly not an oversight because it's a recipe added by gtnh, documented in gtnh, which almost everyone playing gtnh uses. It's in the main path of progression.


For now, I've made a PR to revert the premature nerf, since the conversation hasn't been resolved, obviously this isn't permanent, but let's not allow a nerf sit on live before anyone has agreed on it. https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/162

**Comment by SirFell** [comment]
nerf being in testing vs nerf being in stable is different things but either way, yall do it whatever way you want and discuss it whatever way you want. with current state of project management and people believing "the holy quest book" like undoubtable source of information - there is no point in trying to improve on anything. I promised to check other recipes which double for other recipes - i wont do that anymore, dont feel like wasting my time doing something noone wants to see, lets just continue abusing ancient bugs and oversights. this is my final comment on this matter and im no longer taking part in further discussion

**Comment by mitchej123** [comment]
> nerf being in testing vs nerf being in stable is different things but either way, yall do it whatever way you want and discuss it whatever way you want. with current state of project management and people believing "the holy quest book" like undoubtable source of information - there is no point in trying to improve on anything. I promised to check other recipes which double for other recipes - i wont do that anymore, dont feel like wasting my time doing something noone wants to see, lets just continue abusing ancient bugs and oversights. this is my final comment on this matter and im no longer taking part in further discussion

There was no discussion, there was a ticket, PR, and merge in quick order by two people.  

We're fine discussing and adjusting, but not forcing through things without any semblance of a consensus. 

I actually liked where the discussion was going about how much for each method.
