### ISSUE TITLE
T.F.F.T Multi I/O Hatch crashes the game when used with Steve's Factory Manager.

### ISSUE THREAD

**Issue by aglebionek** [GTNewHorizons/GT-New-Horizons-Modpack#7631]
**Which modpack version are you using?**
2.1.0.0

**If in multiplayer; On which server does this happen?** 
Happens on both single and a server hosted by a friend.

**What did you try to do, and what did you expect to happen?**
Tried to use T.F.F.T Multi I/O Hatch [IV] with Steve's Factory Manager. 

**What happened instead?**
Once the hatch is connected to an inventory cable, trying to search for any inventory in Machine Inventory Manager crashes the game. 

**What changes do you propose?**
Either fix it or mention the problem in block's description if fix is not possible.

**Comment by botn365** [comment]
need crash log

**Comment by aglebionek** [comment]
[crash-2021-03-14_19.31.10-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6137406/crash-2021-03-14_19.31.10-client.txt)

**Comment by Glease** [comment]
Fixed by bot in  GTNewHorizons/KekzTech#9. Try pack version 2104.
