### ISSUE TITLE
weird chests request

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#7632]
#### Which modpack version are you using?
2.1.0.4
#

this is a bit of a weird one, but I was wondering if it would be possible to add a very special kind of chest. something that holds items like a normal chest, but limits stack size to 1 on every item. if you put 2 items inside of it, instead of forming a stack of 2, you would end up with 2 separate stacks of 1 item. 

i'm sure this would have some use beyond my imagination, but essentially this can function as a method of preserving orders of many items, without requiring one storage block per item. As currently if you push 2+ of the same item into any single block storage method, they will combine into a single stack, thus loosing the information of order. 

 Being able to have an abstract way of defining item orders of anything has its uses. order plays a roll in assline automation, multi block fluid capture, and a few other things. personally i think it would allow for some cool automated building techniques, but i'm sure there's many other fun uses as well.

**Comment by alphaNOVAircraft** [comment]
So you want a reverse buffer xD

**Comment by repo-alt** [comment]
does  filing cabinet stack items?

**Comment by 0lafe** [comment]
![image](https://user-images.githubusercontent.com/21280852/111087947-01653600-84fb-11eb-8ad5-5567279ca2a4.png)
yeah it does
