### ISSUE TITLE
RFC: Multiblock Wall Sharing Adjustment

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT-New-Horizons-Modpack#7633]
Instead of polluting other issues with mixed arguments, let's discuss adjusting (or prohibiting) wall sharing for multiblocks here.

**Comment by mitchej123** [comment]
**Proposal**
I propose we limit wall sharing on multiblocks.  

**Potential Implementation:**
Convert casings/coils into non ticking TEs (similar to ores, and how GT6 handles multiblocks) that have a reference to any controller that has claimed them, and a count of how many controllers can claim them.  This also optionally allows for covers, redstone, input, output, etc to work with any block and not just the controller or specialized hatches.

**Limited Sharing**
Double casings can be made available to allow wall sharing for aesthetic purposes without allowing for cheesing of resources.

**Backwards Compatability**
To avoid breaking existing setups, a flag can be set on new controllers that prohibits wall sharing (except where allowed as per the previous section).  Existing setups would continue to work until broken and replaced, and then would be subject to the new rules.

**Comment by bartimaeusnek** [comment]
I disagree with this for the following reasoning, this will not work without updating already existing mods, and it will create 2 classes of multis, one that still work with wallsharing, and one that does not. Another reason why this isnt a good idea: Wallsharing in itself isnt bad, if its limited to a certain extend. _Infinite_ wallsharing is, because it literally makes multiblocks cost exponentially less.

**Comment by basdxz** [comment]
Wall sharing itself is a good mechanic, although not entirely intentionally created I must assume. It give's players a sort of eureka! moment once they realise they can do more with less, and mechanics that leave the player feeling smart about themselves are generally good. It would make more sense to build new multis or modify existing ones to have their blocks arranged to make them harder to tile along, at the same time creating new possibilities with the TecTech structure check allowing for more intricate tetris-like tiling multis for people who want the most optimal wall sharing.

**Comment by alphaNOVAircraft** [comment]
Wallsharing should stay as it is. Sure, you can save resources by doing so, but you dont gain any advantage when making the first one. If you share expanding your setup will be cheaper, but then you have to manage your hatches etc better. It takes more though of the players to effectivly use wallsharing then to build the exactly same multi over and over again. It makes stuff look at least a bit different in different setups and you can save on TEs by sharing hatches that are needed by multiple controllers. 

It might not be intended when it was added, but its a good mechanic imo, rewarding ppl to make more complicated and compact setups. 

And the saving you gain by wallsharing isnt that huge imo, at least i cant remember sharing any multi bcz of cost.

**Comment by GeicowithaBango** [comment]
i dont see an argument on how this would be a good change. the covers are already fully operating. While I see two issues that will appear: 
The current state of (TT) oil cracker is perfect, they would be too expensive if we wouldn’t  allow wall-sharing, which would create the need to rebalance them again. 
Wall-sharing is a fine mechanic gameplay-wise I dont see how you cant understand this. 
Instead of nerfing things again why not make new needed content?

**Comment by Houstonruss** [comment]
Sharing walls lets you share hatches and busses, saving precious CPU with less infrastructure.

Modifying these things this late in the pack's life is a bad choice, especially considering casing cost is pennies for nearly everything, even fusion reactors. 

What is a tungstensteel ingot besides a miserable pile of dust?

Craft some circuits, increase your factory's production, not it's footprint.

**Comment by mitchej123** [comment]
> Infinite wallsharing
Sensationalism much?  How many ways can a given block possibly be shared?

> Instead of nerfing things again why not make new needed content?
The non ticking TE would enable easier creation of said content (at least for what I plan on doing)

> Wall sharing itself is a good mechanic, although not entirely intentionally created I must assume.
Still allowed under my proposal, except in cases of things like turbines.. which is just terrible.

> Sharing walls lets you share hatches and busses, saving precious CPU with less infrastructure.
How does it save CPU? And why are you overlooking the part where I explicitly said "and a count of how many controllers can claim them"

> Wallsharing in itself isnt bad, if its limited to a certain extend.
See previous two points.

> And the saving you gain by wallsharing isnt that huge imo, at least i cant remember sharing any multi bcz of cost.
And yet that's literally the argument bart and bass are making about the oil cracker...

**Comment by GeicowithaBango** [comment]
its just a bad festure

**Comment by mitchej123** [comment]
For everyone who's skipping over this part:

## Convert casings/coils into non ticking TEs (similar to ores, and how GT6 handles multiblocks) that have a reference to any controller that has claimed them, and a count of how many controllers can claim them

I said limit, not remove.  It could easily be set at "limit of 2" controllers could claim them :)

**Comment by Prometheus0000** [comment]
I'd just like to say that I agree with mitch.

**Comment by GTNH-Afx237v7** [comment]
I'm with mitch's suggestion on this one.
Question though:


    Sharing walls lets you share hatches and busses, saving precious CPU with less infrastructure.

`How does it save CPU? `

Well, less hatches/busses = less ticking = less CPU, unless I am understanding sth wrong?

**Comment by basdxz** [comment]
> I'm with mitch's suggestion on this one.
> Question though:
> 
> ```
> Sharing walls lets you share hatches and busses, saving precious CPU with less infrastructure.
> ```
> 
> `How does it save CPU? `
> 
> Well, less hatches/busses = less ticking = less CPU, unless I am understanding sth wrong?

Pretty much what Houston meant. Since hatches do tick.

**Comment by boubou19** [comment]
> I disagree with this for the following reasoning, this will not work without updating already existing mods, and it will create 2 classes of multis, one that still work with wallsharing, and one that does not.

I fail to see how this is not the case with porting multiblocks to tectech API

**Comment by Prometheus0000** [comment]
Or with GT++ multis halting instead of voiding.

**Comment by bombcar** [comment]
Why not make Obama implement this form of non-wallsharing (or priced wall sharing) and slowly migrate multiblocks to that? The shapes are already looking not very shareable. 

The idea to allow upgrades to permit wallsharing is good - for example a LCR with a nichrome coil could share that coil with another LCR. 

Perhaps another way to do it would be to make the casings/coils have sides (like how an input hatch has a square on one side) and that side has to face the controller for the MB to form. And more expensive casing would have more sides. 

For me wallsharing is less about saving resources than it is about making a “poor man’s overclock” as with my 2x shared DT that has one input and shared output and runs twice as fast as a single.
