### ISSUE TITLE
Cobalt bees and inconsistent recipes

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#7635]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
I started breeding cobalt bees a few versions ago with the intent to drive T2 fusion with it. At the time it seemed possible to run them along with silicon bees and be able to get higher energy density fusion with 0 pollution emissions since no EBF would be involved.

#
#### What happened instead? (Attach screenshots if needed)
The nuggets produced by the bees don't work in the fluid extractor and instead have to be pulverised and re-smelted.  

Interestingly, the following also happens:
- NEI indicates that cobalt crops do produce a GT-compatible flavour of oreberries, 
- All workbench crafts on tinkers cobalt convert the output into GT versions, even though the machine-equivalent recipes don't exist

#
#### What do you suggest instead/what changes do you propose?
Either:
- Tinkers-smelted cobalt should work in GT machines in general
or
- Cobalt bees should output GT-friendly nuggets

#
#### What is your GTNH Discord username?
Combuster

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/111219045-f3242200-85ad-11eb-9ab1-033ba57bacc1.png)
This may have been done on purpose to make you have to use the EBF.

**Comment by boubou19** [comment]
@combusterf what's the discoverer of this bee? it should tell us from what mod it's from.

**Comment by combusterf** [comment]
MysteriousAges
![image](https://user-images.githubusercontent.com/8459776/111220125-12847480-85d9-11eb-9497-f1fa01ab1034.png)

**Comment by boubou19** [comment]
then it's a bee from magic bee. not GT. It's unlikely that this recipe output from this bee species was ever balanced.

**Comment by Glease** [comment]
It's just picking the first result of `nuggetCobalt` in oredict. Maybe we need a unification recipe to convert it over.

**Comment by ChromicRedBrick** [comment]
Ardite, cobalt, manyullyn bees all produce TiC nuggets that can't be directly converted into GT ones.

![Ardite](https://user-images.githubusercontent.com/85604068/193335196-c08544bb-f293-4c4a-92ab-86351692c574.png)
![Cobalt](https://user-images.githubusercontent.com/85604068/193335200-452167ef-f8dc-4692-b0ab-02b56e16fff0.png)
![Manyullyn](https://user-images.githubusercontent.com/85604068/193335202-d3d2961f-001a-4bfc-94a8-ddc6655536b3.png)
