### ISSUE TITLE
suggestion: better sensor card recycling

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7638]
#### Which modpack version are you using?
2.1.0.0

#
#### What did you try to do, and what did you expect to happen?
Had to move a clean room's control block while expanding it, the sensor card no longer works, tried to find a way to reset the coordinates.
#
#### What happened instead? (Attach screenshots if needed)
No way to reset coordinates, the only thing you can do is recycle two of them to get two electronic circuits.  That's an extremely bad recycle.
#
#### What do you suggest instead/what changes do you propose?
I understand that it's impossible to recycle them fully via an assembler as they take two different parts and the assembler only has one output slot.  They should at least recycle into the same number of circuits that it took to make them.  Three each, so two cards for six circuits.
I would honestly prefer a shapeless recipe to revert sensor cards back into sensor kits.  I don't understand why it's like this.
#
#### What is your GTNH Discord username?
McFrugal

**Comment by Skiftcha** [comment]
i do not think sensor card is that much expensive so you need to make it returnable
but current recycling recipe is very strange
