### ISSUE TITLE
AE2 Charger's EU charge is wrong.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7641]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Single and multi
#
#### What did you try to do, and what did you expect to happen?
I sent EU to AE2's charger.
#
#### What happened instead? (Attach screenshots if needed)
Only 1/10 of the internal buffer was charged.
![2021-03-15_21 25 51](https://user-images.githubusercontent.com/40425798/111386047-04287c80-86ef-11eb-9e8b-a6c32a6b618b.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it.
#
#### What is your GTNH Discord username?
yukieiji

**Comment by repo-alt** [comment]
Charger does not accept EU directly from GT cables, also I don't see that in your picture.
If you mean just charger not accepting enough energy, I cannot reproduce that in dev, can you test the latest version?

**Comment by yukieiji** [comment]
@repo-alt It also happened with ver 2.1.0.5 single
![2021-03-29_09 27 14](https://user-images.githubusercontent.com/40425798/112773428-04bafe80-9071-11eb-8308-15be39f916ae.png)

**Comment by repo-alt** [comment]
Not sure I understand what do you mean. There are 1.5k out of 1.5k energy in the inscriber on that picture

**Comment by boubou19** [comment]
well waila says 1.5k out of 15k. the question now is: is it a mistake in the string displayed by waila or if the internal buffer is supposed to be 15k

**Comment by repo-alt** [comment]
oh, 15k, ok, will check

**Comment by repo-alt** [comment]
Charger is really ancient, looks like a direct port from pre-1.7 times

**Comment by repo-alt** [comment]
Ok, I fixed charging the charger, but it has a side effect. Charger uses all it's energy to charge a certus quartz crystal, and now as it has 10 times more energy it would use it. Probably not much of an issue, since who uses charger for the crystals anyway.

**Comment by yukieiji** [comment]
@repo-alt I think that's a bug that has existed for a long time.
ver2.1.0.0 and ver2.1.0.5 both seem to complete the charge when all the energy is used, and don't check how much energy has been used.

**Comment by Prometheus0000** [comment]
Does it still use a random amount of time to make a charged crystal? Because that's always been super annoying.

**Comment by repo-alt** [comment]
Of course it does
