### ISSUE TITLE
Crash by MyTown2 sqlite

### ISSUE THREAD

**Issue by KuroPeach** [GTNewHorizons/GT-New-Horizons-Modpack#7645]
There is no crash report, only log, I intercepted the important part, I added some other mod
https://paste.ubuntu.com/p/KhKYCSSgkS/

**Comment by boubou19** [comment]
Is this your first launch or did it broke suddently? Also check if you have `org/xerial/sqlite-jdbc` in your `libraries` folder and/or your `bin` folder. Officials use the 3.7.2 version of sqlite-jdbc.

**Comment by Leaveleaf** [comment]
Yep, it first time started, there is no sqlite-jdbc in lib and bin, and the download address can be provided? it is probably blocked by GFW

**Comment by boubou19** [comment]
you can download it there: https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.jar .The jar file must be put in `org/xerial/sqlite-jdbc/3.7.2/` so it looks like `org/xerial/sqlite-jdbc/3.7.2/sqlite-jdbc-3.7.2.jar`

**Comment by Leaveleaf** [comment]
ok, thanks

**Comment by Leaveleaf** [comment]
It doesn't work, it crashed again, the prompts in the log are the same as before
![image](https://user-images.githubusercontent.com/19620848/111488705-72fbe900-8774-11eb-876b-559344c48cff.png)

**Comment by boubou19** [comment]
try to put it in the `bin` folder if you have any, because i don't know where it's looking for the libraries.

**Comment by Leaveleaf** [comment]
Okay, I'm trying to put it in MyEssentials/libs,  see it calls a lot of MyEssentials code. If it doesn't work, I will try the bin directory

**Comment by Leaveleaf** [comment]
Doesn't work again. I gave it up and disabled it first, but I don’t know why there are two of them in the download server, one is disabled and the other is enabled.
![image](https://user-images.githubusercontent.com/19620848/111499946-6d0b0580-877e-11eb-9a0b-11a57de76879.png)

**Comment by Curtion** [comment]
Did you solve it？ I encountered the same problem, but it may not have much to do with GFW, because I used the proxy of HK and US and the error still persists.  This problem seems to go to MyTown2 to open an issue?

**Comment by Curtion** [comment]
I found the reason，`central.maven.org` DNS Record not found，So it's still a GFW problem

**Comment by Leaveleaf** [comment]
No solution, I changed to FTBU

**Comment by boubou19** [comment]
I think i found the cause: the class path of forge servers doesn't have the required libs of any database for mytown2.

**Comment by Curtion** [comment]
> I think i found the cause: the class path of forge servers doesn't have the required libs of any database for mytown2.

In `MyEssentials-Core-1.7.10-1.19GTNH-universal.jar` file have  `dep.info` config file , `repo` field is `central.maven.org` domain，however  `central.maven.org` DNS Record not found. this domain is not accessible.May be this reason,because `sqlite-jdbc-3.8.5-pre1.jar` file Download use this domain

**Comment by Curtion** [comment]
I have resolved,olny download
[https://repo1.maven.org/maven2/com/esotericsoftware/reflectasm/reflectasm/1.09/reflectasm-1.09.jar](https://repo1.maven.org/maven2/com/esotericsoftware/reflectasm/reflectasm/1.09/reflectasm-1.09.jar)
[https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.32/mysql-connector-java-5.1.32.jar](https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.32/mysql-connector-java-5.1.32.jar)
[https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.8.5-pre1/sqlite-jdbc-3.8.5-pre1.jar](https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.8.5-pre1/sqlite-jdbc-3.8.5-pre1.jar)

Then put them in `MyEssentials/libs` folder，Now the server is working properly

**Comment by Leaveleaf** [comment]
> put it in MyEssentials/libs,

My guess is correct, but the correct lib was not found.  : )
