### ISSUE TITLE
Wand focus: Crafting & Planar Theory researchs

### ISSUE THREAD

**Issue by TA0MACHINE** [GTNewHorizons/GT-New-Horizons-Modpack#7648]
Version 2.1.0.0 23.12.2020
multiplayer
Eta
tried to research this notes but this dots not allowed do it fully.
Tried 3-5 times delete in bin notes and make new. It doesn't help.
![f1kOoC](https://user-images.githubusercontent.com/42874669/111527067-25797f00-8768-11eb-89b5-ab4553f237a0.png)
![IY158l](https://user-images.githubusercontent.com/42874669/111527069-26aaac00-8768-11eb-9205-2ac5aa5ab99d.png)
TAO#4382

**Comment by bedrill64** [comment]
I expect a typo in the names of aspects required for research in the code, bug was dealt with some time ago with some other research. As I'm checking the script file, it is already fixed in dev.
FYI planar theory is missing Tenebrae, wand focus: crafting is missing Instrumentum aspect.

**Comment by Ethryan** [comment]
Closing this since it's fixed.
