### ISSUE TITLE
Oredict does not work with the assembly line

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7649]
#### Which modpack version are you using?
21.0.4
#
GT++ messes with assline NEI oredict visibility. If you remove it, they properly cycle. Will be fixed when it's removed.

~~Energy Module #5002~~ Invalid
~~A number of unspecified TT items #6477~~ See https://github.com/Technus/TecTech/pull/55
~~Data Bank  #6178~~ See https://github.com/Technus/TecTech/pull/55
~~Research Station #7367~~ See https://github.com/Technus/TecTech/pull/55

~~UHV energy hatch/dynamo, UHV pump (silicone) #6516~~ See https://github.com/Technus/TecTech/pull/55
~~non-specific about rubbers #7321~~ Multiple PRs, see links at bottom

Containment casing (GT++) #7218
Fusion Casing mkIII (GT++)  #6975

**Comment by Prometheus0000** [comment]
I got oredict to work on the data bank recipe by changing 
```
RA.addAssemblylineRecipe(ItemList.Hatch_DataAccess_EV.get(1), 20000, new ItemStack[]{
                CustomItemList.Machine_Multi_Switch.get(1),
                GT_OreDictUnificator.get(OrePrefixes.circuit, Materials.Master, 2),
                ItemList.Tool_DataOrb.get(1),
                ItemList.Cover_Screen.get(1),
        }, new FluidStack[]{
                new FluidStack(FluidRegistry.getFluid("ic2coolant"), 2000),
                Materials.Hydrogen.getGas(1000),
        }, CustomItemList.Machine_Multi_DataBank.get(1), 12000, 14000);
```
to
```
RA.addAssemblylineRecipe(ItemList.Hatch_DataAccess_EV.get(1), 20000, new Object[]{
                CustomItemList.Machine_Multi_Switch.get(1),
                new Object[]{OrePrefixes.circuit.get(Materials.Master), 2},
                ItemList.Tool_DataOrb.get(1),
                ItemList.Cover_Screen.get(1),
        }, new FluidStack[]{
                new FluidStack(FluidRegistry.getFluid("ic2coolant"), 2000),
                Materials.Hydrogen.getGas(1000),
        }, CustomItemList.Machine_Multi_DataBank.get(1), 12000, 14000);
```

You do need to make a new stick though.

**Comment by yukieiji** [comment]
The various UHV components also didn't work the Oredict...

**Comment by yukieiji** [comment]
It would be difficult to find and change everything, so I think it would be easier to add the ability to convert to an oredict on the API side of adding AssemblyLine recipes.
I think the only recipes that didn't require the oredicti were the Circuit-related recipes in Bio and Wetware.

**Comment by Prometheus0000** [comment]
Really? GT++ messes with the visibility, but if you remove it you can see the circuits changing in NEI.
![image](https://user-images.githubusercontent.com/8517039/115636793-b51ccb00-a2dc-11eb-96e4-3c0289416be1.png)

**Comment by yukieiji** [comment]
The rubber needed for the pumps and conveyors, not the circuits, didn't work except for silicone rubber.

**Comment by Prometheus0000** [comment]
There's an AnySyntheticRubber thing I'm investigating next.

**Comment by Prometheus0000** [comment]
This seems to allow picking from a list of items in an array?
```
GT_Values.RA.addAssemblylineRecipe(ItemList.Circuit_Crystalmainframe.get(1L), 72000, new Object[]{
                ItemList.Circuit_Board_Wetware_Extreme.get(1L),
                ItemList.Circuit_Chip_Stemcell.get(16L),
                ItemList.Circuit_Parts_Reinforced_Glass_Tube.get(16L),
                GT_OreDictUnificator.get(OrePrefixes.pipeTiny, Materials.Polybenzimidazole, 8L),
                GT_OreDictUnificator.get(OrePrefixes.itemCasing, Materials.ElectrumFlux, 4L),
                new ItemStack[]{GT_OreDictUnificator.get(OrePrefixes.foil, (Materials.StyreneButadieneRubber), 32L), GT_OreDictUnificator.get(OrePrefixes.foil, (Materials.Silicone), 32L)},
                GT_OreDictUnificator.get(OrePrefixes.bolt, Materials.HSSS, 32L),
        }, new FluidStack[]{
                GregTech_API.mIC2Classic ? Materials.Water.getFluid(250L) : Materials.GrowthMediumSterilized.getFluid(250L),
                Materials.UUMatter.getFluid(250L),
                GregTech_API.mIC2Classic ? Materials.Lava.getFluid(1000L) : new FluidStack(FluidRegistry.getFluid("ic2coolant"), 1000)
        }, ItemList.Circuit_Chip_NeuroCPU.get(1L), 600, 80000);
```

But AnySyntheticRubber doesn't work at all.

**Comment by Prometheus0000** [comment]
I managed to get AnySyntheticRubber to work after all. Similarly to before, if it's an Object type instead of ItemStack at the beginning, you can change ```GT_OreDictUnificator.get(OrePrefixes.ring, Materials.AnySyntheticRubber, 32L),``` to ```new Object[]{OrePrefixes.ring.get(Materials.AnySyntheticRubber), 32},``` and have it work for example.

**Comment by Glease** [comment]
Is the issue completely resolved, or are there any recipes left without oredict?

**Comment by Prometheus0000** [comment]
There's some elemental matter TT ones that I didn't bother with, and some GT++ ones I didn't bother with. That should be it.

**Comment by ChromicRedBrick** [comment]
In 2.2.0.0-RC-2, UHV energy/dynamo hatch recipes are not oredicted, cannot craft with 360K Space/NaK coolant cells.

![UHV Dynamo Hatch](https://user-images.githubusercontent.com/85604068/189949409-783d2c7f-8497-44fb-8a16-6b642fc1888a.png)
![UHV Energy Hatch](https://user-images.githubusercontent.com/85604068/189949418-ceaf66bf-0e50-4979-83c7-e5809dc9771a.png)

**Comment by Dream-Master** [comment]
coolant cells are not oredicted so far i remember

**Comment by ChromicRedBrick** [comment]
> coolant cells are not oredicted so far i remember

Sorry I got it wrong, what I wanted to say is that UHV hatches should be craftable with 360K Space/NaK coolant cells like ZPM/UV hatchs. This issue mentioned [#6516](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6516), but the problem still not fixed so far.

**Comment by Dream-Master** [comment]
you mean the circuits ?

**Comment by ChromicRedBrick** [comment]
> you mean the circuits ?

I mean coolant cells. Now UHV hatches can only be crafted with helium coolant cells.

**Comment by Dream-Master** [comment]
ok but this need to define in a new recipe. I said coolant cells not oredicted so it need one recipe for HE Coolant, NaK Coolant and Space Collant
