### ISSUE TITLE
A suggestion, why not change the generator to RTG

### ISSUE THREAD

**Issue by KuroPeach** [GTNewHorizons/GT-New-Horizons-Modpack#7651]
I tried to replace the generator with RTG+ClimateControl, the world generation speed is at least seven or eight times faster

**Comment by Dream-Master** [comment]
I run on my servers different versions. Some Server use RTG some RWG.
For me personal RWG have a much nicer terrain design than rtg but sure rwg is alpha or beta and never will be finished till the mod dev vanish and the license is closed.

**Comment by Leaveleaf** [comment]
The rwg terrain is indeed more beautiful , but the performance is too bad. Loading the newly generated area basically has to wait
：）
