### ISSUE TITLE
infinite metal foil 

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#7652]
The disassembler will return metal foil when disassembling certain cables.

(↓ 2x osmium cable)
![图片](https://user-images.githubusercontent.com/60341015/111610318-2ec12500-8816-11eb-87c8-4cca683e52e5.png)

but we can produce these cables with polyphenylene sulfide.

**Comment by Florexiz** [comment]
Also see #7586

**Comment by Prometheus0000** [comment]
Duplicate
