### ISSUE TITLE
uhv SC is available in luv

### ISSUE THREAD

**Issue by GlodBlock** [GTNewHorizons/GT-New-Horizons-Modpack#7654]
The disassembler will return uhv sc when disassembling the SC coil

![图片](https://user-images.githubusercontent.com/60341015/111612194-341f6f00-8818-11eb-80e8-b0070ba45c3c.png)

And we can make the SC coil with luv SC.

What's more, we can get Am and Tn by disassembling uhv SC in luv.

**Comment by GTNH-Colen** [comment]
I assume this is because of @bartimaeusnek's changes to how the disassembler works? It was inevitable a few of these cases were going to appear, shouldn't be too hard to patch maybe?

**Comment by bartimaeusnek** [comment]
We can either lock this, (read: disallow fusion coils) or make the dissassembler return LuV coils no matter what.
