### ISSUE TITLE
Can't apply Solar enchantment to wand Focus illumination

### ISSUE THREAD

**Issue by TA0MACHINE** [GTNewHorizons/GT-New-Horizons-Modpack#7655]
Version 2.1.0.0 23.12.2020
multiplayer: Eta
Tried add solar enchantment to wand Focus illumination in Focal Manipulator. 
When you press "start upgrade" nothing happens.
TAO#4382
![WYFhDm](https://user-images.githubusercontent.com/42874669/111645432-5cec3800-8809-11eb-9c64-24a1b20c6f67.png)

**Comment by GTNH-Afx237v7** [comment]
Have you tried with more than 24 levels of XP? Not sure where I saw it, but I remember there being some issue where it wouldn't start because of insufficient XP.

**Comment by TA0MACHINE** [comment]
I had 80 xp in that time

**Comment by repo-alt** [comment]
Ok, turns out that it is broken only on Thermos.
why, just why
