### ISSUE TITLE
Make Electric Air Filter suck less

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#7656]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
delta, sp

#
#### What did you try to do, and what did you expect to happen?
Tried removing pollution from a chunk with the multiblock Electric Air Filter
Expected to work like the singleblock but better

#
#### What happened instead? (Attach screenshots if needed)
Found out that the multiblock removes 280 gibbl/sec with IV power, compared to the single block 103200 gibbl/sec
Noticed that the mutliblock cycles every 10 seconds, and uses 1 to 2k of the turbine durability that is inside.
Putting Adsorption Filter where the turbine should be, makes the machine to drop to 50 gibbl/sec while still consuming the same amount of power; Not sure if that's how it's supposed to be used, but I couldn't find any other slot.
Removing turbine and leaving the mutliblock without anything in the slot makes it go to 50 gibbl/sec, so not sure what's the point of the Adsorption Filter
There is no difference in machine cycle speed (10 sec/cycle) and pollution reduction (280 gibbl/sec with IV mufflers) between IV and ZPM power, they are the same. I only tested IV and ZPM but I guess there's just no change between all powers.
There is a difference when using better Muffler Hatches (280 gibbl/sec with IV, 392 with ZPM)

#
#### What do you suggest instead/what changes do you propose?
Turbines are expensive to make, I can understand if the mutliblock consumes it like a plasma generator, but right now it's using too much durability for every cycle.
The gibbl/sec right now are ridicoulusly low, you'd need 1 multi air filter for every multi in your base, raise it up and make it change based on how much power the machine consumes. 1 or 2 mutliblocks should be able to keep up with the pollution production of an entire base. Would be nice if it could clean more than just the chunk where it is built, maybe with some type of item or fluid boost, it could do 3x3 or 5x5 (that's to reduce the number of machines needed in a base, if I have an 81 chunk base, 9x9, the whole base can be covered with 9 multiblocks instead of 81, that's mostly because of lag)

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by Prometheus0000** [comment]
Like the other issue, talk about it in the pollution channel.

**Comment by Prometheus0000** [comment]
Apparently @boubou19 wants this? Still think pollution discussion belongs in the pollution channel, because it's liable to become completely different, so any discussion using current mechanics is premature.

**Comment by boubou19** [comment]
well at that point, pollution discussion is stuck, nothing happens and players are stuck with shitty pollution, let's give a way for players to actively fight pollution, because let's be honnest, that will take monthes before getting implemented, and several pack versions are likely to be released. So it is still worth to adress this issue

**Comment by wakasagisan** [comment]
It would be cool if we can fight pollution with silverwood trees <3

**Comment by Glease** [comment]
![Efficiency of air filter as it is now](https://media.discordapp.net/attachments/502566698142924811/825016046414331954/unknown.png)

Efficiency of air filter as it is now. Only a few common turbine choices are listed.

**Comment by boubou19** [comment]
Bart made a custom GT version exporting all the turbine tooltips, so we will soon have the master table of the air filter.

**Comment by johnch18** [comment]
I don't know if it's me misunderstanding the tooltip, but the UV pollution scrubber says that it works on the 3x3 chunk area it resides in and in using it I have found that to not be the case.

**Comment by Dream-Master** [comment]
the pollution scrubber is gt++ shit. we talk about the core mod multiblock air filter

**Comment by johnch18** [comment]
Okay

**Comment by Glease** [comment]
gt++ scrubber is weird in every sense. you *can* use it but I don't like balancing around it.

**Comment by Dream-Master** [comment]
i will disable scrubbers next release.

**Comment by yukieiji** [comment]
If we disable scrubbers, I think have to adjust the amount of pollution the rockets.
Otherwise, the pollution of rocket will make the land less and less habitable...

**Comment by boubou19** [comment]
Pollution from rockets have already been reworked.

**Comment by yukieiji** [comment]
I don't think some Electric Air Filter(even the one suggested) can decontaminate the pollution rocket(T8 1,280,000 pollution/s) put out between liftoff and the switch to the space map...

**Comment by Glease** [comment]
GTNewHorizons/NewHorizonsCoreMod#172

**Comment by Glease** [comment]
GTNewHorizons/NewHorizonsCoreMod#172

**Comment by redmage17** [comment]
> 
> 
> i will disable scrubbers next release.

And watch as anyone who doesn't have pollution turned off do so....
