### ISSUE TITLE
Radon Decay quest issues

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7657]
#### Which modpack version are you using?
2.1.0.4
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
Quest have misleading requirements for 2 decayed radium 226 dusts, and then asking for radon cell (each dust give you 144 mb of radon)
![image](https://user-images.githubusercontent.com/29033773/111665822-2b349a80-8824-11eb-8533-5dbcdccbd22d.png)
Also #4641 is again an issue, lead box moved after radon decay quest
#### What is your GTNH Discord username?
FalseColor

**Comment by GTNH-Afx237v7** [comment]
It shows you the basic principle of how to operate this process, i.e. that Radon can come from decayed Radium-226 dusts. 
As for the lead-lined box I think it is OK that it comes after this quest, for the same reason I just stated - it shows the basic principle. The box is then the next advancement for you to make things  easier.
