### ISSUE TITLE
Negative kelvin temperatures in rocket fuels chemistry

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#7659]
#### Which modpack version are you using?
2.1.0.0
#
#### What did you try to do, and what did you expect to happen?
Kelvin is an absolute scale -- negative temperatures (in real life) should be impossible.
The rocket fuels at least appear to be trying to keep to realistic-ish chemistry, not magic-y or super-tech-y that would handwave away negative temperatures.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/28197216/111725327-dfd6b800-8834-11eb-8629-8300c6a4f418.png)
![image](https://user-images.githubusercontent.com/28197216/111725390-fb41c300-8834-11eb-8415-a5084bdeec13.png)
![image](https://user-images.githubusercontent.com/28197216/111725416-04cb2b00-8835-11eb-8a76-48c3bbe6a3ac.png)
![image](https://user-images.githubusercontent.com/28197216/111725505-2e845200-8835-11eb-93b1-46b7b5a0e9f6.png)
#
#### What do you suggest instead/what changes do you propose?
Double-check that these temperature values are intentional and correct.

**Comment by Dream-Master** [comment]
bug Alk for it. It's gt++ fluids

**Comment by johnch18** [comment]
A negative temperature substance would put out a lot of energy, so it would make a fantastic fuel.
