### ISSUE TITLE
Add "Cover Proxy" - [Feature Request] [Suggestion]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7661]
I was thinking that adding a block that can point to hatches/buses/controllers in a multiblock and sort of "extend" them would be a good idea, sort of like a more restrictive Actually Additions phantomface. i.e., placing an cover proxy toward a controller and placing a machine control cover on the proxy would cause the cover to act as if it were on the controller itself. This would allow a lot more flexibility in constructing multis or other automations. If it could be used as a sort of hatch itself in multis, that would be ideal as well.

**Comment by Prometheus0000** [comment]
Use a transvector interface?

**Comment by johnch18** [comment]
We had ender tanks and the ender fluid link cover was still added, I think it would be nice to have a method to do this without diving into thaumcraft.

**Comment by repo-alt** [comment]
Kinda like GT6 extender.
