### ISSUE TITLE
Unhide TC recipes in NEI

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7662]
With new feature added for AL recipes to show up in NEI without scanning I propose to also make same change for TC recipes

FalseColor — Today at 9:26 PM
Why not to enable TC recipes then?
mitchej123 — Today at 9:26 PM
lazy?
Make an issue, or a PR; I'm down
I think hiding NEI recipes is stupid anyway
I'd rather have it say  LOCKED 
Prometheus0000 — Today at 9:27 PM
Wouldn't that confuse people though? They're think it was researched and could make it
Prometheus0000 — Today at 9:27 PM
Unless NEI says something like that
#
#### What is your GTNH Discord username?
FalseColor

**Comment by johnch18** [comment]
I agree, I don't mind the research being required, but having to do it before even knowing if something is worth making doesn't make much sense.
