### ISSUE TITLE
Suggestion: Drowning Creeper remove?

### ISSUE THREAD

**Issue by Waraslt** [GTNewHorizons/GT-New-Horizons-Modpack#7663]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Yes, Any
#
#### What did you try to do, and what did you expect to happen?
Simple, Drowning Creepers Ruin/Grief my home area/my gardens apples/walnuts/farms etc(thats even worse than pvp or player griefing, well they can actually bring a bunch of those creepers and ruin your base, because this is legit)
#
#### What happened instead? (Attach screenshots if needed)
![new horizons01](https://user-images.githubusercontent.com/11662034/111828067-6b168300-88f3-11eb-9612-27384f5ce927.png)

#
#### What do you suggest instead/what changes do you propose?
remove drowning creepers, like u did remove those exploding fishes in the ocean in previous version, those were very anoying as hell so why not remove these too? these actually are even more annoying!
#

**Comment by Dream-Master** [comment]
NO. @Waraslt go play vanilla mc :)
Or feel free to make a pr and change the creeper be less annoying.

**Comment by Prometheus0000** [comment]
Do they replace TEs? If not, I don't think we'll end up removing them. Just make a fence+light things up.

**Comment by Waraslt** [comment]
> Do they replace TEs? If not, I don't think we'll end up removing them. Just make a fence+light things up.

not sure what u mean TE? 
but they do remove fruits/farms with water(not the trees) whuch mean I have to regrow those trees, not even counting fighting those silverfishes for hours...

**Comment by Prometheus0000** [comment]
TE is a non-stupid block. IE: anything that does something, like a furnace.

You could make a PR for a config for whether or not to replace blocks, there's nothing in the config.

**Comment by Glease** [comment]
My first (or second?) farm runs off the water from a drowning creeper. Please don't remove it.

**Comment by Florexiz** [comment]
It doesnt replace anything, just filling empty space with stone and water

**Comment by boubou19** [comment]
it also does not update blocks after the water appeared.

**Comment by Dream-Master** [comment]
We dont cripple special mobs or infernal mobs anymore. If you guys want to look into the code change stuff i am fine with but disable is a big NO.

**Comment by Waraslt** [comment]
yea fine I can live with that, fence the garden/light it full up, just need abit more torches, but I preffer fighting mobs around me wherever they spawn and have some fun, well theres still 2 more directions to go for them, but still those creepers will still ruin those hunting grounds(if they manage to explode), 

if it would be a single player sure I would change them, but I never play single player.

**Comment by Glease** [comment]
Your fruit is removed by the explosion, not the stone/water generation. If it was a normal creeper, the fruits will be gone as well.

**Comment by Waraslt** [comment]
> Your fruit is removed by the explosion, not the stone/water generation. If it was a normal creeper, the fruits will be gone as well. Even on normal hunting grounds, if you let a normal creeper go boom, there will also be a hole on the ground as well.
> 
> If you want a drowning creeper to generate less silverfish, we can tweak that, but otherwise I do not see how it is more annoying than a normal creeper.

well to tell you the truth I'm playing on the server where griefing is very limited, explosions are disabled, any interference with land claim is prohibited from outside except these creepers, so no apples are removed with flowing water here.

**Comment by Glease** [comment]
Ah now I see why you are so angry over all this. The special mobs creepers are indeed not respecting the mobGriefing setting. I'll poke around and see what I can do.
