### ISSUE TITLE
Fix the IC2 Spade tooltip, add better info to the quest

### ISSUE THREAD

**Issue by McFrugal** [GTNewHorizons/GT-New-Horizons-Modpack#7664]
#### Which modpack version are you using?
2.1.0.0

#
#### What do you suggest instead/what changes do you propose?
Ok, so, the questbook says the Spade is worse at collecting seed bags.  The tooltip says the opposite.  The big IC2 Crops post says the Spade ignores growth stage and thus us good at trying to get seed bags from the initial sprout of a crop.  I am thus confused.

The Spade should not have misleading information in its tooltip.  The questbook should give all the important information on it, meaning that it should tell the reader what situations it's better to use a Spade, and when it's better to just punch the crop.
#
#### What is your GTNH Discord username?
McFrugal

**Comment by Prometheus0000** [comment]
Go update your questbook or update your pack version.
![image](https://user-images.githubusercontent.com/8517039/111849504-1cadb800-88e4-11eb-9846-7d1119068d90.png)

**Comment by McFrugal** [comment]
That's the version I have.
That doesn't say it ignores growth state.  That says you CAN right click to get seeds, not that the Spade helps there.  The formula doesn't help if you're comparing Spade vs punch, and it's unclear as to if that formula is for Spade chances or for punching.  It has no variable for the stage of the crop, so either that formula only works for max stage, or it's the Spade formula.  It was posted in the IC2 Crops post in a section that doesn't talk about the Spade, so... it's for max stage punching?  Except that doesn't make sense since you can get more than 1 seed.  That formula can't go above 100%.  Does it roll twice?

**Comment by Prometheus0000** [comment]
> That doesn't say it ignores growth state.

![image](https://user-images.githubusercontent.com/8517039/111850203-086aba80-88e6-11eb-8a88-4b356a0faf41.png)

I just put the formula someone else posted in there. If it's wrong, it's not my fault. It _should_ be for the spade. If it's wrong, find the correct one and I'll fix it. I also have no idea what the normal formula is, or well, anything about deciding seed drop formulas.

**Comment by bedrill64** [comment]
The given formula is calculating seedbag chance based on crops tier and stats, you can use wolfram alpha to check diagram for given data, it is accurate and shouldn't go above 100%. Better stat and higher tier lowers the seedbag chance.

**Comment by McFrugal** [comment]
Again, that doesn't say it ignores growth rate.
"you can right click to get seeds at the initial maturity state".  That's true when punching it too.

I read the quest, got confused by the text and how it contradicted the tooltip, and felt that it must be referring to accidentally uprooting a crop when trying to weed and that the weed trowel wouldn't do that, so I kept using the Spade to attempt to harvest seeds.

**Comment by Prometheus0000** [comment]
It's not my fault that bart made a completely inaccurate tooltip.

**Comment by Prometheus0000** [comment]
I adjusted the quest again, based on the discussion with bart in discord.
