### ISSUE TITLE
Add a Molten Naquadria recipe to the Fusion Reactor [Un-Nerf request]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7665]
Naquadria is pretty annoying to get, it doesn't spawn as an ore and it cannot be replicated. The best way at present is ore processing enriched naquadah, but this method is not optimal in my opinion. I think adding a way to craft molten naquadria in the fusion reactor would ease this problem. I would suggest that it be a MkIII recipe, in order to maintain balance, as UV components require a lot of the stuff. I would personally suggest:
    32L U-235/Pu-239 + 64L Nq+ -> 16L Nq* 
as it still requires enriched naquadah, but also includes something suitably expensive (something radioactive, fitting with the theme), and requires a lot of both relative to the output.

I noticed that in the past that Naquadria was available as a pumpable fluid. I can understand the logic behind removing this, but I think we have gone from one extreme to the other. Adding an ore / small ore for it would also be suitable, but personally I'm partial to the idea of it being a fusion recipe.

**Comment by GeicowithaBango** [comment]
there should be a naquadria fusion recipe already in the game

**Comment by johnch18** [comment]
There is not, I'm on 2.1.0.0.

**Comment by GeicowithaBango** [comment]
gonna check it out tomorrow

**Comment by johnch18** [comment]
According to NEI, the only way to get Molten Naquadria is to use a fluid canning machine or a fluid extractor.

**Comment by GeicowithaBango** [comment]
I can confirm that the Naquadria recipe is missing, and there is one, definitely

**Comment by johnch18** [comment]
I wouldn't mind if it's suitably gated, I just think it's weird that getting naquadria never evolves past "mining lots of enriched naquadah"
