### ISSUE TITLE
Bartworks simple sterling generator uses buckets as fuel

### ISSUE THREAD

**Issue by Rakdarian** [GTNewHorizons/GT-New-Horizons-Modpack#7666]
#### Which modpack version are you using?
latest version
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
put a bucket of creosote in the sterling water generator and i expected it to return an empty bucket
#
#### What happened instead? (Attach screenshots if needed)
it consumed the bucket and the creosote oil
#
#### What do you suggest instead/what changes do you propose?
either remove the buckets as fuel, or have them return the buckets as fuel
#
#### What is your GTNH Discord username?
𝕽𝖆𝖐𝖉𝖆𝖗𝖎𝖆𝖓#7628

**Comment by Prometheus0000** [comment]
Is there even an output slot?

**Comment by johnch18** [comment]
No output slot, only fuel input. Why would you want to use buckets? Let's say you get the bucket back, you now need to extract it, fill it, and put it back in.

**Comment by skynsun** [comment]
I dont know if its related but the bucket happen to be consummed too when i try to craft gallium from xp bucket. it happen with crafter (ender IO), autocrafting bench and project bench (projectred), But they dont consumme with crafting station (tinker construct) and vanilla craft table.
