### ISSUE TITLE
New block idea - voiding fluid tank

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7670]
#### What do you suggest instead/what changes do you propose?
So my idea is a gregtech tank which will immediately void fluids that are input.

The main purpose being the ability to empty cells and other fluid containers without having to then empty the tank that you emptied them into.
#
#### What is your GTNH Discord username?
KiloJoel

**Comment by GTNH-Afx237v7** [comment]
If a void / overflow cover comes into existence, this could solve this particular issue as well

**Comment by Prometheus0000** [comment]
Plunger or tank+pump above a fluid trash can. Or an overflow cover set to 0 (if it can).

**Comment by KiloJoel** [comment]
> 
> 
> If a void / overflow cover comes into existence, this could solve this particular issue as well

Not fully, because this would allow you to input any liquid into the tank at any time, because the tank would never contain a specific liquid, so could empty any liquid.

**Comment by KiloJoel** [comment]
> 
> 
> Plunger or tank+pump above a fluid trash can. Or an overflow cover set to 0 (if it can).

My reasoning is a more automatic and sensible way to handle voiding for cells, plunger isn't automatic, and an overflow cover would only allow 1 liquid type, as said in the previous comment
