### ISSUE TITLE
"Button Group" item no crafting recipe

### ISSUE THREAD

**Issue by LaM0x** [GTNewHorizons/GT-New-Horizons-Modpack#7671]
#### If in multiplayer; On which server does this happen? 

#   Eta
#### What did you try to do, and what did you expect to happen?

#   The button group recipe doesnt exist, it cant be crafted (and for a keyboard to be magic would be weird)
#### What happened instead? (Attach screenshots if needed)

#
![image](https://user-images.githubusercontent.com/28361743/111887093-03376980-89d3-11eb-84cd-3e601925d004.png)
#### What is your GTNH Discord username?
LaM0x#7758

**Comment by Prometheus0000** [comment]
There's no such item?

**Comment by boubou19** [comment]
i already seen it in the game at some point, so must be an outdated configuration. How did you downloaded the game? Technic forge or multimc?

**Comment by LaM0x** [comment]
technic launcher, i wanted to make a typing machine for my house

**Comment by boubou19** [comment]
Try to install the pack via multimc and see if it still happens.
