### ISSUE TITLE
nano helmet typo

### ISSUE THREAD

**Issue by LaM0x** [GTNewHorizons/GT-New-Horizons-Modpack#7673]
#### If in multiplayer; On which server does this happen? 

#  Eta
#### What did you try to do, and what did you expect to happen?

#   my ocd got triggered
#### What happened instead? (Attach screenshots if needed)

#   
![image](https://user-images.githubusercontent.com/28361743/111887208-c455e380-89d3-11eb-9e03-e37145c3c176.png)

#### What is your GTNH Discord username?
LaM0x#7758

**Comment by GTNH-Afx237v7** [comment]
see https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/166
