### ISSUE TITLE
Backport Storage Downgrade item [Feature Request]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7675]
In later versions of storage drawers, there is an item that allows you to set your drawer's base capacity at 1 stack. This is useful for creating smaller buffers of specific sizes. I think it would be very useful and should be backported.

**Comment by boubou19** [comment]
as a temporary workaround, we have baby chests that acheive this.

**Comment by johnch18** [comment]
That's limiting you to one stack though

**Comment by boubou19** [comment]
one could also fill a chest with junk item stacks, then whitelist/blacklist the exportation from the chest, but that's not convenient as well in comparison to the storage drawers thing you describe.
