### ISSUE TITLE
The disassembler does not work on some items

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7676]
Like:
pollution scrubber
gas turbine gen
steam turbine gen
combustion gen
steel firebox casing
motor machine casing
titanium pipe casing
vacuum freezer controller
industrial material press

@bartimaeusnek Does it only work on things that have assembler recipes? Are you planning on adding support for normal crafting and/or assline and/or circuit assembler recipes? Or other types?

**Comment by Houstonruss** [comment]
Wont matter soon, disassembly is getting phased out. If you gotta recycle something try the arc furnace!

**Comment by Prometheus0000** [comment]
? This is after disassembly change?
