### ISSUE TITLE
Connecting Redstone Conduits to AE2 Buses causes extreme network lag.

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7678]
#### Which modpack version are you using?
2.1.0.0

#
#### What did you try to do, and what did you expect to happen?
I was automating an LCR, and as part of that I used redstone conduits to toggle some export buses with redstone cards.

#
#### What happened instead? (Attach screenshots if needed)
Soon after, my entire network became unable to import/export anything, fluids or items. Storage buses and interfaces still worked fine, however. I also experienced a somewhat noticeable framerate drop.
At first I didn't realize that my automation and this problem were correlated, so I began to quarantine different pieces of my network to isolate the problem until I narrowed it down. I began to test the interaction between bus and conduit and found that after connecting them and allowing the problem to begin, I could immediately solve it by disconnecting the conduits from the buses. 

Something about these two types of devices interacting causes AE2 to freak out. I couldn't find anything online about anyone noticing this before, so maybe I'm imagining things.

**Comment by Prometheus0000** [comment]
So no other redstone types or conduit types cause this?

**Comment by johnch18** [comment]
I've used red alloy wire and vanilla redstone with buses before and didn't notice anything. I don't use any other conduit types so I can't speak on any of them.

**Comment by johnch18** [comment]
I'm going to do some testing with other redstone types, I'm wondering if it might be in part because of my network size.

**Comment by repo-alt** [comment]
Please describe some simple setup that produces lag for you (with conduits and import/export buses)
