### ISSUE TITLE
Calcium ingot has no blast furnace recipe

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7682]
#### Which modpack version are you using?
2.1.0.0

#
#### What did you try to do, and what did you expect to happen?
Tried crafting calcium ingots first in a multi-smelter, then a blast furnace.

#
#### What happened instead? (Attach screenshots if needed)
Couldn't craft them, discovered in NEI that they're only craftable from fluid or in the Infernal Blast Furnace

#
#### What do you suggest instead/what changes do you propose?
Add an EBF recipe.

**Comment by Prometheus0000** [comment]
Calcium is not supposed to, is it?

**Comment by botn365** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6274
it is

**Comment by Prometheus0000** [comment]
Duplicate then.
