### ISSUE TITLE
GT++'s Leaves array is out of bounds and the client is stuck

### ISSUE THREAD

**Issue by Leaveleaf** [GTNewHorizons/GT-New-Horizons-Modpack#7683]
GT++'s Leaves array is out of bounds and the client is stuck, After the trees have grown
https://paste.ubuntu.com/p/g8rpSqTnKc/
GTNH-2.1.0.4 with OptiFine_1.7.10_HD_U_E7.jar

**Comment by boubou19** [comment]
did you replicated it without optifine? and is the `chunk loading` option in video settings set to default? if it's not set on default,  set it on default and see if it happens again.

**Comment by Leaveleaf** [comment]
ok，i'm use multi-core，change it now

**Comment by Leaveleaf** [comment]
It’s still stuck, but I think I found the reason. My tree farm is on fire. It's probably because the trees replaced the fire block, which caused the game to go wrong.

**Comment by boubou19** [comment]
can i close this then?
