### ISSUE TITLE
Input Hatch/Bus priorities for multiblocks - [RFC]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7684]
Something that has perplexed and frustrated me for a while now is how a multiblock selects which bus or hatch to prioritize when beginning a recipe. I used to believe that it was simply a directional priority thing, something like UD/NESW, however in testing I've found that not to be the case.
What exactly determines the selection of input, is there a certain order a multiblock goes through or is it random? It would be helpful to know exactly how multiblocks select which recipes to run, (e.g. a neutronium blast furnace that uses radon but has argon as a backup), as it would allow more control when building multiblocks. My personal preference would be to allow some way to set hatch/bus priorities.

**Comment by Prometheus0000** [comment]
This isn't the place for questions, go ask on the discord.
