### ISSUE TITLE
Torches need to produce pollution

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#7685]
They smoke therefor they pollute about 5 a tick should do it. Magnum torches should produce about 200.

**Comment by boubou19** [comment]
everyone is struggling with pollution and you want to add some more? how nice of you

**Comment by Houstonruss** [comment]
Magnum torch 128x pollution. not having mobs is too cheap rn this would balance it

**Comment by Glease** [comment]
Let's stop trolling and fill [these](https://gtnh.miraheze.org/wiki/Pollution_revamp) [pages](https://gtnh.miraheze.org/wiki/Pollution_revamp_visions) instead.

**Comment by redmage17** [comment]
> 
> 
> Let's stop trolling and fill [these](https://gtnh.miraheze.org/wiki/Pollution_revamp) [pages](https://gtnh.miraheze.org/wiki/Pollution_revamp_visions) instead.

Not Trolling Torches produce smoke there for are polluting.
