### ISSUE TITLE
Pollution Rework Idea

### ISSUE THREAD

**Issue by MatthewCOwen** [GTNewHorizons/GT-New-Horizons-Modpack#7686]
#### Which modpack version are you using?
2.1.0.4
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
I think that pollution should be added to minecraft torches since they constantly emit smoke particles. This would also incentivize the player to use the underutilized mod *Open Modular Turrets* instead of excessively lighting up the surrounding area.

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7685

**Comment by basdxz** [comment]
we also need to have mobs destroy blocks
you know, like zombies in hard mode can break doors but instead any GT Block
this is because a GTNH is supposed to be a hardcore back but it seems to be getting constant 
buffs masked as QoL issues which is honestly unfunny
