### ISSUE TITLE
Carpenter autocrafting issues

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#7687]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Make industrial apiaries autocraftable
#
#### What happened instead? (Attach screenshots if needed)
I found a few other crafting recipes suffering from the same problem as in #7088. The beealyzer is present both as top-slot and grid-slot recipies, so it will always go in the top slot and thus both the analyst and alveary stablisers can't be crafted without manual interference.
#
#### What do you suggest instead/what changes do you propose?
Since the pattern repeats for all the *lyzers to *database and *lyzers to analyst, it's probably best to tackle this for all of them.
The analyst requires all three beealyzer, treealyzer and flutterlyzer, so it's most appropriate to fix the recipes that have a *lyzer in the top slot. The uninformed course of action would be to swap with the HV circuit, but that will cause a new set of top-slot conflicts for the circuits.

So instead I would suggest updating the recipes with something similar in technology. The HV circuit is like the last thing in MV to craft, so options would be to use an plastic PCB (somewhat earlier in MV and more chemistry-focused and a common top-slot item), an HV hull (another late-MV craft). A data stick would lore-wise be more appropriate, but that would push the recipes well into HV land after the cleanroom.

Summarized, from
![image](https://user-images.githubusercontent.com/8459776/111919954-aac4a280-8a8c-11eb-9841-26bb671dfd72.png)
to
![image](https://user-images.githubusercontent.com/8459776/111920024-fc6d2d00-8a8c-11eb-8cc4-c24790e0762e.png)
for the [bee/tree/flutter]lyzers to their database variants.

#
#### What is your GTNH Discord username?
Combuster

**Comment by Prometheus0000** [comment]
Don't you just need the beealyzer?
![image](https://user-images.githubusercontent.com/8517039/111920366-ea779400-8a64-11eb-994a-85cee0cfed94.png)
![image](https://user-images.githubusercontent.com/8517039/111920370-eea3b180-8a64-11eb-86b9-65c18ac76e8a.png)
![image](https://user-images.githubusercontent.com/8517039/111920350-d16ee300-8a64-11eb-949f-91e5525601d9.png)
![image](https://user-images.githubusercontent.com/8517039/111920354-d895f100-8a64-11eb-8042-72557a8c67dd.png)
It autocrafts fine? What do you need to autocraft the others for?

**Comment by combusterf** [comment]
No, it does not autocraft
![image](https://user-images.githubusercontent.com/8459776/111920540-d8f7b180-8a8f-11eb-9952-644722d2bec7.png)
The beealyzer can't be inserted into the carpenter
![image](https://user-images.githubusercontent.com/8459776/111920562-fcbaf780-8a8f-11eb-9d89-93a41276e3f8.png)

**Comment by Prometheus0000** [comment]
I just saw that. What about the others? Why do you need to autocraft them?

**Comment by combusterf** [comment]
I don't, but might as well fix them all/keep them consistent while we're at it.

**Comment by Prometheus0000** [comment]
There's no point in spending extra effort on other stuff if no-one is going to craft a ton of them.

**Comment by Prometheus0000** [comment]
I just replaced the beealyzer with a royal jelly.
