### ISSUE TITLE
ME system don't see extra cells crafting storage

### ISSUE THREAD

**Issue by Oueio** [GTNewHorizons/GT-New-Horizons-Modpack#7688]
#### Which modpack version are you using?
2.1.0.4
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Trying to autocraft CAL with 110000 bytes
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/75951914/111981203-6b439800-8b18-11eb-8dc8-bb85f9256a88.png)
![image](https://user-images.githubusercontent.com/75951914/111981232-74346980-8b18-11eb-95af-f23d8d9c3e3e.png)

#
#### What do you suggest instead/what changes do you propose?

#

**Comment by GTNH-Afx237v7** [comment]
You need to attach the EC2 crafting storage to a regular AE2 crafting storage for it to work.

**Comment by Oueio** [comment]
okay, thanks
