### ISSUE TITLE
Quest change suggestion

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7690]
#### Which modpack version are you using?
Dev version

Quest 893 asks you to make 1 mv pump, and the next quest(951) requires the use of 2 mv pump so make the pump quest ask for 2 pumps instead of 1

**Comment by boubou19** [comment]
pack version 2.1.0.4

**Comment by Prometheus0000** [comment]
No. All of them only ask for 1. I'm not going to count up all the pumps, motors, conveyors, etc for every tier you need to complete the quests. Not to mention you'll likely still need a bunch more. Just make a bunch of them.
