### ISSUE TITLE
Me Interface "sleep loop" in combination with GT Multiblocks 

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#7692]
#### Which modpack version are you using?
2.1.0.0 (Issue is unrelated to verison) 
#
#### If in multiplayer; On which server does this happen? 
private 
#
#### What did you try to do, and what did you expect to happen?
I build a wiremill setup that should be fast enough for all my future plans, it consists of 8 PAs with 64 ZPM Wiremills each. The items get pushed into the different input buses of the PAs with pipe => conveyer => conduit => input bus. 
I expected the interface to keep all PAs supplied with items while they are running. 
#
#### What happened instead? (Attach screenshots if needed)
The PAs shut down all the time due to a loop like behaviour of Interface and PA: 
Interface pushes items into pipe (at the beginning, as long as there is room left in the pipe it does that every tick). When the pipe is full bcz at the beginning the PAs arent running (cz they need a short time to toggle on). the interface puts itselfe into a short sleep (only a few ticks, but enough to cause issues).
Now the PAs toggle active and use up all the items in the input bus and pipe before the interface is finished with its shourt sleep cycle and the PAs toggle off again (cz they have no more items to process). 

This behaviour will repeat every few sec, extremely limiting the throughput of the entire system. 

A current option to avoid that behaviour is adding a large enough buffer inbetween (e.g. in this case a Quantium Item Pipe). But such a pipe is not ms friendly at all (e.g. in this setup it takes avrg of 820 000 ns). 

#
#### What do you suggest instead/what changes do you propose?
Find a solution to aviod the given loop. 

#
#### What is your GTNH Discord username?
alphaNOVA#9875

**Comment by mitchej123** [comment]
This seems like it would introduce more lag by running the check every tick when the target inventory was recently full?

**Comment by alphaNOVAircraft** [comment]
> This seems like it would introduce more lag by running the check every tick when the target inventory was recently full?

It would be more laggy on the ME Interface time, but only for the short period till the PAs will turn on (or other multiblocks). In comparison to other solutions (namely a large buffer) it should be way less laggy. 

Thats why i also suggested, that this option should be locked behind a upgrade card that isnt aviable until lategame where you actually need it. And ofc it should only check every tick while the craft is running. So the worst case would probably be around 100 additional operations per till the PAs turn on.

**Comment by Prometheus0000** [comment]
Can't you just use a super bus (I)?

**Comment by alphaNOVAircraft** [comment]
Using a Superbus will increse the ticktime of the distribution pipe up to more then 2 ms 
So thats a even more laggy solution

**Comment by Prometheus0000** [comment]
Is there no way to get the input bus to tell the interface that it has space? Or would that require serious code rejiggering since it has no idea where the input is coming from?

**Comment by alphaNOVAircraft** [comment]
> Is there no way to get the input bus to tell the interface that it has space? Or would that require serious code rejiggering since it has no idea where the input is coming from?

Doesnt even have to be a input bus, could be a special block from ae2 or gt, but would probably be the most lag efficient fix

**Comment by Prometheus0000** [comment]
Yeah, but admittedly if it were possible I think someone would have done it already 😞

**Comment by alphaNOVAircraft** [comment]
If it would be possible; 
Make it a gt cover (that way its quite flexible and can be used on multiple ways), (would also be nice if it would only let items in like a shutter module)

**Comment by alphaNOVAircraft** [comment]
Possible approach; 

Add a upgrade card that disables the sleep feature so it keeps on pushing / checking every tick. 

This would add some more operations at startup of the PAs, but once they are running the total amount of checks / pushing operations of the Interface are the same as before, but the throughput of the setup will not be limited by the toggle on / off loop and no laggy buffer is required. 

This upgrade could of course be a source for additional lag tho if ppl use it randonmly on setups where there is absolutly no need for. Overall i dont think such a upgrade would be necessary anywhere before UV or UHV, so gating it behind that tier could ensure not everyone is spamming it. 

Overall it should be way less laggy then the current fix with a large enough buffer.

**Comment by repo-alt** [comment]
Probably the simplest solution is to let the input bus to wake up the interface when it is empty (or non-full)

Can't say I understand Lea's suggestion (first part)

**Comment by alphaNOVAircraft** [comment]
> Probably the simplest solution is to let the input bus to wake up the interface when it is empty (or non-full)

Would be cool if that one could be implemented to a cover, sometimes its more or less required to distribute the items before they reach the final Multi that will process them, cz just having the pattern on multiple input bus wont add the required parallels. 

But i guess if its possible for a hatch it also could be possible for a cover ?!

**Comment by botn365** [comment]
we need a input bus ae
when it makes a recipe it will push the items in some inventory then force the multi to do a recipe search if it was not running
then when the multi consumes items it puts a flag on the all the input busses ae to tell them they can push items again

**Comment by boubou19** [comment]
wasn't ae input bus added already?

**Comment by alphaNOVAircraft** [comment]
> wasn't ae input bus added already?

I think a output bus was added that directly transfers the items into the ae instead of output bus to ae.

**Comment by repo-alt** [comment]
Output is conceptually simple. Input though, not so much.

**Comment by Glease** [comment]
> ME Input Bus

Sounds like AE2 molecule assemblers, but with different recipe map.

**Comment by repo-alt** [comment]
molecular assembler is a glorified crafting table

**Comment by Glease** [comment]
I mean vanilla crafting table recipe map. The operational semantics of these two are quite similiar. Push stuff matching recipe inside, wait a few seconds, then recieve the items pushed out by the machine.

**Comment by repo-alt** [comment]
In that respect currently multiblock behaves exactly like molecular assembler with a different recipe map. Stuff gets pushed into it by the interfaces, and it pushes the result back.

**Comment by Glease** [comment]
Hmmm yes. Then what's really lacking is just waking up the interface.

**Comment by GTNH-Afx237v7** [comment]
What about the config settings for min/max tickrate -or am I understanding this wrong?
![grafik](https://user-images.githubusercontent.com/64365566/112267309-8972da80-8c75-11eb-99e5-1da165f207f3.png)

**Comment by Prometheus0000** [comment]
Why does that text file look like 1980s DOS?

**Comment by GTNH-Afx237v7** [comment]
Because I like the look

**Comment by repo-alt** [comment]
That config does indeed regulate delay, but it's not like we actually want the interface to work every tick, (except the special case described above)

**Comment by 0lafe** [comment]
what if you put a larger chest/pipe between AE and the wire mills?

**Comment by sintken** [comment]
Good workaround is to put the interface on a 2x2 upgraded drawer with a conveyor against the input bus. As long as the conveyor works faster than the multi, the multi will stay on. Doesn't work as well for recipes needing multiple inputs, but that can be solved with some subnetting.
