### ISSUE TITLE
Feature Request: Buildcraft harvesting bots to support Natura crops (possibly Thaumcraft as well)

### ISSUE THREAD

**Issue by Zodiack256b** [GTNewHorizons/GT-New-Horizons-Modpack#7693]
#### Which modpack version are you using?
2.1.0.4

#### If in multiplayer; On which server does this happen? 
Private Server

#### What did you try to do, and what did you expect to happen?
Setup Buildcraft havesting robot with natura crops (Barley, Cotton, Berries) in area designated to work in.

#### What happened instead? (Attach screenshots if needed)
Natura crops were skipped by the bots, Berries the bots broke the center berry bush of the 3 high bushes and get locked up trying to harvest the already broken bush.

Side note, The bots detect and harvest the Umbral Rose bush as a crop. I have not had the chance to try other Thaumcraft related plants

#
#### What do you suggest instead/what changes do you propose?
See if it would be possible to import the way Harvestcraft crops are treated by the bots logic to Natura and maybe other mods within the pack.

#### What is your GTNH Discord username?
ZodiacK256B

**Comment by repo-alt** [comment]
Looks like BC is opensource now, so perhaps it may be fixed, if somebody had nonzero interest

**Comment by Dream-Master** [comment]
https://github.com/GTNewHorizons/BuildCraft

**Comment by asiekierka** [comment]
Both should be added in BuildCraft Compat 7.1.8.
