### ISSUE TITLE
Rhodium Duplication Glitch

### ISSUE THREAD

**Issue by xyqyear** [GTNewHorizons/GT-New-Horizons-Modpack#7694]
#### Which modpack version are you using?
2.1.0.0
#
#### What did you try to do, and what did you expect to happen?
Using packager to make tiny rhodium dust into rhodium dust. 9 tiny dust items should yield 1 dust item and 4 small rhodium dust items should yield 1 dust item.
#
#### What happened instead? (Attach screenshots if needed)
2 small rhodium dust items can make 2 dust items and 1 tiny rhodium dust item can make 2 dust items.
![image](https://user-images.githubusercontent.com/29950788/112157342-1429ea00-8c22-11eb-8b9c-1d283bdd4a6b.png)
![image](https://user-images.githubusercontent.com/29950788/112157359-17bd7100-8c22-11eb-9741-22e9dc69bc8b.png)

#
#### What do you suggest instead/what changes do you propose?
Delete the two above recipes.
#
#### What is your GTNH Discord username?
xyq

**Comment by Prometheus0000** [comment]
More reasons not to like non-full dusts. @bartimaeusnek
