### ISSUE TITLE
remove pure tungsten ore from europe

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#7696]
with the new tungsten ore chain pure tungsten ore should not be unlocked this early
replace it with tungstate ore

**Comment by Florexiz** [comment]
According to rutile/titanium ores we should replace europa tungsten vein to small tungsten ores, not remove it entirely

**Comment by alphaNOVAircraft** [comment]
If you replace it with a small ore ppl will just mine more small ore, not use the line, removing it completly from that gc tier seems better to me.

**Comment by Florexiz** [comment]
What is the difference from rutile then?

**Comment by alphaNOVAircraft** [comment]
I never said pure titanium should be aviable as small ore on mars. But the furth you go the better the drilllings get => its more efficient to use small instead of the compount ores

**Comment by botn365** [comment]
i think small titanium ore should be replaced by small rutile ore on plants before T4

**Comment by GlodBlock** [comment]
i don't think that would be a good idea. it is painful to setup a metal processing line and add burden on tps. making tungsten more difficult to get in early game is pointless because the line will be deserted immediately as  soon as you unlock the tungsten ore.
gtnh isn't gregicality, add more interesting machines and features instead of keeping nerfing.

**Comment by Prometheus0000** [comment]
> deserted immediately as soon as you unlock the tungsten ore

You do know about the new tungsten processing, right?

**Comment by GlodBlock** [comment]
> > deserted immediately as soon as you unlock the tungsten ore
> 
> You do know about the new tungsten processing, right?

yeah.
but tungsten line is different from titanium, rutile only consumes sodium and chlorine so it still have a chance to keep running when titanum ore is unlocked.

**Comment by Prometheus0000** [comment]
Well, you have significantly reduced smelting times with the new line, so you might want to keep using it.

**Comment by Prometheus0000** [comment]
@botn365 I think you already did this?
