### ISSUE TITLE
Cobaltite on the ebf giving a different ammount of sulfur dioxideCobaltite on the ebf giving a different ammount of sulfur dioxide

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7697]
#### Which modpack version are you using?
Version 2.1.0.4
#### What did you try to do, and what did you expect to happen?
I was Making sulfur dioxide on the ebf using the cobaltite recipe
#
#### What happened instead? (Attach screenshots if needed)
It's giving a lot less sulfur dioxide than the nei says
![2021-03-23_20 36 16](https://user-images.githubusercontent.com/57275066/112232806-fb1c3b80-8c17-11eb-92d2-d5d819ffe185.png)
![2021-03-23_20 35 59](https://user-images.githubusercontent.com/57275066/112232817-02dbe000-8c18-11eb-8e16-8cb861a36b4d.png)

**Comment by Prometheus0000** [comment]
Read the hatch tooltip
