### ISSUE TITLE
buff quantum tank or have new tank tier?

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#7700]
as we know, an unit of item usually is 1 item, but in fluid, is 1000mb or 144mb. so quantum tank V0 is significantly smaller than quantum chest V. 
according to my another issue, player can easyly use out quantium tank V. maybe we can buff quantum tank V or have higher tier tanks like quantum tank VI, whitch is over 2MB capacity.

**Comment by repo-alt** [comment]
Not impossible, but require some accuracy. Quantum tank V already has capacity 2^31, and FluidStack has amount field of type `int`, so those giant tanks should have separate FluidStack and `long` capacity, which may easily lead to dupes/void.

**Comment by Prometheus0000** [comment]
Why exactly do you need this much? And why can't you just use more than one tank?

**Comment by Pnc6lx** [comment]
in my base, some fluid have vary large amount. in other issue, i said extracells have visual bug with fluid over 2^31 mb. 
when  put out these fluid, i find N2 is 8*64*65536000=33.5Gmb, slightly much bigger than quantum tank V, 2.1Gmb

**Comment by Prometheus0000** [comment]
Again, why do you need that? Just void it or stop producing it.

**Comment by GTNH-Colen** [comment]
> in my base, some fluid have vary large amount. in other issue, i said extracells have visual bug with fluid over 2^31 mb.
> when put out these fluid, i find N2 is 8_64_65536000=33.5Gmb, slightly much bigger than quantum tank V, 2.1Gmb

One thing I might suggest that works well for me is using bedrockium drums, if you pipe empty drums into a super tank it will fill them as if they were cells, these can then be stored in a super chest. For example a minimum size super chest which holds 4,000,000 items can hold 262,144,000,000,000L of fluid or 122,070 max sized super tanks (2^31 ml) worth.

If you really need to store this much fluid I'd assume you have access to void miners so bedrockium shouldn't be a concern. Lastly if you want some way to 'monitor' it you can use OC to count the number of bedrockium drums in there and multiply that by the fluid held to create a display.

> Again, why do you need that? Just void it or stop producing it.

Never.

**Comment by Prometheus0000** [comment]
Do the osmium cells not hold more? Or whatever the highest tier one is.

**Comment by GTNH-Colen** [comment]
> Do the osmium cells not hold more? Or whatever the highest tier one is.

Yes but osmium is arguably more irritating to obtain due to the plat line, bedrockium can be obtained in the millions fairly easily from VMs. If you want to cook it normally then it's even better efficiency wise but there is an assembler recipe that turns 9 dust into 1 ingot in 1 tick which is far faster if you don't care.

**Comment by GTNH-Colen** [comment]
I do kinda agree with the sentiment of this post though, larger tanks would be nice however I'm not sure where to gate them as imo quantum tank Vs are already far too expensive for what they do.
