### ISSUE TITLE
Red Zirconium ignored by ore drilling plant

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#7701]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Multiplayer, private server
#
#### What did you try to do, and what did you expect to happen?
I built ore drilling plant on Ross128b. I expected it to mine every ore in the radius.
#
#### What happened instead? (Attach screenshots if needed)
It mined all the ores except red zircon which was ignored
#
#### What do you suggest instead/what changes do you propose?
Add red zircon ore to blocks mined by ore drilling plant
#
#### What is your GTNH Discord username?
Pxx500

**Comment by Prometheus0000** [comment]
Does anyone know if this is a new bug? Did miners of either type pick them up before?

Also, please check latest version just in case.

**Comment by repo-alt** [comment]
perhaps it is not registered in oredictionary for some reason

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/112342732-db792780-8c98-11eb-90a2-07c2a8cd0260.png)
On 2.1.0.4

**Comment by repo-alt** [comment]
well, it is interesting if it is so in 2.1.0.0, or if miner doesn't work on 2.1.0.4

**Comment by Pxx500** [comment]
![image](https://user-images.githubusercontent.com/81298696/112356675-1ac26b00-8ccf-11eb-9af2-84946678ceca.png)
It is in the ore dictionary in 2.1.0.0

**Comment by GTNH-Afx237v7** [comment]
For me the ore drilling rig did not mine Djurleite on Ross128b. Everything else was cleared. This happened with 2.1.0.0.
However, I have the feeling that it occurs randomly, though this would need more testing.

**Comment by Sphyix** [comment]
Issues with Prasiolite on Ross128ba aswell
![WlVVnQ4gsD](https://user-images.githubusercontent.com/17811922/114296920-15766600-9aae-11eb-8fb4-b83267d15918.png)

**Comment by Prometheus0000** [comment]
Still skipping Djurleite in 2.1.0.5.
