### ISSUE TITLE
GT Metal Frame Boxes have misleading tooltip about cfoam

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#7702]
#### Which modpack version are you using?
GTNH v2.1.0.3

#### If in multiplayer; On which server does this happen? 
single player

#### What did you try to do, and what did you expect to happen?
The tooltip of GT metal frame boxes mentions that it is something that you can spray construction foam on. I interpreted this as the metal frame boxes behaving the same as IC2's wooden scaffolds, in that they provide a way to shape the spraying of construction foam by replacing in-world frame boxes with an unhardened construction foam block.

An example with IC2 wooden scaffolds:

https://user-images.githubusercontent.com/33518699/112333671-cd230f80-8c88-11eb-85d0-74a15a56601d.mp4

#### What happened instead? (Attach screenshots if needed)
Spraying construction foam on a metal frame box operates like spraying the foam on any other block, without replacing the frame box.

https://user-images.githubusercontent.com/33518699/112333854-f2b01900-8c88-11eb-8d8f-0485330deaf6.mp4

#### What do you suggest instead/what changes do you propose?
I'd suggest removing the part of the tooltip that mentions cfoam. 

#### What is your GTNH Discord username?
querns

**Comment by leagris** [comment]
Reminiscent of GT5.07 and GT5.08
GT5 Experimental 5.09 moved it to a chemical bath recipe and added more reinforced plated stone blocks.
