### ISSUE TITLE
Changed ingot temp for EBF when using different gasses

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7703]
#### Which modpack version are you using?
2.1.0.4 (also using updated versions of GT, BW, TT, NEI)
#
Some EIO ingots have different EBF temps depending on whether you use a gas or not. It's lower if you do. I don't think this was like this before, and is likely due to @bartimaeusnek 's coil changes.

Electrical steel, energetic alloy, vibrant alloy, redstone alloy, conductive iron, pulsating iron, dark steel, energetic silver, vivid alloy.
Not all are affected though.

![image](https://user-images.githubusercontent.com/8517039/112379153-2d807400-8cbe-11eb-9582-5789ff033943.png)
![image](https://user-images.githubusercontent.com/8517039/112379195-3a04cc80-8cbe-11eb-9d25-f03d36dd221f.png)

It might also affect other materials.

**Comment by Prometheus0000** [comment]
Oh, and the temp used to be different too, according to the quest.
![image](https://user-images.githubusercontent.com/8517039/112379493-9b2ca000-8cbe-11eb-857d-ec176e1df7f1.png)
Kanthal is still 2700, so I don't know why it changed.

**Comment by Dream-Master** [comment]
@bartimaeusnek i need a bit more infos here if this was changed or why it was changed. Thanks

**Comment by bartimaeusnek** [comment]
These Screenshots are from 2.0.7.5 (which is over a year old by now):

![grafik](https://user-images.githubusercontent.com/33183715/112459160-d4681d00-8d5d-11eb-8780-8e3eeb5c5409.png)
![grafik](https://user-images.githubusercontent.com/33183715/112459174-d8943a80-8d5d-11eb-9dcc-1c99a7249e0d.png)

It was not changed recently @Dream-Master.

**Comment by botn365** [comment]
i checked version 5.1
has the same temp difrence and its also there for hss-g,hss-s and hss-e
