### ISSUE TITLE
Change 9A battery buffers into 8A battery buffers

### ISSUE THREAD

**Issue by bedrill64** [GTNewHorizons/GT-New-Horizons-Modpack#7709]
The idea behind this change is that there is almost no condition when you would place 9 batteries into the 9A batbuff, because it requires at least 12A cable to be used with it, and if you wanna 12A cable, then you just can use 16A bat buffer.

My proposition is to change all 9A batbuffs to 8A ones, so you can fill its whole container without OCD being triggered and reduce the chance of overampering your 8A cables. Slot layout would be changed to 4x2, so it fits the other bat buffers:
1A- 1x1
4A - 2x2
8A - 4x2
16A - 4x4

This is not an issue of high importance, but just QoL addition if someone is willing to make this change. Also, put the RFC tag on the thread.

**Comment by alphaNOVAircraft** [comment]
Or you just block of one slot with a random item and you are fine. I dont feel like thats an issue

**Comment by Ethryan** [comment]
I usually use a stick

**Comment by bedrill64** [comment]
I mean, ofc you can do that, but if anyone has time, then there would be no need for that.

**Comment by CatsLeftEar** [comment]
4 8 16 also makes sense because number is multiplying by 2 every time

**Comment by johnch18** [comment]
But then it wouldn't be a square :(

**Comment by CatsLeftEar** [comment]
But why is it a square in first place? We have wires cables 1,2,4,8,12,16, not 1 3 6 9 16

**Comment by Savallator** [comment]
Ohh that would be so nice... it is one thing that has bothered me for a long time.
