### ISSUE TITLE
Broken recipe of stone circuit plates (Project red)

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#7710]
#### If in multiplayer; On which server does this happen? 
Official server Eta
#
#### What did you try to do, and what did you expect to happen?
Tried so smelt stone in furnace, expected no recipe to go, because there is no recipe for stone in furnace in NEI.
#
#### What happened instead? (Attach screenshots if needed)
Stone smelted into circuit plate
#
#### What do you suggest instead/what changes do you propose?
Remove imbalanced broken recipe and the normal recipe should remain 
![изображение](https://user-images.githubusercontent.com/67397297/112640278-7876c480-8e41-11eb-8910-11a60cc20f29.png)

#
#### What is your GTNH Discord username?
CatsLeftEar

**Comment by Dream-Master** [comment]
i dont understand what is wrong here?

**Comment by Ethryan** [comment]
Seems you can smelt stone into PR Circuit plate in a regular furnace if I understand this correctly.

**Comment by Impos913** [comment]
Doesn't work in 2.1.0.5

**Comment by Impos913** [comment]
![ss](https://user-images.githubusercontent.com/36479271/112650835-dc5ab680-8e5c-11eb-88b0-2691bde28cce.PNG)

**Comment by Impos913** [comment]
![ss1](https://user-images.githubusercontent.com/36479271/112650868-e41a5b00-8e5c-11eb-9030-f41bfe358d48.PNG)

**Comment by CatsLeftEar** [comment]
> 
> 
> Doesn't work in 2.1.0.5

try electrical furnace. Normal doesnt work here either

**Comment by Impos913** [comment]
Oh it worked

**Comment by CatsLeftEar** [comment]
So instead of compressing stone dust in plates, making wiring in laser engraver and using forming press, you can just throw some stone in furnace and get 2 circuits for 1 stone. This needs fix

**Comment by GTNH-Afx237v7** [comment]
The ProjectRed script file contains seven `furnace.remove` instructions, out of which six work fine. 
The a.m. circuit plate is the only `furnace.remove` recipe that does not work. I tried `furnace.remove(<ProjRed|Core:projectred.core.part>, <*>)` which was supposed to remove all furnace recipes that have any input and result in the circuit plate as output. Unfortunately that did not work, i.e. you can still get the circuit plates as mentioned above. I also tried `furnace.remove(<*>, <minecraft:stone>)` that is supposed to remove any furnace recipe that uses `minecraft:stone` as its input. Sadly this did not work either, still the same as mentioned above.
You can also get the circuit plates by inputting stone in the multi smelter, but not in an IC2 iron furnace or a Natura nether furnace. The IC2 furnace will not accept `minecraft:stone` as input; the Natura furnace will accept it as input but will not perform an operation.

**Comment by Solotov0** [comment]
Not sure if this was worked on specifically since, but 2.1.2.2.Dev2 has lost all recipes for this stone circuit 10341

**Comment by mitchej123** [comment]
> Not sure if this was worked on specifically since, but 2.1.2.2.Dev2 has lost all recipes for this stone circuit 10341

fixed, again.

**Comment by YannickMG** [comment]
And I believe the core issue here (furnace recipe in multismelter) is fixed as I couldn't reproduce it. Please correct me if it's still reproduceable.
