### ISSUE TITLE
RFC: ore dict card for AE2

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#7712]
Add new card for AE2, opening by RMB with card on hand, with interface looks like ore dict export bus. This card can work with export, import, storage buses. if this card installed, bus work with construction from card and ignore gui filter.

#
#### What is your GTNH Discord username?
Rait_GamerGR

**Comment by johnch18** [comment]
So you want ore dict IO in import buses and storage buses?

**Comment by RaitGamerGR** [comment]
> So you want ore dict IO in import buses and storage buses?

Yes

**Comment by repo-alt** [comment]
Current intention is to implement it like fuzzy card, so that the filter is the property of a bus, not the card item itself. (Because card item is not really a good place to store data)
Also I think having this card installed will disable usual item list filter.
Recipe suggestions are welcome.

**Comment by GTNH-Afx237v7** [comment]
So we could now place this card on a storage bus and no longer need storage bus on GT type filter combination?

**Comment by repo-alt** [comment]
kind of

**Comment by repo-alt** [comment]
Build for testing
[appliedenergistics2-rv3-beta-45-GTNH.jar.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6300543/appliedenergistics2-rv3-beta-45-GTNH.jar.zip)

**Comment by GTNH-Afx237v7** [comment]
Two small visual things:

Text extends over GUI box
![grafik](https://user-images.githubusercontent.com/64365566/114506686-70d16100-9c32-11eb-9c85-e51eca783d5d.png)

Is the gap between the **T** icon and the four buttons above intended?
![grafik](https://user-images.githubusercontent.com/64365566/114506841-9eb6a580-9c32-11eb-841f-e1892b9c2a15.png)

Is this card meant to be used exclusively? Seems it is not treated equally when a storage bus has other configured items in it as well (or maybe I am doing sth wrong).

But all in all, first testing on my little ore processing looks good - will filter according to ore dictionary, works when the storage bus is both on the main network and on a P2P subnet.
Will also accept `dustSmall* | dustTiny*` in an export bus and happily do it's thing.

Bye bye EC2 ore dictionary export bus, I dare say.

**Comment by repo-alt** [comment]
The gap is where fuzzy card control is rendered. I'll look if it is possible to set them both in the same place.
Oredictionary overrides all other filters, I think it was clearly stated in the initial post, and in my "design document". I'll see if it would be possible to disable filter slots w/o too much pain.

**Comment by GTNH-Afx237v7** [comment]
Must have missed the override property, it was early today and I didn't have my coffee yet...

**Comment by GTNH-Colen** [comment]
How does this compare lag wise to the ore dict bus?

**Comment by GTNH-Afx237v7** [comment]
I didn’t notice anything immediate, but have also not done extensive testing.

**Comment by repo-alt** [comment]
Lag-wise it is the same as oredictionary export bus I think, but it does not use much time by itself. Most of the time is just extracting stuff from the network, which is not really avoidable.

**Comment by repo-alt** [comment]
[appliedenergistics2-rv3-beta-45-GTNH.jar.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6306533/appliedenergistics2-rv3-beta-45-GTNH.jar.zip)
Some UI fixes

**Comment by GTNH-Afx237v7** [comment]
Not sure about the transfer speed of the ore dictionary export bus, I believe it is 1 stack/tick max?
The AE storage bus with ore dictionary card can handle how many stacks/tick?

**Comment by repo-alt** [comment]
Storage bus by itself does not have any limits I think

**Comment by repo-alt** [comment]
This is also related
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/46
