### ISSUE TITLE
Make the coremod deploader remembering that he has already downloaded everything after the first start

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7714]
The deploader used to download custom mods on twitch will redownload every mod missing in the mods folder, which makes testing new stuff like trying out the new nei version a pain for the players.

So i'm suggesting to make the deploader remembering if he already downloaded the custom mods and only try to download the mods until the first successful boot.

**Comment by Prometheus0000** [comment]
Does it have a config file? It could just change something in it after successfully loading if it does.
