### ISSUE TITLE
Crash on loading into world

### ISSUE THREAD

**Issue by AJFelidae** [GTNewHorizons/GT-New-Horizons-Modpack#7720]
#### Which modpack version are you using?
2.1.0.5 Beta
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
I loaded a new world, and I crashed shortly after entering with a lot of lag. Logs are at https://pastebin.com/pYGe8MN7.
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
WarriorAvi#0249

**Comment by leagris** [comment]
Client crashed while rendering an arrow inside a Quiver held by SpecialMobs Giant Skeleton entity
`Entity Type: SpecialMobs.GiantSkeleton (toast.specialMobs.entity.skeleton.EntityGiantSkeleton)`

wearing a BattleGear Quiver:
`at mods.battlegear2.client.model.QuiverModel.render(QuiverModel.java:85)`
with an arrow to render:
`at mods.battlegear2.client.utils.BattlegearRenderHelper.renderArrow(BattlegearRenderHelper.java:690)`

Bad luck incompatible mods patching entity renderer to make special mobs out of vanilla skeleton models, but patch is incompatible with the rendering of models from battlegear2, probably incompatible with rendering GT Arrows models inside a quiver in this specific condition.

Ask a server moderator or admin to cleanup the specialmob entitities in your area so you can login again.

**Comment by boubou19** [comment]
I see you have optifine installed. Make sure your chunk loading option is set on default, because smooth chunkloading and multicore chunkloading are known to cause `Already tesselating` crashes. It is known to change on its own after you changed your gui scale.
