### ISSUE TITLE
Invalid Ore Dictionary gravel

### ISSUE THREAD

**Issue by TA0MACHINE** [GTNewHorizons/GT-New-Horizons-Modpack#7723]
Version 2.1.0.0 23.12.2020
multiplayer: Eta
when you receiving byproduct from cobblestone in SAG MILL Ender IO - Gravel, it's Invalid Ore Dictionary
TAO#4382
![3cnR44cHm9](https://user-images.githubusercontent.com/42874669/112850242-81220180-90b2-11eb-9288-0b1d863e7365.gif)

**Comment by repo-alt** [comment]
Doesn't look like a visual bug

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/116133515-cd099b80-a69c-11eb-8d06-451fbf2a633e.png)
Tested.

**Comment by Prometheus0000** [comment]
Name remover fixes it. Try exporting it to that automatically until/if it gets fixed.

**Comment by repo-alt** [comment]
I wonder what is that tag
