### ISSUE TITLE
Recipe maps don't recognize industrial diamonds

### ISSUE THREAD

**Issue by greesyB** [GTNewHorizons/GT-New-Horizons-Modpack#7724]
#### Which modpack version are you using?
2.1.0
#
#### If in multiplayer; On which server does this happen? 
Private server, reproducible in single player
#
#### What did you try to do, and what did you expect to happen?
Tried automating industrial diamond -> flawless -> exquisite with laser engraver.
#
#### What happened instead? (Attach screenshots if needed)
Industrial diamonds cannot be automatically inserted into a laser engraver. I tried conveyor, item conduit, and AE interface. Manually inserting industrial diamonds runs the recipe just fine, resulting in 3 industrial -> 1 flawless.

The same is true for implosion compressor input bus, but you can get around this by disabling input filter of bus.

#
#### What do you suggest instead/what changes do you propose?
Implosion compressor and laser engraver should recognize industrial diamonds as valid inputs.

Worth noting that compressors do recognize industrial diamonds as valid inputs (for blocks), so this is not an issue for every recipe map
#
#### What is your GTNH Discord username?
Greesy

**Comment by Glease** [comment]
Try if disabling the input filter of input bus (right click with screwdriver) works.

**Comment by greesyB** [comment]
> Try if disabling the input filter of input bus (right click with screwdriver) works.

Thanks! I didn't know about that feature, updated the parent comment to focus on laser engraver.

**Comment by Glease** [comment]
Actually, both thing can disable input filtering. It should be in 2.1.0.2+.

**Comment by Glease** [comment]
Even though there is a workaround, finding out exactly why it doesn't acceot the industrial diamonds is still of some interest.
