### ISSUE TITLE
Bioware boards requiring UV circuits cuts into usability

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7727]
At present, for every 32 bioware processor boards, you need 1 UV circuit. Assuming the player is using the bioware line for UV circuits, this means that every 32 boards requires 3 boards, reducing the "efficiency" of the recipe by 9.4%. Were the boards to change to use ZPM circuits, you would need 1 circuit per 32 boards, this would make the efficiency loss 3.1%, with requiring LuV circuits costing "nothing".
I think reducing the recipe to LuV would be the best course of action, and would mirror Wetware circuits requiring an IV circuit in the form of a sensor.

**Comment by alphaNOVAircraft** [comment]
I think the current version is fine, it was already buffed last patch and seems quite fine to me atm. Overall Bioware is the most expensive circuit line and is supposed to be expensive

**Comment by Florexiz** [comment]
I don't like entire concept when you need circuits of same or higher tier then you making
