### ISSUE TITLE
Quests for Q-Suit should be clear you need IV assembler

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#7729]
#### Which modpack version are you using?
2.1.0.5
#
The Q-Suit is an upgrade to the NanoSuit, and thus uses the nanosuit in the crafting. Cool.

It takes multiple steps, and there are quests to guide you along each step, like many chem quests. Cool.

The first steps are possible at EV (and first quests open up), which turn the useful NanoSuit into the unusable plated parts. Finishing the process to get wearable gear needs IV. Not cool.

#
#### What do you suggest instead/what changes do you propose?
Either gate the quests behind having the appropriate tier of assembler to finish the Q-Suit, or at the very least put a text warning in the quests that you'll need an IV assembler to finish the Q-Suit.

#
#### What is your GTNH Discord username?
NeroOneTrueKing

**Comment by greesyB** [comment]
I'd also suggest mentioning that the quantum chest doesn't keep the flight capabilities of advanced nano chest, making it not worth making for many until gravichest (post assline)

**Comment by johnch18** [comment]
I feel like one should be in the habit of checking voltages whenever checking recipes.

> I'd also suggest mentioning that the quantum chest doesn't keep the flight capabilities of advanced nano chest, making it not worth making for many until gravichest (post assline)
It does, though. GregTech adds flight to the qchest.

**Comment by greesyB** [comment]
> It does, though. GregTech adds flight to the qchest.

How are you meant to use it? I have a quantum chest and it certainly doesn't have the same controls as advanced nano chest.

**Comment by johnch18** [comment]
Mode switch + Space IIRC. I know for a fact I've done it in this pack this version, I just can't remember the keybinds offhand.

**Comment by greesyB** [comment]
Ah, figured it out. Mode switch + space for hover, which does nothing unless you have jetpack on, which is sprint + mode switch. Not sure why it doesn't use the gravi fly key like the nano chest does.
