### ISSUE TITLE
Rocket pollution values

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#7730]
#### Which modpack version are you using?

#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)
I made this proposal in discord before, but it didn't get much attention, and now since single block scrubbers are being disabled, it's even more relevant.

For rocket pollution numbers, the higher tiers get out of hand. The current pollution function is 10,000 x 2^(tier-1) per second (as of dev versions, in 2.1.0.0 it's 10,000 x 2^tier). The launch times are around 30s except for T1 which is 60s.
So the numbers are approx:
T1 - 600,000
T2 - 600,000
T3 - 1,200,000
T4 - 2,400,000
T5 - 4,800,000
T6 - 9,600,000
T7 - 19,200,000
T8 - 38,400,000
#
#### What do you suggest instead/what changes do you propose?
I propose they be made into a non-exponential function - 10,000 x Tier
This makes the numbers:
T1 - 600,000
T2 - 600,000
T3 - 900,000
T4 - 1,200,000
T5 - 1,500,000
T6 - 1,800,000
T7 - 2,100,000
T8 - 2,400,000
#
#### What is your GTNH Discord username?
KiloJoel

**Comment by boubou19** [comment]
Single block scrubbers are getting disabled, but did you see the new electric air filter numbers?

**Comment by KiloJoel** [comment]
Ah, yes, I see them now. I was going off people's existing concerns in the scrubber issue. They're exponential like the current rocket values, so that does mirror the current rocket values.

However since the multi scrubber needs infrastructure and is not simple to set up, this limits you to launching only in the chunk you have your scrubber in right? And doesn't address the pollution created on the planet. Might be a big issue for people with bases not in the overworld

**Comment by boubou19** [comment]
what's the delay before the pollution spread to the neighboor chunks and what's the amount moved/leftover in chunks?

**Comment by bedrill64** [comment]
It checks if the pollution value is greater than 400,000 every 1200 ticks. If it is, then it finds each neighboring chunk (not diagonals). For each neighboring chunk, the controller first decides if the pollution can be spread to that chunk. If the pollution of the neighbor times 6, is less than the current chunk's pollution times 5, then it is a valid chunk to spread to, if not then nothing happens with that neighbor.

**Comment by boubou19** [comment]
because of the lenght of the pollution cycle, it will spread only once at maximum, while it seems to be fine for early rocket tiers, that just sucks to have a T8 with such pollution values. Linear values seems better, but on the other hand, with the buff of the electric air filter, you can always burry one near the bedrock, because the pollution is not taking the Y level into account.

**Comment by boubou19** [comment]
i just said a work around, never said it was a proper solution

**Comment by alphaNOVAircraft** [comment]
wasnt ment as a attack against you boubs <3 

But that pollution change was ninjad in by bart, noone thinks it should be there, it doesnt even server that anyways questionable purpos of pollution and noone was asked / wanted to see it. Just remove it.

**Comment by botn365** [comment]
the polution added to the rocket onlymakes the game worse these numbers should be reduced a lot defnetly for the higer tiers

**Comment by leagris** [comment]
Please refer to [[RFC] Disable Pollution and re-work the mechanic #7341](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7341)

**Comment by Dream-Master** [comment]
i would say make t2 a bit more than t1 so maybe 750,000

**Comment by KiloJoel** [comment]
The reason t2 and t1 are the same is because t1 takes twice as long to launch

**Comment by Glease** [comment]
@Dream-Master We need a way to fix the pollution caused by rockets, so people don't build a nice launch platform, then immediately abandon it after one launch due to smog.

**Comment by Dream-Master** [comment]
sure ik. But like in real life rockets need to make some pollution and you dont have to start it in the middle of your base. I am ok with the other values. Sure we need to test it first and see if this is balanced.

**Comment by alphaNOVAircraft** [comment]
> The reason t2 and t1 are the same is because t1 takes twice as long to launch

wouldnt that mean that t1 produces more pollution then t2!? So the exact opposite of dreams request o.O xD

**Comment by Dream-Master** [comment]
that make no sense. so maybe we need to reduce t1 and let t2 at 600

**Comment by KiloJoel** [comment]
> 
> wouldnt that mean that t1 produces more pollution then t2!? So the exact opposite of dreams request o.O xD

No, T1 makes 10,000/s for 60s, and T2 makes 20,000/s for 30s. This is the case with the current implementation and my proposed new one.

**Comment by alphaNOVAircraft** [comment]
> sure ik. But like in real life rockets need to make some pollution and you dont have to start it in the middle of your base. I am ok with the other values. Sure we need to test it first and see if this is balanced.

noone has to, but if ppl are able to they will spend some time on a cool looking launch pad and not just move over 5 chunks to spare them with the pollution. (And building a real launch pad is much more realistic then starting a moon or even higher rocket from the middle of nowhere without and building or any notable structures that could act as "fake launch infrastructure"

**Comment by KiloJoel** [comment]
I guess it would be doable to make a special case for T1 or T2, though I think it's probably not very important/impactful to do so

**Comment by Savallator** [comment]
This is still a problem and it is really stupid to have several millions of pollution everytime a T8 rocket is launched...

**Comment by bombcar** [comment]
With pollution as it is it NEVER Makes sense to launch higher than T3 really, launch T1 to the moon, and launch your big pollution machine from them.

**Comment by Savallator** [comment]
Yeah, because i totally want to go through 2 Planet selection screens, and wait for 2 launches...
Imho the rocket pollution should cap out in a way that, give the chunk has 0 pollution at launch, it should not really exceed the sour rain limit (2M) by much. I mean, a single launch should not screw up the world. This is made worse by the fact that the pollution visuals never disappear even when the chunk is quickly cleaned by an air filter (#9145), so everytime a rocket is launched i need to restart the game...

**Comment by bombcar** [comment]
2 Million as a maximum makes sense to me; or perhaps limit pollution to 2 million or less if you launch from a "new launch Multiblock" if we wanted to add content.

**Comment by leagris** [comment]
When the ingredients are mouldy and covered with maggots, it is no longer the time to discuss the merits of the recipes for preparing a meal.

Pollution is irremediably broken in code, inconsistent because it still has no clear mission statement. This makes any balance discussion totally moot.

**Comment by Sphyix** [comment]
> Pollution is irremediably broken in code, inconsistent because it still has no clear mission statement. This makes any balance discussion totally moot.

What do you mean?
Pollution was clearly enabled back with the multiblock air filter to be a power sink :)
I can't find any other explanation for it.

Anyway @Savallator you can disable pollution client-side from Gregtech configs, and if you are really annoyed at it cause it clearly makes no sense and still doesn't add anything to the gameplay, it can be totally disabled

**Comment by boubou19** [comment]
> Pollution was clearly enabled back with the multiblock air filter to be a power sink :)

lmao 1 iv amp to keep up with all my pollution at UEV isn't that much of a power sink

**Comment by Sphyix** [comment]
Then i don't have an explanation on why pollution was enabled again

**Comment by FavoritoHJS** [comment]
From what I've heard, it's so the team can know more about the million and one ways it's FUBAR.
