### ISSUE TITLE
Singleblock machines not limiting unique item inputs to 1 stack

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#7732]
#### Which modpack version are you using?
2.1.0.5
#
#### What did you try to do, and what did you expect to happen?
I hook up a singleblock chemical reactor to an EnderIO conduit. I want one slot filled with item A, the other slot filled with item B.
This issue also occurs piping in items with a GT conveyor module, or with GT pipes, or with item translocators that aren't deliberately using the diamond nugget regulators. I have not tested other item piping methods.

#
#### What happened instead? (Attach screenshots if needed)
My GT machine is not using the "only accept 1 stack of each type of item" logic and I don't know how to turn it back on. Breaking and replacing the machine only sometimes works??
![image](https://user-images.githubusercontent.com/28197216/113184622-07f1ee00-921b-11eb-947b-ded4442ba70d.png)

#
#### What do you suggest instead/what changes do you propose?
I think there was previous "only accept 1 stack of each type of item" behaviour that is somehow not working. Or something. I'd like either a good workaround or a fix.

Robot arms are able to regulate input to go only into a single place, but this makes the singleblock machine less space-efficient, since I need to dedicate one face per input slot instead of sharing one face for all input slots.

#
#### What is your GTNH Discord username?
NeroOneTrueKing

**Comment by Glease** [comment]
Sounds like a problem of disabled input filter. Will check what I can do here when I got time.

**Comment by Florexiz** [comment]
Now input filter disabled by default. You can enable it with shift + rmb with screwdriver

**Comment by NeroOneTrueKing** [comment]
Thank you, this was it!

**Comment by KiloJoel** [comment]
While not a bug, this does highlight that it's probably not obvious enough that input filter can be turned on. Especially for new players which don't know it even exists.

**Comment by Prometheus0000** [comment]
Add a ticket for a text addition to a quest or a new quest.

**Comment by Glease** [comment]
If someone can get me a few good icon I can add them to GUI.

**Comment by Glease** [comment]
A disabled input filter should not allow multiple stack of same item. This is not the original intention of this feature. I'll see if I can make this part work without ruining the original intention, i.e. let items in without fluid.
