### ISSUE TITLE
Conflicting Ztones recipes

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7736]
#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Craft some of the ztones blocks (iszm, agon, korp). Almost every block except few
#
#### What happened instead? (Attach screenshots if needed)
Each restart (?) recipe gives different subtype of the block because they all have same recipe making crafting of them quite... unpredictable
#
#### What do you suggest instead/what changes do you propose?
Disable shaped recipe for every block except default with 0 number. They still have ofanix and chisel recipes to convert from one to another
#
#### What is your GTNH Discord username?
FalseColor

**Comment by Prometheus0000** [comment]
They look fine to me? Can you post some pictures of what you mean? So I don't have to restart a bunch to try to figure out what you mean.

**Comment by Florexiz** [comment]
Its hard to make picture of it. Just same recipe return different result on unknown reason
![image](https://user-images.githubusercontent.com/29033773/113348510-57c9d580-933f-11eb-98e6-47136afa80d5.png)
![image](https://user-images.githubusercontent.com/29033773/113348534-5ef0e380-933f-11eb-89f2-935daf099ff8.png)
![image](https://user-images.githubusercontent.com/29033773/113348711-9e1f3480-933f-11eb-890d-ecdfe81bcb35.png)

You cant be sure which one you craft, each restart (I guess? not sure when it changes) it give you different result

**Comment by Florexiz** [comment]
Cycling works only when already made

**Comment by Prometheus0000** [comment]
I see, I was thinking it had something to do with the Ofanix recipes.

**Comment by KiloJoel** [comment]
I've noticed significant lag associated with these recipes because of the overlap, I think a good solution would be to remove all recipes except the one for the 0 version of each

**Comment by GTNH-Afx237v7** [comment]
Reminds me of this issue: #7488
Where it was/is not possible to craft specific fence type due to recipe acceleration

**Comment by Prometheus0000** [comment]
Just how significant is this lag? And when does it occur? Startup? World load? Checking the recipes?

I have assember recipes for all of them, and they can be chiseled, but you can't remove the non-ofanix recipes without removing the ofanix recipes using MT, and I don't know another way to do it. And it's not OS, so it would be difficult to mess with it internally.

I'd like to know if we really need to remove the normal crafting recipes or not.

**Comment by KiloJoel** [comment]
> Just how significant is this lag? And when does it occur? Startup? World load? Checking the recipes?

The lag that I experienced was when crafting them, it's especially noticeable when shift-click crafting a stack at a time

**Comment by boubou19** [comment]
was it made from a AE terminal or through normal crafting grid? because AE tends to lag the server when doing shift clicks to craft stacks at once.

**Comment by KiloJoel** [comment]
Normal crafting grid

**Comment by Florexiz** [comment]
Issue is still present in 2.1.1.4 QF2
Every block type is still crafted same way
![image](https://user-images.githubusercontent.com/29033773/140640910-efda290b-6cf8-4d13-ad75-e82ef723aa91.png)
![image](https://user-images.githubusercontent.com/29033773/140640920-b1b6bd6b-21aa-4d35-8b6f-ac488cf3b634.png)

**Comment by Chaoschaot232** [comment]
Is also still there in 2.1.2.3qf and also I am not sure, why the Hardened Clay recipies outputting 16 Cray Blocks. I mean ok, free Blocks for everyone but shouldn't this be 8 since only 8 BLocks are consumed?

![image](https://user-images.githubusercontent.com/1703441/159587416-e8aa2aa0-e3f3-4b0e-8efa-cd88d53a34d9.png)

![image](https://user-images.githubusercontent.com/1703441/159587438-8e83b518-b560-40b3-a20a-56a50eb39603.png)
