### ISSUE TITLE
Witchery crashes Server

### ISSUE THREAD

**Issue by Ubus99** [GTNewHorizons/GT-New-Horizons-Modpack#7739]
#### Which modpack version are you using?

#2.1.0.0
#### If in multiplayer; On which server does this happen? 

#Private
#### What did you try to do, and what did you expect to happen?

#I put Oak Saplings into a Witches Oven, i expected the recipe to work
#### What happened instead? (Attach screenshots if needed)

#Complete server-Crash
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6246502/latest.log)

#### What do you suggest instead/what changes do you propose?

#Ubus99

**Comment by Prometheus0000** [comment]
Known. Update to 2.1.0.1 or later.

**Comment by Ubus99** [comment]
where do i get 2.1.0.1? its not on Curseforge

**Comment by Prometheus0000** [comment]
Discord.
