### ISSUE TITLE
no interaction with T.F.F.T Multi I/O hatch 

### ISSUE THREAD

**Issue by TA0MACHINE** [GTNewHorizons/GT-New-Horizons-Modpack#7742]
Version 2.1.0.0 23.12.2020
multiplayer: Eta
T.F.F.T Multi I/O hatch not active. I can't turn it with a wrench. It always faced down.
![NW5kHl](https://user-images.githubusercontent.com/42874669/113394885-b162ec00-93a1-11eb-8dfd-90519f3cec0b.png)

TAO#4382

**Comment by Prometheus0000** [comment]
Did you try attaching a conduit/fluid storage bus to it? Or updating to latest?

**Comment by TA0MACHINE** [comment]
When it in TFFT I can't rotate it to ME fluid bus
![xFNXzp](https://user-images.githubusercontent.com/42874669/113396606-71e9cf00-93a4-11eb-8a54-e473b3a0ab77.png)

**Comment by Prometheus0000** [comment]
Does it not work if you don't do so though? I don't think the rotation of a bus has anything to do with something else interacting with it.

**Comment by TA0MACHINE** [comment]
when you put in ME fluid terminal cell and try to fill with liquid from TFFT nothing happens

**Comment by Prometheus0000** [comment]
That sounds like EC2 lacking functionality rather than being a bug in the TFFT. Consider using conduits and having them go to separate buffer tanks or something.

**Comment by TA0MACHINE** [comment]
can I put T.F.F.T Multi I/O hatch instead bottom TFFT casing no loss of fluids and will it work?

**Comment by botn365** [comment]
same bug that couses the crashing already fixed

**Comment by Glease** [comment]
@botn365 so fixed in dev?
