### ISSUE TITLE
Quantum Tank/Chest Controller (RFC)

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7745]
I just want some feedback regarding the idea of a "quantum controller", a block that allows interfacing with multiple super/quantum chests/tanks at once. #7445 
1. Would you want tanks and chests to have different controllers
2. Would you want the tier of the controller to influence the amount of objects it can interface with? If not please provide a suggestion.
3. Were you to be against this, what is your reasoning?

**Comment by alphaNOVAircraft** [comment]
Before adding a Controller for QC we should once again try to find the issue with saving of their contents, otherwise QC are voiding duping coinflip devices, which shouldnt really be used imo. (They are unpredictable)
See #7051

**Comment by johnch18** [comment]
@alphaNOVAircraft could [this commit ](https://github.com/GTNewHorizons/GT5-Unofficial/commit/ffbec810bd1b0d66d820e80e3288507a1ea3f082) have any impact?

**Comment by johnch18** [comment]
I think code-wise it wouldn't be impossible, multiblocks link their IO stuff together all the time.

**Comment by alphaNOVAircraft** [comment]
Dont think so, it was an issue before as well, even tho the linked issue says AE2 it does happen without it as well, just was the scenario i noticed it the first time. 
the linked commit is way later then the original issue

**Comment by johnch18** [comment]
What's the source of the lag

**Comment by johnch18** [comment]
More than anything, let's pretend we live in a hypothetical universe where whatever code gets implemented is flawless. What settings / behaviors / parameters would you want

**Comment by alphaNOVAircraft** [comment]
Different tiers would be nice, could increase the range of the controller (so tier 1 = hv = 4 blocks reach, 2 = iv = 8, 3 = zpm = 16 blocks radius Smth like that

**Comment by johnch18** [comment]
What sort of scaling would you recommend?

**Comment by GTNH-Colen** [comment]
> Different tiers would be nice, could increase the range of the controller (so tier 1 = hv = 4 blocks reach, 2 = iv = 8, 3 = zpm = 16 blocks radius Smth like that

I would be against radius as that quickly gets absurd, limiting a tier to say 4 chests, 8 chests etc would be reasonable though

**Comment by GTNH-Afx237v7** [comment]
1. Yes pls different controllers for tanks and chests
2. No final idea yet; if it’s meant to optimize performance I believe it should not be tiered
3. Not saying that I am against it - just in the light of the recent implementation by repolainen for a non-ticking AE handler, which is supposed to make interaction between chests and storage busses as good in performance as pre-formatted storage cells, if the controller is eventually necessary? 

Regarding a tank controller, I wonder how this should work? When using AE and fluids, there is either ExtraCells or Fluid P2P - would like to hear (and discuss) on how it works.

**Comment by johnch18** [comment]
Not to imply any intent on my part but,  almost wonder if it would be more productive to backport AE2 1.12 fluid handling than fix EC2

**Comment by GTNH-Afx237v7** [comment]
No clue how it is done in later versions of AE2... Never went past 1.7.10. From personal experience, ExtraCells is messy, sometimes extremely laggy, tends to occasionally dupe/void stuff... 
It has also been mentioned to salvage the large capacity storage/crafting components from EC2 and scrap the mod altogether, especially with how good fluid P2Ps are.

**Comment by johnch18** [comment]
My todo list requires me to bumblef*ck around with AE2's API so I'll do my best

**Comment by Prometheus0000** [comment]
As far as a tank controller goes, wouldn't it be better to just add more tiers to the TFFT, and make sure it's not buggy (if it is)? I mean, this is what it's for.

**Comment by johnch18** [comment]
A tank controller would still have use cases for when someone doesn't necessarily want to build a large multi for their fluids. A small array of QTs (uwu) and a controller could be great for LCR setups
