### ISSUE TITLE
New mod suggestion : FPS Reducer

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7749]
Fits perfectly for GTNH and AFK-ing / atl tabing a lot

https://www.curseforge.com/minecraft/mc-mods/fps-reducer

**Comment by mitchej123** [comment]
Lol, I always disable this on any pack that ships it, since I alt tab out a lot.  I wouldn't mind including a link for it, or shipping it disabled by default though.

**Comment by Alexdoru** [comment]
How does it bothers you if you are alt tabing ?

**Comment by Dream-Master** [comment]
ARR better not.

**Comment by mitchej123** [comment]
> How does it bothers you if you are alt tabing ?

I play windowed on multi monitor: one screen dedicated to MC, one for music, and one for web.  It's hugely distracting when it starts stuttering on the MC window.

**Comment by mitchej123** [comment]
> ARR better not.

Also this.  I'd prefer an OSS license (MIT, GPL, etc)

**Comment by Alexdoru** [comment]
> > How does it bothers you if you are alt tabing ?
> 
> I play windowed on multi monitor: one screen dedicated to MC, one for music, and one for web. It's hugely distracting when it starts stuttering on the MC window.

I see, I am a one monitor peasant so this mod is really good to cut useless load on GPU and also the fact that it turns off the sound is handy. I can leave the game open and do someting else with minimal impact on my computer

**Comment by glowredman** [comment]
> I wouldn't mind including a link for it

It's linked on the wiki page, which is mentioned early in the quest book

**Comment by Prometheus0000** [comment]
There's no mention of optional mods though, but that can be added.

**Comment by Prometheus0000** [comment]
I mentioned optional mods in the QB, but do we want mod this or no?
