### ISSUE TITLE
Singleplayer crash

### ISSUE THREAD

**Issue by TA0MACHINE** [GTNewHorizons/GT-New-Horizons-Modpack#7750]
Version 2.1.0.0 23.12.2020
singleplayer
My SP began crashes even if i didn't build anything. After saving world and re enter in SP world. 
![uxC6f5](https://user-images.githubusercontent.com/42874669/113491544-4832c400-94da-11eb-85d5-9daa5282cb05.png)
[crash-2021-04-03_23.56.22-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6253433/crash-2021-04-03_23.56.22-client.txt)
Can some one indicate the reason?
TAO#4382

**Comment by johnch18** [comment]
Please post a pastebin to the full log.

**Comment by boubou19** [comment]
well the crashlog is already provided as a text file

**Comment by johnch18** [comment]
Damn, if only I had angled my eyes 2 degrees upwards.

**Comment by TA0MACHINE** [comment]
happens if you disconnect from the server and try to load a single player game. Loaded only after a complete reboot of the launcher.

**Comment by TA0MACHINE** [comment]
Hello again, I hope there will be solution or fix, it's really annoying always reboot launcher when I need test something in SP

**Comment by GTNH-Afx237v7** [comment]
It shows the following error entity: 
Particle: FXWisp, Pos (-11500.500195313245,77.5,7436.499804686755) 
have you tried going to this location and looking for what may be wrong?
Does is always crash with the same error message?

**Comment by TA0MACHINE** [comment]
yes, always....
And if I making new world the same
