### ISSUE TITLE
Boots of the comet breaking the Twilight Forest's portal

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7751]
#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
Zeta.
#
#### What did you try to do, and what did you expect to happen?
I entered the twilight forest.
#### What happened instead? (Attach screenshots if needed)
The portal turned into ice.
![2021-04-03_19 41 35](https://user-images.githubusercontent.com/57275066/113496720-d2772a00-94d2-11eb-90ba-581ff872e12f.png)
![2021-04-03_22 23 30](https://user-images.githubusercontent.com/57275066/113496721-d30fc080-94d2-11eb-8e35-62a59b248202.png)

**Comment by GTNH-Afx237v7** [comment]
Boots of the comet will temporarily turn water into ice - do the ice blocks turn back into water, or even into the portal Blocks? From the images it looks like these are two separate portals?

**Comment by maniifestantes** [comment]
It turns back to the water, the boots turn water into ice when you're near it.
Yeah they're two different portals. Both broke.
