### ISSUE TITLE
Neutron reflector parts dupe

### ISSUE THREAD

**Issue by Mr-Vovikpro123** [GTNewHorizons/GT-New-Horizons-Modpack#7752]
Version 2.1.0.0
Singleplayer

I tried to craft "small neutron reflector parts" and "neutron reflector parts" in assembler

Assembler consumed only 1 part instead of 5( for small neutron reflector parts) and 8(for neutron reflector parts) as written in nei.

https://user-images.githubusercontent.com/64985356/113516601-c8613400-9583-11eb-8a5b-f9bfd807ff90.mp4

Discord username: A3W10

**Comment by Prometheus0000** [comment]
Try again in latest first.

**Comment by Prometheus0000** [comment]
See #3962, #6693, #6719. Dream added recipe which _do not work_ as I stated previously.
