### ISSUE TITLE
Change Avaritia's Matter clusters

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7753]
#### What did you try to do, and what did you expect to happen?

So basically when you mine with an infinty avaritia tool instead of droping all the items on the ground it drops a matter cluster that contains all the items. A matter cluster can contain up to 16384 items (256 stacks).
To retrieve the items you have to right click the matter cluster and all items are dropped on the ground, 256 stacks dropped on the ground, it makes enormous lag.

![image](https://user-images.githubusercontent.com/57050655/113516672-dad76f80-957b-11eb-8c96-c3f2134a5496.png)
![image](https://user-images.githubusercontent.com/57050655/113516679-e460d780-957b-11eb-9245-185ba3cd3b48.png)

#

#### What do you suggest instead/what changes do you propose?
Quick fix : change the maximum size of a matter cluster to 4096 items (this is done in latter versions of avaritia)
Tedious fix : add a new block that can deconstruct the matter cluster and export the items to its inventory so then you can pull the items out and export them to wherever you want ? With a GUI looking like this perhaps idk 

![image](https://user-images.githubusercontent.com/57050655/113516843-cf387880-957c-11eb-80c1-d336f5c2624b.png)

**Comment by johnch18** [comment]
We should make drawers and super buffers drop these

**Comment by Prometheus0000** [comment]
Why would you use this instead of a MBM or VM? You have to be UHV to even get it, I don't really see any point in spending time on this.

**Comment by Alexdoru** [comment]
> Why would you use this instead of a MBM or VM? You have to be UHV to even get it, I don't really see any point in spending time on this.

Right now when using avaritia tools you just have to forget about the blocks you just mined because if you try to open a matter cluster it will drop 256 stacks on the ground and freeze the game for a 1-2 minutes and just kill server TPS.

Just changing the max size of a cluster to 64 stacks would be cool and should be a quick fix :)

**Comment by boubou19** [comment]
>Right now when using avaritia tools you just have to forget about the blocks you just mined because if you try to open a matter cluster it will drop 256 stacks on the ground and freeze the game for a 1-2 minutes and just kill server TPS.

Not always true, the officials can tank this quite well, and it's player's responsability to use something to collect the droped items on the ground when you unbox the items.

**Comment by Alexdoru** [comment]
changing this to 64*64 should do the trick : https://github.com/GTNewHorizons/Avaritia/blob/4410de6daaca9816882395e5741228995801d1e2/src/main/java/fox/spiteful/avaritia/items/ItemMatterCluster.java#L40

that's the file from latter versions :

https://github.com/SpitefulFox/Avaritia/blob/master/src/main/java/fox/spiteful/avaritia/items/ItemMatterCluster.java

**Comment by Alexdoru** [comment]
> > Right now when using avaritia tools you just have to forget about the blocks you just mined because if you try to open a matter cluster it will drop 256 stacks on the ground and freeze the game for a 1-2 minutes and just kill server TPS.
> 
> Not always true, the officials can tank this quite well, and it's player's responsability to use something to collect the droped items on the ground when you unbox the items.

I have a room with annihilation planes on the ground and when I open one it freeze the game for 1-2 mins and kills TPS and I don't have a cheap computer. No wonder they changed it in later versions

**Comment by boubou19** [comment]
Well must be the annihilation planes then, because i can assure you that an ender collector can tank many matter clusters, and is basically limited by the attached storage.

**Comment by Alexdoru** [comment]
ok the ender collector works flawlessly, it looks like the items don't event get dropped on the ground they directly teleport to the inventory. But still if you aren't using the ender collector and just open the cluster the items on the ground just totally freeze the game (I just tested it)

**Comment by Alexdoru** [comment]
![image](https://user-images.githubusercontent.com/57050655/113527329-7f2dd600-95bd-11eb-81b4-136ab10e530a.png)
