### ISSUE TITLE
Add a button to toggle sorting in chest buffers

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7754]
#### Which modpack version are you using?
GTNH 2.1.0.5
#
#### What did you try to do, and what did you expect to happen?
Now chest buffers don't require power to work anymore meaning that when the machine is ON it will auto sort its own inventory.
I would like to be able to toggle ON/OFF the sorting and that it is independant of the machine being ON or OFF.

#
#### What do you suggest instead/what changes do you propose?
Add a way to toggle the sorting ON or OFF, maybe use a screwdriver on the machine (Note that using a screwdriver on the output side of the chest buffer changes the itemstack size regulation and does nothing and the other 5 sides of the machine)

Or/And

Add a button inside the buffer to toggle ON/OFF the sorting.

![image](https://user-images.githubusercontent.com/57050655/113518798-cfd70c00-9588-11eb-9da1-c9112f4b3209.png)

**Comment by johnch18** [comment]
I already added [this feature](https://github.com/GTNewHorizons/GT5-Unofficial/pull/490), I'll get around to making a button if I can

**Comment by johnch18** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/490
Fixed in dev, will maybe add a button.

**Comment by Alexdoru** [comment]
From the discord discussion and what mitch said I thought that you were talking about someting else. That's really nice if the feature is already implemented :)
