### ISSUE TITLE
Backpack causing enormous lag when a lot of items are on the ground

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7756]
#### Which modpack version are you using?
GTNH 2.1.0.0
#
#### What did you try to do, and what did you expect to happen?
I opened a matter cluster (it droped 256 stacks on the ground) to test if it was laggy ( see #7753) and my game frozze for an hour before I decided to atl f4

![image](https://user-images.githubusercontent.com/57050655/113529746-93290600-95c4-11eb-9c5c-90f697fcdc0c.png)
![image](https://user-images.githubusercontent.com/57050655/113529755-9623f680-95c4-11eb-9427-356eeb82c1b7.png)

#
#### What do you suggest instead/what changes do you propose?
Investigate the issue
#
#### What is your GTNH Discord username?
Alexdoru#9395

**Comment by Glease** [comment]
It looks like it want to pick up items every tick, despite the backpack is full/does not exist whatsoever, thus the lagging.

**Comment by Alexdoru** [comment]
It looks like it's trying to save the content of the backpack every time it tries to auto pick up an item via the filtering thing
