### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by omegaelit** [GTNewHorizons/GT-New-Horizons-Modpack#7757]
#### Which modpack version are you using?
Version 2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
On local multiplayer server
#
#### What did you try to do, and what did you expect to happen?
I'm trying to launch the server but after the second launch, it just crushes.
https://pastebin.com/fsAcEQEj
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
ὦelit#7045

**Comment by boubou19** [comment]
The game complains about a malformed JSON. Did you modified any JSON recently? or is it a freshly made server?

**Comment by boubou19** [comment]
After investigating a bit, i did not see any issue in the `<instance>/config/BloodMagic/Schematics` in both the client pack (technic) and the server pack. So please check your JSON files in this folder, and if you did not touched any file in this folder but it is still crashing, reinstall/redownload the server pack. (The error says it's missing a `{` at the begining of the file)

I'm closing this issue.
