### ISSUE TITLE
Forestry multifarm and few problematic crops

### ISSUE THREAD

**Issue by Pyromanc3r** [GTNewHorizons/GT-New-Horizons-Modpack#7759]
#### Which modpack version are you using?

GTNH 2.1.0.0

#### What did you try to do, and what did you expect to happen?

Section "Forestry and Multi-farms", quest "the Multifarm".  

The Questbook says that the multifarm can collect a harvest in the "**Orchard**" mode. And mods such as Natura, Pams's Harvestcraft are supported. I found few plants that farm does not handle.
Natura: Barley, Cotton (Cotton ver. from Pam works fine), Berry bushes.
Pam's Harvest the Nether: Glow Flower, Blood Leaf, Flesh Root, Marrow Berry (last 3 plants grow on the Soulsand block).

#### What do you suggest instead/what changes do you propose?

Add support for these mods or change the description in Questbook.

**Comment by Prometheus0000** [comment]
https://ftbwiki.org/MultiFarm#Managed_Farms
![image](https://user-images.githubusercontent.com/8517039/129422877-1154178f-738e-4849-9038-b30e2d5eb7a8.png)
You can see (and I tested it) that barley works just fine. Cotton also works in managed crop farm mode. I've changed the text to be less misleading though.
