### ISSUE TITLE
Lamps from "ProjectRed Illumination". Crash

### ISSUE THREAD

**Issue by Pyromanc3r** [GTNewHorizons/GT-New-Horizons-Modpack#7761]
#### Which modpack version are you using?

GTNH 2.1.0.0

#### What did you try to do, and what did you expect to happen?

If you cut any lamp (I tried inverted versions) with a **Diamond Saw** from mod _Forge Microblocks_, hang the resulting half lamp on the wall and try to break it, then the client crashed.
#### What happened instead? (Attach screenshots if needed)

Crash log https://pastebin.com/iZjCrYWR
#### What do you suggest instead/what changes do you propose?

need fix

**Comment by mitchej123** [comment]
Dupe https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6419
