### ISSUE TITLE
Oilsand Crashes game

### ISSUE THREAD

**Issue by kurisu-tofa** [GTNewHorizons/GT-New-Horizons-Modpack#7763]
#### Which modpack version are you using?

#
 2.1.0.0

#### What did you try to do, and what did you expect to happen?

# 
Mined basic stone oilsand with a tc pickaxe with silky jewel, expected to simply obtain the oil sand ore
#### What happened instead? (Attach screenshots if needed)

# 
Once the block was broken, got instant crashed. Tried again once relogging, did it again, so not a fluke. 

#### What is your GTNH Discord username?
Kurisu#6164

**Comment by alphaNOVAircraft** [comment]
Can you please link a crashlog, Would make things way easier :)

**Comment by kurisu-tofa** [comment]
https://pastebin.com/vTcGmBvi Heres the crash report

**Comment by Prometheus0000** [comment]
It's the small ore crash again. Update to fix, hopefully. #7126, #7224, #7289.
