### ISSUE TITLE
[Suggestion] few QoL mods 

### ISSUE THREAD

**Issue by Pyromanc3r** [GTNewHorizons/GT-New-Horizons-Modpack#7765]
Would you not port these mods? Or create analog for GTNH modpack?
https://www.curseforge.com/minecraft/mc-mods/itemzoom - This mod very comfortable when you work with chisel. It shows a big preview of the block. For construction and decor it would very help. 
https://www.curseforge.com/minecraft/mc-mods/whats-that-slot - and this one shows that you can put in a slot of some mechanism or what one or another generator works. It is very useful when you do not know what it is for the device and what it works on.

**Comment by johnch18** [comment]
I'm 99% sure we have a zoom function already in game.

**Comment by Prometheus0000** [comment]
Neither of them is available for this version, and both seem totally useless.
