### ISSUE TITLE
World breaker in hammer mode weird behavior

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7766]
#### Which modpack version are you using?
GTNH 2.1.0.0

# 
In vanilla minecraft you break blocks slower when you are flying/on a ladder than when you are on the ground.

Somehow with world breaker in hammer mode it's faster when you are flying (does it have something to do with the fact that I wear full infinity armor ?)

And if somehow you insta mine multiple blocks at once when in hammer mode it drops all the items on the ground instead of droping a matter cluster

If you have vambraces of steady progressions equipped it makes you mine even faster when you are flying thus triggering this bug more often

![image](https://user-images.githubusercontent.com/57050655/113638062-469e0300-9676-11eb-8f0c-068b42851d54.png)

**Comment by Prometheus0000** [comment]
Use a MBM?

**Comment by Alexdoru** [comment]
> Use a MBM?

What’s the point of your comment ?
I already have 10 void miners and this is a bug report not an open question on how to effectively harvest ressources

**Comment by Prometheus0000** [comment]
Like before, I fail to see the point in spending time on this. You need infinity to make it, and by that point you should have better things to do than manual mining.

**Comment by Alexdoru** [comment]
> Like before, I fail to see the point in spending time on this. You need infinity to make it, and by that point you should have better things to do than manual mining.

I found a bug
I reported the bug
End of story 

that’s how bug reports work
