### ISSUE TITLE
Make Molecular Transformers usable in Processing Arrays

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7769]
Pretty self-explanatory, useful for graphene and sunnarium

**Comment by Prometheus0000** [comment]
Can't they already accept UHV/UEV/UIV or something? What's the point?

**Comment by johnch18** [comment]
They cap out at 1/tick, so at higher energy tiers they benefit more from parallelization

**Comment by Prometheus0000** [comment]
How are you even producing something like 64A of UIV?

**Comment by johnch18** [comment]
Trade secret

**Comment by sintken** [comment]
20mil eu/t is just 2.5a UIV, so for tin->silver (20mil eu) 2.5A UIV or 10A UEV is enough to max out a transformer. ive got eight t3 fusions stacked using tin plasma, and i have noticed this issue - i've got a half dozen transformers just lined up for them <.<

**Comment by johnch18** [comment]
There's also the argument to be made that space itself is a resource

**Comment by Hikari1nVoid** [comment]
At UHV+ there are a bunch of  alternative solutions for sunnarium and graphene and I don't think the MT will be widely used at that stage.
From my view the only use of MT after UHV is for automated tin plasma production.(and this may be removed since there's a pending nerfing on tin plasma.)
