### ISSUE TITLE
Magneto Resonatic LV (and above) circuit recipe broken

### ISSUE THREAD

**Issue by sintken** [GTNewHorizons/GT-New-Horizons-Modpack#7770]
#### Which modpack version are you using?
2.0.9.0 (sorry)
#
#### If in multiplayer; On which server does this happen? 
Prospercraft. Also tested in singleplayer, same problem.
#
#### What did you try to do, and what did you expect to happen?
Make LV-tier magneto resonatic circuit in circuit assembler (tested with singleblock and in a PA)
#
#### What happened instead? (Attach screenshots if needed)
Crafted ULV-tier magneto resonatic circuit instead. Issue seems to be that the ulv-tier circuit will consume the second board if its present, but only actually needs one board. so the LV-tier circuit sees ingredients for ULV-tier circuit and crafts it, ignoring other materials. Also tested the ULV-tier circuit in the CAL, which required boards in the first input bus but not the third.
#
#### What do you suggest instead/what changes do you propose?

Fix ULV-tier recipe to require 2 imprint-supporting boards, or change the recipe to use chipped/flawed magneto-resonatic crystals instead of normal ones. My guess is this issue is also present for mv/hv/ev/iv/LuV circuits, since they all use the same grade of magneto-resonatic crystal.

#
#### What is your GTNH Discord username?
sintken (taintstainer)

**Comment by yukieiji** [comment]
Maybe those recipes here
https://github.com/bartimaeusnek/bartworks/blob/master/src/main/java/com/github/bartimaeusnek/bartworks/system/material/processingLoaders/AdditionalRecipes.java#L317-L352

**Comment by Prometheus0000** [comment]
I wonder why bart is adding tiberium to naq reactors as a fuel?
