### ISSUE TITLE
Server crash due BloodMagic initialization

### ISSUE THREAD

**Issue by omegaelit** [GTNewHorizons/GT-New-Horizons-Modpack#7772]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Local multiplayer
#
#### What did you try to do, and what did you expect to happen?
Launch server, but it crashes, and after deleting `config/BloodMagic` it launches.
I suggest the problem is in the load meter config.
Continuing #7757, I redownloaded the Server pack and the problem still occurs.
#
#### What happened instead? (Attach screenshots if needed)
Server pack downloaded from here: http://downloads.gtnewhorizons.com/ServerPacks/
#
#### What do you suggest instead/what changes do you propose?
#
#### What is your GTNH Discord username?
ὦelit#7045

**Comment by boubou19** [comment]
can you try deleting the `<instance>/config/BloodMagic/Schematics` and launch the server? Just to see if the issue is inside this folder or not.

**Comment by omegaelit** [comment]
I tried deleting Schematics and leave meteors but It doesn't help me.

**Comment by boubou19** [comment]
can you post the crashlog it gave you? maybe it has changed.

**Comment by omegaelit** [comment]
It's funny, but after reuploading the meteor folder, it crashed with old generated schematics `https://pastebin.com/9dJs9mNj`, but after deleting schematics, the server started normally. Why that doesn't happen last time, IDK.
Issue is closed, sorry.
