### ISSUE TITLE
Zyngen Issues

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#7773]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What did you try to do, and what did you expect to happen?
Issue 1 - Turned on the machine without giving power to it, expected to delete items by turning on and immediatly off by going out of energy.
Issue 2 - I used the machine to make some alloys, by using separate input buses. One input bus had Mold (Nuggets) in it and was used to make nuggets, the other input bus was just empty. I expected the machine to output the alloy when using the empty input bus.

#
#### What happened instead? (Attach screenshots if needed)
Issue 1 - The machine kept running without power.
![javaw_4nOsRMBcFU](https://user-images.githubusercontent.com/17811922/113718979-7805e580-96ed-11eb-8556-74a3f7847e85.png)

Issue 2 - There is no separation between buses, so trying to make an alloy with 2 different ingots in an empty hatch may end up using the Mold (Nugget) and giving nuggets of both inputs as an output.

#
#### What do you suggest instead/what changes do you propose?
Fix both issues

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by Glease** [comment]
Please ask [here](https://github.com/alkcorp/GTplusplus/issues/) instead. We don't have our own fork of gt++ for licensing reasons.

**Comment by Sphyix** [comment]
alkcorp/GTplusplus#771

**Comment by General-Ike** [comment]
Tip to bypass the shared input bus issue:
Dusts can be smelted together into their alloys and won't interact with any mold recipes that I'm aware of.

**Comment by Sphyix** [comment]
Yeah I guess that's a good workaround, i decided to report the issue anyway after i found that no power was being used, i discovered the bus sharing some time ago

**Comment by yukieiji** [comment]
This issue hasn't been fixed in v2.1.1.0
