### ISSUE TITLE
Searchable quests / NEI Tab

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#7774]
#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
Jimmy's whitelisted server
#
#### What do you suggest instead/what changes do you propose?
It would be very useful if there was an NEI tab that lets you search rewards from quests and/or an option to search for quests by name in the questbook (or even rewards names).
#
#### What is your GTNH Discord username?
Hucking#0193

**Comment by Alexdoru** [comment]
the NEI thing was in the game before right ?

**Comment by Prometheus0000** [comment]
That sounds like it's of _supremely_ limited utility, and not worth it at all. @mitchej123 do you have an opinion on the usefulness vs difficulty of this?

> option to search for quests by name in the questbook

This already exists in the QB? Just not from NEI.

**Comment by hucking** [comment]
Ah I never noticed the search feature in the QB I apologize, still would be nice if you could search by rewards too

**Comment by Prometheus0000** [comment]
I'd rather the crashes were fixed than adding of superfluous features. Just do all the quests available to you to get all the rewards. What would you even search for? Not to mention that it should be a nice surprise that you get something good when completing a quest. Though you can just see when you unlock it. Now hiding rewards, that would be a better feature request.

**Comment by hucking** [comment]
alright I guess I'll close this, but I still think it's useful especially when playing on a server to be able to request players to hand in certain quests. But I understand your philosophy.
