### ISSUE TITLE
Bars made from dark STEEL are called dark IRON bars

### ISSUE THREAD

**Issue by Warlander** [GTNewHorizons/GT-New-Horizons-Modpack#7776]
#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
I made dark steel bars expecting them to be called "dark steel bars".
#
#### What happened instead? (Attach screenshots if needed)
They are called "dark iron bars" instead.
#
#### What do you suggest instead/what changes do you propose?
Rename them from "dark iron bars" to "dark steel bars"
#
#### What is your GTNH Discord username?
Warlander

**Comment by bombcar** [comment]
Dark iron is a thing, the recipe should probably be changed to use dark iron rods instead of dark steel.

**Comment by chochem** [comment]
it tooks us a moment. but today is the day
