### ISSUE TITLE
BloodMagic crash again due meteor

### ISSUE THREAD

**Issue by omegaelit** [GTNewHorizons/GT-New-Horizons-Modpack#7779]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Local multiplayer
#
#### What did you try to do, and what did you expect to happen?
I'm trying to start the server again but it crashes, and after deleting `config/BloodMagic/meteors` it starts normally.
crash report: https://pastebin.com/PdR4LPzK
last console messages: https://pastebin.com/7tML1xYD
#
#### What happened instead? (Attach screenshots if needed)
#
#### What do you suggest instead/what changes do you propose?
#
#### What is your GTNH Discord username?
ὦelit#7045

**Comment by Ethryan** [comment]
Crashlog please

**Comment by omegaelit** [comment]
I already send it 
> crash report: https://pastebin.com/PdR4LPzK

**Comment by Glease** [comment]
Something wrong with the bot. It shouldn't close issues with crash labels.

**Comment by Prometheus0000** [comment]
@omegaelit Did you make sure to delete your config dir and replace it with the new one?

Also, the new version is out.

**Comment by omegaelit** [comment]
The server stopped crashing.
