### ISSUE TITLE
New trinium coils don't work with volcanus

### ISSUE THREAD

**Issue by Oueio** [GTNewHorizons/GT-New-Horizons-Modpack#7781]
#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Crafted trinium coil for use with volcanus
#
#### What happened instead? (Attach screenshots if needed)
Volcanus just don't work, EBF works
#
#### What do you suggest instead/what changes do you propose?
Fix it:)
#
#### What is your GTNH Discord username?
None

**Comment by Prometheus0000** [comment]
Go to the GT++ repo.
