### ISSUE TITLE
AE2 autocrafting Tier 1 Booster consumes canister, by hand doesn't

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#7782]
#### Which modpack version are you using?
2.1.0.5
#
#### What happened instead? (Attach screenshots if needed)
When crafting a Tier 1 Booster in a crafting table, you get an empty canister back.
When crafting a Tier 1 Booster via AE2 autocrafting (molecular assembler), the ME system is not credited back with an empty canister.
#
#### What do you suggest instead/what changes do you propose?
Preferably, credit the ME system with an empty canister when autocrafting rocket boosters.
#
#### What is your GTNH Discord username?
NeroOneTrueKing

**Comment by Prometheus0000** [comment]
It's supposed to be used up. Also, there's tickets on that, but not the AE thing I think. Go mention that on an existing ticket if you like.
