### ISSUE TITLE
Fermenter needing any item to make biomass into fermented biomass

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7783]
#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
I'm making ammonia, and i tried using the fermenter, but it just wasn't working. Apparently you need to place any item in the slot for it to work, even though the recipe says you don't need anything.
#
#### What happened instead? (Attach screenshots if needed)

https://user-images.githubusercontent.com/57275066/113961838-061cc180-97fd-11eb-9126-f8adb579c567.mp4

![2021-04-07_23 42 38](https://user-images.githubusercontent.com/57275066/113962838-e38ba800-97fe-11eb-978d-39a5ba7fe286.png)

![2021-04-07_23 42 40](https://user-images.githubusercontent.com/57275066/113962847-ea1a1f80-97fe-11eb-9c21-b5cf7980453b.png)

![2021-04-08_00 08 24](https://user-images.githubusercontent.com/57275066/113962856-ed151000-97fe-11eb-978e-2e39f65f3870.png)

**Comment by Prometheus0000** [comment]
@bartimaeusnek , you fixed this when you fixed the threading thing, right?

**Comment by Glease** [comment]
I cannot replicate this on latest dev build.
![Fermenter working](https://user-images.githubusercontent.com/4586901/118377027-011e0f80-b5fe-11eb-9abe-54f568127519.png)

Please check if you have sufficient power, or simply wait a few more seconds to let the recipe lookup complete.
