### ISSUE TITLE
EnderIO powered spawners not upgradable using capacitors

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7785]
#### Which modpack version are you using?
2.0.0.5

In never versions of the mod, (and I could swear older ones but don't quote me), capacitors increased the power use and increased the spawn rate of mobs. This does not occur. I made a stellar capacitor for my skeleton spawner and nothing about it changed at all. I don't know if this is a backport or a bug.

**Comment by Prometheus0000** [comment]
See the other tickets about the backported capacitors not working.

**Comment by johnch18** [comment]
Oh sh*t where?

**Comment by Prometheus0000** [comment]
Just search for capacitor. And maybe filter by the EIO label.

**Comment by johnch18** [comment]
Smh becoming a dev means I actually have to pay attention. This is bullshit

**Comment by Dream-Master** [comment]
@Prometheus0000 duplication happend. link the issues please. Thanks

**Comment by Prometheus0000** [comment]
#6641 #6573. I really don't think it's hard to use the search function, that's what it's there for, and what I used to find these.
