### ISSUE TITLE
Xp oreberry quest gated behind an mv steam turbine

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7788]
#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
The quest to buy the experience oreberry is gated behind mv steam turbine.
![2021-04-08_17 55 08](https://user-images.githubusercontent.com/57275066/114099517-4d589000-9899-11eb-9b58-10f68e4327e3.png)

**Comment by Dream-Master** [comment]
I gated a bit higher in tier. You got your free xp berries allready in a quest. So it's not a mistake.

**Comment by Prometheus0000** [comment]
Then why is a steam turbine? You don't have to make those. It should be MV hull + MV circuits instead if you want to make it MV.

**Comment by Dream-Master** [comment]
I guess I picked some random mv block. feel free to change it to a hull or a circuit.
