### ISSUE TITLE
I can't form the infernal blast furnace because of the stairs.

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7790]
#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
I'm trying to make the infernal blast furnace from the witching gadgets, but when i try to right click it won't form, waila says the infernal brick stairs is actually sandy brick stairs.
#
#### What happened instead? (Attach screenshots if needed)
![2021-04-09_01 20 25](https://user-images.githubusercontent.com/57275066/114128164-20749f00-98d2-11eb-93b6-da4d4a94c2b5.png)
![2021-04-09_01 16 38](https://user-images.githubusercontent.com/57275066/114128167-21a5cc00-98d2-11eb-975a-d15f92f175fa.png)

**Comment by Impos913** [comment]
I think you need to put stairs the other way, full side touching lava. I have an infernal blast furnace and didn't have any forming issues.

**Comment by Prometheus0000** [comment]
https://ftbwiki.org/Infernal_Blast_Furnace Indicates what Impos913 said is correct.

**Comment by bartimaeusnek** [comment]
> The [...] Stairs have to be rotated towards the center of the structure.
