### ISSUE TITLE
Percent chance vs tiny dust output in ore processing [RFC]

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7791]
This is simple. Would you rather have a guaranteed tiny dust output or a percentage based full dust output in the ore processing steps.

**Comment by maniifestantes** [comment]
Depending on the percentage, i'd go with the full dust, just for the sake of a weird sense of gambling.

**Comment by GTNH-Afx237v7** [comment]
Percent based full dust. No more packaging tiny dusts.

**Comment by Dream-Master** [comment]
I am against it. Sometimes i set % to small and tiny dust as well. Lets add better sorting system or mechnics instead of remove small and tiny dusts.

**Comment by Alexdoru** [comment]
%chance full dust. Right now the grand majority of tiny dusts that goes through packagers come from ore processing. If we could change the ore processing recipes to give only full dust with a % chance that would save TPS.

**Comment by Dream-Master** [comment]
I think more variations of dust make recipes more complex. I like this complexity.

**Comment by Prometheus0000** [comment]
It's Lag+Complexity(AKA annoyance) vs Non-Lag+Simpler(you still have to move the dusts around).

It's pretty clear which is better.

Also, if by recipes you mean recipes that _use_ tiny/small dusts, I'm pretty sure no-one uses those, and there's another ticket about removing them and/or adding full dust versions if they don't have one.

**Comment by Dream-Master** [comment]
I use this multiple time in bee comb processing or some dust processing.

**Comment by Prometheus0000** [comment]
That's not what I mean. I mean when the tiny/small dust is the input, not the output.

**Comment by GTNH-Afx237v7** [comment]
I still wonder why small/tiny dusts would be used in a mixer recipe as inputs, to give small/tiny dusts or full dusts as output...
If tiny dust output was changed to %, this should obviously also affect any bee combs.
I believe this will be for the better to have % chance instead of small/tiny.

**Comment by Methes** [comment]
Sidestep - make Voidminers generate bedrock ores. Can only be processed in separate (complex) processing chain due to density and hardness. Makes VMs slower but each ore is worth more dusts than regular one and the final step of processing chain is full dust form only.

As I understand small/tiny dusts become an issue with VMs?
Makes all parties happy, lower overhead, potential new exciting chain than macerate-hammer-wash-smelt.

**Comment by GTNH-Colen** [comment]
I'm against fully removing small/tiny dusts as that will have huge knock on effects but don't see the harm if we just do this for ore processing.

**Comment by querns** [comment]
One idea I saw floated a while back was to allow you to put a numbered circuit into a centrifuge or a new dust cleaning machine or whatever that let you choose between percentage chance and tiny dust.

**Comment by Alexdoru** [comment]
> I'm against fully removing small/tiny dusts as that will have huge knock on effects but don't see the harm if we just do this for ore processing.

exactly what we need

**Comment by Alexdoru** [comment]
> One idea I saw floated a while back was to allow you to put a numbered circuit into a centrifuge or a new dust cleaning machine or whatever that let you choose between percentage chance and tiny dust.

why would someone chose to have tiny dusts if you can have directly the full dsut ?

**Comment by querns** [comment]
> > One idea I saw floated a while back was to allow you to put a numbered circuit into a centrifuge or a new dust cleaning machine or whatever that let you choose between percentage chance and tiny dust.
> 
> why would someone chose to have tiny dusts if you can have directly the full dsut ?

You can get screwed by the RNG sometimes with percentage chance, especially for critical applications like one's initial tiny gallium dust electrolysis from sphalerite dust in MV. It'd allow someone who simply would not tolerate the RNG aspect to guarantee a particular return in exchange for automation complexity.

**Comment by Alexdoru** [comment]
> You can get screwed by the RNG sometimes with percentage chance, especially for critical applications like one's initial tiny gallium dust electrolysis from sphalerite dust in MV. It'd allow someone who simply would not tolerate the RNG aspect to guarantee a particular return in exchange for automation complexity.

idk considering it is ore processing and in GTNH you process thousands of ores at once, the RNG tends to converge pretty quickly towards the correct amount

**Comment by Glease** [comment]
> You process thousands of ores at once

Not the case when you are still pre HV.

**Comment by GTNH-Colen** [comment]
> > You process thousands of ores at once
> 
> Not the case when you are still pre HV.

Unless you're min maxing ores to the point where you're processing like exactly 9 to get a full dust or something this really isn't a concern, it averages out very quickly. People tend to mine large veins at once, it shouldn't be an issue.

**Comment by Alexdoru** [comment]
> Unless you're min maxing ores to the point where you're processing like exactly 9 to get a full dust or something this really isn't a concern, it averages out very quickly. People tend to mine large veins at once, it shouldn't be an issue.

exactly, from the start of the game you mine veins one by one and stop mining when your inventory is full which mean you have stacks of ores and once processed on average it is the same with both recipes

And adding a circuit config will be harded to code rather than just changing the recipe

**Comment by mitchej123** [comment]
Psh, valid solutions have been proposed to eliminate/reduce the lag, and people want reduced complexity.  🤕 🤒

**Comment by yukieiji** [comment]
How about adding a recipe to the existing machine that has a chance of getting full dust?
Crushed Ore processing: Add Chemical Bath recipe(Percent based full dust, need to make the recipe to consume another fluid instead of water because of the GT++ machine)
Purified Ore processing: Add Centrifuge recipe(Percent based full dust)
Impure Dust/Pure Dust processing: Add Thermal Centrifuge recipe(Percent based full dust)

**Comment by GTNH-Colen** [comment]
> Psh, valid solutions have been proposed to eliminate/reduce the lag, and people want reduced complexity. 🤕 🤒

I mean if people want complexity then Methes solution seems good, that'd naturally be more work though.

**Comment by Florexiz** [comment]
So compiling ideas:
1) Add prospection controller item which you can config in special machine with elemental scans of materials (orbs used by replicator)
2) Make VM produce materials specified in prospection controller if they exist in this dim considering weights
3) Make VM produce not ores, but bedrock clusters
4) Add special cluster extractor multi that can extract from each cluster for example 100 gold, 10 nickel, 10 iron, (all byproducts)

**Comment by GTNH-Afx237v7** [comment]
Still in favor of changing tiny piles to % based full dusts...

**Comment by bombcar** [comment]
Reducing the amount of times you encounter tiny/small is nice. Fully removing them from the game entirely might complicate some things (as tiny dusts are basically macerated nuggets). 

A steam-era solution for filtering out tinies would be nice (even if it voids them perhaps) to go along with the percent chance change.

**Comment by boubou19** [comment]
That's a very welcomed change, as main lag from oreproc is handling the tiny piles (lag from buffers in sorting mode + lag from packager).

**Comment by bombcar** [comment]
Can disassembler / arc furnace recipes also return percentage Chances? Would fix/tune a lot I suspect.

**Comment by mitchej123** [comment]
There were valid suggestions, but nobody has the time or desire to implement them.  I say go ahead and convert to percent chance for large dust

**Comment by Dream-Master** [comment]
it was partly done for the ore washer

**Comment by Glease** [comment]
Is this fully resolved across all addons?

**Comment by repo-alt** [comment]
Isn't there tiny dust in Rare  Earth I processing? (last place where I saw that)

**Comment by joshaup1999** [comment]
> Is this fully resolved across all addons?

There is still a few things with tiny piles. Rare Earth I being one of them. Plat line also has the tiny piles
