### ISSUE TITLE
Fluid-Only Machine recipes not working unless Item is in Input

### ISSUE THREAD

**Issue by anabsolutesloth** [GTNewHorizons/GT-New-Horizons-Modpack#7792]
#### Which modpack version are you using?
2.1.0.5
Sidenote: using experimental recipe load speedup Gregtech jar from Bart
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Electrolyze Lead-Zinc Solution with proper equipment.
#
#### What happened instead? (Attach screenshots if needed)
Electrolyer did not operate unless an Item was present in the Item slots
Will work with ANY item in the input slots.
![image](https://user-images.githubusercontent.com/63694982/114143799-6ed17000-98c9-11eb-8b60-3dcd5865f7f0.png)
Not working
![image](https://user-images.githubusercontent.com/63694982/114143826-785ad800-98c9-11eb-8900-123dfd6616ce.png)
Working
#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
Emperdog

**Comment by bartimaeusnek** [comment]
already fixed
