### ISSUE TITLE
Game crashes when running through some chunks on a private server

### ISSUE THREAD

**Issue by troonce** [GTNewHorizons/GT-New-Horizons-Modpack#7793]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Ran through a chunk, expected to just walk through it and not crash
#
#### What happened instead? (Attach screenshots if needed)
game crashed (freeze then crash)(tested with 3 different people and all crashed)
#
#### What do you suggest instead/what changes do you propose?
not crash
#
#### What is your GTNH Discord username?
Sama#5703

The two provided crash reports are from two different users.
[crash-2021-04-09_17.53.27-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6288778/crash-2021-04-09_17.53.27-client.txt)

[crash-2021-04-09_18.25.52-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6288779/crash-2021-04-09_18.25.52-client.txt)

Edit:
Related Issues:
https://forum.feed-the-beast.com/threads/2-4-2-2-5-0-crash-in-the-nether.161405/
https://forum.gamemods.com.br/threads/meu-minecraft-com-mods-tava-rodando-liso-agora-toda-vez-que-entro-crasha.40020/

**Comment by boubou19** [comment]
can you try to reproduce the issue without fastcraft?
