### ISSUE TITLE
Crash from mod not in pack (it seems?)

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7794]
#### Which modpack version are you using?
Modified 2.1.0.5
#
#### What did you try to do, and what did you expect to happen?
Switch to non-creative mode, not crash.
#
#### What happened instead? (Attach screenshots if needed)
Crashes. Also crashes on loading world.
[crash-2021-04-10_04.10.39-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6289496/crash-2021-04-10_04.10.39-client.txt)

#
#### What do you suggest instead/what changes do you propose?
The crash seems related to @SinTh0r4s's hydroenergy mod, which I don't think is included? It's also apparently related to the pollution code? Which you don't see in creative.

**Comment by Dream-Master** [comment]
i messaged him and hope he can take a look. Maybe somethings went in the api allready

**Comment by Prometheus0000** [comment]
Apparently this is only a problem on a branch for hydroenergy.
