### ISSUE TITLE
Existing item filter item (for conduits) should be more expensive

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7795]
#### Which modpack version are you using?
2.1.0.5
#
You can filter way more with it than the Big ones, but it costs way less, and those are EV, and it's MV.

**Comment by alphaNOVAircraft** [comment]
The other one has features like ignore nbt etc. 

Moving the existing will mostly make ppl use more of the basic ones, so i think the current price of them is fine. It doesnt allow to do anything new, it only reduces the amount of conduit connectors you need (which i guess is also in the tps intrest). The advanced ones allow e.g. for easy flask automation etc

**Comment by alphaNOVAircraft** [comment]
You could maybe increase the cost slightly, but they should stay at the same tier imo.

**Comment by Prometheus0000** [comment]
Does anyone actually use the Big ones though? Maybe those should be cheaper? Like, not End Steel.

**Comment by alphaNOVAircraft** [comment]
I use them in plenty of setups, cz they can e.g. easily filter of all types of flasks (to split up flasks and crafting items for e.g. assembly PAs). 
I dont think many ppl use them just as bigger filter (iirc bot did it)

**Comment by Prometheus0000** [comment]
Any comments from anyone else?

**Comment by GTNH-Afx237v7** [comment]
It is dirt cheap compared to the big item filter. Think the big item filter has 3x9 slots whereas the existing item filter can recognize 50?60? items. I suggest making the big item filter cheaper, as you mentioned use sth different than end steel.
