### ISSUE TITLE
The chisel's factory series block material is all transparent

### ISSUE THREAD

**Issue by Leaveleaf** [GTNewHorizons/GT-New-Horizons-Modpack#7796]
The chisel's factory series block material is all transparent. 
Modifying the chunk loading of optfine is also invalid. It can be fixed in this way in 2.1.0.4

#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
yes
#
![image](https://user-images.githubusercontent.com/19620848/114275283-85f09900-9a54-11eb-986f-f5d51acfd446.png)
![image](https://user-images.githubusercontent.com/19620848/114275382-ff888700-9a54-11eb-9dcf-8ce0625a3c2b.png)

**Comment by Prometheus0000** [comment]
Remove optifine.

**Comment by Leaveleaf** [comment]
Remove optifine will very lag : (

**Comment by Prometheus0000** [comment]
Get a better computer or do less things that cause lag then. Or don't use chisel blocks.

**Comment by Leaveleaf** [comment]
But this problem did not appear in version 2104,   2105: Chisel-release-17-c5e8645.jar → Chisel-release-19-d3b6803.jar
Is there something wrong with this update?

**Comment by Prometheus0000** [comment]
My understanding is that chisel was always like this, and also that the multithread chunk load thing (whatever it's called) is super bad  for...some reason. You'll have to get someone else to say though. You can also try going through the commits on the chisel repo yourself to see what changed.

**Comment by Leaveleaf** [comment]
I noticed that no one posted issues on Chisel before posting here. I will changed to xtones to decorate the base.
