### ISSUE TITLE
Scanner displays optimal plasma flow in L/t instead of L/s

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7799]
At present scanning a plasma turbine will give you an optimal flow in units of L/t rather than L/s. 
![image](https://user-images.githubusercontent.com/42650497/114289180-0ef6d880-9a33-11eb-8f82-5509abde607f.png)

**Comment by Alexdoru** [comment]
Note : the number of 68 is correct, just needs to change the « L/t » to « L/s »

**Comment by Prometheus0000** [comment]
I'd say just make a PR.

**Comment by Sphyix** [comment]
isn't it better to have the L/t instead of L/s? More precision

**Comment by Prometheus0000** [comment]
The plasma gen runs on L/s.

**Comment by repo-alt** [comment]
L/s is _more_ precise than L/t.

**Comment by GTNH-Afx237v7** [comment]
How is one more precise than the other?

**Comment by Alexdoru** [comment]
An integer of L/s has more precision than an integer of L/t because the L/t value has more rounding error than the L/s

**Comment by GTNH-Afx237v7** [comment]
Guess you need to have programming knowledge to identify this...

**Comment by johnch18** [comment]
The value shown is off by a factor of 20
