### ISSUE TITLE
Climate bug on the moon

### ISSUE THREAD

**Issue by Derton1332** [GTNewHorizons/GT-New-Horizons-Modpack#7800]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
locale server
#
#### What did you try to do, and what did you expect to happen?
make a bee lapotron
#
#### What happened instead? (Attach screenshots if needed)
I make a bee lapotron. 
#
#### What do you suggest instead/what changes do you propose?
One of the conditions is an icy climate on the moon, but a normal climate on the moon. And at high altitude it's just cold

at normal altitude:
![image](https://user-images.githubusercontent.com/82309137/114297784-63459b00-9abb-11eb-9033-580d963b29c4.png)

At the highest point:
![image](https://user-images.githubusercontent.com/82309137/114297796-6fc9f380-9abb-11eb-83ba-399f338a4e39.png)

#
#### What is your GTNH Discord username?
CrashTest

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/114299057-63c43e80-9a87-11eb-8b45-096f18c6e73f.png)
For now change the biome, or use an alveary or industrial apiary.

I'm not sure if the bee's reqs should change or if the dim should. Anyone know if the other space-type bees have similar problems?

**Comment by Dream-Master** [comment]
Its more a gc bug ?

**Comment by Derton1332** [comment]
I think yes. There can be no normal temperature on the moon. I have tried using alveary and industrial apiary They do not see the lapis block and the mutation does not occur. (Sorry for my bad English, I translate through a translator)

**Comment by Prometheus0000** [comment]
Alveary needs the lapis block below the center bottom block, which has to be a normal alveary block. I'm not sure if you can make it cold enough though. If you can make an industrial apiary, you can also just use mutatron to make it directly though, which I forgot to mention.

**Comment by Derton1332** [comment]
I tried both under the central unit and over the entire alveary.  doesn't work.  industrial apiary can't do it yet.  in singleplayer tried with industrial apiary - doesn't work
