### ISSUE TITLE
Extreme lag induced by OpenComputers

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7803]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
eta
#
![image](https://user-images.githubusercontent.com/12850933/114320452-4ab69e80-9b16-11eb-96ef-b082220b2522.png)
![image](https://user-images.githubusercontent.com/12850933/114320486-63bf4f80-9b16-11eb-8189-b09b06cb75cc.png)

link of the warmroast dump: https://cdn.discordapp.com/attachments/684890002181849120/830904579133800448/WarmRoast.html

It happens when the player turns his computer on.

**Comment by repo-alt** [comment]
Looks like it writes directly to the disk or something. It is configurable iirc.

**Comment by boubou19** [comment]
I have one question tho: why is it called by wawla?

I'll check his drives to see what kind of code there is inside them. But it's weird that it happens when the computer turns on.

**Comment by boubou19** [comment]
I just checked the config and file changes are buffered on eta, so if it really writes to disk, there is an issue.

**Comment by repo-alt** [comment]
I looked a bit and perhaps it is a wawla bug. It asks for full tile NBT server side. There is a special hack in OC to avoid writing full NBT unless it is explicitly asked.

**Comment by boubou19** [comment]
I have the confirmation that it's wawla itself: the computer is off, and when i look at it, it drops the TPS near 0. Because i cannot access the computer anymore, i checked the size of the HDDs directly from the server files: the 1st is 1.73MB, the 2nd is 1.76MB.

**Comment by repo-alt** [comment]
Looks like wawla is ARR, also I can't find 1.7.10 sources.

**Comment by leagris** [comment]
> Looks like wawla is ARR, also I can't find 1.7.10 sources.

https://github.com/Darkhax-Minecraft/WAWLA/tree/066b35f7a1bf893a0bc30483d9e17fafd048580e
