### ISSUE TITLE
AE pattern output change request

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#7809]
#### Which modpack version are you using?
2.0.1.6

It would be nice if there was a way to change how AE processing patterns output in an interface. Currently if you place multiple non full stacks of an item in a pattern, it will combine those stacks in the output inventory. For example, if I put 4 different stacks of dirt in a pattern, but each stack only had 1 dirt in it, when the recipe is run, it will simply push 4 dirt at once rather than ending up with 4 separate stacks of 1 dirt. It would be nice for a lot of purposes to be able to disable this feature.

**Comment by repo-alt** [comment]
What if the target inventory contains something?

**Comment by 0lafe** [comment]
It might be nice if it pushed them after existing stuff, but i'm not sure it matters what happens with that. generally my ideas for this would always use blocking mode

**Comment by repo-alt** [comment]
I looked at the pattern pushing code and it turns out that it would be very hard to implement such a a feature. The reason is that interface sees adjacent inventory via special adapter, that has no notion of insertion slots. Changing adapter interface is a major modification.
