### ISSUE TITLE
Carpenters Blocks start disappearing 2h after placing them

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#7810]
#### Which modpack version are you using?
Latest Release 2.1.0.0.
#
#### If in multiplayer; On which server does this happen? 
On my own dedicated server, running on my machine which im also playing on
#
#### What did you try to do, and what did you expect to happen?
I placed Carpenters Bocks from the Carpenters Blocks mod and filled it in with the Block i wanted them to look like. I expected the blocks to stay there until I mine them.
#
#### What happened instead? (Attach screenshots if needed)
After ca 2h, the carpenters blocks started disappearing (not only visual glitch, they arent actually there). This happened randomly, and after about 10 hours all the carpenters blocks were gone.
#
#### What do you suggest instead/what changes do you propose?
N/A
#
#### What is your GTNH Discord username?
TrainerSnow
#5086

**Comment by Glease** [comment]
Check your log and see if there is something suspicious please. There is too few information to work on. 2.1.0.0 has been out for quite a while and thus you might be the only one who ever stepped into this problem.

**Comment by boubou19** [comment]
maybe it was a chunk saving issue? like it reverted to an earlier state, when you did not placed the carpenters?

**Comment by YannickMG** [comment]
Please create a new issue referencing this one if this re-occurs.
