### ISSUE TITLE
Safe mode in machine controller

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#7811]
#### Which modpack version are you using?
2.1.0.6b
#
#### If in multiplayer; On which server does this happen? 
Zeta and SP
#
#### What did you try to do, and what did you expect to happen?
Enable "Safe Mode" in machine controller cover
#
#### What happened instead? (Attach screenshots if needed)
Each time you open cover (or close?) it reset safe mode to disabled

![image](https://user-images.githubusercontent.com/29033773/114709390-2f75aa00-9d35-11eb-95bf-beede6bc1c0e.png)
#### What is your GTNH Discord username?
FalseColor

**Comment by johnch18** [comment]
Thanks for bringing this to my attention, I'll work on it later today.
