### ISSUE TITLE
Pam's Saplings Growing Trunk Logs as Fruit (Screenshot Included)

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#7812]
#### Which modpack version are you using?
2.1.0.6b
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Plant Pam's Maple tree. Grows maple logs on the leaf instead of the trunk and spruce trunk. Maple wood grows on tree like fruit would lol.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/33701188/114791770-aa968a80-9d4c-11eb-98ca-62279c27703d.png)

#
#### What do you suggest instead/what changes do you propose?
It looks like someone made some changes to cleanup sapling code to our harvest craft repository and maybe got some things swapped around. Also occurs on paperbark and cinnamon...ones that grow stuff on their bark.
#
#### What is your GTNH Discord username?
shawnbyday

**Comment by johnch18** [comment]
Ungrateful kids can't even eat trunk logs these daysl
