### ISSUE TITLE
Voidmetal goggles of revealing in the wrong quest area

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7813]
#### Which modpack version are you using?
2.1.0.6b
#
#### If in multiplayer; On which server does this happen? 
zeta
#
#### What did you try to do, and what did you expect to happen?
the quest needs you to make the voidmetal goggle of revealing, which needs shadow ingot, and that needs the vacuum freezer to make, which is mid to lake hv, probably not where you'll be if you like to do thaumcraft early, as the quest comes before the infusion altar.
#
#### What do you suggest instead/what changes do you propose?
Maybe placing it at the adept thaumaturge tab, after a quest for shadow ingot(if that exists, i'm not that in the adept tab)

**Comment by Prometheus0000** [comment]
It's not in the wrong place, and it even says it needs infusion in the quest. It's there so it's next to the normal goggles.
