### ISSUE TITLE
People are lagging the server by cutting down sacred-oak to gain money for leveling up

### ISSUE THREAD

**Issue by Ajes1337** [GTNewHorizons/GT-New-Horizons-Modpack#7814]
#### Which modpack version are you using? newest/recommended 2021-04-15

#
#### If in multiplayer; On which server does this happen? eta

#
#### What did you try to do, and what did you expect to happen? low-tps only 4 ppl on

#
#### What happened instead? (Attach screenshots if needed) attached

#
#### What do you suggest instead/what changes do you propose? a way so that ppl do not cut down trees that makes bad TPS for purpose of gaining money..

#
#### What is your GTNH Discord username? Ajes#7852

![chat](https://user-images.githubusercontent.com/11885892/114872747-e556fc00-9dfa-11eb-842e-cbcba524d5a7.png)

**Comment by boubou19** [comment]
in such cases, ping me or another staff member, destroying tps on purpose is against the rules.
