### ISSUE TITLE
The ZPM and UV batteries appears to be misnamed

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7816]
#### Which modpack version are you using?
2.1.0.6 stripped instance
#
![image](https://user-images.githubusercontent.com/8517039/114924275-cefd7000-9dfb-11eb-8819-0e39e6a6ba3e.png)
![image](https://user-images.githubusercontent.com/8517039/114924236-c442db00-9dfb-11eb-87db-ebbcd0b66d74.png)
![image](https://user-images.githubusercontent.com/8517039/114924249-c7d66200-9dfb-11eb-9191-6e33d19f8a22.png)

Same for the ZPM one.

**Comment by boubou19** [comment]
partly reported here https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3194, but was closed because it was staled.

**Comment by Prometheus0000** [comment]
That's good to know, but it says 'rename the "large naquadria battery (empty)" to "large naquadah battery (empty)"', when it should be the opposite, since you use naquadria to fill it.
