### ISSUE TITLE
Repair enchantment not working

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7818]
#### Which modpack version are you using?
2.1.0.6b
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
I enchanted all my set with repair II, but i spent the entire afternoon on and my armor wasn't repaired
#
#### What happened instead? (Attach screenshots if needed)
![2021-04-15_17 56 28](https://user-images.githubusercontent.com/57275066/114941611-c3b93d00-9e19-11eb-91e1-96e7a6ce67c0.png)

**Comment by greesyB** [comment]
I can't tell from the screenshot, do you have a wand in your inventory? Repair needs vis to work.

**Comment by maniifestantes** [comment]
oh it does? i didn't know about that
yeah it does work with the wand
well then consider this close
