### ISSUE TITLE
NEI not highlighting some items

### ISSUE THREAD

**Issue by hohounk** [GTNewHorizons/GT-New-Horizons-Modpack#7819]
#### Which modpack version are you using?
2.1.0.6b in singleplayer with a few QoL mods added (graphics and sound)

#
#### What did you try to do, and what did you expect to happen?
Tried to highlight anything containing chlorine in inventories by searching for "cl" in NEI and turning on the highlight feature.  I would have expected anything that has "cl" somewhere in their information to light up. 

#
#### What happened instead? (Attach screenshots if needed)
Most things highlighted properly, salt crystal variations outside the one looking like flint did not
![image](https://user-images.githubusercontent.com/4471281/115004754-ce261600-9eaf-11eb-9923-3f7b07e2f9f1.png)

#
#### What is your GTNH Discord username?
Hoho

These are the current NEI settings I am using:
![image](https://user-images.githubusercontent.com/4471281/115004874-f3b31f80-9eaf-11eb-94e4-0c3b92456898.png)

**Comment by hohounk** [comment]
Not sure if it helps but when I clean out the search bar entirely those salt crystals don't light up at all. 

![image](https://user-images.githubusercontent.com/4471281/115436513-c057f400-a213-11eb-9a7f-1fcfb2376aeb.png)

I've yet to find any search string that would match them. Even wildcards and @bart don't. Though with @bart I had one thing light up:
![image](https://user-images.githubusercontent.com/4471281/115436808-1167e800-a214-11eb-9ce8-7ac282b9f9be.png)

**Comment by YannickMG** [comment]
Actually they don't even show up in NEI's item search, though you can find recipes for them from their ingredients.

**Comment by YannickMG** [comment]
It looks like this happens for any item that's hidden in the NEI item panel with codechicken.nei.api.API.hideItem.
