### ISSUE TITLE
No assembler/machine recipe for some AE2 recipes

### ISSUE THREAD

**Issue by Dr-Turtle** [GTNewHorizons/GT-New-Horizons-Modpack#7823]
#### Which modpack version are you using?
2.1.0.4
#
#### If in multiplayer; On which server does this happen? 
Private
#

#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/34402990/115035299-6d401300-9e9a-11eb-803f-416402669408.png)

#
#### What do you suggest instead/what changes do you propose?
It is annoying to autocraft items which require tools in the process as they are not consumed.
An assembler recipe for these recipes should be added (in addition to the current recipes) using the same materials, but not using the tools.
There may be more, but I have noticed this with the following recipes:
ME Storage Bus
ME Import Bus
ME Output Bus
ME Terminal
ME Conversion Monitor
ME Crafting Terminal
ME Formation Plane
ME Annihilation Plane
ME Interface Terminal
P2P Tunnel - ME
ME Pattern Terminal
ME Processing Pattern Terminal
Illuminated Panel
ME Storage Monitor
Portable Cell

Not all of these are necessarily going to be autocrafted often, but some of these would be very useful to have assembler recipes for.
#
#### What is your GTNH Discord username?
Dr. Turtle#0001

**Comment by GTNH-Afx237v7** [comment]
Alternatively a tool/set of tools that can only be used in autocrafting but does not get consumed.

**Comment by Prometheus0000** [comment]
The script is broken.

**Comment by Ethryan** [comment]
Fixed
