### ISSUE TITLE
HoloInventory delay

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#7824]
#### Which modpack version are you using?
2.1.0.6b

HoloInventory seems a bit delayed. Sometimes it doesn't update what is in the chest/machine/whatever.
I and my brother noticed this after updating our server from 2.1.0.5

#### What is your GTNH Discord username?
ImpossibleVT#3997

**Comment by johnch18** [comment]
I've had this issue issue with fluids in hatches in particular, sometime you have to enter the gui to update it.

**Comment by Glease** [comment]
Fluid won't display correctly any more. Generating those fluid display items on server side used to be a major tps consumer so I get rid of that. Generating them on client side is unfortunately impossible as fluid inventory does not got sent to client.

I can try to make it update when a player is staring at a GT block, but it does mean an extra ray trace per player per tick on server side. 

You can't really see what's inside via holoinventory anyway. The color is telling nothing, at least to me. You probably could have just look at what waila told you instead.

**Comment by mitchej123** [comment]
I'd be a fan of doing a waila style packet from the server to see this.  I like using holoinventory to see if a pipe is clogged.
