### ISSUE TITLE
Morph

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7826]
#### Which modpack version are you using?
latest
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Is there any chance adding Morph in the pack?
it will be so convenient to maintenance or building if you turn into a creature that only 1 x 1
I think it is 100% doable by balancing it with GTNH style
#
#### What is your GTNH Discord username?
LoliNeko (Eason1134HK)

**Comment by Prometheus0000** [comment]
Christ, no. That thing gives you flight the second you kill a bat.

**Comment by Eason134HK** [comment]
> Christ, no. That thing gives you flight the second you kill a bat.

you can disable flight ability

**Comment by Prometheus0000** [comment]
Still sounds pointless.

**Comment by Eason134HK** [comment]
> Still sounds pointless.
nvm
