### ISSUE TITLE
Balancing the New Tungsten Line [RFC]

### ISSUE THREAD

**Issue by Leche-Caliente** [GTNewHorizons/GT-New-Horizons-Modpack#7827]
Has been some discussion in discord about the new tungsten from tungstate/scheelite processing line in dev 2.1.0.6. Mitch asked for people to leave feedback on Github, so I reckon this is a good place for that to happen.

Personally I like that change, new processing lines are usually pretty good as long as they're not annoying. My one minor suggestion would be to change the sodium tungstate autoclave recipe from EV to HV. I'm not sure why the tungstate ---> scheelite line needs to be at EV power, and I think that having to overvolt both an EBF and an autoclave to get tungsten out of end stone is a bit too much.

I also heard some other people ask for a yield increase to go with the added complexity (i.e. 7 tungstate to 2 tungsten instead of the 7 to 1 that we have right now). Personally, I don't necessarily oppose something like that, but I'm not too knowledgeable about the balance considerations.

**Comment by NeroOneTrueKing** [comment]
_Speaking as someone who already had a good stockpile of tungsten when the change happened at did not have to work through making the setup at tier..._

I like the changes, and I appreciate that as compensation for the new processing the blast time of tungsten was reduced.
I'd like to see tungstensteel produced by the oxide route have a similar reduction in total blast time, as it currently is 500s for 4 ingots with oxide and 125s for 1 ingot without oxide.

**Comment by Prometheus0000** [comment]
There is no TS oxide on 2.1.0.6b. Please update (or check it out) before making further comments so you know the current state.

Bot removed it due to...something related to HSS. He didn't say what.

**Comment by Leche-Caliente** [comment]
> why would it matter you need EV to smelt tungsten

I don't think it matters that much. I suppose you're right that getting the power together isn't that big of a deal considering that you can just use the same generators that run your EBF. I just don't see why that recipe needs to be EV. Tungsten is already EV gated by the EBF as you said, and the new process is pretty resource intensive in infrastructure for an on-tier player anyway. Is the problem that the EV autoclave didn't have any reason to build?

**Comment by botn365** [comment]
i tought the it would be fun if it was a EV autoclave 
you dont even need to make it at the moment sinse you can decide to just only process scheelite at first

**Comment by Leche-Caliente** [comment]
I noticed that, although finding a tungsten meteor is a bit icky, it is a viable alternative I would say.

**Comment by Alastors** [comment]
I kind of hated the new recipe, at first, it felt much to tedious and long for a single product. Tungstate + Sodium--> liquid Sodium Tungstate + Calcium Chloride --> Scheelite + Hydrochloric Acid --> Tungstic Acid Dust + blast furnace for a bit --> Tungsten Trioxide Dust + (Carbon or nitrogen gas to either make tungsten or make dust) for an ingot or two. Sure one could argue that its just a relatively close to net zero loss for byproducts processing line but like, it just feels tedious and unnecessary, it is certainly a little closer to real life tunsten processing which dont get me wrong I enjoy it but it just feels like its more than what it should be. But listing it all out has actually made me like it a little more actually. So idk how exactly I feel about it anymore

**Comment by ahmetsad** [comment]
> i tought the it would be fun if it was a EV autoclave
> you dont even need to make it at the moment sinse you can decide to just only process scheelite at first
there is (almost) no way to acquire scheelite with T1 rocket yet you need tungsten for t2 rocket and EV energy hatches so it's forced progression. finding scheelite at end is out of question. maybe add scheelite to moon stone dust? centrifuging endstone dust takes ridiculous time that shouldn't be only way.

**Comment by botn365** [comment]
you unlock EV with T1 rocket so you can process tungstate before T2 rocket

**Comment by ahmetsad** [comment]
I wrote scheelite not tungstate. Ofc you have access to tungstate at EV it's just too long processing yet you need to process more because it's not easy source of it. centrifuging tungstate from endstone dust takes 3 hours for 6 tungstensteel ingot.

**Comment by Prometheus0000** [comment]
You only need 2 for the T2 rocket. Also, you can also get tungstate from ender goo or moon dust. I'm not sure why it would take so long, but just do something else in your base until it's done? Like making the rest of the rocket parts.

There's absolutely no need to add scheelite before T2 dims.

**Comment by botn365** [comment]
titanium is 4 - 5 stem automation line with al the recycling depending if you start from rutile or ilmenite

frem scheelite its 6 steps and 9 (10 if wanting to process both)from tungstate if you calculate as water and unprocessed tungsten as input until dust

to me this isent to long its about twice as long as titanium and still a shorter then paltinum

> centrifuging tungstate from endstone dust takes 3 hours for 6 tungstensteel ingot.
has nothing to do with this change

**Comment by Prometheus0000** [comment]
It was EV before, I don't see the problem?

> What was the original goal of having it in the end in first place

I assume it was to add alternative sources. And you can get titanium pre-moon too.

**Comment by Glease** [comment]
Even before this change you still need an EV electrolyzer. What your are attempting is to skip EV entirely, which is of course impossible, and rightful it should.

**Comment by hohounk** [comment]
> It was EV before, I don't see the problem?

no real problem, I just imagined that the goal was to make limited amount of tungsten available before going to space just for things like what I wanted - a machine/item or two to make it easier to progress. I'm not particularly fond of having to fight mobs for resources and thus having stuff gated behind mob drops is not my ideal for having fun. Thus, to minimize that part of the modpack I would have preferred to get a weapon to minimize the farming it takes.

> And you can get titanium pre-moon too.

I honestly didn't know that but now that I looked at the way to get it, it seems that getting the EV autoclave would be doable before space and thus, unless I miss something, getting tungsten is doable as well. Getting both at that tech level is inconvenient enough that no sane person would attempt to do much else than the absolute bare minimum.

> What your are attempting is to skip EV entirely, which is of course impossible, and rightful it should.

no, I'm not attempting to skip it. I just saw the requirements for processing tungsten and all but one step was easily doable in HV so I imagined the goal really was to make it available at HV even if it would require some tedium a'la going through a mountain endstone for the required raw resources. I agree that skipping tiers should not be possible.

**Comment by Prometheus0000** [comment]
> I just imagined that the goal was to make limited amount of tungsten available before going to space

It is not. It's supposed to be EV. Whether you can get to EV without going to space is up to you.

> no sane person would attempt to do

Please see the no-rocket run. Sampsa did this up to ZPM or so. It involves lots of crops and UUM.

> all but one step was easily doable in HV so I imagined the goal really was to make it available at HV

It's really not. Now, you can get scheelite like alastor did at HV in the end, but I dunno if it'll stay like that, but I think bot said that specifically preventing that is not necessary. Go for that if you want it.

**Comment by MatthewCOwen** [comment]
The reason tungstensteel oxide got removed was because to make HSS-G you'd have to smelt up the tungstensteel only to macerate it back into dust to make the alloy, which was just a waste of time and power

**Comment by Prometheus0000** [comment]
Wouldn't you use way more TS than HSS-G though? I'm not sure about if the tungsten to TS recipe is changed in this version compared to before though, I think it's faster anyway?

**Comment by MatthewCOwen** [comment]
when there was TS Oxide, the only way to get TS dust was to cook up the TS Oxide and then macerate it. That was just a big waste of time and EU. By making the tungsten dust directly, you can take that and turn it into TS dust, which is much better

**Comment by Prometheus0000** [comment]
It seems like this discussion is done.
