### ISSUE TITLE
Adding additional tiers of Ender fluid covers and buffing transfer rate [RFC]

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#7829]
At present the max transfer rate on this cover is 400L/t which for an LuV device is rather pathetic considering the ender tank is IV and does around 16,000L/t. On balance though the ender tank is more of a pain in the ass to get (for pure tech players) and that the cover is convenient as it doesn't take up a block. However I'd still encourage the cover as they are more FPS friendly when used on mass such as for a chem setup. I suggest the following adjustments/additions:

| Tier  | Transfer rate (L/t) |
| ------------- | ------------- |
| EV  |  4000 |
| IV  | 8000  |
| LuV  | 16000  |
| ZPM  | 32000 |
| UV  | 64000  |

Higher tiers could exist but honestly I don't see many people needing more than this and if they really do they can use multiple covers. Additionally while I'm here a quest mentioning these would be really good, ideally in the lowest tech tier we decide to put them in as they are seriously under utilised at present.

See: https://github.com/Technus/TecTech/wiki/Ender-Fluid-Link-Cover

**Comment by Prometheus0000** [comment]
Uh, is this what it currently does or a suggestion to change it to? The link says it's '8-THOUSAND milibuckets a tick'?

> At present the max transfer rate on this cover is 400L/t

So this is confusing. Your chart is what you're suggesting...right? This isn't clear. Also, how do these numbers compare with pump speed?

> However I'd still encourage the cover as they are more FPS friendly when used on mass such as for a chem setup.

Did you try the tanks with the config to remove the FX at the bottom? To see if they still lag?

**Comment by GTNH-Colen** [comment]
> Uh, is this what it currently does or a suggestion to change it to? The link says it's '8-THOUSAND milibuckets a tick'?

Yea but this is wrong, I tested it in-game a little while ago and it was ~8000L/s not per tick.

> So this is confusing. Your chart is what you're suggesting...right? This isn't clear. Also, how do these numbers compare with pump speed?

Really not sure what is confusing about a chart with two columns. Why are pump speeds relevant when we should be discouraging large pipe networks ideally?

> Did you try the tanks with the config to remove the FX at the bottom? To see if they still lag?

I have not, is this the default option in the pack now?

**Comment by Prometheus0000** [comment]
> Really not sure what is confusing about a chart with two columns.

Adding a 'currently' column would make it clearer. Or a 'I suggest adding tiers as such' right above the chart. I mean, unless you know about it already, you might think that these are the existing tiers and you want to add more for example.

> I have not, is this the default option in the pack now?

No. Nobody tested it as far as I know, and nobody changed the default. Which makes me sad, because I can't even tell if it works if no-one who has lag from them tests it.

> Why are pump speeds relevant

As a comparison. Also, I feel it's better to standardize around them rather just picking arbitrary numbers.

BTW, I'm not opposed to additional tiers or anything.

**Comment by GTNH-Colen** [comment]
> Adding a 'currently' column would make it clearer. Or a 'I suggest adding tiers as such' right above the chart. I mean, unless you know about it already, you might think that these are the existing tiers and you want to add more for example.

Think this got lost in one of my revisions before posting, added now.

> As a comparison. Also, I feel it's better to standardize around them rather just picking arbitrary numbers.

I guess? I just picked numbers which felt good for the relevant tiers, it's not a huge decision but shouldn't be in the millions in EV. These happen to be very close to the pump speeds anyways, with a small bit of rounding.
