### ISSUE TITLE
Robot-Arm not inserting into second chem reactor slot

### ISSUE THREAD

**Issue by Vnnncnnnt** [GTNewHorizons/GT-New-Horizons-Modpack#7830]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
locally hosted server
#
#### What did you try to do, and what did you expect to happen?
Tried to insert stuff into the second slot of a chem reactor with a robot arm. Tested it with LV and LuV arms in creative as well.
#
#### What happened instead? (Attach screenshots if needed)
I tried all the settings for the "internal slot" and couldnt get it to insert into the right slot (4 is the left slot btw)
#
#### What is your GTNH Discord username?
Aber auf Ex

**Comment by Glease** [comment]
Check #7179. Try put the fluids in before you push items inside.

**Comment by Prometheus0000** [comment]
This works perfectly fine, use slot 5. Generally, you'll want to try a lot of numbers before giving up with the RA.
