### ISSUE TITLE
Chest buffers can’t disable sorting mode

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7831]
#### Which modpack version are you using?
GTNH 2.1.0.6
#

#### What did you try to do, and what did you expect to happen?

I shift right clicked with a soldering iron on a chest buffer, it said in the chat "Sort mode : disabled", but the chest buffer was still doing sorting. 

#
#### What is your GTNH Discord username?
Alexdoru#9395

**Comment by Prometheus0000** [comment]
See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7754, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7741, https://github.com/GTNewHorizons/GT5-Unofficial/pull/490.

I'm not sure which version they're in on, maybe try an updated GT5 version? Or get @johnch18 to fix it.

**Comment by Prometheus0000** [comment]
According to nukalsh it does work, so maybe talk to them? They said the used the zeta 2.1.0.6 version, so that should be 2.1.0.6b.

**Comment by Alexdoru** [comment]
Ok I messed up the title

**Comment by boubou19** [comment]
Well just tried on zeta which is on 2.1.1.3, and it works, but not for all of them. For exemple, it works well for the high voltage chest buffer, but it doesn't work at all for the ultimate voltage chest buffer. The sorting mode now is supposed to be default off, but looks like nothing change, no matter what says the chat about it. This is really annoying.

**Comment by boubou19** [comment]
i think i found the cause: https://github.com/D-Cysteine/GT5-Unofficial/blob/2426e485340ef9f9934a1df03c5ba67115720a1a/src/main/java/gregtech/common/tileentities/automation/GT_MetaTileEntity_ChestBuffer.java#L73

**Comment by D-Cysteine** [comment]
Yeah, I think it might be as simple as changing that line to be this:
`if (bSortStacks && aBaseMetaTileEntity.hasInventoryBeenModified())`

Though, I am confused how this could have been working for only some of the voltage tiers. I think all of the voltage tiers use the same code, so I am mystified by how they could be behaving differently =S

**Comment by boubou19** [comment]
well i guess on slow buffers, because we use it for a tick, the chances that we run into `aTimer % tickRate[mTier] == 0` are low, hence why it "worked".
