### ISSUE TITLE
BQ bug about <ore:cellHydrogenPeroxide>

### ISSUE THREAD

**Issue by KuroPeach** [GTNewHorizons/GT-New-Horizons-Modpack#7833]
modpack 2.1.0.5  bq quest 2.1.0.6

Some rocket fuel quest require HydrogenPeroxide from GTPP, But it will be automatically converted to Bartwork.

![image](https://user-images.githubusercontent.com/19620848/115431960-76cdd000-a238-11eb-95a6-ccdb3948b6d8.png)
![image](https://user-images.githubusercontent.com/19620848/115431848-5867d480-a238-11eb-967a-7b69e5f81515.png)
![image](https://user-images.githubusercontent.com/19620848/115431900-66b5f080-a238-11eb-94bb-427ec2bfe7f6.png)

**Comment by Leaveleaf** [comment]
Then I found out that Bart’s HydrogenPeroxide cannot participate in the recipes of GTPP

**Comment by Prometheus0000** [comment]
@botn365

**Comment by Prometheus0000** [comment]
BTW, you forgot to capitalize Hydrazine for the Hydrazine cell, which is I guess why that didn't unify as well?

**Comment by botn365** [comment]
with how bartworks materials works this is basicly imposibe sisne how bart names fluids is difernt from gtpp
bartworks is "hydrogen peroxide" while gtpp is "fluid.hydrogenperoxide" 
and i have to use forceunification or else my recipes get messed up

**Comment by Prometheus0000** [comment]
Maybe you should disable your rocket fuel recipes until GT++ is removed or change the name slightly until then, like adding a 1 on the end or something. Because you've broken normal rocket fuel crafting.

**Comment by botn365** [comment]
my rocket fuel is to replace gt++ and no i dint break it sinse all recipes that have to do with hydrazine and hydrogen peroxide get made as fluid and are consumed as fluid so as long they dont put it in a cell it wont convert

**Comment by Prometheus0000** [comment]
@Leaveleaf Please try what bot said, and don't put them in cells. You should force complete the quests that mess up as a result with a command or get an admin to do so.

**Comment by Leaveleaf** [comment]
Okay, thank you. I did use other methods to take out the fluid. I changed the quest to match the OD. 
But we still need to solve it, before GTPP is completely removed.
