### ISSUE TITLE
Fluid level emitters are stupendously laggy

### ISSUE THREAD

**Issue by RubiksImplosion** [GTNewHorizons/GT-New-Horizons-Modpack#7834]
#### Which modpack version are you using?
Zeta 2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
Private 2-player server
#
#### What did you try to do, and what did you expect to happen?
We had a dozen or so fluid level emitters that  were controlling fluid levels
#
#### What happened instead? (Attach screenshots if needed)
They caused unplayable amounts of client-side TPS lag
#
#### What do you suggest instead/what changes do you propose?
Either fix them or disable them, since they will cause unplayable amounts of lag
#
#### What is your GTNH Discord username?
RubiksImplosion#7493

**Comment by eigenraven** [comment]
Fixed in dev
