### ISSUE TITLE
[Suggestion] Make miners replace ores with stone

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#7837]
#
#### What do you suggest instead/what changes do you propose?

Right now miners leave air blocks after mining ores. It would be cool if instead they were replacing ores with stone.

Here is why :
When breaking a block it updates the lightning, and the fluids

Also miners transform the undergrounds into a gruyère and leave a lot of dark spots that would be really tedious to light up. It creates a lot of spawning spots

**Comment by leagris** [comment]
I'd suggest it replaces the ore block with its compound stone block instead (stone, black granite, red granite, basalt, marble, planet's stone).

**Comment by Alexdoru** [comment]
> I'd suggest it replaces the ore block with its compound stone block instead (stone, black granite, red granite, basalt, marble, planet's stone).

Of course

**Comment by repo-alt** [comment]
Here is the original discussion https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5278
