### ISSUE TITLE
[Suggestion / RFC] Change ME Storage Components beeing extensive recursive crafting

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#7839]
#### What do you suggest instead/what changes do you propose?
Currently ME Storage compnents dont bring any benefit when beeing upgraded in terms of capacity (they even get more expensive but not more capacity). Furthermore the high tier cells take insane amounts of cheap compnents that just slow down crafting (1 16M drive is 64 000 ulv circuits e.g.)) 
Maybe add direct recipes for storage cells higher then 1k that get aviable later so that a alternative to the currently recursive crafting only exits
#
#### What is your GTNH Discord username?
alphaNOVA#9875

**Comment by Prometheus0000** [comment]
There was already another issue on this. You couldn't go post there instead? We reopen stuff you know. Not that I could find it either, lol. I think it was colen's issue?

**Comment by alphaNOVAircraft** [comment]
Mitch suggested i open an issue so i guessed there wassnt one, and reopening issues will get lost again, most ppl dont bother to check page 238 of issues..

**Comment by GTNH-Colen** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/5040 I think this was the other thread? Not of my creation though.

**Comment by GTNH-Afx237v7** [comment]
I'm also all for reducing the nested crafting - the resource cost for larger AE cells are much higher than for a comparably sized super/quantum chest.

**Comment by Glease** [comment]
The prohibitively high cost of ME storage cells is one of the several major reasons people use solid drawer cubes. Making ME storage cells easier, if not cheaper, to get would solve the lag from these stupid constructs.

**Comment by Prometheus0000** [comment]
So what are the recipe suggestions? I don't see any? Which ones should have new recipes? 1 new one for 256k and that's it? All of them past 1k? You need to be clearer about _how_ you want them changed.

**Comment by GTNH-Afx237v7** [comment]
So currently the base for all components is the 1K ME Storage component, consisting of 

- 4 ULV Circuits
- 4 Charged Certus Quartz Dust
- 1 Item Processor Tier 1

As components tier up, the required processors tier up, up and including UV-Tier circuits for the 16384K Storage component.

How about each tier of storage consist of

- 4 tiered circuits 
- 4 plates of appropriate tier
- 1 item processor

without requiring the previous tier, i.e. no nested crafting?

So a 1K storage component could remain as is, whereas e.g. the 4096K would be

- 4 LuV Circuits
- 4 LuV-plates (Rhodium-plated Palladium)
- 1 item processor (tier 2? tier 3?)

**Comment by repo-alt** [comment]
Sounds good. Recursive crafting is evil.

**Comment by GTNH-Afx237v7** [comment]
So first sketch looks like this:

1K ME |   |  
-- | -- | --
ULV-Circuit | Charged Certus | ULV-Circuit
Charged Certus | Item Processor Tier 1 | Charged Certus
ULV-Circuit | Charged Certus | ULV-Circuit
  |   |  
4K ME |   |  
LV-Circuit | Steel plate | LV-Circuit
Steel plate | Item Processor Tier 1 | Steel plate
LV-Circuit | Steel plate | LV-Circuit
  |   |  
16K ME |   |  
MV-Circuit | Aluminum plate | MV-Circuit
Aluminum plate | Item Processor Tier 2 | Aluminum plate
MV-Circuit | Aluminum plate | MV-Circuit
  |   |  
64K ME |   |  
HV-Circuit | Stainless steel plate | HV-Circuit
Stainless steel plate | Item Processor Tier 2 | Stainless steel plate
HV-Circuit | Stainless steel plate | HV-Circuit
  |   |  
256K |   |  
EV-Circuit | Titanium Plate | EV-Circuit
Titanium Plate | Item Processor Tier 3 | Titanium Plate
EV-Circuit | Titanium Plate | EV-Circuit
  |   |  
1024K |   |  
IV-Circuit | Tungstensteel Plate | IV-Circuit
Tungstensteel Plate | Item Processor Tier 3 | Tungstensteel Plate
IV-Circuit | Tungstensteel Plate | IV-Circuit
  |   |  
4096K |   |  
LuV-Circuit | Rhodium-plated Palladium Plate | LuV-Circuit
Rhodium-plated Palladium Plate | Item Processor Tier 4 | Rhodium-plated Palladium Plate
LuV-Circuit | Rhodium-plated Palladium Plate | LuV-Circuit
  |   |  
16384K |   |  
ZPM-Circuit | Iridium plate | ZPM-Circuit
Iridium plate | Item Processor Tier 4 | Iridium plate
ZPM-Circuit | Iridium plate | ZPM-Circuit

This is indeed a buff for the 16384K as it would use ZPM circuits (currently it jumps from LuV to UV when upgrading 4096K to 16384K)

**Comment by Prometheus0000** [comment]
I'm already working on it, but Elisis messed up the AE2 script.

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/115751363-22753e00-a367-11eb-8a39-73fa7881f850.png)
![image](https://user-images.githubusercontent.com/8517039/115751395-27d28880-a367-11eb-9782-78315f6ae666.png)
![image](https://user-images.githubusercontent.com/8517039/115751416-2bfea600-a367-11eb-84f0-16c50ccd995f.png)
![image](https://user-images.githubusercontent.com/8517039/115751445-315bf080-a367-11eb-9152-2762012961b5.png)
![image](https://user-images.githubusercontent.com/8517039/115751479-3882fe80-a367-11eb-87d9-d28720900537.png)
![image](https://user-images.githubusercontent.com/8517039/115751493-3caf1c00-a367-11eb-80ce-ebe9efd0be38.png)
![image](https://user-images.githubusercontent.com/8517039/115751519-42a4fd00-a367-11eb-93e0-d5f57b67e69c.png)
![image](https://user-images.githubusercontent.com/8517039/115751547-489ade00-a367-11eb-869f-cde495c33ab8.png)
Circuits are oredicted. Should I change the voltages? Or something else?

**Comment by Prometheus0000** [comment]
Adjusted, see PR.

**Comment by 0lafe** [comment]
why lmao? recursion is what gives these a good cost here. they incentivize automation and punish manual crafting, which seems very positive for an EV+ storage system. The cells are always doable, and imo always worth it. things like drawers/chests just aren't the same for a lot of reasons, and the cells do give bonuses in comparison. 

Is there anything that ever actually becomes an issue with these? or do people just unironically dislike recursion that much? seems wack imo

**Comment by Prometheus0000** [comment]
Wasn't it something like 3M or 30M charged certus quartz or something for the last tier? That's not cool. And some still insane amount for the earlier ones?

And we want people to make these over drawer cubes. They're just storage there's no reason to make it ludicrously expensive, or a recursive craft of bajillions of lower tier components.

You can make them use the previous recipe in your own pack.

**Comment by 0lafe** [comment]
you don't need stacks of 4096ks in LuV though, and you don't need crazy cetus costs then either. By the point of making 16Ms don't you have access to be able to produce well over 3M curtis

drawer cubes also lowkey suck to make anyway, even current AE beats it imo. Maybe make drawer cubes less reasonable to make that large or something? but this seems like a wack way to go about it

**Comment by GTNH-Afx237v7** [comment]
Suggested by bot on discord:

```
4K should use 16 dusts and 4 processing units
16K should use 32 dust but in pure crystal form and 4 tier 1 item processors
64K  64 pure crystals 4 tier 2 + 16 tier 1
256K 64 pure fluix 1 tier 3 + 4 tier 2 + 16 EV while changing it to 4 IV circuits
1024K 64 pure fluix 8 tier 3 + 32 tier 2 + 16 LuV + 4 ZPM
4096K 64 pure fluix 2 tier 4 + 8 tier 3 + 16 ZPM + 4 UV
16384K 64 pure fluix 16 tier 4 + 64 tier 3 + 4 UHV + 16 UV

maybe the later tiers should use some field generator as well instead of fluix crystal
```

**Comment by Prometheus0000** [comment]
BTW, that's half of incomprehensible to read.

**Comment by Alexdoru** [comment]
> ![image](https://user-images.githubusercontent.com/8517039/115751363-22753e00-a367-11eb-8a39-73fa7881f850.png)
> ![image](https://user-images.githubusercontent.com/8517039/115751395-27d28880-a367-11eb-9782-78315f6ae666.png)
> ![image](https://user-images.githubusercontent.com/8517039/115751416-2bfea600-a367-11eb-84f0-16c50ccd995f.png)
> ![image](https://user-images.githubusercontent.com/8517039/115751445-315bf080-a367-11eb-9152-2762012961b5.png)
> ![image](https://user-images.githubusercontent.com/8517039/115751479-3882fe80-a367-11eb-87d9-d28720900537.png)
> ![image](https://user-images.githubusercontent.com/8517039/115751493-3caf1c00-a367-11eb-80ce-ebe9efd0be38.png)
> ![image](https://user-images.githubusercontent.com/8517039/115751519-42a4fd00-a367-11eb-93e0-d5f57b67e69c.png)
> ![image](https://user-images.githubusercontent.com/8517039/115751547-489ade00-a367-11eb-869f-cde495c33ab8.png)
> Circuits are oredicted. Should I change the voltages? Or something else?

This is way too cheap wtf

**Comment by Alexdoru** [comment]
We should keep recursive crafting recipes but make each tier cheaper than what it is now. Right now you take 4 storage units + circuits to make one storage unit of the same capacity. It doesn’t really make sense. We should lower the amount of storage component it takes to craft each tear. Reduce it to 2 or 3 and replace it by a tiered metal or whatever.

**Comment by alphaNOVAircraft** [comment]
Wow those new recipes are extremly cheap wtf. 
I would lower the crafting of using 3 (or maybe even 2) of the pervious tier, that way you gain something by adding higher tier circuits and another assembling step. 

For non recursive craftings i would suggest using filed gens (starting at LV for a 4k cell, then T+2 for each higher cell => HV=16k, IV=64k, ZPM=256k, UHV=1024k. Higher Tiers shall stay with recursive only crating but can use the single step crafts (that you can make with field gens). These arent supposed to completly replace the current recipes but instead enable a less recursive steps alternative for the later tiers. That way it would be a bit like circuits and then the shortcut via SOC etc. You shouldnt be independend on making 16000 1k storage components in UEV, but you also shouldnt be able to simply carft a 16M cell in one step in UV!. 

Its a bit like circuits, your only option to get the highest tiers is by using 3 steps of 2 previous ones. 

I did not intend to buff me cell so that they are basicly free for unlimited storage but to enable a replacement with less recursive crafting but higher tier materials.

**Comment by Alexdoru** [comment]
ok so I did an excel and I got this : 
This is the cost of the crafting recipe currently: 

![image](https://user-images.githubusercontent.com/57050655/115940016-6029b200-a4a0-11eb-861d-35366bffca3f.png)

it is expensive and you don't "benefit" when combining cells together because you pay the cost of 4 cells + circuits to get the storage amount of the 4 cells 

this is for 3 items in the recursivity crafting : 

![image](https://user-images.githubusercontent.com/57050655/115940089-99fab880-a4a0-11eb-97d6-51947d87d3ce.png)

Note that it is already way cheaper, my recommendation would be to keep the recipe we have in the game now and replace the top middle cell by a tiered metal plate or a charged certus quartz dust, whatever.

![image](https://user-images.githubusercontent.com/57050655/115940251-1c837800-a4a1-11eb-92e2-390188ffb09e.png)


I think we need to keep the recursivity for the following reason : 

With recursive crafting you can keep the cells that you crafted from the beginning and continuously upgrade them as you progress throught the tiers. And with the little cost of some extra circuits you get 33% more storage by combining 3 storage component together.

Thank you for comming to my Ted Talk

**Comment by Alexdoru** [comment]
Also bot said that while he agrees with the fact that the total quantity of components should be reduced to craft the cells, he still wants the 16384k cells to be expensive to make the inf chest.

So why not make the 4096k cells require ZPM circuits instead of LuV and the 16384k require UHV instead of UV.
As I said on discord when playing the game from EV to UV you don't need more than 64k cells in your main AE system and 1024k cells in your ore processing system. At least before you have the void miner (for that you use quantum chests and a trashcan)
So making the 4096k and 16384k use higher tier circuits wouldn't hurt anyone considering the overall quantity of materiel is already greatly reduced by switching to 1:3 recursivity

**Comment by Florexiz** [comment]
Full support for reducing prev. tier storage usage to 3. Replacing them entirely with plates makes them stupidly cheap

**Comment by Prometheus0000** [comment]
The chart was very helpful, thanks. I adjusted the recipes.

The first 4 have 2 components changed to tiered plates.
![image](https://user-images.githubusercontent.com/8517039/115962590-2ed5d400-a4ea-11eb-8e2e-860c6e362980.png)
![image](https://user-images.githubusercontent.com/8517039/115962596-32695b00-a4ea-11eb-82b2-c0d36833572c.png)
![image](https://user-images.githubusercontent.com/8517039/115962602-385f3c00-a4ea-11eb-97af-8fb8493db6c9.png)
![image](https://user-images.githubusercontent.com/8517039/115962605-3bf2c300-a4ea-11eb-82e4-2e3a66a277c2.png)

Then it gets _more expensive_.
![image](https://user-images.githubusercontent.com/8517039/115962634-57f66480-a4ea-11eb-8ff7-545929fda4ba.png)
Iridium plates and ZPM circuits and voltage.
Alt 256k
![image](https://user-images.githubusercontent.com/8517039/115962641-617fcc80-a4ea-11eb-91e5-407180f3627d.png)
ZPM field gens and americium.
![image](https://user-images.githubusercontent.com/8517039/115962701-a0158700-a4ea-11eb-9966-7c2fa562a571.png)
Osmium+UV.
![image](https://user-images.githubusercontent.com/8517039/115962707-a60b6800-a4ea-11eb-9708-ceb7753ee4de.png)
Neutronium+UHV.
![image](https://user-images.githubusercontent.com/8517039/115962723-b28fc080-a4ea-11eb-94a8-95dfb23876fc.png)
Bedrockium+UEV.

So now the lower tiers are reasonable, and the higher ones are masochistic. Which people want, apparently. And you can skip to the 5th one. I think people will use drawer cubes instead though.

**Comment by botn365** [comment]
should be a recursion of 3 for all of them
and for the singles 1(2) plate is to cheap should be 4 compressed plate

for assembler recipes
do only 4 circuits and 1 tier processor
and no extra fluix 

alt recipe is fine but what field gen is that
and non alt should at be LuV or less

and al the assembler recipes can be tierded down exept for alt wich should stay zpm

**Comment by 0lafe** [comment]
should put alt recipes in the assline line lapos

**Comment by botn365** [comment]
alt being assline sounds like a good idea but only the alt

**Comment by Prometheus0000** [comment]
> should be a recursion of 3 for all of them

This is a compromise. Between 0 and 4.

> and for the singles 1(2) plate is to cheap should be 4 compressed plate

I don't really see why?

> and no extra fluix

How much fluix is extra?

> alt recipe is fine but what field gen is that

It says ZPM right under it?

> and non alt should at be LuV or less
and al the assembler recipes can be tierded down exept for alt wich should stay zpm

>Also bot said that while he agrees with the fact that the total quantity of components should be reduced to craft the cells, he still wants the 16384k cells to be expensive to make the inf chest.

I made them expensive for you.

> alt being assline sounds like a good idea but only the alt

You can't do that in script, so I don't want to.

> should put alt recipes in the assline line lapos

Make a ticket.

**Comment by Alexdoru** [comment]
> > Also bot said that while he agrees with the fact that the total quantity of components should be reduced to craft the cells, he still wants the 16384k cells to be expensive to make the inf chest.
> 
> I made them expensive for you.
> 

the idea is to make all the recipes cheaper in terms of quantity and then for the last two tiers make them a bit more expensive in a way that it still a bit expensive compared to what is in the game right now

**Comment by Alexdoru** [comment]
Note : while I think of it, should we apply the same changest to the fluid cells and essentia cells

**Comment by joshaup1999** [comment]
> Note : while I think of it, should we apply the same changest to the fluid cells and essentia cells

Would probably be a smart idea, they’d have the same issue with the recurring crafting. Wouldn’t be hard adjusting them once we have an agreement on the standard recipe

**Comment by Alexdoru** [comment]
![image](https://user-images.githubusercontent.com/57050655/115965522-f6ee8100-a529-11eb-9601-980095348b1b.png)

I made it 3:1 recursive crafting and added some tiered metal plates, the 1024k is obtainable after the platline in late IV wich is when you might need it if you have a serious mining addiction.

I also uptiered the circuits for the 4096k and 16384k : 
 now it's ZPM circuits for the 4096k
and UHV circuits for the 16384k

**Comment by GTNH-Afx237v7** [comment]
Oredicted circuits? Guess the components are assembler recipes, or shaped crafting?

**Comment by Florexiz** [comment]
> ![image](https://user-images.githubusercontent.com/57050655/115965522-f6ee8100-a529-11eb-9601-980095348b1b.png)
> 
> I made it 3:1 recursive crafting and added some tiered metal plates, the 1024k is obtainable after the platline in late IV wich is when you might need it if you have a serious mining addiction.
> 
> I also uptiered the circuits for the 4096k and 16384k :
> now it's ZPM circuits for the 4096k
> and UHV circuits for the 16384k

Maybe we should increase tier of used plates? They are too cheap imo

**Comment by 0lafe** [comment]
that's true. up to 64k is too cheap imo. i also think we should go back to LV circuits in 1ks

**Comment by Florexiz** [comment]
This can also remove 1 tier skip in used circuit tiers

**Comment by johnch18** [comment]
> > ![image](https://user-images.githubusercontent.com/57050655/115965522-f6ee8100-a529-11eb-9601-980095348b1b.png)
> > I made it 3:1 recursive crafting and added some tiered metal plates, the 1024k is obtainable after the platline in late IV wich is when you might need it if you have a serious mining addiction.
> > I also uptiered the circuits for the 4096k and 16384k :
> > now it's ZPM circuits for the 4096k
> > and UHV circuits for the 16384k
> 
> Maybe we should increase tier of used plates? They are too cheap imo
> In starting circuits

It should be NaqAlloy if we want to keep consistent

**Comment by Prometheus0000** [comment]
> Note : while I think of it, should we apply the same changest to the fluid cells and essentia cells

I have no problem with that later.

> I also uptiered the circuits for the 4096k and 16384k

I hate inconsistency.

> I made it 3:1 recursive crafting

I still like 2:1 better. And you didn't list any shortcut one, so that makes it still cancerous.

> Maybe we should increase tier of used plates? They are too cheap imo

> It should be NaqAlloy if we want to keep consistent

Plates should match the tier of circuits, and be the tier material. And replacing steel with naquadah alloy, really? And no tier uses this material in hulls.

> i also think we should go back to LV circuits in 1ks

It's supposed to be less expensive, not more.

**Comment by botn365** [comment]
2:1 would be way to cheap

**Comment by Prometheus0000** [comment]
Only according to the people posting here recently, who are basically all in the 'I love recursive crafting' club.

**Comment by boubou19** [comment]
can we have some numbers for the 2:1?

**Comment by botn365** [comment]
i hate recersion and i see why alexduro wants it and my proposal is keep the 4:1 recursion and have for evry 2 tiers a second recipe that does not use recursion

**Comment by Prometheus0000** [comment]
Personally I don't understand alex's argument about 

> With recursive crafting you can keep the cells that you crafted from the beginning and continuously upgrade them as you progress throught the tiers

Just disassemble them? It works, I tried it.

**Comment by botn365** [comment]
there is somthing fun about being able to upgrade you old parts 
thats why alt recipes is perfect you can still upgrade old components but making the higest componets doesent need a +100K items

**Comment by Prometheus0000** [comment]
Please suggest some alt recipes then, because I didn't see you do so?

**Comment by Alexdoru** [comment]
> can we have some numbers for the 2:1?

![image](https://user-images.githubusercontent.com/57050655/115968360-e9d88e80-a537-11eb-9b88-52b83f13e7f7.png)

**Comment by Alexdoru** [comment]
> i hate recersion and i see why alexduro wants it and my proposal is keep the 4:1 recursion and have for evry 2 tiers a second recipe that does not use recursion

My idea is to go with 3:1 recursion and the item on top is up to discussion, I put some random plates as an example. 
And my idea of 3:1 doesn not exclude at all some one step shortcut recipes, I welcome it

**Comment by Prometheus0000** [comment]
Personally I'd like 2:1 for the first 4 and 4:1 for the last 4, though if the alt recipes aren't absurd it won't matter.

**Comment by Alexdoru** [comment]
> > I also uptiered the circuits for the 4096k and 16384k
> 
> I hate inconsistency.

the current recipes are inconsistent, the last tier is UV instead of ZPM.

Also I chose ZPM and UHV for the last two tiers because you only use those when crafting an inf chest, it was to pump up the cost a bit.

**Comment by NeroOneTrueKing** [comment]
If the cost of the last components has to be high because they're used in the infinity chest... why not add a sub-recipe that is expensive, instead of making the storage components themselves overpriced?

Like, 8x 4096k storage components around a LuV field gen to create one subcomponent, and 8x 16384k storage components around a ZPM field gen to create another subcomponent, and use those subcomponents instead of the normal storage components in the infinity chest recipe.

This way, storage component crafting remains consistent even at the highest tiers, while still keeping the price of an infinity chest high.

**Comment by Yarntheory** [comment]
I would like to note, a 64k ME storage drive stores the same number of items as a storage drawer with 4 emerald upgrades and a void upgrade.

ME storage components should be cheaper, not more expensive. Players should be incentivized to use AE2 for server and game performance.

**Comment by Alexdoru** [comment]
> I would like to note, a 64k ME storage drive stores the same number of items as a storage drawer with 4 emerald upgrades and a void upgrade.
> 
> ME storage components should be cheaper, not more expensive. Players should be incentivized to use AE2 for server and game performance.

But that’s only for storing one item, otherwise you would need 63 drawers with upgrades to do the same thing as the ME cell. And your argument also applies to vanilla recipes, a bunch of wood and emerald will always be cheaper than me components. So what’s your point ? We should make them dirt cheap ? No

And the point of this ticket is to make them cheaper, I proposes recipes that makes them way cheaper than what it is now

**Comment by Yarntheory** [comment]
That is a 64k drive storing a single item type. A storage drawer with all 5 upgrades holds 655,360 items, so it holds more than a full 64k drive. A 16M storage drive, with a full set of 63 types, should store 68,157,440 items, or ~1.08 million items per type.

**Comment by Sphyix** [comment]
I like the recursion at 2, but I think it makes the 16384k way too cheap.
What about just splitting recursion and doing recursivity at 2 for 1k to 64k and at 4 for 256k+?
![chrome_TzBEDPPqL0](https://user-images.githubusercontent.com/17811922/116174139-21992f00-a70e-11eb-9b44-b2d8bff70bc2.png)
![chrome_TWGKrJnsZK](https://user-images.githubusercontent.com/17811922/116174524-e2b7a900-a70e-11eb-8ba7-11744d10adf7.png)

Threw down some numbers just to see what's the result, 16384k are expensive as needed, rest is cheaper.
Numbers for the 256k+ can be tweaked by adjusting the number of circuits and processors used.
I'm just not sure about the 64k, maybe it's too expensive compared to the 256k?

**Comment by 0lafe** [comment]
drawers have a lot of downsides to the drives though. You make a stack of drives and shift click them into a single block, but with drawers you need to place them down individually and fill them with upgrades. Not to mention they can't dynamically allocate their overall capacity between item types, giving some larger inefficiencies. 

One issue here is that when cost is the only component, the balance has issues when looking across tiers. You generally are gaining quite a lot of processing ability each tier in the early game, and drawers are craftable in stone age. The upgrades are LV/MV, so by the time you reach EV and get AE, your processing ability has become so tremendous in comparison to your increased need for storage. There isn't a good way to give it a good cost for the utility within the tier. 

Imo an easy solution is to give drawers other downsides that make them unusable by AE tiers, forcing the player into making AE drives. This allows us to give them any cost we want, and it would theoretically still be worth it. Personally I think putting more epoxy in them would be a fun change, as we have yet to really reach possible EV+ levels of oil derivative usage. 

I think a very simple change could be to throttle the throughputs on drawer controllers. Let them check a drawer once per second or once per few ticks. That would allow them to work well for ores and dusts in early game, however any automated input would probably struggle and cause the player to look for alternatives. If the drawers controllers search less often, that would probably also be better for performance on what could be very large drawer networks.

**Comment by leagris** [comment]
Throttling drawer controllers, is one tool to reduce drawers spam, the other tool is to limit the number of controlled drawers and the area size, which are both configurable options (As I already featured the former. I can certainly turn controller search tick rate into an option as well).

Although, reducing the service of mod features shall remain a last resort option.

Priority shall be to preserve services and improve but not degrade content. (You don't cut-out bits of feet when shoes are undersized).

So, lets continue to focus on improving the service and cost/benefit ratio of ME disks and drives before cutting-out bit of the drawers.

**Comment by Dream-Master** [comment]
lets use a 3:1 ratio not ix it up. And yes plates are to cheap

**Comment by Prometheus0000** [comment]
ix?

**Comment by Dream-Master** [comment]
mix

**Comment by Alexdoru** [comment]
The lord has spoken, what should we put instead of the plate for 3:1?

**Comment by johnch18** [comment]
> > It should be NaqAlloy if we want to keep consistent
> 
> Plates should match the tier of circuits, and be the tier material. And replacing steel with naquadah alloy, really? And no tier uses this 

I meant that the ZPM component should use Naquadah Alloy rather than Naquadria because ZPM components use NaqAlloy. Also, the default AE2 balance is 3 T-1 components => 1 T component.

**Comment by NoX-programer** [comment]
So, how will looks recipes after all decisions/suggestions? (less recursive (alt recipes is good!), 3:1 ratio, maybe some fun chem like polycaprolactam, epoxy etc.)

**Comment by repo-alt** [comment]
The recipes being put to vote are pure madness, we should promote higher tier storage, not forbid them. Otherwise we should forbid storage buses on super chests, because no sane person would spend a lot of UHV circuits on a _cell_, that does the same as storage bus (a bit more efficiently for the server, but the player doesn't see that)

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/119016627-2a290200-b968-11eb-94ae-55604d211313.png)
So comparing them to SC/QCs, the 256k holds ~2M, 1/2 of a SC I, the 1024k ~8M about the same as a SC II, the 4096k ~32M about the same as a SC IV, and the 16384 ~128M which is the same as a QC I. 

So why should they be more expensive? You're going to be formatting them to hold one thing at this level, so multiple items in one cell is irrelevant. Why not just add a SC/QC -> Component recipe?

**Comment by mitchej123** [comment]
> Why not just add a SC/QC -> Component recipe?

<3

**Comment by botn365** [comment]
> So why should they be more expensive? You're going to be formatting them to hold one thing at this level, so multiple items in one cell is irrelevant. Why not just add a SC/QC -> Component recipe?

i for sure dint ae was general storage al spesific mass storage was QC/infinity schest
i would stil have liked QC more sinse they have everflow void but they have trouble saving their contents

**Comment by repo-alt** [comment]
So, essentially you say that we don't need larger storage cells and promote Quantum chests instead? That is probably ok

**Comment by Prometheus0000** [comment]
I say add voiding to cells (workbench option, like formatting) _and_ and even larger ones. And/or single type ones, and/or voiding ones.

**Comment by repo-alt** [comment]
Add a separate issue about that, maybe that is not so hard to implement

**Comment by repo-alt** [comment]
If some non-recursive version of recipes will be accepted, I think recursive recipes need not be removed, because they are useful to recycle low tier cells.

**Comment by KamenriderZO** [comment]
In my opinion : No matter which type of components, they all can hold only 63 types of items.
Higher tiers only increase the storage.So the recipe just need 1 lower Tier component.
We should use 1:1 recursion.
And other material could be expensive:maybe +4 different type of chest or single type item storage (super chest)
and other things.
To consider function.1k and 2048k they all just save 63 types. so it means just upgrade the capacity.
If you use 4:1 or 3:1 recursion,why the higher tier components can't save 63^(4n) type items???

**Comment by querns** [comment]
Perhaps making circuit assembly line recipes for ME storage components might be of help? Not only does it allow for easy batching, but there can be SoCs involved to ease the material requirements (or, heck, even entirely new wafers made with fluix/certus/nether lenses or whatever.)

**Comment by Glease** [comment]
So, do we have a consensus now?

**Comment by bombcar** [comment]
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/241

**Comment by ArtherCasan** [comment]
This is too cheap now. I think multiply recipe time by 20 or 30 times and add a same voltage level Field Generator each recipe will be ok.

**Comment by Sphyix** [comment]
> This is too cheap now. I think multiply recipe time by 20 or 30 times and add a same voltage level Field Generator each recipe will be ok.

Adding same tier field gen would make them go tier+1
Multiplying recipe time by 30 just doesn't make sense. The whole point of this is that right now they are kinda cheap already, but they take a lot of time to make because of the recursion.

**Comment by repo-alt** [comment]
I think the recipes are (finally) ok, because the situation when infinity chest is way cheaper than 256 max size cells is weird (and bad for servers).
