### ISSUE TITLE
Aqua Regia doesn't have an LCR recipe [suggestion]

### ISSUE THREAD

**Issue by Leche-Caliente** [GTNewHorizons/GT-New-Horizons-Modpack#7843]
Title, at the moment Aqua Regia can only be made in a mixer, which means the only multiblock option for making it is the GT++ industrial mixer or a processing array. I believe that there should be an LCR recipe for it as well.

I know that aqua regia is a mixture and not a compound, but other simple mixtures like diesel have LCR recipes already, so I don't believe that adding one for aqua regia would be inappropriate.

**Comment by botn365** [comment]
mixer is mixer not chemical reactor so no should not be a LCR recipe

**Comment by joshaup1999** [comment]
> mixer is mixer not chemical reactor so no should not be a LCR recipe

Same can be said then for diesel, since that’s just a mixer recipe

**Comment by bartimaeusnek** [comment]
Not meant to have one.

**Comment by Leche-Caliente** [comment]
> mixer is mixer not chemical reactor so no should not be a LCR recipe

>I know that aqua regia is a mixture and not a compound, but other simple mixtures like diesel have LCR recipes already, so I don't believe that adding one for aqua regia would be inappropriate.

Please at least read my post before commenting.

**Comment by Leche-Caliente** [comment]
> Not meant to have one.

Is there a reason why it isn't intended? Just to make platline people deal with singleblocks/cells?
