### ISSUE TITLE
aqua regia should be a 1:3 mixture of nitric acid and hydrochloric acid.

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#7844]
Aqua regia (/ˈreɪɡiə, ˈriːdʒiə/; from Latin, lit. "regal water" or "Royal water") is a mixture of nitric acid and hydrochloric acid, optimally in a molar ratio of 1:3.(wikipedia)

**Comment by Glease** [comment]
So what's your suggestion? Renaming or recipe change?

**Comment by GTNH-Afx237v7** [comment]
Currently it's a mixture of Nitric acid and diluted sulfuric acid - which is also output when processing platinum solution, so it would require to change this recipe as well (if the acid is to be recycled). Personally I believe the platline is already a large enough dump for chlorine, so I suggest we keep the recipes as is but add an LCR one for nitric acid as mentioned in #7843.

**Comment by iouter** [comment]
> So what's your suggestion? Renaming or recipe change?

recipe change. maybe use the gt6 recipe, mix 2000L of hydrochloric acid and 1250L of nitric acid to 3250L of aqua regia.

**Comment by iouter** [comment]
> Currently it's a mixture of Nitric acid and diluted sulfuric acid - which is also output when processing platinum solution, so it would require to change this recipe as well (if the acid is to be recycled). Personally I believe the platline is already a large enough dump for chlorine, so I suggest we keep the recipes as is but add an LCR one for nitric acid as mentioned in #7843.

if possible, it is better to be more scientific. and only need to change the dilute sulfuric acid to a certain amount of hydrogen chloride.

**Comment by keld0111** [comment]
I’m all for realism.
I **do not** agree with GT6's recipe of: 2000L HCl + 1250L HNO3 -> 3250L (HNO3)(HCl)4
 
![GT6_recipe](https://user-images.githubusercontent.com/78633195/115774033-abe03c80-a376-11eb-8c3b-3406c01b7588.png)

**Assumptions:**
GT:NH “Hydrochloric acid” is concentrated hydrochloric acid, 36% kg HCl/kg so ~11.65M, 11.65 mol/L [1]
GT:NH “Nitric acid” is concentrated nitric acid, 70% kg HNO3/kg so ~15.8M, 15.8 mol/L [1]
For every 1L of Nitric acid, we need ~1.36L of Hydrochloric acid to achieve a 1:1 molar ratio. For the synthesis of Aqua regia, we need a 3:1 molar ratio of Hydrochloric acid to Nitric acid, so we need 3*(1.36L)=4.08, or roughly 4L of Hydrochloric acid for every liter of Nitric acid.

**Chemical reaction for Aqua Regia synthesis** [0]
3 mol HCl + 1 mol HNO3 -> 1 mol “Aqua regia”

**Proposed GT:NH reaction:**
4000L HCl + 1000L HNO3 -> 5000L “Aqua regia”, NOCl + Cl2 + 2H2O

References:
[0]: [https://en.wikipedia.org/wiki/Aqua_regia](url)
[1]: [https://www.nestgrp.com/protocols/trng/molarity.shtml](url)

**Comment by botn365** [comment]
if we would actualy use mols and stuff all of GT chemistry would need to be refractord 
1:3 so 1 bucket of nitric + 3 buckets hydrochloric = 4 buckets of aqua regia

**Comment by bartimaeusnek** [comment]
> 
> 
> if we would actualy use mols and stuff all of GT chemistry would need to be refractord
> 1:3 so 1 bucket of nitric + 3 buckets hydrochloric = 4 buckets of aqua regia

It was like that for a long time, but some people thought it would be "confusing" and "gameplay destroying". So it got removed eventually in like 2.0.4.0 or so

**Comment by Ngar1** [comment]
This change make it more realistic, but is it worth? We should concentrate on realy new funny/sophisticated/.. or failures, i think.
