### ISSUE TITLE
GT++ Wither cage assembler recipe more expensive than crafting table recipe

### ISSUE THREAD

**Issue by Dr-Turtle** [GTNewHorizons/GT-New-Horizons-Modpack#7846]
#### Which modpack version are you using?
2.1.0.6
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### Describe the Issue
The Crafting table requires fewer materials than the assembler recipe with the same output.
#
#### Screenshots
![image](https://user-images.githubusercontent.com/34402990/115746753-97924480-a362-11eb-9263-980ca7c9eba2.png)
![image](https://user-images.githubusercontent.com/34402990/115746783-9f51e900-a362-11eb-83b0-f88fefa44790.png)
#

#### What do you suggest instead/what changes do you propose?
Change the assembler recipe to either require the same materials for the same output or make the assembler recipe more efficient rather than less.
#
#### What is your GTNH Discord username?
`Dr. Turtle#0001`

**Comment by Prometheus0000** [comment]
We can't change GT++ assembler recipes, so this can't be fixed by us

**Comment by Dream-Master** [comment]
@draknyte1 any new about license change ?

**Comment by Dr-Turtle** [comment]
> We can't change GT++ assembler recipes, so this can't be fixed by us.
> 
> Well, I guess we could make the first one give less materials, but do you really want that?

damn, you can't even change recipes? That's dumb

**Comment by Prometheus0000** [comment]
There's no way to remove any machine recipe with MT. Because there's no code support.

**Comment by Dream-Master** [comment]
It is possible but it is tricky and need a lot of work.

**Comment by Prometheus0000** [comment]
We're removing GT++ soon anyway, just use one of the _several_ other options for wither containment.
