### ISSUE TITLE
Oil drilling rigs giving too much oil in modes lower than its maximum

### ISSUE THREAD

**Issue by Dr-Turtle** [GTNewHorizons/GT-New-Horizons-Modpack#7849]
#### Which modpack version are you using?
2.1.0.6
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Set a T2 oil drill to 1x1 mode as opposed to the default 4x4. I expected it to perform operations 16x faster, but only using the amount of oil in the current chunk
#
#### What happened instead? (Attach screenshots if needed)
It was 16x faster as intended, but still gave the same amount per operation (in this case, it was 2356 oil) as if it was in 4x4 mode.
#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
`Dr. Turtle#0001`

**Comment by Alexdoru** [comment]
I don’t understand how this is a bug

**Comment by Dr-Turtle** [comment]
> I don’t understand how this is a bug

It makes 1 chunk mode 16x faster than 16 chunk mode with no penalty - it should either only give the oil from the chunk it's in or an average of all the chunks in the miner's max range rather than the amount it would get when it's set to 4x4 mode but faster.

**Comment by Glease** [comment]
Hi, can you please check if this is still happening in latest dev?
