### ISSUE TITLE
Can't see the circuits recipes

### ISSUE THREAD

**Issue by apk-modpack** [GTNewHorizons/GT-New-Horizons-Modpack#7852]
#### Which modpack version are you using?
a bit special, I used your GT and NEI for developing my own modpack :S
#
#### If in multiplayer; On which server does this happen? 
---------
#
#### What did you try to do, and what did you expect to happen?
I have the circuits in the NEI, but I can't see the recipes
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
i don't find the discord link :S

**Comment by Prometheus0000** [comment]
https://discord.gg/EXshrPV for the server. Circuit recipes might be defined in the MT scripts folder, the GTNH coremod, GT, or in tectech for the highest tier.

That said, this is not the place to ask for help with making your modpack, go do that on the server and see if anyone wants to help you.
