### ISSUE TITLE
Thaumic restorer OP with BM flight flasks and printing press plates

### ISSUE THREAD

**Issue by Dr-Turtle** [GTNewHorizons/GT-New-Horizons-Modpack#7853]
#### Which modpack version are you using?
2.1.0.6
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What do you suggest instead/what changes do you propose?
The thaumic restorer currently allows repairing of the BM flight flasks and printing press plates although these items are intended to be used a few times before breaking. In the case of the flight flasks, it allows for creative flight very early-game only using a couple instrumentum to recharge the flask.

With printing press plates, it allows for duplicating books while only needing to spend the xp once.

I suggest that both of these items should be blacklisted from the thaumic restorer. I assume this is not too difficult as there are many items in the pack with durability that cannot be placed in the thaumic restorer.
#
#### What is your GTNH Discord username?
`Dr. Turtle#0001`

**Comment by Prometheus0000** [comment]
_Is_ there a blacklist?

**Comment by Dr-Turtle** [comment]
> _Is_ there a blacklist?

I assumed so, but i can't find one - not sure why some items can't be placed in it.

**Comment by Glease** [comment]
There is no such thing as an explicit blacklist. Items got a value set to signal it cannot be repaired, e.g. by anvil. Restorer will simply use that value.

**Comment by NoX-programer** [comment]
also, `<MagicBees:frameOblivion>` ;-)
it's almost like
`sv_cheats 1`
