### ISSUE TITLE
Make Bartworks tiered glass recipes non-recursive 

### ISSUE THREAD

**Issue by redmage17** [GTNewHorizons/GT-New-Horizons-Modpack#7857]
I really don't care if we have to increase the costs to make up for not using prior tiers. Or increase the steps used to make the blocks. I just find it silly you need to used the materials from 5 tiers prior to make these things. 

Also pouring molten metal onto glass does not make glass. It makes metal slag covering cracked glass.

My initial idea was something like 1 chromeframe+ 2 stacks of chrome foil + 9 buckets of molten borosilicate glass = chrome reinforced borosilicate glass block in the ebf. I'd be willing to code this myself but want to see how receptive it is before spending a few hours on it. Other ideas include dusts similar to the ytrium thorium glass recipe

**Comment by johnch18** [comment]
That's still just [METAL]+glass, so what's the functional difference

**Comment by redmage17** [comment]
> 
> 
> That's still just [METAL]+glass, so what's the functional difference

The original recipe requires a block of tiered glass from the previous tier, in this instance tungsten reinforced glass, this repeats tier after tier

**Comment by 0lafe** [comment]
imo if you want to remove recursion you should make the single step recipe take longer/cost more. if it's simply better that seems wrong imo. iirc much of the cost of the glass was the solidifying of the previous glass, so if that's gone we might want really long ebf times to compensate. 

if one path is more steps and more setup (recursion) it should compensate by being cheaper/faster to produce once setup

**Comment by mitchej123** [comment]
>  you should make the single step recipe take longer

No.  Recursive crafting is cancer.

**Comment by 0lafe** [comment]
it gives a good cost to things in a very natural way. often times the good cost challenges don't come from new items, but rather being able to achieve such large quantities of items that are normally not used much. 

if you don't want to do that, an alternative is good, but it being easier and cheaper is just retarded

**Comment by mitchej123** [comment]
I've no objection to it being equivalent cost, but fuck recursive crafting.

**Comment by redmage17** [comment]
> 
> 
> imo if you want to remove recursion you should make the single step recipe take longer/cost more. if it's simply better that seems wrong imo. iirc much of the cost of the glass was the solidifying of the previous glass, so if that's gone we might want really long ebf times to compensate.
> 
> if one path is more steps and more setup (recursion) it should compensate by being cheaper/faster to produce once setup
> 
> alternatively you could put a lot of costly/complex materials in the single step recipes. like Eu in the LuV glass or Nq+ in the IV one

If we remove al
