### ISSUE TITLE
Iridium ingots can be crafted from the ore without platline

### ISSUE THREAD

**Issue by Leche-Caliente** [GTNewHorizons/GT-New-Horizons-Modpack#7858]
#### Which modpack version are you using?
2.1.0.6b

![2021-04-24_14 03 14](https://user-images.githubusercontent.com/64061913/115972917-30ad9080-a506-11eb-8258-7bc5a417c817.png)
![2021-04-24_14 03 38](https://user-images.githubusercontent.com/64061913/115972920-330fea80-a506-11eb-8345-c9dfefa9b785.png)

I've been told this is unintended, so I posted it here.

**Comment by Dream-Master** [comment]
yea shitty ic2. Will check that

**Comment by Leche-Caliente** [comment]
Also just found this one.

![2021-04-27_11 46 57](https://user-images.githubusercontent.com/64061913/116296265-dce1b800-a74e-11eb-9635-03524169aa8e.png)

Purified iridium ore sifting for ic2 ore + iridium metal residue.

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/117185793-3594fe80-ada8-11eb-8115-da181f5d7844.png)
