### ISSUE TITLE
bloodmagic questline issue

### ISSUE THREAD

**Issue by hebiohime** [GTNewHorizons/GT-New-Horizons-Modpack#7859]
v2.1.0.0
the titanium quest required for bloodmagic quest line seems in error
![unknown](https://user-images.githubusercontent.com/13721540/115980083-e6ed9600-a557-11eb-9614-83ce0c0218d5.png)
![unknown](https://user-images.githubusercontent.com/13721540/115980086-ef45d100-a557-11eb-9042-5439ae4e2998.png)
maybe the normal titanium quest would fit better in that spot, i haven't touched bees atall
![unknown](https://user-images.githubusercontent.com/13721540/115980096-01c00a80-a558-11eb-9692-0b93afddecb4.png)

**Comment by Prometheus0000** [comment]
Update your version

**Comment by Dream-Master** [comment]
To be fair 2.1.0.0 is the last stable version. 2.1.x.x just dev versions. So a label fix in dev would be  better.
