### ISSUE TITLE
[Suggestion] R click block

### ISSUE THREAD

**Issue by 0lafe** [GTNewHorizons/GT-New-Horizons-Modpack#7861]
#### Which modpack version are you using?
2.0.1.6
#

I think it would be nice to have a 3rd option for r clicking items. At the moment we have golems with use cores, and OC, but that's it. Imo it would be nice to have something like a mechanic user from exu2 to automate things like placing covers on hatches

**Comment by boubou19** [comment]
dynamism tablets?

**Comment by 0lafe** [comment]
they kind of work, but seem to have weird hit boxes on some hatches and from my experience can't place covers on the top/bottom of the hatches

**Comment by glowredman** [comment]
Stripes Transport Pipes have right-click behavior aswell, though somewhat limited: https://minecraftbuildcraft.fandom.com/wiki/Stripe_Pipe

**Comment by 0lafe** [comment]
if that can place on the top/bottom of blocks then that's perfect

**Comment by 0lafe** [comment]
I'm not sure if I'm just using the stripes pipe wrong, but it doesn't seem to be able to place covers on blocks, or use tools on them. It can place blocks fine, but doesn't seem to have good item interactions. 
![2021-04-26_15 31 12](https://user-images.githubusercontent.com/21280852/116140012-b23b2500-a6a4-11eb-8255-1f71517cbdb7.png)

Dynamism tablets have this issue in which they place covers on seemingly the wrong face of the block, and are unable to use tools on them. 

![2021-04-26_15 34 09](https://user-images.githubusercontent.com/21280852/116140470-5f15a200-a6a5-11eb-83b1-736bf0f5f357.png)

Golems seem to be the only option beyond OC but they have some issues. They like falling through the floor and generally being quite strange to work with. There's two other downsides to golems. Some actions need a 2nd item in the inventory, such as the soldering iron. This is essentially impossible with golems as they can only hold 1 item type. The other issue is that some covers need to be clicked on in a certain spot on the face. Iirc the mech user can specify up/down on where to click the block, which is quite useful here
