### ISSUE TITLE
visual doubling items in ME system

### ISSUE THREAD

**Issue by TA0MACHINE** [GTNewHorizons/GT-New-Horizons-Modpack#7862]
Version 2.1.0.0 23.12.2020
multiplayer: Eta
if connected to compressed chest 2 storage buses and put items in this chest it will shows double quantity of items.

![Снимок экрана 2021-04-25 204933](https://user-images.githubusercontent.com/42874669/116003940-13151f80-a609-11eb-8d93-7906c838ee5b.png)

**Comment by GTNH-Afx237v7** [comment]
Is it the same with normal chest or drawer or any other inventory that a storage bus can read? To identify if this is bound to Avaritia or AE.

Eventually, I don't see why someone would put more than one storage bus on an inventory or a machine?

**Comment by TA0MACHINE** [comment]
you have, for example, the main wires, which are needed a lot and the same but 12x, which are rarely used and there are ~ 12 of them (the same about triple plates etc.). So as not to occupy the volume of ME drivers it is convenient to do so.
With  vanilla chest the same.

**Comment by alphaNOVAircraft** [comment]
You can adjust one of the storage bus to not allow extraction and then to only report items to the system that are extractable. i have 3 storage bus on my infinity chest and i dont see the items double with that setup

**Comment by TA0MACHINE** [comment]
there must be-directional mode, this chests is a part of ME storage system, so I don't understand how I not allow extraction

**Comment by GTNH-Afx237v7** [comment]
One of the storage buses will be bi-directional, the other will be insert only and "do not report inaccessible items". So you can insert with both busses, one of them can also extract and no visual item doubling

**Comment by TA0MACHINE** [comment]
thanks, it can be solved like this

**Comment by GTNH-Afx237v7** [comment]
May I suggest you close this then?
