### ISSUE TITLE
Crops+UUM -> Ichorium needs way too much UUM per ingot

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#7863]
#### Which modpack version are you using?
2.1.0.6
#
#### What did you try to do, and what did you expect to happen?
Just browsing through uses of primordial pearls, I saw you can extract them into magic essence, and turn that into Ichorium...
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/28197216/116019420-c847d780-a609-11eb-9f9d-45ed9bd4940f.png)
That is 190,000 UUM per ingot. What the heck.
#
#### What do you suggest instead/what changes do you propose?
Reduce the UUM cost to be the same as other silly crops+UUM -> materials recipes, like space plutonium; 1,000 UUM per recipe. 
![image](https://user-images.githubusercontent.com/28197216/116019598-2eccf580-a60a-11eb-9925-4d6fca5d36b0.png)
#
#### What is your GTNH Discord username?
NeroOneTrueKing

**Comment by 0lafe** [comment]
we should remove that recipe imo. Ichorium is one of the only nice infusion reqs we have, especially with its DE integration

**Comment by NeroOneTrueKing** [comment]
I mean that would be fine too. It just seems absurd to have a recipe that takes 190k UUM for something that isn't UHV+ or stargate-level.

**Comment by Prometheus0000** [comment]
I vote for removal as well, just make it the normal way.
