### ISSUE TITLE
Adding LittleTiles to the pack

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#7864]
What do you suggest instead/what changes do you propose?

What’s everyone’s opinion on adding Littletiles to the pack? Would be a nice mod to make a lot of nicer builds. Not sure how limited the functionality of it is compared to 1.12, but either way would add a new depth to base building and aesthetics 

https://www.curseforge.com/minecraft/mc-mods/littletiles

What is your GTNH Discord username?

Lord Peverell, Master of Death#3125

**Comment by Prometheus0000** [comment]
Don't we already have something that does this?

**Comment by GTNH-Afx237v7** [comment]
3D printing from OC. Next best thing is probably Architecture Craft. There was already an issue about adding littletiles however it was closed as support for this mod was/is considered unclear.

**Comment by GTNH-Afx237v7** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/4055 The first issue as just mentioned

**Comment by Ngar1** [comment]
The actual licence of LitleTiles allows modification. If there is someone to maintain the 1.7.10 Version, than it could be ..

https://github.com/CreativeMD/LittleTiles/blob/1.12/LICENSE

**Comment by Dream-Master** [comment]
its a license for 1.12 not sure if we have one for 1.7.10.

**Comment by GTNH-Colen** [comment]
It is a really cool mod just cautious of any potential issues in the 1.7.10 version that could arise as it looks like a complicated mod to try and patch.

**Comment by Cinobi** [comment]
Based on my openPC prints expirience, 3d prints eats freakin TONS of fps, so i'm not sure it's good idea to add smth like this since ppl will spam with structures and come to us crying about fps lags.

**Comment by septemberWaves** [comment]
I recall a while ago seeing someone do some tests with Little Tiles for comparison with Chisels & Bits, and the performance impact from Little Tiles was surprisingly low. I think that was for 1.12 though, and I'm not sure how Little Tiles in 1.7 compares. Having played with the 1.12 version of the mod though, the performance impact from using a lot of microblocks wasn't even significant enough to notice. Compared with Project Red's far more restrictive microblock system, if the 1.7 version is as good as the 1.12 version then it should be better for performance.

**Comment by Prometheus0000** [comment]
We don't have chisels and bits though, so the comparison in meaningless.

**Comment by Ngar1** [comment]
creativmd - autor from LittleTiles, allows GTNH Team maintaining LittleTiles-Mod 1.7.10. I send Dream the original mail (its german ;-).

**Comment by Ngar1** [comment]
Is it planned to implement LittleTiles into GTNH?

**Comment by Dream-Master** [comment]
@Ngar1 did you send me that text ? cant remember

**Comment by Ngar1** [comment]
I sended the Mail as plain text via Discord, but here it is:

Guten Tag,
also ihr könnt gerne die 1.7.10 Version weiterentwickeln. Wäre nur schön, falls ihr das auch releasen wollt (außerhalb des Modpacks), es vorher mit mir anzusprechen.

Gruß Matthias

On 5/12/2021 8:20 AM, noreply@creativemd.de wrote:
You have received a new message from your website contact form.

Message:
Guten Morgen, ich wollte fragen ob die Lizenz für Dein Mod LittleTile 
auch für die 1.7.10 Version gilt. Im GTNH Pack (https://github.com/GTNewHorizons) würde man dieses gern integrieren, doch wegen schlechter Erfahrungen sollte es ein Mod mit der Lizenz zum weiter pflegen sein. Gruß, Gunna

**Comment by Dream-Master** [comment]
ok danke.

**Comment by Ngar1** [comment]
Is there a decission to integrate this mod in GTNH? It would be realy nice!

**Comment by Dream-Master** [comment]
I will  check but not this release. next one

**Comment by Dream-Master** [comment]
We add two more mods to waiting list since we now in the final testing phase and dont add new mods so close to an update.

**Comment by KaneHart** [comment]
Very cool mod. It would need to be tested well but if there's no major issues in the performance is fine I don't see an issue why not. I think a pack like this with a lot of length to it definitely deserves a few more tools to make some more interesting builds.

**Comment by Dream-Master** [comment]
18 upvotes 28 downvotes  15 neutral

**Comment by repo-alt** [comment]
I voted neutral myself, because I don't build, but what is the reason to downvote? As I understand it does not affect those not using it?

**Comment by Dream-Master** [comment]
I just post the result now. Not sure how slow it make the pack if people use it.

**Comment by repo-alt** [comment]
Like, why would it affect TPS at all? As for startup time, it is easy to measure. (Well, all those obvious things shouldbe said by the mod proponents of course.)

**Comment by TimeConqueror** [comment]
I doubt they are not tile entities. TileEntities has impact on storage and afaik on 1.7.10 they all are tickable.

**Comment by repo-alt** [comment]
On storage, like, chunk saving time? ok, it is not impossible, especially if there is a way to automatically create them. As for ticking, there shoudl be some crazy amount of tiles for the empty updateEntity() call to become noticeable...

**Comment by Ngar1** [comment]
where was the voting?

**Comment by Dream-Master** [comment]
> where was the voting?

On Discord

**Comment by Ngar1** [comment]
Again the question for nice buildings:

What better alternative will be there?

-     Architecturecraft has just some example blocks, no one extending them (I tried, but wasnt able to do)
-     Carpeter Blocks stick on some edge blocks for roofs...
-     Chisle and Bits come under criticsm about performance

**Comment by Dream-Master** [comment]
I reopen the issue and maybe we can add it to the zeta test pack and think about to add it.

**Comment by GTNH-Colen** [comment]
How this got rejected but shit like logistics pipes made it's way into the pack will forever baffle me.

**Comment by glowredman** [comment]
> How this got rejected but shit like logistics pipes made it's way into the pack will forever baffle me.

Because LP is *not* shit

**Comment by Dream-Master** [comment]
I hope after the recipe are redone it is much better.

**Comment by hawktechbr** [comment]
If the mod was ever added, would it be a backport from current versions? I ask this because the newer versions have A LOT of features that aren't present in the 1.7.10 version. Other than that I'd love to see this mod in the pack, the amount of building customization it adds makes everything else pale in comparison.

**Comment by Dream-Master** [comment]
if someone is port it back yes.

**Comment by bombcar** [comment]
This is in the 2.1.2.0rc download -intentional?
