### ISSUE TITLE
Gregtech.log spam with 6724 lines of "Unknown Key for Unification, Typo?"

### ISSUE THREAD

**Issue by leagris** [GTNewHorizons/GT-New-Horizons-Modpack#7866]
`Gregtech.log` is spammed by 6724 lines of `Unknown Key for Unification, Typo?` messages.

Maybe we could save some load time by not spamming these messages and fixing the underlying cause:

Here is how to get a report of these from a Linux shell.
```sh
fgrep -F 'Unknown Key for Unification, Typo?' ./logs/GregTech.log |
  cut -d ' ' -f6 | sort | uniq -c | sort -k1nr
```

| Lines   | Ore Dictionary Name              |
|--------:|----------------------------------|
|    5766 | craftingToolScrewdriver          |
|     131 | craftingChest                    |
|      72 | circuitGood                      |
|      63 | circuitData                      |
|      63 | circuitElite                     |
|      57 | cableGt01Tin                     |
|      54 | cableGt01Gold                    |
|      53 | cableGt01AnyCopper               |
|      49 | cableGt01Aluminium               |
|      36 | cableGt01Platinum                |
|      35 | craftingFilter                   |
|      17 | circuitMaster                    |
|      15 | craftingToolWrench               |
|      12 | cableGt01Tungsten                |
|      12 | stickLongGraphene                |
|      11 | circuitUltimate                  |
|       8 | circuitSuperconductor            |
|       8 | craftingGrinder                  |
|       7 | cableGt04Gold                    |
|       7 | wireGt04AnyCopper                |
|       6 | cableGt04Aluminium               |
|       5 | cableGt04AnyCopper               |
|       5 | cableGt04NaquadahAlloy           |
|       5 | cableGt04Tin                     |
|       5 | craftingAnvil                    |
|       5 | craftingDiamondBlade             |
|       5 | pipeMediumBronze                 |
|       5 | pipeMediumSteel                  |
|       5 | pipeMediumTitanium               |
|       5 | wireGt04Cupronickel              |
|       4 | cableGt01Naquadah                |
|       4 | craftingIndustrialDiamond        |
|       4 | pipeLargeStainlessSteel          |
|       4 | pipeLargeSteel                   |
|       4 | pipeMediumStainlessSteel         |
|       4 | pipeMediumTungstenSteel          |
|       4 | plateAnyRubber                   |
|       4 | ringAnyRubber                    |
|       4 | wireGt02AnyCopper                |
|       4 | wireGt04Kanthal                  |
|       4 | wireGt04Nichrome                 |
|       4 | wireGt04TungstenSteel            |
|       3 | cableGt01NiobiumTitanium         |
|       3 | cableGt01VanadiumGallium         |
|       3 | cableGt04Platinum                |
|       3 | cableGt04Tungsten                |
|       3 | circuitInfinite                  |
|       3 | circuitPrimitive                 |
|       3 | craftingToolHardHammer           |
|       3 | stickAnyIron                     |
|       3 | wireGt01AnyCopper                |
|       3 | wireGt02Cupronickel              |
|       2 | cableGt01Lead                    |
|       2 | cableGt02Copper                  |
|       2 | cableGt02Naquadah                |
|       2 | craftingIronFurnace              |
|       2 | rotorLead                        |
|       2 | wireGt01Gold                     |
|       2 | wireGt01Superconductor           |
|       2 | wireGt02Kanthal                  |
|       2 | wireGt02Nichrome                 |
|       2 | wireGt02Tin                      |
|       2 | wireGt02TungstenSteel            |
|       2 | wireGt04Naquadah                 |
|       2 | wireGt04VanadiumGallium          |
|       2 | wireGt08AnnealedCopper           |
|       2 | wireGt16Aluminium                |
|       2 | wireGt16AnnealedCopper           |
|       2 | wireGt16AnyCopper                |
|       2 | wireGt16Gold                     |
|       2 | wireGt16Lead                     |
|       2 | wireGt16Naquadah                 |
|       2 | wireGt16NaquadahAlloy            |
|       2 | wireGt16Superconductor           |
|       2 | wireGt16Tin                      |
|       2 | wireGt16Tungsten                 |
|       2 | wireGt16VanadiumGallium          |
|       1 | batteryMaster                    |
|       1 | cableGt01AnnealedCopper          |
|       1 | cableGt01Copper                  |
|       1 | cableGt01HSSG                    |
|       1 | cableGt01NaquadahAlloy           |
|       1 | cableGt01TungstenSteel           |
|       1 | cableGt02Aluminium               |
|       1 | cableGt02Silver                  |
|       1 | cableGt02Tin                     |
|       1 | cableGt02Tungsten                |
|       1 | craftingToolCrowbar              |
|       1 | craftingToolFile                 |
|       1 | craftingToolSaw                  |
|       1 | craftingToolSoftHammer           |
|       1 | craftingToolWireCutter           |
|       1 | dyeBlue                          |
|       1 | dyeLime                          |
|       1 | dyeRed                           |
|       1 | frameGtSteel                     |
|       1 | frameGtTitanium                  |
|       1 | gearAluminium                    |
|       1 | gearStainlessSteel               |
|       1 | gearSteel                        |
|       1 | gearTitanium                     |
|       1 | gearTungstenSteel                |
|       1 | pipeHugePlastic                  |
|       1 | pipeLargeBronze                  |
|       1 | pipeLargePlastic                 |
|       1 | pipeLargePolytetrafluoroethylene |
|       1 | pipeLargeTitanium                |
|       1 | pipeLargeTungstenSteel           |
|       1 | pipeMediumPlastic                |
|       1 | plateAnyBronze                   |
|       1 | plateAnySyntheticRubber          |
|       1 | ringAnySyntheticRubber           |
|       1 | springCopper                     |
|       1 | springLead                       |
|       1 | springTin                        |
|       1 | wireGt01Aluminium                |
|       1 | wireGt01Electrum                 |
|       1 | wireGt01HSSG                     |
|       1 | wireGt01Lead                     |
|       1 | wireGt01Naquadah                 |
|       1 | wireGt01NaquadahAlloy            |
|       1 | wireGt01Platinum                 |
|       1 | wireGt01Silver                   |
|       1 | wireGt01Tin                      |
|       1 | wireGt01Tungsten                 |
|       1 | wireGt01VanadiumGallium          |
|       1 | wireGt04Aluminium                |
|       1 | wireGt04AnnealedCopper           |
|       1 | wireGt04Electrum                 |
|       1 | wireGt04Gold                     |
|       1 | wireGt04Graphene                 |
|       1 | wireGt04Lead                     |
|       1 | wireGt04NaquadahAlloy            |
|       1 | wireGt04Superconductor           |
|       1 | wireGt04Tin                      |
|       1 | wireGt04Tungsten                 |
|       1 | wireGt08Aluminium                |
|       1 | wireGt08AnyCopper                |
|       1 | wireGt08Gold                     |
|       1 | wireGt08Lead                     |
|       1 | wireGt08Naquadah                 |
|       1 | wireGt08NaquadahAlloy            |
|       1 | wireGt08Superconductor           |
|       1 | wireGt08Tin                      |
|       1 | wireGt08Tungsten                 |
|       1 | wireGt08VanadiumGallium          |
| Total   | 6724 lines                       |

**Comment by Prometheus0000** [comment]
Why are you mentioning a quest here...? Is the quest causing problems?

**Comment by leagris** [comment]
> Why are you mentioning a quest here...? Is the quest causing problems?

please ignore, was some leftover copypaste ^^

**Comment by leagris** [comment]
> looks like it's defined here: https://github.com/Blood-Asp/GT5-Unofficial/blob/77a3c956e510b7c8ef4654054bcb16a0fccb86f7/src/main/java/gregtech/api/util/GT_OreDictUnificator.java#L108

While this is the place the message is generated, the problem is recipes using the Oredictionary Unification class to get an ItemStack from an Ore Dictionary name rather than using the OreDictionary registry when they just need an ingredient or something that is not unificated.

**Comment by boubou19** [comment]
what happens if the devpack is run with this log removed? is it improving noticeably the loading time?

**Comment by mitchej123** [comment]
I'd say we should get to the bottom of why it's being triggered, not just remove the log.
