### ISSUE TITLE
No Way to make Hydrogen Peroxide Cell GT++ as required by questbook

### ISSUE THREAD

**Issue by Dyonovan** [GTNewHorizons/GT-New-Horizons-Modpack#7867]
#### Which modpack version are you using?
2.1.0.6b
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Made the Hydrogen Peroxide in the Chemical Plant and place 2 cells in the output hatch. What was returned was 2 of the BartWorks Hydrogen Peroxide cells. Even tried using different tanks. The questbook is asking for the GT++ cells.
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Change questbook to accept the Bartworks Cells
#
#### What is your GTNH Discord username?
Dyonovan

**Comment by boubou19** [comment]
duplicated of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7833
