### ISSUE TITLE
Occasional crash on searching AE2 terminal

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#7868]
#### Which modpack version are you using?
2.1.0.5
#
#### What did you try to do, and what did you expect to happen?
Searching my AE network caused a hard crash, a few times now.
#
#### What happened instead? (Attach screenshots if needed)
https://pastebin.com/1BtkaV9P
#
#### What is your GTNH Discord username?
NeroOneTrueKing

**Comment by repo-alt** [comment]
What sorting method is set in the terminal?

**Comment by NeroOneTrueKing** [comment]
InvTweaks's sorting, I'm pretty sure.

**Comment by repo-alt** [comment]
Well it basically means that Inventory Tweaks sort item non transitively. That is, from it's point of view it is possible to have A < B, B < C and A > C
