### ISSUE TITLE
Suggestion: add a text in the main menu saying the modpack version

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7871]
Today i had both zeta pack and stable pack opened and on the main menu. I had no way to differenciate them until i go in the multiplayer screen.

I suggest to add something like this:
![image](https://user-images.githubusercontent.com/12850933/116270519-745eff00-a77f-11eb-8f93-1429a3325efc.png)
What do you think?

**Comment by Prometheus0000** [comment]
It also says when you open a world as long as someone updated the text.

**Comment by boubou19** [comment]
So i should open a world to get the pack version i'm running on? that does not sound very convenient.

**Comment by GTNH-Afx237v7** [comment]
The version index on the main menu sounds like a good suggestion boubou.
