### ISSUE TITLE
PH Recipe Conflict 1

### ISSUE THREAD

**Issue by Ian-Hernandez** [GTNewHorizons/GT-New-Horizons-Modpack#7874]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Tried to craft cottage pie, expected to get cottage pie as the output in a crafting table
Tried to craft pork sausage, expected to get pork sausage as the output in a crafting table
#
#### What happened instead? (Attach screenshots if needed)
Tried to craft cottage pie, the output of the recipe was shepard's pie in the crafting grid
Tried to craft pork sausage, the output of the recipe was sausage in the crafting grid
#
#### What do you suggest instead/what changes do you propose?
The recipe should give cottage pie as the output
The recipe should give pork sausage as the output
(both recipes should have something different so that they do not create the same output)
#
#### What is your GTNH Discord username?
EternalVigilante#0467

**Comment by Prometheus0000** [comment]
Cottage pie uses listAllbeefraw. Shepard's pie uses listAllmuttonraw. Just don't use tofu and you should be good for those.
