### ISSUE TITLE
NEI's search item function (t) doesn't work with liquids

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7878]
#### Which modpack version are you using?
2.1.06b
#
#### If in multiplayer; On which server does this happen? 
zeta
#
#### What did you try to do, and what did you expect to happen?
When i use the search function on nei on a liquid it highlights all liquids nearby, not just that specific one.
![2021-04-28_14 39 16](https://user-images.githubusercontent.com/57275066/116448860-f149b180-a82f-11eb-96e0-3f8fe0b8c7bc.png)
![2021-04-28_14 39 14](https://user-images.githubusercontent.com/57275066/116448865-f27ade80-a82f-11eb-99d8-58af055a02dc.png)

**Comment by Prometheus0000** [comment]
Probably because they all use the same ID, but different meta #s.

**Comment by mitchej123** [comment]
This functionality is added by Extra utilities
