### ISSUE TITLE
EC2 autocrafting issues

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#7882]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
Tried to autocraft 5k steel ingots with a recipe set for 256 each time.
![javaw_B64jznVieH](https://user-images.githubusercontent.com/17811922/116625704-614c5a80-a94a-11eb-9b65-2bedcc7ab17f.png)

I used EC2 1024k crafting storage paired with a 64k AE2 crafting storage and some co-processing units
![javaw_bx8B8je7hD](https://user-images.githubusercontent.com/17811922/116625762-7c1ecf00-a94a-11eb-9368-f9dafadb19db.png)

Interface output was set to a buffer chest before sending it to the EBF to smelt.
Expected AE2 to output all the iron dusts to the chest.

#
#### What happened instead? (Attach screenshots if needed)
Crafting started like normal, some stacks of iron are moved, then the crafting stops and the interface stops working for every recipe that is in the same interface.
![javaw_CMF7BFranv](https://user-images.githubusercontent.com/17811922/116625927-c1db9780-a94a-11eb-926f-392cb908af21.png)
![javaw_tZBq7UbtHn](https://user-images.githubusercontent.com/17811922/116625948-c86a0f00-a94a-11eb-8415-d916243d35c5.png)

This doesn't happen if the crafting is started with a crafting cpu with only AE2 crafting storages.
The output of the interface doesn't matter, it locked the crafting when outputting to a chest and to a 16 slot input bus.
Only way to reset it that I know of is removing power to the system and restarting it.
After that an interface is locked during a crafting with EC2 storages, it won't work for AE2 storages either, but starting a new craft using only AE2 storages and moving the recipe to a different interface works.

That's all I tested for now, I'll update if I find anything else.

#
#### What do you suggest instead/what changes do you propose?
Fix it please :)

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by GTNH-Afx237v7** [comment]
EC2 again....
