### ISSUE TITLE
Add Glass dust recipe

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#7883]
#### Which modpack version are you using?
2.1.0.0
#

Glass dust right now is craftable only in shapeless with a tiny pile of flint dust and quartz sand
![javaw_2R3WA6tjXS](https://user-images.githubusercontent.com/17811922/116627203-f3556280-a94c-11eb-889c-f954bb062cc6.png)

And in a mixer with a small pile of flint dust (notice: small) and quartzite/quartz dust
![javaw_Da2s8jPyDR](https://user-images.githubusercontent.com/17811922/116627245-07995f80-a94d-11eb-9adc-bd8e002d3635.png)

Now, the most common source of flint dust is cobblestone -> gravel -> flint -> pulverization/forge hammer -> tiny flint dust
This is convenient for the shapeless as it asks for a tiny.
Or cobblestone -> gravel -> centrifuge -> flint dust
This is not convenient for any recipe as it needs to be crafted to make it small or tiny

It would be a good idea to add a recipe for the mixer accepting 1 tiny pile of flint dust and 1 quartz sand making 1 glass dust or/and a recipe accepting 1 flint dust and 9 quartz sand making 9 glass dust
This would make it possible to create patterns outputting from AE 256 items at a time instead of making 1 glass dust at a time with the molecular assembler, or being forced to use it anyway to make the small dust and 4 glass dust at a time in a mixer.

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by Prometheus0000** [comment]
Just fluid extract sand or use an arc furnace on sand?

**Comment by Sphyix** [comment]
I guess that makes glass that I can then pulverize, totally missed that.
But still I would consider the recipe thing that I said, as it makes not much sense how it is right now.

**Comment by GTNH-Afx237v7** [comment]
As some recipes involving tiny/small dusts have been removed, or are in the process of being removed, we should not add more recipes with tiny dusts.
When do you need lots of glass dust in early game, i.e. before MV arc furnace makes glass really easy? Genuine question, do not mean to sound condescending, as early game has been long ago for me.
