### ISSUE TITLE
Industrial Extrusion do not share casing with other

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#7884]
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
myFTB
#
#### What did you try to do, and what happen?
placed two extruders near by with multi-mashine "case shareing". 

If I placed the second controler beside the first (working!), the first maschine signed as "incomplete structure" and stop working.   

#
#### What do you suggest instead/what changes do you propose?
working case sharing

This issue is placed in GTplusplus by Prometheus0000 as a comment

This mod seems not to be maintained, last changes are 15 months ago
https://github.com/alkcorp/GTplusplus/issues/663

**Comment by GTNH-Afx237v7** [comment]
Not 100% sure about the future of GT++ but a) pls report at original repo and b) don’t expect it to be changed.

**Comment by Ngar1** [comment]
As I said, it is reported by Prometheus0000 as a comment

**Comment by iouter** [comment]
You need to place a controller in the front and a controller in the back

**Comment by Ngar1** [comment]
it can be solved with iouters tipp: controller alternated at back and front side of multiblock
