### ISSUE TITLE
AE2 showing ghost items with buggy recipe

### ISSUE THREAD

**Issue by Savallator** [GTNewHorizons/GT-New-Horizons-Modpack#7886]
#### Which modpack version are you using?
2.1.0.6b
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
With no Interface connected i expected the list of things to craft to be empty. I had Ghost items occuring, and gradually removed parts of the network to see where they come from. I found out they come from the ME Drives itself (see attached Screenshot). I made a test setup containing only 2 drives, a creative energy cell and a terminal. When i try to craft one of them, it just shows it missing (see screen)
![2021-04-30_21 38 42](https://user-images.githubusercontent.com/10967188/116746270-85687400-a9fc-11eb-8ce7-d28964e2772c.png)
![2021-04-30_21 38 48](https://user-images.githubusercontent.com/10967188/116746272-86010a80-a9fc-11eb-9092-2721058b5cd6.png)
![2021-04-30_21 38 53](https://user-images.githubusercontent.com/10967188/116746273-86010a80-a9fc-11eb-9f08-ff1a0be054e2.png)

#
#### What happened instead? (Attach screenshots if needed)
There are several Ghost items.
#
#### What do you suggest instead/what changes do you propose?
Fix it ;-)
#
#### What is your GTNH Discord username?
Boldar#1676

**Comment by Prometheus0000** [comment]
So the encoded patterns are stored in your drive? I'm going to say don't do that? Not that I understand why you would.

**Comment by Savallator** [comment]
No, they are not. It is coming out of nowhere.

**Comment by Savallator** [comment]
But even if they were, a pattern inside a drive should not be shown as craftable...

**Comment by Prometheus0000** [comment]
Did you try placing down new drives and cells? And all new other stuff? Maybe they're bugged, because that should be impossible.

**Comment by repo-alt** [comment]
W/o  a way to reproduce that idk what can I do. Weird bug anyway, first time I see something like that.

**Comment by Savallator** [comment]
It got fixed by dragging the storage cells out and putting them back in.

**Comment by Savallator** [comment]
But i suspect it had to do with lingering recipes, so when you craft something and that gets paused by either power outage or changes to the network.

**Comment by repo-alt** [comment]
well, that _kind of_ makes sense, because craftables are cached along with normal items

**Comment by Savallator** [comment]
Under what conditions is the cache remade?

**Comment by repo-alt** [comment]
Well, it is definitely not saved on disk, so I actually have no idea how it might survive reboot. So much for that idea then...

**Comment by Savallator** [comment]
But it did not have to. The faulty patterns itself were of course still in place after the reboot, i removed them after patching.

**Comment by repo-alt** [comment]
Well, removing the patterns and rebooting should have fixed it then too. If that is the case I think we may close the bug.

**Comment by Savallator** [comment]
It is still a bug though...

**Comment by Savallator** [comment]
when i remove a pattern, why is it not cleared from cache?
