### ISSUE TITLE
Neutronium Comb cann't be produced.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7888]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
mullti and single
#
#### What did you try to do, and what did you expect to happen?
Neutronium queen were breeding for a long time in Industrial Apiary(with 8x Production Upgrade).
![2021-05-01_12 26 27](https://user-images.githubusercontent.com/40425798/116769647-8fc85380-aa78-11eb-8a31-a7398ec63b1e.png)
![2021-05-01_12 26 31](https://user-images.githubusercontent.com/40425798/116769649-90f98080-aa78-11eb-838b-fce8d5e85a30.png)
![2021-05-01_12 26 33](https://user-images.githubusercontent.com/40425798/116769650-90f98080-aa78-11eb-816f-484355e94ea2.png)
#
#### What happened instead? (Attach screenshots if needed)
Neutronium Comb cann't be produced.
#
#### What do you suggest instead/what changes do you propose?
Fix it.
Isn't there a digit cut off somewhere, like 0.0% Comb production in NEI?
#
#### What is your GTNH Discord username?
yukieiji

**Comment by Prometheus0000** [comment]
It's something like 0.000000001%, along with the infinity ones, and no it isn't a bug.

**Comment by yukieiji** [comment]
Why close it?
By installing x8 ProductionUpgrade, the production rate is +160%, but it doesn't produce at all?
Even if the production rate is 0.000000000000001%, if it is +160%, it will be 160.0.000000000000001%, and it is strange that it is not produced, right?

**Comment by Prometheus0000** [comment]
No, it would be more like 0.0000000016%. Or 0.0000000026%. I dunno. In any case it is low on purpose so you can't get it.

**Comment by Prometheus0000** [comment]
Unless this one was needed for something and I'm mistaking it for another one?

**Comment by Prometheus0000** [comment]
Looks like it's just low, not absurdly low 
```
beeSpecies.addProduct(GT_Bees.combs.getStackForType(CombType.NEUTRONIUM), 0.0001f);
```

Try running it for a couple days or weeks.

**Comment by yukieiji** [comment]
I see in the Production Modifier section that there is 516%....(My calculations and yours don't seem to match this either...)
![2021-05-01_13 20 22](https://user-images.githubusercontent.com/40425798/116770837-59430680-aa81-11eb-807f-55e40e2d1036.png)
I think there is something wrong if 230 generations of crosses in this state produce none...

**Comment by leagris** [comment]
So, what is the point of such a ridiculously low production rate, except that it encourages spamming fast ticking upgrades, spamming industrial apiaries, spamming everything for minor improbable outcome.
I suggest it be removed entirely or tuned to a more realist practical chance. Or are players supposed to wait until our real life sun grows to a red giant and eat Earth to get one comb that will yield a tiny dust of. Well forget it. This nerf is totally inept.

**Comment by Prometheus0000** [comment]
Making it memey apparently. See #6422.

**Comment by botn365** [comment]
but isent neutronium comb not used in a few recipes for bees
if so the chance should be way higer

**Comment by Prometheus0000** [comment]
Making the advanced mutatron, of which you only need one ever, needs 4. Then there's some UUM and ore multiplying stuff that shouldn't even be there.

**Comment by yukieiji** [comment]
I've been breeding for a few days, and I've reached 1,000 generations, but it's not producing anything.
![2021-05-04_11 41 59](https://user-images.githubusercontent.com/40425798/116955691-36596200-acce-11eb-9bde-182d1f0fc155.png)


Isn't there something wrong after all?

**Comment by mitchej123** [comment]
Are you doing it in the preferred environment of Hellish Damp?

**Comment by yukieiji** [comment]
Neutronium Comb isn't a special product and should be able to be produced in any environment...
![2021-05-04_11 48 58](https://user-images.githubusercontent.com/40425798/116955931-dc0cd100-acce-11eb-96a8-81aeb5b0538a.png)

**Comment by Prometheus0000** [comment]
Ask on the discord server if anyone else's made some.

**Comment by yukieiji** [comment]
I asked before, but didn't get any reply, so I opened a ticket....
https://discord.com/channels/181078474394566657/234936569360809996/837542701866942494

**Comment by Glease** [comment]
The base chance is 0.01%. Fast genome multiply it by 1.2. Your housing further multiply it by 5.16. Overall the production chance is 0.06192%. Do mind you have a glaring **4% lifespan modifier** on your housing, which basically means it can work only once per generation before dying. The chance for you not geting the output even once out of your 1000 work cycle, is 0.9993808^1000, approximately 53.82%. I'd say you simply haven't waiting long enough.

**Comment by Prometheus0000** [comment]
Blinding speed is faster than fastest BTW.

**Comment by yukieiji** [comment]
I simply don't have a GenSample for Faster or Fastest.

**Comment by Prometheus0000** [comment]
I'm pretty sure neutronium bees were much harder to get than those traits. You know you can use NEI on the samples to find which bees have them, right?

**Comment by yukieiji** [comment]
Fast was enough for me because don't need that much speed when making neutronium bee.
Also, in making the neutronium bee, there is no need to make a Fastest or Faster bee.

**Comment by yukieiji** [comment]
It's good to test, but first of all, has anyone been able to produce Neutronium Comb in v2.1.0.0?

**Comment by yukieiji** [comment]
@Glease I tried Fastest, but the production modifier is not reaching 1600%....
![2021-05-05_13 01 36](https://user-images.githubusercontent.com/40425798/117096602-93bfe280-ada4-11eb-99e6-e8270fad9e4f.png)

**Comment by Glease** [comment]
I'd suggest try an alveary with 2 working frame (or whatever that was called. made from nether star and blue steel rods) from GT++.

**Comment by yukieiji** [comment]
Is this okay?
![2021-05-05_13 46 18](https://user-images.githubusercontent.com/40425798/117098020-48a7ce80-ada8-11eb-9c5d-211c91d36de4.png)
![2021-05-05_13 45 24](https://user-images.githubusercontent.com/40425798/117098008-3cbc0c80-ada8-11eb-96b9-586afce47b9f.png)

**Comment by yukieiji** [comment]
In the alveary, it was produced soon after one generation....
In Industrial Apiary, Production Modifier is 1/4, but why isn't it produced after 4 times more generations?

**Comment by Glease** [comment]
Pure luck.

**Comment by yukieiji** [comment]
I've been able to make a few per generation, but can I chalk this up to luck?
Isn't this evidence of some glitch in Industrial Apiary's production calculations?

**Comment by Glease** [comment]
Highly unlikely. They basically uses the same algorithm from forestry. I'm not sure if displayed production modifier is correct though.
