### ISSUE TITLE
TF Lootchest rebalance

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/GT-New-Horizons-Modpack#7890]
I start to add more usefull stuff into TF chests.
I need some ideas which items i have to pack in the chests.

- [ ] hill1 small 
- [ ] hill2 medium
- [ ] hill3 large
- [ ] hedge maze
- [ ] labyrinth_room
- [ ] labyrinth_dead end 
- [ ] tower_room Lich
- [ ] tower_library Lich
- [ ] basement Lich
- [ ] labyrinth_vault
- [ ] darktower_cache
- [ ] darktower_key
- [ ] darktower_boss
- [ ] tree_cache
- [ ] stronghold_cache
- [ ] stronghold_room
- [ ] stronghold_boss
- [ ] aurora_cache
- [ ] aurora_room
- [ ] aurora_boss
- [ ] troll_garden
- [ ] troll_vault

**Comment by Alastors** [comment]
Thaumium ingots? and maybe just in general more common base TC materials like nitor and alumentum?

**Comment by Prometheus0000** [comment]
I don't see the point in separating these out into different things, as the TF isn't really hard unless you do it super early. Just make it all the same but with higher percentages for later stuff (at least for the things not TF-specific already). Just make sure not to remove stuff like the mazebreaker that you can only get from them by accident.

Making them all different loot tables just creates work no-one wants to do.

**Comment by Dream-Master** [comment]
This issue need to be open.
