### ISSUE TITLE
[Suggestion]Add industrial scale lubricant production

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7891]
#### Which modpack version are you using?
2.1.0.0

#
#### What do you suggest instead/what changes do you propose?
Lubricants are required for drills, cutters, engines, components (Luv onwards), etc. and are needed in large amount, but as of v2.1.0.0 there is no way to produce them in large amount(mass production of them from fish oil or seed oil would require advancing IC2 agriculture and huge farmland).

So I propose the following production line on an industrial scale to process ethanol and make lubricant.(This is based on the production of "complex ester")
Phosphoric Acid 2000L + Ethanol 1000L -> Organophosphate 2000L
Sulfuric Acid 1000L + Ethanol 1000L -> Organosulfate 1000L
Carbon Monoxide 1000L + Hydrochloric Acid 2000L -> Phosgene 1000L + Hydrogen 1000L
Phosgene 1000L  + Ethanol 1000L -> Carbonate Ester 1000L
Organophosphate 2000L + Organosulfate 1000L + Carbonate Ester 1000L -> lubricant 4000L

#
#### What is your GTNH Discord username?
yukieiji

**Comment by Prometheus0000** [comment]
Wouldn't people just make a PA of the current recipe instead? This uses a bunch of stuff. In addition, I don't see how it's faster at all?

> (mass production of them from fish oil or seed oil would require advancing IC2 agriculture and huge farmland)

I fail to see why this is a problem. Or why it would be true, you have other ways to get those things.

Instead you should suggest a _new_ lubricant for LuV+/ZPM+ or something. Assuming that this is even needed. One that you need less of but need more complicated _new_ materials, not old stuff, _again_.

**Comment by boubou19** [comment]
what about the wood -> wood tar -> creosote -> lubricant chain? Isn't it enough?

**Comment by yukieiji** [comment]
>Wouldn't people just make a PA of the current recipe instead? This uses a bunch of stuff. In addition, I don't see how it's faster at all?

Cutter's recipe is almost twice as fast with or without Lubricant...

> what about the wood -> wood tar -> creosote -> lubricant chain? Isn't it enough?
When you consume a lot of Lubricant(e.g. making a lot of electronic circuit parts with a cutter), I think that chain will be slow to produce. Currently, there is a serious lack of Lubricants in my base....

**Comment by Prometheus0000** [comment]
> Cutter's recipe is almost twice as fast with or without Lubricant...

Make a PA to _make lubricant_.

> Currently, there is a serious lack of Lubricants in my base....

Make more of the above. And maybe some DTs.

**Comment by Glease** [comment]
isn't there a recipe that use raw oil and something like soapstone. That ought to be fast enough.

**Comment by yukieiji** [comment]
> Make a PA to make lubricant.
What is PA?

> isn't there a recipe that use raw oil and something like soapstone. That ought to be fast enough.
Sure, it's fast, but isn't it wasteful to make a large amount of useful Oil directly into Lubricant?

**Comment by Prometheus0000** [comment]
How can you be far enough to need huge amounts of lubricant, but still not know what processing arrays are?

**Comment by yukieiji** [comment]
I don't often abbreviate processing array....(I've never seen a Japanese GT Player abbreviate it)

**Comment by Prometheus0000** [comment]
Every english player does it every time.

**Comment by Glease** [comment]
Cultural barrier then.

Anyway, did you tried the recipe I mentioned? 1 Redstone + 750L raw oil => 750L lubricant in brewing machine, 4EU/t @ 128 ticks. Both of these ingredients are available in great abundance. This should be more than enough to cover any lubricant need.

**Comment by yukieiji** [comment]
>Anyway, did you tried the recipe I mentioned? 1 Redstone + 750L raw oil => 750L lubricant in brewing machine, 4EU/t @ 128 ticks. Both of these ingredients are available in great abundance. This should be more than enough to cover any lubricant need.

Do you think it would be a waste to prepare a large amount of raw oil for Lubricant?

If we want Advanced Lubricant, shouldn't what we can make with this line be Advanced Lubricant?
Complex Ester is an excellent lubricant(Synthetic Base Oil) that is also used in real world.

**Comment by leagris** [comment]
So, instead of adding more lubricant bloat, which does not improve gameplay. Make recipes use less lubricant.

#### No lubricant precision sawing
Precision Sawing of silicon wafers don't use any lubricant, but an electro deposited abrasive on the surface of a diamond saw blade, operating in an electric field. The electric field acts as a lubricant, pushing particles away. This method is the actual current one used, it produces optically perfect polished silicon wafers.

#### Silicone based lubricant grinding
Only the older primitive methods of grinding silicon wafers out of silicon ingots needed a lubricant. Usually a formulation of polysiloxane like dimethyl-siloxane which prevent unwanted foaming and some phosphorus compound for low temperature thermal stability and viscosity. This method is obsolete and used in older or lower tech chip fabs. It also output less wafers per silicon ingot, and require further polishing of the wafers.

Maybe we could have both methods reflected in game, like using the regular cutting machine with lubricant to cut ordinary wafers only.

Have advanced or high tier cutting machines cut all silicone wafers without lubricant, yield more wafers per silicone boulle. (Let the lubricant-free recipe be higher tier EU/t requirement but yield more.

**Comment by Prometheus0000** [comment]
Or just make the upcoming cutting machine multi not use lubricant?

**Comment by Glease** [comment]
> Do you think it would be a waste to prepare a large amount of raw oil for Lubricant?

No, it's certainly not a waste. Oil is not at all precious. What is really precious is oil product. The only way to fully utilize the output of one T3 oil rig is to use an overclocked mega distillation tower.

**Comment by yukieiji** [comment]
>Or just make the upcoming cutting machine multi not use lubricant?

We must craft a single Cutting machine for that tier, so please don't do that.

**Comment by Prometheus0000** [comment]
I'm not talking about the GT++ one. And I still don't see why it's necessary at all, just throwing it out there.

**Comment by yukieiji** [comment]
The IC required for that tier's energy hatch will require that tier's cutting machine, which will necessarily require a single one.

**Comment by iouter** [comment]
more recipes are always good.

**Comment by Dream-Master** [comment]
Adding a new recipe change that make at some tier sense isnt a bad idea. But it must be well balanced and make gameplay better.
