### ISSUE TITLE
Present Chest can't move with Dolly

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/GT-New-Horizons-Modpack#7896]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Ist es möglich die Present Chest von Chisel mit der Dolly zu bewegen?
It is possible to move Present Chest from Chisel with the Dolly
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
DragScorpion

**Comment by Dream-Master** [comment]
We have jabba code so i remember we add other chest to the code already.

**Comment by boubou19** [comment]
https://github.com/GTNewHorizons/Jabba/commit/12075adda0a9ed42510788db199f9259ec4ca660

**Comment by Dream-Master** [comment]
it work but it open the chest so it is bugged

**Comment by Dream-Master** [comment]
need a more advanced coder to help me. @jss2a98aj say he want to help me

**Comment by Ethryan** [comment]
Can we change the bot to not close issues in the [Icebox](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/milestone/87)?
