### ISSUE TITLE
Marble Slabs recipe change

### ISSUE THREAD

**Issue by DragScorpion** [GTNewHorizons/GT-New-Horizons-Modpack#7897]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Marble Slabs Vanilla recipe?
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Pls into Cutter
#
#### What is your GTNH Discord username?
DragScorpion

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/116809590-09c31000-ab3f-11eb-9d74-4c138a87836c.png)
