### ISSUE TITLE
Add specific teleport 

### ISSUE THREAD

**Issue by TA0MACHINE** [GTNewHorizons/GT-New-Horizons-Modpack#7898]
#### Which modpack version are you using?
Version 2.1.0.0 23.12.2020
ETA
#### What do you suggest instead/what changes do you propose?
Add teleport for Greg tech quarry.
The issue is, you can’t teleport quarry correctly, there are several ways to do this, but none of these paths are stable (screenshot).
![Uploading 786B5395-8566-4C51-B2D9-26436A0A7010.png…]()
When you always put/removing quarry it’s annoying. Make some teleport only for quarry and fluid drilling platform?

**Comment by GTNH-Afx237v7** [comment]
Moving TileEntities via frames/transposers may work (results may vary).

**Comment by Prometheus0000** [comment]
Absolutely not. Do not suggest things that cause world corruption, especially on servers.

**Comment by 0lafe** [comment]
both those options are pretty solid, and work well on servers without corruption. There's some guidelines for sure, but usually people won't be using the no no blocks in multi miner setups. Could be nice to make a quest or something to help people avoid some of the bad combinations (frames with TVIs/RIO, or BM with SFM)

**Comment by TA0MACHINE** [comment]
I had use teleposer for this purpose, but suddenly appeares this
![2021-04-19_202323](https://user-images.githubusercontent.com/42874669/116824143-4881b600-ab91-11eb-92f9-38bff88931d6.png)

**Comment by Prometheus0000** [comment]
How did you use it, they should be blacklisted?

**Comment by 0lafe** [comment]
who would do that and why? GT multis work pretty well with the teleposers

was that sign put there by an admin or something? nothing in that setup seems to be an issue for the teleposers

**Comment by TA0MACHINE** [comment]
> Absolutely not. Do not suggest things that cause world corruption, especially on servers.

I perfectly understand your position, but again and again put this setup annoying. And use ender quarry from extra utilities not so profitable.

**Comment by TA0MACHINE** [comment]
> who would do that and why? GT multis work pretty well with the teleposers
> 
> was that sign put there by an admin or something? nothing in that setup seems to be an issue for the teleposers

some of admins. I had use this by teleposing and all was fine, but if this sign here, so there is problems
