### ISSUE TITLE
Add Just Enough Calculation Mod.

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#7899]
#### What do you suggest to being added?
I suggest to add the Just Enough Calculation Mod.
#
#### Why?
This Mod only adds one Item (A Calculator). This allows for easy calculation for certain recipes (Crafting Recipes and also processing recipes). It is similar to the ae2 crafting preview when autocrafting, just without crafting, only the calculations. It also supports fluids. This will make planning batch-crafts before ae2 easier. The Mod is very lag-friendly.
#
#### Screenshots:
GUI when opening:
![2021-05-03_12 02 37](https://user-images.githubusercontent.com/81151019/116865476-034d9a80-ac0a-11eb-8494-4ef4d4ec611b.png)

Adding a Recipe for e.g. a advanced Circuit. Bottom is Input, Top is output. Crafting table Recipes can be shift clicked from NEI, Processing Recipes can be created by dragging ghost items from NEI. 
![2021-05-03_12 04 39](https://user-images.githubusercontent.com/81151019/116865478-047ec780-ac0a-11eb-8e82-71aa779d5238.png)

Dragging a advanced Circuit into the top left Slot shows the Items/Fluids needed to create that Item. When these items are in Inventory, the icon turns Green.
![2021-05-03_12 04 47](https://user-images.githubusercontent.com/81151019/116865482-05175e00-ac0a-11eb-9bb8-5672d1dd6fae.png)

Adding recipes to e.g. Annealed Copper Bolts and MV-Circuits wont show these Items in the GUI, but rather the needed Ingredients to craft these Items:
![2021-05-03_12 06 32](https://user-images.githubusercontent.com/81151019/116865485-05aff480-ac0a-11eb-95d2-90dac6a35b61.png)

Crafting Recipe Suggestion:
![2021-05-03_12 08 22](https://user-images.githubusercontent.com/81151019/116865488-06488b00-ac0a-11eb-800d-79a1d4091b82.png)

#
#### Server or Client?
As it adds an Item, needs to be on both
#
#### Dependencies?
None
Works Flawlessly with Mitchej's NEI Fork, tested on Single and Multiplayer.
#
#### What is your GTNH Discord username?
TrainerSnow#5086

**Comment by Prometheus0000** [comment]
How does it handle things like alternate recipes though? Like 2 iron+hammer=plate vs 1 iron+bending machine=1 plate

**Comment by Methes** [comment]
Judging by the screenshots it looks like you manually insert and save the recipes so you basically create your own recipe map it calculates with. Looks neat.

**Comment by mitchej123** [comment]
Duplicate 
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3186
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/1185

**Comment by repo-alt** [comment]
It is a duplicate indeed but neither of the previous bugs has a clear explanation why is this a bad idea. (Not that I actually support it, just saying)

**Comment by TrainerSnow** [comment]
> 
> 
> How does it handle things like alternate recipes though? Like 2 iron+hammer=plate vs 1 iron+bending machine=1 plate
As methes said, you add the recipe yourself, nothing really gets auto generated.
