### ISSUE TITLE
[Adventure Backpack] Graphical Glitch with Status Effect Display affected by Vis stone [Thaumcraft]

### ISSUE THREAD

**Issue by tyrael93** [GTNewHorizons/GT-New-Horizons-Modpack#7903]
Using version-h15 of Adventure backpack, when a Vis Stone (TC) is in your inventory it will render a black layout on all the status effects. This does not happen when wielding a wand. 
Here are two pics as proof, the bug can be reproduced simply by having the status effects enabled and having a vis stone in your inventory.
>with a vis stone
![2021-05-04_00 10 20](https://user-images.githubusercontent.com/5557920/116940679-94565d00-ac6e-11eb-96c1-04f3b5620c8c.png)
>without a vis stone, with a wand 
![2021-05-04_00 11 32](https://user-images.githubusercontent.com/5557920/116940745-a59f6980-ac6e-11eb-9115-613994e435ea.png)

Thank you in advance for any help on the subject.

**Comment by YannickMG** [comment]
Looks like this bug is triggered by having either https://github.com/KryptonCaptain/ThaumicUtilities or https://www.curseforge.com/minecraft/mc-mods/thaumic-utilities installed. (I could only get the first more up to date one to work)

**Comment by bombcar** [comment]
That mod is MIT perhaps we should also consider bringing it in

**Comment by YannickMG** [comment]
It does look neat.
