### ISSUE TITLE
Gating indium behind T3 fusion is unreasonable

### ISSUE THREAD

**Issue by Mxrynd** [GTNewHorizons/GT-New-Horizons-Modpack#7904]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Overall I can see the following modpack philosophy: 
1. when you first face new material it is ass pain to get a reasonable amount of it
2. in a tier or two higher you find a better way of getting it (ore with 1st byproduct/pure ore/new process) and you can farm a reasonable amount of resource in reasonable amount of time. Simultaneously your demand of this resource grows.
3. (optionally)the demand becomes absurdly high and at the same time you find even better source of it (like pure ore or ore with high spawn rate)
To sum up: resource availabilite scales side by side with usage.

For example: everyone need to build a platline to progress further in IV. By processing platinum one gets fair amout of iridium and a little of osmium. After grinding tons of this for fusion mk1 you open the paradise: 
1. you can process iridium ore to get tons of it in few easy platline steps
2. the rarest and grindest one to get osmium not can be crafted in fusion reactor with reasonable speed.

On the other hand: indium. One starts to need it in IV with 2 alternative ways of getting: tine dusts (ewww) in chem reactor and a (rare and sporadic) ore on ross. During IV-ZMP progressing the demand of indium grows and grows (a lot for asslines in IV, ton for fusion mk1 in LUV and SHIT TON for fusion mk2 in ZPM). For example I've spent ~ 8 hours of flying arund ross and moving miner to get indium for t1 fusion. t2 reactor requires ~10x more indium and that leads us to absolutly unreasonable time on ross farming indium.
Than you enter UV and (surprise) amount of indium needed becomes about the same as in IV, because new wafers do not need indium. As a result you can now make indium in t3 fusion but you do not need it.
To sum up: huge boost of indium demand during IV-late ZPM progression, no new ways to get it in this tears, that do not line up with availability politics for other resouces.
Indium fusion recipe fits in fusion mk1 voltage, but reaction can  not be started because of start power required.

#
#### What happened instead? (Attach screenshots if needed)
#
#### What do you suggest instead/what changes do you propose?
Make indium fusion recipe starting energy requirement to fit t1 fusion.
#
#### What is your GTNH Discord username?
Shyrff

**Comment by joshaup1999** [comment]
Indium honestly isn’t that bad to get with the chem reactor way, just move your miners every now and then on Mars. Easier than trying to find it on Ross

**Comment by botn365** [comment]
bringing it down to T2 is somthing im oke with but T1 defnetly not

**Comment by Mxrynd** [comment]
@botn365 the problem is that you do not need it after you build t2 (t3 reactor do not need indium to build AT ALL). Moving it to T1 is new source after full IV and LUV tier. Moving to T2 does not change situation at all and leaves player without new source of rare material for 3 tiers which not lines up with other rare materials.

**Comment by Mxrynd** [comment]
In my opinion it should be T1 but probably with harder reciepe (not lithium + silver but smth more high tier maybe?)

**Comment by GTNH-Afx237v7** [comment]
I’m also thinking that T1 is too early. Your first T1 reactor is a grind, sure. The upgrade to T2 requires a decent amount for the 48 wafers, however it’s possible without needing to fuse indium with the T1. (Personally I did my first two stacks of indium with Roquesite from Ross, and then solely from UUM (without crops)).

**Comment by 0lafe** [comment]
Doesn't T2 technically give more indium in the form of the VM? I know our only issue with the ore proc method was the limited amount of ores we had to process.

**Comment by Mxrynd** [comment]
I have not checked yet if VM works correctly in bart's dimensions (I do not understand why it does not work in nether and TF for example btw).

**Comment by 0lafe** [comment]
i would hope it's unable to get the ross In ore at least in good quantities, i meant it would help in obtaining galena and sphalerite

**Comment by Mxrynd** [comment]
And one more clarification why I think that T1 is not too early: osmium and indium are both rare IV materials with about the same difficulty of obtaining. Osmium has it's effective way of obtaining in T1, indium -- on T3 (when it's not even needed a lot). 
I just want to point out inconsistancy in this IV-ZPM high demand resources availability logic.
If most of contibutors community  think  that my suggestion is too OP, feel free to close discussion

**Comment by johnch18** [comment]
Does anyone actually use fusion for indium? I feel like that recipe would be far slower than the ore processing method.

**Comment by Sphyix** [comment]
> Does anyone actually use fusion for indium? I feel like that recipe would be far slower than the ore processing method.

yes, indium is mostly made with uu or fusions, making it t2 or even t1 would remove the need to use uu for it
ores are not a good alternative, really too slow and you don't get enough of it

**Comment by GTNH-Afx237v7** [comment]
As I stated earlier I used to use UUM for indium but have meanwhile switched to galena/sphalerite as this is simply much faster, given you have the aluminum and plenty of sulfuric acid. 
T1 is too early, T2 I’d say is OK. Whether or not T3 is too much I can’t really say as I have not made a T3 reactor yet.

**Comment by Sphyix** [comment]
This is still an issue that should be fixed

**Comment by bombcar** [comment]
Maybe something could be done with this along with balancing the over-use of UUM.

**Comment by draknyte1** [comment]
There is a way to get indium albeit in small amounts from milling.
