### ISSUE TITLE
Applied Energistics cell oredict filter Crash [AE2 Beta-46] [Creative Mode]

### ISSUE THREAD

**Issue by tyrael93** [GTNewHorizons/GT-New-Horizons-Modpack#7905]
#### What did you try to do, and what did you expect to happen?

When searching in the creative search tab the following crash ensued.
![12](https://user-images.githubusercontent.com/5557920/116979337-2721e680-acc5-11eb-95fb-fdf00c6e85ed.png)

https://pastebin.com/B2WJQfHY

**Comment by repo-alt** [comment]
What is ExtraCells version?

**Comment by tyrael93** [comment]
The latest NH version, ExtraCells-1.7.10-2.4.7b13.jar.

**Comment by repo-alt** [comment]
Well, I can't reproduce it in NEI, but I know the condition when it will crash in the same manner, so I need to update/rebuild Extra Cells anyway

**Comment by tyrael93** [comment]
Quick update: I have now definitive proof that it happened again when searching with a barebone instance with only extra cells b13 and AE2 beta-46 when searching in the creative mode bar.

**Comment by repo-alt** [comment]
(It will be closed when the update will come out)
