### ISSUE TITLE
Getting kicked out of singleplayer world while being in Twilight Forest

### ISSUE THREAD

**Issue by ForsakenKappa** [GTNewHorizons/GT-New-Horizons-Modpack#7906]
#### Which modpack version are you using?
Latest one as of 04.05.2021 (2.1.0.0 (?))
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
I entered the TF and looked around; excpected continue exploring dimension
#
#### What happened instead? (Attach screenshots if needed)
Got kicked out of my SSP
#
#### What do you suggest instead/what changes do you propose?
IDK
#
#### What is your GTNH Discord username?
SadCookie

![2021-05-04_21 10 34](https://user-images.githubusercontent.com/75193955/116991829-de981680-ad20-11eb-9aa7-b9fde6961ee3.png)

[2021-05-04-2.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6420460/2021-05-04-2.log)

**Comment by boubou19** [comment]
remove fancy block particles, it's erroring when you enter the dim it seems

**Comment by ForsakenKappa** [comment]
OH wow, it's been that mod. How did you figured that out?

**Comment by boubou19** [comment]
the stacktrace in the logs is mentionning it at the direct crash cause.
