### ISSUE TITLE
Output Hatches and Machine extract rate visible somewhere?

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#7907]
#### Which modpack version are you using?
GTNH
#
#### If in multiplayer; On which server does this happen? 
Jimmy's Community Server
#
#### What did you try to do, and what did you expect to happen?
I was trying to set up an LHE + some steam turbines
#
#### What happened instead? (Attach screenshots if needed)
I had issues figuring out why my turbines didn't get to max efficiency when I was testing this in a creative world.
Turns out it was related to the output hatch default extract rate. Putting Pumps would've solved the issue but is quite expensive as IV pumps would've been required for the optimal flow. However EV output hatches were cheaper and worked fine.
#
#### What do you suggest instead/what changes do you propose?
I suggest to add tooltip information on hatches/buses for their default extract behavior as well as perhaps machines. Or at least for this to be more easily accessible information perhaps in the quest book. I've had issues before with machines auto-output being too slow for certain automations.

I also think the LHE page on the wiki and the explanations on the steam turbines in the quest book weren't enough for me to be able to know how the thing works at all before doing a bunch of testing and asking around. The spreadsheet is fantastic but doesn't contain enough information to properly setup a LHE/Turbine combo, it helps you figure out the numbers but the actual mechanics are not explained anywhere. There is also misleading information in the questbook about the turbines exploding and whatnot which I believe has been patched out.

Overall LHE/Turbine documentation needs improving IMO and would love to help out as I've personally done a lot of testing to exactly figure out how every mechanic works. Would also really love tooltip for default extract behavior on hatches/buses, would be really helpful.

Sorry for wall of text.
#
#### What is your GTNH Discord username?
Hucking#0193

**Comment by Prometheus0000** [comment]
Didn't repo just add scanner capability? https://github.com/GTNewHorizons/GT5-Unofficial/pull/520

**Comment by hucking** [comment]
correct me if i'm wrong but that does not include auto-extract rate right?

**Comment by repo-alt** [comment]
I just added information about the hatch capacity and what it is locked to (and only that last line is not obvious from the GUI). What is requested here is less obvious information, and I'm not sure if it can be obtained in a generic fashion.

**Comment by hucking** [comment]
At the very least can be put into a spreadsheet or added into the LHE quest info. This was a big problem for me when making the LHE

**Comment by Prometheus0000** [comment]
I didn't even realize hatches had a limited output rate. Also, isn't it output rate rather than extraction rate? I think adding the info to their TT would be best. Assuming there's a way to even find it?

Or are you talking about the reactor fluid port, and not the GT blocks?

If you want to add info to the wiki, there's no limitation or anything, just need to sign up. I setup an LHE for testing once, but I never really _used_ them.

Also, turbines do explode if you generate too many amps, but can't output it. You should always check out the latest version of the QB before complaining about the text if it's about another part.

**Comment by hucking** [comment]
I see, I think there is a difference between output rate and extraction rate, the recipe will give u a certain yield based on the tier of the output hatch (if for example the recipe makes a larger yield than the hatch can contain u will void the excess) but you can still pump it out manually with the help of external items/blocks like GT pumps, conduits etc. The hatches however auto-extract by default into pipes connected to their output side. I believe the proper term is therefore extract rate and not output rate.

Also in regards to the explanation about the turbine exploding in the quest book I must've misunderstood the text, disregard that, sorry.

**Comment by Prometheus0000** [comment]
The hatches output from themselves, they can't extract from themselves, that's incorrect english. Conversely the pumps extract from the output hatch, but you could also say they import to the pipe. But you can't say the pump outputs to the pipe.

Now if you're saying that the output bus is extracting fluid from the multi that might work, but that would be talking about filling _them_ up, and not about moving it out of the multiblock.

**Comment by hucking** [comment]
Fair enough regardless of the English I think the output rate would be a great addition to the TT

**Comment by repo-alt** [comment]
iirc hatch tries to output whatever it holds when something is put into it at the end of the tick. If it cannot - adjacent tank is not big enough, then it will try outputting every 8 tick

**Comment by Prometheus0000** [comment]
So there's no output limit after all? Assuming the tank it's trying to output to is >= the output hatch?

**Comment by repo-alt** [comment]
If the hatch itself is big enough to receive recipe output, yes.

**Comment by Prometheus0000** [comment]
Then maybe hucking's pipe wasn't big enough or something?

What about if it _can_ output. Does it still wait 8 ticks to output again if it gets more fluid the next tick? Because otherwise this sounds like user error.

**Comment by repo-alt** [comment]
If the recipe takes one tick I think it will try to output again. I didn't check the code it is just from memory

**Comment by hucking** [comment]
I will try to reproduce in a bit, I was using the same pipes/recipes and there was a different in output rate between HV and EV output hatches

**Comment by hucking** [comment]
I think this was just user error sorry guys. I just tested and noticed no difference between the two hatches not sure how this happened before o.O
