### ISSUE TITLE
Bacterial Vat Questline and Sieverts lacking clarity and a Red String

### ISSUE THREAD

**Issue by Aggadahr** [GTNewHorizons/GT-New-Horizons-Modpack#7910]
#### Which modpack version are you using?
2.1.0
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Im currently in UV and working towards the Wetware Circuit Line, which needs Growth Medium. This is the first utilization of Bacterial Vats, the first Quest for that is in Zpm: "This is not how you make Cheese"
Now, I had some questions, turned out there is more information and also a Quest for the Bacterial Vat in Multiblock Goals, but gated behind a Quest in HV, "Bio Lab"

The thing is, I reached UV Tier without ever doing that quest. How am i supposed to know that i need to complete it for a followup quest 5 Tiers later? Also, the whole inforamtion regarding Bacterial Vats is spread across multiple Tiers and 3 Quest Tabs
#
#### What do you suggest instead/what changes do you propose?
Please chain these Quests properly together, maybe link them all in the zpm quest tab and gate the Growth Medium Quest behind it.
#
#### What is your GTNH Discord username?
Shadii

**Comment by Prometheus0000** [comment]
You can use it in HV, and you missed the mutagen quest in LuV too.

**Comment by Aggadahr** [comment]
My point is, the Bacterial Vat is 100% optional until you reach UV Tier, where its the only machine that can produce Growth Medium for the Wetware Circuit Line.
A lot of desperately needed Information is located in Multiblock Goals, which is gated behind a small Quest in HV, which isnt even needed to progress through the Tiers. 
Also, the Mutagen Quest in LuV is optional as well

**Comment by Prometheus0000** [comment]
I'm just saying I'm not moving them to UV.

**Comment by Aggadahr** [comment]
Since the same Quest can appear in multiple Tabs, maybe link the quests with all that very useful information in the ZPM tab, where the starting point for Wetware Circuits is? Because everything before that is optional and fairly easy to miss
