### ISSUE TITLE
Fix 2nd EBF Quest in MV

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#7913]
#### Which modpack version are you using?
2.1.0.5 (Dev)

After you get your first 64 Stainless Steel Ingots in the MV Questline, there is a Quest "Stainless taking too long?". The quests explains, that one should build a second EBF, for faster Stainless. The Quest only asks for
-One EBF Controller
-One MV Muffler Hatch
-2 Energy Hatches
It is thought that one builds a new EBF to complete the quest, but it is possible to just dismatle your only EBF, let the Quest recognize and assemble it again, prior to building a 2nd EBF.
#
#### What do you suggest instead/what changes do you propose?
Change the amount of EBF-Controllers asked for to 2, or make it a crafting task. Also ask for a second set of Coils.
#
#### What is your GTNH Discord username?
TrainerSnow
#5086

**Comment by MLellmann** [comment]
There are a few problems with your suggestions to solve this:

1) Making it a crafting task: With some update some time ago the Questbook will detect quests even if they are currently not active, especially crafting tasks, so crafting it once would complete both quests.

2) A second set of coils is questionable as you do not need a full set if you share a side.

Tbh, in my opinion leaving this quest like this (and other affected ones like the one for 2x and 4x BBF) and not changing them is fine - it should be seen as a hint to the new player as what to do, and not be a strict requirement. I mean, if they do not build a second they might have the quest rewards, but are punished by only having one EBF for processing.

**Comment by Prometheus0000** [comment]
I agree with MLellmann, I could make it require this or that, but in the end you could just disassemble your current one. And _making_ you do so so it can count all the blocks so you have it legit is not cool. And I don't want to start adding crafting tasks outside of pre-LV. If they don't want to make a second one that's fine, I didn't.

> Making it a crafting task: With some update some time ago the Questbook will detect quests even if they are currently not active, especially crafting tasks, so crafting it once would complete both quests.

This is actually a specific flag set per quest that defaults off. This is because it has CPU overhead.
