### ISSUE TITLE
It got stuck at 27%

### ISSUE THREAD

**Issue by keremlov** [GTNewHorizons/GT-New-Horizons-Modpack#7914]
#### Which modpack version are you using?
2.1.0.0QF1
#
#### What did you try to do, and what did you expect to happen?
I tried to open the game but it got stuck at 27%

**Comment by Glease** [comment]
Has a bit more patience. Check the logs to see if it is still working. If not please upload the log so we can have a look into it.

**Comment by keremlov** [comment]
I have waited like 10 minutes , it just pre initilazition : loading lootgames. I even downloaded an earlier version and that didn't work

**Comment by Glease** [comment]
Try set `disableDonorListDownloading` to `true` in `config/LootGames/lootgames.cfg`

**Comment by keremlov** [comment]
There is no such thing in the file

> Try set `disableDonorListDownloading` to `true` in `config/LootGames/lootgames.cfg`

**Comment by keremlov** [comment]
This is the file 

# Configuration file

debug {
    # Enable debug output to fml-client-latest.log [default: false]
    B:DoDebugMessages=false

    # LogLevel for the separate DungeonGenerator Logger. Valid options: info, debug, trace [default: INFO]
    S:DungeonLoggerLogLevel=INFO
}


games {
    # Enable or disable struct exploding on max failed attempts [default: true]
    B:ExplodeEvent=true

    # Enable or disable struct filling with lava on max failed attempts [default: true]
    B:LavaEvent=true

    # Enable or disable struct filling with monsters on max failed attempts [default: true]
    B:MobEvent=true

    gol {
        # Enable or disable Debugging of this game (Only enable this if you expect a bug. This will blow up your logfile...) [default: false]
        B:Debug=false

        # At which stage should the playfield become a full 3x3 pattern? Set 0 to disable and keep the 4-block size; set 1 to always start with 3x3 [range: 0 ~ 4, default: 2]
        I:ExpandPlayFieldAtStage=2
        I:MaxDigits=30

        # How many attempts does a player have? 1 means the struct will fail after the first misclicked block [range: 1 ~ 256, default: 3]
        I:MaxGameTries=2

        # How many digits should be randomly choosen at game-start? [range: 1 ~ 256, default: 2]
        I:StartDigits=2

        # How long does it take to timeout a game? Value is in seconds. If no player input is done in that time, the game will go to sleep. The next player will start fresh [range: 5 ~ 600, default: 60]
        I:Timeout=15

        gamestages {

            stagei {
                # Syntax: <DimensionID>;<LootTableName>;<AdditionalDigitsRequired>; one line for each Dimension. If you use AdditionalDigitsRequired, make sure to use the same or an higher number on each stage [default: []]
                S:DimensionalConfig <
                    
                 >

                # The amount of time (in milliseconds; 1000ms = 1s) to wait at playback before moving to the next color [range: 100 ~ 2000, default: 1200]
                I:DisplayTime=1200

                # The loottable for the chest in this stage [default: dungeonChest]
                S:LootTable=chest1

                # Maximum amount of items to be spawned [range: 1 ~ 256, default: 2]
                I:MaxItems=8

                # Minimum correct digits required to complete this stage and unlock the chest. This can be adjusted per-Dimension in S:DimensionalConfig [range: 1 ~ 256, default: 5]
                I:MinDigitsRequired=5

                # Minimum amount of items to be spawned [range: 1 ~ 256, default: 2]
                I:MinItems=4

                # If true, the pattern will randomize on each level in this stage [default: false]
                B:RandomizeSequence=false
            }

            stageii {
                # Syntax: <DimensionID>;<LootTableName>;<AdditionalDigitsRequired>; one line for each Dimension. If you use AdditionalDigitsRequired, make sure to use the same or an higher number on each stage [default: []]
                S:DimensionalConfig <
                    
                 >

                # The amount of time (in milliseconds; 1000ms = 1s) to wait at playback before moving to the next color [range: 100 ~ 2000, default: 800]
                I:DisplayTime=800

                # The loottable for the chest in this stage [default: mineshaftCorridor]
                S:LootTable=chest2

                # Maximum amount of items to be spawned [range: 1 ~ 256, default: 4]
                I:MaxItems=10

                # Minimum correct digits required to complete this stage and unlock the chest. This can be adjusted per-Dimension in S:DimensionalConfig [range: 1 ~ 256, default: 10]
                I:MinDigitsRequired=10

                # Minimum amount of items to be spawned [range: 1 ~ 256, default: 4]
                I:MinItems=5

                # If true, the pattern will randomize on each level in this stage [default: false]
                B:RandomizeSequence=false
            }

            stageiii {
                # Syntax: <DimensionID>;<LootTableName>;<AdditionalDigitsRequired>; one line for each Dimension. If you use AdditionalDigitsRequired, make sure to use the same or an higher number on each stage [default: []]
                S:DimensionalConfig <
                    
                 >

                # The amount of time (in milliseconds; 1000ms = 1s) to wait at playback before moving to the next color [range: 100 ~ 2000, default: 600]
                I:DisplayTime=600

                # The loottable for the chest in this stage [default: pyramidJungleChest]
                S:LootTable=chest3

                # Maximum amount of items to be spawned [range: 1 ~ 256, default: 6]
                I:MaxItems=11

                # Minimum correct digits required to complete this stage and unlock the chest. This can be adjusted per-Dimension in S:DimensionalConfig [range: 1 ~ 256, default: 15]
                I:MinDigitsRequired=15

                # Minimum amount of items to be spawned [range: 1 ~ 256, default: 6]
                I:MinItems=6

                # If true, the pattern will randomize on each level in this stage [default: false]
                B:RandomizeSequence=false
            }

            stageiv {
                # Syntax: <DimensionID>;<LootTableName>;<AdditionalDigitsRequired>; one line for each Dimension. If you use AdditionalDigitsRequired, make sure to use the same or an higher number on each stage [default: []]
                S:DimensionalConfig <
                    
                 >

                # The amount of time (in milliseconds; 1000ms = 1s) to wait at playback before moving to the next color [range: 100 ~ 2000, default: 500]
                I:DisplayTime=500

                # The loottable for the chest in this stage [default: strongholdCorridor]
                S:LootTable=chest4

                # Maximum amount of items to be spawned [range: 1 ~ 256, default: 8]
                I:MaxItems=12

                # Minimum correct digits required to complete this stage and unlock the chest. This can be adjusted per-Dimension in S:DimensionalConfig [range: 1 ~ 256, default: 20]
                I:MinDigitsRequired=25

                # Minimum amount of items to be spawned [range: 1 ~ 256, default: 8]
                I:MinItems=7

                # If true, the pattern will randomize on each level in this stage [default: true]
                B:RandomizeSequence=true
            }

        }

    }

}


main {
    # Switch to enable or disable the Master-Blocks. If disabled, no minigames will spawn. You can change this ingame [default: false]
    B:MinigamesEnabled=true
}


worldgen {
    # List DimensionIDs where LootGame Dungeons are allowed to spawn, with Rhombus Size. Syntax is <DimensionID>:<Rhombus Size> [default: [0; 20]]
    S:DimensionWhitelist <
        0;12
     >

    # Enable or disable RetroGen [default: false]
    B:RetroGenDungeons=false

    # Enable or disable WorldGen [default: false]
    B:WorldGenEnabled=true
    I:WorldGenRhombusSize=12
}

**Comment by Glease** [comment]
Try replace the lootgames with this version: http://downloads.gtnewhorizons.com/Dev-Pack/Files/mods/LootGames-1.7.10-1.0.20.jar

You will need to move the old jar away and set the config I mentioned above.

**Comment by keremlov** [comment]
Okay I got it. I didn't download it on Technic Launcher , I was using Curse Launcher now it's working just fine. Thank you for the help!
