### ISSUE TITLE
Potential alteration of materials list to remove some ore from VM pickup

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7916]
#### Which modpack version are you using?
21.0.6b
#

Ores collected by the VM that seem totally useless and are not spawned elsewhere and should have the material deleted:

Atlarus Ore, Promethium Ore, Praseodymium Ore, Rubidium Ore, Scandium Ore, Forcicium Ore, Forcillium Ore, Force Ore, Dilithium Ore, Infuscolium Ore, Emery Ore, Celenegil Ore, Pumice Ore, Inolashite Ore, Sanguinite Ore, Hepatizon Ore, Angmallen Ore, Eximite Ore, Prometheum Ore, Carmot Ore, Haderoth Ore, Meutoite Ore, Thulium Ore, Erbium Ore, Holmium Ore, Dysprosium Ore, Terbium Ore
#
Potentially useful, but we already have saltpeter so should be deleted too:

Niter Ore (the VM is the only way to get it)
#
Has two version picked up by the VM, but gets unified after picking up, so should be unifed beforehand:
GT Cheese ore 894, BW cheese ore 32660
PS: the unification breaks the GC cheese ore needed for the no-rocket run. Also, why would it unify to the BW one? That seems weird.
#
Should not be an ore, and does not spawn anywhere else, so should have the ore disabled:
Americium, Europium, Flerovium (is this even used? can we delete this?), Cosmic Neutronium, Lutetium, Ichorium, Shadow, Manyullyn, Electrum, Fluxed Electrum, Pig iron (wrought iron), Indium, 
#
Maybe or maybe not disable the ore, but it doesn't spawn anywhere else:
Trinium, Phosphate, Tantalum, Mysterious Crystal, Tellurium Ore
#
Only used by GT++? ores:
Gadolinium Ore, Strontium Ore, Ytterbium Ore
#

Useless ores that actually spawn can be discussed for removal later, since it would alter worldgen, and I think doing it all at once rather than in bits and pieces is a better idea.
**Make sure to mention if there's a use I missed, since deleting the material is a very good way to mess things up if it's actually used.**

Should be done after next release anyway, to prevent bugs.

Related: #6136, #6560, #6995, #7356

**Comment by johnch18** [comment]
Vulcanite is useless as well IIRC

**Comment by Prometheus0000** [comment]
This is just for stuff picked up by the VM. And not anything that spawns on a planet, so worldgen doesn't break. All the other useless stuff is another huge list.

**Comment by sintken** [comment]
Other useless ores picked up by VM with non-planetary spawns are Oureclase Ore and Rubracium Ore.

Dysprosium is used for laurenium for chemplant casings for t7-t8 rocket fuel; the ore is present in toxic everglades, so it should be safe to remove from the DD list. Gadolinium (listed as gt++? only) is used for the casings for the broken-ass gt++ matter fab.

**Comment by Prometheus0000** [comment]
Rubracium has samarium, a critical material as a byproduct. Which is ironic, given that rubracium itself is useless. And it's on planets too.

Guess I missed oureclase.

**Comment by boubou19** [comment]
I wonder what will happens to tools made of one of those useless materials.

**Comment by Prometheus0000** [comment]
You need a VM and the DD to get them, so I don't care unless it crashes. They can make another one out of something useful.

**Comment by boubou19** [comment]
Not all the existing bases were made pre DD change to remove all the useless ores from oregen...

**Comment by Prometheus0000** [comment]
Dysprosium Ore, Terbium Ore seems to be used in obama (or at least had ore entries), so will not be removed for now.

I'll check and see what happens.

**Comment by Prometheus0000** [comment]
OK, it crashed. So we need to add something to the mod first before doing anything. Or warn players to throw tools away I guess.
[crash-2021-05-25_10.49.36-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6540181/crash-2021-05-25_10.49.36-server.txt)

**Comment by Prometheus0000** [comment]
Uh, I think someone added a config list, but did they add anything to it?

**Comment by D-Cysteine** [comment]
Config added here:
 * https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6560#issuecomment-886450556

I didn't think I was qualified to figure out what exactly should be removed, so I left the config empty. Doesn't seem like anyone else has added anything yet, either:
 * https://github.com/D-Cysteine/GT-New-Horizons-Modpack/blob/master/config/GTNewHorizons/dreamcraft.cfg

**Comment by Prometheus0000** [comment]
@D-Cysteine I can't get it to work. I tried both names and numbers, but it does nothing.

```
S:BlacklistedMaterials <
        #Americium, Europium, Ichorium, Indium, MysteriousCrystal, Trinium
        103, 70, 978, 56, 398, 868
     >
```

**Comment by glowredman** [comment]
> 
> 
> @D-Cysteine I can't get it to work. I tried both names and numbers, but it does nothing.
> 
> ```
> S:BlacklistedMaterials <
>         #Americium, Europium, Ichorium, Indium, MysteriousCrystal, Trinium
>         103, 70, 978, 56, 398, 868
>      >
> ```

Afaik you have to put all entries below each other:
```
S:BlacklistedMaterials <
        Americium
        Europium
        Ichorium
        Indium
        MysteriousCrystal
        Trinium
     >
```
Also, I don't think using `#` to comment out stuff does not work inside lists.

**Comment by Prometheus0000** [comment]
OK, this looks like it works, thanks.

**Comment by Prometheus0000** [comment]
I spent some time working on a list, so get ready to complain. This reduces the number of ores picked up from 279 (according to colen) to 122.

**Doesn't spawn (also no use for almost all of them):**
        Angmallen
        Atlarus
        Carmot
        Celenegil
        DarkIron
        Dilithium
        Duralumin
        Emery
        Erbium
        Eximite
        Force
        Forcicium
        Forcillium
        Gadolinium
        Haderoth
        Hepatizon
        Holmium
        Infuscolium
        Inolashite
        Meutoite
        Niter
        Oureclase
        PigIron
        Prometheum
        Promethium
        Praseodymium
        Pumice
        Rubidium
        Scandium
        Sanguinite
        Strontium
        Tellurium
		Terbium
        Thulium
		Ytterbium
		

**Is useless (pure materials only in this list), or at least is useless at UEV:**
		Adamantium
		Alduorite
		Ceruclase
		Dysprosium
		Endium
		Lanthanum
		Mithril
		Orichalcum
		Oriharukon
		ShadowIron
		Tartarite
		Vulcanite
		Vyroxeres
		
**Only for taking apart for other stuff that has a more pure ore (scheelite and tungstate, but not tungsten for example)**
		Almandine
		Alunite
		Andradite
		BandedIron
		Barite
		BasalticMineralSand
		Bauxite
		Bentonite
		BrownLimonite
		Cassiterite
		CassiteriteSand
		Chalcopyrite
		Chromite
		Chrysotile
		Cobaltite
		Cooperite
		Diatomite
		Dolomite
		FoolsRuby
		FullersEarth
		Garnierite
		Glauconite
		GlauconiteSand
		GraniticMineralSand
		Grossular
		Ilmenite
		Kaolinite
		Kyanite
		Lazurite
		Lepidolite
		Magnesite
		Magnetite
		Mirabilite
		Molybdenite
		Pentlandite
		Perlite
		Pitchblende
		Pollucite
		Powellite
		Pyrite
		Pyrochlore
		Pyrolusite
		Pyrope
		Realgar
		Rubracium
		Scheelite
		Sodalite
		Spessartine
		Spodumene
		Stibnite
		Tantalite
		Tetrahedrite
		Trona
		Tungstate
		YellowLimonite
		Uraninite
		Uvarovite
		VanadiumMagnetite
		Vermiculite
		Wollastonite
		Wulfenite
		Zeolite
		
**Useful stuff that shouldn't have an ore, and thus not be picked up by a VM:**
        Americium
        Cheese
        CosmicNeutronium
        Electrum
        ElectrumFlux
        Europium
        Flerovium_GT5U
        Ichorium
        Indium
        Lutetium
        Manyullyn
        MysteriousCrystal
        Naquadria
        QuartzSand
        Shadow

**BW:**

**Doesn't spawn:**
       Atheneite
		Crude Rhodium Metal
        Iridium Metal Residue
        Leach Residue
        Orundum
		Platinum Metallic Powder
        Palladium Metallic Powder
        Rarest Metal Residue
		Temagamite
		Terlinguaite
		
**Only for taking apart for other stuff:**
		Arsenopyrite
		Bismuthinite
		Bismutite
		Bornite
		Chromo-Alumino-Povondraite
		Djurleite
		Fayalite
		Ferberite
		Fluor-Buergerite
		Forsterite
		Green Fuchsite
		Hedenbergite
		Huebnerite
		Loellingite
		Olenite
		Orange Descloizite
		Prasiolite
		Red Descloizite
		Red Fuchsite
		Vanadio-Oxy-Dravite
		Wittichenite
		
**Has europium/indium in it:**
        BArTiMaEuSNeK
Roquesite

PS: some ores like bastnasite, borax, calcite, fluorspar, monazite, phosphate or red zircon are the best source for something even if they're not pure. Sphalerite and galena aren't on the list so you can still make indium. Rutile can be used to make titaniumtetrachloride, which reduces costs of some things, so I left it off. Thorianite also has a use in glass, though I'm not sure if anyone would care at this level.

**Comment by boubou19** [comment]
- 1st list: i agree totally
- 2nd list: i agree totally
- 3rd list: outside of the fools ruby, i am against of the ores in this list, because in the current state of things, every ore is added with the same weight in the deep dark, so the probability to get an ore every 10 ticks is 1 divided by the amount of ores inside the orelist. So butchering all the impure ores will just buff a lot the deepdark. 
- 4th list: i think we need to discuss a bit. (for me lutetium should be availiable since the spam of nuclear breeder reactors generate quite some lag due to ic² shitty code)
- 5th list: looks fine, but i'd be fine with only the ores that give platinum line stuff being removed. 
- 6th list: if it's just to reduce the orelist of the deepdark without any other reason, then i make the same remark as for the 3rd list.
- 7th list: roquesite doesnt seems as bad as pure indium, given it's an impure ore, BArTiMaEuSNeK ore is a meme ore and gives Neon outside of europium, which can at least be used to boost x4 the output of the void miner, so maybe that could cause a positive loop (one would need to make the calculus to make sure it's positive tho).

> PS: some ores like bastnasite, borax, calcite, fluorspar, monazite, phosphate or red zircon are the best source for something even if they're not pure. Sphalerite and galena aren't on the list so you can still make indium. Rutile can be used to make titaniumtetrachloride, which reduces costs of some things, so I left it off. Thorianite also has a use in glass, though I'm not sure if anyone would care at this level.

At that point of the game, you don't really care anymore of the best way to get stuff, as efficiency is compensated with speed.

**Comment by Prometheus0000** [comment]
> 3rd list: outside of the fools ruby, i am against of the ores in this list, because in the current state of things, every ore is added with the same weight in the deep dark, so the probability to get an ore every 10 ticks is 1 divided by the amount of ores inside the orelist. So butchering all the impure ores will just buff a lot the deepdark.

That's partly the idea though? Why have things get pulled up that people just void? To add artificial difficulty? Just make the VM slightly slower if you feel it's too strong now.

> 4th list: i think we need to discuss a bit. (for me lutetium should be availiable since the spam of nuclear breeder reactors generate quite some lag due to ic² shitty code)

Lutetium doesn't have an ore, and it's ore should be disabled, like a lot of stuff. I think adding another way of getting it would be better than relying on DD mining. This is also the list I think people will want to complain about the most. Also, I've _never_ heard about nukes being laggy ever.

> 5th list: looks fine, but i'd be fine with only the ores that give platinum line stuff being removed.

Why? They don't even generate in any dim, why start giving them out here so people can void them?

> 6th list: if it's just to reduce the orelist of the deepdark without any other reason, then i make the same remark as for the 3rd list.

And I say the same thing again, why add stuff people will void?

> 7th list: roquesite doesnt seems as bad as pure indium, given it's an impure ore, BArTiMaEuSNeK ore is a meme ore and gives Neon outside of europium, which can at least be used to boost x4 the output of the void miner, so maybe that could cause a positive loop (one would need to make the calculus to make sure it's positive tho).

Those are on the list _only_ because of the massive buff using the VM gives to getting them. If they were as rare as they are normally, I'd have no problem with them being on the list. That said, it doesn't matter that much either way.

PS: the VM should really have the first 2 fluids reworked to be possible to get outside of replicating (which I think everyone on the dev team already knows).

> At that point of the game, you don't really care anymore of the best way to get stuff, as efficiency is compensated with speed.

Again, if people just void something because you need to get 50 or 20 of it to break it apart, why even bother giving it to them? We need some DD players like @GTNH-Colen or @botn365 to tell us what people void and what they keep.

**Comment by Prometheus0000** [comment]
Why is this marked as fixed/closed when nothing happened?

**Comment by Dream-Master** [comment]
huh idk.

**Comment by bombcar** [comment]
This list should be reformatted and rechecked after 2.1.2.0 is out, many things now have uses.

**Comment by MrJakobLaich** [comment]
Removing stuff would add space for things like #9119 (cool soldering alloy stuff that I'm working on)

**Comment by lordclips** [comment]
Quick note since I found this admittedly extremely quiet and quite dead issue, but considering it is still open:

Pig Iron doesn't have any real life equivalent ore form except for the fact that it is iron. However, the original issue says:

"Pig iron (wrought iron)"

When Pig and Wrought iron are two different kinds of iron, each with significantly different carbon contents (pig hovering around 4%, Wrought around .08%). Pig iron has practically replaced Wrought iron, at least IRL, in terms of steel making, and while mostly useless could still be used in the future for better steel-refining accuracy or techniques at higher ages, so at least this one niche case should be considered, as Wrought iron is more of a steel pre-cursor than it is steel itself, while Pig Iron is used directly in the steel making process (or at least, was, since there are techniques that now do iron -> steel processing directly).

I just wanted to argue in favor of Pig Iron, seeing as it could be maybe considered for future use (granted it is made, since it makes no sense in ore form) as another, potentially better, form of steel production in an EBF.
