### ISSUE TITLE
Hopper and Soft mallet issue

### ISSUE THREAD

**Issue by akdude2000** [GTNewHorizons/GT-New-Horizons-Modpack#7918]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
epsilon
#
#### What did you try to do, and what did you expect to happen?
I used a soft mallet on a hopper to temporarily disable its output/input
#
#### What happened instead? (Attach screenshots if needed)
i was immediately disconnected with a "internal server error" message, unpon rejoining server i loaded in and was disconnected about 1second in. 
#
#### What do you suggest instead/what changes do you propose?
idk at least make it so I'm not disconnected immediately, idk how bad it would be to fix, waiting for a server restart, or and admin to reset my position to spawn(if possible while offline), or chunk reset (which would be bad as this is situated in the middle of all my HV machines.)
#
#### What is your GTNH Discord username?
akdude2000#9653

**Comment by Prometheus0000** [comment]
I'm pretty sure you aren't supposed to be able to use it on anything outside of GT anyways.

**Comment by akdude2000** [comment]
the real issue is any one who looks at it gets disconnected, according to an admin it seems to have something to do with there holo glasses. tho i wasn't wearing any, but i was wearing my thaum goggles.

which both have an overlay essentially. idk

**Comment by boubou19** [comment]
this might happen because officials are using a newer hodgepodge version. Will debug it later today.

**Comment by akdude2000** [comment]
feel free to dm me, if you have any question.
