### ISSUE TITLE
OC Transposer Move Speed

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#7919]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
private / unrelated
#
#### What did you try to do, and what did you expect to happen?
Used OC Transposer to move Fluids out of my output hatch (Biomedium Setup, 6 Trans in total). Expected it to work flawlessly

#
#### What happened instead? (Attach screenshots if needed)
Program was extremly slow (around 15 sec for 6 transposers). Slowes down so much it noticably reduces the efficency of the setup. 
#
#### What do you suggest instead/what changes do you propose?
According to bot a transposer needs a sec to move 4 B of liquied. This is way to little. I suggest changing it at least to 32 B a second. OC is powerful but compared to nearly all other ways of moving fluids its just insanly bad. If it cant be properly used on Biomedium which seems like the perfect use case for it i really think it needs a buff. 
#
#### What is your GTNH Discord username?
alphaNOVA

**Comment by Retster** [comment]
Now we are can to configure transposer fluid transfer rate, and that definitely perfect! 👍 

But default value in the config(GTNH 2.1.2.1) now it's set to : **transposerFluidTransferRate=16000** It's mean 16 bucket per second transfer rate. And do not correspond to the needs of the players in the gtnh, it's terribly low.

I suggest to change default walue in this config to at least 512000. And even this value make transfer rate only 25.6 bucket/tick, that not no much but at least we can work with that.🥇
Also i can say that SFM now can transfer any amount of fluid per tick.
Thanks in advance!
