### ISSUE TITLE
Americium Comb Typo

### ISSUE THREAD

**Issue by Yarntheory** [GTNewHorizons/GT-New-Horizons-Modpack#7920]
#### Which modpack version are you using?
2.1.0

There is a typo in the Amercium Comb name, it is spelled "Americum". Which is silly and possibly intentional, but hey.

![image](https://user-images.githubusercontent.com/10872110/117553210-fb746880-b004-11eb-812e-7a60150c86f4.png)

**Comment by interestingusernam3** [comment]
![o3s455ay3fx31](https://user-images.githubusercontent.com/51925758/118449805-c9918f00-b6f3-11eb-8ca6-bb8d25f9d363.png)
