### ISSUE TITLE
Wooden Platform uncraftable in latest stable version

### ISSUE THREAD

**Issue by wildejackson** [GTNewHorizons/GT-New-Horizons-Modpack#7921]
#### Which modpack version are you using?
2.0.9.0 (Last stable)
#
#### If in multiplayer; On which server does this happen? 
Prospercraft, though effects all versions
#
#### What did you try to do, and what did you expect to happen?
Attempted to craft a railcraft "wooden platform" 
#
#### What happened instead? (Attach screenshots if needed)
The wooden platform requires a netherrack cobblestone slab which is itself uncraftable
#
#### What do you suggest instead/what changes do you propose?
I believe there may be a damage value typo, as the more sensible recipe here is to use creosote block slabs (which share the same ID). I also would appreciate if the nether cobble was craftable for decoration (prehaps as a new chisel option for netherrack). The slabs are craftable from the nether cobble block but its uncraftable.
#
#### What is your GTNH Discord username?
wildejackson

**Comment by Prometheus0000** [comment]
Er, what mod is it from? And is that the exact name?

**Comment by Prometheus0000** [comment]
NVM I need to read more thoroughly.
