### ISSUE TITLE
Watter bottle & Coins

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7925]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta 
#
#### What did you try to do, and what did you expect to happen?
![image](https://user-images.githubusercontent.com/59776356/118061947-8a4c0100-b3c8-11eb-8347-92c2b75ad79a.png)
i claimed this quest reward 
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/118061978-9a63e080-b3c8-11eb-9a70-f6d1b7d952eb.png)
only 6 water bottle given and my Coins are not given
#
#### What do you suggest instead/what changes do you propose?
where is those 10 water bottle and my coins go? can i get them back ? and pls fix this issue i don't want other quest reward gone again 
#
#### What is your GTNH Discord username?
Eason1134HK#5098

**Comment by Prometheus0000** [comment]
Water bottles don't stack, so presumably it just voided the stuff it couldn't fit, though I thought it was supposed to spill it on the ground?

**Comment by Eason134HK** [comment]
> Water bottles don't stack, so presumably it just voided the stuff it couldn't fit, though I thought it was supposed to spill it on the ground?

no they are not on the ground they are gone

**Comment by Methes** [comment]
![2021-05-13_19 49 31](https://user-images.githubusercontent.com/8257735/118165271-66b6a400-b424-11eb-8c1b-dd7eaae36e30.png)
Worked for me, extra items dropped on the ground as usual. User error? Using 2.1.0.6

**Comment by Glease** [comment]
Please try reproduce this again. I cannot get this to happen either way.
