### ISSUE TITLE
Make URL links in quests clickable

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#7926]
for example, the quest of the assline. (does this URL need to be updated?)
![url](https://user-images.githubusercontent.com/62897714/118292327-17976e80-b50b-11eb-887d-0a89c60b21fa.jpg)
I think this can also help add more wiki content to the quest.

**Comment by Prometheus0000** [comment]
BQ Tweaker for 1.12 apparently added this and pictures recently or something. It introduced other bugs though, so just backporting it is a bad idea. Personally, I'd rather have the crash bugs fixed.

**Comment by Regian24** [comment]
BetterQuestingTweaker in 1.12.2 does this. I used it in my pack.

**Comment by Prometheus0000** [comment]
It also removes the designer button, which is unacceptable.

**Comment by Regian24** [comment]
You're wrong, I made quests using BQTweaker and I still use the designer button.

**Comment by Prometheus0000** [comment]
https://discord.com/channels/117100935490043911/428732866109636609/836666439770439731

**Comment by Regian24** [comment]
i cant see the message, can you do a screenshot?

**Comment by Prometheus0000** [comment]
https://discordapp.com/invite/AevsYGa <- BQ3 server
Go to #mod_discussion and scroll up a bit

**Comment by Regian24** [comment]
Ok, thank you. I was just using an older version of BQTweaker. Anyways they're putting all the stuff in the configs, so that wouldn't matter.

**Comment by Prometheus0000** [comment]
Someone would still have to backport it at least, and that requires effort.

**Comment by Regian24** [comment]
Yeah. It isn't that big anyway, and sadly it's 1.12 :(

**Comment by Dream-Master** [comment]
can be tested with build
https://github.com/GTNewHorizons/BetterQuesting/releases/tag/3.3.4-GTNH-pre
