### ISSUE TITLE
RFC: EC2 destiny

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#7927]
Due to outstanding code quality, this mod gained universal respect among developers. To get to it's current state it was rewritten from scratch twice, once in a different language (there was also another attempt in yet another language, for the best of luck). It's maintenance is also made so much easier taking into account great fluid support in Forge. Unfortunately, there are some items that do not really fit the theme of the mod, like "Certus tanks", "Large storage cells" and "ME robot upgrade", these should be removed (to AE2 and OC respectively), to preserve perfection and consistency of the mod. If you think there are more items that do not really fit the theme of this great mod, please comment below.

**Comment by Prometheus0000** [comment]
@repo-alt Is this still happening, or did you get busy? I recall you having second thoughts?

**Comment by repo-alt** [comment]
Well I ported certus tank to AE2 to test the concept, and tested that id remapping works, but after that I cooled down a bit. I mean people who use it on their own servers or in SSP may not really care about bugs and dupes, and on officials we may just disable recipes if necessary. As such it is not worthy time investment.

**Comment by Prometheus0000** [comment]
Then I think there needs to be a discussion about what to disable.

**Comment by repo-alt** [comment]
I would disable fluid interface at least.

**Comment by GTNH-Colen** [comment]
> I would disable fluid interface at least.

And the ore dict bus now that we have ore dict cards instead.

**Comment by Prometheus0000** [comment]
Higher tier storage cells: Keep
Crafting storages: Keep
Quartz Tank: Keep
ME OC things: Keep

ME Block Container:Keep I guess
ME Portable Fluid Storage: Keep I guess
Walrus: Keep I guess

Fluid Vibration Chamber: Either way
ME Fluid Annihilation Plane: Either way
ME Fluid Formatting Plane: Either way

ME Drive Fixture: Is this even useful?
ME Energy Cell Fixture: Is this even useful?

Fluid storage cells: Remove
ME Fluid Terminal: Remove
ME Fluid Assembler: Remove
ME Fluid Interface: Remove
ME Fluid Auto Filler: Remove
ME Fluid Export Bus: Remove
ME Fluid Import Bus: Remove
ME Fluid Storage Bus: Remove
ME Fluid Level Emitter: Remove
ME Fluid Storage Monitor: Remove
ME Fluid Conversion Monitor: Remove
ME Fluid Pattern: Remove
Wireless Fluid ME Terminal: Remove
Blast Resistant ME Drive: Remove, as it's buggy

Note that many TE recipes use these, so they need to be adjusted too. Same for quests. If no one comments, I'm going to make a PR to remove everything below the walrus.

**Comment by boubou19** [comment]
This seems ok for me. Fluid AE was a nice QoL, but it doesn't justify at all the gigantic amount of lag induced by its usage.

**Comment by GTNH-Colen** [comment]
ME Fluid Annihilation Plane and ME Fluid Formation Plane may as well go if you are getting rid of the rest, useless otherwise. Walrus also has a few glitches in its rendering iirc so may as well purge that.

**Comment by GTNH-Afx237v7** [comment]
Is the fluid vibration chamber even functional?
Portable fluid storage should also be removed

**Comment by Prometheus0000** [comment]
I don't know why either of them are even enabled. I doubt they produce enough power anyway.

Why should it be removed? It's basically a big bucket. It...might...theoretically...have some use? Or not.

**Comment by GTNH-Colen** [comment]
> I don't know why either of them are even enabled. I doubt they produce enough power anyway.
> 
> Why should it be removed? It's basically a big bucket. It...might...theoretically...have some use? Or not.

Vibration chamber does have a recipe but it's pretty useless (everyone just uses combustion gens) and you'd have to come up with a new recipe for it. I'd vote just axe it tbh.
