### ISSUE TITLE
[TiCon] Crafting Station doesnt see Iron chest inventory

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [GTNewHorizons/GT-New-Horizons-Modpack#7928]
#### Which modpack version are you using?
2.1.6b
#

#### What did you try to do, and what did you expect to happen?

Placed an iron chest next to a crafting station to hold tools and materials, expected it to show in the crafting station the same way a normal chest does
#
#### What happened instead? (Attach screenshots if needed)
The inventory does not show up in the crafting station UI
#
#### What do you suggest instead/what changes do you propose?
Appears ticon uses [TileEntityChest directly](https://github.com/GTNewHorizons/TinkersConstruct/blob/master/src/main/java/tconstruct/tools/logic/CraftingStationLogic.java#L44) ([related gui](https://github.com/GTNewHorizons/TinkersConstruct/blob/master/src/main/java/tconstruct/tools/gui/CraftingStationGui.java#L82))

Newer versions use capabilities and such, so Im not sure how best to fix this.
#
#### What is your GTNH Discord username?
A_D

**Comment by A-UNDERSCORE-D** [comment]
Having a look at hologlasses, looks like there IS a minecraft IInventory that could maybe be used?

**Comment by PhoenixtheII** [comment]
Can confirm on 2.1.0.7a

**Comment by million09** [comment]
any progress?

**Comment by mitchej123** [comment]
The hard part is the gui work.  Seeing the inventory itself is easy-ish to add.  That being said I don't think anyone has picked this up.

**Comment by eigenraven** [comment]
This has been fixed in dev for a while now.
