### ISSUE TITLE
Platline quests are super tedious and awful to complete

### ISSUE THREAD

**Issue by MatthewCOwen** [GTNewHorizons/GT-New-Horizons-Modpack#7931]
#### Which modpack version are you using?
2.1.0.6
#
#### If in multiplayer; On which server does this happen? 
Any
#
#### What did you try to do, and what did you expect to happen?
I'm setting up my plat line and I've got about 1/3 of it done. Now I want to go back and complete a couple quests so that I can unlock the IV tab. However, since I set up my platline using LCRs it is a pain to go through each step, making sure that I get the right outputs from an already automated system.

Quests like this are really annoying:
![image](https://user-images.githubusercontent.com/16054364/118373443-ac31b900-b56b-11eb-905d-f265dae68080.png)

Because after filling up the cells from an output hatch I now have to decouple my output hatch from the input hatch so I can drain the cells in the input hatch.
#
#### What do you suggest instead/what changes do you propose?
I would suggest keeping the retrieval quests, but setting the amounts to 0 so that players can still use the items shown as a way to look them up in NEI. In addition to changing the amounts of the retrieval tasks, I would also suggest adding a checkbox task so that the player still has to look at the quest at least once to proceed.

Furthermore, since the intermediary steps can be easily completed, I would suggest that all rewards be moved to the final step where there is a retrieval task for the pure dust form of the material.

So as an example this quest I showed before could be updated to look like this:
![image](https://user-images.githubusercontent.com/16054364/118373477-ea2edd00-b56b-11eb-8263-9032421e3e11.png)

This would also be helpful to those lucky players who find a platinum vein asteroid in the End. It will allow them to skip over some plat line quests without much hassle.

**Comment by Prometheus0000** [comment]
Duplicate see #7604. Also another one I can't find.
I have a solution already, just nobody wanted to test it. It also needs to be checked on a server before actual use though.

**Comment by Prometheus0000** [comment]
[DefaultQuest(for testing).zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6487988/DefaultQuest.for.testing.zip)
This version has a better test on the first tab though.
