### ISSUE TITLE
Plasma turbines explode when loading chunk

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#7932]
#### Which modpack version are you using?
2.1.0.0 and 2.1.0.6b (happens on both of them)
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I built plasma turbines and expected them to work
#
#### What happened instead? (Attach screenshots if needed)
After server restarts or chunk gets unloaded and loaded again all turbines explode, on 2.1.0.0 I was using IC2 fluid regulator and on 2.1.0.6b I tried GT fluid regulators.
Turbines ran for a few hours and then server was restarted, after I logged in all turbines were gone and probably all exploded at the same time.
This never happened with steam turbines.
Helium plasma flow is 18L/s with large draconium and 4A LuV Dynamo. Theoretically my max flow for this hatch is about 18,5L/s.
When I set flow to 15L/s turbines don't explode (trial and error).
All turbines are in the same chunk.
#
#### What do you suggest instead/what changes do you propose?
Make turbines ignore fluid spikes for a few saconds after loading in or maybe add modular hatch that works like volumetric flask?
#
#### What is your GTNH Discord username?
Pxx500

**Comment by Prometheus0000** [comment]
What plasma though?

**Comment by Pxx500** [comment]
Edited

**Comment by Prometheus0000** [comment]
![image](https://user-images.githubusercontent.com/8517039/118377472-6391f400-b59b-11eb-9634-c2bad0171b81.png)
?

Did you use the old LTC?

**Comment by Pxx500** [comment]
I don't think calculations are the problem since turbines worked for like 20 hours
I did them by hand not using tubine calculator

**Comment by botn365** [comment]
at the start turbine doesent run for a few seconds during that time enough plasma can be horded for the large draconium to generate to much energy and explode

**Comment by Prometheus0000** [comment]
Uh, bot, then how do you prevent explosions?

**Comment by Pxx500** [comment]
And how does that close the topic?

**Comment by botn365** [comment]
i dint use large draconium with 4x LuV

**Comment by Pxx500** [comment]
Doesn't change the fact that turbine doesn't work as intended

**Comment by Prometheus0000** [comment]
So the LTC is correct, and his math is wrong, and he just needed a larger dynamo or different turbine?

**Comment by Prometheus0000** [comment]
> Doesn't change the fact that turbine doesn't work as intended
It should handle near max power

Even infinity turbines don't put out that much?

**Comment by Pxx500** [comment]
I used LTC now and it proves that my calculations are right

**Comment by Pxx500** [comment]
> > Doesn't change the fact that turbine doesn't work as intended
> > It should handle near max power
> 
> Even infinity turbines don't put out that much?

Near max meand slightly less than 4A LuV

**Comment by Prometheus0000** [comment]
Did I not enter something right?

**Comment by Pxx500** [comment]
Excuse me how is that NOT a bug? Turbines are meant to work under these conditions and calculations are proving that

**Comment by Pxx500** [comment]
My turbine generates 125337,6EU out of 131792EU dynamo can handle

**Comment by Skiftcha** [comment]
turbine max input rate is optimal flow + some extra value
for large draconium + helium optimal flow is 30 L/s and max consumption is 37 L/s (i do not know how to calculate it, just practically)
with 200k - 208k eu/t
if you have extra plasma in input hatch, it will use maximum possible plasma.

setting rate for 18 or 15 L/s will work at moment, but anything that will cause extra plasma in hatch (like restart, or just changing broken rotor, or anything else that will make you stop turbine but not fluid regulator) will cause plasma overflow and explosion.

LuV quest also says you to use NORMAL draconium, not large.
and asks you to test in creative.

**Comment by Skiftcha** [comment]
if you use optimal flow value any overflow usually make turbine less efficient so it does not increase eu/t
and in your case overflow cause higher plasma rate and higher efficiency. resulting in eu/t spike and explosion

**Comment by Prometheus0000** [comment]
It was talked about in discord after this, and an understanding was reached.

**Comment by madmacf** [comment]
Has this been solved? 
It's a bug. Very annoying since it just blew up half of my setup.
Running a turbine fine for 20 minutes and logging out. When logging in again, the plasma turbine explodes.
Using a trinium turbine on 4A ZPM buffered hatch, set regulater to 101L/s = about 508000 eu/t. The hatch can handle about 524000 eu/t. Fine tuned it by hand. Running stable.
Optimal flow is 125L/s and that's more than the hatch can handle. 
It seems like the plasma turbine spikes to full load when the world loades.
v2.1.2.0 single player.

**Comment by Pxx500** [comment]
It can be fixed but no one really wanted it that much, after I got information that I was doing things inefficiently I changed my setup and carried on, if you really need it probably just write on mod-dev on discord maybe someone will fix it.

**Comment by chochem** [comment]
turbines are changed in the .4-zeta version. Among other things, turbines no longer explode from having too much energy production. So that should fix any such problems.

**Comment by madmacf** [comment]
@chochem: Very good. I hope it's a permanent feature. 
RIght now it's inconsistent behavior that only the turbine explodes. By that logic a lot of other producers should explode as well. Others producers and batteries just void the excess energy. 
The IC2 reactor can survive reloads even though its heat is at 85% and is close exploding for example. 
Also there's no mention of a "use rotor at 100% rule" in the quest book. Also it can't be a requirement for a user to trawl through the discord chat to find info like that, before activating the turbine. The user can only assume that the regulator is reliable.

**Comment by madmacf** [comment]
@Pxx500: The IC2 reactor was just an example of a machine that has been programmed robustly. That it can survive a reload. The plasma turbine is not working robustly. As you write yourself. The turbine structure loads -> fuel is loaded (too much) -> the turbine starts and ends up spinning too fast for a couple of second ->kaboom.
Ideally the turbine should start and then load the fuel to prevent the problem. If that's way too much work to program then just make it not explode and just void the excess energy.
I enjoy playing the pack. It's just frustrating when a bug (IMHO), makes you stop playing.

**Comment by Pxx500** [comment]
It's fixed now so it's good :)

**Comment by madmacf** [comment]
@Pxx500: Sorry for being an imbecille, but is it possible to get the .4 zeta version? I'm a n00b at using github.

**Comment by chochem** [comment]
check out the discord :)

**Comment by Pxx500** [comment]
All newest versions are on Jenkins, it should be somewhere in the discord

**Comment by madmacf** [comment]
Thank you. Nice to know that it has been fixed.
