### ISSUE TITLE
Oredictionary filter card needs a recipe

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7933]
#### Which modpack version are you using?
2.1.0.6
#
Suggest a recipe, so you can actually make it. If no suggestions, I'll throw something together.

See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7712, https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/45, https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/46.

**Comment by GTNH-Afx237v7** [comment]
Suggestion: 
1x Logic Processor
1x Calculation Processor
1x Advanced Card
GT Type filter (HV?)
288mb molten Redstone
in an assembler (480 eu/t @ 10 secs)

**Comment by Florexiz** [comment]
Fuzzy cards, big eio filter
![image](https://user-images.githubusercontent.com/29033773/120074432-93fe8580-c0a5-11eb-98ea-c8f1d1cd9a0e.png)

**Comment by Dream-Master** [comment]
o will add

**Comment by Prometheus0000** [comment]
We're still collecting suggestions, there's no need to do it right away. Not to mention the latter is probably way too expensive.

**Comment by Dream-Master** [comment]
sure but i cant hear it is too expensive anymore. GTNH becomes more and more a general mc pack.

**Comment by GTNH-Afx237v7** [comment]
Given how the other AE2 upgrade cards are crafted, I propose the following alternative:
![grafik](https://user-images.githubusercontent.com/64365566/120310731-fdb1a600-c2d6-11eb-8880-df3dfa5058a2.png)
1x Advanced Card
1x High Voltage Type Filter
2x Engineering Processor
Shapeless crafting recipe

This also fits the "make every recipe Gregtech-style" more.

**Comment by boubou19** [comment]
I would have put an EV type filter to ensure this advanced feature is unlocked a bit after AE, but otherwise the recipe pattern looks good to me

**Comment by GTNH-Afx237v7** [comment]
I assume the EC2 ore dictionary export bus will be removed in the near future with this card? Thinking about how useful this card is in comparison to the ore dictionary export bus, we may as well put the item filter at IV level. Before that, your ore processing is most likely not going to be that huge anyway...

**Comment by Dream-Master** [comment]
@GTNH-Afx237v7 can you add titanium to set it into the right tier and change the recipe from shapeless to shaped to not accidentally override an existing one.

**Comment by GTNH-Afx237v7** [comment]
Titanium as in EV-type filter instead of IV? Or add titanium as plates, too? All other upgrade cards are shapeless, too, that is why I made this recipe shapeless as well.

**Comment by Dream-Master** [comment]
if it not override anyhing do it shapeless.
I am not sure about the ingredient recipe. are they in iv allready?

**Comment by botn365** [comment]
firts recipe looks horible 
second recipe looks fine

**Comment by GTNH-Afx237v7** [comment]
Second as an the one with the IV type filter (2nd image)? Because I also proposed another recipe (very top) without an image. But I think the type filter recipe is suitable.
