### ISSUE TITLE
Balance of trading

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#7934]
#### Which modpack version are you using?
2.1.0.6
#

It's not a bug reporting but a suggestion and a question.
There is huge amount of trade cycling,for example:
8 Emeralds -> 32 tracks -> 64 iron ingots -> 16 Emeralds
or
4 Emeralds -> 16 boost tracks -> 32 gold ingots -> 16 Emeralds
such like these endless cycle (The number may not be accurate , just an example)

Will you balance the trading or it is just ok for player?

**Comment by Glease** [comment]
It probably take a lot more effort to set up a proper villager farm and find a good trading combination than to just mine those iron ore. I don't see why it need nerfing, but that may be just me.

**Comment by Prometheus0000** [comment]
Tell us how to change the villager trades first, cuz I have no idea how. Also, I don't think it's worth bothering. By the time you can do this, you have more iron and emerald than you can use most likely.
