### ISSUE TITLE
Crash while using a ladder

### ISSUE THREAD

**Issue by MLellmann** [GTNewHorizons/GT-New-Horizons-Modpack#7936]
#### Which modpack version are you using?

2.1.0.7

#### If in multiplayer; On which server does this happen? 

Single Player, two different worlds

#### What happened instead? (Attach screenshots if needed)

I expected to be able to use a ladder - It crashed. (Internal Server Shutdown)

I hat a total of 4 crashes while using world generated ladders (in villages) the instant i got started climbing (up or down).

No crash climbing up a 5th, but then trying to get down, it crashed again.
EDIT: This was in a new world, so it is not dependent on the world.

Crash-Report: https://gist.github.com/MLellmann/fba2f07c3d35f6fa21b82d4d5aac3d40

#
#### What is your GTNH Discord username?

Tywien

**Comment by maniifestantes** [comment]
there's a fix for this, download this file and replace it on the mods folder http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/lastSuccessfulBuild/artifact/build/libs/gregtech-5.09.34.17.jar

**Comment by MLellmann** [comment]
Someone in Discord did link me the same file. Unfortunately, it did not fix the crash. 

Also, an upgrade of Java to 291 (from 271) did also not solve the issue.

**Comment by Glease** [comment]
You might have been using a wrong build. Try this instead: http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/1238/artifact/build/libs/gregtech-5.09.34.17.jar

The lastSuccessfulBuild is something completely unrelated and doesn't actually have the fix

**Comment by MLellmann** [comment]
Thank you - the version from Glease fixed the issue.

**Comment by kasper-tfg** [comment]
I am also getting this same crash as well.  It happens as soon as I join the server now.  
https://paste.ee/p/tzIRb
