### ISSUE TITLE
2.1.0.7 Server Crash

### ISSUE THREAD

**Issue by Aurastorm** [GTNewHorizons/GT-New-Horizons-Modpack#7937]
#### Which modpack version are you using?
2.1.0.7 (server)
#
#### If in multiplayer; On which server does this happen? 
Self-Hosted
#
#### What did you try to do, and what did you expect to happen?
Launch server
#
#### What happened instead? (Attach screenshots if needed)
Crash
[crash-2021-05-18_17.10.05-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6504710/crash-2021-05-18_17.10.05-server.txt)
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6504715/fml-server-latest.log)
#
#### What do you suggest instead/what changes do you propose?
N/A
#
#### What is your GTNH Discord username?
```Aura#0696```

**Comment by Prometheus0000** [comment]
Looks like the crash that occurred on Zeta? Was that not fixed?

**Comment by repo-alt** [comment]
Should use MyEssentials-Core-1.7.10-1.22

**Comment by Aurastorm** [comment]
> Should use MyEssentials-Core-1.7.10-1.22

I do not use MyTown and I have it disabled alongside MyTownWebAuth. Does MyEssentials-Core help if this is the case?

**Comment by boubou19** [comment]
myessentials-core is used by mytown2 iirc. If you don't have it, either update myessentials-core or remove it

**Comment by KaneHart** [comment]
Just remove anything mysomething. I guess it was once again included? Unless this one actually works... With Pure Forge they always had so many bugs and problems...

**Comment by Aurastorm** [comment]
> And don't forget to agree to the EULA ;)
_Yuuuuuuuuup._ I really appreciate you bringing this up because _that was the issue._
Of course it was.
Sigh. Thanks, all.
