### ISSUE TITLE
Autoclave reduces FPS from 100 to 20

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#7938]
#### Which modpack version are you using?
2.1.0.6b
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
I ordered 10k carbon fibre via AE2 with fluid interface. I expected it to produce it without any problems.
#
#### What happened instead? (Attach screenshots if needed)
Items were produced but after this my client had 20FPS for unknown reason. At first I didn't knew the machine was at fault so I tried removing fastcraft, optifine etc. My last hope was to search for a possible cause in-game, when looking around I noticed that my FPS is much lover when looking in the direction of my AE2 system where I previously placed an autoclave with automated carbon fibre. Instantly after destroying it FPS went back to normal. 
#
#### What do you suggest instead/what changes do you propose?
Fix, probably a problem with gregtech?
#
#### What is your GTNH Discord username?
Pxx500
#
After talking on discord I was said to use VisualVM to try to find possible cause, unfortunately I have no experience in analyzing this kind of data so only thing I can do it to upload snapshots of data VVM collected.
https://drive.google.com/file/d/1q8l4alf2i87UsxF6OjZukQKQPzOIvssG/view?usp=sharing
https://drive.google.com/file/d/1ZEpEewCWbbLx-PtT5Dz0M2I_97UuitxZ/view?usp=sharing

I also think the bug might be somehow related to the bug that caused lags for Kharax on ep172 of his series:
https://youtu.be/ZLXcf3Zi2Qw?t=152
Both his distillery and my autoclave are fast and were making a lot of processing at once although his machine wasn't connected to extracells fluid interface. I have to check whether the FPS goes back to normal after turning the power off, but my server admin is asleep so I'll do it tomorrow. I can also upload my map if it will help in any way (also tomorrow).

**Comment by firendlyGhost** [comment]
Fluid interfaces from Extra cells, a notoriously bad mod, cause insane amounts of lag, this is a well known "feature" the mod is getting removed in the near future there's no fix other than dont use it, use fluid P2P instead or other fluid transport

**Comment by GTNH-Afx237v7** [comment]
Fluid interface from EC2 can kill tps but not fps (in my experience).

**Comment by Pxx500** [comment]
I found the reason for the lag, there was a pump set to import on the part of the machine connected to the fluid intefrace and removing it made the lag disappear just as putting it back on resumed the lag.

I guess it's not important so I'll close the issue since pump shuldn't be there in the first place.
