### ISSUE TITLE
[Suggestion] Add quest explaining fluid/eu/redstone p2p tunnels

### ISSUE THREAD

**Issue by Quadrocake** [GTNewHorizons/GT-New-Horizons-Modpack#7941]
#### Which modpack version are you using?
2.1.0.7

It is a bit confusing because NEI recipes for other modes of p2p tunnels are not showing anything, and only mention of how to change p2p modes that I found was in a separate article on GTNH wiki. At least mentioning them in existing quest would be a great addition I think.
Also since EC2 is going to be removed in future it will also help people to see that a viable alternative to it exists already. 

#### What is your GTNH Discord username?
Quadrocake

**Comment by Prometheus0000** [comment]
Does it not say how to make them in the latest version?

**Comment by Quadrocake** [comment]
As of 2.1.0.7, haven't found anything. In separate quest chain for basic AE2 setup, in "p2p" quest there is a mention that EC2 is bad but no mention of fluid p2p.

**Comment by joshaup1999** [comment]
Have you reloaded the quests with the command?

**Comment by Quadrocake** [comment]
Yup, I definetly have new quests. Am I missing something?

**Comment by Prometheus0000** [comment]
I guess I need to add some text then.
