### ISSUE TITLE
Transformers in Step-Up mode not outputting power

### ISSUE THREAD

**Issue by MatthewCOwen** [GTNewHorizons/GT-New-Horizons-Modpack#7948]
#### Which modpack version are you using?
2.1.0.7a
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
I have turbines feeding EV to step up transformers
#
#### What happened instead? (Attach screenshots if needed)
![2021-05-20_11 20 41](https://user-images.githubusercontent.com/16054364/119029860-09f44580-b95e-11eb-9cf6-48d275002dbc.png)
As you can see, the IV voltage side is pointing down, but the 1x aluminium cable is not burning.
Also when I scan my tranformers, they do show to have EU stored within them.

**Comment by Prometheus0000** [comment]
Related to https://github.com/GTNewHorizons/GT5-Unofficial/pull/538 ? @Glease 

Does it work in 2.1.0.7? Or in SP? What's the max storage, is it enough to output 1A of IV?
