### ISSUE TITLE
the adept magic energy absorber and adept magic energy converter only take the advanced hv-tiered circuit (the blue one) instead of any hv-tiered circuit

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7955]
#### Which modpack version are you using?
Dev 2.1.0.6b
####

The Name says exactly what happens here, 
<img width="466" alt="Screen Shot 2021-05-21 at 1 19 36 PM" src="https://user-images.githubusercontent.com/78517796/119174930-316b1100-ba37-11eb-8cfa-39194926939f.png">
<img width="461" alt="Screen Shot 2021-05-21 at 1 19 42 PM" src="https://user-images.githubusercontent.com/78517796/119174943-35972e80-ba37-11eb-8e0d-e6c4ac6d1f52.png">

these only use the primal hv-circuits and not any other kind like normal machines which is a bug or accident I'd think?

#
#### What is your GTNH Discord username?
Alastors_Game

**Comment by Prometheus0000** [comment]
Infusions auto-oredict. Did you try the other types?

**Comment by Alastors** [comment]
@Prometheus0000 trying them rn

**Comment by Glease** [comment]
It does work from the tests conducted by alastors.
