### ISSUE TITLE
Crafting different vanilla fences with screws always results in oak fence

### ISSUE THREAD

**Issue by Quadrocake** [GTNewHorizons/GT-New-Horizons-Modpack#7957]
#### Which modpack version are you using?
2.1.0.7a
#
I've tested spruce, birch, jungle, acacia, and they all result in default oak fence:
![image](https://user-images.githubusercontent.com/46348077/119206022-a7f12880-baa2-11eb-89b8-e1254cc680db.png)
While recipes without screws are working fine:
![image](https://user-images.githubusercontent.com/46348077/119206046-bb9c8f00-baa2-11eb-8158-a346349013f1.png)
And trees from mods are also working fine even with screws:
![image](https://user-images.githubusercontent.com/46348077/119206133-fb637680-baa2-11eb-8bb2-7c310bb45fbe.png)
#
#### What is your GTNH Discord username?
Quadrocake

**Comment by Prometheus0000** [comment]
Wasn't this part of some kind of speedup lea did? So now you need to chisel them. Search for the ticket.
PS: you can't chisel all of them because of GUI BS.
