### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#7959]
#### Which modpack version are you using?
2.1.0.6b and 2.1.0.7a and 2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Crash happens randomly, usually when walking. Never happened on 2.1.0.0 but after going to dev crashes are happening pretty often.
# 
#### What do you suggest instead/what changes do you propose?
Fix
#
#### What is your GTNH Discord username?
Pxx500

[crash-2021-05-22_16.53.37-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6526663/crash-2021-05-22_16.53.37-client.txt)

**Comment by Prometheus0000** [comment]
Did you get the fixes though?

**Comment by Alastors** [comment]
Pxx did you have optifine in the folder? Optifine does that sometimes, mytown also does that, delete both

**Comment by Pxx500** [comment]
> Did you get the fixes though?

What fixes?

**Comment by Prometheus0000** [comment]
Go search discord for them.

**Comment by Pxx500** [comment]
I'm not sure if this is the fix you are talking about http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/1245/
but the game still crashes

**Comment by Prometheus0000** [comment]
If you're using a server did you update myessentials? Other than that the other fixes should be in 7a, so it's a new one or one I don't know.

**Comment by Pxx500** [comment]
Server doesn't have my essentials and optifine was running on version 2.1.0.0 and since it helps my FPS a lot I'm reluctant to delete it

**Comment by KaneHart** [comment]
There might not actually be enough in that crash to figure out the crash. This looks like a night optifine vs something conflicting. I guess the biggest question is you using any those silly OptiFine tweaks like threaded chunk, etc? Their known to break very badly.

I still think you should try to repeat said crash without optifine. I mean your render distance alone is set too high, even though your on a server it will be lower it can still buffer around when moving.

**Comment by Pxx500** [comment]
[crash-2021-05-24_20.50.53-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6535058/crash-2021-05-24_20.50.53-client.txt)
My friend is also experiencing crashes even though he doesn't have optifine.

**Comment by KaneHart** [comment]
@mitchej123 Not sure if you want to check this out before 2.1.1.0

**Comment by botn365** [comment]
ConcurrentModificationException 
this looks like a pain to figure out what would cous this

**Comment by KaneHart** [comment]
Your Java Version is quite Outdated 1.8.0_51 not saying this would fix it, but it's quite outdated. I think were 292? To give you an idea how far behind it is.

**Comment by Prometheus0000** [comment]
> this looks like a pain to figure out what would cous this

Yes, but it's a regression, so we should at least try, since we don't want an update that causes people to crash all the time. Or at least some people.

**Comment by Dream-Master** [comment]
I packing the mod folder twice in the pack. Maybe that is the issue. I reupload the file now.

**Comment by KaneHart** [comment]
> I packing the mod folder twice in the pack. Maybe that is the issue. I reupload the file now.

I highly doubt it read the folder inside. That being said it's hopeful thinking heh.

**Comment by Glease** [comment]
@Pxx500 what version of modpack are you using exactly? 2.1.0.7, 2.1.0.7a or 2.1.0.6?

**Comment by Pxx500** [comment]
2.1.0.6b and 2.1.0.7a

**Comment by Prometheus0000** [comment]
Could you try going back versions until it stops happening?

**Comment by Pxx500** [comment]
2.1.0.0 was fine

**Comment by Prometheus0000** [comment]
Well, it isn't happening to us, so how do you expect us to fix it without knowing which change over the course of months caused it? At least a version would narrow it down.

**Comment by Pxx500** [comment]
Where can I download all the versions?

**Comment by Glease** [comment]
I'll try code a mod real quick to help narrow down the source of bug.

In mean time let's ask on discord if someone else is also having problems like this.

**Comment by Glease** [comment]
Please try add this mod to your mods folder. It will not solve the problem, however it'll add a few more lines to crash report and will (hopefully) help narrow down the cause.

Please do remember due to the nature of this bug (randomly happen only to some people) this might not help at all.

**Comment by KaneHart** [comment]
@Pxx500 any luck getting it to crash since?

**Comment by Pxx500** [comment]
I was having GTNH open for 14 hours straight with no luck getting the crash even though yesterday I had 3.
But I guess 1:12AM when I'm about to go to sleep is the perfect time for a crash.
[crash-2021-05-26_01.12.50-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6542877/crash-2021-05-26_01.12.50-client.txt)
I hope there's something useful in there!

**Comment by Pxx500** [comment]
I can see a lot of red text in game log that is similar to the one in the crash log but not exactly the same. In case it's somehow relevant (it's probably not though):
[Above crash.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6542915/Above.crash.txt)

**Comment by Glease** [comment]
Did you add the debug mod I mentioned above?

**Comment by Pxx500** [comment]
Yes

**Comment by Hachuurui** [comment]
Have you guys considered using Forge's built in function to delete erroring entities/tile entities to help trace this?

Backup the world. Update the forge.cfg to enable that feature, then wait for it to occur and take note of what blocks/items vanish?

If nothing else, it would help narrow down the mod/blocks involved and give you guys a place to search source code wise. If you have a copy of the world I could also setup a test environment for this. Just hit me up on discord.

**Comment by Glease** [comment]
@Pxx500 Hi, I have updated DebugMod to make it more reliably produce thread dumps. Could you please try update it and use this jar instead: https://github.com/Glease/DebugMod/releases/download/1.0.2/DebugHelper-1.0.2.jar

**Comment by Pxx500** [comment]
[log.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6593489/log.txt)
In mod list version of the mod is 1.0.1 if you care about that, but it's not important.
@Glease

**Comment by Glease** [comment]
This is getting on my nerve. why tf it doesn't want to generate the stack trace :(

**Comment by Glease** [comment]
@Pxx500 Hi, sorry for the ping again. I have updated the mod again in the hope it will properly generate the dump this time https://github.com/Glease/DebugMod/releases/download/1.0.3/DebugHelper-1.0.3.jar I have removed all preconditions. If this still fails then I'd have totally no idea what's going on.

If it success, you'd see your crash report bloated with a lot more text. The `Thread Dump` line would also not contain `Not generated`.

**Comment by Pxx500** [comment]
[crash-2021-06-04_16.45.32-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6599320/crash-2021-06-04_16.45.32-client.txt)
Unfortunately it didn't generate

**Comment by Pxx500** [comment]
Since only I and my friend experience those crashes is it possible that it's server sided? Server doesn't crash though and we never crashed at the same time. @Glease

**Comment by Glease** [comment]
That's really just guessing around who is doing bad. There is 1000 cause for a ConcurrentModificationException and the stack trace isn't at all useful. Even if you limit it to a server side only or client side only problem it's still looking for a needle in a haystack.

I created DebugMod in the hope of it adding thread dump to crashreport, which is a lot more helpful while traking down ConcurrentModificationException than the existing infos in the stack trace. However, well you see, it just doesn't want to work 😢

**Comment by Pxx500** [comment]
For some reson I cannot use the map when changing to earlier versions . After loading world the game just goes back to main menu. I tried to use earlier version of my save I saved when going from 2.1.0.0 to dev versions, 2 minecrafts were running for about 20 hours and neither crashed (2.1.0.7 and the other was 2.1.0.2b). I have no clue what to do anymore.

**Comment by Pxx500** [comment]
After gradually removing Extra Cells from AE2 network crashes stopped occurring or are very rare, although I have no direct evidence whether this really was ECs fault.
