### ISSUE TITLE
Random Crash/GT oredict

### ISSUE THREAD

**Issue by PlasmaFox256** [GTNewHorizons/GT-New-Horizons-Modpack#7961]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
i was just mining
#
#### What happened instead? (Attach screenshots if needed)
i picked up a gt ore and game crashed
#
#### What do you suggest instead/what changes do you propose?
look at crash report or fix issue
#
#### What is your GTNH Discord username?
PlasmaFox#3622
[crash-2021-05-23_17.20.56-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6527696/crash-2021-05-23_17.20.56-server.txt)

**Comment by mitchej123** [comment]
Update nei to 2.1+
