### ISSUE TITLE
wraps of muti-layer reinforced circuit boards is registered twice in the game

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#7963]
#### Which modpack version are you using?
2.1.0.0 and 2.1.0.7a
#
#### If in multiplayer; On which server does this happen? 
delta and zeta
#
#### What did you try to do, and what did you expect to happen?
despite having no use yet, the multilayer fiber-reinforced circuit board is registered twice in the game:
![image](https://user-images.githubusercontent.com/12850933/119271765-3da3c980-bc03-11eb-91bc-366240ac7279.png)

**Comment by Prometheus0000** [comment]
BTW, all the wraps have broken names for me. Either due to a bug in the latest version, or because of using a stripped pack.

**Comment by boubou19** [comment]
i noticed some extra s from biocells and stemcells wraps, but other than that, it does not look broken to me on 2.1.0.0 and Manii did not tell me that he was seeing weird things on zeta, so i guess it comes from your stripped instance.

**Comment by boubou19** [comment]
looks like the wrap of coated circuit board is also registered twice in the game.
