### ISSUE TITLE
The oil cracker still only allows going from one direction to the other

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7965]
#### Which modpack version are you using?
Stripped 2.1.0.7a
#
#### What did you try to do, and what did you expect to happen?
Test the cracker
#
#### What happened instead? (Attach screenshots if needed)
You can only go from the left side to the right side
![image](https://user-images.githubusercontent.com/8517039/119272395-a1ae9980-bbd3-11eb-8bf2-1dc0176985ca.png)

#
#### What do you suggest instead/what changes do you propose?
You should be able to input from either side, then output only from the other side, not have it predetermined before you build it. On the other hand, the middle hatch is fixed properly. I recall another issue about this, but couldn't find it.
#

**Comment by botn365** [comment]
people can turn the face 180 degrees

**Comment by Prometheus0000** [comment]
It will still break existing ones though. Is this not easy to fix?

**Comment by botn365** [comment]
nope not easy to fix and this takes them 2 seconds to fix

**Comment by botn365** [comment]
i mean takes to seconds for a player to rotate the face

**Comment by iouter** [comment]
#7616 
is this one?

**Comment by Prometheus0000** [comment]
No, that's about the middle hatch.

**Comment by Glease** [comment]
Fixed during structurelib integration.
