### ISSUE TITLE
Transformer doesn't work (Step up)

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#7966]
#### Which modpack version are you using?
2.1.0.7a
#
#### If in multiplayer; On which server does this happen? 
single
#
#### What did you try to do, and what did you expect to happen?
I have 4 A MV generators outside the cleanroom and through a 4 A cable diode into the room.
then a MV transformer made them to 1 HV. (step up form)
It works before 2.1.0.7 update,but after it won't work.

I tried to find out where the problem is,and i tried a HV transformer (step up) to make 1 A EV (charge 1 EV battery buffer).
but it still doesnt work.
(Step down works)

I think all transformers with step up mode has some problems

**Comment by Prometheus0000** [comment]
Already fixed, also duplicate. Get the fix from the pin in #help.
