### ISSUE TITLE
Removal of platinum group sludge

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#7967]
#### Which modpack version are you using?
2.1.0.7
#
Can we just get rid of this already? We already have the platline.

**Comment by Dream-Master** [comment]
sure let me compare it but this was added by blood so it is very old

**Comment by Ngar1** [comment]
why not let it be? It works and receipts were changed to the new platinium dusts.

**Comment by Prometheus0000** [comment]
Because it's taking a slot that could be used for new materials. 3 if you include the fluids.

**Comment by Ngar1** [comment]
ok, thx for explanation

**Comment by Dream-Master** [comment]
@Prometheus0000 remove of a existing Material is not a goid code style. We got backwards compatibility issues.

**Comment by Prometheus0000** [comment]
Why not? It's basically useless. And we already need to clean up and remove a bunch of materials anyways too.

Where is the backwards compat issue?

**Comment by Prometheus0000** [comment]
So did you make a decision on this or what?
