### ISSUE TITLE
Purple Drink has no recipe

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/GT-New-Horizons-Modpack#7968]
I was looking up how to make more chum burgers, for the hunger effect, and noticed that they need purple drink in a Mixer; however purple drink has no crafting recipe.

**Comment by Prometheus0000** [comment]
Do we really need this stuff though? Can we have it in _without_ using a precious material slot? Which I'm pretty sure it uses.

**Comment by mitchej123** [comment]
It's already there, it's on gt6... yes we need it.  Now it needs a recipe :)

**Comment by Ethryan** [comment]
Maybe chemical reacting fluid Poison with Spider Eyes?

**Comment by Dream-Master** [comment]
> It's already there, it's on gt6... yes we need it. Now it needs a recipe :)

I guess it was designed to found in chests only?

**Comment by mitchej123** [comment]
> I guess it was designed to found in chests only?

Lol.  Given how much we've changed things, I don't think the original design of where to get things should matter *too* much.  :)

**Comment by Dream-Master** [comment]
ok sure add a recipe if you like :)

**Comment by mitchej123** [comment]
*gasp* how dare I close my own issue.  Totally reopening this and will add a recipe at some point :rofl:

**Comment by YannickMG** [comment]
Add some purple essentia to the recipe for extra pain.

**Comment by mitchej123** [comment]
:scream:
