### ISSUE TITLE
TF: Naga not spawning

### ISSUE THREAD

**Issue by Koalacards** [GTNewHorizons/GT-New-Horizons-Modpack#7969]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
N/A on singleplayer
#
#### What did you try to do, and what did you expect to happen?
I went to a naga chamber expecting for the spawner to spawn the naga boss
#
#### What happened instead? (Attach screenshots if needed)
The naga spawner kept spinning and didn't spawn the boss. I also tried to use a naga spawn egg and it disappeared immediately.
#
#### What do you suggest instead/what changes do you propose?
Not sure if this is a bug with the version, but the naga gates Thaumcraft so I would appreciate any help.
#
#### What is your GTNH Discord username?
Koalacards#4618

**Comment by Glease** [comment]
Can't reproduce. Check if you are on peaceful or some server side plugin is at play here.

**Comment by KaneHart** [comment]
Also can't reproduce as well. Like said above you might be just in peaceful mode. When you spawn a mob in peaceful mode I'm pretty sure they also vanish instantly like that.

**Comment by Dream-Master** [comment]
In peaceful mod it isnt possible to spawn the TF Bosses so far ik.

**Comment by Koalacards** [comment]
Thanks for the comments. I had created a test world to try out some setups and didn't realize that the peaceful mode carried over between worlds. Put the difficulty backed to normal and it spawned file 👍
