### ISSUE TITLE
Cooking for Blockheads Needs Recipes.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#7970]
#### Which modpack version are you using?
2.1.0.7a

I'm pretty sure I did not see a dedicated thread for this. Even basic plates, etc. It should not release into 2.1.1.0 without it.

**Comment by mitchej123** [comment]
Dream has a PR in review

**Comment by Dream-Master** [comment]
@KaneHart https://github.com/GTNewHorizons/CookingForBlockheads/pull/6
