### ISSUE TITLE
Output Bus (ME) is expensive to craft

### ISSUE THREAD

**Issue by EReeeN1208** [GTNewHorizons/GT-New-Horizons-Modpack#7972]
#### Which modpack version are you using?
2.0.1.7

#### What do you suggest instead/what changes do you propose?
The Output Bus (ME) is expensive to craft for the purpose it serves. It's meant to be a lag friendly option, but requires 2 ME interfaces, 4 EV Circuits, 2 Acceleration cards and an EV output bus. The name states it acts like an output bus, and the questbook states it can act like an interface, output bus or import bus. I believe that the current recipe should be changed, as this item doesnt offer any benefit other than causing less lag.

#### What is your GTNH Discord username?
EReeeN1208#8490

**Comment by EReeeN1208** [comment]
Note: I misspelled the version, it is 2.1.0.6
Sorry for the inconvenience

**Comment by GTNH-Afx237v7** [comment]
It is a lag friendlier option, however that only comes into play when the output bus is outputting items at a high rate. I am not aware of specific numbers, say in terms of items/tick, but I believe the optimization comes into play at a time where the above recipe is no longer too expensive to be worth it.

**Comment by repo-alt** [comment]
ME outpus bus is "necessary" when the usual output bus pointing into an interface can't keep up, that is, when the output rate is at least 2 stacks per tick (8 stack/t is the theoretical throughput limit for the interface, but it is usually throttled). Indeed ME output bus is more CPU friendly even before that, because it involves no slot handling, but, before you start counting in stacks per tick the effect is minimal.

**Comment by repo-alt** [comment]
(not like I'm against making it cheaper, just a technical note)

**Comment by GTNH-Afx237v7** [comment]
I’ve had a regular bus/interface combo take up 1,000ns while the ME output bus used 4,000ns (both as per tricorder indication), hence my comment about a „break-even“ point.

**Comment by repo-alt** [comment]
This is weird, ME bus does no work of a bus and only a part of the interface job, so why it may take more time is beyond me

**Comment by GTNH-Afx237v7** [comment]
I may have to grab the latest dev and test again, iirc I tried las time with 2.1.0.5b

**Comment by repo-alt** [comment]
I have a possible explanation: tricorder cannot measure item storing time in a usual interface, (because it is not really localized), but in the ME bus it is done locally. The work time of the usual bus is negligible if it is not facing a big inventory (and does not have a big inventory itself).
