### ISSUE TITLE
Please add Stone Legion to the Server List.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#7974]
#### Which modpack version are you using?
2.1.0.7a

Hello StoneLegion.com has decided it will be ready to be put back on the Server List.

Server Name: StoneLegion.com GTNH (Canada)
mc.stonelegion.com

Were still worlds genning, etc. But we should be online this week so it's safe to throw us on for the 2.1.1.0.

**Comment by KaneHart** [comment]
@Dream-Master 

Hey mate I checked the first 3 servers on the list and were not there!

![image](https://user-images.githubusercontent.com/425853/122293706-49627300-cec5-11eb-994d-6e91af5c6a58.png)


Joking aside were not on the entire list :)

Thanks.

**Comment by Prometheus0000** [comment]
?
![image](https://user-images.githubusercontent.com/8517039/122294028-a100de80-cec5-11eb-839f-a2c57140f31a.png)

**Comment by Prometheus0000** [comment]
Maybe it wasn't updated properly?

**Comment by KaneHart** [comment]
Strange... Maybe I got the wrong client let me double check... I did a 100% new instance.

**Comment by KaneHart** [comment]
Can confirm that it's not bundled with Pre2 Version. Must be the version just before this request before.
