### ISSUE TITLE
Blood Magic Recipe Balancing

### ISSUE THREAD

**Issue by Sunrobbie** [GTNewHorizons/GT-New-Horizons-Modpack#7975]
#### Which modpack version are you using?
2.1.0.7a

#### Description of Problem

Blood magic is gated extremely harshly in this pack. I agree it should be difficult, but in order to create a Well of Suffering, the ritual which allows you to automate the collection of LP for your altar, you need to craft:

37*13 (481) Blank Slates
37*4 + 1*36 (184) Reinforced Slates
37*2 + 1*2 (76) Terrae
A large amount of obsidian tile and 4 obsidian totem, but that is comparatively easy to obtain

Additionally, you need a tier 3 altar in order to even craft the activation catalyst for the ritual, upgrading your altar to that point requires at minimum 28*4 (112) Blank Slates, without accounting for the crafting of any enhancer runes such as speed or sacrifice.

Now, you need to craft a total of 481+184+112 or 777 blanks slates at the bare minimum to achieve a Well of Suffering. Each slate takes 2000 LP, and at 0 speed runes the altar will operate at 20LP/tick, so 5 seconds per rune. This means 777*5 (3,885) seconds or around 65 minutes of nonstop altar operation. Each reinforced slate takes exactly twice as much LP and therefore twice as long, resulting in 184*10 (1,840) seconds, or another 30 minutes of stabbing yourself or other creatures at the blood altar. Additionally, every 9 arcane slate takes 60 seconds to cut in a cutting machine with 1000L Life Essence, so 65 seconds per slate when accounting for the fill speed of a life essence cell, or another 93 minutes of crafting/stabbing time.

Thus, assuming you have infinite health and can afford to stand still at an altar using the dagger constantly, it will take you at bare minimum 3 hours of sitting at the altar and making sure it doesn't run out of life essence. This can be reduced by making and using speed runes, but without the help of sacrifice/self sacrifice runes, it's impossible to keep up with more than 1 or 2 speed runes for a 40% speed boost. Health restoration methods are also rather difficult, and whether it's a wand focus mending or regeneration potions, each heart is worth only 100LP. With the total LP cost being over 1.5 MILLION LP in just the Arcane Slate -> Blank Slate step alone, you need to sacrifice well over 15k hearts or 3k mobs.

Therefore, it's nearly impossible to achieve the 3 hour time even if you decided to craft speed runes, as either you need ridiculous regeneration powers or a large amount of mobs, which is not healthy from a server standpoint. In reality, it takes more in the realm of 5+ hours of self sacrifice in order to get a basic Well of Suffering setup.

When you finally do have a Well of Suffering setup, it's not even very good. The easiest path to lots of LP is to spam witches or undead mobs on graveyard soil, rather than bothering to spend the hours collecting ingredients and microcrafting sacrifice runes.

#### Proposed Changes 

Basic Crafting Stuff:

Runes of Sacrifice/Self Sacrifice should be made MUCH cheaper, and available earlier, perhaps tier 2 altar: Making these cheaper but still requiring the grind of slates for the T2 altar will keep an entry barrier, but will make it easier to keep up with more speed runes, speeding up further rune crafting. Additionally, making these cheaper will help discourage creature spam under a blood altar, as more runes on the altar means more LP per Well of Suffering tick, reducing the number of mobs you need for the same LP gain. 
Possible recipes: Move to arcane table, craft with 40 Vis of each type.
                           Remove one of each of the reagents, Imbued Slate->Reinforced Slate
                           Tier down Imbued Slate -> Blank Slate
                           Change reagents from BM reagents to Thaumcraft Crystal Clusters
                           Any mixture of the above
Crafting these should not be extremely easy, but be highly incentivized to avoid mob spam.

Change the Simple Catalyst Recipe to use Wood Ash instead of Growth Medium: Crafting Simple Catalysts at lower tiers (MV, HV) is extremely tedious, and growth medium takes both too long to mix and requires a large amount of bones/mulch/wood ash/sugar, some of which are difficult to obtain in large amounts early on, especially with how dangerous mobs can be in these tiers. Lowering the cost of a simple catalyst by removing one crafting step of the components helps make most of blood magic less painful, as simple catalysts are required in almost every recipe.

Swap Lava Bucket in Incendium recipe to Lavastone Bricks, Lava Cells, or something that can be stacked: Crafting the Incendium for sacrifice runes requires you to babysit the alchemic chemistry set and swap out empty buckets, I recommend changing the Lava Bucket to something stackable

Reduce the cost of an Imperfect Ritual Stone: Changing the Blank Blood Stone to a Blood Rune will reduce the Slate cost by around 25% but add a large cost in concrete and some energy, reducing the time spent crafting at the altar and forcing an at least temporary concrete/assembler setup to be created.

Sigil Changes:

Sigil of Suppression: Why does this require a teleposer? It lets you walk through fluids unobstructed, replace teleposer with a Drain Module Cover, keeps it thematic, no need for tungstensteel and a ridiculous amount of slates to walk through water/lava. Alternatively, maybe a wand focus telekinesis instead of a teleposer.

Sigil of Magnetism: This requires blocks of Magnetic Neodymium, and Energetic Alloy Dusts+lot of Simple Catalysts for the Potentia, when it's literally just a magnet? Current recipe is far too expensive when an enderio Electromagnet can be made in HV as soon as you make a vac freezer. Changing the blocks to Magnetic Steel makes it remain difficult because of the Potentia and aspect requirements, and allows access around the same time as other magnet options.

Sigil of the Blood Lamp: This sigil needs a tier 3 altar, 8 Plutonium 239 dusts, 2 Hyperenergetic Nitor, all to place light sources? Change the Hyperenergetic Nitor to just Nitor, tier down the slates, and swap the Virtuus for Magicales or Incendium.

The other sigils seem fairly balanced, open to suggestions.

Warp:

There's way too much warp on the researches, I recommend reducing the amount of warp by a large amount. While it should be the most warpy tab, by no means should it account for over 300 warp on its own, especially when withers spawn at only 80.

#
#### What is your GTNH Discord username?
Sunrobbie, Fluid Nuke Initiate

**Comment by 0lafe** [comment]
can't you automate LP gen with a mob spawned and the non player dagger? definitely a pain to do by hand but iirc i wasn't do it by hand

**Comment by Sunrobbie** [comment]
> can't you automate LP gen with a mob spawned and the non player dagger? definitely a pain to do by hand but iirc i wasn't do it by hand

I just performed a test using the Dagger of Sacrifice in a Dynamism Tablet, and it punches mobs with the dagger but the sacrifice does not perform, and no LP is added to the altar

**Comment by Alastors** [comment]
I will note, studying the entire thaumonomicon nets you just above 700+ perm warp total, blood magic itself as noted by Sun accounts for literally 300+ of that warp making it around 3/7ths of the total books warp, let that sink in. Three Sevenths of _all_ warp, _all concentrated in a single tab of the book._ That is too much warp for one tab in general so a lot of the warp should be reduced a level or two tbh.

**Comment by yukieiji** [comment]
Blood Magic distortion change was discussed in an earlier ticket(#5604) and I believe the conclusion was no.

**Comment by Alastors** [comment]
> Blood Magic warp change was discussed in an earlier ticket(#5604) and I believe the conclusion was no.

This was a long time ago and dream said it himself "After we add new effects to warp Theory we can do new balancing about Blood magic" 

Plus the fact of the matter is, many things have changed since this discussion, such as the removal or nerfing of many warp removing thaumic machines since then. So clearly blood magic itself is in the run to get rebalanced.

**Comment by yukieiji** [comment]
In the past year, Warp has only softened with the implementation of ImpureTear and increased difficulty with Soul Blazier and Warped Tumor recipe changes, but I don't think it has changed that much.
I also think it's premature to diminish Warp since no new Warp effects have been implemented in WarpTheory.
Warp have increased from a year ago(https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5643#issuecomment-590108550), which is probably due to adjustments other than BloodMagic.

**Comment by combusterf** [comment]
I too noticed that the LP cost of getting well of suffering/feathered knife should go down dramatically since there is no legit way of automating it before that. In terms of self-sacrifice, that is roughly 20000 pricks, or 20 hours of manual clicking with the regeneration I buff active.

That's not effort, that's slavery
