### ISSUE TITLE
Crash when trying to click the questionmark on an arcane worktable with stuff already in it

### ISSUE THREAD

**Issue by gordominossi** [GTNewHorizons/GT-New-Horizons-Modpack#7976]
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
Singleplayer

#
#### What did you try to do, and what did you expect to happen?
Tried auto filling the crafting workbench with the recipe for woven cotton when it already had 18 woven cotton laid out in there.
Expected to auto fill the worktable as a regular workbench

#
#### What happened instead? (Attach screenshots if needed)
[The game crashed](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6534788/crash-2021-05-24_17.18.00-client.txt)

#
#### What do you suggest instead/what changes do you propose?
Not crashing

#
#### What is your GTNH Discord username?
gordominossi

**Comment by Prometheus0000** [comment]
Try updating
