### ISSUE TITLE
Speed up the Thaumic Stone Extruder or Make it not require the HV rock breaker, It takes 10x as long to produce the same amount of stone

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7978]
#### Which modpack version are you using?
2.1.0.6b
#
#### What did you try to do, and what did you expect to happen?
Not be worse than the item it needs to be crafted
#
#### What happened instead? (Attach screenshots if needed)

"Thaumic Stone Extruder is a block added by the Witching Gadgets mod. When placed in the world, it will automatically produce Cobblestone, one in 2 seconds ." -FTB wiki, and I am very sure this is accurate. (I just now checked it, it is exactly 2 seconds, jesus christ it is slow)

<img width="714" alt="Screen Shot 2021-05-25 at 1 00 04 PM" src="https://user-images.githubusercontent.com/78517796/119538451-20810f00-bd59-11eb-864f-61befcbea002.png">

Notice it needs the HV rock breaker to be crafted and a flipping energy crystal for, if the FTB wiki is correct

For reference I let the stone extruder run for a bit by itself so it could get some inventory
and then a few minutes later after it got around 4 stacks I started building an hv rock breaker (the machine it takes to build the stone extruder for some idiotic reason) and waited to see how long it would take to surpass it

It took fucking 40 seconds to do the same thing it had taken the stone extruder around like 7 to do. 

![Screen_Shot_2021-05-25_at_1 35 19_PM](https://user-images.githubusercontent.com/78517796/119543391-9b98f400-bd5e-11eb-8f1e-3b31311d1d74.png)
![Screen_Shot_2021-05-25_at_1 35 42_PM](https://user-images.githubusercontent.com/78517796/119543405-9fc51180-bd5e-11eb-9ba7-38b39d5b0474.png)
![Screen_Shot_2021-05-25_at_1 36 04_PM](https://user-images.githubusercontent.com/78517796/119543419-a3f12f00-bd5e-11eb-9b8d-ab3c2e41fdae.png)

And to prove I didn't just break the stone extruder or whatever, 
<img width="1440" alt="Screen Shot 2021-05-25 at 1 36 56 PM" src="https://user-images.githubusercontent.com/78517796/119543585-cdaa5600-bd5e-11eb-9a94-ee9a0e08a4d6.png">

#
#### What do you suggest instead/what changes do you propose?

Either make it not require any of the rock breakers and just make it use a hammer (And sure as hell not the energy crystal, or at the very least make it as fast as the hv rock breaker, 2 seconds for no energy that you have to infuse with literally everything vs 0.2 seconds for a literal _single amp_ of hv is ridiculous 

<img width="518" alt="Screen Shot 2021-05-25 at 1 29 02 PM" src="https://user-images.githubusercontent.com/78517796/119542121-2c6ed000-bd5d-11eb-96df-d81a4de05b4b.png">

for reference this is _stone_ out of the _LV ROCK BREAKER_, notice how LV is 5 times faster than something that not only takes the HV equivalent of this but also an energy crystal?!

I propose that the Thaumic Stone Extruder should at least be twice as fast as the HV rock breaker since there is so much more involved in crafting and all of that. (so literally just 1 stone every tenth of a second vs the HV rock breaker's 1 stone every fifth of a second

Also do the same for the Thaumic Ice Solidifier, I can't find out how fast it is online but it has the exact same cost so Im sure its the same issue

<img width="909" alt="Screen Shot 2021-05-25 at 1 42 49 PM" src="https://user-images.githubusercontent.com/78517796/119543828-195cff80-bd5f-11eb-9694-b085328e297d.png">

#
#### What is your GTNH Discord username?
Alastors_Game

**Comment by Alastors** [comment]
I will add, Prom said since y'all had a fork of Witching Gadgets that it wouldn't be that hard, all that'd have to be done is a switch the speed, "Probably change 32 to something else to make it faster", which by god if it is going to keep its current recipe (which it shouldn't), the speed needs to be increased

https://discord.com/channels/181078474394566657/234936569360809996/846794913802223706

**Comment by Cata-bre** [comment]
Any update on this? If we don't make it faster, then we should make it cheaper. As it stands, the Thaumic Extruders are not currently worth the warp.

**Comment by bombcar** [comment]
I'm staring at the code right now, I could make it faster; though we might lose the cool sound effect which plays 32 ticks into the process.

How would people feel if it still worked every 2 seconds, but instead produced 16 cobble?

**Comment by Alastors** [comment]
> I'm staring at the code right now, I could make it faster; though we might lose the cool sound effect which plays 32 ticks into the process.
> 
> How would people feel if it still worked every 2 seconds, but instead produced 16 cobble?

16 cobble every other second is really nice, though I feel that for it's price, every second would be more justified, but either way, thats still a major major improvement! Thank you!!!

**Comment by bombcar** [comment]
Setting up a test world to spawn this in, but it's "powerless" once build, right? And just produces stone forever?

**Comment by Alastors** [comment]
> Setting up a test world to spawn this in, but it's "powerless" once build, right? And just produces stone forever?

yes essentially, at the cost that it is much more expensive than the rock breaker of the HV tier, and has no further upgrades
