### ISSUE TITLE
Game crashing when breaking Small Brown Limonite Ore with TiCon hammer.

### ISSUE THREAD

**Issue by r58Playz** [GTNewHorizons/GT-New-Horizons-Modpack#7984]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
Broke Small Brown Limonite Ore indirectly with TiCon hammer*
I expected it to break a 3x3 of blocks including the Small Brown Limonite Ore.
*ex: X=small brown limonite ore, Y=brown limonite ore, Z=stone, bold Z is the block I'm breaking.
ZXZ
Y**Z**Z
ZZZ
#
#### What happened instead? (Attach screenshots if needed)
The game crashed. Log and crash report below discord username.
#
#### What do you suggest instead/what changes do you propose?
Try to fix this bug
#
#### What is your GTNH Discord username?
r58Playz#3467

Log:
https://paste.ee/p/vod3W

Crash Report:
https://paste.ee/p/GtCXz

**Comment by Prometheus0000** [comment]
Already fixed, duplicate, learn to use search.
