### ISSUE TITLE
Server commands like /home

### ISSUE THREAD

**Issue by simbiant** [GTNewHorizons/GT-New-Horizons-Modpack#7985]
#### Which modpack version are you using?

2.1.0
#
#### If in multiplayer; On which server does this happen? 

2.1.0.0
#
#### What did you try to do, and what did you expect to happen?

Any mods on server for setting commands like /home /spawn
I don't know how to install it(

**Comment by boubou19** [comment]
for this kind of questions, please use the #help channel of our discord server. And you are looking for something like either forge essentials if you want to stay on a pure forge server, or use plugins like essentials if you want to run it on thermos (discouraged).
