### ISSUE TITLE
Change cheaper Vacuum Tube recipes to Circuit Assembler instead of normal Assembler

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#7987]
The first ULV Circuit (Vacuum Tubes) has a cheaper recipe using the assembler (using molten red/redstone alloy). As every other circuit in the game (excluding nano and pico circuit) has their recipe in the circuit assembler, i propose to change the recipes for the ULV Circuit to the Circuit assembler

#### What is your GTNH Discord username?
TrainerSnow
#5086

**Comment by Methes** [comment]
Stretching LV further makes no sense. It makes crafting LV circuits easier.
Also it uses molten red(stone) alloy instead of tin/soldering iron.
If the discrepancy really bugs you, figure out additional recipe for circuit assembler instead of getting rid of the assembler one.

**Comment by Ngar1** [comment]
Redstone is "solder" like base receipt (red... bolt) and does not fit to standard solder alloy of IC production. It forces every existing world / fab to change their setup without need or advantage. Please change only if it makes the game more fascinating, not jangle players.

**Comment by Prometheus0000** [comment]
There's already Nand Chips that are made in the CA. This is a _tube_ not a real circuit, there's no reason for a CA recipe, you're supposed to stop using it after you make the MV CA.
