### ISSUE TITLE
Medium Oil not outputting

### ISSUE THREAD

**Issue by EReeeN1208** [GTNewHorizons/GT-New-Horizons-Modpack#7988]
#### Which modpack version are you using?
2.1.0.6
#

#### What did you try to do, and what did you expect to happen?
I set up an Fluid Drilling Rig in a chunk that contained medium oil. According to the folks on the discord, it would output raw oil or normal oil.
#
#### What happened instead? (Attach screenshots if needed)
Once the mining pipes reached bedrock, the rig did not output any oil, and instead started pulling the pipes back up, and placed them back down after all the pipes were extracted.
#
#### What do you suggest instead/what changes do you propose?
Either a new type of oil to be added, or medium oil to be changed into raw or normal oil.
#
#### What is your GTNH Discord username?
EReeeN1208#8490

**Comment by EReeeN1208** [comment]
I do not remember the exact amount, but the chunk contained around 250-500 medium oil. I can check if needed.

**Comment by Glease** [comment]
Did you drilled the right chunk? Maybe it's too close to the edge of oil region and the controller went to another field that is empty, while the rest of machinery is left in the rich oil field.

**Comment by EReeeN1208** [comment]
The rig is fully in the correct chunk.

**Comment by Glease** [comment]
After discussing on discord, the prospecting result might has been misinterpreted. The chunk doesn't actually contain any oil.
