### ISSUE TITLE
Solar boilers calcify far too quickly

### ISSUE THREAD

**Issue by ben0sharples** [GTNewHorizons/GT-New-Horizons-Modpack#7989]
#### Which modpack version are you using?
2.1.0.7a
#
High Pressure Solar Boilers are calcifying significantly quicker than they were for me on 2.1.0.0, can't confirm if the same is true for regular Solar Boilers but I would presume they work on the same code.

FTBWiki says that the calcification process (after the initial delay where they work at full capacity) should take approx. 3 and a half hours. Counting the time between calcification ticks (where the output reduces by 1L/s) I got approx. 14 seconds. Full calcification is 240L/s which would take 56 minutes at this rate. This is over three times faster than the base rate, though I don't know if they'd had any kind of nerf in GT:NH prior to this.

I'd presumed this would be due to the halving of the cycle length in Glease's code cleanup, but that would explain a twofold rate increase, where this is more than threefold. There may be something else going on to cause such a significant rate increase, if there wasn't some kind of adjustment that had already been made to them.
#
#### What is your GTNH Discord username?
Exp0nent

**Comment by Prometheus0000** [comment]
@Glease Did you see this one as well?

**Comment by ben0sharples** [comment]
He's the one that suggested I make a new thread for it so he should be aware.

**Comment by Glease** [comment]
I actually forget about it. I vaguely remembered something need to be done with boilers, and the first search result on discord showed some integer overflow problems.

Nonetheless the problem will be fixed in that PR as well
