### ISSUE TITLE
add Just Enough Calculation ported from 1.16

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#7990]
https://github.com/Discreater/JustEnoughCalculation

**Comment by yukieiji** [comment]
Duplicate of #7899, #6145, #3186,  #1185

**Comment by iouter** [comment]
this is backported from 1.16

**Comment by Alastors** [comment]
> this is backported from 1.16

just going to tell you now, this probably won't ever happen especially the 1.16 version, as back porting from like 1.8.9 is a bitch, and each version up just makes it a lot worse, so unless it is absolutely gamebreaking quality of life changes it just typically won't happen without an act of god

**Comment by Alastors** [comment]
nvm I got notified and have since realized it has already been backported. Kekw

**Comment by Prometheus0000** [comment]
!nei

**Comment by KaneHart** [comment]
It's never considered a duplicate if the other ones are closed ;)

**Comment by Discreater** [comment]
Hi, I'm the maintainer of the 1.7.10 version. The 1.7.10 branch has been merged into the [original repository](https://github.com/Towdium/JustEnoughCalculation/tree/1.7.10), and has been released in [curseforge](https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation).

This mod can help you calculate how many of resources you need to gather for certain items. It won't load any recipe automatically. But you can easily transfer the recipe from NEI recipe handler gui by clicking the `?` button, or add a custom recipe. 
It also supports fluid(only support several mods now) and ore dictionary. And it can check inventory for missing ingredients.

At present, It has almost all features in it's 1.16 version, excepts:
- Client only.
- No calculator item. Open the gui by press key. No default key bindings.

For more information you can check [README](https://github.com/Towdium/JustEnoughCalculation/blob/1.7.10/README.md) and this [issue](https://github.com/Towdium/JustEnoughCalculation/issues/85)

**Comment by Dream-Master** [comment]
Has the mod a open license because I don't add mods are closed source or with cryptic license.

**Comment by Discreater** [comment]
GPLv3
https://github.com/Towdium/JustEnoughCalculation/blob/1.16/LICENSE.md
https://github.com/Towdium/JustEnoughCalculation/blob/1.7.10/LICENSE.md

**Comment by repo-alt** [comment]
Why was it not added still?

**Comment by davey-tan** [comment]
Bump?
