### ISSUE TITLE
Server crashes during initalization

### ISSUE THREAD

**Issue by TheElan** [GTNewHorizons/GT-New-Horizons-Modpack#7994]
#### Which modpack version are you using?

# 2.1.0.7a
#### If in multiplayer; On which server does this happen? 

# private
#### What did you try to do, and what did you expect to happen?
I was originally trying to update my 2.1.0.0 server, which worked perfectly fine with Eclipse OpenJ9. Even after trying a fresh server with Oracle java it didn't start.

I had downloaded server from link in `announcments` channel: http://downloads.gtnewhorizons.com/Dev-Pack/Pack/Server/GTNewHorizonsServer-1.7.10-2.1.0.7a.zip

#### What happened instead? (Attach screenshots if needed)
It crashed during initialization, attaching logs (both for Oracle and Eclipse JVM).
There different errors for different JVMs, however they both have problems with ToolNetworkTool as I can see.

[crash-2021-05-29_21.32.21-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6565189/crash-2021-05-29_21.32.21-server.txt)
[crash-2021-05-29_21.34.39-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6565190/crash-2021-05-29_21.34.39-server.txt)
[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6565192/fml-server-latest.log)

#### What is your GTNH Discord username?
Elan

**Comment by TheElan** [comment]
As suggested in discord, removing MyTown mods didn't help.

**Comment by TheElan** [comment]
Updating to Oracle Java 8u291 didn't hel either

**Comment by TheElan** [comment]
guavo47 wrote:
> Just tried to upgrade from 2.1.0.6b to 2.1.0.7a and had the same issue.
> Appears appliedenergistics2-rv3-beta-47-GTNH.jar was included in the Dev-Pack/Packs client and server zip files.
> However, http://downloads.gtnewhorizons.com/Dev-Pack/Files/mods/ has appliedenergistics2-rv3-beta-44-GTNH.jar.
> Reverting to the ae2 beta-44 file allows for the 2.1.0.7a server to start.

**Comment by Glease** [comment]
The actual problematic mod is MyEssentials-Core. Try replace it with this: http://jenkins.usrv.eu:8080/job/MyEssentials-Core/8/artifact/build/libs/MyEssentials-Core-1.7.10-1.22GTNH-universal.jar or yeet all mods begining with My
