### ISSUE TITLE
Getting non-critical ConcurrentModificationException from AnvilChunkLoader & NBTCompound stack

### ISSUE THREAD

**Issue by TheElan** [GTNewHorizons/GT-New-Horizons-Modpack#7995]
#### Which modpack version are you using?

# 2.1.0.0
#### If in multiplayer; On which server does this happen? 

# private
#### What did you try to do, and what did you expect to happen?
When my server is up for less then 1h (may be quicker) `ConcurrentModificationException` starts to pop up.

#### What happened instead? (Attach screenshots if needed)
I'm getting `ConcurrentModificationException ` as can be seen in a [server_log.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6565198/server_log.txt) and it looks to me that is causes a slight TPS drop when this happens. It's not critical, server runs just fine. 

If needed I can upload server zip to some cloud.

#### What is your GTNH Discord username?
Elan

**Comment by Glease** [comment]
@TheElan Hi, I have updated DebugMod to make it more reliably produce thread dumps. Could you please try this jar: https://github.com/Glease/DebugMod/releases/download/1.0.2/DebugHelper-1.0.2.jar
