### ISSUE TITLE
return from Ender , the HP becomes original

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#7998]
#### Which modpack version are you using?
2.1.0.7a
#

The bonus HP from pam's food disappeared after returning from the Ender

**Comment by Prometheus0000** [comment]
You sure that it isn't the tinkers hearts? It's known they do that.

**Comment by KamenriderZO** [comment]
No not tinker's heart has been reset, but the food bonus.
I was yellow Hp(2 more HP bar) ,after I return from end I'm red Hp now.
But it reset again to yellow when I restart the game.

**Comment by KamenriderZO** [comment]
![XMA(IB% X7$ZS14{FIK_8](https://user-images.githubusercontent.com/77818313/120406184-92a1b700-c34a-11eb-8201-8f0b1a9fad46.png)

I came from end and then I go to Mars to collect my Ores and now I'm coming back to earth.
But the HP is always 10 heart.

**Comment by Prometheus0000** [comment]
@mitchej123

**Comment by Sovereignty89** [comment]
@mitchej123 could [this](https://bugs.mojang.com/browse/MC-29386) be it?

**Comment by mitchej123** [comment]
Looks like this patch on forge might fix it: https://github.com/MinecraftForge/MinecraftForge/pull/4830/files  need to look into it and see if it can be backported via mixins.

**Comment by mitchej123** [comment]
![TheEnd](https://user-images.githubusercontent.com/1894689/147184552-45cde514-6237-4673-a745-0256dddf8c70.gif)

**Comment by KamenriderZO** [comment]
> ![TheEnd](https://user-images.githubusercontent.com/1894689/147184552-45cde514-6237-4673-a745-0256dddf8c70.gif)

WOW is it fixed in dev？

**Comment by mitchej123** [comment]
Still in review https://github.com/GTNewHorizons/Hodgepodge/pull/47  Soon :tm:
