### ISSUE TITLE
Broken ae2 autocrafting recipe when it comes to using IV pump

### ISSUE THREAD

**Issue by wakasagisan** [GTNewHorizons/GT-New-Horizons-Modpack#7999]
#### Which modpack version are you using?
2.1.0.6b
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
After the update from the most recent stable build(2.1.0.0 I think), a big number of autocrafting recipes using machine components(eg. motor, pump) are broken. The voltage tier doesn't seem to play a role, as the broken recipes are inconsistent. However, although some recipes are fixable, some remains broken even with new recipe, and uncraftable even though all the coded materials are present in the ME network. So far I only have found this issue with IV energy hatch only, but it's likely the same with other recipes that would use IV pump(however, superconductor recipe works just fine).
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
I think the cover status NBT removal caused this. Maybe instead of removing that completely, just add a recipe that allows components that had been used as cover to be converted into the crafted one instead, or this is just one unique case of bug regarding the change
#
#### What is your GTNH Discord username?
wakasagisan#6138

**Comment by GTNH-Afx237v7** [comment]
The disassembly NBT was removed, and replaced with fallback-recipes for some components. I don't know the technical details, but that is pretty much the explanation. So you will need to reencode your AE patterns.
However can you give a detail on what is not fixable please?

**Comment by boubou19** [comment]
i suffered this for years, but hopefully it should be the last time someone encounter this because as Afx237v7 said, nbt disassemly data were stripped from items, as disassembly recipes were introduced to replace these data.

**Comment by wakasagisan** [comment]
I tried several times recoding the pattern with a new IV pump, but for IV energy hatch in particular, it’s broken even if I just recode the pattern with a pump that exist in the network. I got it working once, but it’s broken again later for some unknown reason.

**Comment by boubou19** [comment]
that smells like a nbt issue: to help you track that one down, either use `/mt hand` on the different parts of the recipe, and if you can't use `/mt hand` then use `/iih`. It will display some informations about the item held in hand, especially their NBT if they have any.

**Comment by wakasagisan** [comment]
apparently reloading the world fixed this issue for some reason? But I'm afraid it might be broken like it did previously, so I will keep this issue updated.

**Comment by wakasagisan** [comment]
I got this issue once again, this time I didn't change anything from the recipes that worked last time, and it seems to be a problem with IV energy hatch only, the other tiers of energy hatches autocrafting works just fine. Perhaps it might has to do with the fact that IV energy hatch is the only tier that use superconductor(which uses pump) and doesn't use ass line to craft?

**Comment by yukieiji** [comment]
Changing the crafting of components such as Pump to the recipe using Assembler and changing the crafting recipe to something made from it should fix it.
If it is made with normal crafting, it will sometimes go wrong due to NBTs, but if it is made with Assembler, there are no NBTs and it should not happen.

**Comment by wakasagisan** [comment]
> Changing the crafting of components such as Pump to the recipe using Assembler and changing the crafting recipe to something made from it should fix it.
> If it is made with normal crafting, it will sometimes go wrong due to NBTs, but if it is made with Assembler, there are no NBTs and it should not happen.

yet that's exactly what happened. I have recoded 5 times in total, 3 don't work, 2 broken after restart. Could this happen with configs? because I could have made some mistakes while updating my game

**Comment by GTNH-Afx237v7** [comment]
Not aware that a config change has effect on your AE2 patterns...

**Comment by yukieiji** [comment]
>yet that's exactly what happened. I have recoded 5 times in total, 3 don't work, 2 broken after restart. Could this happen with configs? because I could have made some mistakes while updating my game

The Assembler here is the GT Assembler, not the MolecularAssembler.
Probably because it is a Crafting Recipe by MolecularAssembler, the NBT removed by the update may have caused the recipe to go wrong.

**Comment by wakasagisan** [comment]
Ok, I think I have found a solution to this problem but not the cause of this. It seems like restarting the whole client can fix this recipe for some reason.

**Comment by GTNH-Afx237v7** [comment]
Cannot reproduce this... for sure I had to reencode some patterns, but once done everything remains intact...
