### ISSUE TITLE
regulators broken?

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#8000]
#### Which modpack version are you using?
2.1.0.7a whith gregtech Build #1271 (and also updated gt++ and bartowkrs)
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?
nothing, expected my old steup built in 2.1.0.0 that used to work to keep working; it wasn't working, i fiddled whith it a bit, couldn't find anything wrong, tryed whith a new regulator in a different place and i couldn't make it work
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/8298646/120449168-7ecc7400-c38f-11eb-8cdb-65b7596141d2.png)
![image](https://user-images.githubusercontent.com/8298646/120449220-8724af00-c38f-11eb-8e58-f84a8ae648e4.png)
![image](https://user-images.githubusercontent.com/8298646/120449267-91df4400-c38f-11eb-9332-3d9bb63af7bd.png)

(the original setup where i discoveredthe problem was whith a regulator feeding the input bus of an ebf (whith filtering and sroting off, but i don't think that matters when the problem persists whith a chest)
#
#### What do you suggest instead/what changes do you propose?
could this possibly be a bug or i completly forgot how to make these things work?
#
#### What is your GTNH Discord username?
tom#6482

**Comment by Glease** [comment]
> Machine is inactive

I haven't looked at the code, but this does not sound right.

**Comment by GTNH-Afx237v7** [comment]
Still not working in 2.1.1.0pre2:(
