### ISSUE TITLE
Add a cleaning recipe for the bibliocraft clipboard.

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8003]
#### Which modpack version are you using?
2.1.0.0
#

I wanted to clean my very old clipboard because it was full of stuff. So i naïvely tried to put it in the crafting grid to get back a clean version, like with EIO items. Nothing happened obviously, because there is no such recipe. I know it's nothing to craft, but you don't throw away your clipboard if the pages are full, you replace the written pages with empty ones. So adding some paper in the recycling recipe would make sense i guess.

**Comment by GTNH-Afx237v7** [comment]
![grafik](https://user-images.githubusercontent.com/64365566/120758491-338e9e80-c512-11eb-86db-8ef4173337ef.png)
![grafik](https://user-images.githubusercontent.com/64365566/120758530-3ee1ca00-c512-11eb-9d34-4cf21336da81.png)

:D

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/8009
