### ISSUE TITLE
cursed earth keeps spawning mobs in the nether even when you're not in the dimension

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#8013]
#### Which modpack version are you using?
2.1.0.7a
#
#### If in multiplayer; On which server does this happen? 
zeta
#
#### What did you try to do, and what did you expect to happen?
I made a mob farm, and when i left someone on the server complained about tps lag, turns out my mob farm in the nether keep summoning mobs there even if i leave the dimension( there was a chunkloader there, but i removed it, yet it's still spawning)
the problem solves when i go back to the farm, but the number ramp up again when i leave.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/57275066/120874359-b0566280-c57c-11eb-95f0-bc69d9017c93.png)

#
#### What do you suggest instead/what changes do you propose?
Finding a way to solve it or at least a reason why it keeps spawning mobs.

**Comment by Prometheus0000** [comment]
> What do you suggest instead/what changes do you propose?

**Comment by KaneHart** [comment]
I would definitely test this out again on your own instance/server. Mostly for the fact that you need to repeat it first to make sure it's not a bug with chunk loading versus the mod itself.

**Comment by leagris** [comment]
I think I remember when a Nether portal is present, chunk is kept loaded to allow entities to travel through it. If Cursed Earth is placed in same chunk or close to a Nether Portal, chances are it remains chunk-loaded forever.
