### ISSUE TITLE
Cooking for Blockheads - tools don't lose durability

### ISSUE THREAD

**Issue by Logos-Askrson** [GTNewHorizons/GT-New-Horizons-Modpack#8020]
#### Which modpack version are you using?
2.1.07.a
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Using the cooking table with the tool on a tool rack, I crafted Mayo, then checked the soft hammer's durability. I expected to find the durability to decrease, as happens when you craft that item in inventory.
#
#### What happened instead? (Attach screenshots if needed)
The soft hammer's durability did not decrease.
#
#### What do you suggest instead/what changes do you propose?
If this is intended behavior, no change is needed.
If this is not intended behavior, then tools on tool racks should be damaged when used.
#
#### What is your GTNH Discord username?
Logos - Mokou#2981

**Comment by mitchej123** [comment]
It's unintended, but I haven't tracked it down yet.  Hasn't been a super high priority.  Most of Pam's tools don't use durability, the only one that's slightly unbalanced would be anything you can use in place of a juicer since that needs stainless steel to unlock.
