### ISSUE TITLE
add an equivalent recipe in the assembler for the assembling line casing

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8021]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
This recipe has no equivalent in the assembler, so when mass crafted through AE, it's slow to simulate because it needs to check after each craft if it can reuse the tools or if it needs to take another set of tools:
![image](https://user-images.githubusercontent.com/12850933/120940459-b172c580-c71d-11eb-99ac-1c6dea91d047.png)

I suggest to add an equivalent in the assembler, that way it's faster to simulate, impacting less the TPS when masscrafted.

**Comment by GTNH-Afx237v7** [comment]
**note to self:**
something like
GT_Values.RA.addAssemblerRecipe(GT_OreDictUnificator.get(OrePrefixes.plate, Materials.Steel, 4L), GT_OreDictUnificator.get(OrePrefixes.frameGt, Materials.Tungstensteel, 1L), ItemList.Robot_Arm_IV.get(2L), gregtech:gt.blockcasings2:5, 1L, 30, 200); 
not sure about the last part and where to put it yet...

**Comment by Dream-Master** [comment]
yea that recipe is fine.

**Comment by Ethryan** [comment]
Wont it conflict with the solid steel casing recipe?

**Comment by GTNH-Afx237v7** [comment]
Solid steel casing needs 6 plates and steel frame box. I briefly looked at possible conflicts but didn’t see any, but will also take a closer look again.

**Comment by Dream-Master** [comment]
usa a control circuit as always and you dont have conflicts

**Comment by 0lafe** [comment]
if you put the recipe in the assline it shouldn't conflict :D

**Comment by Ethryan** [comment]
1 Plate per input bus right 0lafe

**Comment by GTNH-Afx237v7** [comment]
Bruh...
Not happening

**Comment by 0lafe** [comment]
> 1 Plate per input bus right 0lafe

i mean of course, how else would we make it fun

**Comment by GTNH-Afx237v7** [comment]
:D (steelplate is oredicted)
![grafik](https://user-images.githubusercontent.com/64365566/121484100-30425980-c9cf-11eb-8516-f68ac49904ff.png)

**Comment by Dream-Master** [comment]
@GTNH-Afx237v7 add a control circuit

**Comment by GTNH-Afx237v7** [comment]
There are no recipe conflicts. But I will add one.

**Comment by Dream-Master** [comment]
Not now but for be safe in the future I like to see a circuit in the recipe

**Comment by GTNH-Afx237v7** [comment]
No problem :)
