### ISSUE TITLE
Me Storage Cell bugged

### ISSUE THREAD

**Issue by cLose322** [GTNewHorizons/GT-New-Horizons-Modpack#8022]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I put a circuit programmer  into the  ME Terminal.
(This one)
![Capture9](https://user-images.githubusercontent.com/85527130/121094276-0e8e7a00-c7f7-11eb-865c-ff17e3439557.PNG)

#
#### What happened instead? (Attach screenshots if needed)
Now the ME Storage Cell that is storing the circuit programmer is bugged (?), and the terminal is not showing the items from inside:
![Capture5](https://user-images.githubusercontent.com/85527130/121093607-ef431d00-c7f5-11eb-9de3-6f4abb0f4d58.PNG)
![Capture6](https://user-images.githubusercontent.com/85527130/121093613-f36f3a80-c7f5-11eb-83eb-2f9b2b0c1ebe.PNG)
You can see that another storage cell is working just fine, even if it holds more items, and if i put the storages together, the terminal is displaying nothing as well:
![Capture7](https://user-images.githubusercontent.com/85527130/121093695-0f72dc00-c7f6-11eb-8c69-00431d50536e.PNG)
![Capture8](https://user-images.githubusercontent.com/85527130/121093700-113c9f80-c7f6-11eb-829c-d14cc2c61db6.PNG)
(Other terminals does not work as well).
#
#### What do you suggest instead/what changes do you propose?
Can i somehow get my items back from the storage cell or delete the circuit programmer from config file?
#
#### What is your GTNH Discord username?
cLose ;o

**Comment by repo-alt** [comment]
You may try to make a subnetwork with a storage cell on some chest and IO port, and dump the cell contents in that subnetwork

**Comment by cLose322** [comment]
> You may try to make a subnetwork with a storage cell on some chest and IO port, and dump the cell contents in that subnetwork

I didn't know you can do that, it worked, thank you :)
