### ISSUE TITLE
Pollution visual effects are interdimensional

### ISSUE THREAD

**Issue by TheBrochacho** [GTNewHorizons/GT-New-Horizons-Modpack#8023]
#### Which modpack version are you using?
2.1.0.7a

Pollution visual effects get rendered at the same spot in different dimensions.
![2021-06-07_16 52 58](https://user-images.githubusercontent.com/16054364/121101626-0a3f6e00-c7b1-11eb-8c2f-32ee8c7694f8.png)
![2021-06-07_16 53 25](https://user-images.githubusercontent.com/16054364/121101632-0ca1c800-c7b1-11eb-8c01-10a8e973dfd4.png)

#### What do you suggest instead/what changes do you propose?
Disable Pollution.

**Comment by Prometheus0000** [comment]
New way to grief people found!

**Comment by basdxz** [comment]
Disable Pollution.

**Comment by botn365** [comment]
Disable Pollution.

**Comment by mitchej123** [comment]
Disable Pollution

**Comment by KaneHart** [comment]
Disabled Pollution

**Comment by KaneHart** [comment]
Just a clairfaction, I stated the pollution is disabled not to disable it!
