### ISSUE TITLE
Spelling error in botdustries, hydrazine should be renamed Hydrazine

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#8024]
#### Which modpack version are you using?
2.1.0.7a
#
See title. Pls fix @botn365
Just to be clear, the h should be H.

**Comment by repo-alt** [comment]
W/o the comment title looks cryptic

**Comment by Prometheus0000** [comment]
Is there a way to not see the title?

**Comment by repo-alt** [comment]
Not when open, but in the #github-issues
