### ISSUE TITLE
ExtraCells2 fluid terminal water cell bug

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#8028]
#### Which modpack version are you using?
2106b
#
#### If in multiplayer; On which server does this happen? 
private srv
#
#### What did you try to do, and what did you expect to happen?
Insert a cell content into the ae2. When the cell content is water the empty cell is not given back.
It works with other fluids what i tested, so far only water acting like this
demo: https://www.youtube.com/watch?v=49ML_YcYXDQ
#
#### What happened instead? (Attach screenshots if needed)
Empty cell got voided
#
#### What do you suggest instead/what changes do you propose?
It should give back the empty cell
#
#### What is your GTNH Discord username?
szajkop

**Comment by kubasz** [comment]
This is fixed in ec2 by <https://github.com/GTNewHorizons/ExtraCells2/pull/51> now
