### ISSUE TITLE
Bees Should Be Affected By Pollution

### ISSUE THREAD

**Issue by TheBrochacho** [GTNewHorizons/GT-New-Horizons-Modpack#8030]
#### Which modpack version are you using?
2.1.0.7a
#
#### What did you try to do, and what did you expect to happen?
I found this short video 
[![Watch the video](https://img.youtube.com/vi/BONmJ7b0x74/maxresdefault.jpg)](https://www.youtube.com/watch?v=BONmJ7b0x74)
Currently on Zeta, I have my alvearies in the vicinity of my EBFs. 
![2021-06-09_09 50 13](https://user-images.githubusercontent.com/16054364/121396397-302b5680-c908-11eb-8049-fb42cfca99be.png)
This area is subjected to high amounts of pollution from running the EBFs frequently.
#
#### What do you suggest instead/what changes do you propose?
I think that bee work rates should be penalized in areas with large amounts of pollution. Also pollution should make pristine bees have a chance to become ignoble due to the impurities in the air.

I would also suggest that pollution affect the rate at which butterflies pollinate trees since I'm sure they are affected by pollution as well.

**Comment by shitstainlord** [comment]
Yes please. Give people more reasons to turn off pollution by default

**Comment by Cinobi** [comment]
If u want to add a debuff to bees from pollution, why not to make it both way?
like "natural" bees like food generation bees gets drawback, but "unnatural" bees like materials generators gets boost? and viceversa 

Hate this idea overall, but no more _jsutnerfs_ please xD
