### ISSUE TITLE
Good circuit board quest trade

### ISSUE THREAD

**Issue by dcirusc36** [GTNewHorizons/GT-New-Horizons-Modpack#8031]
#### Which modpack version are you using?  2.1.0.7a

#
#### If in multiplayer; On which server does this happen?  N/A

#
#### What did you try to do, and what did you expect to happen?  I tried to purchase good circuit boards in coins coins coins quest tab i expected to trade 5 coin "The technician 10" for 4 good circuit boards.

#
#### What happened instead? (Attach screenshots if needed) with multiple coins in inventory more than required (which is 5) it doesn't detect any coins to trade for the circuit boards.

#
#### What do you suggest instead/what changes do you propose? suggest that the quest is checked it has the right requirements to make the trade to purchase the circuit boards.

#

**Comment by Prometheus0000** [comment]
Are you sure it's the right color of coin?

**Comment by dcirusc36** [comment]
the colour of coin is green in the quest requirement the type of coin i am using is green. notice i said it requires "the technician 10" x5 which is green coins.

**Comment by Prometheus0000** [comment]
You did press the submit button while not being in edit mode?
And it's not that it's completed, but you haven't claimed the rewards?

**Comment by dcirusc36** [comment]
i havn't used edit mode don't how to. The quest is completed from another day yes it doesn't say i unclaimed rewards. as you can see on my hotbar i have 26 coins slot 6.
![questbug](https://user-images.githubusercontent.com/50635197/121456272-b6de4300-c99d-11eb-8311-8588242f2891.png)

**Comment by Prometheus0000** [comment]
It might have the quest repeat thing set wrong.

**Comment by Prometheus0000** [comment]
This works fine for me. Are you sure you meet the quest requirements? I changed some of the coins quests to match with the others, you need Tier 3 (HV) completed.

**Comment by dcirusc36** [comment]
Hey Prometheus0000 , i updated my pack to GTNewHorizonsClient-1.7.10-2.1.1.0.pre2 , the quest now works im at hv with ev unlocked. i can buy the circuits again so i dunno must be an issue with 2.1.0.7a version im just glad it works, this can be closed if needed.
