### ISSUE TITLE
Ender fluid link cover color coding doesn't make sense

### ISSUE THREAD

**Issue by shitstainlord** [GTNewHorizons/GT-New-Horizons-Modpack#8033]
#### Which modpack version are you using?
2.1.0.7a

#### What did you try to do, and what did you expect to happen?
I looked up the hex8 color code for green to link ender fluid link covers as such:

![image](https://user-images.githubusercontent.com/50236595/121499539-27a94d80-c9e6-11eb-830f-672d8baeb1e2.png)

#### What happened instead? (Attach screenshots if needed)

![image](https://user-images.githubusercontent.com/50236595/121499189-d1d4a580-c9e5-11eb-867b-61b660b9dd51.png)

Instead I get checkered blue board on the screen which doesn't make any sense

Edit: Messed up the screenshot

![image](https://user-images.githubusercontent.com/50236595/121501386-dd28d080-c9e7-11eb-9ce5-def3f04bfeda.png)

It still never gives out the expected color. Another example; FFFF00FF is the code for yellow

![image](https://user-images.githubusercontent.com/50236595/121501712-26792000-c9e8-11eb-8cfa-4afc6f3eeba6.png)

But you get pink instead

#### What do you suggest instead/what changes do you propose?

Change it to normal 6 digit hex code (Who even uses hex8?) And hopefully the display on the box will show the correct color.

I also suggest that there could be two additional buttons on the gui to copy and paste color codes quickly

**Comment by potato4444** [comment]
Going purely off your screenshots it would seem that the colour being displayed is because the hex number is being interpreted in the format #AARRGGBB (the checkering represent transparency)
