### ISSUE TITLE
IC2 Harvester Recipe bugged

### ISSUE THREAD

**Issue by Aggadahr** [GTNewHorizons/GT-New-Horizons-Modpack#8035]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Tried crafting the IC2 Harvester

![javaw_2021-06-10_15-59-56](https://user-images.githubusercontent.com/46688121/121538241-ea07ed00-ca04-11eb-8350-7391c9a0a3fe.png)

The shown Recipe doesnt work. The Harvester appears in the Product slot but you cant take it. (so far i tried crafting terminal, vanilla crafting table, Forestry Worktable, Tinkers Construct Crafting Station and Ofanix)

HOWEVER if you replace the components with the HV Version (old Recipe, not shown in NEI) it shows an empty product slot but you can take the Harvester by clicking the empty slot
#
#### What is your GTNH Discord username?
Shadii

**Comment by repo-alt** [comment]
Weird, on Zeta it works just fine

**Comment by boubou19** [comment]
there is a mismatch between some client packs and server in 2.1.0.0 afaik only this recipe is affected. It's fixed in dev
