### ISSUE TITLE
Duplicated Receipe for Clay dust causing Clay block to give 9 dust instead of 2

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#8036]
#### Which modpack version are you using?
2.1.0.7a
#
#### If in multiplayer; On which server does this happen? 
Stone Legion
#
#### What did you try to do, and what did you expect to happen?
4 clay -> clay block -> 2 clay dust
matter is conserved and the universe is happy
#
#### What happened instead? (Attach screenshots if needed)
4 clay -> clay block -> 9 clay dust
![image](https://user-images.githubusercontent.com/49487505/121555336-805c0300-ca45-11eb-89ae-b3aa9b6e1893.png)
![image](https://user-images.githubusercontent.com/49487505/121555397-8eaa1f00-ca45-11eb-8f0f-4ffe43e3a66b.png)

matter is not conserved and the universe is not happy
#
#### What do you suggest instead/what changes do you propose?
remove the extra receipe... dunno how tf it got there 
#
#### What is your GTNH Discord username?
Hebi

**Comment by tommy307507** [comment]
![image](https://user-images.githubusercontent.com/49487505/121557339-41c74800-ca47-11eb-8b2f-7197ba7c06c3.png)

Also this reverse receipe exist... someone told me its some oredict stuff messing up... not sure if this is been reported before but no one I know talked about it

**Comment by Prometheus0000** [comment]
Looks like this is another autogenerated one that assumes block=9 items.

**Comment by Prometheus0000** [comment]
Same problem as #7956

**Comment by Prometheus0000** [comment]
The maceration part has to do with the reverse recipe line
```
RA.addPulveriserRecipe(aStack, new ItemStack[]{GT_OreDictUnificator.getDust(aData.mMaterial), GT_OreDictUnificator.getDust(aData.getByProduct(0)), GT_OreDictUnificator.getDust(aData.getByProduct(1)), GT_OreDictUnificator.getDust(aData.getByProduct(2))}, null, aData.mMaterial.mMaterial==Materials.Marble ? 1 : (int) Math.max(16, tAmount / M), 4, tHide);
```
in the GT_RecipeRegistrator class, but I couldn't figure out how to change it to fix it.
