### ISSUE TITLE
Apiarist Database is not craftable

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#8038]
#### Which modpack version are you using?
2.1.0.7a
#
The bee analyzer can't be set in the slot
see the picture below
![RGBUFXYI5TQPGLIXZ}`PZ1Z](https://user-images.githubusercontent.com/77818313/121745658-efe4f780-cb04-11eb-9667-5980b1d51c6d.png)
The analyzer is clean, new made.I can't put it in the slot. But the database recipe said so

**Comment by Prometheus0000** [comment]
This thing again? You're sure you checked the recipe and it's exactly the same?

**Comment by KamenriderZO** [comment]
I'sure . I made another Lepidopterist database justnow.
But this one can't even set in the slot

**Comment by KaneHart** [comment]
When you said clean you just made it? I would try this recipe to see if it makes any diff then again throw it in:
![image](https://user-images.githubusercontent.com/425853/121749362-89e27b00-cad8-11eb-9daa-7a066390b702.png)

**Comment by KamenriderZO** [comment]
I'have already tried both. doesn't work
nether a new crafted one,nor put the old one in the worktable to craft another time.

**Comment by KamenriderZO** [comment]
It seems like the slot doesn't know this item

**Comment by Prometheus0000** [comment]
? @KamenriderZO
![image](https://user-images.githubusercontent.com/8517039/121757186-ba331500-caea-11eb-87d7-6e912f72a2ed.png)

**Comment by Prometheus0000** [comment]
Check all the items again. Note that there's two types of molten redstone, the TiC one is not what you want if you used that.

**Comment by KamenriderZO** [comment]
Why?I can't place the Beealyzer 4864 in that middle slot.

**Comment by Prometheus0000** [comment]
ID changes per world, only meta stays the same.

**Comment by KamenriderZO** [comment]
![image](https://user-images.githubusercontent.com/77818313/121757591-5c202500-cb1e-11eb-88a4-830bf4cf848b.png)

4 diamond screws 6956:27500
1 Emerald plate 6856:17501
1 Nanoprocessor 6958:32082
2 gold casing 6957:18086
1 diamond plate 6956:17500
moltenredstone from GT fluid extractor

and beealyzer 4864

I don't know what's wrong...

**Comment by Prometheus0000** [comment]
Did you make sure to delete the script folder when updating, and not just replace it?

This is the script recipe in the extra bees zs file (the formatting got weird, but the numbers are the same)
// --- Apiarist Database
mods.forestry.Carpenter.addRecipe(<ExtraBees:dictionary>, [[<gregtech:gt.metaitem.01:27500>, <gregtech:gt.metaitem.01:17501>, <gregtech:gt.metaitem.01:27500>],
														  [<ore:itemCasingGold>, <ore:circuitAdvanced>, <ore:itemCasingGold>], 
                                                          [<gregtech:gt.metaitem.01:27500>, <gregtech:gt.metaitem.01:17500>, <gregtech:gt.metaitem.01:27500>]], <liquid:molten.redstone> * 1440, 60, <Forestry:beealyzer:*>);
// -
recipes.addShapeless(<ExtraBees:dictionary>, [<ExtraBees:dictionary>]);

Note the liquid:molten.redstone, if you put yours into a universal cell, it should be either molten.redstone or redstone.molten.
![image](https://user-images.githubusercontent.com/8517039/121757812-c61fd680-caec-11eb-856b-235eedcfa162.png)
![image](https://user-images.githubusercontent.com/8517039/121757816-ce781180-caec-11eb-9ecf-8a8bf5914897.png)
Though the one from GT fluid extractor should be the right one.

**Comment by KamenriderZO** [comment]
No i never changed script, I always grab the latest build of GT++ and GT5unofficial from jenkin.And I just replace the mod

**Comment by KamenriderZO** [comment]
![image](https://user-images.githubusercontent.com/77818313/121758079-2da34980-cb20-11eb-8b21-c1a8097d8157.png)
The screen is placeable , even there is no such recipe.
But the beealyzer isn't placeable.
I think its not an issue of correct recipe??

**Comment by Prometheus0000** [comment]
Because it's in another recipe. Your version for some reason doesn't recognize the beealyzer as part of a recipe. I assume the recipe shows up in NEI properly? I'd say do a clean reinstall once the next dev comes out this weekend if looking at the script recipe doesn't help.

**Comment by KamenriderZO** [comment]
OK thinks,i will try that way.maybe my game is in chaos
