### ISSUE TITLE
Describe usage of Multiblock Machine Blueprint in quest text

### ISSUE THREAD

**Issue by ddejong42** [GTNewHorizons/GT-New-Horizons-Modpack#8045]
#### Which modpack version are you using?
2.1.0.7a
#

#
#### What did you try to do, and what did you expect to happen?
Clicked on a pyrolyse oven controller with the TecTech Multiblock Machine Blueprint.  I expected an easy to understand diagram of what went where.
#
#### What happened instead? (Attach screenshots if needed)
It displayed the necessary information, but not in a way that made sense to me.  I ended up having to look up an old video to find the layout, then after having built one for reference I could reverse engineer what the blueprint was trying to tell me.
#
#### What do you suggest instead/what changes do you propose?
One of the quests should describe how to interpret what it shows you, probably the one for the EBF as that seems to be the first one that uses this new format.  Something like: "To see how the multiblock is supposed to be built, place the controller block and right click on it with a Multiblock Machine Blueprint.  It will display the mandatory blocks in the world as a small seethrough version of the block, as well as light blue blocks indicating where air blocks and blocks where you have choices go.  The chat text is a key to which blocks are valid choices; 0 for blocks with no dots, 1 for blocks with one dot on each face, and so on."
#
#### What is your GTNH Discord username?
PeculiarLynx

**Comment by Prometheus0000** [comment]
It is explained, in UV. I'm waiting for the rest of the MBs to be changed before modifying quests.

**Comment by iouter** [comment]
This should be done before 2110...... or just revert the commit of the bart (at least keep the structure introduction in the tooltip)

**Comment by Prometheus0000** [comment]
Structurelib is unlikely to be done in the next week, much less the porting of the MBs.

It's not hard to understand. Use the thing, see the text. Though I do want the structure text, it's broken in BW.

**Comment by iouter** [comment]
as far as I know, structurelib has to wait until 2120.

for beginners, the biggest problem is #7364 . my biggest lesson in using blueprints is must to raise the controller block at first. at least temporarily modify quests to explain the blueprint before the 2110 release.

I really hope that those structure introductions will come back.
