### ISSUE TITLE
debug card impacted by the lua version

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8048]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I tried to set the NBT of a block, but with Lua 5.3, it's impossible to set an NBT if the edited values are numbers. Switching back to Lua 5.2 make the card work again, so looks like the new number system in Lua 5.3 messed up something.
![image](https://user-images.githubusercontent.com/12850933/121805576-13ff2080-cc4c-11eb-80af-9e2d6bd5029c.png)

**Comment by repo-alt** [comment]
https://github.com/MightyPirates/OpenComputers/issues/2448
I tried to fix that with ASM, but fixing the function pointed out by @payonel is not enough, it breaks further in JNLua, and I was unable to dig to the real reason

**Comment by boubou19** [comment]
well it's not a big issue anyways: putting back lua 5.2 is an easy workaround. But they shouldn't have put 5.3 as default. Might be worth considering putting back 5.2 as default if it's unfixable.
