### ISSUE TITLE
Part of steam pipes not inputting into machines

### ISSUE THREAD

**Issue by oliverstr0** [GTNewHorizons/GT-New-Horizons-Modpack#8049]
Version 2.1.0..0

When i connect machines in a certain part of my steam lines even if the steam pipe is full no steam goes into the machines i expect for steam to actually go in the machines

Basically one time i logged in and one half of my steam pipes stopped inputting into **all** machines (the pipes are full) i have tried all methods including replacing the pipes but it seems even when replaced a part of them just refuse to input into machines ill provide latest and those other logs can provide world
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6644372/latest.log)
[2021-06-13-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6644375/2021-06-13-3.log)

Discord User : oliverstr#8820

**Comment by boubou19** [comment]
can you post a picture of your setup? Also do you try to input the steam on the output side?

**Comment by oliverstr0** [comment]
> can you post a picture of your setup? Also do you try to input the steam on the output side?
Yeah adding pics now but i dont have output blocked i think a picture will explain better 

![](https://cdn.discordapp.com/attachments/853680356057022494/853683437059571712/unknown.png)

![](https://cdn.discordapp.com/attachments/853680356057022494/853683517120577566/unknown.png)

**Comment by oliverstr0** [comment]
Basically in that pic you can see the pipe is full and connected to the machine yet the machine is nearly empty and its not filling it only fills when you replace the pipe for a bit

**Comment by boubou19** [comment]
what's the "raw oil" thingy on the tricorder report?

**Comment by oliverstr0** [comment]
> what's the "raw oil" thingy on the tricorder report?

oh thats probably just raw oil underground in the chunk

**Comment by botn365** [comment]
why is there water in that pipe

**Comment by oliverstr0** [comment]
> why is there water in that pipe

wdym water? thats steam? im using steam machines rn

**Comment by oliverstr0** [comment]
oh wait...

**Comment by Prometheus0000** [comment]
You really should've asked for help on discord first.
