### ISSUE TITLE
Ender Conduit cannot extract fluids from T.F.F.T Multi I/O Hatch

### ISSUE THREAD

**Issue by albus12138** [GTNewHorizons/GT-New-Horizons-Modpack#8053]
#### Which modpack version are you using?
2.1.0.0 with KekzTech 0.5.5
#
#### If in multiplayer; On which server does this happen? 
MP/SP
#
#### What did you try to do, and what did you expect to happen?
I want to extract all fluids from TFFT to supertanks with ender conduit.
#
#### What happened instead? (Attach screenshots if needed)
Only the fluid in #0 slot can be extracted. But ME storage bus can access all the fluids. (Both mentioned in the TFFT quest)
#
#### What do you suggest instead/what changes do you propose?
Fix it
#
#### What is your GTNH Discord username?
r4phael#8493

**Comment by Prometheus0000** [comment]
Update.

**Comment by albus12138** [comment]
In 2.1.0.0, KekzTech's version is 0.5.2. 
I have updated to the lastest build(0.5.5) on http://jenkins.usrv.eu:8080/job/KekzTech/. Also try to build from source code by myself. Both of them didn't work. BTW, wrench and screwdriver are unavailable too.
Do I have to update other mods?

**Comment by Prometheus0000** [comment]
This is a mod _pack_, you update the _pack_. There's lots of mods that rely on other mods being a specific version.

**Comment by albus12138** [comment]
I think this problem is caused by kekztech itself. It should be solved by update itself (like witchery's NPE problem). Anyway, I will update to 2.1.0.7a and test it.

**Comment by mitchej123** [comment]
While what you wrote is technically accurate, the mods are developed as a part of the pack and little attention is paid to intermod dependencies.  Upgrading kektech might require an updated GT5u, which might require <insert random other dependencies> to be updated.  Updating individual mods is therefore not supported :)

**Comment by albus12138** [comment]
Not work in 2.1.0.7a.  : (
Ender Conduit
![2021-06-15_11 23 08](https://user-images.githubusercontent.com/9742081/121987996-230cdc80-cdcc-11eb-8df7-ff98103e37e4.png)
ME Fluid Terminal
![2021-06-15_11 24 37](https://user-images.githubusercontent.com/9742081/121988056-49327c80-cdcc-11eb-8038-28b1973b6064.png)

**Comment by Prometheus0000** [comment]
@botn365 Is the one that's supposed to have fixed it.

**Comment by madmacf** [comment]
Still not working as of 2.1.2.0 :-(
