### ISSUE TITLE
[RFC] - Buffing PA Efficiency Boosts in preparation for GT++ removal

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#8058]
At present, in a processing array, UEV+ machines start to receive a 4x efficiency boost in processing arrays ([Code](https://github.com/GTNewHorizons/GT5-Unofficial/blob/e93fefc3737a133153817e8536be0319d4e68ef8/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_ProcessingArray.java#L181)).
Since we are planning on removing A2, it might be appropriate to buff processing arrays in order to incentivise players to use them and to bridge the gap. Perhaps starting at LuV machines, we could have a 1.33x bonus or something similar. This is a thread to discuss the balance of such a change.

**Comment by mitchej123** [comment]
I vote no. The PA is an ugly gameplay hack instead of actual new content.  We'll be adding in Obama with actual balanced replacements.  The PA needs to fade into oblivion.

**Comment by Houstonruss** [comment]
The whole point was to nae-nae the overpowered mod, not replace it with over powered machines.

**Comment by Houstonruss** [comment]
And as far as liscences are concerned... Too little too late. The fact that ++ got updated again isn't just a mistake, its a tragedy.

**Comment by johnch18** [comment]
> I vote no. The PA is an ugly gameplay hack instead of actual new content. We'll be adding in Obama with actual balanced replacements. The PA needs to fade into oblivion.

> The whole point was to nae-nae the overpowered mod, not replace it with over powered machines.

My vision is for a stopgap, to sort of wean players off of GT++. Project Obama is indeterminate in terms of when it will be ready, so I don't think this is a long-term replacement.

**Comment by mitchej123** [comment]
Just say "NO" to the PA

**Comment by Houstonruss** [comment]
> > I vote no. The PA is an ugly gameplay hack instead of actual new content. We'll be adding in Obama with actual balanced replacements. The PA needs to fade into oblivion.
> 
> > The whole point was to nae-nae the overpowered mod, not replace it with over powered machines.
> 
> My vision is for a stopgap, to sort of wean players off of GT++. Project Obama is indeterminate in terms of when it will be ready, so I don't think this is a long-term replacement.

The proposed stopgap was an interim update that let you trade in your ++ blocks for obama. The value here is you don't lose your machines entirely.

**Comment by mitchej123** [comment]
> And as far as liscences are concerned... Too little too late. The fact that ++ got updated again isn't just a mistake, its a tragedy.

We've only removed stuff from it :-D

**Comment by johnch18** [comment]
> > And as far as liscences are concerned... Too little too late. The fact that ++ got updated again isn't just a mistake, its a tragedy.
> 
> We've only removed stuff from it :-D

Don't bully me mitch-kun :'(
