### ISSUE TITLE
Rocket/fuel quests need updating

### ISSUE THREAD

**Issue by hohounk** [GTNewHorizons/GT-New-Horizons-Modpack#8059]
#### Which modpack version are you using?
 2.1.0.7a
#
#### If in multiplayer; On which server does this happen? 
singleplayer
# 
#### What did you try to do, and what did you expect to happen?
attempted to make RP1 for T2 rocket.
# 
#### What happened instead? (Attach screenshots if needed)
Found out from discord that T2 rocket works fine with nitrodiesel and that quests are outdated
#
#### What do you suggest instead/what changes do you propose?
Update rocket fuel and rocket quests to be up to date in terms of what tier of rocket requires what fuel
E.g this is in T2 rocket quest. It says it requires RP-1 while people on discord said nitrodiesele is fine
![image](https://user-images.githubusercontent.com/4471281/122112820-f12a6300-ce29-11eb-9d8c-7f3724508766.png). They told me that next tier of fuel would be lmp-103s but I'm not seeing that in questbook so probably the fuel quests require updates as well.

#
#### What is your GTNH Discord username?
Hoho

**Comment by ahmetsad** [comment]
Cetane boosted diesel works for T2 rocket in the latest update.
