### ISSUE TITLE
High Energy flow circuit only have circuit assembler recipe

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8060]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I wanted to make a circuit assembly line (CAL) for the high energy flow circuit (added by the core mod, and used in the recipe of the active transformer from tectech, it's only use case), but the high energy flow circuit only has a recipe in the circuit assembler. I suggest to add a recipe for it in the CAL, as opencomputer's microchips are also added to the CAL.

**Comment by iouter** [comment]
No one would use this recipe, bart removed all the benefits of the CAL. It's garbage, non-recyclable garbage.

**Comment by Prometheus0000** [comment]
?

**Comment by boubou19** [comment]
Well i dont really care if there is a benefit to it, i just want to remove all my circuit assemblers in my cleanroom, and this is the last recipe that prevents me to do so. IMO there is still an advantage to have it in the CAL: the bulk crafting.

**Comment by tommmmmmmmm** [comment]
if you only want to get rid of the cleanroom, you can put the circuit assembler inside a PA

**Comment by Prometheus0000** [comment]
PAs will be killed eventually.

**Comment by boubou19** [comment]
I already have enough PA like that, plus the CAL is the legit multiblock alternative to the circuit assembler, so why not add a recipe for it?

**Comment by ScriptedPiky** [comment]
I think the problem with the CAL is that you need the original circuit to slice, then you can put it inside the CAL to multiply the recipe by 16x. And if I recall, the slicing of the circuit tries to keep the original data of the circuit that was sliced? Not sure how the process ultimately works, but maybe something can be fiddled with
