### ISSUE TITLE
2.1.1.0 pre1 not opening (prompting to remove a mod)

### ISSUE THREAD

**Issue by tommmmmmmmm** [GTNewHorizons/GT-New-Horizons-Modpack#8062]
#### Which modpack version are you using?
GTNewHorizonsClient-1.7.10-2.1.1.0.pre1
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
update the game and try out new patch
i also tryed making a new instance in mmc to check if it could have been caused by some old files i might had forgotten to remove
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/8298646/122158574-3328c880-ce6d-11eb-96d7-31ccb12444b8.png)

#
#### What do you suggest instead/what changes do you propose?
remove ![image](https://user-images.githubusercontent.com/8298646/122158776-7b47eb00-ce6d-11eb-9828-8c6c9fd70b4f.png)  (solved the problem)
#
#### What is your GTNH Discord username?
tom#6482

**Comment by Dream-Master** [comment]
Ah ok will fix

**Comment by Dream-Master** [comment]
fixed in pre2

**Comment by Dream-Master** [comment]
http://downloads.gtnewhorizons.com/Dev-Pack/Pack/Client/GTNewHorizonsClient-1.7.10-2.1.1.0.pre2.zip
