### ISSUE TITLE
DataReader quest is missing?

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#8065]
#### Which modpack version are you using?
2.1.1.0Pre2
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
I looked for the DataReader quest.
#
#### What happened instead? (Attach screenshots if needed)
Not found. It was existing in v2.1.0.0, so it may have been deleted by mistake.

・in v2.1.0.0
![2021-06-16_21 06 25](https://user-images.githubusercontent.com/40425798/122216046-e97cc400-cee6-11eb-835d-20fb267e9618.png)

・in v2.1.1.0Pre2
![2021-06-16_21 07 09](https://user-images.githubusercontent.com/40425798/122215980-d538c700-cee6-11eb-8c08-c86be14f1e87.png)

#
#### What do you suggest instead/what changes do you propose?
Add it.
#
#### What is your GTNH Discord username?
yukieiji

**Comment by Prometheus0000** [comment]
It was removed on purpose because it has no value any more, you can see the recipes in NEI without holding them first.
