### ISSUE TITLE
Server startup ( 2.1.1.0 )

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#8066]
#### Which modpack version are you using?
GTNewHorizonsServer-1.7.10-2.1.1.0.pre1
#
#### If in multiplayer; On which server does this happen? 
server 
#
#### What did you try to do, and what did you expect to happen?
Server startup
#
#### What happened instead? (Attach screenshots if needed)
crash
#
#### What do you suggest instead/what changes do you propose?
There are duplicate mods in the "mods" folder. Some are disabled. 
You need to remove the on or off and remove one of the kekztech versions.
The second crash was due to 
MyEssentials-Core
MyPermissions
MyTown2
MyTownWebAuth

Crashes https://dropmefiles.net/ru/Qy4MWB
#
#### What is your GTNH Discord username?
Кетцаль#0802

**Comment by Dream-Master** [comment]
ok will fix

**Comment by Dream-Master** [comment]
ok kekztech dup remove but what is with the other mods?

**Comment by Prometheus0000** [comment]
They shouldn't be there?

**Comment by Dream-Master** [comment]
why ?

**Comment by Prometheus0000** [comment]
Aren't they plugins for the official servers? And not for other servers, so it crashes. Ask boubou if you want to know what they do.

**Comment by Dream-Master** [comment]
ok i disabled this mod

**Comment by boubou19** [comment]
the culprit here in the 2nd crash is MyEssentials-Core, but it was fixed with its latest version (MyEssentials-Core-1.7.10-1.22GTNH). Also, MyTown2 is a pain to get it work on a server, because by default it lacks some required libs. I suggest disabling the combo MyEssentials-Core + MyTown2 + MyTown2WebAuth. Server admins can always try to set it up if they wish.

**Comment by KaneHart** [comment]
I recommend dreams to always keep the my anything disabled by default. Still include it but disabled. I'm sure most people who run their own private server don't use it anyways.
