### ISSUE TITLE
The machine and components can still be disassembled

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#8067]
#### Which modpack version are you using?
2.1.1.0Pre2
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
Disassembling motors, etc.
#
#### What happened instead? (Attach screenshots if needed)
disassemble it.
![2021-06-16_21 17 12](https://user-images.githubusercontent.com/40425798/122217280-3ad98300-cee8-11eb-8986-e87fa9679676.png)
![2021-06-16_20 46 50](https://user-images.githubusercontent.com/40425798/122217297-3dd47380-cee8-11eb-824a-00fdaf504d0b.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it
#
#### What is your GTNH Discord username?
yukieiji

**Comment by boubou19** [comment]
It's intended: now you can disassemble items, but there are no more crafting nbt on the items.

**Comment by yukieiji** [comment]
So the nbt was just removed, but the disassembly is allowed?

**Comment by boubou19** [comment]
yes. That way the little amount of players can still use the disassembler, and the nbt removal makes the shift clicking on the ? button in NEI work with GT components. It'll break once again the AE2 patterns, but it should be the last time.

**Comment by yukieiji** [comment]
Thank you, boubou19. This ticket is closed.
