### ISSUE TITLE
Strong redstone mode is not indicated on GT machine tooltips

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8068]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
I had one of my PA controllers refusing to stack with the others i had in my inventory. So i though it was due to crafting NBT, so i put both the controller and the stack of controllers in the name remover with no circuit to remove all it can. But the controller refused to stack even after being through the name remover. So i did a `/mt hand` to see the NBT:
![image](https://user-images.githubusercontent.com/12850933/122296987-5a2ddb80-cefb-11eb-8fb1-221add51d089.png)

Could be cool if we had an indication in the tooltip similar to what we have for the covers:
![image](https://user-images.githubusercontent.com/12850933/122297246-99f4c300-cefb-11eb-9ca9-79df6b593b1c.png)

**Comment by Prometheus0000** [comment]
Or if that was stripped on wrenching.
