### ISSUE TITLE
Item/Type filter recipe change?

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#8069]
#### Which modpack version are you using?
2.1.0.7
#
Type:
Currently all tiers use an HV circuit, making it MV at minimum. However, the conveyor belt and hull both are the same tier as the block.

Item:
Same as before, but all tiers use an LV circuit.

Should we also make the circuit the same tier as the block, or leave it as it is?

**Comment by Glease** [comment]
Leave it as is. No reason to scale it. The feature set of machine (speed, recipe map, etc) does not change beyond being able to pass through higher tier of power, which has totally nothing to do with circuits.

**Comment by TrainerSnow** [comment]
I personally found it weird that they required circuits anyway, why not have them require 2 Conveyors instead of 1 Conveyor and 1 Circuit? (Kind of one for Output, one for Input).
