### ISSUE TITLE
Bug in the drawing of the last tablets ( Thaumcraft4Tweaks-1.3.2 )

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#8072]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Server
#
#### What did you try to do, and what did you expect to happen?
open Thaumonomicon with maximum screen size ( 2560x 1440 )
#
#### What happened instead? (Attach screenshots if needed)
If you open Thaumonomicon in a large window, it does not have the last 4 tabs, if you then open in a small window (as it was before the improvement), everything is drawn. If after the small open in the big window, then there will appear missing

![image](https://user-images.githubusercontent.com/17906427/122372486-605aa100-cf69-11eb-9219-f331c20e0831.png)
![image](https://user-images.githubusercontent.com/17906427/122373692-5c7b4e80-cf6a-11eb-9825-be0bcf680a46.png)

#

#### What is your GTNH Discord username?
Кетцаль#0802

**Comment by Glease** [comment]
Fixed in 1.3.3 of said mod. Get it from [curseforge](https://www.curseforge.com/minecraft/mc-mods/tc4tweaks/files/3354720)
