### ISSUE TITLE
[GT5u] - pollution config change

### ISSUE THREAD

**Issue by GTNH-Afx237v7** [GTNewHorizons/GT-New-Horizons-Modpack#8073]
#### Which modpack version are you using?
2.1.1.0 pre2
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Upgrade from 2.1.0.0 to 2.1.1.0 which includes the config change `enable.pollution=false`
#
#### What happened instead? (Attach screenshots if needed)
As expected, pollution is no longer generated, pollution clearing blocks are disabled. However, any existant pollution level cannot be dealt with, as aforementioned blocks are disabled and the command /gt pollution <amount> no longer works.
Therefore, unless you have eliminated all pollution before upgrading to the lastet version that includes this config change, your pollution will be with you indefinitely.
#
#### What do you suggest instead/what changes do you propose?
? Out of ideas on this one
Maybe still allow the command to be used ? 
Not an issue for those that have control over the config, however anyone playing on an official server has no influence over this.
As the command alters pollution per chunk, it seems to be a lot of work for server admins to change each chunk (if that is even an option)?
#
#### What is your GTNH Discord username?
Afx237v7

**Comment by boubou19** [comment]
well, as long as the effects of the pollution are disabled as well (potion effects, landscape effects and visual effects) it does not really matter if the pollution is stuck at insane levels. Now if those are still happening, then it's a major issue.

**Comment by GTNH-Afx237v7** [comment]
The visual effects remain, have not tested the debuff/landscape effects.

**Comment by boubou19** [comment]
looks like the pollution renderer is not checking at all if the pollution is enabled or not.

**Comment by GTNH-Afx237v7** [comment]
Debuff effects do not occur, I am at 2.4M gibbl without any armor and nothing is happening. 
Decay effect is being tested, but it seems that no decay is taking place.
Debug pollution generator from TecTech has no effect, as an attempt to get rid of pollution.
