### ISSUE TITLE
Glass tubes are sometimes hard to see with default textures

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8078]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
it's very hard to see them in some GUI of the game. Here are some examples:
in AE crafting:
![image](https://user-images.githubusercontent.com/12850933/122523634-8b033300-d017-11eb-8570-60ce3f911ca2.png)
in the vacuum tube recipe:
![image](https://user-images.githubusercontent.com/12850933/122523757-a8d09800-d017-11eb-991d-94df277645a4.png)

I would have done something about it myself, but i'm bad at texturing work.

**Comment by Glease** [comment]
Now take a break and look at your window IRL. Do you see anything? If yes you probably need to clean up your window.

Jokes aside, it can probably use a skyblue-ish tint to make it stands out a bit. That's also what vanilla glass has been doing.

**Comment by Ethryan** [comment]
Give me to later today and i think i can come up with a transparent slightly blue interior to make it easier to see.

**Comment by Prometheus0000** [comment]
Just don't make it too close to the reinforced glass.

**Comment by Ethryan** [comment]
![12](https://user-images.githubusercontent.com/3237986/122639221-fcff7900-d0f8-11eb-91f9-f7b2d3605d70.png)
![13](https://user-images.githubusercontent.com/3237986/122639222-012b9680-d0f9-11eb-9069-d20109ad6e68.png)
![23](https://user-images.githubusercontent.com/3237986/122639224-04268700-d0f9-11eb-8f86-9788ea159dc1.png)
Thoughts?

**Comment by Glease** [comment]
It's slightly hard to distinguish them, but that might just be me, though now you indeed can notice its presence.

![screen](https://user-images.githubusercontent.com/4586901/122640343-ac584200-d131-11eb-8dec-7191d78b1acd.png)

**Comment by Ethryan** [comment]
![23](https://user-images.githubusercontent.com/3237986/122641341-eeb75a00-d104-11eb-9db0-56d09c799599.png)
Small darker border to differentiate it

**Comment by Glease** [comment]
Much better now.

![screen](https://user-images.githubusercontent.com/4586901/122641520-71a5d800-d138-11eb-8ed5-f570d562557e.png)

**Comment by KaneHart** [comment]
Looks great thank you.

**Comment by Prometheus0000** [comment]
It looks really similar to the reinforced glass one now. Was there a need to make it the same color? Making it non-opaque would have been enough, wouldn't it?
