### ISSUE TITLE
IC2 nuclear reactor item insert bug

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#8084]
#### Which modpack version are you using?
2106b
#
#### If in multiplayer; On which server does this happen? 
private srv
#
#### What did you try to do, and what did you expect to happen?
automatize ic2 nukes with enderio. The automatization is done by an autocrafting ae2 interface which supplies quad thorium fuel. the depleted fuels are getting recycled then put back in the same interface (and then sucked in by ae2)
The item moving is done by enderio item conduits. Extract filter is set on all reactors to only extract depleted cells and inserting is also enabled to replace the empty places with new fuel.
#
#### What happened instead? (Attach screenshots if needed)
It happens that my ae2 system is not fast enough to take the items from the interface and the enderio conduit will extract it and put it inside an already full reactor
![kép](https://user-images.githubusercontent.com/7230430/122656355-11279280-d15a-11eb-880d-57df47633dd1.png)
The dust is literraly in the reactor and not just NEI overflowing.
(for sure i can put a filter on the interface extract side to not take crap in so its not gamebreaking)
Also, i can take the dust out by hand and even place it back.
#
#### What do you suggest instead/what changes do you propose?
The item insertion should be disabled when the reactor is full with control elements
#
#### What is your GTNH Discord username?
szajkop

**Comment by GlodBlock** [comment]
it will be hard to fix because IC2 is closed source.

**Comment by Prometheus0000** [comment]
Then you wouldn't be able to put cells into a fluid reactor which is what that slot is for.

**Comment by Szajkop** [comment]
Well after testing it on 2110 i can still put in the dust
![kép](https://user-images.githubusercontent.com/7230430/124333825-9452da80-db95-11eb-88cb-022a7bd924d7.png)
or my hammer
![kép](https://user-images.githubusercontent.com/7230430/124333842-a03e9c80-db95-11eb-9e67-c126fdf25bc0.png)
