### ISSUE TITLE
Getting "Fatal Error Occured this connection is terminated " while opening Copterpack

### ISSUE THREAD

**Issue by k3nw4y** [GTNewHorizons/GT-New-Horizons-Modpack#8085]
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Craftersland
#
#### What did you try to do, and what did you expect to happen?
when opening the copterpack GUI , that is shift rightclicking or pressing the keu to open it, it kicks me from server, same happening with single player
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/46229190/122755722-0af8f980-d2b3-11eb-9a2c-07b34b5edad9.png)

#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
aio.imnotsure.tech#7664

**Comment by boubou19** [comment]
do you have any log? because without them, we will not able to trackdown what happens.

**Comment by k3nw4y** [comment]
https://paste.ee/p/XMjMs

There is nothing in the logs, im using Java 8 openJDK,and my system details:
![image](https://user-images.githubusercontent.com/46229190/122776818-11926b80-d2c9-11eb-86ef-47c3f940a2a4.png)

**Comment by k3nw4y** [comment]
https://paste.ee/p/STy3l

today i managed to get an error trying on second time

**Comment by k3nw4y** [comment]
seems fixed on 2.1.1.0
