### ISSUE TITLE
galacticraft fuel loader is not loaded fuel

### ISSUE THREAD

**Issue by SiroLove** [GTNewHorizons/GT-New-Horizons-Modpack#8086]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
singleplayer
#
#### What did you try to do, and what did you expect to happen?

Attempted to load fuel to locket, expected to load fuel in locket.

#
#### What happened instead? (Attach screenshots if needed)

'Fuel is too low quality!' to be loaded when fuel is loaded into a rocket.
Experiments were conducted in all directions, but they were all the same results.

![2021-06-22_10 17 04](https://user-images.githubusercontent.com/86272473/122848261-26601500-d344-11eb-9984-8f0126061d4c.png)

#
#### What do you suggest instead/what changes do you propose?

How can I solve this problem?

#

**Comment by Prometheus0000** [comment]
Which fuel, which rocket?

**Comment by Prometheus0000** [comment]
Also, look at the quests for the valid ones.

**Comment by SiroLove** [comment]
diesel fuel of gregtech and tier1 rocket of galacticraft.

screenshots is experiment world. All the related quests were opened survivor world

**Comment by Prometheus0000** [comment]
Diesel hasn't been valid for a long long time. Read the quests.

**Comment by SiroLove** [comment]
oh thank you
It's because I copied it from an old YouTube video.
So 'Cetane-boosted diesel cell' is the only fuel that goes in now?

**Comment by Prometheus0000** [comment]
For T1 and T2

**Comment by SiroLove** [comment]
Thank you so much.
