### ISSUE TITLE
the mutiblock machine doesn't work

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#8088]
#### Which modpack version are you using?
2.1.1.0
#
Vacuum Freezer ,EBF doesn't work after update to 2.1.1.0 release
They just eat the materials and can't restart

**Comment by boubou19** [comment]
From where did you downloaded the update? because the Technic launcher seems to have some outdated mods, so please use the multimc release instead. Also do you play on a server? if yes, do you use any other server type than forge? (thermos/crucible/ultramine)

**Comment by KamenriderZO** [comment]
from technic launcher

**Comment by boubou19** [comment]
that looks like the fixed bug due to the port of the ebf structure check to tectech's api. It's only taking 1A from the hatch so it fails the recipe. Please use the multimc release instead for now, the time for Dream to fix this.

**Comment by KamenriderZO** [comment]
OK thanks

**Comment by boubou19** [comment]
please tell us if it corrected your issue.

**Comment by yukieiji** [comment]
Maybe it's because TecTech version is old for techniclauncher? #8087

**Comment by KamenriderZO** [comment]
I down it from discord link from Dream Master now.
There is no more such problem.
