### ISSUE TITLE
Update Chisel Tooltips for Materials that are not in World Gen.

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#8091]
#### Which modpack version are you using?
2.1.1.0

```
worldgen {
    # Amount of andesite to generate in the world; use 0 for none.
    I:andesiteAmount=0

    # Amount of diorite to generate in the world; use 0 for none.
    I:dioriteAmount=0

    # Amount of granite to generate in the world; use 0 for none.
    I:graniteAmount=0
```

All 3 of these have the following tooltip: 
"Generates in Your World"

https://github.com/GTNewHorizons/Chisel/blob/1.7/release/src/main/java/team/chisel/Features.java#L649
https://github.com/GTNewHorizons/Chisel/blob/1.7/release/src/main/java/team/chisel/Features.java#L140
https://github.com/GTNewHorizons/Chisel/blob/1.7/release/src/main/java/team/chisel/Features.java#L1067

If you want you can remove it via the Lang files instead.

**Comment by Dream-Master** [comment]
@KaneHart make a pr i merge it!
