### ISSUE TITLE
Electric prospector scanner single chunk scan give cryptic names

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/GT-New-Horizons-Modpack#8092]
#### Which modpack version are you using?
Zeta-one
#
#### If in multiplayer; On which server does this happen? 
Zeta live
#
#### What did you try to do, and what did you expect to happen?
Trying to use Electric prospector scanner at moon
#
#### What happened instead? (Attach screenshots if needed)
Instead of list of found ores in chat i got this(see screen attached)
#
#### What do you suggest instead/what changes do you propose?
fix   =D
#
#### What is your GTNH Discord username?
Cinobi

![2021-06-22_19 39 37](https://user-images.githubusercontent.com/25028786/122968683-7a92e580-d394-11eb-8a0e-04cf2aa071c0.png)

**Comment by Prometheus0000** [comment]
How did you get this item? It seems more like it's the non-electric one? Dd you try using it in the air, or in a different mode?

**Comment by Cinobi** [comment]
> 
> 
> How did you get this item? It seems more like it's the non-electric one? Dd you try using it in the air, or in a different mode?

No idea why u even rised such a quesition, but here u are - perfectly crafter LuV scanner - same error, and, as u see, it even shows  some small ores in ores only mode
![2021-06-25_20 11 08](https://user-images.githubusercontent.com/25028786/123461278-9515ca80-d5f1-11eb-8897-5ff9f421c5b1.png)

**Comment by Prometheus0000** [comment]
I didn't think it had a right-click on the ground mode.

> and, as u see, it even shows some small ores in ores only mode

Why is this bad? Is there a separate small ore mode?

**Comment by Glease** [comment]
Click ground gives ore status in text form. Click air gives GUI. It always has been like this. 

The ore shown are not small ores. If you do turn on small ore mode, the map should be almost completely filled with colored dots. They are scattered around the vein due to how GT generates the vein.

**Comment by Prometheus0000** [comment]
I think the problems is that it's not giving the right names

**Comment by Glease** [comment]
Yeah that's valid points.

**Comment by Cinobi** [comment]
> 
> 
> Click ground gives ore status in text form. Click air gives GUI. It always has been like this.
> 
> 

![2021-06-25_21 32 37](https://user-images.githubusercontent.com/25028786/123470335-eecfc200-d5fc-11eb-9601-668e152e2df0.png)
=D

**Comment by Prometheus0000** [comment]
Ores mode shows no small ores for me if you're saying that's another bug? Only ores and small ores mode does.

**Comment by Cinobi** [comment]
> 
> 
> Ores mode shows no small ores for me if you're saying that's another bug? Only ores and small ores mode does.

free to join zeta, i'l give u scanner and see by urself

**Comment by Prometheus0000** [comment]
Looks fine to me?
![image](https://user-images.githubusercontent.com/8517039/123480425-59b6d400-d5d0-11eb-934a-7fffad49813b.png)
Also, not whitelisted, and too lazy to do so. Maybe the server has something wrong with it.

**Comment by Szajkop** [comment]
The same happened on my server too.
Version: 2110
Right clicking the ground gives unusable returns in chat.
Also the non electric version behaves the same

The popup gui shows small ores even when the filter (shift + right click) set to only ores 

Both worked correctly on the 2106b version in the new release smthing broke them

**Comment by AtomicGrog** [comment]
A workaround of sorts. You can translate the names by searching the GregTech.lang file in the root minecraft folder if it helps anyone till theres a fix.
