### ISSUE TITLE
On Technic launcher multiblocks broke with new update

### ISSUE THREAD

**Issue by oliverstr0** [GTNewHorizons/GT-New-Horizons-Modpack#8093]
#### Which modpack version are you using?
2.1.1.0
#
#### What did you try to do, and what did you expect to happen?
Being able to open GUI and there being power drain
#
#### What happened instead? (Attach screenshots if needed)
I only tried the EBF since its the only multiblock i have but i couldnt open GUI (hatches and buses worked fine though) and when smelting items there was absolutely no power drain i tried multiple 
#
#### What do you suggest instead/what changes do you propose?
That the multiblocks are fixed asap
#
#### What is your GTNH Discord username?
oliverstr#8820

**Comment by Prometheus0000** [comment]
duplicatex2, #8088 #8087

**Comment by Dream-Master** [comment]
and fixed. I updated the two wrong mods on technic
