### ISSUE TITLE
Native ore cluster not processing for GT ore variations in thaumatorium

### ISSUE THREAD

**Issue by PolkageistHS** [GTNewHorizons/GT-New-Horizons-Modpack#8095]
#### Which modpack version are you using?
2.1.1.0 release / Technic
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
Tried putting oreRedgraniteTungstate, oreMarbleIron, oreNetherrackNetherQuartz, and oreEndstoneCobaltite in the thaumatorium to get a native cluster, expecting it to pull essentia to create the native cluster.  I have the research completed in the thaumnomnomicon and can view it in the Thaumcraft NEI plugin.  At first I thought it might be because of the changes to tungstate, but the marble iron ore doesn't work either.  I was able to get a native cluster from "normal" (read: stone) ore with both copper and cobaltite, but any variations such as endstone, red granite, or marble don't seem to work.  
#
#### What happened instead? (Attach screenshots if needed)
Nothing happened.  No essentia was pulled from either the essentia provider or jars.  I tried cycling through the up and down arrows to see if that did anything but nope.  
![image](https://user-images.githubusercontent.com/9247381/123052501-bd19e980-d3b7-11eb-8c52-c30f9459c323.png)
#
#### What do you suggest instead/what changes do you propose?
Fix it? ¯\_(ツ)_/¯ tbh I don't know if it's been broken for a while or not, I've never made native clusters before.  
#
#### What is your GTNH Discord username?
Pao

**Comment by Alastors** [comment]
I will say, it works in the crucible, it just doesn't in the thaumotorium

**Comment by Alastors** [comment]
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8267

I made a note here too if it helps at all

**Comment by Alastors** [comment]
<img width="561" alt="Screen Shot 2021-07-19 at 9 54 59 PM" src="https://user-images.githubusercontent.com/78517796/126250406-61fecddc-163c-457e-961e-749534c297d4.png">
but I can confirm it does work in the crucible
