### ISSUE TITLE
Output Bus (ME) doesn't work with gt++ multis

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8098]
#### Which modpack version are you using?
2.1.1..0

#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What did you try to do, and what did you expect to happen?
Used the new Output Bus (ME) on gt++ multis, expected it to work normally

#
#### What happened instead? (Attach screenshots if needed)
Multi doesn't want to start, is it possible that it can't see "storage space" into the new output bus?
GT++ doesn't start if there's not enough room for output
Right now tested Industrial Extrusion Machine and Large Processing Factory and both refuse to start

#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by Glease** [comment]
The associated PR will allow you to ignore all output space checking by right clicking the controller with a soldering tool.

**Comment by Sphyix** [comment]
@Glease is this gonna remove the automatic safe of the GT++ machines to stop when output is full? For example what happens if the ME turns off?
That'll make it still useless cause I'd have to remake a lot of setups to avoid voiding stuff

**Comment by Glease** [comment]
ME powering down while your automation is working is like a really rare situation, no? It's impossible to know if your ME network can accept all the outputs as long as there are more than one stack of output anyway (technical limitation of AE2 API).

**Comment by boubou19** [comment]
keep in mind that GT multis have the same AE limitations, so it's not bothering that much.

**Comment by Sphyix** [comment]
> keep in mind that GT multis have the same AE limitations, so it's not bothering that much.

yes but GT automation is done with the voiding "issue" already into consideration, so in all setups there's redstone to stop it, that's not the case on GT++ and some automations that just output to the AE could void stuff this way
Anyway it's fine if nothing can be done about it, it's true that it's kinda rare that an AE turns off
