### ISSUE TITLE
Packager keeps eating the dust schematic

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#8100]
#### Which modpack version are you using?
2110
#
#### If in multiplayer; On which server does this happen? 
private srv
#
#### What did you try to do, and what did you expect to happen?
Compressing tiny pile of dusts with the Advanced Packager II (HV)

#
#### What happened instead? (Attach screenshots if needed)

After 1 operation the schematic dissapears
https://user-images.githubusercontent.com/7230430/123109604-a7e69e80-d43b-11eb-91c0-00c216ba4e51.mp4

#
#### What do you suggest instead/what changes do you propose?
Schema should be persistent
#
#### What is your GTNH Discord username?
Szajkop

**Comment by Szajkop** [comment]
Thanks for the fix, i downloaded the new build from jenkins.
Tested, works fine now

**Comment by combusterf** [comment]
This isn't strictly limited to GT++, but notoriously includes gypsum which you get from regular ore processing, so you might want to explicitly filter that out as a temporary workaround.

The other problem group for which this happens is anything originally from Ender IO.

**Comment by Glease** [comment]
> 
> 
> This isn't strictly limited to GT++, but notoriously includes gypsum which you get from regular ore processing, so you might want to explicitly filter that out as a temporary workaround.
> 
> The other problem group for which this happens is anything originally from Ender IO.

It is tagged as GT++ because it's a bug in GT++, not because it affects GT++ dusts only.

**Comment by elements-interviews** [comment]
And the devs weren't the target audience for that comment 😉

**Comment by combusterf** [comment]
And the devs weren't the target audience for that comment 😉
