### ISSUE TITLE
The needs maintenance cover doesn't make sense

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#8103]
#### Which modpack version are you using?
2.1.1.0
#
The grammar/text makes these incomprehensible.
![image](https://user-images.githubusercontent.com/8517039/123170774-eafb3e80-d448-11eb-8545-2dd29bea97b8.png)
![image](https://user-images.githubusercontent.com/8517039/123170796-efbff280-d448-11eb-95c2-7e61bebef1ac.png)
Rotor=turbine? rotor needs maint=replacement? low/high accuracy mod = ? And why at 79% and 99% durability? Is it supposed to be less than 20% and at 0%?

**Comment by Erik4556** [comment]
Commenting because these fields are still labeled incorrectly in 2.6.0. Current label vs apparent actual behavior is as follow:
"Rotor < 80%" -> Rotor < 20%
"Rotor < 100%" -> Rotor = 0%

This applies to both the Needs Maintenance Cover 7195:32748 and the Wireless Needs Maintenance Cover 7196:32583
