### ISSUE TITLE
[RFC]add a GT cover “item filter”

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#8105]
sometimes. "item filter" block is not enough, so can you add a "item filter" like GT6?

my idea is it can filters for 1-3 items, whitelist and blacklist mode, and the "item filter" assembled with the conveyor module can also extract the set 1-3 items.

**Comment by Glease** [comment]
Cover cannot support more than 1 item to filter due to technical reasons.

**Comment by Glease** [comment]
https://github.com/GTNewHorizons/GT5-Unofficial/pull/574
