### ISSUE TITLE
Crashin with OutOfBounds error with entities

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#8108]
#### Which modpack version are you using?
New Horizons-2.1.0.0QF1-1.7.10.zip

#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
Just Explore and the game crashes, this happened 2 time
#
#### What happened instead? (Attach screenshots if needed)
Game suddenly closed out of world and crashed
#
#### What do you suggest instead/what changes do you propose?
im not sure, Though, I will state here that the only modifcations that I made was adding FriendlyFire, Ender Utilites and one other Tech Mod HBM's Nuclear tech ver 1.0.27-3899 (Can be located [here](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/releases/tag/1.0.27X3899))
#
#### What is your GTNH Discord username?
Na

Crash Reports
[crash-2021-06-24_17.01.47-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6712207/crash-2021-06-24_17.01.47-client.txt)
[crash-2021-06-24_15.55.55-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6712208/crash-2021-06-24_15.55.55-client.txt)
(note: both Reports have the same error)

**Comment by SteamDoge9000** [comment]
I have come down to a concluson and found out that it might be some bad iteraction with between HBM and Galacticraft (or at least the one that was modfied by your end)

**Comment by Prometheus0000** [comment]
It's not our problem if a mod you add causes crashes.

**Comment by FavoritoHJS** [comment]
Seems to be a problem with negative potion IDs, as the new effects got allocated above ID 127. Please close as Won't Fix.

**Comment by SteamDoge9000** [comment]
alright then, but I do have a queston though, how do I remove a mod form the pack that is something like Bugtorch but it keeps on resinstalling it

I found a fix to this issue from the other end but something about its mixin is not liking Potion ID helper and Im trying to remove that mod but the pack keeps on resintalling it

**Comment by Prometheus0000** [comment]
You can disable the individual mixins/asms in the config files. Your game may work in unexpected ways if you remove the mod completely. And one of the ASM mods relies on the other.

There's some kind of thing that redownloads stuff. Maybe search on discord, I think it was deploader or something? On the current version it should run once, then disable. PS: you're way out of date, the new version is released.

**Comment by SteamDoge9000** [comment]
can you give me a link to the newest version then please?

and if that dosent work, how would I go about to disable the mixin?

**Comment by Prometheus0000** [comment]
Go to announcements in the discord channel
