### ISSUE TITLE
Outdated Quest

### ISSUE THREAD

**Issue by JoshX9706** [GTNewHorizons/GT-New-Horizons-Modpack#8110]
#### Which modpack version are you using?
2.1.0.0
#
####
The Quest Tier 1 Heavy Duty Plates has Stainless Steel Bolts as a requirement despite the recipe using Stainless Steel Fluid
![image](https://user-images.githubusercontent.com/47550807/123363920-5c5dee80-d528-11eb-8340-9bc96e46444d.png)

#
#### What is your GTNH Discord username?
JoshX9706

**Comment by Prometheus0000** [comment]
Invalid, update

**Comment by JoshX9706** [comment]
Stainless Steel Bolts still a reqirement in 2.1.0.0
![image](https://user-images.githubusercontent.com/47550807/123366295-d2fceb00-d52c-11eb-8ec8-49efe99d5a10.png)
