### ISSUE TITLE
Tungsten trioxide + carbon dust = 2 hot tungsten ingots recipe doesn't work with volcanus

### ISSUE THREAD

**Issue by stlchase40** [GTNewHorizons/GT-New-Horizons-Modpack#8112]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Put items in and expected the hot tungsten.
#
#### What happened instead? (Attach screenshots if needed)
It just stay there
#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
stlchase40
![2021-06-25_10 38 26](https://user-images.githubusercontent.com/86484890/123450344-412fc500-d5a2-11eb-82c2-4ff5533f4e2e.png)

**Comment by GlodBlock** [comment]
i am sure that you don't use output hatch in volcanus.
volcanus and other gt++ mulits won't work if there is no space for all output products.

**Comment by stlchase40** [comment]
> 
> 
> i am sure that you don't use output hatch in volcanus.
> volcanus and other gt++ mulits won't work if there is no space for all output products.

yup that was the problem.... great...

**Comment by GlodBlock** [comment]
that feature will be optional on next update.
see https://github.com/GTNewHorizons/GTPP/pull/7
