### ISSUE TITLE
Power station doesn't accept Tectech's IV 4A dynamo hatch

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#8114]
#### Which modpack version are you using?
2.1.1.0 release
#
I just repalce the EV dynamo hatch(buffered) with IV 4A dynamo hatch from Tectech
The controller said: incomplete structure.
![1~}J657H_3RM$7ET458V41U](https://user-images.githubusercontent.com/77818313/123462936-34838f00-d5eb-11eb-86e8-6bd3261f8ddd.png)
![R2$@RACEFL_EED4DQIC%F H](https://user-images.githubusercontent.com/77818313/123462938-35b4bc00-d5eb-11eb-857a-a835329b85df.png)

**Comment by GTNH-Afx237v7** [comment]
Did you upgrade the Redox cells from EV to IV, too? Cell tier and hatch tier must match.

**Comment by KamenriderZO** [comment]
ah ,so the Tier hatch must be <= redox cells?
OK i got it
