### ISSUE TITLE
Object Submission Station does not allow selecting consume:yes tasks

### ISSUE THREAD

**Issue by kevinkjt2000** [GTNewHorizons/GT-New-Horizons-Modpack#8123]
#### Which modpack version are you using?
2.1.0.0
2.1.1.0

#
#### If in multiplayer; On which server does this happen?
private server I share with friends

#
#### What did you try to do, and what did you expect to happen?
I selected the vaccuum tube quest task to submit 30 yellow technician tokens, and I expected that clicking the green checkmark to confirm this would lock in my choice.

#
#### What happened instead? (Attach screenshots if needed)
After the green checkmark, I exited the interface with the done button. When I open the interface again, it has forgotten what I selected! Which seems to make it impossible to insert any items into it.

#
#### What do you suggest instead/what changes do you propose?
I did some further investigation and realized that this submission system only forgets my decision whenever the task is a consume:yes type. Every other task it seems to remember just fine.

Additionally, this is a coin reward that I have claimed before, but I waited for the cooldown to refresh before trying it in the OSS.

#
#### What is your GTNH Discord username?
kevinkjt2000#3258

**Comment by boubou19** [comment]
can you try again on 2.1.1.0 please?

**Comment by kevinkjt2000** [comment]
Was better questing updated? Where's the changelog for 2.1.1.0?

**Comment by boubou19** [comment]
changelog will come when Dream will have finished to make the listing of all things that have changed. But BQ got some optimizations, even if i did not see stuff related to OSS in the commit history from my very quick lookup. Anyways, you should update to 2.1.1.0 Because tons of stuff have improved. It makes the ticket management easier if we know it's still a thing on 2.1.1.0.

**Comment by kevinkjt2000** [comment]
Fair enough. I'll do the update. I just wanted to scroll through the changelog while waiting on downloads, backups, and moving files around.

**Comment by kevinkjt2000** [comment]
I did the update, ran `bq_admin default load` in the server console, and now the OSS doesn't show "Vaccuum Tubes" anymore. In fact, all of the orange quests don't show in the OSS; only the red quests show. Should I wait for the quest to be available again (there's no timeout when I hover over the quest), or is the quest broken somehow?

![image](https://user-images.githubusercontent.com/4098674/123523811-da86d600-d68b-11eb-9d29-14da42c6fef0.png)

**Comment by kevinkjt2000** [comment]
I tried one of the red quests to see if I can still reproduce my original issue. Clicking the arrow several times, "Seed bags", click the green checkmark, click done, re-open the OSS GUI, and behold it has forgotten it. Seems like this is still a bug in 2.1.1.0 (I'll add that version to my original post)

**Comment by combusterf** [comment]
I can manage to lock in "Endless evolution" on 2.1.1.0 Delta (a different repeatable consume:yes) and have it remember it both before and after completing the quest the first time, but the end result of not being able to pipe in items is the same for me.
