### ISSUE TITLE
Sand duplication

### ISSUE THREAD

**Issue by Zaideron** [GTNewHorizons/GT-New-Horizons-Modpack#8124]
#### Which modpack version are you using?
Gregtech New Horizons
#
#### If in multiplayer; On which server does this happen? 
Eta 
#
#### What did you try to do, and what did you expect to happen?
When breaking a piece of gravel with a hammer, I was expecting to give me 1 piece of sand
#
#### What happened instead? (Attach screenshots if needed)
Instead of 1 piece of sand, it gave me 1 piece of sand and 1 piece of gravel, thus creating an infinite amount of sand
#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
Zaideron

**Comment by boubou19** [comment]
modpack version: 2.1.1.0, see #5240

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/IguanaTweaksTConstruct/pull/12
