### ISSUE TITLE
Quests not detecting/completing 

### ISSUE THREAD

**Issue by keithc463** [GTNewHorizons/GT-New-Horizons-Modpack#8125]
#### Which modpack version are you using?
2.1.0.0QF1
#
#### If in multiplayer; On which server does this happen? 
Private hosted server
#
#### What did you try to do, and what did you expect to happen?
Joined a party and crafted 3 flint, expected it to complete a quest. 
#
#### What happened instead? (Attach screenshots if needed)
It did complete  for the friend I joined party of but not for me and now I can't complete it at all without force completing 
#
#### What do you suggest instead/what changes do you propose?
Have it completed for me :D.
#
#### What is your GTNH Discord username?
keithc463#5672

**Comment by boubou19** [comment]
can you try to update and see if it's still a thing in 2.1.1.0? some optimizations were done in BQ for parties.

**Comment by keithc463** [comment]
2.1.0.0 is showing as latest version for me in curseforge, can't see a 2.1.1.0 is there a way to grab it?

**Comment by Glease** [comment]
Get it here: http://downloads.gtnewhorizons.com/ClientPacks/

**Comment by boubou19** [comment]
you can also download it by using the technic launcher by using the latest version of the pack (not the current recommanded one, which will download the 2.1.0.0, Dream will change the 2.1.1.0 to recommanded very soon)

**Comment by keithc463** [comment]
Still bugged unfortunately

**Comment by Prometheus0000** [comment]
Make sure you're not in edit mode. It works for me, but I haven't tried party stuff. Also, you're sure it's not a consume task, and that you both were caught up?

**Comment by keithc463** [comment]
100% sure, not in edit mode, thing is the quest completes for the party leader(only two of us) if I do the quest(or get the requirements at least) but I can't physically complete the quest myself

**Comment by Szajkop** [comment]
You have to start the server in online mode for the player UUIDs to work. BQ uses theese values for syncing. We had the same issue on my server.
Other fix is to download the "UUID offline" mod and install it on the server.

**Comment by Glease** [comment]
So it's more like a offline mode problem. I believe there is nothing we can do here.

**Comment by Prometheus0000** [comment]
How can a server be offline? You need to be online to connect to it? Or is this one of those 'avoiding auth server' type things? Which we don't support.

**Comment by Glease** [comment]
Pretty sure he is talking about the later one.

**Comment by keithc463** [comment]
Nope we were just using a LAN hosted server with hamaichi, eventually just
bought a hosted server as couldn't get it to work
