### ISSUE TITLE
Add a config for the AE2 "search string persistent" change

### ISSUE THREAD

**Issue by mudspaw** [GTNewHorizons/GT-New-Horizons-Modpack#8126]
#### Which modpack version are you using?
2.1.1.0 on Technic
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
I attempted to quickly clear the AE2 terminal search bar by pressing ESC and opening the terminal again.
#
#### What happened instead? (Attach screenshots if needed)
Unfortunately, this no longer clears the search bar, something I am very used to when rapidly searching for items in my system.
#
#### What do you suggest instead/what changes do you propose?
I was hoping that the change to make AE2 searches persistent could have a client side config added to it to disable this feature.
https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/commit/9485097604f8c511c2d54d86a9a83b25be86f07e
#
#### What is your GTNH Discord username?
mudspaw

**Comment by repo-alt** [comment]
right click the search bar to clear it

**Comment by mudspaw** [comment]
While I am aware of the ability to right click the search bar to clear the terminal, I am still very used to clearing the terminal by pressing esc, something I have been doing in modpacks even before playing GTNH. This does not really address the issue I have with this change. There are also plenty of other people similarly disgruntled by the change.

![2bd0303ebc9b209d7f381aa1814dedc6](https://user-images.githubusercontent.com/76231301/123532931-8f96ae00-d6df-11eb-874b-76e950f8c106.png)
![06267fe2f6799655ad8ce3c5a1f43d00](https://user-images.githubusercontent.com/76231301/123532933-92919e80-d6df-11eb-95dd-43c4af64ae32.png)
![92945a5e5bdefad5090c67fd906ea17e](https://user-images.githubusercontent.com/76231301/123532937-99201600-d6df-11eb-8071-77a19988cdd2.png)
![b432e35f68158abe87220421c4223afd](https://user-images.githubusercontent.com/76231301/123532939-9d4c3380-d6df-11eb-870c-31f3fe8b14c3.png)
![dea1296f6ec45666b5a083ab57f1b1ab](https://user-images.githubusercontent.com/76231301/123532945-a3daab00-d6df-11eb-8057-fabb8dc71983.png)
![f69773afe6c5b6e5b19a4f4a026dcb2d](https://user-images.githubusercontent.com/76231301/123532949-a63d0500-d6df-11eb-9439-c399d568c5ae.png)

This is why I feel a config to allow the player to disable this change is warranted.

**Comment by Szajkop** [comment]
For me i like the search keep feature. It makes some tasks faster. And you always can clear it with a click.

However if i use the wireless crafting terminal it will clear the searchbar on closing.

Some unified approach would be cool to have similar behavior in all terminals. For example to change the terminal mode to keep the search or clear on closing. (I recall there is a feature something like that but its not worked as expected for me)

**Comment by repo-alt** [comment]
Probably all those good people _don't know_ you can clear the search bar. But I'll look if the client-side config is possible
