### ISSUE TITLE
Sliced LV tier circuits makes with error name

### ISSUE THREAD

**Issue by Alsarus** [GTNewHorizons/GT-New-Horizons-Modpack#8128]
#### Which modpack version are you using?
2110
#
#### If in multiplayer; On which server does this happen? 
local mp
#
#### What did you try to do, and what did you expect to happen?
Try to sliced LV circuits(integrated logic circuit and micropocessor) and make imprint for circuit assembly line. 
#
#### What happened instead? (Attach screenshots if needed)
http://puu.sh/HRWcT/1d727ac7c4.jpg
http://puu.sh/HRWa6/6dff7cf284.jpg
Sliced makes with error name. Imprint makes with error name and this imprint not working in circuit assembly line.
#
#### What do you suggest instead/what changes do you propose?
fix
#
#### What is your GTNH Discord username?
Alsarus

**Comment by Alsarus** [comment]
Make sliced circuits in cutting factory. They make with error name - http://puu.sh/HRWlG/56d09da93c.jpg
Try make in single machine - it make correctly - http://puu.sh/HRWkV/83f61b8007.jpg
So it bug cutting factory machine.

**Comment by Skiftcha** [comment]
it is noted in quest
![image](https://user-images.githubusercontent.com/2212585/123524158-2019c200-d6d1-11eb-99ee-5d47adb7ebd2.png)

**Comment by Alsarus** [comment]
Yep. Sorry. Closed.
