### ISSUE TITLE
Quicklime recycling issue in acetic acid to calcium acetate to acetone recipes 

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#8131]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
My epoxid line broke after the upgrade.

#
#### What happened instead? (Attach screenshots if needed)
It turns out that the mixer recipe for small piles has been removed: 
![image](https://user-images.githubusercontent.com/8459776/123539030-fc3d9700-d737-11eb-8488-aeace6f28547.png)
It still works with full-sized dusts so there's no apparent nerf involved, but it's a rather annoying and pointless change since the distillery step immediately afterwards still returns small piles of quicklime and these can't be recycled anymore without adding an extra machine.

#
#### What do you suggest instead/what changes do you propose?
Restore the removed mixer recipe, dividing the base one by 4 that would be:
CaO small pile + circuit 1 + 500L acetic acid -> 250L calcium acetate
16 EU/t 1A LV 1 sec / 20 ticks

Edit: as discussed below, the other alternative is to make the distillery output 1 normal pile of CaO (and optionally scale the recipes accordingly) to remove the small piles from the system altogether

#
#### What is your GTNH Discord username?
Combuster

**Comment by boubou19** [comment]
it's not a bug, it's intended: it's a decision to remove as much as possible small and tiny pile usages from the game.

**Comment by combusterf** [comment]
So then the distillery is out of line in terms of outputting 3 small piles...

You can have that output one normal pile - which does mean getting perfect recycling of quicklime which is a buff. Otherwise you'd have to do some number juggling to make a lossy distillery recipe fit the input/output slot sizes without breaking all the other calcium acetate-related recipes.

**Comment by Prometheus0000** [comment]
So, to solve this there's a couple solutions:
1) Ignore it. Lame.
2) Make the distillery tank larger (currently 1000L/1000L) and multiply the recipe by 4, and similarly for the carbon ones. This is easy to do.
3) Try to add a chance based thing like the centrifuge or macerator has, so you'd have a 75% of getting a full dust. I'm not sure I can do this.
4) Make it a DT-only recipe. I don't think people would like this.

Honestly I don't know why it has a 1000L tank to begin with if some recipes use that much, there's no leeway.

**Comment by combusterf** [comment]
Option 2 sounds like a good solution.
