### ISSUE TITLE
Bug or Oddly Worded Quest.  Flower Power - Crops / Flowers

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#8134]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
http://stonelegion.com
#
#### What did you try to do, and what did you expect to happen?
Right Click Crop Stick? Maybe with 4 of the same type of flowers?
#
#### What happened instead? (Attach screenshots if needed)
Nothing...
#
#### What do you suggest instead/what changes do you propose?
Right click the Crop Stick with Vanilla Flowers? Or just change the quest wording? 
#
#### What is your GTNH Discord username?
Kane Hart#6969

![image](https://user-images.githubusercontent.com/425853/123546235-be397680-d729-11eb-946a-889017c45f3e.png)

I also because I doubt this is how it works tried to plant actual flowers beside the crop sticks lol.. I mean that wording sounds like 4 flowers around a crop stick... Not sure if it was with or without crossbreeding haha...

![image](https://user-images.githubusercontent.com/425853/123546250-cbeefc00-d729-11eb-8d0d-499dc8ffa469.png)

![image](https://user-images.githubusercontent.com/425853/123546291-fe005e00-d729-11eb-86ef-b863a425cb93.png)

**Comment by Glease** [comment]
It means you need to hold at least 4 of these flowers and right click on an empty crop stick.

**Comment by KaneHart** [comment]
> It means you need to hold at least 4 of these flowers and right click on an empty crop stick.

I tried that. When you are in game next can you confirm?

**Comment by Glease** [comment]
2 minutes ago. It did work.

https://user-images.githubusercontent.com/4586901/123548544-bdd7c480-d797-11eb-9472-dc520ecaf949.mp4

**Comment by KaneHart** [comment]
Thanks, for sure working for you. This might be a issue with Thermos or a plugin. I will have to do more testing later. I will close this and make a new one if it's based on interaction, but I might as well just report it to the Crucible devs. 

Thank for checking Glease.

**Comment by boubou19** [comment]
it reminds me of this annoying bug happening sometimes on the officials for a couple of reboot then it fixes itself: you cannot plant any crop in the ow dim, but works in the other dims.

**Comment by Prometheus0000** [comment]
BTW, this is the _only_ crop that's like this. All the others only need 1 item.
