### ISSUE TITLE
AE Wireless Terminal doesnt link but works without losing power. 

### ISSUE THREAD

**Issue by EmrahKhan** [GTNewHorizons/GT-New-Horizons-Modpack#8135]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
I tried to link an AE Wireless Terminal to my network. 

#
#### What happened instead? (Attach screenshots if needed)
When i put AE Wireless Terminal inside the security terminal, it show as unlinked.
![image](https://user-images.githubusercontent.com/27235063/123547894-42601e00-d76b-11eb-991b-78037243b429.png)

I tried to use it and saw that it still works even it says unlinked. It also doesnt lose any power when i use it. (I dont have any wireless chargers)
![image](https://user-images.githubusercontent.com/27235063/123547967-910db800-d76b-11eb-8500-4c8f7264ae49.png)

#
#### What do you suggest instead/what changes do you propose?
I dont know if i'm doing something wrong but it seems to be a bug. Maybe you can look into it. 

#
#### What is your GTNH Discord username?
Emrah

**Comment by repo-alt** [comment]
Can't reproduce that in dev, must be mod interaction...

**Comment by repo-alt** [comment]
Well, it is WirelesCraftingTerminal behaviour, it does not drain power if creative or cheat mode is enabled

**Comment by EmrahKhan** [comment]
> Well, it is WirelesCraftingTerminal behaviour, it does not drain power if creative or cheat mode is enabled

Oh yeah, i have cheat mode enabled. That explains it. also it shows unlinked because of that?

**Comment by repo-alt** [comment]
Porbably, at least it is also only with WCT, and also in cheat mode
