### ISSUE TITLE
anchor don't seems to be working if 100% sealed

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#8138]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
delta 
#
#### What did you try to do, and what did you expect to happen?
I built a completely sealed cobblestone room Then put an anchor inside
anchor don't seems to be working if 100% sealed
![image](https://user-images.githubusercontent.com/59776356/123577359-42f9c280-d806-11eb-80af-7a9282c2a007.png)
![image](https://user-images.githubusercontent.com/59776356/123577371-48570d00-d806-11eb-93aa-ac93db917cc9.png)
You can see it won’t work if I seal it completely
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
is that how it work? I'm not so sure but I believe it is more like a bug
#
#### What is your GTNH Discord username?
Eason1134HK

**Comment by Prometheus0000** [comment]
I can confirm that this kind of thing happened to me before, though I have no idea why it's like this.
