### ISSUE TITLE
Innacurate "Wand Focus Dislocation" Quest

### ISSUE THREAD

**Issue by stinomichael** [GTNewHorizons/GT-New-Horizons-Modpack#8139]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
The quest for the dislocation focus states that it allows the user to move Aura Nodes.
#
#### What happened instead? (Attach screenshots if needed)
The focus can not move aura nodes. Other blocks move as intended.
#
#### What do you suggest instead/what changes do you propose?
Change description to say nodes can not be moved.
#
#### What is your GTNH Discord username?
negative

**Comment by MaxLunar** [comment]
Dislocation focus actually can move nodes, but only energized ones, because they dont allow regular wand charging. Probably needs some clarification (and tell player that moving such nodes leads to massive flux explosion).

**Comment by stinomichael** [comment]
It does say it can, but it's worded as it can move aura nodes & energized nodes. Should be changed to only say energized. Telling about the flux explosion would probably be a good idea too.

**Comment by Prometheus0000** [comment]
I was probably just thinking about the BM teleposer when I wrote the text.
