### ISSUE TITLE
updating to 2.1.1.0 causes a crash

### ISSUE THREAD

**Issue by Will118oganesson** [GTNewHorizons/GT-New-Horizons-Modpack#8140]
#### Which modpack version are you using?

2.1.0.0/2.1.1.0
#### What did you try to do, and what did you expect to happen?

I tried updating the modpack to 2.1.1.0. shouldn't have had any issues(crashes)
#### What happened instead? (Attach screenshots if needed)

When I loaded up the game it crashed. It is worth noting I deleted the dependencies.json as the version description told me to. I tried loading the game  with and without the file, same result.

#### What is your GTNH Discord username?
Will2021

**Comment by boubou19** [comment]
what's the source you used to get the packversion? and without logs we can't do anything so please give us at least the crash report.

**Comment by MotiasF33** [comment]
> 
> #### Which modpack version are you using?
> 
> 2.1.0.0/2.1.1.0
> #### What did you try to do, and what did you expect to happen?
> 
> I tried updating the modpack to 2.1.1.0. shouldn't have had any issues(crashes)
> #### What happened instead? (Attach screenshots if needed)
> 
> When I loaded up the game it crashed. It is worth noting I deleted the dependencies.json as the version description told me to. I tried loading the game with and without the file, same result.
> #### What is your GTNH Discord username?
> 
> Will2021

try download clientpack, unarchive it to new folder and move only your personal data, maps, etc from old client folder to new

**Comment by Will118oganesson** [comment]
how do i download clientpack in curse?

**Comment by boubou19** [comment]
curse is not yet updated (and has sometimes issues), either use the technic launcher or the clientpack in the announcements channel on discord.

**Comment by MotiasF33** [comment]
http://downloads.gtnewhorizons.com/ClientPacks/GTNewHorizonsClient-1.7.10-2.1.1.0.zip

**Comment by Will118oganesson** [comment]
ill try technic

**Comment by MotiasF33** [comment]
> 
> 
> ill try technic

nice
report the result

**Comment by Will118oganesson** [comment]
btw iss clientpack just the default daownload option?

**Comment by Will118oganesson** [comment]
it loaded correctly

**Comment by boubou19** [comment]
i'll close this then

**Comment by Will118oganesson** [comment]
k
