### ISSUE TITLE
2.1.1.0 random crash

### ISSUE THREAD

**Issue by Will118oganesson** [GTNewHorizons/GT-New-Horizons-Modpack#8141]
#### Which modpack version are you using?

2.1.1.0
#### What did you try to do, and what did you expect to happen?

I loaded my world after loading the pack. It shouldn't crash
#### What happened instead? (Attach screenshots if needed)

the game crashes every time after a short while

[crash-2021-06-28_13.05.25-client.txt] 
(https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6726090/crash-2021-06-28_13.05.25-client.txt)

#### What is your GTNH Discord username?
Will2021

**Comment by Will118oganesson** [comment]
i actually changed the gui scale and was wondering if that was the issue( it is currently set to normal)

**Comment by Will118oganesson** [comment]
i think its fine now

**Comment by boubou19** [comment]
then i'm closing this
