### ISSUE TITLE
NEI bee plugin tooltip/cursor offset error

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#8142]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Using the NEI plugin to plan future bee breeds
#
#### What happened instead? (Attach screenshots if needed)
The hot area for the breeding requirements markers was moved. Instead of showing up when hovering over percentage text, it now shows up when hovering roughly where the princess' crown is. This makes it a bit annoying to use since it overlaps with the bee item slot itself.
![image](https://user-images.githubusercontent.com/8459776/123683659-c6d69d80-d84c-11eb-9010-6af7294f03a6.png)
![image](https://user-images.githubusercontent.com/8459776/123683710-d7871380-d84c-11eb-91f4-6b1314c471a4.png)

Interestingly the other bee breeding tabs don't suffer from this problem.
#
#### What do you suggest instead/what changes do you propose?
The hot area should move back down where it was so it can more easily be accessed.

#
#### What is your GTNH Discord username?
Combuster

**Comment by Prometheus0000** [comment]
Already reported on the NEI repo
