### ISSUE TITLE
Unable to Interact wtih entities after dying near your respawn point

### ISSUE THREAD

**Issue by Shibva** [GTNewHorizons/GT-New-Horizons-Modpack#8146]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Singleplayer
#
#### What did you try to do, and what did you expect to happen?
I tried to interact wtih my mobs after I died __Close to my Respawn__ and I try to hurt other mobs and even try to get my dogs to sit up
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/38770780/123719541-d1defd00-d84f-11eb-9107-28c39ab310d0.png)
I am unable to interact with such in any way, the only interaction that is possible is if they interact with another entity (using bows allows for you to harm mobs that are in this state)
#
#### What do you suggest instead/what changes do you propose?
Idk, maybe try to find a way to fix this, this was noted in another pack I slaped together and I removed the 3-4 mods I added into this pack and the issue still presists. (Modifications: Optifine E7 Ultra was added and Hardcore Darkness was removed)
#
#### What is your GTNH Discord username?
Doge_9000
#
#### Steps to Reproduce
1. have your spawn point be not far from where you are, presumably maybe a chunk or 2 away or closer
2. Have some mobs that you can interact wtih (a contained hostlile, a Tamed pet (like a dog) and a villager
3. DIE!
4. Try to interact wtih mods that were near your respawn and death point ( if done correctly you will find that you are unable to interact with most of them if not all (regarding the Villager and The Tamed wolf)

This issue is guaranteed to resolve its self if you exit and rejoin the world and theres a possibility that it also resloves when the entices are reloaded after exiting the chunk they are loaded in

(NOTE: while you are unable to interact with them, they can still be pushed by your hitbox and even take damage form other mobs (even Tamed wolves that are affected still respond when you are attacked. You can test this also by using a bow as a mean to have another entity "interact" with the affected entity.

All mobs presumably under the living base are presumed to be affected as items are not affected by this)

**Comment by SteamDoge9000** [comment]
UPDATE: Can Confirm that when the chunk with sed entities are unloaded that they are fixed and can be interacted with once more when they are reloaded

This means that whatever issue is going on can be fixed if the entity is reloaded, maybe another mod can force any entites to reload when the player respawns wtihin X chuncks

**Comment by SteamDoge9000** [comment]
if it dosent work, try respawning with a bed

**Comment by SteamDoge9000** [comment]
For Visual Documentation of this Bug Please click this link

https://cdn.discordapp.com/attachments/401118216228831252/859247346977341461/2021-06-28_21-38-03.mp4

**Comment by SteamDoge9000** [comment]
More evidence for what might be going on

When I can interact with it, the Waila tab will show its information 
![image](https://user-images.githubusercontent.com/38770780/123726776-88e27500-d85e-11eb-85d7-afdd54db7bd1.png)

this is when I am unable to after I have died
![image](https://user-images.githubusercontent.com/38770780/123726798-93047380-d85e-11eb-9c1f-d8203facbe58.png)
It dosent register as an entity there

but like I have said, this issue seems to fix itself when the entity is unloaded and reloaded

**Comment by SteamDoge9000** [comment]
After running one more set of test and being disappointed in myself, I found the issue

apparently Optifine is doing something to cause this (E7 Ultra)

**Comment by SteamDoge9000** [comment]
It would be nice if somene could try to duct-tape over this issue

**Comment by SteamDoge9000** [comment]
"I had this issue without optifine: it's just the game not unloading the chunks because it knows you'll respawn here. So as a result, mobs are still loaded in memory, and sometimes, interaction issues are happening (on servers, they are mostly invisible mobs)."
-BouBou_19
