### ISSUE TITLE
Tinkers does not show alloys/craft

### ISSUE THREAD

**Issue by Volkoff96** [GTNewHorizons/GT-New-Horizons-Modpack#8148]
#### Which modpack version are you using?
/ClientPacks/GTNewHorizonsClient-1.7.10-2.1.1.0.zip
#
#### If in multiplayer; On which server does this happen? 
/ServerPacks/GTNewHorizonsServer-1.7.10-2.1.1.0.zip / Solo
#
#### What did you try to do, and what did you expect to happen?
Click on the alloy, all old versions showed alloys/how to make it, but 2.1.1.0-nope :( 
![TcNoSeeCraft](https://user-images.githubusercontent.com/73396969/123787218-fc829180-d8f3-11eb-86f1-2337cba9d73e.PNG)
#
#### What happened instead? (Attach screenshots if needed)
Not see how do it.

#
#### What do you suggest instead/what changes do you propose?
Return the visibility of crafting?
#
#### What is your GTNH Discord username?
Volkoff96

**Comment by Prometheus0000** [comment]
Known issue reported on the NEI repo.
