### ISSUE TITLE
Meteoric steel processing problem

### ISSUE THREAD

**Issue by simbiant** [GTNewHorizons/GT-New-Horizons-Modpack#8150]
#### Which modpack version are you using?
2.1.0.7
#
#### If in multiplayer; On which server does this happen? 
mine
#
#### What did you try to do, and what did you expect to happen?

I was trying to make meteoric steel ingot from meteoric iron dust, according to NEI, but it makes meteoric iron ingots instead
#
#### What happened instead? (Attach screenshots if needed)
![11](https://user-images.githubusercontent.com/24406976/123852757-594a7000-d925-11eb-9a09-cff0b9688aee.png)
![12](https://user-images.githubusercontent.com/24406976/123852765-5a7b9d00-d925-11eb-860f-1b7d119c344c.png)
![13](https://user-images.githubusercontent.com/24406976/123852766-5a7b9d00-d925-11eb-8564-322befff531d.png)
![14](https://user-images.githubusercontent.com/24406976/123852768-5b143380-d925-11eb-8431-a814e530c7b2.png)

#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
@SimbiAnT29

**Comment by Glease** [comment]
Can't reproduce. Make sure you don't have a config 1 circuit somewhere inside your EBF. Remember to check controller as well.
