### ISSUE TITLE
Fluid Terminal QOL Improvements

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#8151]
#### Which modpack version are you using?
2.1.0.7a
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happened instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
It would be nice if the fluid terminal matched the behavior of the ME terminal. Specifically:
* Setting to not auto-capture the typing cursor.
* Setting to syncronize with NEI.
* Setting to order fluid display by volume. (This helps keep the fluids that bounce around from being in the middle of the list).

Not sure if anyone else has anything to add to this?
#
#### What is your GTNH Discord username?
shawnbyday

**Comment by Szajkop** [comment]
Also, it usually fails to fill regular empty cells with fluid. But sometimes it works somehow.
With universal fluid cells (and the gt ones like steel fluid cell) the filling works all the time.
Also the emptying back in the system works all the time for both type of cells
