### ISSUE TITLE
GregTech AE2 Fluid Hatch?

### ISSUE THREAD

**Issue by shawnbyday** [GTNewHorizons/GT-New-Horizons-Modpack#8152]
#### Which modpack version are you using?
2.1.0.7a
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happened instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?
Is it possible to add a GregTech fluid output hatch similar to the GregTech AE item hatch for direct output into AE2? Not sure if along the same path or not but has this been considered for the input side as well?

#
#### What is your GTNH Discord username?
shawnbyday

**Comment by GTNH-Colen** [comment]
I'd rather not further encourage the hell that is fluid AE.

**Comment by shawnbyday** [comment]
Have any ideas for some alternatives? I don't like moving things around in cells and such. Can fluid logic/code be improved in any way to make it less terrible?

**Comment by Prometheus0000** [comment]
We're removing fluid AE, so it's all good.

**Comment by shawnbyday** [comment]
Ok, so forced moving around in cells? There any other option?

**Comment by Prometheus0000** [comment]
Pipes, conduits, ender tanks, ender link covers, fluid P2P tunnels are still around, probably others.

**Comment by Prometheus0000** [comment]
Apparently we're just disabling it for the servers.

@repo-alt you're the only one who would do this, are you going to, or not? If not, let's close this.

**Comment by repo-alt** [comment]
(Reopen if you find a volunteer)
