### ISSUE TITLE
Change draconic evolution particle generator to be gated at a more reasonable tier

### ISSUE THREAD

**Issue by Jimbno** [GTNewHorizons/GT-New-Horizons-Modpack#8154]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
The DE particle generator is currently is gated at (ZPM?) due to it needing a draconic core in it's recipe, a shame since this blocks gives some neat aesthetic options, my suggestion would be to gate it at a more reasonable tier like HV/EV.

#
#### What is your GTNH Discord username?
Jimbno

**Comment by ScriptedPiky** [comment]
The Draconic Core is actually gated at UV-UHV+ by virtue of the damn ancient quest chain that requires Pluto (UV-UHV~) to be visited. So anything DE related that requires a core, regardless of it being aesthetic or nearly useless (DE furnace) is unfortunately very far out.

**Comment by Jimbno** [comment]
That's what I'm saying change the particle emitter recipe so it doesn't require a core
