### ISSUE TITLE
PSA: Doggos Guide to Instaling Newer versions of GTNH on Curseforge Platforms for Dummies

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#8156]
Notice: This Issue is a Guide for installing for those that are having trouble updating their pack to newer versions of GTNH, but I as a curse user myself will give you step-by-step instructions on I believe you need todo in order for your pack to update.

1. Remove all the mods in the Mod Directory (save the ones that you added like Optifine, Dynamic Surroundings, etc.)
2. (optional but recommended) Clear out the Scripts Folder and the Config folder (again, save what configs you adjusted personally to prevent them from being reset if you changed any of them (Ie. Waila, Ingameinfo, etc) by moving them outside of he config folder temporarily
3. Update the pack
4. Run it once
4.5 (if the pack is refusing to start and a box keeps popping up after it updates, remove the Dependencies.Json temporarily (this is if the pack is still undergoing work for curseforge and serves as a troubleshoot step)
5. Add back the mods and configs you added back into their respected folders
6. Start pack again

7. if everything was done correctly, your pack should be updated and ready to play

8. Enjoy!

**Comment by Dream-Master** [comment]
I upload a new version so the dependencies.json not need to be deleted anymore.

**Comment by Prometheus0000** [comment]
Go post this kind of info on the wiki. This is for bug reports.
