### ISSUE TITLE
Inconsistent GT Fluid Pipe "Fluid Capacity"

### ISSUE THREAD

**Issue by vovaksenov** [GTNewHorizons/GT-New-Horizons-Modpack#8161]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
Capacity progression in most fluid pipes works like this:
Tiny - Small - Normal - Large - Huge, 
which (seems to be due to their costs in ingots) have relative capacities of
1 - 2 - 6 - 12 - 24. 
Example (Bronze fluid pipes): 400 - 800 - 2400 - 4800 - 9600
#
#### What happened instead? (Attach screenshots if needed)
Some of the materials do not adhere to this "rule":
- Trinium Naquadah Carbonite
- Staballoy
- Tantalloy (both)
- Void Metal
- Europium
- Potin
- Maraging Steel (both)
- Inconel (both)
- Hastelloy-X
- Tungsten
- Dark Steel
- Clay
- Lead

These follow linear progression (1 - 2 - 3 - 4 - 5), which makes little sense in relation to their material costs and encourages the use of many parallel small pipe pipelines. This is especially noticeable in early game with Potin pipes recommended by the Quest Book.
#
#### What do you suggest instead/what changes do you propose?
Correct the inconsistency.

**Comment by Prometheus0000** [comment]
Blame GT++

**Comment by Prometheus0000** [comment]
If there are any non-GT++ ones, mention them.

**Comment by Dream-Master** [comment]
No we can change that now. So not blame GT++. But indeed this are alot of GT++ pipes

**Comment by Prometheus0000** [comment]
I just checked the SS, they're ALL GT++.

**Comment by Dream-Master** [comment]
ok fine so we can change them in gt++ code so long we have obama.

**Comment by Prometheus0000** [comment]
I mean, the versions in obama yes, in gt++, I see no point.

**Comment by Dream-Master** [comment]
@Prometheus0000 are you know when it is released? if you can 100% sure with the next stable relase go ahead and change it nly in obama if not we need to change it maybe in both mods.

**Comment by Prometheus0000** [comment]
I just don't feel it's worth it for something so inconsequential, but if someone wants to, that's fine.

**Comment by Dream-Master** [comment]
btw @botn365 how far we are with project Obama ?
