### ISSUE TITLE
New Radon recipe is heavily plutonium positive (?)

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8166]
#### Which modpack version are you using?
2.1.1.0

#
#### If in multiplayer; On which server does this happen? 
delta

I had a quad LCR setup for radon running on the old recipe with the tiny dust.
I changed the setup by shutting down 3 of the LCRs and changing to the new recipe with uranium dust and 72 plutonium ingots.
After some days I checked the setup and found out the buffer chest for plutonium filled up.
I swapped the chest for an upgraded barrel, and after ~2 hours I found this:
![javaw_BF8bVBp76t](https://user-images.githubusercontent.com/17811922/124335753-a899d600-db9b-11eb-8a99-9575c6647e42.png)

Screenshots of the setup:
The LCR that is working is the right one in the screenshot

![javaw_QOUHbA0uWC](https://user-images.githubusercontent.com/17811922/124335798-d2eb9380-db9b-11eb-95f5-ddafba778e4c.png)
![javaw_WxC0QYmM65](https://user-images.githubusercontent.com/17811922/124335801-d4b55700-db9b-11eb-8145-6377e3d07b51.png)

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by Prometheus0000** [comment]
How would it be positive, the numbers are the same on both sides?
![image](https://user-images.githubusercontent.com/8517039/124337149-25628b00-db6f-11eb-87b3-df10d88ce992.png)

**Comment by Sphyix** [comment]
I don't know? I couldn't figure it out

**Comment by Prometheus0000** [comment]
It does not appear to be using the second stack of plutonium (8 left over) in the input.

**Comment by GlodBlock** [comment]
The LCR itemself forbids any recipe that contians more than 64 the same item.
see [https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/tileentities/machines/multi/GT_MetaTileEntity_LargeChemicalReactor.java#L105](url)
Theoretically such recipe shoulden't be executed by LCR. Maybe you should change the recipe.

**Comment by Prometheus0000** [comment]
I thought that might be the case, though I can't understand why, it's not like there isn't enough space.

**Comment by Glease** [comment]
The underlying code is not designed to work with multiple stack of same input

**Comment by Ethryan** [comment]
Maybe change input to blocks?

**Comment by Prometheus0000** [comment]
I'm just going to make it 8x, and use slightly more uranium.

**Comment by GTNH-Colen** [comment]
> I'm just going to make it 8x, and use slightly more uranium. I don't want people to have to do an extra step.

Have you tried making the item stack 72 instead of 64? I noticed Alk has some recipes like this that give out 100 odd items in a single stack which seem to function correctly.

**Comment by Glease** [comment]
LCR code has a few optimization lines that forbids such possibility.

**Comment by GTNH-Afx237v7** [comment]
Fixed already

**Comment by miozune** [comment]
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/588
