### ISSUE TITLE
Request: Add support for Iron Chest to TConsturct-GTNH

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#8168]
#### Which modpack version are you using?
2.1.1.0
#
#### Suggestion
make it so the Tconstruct table will allow to work with Iron Chest chests like it does in 1.12.2+
#
###Username
Doggo_9000

**Comment by Prometheus0000** [comment]
Duplicate of #7928
