### ISSUE TITLE
Inventory scanning essentia modified Thaumic Horizons syringes causes an instant crash to desktop.

### ISSUE THREAD

**Issue by Nrin123** [GTNewHorizons/GT-New-Horizons-Modpack#8169]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
mc.stonelegion.com
#
#### What did you try to do, and what did you expect to happen?
Using the thaumometer on my cursor to scan items in my inventory I moused over a Thaumic Horizons blood syringe modified with essentia and expected it to try and scan it.
#
#### What happened instead? (Attach screenshots if needed)
Upon mousing over the syringe my game crashed to desktop.
#
#### What is your GTNH Discord username?
Nrin#7237

**Comment by GTNH-Afx237v7** [comment]
Can you please provide a crashlog?

**Comment by Nrin123** [comment]
Here is the crash report.

[crash-2021-07-02_21.22.05-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6772880/crash-2021-07-02_21.22.05-client.txt)
