### ISSUE TITLE
EV Conveyor cant be crafted with normal Rubber in an Assembler

### ISSUE THREAD

**Issue by TrainerSnow** [GTNewHorizons/GT-New-Horizons-Modpack#8172]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Own
#
#### What did you try to do, and what did you expect to happen?
Tried to craft an EV Conveyor Module in an Assembler, using normal Rubber Sheets. 
#
#### What happened instead? (Attach screenshots if needed)
Won't work, cuz the assembler recipe Only accepts SB Rubber or Silicone Rubber, the crafting recipe also accepts the normal rubber.
#
#### What do you suggest instead/what changes do you propose?
Allow the Conveyor to also be crafted using normal Rubber in the Assembling Machine.
#
#### What is your GTNH Discord username?
TrainerSnow#5086

**Comment by boubou19** [comment]
I think it's intended to make you use the silicone rubber recipe instead.

**Comment by Dream-Master** [comment]
yes it is
