### ISSUE TITLE
Typewriter is uncraftable because it requires button groups.

### ISSUE THREAD

**Issue by AtomBlade** [GTNewHorizons/GT-New-Horizons-Modpack#8174]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Just a personal server for a friend and I.
#
#### What did you try to do, and what did you expect to happen?
I tried to craft a typewriter.
#
#### What happened instead? (Attach screenshots if needed)
The typewriter requires a "button group" to craft. The "button group" seems to be a disabled, uncraftable item, so the typewriter is currently not craftable.
![2021-07-03_12 08 05](https://user-images.githubusercontent.com/13388198/124360421-baa96200-dbf7-11eb-8dc3-b6119cfb3291.png)
#
#### What do you suggest instead/what changes do you propose?
Replace the Button Group item in the crafting recipe with something else.
#
#### What is your GTNH Discord username?
AtomBlade#9959

**Comment by Dream-Master** [comment]
i will check if they have a recipe otherwise i will add some

**Comment by BranTheBuildor** [comment]
This is still an issue in 2.3.0. Commenting to reopen

**Comment by boubou19** [comment]
2.3.0 is fairly old, can you try booting up if it's fixed in 2.3.6?

**Comment by miozune** [comment]
still issue in 2.3.6

**Comment by Dream-Master** [comment]
> #### Which modpack version are you using?
> 2.1.1.0
> 
> #### If in multiplayer; On which server does this happen?
> Just a personal server for a friend and I.
> 
> #### What did you try to do, and what did you expect to happen?
> I tried to craft a typewriter.
> 
> #### What happened instead? (Attach screenshots if needed)
> The typewriter requires a "button group" to craft. The "button group" seems to be a disabled, uncraftable item, so the typewriter is currently not craftable. ![2021-07-03_12 08 05](https://user-images.githubusercontent.com/13388198/124360421-baa96200-dbf7-11eb-8dc3-b6119cfb3291.png)
> 
> #### What do you suggest instead/what changes do you propose?
> Replace the Button Group item in the crafting recipe with something else.
> 
> #### What is your GTNH Discord username?
> AtomBlade#9959

it had a recipe as i add it in script maybe it got lost in recipes to script transition?
