### ISSUE TITLE
Stainless steel bee (HV material) is gated behind titanium bee (EV Material) 

### ISSUE THREAD

**Issue by Zeruel13** [GTNewHorizons/GT-New-Horizons-Modpack#8176]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Breed a stainless steel bee in HV but it requires a Titanium bee which is for EV materials
#
#### What happened instead? (Attach screenshots if needed)
Saw that in order to make a stainless steel bee, a titanium bee is needed. 
![image](https://user-images.githubusercontent.com/63512252/124368939-52c53c80-dc34-11eb-9f1b-e77bf06a78b4.png)
#
#### What do you suggest instead/what changes do you propose?
change the bee breeding tree such that the Titanium bee is made from the Stainless Steel bee. 

Below is just a suggestion to change the breeding tree:
Ruby + Aluminium = Chrome
Steel + Chrome = Stainless Steel
Stainless Steel + Aluminium = Titanium 

The quest line in Be(e) Breeding would also have to be updated to reflect these changes. 

#
#### What is your GTNH Discord username?
Zeruel13

**Comment by alphaNOVAircraft** [comment]
Bees need a proper rebanace at some point, most of them are not even close to being worth going for.
