### ISSUE TITLE
Client crash upon trying to open skystone chest

### ISSUE THREAD

**Issue by k3nw4y** [GTNewHorizons/GT-New-Horizons-Modpack#8177]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
craftersland
#
#### What did you try to do, and what did you expect to happen?
Tried to open skystone chest and client is instantly crashing, expected not to crash
#
#### What happened instead? (Attach screenshots if needed)
Log: https://paste.ee/p/RqukE
#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
k3nw4_y#7664

**Comment by Prometheus0000** [comment]
Try updating.

**Comment by k3nw4y** [comment]
my bad, im already on 2.1.1.0

**Comment by GTNH-Afx237v7** [comment]
Tried myself today, can’t reproduce though...

**Comment by brunyman** [comment]
yes, this should be closed was a local server issue

**Comment by GTNH-Afx237v7** [comment]
Issue author can close himself
