### ISSUE TITLE
Fix needed: Campfire lacks hardness and instantly brakes form a "Punch") [Adventure Backpack]

### ISSUE THREAD

**Issue by Shibva** [GTNewHorizons/GT-New-Horizons-Modpack#8178]
#### Which modpack version are you using?
2.1.1.0
#
#### Mod Version Number
1.7.10-0.9-h15-GTNH
#
#### What did you try to do, and what did you expect to happen?
for the campfire to not break when I mine it bear handed
#
#### What happened instead? (Attach screenshots if needed)
it breaks within a second of mining it with a bare hand and does not drop
#
#### What do you suggest instead/what changes do you propose?
add a hardness value to so it takes a bit longer to mine by hand (2-3 seconds? or the time it takes to break a log bear handed)
#
#### What is your GTNH Discord username?
Doggo_9000

**Comment by Prometheus0000** [comment]
Campfire? Was there such a block?

**Comment by SteamDoge9000** [comment]
![image](https://user-images.githubusercontent.com/38770780/124375494-7d34eb00-dc70-11eb-829a-45345b4279af.png)
Yes

**Comment by Prometheus0000** [comment]
https://github.com/GTNewHorizons/AdventureBackpack2/blob/d2337349ef38f63cddd04e9a5396b0b8f8b6f292/src/main/java/com/darkona/adventurebackpack/block/BlockCampFire.java#L33

**Comment by SteamDoge9000** [comment]
Thanks

**Comment by Prometheus0000** [comment]
? I didn't change anything, just point out where the code was.

**Comment by SteamDoge9000** [comment]
oh, strange though

**Comment by SteamDoge9000** [comment]
I was still able to punch it with a second
do you mind checking it in game

**Comment by Prometheus0000** [comment]
I confirmed this already. I dunno why it isn't stone hardness, but maybe it needs to be set explicitly.

Personally I don't really care enough to try changing it, as you could also say it's like this on purpose, and it isn't super important or anything.

**Comment by SteamDoge9000** [comment]
alight, if you want you can close the issue

**Comment by Prometheus0000** [comment]
Someone else might care enough to change it.

**Comment by glowredman** [comment]
Setting the Material does not set the hardness or blast resistance or anything like that (check the Material class to see what it does). Changing the hardness must be done by calling `setHardness()`
