### ISSUE TITLE
Strange issue, might be duplicate Arrows on Thaumnomicon are hard to notice

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#8179]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Sp
#
#### What did you try to do, and what did you expect to happen?
Try to locate where arrow are to change the tabs
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/38770780/124375265-5de98e00-dc6f-11eb-8f6b-434bfaed5942.png)
I missed it very easaly and found that if you select the Search Bar it lights up
![image](https://user-images.githubusercontent.com/38770780/124375282-75c11200-dc6f-11eb-9047-1b95cb2d091b.png)
This might be a bad interaction between the thaumcraft base and Witching gadgets adding the search bar
#
#### What do you suggest instead/what changes do you propose?
fix this lighitng issue so others dont make reports on the arrow tabs being missing
(note: [GTNH Faithful X32](https://github.com/Ethryan/GTNH-Faithful-Textures) and [Modded Faithful X32](http://f32.me/) is Present, add these if the issue cannot be reproduced)

#
#### What is your GTNH Discord username?
Doggo_9000

**Comment by Prometheus0000** [comment]
I don't have it open, but I don't remember having any problem getting to the next page.

**Comment by SteamDoge9000** [comment]
its just that it goes dark, or its kind of hard to notice because of it, I took me a minute for me to find it
but it might just be some texturepack issue with GTNH faithful x32 or with the other texture pack menchoned. thats just a hopeful guess

**Comment by SteamDoge9000** [comment]
Issue has been Corrected by @Glease as of Thaumcraft4Tweaks-1.3.5.jar
(thanks for responding to the issue and fixing this annoying visual ^w^)
Changelog:
1.3.5
Fix navigation button color (@70f842913ce4065 by Glease)

general code maintenance by IDE (@72867cdf7eaec69 by Glease)
