### ISSUE TITLE
OC keyboard recipe is not consuming all the buttons from the recipe

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8184]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
delta
#
![image](https://user-images.githubusercontent.com/12850933/124396999-67293800-dd0d-11eb-898d-59f4f899d9d3.png)

Only a stack is actually consummed. Might be the same reason as #8166

**Comment by Prometheus0000** [comment]
Same as #6803, but that's a good theory.
