### ISSUE TITLE
Placing the output bus in the ExxonMobil Chemical Plant will make it incomplete structure.

### ISSUE THREAD

**Issue by iouter** [GTNewHorizons/GT-New-Horizons-Modpack#8186]
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
--
#
#### What did you try to do, and what did you expect to happen?
build the ExxonMobil Chemical Plant
#
#### What happened instead? (Attach screenshots if needed)
incomplete structure
#
#### What do you suggest instead/what changes do you propose?
placing the output bus will make it incomplete structure.
#
#### What is your GTNH Discord username?
iouter

**Comment by Prometheus0000** [comment]
That's not nearly enough information. We didn't change it, so I'm going to say user error most likely.

**Comment by GlodBlock** [comment]
i have tested it on my PC and found there is no such bug in 2.1.1.0.
mayed you should follow the instrcution in gt++ manual. could you provide more information such as screenshots.

**Comment by iouter** [comment]
this is not a bug. after more testing, I found that it's the chemical plant would check the hatches amount. so this will cause some old structures to fail.

**Comment by iouter** [comment]
"10 machine casing in bottom layer at least" i suggest to add it to the tooltip/manual.
